### ISSUE TITLE
Tuya MCU light toggle 

### ISSUE THREAD

**Issue by wlatic** [esphome/issues#1000]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Bass.ii

**ESP (ESP32/ESP8266, Board/Sonoff):**

Esp8266
**Affected component:**
tuya MCU light (3 way switch)

**Description of problem:**
When the tuya MCU is used for a 3 way switch (rather than dimmer) a switch toggle happens on device restart/wifi reconnect. If the light is on the toggle is off, if the light is off the toggle is on.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: bedroomlight
  friendly_name: Bedroom Light
  icon: "mdi:lightbulb"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "***"
  password: "***"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroomlight Fallback Hotspot"
    password: "AQBamb13afiL"

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  level: none

# Enable Home Assistant API
api:

ota:

web_server:
  port: "80"


# My dimmer used the hardware serial port on the alternate pins
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

light:
  - platform: "tuya"
    name: "Bedroom Light"
    dimmer_datapoint: 2
    switch_datapoint: 1
    restore_mode: ALWAYS_OFF
    

```

**Logs (if applicable):**

```
N/A

```

**Additional information and things you've tried:**
Tried adjusting the dimmer and switch values without success.

**Comment by wlatic** [comment]
Have done testing using:
```
on_boot:
    priority: -1000.1
    then:
    - light.turn_off: bedroomlight
```
When flashing the light while its on the light will then turn off and then come back on just as the log says:
```
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.7.51: timed out). Re-Trying in 1 seconds
INFO Connecting to 192.168.7.51:6053 (192.168.7.51)
```
