### ISSUE TITLE
AddressableLight::write_state transitions not linear

### ISSUE THREAD

**Issue by mcd1992** [esphome/issues#1001]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Git dev branch [latest commit a55787f40caf11e8c7ed83aff76dd1205c5a50f6] in a python3 virtualenv

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 Generic

**Affected component:**

https://esphome.io/components/light/fastled.html or any other AddressableLight

**Description of problem:**
When using transition_length with an AddressableLight based light the effect will transition very quickly with little regard to the transition_length set. If you use a transition to go from 255 brightness to 1 brightness over 60 seconds it will fade very quickly and then eventually reach brightness 1 at about 30 seconds . If you go the other way from 1 brightess to 255 brightness over 60 seconds its even worse. It will sit at 1 brightness for about 15 seconds then jump to full brightness.

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: partition
    default_transition_length: 1s
    name: "Wake Lights"
    id: espwakelights
    segments:
      - id: espwakelight_left_lightbar
        from: 0
        to: 10
      - id: espwakelight_right_lightbar
        from: 0
        to: 10
  - platform: fastled_clockless
    default_transition_length: 1s
    chipset: WS2811
    pin: GPIO23
    num_leds: 10
    rgb_order: BRG
    name: "ESPWakeLight Left Lightbar"
    id: espwakelight_left_lightbar
  - platform: fastled_clockless
    default_transition_length: 1s
    chipset: WS2811
    pin: GPIO22
    num_leds: 10
    rgb_order: BRG
    name: "ESPWakeLight Right Lightbar"
    id: espwakelight_right_lightbar
```

**Logs (if applicable):**

```
N/A
The logs do show the proper transition time and everything being set on the ESP32.
The issue lies in the physical result.
```

**Additional information and things you've tried:**
I've been digging through the code a bit but I'm not familiar with the esphome codebase yet so it's still pretty foreign to me. I will eventually throw some debug prints into the AddressableLight::write_state and LightTransitionTransformer::smoothed_progress to see what the math is doing but for now I'm not sure how it works, but its definitely not linear like one would expect.

Related to commit: https://github.com/esphome/esphome/pull/750
