### ISSUE TITLE
MS5611 measurement errors

### ISSUE THREAD

**Issue by truglodite** [esphome/issues#1004]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
ESPhome 1.15.0dev, Hassos 3.8, hassio 0.104.3, pi3b+

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP12F module (esp8266), 5V usb-LM1117 powered

**Affected component:**
MS5611 i2c barometer

**Description of problem:**
Pressure measurements randomly jump up and down by 10 to 30hpa.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: garage
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    then:
      - switch.turn_off: beeper

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Fallback Hotspot"
    password: "password"

captive_portal:

# Enable logging to get dallas address
logger:
  
# Enable HA API
api:
  password: !secret garage_password
# Enable ota
ota:
  password: !secret ota_password

#define pirPin              13     // PIR output
#define dhtPin              12     // DHT sensor data pin (default io12)
#define dallasPin           14     // Dallas sensor data pin
#define sclPin              4      // i2c clock pin
#define sdaPin              5      // i2c data pin
#define beepPin             16     // Beeper signal

dallas:
  - pin: GPIO14
  
i2c:  
  sda: GPIO5
  scl: GPIO4

sensor:
  - platform: dallas
    index: 0
    resolution: 12
    accuracy_decimals: 1
    name: "Garage Temperature"
    id: celsius
    unit_of_measurement: "°F"
    filters:
      - lambda: return x * (9.0 / 5.0) + 32.0; # c to f
    
  - platform: dht
    pin: GPIO12
    model: DHT22
    humidity:
      accuracy_decimals: 0
      name: "Garage Humidity"
    update_interval: 60s
    
  - platform: wifi_signal
    name: "Garage WiFi Signal"
    update_interval: 60s
    
  - platform: ms5611
    address: 0x77
    temperature:
      name: "Garage Baro Temperature"
    pressure:
      name: "Garage Pressure"
      filters:
        - lambda: return x - 8.6; # calibration
        
  - platform: bh1750
    name: "Garage Luminance"
    address: 0x23
    update_interval: 10s

binary_sensor:
  - platform: status
    name: "Garage Status"
    
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT
    name: "Garage Motion"
    device_class: motion
    
switch:
  - platform: gpio
    name: "Garage Beeper"
    pin: GPIO16
    id: beeper
    icon: mdi:volume-low
    
  - platform: template
    name: "Garage Beeps 2"
    turn_on_action:
    - switch.turn_on: beeper
    - delay: 50ms
    - switch.turn_off: beeper
    - delay: 50ms
    - switch.turn_on: beeper
    - delay: 50ms
    - switch.turn_off: beeper
    
  - platform: template
    name: "Garage Beeps 3"
    turn_on_action:
    - switch.turn_on: beeper
    - delay: 50ms
    - switch.turn_off: beeper
    - delay: 50ms
    - switch.turn_on: beeper
    - delay: 50ms
    - switch.turn_off: beeper
    - delay: 50ms
    - switch.turn_on: beeper
    - delay: 50ms
    - switch.turn_off: beeper
    
  - platform: template
    name: "Garage Beeps 5"
    turn_on_action:
    - switch.turn_on: beeper
    - delay: 50ms
    - switch.turn_off: beeper
    - delay: 50ms
    - switch.turn_on: beeper
    - delay: 50ms
    - switch.turn_off: beeper
    - delay: 50ms
    - switch.turn_on: beeper
    - delay: 50ms
    - switch.turn_off: beeper
    - delay: 50ms
    - switch.turn_on: beeper
    - delay: 50ms
    - switch.turn_off: beeper
    - delay: 50ms
    - switch.turn_on: beeper
    - delay: 50ms
    - switch.turn_off: beeper

```

**Logs (if applicable):**

I posted graphs displaying the behavior here:
https://community.home-assistant.io/t/ms5611-going-bad-or-i2c-issue/164240/4

**Additional information and things you've tried:**
At first, I thought it was a 4 year old ms5611 that was just going bad. The sensor was running on the same esp device for a very long time with zero problems, using my own arduino code compiled with PIO. After switching to esphome, within a day these errors started to pop up. I swapped in a brand new ms5611, and the issue remains. I have also scoped out the i2c lines and verified decent looking traces (300/350ns rise time for sda/scl). I'm running at 50kHz only, so the 350ns should not be an issue.

I know from operating drones, that this baro is sensitive to sun light. The baro having issues is inside a dark enclosure (with no LED's nearby).

I lost the stackexchange link I read yesterday, where some folks were dealing with a very similar problem on an ms5611. Their debugging had not concluded, but they were focusing on the possibility that the ms5611 calibration prom data is not being read correctly. Not sure if this info will be of use, so figured I'd mention that.
