### ISSUE TITLE
PCF8574 only works when address is 0x20

### ISSUE THREAD

**Issue by bradphillips921** [esphome/issues#1014]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**
When connecting a PCF8574 to a Wemos D1 Mini or NodeMCU you can only use the address 0x20 on the pcf8574. Any other address and the ESP8266 board won't boot. I have tried with all address 0x21-0x27 as well as two different pcf8574 boards, two Wemos D1 Mini boards, and a NodeMCU board.

**Problem-relevant YAML-configuration entries:**
```yaml
# pcf8574 configuration entry
i2c:
  sda: D2
  scl: D1

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Forum topic I discussed this on
https://community.home-assistant.io/t/need-help-working-with-wemos-d1-mini-and-pcf8574-expansion-board/165995

**Comment by S-Przybylski** [comment]
Dear @bradphillips921 
i use seven PCF8574 on a Wemos D1 mini at the same time without any issue on the same pins 4=D2 and 5=D1 like you did!
Here is my configuration:

````
i2c:
  sda: 4
  scl: 5
  scan: True

pcf8574:
  - id: 'pcf8574_hub1'
    address: 0x20
    pcf8575: False

  - id: 'pcf8574_hub2'
    address: 0x21
    pcf8575: False

  - id: 'pcf8574_hub3'
    address: 0x22
    pcf8575: False

  - id: 'pcf8574_hub4'
    address: 0x23
    pcf8575: False

  - id: 'pcf8574_hub5'
    address: 0x24
    pcf8575: False

  - id: 'pcf8574_hub6'
    address: 0x25
    pcf8575: False

  - id: 'pcf8574_hub7'
    address: 0x26
    pcf8575: False

````
