### ISSUE TITLE
light.name is optional despite documentation stating Required

### ISSUE THREAD

**Issue by akasma74** [esphome/issues#1024]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
Sonoff RF

**Affected component:**
[light](https://esphome.io/components/light/binary.html)

**Description of problem:**
If `name` configuration variable of the `light` is omitted, there is no errors (despite it being Required) and the module works BUT there is no light entity in HA.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
output:
  - platform: gpio
    pin: GPIO12
    id: relay

light:
  - platform: binary
    id: ${device_id}
    #name: my light
    output: relay
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
