### ISSUE TITLE
CCT Dimming non-uniform brightness curve 

### ISSUE THREAD

**Issue by fluffymadness** [esphome/issues#1029]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**Affected component:**

https://esphome.io/components/light/index.html

**Description of problem:**
I have cct led-strips that go from 2700k-6000k and a quinled dimmer with esphome I'm using them with. 
When for example the strip has
10w on warm white
10w on cold white

Right now esphome gives me the following:

10w on 2700k
10w on 6000k
20w on ~4000k with double the brightness

Standard CCT dimmers like the milight FUT035 dimmer implement a uniform brightness curve for cct.
When I'm on ~4000k there the wattage of the strip turns down to 5w for both channels to also
give 10w in total on 4000k.

I'm using multiple rows of this strips in an aluminium profile that is rated for a specific wattage. So the strips can go too hot if the wattage output doubles at a different color temperature.
I did some reading in the esphomewiki and didn't really find an option i could activate to solve that issue.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
switch:
  - platform: gpio
    name: "Q1_Onboard light"
    pin: 2
output:
  - platform: ledc
    pin: 16
    frequency: 40000Hz
    id: LED_gpio_16
  - platform: ledc
    pin: 17
    frequency: 40000Hz
    id: LED_gpio_17
  - platform: ledc
    pin: 5
    frequency: 40000Hz
    id: LED_gpio_5
  - platform: ledc
    pin: 19
    frequency: 40000Hz
    id: LED_gpio_19
light:
  - platform: cwww
    name: "Oben"
    cold_white: LED_gpio_17
    warm_white: LED_gpio_16
    cold_white_color_temperature: 166 mireds
    warm_white_color_temperature: 370 mireds
    default_transition_length: 1s
  - platform: cwww
    name: "Unten"
    cold_white: LED_gpio_19
    warm_white: LED_gpio_5
    cold_white_color_temperature: 166 mireds
    warm_white_color_temperature: 370 mireds
    default_transition_length: 1s
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
