### ISSUE TITLE
Wrong order for lambda template sensor leads to "not declared in this scope" compile error

### ISSUE THREAD

**Issue by mvturnho** [esphome/issues#103]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

esphome on Windows

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESp8266
**Affected component:**

Template Sensor
https://deploy-preview-176--esphome.netlify.com/components/sensor/template.html

**Description of problem:**
When compiling the yaml with a lambda function in a Template sensor we receive a compile error.

The main.cpp shows that the template sensor lambda function is to refering to a sensor that has not yet been declared. So the Template sensor with lambda should be at the bottom of the file.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: test
  platform: ESP8266
  board: nodemcuv2
  esphome_core_version:
    repository: https://github.com/esphome/esphome-core.git
    branch: dev

# Enable logging
logger:
  level: DEBUG

ota:
  safe_mode: True
  password: VERYSECURE

binary_sensor:
  - platform: gpio
    pin: D3
    name: "Living Room Window"
    id: testgpio
    device_class: window
sensor:
  - platform: template
    name: "Template Sensor"
    lambda: |-
      if (testgpio->state) {
        return 200.0;
      }
      return 0.0;
    update_interval: 60s    
```

**Traceback (if applicable):**

```
$ esphome test-template-sensot.yaml compile
INFO Reading configuration...
INFO Generating C++ source...
WARNING Local changes in esphome-core copy from git. Will not auto-update.
INFO Compiling app...
INFO Running:  platformio run -d test
Processing test (platform: espressif8266@1.8.0; framework: arduino; board: nodemcuv2)

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz 80KB RAM (4MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.1.3
|   |-- <ESP8266WiFi> 1.0
|-- <Hash> 1.0
|-- <esphome-core> 1.12.0-dev #4a47742
|   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <ESPAsyncTCP> 1.1.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs\test\src\main.cpp.o
Compiling .pioenvs\test\lib037\ESP8266WiFi\WiFiServerSecureAxTLS.cpp.o
Compiling .pioenvs\test\lib037\ESP8266WiFi\WiFiServerSecureBearSSL.cpp.o
Compiling .pioenvs\test\lib037\ESP8266WiFi\WiFiUdp.cpp.o
Compiling .pioenvs\test\lib9e3\ESP8266mDNS\ESP8266mDNS.cpp.o
Compiling .pioenvs\test\lib400\ESPAsyncTCP_ID305\AsyncPrinter.cpp.o
Compiling .pioenvs\test\lib400\ESPAsyncTCP_ID305\ESPAsyncTCP.cpp.o
Compiling .pioenvs\test\lib400\ESPAsyncTCP_ID305\ESPAsyncTCPbuffer.cpp.o
src\main.cpp: In lambda function:
src\main.cpp:19:11: error: 'testgpio' was not declared in this scope
if (testgpio->state) {
^
Compiling .pioenvs\test\lib400\ESPAsyncTCP_ID305\SyncClient.cpp.o
Compiling .pioenvs\test\lib400\ESPAsyncTCP_ID305\tcp_axtls.c.o
*** [.pioenvs\test\src\main.cpp.o] Error 1
 [ERROR] Took 5.20 seconds

```

main.cpp
```cpp
// Auto generated code by esphome
// ========== AUTO GENERATED INCLUDE BLOCK BEGIN ===========
#include "esphome.h"
using namespace esphome;
// ========== AUTO GENERATED INCLUDE BLOCK END ==========="

void setup() {
  // ===== DO NOT EDIT ANYTHING BELOW THIS LINE =====
  // ========== AUTO GENERATED CODE BEGIN ===========
  App.set_name("test");
  App.set_compilation_datetime(__DATE__ ", " __TIME__);
  LogComponent *logcomponent = App.init_log(115200, 512, UART_SELECTION_UART0);
  logcomponent->set_global_log_level(ESPHOME_LOG_LEVEL_DEBUG);
  OTAComponent *otacomponent = App.init_ota();
  otacomponent->set_auth_password("VERYSECURE");
  otacomponent->start_safe_mode();
  sensor::TemplateSensor *sensor_templatesensor = App.make_template_sensor("Template Sensor", 60000);
  sensor_templatesensor->set_template([=]() -> optional<float> {
      if (testgpio->state) {
        return 200.0;
      }
      return 0.0;
  });
  binary_sensor::GPIOBinarySensorComponent *testgpio = App.make_gpio_binary_sensor("Living Room Window", 0);
  testgpio->set_device_class("window");
  // =========== AUTO GENERATED CODE END ============
  // ========= YOU CAN EDIT AFTER THIS LINE =========
  App.setup();
}

void loop() {
  App.loop();
}
```

**Additional information and things you've tried:**
