### ISSUE TITLE
CCS811 sensor doesn't save baseline

### ISSUE THREAD

**Issue by nicoolaro** [esphome/issues#1030]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASS.IO 
**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 Mini and CCS811 sensor board
**Affected component:**

https://esphome.io/components/sensor/ccs811.html?highlight=ccs811

**Description of problem:**

I followed guide from the KB, seems that for some reason baseline is not saved. I did set it in the code but readings are much higher. Also when i look at the logs seems that sensor is setting its own baseline each minute as per default .
**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: ccs811
    eco2:
      name: "CCS811 eCO2 Value"
    tvoc:
      name: "CCS811 Total Volatile Organic Compound"
    address: 0x5A
    baseline: 0x29BF
    update_interval: 60s
    temperature: roomtemp
    humidity: roomhumid

```

**Logs (if applicable):**

```
[12:20:54][D][ccs811:077]: Got co2=1799 ppm, tvoc=448 ppb, baseline=0x35BF
[12:20:54][D][sensor:092]: 'CCS811 eCO2 Value': Sending state 1799.00000 ppm with 0 decimals of accuracy
[12:20:54][D][sensor:092]: 'CCS811 Total Volatile Organic Compound': Sending state 448.00000 ppb with 0 decimals of accuracy
```

**Additional information and things you've tried:**

reboot
