### ISSUE TITLE
WaveShare e-paper 1.54in v2 display does not work 

### ISSUE THREAD

**Issue by Basanon** [esphome/issues#1032]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
ESPhome 1.14.3, Hassos 3.5, hassio 0.104.2, pi4

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32, Dev Module

**Affected component:**
Waveshare E-Paper Display 1.54in **v2**

**Description of problem:**
Display just shows nothing

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32test
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "X"
  password: "X"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.74
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "X"
    password: "X"

captive_portal:

# Enable logging
logger:
#  level: very_verbose
# Enable Home Assistant API

api:

ota:

# Example configuration entry
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

display:
  - platform: waveshare_epaper
    cs_pin: GPIO5
    dc_pin: GPIO17
    busy_pin: GPIO4
    reset_pin: GPIO16
    model: 1.54in
    full_update_every: 5
    lambda: |-
      it.fill(COLOR_OFF);
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Firs time I thought I have defected display module, since I have two of them, 2.9 and 1.54 size.
2.9 size display work just fine, 1.54 don't even blink. 
Tried many tests from GitHub, nothing happen. 
Then I contacted WaveShare, and they ask me "Does your module have a sticker with v2?" 
Yes, I have it. Then I found this example of code - [https://github.com/waveshare/e-Paper/tree/master/Arduino/epd1in54_V2](url), and finally, my 1.54in display start show picture like here [![](https://www.waveshare.com/w/thumb.php?f=1.54inch-e-paper-module-6.jpg&width=600)](url)
