### ISSUE TITLE
Remote Receiver truncates long signals

### ISSUE THREAD

**Issue by albertofustinoni** [esphome/issues#1037]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**Affected component:**

Remote Receiver

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
remote_receiver:
  pin:
    number: GPIO18
    inverted: yes
  dump: raw
  filter: 300us
  buffer_size: 65536
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

I am attempting to use the remote receiver on an ESP32 to dump codes for a couple of AC units, both of which use the Panasonic protocol, however:

- The built in component for Panasonic protocol is hard coded to support payloads 48 bits long
- Even when forcing raw dumps, only the initial part of the signal is actually recorded
- Increasing `buffer_size` in `remote_receiver` config  does not have any effect (I have it set to 65536, no change from default behavior)

According to the [the findings of a reverse engineering effort](https://www.analysir.com/blog/2014/12/27/reverse-engineering-panasonic-ac-infrared-protocol/) (which match my own observations when decoding the partial raw dumps), the signals can be up to 216 bit long after decoding.

Can this be fixed?

**Comment by glmnet** [comment]
Esphome will understand the code ends once the transmitter is idle by default 10ms. Check idle config and increase it.

**Comment by albertofustinoni** [comment]
I tried upping the idle time in config, but to no effect.
Here is what I have right now

```
remote_receiver:
  pin:
    number: GPIO18
    inverted: yes
  dump: all
  #filter: 200.0us
  idle: 100ms
  buffer_size: 64kb
```

And here is what the log says

```
[15:37:49][C][remote_receiver.esp32:055]:   Pin: GPIO18 (Mode: INPUT, INVERTED)
[15:37:49][C][remote_receiver.esp32:060]:   Channel: 0
[15:37:49][C][remote_receiver.esp32:061]:   Clock divider: 80
[15:37:49][C][remote_receiver.esp32:062]:   Tolerance: 25%
[15:37:49][C][remote_receiver.esp32:063]:   Filter out pulses shorter than: 50 us
[15:37:49][C][remote_receiver.esp32:064]:   Signal is done after 100000 us of no changes
```
