### ISSUE TITLE
dynamic component variables (This option is not templatable)

### ISSUE THREAD

**Issue by Bierchermuesli** [esphome/issues#1043]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** docker
**ESP (ESP32/ESP8266, Board/Sonoff):** wemos_d1_mini32
**Affected component:** tm1637 (from dev) and/or maybe others
**Description of problem:**
obiously it is not possible to use lambdas for component variables (probably not made for this?)
In this case I would like to change a component variable during runtime (display brightness). 

**Problem-relevant YAML-configuration entries:**
```yaml
display:
    platform: tm1637
    id: tm1637_display
    clk_pin: GPIO23
    dio_pin: GPIO05
    intensity: !lambda return id(brightness_value).state;
    ...
```

**Logs (if applicable):**
```
  This option is not templatable!.
  intensity: !lambda |-
    return id(brightness_value).state
```

**Additional information and things you've tried:**
globals vars won't work either
substitutions would work but can't be changed during runtime IMHO.

Any advice?
btw. tm1637 from current dev works great! Thanks!
