### ISSUE TITLE
Wifi AP mode IP address

### ISSUE THREAD

**Issue by jmigege** [esphome/issues#1051]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Esphome 1.14.3 via PIP

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**
Wifi AP mode

**Description of problem:**
wifi is in simple ap mode.
The ip address cannot be changed. 
In the conf.yaml file, manual_ip is specified. when ESP32 starts, it has the ip address 192.168.4.1 (Captive Portal). Ping is KO  the IP address of the conf file but is ok on the ip 192.168.4.1.
However, the captive portal is not active in conf. ESP starts always in Captive portail.
In addition, the API is disabled.

**Problem-relevant YAML-configuration entries:**
```yaml

esphome:
  name: esp
  platform: ESP32
  board: nodemcu-32s

wifi:
  ap:
    ssid: "Esp"
    password: "password"
    manual_ip:
      static_ip: 192.168.1.1
      gateway: 192.168.1.1
      subnet: 255.255.255.0

# Enable logging
logger:
api:
ota:
sensor:
  - platform: uptime
    name: "Uptime"
    update_interval: 60s

**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
