### ISSUE TITLE
ERROR Error binary size: Error: ESP does not have enough space to store OTA file

### ISSUE THREAD

**Issue by jperquin** [esphome/issues#1068]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hassos 3.11 / Hass.io 0.106 / ESPHOME 1.14.3

**ESP (ESP32/ESP8266, Board/Sonoff):**
platform: esp8266 / board: esp8285

# Enable over-the-air updates
ota:
-->

**Affected component:**
 

**Description of problem:**
After several succesful succesive OTA updates of these Gosund plugs (I have 7 in total), a recent OTA upload must have been so large that insufficient RAM is left over for a fresh firmware copy, resulting in this error:
`Creating BIN file "/data/gosund_plug_1/.pioenvs/gosund_plug_1/firmware.bin" using "/data/gosund_plug_1/.pioenvs/gosund_plug_1/firmware.elf"
========================= [SUCCESS] Took 16.91 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of gosund_plug_1.local
INFO  -> 192.168.30.144
INFO Uploading /data/gosund_plug_1/.pioenvs/gosund_plug_1/firmware.bin (333152 bytes)
ERROR Error binary size: Error: ESP does not have enough space to store OTA file. Please try flashing a minimal firmware (remove everything except ota)`

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: $devicename
  platform: esp8266
  board: esp8285
  arduino_version: recommended
#  arduino_version: latest
#  arduino_version: dev
  board_flash_mode: dout


# Enable over-the-air updates
ota:

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_pw
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Is there any way to create an even more minimalistic "recovery" firmware.bin so I do not have to go the USB route, which would be a real PITA given the fact that these plugs need soldering..
