### ISSUE TITLE
CS pin in SPI should be optional

### ISSUE THREAD

**Issue by igg** [esphome/issues#1071]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP8266, WeMos D1 Mini):**

**Affected component:**

https://esphome.io/components/spi.html

**Description of problem:**
With a single peripheral on the SPI bus, the peripheral's CS pin can be tied to ground, thus saving a pin on the board. Currently, it is not possible to define an SPI peripheral without a CS pin since this pin is required.

**Problem-relevant YAML-configuration entries:**
```yaml
spi:
  clk_pin: D5
  mosi_pin: D7
display:
  - platform: ssd1325_spi
    model: "SSD1325 128x64"
    id: dsply
    reset_pin: D0
#    cs_pin: D1
    dc_pin: D8
    lambda: |-
      it.print(0, 0, id(font), "Hello World!");
```
The above yaml results compilation error:
```
'cs_pin' is a required option for [display.ssd1325_spi].
```
Uncommenting the `cs_pin` line makes compilation work. Leaving the `D1` pin unconnected and tying the display's `CS` pin to ground works.

I have a working fix for this, and will update this comment with a pull request when its ready.
**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
