### ISSUE TITLE
on_boot i cannot get homeassistant.event to work

### ISSUE THREAD

**Issue by donnib** [esphome/issues#1073]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: smoke_kontor
  platform: ESP8266
  board: esp01_1m
  on_boot:
    then:
      - logger.log: "sending event"
      - homeassistant.event:
          event: esphome.event_test
          data:
            title: My event

```
but i also tried 
```yaml
esphome:
  name: smoke_kontor
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: -100
    then:
      - logger.log: "sending event"
      - homeassistant.event:
          event: esphome.event_test
          data:
            title: My event
```
but no matter what i do i don't get events in home assistant Developer tools -> Events and i listen to esphome.event_test however i do see the log "sending event" in the logs.

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by randybb** [comment]
Because it takes few seconds to get it connected to HA. Maybe you can try to add some [delay](https://esphome.io/guides/automations.html#delay-action) before your actions.

**Comment by donnib** [comment]
I don’t like delays, can it be done without delay, hooking up to an event when it is connected?

**Comment by randybb** [comment]
https://esphome.io/components/binary_sensor/status.html and then _on_state:_ is what you are looking for.

**Comment by donnib** [comment]
Thanks but I want the event on boot. How is that possible ?

**Comment by randybb** [comment]
There is nothing that would trigger an event after device has been rebooted and connected, but you can define lambda condition (https://esphome.io/guides/automations.html#lambda-condition) and do any complex decisions in automation - something like if status is changed to connected and uptime counter (https://esphome.io/components/sensor/uptime.html) is < 5 minutes, then it will fire your event. And sure, you can check status and uptime from HA perspective and have the logic in one place without relaying on configuration on ESPHome site.

**Comment by estebanz01** [comment]
I'm experiencing a similar behaviour with homeassistant.service. It does not get called. I added a `wait_until:` and `priority: -500` without success. Here's my `on_boot`:
```yaml
esphome:
  name: esp32cam
  platform: ESP32
  board: esp32cam
  on_boot:
    priority: -500
    then:
      - wait_until:
          api.connected:
      - logger.log: Api connected!
      - homeassistant.service:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.cameraon
      - logger.log: Homeassistant service called!
  on_shutdown:
    - logger.log: Turning off!
    - homeassistant.service:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.cameraon
```

Sometimes, the `on_shutdown:` works, sometimes it doesn't, but I'm not concerned about that one.
