### ISSUE TITLE
remote_transmitter - This platform has been removed in 1.13, please see the docs for updated instructions.

### ISSUE THREAD

**Issue by bcrowie** [esphome/issues#1074]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io 106 on Debian, atomic pi
**ESP (ESP32/ESP8266, Board/Sonoff):**

Nodemcu v1
**Affected component:**

https://esphome.io/components/remote_transmitter.html#remote-transmitter-transmit-raw-action

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```
remote_transmitter:
  pin: D4
  carrier_duty_percent: 50%

switch:
  - platform: remote_transmitter
    name: "TV Toggle"
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [9024, -4512, 564, -564, 564, -1692, 564, -1692, 564, -564, 564, -564, 564, -564, 564, -564, 564, -1692, 564, -1692, 564, -564, 564, -1692, 564, -564, 564, -564, 564, -564, 564, -564, 564, -564, 564, -1692, 564, -1692, 564, -1692, 564, -1692, 564, -564, 564, -564, 564, -564, 564, -564, 564, -564, 564, -564, 564, -564, 564, -564, 564, -1692, 564, -1692, 564, -1692, 564, -1692, 564, -43140]

```

**Logs (if applicable):**

```
INFO Reading configuration /config/esphome/switch.yaml...
Failed config

switch.remote_transmitter: [source /config/esphome/switch.yaml:32]
  
  This platform has been removed in 1.13, please see the docs for updated instructions.
  platform: remote_transmitter
  name: TV Toggle
  turn_on_action: 
    - remote_transmitter.transmit_raw: 
        code: 
          - 9024
          - -4512
          - 564
          - -564
          - 564
          - -1692
          - 564
          - -1692
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -1692
          - 564
          - -1692
          - 564
          - -564
          - 564
          - -1692
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -1692
          - 564
          - -1692
          - 564
          - -1692
          - 564
          - -1692
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -564
          - 564
          - -1692
          - 564
          - -1692
          - 564
          - -1692
          - 564
          - -1692
          - 564
          - -43140

```

**Additional information and things you've tried:**

I received the error saying the platform was removed in 1.13. I looked up said changes but found nothing. No changes to this platform were mentioned in any of the 1.13 changelogs.
