### ISSUE TITLE
Lambda parser finds id() s in c++ comments

### ISSUE THREAD

**Issue by fake-name** [esphome/issues#1087]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

```
odroid@odroid:~/Programming/ICScraper$ uname -a
Linux odroid 4.14.165-172 #1 SMP PREEMPT Wed Jan 15 20:20:27 -03 2020 armv7l armv7l armv7l GNU/Linux
odroid@odroid:~/Programming/ICScraper$ python3 --version
Python 3.6.9
odroid@odroid:~/Programming/ICScraper$ pip --version
pip 19.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
odroid@odroid:~/Programming/ICScraper$ esphome version
Version: 1.14.3
```

 

**Affected component:**

YAML parsing somewhere.

**Description of problem:**

Basically, from what I can tell, the `id()` directives in YAML lambdas are resolved by python code before compilation in a manner that's completely unaware of both YAML and C(++) comments. 

As such, if you have *commented out* `id(invalid_ref)` in a lambda, the code generation process fails.

**Problem-relevant YAML-configuration entries:**
```yaml
wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test"
    password: "testtest"

uart:
  - id: nextuart
    rx_pin: GPIO36
    tx_pin: GPIO4
    baud_rate: 9600


display:
  - platform: nextion
    uart_id: nextuart
    # full_update_every : 30
    lambda: |-
      it.set_component_text_printf("t22", "%.2f", 5);
      # // voff = voff + vstep;
      # // it.printf( 0, voff, id(display_font), "Input: %.1f V",    (input_voltage_sensor)       ->state);




```

**Logs (if applicable):**

```
1 odroid@odroid:~/Programming/ICScraper$ esphome test.yaml compile
INFO Reading configuration test.yaml...
Failed config

display.nextion:
  platform: nextion
  uart_id: nextuart

  Couldn't find ID 'display_font'. Please check you have defined an ID with that name in your configuration.
  lambda: !lambda |-
    it.set_component_text_printf("t22", "%.2f", 5);
    # // voff = voff + vstep;
    # // it.printf( 0, voff, id(display_font), "Input: %.1f V",    (input_voltage_sensor)       ->state);
  update_interval: 5s
```

The printf causing the error is commented out with both C++ AND YAML comments, and yet it still causes failures.

I'm not sure how YAML comments work in the lambdas, but I'd expect at least C comments to work properly. If there's a custom preprocessor that fiddles with the lambda content before it's passed to the C++ compiler, it should probably stop modifying a line after it hits a `//`.
