### ISSUE TITLE
Dallas Temperature Sensors stopped working after upgrading to 1.11.X branch

### ISSUE THREAD

**Issue by mannkind** [esphome/issues#109]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

MacOS: 10.14.3  
Python: 2.7.15  
Pip: 19.0.3  
ESPHome(yaml): 1.11.X 

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 Mini, and Sonoff S20

**Affected component:**

Dallas

**Description of problem:**

After upgrading from 1.10.1 -> 1.11.X (0,1,2 doesn't matter) my Dallas temperature sensors stopped working. 
Debug over MQTT says...
> [19:22:59][W][sensor.dallas:084]:   Found no sensors!

**Problem-relevant YAML-configuration entries:**
```yaml
dallas:
  - pin: GPIO3

# Individual sensors
sensor:
  - platform: dallas
    #name: "First Floor Temperature"
    name: "Temperature 008"
    address: 0x6804175194DEFF28
    filters:
      - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

Downgrading to 1.10.1 makes the temperature sensors work again.
I looked over the change log/documentation, but nothing stood out to me.
