### ISSUE TITLE
The Light Partition component doesn't respect 'color_correct' of its segments. 

### ISSUE THREAD

**Issue by 7h30n3** [esphome/issues#1091]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows 10
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**Affected component:**

https://esphome.io/components/light/partition.html

**Description of problem:**
The Light Partition component doesn't respect `color_correct` of its segments. 
I need to correct one of my lights, so they look nearly the same.  If I turn them one separately they have the same color, but if I turn on the light partition they differ.

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: partition
    name: "Partition Light"
    segments:
      - id: light1
        from: 0
        to: 31
      - id: light2
        from: 0
        to: 31
  - platform: fastled_spi
    id: light1
    chipset: WS2801
    data_pin: 32
    clock_pin: 33
    num_leds: 32
    rgb_order: RBG
    color_correct: [85%, 100%, 40%] 
    name: "${device_name} Light 1"
  - platform: fastled_spi
    id: light2
    chipset: WS2801
    data_pin: 26
    clock_pin: 27
    num_leds: 32
    rgb_order: RGB
    name: "${device_name} Light 2"

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
