### ISSUE TITLE
I can't flash esp32 through serial.

### ISSUE THREAD

**Issue by strumf666** [esphome/issues#1092]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**
 Wemos esp32pro

**Affected component:**

**Description of problem:**
I can't flash esp32 through serial (first flash).

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32_klet
  platform: ESP32
  board: lolin_d32_pro

wifi:
  ssid: "xxx"
  password: "yyy"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "aaa"

ota:
  password: "aaa"

i2c:
  sda: 21
  scl: 22
  scan: True
  
dallas:
  - pin: GPIO23

sensor:
  - platform: bme280
    temperature:
      name: "Klet Temperature"
      oversampling: 1x
    pressure:
      name: "Klet Pressure"
      oversampling: 1x
    humidity:
      name: "Klet Humidity"
      oversampling: 1x
    address: 0x77
    update_interval: 60s
  - platform: bh1750
    name: "Klet Illuminance"
    address: 0x23
    update_interval: 60s


```

**Logs (if applicable):**
Retrieving maximum program size /data/esp32_klet/.pioenvs/esp32_klet/firmware.elf
Checking size /data/esp32_klet/.pioenvs/esp32_klet/firmware.elf
DATA:    [==        ]  18.9% (used 61828 bytes from 327680 bytes)
PROGRAM: [========= ]  93.0% (used 1523406 bytes from 1638400 bytes)
Configuring upload protocol...
AVAILABLE: esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Use manually specified: /dev/ttyUSB0
Uploading /data/esp32_klet/.pioenvs/esp32_klet/firmware.bin
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32D0WDQ5 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: c8:2b:96:8c:34:5c
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 16MB
Flash params set to 0x0240
Compressed 15872 bytes to 10319...

Writing at 0x00001000... (100 %)
Wrote 15872 bytes (10319 compressed) at 0x00001000 in 0.3 seconds (effective 471.2 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 143...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (143 compressed) at 0x00008000 in 0.0 seconds (effective 2499.3 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...

Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 8861.0 kbit/s)...
Hash of data verified.
Compressed 1523520 bytes to 887063...

Writing at 0x00010000... (1 %)
A fatal error occurred: Failed to write compressed data to flash after seq 0 (result was C100)
*** [upload] Error 2
========================= [FAILED] Took 28.31 seconds =========================
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I tried turning almost all my wifi devices and other esp32 boards in case they would be making interference, but it didn't help, I tried 2 different cables, at least on used successfully in the past and I tried to flash one of my existing esp32 boards and still couldn't make it work.
