### ISSUE TITLE
Can't upload an OTA in ESP32

### ISSUE THREAD

**Issue by sermayoral** [esphome/issues#1100]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant 0.107.5
ESPHome 1.14.3 (release)

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**Affected component:**

https://esphome.io/components/ota.html

**Description of problem:**

I can't perform an OTA update. I have uploaded lots of firmware of this device but, suddenly, the OTA update does not work anymore. I have put a SSD1306 screen yesterday, after that i uploaded a firmware with the screen with success. Ten minutes later i fixed a problem with the screen (to show pzems data), but when i tried to upload the firmware again, i got this error. I tried many times without success. Today i have tried once again, but same result :-(

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: portero
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret nombre_wifi_1
  password: !secret passwd_wifi
  
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.36
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.30
    dns2: 8.8.8.8
  
  # Necesario establecer esta linea en el cambio de IP de *.37 a la nueva
  # use_address: 192.168.1.37
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Portero Fallback Hotspot"
    password: !secret passwd_esphome

captive_portal:

# Enable logging
logger:
  # Necesario si queremos usar UART0
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret passwd_esphome

# Habilita el acceso web al ESP
# web_server:
#   port: 80

ota:
  password: !secret passwd_esphome
  
binary_sensor:
  # Sensor para detectar llamada al porterillo
  - platform: gpio
    pin: 
      number: 18
      mode: INPUT_PULLUP
      inverted: True
    name: "Portero"
    device_class: sound
    filters:
      - delayed_on: 100ms
  # Boton de gestion de pantalla consumos
  - platform: gpio
    pin: 
      number: 25
      mode: INPUT_PULLUP
      inverted: True
    id: boton_gestion_pantalla
    on_press:
      then:
      - display.page.show_next: my_display
      - component.update: my_display

# Definimos la pantalla   
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: my_display
    pages:
      - id: pagina_apagado
        lambda: |-
          it.fill(COLOR_OFF);
      - id: pagina_general
        lambda: |-
          it.printf(63, 0, id(cabecera), TextAlign::TOP_CENTER, "GENERAL");
          it.printf(63, 15, id(cuerpo), TextAlign::TOP_CENTER, "%.1f W", id(pzem_general_power).state);
      - id: pagina_calefaccion
        lambda: |-
          it.printf(63, 0, id(cabecera), TextAlign::TOP_CENTER, "CALEFACCION");
          it.printf(63, 15, id(cuerpo), TextAlign::TOP_CENTER, "%.1f W", id(pzem_calefaccion_power).state);
      
# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

# Definimos las fuentes que iran en la pantalla
font:
  - file: 'fuentes/slkscr.ttf'
    id: cabecera
    size: 9
  - file: 'fuentes/BebasNeue-Regular.ttf'
    id: cuerpo
    size: 40

# Habilitamos el bus I2C para el control de la pantalla
i2c:
  sda: 21
  scl: 22
      
sensor:
  # Termometros
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:30:AF:2D
    temperature:
      name: "Temperatura 3"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 15 #3
            send_every: 3 #2
    humidity:
      name: "Humedad 3"
    battery_level:
      name: "Bateria Higrometro Peques"
  - platform: xiaomi_lywsd02
    mac_address: 3F:59:C8:63:38:99
    temperature:
      name: "Temperatura 4"
    humidity:
      name: "Humedad 4"
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:38:39:8E
    temperature:
      name: "Temperatura 5"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 15 #3
            send_every: 3 #2
    humidity:
      name: "Humedad 5"
    battery_level:
      name: "Bateria Higrometro Salon"
  # Pzem General
  - platform: pzemac
    modbus_id: bus_general
    current:
      name: "General Intensidad"
      internal: true
    voltage:
      name: "General Voltaje"
      internal: true
    power:
      name: "General Consumo Instantaneo"
      id: pzem_general_power
    frequency:
      name: "General Frecuencia"
      internal: true        
    power_factor:
      name: "General Factor Potencia"
      internal: true        
    update_interval: 30s
  # Pzem Calefaccion
  - platform: pzemac
    modbus_id: bus_calefaccion
    current:
      name: "Calefaccion Intensidad"
      internal: true      
    voltage:
      name: "Calefaccion Voltaje"
      internal: true      
    power:
      name: "Calefaccion Consumo Instantaneo"
      id: pzem_calefaccion_power
    frequency:
      name: "Calefaccion Frecuencia"
      internal: true      
    power_factor:
      name: "Calefaccion Factor Potencia"
      internal: true      
    update_interval: 30s
      
switch:
  - platform: gpio
    pin: 19
    id: portal_no_usar
  - platform: template
    name: "Portal"
    turn_on_action:
    - switch.turn_on: portal_no_usar
    - delay: 600ms
    - switch.turn_off: portal_no_usar
  - platform: gpio
    pin: 23
    name: "Zumbador"
    restore_mode: ALWAYS_ON
  
# Necesario para el PZEM
uart:
  - id: uart_general
    tx_pin: 1
    rx_pin: 3
    baud_rate: 9600
    stop_bits: 2
  - id: uart_calefaccion
    tx_pin: 17
    rx_pin: 16
    baud_rate: 9600
    stop_bits: 2
modbus:
  - id: bus_general
    uart_id: uart_general
  - id: bus_calefaccion
    uart_id: uart_calefaccion
```

**Logs (if applicable):**

```
INFO Reading configuration /config/esphome/portero.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/portero
Processing portero (board: esp-wrover-kit; framework: arduino; platform: espressif32@1.11.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
Dependency Graph
|-- <AsyncTCP-esphome> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.6
|   |-- <AsyncTCP-esphome> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <Wire> 1.0.1
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
Compiling /data/portero/.pioenvs/portero/src/main.cpp.o
Linking /data/portero/.pioenvs/portero/firmware.elf
Retrieving maximum program size /data/portero/.pioenvs/portero/firmware.elf
Checking size /data/portero/.pioenvs/portero/firmware.elf
Building /data/portero/.pioenvs/portero/firmware.bin
DATA:    [==        ]  18.9% (used 62068 bytes from 327680 bytes)
PROGRAM: [==========]  95.0% (used 1557106 bytes from 1638400 bytes)
======================== [SUCCESS] Took 190.58 seconds ========================
INFO Successfully compiled program.
INFO Connecting to 192.168.1.36
INFO Uploading /data/portero/.pioenvs/portero/firmware.bin (1557216 bytes)
Uploading: [=                                                           ] 2% 
ERROR Error sending data: [Errno 104] Connection reset by peer
```

**Additional information and things you've tried:**
