### ISSUE TITLE
Dallas Temperature Sensor error:found no sensors in ESP32

### ISSUE THREAD

**Issue by RewinKant** [esphome/issues#1101]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Home Assistant:
arch: aarch64
docker: true
hassio: true
os_name: Linux
os_version: 4.19.106-v8
python_version: 3.7.7
version: 0.107.5

**ESP (ESP32/ESP8266, Board/Sonoff):**
NodeMCU-32S ESP32 - error [AliExpress](https://aliexpress.ru/item/32864722159.html?spm=a2g0s.9042311.0.0.234733edwPgZ4E)
NodeMCU ESP8266 - test [AliExpress](https://aliexpress.ru/item/32656401198.html?spm=a2g0s.9042311.0.0.234733edwPgZ4E)

**Affected component:**
[Dallas Temperature Sensor](https://esphome.io/components/sensor/dallas.html)

**Description of problem:**
I couldn't connect this module to ESP32. I started looking for a problem in Dallas by dismantling it to the end. When I connected this module to the ESP8266, I realized that the sensor is working. So, in my opinion, there is an error in the ESPHome program or it does not work correctly. The photo below shows the comparative modifications of ESP32 and ESP8266. And a photo with the connected circuit.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test_esp32
  platform: ESP32
  board: nodemcu-32s
wifi:
  ssid: "Natali"
  password: "11197683"
  ap:
    ssid: "Test Esp32 Fallback Hotspot"
    password: "LN77gfxpxdNG"
captive_portal:
logger:
  level: DEBUG
api:
  password: "1234"
ota:
  password: "1234"

dallas:
  - pin: GPIO34
    update_interval: 5s
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
in photo
```
![ESP32 vs ESP8266_1](https://user-images.githubusercontent.com/49276527/77420317-869c9a00-6e15-11ea-848a-0e2471f0bda9.jpg)

**Additional information and things you've tried:**
module DS18B20 [AliExpress](https://aliexpress.ru/item/4000143479592.html?spm=a2g0s.9042311.0.0.234733edwPgZ4E)

Connection diagram:
![photo_2020-03-24_21-12-16](https://user-images.githubusercontent.com/49276527/77419398-10e3fe80-6e14-11ea-9f37-052455d8dd61.jpg)
![photo_2020-03-24_21-12-09](https://user-images.githubusercontent.com/49276527/77419452-248f6500-6e14-11ea-83e5-34df10cce172.jpg)
