### ISSUE TITLE
componen climate bang_bang don't work in mode heat or cool. (Source code that works bang_bang.cpp )

### ISSUE THREAD

**Issue by xheronimo** [esphome/issues#1104]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home assistant, docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32
**Affected component:**

**Description of problem:**
Component bang_bang don't work . Only in mode auto or off.
In mode heat or cool don't wor
Relays don't disable.
Y solve the problem to don't disable relays. But heat and cool modes behave like auto

**Problem-relevant YAML-configuration entries:**
```yaml
"node1.yaml"

sensor:
  - platform: dallas
    index: 0
    name: $Nombre_Sensor_01
    id: $Id_Sensor_01
    dallas_id: $Id_Hub_Sensor_01
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    resolution: 12
  - platform: gpio
    name: $Nombre_Salida_Calefaccion_01
    id: $Id_Salida_Calefaccion_01
    icon: $Icono_Id_Salida_Calefaccion_01
    restore_mode: ALWAYS_OFF    
    pin:
      mcp23008: mcp23008_hub_5
      number: 0
      mode: OUTPUT
  - platform: gpio
    name: $Nombre_Salida_Calefaccion_03
    id: $Id_Salida_Calefaccion_03
    icon: $Icono_Id_Salida_Calefaccion_03  
    restore_mode: ALWAYS_OFF 
    pin:
      mcp23008: mcp23008_hub_5
      number: 2
      mode: OUTPUT

climate:
  - platform: bang_bang
    sensor: $Id_Sensor_01
    id: $Id_Calefaccion_01
    name: $Nombre_Calefaccion_01
    visual:
      min_temperature: 12 °C
      max_temperature: 25 °C
      temperature_step: 0.1 °C

    default_target_temperature_low: 12 °C
    default_target_temperature_high: 22 °C
   
    heat_action:
      - switch.turn_on: $Id_Salida_Calefaccion_01
      - switch.turn_off: $Id_Salida_Calefaccion_03
    idle_action:
      - switch.turn_off: $Id_Salida_Calefaccion_01
      - switch.turn_off: $Id_Salida_Calefaccion_03
    cool_action:
      - switch.turn_on: $Id_Salida_Calefaccion_03
      - switch.turn_off: $Id_Salida_Calefaccion_01
        
"customize.yaml"
        - type: state-label
          entity: climate.nombre_calefaccion_01
          attribute: current_temperature
          suffix: ' ºC'
          style:
            top: 65%
            left: 22%
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
file
esphome/esphome/components/bang_bang/bang_bang_climate.cpp
[bang_bang_climate.zip](https://github.com/esphome/issues/files/4375334/bang_bang_climate.zip)

I think this problem is in return 
void BangBangClimate::compute_state_() {
  if (this->mode != climate::CLIMATE_MODE_AUTO) {
    // in non-auto mode
    this->switch_to_action_(static_cast<climate::ClimateAction>(this->mode));
//  return; THE PROBLEM TO SOLVED 
  }
Now the problem is that it either behaves like a shutdown or always like a car, I think because of the code that follows
