### ISSUE TITLE
remote_transmitter work Incorrect

### ISSUE THREAD

**Issue by nmweizi** [esphome/issues#1117]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip3 homeassistant  v0.107.4
**ESP (ESP32/ESP8266, Board/Sonoff):**

Processing fr (board: nodemcuv2; framework: arduino; platform: espressif8266@2.2.3)

**Affected component:**

https://esphome.io/components/remote_transmitter.html

**Description of problem:**
Unable to transmit nec code previously catched with receiver dump mode.

I want to send 'Power on/off' to TV, the protocol is an IR NEC, send with command/address, TV not power on or off.same JVC or LG

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: fr
  platform: ESP8266
  board: nodemcuv2


wifi:
  ssid: "xxxx"
  password: "xxxxx"
  reboot_timeout: 0s
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Asd Fallback Hotspot"
    password: "xxxxx"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxxxx"

ota:
  password: "xxxxx"


mqtt:
  broker: 192.x.x.x
  username: xxx
  password: xxxxx
  discovery: True
  discovery_retain: True
  reboot_timeout: 0s

remote_receiver:
  pin: 
    number: D1
    inverted: True
  dump: all

  #tolerance: 50%
  #filter: 250us
  #idle: 4ms
  buffer_size: 4kb


            
  
remote_transmitter:
  pin: D8
  
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%
  
switch:
  - platform: template
    name: "TC ON"
    assumed_state: True
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x4DB2
          command: 0x3BC4

```

**Logs (if applicable):**

```
[18:03:21][D][remote.jvc:048]: Received JVC: data=0x4DB2
[18:03:21][D][remote.lg:053]: Received LG: data=0x4DB23BC4, nbits=32
[18:03:21][D][remote.nec:068]: Received NEC: address=0x4DB2, command=0x3BC4

[17:26:47][D][switch:021]: 'TC ON' Turning ON.
[17:26:48][D][remote_transmitter:066]: Sending remote code...


```

**Additional information and things you've tried:**
If I use a simple code using tasmota, all is working using the NEC protocol.
```
00:09:06 MQT: tele/ir_65F543/RESULT = {"IrReceived":{"Protocol":"NEC","Bits":32,"Data":"0x4DB23BC4","DataLSB":"0xB24DDC23","Repeat":0}}
irsend {"Protocol":"NEC","Bits":32,"Data":"0x4DB23BC4","DataLSB":"0xB24DDC23","Repeat":0}
```
