### ISSUE TITLE
Bootloop and impossible to reflash

### ISSUE THREAD

**Issue by Kabron287** [esphome/issues#1121]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HomeAssistant Windows 10x64
**ESP (ESP32/ESP8266, Board/Sonoff):**

M5Stack
**Affected component:**

**Description of problem:**
After some time of properly work, bootloop occured.
Any flash-programmer could not determine flash size. 
Second flashed device run into bootloop immediately.
I'm afraid I bricked both devices. 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: switch
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: 'ASUS-YER'
  password: '***********'

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: '*******'

ota:
  password: '*******'

web_server:
  port: 8080

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      mode: INPUT_PULLUP
      inverted: True
    name: "Switch button"
    on_press:
      - switch.toggle: relay_1
  - platform: status
    name: "Switch Status"

switch:
  - platform: gpio
    name: "Switch Relay 1"
    pin: GPIO32
    id: relay_1

esp32_ble_tracker:

sensor:
  - platform: xiaomi_cgg1
    mac_address: 58:2D:34:36:83:1D
    temperature:
      name: "Xiaomi CGG1 Temperature"
    humidity:
      name: "Xiaomi CGG1 Humidity"
    battery_level:
      name: "Xiaomi CGG1 Battery Level"
     
```

**Logs (if applicable):**

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)                     
flash read err, 1000                                                            
ets_main.c 371                                                                  
ets Jun  8 2016 00:22:57

esphome-flasher output:

Using 'COM34' as serial port.
Connecting....
Detecting chip type... ESP32
Connecting....

Chip Info:
 - Chip Family: ESP32
 - Chip Model: ESP32D0WDQ6 (revision 1)
 - Number of Cores: 2
 - Max CPU Frequency: 240MHz
 - Has Bluetooth: YES
 - Has Embedded Flash: NO
 - Has Factory-Calibrated ADC: YES
 - MAC Address: 80:7D:3A:DB:FC:00
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
 - Flash Size: 4MB
 - Flash Mode: dio
 - Flash Frequency: 40MHz
Erasing flash (this may take a while)...
Unexpected error: Error while erasing flash: Timed out waiting for packet content

platformio output:

esptool.py v2.6
Serial port COM34
Connecting.....
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: 80:7d:3a:db:fc:00
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Warning: Could not auto-detect Flash size (FlashID=0xffffff, SizeID=0xff), defaulting to 4MB
Compressed 15872 bytes to 10319...

A fatal error occurred: Timed out waiting for packet content
```

**Additional information and things you've tried:**
