### ISSUE TITLE
ble_presence not showing as a tracker

### ISSUE THREAD

**Issue by TheWidowLicker** [esphome/issues#1124]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io on a Raspberry Pi 3 B+
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 (SeeKool)
**Affected component:**

ble_presence

**Description of problem:**
I have a watch by a company called Gligo.
I ahve set it up with ble_presence. I have put in it's MAC address and a name.
It appears in home assistant and is seen but instead of giving me the status of away etc.
I get on or off.
This means I am not able to add it as a tarcker for my person in home assistant.
I the mac address is not shown as RANDOM. It is shown as PUBLIC.

**Problem-relevant YAML-configuration entries:**
```yaml
# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

binary_sensor:
  - platform: ble_presence
    mac_address: 0C:61:CF:C6:DB:68
    name: "Adam's Gligo Watch"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
