### ISSUE TITLE
Several pzemac sensors do not work when connected to the same bus

### ISSUE THREAD

**Issue by ASL07** [esphome/issues#1139]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

I'm using the Version: 1.15.0-dev but I have also tried this with the latest release

Board is Wemos d1 
ESP8266
**Affected component:**

pzemac
https://esphome.io/components/sensor/pzemac.html
**Description of problem:**
Several pzemac sensors connected to the same uart bus, with different modbus adress for each sensor don't work

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: panel
  platform: ESP8266
  board: d1_mini

# Example configuration entry
uart:
  rx_pin: D1
  tx_pin: D2
  baud_rate: 9600
  stop_bits: 1

sensor:
  - platform: pzemac
    address: 1
    current:
      name: "Apartment 1 Current"
    voltage:
      # NOTE: Use this to force sending values even if they stay the same
      # force_update: true
      name: "Apartment 1 Voltage"
    power:
      name: "Apartment 1 Power"
    frequency:
      name: "Apartment 1 Frequency"
    power_factor:
      name: "Apartment 1 Power Factor"
    energy:
      name: "Apartment 1 Energy"
    update_interval: 30s

  - platform: pzemac
    address: 2
    current:
      name: "Apartment 2 Current"
    voltage:
      name: "Apartment 2 Voltage"
      # force_update: true
    power:
      name: "Apartment 2 Power"
    frequency:
      name: "Apartment 2 Frequency"
    power_factor:
      name: "Apartment 2 Power Factor"
    energy:
      name: "Apartment 2 Energy"
    update_interval: 30s

  - platform: pzemac
    address: 3
    current:
      name: "Apartment 3 Current"
    voltage:
      name: "Apartment 3 Voltage"
    power:
      name: "Apartment 3 Power"
    frequency:
      name: "Apartment 3 Frequency"
    power_factor:
      name: "Apartment 3 Power Factor"
    energy:
      name: "Apartment 3 Energy"
    update_interval: 30s

  - platform: pzemac
    address: 4
    current:
      name: "Apartment 4 Current"
    voltage:
      # force_update: true
      name: "Apartment 4 Voltage"
    power:
      name: "Apartment 4 Power"
    frequency:
      name: "Apartment 4 Frequency"
    power_factor:
      name: "Apartment 4 Power Factor"
    energy:
      name: "Apartment 4 Energy"
    update_interval: 30s

  - platform: pzemac
    address: 5
    current:
      name: "Apartment 5 Current"
    voltage:
      force_update: true
      name: "Apartment 5 Voltage"
    power:
      name: "Apartment 5 Power"
    frequency:
      name: "Apartment 5 Frequency"
    power_factor:
      name: "Apartment 5 Power Factor"
    energy:
      name: "Apartment 5 Energy"
    update_interval: 30s

  - platform: pzemac
    address: 6
    current:
      name: "Apartment 6 Current"
    voltage:
      force_update: true
      name: "Apartment 6 Voltage"
    power:
      name: "Apartment 6 Power"
    frequency:
      name: "Apartment 6 Frequency"
    power_factor:
      name: "Apartment 6 Power Factor"
    energy:
      name: "Apartment 6 Energy"
    update_interval: 10s

  - platform: pzemac
    address: 7
    current:
      name: "Apartment 7 Current"
    voltage:
      # force_update: true
      name: "Apartment 7 Voltage"
    power:
      name: "Apartment 7 Power"
    frequency:
      name: "Apartment 7 Frequency"
    power_factor:
      name: "Apartment 7 Power Factor"
    energy:
      name: "Apartment 7 Energy"
    update_interval: 30s
```

**Logs (if applicable):**

```

```

**Additional information and things you've tried:**

I have several pzemac sensor connected to the same uart (using pins D1 and D2), I am using a Wemos D1
Each of the pzem has a different modbus address
The pzem are wired in parallel to the Wemos D1 through a level converter 3.3v to 5v
I have tried using an external supply for the pzem bus, suspecting the wemos could not provide enough power, but it makes no difference

I have tested all the pzem individually, and they work well, whenever there is only one device in the bus
However, when I connect more than one pzem to the bus, it doesn't work, the Wemos doesn't boot up properly, and, both the TX and RX leds on the pzem are on continuously.

Has anyone had any success with a similar setup?
