### ISSUE TITLE
Configuration for Gosund sp111 v1.1 smart plug

### ISSUE THREAD

**Issue by martin3000** [esphome/issues#1146]
**Ubuntu**

Ubuntu 

**ESP8285**

ESP8285

**Affected component:**

Plug

**Description of problem:**
This is the yaml for flashing the Gosund SP111 v1.1 smart plug. It does not work for v1 or v1.4
In tasmota, it is this device: https://templates.blakadder.com/gosund_SP111_v2.html

After plugging in, wait 2 minutes. Then connect you mobile phone to the access point gosund-sp111 and navigate to 192.168.4.1 with the web browser. A page should appear where you can select you wifi network and you can enter your wifi password.

**Problem-relevant YAML-configuration entries:**
```yaml
#
# gosund sp111 smart plug with power sensor
#
esphome:
  name: gosundsp111
  platform: ESP8266
  board: esp8285

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "gosund-sp111"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable over-the-air updates
ota:

# Enable Web server
web_server:
  port: 80

sensor:
  # Power sensor
  - platform: hlw8012
    voltage_divider: 771
    current_resistor: 0.0012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 3
    update_interval: 3s
    # Current sensor
    current:
      name: current
      unit_of_measurement: A
      accuracy_decimals: 3
    # Voltage sensor
    voltage:
      name: voltage
      unit_of_measurement: V
      accuracy_decimals: 1
    # Power sensor
    power:
      id: power
      name: power
      unit_of_measurement: W
      accuracy_decimals: 0
      filters:
      - multiply: 0.5

binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    name: button
    pin:
      number: GPIO13
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  # Switch to toggle the relay
  - platform: gpio
    id: relay
    name: relay
    pin: GPIO15
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

output:
  # Relay state led
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO2
      inverted: true

light:
  # Relay state light
  - platform: monochromatic
    output: state_led
    id: led

# Uses the red LED as a ESPhome status indicator
status_led:
  pin:
    number: GPIO0
    inverted: true


```

**Logs (if applicable):**

**Additional information and things you've tried:**
