### ISSUE TITLE
MIC sensor, status fast change

### ISSUE THREAD

**Issue by Iv711** [esphome/issues#115]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

ESP8266. NodeMCU
**Affected component:**

https://esphome.io/components/binary_sensor/gpio.html

**Description of problem:**
Hi! (Im sorry for my English, this is all Google;))
I use the microphone sensor, but if the noise occurs and quickly subsides, the sensor status quickly changes off-on-off. Is it possible to make a status delay after triggering, so that the on status would remain at least 10 seconds?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
  - platform: gpio
    pin:
      number: D2
      inverted: True
    name: "Mic Kitchen sensor"
    device_class: sound
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
