### ISSUE TITLE
DEV: (new) IR remote (Daikin) component not working

### ISSUE THREAD

**Issue by HA-TB303** [esphome/issues#1150]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio 0.108.6 with the latest (rebuild) ESPHOME DEV version as available today.

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**

The component seems to send IR signals, but the Daikin AC is not responding to them. Someone else tried, with the same result: https://community.home-assistant.io/t/how-to-get-new-daikin-climate-component-working/185603

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: esp32_ir_daikin
  upper_devicename: ESP32 daikin

esphome:
  name: $devicename
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  power_save_mode: high
  # enable the fallback hotspot
  ap:
    ssid: $devicename
    password: "qwe12345"

captive_portal:
  
api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password
  
web_server:
  port: 80

logger:
  baud_rate: 0
  
remote_transmitter:
  pin: GPIO18
  carrier_duty_percent: 50%

climate:
  - platform: daikin
    name: "Airco living"
```
