### ISSUE TITLE
Property "name" in uptime sensor and wifi_signal sensor not working in ESP32

### ISSUE THREAD

**Issue by melwinek** [esphome/issues#1156]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 Mini and Wemos D1 ESP32 Mini

**Affected component:**

Wifi sensor and uptime sensor

**Description of problem:**
Property "name" in uptime sensor and wifi_signal sensor not working in ESP32

**Problem-relevant YAML-configuration entries:**
```
ESP 8266
--------------------
esphome:
  name: dmalypokoj
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "xxx"
  password: "yyy"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "zzz"

ota:
  password: "zzz"

sensor:
  - platform: uptime
    name: "Dol MPokoj Uptime"
    filters:
      - lambda: return x / 86400;
    unit_of_measurement: "days"
    accuracy_decimals: 2

  - platform: wifi_signal
    name: "Dol Mpokoj RSSI"
	
	
	
ESP 32
--------------------
esphome:
  name: kotlownia
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: "xxx"
  password: "yyy"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "zzz"

ota:
  password: "zzz"
  
  
sensor:
  - platform: uptime
    name: "Kotlownia uptime"
    filters:
      - lambda: return x / 86400;
    unit_of_measurement: "days"
    accuracy_decimals: 2

  - platform: wifi_signal
    name: "Kotlownia RSSI"
    update_interval: 60s

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
In attachements screenshots of screen with entities in HA

![s1](https://user-images.githubusercontent.com/10649327/79725656-d7ef5a80-82e9-11ea-9a18-e809751db951.jpg)
![s2](https://user-images.githubusercontent.com/10649327/79725658-d887f100-82e9-11ea-9446-1582fb90596a.jpg)
