### ISSUE TITLE
SGP30 Baseline readings are misplaced

### ISSUE THREAD

**Issue by keniji** [esphome/issues#1157]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266

**Affected component:**
SGP30

**Description of problem:**
According to [Issue 950](https://github.com/esphome/issues/issues/950), baseline readings are separated in an update: [SGP30](https://github.com/esphome/esphome/blob/dev/esphome/components/sgp30/sensor.py), and I am now using this update. However, after I set the baseline readings and get the new readings after 1 hour, I found the readings are "exchanged". For example, if I set:
````
eco2_baseline: 0xAAAA
tvoc_baseline: 0xBBBB
````
After 1 hour (the readings can be recalculated) I will see in log:
`Current eCO2 baseline: 0xBBBB, TVOC baseline: 0xAAAA`

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: sgp30
    baseline:
      eco2_baseline: 0x8BD9
      tvoc_baseline: 0x94F9
    eco2:
      name: aq_shb_bed_eco2
      id: sgp30_eco2
      accuracy_decimals: 1
    tvoc:
      id: sgp30_tvoc
      accuracy_decimals: 1
    address: 0x58
    update_interval: 30s
    compensation:
      temperature_source: aht10_temperature
      humidity_source: aht10_humidity
```

**Logs (if applicable):**
```
[03:39:42][D][sgp30:131]: External compensation data received: Humidity 53.75%
[03:39:42][D][sgp30:141]: External compensation data received: Temperature 26.14°C
[03:39:42][D][sgp30:150]: Calculated Absolute humidity: 13.159 g/m³ (0x0D28)
[03:39:42][I][sgp30:112]: Current eCO2 baseline: 0x94F9, TVOC baseline: 0x8BD9
```

**Additional information and things you've tried:**
In the environment above, I found the eCO2 baseline is getting smaller and TVOC's is larger, so I think the correct readings should be 0x8BD9 for eCO2 and 0x94F9 for TVOC?
