### ISSUE TITLE
Waveshare e-paper 2.7in display does not work

### ISSUE THREAD

**Issue by ukewea** [esphome/issues#1159]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome 1.15.0-dev

**ESP (ESP32/ESP8266, Board/Sonoff):**

[E-Paper ESP8266 Driver Board (by Waveshare)](https://www.waveshare.com/wiki/E-Paper_ESP8266_Driver_Board)

**Affected component:**

https://esphome.io/components/display/waveshare_epaper.html (`2.70in` to be specific)

**Description of problem:**
The display is filled with random pixels, not what I put into the DisplayBuffer.

**Problem-relevant YAML-configuration entries:**
```yaml
font:
  - file: "Arial.ttf"
    id: my_font
    size: 16

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  # I defined the MISO pin (though not connected) so hardware SPI will be used
  miso_pin: GPIO12

display:
  - platform: waveshare_epaper
    update_interval: 10s
    cs_pin: GPIO15
    dc_pin: GPIO4
    busy_pin: GPIO5
    reset_pin: GPIO2
    model: 2.70in
    lambda: |-
    it.printf(20, 120, my_font, "Hello world %d!", millis());
```

**Logs (if applicable):**

```
```

**Additional information and things you've tried:**
I've noticed that on the wiki page the 2.70in model is marked with `(not tested)`, so I downloaded the demo code from WaveShare and tried to figure out how they send buffer to the display. With some modification in the `waveshare_epaper.cpp` generated by ESPHome I actually made the display work properly, but I am not sure if my yaml configuration is done right.

Thanks.
