### ISSUE TITLE
set value for template Sensor

### ISSUE THREAD

**Issue by Heiner1967** [esphome/issues#1161]
the following sample code to set a value of a template sensor is givenas instruction and works fine:

`  - platform: template
    name: templatesensor_x
    id: x
    lambda: |-
      return 5.6;
    update_interval: 60s` 

If however I like now to write the 5.6 by way of a variable into the template Sensor
I would replace 

> return 5.6;
with
> return id(ch1s);
which is the name of a variable and defined here:
`globals:
  - id: ch1s
    type: float
    restore_value: false
    initial_value: "5.6"`

The code compiles but the template sensor does not have any value.
What am I doing wrong?
( At the end i even like to do some math to calculate a value, but I only get the code for a variable to work, but not transfered into the template Sensor
> 

DO NOT DELETE ANY TEXT from this template! Otherwise the issue may be closed without a comment.
-->

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
nodemcu-32s

**Affected component:**
https://esphome.io/components/sensor/template.html

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: watersystem
  platform: ESP32
  board: nodemcu-32s 

globals:
  - id: ch1s
    type: float
    restore_value: false
    initial_value: "5.6"

wifi:
  ssid: "xx"
  password: "xx"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:

  - platform: template
    name: x
    id: x
    lambda: |-
      return id(ch1s);
    update_interval: 60s

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
