### ISSUE TITLE
ESPHome light ignores white light transition time when, Home Assistant "light.turn_on" automation is call

### ISSUE THREAD

**Issue by levvvy** [esphome/issues#1169]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 mini
**Affected component:**

https://esphome.io/components/light/index.html

**Description of problem:**
When calling service:
```light.turn_on```
 with params:
```entity_id: light.fastledsk_light_2
rgb_color:
  - 0
  - 0
  - 0
white_value: 225
transition: 360
brightness:1
```
the white light transition takes time set in the ESPHome configuration, not 360 seconds given as service parameter, but RGB transition takes as set in config

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: neopixelbus
    variant: SK6812
    pin: GPIO3
    num_leds: 25
    type: GRBW
    name: "FastLEDsk Light"
    method: ESP8266_DMA

  - platform: monochromatic
    name: "Spoty"
    output: spot
    id: led_light
    default_transition_length: 1.5s

output:
  - platform: esp8266_pwm
    pin: D0
    frequency: 150 Hz
    id: spot
    inverted: True
    max_power: 1.00

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Related issue**
[#34426](https://github.com/home-assistant/core/issues/34426)
