### ISSUE TITLE
Neopixel White LED are independent / unable to TurnOff

### ISSUE THREAD

**Issue by Bierchermuesli** [esphome/issues#117]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Docker:
- ottowinter/esphomeyaml:latest --> Works like a charm...
- esphome/esphome:1.11.0 --> Neopixel does not work at all
- esphome/esphome --> White LED are independent
- esphome/esphome:dev -->White LED are independent

**ESP (ESP32/ESP8266, Board/Sonoff):**
- Wemos D1 Pro
- NodeMcu V2

**Affected component:**
- Neopixel

**Description of problem:**
When light.turn_off with home-assistant, all RGB LED's goes off as expected but the white LED's stays independent On with last `white_value`. Also, adjusting `brightness` does only affect RGB LED's

Only way to turn off the strip is to set `white_value` to `0` and then light.turn_off the light. 

Although I  liked to just have the (Warm-)White LED on - which is not possible otherwise (White LEDs are always dimmed in the other RGB `brightness`)... 

Same configuration with older Docker image worked  - so I assume its a neopixel bug

**Problem-relevant YAML-configuration entries:**
```
light:
    - platform: neopixelbus
      pin: GPIO3
      num_leds: 61
      name: "Chochi"
      variant: SK6812
      type: GRBW
      method: ESP8266_DMA
logger:
  baud_rate: 0
  level: debug
```
also tried with `GPIO2` and `ESP8266_UART1`

Thanks for everything!
