### ISSUE TITLE
failed to parse protocol - http

### ISSUE THREAD

**Issue by tiagofreire-pt** [esphome/issues#1175]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

PIP esphome-dev  

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**Affected component:**

```http_request```

**Description of problem:**

Error about the http url parsing.

**Problem-relevant YAML-configuration entries:**
```yaml
binary_sensor:
  - platform: esp32_touch
    name: "ESP32 Touch Pad GPIO27"
    pin: GPIO27
    threshold: 1000
    on_press:
      then:
        - http_request.post:
            url: http://online.oliveiradigital.net/user.php?cont=login&username=u123&password=u123&Submit=Login&md5=123
            verify_ssl: false  

```

**Logs (if applicable):**
```
[12:11:41][D][binary_sensor:036]: 'ESP32 Touch Pad GPIO27': Sending state ON
[12:11:41][E][HTTPClient.cpp:241] beginInternal(): failed to parse protocol
[12:11:41][E][HTTPClient.cpp:241] beginInternal(): failed to parse protocol
[12:11:41][W][http_request:032]: HTTP Request failed at the begin phase. Please check the configuration
```

**Additional information and things you've tried:**
Seems to come from here: https://github.com/espressif/arduino-esp32/blob/master/libraries/HTTPClient/src/HTTPClient.cpp#L139

I get this warning while compiling:

```
src/esphome/components/http_request/http_request.cpp: In member function 'const char* esphome::http_request::HttpRequestComponent::get_string()':
src/esphome/components/http_request/http_request.cpp:81:89: warning: function may return address of local variable [-Wreturn-local-addr]
 const char *HttpRequestComponent::get_string() { return this->client_.getString().c_str(); }
                                                                                         ^
src/esphome/components/http_request/http_request.cpp:81:81: note: declared here
 const char *HttpRequestComponent::get_string() { return this->client_.getString().c_str(); }
```
