### ISSUE TITLE
[HTTP-Client] failed connect, error(-1): connection refused

### ISSUE THREAD

**Issue by HebelHuber** [esphome/issues#1178]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

esphome running in Docker, built from github
influxdb running in Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, d1_mini

**Affected component:**

http_request

**Description of problem:**
http_request.post and http_request.send both return error(-1): connection refused

I am trying to write data to influxdb via http post request.
Doing so works from another machine with postman (exactly the same url).
the hostname gets resolved properly, log always looks the same.
See attached log.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  SSID: "SSID"
  PASS: "PASS"
  room: Office
  devicename: samplesensor
  logger_level: VERBOSE
  influxdbhostname: madhome
  influxdbhostport: "8086"
  influxdbname: InfluxDB

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini
  #arduino_version: 2.6.3
  
wifi:
  ssid: $SSID
  password: $PASS

# enable ota
ota:

# Enable logging
logger:
  level: $logger_level

# enable http requests
http_request:
  useragent: esphome/$devicename
  timeout: 5s
  
globals:
  - id: measureName
    type: String
  - id: measureValue
    type: String
  - id: payload
    type: String
  
# this is the "send to influxDB" script
script:
  - id: SendToInfluxDB
    then:
      if:
        condition:
          wifi.connected:
        then:
          - lambda: |-
              id(payload) = "$devicename";
              id(payload) = id(payload) + "_";
              id(payload) = id(payload) + id(measureName);
              id(payload) = id(payload) + ",host=";
              id(payload) = id(payload) + "$devicename";
              id(payload) = id(payload) + ",room=";
              id(payload) = id(payload) + "$room";
              id(payload) = id(payload) + " value=";
              id(payload) = id(payload) + id(measureValue);
          - logger.log:
              format: "PAYLOAD: %s"
              args: [ 'id(payload).c_str()' ]
          #- http_request.post:
              #verify_ssl: false
              #url: http://$influxdbhostname:$influxdbhostport/write?db=$influxdbname
              #headers:
                #Content-Type: text/plain
              #body: lambda |-
                #return id(payload)
          - http_request.send:
              method: POST
              url: http://$influxdbhostname:$influxdbhostport/write?db=$influxdbname
              headers:
                Content-Type: text/plain
              body: lambda |-
                return id(payload)
              verify_ssl: false
              
# This works from other devices:
# curl -i -XPOST 'http://madhome:8086/write?db=InfluxDB' --data-binary 'Temperature,host=MadWolf,room=Office value=0.64'

# Uptime sensor.
sensor:
  - platform: uptime
    name: $devicename Uptime
    update_interval: 60s
    on_value:
      then:
        - lambda: |-
            id(measureName) = "uptime"; id(measureValue) = String(x);
        - script.execute: SendToInfluxDB
```

**Logs (if applicable):**

```
[D][sensor:092]: 'samplesensor WiFi Signal': Sending state -82.00000 dB with 0 decimals of accuracy
[D][main:258]: PAYLOAD: samplesensor_wifi_signal,host=samplesensor,room=Office value=-82.00
[HTTP-Client][begin] url: http://madhome:8086/write?db=InfluxDB
[HTTP-Client][begin] host: madhome port: 8086 url: /write?db=InfluxDB
[HTTP-Client][sendRequest] type: 'POST' redirCount: 0
[hostByName] request IP for: madhome
[hostByName] Host: madhome IP: 192.168.178.118
[HTTP-Client] failed connect to madhome:8086
[HTTP-Client][returnError] error(-1): connection refused
[W][http_request:046]: HTTP Request failed; URL: http://madhome:8086/write?db=InfluxDB; Error: connection refused
[HTTP-Client][end] tcp is closed
```

**Additional information and things you've tried:**
I tried http_request.post and http_request.send method: POST, the result ist the same.
I tried using IP instead of hostname.
I tried using different framework versions.
I tried hardcoding url and payload.
Sending from another machine with postman or curl works.
Example:
```
curl -i -XPOST 'http://madhome:8086/write?db=InfluxDB' --data-binary 'Temperature,host=MadWolf,room=Office value=0.64'
```

There seems to be something similar in [http_request in dev branch is sending corrupted request #1040](https://github.com/esphome/issues/issues/1040), but i am not sure if it's the same issue.
It seems more like the packet is never leaving the board, as i couldn't find it with wireshark.
Also, since i built from github, this fix should be in already.
