### ISSUE TITLE
ds18b20 not recognized

### ISSUE THREAD

**Issue by fragolinux** [esphome/issues#118]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
esphome 1.11.2 as addon in hass.io on ubuntu 18.04, HA 0.89.1

**ESP (ESP32/ESP8266, Board/Sonoff):**
it's a witty board (it has integrated rgb led and 1 button and 1 ldr), i selected esp01_1m as board

**Affected component:**
ds18b20 dallas temperature sensor

**Description of problem:**
it cannot detect any sensor ("**[20:51:20][W][sensor.dallas:084]:   Found no sensors!**"), while on tasmota with "sensors" build it works without any issue... oh, even static ip does not work, i commented it out, on reboot it was still on previous dhcp address (different from the static one, which is out of the dhcp range)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: witty
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ....................
  password: ..................
#  manual_ip:
#    static_ip: 192.168.1.115
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0

logger:
  level: VERY_VERBOSE

api:
  password: ................

ota:
  password: ................

light:
  - platform: rgb
    name: "LED RGB"
    red: output_red
    green: output_green
    blue: output_blue

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO15
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13

web_server:
  port: 80

dallas:
  - pin: GPIO16

sensor:
  - platform: adc
    pin: A0
    name: "LDR"
    update_interval: 5s
#  - platform: dallas
#    name: "Temperatura"
#    index: 0
```

**Traceback (if applicable):**
```

```

**Additional information and things you've tried:**
as said, in tasmota it just works, on same pin (gpio16), i come from there and this is my 1st esphomized device...
