### ISSUE TITLE
Timer delay issue

### ISSUE THREAD

**Issue by tschechniker** [esphome/issues#1182]
Hi,

i currently have this timer setting:

```
time:
  - platform: sntp
    timezone: Europe/Berlin
    # ...
    on_time:
      - seconds: 0
        minutes: 0
        hours: 20
      # Every 5 minutes
      #- seconds: /5
        then:
          - switch.turn_on: beet_terasse
          - delay: 30min
          - switch.turn_off: beet_terasse
      - seconds: 0
        minutes: 0
        hours: 2
      # Every 5 minutes
      #- seconds: /5
        then:
          - switch.turn_on: rasen
          - delay: 30min
          - switch.turn_off: rasen
              
```

It worked all fine but i did an update (i don't know the version i used before) and now it turns on normaly but never turn off again. Did i miss something? 

Thanks for your help
