### ISSUE TITLE
Timer delay issue

### ISSUE THREAD

**Issue by tschechniker** [esphome/issues#1183]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Installed via Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

https://esphome.io/components/time.html

**Description of problem:**
It worked all fine but i did an update (i don't know the version i used before) and now it turns on normaly but never turn off again. Did i miss something?

**Problem-relevant YAML-configuration entries:**
```yaml
time:
  - platform: sntp
    timezone: Europe/Berlin
    # ...
    on_time:
      - seconds: 0
        minutes: 0
        hours: 20
      # Every 5 minutes
      #- seconds: /5
        then:
          - switch.turn_on: beet_terasse
          - delay: 30min
          - switch.turn_off: beet_terasse
      - seconds: 0
        minutes: 0
        hours: 2
      # Every 5 minutes
      #- seconds: /5
        then:
          - switch.turn_on: rasen
          - delay: 30min
          - switch.turn_off: rasen

```

**Logs (if applicable):**

```
[D][switch:021]: 'Bewässerung Rasen Terasse' Turning ON.
[D][switch:045]: 'Bewässerung Rasen Terasse': Sending state ON
```

**Additional information and things you've tried:**

I tried to reproduce the error with a smaller wait time. If you set it to 2 minutes for example it works. But not with 30 Minutes
