### ISSUE TITLE
internal flag does not work for status_led

### ISSUE THREAD

**Issue by abelmatser** [esphome/issues#1184]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant 108.9 (Hass.io)

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff S20, S26

**Affected component:**

status_led

**Description of problem:**
I can not add 'internal: true' flag to the configuration without breaking the dictionary at line 1 or having an unidentified error within status_led. I am trying to do this, because I do not think it is necessary for Home Assistant to control the lights of the switch (`light.sonoff_s26_1_green_led`)

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  plug_id: s26_1
  plug_name: Sonoff S26_1
  #https://esphome.io/guides/configuration-types.html#config-substitutions

esphome:
  name: sonoff_${plug_id}
  platform: ESP8266
  board: esp01_1m
  platformio_options:
    lib_deps: AsyncTCP@<1.1.0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

mqtt:
  broker: !secret mosquitto_ip
  username: !secret mosquitto_login
  password: !secret mosquitto_pass

# Enable logging
logger:

# Enable Home Assistant API
# api:

web_server:
  port: 80

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: $plug_name Button
    on_release:
      then:
        - switch.toggle: ${plug_id}_relay
  - platform: status
    name: $plug_name Status


switch:
  - platform: gpio
    name: $plug_name Relay
    pin: GPIO12
    id: ${plug_id}_relay
    
# Original
# status_led:
#   pin:
#     number: GPIO13
#     inverted: yes

# Try 1
status_led:
  - pin:
      number: GPIO13
      inverted: yes
    internal: true

# Try 2
# status_led:
#   pin:
#     number: GPIO13
#     inverted: yes
#     internal: true
```

**Logs (if applicable):**

```
INFO Reading configuration /config/esphome/sonoff_s26_1.yaml...
Failed config

status_led: 
  
  expected a dictionary.
  - pin: 
      number: GPIO13
      inverted: True
    internal: True
```

**Additional information and things you've tried:**
I tried to put the internal flag on different positions within status_led, but it did not work for me.

```
# Try 2
# status_led:
#   pin:
#     number: GPIO13
#     inverted: yes
#     internal: true
````
