### ISSUE TITLE
Upgraded to espHOME Connectivity issues

### ISSUE THREAD

**Issue by talk2dug** [esphome/issues#119]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

I have Docker running HA with HASSIO installed. Running on a mac mini with Debian 9.
**ESP (ESP32/ESP8266, Board/Sonoff):**

I have a mix of esp-01 esp32 and esp8285
**Affected component:**

No components. 

**Description of problem:**
Before the update, everything was working as expected. After the update, I can not add them to HA through the new configure ESPHome gui. It asks for the password, I supply it, and I can watch my ping just start timing out. This happens for ALL of my esp-01 and esp8285 devices, which I have many spread through out my house, and way up in in flood lights. 

I was OK with the delay in response I was experiencing, and even had my wife not complaining. And then the new update happened. Now my devices (that have the esp01) are no longer in my system, because i can't add them via the new config. 

As soon was i send the password, the pings start timing out, and then I get the incorrect password, which i assume is just a generic error message, because the password is right and used on the esp32s, which are rocking.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

esphomeyaml:
  name: flood_004
  platform: ESP8266
  board: esp8285

wifi:
  ssid: 'Sorrento2'
  password: '0000011111'
  manual_ip:
  # Set this to the IP of the ESP
    static_ip: 192.168.0.250
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
mqtt:
  broker: '192.168.0.142'
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: '********'

ota:
  password: '********'
switch:
  - platform: gpio
    name: "Flood 004"
    pin: GPIO12
    id: relay
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
My first round of troubleshooting was to move my Deco M5 WAPs around, thinking maybe it was a weak connection in the mesh. 
Then i found a forum that said the latest update to the M5s caused issues with ESPs and Raspberry Pis, so i put all three of them back to factory defaults, and set it back up. Same result.

So then I said EFF it and went to walmart and bought as brand spanking new google wifi mesh. Set it up, got all my 96 devices to show up, went to setup the remaining espHome devices, and yup, you guessed it....... ping of death.....

Ping times normally just sitting there not trying to talk to it, are great, between 6 and 40 avg. 

Updating the devices is going to be a huge pain in the ass, as a few of them are litterally 50' up inside a water proof and weather proof box for my flood lights. 

So, can we not use the must supply password and go back to pure MQTT?
