### ISSUE TITLE
How to filter out "unavailable" from binary sensor?

### ISSUE THREAD

**Issue by roc634** [esphome/issues#1197]
I connect a rain sensor to  a ESP32 board. I expect ONs and OFFs but I also receive a lot of "unavailable" randomly, which is annoying. I've tried the filter out method, 

```
binary_sensor:
  - platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: True
    name: "rain"
    id: rain_roof
    device_class: moisture
    filters:
      - delayed_on: 1000ms
      - filter_out: 'unavailable'
```

but it seems it doesn't work on binary sensor.

```
      Unable to find filter with the name 'filter_out'.
      filter_out: unavailable [source /root/roof.yaml:89]
```
and then I tried to use lambda, 

```
binary_sensor:
  - platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: True
    name: "rain"
    id: rain_roof
    device_class: moisture
    filters:
      - delayed_on: 1000ms
     - lambda: |-
         if (id(rain_roof).state != 'unavailable') {
           return x;
         } else {
           return {};
         }
```

but I don't know how to make it ignore "unavailable", and I got the following message. 

```
src/main.cpp:281:31: warning: character constant too long for its type
       if (rain_roof->state != 'unavailable') {
                               ^
src/main.cpp: In lambda function:
src/main.cpp:281:28: warning: comparison of constant '1633840229' with boolean expression is always true [-Wbool-compare]
       if (rain_roof->state != 'unavailable') {
```

Could you please help me with that? Thank you so much!!
