### ISSUE TITLE
Issue with Remote Transmitter and custom RCSwitch code

### ISSUE THREAD

**Issue by stich86** [esphome/issues#120]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 + FS1000A (315Mhz)
**Affected component:**

**Description of problem:**

i'm trying to use a Remote Transmitter part to open a gate. I'm successfully using rc-switch (with custom protocol) library with a simple sketch that works without problem. In my sketch i'm using code in decimal (no binary), but i've converted my dec 2 bin and still not works :(

**Problem-relevant YAML-configuration entries:**
```yaml

esphome:
  name: testesp01
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: 'XXXXX'
  password: 'XXXXX'

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'XXXXX'

ota:
  password: 'XXXXX'

remote_transmitter:
  pin: D1

switch:
  - platform: remote_transmitter
    name: "Cancello"
    rc_switch_raw:
      code: '00110000110011011001100011110000'
      protocol:
        pulse_length: 810
        sync: [4, 4]
        zero: [2, 2]
        one: [1, 1]
        inverted: False
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
