### ISSUE TITLE
Unable to transmit 433mhz RC Switch using FS1000A

### ISSUE THREAD

**Issue by ennetech** [esphome/issues#1203]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

hass.io in a Rpi3 but all config to the module is done via serial port
**ESP (ESP32/ESP8266, Board/Sonoff):**

https://esphome.io/devices/nodemcu_esp8266.html
**Affected component:**

https://esphome.io/components/remote_transmitter.html

**Description of problem:**
I am using a nodemcu board to create a 433mhz gateway, i managed to receive the codes (433mhz remote ac plugs) flawlessly but i cannot succeed in transmitting back, i've also set up an arduino to dump all the traffic on 433 but i cannot see the codes sent through esphome.

The module i am using for transmitting is a cheap FS1000A (tested working with an arduino) wired like this guide:
https://www.instructables.com/id/Using-an-ESP8266-to-Control-Mains-Sockets-Using-43/

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: bridge1
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: ""
  password: ""

captive_portal:

# Enable logging
logger:
  level: DEBUG
# Enable Home Assistant API
api:

ota:

remote_transmitter:
  pin: D1
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%

switch:
  - platform: template
    name: I-2-ON
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '10100110000001111011101000000000'
          protocol: 2      
  - platform: template
    name: I-2-OFF
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '10101110000001111011101000000000'
          protocol: 2   
```

**Logs (if applicable):**

```
[17:26:11][D][remote_transmitter:066]: Sending remote code...
[17:26:13][D][switch:021]: 'I-2-ON' Turning ON.
```

**Additional information and things you've tried:**
```
  - platform: template
    name: I-2-OFF
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '10101110000001111011101000000000'
          protocol: 2   
          repeat:
            times: 10
            wait_time: 500ms
```
