### ISSUE TITLE
Ina3221 wrong power value

### ISSUE THREAD

**Issue by sendorm** [esphome/issues#1206]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Homeasssistant ver 109.1 on Ubuntu 18.04 LTS python 3.7

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 nodemcu v3

**Affected component:**

https://esphome.io/components/sensor/ina3221.html

**Description of problem:**
The power values shown by the integration is 10 times more. I use the default shunt resistance of 0.1ohms. Only when I use a value of 1ohm the power values are correct. The ina board I am using has a shunt value of R100 (0.1ohms).

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: ina3221
    address: 0x40
    channel_1:
      shunt_resistance: 1 ohm
      power:
        name: "UPS 12V Power"
      bus_voltage:
        name: "UPS 5V Volt"    
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Changing the shunt value to 1ohm solved the misreading. Showing that the integration calculates wrongly.
