### ISSUE TITLE
Dual Oled Display on I2c Causes wifi to drop

### ISSUE THREAD

**Issue by thieaux** [esphome/issues#1210]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

When I2C bus is used with 2 ssd1306 wifi connection is dropped
**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266

**Affected component:**
https://esphome.io/components/display/ssd1306.html

**Description of problem:**
When 2 old ssd1306 displays with different addresses is used the wifi connection is dropped, using external power supply 2.5A....When displays are not connected board comes back online

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```esphome:
  name: kitchen
  platform: ESP8266
  board: d1_mini
 
switch:
  - platform: restart
    name: "Kitchen Restart"
wifi:
  ssid: "hassio"
  password: "xxxxxxxxxx"
  manual_ip:
    static_ip: 192.168.33.211
    gateway: 192.168.33.1
    subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen Fallback Hotspot"
    password: "xxxxxxxxxxxx"

captive_portal:

# Enable logging
logger:
  level: DEBUG
  logs:
    sensor: WARN

# Enable Home Assistant API
api:

ota:

i2c:
  sda: D1
  scl: D2

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3D
    lambda: |-
      it.print(0, 0, id(my_font), "this is D");
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(my_font), "This is C");    
font:
  - file: "Comic Sans MS.ttf"
    id: my_font
    size: 20

**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```INFO Reading configuration /config/esphome/kitchen.yaml...
INFO Starting log output from 192.168.33.211 using esphome API
INFO Connecting to 192.168.33.211:6053 (192.168.33.211)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.33.211: [Errno 113] No route to host). Re-Trying in 1 seconds
INFO Connecting to 192.168.33.211:6053 (192.168.33.211)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.33.211: [Errno 113] No route to host). Re-Trying in 1 seconds
INFO Connecting to 192.168.33.211:6053 (192.168.33.211)

**Additional information and things you've tried:**

change to external power supply, change sda clk pins. static ip 


<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
