### ISSUE TITLE
ttp229_bsf component (non i2c) requires i2c

### ISSUE THREAD

**Issue by rradar** [esphome/issues#1217]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
- hassio
- pip

**ESP (ESP32/ESP8266, Board/Sonoff):**
- esp8266, d1 mini

**Affected component:**
- [ttp229_bsf](https://esphome.io/components/binary_sensor/ttp229.html#ttp229-bsf-type) ("The pin-based version of the sensor, uses SDO+SCL pins.")

**Description of problem:**

The **non i2c version** (the ttp229-**bsf**-type) can't be compiled without i2c pins defined - despite having the sdo/scl pins set accordingly:

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  platform: ESP8266
  board: d1_mini
  name: $devicename

ttp229_bsf:
  sdo_pin: D0
  scl_pin: D1

logger:
  level: VERBOSE

binary_sensor:
  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 0"
    channel: 0

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 1"
    channel: 1

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 2"
    channel: 2

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 3"
    channel: 3

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 4"
    channel: 4

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 8"
    channel: 8

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 9"
    channel: 9

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 10"
    channel: 10

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 11"
    channel: 11

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 12"
    channel: 12

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 13"
    channel: 13

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 14"
    channel: 14

  - platform: ttp229_bsf
    name: "${upper_devicename} Channel 15"
    channel: 15

```

**Logs (if applicable):**

```yaml
Failed config

ttp229_bsf: [source ...]
  
  Component ttp229_bsf requires component i2c.
  sdo_pin: D0
  scl_pin: D1
```
**Additional information and things you've tried:**
