### ISSUE TITLE
ESP Home addon does not see the sensors anymore

### ISSUE THREAD

**Issue by pr0fetul** [esphome/issues#1218]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io version 0.109.6 in Docker 
**ESP (ESP32/ESP8266, Board/Sonoff):**
 ESP8266 - 2 boards - same behaviour

**Affected component:**
 The ESP home addon does not see the sensors anymore. This happens on 2 identical sensors. 

**Description of problem:**
The ESP home addon does not see the sensors anymore. I have checked the router - the sensors have static IP addresses. I have unplugged the sensors, replugged them - they show up in router under DHCP with static IP addresses, ESP does not see them. This is the error message from Show Logs:
`
INFO Reading configuration /config/esphome/bedroom_sensor.yaml...
INFO Starting log output from bedroom_sensor.local using esphome API
WARNING Error resolving IP address of bedroom_sensor.local. Is it connected to WiFi?
WARNING (If this error persists, please set a static IP address: https://esphome.io/components/wifi.html#manual-ips)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error resolving IP address: Error resolving address with mDNS: Did not respond. Maybe the device is offline., [Errno -2] Name or service not known). Re-Trying in 1 seconds
`
The sensors worked fine with this version of HA until last night - this morning the communication "died" . 

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: bedroom_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "xxxx"
  password: "yyyy"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "bedroom_sensor"
    password: "zzzzzz"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  sda: D2
  scl: D1
  scan: True

sensor:
#WiFi Sensor for the NodeMCU
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
    filters:
      - lambda: |-
          if (x <= -100) {
            return 0;
          } else if (x >= -50) {
            return 100;
          } else {
            return (2 * (x + 100));
          }
    unit_of_measurement: "%"

#UpTime sensor for the NodeMCU
  - platform: uptime
    name: Uptime Sensor
    filters:
      - lambda: |-
          return x / 3600;
    unit_of_measurement: "Hours"

#Light Sensor:
  - platform: bh1750
    name: "Bedroom Luminosity"
    address: 0x23
    update_interval: 60s
    icon: "mdi:brightness-6"

#Temperature Humidity and Pressure Sensor:
  - platform: bme280
    temperature:
      name: "Bedroom Temperature"
      oversampling: 16x
      id: temperature
    pressure:
      name: "Bedroom Pressure"
    humidity:
      name: "Bedroom Humidity"
      oversampling: 16x
      id: humidity
    address: 0x76
    update_interval: 60s

#Air Quality Sensor:
  - platform: ccs811
    eco2:
      name: "Bedroom eCO2 Value"
    tvoc:
      name: "Bedroom Total Volatile Organic Compound"
    address: 0x5A
    update_interval: 60s
    baseline: 0x4481
    temperature: temperature
    humidity: humidity

#Text sensor for the NodeMCU
text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ssid:
      name: xxxxxx
    

#Reboot Switch for the NodeMCU
switch:
  - platform: restart
    name: "NodeMCU Restart"




```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by aptonline** [comment]
Seeing a similar issue in 0.110.1 and latest ESPHome. I believe it’s an mdns issue of some description.

**Comment by meichthys** [comment]
I'm also seeing this in 0.111.4
All of my EspHome sensors are now offline. I did add a network interface to homeassistant, so it's possible that caused an issue for me.

**Comment by glmnet** [comment]
It happened to me yesterday that a node got disconnected, never had an issue with it. Looked ok via ping and remote logs. Restarting HA solved the issue, what steps are you taking to bring the node back online?

**Comment by meichthys** [comment]
Restarting HA didn’t help for me. I also tried reinstalling The ESPhome addon but that hasn’t worked. I’ve seen some other issues that mention that it is an issue with using a reverse proxy, but even accessing it locally doesn’t seem to help for me. I’ve had this happen once or twice in the past and it seemed to fix itself (maybe it was a router reboot or something network related).

**Comment by bmbouter** [comment]
I am also experiencing this issue. I don't think it's related to Hass version as much as the ESPhome itself from 1.14.3 ➡️1.14.5. I believe the significant symptom is that the devices themselves are no longer maintaining their same hostnames or not responding to mDNS somehow. Hass couldn't interfere with this, and here's why I believe that.

My network supports mDNS, I can from a computer on the LAN ping those mDNS names, so that is working fine. What isn't working is pinging these devices showing "offline". These connections would be between my computer <-> Wifi <-> switch <-> Wifi <-> esphome_device. Hass wouldn't be involved.

Interestingly, hass established connections with these devices and I can still control them! So really what isn't working is the mDNS part (as described here by others also). To restate what is working, if I connect to the logs port for example by IP address directly the device is actually online and working. If I try to connect to the device by mDNS it does not...

I've been using this setup for 12ish months rock solid. About 10 days ago I updated from 1.14.3 ➡️1.14.5, rebuilt my code for all devices and pushed (big mistake). Now all of them show offline. They come online for a few minutes when I restart them. Something between 1.14.3 and 1.14.5. in the client code has regressed this. I use 8266 deices (mix of nodemcu's and sonoffs).

**Comment by meichthys** [comment]
^This. 
@bmbouter great summary. 
One thing to add: I've noticed that if you create a device with a static IP address it will still show as online - further supporting the idea that it seems like an mDNS issue.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I think I also have this problem: https://community.home-assistant.io/t/esphome-device-says-connected-successfully-is-sending-sensor-data-but-appears-completely-offline-in-home-assistang-no-mqtt/214025

**Comment by bmbouter** [comment]
> I think I also have this problem: https://community.home-assistant.io/t/esphome-device-says-connected-successfully-is-sending-sensor-data-but-appears-completely-offline-in-home-assistang-no-mqtt/214025

The symptoms you describe are different. You can push firmware, but with mDNS not working I cannot. Also I cannot show the logs because of mDNS issue, but it sounds like you can.

Perhaps they are the same, but the symptoms sound different from the description.

**Comment by PedroLamas** [comment]
Seeing this issue myself, only noticed yesterday after I rebuilt and re-deployed one of my nodes... after that mDNS for that node (ESP8266) stopped showing up...

**Comment by Tokn59** [comment]
Same problem here but I was able to add new sensors through configuration - ESPHome - and then adding the node with it's IP address .... No automatic discovery ...

**Comment by OttoWinter** [comment]
Not sure what this is, and haven't been able to reproduce on my testing RPi 3b+ Hass.io arm64v8 system.

Might be related to the supervisor now having its own mDNS listener. The fact that this appears to be semi-random makes that less likely though.

**Comment by PedroLamas** [comment]
@OttoWinter I for one don't think this has got anything to do with Hass.io integration!

Using my Network Analyzer app in my Android phone, I can't see any mDNS announcement from my ESP8266 node, yet I do see for everything else on the network (both wired and wireless devices appear fine)

**Comment by h0jeZvgoxFepBQ2C** [comment]
I also don't have a supervisor afaik (native linux installation).

**Comment by PedroLamas** [comment]
Actually, now that you mention that, I too am not using Hass.io Supervisor! My install is everything under docker, attached to the host network.

Here's my node config just in case:

```yaml
esphome:
  name: testnode
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  fast_connect: true
  reboot_timeout: 3min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testnode Fallback Hotspot"
    password: !secret wifi_ap_password

sensor:
  - platform: pulse_counter
    pin: GPIO12
    unit_of_measurement: 'kW'
    name: 'Power Meter'
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 1000us
    filters:
      - multiply: 0.075
    id: my_power
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: my_power

time:
  - platform: sntp
    id: my_time

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
```
