### ISSUE TITLE
Internal flag not properly set for binary sensor

### ISSUE THREAD

**Issue by SimonO93** [esphome/issues#1224]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Esphome Version: 1.14.3

binary sensor

Cannot change flag internal of binary_sensor, whatever is set element is not visible in Home Assistant

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
    name: test
    platform: ESP8266
    board: d1_mini_lite
    build_path: target/test

binary_sensor:
  - platform: gpio
    id: bs_1
    name: "test bs1"
    internal: true
    pin:
      number: D0
  - platform: gpio
    id: bs_2
    name: "test bs2"
    internal: false
    pin:
      number: D1

switch:
  - platform: gpio
    id: sw_1
    name: "sw_1"
    internal: true
    pin:
      number: D0
  - platform: gpio
    id: sw_2
    name: "sw_2"
    internal: false
    pin:
      number: D0

```

**Logs (if applicable):**

```c
// Auto generated code by esphome
// ========== AUTO GENERATED INCLUDE BLOCK BEGIN ===========
#include "esphome.h"
using namespace esphome;
using namespace binary_sensor;
using namespace switch_;
gpio::GPIOBinarySensor *bs_1;
gpio::GPIOBinarySensor *bs_2;
gpio::GPIOSwitch *sw_1;
gpio::GPIOSwitch *sw_2;
// ========== AUTO GENERATED INCLUDE BLOCK END ==========="

void setup() {
  // ===== DO NOT EDIT ANYTHING BELOW THIS LINE =====
  // ========== AUTO GENERATED CODE BEGIN ===========
  // esphome:
  //   name: test
  //   platform: ESP8266
  //   board: d1_mini_lite
  //   build_path: target/test
  //   libraries: []
  //   board_flash_mode: dout
  //   arduino_version: espressif8266@2.2.3
  //   includes: []
  //   platformio_options: {}
  //   esp8266_restore_from_flash: false
  App.pre_setup("test", __DATE__ ", " __TIME__);
  // binary_sensor:
  // switch:
  // binary_sensor.gpio:
  //   platform: gpio
  //   id: bs_1
  //   name: test bs1
  //   internal: true
  //   pin:
  //     number: 16
  //     inverted: false
  //     mode: INPUT
  bs_1 = new gpio::GPIOBinarySensor();
  App.register_component(bs_1);
  // binary_sensor.gpio:
  //   platform: gpio
  //   id: bs_2
  //   name: test bs2
  //   internal: false
  //   pin:
  //     number: 5
  //     inverted: false
  //     mode: INPUT
  bs_2 = new gpio::GPIOBinarySensor();
  App.register_component(bs_2);
  // switch.gpio:
  //   platform: gpio
  //   id: sw_1
  //   name: sw_1
  //   internal: true
  //   pin:
  //     number: 16
  //     inverted: false
  //     mode: OUTPUT
  //   interlock_wait_time: 0ms
  //   restore_mode: RESTORE_DEFAULT_OFF
  sw_1 = new gpio::GPIOSwitch();
  App.register_component(sw_1);
  // switch.gpio:
  //   platform: gpio
  //   id: sw_2
  //   name: sw_2
  //   internal: false
  //   pin:
  //     number: 16
  //     inverted: false
  //     mode: OUTPUT
  //   interlock_wait_time: 0ms
  //   restore_mode: RESTORE_DEFAULT_OFF
  sw_2 = new gpio::GPIOSwitch();
  App.register_component(sw_2);
  App.register_binary_sensor(bs_1);
  bs_1->set_name("test bs1");
  bs_1->set_internal("internal");
  App.register_binary_sensor(bs_2);
  bs_2->set_name("test bs2");
  bs_2->set_internal("internal");
  App.register_switch(sw_1);
  sw_1->set_name("sw_1");
  sw_1->set_internal(true);
  App.register_switch(sw_2);
  sw_2->set_name("sw_2");
  sw_2->set_internal(false);
  bs_1->set_pin(new GPIOPin(16, INPUT, false));
  bs_2->set_pin(new GPIOPin(5, INPUT, false));
  sw_1->set_pin(new GPIOPin(16, OUTPUT, false));
  sw_1->set_restore_mode(gpio::GPIO_SWITCH_RESTORE_DEFAULT_OFF);
  sw_2->set_pin(new GPIOPin(16, OUTPUT, false));
  sw_2->set_restore_mode(gpio::GPIO_SWITCH_RESTORE_DEFAULT_OFF);
  // =========== AUTO GENERATED CODE END ============
  // ========= YOU CAN EDIT AFTER THIS LINE =========
  App.setup();
}

void loop() {
  App.loop();
}

```

**Additional information and things you've tried:**
Please look at set_internal call
```c
  bs_1->set_internal("internal");
  bs_2->set_internal("internal");
  sw_1->set_internal(true);
  sw_2->set_internal(false);
```
