### ISSUE TITLE
bang bang climate loses values ​​sent by home assistant

### ISSUE THREAD

**Issue by blademckain** [esphome/issues#1229]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32

**Affected component:**
[Bang bang climate controller
](https://esphome.io/components/climate/bang_bang.html)

**Description of problem:**
The default_target_temperature_low and default_target_temperature_high settings, modified through the home assistant's lovelace gui are lost when the esp32 is restarted

**Problem-relevant YAML-configuration entries:**
```yaml
climate:
  - platform: bang_bang
    sensor: dht22_t
    name: my_bang_climate
    id: my_bang_climate
    visual:
      min_temperature: 12 °C
      max_temperature: 35 °C
      temperature_step: 0.1 °C
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 22 °C
    away_config:
      default_target_temperature_low: 16 °C
      default_target_temperature_high: 17 °C
    heat_action:
      - logger.log: "Heat ON"
      - switch.turn_on: OU7  
    idle_action:
      - logger.log: "Idle ON"
      - switch.turn_off: OU7

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Each time the esp32 is restarted, the bang bang start with the configurations taken in the .yaml file and loses any changes made through the home assistant gui
