### ISSUE TITLE
After the 'getting started' wizard nothing is added to homeassistant

### ISSUE THREAD

**Issue by gald33** [esphome/issues#1236]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip venv, python 3.7.
Operating System: KDE neon User Edition 5.18 (it is based on Ubuntu 18.04)
Kernel: Linux 5.3.0-45-generic
Architecture: x86-64
I'm using a PC which is at home. Everything I do is via ssh. Homeassistant and esphome are meant to be installed in the same virtual environment with python 3.7. Since I'm not sure homeassistant is really running in this venv I later installed esphome without a venv with pip of python 3.7 (by the way, this is the line in systemctl: ExecStart=/home/my_user/homeassistant/bin/hass -c "/home/%i/.homeassistant", and /home/my_user/homeassistant is where the homeassistant and esphome were installed in a venv. Maybe you can tell if it running in the venv or not). Homeassistant does work.

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 (though I haven't even connected it).

**Affected component:**
none

**Description of problem:**
I'm following the 'getting started' manual at https://esphome.io/guides/getting_started_command_line.html. I've finished the wizard to create a basic yaml file which I named plant.yaml. According to the wizard: "Check your Home Assistant "integrations" screen. If all goes well, you should see your ESP being discovered automatically.", but nothing is discovered.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
This is the plant.yaml
esphome:
  name: plant
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "wifi_name"
  password: "wifi_pass"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plant Fallback Hotspot"
    password: "another_pass"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I've tried moving the yaml file to the directory with homeassistant's configuration.yaml, restarting homeassistant, and waiting.
