### ISSUE TITLE
Multiple raw codes remote receiver

### ISSUE THREAD

**Issue by oskarax** [esphome/issues#1239]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant running in a Linux VM

**ESP (ESP32/ESP8266, Board/Sonoff):**
 D1 Mini v.3.0.1 ESP8266

**Affected component:**
 https://esphome.io/components/remote_receiver.html

**Description of problem:**
Hi! im having issues with the raw ir codes being captured by esphome. The raw codes är slightly different every same button press which makes it impossible to do a automation in Home Assistant as the code needs to be exactly the same for the binary sensor to trigger off-on.
A quick solution for this is to press the same button 20 times and save all the raw codes and add them as 20 different remote_receivers. But that isn't very convenient and it takes a lot of time and when I want to do a automation in Home Assistant a need all the 20 triggers for it.
So my question is if its possible to add all the raw codes after one another under one single remote_receiver? Ive tried but maybe im doing it wrong. This is hard for me to explain, I have a picture on the config file if that will help. Thanks

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: mottagare1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid:
  password: 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mottagare1 Fallback Hotspot"
    password: "DvFFmyJO6fet"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


remote_receiver:
  dump: all
  filter: 250us
  idle: 20ms
  pin: 
    number: D5
    inverted: true
    mode: INPUT_PULLUP

binary_sensor:
 - platform: remote_receiver
   name: "crtain1 upp"
   raw: 
    code: [3331, -2919, 15833, -2918, 6458, -6042, 6456, -9170, 6456, -6044, 3333, -6042, 6459, -6042, 6456, -9169, 6457, -6044, 6458, -2917, 12720]

 - platform: remote_receiver
   name: "crtain1 upp2"
   raw: 
    code: [-2924, 3328, -15423, 3331, -6045, 6454, -6047, 9581, -6045, 6453, -2922, 6456, -6045, 6454, -6047, 9581, -6045, 6454, -6047, 3324, -12302]

 - platform: remote_receiver
   name: "crtain1 upp3"
   raw: 
    code: [-2924, 3328, -15423, 3331, -6044, 6454, -6047, 9582, -6044, 6454, -2922, 6456, -6045, 6454, -6046, 9582, -6045, 6453, -6047, 3325, -2919, 9599]

 - platform: remote_receiver
   name: "crtain1 upp4"
   raw: 
    code: [3328, -2922, 15832, -2919, 5333, -918, 6453, -6047, 9582, -6044, 6454, -2922, 6456, -6045, 6454, -4757, 1493, -1973, 7405, -6045, 6451, -6049, 3325, -12301]

 - platform: remote_receiver
   name: "crtain1 upp4"
   raw: 
    code: [-2924, 3328, -15423, 3331, -770, 5478, -6047, 6451, -9175, 6454, -6047, 3330, -6045, 6454, -6047, 6452, -9174, 6452, -6049, 6454, -2922, 12717]

 - platform: remote_receiver
   name: "crtain1 upp5"
   raw: 
    code: [3327, -2924, 15829, -2922, 6456, -6044, 6452, -9174, 6452, -6049, 3329, -6047, 6453, -6048, 6451, -9174, 6452, -6049, 6454, -1974, 1144, -12304]

 - platform: remote_receiver
   name: "crtain1 upp6"
   raw: 
    code: [-2927, 3326, -15425, 3328, -6047, 6451, -6050, 9578, -6048, 6449, -2926, 6454, -6047, 6451, -6052, 6842, -2531, 6451, -6049, 6454, -2922, 12715]

 - platform: remote_receiver
   name: "crtain1 upp7"
   raw: 
    code: [3317, -2921, 15834, -2919, 6454, -6047, 6451, -9175, 2707, -3541, 6458, -2918, 6458, -6042, 2132, -3237, 1085, -6049, 9581, -6045, 6449, -6050, 3323, -12302]

 - platform: remote_receiver
   name: "crtain1 upp8"
   raw: 
    code: [3329, -2921, 15832, -2919, 6456, -6045, 6454, -9172, 6453, -6047, 3329, -6047, 6382, -3468, 484, -1995, 373, -6049, 9578, -6047, 6452, -6049, 3322, -12304]

 - platform: remote_receiver
   name: "crtain1 upp9"
   raw: 
    code: [-2924, 3329, -3287, 12341, -2919, 6456, -6045, 6454, -9172, 6451, -6049, 3329, -6047, 6453, -6047, 6452, -9174, 6452, -6049, 6453, -2922, 12715]

 - platform: remote_receiver
   name: "crtain1 upp10"
   raw: 
    code: [-2924, 3328, -15422, 3331, -6047, 6453, -6047, 9579, -6045, 6454, -2922, 6457, -6045, 6452, -6049, 9581, -6042, 6456, -6045, 3324, -12304]

 - platform: remote_receiver
   name: "crtain1 upp11"
   raw: 
    code: [3321, -2929, 15826, -2923, 6455, -6045, 6449, -9176, 6449, -1444, 4809, -2924, 6451, -6049, 6453, -6047, 9579, -6047, 6449, -2878, 3375, -2924, 12714]

 - platform: remote_receiver
   name: "crtain1 upp12"
   raw: 
    code: [3326, -2924, 15831, -2920, 6456, -6044, 6452, -9173, 6452, -3089, 3161, -2924, 6453, -6047, 6452, -6049, 9580, -6045, 6451, -6049, 3322, -6510, 6010]
    
 - platform: remote_receiver
   name: "crtain1 upp13"
   raw: 
    code: [3326, -2924, 15831, -2920, 6455, -6044, 6452, -9174, 6451, -6049, 3331, -6044, 6454, -6047, 6453, -9172, 6452, -6052, 6450, -2922, 8228, -4272]
    
 - platform: remote_receiver
   name: "crtain1 upp14"
   raw: 
    code: [3329, -2922, 15828, -2922, 6456, -6045, 6453, -9172, 6453, -2534, 3716, -2922, 6456, -6044, 6454, -6047, 9581, -6044, 6454, -6046, 3322, -12304]
    
 - platform: remote_receiver
   name: "crtain1 upp15"
   raw: 
    code: [3329, -2921, 6095, -9531, 3330, -6045, 6453, -6047, 9581, -6044, 6454, -2922, 6455, -6045, 6454, -6046, 9581, -6045, 6453, -6047, 3324, -12301]

 - platform: remote_receiver
   name: "crtain1 ner"
   raw: 
    code: [3329, -2922, 5596, -10029, 3333, -6042, 6455, -6046, 9581, -6045, 6454, -2921, 6456, -6045, 6454, -6047, 9581, -6044, 6454, -6047, 6449, -12301]

 - platform: remote_receiver
   name: "crtain1 ner_2"
   raw: 
    code: [-2922, 3331, -15420, 3334, -6042, 6456, -6045, 9584, -6042, 6454, -2922, 6459, -6042, 6457, -6044, 9584, -6042, 6457, -6044, 6452, -12300]

 - platform: remote_receiver
   name: "crtain1 ner_3"
   raw: 
    code: [-2923, 3332, -15420, 3333, -6043, 6456, -6044, 9582, -6044, 6455, -2921, 6457, -6044, 6454, -6047, 9584, -6042, 6457, -6044, 6452, -12300]
    
 - platform: remote_receiver
   name: "crtain1 ner_4"
   raw: 
    code: [3329, -2921, 15832, -2920, 6456, -6044, 6454, -9172, 6454, -6047, 3333, -6043, 6458, -6042, 2732, -3519, 9583, -6043, 6456, -6045, 6452, -12299]
    
 - platform: remote_receiver
   name: "crtain1 ner_5"
   raw: 
    code: [3331, -2919, 15834, -2917, 6459, -6042, 6456, -9170, 6456, -6045, 3333, -6042, 6461, -6040, 6456, -9170, 6456, -6045, 6458, -6042, 12720]
    
 - platform: remote_receiver
   name: "crtain1 ner_6"
   raw: 
    code: [3331, -2919, 15834, -2917, 6459, -6042, 6456, -9170, 6456, -6045, 3333, -6042, 6459, -6042, 6456, -9170, 6456, -6045, 6458, -6043, 12720]
    
 - platform: remote_receiver
   name: "crtain1 ner_7"
   raw: 
    code: [3329, -2922, 12034, -3592, 2556, -569, 2315, -3935, 6454, -6047, 9581, -6045, 6454, -2921, 6457, -6044, 6457, -6044, 9584, -6042, 6454, -6047, 6450, -12301]
    
 - platform: remote_receiver
   name: "crtain1 ner_8"
   raw: 
    code: [-2923, 3332, -15420, 3333, -6042, 6454, -6047, 9581, -6045, 6456, -2920, 6458, -5687, 563, -6043, 6454, -9172, 6456, -2372, 3879, -6044, 6452, -12299]
    
 - platform: remote_receiver
   name: "crtain1 ner_9"
   raw: 
    code: [3329, -2921, 15832, -2919, 6456, -6045, 6454, -9172, 6454, -6047, 3331, -6044, 6457, -6044, 6454, -9172, 6454, -6047, 6456, -6045, 12716]
    
 - platform: remote_receiver
   name: "crtain1 ner_10"
   raw: 
    code:  [3331, -2919, 15834, -2917, 6459, -6042, 6456, -9169, 6457, -6044, 3333, -6043, 6458, -6042, 6456, -9170, 6456, -6045, 6458, -6042, 12720]
    
 - platform: remote_receiver
   name: "crtain1 ner_11"
   raw: 
    code: [3328, -2922, 15831, -2920, 6454, -6046, 6454, -6047, 6454, -6046, 6454, -6047, 6454, -6047, 6453, -9172, 6454, -6047, 6458, -6042, 12707]
    
 - platform: remote_receiver
   name: "crtain1 ner_12"
   raw: 
    code: [485, -2333, 14546, -2924, 3331, -15421, 3331, -6044, 6454, -6047, 9582, -6045, 6454, -2921, 6457, -6045, 6456, -6044, 9582, -6046, 6453, -6047, 6449, -12303, 8412]
    
 - platform: remote_receiver
   name: "crtain1 ner_13"
   raw: 
    code: [-2929, 3324, -15424, 3328, -6047, 6451, -6049, 9578, -6047, 6451, -2924, 6454, -6046, 6453, -6047, 9579, -6046, 6452, -3340, 2914, -6045, 12716]
    
 - platform: remote_receiver
   name: "crtain1 ner_14"
   raw: 
    code: [-2922, 3331, -15419, 3333, -6042, 6456, -6044, 9581, -6044, 6454, -2921, 6456, -6044, 6456, -6044, 9583, -6042, 2406, -3845, 6455, -4796, 1450, -12299]
    
 - platform: remote_receiver
   name: "crtain1 ner_15"
   raw: 
    code: [-2923, 3331, -12533, 3092, -2919, 6459, -6042, 6455, -9170, 6453, -6047, 3333, -6042, 6458, -6042, 6456, -9169, 6454, -6046, 6459, -6041, 12717]
    
 - platform: remote_receiver
   name: "crtain1 ner_16"
   raw: 
    code: [2968, -610, 1110, -2923, 3331, -15420, 3333, -6042, 6455, -6045, 9583, -6042, 6456, -2919, 6458, -6042, 6454, -6046, 9583, -6042, 6456, -6044, 6452, -12298]
    
 - platform: remote_receiver
   name: "evening"
   raw: 
    code: [-3010, 3329, -7399, 8229, -1452, 1671, -6047, 6453, -6047, 9581, -6045, 3326, -9174, 6456, -2920, 6453, -6047, 9583, -6043, 3331, -6044, 9579, -12297]
    
 - platform: remote_receiver
   name: "evening2"
   raw: 
    code: [-3010, 3329, -15422, 3331, -6044, 6454, -6047, 9581, -6045, 3328, -9172, 6456, -2919, 6454, -599, 5651, -9172, 6454, -2921, 6457, -9169, 12720]
    
 - platform: remote_receiver
   name: "evening3"
   raw: 
    code: [-3011, 3329, -15422, 3331, -6044, 6454, -6047, 9581, -6044, 3327, -9174, 6456, -2919, 6454, -6047, 9583, -6042, 3327, -6048, 9577, -12299]
    
 - platform: remote_receiver
   name: "evening4"
   raw: 
    code: [-3010, 3329, -15422, 3331, -6044, 6454, -6047, 9581, -6044, 3327, -9174, 6456, -2919, 6454, -6046, 9582, -6044, 3326, -6048, 9578, -12299]
    
 - platform: remote_receiver
   name: "evening5"
   raw: 
    code: [3416, -2921, 15831, -2919, 6456, -6045, 6454, -9171, 6454, -2921, 9581, -6045, 3331, -6044, 6454, -9172, 6453, -2922, 6455, -9170, 12712]
    
 - platform: remote_receiver
   name: "evening6"
   raw: 
    code: [-3011, 3326, -15424, 3331, -6044, 6454, -6047, 9580, -6045, 3327, -9173, 6453, -2922, 6454, -6046, 9579, -6047, 3324, -6051, 9578, -12297]
    
 - platform: remote_receiver
   name: "evening7"
   raw: 
    code: [-3011, 3331, -15420, 3331, -6044, 6454, -6046, 9581, -6044, 3327, -9173, 6456, -2920, 6453, -6047, 9581, -6044, 3326, -6049, 9577, -12298]
    
 - platform: remote_receiver
   name: "evening8"
   raw: 
    code: [3913, -3009, 3328, -15422, 3335, -3577, 2669, -6044, 6456, -9169, 6456, -2919, 9581, -6044, 3334, -6041, 6457, -9169, 6456, -2919, 6456, -9169, 12713]
    
 - platform: remote_receiver
   name: "evening9"
   raw: 
    code: [-3010, 3330, -15421, 3331, -6044, 6454, -6046, 9583, -6043, 3326, -9174, 6456, -2919, 6456, -6044, 9583, -6042, 3327, -6048, 9579, -12296]
    
 - platform: remote_receiver
   name: "evening10"
   raw: 
    code: [-3011, 3331, -15419, 3333, -6042, 6454, -6046, 9583, -6042, 3327, -9173, 6459, -2917, 6453, -6046, 9584, -6042, 3326, -6049, 9578, -12297]

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
