### ISSUE TITLE
Rotary encoder component broken in dev branch

### ISSUE THREAD

**Issue by puuu** [esphome/issues#124]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip/git

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

rotary encoder

**Description of problem:**
Using the dev branch, the rotary_encoder do not change its state when rotating. Version 1.11.2 of esphome-core works fine.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: rot_test
  platform: ESP8266
  board: d1_mini
  esphome_core_version:
    #tag: v1.11.2 # ok
    #commit: 6088a6d2e256511067d7b6da19a3638b74cf42d7 # ok
    #commit: acccea739754fc12689a880b1e5ef7ae8eed318a # comiler error
    #commit: e691aa9ae1b54fa1748fe8a0f0cf2b69eae876ea # comiler error
    tag: dev # broken

logger:

sensor:
  - platform: rotary_encoder
    name: rot_left
    id: rot_left
    pin_a:
      number: D2
      mode: INPUT_PULLUP
    pin_b:
      number: D1
      mode: INPUT_PULLUP
    on_value:
      then:    
        - lambda: |-
            ESP_LOGD("Rot", "Got: %f", x);
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
