### ISSUE TITLE
Compiling hangs at AsyncMqttClient-esphome

### ISSUE THREAD

**Issue by Martinvdm** [esphome/issues#1241]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

AsyncMqttClient-esphome

**Description of problem:**
Not continuing compiling

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  display_name: SolarWeatherStation

esphome:
  name: solar_weather
  platform: ESP8266
#  board: d1_mini_pro
  board: d1_mini
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

#api:

# Enable logging
logger:

mqtt:
  broker: !secret mqtt_broker
  birth_message:
    topic: solarsensor/birthdisable
    payload: disable
  will_message:
    topic: solarsensor/willdisable
    payload: disable

ota:

i2c:
 - id: ic_1
   sda: 4
   scl: 5
   scan: false

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 20s
    
  - platform: bme280
    temperature:
      name: ${display_name} Temp
      oversampling: 4x
    pressure:
      name: ${display_name} Pres
      oversampling: 4x
    humidity:
      name: ${display_name} Humi
      oversampling: 4x
    address: 0x76
    update_interval: 30s

  - platform: bh1750
    name: ${display_name} Lux
    address: 0x23
    update_interval: 25s
      
  - platform: adc
    pin: A0
    name: ${display_name} Battery
    update_interval: 35s
    filters:
      - multiply: 5.1923

deep_sleep:
  run_duration: 40s
  sleep_duration: 4min

```

**Logs (if applicable):**

```
INFO Reading configuration /config/solar_weather.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/solar_weather
Processing solar_weather (board: d1_mini; framework: arduino; platform: espressif8266@2.2.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Looking for AsyncMqttClient-esphome library in registry

```

**Additional information and things you've tried:**
Sometimes it hangs on: Looking for AsyncMqttClient-esphome library in registry
When doing a clean build it hangs on:
Looking for AsyncMqttClient-esphome library in registry
LibraryManager: Installing id=6759 @ 0.8.4

i did checked DNS, and with curl it can curl to platform.io
deleted folder, compile again, same issue
validate is OK

docker-compose:
```
  esphome:
    container_name: ESPHome
    image: esphome/esphome:latest
    network_mode: host
    restart: always
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /home/docker/esphome:/config
      - /etc/localtime:/etc/localtime:ro
```
