### ISSUE TITLE
Stepper pulses are missed/unstable pulse generator

### ISSUE THREAD

**Issue by abrilevskiy** [esphome/issues#1246]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266

**Affected component:**
Stepper

**Description of problem:**
Pulse generator at stepper component works unstable: pulses are missed, duration is also different, please take a look to pictures 
![Logic 2  Logic16 - Disconnected  5_25_2020 11_49_05 AM](https://user-images.githubusercontent.com/7629383/82808872-8cedd780-9e93-11ea-8348-90ffe8f1b97b.png)
![Logic 2  Logic16 - Disconnected  5_25_2020 11_49_16 AM](https://user-images.githubusercontent.com/7629383/82808874-8d866e00-9e93-11ea-9381-4184826b2ec3.png)
![Logic 2  Logic16 - Disconnected  5_25_2020 11_49_36 AM](https://user-images.githubusercontent.com/7629383/82808875-8eb79b00-9e93-11ea-9c53-a03a448d7097.png)
![Logic 2  Logic16 - Disconnected  5_25_2020 11_51_21 AM](https://user-images.githubusercontent.com/7629383/82808877-8eb79b00-9e93-11ea-9dd1-19d8a371a889.png)

(screenshots from Logic Analyser)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: cover_debug
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ...
  password: ...

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ...
    password: ...

captive_portal:

debug:

# Enable logging
logger:
  level: DEBUG
  logs:
    mqtt.component: ERROR
    mqtt.client: ERROR

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

mqtt:
  broker: ...
  username: ...
  password: ...

stepper:
    - platform: a4988
      id: my_stepper
      step_pin: GPIO12
      dir_pin:
          number: GPIO13
          inverted: True
      sleep_pin: GPIO14
      max_speed: 250 steps/s
      acceleration: 50
      deceleration: 50

cover:
  - platform: template
    name: "Bedroom Blind Roller Right"
    id: BadroomBlindRollerRight
    open_action:

      - stepper.set_target:
          id: my_stepper
          target: 0
    close_action:

      - stepper.set_target:
          id: my_stepper
          target: 32000
    stop_action:

      - stepper.set_target:
          id: my_stepper
          target: !lambda return id(my_stepper).current_position;
    optimistic: true

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
