### ISSUE TITLE
Xiaomi CGG1 - ESP32 lost connection

### ISSUE THREAD

**Issue by anglrus** [esphome/issues#1249]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESP Home uses Docker on Synology

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 DEVKitV1
ESP Home Dashboard : 1.14.3

**Affected component:**

https://esphome.io/components/sensor/xiaomi_cgg1.html

**Description of problem:**
Xiaomi sensors lost connection:
[xiaomi_cgg1:012]: Xiaomi CGG1
ERROR Error while reading incoming messages: Error while receiving data: [Errno 104] Connection reset by peer

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

esphome:
  name: ble_tracker
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "SSID"
  password: "PASSWORD"
  manual_ip:
    static_ip: 192.168.1.6
    gateway: 192.168.1.1
    subnet: 255.255.255.0  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ble Tracker Fallback Hotspot"
    password: "PASSWORD"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "PASSWORD"

ota:
  password: "PASSWORD"
  
# Веб сервер
web_server:
  port: 80  
  
# Интерфал сканирования
esp32_ble_tracker:

sensor:
  - platform: xiaomi_cgg1
    mac_address: XX
    temperature:
      name: temperature.bathroom
    humidity:
      name: humidity.bathroom
    battery_level:
      name: battery.bathroom
      
  - platform: xiaomi_cgg1
    mac_address: XX
    temperature:
      name: temperature.bedroom
    humidity:
      name: humidity.bedroom
    battery_level:
      name: battery.bedroom      
      
  - platform: xiaomi_hhccjcy01
    mac_address: XX
    temperature:
      name: temperature.schefflera
    moisture:
      name: moisture.schefflera
    illuminance:
      name: illuminance.schefflera
    conductivity:
      name: conductivity.schefflera
    battery_level:
      name: battery.schefflera      
      
  - platform: xiaomi_hhccjcy01
    mac_address: XX
    temperature:
      name: temperature.croton
    moisture:
      name: moisture.croton
    illuminance:
      name: illuminance.croton
    conductivity:
      name: conductivity.croton
    battery_level:
      name: battery.croton            
        


**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

I tried to push buttons on back side of sensors. It provides posibility to connect. But connection lost after some time. Flower care works w/h problem.

Additional I have USB Bluetooth for Synology. And there is line inside HA configurtion.yaml:

device_tracker:
   - platform: bluetooth_tracker

It shows data from CGG1 BLE sensors

<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
