### ISSUE TITLE
hx711 crashes when using filters "on value range"

### ISSUE THREAD

**Issue by thieaux** [esphome/issues#1252]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io running rpi 
**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 D1 mini

**Affected component:**
HX711

**Description of problem:**
Using hx711 amplifier with 4 load cells to monitor weight of water jug (5 gallons), whenever  the weight is below 8.3 pound (gallon) it would open a relay to cut water pump using filters: on value range, below 1 gallon the relay would open to cut power to the pump, above 1.5 the relay would be de energized (nc) allow pump to run. When the weight drops below 1 gallon the relay activates , but when the weight is replaced again the hx711 crashes with "hx711 not ready for measurements" this only happens when using the on value range filter.
**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: water
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "hassio"
  password: "8095635350"
  manual_ip:
     static_ip: 192.168.33.208
     gateway: 192.168.33.1
     subnet: 255.255.255.0
     
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testscale Fallback Hotspot"
    password: "dFRdfJeI9amt"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
sensor:
  - platform: hx711
    name: "POTABLE WATER"
    dout_pin: D4
    clk_pin: D3
    gain: 128
    update_interval: 5s
    on_value_range:
      - above: 1.25
        then:
          - switch.turn_off: "water_pump" 
      - below: 1
        then:
          - switch.turn_on: "water_pump" 
    filters: 
    - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - -572000 -> 0.0
          - -152000 -> 5.0
    unit_of_measurement: GALLONS
    
   
    
  - platform: wifi_signal
    name: "WiFi Signal Water"
    update_interval: 60s     

switch:
  - platform: gpio
    pin: D5
    id: water_pump
    name: "Potable Water Pump"       
    
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```16:59:44][C][logger:175]: Logger:
[16:59:44][C][logger:176]:   Level: DEBUG
[16:59:44][C][logger:177]:   Log Baud Rate: 115200
[16:59:44][C][logger:178]:   Hardware UART: UART0
[16:59:44][C][hx711:021]: HX711 'POTABLE WATER'
[16:59:44][C][hx711:021]:   Unit of Measurement: 'GALLONS'
[16:59:44][C][hx711:021]:   Accuracy Decimals: 0
[16:59:44][C][hx711:021]:   Icon: 'mdi:scale'
[16:59:44][C][hx711:022]:   DOUT Pin: GPIO2 (Mode: INPUT)
[16:59:44][C][hx711:023]:   SCK Pin: GPIO0 (Mode: OUTPUT)
[16:59:44][C][hx711:024]:   Update Interval: 5.0s
[16:59:44][C][captive_portal:169]: Captive Portal:
[16:59:44][C][ota:029]: Over-The-Air Updates:
[16:59:44][C][ota:030]:   Address: 192.168.33.208:8266
[16:59:44][C][api:095]: API Server:
[16:59:44][C][api:096]:   Address: 192.168.33.208:6053
[16:59:44][C][wifi_signal.sensor:009]: WiFi Signal 'WiFi Signal Water'
[16:59:44][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dB'
[16:59:44][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[16:59:44][C][wifi_signal.sensor:009]:   Icon: 'mdi:wifi'
[16:59:49][D][hx711:031]: 'POTABLE WATER': Got value -383159
[16:59:49][D][sensor:092]: 'POTABLE WATER': Sending state 2.24811 GALLONS with 0 decimals of accuracy
[16:59:54][D][hx711:031]: 'POTABLE WATER': Got value -383223
[16:59:54][D][sensor:092]: 'POTABLE WATER': Sending state 2.24734 GALLONS with 0 decimals of accuracy
[16:59:59][D][hx711:031]: 'POTABLE WATER': Got value -383352
[16:59:59][D][sensor:092]: 'POTABLE WATER': Sending state 2.24581 GALLONS with 0 decimals of accuracy
[17:00:04][D][hx711:031]: 'POTABLE WATER': Got value -382116
[17:00:04][D][sensor:092]: 'POTABLE WATER': Sending state 2.26052 GALLONS with 0 decimals of accuracy
[17:00:09][D][hx711:031]: 'POTABLE WATER': Got value -384196
[17:00:09][D][sensor:092]: 'POTABLE WATER': Sending state 2.23576 GALLONS with 0 decimals of accuracy
[17:00:14][D][hx711:031]: 'POTABLE WATER': Got value -383529
[17:00:14][D][sensor:092]: 'POTABLE WATER': Sending state 2.24370 GALLONS with 0 decimals of accuracy
[17:00:19][D][hx711:031]: 'POTABLE WATER': Got value -383857
[17:00:19][D][sensor:092]: 'POTABLE WATER': Sending state 2.23980 GALLONS with 0 decimals of accuracy
[17:00:24][D][sensor:092]: 'WiFi Signal Water': Sending state -65.00000 dB with 0 decimals of accuracy
[17:00:24][D][hx711:031]: 'POTABLE WATER': Got value -383534
[17:00:24][D][sensor:092]: 'POTABLE WATER': Sending state 2.24364 GALLONS with 0 decimals of accuracy
[17:00:29][D][hx711:031]: 'POTABLE WATER': Got value -383729
[17:00:29][D][sensor:092]: 'POTABLE WATER': Sending state 2.24132 GALLONS with 0 decimals of accuracy
[17:00:34][D][hx711:031]: 'POTABLE WATER': Got value -383526
[17:00:34][D][sensor:092]: 'POTABLE WATER': Sending state 2.24374 GALLONS with 0 decimals of accuracy
[17:00:39][D][hx711:031]: 'POTABLE WATER': Got value -383681
[17:00:39][D][sensor:092]: 'POTABLE WATER': Sending state 2.24189 GALLONS with 0 decimals of accuracy
[17:00:44][D][hx711:031]: 'POTABLE WATER': Got value -383386
[17:00:44][D][sensor:092]: 'POTABLE WATER': Sending state 2.24540 GALLONS with 0 decimals of accuracy
[17:00:45][I][ota:046]: Boot seems successful, resetting boot loop counter.
[17:00:49][D][hx711:031]: 'POTABLE WATER': Got value -383545
[17:00:49][D][sensor:092]: 'POTABLE WATER': Sending state 2.24351 GALLONS with 0 decimals of accuracy
[17:00:54][D][hx711:031]: 'POTABLE WATER': Got value -548097
[17:00:54][D][sensor:092]: 'POTABLE WATER': Sending state 0.28456 GALLONS with 0 decimals of accuracy
[17:00:54][D][switch:021]: 'Potable Water Pump' Turning ON.
[17:00:54][D][switch:045]: 'Potable Water Pump': Sending state ON
[17:00:59][W][hx711:037]: HX711 is not ready for new measurements yet!
[17:01:04][W][hx711:037]: HX711 is not ready for new measurements yet!
[17:01:09][W][hx711:037]: HX711 is not ready for new measurements yet!
[17:01:14][W][hx711:037]: HX711 is not ready for new measurements yet!

**Additional information and things you've tried:**
eliminating the on value range , doesn't  crash the hx711


<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
