### ISSUE TITLE
Color picker + white value not working any more with RGBWW Leds

### ISSUE THREAD

**Issue by ghost** [esphome/issues#1262]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8285 Novostella Floodlight
**Affected component:**
https://esphome-configs.io/devices/novostella-20w/

**Description of problem:**
when i pick a color in color picker of the entity in home assistant the slider of the white value jumps back to 0. with software version 1.14.3 it is working

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```#Novostella 20W Flood Light, https://smile.amazon.com/gp/product/B07VH1VHYL
#https://fccid.io/2AI5T-SFGD-002
#https://blakadder.github.io/templates/novostella_20W_flood.html
substitutions:
  device_name: novoflood_neu
  device_description: 20W RGBWW flood light
  friendly_name: Novostella Flood Light neu

esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "SKYDSL"
  password: "AVaeBWbbKMfZiA"
  fast_connect: on #we only have one WiFi AP so just use the first one that matches
  ap: #since we listed an SSID above, this AP mode will only enable if no WiFi connection could be made
    ssid: ${friendly_name}_AP
    password: traktor10

captive_portal:

# Enable logging
logger:
  baud_rate: 0 #disable UART logging since we aren't connected to GPIO1 TX

# Enable Home Assistant API
api:

# Enable OTA updates
ota:

# Enable web server
web_server:
  port: 80

binary_sensor:
# Reports if this device is Connected or not
- platform: status
  name: ${friendly_name} Status

sensor:
# Reports the WiFi signal strength
- platform: wifi_signal
  name: ${friendly_name} Signal
  update_interval: 60s

# Reports how long the device has been powered (in minutes)
- platform: uptime
  name: ${friendly_name} Uptime
  filters:
    - lambda: return x / 60.0;
  unit_of_measurement: minutes

text_sensor:
# Reports the ESPHome Version with compile date
- platform: version
  name: ${friendly_name} ESPHome Version

output:
- platform: esp8266_pwm
  id: red
  pin: GPIO4
  inverted: False
- platform: esp8266_pwm
  id: green
  pin: GPIO12
  inverted: False
- platform: esp8266_pwm
  id: blue
  pin: GPIO14
  inverted: False
- platform: esp8266_pwm
  id: cold_white
  pin: GPIO5
  inverted: False
- platform: esp8266_pwm
  id: warm_white
  pin: GPIO13
  inverted: False

light:
- platform: rgbww
  name: ${friendly_name}
  red: red
  green: green
  blue: blue
  cold_white: cold_white
  warm_white: warm_white
  cold_white_color_temperature: 6500 K
  warm_white_color_temperature: 2700 K
  id: thelight
  restore_mode: ALWAYS_ON #Start with light on after reboot/power-loss event, so that it works from a dumb lightswitch
  effects:
    - random:
    - strobe:
    - flicker:
        alpha: 50% #The percentage that the last color value should affect the light. More or less the “forget-factor” of an exponential moving average. Defaults to 95%.
        intensity: 50% #The intensity of the flickering, basically the maximum amplitude of the random offsets. Defaults to 1.5%.
    - lambda:
        name: Throb
        update_interval: 1s
        lambda: |-
          static int state = 0;
          auto call = id(thelight).turn_on();
          // Transtion of 1000ms = 1s
          call.set_transition_length(1000);
          if (state == 0) {
            call.set_brightness(1.0);
          } else {
            call.set_brightness(0.01);
          }
          call.perform();
          state += 1;
          if (state == 2)
            state = 0;

# Blink the light if we aren't connected to WiFi.
interval:
- interval: 500ms
  then:
  - if:
      condition:
        not:
          wifi.connected:
      then:
        - light.turn_on:
            id: thelight
            brightness: 50%
            transition_length: 0s
        - delay: 250ms
        - light.turn_off:
            id: thelight
            transition_length: 250ms

**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->

**Comment by rwoelk** [comment]
I have seen this in 1.15.0b3 as well. For my Tuya based Globe bulbs, this is ideal. The RGB LEDs are about 25% of the brightness of the WW/CW, so in 1.14 when I pick a color, it is lost in the white. In 1.15 it automatically turns the white LEDs off. For my LED strips in RGBW and RGBWW they are all the same brightness, so sometimes I would like to pick a different color cast. 

Under dev docs I found the new command "color interlock" https://next.esphome.io/components/light/rgbw.html#rgbw-color-interlock but it doesn't matter which way I set it, the effect is the same

**Comment by setola** [comment]
Hi there,

I'm on version v1.15.2 and adding [color interlock](https://next.esphome.io/components/light/rgbww.html?highlight=color_interlock#configuration-variables) option, as mentioned by @rwoelk, solved my issue.

The test I've done in HA for my test light:

1. white value at 100%
2. brightness at half way (to avoid blinding on point 4)
3. color temperature full warm
4. look at the light: only warm white led are on
5. set color temperature full cold
6. look at the light: only cold white led are on
7. choose a color from the picker
8. look at the light: both white led are off and RGB led are on

Here's the relevant part of [novoflood_common.yaml](https://www.esphome-devices.com/devices/novostella-20w/#split-configuration)
```yaml
[...]
light:
- platform: rgbww
  name: ${friendly_name}
  red: red
  green: green
  blue: blue
  cold_white: cold_white
  warm_white: warm_white
  cold_white_color_temperature: 6500 K
  warm_white_color_temperature: 2700 K
  id: thelight
  color_interlock: true
  restore_mode: ALWAYS_ON #Start with light on after reboot/power-loss event, so that it works from a dumb lightswitch
[...]
```

Here's my PR for the documentation: [#31](https://github.com/esphome-devices/esphome-devices/pull/31)

Cheers!

**Comment by lrvick** [comment]
Just encountered this issue.

When upgrading ESPhome firmware on my RGBWW bulbs from 1.15.3 to 1.20.4 I lose my color picker, lite on/off status, and brightness value in Home Assistant for only the upgraded bulbs. 

Using these bulbs:
https://www.athom.tech/blank-1/gu10-rgbcw

And this Esphome config:
```
substitutions:
  devicename: lamp_1_bulb_1

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "xxxxxxxxxxxxxx"
  password: "xxxxxxxx"
  ap:
    ssid: "$devicename"
    password: "xxxxxxxxxx"

captive_portal:

logger:
  # Disable logging to serial
  baud_rate: 0

api:
  password: "xxxxxxx"

ota:
  password: "xxxxxxxxxxxxxx"

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO5

light:
  - platform: rgbww
    name: $devicename
    id: $devicename
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6200 K
    warm_white_color_temperature: 2800 K
```

@oxan Should we reopen this?

Any ideas welcome.
