### ISSUE TITLE
light.on_turn_on and light.on_turn_off are inverted if the output pin is inverted.

### ISSUE THREAD

**Issue by marklister** [esphome/issues#1268]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

More or less latest Raspian Buster running hass as a service.
Home Assistant 0.110.2
Raspberry Pi zero W (I know)

**ESP (ESP32/ESP8266, Board/Sonoff):**

I'm testing on an ESP 8266.  It's a Chinese Geekcriet board with 4MB Flash.  I have D1 mini pros available and a few ESP32 dev boards in the same NodeMcu form factor.  I haven't tried any as I'm sure they won't affect this.

**Affected component:**

The Light component.  I'm not linking the documentation because the bug relates to the dev branch and the feature I'm using is not documented.

**Description of problem:**

`light.on_turn_on` triggers when my light is switched *off*.
`light.on_turn_off` triggers when my light is switched *on*.

The output pin is set to `inverted: True` 

**Problem-relevant YAML-configuration entries:**
```yaml
output:
  - platform: esp8266_pwm
    id: led1
    pin: GPIO16
    inverted: True

light:
  - platform: monochromatic
    name: "Led 1"
    id: light1
    output: led1
    on_turn_on:
      - logger.log: "Light 1 turned on"
    on_turn_off:
      - logger.log: "Light 1 turned off"
```

**Logs (if applicable):**

The logs are not particularly relevant because you cant see the led state.  Both events are logged correctly just `....on` instead of `...off` and vice versa. 

**Additional information and things you've tried:**

I've tested this by installing the 4 files in PR 1037: https://github.com/esphome/esphome/pull/1037 over the ones in 1.14.4.  It is possible that my hack has caused the bug but I doubt it.
