### ISSUE TITLE
Upgrade to 1.14.4 cause ESP32 to lockup with DHT11 sensor 

### ISSUE THREAD

**Issue by faspina** [esphome/issues#1269]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32/NodeMcu32

**Affected component:**
DHT11 

https://esphome.io/components/sensor/dht.html

**Description of problem:**
DHT11 sensor was working with 1.14.3 , upgraded to 1.14.3 , NODEMCU lockedup and unresponsive,  took out the following code and it worked. Also simplified the DHT sensor and took out the filters, same result. Tried different GPIO , same result.  Works fine on my original nodemcu  

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: dht
    model: DHT11
    pin: GPIO21
    update_interval: 30s     
    temperature:
      name: "Office"
      filters:
        - filter_out: nan
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
        - lambda: return x * (9.0/5.0) + 32.0; # report temperature in Fahrenheit
      unit_of_measurement: "°F"
    humidity:
      name: "Office Humidity"
      filters:
        - filter_out: nan
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
      accuracy_decimals: 1  
      

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
