### ISSUE TITLE
Difficulty Migrating from Sonoff Tasmota: 7 successes, 3 failures

### ISSUE THREAD

**Issue by grantalewis** [esphome/issues#1271]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome on Home Assistant (formerly Hass.io). Mac Mini running Ubuntu 64. Home Assistant and all add ons are in Docker containers. All flashing performed on a Windows 10 computer.

Migrating Sonoff Basics from Tasmota to ESP8266 

**Description of problem:**
I have about 10 Sonoff devices. Of those, I've successfully flashed 7 and three have misbehaved after flashing. It seems like the flashing process is somehow incomplete - like maybe there's something that's leftover, something that's not getting entirely overrwritten.

I've been using these Basic units with Tasmota firmware for about a year. All have IP address reservations on the router via their MAC addresses. So my process has been to create the YAML file, validate it in ESPHome, create and downloaded the .bin file, and then use the Tasmota web interface to upload the new firmware. It worked with 7 of the units, but with the other three, it just keeps failing. After unplugging and then plugging back in, each unit's green LED flashes continuously and never comes online. I can't bring up its web page.

With all three I can re-flash with Tasmota and things go back just as they were before. But if I try to flash the new .bin file created by ESPHome, they once again become inaccessible. It doesn't make sense to me that the process that works just fine in 7 cases fails with 3.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: dog_food_light
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

wifi:
  ssid: <redacted>
  password: <redacted>

api:

logger:

ota:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Dog Food Light ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Dog Food Light IP
    ssid:
      name: Dog Food Light SSID
    bssid:
      name: Dog Food Light BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Dog Food Light Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Dog Food Light WiFi Signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name:   Dog Food Light Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: Dog Food Light Relay
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

```

**Logs (if applicable):**

**Additional information and things you've tried:**

I've also tried flashing the Sonoff board directly from the FTDI adapter (rather than OTA). No luck.

**Comment by grantalewis** [comment]
Solved. Providing more explicit settings in the wifi section of my yaml fixed the issue:
```
wifi:
 ssid: <redacted>
 password: <redacted>
 manual_ip:
   static_ip: 192.168.1.59
   subnet: 255.255.255.0
   dns1: 192.168.1.1
   gateway: 192.168.1.1
```
