### ISSUE TITLE
Homekit support

### ISSUE THREAD

**Issue by aardjoun** [esphome/issues#128]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp8266 sonoff basic
**Affected component:**

Homekit support

**Description of problem:**
The esphome based esp isn't discovered in Apple Home App.
Home Assistant Homekit component work with HA switches 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: lampe_cuisine
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'ssid'
  password: 'password'

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'password'

ota:
  password: 'password'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Lampe cuisine"
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: template
    name: "Lampe cuisine"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    # - light.turn_off: led
    turn_off_action:
    - switch.turn_off: relay
    # - light.turn_on: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

# light:
#   - platform: monochromatic
#     name: "Lampe led cuisine"
#     output: basic_green_led
#     id: led

sensor:
  - platform: wifi_signal
    name: "Lampe cuisine WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Lampe cuisine Uptime"
  
text_sensor:
  - platform: version
    name: "Lampe cuisine ESPHome Version"
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
