### ISSUE TITLE
Upgrade to 1.14.4 caused Shelly 1 not to connect to the network

### ISSUE THREAD

**Issue by bruxy70** [esphome/issues#1280]
**Operating environment/Installation (Hass.io/Docker/pip/etc.): Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff): ESP8266, Shelly 1

**Affected component:**

WiFi I guess, or the whole device

**Description of problem:**
Due to the issues with no internet connection, I upgraded to 1.14.4. Then compiled a simple script for Shelly 1, it compiled fine, uploaded successfully, but it does not connect to WiFi. The script is an exact copy from another working Shelly (except the names). The new shelly appears in DHCP (there is a new entry with Shelly MAC), but I cannot ping it and cannot add it to Home Assistant.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  password: !secret api_password
ota:
  password: !secret ota_password

switch:
  - platform: gpio
    name: cerpadlo_bazen
    pin: GPIO04
    id: cerpadlo_bazen
```

**Logs (if applicable):**

I've tried to connect the Shelly to the serial monitor, but it does not show anything, I do not think it can be powered by 3V. And it is explicitly stated not to connect the USB whilst it is connected to mains.
```

```

**Additional information and things you've tried:**
I have tried to add ap, captive portal and output_power: 17.5dB. No difference.
