### ISSUE TITLE
use GPIO2 for ACD on esp32 wroom32

### ISSUE THREAD

**Issue by jasonblewis** [esphome/issues#1281]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Debian, building from command line:

`esphome  iotuz.yaml run  --upload-port=iotuz.local`

**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32 wroom 32 on an [IoTuz](https://github.com/CCHS-Melbourne/iotuz-esp32-hardware/wiki) board
**Affected component:**

[adc](https://esphome.io/components/sensor/adc.html)

**Description of problem:**
if you set it to use pin 2, esphome produces the following error:

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: iotuz
  platform: ESP32
  board: esp32dev

sensor:
  - platform: adc
    pin: 2
    name: "Battery Level"
    update_interval: 60s
    attenuation: 11db
```

**Logs (if applicable):**

```
jason@sage:~/ownCloud/projects/esphome/config$ esphome  iotuz.yaml run  --upload-port=iotuz.local
INFO Reading configuration iotuz.yaml...
Failed config

sensor.adc: [source iotuz.yaml:70]
  platform: adc
  
  ESP32: Only pins 32 though 39 support ADC.
  pin: 2 [source iotuz.yaml:71]
  name: Battery Level
  update_interval: 60s
  attenuation: 11db

```

according to this page, gpio2 can be used for ADC if I understand correctly:

https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

on adc_2

**Comment by JSchuetzke** [comment]
I just managed to get my temperature sensor to work so I'm not an expert but for me I had to specify the pin with "GPIOx"

So in your case the solution could be:
```yaml
sensor:
  - platform: adc
    pin: GPIO2
```
