### ISSUE TITLE
Integration Platform Periodically Changes to 'inf' Requiring a Contoller Reboot

### ISSUE THREAD

**Issue by Jonah1970** [esphome/issues#1284]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HA Core 0.110.6 on Synology Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 with board nodemcuv2

**Affected component:**

https://esphome.io/components/sensor/integration.html

**Description of problem:**
My application uses an opitical sensor to count pulses from the LED on my home electricity meter to measure power (pulse_counter).  I also calculate energy (meter_power) and daily energy (total_daily_energy) plus temperature/humidity (dht/AM2302) which I believe is all implemented as per the docs.

Everything works fine except that periodically (i.e. once every several weeks) the power measurement goes to 'inf' however everything else appears to continue functioning OK.  The only workaround I have found is to reboot the board.  

The outcome is that my hourly/daily/monthly Utility Meter entities in Home Assistant become inacurate depending on how long it takes me to spot the problem and reboot the controller.

I can understand that integrators will eventually roll-over at some stage but this problem can occur when the value is in the 100's which makes me think it must be something else.  

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  esphome_name: "Boiler Room Sensor"

esphome:
  name: nodemcu01
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_ssid_pwd
  fast_connect: true
  reboot_timeout: 45min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcu01 Fallback Hotspot"
    password: "EsCfUQdASlGG"

captive_portal:

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  password: !secret esphome_api_pwd

ota:
  password: !secret esphome_ota_pwd

web_server:
  port: 80

time:
  - platform: homeassistant
  
###############################################################################
# Pulse Sensor configuration - D2 = pin 4
sensor:
  - platform: pulse_counter
    name: 'Meter Power'
    pin: D2
    unit_of_measurement: 'kW'
    accuracy_decimals: 3
    id: meter_power
    filters:
      - multiply: 0.06
      
  - platform: integration
    name: "Meter Energy"
    accuracy_decimals: 1
    sensor: meter_power
    restore: true
    time_unit: h
    
  - platform: total_daily_energy
    name: "Total Daily Energy"
    accuracy_decimals: 1
    power_id: meter_power

# DHT Sensor configuration - D5 = pin 14      
  - platform: dht
    pin: D5
    temperature:
      name: "Boiler Room Temperature"
    humidity:
      name: "Boiler Room Humidity"
    model: AM2302
    update_interval: 60s

  - platform: wifi_signal
    name: "${esphome_name} WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "${esphome_name} Uptime"

```

**Logs (if applicable):**

```
[D][pulse_counter:159]: 'Meter Power': Retrieved counter: 57.00 pulses/min
[D][sensor:092]: 'Meter Power': Sending state 3.42000 kW with 3 decimals of accuracy
[D][sensor:092]: 'Meter Energy': Sending state inf kWh with 1 decimals of accuracy
[D][dht:048]: Got Temperature=30.0°C Humidity=29.6%
[D][sensor:092]: 'Boiler Room Temperature': Sending state 30.00000 °C with 1 decimals of accuracy
[D][sensor:092]: 'Boiler Room Humidity': Sending state 29.60000 % with 0 decimals of accuracy
[D][dht:048]: Got Temperature=29.7°C Humidity=30.3%
[D][sensor:092]: 'Boiler Room Temperature': Sending state 29.70000 °C with 1 decimals of accuracy
[D][pulse_counter:159]: 'Meter Power': Retrieved counter: 4.00 pulses/min
[D][sensor:092]: 'Meter Power': Sending state 0.24000 kW with 3 decimals of accuracy
[D][sensor:092]: 'Meter Energy': Sending state inf kWh with 1 decimals of accuracy
[D][pulse_counter:159]: 'Meter Power': Retrieved counter: 5.00 pulses/min
[D][sensor:092]: 'Meter Power': Sending state 0.30000 kW with 3 decimals of accuracy
[D][sensor:092]: 'Meter Energy': Sending state inf kWh with 1 decimals of accuracy
[D][dht:048]: Got Temperature=28.8°C Humidity=31.5%
[D][sensor:092]: 'Boiler Room Temperature': Sending state 28.80000 °C with 1 decimals of accuracy
[D][sensor:092]: 'Boiler Room Humidity': Sending state 31.50000 % with 0 decimals of accuracy
[D][pulse_counter:159]: 'Meter Power': Retrieved counter: 26.00 pulses/min
[D][sensor:092]: 'Meter Power': Sending state 1.56000 kW with 3 decimals of accuracy
[D][sensor:092]: 'Meter Energy': Sending state inf kWh with 1 decimals of accuracy
[D][pulse_counter:159]: 'Meter Power': Retrieved counter: 6.00 pulses/min
[D][sensor:092]: 'Meter Power': Sending state 0.36000 kW with 3 decimals of accuracy
[D][sensor:092]: 'Meter Energy': Sending state inf kWh with 1 decimals of accuracy
[D][dht:048]: Got Temperature=28.7°C Humidity=31.8%

```

**Additional information and things you've tried:**

The following snips show what is shown in the Front End, the graph showing the Meter Energy appears to 'hold last value' when the reading goes to 'inf'.

![image](https://user-images.githubusercontent.com/53110372/84130793-9ce0ec00-aa3b-11ea-937f-ec9145405c79.png)

![image](https://user-images.githubusercontent.com/53110372/84130952-d44f9880-aa3b-11ea-8bcf-078fabee21db.png)

![image](https://user-images.githubusercontent.com/53110372/84130993-e16c8780-aa3b-11ea-834e-7ed1834709cd.png)

![image](https://user-images.githubusercontent.com/53110372/84131435-72dbf980-aa3c-11ea-8789-f27b93f37de1.png)
