### ISSUE TITLE
Dallas Temperature causes ESP32 module to create a WD error

### ISSUE THREAD

**Issue by Bishbosh02** [esphome/issues#1287]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 Node32 development board and the Dallas DS18B20 sensor on Hass.io

I have only configured the one sensor and have tried it on pin 23,15 and pin 4 with the same results, the same config works fine on an 8266 NodeMCU  with pin 4

I suspect that the wire.h is taking to long to read the scratch memory and not yielding to the WD interrupt  

Flowing the documentation 
https://esphome.io/components/sensor/dallas.html
and this example
https://randomnerdtutorials.com/esp32-multiple-ds18b20-temperature-sensors/

I suspect if I did it in Aurdino it would work but I need to use ESPHome for this project 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: esp32test
  platform: ESP32
  arduino_version: 1.0.4
  board: nodemcu-32s

wifi:
  ssid: "MySid"
  password: "MyPassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Test Fallback Hotspot"
    password: "RSnYtuc9Yx9E"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
dallas:
  - pin: GPIO4
```

**Logs (if applicable):**

[0;32m[I][logger:156]: Log initialized[0m
[0;35m[C][ota:364]: There have been 0 suspected unsuccessful boot attempts.[0m
[0;32m[I][app:028]: Running through setup()...[0m
[0;35m[C][dallas.sensor:032]: Setting up DallasComponent...[0m
[0;35m[C][wifi:033]: Setting up WiFi...[0m
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
Core 1 register dump:
PC      : 0x4008bac6  PS      : 0x00060f34  A0      : 0x8008aca3  A1      : 0x3ffb1770  
A2      : 0x3ffb7d7c  A3      : 0x3ffb8074  A4      : 0x00000001  A5      : 0x00000001  
A6      : 0x00060f23  A7      : 0x00000000  A8      : 0x3ffb8074  A9      : 0x3ffb8074  
A10     : 0x00000001  A11     : 0x00000001  A12     : 0x00000020  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x0000000e  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x40001609  LEND    : 0x4000160d  LCOUNT  : 0x00000000  

Backtrace: 0x4008bac6:0x3ffb1770 0x4008aca0:0x3ffb1790 0x40088f3b:0x3ffb17b0 0x400ebe5e:0x3ffb17f0 0x400ebf1e:0x3ffb1810 0x400870f6:0x3ffb1830 0x4008762a:0x3ffb1850 0x400fd781:0x3ffb18c0 0x400fc049:0x3ffb18e0 0x400fc497:0x3ffb1900 0x400fae21:0x3ffb1970 0x400fb21d:0x3ffb19c0 0x400fb354:0x3ffb1a40 0x400fa2ea:0x3ffb1aa0 0x400fa951:0x3ffb1ae0 0x4014776e:0x3ffb1b00 0x40147962:0x3ffb1b50 0x401479b5:0x3ffb1b80 0x400fdc2f:0x3ffb1ba0 0x400fdd82:0x3ffb1bc0 0x400ea3d1:0x3ffb1be0 0x400df51c:0x3ffb1c00 0x400da115:0x3ffb1d00 0x400da174:0x3ffb1d30 0x400d9368:0x3ffb1d60 0x4015c851:0x3ffb1d80 0x4015c90d:0x3ffb1da0 0x400dba85:0x3ffb1dc0 0x400dd11e:0x3ffb1e10 0x400e77e3:0x3ffb1fb0 0x40089135:0x3ffb1fd0

Core 0 register dump:
PC      : 0x400895ee  PS      : 0x00060034  A0      : 0x80089d4d  A1      : 0x3ffbbf40  
A2      : 0x3ffbf334  A3      : 0xb33fffff  A4      : 0x00060023  A5      : 0x003fffff  
A6      : 0x00060021  A7      : 0x00000000  A8      : 0x0000abab  A9      : 0x0000cdcd  
A10     : 0x0000abab  A11     : 0x00060023  A12     : 0x00060021  A13     : 0x3ffbbff0  
A14     : 0x00000003  A15     : 0x00060f23  SAR     : 0x0000001f  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x400895ee:0x3ffbbf40 0x40089d4a:0x3ffbbf70 0x4008b964:0x3ffbbf90 0x4008b91a:0x3ffbbfb0 0x4008c66f:0x00000000

Rebooting...
ets Jun  8 2016 00:22:57

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
