### ISSUE TITLE
No "oscillation" toggle for speed.fan in HAss

### ISSUE THREAD

**Issue by fantomnotabene** [esphome/issues#1298]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io, ESPHome v1.14.4

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, nodemcuv2

**Affected component:**

fan

**Description of problem:**
<img width="358" alt="Снимок экрана 2020-06-15 в 14 46 50" src="https://user-images.githubusercontent.com/9576189/84653973-0dde4300-af17-11ea-97e7-4ccd7d46ad68.png">
No oscillation toggle.

**Problem-relevant YAML-configuration entries:**
```yaml
fan:
  - platform: speed
    output: ballu_fan_speed_output
    oscillation_output: ballu_fan_oscillation_output
    name: "Ballu Fan"
```

**Logs (if applicable):**

```
[speed.fan:047]: Setting oscillation: OFF
```
Shows off on every interaction.
**Additional information and things you've tried:**
SUPPORT_SET_SPEED = 1
SUPPORT_OSCILLATE = 2
So `supported_features` should be `3`, but there is `1`

*UPD:* Just set up the `web_server`, and there is no `oscillation` in the
```json
{
  "id":"fan-ballu_fan",
  "state":"OFF",
  "value":false,
  "speed":"low"
}
```
either.
