### ISSUE TITLE
Cannot use ADC sensor with ESP32 Cam

### ISSUE THREAD

**Issue by raresserban** [esphome/issues#1301]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant OS 0.111.3, EspHome addon 1.14.4.

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 Cam Ai Thinkerer

**Affected component:**

Analog to Digital Sensor:
https://esphome.io/components/sensor/adc.html?highlight=esp32

**Description of problem:**
I want to use the ADC sensor with an ESP32 Cam, I what to add a photoresistor on pin 13. However, I get an error that for ESP32 only pins 32 to 39 can be used (the documentation already states this).
However, I have checked the pinout of the ESP32 Cam board, and pin 13 should support ADC, according to this:
https://randomnerdtutorials.com/esp32-cam-ai-thinker-pinout/

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: adc
    pin: 13
    name: Hallway Brightness
    update_interval: 10s
    attenuation: 11db
```

**Logs (if applicable):**

```
None
```

**Additional information and things you've tried:**
I believe that for `board: esp32cam`, other pins besides 32 to 39 should also be supported by ADC.
