### ISSUE TITLE
Multiple Include Templates are not merged

### ISSUE THREAD

**Issue by jeremywillans** [esphome/issues#1306]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

Substitutions

**Description of problem:**
Trying to use a combination of both a template and a common configuration file however the sections are not being merged if they are in both, only the section from the second (or last) file is included.

In the below example, the binary_sensor in the kogan template file is not compiled.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  device_name: kogan_plug_2
  device_ip: 192.168.10.5

<<: !include templates/kogan_plug_gen2.yaml
<<: !include common_config.yaml
```
```yaml
## kogan_plug_gen2.yaml
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285

binary_sensor:
  - platform: gpio
    pin:
      number: 03
      mode: INPUT_PULLUP
      inverted: true
    name: "${device_name}_button"
    on_press:
      - switch.toggle: relay
```
```yaml
## common_config.yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.10.1
    subnet: 255.255.255.0

logger:

web_server:
  port: 80
  
api:
  reboot_timeout: 15min
  password: !secret api_password

ota:
  password: !secret ota_password
  
binary_sensor:
  - platform: status
    name: "${device_name}_status"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
