### ISSUE TITLE
Sonoff touch 1ch sensor backlight gone

### ISSUE THREAD

**Issue by kevinblo** [esphome/issues#1307]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff Touch 1ch

**Affected component:**

https://esphome.io/devices/sonoff_t1_uk_3gang_v1.1.html

**Description of problem:**
There are several touch on 1 and 2 keys. After moving to esphome, on 1 keyboards, the sensor is no longer lit, on 2 keyboards it is lit. The configuration is the same (except for the number of relays). The switches themselves are working correctly. There is a solution?

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: sonoff_touch_sconce
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ""
  password: ""
  use_address: 192.168.1.206

  ap:
    ssid: "Sonoff Touch Sconce"
    password: ""

captive_portal:

logger:

api:
  password: ""

ota:
  password: ""

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sconce light switch"
    on_click: 
      then:
        - switch.toggle: relay
  - platform: status
    name: "Sconce light status"

switch:
  - platform: gpio
    name: "Sconce light relay"
    pin: GPIO12
    id: relay

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  - platform: monochromatic
    name: "Sconce light led"
    output: blue_led
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
