### ISSUE TITLE
Sonoff touch TX touch backlight turn off

### ISSUE THREAD

**Issue by MeloT88** [esphome/issues#1310]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio in docker container
**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff Touch TX Series 3 gangs
**Affected component:**

https://esphome-configs.io/devices/sonoff-t1-r2/

**Description of problem:**
I would like to separate the backlight of the touch button from the relay and be able to turn off the back lights of each single touch. 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: masterwallswitch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Master Touch1"
    on_press:
      - switch.toggle: relay_1
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Master Touch2"
    # on_press:
    #   - switch.toggle: relay_2
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - homeassistant.service:
              service: switch.toggle
              data:
                entity_id: switch.bedside_lamps2_2
          - logger.log: "Dining Lamp"  
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Master Touch3"
    # on_press:
    #   - switch.toggle: relay_3
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - homeassistant.service:
              service: switch.toggle
              data:
                entity_id: switch.bedside_lamps_2
          - logger.log: "Dining Lamp"
      - timing:
          - ON for 3s to 5s
          - OFF for at least 0.5s
        then:
          - homeassistant.service:
              service: homeassistant.turn_off
              data:
                entity_id: group.common_area_lights
          - logger.log: "Single Long Clicked"
  - platform: status
    name: "Sonoff TX 3 Gang Status"

switch:
  - platform: gpio
    name: "Master Relay1"
    pin: GPIO12
    id: relay_1
  - platform: gpio
    name: "Master Relay2"
    pin: GPIO5
    id: relay_2
  - platform: gpio
    name: "Master Relay3"
    pin: GPIO4
    id: relay_3

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Sonoff TX 3 Gang Blue LED"
    output: blue_led
    internal: true
    id: blue_led_light
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
