### ISSUE TITLE
Unsolicited reboots of ESP32 QUINLED on HA

### ISSUE THREAD

**Issue by Lefuneste83** [esphome/issues#1313]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Home Assitant on Docker Home Assistant 0.111.4

Issue occurs with compiled firmware against Dev and 1.14.5. 1.14.4 does not allow the ESP32 to reboot properly due to another bug with one of the sensors.

**ESP (ESP32/ESP8266, Board/Sonoff):**
Esp32 mhetesp32devkit

**Affected component:**
wifi
output
light

**Description of problem:**
Unsolicited reboots of the ESP32 :
-At random moments
-In particular when controlling several GPIO on the same ESP32 through a light group entity (in configuration.yaml) for brightness.

light:
  - platform: group
    name: "LED Cave"
    entities:
      - light.led_cave_01_a
      - light.led_cave_01_b

The ESP32 is coupled with a QUINLED QUAD which has been running flawlessly for more than a year.
The issue occurs whatever the hardware used (tried with several ESP32/QUINLED Boards). The ESP32 seems to disconnect or be disconnected then reconnects rapidly. This reboot problem appeared a few days ago and now that I am investigating it seems obvious that there is a regression in one of the components. It may be related to HA less likely to the Wifi.

**Problem-relevant YAML-configuration entries:**

```
esphome:
  name: led_cave_01
  platform: ESP32
  board: mhetesp32devkit

wifi:
  ssid: "SSID
  password: "mypassword"
  fast_connect: on
  manual_ip:
    static_ip: 192.168.X.X
    gateway: 192.168.X.X
    subnet: 255.255.255.X
    dns1: 192.168.X.X
    dns2: 8.8.8.8
    
mqtt:
  broker: "192.168.X.X"
  username: "mylogin"
  password: "mysecret
  birth_message:
  will_message:
  
# Enable logging
logger:

ota:
  password: "otapassword"

dallas:
  - pin: GPIO18

switch:
  - platform: gpio
    name: "Led Cave 01 Onboard Light"
    pin: 2

output:
  - platform: ledc
    pin: 16
    frequency: "40000Hz"
    id: LED_gpio_16
  - platform: ledc
    pin: 17
    frequency: "40000Hz"
    id: LED_gpio_17
  - platform: ledc
    pin: 5
    frequency: "40000Hz"
    id: LED_gpio_5
  - platform: ledc
    pin: 19
    frequency: "40000Hz"
    id: LED_gpio_19

light:
  - platform: cwww
    name: "Led Cave 01 A"
    warm_white: LED_gpio_16
    cold_white: LED_gpio_17
    warm_white_color_temperature: 3000 K
    cold_white_color_temperature: 6000 K
    default_transition_length: 1s

  - platform: cwww
    name: "Led Cave 01 B"
    warm_white: LED_gpio_5
    cold_white: LED_gpio_19
    warm_white_color_temperature: 3000 K
    cold_white_color_temperature: 6000 K
    default_transition_length: 1s
    
sensor:
  - platform: wifi_signal
    name: "Led Cave 01 Wifi Signal Sensor"
    update_interval: 60s

  - platform: dallas
    index: 0
    name: "Led Cave 01 Temperature Sensor"
```
```

**Logs (if applicable):**
No significant info in the logs. THe ESP32 just reboot, flickers the light once, then goes back to logging 
Increasing loglevel to VERBOSE does not bring further information.

INFO Reading configuration /config/esphome/led_cave_01.yaml...
INFO Starting log output from led_cave_01/debug
INFO Connected to MQTT broker!


```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
The issue seems mitigated when directly controlling entities without using light group configuration from HA. The reboot still occurs but randomly. Controlling through light group triggers the reboot about 20% of the time.
I will try to pinpoint the issue further in the coming days.

<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
