### ISSUE TITLE
MQTT on_json_message() conditions are not parsed correctly.

### ISSUE THREAD

**Issue by algirdasc** [esphome/issues#1314]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Esphome 1.14.4 on Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (LEDENET Smart WiFi LED Controller 5 Channel)

**Affected component:**

https://esphome.io/components/mqtt.html?highlight=mqtt%20json#mqtt-publish-json-action

**Description of problem:**
After update from 1.14.3 to 1.14.4 version MQTT JSON message condition seems broken. When `{"occupancy": true}` both of conditions are evaluated to true. It looks like I cannot re-use `x["occupancy"]`, because after first use it is evaluated to `false` regardless it is set to `true`. I've tried reordering conditions which solved the problem - putting `return x["occupancy"] == false;` in front of the condition list solves the issue. It can be reproduced in 3 same devices.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: False
  on_json_message:
    topic: zigbee2mqtt/motion1_sensor
    then:
      - if:
          condition: 
            and:
              - lambda: 'return x["occupancy"] == true;'
              - light.is_on: ${esp_id}_strip
          then:
            - light.turn_on: 
                id: ${esp_id}_strip
                brightness: 65%
                white: 50%
      - if:
          condition: 
            and:
              - lambda: 'return x["occupancy"] == false;'
              - light.is_on: ${esp_id}_strip
          then:
            - light.turn_on: 
                id: ${esp_id}_strip
                brightness: 15%      
                white: 15%
                transition_length: 60s      
```

**Logs (if applicable):**

When `{"occupancy": false}`:
```
[09:51:20][D][light:264]: 'Bedroom LED1 Strip' Setting:
[09:51:20][D][light:277]:   Brightness: 15%
[09:51:20][D][light:289]:   White Value: 15%
[09:51:20][D][light:303]:   Transition Length: 60.0s
```

When `{"occupancy": true}`:
```
[09:52:01][D][light:264]: 'Bedroom LED1 Strip' Setting:
[09:52:01][D][light:277]:   Brightness: 65%
[09:52:01][D][light:289]:   White Value: 50%
[09:52:01][D][light:303]:   Transition Length: 1.0s
[09:52:01][D][light:264]: 'Bedroom LED1 Strip' Setting:
[09:52:01][D][light:277]:   Brightness: 15%
[09:52:01][D][light:289]:   White Value: 15%
[09:52:01][D][light:303]:   Transition Length: 60.0s
```

**Additional information and things you've tried:**
