### ISSUE TITLE
captive portals not working on certain Sonoff devices with 1.15.0-dev

### ISSUE THREAD

**Issue by phixion** [esphome/issues#1316]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Homeassisant supervised w/ current esphome-dev addon esphome==1.15.0.dev0

**ESP (ESP32/ESP8266, Board/Sonoff):**
Sonoff T3 Touch Lightswitches
Sonoff Basic R2
Sonoff TH16
Nodemcus
Luminea LED controllers

**Affected component:**

wifi fallback APs/captive portals

**Description of problem:**
wifi fallback APs are being spawned but the captive portals are not popping up. I have flashed around 15 devices but it only happens on:

- Sonoff T3 Touch Lightswitches
- Sonoff Basic R2

Since its the second time I see that behaviour, I thought it might be a bug. I run the same wifi config accross all my devices. 

**Problem-relevant YAML-configuration entries:**
```yaml
networks:
  - ssid: !secret iot_ssid # pragma: allowlist secret
    password: !secret phixnet_wifi_iot_pwd # pragma: allowlist secret
    hidden: true
fast_connect: true
domain: !secret domain # pragma: allowlist secret
power_save_mode: none
#output_power: 20dB
ap:
  ssid: !secret fallback_ssid # pragma: allowlist secret
  password: !secret fallback_wifi_pwd # pragma: allowlist secret

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

wifi.yaml:
https://github.com/phixion/Home-AssistantConfig/blob/master/esphome/shared/wifi.yaml

affected devices:
sonoff basic: https://github.com/phixion/Home-AssistantConfig/blob/master/esphome/schalter1.yaml
sonoff t3: https://github.com/phixion/Home-AssistantConfig/blob/master/esphome/switchbad.yaml
