### ISSUE TITLE
Bang Bang climate control does not switch from "Off" to "Idle" until it has cycled through "Cool"

### ISSUE THREAD

**Issue by jptrsn** [esphome/issues#1317]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 Mini

**Affected component:**

[Bang Bang Climate](https://esphome.io/components/climate/bang_bang.html)

**Description of problem:**
When changing the state of the bang-bang climate from off to cool, the thermostat remains in the "Off" state unless it transitions into the "Cool" state. For example, if I set my air conditioner to 25 degrees, and the temperature sensor is at 23 degrees, then I change the thermostat state from "Off" to "Cool" it remains in the off state. This doesn't trigger the `idle_action` as expected.

**Problem-relevant YAML-configuration entries:**
```yaml
climate:
  - platform: bang_bang
    name: ${DEVICE_NAME} Thermostat
    sensor: temp
    default_target_temperature_high: ${TARGET_TEMP}
    id: therm

    cool_action:
      - script.execute: on_cool
    idle_action:
      - script.execute: on_idle
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

I'm currently using the dev branch of esphome, as it supports single-set-point in the bang bang climate platform. This may not be a visible problem yet, but could possibly affect the next release.
