### ISSUE TITLE
gate_pin option on ac_dimmer component doesn't honor pin schema

### ISSUE THREAD

**Issue by tracestep** [esphome/issues#1318]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass OS 4.10 (Home Assistant 0.111.4) on Virtualbox x86_64, python 3.7.7, using ESPHome dev 1.14.5

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP01 1MB flash board

**Affected component:**

`ac_dimmer` component

**Description of problem:**
ac_dimmer does not honor `inverted: yes` option for `gate_pin`: pin is high when dimmer is off and low when at 100% birghtness, which is expected behavior with `inverted: yes` option. But when dimmer is between 1 and 254 the pulse is active high (same behavior as with `inverted: no`). This result in the load being 100% on independent of the brightness adjustment.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test
  platform: ESP8266
  board: esp01_1m

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: GPIO2
    method: leading_pulse
    min_power: 0%
    init_with_half_cycle: false
    inverted: yes
    zero_cross_pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: no

light:
  - platform: monochromatic
    output: dimmer1
    name: Dimmer Light
    gamma_correct: 2
```

**Logs (if applicable):**

not applicable

**Additional information and things you've tried:**
Scope capture attached - brightness at ~80 (32%); zero-cross circuit with SFH620 (emitter to GND, collector on GPIO1). MOC3021 triac driver (anode to +3.3V via 330R resistor, cathode to GPIO2).

![ac_dimmer](https://user-images.githubusercontent.com/16390082/86281073-50f51300-bbb3-11ea-9c82-a8b3e43219a5.png)

**Comment by glmnet** [comment]
if you're trying to invert gate pin you should write something like:

```yaml
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 
      number: GPIO2
      inverted: yes
    method: leading_pulse
    min_power: 0%
    init_with_half_cycle: false
    zero_cross_pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: no
````
