### ISSUE TITLE
Ultrasonic Distance Sensor issues 

### ISSUE THREAD

**Issue by royasulin** [esphome/issues#1320]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant 0.111.4
esphome: 1.14.5

**ESP (ESP32/ESP8266, Board/Sonoff):**

platform: ESP8266
 board: nodemcuv2 

**Affected component:**

https://esphome.io/components/sensor/ultrasonic.html

**Description of problem:**
the ultrasonic ( hc-sr04)  sensor is reporting a fixed value and not updating even if we change the update_interval parameter 
Tested on two different boards and two different HC-SR04. 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

- platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    name: "level in cm"
    update_interval: 3s
    filters:
    # Replace the 0.42 by the height of your container. From the sensor to the bottom.
    # I multiplied by 100 in order to get CM since the sensor works in meters
    - lambda: return (0.42-x)*100;
    unit_of_measurement: "cm"

**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
