### ISSUE TITLE
xiaomi_hhccjcy01 missing battery_level

### ISSUE THREAD

**Issue by CODeRUS** [esphome/issues#1323]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** esphome-1.15.0-dev esphome/esphome:dev Docker

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP32

**Affected component:** https://next.esphome.io/components/sensor/xiaomi_ble.html?highlight=ble#hhccjcy01

**Description of problem:**
Compilation failed

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: xiaomi_hhccjcy01
    battery_level:
      name: "Xiaomi HHCCJCY01 Battery Level"
```

**Logs (if applicable):**

```
[battery_level] is an invalid option for [sensor.xiaomi_hhccjcy01]. Please check the indentation.

```

**Additional information and things you've tried:**
https://github.com/esphome/esphome/commit/3fba3a5e2e812485a49dd7cf38aed7e1ff403c94
