### ISSUE TITLE
Cant send SMS with sim800l with esp32

### ISSUE THREAD

**Issue by delta010** [esphome/issues#1326]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

 Esp32 (TTGO T-Call ESP32 with SIM800L)

**ESPHome version (latest production, beta, dev branch)**

1.14.4 

**Affected component:**

https://esphome.io/components/sim800l.html

**Description of problem:**
I am  using TTGO T-Call ESP32 with SIM800L for sending and receiving SMS . when I send an SMS to my phone via home assistant service nothing happens the ESphome log says "Sending to +XXXXXXXXXx: Hello World!" but I don't receive any SMS

**Problem-relevant YAML-configuration entries:**
```yaml

esphome:
  name: esp32gsm
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "xXXXXXXXXX"
  password: "xxxxxxxxxx"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.217
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
    dns1: 192.168.1.1
ota:

# Enable logging
logger:

# Enable Home Assistant API
web_server:
  port: 80
  
i2c:  
  sda: GPIO21
  scl: GPIO22
  scan: True
  
# Enable Home Assistant API

api:
  services:
  - service: send_sms
    variables:
      recipient: string
      message: string
    then:
    - sim800l.send_sms:
        recipient: !lambda 'return recipient;'
        message: !lambda 'return message;'

uart:
  baud_rate: 9600
  tx_pin: TX
  rx_pin: RX
sim800l:
  on_sms_received:
    - lambda: |-
        id(sms_sender).publish_state(sender);
        id(sms_message).publish_state(message);
    - logger.log:
        format: "Received '%s' from %s"
        args: [ 'message.c_str()', 'sender.c_str()' ]

text_sensor:
- platform: template
  id: sms_sender
  name: "Sms Sender"
- platform: template
  id: sms_message
  name: "Sms Message"
    
time:
  - platform: sntp
    id: timer
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

switch:
  - platform: gpio
    name: "SIM800_PWKEY"
    pin: 4
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "SIM800_RST"
    pin: 5
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "SIM800_POWER"
    pin: 23
    restore_mode: ALWAYS_ON
```

**Logs (if applicable):**

```
[13:05:36][C][wifi:415]: WiFi:
[13:05:36][C][wifi:283]:   SSID: 

[redacted]
[13:05:36][C][wifi:284]:   IP Address: 192.168.1.217
[13:05:36][C][wifi:286]:   BSSID: 

[redacted]
[13:05:36][C][wifi:287]:   Hostname: 'ttgo_t_call_esp32'
[13:05:36][C][wifi:291]:   Signal strength: -17 dB ▂▄▆█
[13:05:36][C][wifi:295]:   Channel: 11
[13:05:36][C][wifi:296]:   Subnet: 255.255.255.0
[13:05:36][C][wifi:297]:   Gateway: 192.168.1.1
[13:05:36][C][wifi:298]:   DNS1: 192.168.1.1
[13:05:36][C][wifi:299]:   DNS2: 0.0.0.0
[13:05:36][C][uart:040]: UART Bus:
[13:05:36][C][uart:042]:   TX Pin: GPIO1
[13:05:36][C][uart:045]:   RX Pin: GPIO3
[13:05:36][C][uart:047]:   Baud Rate: 9800 baud
[13:05:36][C][uart:048]:   Stop bits: 1
[13:05:36][C][template.text_sensor:020]: Template Sensor 'Sms Sender'
[13:05:36][C][template.text_sensor:020]: Template Sensor 'Sms Message'
[13:05:36][C][switch.gpio:042]: GPIO Switch 'SIM800_PWKEY'
[13:05:36][C][switch.gpio:043]:   Pin: GPIO4 (Mode: OUTPUT)
[13:05:36][C][switch.gpio:059]:   Restore Mode: Always OFF
[13:05:36][C][switch.gpio:042]: GPIO Switch 'SIM800_RST'
[13:05:36][C][switch.gpio:043]:   Pin: GPIO5 (Mode: OUTPUT)
[13:05:36][C][switch.gpio:059]:   Restore Mode: Always ON
[13:05:36][C][switch.gpio:042]: GPIO Switch 'SIM800_POWER'
[13:05:36][C][switch.gpio:043]:   Pin: GPIO23 (Mode: OUTPUT)
[13:05:36][C][switch.gpio:059]:   Restore Mode: Always ON
[13:05:36][C][logger:175]: Logger:
[13:05:36][C][logger:176]:   Level: DEBUG
[13:05:36][C][logger:177]:   Log Baud Rate: 0
[13:05:36][C][logger:178]:   Hardware UART: UART0
[13:05:36][C][sim800l:259]: SIM800L:
[13:05:36][C][sim800l:260]:   RSSI: 0 dB
[13:05:36][C][web_server:123]: Web Server:
[13:05:36][C][web_server:124]:   Address: 192.168.1.217:80
[13:05:36][C][ota:029]: Over-The-Air Updates:
[13:05:36][C][ota:030]:   Address: 192.168.1.217:3232
[13:05:36][C][api:095]: API Server:
[13:05:36][C][api:096]:   Address: 192.168.1.217:6053
[13:05:36][C][sntp:043]: SNTP Time:
[13:05:36][C][sntp:044]:   Server 1: '0.pool.ntp.org'
[13:05:36][C][sntp:045]:   Server 2: '1.pool.ntp.org'
[13:05:36][C][sntp:046]:   Server 3: '2.pool.ntp.org'
[13:05:36][C][sntp:047]:   Timezone: 'IST-5:30'
[13:05:38][D][api.connection:583]: Client 'Home Assistant 0.111.0 (192.168.1.5)' connected successfully!
[13:07:31][I][ota:046]: Boot seems successful, resetting boot loop counter.
[13:07:59][D][switch:021]: 'SIM800_PWKEY' Turning ON.
[13:07:59][D][switch:045]: 'SIM800_PWKEY': Sending state ON
[13:08:07][D][sim800l:252]: Sending to +919744019818: Hello World!

```

**Additional information and things you've tried:**

**Comment by rradar** [comment]
Could you please provide a log with `very_verbose` @delta010 ?

Can you conform the the same sim800l works with a esp8266 and doesn't work with another esp32?

**Comment by delta010** [comment]
Log with very_verbos
`
INFO Reading configuration /config/esphome/ttgo_t_call_esp32.yaml...
INFO Detected timezone 'IST' with UTC offset 5:30
INFO Starting log output from 192.168.1.217 using esphome API
INFO Connecting to 192.168.1.217:6053 (192.168.1.217)
INFO Successfully connected to 192.168.1.217
[21:38:39][I][app:100]: ESPHome version 1.14.4 compiled on Jul  4 2020, 21:35:31
[21:38:39][C][wifi:415]: WiFi: xxxxxxx
[21:38:39][C][wifi:283]:   SSID: xxxxxxxx

[redacted]
[21:38:39][C][wifi:284]:   IP Address: 192.168.1.217
[21:38:39][C][wifi:286]:   BSSID: xxxxxxxxxx

[redacted]
[21:38:39][C][wifi:287]:   Hostname: 'ttgo_t_call_esp32'
[21:38:39][C][wifi:291]:   Signal strength: -18 dB ▂▄▆█
[21:38:39][V][wifi:293]:   Priority: 0.0
[21:38:39][C][wifi:295]:   Channel: 11
[21:38:39][C][wifi:296]:   Subnet: 255.255.255.0
[21:38:39][C][wifi:297]:   Gateway: 192.168.1.1
[21:38:39][C][wifi:298]:   DNS1: 192.168.1.1
[21:38:39][C][wifi:299]:   DNS2: 0.0.0.0
[21:38:39][C][uart:040]: UART Bus:
[21:38:39][C][uart:042]:   TX Pin: GPIO26
[21:38:39][C][uart:045]:   RX Pin: GPIO27
[21:38:39][C][uart:047]:   Baud Rate: 9800 baud
[21:38:39][C][uart:048]:   Stop bits: 1
[21:38:39][C][template.text_sensor:020]: Template Sensor 'Sms Sender'
[21:38:39][C][template.text_sensor:020]: Template Sensor 'Sms Message'
[21:38:39][C][switch.gpio:042]: GPIO Switch 'SIM800_PWKEY'
[21:38:39][C][switch.gpio:043]:   Pin: GPIO4 (Mode: OUTPUT)
[21:38:39][C][switch.gpio:059]:   Restore Mode: Always OFF
[21:38:39][C][switch.gpio:042]: GPIO Switch 'SIM800_RST'
[21:38:39][C][switch.gpio:043]:   Pin: GPIO5 (Mode: OUTPUT)
[21:38:39][C][switch.gpio:059]:   Restore Mode: Always ON
[21:38:39][VV][uart:070]:     Read 0b00000000 (0x00)
[21:38:39][VV][sim800l:230]: Buffer pos: 1 0
[21:38:39][C][switch.gpio:042]: GPIO Switch 'SIM800_POWER'
[21:38:39][C][switch.gpio:043]:   Pin: GPIO23 (Mode: OUTPUT)
[21:38:39][C][switch.gpio:059]:   Restore Mode: Always ON
[21:38:39][C][logger:175]: Logger:
[21:38:39][C][logger:176]:   Level: VERY_VERBOSE
[21:38:39][C][logger:177]:   Log Baud Rate: 115200
[21:38:39][C][logger:178]:   Hardware UART: UART0
[21:38:39][C][sim800l:259]: SIM800L:
[21:38:39][C][sim800l:260]:   RSSI: 0 dB
[21:38:39][C][web_server:123]: Web Server:
[21:38:39][C][web_server:124]:   Address: 192.168.1.217:80
[21:38:39][C][ota:029]: Over-The-Air Updates:
[21:38:39][C][ota:030]:   Address: 192.168.1.217:3232
[21:38:39][C][api:095]: API Server:
[21:38:39][C][api:096]:   Address: 192.168.1.217:6053
[21:38:39][C][sntp:043]: SNTP Time:
[21:38:39][C][sntp:044]:   Server 1: '0.pool.ntp.org'
[21:38:39][C][sntp:045]:   Server 2: '1.pool.ntp.org'
[21:38:39][C][sntp:046]:   Server 3: '2.pool.ntp.org'
[21:38:39][C][sntp:047]:   Timezone: 'IST-5:30'
[21:38:40][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=128296 (now=133296)
[21:38:42][VV][uart:070]:     Read 0b00000000 (0x00)
[21:38:42][VV][sim800l:230]: Buffer pos: 2 0
[21:38:44][VV][api.service:250]: on_ping_request: PingRequest {}
[21:38:44][VV][api.service:035]: send_ping_response: PingResponse {}
[21:38:44][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=133296 (now=138296)
[21:38:45][VV][uart:070]:     Read 0b00000000 (0x00)
[21:38:45][VV][sim800l:230]: Buffer pos: 3 0
[21:38:45][VV][scheduler:131]: Running interval '' with interval=10000 last_execution=129289 (now=139289)
[21:38:48][VV][uart:070]:     Read 0b00000000 (0x00)
[21:38:48][VV][sim800l:230]: Buffer pos: 4 0
[21:38:49][VV][api.service:250]: on_ping_request: PingRequest {}
[21:38:49][VV][api.service:035]: send_ping_response: PingResponse {}
[21:38:49][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=138296 (now=143296)
[21:38:49][VV][uart:054]:     Wrote 0b00011010 (0x1A)
[21:38:49][V][sim800l:041]: S: AT - 1
[21:38:49][VV][uart:064]:     Wrote "AT"
[21:38:49][VV][uart:054]:     Wrote 0b00001010 (0x0A)
[21:38:49][VV][uart:070]:     Read 0b00011010 (0x1A)
[21:38:49][VV][sim800l:230]: Buffer pos: 5 26
[21:38:49][VV][uart:070]:     Read 0b01000001 (0x41)
[21:38:49][VV][sim800l:230]: Buffer pos: 6 65
[21:38:49][VV][uart:070]:     Read 0b01010100 (0x54)
[21:38:49][VV][sim800l:230]: Buffer pos: 7 84
[21:38:49][VV][uart:070]:     Read 0b00001010 (0x0A)
[21:38:49][VV][sim800l:230]: Buffer pos: 8 10
[21:38:49][V][sim800l:048]: R:  - 2
[21:38:50][VV][api.service:250]: on_ping_request: PingRequest {}
[21:38:50][VV][api.service:035]: send_ping_response: PingResponse {}
[21:38:51][VV][uart:070]:     Read 0b00000000 (0x00)
[21:38:51][VV][sim800l:230]: Buffer pos: 0 0
[21:38:54][VV][uart:070]:     Read 0b00000000 (0x00)
[21:38:54][VV][sim800l:230]: Buffer pos: 1 0
[21:38:55][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=143296 (now=148296)
[21:38:55][VV][api.service:250]: on_ping_request: PingRequest {}
[21:38:55][VV][api.service:035]: send_ping_response: PingResponse {}
[21:38:55][VV][scheduler:131]: Running interval '' with interval=10000 last_execution=139289 (now=149292)
[21:38:57][VV][uart:070]:     Read 0b00000000 (0x00)
[21:38:57][VV][sim800l:230]: Buffer pos: 2 0
[21:38:59][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=148296 (now=153296)
[21:39:00][VV][api.service:250]: on_ping_request: PingRequest {}
[21:39:00][VV][api.service:035]: send_ping_response: PingResponse {}
[21:39:00][VV][scheduler:131]: Running interval 'update' with interval=60000 last_execution=93718 (now=153718)
[21:39:00][VV][uart:070]:     Read 0b00000000 (0x00)
[21:39:00][VV][sim800l:230]: Buffer pos: 3 0
[21:39:03][VV][uart:070]:     Read 0b00000000 (0x00)
[21:39:03][VV][sim800l:230]: Buffer pos: 4 0
[21:39:04][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=153296 (now=158300)
[21:39:04][VV][uart:054]:     Wrote 0b00011010 (0x1A)
[21:39:04][V][sim800l:041]: S: AT - 1
[21:39:04][VV][uart:064]:     Wrote "AT"
[21:39:04][VV][uart:054]:     Wrote 0b00001010 (0x0A)
[21:39:04][VV][uart:070]:     Read 0b00011010 (0x1A)
[21:39:04][VV][sim800l:230]: Buffer pos: 5 26
[21:39:04][VV][uart:070]:     Read 0b01000001 (0x41)
[21:39:04][VV][sim800l:230]: Buffer pos: 6 65
[21:39:04][VV][uart:070]:     Read 0b01010100 (0x54)
[21:39:04][VV][sim800l:230]: Buffer pos: 7 84
[21:39:04][VV][uart:070]:     Read 0b00001010 (0x0A)
[21:39:04][VV][sim800l:230]: Buffer pos: 8 10
[21:39:04][V][sim800l:048]: R:  - 2
[21:39:05][VV][api.service:250]: on_ping_request: PingRequest {}
[21:39:05][VV][api.service:035]: send_ping_response: PingResponse {}
[21:39:05][VV][api.service:250]: on_ping_request: PingRequest {}
[21:39:05][VV][api.service:035]: send_ping_response: PingResponse {}
[21:39:05][VV][scheduler:131]: Running interval '' with interval=10000 last_execution=149289 (now=159290)
[21:39:07][VV][uart:070]:     Read 0b00000000 (0x00)
[21:39:07][VV][sim800l:230]: Buffer pos: 0 0
[21:39:09][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=158296 (now=163299)
[21:39:10][VV][uart:070]:     Read 0b00000000 (0x00)
[21:39:10][VV][sim800l:230]: Buffer pos: 1 0
[21:39:10][VV][api.service:250]: on_ping_request: PingRequest {}
[21:39:10][VV][api.service:035]: send_ping_response: PingResponse {}
[21:39:13][VV][uart:070]:     Read 0b00000000 (0x00)
[21:39:13][VV][sim800l:230]: Buffer pos: 2 0
[21:39:14][VV][scheduler:131]: Running interval 'update' with interval=60000 last_execution=107911 (now=167913)
[21:39:14][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=163296 (now=168296)
[21:39:15][VV][api.service:250]: on_ping_request: PingRequest {}
[21:39:15][VV][api.service:035]: send_ping_response: PingResponse {}
[21:39:15][VV][scheduler:131]: Running interval '' with interval=10000 last_execution=159289 (now=169289)
[21:39:16][VV][uart:070]:     Read 0b00000000 (0x00)
[21:39:16][VV][sim800l:230]: Buffer pos: 3 0
[21:39:19][VV][uart:070]:     Read 0b00000000 (0x00)
[21:39:19][VV][sim800l:230]: Buffer pos: 4 0
[21:39:19][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=168296 (now=173296)
[21:39:19][VV][uart:054]:     Wrote 0b00011010 (0x1A)
[21:39:19][V][sim800l:041]: S: AT - 1
[21:39:19][VV][uart:064]:     Wrote "AT"
[21:39:19][VV][uart:054]:     Wrote 0b00001010 (0x0A)
[21:39:19][VV][uart:070]:     Read 0b00011010 (0x1A)
[21:39:19][VV][sim800l:230]: Buffer pos: 5 26
[21:39:19][VV][uart:070]:     Read 0b01000001 (0x41)
[21:39:19][VV][sim800l:230]: Buffer pos: 6 65
[21:39:19][VV][uart:070]:     Read 0b01010100 (0x54)
[21:39:19][VV][sim800l:230]: Buffer pos: 7 84
[21:39:19][VV][uart:070]:     Read 0b00001010 (0x0A)
[21:39:19][VV][sim800l:230]: Buffer pos: 8 10
[21:39:19][V][sim800l:048]: R:  - 2
[21:39:20][VV][api.service:250]: on_ping_request: PingRequest {}
[21:39:20][VV][api.service:035]: send_ping_response: PingResponse {}
[21:39:20][VV][api.service:250]: on_ping_request: PingRequest {}
[21:39:20][VV][api.service:035]: send_ping_response: PingResponse {}
[21:39:22][VV][uart:070]:     Read 0b00000000 (0x00)
[21:39:22][VV][sim800l:230]: Buffer pos: 0 0
[21:39:24][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=173296 (now=178296)
[21:39:25][VV][uart:070]:     Read 0b00000000 (0x00)
[21:39:25][VV][sim800l:230]: Buffer pos: 1 0
[21:39:25][VV][scheduler:131]: Running interval '' with interval=10000 last_execution=169289 (now=179290)
[21:39:25][VV][api.service:250]: on_ping_request: PingRequest {}
[21:39:25][VV][api.service:035]: send_ping_response: PingResponse {}
[21:39:28][VV][uart:070]:     Read 0b00000000 (0x00)
[21:39:28][VV][sim800l:230]: Buffer pos: 2 0
[21:39:29][VV][scheduler:131]: Running interval 'update' with interval=5000 last_execution=178296 (now=183296) `

and this is my module
![ttgo-t-call-v13-esp32-wifi-wireless-sim800l-gsm-gprs-module-fpc-antenna-development-board](https://user-images.githubusercontent.com/29528880/86516853-b9592400-be41-11ea-9162-f6f439aa6119.jpg)

**Comment by glmnet** [comment]
Ahh good thing you posted the module picture. 
Looks like serial and setup is not done properly

Try following this thread 

https://community.home-assistant.io/t/esp32-sim800l-ttgo-t-call-not-working/149781/15

**Comment by delta010** [comment]
I already followed that thread but nothing changed ;

I also found something strange about the sim800l on the log

`[21:38:39][C][sim800l:259]: SIM800L:
[21:38:39][C][sim800l:260]: RSSI: 0 dB`

**Comment by glmnet** [comment]
Per your verbose logs, the receiver is not getting valid data via serial.

Try changing this

````
uart:
  baud_rate: 9600
  tx_pin: TX
  rx_pin: RX
````

to this as in the thread:

````

Copy to clipboard
uart:
  baud_rate: 9600
  tx_pin: 27
  rx_pin: 26
````
