### ISSUE TITLE
Ethernet reconnect attempts are happening too often (will freeze esphome-flasher GUI)

### ISSUE THREAD

**Issue by aaronk6** [esphome/issues#1328]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

Olimex ESP32-POE

**ESPHome version (latest production, beta, dev branch)**

1.15-dev

**Affected component:**

https://esphome.io/components/ethernet.html

**Description of problem:**

When the Ethernet cable is disconnected, the reconnect attempts are happening too often (seeing 32 log entries per second). This eventually freezes the esphome-flasher GUI.

**Problem-relevant YAML-configuration entries:**
```yaml
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
```

**Logs (if applicable):**

```
[11:39:00][W][ethernet:041]: Connecting via ethernet failed! Re-connecting...
[11:39:00][W][ethernet:041]: Connecting via ethernet failed! Re-connecting...
[11:39:00][W][ethernet:041]: Connecting via ethernet failed! Re-connecting...
…
```

(This is being displayed 32 times per second.)

**Additional information and things you've tried:**

n/a
