### ISSUE TITLE
AHT10 is busy, waiting... Issue reading humidity

### ISSUE THREAD

**Issue by VladoPortos** [esphome/issues#1330]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESP01 with AHT10 sensor, custom board just 5V to 3.3V ( nothing else )
**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**
For some reason Humidity is not always returned from sensor and its returning nothing / unknown value instead. Not sure why is this happening.  

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp01_sensor_aht10
  platform: ESP8266
  board: esp01

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp01 Sensor Setting"
    password: "xxxxx"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxxxx"

ota:
  password: "xxxxx"

web_server:
  port: 80

i2c:
  sda: 0
  scl: 2
  scan: True
  id: bus_a

sensor:
  - platform: aht10
    temperature:
      name: "Temperature_AH10"
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      filters:
        - offset: -2.2
    humidity:
      name: "Humidity_AH10"
      accuracy_decimals: 1
      unit_of_measurement: "%"
      filters:
        - offset: 7.58
    i2c_id: bus_a
    address: 0x38
    update_interval: 90s
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

```

**Logs (if applicable):**

```
[D][aht10:066]: AHT10 is busy, waiting...
[D][sensor:092]: 'Temperature_AH10': Sending state 25.43576 °C with 1 decimals of accuracy
[D][sensor:092]: 'Humidity_AH10': Sending state 57.47672 % with 1 decimals of accuracy
[D][aht10:066]: AHT10 is busy, waiting...
[D][sensor:092]: 'Temperature_AH10': Sending state 25.45827 °C with 1 decimals of accuracy
[D][sensor:092]: 'Humidity_AH10': Sending state 58.07124 % with 1 decimals of accuracy
[D][sensor:092]: 'WiFi Signal Sensor': Sending state -60.00000 dB with 0 decimals of accuracy

```

**Additional information and things you've tried:**
I have tried replace esp01 and AHT10 sensor, it does the same every time... I have also tried interval to 90 sec ...
