### ISSUE TITLE
script.wait never returns and blocks execution indefinitely

### ISSUE THREAD

**Issue by napieraj** [esphome/issues#1341]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io, pip

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32, ESP8266

**ESPHome version (latest production, beta, dev branch)**
current dev, v1.14.5

**Affected component:**
`script.wait` action ([https://esphome.io/guides/automations.html#script-wait-action](https://esphome.io/guides/automations.html#script-wait-action))

**Description of problem:**
The `script.wait` action never returns execution to the sequence from which it was initiated, blocking execution indefinitely -- any actions following it are never executed, even after the script has finished

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  ...
  on_boot:
    priority: -100
    then:
      - delay: 5s
      - logger.log: "Executing Script"
      - script.execute: wait_example
      - logger.log: "Waiting for script"
      - script.wait: wait_example
      - logger.log: "Finished Waiting"

script:
- id: wait_example
  then:
  - logger.log: "Running script"
  - delay: 10s
  - logger.log: "Finished Script"

binary_sensor:
  - platform: template
    name: "Script Running"  
    lambda: |-
      return id(wait_example).script_is_running();
```
**Logs (if applicable):**
A template binary_sensor is attached to script_is_running() to better follow its execution, the script finishes but the logger call following `script.wait` is never called:
```
[D][main:090]: Executing Script
[D][main:164]: Running script
[D][main:175]: Waiting for script
[D][binary_sensor:036]: 'Script Running': Sending state ON
[D][main:179]: Finished Script
[D][binary_sensor:036]: 'Script Running': Sending state OFF
```

**Additional information and things you've tried:**
N/A
