### ISSUE TITLE
Detaching servo causes unintended motion

### ISSUE THREAD

**Issue by ZetaPhoenix** [esphome/issues#1347]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 D1 Mini

**ESPHome version (latest production, beta, dev branch)**

v1.14
v1.15.0-dev

**Affected component:**

servo
https://next.esphome.io/components/servo.html

**Description of problem:**

I order to prevent the cover from moving on reset of the D1 (https://github.com/esphome/issues/issues/964) I switched to the dev branch. After switching to `dev`, when ever I issue a detach for a servo the servo will make an sudden jerk in the CW rotation (negative direction, IE short pulse).

Using detach in the non dev branch works just fine (servo stops driving with out noise or motion) but then the servo will always go to 0 on startup.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
cover:
  - platform: template
    device_class: blind
    name: "Living Room Blinds"

    optimistic: true
    open_action:
    - servo.write:
         id: blind_tilt_servo
         level: 0.0%
    - delay: 4s
    - servo.detach: blind_tilt_servo
    close_action:
    - servo.write:
         id: blind_tilt_servo
         level: -100.0%
    - delay: 4s
    - servo.detach: blind_tilt_servo
    stop_action:
    - servo.detach: blind_tilt_servo

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D3
    frequency: 50 Hz

servo:
  - id: blind_tilt_servo
    output: pwm_output
    min_level: 3.0%
    idle_level: 7.5%
    max_level: 12.0%
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
