### ISSUE TITLE
must be string, got <class 'esphome.helper.OrderedDict'>. did you forget putting quotes around the value?.

### ISSUE THREAD

**Issue by nathan951** [esphome/issues#1350]
```
  - platform: gpio
    pin: GPIO4
    id: pool_heater
    name: Pool Heater
    inverted: True
    on_turn_on:
      - switch.turn_on: pool_pump
      - switch.turn_off: spa_heater
      - homeassistant.service:
          service: notify.nate
          data:
            title: POOL Heater is ON
            message: The pool heater was just turned on.
            data:
              group: 'pool'
```
 Adding: `group: 'pool' `
flags error: `must be string, got <class 'esphome.helper.OrderedDict'>. did you forget putting quotes around the value?.`

have tried with and without quotes
