### ISSUE TITLE
notify data with group gets error

### ISSUE THREAD

**Issue by nathan951** [esphome/issues#1351]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**
1.15-dev

**Affected component:**

**Description of problem:**
cant save/upload yaml

**Problem-relevant YAML-configuration entries:**
```
  - platform: gpio
    pin: GPIO4
    id: pool_heater
    name: Pool Heater
    inverted: True
    on_turn_on:
      - switch.turn_on: pool_pump
      - switch.turn_off: spa_heater
      - homeassistant.service:
          service: notify.nate
          data:
            title: POOL Heater is ON
            message: The pool heater was just turned on.
            data:
              group: 'pool'
```
 Adding: `group: 'pool' ` flags error

**Logs (if applicable):**

```
flags error: `must be string, got <class 'esphome.helper.OrderedDict'>. did you forget putting quotes around the value?.`

```

**Additional information and things you've tried:**

tried with and without quotes
