### ISSUE TITLE
Incorrect letter capitalization in config parser

### ISSUE THREAD

**Issue by PaulAntonDeen** [esphome/issues#1357]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

0.112.4

**ESP (ESP32/ESP8266, Board/Sonoff):**

Waveshare ESP32 driver board
**ESPHome version (latest production, beta, dev branch)**

1.15-dev rebuilt today

**Affected component:**

Waveshare display 7.50inV2

**Description of problem:**
![image](https://user-images.githubusercontent.com/25848961/87433406-9240e600-c5e9-11ea-9c60-e7b4444ce645.png)
I've entered a display model which generates an error. You'll notice that I've written the model with 7.50inV2 (uppercase V), then in the error tooltip it shows that I entered a lowercase v and suggests that uppercase V is a valid option. I've tried copy pasting the suggested value from the 'validate' error log and that also spits out the same error.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: eink75
  upper_devicename: Eink75

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${upper_devicename}
    password: !secret HA_password

captive_portal:

logger:

api:
  password: !secret HA_password

ota:
  password: !secret HA_password
  
time:
- platform: homeassistant
  id: esptime

esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

display:
  - platform: waveshare_epaper
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    model: 7.50inV2 #800x480
    #rotation: 270°
    update_interval: 59s
    lambda: |-
      it.strftime(400, 200, id(date_font), TextAlign::BOTTOM_CENTER, "%H:%M", id(esptime).now());
      it.strftime(400, 400, id(date_font), TextAlign::BOTTOM_CENTER, "%b %d %a", id(esptime).now());
      
font:
  - file: 'fonts/arial.ttf'
    id: date_font
    size: 140

```

**Logs (if applicable):**

```
INFO Reading configuration /config/esphome/eink75.yaml...
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 28 March 02:00:00 to 31 October 03:00:00
Failed config

display.waveshare_epaper: [source /config/esphome/eink75.yaml:37]
  platform: waveshare_epaper
  cs_pin: GPIO15
  dc_pin: GPIO27
  busy_pin: GPIO25
  reset_pin: GPIO26
  
  Unknown value '7.50inv2', did you mean '7.50inV2', '7.50in'?.
  model: 7.50inV2 [source /config/esphome/eink75.yaml:42]
  update_interval: 59s
  lambda: |-
    it.strftime(400, 200, id(date_font), TextAlign::BOTTOM_CENTER, "%H:%M", id(esptime).now());
    it.strftime(400, 400, id(date_font), TextAlign::BOTTOM_CENTER, "%b %d %a", id(esptime).now());

```

**Additional information and things you've tried:**
