### ISSUE TITLE
Homeassistant.event error: service not found

### ISSUE THREAD

**Issue by eaglesvr** [esphome/issues#1362]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Ubuntu 18.04 Homeassistant venv/pip . Esphome venv/pip 

**ESP (ESP32/ESP8266, Board/Sonoff):**
Sonoff RF Bridge

**ESPHome version (latest production, beta, dev branch)**
Both ESPHome version  v1.14 and 1.15-dev

**Affected component:**
Native API Component
https://esphome.io/components/api.html?highlight=event

**Description of problem:**
Esphome remote receiver fires homeassistant event for each received RF signal. Esphome call of  homeassistant.event raises error in homeassistant core "Service esphome.test_event not found"

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: sonoff_rf_bridge02
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'xxx'
  password: 'xxx'
# Enable logging
logger:

# Enable Home Assistant API

api:
  services:
     - service: test_event
       then:

ota:

web_server:
  port: 80
remote_receiver:
  pin: 4
  dump: rc_switch
  filter: 100us
  tolerance: 50%
  idle: 2ms
  on_rc_switch:
#  on_raw:
     - logger.log: "sending esphome.event"
     - homeassistant.event:
         event: esphome.test_event
         data:
           title: test_title

```

**Logs (if applicable):**

```
2020-07-18 13:08:31 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/svr/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1115, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: (ServiceNotFound(...), 'Service esphome.test_event not found')

```
**Additional information and things you've tried:**
Tested both the current esphome release as well as dev version. When HomeAssistant.event section is commented Debug log shows test message, no other errors. That means RF receiving and processing code works. It looks like that HomeAssistant core is missing code for processing Esphome events. But "Native API Component" documentation doesn't mention any additional configuration for Homeassistant/ EspHome. EspHome component configured in HomeAssistant via Integration menu.
