### ISSUE TITLE
Nan redings when exit from deepsleep

### ISSUE THREAD

**Issue by kurumuru** [esphome/issues#1363]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**ESPHome version (latest production, beta, dev branch)**

1.14.5
**Affected component:**

dht

**Description of problem:**
Always get nan readings after wakeup. 
DHT sensor gnd is attached to gpio 13, when device boots it's set to low.
Same configuration work as expected with bme280.
**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: node_out
  sleep_time: 10min
  expire_time: 20min
  update_time: 30s
  timeout: 30s
  v_max: '3722'
  v_min: '2800'

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01
  on_boot:
    priority: 799
    then:
      - switch.turn_on: sensor_power

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: False
  reboot_timeout: ${timeout}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 20
  reboot_timeout: ${timeout}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: !secret wifi_password

captive_portal:

sensor:
  - platform: adc
    pin: A0
    name: battery
    id: batt
    update_interval: ${update_time}
    accuracy_decimals: 0
    filters:
      - multiply: ${v_max}
    unit_of_measurement: mV
    expire_after: ${expire_time}
    #state_topic: ${devicename}/battery
    retain: False
    on_value:
      then:
        - wait_until:
            mqtt.connected:
        - mqtt.publish:
            topic: ${devicename}/sensor/percent/state
            payload: !lambda |-
              const float min = ${v_min};
              const float max = ${v_max};
              char val[6];
              snprintf(val, sizeof(val), "%.1f", ((x - min) * 100) / (max - min));
              return val;

  - platform: dht
    model: DHT22
    pin:
      number: 12
    temperature:
      name: temperature
    humidity:
      name: humidity
    update_interval: ${update_time}

  - platform: wifi_signal
    name: signal
    expire_after: ${expire_time}
    accuracy_decimals: 2
    update_interval: ${update_time}
    #state_topic: ${devicename}/signal
    retain: False

switch:
  - platform: gpio
    id: sensor_power
    pin:
      number: 13
      inverted: yes

deep_sleep:
  id: sleep_fail
  run_duration: 1s
  sleep_duration: ${sleep_time}

debug:

logger:
  level: debug


```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Adding 1 second delay in read_sensor_(), as it's described in dht datasheet seems to work for me.
```
diff --git a/dht.cpp b/dht_.cpp
index 625a546..86681ae 100644
--- a/dht.cpp
+++ b/dht_.cpp
@@ -80,6 +80,7 @@ bool HOT ICACHE_RAM_ATTR DHT::read_sensor_(float *temperature, float *humidity,
   uint8_t data[5] = {0, 0, 0, 0, 0};

   {
+    delayMicroseconds(1 * 1000 * 1000);
     InterruptLock lock;

     this->pin_->digital_write(false);
```
