### ISSUE TITLE
esp32 unable to connect to wpa2 enterprise network

### ISSUE THREAD

**Issue by dr-oblivium** [esphome/issues#1379]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32, Board TTGO-T-Beam

**ESPHome version (latest production, beta, dev branch)**

dev branch

**Affected component:**

https://next.esphome.io/components/wifi.html#enterprise-authentication

**Description of problem:**
I was playing around with the wpa2 enterprise feature on esphome.
esphome saw my wpa2 enterprise SSID's however did not want to connect.
A connection wasn't even tried. The wpa2 enterprise SSID's where not in selection of valid SSID's.
(I troubleshooted this adding extra logging to the code)

The problem is found to be the ssid matching code. It wants a password at the ssid level in the config file.
The dev code also misses a line to copy the EAP parameters to the esp32 specific code.

**Problem-relevant YAML-configuration entries:**
```yaml
wifi:
  networks:
  - ssid: wifi-enterprise
    priority: 5
    eap:
      username: ${devicename}
      password: <radius password>
#      certificate_authority: .ubnt-radius.pem

```

**Logs (if applicable):**

```
[18:17:45][D][WiFiGeneric.cpp:337] _eventCallback(): Event: 1 - SCAN_DONE
[18:17:45][V][wifi_esp32:357]: Event: WiFi Scan Done status=0 number=3 scan_id=128
[18:17:45][D][wifi:320]: Found networks:
[18:17:45][D][wifi:370]: - wifi-enterprise [AP_MAC1] ▂▄▆█
[18:17:45][D][wifi:370]: - wifi-enterprise [AP_MAC2] ▂▄▆█
[18:17:45][D][wifi:370]: - wifi-enterprise [AP_MAC3] ▂▄▆█
[18:17:45][W][wifi:375]: No matching network found!
```

**Additional information and things you've tried:**

PR to fix will follow.
