### ISSUE TITLE
RGBWW and Strobe Effect: Can't control warm/cold white independently

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [esphome/issues#1381]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**ESPHome version (latest production, beta, dev branch)**

v1.14.5
**Affected component:**

Strobe Effect

**Description of problem:**
I cannot control warm and cold white independently on an RGBWW light with the Strobe Effect (looking at the documentation I think the actions are also affected).

**Problem-relevant YAML-configuration entries:**

I would expect this to work, but `cold_white` and `warm_white` don't exist, only `white`. I would also like to see a color temperature option if possible, that would make pulsing different temperatures easier as a sort of "notification" to get your attention.
```yaml
light:
  - platform: rgbww
    name: RGB CCT Test
    red: R
    green: G
    blue: B
    cold_white: CW
    warm_white: WW
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    effects:
    - strobe:
        name: Warm/Cold flicker
        colors:
          - brightness: 100%
            red: 0%
            green: 0%
            blue: 0%
            cold_white: 0%
            warm_white: 100%
            duration: 50ms
          - brightness: 100%
            red: 0%
            green: 0%
            blue: 0%
            cold_white: 100%
            warm_white: 0%
            duration: 50ms

```
