### ISSUE TITLE
ESP32-CAM not compiling

### ISSUE THREAD

**Issue by madrose** [esphome/issues#139]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

latest ESPHome (1.12.0)
ESP32-CAM

**Affected component:**

Camera Component

**Description of problem:**
Trying to compile for the ESP32-CAM 
https://www.aliexpress.com/item/1pcs-ESP32-CAM-WiFi-WiFi-Module-ESP32-serial-to-WiFi-ESP32-CAM-Development-Board-5V-Bluetooth/32955484091.html

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32_camera
  platform: ESP32
  board: esp32dev

wifi:
  ssid: 'IOT'
  password: '************'
  fast_connect: true

# Example configuration entry
web_server:
  port: 80

  
  # Enable logging
logger:

ota:

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  reset_pin: GPIO15
  resolution: 640x480
  # Image settings
  name: cam
```

**Traceback (if applicable):**

```
[32mINFO Reading configuration...[0m
[32mINFO Generating C++ source...[0m
[32mINFO Core config or version changed, cleaning build files...[0m
[32mINFO Deleting config\esp32_camera\.pioenvs[0m
[32mINFO Deleting config\esp32_camera\.piolibdeps[0m
[32mINFO Compiling app...[0m
[32mINFO Running:  platformio run -d 'config\esp32_camera'[0m
Processing esp32_camera (board: esp32dev; framework: arduino; platform: espressif32@1.6.0)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
LibraryManager: Installing id=1826 @ 1.0.3
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=306 @ 1.1.1
Downloading...
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=305
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing v1.12.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
LibraryManager: Installing id=3837 @ 5.13.3
Downloading...
Unpacking  [####################################]  100%
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz 320KB RAM (4MB Flash)
DEBUG: CURRENT(esp-prog) EXTERNAL(esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 28 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <AsyncTCP> 1.0.3
|-- <ESP Async WebServer> 1.1.1
|   |-- <AsyncTCP> 1.0.3
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <FS> 1.0
|-- <Preferences> 1.0
|-- <Update> 1.0
|-- <esphome-core> 1.12.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <ESPmDNS> 1.0
|   |   |-- <WiFi> 1.0
|   |-- <AsyncTCP> 1.0.3
|   |-- <Preferences> 1.0
|   |-- <WiFi> 1.0
|   |-- <Update> 1.0
|   |-- <ESP Async WebServer> 1.1.1
|   |   |-- <AsyncTCP> 1.0.3
|   |   |-- <FS> 1.0
|   |   |-- <WiFi> 1.0
|   |   |-- <ArduinoJson-esphomelib> 5.13.3
Compiling .pioenvs\esp32_camera\src\main.cpp.o
Generating partitions .pioenvs\esp32_camera\partitions.bin
Compiling .pioenvs\esp32_camera\lib67f\AsyncTCP_ID1826\AsyncTCP.cpp.o
Compiling .pioenvs\esp32_camera\lib1a7\FS\FS.cpp.o
Compiling .pioenvs\esp32_camera\lib1a7\FS\vfs_api.cpp.o
src\main.cpp: In function 'void setup()':
src\main.cpp:23:3: error: 'ESP32Camera' was not declared in this scope
ESP32Camera *esp32camera = App.register_component(new ESP32Camera("cam"));
^
src\main.cpp:23:16: error: 'esp32camera' was not declared in this scope
ESP32Camera *esp32camera = App.register_component(new ESP32Camera("cam"));
^
src\main.cpp:23:57: error: expected type-specifier before 'ESP32Camera'
ESP32Camera *esp32camera = App.register_component(new ESP32Camera("cam"));
^
src\main.cpp:41:31: error: 'ESP32_CAMERA_SIZE_640X480' was not declared in this scope
esp32camera->set_frame_size(ESP32_CAMERA_SIZE_640X480);
^
*** [.pioenvs\esp32_camera\src\main.cpp.o] Error 1
```

**Additional information and things you've tried:**

I have tried several board type and they all gave the same error.
