### ISSUE TITLE
After transmit any command ESP32 constantly restarts

### ISSUE THREAD

**Issue by ekorsanov01** [esphome/issues#1391]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

homeassistant v0.113.2

**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32 (single core))

[https://yadi.sk/i/d2eHc5Y8M4oFxw](url)
[https://yadi.sk/i/9WWosrqvQklFQA](url)

**Affected component:**

https://esphome.io/components/remote_transmitter.html

**Description of problem:**

After transmit any command ESP constantly restarts,
but the command is successfully sent once before restarting the Board and the TV turns on!
After sending the command, the IR led remains at a voltage of 1.4 V, can this be a problem?

**Problem-relevant YAML-configuration entries:**

```yaml
substitutions:
  devicename: xiaomi_ir
  upper_devicename: Xiaomi IR Remote

esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1
  platformio_options:
    platform: espressif32@1.11.0
    platform_packages: |-4
      
          framework-arduinoespressif32 @ https://github.com/pauln/arduino-esp32.git#solo-no-mac-crc/1.0.4
  
wifi:
  ssid: "your_SSID_here"
  password: "your_Password_here"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiaomi Ir Fallback Hotspot"
    password: "your_Password_here"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "api_password_here"

ota:
  password: "ota_password_here"
  
web_server:
  port: 80
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      inverted: False
    name: ${upper_devicename} Button A
        
  - platform: gpio
    pin:
      number: GPIO33
      inverted: False
    name: ${upper_devicename} Button B
                
  - platform: gpio
    pin:
      number: GPIO34
      inverted: False
    name: ${upper_devicename} Button C
                
  - platform: gpio
    pin:
      number: GPIO35
      inverted: False
    name: ${upper_devicename} Button D

status_led:
  pin:
    number: GPIO18  #Orange LED - flashes for status events
    inverted: True
    
output:
  - platform: gpio
    pin: GPIO23     #Blue LED - Powered on always
    id: PowerLED
    
sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    
  - platform: uptime
    name: ${upper_devicename} Uptime

switch:
  - platform: restart
    name: ${upper_devicename} Restart

  - platform: template
    name: ${upper_devicename} LG TV Power On
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x02FD48B7              
          nbits: 32
          transmitter_id: internal
          
mqtt:
  broker: "your_broker_ip_address"
  username: "your_mqtt_username"
  password: "your_mqtt_password"
  discovery: True
  
remote_receiver:
  pin:
    number: GPIO27
    inverted: True
  dump: all

remote_transmitter:
  pin:
    number: GPIO26
    inverted: False    #Needs idle state to be set to high. Not currently feasible. Will cause board heating.
  carrier_duty_percent: 50%
  id: internal

```

**Logs (if applicable):**

```
[C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[C][wifi_signal.sensor:009]:   Icon: 'mdi:wifi'
[D][api.connection:583]: Client 'Home Assistant 0.113.2 (192.168.1.46)' connected successfully!
[D][remote.nec:068]: Received NEC: address=0x20DF, command=0x40BF
[D][remote.raw:041]: Received Raw: 8917, -2368, 424
[D][remote.nec:068]: Received NEC: address=0x20DF, command=0x40BF
[D][remote.nec:068]: Received NEC: address=0x20DF, command=0x40BF
[D][remote.raw:041]: Received Raw: 8969, -2314, 476
[D][sensor:092]: 'Xiaomi IR Remote WiFi Signal': Sending state -62.00000 dB with 0 decimals of accuracy
[D][sensor:092]: 'Xiaomi IR Remote Uptime': Sending state 41.95800 s with 0 decimals of accuracy
[D][switch:029]: 'Xiaomi IR Remote AIR Power On' Toggling ON.
[D][remote.lg:053]: Received LG: data=0x20DF10EF, nbits=32
[D][remote.raw:041]: Received Raw: 196, -647, 158, -289, 648, -911, 171, -1336, 246, -397, 918
[D][remote.raw:041]: Received Raw: 676, -624, 335, -320, 150, -5593, 325, -544, 201, -551, 527
[D][remote.raw:041]: Received Raw: 85, -6298, 104, -7221, 618, -670, 296, -361, 223, -1174, 276, -1069, 324, -3407, 238
[D][remote.raw:041]: Received Raw: 878, -1222, 153, -1232, 93
[D][remote.raw:041]: Received Raw: 836, -2630, 225, -1258, 166
[D][remote.raw:041]: Received Raw: 525, -1763, 93, -1384, 77, -1362, 109
[D][remote.raw:041]: Received Raw: 655, -855, 292, -369, 145, -1361, 177, -561, 444, -796, 129, -7948, 122
[D][remote.raw:041]: Received Raw: 279, -892, 297, -1743, 568, -2819, 66, -404, 210
[D][remote.raw:041]: Received Raw: 602, -1237, 134, -1528, 218
[D][remote.raw:041]: Received Raw: 251, -363, 161
[D][remote.raw:041]: Received Raw: 252, -1302, 89, -1580, 401, -905, 216, -395, 188
[D][remote.raw:041]: Received Raw: 94, -1073, 219, -404, 136, -2823, 119, -6053, 129, -8408, 162, -2652, 222
[D][remote.raw:041]: Received Raw: 95
[D][remote.raw:041]: Received Raw: 493, -1333, 160, -1917, 73, -7252, 83, -1972, 137, -1385, 129
[D][remote.raw:041]: Received Raw: 222, -978, 247, -373, 159
[D][remote.raw:041]: Received Raw: 247, -367, 126
[D][remote.raw:041]: Received Raw: 85, -1552, 154
[D][remote.raw:041]: Received Raw: 195, -3271, 130
[D][remote.raw:041]: Received Raw: 155
[D][remote.raw:041]: Received Raw: 128, -1072, 177, -436, 131
[D][remote.raw:041]: Received Raw: 213, -963, 83, -572, 94, -2002, 66
[D][remote.raw:041]: Received Raw: 156
[D][remote.raw:041]: Received Raw: 86
[D][remote.raw:041]: Received Raw: 93
[D][remote.raw:041]: Received Raw: 85
[D][remote.raw:041]: Received Raw: 82
[D][remote.raw:041]: Received Raw: 128
[D][remote.raw:041]: Received Raw: 85
[D][remote.raw:041]: Received Raw: 112
[D][remote.raw:041]: Received Raw: 83
[D][remote.raw:041]: Received Raw: 124
[D][remote.raw:041]: Received Raw: 78
[D][remote.raw:041]: Received Raw: 121
[D][remote.raw:041]: Received Raw: 73
[D][remote.raw:041]: Received Raw: 84
[D][remote.raw:041]: Received Raw: 82
[D][remote.raw:041]: Received Raw: 83
[D][remote.raw:041]: Received Raw: 67
[D][remote.raw:041]: Received Raw: 114
[D][remote.raw:041]: Received Raw: 90, -1117, 150
[D][remote.raw:041]: Received Raw: 90

Brownout detector was triggered

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:156]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:364]: There have been 1 suspected unsuccessful boot attempts.
[I][app:028]: Running through setup()...
[D][binary_sensor:034]: 'Xiaomi IR Remote Button A': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button B': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button C': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button D': Sending initial state OFF
[C][remote_receiver.esp32:012]: Setting up Remote Receiver...
[C][wifi:033]: Setting up WiFi...

Brownout detector was triggered

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:156]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:364]: There have been 2 suspected unsuccessful boot attempts.
[I][app:028]: Running through setup()...
[D][binary_sensor:034]: 'Xiaomi IR Remote Button A': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button B': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button C': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button D': Sending initial state OFF
[C][remote_receiver.esp32:012]: Setting up Remote Receiver...
[C][wifi:033]: Setting up WiFi...

Brownout detector was triggered

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:156]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:364]: There have been 3 suspected unsuccessful boot attempts.
[I][app:028]: Running through setup()...
[D][binary_sensor:034]: 'Xiaomi IR Remote Button A': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button B': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button C': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button D': Sending initial state OFF
[C][remote_receiver.esp32:012]: Setting up Remote Receiver...
[C][wifi:033]: Setting up WiFi...

Brownout detector was triggered

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:156]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:364]: There have been 4 suspected unsuccessful boot attempts.
[I][app:028]: Running through setup()...
[D][binary_sensor:034]: 'Xiaomi IR Remote Button A': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button B': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button C': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button D': Sending initial state OFF
[C][remote_receiver.esp32:012]: Setting up Remote Receiver...
[C][wifi:033]: Setting up WiFi...

.....

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:156]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:364]: There have been 10 suspected unsuccessful boot attempts.
[E][ota:369]: Boot loop detected. Proceeding to safe mode.
[I][app:028]: Running through setup()...
[C][wifi:033]: Setting up WiFi...
```

**Additional information and things you've tried:**
