### ISSUE TITLE
After transmit any command ESP32 constantly restarts

### ISSUE THREAD

**Issue by ekorsanov01** [esphome/issues#1392]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

homeassistant v0.113.2
docker_version v18.09.7
hassio - true
host_os | Ubuntu 18.04.3 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.19.63-sunxi64
python_version | 3.8.3
supervisor | 229
virtualenv | false

**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32 (single core))

[https://yadi.sk/i/d2eHc5Y8M4oFxw](url)
[https://yadi.sk/i/9WWosrqvQklFQA](url)

**ESPHome version (latest production, beta, dev branch)**

ESPHome version like v1.14.5

**Affected component:**

https://esphome.io/components/remote_transmitter.html

**Description of problem:**

After transmit any command ESP constantly restarts,
but the command is successfully sent once before restarting the Board and the TV turns on!
After sending the command, the IR led remains at a voltage of 1.4 V, can this be a problem?

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: xiaomi_ir
  upper_devicename: Xiaomi IR Remote

esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1
  platformio_options:
    platform: espressif32@1.11.0
    platform_packages: |-4
      
          framework-arduinoespressif32 @ https://github.com/pauln/arduino-esp32.git#solo-no-mac-crc/1.0.4
  
wifi:
  power_save_mode: light
  ssid: "---"
  password: "--"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "Xiaomi Ir Fallback Hotspot"
  #   password: "12345678"

#captive_portal:

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  password: "1"

ota:
  password: "1"
  
web_server:
  port: 80
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      inverted: False
    name: ${upper_devicename} Button A
        
  - platform: gpio
    pin:
      number: GPIO33
      inverted: False
    name: ${upper_devicename} Button B
                
  - platform: gpio
    pin:
      number: GPIO34
      inverted: False
    name: ${upper_devicename} Button C
                
  - platform: gpio
    pin:
      number: GPIO35
      inverted: False
    name: ${upper_devicename} Button D

status_led:
  pin:
    number: GPIO18  #Orange LED - flashes for status events
    inverted: True
    
output:
  - platform: gpio
    pin: GPIO23     #Blue LED - Powered on always
    id: PowerLED
    
sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    
  - platform: uptime
    name: ${upper_devicename} Uptime

switch:
   - platform: restart
     name: ${upper_devicename} Restart

   - platform: template
     name: ${upper_devicename} AIR Power On
     turn_on_action:
       - remote_transmitter.transmit_nec:
           address: 0x20DF
           command: 0x10EF
           transmitter_id: internal
          
# mqtt:
#   broker: "your_broker_ip_address"
#   username: "your_mqtt_username"
#   password: "your_mqtt_password"
#   discovery: True
  
remote_receiver:
   pin:
     number: GPIO27
     inverted: True
   dump: all

remote_transmitter:
   pin:
     number: GPIO26
     inverted: False    #Needs idle state to be set to high. Not currently feasible. Will cause board heating.
   carrier_duty_percent: 100%
   id: internal

climate:
  - platform: tcl112
    name: dantex_ac
    transmitter_id: internal
    id: dantex_ac
    visual:
      min_temperature: 16 °C
      max_temperature: 31 °C
      temperature_step: 1 °C

```

**Logs (if applicable):**

```
[VV][preferences:051]: SAVE 0: 0=0x00000000 1=0x0DEFE4E3 (Type=233825507, CRC=0x0DEFE4E3)
[VV][scheduler:131]: Running interval '' with interval=10000 last_execution=111724 (now=121724)
[VV][scheduler:025]: set_timeout(name='', timeout=0)
[VV][scheduler:131]: Running timeout '' with interval=0 last_execution=126811 (now=126819)
[D][switch:029]: 'Xiaomi IR Remote AIR Power On' Toggling ON.
[VV][remote_base:040]: Sending times=1 wait=0ms: 9000, -4500, 560, -560, 560, -560, 560, -1690, 560, -560, 560, -560, 560, -560, 560, -560, 560, -560, 560, -1690, 560, -1690, 560, -560, 560, -1690, 560, -1690, 560, -1690, 560, -1690, 560, -1690, 560, -560, 560, -560, 560, 
[VV][remote_base:053]:   -560, 560, -1690, 560, -560, 560, -560, 560, -560, 560, -560, 560, -1690, 560, -1690, 560, -1690, 560, -560, 560, -1690, 560, -1690, 560, -1690, 560, -1690, 560
[VV][remote_receiver.esp32:089]: START:
[VV][remote_receiver.esp32:094]: 0 A: OFF 199us (199 ticks)
[VV][remote_receiver.esp32:097]: 0 B: ON 735us (735 ticks)
[VV][remote_receiver.esp32:094]: 1 A: OFF 141us (141 ticks)
[VV][remote_receiver.esp32:097]: 1 B: ON 1552us (1552 ticks)
[VV][remote_receiver.esp32:094]: 2 A: OFF 248us (248 ticks)
[VV][remote_receiver.esp32:097]: 2 B: ON 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 3 A: OFF 4us (4 ticks)
[VV][remote_receiver.esp32:099]: 3 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 4 A: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:099]: 4 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 5 A: OFF 74us (74 ticks)
[VV][remote_receiver.esp32:097]: 5 B: ON 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 6 A: OFF 4us (4 ticks)
[VV][remote_receiver.esp32:099]: 6 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 7 A: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:099]: 7 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 8 A: OFF 83us (83 ticks)
[VV][remote_receiver.esp32:097]: 8 B: ON 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 9 A: OFF 4us (4 ticks)
[VV][remote_receiver.esp32:099]: 9 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 10 A: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:099]: 10 B: OFF 0us (0 ticks)
E (127396) rmt: RMT[0] ERR
E (127396) rmt: status: 0x13000040
[VV][remote_receiver.esp32:094]: 11 A: OFF 87us (87 ticks)
[VV][remote_receiver.esp32:097]: 11 B: ON 0us (0 ticks)
[VV][remote_receiver.esp32:102]: 

[D][remote.raw:041]: Received Raw: 199, -735, 141, -1552
[V][app:076]: A component took a long time in a loop() cycle (0.31 s).
[V][app:077]: Components should block for at most 20-30ms in loop().
[VV][remote_receiver.esp32:089]: START:
[VV][remote_receiver.esp32:094]: 0 A: OFF 74us (74 ticks)
[VV][remote_receiver.esp32:097]: 0 B: ON 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 1 A: OFF 4us (4 ticks)
[VV][remote_receiver.esp32:099]: 1 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 2 A: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:099]: 2 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 3 A: OFF 83us (83 ticks)
[VV][remote_receiver.esp32:097]: 3 B: ON 0us (0 ticks)
[VV][remote_receiver.esp32:102]: 

[D][remote.raw:041]: Received Raw: 
[VV][remote_receiver.esp32:089]: START:
[VV][remote_receiver.esp32:094]: 0 A: OFF 83us (83 ticks)
[VV][remote_receiver.esp32:097]: 0 B: ON 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 1 A: OFF 4us (4 ticks)
[VV][remote_receiver.esp32:099]: 1 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 2 A: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:099]: 2 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 3 A: OFF 87us (87 ticks)
[VV][remote_receiver.esp32:097]: 3 B: ON 0us (0 ticks)
[VV][remote_receiver.esp32:102]: 

[D][remote.raw:041]: Received Raw: 
[VV][remote_receiver.esp32:089]: START:
[VV][remote_receiver.esp32:094]: 0 A: OFF 87us (87 ticks)
[VV][remote_receiver.esp32:097]: 0 B: ON 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 1 A: OFF 256us (256 ticks)
[VV][remote_receiver.esp32:099]: 1 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 2 A: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:099]: 2 B: OFF 0us (0 ticks)
[VV][remote_receiver.esp32:094]: 3 A: OFF 95us (95 ticks)
[VV][remote_receiver.esp32:097]: 3 B: ON 4907us (4907 ticks)
[VV][remote_receiver.esp32:102]: 

[D][remote.raw:041]: Received Raw: 438
[VV][remote_receiver.esp32:089]: START:
[VV][remote_receiver.esp32:094]: 0 A: OFF 95us (95 ticks)
[VV][remote_receiver.esp32:097]: 0 B: ON 4907us (4907 ticks)
[VV][remote_receiver.esp32:094]: 1 A: OFF 770us (770 ticks)
[VV][remote_receiver.esp32:097]: 1 B: ON 2226us (2226 ticks)
[VV][remote_receiver.esp32:094]: 2 A: OFF 331us (331 ticks)
[VV][remote_receiver.esp32:097]: 2 B: ON 4496us (4496 ticks)
[VV][remote_receiver.esp32:094]: 3 A: OFF 323us (323 ticks)
[VV][remote_receiver.esp32:097]: 3 B: ON 492us (492 ticks)
[VV][remote_receiver.esp32:094]: 4 A: OFF 615us (615 ticks)
[VV][remote_receiver.esp32:097]: 4 B: ON 4209us (4209 ticks)
[VV][remote_receiver.esp32:094]: 5 A: OFF 164us (164 ticks)
[VV][remote_receiver.esp32:097]: 5 B: ON 1692us (1692 ticks)
[VV][remote_receiver.esp32:094]: 6 A: OFF 91us (91 ticks)
[VV][remote_receiver.esp32:097]: 6 B: ON 529us (529 ticks)
[VV][remote_receiver.esp32:094]: 7 A: OFF 428us (428 ticks)
[VV][remote_receiver.esp32:097]: 7 B: ON 336us (336 ticks)
[VV][remote_receiver.esp32:094]: 8 A: OFF 519us (519 ticks)
[VV][remote_receiver.esp32:097]: 8 B: ON 684us (684 ticks)
[VV][remote_receiver.esp32:094]: 9 A: OFF 92us (92 ticks)
[VV][remote_receiver.esp32:097]: 9 B: ON 518us (518 ticks)
[VV][remote_receiver.esp32:094]: 10 A: OFF 196us (196 ticks)
[VV][remote_receiver.esp32:097]: 10 B: ON 1052us (1052 ticks)
[VV][remote_receiver.esp32:094]: 11 A: OFF 1208us (1208 ticks)
[VV][remote_receiver.esp32:097]: 11 B: ON 436us (436 ticks)
[VV][remote_receiver.esp32:094]: 12 A: OFF 456us (456 ticks)
[VV][remote_receiver.esp32:097]: 12 B: ON 595us (595 ticks)
[VV][remote_receiver.esp32:094]: 13 A: OFF 276us (276 ticks)
[VV][remote_receiver.esp32:097]: 13 B: ON 288us (288 ticks)
[VV][remote_receiver.esp32:094]: 14 A: OFF 125us (125 ticks)
[VV][remote_receiver.esp32:097]: 14 B: ON 400us (400 ticks)
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400eb0da  PS      : 0x00060530  A0      : 0x800eb172  A1      : 0x3ffb1d10  
A2      : 0x3ffd69fc  A3      : 0x00000001  A4      : 0x00000068  A5      : 0x3ffd6b14  
A6      : 0x6d305b1b  A7      : 0x0a0d0a0d  A8      : 0x800eb0e8  A9      : 0x3ffb1cf0  
A10     : 0x00000068  A11     : 0x00000068  A12     : 0x00000068  A13     : 0x00000068  
A14     : 0x00000000  A15     : 0x7061000a  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000001  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

Backtrace: 0x400eb0da:0x3ffb1d10 0x400eb16f:0x3ffb1d30 0x400eb18b:0x3ffb1d50 0x400eb1e1:0x3ffb1d70 0x400de8f6:0x3ffb1da0 0x400da985:0x3ffb1dc0 0x400daad5:0x3ffb1df0 0x400e51d5:0x3ffb1e10 0x400e5202:0x3ffb1e40 0x400dcd97:0x3ffb1ea0 0x400dcf25:0x3ffb1ef0 0x4016b25d:0x3ffb1f20 0x4016b329:0x3ffb1f40 0x400e37d5:0x3ffb1f60 0x400e5ff6:0x3ffb1f90 0x400f2995:0x3ffb1fb0 0x4008955d:0x3ffb1fd0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:156]: Log initialized
[C][status_led:014]: Setting up Status LED...
[VV][preferences:038]: LOAD 0: valid=YES, 0=0x00000000 1=0x0DEFE4E3 (Type=233825507, CRC=0x0DEFE4E3)
[C][ota:364]: There have been 0 suspected unsuccessful boot attempts.
[VV][preferences:051]: SAVE 0: 0=0x00000001 1=0x42F4583F (Type=233825507, CRC=0x42F4583F)
[I][app:028]: Running through setup()...
[V][app:029]: Sorting components by setup priority...
[D][binary_sensor:034]: 'Xiaomi IR Remote Button A': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button B': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button C': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button D': Sending initial state OFF
[VV][scheduler:056]: set_interval(name='update', interval=60000, offset=6822)
[VV][preferences:038]: LOAD 1: valid=YES, 0=0x00000000 1=0x000041C0 (Type=2722369216, CRC=0xFD85AF20)
[D][climate:172]: 'dantex_ac' - Sending state:
[D][climate:175]:   Mode: OFF
[D][climate:186]:   Target Temperature: 24.00°C
[VV][preferences:051]: SAVE 1: 0=0x00000000 1=0x000041C0 (Type=2722369216, CRC=0xFD85AF20)
[C][remote_receiver.esp32:012]: Setting up Remote Receiver...
[C][wifi:033]: Setting up WiFi...
[V][wifi_esp32:033]: Enabling STA.
[VV][esp-idf:000]: I (445) wifi: wifi driver task: 3ffafadc, prio:23, stack:3584, core=0
[VV][esp-idf:000]: I (456) wifi: wifi firmware version: 7997e4b
[VV][esp-idf:000]: I (456) wifi: config NVS flash: enabled
[VV][esp-idf:000]: I (462) wifi: config nano formating: disabled
[VV][esp-idf:000]: I (469) wifi: Init dynamic tx buffer num: 32
[VV][esp-idf:000]: I (476) wifi: Init data frame dynamic rx buffer num: 32
[VV][esp-idf:000]: I (483) wifi: Init management frame dynamic rx buffer num: 32
[VV][esp-idf:000]: I (491) wifi: Init management short buffer num: 32
[VV][esp-idf:000]: I (499) wifi: Init static rx buffer size: 1600
[VV][esp-idf:000]: I (505) wifi: Init static rx buffer num: 16
[VV][esp-idf:000]: I (512) wifi: Init dynamic rx buffer num: 32

Brownout detector was triggered

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:156]: Log initialized
[C][status_led:014]: Setting up Status LED...
[VV][preferences:038]: LOAD 0: valid=YES, 0=0x00000001 1=0x42F4583F (Type=233825507, CRC=0x42F4583F)
[C][ota:364]: There have been 1 suspected unsuccessful boot attempts.
[VV][preferences:051]: SAVE 0: 0=0x00000002 1=0x13D89D5A (Type=233825507, CRC=0x13D89D5A)
[I][app:028]: Running through setup()...
[V][app:029]: Sorting components by setup priority...
[D][binary_sensor:034]: 'Xiaomi IR Remote Button A': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button B': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button C': Sending initial state OFF
[D][binary_sensor:034]: 'Xiaomi IR Remote Button D': Sending initial state OFF
[VV][scheduler:056]: set_interval(name='update', interval=60000, offset=21671)
[VV][preferences:038]: LOAD 1: valid=YES, 0=0x00000000 1=0x000041C0 (Type=2722369216, CRC=0xFD85AF20)
[D][climate:172]: 'dantex_ac' - Sending state:
[D][climate:175]:   Mode: OFF
[D][climate:186]:   Target Temperature: 24.00°C
[VV][preferences:051]: SAVE 1: 0=0x00000000 1=0x000041C0 (Type=2722369216, CRC=0xFD85AF20)
[C][remote_receiver.esp32:012]: Setting up Remote Receiver...
[C][wifi:033]: Setting up WiFi...
[V][wifi_esp32:033]: Enabling STA.
[VV][esp-idf:000]: I (445) wifi: wifi driver task: 3ffafadc, prio:23, stack:3584, core=0
[VV][esp-idf:000]: I (456) wifi: wifi firmware version: 7997e4b
[VV][esp-idf:000]: I (456) wifi: config NVS flash: enabled
[VV][esp-idf:000]: I (462) wifi: config nano formating: disabled
[VV][esp-idf:000]: I (469) wifi: Init dynamic tx buffer num: 32
[VV][esp-idf:000]: I (476) wifi: Init data frame dynamic rx buffer num: 32
[VV][esp-idf:000]: I (483) wifi: Init management frame dynamic rx buffer num: 32
[VV][esp-idf:000]: I (491) wifi: Init management short buffer num: 32
[VV][esp-idf:000]: I (499) wifi: Init static rx buffer size: 1600
[VV][esp-idf:000]: I (505) wifi: Init static rx buffer num: 16
[VV][esp-idf:000]: I (512) wifi: Init dynamic rx buffer num: 32

Brownout detector was triggered
....

```

**Additional information and things you've tried:**
