### ISSUE TITLE
Can' update color on nextion text

### ISSUE THREAD

**Issue by denisvic** [esphome/issues#1394]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**ESPHome version (latest production, beta, dev branch)**

latest production
**Affected component:**

Nextion Display

**Description of problem:**
I'm trying to change component text color using "it.set_component_text" but nothing happens. Some errors in logs.

**Problem-relevant YAML-configuration entries:**
```yaml
display:
  - platform: nextion
    lambda: |-
      it.set_component_text("statut", "test");
      it.set_component_font_color("statut", "17601");
```

**Logs (if applicable):**

```
[00:45:32][W][nextion:182]: Nextion reported failed to assign variable!
[00:45:32][W][nextion:036]: Waiting for ACK timed out!
[00:45:32][W][nextion:083]: Sending command 'statut.pco="17601"' failed because no ACK was received

```

**Additional information and things you've tried:**
Same problem described here : https://github.com/esphome/issues/issues/915
