### ISSUE TITLE
Sonoff Basic won't log to wifi when even number of binary_sensor defined

### ISSUE THREAD

**Issue by ppmt** [esphome/issues#1398]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio 1.113.3 

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff Basic TH_V1.1

**ESPHome version (latest production, beta, dev branch)**

v1.14.4 (from Home Assistant Add-on and the esptool in Linux)
**Affected component:**

binary_sensor ( https://esphome.io/components/binary_sensor/index.html )

**Description of problem:**
When I flash the sonoff basic with a even number of  binary_sensor then the sonoff can not log on the wifi network
With an odd number then it can connect with no problem.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: nextion
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: "PLUSNET-RG58"
  password: "not my password"
  output_power: 17.5db
web_server:
  port: 80
logger:  # Enable logging
  baud_rate: 0     # Disable UART logging
#  level: VERBOSE
api: # Enable Home Assistant API
  password: "secret"
ota:
  password: "secret"
status_led:
  pin:
    number: GPIO13
    inverted: yes
# Uart port definition - This works OK, but also HW UART0 works if Logs are disabled or changed to UART1
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600 

globals:
  - id: nextion_page_id
    type: int
    restore_value: no
    initial_value: '0'

binary_sensor:
  - platform: nextion
    page_id: 0
    component_id: 12
    name: "page forward"
    internal: true
    on_state:
      then:
        - lambda: |-
            id(nextion_page_id)=1;
            id(display_nextion).goto_page("page1");
        - component.update: display_nextion
  - platform: nextion
    page_id: 1
    component_id: 1
    name: "page back"
    internal: true
    on_state:
      then:
        - lambda: |-
            id(nextion_page_id)=0;
            id(display_nextion).goto_page("page0");
        - component.update: display_nextion
  - platform: nextion
    page_id: 0
    component_id: 3
    id: minus_set_temp 
    name: "Nextion Target Down"
    #internal: true
    on_press:
      then:
        - lambda: |-
            id(nextion_page_id)=0;
        - component.update: display_nextion
  - platform: nextion
    page_id: 0
    component_id: 5
    id: plus_set_temp 
    name: "Nextion Target up"
    #internal: true
    on_press:
      then:
        - lambda: |-
            id(nextion_page_id)=0;
        - component.update: display_nextion
  - platform: nextion
    page_id: 0
    component_id: 7
    name: "dummy to have odd number of binary_sensor"
    internal: true
    on_state:
      then:
        - lambda: |-
            id(nextion_page_id)=0;
            id(display_nextion).goto_page("page0");
        - component.update: display_nextion

display:
  - platform: nextion
    id: display_nextion
    update_interval: 30s
    lambda: |-
      it.set_wait_for_ack(false);
      if (id(nextion_page_id) == 0) {
          it.set_component_text_printf("TempT","%.1f",id(Temp_Down).state);  //Thermostat Temp
          it.set_component_text_printf("Humidity","%.1f",id(Humidity_Down).state);  //Thermostat Humidity
          it.set_component_text_printf("TargetT","%.1f",id(Target_Temp).state);  //Temperature Target
      } else if (id(nextion_page_id) == 1) {
          it.set_component_text_printf("UpstairsT","%.1f",id(Landing_Temp).state);  //MasterBedroom Temp
          it.set_component_text_printf("MasterT","%.1f",id(Master_Temp).state);  //MasterBedroom Temp
          it.set_component_text_printf("LivingT","%.1f",id(Living_Temp).state);  //Living Room Temp
          it.set_component_text_printf("KitchenT","%.1f",id(Kitchen_Temp).state);  //Kitchen Room Temp
          it.set_component_text_printf("TheoT","%.1f",id(TheoBedRoom_Temp).state);  //Kitchen Room Temp
      }

#Read sensor data from Home Assistant   
sensor:
#First page for the Thermostat
  - platform: homeassistant
    id: Temp_Down
    entity_id: sensor.thermostat_am2301_temperature
  - platform: homeassistant
    id: Humidity_Down
    entity_id: sensor.thermostat_am2301_humidity
  - platform: homeassistant
    id: Target_Temp
    entity_id: sensor.climate_target
#Second page for the Temperature Sensors
  - platform: homeassistant
    id: Master_Temp
    entity_id: sensor.sensor1_temp
  - platform: homeassistant
    id: Living_Temp
    entity_id: sensor.sensor2_temp
  - platform: homeassistant
    id: Kitchen_Temp
    entity_id: sensor.sensor3_temp
  - platform: homeassistant
    id: Landing_Temp
    entity_id: sensor.misol_intempc
  - platform: homeassistant
    id: TheoBedRoom_Temp
    entity_id: sensor.theo_speaker_am2301_temperature


```

**Logs (if applicable):**

```
INFO Starting log output from /dev/ttyUSB0 with baud rate 115200
[19:17:57][D][wifi:319]: Found networks:
[19:17:57][D][wifi:321]:   No network found!
[19:18:02][D][wifi:304]: Starting scan...
[19:18:08][D][wifi:319]: Found networks:
[19:18:08][D][wifi:321]:   No network found!
[19:18:13][D][wifi:304]: Starting scan...
[19:18:19][D][wifi:319]: Found networks:
[19:18:19][D][wifi:321]:   No network found!
[19:18:24][D][wifi:304]: Starting scan...
[19:18:30][D][wifi:319]: Found networks:
[19:18:30][D][wifi:321]:   No network found!


```

I have tried with 1 binary_sensor and it works, 2 it doesn't, 3 it does, 4 it doesn't. you see the pattern
