### ISSUE TITLE
D1 mini Error 113 WARNING Couldn't connect to API

### ISSUE THREAD

**Issue by K-Glasius** [esphome/issues#14]
Hi 
i have a D1 mini whit this yamel 
```
esphomeyaml:
  name: pool
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: '*****'
  password: '******'

  manual_ip:
    static_ip: 192.168.1.75
    gateway: 192.168.1.1
    subnet: 255.255.255.0
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: '******'

ota:
  password: '******'
  ```

i am getting erros on the API 

LOG
```
INFO Reading configuration...
INFO Starting log output from 192.168.1.75 using esphomelib API
INFO Connecting to 192.168.1.75:6053 (192.168.1.75)
WARNING Couldn't connect to API (Error connecting to 192.168.1.75: [Errno 113] No route to host). Trying to reconnect in 1 seconds
INFO Connecting to 192.168.1.75:6053 (192.168.1.75)
WARNING Couldn't connect to API (Error connecting to 192.168.1.75: [Errno 113] No route to host). Trying to reconnect in 2 seconds
INFO Connecting to 192.168.1.75:6053 (192.168.1.75)
WARNING Couldn't connect to API (Error connecting to 192.168.1.75: [Errno 113] No route to host). Trying to reconnect in 4 seconds
INFO Connecting to 192.168.1.75:6053 (192.168.1.75)
WARNING Couldn't connect to API (Error connecting to 192.168.1.75: [Errno 113] No route to host). Trying to reconnect in 8 seconds
INFO Connecting to 192.168.1.75:6053 (192.168.1.75)
WARNING Couldn't connect to API (Error connecting to 192.168.1.75: [Errno 113] No route to host). Trying to reconnect in 16 seconds```

plz help
