### ISSUE TITLE
Issue with -delay or cover

### ISSUE THREAD

**Issue by ds495** [esphome/issues#1400]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

esp8266
**ESP (ESP32/ESP8266, Board/Sonoff):**
esp8266 d1 mini

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

https://esphome.io/components/cover/template.html

**Description of problem:**
Motors run continuously although I am using a delay command in cover: "template"

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
name: coupola
platform: ESP8266
board: d1_mini
wifi:
ssid: '2.4'
password: +++
logger: null
api: null
ota: null
web_server:
port: 80
output:

    platform: gpio
    id: win1_out
    pin: D1
    platform: gpio
    id: win1_in
    pin: D2
    platform: gpio
    id: win2_out
    pin: D5
    platform: gpio
    id: win2_in
    pin: D6
    switch:
    platform: output
    name: win1out
    output: win1_out
    id: win1out
    platform: output
    name: win1in
    output: win1_in
    id: win1in
    platform: output
    name: win2out
    output: win2_out
    id: win2out
    platform: output
    name: win2in
    output: win2_in
    id: win2in
    cover:
    platform: template
    name: Window 1
    id: w1
    optimistic: true
    open_action:
        switch.turn_off: win1in
        switch.turn_on: win1out
        delay: 10s
        switch.turn_off: win1out
        close_action:
        switch.turn_off: win1out
        switch.turn_on: win1in
        delay: 15s
        switch.turn_off: win1in
        stop_action:
        switch.turn_off: win1in
        switch.turn_off: win1out
    platform: template
    name: Window 2
    id: w2
    optimistic: true
    open_action:
        switch.turn_off: win2in
        switch.turn_on: win2out
        delay: 15s
        switch.turn_off: win2out
        close_action:
        switch.turn_off: win2out
        switch.turn_on: win2in
        delay: 30s
        switch.turn_off: win2in
        stop_action:
        switch.turn_off: win2in
        switch.turn_off: win2out
        binary_sensor:
    platform: gpio
    name: reed switch 1
    id: reed1
    pin: D3
    filters:
    invert: null
    on_press:
    then:
    - switch.turn_off: win1in
    - switch.turn_off: win1out
    platform: gpio
    pin: D7
    name: reed switch 2
    id: reed2
    filters:
    invert: null
    on_press:
    then:
    - switch.turn_off: win2in
    - switch.turn_off: win2out
    platform: gpio
    pin: D4
    name: Window 1 Control Button
    id: button1
    filters:
    invert: null
    on_press:
    then:
    - lambda: |
    if (id(w1).state == cover::COVER_OPEN) {
    if (id(win1out).state){
    // window is opening
    id(w1).stop();
    } else {
    // window is open and not moving
    id(w1).close();
    }
    } else {
    if (id(win1in).state){
    // window is closing
    id(w1).stop();
    } else {
    // win is closed and not moving
    id(w1).open();
    }
    }
    platform: gpio
    pin: D8
    name: Window 2 Control Button
    id: button2
    filters:
    invert: null
    on_press:
    then:
    - lambda: |
    if (id(w2).state == cover::COVER_OPEN) {
    if (id(win2out).state){
    // window is opening
    id(w2).stop();
    } else {
    // window is open and not moving
    id(w2).close();
    }
    } else {
    if (id(win2in).state){
    // window is closing
    id(w2).stop();
    } else {
    // win is closed and not moving
    id(w2).open();
    }
    }
```

**Logs (if applicable):**

```sorry, don't know how to do this
PASTE DEBUG LOG HERE

```sorry, don't know how to do this

**Additional information and things you've tried:**
HI,
I am newbe to this system but have put together the hardware to open and close four windows based on what Dr. Zzzs has done. Using D1 mini board to control L298 H Bridge motor controllers. Each D1 then can control 2 windows.

Here is the yaml file. I use ESPhome from a command prompt on a Windows based computer. The code compiles and loads (only over USB not over-the-air)

    I can open a browser window by using a 192.168.3.15 URL but not if I try something like coupola.local:80. I can not get Home Assistant to recognize the device automatically and it doesn't like the URL I put in.

What does come up as a control screen is this. Not what I expected as I would expect "close", "stop" and "open" buttons. (As I side note I compiled, loaded and ran the GARAGE DOOR OPENER example in esphome.io and did not get the control display shown but instead got something similiar to what I get with my code) This is a screen shot of the control screen

![Untitled](https://user-images.githubusercontent.com/69324024/89583501-73102f80-d808-11ea-9529-4bcf43b0fbb5.png)


If I click on win1out, the window goes out but runs continuously as the "delay" command doesn't kick in. I can start and stop motor but hitting the toggle button. Same for win1in. The two reed switches work as I expected from the coding.

Seems like something basic that I am missing?????????

Thanks for your help.



<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
