### ISSUE TITLE
AS3935_i2C -  Read failed!

### ISSUE THREAD

**Issue by zibous** [esphome/issues#1411]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip, OSX High Sierra

**ESP (ESP32/ESP8266, Board/Sonoff):**
nodemcuv2 and Wemos D1 Mini

**ESPHome version (latest production, beta, dev branch)**
ESPHome v1.15.0b3

**Affected component:**
as3935

**Description of problem:**
Has anyone managed to get one of these working? I have tried and tried but not a squeak of output.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: blitzsensor
  platform: ESP8266
  board: nodemcuv2
  platformio_options:
    upload_speed: 115200
  
wifi:
  ssid:  !secret ssid_name
  password: !secret ssid_pswd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Messstation Hotspot"
    password: "tMtkdRRAxEnO"

captive_portal:

# Enable logging
# see: https://esphome.io/components/logger.html?highlight=logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
  password: !secret ha_pswd

ota:
  password: !secret ota_pswd

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: tele/blitzsensor/LWT
    payload: online
  will_message:
    topic: tele/blitzsensor/LWT
    payload: offline

# connection ams as3935 Franklin Lightning Sensor
i2c:
  scl: D1
  sda: D2
  scan: True
  
as3935_i2c:
  irq_pin: GPIO13
  indoor: False
  spike_rejection: 5

sensor:
  - platform: as3935
    lightning_energy:
      name: "ESP Blitz Energie"
    distance:
      name: "ESP Sturm entfernung"
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

# see https://esphome.io/components/sensor/as3935.html?highlight=as3935
binary_sensor:
  - platform: as3935
    name: "ESP Sturmwarnung"


```

**Logs (if applicable):**

```
[14:51:15][C][ota:366]: There have been 1 suspected unsuccessful boot attempts.
[14:51:15][I][app:029]: Running through setup()...
[14:51:15][C][as3935:010]: Setting up AS3935...
[14:51:15][C][as3935:013]:   IRQ Pin: GPIO13 (Mode: INPUT)
[14:51:15][C][wifi:033]: Setting up WiFi...
[14:51:15][D][wifi:324]: Starting scan...
[14:51:15][D][binary_sensor:036]: 'ESP Sturmwarnung': Sending state OFF
....
14:52:09][D][sensor:092]: 'WiFi Signal': Sending state -76.00000 dB with 0 decimals of accuracy
[14:52:31][W][i2c:086]: Requesting 1 bytes from 0x03 failed!
[14:52:31][W][as3935_i2c:029]: Read failed!
[14:52:31][W][i2c:070]: Received NACK on transmit of address 0x03
[14:52:31][W][as3935_i2c:029]: Read failed!

```

**Additional information and things you've tried:**

Name | State | Actions
-- | -- | --
WiFi Signal | -79 dB |  
ESP Sturm entfernung |   |  
ESP Blitz Energie |   |  
ESP Sturmwarnung | OFF |  

Sensor:
![GY-AS3935_01](https://user-images.githubusercontent.com/30198737/90135758-71e48280-dd73-11ea-8119-fddbc39bf066.png)

I don't get any data (distance, energy) and the status is always "OFF".
What am I doing wrong or what is the solution?
