### ISSUE TITLE
TM1637 - time not working

### ISSUE THREAD

**Issue by SnowyTerror** [esphome/issues#1414]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io (Home Assistant) Version: 0.114.0 on Raspberry Pi 4

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 Mini

**ESPHome version (latest production, beta, dev branch)**

Tested on ESPHome Beta Version: 1.15.0b3

**Affected component:**

Link: [https://beta.esphome.io/components/display/tm1637.html?highlight=tm1637](https://beta.esphome.io/components/display/tm1637.html?highlight=tm1637)

**Description of problem:**
The time function in the below link in relation to TM1637 doesn't work at all, once the sketch is uploaded via OTA as normal it would start counting up from when it has started by the minute.

**Problem-relevant YAML-configuration entries:**
```yaml
time:
  - platform: homeassistant
    id: homeassistant_time

display:
  platform: tm1637
  clk_pin: D6
  dio_pin: D5
  update_interval: 500ms
  lambda: |-
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H.%M", id(homeassistant_time).now());
      else
        it.strftime("%H%M", id(homeassistant_time).now());

```

**Logs (if applicable):**

No Logs available

**Additional information and things you've tried:**
Tried different methods for the time to work by either GPS but do not seem to work, attempted multiple times to confirm that when sketch is uploaded it will start counting up by the minute rather than showing correct time.
