### ISSUE TITLE
Manual IP assignment stops time component

### ISSUE THREAD

**Issue by RubyBailey** [esphome/issues#1417]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows 10, VMWare Workstation 15 Player running Ubuntu 18.04.4 LTS
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 Node MCU V2
**ESPHome version (latest production, beta, dev branch)**

v1.14.5
**Affected component:**

https://esphome.io/components/time.html
https://esphome.io/components/wifi.html

**Description of problem:**
When adding manual_ip time component stops working.
Original code was written without manual ip and functioned flawlessly. Added manual ip and noted integration reset was no longer working. Tested by adding in interval component and integration reset functioned again, yet not on minute boundaries as with time component. Commented out interval and manual ip and time + integration reset worked again.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: watermeter
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "removed_ssid"
  password: "removed_password"
# remove comments markers from manual ip lines below and integration reset / time component stops working
#  manual_ip:
#    # IP of ESP
#    static_ip: 192.168.68.186
#    # IP of router
#    gateway: 192.168.68.1
#    # Subnet of network
#    subnet: 255.255.255.0  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Watermeter Fallback Hotspot"
    password: "removed_password"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API - disabled by comment out 
# api:

# Over the air update enabled
ota:

mqtt:
  broker: 192.168.68.190
  # Last will topics and message
  birth_message:
    topic: watermeter/LWT
    payload: Online
  will_message:
    topic: watermeter/LWT
    payload: Offline

# Configure sensor
sensor:
  - platform: pulse_counter
    id: water_pulse
    pin: GPIO14
    name: "Pulse Counter"
    update_interval: 1s

  - platform: integration
    id: water_total_minute
    name: "Water Total Minute"
    sensor: water_pulse
    time_unit: min
    filters:
      - lambda: return x / 439.0;    

time:
  - platform: sntp
    # ...
    on_time:
      # Every minute
      - cron: '0 /1 * * * *'
        then:
          - sensor.integration.reset: water_total_minute    

# Remove comment markers to test that integration reset is still working when manual ip assigned
#interval:
# One  minute
#  - interval: 1min
#    then:
#      - sensor.integration.reset: water_total_minute


```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
