### ISSUE TITLE
ESP32 compile error: redefinition of 'class WiFiUDP' - wifi_component.cpp

### ISSUE THREAD

**Issue by zibous** [esphome/issues#1418]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
python 3.8, OSX

**ESP (ESP32/ESP8266, Board/Sonoff):**
board: esp-wrover-kit; framework: arduino; platform: espressif32@1.12.4
board: esp32dev; framework: arduino; platform: espressif32@1.12.4

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**
wifi

**Description of problem:**

Compile Error: previous definition of 'class WiFiUDP

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32wrom
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "hotlan"
  password: "dx4kkdaoo!e"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Wrom Fallback Hotspot"
    password: "BWVYSbAPOpzd"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "h4ooxd8d"

ota:
  password: "hh4pp&dds"


```

**Logs (if applicable):**

```
INFO Reading configuration production/esp32wrom.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d production/esp32wrom
Processing esp32wrom (board: esp-wrover-kit; framework: arduino; platform: espressif32@1.12.4)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10004.200129 (1.0.4) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa32 2.50200.80 (5.2.0)
Dependency Graph
|-- <AsyncTCP-esphome> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.7
|   |-- <AsyncTCP-esphome> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <DNSServer> 1.1.0
|   |-- <WiFi101> 0.16.0
|-- <Update> 1.0
|-- <WiFi101> 0.16.0
|-- <WiFi> 1.0
Compiling .pioenvs/esp32wrom/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/esp32wrom/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/esp32wrom/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/esp32wrom/src/esphome/core/helpers.cpp.o
Compiling .pioenvs/esp32wrom/src/esphome/core/log.cpp.o

.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/sys/unistd.h:30:9: error: conflicting declaration of C function 'int close(int)'
 int     _EXFUN(close, (int __fildes ));
.platformio/lib/WiFi101/src/socket/include/socket.h:1839:15: note: previous declaration 'sint8 close(SOCKET)'
 NMI_API sint8 close(SOCKET sock);
.platformio/lib/WiFi101/src/WiFiServer.h:31:2: error: 'SOCKET' does not name a type
  SOCKET _socket;
platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/sys/unistd.h:30:9: note: previous declaration 'int close(int)'
 int     _EXFUN(close, (int __fildes ));
...
.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiUdp.h:42:7: error: previous definition of 'class WiFiUDP'
 class WiFiUDP : public UDP {
       ^
*** [.pioenvs/esp32wrom/src/esphome/components/wifi/wifi_component.cpp.o] Error 1
========================== [FAILED] Took 8.34 seconds ==========================
```
