### ISSUE TITLE
ERROR Error binary size: Error: ESP has been flashed with wrong flash size. Please choose the correct 'board' option

### ISSUE THREAD

**Issue by Sennevds** [esphome/issues#1419]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io and pip(on windows 10

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 board sparkfun thing

**ESPHome version (latest production, beta, dev branch)**
Latest on hass.io(1.14.4) and latest on pip (1.14.5)

**Affected component:**
OTA

**Description of problem:**
Can't upload new version over OTA to the thing board. It worked for the pip version 1.14.3 but after updating to the latest version I get following message:
`ERROR Error binary size: Error: ESP has been flashed with wrong flash size. Please choose the correct 'board' option`

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: temperature
  platform: ESP8266
  board: thing

wifi:
  ssid: "*****"
  password: "*****"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperature Fallback Hotspot"
    password: "*****"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "****"

ota:
  password: "****"

dallas:
  - pin: GPIO14

sensor:
  - platform: dallas    
    address: 0x7200000A987F8E28
    name: "Temperature outside"
  - platform: dallas
    address: 0x8D00000AEEF94728
    name: "Temperature pool"

```

**Logs (if applicable):**
```
INFO Reading configuration /config/esphome/temperature.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/temperature
Processing temperature (board: thing; framework: arduino; platform: espressif8266@2.2.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 512KB Flash
PACKAGES: 
 - framework-arduinoespressif8266 2.20502.0 (2.5.2) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa 1.40802.2 (4.8.2)
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.6
|   |-- <ESPAsyncTCP-esphome> 1.2.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling /data/temperature/.pioenvs/temperature/src/main.cpp.o
Linking /data/temperature/.pioenvs/temperature/firmware.elf
Retrieving maximum program size /data/temperature/.pioenvs/temperature/firmware.elf
Checking size /data/temperature/.pioenvs/temperature/firmware.elf
Building /data/temperature/.pioenvs/temperature/firmware.bin
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=====     ]  45.5% (used 37288 bytes from 81920 bytes)
Flash: [========  ]  81.3% (used 406244 bytes from 499696 bytes)
Creating BIN file "/data/temperature/.pioenvs/temperature/firmware.bin" using "/data/temperature/.pioenvs/temperature/firmware.elf"
========================= [SUCCESS] Took 16.43 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of temperature.local
INFO  -> 192.168.0.39
INFO Uploading /data/temperature/.pioenvs/temperature/firmware.bin (410400 bytes)
ERROR Error binary size: Error: ESP has been flashed with wrong flash size. Please choose the correct 'board' option (esp01_1m always works) and then flash over USB.
```
