### ISSUE TITLE
D1_MINI - Firmware flash fails, Device to not start  or problem with log ??

### ISSUE THREAD

**Issue by zibous** [esphome/issues#1424]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip, OSX High Sierra

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 Board Wemos D1 mini kompatibel

**ESPHome version (latest production, beta, dev branch)**
ESPHome v1.15.0b3

**Affected component:**

Board Wemos D1 mini
https://esphome.io/devices/esp8266.html

**Description of problem:**
Firmware flash fails, Device to not start  or problem with log ??

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  device_name_lower: wemosd1
  device_name_upper: "Test Wemos D1"
  device_id: "wmt"
  update_time: 60s
  device_name_short: testwemosd1
  device_description: Simple testcase Wemos D1
  
esphome:
  name: $device_name_short
  comment: ${device_description}
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: true
  platformio_options:
    upload_speed: 115200

wifi:
  power_save_mode: none
  networks:
    - ssid:  !secret ssid1_name
      password: !secret ssid1_pswd
    - ssid:  !secret ssid2_name
      password: !secret ssid2_pswd

captive_portal:

web_server:
  port: 80

# Enable logging
# see: https://esphome.io/components/logger.html?highlight=logging
logger:
  level: VERBOSE

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Zurich
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

sensor:
  
  - platform: wifi_signal
    name: ${device_id} WiFi Signal
    update_interval: ${update_time}
    
  - platform: uptime
    name: "${device_id} Uptime"
  
```

**ESP8266 Board Wemos D1 mini kompatibel**
![wemos_d1_mini_komp01](https://user-images.githubusercontent.com/30198737/90744638-5415a100-e2d0-11ea-8764-5264b2bd59e7.png)

![wemos_d1_mini_komp02](https://user-images.githubusercontent.com/30198737/90744677-57109180-e2d0-11ea-891e-d49433d0667a.png)

**Logs (if applicable):**
```
INFO Reading configuration config/d1Mini.yaml...
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 28 March 02:00:00 to 31 October 03:00:00
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d config/testwemosd1
Processing testwemosd1 (board: d1_mini; framework: arduino; platform: espressif8266@2.6.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20702.0 (2.7.2) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.7
|   |-- <ESPAsyncTCP-esphome> 1.2.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/testwemosd1/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/api/util.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/time/automation.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/web_server/web_server.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/wifi/wifi_component_esp32.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/components/wifi_signal/wifi_signal_sensor.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/core/application.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/core/component.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/core/controller.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/core/esphal.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/core/log.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/core/preferences.cpp.o
Compiling .pioenvs/testwemosd1/src/esphome/core/util.cpp.o
Compiling .pioenvs/testwemosd1/src/main.cpp.o
Linking .pioenvs/testwemosd1/firmware.elf
Retrieving maximum program size .pioenvs/testwemosd1/firmware.elf
Checking size .pioenvs/testwemosd1/firmware.elf
Building .pioenvs/testwemosd1/firmware.bin
RAM:   [=====     ]  47.8% (used 39124 bytes from 81920 bytes)
Flash: [====      ]  43.1% (used 449876 bytes from 1044464 bytes)
Creating BIN file ".pioenvs/testwemosd1/firmware.bin" using "/Users/petsie1612/.platformio/packages/framework-arduinoespressif8266@3.20702.0/bootloaders/eboot/eboot.elf" and ".pioenvs/testwemosd1/firmware.elf"
========================= [SUCCESS] Took 11.91 seconds =========================
INFO Successfully compiled program.
INFO Running:  esptool.py --before default_reset --after hard_reset --baud 115200 --chip esp8266 --port /dev/cu.wchusbserialfa1340 write_flash 0x0 config/testwemosd1/.pioenvs/testwemosd1/firmware.bin
esptool.py v2.8
Serial port /dev/cu.wchusbserialfa1340
Connecting....
Chip is ESP8266EX
Features: WiFi
WARNING: Detected crystal freq 156.33MHz is quite different to normalized freq 40MHz. Unsupported crystal in use?
Crystal is 40MHz
MAC: 48:3f:da:66:54:d9
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 454032 bytes to 312822...
Wrote 454032 bytes (312822 compressed) at 0x00000000 in 164.5 seconds (effective 22.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
INFO Successfully uploaded program.
INFO Starting log output from /dev/cu.wchusbserialfa1340 with baud rate 115200
[10:06:59]
  
```
Restart:
```
Showing Logs For: d1Mini.yaml
INFO Reading configuration config/d1Mini.yaml...
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 28 March 02:00:00 to 31 October 03:00:00
INFO Starting log output from /dev/cu.wchusbserialfa1340 with baud rate 115200

```

**Additional information and things you've tried:**

What am I doing wrong ? 
f I use other firmware e.g. Tasmota, ESPEasy ..., then the board starts and works.

Is there a solution for that?
