### ISSUE TITLE
Puls counter not correct.

### ISSUE THREAD

**Issue by mrrjames** [esphome/issues#1428]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**
ESPHome version 1.14.4

**Affected component:**

**Description of problem:**
I have made a puls counter reader with a nodemcuv2 with photoresistor, I used a scritpt with   filters:
       - multiply: 0.06, because my meter has a C 1000. 
But the readings are way to much, if i check the correct watts then it is in home assistant much more. I checked the pulses on the photo resistor en the are good and the same as the original meter.  So the pulses are good. The readings aren't.
I don't know why the reading are wrong, 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: solarmeter
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "mywifi"
  password: "mywifi"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Solarmeter Fallback Hotspot"
    password: "00"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "**********"

ota:
  password: "**********"

# Enable Web server
web_server:
  port: 80

sensor:
  # Uptime sensor
  - platform: uptime
    name: Elec Meter Uptime
    

  # WiFi Signal sensor
  - platform: wifi_signal
    name: Elec Meter WiFi Signal
    update_interval: 1s
  
  #########################################
  #
  # Electricity usage
  #
  #########################################
    
  # usage right now in kW
  - platform: pulse_counter
    pin: D5
    unit_of_measurement: 'kW'
    name: 'Power Meter'
    id: power_meter
    filters:
       - multiply: 0.06
    
    
  # converts above to kWh used today
  - platform: total_daily_energy
    name: "Total Daily Energy test"
    power_id: power_meter
    id: kwh_so_far
    
switch:
  # Switch to restart
  - platform: restart
    name: Electricity meter monitor restart
    
# Sync time
time:
  - platform: sntp
    id: my_time
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Did a filter > internal_filter: 10us
But this doesn't work.
