### ISSUE TITLE
White value is not restored when switching back to white

### ISSUE THREAD

**Issue by Leon99** [esphome/issues#1433]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io 0.114.2

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

1.15.0b3

**Affected component:**

RGBWW

**Description of problem:**
When switching from white to an RGB color, the white value goes to 0 (perfect).
However, when switching back to white, the white value remains 0.

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: rgbww
    name: 'RGBWW Light'
    default_transition_length: 0s
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_coldwhite
    warm_white: output_warmwhite
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    restore_mode: ALWAYS_ON
```
