### ISSUE TITLE
SNTP ignores time zones

### ISSUE THREAD

**Issue by f403** [esphome/issues#1434]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** pip

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP8266

**ESPHome version (latest production, beta, dev branch)** beta, dev; latest must be affected as well

**Affected component:** sntp

**Description of problem:**

sntp ignores time zones, both `.now()` and `.utcnow()` return same values.

Time zones support seems to be disabled for ESP8266 in [sntp_component.cpp](https://github.com/esphome/esphome/blob/beta/esphome/components/sntp/sntp_component.cpp#L38). 

Deleting [line 38](https://github.com/esphome/esphome/blob/beta/esphome/components/sntp/sntp_component.cpp#L38) there solves this issue.

Does anybody know, what were the intentions there?
```c++
#ifdef ARDUINO_ARCH_ESP8266
  // let localtime/gmtime handle timezones, not sntp
  sntp_set_timezone(0);
#endif
```

**Problem-relevant YAML-configuration entries:**
```yaml
time:
  - platform: sntp
    id: sntp_time
    timezone: 'Europe/Berlin'

display:
...
    lambda: |-
      auto time = id(sntp_time).now();
      it.strftime(1, 1, id(digit_font_main), "%H:%M", time);
```

**Logs (if applicable):**

**Additional information and things you've tried:**

**Comment by thedexboy** [comment]
Can confirm. Latest dev version has this issue as well.
Man, I thought I was going nuts for a second there... :)

**Comment by dclobato** [comment]
Same here.  I was about to open a issue on this 👍

**Comment by allan-reynolds** [comment]
Same here, I have been going nuts.  I had just done a big rehash of my config for some of my esp8266 devices and spent several days convinced I had gone back to the original config.  then realised I had not updated these devices for a while came here searching before opening an issue and found this.

I am using the 1.15.b4 via Hass.io addon.

**Comment by ssieb** [comment]
Likely related to https://github.com/esphome/esphome/pull/1231

**Comment by dclobato** [comment]
I have changed the time source from SNTP to Home Assistant and, now, I always get "01/01/1970 00:00:00" as time when syncing. The machine running HA is with the right time (automations are running on time)

```yaml
time:
  - platform: homeassistant
    id: local_time
```

```
[17:05:25][D][api.connection:604]: Client 'Home Assistant 0.114.1 (10.0.1.4)' connected successfully!
[17:05:25][D][time:029]: Synchronized time: Wed Dec 31 21:00:14 1969
```

I believe the problem is not on the SNTP component, but somewhere on the time component, as @ssieb pointed above.
