### ISSUE TITLE
Inconsistent Reporting From DHT11

### ISSUE THREAD

**Issue by timelyfiasco** [esphome/issues#1439]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp12
**ESPHome version (latest production, beta, dev branch)**

1.15-dev
**Affected component:**

https://esphome.io/components/sensor/dht.html

**Description of problem:**
I have tried 
  update_interval: 2s, 5s, 15s
  run_duration: 45s, 30s
  sleep_duration: 10min
What could possibly be the problem why I am getting inconsistent result?
The chart is usable but I want to fix the problem
Sometimes, there is no update after 10mins. 
Sometimes, it updates one value only (either temp or humidity).
**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
sensor:
deep_sleep:
  id: deep_sleep_1
  run_duration: ${run_duration}
  sleep_duration: ${sleep_duration}
sensor:
  - platform: dht
    pin: 14
    temperature:
      name: "${project} Temperature"
    humidity:
      name: "${project} Humidity"
    model: DHT11
    update_interval: ${update_interval}
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

at 5s run_duration
I receive very few dht reading, <10%
at 45s run_duration
![pasted_image](https://user-images.githubusercontent.com/33004592/91165998-3b5c1f80-e704-11ea-8bc6-5ab22e1f0d4c.png)
without sleep
![pasted_image001](https://user-images.githubusercontent.com/33004592/91166023-431bc400-e704-11ea-8068-0c2ea3372959.png)
