### ISSUE TITLE
Total Daily Energy Sensor value jumps when turning on device (not gradually)

### ISSUE THREAD

**Issue by 7h30n3** [esphome/issues#1442]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant: 0.114.4

**ESP (ESP32/ESP8266, Board/Sonoff):**

Gosund SP112 V3.4

```
  platform: ESP8266
  board: esp8285
```

**ESPHome version (latest production, beta, dev branch)**

ESPHome: 1.15.0b4

**Affected component:**

https://esphome.io/components/sensor/total_daily_energy.html

**Description of problem:**
My Device uses around 20W in idle. Turned on the power consumption is around 120W.
Turning on the device I would expect that the graph for the total daily energy (TDE) grows gradually with a slope depending on the power consumption.

However, as soon as I turn on the device the value for TDE jumps and then grows gradually.

<img width="301" alt="Anmerkung 2020-08-30 104035" src="https://user-images.githubusercontent.com/18004390/91655428-b2046e80-eab0-11ea-9b23-de6f4350f5ee.png">
<img width="301" alt="Anmerkung 2020-08-30 104003" src="https://user-images.githubusercontent.com/18004390/91655453-deb88600-eab0-11ea-9dad-e428237908ca.png">

**Problem-relevant YAML-configuration entries:**
```yaml
  # Total daily energy sensor
  - platform: total_daily_energy
    name: ${device_name} Daily Energy
    power_id: power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
