### ISSUE TITLE
Automation is not working as expected

### ISSUE THREAD

**Issue by stich86** [esphome/issues#1443]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 / nodemcu

**ESPHome version (latest production, beta, dev branch)**
ESPHome version 1.14.5

**Affected component:**
automation

**Description of problem:**
I'm trying to close a template cover when a rain sensor close a GPIO on the ESP but putting two condition: A maintenance-switch is not on (for example to clean the sensor and avoid cover closing) and the binary_sensor (attached to the rain sensor) is on for a least 1,5s (this is just for test, in production it should be at least 5s)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: wemos_terrazzo
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: "IoT"
  password: "xxxxx"
  reboot_timeout: 30s

binary_sensor:
  - platform: status
    name: "Stato ESP Terrazzo"
  - platform: gpio
    pin:
      number: D7
      inverted: True
      mode: INPUT_PULLUP
    name: "Sensore Pioggia"
    device_class: moisture
    id: rain_sensor
    on_state:
     then:
        if:
         condition:
           for:
             time: 1500ms
             condition:
               - switch.is_off: maint_switch
               - binary_sensor.is_on: rain_sensor
         then:
           - logger.log: "Got it!"
           - cover.close: cover_1

switch:
  - platform: gpio
    pin: D1
    name: "Relay Contatto Apri-Tenda"
    id: relay_1
    internal: False
    inverted: True
  - platform: gpio
    pin: D2
    name: "Relay Contatto Chiudi-Tenda"
    id: relay_2
    internal: False
    inverted: True
  - platform: template
    name: "Manutenzione"
    id: maint_switch
  - platform: restart
    name: "Riavvia Wemos Terrazzo"

cover:
  - platform: template
    name: "Pergotenda"
    open_action:
    - switch.turn_on: relay_1
    - delay: 1500ms
    - switch.turn_off: relay_1
    close_action:
    - switch.turn_on: relay_2
    - delay: 1500ms
    - switch.turn_off: relay_2
    stop_action:
    - switch.turn_on: relay_1
    - switch.turn_off: relay_1
    optimistic: true
    id: cover_1

sensor:
  - platform: uptime
    name: "Uptime Wemos Terrazzo"
  - platform: wifi_signal
    name: "Segnale WiFi Wemos Terrazzo"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "ESPHome Version"

logger:

api:
  password: "xxxx"
  reboot_timeout: 30s

ota:
  password: "xxxx"

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by stich86** [comment]
ok, i've solved in this way (just binary sensor part):

```
binary_sensor:
  - platform: status
    name: "Stato ESP Terrazzo"
  - platform: gpio
    pin:
      number: D7
      inverted: True
      mode: INPUT_PULLUP
    name: "Sensore Pioggia"
    device_class: moisture
    id: rain_sensor
    filters:
      - delayed_on: 2s
      - delayed_off: 60s
    on_press:
      then:
        - if:
            condition:
              switch.is_off: maint_switch
            then:
              cover.close: cover_1
```

you can close the issue
