### ISSUE TITLE
global variable does not survive power-cyle

### ISSUE THREAD

**Issue by pille** [esphome/issues#1444]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

integrated with Home Assistant 0.114.4

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266/d1_mini

**ESPHome version (latest production, beta, dev branch)**

Version: 1.14.5
**Affected component:**

https://esphome.io/guides/automations.html#bonus-2-global-variables

**Description of problem:**
i'm reading out a meter using a hall sensor with ```pulse_counter```.
since the meter only gives pulses, i need to add an offset to get the correct value.
i've configured this using a global variable (```gas_meter_offset```), that should be saved across reboots.
however - the stored value only survives a reset (triggered by button). during a complete power cycle this value gets lost.

**Problem-relevant YAML-configuration entries:**
```yaml
globals:
  - id: gas_meter_offset
    type: float
    restore_value: true
    initial_value: "100.0"

sensor:
  - platform: pulse_counter
    name: "Gas Meter"
    id: gas_meter
    pin: D4
    icon: "mdi:fire"
    update_interval: 10s
    unit_of_measurement: "m³"
    accuracy_decimals: 3
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 100ms
    filters:
      - lambda: |-
          id(gas_meter_offset) += x / 6 * 0.01;
          return id(gas_meter_offset);
```

**Logs (if applicable):**

there's nothing about restoring global variables in the logs.

**Additional information and things you've tried:**
