### ISSUE TITLE
BME280 sensor show values near two grades higher than other temperature sensors

### ISSUE THREAD

**Issue by damocles-git** [esphome/issues#1449]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32cam

**ESPHome version (latest production, beta, dev branch)**

Version: 1.14.5

**Affected component:**

BME280

**Description of problem:**

I have several temperature sensors across the floor but the BME280 managed by esphome is near two grades celsius higher than the rest.

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:38:38:76
    temperature:
      name: "Xiaomi Temperature"
      accuracy_decimals: 2
    humidity:
      name: "Xiaomi Humidity"
      accuracy_decimals: 2
    battery_level:
      name: "Xiaomi Battery Level"
      accuracy_decimals: 2
  - platform: bme280
    temperature:
      name: "esp32cam_02_Temperature"
      oversampling: '1x'
      accuracy_decimals: 2
    pressure:
      name: "esp32cam_02_Presure"
      oversampling: '1x'
      accuracy_decimals: 2
    humidity:
      name: "esp32cam_02_Humidity"
      oversampling: '1x'
      accuracy_decimals: 2
    address: 0x76
    update_interval: 60s

```

**Logs (if applicable):**

The next four logs are from sensors in the same room (hall) with all doors closed for better temperature stability.

esp32cam/esphome + BME280: **25.0°C**
```
[14:47:46][D][bme280.sensor:197]: Got temperature=25.0°C pressure=1015.8hPa humidity=52.5%
[14:47:46][D][sensor:092]: 'esp32cam_02_Temperature': Sending state 25.03000 °C with 2 decimals of accuracy
[14:47:46][D][sensor:092]: 'esp32cam_02_Presure': Sending state 1015.82623 hPa with 2 decimals of accuracy
[14:47:46][D][sensor:092]: 'esp32cam_02_Humidity': Sending state 52.52734 % with 2 decimals of accuracy
```
esp32cam/esphome + Xiaomi LYWSDCGQ: **23.0°C**
```
[14:47:59][D][xiaomi_ble:161]: Got Xiaomi LYWSDCGQ (58:2D:34:38:38:76):
[14:47:59][D][xiaomi_ble:164]:   Temperature: 23.0°C
[14:47:59][D][xiaomi_ble:167]:   Humidity: 61.8%
[14:47:59][D][sensor:092]: 'Xiaomi Temperature': Sending state 23.00000 °C with 2 decimals of accuracy
[14:47:59][D][sensor:092]: 'Xiaomi Humidity': Sending state 61.80000 % with 2 decimals of accuracy
```
wemos_mini_d1/tasmota + BME280: **23.1°C**
```
2020-09-02T14:49:04.351480+02:00 tasmota_A7CF8A-3978 ESP-RSL: tele/tasmota_A7CF8A/SENSOR = {"Time":"2020-09-02T14:49:04","BME280":{"Temperature":23.1,"Humidity":55.9,"De
wPoint":13.8,"Pressure":1015.7},"PressureUnit":"hPa","TempUnit":"C"}
```

zigbee2mqtt + Xiaomi Aqara WSDCGQ11LM: **22.87°C**
```
2020-09-02T14:47:49+02:00 rpi0-01 npm[8671]: #033[32mzigbee2mqtt:info #033[39m 2020-09-02 14:47:49: MQTT publish: topic 'casa/zigbee2mqtt/xiaomi-weather-01', payload '{"temperature":22.87,"linkquality":0,"humidity":63.85,"pressure":1013.5,"battery":97,"voltage":2995,"device":{"friendlyName":"xiaomi-weather-01","model":"WSDCGQ11LM","ieeeAddr":"0x00158d00034d1c9b","networkAddress":63325,"type":"EndDevice","manufacturerID":4151,"manufacturerName":"LUMI","powerSource":"Battery","applicationVersion":3,"stackVersion":2,"zclVersion":1,"hardwareVersion":30,"dateCode":"20161129","softwareBuildID":"3000-0001"}}'
```
**Additional information and things you've tried:**

I have tried to change oversampling values from 1x to 16x and does not change the result of the readings and esphome+BME280 is **consistently** almost two degrees higher than all other sensors.
