### ISSUE TITLE
Binary status sensor disappears in HA 0.114.4

### ISSUE THREAD

**Issue by Kaibob2** [esphome/issues#1451]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

arch | x86_64
chassis | desktop
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | Ubuntu 20.04.1 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 5.4.0-42-generic
python_version | 3.8.3
supervisor | 235
timezone | Europe/Berlin
version | 0.114.4
virtualenv | false

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 mini

**ESPHome version (latest production, beta, dev branch)**

v1.14.5

**Affected component:**

binary sensor: platform: status

**Description of problem:**
I have no absolute moment from when the problems started but i suppose it was working fine with the last HA main version.
In fact it is two problems:
The first was, that when domain isn't specified it defaults to .local (which was no problem until some time ago) but lastly some nodes reported offline in the dashboard and some others didn't. This was easy to fix by adding domain: .fritz.box, as this is my local domain. All FritzBoxes should resolve .local to internal, too, so I have no idea why adding my domain fixed this. So, solved, even if not perfect.
The second issue is more complicated. All nodes, 15 Wemos D1 mini, have a binary status sensor. When one goes offline it is reported as offline in Homeassistant. At that moment i got a push message via nodeRed that a node is offline. (happened almost never) This was working perfect until something changed i don't know of. Lastly some nodes reported offline a couple times per day and the status sensor went unavailable in HA. All other sensors or switches continued working like normal and I could only get the status sensor back by restarting the node. I tried different SSIDs and a blank Wemos with only a status and a SSID sensor without luck. After an elightning conversation on the discord channel i installed the ESPhome beta addon and upgraded all nodes to 1.15.0b4. To my surprise from that moment on not one node disconnected or reported offline. They all are rock solid for days now.
I'm sorry that I can't narrow it down any further but maybe this is of help for somebody.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: klingel
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
  - ssid: "xxxx"
    password: "xxxx"
  reboot_timeout: 5min
  domain: .fritz.box

# Enable fallback hotspot (captive portal) in case wifi connection fails
# AP IP: 192.168.4.1
  ap:
    ssid: "xxxx"
    password: "xxxx"

captive_portal:


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxxx"

ota:
  password: "xxxxx"

switch:
  - platform: gpio
    pin: D6
    name: "Klingel an"
    restore_mode: ALWAYS_ON
    inverted: yes
  - platform: restart
    name: "Klingel restart"
    
binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    name: "Klingeltaster"
    filters:
      - delayed_on: 100ms
  - platform: status
    name: "Klingel verbindung"

sensor:    
  - platform: wifi_signal
    name: "Klingel Signal"
    update_interval: 60s
    
status_led:
  pin:
    number: GPIO2
    inverted: True   

text_sensor:
  - platform: wifi_info
    ssid:
      name: "Klingel WiFi SSID"     

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
