### ISSUE TITLE
Wildly differing BMP280 SeaPressure and Altitude results

### ISSUE THREAD

**Issue by pashdown** [esphome/issues#1456]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 Wemos d1mini BMP280
**ESPHome version (latest production, beta, dev branch)**

1.14.4
**Affected component:**

https://esphome.io/cookbook/bme280_environment.html

**Description of problem:**
I'm getting wildly differing results from the formulas for SeaPressure and Altitude on four different BMP280 distributed in my house.  There are two in the basement, one on the second floor, and one in the attic.  The temperatures in these three locations are all different, and I'm wondering if I should be using an outside temperature for this calculation instead of what is on the sensor of the BMP280?

Here's an example of my altitude results when they're all going off the same SeaPressure reading from a nearby station:

- Basement: 1497.7 & 1494.7 (these are within 2 lateral meters of each other)
- 2nd Level: 1498.1
- Attic: 1453.2

Needless to say, my attic is not lower in elevation than my basement, but its temperature can be significantly colder or hotter.  When I took these measurements, it was significantly colder.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: bmp280
    temperature:
      name: "Attic BMP280 Temperature"
      id: attic_bmp280_temperature
      oversampling: 16x
    pressure:
      name: "Attic BMP280 Pressure"
      id: attic_bmp280_pressure
    address: 0x76
    update_interval: 30s
  - platform: template
    name: "Attic BMP280 SeaPressure"
    icon: mdi:gauge
    lambda: |-
      const float STANDARD_ALTITUDE = 1464.7; // in meters, see note
      return id(attic_bmp280_pressure).state / powf(1 - ((0.0065 * STANDARD_ALTITUDE) /
        (id(attic_bmp280_temperature).state + (0.0065 * STANDARD_ALTITUDE) + 273.15)), 5.257); // in hPa
    update_interval: 30s
    unit_of_measurement: hPa
  - platform: template
    name: "Attic Altitude"
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1021.6; //in hPa, see note
      return ((id(attic_bmp280_temperature).state + 273.15) / 0.0065) *
        (powf((STANDARD_SEA_LEVEL_PRESSURE / id(attic_bmp280_pressure).state), 0.190234) - 1); // in meter
    update_interval: 15s
    icon: 'mdi:signal'
    unit_of_measurement: 'm'

```

**Logs (if applicable):**

```
[21:03:28][D][sensor:092]: 'Attic Absolute Humidity': Sending state 4.07493 g/m³ with 2 decimals of accuracy
[21:03:30][D][sensor:092]: 'Attic Altitude': Sending state 1453.23730 m with 1 decimals of accuracy
[21:03:33][D][bmp280.sensor:149]: Got temperature=13.4°C pressure=861.5hPa
[21:03:33][D][sensor:092]: 'Attic BMP280 Temperature': Sending state 13.40000 °C with 1 decimals of accuracy
[21:03:33][D][sensor:092]: 'Attic BMP280 Pressure': Sending state 861.45123 hPa with 1 decimals of accuracy
[21:03:33][D][sensor:092]: 'Attic BMP280 SeaPressure': Sending state 1022.94604 hPa with 1 decimals of accuracy

```

**Additional information and things you've tried:**
I've looked at other SeaPressure formulas out there and none of them include temperature.
