### ISSUE TITLE
http_request.post connection lost error in logs even if post was sent successfully

### ISSUE THREAD

**Issue by slynn1324** [esphome/issues#1463]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

docker esphome/esphome:beta

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 nodemcuv2

**ESPHome version (latest production, beta, dev branch)**

1.15.0b4

**Affected component:**

https://next.esphome.io/components/http_request.html

**Description of problem:**
When sending an HTTP Post to send a Pushover notification, the logs report "Error: connection list" for the HTTP request, but the request was sent and the alerts come through Pushover as expected.  I don't know what it doesn't like about the end of the connection, but it would be nice to not have false errors in the logs.

**Problem-relevant YAML-configuration entries:**
```yaml

http_request:
  useragent: esphome
  timeout: 10s

interval:
  - interval: 1min
    then:
      - http_request.post:
          verify_ssl: false
          url: https://api.pushover.net/1/messages.json
          headers:
            Content-Type: application/json
          json:
            token: ...omitted... 
            user: ...omitted...
            title: ESPHome
            message: Hello from ESPHome Device

```

**Logs (if applicable):**

```
[16:32:27][C][http_request:010]: HTTP Request:
[16:32:27][C][http_request:011]:   Timeout: 10000ms
[16:32:27][C][http_request:012]:   User-Agent: esphome
...
[16:32:40][W][http_request:048]: HTTP Request failed; URL: https://api.pushover.net/1/messages.json; Error: connection lost
```

**Additional information and things you've tried:**
