### ISSUE TITLE
SHT3X-D needs to report and control heater status

### ISSUE THREAD

**Issue by Drizzt321** [esphome/issues#1465]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io Home-Assistant, 0.114.4 from the QCOW VM image, ESPHome 1.14.4 from HA Integrations.

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, Wemos D1 mini

**ESPHome version (latest production, beta, dev branch)**

ESPHome 1.14.4 from HA Integrations

**Affected component:**

SHT3X-D temperature/humidity i2c sensor
https://esphome.io/components/sensor/sht3xd.html

**Description of problem:**

So I got some cheap SHT31-D boards from Amazon, and they are reporting temperatures quite a bit above what I would expect from other thermometers I have. I've also compared using a Adafruit SHT31-D board + Arduino with their sample code, with the heater off. Looks like the cheap ones I got start off with the heater on. Since ESPHome code doesn't turn it off to start with, it reports significantly higher temps than it should.

For example, the Adafruit Huzzah with these cheapo SHT31-D is reporting ~76F and ~57% humidity, one of the D1 mini with the Adafruit SHT31-D and ESPHome is reporting ~76F and 57% humidity. A separate D1 mini with the cheapo SHT31-D is reporting ~84F and 45% humidity. This SHT31-D is fresh, hasn't been set to be heater off via the Arduino code, so I presume the default is heater set to on. 

I think the SHT3X-D code should expose the Heater status (On/Off), and provide a control to turn the heater on and off. This lets HA script on/off the heater in a controlled fashion to evaporate/help remove condensation that may build up. 

**Problem-relevant YAML-configuration entries:**
```yaml
i2c:
  sda: 4
  scl: 5
  scan: True
  id: bus_a
sensor:
  - platform: sht3xd
    temperature:
      name: "Kitchen Room Temperature"
    humidity:
      name: "Kitchen Room Humidity"
    address: 0x44
    update_interval: 60s
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
