### ISSUE TITLE
hass.io addon does not allow you to set the color_interlock variable.

### ISSUE THREAD

**Issue by tduffy83** [esphome/issues#1468]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
N/A

**ESPHome version (latest production, beta, dev branch)**
Latest via hass.io addon

**Affected component:**
hass.io addon

**Description of problem:**

Trying to set the color_interlock variable in light.rgw gives error "[color_interlock] is an invalid option for [light.rgbw]. Please check the indentation."

**Problem-relevant YAML-configuration entries:**

```
light:
   - platform: rgbw
     name: Pedestal
     id: Merkury_75w_RGBW_Bulb
     red: sm16716_red
     green: sm16716_green
     blue: sm16716_blue
     white: pwm_white
     color_interlock: True
```

**Logs (if applicable):**

N/A

**Additional information and things you've tried:**
