### ISSUE TITLE
Exception: Unable to find size and start point in file eboot.elf

### ISSUE THREAD

**Issue by dominikheinz** [esphome/issues#1476]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
HassOS 4.13, Supervisor Version 243, EspHome Version  1.15.1

**ESP (ESP32/ESP8266, Board/Sonoff):**
Generic ESP8266

**ESPHome version (latest production, beta, dev branch)**
ESPHome Addon version: 1.15.1

**Affected component:**
Most likely this one: https://esphome.io/devices/sonoff_s20.html however, the issue does not seem to be component specific.

**Description of problem:**
After a fresh install, I added a node and wanted to compile the bin, so that I can flash it on the target device. The script validated just fine.
During compilation, the follow exception is thrown: `Unable to find size and start point in file eboot.elf for .text` See the screenshot for details.

![esphome build error](https://user-images.githubusercontent.com/32770080/93283331-a1eacf80-f7d0-11ea-9dee-8ab6a16101c3.PNG)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: smartplug1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: censored
  password: censored
  
  manual_ip:
    static_ip: 192.168.1.195
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  ap:
    ssid: censored
    password: censored

api:

logger:

ota:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S20 Button"
  - platform: status
    name: "Sonoff S20 Status"


switch:
  - platform: gpio
    name: "Sonoff S20 Relay"
    pin: GPIO12

output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: s20_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Sonoff S20 Green LED"
    output: s20_green_led
```

**Logs (if applicable):**
See the screenshot.

**Additional information and things you've tried:**
Restarting EspHome. Reinstalling EspHome.
