### ISSUE TITLE
MQTT Config Validation Fails When MQTT Component Defined in a Package

### ISSUE THREAD

**Issue by DeanCording** [esphome/issues#1487]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Ubuntu/pip/Mosquitto

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**ESPHome version (latest production, beta, dev branch)**

1.15.1
**Affected component:**

https://esphome.io/guides/configuration-types.html#packages

**Description of problem:**
When config for MQTT component is placed in a package the config validation fails.

**Problem-relevant YAML-configuration entries:**
This config works:
```yaml
esphome:
  name: test
  platform: ESP8266
  board: esp12e
  build_path: ./build/test

wifi:
  ssid: "Home"
  password: "xxxxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"

captive_portal:

debug:

# Enable logging
logger:
  level: debug
  
ota:

mqtt:
  broker: xxxxxxxxx
  username: xxxxxx
  password: xxxxxxxx
  discovery: false

time:
   - platform: sntp
     servers: xxxxxxxx
     id: sntp_time

status_led:
  pin:
    number: GPIO2
    inverted: true

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
      
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 10s
    expire_after: 2min

```

Placing this configuration in a package causes the config validation to fail.

base.yaml
```yaml
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp12e
  build_path: ./build/${device_name}

wifi:
  ssid: "Home"
  password: "xxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}

captive_portal:

debug:

# Enable logging
logger:
  level: debug

ota:

mqtt:
  broker: iot64.xxx.xxx
  username: xxxxxxx
  password: xxxxxx
  discovery: false
  
time:
   - platform: sntp
     servers: ntp.xxxx
     id: sntp_time

status_led:
  pin:
    number: GPIO2
    inverted: true
    
text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 10s
    expire_after: 2min
```
test.yaml
```yaml
substitutions:
  device_name: test

packages:
  config: !include config/base.yaml
```

**Logs (if applicable):**

```
$ esphome test.yaml run
INFO Reading configuration test.yaml...
INFO Detected timezone 'AEST' with UTC offset 10
Failed config

sensor.wifi_signal: [source config/base.yaml:55]
  platform: wifi_signal
  name: WiFi Signal Sensor
  update_interval: 60s
  
  This option requires component mqtt.
  expire_after: 2min [source base.yaml:58]
```

**Additional information and things you've tried:**
