### ISSUE TITLE
WiFi connection issue since Version 1.15.0

### ISSUE THREAD

**Issue by Chris591** [esphome/issues#1496]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):** Sonoff Basic

**ESPHome version (latest production, beta, dev branch)** v1.15.1

**Affected component:** WiFi

**Description of problem:** WiFi can't connect

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
substitutions:
  device_name: test_licht64

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "${device_name} Fallback Hotspot"
#    password: !secret wifi_fallback_password
#
#captive_portal:

# Enable logging
logger:
#  level: VERBOSE

# Enable Web server
web_server:
  port: 80

# Enable Home Assistant API
api:

# Enable Home Assistant API.
ota:

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${device_name}_Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${device_name}_WiFi_Signal
    update_interval: 60s


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name}_Button"
    on_press:
      - switch.toggle: relay
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name}_Taster"
    filters:
      # Small filter, to debounce the button press.
      - delayed_on: 100ms
#      - delayed_off: 1s
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${device_name}_Switch"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
[12:26:39][I][wifi:194]: WiFi Connecting to 'ABC'...
[12:26:45][W][wifi_esp8266:392]: Event: Disconnected ssid='ABC' reason='Probe Request Unsuccessful'
[12:26:45][W][wifi:485]: Error while connecting to network.
[12:26:45][W][wifi:522]: Restarting WiFi adapter...
... repeating these messages all the time ...
```

**Additional information and things you've tried:**

If I enable verbose logging I don't see the issue anymore!
