### ISSUE TITLE
Shelly 2.5: i2c NACK issue with ADE7953

### ISSUE THREAD

**Issue by Savjee** [esphome/issues#1497]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
HassOS with the ESPHome add-on

**ESP (ESP32/ESP8266, Board/Sonoff):**
Shelly 2.5 (ESP8266, 1MB)

**ESPHome version (latest production, beta, dev branch)**
`ESPHome version 1.15.1 compiled on Sep 20 2020, 15:35:25`

**Affected component:**
ADE7953 Power Sensor: https://esphome.io/components/sensor/ade7953.html?highlight=ade795

**Description of problem:**
I'm using a configuration for the Shelly 2.5 from this website: https://esphome-configs.io/devices/shelly-25/

Trying to get the power sensor to work, without success. On boot, ESPHome finds no i2c device:

```
[15:35:58][C][i2c:028]: I2C Bus:
[15:35:58][C][i2c:029]:   SDA Pin: GPIO12
[15:35:58][C][i2c:030]:   SCL Pin: GPIO14
[15:35:58][C][i2c:031]:   Frequency: 50000 Hz
[15:35:58][I][i2c:033]: Scanning i2c bus for active devices...
[15:35:58][I][i2c:049]: Found no i2c devices!
```

After about a minute, these `NACK` messages start to show up:

```
[15:40:39][W][i2c:070]: Received NACK on transmit of address 0x38
[15:40:39][W][i2c:070]: Received NACK on transmit of address 0x38
[15:40:39][W][i2c:070]: Received NACK on transmit of address 0x38
[15:40:39][W][i2c:070]: Received NACK on transmit of address 0x38
[15:40:39][W][i2c:070]: Received NACK on transmit of address 0x38
```

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: ade7953
    voltage:
      name: ${devicename} voltage
    current_a:
      name: ${channel_2} current
      internal: true
    current_b:
      name: ${channel_1} current
      internal: true
    active_power_a:
      name: ${channel_2} power
      id: power_channel_2
      filters:
        - multiply: 1
      on_value_range:
        - above: ${max_power}
          then:
            - light.turn_off: lightid2
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${devicename}
                data_template:
                  message: Switch turned off because power exceeded ${max_power}W
    active_power_b:
      name: ${channel_1} power
      id: power_channel_1
      filters:
        - multiply: -1
      on_value_range:
        - above: ${max_power}
          then:
            - light.turn_off: lightid1
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${devicename}
                data_template:
                  message: Switch turned off because power exceeded ${max_power}W
    update_interval: 30s
```

**Logs (if applicable):**

This is the problematic one:
```
[15:40:39][W][i2c:070]: Received NACK on transmit of address 0x38
```

**Additional information and things you've tried:**

Things I've tried so far:
* Checked the GPIO numbers & pinouts. They seem correct (and match with Tasmota)
* Tried all i2c bus frequencies
* Restarted the Shelly with the [Restart switch](https://esphome.io/components/switch/restart.html?highlight=restart) 

Unfortunately, I can't easily power-cycle the device because it's in a wall.

I have two Shelly 2.5 units that have this issue. I guess the sensor is going into sleep mode and doesn't recover from that.
