### ISSUE TITLE
Sensor ntc higher tempature by 10 degrees then in reality

### ISSUE THREAD

**Issue by dzikus** [esphome/issues#1502]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

Shelly 2.5

**ESPHome version (latest production, beta, dev branch)**

1.15.1

**Affected component:**

ntc, resistance, adc

**Description of problem:**

On 1.14.5 temperature is compatible with original Shelly firmware (indications are very similar), starting since 1.15 temperature is higher by ~10 degerees C/K.
These two are in the same wall, very close to each other (2cm gap between):
<img width="674" alt="Zrzut ekranu 2020-09-21 o 15 22 02" src="https://user-images.githubusercontent.com/3209066/93771937-7a579500-fc1e-11ea-9b16-160fb04b244a.png">
<img width="670" alt="Zrzut ekranu 2020-09-21 o 15 22 40" src="https://user-images.githubusercontent.com/3209066/93771958-804d7600-fc1e-11ea-9152-ff36f593cdd6.png">

Here is history graph of another one ntc temperature also in the same wall before and after upgrade to 1.15:
<img width="448" alt="Zrzut ekranu 2020-09-21 o 15 28 16" src="https://user-images.githubusercontent.com/3209066/93772543-3913b500-fc1f-11ea-8e78-06aa33acdf96.png">

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: shelly25_wykusz_prawy
  longdevicename: Wykusz prawy
  pin_led1: GPIO0
  pin_button1: GPIO2
  pin_relay1: GPIO15
  pin_switch2n: GPIO5
  pin_sda: GPIO12
  pin_switch1n: GPIO13
  pin_scl: GPIO14
  pin_relay2: GPIO4
  pin_ade7953: GPIO16
  pin_temp: A0
  open_duration: 26s
  close_duration: 25s
#  open_duration: 27s
#  close_duration: 26s
  max_power: "200"
  max_temp: "70.0"

esphome:
  name: "${devicename}"
  platform: ESP8266
  board: modwifi

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  ap:
    ssid: "esp-${devicename}"
    password: !secret wifi_password

captive_portal:

logger:

api:

ota:

web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers:
      - !secret home_ntp
#      - time.google.com
  - platform: homeassistant

i2c:
  sda: ${pin_sda}
  scl: ${pin_scl}

sensor:
  - platform: ade7953
    voltage:
      name: ${longdevicename} napięcie
    current_a:
      name: ${longdevicename} prąd 2
      internal: true
    current_b:
      name: ${longdevicename} prąd 1
      internal: true
    active_power_a:
      name: ${longdevicename} Moc 2
      id: power_channel_2
      filters:
        - multiply: 1
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: relay1
            - switch.turn_off: relay2
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Wiadomość od ${longdevicename}
                data_template:
                  message: ${longdevicename} A pobiera za dużo mocy, ponad ${max_power}W
    active_power_b:
      name: ${longdevicename} Moc 1
      id: power_channel_1
      filters:
        - multiply: -1
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: relay1
            - switch.turn_off: relay2
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Wiadomość od ${longdevicename}
                data_template:
                  message: ${longdevicename} B pobiera za dużo mocy, ponad ${max_power}W
    update_interval: 30s
  - platform: total_daily_energy
    name: ${longdevicename} zużycie dzienne 1
    power_id: power_channel_1
    filters:
      - multiply: 0.001
    unit_of_measurement: kW
  - platform: total_daily_energy
    name: ${longdevicename} zużycie dzienne 2
    power_id: power_channel_2
    filters:
      - multiply: 0.001
    unit_of_measurement: kW
  - platform: wifi_signal
    name: "${longdevicename} WiFi Signal"
    update_interval: 300s
  - platform: uptime
    name: "${longdevicename} Uptime"
    update_interval: 300s
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${longdevicename} temperatura
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: relay1
          - switch.turn_off: relay2
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Wiadomość od ${longdevicename}
              data_template:
                message: ${longdevicename} wyłączony ponieważ temperatura maksymalna ${max_temp} została przekroczona
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

text_sensor:
  - platform: version
    name: "${longdevicename} ESPHome Version"
    internal: true
  - platform: wifi_info
    ip_address:
      name: "${longdevicename} IP Address"
      internal: true
    ssid:
      name: "${longdevicename} Connected SSID"
      internal: true
    bssid:
      name: "${longdevicename} Connected BSSID"
      internal: true

binary_sensor:
  - platform: gpio
    pin: ${pin_switch1n}
    name: "${longdevicename} Switch 1"
    internal: true
    id: switch1
  - platform: gpio
    pin: ${pin_switch2n}
    name: "${longdevicename} Switch 2"
    internal: true
    id: switch2

switch:
  - platform: gpio
    pin: ${pin_relay1}
    name: "${longdevicename} Relay 1"
    internal: true
    id: relay1
    interlock: &interlock_group [relay1, relay2]
  - platform: gpio
    pin: ${pin_relay2}
    name: "${longdevicename} Relay 2"
    internal: true
    id: relay2
    interlock: *interlock_group
  - platform: template
    id: block_control
    name: "${longdevicename} zablokuj przyciski"
    optimistic: true
  - platform: template
    name: "Move UP"
    internal: true
    lambda: |-
      if (id(switch1).state && !id(block_control).state) {
        return true;
      } else {
        return false;
      }
    on_turn_on:
      then:
        cover.open: roller
    on_turn_off:
      then:
        cover.stop: roller
  - platform: template
    name: "Move DOWN"
    internal: true
    lambda: |-
      if (id(switch2).state && !id(block_control).state) {
        return true;
      } else {
        return false;
      }
    on_turn_on:
      then:
        cover.close: roller
    on_turn_off:
      then:
        cover.stop: roller
  - platform: restart
    name: "${longdevicename} Restart"
  - platform: shutdown
    name: "${longdevicename} Shutdown"
    internal: true

cover:
  - platform: time_based
    name: "${longdevicename}"
    device_class: shutter
    id: roller
    open_action:
      - switch.turn_on: relay2
    open_duration: ${open_duration}
    close_action:
      - switch.turn_on: relay1
    close_duration: ${close_duration}
    stop_action:
      - switch.turn_off: relay1
      - switch.turn_off: relay2
```
