### ISSUE TITLE
Thermostat Climate will not set to Target Temperature below 10 C

### ISSUE THREAD

**Issue by MagnaPilot** [esphome/issues#1507]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASS.IO
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32, HELTEC HTIT-WB32 and NodeMCU 1.1

**ESPHome version (latest production, beta, dev branch)**

1.16-dev
**Affected component:**

https://next.esphome.io/components/climate/thermostat.html

**Description of problem:**

When using the Climate Thermostat in 1.16-dev.  I have been unable to set a target temperature below 10C.  I have tried directly setting the thermostat, as well as using the button logic I had planned on using.  Each time, as you'll see in the log, the thermostat acknowledges that the  setpoint has been commanded, but responds still with a 10C setting.

**Problem-relevant YAML-configuration entries:**
```yaml
binary_sensor:

  - platform: gpio
    pin: 
      number: 0
      mode: INPUT_PULLUP
    internal: true
    name: up_button
    filters:
      - delayed_on: 500ms
    on_press:
      then:
        - climate.control:
            id: refridgerator_thermostat
            mode: 'COOL'
            target_temperature: !lambda return (id(refridgerator_thermostat).target_temperature + 1.0);
        - component.update: my_display
    
  - platform: gpio
    pin: 
      number: 17
      mode: INPUT_PULLUP
    internal: true
    name: down_button
    filters:
      - delayed_on: 500ms
    on_press:
      then:
        - climate.control:
            id: refridgerator_thermostat
            mode: 'COOL'
            target_temperature: !lambda return (id(refridgerator_thermostat).target_temperature - 1.0);
        - component.update: my_display
        
  - platform: gpio
    pin: 
      number: 12
      mode: INPUT_PULLUP
    internal: true
    name: power_button
    filters:
      - delayed_on: 500ms
    on_press:
      then:
        - climate.control:
            id: refridgerator_thermostat
            mode: 'COOL'
            target_temperature: 1
        - component.update: my_display

climate:
  - platform: thermostat
    sensor: refridgerator_sensor_10k
    id: refridgerator_thermostat
    name: rv_refridgerator_thermostat
    hysteresis: 1.0
    default_target_temperature_high: 1 °C
    cool_action:
      - switch.turn_on: tankheater1
    idle_action:
      - switch.turn_off: tankheater1
```

**Logs (if applicable):**

```
[D][ntc:026]: 'Refridgerator Temperature' - Temperature: 24.9°C
[D][sensor:092]: 'Refridgerator Temperature': Sending state 24.88594 °C with 1 decimals of accuracy
[D][climate:262]: 'rv_refridgerator_thermostat' - Sending state:
[D][climate:265]:   Mode: COOL
[D][climate:267]:   Action: COOLING
[D][climate:276]:   Current Temperature: 24.89°C
[D][climate:282]:   Target Temperature: 10.00°C
[D][binary_sensor:036]: 'up_button': Sending state OFF
[D][binary_sensor:036]: 'up_button': Sending state ON
[D][climate:010]: 'rv_refridgerator_thermostat' - Setting
[D][climate:014]:   Mode: COOL
[D][climate:025]:   Target Temperature: 11.00
[D][climate:262]: 'rv_refridgerator_thermostat' - Sending state:
[D][climate:265]:   Mode: COOL
[D][climate:267]:   Action: COOLING
[D][climate:276]:   Current Temperature: 24.89°C
[D][climate:282]:   Target Temperature: 11.00°C
[D][binary_sensor:036]: 'power_button': Sending state OFF
[D][binary_sensor:036]: 'power_button': Sending state ON
[D][climate:010]: 'rv_refridgerator_thermostat' - Setting
[D][climate:014]:   Mode: COOL
[D][climate:025]:   Target Temperature: 1.00
[D][climate:262]: 'rv_refridgerator_thermostat' - Sending state:
[D][climate:265]:   Mode: COOL
[D][climate:267]:   Action: COOLING
[D][climate:276]:   Current Temperature: 24.89°C
[D][climate:282]:   Target Temperature: 10.00°C
[D][binary_sensor:036]: 'down_button': Sending state OFF
[D][binary_sensor:036]: 'down_button': Sending state ON
[D][climate:010]: 'rv_refridgerator_thermostat' - Setting
[D][climate:014]:   Mode: COOL
[D][climate:025]:   Target Temperature: 9.00
[D][climate:262]: 'rv_refridgerator_thermostat' - Sending state:
[D][climate:265]:   Mode: COOL
[D][climate:267]:   Action: COOLING
[D][climate:276]:   Current Temperature: 24.89°C
[D][climate:282]:   Target Temperature: 10.00°C


```

**Additional information and things you've tried:**

I have attempted setting both the target and target_high temperatures, no changes have been found.  Even with the default set target of 1C, the thermostat still defaults to 10C upon boot.  I have run this code on two different branded ESP32 modules.  I did not include the sensor code, but did include the button code for reference on how I was requesting the value change.  If my code is the cause of the issue, I apologize, I've spent a few hours trying to understand this issue and have had no luck on the internet finding similar problems.
