### ISSUE TITLE
PCD 8544 (Nokia 5110/3310) Display all pixels black

### ISSUE THREAD

**Issue by fr3nd** [esphome/issues#1519]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**

Version: 1.15.2

**Affected component:**

https://esphome.io/components/display/pcd8544.html

**Description of problem:**
I've connected the display to the board like this: http://acoptex.com/uploads/esp32nokia_1.jpg
Following [this tutorial](http://acoptex.com/project/1299/basics-project-072z-esp32-development-board-with-nokia-5110-graphical-lcd-module-at-acoptexcom/) the display works properly with backlight, but when trying to configure it with ESPHome, I get all the pixels in black.

However, if I disconnect the GND pin the screen shows the data properly but the backlight doesn't work.

**Problem-relevant YAML-configuration entries:**
```yaml
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

font:
  - file: 'pixelmix.ttf'
    id: font1
    size: 8

display:
  - platform: pcd8544
    cs_pin: GPIO5
    dc_pin: GPIO19
    reset_pin: GPIO14
    update_interval: 5s
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");

switch:
  - platform: gpio
    pin: 27
    name: "Nokia screen backlight"
```

**Logs (if applicable):**

Nothing relevant in the logs

**Additional information and things you've tried:**
