### ISSUE TITLE
Got data coming in HA (native API) but cannot connect to get logs

### ISSUE THREAD

**Issue by akasma74** [esphome/issues#152]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io 0.89.0

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266, Wemos D1 mini

**Affected component:**
logger

**Description of problem:**
I noticed that sometimes my HA receives data from esphome node (I can open temperature graph and it says "updated 15 seconds ago"), but command `esphome bathroom_extractor_fan_node.yaml logs` cannot connect for quite a long time:

> INFO Reading configuration...
> INFO Starting log output from 192.168.0.53 using esphome API
> INFO Connecting to 192.168.0.53:6053 (192.168.0.53)
> WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.0.53: timed out). Re-Trying in 1 seconds
> INFO Connecting to 192.168.0.53:6053 (192.168.0.53)
> WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.0.53: [Errno 64] Host is down). Re-Trying in 2 seconds
> INFO Connecting to 192.168.0.53:6053 (192.168.0.53)
> WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.0.53: [Errno 64] Host is down). Re-Trying in 4 seconds
> INFO Connecting to 192.168.0.53:6053 (192.168.0.53)
> WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.0.53: [Errno 64] Host is down). Re-Trying in 8 seconds
> INFO Connecting to 192.168.0.53:6053 (192.168.0.53)
> WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.0.53: timed out). Re-Trying in 16 seconds
> INFO Connecting to 192.168.0.53:6053 (192.168.0.53)
> WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.0.53: timed out). Re-Trying in 32 seconds
> INFO Connecting to 192.168.0.53:6053 (192.168.0.53)
> INFO Successfully connected to 192.168.0.53
> [08:01:21][I][application:097]: esphome-core version 1.12.1 compiled on Mar 20 2019, 13:38:52

and then in finally connects. The node remains Connected according to the status sensor.

Also, soon before this time I got the following in HA log:

> 2019-03-21 07:32:54 WARNING (MainThread) [homeassistant.components.esphome] Error getting initial data: Timeout while waiting for API response!
> 2019-03-21 07:37:49 WARNING (MainThread) [homeassistant.components.esphome] Error getting initial data: Timeout while waiting for API response!

I'm not saying that it happens constantly - completely the opposite, it usually connects and provides logs very quickly if the node is online (not rebooting).

But it's alarming that we have different status on different channels (data/logs).
And I have no idea what those warnings in HA log mean.

According to the status sensor , the node was unavailable at 07:32 and 07:36-37, but uptime is high. Couldn't see any significant dips on WiFi signal level graph.

**Problem-relevant YAML-configuration entries:**
```
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd
  manual_ip:
    static_ip: 192.168.0.53
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_passwd

ota:
  password: !secret ota_passwd

  - platform: status
    name: ${devicename}_status
```

**Traceback (if applicable):**
```

```

**Additional information and things you've tried:**
