### ISSUE TITLE
light.on_turn_off / light .on_turn_on firing inappropriately or binary light not working correctly

### ISSUE THREAD

**Issue by justlikeef** [esphome/issues#1526]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP12-F

**ESPHome version (latest production, beta, dev branch)**
dev

**Affected component:**
light

**Description of problem:**
If the light is on, calling turn_on with a brightness of 100% or 10% causes the locatorled to turn on

**Problem-relevant YAML-configuration entries:**
```yaml
        - light.turn_on:
            id: light1
            brightness: 100%

        - light.turn_on:
            id: light1
            brightness: 10%

light:
  - platform: binary
    name: "Locator LED"
    output: locatorledpin
    id: locatorled
    internal: true
  - platform: monochromatic
    id: light1
    output: dimmer1
    name: Dimmerized Light
    on_turn_on:
      - light.turn_off: locatorled
    on_turn_off:
      - light.turn_on: locatorled

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
[17:43:48][D][light:264]: 'Dimmerized Light' Setting:
[17:43:48][D][light:277]:   Brightness: 100%
[17:43:48][D][light:303]:   Transition Length: 1.0s
[17:43:48][D][light:264]: 'Locator LED' Setting:
[17:43:48][D][light:273]:   State: OFF
[17:43:55][D][light:264]: 'Dimmerized Light' Setting:
[17:43:55][D][light:277]:   Brightness: 10%
[17:43:55][D][light:303]:   Transition Length: 1.0s
[locatorled is turned on during the 17:43:55 logs]





**Additional information and things you've tried:**




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
