### ISSUE TITLE
Shelly 2.5 with ADE7953 getting hot (76ºC)

### ISSUE THREAD

**Issue by djwmarcx** [esphome/issues#1529]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

Shelly 2.5

**ESPHome version (latest production, beta, dev branch)**

v1.15.2

**Affected component:**

ade7953

**Description of problem:**
The device is getting hot with all configurations (including an empty one). The internal NTC is measuring 76ºC. It is also hot to the touch.

**Problem-relevant YAML-configuration entries:**
```yaml
# Basic Config
substitutions:
  devicename: shelly_25


esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
 
i2c:
  sda: GPIO12
  scl: GPIO14

    
  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${devicename} Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
    internal: true
  - platform: adc
    id: temp_analog_reading
    pin: A0
    update_interval: 30s

# ADDING THIS FIXES THE PROBLEM
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
    name: ${devicename} IRQ?

```

**Logs (if applicable):**

```


```

**Additional information and things you've tried:**

The problem seems to be that in this device the ADE7953 IRQ pin is connected to the GPIO16. The ade7953 component does not initialize this pin as an input, so it actually acts some kind of load overheating the esp chip. 

I don't' know any other devices with a similar setup. Not sure if make sense to modify the ade7953 to handle this or not.

I've tried adding a dummy binary sensor to the GPIO16 and the problem disappeared, lowering the temperature 20 degrees. However, it's a very weird solution.
