### ISSUE TITLE
RGBW color interlock

### ISSUE THREAD

**Issue by notherealmarco** [esphome/issues#1531]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
esp8266 nodemcu

**ESPHome version (latest production, beta, dev branch)**
1.15.2

**Affected component:**
RGBW Light

**Description of problem:**
The new RGBW update isn't working good for me. I used to get a variable temperature light by mixing the white (which is a warm white) with the RGB colors. With the new update, i cannot do anymore things like: white led turned on to 100% and RGB leds to 30%. The new color interlock feature isn't helpful as it doesn't allow white and rgb to be mixed together.
I had to roll back to 1.14.

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: rgbw
    name: "mrc_lampada"
    red: pin_1
    green: pin_2
    blue: pin_5
    white: pin_7
    gamma_correct: 2.8
    default_transition_length: 2s
```

**Logs (if applicable):**

```
not needed

```

**Additional information and things you've tried:**
