### ISSUE TITLE
Unexpected mqtt client behavior

### ISSUE THREAD

**Issue by Pop70** [esphome/issues#1533]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Operating system
HassOS 4.13
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 all
**ESPHome version (latest production, beta, dev branch)**

ESPHome
Current version: 1.15.2
**Affected component:**

https://esphome.io/components/mqtt.html
MQTT client

**Description of problem:**
1. Unexpected PUBLISH message when node entering deep-sleep, instead DISCONNECT message
2. Unexpected will_message in CONNECT message, instead expected birth_meesage. 

**Problem-relevant YAML-configuration entries:**
1.
```yaml

mqtt:
  broker: bla-bla-bla.ru 
  port: 1883
  username: name
  password: pass
  client_id: id
  birth_message:
#   topic: f/TEMP1/status
#   payload: "online"
  will_message:
#   topic: f/TEMP1/status
#   payload: "offline"

  discovery: false
  log_topic:
  topic_prefix: f/TEMP1

deep_sleep:
  run_duration: 10s
  sleep_duration: 6min

```
2.
```yaml
mqtt:
  broker: bla-bla-bla.ru 
  port: 1883
  username: name
  password: pass
  client_id: id
  birth_message:
   topic: f/TEMP1/status
   payload: "online"
  will_message:
#   topic: f/TEMP1/status
#   payload: "offline"

  discovery: false
  log_topic:
  topic_prefix: f/TEMP1
```
3.
```yaml
  broker: bla-bla-bla.ru 
  port: 1883
  username: name
  password: pass
  client_id: id
  birth_message:
#   topic: f/TEMP1/status
#   payload: "online"
  will_message:
   topic: f/TEMP1/status
   payload: "offline"

  discovery: false
  log_topic:
  topic_prefix: f/TEMP1
```

**Logs (if applicable):**

Server log:
1.
```
2020-10-05 12:28:24    MQTT  CONNECT  =
2020-10-05 12:28:34    MQTT  PUBLISH  f/TEMP1/status=offline

```
2.
```
2020-10-05 12:49:07    MQTT  CONNECT  =
2020-10-05 12:49:08    MQTT  PUBLISH  f/TEMP1/status=online
2020-10-05 12:49:18    MQTT  PUBLISH  f/TEMP1/status=offline
```
3.
```
2020-10-05 13:04:40    MQTT  CONNECT  f/TEMP1/status=offline
2020-10-05 13:04:50    MQTT  PUBLISH  f/TEMP1/status=offline
```
**Additional information and things you've tried:**
