### ISSUE TITLE
How to access the ESPHome boot loop counter (from a lambda)?

### ISSUE THREAD

**Issue by jant90** [esphome/issues#1539]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows 10, Python 3.8, ESPHome cli

**ESP (ESP32/ESP8266, Board/Sonoff):**

MH ET LIVE ESP32MiniKit

**ESPHome version (latest production, beta, dev branch)**

v1.15.2 Stable

**Affected component:**

Boot loop counter

**Description of problem:**
I would like to send some IR commands on boot once and do this as quickly as possible (so with a high on_boot priority). The problem I face is that during boot my ESP often fails to connect to Wi-Fi causing the ESP to reboot once or twiced when that happens the IR commands are sent again as part of the on_boot logic causing unwanted results.

Therefore I would like to check if the boot loop counter is at 0 and only then send my IR commands. If the ESP reboots after that (because of Wi-Fi connect failure) the IR commands wouldn't be sent again because the boot loop counter should now be at 1.

**Does anyone have some lambda code example on how to read the boot loop counter so I can make a lambda condition with it?**

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: irblaster
  platform: ESP32
  board: mhetesp32minikit
  on_boot:
    # Send IR power command on boot
    - priority: 600.0
      then:
        - script.execute: power_on_boot

# Configure Wi-Fi connection
wifi:
  ssid: "x"
  password: "x"

# Enable passwordless OTA updates
ota:

# Configure the local Mosquitto broker
mqtt:
  broker: 192.168.178.30
  discovery: false

# Configure the IR transmitter
remote_transmitter:
  pin: 16
  carrier_duty_percent: 50%

# Script to execute on boot
script:
  - id: power_on_boot
    then:
      - logger.log: "Executing boot script now"
      - switch.turn_on: ir_pwr

# Configure IR buttons
switch:
  - platform: template
    name: Power Button
    id: ir_pwr
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0x10EF
          command: 0x08F7
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I tried using an on_boot priority of 250 so the IR commands are sent once the Wi-Fi connection is up but this is too slow for me, especially if the first connection attempt fails and the board has to reboot.

**Comment by akomelj** [comment]
Boot loop counter is reset roughly 2 minutes after the boot - regardless of the state of Wi-fi connectivity. Default "Wi-fi unavailable" reboot timeout is 15 minutes so your system will reboot with unsuccessful boot counter already set to 0. 

Additionally, you cannot access the boot loop counter from lambda's easily because OTA component's boot loop counter methods are protected. You could probably circumvent that by accessing `ESPPreferences global_preferences` for OTA component directly but that is highly unsupported and may break at any time.

What you can do is - you can use a global variable with `restore_value` set to `true` and track Wi-fi state manually by checking `wifi.connected` condition in `on_shutdown` trigger and then act accordingly in `on_boot` trigger.

This may help - these are relevant parts from one of my configs (my smart switch enters fall-back mode after 24 hrs without Wi-fi/MQTT/internet connectivity and turns-on the dehumidifier):

```yaml
globals:
  # counts reboots due to wifi/MQTT connectivity loss
  - id: _fallback_reboots
    type: uint16_t
    restore_value: true
    initial_value: "0"
```

```yaml
  # save wi-fi state counter during reboot; we want to know whether device was rebooted
  # due to unavailability of wi-fi or due to a scheduled reboot
  on_shutdown:
    - if:
        condition:
          and:
            - wifi.connected:
            - mqtt.connected:
            - lambda: return id(sntp_time).now().is_valid();
        then:
          # reset fallback reboot counter
          - lambda: id(_fallback_reboots) = 0;
        else:
          # increase fallback reboot counter
          - lambda: id(_fallback_reboots) = id(_fallback_reboots) + 1;
    - lambda: !lambda |-
        ESP_LOGD("fallback", "Wi-fi connected: %d", id(wifi_client).is_connected());
        ESP_LOGD("fallback", "MQTT connected: %d", id(mqtt_client).is_connected());
        ESP_LOGD("fallback", "Fall-back reboot counter: %d", id(_fallback_reboots));
        _fallback_reboots->loop();   // MANDATORY: sync to RTC
```

You can then act accordingly in your `on_boot` trigger:

```yaml
  # go into fall-back mode after 96 unsuccessful Wi-fi/MQTT connects (24 hrs)
  on_boot:
    priority: -100
    then:
      - if:
          condition:
            lambda: !lambda |-
                ESP_LOGI("fallback", "Fall-back reboot counter: %d", id(_fallback_reboots));
                return id(_fallback_reboots) > ${max_fallback_reboots};
          then:
            - lambda: !lambda |-
                ESP_LOGW("fallback", "Maximum number of fall-back reboots reached. Entering fall-back mode.");

                // enter fall-back mode: disable automatic Wi-fi/MQTT reboots & access point mode
                id(_fallback_mode) = true;    // enter fallback mode
                id(wifi_client).set_reboot_timeout(0);  // disable automatic Wi-fi reboots
                id(wifi_client).set_ap_timeout(0);      // disable automatic AP mode  
                id(mqtt_client).set_reboot_timeout(0);  // disable automatic MQTT reboots

                // start dehumidifier for ${fallback_running_time} minutes
                ESP_LOGI("fallback", "Starting appliance in fall-back mode (max running time: %d minutes)", ${fallback_running_time_min});
                id(relay).turn_on();
                id(_max_running_time_min) = ${fallback_running_time_min};
```
