### ISSUE TITLE
Setting brightness on SSD1306 doesn't work

### ISSUE THREAD

**Issue by Metal-Frog** [esphome/issues#1551]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Home Assistant 0.116.2 on RasPi 3b

**Device:**
NodeMCU ESP8266 with OLED display

**ESPHome version (latest production, beta, dev branch)**
ESPHome 1.15.2 prod

**Affected component:**
https://esphome.io/components/display/ssd1306.html?highlight=ssd1306

**Description of problem:**
I try to set the display brightness but nothing happens.

**Problem-relevant YAML-configuration entries:**
```yaml
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    reset_pin: D0
    address: 0x3C
    id: SSD1306
    brightness: 0.5   #also tried 50%
```

**Logs (if applicable):**
```
nothing in logs
```

**Additional information and things you've tried:**
Also tried this in a timer:
```
      - lambda: |-
          id(SSD1306).set_brightness(0.5);
          id(SSD1306).setup();
```
Display flickers, but brightness didn't change.
Any ideas?
