### ISSUE TITLE
Error: Could not find a version that satisfies the requirement '~2.40802.191122' for your system 'freebsd_amd64'

### ISSUE THREAD

**Issue by timweld** [esphome/issues#1555]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Iam using EspHome on TrueNAS Core  RC 12.1 Community plagin
**ESP (ESP32/ESP8266, Board/Sonoff):**

Trying to compile bin for Sonoff board
**ESPHome version (latest production, beta, dev branch)**

that one https://github.com/ix-plugin-hub/iocage-plugin-index.git
**Affected component:**

**Description of problem:**
Then click Compile got that log and everything stops
INFO Reading configuration /var/db/esphome/entrance.yaml...
WARNING ESP8266: Pin 9 (9-10) might already be used by the flash interface in QUAD IO flash mode.
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /var/db/esphome/entrance
Processing entrance (board: esp01_1m; framework: arduino; platform: espressif8266@2.6.2)
--------------------------------------------------------------------------------
PackageManager: Installing toolchain-xtensa @ ~2.40802.191122
Error: Could not find a version that satisfies the requirement '~2.40802.191122' for your system 'freebsd_amd64'

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: entrance
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "xxxxx"
  password: "xxxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Entrance Fallback Hotspot"
    password: "xxxxxxx"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "123456"

ota:
  password: "123456"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff TX EU 2 Gang Touchpad 1"
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff TX EU 2 Gang Touchpad 2"
  - platform: status
    name: "Sonoff TX EU 2 Gang Status"

switch:
  - platform: gpio
    name: "Sonoff TX EU 2 Gang Relay 1"
    pin: GPIO12
  - platform: gpio
    name: "Sonoff TX EU 2 Gang Relay 2"
    pin: GPIO5
  
output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Sonoff TX EU 2 Gang Blue LED"
    output: blue_led

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
