### ISSUE TITLE
Packages not working correctly on ESP32 platform

### ISSUE THREAD

**Issue by Guyohms** [esphome/issues#1561]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 Wroom32

**ESPHome version (latest production, beta, dev branch)**

1.15.2

**Affected component:**

`packages:`
https://esphome.io/guides/configuration-types.html#packages

**Description of problem:**
ID defined inside a package does not pass the config check when you define a component of the same type later on in the main configuration file.

Everything works well on ESP8266 platform.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: arrosage_avant
  devicefriendlyname: Arrosage avant
  devicefriendlynamelower: arrosage_avant
  deviceplatform: ESP32
  deviceboard: nodemcu-32s
  devicehardware: ESP32
  devicehardwarelower: esp32

packages:
  commun: !include commun/.commun.yaml
  wifi_signal: !include commun/sensor/wifi_signal.yaml
  restart_wifi_low: !include commun/binary_sensor/restart_wifi_low.yaml
  restart: !include commun/switch/restart.yaml
```
This passes config validation.
And then I add :
```yaml
switch:
```
Now it fails to validate and I get the error : 
```
Couldn't find ID 'switch_restart'. Please check you have defined an ID with that name in your configuration.
```

The ID is defined in restart.yaml which is : 
```yaml
# restart.yaml
switch:
  platform: restart
  name: "Redémarrage ${devicefriendlyname}"   
  id: switch_restart
```

```yaml
# wifi_signal.yaml
sensor:
  platform: wifi_signal
  name: ${devicehardware} ${devicefriendlyname} status
  id: RSSI
  update_interval: 3s
  accuracy_decimals: 1
  filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 10
```

```yaml
# restart_wifi_low.yaml
binary_sensor:
  platform: template
  internal: true
  lambda: |-
    return (id(RSSI).state < -80);
  filters:
    - delayed_on: 10min
  on_press:
    - switch.turn_on: switch_restart
```

**Logs (if applicable):**

```
No logs
```

**Additional information and things you've tried:**

I added the exact same packages to an ESP8266 platform and it worked beautifully. 
So the code works and the path is good.

```yaml
substitutions:
  devicename: aquarium
  devicefriendlyname: Aquarium
  devicefriendlynamelower: aquarium
  deviceplatform: ESP8266
  deviceboard: d1_mini
  devicehardware: D1 mini
  devicehardwarelower: d1_mini

packages:
  commun: !include commun/.commun.yaml
  wifi_signal: !include commun/sensor/wifi_signal.yaml
  restart_wifi_low: !include commun/binary_sensor/restart_wifi_low.yaml
  restart: !include commun/switch/restart.yaml
...
...
```

**Comment by Guyohms** [comment]
After some more testing, it's not related only to the ESP32.

I added `binary_sensor:` to the main configuration file and it's working...

The ESP8266 device already had a `binary_sensor:` in the config so it was not giving this error.

So it seams that you have to define the component in the main configuration file even if it's defined in the package for it to validate...

**Comment by Guyohms** [comment]
After some more testing, I found what's wrong and it's my fault!

I needed to add a `-` for the elements in my packages so that creates a list that will be merged with the list in the main config file. (kinda obvious, but I got caught).

So my restart.yaml becomes this :
```yaml
# restart.yaml
switch:
  - platform: restart
    name: "Redémarrage ${devicefriendlyname}"   
    id: switch_restart
```
It's a no-issue then. Just YAML learning!

BTW I learnt in the process that if you add something like `switch:` without anything under it in the main config file, it will overwrite the packages with nothing instead of merging the package with nothing...

Validation will show this if you do so : 
````yaml
...
switch: []
...
