### ISSUE TITLE
No network access after flashing ESPHome binary

### ISSUE THREAD

**Issue by eboston** [esphome/issues#1567]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HassOS 4.14 running in VM.  
Supervisor 247
Core 0.116.4

**ESP (ESP32/ESP8266, Board/Sonoff):**

Shelly 2.5 

**ESPHome version (latest production, beta, dev branch)**

1.15.2

**Affected component:**

**Description of problem:**

Device connects to network and gets an IP address, but doesn't respond to pings or any other network access.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${SSID}
  password: ${SSID_PWD}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${Name} Fallback Hotspot"
    password: !secret WIFIpwdFallback

  manual_ip:
    static_ip: ${IP_Addr}
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

time:
  - platform: homeassistant
    id: homeassistant_time

captive_portal:

# Enable logging
#logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

```

**Logs (if applicable):**

USB Output
```
bcn 0
del if1
usl
mode : null
mode : sta(68:c6:3a:fb:78:57)
add if0
sleep disable
scandone
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 3
cnt

connected with Xxxxxx-NoT, channel 1
ip:192.168.30.36,mask:255.255.255.0,gw:192.168.1.1
ip:192.168.30.36,mask:255.255.255.0,gw:192.168.1.1
pm open,type:0 0

```
Nothing else shows up after this.

**Additional information and things you've tried:**

When I flash Tasmota to the device, to connects to the network with no issue.  Once I flash the ESPHome bin, the device stops responding.

EDIT:  Adding a WiFi Signal Sensor seems to correct the problem.  The device should work without the wifi signal sensor.
