### ISSUE TITLE
ESP32 Camera: Increased idle framerate not reflected in Home Assistant 

### ISSUE THREAD

**Issue by nalt** [esphome/issues#1570]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Ubuntu 20.04, Home Assistant 0.115.6

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP32 Cam board

**ESPHome version (latest production, beta, dev branch)** 1.15.2

**Affected component:** https://esphome.io/components/esp32_camera.html

**Description of problem:**
The camera component allows to specify the idle_framerate, which defaults to 0.1 fps. When this value is increased, the higher framerate is not reflected in Home Assistant, it still updates the idle image only once in 10s. Obviously, there are many components involved from the board to the GUI, and any of those could cause the problem.

**Problem-relevant YAML-configuration entries:**
```yaml
esp32_camera:
  # …
  name: ESP32
  resolution: 800x600
  jpeg_quality: 10
  max_framerate: 15 fps
  idle_framerate: 1.0 fps

```

**Logs (if applicable):**

```
# ESPHome logs once per second (as expected):
[13:43:47][D][esp32_camera:159]: Got Image: len=37136
# Browser logs a Websocket message once in 10s:
{"type":"auth/sign_path","path":"/api/camera_proxy/camera.esp32","id":26}
```

**Additional information and things you've tried:** Delete device, restart Home Assistant
