### ISSUE TITLE
Basic Authentication support in http_request

### ISSUE THREAD

**Issue by readylan** [esphome/issues#1576]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

~/dev/esphome2$ pip freeze
bottle==0.12.18
cayenne-mqtt==1.1.0
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
colorama==0.4.3
colorlog==4.2.1
ecdsa==0.16.0
esphome==1.15.2
esphomeflasher==1.3.0
esptool==2.8
idna==2.10
ifaddr==0.1.7
marshmallow==3.8.0
numpy==1.19.2
paho-mqtt==1.5.0
Pillow==7.2.0
pkg-resources==0.0.0
platformio==4.3.4
protobuf==3.12.2
pyaes==1.6.1
pyelftools==0.26
pyserial==3.4
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
semantic-version==2.8.5
six==1.15.0
tabulate==0.8.7
tornado==6.0.4
tzlocal==2.1
urllib3==1.25.10
voluptuous==0.11.7
wxPython==4.1.0

**ESP (ESP32/ESP8266, Board/Sonoff):**

M5_Stack Atom (ESP32)

**ESPHome version (latest production, beta, dev branch)**

esphome==1.15.2

**Affected component:**

https://esphome.io/components/http_request.html

**Description of problem:**
Hello !
I try to send sensor values to a cloud platform which needs "Authorization" header (basic)
This is the affected section in my yaml file:

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
- http_request.post:
                url: https://api.mydevices.com/things/***DEVICE_ID**/data
                headers:
                  Content-Type: application/json
                  Authorization: Basic YjZhNDg4MTAtZjcyOC0 <<<<< b64 encoded username/password >>>>>M2Q1OWJiOWM0MWY0N2U4ZWUwZDhlMmRiNjU2N2I5MTVlZmM=
                verify_ssl: false
                json: |-
                    root["channel"] = 3;
                    root["value"] = x; 
                    root["type"] = "co2"; 
                    root["unit"] = "ppm"; 
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
[21:10:47][D][sensor:092]: 'Workshop eCO2': Sending state 413.00000 ppm with 0 decimals of accuracy
[21:10:47][W][http_request:048]: HTTP Request failed; URL: https://api.mydevices.com/things/***DEVICE_ID**/data; Error: connection refused
```

**Additional information and things you've tried:**
The same data can be posted from an online utility that is sending in raw:
```
POST /things/***DEVICE_ID**/data HTTP/1.1
Authorization: Basic YjZhNDg4MTAtZjcyOC0 <<<<< b64 encoded username/password >>>>>M2Q1OWJiOWM0MWY0N2U4ZWUwZDhlMmRiNjU2N2I5MTVlZmM=
Host: api.mydevices.com
Content-Type: application/json
Content-Length: 96

[
   {
      "channel": 3,
      "value": 450.1,
      "type": "co2",
      "unit": "ppm"
   }
]
```
So, can I use basic Authentication in my use case?

Regards,

Eduardo
