### ISSUE TITLE
fastled E1.31 doesn't work with more than 340 leds

### ISSUE THREAD

**Issue by j2mc** [esphome/issues#1579]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32

**ESPHome version (latest production, beta, dev branch)**
1.15.2

**Affected component:**
fastled_clockless

**Description of problem:**
I have a single output with 399 leds, the built in effects work with all 399 however E1.31 ignores all leds over 340, which is the third universe.  All the leds in the first and second universe work great, but I'm unable to control anything in the third.  Tested with both xLights and Vixen, both show the same results.

**Problem-relevant YAML-configuration entries:**
```yaml
e131:
  method: unicast

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO4
    num_leds: 399
    rgb_order: GRB
    name: "Garage Roof"
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
      - e131:
          universe: 1
          channels: RGB

```

**Logs (if applicable):**

```
Forgot to copy the log, but when e131 is enabled it shows it attaching to universe 1, 2 and 3

```

**Additional information and things you've tried:**
