### ISSUE TITLE
Xiaomi LYWSD02 BLE reporting battery, but there is no way to get data

### ISSUE THREAD

**Issue by sermayoral** [esphome/issues#1580]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant Supervised 0.116.4 on Debian

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**

1.15.3 (latest production)

**Affected component:**

https://esphome.io/components/sensor/xiaomi_ble.html#lywsd02

**Description of problem:**

I have observed in the ESPHome log that this device is reporting battery level, but there is no information about it in the documentation.

**Problem-relevant YAML-configuration entries:**
```yaml
# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

# Especifica los sensores de temperatura a escanear
sensor:
  - platform: xiaomi_lywsd02
    mac_address: 3F:59:C8:63:38:99
    temperature:
      name: "Temperatura 4"
    humidity:
      name: "Humedad 4"
```

**Logs (if applicable):**

```
[10:59:19][D][xiaomi_ble:300]: Got Xiaomi LYWSD02 (3F:59:C8:63:38:99):
[10:59:19][D][xiaomi_ble:306]:   Humidity: 70.0%
[10:59:19][D][sensor:092]: 'Humedad 4': Sending state 70.00000 % with 1 decimals of accuracy
[10:59:33][D][xiaomi_ble:300]: Got Xiaomi LYWSD02 (3F:59:C8:63:38:99):
[10:59:33][D][xiaomi_ble:309]:   Battery Level: 26%
```

**Additional information and things you've tried:**
