### ISSUE TITLE
Excess memory consumption on v1.15 and greater

### ISSUE THREAD

**Issue by skrenes** [esphome/issues#1582]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Latest version of Debian GNU/Linux 10 (buster) hosting Docker. Latest container (v.1.15.3 at the time of report).

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU v2 (ESP8266)

**ESPHome version (latest production, beta, dev branch)**

v1.15.3

**Affected component:**

https://esphome.io/components/light/fastled.html

**Description of problem:**
I have a NodeMCU v2 connected to 9 segments of WS2812B LEDs. I simply tried to upgrade to v1.15.3 with the following error:
```
INFO Reading configuration /config/chandelabra.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/chandelabra
Processing chandelabra (board: esp01_1m; framework: arduino; platform: espressif8266@2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.7
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <FastLED> 3.3.2
|   |-- <SPI> 1.0
|   |-- <EspSoftwareSerial> 6.8.5
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Linking .pioenvs/chandelabra/firmware.elf
/root/.platformio/packages/toolchain-xtensa@2.40802.200502/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/chandelabra/firmware.elf section `.text1' will not fit in region `iram1_0_seg'
collect2: error: ld returned 1 exit status
*** [.pioenvs/chandelabra/firmware.elf] Error 1
========================== [FAILED] Took 3.23 seconds ==========================
```

I removed the build files and recompiled on all v1.15 versions without success; however going back to v1.14.5 (and prior) continues to work well:
```
INFO Reading configuration /config/chandelabra.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/chandelabra
Processing chandelabra (board: esp01_1m; framework: arduino; platform: espressif8266@2.2.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 2.20502.0 (2.5.2) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa 1.40802.0 (4.8.2)
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.6
|   |-- <ESPAsyncTCP-esphome> 1.2.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <FastLED> 3.2.9
|   |-- <EspSoftwareSerial> 5.0.4
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/chandelabra/src/main.cpp.o
src/main.cpp:156:3: warning: multi-line comment [-Wcomment]
   //   lambda: !lambda "int seconds = (id(uptime_sec).state);\nint days = seconds / (24 *\
   ^
Linking .pioenvs/chandelabra/firmware.elf
Building .pioenvs/chandelabra/firmware.bin
Retrieving maximum program size .pioenvs/chandelabra/firmware.elf
Checking size .pioenvs/chandelabra/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=====     ]  50.3% (used 41228 bytes from 81920 bytes)
Flash: [====      ]  42.5% (used 435356 bytes from 1023984 bytes)
Creating BIN file ".pioenvs/chandelabra/firmware.bin" using ".pioenvs/chandelabra/firmware.elf"
========================= [SUCCESS] Took 3.96 seconds =========================
INFO Successfully compiled program.
```

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  device_name: chandelabra
  device_name_pretty: Chandelabra

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  comment: ESP8266 with 9 strings of WS2812B LEDs
  on_boot:
    then:
      - light.turn_off:
          id: light_1

<<: !include .config.yaml

light:
  - platform: partition
    name: ${device_name_pretty} Light
    id: light_1
    color_correct: [70%, 70%, 70%]
    segments:
      - id: string1
        from: 12
        to: 18
      - id: string2
        from: 12
        to: 18
      - id: string3
        from: 12
        to: 18
      - id: string4
        from: 12
        to: 18
      - id: string5
        from: 12
        to: 18
      - id: string6
        from: 12
        to: 18
      - id: string7
        from: 12
        to: 18
      - id: string8
        from: 12
        to: 18
      - id: string9
        from: 12
        to: 18
    effects:
      - addressable_rainbow:
          name: Rainbow
          speed: 10
          width: 19

  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: 2
    num_leds: 19
    id: string1
  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: 12
    num_leds: 19
    id: string2
  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: 3
    num_leds: 19
    id: string3
  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: 5
    num_leds: 19
    id: string4
  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: 0
    num_leds: 19
    id: string5
  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: 14
    num_leds: 19
    id: string6
  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: 13
    num_leds: 19
    id: string7
  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: 15
    num_leds: 19
    id: string8
  - platform: fastled_clockless
    chipset: WS2812B
    rgb_order: GRB
    pin: 4
    num_leds: 19
    id: string9

```

**Logs (if applicable):**

Not applicable. Cannot compile.

**Additional information and things you've tried:**
In case you wonder why I'm only using the last 7 LEDs of each string, it's because each string is a double ring and the outside ring (the first 12 LEDs) were all manufactured to subpar standards and have had serious issues (likely due to overheating during assembly). This configuration has worked well for over a year and has nothing to do with the reported bug.
