### ISSUE TITLE
Climate or transmitter broken in 1.15.3

### ISSUE THREAD

**Issue by ppd13** [esphome/issues#1595]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio in Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**
D1 mini Esp8266

**ESPHome version (latest production, beta, dev branch)**
ESPHome version v1.15.3

**Affected component:**
climate or transmitter

**Description of problem:**
I was running 1.15.2 and was working fine. Since i upgraded to 1.15.3 cant control aircon anymore. When revert back to 1.15.2 it works again. Not sure if climate or transmitter module is broken in this version

**Problem-relevant YAML-configuration entries:**
```yaml
remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

climate:
  - platform: daikin
    name: "gbr aircon"
    supports_heat: False

```

**Logs (if applicable):**

```
[08:19:55][D][climate:262]: 'mbr aircon' - Sending state:
[08:19:55][D][climate:265]:   Mode: OFF
[08:19:55][D][climate:270]:   Fan Mode: AUTO
[08:19:55][D][climate:273]:   Swing Mode: OFF
[08:19:55][D][climate:282]:   Target Temperature: 27.00°C

```

**Additional information and things you've tried:**
version changes
