### ISSUE TITLE
ESP32 BLE Tracker Unstable

### ISSUE THREAD

**Issue by ioudeveldhuis** [esphome/issues#16]
**Operating environment (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266/Board/Sonoff):**
ESP32

**Affected component:**
N/A

**Description of problem:**
When compiling the yaml below from the ESPHome Dashboard, the process stops with : Terminated process. 
No firmware can be downloaded after this.

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: crazylongname
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: 'obnoxiousssid'
  password: 'totallyobviouspassword'
  id: my_wifi

esp32_ble_tracker:
  scan_interval: 300s

binary_sensor:
```

**Traceback (if applicable):**
N/A

**Additional information:**
https://imgur.com/a/38SHZ3Y
