### ISSUE TITLE
MCP23017 problems

### ISSUE THREAD

**Issue by ddean6232** [esphome/issues#160]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASSIO
**ESP (ESP32/ESP8266, Board/Sonoff):**

WEMOS DI MINI
**Affected component:**

https://esphome.io/components/mcp23017.html?highlight=mcp23017

**Description of problem:**
Cannot get MCP23017 to operate as per instructions.  I have tested the module with the manufacture instructions on an Arduino Uno and it works as documented.  I have attached the manf. instructions to this issue for you ref.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: tempnode
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'xxxx'
  password: 'xxxx'

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# I2C INTERFACE
i2c:
  sda: D2
  scl: D1
  scan: False
  frequency: 400kHz

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x27

# Individual outputs
switch:
  - platform: gpio
    name: "MCP23017 Pin #0"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 0
      number: 0
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
      inverted: False

**Traceback (if applicable):**
<!--
Please copy the traceback here if compilation is failing. If possible, also connect to the ESP over USB and copy its logs into the backticks.
-->
```

```

**Additional information and things you've tried:**

Arduino Uno and manf. instructions and code
[MCP2307_IO_Expansion_Board_User_Manual_EN.pdf](https://github.com/esphome/issues/files/2999014/MCP2307_IO_Expansion_Board_User_Manual_EN.pdf)
[MCP23017-Datasheet.pdf](https://github.com/esphome/issues/files/2999015/MCP23017-Datasheet.pdf)




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
