### ISSUE TITLE
ESPHome fails generating code for just more than 20 sensors.

### ISSUE THREAD

**Issue by ogry** [esphome/issues#1605]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows 10/PIP install

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 Developer board
(https://www.aliexpress.com/item/32842941195.html)

**ESPHome version (latest production, beta, dev branch)**

ESPHome v1.15.3 (may be Dev version, but is what gets with a simple 'pip install esphome')

**Affected component:**

Not sure, as it seems to be something related to generation proces.
https://esphome.io/components/sensor/index.html

**Description of problem:**
Error compiling from a yaml file with more than 20 sensors defined.

There is the full YAML file: https://pastebin.com/SW4sViCu

There are 155 rfreceiver sensors very simple, mostly like this one:
**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
binary_sensor:
  - id: botonmandoa01
    platform: remote_receiver
    name: 'Boton MandoA01'
    filters:
      - delayed_off: 250ms
    rc_switch_raw: 
      code: '010111000101000011000000'
    on_press:
     then:
       - switch.toggle: luz_oeste
       - delay: 20s
       - switch.turn_off: luz_oeste
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
Archiving .pioenvs\testel32\libFrameworkArduino.a
src\main.cpp: In function 'void setup()':
src\main.cpp:802:6: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
 void setup() {
      ^
Linking .pioenvs\testel32\firmware.elf
Retrieving maximum program size .pioenvs\testel32\firmware.elf
Building .pioenvs\testel32\firmware.bin
Checking size .pioenvs\testel32\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  14.1% (used 46208 bytes from 327680 bytes)
Flash: [======    ]  60.2% (used 1104118 bytes from 1835008 bytes)
esptool.py v2.6
================================================= [SUCCESS] Took 48.53 seconds =================================================
�[32mINFO Successfully compiled program.�[0m

```

**Additional information and things you've tried:**
Cutting of the YAML to exactly 20 sensors, all works again.
