### ISSUE TITLE
H801 Red not working

### ISSUE THREAD

**Issue by zachsteffens** [esphome/issues#1606]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant - Docker: v 0.115.4

**ESPHome version (latest production, beta, dev branch)**
ESPHome 1.15.3 (Docker)

**Affected component:**

H801(https://esphome.io/cookbook/h801.html)

**Description of problem:**
Cant get the leds to turn red. Blue works flawlessly, green is close, red is non existent. selecting red from the HA color wheel displays a pale yellow.

I have the normal style led strip (in the order of "+ G R B W" So i dont believe it's an issue with switching the GPIO pin numbers

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: kitchen_counter_leds_v2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "SSID"
  password: "PW"
  manual_ip:
    static_ip: IP
    gateway: 192.168.1.1
    subnet: 255.255.255.0

logger:
api:
ota:
sensor:
  - platform: wifi_signal
    name: "WiFi Signal h801KitchenCounterlight"
    update_interval: 60s
#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w
light:
  - platform: rgbw
    name: "H801 KitchenCounter Light"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w


```

**Logs (if applicable):**

```

```

**Additional information and things you've tried:**
I've swapped out for a spare h801 and have the same issue.
