### ISSUE TITLE
Logger is broken in 1.16.0-dev

### ISSUE THREAD

**Issue by Anonym-tsk** [esphome/issues#1609]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, ESP32 (Wemos D1 Mini, Sonoff Basic, NodeMCU v3, Wroom ESP32 and others)

**ESPHome version (latest production, beta, dev branch)**

1.16.0-dev

**Affected component:**

logger

**Description of problem:**
There are no logs in dashboard.
```
INFO Reading configuration /config/co2mon.yaml...
INFO Starting log output from co2mon.local using esphome API
INFO Connecting to co2mon.local:6053 (192.168.0.18)
INFO Successfully connected to co2mon.local
```

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: co2mon
  platform: ESP8266
  board: d1_mini
  comment: Masterkit MT8057

sensor:
  - platform: zyaura
    clock_pin: D1
    data_pin: D2
    co2:
      name: "CO2Mon CO2"
      id: co2ppm
    temperature:
      name: "CO2Mon Temperature"
      id: temperature
    update_interval: 20s

status_led:
  pin:
    number: D4
    inverted: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  ap:
    ssid: "CO2mon"
    password: "1234567890"

logger:

api:
  password: "esphome"
  reboot_timeout: 0s

ota:
  password: "esphome"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Sometimes i can see log after few minutes. But very rare.
