### ISSUE TITLE
Help understanding what went wrong updating to latest version

### ISSUE THREAD

**Issue by tatunts** [esphome/issues#162]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, Sonoff Basic

**Affected component:**

Sensor template

**Description of problem:**

Hello everyone. Sorry to bother again but I've been wondering what I could have done to broke a few sonoffs basics that are not able to connect back to the wifi network after updating to version 1.12 using the exact same yaml files to compile and flash OTA. Those devices were working perfeclty, no issues at all, after an OTA flash the led keeps flashing, I can see they are trying to connect to my router (Asus RT-AC68U) with incorrect values of transfer rate, lease time and so on, after a few seconds they simply disconnect.

After dozens os tries, even erasing the flash memory, I've noticed that if I take this template sensor out and flashing using cables, those devices return immediately. I don't get it how they were working just fine before the update and also why all my other 20+ sonoffs that was updated using the exact same method came back working flawlessly.

I've flashed 40 devices (including D1 mini, Sonoff Dual, 4CH but mostly Basics) using that template sensor and only 5 of them (all basics) broke.

This template sensor is used to calculate the RSSI quality in percentage using a non-linear formula.

Thanks!

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: ${project_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: ${wifi_ssid}
    password: ${wifi_psw}
  - ssid: Backup
    password: ${wifi_psw}
  ap:
    ssid: ${friendly_name}
    password: ${ap_psw}
    channel: 6

logger:

web_server:

api:
  password: ${api_psw}

ota:

binary_sensor:

## Buton 00

  - platform: gpio
    id: button_01
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 600ms
      - delayed_off: 600ms
    on_state:
      then:
        - switch.toggle: main_switch

output:
  - platform: gpio
    pin: GPIO12
    id: main_relay

switch:
  - platform: output
    name: ${switch_entity_id}
    id: main_switch
    output: main_relay
    icon: ${switch_icon}

sensor:
  - platform: wifi_signal
    id: wifi_rssi
    update_interval: 60s

  - platform: template
    name: ${friendly_name} - Sinal Wifi
    unit_of_measurement: '%'
    accuracy_decimals: 0
    update_interval: 60s
    icon: "mdi:wifi"
    lambda: |-
        if (id(wifi_rssi).state < -92.0)
          return 100.0;
        if (id(wifi_rssi).state > -21.0)
          return 1.0;
        else
          return round(( -0.0154 * id(wifi_rssi).state * id(wifi_rssi).state ) - ( 0.3794 * id(wifi_rssi).state ) + 98.182 );

status_led:
  pin:
    number: GPIO13
    inverted: true
```

**Traceback (if applicable):**

```
[32mINFO Reading configuration...[0m
[32mINFO Generating C++ source...[0m
[32mINFO Compiling app...[0m
[32mINFO Running:  platformio run -d casa_sonoffbasic_ventilador_casa[0m
Processing casa_sonoffbasic_ventilador_casa (platform: espressif8266@1.8.0; framework: arduino; board: esp01_1m)
-----------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz 80KB RAM (1MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 29 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP Async WebServer> 1.1.1
|   |-- <ESPAsyncTCP> 1.2.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.1.3
|   |-- <ESP8266WiFi> 1.0
|-- <Hash> 1.0
|-- <esphome-core> 1.12.1
|   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESPAsyncTCP> 1.2.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP Async WebServer> 1.1.1
|   |   |-- <ESPAsyncTCP> 1.2.0
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <Hash> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> 1.0
Retrieving maximum program size .pioenvs\casa_sonoffbasic_ventilador_casa\firmware.elf
Checking size .pioenvs\casa_sonoffbasic_ventilador_casa\firmware.elf
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [====      ]  42.3% (used 34656 bytes from 81920 bytes)
PROGRAM: [====      ]  36.9% (used 377976 bytes from 1023984 bytes)
============================================= [SUCCESS] Took 4.04 seconds =============================================
```

**Additional information and things you've tried:**

Flashed many times OTA/cables and erased flash memory using ESPTOOL.

Also, I've noticed that all devices broken were using a `switch` component, all others uses `light`, only to show the correct domain entity on HA. The same output gpio method are used on both templates, I just don't understand why removing the template sensor makes it works again.

I've tried arduino core 2.5 but the device does not connect to wifi neither shows the AP to connect to.

Also, compiling using `esphome_core_version: 1.11.2` with the same config file works just fine. I believe there is something with version `1.12` using this config with a `switch` component alongside that code of `template sensor` .

**Comment by tatunts** [comment]
I am not sure if this is related but I am now struggling to compile some firmwares using similar templates and method:

```yaml
esphome:
  name: ${project_name}
  platform: ESP8266
  board: esp01_1m
  esphome_core_version: 1.11.2

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_psw}
  fast_connect: true
  ap:
    ssid: ${friendly_name}
    password: ${ap_psw}

logger:

web_server:

api:
  password: ${api_psw}

ota:

binary_sensor:

## Buton 00

  - platform: gpio
    id: button_00
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - switch.toggle: main_switch

output:
  - platform: gpio
    pin: GPIO12
    id: main_relay

switch:
  - platform: output
    name: ${switch_entity_id}
    id: main_switch
    output: main_relay
    icon: ${switch_icon}

sensor:
  - platform: wifi_signal
    id: wifi
    update_interval: 60s

  - platform: template
    name: ${friendly_name} - Sinal Wifi
    unit_of_measurement: '%'
    accuracy_decimals: 0
    icon: "mdi:wifi"
    lambda: |-
        if (id(wifi).state < -92.0)
          return 100.0;
        if (id(wifi).state > -21.0)
          return 1.0;
        else
          return round(( -0.0154 * id(wifi).state * id(wifi).state ) - ( 0.3794 * id(wifi).state ) + 98.182 );

status_led:
  pin:
    number: GPIO13
    inverted: true
```

The error does not shows up if this part is removed:

```yaml
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - switch.toggle: main_switch
```

Here is a video showing the behavior: https://photos.app.goo.gl/PXvXLdnikqspxdzm8

This is the error log:

```
[32mINFO Reading configuration...[0m
[32mINFO Generating C++ source...[0m
[32mINFO Core config or version changed, cleaning build files...[0m
[32mINFO Deleting casa_sonoffbasic_chuveiro_social\.pioenvs[0m
[32mINFO Deleting casa_sonoffbasic_chuveiro_social\.piolibdeps[0m
[32mINFO Compiling app...[0m
[32mINFO Running:  platformio run -d casa_sonoffbasic_chuveiro_social[0m
Processing casa_sonoffbasic_chuveiro_social (platform: espressif8266@1.8.0; framework: arduino; board: esp01_1m)
---------------------------------------------------------------------------------------------
LibraryManager: Installing id=306 @ 1.1.1
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=305
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=1826
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=305 @ 1.1.3
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing v1.11.2
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=3837 @ 5.13.3
Downloading...
Unpacking  [####################################]  100%
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz 80KB RAM (1MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 29 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP Async WebServer> 1.1.1
|   |-- <ESPAsyncTCP> 1.2.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.1.3
|   |-- <ESP8266WiFi> 1.0
|-- <Hash> 1.0
|-- <esphome-core> 1.11.2
|   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <ESPAsyncTCP> 1.2.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP Async WebServer> 1.1.1
|   |   |-- <ESPAsyncTCP> 1.2.0
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <Hash> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\src\main.cpp.o
Generating LD script .pioenvs\casa_sonoffbasic_chuveiro_social\ld\eagle.app.v6.common.ld
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\BearSSLHelpers.cpp.o
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\CertStoreBearSSL.cpp.o
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\ESP8266WiFi.cpp.o
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\ESP8266WiFiAP.cpp.o
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\ESP8266WiFiGeneric.cpp.o
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\ESP8266WiFiMulti.cpp.o
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\ESP8266WiFiScan.cpp.o
src\main.cpp: In function 'void setup()':
src\main.cpp:59:14: error: wrong number of template arguments (0, should be 1)
Automation<> *automation = App.make_automation<>(binary_sensor_multiclicktrigger);
^
In file included from .piolibdeps\esphome-core\src/esphome/binary_sensor/binary_sensor.h:10:0,
from .piolibdeps\esphome-core\src/esphome/controller.h:4,
from .piolibdeps\esphome-core\src/esphome/api/api_server.h:9,
from .piolibdeps\esphome-core\src/esphome/application.h:6,
from .piolibdeps\esphome-core\src/esphome.h:1,
from src\main.cpp:3:
.piolibdeps\esphome-core\src/esphome/automation.h:64:7: error: provided for 'template<class T> class esphome::Automation'
class Automation;
^
src\main.cpp:59:28: error: invalid type in declaration before '=' token
Automation<> *automation = App.make_automation<>(binary_sensor_multiclicktrigger);
^
src\main.cpp:59:83: error: cannot convert 'esphome::Automation<bool>*' to 'int*' in initialization
Automation<> *automation = App.make_automation<>(binary_sensor_multiclicktrigger);
^
src\main.cpp:60:25: error: wrong number of template arguments (0, should be 1)
switch_::ToggleAction<> *action = main_switch->make_toggle_action<>();
^
In file included from .piolibdeps\esphome-core\src/esphome/controller.h:8:0,
from .piolibdeps\esphome-core\src/esphome/api/api_server.h:9,
from .piolibdeps\esphome-core\src/esphome/application.h:6,
from .piolibdeps\esphome-core\src/esphome.h:1,
from src\main.cpp:3:
.piolibdeps\esphome-core\src/esphome/switch_/switch.h:17:7: error: provided for 'template<class T> class esphome::switch_::ToggleAction'
class ToggleAction;
^
src\main.cpp:60:35: error: invalid type in declaration before '=' token
switch_::ToggleAction<> *action = main_switch->make_toggle_action<>();
^
src\main.cpp:60:71: error: no matching function for call to 'esphome::switch_::OutputSwitch::make_toggle_action()'
switch_::ToggleAction<> *action = main_switch->make_toggle_action<>();
^
src\main.cpp:60:71: note: candidate is:
In file included from .piolibdeps\esphome-core\src/esphome/controller.h:8:0,
from .piolibdeps\esphome-core\src/esphome/api/api_server.h:9,
from .piolibdeps\esphome-core\src/esphome/application.h:6,
from .piolibdeps\esphome-core\src/esphome.h:1,
from src\main.cpp:3:
.piolibdeps\esphome-core\src/esphome/switch_/switch.h:106:20: note: template<class T> esphome::switch_::ToggleAction<T>* esphome::switch_::Switch::make_toggle_action()
ToggleAction<T> *make_toggle_action();
^
.piolibdeps\esphome-core\src/esphome/switch_/switch.h:106:20: note:   template argument deduction/substitution failed:
src\main.cpp:60:71: note:   couldn't deduce template parameter 'T'
switch_::ToggleAction<> *action = main_switch->make_toggle_action<>();
^
src\main.cpp:61:15: error: request for member 'add_actions' in '* automation', which is of non-class type 'int'
automation->add_actions({action});
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\WiFiClient.cpp.o^

Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\WiFiClientSecureAxTLS.cpp.o
Compiling .pioenvs\casa_sonoffbasic_chuveiro_social\libac1\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
*** [.pioenvs\casa_sonoffbasic_chuveiro_social\src\main.cpp.o] Error 1
================================ [ERROR] Took 17.93 seconds ================================
```

Thanks.

**Comment by RomanWojnar** [comment]
I have a very similar problem.
Sonoff Basic after adding code:

`text_sensor:
   - platform: wifi_info
     ip_address:
       name: Wemos ESP IP Address
     ssid:
       name: Wemos ESP Connected SSID`


Sonoff Basic does not connect to WiFi.
Sonoff S26 is not the problem.

**Comment by OttoWinter** [comment]
>   esphome_core_version: 1.11.2

Your core and esphome versions need to be in sync. You also need to install v1.11.2 of the python tool to get it to compile.

> using this config with a switch component alongside that code of template sensor .

very unlikely, I believe it is just random - esphome is a highly modularized system, components can *crash* the system (resulting in a stacktrace), but not affect things like wifi.

For me to help with this issue the compile logs will not help - they're basically useless to me. I will need logs over USB and preferable verbose log setting.

@RomanWojnar 
WiFi Info has been fixed in 1.12.1 - that's a separate issue.

**Comment by RomanWojnar** [comment]
@OttoWinter 

tatunts napsal:

> **Operating environment/Installation (Hass.io/Docker/pip/etc.):**
> 
> **ESP (ESP32/ESP8266, Board/Sonoff):**
> 
> ESP8266, Sonoff Basic
> 
> **Affected component:**
> 
> Sensor template
> 
> **Description of problem:**
> 
> Hello everyone. Sorry to bother again but I've been wondering what I could have done to broke a few sonoffs basics that are not able to connect back to the wifi network after updating to version 1.12 using the exact same yaml files to compile and flash OTA. Those devices were working perfeclty, no issues at all, after an OTA flash the led keeps flashing, I can see they are trying to connect to my router (Asus RT-AC68U) with incorrect values of transfer rate, lease time and so on, after a few seconds they simply disconnect.
> 

and that's exactly what happens to me.
Only Sonoff Basic, Sonoff S26 is OK.
I just added this code:
```text_sensor:
  - platform: wifi_info
    ip_address:
      name: Sonoff ESP IP Address
    ssid:
      name: Sonoff ESP Connected SSID
```
ESPHome  version 1.12.1

**Comment by tatunts** [comment]
Hello again.

I was trying to get a valid log data from the USB connection but with the Sonoff Basic it is impossible since when the pins are disconnected or if I reset the device by disconnecting the USB after flashing, the connection gets cut.

Since I need this device up and running, I've removed it from where it was, connected over USB, erased the flash using ESPTool and re-flashed with the `1.12.1` version with no luck. Same behavior as before. Then I've once again erased the flash memory and flashed with a backup that I had with the previous working version (`1.11.2`) and it worked flawlessly, exact same yaml file, exact flashing method but with previous core version.

I really think there is something that have changed with the latest release, unfortunately.

For now I will try to restore the other devices with the previous version and see how it goes.

I wonder if there is a plan of releasing a new version soon? I would like to try again and see if it happens again.

Thanks!

**Comment by tatunts** [comment]
Another problematic code:

```yaml
esphome:
  name: ${project_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_psw}
  fast_connect: true
  ap:
    ssid: ${friendly_name}
    password: ${ap_psw}

logger:

web_server:

api:
  password: ${api_psw}

ota:

binary_sensor:

## Buton 00

  - platform: gpio
    id: button_00
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - light.toggle: main_light
      - timing:
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - text_sensor.template.publish:
              id: buttons
              state: "button_pressed"
          - delay: 50ms
          - text_sensor.template.publish:
              id: buttons
              state: "button_00_double"
      - timing:
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - text_sensor.template.publish:
              id: buttons
              state: "button_pressed"
          - delay: 50ms
          - text_sensor.template.publish:
              id: buttons
              state: "button_00_triple"
      - timing:
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - text_sensor.template.publish:
              id: buttons
              state: "button_pressed"
          - delay: 50ms
          - text_sensor.template.publish:
              id: buttons
              state: "button_00_quadruple"
      - timing:
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - text_sensor.template.publish:
              id: buttons
              state: "button_pressed"
          - delay: 50ms
          - text_sensor.template.publish:
              id: buttons
              state: "button_00_many"
      - timing:
          - ON for at least 2s
        then:
          - text_sensor.template.publish:
              id: buttons
              state: "button_pressed"
          - delay: 50ms
          - text_sensor.template.publish:
              id: buttons
              state: "button_00_long"

output:
  - platform: gpio
    pin: GPIO12
    id: main_relay

light:
  - platform: binary
    name: ${light_entity_id}
    id: main_light
    output: main_relay

sensor:
  - platform: wifi_signal
    id: wifi
    update_interval: 60s

  - platform: template
    name: ${friendly_name} - Sinal Wifi
    unit_of_measurement: '%'
    accuracy_decimals: 0
    icon: "mdi:wifi"
    lambda: |-
        if (id(wifi).state < -92.0)
          return 100.0;
        if (id(wifi).state > -21.0)
          return 1.0;
        else
          return round(( -0.0154 * id(wifi).state * id(wifi).state ) - ( 0.3794 * id(wifi).state ) + 98.182 );

text_sensor:
  - platform: template
    name: ${friendly_name} - Interruptores
    id: buttons
    icon: mdi:light-switch

status_led:
  pin:
    number: GPIO13
    inverted: true
```

If I take this part off, the Sonoff Basic does not connect to the network and becomes unavailable:

```yaml
  - platform: gpio
    id: button_00
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - light.toggle: main_light
      - timing:
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - text_sensor.template.publish:
              id: buttons
              state: "button_pressed"
          - delay: 50ms
          - text_sensor.template.publish:
              id: buttons
              state: "button_00_double"
      - timing:
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - text_sensor.template.publish:
              id: buttons
              state: "button_pressed"
          - delay: 50ms
          - text_sensor.template.publish:
              id: buttons
              state: "button_00_triple"
      - timing:
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - text_sensor.template.publish:
              id: buttons
              state: "button_pressed"
          - delay: 50ms
          - text_sensor.template.publish:
              id: buttons
              state: "button_00_quadruple"
      - timing:
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at most 399ms
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - text_sensor.template.publish:
              id: buttons
              state: "button_pressed"
          - delay: 50ms
          - text_sensor.template.publish:
              id: buttons
              state: "button_00_many"
      - timing:
          - ON for at least 2s
        then:
          - text_sensor.template.publish:
              id: buttons
              state: "button_pressed"
          - delay: 50ms
          - text_sensor.template.publish:
              id: buttons
              state: "button_00_long"
```

Very strange, indeed.

Thanks.

**Comment by tatunts** [comment]
Hello.

Unfortunately, the problem was not solved with the latest update.

It seems that the problem revolves around the device type, as being most complains of people (like me) running ESPHome on Sonoff Basics, like this: https://github.com/esphome/issues/issues/163#issuecomment-482100334

I've flashed yesterday another Sonoff basic that was not able to connect to wifi after a update and the problem persisted after re-flashing with the latest version. The solution was removing the `binary_sensor` component. Here is the code used:

```yaml
esphome:
  name: ${project_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_psw}
  fast_connect: false
  ap:
    ssid: ${friendly_name}
    password: ${ap_psw}

logger:

web_server:

api:
  password: ${api_psw}

ota:

binary_sensor:

## Buton 00

  - platform: gpio
    id: button_00
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 400ms
        then:
          - switch.toggle: main_switch

output:
  - platform: gpio
    pin: GPIO12
    id: main_relay

switch:
  - platform: output
    name: ${switch_entity_id}
    id: main_switch
    output: main_relay
    icon: ${switch_icon}

sensor:
  - platform: wifi_signal
    id: wifi
    update_interval: 60s

  - platform: template
    name: ${friendly_name} - Sinal Wifi
    unit_of_measurement: '%'
    accuracy_decimals: 0
    icon: "mdi:wifi"
    lambda: |-
        if (id(wifi).state < -92.0)
          return 100.0;
        if (id(wifi).state > -21.0)
          return 1.0;
        else
          return round(( -0.0154 * id(wifi).state * id(wifi).state ) - ( 0.3794 * id(wifi).state ) + 98.182 );

status_led:
  pin:
    number: GPIO13
    inverted: true
```

Everything worked perfectly after the first flash then broke down after the update...

Thanks!
