### ISSUE TITLE
Calling servo.detach once on ESP32 renders further commands effectless - is this intended?

### ISSUE THREAD

**Issue by RAYs3T** [esphome/issues#1620]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant on ProxMox

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 D1 mini

**ESPHome version (latest production, beta, dev branch)**

v1.15.3 (via Home Assistant)

**Affected component:**

https://esphome.io/components/servo.html

**Description of problem:**
So the idea is to detach the servo once the movement is done to avoid permanent micro adjustments.
Once you call `detach` on a servo, further commands can no longer control the servo.

Is this intended behavior? My expectation would be that the next time you call the `servo.write` it would attach again.

**Problem-relevant YAML-configuration entries:**
```yaml
      then:
        - logger.log: "Start servo change"
        - servo.write:
            id: ob_tilt
            level: !lambda 'return level / 100.0;'
        - delay: 2s
        - logger.log: "Done"
        - servo.detach: ob_tilt
        - logger.log: "Detached"

```

**Logs (if applicable):**

```

```

**Additional information and things you've tried:**
Once you remove the `detach` all further calls work fine.
