### ISSUE TITLE
MQTT broker unavailable causes esphome to be unresponsive

### ISSUE THREAD

**Issue by lancelon** [esphome/issues#1627]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Mac OS X pip3
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32-POE
**ESPHome version (latest production, beta, dev branch)**

1.15.3
**Affected component:**

Core/Wizard

This is a node I've successfully connected to a Home Assistant instance at work. I moved it home and it was duly 'discovered' as an integration. I tried to connect it to my home HA instance and got "Can't connect to ESP. Please make sure your YAML file contains an 'api:' line.". Weird, as it worked at work. I thought maybe there might be some hard link going on between the work HA instance which was preventing a second/replacement connection from working so I ran `esphome traffic.yaml run` from home and the firmware was duly (and successfully) uploaded OTA to 192.168.0.117, however, after that HA was unable to connect on traffic.local:6053 (192.168.0.117). The HA Front end reports the same error as before ("Can't connect to ESP. Please make sure your YAML file contains an 'api:' line."). 

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: traffic
  platform: ESP32
  board: esp32-poe

mqtt:
  broker: 192.168.2.30
  client_id: TrafficLight
  topic_prefix: Traffic
  will_message:
    topic: traffic/avail
    payload: offline
  on_message:
    - topic: traffic/green/on
      then:
        - switch.turn_on: relay2
    - topic: traffic/green/off
      then:
        - switch.turn_off: relay2


logger:


api:
  password: "x"

ota:
  password: "x"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

switch:
  - platform: gpio
    name: "Relay1"
    pin: 0
    id: relay1
    interlock: [relay2]
  - platform: gpio
    name: "Relay2"
    id: relay2
    pin: 1
    interlock: [relay1]


```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

Eventually I figured out the problem! The MQTT broker at work is at 192.168.2.30 and the one at home is at 192.168.0.110. Once I made the change, the API connection etc work fine
