### ISSUE TITLE
OTA Safe Mode with Captive Portal

### ISSUE THREAD

**Issue by alexyao2015** [esphome/issues#1629]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU ESP8266
**ESPHome version (latest production, beta, dev branch)**

v1.15.3
**Affected component:**

[OTA](https://esphome.io/components/ota.html)

**Description of problem:**
When both the wifi network is unable to be connected to and if there is an issue causing a boot loop, safe mode is effectively rendered useless as there is not enough time to connect to the ap and reconfigure wifi credentials to try OTA. 

This is because there is a period of time before ESPHome will start the fallback AP. Under the default settings, there is one minute before the fallback ap will start and two minutes before the OTA safe mode will force a reboot. This means the user will have just one minute to find the ap and enter the wifi credentials or upload a new firmware, making it almost impossible to reclaim the device.

Potential solution:
Change the default enable time to 4-5 minutes and allow for a customizable ota enable time. 

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test
  platform: ESP8266
  board: esp12e
  
wifi:
  ssid: "wrong ssid"
  password: "wrongpassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"

captive_portal:
logger:
    
# Enable Home Assistant API
api:

ota:
```

**Logs (if applicable):**

```
Bootloop was done forcibly through the use of the RST button. 

[22:27:56][E][ota:371]: Boot loop detected. Proceeding to safe mode.
[22:27:56][I][app:029]: Running through setup()...
...
[22:28:41][D][wifi:324]: Starting scan...
[22:28:47][W][wifi:394]: No matching network found!
...
[22:28:56][I][wifi:116]: Starting fallback AP!
...
[22:29:56][E][ota:375]: No OTA attempt made, restarting.
[22:29:56][I][app:132]: Forcing a reboot...
```

**Additional information and things you've tried:**
Relevant code:
https://github.com/esphome/esphome/blob/b493d5bba5d41d1c22b54efd4174bea6140fc177/esphome/components/ota/ota_component.cpp#L361
https://github.com/esphome/esphome/blob/b493d5bba5d41d1c22b54efd4174bea6140fc177/esphome/components/ota/ota_component.h#L50
