### ISSUE TITLE
After upgrade to 1.21.1 Sonoff Touch cannot connect to Wi-Fi and becomes unstable

### ISSUE THREAD

**Issue by davidvidmar** [esphome/issues#163]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASS.IO

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff Touch

**Description of problem:**

After uploading a new version of firmware with version 1.12.1 the switch will not connect to Wifi. Status LED keeps blinking. After a while switch might or might now freeze - touch button stops responding, LED is not blinking and switch is not connected to wifi.

**Problem-relevant YAML-configuration entries:**
```
esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass  
  power_save_mode: light
  fast_connect: true  
  manual_ip:
    static_ip: 192.168.xx.yy
    gateway: 192.168.xx.1
    subnet: 255.255.255.0   

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

# Status sensors

sensor:    
  - platform: wifi_signal
    name: "ESPHome $upper_devicename WiFi Signal"
    update_interval: 10s    
  - platform: uptime
    name: "ESPHome $upper_devicename Uptime"

text_sensor:    
  - platform: version
    name: "ESPHome $upper_devicename Version"

switch:
  - platform: restart
    name: "ESPHome $upper_devicename Restart"

binary_sensor:
  - platform: status
    name: "ESPHome $upper_devicename Status"

# https://esphome.io/devices/sonoff.html#sonoff-touch

# Pin     Function
# ------------------------------
# GPIO0   Button (inverted)
# GPIO12  Relay and Red LED
# GPIO13  Blue LED (inverted)

  - platform: gpio    
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true    
    on_press:
      - fan.toggle: fan

output:
  - platform: gpio
    id: relay    
    pin: GPIO12

status_led:
  pin:
    number: GPIO13
    inverted: false

fan:
  # https://esphome.io/components/fan/binary.html
  - platform: binary
    id: fan
    name: $upper_devicename
    output: relay

```

**Additional information and things you've tried:**

I took board out of the switch and pluged it in programmator near wifi router, I could get the switch to connect to wifi. This was I could reflash, but nothing changed. When I put board back into switch I have no wifi connection. Checking logs it keeps connecting then reboots. 

I use static IP. I tried fast connect and light power safe with no notable changes to behavior.

Right not I'm back to Tasmota and switch seems stable.
