### ISSUE TITLE
HTTP request broken with wifi_signal sensor

### ISSUE THREAD

**Issue by fl42** [esphome/issues#1631]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Fedora 32, pip 20.2.3, python 3.8

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 in Sonoff RF Bridge

**ESPHome version (latest production, beta, dev branch)**
1.15.3

**Affected component:**
[HTTP Request](https://esphome.io/components/http_request.html)
[WiFi Signal Sensor](https://esphome.io/components/sensor/wifi_signal.html)

**Description of problem:**
HTTP POST request fails with "connection failed" error when wifi_signal sensor is setup

**Problem-relevant YAML-configuration entries:**

HTTP request:
```yaml
...
    on_press:
      then:
        - if:
            condition:
              lambda: |-
                ...
            then:
            - http_request.post:
                url: https://my-url
                headers:
                  Content-Type: application/json
                  Authorization: Basic xxx
                body: |-
                  {
                    "message": "My message",
                    "data": ["xxx"]
                  }
                verify_ssl: false
            else:
            - logger.log: "My message if condition is false"
```
WiFi signal sensor:
```yaml
sensor:
  - platform: wifi_signal
    name: Wifi
```

**Logs (if applicable):**

```
[11:26:48][W][http_request:048]: HTTP Request failed; URL: https://my-url; Error: connection failed
```

EDIT: I don't know if it's related but during the HTTP request the api/logger seems to freeze.
However, this behavior is present whether the HTTP request works or not.
(The HTTP request is sent when the binary sensor 'My sensor' switches to ON)
```
[12:20:43][D][binary_sensor:036]: 'My sensor': Sending state ON
WARNING Disconnected from API: Timeout while waiting for message response!
INFO Connecting to 192.168.0.110:6053 (192.168.0.110)
WARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 1 seconds
INFO Connecting to 192.168.0.110:6053 (192.168.0.110)
INFO Successfully connected to 192.168.0.110
[12:21:01][D][remote.rc_switch:256]: Received RCSwitch Raw: protocol=1 data='...'
```

**Additional information and things you've tried:**

Adding wifi_signal sensor seems to break http request component.
I tried multiple times : without wifi_signal sensor the http request component works as expected, with wifi_signal sensor the error message is always present (and the HTTP endpoint is not called).

How could I get more information about this error?
The relation between these 2 modules is not obvious, how could I confirm it?

Thank you for your help

EDIT : The problem is _not_ present on ESP32 (nodemcu-32s)
