### ISSUE TITLE
ac_dimmer component doesn't dim correctly using RobotDyn AC dimmer

### ISSUE THREAD

**Issue by xanderdekok** [esphome/issues#1632]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESPWROOM32
**ESPHome version (latest production, beta, dev branch)**

1.15.3
**Affected component:**

https://esphome.io/components/output/ac_dimmer.html?highlight=dimmer

**Description of problem:**
When using the ac_dimmer component in combination wit the RobotDyn AC dimmer the lamp has an irregular flicker. I use a dimmable LED lamp. Also a normal light bulb doesn't work. I live in the Netherlands so we have 230v at 50hz.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp_test
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "***"
  password: "***"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Test Fallback Hotspot"
    password: "***"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "***"

ota:
  password: "***"

# Enable Bluetooth scanning for this ESP32
# esp32_ble_tracker:

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 22
    zero_cross_pin:
      number: 23
      mode: INPUT
      inverted: yes
    method: leading
    init_with_half_cycle: False
light:
  - platform: monochromatic
    output: dimmer1
    name: Dimmer test
```

**Logs (if applicable):**

```
NA

```

**Additional information and things you've tried:**
I have tried all the possible setting for the ac_dimmer component, but the shown configuration works best with the dimmable LED lamp. The normal light bulp has an even worse irregular flicker than the LED lamp using this configuration.

**Comment by glmnet** [comment]
Well this came in a good time, as I just got a RobotDyn dimmer from @Svrbinek I'm just reproducing this issue, it seems a software issue indeed, I noticed the ZC spike is not very "square" and is more like a peak, other than that is not much different from my original test device.
I had to setup the ZC pin as INPUT_PULLUP (not just INPUT) otherwise the interrupt routine was missing some ZC events, use with default leading method. This kind of works, however not perfect.
Anyway the code is producing different times calculation and this causes flickering of course. Will have to connect the logic analyzer and add some debug pins there to see whats going on.

**Comment by pterodaktil02** [comment]
Same problem 


**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

`esphome:
  name: test_dimmer
  platform: ESP32
  board: esp32doit-devkit-v1`
**ESPHome version (latest production, beta, dev branch)**

ESPHome
Current version: 1.15.3
**Affected component:**

https://esphome.io/components/output/ac_dimmer.html

**Description of problem:**


**Problem-relevant YAML-configuration entries:**
```
output:
  - platform: ac_dimmer
    id: dimmer_light
    gate_pin: GPIO18
    zero_cross_pin:
      number: GPIO19
      mode: INPUT
      inverted: yes

light:
  - platform: monochromatic
    output: dimmer_light
    name: Dimmerized Light
    
sensor:
   - platform: duty_cycle
    pin:  GPIO21
    name:  GPIO21 
    internal: true 
    update_interval: 5s
  - platform: duty_cycle
    internal: true   
    pin:  GPIO18
    name:  GPIO18
    update_interval: 5s  

```

**Logs (if applicable):**

```
[08:29:56][D][duty_cycle:036]: 'GPIO21' Got duty cycle=0.0%
[08:29:56][D][sensor:092]: 'GPIO21': Sending state 0.00000 % with 1 decimals of accuracy
[08:29:56][D][duty_cycle:036]: 'GPIO18' Got duty cycle=100.0%
[08:29:56][D][sensor:092]: 'GPIO18': Sending state 100.00000 % with 1 decimals of accuracy

```

**Additional information and things you've tried:**
After  turn on Dimmerized Light  i can not  control it - it always   on with 100% power

**Comment by glmnet** [comment]
Please test with mode INPUT_PULLUP

**Comment by pterodaktil02** [comment]
> Please test with mode INPUT_PULLUP

It' work  but  we have  filcker   on  ordinaly lamp. is ther  way  change  frecudency of  cut

**Comment by xanderdekok** [comment]
> Please test with mode INPUT_PULLUP

Also tested with INPUT_PULLUP. Unfortunately no difference...

**Comment by pterodaktil02** [comment]
> > Please test with mode INPUT_PULLUP
> 
> Also tested with INPUT_PULLUP. Unfortunately no difference...

try   change pins

i use  this config

`output:
  - platform: ac_dimmer
    id: dimmer_light
    gate_pin: GPIO21
    zero_cross_pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: yes`

**Comment by xanderdekok** [comment]
> > > Please test with mode INPUT_PULLUP
> > 
> > 
> > Also tested with INPUT_PULLUP. Unfortunately no difference...
> 
> try change pins
> 
> i use this config
> 
> `output:
> 
> * platform: ac_dimmer
>   id: dimmer_light
>   gate_pin: GPIO21
>   zero_cross_pin:
>   number: GPIO19
>   mode: INPUT_PULLUP
>   inverted: yes`

It seems to work, the lamp seems to be dimming stable now. Why does it work now?

But it has a real strange side affect. Everything is now inverted on my dashboard. So On is now Off... And 0% is full brightness, 100% is off.

**Comment by mkleijn** [comment]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io on PI3b+

**ESP (ESP32/ESP8266, Board/Sonoff):**
  platform: ESP32
  board: nodemcu-32s

**ESPHome version (latest production, beta, dev branch)**
Latest production (1.15.3)

I also had an issue with the RoboDyn dimmers (both with the single channel version as 4 channel version). Before switching to ESPHome I used my own code using this library: https://github.com/fabiuz7/Dimmable-Light-Arduino. The author of that library describes the same issue with the zero crossing signal not being 'digital' on the RoboDyn hardware: https://github.com/fabiuz7/Dimmable-Light-Arduino/wiki/Notes-about-dimmer-boards. This can be fixed on the hardware side by inserting a non-inverting Schmitt Trigger between the ZC signal from the optocoupler and the ESP. I ordered some SMD versions that I hoped i could solder in the jumper wires between the ESP32 and the board, but i don't trust my soldering skills too much, so until now I relied on some 'software debouncing' of the signal that the library provided. This worked reasonably well, but sometimes there was still some flickering, probably due to some spikes and surges on the net.

About two months ago I migrated to ESPHome because of the (fast) integration with Home Assistant and the fact I think this code has been tested a bit better than my own Arduino code :)

However, out of the box i wasn't able to get a smooth dimming on my (mostly) led lights.  But also a halogen bulb was flickering using the settings from the documentation. I tried all edge modes (raising, leading, leading pulse), with and without half cycle init. I eventually was able to get a reasonable result using the following settings:

` 
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 16
    zero_cross_pin:
      number: 4
      mode: INPUT_PULLDOWN
    min_power: 35%

  - platform: ac_dimmer
    id: dimmer2
    gate_pin: 17
    zero_cross_pin:
      number: 4
      mode: INPUT_PULLDOWN

  - platform: ac_dimmer
    id: dimmer3
    gate_pin: 18
    zero_cross_pin:
      number: 4
      mode: INPUT_PULLDOWN

  - platform: ac_dimmer
    id: dimmer4
    gate_pin: 27
    zero_cross_pin:
      number: 4
      mode: INPUT_PULLDOWN


light:
  - platform: monochromatic
    output: dimmer1
    id: light_1
    name: Light Babyroom 
    default_transition_length: 50ms

  - platform: monochromatic
    output: dimmer2
    id: light_2
    name: Light Hallway
    default_transition_length: 50ms

  - platform: monochromatic
    output: dimmer3
    id: light_3
    name: Light Patio 
    default_transition_length: 50ms

  - platform: monochromatic
    output: dimmer4
    id: light_4
    name: Light Master bedroom 
    default_transition_length: 50ms
`

So instead of using 'inverted' and 'INPUT_PULLUP' on the zero crossing pin as advised in the documentation and this thread I use normal and INPUT_PULLDOWN. It kinda works but it doesn't sit well with me that I go against the advised settings. Probably i'm not detecting the zero crossing of the first half of the cycle, but of the second half (so 180 degree phase shift). Is that a bad thing? Or doesnt it really matter that much?

I still see some flickering with the lights at certain values, and it is also sensitive to noise on the net: I notice for instance that when my laptop adapter is plugged in without any load (so not connected to my laptop) this causes some led bulbs connected to the same phase to flicker. Other led lights using the same ESP / dimmer board have no visual flickering.

**Comment by glmnet** [comment]
There is a big warning at the top of the docs saying this component is not fully tested yet https://esphome.io/components/output/ac_dimmer.html so I really don't understand why you expect to work flawlessly

Otto did the initial work here without any hardware at all, that was amazing, I took over the PR and did a substantial amount of testing but I did not have available the popular RobotDyn module, I had another one and I had very good result with that module, that's why I released this component as is now. You can find more details in the PR https://github.com/esphome/esphome/pull/880

I now have the RobotDyn so I'll test with pull down to see what happens, but as I stated before INPUT_PULLUP does works better than nothing in my setup but still has issues at some brightness levels.

**Comment by mkleijn** [comment]
Sorry? Where do I state that i expect it to work flawlessly? I thought this was a good place to write down my experiences so others might be able to try my non-inverted / pulldown method. And supply the original developers with a link to another library / wiki page that describes this issue with the RoboDyn analog ZC signal and how they combated it. 

I actually wanted to drop my experience in PR 880 as I was invited by that big warning at the top of the docs you mention, but the comments there are closed so I posted it here.

Anyway, kudos to both Otto and you for the amazing work on ESPHome, and apologies if I offended you in any way. 

Out of interest, what dimmer module you had good experience with? It might be the easiest solution to swap that (if it fits my casing).

**Comment by glmnet** [comment]
> and the fact I think this code has been tested a bit better than my own Arduino code :)

Maybe I took this comment specific to this code, but you meant all ESPHome, no worries I'm not offended is just that the warning is there.

Anyway, your post is indeed useful. 
In the long 880 thread there is a picture of the hardware I used for development, looks very much like the one used by the library you posted, a blue one, mine is 4 channel not 8 though.

One key difference between that library (and other libraries) I've seen around and the one in ESPHome is that the ISR is setup on the ZC pin as `RISING` whereas in ESPHome it is `FALLING` [see here](https://github.com/esphome/esphome/blob/7ff3f752e23b0c11aa2123209d7b2e296cbfdf63/esphome/components/ac_dimmer/ac_dimmer.cpp#L174) this might be related, but I need to test that better.

**Comment by mkleijn** [comment]
Ah ok @glmnet I see how that line you quoted could be seen as me being sarcastic about the code maturity of this component or ESPHome in general, but that was not how I intended it. 

Interesting to hear about your tests with FALLING vs RAISING on the ZC interrupt. I'll see if I can do some testing of my own with this.

But in the end it might be impossible to get a complete flicker-free implementation without some hardware adjustments like adding a Schmitt trigger or replacing the 4N25 optocoupler by one with an integrated Schmitt trigger like the H1L11 (http://www.bristolwatch.com/ele2/zcnew.htm). 
The 'official' library supplied by RoboDyn (https://github.com/RobotDynOfficial/RBDDimmer) which I started out with using gave far worse results so maybe it's just the best possible result with these boards as they are.

**Comment by Svrbinek** [comment]
Hello. If necessary, I can help with testing. I am glad that this project is moving in the right direction.

**Comment by Hendrikdenhond** [comment]
I have the dimmer connected to some halogen lights (resistive load) and also experienced a lot of flickering.
I tried all combinations of code but nothing worked.
BUT I found the origin of my problem.  I was powering the esp with a external 5V powersupply soldered to the 5V and GND pin and had flickering.  When the ESP was connected over and USB cable with powerplug the flickering was gone.
So I suspect that the filtering on the powersupply was not sufficient enough and messed up the zero cross signal. Did not tried LED lamps yet.
For info: I tested on belgium powernet, 240AC 50Hz.

**Comment by xanderdekok** [comment]
I did some more testing and I got the dimmer also working with a Sonoff 4CH. You can see my configuration below.
I did a few modifications to the Sonoff 4CH:

1. I soldered pin headers onto the board to flash it and to use with the dimmer for the zero cross pin
2. I soldered a wire to the GPIO 10 pin at 3rd button for the gate pin
3. I soldered 2 wires to the 4th button, to be able to use an external switch to turn on relay 4.

I did notice some side affects

1. The dimmer icon on the Lovelace dashboard is still inverted, like I also experienced before.  See my previous comment.
2. There was interference between the wires for the dimmer and the external switch. This caused button 4 to be triggered irregularly.  It also caused the dimmed lights to drop out for about 0.5s at a time at irregular intervals.

I was able to solve the interference by making sure the wires for the dimmer and the external switch are no longer close together. So apparently when using this dimmer it is prone to signal interference... 
This might be why some people are experiencing a flicker. I too had a flicker with my original setup for my ESP32 board and after switching pins it miraculously worked.


```yaml
esphome:
  name: tuinverlichting
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "#3_NoT"
  password: "SmartThingsThatShouldNotPhoneHome"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "T Verlichting Fallback Hotspot"
    password: "xxx"

captive_portal:

# Enable Web server
web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxx"

ota:
  password: "xxx"

interval:
  - interval: 1s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - output.turn_on: blue_led
        else:
          - output.turn_off: blue_led

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  name: "Tuinverlichting Button 1"
  on_press:
    - switch.toggle: relay_1
- platform: gpio
  pin:
    number: GPIO9
    mode: INPUT_PULLUP
    inverted: True
  name: "Tuinverlichting Button 2"
  on_press:
    - switch.toggle: relay_2
#- platform: gpio
#  pin:
#    number: GPIO10
#    mode: INPUT_PULLUP
#    inverted: True
#  name: "Tuinverlichting Button 3"
#  on_press:
#    - switch.toggle: relay_3
- platform: gpio
  pin:
    number: GPIO14
    mode: INPUT_PULLUP
    inverted: True
  name: "Tuinverlichting Button 4"
  on_press:
    - switch.toggle: relay_4
- platform: status
  name: "Tuinverlichting Status"

switch:
- platform: gpio
  name: "Tuinverlichting Relay 1"
  pin: GPIO12
  id: relay_1
- platform: gpio
  name: "Tuinverlichting Relay 2"
  pin: GPIO5
  id: relay_2
- platform: gpio
  name: "Tuinverlichting Relay 3"
  pin: GPIO4
  id: relay_3
- platform: gpio
  name: "Tuinverlichting Relay 4"
  pin: GPIO15
  id: relay_4

output:
- platform: esp8266_pwm
  id: blue_led
  pin: GPIO13
  inverted: True

- platform: ac_dimmer
  id: dimmer_tuinverlichting
  gate_pin: GPIO10
  zero_cross_pin:
    number: GPIO2
    mode: INPUT_PULLUP
  inverted: yes

light:
  - platform: monochromatic
    output: dimmer_tuinverlichting
    name: Dimmer Veranda


```
