### ISSUE TITLE
ESP32-POE constant socket errors MQTT

### ISSUE THREAD

**Issue by lancelon** [esphome/issues#1636]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Mac OS X pip3

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32-POE

**ESPHome version (latest production, beta, dev branch)**

1.15.3

**Affected component:**

MQTT / API

**Description of problem:**
Despite using ethernet, my Olimex ESP32-POE running ESPHome is CONSTANTLY showing an MQTT broker error and disconnecting then reconnecting. I'm really confused. I AM using the HA API integration but will be disabling it to see if it helps. Otherwise....any other tips?!

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: traffic
  platform: ESP32
  board: esp32-poe

mqtt:
  broker: 192.168.1.1
  client_id: TrafficLight
  topic_prefix: Traffic
  will_message:
    topic: traffic/avail
    payload: offline
  on_message:
    - topic: traffic/green/on
      then:
        - switch.turn_on: relay1
    - topic: traffic/green/off
      then:
        - switch.turn_off: relay1
    - topic: traffic/red/on
      then:
        - switch.turn_on: relay2
    - topic: traffic/red/off
      then:
        - switch.turn_off: relay2

#wifi:
#  ssid: "x"
#  password: "x"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Traffic Fallback Hotspot"
#    password: "oBgluJkLBRjP"

#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "x"

ota:
  password: "x"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

  switch:
  - platform: gpio
    name: "Green Light"
    pin: 32
    id: relay1
    interlock: [relay2]
  - platform: gpio
    name: "Red Light"
    id: relay2
    pin: 13
    interlock: [relay1]

binary_sensor:
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: True
    name: "Allow Access"
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.turn_on: relay1
  - platform: gpio
    pin:
      number: 15
      mode: INPUT_PULLUP
      inverted: True
    name: "Stop Access"
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.turn_on: relay2
```

**Logs (if applicable):**

```
15:24: Socket error on client TrafficLight, disconnecting.
15:25: New connection from 192.168.2.24 on port 1883.
15:25: New client connected from 192.168.2.24 as TrafficLight (c1, k15).
15:34: New connection from 192.168.2.24 on port 1883.
15:34: Client TrafficLight already connected, closing old connection.
15:34: Client TrafficLight disconnected.
15:34: New client connected from 192.168.2.24 as TrafficLight (c1, k15).
15:35: Client RANGER has exceeded timeout, disconnecting.
15:35: Socket error on client RANGER, disconnecting.
15:36: New connection from 192.168.2.4 on port 1883.
15:36: New client connected from 192.168.2.4 as RANGER (c1, k60, u'').
16:51: New connection from 192.168.2.24 on port 1883.
16:51: Client TrafficLight already connected, closing old connection.
16:51: Client TrafficLight disconnected.
16:51: New client connected from 192.168.2.24 as TrafficLight (c1, k15).
16:52: Client RANGER has exceeded timeout, disconnecting.
16:52: Socket error on client RANGER, disconnecting.
16:52: New connection from 192.168.2.4 on port 1883.
16:52: New client connected from 192.168.2.4 as RANGER (c1, k60, u'').
17:13: Saving in-memory database to /data/mosquitto.db.
17:17: New connection from 192.168.2.24 on port 1883.
17:17: Client TrafficLight already connected, closing old connection.
17:17: Client TrafficLight disconnected.
17:17: New client connected from 192.168.2.24 as TrafficLight (c1, k15).
17:18: Client RANGER has exceeded timeout, disconnecting.
17:18: Socket error on client RANGER, disconnecting.
17:19: New connection from 192.168.2.4 on port 1883.
17:19: New client connected from 192.168.2.4 as RANGER (c1, k60, u'').
17:43: Saving in-memory database to /data/mosquitto.db.


```

**Additional information and things you've tried:**

Struggle to see how I'd debug by serial because ethernet won't work at the same time as serial will it?

Would love some help. Thanks
