### ISSUE TITLE
Platform esphome does not generate unique IDs.

### ISSUE THREAD

**Issue by nerdgarden** [esphome/issues#1637]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Homeassistant managed on RaspiOS
**ESP (ESP32/ESP8266, Board/Sonoff):**

Shelly 1, Sonoff T1
**ESPHome version (latest production, beta, dev branch)**

Version: 1.15.3

**Affected component:**

All

**Description of problem:**
I receive an error in Home Assistant logs and devices appearing and disappearing:

2020-11-16 19:58:04 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform esphome does not generate unique IDs. ID sala_da_pranzobinary_sensorsala_da_pranzo already exists - ignoring binary_sensor.sala_da_pranzo
2020-11-16 19:58:04 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID sala_da_pranzolightsala_da_pranzo already exists - ignoring light.sala_da_pranzo
2020-11-16 19:58:16 ERROR (MainThread) [homeassistant.util.logging] Exception in _on_device_update when dispatching 'esphome_5d78a31df7543f3794c3d702aebacfca_on_device_update': ()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 545, in _on_device_update
if self._entry_data.available:
File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 560, in _entry_data
return self.hass.data[DATA_KEY][self._entry_id]
KeyError: '5d78a31df7543f3794c3d702aebacfca'
2020-11-16 19:58:16 ERROR (MainThread) [homeassistant.util.logging] Exception in _on_device_update when dispatching 'esphome_5d78a31df7543f3794c3d702aebacfca_on_device_update': ()
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 545, in _on_device_update
if self._entry_data.available:
File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 560, in _entry_data
return self.hass.data[DATA_KEY][self._entry_id]
KeyError: '5d78a31df7543f3794c3d702aebacfca'
2020-11-16 19:58:17 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform esphome does not generate unique IDs. ID sala_da_pranzobinary_sensorsala_da_pranzo already exists - ignoring binary_sensor.sala_da_pranzo
2020-11-16 19:58:17 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID sala_da_pranzolightsala_da_pranzo already exists - ignoring light.sala_da_pranzo
2020-11-16 19:58:17 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID pulsantiera_cucinalightcucina already exists - ignoring light.cucina
2020-11-16 19:58:17 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID pulsantiera_cucinalightsala_piccola already exists - ignoring light.sala_piccola
2020-11-16 19:58:17 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID pulsantiera_cucinalightingresso_due already exists - ignoring light.ingresso_due
2020-11-16 19:58:17 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform esphome does not generate unique IDs. ID pulsantiera_cucinabinary_sensorpulsantiera_cucina already exists - ignoring binary_sensor.pulsantiera_cucina

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: pulsantiera_bagno_ingresso
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pulsantiera Bagno Ingresso"
    password: "ahIvFcsB6Rg1"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: toggle_1
    on_press:
      then:
        - light.toggle: light_1
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    id: toggle_2
    on_press:
      then:
      - light.toggle: light_2
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    id: toggle_3
    on_press:
      then:
        - light.toggle: light_3
  - platform: status
    name: "Pulsantiera Bagno Ingresso"

status_led:
  # Register the blue LED as status led
    pin:
      number: GPIO13
      inverted: True

output:
  - platform: gpio
    id: relay_1
    pin: GPIO12
  - platform: gpio
    id: relay_2
    pin: GPIO5
  - platform: gpio
    id: relay_3
    pin: GPIO4

light:
  # ... and then make a light out of it.
  - platform: binary
    id: light_1
    output: relay_1
    name: "Bagno ingresso"
  - platform: binary
    id: light_2
    output: relay_2
    name: "Ingresso"
    on_turn_on:
    - delay: 0.1s
    - light.turn_off: light_2
  - platform: binary
    id: light_3
    output: relay_3
    name: "Sala Grande"

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by akomelj** [comment]
I am experiencing a similar problem.

I am NOT using ESPHome integration in Home Assistant and instead rely on MQTT auto discovery for various reasons.

ESPHome generates non-unique `unique_id` identifiers for some sensors and switches and most of the time Home Assistant does not pick these sensors and switches up, complaining that `unique_id`s are not unique enough (Home Assistant 0.118.4). Whether these sensors are later visible in Home Assistant UI or not, depends on pure luck with timing how device discovery messages are published to MQTT, how historic data is restored, how Home Assistant is restarted, etc.

A simple fix is obvious. However - as it probably breaks backwards compatibility and may cause some sensors from older version devices to be duplicated - I would like some further comments from the authors of ESPHome.

In mqtt_component.cpp:

```diff
         } else {
           // default to almost-unique ID. It's a hack but the only way to get that
           // gorgeous device registry view.
-          root["unique_id"] = "ESP" + this->component_type() + this->get_default_object_id_();
+          root["unique_id"] = get_mac_address() + "-" + this->component_type() + "-" + this->get_default_object_id_();
         }
```

Let's use `restart` switch with name `Restart` as an example. Before change, the uniquely generated ID for this generic MQTT switch is `ESPswitchrestart` and may conflict with any other ESPHome device using the same definition of the switch (i.e. when reusing configuration via split configuration files or just friendly naming the `restart` switch `Restart`). :-)

The proposed change generates a different, hopefully globally unique ID and Home Assistant happily registers the switch with the device: `cc50e34ba6fb-switch-restart`.

Any comment on why this hasn't been implemented  would be greatly appreciated - I've noticed that `get_mac_address()` is  used when generating IDs in some out-of-the-box sensors (i.e. Wi-fi info, etc) so I assume some reason exists for not doing it generically. Can someone elaborate what that comment *"default to almost-unique ID. It's a hack but the only way to get that gorgeous device registry view."* means or if generating unique `unique_id`s may be a bad idea?

**Comment by john-arvid** [comment]
Same problem here, every time I restart home assistant I get this problem for one specific device.

**Comment by YvesZH** [comment]
+1
Same here

**Comment by The-Deep-Sea** [comment]
+1
An alternative to the approach using the mac address is using the node name. 
According to the documentation: _This is the name of the node. It should always be unique in your ESPhome network._

**Comment by CarlosGS** [comment]
Any tips to fix this?

> ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID bombilla_estudiolightbombilla_estudio already exists - ignoring light.bombilla_estudio

We only need to know where is it actually checking. Not sure if that's `.storage` :thinking:

**Comment by tvwerkhoven** [comment]
I have the same problem. When there are esphome entities connected with:
1. multiple sensors of the same platform
2. for platforms which do not have a static unique id

Homeassistant only reads 1 (random?) sensor of this pool.

For example: the [BME280](https://esphome.io/cookbook/bme280_environment.html) or [MH-Z19B](https://esphome.io/components/sensor/mhz19.html) sensors both show this problem, whereas 1wire sensors (such as [Dallas](https://esphome.io/components/sensor/dallas.html)) do not.

### Proposed fix

- Current method: generating unique_id with `<esphome id>_<sensor_platform>` (e.g. esp_livingsensormh-z19_co2)
- Proposed fix: generate unique_id with `<esphome id>_<sensor_platform>_<sensor_id>` (e.g. `esp_livingsensormh-z19_co2_my_sensor_id1`)

It will be up to the user to ensure `<sensor_id>` is unique, but that's better than having no control. I'm not sure where in the codebase `unique_id` is generated, but hopefully someone can help.

### Example
In my case I address a sensor twice in an esphome node, 1x to show the actual value, 1x to show the exponential moving average (ema) on an oled. However, Homeassistant only accepts one of these sensors, and ignores the other, because both get the unique_id `esp_livingsensormh-z19_co2`. The proposed fix would give these two sensors `unique_id`s:
`esp_livingsensormh-z19_co2_mh_z19` and `esp_livingsensormh-z19_co2_mh_z19_ema`

```yaml
sensor:
  - platform: mhz19
    id: mh_z19
    co2:
      name: "MH-Z19 CO2"
      id: mh_z19_co2
    temperature:
      name: "MH-Z19 Temperature"
      id: mh_z19_temp
    update_interval: 60s
    uart_id: myuart1
  - platform: mhz19
    id: mh_z19_ema
    co2:
      name: "MH-Z19 CO2"
      id: mh_z19_co2_ema
      filters:
      - exponential_moving_average:
          alpha: 0.0028 # We want ~12 hour averaging, at 60s update, that's 12*3600/60 = 720points, thus alpha should be 2/1440 ~ 0.0028 
          send_every: 1
    update_interval: 60s # if changed also update alpha
    uart_id: myuart1
```

**Comment by tvwerkhoven** [comment]
Update: it seems I was wrong, `unique_id` is generated with <esphome id>_<sensor_name>, so as a user one should ensure `<sensor_name>` is unique across *all* esphome entities you want to use with Home Assistant.

**Comment by OttoWinter** [comment]
@akomelj Yes, the **MQTT integration** does not have a great default way to generate unique IDs. As you said it doesn't contain the MAC address/node name. That's an issue dating quite a while back and we tried to fix it, but as you said it's a pretty big breaking change and so would first need HA to add some functionality to _migrate_ unique IDs.

**BUT**, that's only for MQTT, most other posts here appear to be about `api` connectivity with HA. There, `unique_id`s _do_ contain the device name, and so the generated unique IDs should be "more" safe. But there appears to be a bug in the HA integration somewhere that creates those exceptions, I haven't found how to replicate nor what it could be yet.

Let's keep this issue about the `api` unique id error, not MQTT unique ids.

**Comment by juicejuice** [comment]
@OttoWinter I definitely get this with the HA "api" integration for ESPHome. If there is anything I can investigate or do to help track it down just let me know. It seems to happen randomly e.g. I restarted HA yesterday and now one of my new ESPHome devices is unavailable, HA log reports the unique ID issue. I have solved in the past by removing and readding the relevant device integrations but the problem will still come back from time to time.

**Comment by OttoWinter** [comment]
> inspection of core.device_registry shows that many of my ESPHome devices have two or more "config_entries". I'm not really familiar with HA internals but I would expect each device to have a single config_entry.

Oh that is very interesting! I have absolutely no idea how that can happen, because ESPHome just writes to the `esphome.{config_entry_id}` file (and each config entry is fully independent, on the esphome _integration_ side there's no communication whatsoever between config entries).

That makes me think _maybe_ there's a race condition or something in the HA `Storage` system maybe?

**Comment by juicejuice** [comment]
@OttoWinter I'm digging into this a little more but I'm only an HA user rather than developer so it's taking some time. From my system snapshot I can see a number of ESPHome devices have duplicate/triplicate config_entries in core.device_registry. The IDs are pointing to different devices e.g. it's not that I have duplicate configurations for the same device in core.config_entries.

One idea that came to mind is that my LAN is using DHCP for the ESPHome devices. Is it possible that my DHCP server is sometimes assigning an IP to a new device that used to belong to an older device? So when I setup a new device it gets confused because the old IP has been recycled for the new device? (I noticed that each device's IP is stored as the "host" value for each entry_id in core.config_entries)

**Comment by OttoWinter** [comment]
Thanks @juicejuice - I just looked into my `core.device_registry` and I too see lots of devices have multiple items under the `config_entries` key (each time _one_ of them is the right one, but a different one points to a completely random config entry/device).

If yours and my issues are the same - or have the same root cause - then that rules out DHCP. I only use static IP assignments. It also rules out mDNS as being involved, because my HA deployment is in a docker container without mDNS access.

About the `host` thing: That's the host that was initially entered when setting up in the integrations screen. How did you set up the device? Via entering the host manually or by autodiscovery?

**Comment by juicejuice** [comment]
@OttoWinter thanks - good details and it seems DHCP was a bad guess :)
Most of my ESPHome devices were setup via autodiscovery but for a few of them I typed in the mDNS hostname manually e.g. "something.local". In all cases IP addresses are showing in core.config_entries, none of them have the hostname for that field. Is that expected?

BTW I've now written a Python script that extracts all the relevant data from the .storage config files. The preliminary JSON output is already proving insightful. I'll do a little more research on my data set, maybe pull it into Excel, and report anything interesting that pops out.

**Comment by OttoWinter** [comment]
> In all cases IP addresses are showing in core.config_entries, none of them have the hostname for that field. Is that expected?

Huh, that _definitely_ should not be the case. After some digging it looks like that was introduced here https://github.com/home-assistant/core/pull/34753

**Comment by juicejuice** [comment]
@OttoWinter I'm running out of good ideas on this one. I would need to know a lot more about the internals to continue diagnosis. I'll clean up my config and then keep an eye out if it happens again and try to figure out what triggered it. In the meantime I'm listing my findings here in case it helps others.

These observations are related to the config files in the homeassistant .storage folder:
1. core.device_registry tracks all devices and allows for a single device ID to have multiple "config_entries" IDs
2. when there are multiple "config_entries" IDs for a single ESPHome device, these are for config_entries of different ESPHome devices!
3. these mismatched config_entries IDs cause unique ID errors in the HA log and the ESPHome devices become unavailable in HA and Lovelace (ESPHome still sees them correctly)
4. the core.config_entries, core.entity_registry, and esphome.* files all match up nicely, no duplicate IDs or mismatches; the problems always stem from the core.device_registry getting tangled up
5. ESPHome also leaves behind "orphaned" esphome.* files where devices have been adjusted in the past, it doesn't appear these are ever cleaned up, although their relevant config_entries are removed from the core.* files

**Comment by OttoWinter** [comment]
Thanks so much @juicejuice ! This insight is helping a lot for understanding this complex issue!

I've deployed my setup with more logging, and am hoping to catch this issue happening (but so far hasn't happened). I tried all sorts of things, reconnecting devices like crazy, disabling, deleting etc. Is there some way you could consistently get to that state?

If possible, some debug logs might be helpful - the affected code doesn't appear to log very much, but maybe it could still help. You can turn up the logging like this in your HA `configuration.yaml`:

```yaml
logger:
  # ...
  logs:
    homeassistant.components.esphome: debug
    homeassistant.helpers.device_registry: debug
    homeassistant.helpers.storage: debug
    homeassistant.helpers.entity_registry: debug
```

Ad 5: Yeah, those files aren't removed, but that also isn't a big issue because they're essentially ignored after the entry is removed (nevertheless, I implemented removal upon entry removal here: https://github.com/home-assistant/core/pull/52296)
