### ISSUE TITLE
ESP32 adc reads unexpected values

### ISSUE THREAD

**Issue by DonGar** [esphome/issues#1640]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io on an Intel NUC.

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32-DevKitC-32E

**ESPHome version (latest production, beta, dev branch)**

Latest Production (0.117.6)

**Affected component:**

ADC Sensor
https://esphome.io/components/sensor/adc.html

**Description of problem:**
When attenuation is set, the sensor will read the max allows voltage, or 0, but nothing in between with most voltages reading as max voltage.

If attenuation is not set and I use a voltage divider, the ESP32 reads expected voltage values.

When not using the voltage divider, the circuit is:

board 3.3v -> variable resister -> GPIO36
  Will always read 3.9v, even with 1000k Ohms of resistence.

board GND -> GPIO36
  Will always read 0.0v.

Disconnected -> GPIO36
  Will float the voltage around randomly.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test
  platform: ESP32
  board: nodemcu-32s

sensor:
  - platform: adc
    pin: GPIO36
    name: "Flex 0"
    update_interval: 1s
    attenuation: 11db
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
