### ISSUE TITLE
Problem with ac_dimmer

### ISSUE THREAD

**Issue by pterodaktil02** [esphome/issues#1642]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

`esphome:
  name: test_dimmer
  platform: ESP32
  board: esp32doit-devkit-v1`
**ESPHome version (latest production, beta, dev branch)**

ESPHome
Current version: 1.15.3
**Affected component:**

https://esphome.io/components/output/ac_dimmer.html

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```
output:
  - platform: ac_dimmer
    id: dimmer_light
    gate_pin: GPIO18
    zero_cross_pin:
      number: GPIO19
      mode: INPUT
      inverted: yes

light:
  - platform: monochromatic
    output: dimmer_light
    name: Dimmerized Light
    
sensor:
   - platform: duty_cycle
    pin:  GPIO21
    name:  GPIO21 
    internal: true 
    update_interval: 5s
  - platform: duty_cycle
    internal: true   
    pin:  GPIO18
    name:  GPIO18
    update_interval: 5s  

```

**Logs (if applicable):**

```
[08:29:56][D][duty_cycle:036]: 'GPIO21' Got duty cycle=0.0%
[08:29:56][D][sensor:092]: 'GPIO21': Sending state 0.00000 % with 1 decimals of accuracy
[08:29:56][D][duty_cycle:036]: 'GPIO18' Got duty cycle=100.0%
[08:29:56][D][sensor:092]: 'GPIO18': Sending state 100.00000 % with 1 decimals of accuracy

```

**Additional information and things you've tried:**
After  turn on Dimmerized Light  i can not  control it - it always   on with 100% power
