### ISSUE TITLE
Devices permanently disconnected from wifi

### ISSUE THREAD

**Issue by jpgimenez** [esphome/issues#1643]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

  * ESP32
  * Sonoff

**ESPHome version (latest production, beta, dev branch)**

1.15.3

**Affected component:**

https://esphome.io/components/wifi.html

**Description of problem:**
I was cleaning the config of some of my devices, and enabling ap/captive portal at the same time. In the process I saw some of the devices disappear from the network, I first suspect from the wifi settings, but the captive was not showing neither, I found issue #1629, but in my case the credentials are ok, other devices are using those credentials without issues, the main difference with working devices is that I removed the `platform: gpio` from `binary_sensor` section, because I wasn't using the button.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: bedroom
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
web_server:
  port: 80

binary_sensor:
  - platform: status
    name: "System Status"

# Example configuration entry
sensor:
  - platform: uptime
    name: "System Uptime"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO13
      inverted: True
```

```diff
diff --git a/esphome/bedroom.yaml b/esphome/bedroom.yaml
index df961b2..ef7a20e 100644
--- a/esphome/bedroom.yaml
+++ b/esphome/bedroom.yaml
@@ -4,11 +4,8 @@ esphome:
   board: esp01_1m
 
 wifi:
-  networks:
-  - ssid: !secret wifi-ssid-int
-    password: !secret wifi-password-int
-  - ssid: !secret wifi-ssid-ext
-    password: !secret wifi-password-ext
+  ssid: !secret wifi-ssid
+  password: !secret wifi-password
 
 # Enable logging
 logger:
@@ -25,34 +22,6 @@ web_server:
 binary_sensor:
   - platform: status
     name: "System Status"
-  - platform: gpio
-    pin:
-      number: GPIO14
-      mode: INPUT_PULLUP
-      inverted: True
-    name: "Button"
-    on_multi_click:
-    - timing:
-        - ON for at most 1s
-        - OFF for at most 1s
-        - ON for at most 1s
-        - OFF for at least 0.2s
-      then:
-        - logger.log: "Double Clicked"
-    - timing:
-        - ON for 1s to 2s
-        - OFF for at least 0.5s
-      then:
-        - logger.log: "Single Long Clicked"
-    - timing:
-        - ON for at most 1s
-        - OFF for at least 0.5s
-      then:
-        - logger.log: "Single Short Clicked"
-        - homeassistant.service:
-            service: automation.trigger
-            data:
-              entity_id: "automation.light_toggle_bedroom"
 
 # Example configuration entry
 sensor:
```

**Logs (if applicable):**

I don't have logs.
 
**Additional information and things you've tried:**

I tried restarting, but nothing, the devices didn't try to connect to the router, no intent are show on the router logs.
