### ISSUE TITLE
Sim800L issues in 1.15.3

### ISSUE THREAD

**Issue by syphernl** [esphome/issues#1649]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Pip

**ESP (ESP32/ESP8266, Board/Sonoff):** 

ESP32

**ESPHome version (latest production, beta, dev branch)**

1.15.3

**Affected component:**

https://esphome.io/components/sim800l.html

**Description of problem:**
After updating from `1.15.2` to `1.15.3` my Sim800L could not properly register to the network. 

```
[13:25:41][D][sim800l:216]: Unhandled: +CREG: 1,0 - 0
[13:25:41][D][sim800l:216]: Unhandled: OK - 0
[13:25:41][D][sim800l:216]: Unhandled: +CREG: 1,0 - 0
[13:25:41][D][sim800l:216]: Unhandled: OK - 0
[13:25:44][W][sim800l:062]: Not ack. 2 +CREG: 1,0
[13:25:44][D][sim800l:216]: Unhandled: OK - 0
[13:25:46][D][sim800l:216]: Unhandled: +CREG: 1,0 - 0
[13:25:46][D][sim800l:216]: Unhandled: OK - 0
[13:25:46][D][sim800l:216]: Unhandled: +CREG: 1,0 - 0
[13:25:46][D][sim800l:216]: Unhandled: OK - 0
```

After downgrading back to `1.15.2` it properly registers again:
```
[D][sim800l:216]: Unhandled: Call Ready - 0
[D][sim800l:216]: Unhandled: SMS Ready - 0
[W][sim800l:062]: Not ack. 3 AT+CMGF=1
[D][sim800l:216]: Unhandled: OK - 0
[D][sim800l:216]: Unhandled: +CMTI: "SM",2 - 0
[W][sim800l:062]: Not ack. 3 ATE0AT+CMGF=1
[D][sim800l:216]: Unhandled: OK - 0
[D][sim800l:216]: Unhandled: OK - 0
[D][sim800l:103]: Registered OK
```
and can receive SMS again 
```
[D][sim800l:129]: RSSI: 12
[D][sim800l:174]: Received SMS from: +316XXXXXXXX
[D][sim800l:175]: Test test test
```

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: sim800l
  platform: ESP32
  board: esp-wrover-kit

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
  use_address: "XX.XX.XX.XX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sim800L Fallback Hotspot"
    password: "XXXXXXXXXXX"

captive_portal: 

# Enable Web server
web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
  - service: send_sms
    variables:
      recipient: string
      message: string
    then:
    - sim800l.send_sms:
        recipient: !lambda 'return recipient;'
        message: !lambda 'return message;'

text_sensor:
  - platform: template
    id: sms_sender
    name: "Sms Sender"
  - platform: template
    id: sms_message
    name: "Sms Message"

uart:
  baud_rate: 9600
  tx_pin: 27
  rx_pin: 26

sim800l:
  id: sms
  on_sms_received:
  - lambda: |-
      id(sms_sender).publish_state(sender);
      id(sms_message).publish_state(message);

switch:
  - platform: gpio
    name: "SIM800_PWKEY"
    pin: 4
    restore_mode: ALWAYS_OFF
    internal: true
  - platform: gpio
    name: "SIM800_RST"
    pin: 5
    restore_mode: ALWAYS_ON
    internal: true
  - platform: gpio
    name: "SIM800_POWER"
    pin: 23
    restore_mode: ALWAYS_ON
    internal: true
  - platform: restart
    name: "Sim800L Restart"

ota:
  password: !secret ota_password

```

**Logs (if applicable):**

 See above

**Additional information and things you've tried:**
This change seems to be the difference between `1.15.2` and `1.15.3`: https://github.com/esphome/esphome/pull/977 (issue https://github.com/esphome/issues/issues/1042).

I am using a sim card of an MVNO (Simyo) on the KPN network.
