### ISSUE TITLE
Home Assistant addon toggles switches on start

### ISSUE THREAD

**Issue by chriscrowe** [esphome/issues#165]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

- HassIO running on Ubuntu VM in Synology DS918+
- ESPHome addon running in HassIO

**ESP (ESP32/ESP8266, Board/Sonoff):**

- Teckin SP20 switch, ESP8266, running ESPHome v 1.11.2

**Affected component:**

https://esphome.io/guides/getting_started_hassio.html

**Description of problem:**

When the Home Assistant ESPHome addon (container) starts, it toggles my ESPHome Teckin SP20 switches off and back on again. This obviously presents an issue if the switches are hooked inline on something like a NAS, which could result in data corruption (luckily a well-placed UPS helps in this case).

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  plug_name: teckin1
  # Higher value gives lower watt readout
  current_res: "0.002142347"
  # Lower value gives lower voltage readout
  voltage_div: "946"

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "**********"
  password: "**********"

# Enable logging
logger:

# Enable Web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: "**********"

ota:
  password: "**********"

time:
  - platform: homeassistant
    id: homeassistant_time
    
binary_sensor:
  - platform: gpio
    pin:
      number: 13
      inverted: True
    name: "${plug_name}_button"
    on_press:
      - then:
        - switch.toggle: relay
        - if:
            condition:
              switch.is_on: relay
            then:
              switch.turn_on: blue_led
            else:
              switch.turn_off: blue_led
    
switch:
  - platform: gpio
    name: "${plug_name}_Relay"
    pin: 04
    restore_mode: ALWAYS_ON
    id: relay
  - platform: gpio
    name: "${plug_name}_LED_Blue"
    pin:
      number: 2
      inverted: True
    restore_mode: RESTORE_DEFAULT_OFF
    id: blue_led
  - platform: gpio
    name: "${plug_name}_LED_Red"
    pin:
      number: 0
      inverted: True
    restore_mode: RESTORE_DEFAULT_OFF
    id: red_led

sensor:
  - platform: hlw8012
    sel_pin:
      number: 12
      inverted: True
    cf_pin: 5
    cf1_pin: 14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${plug_name}_Amperage"
      unit_of_measurement: A
    voltage:
      name: "${plug_name}_Voltage"
      unit_of_measurement: V
    power:
      name: "${plug_name}_Wattage"
      unit_of_measurement: W
      id: "${plug_name}_Wattage"
    change_mode_every: 8
    update_interval: 10s
  - platform: total_daily_energy
    name: "${plug_name}_Total Daily Energy"
    power_id: "${plug_name}_Wattage"
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
      
# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: ${plug_name}_Uptime Sensor
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
