### ISSUE TITLE
GPIO low state in deep sleep mode 

### ISSUE THREAD

**Issue by adiman29** [esphome/issues#1650]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

 Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266

**ESPHome version (latest production, beta, dev branch)**
 1.15.3

**Affected component:**
 
https://esphome.io/components/deep_sleep.html
https://esphome.io/components/sensor/pmsx003.html

**Description of problem:**

The point is that I have a pms7003 sensor and I would like to put it to sleep together with esp8266, i.e. give the low state to the pin set. However, as soon as esp enters sleep mode, all GPIOs are high and pms7003 is running. 

**Problem-relevant YAML-configuration entries:**
```yaml

esphome:
  name: pogodynka
  platform: ESP8266
  board: d1_mini

deep_sleep:
  id: deep_sleep_1
  run_duration: 3min
  sleep_duration: 2min
  
uart:
  rx_pin: GPIO13
  baud_rate: 9600
  
switch:
  - platform: gpio
    pin: 0
    id: pms_set

interval:
  - interval: 2min
    then:
      - switch.turn_on: pms_set
      - delay: 15s
      - switch.turn_off: pms_set

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "PM1"
    pm_2_5:
      name: "PM2.5"
    pm_10_0:
      name: "PM10"



**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->


PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

Im tried 10k resistor pull-down and on_shutdown option. Not working
