### ISSUE TITLE
Client reconnecting to MQTT every 15 minutes, like #1636

### ISSUE THREAD

**Issue by lancelon** [esphome/issues#1651]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Mac OS X pip3

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32-POE

**ESPHome version (latest production, beta, dev branch)**

1.15.3

**Affected component:**

MQTT 

**Description of problem:**
Now getting a REGULAR MQTT disconnect every 15 minutes.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: traffic
  platform: ESP32
  board: esp32-poe

mqtt:
  broker: 192.168.1.1
  client_id: TrafficLight
  topic_prefix: Traffic
  will_message:
    topic: traffic/avail
    payload: offline
  on_message:
    - topic: traffic/green/on
      then:
        - switch.turn_on: relay1
    - topic: traffic/green/off
      then:
        - switch.turn_off: relay1
    - topic: traffic/red/on
      then:
        - switch.turn_on: relay2
    - topic: traffic/red/off
      then:
        - switch.turn_off: relay2

#wifi:
#  ssid: "x"
#  password: "x"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Traffic Fallback Hotspot"
#    password: "oBgluJkLBRjP"

#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "x"

ota:
  password: "x"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

  switch:
  - platform: gpio
    name: "Green Light"
    pin: 32
    id: relay1
    interlock: [relay2]
  - platform: gpio
    name: "Red Light"
    id: relay2
    pin: 13
    interlock: [relay1]

binary_sensor:
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: True
    name: "Allow Access"
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.turn_on: relay1
  - platform: gpio
    pin:
      number: 15
      mode: INPUT_PULLUP
      inverted: True
    name: "Stop Access"
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.turn_on: relay2
```

**Logs (if applicable):**

```
1606076960: Socket error on client TrafficLight, disconnecting.
1606076979: New connection from 192.168.2.19 on port 1883.
1606076979: New client connected from 192.168.2.19 as TrafficLight (c1, k15).
1606077879: Socket error on client TrafficLight, disconnecting.
1606077899: New connection from 192.168.2.19 on port 1883.
1606077899: New client connected from 192.168.2.19 as TrafficLight (c1, k15).
1606078319: Saving in-memory database to /data/mosquitto.db.
1606078799: Socket error on client TrafficLight, disconnecting.
1606078818: New connection from 192.168.2.19 on port 1883.
1606078818: New client connected from 192.168.2.19 as TrafficLight (c1, k15).
1606079719: Socket error on client TrafficLight, disconnecting.
1606079738: New connection from 192.168.2.19 on port 1883.
1606079738: New client connected from 192.168.2.19 as TrafficLight (c1, k15).
1606080120: Saving in-memory database to /data/mosquitto.db.
1606080638: Socket error on client TrafficLight, disconnecting.
1606080658: New connection from 192.168.2.19 on port 1883.
1606080658: New client connected from 192.168.2.19 as TrafficLight (c1, k15).
1606081558: Socket error on client TrafficLight, disconnecting.
1606081578: New connection from 192.168.2.19 on port 1883.
1606081578: New client connected from 192.168.2.19 as TrafficLight (c1, k15).
1606081921: Saving in-memory database to /data/mosquitto.db.
1606082478: Socket error on client TrafficLight, disconnecting.
1606082497: New connection from 192.168.2.19 on port 1883.
1606082497: New client connected from 192.168.2.19 as TrafficLight (c1, k15).
```

**Additional information and things you've tried:**

Like #1636. This problem was stable for a few days but then I restarted the router at work (don't know if it's linked) and it's flared up again, but worse than before.
