### ISSUE TITLE
ULN2003 Stepper misstepping when in half step mode

### ISSUE THREAD

**Issue by Fractal147** [esphome/issues#1655]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Builtin ESP webserver

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP12E module, 

**ESPHome version (latest production, beta, dev branch)**

ESPHome 1.14.5

**Affected component:**

Stepper

**Description of problem:**
Stepper set to HALF_STEP mode has misconfigured steps.
It should be A, AB, B, BC, C, CD, D, DA (so 1 pin low, then 2, then 1, then 2...etc)
What it actually does is 
A, **B, AB**, BC, C, CD, D, DA...etc

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
# Example configuration entry
stepper:
  - platform: uln2003
    id: my_stepper
    pin_a: D0
    pin_b: D1
    pin_c: D2
    pin_d: D3
    max_speed: 250 steps/s
    step_mode: HALF_STEP

    # Optional:
    acceleration: inf
    deceleration: inf
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
nothing relevant in the logs...

```

**Additional information and things you've tried:**
uln2003.cpp is at fault.
Line 73: if (i == 0 || i == 2 || i == 7) should be if (i == 0 || i == 1 || i == 7)
