### ISSUE TITLE
Using !secret tag in packages subdirectory not using correct path for secrets.yaml

### ISSUE THREAD

**Issue by shbatm** [esphome/issues#1656]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassos VM with ESPHome Add-on (dev)

**ESP (ESP32/ESP8266, Board/Sonoff):**

Any

**ESPHome version (latest production, beta, dev branch)**

v1.16.0-dev

**Affected component:**

[packages](https://esphome.io/guides/configuration-types.html#packages), but also maybe any include

**Description of problem:**
When including a package file located in a subdirectory (e.g. config/common/) like in the [packages](https://esphome.io/guides/configuration-types.html#packages) example, using `!secret` will look for a `secrets.yaml` file in that directory, rather than the root directory.

**Problem-relevant YAML-configuration entries:**
```yaml
# In device config yaml file:
packages:
  device_base: !include common/device_config.yaml

# In common/device_config.yaml:
wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

```

**Logs (if applicable):**

```
ERROR Error while reading config: Invalid YAML syntax:

Error reading file /config/esphome/common/secrets.yaml: [Errno 2] No such file or directory: '/config/esphome/common/secrets.yaml'
```

**Additional information and things you've tried:**
Flattening the structure or putting a copy of the secrets file in the subdirectory work, but the `!secret` tag
