### ISSUE TITLE
MQTT Subscribe as binary sensor

### ISSUE THREAD

**Issue by jperquin** [esphome/issues#1661]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hassio.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
Wemos D1 Mini Pro

**ESPHome version (latest production, beta, dev branch)**
1.15.3

**Affected component:**
MQTT Subscribe

**Description of problem:**
Trying to pull in online status of another board (also connected via MQTT) and based on whether this is true (online) or false (offline), I want to toggle a switch on this board.

**Problem-relevant YAML-configuration entries:**
```
text_sensor:
#MH_ET_Live status
  - platform: mqtt_subscribe
    name: "test_bridge_status"
    id: bridge_status
    topic: ishr/locatie_6/mh_et_live_6/available
```
```
switch:
  - platform: template
    name: "Bridge Status"
    lambda: !lambda |-
      if (id(bridge_status).state) = online;
      {
        return BRIDGE ONLINE;
      } else {
        return BRIDGE OFFLINE;
      }
```
**Logs (if applicable):**

```
src/main.cpp: In lambda function:
src/main.cpp:454:33: error: expected primary-expression before '=' token
       if (bridge_status->state) = online;
                                 ^
src/main.cpp:454:35: error: 'online' was not declared in this scope
       if (bridge_status->state) = online;

```

**Additional information and things you've tried:**
