### ISSUE TITLE
Compiling file makes crush of all home assistant

### ISSUE THREAD

**Issue by damyano** [esphome/issues#1662]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
esp8266

**ESPHome version (latest production, beta, dev branch)**
1.15.3

**Affected component:**

**Description of problem:**

I can't compile file , when I try , all homeassistant freeze. It crashes after line like in the screen. Hassio version 4.17, system version 0.118.4

![image](https://user-images.githubusercontent.com/67058580/100549946-ac1c5600-3276-11eb-811c-23365e459be6.png)

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

esphome:
  name: esplazienka
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "xxx"
  password: "xxx"
  manual_ip:
    static_ip: x
    gateway: x
    subnet: x
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esplazienka Fallback Hotspot"
    password: "xxx"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxx"

ota:
  safe_mode: True
  password: "xxx"

binary_sensor:
  - platform: gpio
    pin: 
     number: 5
     mode: INPUT_PULLUP
     inverted: False
    name: "Czujnik zalania pod wanna"
sensor:
  - platform: dht
    pin: 14
    model: dht22
    temperature:
      name: "Lazienka - Temperatura"
    humidity:
      name: "Lazienka - Wilgotnosc"
    update_interval: 60s
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
