### ISSUE TITLE
DHT-22 read failure doesn't flash the status_led

### ISSUE THREAD

**Issue by trapper-** [esphome/issues#1666]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
N/A - issue on device

**ESP (ESP32/ESP8266, Board/Sonoff):**
Wemos D1 Mini, but I suspect this is a general issue.

**ESPHome version (latest production, beta, dev branch)**
latest production

**Affected component:**
https://esphome.io/components/sensor/dht.html

**Description of problem:**
When I unplug the sensor I see read failure messages in the log, but there is no indication on the status LED. Status LED is working correctly during startup and network connection.

**Problem-relevant YAML-configuration entries:**
```yaml
status_led:
  pin:
    number: D4
    inverted: true

sensor:
  - platform: dht
    model: DHT22
    pin: D0
    temperature:
      name: "${name} Temperature"
    humidity:
      name: "${name} Humidity"
    update_interval: 10s
```

**Logs (if applicable):**
```
[22:35:01][W][dht:120]: Requesting data from DHT failed!
[22:35:01][W][dht:058]: Invalid readings! Please check your wiring (pull-up resistor, pin number) and consider manually specifying the DHT model using the model option.
```

**Additional information and things you've tried:**
