### ISSUE TITLE
entity_id don't allow for multiple entities

### ISSUE THREAD

**Issue by MrBartusek** [esphome/issues#1672]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io / Wemos D1 Mini (ESP8266)

**ESPHome version (latest production, beta, dev branch)**

v.1.15.3 (latest production)

**Affected component:**

https://esphome.io/components/binary_sensor/gpio.html

**Description of problem:**

While using multiple entities id in service home assistant does is fine

![image](https://user-images.githubusercontent.com/23432278/101243764-ad300600-3702-11eb-8f01-cba48ca03784.png)

But esphome gives an error

![image](https://user-images.githubusercontent.com/23432278/101243771-bc16b880-3702-11eb-870f-e3a1857cdfae.png)

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: gpio
    name: "Button"
    pin:
      number: D1
      mode: INPUT_PULLUP
    on_press:
      then:
        - homeassistant.service:
            service: homeassistant.toggle
            data:
              entity_id: 
              - light.rgb_lamp # Error here
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

The workaround is just calling the same service multiple times but that's less-readable and won't work in all cases
