### ISSUE TITLE
ESP32 does not transmit RF codes

### ISSUE THREAD

**Issue by DieKatzchen** [esphome/issues#1673]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**ESPHome version (latest production, beta, dev branch)**

1.15.3
**Affected component:**

remote-transmitter

**Description of problem:**
RF transmitter never actually transmits on ESP32. I migrated my RF code from an esp8266 to an esp32. I thought I had hooked up the transmitter wrong and was tearing my hair out checking and rechecking the connection until I noticed that the log indicates "[D][switch:021]: 'Projector Down' Turning ON." thus it received the switch command, but there is no "[D][remote_transmitter:066]: Sending remote code..." following it

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
remote_transmitter:
  pin:
    number: RX
    inverted: false
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%
  id: rf
  
switch:
  - platform: template
    name: Projector UP
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '100010110010010110000010'
          protocol: 1
          repeat: 10
          transmitter_id: rf
          
  - platform: template
    name: Projector Down
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '100010110010010110000100'
          protocol: 1
          repeat: 10
          transmitter_id: rf
          
  - platform: template
    name: Projector Stop
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '100010110010010110001000'
          protocol: 1
          repeat: 10
          transmitter_id: rf
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Rolled my docker container back several times. Got all the way to 1.12 before the YAML code was no longer backwards compatible. Same behavior in every version tried.
