### ISSUE TITLE
MAX31855 inaccurate readings

### ISSUE THREAD

**Issue by NobleKangaroo** [esphome/issues#1676]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant addon is installed, but I haven't actually integrated it; using console (`logger:`) to validate readings before I actually add any entities to Home Assistant.

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 - tried both a generic and a NodeMCU

**ESPHome version (latest production, beta, dev branch)**

ESPHome 1.15.3

**Affected component:**

[MAX31855 sensor](https://esphome.io/components/sensor/max31855.html) (thermocouple-to-digital converter)

**Description of problem:**
Temperature readings don't agree with actual temperature, and don't align with Adafruit library readings. In an area, the temperature is currently 25.0°C; ESPHome reports 50.0°C (25.0°C too high)
- When I increase the area's temperature to 34.5°C, ESPHome reports 70.0°C (35.5°C too high)
- Offsetting the temperature in ESPHome by -25.0°C using a filter does result in 25.0°C for the initial temperature; however the increased (34.5°C / 70.0°C) temperature becomes 45.0°C which is still too high
Doesn't appear to be a direct mapping, but might be a result of shifting the bits one too few times (50C >> 1 = 25C, 69C >> 1 = 34.5C, etc).

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: server_room
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

font:
  - id: font_arial_12
    file: "arial.ttf"
    size: 12
  - id: font_arial_16
    file: "arial.ttf"
    size: 16
  - id: font_consola_12
    file: "consola.ttf"
    size: 12
  - id: font_consola_16
    file: "consola.ttf"
    size: 16

i2c:
  scl: GPIO5  # D1 - serial clock
  sda: GPIO4  # D2 - serial data

spi:
  miso_pin: GPIO12  # MAXD0  - receiving bus
  mosi_pin: GPIO13  # unused - sending bus
  clk_pin: GPIO14   # MAXCLK - clock bus

sensor:
  # SPI MAX31855
  - id: sensor_temp
    platform: max31855
    cs_pin: GPIO16  # MAXCS  - chip select (D0 / GPIO16)
    update_interval: 1s
    reference_temperature:
      id: sensor_temp_internal
  # Convert MAX31855 temperature to Fahrenheit
  - id: sensor_temp_f
    platform: template
    lambda: |-
      return (id(sensor_temp).state * 9.0 / 5.0) + 32.0;
    update_interval: 1s
  # Convert MAX31855 internal temperature to Fahrenheit
  - id: sensor_temp_internal_f
    platform: template
    lambda: |-
      return (id(sensor_temp_internal).state * 9.0 / 5.0) + 32.0;
    update_interval: 1s
  # uptime sensor
  - id: sensor_uptime
    internal: true
    platform: uptime
    update_interval: 1s

display:
  # I2C OLED
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    pages:
      - lambda: |-
          it.rectangle(0, 0, 128, 16);
          it.rectangle(0, 16, 128, 48);
          it.print(0, 0, id(font_arial_16), TextAlign::TOP_LEFT, "Hello, world!");
          if (id(sensor_uptime).has_state()) {
            it.printf(0, 16, id(font_consola_12), TextAlign::TOP_LEFT, "Uptime: %.0f", id(sensor_uptime).state);
          }
          if (id(sensor_temp).has_state()) {
            it.printf(0, 28, id(font_consola_12), TextAlign::TOP_LEFT, "Temp: %.1fC %.1fF", id(sensor_temp).state, id(sensor_temp_f).state);
          }
          if (id(sensor_temp_internal).has_state()) {
            it.printf(0, 40, id(font_consola_12), TextAlign::TOP_LEFT, "Internal: %.1fC %.1fF", id(sensor_temp_internal).state, id(sensor_temp_internal_f).state);
          }
          if (id(sensor_temp).has_state()) {
            it.print(0, 52, id(font_consola_12), TextAlign::TOP_LEFT, "XXX");
          }
  # I2C LCD
  - platform: lcd_pcf8574
    dimensions: 20x4
    #address: 0x3F
    address: 0x27
    lambda: |-
      it.print("Hello, world!");
      if (id(sensor_uptime).has_state()) {
        it.printf(0, 1, "Uptime: %.0f", id(sensor_uptime).state);
      }
      if (id(sensor_temp).has_state()) {
        it.printf(0, 2, "Temp: %.1fC %.1fF", id(sensor_temp).state, id(sensor_temp_f).state);
      }
```

**Logs (if applicable):**

The [Adafruit lib](https://github.com/adafruit/Adafruit-MAX31855-library/blob/master/Adafruit_MAX31855.cpp), using the [example sketch](https://github.com/adafruit/Adafruit-MAX31855-library/blob/master/examples/serialthermocouple/serialthermocouple.ino), results in:
```
13:08:07.189 -> Internal Temp = 21.87
13:08:07.223 -> C = 21.00
13:08:07.223 -> F = 69.80
```
The [ESPHome integration](https://github.com/esphome/esphome/blob/dev/esphome/components/max31855/max31855.cpp#L37-L105), using the above YAML, produces (in serial monitor):
```
13:11:05.286 -> [0;36m[D][max31855:066]: Got reference temperature: 44.7500°C[0m
13:11:05.286 -> [0;36m[D][sensor:092]: 'sensor_temp_internal': Sending state 44.75000 °C with 2 decimals of accuracy[0m
13:11:05.286 -> [0;36m[D][max31855:102]: Got thermocouple temperature: 41.00°C[0m
13:11:05.286 -> [0;36m[D][sensor:092]: 'sensor_temp': Sending state 41.00000 °C with 1 decimals of accuracy[0m
13:11:05.554 -> [0;36m[D][sensor:092]: 'sensor_temp_internal_f': Sending state 112.55000  with 1 decimals of accuracy[0m
13:11:05.655 -> [0;36m[D][sensor:092]: 'sensor_temp_f': Sending state 105.80000  with 1 decimals of accuracy[0m
```

**Additional information and things you've tried:**
Working on debugging this by putting the source into a custom component and making changes/fixes as necessary.
