### ISSUE TITLE
Delay and asynchronous code

### ISSUE THREAD

**Issue by blademckain** [esphome/issues#168]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**
Sonoff 4ch Pro

**Affected component:**
https://esphome.io/components/binary_sensor/index.html

**Description of problem:**
During the execution of a lambda function, no other event is perceived.
The lambda function should stop when I release the button but the sonoff does not detect any other event while it is performing the lambda function. And therefore it doesn't even notice that I released the button

**Problem-relevant YAML-configuration entries:**
```yaml
globals:
   - id: my_global_float
     type: float
     restore_value: yes
     initial_value: '0.5'

 binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  name: "Sonoff 4CH Button 1"
  id: btn1
  on_multi_click:
	- timing:
    		- ON for at least 0.6s
  	   then:
    		- logger.log: "Single Long Clicked"
		- lambda: |-
			while(id(btn1).state){
	    			id(my_global_float) += 0.1;
            			id(blue_led).set_level(id(my_global_float));
				delay(1000);
			}
	- timing:
    		- ON for at most 0.5s
  	   then:
    		- logger.log: "Single Short Clicked"


output:
- platform: esp8266_pwm
  id: blue_led
  pin: GPIO13
  inverted: True

```

**Additional information and things you've tried:**
is there a possibility to perform a lambda function asynchronously?
