### ISSUE TITLE
OTA stopped working. Error: Finishing update failed.

### ISSUE THREAD

**Issue by davida72** [esphome/issues#1684]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**Home Assistant OS / Wemos D1 Pro**

**ESPHome version (latest production from Home Assistant Add On Manager**

**Affected component:**

I've been able to compile and upload via USB and OTA was working fine previously but I've done something that's stopped it working. I've tried reinstalling ESPHome on Home Assistant, I've rebuilt new firmware, I've added and removed the device from Home Assistant. I can't see anything useful in the logs. 

I can control everything fine from Home Assistant and USB upload of firmware works fine. It's just OTA that's broken. The log shows that it’s OTA port is open. 

Any idea why I'm no longer able to upload my firmware OTA?

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: nullo
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: "timor"
  password: "password"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.86.69
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.86.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tunnelleds Fallback Hotspot"
    password: "IxFsIotrRrSE"

light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO2
    num_leds: 50
    rgb_order: RGB
    name: "FastLED WS2811 Light"
    effects:
      - addressable_rainbow:


captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

```

**Logs (if applicable):**

```
INFO Reading configuration /config/esphome/nullo.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/nullo
Processing nullo (board: d1_mini_pro; framework: arduino; platform: espressif8266@2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 16MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.7
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <FastLED> 3.3.2
|   |-- <SPI> 1.0
|   |-- <EspSoftwareSerial> 6.8.5
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Retrieving maximum program size /data/nullo/.pioenvs/nullo/firmware.elf
Checking size /data/nullo/.pioenvs/nullo/firmware.elf
RAM:   [====      ]  44.7% (used 36632 bytes from 81920 bytes)
Flash: [====      ]  39.8% (used 416192 bytes from 1044464 bytes)
========================= [SUCCESS] Took 11.60 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 192.168.86.69
INFO Uploading /data/nullo/.pioenvs/nullo/firmware.bin (420352 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
ERROR Error Update end: Error: Finishing update failed. See the MQTT/USB logs for more information.

```
