### ISSUE TITLE
On_loop runs during safe mode

### ISSUE THREAD

**Issue by alexyao2015** [esphome/issues#1686]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**ESPHome version (latest production, beta, dev branch)**

ESPHome 1.16.0-dev
**Affected component:**

OTA

**Description of problem:**
The code contained in on_loop is ran even when safe mode has been started. Any bad code that is in on_loop will not be protected by safe mode. On_loop should be isolated from running until OTA has a chance to initialize.

This code here results in an infinite bootloop, when we should expect it to bootloop 10 times before entering safe mode.

Doing the same thing using `interval` does not result in this issue occurring.

If this is intended, maybe put a warning in the documentation mentioning this or remove on_loop altogether in favor of interval instead.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: a
  platform: ESP8266
  board: esp01_1m
  on_loop:
    then:
      - lambda: 'ESP_LOGD("main", "I am at execution number %s", 10);' # just test code that will definitely crash the ESP

wifi:
  ssid: "a"
  password: "a"
  ap:
    ssid: "A Fallback Hotspot"
    password: "a"

captive_portal:

logger:

api:

ota:

web_server:
  port: 80
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
