### ISSUE TITLE
ESPHome not connecting to SSID with spaces

### ISSUE THREAD

**Issue by rpvelloso** [esphome/issues#1694]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):*pip* 

**ESP (ESP32/ESP8266, Board/Sonoff):*esp01* 

**ESPHome version (latest production, beta, dev branch)*v1.15.0*

**Affected component:*WIFI*

**Description of problem:*ESPHome does not connects to an SSID with spaces. I have 3 APs, two have spaces in the SSIDs and ESPHome does not connect on these two APs, only to the AP with no spaces in the SSID. I have supplied only one AP at a time to test it. I've tested all SSIDs with Tasmota and works fine with the three APs (so the problem is not in the ESP01 board, but in the firmware)*

**Problem-relevant YAML-configuration entries:**
```yaml
wifi:
  ssid: "Casa"
  password: "thisSSIDworksFine"

wifi:
  ssid: "Casa Sala"
  password: "thisSSIDdoesNot"
```

**Logs (if applicable):**

```
no logs :(

```

**Additional information and things you've tried:**

**Comment by rradar** [comment]
not sure but did you already tried something like this @rpvelloso ?

```yaml
wifi:
  ssid: "Casa%20Sala"
  password: "doesThisSSDnowWORK?"
```
