### ISSUE TITLE
OTA causing brick

### ISSUE THREAD

**Issue by yovio** [esphome/issues#1699]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Official docker image (esphome/esphome)

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (TYWE2S module in Feit Smart Dimmer)

**ESPHome version (latest production, beta, dev branch)**

v1.15.3

**Affected component:**

OTA

**Description of problem:**

Flashing esphome fw over serial always working fine and able to unbrick the module.

1st OTA after serial flashing also working fine, module are able to boot up and back online
Subsequent OTA will causing brick module, unable to boot.

TYWE2S module de-soldered from device and connected only VCC and Ground.

Log message while performing OTA always said successful OTA but the module unable to boot.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: dining_room_dimmer
  platform: ESP8266
  board: esp01_1m

#Put your home network info here
wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dining Room Dimmer"
    password: ""

captive_portal:

#web_server:
#  port: 80
  
# Make sure logging is not using the serial port
logger:
  baud_rate: 0
  level: VERBOSE
  
# Enable Home Assistant API
api:

# Make sure you can upload new firmware OTA
ota:

# My dimmer used the hardware serial port on the alternate pins
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Make the light
light:
  - platform: "tuya"
    name: "dining_dimmer"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 0
    max_value: 1000

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
