### ISSUE TITLE
ESPHome version and Wifi Info text sensor cannot have state_topic changed

### ISSUE THREAD

**Issue by AlexDanault** [esphome/issues#170]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Command line.

**ESP (ESP32/ESP8266, Board/Sonoff):**

Esp8266

**Affected component:**

ESPHome Version and Wifi Info text sensors

**Description of problem:**
The ESPHome version and Wifi Info text sensors cannont have their state_topic changed, it causes a compilation error.

**Problem-relevant YAML-configuration entries:**
```yaml
text_sensor:
  - platform: version
    name: ESPHome Version
    id: version
    state_topic: devices/habitat_chambre_alex.local/esphome_version
  - platform: wifi_info
    ip_address:
      name: WiFi IP Address
      id: wifi_ip_address
      state_topic: devices/habitat_chambre_alex.local/wifi_ip
    ssid:
      name: Wifi SSID
      id: wifi_ssid
      state_topic: devices/habitat_chambre_alex.local/wifi_ssid
```

**Traceback (if applicable):**

```
Compiling .pioenvs\habitat_chambre_alex\src\main.cpp.o
src\main.cpp: In function 'void setup()':
src\main.cpp:67:23: error: request for member 'set_custom_state_topic' in 'version->esphome::text_sensor::VersionTextSensor::<anonymous>.esphome::text_sensor::TextSensor::get_mqtt()', which is of pointer type 'esphome::text_sensor::MQTTTextSensor*' (maybe you meant to use '->' ?)
version->get_mqtt().set_custom_state_topic("devices/habitat_chambre_alex.local/esphome_version");
^
src\main.cpp:68:31: error: request for member 'set_custom_state_topic' in 'wifi_ip_address->esphome::text_sensor::IPAddressWiFiInfo::<anonymous>.esphome::text_sensor::TextSensor::get_mqtt()', which is of pointer type 'esphome::text_sensor::MQTTTextSensor*' (maybe you meant to use '->' ?)
wifi_ip_address->get_mqtt().set_custom_state_topic("devices/habitat_chambre_alex.local/wifi_ip");
^
src\main.cpp:69:25: error: request for member 'set_custom_state_topic' in 'wifi_ssid->esphome::text_sensor::SSIDWiFiInfo::<anonymous>.esphome::text_sensor::TextSensor::get_mqtt()', which is of pointer type 'esphome::text_sensor::MQTTTextSensor*' (maybe you meant to use '->' ?)
wifi_ssid->get_mqtt().set_custom_state_topic("devices/habitat_chambre_alex.local/wifi_ssid");
^
*** [.pioenvs\habitat_chambre_alex\src\main.cpp.o] Error 1
```

**Additional information and things you've tried:**
