### ISSUE TITLE
Condition with sun and time check (via lambda) not working as expected

### ISSUE THREAD

**Issue by hgregorian** [esphome/issues#1701]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

1.15.3

**Affected component:**

Not really component necessarily.  Conditions?  https://esphome.io/guides/automations.html#and-condition

**Description of problem:**
I've got a couple of these light switches and the goal is to use the existing status LED as a nightlight between 10 PM and sunrise.  If no lights are on or all have been turned off, I want the nightlight to turn on and if any lights are turned on, I want the nightlight to turn off.   The nightlight does turn on at 10 PM when no lights are on, and turns off if any light is turned on.  However, when all lights are turned off, the nightlight does not turn on.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: esp_light_switch2_01
  upper_devicename: "Main Bathroom"
  wifi_fast_connect: 'false'

esphome:
  name: $devicename
  comment: "Main Bathroom"
  platform: ESP8266
  board: esp01_1m

<<: !include common/common_no_status_led.yaml
<<: !include common/sensors.yaml
<<: !include common/logger.yaml

time:
  - platform: homeassistant
    id: ha_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 22
        then:
          if:
            condition:
              and:
                - light.is_off: mirror_light
                - light.is_off: light_and_fan
            then:
              light.turn_on: nightlight
        

sun:
  latitude: Y
  longitude: X
  on_sunrise:
    - then:
        - light.turn_off: nightlight

binary_sensor:
- !include common/binary_sensor/status.yaml
- platform: gpio
  id: button_1
  pin:
    number: GPIO3
    mode: INPUT_PULLUP
    inverted: True
  on_press:
    - light.toggle: mirror_light
- platform: gpio
  id: button_2
  pin:
    number: GPIO12
    mode: INPUT_PULLUP
    inverted: True
  on_press:
    - light.toggle: light_and_fan

output:
  - platform: gpio
    id: gpio0
    pin: GPIO0
    inverted: True
  - platform: gpio
    id: relay_1
    pin: GPIO13
  - platform: gpio
    id: relay_2
    pin: GPIO4

light:
  - platform: binary
    id: nightlight
    name: "$upper_devicename Nightlight"
    output: gpio0
  - platform: binary
    id: light_and_fan
    name: "$upper_devicename Main Light and Fan"
    output: relay_1
    on_turn_on:
      - light.turn_off: nightlight
    on_turn_off:
      if:
        condition:
          and:
            - light.is_off: mirror_light
            - sun.is_below_horizon:
            - lambda: 'return (id(ha_time).now().hour > 22);'
        then:
          - light.turn_on: nightlight
  - platform: binary
    id: mirror_light
    name: "$upper_devicename Mirror Light"
    output: relay_2
    on_turn_on:
      - light.turn_off: nightlight
    on_turn_off:
      if:
        condition:
          and:
            - light.is_off: light_and_fan
            - sun.is_below_horizon:
            - lambda: 'return (id(ha_time).now().hour > 22);'
        then:
          - light.turn_on: nightlight

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

I've tested the condition in on_turn_off by using only one of (and not both as represented in my yaml): lambda (checking if before 10 PM), sun.is_below_horizon, and the behavior seems ok. So I'm thinking this is either a bug where the two cannot coexist or a complete misunderstanding of a limitation on my part.
