### ISSUE TITLE
RC Transmitter not working because sync signal is output AFTER the code. Patch added!

### ISSUE THREAD

**Issue by M95D** [esphome/issues#1704]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip3 on ubuntu server
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 on M5Stick-C
**ESPHome version (latest production, beta, dev branch)**

1.15.3
**Affected component:**

RF Transmitter

**Description of problem:**
RF Transmitter doesn't work. There are numerous other bugs reports, none describe this exact problem.
RF Transmitter outputs sync signal AFTER the code, not before. Signal bits are in the correct order.
I found out by looking at a signal recording with RTL-SDR.

**Problem-relevant YAML-configuration entries:**
```yaml
remote_transmitter:
 pin: GPIO0
 carrier_duty_percent: 100%

switch:
  - platform: template
    name: "Shades Up"
    turn_on_action:
      remote_transmitter.transmit_rc_switch_raw:
        code: '0001101000110001100010110100000000010001'
        protocol:
          pulse_length: 360
          sync: [14,4]
          one: [2,1]
          zero: [1,2]

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
