### ISSUE TITLE
Simple Cathode LED Error

### ISSUE THREAD

**Issue by cwberardi** [esphome/issues#1714]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**

Arguably not a bug, but no matter what I try in my config file I cannot get esphome to light a basic cathode LED.  I have checked the voltage of the pin output which show I am getting a signal.  Does anyone have a working schematic and code where they are turning on/off a single cathode LED?

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: bedroom_sensor
  platform: ESP8266
  board: 
  
packages:
  wifi: !include wifi.yaml

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: True

sensor:
  - platform: adc
    pin: A0
    name: "Bedroom Ambient Light"
    update_interval: 120s
  - platform: htu21d
    temperature:
      name: "Bedroom Temperature"
      id: htu21d_temp
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
        - offset: -2.0
      unit_of_measurement: "°F"
    humidity:
      name: "Bedroom Humidity"
      id: htu21d_humidity
    update_interval: 120s
  - platform: sgp30
    eco2:
      name: "Bedroom eCO2"
      accuracy_decimals: 1
    tvoc:
      name: "Bedroom TVOC"
      accuracy_decimals: 1
    update_interval: 120s
    compensation:
      temperature_source: htu21d_temp
      humidity_source: htu21d_humidity
  - platform: wifi_signal
    name: "Bedroom Sensor WiFi Signal"
    update_interval: 120s

binary_sensor:
  - platform: gpio
    pin: GPIO12
    name: "PIR Sensor"
    device_class: motion
    on_press:
      then:
        - light.turn_on: single_led
    on_release:
      then:
        - light.turn_off: single_led
  - platform: status
    name: "Bedroom Sensor Status"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: Bedroom Sensor IP Address
    ssid:
      name: Bedroom Sensor SSID
    mac_address:
      name: Bedroom Sensor Mac Wifi Address

light:
  - platform: binary
    name: "LED"
    output: gpio_led
    id: single_led

output:
  - platform: binary
    pin: GPIO16
    id: gpio_led

switch:
  - platform: restart
    name: "Bedroom Sensor Restart"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret esp_ota

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I've tried multiple pins on my D1 mini as well as multiple LEDs and resistors, nothing has yielded light.
