### ISSUE TITLE
wait_time incorrect in 433MHz remote_transmitter

### ISSUE THREAD

**Issue by Erriez** [esphome/issues#1718]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip3

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

Version: 1.15.3

**Affected component:**

remote_transmitter

**Description of problem:**

`wait_time` is incorrect between packets.

I have a KaKu (Klik aan / Klik uit) device with a very simple timing. It requires **5ms +/- 5%** between repeats, otherwise the command is ignored. Setting `wait_time` to 4ms results in 13ms between two packets and that's the reason why KaKu does not work.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: kaku
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "ssid"
  password: "password"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "password"

ota:
  password: "password"

remote_transmitter:
  pin: D1
  carrier_duty_percent: 100%

switch:
  - platform: template
    name: Kaku B On Button
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '00100100100001100000010001010'
          protocol:
            pulse_length: 300
            zero: [1, 3]
            one: [3, 1]
          repeat:
            times: 4
            wait_time: 4ms

```

**Logs (if applicable):**

Timing measured with `wait_time: 4ms`:

![KaKuRepeatTimeIncorrect](https://user-images.githubusercontent.com/8849873/103010269-531fa500-4538-11eb-9cf7-ab31784b12a1.png)

**Additional information and things you've tried:**

* Logic Analyzer is the evidence for non-working timing.
* Works fine with an Arduino UNO:

```c++
void rfTx(const char *data)
{
    char c;
    uint8_t i;

    for (uint8_t r = 0; r < 4; r++) {
        i = 0;
        while (data[i] != NULL) {
            c = data[i++];

            if (c == '1') {
                PORTD |= (1<<2);
                delayMicroseconds(950);
                PORTD &= ~(1<<2);
                delayMicroseconds(350);
            } else {
                PORTD |= (1<<2);
                delayMicroseconds(300);
                PORTD &= ~(1<<2);
                delayMicroseconds(1000);
            }
        }
        delay(4);
    }
}

void setup() 
{
    DDRD |= (1<<2);

    // Klik aan Klik uit B on
    rfTx("00100100100001100000010001010");
    
    delay(2000);
    
    // Klik aan Klik uit B off
    rfTx("00100100010100011100110101010");
}

void loop() {
}
```

Correct timing Arduino UNO:

![KaKuRepeatTimeCorrectArduinoUNO](https://user-images.githubusercontent.com/8849873/103010541-ccb79300-4538-11eb-8dcc-a160c95f871d.png)

With instrumented code `remote_transmitter_esp8266.cpp`:

```c++
void RemoteTransmitterComponent::send_internal(uint32_t send_times, uint32_t send_wait) {
  ESP_LOGD(TAG, "Sending remote code...");
  uint32_t on_time, off_time;
  this->calculate_on_off_time_(this->temp_.get_carrier_frequency(), &on_time, &off_time);

  ESP_LOGD(TAG, "carrier_frequency: %u", this->temp_.get_carrier_frequency());
  ESP_LOGD(TAG, "send_times: %u", send_times);
  ESP_LOGD(TAG, "on_time: %u", on_time);
  ESP_LOGD(TAG, "off_time: %u", off_time);
  ESP_LOGD(TAG, "send_wait: %u us", send_wait);

  InterruptLock lock;
  for (uint32_t i = 0; i < send_times; i++) {
    {
      for (int32_t item : this->temp_.get_data()) {
        if (item > 0) {
          const auto length = uint32_t(item);
          ESP_LOGD(TAG, "mark_: %u us", length);
          this->mark_(on_time, off_time, length);
        } else {
          const auto length = uint32_t(-item);
          ESP_LOGD(TAG, "space_: %u us", length);
          this->space_(length);
        }
        App.feed_wdt();
      }
    }

    if (i + 1 < send_times) {
      ESP_LOGD(TAG, "send_wait: %u us", send_wait);
      delay_microseconds_accurate(send_wait);
    }
  }
}
```

The last `space_` timing is too long:

```
[17:30:19][D][switch:021]: 'Kaku B On Button' Turning ON.
[17:30:19][D][remote_transmitter:066]: Sending remote code...
[17:30:19][D][remote_transmitter:070]: carrier_frequency: 0
[17:30:19][D][remote_transmitter:071]: send_times: 4
[17:30:19][D][remote_transmitter:072]: on_time: 0
[17:30:19][D][remote_transmitter:073]: off_time: 0
[17:30:19][D][remote_transmitter:074]: send_wait: 4000 us
[17:30:19][D][remote_transmitter:082]: mark_: 300 us
[17:30:19][D][remote_transmitter:086]: space_: 900 us
...
[17:30:20][D][remote_transmitter:082]: mark_: 300 us
[17:30:20][D][remote_transmitter:086]: space_: 900 us
[17:30:20][D][remote_transmitter:082]: mark_: 300 us
[17:30:20][D][remote_transmitter:086]: space_: 9300 us  <====   9300 us must be 900 us!
[17:30:20][D][remote_transmitter:094]: send_wait: 4000 us
```

This seems to be the root cause.

**Comment by Erriez** [comment]
Found the solution: The default is `sync: [1, 31]` which results in an additional pulse at the end of the frame and 9300 us spacing before the `wait_time`.

The timing for my device must be < 5%, otherwise the commands are ignored.

With a protocol analyzer I was able to generate the following code:
```yaml
remote_transmitter:
  pin: D1
  carrier_duty_percent: 100%

switch:
  - platform: template
    name: Kaku B On Button
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '00100100100001100000010001010'
          protocol:
            pulse_length: 90
            sync: [0, 0]
            zero: [3, 10]
            one: [9, 3]
          repeat:
            times: 4
            wait_time: 4100us
  - platform: template
    name: Kaku B Off Button
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '00100100010100011100110101010'
          protocol:
            pulse_length: 90
            sync: [0, 0]
            zero: [3, 10]
            one: [9, 3]
          repeat:
            times: 4
            wait_time: 4100us
```
