### ISSUE TITLE
MQTT persistence? (or am I missing a point?)

### ISSUE THREAD

**Issue by jeanfabrice** [esphome/issues#1719]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Eclipse Mosquitto 2020.12.1

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP WROOM 32

**ESPHome version (latest production, beta, dev branch)**
1.15.3

**Affected component:**

https://esphome.io/components/mqtt.html

**Description of problem:**
Messages posted to MQTT topic during deep_sleep are not processed at wake-up.

**Problem-relevant YAML-configuration entries:**
```yaml
mqtt:
  broker: mqtt.local
  username: esp32
  password: <redacted>
  topic_prefix: homeassistant/esp32
  discovery_prefix: discovery
 
deep_sleep:
  run_duration: 10s
  sleep_duration: 20s
  id: deep_sleep_1

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I would like my esp32 to process messages received in the subscribed topic while being asleep.
My goal is to build a cover switch, powered on battery, so taking advantages of deep_sleep capacity. Esp32 will be in deep_sleep 20s and run 10s. If I ask for cover closing during sleep time, I would like it to close the cover as soon as it wakes up.

Looking at this guide <http://www.steves-internet-guide.com/mqtt-clean-sessions-example/>, my understanding it that in order to process messages received while being disconnected, mqtt client has to use `clean_session=False` to ask for persistence on broker side.

ESPhome is using  [Paho mqtt client](https://github.com/eclipse/paho.mqtt.python) and does not seem to provide any specifics regarding `clean_session` : <https://github.com/esphome/esphome/blob/dev/esphome/mqtt.py#L46>.

When clean_session is not set, it defaults to `None` on Paho side, and `None` equals `True`: <https://github.com/eclipse/paho.mqtt.python/blob/v1.5.1/src/paho/mqtt/client.py#L554>

So my understanding is that esphome is not using persistent connection to the MQTT broker and there is currently no way to set it. Is that correct? Since I'm very new to esphome/hass.io, am I missing something?
