### ISSUE TITLE
Infrared receive does not recognize any protocol

### ISSUE THREAD

**Issue by Erriez** [esphome/issues#1720]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip3

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 mini lite and NodeMCU

**ESPHome version (latest production, beta, dev branch)**

Version: 1.15.3

**Affected component:**

remote_receiver

**Description of problem:**

Infrared transmit/receive verification with a protocol analyzer shows:
* Correct data on transmit infrared LED pin (including 38kHz carrier).
* Correct timing on IR receiver pin from ESP8266 infrared transmitter and remote controller.
* ESP8266 infrared receiver pin shows correct timing (Max 1% deviation).
* No protocols recognized by receiver with `dump: all`.

**Problem-relevant YAML-configuration entries:**

**ESP8266 Infrared transmitter with Samsung TV CH1 code:**
```yaml
esphome:
  name: samsung_tx
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "ssid"
  password: "password"

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: Samsung
    turn_on_action:remote_receiver
      remote_transmitter.transmit_samsung:
        data: 0xE0E020DF
```

**ESP8266 Infrared receiver:**
```yaml
esphome:
  name: samsung_rx
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: "ssid"
  password: "password"

# Enable Home Assistant API
api:
  password: "otaupdate"

ota:
  password: "otaupdate"

remote_receiver:
  pin: 
    number: D1
    inverted: True
  dump: all
  tolerance: 80%
  idle: 20ms
  buffer_size: 2kb
```

**Logs (if applicable):**

Infrared TX (ESP8266 Mini Lite or remote control) and Infrared RX (to ESP8266 NodeMCU) signal:

![InfraredTxRxSamsungCH1](https://user-images.githubusercontent.com/8849873/103099384-8e8ca300-460e-11eb-9ee8-6485588fc22b.png)

**Transmit:**
```
[17:32:09][D][switch:021]: 'Samsung' Turning ON.
[17:32:09][D][remote_transmitter:066]: Sending remote code...
```

**Receive (RAW) timing OK, no Samsung protocol displayed:***
```
[17:32:09][D][remote.raw:028]: Received Raw: -4475, 4513, -572, 1695, -572, 1695, -572, 1694, -572, 564, -573, 537, -599, 565, -572, 535, -601, 537, -600, 1694, -572, 1696, -572, 1694, -574, 563, -572, 537, -600, 564, -572, 564, -572, 564, -573, 564, -572, 564, -572, 1695, -572, 564, 
[17:32:09][D][remote.raw:041]:   -572, 564, -573, 565, -572, 564, -572, 565, -573, 1666, -601, 1695, -572, 538, -598, 1695, -572, 1695, -572, 1694, -573, 1694, -573, 1694, -572
```

**Receive (RAW) reformatted for readability:**
```
Received Raw: 
Start: 4475, 4513,
0xE0: -572, 1695, -572, 1695, -572, 1694, -572, 564, -573, 537, -599, 565, -572, 535, -601, 537, 
0xE0: -600, 1694, -572, 1696, -572, 1694, -574, 563, -572, 537, -600, 564, -572, 564, -572, 564, 
0x20: -573, 564, -572, 564, -572, 1695, -572, 564, -572, 564, -573, 565, -572, 564, -572, 565, 
0xDF: -573, 1666, -601, 1695, -572, 538, -598, 1695, -572, 1695, -572, 1694, -573, 1694, -573, 1694, 
Stop: -572
```

**remote_base/samsung_protocol.cpp timing configuration seems to be correct:**
```c++
static const uint8_t NBITS = 32;
static const uint32_t HEADER_HIGH_US = 4500;
static const uint32_t HEADER_LOW_US = 4500;
static const uint32_t BIT_HIGH_US = 560;
static const uint32_t BIT_ONE_LOW_US = 1690;
static const uint32_t BIT_ZERO_LOW_US = 560;
static const uint32_t FOOTER_HIGH_US = 560;
static const uint32_t FOOTER_LOW_US = 560;
```

Even with 80% allowed deviation, the Samsung protocol is not recognized by the receiver.

**Additional information and things you've tried:**

* I also tried to connect two ESP's directly and did not make sense.
* I also tried a different protocol such as:

```yaml
remote_transmitter.transmit_jvc:
  data: 0x1234
```

**Comment by Erriez** [comment]
**Found the solution:** 

`tolerance: 80%` of the infrared receiver does not work. Removing this line changes the tolerance to default tolerance of 25% which is sufficient.

Working receiver yaml:

```yaml
remote_receiver:
  pin: 
    number: D1
    inverted: True
  dump: all
  idle: 20ms
  buffer_size: 2kb
```

Correct expected output:

```
[21:46:39][D][remote.samsung:055]: Received Samsung: data=0xE0E020DF
[21:48:05][D][remote.samsung:055]: Received Samsung: data=0xE0E030CF
```
