### ISSUE TITLE
Total Daily Energy Sensor

### ISSUE THREAD

**Issue by quazzie** [esphome/issues#173]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff POW

**Affected component:**

[total_daily_energy](https://esphome.io/components/sensor/total_daily_energy.html)
[time](https://esphome.io/components/time.html)

**Description of problem:**
The help for [Total Daily Energy Sensor](https://esphome.io/components/sensor/total_daily_energy.html) states that if a time component is present it resets at midnight.
This worked some versions ago (can't remember which). But according to the source it now resets yearly.

To sneak in a feature request in this bug-report i would suggest a customizable timeframe for resets.
one sensor resets daily, and one every month for example.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: total_daily_energy
    name: tot_energy_day
    power_id: my_power
    unit_of_measurement: kWh

time:
  - platform: sntp
    id: my_time
    timezone: "Europe/Stockholm"
    servers:
      - 192.168.1.42
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
