### ISSUE TITLE
ESP-12 keeps rebooting when not logging - but works fine while logging

### ISSUE THREAD

**Issue by Jojo-A** [esphome/issues#1737]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant 0.118.4 (not relevant to this issue)

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 ESP-12 on NodeMCU Dev Board

**ESPHome version (latest production, beta, dev branch)**

1.15.3

**Affected component:**

something in the core?!

**Description of problem:**
Very basic setup: nothing but a pulse counter and a filter.
When I upload the config OTA or via serial, everything works fine, which means the the sensor for pulse counter gets filtered correctly and reaches the expected value after the expected time BUT ONLY while I am connected to the board for logging (keeping the terminal window open).
NOW: when I close the terminal from where I uploaded the config, the board seems to reboot after some time and keeps rebooting after ~15 minutes or so. This can be seen in the filtered sensor value, which gets reset over and over again.
I strongly guess, that this is related to the problem described here: https://github.com/esphome/esphome-core/issues/394 which has not been solved as how I understand it...

![Bildschirmfoto vom 2021-01-03 15-02-18](https://user-images.githubusercontent.com/33325587/103480453-c77a0400-4dd4-11eb-96ea-72181190ce9b.png)
The graphic shows:
- the boards seems to reboot until ~13:05
- at ~13:05 I re-uploaded the config OTA without applying any changes
- terminal window kept open until ~ 13:40
- at 13:40 I closed the terminal window from where I uploaded the config
- at ~14:00 the board reboots and keeps hanging in this circle... 
This is totally reproducible.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: geigercounter
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "WiFi SSID"
  password: "verysecretwifipassword"


captive_portal:

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: xxx.xxx.xxx.xxx
  username: username
  password: verysecretpassword

sensor:
  - platform: pulse_counter
    pin: D2
    unit_of_measurement: 'µSv/h'
    name: 'radiation'
    update_interval: 60s
    filters:
      - multiply: 0.00812
      - offset: -0.087696
      - exponential_moving_average:
          alpha: 0.0667
          send_every: 1
    state_topic: "sensor/geigercounter"
    retain: True

```

**Logs (if applicable):**

```
I can not provide any logs of the error event, because it works while I am staying connected to it. It only reboots when I disconnect... :(

```

**Additional information and things you've tried:**
- different logging levels -> no change
- different filter configs -> no change
- different boards (!) -> no change
- with or w/o webserver -> no change
- with or w/o MQTT discovery -> no change
