### ISSUE TITLE
TCS34725 color temperature algorithm wrong. Better one available.

### ISSUE THREAD

**Issue by kolins-cz** [esphome/issues#1740]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Latest esphome and HomeAssistant (as of 5th January 2021)

**ESP (ESP32/ESP8266, Board/Sonoff):**

Generic ESP32 but is does not matter
**ESPHome version (latest production, beta, dev branch)**

 1.15.3
**Affected component:**

TCS34725

**Description of problem:**
Function for calculating color temperature for this sensor is now deprecated in Adafruit library as it was found to produce wrong values.
https://github.com/esphome/esphome/blob/3ee6348e41f31b293e2a7d61c8f896b55acba519/esphome/components/tcs34725/tcs34725.cpp#L94

Adafruit lib provides newer function based on manufacturers white paper. It should provide better results.
https://github.com/adafruit/Adafruit_TCS34725/blob/6dc42834bd071aeb94bdddff7e17cb662de20ad2/Adafruit_TCS34725.cpp#L418

Here are some references to mentioned issue:
https://github.com/adafruit/Adafruit_TCS34725/issues/21
https://github.com/letscontrolit/ESPEasy/issues/3453

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
 - platform: tcs34725
    red_channel:
      name: "Weather Station Red Channel"
    green_channel:
      name: "Weather Station Green Channel"
    blue_channel:
      name: "Weather Station Blue Channel"
    clear_channel:
      name: "Weather Station Clear Channel"
    illuminance:
      name: "Weather Station Illuminance (TCS34725)"
    color_temperature:
      name: "Weather Station Color Temperature"
    gain: 1x
    integration_time: 50ms
    address: 0x29
    update_interval: 10s
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

Also illuminance values are way off. I have two different sensors next to TCS34725. They are more or less similar but TCS is wrong by orders of magnitude. Also you can see how wrong is temperature. 
![image](https://user-images.githubusercontent.com/8409715/103622726-63bc1c00-4f37-11eb-854b-011c351b8b4a.png)
