### ISSUE TITLE
AM2320 doesn't work by default

### ISSUE THREAD

**Issue by soostdijck** [esphome/issues#1741]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
"Home assistant OS" running in a LXC container" (which in turn is running esphome in a docker container)

**ESP (ESP32/ESP8266, Board/Sonoff):**
NodeMCU v2 (ESP8266)

**ESPHome version (latest production, beta, dev branch)**
1.15.3

**Affected component:**
AM2320

**Description of problem:**
When connecting a AM2320 (temperature and humidity sensor) via I2C there are some issues getting it to work. The problem can be reproduced like this:
* Connect a AM2320 to a NodeMCU (with esphome)
* (cold)Boot the NodeMCU and the AM2320 isn't found with the following error: `[E][am2320:065]: Communication with AM2320 failed!`. The sensor won't be working at all.
* Hit the reset button on the NodeMCU and the sensor starts working.
*Side not, the I2C bus reports no devices found in either situation.

**Problem-relevant YAML-configuration entries:**
The workaround:
Add a `setup_priority: -100` to the sensor yaml config, like this and it starts working on a cold boot as well:
```yaml
sensor:
  - platform: am2320
    setup_priority: -100
    address: 0x5C
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
```

**Logs (if applicable):**
Any of the above solutions keep on saying this, which doesn't seem to cause harm:
```
[W][i2c:070]: Received NACK on transmit of address 0x5C
```

**Additional information and things you've tried:**
n/a
