### ISSUE TITLE
Esphome in docker on RPi4 (64 bit raspbian) cannot compile

### ISSUE THREAD

**Issue by mef-hamburg** [esphome/issues#1745]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker on RPi4 in 64bit, Raspian
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 and ESP8266
**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**
Cannot compile, resulting in error

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: "esp32_kitchen"

<<: !include common_includes/common_esp32_devkitc_v1.yaml

 
esp32_ble_tracker:
  scan_parameters:
     active: true


sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: 'c4:7c:8d:6a:75:28'
    temperature:
      name: "Hochbeet Temperature"
    moisture:
      name: "Hochbeet Moisture"
    illuminance:
      name: "Hochbeet Illuminance"
    conductivity:
      name: "Hochbeet Conductivity"
#    battery_level:
#      name: "Hochbeet Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: "xxxxx"
    bindkey: "xxxxxx"
    temperature:
        name: "Kitchen Temperature"
    humidity:
        name: "kitchen Humidity"

```

**Logs (if applicable):**

```
INFO Reading configuration /config/esp32_kitchen.yaml...
/usr/local/lib/python3.6/dist-packages/tzlocal/unix.py:158: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn('Can not find any timezone configuration, defaulting to UTC.')
INFO Detected timezone 'UTC' with UTC offset 0
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esp32_kitchen
Processing esp32_kitchen (board: esp32doit-devkit-v1; framework: arduino; platform: espressif32@1.12.4)
--------------------------------------------------------------------------------
PackageManager: Installing toolchain-xtensa32 @ ~2.50200.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
toolchain-xtensa32 @ 2.50200.80 has been successfully installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10004.200129 (1.0.4) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa32 2.50200.80 (5.2.0)
Looking for AsyncTCP-esphome library in registry
LibraryManager: Installing id=6798 @ 1.1.1
AsyncTCP-esphome @ 1.1.1 has been successfully installed!
Looking for ESPAsyncWebServer-esphome library in registry
LibraryManager: Installing id=6758 @ 1.2.7
ESPAsyncWebServer-esphome @ 1.2.7 has been successfully installed!
Looking for ESPAsyncTCP-esphome library in registry
LibraryManager: Installing id=6757
ESPAsyncTCP-esphome @ 1.2.3 has been successfully installed!
Looking for AsyncTCP-esphome library in registry
LibraryManager: Installing id=6798
AsyncTCP-esphome @ 1.1.1 has been successfully installed!
Looking for ArduinoJson-esphomelib library in registry
LibraryManager: Installing id=3837 @ 5.13.3
ArduinoJson-esphomelib @ 5.13.3 has been successfully installed!
Dependency Graph
|-- <AsyncTCP-esphome> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.7
|   |-- <AsyncTCP-esphome> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
Compiling .pioenvs/esp32_kitchen/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling .pioenvs/esp32_kitchen/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/esp32_kitchen/src/esphome/components/api/api_pb2_service.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
sh: 1: xtensa-esp32-elf-g++: not found
*** [.pioenvs/esp32_kitchen/src/esphome/components/api/api_connection.cpp.o] Error 127
Compiling .pioenvs/esp32_kitchen/src/esphome/components/api/api_server.cpp.o
*** [.pioenvs/esp32_kitchen/src/esphome/components/api/api_pb2.cpp.o] Error 127
*** [.pioenvs/esp32_kitchen/src/esphome/components/api/api_pb2_service.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [.pioenvs/esp32_kitchen/src/esphome/components/api/api_server.cpp.o] Error 127
========================= [FAILED] Took 70.90 seconds =========================


```

**Additional information and things you've tried:**

tried different docker images, including esphome/esphome-hassio-aarch64:latest and esphome/esphome-aarch64:latest
on these two esphome doesn't seem to run at all.
esphome runs only with esphome/esphome:latest image
