### ISSUE TITLE
Climate Thermostat setpoint issue 

### ISSUE THREAD

**Issue by AalianKhan** [esphome/issues#1751]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 mini
**ESPHome version (latest production, beta, dev branch)**

V1.15.3
**Affected component:**

https://esphome.io/components/climate/thermostat.html

**Description of problem:**
I have set up a wemos D1 mini with an OLED screen, 2 touch buttons and other components to work as a HVAC thermostat. I have everything set up and works as expected. 

I have set it up in which when the current mode is heating, use the 2 buttons to set the target low temperature up or down and when the current mode is cooling then use the 2 buttons to set the target high temperature up or down. 

It works as expected in the heat mode. it moves the target low temperature up or down depending on which button is pressed and moves the target temperature high if it comes in the way. For example, target low is currently 22 and target high is currently 22 and the button used to increase the target is pressed then it sets both target high and target low to 23. 

However, this is not the same behaviour when the mode is set to cool. It moves the target high correctly but it doesn't move the target low temperature when it's in the way. For example, the target high is 22 and the target low is 22. Since the mode is on cooling it should move target high only. when the button is pressed to decrease the temperature it doesn't move the target high and target low to 21 but instead does nothing. 

**Problem-relevant YAML-configuration entries:**
```yaml
# Buttons
binary_sensor:
  - platform: gpio
    id: b1
    pin: D3
    on_press:
      then:
        - if:  # If on the main page, switch to target temperature page
            condition: 
              lambda: 'return id(currentPG).state == "mainPG";'
            then:
              - display.page.show: targetTempPG
              - component.update: oled
              - text_sensor.template.publish: 
                  id: currentPG
                  state: "targetTempPG"
              - script.execute: displayTimeout
            else:
              - if: # If on the target temp page and mode is set to heat
                  condition: 
                    lambda: 'return id(currentPG).state == "targetTempPG" && id(myClimate).mode == CLIMATE_MODE_HEAT;'
                  then:
                    - script.stop: displayTimeout
                    - climate.control:
                        id: myClimate
                        target_temperature_low: !lambda 'return id(myClimate).target_temperature_low + 1;'
                    - component.update: oled
                    - script.execute: displayTimeout
                  else:
                    - if: # If on the target temp page and mode is set to cool
                        condition: 
                          lambda: 'return id(currentPG).state == "targetTempPG" && id(myClimate).mode == CLIMATE_MODE_COOL;'
                        then:
                          - script.stop: displayTimeout
                          - climate.control:
                              id: myClimate
                              target_temperature_high: !lambda 'return id(myClimate).target_temperature_high + 1;'
                          - component.update: oled
                          - script.execute: displayTimeout
                    
  - platform: gpio
    id: b2
    pin: D4
    on_press:
      then:
        - if:  # If on the main page, switch to target temperature page
            condition: 
              lambda: 'return id(currentPG).state == "mainPG";'
            then:
              - display.page.show: targetTempPG
              - component.update: oled
              - text_sensor.template.publish: 
                  id: currentPG
                  state: "targetTempPG"
              - script.execute: displayTimeout
            else:
              - if: # If on the target temp page and mode is set to heat
                  condition: 
                    lambda: 'return id(currentPG).state == "targetTempPG" && id(myClimate).mode == CLIMATE_MODE_HEAT;'
                  then:
                    - script.stop: displayTimeout
                    - climate.control:
                        id: myClimate
                        target_temperature_low: !lambda 'return id(myClimate).target_temperature_low - 1;'
                    - component.update: oled
                    - script.execute: displayTimeout
                  else:
                    - if: # If on the target temp page and mode is set to cool
                        condition: 
                          lambda: 'return id(currentPG).state == "targetTempPG" && id(myClimate).mode == CLIMATE_MODE_COOL;'
                        then:
                          - script.stop: displayTimeout
                          - climate.control:
                              id: myClimate
                              target_temperature_high: !lambda 'return id(myClimate).target_temperature_high - 1;'
                          - component.update: oled
                          - script.execute: displayTimeout

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

This can easily be fixed with this if statement but considering that it worked as expected in heat mode without the need to put anything extra I felt the need to report this.
```yaml
- climate.control:
    id: myClimate
    target_temperature_high: !lambda 'return id(myClimate).target_temperature_high - 1;'
    target_temperature_low: !lambda |-
        if (id(myClimate).target_temperature_high == id(myClimate).target_temperature_low){
            return id(myClimate).target_temperature_low - 1;
        } else {
            return id(myClimate).target_temperature_low;
        }
```
