### ISSUE TITLE
MCP9808 documentation: [temperature] is an invalid option for [sensor.mcp9808]

### ISSUE THREAD

**Issue by tvwerkhoven** [esphome/issues#1755]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Built from source

**ESP (ESP32/ESP8266, Board/Sonoff):**

N/A

**ESPHome version (latest production, beta, dev branch)**

v1.16.0b2

**Affected component:**

MCP9808 (no docs since dev branch)

**Description of problem:**
The temperature option listed in the doc raises an error and seems superfluous, as it's a temperature-only sensor (like Dallas)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp_mobile
  platform: ESP8266
  board: d1_mini_pro

wifi:
  redacted

logger:
  baud_rate: 0

api:
  reboot_timeout: 0s

ota:

mqtt:
  redacted

uart:
  - id: myuart0 # SDS pm2.5/pm10
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 9600
  - id: myuart1 # MH-z19B CO2
    rx_pin: GPIO12 # GPIO3 = RX hardware
    tx_pin: GPIO13 # GPIO1 = TX hardware
    baud_rate: 9600

i2c:
  sda: 4
  scl: 5
  scan: True

sensor:
  - platform: sds011
    redacted
  - platform: wifi_signal
    redacted
  - platform: uptime
    redacted
  - platform: mhz19
    redacted
  - platform: mcp9808
    temperature:
      name: "MCP Temperature"
    update_interval: 30s
    state_topic: influx/environv3/quantity/T/source/mcp9808/board/esp_mobile/location/home/room/guestoffice/value/state
  - platform: bme280
    redacted
```

**Logs (if applicable):**

```
not applicable
```

**Additional information and things you've tried:**

<img width="706" alt="Screenshot 2021-01-11 at 12 28 34" src="https://user-images.githubusercontent.com/78742/104177112-9323ca80-5408-11eb-8b63-7276f835a049.png">
