### ISSUE TITLE
Using Softserial with ESP-32 Dev Kit C V4

### ISSUE THREAD

**Issue by it-guy92** [esphome/issues#1757]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io on RaspberryPi 4

ESP-32 Dev Kit C V4

**ESPHome version (latest production, beta, dev branch)**
v1.15.3

**Affected component:**

https://esphome.io/components/uart.html

**Description of problem:**
Hey,
i can only use the first two assigned uart ports. My Idea is to use Hardware Serial for uart1 and uart2. And for uart3, uart4 Softserial.

If i try to send data via uart3 or uart4 it wont work. Receiving on uart3 or uart4 also won't work.

I test it with an Oscilloscope and an USB Serial Adapter on my MacBook with screen (Terminal). Of course i swapped rx/tx already.

My wiring is fine. For testing i commented uart1 and uart2 out. Now uart3 and uart4 are working.
Is there an problem with Software Serial?

I used this example: https://esphome.io/components/text_sensor/uart.html

**Problem-relevant YAML-configuration entries:**
```yaml


esphome:
  name: esp32_a
  platform: ESP32
  board: esp-wrover-kit
  includes:
      - uart_read_line_sensor.h

wifi:
  networks:
  - ssid: "#########"
    password: "#########"
  - ssid: "#########"
    password: "#########"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Wohnmobil Fallback Hotspot"
    password: "#########"

captive_portal:

# Enable logging
logger:
  level: VERY_VERBOSE #makes uart stream available in esphome logstream
  logs:
    uart_esp32: VERY_VERBOSE
    i2c: DEBUG
    scheduler: DEBUG
    sensor: DEBUG
    sensor.filter: DEBUG
    api: DEBUG
    api.service: DEBUG
  baud_rate: 0 #disable logging over uart
  
# Enable Home Assistant API
api:

ota:

uart:
  - id: uart1
    tx_pin: GPIO27
    rx_pin: GPIO36
    baud_rate: 9600
  - id: uart2
    tx_pin: GPIO33
    rx_pin: GPIO39
    baud_rate: 9600
  - id: uart3
    tx_pin: GPIO25
    rx_pin: GPIO34
    baud_rate: 9600
  - id: uart4
    tx_pin: GPIO26
    rx_pin: GPIO35
    baud_rate: 9600
  
text_sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart1));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: "uart_readline1"
    name: "uart_readline1"

- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart2));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: "uart_readline2"
    name: "uart_readline2"

- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart3));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: "uart_readline3"
    name: "uart_readline3"

- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart4));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: "uart_readline4"
    name: "uart_readline4"
```

**Logs (if applicable):**

```
Logs are at VERY_VERBOSE but just shows nothing if i try to receive on uart3 or uart4.
```

**Additional information and things you've tried:**
Swapping RX/TX
Commenting out uart1 and uart2, now uart3 and uart4 are working.
Checking my wiring
Taking measurements with my Oscilloscope
Connecting direct on GPIO pins without any other wiring
