### ISSUE TITLE
Restore mode doesn't work after a few reboots

### ISSUE THREAD

**Issue by Mastiffen** [esphome/issues#1762]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Node-RED/MQTT, programming in ESPhome command line on Pi

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**ESPHome version (latest production, beta, dev branch)**

latest productions
**Affected component:**

https://esphome.io/components/switch/gpio.html

**Description of problem:**
I have a quad relay card connected to an ESP-WROOM-32 from Aliexpress that I need to remember the settings for the four pins I'm using. When I program it, after a few reboots (it doesn't matter if it's power pull or the reboot switch) it stops saving the mode of the pins, and it will be stuck on every reboot on the last setting that it actually did save. If I re-program it, the process will start again, and I get a few more saves before it's stuck. My test YAML is very simple:

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: madmaxhekk
  platform: ESP32
  board: esp32dev

wifi:
  ssid: ""
  password: ""

captive_portal:

# Enable logging
#logger:

ota:

mqtt:
  broker: 192.168.3.1
  topic_prefix: madmax/esp/madmaxhekk
  reboot_timeout: 5min

switch:
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "rele1"
    pin: 12
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "rele2"
    pin: 4
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "rele3"
    pin: 27
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "rele4"
    pin: 26
  - platform: restart
    name: "omstart"
    id: omstart
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I have tried to program the boards as a few different board versions, like esp32dev and esp32doit-devkit-v1, but that doesn't change anything. I have also of course tried different boards, I have 6 and I have testet with 3 of them, all have the exact same problem. The board is this: 
https://www.aliexpress.com/item/32996463686.html
