### ISSUE TITLE
ESPhome ver1.17.0-dev fails to compile

### ISSUE THREAD

**Issue by KixMan28** [esphome/issues#1763]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Version | 2021.1.2
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.79-v7
CPU Architecture | armv7l

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, board ESP8285
**ESPHome version (latest production, beta, dev branch)**

v1.17.0-dev
**Affected component:**

https://esphome.io/devices/esp8266.html

**Description of problem:**
I try to compile my configuration for the BW-SHP6 smart socket, but the compilation fails:
````
Linking /data/ironing_plug/.pioenvs/ironing_plug/firmware.elf
Building /data/ironing_plug/.pioenvs/ironing_plug/firmware.bin
Retrieving maximum program size /data/ironing_plug/.pioenvs/ironing_plug/firmware.elf
Checking size /data/ironing_plug/.pioenvs/ironing_plug/firmware.elf
RAM:   [=====     ]  47.8% (used 39140 bytes from 81920 bytes)
Flash: [====      ]  42.9% (used 439400 bytes from 1023984 bytes)
/usr/bin/python3: can't open file '/root/.platformio/packages/framework-arduinoespressif8266/tools/elf2bin.py': [Errno 2] No such file or directory
*** [/data/ironing_plug/.pioenvs/ironing_plug/firmware.bin] Error 2
========================= [FAILED] Took 309.24 seconds =========================
````

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  plug_name: ironing_plug
  friendly_name: Ironing Plug
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "890"

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret esphome_ssid2
  password: !secret esphome_pwd2
  manual_ip:
    static_ip: 192.168.1.151
    gateway: !secret esphome_gateway
    subnet: !secret esphome_subnet


# Enable logging
logger:

# Enable Web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: ''

ota:
  password: ''

time:
  - platform: homeassistant
    id: homeassistant_time
    
binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO13
      inverted: True
    on_press:
      - switch.toggle: relay
    name: "${friendly_name} button"
        
switch:
- platform: gpio
  name: "${friendly_name}"
  id: relay
  pin: GPIO15
  on_turn_on:
    - switch.turn_on: "${plug_name}_LED_Blue"
  on_turn_off:
    - switch.turn_off: "${plug_name}_LED_Blue"
    - switch.turn_off: "${plug_name}_LED_Red"
- platform: gpio
  internal: true
  name: "${friendly_name} LED Blue"
  id: "${plug_name}_LED_Blue"
  pin: GPIO2
  inverted: True
- platform: gpio
  name: "${friendly_name} LED Red"
  internal: true
  id: "${plug_name}_LED_Red"
  pin: GPIO0
  inverted: True
sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${friendly_name} Current"
      unit_of_measurement: 'A'
      accuracy_decimals: 3
    voltage:
      name: "${friendly_name} Voltage"
      unit_of_measurement: 'V'
    power:
      name: "${friendly_name} Power"
      unit_of_measurement: 'W'
      id: "${plug_name}_Power"
      on_value_range:
        - above: 1.0
          then:
            - switch.turn_on: "${plug_name}_LED_Red"
        - below: 1.0
          then:
            - switch.turn_off: "${plug_name}_LED_Red"
    change_mode_every: 8
    update_interval: 5s
  - platform: total_daily_energy
    name: "${friendly_name} Total Daily Energy"
    power_id: "${plug_name}_Power"
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh

# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: '${friendly_name} Uptime'
    unit_of_measurement: days
    update_interval: 600s
    filters:
      - multiply: 0.000011574
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
In the current working ver1.15.3 I can compile the same code without issues.
