### ISSUE TITLE
Problem with compilation - ESP32

### ISSUE THREAD

**Issue by HouseSimOn** [esphome/issues#1768]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**ESPHome version (latest production, beta, dev branch)**

v1.15.3
**Affected component:**

**Description of problem:**
I've created, with configuration tool, new ESPHome node. Then, I wanted to compile SW to download bin file. I've get following error.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: bt_bridge2
  platform: ESP32
  board: mhetesp32devkit

wifi:
  ssid: "XXX"
  password: "XXX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bt_Bridge2"
    password: "XXX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
INFO Reading configuration /config/esphome/bt_bridge2.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/bt_bridge2
Processing bt_bridge2 (board: mhetesp32devkit; framework: arduino; platform: espressif32@1.12.4)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10004.200129 (1.0.4) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa32 2.50200.80 (5.2.0)
Dependency Graph
|-- <AsyncTCP-esphome> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.7
|   |-- <AsyncTCP-esphome> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
Compiling /data/bt_bridge2/.pioenvs/bt_bridge2/FrameworkArduino/esp32-hal-adc.c.o
Compiling /data/bt_bridge2/.pioenvs/bt_bridge2/FrameworkArduino/esp32-hal-bt.c.o
cc1: internal compiler error: Illegal instruction
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
cc1: internal compiler error: Illegal instruction
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
Compiling /data/bt_bridge2/.pioenvs/bt_bridge2/FrameworkArduino/esp32-hal-cpu.c.o
cc1: internal compiler error: Illegal instruction
*** [/data/bt_bridge2/.pioenvs/bt_bridge2/FrameworkArduino/esp32-hal-adc.c.o] Error 1
*** [/data/bt_bridge2/.pioenvs/bt_bridge2/FrameworkArduino/esp32-hal-bt.c.o] Error 1
Compiling /data/bt_bridge2/.pioenvs/bt_bridge2/FrameworkArduino/esp32-hal-dac.c.o
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
*** [/data/bt_bridge2/.pioenvs/bt_bridge2/FrameworkArduino/esp32-hal-cpu.c.o] Error 1
cc1: internal compiler error: Illegal instruction
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
*** [/data/bt_bridge2/.pioenvs/bt_bridge2/FrameworkArduino/esp32-hal-dac.c.o] Error 1
========================= [FAILED] Took 105.74 seconds =========================
```

**Additional information and things you've tried:**
I've tried to delete build files - without result. With ESP8266 everything works fine. I have ESP32 nodes - added a few weeks ago - and then it was compiled without errors. Now, I have problems also with old nodes.
