### ISSUE TITLE
Dallas one Wire Not recognizing Sensor when using I2c

### ISSUE THREAD

**Issue by craighaehnel** [esphome/issues#1771]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
Chip Family: ESP32
Chip Model: ESP32D0WDQ5 (revision 1)
Number of Cores: 2
Max CPU Frequency: 240MHz
Has Bluetooth: YES
Has Embedded Flash: NO
Has Factory-Calibrated ADC: YES

esp32-wrover-b-ipx-8mb

**ESPHome version (latest production, beta, dev branch)**
Current version: 1.15.3

**Affected component:**

**Description of problem:**
The dallas one wire sensor works untill I add spi to the the yaml. The id is no longer found after this and no temperature data is given yaml works with i2c and io expander.
i have tried diffrent sensors and other IO pins also.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: boilcon
  platform: ESP32
  board:  esp32dev

wifi:
  ssid: "*******"
  password: "******"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Boilcon Fallback Hotspot"
    password: "*****"

captive_portal:

# Enable logging
logger: 
 level: VERY_VERBOSE

# Enable Home Assistant API
api:
  password: "****"

ota:
  password: "***"
  
  
  
dallas:
  - pin: 23
  
spi:
  miso_pin: 33
  clk_pin: 32
  id: bus_A  
  
  
  
sensor:
  - platform: dallas
    address:  0x030000064DA28528
    name: "onewiretestsesor"

  
 

 
  
    
  - platform: max6675
    name: "hightempsens1"
    cs_pin: 25
    update_interval: 15s
  - platform: max6675 
    name: "hightempsens2"
    cs_pin: 26
    update_interval: 15s
```

**Logs (if applicable):**
Part of log file:
[20:44:28][C][spi:081]: SPI bus:
[20:44:28][C][spi:082]: CLK Pin: GPIO32 (Mode: OUTPUT)
[20:44:28][C][spi:083]: MISO Pin: GPIO33 (Mode: INPUT)
[20:44:28][C][spi:085]: Using HW SPI: YES
[20:44:28][C][logger:185]: Logger:
[20:44:28][C][logger:186]: Level: VERY_VERBOSE
[20:44:28][C][logger:187]: Log Baud Rate: 115200
[20:44:28][C][logger:188]: Hardware UART: UART0
[20:44:28][C][max6675:025]: MAX6675 'hightempsens1'
[20:44:28][C][max6675:025]: Unit of Measurement: '°C'
[20:44:28][C][max6675:025]: Accuracy Decimals: 1
[20:44:28][C][max6675:025]: Icon: 'mdi:thermometer'
[20:44:28][C][max6675:026]: CS Pin: GPIO25 (Mode: OUTPUT)
[20:44:28][C][max6675:027]: Update Interval: 15.0s
[20:44:28][C][max6675:025]: MAX6675 'hightempsens2'
[20:44:28][C][max6675:025]: Unit of Measurement: '°C'
[20:44:28][C][max6675:025]: Accuracy Decimals: 1
[20:44:28][C][max6675:025]: Icon: 'mdi:thermometer'
[20:44:28][C][max6675:026]: CS Pin: GPIO26 (Mode: OUTPUT)
[20:44:28][C][max6675:027]: Update Interval: 15.0s
[20:44:28][C][dallas.sensor:072]: DallasComponent:
[20:44:28][C][dallas.sensor:073]: Pin: GPIO23 (Mode: INPUT)
[20:44:28][C][dallas.sensor:074]: Update Interval: 60.0s
[20:44:28][W][dallas.sensor:077]: Found no sensors!
[20:44:28][C][dallas.sensor:087]: Device 'onewiretestsesor'
[20:44:28][C][dallas.sensor:087]: Unit of Measurement: '°C'
[20:44:28][C][dallas.sensor:087]: Accuracy Decimals: 1
[20:44:28][C][dallas.sensor:087]: Icon: 'mdi:thermometer'
[20:44:28][V][dallas.sensor:087]: Unique ID: 'dallas-030000064DA28528'
[20:44:28][C][dallas.sensor:095]: Address: 0x030000064DA28528
[20:44:28][C][dallas.sensor:096]: Resolution: 12
[20:44:28][C][captive_portal:169]: Captive Portal:
[20:44:28][C][ota:029]: Over-The-Air Updates:
[20:44:28][C][ota:030]: Address: boilcon.local:3232
[20:44:28][C][ota:032]: Using Password.
[20:44:28][C][api:095]: API Server:
[20:44:28][C][api:096]: Address: boilcon.local:6053
[20:44:31][VV][api.service:192]: on_hello_request: HelloRequest {
[20:44:31] client_info: 'Home Assistant 2021.1.4'
[20:44:31]}
[20:44:31][V][api.connection:588]: Hello from client: 'Home Assistant 2021.1.4 (192.168.254.30)'
[20:44:31][VV][api.service:012]: send_hello_response: HelloResponse {
[20:44:31] api_version_major: 1
[20:44:31] api_version_minor: 3
[20:44:31] server_info: 'boilcon (esphome v1.15.3)'
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

lso there was a compiler warning, Not being much of a programmer I don't no if its needed here it is.

"Compiling /data/boilcon/.pioenvs/boilcon/FrameworkArduino/esp32-hal-ledc.c.o
Compiling /data/boilcon/.pioenvs/boilcon/FrameworkArduino/esp32-hal-matrix.c.o
/root/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-i2c.c: In function 'i2cDumpFifo':
/root/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-i2c.c:415:35: warning: ' ' flag used with '%X' gnu_printf format [-Wformat=]
} else k += sprintf(&buf[k],"% 4X ",fifoBuffer[i]);
^
/root/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-i2c.c:415:35: warning: ' ' flag used with '%X' gnu_printf format [-Wformat=]
Compiling /data/boilcon/.pioenvs/boilcon/FrameworkArduino/esp32-hal-misc.c.o
Compiling /data/boilcon/.pioenvs/boilcon/FrameworkArduino/esp32-hal-psram.c.o

Hopefully This is the proper place for this issue. If not could you guys direct me to a forum For ESPHOME ?

This setup currently worked on wroom32 board with no problems this was the proto
I have tried pin 14 and 23 with one wire 
Using powered mode for buss
same results with any one wire temp sensor i have tried

The esp is currently on a custom pcb hydronic booiler control board other pins are in use.

pin map 
io22 i2c
io21 i2c
io32 sck1
io33 so1
io25 cs 1
io26 cs 2
io27 sl 1
io23 onewire  will have seven or more sensors
 mcp23017: mcp23017_hub in use     controling 8 relays and 8 inputs
2 x  max6675

any help to get these devices working together is Greatly appropriated
thanks 
Sorry about the wrong title 
should be 
"Dallas one Wire Not recognizing Sensor when adding  spi to yaml"
