### ISSUE TITLE
Costco Feit Smart Dimmer stops responding to commands

### ISSUE THREAD

**Issue by ic3man5** [esphome/issues#1776]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
HA

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (TYWE2S)
Intertek 5014010

See here for more details: https://community.home-assistant.io/t/costco-feit-smart-dimmer-tuya-convert-tasmota/151390

**ESPHome version (latest production, beta, dev branch)**
1.15.3

**Affected component:**
Tuya Dimmer

**Description of problem:**
I have 8 of these dimmers all flashed with ESPHOME firmware with the YAML script below. Issue I've found is the secondary chip connected to the ESP8266 stops responding to commands sent from the ESP8266. The ESP8266 can still read the state of the dimmer when physically changing the brightness/state. I suspect the secondary chip can't handle the UART traffic quick enough and the secondary chip's UART controller overflows and isn't smart enough to recover from it. 

**Problem-relevant YAML-configuration entries:**
```esphome:
  name: dimmer
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "asdf"
  password: "asdf"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dimmer 1 Fallback Hotspot"
    password: "dUg1c33SV9mg"

captive_portal:

# Make sure logging is not using the serial port
logger:
  baud_rate: 0
  level: NONE

# Enable Home Assistant API
api:
  password: "asdf"

ota:
  password: "asdf"

# My dimmer used the hardware serial port on the alternate pins
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Make the light
light:
  - platform: "tuya"
    name: "dimmer1"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 0
    max_value: 1444




```

**Logs (if applicable):**

**Additional information and things you've tried:**

I believe if I can figure out how to add a parameter to the YAML config and have `void Tuya::send_command_()` delay on each byte sent this would fix it. I'm not familiar enough with the code yet to be able to modify anything. I'd like to add a yaml parameter `serial_tx_delay_ms: 1` that is configurable (defaults to 0).

```
# Register the Tuya MCU connection
tuya:
 # Delay in between each byte
 serial_tx_delay_ms: 1
 # Delay at the end of the command sent (needs a better name)
 serial_tx_cmd__delay_ms: 50

# Make the light
light:
  - platform: "tuya"
    name: "dimmer1"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 0
    max_value: 1444
```

**Comment by ic3man5** [comment]
I made some initial changes here, I have yet to compile them or test them (Still have no idea how to do that currently - Next on my list of things to learn here).

https://github.com/ic3man5/esphome/commit/64ea6dc4140497dbdf5b2f561d02c2f59cda506d

**Comment by ic3man5** [comment]
I managed to get this working, it works better but I'm not completely happy with it. Seems its masking some bigger problem underneath. Extending the delays too long makes the initial problem even worse, but a 100us delay in-between bytes seems to help.

This leads me to believe there is some "race" condition going on here (not sure if ESPHome uses interrupts/thread/etc) or the baudrate isn't exactly 9600 like it should be.

```
# Register the Tuya MCU connection
tuya:
  serial_byte_delay_us: 100
  serial_command_delay_us: 10
```

I found removing this return here https://github.com/esphome/esphome/blob/dev/esphome/components/tuya/tuya.cpp#L263 makes the issue worse also. I'm not 100% sure what is going on yet as I don't have a full understanding of ESPHome or the tuya code (assuming someone reverse engineered it somewhere).
