### ISSUE TITLE
on_boot automation does not work together with ledc

### ISSUE THREAD

**Issue by tilman** [esphome/issues#1784]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip/vscode

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32

**ESPHome version (latest production, beta, dev branch)**
latest

**Affected component:**
ledc, on_boot

**Description of problem:**
Access to the ledc output in an on_boot automation with prio greater 400 will crash the ESP. Would be nice to include this in the syntax check or at least a big warning in the doc. Was hard to figure out what the problem was. 

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: demo
  platform: ESP32
  board: esp-wrover-kit
  on_boot:
    priority: 400
    then:
      - output.turn_off: demo_pwm

output:
  - platform: ledc
    pin: 4
    id: demo_pwm
```
