### ISSUE TITLE
RGBW light color correction through max_power has no effect

### ISSUE THREAD

**Issue by baracoder** [esphome/issues#1791]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

"MagicHome" LED controller with esp8285

**ESPHome version (latest production, beta, dev branch)**

v1.15.3

**Affected component:**

light rgbw https://esphome.io/components/light/rgbw.html
output config https://esphome.io/components/output/index.html#config-output

**Description of problem:**
An RGBW light strip has blue tint. [Color correction](https://esphome.io/components/light/rgbw.html#color-correction) refers to setting `max_power` for individual outputs to correct. Setting different values does not affect light color, when setting rgb to white through home assistant.
![Screenshot from 2021-01-26 01-06-14](https://user-images.githubusercontent.com/127523/105781334-b5722800-5f72-11eb-96a8-308e564437b7.png)
 

**Problem-relevant YAML-configuration entries:**
```yaml
output:
  - platform: esp8266_pwm
    pin: GPIO14
    id: pwm_r
  - platform: esp8266_pwm
    pin: GPIO5
    id: pwm_g
    max_power: 0.85
  - platform: esp8266_pwm
    pin: GPIO12
    id: pwm_b
    max_power: 0.7
  - platform: esp8266_pwm
    pin: GPIO13
    id: pwm_w

light:
  - platform: rgbw
    id: strip
    name: ${upper_name_1}
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
    default_transition_length: 300ms
```

**Logs (if applicable):**

```
[D][light:287]:   Red=100%, Green=85%, Blue=71% <-- used those values for calibration
[D][light:287]:   Red=100%, Green=100%, Blue=100%  <- set to middle of color wheel in home assistant
```

**Additional information and things you've tried:**
