### ISSUE TITLE
CGG1 BLE function shows two of three random parameters then unit randomly reboots

### ISSUE THREAD

**Issue by DayRunner131** [esphome/issues#1796]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Operating a BLE hub for Xiaomi CGG1 devices to transmit values via MQTT to HomeAssistant

Running ESPHOME v1.16.0b6 on HomeAssistant version core-2021.1.5

**ESP (ESP32/ESP8266, Board/Sonoff):**

Issue exists on two different ESP32 boards so I do not suspect this is a board related issue.
Either KeeYees ESP32-WROOM-32 or Adafruit Huzzah32 are being tested.

**ESPHome version (latest production, beta, dev branch)**

v1.16.0b6

Also tried v1.15.0 previously.

**Affected component:**

https://esphome.io/components/sensor/xiaomi_ble.html

**Description of problem:**

Upon startup, ESP32 will discover CGG1 and start capturing two of three parameters. Either Temp & Humidity or Humidity & Battery charge. After about 5 minutes, ESP32 will reboot and then fail to locate CGG1 and display no parameters. Unit also fails to reconnect to Homeassistant.

There will also be times when on startup, it will see the MAC address of the CGG1 but not see transmitted information.

NOTE: CGG1 is always within 24 inches of ESP module for testing.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

substitutions:
# Change the disp_name to something you want  
  disp_name: BLE Node
# Interval of how often the power is updated
#  update_time: 10s
  
esphome:
  name: blenode
  platform: ESP32
  board: featheresp32

wifi:
  ssid: "XXXXX"
  password: "XXXXXX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Upstairs Ble Fallback Hotspot"
    password: "XXXXXXX"

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.XX.X
    gateway: 192.168.XX.X
    subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API

mqtt:
  broker: 192.168.x.x
  username: XX
  password: XXXXXX
  discovery: true

ota:

web_server:
  port: 80

esp32_ble_tracker:

sensor:
  - platform: xiaomi_cgg1
    mac_address: "58:2D:34:10:71:51"
    temperature:
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      name: "Ethan's Temperature"
    humidity:
      name: "Ethan's Humidity"
    battery_level:
      name: "Ethan's Battery Level"
  
time:
  - platform: sntp
    id: sntp_time    
    
switch:
  - platform: restart
    name: ${disp_name} Restart 
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

[D][sensor:092]: 'Ethan's Temperature': Sending state 67.46000 °F with 1 decimals of accuracy
[D][sensor:092]: 'Ethan's Humidity': Sending state 44.10000 % with 1 decimals of accuracy
[D][sensor:092]: 'Ethan's Humidity': Sending state 44.10000 % with 1 decimals of accuracy
[D][xiaomi_ble:302]: Got Xiaomi CGG1 (58:2D:34:10:71:51):
[D][xiaomi_ble:305]:   Temperature: 19.7°C
[D][sensor:092]: 'Ethan's Temperature': Sending state 67.46000 °F with 1 decimals of accuracy
[D][sensor:092]: 'Ethan's Temperature': Sending state 67.46000 °F with 1 decimals of accuracy
[D][xiaomi_ble:302]: Got Xiaomi CGG1 (58:2D:34:10:71:51):
[D][xiaomi_ble:305]:   Temperature: 19.7°C
[D][xiaomi_ble:308]:   Humidity: 44.1%
[D][sensor:092]: 'Ethan's Temperature': Sending state 67.46000 °F with 1 decimals of accuracy
[D][sensor:092]: 'Ethan's Humidity': Sending state 44.10000 % with 1 decimals of accuracy
[I][ota:046]: Boot seems successful, resetting boot loop counter.
[D][esp32_ble_tracker:148]: Starting scan...
[D][esp32_ble_tracker:544]: Found device FA:B4:6A:6D:79:14 RSSI=-75
[D][esp32_ble_tracker:565]:   Address Type: PUBLIC
[D][esp32_ble_tracker:544]: Found device 40:5B:D8:81:13:D4 RSSI=-81
[D][esp32_ble_tracker:565]:   Address Type: PUBLIC

OR....

D][xiaomi_ble:302]: Got Xiaomi CGG1 (58:2D:34:10:71:51):
[D][xiaomi_ble:311]:   Battery Level: 87%
[D][sensor:092]: 'Ethan's Battery Level': Sending state 87.00000 % with 0 decimals of accuracy
[D][xiaomi_ble:302]: Got Xiaomi CGG1 (58:2D:34:10:71:51):
[D][xiaomi_ble:311]:   Battery Level: 87%
[D][sensor:092]: 'Ethan's Battery Level': Sending state 87.00000 % with 0 decimals of accuracy
[I][ota:046]: Boot seems successful, resetting boot loop counter.
[D][esp32_ble_tracker:148]: Starting scan...
[D][esp32_ble_tracker:544]: Found device 63:9F:09:72:41:5B RSSI=-63
[D][esp32_ble_tracker:565]:   Address Type: RANDOM
[D][esp32_ble_tracker:569]:   TX Power: 2
[D][esp32_ble_tracker:544]: Found device FA:B4:6A:6D:79:14 RSSI=-81
[D][esp32_ble_tracker:565]:   Address Type: PUBLIC
```

**Additional information and things you've tried:**
