### ISSUE TITLE
pcf8575 no work pin10-17

### ISSUE THREAD

**Issue by pafftis** [esphome/issues#1799]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
home assistent 2020.01.01

**ESP (ESP32/ESP8266, Board/Sonoff):**
esp8266 Lua

**ESPHome version (latest production, beta, dev branch)**
1.15.3

**Problem-relevant YAML-configuration entries:**
```yaml
i2c:
  sda: D4
  scl: D5
  scan: True
  id: bus_a
pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: True

```
iam use pcf8575 module
no work pin 10-15
pin 0-9 work
