### ISSUE TITLE
No log output on Shelly1. Device does not seem to boot.

### ISSUE THREAD

**Issue by jeroenterheerdt** [esphome/issues#180]
After flashing shelly1 (`esphome xxx run`) no output is shown. Output from `esphome xxx logs` is empty too. Device does not seem to boot.

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows, Python27
**ESP (ESP32/ESP8266, Board/Sonoff):**

Shelly1
**Affected component:**

**Description of problem:**
No output from serial port. Device does not seem to boot as it does not claim a IP.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: frontdoorlight
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: xxx
  password: xxxxx

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'xxxx'

ota:
  password: 'xxxx'

switch:
  - platform: gpio
    name: "Front Door Light"
    pin: 5
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
I have tried two devices, reconnecting. I have checked en re-checked the ssid and wifi password.
