### ISSUE TITLE
Not clear how to turn on wifi conditionally

### ISSUE THREAD

**Issue by jbrepogmailcom** [esphome/issues#1800]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HA on RasPi, plus ESPHome on ESP8266
**ESP (ESP32/ESP8266, Board/Sonoff):**

generic
**ESPHome version (latest production, beta, dev branch)**

latest available
**Affected component:**

wifi

**Description of problem:**
It is not clear from documentation if wifi and mqtt communication can be turned on conditionally, e.g. when sensor values are in range. Like in example.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
    on_value_range:
      - above: 28
        then:
          connect to wifi, connect to mqtt and exchange data
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
