### ISSUE TITLE
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)

### ISSUE THREAD

**Issue by human2010** [esphome/issues#1805]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Raspbian/python3.7/pip3
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32（esp-wroom-32）
**ESPHome version (latest production, beta, dev branch)**

v1.14.4
**Affected component:**

https://esphome.io/components/sensor/dht.html

**Description of problem:**
Compiled without errors, but cannot run after downloading. Prompt "Guru Meditation Error: Core 1 panic'ed (Interrupt wdt timeout on CPU1)" 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

# ESPHome Core Configuration
esphome:
  name: esp32
  platform: ESP32
  board: nodemcu-32s

# WiFi Component
wifi:
  ssid: "******"
  password: "***********"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Fallback Hotspot"
    password: "12345678"

# Captive Portal(http://192.168.4.1/)
captive_portal:

# Logger Component
logger:

# Native API Component(homeassistant)
api:

# OTA Update Component
ota:

# Web Server Component
web_server:  

# WiFi Signal & T & H & L Sensor
sensor:
  - platform: wifi_signal
    name: "Esp32 WiFi Signal"
    update_interval: 60s 

  - platform: dht
    pin: GPIO36
    temperature:
      name: "Temperature"
      id: temp_id
    humidity:
      name: "Humidity"
    update_interval: 60s    
    model: DHT11

**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

========================= [SUCCESS] Took 31.62 seconds =========================
INFO Successfully uploaded program.
INFO Starting log output from /dev/ttyUSB0 with baud rate 115200
[00:01:30] : 0x80089f09  A5      : 0x3ffb1c60  
[00:01:30]A6      : 0x00000003  A7      : 0x00060623  A8      : 0x8008175e  A9      : 0x3ffb1c40  
[00:01:30]A10     : 0x0007a303  A11     : 0x00000000  A12     : 0x80089308  A13     : 0x3ffb1c30  
[00:01:30]A14     : 0x00000000  A15     : 0x3ffb0060  SAR     : 0x0000001b  EXCCAUSE: 0x00000006  
[00:01:30]EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  
[00:01:30]
[00:01:30]Backtrace: 0x4008175e:0x3ffb1c60 0x400de3bb:0x3ffb1c80 0x400813a5:0x3ffb1ca0 0x400dd607:0x3ffb1cd0 0x400df4ba:0x3ffb1d20 0x400eb953:0x3ffb1fb0 0x400890f5:0x3ffb1fd0
WARNING Found stack trace! Trying to decode it
INFO Need to fetch platformio IDE-data, please stand by
INFO Running:  platformio run -d esphome_config/esp32 -t idedata
WARNING Decoded 0x4008175e: millis at /home/pi/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-misc.c:170
WARNING Decoded 0x400de3bb: esphome::Scheduler::millis_() at /home/pi/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/stl_vector.h:932
WARNING Decoded 0x400813a5: esphome::Scheduler::call() at /home/pi/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/stl_vector.h:932
WARNING Decoded 0x400dd607: esphome::Application::setup() at /home/pi/esphome_config/esp32/src/esphome/core/application.cpp:47
WARNING Decoded 0x400df4ba: setup() at /home/pi/esphome_config/esp32/src/main.cpp:184
WARNING Decoded 0x400eb953: loopTask(void*) at /home/pi/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:14
WARNING Decoded 0x400890f5: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
[00:01:35]
[00:01:35]Core 0 register dump:
[00:01:35]PC      : 0x4016359a  PS      : 0x00060b34  A0      : 0x800eeb31  A1      : 0x3ffbc050  
WARNING Decoded 0x4016359a: esp_pm_impl_waiti at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/pm_esp32.c:492
[00:01:35]A2      : 0x00000000  A3      : 0x00000001  A4      : 0x80089308  A5      : 0x3ffaef20  
[00:01:35]A6      : 0x00000000  A7      : 0x3ffbbd40  A8      : 0x800eda9e  A9      : 0x3ffbc020  
[00:01:35]A10     : 0x00000000  A11     : 0x00000001  A12     : 0x80089308  A13     : 0x3ffaeec0  
[00:01:35]A14     : 0x00000000  A15     : 0x3ffbbd40  SAR     : 0x00000000  EXCCAUSE: 0x00000006  
[00:01:35]EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
[00:01:35]
[00:01:36]Backtrace: 0x4016359a:0x3ffbc050 0x400eeb2e:0x3ffbc070 0x4008a8d9:0x3ffbc090 0x400890f5:0x3ffbc0b0
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x4016359a: esp_pm_impl_waiti at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/pm_esp32.c:492
WARNING Decoded 0x400eeb2e: esp_vApplicationIdleHook at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/freertos_hooks.c:108
WARNING Decoded 0x4008a8d9: prvIdleTask at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c:3507
WARNING Decoded 0x400890f5: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
[00:01:36]
[00:01:36]Rebooting...
[00:01:36]ets Jun  8 2016 00:22:57
[00:01:36]
[00:01:36]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[00:01:36]configsip: 0, SPIWP:0xee
[00:01:36]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[00:01:36]mode:DIO, clock div:2
[00:01:36]load:0x3fff0018,len:4
[00:01:36]load:0x3fff001c,len:1044
[00:01:36]load:0x40078000,len:8896
[00:01:36]load:0x40080400,len:5828
[00:01:36]entry 0x400806ac
[00:01:36][I][logger:156]: Log initialized
[00:01:36][C][ota:364]: There have been 1 suspected unsuccessful boot attempts.
[00:01:36][I][app:028]: Running through setup()...
[00:01:36][C][dht:011]: Setting up DHT...
[00:01:36][C][wifi:033]: Setting up WiFi...
[00:01:36][D][wifi:304]: Starting scan...
[00:01:36][W][dht:154]: Waiting for DHT communication to clear failed!
[00:01:36][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number).
[00:01:36][D][sensor:092]: 'Temperature': Sending state nan °C with 1 decimals of accuracy
[00:01:36][D][sensor:092]: 'Humidity': Sending state nan % with 0 decimals of accuracy
[00:01:36]Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)

**Additional information and things you've tried:**

The same problem occurs when replacing pin c.
Other sensors, switches, lights, etc. are fine.
ESP8266 can also be used.
ESP32 does not work.
