### ISSUE TITLE
ESP32 Node connection & status dropping from green to red after a few seconds/minutes

### ISSUE THREAD

**Issue by Sleinous** [esphome/issues#1812]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**

I have a single ESP-32 gateway from Olimex on ESPHome for over a year now - no issues and zero disconnections up until now.
Its purpose is to grab xiaomi temp/humidity/battery sensor ble data for use in HA.
Yesterday I noticed that the status bar for this node was red (as opposed to green) & seemed to be sporadically updating. (I noticed this because I also run a XiaomiGateway v3 parallel to this - grabbing the same data from the BLE temp/humidity sensors for redundancy purposes).
Spent about a day researching on the forums and github 'issues' pages thinking it may be to do with multicast and/or mDNS except this has always worked fine for me up until now and I haven't changed anything on my network (no VLANs in use here).
**_So here's what i've tried so far_**
I noticed that the device (esp32cuisine.local) was no longer able to grab it's IP - odd because it was always able to in the past so I added the manual_ip configuration to my yaml for this esp32 - was able to connect to the network but the status bar on ESPHome would stay green for about 5 seconds, then go orange & back to red. Again, sporadic updates of BLE tracking data afterwards. The device was still pingable even after ESPHome displayed the red bar across that node.
I read that this could be linked to multicast & mDNS, but again, i've never had this issue in well over a year of using esphome.

I then tried removing the manual_ip config & adding 'domain', declaring this device in my domain DNS. This time the device correctly connected to the network and resolved it's IP.
Didn't help with the node going offline (red) in ESPHome dashboard though.

Last tried activating VERY_VERBOSE in logger (connected to wifi and then later connected over USB)
I noticed that as soon as VERY_VERBOSE was activated and I was inspecting logs through ESPHome UI the node would stay green for a lot longer, upwards of 30mn, but could someones return to an 'offline' (red) state but still be receiving BLE data from the different sensors around the house...

At this stage I have run out of ideas on where this problem is coming from. Any ideas welcome ! Thanks 

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32cuisine
  platform: ESP32
  board: esp32-gateway

wifi:
  ssid: "testssid"
  password: "testxxxx"
  domain: .xxxxxxx
  #manual_ip:
    # Set this to the IP of the ESP
    #static_ip: 192.168.X.X
    # Set this to the IP address of the router. Often ends with .1
    #gateway: 192.168.X.X
    # The subnet of the network. 255.255.255.0 works for most home networks.
    #subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Cuisine Fallback Hotspot"
    password: "FRcy10KIiQl1"

captive_portal:

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:


esp32_ble_tracker:

sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: "58:2D:34:3B:52:F8"
    temperature:
      name: "Chambre Temperature"
    humidity:
      name: "Chambre Humidité"
    battery_level:
      name: "Chambre Batterie"
  - platform: xiaomi_lywsdcgq
    mac_address: "58:2D:34:3B:55:BC"
    temperature:
      name: "SdB Temperature"
    humidity:
      name: "SdB Humidité"
    battery_level:
      name: "SdB Batterie"
  - platform: xiaomi_lywsdcgq
    mac_address: "58:2D:34:3B:35:8B"
    temperature:
      name: "Salon Temperature"
    humidity:
      name: "Salon Humidité"
    battery_level:
      name: "Salon Batterie"
  - platform: xiaomi_lywsdcgq
    mac_address: "58:2D:34:3B:35:EE"
    temperature:
      name: "Couloir Temperature"
    humidity:
      name: "Couloir Humidité"
    battery_level:
      name: "Couloir Batterie"

```

**Logs (if applicable):**

```
debug over USB log incoming here

```

**Additional information and things you've tried:**
