### ISSUE TITLE
lamda loop not functioning as expected

### ISSUE THREAD

**Issue by danpowpow** [esphome/issues#1813]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

esphome 1.16 in docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32cam
**ESPHome version (latest production, beta, dev branch)**

1.16
**Affected component:**

https://esphome.io/custom/custom_component.html

**Description of problem:**
i have some fairy/festoon lights, which i'm converting to smart control.  they require pulsed dc control, so i am feeding them power through a L298N H-Bridge. I am polarity reversing the signals into the L298N and this is functioning very nicely when using arduino, however using the equivalent simple loop sequence working in esphome is not working. I can get the speed down to about 50 before it starts messing with the wifi connection, but at speed 1 it simply doesnt work. Does esphome run fast enough to process this loop at a high enough frequency?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE



#include "esphome.h"

class festoon : public Component {
 public:
  void setup() override {
    pinMode(14, OUTPUT);
    pinMode(13, OUTPUT);
  }
  void loop() override {
  digitalWrite(14, HIGH);
  digitalWrite(13, LOW);
  delay(1);
  digitalWrite(14, LOW);
  digitalWrite(13, HIGH);  
  delay(1);
    }
  };

##########

esphome:
  name: festoon21
  platform: ESP32
  board: esp32cam

  includes:
    - festoon.h

wifi:
  ssid: "xxxxx"
  password: "xxxxxx"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
custom_component:
- lambda: |-
    auto my_custom = new festoon();
    return {my_custom};  

output:
  - platform: ledc
    pin: GPIO12
    id: gpio_12
    frequency: 19531

# Example usage in a light
light:
  - platform: monochromatic
    output: gpio_12
    name: "Festoon21"

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
