### ISSUE TITLE
Nextion Received Unknown Filler end bytes

### ISSUE THREAD

**Issue by stevemutch** [esphome/issues#1817]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio or Pi4

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 mini, also tried same on a nodemcu (ESP8266 and ESP32)

**ESPHome version (latest production, beta, dev branch)**

1.16.0

**Affected component:**

https://www.esphome.io/components/display/nextion.html?highlight=nextion

**Description of problem:**
I've loaded the yaml below to 3 ESP's (Wemos D1 Mini, ESP8266 Nodemcu and an ESP32. All 3 report back page and component id touches on the Nextion 3.2 Enhanced perfectly but on a 2.4 inch basic every press sends back the following:

[W][nextion:145]: Received unknown filler end bytes from Nextion!

and don't confirm back the usual info i get (see below) when a 3.2 enhanced nextion screen is attached to the same node:

[16:50:39][D][nextion:209]: Got touch page=0 component=2 type=PRESS
[16:50:42][D][nextion:209]: Got touch page=0 component=6 type=PRESS

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: nextion24_controller01
  platform: ESP8266
  board: d1_mini
          
wifi:
  ssid: "xxxxxxx"
  password: "xxxxxxx"
  fast_connect: true
    # Enable fallback hotspot (captive portal) in case wifi connection fails

  ap:
    ssid: "Nextion24_01 Fallback Hotspot"
    password: "xxxxxx"  
   
web_server:
  port: 80
  auth:
    username: xxxxxx
    password: xxxxxx    
  
mqtt:
  broker: mqtt.xxxxxx.com
  username: xxxxxx
  password: xxxxxx
  
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  password: "xxxxxx"

ota:
  password: "xxxxxx"

# Uart port definition - This works OK, but also HW UART0 works if Logs are disabled or changed to UART1
uart:
  rx_pin: D4
  tx_pin: D7
  baud_rate: 9600

#Print sensor data in relevant Nextion objects (number type)
display:
  - platform: nextion  
    id: touchpanel
    update_interval: 3s
    brightness: 1
    lambda: |-
      it.set_wait_for_ack(false);
      it.set_component_value("heaterinvalue", id(heaterin).state);  
      it.set_component_value("ambientvalue", id(ambient).state);  
      it.set_component_value("heateroutvalue", id(heaterout).state);  
      it.set_component_value("poolvalue", id(pool).state);  
      it.set_component_value("spavalue", id(spa).state);
      it.set_component_value("pumpvalue", id(pump).state);

#Read sensor data from MQTT
      
sensor:
  - platform: mqtt_subscribe
    id: heaterin
    topic: ds18b20_sensor02/sensor/ds18b20_sensor02/state
    
  - platform: mqtt_subscribe
    id: heaterout
    topic: ds18b20_sensor02/sensor/ds18b20_sensor02/state 
    
  - platform: mqtt_subscribe
    id: spa
    topic: ds18b20_sensor03/sensor/ds18b20_sensor03/state
    
  - platform: mqtt_subscribe
    id: pool
    topic: ds18b20_sensor03/sensor/ds18b20_sensor03/state    
    
  - platform: mqtt_subscribe
    id: ambient
    topic: ds18b20_sensor03/sensor/ds18b20_sensor03/state    
    
  - platform: mqtt_subscribe
    id: pump
    topic: ds18b20_sensor03/sensor/ds18b20_sensor03/state      
    
binary_sensor:
  - platform: nextion
    filters:
      - invert:
      - delayed_on: 50ms
      - delayed_off: 50ms
      - delayed_on_off: 50ms  
    page_id: 1
    component_id: 2
    id: spa_on
    on_press:
      then:
        - mqtt.publish:
            topic: 40a_relay01/switch/40a_relay01/command
            payload: "ON"
        - component.update: touchpanel   
    on_release:
      then:
        - component.update: touchpanel             

  - platform: nextion
    filters:
      - invert:
      - delayed_on: 50ms
      - delayed_off: 50ms
      - delayed_on_off: 50ms    
    page_id: 1
    id: spa_off
    component_id: 3
    on_press:
      then:
        - mqtt.publish:
            topic: 40a_relay01/switch/40a_relay01/command
            payload: "OFF"
        - component.update: touchpanel      
    on_release:
      then:
        - component.update: touchpanel  

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by stratus-ss** [comment]
For me I only encounter this about 5% of the time, but its enough to not trust whether the device has actually done anything

I have this occasionally with a Nextion 3.5 basic screen sample ESP Log output

```
[16:24:26][W][nextion:145]: Received unknown filler end bytes from Nextion!
[16:24:27][D][nextion:209]: Got touch page=5 component=4 type=PRESS
[16:24:27][D][binary_sensor:036]: 'proj_led_but': Sending state ON
[16:24:27][D][binary_sensor:036]: 'proj_led_but': Sending state OFF
[16:24:28][D][nextion:209]: Got touch page=5 component=4 type=PRESS
[16:24:28][D][binary_sensor:036]: 'proj_led_but': Sending state ON
[16:24:28][D][binary_sensor:036]: 'proj_led_but': Sending state OFF
[16:24:29][W][nextion:145]: Received unknown filler end bytes from Nextion!
[16:24:30][D][nextion:209]: Got touch page=5 component=5 type=PRESS
[16:24:30][D][binary_sensor:036]: 'steve_desk_but': Sending state ON
[16:24:30][D][binary_sensor:036]: 'steve_desk_but': Sending state OFF
[16:24:31][D][nextion:209]: Got touch page=5 component=5 type=PRESS
[16:24:31][D][binary_sensor:036]: 'steve_desk_but': Sending state ON
[16:24:31][D][binary_sensor:036]: 'steve_desk_but': Sending state OFF
[16:24:34][D][nextion:209]: Got touch page=5 component=5 type=PRESS
[16:24:34][D][binary_sensor:036]: 'steve_desk_but': Sending state ON
[16:24:34][D][binary_sensor:036]: 'steve_desk_but': Sending state OFF
[16:24:36][D][nextion:209]: Got touch page=5 component=5 type=PRESS
[16:24:36][D][binary_sensor:036]: 'steve_desk_but': Sending state ON
[16:24:36][D][binary_sensor:036]: 'steve_desk_but': Sending state OFF
[16:24:38][D][nextion:209]: Got touch page=5 component=5 type=PRESS
[16:24:38][D][binary_sensor:036]: 'steve_desk_but': Sending state ON
[16:24:38][D][binary_sensor:036]: 'steve_desk_but': Sending state OFF
[16:24:44][D][nextion:209]: Got touch page=3 component=4 type=PRESS
[16:24:44][D][binary_sensor:036]: 'kettle': Sending state ON
[16:24:44][D][binary_sensor:036]: 'kettle': Sending state OFF
[16:24:46][W][nextion:145]: Received unknown filler end bytes from Nextion!
[16:24:47][D][nextion:209]: Got touch page=3 component=7 type=PRESS
[16:24:47][D][binary_sensor:036]: 'kitchen_fan': Sending state ON
[16:24:47][D][binary_sensor:036]: 'kitchen_fan': Sending state OFF
[16:24:51][D][nextion:209]: Got touch page=3 component=7 type=PRESS
[16:24:51][D][binary_sensor:036]: 'kitchen_fan': Sending state ON
[16:24:51][D][binary_sensor:036]: 'kitchen_fan': Sending state OFF
[16:24:52][D][nextion:209]: Got touch page=3 component=3 type=PRESS
[16:24:52][D][binary_sensor:036]: 'laundry_over': Sending state ON
[16:24:52][D][binary_sensor:036]: 'laundry_over': Sending state OFF
[16:24:54][D][nextion:209]: Got touch page=3 component=3 type=PRESS
[16:24:54][D][binary_sensor:036]: 'laundry_over': Sending state ON
[16:24:54][D][binary_sensor:036]: 'laundry_over': Sending state OFF
[16:25:01][D][nextion:209]: Got touch page=6 component=1 type=PRESS
[16:25:01][D][binary_sensor:036]: 'bath_lights': Sending state ON
[16:25:01][D][binary_sensor:036]: 'bath_lights': Sending state OFF
[16:25:06][D][nextion:209]: Got touch page=6 component=1 type=PRESS
[16:25:06][D][binary_sensor:036]: 'bath_lights': Sending state ON
[16:25:06][D][binary_sensor:036]: 'bath_lights': Sending state OFF
[16:25:08][D][nextion:209]: Got touch page=6 component=1 type=PRESS
[16:25:08][D][binary_sensor:036]: 'bath_lights': Sending state ON
[16:25:08][D][binary_sensor:036]: 'bath_lights': Sending state OFF
[16:25:09][D][nextion:209]: Got touch page=6 component=1 type=PRESS
[16:25:09][D][binary_sensor:036]: 'bath_lights': Sending state ON
[16:25:09][D][binary_sensor:036]: 'bath_lights': Sending state OFF
[16:25:10][D][nextion:209]: Got touch page=6 component=2 type=PRESS
[16:25:10][D][binary_sensor:036]: 'bath_over': Sending state ON
[16:25:10][D][binary_sensor:036]: 'bath_over': Sending state OFF
[16:25:12][W][nextion:145]: Received unknown filler end bytes from Nextion!
```

Here is the yaml:

```
esphome:
  name: main_room_nextion
  platform: ESP8266
  board: d1_mini
 
wifi:
  ssid: "xxx"
  password: "xxx"
  domain: .xxx.xxx
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xxxx"
    password: "xxxx"
 
captive_portal:
 
# Enable logging
logger:
  level: DEBUG
  baud_rate: 9600
   
# Enable Home Assistant API
api:
 
ota:
 
web_server:
  port: 80
 
uart:
  rx_pin: D1 #GPIO3 GREEN Cable
  tx_pin: D3 #GPIO1 BLUE Cable
  baud_rate: 9600
 
display:
  - platform: nextion
 
binary_sensor:



## Screen 2 bedroom
  - platform: nextion
    page_id: 2
    component_id: 2
    id: bed_leds
    on_press:
      then:
        - homeassistant.service:
            service: switch.toggle
            data:
              entity_id: switch.rosannapb4   
        - lambda: |-
            id(bed_leds).publish_state(false);
  - platform: nextion
    page_id: 2
    component_id: 1
    id: tv
    on_press:
      then:
        - homeassistant.service:
            service: script.turn_on
            data:
              entity_id: script.tv_power_on
        - lambda: |-
            id(tv).publish_state(false);
  - platform: nextion
    page_id: 2
    component_id: 3
    id: steve_light
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.steves_bed
        - lambda: |-
            id(steve_light).publish_state(false);
  - platform: nextion
    page_id: 2
    component_id: 4
    id: rosanna_bed
    on_press:
      then:
        - homeassistant.service:
            service: switch.toggle
            data:
              entity_id: switch.rosannapb3
        - lambda: |-
            id(rosanna_bed).publish_state(false);
            
## Screen 3 Kitchen & Laundry
  - platform: nextion
    page_id: 3
    component_id: 2
    id: laundry_lights
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.laundryroom
        - lambda: |-
            id(laundry_lights).publish_state(false);
  - platform: nextion
    page_id: 3
    component_id: 1
    id: kitchen_lights
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.kitchen_light_1_kitchen_light_1
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.kitchen_light_2_switch
        - lambda: |-
            id(kitchen_lights).publish_state(false);    
  - platform: nextion
    page_id: 3
    component_id: 3
    id: laundry_over
    on_press:
      then:
        - homeassistant.service:
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.laundryroom_override
        - lambda: |-
            id(laundry_over).publish_state(false);    
  - platform: nextion
    page_id: 3
    component_id: 4
    id: kettle
    on_press:
      then:
        - homeassistant.service:
            service: switch.toggle
            data:
              entity_id: switch.tea_kettle
        - lambda: |-
            id(kettle).publish_state(false);  
  - platform: nextion
    page_id: 3
    component_id: 7
    id: kitchen_fan
    on_press:
      then:
        - homeassistant.service:
            service: switch.toggle
            data:
              entity_id: switch.kitchen_fan
        - lambda: |-
            id(kitchen_fan).publish_state(false);                       

## Screen 4 Hallway
  - platform: nextion
    page_id: 4
    component_id: 1
    id: hall_lights
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.hallway_light1_switch
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.hallway_light2_switch
        - lambda: |-
            id(hall_lights).publish_state(false);    
  - platform: nextion
    page_id: 4
    component_id: 2
    id: hall_over
    on_press:
      then:
        - homeassistant.service:
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.hallway_override
        - lambda: |-
            id(hall_over).publish_state(false);  
## Screen 5 desk lights, dinning room lights
  - platform: nextion
    page_id: 5
    component_id: 5
    id: steve_desk_but
    on_press:
      then:
        - homeassistant.service:
            service: switch.toggle
            data:
              entity_id: switch.steve_desk_light
        - homeassistant.service:
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.steve_desk_light_override
        - lambda: |-
            id(steve_desk_but).publish_state(false);
  - platform: nextion
    page_id: 5
    component_id: 4
    id: proj_led_but
    on_press:
      then:
        - homeassistant.service:
            service: switch.toggle
            data:
              entity_id: switch.projector_leds
        - homeassistant.service:
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.projector_led_override     
        - lambda: |-
            id(proj_led_but).publish_state(false);
  - platform: nextion
    page_id: 5
    component_id: 2
    id: dinning_lights
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.dr_light1_switch
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.dr_light2_switch
        - lambda: |-
            id(dinning_lights).publish_state(false);
  - platform: nextion
    page_id: 5
    component_id: 6
    id: din_lights
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.table_lights_switch
        - lambda: |-
            id(din_lights).publish_state(false);
  - platform: nextion
    page_id: 5
    component_id: 1
    id: rosanna_lights
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.rosanna_desk_leds
        - lambda: |-
            id(rosanna_lights).publish_state(false);            

## Screen 6 Main Bathroom
  - platform: nextion
    page_id: 6
    component_id: 1
    id: bath_lights
    on_press:
      then:
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.main_br_light1
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.main_br_light2
        - lambda: |-
            id(bath_lights).publish_state(false);    
  - platform: nextion
    page_id: 6
    component_id: 2
    id: bath_over
    on_press:
      then:
        - homeassistant.service:
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.bathroom_override
        - lambda: |-
            id(bath_over).publish_state(false);
  - platform: nextion
    page_id: 6
    component_id: 3
    id: bath_full
    on_press:
      then:
        - homeassistant.service:
            service: script.turn_on
            data:
              entity_id: script.main_br_full_white
        - lambda: |-
            id(bath_full).publish_state(false);            
```
