### ISSUE TITLE
esp32_ble_beacon does not work

### ISSUE THREAD

**Issue by VanGog86** [esphome/issues#1818]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
 pip install

**ESP (ESP32/ESP8266, Board/Sonoff):**
 esp32doit-devkit-v1

**ESPHome version (latest production, beta, dev branch)**
 Current version: 1.16.0

**Affected component:**
 https://esphome.io/components/esp32_ble_beacon.html

**Description of problem:**
After successful flashing, my iphone does not detect the ibeacon. I check through the bluetooth screen and don't see any new devices there. through the bleScanner application I see a new device but it is defined as N / A but not as a ibeacon

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: ble
  platform: ESP32
  board: esp32doit-devkit-v1

esp32_ble_beacon :
  type : iBeacon 
  uuid : '12a13a53-905b-0654-3468-3956014a7888'
  major : 234
  minor : 138
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
