### ISSUE TITLE
Restoring a state does not trigger events

### ISSUE THREAD

**Issue by micw** [esphome/issues#1819]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

1.16.0

**Affected component:**

Switch

**Description of problem:**

A switch can trigger events like "on_turn_on", "on_turn_off" that can be used to sync a status led with the switch. The events are not triggered on startup when the switch state is restored.

The following snippet defines a switch and a GPIO with a status LED on it. When turning the switch on, the status LED turns on. When turning the switch off, the status LED turns off. But when the system starts and the state ON is restored, the event is not triggered and the status LED remains OFF.

**Problem-relevant YAML-configuration entries:**
```yaml
output:
- platform: gpio
  id: led1
  pin:
    number: GPIO00

switch:
- platform: gpio
  id: switch1
  pin: GPIO14
  restore_mode: RESTORE_DEFAULT_ON
  on_turn_on:
    - output.turn_on: led1
  on_turn_off:
    - output.turn_off: led1
```
