### ISSUE TITLE
TTP229 without i2c doesn't report any keypresses

### ISSUE THREAD

**Issue by j-a-g-r** [esphome/issues#1823]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 nodemcuv2

**ESPHome version (latest production, beta, dev branch)**
1.16.0

**Affected component:**
https://esphome.io/components/binary_sensor/ttp229.html

**Description of problem:**
The Version of the Ttp229 component **without i2c (ttp229_bsf)**, doesn't report any keypresses neither in HA nor in the esphome logs.
Also the  _ttp229_bsf:_ sensor requires the _i2c:_ component, even though it shouldn't need it.
```
Failed config

ttp229_bsf: [source keypad.yaml:17]

  Component ttp229_bsf requires component i2c.
  sdo_pin: D0
  scl_pin: D1
```
[Here is someone else who described the same problem on discord.](https://discord.com/channels/429907082951524364/429907082955718657/691644957517414400)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: keypad
  platform: ESP8266
  board: nodemcuv2
 
wifi:
  ssid: "..."
  password: "..."
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Keypad Fallback Hotspot"
    password: "..."
 
i2c: # i2c needs to be imported, even though it isn't needed
ttp229_bsf:
  sdo_pin: D0
  scl_pin: D1
 
binary_sensor:
  - platform: ttp229_bsf
    name: TTP229 Channel 0
    channel: 0
 
captive_portal:
# Enable logging
logger:
# Enable Home Assistant API
api:
ota:

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

I tried [this code](https://github.com/Erriez/ErriezTTP229TouchKeypad) to ensure that my board is working.
[I enabled 16 key mode](http://itimewaste.blogspot.com/2014/12/arduino-code-for-ttp229-touch-16-button.html).
[my wiring](https://i.ibb.co/jb4HSfc/untitled.png).
