### ISSUE TITLE
Remote transmitter is not working after update [1.15.3]->[1.16.0]

### ISSUE THREAD

**Issue by mihing** [esphome/issues#1828]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant OS 5.11

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

1.16.0

**Affected component:**

https://esphome.io/components/remote_transmitter.html#remote-transmitter-transmit-rc-switch-raw-action

**Description of problem:**
After updating ESPHome to version 1.16.0, 433MHz transmitter stopped working.
The console looks like everything is ok, but the controlled devices stopped responding to commands.
I rolled back to version 1.15.3 and everything worked again.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: nodemcuv3_rf433
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret Wifi_SSID
  password: !secret Wifi_PWD
  fast_connect: on

logger:
      esp8266_store_log_strings_in_flash: false

api:
  password: !secret HassPass

ota:
  password: !secret HassPass

web_server:
  port: 80


remote_receiver:
  pin:
    number: D1
    #inverted: True
    #mode: INPUT_PULLUP
  dump:
    - rc_switch
  # Settings to optimize recognition of RF devices
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb
      
remote_transmitter:
  pin:
    number: D2
    #inverted: True
    #mode: INPUT_PULLUP
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%
  
switch:

  - platform: template
    name: "RF Power Socket 1"
    icon: "mdi:power-socket-de"
    id: RFSocket1
    
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '101100000111110101011111'
          protocol: 1
          repeat:
            times: 5
            wait_time: 50ms
      - switch.template.publish:
          id: RFSocket1
          state: ON
    
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '101100000111110101010111'
          protocol: 1
          repeat:
            times: 5
            wait_time: 50ms
      - switch.template.publish:
          id: RFSocket1
          state: OFF
```

**Logs (if applicable):**

```
No errors in log.

```

**Additional information and things you've tried:**
