### ISSUE TITLE
Cannot get Thermostat Yaml to validate

### ISSUE THREAD

**Issue by jaysalazar** [esphome/issues#1842]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**ESPHome version (latest production, beta, dev branch)**

1.16.1
**Affected component:**

https://esphome.io/components/climate/thermostat.html

**Description of problem:**
Will not validate, getting the following message ..... Platform not found: 'climate.thermostat'.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
climate:
  - platform: thermostat
    name: "Thermostat Climate Controller"
    sensor: BME280_Temp
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 22 °C
    cool_action:
      - switch.turn_on: air_cond
    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: air_cond
      - switch.turn_off: heater
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
INFO Reading configuration /config/esphome/grow_tent.yaml...
Failed config

climate.thermostat: [source /config/esphome/grow_tent.yaml:88]
  
  Platform not found: 'climate.thermostat'.
  platform: thermostat
  name: Thermostat Climate Controller
  sensor: BME280_Temp
  default_target_temperature_low: 20 °C
  default_target_temperature_high: 22 °C
  cool_action: 
    - switch.turn_on: air_cond
  heat_action: 
    - switch.turn_on: heater
  idle_action: 
    - switch.turn_off: air_cond
    - switch.turn_off: heater
```

**Additional information and things you've tried:**
