### ISSUE TITLE
RF Sync header being sent at the end of the code payload instead of at the beggining 

### ISSUE THREAD

**Issue by Rodrigoah** [esphome/issues#1843]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMcu

**ESPHome version (latest production, beta, dev branch)**

1.15.3

**Affected component:**

remote_transmitter

**Description of problem:**

Header of custom protocol is sent at the end of the code instead of at the beggining

**Problem-relevant YAML-configuration entries:**
```yaml
      remote_transmitter.transmit_rc_switch_raw:
        code: '1010001100110000000101000010010000000001000000000000101101110100'
        protocol:
          pulse_length: 510
          sync: [25, 3]
          zero: [1,3]
          one: [3,1]
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
