### ISSUE TITLE
Inkplate Documentation needs correction

### ISSUE THREAD

**Issue by rklueber** [esphome/issues#1846]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 inside an inkplate6

**ESPHome version (latest production, beta, dev branch)**

v1.16.1
**Affected component:**

https://esphome.io/components/display/inkplate?highlight=inkplate

**Description of problem:**

The platform must be 'inkplate6'.

Cuurent documentation is this
```
display:
- platform: inkplate
  id: inkplate_display
  greyscale: false
  partial_updating: false
  update_interval: 60s

  ...
````
which does not work. It should be:

```
display:
- platform: inkplate6
  id: inkplate_display
  greyscale: false
  partial_updating: false
  update_interval: 60s

  ...
```

**Problem-relevant YAML-configuration entries:**
```yaml
display:
- platform: inkplate
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
