### ISSUE TITLE
DHT: add support for setting the 'device_class'

### ISSUE THREAD

**Issue by StijnVdd** [esphome/issues#1847]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

1.16.1

**Affected component:**

DHT and other sensor components

**Description of problem:**
The sensor components like the DHT, do not report the device_class to HA. It would be great to set the device class correctly for temperature/humidity...

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: dht
    model: DHT22
    pin: 
      number: D5
      mode: INPUT
    temperature:
      name: "temperature"
      accuracy_decimals: 1
      id: temp_sensor
    humidity:
      name: "humidity"
      accuracy_decimals: 1
      id: hum_sensor
    update_interval: 60s

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

Setting the 'device_class' for the temperature section returns an error.
