### ISSUE TITLE
Component remote transmitter don't support 32bit samsung codes

### ISSUE THREAD

**Issue by TobbeJ** [esphome/issues#1860]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

hassio vm

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 but not really relevant to the bug report

**ESPHome version (latest production, beta, dev branch)**

1.16.2

**Affected component:**

Remote Transmitter

**Description of problem:**
Remote transmitter doesnt allow nbits to be set to 32.
This will prevents me from properly setting up the remote transmitter since the upper 12 bits is ignored and this causes my tv to not respond to the codes.

sample output of remote receiver setup to just dump all codes:
```
[D][remote.samsung:055]: Received Samsung: data=0xE0E040BF
[D][remote.samsung:055]: Received Samsung: data=0xE0E040BF
[D][remote.samsung:055]: Received Samsung: data=0xE0E040BF
[D][remote.samsung:055]: Received Samsung: data=0xE0E040BF
```

Note the E0E0 att the start.
since only 20bits is allowed the resulting transmitted code ends up being: 0x000040BF and tv of course don't respond

i'm guessing this line in the code needs changing:
https://github.com/esphome/esphome/blob/5c86f332b269fd3e4bffcbdf3359a021419effdd/esphome/components/remote_base/__init__.py#L331

**Problem-relevant YAML-configuration entries:**
```yaml
remote_transmitter:
  pin: GPIO4
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

#test
switch:
  - platform: template
    name: "Samsung TV Power"
    turn_on_action:
      remote_transmitter.transmit_sony:
        data: 0xE0E040BF
        nbits: 20
  - platform: template
    name: "Samsung TV Mute"
    turn_on_action:
      remote_transmitter.transmit_sony:
        data: 0xE0E0F00F
        nbits: 20

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
