### ISSUE TITLE
st7735 has various small problems preventing support of M5Stick-C

### ISSUE THREAD

**Issue by wjcarpenter** [esphome/issues#1863]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Standalone pip3 esphome 1.16.2

Standalone pip3 esphome 1.16.2

**ESP (ESP32/ESP8266, Board/Sonoff):** 
ESP32, M5Stick-C

**ESPHome version (latest production, beta, dev branch)**
latest production

1.16.2
**Affected component:**

https://esphome.io/components/display/st7735.html

**Description of problem:**
Support for the st7735 was recently added, but it does not quite support that display in the M5Stick-C. 

It most closely resembles the model INITR_MINI160X80. but that model has "colstart" hardcoded to 24 in the C++ code. M5Stick-C needs a value of 26. It would be a good enough fix to eliminate the hardcoding and accept the configured value, as is done for other models.

The display must also have the ST77XX_INVON command sent to it during initialization. A reasonable thing would be to have a new optional boolean configuration property, for example, `invert` with a default value of false. When set to true,
```
  if (this->invert_) {
    sendcommand_(ST77XX_INVON, &data, 0);
  }
```
during device initialization. Assuming these changes, a YAML config for the display part of the M5Stick-C is given in the YAML section below.

**Problem-relevant YAML-configuration entries:**
```
display:
  - platform: st7735
    model: INITR_MINI160X80
    rowstart: 1
    colstart: 26
    devicewidth: 0
    deviceheight: 0
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 270
    usebgr: true
    invert: true
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I have made these changes locally and gotten the display working completely on M5Stick-C. I could supply a pull request if that would be helpful. (The only reason I didn't automatically send a PR is because I see that some additional work has been done in the `dev` branch for the st7735 since the 1.16.2 release.
