### ISSUE TITLE
Cannot use A0 and VCC at same time

### ISSUE THREAD

**Issue by jbrepogmailcom** [esphome/issues#1864]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASSIO

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

latest prod

**Affected component:**

A0 and VCC

**Description of problem:**

Hello. I would like to measure voltage on A0 pin and also VCC battery voltage. If I program it in C++, it works. But following configuration only sends one mqtt sensor - I suspect that one definition overrides the other. Is there any other way how to define both sensors?

```
sensor:
  - platform: adc
    id: pracka2_vcc
    pin: VCC
    name: "Pracka2 VCC"
    retain: true
    update_interval: 30s
    accuracy_decimals: 2

  - platform: adc
    id: pracka2_pr
    pin: A0
    name: "Pracka2 Photo Resistor"
    retain: true
    update_interval: 30s
    accuracy_decimals: 3
```

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
