### ISSUE TITLE
display component has UnicodeDecodeError

### ISSUE THREAD

**Issue by randompee** [esphome/issues#1866]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip on Raspi 3B+
**ESP (ESP32/ESP8266, Board/Sonoff):**

e.g. esp32doit-devkit-v1
**ESPHome version (latest production, beta, dev branch)**

1.17.0-dev
**Affected component:**

https://esphome.io/components/display/index.html

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
display:
...
         lambda: |-
              it.printf(0,  6, id(my_font5), "CO""\u2082");
...
font:
   - file: "DejaVuSans.ttf"
     id: my_font5
     size: 20
```

**Logs (if applicable):**

```
  File "/home/pi/.local/lib/python3.7/site-packages/google/protobuf/internal/decoder.py", line 572, in _ConvertToUnicode
    value = local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 80: 'utf-8' codec can't decode byte 0xe2 in position 80: invalid continuation byte in field: 


```

**Additional information and things you've tried:**

when I added the (optional!!) line 

        glyphs: " ()CHMOPRT%\u2082\u00B0"

to the font, all was well, the UnicodeDecodeError went away. I did not give more info on the ESPs and so on because I tested with two different ones and two different displays, and the results were the same.
