### ISSUE TITLE
dallas.sensor Scratch pad checksum invalid! error

### ISSUE THREAD

**Issue by ptr727** [esphome/issues#1870]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff TH10

**ESPHome version (latest production, beta, dev branch)**

1.16.2

**Affected component:**

dallas

**Description of problem:**
Running up to version 16.0.0 no problems with dallas.
After upgrading to 16.2 all dallas sensors started reporting `Scratch pad checksum invalid!` errors:
`[01:58:14][W][dallas.sensor:146]: 'sonoff_th10_hot_recirc_pump_recirc_temp' - Scratch pad checksum invalid!`

**Problem-relevant YAML-configuration entries:**
```yaml
  # https://esphome.io/components/sensor/dallas.html
  - platform: dallas
    address: 0x05011455296AAA28
    name: ${device_name}_recirc_temp
    id: recirc_temp
    # https://esphome.io/components/sensor/index.html#sliding-window-moving-average-exponential-moving-average
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
          send_first_at: 3
```
Full config: https://github.com/ptr727/ESPHome-Config/blob/develop/sonoff_th10_hot_recirc_pump.yaml

**Logs (if applicable):**

```
[01:58:14][W][dallas.sensor:146]: 'sonoff_th10_hot_recirc_pump_recirc_temp' - Scratch pad checksum invalid!
```

**Additional information and things you've tried:**

If I change the docker image from `esphome:latest` back to `esphome:16.0.0` the problem goes away.
If I switch to `esphome:latest` or `esphome:beta` the error returns.
