### ISSUE TITLE
Function (Time -platform: sntp Inaccurate or fails

### ISSUE THREAD

**Issue by emilioaray-dev** [esphome/issues#1872]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker-compose.yml

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32-wroom-devkit

**ESPHome version (latest production, beta, dev branch)**

Home Assistant 2021.2.3

**Affected component:**

https://esphome.io/components/time.html#time-on-time

**Description of problem:**
It works correctly for an interval of 4 hours, then the ignition times begin to decrease. From 15 minutes they go down to 9.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: watercooler
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  level: DEBUG

wifi:
  ssid: 'TPLINK-ARAY2'
  password: '*****'

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'Watercooler Fallback Hotspot'
    password: '*********'

captive_portal:

# Enable Home Assistant API
api:
  password: '********'
ota:
  password: '********'

mqtt:
  broker: 192.168.1.39

web_server:
  port: 80

switch:
  - platform: gpio
    name: 'Compresor'
    pin: 23
    icon: 'mdi:snowflake-melt'
    restore_mode: ALWAYS_OFF #State Start Off
    id: 'compresor'
    on_turn_on:
      - logger.log: 'Compresor On!'
    on_turn_off:
      - logger.log: 'Compresor Off!'

  - platform: restart
    name: 'Reset Compresor'
    id: 'ResetCompresor'
    on_turn_on:
      - logger.log: 'Reboot Compresor!'

time:
  - platform: sntp
    # ... update_interval: 4hours
    on_time:
      # Every 1 Hours
      - seconds: 0
        minutes: 0
        hours: /1
        then:
          - logger.log: 'On 15 min, Compresor!'
          - switch.turn_on: compresor
          - delay: 15min
          - logger.log: 'Off 45 min, Compresor!'
          - switch.turn_off: compresor

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

https://drive.google.com/file/d/1rT-p8Rr22vlkhekA6FWumTjL-vFNOD75/view?usp=sharing
