### ISSUE TITLE
ESP32 Arduino loop task stack full. Getting Kernel panic

### ISSUE THREAD

**Issue by justlikeef** [esphome/issues#1875]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

WSL2 git clone

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 WROVER

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**
Kernel Panic

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```substitutions:
  device_name: "Filter Pump Dev"
  emer_temp: "34"

esphome:
  name: filter_pump_dev
  platform: ESP32
  board: esp-wrover-kit
  on_boot:
    priority: -100
    then:
      - script.execute: show_oper_mode
      - script.execute: show_run_mode
      - script.execute: rotate_display

globals:
  # 0 - Off   1-Local Only  2-Manual   3-Automatic
  - id: oper_mode
    type: int
    restore_value: yes
    initial_value: "3"
  - id: auto_run_state
    type: int
    restore_value: yes
    initial_value: "0"
  - id: man_run_state
    type: int
    restore_value: yes
    initial_value: "0"
  - id: loc_run_state
    type: int
    restore_value: yes
    initial_value: "0"
  - id: emer_run_state
    type: int
    restore_value: yes
    initial_value: "0"

wifi:
  ssid: !secret wireless_ssid
  password: !secret wireless_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.120
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Filter Pump"
    password: "m1KtNbN1uc9T"

captive_portal:

logger:
  logs:
    light: info

web_server:
  port: 80
  auth:
    username: admin
    password: !secret dev_web_server_password

api:
  password: !secret dev_api_password

ota:
  password: !secret dev_ota_password

script:
  - id: update_oper_mode_text
    then:
      - text_sensor.template.publish:
          id: oper_mode_text
          state: !lambda |-
            int oper_mode_int = int(id(oper_mode));
            if (oper_mode_int == 0) {
              ESP_LOGD("main", "Operating mode Off");
              return "OFF";
            }
            if (oper_mode_int == 1) {
              ESP_LOGD("main", "Operating mode LOCAL ONLY");
              return "LOCAL ONLY";
            }
            if (oper_mode_int == 2) {
              ESP_LOGD("main", "Operating mode MANUAL");
              return "MANUAL";
            }
            ESP_LOGD("main", "Operating mode AUTOMATIC");
            return "AUTOMATIC";
  - id: update_pump_status_text
    then:
      - lambda: |-
          ESP_LOGD("main","beginstate");
          if (int(id(oper_mode)) == 0) {
            ESP_LOGD("main","OFF");
            id(pump_status_text).publish_state("OFF");
          } else {
            ESP_LOGD("main","NOTOFF");
            if (int(id(auto_run_state)) == 1) {
              ESP_LOGD("main","ON");
              id(pump_status_text).publish_state("ON");
            } else {
              ESP_LOGD("main","NOTRUNNING");
              id(pump_status_text).publish_state("STANDBY");
            }
          }
          ESP_LOGD("main","INVALID");
          id(pump_status_text).publish_state("ERROR");
  - id: inc_oper_mode
    then:
      - lambda: |-
          if (id(oper_mode) < 3) {
            id(oper_mode) += 1;
          }
      - script.stop: update_oper_mode_text
      - script.execute: update_oper_mode_text
      - script.stop: check_run
      - script.execute: check_run
  - id: dec_oper_mode
    then:
      - lambda: |-
          if (id(oper_mode) > 0) {
            id(oper_mode) -= 1;
          }
      - script.stop: update_oper_mode_text
      - script.execute: update_oper_mode_text
      - script.stop: check_run
      - script.execute: check_run
  - id: check_run
    then:

  - id: check_is_running
    then:
      
  - id: show_oper_mode
    then:
      - script.execute: update_oper_mode_text
      - if:
          condition:
            lambda: |-
              if (id(oper_mode) < 3) {
                return true;
              }
              return false;
          then:
            if:
              condition:
                lambda: |-
                  if (id(oper_mode) > 0) {
                    return true;
                  }
                  return false;
              then:
                while:
                  condition:
                    lambda: |-
                      if (id(oper_mode) > 0) {
                        return true;
                      }
                      return false;
                  then:
                    - light.toggle: blue_led
                    - delay: 1s 
              else:
                light.turn_off: blue_led
          else:
            light.turn_on: blue_led
  - id: show_run_mode
    then:
      - logger.log: "show_run_mode"
      - logger.log: "show_run_mode: call update_pump_status_text"
      - script.execute: update_pump_status_text
      - logger.log: "show_run_mode: after update_pump_status_text"
      - if:
          condition:
            lambda: |-
              if (
                (
                  id(emer_run_state) == 1 || 
                  id(man_run_state) == 1 || 
                  id(auto_run_state) == 1 || 
                  id(loc_run_state) == 1
                ) 
                && (
                  id(phase_a).state &&
                  id(phase_b).state
                )
              ) {
                return true;
              }
              return false;
          then:
            while:
              condition:
                lambda: |-
                  if ((id(emer_run_state) == 1 || id(man_run_state) == 1 || id(auto_run_state) == 1 || id(loc_run_state) == 1) && (id(phase_a).state && id(phase_b).state)) {
                    return true;
                  }
                  return false;
              then:
                - light.toggle: yellow_led
                - delay: 250ms
          else:
            script.execute: show_emer_run
  - id: show_emer_run
    then:
      if:
        condition:
          - switch.is_on: pump_emergency_run
        then:
          while:
            condition:
              - switch.is_on: pump_emergency_run
            then:
              - light.toggle: yellow_led
              - delay: 500ms
        else:
          - script.execute: show_manual_run
  - id: show_manual_run
    then:
      if:
        condition:
          or:
            - switch.is_on: pump_manual_run
            - switch.is_on: pump_local_run
        then:
          while:
            condition:
              or:
                - switch.is_on: pump_manual_run
                - switch.is_on: pump_local_run
            then:
              - light.toggle: yellow_led
              - delay: 1s
        else:
          - script.execute: show_normal_run
  - id: show_normal_run
    then:
  - id: rotate_display
    then:
      while:
        condition:
          lambda: |-
            return true;
        then:
          - display.page.show_next: status_display
          - delay: 5s

heartbeat_led:
  pin: 23
  
status_led:
  pin: 19

i2c:
  sda: 21
  scl: 22

font:
  - file: "OpenSans-Regular.ttf"
    id: OpenSans13
    size: 13
  - file: "OpenSans-ExtraBold.ttf"
    id: OpenSansBold20
    size: 20
    
image:
  - file: "wifi.jpg"
    id: wifi_logo
    type: binary
    resize: 16x16

display:
  - platform: ssd1306_i2c
    id: status_display
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 1s
    pages:
      - id: status_1
        lambda: |-
          it.strftime(0, 0, id(OpenSans13), TextAlign::TOP_LEFT, "%H:%M:%S", id(sntp_time).now());
          it.image(90, 0, id(wifi_logo));
          if (!wifi_wificomponent->is_connected()) {
            it.print(112, 8, id(OpenSans13), TextAlign::CENTER_LEFT, "X");
          } else {
            int sigstrength = WiFi.RSSI();
            if (sigstrength >= -80) {
              it.filled_rectangle(108, 14, 3, 1);
            }
            if (sigstrength >= -70) {
              it.filled_rectangle(114, 10, 3, 5);
            }
            if (sigstrength >= -60) {
              it.filled_rectangle(119, 5, 3, 10);
            }
            if (sigstrength >= -50) {
              it.filled_rectangle(124, 0, 3, 15);
            }
          }
          it.printf(0, 16, id(OpenSansBold20), "%s", id(oper_mode_text).state.c_str());
          it.printf(0, 32, id(OpenSansBold20), "%s", id(pump_status_text).state.c_str());
      - id: status_2
        lambda: |-
          IPAddress ip = WiFi.localIP();
          it.printf(0, 0, id(OpenSans13), "%s", ip.toString().c_str());
          it.printf(0, 16, id(OpenSans13), "%s", get_mac_address_pretty().c_str());
          it.printf(0, 28, id(OpenSans13), "%s", WiFi.SSID().c_str());
          it.printf(0, 42, id(OpenSans13), "RSSI: %i", WiFi.RSSI());
time:
  - platform: sntp
    id: sntp_time
    on_time:
    - trigger_id: morning
      cron: '0 /2 0-9 * * *'
      then:
        - switch.turn_on: pump_automatic_run
    - trigger_id: evening
      cron: '0 /2 22-23 * * *'
      then:
        - switch.turn_on: pump_automatic_run
    - trigger_id: daytime
      cron: '0 /2 10-21 * * *'
      then:
        - switch.turn_off: pump_automatic_run
uart:
  rx_pin: 14
  tx_pin: 13
  baud_rate: 9600
        
output:
  - platform: gpio
    pin: 18
    id: blue_led_output
  - platform: gpio
    pin: 4
    id: yellow_led_output

light:
  - platform: binary
    id: blue_led
    output: blue_led_output
    internal: true
  - platform: binary
    output: yellow_led_output
    id: yellow_led
    internal: true

dallas:
  - pin: 15

text_sensor:
  - platform: template
    name: "$device_name Uptime"
    id: uptime_human
    icon: mdi:clock-start
  - platform: version
    name: "$device_name ESPHome Version"
    id: esphome_version
  - platform: template
    name: "$device_name Oper Mode"
    id: oper_mode_val
    lambda: |-
      return esphome::to_string(id(oper_mode));
  - platform: template
    name: "$device_name Operating Mode"
    icon: "mdi:run"
    id: oper_mode_text
  - platform: template
    name: "$device_name Pump Status"
    icon: "mdi:water-pump"
    id: pump_status_text
  - platform: wifi_info
    ip_address:
      name: "$device_name IP Address"
    ssid:
      name: "$device_name Connected SSID"
    bssid:
      name: "$device_name Connected BSSID"
    mac_address:
      name: "$device_name Mac Wifi Address"
      
sensor:
  - platform: uptime
    id: uptime_seconds
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_seconds).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();
  - platform: wifi_signal
    id: wifi_signal_strength
    name: "$device_name WiFi Signal Strength"
    update_interval: 60s
  - platform: dallas
    address: 0xEE01203373AB8428
    id: outside_temp
    name: "$device_name Outside Temperature"
    accuracy_decimals: 2
    filters:
      - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    on_value_range:
      - above: $emer_temp
        then:
          - switch.turn_off: pump_emergency_run
      - below: $emer_temp
        then:
          - switch.turn_on: pump_emergency_run
  - platform: pzemac
    current:
      name: "$device_name Current"
    voltage:
      name: "$device_name Voltage"
    energy:
      name: "$device_name Energy"
    power:
      name: "$device_name Power"
    frequency:
      name: "$device_name Frequency"
    power_factor:
      name: "$device_name Power Factor"
    update_interval: 60s
    
switch:
  - platform: gpio
    pin: 26
    id: phase_a
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - script.stop: check_is_running
        - script.execute: check_is_running
    on_turn_off:
      then:
        - script.stop: check_is_running
        - script.execute: check_is_running
  - platform: gpio
    pin: 27
    id: phase_b
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - script.stop: check_is_running
        - script.execute: check_is_running
    on_turn_off:
      then:
        - script.stop: check_is_running
        - script.execute: check_is_running
  - platform: template
    id: pump_automatic_run
    name: "$device_name Run by Schedule"
    lambda: |-
      if (id(auto_run_state) == 1) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - globals.set:
          id: auto_run_state
          value: "1"
    turn_off_action:
      - globals.set:
          id: auto_run_state
          value: "0"
    on_turn_on:
      then:
        - script.stop: show_run_mode
        - script.execute: show_run_mode
    on_turn_off:
      then:
        - script.stop: show_run_mode
        - script.execute: show_run_mode
  - platform: template
    id: pump_manual_run
    name: "$device_name Manual Run"
    lambda: |-
      if (id(man_run_state) == 1) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - globals.set:
          id: man_run_state
          value: "1"
    turn_off_action:
      - globals.set:
          id: man_run_state
          value: "0"
    on_turn_on:
      then:
        - script.stop: show_run_mode
        - script.execute: show_run_mode
    on_turn_off:
      then:
        - script.stop: show_run_mode
        - script.execute: show_run_mode
  - platform: template
    id: pump_emergency_run
    name: "$device_name Emergency Run"
    lambda: |-
      if (id(emer_run_state) == 1) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - globals.set:
          id: emer_run_state
          value: "1"
    turn_off_action:
      - globals.set:
          id: emer_run_state
          value: "0"
  - platform: template
    id: pump_local_run
    lambda: |-
      if (id(loc_run_state) == 1) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - globals.set:
          id: loc_run_state
          value: "1"
    turn_off_action:
      - globals.set:
          id: loc_run_state
          value: "0"
  - platform: template
    id: mode_up
    name: "$device_name Mode Up"
    turn_on_action:
      then:
        - script.execute: inc_oper_mode
    on_turn_on:
      then:
        - script.stop: check_run
        - script.execute: check_run
  - platform: template
    name: "$device_name Mode Down"
    id: mode_down
    turn_on_action:
      then:
        - script.execute: dec_oper_mode
    on_turn_on:
      then:
        - script.stop: check_run
        - script.execute: check_run
  - platform: template
    id: pump_is_running
    name: "$device_name Pump"
    icon: "mdi:run"
    lambda: |-
      if (id(phase_a).state and id(phase_b).state) {
        return true;
      }
      return false;

binary_sensor:
  - platform: gpio
    pin:
      number: 17
      mode: INPUT_PULLUP
      inverted: yes
    id: on_button
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "On double click"
          - script.stop: inc_oper_mode
          - script.execute: inc_oper_mode
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "On Single click"
          - switch.turn_on: pump_local_run
  - platform: gpio
    pin:
      number: 16
      mode: INPUT_PULLUP
      inverted: yes
    id: off_button
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Off Double click"
          - script.stop: dec_oper_mode
          - script.execute: dec_oper_mode
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Off Single click"
          - switch.turn_off: pump_local_run


**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```[20:45:59]ets Jun  8 2016 00:22:57
[20:45:59]
[20:45:59]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[20:45:59]configsip: 0, SPIWP:0xee
[20:45:59]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[20:45:59]mode:DIO, clock div:2
[20:45:59]load:0x3fff0018,len:4
[20:45:59]load:0x3fff001c,len:1044
[20:45:59]load:0x40078000,len:8896
[20:45:59]load:0x40080400,len:5828
[20:45:59]entry 0x400806ac
[20:45:59][I][logger:166]: Log initialized
[20:45:59][C][heartbeat_led:020]: Setting up Heartbeat LED...
[20:45:59][C][status_led:014]: Setting up Status LED...
[20:45:59][C][ota:366]: There have been 9 suspected unsuccessful boot attempts.
[20:45:59][I][app:029]: Running through setup()...
[20:45:59][C][uart_esp32:072]: Setting up UART...
[20:45:59][C][switch.gpio:011]: Setting up GPIO Switch 'phase_a'...
[20:45:59][D][switch:025]: 'phase_a' Turning OFF.
[20:45:59][D][switch:045]: 'phase_a': Sending state OFF
[20:45:59][D][switch:025]: 'phase_a' Turning OFF.
[20:45:59][C][switch.gpio:011]: Setting up GPIO Switch 'phase_b'...
[20:45:59][D][switch:025]: 'phase_b' Turning OFF.
[20:45:59][D][switch:045]: 'phase_b': Sending state OFF
[20:45:59][D][switch:025]: 'phase_b' Turning OFF.
[20:45:59][D][binary_sensor:034]: 'on_button': Sending initial state OFF
[20:45:59][D][binary_sensor:034]: 'off_button': Sending initial state OFF
[20:45:59][C][dallas.sensor:032]: Setting up DallasComponent...
[20:45:59][D][text_sensor:015]: 'Filter Pump Dev ESPHome Version': Sending state '1.17.0-dev Feb 25 2021, 20:34:12'
[20:45:59][D][text_sensor:015]: 'Filter Pump Dev Mac Wifi Address': Sending state '3C:71:BF:83:D3:14'
[20:45:59][C][ssd1306_i2c:010]: Setting up I2C SSD1306...
[20:46:00][C][wifi:033]: Setting up WiFi...
[20:46:00][I][wifi:194]: WiFi Connecting to 'justlikeef'...
[20:46:00][D][text_sensor:015]: 'Filter Pump Dev Oper Mode': Sending state '3'
[20:46:00][D][text_sensor:015]: 'Filter Pump Dev Uptime': Sending state '1s'
[20:46:00][D][sensor:092]: 'uptime_seconds': Sending state 0.58300 s with 0 decimals of accuracy
[20:46:00][D][switch:045]: 'Filter Pump Dev Run by Schedule': Sending state OFF
[20:46:00][D][main:183]: show_run_mode
[20:46:00][D][main:186]: show_run_mode: call update_pump_status_text
[20:46:00]***ERROR*** A stack overflow in task loopTask has been detected.
[20:46:00]abort() was called at PC 0x4008d580 on core 1
[20:46:00]
[20:46:00]Backtrace: 0x4008d338:0x3ffaff20 0x4008d569:0x3ffaff40 0x4008d580:0x3ffaff60 0x4008a628:0x3ffaff80 0x4008c2b0:0x3ffaffa0 0x4008c266:0xabba1234
[20:46:00]
[20:46:00]Rebooting...


**Additional information and things you've tried:**
Power supply
Multiple development boards



<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->

**Comment by justlikeef** [comment]
Verbose logging:
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:166]: Log initialized
[C][heartbeat_led:020]: Setting up Heartbeat LED...
[C][status_led:014]: Setting up Status LED...
[C][ota:366]: There have been 2 suspected unsuccessful boot attempts.
[I][app:029]: Running through setup()...
[V][app:030]: Sorting components by setup priority...
[C][uart_esp32:072]: Setting up UART...
[C][switch.gpio:011]: Setting up GPIO Switch 'phase_a'...
[D][switch:025]: 'phase_a' Turning OFF.
[D][switch:045]: 'phase_a': Sending state OFF
[D][switch:025]: 'phase_a' Turning OFF.
[C][switch.gpio:011]: Setting up GPIO Switch 'phase_b'...
[D][switch:025]: 'phase_b' Turning OFF.
[D][switch:045]: 'phase_b': Sending state OFF
[D][switch:025]: 'phase_b' Turning OFF.
[D][binary_sensor:034]: 'on_button': Sending initial state OFF
[D][binary_sensor:034]: 'off_button': Sending initial state OFF
[V][preferences:260]: nvs_get_blob('3'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[V][preferences:260]: nvs_get_blob('4'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[V][preferences:260]: nvs_get_blob('5'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[V][preferences:260]: nvs_get_blob('6'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[V][preferences:260]: nvs_get_blob('7'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[V][preferences:260]: nvs_get_blob('8'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[V][preferences:260]: nvs_get_blob('9'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[C][dallas.sensor:032]: Setting up DallasComponent...
[D][text_sensor:015]: 'Filter Pump Dev ESPHome Version': Sending state '1.17.0-dev Feb 26 2021, 05:14:17'
[D][text_sensor:015]: 'Filter Pump Dev Mac Wifi Address': Sending state '3C:71:BF:83:D3:14'
[C][ssd1306_i2c:010]: Setting up I2C SSD1306...
[V][preferences:260]: nvs_get_blob('12'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[C][wifi:033]: Setting up WiFi...
[V][wifi_esp32:036]: Enabling STA.
[V][esp-idf:000]: I (535) wifi: wifi driver task: 3ffcbe90, prio:23, stack:3584, core=0

[V][esp-idf:000]: I (1339) wifi: wifi firmware version: 7997e4b

[V][esp-idf:000]: I (1340) wifi: config NVS flash: enabled

[V][esp-idf:000]: I (1342) wifi: config nano formating: disabled

[V][esp-idf:000]: I (1349) wifi: Init dynamic tx buffer num: 32

[V][esp-idf:000]: I (1355) wifi: Init data frame dynamic rx buffer num: 32

[V][esp-idf:000]: I (1363) wifi: Init management frame dynamic rx buffer num: 32

[V][esp-idf:000]: I (1371) wifi: Init management short buffer num: 32

[V][esp-idf:000]: I (1378) wifi: Init static rx buffer size: 1600

[V][esp-idf:000]: I (1385) wifi: Init static rx buffer num: 16

[V][esp-idf:000]: I (1392) wifi: Init dynamic rx buffer num: 32

[V][esp-idf:000]: I (1467) wifi: mode : softAP (3c:71:bf:83:d3:15)

[V][esp-idf:000]: I (1468) wifi: Total power save buffer number: 16

[V][esp-idf:000]: I (1470) wifi: Init max length of beacon: 752/752

[V][esp-idf:000]: I (1478) wifi: Init max length of beacon: 752/752

[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:337] _eventCallback(): Event: 14 - AP_STOP
[V][wifi_esp32:419]: Event: WiFi AP start
[V][wifi_esp32:352]: Event: WiFi ready
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
Debug exception reason: Stack canary watchpoint triggered (loopTask)
Core 1 register dump:
PC      : 0x40139672  PS      : 0x00060c36  A0      : 0x8008aaa0  A1      : 0x3ffb0070
A2      : 0x3f413e84  A3      : 0x00000069  A4      : 0x3f4141b8  A5      : 0x3f413f10
A6      : 0x00060820  A7      : 0x0000cdcd  A8      : 0x8013965d  A9      : 0x3ffb0050
A10     : 0x3ffb6678  A11     : 0x3f414cd9  A12     : 0x3f413f10  A13     : 0x3f413e84
A14     : 0x00000069  A15     : 0x3f414ccc  SAR     : 0x00000004  EXCCAUSE: 0x00000001
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff

Backtrace: 0x40139672:0x3ffb0070 0x4008aa9d:0x3ffb00a0 0x4008c913:0x3ffb00d0 0x4008cf87:0x3ffb00f0 0x400858fc:0x3ffb0110 0x40085931:0x3ffb0130 0x40085df5:0x3ffb0150 0x4000beaf:0x3ffb0170 0x4008930e:0x3ffb0190 0x40089554:0x3ffb01b0 0x40085ec8:0x3ffb01d0 0x40085ef8:0x3ffb01f0 0x40086049:0x3ffb0220 0x4013fd7b:0x3ffb0240 0x4013c095:0x3ffb0500 0x40139675:0x3ffb0550 0x4008aa9d:0x3ffb0580 0x4008c913:0x3ffb05b0 0x4008cf87:0x3ffb05d0 0x400858fc:0x3ffb05f0 0x40085931:0x3ffb0610 0x40085df5:0x3ffb0630 0x4000beaf:0x3ffb0650 0x40085e33:0x3ffb0670 0x4000bef5:0x3ffb0690 0x4008253e:0x3ffb06b0 0x40082565:0x3ffb06d0 0x4011c794:0x3ffb06f0 0x400f8be8:0x3ffb0710 0x400e83b1:0x3ffb0810 0x400e8410:0x3ffb0840 0x400e74e5:0x3ffb0870 0x4017e559:0x3ffb0890 0x4017e615:0x3ffb08b0 0x400eac3d:0x3ffb08d0 0x400f5732:0x3ffb0920 0x40103fa3:0x3ffb1fb0 0x40089a75:0x3ffb1fd0

**Comment by justlikeef** [comment]
May be the same as #1605

**Comment by justlikeef** [comment]
Looks like the text_sensor.publish action causes the stack overflow.

**Comment by justlikeef** [comment]
Calling the update function using id(text_sensor)->update() will also cause the stack overflow.

**Comment by kbx81** [comment]
I've run into this before with large configs such as this. I edited `main.cpp in my `~/.platformio/packages/framework-arduinoespressif32/cores/esp32` folder to enlarge the stack. YMMV.

```c
xTaskCreateUniversal(loopTask, "loopTask", 8192 * 4, NULL, 1, &loopTaskHandle, CONFIG_ARDUINO_RUNNING_CORE);
```

...I added the `* 4` to quadruple the stack size to ~32KB.

**Comment by justlikeef** [comment]
Thank you!!! I haven't had time to dig through code yet.

Maybe this should be the default for the ESP32 where there are more
resources?

Thanks,
Rob

**Comment by kbx81** [comment]
Unfortunately that piece isn't a part of the ESPHome codebase...so I guess go complain to the Arduino folks? 😁😇

**Comment by glmnet** [comment]
I wonder if there is a PR for that. A #define constant which could be redefined in platformio_options would work great

**Comment by trvrnrth** [comment]
@glmnet It would appear so. And it's merged! https://github.com/espressif/arduino-esp32/pull/4564. Looks like it made it into https://github.com/espressif/arduino-esp32/releases/tag/1.0.5 / https://github.com/platformio/platform-espressif32/releases/tag/v3.1.0

**Comment by glmnet** [comment]
Cool then a mechanism too set should be documented. 

I don't know is ESPHome is merging build_flags inside platformio_options

**Comment by trvrnrth** [comment]
@glmnet At the moment it [overwrites them](https://github.com/esphome/esphome/blob/69879920eb21d92a8e06a16d559a5729a538456a/esphome/writer.py#L275) rather than merging which is problematic. If a special case was added to merge in build flags then something like this would work:
```
esphome:
  ...
  arduino_version: latest
  platformio_options:
    build_flags: 
      - -DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768
```
