### ISSUE TITLE
Substitutions within substitutions not working with packages

### ISSUE THREAD

**Issue by edenhaus** [esphome/issues#1878]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Docker

**ESP (ESP32/ESP8266, Board/Sonoff):** All devices

**ESPHome version (latest production, beta, dev branch)** v1.16.2 and also the dev version

**Affected component:** https://www.esphome.io/guides/configuration-types.html#substitutions

**Description of problem:**
The problem is when we use substitutions in other substitutions variables, that in some cases not all will be replaced correctly.
The problem exists only if packages are used and that have substitutions key itself in the package.
As you can see in the in the logs below, the substitutions variable **num** will not replaced correctly.

**Problem-relevant YAML-configuration entries:**
```yaml
# file: packages/wifi_info.yaml
text_sensor:
  - platform: wifi_info
    bssid:
      name: ${device} Connected BSSID
```

```yaml
# file: packages/wifi_info.yaml
substitutions:
  device: esp${num}

packages:
  wifi_info: !include wifi_info.yaml

esphome:
  name: ${device}
  build_path: ./build/${device}

wifi:
  ap:
    ssid: ${device}_AP
    password: testtestAP
  ssid: test
  password: testtestAP
  manual_ip:
    static_ip: 192.168.1.1${num}
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

captive_portal:

api:

ota:

logger:

```

```yaml
# file: test.yaml
substitutions:
  num: "02"

packages:
  device_base: !include packages/test_base.yaml

esphome:
  platform: ESP8266
  board: esp8285
```

**Logs (if applicable):**

```
INFO Reading configuration /config/test.yaml...
INFO Configuration is valid!
substitutions:
  device: esp02
  num: '02'
esphome:
  name: esp02
  build_path: ./build/esp02
  platform: ESP8266
  board: esp8285
  arduino_version: espressif8266@2.6.2
  platformio_options: {}
  esp8266_restore_from_flash: false
  board_flash_mode: dout
  includes: []
  libraries: []
text_sensor:
- platform: wifi_info
  bssid:
    name: esp${num} Connected BSSID
wifi:
  ap:
    ssid: esp02_AP
    password: testtestAP
    ap_timeout: 1min
  manual_ip:
    static_ip: 192.168.1.102
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 0.0.0.0
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  networks:
  - ssid: test
    password: testtestAP
    priority: 0.0
  use_address: 192.168.1.102
captive_portal: {}
api:
  port: 6053
  password: ''
  reboot_timeout: 15min
ota:
  safe_mode: true
  port: 8266
  password: ''
  reboot_timeout: 5min
  num_attempts: 10
logger:
  baud_rate: 115200
  tx_buffer_size: 512
  hardware_uart: UART0
  level: DEBUG
  logs: {}
  esp8266_store_log_strings_in_flash: true
```

**Additional information and things you've tried:**
