### ISSUE TITLE
PollingComponent::set_update_interval not updating the Component::update() TimeFunction

### ISSUE THREAD

**Issue by olicooper** [esphome/issues#189]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows - Python27 pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (NodeMCU v2)

**Affected component:**

https://esphome.io/components/sensor/pulse_counter.html

**Description of problem:**

When I call `id(power_kw).set_update_interval(new_update_interval);` in my lambda, I expect the next call to the function to occur at the new interval. Unfortunately the interval remains the same but the amount of 'pulses' recorded increases due to the way the function calculates the value using `get_update_interval()`

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: pulse_counter
    pin: D5
    unit_of_measurement: 'kW'
    name: Power kW
    id: power_kw
    filters:
      - multiply: 0.06
    internal_filter: 1ms
    update_interval: 30s
    accuracy_decimals: 2
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    on_raw_value:
      then:
        - lambda: |- 
            uint32_t curr_update_interval = id(power_kw).update_interval();
            float pulse_count = x; //id(power_kw).raw_state;
            // [
            //   pulse_count <15 == 30000 (30s)
            //   pulse_count 16-30 == 15000 (15s)
            //   pulse_count >30 == 10000 (10s)
            // ]
            uint32_t new_update_interval = (pulse_count < 15 ? 30000 : pulse_count < 30 ? 15000 : 10000);
            
            ESP_LOGD("pulse_counter.power_kw", "START change interval check");
            

            if (curr_update_interval != new_update_interval) {
              ESP_LOGD("pulse_counter.power_kw", "Raw value=\%0.2f, new interval=\%d", pulse_count, new_update_interval);
              id(power_kw).set_update_interval(new_update_interval);
            }
            ESP_LOGD("pulse_counter.power_kw", "END change interval check");

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

I have debugged the issue and came up with a potential fix...

### component.cpp
Update the `set_update_interval` function to re-create the "update" callback with the new interval:
```
void PollingComponent::set_update_interval(uint32_t update_interval) { 
  this->update_interval_ = update_interval;
  this->set_interval("update", this->update_interval_, [this]() { this->update(); });
}
```
Then update the `set_interval` function to ensure the "update" callback isn't executed immediately:
```
void Component::set_interval(const std::string &name, uint32_t interval, std::function<void()> &&f) {  // NOLINT
  const uint32_t now = millis();
  // only put offset in lower half
  uint32_t offset = 0;
  if (interval != 0)
    offset = (random_uint32() % interval) / 2;
  ESP_LOGVV(TAG, "set_interval(name='%s', interval=%u, offset=%u)", name.c_str(), interval, offset);
  uint32_t last_execution_ = (now - interval - offset);
  if (!name.empty()) {
    if (this->cancel_interval(name)) {
      last_execution_ = now;
    }
  }
  struct TimeFunction function = {
      .name = name,
      .type = TimeFunction::INTERVAL,
      .interval = interval,
      .last_execution = last_execution_,
      .f = std::move(f),
      .remove = false,
  };
  this->time_functions_.push_back(function);
}
```
