### ISSUE TITLE
Failed config with the ArduinoPortExpander and analog reading

### ISSUE THREAD

**Issue by davidusb-geek** [esphome/issues#1892]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Ubuntu 20.04 LTS, esphome installed using pip

**ESP (ESP32/ESP8266, Board/Sonoff):**
Wemos d1 mini and the ArduinoPortExpander installed on an Arduino Uno

**ESPHome version (latest production, beta, dev branch)**
v1.16.2

**Affected component:**
https://esphome.io/cookbook/arduino_port_extender.html
https://esphome.io/components/sensor/adc.html
https://esphome.io/components/sensor/ct_clamp.html

**Description of problem:**
Hi, I've been using the ArduinoPortExpander with esphome to control mostly relays, digital outputs (to LEDs and buzzers, etc) and for some binary sensors. I'm using a wemos d1 mini and an Arduino Uno as the APE device.
Now I want to read two power loads in my house using the analog input pins and two different current clamps (SCT-013-030). I want to use for this the CT Clamp current sensor from esphome (https://esphome.io/components/sensor/ct_clamp.html). The problem is that analog sensor output from the APE is not a voltage. So either using the ct_clamp or the analog to digital (https://esphome.io/components/sensor/adc.html) sensor integrations gives a failed configuration error.

**Problem-relevant YAML-configuration entries:**
```
esphome:
  name: main_tableau_elec
  platform: ESP8266
  board: d1_mini
  includes:
    - arduino_port_expander.h

wifi:
  ssid: !secret wifi_id
  password: !secret wifi_pwd

logger:
  level: DEBUG

api:
  password: !secret ota_pwd

ota:
  password: !secret ota_pwd

i2c:
  id: i2c_component

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExpander(i2c_component, 0x08, true);
      return {ape_component};

sensor:
  - platform: custom
    lambda: |-
      return {ape_analog_input(ape, 0),  // 0 = A0
              ape_analog_input(ape, 1)};  // 1 = A1
    sensors:
      - name: Analog A1
        id: analog_a1
        filters:
          - throttle: 10s
      - name: Analog A2
        id: analog_a2
        filters:
          - throttle: 10s
  - platform: adc
    pin: analog_a1
    name: ADC1
    update_interval: 60s
  - platform: adc
    pin: analog_a2
    name: ADC2
    update_interval: 60s
```

**Logs (if applicable):**
And the error message obtained is this:
```
Failed config

sensor.adc: [source main_tableau_elec.yaml:61]
  platform: adc
  
  Cannot resolve pin name 'analog_a1' for board d1_mini.
  pin: analog_a1 [source main_tableau_elec.yaml:62]
  name: ADC1
  update_interval: 60s
sensor.adc: [source main_tableau_elec.yaml:65]
  platform: adc
  
  Cannot resolve pin name 'analog_a2' for board d1_mini.
  pin: analog_a2 [source main_tableau_elec.yaml:66]
  name: ADC2
  update_interval: 60s
```

**Additional information and things you've tried:**
The same error arises if I try to use the ct_clamp integration. Do you think that there is a way to achieve some compatibility with the ct_clamp or the adc esphome integrations? Could you help me to solve this issue? What modifications as custom codes needs to be made to achieve this compatibility?
A secondary solution for me is to connect a ADS1115 directly to my wemos d1 mini ESP8266, but then it will be a shame to not use those analog pins available in the Arduino Uno APE.
Thank you for your help
