### ISSUE TITLE
ili9431 display colors inverted on (older) M5Stack Cores

### ISSUE THREAD

**Issue by Josverl** [esphome/issues#1893]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Python 3.8.5 on Windows 10 
pip 
**ESP (ESP32/ESP8266, Board/Sonoff):**
 ESP32 
 - M5stack Core - hardware rev 2017.11
 - M5stack Fire - hardware rev 2018.2a

**ESPHome version (latest production, beta, dev branch)**

ESPHome Version: 1.16.2
**Affected component:**

https://esphome.io/components/display/ili9341.html

**Description of problem:**
All colors are inverted 
Color used in code | Expected| Color shown on display
---------------------|-----------|--
COLOR_BLACK | Black | White 
COLOR_WHITE | White| Black
Color(1,0,0) | Red | Purple 
Color(0,1,0) | Green | orange 
Color(0,0,1) | Blue | Light Blue

**Problem-relevant YAML-configuration entries:**
```yaml
display:
  - platform: ili9341
    model: M5Stack
    cs_pin: 14
    dc_pin: 27
    led_pin: 32
    reset_pin: 33
    rotation: 0
    update_interval: 10s
    lambda: |-
      // Draw a circle in the middle of the display
      it.fill(id(COLOR_BLACK));
      it.filled_circle(it.get_width() / 2, it.get_height() / 2, 30, id(RED));
      it.rectangle(10,10,200,200,id(BLUE));
      it.print(0, 0, id(my_font), id(GREEN),"Hello World!");

color: #ILI colors inverted :-(
    - id: RED
      red:   1
      green: 0
      blue:  0
    
    - id: BLUE
      red:     0
      green:   0
      blue:    1
    
    - id: GREEN
      red:   0
      green: 1
      blue:  0

```

**Logs (if applicable):**

```
[21:08:29][C][logger:185]: Logger:
[21:08:29][C][logger:186]:   Level: VERBOSE
[21:08:29][C][logger:187]:   Log Baud Rate: 115200
[21:08:29][C][logger:188]:   Hardware UART: UART0
[21:08:29][C][ili9341:035]: ili9341
[21:08:29][C][ili9341:035]:   Rotations: 0 °
[21:08:29][C][ili9341:035]:   Dimensions: 320px x 240px
[21:08:29][C][ili9341:036]:   Width: 320, Height: 240,  Rotation: 0
[21:08:29][C][ili9341:037]:   Reset Pin: GPIO33 (Mode: OUTPUT)
[21:08:29][C][ili9341:038]:   DC Pin: GPIO27 (Mode: OUTPUT)
[21:08:29][C][ili9341:040]:   Backlight Pin: GPIO32 (Mode: OUTPUT)
[21:08:29][C][ili9341:042]:   Update Interval: 10.0s

```

**Additional information and things you've tried:**

the ESPHome driver for the ili9342 display is [hardcoded to invert the display on the M5 Stack](https://github.com/esphome/esphome/blob/2c0fe49b86f5b1ede27e76f3ef68f5f03af22d65/esphome/components/ili9341/ili9341_display.cpp#L227), which makes the driver work incorrectly on hardware that does not need to be inverted.

i have updated the driver to allow 
- the yaml file to specify the display inversion to be configured `invert: true/false`
- i have tested this only on the m5stack

im happy to submit a PR for the code and update the relevant documentation if someone can point me to the appropriate workflows.
