### ISSUE TITLE
ESP32 Cam failes to compile with arduino_version: latest

### ISSUE THREAD

**Issue by Adi146** [esphome/issues#1894]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** pip

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP32

**ESPHome version (latest production, beta, dev branch)** 1.16.2

**Affected component:** ESP32 Camera

**Description of problem:**
esphome failes to compile with arduino_version: latest and ESP32 Camera enabled

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: ...
  platform: ESP32
  board: nodemcu-32s
  arduino_version: latest
esp32_camera:
  name: Printer Camera
  jpeg_quality: 10
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

```

**Logs (if applicable):**

```
src/esphome/components/esp32_camera/esp32_camera.cpp:58:10: error: 'FRAMESIZE_QQVGA2' was not declared in this scope
     case FRAMESIZE_QQVGA2:
          ^
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'void esphome::esp32_camera::ESP32Camera::set_frame_size(esphome::esp32_camera::ESP32CameraFrameSize)':
src/esphome/components/esp32_camera/esp32_camera.cpp:213:34: error: 'FRAMESIZE_QQVGA2' was not declared in this scope
       this->config_.frame_size = FRAMESIZE_QQVGA2;
                                  ^

```

**Additional information and things you've tried:**
