### ISSUE TITLE
2 pzem's on different pins (and therefore different UART Busses)

### ISSUE THREAD

**Issue by bjornstevens** [esphome/issues#1896]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, nodemcu amica

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

pzemac

**Description of problem:**

I can't seem to figure out how to get my 2 pzem-004T's to get read by esphome.
The issue seems to rely on that i can't define the 'uart_id' in the pzemac configuration. Is there any workaround for this?

As of now I can only select 1 of the 2 "ua's". Which makes it only possible for me to read out 1 sensor, while I would really love to read out both of them

**Problem-relevant YAML-configuration entries:**
```yaml

modbus:
    - uart_id: ua1
    

uart:
  - id: ua1
    tx_pin: D1
    rx_pin: D2
    baud_rate: 9600
    #stop_bits: 1
  - id: ua2
    tx_pin: D5
    rx_pin: D6
    baud_rate: 9600
    #stop_bits: 1
  
sensor:
  - platform: pzemac
    current:
      name: "PZEM-004T V3 Current"
    voltage:
      name: "PZEM-004T V3 Voltage"
    energy:
      name: "PZEM-004T V3 Energy"
    power:
      name: "PZEM-004T V3 Power"
    frequency:
      name: "PZEM-004T V3 Frequency"
    power_factor:
      name: "PZEM-004T V3 Power Factor"
    update_interval: 1s
    address: 1
  - platform: pzemac
    current:
      name: "PZEM-004T_2 V3 Current"
    voltage:
      name: "PZEM-004T_2 V3 Voltage"
    energy:
      name: "PZEM-004T_2 V3 Energy"
    power:
      name: "PZEM-004T_2 V3 Power"
    frequency:
      name: "PZEM-004T_2 V3 Frequency"
    power_factor:
      name: "PZEM-004T_2 V3 Power Factor"
    update_interval: 1s
    address: 2


```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

I tried playing with the addresses, changing out the modbus to something else (and also can't get it to use different connections)
I also tried to change things in the uart, but also without succes. I can only get it to pick 1 of the 2 connections, while i want both.
