### ISSUE TITLE
ESP8266 PWM issue with 1.12.2?

### ISSUE THREAD

**Issue by mmotley999** [esphome/issues#190]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker (armhf)
**ESP (ESP32/ESP8266, Board/Sonoff):**

Board/Martin Jerry SD01 dimmer
**Affected component:**

PWM Dimming

**Description of problem:**
I have one working Martin Jerry/Tessan dimmer from 1.12.1.  Flashed a second Martin Jerry SD01 dimmer module with the newest ESPHome Docker image and core (1.12.2), but for some reason the PWM that controls the dimming seems a bit whacky now.

The config below is working just fine on another Martin Jerry switch, which was compiled/pushed via 1.12.1.  See this thread for details:  https://community.home-assistant.io/t/martin-jerry-tessan-dimmer-automation-help-solved/107324

Here's what's happening now:

Pushing the dim up/down buttons does not dim the light, except under these circumstances:
  - I turn off then turn on the light.  Example:  Set dim from 100% to 50%.  Light is still at 100%.  Turn off via the main button, turn it back on, the light was come on at 50% dim.
- If the light is below 100% when it comes on, adjusting up does not work UNTIL I hit 100% dim level, then the light jumps to full brightness.

Dimming is controlled through PWM on GPIO13.

I tried forcing a recompile forcing 1.12.1 version (via "esphome_core_version: 1.12.1") but still no dice.  I did notice that AsyncTCP 1.2.0 was used under both 1.12.1 and 1.12.2, and I know this is something that changed... just an observation.

**Problem-relevant YAML-configuration entries:**
```yaml
# ##################################
# Martin Jerry Dimmer MJ-SD01
# ##################################
# D3 GPIO0: up button (inverted, input_pullup)
# TX GPIO1: down button (inverted, input_pullup)
# RX GPIO3: led5 (inverted)
# D1 GPIO5: led4 (inverted)
# D6 GPIO12: led3 (inverted)
# D7 GPIO13: pwm
# D5 GPIO14: led2 (inverted)
# D8 GPIO15: main button (input_pullup)
# D0 GPIO16: led1 + relay (inverted)
# ##################################


substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: dimmer_toyroom   # hostname & entity_id
  friendly_name: Toyroom Light   # Displayed in HA frontend
  pwm_min_power: 0%   # keep dimming functional at lowest levels
  no_delay: 0s   # transition when changing dimmer_lvl & relay delay
  transition_length: .5s   # transition when turning on/off
  long_press_min: .5s   # minimum time to activate long-press action
  long_press_max: 2s   # maximum time to activate long-press action
  long_press_up: 100%   # long press brightness
  long_press_down: 20%   # long press brightness
  long_press_main: 50%   # long press brightness
  ssid: #####
  ssidpass: #####

esphome:
  # https://esphome.io/components/esphome
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  # https://esphome.io/components/wifi
  ssid: $ssid
  password: $ssidpass
  
web_server:
  port: 80
  # https://esphome.io/components/web_server.html


logger:
  # https://esphome.io/components/logger


api:
  #password: !secret esphome_api_password
  # https://esphome.io/components/api


ota:
  #password: !secret esphome_ota_password
  # https://esphome.io/components/ota


output:
  - platform: gpio
    # https://esphome.io/components/output/gpio.html
    pin: GPIO3
    inverted: true
    id: led5

  - platform: gpio
    # https://esphome.io/components/output/gpio.html
    pin: GPIO5
    inverted: true
    id: led4

  - platform: gpio
    # https://esphome.io/components/output/gpio.html
    pin: GPIO12
    inverted: true
    id: led3

  - platform: gpio
    # https://esphome.io/components/output/gpio.html
    pin: GPIO14
    inverted: true
    id: led2

  - platform: esp8266_pwm
    # https://esphome.io/components/output/index.html#config-output
    pin: GPIO13
    id: pwm
    power_supply: relay
#    min_power: ${pwm_min_power}


light:
  - platform: monochromatic
    # https://esphome.io/components/light/monochromatic.html
    name: ${friendly_name}
    output: pwm
    default_transition_length: ${no_delay}
    gamma_correct: 0.0
    id: dimmer


power_supply:
  - id: relay
    # https://esphome.io/components/power_supply.html
    pin: 
      number: GPIO16
      inverted: True
    enable_time: ${no_delay}
    keep_on_time: ${no_delay}


binary_sensor:
  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin: 
      number: GPIO0
      inverted: True
      mode: INPUT_PULLUP
    name: ${friendly_name} Up Button
    id: up_button
    internal: True
    on_press:
      then:
        - lambda: |-
            if (id(dimmer_lvl) > .91) {
              id(dimmer_lvl) = 1.0;
            }
            else if (id(dimmer_lvl) <= .91) {
              id(dimmer_lvl) += .08;
            };
            id(apply_dimming).execute();
    on_click:
      # https://esphome.io/components/binary_sensor/index.html#on-click
      min_length: ${long_press_min}
      max_length: ${long_press_max}
      then:
        - light.turn_on:
            id: dimmer
            brightness: ${long_press_up}

  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin: 
      number: GPIO1
      inverted: True
      mode: INPUT_PULLUP
    name: ${friendly_name} Down Button
    internal: True
    on_press:
      then:
        - lambda: !lambda |-
            if (id(dimmer_lvl) < .10) {
              id(dimmer_lvl) = .01;
            }
            else if (id(dimmer_lvl) >= .10) {
              id(dimmer_lvl) -= .08;
            };
            id(apply_dimming).execute();
    on_click:
      # https://esphome.io/components/binary_sensor/index.html#on-click
      min_length: ${long_press_min}
      max_length: ${long_press_max}
      then:
        - light.turn_on:
            id: dimmer
            brightness: ${long_press_down}

  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin: 
      number: GPIO15
      mode: INPUT_PULLUP
    name: ${friendly_name} Main Button
    internal: True
    on_press:
      - light.toggle: 
          id: dimmer
          transition_length: 0s
    on_click:
      # https://esphome.io/components/binary_sensor/index.html#on-click
      min_length: ${long_press_min}
      max_length: ${long_press_max}
      then:
        - light.turn_on:
            id: dimmer
            brightness: ${long_press_main}


globals:
  - id: dimmer_lvl
    # https://esphome.io/guides/automations.html#bonus-2-global-variables
    type: float
    restore_value: no
    initial_value: '1.0'


script:
  - id: apply_dimming
    # https://esphome.io/guides/automations.html#script-execute-action
    then:
      - lambda: |-
          auto call = id(dimmer).turn_on();
          call.set_brightness(id(dimmer_lvl));
          call.perform();
      - logger.log:
          format: "dimmer_lvl = %.2f"
          args: ['id(dimmer_lvl)']


interval:
  - interval: 500ms
    # https://esphome.io/guides/automations.html#interval
    then:
      - lambda: |-
          auto dimmer_vals = id(dimmer).get_current_values();
          if (dimmer_vals.is_on()) {
            id(dimmer_lvl) = dimmer_vals.get_brightness();
          }
          if (id(dimmer_lvl) > .19) { id(led2).turn_on(); }
          if (id(dimmer_lvl) < .20) { id(led2).turn_off(); }
          if (id(dimmer_lvl) > .39) { id(led3).turn_on(); }
          if (id(dimmer_lvl) < .40) { id(led3).turn_off(); }
          if (id(dimmer_lvl) > .59) { id(led4).turn_on(); }
          if (id(dimmer_lvl) < .60) { id(led4).turn_off(); }
          if (id(dimmer_lvl) > .79) { id(led5).turn_on(); }
          if (id(dimmer_lvl) < .80) { id(led5).turn_off(); }
          if (!dimmer_vals.is_on()) {
            id(led2).turn_off();
            id(led3).turn_off();
            id(led4).turn_off();
            id(led5).turn_off();
          }

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
