### ISSUE TITLE
color_correct option not available for cwww platform

### ISSUE THREAD

**Issue by Elektrofreak** [esphome/issues#1902]
When using the cwww platform, it inherits all configuration variable options from the Light component according to the documentation: [Cold White + Warm White Light](https://esphome.io/components/light/cwww.html) 

So I tried to put the following code into the ESPHome plugin of Home Assistant:

```
light:
  - platform: cwww
    name: "ESP Cam Light"
    cold_white: gpio_4
    warm_white: gpio_12
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    default_transition_length: 5s
    color_correct: [70%, 75%]
```
The last line is highlighted and described as "[color_correct] is an invalid option for [light.cwww]. Did you mean [gamma_correct]?"

Is this feature not implemented as described?
