### ISSUE TITLE
color_correct option not available for cwww platform

### ISSUE THREAD

**Issue by Elektrofreak** [esphome/issues#1903]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**

v1.16.2

**Affected component:**

https://esphome.io/components/light/cwww.html
https://esphome.io/components/light/index.html#config-light

**Description of problem:**
When using the cwww platform, it inherits all configuration variable options from the Light component according to the documentation (see above). The last line of the yaml config shown below is highlighted and described as "[color_correct] is an invalid option for [light.cwww]. Did you mean [gamma_correct]?"

Is this feature not implemented as described?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
light:
  - platform: cwww
    name: "ESP Cam Light"
    cold_white: gpio_4
    warm_white: gpio_12
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    default_transition_length: 5s
    color_correct: [70%, 75%]
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
The color_correct configuration should also be available for warm white and cold white leds as this feature can be used to correct the brightness of both leds.
