### ISSUE TITLE
Compiling yaml is causing RPi to freeze

### ISSUE THREAD

**Issue by jdenver13** [esphome/issues#191]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

RPi3+ in wifi mode
**ESP (ESP32/ESP8266, Board/Sonoff):**
1.12.1 then upgraded to 1.12.2, still not working

**Affected component:**

**Description of problem:**
Been using ESPhome for a while now and all seems ok until I tried to compile a new .bin file and it just freezes, the RPi attempts to restart but then freezes, I loose access to SSH and access to the unifi add-on so I know its failed, the only way now is to recycle the power and delete the home-assistant_v2.db file as its now corrupt.

This was happening before upgrading to v1.12.2 on version 1.12.1

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  plug_name: smartplug_4
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: 'password'
  password: 'password111'
logger:
  baud_rate: 0
uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 4800
web_server:
  port: 80
api:
  password: 'password222'
ota:
  password: 'password333'
time:
- platform: homeassistant
  id: homeassistant_time
binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
switch:
- platform: gpio
  name: "${plug_name}_Relay"
  id: relay
  pin: GPIO14
  restore_mode: ALWAYS_ON
sensor:
- platform: wifi_signal
  name: "${plug_name} WiFi"
- platform: adc
  pin: VCC
  name: "VCC Voltage"
- platform: cse7766
  voltage:
    name: "${plug_name}_Voltage"
  current:
    name: "${plug_name}_Amperage"
  power:
    name: "${plug_name}_Wattage"
    id: "${plug_name}_Wattage"
- platform: total_daily_energy
  name: "${plug_name}_Total Daily Energy"
  power_id: "${plug_name}_Wattage"
  filters:
    - multiply: 0.001
  accuracy_decimals: 2
  unit_of_measurement: kWh
- platform: uptime
  name: ${plug_name}_Uptime Sensor
  filters:
    - lambda: return (x/60.0)/60;
  unit_of_measurement: "H"
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

Rebooted RPi and restarted ESPHome, also tried a clean build. I have 3 other smart plugs using the same .yaml (different names) and where they had all compiled and flashed over the air, they now no longer get through the compiling stage.

I think this all seemed to happen after following this issue: https://github.com/esphome/issues/issues/143 but I can't be sure as I was having issues with SSL logging in locally and infulxdb add-on at the time

<img width="897" alt="Screenshot 2019-04-01 07 54 16" src="https://user-images.githubusercontent.com/39801897/55381555-5892bb80-551b-11e9-9e79-42e618bee554.png">
<img width="848" alt="Screenshot 2019-04-01 07 54 36" src="https://user-images.githubusercontent.com/39801897/55381568-5fb9c980-551b-11e9-8017-337f84fc19f7.png">
