### ISSUE TITLE
Template switch turns off instantly

### ISSUE THREAD

**Issue by TheLastGimbus** [esphome/issues#1911]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Installed with normal system-wide `pip3` on Ubuntu 20

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 wemos d1 mini

**ESPHome version (latest production, beta, dev branch)**

1.16.2

**Affected component:**

[Template switch](https://esphome.io/components/switch/template.html)

**Description of problem:**
Hi there!
I have a board which controlls lights in the hallway, with pir motion sensor. I want motion sensor to enable the light for 3 minutes, and then turn it off. *But*, I also want to be able to *disable* this behavior so it doesn't annoy me when I don't want it to do so

So I created a template switch:
```yaml
switch:
  - platform: template
    name: "Hall 2 auto pir"
    id: hall_2_auto_pir
```
And then in pir sensor:
```yaml
binary_sensor:
  - platform: gpio
    name: "Hall 2 PIR"
    pin: 5  # D1
    device_class: motion
    id: hall_2_pir
    on_press:
      - if:
          condition:
            switch.is_on: hall_2_auto_pir
          then:
            - script.execute: some_script
```
But the `script.execute: some_script` never executes, because `switch.hall_2_auto_pir` is always disabled!
<sub>To be sure - it works when I remove `if` statement...</sub>

When I click on it in Home Assistant dashboard, it clicks, and then turns off after 1 second:

https://user-images.githubusercontent.com/40139196/111090671-d4337a80-8530-11eb-8616-1b8da1665b58.mp4

Meanwhile, logs from esphome just say:
```
[01:51:45][D][switch:021]: 'Hall 2 auto pir' Turning ON.
[01:51:48][D][switch:021]: 'Hall 2 auto pir' Turning ON.
[01:51:51][D][switch:021]: 'Hall 2 auto pir' Turning ON.
[01:51:55][D][switch:021]: 'Hall 2 auto pir' Turning ON.
```

**Additional information and things you've tried:**

I tried adding
```yaml
lambda: |-
  return ! id(hall_2_auto_pir).state;
```
But then it just kept toggling in a loop :disappointed:

**Comment by nikito7** [comment]
```yaml
binary_sensor:
  - platform: gpio
    name: "Hall 2 PIR"
    pin: 5  # D1
    device_class: motion
    id: hall_2_pir
    on_press:
    - if:
        condition:
          lambda: return id(hall_2_auto_pir).state;
        then:
        - script.execute: some_script
```
