### ISSUE TITLE
iBeacons doesn't get recognised by esp32_ble_tracker

### ISSUE THREAD

**Issue by marcinbauer85** [esphome/issues#1912]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
HassOS core-2021.3.4

**ESP (ESP32/ESP8266, Board/Sonoff):**
D1 ESP32

**ESPHome version (latest production, beta, dev branch)**
1.16.2

**Affected component:**
https://esphome.io/components/binary_sensor/ble_presence.html

**Description of problem:**
An iBeacon transmitted by Hass.io for Android, doesn't get recognised by an ESP32 D1 running ESPHome with ble_presence
**1. iBeacon from Hassio Android:**
![image](https://user-images.githubusercontent.com/6719575/111211106-4c9c4900-85ce-11eb-8fd3-1ed20e22c9c7.png)
**2. How it is scanned:**
![image](https://user-images.githubusercontent.com/6719575/111210819-fdeeaf00-85cd-11eb-95f9-f02024e45fde.png)
**3. How its discovered by HassOS: Always OFF**

**1. Beacon from nRF Connect:**
![image](https://user-images.githubusercontent.com/6719575/111210973-2bd3f380-85ce-11eb-9033-e37be599f502.png)
**2. How its scanned:**
![image](https://user-images.githubusercontent.com/6719575/111210905-1bbc1400-85ce-11eb-9161-1abbb195f124.png)
**3. How its discovered by HassOS (its discoevered perfectly:**
![image](https://user-images.githubusercontent.com/6719575/111211419-aac92c00-85ce-11eb-9073-46d1f1cf550e.png)

**Problem-relevant YAML-configuration entries:**
```yaml
esp32_ble_tracker:
  scan_parameters:
    duration: 10s

binary_sensor:
  - platform: ble_presence
    service_uuid: '60071c27-0543-4597-a2d8-8cad0f85d446'
    name: "M6T_CAR"

```

**Logs (if applicable):**

**Additional information and things you've tried:**
