### ISSUE TITLE
ESP-01 will not connect to WIFI after PIP3 update of esphome

### ISSUE THREAD

**Issue by kmstr113** [esphome/issues#1917]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

This is a 2.4Ghz wifi network. Standard home router.
**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP-01

**ESPHome version (latest production, beta, dev branch)**

**Description of problem:**
The wifi will not connect. I used a similar yaml back in january and it connected fine. I updated esphome with pip3 today and tried to run the same yaml file with different device names and it will not connect to any wifi router I have. I am using a standard home router 2.4Ghz, I have others for testing and the device will not connect to that router either. If I change the SSID on the other routers I have and shut off the production router I am using the old devices flashed back in January will connect fine, But the new devices will not connect at all.

I have mutiple New ESP-01 and have tried many of them with the new flash and they all fail

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: printdesk
  platform: ESP8266
  board: esp01

wifi:
  ssid: "TL3KG"
  password: "--REDACTED--"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Labdesk Fallback Hotspot"
    password: "Umgr97YoqR8M"

captive_portal:

#web_server: 
#  port: 80
#  auth:
#    username: admin
#    password: opengl64

# Enable logging
logger:
  level: debug
# Enable Home Assistant API
api:

ota:
output:
  platform: gpio
  pin: GPIO0
  id: main_relay

light:
  platform: binary
  name: "print_desk"
  id: rele1
  output: main_relay

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
