### ISSUE TITLE
AM2320 sensor not working (but found at 0x5c address)

### ISSUE THREAD

**Issue by sergeolkhovik** [esphome/issues#192]
First, gentlemen, I want to say that I'm really impressed about this platform. Amazing!
I had some self-developed code but now migrating to HA + ESPHome. And got some issues with AM2320 sensor.

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Latest 1.12.2, PIP installation.

**ESP (ESP32/ESP8266, Board/Sonoff):**

Have 2 the same Chinees WeMos D1 devices, one runs NodeMCU (custom build with am2320 support, https://nodemcu.readthedocs.io/en/master/en/modules/am2320/), another one runs ESPHome, both have (again, Chineese) AM2320 sensors (the same order, https://www.aliexpress.com/item/1pcs-New-AM2320-Digital-Temperature-and-Humidity-Sensor-Original-authentic-Can-replace-SHT20-SHT10/32593087118.html?spm=a2g0s.9042311.0.0.27424c4dKmnhSx), both chips have sensor connected via pins GPIO4/5 (D2/D1), and both have OLED 128x64 displays. Currently don't have any pull-up resistor on i2c bus (but I might have already tried before with no luck, cannot recall).

**Affected component:**

DHT12 T+H sensor.

**Description of problem:**
ESPHome marks am2320 sensor failed (but can find this device at 0x5c), nodemcu installation works perfectly.

**Problem-relevant YAML-configuration entries:**
```yaml
i2c:
    sda: 4
    scl: 5
    scan: True

sensor:
    - platform: dht12
      temperature:
          id: air_t
          name: D3 Air T
          icon: "mdi:temperature-celsius"
          filters:
              - offset: -1.2
      humidity:
          id: air_h
          name: D3 Air H
          filters:
              - offset: -7
      update_interval: 60s

```

**Traceback (if applicable):**

```
[19:42:55][C][i2c:035]: I2C Bus:
[19:42:55][C][i2c:036]:   SDA Pin: GPIO4
[19:42:55][C][i2c:037]:   SCL Pin: GPIO5
[19:42:55][C][i2c:038]:   Frequency: 50000 Hz
[19:42:55][I][i2c:040]: Scanning i2c bus for active devices...
[19:42:55][I][i2c:047]: Found i2c device at address 0x3C
[19:42:55][I][i2c:047]: Found i2c device at address 0x5C
[19:42:55][C][output.gpio:025]: GPIO Binary Output:
[19:42:55][D][sensor.dht12:057]: DHT12:
[19:42:55][C][sensor.dht12:058]:   Address: 0x5C
[19:42:55][E][sensor.dht12:060]: Communication with DHT12 failed!
[19:42:55][C][sensor.dht12:062]:   Temperature 'D3 Air T'
[19:42:55][C][sensor.dht12:062]:     Unit of Measurement: '°C'
[19:42:55][C][sensor.dht12:062]:     Accuracy Decimals: 1
[19:42:55][C][sensor.dht12:062]:     Icon: 'mdi:temperature-celsius'
[19:42:55][C][sensor.dht12:063]:   Humidity 'D3 Air H'
[19:42:55][C][sensor.dht12:063]:     Unit of Measurement: '%'
[19:42:55][C][sensor.dht12:063]:     Accuracy Decimals: 0
[19:42:55][C][sensor.dht12:063]:     Icon: 'mdi:water-percent'
```

**Additional information and things you've tried:**
But when I connect esp via USB I see extra info at the very beginning:

```
[D][light.state:418]: 'D3 Built-in LED' Turning OFF
[C][display.ssd1306:299]: Setting up I2C SSD1306...
[C][sensor.dht12:049]: Setting up DHT12...
[W][i2c:077]: Received NACK on transmit of address 0x5C
[W][sensor.dht12:068]: Updating DHT12 failed!
[E][component:151]: Component was marked as failed.
```

The most important thing here is that alternative configuration (NodeMCU) works without any problem, I can get some values and display them on display, code is pretty simple like:

```
    i2c.setup(0, PIN_SDA, PIN_SCL, i2c.SLOW)
    tmr.delay(2000000) -- 2 seconds
    am2320.setup()
...

        h, t = am2320.read()
        h = h / 10
        t = t / 10
        msg = string.format("appSensors: t = %0.3f, h = %0.3f", t, h);
        print(msg);

```

Oh, wait... I just found (and I really forgot about that!) that I have some delay set between i2c initialization and am2302 sensor set up. Probably this is because Chineese origin of these sensors, is there a way to implement something like this is ESPHome configuration?

Please ask me if you need any extra info/details or debugging from me to figure out the problem.
Highly appreciate any help on this.
Thanks!

**Comment by OttoWinter** [comment]
Yes the initial delay could be the culprit here (according to the datasheet esphome's timing is ok though). You can add a delay by setting
```yaml
sensor:
- platform: dht12
  setup_priority: -100
  # ...
```
