### ISSUE TITLE
Logger timezone issue

### ISSUE THREAD

**Issue by chemelli74** [esphome/issues#1923]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant 2021.3.4

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 dev board

**ESPHome version (latest production, beta, dev branch)**

v1.16.2

**Affected component:**

logger

**Description of problem:**
Time is synchronized with HA but is off by 1 hour

**Problem-relevant YAML-configuration entries:**
```yaml
# Sync time via Home Assistant API
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Europe/Rome"
```

**Logs (if applicable):**

esphome config:
```
time:
- platform: homeassistant
  id: homeassistant_time
  timezone: CET-1CEST-2,M3.4.0/2,M10.5.0/3
  update_interval: 15min
```

esphome run:
```
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 28 March 02:00:00 to 31 October 03:00:00
```

esphome logs:
```
[08:13:17][C][homeassistant.time:010]: Home Assistant Time:
[08:13:17][C][homeassistant.time:011]:   Timezone: 'CET-1CEST-2,M3.4.0/2,M10.5.0/3'
```

**Additional information and things you've tried:**

Logs shows **8**:13 but here it's **9**:13 
Tried removing `timezone` from yaml, but I still get **8**:13 :-S

**Comment by randybb** [comment]
Do you have a correct time on HA server? 

I have the same timezone (Europe/Bratislava, that is GMT+1) and time on my side is correct.

**Comment by chemelli74** [comment]
You, time in HA is fine as well as time zone.

Do you have the same values on if you do a `config` check ?
What I don’t get is why it shows “CET-1” and not CET

Thx,

Simone

**Comment by chemelli74** [comment]
@randybb can you please check your config and let me know if it's like mine or not please ?

Thank you,

Simone

**Comment by randybb** [comment]
In my case it is
```yaml
  - platform: homeassistant
    id: ha_time
    timezone: Europe/Bratislava
```
```syslog
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 28 March 02:00:00 to 31 October 03:00:00
[14:44:35][C][homeassistant.time:010]: Home Assistant Time:
[14:44:35][C][homeassistant.time:011]:   Timezone: 'CET-1CEST-2,M3.4.0/2,M10.5.0/3'
```
and time in the log is matching the current time.
