### ISSUE TITLE
MCP23017 random outputs at startup

### ISSUE THREAD

**Issue by comm-lab** [esphome/issues#1924]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant 2021.1.4

**ESP (ESP32/ESP8266, Board/Sonoff):**

Olimex ESP32-EVB

**ESPHome version (latest production, beta, dev branch)**

1.17.0-dev

**Affected component:**

MCP23017

**Description of problem:**
During startup of the firmware the output pins of the MCP23017 are set to random values. This should be due to the fact that in the component setup function the code that was setting all pins as inputs is been removed (in commit b52f7cfe86a167bcd3f41baf2194243699a3e354 MCP230xx open drain interrupt pins (#1243)
):
```cpp
  // all pins input
  this->write_reg_(MCP23017_IODIRA, 0xFF);
  this->write_reg_(MCP23017_IODIRB, 0xFF);
```
They should all be set as inputs at setup, then, after OLATA and OLATB are set, they can be set as configured in yaml at main.cpp:
```cpp
 out_puntoluce1->set_pin(new mcp23xxx_base::MCP23XXXGPIOPin(MCP23017_0, 8, mcp23xxx_base::MCP23XXX_OUTPUT, true, mcp23xxx_base::MCP23XXX_NO_INTERRUPT));
```
**Problem-relevant YAML-configuration entries:**
```yaml
#------------------------MCP23017_0-----------------------------------------          
mcp23017:
  - id: 'MCP23017_0'
    address: 0x27

#------------------------MCP23017_1-----------------------------------------          
  - id: 'MCP23017_1'
    address: 0x26

#------------------------MCP23017_2-----------------------------------------          

  - id: 'MCP23017_2'
    address: 0x25

switch:             
#------------------------MCP23017_0 Port B (outputs)----------
  - platform: gpio
    id: out_puntoluce1
    name: "MCP23017_0 PIN #8"
    pin:
      mcp23xxx: MCP23017_0
      number: 8
      mode: OUTPUT
      inverted: True
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

I've tried adding those two lines back to the setup fuction, (after open drain interrupts setting) and everything works fine.
My component setup now looks like this:

```cpp
void MCP23017::setup() {
  ESP_LOGCONFIG(TAG, "Setting up MCP23017...");
  uint8_t iocon;
  if (!this->read_reg(mcp23x17_base::MCP23X17_IOCONA, &iocon)) {
    this->mark_failed();
    return;
  }

  if (this->open_drain_ints_) {
    // enable open-drain interrupt pins, 3.3V-safe
    this->write_reg(mcp23x17_base::MCP23X17_IOCONA, 0x04);
    this->write_reg(mcp23x17_base::MCP23X17_IOCONB, 0x04);
  }

  // all pins input
  this->write_reg(mcp23x17_base::MCP23X17_IODIRA, 0xFF);
  this->write_reg(mcp23x17_base::MCP23X17_IODIRB, 0xFF);
}
```
