### ISSUE TITLE
How to apply PWM to motor?

### ISSUE THREAD

**Issue by maurera** [esphome/issues#1925]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Home Assistant OS 5.12

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP32 Cam

**ESPHome version (latest production, beta, dev branch)** v1.16.2

**Affected component:** https://esphome.io/cookbook/dual-r2-cover.html

**Description of problem:**
Hello, please advise if this is the wrong place to be posting this. I'm just getting started with Home Assistant, ESPHome, and electronics in general. 

I would like to know how to apply PWM and also interlock with another GPIO pin. 

I'm trying to control a motor for a chicken coop door using ESPHome. The *cover* component seems most useful since I have endstops at the top and bottom of door range of motion.

I am using a 2.4A power supply, DRV8833 motor controller board, and 12v motor similar to [DC 12V Worm Gear Motor](https://www.cytron.io/p-dc-12v-worm-gear-motor-200rpm), but only 5rpm gearing. The power surge when I switch on the motor causes the ESP32 to reset (I verified this by having the ESP32 flash its LED on boot).

I think I can avoid this by doing a slower ramp-up of the motor, using PWM. The motor controller board does not have an EN input, just IN1 and IN2 (IN1 high IN2 low spins one way, IN1 low IN2 high spins other way).

I need a component that can:
- apply PWM, rather than binary on/off
- PWM speed needs to gradually increase to limit the power surge 
- interlock with another gpio pin, so that IN1 and IN2 are never both high at the same time

References:
- I suppose I'm looking for a a simpler version of this, without the binary sensor portion: https://esphome.io/cookbook/dual-r2-cover.html
- I've read that the ledc component is what's used to control PWM on the ESP32. Is this what I should be using? https://esphome.io/components/output/ledc.html
- This issue is similar, however the DRV8833 only has 2 inputs IN1 and IN2 (no EN), I want to be able to spin the motor both directions, and I'm not using a stepper motor. https://github.com/esphome/feature-requests/issues/48

Thank you

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: coop_esp32_door
  platform: ESP32
  board: esp32cam
  on_boot:
    then:
      - switch.turn_on: flash32
      - delay: 50ms
      - switch.turn_off: flash32

wifi:
  ssid: "***"
  password: "***"

switch:
  - platform: gpio
    pin: GPIO13
    id: door32_up
    name: door32_up
    interlock: &interlock_group [door32_up, door32_down]
  - platform: gpio
    pin: GPIO2
    id: door32_down
    name: door32_down
    interlock: *interlock_group
  - platform: gpio
    pin: GPIO4
    id: flash32
    name: flash32
    
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: door32_up_endstop
  - platform: gpio
    pin: 
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: True
    id: door32_down_endstop

cover:
  - platform: endstop
    name: "Chicken door32"
    id: my_cover32

    open_action:
      - switch.turn_on: door32_up
    open_duration: 10s
    open_endstop: door32_up_endstop

    close_action:
      - switch.turn_on: door32_down
    close_duration: 10s
    close_endstop: door32_down_endstop

    stop_action:
      - switch.turn_off: door32_up
      - switch.turn_off: door32_down

    max_duration: 10s

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

Update - I've got something working, but it's not pretty! Can anyone help with a nicer way of doing this?

```
output:
- platform: ledc
  pin: GPIO13
  id: IN1
- platform: ledc
  pin: GPIO2
  id: IN2
- platform: ledc
  pin: GPIO4
  id: flash32

switch:
  # - platform: gpio
  #   pin: GPIO4
  #   id: flash32
  #   name: flash32
  - platform: template
    name: "Andrew Switch"
    id: andrew_switch
    turn_on_action:
      - output.turn_off: IN2
      - output.set_level: 
          id: IN1
          level: 1%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 2%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 3%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 4%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 5%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 7%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 9%
      - output.set_level: 
          id: flash32
          level: 20%
      - delay: 500ms
      - output.turn_off: flash32
      - delay: 500ms
      - output.set_level: 
          id: flash32
          level: 20%
      - delay: 500ms
      - output.turn_off: flash32
      - delay: 500ms
      - output.set_level: 
          id: flash32
          level: 20%
      - delay: 500ms
      - output.turn_off: flash32
      - output.set_level: 
          id: IN1
          level: 15%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 20%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 25%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 30%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 35%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 40%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 45%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 50%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 60%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 70%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 80%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 90%
      - delay: 500ms
      - output.set_level: 
          id: IN1
          level: 100%
      - delay: 5s
      - output.turn_off: IN1
      - output.set_level: 
          id: flash32
          level: 20%
      - delay: 500ms
      - output.turn_off: flash32
      - delay: 500ms
      - output.set_level: 
          id: flash32
          level: 20%
      - delay: 500ms
      - output.turn_off: flash32
    turn_off_action:
    - output.turn_off: IN1
    - output.turn_off: IN2
```
