### ISSUE TITLE
ble_presence not respecting filters

### ISSUE THREAD

**Issue by chemelli74** [esphome/issues#1931]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant core 2021.3.4

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 dev board

**ESPHome version (latest production, beta, dev branch)**

v1.16.2

**Affected component:**

ble_presence

**Description of problem:**
Filters `delayed_on` and `delayed_off `are not respected. See screenshot below

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: ble_presence
    mac_address: 'C4:7C:8D:XX:XX:XX'
    name: "Xiaomi Sensore 4 Connectivity"
    device_class: connectivity
    filters:
      - delayed_on: 5s
      - delayed_off: 5s
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

![image](https://user-images.githubusercontent.com/57354320/112123485-98985080-8bc1-11eb-904d-1d080b10fdb4.png)
