### ISSUE TITLE
ST7789V backlight_pin should not be mandatory some boards do not wire it

### ISSUE THREAD

**Issue by manonfgoo** [esphome/issues#1944]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip install, 

**ESP (ESP32/ESP8266, Board/Sonoff):**

M5StickC PLUS  with St7789V Display

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**
ST7789V

**Description of problem:**

I am trying to use the Display St7789V Display of M5StickC PLUS (https://docs.m5stack.com/#/en/core/m5stickc_plus?id=m5stickc-plus). This display does not have the backlight_pin wired but the driver mandatory requires a backlight_pin. Currently I have set the backlight_pin to an unused GIPO. Would it be possible to make the backlight_pin optional ?

Kind regards,
Manon

**Problem-relevant YAML-configuration entries:**

```

# built-in 80x160 TFT
display:
  - platform: st7789v
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    backlight_pin: GPIO26.  ### <<<---- this is not connected, i use a unconnected GPIO to satisfy the constarints


```

**Additional information and things you've tried:**
