### ISSUE TITLE
PCF8575 Floating pins / INPUT_PULLUP

### ISSUE THREAD

**Issue by Tofandel** [esphome/issues#1948]
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP 32 (POE Olimex version)

**ESPHome version (latest production, beta, dev branch)**

1.16.2

**Affected component:**

https://esphome.io/components/pcf8574.html

**Description of problem:**
Does the pcf8575 needs external pullup resistors? I haven't found anything explicit saying it does or doesn't, but hinting more to the fact that there is indeed internal pullups

Right now I have a board setup with some floating pins and I'm seeing a few random on/off events (the other non floating pins don't have this issue)
![image](https://user-images.githubusercontent.com/6115458/112826228-00044380-908d-11eb-91dc-a7ae7f027514.png)

**Problem-relevant YAML-configuration entries:**
```yaml

i2c:
  sda: GPIO13
  scl: GPIO14
  scan: True
pcf8574:
  - id: 'pcf8575_hub'
    address: 0x21
    pcf8575: true

binary_sensor:
  - platform: gpio
    device_class: motion
    name: "Motion First Floor Room 1"
    pin:
      pcf8574: pcf8575_hub
      number: 1
      mode: INPUT #Because INPUT_PULLUP was removed
      inverted: false

```

**Logs (if applicable):**

I sometimes see this in the logs, so maybe I have an underlying communication issue between the ESP and the PCF8575?
```!
[13:04:35][W][i2c:086]: Requesting 2 bytes from 0x21 failed!
[13:04:35][D][binary_sensor:036]: 'Alarm Tamper': Sending state OFF
[13:04:35][D][binary_sensor:036]: 'Alarm Tamper': Sending state ON
```
