### ISSUE TITLE
Higher power consumption on power plug than other firmwares

### ISSUE THREAD

**Issue by hanzoh** [esphome/issues#1950]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

platform: ESP8266
board: esp8285
**ESPHome version (latest production, beta, dev branch)**

1.16.2
**Affected component:**

n/a

**Description of problem:**
I have flashed a Gosund SP1 plug with esphome and found that it then uses a constant 1.75W by itself, when the relay is on.
Then I flashed Tasmota and after that ESPurna on the same plug to compare power usage.
Both firmwares use a maximum power of ~1.15W, but they also lower it in between sending updates.
The esphome power usage was independent of yaml config, I even reduced it to the bare minimum (see below).
The best power consumption was on the original Tuya firmware, they seem to turn stuff off when it is not currently needed.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp01
  platform: ESP8266
  board: esp8285

wifi:
  ssid: "myssid"
  password: "mypassword"

ota:
```

**Logs (if applicable):**

```
n/a
```

**Additional information and things you've tried:**
n/a
