### ISSUE TITLE
ESPHome's RF remote transmitter doesn't transmit

### ISSUE THREAD

**Issue by jant90** [esphome/issues#1956]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HassOS

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 dev board

**ESPHome version (latest production, beta, dev branch)**

Latest (v1.16.2)

**Affected component:**

Remote transmitter: https://esphome.io/components/remote_transmitter.html

**Description of problem:**
I have a working RF example using an Arduino sketch with the [rc-switch library](https://github.com/sui77/rc-switch). But I can't get RF transmitting to work with ESPHome.

I already had the correct RF codes for my sockets from my RF bridge flashed with Portisch firmware, first with Tasmota and later with ESPHome. I could simply convert the HEX codes to decimal or binary and turn my outlet on and off using the following Arduino sketch (modified SendDemo).
```c
#include <RCSwitch.h>

RCSwitch mySwitch = RCSwitch();

void setup() {
  Serial.begin(9600);
  mySwitch.enableTransmit(16);
}

void loop() {
  // Send codes as decimal
  mySwitch.send(8213588, 24);
  delay(1000);  
  mySwitch.send(8213585, 24);
  delay(1000);  

  // Send the same codes as binary (I had to add a leading 0)
  mySwitch.send("011111010101010001010100");
  delay(1000);  
  mySwitch.send("011111010101010001010001");
  delay(1000);
}
```
Using the [ReceiveDemo](https://github.com/sui77/rc-switch/blob/master/examples/ReceiveDemo_Advanced/ReceiveDemo_Advanced.ino) I would consistently get the same code as well:
```
Decimal: 8213588 (24Bit) Binary: 011111010101010001010100 Tri-State: F11FFFF0FFF0 PulseLength: 149 microseconds Protocol: 1
```
When using the exact same board and wiring, just flashing over the Arduino sketch with ESPHome transmitting RF codes isn't working at all. I don't even see any RF activity on my Sonoff RF bridge (no red LED flashing).

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esphome_test
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true
  power_save_mode: none

logger:
  level: DEBUG

api:

web_server:

remote_transmitter:
  pin: 16
  carrier_duty_percent: 100%

switch:
  - platform: template
    name: RF Socket
    optimistic: true
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '011111010101010001010100'
          protocol: 1
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '011111010101010001010001'
          protocol: 1
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by jant90** [comment]
Related to #1828, so this is definitely a regression in ESPHome 1.16. Solution there is to use:
```yaml
- remote_transmitter.transmit_rc_switch_raw:
    code: '011111010101010001010100'
    protocol: 1
    repeat: 
      times: 10
      wait_time: 0s
```
While this works RF actions are very delayed and this makes the ESP32 somewhat slow to respond. I could lower it to 4 times repeat and this seems to improve responsiveness (any lower and my socket wouldn't respond anymore).
