### ISSUE TITLE
Component Animation (Gif) does not compile with option Grayscale or RGB24

### ISSUE THREAD

**Issue by Ierlandfan** [esphome/issues#1957]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 (TTGO T-Display)
**ESPHome version (latest production, beta, dev branch)**

ESPhome 1.16.2
**Affected component:**

https://esphome.io/components/display/index.html

**Description of problem:**
Animation (Gif) does not accept Grayscale or RGB24

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

animation:
  - file: "rotating-fanblades.gif"
    id: spinning_fan
    resize: 75x75
    type: RGB24
**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```
 File "/usr/local/lib/python3.8/dist-packages/esphome/components/animation/__init__.py", line 78, in to_code
    data[pos] = pix[0]
IndexError: list assignment index out of range

**Additional information and things you've tried:**

The component "image" does compile succesfully with the option RGB24



<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
