### ISSUE TITLE
Unknown Value: Pin mode OUTPUT_OPEN_DRAIN for SX1509

### ISSUE THREAD

**Issue by Dreamoffice** [esphome/issues#1959]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 dev board
**ESPHome version (latest production, beta, dev branch)**

v1.16.2
**Affected component:**

https://esphome.io/components/sx1509.html?highlight=sx1509

**Description of problem:**
I'm using the I/O Expander SX1509 with an 16 Relayboard. i want to set the Pin mode to OUTPUT_OPEN_DRAIN but it is not possible. The syntax shows me unknown value. If the Pin is low the Relay is ON if the Pin is high the Relay is off and the Pin has 3.3 Volts which i do not need.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```switch:
  - platform: gpio
    name: "SX1509 Pin #1"
    pin:
      sx1509: sx1509_hub1
      # Use pin number 1 on the SX1509
      number: 1
      # use as output for switch
      mode: OUTPUT
      inverted: True

**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
