### ISSUE TITLE
How used LittleFS?

### ISSUE THREAD

**Issue by SCratORS** [esphome/issues#1968]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):** 

ESP8266 (ESP-12E/F/S)

**ESPHome version (latest production, beta, dev branch)**

v1.16.2

**Affected component:**

**Description of problem:**
How can I use LittleFS in custom components? I created my own component, connected the library "LittleFS.h" But when trying to initialize LittleFS.begin() or LittleFS.format() I get false.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
   platformio_options:
      board_build.filesystem = littlefs
```

**Logs (if applicable):**

```
error: expected a dictionary

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
```
esphome:
  platformio_options:
    board_build.filesystem: littlefs
```
note the `:` - this is in a YAML file, so needs to be in YAML syntax.

**Comment by SCratORS** [comment]
I know that.
But the YAML editor reports that "error: expected a dictionary"

**Comment by SCratORS** [comment]
Ok.
board_build.filesystem: littlefs
custom component code:
`include <LittleFS.h>
...
LittleFS.format(); //return false
LittleFS.begin(); //return false
`
Does not work.

**Comment by SCratORS** [comment]
SOLVED. Thanks.
```
esphome: 
  platformio_options:
    board_build.filesystem: littlefs
    board_build.ldscript: eagle.flash.4m3m.ld
```
**I wish it was written somewhere...**
