### ISSUE TITLE
speed fan component should turn off oscillation on fan.turn_off

### ISSUE THREAD

**Issue by ishioni** [esphome/issues#1970]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant 2021.04.0 on Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff ifan03 (esp8285)
**ESPHome version (latest production, beta, dev branch)**

1.16.2
**Affected component:**

speed fan

**Description of problem:**
I'm using a sonoff ifan03 to drive a standing fan described here https://github.com/ishioni/mqtt-fan
I'm using the light switch relay to drive the oscillation motor of the fan, and I'd like to automatically disable the oscillation motor when the fan is switched off. This is not the default, and it seems impossible to get this to work when using the speed fan component, as it's not possible to do this:

```yaml
fan.turn_off: 
  id: ifan03_fan
  oscillate: false
```
This would fix controlling the fan from the RF remote. But it would not change the behaviour in HA itself (which one could get around using HAs automations). I think the best way is to add an option to the component itself

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esphome_ifan03
  platform: ESP8266
  board: esp8285
  includes:
    - ifan03.h

wifi:

  ap:
    ssid: "esphome-ifan03"

captive_portal:

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

remote_receiver:
  pin: GPIO3

sensor:
  - platform: wifi_signal
    name: "Wifi signal sensor"

binary_sensor:
  - platform: remote_receiver
    name: "Buzzer"
    internal: true
    id: remote_buzzer
    raw:
      code: [-207, 104, -103, 104, -104, 103, -104, 207, -104, 103, -104, 103, -104, 104, -103, 104, -103, 104, -104, 107, -721, 105, -206, 207, -518, 105, -931, 104, -104, 103, -725, 104, -104, 103, -725, 104, -104, 103, -207, 104, -414]
    on_release:
      then:
        - switch.toggle: buzzer_dummy
        - output.turn_on: buzzer
        - delay: 100ms
        - output.turn_off: buzzer

  - platform: remote_receiver
    name: "Fan off"
    id: remote_off
    raw:
      code: [-207, 104, -103, 104, -104, 103, -104, 207, -104, 103, -104, 104, -103, 104, -104, 103, -104, 105, -102, 104, -725, 104, -311, 103, -518, 104, -933, 103, -104, 104, -725, 104, -932, 104, -207, 207, -519]
    on_release:
      then:
        - fan.turn_off: ifan03_fan
        - switch.turn_off: ifan03_oscillation
    internal: true

  - platform: remote_receiver
    name: "Fan low"
    internal: true
    id: remote_low
    raw:
      code: [-207, 104, -104, 103, -104, 104, -103, 207, -104, 104, -103, 104, -104, 103, -104, 104, -103, 104, -104, 103, -726, 103, -312, 103, -518, 104, -933, 103, -104, 104, -725, 104, -103, 104, -726, 103, -104, 311, -518]
    on_release:
      then:
        - fan.turn_on:
            id: ifan03_fan
            speed: LOW
        - if:
            condition:
              and:
                - switch.is_on: buzzer_dummy
            then:
              - output.turn_on: buzzer
              - delay: 50ms
              - output.turn_off: buzzer

  - platform: remote_receiver
    name: "Fan medium"
    internal: true
    id: remote_med
    raw:
      code: [-208, 103, -104, 104, -103, 104, -103, 208, -103, 104, -104, 103, -104, 104, -103, 104, -104, 103, -104, 103, -726, 104, -310, 104, -518, 104, -933, 103, -104, 104, -725, 104, -207, 104, -622, 103, -416, 102, -415]
    on_release:
      then:
        - fan.turn_on:
            id: ifan03_fan
            speed: MEDIUM
        - if:
            condition:
              and:
                - switch.is_on: buzzer_dummy
            then:
              - output.turn_on: buzzer
              - delay: 50ms
              - output.turn_off: buzzer
              - delay: 50ms
              - output.turn_on: buzzer
              - delay: 50ms
              - output.turn_off: buzzer

  - platform: remote_receiver
    name: "Fan high"
    internal: true
    id: remote_high
    raw:
      code: [-207, 104, -104, 103, -104, 104, -103, 208, -103, 104, -104, 103, -104, 104, -103, 104, -104, 103, -104, 103, -726, 104, -311, 104, -518, 103, -934, 103, -103, 104, -726, 103, -104, 207, -622, 104, -103, 104, -207, 104, -415]
    on_release:
      then:
        - fan.turn_on:
            id: ifan03_fan
            speed: HIGH
        - if:
            condition:
              and:
                - switch.is_on: buzzer_dummy
            then:
              - output.turn_on: buzzer
              - delay: 50ms
              - output.turn_off: buzzer
              - delay: 50ms
              - output.turn_on: buzzer
              - delay: 50ms
              - output.turn_off: buzzer
              - delay: 50ms
              - output.turn_on: buzzer
              - delay: 50ms
              - output.turn_off: buzzer

  - platform: remote_receiver
    name: "Fan oscillate"
    internal: true
    id: remote_osc
    raw:
      code: [-207, 104, -103, 104, -104, 103, -104, 207, -104, 103, -104, 104, -103, 104, -103, 104, -104, 103, -104, 104, -725, 104, -311, 103, -518, 104, -933, 103, -104, 103, -726, 103, -311, 104, -518, 104, -207, 104, -103, 104, -414]
    on_release:
      then:
        - switch.toggle: ifan03_oscillation
        - if:
            condition:
              and:
                - switch.is_on: buzzer_dummy
            then:
              - output.turn_on: buzzer
              - delay: 50ms
              - output.turn_off: buzzer

output:
  - platform: custom
    type: float
    outputs:
      id: fanoutput
    lambda: |-
      auto ifan03_fan = new IFan03Output();
      App.register_component(ifan03_fan);
      return {ifan03_fan};

  - platform: gpio
    pin: GPIO9
    id: oscillation_out
    inverted: true

  - platform: gpio
    pin: GPIO10
    id: buzzer
    inverted: true

switch:
  - platform: restart
    name: "Restart"
    
  - platform: template
    id: buzzer_dummy
    name: "Buzzer"
    optimistic: True
  
  - platform: output
    id: ifan03_oscillation
    name: "Ifan03 Oscillation"
    # internal: true
    output: oscillation_out
  
  - platform: template
    id: update_fan_speed
    optimistic: True
    turn_on_action:
      then:
        - delay: 200ms
        - if:
            condition:
              and:
                - switch.is_off: relay_fan1
                - switch.is_off: relay_fan2
                - switch.is_off: relay_fan3
            then:
              - fan.turn_off: 
                  id: ifan03_fan
                  # oscillating: false
                
        - if:
            condition:
              and:
                - switch.is_on: relay_fan1
                - switch.is_off: relay_fan2
                - switch.is_off: relay_fan3
            then:
              - fan.turn_on:
                  id: ifan03_fan
                  speed: LOW
        - if:
            condition:
              and:
                - switch.is_off: relay_fan1
                - switch.is_on: relay_fan2
                - switch.is_off: relay_fan3
            then:
              - fan.turn_on:
                  id: ifan03_fan
                  speed: MEDIUM
        - if:
            condition:
              and:
                - switch.is_off: relay_fan1
                - switch.is_off: relay_fan2
                - switch.is_on: relay_fan3
            then:
              - fan.turn_on:
                  id: ifan03_fan
                  speed: HIGH
        - switch.turn_off: update_fan_speed

  - platform: gpio
    pin: GPIO14
    id: relay_fan1

  - platform: gpio
    pin: GPIO12
    id: relay_fan2

  - platform: gpio
    pin: GPIO15
    id: relay_fan3

fan:
  - platform: speed
    output: fanoutput
    # oscillation_output: oscillation_out
    id: ifan03_fan
    name: "iFan03 Fan"

```

**Logs (if applicable):**

```
[12:50:42][D][speed.fan:039]: Setting speed: 0.00
[12:50:42][D][speed.fan:050]: Setting oscillation: ON

```

**Additional information and things you've tried:**
As seen in my full config above, I have a separate switch for oscillation now as a workaround. Not that having both an oscillating fan and an oscillation switch desyncs the state between them, which is suboptimal
