### ISSUE TITLE
PCF8575 as input

### ISSUE THREAD

**Issue by zinoalex** [esphome/issues#1974]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant
**ESP (ESP32/ESP8266, Board/Sonoff):**

Generic ESP32
**ESPHome version (latest production, beta, dev branch)**

1.16.2
**Affected component:**

PCF8574

**Description of problem:**
Hi guys, I'm trying to use a PCF8575 as INPUT.
When I flash a simple code with ESPhome the program does not work (no change of input state), if I flash a similar program but with arduino IDE and using arduino library the system works.
Codes below.
Does esphome support pcf8575 as input? 
Because I've read that in order to use a pin as input you need to initialize that pin as outup in high state and only after that you can use it as input.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

pcf8574:
  - id: 'pcf8575_hub'
    address: 0x20
    pcf8575: True
    
binary_sensor:
  - platform: gpio
    name: "Pin #1"
    pin:
      pcf8574: pcf8575_hub
      number: 1
      mode: INPUT
      inverted: False


Arduino code:

#include "Arduino.h"
#include "PCF8575.h"

// Set i2c address
PCF8575 pcf8575(0x20);
unsigned long timeElapsed;
void setup()
{
	Serial.begin(115200);

	pcf8575.pinMode(P1, INPUT);

	pcf8575.begin();
}

void loop()
{
	uint8_t val = pcf8575.digitalRead(P1);
	if (val==HIGH) Serial.println("KEY PRESSED");
	delay(50);
}
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
