### ISSUE TITLE
esp32 LEDC with OUTPUT_OPEN_DRAIN

### ISSUE THREAD

**Issue by osresearch** [esphome/issues#1975]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

`esphome` 1.16.2 installed via `pip3` on ubuntu 20.04

**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32cam board

**ESPHome version (latest production, beta, dev branch)**

1.16.2

**Affected component:**

[ledc](https://esphome.io/components/output/ledc.html?highlight=ledc)

**Description of problem:**

The ledc component switches the pin mode to output, so a pin configured as `OUTPUT_OPEN_DRAIN` will not behave correctly. When used as a binary lamp, this works fine for turning on and off an external MOSFET:

```
output:
  - platform: gpio
    id: lamp
    inverted: True
    pin:
      number: GPIO3
      mode: OUTPUT_OPEN_DRAIN

light:
  - platform: binary
    output: lamp
    name: "lamp"
```

However, when it is switch to use the `ledc` output platform the pin is switched back to `OUTPUT` and the dimming does not work correctly.  The problem might be in the underlying call to `ledcAttachPin()`, as discussed here: https://esp32.com/viewtopic.php?t=15783
```
void ledcAttachPin(uint8_t pin, uint8_t chan)
{
    if(chan > 15) {
        return;
    }
    pinMode(pin, OUTPUT);
    pinMatrixOutAttach(pin, ((chan/8)?LEDC_LS_SIG_OUT0_IDX:LEDC_HS_SIG_OUT0_IDX) + (chan%8), false, false);
}
```

I can add a `lambda` that switches it to open drain when turning the lamp on, and this works for dimming, but is unable to turn the lamp off. I thought perhaps adding an explicit switch back to input mode would work, but that leaves it in a flickering state.

```
output:
  - platform: ledc
    id: lamp_pwm
    inverted: True
    pin:
      number: GPIO3
      mode: OUTPUT_OPEN_DRAIN

light:
  - platform: monochromatic
    output: lamp_pwm
    name: "lamp"
    on_turn_on:
      - lambda: pinMode(3, OUTPUT_OPEN_DRAIN);
    on_turn_off:
      - lambda: pinMode(3, INPUT);
```

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: bigswitch
  platform: ESP32
  board: esp32cam

wifi:
  ssid: "xyzzy"
  password: "password"

# Enable logging on the second uart, leaving RX=GPIO3 free
# for the PWM to the big switch LEDs
logger:
  hardware_uart: UART2

# Do NOT Enable Home Assistant API
#api:

# talk to mqtt broker for grafana updates
mqtt:
  broker: dashboard

ota:

output:
  - platform: ledc
    id: lamp_pwm
    inverted: True
    pin:
      number: GPIO3
      mode: OUTPUT_OPEN_DRAIN

light:
  - platform: monochromatic
    output: lamp_pwm
    name: "lamp"
    on_turn_on:
      - lambda: pinMode(3, OUTPUT_OPEN_DRAIN);
    on_turn_off:
      - lambda: pinMode(3, INPUT); digitalWrite(3, 0);
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
