### ISSUE TITLE
ac_dimmer / dallas interrupt issue 

### ISSUE THREAD

**Issue by fraxinas** [esphome/issues#1976]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
`homeassistant/home-assistant:stable` Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32-WROOM32D custom board

**ESPHome version (latest production, beta, dev branch)**
`esphome 1.16.2`

**Affected component:**
`ac_dimmer` in conjunction with `dallas`

**Description of problem:**
When polling a dallas sensor, the ac_dimmer output stays `high` for a couple of mains cycles, therefore the light flashes for 15 ms for each dallas device read.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: geckocontrol
  platform: ESP32
  board: nodemcu-32s

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 16
    min_power: 15%
    zero_cross_pin:
      number: 17
      mode: INPUT
      inverted: no

light:
  - platform: monochromatic
    output: dimmer1
    name: "Dimmer Daylight"
    gamma_correct: 1.0
    default_transition_length: 0s

dallas:
  - pin: 22

  - platform: dallas
    address: 0x0305473B405A0028
    name: "Temperature 1"
    unit_of_measurement: "°C"

  - platform: dallas
    address: 0x5505473B82670028
    name: "Temperature 2"
    unit_of_measurement: "°C"
```

**Logs (if applicable):**
Whenever the Dallas sensors are polled (in my case everyy 60s) as indicated by the log, the light flashes and the triac output reads as following:
![image](https://user-images.githubusercontent.com/1109826/114307272-2c817c00-9adf-11eb-8611-d980da73d6fd.png)
![image](https://user-images.githubusercontent.com/1109826/114307278-32775d00-9adf-11eb-9fee-d3f6248a597e.png)
it's visible that there are 2 moments with missing triac output around each poll of the dallas sensor, taking 760ms in total, exactly the time which a dallas poll takes to complete.

**Additional information and things you've tried:**
We found out, that the dallas sensor is read blockingly and therefore a few interrupts for ac_dimmer are missed because dallas integration disables the interrupts.

**Possible solution:**
unblock/re-enable interrupts during waiting time in the dallas polling routine.
