### ISSUE TITLE
support Adafruit 2.13" e-ink feather (and other non-partial refresh displays)

### ISSUE THREAD

**Issue by osresearch** [esphome/issues#1977]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

esphome installed via pip3 on ubuntu 20.04

**ESP (ESP32/ESP8266, Board/Sonoff):**

Adafruit Feather 8266

**ESPHome version (latest production, beta, dev branch)**

1.16.2

**Affected component:**

[waveshare_epaper](https://esphome.io/components/display/waveshare_epaper.html?highlight=waveshare)

**Description of problem:**
Displays like the [Adafruit 2.13" SSD1675 displays](https://www.adafruit.com/product/4195) do not support partial refresh.  Setting `full_update_every: 1` causes problems since `WaveshareEPaperTypeA::display()` never calls `this->write_lut_()` if `this->full_update_every_` is 1:

```
  if (this->full_update_every_ >= 2) {
    if (full_update != prev_full_update) {
      if (this->model_ == TTGO_EPAPER_2_13_IN) {
        this->write_lut_(full_update ? FULL_UPDATE_LUT_TTGO : PARTIAL_UPDATE_LUT_TTGO, LUT_SIZE_TTGO);
      } else if (this->model_ == TTGO_EPAPER_2_13_IN_B73) {
        this->write_lut_(full_update ? FULL_UPDATE_LUT_TTGO_B73 : PARTIAL_UPDATE_LUT_TTGO_B73, LUT_SIZE_TTGO_B73);
      } else {
        this->write_lut_(full_update ? FULL_UPDATE_LUT : PARTIAL_UPDATE_LUT, LUT_SIZE_WAVESHARE);
      }
    }
    this->at_update_ = (this->at_update_ + 1) % this->full_update_every_;
  }
```

The fix is to preload the LUT in the initialization routine, which is what [`Adafruit_SSD1675.cpp` does](https://github.com/adafruit/Adafruit_EPD/blob/master/src/drivers/Adafruit_SSD1675.cpp#L219) or do send the full LUT everytime

**Problem-relevant YAML-configuration entries:**
```yaml
display:
  - platform: waveshare_epaper
    cs_pin: 0
    dc_pin: 15
    model: 2.13in-ttgo
    full_update_every: 1 # no partial refresh
    update_interval: 60s
    rotation: 270
    lambda: |-
      it.strftime(125, -10, id(din_big), "%H:%M", id(ntp).now());
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by osresearch** [comment]
![PXL_20210411_161536566](https://user-images.githubusercontent.com/3068843/114312172-06190c00-9af2-11eb-8566-7daf5005a52f.jpg)

Ah, looks like this was fixed in https://github.com/esphome/esphome/pull/1543 to check for `full_update_every >= 1`, which solves the problem and the display works without my hacks.  In case anyone else is looking for how to connect their Adafruit ESP8266 Feather and E-Ink Featherwing, here is the yaml for the spi and display configuration:

```yaml
spi:
  clk_pin: 14
  mosi_pin: 13
  miso_pin: 12

display:
  - platform: waveshare_epaper
    cs_pin: 0
    dc_pin: 15
    model: 2.13in-ttgo
    full_update_every: 1 # no partial refresh
    update_interval: 60s
    rotation: 270
```
