### ISSUE TITLE
Pulse Width Sensor never returns zero

### ISSUE THREAD

**Issue by koeberlue** [esphome/issues#1978]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

v1.16.2

**Affected component:**

https://esphome.io/components/sensor/pulse_width.html

**Description of problem:**

I have connected a [5V PWM Fan](https://noctua.at/de/products/fan/nf-f12-5v-pwm) and I'm trying to read out its current speed via PWM. This works perfectly fine while it is turning. But when it is stopped, I never receive a pulse width of zero. It seems like i always get the last measured value before it stopped.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: pulse_width
    pin: D0
    name: Pulse Width Sensor
    filters:
      - lambda: return 60 / (4*x);
```

**Logs (if applicable):**

```
(Will paste logs when I'm at home)
```

**Additional information and things you've tried:**

I looked into [`pulse_width.cpp`](https://esphome.io/api/pulse__width_8cpp_source.html) and it seems like `arg->last_width_` never gets reset to zero. Is this the expected behavior?
