### ISSUE TITLE
Cannot compile project using esp32_camera

### ISSUE THREAD

**Issue by vijaygill** [esphome/issues#1979]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32Cam

**ESPHome version (latest production, beta, dev branch)**
Latest dev branch pulled from git - commit - bf1885af3f5045a43dce38339485326678fc4b44

**Affected component:**
esp32_camera

**Description of problem:**
Compile failes with following error

`
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'virtual void esphome::esp32_camera::ESP32Camera::dump_config()':
src/esphome/components/esp32_camera/esp32_camera.cpp:58:10: error: 'FRAMESIZE_QQVGA2' was not declared in this scope
     case FRAMESIZE_QQVGA2:
          ^
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'void esphome::esp32_camera::ESP32Camera::set_frame_size(esphome::esp32_camera::ESP32CameraFrameSize)':
src/esphome/components/esp32_camera/esp32_camera.cpp:213:34: error: 'FRAMESIZE_QQVGA2' was not declared in this scope
       this->config_.frame_size = FRAMESIZE_QQVGA2;
                                  ^
Compiling .pioenvs/esp32cam-001/src/esphome/components/json/json_util.cpp.o
*** [.pioenvs/esp32cam-001/src/esphome/components/esp32_camera/esp32_camera.cpp.o] Error 1
`

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
    device_name: esp32cam-001
    device_name_verbose: "ESP32Cam 001"

packages:
    globals: !include common/globals.yaml

esphome:
  platform: ESP32
  board: esp32dev
  arduino_version: dev

api:

ota:

esp32_camera:
    name: "${device_name_verbose} Camera"
    external_clock:
        pin: GPIO0
        frequency: 20MHz
    i2c_pins:
        sda: GPIO26
        scl: GPIO27
    data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
    vsync_pin: GPIO25
    href_pin: GPIO23
    pixel_clock_pin: GPIO22
    power_down_pin: GPIO32
    jpeg_quality: 20
    idle_framerate: 0 fps
    max_framerate: 5 fps
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

Tried with stable version of arduino.
Cleaned up PlatformIO cache.
Cleaned build folder.
