### ISSUE TITLE
MQTT Error resolving MQTT broker IP address: -6

### ISSUE THREAD

**Issue by frspp** [esphome/issues#1981]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

macos 11.2.3, homebrew?

**ESP (ESP32/ESP8266, Board/Sonoff):**

Nodemcu ESP32

**ESPHome version (latest production, beta, dev branch)**

1.16.2.

**Affected component:**

MQTT https://esphome.io/components/mqtt.html

**Description of problem:**
Logger reads: 
"[17:17:57][C][wifi:318]:   DNS1: 0.0.0.0
...
Couldn't resolve IP address for 'http://mqtt.thingspeak.com'!
Error resolving MQTT broker IP address: -6"

Why cannot find/get DNS from router? What is error -6? Why cannot connect? 

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32ruuvi
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "CUT"
  password: "CUT"
  fast_connect: true
  manual_ip:
    static_ip: 192.168.8.42
    subnet: 255.255.255.0
    gateway: 192.168.8.1

# Enable logging
logger:

ota:
  password: "CUT"

# Ruuvitags BLE
esp32_ble_tracker:

sensor:
  - platform: ruuvitag
    mac_address: CUT
    humidity:
      name: "Ruuvi B18C Humidity"
      id: ruuvib18ch
    temperature:
      name: "Ruuvi B18C Temperature"
      id: ruuvib18ct
    pressure:
      name: "Ruuvi B18C Pressure"
      id: ruuvib18cp

dallas:
  - pin: GPIO32 
    update_interval: 10s

mqtt:
  broker: http://mqtt.thingspeak.com
  username: whatever
  password: CUT
  discovery: false

interval:
  - interval: 15sec
    then:
    - mqtt.publish:
        topic: channels/CUT/publish/CUT 
        payload: field1=ilpsisaimut&field2=ilpsisapuhallust&field3=ruuvib18ct&field4=ruuvib18ch&field5=ruuvia0act&field6=ruuvia0ach&field7=ruuvi2a0dt&field8=shellyilp


```

**Logs (if applicable):**

```
[17:17:57][C][wifi:318]:   DNS1: 0.0.0.0
[17:17:57][C][wifi:319]:   DNS2: 0.0.0.0

[16:47:09][W][mqtt:127]: Couldn't resolve IP address for 'http://mqtt.thingspeak.com'!
[16:47:09][W][mqtt:112]: Error resolving MQTT broker IP address: -6

```

**Additional information and things you've tried:**
Tried adding router ip for dns, no help. Tried adding DNS ip from router, no help.

**Comment by frspp** [comment]
Aha, I see in the logs "dns: 0.0.0.0.0". 

Tried settings dns1 manually. Now I did OTA flash and still get "ERROR Cannot connect to MQTT broker: [Errno 8] nodename nor servname provided, or not known"

**Comment by frspp** [comment]
updated the OP

**Comment by koenvervloesem** [comment]
When using DHCP, your DHCP server sends your client the IP addresses of DNS servers. You have set up your IP address manually, so you need to [add the DNS servers manually](https://esphome.io/components/wifi.html#configuration-variables):

```yaml
wifi:
  ssid: "CUT"
  password: "CUT"
  fast_connect: true
  manual_ip:
    static_ip: 192.168.8.42
    subnet: 255.255.255.0
    gateway: 192.168.8.1
    dns1: YOURDNS1
    dns2: YOURDNS2
```

The `http://` before the domain of the MQTT broker is wrong too: it just needs a hostname or IP address, no protocol (which isn't http anyway).
