### ISSUE TITLE
'Open Node Web Server Interface' link does not contain web server port (e.g. 8080)

### ISSUE THREAD

**Issue by QNimbus** [esphome/issues#1984]
When using a non-standard TCP port for the webserver on the ESP node (e.g. `8080` instead of the default `80`) the dashboard link does not work. This is because the generated link does not contain a TCP port.

Snippet of my YAML config:

```yaml
---
  # ESPHome integration. See: https://www.home-assistant.io/integrations/esphome & https://esphome.io/
  esphome:
    name: esphome_home_ff_office_appliance_relays
    comment: Prusa MK3S+ Relays
    platform: ESP8266
    board: d1_mini

  wifi:
    ssid: !secret wifi_iot_ssid
    password: !secret wifi_iot_wpa2

    # If you have changed your static IP and want to flash OTA to the previously configured IP address.
    # use_address: 10.30.90.6

    # # Optional manual IP
    # manual_ip:
    #   static_ip: 10.30.90.6
    #   gateway: 10.30.0.1
    #   subnet: 255.255.0.0

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: !secret wifi_ap_captive_ssid
      password: !secret wifi_ap_captive_wpa2

  captive_portal:

  # Enable logging
  logger:

  # Enable Home Assistant API
  api:
    password: !secret esphome_api_password

  # OTA Password. See: https://esphome.io/components/ota.html#updating-the-password
  #
  # Since the password is used both for compiling and uploading the regular esphome <file> run won’t work of course.
  # This issue can be worked around by executing the operations separately through an on_boot trigger. See link.
  ota:
    password: !secret esphome_ota_password

  web_server:
    port: 8080
    auth:
      username: !secret esphome_web_server_username
      password: !secret esphome_web_server_password

...
```

In my case the link generated is: `http://esphome_home_ff_office_appliance_relays.local/` and should be `http://esphome_home_ff_office_appliance_relays.local:8080/`

![image](https://user-images.githubusercontent.com/3206309/114889697-9fa22f80-9e0a-11eb-9aaf-62ff83e2731a.png)
