### ISSUE TITLE
'Open Node Web Server Interface' link does not contain web server port (e.g. 8080)

### ISSUE THREAD

**Issue by QNimbus** [esphome/issues#1985]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 Wemos D1

**ESPHome version (latest production, beta, dev branch)**

ESPHome version v1.16.2

**Affected component:**

ESPHome dashboard

**Description of problem:**

When using a non-standard TCP port for the webserver on the ESP node (e.g. `8080` instead of the default `80`) the dashboard link does not work. This is because the generated link does not contain a TCP port. (See YAML config)

In my case the link generated is: `http://esphome_home_ff_office_appliance_relays.local/` and should be `http://esphome_home_ff_office_appliance_relays.local:8080/`

**Problem-relevant YAML-configuration entries:**

```yaml
---
  # ESPHome integration. See: https://www.home-assistant.io/integrations/esphome & https://esphome.io/
  esphome:
    name: esphome_home_ff_office_appliance_relays
    comment: Prusa MK3S+ Relays
    platform: ESP8266
    board: d1_mini

.....
  
  web_server:
    port: 8080
    auth:
      username: !secret esphome_web_server_username
      password: !secret esphome_web_server_password

.....
```

**Logs (if applicable):**

Not applicable

**Additional information and things you've tried:**

This is the dashboard link I'm reffering to: 

![image](https://user-images.githubusercontent.com/3206309/114889697-9fa22f80-9e0a-11eb-9aaf-62ff83e2731a.png)

This issue can likely be resolved by changing [this part](https://github.com/esphome/esphome/blob/e6f8e73705dc310cb8b188fd509b543fe3ad7cf9/esphome/dashboard/templates/index.html#L75) part of the `esphome/dashboard/templates/index.html` template file.

In the template _only_ the address is used to form the URL. The web server port also should be used to form the URL.

```
              {% if 'web_server' in entry.loaded_integrations %}
              <a href="http://{{ escape(entry.address) }}" target="_blank"><i
                  class="material-icons node-webserver right tooltipped" data-position="left"
                  data-tooltip="Open Node Web Server Interface">launch</i></a>
              {% end %}
```
