### ISSUE TITLE
ESP32 / SCD30 / temperature_offset

### ISSUE THREAD

**Issue by LeDistordu** [esphome/issues#1986]
i follow this documentation
https://esphome.io/components/sensor/scd30.html

I have ESP32 NodeMCU and sensor SCD30

When i add "temperature_offset" like documentation, i have an error : [scd30:089]: Measurement Initialization failed!

```
- platform: scd30
    automatic_self_calibration: true
    co2:
      name: "co2"
      accuracy_decimals: 1
    temperature:
      name: "temperature"
      accuracy_decimals: 2
    humidity:
      name: "humidity"
      accuracy_decimals: 1
#     temperature_offset: 1.5 °C
    update_interval: 300s
```

Without it's ok !

I try : 

```
temperature_offset: 1.5 °C
temperature_offset: "1.5 °C"
temperature_offset: '1.5 °C'
temperature_offset: 1.5
```

**Comment by ashald** [comment]
For those who'd run into the same issue - as I did - IDK whether `temperature_offset` is supported at all, or erroneously present in the docs, but there is another way around.
SCD30 component is based on the sensor platform which provides a generic way to post-process values - [Sensor Filter](https://esphome.io/components/sensor/index.html#sensor-filters).
This works like a charm and my config looks like this now:
```
sensor:
  - platform: scd30
    i2c_id: bus_a
    co2:
      name: "Basement CO2"
      accuracy_decimals: 1
    temperature:
      name: "Basement Temperature"
      accuracy_decimals: 2
      filters:
        - offset: -3.0
    humidity:
      name: "Basement Humidity"
      accuracy_decimals: 1
    update_interval: 60s
```
