### ISSUE TITLE
ESP32 / SCD30 / problem with "temperature_offset"

### ISSUE THREAD

**Issue by LeDistordu** [esphome/issues#1987]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker / Homeassistant

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 NodeMCU

**ESPHome version (latest production, beta, dev branch)**

ESPHome version v1.16.2

**Affected component:**

ESP32

**Description of problem:**

i follow this documentation
https://esphome.io/components/sensor/scd30.html

I have ESP32 NodeMCU and sensor SCD30

When i add "temperature_offset" like documentation, i have an error : [scd30:089]: Measurement Initialization failed!

```
- platform: scd30
    automatic_self_calibration: true
    co2:
      name: "co2"
      accuracy_decimals: 1
    temperature:
      name: "temperature"
      accuracy_decimals: 2
    humidity:
      name: "humidity"
      accuracy_decimals: 1
#     temperature_offset: 1.5 °C
    update_interval: 300s
```

Without it's ok !

I try : 

```
temperature_offset: 1.5 °C
temperature_offset: "1.5 °C"
temperature_offset: '1.5 °C'
temperature_offset: 1.5
```
