### ISSUE TITLE
Power supply component and binary light

### ISSUE THREAD

**Issue by jamien82** [esphome/issues#1988]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home assistant OS

**ESP (ESP32/ESP8266, Board/Sonoff):**
Lolin ESP8288 D1 Pro

**ESPHome version (latest production, beta, dev branch)**
 v 1.16.2

**Affected component:**
https://esphome.io/components/power_supply.html

**Description of problem:**

I have a atx powersupply controlling some lights in my bus, I want to turn on powersupply when lights switched on but it throws an error

  [power_supply] is an invalid option for [light.binary]. Please check the indentation.
  power_supply: atx_power_supply [source /config/esphome/bus_controller.yaml:100]

Im sure im doing it correctly, but im still having problems.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: bus_controller
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: !secret wifissid
  password: !secret wifikey
  reboot_timeout: "5min"
  manual_ip:
    static_ip: 192.168.5.43
    subnet: 255.255.255.0
    gateway: 192.168.5.252
  use_address: "192.168.5.43"
  fast_connect: true

#
# Pins in use
#   I2C           D1
#   I2C           D2
#   RF            D3
#   Power Relay   D4
#






logger:
 level: VERBOSE

debug:

# Enable Home Assistant API
api:

ota:


i2c:
  sda: D2
  scl: D1
  scan: True
  frequency: 200kHz
  
# Example configuration entry
mcp23017:
  - id: 'mcp23017_output'
    address: 0x20
  - id: 'mcp23017_Input'
    address: 0x21

sensor:
  - platform: bmp280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    address: 0x76
    update_interval: 60s


power_supply:
  - id: 'atx_power_supply'
    pin:
      number: D4
      inverted: true


switch:
  - platform: gpio
    name: "Un commoned 1"
    pin:
      mcp23017: mcp23017_output
      number: 0
      mode: OUTPUT
      inverted: false
    id: out0
  - platform: gpio
    name: "Un commoned 2"
    pin:
      mcp23017: mcp23017_output
      number: 1
      mode: OUTPUT
      inverted: false
  - platform: gpio
    name: "Un commoned 3"
    pin:
      mcp23017: mcp23017_output
      number: 2
      mode: OUTPUT
      inverted: False
      
light:
  - platform: binary
    name: "Kitchen floor"
    output: pin3
    power_supply: atx_power_supply
    
  - platform: binary
    name: "MCP23017 Pin #4"
    output: pin4

  - platform: binary
    name: "Drivers seat"
    output: pin5

  - platform: binary
    name: "MCP23017 Pin #6"
    output: pin6

  - platform: binary
    name: "Top bunk"
    output: pin7

  - platform: binary
    name: "Master bed"
    output: pin8

  - platform: binary
    name: "Sink"
    output: pin9

  - platform: binary
    name: "Wardrobe"
    output: pin10

  - platform: binary
    name: "Outside"
    output: pin11

  - platform: binary
    name: "Bright shoe rack"
    output: pin12

  - platform: binary
    name: "Shoe rack"
    output: pin13

  - platform: binary
    name: "Tall boy"
    output: pin14

  - platform: binary
    name: "Front middle"
    output: pin15

      
output:

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin3"
    pin:
      mcp23017: mcp23017_output
      number: 3
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin4"
    pin:
      mcp23017: mcp23017_output
      number: 4
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin5"
    pin:
      mcp23017: mcp23017_output
      number: 5
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin6"
    pin:
      mcp23017: mcp23017_output
      number: 6
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin7"
    pin:
      mcp23017: mcp23017_output
      number: 7
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin8"
    pin:
      mcp23017: mcp23017_output
      number: 8
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin9"
    pin:
      mcp23017: mcp23017_output
      number: 9
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin10"
    pin:
      mcp23017: mcp23017_output
      number: 10
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin11"
    pin:
      mcp23017: mcp23017_output
      number: 11
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin12"
    pin:
      mcp23017: mcp23017_output
      number: 12
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin13"
    pin:
      mcp23017: mcp23017_output
      number: 13
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin14"
    pin:
      mcp23017: mcp23017_output
      number: 14
      mode: OUTPUT
      inverted: False

  - platform: gpio
    power_supply: atx_power_supply
    id: "pin15"
    pin:
      mcp23017: mcp23017_output
      number: 15
      mode: OUTPUT
      inverted: False


     
      
      
      
binary_sensor:
      
  - platform: gpio
    name: "MCP23017 Input Pin #0"
    pin:
      mcp23017: mcp23017_Input
      number: 0
      mode: INPUT_PULLUP
      inverted: false
    on_release:
      - switch.toggle: out0
      
  - platform: gpio
    name: "MCP23017 Input Pin #1"
    pin:
      mcp23017: mcp23017_Input
      number: 1
      mode: INPUT_PULLUP
      inverted: false
  - platform: gpio
    name: "MCP23017 Input Pin #2"
    pin:
      mcp23017: mcp23017_Input
      number: 2
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #3"
    pin:
      mcp23017: mcp23017_Input
      number: 3
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #4"
    pin:
      mcp23017: mcp23017_Input
      number: 4
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #5"
    pin:
      mcp23017: mcp23017_Input
      number: 5
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #6"
    pin:
      mcp23017: mcp23017_Input
      number: 6
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #7"
    pin:
      mcp23017: mcp23017_Input
      number: 7
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #8"
    pin:
      mcp23017: mcp23017_Input
      number: 8
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #9"
    pin:
      mcp23017: mcp23017_Input
      number: 9
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #10"
    pin:
      mcp23017: mcp23017_Input
      number: 10
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #11"
    pin:
      mcp23017: mcp23017_Input
      number: 11
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #12"
    pin:
      mcp23017: mcp23017_Input
      number: 12
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #13"
    pin:
      mcp23017: mcp23017_Input
      number: 13
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #14"
    pin:
      mcp23017: mcp23017_Input
      number: 14
      mode: INPUT_PULLUP
      inverted: False
  - platform: gpio
    name: "MCP23017 Input Pin #15"
    pin:
      mcp23017: mcp23017_Input
      number: 15
      mode: INPUT_PULLUP
      inverted: False

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
