### ISSUE TITLE
homeassistant.service - light.turn_on sending "rgb_color" fails - does not accept "list"?

### ISSUE THREAD

**Issue by tubalainen** [esphome/issues#1993]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 / NodeMCU V2

**ESPHome version (latest production, beta, dev branch)**

ESPHome 1.16.1

**Affected component:**

**Description of problem:**
https://esphome.io/components/api.html#homeassistant-service-action

**Problem-relevant YAML-configuration entries:**
```yaml
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      inverted: True
    name: "Displaylabb knapp 1"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - homeassistant.service:
            service: light.turn_on
            data:
              entity_id: light.lampa_ikea_rgb
              rgb_color: [0,255,255] # <<- Not allowed by the editor "must be a string", making it into a string will not be accepted by HA
```

**Logs (if applicable):**

```
N/A

```

**Additional information and things you've tried:**
https://www.home-assistant.io/integrations/light/
https://github.com/esphome/issues/issues/784
https://community.home-assistant.io/t/passing-list-to-service-call/266214

![image](https://user-images.githubusercontent.com/26795429/115403643-e74eff80-a1ec-11eb-8d66-50809d8ec3fa.png)
