### ISSUE TITLE
Esphome esp32-->BME280

### ISSUE THREAD

**Issue by swbouman** [esphome/issues#1995]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32

**ESPHome version (latest production, beta, dev branch)**

1.16.2
**Affected component:**

BME280

**Description of problem:**

Hi everyone,

I've installed a bme280 sensor. It functioned very well but after a power cycle the sensor refuses to send measurements. It is seen at i2c adres, communication is active, but no readings. Sometimes it starts output at sudden time, but it stays a sleep most of the time. 

Any ideas how to get communication available?

Kind regards

**Problem-relevant YAML-configuration entries:**
```yaml
  esphome:
  name: schuur
  platform: ESP32
  board: nodemcu-32s

      
wifi:
  ssid: "XXXX"
  password: "XXXX"


captive_portal:

# Enable logging
logger:
 level: VERBOSE

# Enable Home Assistant API
api:
  password: "XXXX"

ota:
  password: "XXXX"

i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a
  
sensor:

  - platform: bme280
    temperature:
      id: bme280_temperature
      name: "Temperatuur"
      oversampling: 16x
    pressure:
      name: "Luchtdruk"
    humidity:
      id: bme280_humidity
      name: "luchtvochtigheid"
      oversampling: 16x
    address: 0x76
    update_interval: 60s
```

**Logs (if applicable):**

```
[12:35:11][I][i2c:033]: Scanning i2c bus for active devices...
[12:35:11][I][i2c:040]: Found i2c device at address 0x23
[12:35:11][I][i2c:040]: Found i2c device at address 0x76
```

**Additional information and things you've tried:**
