### ISSUE TITLE
ESP32-cam not sending image to Home Assistant after adding directional adjustments

### ISSUE THREAD

**Issue by palengh** [esphome/issues#1999]
Further trying to get the ESP32-cam setup right (See https://discord.com/channels/429907082951524364/429907082955718657/835485118499913728).

This could be a flashing issue or similar. I have now reflashed the esp 10 times, only to get the same result. When saving the yaml without the esp32_camera settings, then pasting in the yaml below, saving and re-flashing OTA, image shows up in HA, but flipped.

```yaml
esp32_camera:
  name: ${friendly_name}
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  resolution: 1024x768
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
```

Then when adding `vertical_flip: false`, the image disappears in HA, but ESPHome desktop log shows a continous stream of images. Then, if remark it (#)  `vertical_flip: false`, recompiling no image. When pasting in the original code, it all works. Seems like my camera, sa shown in HA cannot take the `vertical_flip: false` parameter, or `horizontal_mirror` for that matter.
