### ISSUE TITLE
Set Sleep Duration lambda service command not working 

### ISSUE THREAD

**Issue by curt7000** [esphome/issues#2004]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

PIP
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**ESPHome version (latest production, beta, dev branch)**

1.16.2
**Affected component:**

Deep Sleep

**Description of problem:**
I am trying to adjust the deep_sleep time via a MQTT payload. I have the code below, but the set_sleep_duration does not appear to be working. My ESP8266 will go to sleep but never wake. Note: I am ensuring the MQTT payload is OFF prior to re-awaking.

**Problem-relevant YAML-configuration entries:**
```yaml
`deep_sleep:
id: deep_sleep_1

mqtt:
broker: 10.0.1.10
username: homeassistant
password: my password
birth_message:
will_message:
on_message:
- topic: officecontroller/ota_mode
payload: 'ON'
then:
- deep_sleep.prevent: deep_sleep_1
- topic: officecontroller/sleep_mode_day
payload: 'ON'
then:
- logger.log: "Time to sleep ... setting sleep duration"
- lambda: |-
id(deep_sleep_1).set_sleep_duration(6000);
- logger.log: "Delaying sleep by 10s"
- delay: 10s
- logger.log: "Time to sleep !!! Hibernating"
- deep_sleep.enter: deep_sleep_1
- topic: officecontroller/sleep_mode_night
payload: 'ON'
then:
- logger.log: "Time to sleep ... setting sleep duration"
- lambda: |-
id(deep_sleep_1).set_sleep_duration(12000);
- logger.log: "Delaying sleep by 10s"
- delay: 10s
- logger.log: "Time to sleep !!! Hibernating"
- deep_sleep.enter: deep_sleep_1`

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
