### ISSUE TITLE
ESP32 + Hidden SSID + fast_connect = RSSI sensor not updating

### ISSUE THREAD

**Issue by KosieKramer** [esphome/issues#2006]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome (1.16.2) on Home Assistant (core-2021.4.6)

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 WROOM32 development board

**ESPHome version (latest production, beta, dev branch)**

v1.16.2

**Affected component:**

https://esphome.io/components/wifi.html
https://esphome.io/components/sensor/wifi_signal.html

**Description of problem:**
When using ESP32 WROOM32 devices, together with a hidden SSID and the fast_connect directive, the wifi_signal sensor does not update, but keeps reporting the same value. Confirmed with 4 different boards, in 2 sites. One site using FortiNet AP's and the other Ubiquiti Unifi AP's. The other ESP8266-based devices behave normally in the same environments.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32_main_db
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "Hidden SSID"
  password: "blahblahblah"
  fast_connect: true
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Main Db Fallback Hotspot"
    password: "blahblahblah"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "blahblahblah"

ota:
  password: "blahblahblah"

sensor:
  - platform: wifi_signal
    name: "Main DB RSSI"
    update_interval: 60s

  - platform: dht
    pin: GPIO15
    temperature:
      name: "Main DB Temperature 1"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 60
    humidity:
      name: "Main DB Humidity 1"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 60
    update_interval: 1s

  - platform: dht
    pin: GPIO4
    temperature:
      name: "Main DB Temperature 2"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 60
    humidity:
      name: "Main DB Humidity 2"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 60
    update_interval: 1s

switch:
  - platform: restart
    name: "ESP32 Main DB Restart"

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
