### ISSUE TITLE
Random colour flickering with RGBW strip

### ISSUE THREAD

**Issue by bashlk** [esphome/issues#2007]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Homeassistant 2021.2.3 installed via pip on rpi2b

**ESP (ESP32/ESP8266, Board/Sonoff):**
NodeMCU (ESP8266)

**ESPHome version (latest production, beta, dev branch)**
1.15.3

**Affected component:**
https://esphome.io/components/light/neopixelbus.html

**Description of problem:**
I have a BTF lighting SK6812 RGBW LED strip attached to a NodeMCU to be controlled by the neopixelbus integration and it results in random colour flickering (most frequently green) every time a new colour is set (happens regardless of the colour) Once a colour has been set, it is maintained without any flickering. (See video - https://imgur.com/a/txPpxNU - I am just activating the same scene repeatedly and it behaves differently each time)

The LED strip is powered by a 5V 4A power supply and its data pin is directly attached to the ESP and the ground is shared. This setup worked flawlessly for a few months until this flickering started and progressively got worse.

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: neopixelbus
    id: screen
    type: GRBW
    pin: GPIO2
    num_leds: 130
    name: "Screen Light"
    variant: SK6812
    method: ESP8266_UART1
    effects:
      - random:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_twinkle:
      - addressable_random_twinkle:
```

**Additional information and things you've tried:**
I tried using different methods / pins but nothing changed. I also have another another part of the same LED strip (27 LEDS) connected to a completely different power supply (5V 2A) and a Wemos D1 that is showing the same behaviour.
