### ISSUE TITLE
MQTT messages may be silently discarded instead of being published

### ISSUE THREAD

**Issue by smurfix** [esphome/issues#2009]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Lunix bullseye, venv

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff S20

**ESPHome version (latest production, beta, dev branch)**

dev

**Affected component:**

https://www.home-assistant.io/docs/mqtt/

**Description of problem:**
When I publish multiple MQTT messages, some are silently discarded.

Inserting a delay fixes the problem.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  on_boot:
    then:
    - delay: 5s
    - mqtt.publish_json: …
    - mqtt.publish_json: …
    - mqtt.publish_json: …
    - mqtt.publish_json: …
```

Of these four messages (fairly large ones, but then the ESP8266 has enough memory, 55% free) only two are transmitted.

**Logs (if applicable):**

No logs, mqtt debug doesn't report anything. Specifically it doesn't report discarding any messages.

**Additional information and things you've tried:**

Workaround: Add a delay between these messages. But that's not a long-term solution as I suspect that the problem may show up in other contexts.
