### ISSUE TITLE
binary_sensor stops checking state?

### ISSUE THREAD

**Issue by jordansissel** [esphome/issues#2017]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU ESP-32S

**ESPHome version (latest production, beta, dev branch)**

1.16.2

**Affected component:**

https://esphome.io/components/binary_sensor/index.html?highlight=device_class#binary-sensor-filters

**Description of problem:**

When using a gpio binary_sensor, I am finding that sometimes my device stops registering state changes entirely for this sensor. I haven't found any correlated settings involved in this problem.

**Problem-relevant YAML-configuration entries:**
```yaml
output:
  - platform: gpio
    pin: GPIO2
    id: blue_led

binary_sensor:
  - platform: gpio
    name: "power"
    device_class: power # https://www.home-assistant.io/integrations/binary_sensor
    pin: 
      number: GPIO23
      mode: INPUT_PULLDOWN

    # Debounce any light flickering.
    filters:
    - delayed_on_off: 100ms

    on_press:
      then:
        - output.turn_on: blue_led
    on_release:
      then:
        - output.turn_off: blue_led

  - platform: gpio
    device_class: problem # https://www.home-assistant.io/integrations/binary_sensor
    name: "fault"
    pin: 
      number: GPIO22
      mode: INPUT_PULLDOWN
```

**Logs (if applicable):**

```
[22:01:45][D][binary_sensor:036]: 'power': Sending state OFF
[22:01:45][D][binary_sensor:036]: 'power': Sending state ON
[22:01:45][D][binary_sensor:036]: 'fault': Sending state ON
[22:01:45][D][binary_sensor:036]: 'fault': Sending state OFF


```

**Additional information and things you've tried:**

Overall, I observe that the log output "Sending state ..." for each sensor will stop appearing the logs for unknown reasons.

I wondered if this was some serial port delay, so I setup `on_press`/`on_release` to toggle the blue led on the nodemcu board to represent the state of one of binary_sensor entries.

I then had a hypothesis that `delayed_on_off` filter was caused, so I configured two phototransistors (via binary_sensor gpio), one with and without that filter. Same rough effect.

I've tested a few different hypothesis and still haven't come up with a solution.

Any ideas of what I can do next? Is this a bug? It's hard to tell if the esp32s is stuck/stalled or if the binary_sensor has stopped reporting?
