### ISSUE TITLE
pulse_meter seems to be doubling the amount of pulses counted

### ISSUE THREAD

**Issue by pedrolamas** [esphome/issues#2022]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):** ESP8266

ESP8266
**ESPHome version (latest production, beta, dev branch)**

v1.17.0
**Affected component:**

https://esphome.io/components/sensor/pulse_meter.html

**Description of problem:**

For a while now I've been using the `pulse_counter` to count the light pulses on my power meter and it has worked very well in that!

I see that the latest version of ESPHome is recommending to use `pulse_meter` so I replaced it today and it seems to be counting double the amount of pulses than the `pulse_counter`

**Problem-relevant YAML-configuration entries:**

old yaml:

```yaml
sensor:
  - platform: pulse_counter
    id: pulse_counter_d1
    name: "${esphome_name} Power Meter"
    pin: D1
    unit_of_measurement: "kW"
    accuracy_decimals: 3
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 10ms
    filters:
      - multiply: 0.075
    total:
      name: "${esphome_name} Total Pulses"
```

new yaml:

```yaml
sensor:
  - platform: pulse_meter
    id: pulse_counter_d1
    name: "${esphome_name} Power Meter"
    pin: D1
    unit_of_measurement: "kW"
    accuracy_decimals: 3
    internal_filter: 10ms
    filters:
      - multiply: 0.075
    total:
      name: "${esphome_name} Total Pulses"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by olicooper** [comment]
I noticed that `App.register_component` is called twice in my code. I wonder if this is causing the issue?

```c
power_kw = new pulse_meter::PulseMeterSensor();
App.register_component(power_kw);
// ...
App.register_sensor(power_kw);
power_kw->set_unit_of_measurement("kW");
power_kw->set_force_update(false);
// ...
```

I also have an issue where the 'total daily energy' keeps resetting itself. Might open a separate issue.

**Comment by pedrolamas** [comment]
Thanks for your comments @olicooper, but I don't think that is a problem as I also see that with `pulse_counter`

**Comment by pedrolamas** [comment]
Hi @stevebaxter, as you implemented the `pulse_meter` in https://github.com/esphome/esphome/commit/a77784a6da8ef60e065db96d769092c759faf6e4, I was hoping you might have some insight on this matter?

**Comment by stevebaxter** [comment]
Couple of things to check:

1. Make sure you have the right pull-up/down setting for the pin your sensor is on. Photodiodes in particular are often a bit noisy when switching, this could be counted as a second pulse. Pulling to the right level should help with that.
2. Set a longer value for `internal_filter`. This is the length of time after a pulse that we will ignore any further pulses, again this will help you ignore any noise.

This is my setup for my electricity meter (1000 pulses/kWh). I'm using a photodiode with some electronics that's "active low", so I pull up the pin it's on (I'm pretty sure that's right, and it seems to work):
```
sensor:
  - platform: pulse_meter
    name: "Electricity"
    pin:
      number: D5
      mode: INPUT_PULLUP
    unit_of_measurement: "kW"
    internal_filter: 100ms
    accuracy_decimals: 3
    timeout: 2 min
    filters:
      # Convert pulses/min (Wh/min) to kW
      - multiply: 0.06
    total:
      name: "Electricity Meter"
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
```
It looks like your meter uses 800 pulses/kWh? In this case, even if your house is using 20 kW (a lot) you should only get 4.5 pulses/second, so 100ms as the filter should be fine.

**Comment by stevebaxter** [comment]
No need to invert - we detect a rising edge, it doesn't really matter if that edge is at the start or end of the pulse as it's the distance between pulses we're looking for. 10ms is very short, you want this to be as long as possible while still allowing you to record the maximum likely level from the meter.

**Comment by stevebaxter** [comment]
What exactly is your sensor?

**Comment by pedrolamas** [comment]
Right now I'm using a simple LDR but I do have a TEPT4400 transistor that I need to assemble!

With 100ms seems to be correctly measuring, here's my current config:

```yaml
sensor:
  - platform: pulse_meter
    id: pulse_meter_d1
    name: "${esphome_name} Power Meter"
    pin: D1
    unit_of_measurement: "kW"
    accuracy_decimals: 3
    internal_filter: 100ms
    filters:
      - multiply: 0.075
    total:
      name: "${esphome_name} Total Energy"
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      filters:
        - multiply: 0.001

  - platform: total_daily_energy
    name: "${esphome_name} Total Daily Energy"
    power_id: pulse_meter_d1
```

This seems to be updating home assistant every ~0.5s... is this expected?

![image](https://user-images.githubusercontent.com/85504/117483121-3753f300-af5d-11eb-8890-503325b60c42.png)
