### ISSUE TITLE
Device class attribute is missing in MQTT discovery payload

### ISSUE THREAD

**Issue by definitio** [esphome/issues#2023]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Arch Linux, Python 3.9, pip.

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**

1.17.0

**Affected component:**

https://esphome.io/components/sensor/index.html

**Description of problem:**
Setting `device_class` doesn't work.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: template
    name: $room illuminance
    state_topic: ${room}/sensor/illuminance
    device_class: illuminance
    lambda: 'return id(indoor_illuminance_raw).state;'
    update_interval: 10s
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 6
          send_first_at: 6
```

**Additional information and things you've tried:**
Icon is also missing. It was there in the previous version.
