### ISSUE TITLE
DHT sensor error when NAME in non-English characters

### ISSUE THREAD

**Issue by IvanGavrilenko** [esphome/issues#2027]
When attached DHT-11 sensor and if _name_ section in sensor block consists of only English cahracters - then web server and HomeAssistant receives both values - temperature and humidity:
```
sensor:
  - platform: dht
    pin: D3
    temperature:
      name: Temperature #pay attantion to this name
      filters:
        - filter_out: nan
    humidity:
      name: Humidity #pay attantion to this name
      filters:
        - filter_out: nan
    update_interval: 20s
```
![Working HomeAssistant](https://user-images.githubusercontent.com/37136246/117298306-e4583e00-ae7f-11eb-8f7e-441ee32e0e4a.jpg)
![working web server](https://user-images.githubusercontent.com/37136246/117298309-e4f0d480-ae7f-11eb-8744-d54633c871e9.jpg)

But if the _name_ section consists of only Russian characters then both web server and HomeAssistant show the single sensor (and web server shows name from temperature and value - from humidity - it looks like the temperature sensor obtains the value from the temperature and shows the temperature value and then after a part of second the humidity value is written to the same sensor and overwrites it's value): 
```
sensor:
  - platform: dht
    pin: D3
    temperature:
      name: Температура #The error goes here 
      filters:
        - filter_out: nan
    humidity:
      name: Влажность #The error goes here 
      filters:
        - filter_out: nan
    update_interval: 20s
```
![not working HomeAssistant](https://user-images.githubusercontent.com/37136246/117299062-c50de080-ae80-11eb-98a9-4899139e89bd.jpg)
![not working web server](https://user-images.githubusercontent.com/37136246/117299065-c5a67700-ae80-11eb-8311-6c0b36330ae4.jpg)

the both YAMLs and parts VERY_VERBOSE logs having sensor value obtaining are attached
[working log.txt](https://github.com/esphome/issues/files/6434438/working.log.txt)
[not working log.txt](https://github.com/esphome/issues/files/6434440/not.working.log.txt)
[YAML working.txt](https://github.com/esphome/issues/files/6434453/YAML.working.txt)
[YAML not working.txt](https://github.com/esphome/issues/files/6434454/YAML.not.working.txt)
