### ISSUE TITLE
pulse_meter 'total' not working as expected

### ISSUE THREAD

**Issue by olicooper** [esphome/issues#2034]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HomeAssistant (2021.4.6) on Ubuntu, VSCode & pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU v2 (ESP8266)

**ESPHome version (latest production, beta, dev branch)**

1.17.1

**Affected component:**

https://esphome.io/components/sensor/pulse_meter.html

**Description of problem:**
Couple of issues...
1. Using the `total` variable, I want to output the total daily energy. With the original [total_daily_energy](https://esphome.io/components/sensor/total_daily_energy.html) component it used to reset at midnight but this one uses the generic 'sensor' component which doesn't do this. This new component is advertised as a drop-in for the original so I assumed it would work the same. Is this a design decision or an oversight? We could update the [power_meter docs](https://esphome.io/components/sensor/pulse_meter.html#counting-total-pulses) to tell the user to use 'total_daily_energy' sensor instead of 'total' if they want to display total daily enegy?
2. The `total` that is output also keeps resetting randomly. My original configuration worked flawlessly. I am in the process of testing if it is due to hard reset from memory overflow or something. My initial thoughts are that it might be the speed that updated values are published?

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: pulse_meter
    pin: D5 #14
    unit_of_measurement: 'kW'
    icon: "mdi:flash"
    name: ${node_name} Power kW
    id: power_kw
    internal_filter: 50ms
    filters:
      - multiply: 0.06
    total:
      name: ${node_name} Total Daily Energy
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
```

**Logs (if applicable):**

**Additional information and things you've tried:**
