### ISSUE TITLE
ADC creates same MQTT unique_id for every sensor on the same board

### ISSUE THREAD

**Issue by akoivist** [esphome/issues#2036]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

1.17.1

**Affected component:**

ADC

**Description of problem:**
ADC creates a unique_id using just node-mac + "-adc". This is a problem for example when we want two ADC-sensors: one with the raw value, and a second one with filtered value.
I would prefer ADC to use sensor id instead of the fixed "-adc".

The code:
https://github.com/esphome/esphome/blob/229bf719a2bc40f1ef297efb88684c97f47a458f/esphome/components/adc/adc_sensor.cpp#L90

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: adc
    pin: A0
    name: "Ford 12V Voltage"
    update_interval: 5s
    accuracy_decimals: 1
    filters:
     - sliding_window_moving_average:
        window_size: 5
        send_first_at: 3
     - calibrate_linear:
       - 0.74 -> 12
       - 0.95 -> 15.3
     - or:
       - throttle: 120s
       - delta: 0.2
    availability:    
    expire_after: 11min
    retain: False

  - platform: adc
    pin: A0
    name: "Ford 12V Voltage raw"
    id: "ford_12v_voltage_raw"
    update_interval: 5s
    accuracy_decimals: 3
    filters:
     - or:
       - throttle: 120s
       - delta: 0.1
    availability:    
    expire_after: 11min
    retain: False

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
