### ISSUE TITLE
ESPHome - Sonoff T1 - WIFI Light

### ISSUE THREAD

**Issue by meatalhead** [esphome/issues#2039]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome v1.16.2 used to flash a Sonoff T1 (UK), running in Docker accessed through HASS core-2021.4.6

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff T1 (UK)

**ESPHome version (latest production, beta, dev branch)**

ESPHome v1.16.2

**Affected component:**

https://esphome.io/cookbook/sonoff-basic-light-switch.html

**Description of problem:**
The T1 has been flashed and functions within HASS, using the code below. The wifi light does not stop blinking, the wifi signal strength is healthy on the logs at -40 db. Is there something I've missed in the code to stop the wifi light or is this a fault?

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: nursey_light_switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_SSID
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret StaticID
    gateway: !secret GatewayID
    subnet: 255.255.255.0
  power_save_mode: none
  reboot_timeout: 10s
  ap:
    ssid: "Nursery Light Switch Hotspot"
    password: !secret wifi_password

# Enable logging
logger:

captive_portal:

api:

ota:

mqtt:
  broker: !secret BrokerID
  username: !secret MQTT_ID
  password: !secret MQTT_password
  port: 1883
  discovery: True
  discovery_retain: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: nursery_light_switch
    
    on_multi_click:
    #double click
#    - timing:
#      - ON for at most 1s
#      - OFF for at most 1s
#      - ON for at most 1s
#      - OFF for at most 0.2s
#      then:
#        - light.toggle: nursery_light_switch_light
    #hold button
    - timing:
      - ON for 1s to 5s
      - OFF for at least 0.5s
      then:
        - homeassistant.service:
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.nursery_light_switch_hld

    #single press
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - light.toggle: nursery_light_switch_light

  - platform: status
    name: "Nursery Light Status"

output:
  - platform: gpio
    pin: GPIO12
    id: nursery_light_switch_relay

light:
  - platform: binary
    name: "Nursery Light"
    id: nursery_light_switch_light
    output: nursery_light_switch_relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
sensor:
  - platform: wifi_signal
    name: "Nursery Light Switch WiFi signal"
    update_interval: 60s

  - platform: uptime
    name: "Nursery Light Switch uptime"

text_sensor:
  - platform: version
    name: "Nursery Light Switch ESPHome version"


```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
