### ISSUE TITLE
Bruh multisensor & Connectivity issues

### ISSUE THREAD

**Issue by soppilif** [esphome/issues#204]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio 0.91.0

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESPHome 1.12.2

**Affected component:**

https://esphome.io/guides/getting_started_hassio.html
https://esphome.io/devices/nodemcu_esp8266.html

**Description of problem:**
I can't connect to my nodemcu. I get this error in the Show Logs:

> INFO Reading configuration...
INFO Starting log output from esp_55ec28.lan using esphome API
INFO Connecting to esp_55ec28.lan:6053 (192.168.1.100)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.1.100: [Errno 111] Connection refused). Re-Trying in 1 seconds

But the nodemcu is connected to the wifi. As you can see it gets the ip from the mDNS.
I can ping it successfully in the terminal.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp_55ec28
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid_name
  password: !secret wifi_pwd
  domain: .lan

# Enable logging
logger:

# Enable Home Assistant API
api:
  #password: !secret wifi_pwd

ota:
  password: !secret wifi_pwd

sensor:
  - platform: dht
    pin: D7
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"

  - platform: adc
    pin: A0
    name: "Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Motion"
    device_class: motion

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
