### ISSUE TITLE
RGBCCT Bulb issue

### ISSUE THREAD

**Issue by cyber-junkie9** [esphome/issues#2040]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

1.17.2 

**Affected component:**

RGBWW

**Description of problem:**
Color does not apply autocratically , have to set white brightness value to 0 to select any color from picker
Color brightness also doesn't work
is there any platform available for RGBCCT bulb ?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: smitch_1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "ssid"
  password: "password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "smitch_1 Fallback Hotspot"
    password: "YA50s8A0ekW5"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
    max_power: 100%
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
    max_power: 100%
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
    max_power: 100%
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO13
    max_power: 100%
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO05
    max_power: 100%

# Define a light entity
light:
  - platform: rgbww
    name: smitch
    id: bulb
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6200 K
    warm_white_color_temperature: 2800 K
    default_transition_length: 3s
    color_interlock: true # avoids simultaneous RGB and W/W

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
