### ISSUE TITLE
HA 2021.5 colormodes issues with color_interlock

### ISSUE THREAD

**Issue by BoukeHaarsma23** [esphome/issues#2046]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

1.18.0b3
**Affected component:**

RGBWW

**Description of problem:**
Using the RGBWW color with color_interlock set to true I get some strange behavior in HA 2021.5.

For example:
HA 2021.5: Bulb currently in white mode --> setting color --> nothing happens --> setting white to 0 --> see color
I can see in the logs of the esp that the white value is not set to 0 when setting the color

In HA 2021.4.5 the white channel is correctly set to 0

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: rgbww
    name: "${name}"
    cold_white: output_white
    warm_white: output_warmwhite
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    default_transition_length: 0.2s
    red: output_red
    green: output_green
    blue: output_blue
    color_interlock: true

```

**Logs (if applicable):**

```
[11:52:09][D][light:265]: 'overhead1' Setting:
[11:52:09][D][light:287]:   Red=100%, Green=0%, Blue=0%
[11:52:09][D][light:290]:   White Value: 100%
[11:52:09][D][light:304]:   Transition Length: 0.2s
```

**Additional information and things you've tried:**
