### ISSUE TITLE
Couldnt Find ID : sun_sun

### ISSUE THREAD

**Issue by alex-shaw** [esphome/issues#2049]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.IO version : core-2021.4.6
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**ESPHome version (latest production, beta, dev branch)**

1.17.2
**Affected component:**

Sun

**Description of problem:**
Previously compiling YAML is now throwing an error about a missing sun_sun Id.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
sun:
  latitude: 3.764856
  longitude: 112.810328
  
  on_sunset:
    then:
    - lambda: |-
    
        auto sunrise = id(sun_sun).sunrise();
        auto sunset = id(sun_sun).sunset();
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
N/A
```

**Additional information and things you've tried:**

**Comment by glmnet** [comment]
it might have happen that `sun_sun` was the generated id before and now it is not anymore.
when you rely on the id to be fixed you should specify it:

```yaml
sun:
  id: sun_sun
  latitude: 3.764856
  longitude: 112.810328
  on_sunset:
    then:
    - lambda: |-
    
        auto sunrise = id(sun_sun).sunrise();
        auto sunset = id(sun_sun).sunset();
```
