### ISSUE TITLE
fastLED + partition isnt updating LEDs with effects

### ISSUE THREAD

**Issue by TheEris** [esphome/issues#2058]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32dev
**ESPHome version (latest production, beta, dev branch)**

1.17.2
**Affected component:**

https://esphome.io/components/light/fastled.html
https://esphome.io/components/light/partition.html

**Description of problem:**
The strobe effect is not updating, light is stuck at a single color. But when different light on the same bus or a different one is updated (change color/brightness with transition), the effect is updating correctly. Looks like the effect is not updating the bus, but it works internally.

In my case, I have two fastLED instances on two pins with 4 LEDs each. Each LED is a separate light entity and each has effects.

Also, the ESP32 (sometimes) hangs and needs to be restarted via power cycle when updating effect on multiple lights at once. But I'm not 100% sure it's because of the lights.  

**Problem-relevant YAML-configuration entries:**
Relative part of the Yaml is at the `LED Stanice` and `LED Globus` coments, around the middle of the code. 
<details>
  <summary>LONG YAML !</summary>

 ```yaml
substitutions:
  devicename: globus
  devicename_full: Globus

###########################################
#                                         #
#                 Core                    #
#                                         #
###########################################

esphome:
  name: $devicename
  platform: ESP32
  board: esp32dev

###########################################
#                                         #
#                 Ethernet                #
#                                         #
###########################################

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  
  manual_ip:
    static_ip: 192.168.0.101
    gateway: 192.168.0.1
    subnet: 255.255.254.0
    
###########################################
#                                         #
#                 Logger                  #
#                                         #
###########################################

logger:

###########################################
#                                         #
#                  API                    #
#                                         #
###########################################

api:
  services:
  - service: dfplayer_next
    then:
      - dfplayer.play_next:
  - service: dfplayer_previous
    then:
      - dfplayer.play_previous:
  - service: dfplayer_play
    variables:
      file: int
    then:
      - dfplayer.play: !lambda 'return file;'
  - service: dfplayer_play_loop
    variables:
      file: int
      loop_: bool
    then:
      - dfplayer.play:
          file: !lambda 'return file;'
          loop: !lambda 'return loop_;'
  - service: dfplayer_play_folder
    variables:
      folder: int
      file: int
    then:
      - dfplayer.play_folder:
          folder: !lambda 'return folder;'
          file: !lambda 'return file;'

  - service: dfplayer_play_loop_folder
    variables:
      folder: int
    then:
      - dfplayer.play_folder:
          folder: !lambda 'return folder;'
          loop: True

  - service: dfplayer_set_device_tf
    then:
      - dfplayer.set_device: TF_CARD

  - service: dfplayer_set_device_usb
    then:
      - dfplayer.set_device: USB

  - service: dfplayer_set_volume
    variables:
      volume: int
    then:
      - dfplayer.set_volume: !lambda 'return volume;'
  - service: dfplayer_set_eq
    variables:
      preset: int
    then:
      - dfplayer.set_eq: !lambda 'return static_cast<dfplayer::EqPreset>(preset);'

  - service: dfplayer_sleep
    then:
      - dfplayer.sleep

  - service: dfplayer_reset
    then:
      - dfplayer.reset

  - service: dfplayer_start
    then:
      - dfplayer.start

  - service: dfplayer_pause
    then:
      - dfplayer.pause

  - service: dfplayer_stop
    then:
      - dfplayer.stop

  - service: dfplayer_random
    then:
      - dfplayer.random

###########################################
#                                         #
#               Web Server                #
#                                         #
###########################################

#web_server:
#  port: 80

###########################################
#                                         #
#           Over The Air updates          #
#                                         #
###########################################

ota:

###########################################
#                                         #
#               Status LED                #
#                Heartbeat                #
#                                         #
###########################################

status_led:
  pin: GPIO15

###########################################
#                                         #
#                  I2C                    #
#                                         #
###########################################

i2c:
  sda: GPIO2
  scl: GPIO4
  #frequency: 800kHz
  scan: True # scan bus for slaves

###########################################
#                                         #
#                  UART                   #
#                                         #
###########################################

uart:
  tx_pin: GPIO012
  baud_rate: 9600

###########################################
#                                         #
#                DFPlayer                 #
#                                         #
###########################################

dfplayer:

###########################################
#                                         #
#                 mcp23017                #
#                                         #
###########################################

mcp23017:
  - id: 'mcp_in' # Inputs
    address: 0x20

  - id: 'mcp_internal' # Internal GPIO
    address: 0x21

###########################################
#                                         #
#                 pca9685                 #
#                                         #
###########################################

#12bit PWM - 4096 steps
pca9685:
  - frequency: 1000 #24-1525Hz
    #address: 0x00
    id: pwm0

# Second pca9685
#  - frequency: 1000
#    address: 0x01
#    id: pwm1

###########################################
#                                         #
#                 ads1115                 #
#                                         #
###########################################

ads1115:
  - address: 0x48

###########################################
#                                         #
#                 Sensors                 #
#                                         #
###########################################

#sensor:

################## Analog ##################

#  - platform: ads1115
#    multiplexer: 'A0_GND'
#    gain: 6.144
#    update_interval: 100ms
#    name: ${devicename_full} Analog 0
#    filters:
#      - delta: 0.1
    
#  - platform: ads1115
#    multiplexer: 'A1_GND'
#    gain: 6.144
#    update_interval: 10s
#    name: ${devicename_full} Analog 1
#    filters:
#      - delta: 0.5
    
#  - platform: ads1115
#    multiplexer: 'A2_GND'
#    gain: 6.144
#    update_interval: 10s
#    name: ${devicename_full} Analog 2
#    filters:
#      - delta: 0.5
    
#  - platform: ads1115
#    multiplexer: 'A3_GND'
#    gain: 6.144
#    update_interval: 10s
#    name: ${devicename_full} Analog 3
#    filters:
#      - delta: 0.5

###########################################
#                                         #
#              Binary Sensors             #
#                                         #
###########################################

binary_sensor:
  - platform: gpio
    name: ${devicename_full} input 1
    pin:
      mcp23xxx: mcp_in
      number: 0
      mode: INPUT_PULLUP
      inverted: False

  - platform: gpio
    name: ${devicename_full} input 2
    pin:
      mcp23xxx: mcp_in
      number: 1
      mode: INPUT_PULLUP
      inverted: False

  - platform: gpio
    name: ${devicename_full} input 3
    pin:
      mcp23xxx: mcp_in
      number: 2
      mode: INPUT_PULLUP
      inverted: False

  - platform: gpio
    name: ${devicename_full} input 4
    pin:
      mcp23xxx: mcp_in
      number: 3
      mode: INPUT_PULLUP
      inverted: False

  - platform: gpio
    name: ${devicename_full} input 5
    pin:
      mcp23xxx: mcp_in
      number: 4
      mode: INPUT_PULLUP
      inverted: False

  - platform: gpio
    name: ${devicename_full} input 6
    pin:
      mcp23xxx: mcp_in
      number: 5
      mode: INPUT_PULLUP
      inverted: False

  - platform: gpio
    name: ${devicename_full} input 7
    pin:
      mcp23xxx: mcp_in
      number: 6
      mode: INPUT_PULLUP
      inverted: False

  - platform: gpio
    name: ${devicename_full} input 8
    pin:
      mcp23xxx: mcp_in
      number: 7
      mode: INPUT_PULLUP
      inverted: False
      
  - platform: gpio
    name: ${devicename_full} input 9
    pin:
      mcp23xxx: mcp_in
      number: 8
      mode: INPUT_PULLUP
      inverted: False
    filters:
      - delayed_on: 500ms
  
  - platform: gpio
    name: ${devicename_full} input 10
    pin:
      mcp23xxx: mcp_in
      number: 9
      mode: INPUT_PULLUP
      inverted: False
    filters:
      - delayed_on: 500ms
      
  - platform: gpio
    name: ${devicename_full} input 11
    pin:
      mcp23xxx: mcp_in
      number: 10
      mode: INPUT_PULLUP
      inverted: False
    filters:
      - delayed_on: 500ms
      
  - platform: gpio
    name: ${devicename_full} input 12
    pin:
      mcp23xxx: mcp_in
      number: 11
      mode: INPUT_PULLUP
      inverted: False
    filters:
      - delayed_on: 500ms
      
  - platform: gpio
    name: ${devicename_full} input 13
    pin:
      mcp23xxx: mcp_in
      number: 12
      mode: INPUT_PULLUP
      inverted: False
      
  - platform: gpio
    name: ${devicename_full} input 14
    pin:
      mcp23xxx: mcp_in
      number: 13
      mode: INPUT_PULLUP
      inverted: False
      
  - platform: gpio
    name: ${devicename_full} input 15
    pin:
      mcp23xxx: mcp_in
      number: 14
      mode: INPUT_PULLUP
      inverted: False
      
  - platform: gpio
    name: ${devicename_full} input 16
    pin:
      mcp23xxx: mcp_in
      number: 15
      mode: INPUT_PULLUP
      inverted: False


################## DFPlayer ##################

  - platform: gpio
    name: ${devicename_full} DFPlayer Playing 1
    pin:
      mcp23xxx: mcp_internal
      number: 13
      mode: INPUT_PULLUP
      inverted: True

  - platform: gpio
    name: ${devicename_full} DFPlayer Playing 2
    pin:
      mcp23xxx: mcp_internal
      number: 14
      mode: INPUT_PULLUP
      inverted: True

################## Fault Detection ##################

  - platform: gpio
    name: ${devicename_full} Motor Driver Fault
    pin:
      mcp23xxx: mcp_internal
      number: 9
      mode: INPUT_PULLUP
      inverted: True


###########################################
#                                         #
#           PWM Outputs as Lights         #
#                                         #
###########################################

light:
  - platform: monochromatic
    name: ${devicename_full} PWM Output 1
    output: pwm0_0
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 2
    output: pwm0_1
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 3 
    output: pwm0_2
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 4
    output: pwm0_3
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 5
    output: pwm0_4
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 6
    output: pwm0_5
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 7
    output: pwm0_6
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 8
    output: pwm0_7
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 9
    output: pwm0_8
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 10
    output: pwm0_9
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 11
    output: pwm0_10
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 12
    output: pwm0_11
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 13
    output: pwm0_12
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 14
    output: pwm0_13
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 15
    output: pwm0_14
    default_transition_length: 0s
    
  - platform: monochromatic
    name: ${devicename_full} PWM Output 16
    output: pwm0_15
    default_transition_length: 0s
    effects:
      - strobe:
          name: Blik
          colors:
            - state: True
              duration: 666ms
            - state: False
              duration: 666ms

###########################################
#                                         #
#                LED Stanice              #
#                                         #
###########################################

  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO14
    num_leds: 4
    rgb_order: RGB
    internal: true
    id: stanice_led

  - platform: partition
    name: "LED Stanice 1"
    segments:
      - id: stanice_led
        from: 0
        to: 0
    effects:
      - strobe:
          name: OK
          colors:
            - state: True
              red: 0%
              blue: 0%
              green: 100%
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: ERROR
          colors:
            - state: True
              red: 100%
              blue: 0%
              green: 0%
              duration: 500ms
            - state: False
              duration: 500ms
        
  - platform: partition
    name: "LED Stanice 2"
    segments:
      - id: stanice_led
        from: 1
        to: 1
    effects:
      - strobe:
          name: OK
          colors:
            - state: True
              red: 0%
              blue: 0%
              green: 100%
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: ERROR
          colors:
            - state: True
              red: 100%
              blue: 0%
              green: 0%
              duration: 500ms
            - state: False
              duration: 500ms
        
  - platform: partition
    name: "LED Stanice 3"
    segments:
      - id: stanice_led
        from: 2
        to: 2
    effects:
      - strobe:
          name: OK
          colors:
            - state: True
              red: 0%
              blue: 0%
              green: 100%
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: ERROR
          colors:
            - state: True
              red: 100%
              blue: 0%
              green: 0%
              duration: 500ms
            - state: False
              duration: 500ms
              
  - platform: partition
    name: "LED Stanice 4"
    segments:
      - id: stanice_led
        from: 3
        to: 3
    effects:
      - strobe:
          name: OK
          colors:
            - state: True
              red: 0%
              blue: 0%
              green: 100%
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: ERROR
          colors:
            - state: True
              red: 100%
              blue: 0%
              green: 0%
              duration: 500ms
            - state: False
              duration: 500ms
              
###########################################
#                                         #
#                LED Globus               #
#                                         #
###########################################

  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO17
    num_leds: 4
    rgb_order: GRB
    internal: true
    id: globus_led
    effects:
      - strobe:
          name: OK
          colors:
            - state: True
              red: 0%
              blue: 0%
              green: 100%
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: ERROR
          colors:
            - state: True
              red: 100%
              blue: 0%
              green: 0%
              duration: 500ms
            - state: False
              duration: 500ms
              
  - platform: partition
    name: "LED Globus 1"
    segments:
      - id: globus_led
        from: 0
        to: 0
    effects:
      - strobe:
          name: OK
          colors:
            - state: True
              red: 0%
              blue: 0%
              green: 100%
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: ERROR
          colors:
            - state: True
              red: 100%
              blue: 0%
              green: 0%
              duration: 500ms
            - state: False
              duration: 500ms    
              
  - platform: partition
    name: "LED Globus 2"
    segments:
      - id: globus_led
        from: 1
        to: 1
    effects:
      - strobe:
          name: OK
          colors:
            - state: True
              red: 0%
              blue: 0%
              green: 100%
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: ERROR
          colors:
            - state: True
              red: 100%
              blue: 0%
              green: 0%
              duration: 500ms
            - state: False
              duration: 500ms
        
  - platform: partition
    name: "LED Globus 3"
    segments:
      - id: globus_led
        from: 2
        to: 2
    effects:
      - strobe:
          name: OK
          colors:
            - state: True
              red: 0%
              blue: 0%
              green: 100%
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: ERROR
          colors:
            - state: True
              red: 100%
              blue: 0%
              green: 0%
              duration: 500ms
            - state: False
              duration: 500ms
              
  - platform: partition
    name: "LED Globus 4"
    segments:
      - id: globus_led
        from: 3
        to: 3
    effects:
      - strobe:
          name: OK
          colors:
            - state: True
              red: 0%
              blue: 0%
              green: 100%
              duration: 500ms
            - state: False
              duration: 500ms
      - strobe:
          name: ERROR
          colors:
            - state: True
              red: 100%
              blue: 0%
              green: 0%
              duration: 500ms
            - state: False
              duration: 500ms
              
###########################################
#                                         #
#                Switchs                  #
#                                         #
###########################################

switch:
############## Half-Bridge IN (DIR) #############
##############          1           #############

  - platform: gpio
    name: ${devicename_full} HB IN 01
    pin:
      mcp23xxx: mcp_internal
      number: 0
      mode: OUTPUT
      inverted: False
      
  - platform: gpio
    name: ${devicename_full} HB IN 02
    pin:
      mcp23xxx: mcp_internal
      number: 1
      mode: OUTPUT
      inverted: False
      
  - platform: gpio
    name: ${devicename_full} HB IN 03
    pin:
      mcp23xxx: mcp_internal
      number: 2
      mode: OUTPUT
      inverted: False
      
  - platform: gpio
    name: ${devicename_full} HB IN 04
    pin:
      mcp23xxx: mcp_internal
      number: 3
      mode: OUTPUT
      inverted: False
  
############## Half-Bridge IN (DIR) #############
##############          2           #############

  - platform: gpio
    name: ${devicename_full} HB IN 05
    pin:
      mcp23xxx: mcp_internal
      number: 4
      mode: OUTPUT
      inverted: False
      
  - platform: gpio
    name: ${devicename_full} HB IN 06
    pin:
      mcp23xxx: mcp_internal
      number: 5
      mode: OUTPUT
      inverted: False
      
  - platform: gpio
    name: ${devicename_full} HB IN 07
    pin:
      mcp23xxx: mcp_internal
      number: 6
      mode: OUTPUT
      inverted: False
      
  - platform: gpio
    name: ${devicename_full} HB IN 08
    pin:
      mcp23xxx: mcp_internal
      number: 7
      mode: OUTPUT
      inverted: False

############## Outputs #############

  - platform: gpio
    name: ${devicename_full} Output 18
    pin:
      mcp23xxx: mcp_internal
      number: 10
      mode: OUTPUT
      inverted: False

  - platform: gpio
    name: ${devicename_full} Output 19
    pin:
      mcp23xxx: mcp_internal
      number: 11
      mode: OUTPUT
      inverted: False
  
  - platform: gpio
    name: ${devicename_full} Output 17
    pin:
      mcp23xxx: mcp_internal
      number: 12
      mode: OUTPUT
      inverted: False

############## DFplayer #############

  - platform: gpio
    name: ${devicename_full} DFplayer Switch
    pin:
      mcp23xxx: mcp_internal
      number: 15
      mode: OUTPUT
      inverted: False
      
############## Reset Driver #############

  - platform: gpio
    name: ${devicename_full} Driver Reset
    pin:
      mcp23xxx: mcp_internal
      number: 8
      mode: OUTPUT
      inverted: True

###########################################
#                                         #
#           outputs, Internal use         #
#                                         #
###########################################

output:
  # pca9685 outputs, intelnal definition
  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_0'
    channel: 0

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_1'
    channel: 1

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_2'
    channel: 2

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_3'
    channel: 3

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_4'
    channel: 4

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_5'
    channel: 5

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_6'
    channel: 6

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_7'
    channel: 7

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_8'
    channel: 8

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_9'
    channel: 9

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_10'
    channel: 10

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_11'
    channel: 11

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_12'
    channel: 12

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_13'
    channel: 13

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_14'
    channel: 14

  - platform: pca9685
    pca9685_id: pwm0
    id: 'pwm0_15'
    channel: 15
 ```
</details>

**Logs (if applicable):**

```
~

```

**Additional information and things you've tried:**
