### ISSUE TITLE
NodeMCU tries to connect to set SSID but fails and restarts Wifi adapter in loop

### ISSUE THREAD

**Issue by mr-sneezy** [esphome/issues#206]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HA 0.91.0 and hassos 2.11 on RPi3

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU V3
**Affected component:**

WiFi connectivity

**Description of problem:**
Setting up a NodeMCU as a default esphome device for testing and finding it can't or won't connect to my home WiFi network. 
[19:52:27][I][wifi:167]: WiFi Connecting to 'Not_my_SSID'...
[19:52:33][W][wifi:399]: Error while connecting to network.
[19:52:33][W][wifi:429]: Restarting WiFi adapter...
[19:52:33][I][wifi:167]: WiFi Connecting to 'Not_my_SSID'...
[19:52:39][W][wifi:399]: Error while connecting to network.
[19:52:39][W][wifi:429]: Restarting WiFi adapter...
[19:52:45][D][wifi:271]: Starting scan...

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test1
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "Not_my_SSID"
  password: "Not_my_password"

  manual_ip:
# Set this to the IP of the ESP
    static_ip: 192.168.0.22
# Set this to the IP address of the router. Often ends with .1
    gateway: 191.168.0.1
# The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
Two things:
1/
 Tried a static IP and matching it in the router. No change.

2/
 As a test to try see if the new module was faulty, I took this NodeMCU module and loaded the current release Tasmota sonoff-basic binary via the same esphomeflasher (handy to know that esphhomeflasher will work for other binaries as I run a bunch of Tasmota FW module on my network).
The binary flashed fine same as the esphome one, but in the case of the Tasmota binary it DOES connect to my WiFi and hang on reliably. 
I got into the AP it created as normal and changed the WiFi parameters and restarted it, then got back into it right way via it's new IP on the Wifi network. 
So there is nothing wrong with this NodeMCU module (and the esphome flasher)...
