### ISSUE TITLE
Esp32 single core: After sending command device reboots and does not respond.

### ISSUE THREAD

**Issue by dekuort** [esphome/issues#2063]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

OS: Windows 10
Python 3.9.4
Pio version 5.1.1
Pip: 21.1.1
hassio: false

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

https://esphome.io/components/remote_receiver.html

**Description of problem:**
When i sending command (over mqtt for example), device restarts and getting hot

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: xiaomiir_esphome
  upper_devicename: Xiaomi IR Remote
  room: living room

esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1
  platformio_options:
    extra_scripts: pre:../pre_extra_script.py
    platform: espressif32@1.11.0
    platform_packages: |-4
      
          framework-arduinoespressif32 @ https://github.com/pauln/arduino-esp32.git#solo-no-mac-crc/1.0.4
  
wifi:
  ssid: "-"
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiaomi Ir Fallback Hotspot"
    password: "6864333242"

captive_portal:

# Enable logging
logger:
    level: VERY_VERBOSE

# Enable Home Assistant API
#api:
#  password: "api_password_here"
#  reboot_timeout : 0s

ota:
  password: "ota_password_here"
  
web_server:
  port: 80
  

status_led:
  pin:
    number: GPIO18  #Orange LED - flashes for status events
    inverted: True
    
output:
  - platform: gpio
    pin: GPIO23     #Blue LED - Powered on always
    id: PowerLED
    
sensor:
  - platform: wifi_signal
    name: ${upper_devicename} ${room} WiFi Signal
    
  - platform: uptime
    name: ${upper_devicename} ${room} Uptime

switch:
  - platform: restart
    name: ${upper_devicename} ${room} Restart
    
climate:
  - platform: fujitsu_general      # adjust to match your AC unit!
    id: fujitsu_ac
    name: fujitsu_ac
    receiver_id: rcvr    

mqtt:
  broker: "192.168.1.120"
  port: ""
  username: "home"
  password: ""
  discovery: true
  
remote_receiver:
  id: rcvr
  pin: 
    number: GPIO27
    inverted: False
  dump: all

remote_transmitter:
  pin:
    number: GPIO26
    inverted: false   
  carrier_duty_percent: 50%
  id: internal


```

**Logs (if applicable):**

https://pastebin.com/MC9pyiMn

```
[0;38m[VV][remote_receiver.esp32:093]: 373 A: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:098]: 373 B: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:093]: 374 A: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:098]: 374 B: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:093]: 375 A: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:098]: 375 B: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:093]: 376 A: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:098]: 376 B: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:093]: 377 A: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:098]: 377 B: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:093]: 378 A: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:098]: 378 B: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:093]: 379 A: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:098]: 379 B: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:093]: 380 A: ON 32510us (32510 ticks)[0m
[0;38m[VV][remote_receiver.esp32:098]:E (53371) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (53371) task_wdt:  - IDLE0 (CPU 0)
E (53371) task_wdt: Tasks currently running:
E (53371) task_wdt: CPU 0: wifi
E (53371) task_wdt: Aborting.
abort() was called at PC 0x400f4b47 on core 0

Backtrace: 0x4008c7a0:0x3ffbe370 0x4008c9b1:0x3ffbe390 0x400f4b47:0x3ffbe3b0 0x400845ea:0x3ffbe3d0 0x4014834b:0x3ffc8e60 0x4015364c:0x3ffc8e80 0x4012779a:0x3ffc8ea0 0x4011d46d:0x3ffc8ec0 0x4011e145:0x3ffc9000 0x40167799:0x3ffc9020 0x4008f8c6:0x3ffc9070 0x4008963d:0x3ffc90b0

Rebooting...

```

I used this source: https://github.com/AdamKGoddard/XiaomiIR_ESPHome
