### ISSUE TITLE
WaveShare e-paper 4.20in Rev2.1 display not working

### ISSUE THREAD

**Issue by sbeff** [esphome/issues#2070]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266, LOLIN D1 MINI

**ESPHome version (latest production, beta, dev branch)**
1.18

**Affected component:**
WaveShare e-paper 4.20in Rev2.1 display (I wrote to Waveshare support, and they told me that the Rev2.1 refers to the driver board, and not to the display itself)

**Description of problem:**
The display is not working with ESPHome, I think this might be related to #1032. I tried many pin configurations without success.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: waveshare_display
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "removed"
  password: "removed"

logger:

api:

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

display:
  - platform: waveshare_epaper
    cs_pin: GPIO15
    dc_pin: GPIO16
    busy_pin: GPIO2
    reset_pin: GPIO12
    rotation: 0
    update_interval: 60s
    model: 4.20in
    lambda: |-
      it.rectangle(140,0,140,150);
```

**Logs (if applicable):**

```
[11:52:19][E][waveshare_epaper:119]: Timeout while displaying image!
```

**Additional information and things you've tried:**
I used Waveshare's official code for Raspberry Pi and it worked normally.

**Comment by sbeff** [comment]
I managed to get it to work by using this configuration with my LOLIN D1 mini:
```
spi:
  clk_pin: D5
  mosi_pin: D7

display:
  - platform: waveshare_epaper
    cs_pin: D8
    dc_pin: D6
    update_interval: 00s
    busy_pin: D0
    reset_pin: D2
    model: 4.20in
    lambda: |-
      it.rectangle(140,0,140,150);
```

What could have been the problem?
