### ISSUE TITLE
Sample_rate for BME680 integration doesn't work

### ISSUE THREAD

**Issue by azrael783** [esphome/issues#2073]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker on a Pi4

**ESP (ESP32/ESP8266, Board/Sonoff):**

wemos D1 mini

**ESPHome version (latest production, beta, dev branch)**

v1.18.0

**Affected component:**

https://esphome.io/components/sensor/bme680_bsec.html

**Description of problem:**
Adding the `sample_rate` to the yaml file gives me the error: "[sample_rate] is an invalid option for [0]. Please check indentation". I can't upload the code. Marking the line as a comment it let me upload the code.
 
**Problem-relevant YAML-configuration entries:**
```yaml
# copied from the documentation 
bme680_bsec:
    # i2c address
    # -----------
    # Common values are:
    # - 0x76
    # - 0x77
    # Default: 0x76
    address: 0x77

    # Temperature offset
    # ------------------
    # Useful if device is in enclosure and reads too high
    # Default: 0
    temperature_offset: 0

    # IAQ calculation mode
    # --------------------
    # Available options:
    # - static (for fixed position devices)
    # - mobile (for on person or other moveable devices)
    # Default: static
    iaq_mode: static

    # Sample rate
    # -----------
    # Available options:
    # - lp (low power - samples every 3 seconds)
    # - ulp (ultra low power - samples every 5 minutes)
    # Default: lp
    sample_rate: lp

    # Interval at which to save BSEC state
    # ------------------------------------
    # Default: 6h
    state_save_interval: 4h

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I used this component before - as a custom component - but didn't use the `sample_rate`.
