### ISSUE TITLE
Intermittently on boot NTP time is not requested

### ISSUE THREAD

**Issue by theOzzieRat** [esphome/issues#2075]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

D1 Mini

ESPHome 1.19-dev

**Affected component:**

NTP

Occasionally on boot ESPHome fails to request the time from the NTP server. I have captured the network traffic from the device and it never sends an NTP request. I have attached the pcaps of both it working correctly and when it fails. This occurs randomly on 5 different devices. I suspect it is a timing thing, maybe it tries to send the NTP request before the wifi is fully available? I tried capturing verbose logs but that actually made the problem go away (and there was no extra messages about 'time' at the verbose level anyway).

[ESPHome NTP Problem PCAPs.zip](https://github.com/esphome/issues/files/6543117/ESPHome.NTP.Problem.PCAPs.zip)

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  name: enviro1
  friendly: Enviro 1
  ipaddr: 10.0.10.23
  version: "1.14"
  
esphome:
  name: $name
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: -100
    then:
      - script.execute: startup
                
globals:
  - id: sleep_enable
    type: bool
    initial_value: 'true'
  - id: boot_time
    type: int
  - id: sleep_reason
    type: int

script:
  - id: startup
    then:
      - delay: 5s
      - script.execute: dosleep
  - id: dosleep
    then:
      - logger.log: 
          format: "dosleep: sleep_enbable %d"
          args: [ id(sleep_enable) ]
      - if:
          condition:
            lambda: |-
              int offset = id(ntp_time).now().timestamp - (((id(ntp_time).now().timestamp) / 300) * 300);
              return ((offset > 10) && (offset <270)) && id(sleep_enable);
          then:
            - logger.log: 
                format: "Sleep %d"
                args: [ (((id(ntp_time).now().timestamp + 300) / 300) * 300) - 15 - id(ntp_time).now().timestamp ]
            - mqtt.publish_json:
                topic: ${name}/sleep
                retain: true
                payload: |-
                  root["version"] = "${version}";
                  root["time"] = id(ntp_time).now().strftime("%H:%M:%S");
                  root["duration"] = (((((id(ntp_time).now().timestamp + 300) / 300) * 300) - 15 - id(ntp_time).now().timestamp)*1000)-1;
                  root["reason"] = id(sleep_reason) ? "OTA disabled" : "Boot timeout";
            - delay: 1s
            - deep_sleep.enter:
                id: deep_sleep_1
                sleep_duration: !lambda "return (((((id(ntp_time).now().timestamp + 300) / 300) * 300) - 15 - id(ntp_time).now().timestamp)*1000);"

i2c:
  sda: 4
  scl: 5
  frequency: 50000.0
  scan: true
  
sensor:
  - platform: sht3xd
    temperature:
      name: "Temperature"
      device_class: "temperature"
      accuracy_decimals: 1
      internal: true
      id: temperature
    humidity:
      name: "Humidity"
      device_class: "humidity"
      accuracy_decimals: 0
      internal: true
      id: humidity
    address: 0x44
    update_interval: never
    id: sht3
  - platform: uptime
    id: uptime_sensor
    update_interval: never

deep_sleep:
  id: deep_sleep_1

wifi:
  ssid: "ssid"
  password: "password"
  fast_connect: true
  enable_mdns: false
  manual_ip:
    static_ip: $ipaddr
    gateway: 10.0.10.1
    subnet: 255.255.255.0
    dns1: 10.0.10.1

  ap:
    ssid: "${friendly} Fallback"
    password: "password"
    
time:
  - platform: sntp
    id: ntp_time
    servers: 10.0.10.1
    timezone: AEST-10AEDT-11,M10.1.0/2,M4.1.0/3
    on_time:
      - seconds: 0
        minutes: /5
        then:
          - if:
              condition:
                lambda: 'return id(sleep_enable);'
              then:
                - component.update: sht3
                - delay: 1s
                - mqtt.publish_json:
                    topic: ${name}/sensor/state
                    retain: true
                    payload: |-
                      root["time"] = id(ntp_time).utcnow().timestamp;
                      root["temperature"] = id(temperature).state;
                      root["humidity"] = id(humidity).state;
      - seconds: 10
        minutes: /5
        then:
          - if:
              condition:
                lambda: 'return id(sleep_enable);'
              then:
                - logger.log: 
                    format: "Time %02d:%02d:%02d"
                    args: [ id(ntp_time).now().hour, id(ntp_time).now().minute, id(ntp_time).now().second ]
                - mqtt.publish_json:
                    topic: ${name}/sleep
                    retain: true
                    payload: |-
                      root["version"] = "${version}";
                      root["time"] = id(ntp_time).now().strftime("%H:%M:%S");
                      root["duration"] = 275000 + 15000;
                      root["reason"] = "Task done";
                - delay: 1s
                - deep_sleep.enter:
                    id: deep_sleep_1
                    sleep_duration: !lambda "return (275000 + 20000);"
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"
        - logger.log: Version $version
        - component.update: uptime_sensor
        - globals.set:
            id: boot_time
            value: !lambda "return (id(ntp_time).now().timestamp - (uint32)round(id(uptime_sensor).raw_state));"
        - logger.log:
            format: "Start time %u"
            args: [ id(boot_time) ]
        - logger.log: 
            format: "Start time %02d:%02d:%02d"
            args: [ ESPTime::from_epoch_local(id(boot_time)).hour, ESPTime::from_epoch_local(id(boot_time)).minute, ESPTime::from_epoch_local(id(boot_time)).second ]
        - logger.log: 
            format: "Boot time %02d:%02d:%02d"
            args: [ id(ntp_time).now().hour, id(ntp_time).now().minute, id(ntp_time).now().second ]
        - mqtt.publish_json:
            topic: ${name}/boot
            retain: true
            payload: |-
              root["version"] = "${version}";
              root["start"] = ESPTime::from_epoch_local(id(boot_time)).strftime("%H:%M:%S");
              root["ready"] = id(ntp_time).now().strftime("%H:%M:%S");

mqtt:
  broker: 10.0.10.10
  username: username
  password: password
  log_topic: 
    topic: ${name}/debug
    level: none
  on_message:
    - topic: ${name}/ota_mode
      then:
        - if:
            condition:
              lambda: 'return x == "ON";'
            then:
              - logger.log: 
                  format: "Disable sleep %02d:%02d:%02d"
                  args: [ id(ntp_time).now().hour, id(ntp_time).now().minute, id(ntp_time).now().second ]
              - deep_sleep.prevent: deep_sleep_1
              - globals.set:
                  id: sleep_enable
                  value: 'false'
        - if:
            condition:
              lambda: 'return x == "OFF";'
            then:
              - logger.log: 
                  format: "Enable sleep %02d:%02d:%02d"
                  args: [ id(ntp_time).now().hour, id(ntp_time).now().minute, id(ntp_time).now().second ]
              - mqtt.publish:
                  topic: ${name}/ota_mode
                  retain: true
                  payload: 
              - globals.set:
                  id: sleep_enable
                  value: 'true'
              - globals.set:
                  id: sleep_reason
                  value: '1'
              - script.execute: dosleep

captive_portal:

logger:
  level: DEBUG
  
ota:
  password: "password"
```

**Logs (if applicable):**

```
WORKING LOG
-----------------
[I][logger:170]: Log initialized
[C][ota:366]: There have been 0 suspected unsuccessful boot attempts.
[I][app:029]: Running through setup()...
[C][sht3xd:019]: Setting up SHT3xD...
[C][wifi:033]: Setting up WiFi...
[I][wifi:194]: WiFi Connecting to 'ssid'...
[I][wifi:457]: WiFi Connected!
[C][wifi:303]:   SSID: 'ssid'
[C][wifi:304]:   IP Address: 10.0.10.23
[C][wifi:306]:   BSSID: removed
[C][wifi:307]:   Hostname: 'enviro1'
[C][wifi:311]:   Signal strength: -54 dB ▂▄▆█
[C][wifi:315]:   Channel: 6
[C][wifi:316]:   Subnet: 255.255.255.0
[C][wifi:317]:   Gateway: 10.0.10.1
[C][wifi:318]:   DNS1: 10.0.10.1
[C][wifi:319]:   DNS2: (IP unset)
[D][wifi:466]: Disabling AP...
[C][ota:029]: Over-The-Air Updates:
[C][ota:030]:   Address: 10.0.10.23:8266
[C][ota:032]:   Using Password.
[C][mqtt:025]: Setting up MQTT...
[I][mqtt:170]: Connecting to MQTT...
[I][mqtt:210]: MQTT Connected!
[C][sntp:017]: Setting up SNTP...
[C][deep_sleep:013]: Setting up Deep Sleep...
[I][app:059]: setup() finished successfully!
[I][app:105]: ESPHome version 1.19.0-dev compiled on May 25 2021, 22:31:41
[C][wifi:443]: WiFi:
[C][wifi:303]:   SSID: 'ssid'
[C][wifi:304]:   IP Address: 10.0.10.23
[C][wifi:306]:   BSSID: 06:31:92:BC:FE:62
[C][wifi:307]:   Hostname: 'enviro1'
[C][wifi:311]:   Signal strength: -57 dB ▂▄▆█
[C][wifi:315]:   Channel: 6
[C][wifi:316]:   Subnet: 255.255.255.0
[C][wifi:317]:   Gateway: 10.0.10.1
[C][wifi:318]:   DNS1: 10.0.10.1
[C][wifi:319]:   DNS2: (IP unset)
[C][i2c:028]: I2C Bus:
[C][i2c:029]:   SDA Pin: GPIO4
[C][i2c:030]:   SCL Pin: GPIO5
[C][i2c:031]:   Frequency: 50000 Hz
[I][i2c:033]: Scanning i2c bus for active devices...
[I][i2c:040]: Found i2c device at address 0x44
[D][sntp:056]: Synchronized time: Wed May 26 10:04:54 2021
[D][main:153]: Synchronized system clock
[D][main:156]: Version 1.14
[D][sensor:099]: 'uptime_sensor': Sending state 4.98700 s with 0 decimals of accuracy
[D][main:156]: Start time 1621987489
[D][main:159]: Start time 10:04:49
[D][main:162]: Boot time 10:04:54
[C][uptime.sensor:030]: Uptime Sensor 'uptime_sensor'
[C][uptime.sensor:030]:   Unit of Measurement: 's'
[C][uptime.sensor:030]:   Accuracy Decimals: 0
[C][uptime.sensor:030]:   Icon: 'mdi:timer-outline'
[C][logger:189]: Logger:
[C][logger:190]:   Level: DEBUG
[C][logger:191]:   Log Baud Rate: 115200
[C][logger:192]:   Hardware UART: UART0
[C][sht3xd:034]: SHT3xD:
[C][sht3xd:035]:   Address: 0x44
[C][sht3xd:039]:   Update Interval: 4294967.5s
[C][sht3xd:041]:   Temperature 'Temperature'
[C][sht3xd:041]:     Device Class: 'temperature'
[C][sht3xd:041]:     Unit of Measurement: '°C'
[C][sht3xd:041]:     Accuracy Decimals: 1
[C][sht3xd:042]:   Humidity 'Humidity'
[C][sht3xd:042]:     Device Class: 'humidity'
[C][sht3xd:042]:     Unit of Measurement: '%'
[C][sht3xd:042]:     Accuracy Decimals: 0
[C][captive_portal:169]: Captive Portal:
[C][ota:029]: Over-The-Air Updates:
[C][ota:030]:   Address: 10.0.10.23:8266
[C][ota:032]:   Using Password.
[C][mqtt:059]: MQTT:
[C][mqtt:061]:   Server Address: 10.0.10.10:1883 (10.0.10.10)
[C][mqtt:062]:   Username: 'username'
[C][mqtt:063]:   Client ID: 'enviro1-8caab5592090'
[C][mqtt:065]:   Discovery prefix: 'homeassistant'
[C][mqtt:066]:   Discovery retain: YES
[C][mqtt:068]:   Topic Prefix: 'enviro1'
[C][mqtt:070]:   Log Topic: 'enviro1/debug'
[C][mqtt:073]:   Availability: 'enviro1/status'
[C][sntp:039]: SNTP Time:
[C][sntp:040]:   Server 1: '10.0.10.1'
[C][sntp:041]:   Server 2: ''
[C][sntp:042]:   Server 3: ''
[C][sntp:043]:   Timezone: 'AEST-10AEDT-11,M10.1.0/2,M4.1.0/3'
[C][mqtt:579]: MQTT Message Trigger:
[C][mqtt:580]:   Topic: 'enviro1/ota_mode'
[C][mqtt:581]:   QoS: 0
[C][mqtt.sensor:024]: MQTT Sensor 'uptime_sensor':
[C][mqtt.sensor:028]:   State Topic: 'enviro1/sensor/uptime_sensor/state'
[C][mqtt.sensor:024]: MQTT Sensor 'Temperature':
[C][mqtt.sensor:028]:   State Topic: 'enviro1/sensor/temperature/state'
[C][mqtt.sensor:024]: MQTT Sensor 'Humidity':
[C][mqtt.sensor:028]:   State Topic: 'enviro1/sensor/humidity/state'
[C][deep_sleep:020]: Setting up Deep Sleep...
[D][main:561]: dosleep: sleep_enbable 1
[D][sht3xd:065]: Got temperature=22.42°C humidity=43.99%
[D][sensor:099]: 'Temperature': Sending state 22.41512 °C with 1 decimals of accuracy
[D][sensor:099]: 'Humidity': Sending state 43.99329 % with 0 decimals of accuracy
[D][main:058]: Time 10:05:10
[I][deep_sleep:067]: Beginning Deep Sleep
[W][wifi_esp8266:444]: Event: Disconnected ssid='ssid' bssid=06:31:92:BC:FE:62 reason='Association Leave'
```
```
FAILED LOG
-------------
[I][logger:170]: Log initialized
[C][ota:366]: There have been 0 suspected unsuccessful boot attempts.
[I][app:029]: Running through setup()...
[C][sht3xd:019]: Setting up SHT3xD...
[C][wifi:033]: Setting up WiFi...
[I][wifi:194]: WiFi Connecting to 'ssid'...
[I][wifi:457]: WiFi Connected!
[C][wifi:303]:   SSID: 'ssid'
[C][wifi:304]:   IP Address: 10.0.10.23
[C][wifi:306]:   BSSID: 06:31:92:BC:FE:62
[C][wifi:307]:   Hostname: 'enviro1'
[C][wifi:311]:   Signal strength: -53 dB ▂▄▆█
[C][wifi:315]:   Channel: 6
[C][wifi:316]:   Subnet: 255.255.255.0
[C][wifi:317]:   Gateway: 10.0.10.1
[C][wifi:318]:   DNS1: 10.0.10.1
[C][wifi:319]:   DNS2: (IP unset)
[D][wifi:466]: Disabling AP...
[C][ota:029]: Over-The-Air Updates:
[C][ota:030]:   Address: 10.0.10.23:8266
[C][ota:032]:   Using Password.
[C][mqtt:025]: Setting up MQTT...
[I][mqtt:170]: Connecting to MQTT...
[I][mqtt:210]: MQTT Connected!
[C][sntp:017]: Setting up SNTP...
[C][deep_sleep:013]: Setting up Deep Sleep...
[I][app:059]: setup() finished successfully!
[I][app:105]: ESPHome version 1.19.0-dev compiled on May 25 2021, 22:31:41
[C][wifi:443]: WiFi:
[C][wifi:303]:   SSID: 'myssid'
[C][wifi:304]:   IP Address: 10.0.10.23
[C][wifi:306]:   BSSID: removed
[C][wifi:307]:   Hostname: 'enviro1'
[C][wifi:311]:   Signal strength: -56 dB ▂▄▆█
[C][wifi:315]:   Channel: 6
[C][wifi:316]:   Subnet: 255.255.255.0
[C][wifi:317]:   Gateway: 10.0.10.1
[C][wifi:318]:   DNS1: 10.0.10.1
[C][wifi:319]:   DNS2: (IP unset)
[C][i2c:028]: I2C Bus:
[C][i2c:029]:   SDA Pin: GPIO4
[C][i2c:030]:   SCL Pin: GPIO5
[C][i2c:031]:   Frequency: 50000 Hz
[I][i2c:033]: Scanning i2c bus for active devices...
[I][i2c:040]: Found i2c device at address 0x44
[C][uptime.sensor:030]: Uptime Sensor 'uptime_sensor'
[C][uptime.sensor:030]:   Unit of Measurement: 's'
[C][uptime.sensor:030]:   Accuracy Decimals: 0
[C][uptime.sensor:030]:   Icon: 'mdi:timer-outline'
[C][logger:189]: Logger:
[C][logger:190]:   Level: DEBUG
[C][logger:191]:   Log Baud Rate: 115200
[C][logger:192]:   Hardware UART: UART0
[C][sht3xd:034]: SHT3xD:
[C][sht3xd:035]:   Address: 0x44
[C][sht3xd:039]:   Update Interval: 4294967.5s
[C][sht3xd:041]:   Temperature 'Temperature'
[C][sht3xd:041]:     Device Class: 'temperature'
[C][sht3xd:041]:     Unit of Measurement: '°C'
[C][sht3xd:041]:     Accuracy Decimals: 1
[C][sht3xd:042]:   Humidity 'Humidity'
[C][sht3xd:042]:     Device Class: 'humidity'
[C][sht3xd:042]:     Unit of Measurement: '%'
[C][sht3xd:042]:     Accuracy Decimals: 0
[C][captive_portal:169]: Captive Portal:
[C][ota:029]: Over-The-Air Updates:
[C][ota:030]:   Address: 10.0.10.23:8266
[C][ota:032]:   Using Password.
[C][mqtt:059]: MQTT:
[C][mqtt:061]:   Server Address: 10.0.10.10:1883 (10.0.10.10)
[C][mqtt:062]:   Username: 'username'
[C][mqtt:063]:   Client ID: 'enviro1-8caab5592090'
[C][mqtt:065]:   Discovery prefix: 'homeassistant'
[C][mqtt:066]:   Discovery retain: YES
[C][mqtt:068]:   Topic Prefix: 'enviro1'
[C][mqtt:070]:   Log Topic: 'enviro1/debug'
[C][mqtt:073]:   Availability: 'enviro1/status'
[C][sntp:039]: SNTP Time:
[C][sntp:040]:   Server 1: '10.0.10.1'
[C][sntp:041]:   Server 2: ''
[C][sntp:042]:   Server 3: ''
[C][sntp:043]:   Timezone: 'AEST-10AEDT-11,M10.1.0/2,M4.1.0/3'
[C][mqtt:579]: MQTT Message Trigger:
[C][mqtt:580]:   Topic: 'enviro1/ota_mode'
[C][mqtt:581]:   QoS: 0
[C][mqtt.sensor:024]: MQTT Sensor 'uptime_sensor':
[C][mqtt.sensor:028]:   State Topic: 'enviro1/sensor/uptime_sensor/state'
[C][mqtt.sensor:024]: MQTT Sensor 'Temperature':
[C][mqtt.sensor:028]:   State Topic: 'enviro1/sensor/temperature/state'
[C][mqtt.sensor:024]: MQTT Sensor 'Humidity':
[C][mqtt.sensor:028]:   State Topic: 'enviro1/sensor/humidity/state'
[C][deep_sleep:020]: Setting up Deep Sleep...
[D][main:561]: dosleep: sleep_enbable 1
[D][main:198]: Sleep 271
[I][deep_sleep:067]: Beginning Deep Sleep
[W][wifi_esp8266:444]: Event: Disconnected ssid='ssid' bssid=06:31:92:BC:FE:62 reason='Association Leave'

```
**Additional information and things you've tried:**
