### ISSUE TITLE
ESPHome device always "unavailable" after Home Assistant server restart

### ISSUE THREAD

**Issue by GazTheGeek** [esphome/issues#2076]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Homeassistant core-2021.5.5 / Raspberry Pi

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff TH16 Board: esp01_1m

**ESPHome version (latest production, beta, dev branch)**

ESPHome v1.18.0
**Affected component:**

https://esphome.io/devices/sonoff.html

**Description of problem:**

After every Home Assistant server reboot the entities for this device come back "unavailable". To fix the problem I have to delete the integration and re add it. Then it work fine until the next reboot.

I have other Sonoff TH16s installed and they do not have the same issue.

I also have a Wemos D1 Mini that sometime has the same issue.

In the ESPHome UI The Sonoff shows green and the logs will some the component working fine. The issue is with Home assistant showing the entity as "unavailable"

Wifi signal is strong this unit is located close to the router.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

esphome:
  name: bh_sonoff03
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: xxx
  password: xxx

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BH Sonoff 03"
    password: "xxxx"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    pin: GPIO12
    name: "Stairs Light"
    id: stairs_light_relay

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14 #Yellow wire on jack (Tip of Pin)
      inverted: True
    id: stairs_lights_top_sw
    name: "Stairs Light Top Switch"
    on_state:
      then:
        - switch.toggle: stairs_light_relay
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

Nothing in the Homeassistant logs for this component.

```

**Additional information and things you've tried:**

Reloading the integration for the device does not fix it.
re-uploading the bin does not fix it.

UPDATE: May 27, 2021. Disable and reenabling the integration also fixes it. The issue seems to be on the HA side not the ESPHome side. (If that's a thing)
