### ISSUE TITLE
Error "contains duplicate key "switch", when using substitution yaml file

### ISSUE THREAD

**Issue by rradar** [esphome/issues#208]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip 
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp8266
**Affected component:**

yaml parser?

**Description of problem:**

It's not possible for me to add a `switch:` component to my younameit.yaml while I'm injecting
`<<: !include common.yaml)` which also includes a `switch:` component already.

This is only true for the switch component and not for sensor and others. For the other components it even works when I'm using the component in my main (younameit.yaml) and in the common.yaml

**Problem-relevant YAML-configuration entries:**

yonameit.yaml switch: part
```yaml
switch:
  - platform: output
    name: "${upper_devicename} LED"
    output: led
    id: switch_led
```

common.yaml switch: part
```yaml
switch:
  - platform: restart
    name: "${upper_devicename} Restart"
    id: restart
```

**Traceback (if applicable):**

```
ERROR Error while reading config: YAML file younameit.yaml contains duplicate key "switch". Check lines 21 and 301.
```

**Additional information and things you've tried:**

If I comment out (# switch: ...) the switch component in younameit.yaml compiling works.

When I comment out (# switch:  ...) in common.yaml it does not compile and starts complaining about a duplicate sensor component :tired_face: 

```
ERROR Error while reading config: YAML file oled.yaml contains duplicate key "sensor". Check lines 16 and 301.
```
