### ISSUE TITLE
GPS component does not compile if used as in documentation

### ISSUE THREAD

**Issue by jbrepogmailcom** [esphome/issues#2082]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 Devkit + NEO GPS

**ESPHome version (latest production, beta, dev branch)**

esphome --version does not work

**Affected component:**

GPS

**Description of problem:**
If GPS component is declared as in documentation:
```yaml
uart:
  rx_pin: GPIO16
  baud_rate: 9600

gps:
  latitude:
    name: "Latitude"
  longitude:
    name: "Longitude"
  altitude:
    name: "Altitude"
```

then it does not compile and returns error. GPS itself works fine, lat and lon can be seen in log. The error is:
```
    [latitude] is an invalid option for [0]. Please check the indentation.
    latitude:  [source Documents/blinds-brain-gps.yaml:109]
      name: Latitude
    
    [longitude] is an invalid option for [0]. Please check the indentation.
    longitude:  [source Documents/blinds-brain-gps.yaml:111]
      name: Longitude
    
    [altitude] is an invalid option for [0]. Please check the indentation.
    altitude:  [source Documents/blinds-brain-gps.yaml:113]
      name: Altitude
```

**please advise how to properly declare GPS component and how to use it as location sensor.**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
