### ISSUE TITLE
ESP doesn't wakeup from a 15 min. deepsleep. It works fine the first weeks, but then it never wakesup

### ISSUE THREAD

**Issue by RHAD1969** [esphome/issues#2096]
The relevant portion of the configuration:

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32-WROVER-E

**ESPHome version (latest production, beta, dev branch)**

Home Assistant OS 5.13
core-2021.6.2
supervisor-2021.05.4

**Affected component:**

https://esphome.io/components/deep_sleep.html?highlight=sleep

**Description of problem:**
I have an ESP32-WROVER-E that runs a Dallas temperature sensor and measures its own battery voltage using resistor divider and analog input.

The setup works fine for 3-4 weeks, but suddenly the ESP does not wakeup from deepsleep every 15 min as it should. 

After poweron reset the ESP is 'waiting for download':

``` 
[14:55:53]rst:0x1 (PO\xffets Jul 29 2019\xa0ets Jul 29 2019 12:21:46
[14:55:53]
[14:55:53]rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
[14:55:53]waiting for download
```

Uploading the configuration again makes the ESP functioning again, until a few weeks have passed.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32_buitentemperatuur
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "***"
  password: "***"


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Buitentemperatuur"
    password: "***"

captive_portal:

# Enable logging
debug:

logger:
  level: very_verbose
# Enable Home Assistant API, but not vor MQQT
# api:


mqtt:
  broker: 10.10.2.1
  username: ***
  password: ***
  topic_prefix: buiten/weer
  birth_message:
  will_message:
  on_message:
    - topic: esp32_buitentemperatuur/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: esp32_buitentemperatuur/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1
               
deep_sleep:
  run_duration: 300s
  sleep_duration: 900s
  id: deep_sleep_1
  wakeup_pin: 35
  wakeup_pin_mode: KEEP_AWAKE
 
ota:

dallas:
 - pin: GPIO14
   update_interval: 2 sec

sensor:
  - platform: dallas
    name: "Buiten thermometer"
    unit_of_measurement: "°C"
    index: 0
    
  - platform: adc
    pin: GPIO32
    name: "Buiten thermometer batterij"
    unit_of_measurement: "V"
    update_interval: 10 sec
    attenuation: 11db
    filters:
    - multiply: 11.02

```

**Logs (if applicable):**

```
``` 
[14:55:53]rst:0x1 (PO\xffets Jul 29 2019\xa0ets Jul 29 2019 12:21:46
[14:55:53]
[14:55:53]rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
[14:55:53]waiting for download
```
I cannot find the debug log, since I updated to the latest version. The last sensor update is at 6am and HA restarted at 9.40 am, so I don't think the HA update is the issue
```

**Additional information and things you've tried:**

The wakeup pin also does not work anymore.  

I've connected the ESP32 using serial communication, but no data is transferred ( I waited 3 times the sleep duration) .

Supplied voltage is OK (3.3V). 

I've replaced the ESP32, but issue persists
