### ISSUE TITLE
Fan speed not restored from preference on boot

### ISSUE THREAD

**Issue by wifwucite** [esphome/issues#2097]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip (MacOs)

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**

latest production

**Affected component:**

[speed fan](https://esphome.io/components/fan/speed.html)

**Description of problem:**
When I set a fan speed > 1 and reboot the device the speed is set always set to 1.

**Problem-relevant YAML-configuration entries:**
```yaml
output:
  - platform: ledc
    pin: 19
    id: fan_speed

fan:
  - platform: speed
    name: "sz_fan"
    id: sz_fan
    output: fan_speed
```

**Logs (if applicable):**

```
N/A
```

**Additional information and things you've tried:**
The problem is the setup priority. FanState has HARDWARE-1, SpeedFan has DATA which is lower, it should be HARDWARE. So when the settings are retrieved in FanState::setup the traits have not been set yet by the corresponding SpeedFan component. So any speed value is simply clipped to 1.
