### ISSUE TITLE
catch the state of the PULLUP

### ISSUE THREAD

**Issue by freenetwork** [esphome/issues#210]
Tell me how to catch the state of the PULLUP on the optocoupler 4N35? on_press?
When a call arrives at the ring, I catch an optocoupler 4N35 for 1000ms on D5 input port 

```
esphome:
  name: domofon
  platform: ESP8266
  board: nodemcuv2

...

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT
      inverted: True
    name: "сall"
    on_press:
      min_length: 1000ms
      then:
        - script.execute: call
```
