### ISSUE TITLE
toggling gpio switch relay on Sonoff S20 several times via mqtt or internal script causes firmware to brownout or crash without recovering

### ISSUE THREAD

**Issue by btittelbach** [esphome/issues#2104]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

- mosquito mqtt
- homeassistant, Hass.io on RPi

**ESP (ESP32/ESP8266, Board/Sonoff):**

- Sonoff S20
- ESP8266

**ESPHome version (latest production, beta, dev branch)**

ESPHome Version: 1.18.0

installed and updated via pip3 on ubuntu 21.04

**Affected component:**

https://esphome.io/guides/automations.html#script

**Description of problem:**

Observed behaivour
1. S20 is connected to wifi. status_led is dark, indicating no problems
2. Button on S20 is pressed, starting script
3. S20 Relay turns off
4. Wifi connection drops (was bad to begin with, -90dBm at worst times). Can be observed as device greys out on Homeassistant / sends last will on MQTT
5. 10s should elapse and S20 relay should turn back on. Instead the relay stays off.
6. When initiated by a button press several minutes or hours later, the relay turns back on as if the script continued on (or maybe was restarted?). Eventually device goes back online on HA

It feels like a buffer that sends messages to Homeassistant api or mqtt fills up and blocks further execution of the script.

The problem seemingly went away, when `api:` was commented out and only mqtt was used.

**Problem-relevant YAML-configuration entries:**
```yaml
#===============================================================================
substitutions:
  device_name: chellomodem
  device_friendly_name: "ChelloModemS20"

#===============================================================================  


esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285
  on_boot: 
  - switch.turn_on: relaypower

wifi:
  ssid: !secret iotwifi_name
  password: !secret iotwifi_pass
  reboot_timeout: 5h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome Fallback Hotspot"
    password: !secret fallbackwifi_pass

captive_portal:

# Enable logging
logger:

## commenting out api section seems to alleviate problem
api:
  password: !secret api_password
  reboot_timeout: 5000s

ota:
  password: !secret api_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_friendly_name} Button"
    on_press:
      - script.execute: powercycle
  - platform: status
    name: "${device_friendly_name} Status"

switch:
  - platform: restart 
    name: "Reboot ${device_friendly_name}"
  - platform: gpio
    pin: GPIO12
    id: relaypower
    icon: mdi:desktop-classic
    restore_mode: RESTORE_DEFAULT_ON
    name: "${device_friendly_name} Power"
  - platform: template
    name: "Powercycle ${device_friendly_name}"
    id: powercycle_chellomodem
    optimistic: true
    lambda: return false; # switch is always reported as off
    turn_on_action:
      - script.execute: powercycle

script:
  - id: powercycle
    mode: single
    then:
      - logger.log: "Powercycling appliance ..."
      - switch.turn_off: relaypower
      - delay: 10s
      - switch.turn_on: relaypower

sensor:
  - platform: wifi_signal
    name: "${device_friendly_name} Switch WiFi Signal"
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
    icon: mdi:wifi

mqtt:
    broker: 192.168.1.2

status_led:
  pin:
    number: GPIO13
    inverted: yes

```

**Logs (if applicable):**

```
unfortunately don't have logs from time when wifi disconnects

```

**Additional information and things you've tried:**

**Comment by btittelbach** [comment]
I've changed the configuration and added a second WIFI with better reception.

The new behaviour suggest that the problem might have been somewhere else entirely and not related to bad WIFI reception.

Steps taken:
1. script with id `powercycle` triggered via mqtt

Observed behavior:
1. script executes on Sonoff device
2. Sonoff immediately reboots afterwards

## Configuration
```
#===============================================================================
substitutions:
  device_name: chellomodem
  device_friendly_name: "ChelloModemS20"

#===============================================================================  


esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285
  on_boot: 
  - switch.turn_on: relaypower

wifi:
  reboot_timeout: 5h
  networks:
    - ssid: !secret karoikanewifi_name
      password: !secret karoikanewifi_pass
    - ssid: !secret iotwifi_name
      password: !secret iotwifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome Fallback Hotspot"
    password: !secret fallbackwifi_pass

captive_portal:

# Enable logging
logger:

ota:
  password: !secret api_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_friendly_name} Button"
    on_press:
      - script.execute: powercycle
  - platform: status
    name: "${device_friendly_name} Status"

switch:
  - platform: restart 
    name: "Reboot ${device_friendly_name}"
  - platform: gpio
    pin: GPIO12
    id: relaypower
    icon: mdi:desktop-classic
    restore_mode: RESTORE_DEFAULT_ON
    name: "${device_friendly_name} Power"
  - platform: template
    name: "Powercycle ${device_friendly_name}"
    id: powercycle_chellomodem
    optimistic: true
    lambda: return false; # switch is always reported as off
    turn_on_action:
      - script.execute: powercycle

script:
  - id: powercycle
    mode: single
    then:
      - logger.log: "Powercycling appliance ..."
      - switch.turn_off: relaypower
      - delay: 10s
      - switch.turn_on: relaypower

sensor:
  - platform: wifi_signal
    name: "${device_friendly_name} Switch WiFi Signal"
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
    icon: mdi:wifi

mqtt:
  broker: 192.168.1.2
  reboot_timeout: 0s

status_led:
  pin:
    number: GPIO13
    inverted: yes

```


### Logs

```
chellomodem/debug [D][switch:021]: 'Powercycle ChelloModemS20' Turning ON.                                                                                                                               
chellomodem/debug [D][main:371]: Powercycling appliance ...                                                                                                                                              
chellomodem/debug [D][switch:025]: 'ChelloModemS20 Power' Turning OFF.                                                                                                                                   
chellomodem/debug [D][switch:045]: 'ChelloModemS20 Power': Sending state OFF                                                                                                                             
chellomodem/debug [D][switch:045]: 'Powercycle ChelloModemS20': Sending state ON                                                                                                                         
chellomodem/debug [D][switch:045]: 'Powercycle ChelloModemS20': Sending state OFF                                                                                                                        
chellomodem/switch/chellomodems20_power/state OFF                                                                                                                                                        
chellomodem/switch/powercycle_chellomodems20/state OFF                                                                                                                                                   
chellomodem/debug [D][switch:021]: 'ChelloModemS20 Power' Turning ON.                                                                                                                                    
chellomodem/debug [D][switch:045]: 'ChelloModemS20 Power': Sending state ON                                                                                                                              
chellomodem/switch/chellomodems20_power/state ON                                                    
chellomodem/debug [I][mqtt:210]: MQTT Connected!                                                    
homeassistant/binary_sensor/chellomodem/chellomodems20_status/config {"device_class":"connectivity","payload_on":"online","payload_off":"offline","name":"ChelloModemS20 Status","state_topic":"chellomod
em/status","availability_topic":"chellomodem/status","unique_id":"ESPbinary_sensorchellomodems20_status","device":{"identifiers":"807d3a68628d","name":"chellomodem","sw_version":"esphome v1.18.0 Jun 12
 2021, 01:18:58","model":"PLATFORMIO_ESP8285","manufacturer":"espressif"}}                          
homeassistant/switch/chellomodem/reboot_chellomodems20/config {"icon":"mdi:restart","name":"Reboot ChelloModemS20","state_topic":"chellomodem/switch/reboot_chellomodems20/state","command_topic":"chello
modem/switch/reboot_chellomodems20/command","availability_topic":"chellomodem/status","unique_id":"ESPswitchreboot_chellomodems20","device":{"identifiers":"807d3a68628d","name":"chellomodem","sw_versio
n":"esphome v1.18.0 Jun 12 2021, 01:18:58","model":"PLATFORMIO_ESP8285","manufacturer":"espressif"}}
chellomodem/switch/reboot_chellomodems20/state OFF                                                  
homeassistant/switch/chellomodem/chellomodems20_power/config {"icon":"mdi:desktop-classic","name":"ChelloModemS20 Power","state_topic":"chellomodem/switch/chellomodems20_power/state","command_topic":"c
hellomodem/switch/chellomodems20_power/command","availability_topic":"chellomodem/status","unique_id":"ESPswitchchellomodems20_power","device":{"identifiers":"807d3a68628d","name":"chellomodem","sw_ver
sion":"esphome v1.18.0 Jun 12 2021, 01:18:58","model":"PLATFORMIO_ESP8285","manufacturer":"espressif"}}                                                                                                  
chellomodem/switch/chellomodems20_power/state ON                                                    
homeassistant/switch/chellomodem/powercycle_chellomodems20/config {"name":"Powercycle ChelloModemS20","state_topic":"chellomodem/switch/powercycle_chellomodems20/state","command_topic":"chellomodem/swi
tch/powercycle_chellomodems20/command","availability_topic":"chellomodem/status","unique_id":"ESPswitchpowercycle_chellomodems20","device":{"identifiers":"807d3a68628d","name":"chellomodem","sw_version
":"esphome v1.18.0 Jun 12 2021, 01:18:58","model":"PLATFORMIO_ESP8285","manufacturer":"espressif"}} 
chellomodem/switch/powercycle_chellomodems20/state OFF
homeassistant/sensor/chellomodem/chellomodems20_switch_wifi_signal/config {"unit_of_measurement":"dBm","icon":"mdi:wifi","name":"ChelloModemS20 Switch WiFi Signal","state_topic":"chellomodem/sensor/che
llomodems20_switch_wifi_signal/state","availability_topic":"chellomodem/status","unique_id":"807d3a68628d-wifisignal","device":{"identifiers":"807d3a68628d","name":"chellomodem","sw_version":"esphome v
1.18.0 Jun 12 2021, 01:18:58","model":"PLATFORMIO_ESP8285","manufacturer":"espressif"}}             
homeassistant/binary_sensor/chellomodem/chellomodems20_button/config {"name":"ChelloModemS20 Button","state_topic":"chellomodem/binary_sensor/chellomodems20_button/state","availability_topic":"chellomo
dem/status","unique_id":"ESPbinary_sensorchellomodems20_button","device":{"identifiers":"807d3a68628d","name":"chellomodem","sw_version":"esphome v1.18.0 Jun 12 2021, 01:18:58","model":"PLATFORMIO_ESP8
285","manufacturer":"espressif"}}                                                                   
chellomodem/binary_sensor/chellomodems20_button/state OFF     
chellomodem/debug [I][app:059]: setup() finished successfully!   
chellomodem/debug [D][sensor:099]: 'ChelloModemS20 Switch WiFi Signal': Sending state -72.00000 dBm with 0 decimals of accuracy
chellomodem/sensor/chellomodems20_switch_wifi_signal/state -72                                
chellomodem/debug [D][binary_sensor:036]: 'ChelloModemS20 Status': Sending state ON
chellomodem/status online                                                                           
chellomodem/debug [I][app:105]: ESPHome version 1.18.0 compiled on Jun 12 2021, 01:18:58
chellomodem/debug [C][status_led:019]: Status LED:                                                  
chellomodem/debug [C][status_led:020]:   Pin: GPIO13 (Mode: OUTPUT, INVERTED)             
chellomodem/debug [C][wifi:443]: WiFi:                                                              

```

**Comment by btittelbach** [comment]
and apparently, after behaving like this on five consecutive occasions,
the problem is now no longer reproducable

**Comment by btittelbach** [comment]
The real issue of course being: Why is the relay staying off after reboot, even if the device does not connect to WIFI?

**Comment by btittelbach** [comment]
- I've removed 'captive_portal:' to save resources.
- I've changed the script and added a delay at the end of the script

```
script:
  - id: powercycle
    mode: single
    then:
      - logger.log: "Powercycling appliance ..."
      - switch.turn_off: relaypower
      - delay: 18s
      - switch.turn_on: relaypower
      - delay: 10s
```

sure enough, after a few executions of the script, the device 
1. turns switch off
2. waits 18s
3. turns switch on
4. waits 10s
5. goes offline, switch relay off, keeps relay off and never returns online

this seems more and more like bug in the script execution code. maybe a memory leak?

**Comment by btittelbach** [comment]
toggling the relay several times in quick succession (~15 times, 1s spacing),
causes the same firmware crash. So it's not just the script.

**Comment by btittelbach** [comment]
assuming that esphome uses some kind of watchdog, it is curious that the device never recovers.

This would suggest it is indeed a brownout or EMI issue and may not be the firmware's fault.

**Comment by btittelbach** [comment]
Worked around the issue by having the script reboot the Sonoff S20.

```
switch:
  - platform: restart 
    name: "Reboot ${device_friendly_name}"
    id: rebootme

.....

script:
  - id: powercycle
    mode: single
    then:
      - logger.log: "Powercycling appliance ..."
      - switch.turn_off: relaypower
      - delay: 18s
      - switch.turn_on: rebootme
#      - switch.turn_on: relaypower
#      - delay: 10s

```
