### ISSUE TITLE
pulse_meter 'total' not actual total

### ISSUE THREAD

**Issue by rklomp** [esphome/issues#2107]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

  platform: ESP8266
  board: d1_mini

**ESPHome version (latest production, beta, dev branch)**

ESPHome version 1.18.0

**Affected component:**

https://esphome.io/components/sensor/pulse_meter.html

**Description of problem:**
The pulse meter total sensor is not showing actual total of pulses.
A comment in the code says: "If we've exceeded our timeout interval without receiving any pulses, assume 0 pulses/min until we get at least two valid pulses."

While this is useful for the pulse per second metering, in the case of totals its causing count issues.

Lets say we have the following sequence
5 pulses - timeout - 5 pulses - timeout - 5 pulses

I would expect a total of 15 at this point, but since in each burst of pulses the first one is discarded, the total counted by pulse_meter will be 12.

https://github.com/esphome/esphome/blob/dev/esphome/components/pulse_meter/pulse_meter_sensor.cpp#L71-L83

Looking at the code the if-statements on both lines 72 and 76 cause a pulse to be discarded. So two pulse are discarded instead of one. Just removing the if-statement of line 72 will fix both the counting and will provide a metering output at the second pulse instead of the third pulse. See https://github.com/esphome/esphome/pull/1875

**Problem-relevant YAML-configuration entries:**
```yaml
- platform: pulse_meter
  pin:
    number: D4
    inverted: True
  id: sensor_pulse_meter
  name: "${long_devicename} Current Usage"
  icon: "mdi:water-pump"
  unit_of_measurement: "L/min"
  timeout: 60s
  internal_filter: 10ms
  accuracy_decimals: 1
  total:
    id: sensor_pulse_meter_total
    name: "${long_devicename} Total Consumption"
    icon: "mdi:cube-outline"
    unit_of_measurement: "m3"
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
```

**Logs (if applicable):**

**Additional information and things you've tried:**
