### ISSUE TITLE
catch the state of the PULLUP

### ISSUE THREAD

**Issue by freenetwork** [esphome/issues#211]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASS.IO

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**
Tell me how to catch the state of the PULLUP on the optocoupler 4N35? on_press?
When a call arrives at the ring, I catch an optocoupler 4N35 for 1000ms on D5 input port

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: domofon
  platform: ESP8266
  board: nodemcuv2

...

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT
      inverted: True
    name: "сall"
    on_press:
      min_length: 1000ms
      then:
        - script.execute: call

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
