### ISSUE TITLE
Connection error with  RC522 Rfid reader

### ISSUE THREAD

**Issue by raidnet-ms** [esphome/issues#2111]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io with latest version.
**ESP (ESP32/ESP8266, Board/Sonoff):**

Node MCU
**ESPHome version (latest production, beta, dev branch)**

v 1.18 stable
**Affected component:**

rc522

**Description of problem:**
I get an error in loop with the YAML provided in the documentation. You can see the log below.

**Problem-relevant YAML-configuration entries:**
```yaml

spi:
  clk_pin: D5
  miso_pin: D6
  mosi_pin: D7

rc522_spi: # or rc522_i2c
  cs_pin: D8
  update_interval: 1s

  on_tag:
    then:
    - logger.log: "Tag letto."
    - text_sensor.template.publish:
        id: rfid_tag
        state: "Tag letto"
    - display.page.show: nfc
    - homeassistant.tag_scanned: -|!lambda 'return x;'

```

**Logs (if applicable):**

```
[13:42:18][W][rc522:392]: Communication with the MFRC522 might be down, reset in -211
[13:42:18][I][rc522_spi:013]: SPI Setup
[13:42:18][I][rc522:288]: Soft reset...
[13:42:18][I][rc522:296]: Device online.

```

**Additional information and things you've tried:**

Tried with different pin. The harware is working properly with arduino.
