### ISSUE TITLE
Grow fingerprint blinks irregularly

### ISSUE THREAD

**Issue by mr2c12** [esphome/issues#2117]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Pip in virtualenv.
esphome in ./lib/python3.9/site-packages (1.18.0)

**ESP (ESP32/ESP8266, Board/Sonoff):**

platform: ESP32
board is "ESP-WROOM-32D", currently using "board: lolin_d32" in yaml.

**ESPHome version (latest production, beta, dev branch)**

1.18.0

**Affected component:**

Model R307
doc:
https://esphome.io/components/fingerprint_grow.html
the board is not the adafruit version, just a cheap clone: https://www.sunrom.com/p/finger-print-sensor-r307-new-r305
This component has been implemented as per this feature request: https://github.com/esphome/feature-requests/issues/572

**Description of problem:**
The fingerprint reader works just fine.
Anyway, it keeps "blinking" quite random. The device is supposed to blink when reading a fingerprint, but actually blinks quite often and irregularly (not a predictable pattern).
It blinks even when completely alone.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: myboard
  upper_devicename: MyBoard

esphome:
  name: ${devicename}
  platform: ESP32
  board: lolin_d32

wifi:
  ssid: <correct-value>
  password: <correct-value>
  fast_connect: on
  manual_ip:
    static_ip: 192.168.1.47
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${upper_devicename} Fallback Hotspot"
    password: <correct-value>

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: <correct-value>
  services:
  - service: enroll
    variables:
      finger_id: int
      num_scans: int
    then:
      - fingerprint_grow.enroll:
          finger_id: !lambda 'return finger_id;'
          num_scans: !lambda 'return num_scans;'
  - service: cancel_enroll
    then:
      - fingerprint_grow.cancel_enroll:
  - service: delete
    variables:
      finger_id: int
    then:
      - fingerprint_grow.delete:
          finger_id: !lambda 'return finger_id;'
  - service: delete_all
    then:
      - fingerprint_grow.delete_all:
  - service: rtttl_play
    variables:
      song_str: string
    then:
      - rtttl.play:
          rtttl: !lambda 'return song_str;'
  - service: rtttl_play_scale_up
    then:
      - rtttl.play: 'scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b'
  - service: rtttl_play_siren
    then:
      - rtttl.play: 'siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e'
  - service: rtttl_play_two_shorts
    then:
      - rtttl.play: 'two short:d=4,o=5,b=100:16e6,16e6'
  - service: rtttl_play_two_ok_disarm
    then:
      - rtttl.play: 'two ok disarm:d=4,o=5,b=100:4g5,32p,4g5'
  - service: rtttl_play_one_ok_arm
    then:
      - rtttl.play: 'one ok arm:d=4,o=5,b=100:3e6'
  - service: rtttl_play_scan_failed
    then:
      - script.execute: ${devicename}_rtttl_play_scan_failed
      # - rtttl.play: 'scan failed:d=8,o=5,b=100:d,e,d'
  - service: rtttl_stop
    then:
      - rtttl.stop

ota:

binary_sensor:
  - platform: fingerprint_grow
    id: ${devicename}_fingerprint_enrolling
    name: "${upper_devicename} Fingerprint Enrolling"
  - platform: status
    name: "${upper_devicename} status"
    id: "${devicename}_status"
  - platform: homeassistant
    name: "${upper_devicename} Alarm armed"
    id: "${devicename}_alarm_armed"
    entity_id: binary_sensor.state_is_alarm_armed
    on_state:
      then:
        - script.execute: ${devicename}_update_led_lights
  - platform: homeassistant
    name: "${upper_devicename} Alarm not armed"
    id: "${devicename}_alarm_not_armed"
    entity_id: binary_sensor.state_is_alarm_not_armed
    on_state:
      then:
        - script.execute: ${devicename}_update_led_lights
  - platform: homeassistant
    name: "${upper_devicename} Garden presence"
    id: "${devicename}_garden_presence"
    entity_id: binary_sensor.aqara_motion_garden_action
    on_state:
      then:
        - script.execute: ${devicename}_update_led_lights
  - platform: homeassistant
    name: "${upper_devicename} Kitchen door"
    id: "${devicename}_kitchen_door"
    entity_id: binary_sensor.aqara_door_kitchen
    on_state:
      then:
        - script.execute: ${devicename}_update_led_lights
        

fingerprint_grow:
  sensing_pin: GPIO12
  on_finger_scan_matched:
    - script.execute: ${devicename}_rtttl_play_scan_ok
    - script.execute: ${devicename}_set_temp_presence
    - homeassistant.event:
        event: esphome.${devicename}_finger_scan_matched
        data:
          finger_id: !lambda 'return finger_id;'
          confidence: !lambda 'return confidence;'
    - text_sensor.template.publish:
        id: ${devicename}_fingerprint_state
        state: "Authorized finger"
  on_finger_scan_unmatched:
    - script.execute: ${devicename}_rtttl_play_scan_failed
    - script.execute: ${devicename}_set_temp_presence
    - homeassistant.event:
        event: esphome.${devicename}_finger_scan_unmatched
    - text_sensor.template.publish:
        id: ${devicename}_fingerprint_state
        state: "Unauthorized finger"
  on_enrollment_scan:
    - homeassistant.event:
        event: esphome.${devicename}_enrollment_scan
        data:
          finger_id: !lambda 'return finger_id;'
          scan_num: !lambda 'return scan_num;'
    - text_sensor.template.publish:
        id: ${devicename}_fingerprint_state
        state: "Finger scanned"
  on_enrollment_done:
    - homeassistant.event:
        event: esphome.${devicename}_enrollment_done
        data:
          finger_id: !lambda 'return finger_id;'
    - text_sensor.template.publish:
        id: ${devicename}_fingerprint_state
        state: "Enrolled fingerprint"
  on_enrollment_failed:
    - homeassistant.event:
        event: esphome.${devicename}_enrollment_failed
        data:
          finger_id: !lambda 'return finger_id;'
    - text_sensor.template.publish:
        id: ${devicename}_fingerprint_state
        state: "Failed to enroll fingerprint"
  
globals:
  - id: glb_temp_presence
    type: bool
    restore_value: no
    initial_value: 'false'

light:
  - platform: binary
    id: ${devicename}_greenled
    name: "${upper_devicename} Green Led"
    output: ${devicename}_output_pin14_greenled
  - platform: binary
    id: ${devicename}_redled
    name: "${upper_devicename} Red Led"
    output: ${devicename}_output_pin27_redled

output:
  - platform: ledc
    pin: GPIO21
    id: rtttl_out
  - id: ${devicename}_output_pin14_greenled
    platform: gpio
    pin: GPIO14
  - id: ${devicename}_output_pin27_redled
    platform: gpio
    pin: GPIO27

rtttl:
  output: rtttl_out

script:
  - id: ${devicename}_rtttl_play_scan_failed
    then:
      - rtttl.play: 'scan failed:d=8,o=5,b=100:d,e,d'
  - id: ${devicename}_rtttl_play_scan_ok
    then:
      - rtttl.play: 'scan ok:d=4,o=5,b=100:64e6,64p,16e6'
  - id: ${devicename}_update_led_lights
    then:
      - script.execute: ${devicename}_update_red_led
      - script.execute: ${devicename}_update_green_led
  - id: ${devicename}_update_red_led
    then:
      if:
        condition:
          lambda: 'return (id(glb_temp_presence) || (id(${devicename}_garden_presence).state && !id(${devicename}_kitchen_door).state)) && id(${devicename}_alarm_armed).state;'
        then:
          - logger.log: "${devicename}_update_red_led - ON"
          - light.turn_on: ${devicename}_redled
        else:
          - logger.log: "${devicename}_update_red_led - OFF"
          - light.turn_off: ${devicename}_redled
  - id: ${devicename}_update_green_led
    then:
      if:
        condition:
          lambda: 'return (id(glb_temp_presence) || (id(${devicename}_garden_presence).state && !id(${devicename}_kitchen_door).state)) && id(${devicename}_alarm_not_armed).state;'
        then:
          - logger.log: "${devicename}_update_green_led - ON"
          - light.turn_on: ${devicename}_greenled
        else:
          - logger.log: "${devicename}_update_green_led - OFF"
          - light.turn_off: ${devicename}_greenled
  - id: ${devicename}_set_temp_presence
    mode: restart
    then:
      - globals.set:
          id: glb_temp_presence
          value: 'true'
      - script.execute: ${devicename}_update_led_lights
      - delay: 5s
      - globals.set:
          id: glb_temp_presence
          value: 'false'
      - script.execute: ${devicename}_update_led_lights

          

sensor:
  - platform: fingerprint_grow
    fingerprint_count:
      name: "${upper_devicename} Fingerprint Count"
    last_finger_id:
      name: "${upper_devicename} Fingerprint Last Finger ID"
    last_confidence:
      name: "${upper_devicename} Fingerprint Last Confidence"
    status:
      name: "${upper_devicename} Fingerprint Status"
    capacity:
      name: "${upper_devicename} Fingerprint Capacity"
    security_level:
      name: "${upper_devicename} Fingerprint Security Level"

switch:
  - platform: restart
    name: restart

text_sensor:
  - platform: template
    id: ${devicename}_fingerprint_state
    name: "Fingerprint State"

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 57600
```

**Logs (if applicable):**

```
07:55:59][D][fingerprint_grow:122]: Getting image 1
[07:55:59][D][fingerprint_grow:132]: No finger
[07:56:00][D][fingerprint_grow:091]: Scan and match
[07:56:00][D][fingerprint_grow:122]: Getting image 1
[07:56:01][D][fingerprint_grow:132]: No finger
[07:56:03][D][fingerprint_grow:091]: Scan and match
[07:56:03][D][fingerprint_grow:122]: Getting image 1
[07:56:03][D][fingerprint_grow:132]: No finger
[07:56:04][D][fingerprint_grow:091]: Scan and match
[07:56:04][D][fingerprint_grow:122]: Getting image 1
[07:56:05][D][fingerprint_grow:132]: No finger
[07:56:06][D][fingerprint_grow:091]: Scan and match
[07:56:06][D][fingerprint_grow:122]: Getting image 1
[07:56:06][D][fingerprint_grow:132]: No finger
[07:56:07][D][fingerprint_grow:091]: Scan and match
[07:56:07][D][fingerprint_grow:122]: Getting image 1
[07:56:08][D][fingerprint_grow:132]: No finger
[07:56:08][D][fingerprint_grow:091]: Scan and match
[07:56:08][D][fingerprint_grow:122]: Getting image 1
[07:56:08][D][fingerprint_grow:132]: No finger
[07:56:10][D][fingerprint_grow:091]: Scan and match
[07:56:10][D][fingerprint_grow:122]: Getting image 1
[07:56:10][D][fingerprint_grow:132]: No finger
[07:56:12][D][fingerprint_grow:091]: Scan and match
[07:56:12][D][fingerprint_grow:122]: Getting image 1
[07:56:12][D][fingerprint_grow:132]: No finger
[07:56:13][D][fingerprint_grow:091]: Scan and match
[07:56:13][D][fingerprint_grow:122]: Getting image 1
[07:56:13][D][fingerprint_grow:132]: No finger
[07:56:13][D][fingerprint_grow:091]: Scan and match
[07:56:13][D][fingerprint_grow:122]: Getting image 1
[07:56:14][D][fingerprint_grow:132]: No finger
[07:56:14][D][fingerprint_grow:091]: Scan and match
[07:56:14][D][fingerprint_grow:122]: Getting image 1
[07:56:14][D][fingerprint_grow:132]: No finger
[07:56:15][D][fingerprint_grow:091]: Scan and match
[07:56:15][D][fingerprint_grow:122]: Getting ima
```

**Additional information and things you've tried:**

Relevant pins are:
rx_pin: GPIO13
tx_pin: GPIO15
sensing_pin: GPIO12

The reader is working fine, I can enroll fingerprints and get quite good matches.
There are not other errors (the complete log is quite verbose, maybe not necessary?). The reader is initiated without errors. Restarting the board does not change this behaviour.
It seems to me that the reader is trying to read a fingerprint even if nothing is close to its scan.
