### ISSUE TITLE
ade7953 doesn't allow manual update

### ISSUE THREAD

**Issue by adrez99** [esphome/issues#2118]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
Shelly 2.5 (ESP8266)

**ESPHome version (latest production, beta, dev branch)**
v1.18.0 (latest production)

**Affected component:**
https://esphome.io/components/sensor/ade7953.html

**Description of problem:**
It's not possible to update the sensor manually with component.update

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: ade7953
    irq_pin: GPIO16
    voltage:
      id: voltage
      internal: true
    current_a:
      id: current_up
      internal: true
    current_b:
      id: current_down
      internal: true
    active_power_a:
      id: power_up
    active_power_b:
      id: power_down
      filters:
        - multiply: -1
    update_interval: never

interval:
  - interval: 1min
    then:
      - component.update: power_up
```

**Logs (if applicable):**

```
Failed config

interval: [source /config/shelly2_toldo.yaml:172]
  - [source /config/shelly2_toldo.yaml:172]
    interval: 1min
    then:  [source /config/shelly2_toldo.yaml:174]
      - [source /config/shelly2_toldo.yaml:174]
        component.update:  [source /config/shelly2_toldo.yaml:175]
          
          ID 'power_up' of type sensor::Sensor doesn't inherit from PollingComponent. Please double check your ID is pointing to the correct value.
          id: power_up [source /config/shelly2_toldo.yaml:175]
```

**Additional information and things you've tried:**
I've also tried the lambda .update() method but it isn't working too
