### ISSUE TITLE
WaveShare e-paper 5.83in V2 display not working

### ISSUE THREAD

**Issue by TheStork239** [esphome/issues#2121]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 Waveshare driver board. (I also tried with ESP8266 Waveshare driver board resulting in same issue.)

**ESPHome version (latest production, beta, dev branch)**

v1.18

**Affected component:**

WaveShare e-paper display
https://esphome.io/components/display/waveshare_epaper.html

**Description of problem:**
WaveShare 5.83in black & white display does not work with ESPHome, with the display not refreshing at all, and remaining blank (white), with only a black edge appearing around entire screen when connecting to the ESP32 device.  The display has a "V2" sticker on it; could it be that a new model config is needed for that too, as the new 5.83in V2 is now 648x480 resolution rather than 600x448 like the original 5.83in model was?

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: c-epaper
  platform: ESP32
  board: esp32dev
  on_boot:
    priority: -10
    then:
      - delay: 10s
      - component.update: epaperdisplay

wifi:
  ssid: "removed"
  password: "removed"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "removed"

font:

  - file: 'fonts/Roboto-Regular.ttf'
    id: main_sensor_unit
    size: 20
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z','å', 'ä', 'ö', '/','º','µ','³']

spi:
  clk_pin: 13   #SCK
  mosi_pin: 14  #DIN

display:
  - platform: waveshare_epaper
    id: epaperdisplay
    cs_pin: 15
    dc_pin: 27
    update_interval: 600s
    busy_pin: 25
    reset_pin: 26
    model: 5.83in
    lambda: |-

      it.print(40, 40, id(main_sensor_unit), "TEST");

```

**Logs (if applicable):**

```
No relevant log messages / errors.

```

**Additional information and things you've tried:**
I have also tried the display on ESPHome using a Waveshare ESP8266 driver board, but with no better success.
