### ISSUE TITLE
MiFlora (Xiaomi BLE) battery level unavailable

### ISSUE THREAD

**Issue by austwhite** [esphome/issues#2123]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant / Home Assistant Operating System in VM on VirtualBox
**ESP (ESP32/ESP8266, Board/Sonoff):**

Generic ESP32 device
**ESPHome version (latest production, beta, dev branch)**

Latest Production via Home Assistant addon
**Affected component:**

https://esphome.io/components/sensor/xiaomi_ble.html

**Description of problem:**
This was initially reported in 2019 under #107 and closed with the statement:
Closing as won't fix - I received my MiFlora and was able to confirm that the device does not send battery level data anymore (not even in a new packet type).

However, the device definitely does send the battery level data (in the newer models) as both the Home Assistant MiFlora integration and the FlowerCare app from Xiaomi can accurately retrieve the battery level data from the device that ESPHome cannot.
Can this issue be revisited and looked into further?

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: xiaomi_hhccjcy01
    mac_address: 'xx:xx:xx:xx:xx:xx'
    battery_level:
      name: 'Plant Battery Level'
    moisture:
      name: 'Plant Moisture'
    conductivity: 
      name: 'Plant Soil Cond'

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

All other readings I monitor are accurately updated. 
I have confirmed that the battery level is shown correctly in the Home Assistant MiFlora component, but due to location of the server the connection is flakey.
