### ISSUE TITLE
Multi remote receivers get Error with dump option by candidates checking

### ISSUE THREAD

**Issue by vietlehung** [esphome/issues#2127]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows7/VirtualBox/HassIO (HA core 2021.6.0 / OS 5.13)
**ESP (ESP32/ESP8266, Board/Sonoff):**

D1 mini or ESP32 Dev board got same error
**ESPHome version (latest production, beta, dev branch)**

ESPHome Ver 1.18.0
**Affected component:**

https://esphome.io/components/remote_receiver.html

**Description of problem:**
I'm trying to add multi remote_receivers to a D1 mini/ESP32 Dev kit with ESPhome 1.18.0 with guidance mentioned from here:
https://github.com/esphome/feature-requests/issues/679

and got following error

![multi_remote_receivers_01](https://user-images.githubusercontent.com/49737528/121984163-b50ce900-cdbc-11eb-9106-ab324920d23d.png)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "ABC"
  password: "XXXXXXXX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "qXJNtcxo1MME"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

remote_receiver:
  - id: receiver_one
    pin: D5
    dump: all
  - id: receiver_two
    pin: D6
    dump: all

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

It get error until I removed "dump" option. 
@glmnet  Can you please help to check if this problem relate to our error checking component id candidates. 
https://github.com/esphome/esphome/pull/1570
Thank you.

![multi_remote_receivers_02](https://user-images.githubusercontent.com/49737528/121984187-bccc8d80-cdbc-11eb-80d2-8e5b0c07733f.png)
