### ISSUE TITLE
RDM6300 working randomly

### ISSUE THREAD

**Issue by raidnet-ms** [esphome/issues#2131]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio 6.5 and esphome 1.18
**ESP (ESP32/ESP8266, Board/Sonoff):**
esp8266 on nodeMCU

**ESPHome version (latest production, beta, dev branch)**

esphome 1.18 stable
**Affected component:**

RDM6300 rfid [reader](https://esphome.io/components/binary_sensor/rdm6300.html)

**Description of problem:**
The reader works randomly and only few times.
I have two hardware units and both acts the same. I'm able to read the tag once and if i reset the nodemcu, next time i'm unable to read anything with no logs or error.

**Problem-relevant YAML-configuration entries:**
```yaml
uart:
  rx_pin: GPIO03
  baud_rate: 9600
#  parity: even
#  stop_bits: 2

rdm6300:
  on_tag:
    then:
    - homeassistant.tag_scanned: 'return uint32_to_string(x);'
    - logger.log: "Tag readen"
#    - text_sensor.template.publish:
#       id: rfid_tag_number
#        state: !lambda 'return uint32_to_string(x);'
    

#binary_sensor:           
#  - platform: rdm6300
#    uid: 'xxxxx'
#    name: "Key 2"


text_sensor:
  - platform: template
    name: "RFID Tag"
    id: rfid_tag_number

```

**Logs (if applicable):**

No logs unfortunately
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

I've tryed disabling the logger with baud rate 0
I've tryied to change phisical bus UART1 to the logger
I've tried all UART pins.
