### ISSUE TITLE
Template Switch doesn't update status in frontend

### ISSUE THREAD

**Issue by Zixim** [esphome/issues#214]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

unrelated but : Hassio 0.91.2
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**Affected component:**

https://esphome.io/components/switch/template.html

**Description of problem:**
Pressing the toggle-button in the device's webif does not toggle the state displayed in the webif, even though the switch is effectively toggled.
Logging does show that the switch was toggled.
The webif just does not update the status after toggle.
I also have an uptime sensor, the state of this one updates as expected.

**Problem-relevant YAML-configuration entries:**
```yaml
# Enable Web server
web_server:
# Enable Deep sleep
deep_sleep:
  id: deep_sleep_1
  run_duration: 90s
  sleep_duration: 1min
  wakeup_pin:
    number: GPIO0
    inverted: TRUE
#Switch to prevent deep sleep
switch:
  - platform: template
    name: "OTA mode"
    turn_on_action:
      then:
        - deep_sleep.prevent: deep_sleep_1
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
