### ISSUE TITLE
Setting Fan speed over MQTT

### ISSUE THREAD

**Issue by arctus** [esphome/issues#2142]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**

1.19.0

**Affected component:**

Speed FAN

**Description of problem:**
MQTT speed fan command only accepts preset values of: low, medium, high, that are converted to 33, 66 and 100 in the specified configuration below. MQTT speed fan state returns presets as well and not actual values. As I understand, the purpose of the change was to introduce ability to use actual speeds instead of presets, however it is impossible to set those using MQTT command (and get their value).

**Problem-relevant YAML-configuration entries:**
```yaml
output:
  - platform: ledc
    pin: GPIO16
    id: gpio_16

fan:
  - platform: speed
    output: gpio_16
    name: "Recuperator"
    speed_count: 100

```
