### ISSUE TITLE
Rotary ecnoders might need pull-up pins

### ISSUE THREAD

**Issue by slepiavka** [esphome/issues#2151]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Operating System Home Assistant OS 6.0, Version core-2021.6.4, Version supervisor-2021.06.3 
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 generic

**ESPHome version (latest production, beta, dev branch)**

Current version: 1.19.0

**Affected component:**

[Rotary Encoder sensor](https://esphome.io/components/sensor/rotary_encoder.html)

**Description of problem:**
"Barebones" rotary encoders without the breakout ([examples](https://duckduckgo.com/?q=EC11+rotary+encoder+-breakout&t=newext&atb=v206-1&iar=images&iax=images&ia=images)) don't seem to work without enabling the pull-up resistors on each pin. I think this is because these encoders are, in a way, just (floating?) push buttons.

Might be useful to call out for users that don't know how floating pins behave.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_a: 
      number: D7
      mode: INPUT_PULLUP
    pin_b: 
      number: D6
      mode: INPUT_PULLUP
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
