### ISSUE TITLE
LYWSD03MMC with custom pvvx advertisements not received on Xiaomi Mijia BLE component

### ISSUE THREAD

**Issue by TFhdKi95ae8L** [esphome/issues#2155]
5 pcs LYWSD03MMC with custom pvvx firmware version 3.2 and advertisement type custom do not get received by the ESP32.
I have 1 MiFlora, 2 CGDK2 and 1 LYWSD02 working on the ESP32.
I can also see the 5 LYWSD03MMC in the logs now and then; "found device MAC_ADDRESS, address type: PUBLIC, name: UNIT_NAME.
The units send data, it can be received by the telink flasher webpage.

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
HA OS on RPi 4

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32-WROOM-32

**ESPHome version (latest production, beta, dev branch)**
Latest

**Affected component:**
https://esphome.io/components/sensor/xiaomi_ble.html#lywsd03mmc

**Description of problem:**
See intro

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:xx:xx:xx"
    temperature:
      name: "Keuken Temperature"
    humidity:
      name: "Keuken Humidity"
    battery_level:
      name: "Keuken Battery-Level"
```

**Logs (if applicable):**

```


```

**Additional information and things you've tried:**

Reflashing the units with v3.2, changing advertising type to mi-like and adding dummy bindkey.
