### ISSUE TITLE
New device not being autodiscovered by Home Assistant

### ISSUE THREAD

**Issue by alexeyzel** [esphome/issues#2157]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 Mini (ESP8266)

**ESPHome version (latest production, beta, dev branch)**

v1.19.1

**Affected component:**

api

**Description of problem:**
I created and flashed new device based on Wemos D1 Mini. It shpows as "online" in ESPhome dashboard and i can view logs, but Home Assistant does not add this device to tha device list (on integration page)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: plant-controller
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "pass"

ota:
  password: "pass"

wifi:
  ssid: "ssid"
  password: "pass"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Plant-Controller"
#    password: "H3p7iUE3b5Pr"
#
#captive_portal:

switch:
  - platform: gpio
    pin: D1
    name: "Pump"
    restore_mode: ALWAYS_OFF
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I tried to reboot HA, restart ESPhome.
The manual says that there should be "configure" button on the integration page to try to set it up manually, but I can't find it.

**Comment by alexeyzel** [comment]
Changed switch name to "PlantPump" and it helped. Device have been discovered. New config:

```
esphome:
  name: plant-controller
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "pass"

ota:
  password: "pass"

wifi:
  ssid: "ssid"
  password: "pass"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Plant-Controller"
#    password: "H3p7iUE3b5Pr"
#
#captive_portal:

switch:
  - platform: gpio
    pin: D1
    name: "PlantPump"
    restore_mode: ALWAYS_OFF
```
