### ISSUE TITLE
SSD1306 - OLED display doesn't show anything anymore since 1.17.2

### ISSUE THREAD

**Issue by 7h30n3** [esphome/issues#2160]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU from Amica (ESP8266)

**ESPHome version (latest production, beta, dev branch)**

1.19.1

**Affected component:**

https://esphome.io/components/display/ssd1306.html#ssd1306-spi

**Description of problem:**
After updating ESPHome from 1.16.2 to 1.19.1 my OLED display (SH1106) doesn't show anything anymore.
Even downgrading to 1.18.0 and 1.17.2 didn't bring any improvement.
After downgrading to 1.16.2 everything works again as expected.
Not matter the version the log doesn't show any warnings or errors.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  platform: ESP8266
  name: sh1106_si7021
  board: nodemcuv2

api:

wifi:
  ssid: ' '
  password: ' '
  manual_ip:
    static_ip: 192.168.1.41
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  fast_connect: true
  power_save_mode: high

# Enable logging
logger:
  level: debug
  baud_rate: 0
  
i2c:

ota:

substitutions:
  device_name: SH1106 Si7021
  device_id: sh1106_si7021


spi:
  clk_pin: 14
  mosi_pin: 13

sensor:
  - platform: wifi_signal
    name: "${device_name} RSSI"
    filters:
        - delta: 2.0
    
  - platform: htu21d
    temperature:
      filters:
        - delta: 0.4
        - offset: -3.4
      name: "${device_name} Temperature"
      unit_of_measurement: "°C"
      id: temperature
    humidity:
      filters:
        - delta: 1.2
      name: "${device_name} Humidity"
      accuracy_decimals: 1
      unit_of_measurement: "%"
      id: humidity
    update_interval: 60s
    
time:
  - platform: homeassistant
    id: time_hass

font:
  - file: "sh1106_si7021_dependencies/arial.ttf"
    id: arial_14
    size: 14
    glyphs: "HeloWrd! "    

display:
  - platform: ssd1306_spi
    model: "SH1106 128x64"
    brightness: 60%
    cs_pin: 15
    dc_pin: 0
    reset_pin: 2
    id: my_display
    lambda: |-
      it.print(0, 0, id(arial_14), "Hello World!");
```

**Logs (if applicable):**

```
[spi:081]: SPI bus:
[spi:082]:   CLK Pin: GPIO14 (Mode: OUTPUT)
[spi:084]:   MOSI Pin: GPIO13 (Mode: OUTPUT)
[spi:085]:   Using HW SPI: YES
[ssd1306_spi:019]: SPI SSD1306
[ssd1306_spi:019]:   Rotations: 0 °
[ssd1306_spi:019]:   Dimensions: 128px x 64px
[ssd1306_spi:020]:   Model: SH1106 128x64
[ssd1306_spi:021]:   CS Pin: GPIO15 (Mode: OUTPUT)
[ssd1306_spi:022]:   DC Pin: GPIO0 (Mode: OUTPUT)
[ssd1306_spi:023]:   Reset Pin: GPIO2 (Mode: OUTPUT)
[ssd1306_spi:024]:   External VCC: NO
[ssd1306_spi:025]:   Update Interval: 1.0s

```

**Additional information and things you've tried:**
