### ISSUE TITLE
Example code in XPT2046 touch documentation not working due to spurious comma

### ISSUE THREAD

**Issue by drpetersen** [esphome/issues#2161]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

`pip 21.1.2 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)`

**ESP (ESP32/ESP8266, Board/Sonoff):**

`esp32dev` (DevKitC V4)

**ESPHome version (latest production, beta, dev branch)**

1.19.1

**Affected component:**

[`xpt2046`](https://www.esphome.io/components/binary_sensor/xpt2046.html)

**Description of problem:**

The example code in the *Calibration* section of the documentation for the new XPT2046 touch integration does not compile due to a spurious comma at the end of the second-to-last line. That line should read,

```
              id(touchscreen).y_raw
```

*without* the comma at the end, otherwise compilation results in the following error:

```
Compiling .pioenvs/mydevice/src/main.cpp.o
In file included from src/esphome/components/api/api_server.h:6:0,
                 from src/esphome/components/api/api_connection.h:7,
                 from src/esphome.h:2,
                 from src/main.cpp:3:
mydevice.yaml: In lambda function:
src/esphome/core/log.h:101:99: error: expected primary-expression before ')' token
   esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                                   ^
src/esphome/core/log.h:146:28: note: in expansion of macro 'esph_log_i'
 #define ESP_LOGI(tag, ...) esph_log_i(tag, __VA_ARGS__)
                            ^
mydevice.yaml:159:9: note: in expansion of macro 'ESP_LOGI'
*** [.pioenvs/mydevice/src/main.cpp.o] Error 1
================================================= [FAILED] Took 1.71 seconds =================================================
```

**Problem-relevant YAML-configuration entries:**
```yaml
# …
xpt2046:
  id: touchscreen
  cs_pin: 17
  irq_pin: 16
  dimension_x: 240
  dimension_y: 320
  on_state:
    - lambda: |-
        if (touched)
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%d",
              id(touchscreen).x,
              id(touchscreen).y,
              id(touchscreen).x_raw,
              id(touchscreen).y_raw,
              );
# …
```

**Logs (if applicable):**

(Not applicable, fails at compile time.)

**Additional information and things you've tried:**

Removing the spurious comma solves the problem for me.
