### ISSUE TITLE
OTA Update Failed: ERROR[8]: Flash config wrong real: 4194304 IDE: 16777216

### ISSUE THREAD

**Issue by lblokland** [esphome/issues#218]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Using Hassio and ESPHome

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 ,D1 Mini by Robotdyn

**Affected component:**

OTA is failing

**Description of problem:**
Hi,

I'm using a D1 Mini (RobotDyn) with 32Mb and when trying to flash OTA the debug on the webinterface shows
`Update Failed: ERROR[8]: Flash config wrong real: 4194304 IDE: 16777216`
Flashing manually using 'esptool -cp COM3 -bm dout -cf image.bin -v' works just fine.

The error message on ESPhome console is:
'
INFO Uploading /data/d1_1/.pioenvs/d1_1/firmware.bin (386752 bytes)
ERROR Error binary size: Error: ESP has been flashed with wrong flash size. Please choose the correct 'board' option (esp01_1m always works) and then flash over USB.
WARNING OTA v2 method failed. Trying with legacy OTA...
INFO Starting on 0.0.0.0:46964
INFO Upload size: 386752
INFO Sending invitation to 192.168.178.16 
..........
ERROR No response from the ESP
'

Does anyone know how to solve this?

Cheers,
Leon

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: d1_1
  platform: ESP8266
  board: d1_mini
#  board: Generic 4M
web_server:
  port: 80
## Example configuration entry
output:
  - platform: gpio
    pin: D1
    id: gpio_d1
    
## Example configuration entry
light:
  - platform: binary
    name: "LED Lamp"
    output: gpio_d1
    
## Example configuration entry
#mqtt:
#  broker: 192.168.178.15
#  username: jj
#  password: jj

wifi:
  ssid: "jj"
  password: "jj"
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.178.16
    gateway: 192.168.178.1
    subnet: 255.255.255.0
    dns1: 192.168.178.1
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'jj'

ota:
  password: 'jj'
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
