### ISSUE TITLE
Substitutions not working for some entities id

### ISSUE THREAD

**Issue by chemelli74** [esphome/issues#2188]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**

v1.19.2

**Affected component:**

https://esphome.io/components/sensor/wifi_signal.html
https://esphome.io/components/text_sensor/

**Description of problem:**
Substitutions are operated on the name but not on the entity id for both `wifi_signal` and `text_sensor`.
Work fine instead for `template`.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  device_name: "Gateway BLE Salotto"

sensor:
  - platform: template
    id: sensor_uptime_timestamp
    name: ${device_name} Uptime
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(homeassistant_time).utcnow().timestamp - id(sensor_uptime).state
      );
      return timestamp;

  - platform: wifi_signal
    name: ${device_name} RSSI
    update_interval: 60s

text_sensor:
  - platform: version
    name: ${device_name} Version
    hide_timestamp: true
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

![image](https://user-images.githubusercontent.com/57354320/123411866-392b5180-d5b1-11eb-992a-91c97e2907ac.png)
