### ISSUE TITLE
Double log messages in Web Server GUI

### ISSUE THREAD

**Issue by 5tan** [esphome/issues#2189]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Ubuntu 20.04, esphome installed using pip.

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32, ESP-WROOM-32 on ESP DevKit v1

**ESPHome version (latest production, beta, dev branch)**

1.18.0

**Affected component:**

web_server

**Description of problem:**
Some log messages are doubled in web_server GUI log.
Please note it doesn't happen in serial comm log (left side of the screen).
![image](https://user-images.githubusercontent.com/15819543/123425751-ce831180-d5c2-11eb-9d10-58fde4cc3160.png)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: abc
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: ...
  password: ...

debug:

logger:
  level: DEBUG

ota:

web_server:
  port: 80
  auth:
    username: user
    password: pass

switch:
  - platform: gpio
    id: real_switch
    name: real switch
    pin: GPIO23
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
