### ISSUE TITLE
fastled_clockless while ESP booting first LED is ON and it is GREEN automatically (after updating to 1.19.4) 

### ISSUE THREAD

**Issue by varadujagan** [esphome/issues#2196]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
 
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (D1 mini)

**ESPHome version (latest production, beta, dev branch)**

1.19.4 

**Affected component:**

fastled_clockless

**Description of problem:**
I came across one problem in my WS2812B led, which is connected with Wemos D1 mini.
when powering ON - Wemos D1 mini,  always first LED in WS2812B strip will on and it goes to green color. every time I have to manually turn on the strip and back to off to clear the green color. Other than that Wemos D1 mini and LED (WS2812B) are working great. I'm facing this only after updating (1.19.2 -> 1.19.4)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp_door_bell
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: *******
  password: *******

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
ota:
  password: *******

api:
  password: *******
  services:
    - service: keep_buzzer
      then:
        - rtttl.play: "beep:d=16,o=5,b=100:b"
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

# Status LED 
status_led:
  pin: GPIO2
  
 
binary_sensor:
# door bell
  - platform: gpio
    pin:
      number: D6
      inverted: True
    name: "door bell"
    filters:
      - delayed_off: 50ms
# buzzer 
output:
  - platform: esp8266_pwm
    pin: D5
    id: rtttl_out

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: 'Song ended!'

light:
# light strip 
  - platform: fastled_clockless
    chipset: WS2812b
    pin: D4
    num_leds: 100
    rgb_order: GRB
    name: "Pathway LED"
    effects:
      - addressable_rainbow:
      - addressable_scan:
      - addressable_twinkle:

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
light wiring image : [https://community-assets.home-assistant.io/original/3X/6/f/6f006fa3249674c159ec9c06b247106b40b4bea3.jpeg](url)
For reference: [https://youtu.be/clp0s_mEZyc](url)
