### ISSUE TITLE
Adding Servo component (and ESP8266_pwm) to code stops wifi connecting.

### ISSUE THREAD

**Issue by mr-sneezy** [esphome/issues#220]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HA on hassOS on RPi3

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU v3
**Affected component:**

Servo component

**Description of problem:**
I have a project that has a PIR sensor and LED working fine and reporting motion to HA.

When I add a Servo component to that code, and then upload, the ESPhome node drops offline and won't reconnect ( but the actual NodeMCU hardware responds to the PIR iva LED on/off & servo PWM changes on the pwm pin when viewed on oscilloscope).

Using ESPhomeFlasher to upload same code again gets same result (OTA not possible after issue occurs), logs show the ESP8266 not getting BSSID and Channel like a normal connection. Again the NodeMCU works via it's pin responses and pwm on CRO but node wifi won't connect to the router.

Oddly, reverting to the previous good YAML code (ripping out the Servo and pwm stuff) does NOT restore wifi connection right way after upload via ESPhomeFlasher and rebooting!
What does restore wifi is reflashing with Sonoff Tasmota firmware and checking wifi is working with that, then uploading the previous good ESPhome code after that again and rebooting. 

So to my untrained eye it appears that adding the Servo component is screwing with the wifi code somehow (but I'll be surprised if that's actually right).

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
**wifi killing code**
esphome:
  name: remote_actuator_node1
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "not_my_ssid"
  password: "not_my_password"

  manual_ip:
# Set this to the IP of the ESP
    static_ip: 192.168.0.22
# Set this to the IP address of the router. Often ends with .1
    gateway: 191.168.0.1
# The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  fast_connect: true
# Enable logging

logger:
  level: VERBOSE
# Enable Home Assistant API
api:

ota:

servo:
  - id: my_servo
    output: pwm_output

output:
  - platform: gpio
    pin: D1
    inverted: False
    id: gpio_d1_led
    
  - platform: esp8266_pwm
    id: pwm_output
    pin: D6
    frequency: 50 Hz

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Multisensor Motion"
    device_class: motion
    
    on_press:
      then:
        - output.turn_on: gpio_d1_led
        - servo.write:
            id: my_servo
            level: 100.0%          
    on_release:
      then:
        - output.turn_off: gpio_d1_led
        - servo.write:
            id: my_servo
            level: -100.0%

**previous code that wifi works fine with**
esphome:
  name: remote_actuator_node1
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "not_my_ssid"
  password: "not_my_password"

  manual_ip:
# Set this to the IP of the ESP
    static_ip: 192.168.0.22
# Set this to the IP address of the router. Often ends with .1
    gateway: 191.168.0.1
# The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  fast_connect: true
  
# Enable logging
logger:
#  level: VERBOSE

# Enable Home Assistant API
api:

ota:

output:
  - platform: gpio
    pin: D1
    inverted: False
    id: gpio_d1_led

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Multisensor Motion"
    device_class: motion
    
    on_press:
      then:
        - output.turn_on: gpio_d1_led
        
    on_release:
      then:
        - output.turn_off: gpio_d1_led

```

**Traceback (if applicable):**

```
Compilation and verification is passing with no errors.
```

**Additional information and things you've tried:**
I've repeated the process three times to get the Servo component working and then back tracking to the previous working code (after the Tasmota step to check wifi module still working on that FW).
Not sure what to ask to fix my issue. I have recorded the logs from the failing code and the passing code if needed...
