### ISSUE TITLE
external_component not finding main or default branch using short hand form

### ISSUE THREAD

**Issue by gb53smith** [esphome/issues#2208]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 Mini
Probably not board dependent.

**ESPHome version (latest production, beta, dev branch)**

v19.2

**Affected component:**

external_component:

**Description of problem:**
The external component can be found on my dev1 branch but not on @main or default by removing the @.
With @main the github.com/esphome/esphome/components/dht files are copied to the output source code directory.
Without @ there is a yaml error about missing __int__.py

**Problem-relevant YAML-configuration entries:**
```yaml

external_components:
  - source: github://gb53smith/esphome@main
    components: [dht]
```
Long form works with this
```
  source:
    type: git
    url: https://github.com://gb53smith/esphome
    ref: main
  components: [dht]
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
Please post what error ESPHome shows. Also note that if you added the `__init__.py` file later, it won't get pulled right away due to the `refresh` setting

**Comment by gb53smith** [comment]
The error message is
```
Compiling /data/plants/.pioenvs/plants/src/esphome/components/dht/dht.cpp.o
Compiling /data/plants/.pioenvs/plants/src/main.cpp.o
src/esphome/components/dht/dht.cpp:246:26: error: no 'bool esphome::dht::DHT::read(bool)' member function declared in class 'esphome::dht::DHT'
 bool DHT::read(bool force) {                   ^
*** [/data/plants/.pioenvs/plants/src/esphome/components/dht/dht.cpp.o] Error 1
```
In my latest dht.h (main)  there is ```bool readSensor```.  The ```bool read``` was used on another branch in my repository.

So in summary what works is:
```
source: github://esphome/esphome@dev  #any branch other than main
   components: [dht]

# This long form reference to main
source:
    type: git
    url: https://github.com:/gb53smith/esphome
    ref: main
  components: [dht]
```
What does not work is:
```
source: github://gb53smith/esphome@main  #short form reference to main
    components: [dht]

source: github://gb53smith/esphome #short form reference to default branch
    components: [dht]

```
The empty __init__.py  filename was missing the second underscore in an earlier version but that was corrected and committed.

PS.
I found this external_component feature to be very useful when testing various versions of the DHT component
