### ISSUE TITLE
Bootloop device after updating

### ISSUE THREAD

**Issue by eugene-ki** [esphome/issues#2210]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Add-on in Hass.io (Supervised)
**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff Basic (ESP8285)
**ESPHome version (latest production, beta, dev branch)**

latest production (1.19.4)
**Affected component:**

WiFi Component

**Description of problem:**
After updating to one of the 1.19.* releases there are bootloop on my Sonoff Basic. It's can't connect to WiFi.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: relay_kitchen
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

wifi:
  ssid: ***
  password: '***'
  fast_connect: true


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "relay_thermo_kitchen_button"
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: template
    name: "relay_thermo_kitchen_switch"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    name: "relay_thermo_kitchen_light"
    output: basic_green_led
    id: led

sensor:
  - platform: wifi_signal
    name: "relay_thermo_kitchen_wifi_signal"
    update_interval: 3600s
  - platform: uptime
    name: "relay_thermo_kitchen_uptime"

```

**Logs (if applicable):**

```
There have been suspected X unsuccessful boot attempts. <-- This message in loop

And my router had this log:
192.168.x.x - MAC - DHCP assigned
192.168.x.x - MAC - DHCP deassigned
192.168.x.x - MAC - DHCP assigned
192.168.x.x - MAC - DHCP deassigned

Also in loop, when Sonoff Basic was turned on.
```

**Additional information and things you've tried:**

I had an old 1.16.2 compiled .bin file and it's working fine after I have flashed it by "ESPHome-Flasher-1.2.0-windows-x64".
With static ip option the same issue.
