### ISSUE TITLE
Cannot use dump with more than one remote_receiver

### ISSUE THREAD

**Issue by wesleygas** [esphome/issues#2215]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io core-2021.6.6, using ESPHome addon 1.19.4

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**

1.19.4

**Affected component:**

https://esphome.io/components/remote_receiver.html

**Description of problem:**

Trying to use `dump` when more than one remote_receiver is configured causes

 ```Too many candidates found for 'receiver_id' type 'remote_base::RemoteReceiverBase'. Some are 'rf_recv', 'ir_recv'.``` 

using, for example, the YAML shown in the issue [#679](https://github.com/esphome/feature-requests/issues/679) from feature requests or the following equivalent:

**Problem-relevant YAML-configuration entries:**
```yaml
remote_receiver:
  - id: "rf_recv"
    pin: 
      number: GPIO32
    dump: all
  - id: "ir_recv"
    pin: 
      number: GPIO34
    dump: all
```

**Additional information and things you've tried:**

If dump is not used, everything works fine

**Comment by glmnet** [comment]
This is interesting. Might be just bogus or revealing a issue behind.

**Comment by jesserockz** [comment]
The issue is that the dump schema is more complicated than that and attaches a receiver_id to each dump.

**Comment by wesleygas** [comment]
Is there a way to define which receiver each dumper should be attached to? 

Like it is done within automations or a binary sensor:
```YAML
on_lg:
     receiver_id: "ir_recv" #Like here
     then:
       ...

binary_sensor:
  - platform: remote_receiver
    receiver_id: "rf_recv" #And here
    id: "rfTab1"
    rc_switch_raw:
      code: ...
```

**Comment by glmnet** [comment]
This candidates check already has a special case check for time (as you wouldn't care which time to get the time from as the esp only has one time anyway) maybe dump can be added to the list.

**Comment by jesserockz** [comment]
```yaml
...
dump:
  - jvc:
    receiver_id: ...
```

Indentation is correct above
