### ISSUE TITLE
BME680 different humidity readings (bme680 vs bme680_bsec)

### ISSUE THREAD

**Issue by jjansen85** [esphome/issues#2217]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker (on Synology NAS)

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 Wemos D1 mini

**ESPHome version (latest production, beta, dev branch)**

Latest v1.19.4

**Affected component:**

BME680

**Description of problem:**
I have attached and configured the BME680 sensor.
I use the standard BME680 library and the BME680_BSEC library.
The humidity output of both libraries is very different.

<img width="325" alt="Screenshot 2021-07-04 at 20 30 52" src="https://user-images.githubusercontent.com/26403565/124395990-6e4d4780-dd07-11eb-9bb7-3159f09b19af.png">

**Problem-relevant YAML-configuration entries:**
```yaml
i2c:
  sda: D4
  scl: D3
  scan: True  

bme680_bsec:
  address: 0x77  

sensor:
  - platform: bme680
    temperature:
      name: "BME680 Temperature"
    humidity:
      name: "BME680 Humidity"
    address: 0x77
    update_interval: 20s    
  - platform: bme680_bsec
    temperature:
      name: "BME680_bsec Temperature"
    humidity:
      name: "BME680_bsec Humidity"

```

**Logs (if applicable):**

```
N/A

```

**Additional information and things you've tried:**
