### ISSUE TITLE
[i2c_id] is an invalid option for [sensor.custom].

### ISSUE THREAD

**Issue by 5tan** [esphome/issues#2218]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Ubuntu 20.04, esphome installed using pip.

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32, ESP-WROOM-32E on Espressif board 

**ESPHome version (latest production, beta, dev branch)**

1.18.0

**Affected component:**

sensor

**Description of problem:**
I have two identical (the same address) i2c sensors on two buses.
How to specify which bus should sensor use?

**Problem-relevant YAML-configuration entries:**
```yaml
i2c:
  - id: bus1
    sda: GPIO32
    scl: GPIO27
  - id: bus2
    sda: GPIO25
    scl: GPIO26

sensor:
  - platform: custom
    # i2c_id: bus1
    # address: 0x10
    lambda: |-
      auto sensor = new Veml7700();
      App.register_component(sensor);
      return {sensor};
    sensors:
      name: ALS1
```

**Logs (if applicable):**

```
  platform: custom
  
  [i2c_id] is an invalid option for [sensor.custom]. Please check the indentation.

```

**Additional information and things you've tried:**
