### ISSUE TITLE
LEDC dimming cycle flickers when using I2C

### ISSUE THREAD

**Issue by intermittech** [esphome/issues#2222]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Using Windows 10 and Home Assistant running in Virtual Machines (Proxmox)

**ESP (ESP32/ESP8266, Board/Sonoff):**

Custom ESP32 dimmer boards, QuinLED-Quad, QuinLED-Deca, Prototype boards

**ESPHome version (latest production, beta, dev branch)**

Newest version, as of writing 1.19.4 in fully updated Home Assistant

**Affected component:**

LEDC dimming between values

**Description of problem:**
Everything works correctly when just using LEDC and dimming between values per channel. After adding I2C Screen or Temperature sensor I noticed flickering at some moments. After lowering temperature sensor read time to 10s and setting dimming transition time to 10s it was pretty clear that each time the temperature sensor was read, any dimming fade/change that was going on gets interrupted causing a visual flicker.

Once fading is done, LEDC PWM output is fully stable, flickers are only visible during transition times.

**Problem-relevant YAML-configuration entries:**
```yaml
i2c:
  sda: 1
  scl: 3
  frequency: 400kHz
  scan: true

output:
  - platform: ledc
    pin: 2
    frequency: 20000Hz
    id: LED_channel_1

light:
  - platform: monochromatic
    name: "${esphome_name}-1"
    default_transition_length: 5s
    id: LED1
    output: LED_channel_1

sensor:
  - platform: aht10
    temperature:
      name: "test_anpentalan Temperature"
    humidity:
      name: "test_anpentalan Humidity"
    update_interval: 10s
```

**Logs (if applicable):**

```
I can add logs but there is nothing special visible in the logs, all seems to be working normally.

```

**Additional information and things you've tried:**
I've tried varying I2C frequency, 10kHz, 100kHz, 400kHz or 1000kHz makes no difference to the issue. Tried using only temperature sensor (AHT21) or screen, no change to issue, especially with screen updating issue is VERY apparent. Almost like I2C interrupts the (likely) software dimming routine, sending the new values out very quickly to show the smooth fade.
