### ISSUE TITLE
Climate ir LG starts allways on cold

### ISSUE THREAD

**Issue by hugodelaroza** [esphome/issues#2225]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASSIO

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 - Wemos D1 mini

**ESPHome version (latest production, beta, dev branch)**

Vession 1.19.4

**Affected component:**

Climate IR (https://www.esphome.io/components/climate/ir_climate.html)

**Description of problem:**
When the climate is off, it allways turns on in cold mode, no matter if I touch the cold or hot mode, it turns on in cold mode. After that, I can change the mode to heat if I want and it does it well.
Even more, if I user the IR controller to turn it on, and the controller was in heat, the equipement turns on in heat (that´s ok), but the component in Home Assistant is in cold.

Resuming, the component allways starts in cold 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

remote_transmitter:
  pin: D5
  carrier_duty_percent: 50%



remote_receiver:
  id: rcvr
  pin:
    number: D1
    inverted: True
    mode: INPUT_PULLUP
  dump: all
  tolerance: 55%



climate:
  - platform: climate_ir_lg
    name: "LG Living"
    sensor: templivingid
    receiver_id: rcvr
    header_high: 3265us # AC Units from LG in Brazil, for example use these timings
    header_low: 9856us

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
