### ISSUE TITLE
i2c bus fails after restart

### ISSUE THREAD

**Issue by LeoMaguire** [esphome/issues#2229]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Host Operating System | Home Assistant OS 6.1
-- | --
Update Channel | stable
Supervisor Version | supervisor-2021.06.8
Docker Version | 20.10.6
Disk Total | 1833.1 GB
Disk Used | 5.9 GB
Healthy | true
Supported | true
Board | rpi4-64
Supervisor API | ok
Version API | ok
Installed Add-ons | Node-RED (9.1.4), MariaDB (2.4.0), Visual Studio Code (3.5.0), Mosquitto broker (6.0.1), Terminal & SSH (9.1.3), ESPHome (1.19.4)

**ESP (ESP32/ESP8266, Board/Sonoff):**

Adafruit Huzzah ESP8266 attached to Atlas Scientific Hydroponics WiFi basic kit

**ESPHome version (latest production, beta, dev branch)**

ESPHome Current version: 1.19.4 
**Affected component:**

**Description of problem:**
Restarting ESP8266 causes i2c bvus failure.  Anytime power is removed from ESP8266 we are no longer able to enable the i2c bvus without pushing multiple sketches to change i2c pins to other pins and then back to the proper pins - thus triggering some sort of hard reset on the pins it seems.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: attic-sensors
  platform: ESP8266
  board: huzzah

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "**************************"

wifi:
  ssid: "*******************"
  password: "****************"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Attic-Sensors Fallback Hotspot"
    password: "*************"

captive_portal:

i2c:
  scan: True
#  sda: GPIO13
#  scl:  GPIO14


sensor:
  - platform: ezo
    id: rtd_ezo
    name: "RTD Temperature"
    address: 102
    accuracy_decimals: 2
    unit_of_measurement: "°C"
    update_interval: 30s

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

repeats every time power is cycled on esp8266.  Steps to fix are:

Change:
```
#  sda: GPIO13
#  scl:  GPIO14
```

to

 ```
 sda: 3
 scl: 4
```
  
  Push sketch, wait for boot.
  
  THEN
  
  Change
```
  sda: 3
  scl: 4
```

to

```
  sda: GPIO13
  scl:  GPIO14
```

 push sketch, wait for boot.
 
 
 THEN
 
 Change
```
  sda: GPIO13
  scl:  GPIO14
```

to

```
#  sda: GPIO13
#  scl:  GPIO14
```

push sketch, wait for boot and it should be able to detect i2c devices once again until next reboot / power cycle.
