### ISSUE TITLE
outputs momentarily activated on boot

### ISSUE THREAD

**Issue by puerari** [esphome/issues#2234]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU ESP32

**ESPHome version (latest production, beta, dev branch)**

From: 1.15.3
To: 1.19.4

**Affected component:**

https://esphome.io/components/switch/gpio.html

**Description of problem:**
After update from 1.15.3 to 1.19.4, on boot, all outputs are momentarily set to on. 
After that, the restore_mode configurations are correctly applied.

The problem is that one of my devices (a gate) is activated by pulse and on each boot or reboot the gate is open or closed.

Some new configurations should i do or is it a bug?

**Problem-relevant YAML-configuration entries:**
```yaml
i2c:
  sda: 21
  scl: 22
  scan: False
mcp23017:
  - id: mcp
    address: 0x20
switch:
  - platform: gpio
    name: "Fundo"
    icon: "mdi:track-light"
    id: relay02
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
        mcp23xxx: mcp
        number: 0
        mode: OUTPUT
        inverted: True
binary_sensor:
  - platform: gpio
    name: "Int Fundo"
    internal: True
    pin:
        number: GPIO33
        inverted: True
        mode: INPUT_PULLUP
    on_click:
      max_length: 350ms
      then:
        - switch.toggle:
            id: relay02
    on_double_click:
      min_length: 351ms
      max_length: 999ms
      then:
        - switch.toggle:
            id: relay05
    filters:
      - delayed_on_off: 10ms
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
