### ISSUE TITLE
Float Output: min_power prevents output from turning completely off

### ISSUE THREAD

**Issue by WeekendWarrior1** [esphome/issues#2237]
#### Scenario:
You have an LED configured as a monochromatic light component, controlled by an esp8266_pwm float output (though this issue is the same for all float outputs).
The LED has a minimum duty cycle of 7% required to produce light (operating at the default 1000hz frequency). Below this, it does not turn on.
When you operate the light through HA, you don't want to have to move the brightness slider to 7% to turn on the light, so you set ``min_power: 0.07`` in the yaml.
This works! Now your light output is being scaled/mapped from within HA as 1%-100%, to within esphome as 7%-100%
Happy with the solution, you turn off the light within HA, but to your dismay, the light is still on, very dimly!
#### What is happening?:
When you turn the light off, esphome gets sent a percentage of 0.0 to ``FloatOutput::set_level``, which then gets clamped to your ``min_power`` of 0.07, keeping your light dimly lit.
#### What should happen?:
Light off should mean off, not set to 7% brightness.

#### Testing this:
Once can simply use an LED and resistor attached to an ESP pin to test this.
In the example yaml below I have set ``min_power`` to .50 to help highlight the issue, when you turn the light off, it will still be on at 50% brightness.
One can also add:
```c++
ESP_LOGD(TAG,"adjusted_value %f",adjusted_value);
```
to ``esphome/components/output/float_output.cpp >> void FloatOutput::set_level``, below the line where adjusted_value is declared.

I will push a merge request to fix this, but wanted to make sure that there isn't some sort of good reason this functionality should remain the way it is.

I found some discussion about the issue here: [https://www.reddit.com/r/Esphome/comments/jv48o9/how_to_limit_brightness_range/](https://www.reddit.com/r/Esphome/comments/jv48o9/how_to_limit_brightness_range/)
And a feature request to fix this here: [https://github.com/esphome/feature-requests/issues/1176](https://github.com/esphome/feature-requests/issues/1176)
And here: [https://github.com/esphome/feature-requests/issues/920](https://github.com/esphome/feature-requests/issues/920)

### What is version of ESPHome has the issue?

v1.19.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

float_output

### Example YAML snippet

```yaml
output:
  - platform: esp8266_pwm
    id: output_led
    pin: D4
    min_power: 0.50


light:
  - platform: monochromatic
    name: 'Test_LED'
    output: output_led
    default_transition_length: 0s
    gamma_correct: 0.0        #disabled to demonstrate this more easily
```
