### ISSUE TITLE
I cannot reset the Wi-Fi information by long pressing the button

### ISSUE THREAD

**Issue by tarontop** [esphome/issues#2238]
### The problem

I cannot reset the Wi-Fi information by long pressing the button

### What is version of ESPHome has the issue?

v1.19.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

esp8285

### Component causing the issue

switch

### Example YAML snippet

```yaml
esphome:
  name: plug
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp8285

logger:

api:

ota:

web_server:
  port: 80
  
wifi:
  ap:
    ssid: "test"
    password: ""

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: 3
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    on_press:
      - switch.toggle: relay
    on_click:
      min_length: 4s
      max_length: 8s
      then:
        - lambda: |-
              ESP.eraseConfig();
              ESP.reset();
              ESP.restart();

sensor:
  - platform: uptime
    name: Uptime Sensor
    
switch:
  - platform: gpio
    id: blue_led
    pin:
      number: GPIO13
      inverted: true

  - platform: gpio
    name: "Smart Plug"
    pin: GPIO14
    id: relay
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led
```

### Anything in the logs that might be useful for us?

```txt
It only restarted
```
