### ISSUE TITLE
esp32 RMT IR transmitter set to inverted doesn't send packets correctly

### ISSUE THREAD

**Issue by WeekendWarrior1** [esphome/issues#2240]
#### When using esp32 rmt transmitter with an inverted output, marks and spaces aren't correctly handled, leading to garbled messages.
(This bug was very frustrating to track down!)

#### How to test
Requires 2 esp's to test (at least one must be an esp32)
```yaml
# ESP32

remote_transmitter:
  pin:
    number: GPIO17
    inverted: True
  carrier_duty_percent: 100%

climate:
  - platform: coolix
    name: "Transmitting AC"
```
```yaml
#ESP32 or ESP8266

remote_receiver:
  id: rcvr
  pin:
    number: D2
    inverted: True
    mode: INPUT_PULLUP
  tolerance: 55%

remote_transmitter:
  id: unused_transmitter_leave_floating
  pin:
    number: D3

climate:
  - platform: coolix
    name: "Receiving AC"
    receiver_id: rcvr
```

- Connect a jumper from GPIO17 of the "Transmitting AC" to  D2 of the "Receiving AC"
- Connect a jumper between the grounds of the two boards
- Power them up
- Set a climate setting for the "Transmitting AC"

#### What should happen in this example?
The Receiving AC should be able to parse the body, and the climate settings of "Transmitting AC" should be mirrored by "Receiving AC"

#### What is happening?
The Receiving AC receives garbage (the marks and spaces are inverted (which also effects header detection))

#### Why?
It looks like the RMT peripheral doesn't use esphome's GPIO API, but does still check to see if it's GPIO pin is set to inverted. If so, it swaps the levels of it's idle+carrier signals (so low idle gets flipped to high, and carrier gets flipper to low).
Unfortunately that is the only logic that it performs, and ``data->mark`` and ``data->space`` don't also get inverted.

#### How to confirm that this is the issue
Head to ``esphome/components/coolix/coolix.cpp`` and swap every ``data->mark`` with ``data->space``, and every ``data->space`` with ``data->mark`` (effectively inverting them).
Build this new component, and **ONLY** compile+upload it to the "Transmitting AC" esp32.
Attempting the same experiment as before, the "Receiving AC" should now be mirrored.

#### Discussions around the web + Discoveries
[https://github.com/espressif/esp-idf/issues/5573](https://github.com/espressif/esp-idf/issues/5573)
Looks like this person is also having a similar issue.

After digging around [https://github.com/espressif/esp-idf/blob/master/components/driver/include/driver/rmt.h](https://github.com/espressif/esp-idf/blob/master/components/driver/include/driver/rmt.h), I found a few possible avenues:

- [#define RMT_CHANNEL_FLAGS_INVERT_SIG](https://github.com/espressif/esp-idf/blob/master/components/driver/include/driver/rmt.h#L24) looked promising, but don't really know how to tweak that.
- [rmt_set_gpio()](https://github.com/espressif/esp-idf/blob/master/components/driver/include/driver/rmt.h#L579) looks like it could be called prior to running ``rmt_config()`` to invert a GPIO within the RMT - alas, this function isn't currently available within any ``platformio/framework-arduinoespressif32``

#### Ways it can be fixed

1. Go through **every** component that uses IR and catch if the output pin being inverted, and an esp32 being used, then swap all the ``data->mark``'s and ``data->space``'s (I'm just being dramatic lol)
2. Catch if an esp32 is using an inverted output as a transmitter, and if so, have it fallback to using the esp8266 ir_transmit implementation - I have tested this and it works, I will submit a pull request shortly.
- 2.5. Wait for a newer version of rmt.h to hit ``platformio/framework-arduinoespressif32``, then attempt to fix this properly

### What is version of ESPHome has the issue?

v1.19.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

wemos_d1_mini32

### Component causing the issue

remote_transmitter
