### ISSUE TITLE
Is it possible to get WiFi signal sensor value using REST API?

### ISSUE THREAD

**Issue by 5tan** [esphome/issues#2242]
### The problem

Is it possible to get WiFi signal sensor value using REST API?

I was trying to GET following endpoints:

* ` /wifi_signal/wifi_signal/value`
* ` /sensor/wifi_signal_sensor/value`
* `/wifi_signal/wifi_signal_sensor/value`

But I get either 500 (Internal server error) or 401 (Unauthorized). Credentials are correct, I am able to GET other sensor readings. 

### What is version of ESPHome has the issue?

1.19.4

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

sonoff_sv

### Component causing the issue

sensor/wifi_signal, web_server

### Example YAML snippet

```yaml
sensor:
  - platform: wifi_signal
    name: WiFi signal
    id: wifi_signal_sensor
    update_interval: 1
```
