### ISSUE TITLE
ESPHome does not respect 'manual_ip' setting if 'networks' is given

### ISSUE THREAD

**Issue by tempura-san** [esphome/issues#2247]
### The problem

In the `wifi` section giving a subnode `networks` (even in case only one network is given, what makes the `networks` basically useless, but it is a valid configuration) will force resolution to `.local` addresses only - which fails for me (Docker installation). Expectation is, that the `static_ip` set in the YAML was used - as described in https://esphome.io/components/wifi.html#manual-ips:

> When a manual IP is in your configuration, the OTA process will automatically choose that as the target for the upload.

If the `networks` entry is removed (and only a single network is present) flashing is working fine again.

### What is version of ESPHome has the issue?

v1.19.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

does not matter

### Component causing the issue

does not apply

### Example YAML snippet

```yaml
wifi:
  networks: # if this is omitted, everything is working fine
    ssid: FOOBAR
    password: foopass
      manual_ip:
      static_ip: 192.168.1.42
      gateway:   192.168.1.1
      dns1:      192.168.1.1
      dns2:      192.168.1.2
      subnet:    255.255.255.0
```

### Anything in the logs that might be useful for us?

```txt
...
INFO Reading configuration esp_node.yaml...
INFO Resolving IP address of esp_node.local
ERROR Error resolving IP address of esp_node.local. Is it connected to WiFi?
ERROR (If this error persists, please set a static IP address: https://esphome.io/components/wifi.html#manual-ips)
ERROR Error resolving IP address: Error resolving address with mDNS: Did not respond. Maybe the device is offline., [Errno -2] Name or service not known
...
```

### Additional information

While the YAML configuration above is valid (it compiles and no error is reported) it is **wrong**(?). Bringing the `manual_ip` on the `networks` level will make the snippet work.

So the question is, if it is okay for `manual_ip` to be accepted in the `networks` section (according to the docs it is not listed as subnode)? If not then the parser is missing this one, if yes and it can then be given per network - which one is to take?
