### ISSUE TITLE
esp8266 Couldn't resolve .local zone

### ISSUE THREAD

**Issue by twocolors** [esphome/issues#2253]
### The problem

```
[W][mqtt:137]: Couldn't resolve IP address for 'mqtt.local'!
[W][mqtt:137]: Couldn't resolve IP address for 'mqtt.local'!
```

On ESP32 all work fine

### What is version of ESPHome has the issue?

1.20.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
mqtt:
  broker: 192.168.0.14
#  broker: mqtt.local
  discovery: false
  topic_prefix: esphome/${device_name}
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
