### ISSUE TITLE
Globals String array not returning valid values

### ISSUE THREAD

**Issue by soloam** [esphome/issues#2256]
### The problem

I tried to declare a globals String array, and the return is not what I expected:

```yaml
globals:
  - id: allowed_list
    type: String[2]
    initial_value: '{"1234567890-100-1","0987654321-100-1"}'
```

When I check it on the lamda:

```c++
  //Inside for loop
  uuid_t = id(allowed_list)[x];
  uuid_t.replace("-","");
  uuid_t.toLowerCase();
  
  ESP_LOGD("ble_adv", "Testing %s", uuid_t.c_str());
```
uuid_t is emty, no value is printed

But if I do all in the lamda

```c++
//Declaration
String allowed_list[2] = {"1234567890-100-1","0987654321-100-1"};
```
...

```c++
  //Inside for loop
  uuid_t = allowed_list[x];
  uuid_t.replace("-","");
  uuid_t.toLowerCase();
  
  ESP_LOGD("ble_adv", "Testing %s", uuid_t.c_str());
```
This works Ok

### What is version of ESPHome has the issue?

v1.19.1

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

globals

### Example YAML snippet

```yaml
globals:
  - id: allowed_list
    type: String[2]
    initial_value: '{"1234567890-100-1","0987654321-100-1"}'
```
