### ISSUE TITLE
Condition api.connected is unreliable

### ISSUE THREAD

**Issue by patfelst** [esphome/issues#2260]
### The problem

Waiting for condition `api.connected` is unreliable. I'm using it to turn on a HA switch via the API when my ESP32 boots (wakes) from deep sleep. 

The problem is it never works (the switch in HA isn't turned on) unless I put in a 1s delay after the condition becomes true. With a 2s delay, it works 8 out of 10 times. But it's enough to be annoying.

```yaml
esphome:
  name: ttgo-iron-timer
  platform: ESP32
  board: esp32dev
  on_boot:
    priority: -500
    then:
      - wait_until:
          api.connected:
      - delay: 2s
      - homeassistant.service:
          service: switch.turn_on
          data:
            entity_id: $switch_name
      - globals.set:
          id: api_connected
          value: 'true'
      - globals.set:
          id: countdown
          value: '300'
```
I've found a 100% reliable method is to define a dummy sensor that uses platform `homeassistant`, and then in a lambda, check for the `sensor.has_state()` to become true.

```yaml
interval:
  - interval: 1sec
    then:
      - if:
          condition:
            lambda: |-
              // Use a sensor state to know when API is connected, api.connected condition is unreliable
              if (!id(api_connected) && id(temperature).has_state()) {
                id(countdown) = 300;
                id(api_connected) = true;
                return true;
              }
              else
                return false;
          then:
            - homeassistant.service:
                service: switch.turn_on
                data:
                  entity_id: $switch_name
```

### What is version of ESPHome has the issue?

v1.20.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

Lilygo TTGO

### Component causing the issue

api

### Example YAML snippet

```yaml
See above
```
