### ISSUE TITLE
color_brightness for light.addressable_set gives an error

### ISSUE THREAD

**Issue by denes44** [esphome/issues#2266]
### The problem

I got the following error message:
`[color_brightness] is an invalid option for [light.addressable_set]. Please check the indentation.`

Although the manual says, that the color_brightness is a valid configuration variable for the light.addressable_set action:
[https://esphome.io/components/light/index.html#light-addressable-set-action](url)

### What is version of ESPHome has the issue?

1.20.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
on_turn_on:
      - light.addressable_set:
          id: led_strip
          range_from: 1
          range_to: 1
          color_brightness: !lambda ‘return id(status_led_brightness);'
          red: 100%
          green: 50%
          blue: 0%
    on_turn_off:
      - light.addressable_set:
          id: led_strip
          range_from: 1
          range_to: 1
          color_brightness: 0%
```

### Additional information

The platform is neopixelbus.
