### ISSUE TITLE
NeoPixelBus doesn't get updated for addressable effects

### ISSUE THREAD

**Issue by ActuallyRuben** [esphome/issues#227]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 ESP-12 type board (using nodemcu as platform in the config)

**Affected component:**

[NeoPixelBus light](https://esphome.io/components/light/neopixelbus.html)

**Description of problem:**
Addressable light effects do not get updated properly. They only seem to update at random (couple second) intervals, or immediately when sending a turn_on event.
Normal effects do work as intended.

**Problem-relevant YAML-configuration entries:**
```yaml
light:
 - platform: neopixelbus
   name: "Complete LED strip"
   id: ledstrip
   num_leds: 93
   pin: GPIO3
 - platform: partition
   name: "LED strip top"
   segments:
    - id: ledstrip
      from: 0
      to: 87
   effects:
    - addressable_rainbow:
    - addressable_color_wipe:
    - random:
         transition_length: 10s
         update_interval: 10s
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
I tried fixing this issue myself. By inserting `ESP_LOGD(TAG, "Updating LEDstrip");` in the loop method of the component, just before `this->controller_->Show();`. (On line 90 in [this file](https://github.com/esphome/esphome-core/blob/dev/src/esphome/light/neo_pixel_bus_light_output.tcc) to be specific), the issue resolves itself, but of course then your log gets filled with useless 'Updating LEDstrip' statements. I'm not sure how it's related, but the bug seems to be related to the logger. I found issue #182, could it be related?
