### ISSUE TITLE
Please move thermostat::default_mode to climate so that it is available in all derived components

### ISSUE THREAD

**Issue by ptr727** [esphome/issues#2270]
### The problem

Climate controllers start in the off state, one must use `on_boot` to set the desired default state, [cumbersome](https://github.com/esphome/issues/issues/2233).

`default_mode` was [added](https://github.com/esphome/esphome/pull/2032), but it was added to `thermostat`, so `bang_bang` still needs to use `on_boot` to set the default state.

Please move `default_mode` to `climate` such that all derived components get the benefit.

### What is version of ESPHome has the issue?

1.21-dev

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

Sonoff TH10

### Component causing the issue

thermostat

### Example YAML snippet

```yaml
# https://esphome.io/components/climate/index.html
climate:

  # https://esphome.io/components/climate/bang_bang.html
  - platform: bang_bang
    name: ${device_name}_bangbang
    id: bangbang
    sensor: recirc_temp
    default_mode: HEAT
    default_target_temperature_low: ${target_temperature_low}
    default_target_temperature_high: ${target_temperature_high}
    heat_action:
      - logger.log: "BangBang : Heat Action, Turning Relay On."
      - switch.turn_on: relay
    idle_action:
      - logger.log: "BangBang : Idle Action, Turning Relay Off."
      - switch.turn_off: relay
    visual:
      min_temperature: 20.0
      max_temperature: 50.0
      temperature_step: 0.5
```
```


### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/sonoff_th10_hot_recirc_pump.yaml...
INFO Detected timezone 'PST' with UTC offset -8 and daylight saving time from 13 March 02:00:00 to 06 November 02:00:00
Failed config

climate.bang_bang: [source /config/sonoff_th10_hot_recirc_pump.yaml:146]
  platform: bang_bang
  name: sonoff_th10_hot_recirc_pump_bangbang
  id: bangbang
  sensor: recirc_temp
  
  [default_mode] is an invalid option for [climate.bang_bang]. Please check the indentation.
  default_mode: HEAT [source /config/sonoff_th10_hot_recirc_pump.yaml:150]
  default_target_temperature_low: 30.0
  default_target_temperature_high: 40.0
  heat_action: 
    - logger.log: BangBang : Heat Action, Turning Relay On.
    - switch.turn_on: relay
  idle_action: 
    - logger.log: BangBang : Idle Action, Turning Relay Off.
    - switch.turn_off: relay
  visual: 
    min_temperature: 20.0
    max_temperature: 50.0
    temperature_step: 0.5
```
```


### Additional information

_No response_
