### ISSUE TITLE
SGP40 self test failed

### ISSUE THREAD

**Issue by ddv2005** [esphome/issues#2276]
### The problem

SGP40 sensor does not work because self test failed. I guess that it is because SGP40Component::update() issued between write_command_(SGP40_CMD_SELF_TEST) and scheduled read self test data.  

### What is version of ESPHome has the issue?

1.20.X

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

TTGO T-Display

### Component causing the issue

SGP40

### Example YAML snippet

```yaml
esphome:
  name: vocsensor
  platform: ESP32
  board: featheresp32

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: XXX

wifi:
  ssid: XXX
  password: XXX

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: XXX
    password: XXX

captive_portal:

#####<<: !include base.yaml


font:
  - file: 'fonts/slkscr.ttf'
    id: font_slkscr_8
    size: 8
    glyphs: "!%()+,-/_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"
  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font_bebas_48
    size: 48
  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font_bebas_56
    size: 56
  - file: 'fonts/arial.ttf'
    id: font_arial_12
    size: 12

# COLORS ARE IN RGB565 format
globals:
  - id: color_red
    type: int
    restore_value: no
    initial_value: '0xF800'  
  - id: color_green
    type: int
    restore_value: no
    initial_value: '0x07E0'
  - id: color_blue
    type: int
    restore_value: no
    initial_value: '0x001F'
  - id: color_yellow
    type: int
    restore_value: no
    initial_value: '0xFFE0'
  - id: color_yellow_alt
    type: int
    restore_value: no
    initial_value: '0xFE40'
  - id: color_cyan
    type: int
    restore_value: no
    initial_value: '0x07FF'
  - id: color_orange
    type: int
    restore_value: no
    initial_value: '0xFC20'
  - id: color_teal_blue
    type: int
    restore_value: no
    initial_value: '0x04AE'
  - id: color_beige
    type: int
    restore_value: no
    initial_value: '0xFFBD'



# OPTIONAL: Another way to set colors
substitutions:
  RED: '(0x1F << 11)'
  GREEN: '(0x3F << 5)'
  BLUE: '(0x1F << 0)'
  YELLOW: '(0x1F << 11) | (0x3F << 5)'
  CYAN: '(0x3F << 5) | (0x1F << 0)'
  MAGENTA: '(0x1F << 11) | (0x1F << 0)'
  WHITE: '(0x1F << 11) | (0x3F << 5) | (0x1F << 0)'
  GRAY: '(0x10 << 11) | (0x20 << 5) | (0x10 << 0)'

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a
  
sensor:
  - platform: shtcx
    temperature:
      name: "Kitchen Temperature"
      id: shtcx_temp
    humidity:
      name: "Kitchen Humidity"
      id: shtcx_hum
    address: 0x70
    update_interval: 5s
  - platform: sgp40
    name: "Kitchen VOC"
    id: voc
    update_interval: 5s
    compensation:
      humidity_source: shtcx_temp
      temperature_source: shtcx_hum    
time:
  - platform: homeassistant
    id: esptime

# We can still control the backlight independently
switch:
  - platform: gpio
    pin: GPIO4
    name: "Backlight"
    id: backlight              


display:
  - platform: st7789v
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90°
    #brightness: 0.5
    update_interval: 5s
    lambda: |-
      if (id(shtcx_temp).has_state()) {
        it.printf(4, 4, id(font_arial_12), id(color_teal_blue), "%.2f C, %.2f %%", id(shtcx_temp).state, id(shtcx_hum).state);
      }
      if (id(voc).has_state()) {
        it.printf(16, 72, id(font_bebas_56), id(color_green), "%.0f", id(voc).state);
      }
```

### Anything in the logs that might be useful for us?

```txt
␛[0;35m[C][sgp40:010]: Setting up SGP40...␛[0m
␛[0;36m[D][sgp40:026]: Serial Number: 51173289␛[0m
␛[0;36m[D][sgp40:049]: Product version: 0x20␛[0m
␛[0;36m[D][sgp40:081]: selfTest started␛[0m
␛[0;35m[C][st7789v:010]: Setting up SPI ST7789V...␛[0m
␛[0;35m[C][wifi:037]: Setting up WiFi...␛[0m
␛[0;36m[D][wifi:380]: Starting scan...␛[0m
␛[0;36m[D][sgp40:227]: Sensor has not collected enough samples yet. (1/90) VOC index is: 0␛[0m
␛[0;33m[W][i2c:086]: Requesting 3 bytes from 0x59 failed!␛[0m
␛[0;36m[D][sgp40:092]: selfTest read_data_ failed␛[0m
␛[1;31m[E][component:096]: Component was marked as failed.␛[0m
```
