### ISSUE TITLE
mDNS binds to multiple interfaces

### ISSUE THREAD

**Issue by kennethso168** [esphome/issues#2278]
### The problem

I have an issue similar to this [solved home assistant issue](https://github.com/home-assistant/core/issues/35031). In my case, esphome will bind to multiple interfaces on port 5353 (mDNS).
This leads to UDP4 socket memory issues and UDP4 lost packets.
Below is a netstat extract that shows the issue on my system. The PID is the one used by esphome. The other redundant interfaces that it binds to get choked by packets. Issue is clear if you have a tool to monitor the health of your system, like netdata.

### What is version of ESPHome has the issue?

1.20.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Anything in the logs that might be useful for us?

```txt
$ sudo netstat -ulpna
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
udp        0      0 192.168.0.211:68        192.168.0.1:67          ESTABLISHED 4404/NetworkManager 
udp        0      0 0.0.0.0:111             0.0.0.0:*                           1/init              
udp        0      0 172.25.255.255:137      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.25.0.1:137          0.0.0.0:*                           5226/nmbd           
udp        0      0 172.21.255.255:137      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.21.0.1:137          0.0.0.0:*                           5226/nmbd           
udp        0      0 172.20.255.255:137      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.20.0.1:137          0.0.0.0:*                           5226/nmbd           
udp        0      0 172.19.255.255:137      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.19.0.1:137          0.0.0.0:*                           5226/nmbd           
udp        0      0 172.18.255.255:137      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.18.0.1:137          0.0.0.0:*                           5226/nmbd           
udp        0      0 172.17.255.255:137      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.17.0.1:137          0.0.0.0:*                           5226/nmbd           
udp        0      0 192.168.0.255:137       0.0.0.0:*                           5226/nmbd           
udp        0      0 192.168.0.211:137       0.0.0.0:*                           5226/nmbd           
udp        0      0 0.0.0.0:137             0.0.0.0:*                           5226/nmbd           
udp        0      0 172.25.255.255:138      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.25.0.1:138          0.0.0.0:*                           5226/nmbd           
udp        0      0 172.21.255.255:138      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.21.0.1:138          0.0.0.0:*                           5226/nmbd           
udp        0      0 172.20.255.255:138      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.20.0.1:138          0.0.0.0:*                           5226/nmbd           
udp        0      0 172.19.255.255:138      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.19.0.1:138          0.0.0.0:*                           5226/nmbd           
udp        0      0 172.18.255.255:138      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.18.0.1:138          0.0.0.0:*                           5226/nmbd           
udp        0      0 172.17.255.255:138      0.0.0.0:*                           5226/nmbd           
udp        0      0 172.17.0.1:138          0.0.0.0:*                           5226/nmbd           
udp        0      0 192.168.0.255:138       0.0.0.0:*                           5226/nmbd           
udp        0      0 192.168.0.211:138       0.0.0.0:*                           5226/nmbd           
udp        0      0 0.0.0.0:138             0.0.0.0:*                           5226/nmbd           
udp        0      0 0.0.0.0:631             0.0.0.0:*                           4633/cups-browsed   
udp        0      0 0.0.0.0:50001           0.0.0.0:*                           4672/anydesk        
udp        0      0 0.0.0.0:51820           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:51952           0.0.0.0:*                           22618/firefox       
udp        0      0 127.0.0.1:52179         127.0.0.1:52179         ESTABLISHED 7607/postgres       
udp        0      0 0.0.0.0:36772           0.0.0.0:*                           4397/avahi-daemon:  
udp        0      0 0.0.0.0:37032           0.0.0.0:*                           8742/python3        
udp        0      0 0.0.0.0:37628           0.0.0.0:*                           8742/python3        
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           8742/python3        
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           9924/node-red       
udp   1252608      0 0.0.0.0:5353            0.0.0.0:*                           7603/python3        
udp   1252608      0 0.0.0.0:5353            0.0.0.0:*                           7603/python3        
udp   1252608      0 0.0.0.0:5353            0.0.0.0:*                           7603/python3        
udp   1252608      0 0.0.0.0:5353            0.0.0.0:*                           7603/python3        
udp   1252608      0 0.0.0.0:5353            0.0.0.0:*                           7603/python3        
udp   1252608      0 0.0.0.0:5353            0.0.0.0:*                           7603/python3        
udp   1252608      0 0.0.0.0:5353            0.0.0.0:*                           7603/python3        
udp   1252608      0 0.0.0.0:5353            0.0.0.0:*                           7603/python3        
udp   1252608      0 0.0.0.0:5353            0.0.0.0:*                           7603/python3        
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           7603/python3        
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           4397/avahi-daemon:  
udp        0      0 0.0.0.0:38560           0.0.0.0:*                           8742/python3        
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           51539/netdata       
udp6       0      0 :::53                   :::*                                4643/nextdns        
udp6       0      0 :::111                  :::*                                1/init              
udp6       0      0 :::51820                :::*                                -                   
udp6       0      0 :::5353                 :::*                                4397/avahi-daemon:  
udp6       0      0 :::40870                :::*                                4397/avahi-daemon: 

$ ps -p 7603
    PID TTY          TIME CMD
   7603 ?        00:00:01 esphome

I have this in the docker logs when the docker container starts. Not sure if this is related

WARNING Exception occurred:


Traceback (most recent call last):


  File "/usr/src/app/esphome/zeroconf.py", line 770, in send


    bytes_sent = s.sendto(packet, 0, (_MDNS_ADDR, _MDNS_PORT))


OSError: [Errno 126] Required key not available


INFO 200 GET / (127.0.0.1) 14.23ms
```

### Additional information

```
$ inxi -Fxz

System:    Kernel: 5.8.0-63-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.0.5 Distro: Linux Mint 20.2 Uma 
           base: Ubuntu 20.04 focal 
Machine:   Type: Desktop System: Gigabyte product: B550M AORUS PRO v: N/A serial: <filter> 
           Mobo: Gigabyte model: B550M AORUS PRO v: x.x serial: <filter> UEFI: American Megatrends LLC. v: F13g 
           date: 03/25/2021 
Battery:   Device-1: hidpp_battery_0 model: Logitech Wireless Mouse MX Master 3 charge: 100% (should be ignored) 
           status: Discharging 
CPU:       Topology: 6-Core model: AMD Ryzen 5 PRO 4650G with Radeon Graphics bits: 64 type: MT MCP arch: Zen rev: 1 
           L2 cache: 3072 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 88631 
           Speed: 1385 MHz min/max: 1400/3700 MHz Core speeds (MHz): 1: 1214 2: 1364 3: 1397 4: 1396 5: 1566 6: 1397 7: 1397 
           8: 1397 9: 1216 10: 1441 11: 1587 12: 1396 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Renoir vendor: Gigabyte driver: amdgpu v: kernel bus ID: 06:00.0 
           Display: x11 server: X.Org 1.20.9 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa tty: N/A 
           OpenGL: renderer: AMD RENOIR (DRM 3.38.0 5.8.0-63-generic LLVM 11.0.0) v: 4.6 Mesa 20.2.6 direct render: Yes 
Audio:     Device-1: Advanced Micro Devices [AMD/ATI] driver: snd_hda_intel v: kernel bus ID: 06:00.1 
           Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio vendor: Gigabyte driver: snd_hda_intel v: kernel 
           bus ID: 06:00.6 
           Sound Server: ALSA v: k5.8.0-63-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Gigabyte driver: r8169 v: kernel 
           port: f000 bus ID: 04:00.0 
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           IF-ID-1: br-09c49af21c66 state: up speed: 10000 Mbps duplex: unknown mac: <filter> 
           IF-ID-2: br-1693687d8359 state: down mac: <filter> 
           IF-ID-3: br-2f72a724a169 state: up speed: 10000 Mbps duplex: unknown mac: <filter> 
           IF-ID-4: br-52dbb7209cdd state: down mac: <filter> 
           IF-ID-5: br-ed9844faf087 state: up speed: 10000 Mbps duplex: unknown mac: <filter> 
           IF-ID-6: docker0 state: down mac: <filter> 
           IF-ID-7: veth220d977 state: up speed: 10000 Mbps duplex: full mac: <filter> 
           IF-ID-8: veth3132898 state: up speed: 10000 Mbps duplex: full mac: <filter> 
           IF-ID-9: vethb749792 state: up speed: 10000 Mbps duplex: full mac: <filter> 
           IF-ID-10: wg0 state: unknown speed: N/A duplex: N/A mac: N/A 
Argument "fuse.mergerfs" isn't numeric in numeric eq (==) at /usr/bin/inxi line 12193.
Drives:    Local Storage: total: 11.37 TiB used: 470.05 GiB (4.0%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO Plus 500GB size: 465.76 GiB temp: 43 C 
           ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 970 EVO Plus 500GB size: 465.76 GiB temp: 36 C 
           ID-3: /dev/sda vendor: Seagate model: ST4000VN008-2DR166 size: 3.64 TiB temp: 34 C 
           ID-4: /dev/sdb vendor: Seagate model: ST4000VN008-2DR166 size: 3.64 TiB temp: 33 C 
           ID-5: /dev/sdc vendor: Seagate model: ST4000VN008-2DR166 size: 3.64 TiB temp: 32 C 
RAID:      Device-1: md0 type: mdraid status: active Components: online: nvme0n1p2~c1 nvme1n1p2~c0 
           Info: raid: mirror blocks: 2094080 report: 2/2 UU chunk size: N/A 
           Device-2: bpool type: zfs status: ONLINE size: 1.88 GiB free: 1.08 GiB Components: online: N/A 
           Device-3: dump type: zfs status: ONLINE raid: no-raid size: 3.62 TiB free: 3.41 TiB Components: online: N/A 
           Device-4: rpool type: zfs status: ONLINE size: 460.00 GiB free: 382.00 GiB Components: online: N/A 
           Device-5: tank type: zfs status: ONLINE size: 3.62 TiB free: 3.42 TiB Components: online: N/A 
Partition: ID-1: / size: 375.61 GiB used: 8.41 GiB (2.2%) fs: zfs raid: rpool/ROOT/ubuntu_37k1ls 
           ID-2: /boot size: 1.56 GiB used: 612.6 MiB (38.4%) fs: zfs raid: bpool/BOOT/ubuntu_37k1ls 
           ID-3: /var/log size: 367.63 GiB used: 441.1 MiB (0.1%) fs: zfs raid: rpool/ROOT/ubuntu_37k1ls/var/log 
           ID-4: swap-1 size: 2.00 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/md0 
Sensors:   System Temperatures: cpu: 33.9 C mobo: 41.0 C gpu: amdgpu temp: 31 C 
           Fan Speeds (RPM): cpu: 1194 mobo: 627 
           Voltages: 12v: 12.17 5v: 5.13 3.3v: 3.31 vbat: 3.19 
Info:      Processes: 801 Uptime: 47m Memory: 30.82 GiB used: 11.72 GiB (38.0%) Init: systemd runlevel: 5 Compilers: 
           gcc: 9.3.0 Shell: bash v: 5.0.17 inxi: 3.0.38
```

The docker-compose file used to start my whole home assistant stack:
```
version: "3.7"

services:
    postdb1:
        container_name: postdb1
        network_mode: host
        restart: unless-stopped
        image: postgres:13.3
        volumes:
            - /opt/appdata/homeassistant/postdb:/var/lib/postgresql/data
            - /etc/localtime:/etc/localtime:ro
            - /etc/passwd:/etc/passwd:ro
        environment:
            - POSTGRES_USER=homeassistant
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
        user: 1000:1000
    mqtt:
        image: eclipse-mosquitto:latest
        container_name: mqtt
        restart: unless-stopped
        ports:
          - 1883:1883
          - 9001:9001
        volumes:
          - /opt/appdata/mqtt/data:/mosquitto/data
          - /opt/appdata/mqtt/config:/mosquitto/config
          - /opt/appdata/mqtt/log:/mosquitto/log
        network_mode: "host"
        environment:
          - TZ=Asia/Hong_Kong
    homeassistant: 
        image: ghcr.io/linuxserver/homeassistant:latest
        container_name: homeassistant
        network_mode: host
        depends_on: 
            - postdb1
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Hong_Kong
        volumes:
            - /opt/appdata/homeassistant/config:/config
        ports:
            - 8123:8123
        restart: unless-stopped
    node-red:
        image: nodered/node-red:latest
        container_name: node-red
        network_mode: host
        depends_on:
          - homeassistant
        environment:
          - TZ=Asia/Hong_Kong
        ports:
          - "1880:1880"
          # Join
          - "1820:1820"
        volumes:
          - /opt/appdata/nodered:/data
        user: 1000:1000
        restart: unless-stopped
    esphome:
        image: esphome/esphome:latest
        container_name: esphome
        network_mode: host
        environment:
          - TZ=Asia/Hong_Kong
        ports:
          - "6052:6052"
        volumes:
          - /opt/appdata/esphome:/config
        restart: unless-stopped
```

The UDP Sockets Memory dropped significantly after I stopped the esphome container
![image](https://user-images.githubusercontent.com/5262487/127518683-75c8ca39-0f96-4aa6-a630-55526d7e8766.png)
