### ISSUE TITLE
Camera image glitches at highest 2 resolutions

### ISSUE THREAD

**Issue by SaturnusDJ** [esphome/issues#2281]
### The problem

Image glitches for ESP32CAM.

ESPHome 1.16.2 and Home Assistant 2021.5.5. No problem.

Decided to upgrade ESP devices but got image glitches for ESP32CAMs. With upgrading and downgrading it became clear that the problem happens since ESPHome 1.19.0. The issue is not present in ESPHome 1.18.0. The breaking change about cam for 1.19.0 should be unrelated to this issue. A bug fix for image problems in HA (https://github.com/home-assistant/core/pull/52738) surprisingly also did not fix this issue. In other words, still issues in HA 2021.7.4 with ESPHome 1.19.0 and ESPHome 1.20.3 (and very likely everything in between).

640x480 (default), 800x600 and 1024x768 did work without problems in 1.19.0 and HA 2021.5.5. The higher resolutions of 1280x1024 and 1600x1200 resulted in the glitches.

The stream is a mix of normal images and broken images, see these 2 examples:

https://i.ibb.co/Zzd2MSP/1.png
https://i.ibb.co/7yjYVMy/2.png

It could be that the issue is on Home Assistant's side, but since the problems started from ESPHome 1.19.0, the issue is reported here first.

### What is version of ESPHome has the issue?

v1.19.0 to v1.20.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

ESP32CAM

### Component causing the issue

esp32_camera

### Example YAML snippet

```yaml
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: Camera front door
  resolution: 1600x1200
#  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: false
#  max_framerate: 2 fps
#  idle_framerate: 0.1 fps
```
