### ISSUE TITLE
Unable to sync light effects

### ISSUE THREAD

**Issue by tungmeister** [esphome/issues#2283]
### The problem

I have a 3 button light switch with controllable LEDs behind each button. I have a mode I've setup whereby long pressing the middle button activates a mode in which I can control the speed of a ceiling fan. This mode uses the pulse effect on the LEDs behind buttons 1 and 3 to indicate they can be pressed to adjust the speed. Once the lowest/highest speed is reached the effect stops on the corresponding button. The problem arises when the speed is then increased/decreased re-enabling the button  LED effect. At this point, the pulse effect will be out of sync between the 2 buttons used to adjust ithe speed and from the documentation I can't identify any way to link the effects between the 2 LEDs so that when one is re-enabled it matches the pulse of the other one. see the attached code for further explanation. 

I've tried using:

```
              - wait_until: 
                - lambda: 'return id(button_led_3).current_values.get_brightness() <= 0.1;' # or == 0.0
```

to try and sync when the LED gets turned back on but this doesn't appear to be actually reporting the brightness (did some logging and it looked like it was always 1.0?)

### What is version of ESPHome has the issue?

1.21 dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

esp8255

### Component causing the issue

light

### Example YAML snippet

```yaml
- platform: homeassistant
    name: fan speed
    id: fanspeed
    internal: true
    entity_id: input_number.fan_current_speed
    on_value:
      then:
        - if:
            condition:
              and:
              - lambda: 'return id(speedcontrol) == true;'
              - lambda: 'return id(fanspeed).state == 1;'
            then:
              - light.turn_off: button_led_1
              - globals.set:
                  id: bottom
                  value: 'true'
        - if:
            condition:
              and:
              - lambda: 'return id(speedcontrol) == true;'
              - lambda: 'return id(fanspeed).state == 6;'
            then:
              - light.turn_off: button_led_3
              - globals.set:
                  id: top
                  value: 'true'
        - if:
            condition:
              and:
              - lambda: 'return id(speedcontrol) == true;'
              - lambda: 'return id(fanspeed).state > 1;'
              - lambda: 'return id(bottom) == true;'
            then:
              - light.turn_on:
                  id: button_led_1
                  effect: pulsing
        - if:
            condition:
              and:
              - lambda: 'return id(speedcontrol) == true;'
              - lambda: 'return id(fanspeed).state < 6;'
              - lambda: 'return id(top) == true;'
            then:
              - light.turn_on:
                  id: button_led_3
                  effect: pulsing

...
output:
  - platform: esp8266_pwm
    id: led1
    pin: GPIO16
    inverted: True
  - platform: esp8266_pwm
    id: led2
    pin: GPIO14
    inverted: True
  - platform: esp8266_pwm
    id: led3
    pin: GPIO01
    inverted: True
...
light:
  - platform: monochromatic
    name: "Blind LED"
    output: led1
    internal: true
    id: button_led_1
    default_transition_length: 0.5s
    effects:
      - pulse:
          name: "pulsing"
          transition_length: 0.5s
          update_interval: 0.5s
  - platform: monochromatic
    name: "Fan LED"
    output: led2
    internal: true
    id: button_led_2
    default_transition_length: 0.5s
  - platform: monochromatic
    name: "Light LED"
    output: led3
    internal: true
    id: button_led_3
    default_transition_length: 0.5s
    effects:
      - pulse:
          name: "pulsing"
          transition_length: 0.5s
          update_interval: 0.5s
```

### Additional information
