### ISSUE TITLE
http_request component fail with 1.20.1 -> 1.20.3

### ISSUE THREAD

**Issue by pengelen** [esphome/issues#2284]
### The problem

Since version 1.20.1 when using http_request.post action the ESP32 reboots or freezes for while. 
Version 1.20.0 works fine.

### What is version of ESPHome has the issue?

v1.20.1 - v1.20.2 - v1.20.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

http_request

### Example YAML snippet

```yaml
http_request:
  useragent: esphome/device
  timeout: 3s

binary_sensor:
  - platform: nextion
    page_id: 1
    component_id: 3
    name: "Nextion Component 3 Touch"
    on_press:
      then:
        - http_request.post:
            url: http://192.168.x.x/api/system/commands/core/shutdown
            headers:
              X-Api-Key: !secret octoprintAPI2
        - delay: 30s
        - switch.turn_off: "relay4"
        - switch.turn_off: "relay2"
```

### Anything in the logs that might be useful for us?

```txt
On v1.20.3:
[D][nextion:433]: Got touch page=1 component=3 type=PRESS
[D][binary_sensor:036]: 'Nextion Component 3 Touch': Sending state ON
[E][WiFiClient.cpp:258] connect(): socket error on fd 59, errno: 113, "Software caused connection abort"
[W][http_request:062]: HTTP Request failed; URL: http://192.168.x.x/api/system/commands/core/shutdown; Error: connection refused

-Then reboot or freeze for +/- 55 seconds or with v.1.20.1 freeze till power-reset.
-Also freeze when octoprint is online and reachable.

On v1.20.0:

When octoprint is online:
[D][nextion:433]: Got touch page=1 component=3 type=PRESS
[D][binary_sensor:036]: 'Nextion Component 3 Touch': Sending state ON
[D][http_request:074]: HTTP Request completed; URL: http://192.168.x.x/api/system/commands/core/shutdown; Code: 204
[D][nextion:433]: Got touch page=1 component=3 type=RELEASE
[D][binary_sensor:036]: 'Nextion Component 3 Touch': Sending state OFF

When octoprint is offline it disconnects for 5 seconds and works again:
[D][nextion:433]: Got touch page=1 component=3 type=PRESS
[D][binary_sensor:036]: 'Nextion Component 3 Touch': Sending state ON
[E][WiFiClient.cpp:258] connect(): socket error on fd 55, errno: 113, "Software caused connection abort"
[W][http_request:062]: HTTP Request failed; URL: http://192.168.x.x/api/system/commands/core/shutdown; Error: connection refused
[D][nextion:433]: Got touch page=1 component=3 type=RELEASE
[D][binary_sensor:036]: 'Nextion Component 3 Touch': Sending state OFF
[D][api:067]: Disconnecting ESPHome v1.20.0 (192.168.x.x)
[D][api:067]: Disconnecting Home Assistant 2021.7.4 (192.168.x.x)
[D][api:067]: Disconnecting 192.168.x.x
[D][api:067]: Disconnecting 192.168.x.x
[D][api:067]: Disconnecting 192.168.x.x
[D][dht:048]: Got Temperature=24.2°C Humidity=57.1%
[D][sensor:127]: 'ESP12 Temperature': Sending state 24.20000 °C with 1 decimals of accuracy
[D][sensor:127]: 'ESP12 Humidity': Sending state 57.10000 % with 0 decimals of accuracy
[D][api.connection:670]: Client 'Home Assistant 2021.7.4 (192.168.x.x)' connected successfully!
```
