### ISSUE TITLE
CustomAPIDevice broken

### ISSUE THREAD

**Issue by wburgers** [esphome/issues#2288]
### The problem

I want to compile a custom component which extends the CustomAPIDevice class.
Even the examples on the custom component page are not working (https://esphome.io/custom/custom_component.html).

When compiling, the following error message is shown:
```
In file included from src/main.cpp:10:0:
src/test.h:3:66: error: expected class-name before '{' token
 class CustomNativeAPI : public Component, public CustomAPIDevice {
                                                                  ^
```

I also tried the test case in custom.h (https://github.com/esphome/esphome/blob/dev/tests/custom.h) which also errors.

### Which version of ESPHome has the issue?

1.20.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

CustomAPIDevice

### Example YAML snippet

```yaml
esphome:
  name: test
  platform: ESP8266
  board: d1_mini
  includes:
    - test.h # test.h contains the CustomNativeAPI copied from https://github.com/esphome/esphome/blob/dev/tests/custom.h

custom_component:
  - lambda: |-
      auto testcomponent = new CustomNativeAPI();
      return {testcomponent};
```
