### ISSUE TITLE
Template switch ignoring id, converting name instead

### ISSUE THREAD

**Issue by gitolicious** [esphome/issues#229]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff, Wemos D1 mini

**Affected component:**

https://esphome.io/components/switch/template.html

**Description of problem:**
When creating a template switch with both, `id` and `name`, the `id` is ignored. Instead an `id` is auto-generated from the `name`.
According to the [documentation](https://esphome.io/components/switch/template.html#configuration-variables), it should be possible to set the `id` manually:

> **id** (_Optional_, ID): Manually specify the ID used for code generation.

In below example, the switch will get the id `name`. This can be seen in the web server source code and in the HomeAssistant integrations and entities list.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test
  platform: ESP8266
  board: d1_mini

wifi: !include templates/wifi.yaml
api:
web_server:

switch:
  - platform: template
    id: id
    name: Name
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
When only an `id` is given, it is properly used for the switch id.
