### ISSUE TITLE
Power sensor not working with new HA Energy tab

### ISSUE THREAD

**Issue by LordBoos** [esphome/issues#2300]
### The problem

HA Energy configuration just won't allow me to use ESPHome sensor, even though I've followed the HA guide to set up the sensor by adding `state_class: measurement` and `device_class: power` to my sensor.

I also tried to completely remove the ESPHome integration and add it back - it didn't help. I also tried to create new sensor with new name - also didn't help.

Looks like this is a bug in ESPHome as Home Assistant guide tells me:

> You’re configuring a statistic but you couldn’t find your source in the dropdown? That’s caused by a bug in the integration providing the entity. Integrations need to configure their entities correctly so Home Assistant knows that we need to track statistics for it and how.
Open an issue with the author of the integration and link them to https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics.

### Which version of ESPHome has the issue?

v1.20.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Shelly Plug S - esp8285

### Component causing the issue

sensor, platform: hlw8012

### Example YAML snippet

```yaml
substitutions:
  # Higher value gives lower watt readout
  # current_res: '0.00215'
  current_res: '0.0022'
  # Lower value gives lower voltage readout
  voltage_div: '880'

esphome:
  name: plug_s_pracka
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

binary_sensor:
  - platform: gpio
    id: button
    internal: true
    pin:
      number: GPIO13
    on_press:
      - switch.toggle: relay

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led

switch:
  - platform: gpio
    pin: GPIO15
    id: relay
    name: 'Plug S Pračka'
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

status_led:
  pin:
    number: GPIO02
    inverted: true

sensor:
  - platform: uptime
    name: 'Plug S Pračka Uptime'
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: 'Plug S Pračka WiFi Signal'
    update_interval: 300s

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      state_class: measurement
      device_class: current
      name: 'Plug S Pračka Current'
      unit_of_measurement: 'A'
      accuracy_decimals: 3
      icon: mdi:flash-outline
      filters:
      - multiply: 1.85
    voltage:
      state_class: measurement
      device_class: voltage
      name: 'Plug S Pračka Voltage'
      unit_of_measurement: 'V'
      icon: mdi:flash-outline
    power:
      state_class: measurement
      device_class: power
      name: 'Plug S Pračka Power'
      unit_of_measurement: 'W'
      icon: mdi:flash-outline
    change_mode_every: 4
    update_interval: 1s
    
  - platform: adc
    pin: A0
    name: "Plug S Pračka ADC"
    update_interval: 10s
```
