### ISSUE TITLE
Automation Condition Error "Switch.is_on/off" when using 'Template Number'

### ISSUE THREAD

**Issue by 3ative** [esphome/issues#2305]
### The problem

Throws an error with condition, **switch.is_on/off**

_I hope this screencap is sufficient..._
E.G.
![Capture](https://user-images.githubusercontent.com/51385971/128635012-28e63753-69e6-477a-9dea-950beec4db18.JPG)

### Which version of ESPHome has the issue?

v1.20.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

Template Number

### Example YAML snippet

```yaml
number:
  - platform: template
    name: "Bedroom Curtains"
    update_interval: never
    optimistic: true
    min_value: 0
    max_value: 100
    step: 10
    on_value:
      if:
        condition:
          switch.is_on: test_swtich
        then:
          - stepper.set_target:
              id: curtain_motor_v2
              target: !lambda "return x *65;"
```
