### ISSUE TITLE
Rotary encoder connection via I/O expander (PCF8574)

### ISSUE THREAD

**Issue by cpluess** [esphome/issues#2306]
### The problem

I am trying to connect various rotary encoders via an i/o expander (pcf8574n) to a Wemos D1 mini. 

Creating input pins for the pcf8575 works smooth as silk but the issue is that the yaml file only allows to choose a pin from the wemos board (eg D1 & D2) for the rotary encoder input (eg. pin_a: D1)

I put this in the **issue** section since it feels like this wouldn't be much of an additional **feature** because all the necessary things are already in place. 

### Which version of ESPHome has the issue?

1.20.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

i2c

### Example YAML snippet

```yaml
# PCF8574 inputs
binary_sensor:
  - platform: gpio
    name: "PCF8574 Pin #0"
    pin:
      pcf8574: pcf8574_hub
      number: 0
      mode: INPUT
      inverted: false

# Can't use previously defined pcf8574 pins
sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_a: D1
    pin_b: D2
```

### Anything in the logs that might be useful for us?

```txt
"Can't resolve pin name "XYZ" for board d1_mini"
```
