### ISSUE TITLE
color temperature change with constant_brightness has no longer a constant brightness

### ISSUE THREAD

**Issue by malteger** [esphome/issues#2311]
### The problem

Starting with 1.21.0b1 the brightness of a cwww light during transitions is changing if you change the color temperature with `constant_brightness: true` (happens also for rgbww lights). In esphome 1.20 the brightness has been kept constant while doing the transition. This is most noticeable if you change the temperature from the lowest to the highest value or vice versa. outside of a transition the brightness is constant as in previous versions. 

It looks like both leds (cw and ww) start the transition and in the middle of the transition the light is significantly darker.

### Which version of ESPHome has the issue?

1.21.0b1 

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.8.3

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

cwww

### Example YAML snippet

```yaml
- platform: cwww
  name: ${bulbname}
  id: cwww_light
  warm_white: output_warm
  cold_white: output_cold
  cold_white_color_temperature: 6500K
  warm_white_color_temperature: 2700K
  constant_brightness: true
```
