### ISSUE TITLE
MQTT discovery does not contain state class

### ISSUE THREAD

**Issue by CornerBit** [esphome/issues#2312]
### The problem

The discovery JSON published over MQTT for sensors does not contain the `"state_class": "measurement"` field needed by home assistant to allow for statistics to be collected.

I have tried the following however neither of the components publish this field:
  
  * A template sensor with `state_class` set manually:
     ```yaml
      - platform: template
        name: "Template Sensor"
        lambda: |-
          return 42.0
        update_interval: 60s
        unit_of_measurement: "°C"
        device_class: "temperature"
        state_class: "measurement"
     ```
  * A pulse meter:
     ```yaml
      sensor:
        - platform: pulse_meter
          pin: 12
          unit_of_measurement: 'kW'
          name: 'Electricity Usage'
      ```

The `device_class` is correctly included but `last_reset_type` and `state_class` are missing. An example of the published discovery information is:

```json
{
   "device_class":"temperature",
   "unit_of_measurement":"°C",
   "name":"Template Sensor",
   "state_topic":"device/template_sensor/state",
   "availability_topic":"device/status",
   "unique_id":"...",
   "device":{
      ...
   }
}
```

### Which version of ESPHome has the issue?

1.20.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

MQTT
