### ISSUE TITLE
color_temp = 0 in home assistant

### ISSUE THREAD

**Issue by jbergler** [esphome/issues#2314]
### The problem

With the new color mode changes, I've noticed that Home Assistant forgets the color temperature of my RGBWW light.

```
# the home assistant state is wrong (color_temp = 0.0)
2021-08-12 17:05:25 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=light.arc_lamp, old_state=<state light.arc_lamp=on; min_mireds=161.2903289794922, max_mireds=357.1428527832031, supported_color_modes=['color_temp', 'rgb'], color_mode=color_temp, brightness=71, color_temp=0.0, friendly_name=Arc Lamp, icon=mdi:globe-light, supported_features=40 @ 2021-08-12T17:00:21.834364+12:00>, new_state=<state light.arc_lamp=on; min_mireds=161.2903289794922, max_mireds=357.1428527832031, supported_color_modes=['color_temp', 'rgb'], color_mode=color_temp, brightness=64, color_temp=0.0, friendly_name=Arc Lamp, icon=mdi:globe-light, supported_features=40 @ 2021-08-12T17:00:21.834364+12:00>>
```

I believe this problem is resolved by https://github.com/esphome/esphome/pull/2150 but I'm raising this here to document anyway.

### Which version of ESPHome has the issue?

v1.21.0b1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.8

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

api

### Example YAML snippet

```yaml
light:
  - platform: rgbww
    id: bulb
    name: ${light_name}
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: output_warm_white
    cold_white: output_cold_white
    warm_white_color_temperature: 2800 K
    cold_white_color_temperature: 6200 K
    restore_mode: RESTORE_DEFAULT_OFF
    color_interlock: true
```
