### ISSUE TITLE
AC Dimmer and esp8266_restore_from_flash: true

### ISSUE THREAD

**Issue by l154** [esphome/issues#2317]
### The problem

Using option esp8266_restore_from_flash set to true with ac_dimmer makes ficker at at start when changing brightness. When esp8266_restore_from_flash is set to false everything is OK.
But I need save state.

### Which version of ESPHome has the issue?

 1.20.4 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.5

### What platform are you using?

ESP8266

### Board

AC Dimming using triac

### Component causing the issue

ac_dimmer

### Example YAML snippet

```yaml
esphome:
  name: $devname
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true
....
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: GPIO4
    min_power: 30.7%
    max_power: 65%
    method: leading
    init_with_half_cycle: false
    zero_cross_pin:
      mode: INPUT
      number: GPIO5
# Nazwa urzadzenia 
light:
  - platform: monochromatic
    name: $upper_devname
    id: ${devname}
    output: dimmer1
    default_transition_length: 1500ms
```
