### ISSUE TITLE
bme680_bsec: Per Sensor variable "sample_rate" not working as expected

### ISSUE THREAD

**Issue by ChristianWaechter** [esphome/issues#2320]
### The problem

On the ESPhome page of the bme680_bsec component you can read, that the variable "sample_rate" should be available in the component configuration section to configure all sensors with this variable. I saw now that this variable "sample_rate" can also be set individually per sensor, see the advanced configuration example: https://esphome.io/components/sensor/bme680_bsec.html#advanced-configuration

When doing this in my setup, it is not working showing the error "[sample_rate] is an invalid option for [temperature]. Please check the indentation.", even though it is done exactly as in the example.

![grafik](https://user-images.githubusercontent.com/46220276/129472633-06ed1ad3-8cc7-40db-a12f-449a7787a202.png)

### Which version of ESPHome has the issue?

v1.20.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.6

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

bme680_bsec

### Example YAML snippet

```yaml
esphome:
  name: anything
  platform: ESP8266
  board: d1_mini

i2c:

bme680_bsec:
    address: 0x77
	########### The next line works fine
    sample_rate: ulp

sensor:
  - platform: bme680_bsec
    temperature:
      name: "BME680 Temperature"
	  ########### The next line causes an error!
      sample_rate: lp
```
