### ISSUE TITLE
xiaomi_miscale2 sensor platform briefly reports negative impedance

### ISSUE THREAD

**Issue by bogdanr** [esphome/issues#2323]
### The problem

The xiaomi_miscale2 platform briefly reports negative impedance so the graphs look messed up.

### Which version of ESPHome has the issue?

1.20.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8

### What platform are you using?

ESP32

### Board

Sonoff dual R3

### Component causing the issue

xiaomi_miscale2

**Comment by zibous** [comment]
Same here, current workaround (see sensor impedance):

```yaml
substitutions:
  board: esp32dev
  platform: ESP32
  update_time: 600s
  device_id: "Mi Bodyscan"
  device_name: 'mi bodyscale2'
  device_name_lower: mi_bodyscale2
  device_name_upper: "MI BODYSCALE2"
  device_name_short: mibodyscale
  mac: '5C:CA:D3:4C:EE:74'
  timeformat: '%Y-%m-%d %H-%M-%S'
  publish_interval: 60s
  attribution: "Data provided by ESP-HOME"
  appversion: "1.1.0"
  device_description: 'Mi Bodyscale 2'
  application: "ESP32 ESPHOME APP"
  topic_data: "tele/bodyscale/data"


esphome:
  name: $device_name_short
  comment: ${device_description}
  platform: ${platform}
  board: ${board}

# Enable logging
logger:
  level: DEBUG
  logs:
    mqtt.component: ERROR
    mqtt.client: ERROR

<<: !include common/wifi.yaml
<<: !include common/mqtt.yaml


esp32_ble_tracker:
  id: BTE_HUB

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Zurich
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org 
        
text_sensor:
  - platform: version
    name: ${device_name_upper} Version
    id: appver
    
  - platform: template
    name: ${device_name_upper} Online seit
    id: uptime_human
    icon: mdi:clock-start
   
  - platform: wifi_info
    ip_address:
      name: ${device_name_upper} IP
      id: wifiip
      icon: mdi:ip-network
      
    ssid:
      name: ${device_name_upper} SSID
      id: wifissid
      
    bssid:
      id: wifibssid
      name: ${device_name_upper} BSSID 
      
  - platform: template
    name: ${device_name_upper} Timestamp
    id: systime
    lambda:
      char str[20];
      time_t currTime = id(sntp_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", localtime(&currTime));
      return (std::string) str;  

sensor:
  - platform: xiaomi_miscale2
    mac_address: ${mac}
    weight:
      id: weight
      name: ${device_name_upper} Weight
      accuracy_decimals: 2
      
    impedance:
      name: ${device_name_upper} Impedance
      id: impedance
      on_raw_value:
        then:
          - lambda: |-
              if (id(weight).state >= 60 && id(weight).state <= 80.00) {    
                ESP_LOGI("main", "Publish MQTT Message: Peter, weight: %f", id(weight).state);
              } else if (id(weight).state >= 45 && id(weight).state <= 56) {
                ESP_LOGI("main", "Publish MQTT Message: Reni, weight: %f", id(weight).state); 
              } else {
                ESP_LOGI("main", "Publish MQTT Message: Guest, weight: %f", id(weight).state); 
              }
      on_value:
        - mqtt.publish_json:
            topic: ${topic_data}
            payload: !lambda |-
              if( id(impedance).state > 200 ) {   
                 ESP_LOGI("main", "Publish MQTT Message, weight: %f", id(weight).state);               
                 root["measured"] = id(weight).state;
                 root["calcweight"] = id(weight).state;
                 root["impedance"] = id(impedance).state;
                 root["unit"] = "kg";
                 if (id(weight).state >= 60 && id(weight).state <= 80.00) {
                    root["user"] = "Peter";
                 } else if (id(weight).state >= 45 && id(weight).state <= 56) {
                    root["user"] = "Reni";
                 } else {
                    root["user"] = "Guest";
                 }
                 root["id"] = "${mac}";            
                 root["timestamp"] = id(systime).state;
                 root["lastscan"] = id(systime).state;
                 root["scantime"] = id(systime).state;                   
                 root["version"] = "${appversion}";
                 root["application"] = "${application}";
                 root["attribution"] = "${attribution}";
              }
              

  - platform: uptime
    name: ${device_name_upper} Uptime
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d T":"") + (hours ? String(hours) + "h ":"") + (minutes ? String(minutes) + "m ":"") + (String(seconds) + "s")
              ).c_str();    
```
