### ISSUE TITLE
The number template cannot be discovered by the home assistant

### ISSUE THREAD

**Issue by jack9603301** [esphome/issues#2324]
### The problem

The number template cannot be discovered by the home assistant

No mqtt declaration appears to have been issued to ha

### Which version of ESPHome has the issue?

v1.20.1 

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.8.4

### What platform are you using?

ESP8266

### Board

NODEMCU ESP8266

### Component causing the issue

MQTT Number, Number

### Example YAML snippet

```yaml
number:
  - platform: template
    name: "Template number"
    update_interval: never
    min_value: 0
    max_value: 100
    step: 1
```
