### ISSUE TITLE
Template Number state is always "unknown"

### ISSUE THREAD

**Issue by JamesSwift** [esphome/issues#2328]
### The problem

I decided to try out the new template number as it seems a so much simpler concept to configure than how I used to do it. 

However, although in the ESPHome logs I can see the value being set successfully, Home Assistant always reports the value as `unknown`.

I've tried changing the value internally on the esp 8266, and by calling a service from within home assistant:

```
service: number.set_value
target:
  entity_id: number.kitchen_window_hold_until
data:
  value: 10
```

![image](https://user-images.githubusercontent.com/2080205/129961599-e725cf6f-b657-4861-ac6b-9d225a304894.png)

### Which version of ESPHome has the issue?

v2021.8.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.8.7

### What platform are you using?

ESP8266

### Board

d1 mini

### Component causing the issue

template number

### Example YAML snippet

```yaml
number:
  - platform: template
    name: "Kitchen Window Hold Until"
    id: kitchen_window_hold_until
    min_value: 0
    max_value: 86400
    step: 1
```

### Anything in the logs that might be useful for us?

```txt
[19:35:24][D][number:010]: 'Kitchen Window Hold Until' - Setting
[19:35:24][D][number:029]:   Value: 10.000000
```

**Comment by oxan** [comment]
You should either enable optimistic mode, or supply the lambda and set_action parameters to read/write the number from somewhere (if optimistic mode is off, the template number doesn't track any state itself).

@jesserockz would it make sense to require either optimistic mode to be on, or lambda/set_action to be specified (in config validation)?

**Comment by JamesSwift** [comment]
Thannks @oxan, I read the docs but missed the "defaults to false" under optimistic, I assumed it would default to true. Sorry about that. 

Could I also ask, as the number is a float, what are the limits on precision? I ideally want to store a unix timestamp in there.

I noticed if I set:
```
number:
  - platform: template
    name: "Kitchen Window Hold Until"
    id: kitchen_window_hold_until
    min_value: 1111111111
    max_value: 9999999999
    optimistic: true
    step: 1
```

Home assistant reports:
![image](https://user-images.githubusercontent.com/2080205/129965758-083d8f68-ebbb-4900-8855-f9726c35719f.png)
