### ISSUE TITLE
Waveshare ePaper 2.9" Rev2.1 - flickering screen refreshing problem.

### ISSUE THREAD

**Issue by dougle03** [esphome/issues#2334]
### The problem

Following the example within the ESPHome.io page `https://next.esphome.io/components/display/waveshare_epaper.html`
I've paired up a Waveshare ePaper 2.92 board version 2.1 to a Wemos D1 Mini and loaded the code.
I get the basic itprint text on boot up, but on next refresh the screen shows noise, then flashes the correct display then fades to nearly nothing until the next refresh where the cycle repeats.
![image](https://user-images.githubusercontent.com/59865048/130116131-43196272-9850-4878-895d-cbc729fb58c7.png)

### Which version of ESPHome has the issue?

2021.9.0-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Not applicable

### What platform are you using?

ESP8266

### Board

Wemos D1 (Clone)

### Component causing the issue

Waveshare ePaper 2.9" rev2.1

### Example YAML snippet

```yaml
yaml below.

spi:
  clk_pin: D0
  mosi_pin: D1
  #miso_pin: D7 #not connected
display:
  - platform: waveshare_epaper
    cs_pin: D2
    dc_pin: D3
    busy_pin: D4
    reset_pin: D5
    model: 2.90inv2
    #id: mydisplay
    update_interval: 30s
    full_update_every: 180
    rotation: 90°
    #brightness: 100%
    lambda: |-
      //Header
      it.strftime(0, 0, id(font4), TextAlign::TOP_LEFT, "%a %H:%M", id(esptime).now());
      it.print(0, 50, id(font3), "TESTING");
      
```
```


### Anything in the logs that might be useful for us?

```txt
Nothing in the logs of note.
```

### Additional information

https://user-images.githubusercontent.com/59865048/130116613-ad30d677-3dce-4061-958c-a3fba39d5742.mp4

**Comment by dougle03** [comment]
Note: powered by a lab bench power supply to the USB of the D1. Ground and 3.3v from the D1's pins.

**Comment by ephirial** [comment]
Hey, I can confirm this behaviour. I have tested the same display with a Wemos D1 and I have the same issue. I have tested a bunch of different pin configurations, all with the same result.
I have also tested it on a ESP32, also with the same issue.

**Comment by dougle03** [comment]
Seems like it's an actual bug then. It's a shame as I have plans for this display.

**Comment by swifty99** [comment]
Hi, 
same here.

To mitigate the problem I use:
`  on_boot:
    priority: 700 
      # remove display dirt, bad workaround, shoulb be better
      - delay: 2sec      
      - component.update: my_display 
      - delay: 100ms
      - component.update: my_display 
      - delay: 100ms
      - component.update: my_display 
      - delay: 100ms
      - component.update: my_display 
      - delay: 100ms
`

**Comment by dougle03** [comment]
Thanks, I'll give that a go when I get home ;)

**Comment by dougle03** [comment]
Just need to get home now to try it! 
![image](https://user-images.githubusercontent.com/59865048/131230484-88afc54a-c72e-484c-b0ac-8457e422ed5a.png)

**Comment by dkagedal** [comment]
I have this problem as well. I'm not sure how the code above was meant to help, other than to try to update the display "enough times". Anyway it didn't help to me.

Looking at the code, and at the specs and examples from Waveshare, I'm wondering about the code at https://github.com/esphome/esphome/blob/8f3a739da77e06b5ef18115248ee469ed0caa95f/esphome/components/waveshare_epaper/waveshare_epaper.cpp#L375

Should't there be a call to `this->wait_until_idle_()` after the Master Activation command?

And what is the `0xFF` command? I didn't find that in the specs.

**Comment by dkagedal** [comment]
Tried adding that, and it didn't help. But I don't really know what I'm doing here.

**Comment by dougle03** [comment]
It does look like there is a bug in the module that's presumably messing up the refresh process. People have these displays working fine using Arduino IDE and the libs available; but the ESPHome implementation does not work properly with v2.1 screens. I've tried to buy a v2 screen but can't find them anywhere on sale.
Perhaps the original dev would take a look at some point? 
Anyone know who the dev was?

**Comment by balloob** [comment]
Please do not tag random people to get attention to your issue.

**Comment by dkagedal** [comment]
It seems to get it right when redrawing it initially after boot, but later refreshes are corrupted. So I tried

```
    full_update_every: 1
```

And that solved the issue!

**Comment by dougle03** [comment]
> Please do not tag random people to get attention to your issue.
Sorry, did not mean to tag you, was attempting to tag the original dev for the mod. Apologies again.

**Comment by dougle03** [comment]
> It seems to get it right when redrawing it initially after boot, but later refreshes are corrupted. So I tried
> 
> ```
>     full_update_every: 1
> ```
> 
> And that solved the issue!

Excellent, will give that a try later this evening. Thanks

**Comment by dougle03** [comment]
>  full_update_every: 1

That did it. Now it's stable. Thanks very much. I'll close this issue now, but I suspect a change is needed to the ESPHome docs page.

**Comment by dkagedal** [comment]
This is really just a workaround. The problem remains that partial updates are broken, so i think we can keep this issue open

**Comment by dougle03** [comment]
Yes, I agree. I only closed because it solved my immediate problem, but yes, having it flicker in the corner of my eye every 15 seconds is pretty annoying...

**Comment by LukasK13** [comment]
Please reopen this issue.
The problem is not only the text being blurry but also the flickering during the partial update which should not occur. Definitely not resolved.

**Comment by dougle03** [comment]
Reopened to resolve the issues

**Comment by LukasK13** [comment]
@K-r-i-s-t-i-a-n you implemented esphome/esphome#1538. Did this work with v2?

**Comment by Dianoga** [comment]
I'm seeing this exact same issue. Same screen hooked up to a D1 mini exhibiting the same effect. I also tried switching to a Heltec Wifi kit 32 to see if it was board specific but the same issue is still happening.

**Comment by Dianoga** [comment]
Partial update is the entire reason I'm using this screen. Currently I'm looking at the differences between the code generated by esphome and the sample code provided by waveshare as the sample code is properly working with the partial refresh.

**Comment by Dianoga** [comment]
I don't have it working and have in fact made everything worse (full updates don't work either) but as best as I can tell right now these changes _should_ match the behavior of the example code from waveshare.

https://github.com/Dianoga/esphome/commit/696d319d4baca2884c576eb48be57edd31d5eea8

**Comment by dougle03** [comment]
My yaml that now works, although a full refresh is done every 15 seconds (Which is a bit rubbish).
`spi:
  clk_pin: D0
  mosi_pin: D1 #DIN
  #miso_pin: D7 #not connected
display:
  - platform: waveshare_epaper
    cs_pin: D2
    dc_pin: D6
    busy_pin: D7
    reset_pin: D5
    model: 2.90inv2
    id: mydisplay
    update_interval: 15s
    full_update_every: 1
    rotation: 90
    lambda: |-`

**Comment by LukasK13** [comment]
I had a look at the example code [here](https://github.com/waveshare/e-Paper/blob/master/Arduino/epd2in9_V2/epd2in9_V2.cpp) and the (incomplete) manual [here](https://www.waveshare.com/w/upload/7/79/2.9inch-e-paper-v2-specification.pdf) and implemented a hacky fix for the artial update. Unfortunately, a partial update has to be done 2 s after each full update in order to make the first partial update work. Therefore I had to include a 2 s delay in the code which is rather unprofessional.
You can find my fix [here](https://github.com/LukasK13/esphome/tree/fix-waveshare-epaper-2in9v2).

**Comment by Dianoga** [comment]
How do we get a fix merged into esphome? I don't have enough C knowledge to put together a PR that I would have any faith in. @LukasK13 are you able to submit a PR with your changes? Even if it's not a perfect fix it would be better then the broken we have now.

**Comment by joekeslar** [comment]
Is there a status on the merged fix?

**Comment by Tookir** [comment]
Hi,

Same problem here, I just bought it for a project, it annoys me a little since it is not marked that it does not work in v2.1. Anyone have a solution, other than a total refresh?

**Comment by emdekext** [comment]
I agree, please fix this asap, thanks. 
There's also another open issue, it seems exactly the same problem: [https://github.com/esphome/issues/issues/2459](url)

**Comment by Kaibob2** [comment]
I just bought a 2.9" Waveshare E-Ink Panel V2 and seeing the exact same behaviour as pictured in the start post. 
Reducing `full_update_every:` to 1 fixes the grainy display, but a full update is not what the display is intended for.

**Comment by Kaibob2** [comment]
Meanwhile I also added the above as local `external_component` and this fixed the issue almost perfectly. The mentioned 2 seconds delay (in the original thread) in the partial update code make buttons pretty unresponsive when a lot of display updates occur while pressing them, but that's not a real problem.

**Comment by Tookir** [comment]
Can you share you esp code for exemple Kaibob2 ? I try to add id by external_component github link but it's not working. (errors at compilation).
Thanks for your help.

**Comment by Kaibob2** [comment]
This is what you can use:

```
external_components:
  - source:
      type: git
      url: https://github.com/velaar/esphome
      ref: dev
    components: [ waveshare_epaper]
```

When you have ESPhome 2022.6.0 or newer installed you will need `display` also additional as external component as there was a breaking change from that version onwards. 
`Add display_type property to DisplayBuffer https://github.com/esphome/esphome/pull/3430 by [@guillempages](https://github.com/guillempages) (breaking-change)`
In that case it would be like this then:

```
external_components:
  - source:
      type: git
      url: https://github.com/velaar/esphome
      ref: dev
    components: [ waveshare_epaper, display]
```

**Comment by Kaibob2** [comment]
Another option would be to download the git repository and copy the `display` and `waveshare` folder into a folder of your choice in the esphome directory. In my case it's named `my_components`.
All components in this directory will then be used instead of the default ones during compilation. This method makes the source code a little more independent from changes in a repository of someone else.
If you decide to do so it will be like that:

```
external_components:
  - source:
      type: local
      path: /config/esphome/my_components
```

**Comment by Kaibob2** [comment]
Glad I could help. I'm very thankful for this fix, too.
Most of the info on my display is not time critical either, the few info which is I perform a manual update with `component.update` as soon as a new value arrives. My standard values are:

```
reset_duration: 200ms
update_interval: 30s
full_update_every: 200
```

**Comment by remyderuysscher** [comment]
> This is what you can use:
> 
> ```
> external_components:
>   - source:
>       type: git
>       url: https://github.com/velaar/esphome
>       ref: dev
>     components: [ waveshare_epaper]
> ```
> 
> When you have ESPhome 2022.6.0 or newer installed you will need `display` also additional as external component as there was a breaking change from that version onwards. `Add display_type property to DisplayBuffer https://github.com/esphome/esphome/pull/3430 by [@guillempages](https://github.com/guillempages) (breaking-change)` In that case it would be like this then:
> 
> ```
> external_components:
>   - source:
>       type: git
>       url: https://github.com/velaar/esphome
>       ref: dev
>     components: [ waveshare_epaper, display]
> ```

Excellent, spend many hours to debug this screen.  This solves it.  Should be merged in ESPHome someday.

**Comment by ExZylan** [comment]
> > This is what you can use:
> > ```
> > external_components:
> >   - source:
> >       type: git
> >       url: https://github.com/velaar/esphome
> >       ref: dev
> >     components: [ waveshare_epaper]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When you have ESPhome 2022.6.0 or newer installed you will need `display` also additional as external component as there was a breaking change from that version onwards. `Add display_type property to DisplayBuffer https://github.com/esphome/esphome/pull/3430 by [@guillempages](https://github.com/guillempages) (breaking-change)` In that case it would be like this then:
> > ```
> > external_components:
> >   - source:
> >       type: git
> >       url: https://github.com/velaar/esphome
> >       ref: dev
> >     components: [ waveshare_epaper, display]
> > ```
> 
> Excellent, spend many hours to debug this screen. This solves it. Should be merged in ESPHome someday.

With the latest version of esphome 2023.6.0, this external package no longer works. Any solution?

Compiling the program without the external package still produces errors in the fast screen refresh of my Waveshare 2.9".

I had to revert to an earlier version of esphome to be able to compile the program with the external package.

**Comment by Kaibob2** [comment]
Same here.

**Comment by Kaibob2** [comment]
The fix is pretty simple if you finally find the breaking change related to this issue: https://github.com/esphome/esphome/pull/4926
So, if you're already using the external component from https://github.com/velaar/esphome and have `waveshare_epaper` and  `display` integrated like this:
```
external_components:
  - source:
      type: local
      path: /config/esphome/my_components
```
then just navigate with a file editor to your my_components folder and change 
`time::ESPTime time`
to
`ESPTime time`
in line 371, 377, 380 and 383 in file `display_buffer.cpp`

Afterwards do the same in line 241, 253, 265 and 276 in file `display_buffer.h`

Save both files, click on clean build files in the ESPhome Dashboard for the specific node which won't compile and install like usual.

**Comment by beyondgrave** [comment]
This almost worked for me. I can now get past the time::ESPTime time error, but now get an error about set_transparency. Are you using any images on your epaper display??

**Comment by Kaibob2** [comment]
No, only Icons, lines and Text . Sorry.

**Comment by beyondgrave** [comment]
Weird. I can't even get icons to work... I guess I'll keep fighting with it

**Comment by Kaibob2** [comment]
For the icons i added this 

```
font:
  - file: 'materialdesignicons-webfont.ttf'
    id: icon_font_24
    size: 24
    glyphs: [
      "\U000F1974",  #car-clock
      "\U000F0298",  #gas-station
      "\U000F1077",  #face-woman
      "\U000F0643",  #face-man
      "\U000F050F",  #thermometer
      "\U000F058E",  #water-percent
      "\U000F11DC",  #window-open-variant
      "\U000F06E8",  #lightbulb-on
      "\U000F01AD",  #currency-eur
      "\U000F0D8E",  #mailbox-up-outline
      "\U000F1886"   #mdi-flower-pollen-outline  
      ]
```
and then use the icons like this:
```
    pages:
      - id: mainscreen
        lambda: |-
          if (id(online).state){

            //Temperatur Garten
            it.printf(2, 36, id(icon_font_24), "\U000F050F");          
            if (id(t_garten).has_state())
            {              
              it.printf(24, 41, id(arial18), "%.1f°", id(t_garten).state);
            }
          }
```
Only for example, the whole mainscreen code is huuuge.

**Comment by beyondgrave** [comment]
Ah, I see. I was using still using the Image function in ESPhome and referring to the mdi-icons. Seems like the custom components don't have support for the new/changed Image features (transparency stuff). Using the Font function as a workaround is very clever. I'll have to try that, but I'll have to do a lot of re-coding

**Comment by Kaibob2** [comment]
This whole custom component solution is quite flaky and I guess it will be a constant struggle to keep it working with ongoing changes in the main ESPhome features. I hope that there will be a better supported e-ink display soon. Maybe there is already one available and I just don't know.
Good luck and happy re-coding :)

**Comment by stephenjamieson** [comment]
@jesserockz, apologies for the direct ping, but is there any chance that this will get merged? Or does it need work?

**Comment by velaar** [comment]
> time::ESPTime time

Fixed this in my github version. This manual fix is no longer needed.

**Comment by Kaibob2** [comment]
As there are quite a few `display` related breaking changes in 2023.7.0, has anybody using the waveshare ePaper already updated to this version and can confirm that it's still working?

**Comment by phoenixswiss** [comment]
@Kaibob2  It is broken. I have two 7.5v2 waveshare screens configured with model: 7.50inV2

One was working fine on 2023.6.5 and the other was having problems with artifacts.

After updating to 2023.7.0, the one with artefacts doesn't work with model: 7.50inV2 --> error message: "component api took a long time for an operation". I changed it to 7.50inV2alt and it works with that configuration, but has even more artifacts than before.

The other, which worked fine with 2023.6.5, now has artifacts with model: 7.50inV2 and with model: 7.50inV2alt doesn't even work. I also now have two vertical lines on the screen (a new hw problem). 

In other words: I had and still have a lot of problems with the ePaper display integration in ESPhome in general. I have flashed my old Arduino project to my Lolin D32 Pros and both displays work fine.

**Comment by Kaibob2** [comment]
Thanks for the response. Have you used the external component solution mentioned earlier in this thread or did you use the Standard Esphome Display component?

**Comment by phoenixswiss** [comment]
I'm using the stock ESPhome displac component

```
display:
  - platform: waveshare_epaper
    id: epaper_display
    reset_duration: 200ms
    setup_priority: 1000
    cs_pin: 5
    dc_pin: 0
    busy_pin: 15
    reset_pin: 2
    model: 7.50inV2
    update_interval: never 

[...]

- component.update: epaper_display
```

I don't want to accuse anyone here, especially not the hard working ESPhome developers/community, but as a matter of fact I bought three brand new waveshare 7.5v2 ePaper screens and connected them to the same Lolin D32 Pro ESP32 just like the ones I have been running for two years. 

Since using the ESPhome Display component in my new project, all three brand new displays have some sort of temporary problem (artefacts) or even permanent damage (2 vertical lines on one screen and a completely toasted driver hat after running for a few days on another display). It may just be an unfortunate coincidence.

**Comment by Kaibob2** [comment]
I see. Funny that it works like that for you. I suppose you circumvent the partial Update Problem by setting update_interval: never
Maybe try the custom component solution and see if it helps.

**Comment by Kaibob2** [comment]
This issue https://github.com/esphome/issues/issues/4307 also deals with this display.

**Comment by phoenixswiss** [comment]
I've just noticed something strange. 

If you use a "strong" light source like an LED from a smartphone and point it directly at the display after the display has refreshed ~3 seconds ago, it goes dark at this point. 

But it shouldn't, because the update of the epaper has already been completed and the pixels shouldn't react to light after this step. This only happens when I'm running ESPhome on my ESP32. When I flash my Arduino project on the ESP, the display remains white where I have pointed the LED light source. It seems that ESPhome doesn't put the display to sleep after updating. 

Waveshare warns of display damage if the display is left on for an extended period of time.

https://www.waveshare.com/wiki/7.5inch_e-Paper_HAT_(B)_Manual#ESP32.2F8266:~:text=Note%20that%20the%20screen%20cannot%20be%20powered%20on%20for%20a%20long%20time.%20When%20the%20screen%20is%20not%20refreshed%2C%20please%20set%20the%20screen%20to%20sleep%20mode%20or%20power%20off%20it.%20Otherwise%2C%20the%20screen%20will%20remain%20in%20a%20high%20voltage%20state%20for%20a%20long%20time%2C%20which%20will%20damage%20the%20e%2DPaper%20and%20cannot%20be%20repaired!

**Comment by velaar** [comment]
> As there are quite a few `display` related breaking changes in 2023.7.0, has anybody using the waveshare ePaper already updated to this version and can confirm that it's still working?

So here goes my Friday evening. But it seems to be compiling and working on 2023.7.0.

I have done absolutely zero testing on it and switch to IDF for device-reasons (see no reason why it shouldn't work with default framework though) 

Here is a a yaml to test 

```
esphome:
  name: crystalball
  on_boot:
    priority: 200
    then: 
    - delay: 1sec
    - component.update: my_display

esp32:
  board: esp32dev
  framework:
     type: esp-idf
     version: recommended
     # Custom sdkconfig options
     sdkconfig_options:
       CONFIG_COMPILER_OPTIMIZATION_SIZE: y
     # Advanced tweaking options
     advanced:
       ignore_efuse_mac_crc: false

# Enable logging
logger:
  level: INFO

api:

external_components:
  - source:
      type: git
      url: https://github.com/velaar/esphome
      ref: test_23_7
    components: [ waveshare_epaper, display]

```

**Comment by Kaibob2** [comment]
I'm on vacation for the next 10 days and I suppose it's wiser to test this afterwards :)
Thanks for the effort, I'll report back as soon as I update.

**Comment by MadJalapeno** [comment]
https://github.com/esphome/issues/issues/2334#issuecomment-1646498120 fixed it for me, thank you @velaar

**Comment by zigomatichub** [comment]
I don't have issue after update with model to 7.50in-bV2.
Sorry for my mistake

**Comment by Kaibob2** [comment]
https://github.com/esphome/issues/issues/2334#issuecomment-1646498120 fixed it for me, too.
Thanks for that!

**Comment by Nik19792000** [comment]
https://github.com/esphome/issues/issues/2334#issuecomment-1646498120 fixed it for me too. I've spent few hours before I finally found this issue discussion.

**Comment by boyfromgermany** [comment]
Hello 
i have the 2.9in version with red color support
if i use 2.9in-b it does nothing at all
and if i use 2.9inV2 it shows the text for 1 second but then flickers until it is black 

i used the fix above and the custom component without success

does someone have the same display ?

**Comment by pablogventura** [comment]
> Hello i have the 2.9in version with red color support if i use 2.9in-b it does nothing at all and if i use 2.9inV2 it shows the text for 1 second but then flickers until it is black
> 
> i used the fix above and the custom component without success
> 
> does someone have the same display ?

I am in the same situation, i cant be able to make work this e-ink display. I only see blinking noise. I tried all ideas in this topic.
![imagen](https://github.com/esphome/issues/assets/6233850/71af91b2-bcb1-4e44-bcc5-60b156df9b7f)

**Comment by ellwoodb** [comment]
I have the exact same problem as @pablogventura, I think I also have the same hardware as you!

With `model: 2.90inv2-r2` it's now no noise anymore, but the background is red after a restart, and it becomes less saturated with every refresh.

I really hope this gets fixed some time...

**Comment by Zervendoggo** [comment]
Hello, I updated to ESPHome 2024.4.1 and now I cannot get this external component to work any longer and my device is no longer working, is there anything I can do? :C

**Comment by mateusz-jaworski** [comment]
With model: 4.20in-bv2 is the same case using esp32. Everything works fine except flickering on screen change/refresh. Is possible to check something or how to debug?

**Comment by DorjeDorf** [comment]
Unfortunately it seems the https://github.com/esphome/issues/issues/2334#issuecomment-1646498120 solution no longer works. There are loads of compilation errors while it runs (weirdly enough about missing semi colons). 
Has anyone had any luck with this workaround recently? 

Or better yet, perhaps the dev team had a chance to take a look at this problem and fix it for good in the main codebase?

**Comment by floriansProjects** [comment]
>Has anyone had any luck with this workaround recently?

For me changing the model to
`model: 2.90inv2-r2`
(and disabling the custom component) fixed the problem (using the b/w version).

**Comment by DorjeDorf** [comment]
For me, switching to r2 means refresh is not working at all and the graphics are mirrored on the X axis. 
Here's me hoping someone else will also see a solution for this.

**Comment by floriansProjects** [comment]
this is the full code, maybe you can try this?

```
display:
  - platform: waveshare_epaper
    cs_pin: 5
    dc_pin: 32
    busy_pin: 25
    reset_pin: 33
    model: 2.90inv2-r2
    full_update_every: 1000
    update_interval: 30s
    reset_duration: 100ms
    rotation: 90°
```

**Comment by DorjeDorf** [comment]
Thanks. That's more or less what I used (just different pins). 
I've been fighting with this for weeks now. The biggest problem is the screen mirroring and that I think is purely software based. 

I am for now at least forced to either go down to my own code and skip using ESPHome (which I don't have the time for now really and probably will take ages to work again with C++ as I'm rusty as hell), or hope someone else has/had this problem and will help diagnose it.

**Comment by lukie80** [comment]
This is a very strange issue. I have a BW-Red version running 2.90in. It looks like a partial refresh removes the noise for all following refreshes.
Using "full_update_every: 2" fixes it for static content. For dynamic you get some gap issues.

**Comment by pablogventura** [comment]
Any updates on this issue?

**Comment by pablogventura** [comment]
I’d like to point out that all the problems with these screens are still exactly the same.

**Comment by tubit** [comment]
I just tried my waveshare display again with esphome after some years, I can confirm that the problem is still around. :(

**Comment by dougle03** [comment]
Mines in a drawer somewhere. Moved on the CYD screens. Cheap and easy to program! Power saving was never my primary goal, plus epaper screens can crash without there being any obvious clues on the display as all the data shown would look 'ok' on a glance...

**Comment by pablogventura** [comment]
Hi,

A fix for the **2.9" V2 Rev 2.1** refresh / flicker class of problems (and related **2.9" (B)** BWR buffer handling) is now in a pull request on the main ESPHome repository:

**https://github.com/esphome/esphome/pull/15072**

It targets [esphome/issues#2334](https://github.com/esphome/issues/issues/2334) (long BUSY / false idle timeouts on `model: 2.90inv2`, plus correct BWR RAM transfers for the 2.9" B variants).

If you still have the hardware, please try a build from that PR branch and report whether full and partial updates are stable (no noise, no “fade to nothing” after refresh) on **ESP8266** and/or **ESP32** with `model: 2.90inv2`. Mention your exact module revision if you can.

Thanks.

**Comment by pablogventura** [comment]
**Update — hardware working (photo below)**

I tested a **2.9" tri-color (BWR) panel** (MH-ET LIVE / WeAct-style, SSD1680 class) on an **ESP32** using **`epaper_spi`** and **`WEACT-2.9IN-3C`**. Refresh is slow (~20–25 s per update) but stable: no flicker/noise cycle, counter increments, black + red regions render as expected.

The original report used **`waveshare_epaper`** with **`model: 2.90inv2`**. The fix for that path is in **https://github.com/esphome/esphome/pull/15072**. The YAML below matches `tests/manual/waveshare_2_9_v2_hardware_test.yaml` — adjust **`substitutions`** for your wiring.

![Image](https://github.com/user-attachments/assets/007ae4de-bd33-4289-b934-74ba9b6b531a)

```yaml
# Manual test: waveshare_epaper from ESPHome PR #15072 (github://pr#15072)
# Use this to compile/flash against the PR branch for model 2.90inv2 (Rev 2.1 path).
#
# Pins: edit substitutions for your wiring.
# If stuck on BUSY, try busy_pin with inverted: true.
# Use an update_interval longer than one full refresh to avoid driver backlog.
#
# esphome run this_file.yaml

external_components:
  - source: github://pr#15072
    components: [waveshare_epaper]
    refresh: 1h

substitutions:
  epaper_update_interval: 35s
  pin_spi_clk: GPIO25
  pin_spi_mosi: GPIO26
  pin_epd_cs: GPIO27
  pin_epd_dc: GPIO32
  pin_epd_busy: GPIO33
  pin_epd_rst: GPIO19

esphome:
  name: waveshare-29-test

esp32:
  board: esp32dev

logger:
  level: DEBUG

globals:
  - id: refresh_counter
    type: int
    restore_value: no
    initial_value: "0"

spi:
  id: spi_epaper
  clk_pin: ${pin_spi_clk}
  mosi_pin: ${pin_spi_mosi}

font:
  - file: "https://media.esphome.io/tests/fonts/Monocraft.ttf"
    id: test_font
    size: 18
    glyphs:
      - " "
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "R"
      - "E"
      - "D"

display:
  - platform: epaper_spi
    id: epd
    spi_id: spi_epaper
    model: WEACT-2.9IN-3C
    cs_pin: ${pin_epd_cs}
    dc_pin: ${pin_epd_dc}
    busy_pin:
      number: ${pin_epd_busy}
      mode:
        input: true
        pullup: true
    reset_pin: ${pin_epd_rst}
    update_interval: ${epaper_update_interval}
    full_update_every: 6
    lambda: |-
      it.fill(Color::WHITE);
      it.printf(0, 0, id(test_font), Color::BLACK, "%d", id(refresh_counter));
      // BWR red via RGB (Color has no ::RED, only BLACK/WHITE statics)
      it.filled_rectangle(88, 8, 36, 22, Color(255, 0, 0));
      it.printf(0, 28, id(test_font), Color(255, 0, 0), "RED");
      id(refresh_counter) += 1;

interval:
  - interval: ${epaper_update_interval}
    then:
      - lambda: |-
          ESP_LOGI("epaper_test", "refresh_counter=%d", id(refresh_counter));
```

**Comment by TekkiWuff** [comment]
Tested it with my 2.9inch Rev 2.1 B/W for about 12 hours and it's looking good! Full refresh is a tad slower than before but I'm using partial refreshes most of the time anyway and only do a full refresh about every 4 hours, which works just fine. So far I simply re-compiled my old config with the new version from the PR without changing anything else (still using "platform: waveshare_epaper"), so maybe there is some way to optimize my settings, but I'm not sure it's worth the effort.

Edit: Using an ESP32

Thanks!

**Comment by serialscriptr** [comment]
tried the config above using the epaper_spi component and its able to display R/B/W fine but every update it does a full refresh which is really annoying. It doesnt seem to follow the full_update_every option which I have set to 6.

Maybe I am using a newer display? Mine is the waveshare 2.9" revision 2.1 V4 tri color display. Does anyone have any suggestions on how to make the display work? 

Board: ESP32 WROOM devkit v1. my config:

```yaml
font:
  - file: "fonts/arial.ttf" 
    id: font_1
    size: 32
  - file: "fonts/arial.ttf" 
    id: font_2
    size: 64 

spi:
  clk_pin:  GPIO13
  mosi_pin: GPIO23

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/New_York"

display:
  - platform: epaper_spi
    model: WeAct-2.9in-3c
    full_update_every: 6
    cs_pin: GPIO15
    dc_pin: GPIO27
    reset_pin: GPIO26
    busy_pin: 
      number: GPIO25
      mode:
        input: true
        pullup: true
    rotation: 90
    lambda: |-
      it.fill(Color::WHITE);
      it.strftime(0, 0, id(font_1), Color(255, 0, 0), "%a %m/%d", id(sntp_time).now());
      it.strftime(10, 50, id(font_2), Color::BLACK, "%I:%M %p", id(sntp_time).now());
```

**Comment by pablogventura** [comment]
**Update: `epaper_spi` PR for mono Waveshare 2.9" V2 Rev 2.1**

Per maintainer direction on https://github.com/esphome/esphome/pull/15072, support for this panel is being added to **`epaper_spi`** (not the deprecated `waveshare_epaper` component):

- **Code:** https://github.com/esphome/esphome/pull/17548 (`model: waveshare-2.9in-v2`, 128x296 mono)
- **Docs (draft):** https://github.com/esphome/esphome.io/pull/6977

**Migration from `waveshare_epaper`:**

```yaml
display:
  - platform: epaper_spi
    model: waveshare-2.9in-v2
    # cs_pin, dc_pin, busy_pin, reset_pin, spi as before
    update_interval: 35s
    full_update_every: 6
```

**Hardware test request:** I do not have the original mono Waveshare 2.9" V2 Rev 2.1 panel locally. If you still have the hardware from this issue, please try a build from PR #17548 (or `external_components` from branch `epaper_spi-waveshare-2.9in-v2` on fork `pablogventura/esphome-dev`) and report whether:

1. Full refresh is stable
2. Partial refresh (e.g. `full_update_every: 6`) avoids the noise / fade cycle described in the original report
3. Platform (ESP8266 / ESP32) and panel revision if known

Tri-color / MH-ET BWR panels are a different model (`weact-2.9in-3c`), not covered by this PR.

Thanks.

**Comment by TekkiWuff** [comment]
Tested the new PR with the epaper_spi platform with my 2.9inch Rev 2.1 B/W connected to an ESP32.
Unfortunatly this doesn't seem to work correctly or there are more changes needed in my config than just changing the "platform" and "model" parameters.
When changing the "lambda" to the example given in the PR, I briefly see the text "Hello" as white text on black background (so opposite of what the lambda expresses) after the reset before it flashes black/white 3 times and then the display stays empty (white). Waiting for "update_interval" and/or reducing "full_update_every" to 1 doesn't change anything. It just stays white without any further sign of refreshes (no flashing, no more "Hello")

Here are the relevant parts of my config. The spi and display pins are the same I've used successfully with the "waveshare_epaper" platform before. esphome version is 2026.6.5 in a fresh python venv.
```yaml
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

font:
  - file: "gfonts://Teko@light"
    id: font_text
    size: 32

external_components:
  - source: github://pr#17548
    components: [epaper_spi]
    refresh: 1h

spi:
  clk_pin: GPIO33
  mosi_pin: GPIO32

display:
  - platform: epaper_spi
    model: waveshare-2.9in-v2
    cs_pin: GPIO25
    dc_pin: GPIO26
    busy_pin: GPIO14
    reset_pin: GPIO27
    update_interval: 30s
    full_update_every: 1
    lambda: |-
      it.fill(Color::WHITE);
      it.print(0, 0, id(font_text), Color::BLACK, "Hello");
```

If there is anything I should check or change, let me know!

**Comment by pablogventura** [comment]
Thanks for testing #17548 on your Rev 2.1 B/W panel - that report was very helpful.

I aligned `waveshare-2.9in-v2` with the legacy `WaveshareEPaper2P9InV2R2` / `2.90inv2-r2` path that worked for you on #15072:

- Full refresh via OTP (`0x22` / `0xF7`) instead of registered LUT + `0xC7`
- Same buffer written to both `0x24` and `0x26` on full/base updates
- Hardware reset before partial, 159-byte partial LUT, command `0x37`
- No deep sleep between updates (keeps controller RAM)

Please retest with a fresh pull of the PR:

```yaml
external_components:
  - source: github://pr#17548
    components: [epaper_spi]
    refresh: 0s

logger:
  level: VERBOSE

display:
  - platform: epaper_spi
    model: waveshare-2.9in-v2
    # same pins as before
    update_interval: 35s
    full_update_every: 1
    lambda: |-
      it.fill(Color::WHITE);
      it.print(0, 0, id(font_text), Color::BLACK, "Hello");
```

**Step 1** (`full_update_every: 1`): does the text stay correct (black on white) and keep refreshing every interval?

If Step 1 works, **Step 2**: try `full_update_every: 6` for partials.

If it still sticks after one refresh, please paste VERBOSE lines mentioning `Waiting for idle` or `Display already in state`. Only if busy appears stuck, try `busy_pin: { number: ..., inverted: true }` as an experiment.

Thanks again!

**Comment by TekkiWuff** [comment]
Thank you for all your updates!
I've tried it again with the updated PR and the full refresh is working now. It refreshes at the given interval and shows the black and white shades correctly.
The partial refresh still doesn't seem to be working though. I've modified the lambda to show a counter so I can see if the partial refreshes work but the counter is not updating on the partial refreshes but only the full refreshes. so it shows "Update 1", "Update 7", "Update 13", etc. 

```yaml
external_components:
  - source: github://pr#17548
    components: [epaper_spi]
    refresh: 0s

spi:
  clk_pin: GPIO33
  mosi_pin: GPIO32

display:
  - platform: epaper_spi
    model: waveshare-2.9in-v2
    cs_pin: GPIO25
    dc_pin: GPIO26
    busy_pin: GPIO14
    reset_pin: GPIO27
    update_interval: 35s
    full_update_every: 6
    lambda: |-
      static int update_counter = 1;
      it.fill(Color::WHITE);
      it.printf(0, 0, id(font_text), Color::BLACK, "Update %d", update_counter);
      update_counter++;
```
I've attached the log. Maybe it helps. It has full refreshes starting at 21:19:54 and 21:23:24 and partial refreshes in between.
[refresh.log](https://github.com/user-attachments/files/30022895/refresh.log)
