### ISSUE TITLE
ESP32 S2 WROOM - not able to integrate

### ISSUE THREAD

**Issue by homonto** [esphome/issues#2343]
### The problem

so I am happy user of ESPHome with some ESP32S boards. Recently I bought ESP32-S2-WROOM and I am completely not able to integrate this board with ESPHome. Is it because S2 is not supported or what?
In Arduino or other platforms there is a big difference between ESP32 and S2 but as per ESPHome: "All ESP32-based devices are supported by ESPHome. Simply select ESP32 when the ESPHome wizard asks you ..." - but when I start the wizard it says: "Unable to identify the connected device (12882)." When I skip wizard and try to install it says: "installation failed". I am connecting using usb-c cable from my macbook to the board. Arduino has no issues - any sketch done with Arduino or even esptool works but ESPHome apparently not. I am a big fan of ESPHome for my HA but...
Any help would be appreciated. Thank you

### Which version of ESPHome has the issue?

Current version: 2021.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.8.8

### What platform are you using?

ESP32

### Board

ESP32-S2-WROOM

### Component causing the issue

integration does not work

### Example YAML snippet

```yaml
esphome:
  name: test
  platform: ESP32
  board: esp32dev
  arduino_version: latest

# Enable logging
logger:
  level: DEBUG
# Enable Home Assistant API
api:

ota:
  password: "asdfasdfas"
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  manual_ip:
    static_ip: 192.168.1.184
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "test Fallback Hotspot"
    password: !secret esp_fallback_wifi_password

captive_portal:

sensor:
  - platform: wifi_signal
    update_interval: 5s
    id: test_wifi
    name: "test_wifi"
```

### Anything in the logs that might be useful for us?

```txt
I am not at the log level as it does not integrate even
During installation it shows:

"installation failed" and 2 eyes ;-(
```
