### ISSUE TITLE
after update to 2021.8.0: state: "ON"/"OFF" member missing in json MQTT state topic for monochromatic light

### ISSUE THREAD

**Issue by bshm** [esphome/issues#2345]
### The problem

Esphome used to give information about state and brightness of a dimmer component via MQTT.
e.g. 
```{"state":"OFF","brightness":255}```
recently with the upgrade to 2021.8.0 this changed to
```{"color_mode":"brightness","brightness":255,"color":{}}```
which causes the light state in Home Assistant to be shown as off.

Expected behavior:
state: "ON"/"OFF" json member should be present in state topic payload
Actual behavior:
state: "ON"/"OFF" json member missing in state topic payload.

### Which version of ESPHome has the issue?

2021.8.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.7.4

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

probably related to color mode changes

### Example YAML snippet

```yaml
substitutions:
  <<: !include secrets.yaml

esphome:
  name: minimal
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG   

ota:
  password: ${ota_password}
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

mqtt:
  broker: ${mqtt_broker}
  username: ${mqtt_username}
  password: ${mqtt_password}
  reboot_timeout: 60s

light:
  - platform: monochromatic
    name: "test_dimmer"
    output: test_output

output:
  - platform: template
    id: test_output
    type: float
    write_action:
      - delay: 0s
```

### Anything in the logs that might be useful for us?

```txt
comparison of MQTT payloads of versions 1.20.4 (good) and 2021.8.0 (bad)

good:
minimal/light/test_dimmer/state
{"state":"OFF","brightness":255}

bad:
minimal/light/test_dimmer/state
{"color_mode":"brightness","brightness":255,"color":{}}

good:
homeassistant/light/minimal/test_dimmer/config
{"schema":"json","brightness":true,"name":"test_dimmer","state_topic":"minimal/light/test_dimmer/state","command_topic":"minimal/light/test_dimmer/command","availability_topic":"minimal/status","unique_id":"ESPlighttest_dimmer","device":{"identifiers":"c45bbe4a93b1","name":"minimal","sw_version":"esphome v1.20.4 Aug 22 2021, 18:23:49","model":"PLATFORMIO_ESP01_1M","manufacturer":"espressif"}}

bad:
homeassistant/light/minimal/test_dimmer/config
{"schema":"json","color_mode":true,"supported_color_modes":["brightness"],"brightness":true,"name":"test_dimmer","state_topic":"minimal/light/test_dimmer/state","command_topic":"minimal/light/test_dimmer/command","availability_topic":"minimal/status","unique_id":"ESPlighttest_dimmer","device":{"identifiers":"c45bbe4a93b1","name":"minimal","sw_version":"esphome v2021.8.0 Aug 22 2021, 18:45:50","model":"PLATFORMIO_ESP01_1M","manufacturer":"espressif"}}
```
