### ISSUE TITLE
xiaomi_lywsd03mmc sensors detected, but no data received anymore

### ISSUE THREAD

**Issue by Kees85** [esphome/issues#2346]
### The problem

Using the platform xiaomi_lywsd03mmc to recieve the data of multiple [LYWSD03MMC sensors](https://www.esphome.io/components/sensor/xiaomi_ble.html?highlight=xiaomi_lywsd03mmc#lywsd03mmc) with [ATC MiThermometer](https://github.com/atc1441/ATC_MiThermometer) custom firmware.

The sensors are detected according to the log, but no data received anymore. The values of the entities in Home Assistant is still 'unknown', also after 1+ hour.  Advertising type in the custom ATC firmware is confirmed to 'Mi Like'.

Not quite sure when receiving data is stopped, but it working 6+ months without issues.

More people experience this?

### Which version of ESPHome has the issue?

v2021.8.0 (and before I guess)

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

At least 2021.8 (and before I guess)

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

esp32_ble_tracker

### Example YAML snippet

```yaml
- platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:4A:9F:C9"
    bindkey: "dc32ce267604d74eadc4ce70f724998d"
    temperature:
      name: "Bewaardoos PLA temperatuur"
    humidity:
      name: "Bewaardoos PLA luchtvochtigheid"
    battery_level:
      name: "Bewaardoos PLA batterijniveau"
      
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:01:FE:3E"
    bindkey: "cd5b7e309ce44b32d998b553eb5a48e1"
    temperature:
      name: "Werkkamer temperatuur"
    humidity:
      name: "Werkkamer luchtvochtigheid"
    battery_level:
      name: "Werkkamer batterijniveau"
```

### Anything in the logs that might be useful for us?

```txt
The sensors are detected:

[20:58:47][D][esp32_ble_tracker:620]: Found device A4:C1:38:01:FE:3E RSSI=-53
[20:58:47][D][esp32_ble_tracker:641]:   Address Type: PUBLIC
[20:58:47][D][esp32_ble_tracker:643]:   Name: 'ATC_01FE3E'
```
