### ISSUE TITLE
Compilation not checking for invalid Pull-up/Pull-down configurations on ESP32

### ISSUE THREAD

**Issue by alex-gh** [esphome/issues#2352]
### The problem

It is possible to select an invalid pull-up configuration on ESP32 by setting the INPUT_PULLUP mode on a GPIO34-39.
This should not be possible since those pins do not have pull-ups or pull-downs.

I have expected the compiler to catch this mistake and abort the compilation, instead the compilation proceeded normally.

### Which version of ESPHome has the issue?

2021.8.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

gpio

### Example YAML snippet

```yaml
esphome:
  name: test
  platform: ESP32
  board: nodemcu-32s

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO35
      mode: INPUT_PULLUP
    name: "Invalid Pullup Pin"
```

### Additional information

There is code that could have caught the mistake, but apparently it does not get called:

https://github.com/esphome/esphome/blob/2021.8.0/esphome/pins.py#L131
