### ISSUE TITLE
New RGBCT component has backwards color temperature on ATHOM 15w RGB bulb

### ISSUE THREAD

**Issue by mew1033** [esphome/issues#2361]
### The problem

I just converted from a custom light component (https://github.com/jaddel/ESPHome-Configurations/tree/master/Devices/Bulb%20Athom%2015W%20RGBWCT) to the new RGBCT component (https://esphome.io/components/light/rgbct.html). It works great, thank you! However, the color temperature slider is backwards. Sliding it to the cool side makes my bulb warmer and vice-versa. I'm not sure if I have a bad config, or if the component is backwards. It was working a while back with the custom component I linked above, although in recent versions the custom component wasn't working at all (it would turn on/off, but couldn't control anything else).

Here's the relevant yaml part I'm using now:
```yaml
output:
  - platform: esp8266_pwm
    pin: GPIO13
    id: out_ct
  - platform: esp8266_pwm
    pin: GPIO5
    id: out_ctbrightness
  - platform: esp8266_pwm
    pin: GPIO4
    id: out_red
  - platform: esp8266_pwm
    pin: GPIO12
    id: out_green
  - platform: esp8266_pwm
    pin: GPIO14
    id: out_blue


light:
  - platform: rgbct
    name: "${friendly_name}"
    red: out_red
    green: out_green
    blue: out_blue
    color_temperature: out_ct
    white_brightness: out_ctbrightness
    cold_white_color_temperature: 166 mireds
    warm_white_color_temperature: 333 mireds
    color_interlock: True
```
I got the numbers for the color temperature from here: https://github.com/jaddel/ESPHome-Configurations/blob/master/Devices/Bulb%20Athom%2015W%20RGBWCT/athom_15w.h#L13-L14 I have no idea if they're correct, nor do I know how to find out.

Thanks!

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.8.8

### What platform are you using?

ESP8266

### Component causing the issue

RGBCT

### Example YAML snippet

```yaml
output:
  - platform: esp8266_pwm
    pin: GPIO13
    id: out_ct
  - platform: esp8266_pwm
    pin: GPIO5
    id: out_ctbrightness
  - platform: esp8266_pwm
    pin: GPIO4
    id: out_red
  - platform: esp8266_pwm
    pin: GPIO12
    id: out_green
  - platform: esp8266_pwm
    pin: GPIO14
    id: out_blue


light:
  - platform: rgbct
    name: "${friendly_name}"
    red: out_red
    green: out_green
    blue: out_blue
    color_temperature: out_ct
    white_brightness: out_ctbrightness
    cold_white_color_temperature: 166 mireds
    warm_white_color_temperature: 333 mireds
    color_interlock: True
```
