### ISSUE TITLE
Brightness change transition won't work on effects anymore

### ISSUE THREAD

**Issue by mutlucan96** [esphome/issues#2362]
### The problem

I use the FastLED component to drive WS8211 LEDs. After updating to 2021.8.0 (don't remember the previous version but probably was 1.19.?) transitions started don't apply when there is an effect running even if I explicitly define transition-duration on brightness change call. 

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.8

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

fastled

### Example YAML snippet

```yaml
- platform: fastled_clockless
    chipset: WS2811
    pin: D8
    id: tavan
    num_leds: 120
    rgb_order: BRG
    name: "Tavan Şeritt"
    color_correct: [95%, 95%, 90%]
    effects:
      - addressable_rainbow:
          speed: 5
          width: 120
      - addressable_random_twinkle:
          twinkle_probability: 40%
```
