### ISSUE TITLE
DSMR component givens "No checksum found" with DSMR2

### ISSUE THREAD

**Issue by peterforeman** [esphome/issues#2363]
### The problem

I tried to use the DSMR component to read my DSMR2 meter. This works fine with my custom DSMR component, but now there's a built-in component I'd like to use this.

I have a DSMR2, configured the UART component on Serial2 (pin 16/17), baudrate 9600, 7 data bits, no parity and 1 stopbit. 

The data now comes flowing in, but the component complains about not finding the checksum after the '!'. That is correct: DSMR2 does not have a checksum.

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Not relevant (2021.7.4)

### What platform are you using?

ESP32

### Board

ESP32 devkit

### Component causing the issue

dsmr

### Example YAML snippet

```yaml
uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  data_bits: 7
  parity: NONE
  stop_bits: 1
  
dsmr:

  - platform: dsmr
    energy_delivered_tariff1:
      name: "Consumption Low Tariff Sensor"
    energy_delivered_tariff2:
      name: "Consumption High Tariff Sensor"
(etc.)
```

### Anything in the logs that might be useful for us?

```txt
No checksum found
```
