### ISSUE TITLE
Sonoff S31s with total_daily_energy enabled reboot

### ISSUE THREAD

**Issue by tschundler** [esphome/issues#2366]
### The problem

The devices work file with `total_daily_energy` disabled. But with `total_daily_energy` enabled, they periodically reboot. I added uptime measurement, and it isn't a consistent amount of time - as little as a few minutes and as long as many hours. But I have noticed it reboots sooner on devices using more power.

Is there some sort of possible overflow + divide by zero happening.

It is measuring Watt-hours, not kWh. I'm suspicious this might occur 1000x less if I switch to kWh, but I haven't tested that yet.

### Which version of ESPHome has the issue?

v2021.8.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.8.8

### What platform are you using?

ESP8266

### Board

Sonoff S31

### Component causing the issue

total_daily_energy

### Example YAML snippet

```yaml
`esphome config s31_2.yaml`


substitutions:
  device_prefix: s31_2
  device_hostname: s31-2
  device_title: S31 2
esphome:
  name: s31-2
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  esp8266_restore_from_flash: true
  arduino_version: platformio/espressif8266@2.6.2
  build_path: s31-2
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
captive_portal: {}
debug: {}
logger:
  baud_rate: 0
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
  esp8266_store_log_strings_in_flash: true
web_server:
  port: 80
  css_url: https://esphome.io/_static/webserver-v1.min.css
  js_url: https://esphome.io/_static/webserver-v1.min.js
status_led:
  pin:
    number: 13
    mode: OUTPUT
    inverted: false
binary_sensor:
- platform: gpio
  pin:
    number: 0
    mode: INPUT_PULLUP
    inverted: true
  id: s31_2_button
  disabled_by_default: true
  internal: true
  on_press:
  - then:
    - light.toggle:
        id: s31_2_relayl
  name: s31_2_button
- platform: status
  name: S31 2 Status
  disabled_by_default: false
  device_class: connectivity
output:
- platform: gpio
  id: s31_2_relay
  pin:
    number: 12
    mode: OUTPUT
    inverted: false
light:
- platform: binary
  name: S31 2 Relay
  output: s31_2_relay
  id: s31_2_relayl
  disabled_by_default: false
  restore_mode: RESTORE_DEFAULT_OFF
uart:
- rx_pin: 3
  baud_rate: 4800
  rx_buffer_size: 256
  stop_bits: 1
  data_bits: 8
  parity: NONE
text_sensor:
- platform: template
  name: S31 2 Uptime Human
  id: s31_2_uptime_human
  icon: mdi:clock-start
  internal: false
  disabled_by_default: true
  update_interval: 60s
sensor:
- platform: uptime
  name: S31 2 Uptime
  id: s31_2_uptime_sensor
  update_interval: 60s
  internal: false
  disabled_by_default: true
  on_raw_value:
  - then:
    - text_sensor.template.publish:
        id: s31_2_uptime_human
        state: !lambda |-
          int seconds = round(id(s31_2_uptime_sensor).raw_state);
          int days = seconds / (24 * 3600);
          seconds = seconds % (24 * 3600);
          int hours = seconds / 3600;
          seconds = seconds % 3600;
          int minutes = seconds /  60;
          seconds = seconds % 60;
          return (
            (days ? String(days) + "d " : "") +
            (hours ? String(hours) + "h " : "") +
            (minutes ? String(minutes) + "m " : "") +
            (String(seconds) + "s")
          ).c_str();
  force_update: false
  unit_of_measurement: s
  icon: mdi:timer-outline
  accuracy_decimals: 0
  state_class: ''
- platform: cse7766
  current:
    name: S31 2 Current
    internal: false
    disabled_by_default: true
    force_update: false
    unit_of_measurement: A
    accuracy_decimals: 2
    device_class: current
    state_class: measurement
  voltage:
    name: S31 2 Voltage
    internal: false
    disabled_by_default: true
    force_update: false
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement
  power:
    name: S31 2 Power
    id: s31_2_power
    internal: false
    disabled_by_default: false
    force_update: false
    unit_of_measurement: W
    accuracy_decimals: 1
    device_class: power
    state_class: measurement
  update_interval: 60s
- platform: total_daily_energy
  name: S31 2 Daily Energy
  power_id: s31_2_power
  disabled_by_default: false
  force_update: false
  device_class: energy
  state_class: measurement
  last_reset_type: auto
  min_save_interval: 0s
time:
- platform: sntp
  servers:
  - mythbox.local
  - north-america.pool.ntp.org
  timezone: PST8PDT7,M3.2.0/2,M11.1.0/2
  update_interval: 15min
wifi:
  ap:
    ssid: S31 2 Setup
    password: !secret 'wifi_password'
    ap_timeout: 1min
  enable_mdns: true
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  networks:
  - ssid: XXREDACTEDXX
    password: XXREDACTEDXX
    priority: 0.0
  use_address: s31-2.local
mqtt:
  broker: 192.168.1.180
  username: ''
  password: ''
  discovery: true
  port: 1883
  discovery_retain: true
  discovery_prefix: homeassistant
  topic_prefix: s31-2
  keepalive: 15s
  reboot_timeout: 15min
  birth_message:
    topic: s31-2/status
    payload: online
    qos: 0
    retain: true
  will_message:
    topic: s31-2/status
    payload: offline
    qos: 0
    retain: true
  shutdown_message:
    topic: s31-2/status
    payload: offline
    qos: 0
    retain: true
  log_topic:
    topic: s31-2/debug
    qos: 0
    retain: true
ota:
  password: XXREDACTEDXX
  safe_mode: true
  port: 8266
  reboot_timeout: 5min
  num_attempts: 10
```
```


### Anything in the logs that might be useful for us?

```txt
Serial logging on the S31 interferes with the power sensor, so I'm not sure I'll be able to get good logs. I tried enabling debug logging over MQTT, but didn't notice anything noteworthy.
```
