### ISSUE TITLE
Monochromatic ledc PWM. Dimming non linear

### ISSUE THREAD

**Issue by sicknesz** [esphome/issues#2369]
### The problem

Im using esphome to drive a meanwell driver LED, and it's shipped with a potentiometer that i replaced by an esp running esphome, but the problem (not sure if esphome is responsible or the circuit (using an octocoupler) but 
40% on the pot = 5000 lux but 40% with esphome = 900 lux and i need to rise up to 86% to get the 5000x  i get from 40% with the pot.

I've read about a quite similar issue and you pointed to gamma_correction, i have it set to 1.0, what should the value be to have esp's % match the pot's % ?

the circuit is a simple esp => resistor 330omh => PC817 => dim wire on the driver, could it be the restistor value ?

Thanks.
Sicknesz. 

### Which version of ESPHome has the issue?

ESPHome version 1.16.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.8

### What platform are you using?

ESP32

### Board

esp32

### Component causing the issue

ledc

### Example YAML snippet

```yaml
- platform: ledc
    pin: 23
    frequency: 1220 Hz
    inverted: true
    id: light_pwm
    channel: 0
    
light:
  - platform: monochromatic
    name: "Light"
    output: light_pwm
    gamma_correct: 1.0
```
