### ISSUE TITLE
SCD30 CO2 no "statistics" available in Home Assistant

### ISSUE THREAD

**Issue by shaunbro** [esphome/issues#2376]
### The problem

ESPHome 2021.8.2

Home Assistant does not provide statistics for CO2 measurements for this device. 

Running Validate against the config shows that device_class is not set, manually setting to "carbon_dioxide" does not seem to change the behaviour. Temperature and Humidity show correctly.

`- platform: scd30
  co2:
    name: SCD30 CO2
    accuracy_decimals: 1
    device_class: carbon_dioxide
    disabled_by_default: false
    force_update: false
    unit_of_measurement: ppm
    icon: mdi:molecule-co2
    state_class: measurement`

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.8.8

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

SCD30

### Example YAML snippet

```yaml
sensor:
  - platform: scd30
    co2:
      name: "SCD30 CO2"
      accuracy_decimals: 1
      device_class: "carbon_dioxide"
    temperature:
      name: "SCD30 Temperature"
      accuracy_decimals: 1
    humidity:
      name: "SCD30 Humidity"
      accuracy_decimals: 1
    address: 0x61
    update_interval: 5s
```
