### ISSUE TITLE
pulse_meter with totals to use state class totals_increasing

### ISSUE THREAD

**Issue by ptr727** [esphome/issues#2383]
### The problem

See: https://developers.home-assistant.io/blog/2021/08/16/state_class_total/

The pulse_meter integration with totals uses measurement as state class.
Change default to use totals_increasing.

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.9

### What platform are you using?

ESP32

### Board

esp32-devkitc

### Component causing the issue

pulse_meter

### Example YAML snippet

```yaml
# https://esphome.io/components/sensor/index.html
sensor:
  # https://esphome.io/components/sensor/pulse_meter.html
  # https://esphome.io/components/sensor/pulse_counter.html
  - platform: pulse_meter
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
    unit_of_measurement: 'gal/min'
    name: ${device_name}_water_meter
    icon: 'mdi:water'
    # device_class: 'water'
    filters:
      - multiply: 10
    total:
      name: ${device_name}_water_meter_total
      icon: 'mdi:water'
      # device_class: 'water'
      # state_class: 'total_increasing'
      unit_of_measurement: 'gal'
      filters:
      - multiply: 10
  - platform: pulse_meter
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
    unit_of_measurement: 'ft³/min'
    name: ${device_name}_gas_meter
    icon: 'mdi:fire'
    device_class: 'gas'
    filters:
      - multiply: 10
    total:
      name: ${device_name}_gas_meter_total
      icon: 'mdi:fire'
      device_class: 'gas'
      state_class: 'total_increasing'
      id: gas_total
      unit_of_measurement: 'ft³'
      filters:
      - multiply: 10
  # https://esphome.io/components/sensor/template.html
  - platform: template
    name: ${device_name}_gas_meter_total_m3
    device_class: 'gas'
    state_class: 'total_increasing'
    unit_of_measurement: 'm³'
    lambda: |-
      return id(gas_total).state / 35.315;
```

### Anything in the logs that might be useful for us?

```txt
2021-09-02 13:58:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 289, in complete_setup
    infos, services = await entry_data.async_load_from_store()
  File "/usr/src/homeassistant/homeassistant/components/esphome/entry_data.py", line 145, in async_load_from_store
    self.device_info = DeviceInfo.from_dict(restored.pop("device_info"))
KeyError: 'device_info'
```

### Additional information

Trying to get my gas meter to show up as a gas meter in HA, no luck so far, but investigating I did see the required change in state class.
After making the change to state class the device no longer shows up in HA.
