### ISSUE TITLE
CVE-2021-28139 

### ISSUE THREAD

**Issue by RubenKelevra** [esphome/issues#2384]
### The problem

I was wondering if CVE-2021-28139 is already patched or when a patch is expected to be available?

Reference: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28139 
News: https://amp.thehackernews.com/thn/2021/09/new-braktooth-flaws-leave-millions-of.html#aoh=16306671538768&csi=0

### Which version of ESPHome has the issue?

yes

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

yes

### What platform are you using?

ESP32

### Component causing the issue

Bluetooth library

**Comment by oxan** [comment]
Unfortunately, for the moment, we don't use the IDF from Espressif directly, but through the Arduino framework, which means we're dependent upon them merging the fixes before we can use them. Complicating matters somewhat is that ESPHome has been using the v1.0.x series of the Arduino framework, while Arduino has very recently released v2.0.0. This new major version has incompatibilities for which ESPHome will need to be changed, and history has shown us that new major versions often come with hard-to-debug regressions rendering devices or their connection unstable.

At the time of writing, ESPHome uses Arduino v1.0.6 by default, which seems to be vulnerable. There is no stable version of the Arduino v1.0.x series that uses a patched version of the IDF. Arduino v2.0.0 has the patched IDF, but isn't usable with ESPHome yet. (All based on the patched versions referenced in the Espressif [advisory](https://www.espressif.com/sites/default/files/advisory_downloads/AR2021-004%20Bluetooth%20Security%20Advisory.pdf)).

That said, there is a mitigation available. The `idf-release/v3.3` [development branch](https://github.com/espressif/arduino-esp32/commits/idf-release/v3.3) of Arduino contains v1.0.6 (the current default) with a patched IDF (since commit [1a49760e](https://github.com/espressif/arduino-esp32/commit/1a49760eb671229da4728b64ebb9dffc66d501cd). You can use this branch with ESPHome by putting this in your YAML:
```yaml
esphome:
  platformio_options:
    platform_packages:
      framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#idf-release/v3.3
```

Note that this uses a development branch, so occasionally things might break. You can also pin the first fixed commit in that branch by using this:
```yaml
esphome:
  platformio_options:
    platform_packages:
      framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#1a49760eb671
```
