### ISSUE TITLE
ESPhome not working if not connected to wifi, even if wifi not needed

### ISSUE THREAD

**Issue by jbrepogmailcom** [esphome/issues#2385]
### The problem

Hello, I want to use ESPhome in place where is no wifi. It communicates over GSM. When the esp32 chip does not detect wifi network that it can connect to, it does not work and does not use uart to connect to GSM module.

I am aware that wifi component is mandatory, but other parts of ESPhome should work even if wifi connection is not available, right? Is there any workaround, like putting in ap mode permanently, spawning own wifi access point and then connect to it, etc?

Thank you very much, Jan

### Which version of ESPHome has the issue?

latest

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

not using HA

### What platform are you using?

ESP32

### Board

esp32 + sim800l (TTGO)

### Component causing the issue

wifi

### Example YAML snippet

```yaml
wifi:
  ssid: 'invalid'
  password: 'invalid'
  fast_connect: true
  reboot_timeout: 0s
  ap:
    ssid: "thermostat"
    ap_timeout: 1s
```
