### ISSUE TITLE
DSMR Creates GAS sensor, but unable to use in energy dashboard

### ISSUE THREAD

**Issue by Johnwulp** [esphome/issues#2386]
### The problem

I have a DSMR P1 board in ESPHome. It fetches gas m3 correctly.
In homeassistant is use the utility meter to record data from this sensor.

When configuring the energy dashboard, both sensors can not be selected

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.1

### What platform are you using?

ESP8266

### Board

wemos d1 mini

### Example YAML snippet

```yaml
esphome:
  name: p1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret ssid
  password: !secret ssidpwd
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "P1 Fallback Hotspot"
    password: "xxx"

captive_portal:

# Enable logging
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False
  baud_rate: 0

# Enable Home Assistant API
api:
  password: "xxx"

ota:
  password: "xxx"

uart:
  - rx_pin: D2
    baud_rate: 115200
    id: uart_bus

switch:
  - platform: gpio
    pin: D5
    name: "P1 Request Data"
    restore_mode: ALWAYS_ON
    
sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_returned:
      name: "Power Produced"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    current_l1:
      name: "Current Phase 1"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_returned_l1:
      name: "Power Produced Phase 1"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    gas_delivered:
      name: "Gas Consumed"

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
```

### Anything in the logs that might be useful for us?

```txt
I Think the utility meter is missing the device_class property for this meter. Not sure how to resolve it.
```

### Additional information

Snip from esphome log:
```[19:55:01][D][sensor:131]: 'Gas Consumed': Sending state 5468.00098 m³ with 3 decimals of accuracy```

Utility gas meter:
![utilitygas](https://i.imgur.com/tgAO7VB.png "Utility gas meter")

Gas sensor from esphome:
![gassensor](https://i.imgur.com/291Pp9e.png "Gas sensor from ESPHome")
