### ISSUE TITLE
WARNING (MainThread) [homeassistant.components.mqtt.light.schema_json] Invalid color mode received

### ISSUE THREAD

**Issue by joe-sydney** [esphome/issues#2388]
### The problem

Note this is may be related to the CWWW bug (#2358 ) which I reported and got fixed (in that the lights are discovered by HA, and working).

I notice that my HA log is getting a lot of warnings of invalid color mode:
WARNING (MainThread) [homeassistant.components.mqtt.light.schema_json] Invalid color mode received

When I turn on debug for the mqtt component, I found 2 of the above warnings is preceded by 1 of following debug logs:

DEBUG (MainThread) [homeassistant.components.mqtt] Received message on my_light/light/my_light/state (retained): b'{"color_mode":"cwww","state":"OFF","brightness":255,"color":{"c":255,"w":69}}'

This does not seem to be affecting the operation of the light, but thought perhaps there is something that needs cleaning up.

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.8.8

### What platform are you using?

ESP8266

### Component causing the issue

mqtt, light

### Example YAML snippet

```yaml
output:
  - platform: esp8266_pwm
    pin: 5
    id: output_warmwhite
  - platform: esp8266_pwm
    pin: 4
    id: output_coldwhite

light:
  - platform: cwww
    name: "${name}"
    id: light2
    cold_white: output_coldwhite
    warm_white: output_warmwhite
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
```

### Anything in the logs that might be useful for us?

```txt
DEBUG (MainThread) [homeassistant.components.mqtt] Received message on my_light/light/my_light/state (retained): b'{"color_mode":"cwww","state":"OFF","brightness":255,"color":{"c":255,"w":69}}'
WARNING (MainThread) [homeassistant.components.mqtt.light.schema_json] Invalid color mode received
WARNING (MainThread) [homeassistant.components.mqtt.light.schema_json] Invalid color mode received
```
