### ISSUE TITLE
BLE_CLIENT: Issue Decoding Multiple Characteristics

### ISSUE THREAD

**Issue by mwolter805** [esphome/issues#2390]
### The problem

When decoding BLE from a Weber iGrill2, only the first temperature probe is reported. The remaining three probes and the battery are not available (entities are unknown in HA). 

![Screen Shot 2021-09-04 at 7 37 15 AM](https://user-images.githubusercontent.com/24851651/132098189-ed5c4be2-efa1-4dc1-8f95-d8d845d803fe.jpg)

### Which version of ESPHome has the issue?

2021.8.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.8.6

### What platform are you using?

ESP32

### Board

Olimex ESP32-POE

### Component causing the issue

BLE_CLIENT

### Example YAML snippet

```yaml
substitutions:
  esp32_name: ble-test
  
  prefix: ble_test
  friendly_name: BLE Test
  
  # Weber iGrill2
  igrill_friendly_name: Weber iGrill 2

esphome:
  name: ${esp32_name}
  platform: ESP32
  board: esp32-poe

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  use_address: 192.168.6.10
  enable_mdns: false

# Enable logging
logger:
  # level: VERY_VERBOSE
  level: debug
  logs:
    esp32_ble_tracker: error

# Enable Home Assistant API
api:
  password: "pass"

# Enable over-the-air flashing
ota:
  password: "pass"

time:
  - platform: homeassistant

esp32_ble_tracker:

ble_client:
  - mac_address: 70:91:8F:18:EA:E8
    id: weber_igrill2

switch:
  - platform: restart
    name: "${friendly_name} Restart"
    id: ${prefix}_restart_switch

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime Sensor"
    id: ${prefix}_uptime
    

# Weber iGrill2    

  # First Temperature Probe
  - platform: ble_client
    ble_client_id: weber_igrill2
    id: weber_igrill2_p1
    name: "${igrill_friendly_name} Probe 1"
    service_uuid: 'ada7590f-2e6d-469e-8f7B-1822b386a5e9'
    characteristic_uuid: '06ef0002-2e06-4b79-9e33-fce2c42805ec'
    notify: true
    accuracy_decimals: 0
    unit_of_measurement: '°F'
    device_class: temperature
    lambda: |-
      return (float)x[0];

  # Second Temperature Probe
  - platform: ble_client
    ble_client_id: weber_igrill2
    id: weber_igrill2_p2
    name: "${igrill_friendly_name} Probe 2"
    service_uuid: 'ada7590f-2e6d-469e-8f7B-1822b386a5e9'
    characteristic_uuid: '06ef0004-2e06-4b79-9e33-fce2c42805ec'
    notify: false
    accuracy_decimals: 0
    unit_of_measurement: '°F'
    device_class: temperature
    lambda: |-
      return (float)x[0];
      
  # Third Temperature Probe
  - platform: ble_client
    ble_client_id: weber_igrill2
    id: weber_igrill2_p3
    name: "${igrill_friendly_name} Probe 3"
    service_uuid: 'ADA7590F-2E6D-469E-8F7B-1822B386A5E9'
    characteristic_uuid: '06EF0006-2E06-4B79-9E33-FCE2C42805EC'
    notify: false
    accuracy_decimals: 0
    unit_of_measurement: '°F'
    device_class: temperature

  # Fourth Temperature Probe
  - platform: ble_client
    ble_client_id: weber_igrill2
    id: weber_igrill2_p4
    name: "${igrill_friendly_name} Probe 4"
    service_uuid: 'ADA7590F-2E6D-469E-8F7B-1822B386A5E9'
    characteristic_uuid: '06EF0008-2E06-4B79-9E33-FCE2C42805EC'
    notify: false
    accuracy_decimals: 0
    unit_of_measurement: '°F'
    device_class: temperature
  
  # Battery    
  - platform: ble_client
    ble_client_id: weber_igrill2
    id: weber_igrill2_b
    name: "${igrill_friendly_name} Battery"
    service_uuid: '180F'
    characteristic_uuid: '2A19'
    notify: false
    icon: 'mdi:battery'
    accuracy_decimals: 0
    unit_of_measurement: '%'
    device_class: battery
#    update_interval: 10min
    lambda: |-
      return (float)x[0];
```

### Anything in the logs that might be useful for us?

```txt
There are only a few errors in the logs.
[W][ble_sensor:082]: Error reading char at handle 21, status=15
[W][ble_sensor:082]: Error reading char at handle 37, status=15
[W][ble_sensor:082]: Error reading char at handle 41, status=15
[W][ble_sensor:082]: Error reading char at handle 45, status=15
[W][ble_sensor:082]: Error reading char at handle 93, status=15
```

### Additional information

Wifi is not enabled as this board has PoE. Verified the board has not run out of heap. BLE does appear to be working properly with the board as the xiaomi_lywsd03mmc platform reports values correctly. 

Complete Logs at Very Verbose:
[Olimex ESP32-POE iGrill2 Very Verbose 210904.txt.zip](https://github.com/esphome/issues/files/7110046/Olimex.ESP32-POE.iGrill2.Very.Verbose.210904.txt.zip)

Link to working ESP32 Arduino sketch for the Weber iGrill2:
[https://github.com/1mckenna/esp32_iGrill/blob/main/esp32_iGrill.ino](https://github.com/1mckenna/esp32_iGrill/blob/main/esp32_iGrill.ino)
