### ISSUE TITLE
Total Daily Energy sensor does not work as expected

### ISSUE THREAD

**Issue by RubenKelevra** [esphome/issues#2392]
### The problem

I added an energy sensor to measure the consumption defined in a template sensor of the devices.

I was hoping to have it just "work" and HA to figure out when the device was reset and continue the consumption tracking from the last value before the reset. Kind of "overflow" detection should be built-in anyway, right?

But I'm not really getting what I was expected shown in HA:

![screenshot graph energy usage esphome](https://user-images.githubusercontent.com/614929/132282487-f07c53ef-35ac-45ac-a340-e9529df85140.png)

The freshly added sensor works as expected until I reset the device at 20:15 or so. Then HA shows it as 0 again - which means that HA hasn't detected the "overflow" correctly, and assumes that the sensor can run backward - which is kind of expected I guess if we don't specify (somehow) that it's monotonous in one direction.

But afterward, it drops down to 0 again when the sensor get reset at night, jumps up to a value which doesn't make sense, and then stalls, as my sensor tells it, that the consumption dropped to 1.5 W.

When the consumption is raised again to 15 W at around 06:00 the value seems to incorporate some of the previously measured energy consumptions, but not really properly.

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.9.3

### What platform are you using?

ESP8266

### Board

Wemos D1

### Component causing the issue

total_daily_energy

### Example YAML snippet

```yaml
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

substitutions:
  devicename: d1-device1
  friendly_name: DEVICE

# Insert your SSID and Your PWD after inital setup
wifi:
  networks:
    - ssid: "abc"
      password: "def"

# Enable logging
logger:
  logs:
      # Make adc input less verbose
      adc: INFO

# Enable Home Assistant API
api:

# Enable OTA upgrade
ota:
  password: "abc"

sensor:
  # Read LED from adc input 10 times per second
  - platform: adc
    pin: A0
    internal: true
    id: led_internal
    update_interval: 100ms
    accuracy_decimals: 1
    filters:
      - delta: 0.1
    on_value:
      if:
        condition:
          lambda: 'return x < 0.2;'
        then:
          - binary_sensor.template.publish:
              id: led_sensor
              state: OFF
        else:
          - binary_sensor.template.publish:
              id: led_sensor
              state: ON
  - platform: template
    name: '$friendly_name - Power consumption'
    id: power_consumption
    device_class: power
    state_class: measurement
    unit_of_measurement: 'W'
    accuracy_decimals: 1
  - platform: total_daily_energy
    name: "$friendly_name - Energy Usage"
    power_id: power_consumption
    
time:
  - platform: homeassistant

binary_sensor:
  - platform: template
    id: led_sensor
    name: "$friendly_name Filter"
    device_class: problem

output:
  - platform: gpio
    pin: D6
    id: gpio_d6
    inverted: true
  - platform: gpio
    pin: D7
    id: gpio_d7
    inverted: true
  - platform: gpio
    pin: D5
    id: gpio_d5
    inverted: true
  - platform: template
    id: fan_out_internal
    type: float
    write_action:
      if:
        condition:
          lambda: 'return state < 0.1;'
        then:
          - output.turn_off: gpio_d5
          - output.turn_off: gpio_d7
          - output.turn_off: gpio_d6
          - sensor.template.publish:
              id: power_consumption
              state: 0.1

        else:
          - if:
              condition:
                lambda: 'return state < 0.4;'
              then:
                - output.turn_on:  gpio_d5
                - output.turn_off: gpio_d7
                - output.turn_off: gpio_d6
                - sensor.template.publish:
                    id: power_consumption
                    state: 1.5
              else:
                - if:
                    condition:
                      lambda: 'return state < 0.7;'
                    then:
                      - output.turn_off: gpio_d5
                      - output.turn_on:  gpio_d7
                      - output.turn_off: gpio_d6
                      - sensor.template.publish:
                          id: power_consumption
                          state: 6.5
                    else:
                      - output.turn_off: gpio_d5
                      - output.turn_off: gpio_d7
                      - output.turn_on:  gpio_d6
                      - sensor.template.publish:
                          id: power_consumption
                          state: 15

fan:
 - platform: speed
   output: fan_out_internal
   id: fan_internal
   name: "$friendly_name Fan"
   speed_count: 3
```

### Additional information

I found a ticket which might be related, not sure: https://github.com/esphome/issues/issues/2034
