### ISSUE TITLE
supported device_class list not complete

### ISSUE THREAD

**Issue by pejotigrek** [esphome/issues#2394]
### The problem

ESPHome documentation links HomeAssistant's device_class list as the supported list of entries - in the meantime, lots of them are not supported in ESPHome and cause validation errors.

### Which version of ESPHome has the issue?

2021.8.2 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.3

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
- platform: pm1006
  pm_2_5:
    name: "${hostname}_pm25"
    unit_of_measurement: 'μg/m³'
    icon: mdi:air-filter
    state_class: measurement
    accuracy_decimals: 1
    device_class: pm25
```

### Anything in the logs that might be useful for us?

```txt
Unknown value 'pm25', valid options are '', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'energy', 'gas', 'humidity', 'illuminance', 'monetary', 'signal_strength', 'temperature', 'timestamp', 'power', 'power_factor', 'pressure', 'voltage'.
    device_class: pm25
```

### Additional information

https://www.home-assistant.io/integrations/sensor/#device-class clearly shows more allowed values.
