### ISSUE TITLE
Transition time when turning on doesn't work. Turning off does work.

### ISSUE THREAD

**Issue by cooljimy84** [esphome/issues#2397]
### The problem

when setting transition: 10 and turning on the light in home assistant the light waits 9 seconds (totally off) then go to the set brightness in the last 1 second.

service: light.turn_on
target:
  entity_id:
    - light.esp5_led_strip
data:
  transition: 10
  rgbw_color:
    - 255
    - 255
    - 255
    - 255
  brightness_pct: 100

transition off works as expected.

I did have this open [https://github.com/esphome/issues/issues/1558]

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.8.8

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

neopixelbus

### Example YAML snippet

```yaml
esphome:
  name: esp5
  platform: ESP8266
  board: nodemcuv2

status_led:
  pin:
    number: GPIO2
    inverted: true

# Above the hallway door
wifi:
  ssid: 'WIFI'
  password: 'PASSWORD'
  fast_connect: true

mqtt:
  broker: 'IP'
  username: 'USERNAME'
  password: 'PASSWORD'
  reboot_timeout: 4min

# Enable logging
logger:
  level: INFO

ota:
  password: 'PASSWORD'

text_sensor:
  - platform: version
    name: "ESPHome Version ESP5"
    hide_timestamp: true

sensor:
  - platform: uptime
    name: ESP5 Uptime Sensor
    update_interval: 360s
  - platform: wifi_signal
    name: "WiFi Signal ESP5"
    update_interval: 360s

switch:
  - platform: restart
    name: "ESP5 Restart"

e131:
  method: multicast

light:
  - platform: neopixelbus
    type: GRBW
    pin: GPIO3
    num_leds: 59
    name: "ESP5 LED Strip"
    id: mylight
    color_correct: [100%, 100%, 100%, 50%]
    default_transition_length: 0.5s
```

### Anything in the logs that might be useful for us?

```txt
[08:34:45][D][light:038]: 'ESP5 LED Strip' Setting:
[08:34:45][D][light:049]:   State: ON
[08:34:45][D][light:053]:   Brightness: 100%
[08:34:45][D][light:057]:   Color brightness: 100%
[08:34:45][D][light:061]:   Red: 100%, Green: 100%, Blue: 100%
[08:34:45][D][light:065]:   White: 100%
[08:34:45][D][light:087]:   Transition length: 10.0s
```

**Comment by cooljimy84** [comment]
I have also upgraded and tested a fastled_clockless set of LEDs and this has both the same issues.

version 1.13.6 behaves as expected on both on and off.

**Comment by cooljimy84** [comment]
Just tried 1.14.0b1 and the transition time isn't working (though more like the old ticket where i set 10 seconds and it take 3 seconds https://github.com//issues/1558 ) Hope this helps.

**Comment by oxan** [comment]
Can you try with `gamma_correct: 1.0`?

**Comment by cooljimy84** [comment]
Off is now very smooth turning off.
Turning on seems to go straight to 1% brightness and stay there for a few seconds then quickly ramps up.

For example, If i set transition time to 20 seconds 100% brightness 255, 255, 255, 255 color
2 seconds after hitting call service, the leds turn on at 1% brightness.
10-11 seconds after hitting call service, the leds ramp up smoothly to 100% brightness.

**Comment by oxan** [comment]
Seems the fix to make the transition not run fast made it run slow ;-)

Thinking a bit more thoroughly about it than last time, it seems the whole (addressable) transition logic is dubious at best.

**Comment by cooljimy84** [comment]
Thats a shame, as i saw the posts about using it and ended up creating a lamda effect that turns each LED off one by, rather than fading the whole stripe.

**Comment by oxan** [comment]
Could any of you try esphome/esphome#2786 by adding this to your YAML (probably needs 2021.11):
```yaml
external_components:
  - source: github://pr#2786
    components: [ light, fastled, neopixelbus ]
```
