### ISSUE TITLE
Occasional exception

### ISSUE THREAD

**Issue by jara1** [esphome/issues#24]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip

**ESP (ESP32/ESP8266/Board/Sonoff):**

ESP32

**Affected component:**

**Description of problem:**
Several per day I'm observing exception with reboot.
06.01.19 17:13:40.021- COM7 -> Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
06.01.19 17:13:40.047- COM7 -> Core 0 register dump:
06.01.19 17:13:40.072- COM7 -> PC      : 0x400fc937  PS      : 0x00060930  A0      : 0x801501c4  A1      : 0x3ffb78a0  
06.01.19 17:13:40.098- COM7 -> A2      : 0x00000000  A3      : 0x00000001  A4      : 0x0000004a  A5      : 0x0011e0be  
06.01.19 17:13:40.121- COM7 -> A6      : 0x00000006  A7      : 0x00000014  A8      : 0x80106730  A9      : 0x3ffb7870  
06.01.19 17:13:40.140- COM7 -> A10     : 0x3ffb6c28  A11     : 0x3ffc10c0  A12     : 0x3ffb6c88  A13     : 0x00000000  
06.01.19 17:13:40.164- COM7 -> A14     : 0x3ffb6cb4  A15     : 0x00000000  SAR     : 0x00000019  EXCCAUSE: 0x0000001c  
06.01.19 17:13:40.185- COM7 -> EXCVADDR: 0x00000038  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  
06.01.19 17:13:40.212- COM7 -> 
06.01.19 17:13:40.233- COM7 -> Backtrace: 0x400fc937:0x3ffb78a0 0x401501c1:0x3ffb78c0 0x400f6aad:0x3ffb78e0
06.01.19 17:13:40.255- COM7 -> 
06.01.19 17:13:40.275- COM7 -> Rebooting...

another:
06.01.19 17:50:10.923- COM7 -> Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
06.01.19 17:50:10.952- COM7 -> Core 1 register dump:
06.01.19 17:50:10.976- COM7 -> PC      : 0x400fc937  PS      : 0x00060530  A0      : 0x801501c4  A1      : 0x3ffb7930  
06.01.19 17:50:11.001- COM7 -> A2      : 0x00000000  A3      : 0x00000001  A4      : 0x0000000c  A5      : 0x00216ce3  
06.01.19 17:50:11.027- COM7 -> A6      : 0x00000000  A7      : 0x0000fc6c  A8      : 0x80106730  A9      : 0x3ffb7900  
06.01.19 17:50:11.049- COM7 -> A10     : 0x3ffb6cb8  A11     : 0x3ffc10c0  A12     : 0x3ffb6d18  A13     : 0x00000000  
06.01.19 17:50:11.069- COM7 -> A14     : 0x3ffb6d44  A15     : 0x00000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
06.01.19 17:50:11.090- COM7 -> EXCVADDR: 0x00000038  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  
06.01.19 17:50:11.113- COM7 -> 
06.01.19 17:50:11.138- COM7 -> Backtrace: 0x400fc937:0x3ffb7930 0x401501c1:0x3ffb7950 0x400f6aad:0x3ffb7970
06.01.19 17:50:11.157- COM7 -> 
06.01.19 17:50:11.181- COM7 -> Rebooting...
06.01.19 17:50:11.202- COM7 -> ets Jun  8 2016 00:22:57

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: test
  platform: ESP32
  board: esp32doit-devkit-v1

debug:

wifi:
  ssid: 'xxx'
  password: 'xxx'

mqtt:
  broker: 'xxx'
  username: 'homeassistant'
  password: 'xxx'

# Enable logging
logger:
#  level: VERY_VERBOSE
  level: DEBUG
#  logs:
#    mqtt.component: DEBUG
#    mqtt.client: ERROR

ota:

switch:
  - platform: gpio
    name: "LED"
    pin: 2

uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 60    
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 60
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 60
```

**Traceback (if applicable):**

```

```

**Additional information:**
