### ISSUE TITLE
ble RF Compatibility issues

### ISSUE THREAD

**Issue by amigomcu** [esphome/issues#2401]
### The problem

hi all, 
now i see a error with ble  notify Packet then my peripheral to enable CCCD.
So,i peripheral not start send sensor data(notify) to ESPhome(central).
(i can sure this peripheral work correctly with phone).

have anyone  know the answer of the question?

### Which version of ESPHome has the issue?

v2021.8.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.9.2

### What platform are you using?

ESP32

### Board

esp32 devkit

### Component causing the issue

ble_client

### Example YAML snippet

```yaml
esphome:
  name: ble-gateway
  platform: ESP32
  board: esp-wrover-kit


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "2cdc6c8521424fee60adf7cb2aefacb6"


wifi:
  ssid: "Tenda_xxx"
  password: "xxxx"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ble-Gateway Fallback Hotspot"
    password: "hQpUPVnDcgia"

captive_portal:

# Bluetooth activation  
esp32_ble_tracker:

binary_sensor:
  - platform: template
    id: black_button
    name: "Black iTag Button"
    filters:
      delayed_off: 200ms

ble_client:
  - mac_address: E7:16:13:14:xx:xx
    id: ble_thing

sensor:
  - platform: ble_client
    ble_client_id: ble_thing
    name: "thing battery level"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    notify: true
    icon: 'mdi:battery'
    accuracy_decimals: 0
    unit_of_measurement: '%'
    
  - platform: ble_client
    ble_client_id: ble_thing
    name: "thing Humidity"
    service_uuid: 'EF680200-9B35-4933-9B10-52FFA9740042'
    characteristic_uuid: 'EF680203-9B35-4933-9B10-52FFA9740042'
    notify: true
    update_interval: never
    device_class: "humidity"
    state_class: "measurement"
    accuracy_decimals: 0
    unit_of_measurement: '%'
    on_notify:
      then:
          - logger.log: "Light Turned on!"
```

### Additional information

phone:
![phone_connect_writeCCCD](https://user-images.githubusercontent.com/23089799/132527677-0ea05eaf-183e-47b7-8592-033a424240e2.png)

ESP32:
![esp32_connect_writeCCCD](https://user-images.githubusercontent.com/23089799/132527834-d8f3d0fa-bdeb-4aa0-a537-6b6d5cc583ce.png)
