### ISSUE TITLE
TinyPico does not boot with default yaml

### ISSUE THREAD

**Issue by crlogic** [esphome/issues#2402]
### The problem

Manually flashing ESPHome to a TinyPico does not boot.

Serial output:
`rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3f400020,len:248852
ets Jun  8 2016 00:22:57`

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.4

### What platform are you using?

ESP32

### Board

TinyPico

### Component causing the issue

N/A

### Example YAML snippet

```yaml
esphome:
  name: tinypico-outside
  platform: ESP32
  board: tinypico

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "longstring"

wifi:
  ssid: "wifi"
  password: "wifi secret"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tinypico-Outside"
    password: "pass"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
Flashing process used:

esptool.py -p COM23 read_mac
esptool.py -p COM23 erase_flash
esptool.py --chip esp32 --port COM23 write_flash -fm dio -z 0x1000 tinypico-outside.bin
```
`-fm dio` used at the recommendation of UnExpectedMaker on Discord. The default QIO exhibited the same behavior.
Restoring to MicroPython v1.16 works fine.
```


### Additional information

_No response_
