### ISSUE TITLE
brightness-only lights don't report state back to MQTT properly

### ISSUE THREAD

**Issue by thinkl33t** [esphome/issues#2404]
### The problem

Brightness-only lights don't appear to be sending an ON/OFF state update back to MQTT anymore, so home-assistant doesn't know they're turned on / off

When turning light on from webui / mqtt:

```
usbinlinepwmmer_rubbertree/light/rubber_tree_lights/command {"state": "ON"}
usbinlinepwmmer_rubbertree/debug [D][light:038]: 'Rubber Tree Lights' Setting:
usbinlinepwmmer_rubbertree/debug [D][light:049]:   State: ON
usbinlinepwmmer_rubbertree/debug [D][light:087]:   Transition length: 1.0s
usbinlinepwmmer_rubbertree/light/rubber_tree_lights/state {"effect":"None","color_mode":"brightness","brightness":255,"color":{}}
```

When turning light off from webui / mqtt:

```
usbinlinepwmmer_rubbertree/light/rubber_tree_lights/command {"state": "OFF"}
usbinlinepwmmer_rubbertree/debug [D][light:038]: 'Rubber Tree Lights' Setting:
usbinlinepwmmer_rubbertree/debug [D][light:049]:   State: OFF
usbinlinepwmmer_rubbertree/debug [D][light:087]:   Transition length: 1.0s
usbinlinepwmmer_rubbertree/light/rubber_tree_lights/state {"effect":"None","color_mode":"brightness","brightness":255,"color":{}}
```

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.9.5

### What platform are you using?

ESP8266

### Board

esp-07

### Component causing the issue

light

### Example YAML snippet

```yaml
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

<<: !include common/wifi.yaml
<<: !include common/mqtt.yaml
<<: !include common/ota.yaml

api:

logger:

web_server:
  port: 80

light:
  - platform: monochromatic
    name: $devicename_friendly
    output: output_pin
    id: the_light
    effects:
      - flicker:
          intensity: 15%
          alpha: 90%
output:
  - platform: esp8266_pwm
    id: output_pin
    pin: D4

binary_sensor:
  - platform: gpio
    id: gpio_zero
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: the_light
```
