### ISSUE TITLE
PID climate heat action when climate mode set to cool and vice versa

### ISSUE THREAD

**Issue by crashbash2020** [esphome/issues#2406]
### The problem

Not 100% sure this is a bug, but i read through the important information in climate action vs climate mode, so i don't think this is a misunderstanding. Also the generic home assistant thermostat doesn't have this problem:

When Climate mode is set to "heat", and the set temp is below the current temp, the climate action will set to cooling. (after a few minutes)

When Climate mode is set to "cool", and the set temp is above the current temp, the climate action will set to heating (after a few minutes)

I would expect in both of these scenarios for the climate action to become "idle" as they do in the generic home assistant thermostat.

it seems like to me both "heat" and "cool" climate modes both behave the same as "heat_cool" climate mode

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.9.3

### What platform are you using?

ESP8266

### Board

WEMOS d1 MINI

### Component causing the issue

https://esphome.io/components/climate/pid.html

### Example YAML snippet

```yaml
output:
  - platform: esp8266_pwm
    pin: D3
    frequency: 1000 Hz
    id: pwm_output1

output:
  - platform: esp8266_pwm
    pin: D4
    frequency: 1000 Hz
    id: pwm_output2

climate:
  - platform: pid
    name: 'bedroom3_controller'
    sensor: temperature_sensor
    heat_output: pwm_output1
    cool_output: pwm_output2
    default_target_temperature: 21 °C
    control_parameters: 
      kp: 0.01
      ki: 0.001
      kd: 0
    visual:
      min_temperature: 17 °C
      max_temperature: 32 °C
      temperature_step: 0.1 °C
```

### Additional information

YAML is irrelevant in this case i think
