### ISSUE TITLE
Problem with non-english sensor entities name

### ISSUE THREAD

**Issue by VladNord** [esphome/issues#2407]
### The problem

Hello!
If I use non-english two-word entity sensor names at esphome, where first word is matches the name of the space the device is in, I get an interesting effect of conglutination sensor data into one object, 
Here is example, dht11 sensor
```
sensor:
  - platform: dht
    model: DHT11
    pin: GPIO3
    temperature:
      name: "Балкон Температура"
    humidity:
      name: "Балкон Влажность"
    update_interval: 60s
```
In home assistant i get the following

<img width="413" alt="Снимок экрана 2021-09-11 в 00 19 23" src="https://user-images.githubusercontent.com/51515620/132921848-ec0db40f-bd7c-4118-ba08-fe15c6101238.png">

Temperature and humidity on one graph :)

and get the following error in the log

`Platform esphome does not generate unique IDs.`

if I change the space, rename item into two-word English or one word non-english its working like a charm

<img width="348" alt="image" src="https://user-images.githubusercontent.com/51515620/132922301-2b3bfe55-0bdf-42db-a6e1-fe5a1df9ca96.png">

Same situation with Sonoff pow r2 sensor.

Thanks for help!

### Which version of ESPHome has the issue?

2021.8.2 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.5 

### What platform are you using?

ESP8266

### Board

2021.9.5

### Component causing the issue

dht, cse7766

### Example YAML snippet

```yaml
esphome:
  name: balkon-podsvetka
  platform: ESP8266
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "704e26531bbfcf2333e403466c27e01e"

wifi:
  ssid: ***
  password: ***

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Balkon-Podsvetka"
    password: "RnzNHElDrE8Q"

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Sonoff Basic Button"
    internal: true
    on_press:
      then:
      - light.toggle: ambient_balkon

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
        
light:
  - platform: binary
    name: "Балкон Подсветка"
    output: relay_1
    id: ambient_balkon
    
sensor:
  - platform: dht
    model: DHT11
    pin: GPIO3
    temperature:
      name: "Балкон Температура"
    humidity:
      name: "Балкон Влажность"
    update_interval: 60s

status_led:
  pin:
    number: GPIO13
    inverted: yes
```

### Anything in the logs that might be useful for us?

```txt
Platform esphome does not generate unique IDs
```
