### ISSUE TITLE
HTU21D Temperature Sensor reading too high because of self heating

### ISSUE THREAD

**Issue by kaiomatico** [esphome/issues#2414]
### The problem

Hello, first of all thank you for esphome :-)
The problem is that the temperature readings of htu21d are 2-3 °C too high and the humidity is 10% too low. This is most likely due to the self heating of the sensor. I have tried setting the update_interval to 5min but it did not help.
I have read this can be fixed by entering deep sleep for 5 minutes, then read the sensor and send it to home assistant and then enter deep sleep again for 5 minutes. I could not get it to work with the following code (because the home assistant api requires a sensor to be available every 60 seconds?):
```
esphome:
  name: wonhzimmer
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "OTA_PASSWORD_HERE"

wifi:
  ssid: "SSID_HERE"
  password: "PASSWORD_HERE"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wonhzimmer Fallback Hotspot"
    password: "PASSWORD2_HERE"

captive_portal:

i2c: 

sensor:
  - platform: htu21d
    temperature:
      name: "Wohnzimmer Temperatur"
    humidity:
      name: "Wohnzimmer Luftfeuchtigkeit"
      
deep_sleep:
  run_duration: 10s
  sleep_duration: 5min
```
So I searched and found out that the heating element could be controlled by a register, see this library: https://github.com/enjoyneering/HTU21D/blob/master/src/HTU21D.h#L57 for the address and https://github.com/enjoyneering/HTU21D/blob/master/src/HTU21D.h#L114 for the value.

Can this be implemented? Thank you very much in advance! In the meantime I will test the linked library too see if the results are better, but I am very confident that they will be.

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.6

### What platform are you using?

ESP8266

### Board

nodemcu v3 / standard basic generic dev module from amazon

### Component causing the issue

htu21d

**Comment by kaiomatico** [comment]
Quick update: It is not the self heating, it is the close proximity to the esp8266 on the prototype board. Every type of sensor suffers from this if they are close to the microcontroller, see this solution: https://github.com/wemos/WEMOS_SHT3x_Arduino_Library/issues/2#issuecomment-362202960

So now my question is: how to use deep sleep with the htu21d sensor and home assistant reliably? I am happy to document it in the docs afterwards :+1:

**Comment by kaiomatico** [comment]
Drasticially improved the reading results by bypassing the sensor breakout board LDO with a solder blob and deep sleeping for a minute between each measurement. See this yaml for my current config which is adjusted to a calibrated reference, so I'm closing this issue now. Maybe the results improve further by placing the sensor vertical instead of horizontal:
```
esphome:
  name: wonhzimmer
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "OTA_PASSWORD"

wifi:
  ssid: "WIFI_SSID"
  password: "WIFI_PASSWORD"
  fast_connect: true

i2c: 

sensor:
  - platform: htu21d
    temperature:
      name: "Wohnzimmer Temperatur"
      filters:
      - offset: -0.8
    humidity:
      name: "Wohnzimmer Luftfeuchtigkeit"
      filters:
      - offset: 3.0
    update_interval: 5s
      
deep_sleep:
  run_duration: 10s
  sleep_duration: 1min
```
