### ISSUE TITLE
Automations fail when cabled Ethernet gets disconnected

### ISSUE THREAD

**Issue by adezerega** [esphome/issues#2415]
### The problem

I have set an ESP32 board with built-in ethernet, with a manual IP address. The idea is that the automations work even if the network goes down. However, as soon as the network goes down (simulated by disconnecting the ethernet cable), the automations stop working.

As long as the network cable is connected, when I trigger input INT01 (with MCP23017 chip), the switch THC01 toggles. When the network cable is not connected, this simple automation stops working. 

As per the documentation, automations should work even if the network is disconnected. The only "side effect" is that the controller resets every 15 mins, since the api: cannot reach home assistant.

I can't disable the Wifi reboot timer, since ESPHome says that I can't have the wifi: component at the same time as the ethernet: component.

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.9.5

### What platform are you using?

ESP32

### Board

LILYGO TTGO T-Internet-POE ESP32 WROOM LAN8270A

### Component causing the issue

ethernet:

### Example YAML snippet

```yaml
esphome:
  name: esp32cabled
  platform: ESP32
  board: esp-wrover-kit
logger:
# Enable Home Assistant API
api:
ota:
i2c:
  sda: 15
  scl: 14
  scan: True
  id: bus_a
esp32_ble_tracker:
time:
  - platform: ds1307
    id: ds1307_time
    address: 0x68
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  manual_ip:
    static_ip: 172.16.1.150
    gateway: 172.16.1.1
    subnet: 255.255.255.0
    dns1: 172.16.1.1
    dns2: 8.8.8.8
mcp23017:
  - id: 'MCP23017_1'
    address: 0x20
  - id: 'MCP23017_2'
    address: 0x21
switch:
  - platform: gpio
    name: "THC01"
    pin:
      mcp23xxx: MCP23017_1
      number: 8
      mode: OUTPUT
      inverted: True
    restore_mode: RESTORE_DEFAULT_OFF
    id: CSW1
binary_sensor:
  - platform: gpio
    name: "INT01"
    pin:
      mcp23xxx: MCP23017_1
      number: 0
      mode: INPUT
      inverted: True
    filters:
      - delayed_on_off: 100ms
    on_state:
      then:
        - switch.toggle: CSW1
```
