### ISSUE TITLE
LightCall `set_transition_length` with value > 0 does not respect `set_publish(false)`

### ISSUE THREAD

**Issue by matthewmazzanti** [esphome/issues#2417]
### The problem

I am attempting to build a "candle flicker" effect via the light effect lambda. This involves reading the brightness set via Home Assistant (the `remote_values` of the light class), and setting a transition via `set_transition_length` to smooth things out. As a part of the effect, I don't want the published light value constantly updating, instead I would like the effect to take into account the value set in Home Assistant.

It seems the call to `set_transition_length(100)` (or any value > 0) causes the light to update its `remote_values` field without updating Home Assistant. It would be preferred if `set_transition_length` respected the `set_publish(false)` value.

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.9.6

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

light

### Example YAML snippet

```yaml
output:
  - platform: esp8266_pwm
    pin: D2
    frequency: 120HZ
    id: J3_pwm

light:
  - platform: monochromatic
    output: J3_pwm
    name: J3
    id: J3
    effects:
      - lambda:
          name: Broken
          update_interval: 100ms
          lambda: |-
            auto call = id(J4)->turn_on();
            float remote = id(J4)->remote_values.get_brightness();
            esph_log_d(__FILE__, "brightness: %f", remote);
            call.set_brightness(remote * 0.5);
            call.set_transition_length(100);
            call.set_publish(false);
            call.set_save(false);
            call.set_state(true);
            call.perform();
```

The output of the above is:
```
[23:57:02][D][candle.yaml:076]: brightness: 1.000000
[23:57:02][D][candle.yaml:076]: brightness: 0.500000
[23:57:03][D][candle.yaml:076]: brightness: 0.250000
[23:57:03][D][candle.yaml:076]: brightness: 0.125000
[23:57:03][D][candle.yaml:076]: brightness: 0.062500
[23:57:03][D][candle.yaml:076]: brightness: 0.031250
[23:57:03][D][candle.yaml:076]: brightness: 0.015625
[23:57:03][D][candle.yaml:076]: brightness: 0.007812
...
```

Changing the call to `set_transition_length(0)` gives the correct output: 
```
[00:09:44][D][candle.yaml:076]: brightness: 1.000000
[00:09:44][D][candle.yaml:076]: brightness: 1.000000
[00:09:44][D][candle.yaml:076]: brightness: 1.000000
[00:09:44][D][candle.yaml:076]: brightness: 1.000000
...
```

### Anything in the logs that might be useful for us?

_No Response_

### Additional information

~~Looking into the history of this it seem that [these changes](https://github.com/esphome/esphome/pull/2124/files#diff-e96397dff2fe7d303bdd0cd720a8b22085dfb8860d7dacde26d01a54f7dc3e8fR220-R235) are the root cause. In particular, the reads and updates of `state->current_values` have been changed to `state->remote_values`.~~
