### ISSUE TITLE
SDM Meter component reports in Wh instead of kWh

### ISSUE THREAD

**Issue by benv666** [esphome/issues#2418]
### The problem

So today I finally got myself to getting the SDM220 I have here hooked up with Home Assistant, which after swapping from pins 16/17 to 13/27 for my uart finally worked. (16/17 made the SDM blink the comms indicator, but did not actually receive anything back - guess that's due to the ESP32 board that I use).

Anyway, the integration has a few fields that report Wh but should imho be kWh.
Home Assistant:
https://i.imgur.com/ABZr7IU.png

The meter's display shows the same(ish) value, but clearly in kWh:
https://i.imgur.com/EJ7zvru.jpg

According to this document it seems all register are in kilo:
https://www.kwhmeter.nl/Files/2/26000/26485/Attachments/Product/2VTT478cg4Op41890nO0M1zH8E0FT4G4.pdf

### Which version of ESPHome has the issue?

docker esphome:latest [2021.8.2]

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.9.5

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

sdm_meter

### Example YAML snippet

```yaml
- platform: sdm_meter
    address: 1
    phase_a:
      voltage:
        name: "${upper_devicename} Voltage"
      current:
        name: "${upper_devicename} Current"
      active_power:
        name: "${upper_devicename} Power"
    import_active_energy:
      name: "${upper_devicename} Import Active Energy"
    export_active_energy:
      name: "${upper_devicename} Export Active Energy"
    update_interval: 5s
```

### Anything in the logs that might be useful for us?

```txt
[15:26:14][D][sdm_meter:067]: SDMMeter: F=50.000 Hz, Im.A.E=185.461 Wh, Ex.A.E=0.000 Wh, Im.R.E=67.795 VARh, Ex.R.E=13.594 VARh
[15:26:14][D][sensor:131]: 'Schuur Frequency': Sending state 50.00000 Hz with 3 decimals of accuracy
[15:26:14][D][sensor:131]: 'Schuur Import Active Energy': Sending state 185.46100 Wh with 2 decimals of accuracy
```

### Additional information

It's easy to work around by adding a `unit_of_measurement: kWh`.
