### ISSUE TITLE
ESP32-c3-devkitm-1 boot issues 

### ISSUE THREAD

**Issue by markusg1234** [esphome/issues#2420]
### The problem

I have found that a ESP32-C3-devkitm-1 no longer boots when I compile new firmware where it was working previously.

Error seen below and it will just keeps outputting these errors.

Regards,

Markus

### Which version of ESPHome has the issue?

v2021.10.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.6

### What platform are you using?

ESP32

### Board

ESP32-c3-devkitm-1

### Component causing the issue

firmware.bin

### Example YAML snippet

```yaml
esphome:
  name: test
  platform: ESP32
  board: esp32-c3-devkitm-1
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32#feature/arduino-idf-master
  
output:
  - id: relay_1
    platform: gpio
    pin: GPIO5
    inverted: true
```

### Anything in the logs that might be useful for us?

```txt
[13:05:36]invalid headeESP-ROM:esp32c3-api1-20210207
[13:05:36]Build:Feb  7 2021
[13:05:36]rst:0x7 (TG0WDT_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
[13:05:36]Saved PC:0x4004d1f8
[13:05:36]invalid header: 0xffffffff
[13:05:36]invalid header: 0xffffffff
```

### Additional information

@jesserockz

**Comment by jesserockz** [comment]
I dont have that board, I have the `ESP-C3-01M-KIT` devboard, and this works (in addition to what you have):

```yaml
esphome:
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
```
