### ISSUE TITLE
nextion tft_url ota update - error

### ISSUE THREAD

**Issue by adamcodemaker** [esphome/issues#2423]
### The problem

I have this display https://nextion.ca/datasheets/nx3224k024_011/
I connected TX form display to RX on board (GPIO3) and RX from display to TX on board (GPIO1)
When I try to update using tft_url it fails.
It starts showing 99%
![16316632449312](https://user-images.githubusercontent.com/25587877/133348575-8bebfdc9-b5d3-473f-8474-a8c1198d78d9.jpg)
and this is strange because tft file is ~455KB
Then after 2min it goes to 100% and the display restarts with error
![16316632448880](https://user-images.githubusercontent.com/25587877/133348807-c408b565-8d16-4e48-bb8c-a0c074f7c98a.jpg)
![16316632449211](https://user-images.githubusercontent.com/25587877/133348838-d150085f-4f54-4e66-9ed1-724f8718b81c.jpg)
![16316632554103](https://user-images.githubusercontent.com/25587877/133348852-4b54b60e-1249-45a6-8c90-aa79db608626.jpg)
Upload works ok from Nextion Editor 1.63.3 using USB-UART PL2303 TA
It also works using SD card.
Communication with display is ok. I can read humidity from mqtt topic and display it.
I tried different board (esp32doit-devkit-v1) but with the same result.

### Which version of ESPHome has the issue?

esphome:2021.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

0.117.0

### What platform are you using?

ESP8266

### Board

nodemcu ESP8266 ESP-12E aka Waveshare 16608 or Amica

### Component causing the issue

display/nextion

### Example YAML snippet

```yaml
substitutions:
  ip_address: 192.168.0.62
esphome:
  name: bedroom-drawer
  platform: ESP8266
  board: nodemcuv2
  arduino_version: platformio/espressif8266@2.6.2
  build_path: bedroom-drawer
  platformio_options: {}
  esp8266_restore_from_flash: false
  board_flash_mode: dout
  includes: []
  libraries: []
  name_add_mac_suffix: false
logger:
  baud_rate: 0
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
  esp8266_store_log_strings_in_flash: true
sensor:
- platform: wifi_signal
  name: WiFi Signal Sensor
  update_interval: 60s
  disabled_by_default: false
  force_update: false
  unit_of_measurement: dBm
  accuracy_decimals: 0
  device_class: signal_strength
  state_class: measurement
switch:
- platform: restart
  name: amica restart
  disabled_by_default: false
  icon: mdi:restart
uart:
- rx_pin: 3
  tx_pin: 1
  baud_rate: 9600
  rx_buffer_size: 256
  stop_bits: 1
  data_bits: 8
  parity: NONE
text_sensor:
- platform: mqtt_subscribe
  id: humO
  topic: tmp/outside/sensor/humidity/state
  disabled_by_default: false
  qos: 0
  name: humO
  internal: true
display:
- platform: nextion
  id: nextion1
  brightness: 0.5
  tft_url: http://192.168.0.90:7003/firstproject.tft
  update_interval: 60s
  lambda: !lambda |-
    it.set_component_text_printf("humO", "%s", id(humO).state.c_str());
  auto_wake_on_touch: true
mqtt:
  broker: !secret 'mqtt_broker'
  username: !secret 'mqtt_username'
  password: !secret 'mqtt_password'
  discovery: true
  on_message:
  - topic: tmp/nextion/update
    then:
    - lambda: !lambda |-
        id(nextion1)->upload_tft();
    qos: 0
  port: 1883
  discovery_retain: true
  discovery_prefix: homeassistant
  topic_prefix: bedroom-drawer
  keepalive: 15s
  reboot_timeout: 15min
  birth_message:
    topic: bedroom-drawer/status
    payload: online
    qos: 0
    retain: true
  will_message:
    topic: bedroom-drawer/status
    payload: offline
    qos: 0
    retain: true
  shutdown_message:
    topic: bedroom-drawer/status
    payload: offline
    qos: 0
    retain: true
  log_topic:
    topic: bedroom-drawer/debug
    qos: 0
    retain: true
wifi:
  networks:
  - ssid: !secret 'wifi_ssid_0'
    password: !secret 'wifi_password'
    priority: 0.0
  - ssid: !secret 'wifi_ssid_1'
    password: !secret 'wifi_password'
    priority: 0.0
  manual_ip:
    static_ip: 192.168.0.62
    gateway: !secret 'wifi_gateway'
    subnet: !secret 'wifi_subnet'
    dns1: 0.0.0.0
    dns2: 0.0.0.0
  enable_mdns: true
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  use_address: 192.168.0.62
ota:
  safe_mode: true
  port: 8266
  password: ''
  reboot_timeout: 5min
  num_attempts: 10
binary_sensor: []
```

### Anything in the logs that might be useful for us?

```txt
logs during update

[01:58:03][W][nextion:072]: Nextion is not connected! 
[01:58:04][E][uart_esp8266:167]: Reading from UART timed out at byte 0!
[01:58:04][W][nextion:072]: Nextion is not connected! 
[01:58:04][E][uart_esp8266:167]: Reading from UART timed out at byte 0!
```
