### ISSUE TITLE
Add new device classes

### ISSUE THREAD

**Issue by brantje** [esphome/issues#2425]
### The problem

Hello,
With release 2021.9.5 we have lot more [device classes](https://www.home-assistant.io/integrations/sensor/).
I tried using them as following:

```
sensor:
    pm_1_0:
      name: "$devicename Particulate Matter <1.0µm Concentration"
      icon: "mdi:weather-fog"
      state_class: "measurement"
      device_class: "pm1"
      filters:
        - throttle: 60s
    pm_2_5:
      name: "$devicename Particulate Matter <2.5µm Concentration"
      icon: "mdi:weather-fog"
      state_class: "measurement"
      device_class: "pm25"
      filters:
        - throttle: 60s      
    pm_10_0:
      name: "$devicename Particulate Matter <10.0µm Concentration"  
      icon: "mdi:weather-fog"
      state_class: "measurement"
      device_class: "pm10"
      filters:
        - throttle: 60s  
```

However, upon validation ESPHome gives me the following error:
```
  Unknown value 'pm1', valid options are '', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'energy', 'humidity', 'illuminance', 'signal_strength', 'temperature', 'timestamp', 'power', 'power_factor', 'pressure', 'voltage'.
```

### Which version of ESPHome has the issue?

v1.20.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.6

### What platform are you using?

ESP32

### Board

nodemcu

### Example YAML snippet

```yaml
sensor:  
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_2
    
    pm_1_0:
      name: "$devicename Particulate Matter <1.0µm Concentration"
      icon: "mdi:weather-fog"
      state_class: "measurement"
      device_class: "pm1"
      filters:
        - throttle: 60s
    pm_2_5:
      name: "$devicename Particulate Matter <2.5µm Concentration"
      icon: "mdi:weather-fog"
      state_class: "measurement"
      device_class: "pm25"
      filters:
        - throttle: 60s      
    pm_10_0:
      name: "$devicename Particulate Matter <10.0µm Concentration"  
      icon: "mdi:weather-fog"
      state_class: "measurement"
      device_class: "pm10"
      filters:
        - throttle: 60s
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esp-sensor.yaml...
Failed config

sensor.pmsx003: [source /config/esphome/subs/aq-sub.yaml:64]
  platform: pmsx003
  type: PMSX003
  uart_id: uart_2
  pm_1_0:  [source /config/esphome/subs/aq-sub.yaml:69]
    name: esp-aqsensor Particulate Matter <1.0µm Concentration
    icon: mdi:weather-fog
    state_class: measurement
    
    Unknown value 'pm1', valid options are '', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'energy', 'humidity', 'illuminance', 'signal_strength', 'temperature', 'timestamp', 'power', 'power_factor', 'pressure', 'voltage'.
    device_class: pm1 [source /config/esphome/subs/aq-sub.yaml:72]
    filters: 
      - throttle: 60s
  pm_2_5:  [source /config/esphome/subs/aq-sub.yaml:76]
    name: esp-aqsensor Particulate Matter <2.5µm Concentration
    icon: mdi:weather-fog
    state_class: measurement
    
    Unknown value 'pm25', valid options are '', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'energy', 'humidity', 'illuminance', 'signal_strength', 'temperature', 'timestamp', 'power', 'power_factor', 'pressure', 'voltage'.
    device_class: pm25 [source /config/esphome/subs/aq-sub.yaml:79]
    filters: 
      - throttle: 60s
  pm_10_0:  [source /config/esphome/subs/aq-sub.yaml:83]
    name: esp-aqsensor Particulate Matter <10.0µm Concentration
    icon: mdi:weather-fog
    state_class: measurement
    
    Unknown value 'pm10', valid options are '', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'energy', 'humidity', 'illuminance', 'signal_strength', 'temperature', 'timestamp', 'power', 'power_factor', 'pressure', 'voltage'.
    device_class: pm10 [source /config/esphome/subs/aq-sub.yaml:86]
    filters: 
      - throttle: 60s
sensor.bme680_bsec: [source /config/esphome/subs/aq-sub.yaml:112]
  platform: bme680_bsec
  temperature: 
    name: esp-aqsensor Temperature
    accuracy_decimals: 2
    filters: 
      - offset: -1.0
      - throttle: 60s
  pressure: 
    name: esp-aqsensor Pressure
    accuracy_decimals: 2
    filters: 
      - throttle: 60s
  humidity: 
    name: esp-aqsensor Humidity
    accuracy_decimals: 2
    filters: 
      - throttle: 60s
  iaq:  [source /config/esphome/subs/aq-sub.yaml:130]
    id: bmeiaq
    name: esp-aqsensor IAQ
    
    Unknown value 'aqi', valid options are '', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'energy', 'humidity', 'illuminance', 'signal_strength', 'temperature', 'timestamp', 'power', 'power_factor', 'pressure', 'voltage'.
    device_class: aqi [source /config/esphome/subs/aq-sub.yaml:132]
    filters: 
      - throttle: 60s
  breath_voc_equivalent: 
    name: esp-aqsensor Breath VOC Equivalent
    filters: 
      - throttle: 60s
```
