### ISSUE TITLE
Cannot turn OFF the LED light as long as partitions are still ON

### ISSUE THREAD

**Issue by sgurgul** [esphome/issues#2429]
### The problem

My configuration is:

- fastled_clockless
- WS2812B LED
- Main light ID: light.esp_led_lamp
- Two partitions defined in the script: light.led_lamp_window, light.led_lamp_main

Before (versions older than 2021.8.0) when I wanted to disable all lights I was just calling (through HA service) turn_off service on main light: light.esp_led_lamp

After upgrading to 2021.8.0 I noticed the undesired effect - turn_off tries to disable LEDs, they are blinking and just after that turning on again. At the same time status of the light.esp_led_lamp entity is HA remains OFF which makes it inconsistent with reality. 
HA status of both partitions' light remains ON.

The issue seems to be related with the fact I am using partitions. What makes ma believe so is:

1. I have exactly the same hardware setup in other room but script does not use partitions at all. In configuration without partitions light is turned off properly and nothing changes after upgrading to 2021.8.
2. I found a workaround for the problem: if I turn off both partitions **first** (usign HA turn_off service) and only **after** that I call turn off on main light than the operation is successful - light goes down and it's HA status is consistent with the LED itself.

The phenomenon still exist in 2021.9.0 - I've just upgraded today and re-tested.

### Which version of ESPHome has the issue?

2021.8, 2021.9.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.6

### What platform are you using?

ESP8266

### Board

NodeMCU v3

### Component causing the issue

fastled_clockless

### Example YAML snippet

```yaml
esphome:
  name: esp_led_lamp
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    then:
      - script.execute: turn_lights_on

## ...

##### LIGHTS #####

light:

##### WINDOW #####
  - platform: partition
    id: led_lamp_window
    name: "LED_Lamp_Window"
    segments:
      - id: led_lamp
        from: 0
        to: 13
# Effects
    effects:
      - addressable_scan:

            
##### SMOG #####

  - platform: partition
    id: led_lamp_main
    name: "LED_Lamp_Main"
    segments:
      - id: led_lamp
        from: 14
        to: 293
# Effects
    effects:
      - addressable_scan:

##### BASE #####

  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 294
    rgb_order: GRB
    id: "led_lamp"
    name: "ESP_LED_LAMP"
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - script.execute: turn_lights_on
    on_turn_off:
    - script.execute: turn_lights_off
# Effects
    effects:
      - addressable_scan:

##### SCRIPTS #####

script:
  - id: turn_lights_on
    then:
      - delay: 1s
      - logger.log: "LED LAMP ON"
      - light.turn_on:
          id: led_lamp
          brightness: 1%
          red: 0%
          green: 0%
          blue: 1%
      - light.turn_on:
          id: led_lamp_window
          brightness: 50%
          red: 0%
          green: 0%
          blue: 100%
          effect: "Tierra_Sensor_Window"            
      - light.turn_on:
          id: led_lamp_main
          brightness: 80%
          red: 0%
          green: 0%
          blue: 100%
          effect: "Scan"            
  - id: turn_lights_off
    then:
      - light.turn_off:
          id: led_lamp_window
      - light.turn_off:
          id: led_lamp_main
```
