### ISSUE TITLE
ESP32 WROOM32 with last dev 2021-10-0 is no more connecting, I2C GPIO21/22 problem ?

### ISSUE THREAD

**Issue by SeByDocKy** [esphome/issues#2433]
### The problem

Compule fine but no more connection .... Works fine with the stable release

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.4

### What platform are you using?

ESP32

### Board

WROOM32

### Component causing the issue

?

### Example YAML snippet

```yaml
esphome:
  name: puits
  platform: ESP32
  board: esp32dev
 
wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_password

# Enable logging

logger:
  #level: debug


# Enable Home Assistant API
api:

ota:



time:
  #- platform: sntp
  #  id: my_time
    
  - platform: homeassistant
    id: homeassistant_time  
    
    on_time:
      - seconds: 59
        minutes: 59
        hours: 23
        then:  
          - sensor.template.publish:
              id: template_puits_veille
              state: !lambda return id(daily_well).state;
              
              
i2c:
- sda: GPIO21
  scl: GPIO22
  id: i2c_bus1              
    
switch:
  - platform: restart
    name: "restart_puits"

dallas:
  - pin: GPIO15
    update_interval: 10s

sensor:
  - platform: bme280
    i2c_id: i2c_bus1
    temperature:
      name: "temperature_vs"
      oversampling: 16x
      id: temperature_vs
    pressure:
      name: "pression_vs"
      id: pression_vs
      unit_of_measurement: "bar"
      accuracy_decimals: 3
      filters:
      - lambda: return x / 1000.0;
    humidity:
      name: "humidite_vs"
      id: humidite_vs
    address: 0x76
    update_interval: 10s  

  - platform: homeassistant
    name: "reference_pression"
    entity_id: sensor.darksy_pressure
    id: reference_pression

  - platform: adc
    pin: GPIO36
    name: "pression_puits"
    update_interval: 10s
    attenuation: 11db
    unit_of_measurement: "bar"
    accuracy_decimals: 3
    icon: mdi:gauge
    id: pression_puits
    filters:
    - sliding_window_moving_average:
        window_size: 9
        send_every: 1
    - lambda: return (((x/5.0) + 0.04 )/0.4);
    
    
  - platform: adc
    pin: GPIO39
    name: "pression_surpresseur"
    update_interval: 10s
    attenuation: 11db
    unit_of_measurement: "bar"
    icon: mdi:gauge
    accuracy_decimals: 3
    filters:
    - sliding_window_moving_average:
        window_size: 7
        send_every: 1
    - lambda: return ((x/5.0 - 0.1)*1.333333*10);
    #- lambda: return ((x/5.0 - 0.1)*1.49993*10);

  - platform: dallas
    address: 0x3B8318507361FF28
    name: "temperature_puits"
    unit_of_measurement: "°C"
    resolution: 12
    accuracy_decimals: 2
    
    
  - platform: total_daily_energy
    name: "puits_du_jour"
    power_id: water_flow_meter_puits
    unit_of_measurement: "l"
    accuracy_decimals: 2
    id: daily_well
    
  - platform: template
    name: "puits_veille"
    id: template_puits_veille
    unit_of_measurement: "l"
    accuracy_decimals: 2
    icon: mdi:water
    update_interval: 10s
    
  - platform: template
    name: "volume_puits"
    id: template_volume_puits
    unit_of_measurement: "l"
    accuracy_decimals: 2
    update_interval: 10s
    icon: mdi:water
    filters:
    - sliding_window_moving_average:
        window_size: 9
        send_every: 1
    #lambda: return ( (id(pression_puits).state - 1.10)*7230.7233); 
    #lambda: return ( ( id(pression_puits).state - ( (id(reference_pression).state)*pow( (1.0 - (0.0065*104.0/288.15)) , 5.255)/1000.0 + 0.10))*77238.2294 );
    #lambda: return ( (id(pression_puits).state - ( (id(reference_pression).state)/1000.0 + 0.10 ) )*7230.7233 );
    #lambda: return ( (id(pression_puits).state - ( (id(reference_pression).state)*pow( (1.0 - (0.0065*94.5/288.15)) , 5.255) + 0.10 ) )*7238.2294 );     #108m - 14m = 94 
    
    lambda: return ( (id(pression_puits).state - ( (id(pression_vs).state)/(pow( (1.0 - (0.0065*14/288.15)) , 5.255)) + 0.10 ) )*7238.2294 );     #108m - 14m = 94 
    
    
    # 94.5 comes from my current altitude in order to correct pressure given for sea level
    # 0.1 <=> 1m between the sensor and the water pump
    #https://fr.wikipedia.org/wiki/Variation_de_la_pression_atmosph%C3%A9rique_avec_l%27altitude
    
    # My well is cylindric with a diameter of D=0.96m. My sensor is located 1m below the pump. So if I want to compute the remaining water for the pump I need substracte 0.1 on measured pressure
    # then h= (measured pressured - (1 + 0.1))*10 where we remove the 0 meter air pressure + 1m of difference between the sensor and the pump. Then we multiply *10 to have a meter value
    # Volume of water (L) = h*pi*R²*1000 = delta_p*10*pi*R²*1000= delta_p*pi*(D/2)²1000*10=h*3.14116*(0.96/2)² *1000*10=delta_p*7230.7233 for my particular case
    
    
                                                                  
  - platform: pulse_counter
    id: water_flow_meter_puits
    pin: GPIO2
    name: "water_flow_meter_puits"    
    update_interval: 1s
    icon: mdi:water
    filters:
    - lambda: return (x / 5.48);
    unit_of_measurement: "l"     
    
    
  - platform: wifi_signal
    name: "WiFi puissance_puits"
    update_interval: 10s
    
  - platform: uptime
    #name: "up_puits"
    id: uptime_sec
    #update_interval: 15s 
    #filters:
    #  - lambda: return x / 3600.0;
    #unit_of_measurement: "hours"
    #accuracy_decimals: 2
    #update_interval: 10s
    
binary_sensor:
  - platform: status
    name: "puits_status"
    
    
text_sensor:
  - platform: template
    name: puits_uptime
    lambda: |-
      int seconds = (id(uptime_sec).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600); 
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
    icon: mdi:clock-start
    update_interval: 113s
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/puits.yaml...
INFO Detected timezone 'CET' with UTC offset 1 and daylight saving time from 27 March 02:00:00 to 30 October 03:00:00
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/puits
Processing puits (board: esp32dev; framework: arduino; platform: platformio/espressif32@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
Library Manager: Installing Hash
Library Manager: Already installed, built-in library
Dependency Graph
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <Wire> 1.0.1
|-- <Update> 1.0
|-- <WiFi> 1.0
Retrieving maximum program size /data/puits/.pioenvs/puits/firmware.elf
Checking size /data/puits/.pioenvs/puits/firmware.elf
RAM:   [=         ]  12.8% (used 41880 bytes from 327680 bytes)
Flash: [=====     ]  50.3% (used 923822 bytes from 1835008 bytes)
========================= [SUCCESS] Took 17.33 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of puits.local
INFO  -> 192.168.1.72
INFO Uploading /data/puits/.pioenvs/puits/firmware.bin (923936 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from puits.local using esphome API
WARNING Can't connect to ESPHome API for puits.local: Error connecting to ('192.168.1.72', 6053): [Errno 111] Connect call failed ('192.168.1.72', 6053)
INFO Trying to reconnect to puits.local in the background
```
