### ISSUE TITLE
GPIO0 and GPIO1 not working as GPIO outputs with Ethernet enabled on Olimex ESP32 POE

### ISSUE THREAD

**Issue by RonnyLV** [esphome/issues#2436]
### The problem

GPIO0 and GPIO1 not working as GPIO outputs with Ethernet enabled on Olimex ESP32 POE when i try to switch them on/off.

Works fine if configured on other pin, for example GPIO14.

### Which version of ESPHome has the issue?

2021.9.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp32-poe

### Component causing the issue

ethernet

### Example YAML snippet

```yaml
esphome:
  name: nknet-shed-alarm
  platform: ESP32
  board: esp32-poe

...

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

# Individual outputs
switch:
  - platform: gpio
    pin: GPIO0
    inverted: True
    id: relay
    name: "Relay"
```
