### ISSUE TITLE
can't compile display time

### ISSUE THREAD

**Issue by shom** [esphome/issues#244]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 nodemcu-32s
esphome_core_version: v1.12.2

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
time:
  - platform: homeassistant
    id: time

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.strftime(0, 4, id(font1), "%H:%M", id(time).now);
```

**Traceback (if applicable):**

```
src/main.cpp: In lambda function:
src/main.cpp:45:50: error: invalid use of non-static member function
it.strftime(0, 4, font1, "%H:%M", time->now);
```

**Additional information and things you've tried:**
