### ISSUE TITLE
ESPhome does not work on sonoff basic R3

### ISSUE THREAD

**Issue by rbr101** [esphome/issues#2443]
### The problem

The ESPhome software does not work on sonoff basic R3 version. The image uploads fine but then WIFI won't connect and connection serial port ([19:58:45]/ISK0!EC6C ERROR Serial port closed!) is not possible. When flashing with tasmo firmware everything works fine.

### Which version of ESPHome has the issue?

2021.9.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

latest

### What platform are you using?

ESP8266

### Board

sonoff

### Component causing the issue

bacicR3

### Example YAML snippet

```yaml
esphome:
  name: sonoff-bbq
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff BBQ"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ""

wifi:
  ssid: "xxxxx"
  password: "xxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: " "
    password: " "

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/sonoff-bbqtafel.yaml...
INFO Starting log output from /dev/ttyUSB0 with baud rate 115200
ERROR Serial port closed!
```
