### ISSUE TITLE
No way to set pulldown mode for GPIO

### ISSUE THREAD

**Issue by cab404** [esphome/issues#2448]
### The problem

I am using some fussy relays, which are not satisfied with being digitallyWritten to. They actually need me to switch into input with pulldown mode, thus prompting me to write some unsightly code like this:
```yaml
switch:
  - platform: template
    name: "Pick up phone"
    id: t_pickup
    lambda: |-
      return !digitalRead(12);
    turn_on_action:
      - lambda: |-
          pinMode(12, OUTPUT);
          digitalWrite(12, LOW);
    turn_off_action:
      - lambda: |
          pinMode(12, INPUT);
```

Would be nice to have a flag to make "off" state actually use "input_pulldown" mode on gpio.

### Which version of ESPHome has the issue?

1.16

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266
