### ISSUE TITLE
i2c scanning not working after  after #2303

### ISSUE THREAD

**Issue by martgras** [esphome/issues#2453]
### The problem

I2c scan reports all addresses as connected if Arduino framework is used (esp-idf is ok)

expected 
[16:35:29][I][i2c.arduino:034]: Scanning i2c bus for active devices...
[16:35:29][I][i2c.arduino:042]: Found i2c device at address 0x76
[16:35:29][C][logger:235]: Logger:

actually getting:

I][i2c.arduino:034]: Scanning i2c bus for active devices...
[16:41:58][I][i2c.arduino:040]: Found i2c device at address 0x01
[16:41:58][I][i2c.arduino:040]: Found i2c device at address 0x02
...
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x74
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x75
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x76
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x77

### Which version of ESPHome has the issue?

current dev branch

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
substitutions:
  updates: 60s
  unique_id: bme280

esphome:
  name: ${unique_id}

esp32:
  board: TinyPICO
  framework:
    type: arduino

logger:
  level: VERBOSE
i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

sensor:
  - platform: bme280
    temperature:
      name: "Temperatur (Huette)"
      id: hut_temperature
    humidity:
      name: "Luftfeuchtigkeit (Huette)"
      id: hut_humidity
    update_interval: ${updates}
    address: 0x76
```

### Anything in the logs that might be useful for us?

```txt
I][i2c.arduino:034]: Scanning i2c bus for active devices...
[16:41:58][I][i2c.arduino:040]: Found i2c device at address 0x01
[16:41:58][I][i2c.arduino:040]: Found i2c device at address 0x02
...
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x74
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x75
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x76
[16:41:59][I][i2c.arduino:040]: Found i2c device at address 0x77
```

### Additional information

reverting the code to the previous pattern fixes the issue
 `
wire_->beginTransmission(address);
auto err = wire_->endTransmission(true);
`
