### ISSUE TITLE
Periodical esp reboot when using 'platform: integration/total_daily_energy'

### ISSUE THREAD

**Issue by Spirituss** [esphome/issues#2464]
### The problem

In case I add the ```platform: integration``` and ```platform: total_daily_energy ``` to esp8266, it starts to reboot every 5-15 hours (statistically). 
If I remove these platforms but keep other parts of the configuration, esp works stable for some months. It seems that integration leads to an unhandled exception which cause esp reboot.

 

### Which version of ESPHome has the issue?

All

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

All

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
Here is my esphome config:

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285
  esp8266_restore_from_flash: true  

....

sensor:
  - platform: integration 
    name: energy_monthly_${device_name}
    id: id_energy_monthly
    sensor: id_power
    time_unit: h
    filters:
      - multiply: 0.001
    accuracy_decimals: 3
    restore: true
    state_class: measurement
    device_class: energy
    last_reset_type: auto
#-------------------------------------------------------------------------------    
  - platform: total_daily_energy 
    name: energy_daily_${device_name}
    id: id_energy_daily
    power_id: id_power
    filters:
      - multiply: 0.001
    accuracy_decimals: 3   
    device_class: energy
#-------------------------------------------------------------------------------
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO4
    power:
      name: power_${device_name}
      id: id_power            
    change_mode_every: 4
    update_interval: 10s
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
