### ISSUE TITLE
Sonoff basic R1 - after upgrade to v.2021.9.1 wifi cannot connect

### ISSUE THREAD

**Issue by vobo70** [esphome/issues#2466]
### The problem

I upgraded all my esphome devices from previous version and all Sonoff basic R1 cannot connect to wifi.
Log says: Probe Request Unsuccessful
After remove:
captive portal:
and reflash
everything works.

### Which version of ESPHome has the issue?

v2021.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.9.7

### What platform are you using?

ESP8266

### Board

sonoff basic r1

### Component causing the issue

captive portal

### Example YAML snippet

```yaml
esphome:
  name: grzalka_zasobnik
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "private"
  password: "private"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Grzalka Zasobnik"
    password: "private"
    ap_timeout: 10min

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "private"

ota:
  password: "private"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "przycisk grzalka zasobnik"
    on_press:
      - switch.toggle: przekaznik_grzalka_zasobnik

switch:
  - platform: gpio
    name: "przekaznik grzalka zasobnik"
    pin: GPIO12
    id: przekaznik_grzalka_zasobnik

status_led:
  pin:
    number: GPIO13
    inverted: yes
```

### Anything in the logs that might be useful for us?

```txt
Probe Request Unsuccessful
```
