### ISSUE TITLE
Compilation error for custom sensor with delay(int) line

### ISSUE THREAD

**Issue by SeByDocKy** [esphome/issues#2475]
### The problem

I had compilation error with the last dev nightly build (09/25/21)  while with the the stable  version it compiles fine. The problem comes from the delay instruction inside the associated .h file

### Which version of ESPHome has the issue?

2021.10.1 (09/25/21) dev build

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.4

### What platform are you using?

ESP32

### Board

ESP32cam

### Component causing the issue

custom sensor

### Example YAML snippet

```yaml
esphome:
  name: potager
  platform: ESP32
  board: esp32dev
  includes:
    - tinovi_esp32_custom_sensor.h
  #libraries:
    #- "https://github.com/tinovi/i2cArduino"
    #- "https://github.com/tinovi/i2cArduino/tree/esp32"

wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_password

# Enable logging

logger:
  #baud_rate: 0 #need this to free up UART pins
  #level: debug


# Enable Home Assistant API
api:

ota:



time:
  - platform: homeassistant
    id: homeassistant_time  
    
    on_time:
      - seconds: 55
        minutes: 59
        hours: 23
        then:  
          - sensor.template.publish:
              id: template_potager_veille
              state: !lambda return id(daily_potager).state;
              
      - seconds: /10
        then:
          - sensor.template.publish:
              id: template_potager_veille
              state: !lambda return id(template_potager_veille).state;        

i2c:
  sda: GPIO1 #GPIO03  
  scl: GPIO3 #GPIO01
  scan: True
  id: bus_i2c2

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600 #1280x1024 #800x600 #1280x1024  #800x600 #1280x1024 #1024x768 #800x600 #1024x768 #640x480
  jpeg_quality: 10
  horizontal_mirror: false
  vertical_flip: false
  max_framerate: 0.1fps
  idle_framerate: 0.01fps
  name: potager_camera
  

cover:
- platform: time_based
  name: potager_electrovanne
  id: potager_electrovanne
  assumed_state: false
  open_action:
    - switch.turn_on: open_valve
  open_duration: 15s
  close_action:
    - switch.turn_on: close_valve
  close_duration: 15s
  stop_action:
    - switch.turn_off: open_valve
    - switch.turn_off: close_valve

output:
#flashlight
  - platform: gpio
    pin: GPIO4
    id: gpio_4
#statuslight
  - platform: gpio
    pin:
      number: GPIO33
      inverted: True
    id: gpio_33
light:
#flashlight
  - platform: binary
    output: gpio_4
    name: potager_flash
#statuslight
  - platform: binary   
    output: gpio_33
    name: potager_led_status  
  
switch:
  - platform: restart
    name: "restart_potager"
    
  - platform: gpio
    pin: GPIO14
    interlock: &interlock [open_valve, close_valve]
    inverted: True
    id: open_valve
    
  - platform: gpio
    pin: GPIO15
    interlock: *interlock
    inverted: True
    id: close_valve  
    
binary_sensor:
  - platform: status
    name: "potager_status"
    
    
  # détection de la pluie  
  - platform: gpio
    pin: GPIO02
    filters:
      invert: 
    name: "potager_pluie"
    
sensor:

#  - platform: adc
#    id: potager_conductivite_pluie
#    name: potager_conductivite_pluie
#    pin: GPIO04
#    update_interval: 10s
#    attenuation: 0db  
  
  - platform: uptime
    name: "up_potager"
    id: uptime_sec  
    
  - platform: wifi_signal
    name: "WiFi puissance_potager"
    update_interval: 10s  
    
  - platform: pulse_counter
    id: water_flow_meter_potager
    pin: GPIO16
    #name: "water_flow_meter_potager"    
    update_interval: 1s
    icon: mdi:water
    filters:
     - lambda: return (x / 5.48);
    unit_of_measurement: "l"
    
  - platform: total_daily_energy
    name: "potager_du_jour"
    power_id: water_flow_meter_potager  
    unit_of_measurement: "l"
    accuracy_decimals: 2
    id: daily_potager
    
  - platform: template
    name: "potager_veille"
    id: template_potager_veille
    unit_of_measurement: "l"
    accuracy_decimals: 2
    icon: mdi:water
    update_interval: 10s    
    
  - platform: bh1750
    name: "potager_luminosite"
    address: 0x23
    update_interval: 10s
    measurement_duration: 60
    i2c_id: bus_i2c2
    filters:
    - lambda: if (x < 54612.5) return x;
    - sliding_window_moving_average:
        window_size: 9
        send_every: 1
    
  - platform: custom
    id: tinovi_id
    lambda: |-
      auto TINOVI = new TINOVICustomSensor();
      App.register_component(TINOVI);
      return {TINOVI->e25_sensor, TINOVI->ec_sensor , TINOVI->temp_sensor , TINOVI->vwc_sensor};

    sensors:
    - name: "potager_e25"
      unit_of_measurement: "dS/m"
      accuracy_decimals: 2
      icon: "mdi:epsilon"
      filters:
      - lambda: if (x <= 80.0) return x;
      #- median:
      #    window_size: 7
      #    send_every: 1
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1  
    
    - name: "potager_ec"
      unit_of_measurement: "mS/m"
      accuracy_decimals: 2
      icon: "mdi:sigma-lower"
      filters:
      - lambda: if (x <= 300.0) return x;
      #- median:
      #    window_size: 7
      #    send_every: 1
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
      
    - name: "potager_temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 2
      icon: "mdi:thermometer"
      filters:
      - lambda: if (x <= 70.0) return x;
      #- median:
      #    window_size: 7
      #    send_every: 1
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
          
    - name: "potager_vwc"
      accuracy_decimals: 2
      unit_of_measurement: "cm3cm−3"
      icon: "mdi:alpha-h-circle-outline"  
      filters:
      - lambda: if (x <= 100.0) return x;
      #- median:
      #    window_size: 7
      #    send_every: 1
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
    
text_sensor:
  - platform: template
    name: potager_uptime
    lambda: |-
      int seconds = (id(uptime_sec).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600); 
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
    icon: mdi:clock-start
    update_interval: 113s    
    
  - platform: version
    name: "potager_ESPHome_version"
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/potager.yaml...
INFO Detected timezone 'CET' with UTC offset 1
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/potager
Processing potager (board: esp32dev; framework: arduino; platform: espressif32 @ 3.3.2)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
Library Manager: Installing Hash
Warning! Could not find the package with 'Hash' requirements for your system 'linux_aarch64'
Dependency Graph
|-- <Wire> 1.0.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <noise-c> 0.1.1
|-- <Update> 1.0
|-- <WiFi> 1.0
Compiling /data/potager/.pioenvs/potager/src/esphome/components/api/api_connection.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/api/api_pb2_service.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/api/api_server.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/api/list_entities.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/api/proto.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/api/user_services.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/api/util.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/bh1750/bh1750.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/binary_sensor/automation.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/binary_sensor/filter.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/cover/cover.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/custom/sensor/custom_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/esp32/core.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/esp32/gpio_arduino.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/esp32/gpio_idf.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/esp32/preferences.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/esp32_camera/esp32_camera.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/gpio/output/gpio_binary_output.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/gpio/switch/gpio_switch.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/homeassistant/time/homeassistant_time.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/i2c/i2c.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/i2c/i2c_bus_arduino.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/i2c/i2c_bus_esp_idf.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/light/addressable_light.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/light/automation.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/light/esp_color_correction.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/light/esp_hsv_color.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/light/esp_range_view.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/light/light_call.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/light/light_json_schema.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/light/light_output.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/light/light_state.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/logger/logger.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/mdns/mdns_component.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/mdns/mdns_esp32_arduino.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/mdns/mdns_esp_idf.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/network/util.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/ota/ota_component.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/output/automation.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/output/float_output.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/pulse_counter/pulse_counter_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/restart/restart_switch.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/sensor/automation.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/sensor/filter.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/sensor/sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/status/status_binary_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/switch/automation.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/switch/switch.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/template/sensor/template_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/template/text_sensor/template_text_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/text_sensor/text_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/time/automation.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/time/real_time_clock.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/time_based/time_based_cover.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/total_daily_energy/total_daily_energy.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/uptime/uptime_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/version/version_text_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/wifi/wifi_component.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/components/wifi_signal/wifi_signal_sensor.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/core/application.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/core/color.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/core/component.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/core/controller.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/core/helpers.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/core/log.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/core/scheduler.cpp.o
Compiling /data/potager/.pioenvs/potager/src/esphome/core/util.cpp.o
Compiling /data/potager/.pioenvs/potager/src/main.cpp.o
Generating partitions /data/potager/.pioenvs/potager/partitions.bin
Compiling /data/potager/.pioenvs/potager/lib4fc/Wire/Wire.cpp.o
Compiling /data/potager/.pioenvs/potager/lib64d/WiFi/ETH.cpp.o
Archiving /data/potager/.pioenvs/potager/lib4fc/libWire.a
Compiling /data/potager/.pioenvs/potager/lib64d/WiFi/WiFi.cpp.o
Compiling /data/potager/.pioenvs/potager/lib64d/WiFi/WiFiAP.cpp.o
Compiling /data/potager/.pioenvs/potager/lib64d/WiFi/WiFiClient.cpp.o
In file included from src/main.cpp:79:0:
src/tinovi_esp32_custom_sensor.h: In member function 'bool SVCS3::i2cdelay(int)':
src/tinovi_esp32_custom_sensor.h:97:11: error: call of overloaded 'delay(int)' is ambiguous
    delay(2);
           ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/libraries/Wire/src/Wire.h:28:0,
                 from src/esphome/components/i2c/i2c_bus_arduino.h:7,
                 from src/esphome.h:34,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:105:6: note: candidate: void delay(uint32_t)
 void delay(uint32_t);
      ^
In file included from src/esphome/components/light/light_transformer.h:4:0,
                 from src/esphome/components/light/light_state.h:10,
                 from src/esphome/core/application.h:30,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:2,
                 from src/main.cpp:3:
src/esphome/core/hal.h:39:6: note: candidate: void esphome::delay(uint32_t)
 void delay(uint32_t ms);
      ^
In file included from src/main.cpp:79:0:
src/tinovi_esp32_custom_sensor.h: In member function 'int SVCS3::setReg(byte)':
src/tinovi_esp32_custom_sensor.h:162:10: error: call of overloaded 'delay(int)' is ambiguous
   delay(2);
          ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/libraries/Wire/src/Wire.h:28:0,
                 from src/esphome/components/i2c/i2c_bus_arduino.h:7,
                 from src/esphome.h:34,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:105:6: note: candidate: void delay(uint32_t)
 void delay(uint32_t);
      ^
In file included from src/esphome/components/light/light_transformer.h:4:0,
                 from src/esphome/components/light/light_state.h:10,
                 from src/esphome/core/application.h:30,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:2,
                 from src/main.cpp:3:
src/esphome/core/hal.h:39:6: note: candidate: void esphome::delay(uint32_t)
 void delay(uint32_t ms);
      ^
In file included from src/main.cpp:79:0:
src/tinovi_esp32_custom_sensor.h: In member function 'int SVCS3::newReading()':
src/tinovi_esp32_custom_sensor.h:203:12: error: call of overloaded 'delay(int)' is ambiguous
   delay(300);
            ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/libraries/Wire/src/Wire.h:28:0,
                 from src/esphome/components/i2c/i2c_bus_arduino.h:7,
                 from src/esphome.h:34,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:105:6: note: candidate: void delay(uint32_t)
 void delay(uint32_t);
      ^
In file included from src/esphome/components/light/light_transformer.h:4:0,
                 from src/esphome/components/light/light_state.h:10,
                 from src/esphome/core/application.h:30,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:2,
                 from src/main.cpp:3:
src/esphome/core/hal.h:39:6: note: candidate: void esphome::delay(uint32_t)
 void delay(uint32_t ms);
      ^
In file included from src/main.cpp:79:0:
src/tinovi_esp32_custom_sensor.h: In member function 'virtual void TINOVICustomSensor::update()':
src/tinovi_esp32_custom_sensor.h:308:14: error: call of overloaded 'delay(int)' is ambiguous
     delay(100);
              ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/libraries/Wire/src/Wire.h:28:0,
                 from src/esphome/components/i2c/i2c_bus_arduino.h:7,
                 from src/esphome.h:34,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:105:6: note: candidate: void delay(uint32_t)
 void delay(uint32_t);
      ^
In file included from src/esphome/components/light/light_transformer.h:4:0,
                 from src/esphome/components/light/light_state.h:10,
                 from src/esphome/core/application.h:30,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:2,
                 from src/main.cpp:3:
src/esphome/core/hal.h:39:6: note: candidate: void esphome::delay(uint32_t)
 void delay(uint32_t ms);
      ^
Compiling /data/potager/.pioenvs/potager/lib64d/WiFi/WiFiGeneric.cpp.o
Compiling /data/potager/.pioenvs/potager/lib64d/WiFi/WiFiMulti.cpp.o
/config/esphome/potager.yaml: In lambda function:
/config/esphome/potager.yaml:189:3: warning: control reaches end of non-void function [-Wreturn-type]
     - sliding_window_moving_average:
   ^
/config/esphome/potager.yaml: In lambda function:
/config/esphome/potager.yaml:207:3: warning: control reaches end of non-void function [-Wreturn-type]
       #- median:
   ^
/config/esphome/potager.yaml: In lambda function:
/config/esphome/potager.yaml:220:3: warning: control reaches end of non-void function [-Wreturn-type]
       #- median:
   ^
/config/esphome/potager.yaml: In lambda function:
/config/esphome/potager.yaml:233:3: warning: control reaches end of non-void function [-Wreturn-type]
       #- median:
   ^
/config/esphome/potager.yaml: In lambda function:
/config/esphome/potager.yaml:246:3: warning: control reaches end of non-void function [-Wreturn-type]
       #- median:
   ^
*** [/data/potager/.pioenvs/potager/src/main.cpp.o] Error 1
========================= [FAILED] Took 111.40 seconds =========================
```

### Additional information

the tinovi_esp32_custom_sensor.h file

```
#include <Arduino.h>
#include <Wire.h>
#include "esphome.h"

#define I2C_SDA 1
#define I2C_SCL 3
#define ADDR 0x63

#ifndef VCS3I2C_H_
#define VCS3I2C_H_


#define  REG_READ_START       0x01
#define  REG_GET_DATA         0x09
#define  REG_READ_E25         0x02
#define  REG_READ_EC          0x03
#define  REG_READ_TEMP        0x04
#define  REG_READ_VWC         0x05
#define  REG_CAP              0x0A
#define  REG_RES              0x0B
#define  REG_RC               0x0C
#define  REG_RT               0x0D
#define  REG_CALIBRATE_AIR    0x06
#define  REG_CALIBRATE_WATER  0x07
#define  REG_CALIBRATE_EC     0x10
#define  REG_RES              0x0B
#define  REG_SET_I2C_ADDR     0x08


float e25_old   = 0.0;
float ec_old    = 0.0;
float temp_old  = 0.0;
float vwc_old   = 0.0;



class SVCS3
{
public:
  SVCS3();
  int init(int address, TwoWire *the_wire);
  int init(int address);
  int newAddress(byte newAddr);
  int resetDefault();
  int calibrationAir();
  int calibrationWater();
  int calibrationEC(int16_t valueUs);
  int newReading();
  float getE25();
  float getEC();
  float getTemp();
  float getVWC();
  void getData(float retVal[]);
  void getRaw(byte data[]);
  int16_t getCap();
  int16_t getRc();
  uint32_t getRt();

private:
  TwoWire *_wire;
  uint16_t addr;
  int getState();
  int16_t getVal(byte reg);
  uint32_t getVal32(byte reg);
  int setReg8(byte reg, byte val);
  int setReg(byte reg);
  bool i2cdelay(int size);

};

#endif /* VCS3I2C_H_ */

TwoWire I2C = TwoWire(0);

SVCS3::SVCS3(){
  addr=0x63;
}

int SVCS3::init(int address, TwoWire *the_wire){
  _wire = the_wire;
  addr = address;
  return 0;
}

int SVCS3::init(int address){
  _wire = &Wire;
  _wire->begin();
  addr = address;
  return 0;
}


bool SVCS3::i2cdelay(int size){
  int i=0;
  for (;_wire->available() < size && i<=size;i++) {
	  delay(2);
  }
  if(i>=size){
	  return false;
  }else{
	  return true;
  }
}

int SVCS3::getState(){ //-1:no data, 0:err, 1:ok
  _wire->requestFrom(addr, (uint8_t)1);
   if(i2cdelay(1)){
    return _wire->read();
  }else{
    return -1;
  }
}

int16_t SVCS3::getVal(byte reg){

  _wire->beginTransmission(addr); // transmit to device
  _wire->write(reg);              // sends one byte
  _wire->endTransmission();    // stop transmitting
 
  _wire->requestFrom(addr, (uint8_t)2);
  int16_t ret=0;
  if(i2cdelay(2)){
	byte *pointer = (byte *)&ret;
    pointer[0] = _wire->read();
    pointer[1] = _wire->read();
  }
  return ret;
}

uint32_t SVCS3::getVal32(byte reg){

  _wire->beginTransmission(addr); // transmit to device
  _wire->write(reg);              // sends one byte
  _wire->endTransmission();    // stop transmitting

  _wire->requestFrom(addr, (uint8_t)4);
  int16_t ret=0;
  if(i2cdelay(4)){
	byte *pointer = (byte *)&ret;
    pointer[0] = _wire->read();
    pointer[1] = _wire->read();
    pointer[2] = _wire->read();
    pointer[3] = _wire->read();
  }
  return ret;
}


int SVCS3::setReg8(byte reg, byte val){
  _wire->beginTransmission(addr); // transmit to device
  _wire->write(reg);              // sends one byte
  _wire->write(val);              // sends one byte
  _wire->endTransmission();    // stop transmitting
  return getState();
}

int SVCS3::setReg(byte reg){
  _wire->beginTransmission(addr); // transmit to device
  _wire->write(reg);              // sends one byte
  _wire->endTransmission();    // stop transmitting
  delay(2);
  return getState();
}

int SVCS3::resetDefault(){
  return setReg(REG_RES);
}

int SVCS3::calibrationAir(){
  return setReg(REG_CALIBRATE_AIR);
}

int SVCS3::calibrationWater(){
  return setReg(REG_CALIBRATE_WATER);
}

int SVCS3::calibrationEC(int16_t valueUs)
{
  _wire->beginTransmission(addr);
  _wire->write(REG_CALIBRATE_EC);
  uint8_t *pointer = (uint8_t *)&valueUs;
  _wire->write((uint8_t *)&pointer[0],1);
  _wire->write((uint8_t *)&pointer[1],1);
  _wire->endTransmission();
  return getState();
  
}
int SVCS3::newAddress(byte newAddr){
  if(setReg8(REG_SET_I2C_ADDR, newAddr)){
    addr = newAddr;
  }
  else{
    return 0;
  }
  return 1;
}

int SVCS3::newReading(){
  _wire->beginTransmission(addr); // transmit to device
  _wire->write(REG_READ_START);              // sends one byte
  _wire->endTransmission();    // stop transmitting
  delay(300);
  return getState();
}

float SVCS3::getE25()
{
  return getVal(REG_READ_E25)/100.0;
}

float SVCS3::getEC()
{
  return getVal(REG_READ_EC)/10.0;
}

float SVCS3::getTemp()
{
  return getVal(REG_READ_TEMP)/100.0;
}

float SVCS3::getVWC()
{
  return getVal(REG_READ_VWC);
}

int16_t SVCS3::getCap()
{
  return getVal(REG_CAP);
}

int16_t SVCS3::getRc()
{
  return getVal(REG_RC);
}

uint32_t  SVCS3::getRt(){
	return getVal32(REG_RT);
}

void SVCS3::getData(float readings[]){
  _wire->beginTransmission(addr); // transmit to device
  _wire->write(REG_GET_DATA);              // sends one byte
  _wire->endTransmission();    // stop transmitting
  _wire->requestFrom(addr, (uint8_t)8);
  if(i2cdelay(8)){
	  for (int k = 0; k < 4; k++){
		int16_t ret;
		byte *pointer = (byte *)&ret;
		pointer[0] = _wire->read();
		pointer[1] = _wire->read();
		switch (k) {
		case 0:
			readings[k] = ret / 100.0;
			break;
		case 1:
			readings[k] = ret / 10.0;
			break;
		case 2:
			readings[k] = ret / 100.0;
			break;
		case 3:
			readings[k] = ret / 10.0;
			break;
		}
	  }
  }else{
	  for (int k = 0; k < 4; k++){
		readings[k] = 0.0;
	  }
  }
}

void SVCS3::getRaw(byte data[]){
  _wire->beginTransmission(addr); // transmit to device
  _wire->write(REG_GET_DATA);              // sends one byte
  _wire->endTransmission();    // stop transmitting
  _wire->requestFrom(addr, (uint8_t)8);
  if(i2cdelay(8)){
	  for(int i = 0; i<8; i++){
		  data[i] = _wire->read();
	  }
  }else{
	  for(int i = 0; i<8; i++){
		  data[i] = 0;
	  }
  }
}

class TINOVICustomSensor : public PollingComponent, public Sensor {
 public:
  SVCS3 vcs;
  Sensor *e25_sensor = new Sensor();
  Sensor *ec_sensor = new Sensor();
  Sensor *temp_sensor = new Sensor();
  Sensor *vwc_sensor = new Sensor();
  
  TINOVICustomSensor() : PollingComponent(5000) {}
  void setup() override {
    Serial.begin(115200);
	I2C.begin(I2C_SDA , I2C_SCL);
	//I2C.begin(I2C_SDA , I2C_SCL , 50000);
    vcs.init(ADDR , &I2C);
  }
  void update() override {
	int status;  
    status = vcs.newReading(); // start sensor reading
    delay(100);
	if(status >= 1) {
	float dat[4]={0.0,0.0,0.0,0.0};
    vcs.getData(dat);
	/*
	float e25 = vcs.getE25();
    float ec = vcs.getEC();
    float temp = vcs.getTemp();
    float vwc = vcs.getVWC();
	*/
    float e25   = dat[0];
    float ec    = dat[1];
    float temp  = dat[2];
    float vwc   = dat[3];
	
	if((e25 > 0.0) ) //& (e25 >= e25_old*0.8)
	{
		e25_sensor->publish_state(e25);
	//	ESP_LOGD("custom", "e25 is: %3.2f", e25);
	//	ESP_LOGD("custom", "e25_old is: %3.2f", e25_old);
		e25_old = e25;
	}
	/*
	else 
	{
		e25_sensor->publish_state(e25_old);
		ESP_LOGD("custom", "e25_old is: %3.2f", e25_old);
	}
	*/
	
	if((ec > 0.0) ) //& (ec >= ec_old*0.8)
	{
		ec_sensor->publish_state(ec);
	//	ESP_LOGD("custom", "ec is: %3.2f", ec);
	//	ESP_LOGD("custom", "ec_old is: %3.2f", ec_old);
		ec_old = ec;
	}
	/*
	else 
	{
		ec_sensor->publish_state(ec_old);
		ESP_LOGD("custom", "ec_old is: %3.2f", ec_old);
		
	}
	*/
	
	if((temp > 0.0) ) //& (temp >= temp_old*0.8)
	{
		temp_sensor->publish_state(temp);
	//    ESP_LOGD("custom", "temp is: %3.2f", temp);
	//	ESP_LOGD("custom", "temp_old is: %3.2f", temp_old);	
		temp_old = temp;		
	}
	/*
	else 
	{
		temp_sensor->publish_state(temp_old);
		ESP_LOGD("custom", "temp_old is: %3.2f", temp_old);
	}
	*/
	
	if((vwc > 0.0)  ) //& (vwc >= vwc_old*0.8)
	{
		vwc_sensor->publish_state(vwc);
	//	ESP_LOGD("custom", "vwc is: %3.2f", vwc);
	//	ESP_LOGD("custom", "vwc_old is: %3.2f", vwc_old);
		vwc_old = vwc;
	}
	/*
	else 
	{
		vwc_sensor->publish_state(vwc_old);
		ESP_LOGD("custom", "vwc_old is: %3.2f", vwc_old);
	}
	*/
	
	/*
	ESP_LOGD("custom", "status TINOVI is: %d", status);
	ESP_LOGD("custom", "e25 is: %3.2f", e25);
    ESP_LOGD("custom", "ec is: %3.2f", ec);
	ESP_LOGD("custom", "temp is: %3.2f", temp);
    ESP_LOGD("custom", "vwc is: %3.2f", vwc);
	*/
	
	//delay(1000);

	}
  }
};```
