### ISSUE TITLE
bme680_bsec component: link error: undefined reference to `vtable for esphome::bme680_bsec::BME680BSECComponent'

### ISSUE THREAD

**Issue by jsuanet** [esphome/issues#2480]
### The problem

``` 
Using the bme680_bsec component with ESPHome version 2021.10.0-dev gives the following link error

Linking .pioenvs/test-bme680/firmware.elf
/Users/JSuanet/.platformio/packages/toolchain-xtensa@2.40802.200502/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/test-bme680/src/main.cpp.o:(.text.setup+0x70): undefined reference to `vtable for esphome::bme680_bsec::BME680BSECComponent'
collect2: error: ld returned 1 exit status
*** [.pioenvs/test-bme680/firmware.elf] Error 1

```

### Which version of ESPHome has the issue?

Version: 2021.10.0-dev

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

bme680_bsec

### Example YAML snippet

```yaml
esphome:
  name: test-bme680
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
   
logger:
  level: DEBUG

api:
  password: !secret api_password
  
ota:
  password: !secret ota_password

i2c:
  sda: D1
  scl: D2

bme680_bsec:
 address: 0x77
   
sensor:
  - platform: bme680_bsec
    temperature:
      # Temperature in °C
      name: "Temperature"
```
```


### Anything in the logs that might be useful for us?

```txt
Jos-MBP-new ➜  esphome-yaml esphome compile test-bme680.yaml
INFO Reading configuration test-bme680.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d test-bme680
Processing test-bme680 (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 2.6.2)
-------------------------------------------------------------------------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Library Manager: Installing Update
Warning! Could not find the package with 'Update' requirements for your system 'darwin_x86_64'
Dependency Graph
|-- <ESP8266WiFi> 1.0
|-- <Wire> 1.0
|-- <BSEC Software Library> 1.6.1480
|   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/test-bme680/src/main.cpp.o
Linking .pioenvs/test-bme680/firmware.elf
/Users/JSuanet/.platformio/packages/toolchain-xtensa@2.40802.200502/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pioenvs/test-bme680/src/main.cpp.o:(.text.setup+0x70): undefined reference to `vtable for esphome::bme680_bsec::BME680BSECComponent'
collect2: error: ld returned 1 exit status
*** [.pioenvs/test-bme680/firmware.elf] Error 1
```
```


### Additional information

_No response_
