### ISSUE TITLE
Unable to compile ESP32-C3 due to bsd socket error

### ISSUE THREAD

**Issue by markusg1234** [esphome/issues#2482]
### The problem

I am having an error regarding bsd sockets and is causing compile failure.

Regards,
Markus

### Which version of ESPHome has the issue?

v2021.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.7

### What platform are you using?

ESP32

### Board

ESP32-c3-devkitm-1

### Component causing the issue

bsd_sockets

### Example YAML snippet

```yaml
esphome:
  name: test
  platform: ESP32
  board: esp32-c3-devkitm-1  
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32#feature/arduino-idf-master
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
      

# Enable logging
logger:

api:
  password: "*"
ota:
  password: "*"

wifi:
  ssid: "*"
  password: "*"
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/test.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/test
Processing test (board: esp32-c3-devkitm-1; framework: arduino; platform: https://github.com/platformio/platform-espressif32#feature/arduino-idf-master)

Platform Manager: Installing git+https://github.com/platformio/platform-espressif32#feature/arduino-idf-master
git version 2.30.2
Cloning into '/root/.platformio/.cache/tmp/pkg-installing-ndcl3810'...
Platform Manager: espressif32 @ 3.3.1+sha.33ff413 has been installed!
The platform 'https://github.com/platformio/platform-espressif32#feature/arduino-idf-master' has been successfully installed!
The rest of the packages will be installed later depending on your build environment.
Tool Manager: Installing espressif/toolchain-riscv32-esp @ 8.4.0+2021r1
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: toolchain-riscv32-esp @ 8.4.0+2021r1 has been installed!
Tool Manager: Installing git+https://github.com/espressif/arduino-esp32.git
git version 2.30.2
Cloning into '/root/.platformio/.cache/tmp/pkg-installing-jygbnsn7'...
Updating files: 100% (6565/6565), done.
Tool Manager: framework-arduinoespressif32 @ 0.0.0+sha.317be68 has been installed!
Tool Manager: Installing platformio/tool-esptoolpy @ ~1.30100.0
Downloading  [####################################]  100%          
Tool Manager: tool-esptoolpy @ 1.30100.210531 has been installed!
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 0.0.0+sha.317be68 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - toolchain-riscv32-esp 8.4.0+2021r1
Library Manager: Installing Hash
Library Manager: Already installed, built-in library
Dependency Graph
|-- <ESPmDNS> 2.0.0
|   |-- <WiFi> 2.0.0
|-- <noise-c> 0.1.1
|-- <Update> 2.0.0
|-- <WiFi> 2.0.0
Linking /data/test/.pioenvs/test/firmware.elf
/root/.platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: /data/test/.pioenvs/test/src/esphome/components/socket/bsd_sockets_impl.cpp.o: in function `esphome::socket::BSDSocketImpl::writev(iovec const*, int)':
/config/esphome/test/src/esphome/components/socket/bsd_sockets_impl.cpp:132: undefined reference to `writev(int, iovec const*, int)'
/root/.platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: /data/test/.pioenvs/test/src/esphome/components/socket/bsd_sockets_impl.cpp.o: in function `esphome::socket::BSDSocketImpl::readv(iovec const*, int)':
/config/esphome/test/src/esphome/components/socket/bsd_sockets_impl.cpp:100: undefined reference to `readv(int, iovec const*, int)'
collect2: error: ld returned 1 exit status
*** [/data/test/.pioenvs/test/firmware.elf] Error 1
========================= [FAILED] Took 143.96 seconds =========================
```
