### ISSUE TITLE
Compilation error for esp01_1m

### ISSUE THREAD

**Issue by sebPomme** [esphome/issues#2485]
### The problem

I can't compile for `esp01_1m` on my raspberry-pi 4 anymore.

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

h801

### Component causing the issue

api, captive_portal, json

### Example YAML snippet

```yaml
`h801light.yaml`

esphome:
  name: h801light
  platform: ESP8266
  board: esp01_1m
  on_boot:
    then:
      - light.turn_on:
          id: kitchen_white_light
          brightness: 100%

wifi:
  ssid: 'super_wifi'
  password: 'mega_wifi_de_la_mort'
#  manual_ip:
#    static_ip: x.x.x.x
#    gateway: x.x.x.x
#    subnet: 255.255.255.0
  ap:
    ssid: "h801light-fallback"
    password: "cal97230"

captive_portal:

#logger:
api:
ota:

# custom web_server
web_server:
  port: 80

output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w
light:
  - platform: rgb
    #color_interlock: True
    name: "Kitchen rgb light"
    id: kitchen_rgb_light
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    effects:
      - random:
          name: Cercle de couleur 7s lent
          transition_length: 5s
          update_interval: 7s
      - random:
          name: Cercle de couleur 5s rapide
          transition_length: 2s
          update_interval: 5s
      - random:
          name: Cercle de couleur 15s lent
          transition_length: 5s
          update_interval: 15s
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 250ms
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - flicker:
          name: Flicker Effect With Custom Values
          alpha: 95%
          intensity: 1.5%
  - platform: monochromatic
    name: "Kitchen white light"
    id: kitchen_white_light
    output: pwm_w
    on_turn_on:
      - light.turn_off:
          id: kitchen_rgb_light
      - light.turn_on:
          id: kitchen_white_light
          brightness: 100%
```

### Anything in the logs that might be useful for us?

```txt
pomme@rpi % docker run --rm --network host -v /home/pomme/modifGPIIO/code/esp-home:/config --device=/dev/ttyUSB0 -i -t esphome/esphome h801light.yaml run --no-log
WARNING Calling ESPHome with the configuration before the command is deprecated and will be removed in the future. 
WARNING Please instead use:
WARNING    esphome run h801light.yaml --no-log
INFO Reading configuration h801light.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d h801light
Processing h801light (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@2.6.2)
-------------------------------------------------------------------------------------------------------------------------------
Tool Manager: Installing toolchain-xtensa @ ~2.40802.191122
Tool Manager: Warning! More than one package has been found by toolchain-xtensa @ ~2.40802.191122 requirements:
 - platformio/toolchain-xtensa @ 2.100300.210717
 - mcspr/toolchain-xtensa @ 5.100300.210830
 - tasmota/toolchain-xtensa @ 5.100200.210303
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: toolchain-xtensa @ 2.40802.200502 has been installed!
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Library Manager: Installing Update
Library Manager: Already installed, built-in library
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.3.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <noise-c> 0.1.1
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/h801light/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-lx106-elf-g++: not found
Compiling .pioenvs/h801light/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: xtensa-lx106-elf-g++: not found
Compiling .pioenvs/h801light/src/esphome/components/api/api_pb2.cpp.o
sh: 1: xtensa-lx106-elf-g++: not found
*** [.pioenvs/h801light/src/esphome/components/api/api_connection.cpp.o] Error 127
Compiling .pioenvs/h801light/src/esphome/components/api/api_pb2_service.cpp.o
*** [.pioenvs/h801light/src/esphome/components/api/api_frame_helper.cpp.o] Error 127
*** [.pioenvs/h801light/src/esphome/components/api/api_pb2.cpp.o] Error 127
sh: 1: xtensa-lx106-elf-g++: not found
*** [.pioenvs/h801light/src/esphome/components/api/api_pb2_service.cpp.o] Error 127
================================================= [FAILED] Took 19.91 seconds =================================================
```

### Additional information

My os
```
pomme@rpi % uname -a
Linux rpi-4 5.10.60-v8+ #1449 SMP PREEMPT Wed Aug 25 15:01:33 BST 2021 aarch64 GNU/Linux
pomme@rpi % lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
I try with `pip` version and, same result.

The problem is not present when compiling for `nodemcu-32s`
Pomme
