### ISSUE TITLE
2021.9.2 broke prometheus

### ISSUE THREAD

**Issue by fernandopn** [esphome/issues#2487]
### The problem

Hey ESPHome folks,

At 2021.9.1 I was able to reach the device with http://{esphomeip}/metrics and get the prometheus metrics with no problem (no authentication).
Now at 2021.9.2 it asks for password, leading to a an alert on my Prometheus:
- TargetDown (since prometheus cannot get the metrics anymore).

Thanks in advance,
- Fernando

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

not relevant

### What platform are you using?

ESP8266

### Board

Shelly 2.5

### Component causing the issue

prometheus

### Example YAML snippet

```yaml
esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

logger:

api:
  password: !secret api_password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret api_password

# Activates prometheus /metrics endpoint
prometheus:
```
