### ISSUE TITLE
Climate thermostat state is not updated when longer intervals expire

### ISSUE THREAD

**Issue by Alex9779** [esphome/issues#2492]
### The problem

Playing with the thermostat component in preparation for making my floor heating smart I found that if I use longer intervals for `min_heating_off_time`, `min_heating_run_time` and `min_idle_time` the status in HA is not updated when the device actually switches to the new state based on the set interval if a change in HA happens within the interval.
The issue occurs if I have an interval for example of 30 seconds for all three options.
Start with a actual temperature of 20° and a set of 18°, the thermostat is off. I switch it to heating and the thermostat changes to 'Idle' as expected. Changing the set-point temperature to 22° after waiting 30 seconds brings it to 'Heating' and the device actually activates the output right away. All good.
But if I change the set-point right after switching heating on before the 30 seconds expire the status stays on 'Idle'. After the time expires the device activates the output but the status in HA does not update, it is still 'Idle' and stays 'Idle' forever.
If I then change the temperature to 18° I get 'Idle', raising the temperature before 30 seconds are over to 23° it still reads 'Idle', the devices activates the output after the 30 seconds expired so.

From what I can tell and see in the DEBUG log from the climate component is that the device only sends an update of its state right after it received a change from HA but not when a timer expires and the action is really done in case of longer intervals that allow the user to send changes while a timeout is still active.

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.7

### What platform are you using?

ESP8266

### Board

D1 mini

### Component causing the issue

thermostat

### Example YAML snippet

```yaml
climate:
  - platform: thermostat
    name: test1
    sensor: temperature_test1
    default_target_temperature_low: 18 °C
    min_heating_off_time: 30s
    min_heating_run_time: 30s
    min_idle_time: 30s
    heat_action:
      - output.turn_on: hc1
    idle_action:
      - output.turn_off: hc1
```
