### ISSUE TITLE
Constant API disconnections with multiple MCP23017

### ISSUE THREAD

**Issue by SmarterHomeLife** [esphome/issues#2493]
### The problem

I'm building a lighting control system based on an ESP32 and multiple MCP23017 I2C expanders for inputs and outputs across the 2 x I2C buses on the ESP32, from the notes on the website you can have up to 8 x MCP23017 on an I2C bus but I'm having an issue with any more than 5.

After a day of trial and error, I have 4 x MCP23017 providing 64 inputs and 1 x MCP23017 providing 16 outputs working on a single I2C bus at a frequency of 400kHz.

When I add another 2 x MCP23017 to get an extra 32 inputs, I get these lines constantly in the debug log and all entities show as unavailable in Home Assistant, but all the inputs and outputs still work and show in the esphome log.

The same lines also fill the logs if the frequency is set lower than 400kHz.

[21:07:10][D][api.connection:153]: Home Assistant 2021.9.7 (10.0.4.10) requested disconnected
[21:07:10][D][api:095]: Accepted 10.0.4.10
[21:07:10][D][api.connection:727]: Home Assistant 2021.9.7 (10.0.4.10): Connected successfully
[21:07:15][D][api.connection:153]: Home Assistant 2021.9.7 (10.0.4.10) requested disconnected
[21:07:15][D][api:095]: Accepted 10.0.4.10
[21:07:15][D][api.connection:727]: Home Assistant 2021.9.7 (10.0.4.10): Connected successfully
[21:07:20][D][api.connection:153]: Home Assistant 2021.9.7 (10.0.4.10) requested disconnected
[21:07:20][D][api:095]: Accepted 10.0.4.10
[21:07:20][D][api.connection:727]: Home Assistant 2021.9.7 (10.0.4.10): Connected successfully
[21:07:25][D][api.connection:153]: Home Assistant 2021.9.7 (10.0.4.10) requested disconnected
[21:07:25][D][api:095]: Accepted 10.0.4.10
[21:07:25][D][api.connection:727]: Home Assistant 2021.9.7 (10.0.4.10): Connected successfully

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.7

### What platform are you using?

ESP32

### Board

D1 Mini ESP32 and QuinLED ESP32 are both the same

### Component causing the issue

API/I2C

### Example YAML snippet

```yaml
substitutions:
  devicename: lighting-control-d32-2b24
  name: Lighting Control 2B24
  hotspot: Lighting Control 2B24 WiFi
  password: !secret psk
  static_ip: 10.0.4.11

esphome:
  name: $devicename
  platform: ESP32
  board: wemos_d1_mini32

  on_boot:
    then:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          blue: 100%
          green: 100%
          effect: random

wifi:
  ssid: !secret ssid
  password: !secret psk
  fast_connect: on
  manual_ip:
    static_ip: $static_ip
    gateway: 10.0.4.1
    subnet: 255.255.255.0
#  use_address: lighting-control-d32-2b24.local
  ap:
    ssid: $hotspot
    password: $password

captive_portal:

web_server:
  port: 80

logger:
  level: debug

api:
  password: !secret api_pwd

ota:
  password: !secret api_pwd

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $name IP Address

sensor:
  - platform: wifi_signal
    name: $name WiFi Signal
    update_interval: 60s

i2c:
  sda: 21
  scl: 22
  scan: True
  frequency: 400kHz
  id: bus_a

mcp23017:
  - id: 'lighting1'
    address: 0x20
  - id: 'lighting2'
    address: 0x21
  - id: 'lighting3'
    address: 0x22
  - id: 'lighting4'
    address: 0x23
  - id: 'lighting5'
    address: 0x24
  - id: 'lighting6'
    address: 0x25
  - id: 'lighting7'
    address: 0x26

binary_sensor:
  - platform: status
    name: $name Status

  - platform: gpio
    name: "Button 1"
    pin:
      mcp23xxx: lighting1
      number: 0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: output_1

((To shorten the YAML, I've removed most of the inputs as they're all the same and confirmed correct))

  - platform: gpio
    name: "Button 96"
    pin:
      mcp23xxx: lighting6
      number: 15
      mode: INPUT_PULLUP
      inverted: True

switch:
  - platform: gpio
    name: "Light 1"
    id: output_1
    pin:
      mcp23xxx: lighting7
      number: 0
      mode: OUTPUT

  - platform: gpio
    name: "Light 2"
    id: output_2
    pin:
      mcp23xxx: lighting7
      number: 1
      mode: OUTPUT

  - platform: gpio
    name: "Light 3"
    id: output_3
    pin:
      mcp23xxx: lighting7
      number: 2
      mode: OUTPUT

  - platform: gpio
    name: "Light 4"
    id: output_4
    pin:
      mcp23xxx: lighting7
      number: 3
      mode: OUTPUT

  - platform: gpio
    name: "Light 5"
    id: output_5
    pin:
      mcp23xxx: lighting7
      number: 4
      mode: OUTPUT

  - platform: gpio
    name: "Light 6"
    id: output_6
    pin:
      mcp23xxx: lighting7
      number: 5
      mode: OUTPUT

  - platform: gpio
    name: "Light 7"
    id: output_7
    pin:
      mcp23xxx: lighting7
      number: 6
      mode: OUTPUT

  - platform: gpio
    name: "Light 8"
    id: output_8
    pin:
      mcp23xxx: lighting7
      number: 7
      mode: OUTPUT

  - platform: gpio
    name: "Light 9"
    id: output_9
    pin:
      mcp23xxx: lighting7
      number: 8
      mode: OUTPUT

  - platform: gpio
    name: "Light 10"
    id: output_10
    pin:
      mcp23xxx: lighting7
      number: 9
      mode: OUTPUT

  - platform: gpio
    name: "Light 11"
    id: output_11
    pin:
      mcp23xxx: lighting7
      number: 10
      mode: OUTPUT

  - platform: gpio
    name: "Light 12"
    id: output_12
    pin:
      mcp23xxx: lighting7
      number: 11
      mode: OUTPUT

  - platform: gpio
    name: "Light 13"
    id: output_13
    pin:
      mcp23xxx: lighting7
      number: 12
      mode: OUTPUT

  - platform: gpio
    name: "Light 14"
    id: output_14
    pin:
      mcp23xxx: lighting7
      number: 13
      mode: OUTPUT

  - platform: gpio
    name: "Light 15"
    id: output_15
    pin:
      mcp23xxx: lighting7
      number: 14
      mode: OUTPUT

  - platform: gpio
    name: "Light 16"
    id: output_16
    pin:
      mcp23xxx: lighting7
      number: 15
      mode: OUTPUT

light:
  - platform: fastled_clockless
    id: led
    chipset: WS2812B
    pin: 17
    num_leds: 4
    rgb_order: GRB
    name: $name LED
    effects:
      - addressable_rainbow:
          name: Rainbow
          speed: 10
          width: 8
      - addressable_scan:
          name: Scan Effect
          move_interval: 100ms
          scan_width: 4
      - random:
          name: Random
          transition_length: 10s
          update_interval: 20s
```
