### ISSUE TITLE
Multi Click with Light Automation isn't working anymore

### ISSUE THREAD

**Issue by 7h30n3** [esphome/issues#2494]
### The problem

As mentioned in #2470 after updating to the latest version my light automation isn't working anymore. After some testing I figured out that the last working version was `1.20.4`.

I either can turn on and off the light or I can turn it on and switch the color from red to white, but can't turn it off again.
The expected behavior is to turn on the light in red with a long click or in white with a short click. And if it's on, the next click turns it off.

### Which version of ESPHome has the issue?

1.21.0b1

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

nodemcu

### Example YAML snippet

```yaml
binary_sensor:
  - platform: gpio
    pin: 
      number: 1
      inverted: true
      mode: INPUT_PULLUP
    name: "Right Switch"
    
    on_multi_click:
    - timing:
        - ON for at least 0.3s
      then:
        - logger.log: "Single Long Clicked"
        - light.turn_on:
            id: "${device_id}_light"
            red: 1
            green: 0
            blue: 0
            brightness: 0.3
    - timing:
        - ON for at most 0.3s
        - OFF for at least 0.2s
      then:
        - logger.log: "Single Short Click"
        - if:
            condition:
              - light.is_off: "${device_id}_light"
            then:
              - light.turn_on:
                  id: "${device_id}_light"
                  red: 1
                  green: 1
                  blue: 1
                  brightness: 1
            else:
              - light.turn_off:
                  id: "${device_id}_light"
                  
light:
  - platform: fastled_clockless
    name: "${device_name} Light"
    id: "${device_id}_light"
    chipset: WS2812B
    pin: 13
    num_leds: 60
    rgb_order: GRB  
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

"Clicks" are recognized, but the expected action isn't performed.
