### ISSUE TITLE
Enabling encryption causes warning message after firmware is OTA'd

### ISSUE THREAD

**Issue by bachya** [esphome/issues#2502]
### The problem

When attempting to utilize encryption on a node flashed with 2021.9.2, the logs throw a warning and the node doesn't seem to provide any further logs.

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.10.0b2

### What platform are you using?

ESP8266

### Board

esp8285

### Component causing the issue

api

### Example YAML snippet

```yaml
---
api:
  encryption:
    key: !secret api_encryption_key
  password: !secret api_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    name: Power Button
    on_press:
      - switch.toggle: relay

  - platform: status
    name: Smart Plug 1

esphome:
  name: smart-plug-1
  platform: ESP8266
  board: esp8285

logger:

ota:

status_led:
  pin:
    number: GPIO1
    inverted: true

switch:
  - platform: gpio
    id: led
    pin: GPIO13
    inverted: true

  - platform: gpio
    name: "${device_friendly_name}"
    pin: GPIO14
    id: relay
    on_turn_on:
      - switch.turn_on: led
    on_turn_off:
      - switch.turn_off: led

text_sensor:
  - platform: template
    name: "${device_friendly_name}: ESPHome Version (Short)"
    lambda: |-
      auto state = id(esphome_version).state;
      return state.substr(0, state.find(' '));

  - platform: version
    name: "${device_friendly_name}: ESPHome Version"
    id: esphome_version

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 20dB

  manual_ip:
    static_ip: 192.168.1.100
    gateway: 192.168.1.1
    subnet: 255.255.255.0
```

### Anything in the logs that might be useful for us?

```txt
When I upload this firmware using the 2021.9.2 Docker image:


docker run --rm -v "$(PWD)/esphome":/config esphome/esphome:2021.9.2 run smart_plug_1.yaml


...it succeeds, but shortly thereafter, I get a warning in the logs (and no further logs are generated)::

```
INFO Successfully compiled program.
INFO Connecting to 192.168.1.100
INFO Uploading smart-plug-1/.pioenvs/smart-plug-1/firmware.bin (395392 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.1.100 using esphome API
WARNING Can't connect to ESPHome API for 172.16.20.141: Error while reading data: 0 bytes read on a total of 3 expected bytes
```

If I comment out the encryption lines and re-run the firmware, everything works as expected:

```
INFO Successfully compiled program.
INFO Connecting to 192.168.1.100
INFO Uploading smart-plug-1/.pioenvs/smart-plug-1/firmware.bin (374432 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.1.100 using esphome API
INFO Successfully connected to 192.168.1.100
[21:01:17][I][app:102]: ESPHome version 2021.9.2 compiled on Oct  1 2021, 21:00:25
[21:01:18][C][status_led:019]: Status LED:
[21:01:18][C][status_led:020]:   Pin: GPIO1 (Mode: OUTPUT, INVERTED)
[21:01:18][C][wifi:501]: WiFi:
[21:01:18][C][wifi:361]:   SSID: 'Phil?_IoT'
[21:01:18][C][wifi:362]:   IP Address: 192.168.1.100
[21:01:18][C][wifi:364]:   BSSID: 02:EC:DA:F1:1E:C1
[21:01:18][C][wifi:365]:   Hostname: 'smart-plug-1'
[21:01:18][C][wifi:369]:   Signal strength: -74 dB ▂▄▆█
[21:01:18][C][wifi:373]:   Channel: 1
[21:01:18][C][wifi:374]:   Subnet: 255.255.255.0
[21:01:18][C][wifi:375]:   Gateway: 192.168.1.1
[21:01:18][C][wifi:376]:   DNS1: (IP unset)
[21:01:18][C][wifi:377]:   DNS2: (IP unset)
[21:01:18][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Power Button'
[21:01:18][C][gpio.binary_sensor:016]:   Pin: GPIO4 (Mode: INPUT, INVERTED)
[21:01:18][C][switch.gpio:048]: GPIO Switch 'led'
[21:01:18][C][switch.gpio:048]:   Inverted: YES
[21:01:18][C][switch.gpio:049]:   Pin: GPIO13 (Mode: OUTPUT)
[21:01:18][C][switch.gpio:071]:   Restore Mode: Restore (Defaults to OFF)
[21:01:18][C][switch.gpio:048]: GPIO Switch 'Smart Plug 1'
[21:01:18][C][switch.gpio:049]:   Pin: GPIO14 (Mode: OUTPUT)
[21:01:18][C][switch.gpio:071]:   Restore Mode: Restore (Defaults to OFF)
[21:01:18][C][template.text_sensor:021]: Template Sensor 'Smart Plug 1: ESPHome Version (Short)'
[21:01:18][C][logger:193]: Logger:
[21:01:18][C][logger:194]:   Level: DEBUG
[21:01:18][C][logger:195]:   Log Baud Rate: 115200
[21:01:18][C][logger:196]:   Hardware UART: UART0
[21:01:18][C][status:034]: Status Binary Sensor 'Smart Plug 1 Status'
[21:01:18][C][status:034]:   Device Class: 'connectivity'
[21:01:18][C][version.text_sensor:021]: Version Text Sensor 'Smart Plug 1: ESPHome Version'
[21:01:18][C][version.text_sensor:021]:   Icon: 'mdi:new-box'
[21:01:18][C][ota:029]: Over-The-Air Updates:
[21:01:18][C][ota:030]:   Address: 192.168.1.100:8266
[21:01:18][C][api:135]: API Server:
[21:01:18][C][api:136]:   Address: 192.168.1.100:6053
```
```

### Additional information

(FYI, I used the randomly-generated string from [the documentation](https://esphome.io/components/api.html?highlight=encryption#configuration-variables) for my encryption key.)
