### ISSUE TITLE
Nightly build 2021-10-0, missing WiFiType.h

### ISSUE THREAD

**Issue by SeByDocKy** [esphome/issues#2509]
### The problem

Compilation Error linked with a missing file

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.7

### What platform are you using?

ESP32

### Board

WROOM32

### Component causing the issue

Wifi

### Example YAML snippet

```yaml
esphome:
  name: station_meteo
  platform: ESP32
  board: esp32dev

  includes:
    - veml6070_custom_sensor.h
    - tx23_custom_sensor.h
  libraries:
    - "https://github.com/adafruit/Adafruit_VEML6070"
    - "https://github.com/egzumer/Arduino-LaCrosse-TX23-Library"
    - SPI
    
  on_boot:
    priority: -100
    then:
      - switch.turn_on: reset_GPIO02
      - delay: 1000ms
      - switch.turn_off: reset_GPIO02  
 
wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_password
  
# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:



time:

  - platform: homeassistant
    id: homeassistant_time  
    
    on_time:
      - seconds: 58
        minutes: 59
        hours: 23
        then:  
          - sensor.template.publish:
              id: template_yesteday_rain
              state: !lambda return id(daily_rain).state;
              
          #- sensor.integration.reset: daily_rain    

i2c:
  sda: GPIO22
  scl: GPIO21

binary_sensor:

  - platform: status
    name: "station_meteo_status"
    
    
switch:
  - platform: restart
    name: "restart_station_meteo"
    
  - platform: gpio
    pin: GPIO12
    inverted: yes
    id: reset_GPIO02  

sensor:

  - platform: pulse_counter
    pin:
      number: GPIO12
      inverted: True
      mode: INPUT_PULLUP    
    unit_of_measurement: 'mm'
    update_interval: 2s
    accuracy_decimals: 3
    name: 'station_meteo_compteur_pluviometre'
    id: rain_meter
    filters:
      - multiply:  25 #0.0250 #0.367    #90/2.25ml om 90 est la valeur pour chaque bascule ave 2s et 2.25ml est le volume de chaque réservoir

  - platform: total_daily_energy
    name: "station_meteo_pluie_du_jour"
    power_id: rain_meter  
    unit_of_measurement: "mm"
    accuracy_decimals: 3
    id: daily_rain
    icon: mdi:water
    
    
  #- platform: pulse_counter
  #  pin:
  #    number: GPIO12
  #    inverted: True
  #    mode: INPUT_PULLUP
  #  update_interval: 60s
  #  accuracy_decimals: 0
  #  name: 'control_exterieur_compteur_pluviometre'
  #  id: rain_meter 
    
  #- platform: integration
  #  name: "control_exterieur_pluie_du_jour"
  #  id: daily_rain
  #  sensor: rain_meter
  #  time_unit: min
  #  unit_of_measurement: 'mm'
  #  accuracy_decimals: 4
  #  filters:
  #    - multiply: 0.3125  
    
  - platform: template
    name: "station_meteo_pluie_veille"
    id: template_yesteday_rain
    unit_of_measurement: "mm"
    accuracy_decimals: 3
    icon: mdi:water
    update_interval: 10s
    
  - platform: bme280
    temperature:
      name: "station_meteo_temperature"
      oversampling: 16x
      id: station_meteo_temperature
    pressure:
      name: "station_meteo_pression"
      id: station_meteo_pression
    humidity:
      name: "station_meteo_humidite"
      id: station_meteo_humidite
    address: 0x76
    update_interval: 5s

  #- platform: tx20
  #  wind_speed:
  #    name: "station_meteo_vitesse_vent"
  #    unit_of_measurement: "m/s"
  #    icon: "mdi:weather-windy"
  #    accuracy_decimals: 1
  #  wind_direction_degrees:
  #    name: "station_meteo_direction_vent"
  #  pin:
  #    number: GPIO2
  #    #mode: INPUT_PULLUP
  #  id: tx20_id

  - platform: custom
    id: tx23_id
    lambda: |-
      auto TX23 = new TX23CustomSensor();
      App.register_component(TX23);
      return {TX23->speed_sensor, TX23->direction_sensor};

    sensors:
    - name: "station_meteo_vitesse_vent"
      unit_of_measurement: "m/s"
      accuracy_decimals: 1
      icon: "mdi:weather-windy"
    
    - name: "station_meteo_direction_vent"
      unit_of_measurement: "°"
      icon: "mdi:compass-outline"
      id: "station_meteo_direction_vent"
   
      
  - platform: bh1750
    name: "station_meteo_luminosite"
    address: 0x23
    update_interval: 5s
#    measurement_time: 31
    filters:
#    - lambda: if (x < 54612.5) return x;
    - sliding_window_moving_average:
        window_size: 9
        send_every: 1
    
  - platform: pulse_counter
    pin: GPIO36
    name: "station_meteo_compteur_geiger"
    update_interval: 15s    
  
  - platform: custom
    lambda: |-
      auto veml6070 = new VEML6070CustomSensor();
      App.register_component(veml6070);
      return {veml6070};
    sensors:
      name: "station_meteo_UV"
      unit_of_measurement: "mW/m²"
      accuracy_decimals: 2
      filters:
      - delta: 10
      - multiply: 0.03
      - filter_out: 65535
      - lambda: |-
          if (x > 600) {
            return 0;
          } else {
            return x;
          }
  - platform: uptime
#    name: "up_station_meteo"
    id: uptime_sec
    
  - platform: wifi_signal
    name: "WiFi puissance_station_meteo"
    update_interval: 10s  
    
#  - platform: template
#    name: station_meteo_uptime
#    lambda: |-
#      int seconds = (id(uptime_sec).state);
#      int days = seconds / (24 * 3600);
#      seconds = seconds % (24 * 3600); 
#      int hours = seconds / 3600;
#      seconds = seconds % 3600;
#      int minutes = seconds /  60;
#      seconds = seconds % 60;
#      return { (String(days) + "d " + String(hours) + "h " + String(minutes) + "m "+ String(seconds) + "s").c_str() };
#    icon: mdi:clock-start
#    update_interval: 113s  



text_sensor:
  - platform: template
    name: station_meteo_uptime_total # Temps total depuis le démarrage de la carte
    lambda: |-
      int seconds = (id(uptime_sec).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds / 60;
      seconds = seconds % 60;
      if ( days ) {
        return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s ").c_str() };
      } else if ( hours ) {
        return { (String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s ").c_str() };
      } else if ( minutes ) {
        return { (String(minutes) +"m "+ String(seconds) +"s ").c_str() };
      } else {
        return { (String(seconds) +"s ").c_str() };
      }
    icon: mdi:clock-start
    update_interval: 113s
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/station_meteo.yaml...
WARNING 'station_meteo': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
INFO Detected timezone 'Europe/Paris'
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/station_meteo
Processing station_meteo (board: esp32dev; framework: arduino; platform: espressif32 @ 3.3.2)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF Modes: Finder ~ off, Compatibility ~ soft
Library Manager: Installing Hash
Library Manager: Already installed, built-in library
Dependency Graph
|-- <Adafruit VEML6070 Library> 1.0.6+sha.ecd2a5e
|-- <La Crosse RX23 Library> 1.0.0+sha.92ce726
|-- <SPI> 1.0
|-- <Update> 1.0
|-- <Wire> 1.0.1
|-- <ESPmDNS> 1.0
Compiling /data/station_meteo/.pioenvs/station_meteo/src/esphome/components/network/util.cpp.o
Compiling /data/station_meteo/.pioenvs/station_meteo/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling /data/station_meteo/.pioenvs/station_meteo/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling /data/station_meteo/.pioenvs/station_meteo/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling /data/station_meteo/.pioenvs/station_meteo/src/esphome/components/ota/ota_component.cpp.o
Compiling /data/station_meteo/.pioenvs/station_meteo/src/esphome/components/pulse_counter/pulse_counter_sensor.cpp.o
In file included from src/esphome/components/network/util.cpp:5:0:
src/esphome/components/wifi/wifi_component.h:13:22: fatal error: WiFiType.h: No such file or directory

******************************************************************
* Looking for WiFiType.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFiType.h"
* Web  > https://platformio.org/lib/search?query=header:WiFiType.h
*
******************************************************************

compilation terminated.
*** [/data/station_meteo/.pioenvs/station_meteo/src/esphome/components/network/util.cpp.o] Error 1
========================= [FAILED] Took 12.31 seconds =========================
```

### Additional information

i) Compile and work fine with the stable version
