### ISSUE TITLE
PZEM 016 system crashes

### ISSUE THREAD

**Issue by e1z0** [esphome/issues#2513]
### The problem

Constant crashes with PZEM016 module connected to d1 mini esp8266 using built-in 5V output from module, tried swap tx/rx nothing helped. It's crashing randomly, can run whole day without crash or can crash 5mins from startup and so on.

Connected using this schema (without lcd, only rx,tx,vcc 5v and gnd):
![](https://github.com/Gio-dot/PZEM-016-OLED-2-OUT-ESPHome/raw/master/img/ESPHome-wemos-d1-pzem016-display_bb.png)
)

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.9.6

### What platform are you using?

ESP8266

### Board

d1 mini

### Component causing the issue

pzemac

### Example YAML snippet

```yaml
substitutions:
  esp_name: energy-monitor-1
  esp_name_upper: Energy Phase 1
  description: First phase energy monitor

esphome:
  name: ${esp_name}
  comment: ${description}
  platform: ESP8266
  board: d1_mini
  #arduino_version: latest
  arduino_version: dev

wifi:
  fast_connect: true
  power_save_mode: none
  reboot_timeout: 7min
  use_address: ${esp_name}.local
  ssid: !secret wifi_ap
  password: !secret wifi_password
  ap:
    ssid: "${esp_name_upper} AP"
    password: ""

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker
  client_id: ${esp_name}-client
  username: livingroom
  password: MyMQTTPassword
  discovery: true

debug:

# Enable logging
logger:
  baud_rate: 0
  level: debug

ota:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  stop_bits: 1

sensor:
  - platform: pzemac
    current:
      name: "${esp_name_upper} Current"
      id: aac
      internal: true
    voltage:
      name: "${esp_name_upper} Voltage"
      id: vac
      internal: true
    power:
      name: "${esp_name_upper} Power"
      id: w
      internal: true
    frequency:
      name: "${esp_name_upper} Frequency"
      id: f
      internal: true
    power_factor:
      name: "${esp_name_upper} Power Factor"
      id: pf
      internal: true
    update_interval: 2s
  - platform: total_daily_energy
    name: "${esp_name_upper} Daily Energy"
    power_id: w
    filters:
        # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:counter
    accuracy_decimals: 1

  - platform: template #########################
    name: "${esp_name_upper} Current Slow"
    lambda: |-
      if (id(aac).state) {
        return (id(aac).state);
      } else {
        return 0;
      }
    unit_of_measurement: A
    icon: "mdi:alpha-a-circle"
    update_interval: 10s

  - platform: template #########################
    name: "${esp_name_upper} Voltage Slow"
    lambda: |-
      if (id(vac).state) {
        return (id(vac).state);
      } else {
        return 0;
      }
    unit_of_measurement: V
    icon: "mdi:alpha-v-circle"
    update_interval: 10s

  - platform: template #########################
    name: "${esp_name_upper} Power Slow"
    lambda: |-
      if (id(w).state) {
        return (id(w).state);
      } else {
        return 0;
      }
    unit_of_measurement: W
    icon: "mdi:alpha-w-circle"
    update_interval: 10s
  - platform: template #########################
    name: "${esp_name_upper} Frequency Slow"
    lambda: |-
      if (id(f).state) {
        return (id(f).state);
      } else {
        return 0;
      }
    unit_of_measurement: Hz
    icon: "mdi:alpha-f-circle"
    update_interval: 10s
  - platform: template #########################
    name: "${esp_name_upper} Power Factor Slow"
    lambda: |-
      if (id(pf).state) {
        return (id(pf).state);
      } else {
        return 0;
      }
    unit_of_measurement: PF
    icon: "mdi:alpha-p-circle"
    update_interval: 10s
```

### Anything in the logs that might be useful for us?

```txt
Reset Info: Fatal exception:0 flag:2 (Exception) epc1:0x4023e525 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000
Reset Info: Fatal exception:4 flag:1 (Hardware Watchdog) epc1:0x40242e13 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000
Reset Info: Fatal exception:0 flag:2 (Exception) epc1:0x402532a3 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000
```

### Additional information

I've also tried different arduino_version from 3.0.1 to 2.6.3, the same problem on all versions. Also tried manual ip wifi configuration without fast connect, different AP, with power saving and without. When disconnected from module or with wrong baud_rate, it never crashes.
