### ISSUE TITLE
DSMR: no gas usage for DSMR2

### ISSUE THREAD

**Issue by peterforeman** [esphome/issues#2517]
### The problem

Earlier the DSMR component was updated for usage with the DSMR2 standard. These changes are merged in the dev branch. I tried updating my ESP32 P1 reader with the latest ESPhome dev and now it reports the correct data - except the gas usage which is stays "unknown".

Closed DSMR2 issue: https://github.com/esphome/issues/issues/2363
PR that did not fix this problem: https://github.com/esphome/esphome/pull/2157

### Which version of ESPHome has the issue?

2021.10.0-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Not relevant

### What platform are you using?

ESP32

### Board

ESP32 wrover

### Component causing the issue

dsmr

### Example YAML snippet

```yaml
#######################################################################
# Use ESP32 Serial2
uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  data_bits: 7
  parity: NONE
  stop_bits: 1

# DSMR2 has no CRC
dsmr:
  crc_check: false

sensor:
  - platform: dsmr
    gas_delivered:
      name: "Gas Delivery Total"
      id: gas_delivery_total
      state_class: "total_increasing"
      unit_of_measurement: "m³"
```

### Anything in the logs that might be useful for us?

```txt
No error messages, just no update for this specific sensor. Same for DSMR version sensor.

Text that DSMR2 produces:
0-2:24.3.0(180822110000)(08)(60)(1)(0-2:24.2.0)(m3)
(04700.692)

Note that the actual sensor data is on the next line.
```
