### ISSUE TITLE
Unable to get initial flash of ESP32-CAM working

### ISSUE THREAD

**Issue by nhorvath** [esphome/issues#252]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio addion on x86_64 virtual machine, downloaded binary and trying to flash with esptool on windows. Also tried NodeMCU-pyflasher-3.0

**ESP (ESP32/ESP8266, Board/Sonoff):**

AiThinker clone ESP32-CAM
This one specifically: https://www.aliexpress.com/item/ESP32-CAM-WiFi-Module-Module-ESP32-with-OV2640/33001043678.html?spm=a2g0s.9042311.0.0.27424c4d18eQdP

**Affected component:**

esp32cam

**Description of problem:**
Flashing says it's successful but after resetting the device the led just flashes and never connects to wifi.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32_cam
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "horvath"
  password: "redacted"
  domain: '.horvath'

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'redacted'

ota:
  password: 'redacted'

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: ESP32-CAM
  #resolution: 1600x1200
```

**Traceback (if applicable):**

```
n/a
```

**Additional information and things you've tried:**
```esptool.py.exe --port COM10 write_flash --flash_mode dio 0x0 f:\Downloads\esp32_cam.bin```
I tried a few different flashers, tried erasing the flash. Double checked my wifi config. Tried a different power supply. Nothing seems to get it to connect.

Something else I noticed is I tried to use board: esp32cam as would be indicated here, but it said it was invalid: http://docs.platformio.org/en/latest/boards/espressif32/esp32cam.html#board-espressif32-esp32cam
When that didn't work I just used the one for generic ESP32.
