### ISSUE TITLE
Compile failes with error " HTTPClient.h: No such file or directory" - latest docker image

### ISSUE THREAD

**Issue by vijaygill** [esphome/issues#2520]
### The problem

The code compile failes with latest docker image. The error is

```
In file included from src/esphome/components/nextion/nextion.cpp:1:0:
src/esphome/components/nextion/nextion.h:12:24: fatal error: HTTPClient.h: No such file or directory

```

### Which version of ESPHome has the issue?

latest dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

nextion

### Example YAML snippet

```yaml
Snippet from my YAML file

uart:
    - id: uart_nextion0
      rx_pin: GPIO16
      tx_pin: GPIO17
      baud_rate: 115200

display:
    - platform: nextion
      id: nextion0
      uart_id: uart_nextion0
```
