### ISSUE TITLE
atm90e32 driver "Foward Active Energy" doesn't work the way homeassistant expects

### ISSUE THREAD

**Issue by davidmonro** [esphome/issues#2523]
### The problem

The 'Foward Active Energy' counters (and presumably the reverse ones as well) report themselves to HA as having a state class of 'total_increasing', which I believe means that HA expects them to be a cumulative total, like a utility electricity meter. If the counter decreases then I think HA assumes the device as been replaced or reset, and takes the last number before the decrease as a baseline and then adds the new cumulative total to that for the HA internal cumulative total used in the long-term stats.

What these counters actually do with the current code is return the amount of energy consumed _since the last update_. This means that HA sees a very small total with frequent random resets (when consumption for an update period happens to be less than the last period), and produces nothing useful in the energy dashboard.

What I think needs to happen is for ESPHome to keep an internal cumulative total of these registers which it reports back to HA. An alternative might be to report an extra 0 reading for them after every actual reading, so that HA thinks the device is continually be resetting on every update. I think the internal sum is probably preferable, particularly as then it doesn't matter if HA misses some updates.

(I'm assuming this is a result of the change where last_reset was dropped).

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.9.7

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

atm90e32

### Example YAML snippet

```yaml
// This is basically just the example for the CircuitSetup Split Single Phase Energy Meter from https://esphome.io/components/sensor/atm90e32.html just with my calibrations and the forward_active_energy and reverse_active_energy sensors activated

sensor:
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: "EMON Line Voltage A"
      current:
        name: "EMON CT1 Current"
      power:
        name: "EMON Active Power CT1"
      reactive_power:
        name: "EMON Reactive Power CT1"
      power_factor:
        name: "EMON Power Factor CT1"
      forward_active_energy:
        name: "EMON Foward Active Energy CT1"
      reverse_active_energy:
        name: "EMON Reverse Active Energy CT1"
      gain_voltage: 8080
      gain_ct: 24270
    phase_c:
      voltage:
        name: "EMON Line Voltage B"
      current:
        name: "EMON CT2 Current"
      power:
        name: "EMON Active Power CT2"
      reactive_power:
        name: "EMON Reactive Power CT2"
      power_factor:
        name: "EMON Power Factor CT2"
      forward_active_energy:
        name: "EMON Foward Active Energy CT2"
      reverse_active_energy:
        name: "EMON Reverse Active Energy CT2"
      gain_voltage: 8080
      gain_ct: 24270
    frequency:
      name: "EMON Line Frequency"
    chip_temperature:
      name: "EMON Chip Temperature"
    line_frequency: 50Hz
    current_phases: 2
    gain_pga: 2X
    update_interval: 30s
```
