### ISSUE TITLE
ESPHome light reboots after connecting to wifi

### ISSUE THREAD

**Issue by TheFes** [esphome/issues#2524]
### The problem

I have several ESPHome lightbulbs. Some nights ago there were some wifi issues, and the lights turned on during the night, which was unexpected and unwanted.
To prevent this I added `reboot_timeout: 0s` to both `api:` and `wifi:` which prevents the lightbulb from rebooting after 15 minutes.
However, the bulb also reboots when it connects to wifi again.

With the reboot_timeout disabled, the light turns on after enabling wifi on my router again. And the uptime is restarted, so this would mean it did a reboot.

I know I can use `restore_mode: ALWAYS_OFF` but I would rather not set that, because that would mean I can no longer turn them on by use of the wall switch in case of a disruption in my wifi network, or in case HA is not working for any reason.

Is there a way to prevent the ESP from rebooting when it connects to wifi?

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10

### What platform are you using?

ESP8266

### Board

esp01_1m

### Example YAML snippet

```yaml
substitutions:
  device_name: Slaapkamer
  device_type: Light
  ip: 192.168.2.36

esphome:
  name: slaapkamer_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: on
  reboot_timeout: 0s
  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.2.100
    subnet: 255.255.255.0
  ap:
    ssid: "${device_name} ${device_type} Hotspot"
    password: !secret hotspot_pass

captive_portal:
  
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  reboot_timeout: 0s

# Enable OTA updates
ota:

# Enable Web server
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${device_name} ${device_type} IP

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${device_name} ${device_type} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${device_name} ${device_type} WiFi Signal
    update_interval: 60s 

output:
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_daylight
    pin: GPIO14

light:
  - platform: cwww
    name: ${device_name}
    id: light_bulb
    cold_white: output_daylight
    warm_white: output_warm_white
    cold_white_color_temperature: 153 mireds
    warm_white_color_temperature: 370 mireds
    restore_mode: ALWAYS_OFF
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"

switch:
  - platform: restart
    name: "${device_name} ${device_type} Restart"

binary_sensor:
  - platform: status
    name: ${device_name} ${device_type} Status
```

### Anything in the logs that might be useful for us?

```txt
No option to view logs, as I can not connect it with serial
```
