### ISSUE TITLE
Light output drops nearly half from 1.20.4 - 2021.8.2 with same yaml and HASS setting.

### ISSUE THREAD

**Issue by cooljimy84** [esphome/issues#2526]
### The problem

Turn the LED strip on full brightness with 1.20.4, take note of the brightness, upgrade to 2021.8.2 and it's no where near as bright, but does appear the same colour.

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.9.7

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

light

### Example YAML snippet

```yaml
esphome:
  name: esp5
  platform: ESP8266
  board: nodemcuv2

status_led:
  pin:
    number: GPIO2
    inverted: true

# Above the hallway door
wifi:
  ssid: 'WIFI'
  password: 'PASSWORD'
  fast_connect: true

mqtt:
  broker: '192.168.1.113'
  username: 'USERNAME'
  password: 'PASSWORD'
  reboot_timeout: 2min

# Enable logging
logger:
  level: INFO

ota:
  password: 'PASSWORD'

sensor:
  - platform: uptime
    name: ESP5 Uptime Sensor
    update_interval: 360s
  - platform: wifi_signal
    name: "WiFi Signal ESP5"
    update_interval: 360s

switch:
  - platform: restart
    name: "ESP5 Restart"

light:
  - platform: neopixelbus
    type: GRBW
    pin: GPIO3
    num_leds: 59
    name: "ESP5 LED Strip"
    id: mylight
    color_correct: [100%, 100%, 100%, 50%]
    default_transition_length: 0.5s
# This is the default gamma for ESP
    gamma_correct: 2.8
    effects:
      - random:
          name: Random Effect Fast
          transition_length: 0.1s
          update_interval: 0.5s
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 15
          width: 100
      - strobe:
          name: Flash Red
          colors:
            - state: True
              brightness: 85%
              red: 100%
              green: 0%
              blue: 0%
              white: 0%
              duration: 500ms
            - state: True
              brightness: 1%
              red: 1%
              green: 0%
              blue: 0%
              white: 0%
              duration: 500ms
      - strobe:
          name: Flash Green
          colors:
            - state: True
              brightness: 85%
              red: 0%
              green: 100%
              blue: 0%
              white: 0%
              duration: 500ms
            - state: True
              brightness: 1%
              red: 0%
              green: 1%
              blue: 0%
              white: 0%
              duration: 500ms
      - addressable_color_wipe:
          name: Color Wipe
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              white: 0%
              num_leds: 10
            - red: 0%
              green: 0%
              blue: 0%
              white: 1%
              num_leds: 15
            - red: 0%
              green: 0%
              blue: 100%
              white: 0%
              num_leds: 10
            - red: 0%
              green: 0%
              blue: 0%
              white: 1%
              num_leds: 15
            - red: 0%
              green: 100%
              blue: 0%
              white: 0%
              num_leds: 10
            - red: 0%
              green: 0%
              blue: 0%
              white: 1%
              num_leds: 15
          add_led_interval: 50ms
          reverse: False
      - addressable_color_wipe:
          name: XMAS2
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 0%
              green: 0%
              blue: 0%
              white: 0%
              num_leds: 10
            - red: 0%
              green: 100%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 0%
              green: 0%
              blue: 0%
              white: 0%
              num_leds: 10
          add_led_interval: 100ms
          reverse: False
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 80%
              blue: 0%
              white: 0%
              duration: 500ms
            - state: False
              duration: 250ms
              white: 0%
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              white: 0%
              duration: 500ms
            - state: False
              duration: 250ms
              white: 0%
            - state: True
              brightness: 100%
              red: 80%
              green: 0%
              blue: 100%
              white: 0%
              duration: 500ms
      - lambda:
          name: Throb
          update_interval: 2s
          lambda: |-
            static int state = 0;
            auto call = id(mylight).turn_on();
            // Transtion of 2000ms = 2s
            call.set_transition_length(2000);
            if (state == 0) {
              call.set_brightness(1.0);
            } else {
              call.set_brightness(0.01);
            }
            call.perform();
            state += 1;
            if (state == 2)
              state = 0;
      - random:
          name: 'Random Fast'
          update_interval: 1.0s
          transition_length: 0.5s
      - addressable_scan:
          name: Scan Effect
          move_interval: 15ms
```
