### ISSUE TITLE
Midea AC can not change FAN speed  in  ESPHome 2021.9.2 

### ISSUE THREAD

**Issue by all2beok** [esphome/issues#2528]
### The problem

After updating to version 2021.9.2 from 2021.8.2  changing fan speed stopped working on Pioneer WYS 21 seer mini split, but its still working on Pioneer WYS 19 seer mini splits. I have two Pioneer WYS 19 seers AC’s and one WYS 21 SEER AC, the dongle connects via WiFi card with USB jack with ‘cuts’ as on some photos. (https://community-assets.home-assistant.io/original/3X/0/0/00692dcfff4c39b5842f1d14447e8c8363e8a771.jpeg) After the update 19 seers mini splits work just fine, but I cant change fan speed on 21 seer anymore, tried re-flashing with different options, changed dongles - no go. The 21 seer AC has the same board but I think it has a bit different functionality then 19 ones. When I check 21 seer AC logs I see a warning saying that it cant automatically get capabilities, but not sure if its related to the issue with changing FAN speed. I’m wondering if anybody had similar issues after update. Thank you!

Update: Interesting enough, sometimes, not sure what the logic, it allows to set FAN speed to high, but never to low or medium, it goes back to auto after 2 sec

[midea:113]: Failed to get 0xB5 capabilities report. Suggest to disable it in config and manually set your appliance options
(I tried turning off autoconf - didnt help)

When changing fan speed on 19 seer ACs I see in the log SET_STATUS request being sent but I dont see it for 21 seer AC:

[12:43:44][D][climate:009]: ‘Bedoom AC’ - Setting
[12:43:44][D][climate:022]: Fan: HIGH
[12:43:44][D][AirConditioner:105]: Enqueuing a priority SET_STATUS(0x40) request…

When I change fan speed on 21 seer AC it seems its not sending this command:

[13:50:58][D][climate:009]: ‘Living Room AC’ - Setting
[13:50:58][D][climate:022]: Fan: HIGH
[13:50:58][D][AirConditioner:178]: Enqueuing a GET_STATUS(0x41) request…
[13:50:58][D][ApplianceBase:173]: Enqueuing the request…
[13:50:58][D][ApplianceBase:075]: Getting and sending a request from the queue…

Update: I flashed manually original firmware created in version 8.2 and turns out it can not change fan speed to low and medium, but works fine when I change it to HIGH now I'm not sure if it was working before I've updated ESPHome and supervisor versions or could it be because I use old firmware with latest ESPhome and supervisor? (I dont think so) See additional log info in log section.

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.9.6

### What platform are you using?

ESP8266

### Board

ESP8266 ESP01

### Component causing the issue

Midea

### Example YAML snippet

```yaml
esphome:
  name: living-room-ac
  platform: ESP8266
  board: esp01_1m

# Enable Home Assistant API
api:

ota:
  password: "xxx"

wifi:
  ssid: "xxx"
  password: "xxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living Room-AC"
    password: ""

captive_portal:

# Disable logging over UART (required)
logger:
  baud_rate: 0
  
# UART settings for Midea dongle (required)
uart:
  tx_pin: 1   # hardware dependant
  rx_pin: 3   # hardware dependant
  baud_rate: 9600


# Main settings
climate:
  - platform: midea
    name: "Living Room AC"    # Use a unique name.
    beeper: false        # Beep on commands.
    visual:
      min_temperature: 18 °C
      max_temperature: 30 °C
      temperature_step: 0.5 °C
    period: 1s                  # Optional
    timeout: 2s                 # Optional
    num_attempts: 3             # Optional

    supported_modes:            # All capabilities in this section detected by autoconf.
      - FAN_ONLY                # This capability is always used.
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    custom_fan_modes:
      - SILENT
      - TURBO
    outdoor_temperature:
     name: "Temp"
```

### Anything in the logs that might be useful for us?

```txt
When changing fan speed on 19 seer ACs I see in the log SET_STATUS request being sent but I dont see it for 21 seer AC:

[12:43:44][D][climate:009]: ‘Bedoom AC’ - Setting
[12:43:44][D][climate:022]: Fan: HIGH
[12:43:44][D][AirConditioner:105]: Enqueuing a priority SET_STATUS(0x40) request…

When I change fan speed on 21 seer AC it seems its not sending this command, but sometimes after several attempts it changes speed to HIGH, looks like some kind of request/response issue.

[13:50:58][D][climate:009]: ‘Living Room AC’ - Setting
[13:50:58][D][climate:022]: Fan: HIGH
[13:50:58][D][AirConditioner:178]: Enqueuing a GET_STATUS(0x41) request…
[13:50:58][D][ApplianceBase:173]: Enqueuing the request…
[13:50:58][D][ApplianceBase:075]: Getting and sending a request from the queue…
```
With old firmware something similar is happening when changing speed to low it sends state request to AUTO:

[11:30:37][D][midea_ac:034]: RX: query frame
[11:30:37][D][climate:009]: 'Living Room AC' - Setting
[11:30:37][D][climate:022]:   Fan: LOW
[11:30:37][D][midea_ac:069]: TX: control
[11:30:37][D][midea_dongle:094]: TX: AA 22 AC 00 00 00 00 00 03 02 40 01 57 28 7F 7F 00 00 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 8D DE 
[11:30:38][D][midea_dongle:029]: RX: AA 1E AC 00 00 00 00 00 00 02 C0 01 57 1E 7F 7F 00 00 00 00 04 65 6B 00 00 00 00 00 00 F8 34 
[11:30:38][D][midea_ac:031]: RX: control frame
[11:30:38][D][climate:373]: 'Living Room AC' - Sending state:
[11:30:38][D][climate:376]:   Mode: COOL
[11:30:38][D][climate:381]:   Fan Mode: AUTO
[11:30:38][D][climate:387]:   Preset: NONE
[11:30:38][D][climate:393]:   Swing Mode: OFF
[11:30:38][D][climate:396]:   Current Temperature: 25.50°C
[11:30:38][D][climate:402]:   Target Temperature: 23.50°C
[11:30:38][D][sensor:131]: 'Hum': Sending state 120.00000 % with 0 decimals of accuracy
[11:30:38][D][midea_ac:072]: TX: query
[11:30:38][D][midea_dongle:094]: TX: AA 21 AC 00 00 00 00 00 00 03 41 81 00 FF 03 FF 00 02 00 00 00 00 00 00 00 00 00 00 00 00 03 00 37 31 
[11:30:39][D][midea_dongle:029]: RX: AA 1E AC 00 00 00 00 00 00 03 C0 01 57 1E 7F 7F 00 00 00 00 04 65 6B 00 00 00 00 00 00 F8 33 
[11:30:39][D][midea_ac:034]: RX: query frame
[11:30:39][D][midea_ac:072]: TX: query
