### ISSUE TITLE
logger: UART_NUM_2 was not declared in this scope

### ISSUE THREAD

**Issue by rsumner** [esphome/issues#2529]
### The problem

Running a compile for a ESP32C3 board fails due to undeclared references to UART_NUM_2 in the logger component:

```
src/esphome/components/logger/logger.cpp: In member function 'void esphome::logger::Logger::pre_setup()':
src/esphome/components/logger/logger.cpp:176:21: error: 'UART_NUM_2' was not declared in this scope
         uart_num_ = UART_NUM_2;
                     ^~~~~~~~~~
src/esphome/components/logger/logger.cpp:176:21: note: suggested alternative: 'UART_NUM_0'
         uart_num_ = UART_NUM_2;
                     ^~~~~~~~~~
                     UART_NUM_0
*** [.pioenvs/irsensor1/src/esphome/components/logger/logger.o] Error 1
```

### Which version of ESPHome has the issue?

2021.XX.X-dev

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

ESP32-C3-DevKitM-1

### Component causing the issue

logger

### Example YAML snippet

```yaml
esphome:
  name: irsensor1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
  variant: ESP32C3

logger:
  level: DEBUG

api:

ota:

wifi:
...

remote_receiver:
  # Pin Name on Board: 18
  pin: 
    number: GPIO18
    inverted: True
    mode: INPUT_PULLUP
  dump: raw
  idle: 25ms
```

### Anything in the logs that might be useful for us?

Even if I set `baud_rate: 0` in the logging section to disable UART logging, it still fails to compile.
