### ISSUE TITLE
FastLED crazy flickering

### ISSUE THREAD

**Issue by Diaoul** [esphome/issues#253]
I have a custom made FastLED ESP8266 device which connects to my MQTT and integrates well with HomeAssistant using MQTT JSON Template component. I wanted something easier for my ESP8266 fleet so I tried ESPHome.
I had first some trouble uploading through OTA from Home Assistant so I switch to my PC and I'll sort this one out later.
However, the first thing that I immediately notice is that the Addressable Rainbow Effect flickers badly.
It does it on all addressable effects, it's more or less visible depending on the number of leds on at this moment.
I know clockless is a PITA and very sensitive but still. Is this a known limitation or a bug that can be solved?

**Operating environment/Installation (Hass.io/Docker/pip/etc.):** pip

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP8266

**Affected component:** FastLED Light

**Description of problem:** Addressable Rainbow Effect is flickering

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: dht
    pin: GPIO2
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

light:
  - platform: fastled_clockless
    chipset: NEOPIXEL
    pin: GPIO14
    num_leds: 60
    name: "Light"
    effects:
      - addressable_rainbow:
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
