### ISSUE TITLE
fastled not reporting correct status to *.is_On or *.is_OFF

### ISSUE THREAD

**Issue by tsaG1337** [esphome/issues#2533]
### The problem

I tried switching the LED Stripe chamber_light (which is of type fastled_clockless) but it looks like you can not read the state using light.is_off / on. When I switched to LightButton_LED which is of type RGB it works. If I use chamber_light as condition, it always reports "LEDs Off".

### Which version of ESPHome has the issue?

2021.8.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

custom

### Component causing the issue

fastled

### Example YAML snippet

```yaml
- platform: gpio #Light Button
    pin:
      number: GPIO15
      inverted: true
    id: lightButton
    on_click:
      - min_length: 100ms
        max_length: 500ms
        then:
          - if:
              condition: 
                - light.is_off: LightButton_LED
              then:
                - logger.log: "LED ON"
                - light.turn_on: chamber_light
                - light.turn_on: LightButton_LED
              else:
                - logger.log: "LEDs Off"
                - light.turn_off: chamber_light
                - light.turn_off: LightButton_LED
```
