### ISSUE TITLE
Unable to set value 0 (zero) to internal state of the rotary encoder at startup

### ISSUE THREAD

**Issue by MrC0nst** [esphome/issues#2535]
### The problem

I am unable to set value 0 (zero) to rotary encoder variable at the begining. This code is working fine with any other values but with 0 (zero) i am facing with "Unknown":
![image](https://user-images.githubusercontent.com/75075223/136707894-1194a532-867c-4ee7-8faf-1e8273d60d03.png)

`esphome:
  name: rotary_test
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 600
    then:
      - sensor.rotary_encoder.set_value:
          id: rotary1
          value: 0
sensor:
  - platform: rotary_encoder
    id: rotary1
    name: Rotary Encoder
    pin_a:
      number: D1
    pin_b:
      number: D2`

But if i set value, for example 1 and then set 0 this will work
![image](https://user-images.githubusercontent.com/75075223/136707950-7113f642-5fe3-4276-964f-b3dd6583601d.png)

`  on_boot:
    priority: 600
    then:
      - sensor.rotary_encoder.set_value:
          id: rotary1
          value: 1
      - sensor.rotary_encoder.set_value:
          id: rotary1
          value: 0`

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.10.2

### What platform are you using?

ESP8266

### Board

wemos d1 mini v3

### Component causing the issue

Rotary Encoder Sensor

### Example YAML snippet

```yaml
esphome:
  name: rotary_test
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 600
    then:
      - sensor.rotary_encoder.set_value:
          id: rotary1
          value: 0
sensor:
  - platform: rotary_encoder
    id: rotary1
    name: Rotary Encoder
    pin_a:
      number: D1
    pin_b:
      number: D2
```
