### ISSUE TITLE
Problem with Grow Fingerprint and Wemos D1 Mini when using aurora_led_control

### ISSUE THREAD

**Issue by nicx** [esphome/issues#2542]
### The problem

I have a very strange problem: I am using a Wemos D1 Mini with a capacitive grow fingerprint reader (model R503). Its working as expected when not using aurora_led_control, so I can read and enroll fingerprints and get the correct "answer" if a fingerprint is authorized or not.

When adding any "fingerprint_grow.aura_led_control" function to the yaml I get a weird behavior: the recognition works correctly until the led lights up for the first time (In my yaml example its for the first unauthorized finger). The LED flashes correctly in red, but after that, all fingers are recognized as authorized, even the formerly unauthorized fingers.

Does anyone have any idea what this could be?

### Which version of ESPHome has the issue?

2021.9.3 

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

NA

### What platform are you using?

ESP8266

### Board

Wemos d1 Mini

### Component causing the issue

Grow Fingerprint

### Example YAML snippet

```yaml
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

  on_boot:
    priority: -10
    then:
    - wait_until:
        api.connected:
    - logger.log: API is connected!

# Enable logging
logger:
  # level: VERY_VERBOSE
  # level: VERBOSE
  #  baud_rate: 0

# Enable OTA upgrade
ota:
  password: ""

# Sensors
sensor:
  - platform: fingerprint_grow
    fingerprint_count:
      name: "Fingerprint Count"
    last_finger_id:
      name: "Fingerprint Last Finger ID"
    last_confidence:
      name: "Fingerprint Last Confidence"
    status:
      name: "Fingerprint Status"
    capacity:
      name: "Fingerprint Capacity"
    security_level:
      name: "Fingerprint Security Level"

text_sensor:
  - platform: template
    id: fingerprint_state
    name: "Fingerprint State"

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"


# Hardware Sensors
uart:
  rx_pin: D5 #GPIO14
  tx_pin: D6 #GPIO12
  baud_rate: 57600

fingerprint_grow:
  sensing_pin: D7 #GPIO13
  on_finger_scan_matched:
    - homeassistant.event:
        event: esphome.test_node_finger_scan_matched
        data:
          finger_id: !lambda 'return finger_id;'
          confidence: !lambda 'return confidence;'
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Authorized finger"
  on_finger_scan_unmatched:
    - homeassistant.event:
        event: esphome.test_node_finger_scan_unmatched
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Unauthorized finger"
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 2
  on_enrollment_scan:
    - homeassistant.event:
        event: esphome.test_node_enrollment_scan
        data:
          finger_id: !lambda 'return finger_id;'
          scan_num: !lambda 'return scan_num;'
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Finger scanned"
  on_enrollment_done:
    - homeassistant.event:
        event: esphome.test_node_enrollment_done
        data:
          finger_id: !lambda 'return finger_id;'
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Enrolled fingerprint"
  on_enrollment_failed:
    - homeassistant.event:
        event: esphome.test_node_enrollment_failed
        data:
          finger_id: !lambda 'return finger_id;'
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Failed to enroll fingerprint"

# Home Assistant API
api:
  services:

  # Fingerprint services
  - service: fingerprint_enroll
    variables:
      finger_id: int
      num_scans: int
    then:
      - fingerprint_grow.enroll:
          finger_id: !lambda 'return finger_id;'
          num_scans: !lambda 'return num_scans;'
  - service: fingerprint_cancel_enroll
    then:
      - fingerprint_grow.cancel_enroll:
  - service: fingerprin_delete
    variables:
      finger_id: int
    then:
      - fingerprint_grow.delete:
          finger_id: !lambda 'return finger_id;'
  - service: fingerprint_delete_all
    then:
      - fingerprint_grow.delete_all:
```

### Anything in the logs that might be useful for us?

```txt
[14:43:25][D][fingerprint_grow:092]: Scan and match
[14:43:25][D][fingerprint_grow:123]: Getting image 1
[14:43:25][D][fingerprint_grow:144]: Processing image 1
[14:43:25][I][fingerprint_grow:148]: Processed image 1
[14:43:25][D][fingerprint_grow:114]: Fingerprint not matched to any saved slots
[14:43:25][D][text_sensor:015]: 'Fingerprint State': Sending state 'Unauthorized finger'
[14:43:25][D][fingerprint_grow:304]: Setting Aura LED
[14:43:25][D][fingerprint_grow:308]: Aura LED set
[14:43:25][D][fingerprint_grow:123]: Getting image 1
[14:43:26][D][fingerprint_grow:144]: Processing image 1
[14:43:26][D][fingerprint_grow:027]: Finger removed
[14:43:26][D][fingerprint_grow:092]: Scan and match
[14:43:26][D][fingerprint_grow:123]: Getting image 1
[14:43:26][D][fingerprint_grow:092]: Scan and match
[14:43:26][D][fingerprint_grow:123]: Getting image 1
[14:43:26][D][fingerprint_grow:133]: No finger
[14:43:27][D][fingerprint_grow:092]: Scan and match
[14:43:27][D][fingerprint_grow:123]: Getting image 1
[14:43:27][D][fingerprint_grow:133]: No finger
[14:43:27][D][fingerprint_grow:092]: Scan and match
[14:43:27][D][fingerprint_grow:123]: Getting image 1
[14:43:27][D][fingerprint_grow:133]: No finger
[14:43:28][D][fingerprint_grow:092]: Scan and match
[14:43:28][D][fingerprint_grow:123]: Getting image 1
[14:43:28][D][fingerprint_grow:133]: No finger
[14:43:28][D][fingerprint_grow:092]: Scan and match
[14:43:28][D][fingerprint_grow:123]: Getting image 1
[14:43:28][D][fingerprint_grow:133]: No finger
[14:43:29][D][fingerprint_grow:092]: Scan and match
[14:43:29][D][fingerprint_grow:123]: Getting image 1
[14:43:29][D][fingerprint_grow:144]: Processing image 1
[14:43:29][I][fingerprint_grow:148]: Processed image 1
[14:43:29][D][fingerprint_grow:101]: Fingerprint matched
[14:43:29][D][sensor:121]: 'Fingerprint Last Finger ID': Sending state 10.00000  with 0 decimals of accuracy
[14:43:29][D][sensor:121]: 'Fingerprint Last Confidence': Sending state 0.00000  with 0 decimals of accuracy
[14:43:29][D][text_sensor:015]: 'Fingerprint State': Sending state 'Authorized finger'
[14:43:29][D][fingerprint_grow:123]: Getting image 1
[14:43:30][D][fingerprint_grow:123]: Getting image 1
[14:43:30][D][fingerprint_grow:133]: No finger
[14:43:30][D][fingerprint_grow:027]: Finger removed
[14:43:30][D][fingerprint_grow:092]: Scan and match
[14:43:30][D][fingerprint_grow:123]: Getting image 1
[14:43:30][D][fingerprint_grow:133]: No finger
[14:43:30][D][text_sensor:015]: 'Fingerprint State': Sending state 'Authorized finger'
[14:43:31][D][fingerprint_grow:092]: Scan and match
[14:43:31][D][fingerprint_grow:123]: Getting image 1
[14:43:31][D][fingerprint_grow:133]: No finger
[14:43:31][D][fingerprint_grow:092]: Scan and match
[14:43:31][D][fingerprint_grow:123]: Getting image 1
[14:43:31][D][fingerprint_grow:133]: No finger
[14:43:32][D][fingerprint_grow:092]: Scan and match
[14:43:32][D][fingerprint_grow:123]: Getting image 1
[14:43:32][D][fingerprint_grow:144]: Processing image 1
[14:43:32][I][fingerprint_grow:148]: Processed image 1
[14:43:32][D][fingerprint_grow:101]: Fingerprint matched
[14:43:32][D][sensor:121]: 'Fingerprint Last Finger ID': Sending state 10.00000  with 0 decimals of accuracy
[14:43:32][D][sensor:121]: 'Fingerprint Last Confidence': Sending state 0.00000  with 0 decimals of accuracy
[14:43:32][D][text_sensor:015]: 'Fingerprint State': Sending state 'Authorized finger'
[14:43:32][D][fingerprint_grow:123]: Getting image 1
[14:43:33][D][fingerprint_grow:123]: Getting image 1
[14:43:33][D][fingerprint_grow:133]: No finger
[14:43:33][D][fingerprint_grow:027]: Finger removed
[14:43:33][D][fingerprint_grow:092]: Scan and match
[14:43:33][D][fingerprint_grow:123]: Getting image 1
[14:43:33][D][fingerprint_grow:133]: No finger
[14:43:34][D][fingerprint_grow:092]: Scan and match
[14:43:34][D][fingerprint_grow:123]: Getting image 1
[14:43:34][D][fingerprint_grow:133]: No finger
[14:43:34][D][fingerprint_grow:092]: Scan and match
[14:43:34][D][fingerprint_grow:123]: Getting image 1
[14:43:34][D][fingerprint_grow:133]: No finger
```

**Comment by loongyh** [comment]
The matched fingerprints all have 0 confidence. Can you use the [sfgdemo](https://learn.adafruit.com/adafruit-optical-fingerprint-sensor/downloads) tool from adafruit to check your reader settings?

**Comment by nicx** [comment]
@loongyh I will buy another reader and test ist with that. Thanks for your help so far! :)

**Comment by loongyh** [comment]
All the best :)

**Comment by jirkakarasek** [comment]
I have the same problem, you have a solution ?

**Comment by nicx** [comment]
no, I am still waiting for the new fingerprint sensor to test if its a hardware problem or not.

**Comment by nicx** [comment]
@jirkakarasek which hardware setup do you use? maybe we can find out similarities if the fingerprint itself is not defect.

**Comment by nicx** [comment]
@loongyh in the meantime I got my replacement sensor, but the behavior is the same :(

With the help of other guys in the world of internet I found a working solution with the Arduino IDE using a modified library which supports the Aurora LED: https://github.com/MarcBoettinger/Adafruit_Fingerprint_Sensor_Library/tree/master/Adafruit_Fingerprint_Sensor_Library

The original problem is the same here, i.e. the sensor does not work correctly after the first activation of the LED, but as soon as the function "finger.begin(57600)" is inserted in the sketch directly after the LED activation, the sensor reacts as desired without errors.

In the Sketch it looks like this:
```
  // send command to turn on R503 led
  finger.led_control(1,100,2,3); // code(1-6),speed(1-255),color(1-R/2-B/3_P),time(1-255)
  finger.begin(57600);
```

Now this workaround (which is perhaps simply not a workaround but the correct control of the sensor) would only have to make its way into ESPHome.

**Comment by loongyh** [comment]
Hey @nicx, thanks for spending the time to investigate into this issue 👍

> With the help of other guys in the world of internet I found a working solution with the Arduino IDE using a modified Adafruit library which supports the Aurora LED:

The orginal Adafruit FP Lib [already has support](https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library/blob/0a64b4db9b7b03c17280a9c2144f1f86099d8953/Adafruit_Fingerprint.cpp#L352) for Aura LED:
`uint8_t Adafruit_Fingerprint::LEDcontrol(uint8_t control, uint8_t speed, uint8_t coloridx, uint8_t count)`

Can you see if you can reproduce the fix with your sketch with the original Adafruit FP Lib?

> Now this workaround (which is perhaps simply not a workaround but the correct control of the sensor) would only have to make its way into ESPHome.

I don't think this is the "correct control" as `finger.begin(57600)` invokes arduino's [Serial.begin(speed)](https://www.arduino.cc/reference/en/language/functions/communication/serial/begin/) function, which initializes and sets the baudrate of the serial bus. It's [not supposed to be invoked multiple times](https://forum.arduino.cc/t/can-serial-begin-be-initiated-multiple-times/441531), at least without first invoking `Serial.end()`. I suspect whatever bytes are transmitted when invoking `Serial.begin()` causes the reader to reset or something, thereby seemingly fixing the issue. If you can find out what is the exact sequence of bytes, I can put them in at the end of [`aura_led_control()`](https://github.com/esphome/esphome/blob/dev/esphome/components/fingerprint_grow/fingerprint_grow.cpp#L298).

I actually have a batch of R503s that has the opposite problem, all fingers are recognized as unauthorized after a few minutes of operation. I'll investigate if this issue is due to the use of Aura LED.

**Comment by nicx** [comment]
> Hey @nicx, thanks for spending the time to investigate into this issue 👍

@loongyh you are very welcome :)

> Can you see if you can reproduce the fix with your sketch with the original Adafruit FP Lib?

I just tried it: yes its reproducable regarding the LED control. Without workaround, the reader is not working correctly. With workaround the reader ist not "crashing" anymore. But I'll have another problem with the original library: The one and only saved fingerprint is never matched?! Don't know why...

And as a sidenote: In the setup routine I use the "finger.getTemplateCount();" function. If the originally problem exists I always get 10 templates as answer, otherwise I get the exact count of saved fingerprints on the reader (in my case "1").

> I don't think this is the "correct control" as `finger.begin(57600)` invokes arduino's [`Serial.begin(speed)`](https://www.arduino.cc/reference/en/language/functions/communication/serial/begin/) function, which initializes and sets the baudrate of the serial bus. It's [not supposed to be invoked multiple times](https://forum.arduino.cc/t/can-serial-begin-be-initiated-multiple-times/441531), at least without first invoking `Serial.end()`. I suspect whatever bytes are transmitted when invoking `Serial.begin()` causes the reader to reset or something, thereby seemingly fixing the issue. If you can find out what is the exact sequence of bytes, I can put them in at the end of [`aura_led_control()`](https://github.com/esphome/esphome/blob/dev/esphome/components/fingerprint_grow/fingerprint_grow.cpp#L298).

It would be great if you could help me: What could I exactly do to find out the sequence of bytes? I don't have any idea ;)

> I actually have a batch of R503s that has the opposite problem, all fingers are recognized as unauthorized after a few minutes of operation. I'll investigate if this issue is due to the use of Aura LED.

Hm, sound this could really be the same reason. I'm curious to see what you find out here. ;)

**Comment by nicx** [comment]
and just as a quick hack: is it possible to reset the reader in any similar way using ESPHome in the "on_finger_scan_matched" section?

**Comment by OnFreund** [comment]
Since this is working for most people (I believe), I would suggest adding a separate `reset()` function, rather than making it part of `aura_led_control()`

**Comment by nicx** [comment]
@OnFreund great idea, could you implement it or what is needed to get this into esphome?

**Comment by OnFreund** [comment]
@nicx not really. I have no idea how to reset the device, I'm just saying that if that functionality is added, it shouldn't be called automatically, because most people aren't experiencing this problem.

**Comment by cRemE-fReSh** [comment]
Hi all,
I have the same issue here. Using the Aura LED always results in "ID10.0000" as result for every finger :-(

Has anybody found another solution than to reset the device? From my point of view, resetting is not a proper solution as is could result in "open doors for everybody" if something fails...

**Comment by nicx** [comment]
@cRemE-fReSh unfortunately currently its the only solution I know. And its a pity that I have to use Arduino instead of ESPhome to get this workaround working. I dint find any possibility to "reset" the reader via ESPhome.

@loongyh any idea how I could assist you in finding a "byte sequence" which you could put at the end to aura_led_control() function? Maybe we could try the "Soft Reset" SoftRst (0x3D) byte sequence documented here: https://cdn-shop.adafruit.com/product-files/4651/4651_R503+fingerprint+module+user+manual.pdf
This seems promising ;)

**Comment by loongyh** [comment]
Actually the resetting part was just my conjecture, I'm unsure what's the exact root cause of this so I could be wrong. To find out the byte sequence, you need visibility into the raw bytes that are sent/rcved between the arduino and r503. if you're using arduino ide there's a built-in serial monitor, see if you can try to get the bytes displayed there. alternatively if you have a usb-ttl adapter lying around u can hook it up to monitor the transmissions using a serial terminal program.

**Comment by nicx** [comment]
thanks @loongyh, but what do you think about my idea just to add the documented "Soft Reset" byte sequence? I think this could be a better solution instead of the reinitializing of the serial bus.
Maybe you just could add this "Soft reset" at the end of the aurora function and I can test the behavior?

**Comment by loongyh** [comment]
Done, add these to your yaml config:
```yaml
external_components:
  - source: github://loongyh/esphome@rxxx-auraled-patch
    components: [ fingerprint_grow ]

fingerprint_grow:
  reset: true
```
Let me know how it goes.
