### ISSUE TITLE
power_supply in light component is not waiting for the power supply to start up

### ISSUE THREAD

**Issue by djexit** [esphome/issues#2543]
### The problem

I used the power_supply component in the light component. The power supply is ATX. The power supply needs about 500ms to start up, so I set the "enable_time" parameter to 500ms. The transition time is set to 1s by default in the "light" component. It seems that after turning on the light, the transition time passes first and then the power supply is started, which makes no sense, because (which is also described in the documentation for the power_supply component) the power supply should be turned on first, and only after the time declared in "enable_time" should start the light with the transition time in mind.

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.4

### What platform are you using?

ESP32

### Board

ESP-WROOM-32

### Component causing the issue

light or power_supply

### Example YAML snippet

```yaml
esp32_touch:
  setup_mode: false
  iir_filter: 10ms

binary_sensor:
  - platform: esp32_touch
    name: "ESP32 Touch Pad GPIO27"
    pin: GPIO4
    threshold: 600
    on_press:
      - light.toggle: ledy
      
      
power_supply:
  - id: atx
    enable_time: 500ms
    pin: 
      number: GPIO15
      inverted: true
    
    
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO23
    num_leds: 300
    rgb_order: GRB
    name: "FastLED WS2811 Light"
    id: ledy
    power_supply: atx
```

### Additional information

To reproduce this error correctly, you can set the default_transition_time long for the light component and the long enable_time for the power_supply component, e.g. 5s.
