### ISSUE TITLE
esptool.py fails with esp32-s2-saola-1

### ISSUE THREAD

**Issue by roger-** [esphome/issues#2545]
### The problem

esptool tries to flash my esp32-s2-saola-1 with with chip=esp32. Works if I switch to esp32s2 and manually flash.

### Which version of ESPHome has the issue?

Dev: 6bbb5e9b56bb71353aac609cea7fe325cd9b4c60

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32-IDF

### Board

esp32-s2-saola-1 

### Component causing the issue

flashing

### Example YAML snippet

```yaml
esphome:
  name: xxx

esp32:
  board: esp32-s2-saola-1 
  framework:
    type: esp-idf
```
