### ISSUE TITLE
Sonoff Dual R3 with ESPHome firmware continuously freezes 

### ISSUE THREAD

**Issue by roscsa** [esphome/issues#2548]
### The problem

I bought some new Sonoff dual r3 wifi switch, and changed the firmware on these devices to EspHome. 
However these usually freeze. 
When a device freezes it doesn't respond to Ethernet packets and doesn't respond to the built in inputs too. 
I used a lot of devices with ESP32 (these are developed by myself) and those are working fine. 
The ESP8266 based sonoff devices are also working fine.
Do you have any experiences with these devices? Or do you have any suggestion to solve the problem?
Thanks in advance!

### Which version of ESPHome has the issue?

2021.09.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.4

### What platform are you using?

ESP32

### Board

Sonoff dual r3

### Example YAML snippet

```yaml
esphome:
  name: node-dual-01
  platform: ESP32
  board: esp-wrover-kit

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxxx"

ota:
  password: "xxxx"

wifi:
  ssid: "xxxx"
  password: "xxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Node-Dual-01 Fallback Hotspot"
    password: "xxxx"

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "node02 reset button"
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: True
    name: "IN1"
    filters:
      - delayed_on: 20ms
    on_press:
      then:
        - light.toggle: _light2
    on_release:
      then:
        - light.toggle: _light2
  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: True
    name: "IN2"
    filters:
      - delayed_on: 20ms
    on_press:
      then:
        - light.toggle: _light1

light:
  - platform: binary
    name: "living room"
    output: relay1
    id: _light1
  - platform: binary
    name: "dining room"
    output: relay2
    id: _light2

output:
  - platform: gpio
    pin: GPIO27
    id: relay1
  - platform: gpio
    pin: GPIO14
    id: relay2

status_led:
  pin:
    number: GPIO13
    inverted: yes
```
