### ISSUE TITLE
http_request.post - HTTP Request failed

### ISSUE THREAD

**Issue by laszlojakab** [esphome/issues#2549]
### The problem

Hi, I have two Sonoff T1 light switch. They were functioned previously as a two way switch. If I turned on one of them the other turned on also and if I turned off one of them then the other also turned off. My HA installation wasn't so stable so I didn't use HA automation to sync switches, I implemented synchronization in ESPHome. I enabled web_server component on both switches and sent a turn_on/turn_off command on REST API to the other swich if a button pressed. It worked for a while. I updated ESPHome to 2021.9.2 (and now to 2021.9.3) and my solution not working anymore. I have attached a simplified version of my yaml config. It posts a turn_on command to the other switch but it fails. I tried to call `http://192.168.30.19/light/diningroom_led_light/turn_on` url from a REST API tester application and it returns HTTP 200 in about 30ms and the light turns on. So there should be something on the calling side not with the REST API.

I also have to mention that I have a custom lightoutput component which also not working anymore. It uses AsyncClient from ESPAsyncTCP to communicate with a led controller. I don't know if it is related to this problem because there were stability issues with the led controller itself but I can send TCP commands from my PC to the led controller and it is working. If I use ESPHome on my Sonoff T1s them it is not working anymore (which worked previously in 95% of the times).

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Sonoff T1

### Component causing the issue

http_request

### Example YAML snippet

```yaml
esphome:
  name: diningroom_alt_light_switch
  platform: ESP8266
  board: esp01_1m
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.30.23
    gateway: 192.168.30.1
    subnet: 255.255.255.0

  ap:
    ssid: Diningroom alternative
    password: !secret hotspot_wifi_password
    
  domain: .local-not

captive_portal:

logger:

ota:
  password: !secret ota_password

http_request:
  useragent: esphome/device
  timeout: 3s
  
api:
  password: !secret diningroom_alt_light_switch_password

web_server:
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    id: led_button
    on_click:
      then:
          http_request.post:
            url: http://192.168.30.19/light/diningroom_led_light/turn_on
```

### Anything in the logs that might be useful for us?

```txt
[08:27:32][W][http_request:062]: HTTP Request failed; URL: http://192.168.30.19/light/diningroom_led_light/turn_on; Error: connection failed
```
