### ISSUE TITLE
PN532 does not read tags when logging is set to VERY_VERBOSE

### ISSUE THREAD

**Issue by nmaggioni** [esphome/issues#2552]
### The problem

NFC tags are completely ignored by the `pn532` component when the logging level is set to `VERY_VERBOSE`. All levels above that work as expected.

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

pn532

### Example YAML snippet

```yaml
esphome:
  name: "<DEVICE_NAME>"
  platform: ESP8266
  board: d1_mini

logger:
  level: VERY_VERBOSE

spi:
  miso_pin: D8
  mosi_pin: D5
  clk_pin: D7

pn532_spi:
  cs_pin: D6
  update_interval: 500ms

binary_sensor:
  - platform: pn532
    uid: XX-XX-XX-XX-XX-XX-XX
    name: "<TAG_NAME>"
```

### Anything in the logs that might be useful for us?

```txt
No messages from the `pn532` or `spi` components except the first initialization ones.
```
