### ISSUE TITLE
NodeMCUv2 + sensor dht (SI7021) problem since last uodate

### ISSUE THREAD

**Issue by jcg747** [esphome/issues#2553]
### The problem

Hello,
A while ago, I have built four temp/hum sensor based on a nodeMCU v2 and a Sonoff SI7021 ( with a compatible display) 

Everything was working nicely both on the local display and under HomeAssistant. until the latest ESPhome 2021.9.3 update. Since then, 3 on the 4 have stopped working properly ( no more temp/hum) with the following partial log :

[17:03:12][C][captive_portal:148]: Captive Portal:
[17:03:12][C][ota:029]: Over-The-Air Updates:
[17:03:12][C][ota:030]:   Address: 192.168.10.64:8266
[17:03:12][C][ota:032]:   Using Password.
[17:03:12][C][api:135]: API Server:
[17:03:12][C][api:136]:   Address: 192.168.10.64:6053
[17:03:12][C][api:140]:   Using noise encryption: NO

**[17:03:22][W][dht:167]: Falling edge for bit 40 failed!
[17:03:22][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number).**

[17:03:22][D][sensor:121]: 'SenseNode1 Temp': Sending state nan °C with 1 decimals of accuracy
[17:03:22][D][sensor:121]: 'SenseNode1 Humidity': Sending state nan % with 0 decimals of accuracy

Curiously all 4 are absolutely identical (I tripple checked)

I'm a newcomer on Domotic so I apologize in advance if it look's obvious for more experienced user.
I'm also new to Github, I would appreciate any help to get it sorted
Best regards 
Jean Claude

### Which version of ESPHome has the issue?

20219.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2021.10.5 / Supervisor 2021.10.0

### What platform are you using?

ESP32

### Board

NodeMCU v2

### Component causing the issue

Sonof SI7021

### Example YAML snippet

```yaml
name: sensor_node_1
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "JCG_2G"
  password: "Boeing747-400a"
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.10.64
    gateway: 192.168.10.1
    subnet: 255.255.255.0
    dns1: 192.168.10.1
    dns2: 192.168.10.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor Node 1 Fallback Hotspot"
    password: "xalXOJV4SB2T"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "Boeing747-400"

ota:
  password: "Boeing747-400"

time:
  - platform: homeassistant
    id: esptime
    
sensor:
  - platform: dht
    pin: D4
    model: SI7021
    temperature:
      name: "SenseNode1 Temp"
      id: SenseNode1_Temp 
    humidity:
      name: "SenseNode1 Humidity"
      id: SenseNode1_Hum
    update_interval: 30s

font:
  - file: 'OpenSans-Regular.ttf'
    id: font1
    size: 12
  - file: 'arial.ttf'
    id: font2
    size: 13
    
i2c:
  sda: D2
  scl: D1
  scan: False
```
