### ISSUE TITLE
BME680 BSEC - Wemos D1 - ESPHome 

### ISSUE THREAD

**Issue by SHHA24** [esphome/issues#2555]
### The problem

Hi running the ESPHome config for the BME680 with the BSec as per instructions.
All seems to be working and levels are the same as previous configuration. 
BUT with the new BSec and ESPHome the IAQ reading is very high 1651 IAQ ? 
it is in calibrated state, but this sensor reading doesn’t change a lot, only 1625 to 1660 ….. any ideas? 

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.5

### What platform are you using?

ESP8266

### Board

Wemos D1

### Component causing the issue

BME680

### Example YAML snippet

```yaml
binary_sensor:
  - platform: status
    name: "US Temp Status"

bme680_bsec:
    address: 0x76
    sample_rate: lp   
    iaq_mode: static
    state_save_interval: 6h
logger:
  logs:
    custom_components.iaquk: debug
    
    
    
sensor:
  - platform: bme680_bsec
    temperature:
      name: "US Temperature"
      sample_rate: lp
      filters:
        - median
    pressure:
      name: "US Pressure"
      sample_rate: lp
      filters:
        - median
    humidity:
      name: "US Humidity"
      sample_rate: lp
      filters:
        - median
    gas_resistance:
      # Gas resistance in Ω
      name: "Gas Resistance"
      filters:
        - median
    iaq:
      name: "Home IAQ"
      filters:
        - median
    iaq_accuracy:
      # IAQ accuracy as a numeric value of 0, 1, 2, 3
      name: "Home IAQ Accuracy"    
        
        
    co2_equivalent:
      name: "Home CO2 Equivalent"
    breath_voc_equivalent:
      name: "Home Breath VOC Equivalent"
 

  - platform: sds011
    pm_2_5:
      name: "PM <2.5µm Concentration"
    pm_10_0:
      name: "PM <10.0µm Concentration"
    update_interval: 15min
 
text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "Accuracy"
```
