### ISSUE TITLE
SNTP doest not execute update_interval

### ISSUE THREAD

**Issue by tiagofreire-pt** [esphome/issues#2556]
### The problem

The `update_interval` setting is never applied.

Using a value of 30 seconds, no communication is made to the ntp servers after the boot up process being completed.

I have two ntp servers, on the LAN interface, `192.168.10.203` is a `stratum 1` and `192.168.60.62` is another one but just `stratum 2`.

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.9.5

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

sntp

### Example YAML snippet

```yaml
time:
  - platform: sntp
    id: sntp_time
    servers: 
      - 192.168.10.203
      - 192.168.10.62
    timezone: "Europe/London"
    update_interval: 30s
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"
```
```


### Anything in the logs that might be useful for us?

```txt
The message "Synchronized system clock" never appears on log.
```

### Additional information

Using the firewall packet capture on both LAN and WIFI interfaces, for the ESP32 IP address, only shows NTP sync on its boot. Not a single one after several minutes of packet capturing:

Interface | Capture output
-- | --
LANigb0 | 14:45:11.499950 IP 192.168.11.182.53378 > 192.168.10.203.123: UDP, length 48
LANigb0 | 14:45:11.500293 IP 192.168.10.203.123 > 192.168.11.182.53378: UDP, length 48
WIFIigb1 | 14:45:11.383292 IP 192.168.11.1.67 > 192.168.11.182.68: UDP, length 300
WIFIigb1 | 14:45:11.395596 IP 192.168.11.182 > 224.0.0.251: igmp
WIFIigb1 | 14:45:11.499907 IP 192.168.11.182.53378 > 192.168.10.203.123: UDP, length 48
WIFIigb1 | 14:45:11.500309 IP 192.168.10.203.123 > 192.168.11.182.53378: UDP, length 48
WIFIigb1 | 14:45:11.664632 IP 192.168.11.182.5353 > 224.0.0.251.5353: UDP, length 102
WIFIigb1 | 14:45:11.760355 IP 192.168.11.182 > 224.0.0.251: igmp
WIFIigb1 | 14:45:11.967815 IP 192.168.11.182.5353 > 224.0.0.251.5353: UDP, length 102
WIFIigb1 | 14:45:12.264819 IP 192.168.11.182.5353 > 224.0.0.251.5353: UDP, length 102
WIFIigb1 | 14:45:12.566017 IP 192.168.11.182.5353 > 224.0.0.251.5353: UDP, length 251
WIFIigb1 | 14:45:13.666204 IP 192.168.11.182.5353 > 224.0.0.251.5353: UDP, length 251
WIFIigb1 | 14:45:14.766030 IP 192.168.11.182.5353 > 224.0.0.251.5353: UDP, length 251
