### ISSUE TITLE
on_boot invalid option with esp-idf

### ISSUE THREAD

**Issue by markusg1234** [esphome/issues#2557]
### The problem

Tested an ESP32 with esp-idf that uses on_boot but invalid option is displayed.

### Which version of ESPHome has the issue?

v2021.10.0b6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32-IDF

### Board

Any board

### Component causing the issue

on_boot

### Example YAML snippet
```yaml
esphome:
  name: test-2

esp32:
  board: esp-wrover-kit  
  framework:
    type: esp-idf

  on_boot:
     then:
       - switch.turn_on: test_switch
       

    

logger:


api:

ota:
  password: "*"

wifi:
  ssid: "*"
  password: ""

switch:
  - platform: gpio
    pin: GPIO23
    id: test_switch
    name: "test switch"  
```

### Anything in the logs that might be useful for us?

![error](https://user-images.githubusercontent.com/2220900/137821189-aabd3ff7-e280-42ee-adb1-f12f124bb214.jpg)
