### ISSUE TITLE
Tool Manager can not install required library

### ISSUE THREAD

**Issue by jsuanet** [esphome/issues#2559]
### The problem

Using ESPHome 2021.10b6 the following error occurred:
![Screenshot 2021-10-18 at 15 10 40](https://user-images.githubusercontent.com/75206491/137738327-db97d673-0c65-43ad-ae02-9d99fc5c8f26.png)

### Which version of ESPHome has the issue?

2021.10b6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32-IDF

### Board

esp32doit-devkit-v1

### Example YAML snippet

```
esphome:
  name: study-lamp

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
```
