### ISSUE TITLE
Program failed with code -9

### ISSUE THREAD

**Issue by rosscullen** [esphome/issues#256]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker (Synology)  ESPHome 1.12.2

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff Basic 

**Affected component:**

**Description of problem:**
When compiling build, getting the following error: Program failed with code -9

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: sonoff
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "WIFI"
  password: "password"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'password'

ota:
  password: 'password'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Desk light button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Desk light relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:
  - platform: wifi_signal
    name: "Desk light WiFi signal"
    update_interval: 60s

  - platform: uptime
    name: "Desk light uptime"

text_sensor:
  - platform: version
    name: "Desk light ESPHome version"

```

**Traceback (if applicable):**

```
INFO Reading configuration...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/sonoff
Processing sonoff (platform: espressif8266@1.8.0; framework: arduino; board: esp01_1m)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz 80KB RAM (1MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.2.0
|   |-- <ESP8266WiFi> 1.0
|-- <Hash> 1.0
|-- <esphome-core> 1.12.2
|   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESPAsyncTCP> 1.2.0
|   |   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/sonoff/src/main.cpp.o
Generating LD script .pioenvs/sonoff/ld/eagle.app.v6.common.ld
Compiling .pioenvs/sonoff/lib4d9/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pioenvs/sonoff/lib4d9/ESP8266WiFi/CertStoreBearSSL.cpp.o
Compiling .pioenvs/sonoff/lib4d9/ESP8266WiFi/ESP8266WiFi.cpp.o
```

**Additional information and things you've tried:**
Tried deleting folder and recreating from scratch but no joy
