### ISSUE TITLE
Thermostat with away mode not storing values

### ISSUE THREAD

**Issue by Alex9779** [esphome/issues#2560]
### The problem

I am trying to have my thermostats with 'home' and 'away' mode for day and night but I if I am in 'home' and set it to 20° switch to 'away' and then back to 'home' it is back to 18° which is the default.
Shouldn't the values be stored for each mode and get restored when I switch modes? 
Doesn't make a lot of sense to me that on every switch the default value is set.
Or do I have some config problem?

### Which version of ESPHome has the issue?

2021.10.0b6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

ESP07S

### Component causing the issue

thermostat

### Example YAML snippet

```yaml
nh_0_floor_heating_2.yaml:
substitutions:
  device_name: nh-0-floor-heating-2
  friendly_name: nh_0_floor_heating_2
  ip_address: 172.16.54.92
  min_temperature: 16 °C
  max_temperature: 25 °C
  temperature_step: 0.5 °C
  heat_deadband: 0 °C
  min_heating_off_time: 15s
  min_heating_run_time: 15s
  min_idle_time: 15s
  default_target_temperature_low: 18 °C

packages:
  esphome: !include common/ESP8266.yaml
  wifi: !include common/wifi.yaml
  device: !include common/device.yaml
  floor_heating: !include common/output/floor_heating.yaml
  
logger:
  
sensor:
  - platform: homeassistant
    id: shower_temperature
    entity_id: sensor.nh_0_shower_temperature
    
  - platform: homeassistant
    id: hobby_temperature
    entity_id: sensor.nh_0_hobby_temperature
    
  - platform: homeassistant
    id: whirlpool_temperature
    entity_id: sensor.nh_0_whirlpool_temperature

climate:
  - platform: thermostat
    <<: !include common/climate/default_floor_heating_options.yaml
    name: ${friendly_name}_shower
    sensor: shower_temperature
    heat_action:
      - output.turn_on: hc1
    idle_action:
      - output.turn_off: hc1

  - platform: thermostat
    <<: !include common/climate/default_floor_heating_options.yaml
    name: ${friendly_name}_hobby
    sensor: hobby_temperature
    heat_action:
      - output.turn_on: hc2
      - output.turn_on: hc3
    idle_action:
      - output.turn_off: hc2
      - output.turn_off: hc3

  - platform: thermostat
    <<: !include common/climate/default_floor_heating_options.yaml
    name: ${friendly_name}_whirlpool
    sensor: whirlpool_temperature
    heat_action:
      - output.turn_on: hc4
      - output.turn_on: hc5
    idle_action:
      - output.turn_off: hc4
      - output.turn_off: hc5

default_floor_heating_options.yaml:
default_target_temperature_low: ${default_target_temperature_low}
min_heating_off_time: ${min_heating_off_time}
min_heating_run_time: ${min_heating_run_time}
min_idle_time: ${min_idle_time}
heat_deadband: ${heat_deadband}
away_config:
  default_target_temperature_low: ${default_target_temperature_low}
visual:
  min_temperature: ${min_temperature}
  max_temperature: ${max_temperature}
  temperature_step: ${temperature_step}
```
