### ISSUE TITLE
ESP32-C3 adc compile error

### ISSUE THREAD

**Issue by liwei19920307** [esphome/issues#2563]
### The problem

The latest version 2021.10.X cannot compile the ADC of ESP32-C3, how should I configure it

### Which version of ESPHome has the issue?

2021.10.0b7

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32

### Board

esp_c3_13u

### Component causing the issue

adc

### Example YAML snippet

```yaml
esphome:
  name: esp32_c3_test
  platform: ESP32
  board: esp32-c3-devkitm-1
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
    platform_packages:
      - framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#2.0.0
    board_build.variant: esp32c3
    board_build.f_cpu: 160000000L
    board_build.f_flash: 40000000L
    upload_protocol: esptool
    board_build.flash_mode: dio

sensor:
  - platform: adc
    pin: 3
    name: "esp32_c3_test_brightness"
    update_interval: 60s
    unit_of_measurement: "%"
    icon: "mdi:brightness-6"
    accuracy_decimals: 0
    filters:
      - lambda: |-
            return ( 1 - x ) * 100.0;
```

### Anything in the logs that might be useful for us?

```txt
Failed config

sensor.adc: [source esp32-c3-test.yaml:50]
  platform: adc
  
  ESP32: Only pins 32 though 39 support ADC.
  pin: 3 [source esp32-c3-test.yaml:51]
  name: esp32_c3_test_brightness
  update_interval: 60s
  unit_of_measurement: %
  icon: mdi:brightness-6
  accuracy_decimals: 0
  filters: 
    - lambda: return ( 1 - x ) * 100.0;
```
