### ISSUE TITLE
on_speed_set shown as invalid option for fan

### ISSUE THREAD

**Issue by psbankar** [esphome/issues#2565]
### The problem

https://www.esphome.io/components/fan/index.html#fan-on-speed-set-trigger
According to documentation, when I try to use the on_speed_set trigger for fan, it gives me the following error
'[on_speed_set] is an invalid option for [fan.speed]'

![image](https://user-images.githubusercontent.com/22224770/137873791-93954b24-e080-4f0e-bd13-644d16c6b201.png)

### Which version of ESPHome has the issue?

1.20.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Component causing the issue

fan

### Example YAML snippet

```yaml
fan:
  - platform: speed
    id: bedroomfan
    output: my_output_1
    speed_count: 6
    name: "Bedroom Fan"
    on_speed_set:
    - logger.log: "Fan Speed was changed!"
```
