### ISSUE TITLE
Uptime sensor error with example configuration using ESP32-IDF

### ISSUE THREAD

**Issue by markusg1234** [esphome/issues#2566]
### The problem

With the example configuration an error occurs on compile if using ESP32-IDF

Ihttps://beta.esphome.io/components/sensor/uptime.html?highlight=uptime

Regards,

Markus

### Which version of ESPHome has the issue?

v2021.10.0b7v

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32-IDF

### Board

Any board

### Component causing the issue

Uptime sensor

### Example YAML snippet

```yaml
esphome:
  name: test-2

esp32:
  board: esp-wrover-kit  
  framework:
    type: esp-idf
    
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1"

wifi:
  ssid: "1"
  password: "12345678"

text_sensor:
  - platform: template
    name: Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
sensor:
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/test-2.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/test-2
Processing test-2 (board: esp-wrover-kit; framework: espidf; platform: espressif32 @ 3.3.2)

HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-espidf 3.40300.0 (4.3.0) 
 - tool-cmake 3.16.4 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - tool-ninja 1.7.1 
 - toolchain-esp32ulp 1.22851.191205 (2.28.51) 
 - toolchain-xtensa32 2.80400.210211 (8.4.0)
Reading CMake configuration...
LDF Modes: Finder ~ off, Compatibility ~ soft
No dependencies
Compiling /data/test-2/.pioenvs/test-2/src/main.o
/config/esphome/test-2.yaml: In lambda function:
/config/esphome/test-2.yaml:46:17: error: 'String' was not declared in this scope
                 (days ? String(days) + "d " : "") +
                 ^~~~~~
/config/esphome/test-2.yaml:46:17: note: suggested alternative: 'trunc'
                 (days ? String(days) + "d " : "") +
                 ^~~~~~
                 trunc
Compiling /data/test-2/.pioenvs/test-2/coap/libcoap/src/subscribe.o
Compiling /data/test-2/.pioenvs/test-2/coap/libcoap/src/uri.o
Compiling /data/test-2/.pioenvs/test-2/coap/libcoap/src/coap_io.o
Compiling /data/test-2/.pioenvs/test-2/coap/port/coap_notls.o
Compiling /data/test-2/.pioenvs/test-2/coap/port/coap_mbedtls.o
Compiling /data/test-2/.pioenvs/test-2/console/commands.o
*** [/data/test-2/.pioenvs/test-2/src/main.o] Error 1
Compiling /data/test-2/.pioenvs/test-2/console/esp_console_repl.o
========================== [FAILED] Took 3.53 seconds ==========================
```
