### ISSUE TITLE
Wemos D1 Mini + CT clamp strange behavior

### ISSUE THREAD

**Issue by floringhimie** [esphome/issues#2567]
### The problem

Hi, I have the Wemos D1 mini + CT clamp 50A/1V, SCT013 and in most of the cases is working fine but from time to time it happens to have a strange values:
1 huge values 120 Amps, 90 Apms
2 during one or two days the values are not correct and are vary from 0,5 to 5Amps each 5seconds
<img width="845" alt="Capture" src="https://user-images.githubusercontent.com/33951255/138070334-0d9b3ee2-fbac-4d91-ae6f-18aec6dca2ab.PNG">

Any Idea?
I tried to reset the Wemos but no success.
Seems more like a interference 
Thank you!

### Which version of ESPHome has the issue?

2021.8.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

CT-Clamp

### Example YAML snippet

```yaml
sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    name: "True Current"                # This first sensor gets the Amps, note that is set to internal only.
    id: the_clamp
    internal: true
    update_interval: 10s
    filters:
      - calibrate_linear:               # Calibrate your own stuff here, mine is only used for the car charger, therefore I'm pulling approx 28A
          - 0.00026 -> 0.0
          - 0.02856 -> 8.37
          - 0.09489 -> 27.9
  - platform: wifi_signal
    name: "Poarta RSSI"
    update_interval: 60s
  - platform: template
    name: "ESP8266 Current"             # This sensor is the one that gets seen by HA, if the reading is below 0.1A then it reports 0, keeps your 0 at 0
    id: templated_sensor
    lambda: |-
      if (id(the_clamp).state > 0.1){
        return (id(the_clamp).state);
      } else {
        return 0.0;
      }
    device_class: current
    update_interval: 10s
    accuracy_decimals: 2
    unit_of_measurement: A

  - platform: template
    name: "ESP8266 Watts"               # This sensor converts the Amps to Watts (this is assuming that your voltage is 230, if not change the 230 accordingly)
    id: esp_watts
    lambda: |-
      return id(templated_sensor).state * 230;
    accuracy_decimals: 2
    update_interval: 10s
    device_class: power
    unit_of_measurement: W
                   
  - platform: total_daily_energy        # This sensor will give you a Daily kW reading
    name: "ESP8266 Daily Energy"
    unit_of_measurement: 'kWh'
    power_id: esp_watts
    filters:
      - multiply: 0.001
    device_class: energy

  - platform: adc
    pin: A0
    id: adc_sensor   

  - platform: ct_clamp
    sensor: adc_sensor
    name: "raw values"
    internal: true
    update_interval: 10s
    unit_of_measurement: mA
    accuracy_decimals: 5
```
