### ISSUE TITLE
`esp32` cannot be run in `power_save_mode: none`

### ISSUE THREAD

**Issue by ayufan** [esphome/issues#2570]
### The problem

After updating esphome to https://github.com/esphome/esphome/releases/tag/2021.10.0 I'm unable to compile this very simple YAML config even though I no where use `esp32_ble`.

There appears to be added validation to see if mode is set to `none`, but this does not check if the conflicting components are actually used. Likely this would be better if instead than in `WiFi` would be implemented by conflicting component side, like `esp32_ble`.

This appears this check:
- was initially introduced by https://github.com/esphome/esphome/commit/bfca3f242a4bc5535899f23074bfd0e8770d22aa which validated an actual components used
- disappear in https://github.com/esphome/esphome/commit/ac0d921413c3884752193fe568fa82853f0f99e9#diff-84b8b2544d15d94573bbfe2b3ce5ed448c2666320a0f49e579ab695eae55f49cL158 in favor of iterating a list

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

esp32_ble

### Example YAML snippet

```yaml
esphome:
  name: esp32_test
  platform: ESP32
  board: ttgo-lora32-v1

wifi:
  networks:
  - ssid: "WiFi"
    password: "WiFiWiFi"
  power_save_mode: none
```
