### ISSUE TITLE
Unknown pin mode pulldown with new 2021.10 update

### ISSUE THREAD

**Issue by DDomnick** [esphome/issues#2573]
### The problem

INFO Reading configuration /config/esphome/ts-devnode.yaml...
Failed config

binary_sensor.gpio: [source /config/esphome/ts-devnode.yaml:72]
  platform: gpio
  pin:  [source /config/esphome/ts-devnode.yaml:74]
    number: GPIO36
    
    Unknown pin mode pulldown.
    mode: pulldown [source /config/esphome/ts-devnode.yaml:75]

### Which version of ESPHome has the issue?

2021.10

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.10.1

### What platform are you using?

ESP32

### Board

featheresp32

### Component causing the issue

binary_sensor.gpio

### Example YAML snippet

```yaml
esphome:
  name: ts-devnode
  
esp32:
  board: featheresp32
  framework:
    type: arduino
    version: recommended

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:
  password: "4af7fd86acd"

wifi:
  ssid: "NTIrrrr"
  password: "rrfdgdfgdfg"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ts-Devnode Fallback Hotspot"
    password: "lepxh7W3AZJH"

captive_portal:


# https://esphome.io/components/binary_sensor/index.html?highlight=sensor
# Define Limit Switches
binary_sensor:

  - platform: gpio
    pin: 
      number: GPIO36 
      mode: pulldown     // Or INPUT_PULLDOWN - neither work after update.
    name: "Dev-(+3v3_U)"
    id: util_power
    filters:  
      - delayed_on: 16s
      - delayed_off: 4s
    on_release:
      then:
      - logger.log: "Dev-(+3v3_Util) LOW > 4 seconds - Generator Starting"      # Log in ESPHome
    on_press:                                                                   # Watch for pin to go from low-to-high (a press in ESPHome)
      then:
      - logger.log: "Dev-(+3v3_Util) HIGH > 4 minutes - Generator Stopping"     # Log in ESPHome
```
```


### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/ts-devnode.yaml...
Failed config

binary_sensor.gpio: [source /config/esphome/ts-devnode.yaml:72]
  platform: gpio
  pin:  [source /config/esphome/ts-devnode.yaml:74]
    number: GPIO36
    
    Unknown pin mode pulldown.
    mode: pulldown [source /config/esphome/ts-devnode.yaml:75]
  name: Dev-(+3v3_U)
  id: util_power
  filters: 
    - delayed_on: 16s
    - delayed_off: 4s
  on_release: 
    then: 
      - logger.log: Dev-(+3v3_Util) LOW > 4 seconds - Generator Starting
  on_press: 
    then: 
      - logger.log: Dev-(+3v3_Util) HIGH > 4 minutes - Generator Stopping
```
