### ISSUE TITLE
GPIO Pin 0 does not support Pullup mode

### ISSUE THREAD

**Issue by jrstough** [esphome/issues#2574]
### The problem

After updating ESPHome to version 2021.10.0 I get "GPIO Pin 0 does not support pullup pin mode. Please choose another pin."  I have 3 boards that are doing the same thing.  These worked without any errors before the update.  See code attached.

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

D1 Mini and Node MCU

### Component causing the issue

GPIO

### Example YAML snippet

```yaml
esphome:
  name: basement_utilities
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_pw
  manual_ip:
    static_ip: 192.168.10.106
    gateway: 192.168.10.1
    subnet: 255.255.255.0
# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
   password: !secret esp_node_pw

ota:

# Blue Light 1  
output:
  - platform: gpio
    inverted: true
    pin: D0
    id: frezzer_ok
  - platform: gpio
    pin: D1
    id: frezzer_alarm
  - platform: gpio
    pin: D2
    id: frezzer_not_ok    
    
  - platform: esp8266_pwm
    pin: D8
    id: alarm_test
    
light:
  - platform: monochromatic
    name: "pwm alarm"
    output: alarm_test
    
binary_sensor:
  - platform: gpio
    pin:
      number: D2
    name: "Deep Frezer Temp"
    device_class: heat
    
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "Frezzer Alarm Silenced"
    
#Blue Light 2 on Board
status_led:
  pin:
    number: D4
    inverted: True

#Read Dallas Comms
dallas:
  - pin: D6
  
#Read Deep Freezer Temp  
sensor:
  - platform: dallas
    address: 0xCC01192E0E1C1828
    name: "Deep Freezer Temperature"
    #Setpoints are in Degrees C
    on_value_range:
        #Turn on Below 17.8 F or -17.8 C
        - below: -17.8
          then:
            - output.turn_on: frezzer_ok
            - output.turn_off: frezzer_not_ok
        #Turn Off Above 5 F or -15 C
        - above: -15
          then:
            - output.turn_off: frezzer_ok
            - output.turn_on: frezzer_not_ok
            
#Basement Node MCU Wifi Strength
  - platform: wifi_signal
    name: "Basement Node MCU WiFi"
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/basement_utilities.yaml...
WARNING 'basement_utilities': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
Failed config

binary_sensor.gpio: [source /config/esphome/basement_utilities.yaml:52]
  platform: gpio
  pin:  [source /config/esphome/basement_utilities.yaml:54]
    number: D3
    
    GPIO Pin 0 does not support pullup pin mode. Please choose another pin.
    mode: INPUT_PULLUP [source /config/esphome/basement_utilities.yaml:55]
    inverted: True
  name: Frezzer Alarm Silenced
```
