### ISSUE TITLE
Sonoff Basic - GPIO Pin 0 does not support pullup pin mode

### ISSUE THREAD

**Issue by misterpeee** [esphome/issues#2579]
### The problem

Following the upgrade of ESPHome to 2021.10.0 the pullup configuration on a sonoff basic reports the error "GPIO Pin 0 does not support pullup pin mode. Please choose another pin." during validation.  This configuration was working on the previous version.

The documentation also states using the pull up for the GPIO binary sensor states GPIO0 will require the input pullup option is required: https://esphome.io/devices/sonoff_basic.html

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

Sonoff basic

### Component causing the issue

binary_sensor

### Example YAML snippet

```yaml
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay
```

### Anything in the logs that might be useful for us?

```txt
Failed config

binary_sensor.gpio: [source /config/esphome/test.yaml:17]
  platform: gpio
  pin:  [source /config/esphome/test.yaml:19]
    number: GPIO0
    
    GPIO Pin 0 does not support pullup pin mode. Please choose another pin.
    mode: INPUT_PULLUP [source /config/esphome/test.yaml:20]
    inverted: True
  name: Sonoff Basic Button
  on_press: 
    - switch.toggle: relay
```
