### ISSUE TITLE
error with open logs after update 2021.10

### ISSUE THREAD

**Issue by pepsonEL** [esphome/issues#2584]
### The problem

Before update i use 2021.9.3 and when try open logs al works ok. Now after update to 2021.10 logs no working and can not open/read.....

INFO Reading configuration /config/esphome/Lazienka2_fan_bme280.yaml...
WARNING 'lazienka2_fan_bme280': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
INFO Detected timezone 'Europe/Warsaw'
INFO Starting log output from lazienka2_fan_bme280.local using esphome API
WARNING Can't connect to ESPHome API for lazienka2_fan_bme280.local: Error resolving IP address: [Errno -2] Name or service not known
INFO Trying to reconnect to lazienka2_fan_bme280.local in the background

### Which version of ESPHome has the issue?

2021.10

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

esp8285,  esp01_1m

### Example YAML snippet

```yaml
substitutions:
  device_name: lazienka2_fan_bme280

esphome:
  name: '${device_name}'
  platform: ESP8266
  board: esp8285

# WiFi connection
wifi:
  ssid: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name}_AP'
    password: "xxxxxxxxxxxxxxxxx"
    
captive_portal:

# Enable Web server
web_server:
  port: 80
  auth:
    username: xxxxxxxxxxxxx
    password: xxxxxxxxxxxxxxxxxxxx

# Enable Home Assistant API
api:
  password: xxxxxxxxxxxxxxxxxx

# Enable over-the-air updates
ota:
  password: xxxxxxxxxxxxx
  
# Enable logging
logger:
    baud_rate: 0
    level: DEBUG
    
# Sets time from Homeassistant
time:
  - platform: homeassistant
    id: homeassistant_time

status_led:
  pin:
    number: GPIO13
    inverted: yes

i2c:
  sda: GPIO3 #RX
  scl: GPIO1 #TX
  scan: True

sensor:
  - platform: bme280
    temperature:
      name: '${device_name} Temperature'
      oversampling: 16x
    pressure:
      name: '${device_name} Pressure'
    humidity:
      name: '${device_name} Humidity'
    address: 0x76
    update_interval: 60s
  - platform: wifi_signal
    name: '${device_name} WiFi Signal'
    update_interval: 60s
    accuracy_decimals: 0
  - platform: uptime
    name: '${device_name} Uptime'
    unit_of_measurement: days
    update_interval: 300s
    accuracy_decimals: 1
    filters:
      - multiply: 0.000011574
    
switch:
  - platform: gpio
    name: '${device_name} relay'
    icon: 'mdi:fan'
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT
      inverted: True
    name: '${device_name} button'
    on_press:
      - switch.toggle: relay
# Sensors for ESP version and WIFI information
text_sensor:
  - platform: version
    name: "${device_name} ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "${device_name} ip"
    ssid:
      name: "${device_name} ssid"
```
