### ISSUE TITLE
Teleinfo: PAPP get unknown value since 2021.10

### ISSUE THREAD

**Issue by Nardol** [esphome/issues#2585]
### The problem

I have a teleinfo component set, with HCHP, HCHC and PAPP.
The first two are updated right but PAPP is never updated, in Home Assistant it is set to unknown.

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.10

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

teleinfo

### Example YAML snippet

```yaml
esphome:
  name: teleinfokit
  platform: ESP8266
  board: esp01_1m

uart:
  id: uart_bus
  rx_pin: GPIO3
  baud_rate: 1200
  parity: EVEN
  data_bits: 7

teleinfo:
  id: myteleinfo
  update_interval: 30s
  historical_mode: true

sensor:
  - platform: teleinfo
    tag_name: "HCHC"
    id: hchc
    name: "Index Heures Creuses"
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    icon: mdi:flash
    device_class: energy
    state_class: total_increasing
    teleinfo_id: myteleinfo
    filters:
      - multiply: 0.001
  - platform: teleinfo
    tag_name: "HCHP"
    id: hchp
    name: "Index Heures Pleines"
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    icon: mdi:flash
    device_class: energy
    state_class: total_increasing
    teleinfo_id: myteleinfo
    filters:
      - multiply: 0.001
  - platform: teleinfo
    tag_name: "PAPP"
    id: papp
    name: "Puissance Actuelle"
    unit_of_measurement: "VA"
    state_class: "measurement"
    icon: mdi:flash
    teleinfo_id: myteleinfo
  - platform: teleinfo
    tag_name: "IINST"
    id: iinst
    name: "Intensité Actuelle"
    unit_of_measurement: "A"
    device_class: current
    state_class: "measurement"
    icon: mdi:flash
    teleinfo_id: myteleinfo

i2c:
  sda: GPIO0
  scl: GPIO2
```

### Anything in the logs that might be useful for us?

```txt
[14:49:13][V][sensor:062]: 'Index Heures Creuses': Received new state 4113085.000000
[14:49:13][D][sensor:113]: 'Index Heures Creuses': Sending state 4113.08496 kWh with 3 decimals of accuracy
[14:49:13][V][sensor:062]: 'Index Heures Pleines': Received new state 5575232.000000
[14:49:13][D][sensor:113]: 'Index Heures Pleines': Sending state 5575.23242 kWh with 3 decimals of accuracy
[14:49:13][E][teleinfo:167]: Invalid Value
```
