### ISSUE TITLE
Dependency issue with Arduino framework

### ISSUE THREAD

**Issue by Lyr3x** [esphome/issues#2587]
### The problem

After upgrading to 2021.10 my custom_component which relies on libraries like Wire and EEPROM are not compiling anymore because those dependencies are not found. I am using the CLI as well as a docker setup. Users are reporting that issue as well.

I am depending on the Sensor implementation as it does not make any sense for me to maintain that code as well. 

I already tried to pin the framework version to the version we used previously but that does not help. It would be a huge amount of work to get rid of those libraries which come with the Arduino framework. 

### Which version of ESPHome has the issue?

2021.10

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

various

### Example YAML snippet

```yaml
substitutions:
  devicename: roodedev
  friendly_name: $devicename

external_components:
  refresh: always
  source: components

esphome:
  name: $devicename
  libraries:
    - pololu/VL53L1X@^1.3.0
    
esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino
    platform_version: 3.2.0
    
wifi:
  networks:
    - ssid: !secret ssid1
      password: !secret ssid1_password
  fast_connect: True
  power_save_mode: light
  domain: .shieldnet

captive_portal:

api:
  password: !secret api_password
  reboot_timeout: 60min
  services:
    - service: set_counter
      variables:
        newCount: int
      then:
        - lambda: "id(roode_platform)->sendCounter(newCount);"
    - service: reset_counter
      then:
        - lambda: "id(roode_platform)->sendCounter(0);"
    - service: recalibrate
      then:
        - lambda: "id(roode_platform)->recalibration();"

ota:
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_password

# Enable logging
logger:
  level: INFO

i2c:
  sda: 21
  scl: 22

roode:
  id: roode_platform
  address: 0x29
  update_interval: 10ms
  calibration: true
  roi_height: 16
  roi_width: 6
  max_threshold_percentage: 75
  min_threshold_percentage: 5

  roi_calibration: true
  invert_direction: true
  restore_values: false

switch:
  - platform: restart
    name: $friendly_name Restart
binary_sensor:
  - platform: status
    name: $friendly_name Status
  - platform: roode
    presence_sensor:
      name: $friendly_name presence

sensor:
  - platform: roode
    id: hallway
    people_counter_sensor:
      id: peopleCounter
      name: $friendly_name people counter
    distance_sensor:
      name: $friendly_name distance
      filters:
        - delta: 100.0
    max_threshold_zone0:
      name: $friendly_name max zone 0
    max_threshold_zone1:
      name: $friendly_name max zone 1
    min_threshold_zone0:
      name: $friendly_name min zone 0
    min_threshold_zone1:
      name: $friendly_name min zone 1
    roi_height:
      name: $friendly_name ROI height
    roi_width:
      name: $friendly_name ROI width

  - platform: wifi_signal
    name: $friendly_name RSSI
    update_interval: 60s

  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

text_sensor:
  - platform: roode
    version:
      name: $friendly_name version
  - platform: roode
    entry_exit_event:
      name: $friendly_name last direction
  - platform: template
    name: $friendly_name Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration peopleCounterDev.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing roodedev (board: wemos_d1_mini32; framework: arduino; platform: espressif32 @ 3.2.0)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif32 3.10006.210326 (1.0.6)
 - tool-esptoolpy 1.30000.201119 (3.0.0)
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF Modes: Finder ~ off, Compatibility ~ soft
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <VL53L1X> 1.3.0
|-- <WiFi> 1.0
|-- <FS> 1.0
|-- <Update> 1.0
|-- <ESPAsyncWebServer-esphome> 1.3.0
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <DNSServer> 1.1.0
|-- <Wire> 1.0.1
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESPmDNS> 1.0
Compiling .pioenvs/roodedev/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/api/util.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/esp32/gpio_arduino.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/esp32/gpio_idf.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/i2c/i2c.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/i2c/i2c_bus_arduino.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/i2c/i2c_bus_esp_idf.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/json/json_util.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/mdns/mdns_esp32_arduino.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/mdns/mdns_esp_idf.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/restart/restart_switch.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/roode/roode.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/roodedev/src/esphome/components/sensor/filter.cpp.o
In file included from src/esphome/components/roode/roode.cpp:2:0:
src/esphome/components/roode/roode.h:9:20: fatal error: EEPROM.h: No such file or directory

****************************************************************
* Looking for EEPROM.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:EEPROM.h"
* Web  > https://platformio.org/lib/search?query=header:EEPROM.h
*
****************************************************************

compilation terminated.
*** [.pioenvs/roodedev/src/esphome/components/roode/roode.cpp.o] Error 1
```

### Additional information

https://github.com/Lyr3x/Roode/pull/51
