### ISSUE TITLE
ESPHome seems to generate false negative error message

### ISSUE THREAD

**Issue by alexander-vitishchenko** [esphome/issues#2589]
### The problem

Not able to build a firmware with a new "Graph" feature, using the configuration that feels to be correct and based on the [guide](https://esphome.io/components/display/index.html#graphs)

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32

### Board

ESP32 TTGO with T-Display 

### Component causing the issue

graph

### Example YAML snippet

```yaml
graph:
  - id: single_graph
    sensor: tdisplay_button_input_0    
    duration: 60
    width: 151
    height: 51
```

### Anything in the logs that might be useful for us?

```txt
Failed config

graph: [source /config/esphome/esphome-test-4-esp32-display.yaml:105]
  
  Component graph requires component sensor.
  - id: single_graph
    sensor: tdisplay_button_input_0
    duration: 60
    width: 151
    height: 51
```
