### ISSUE TITLE
SX1509 GPIO support broken in 2021.10

### ISSUE THREAD

**Issue by roblamoreaux** [esphome/issues#2590]
### The problem

I updated to 2021.10 today and now my node using an SX1509 to scan switches won't compile. It doesn't like using the pins as GPIO sensors. Here is the error massage that SX1509 doesn't have GPIO and my keypad is not scanned (individual switches to gnd). This did compile under 2021.9.x

### Which version of ESPHome has the issue?

2021.10.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

SX1509

### Example YAML snippet

```yaml
- platform: gpio
    name: "Hot Tub Keypad Up"
    id: up_button
    pin:
      sx1509: sx1509_hub1
      # Use pin number 0 on the SX1509
      number: 3
      mode: INPUT_PULLUP
      inverted: True
```

### Anything in the logs that might be useful for us?

```txt
`
binary_sensor.gpio: [source /config/esphome/hot_tub_advanced.yaml:270]
  platform: gpio
  name: Hot Tub Keypad Up
  id: up_button
  pin:  [source /config/esphome/hot_tub_advanced.yaml:273]
    
    ID 'sx1509_hub1' of type sx1509::SX1509Component doesn't inherit from sx1509::SX1509GPIOPin. Please double check your ID is pointing to the correct value.
    sx1509: sx1509_hub1 [source /config/esphome/hot_tub_advanced.yaml:274]
    number: 3
    mode: 
      input: True
      pullup: True
      output: False
    inverted: True
  on_press: 
    - then:
```
