### ISSUE TITLE
Fix GPIO validation for ESP32-S2

### ISSUE THREAD

**Issue by vooon** [esphome/issues#2591]
### The problem

I am unable to use some gpios on esp32s2 variant because validator threats it like usual esp32.
For example i can't use `i2c: {scl: 35, sda: 33}` (which replaces D1/D2 from D1 pro mini on S2 mini).
See: https://www.wemos.cc/en/latest/_static/files/sch_s2_mini_v1.0.0.pdf

According to https://www.espressif.com/sites/default/files/documentation/esp32-s2_datasheet_en.pdf only GPIO46 is Input only. Flash and psram also uses different pins.

### Which version of ESPHome has the issue?

2021.11.0-dev

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Example YAML snippet

```yaml
substitutions:
  uname: Gate Lock
  device_name: gate_lock
  friendly_name: $uname
  device_description: "Gate Lock"

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  project:
    name: "vooon.smart_lock"
    version: "0.1.0"

esp32:
  board: esp32-s2-saola-1
  variant: esp32s2
  framework:
    type: esp-idf
    version: recommended

i2c:
  id: i2c_bus
  scl: 35
  sda: 33
  frequency: 100kHz
  scan: true
```

### Anything in the logs that might be useful for us?

```txt
Failed config

i2c: [source entrance-lock.yaml:85]
  - [source entrance-lock.yaml:86]
    id: i2c_bus
    
    GPIO35 (34-39) does not support output pin mode.
    scl: 35 [source entrance-lock.yaml:87]
    sda: 33
    frequency: 100kHz
    scan: True
```
