### ISSUE TITLE
xtensa-lx106-elf-g++: Permission denied

### ISSUE THREAD

**Issue by lloydpick** [esphome/issues#2594]
### The problem

I just pull the latest docker container, restarted the service and then went to compile one of my yamls that was marked as "update available". Compiling was working completely fine before the upgrade. No changes were made to the yaml.

### Which version of ESPHome has the issue?

2021.10.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Example YAML snippet

```yaml
esphome:
  name: car
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    priority: -10
    then:
      - switch.turn_on: green
      - delay: 1s
      - switch.turn_on: yellow
      - delay: 1s
      - switch.turn_on: red
      - delay: 1s
      - switch.turn_off: green
      - switch.turn_off: yellow
      - switch.turn_off: red

wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  use_address: 192.168.1.249
  fast_connect: on #we only have one WiFi AP so just use the first one that matches
  ap: #since we listed an SSID above, this AP mode will only enable if no WiFi connection could be made
    ssid: Car_AP
    password: !secret wifipass

api:

captive_portal:

ota:

web_server:
  port: 80

logger:
  level: VERBOSE

switch:
  - platform: gpio
    pin: D0
    id: red
  - platform: gpio
    pin: D1
    id: yellow
  - platform: gpio
    pin: D2
    id: green

sensor:
  - platform: dht
    pin: D5
    model: AM2302
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s
    
  - platform: ultrasonic
    id: car_sensor
    trigger_pin: D6
    echo_pin: D7
    name: "Ultrasonic Sensor"
    timeout: 3m
    update_interval: 0.5s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - lambda: |-
            if (id(car_sensor).state >= 1.0) {
              id(red).turn_off();
              id(yellow).turn_off();
              id(green).turn_off();
            }
            else if ((id(car_sensor).state >= 0.20) & (id(car_sensor).state < 1.0)) {
              id(red).turn_off();
              id(yellow).turn_on();
              id(green).turn_off();
            }
            else if ((id(car_sensor).state >= 0.15) & (id(car_sensor).state < 0.20)) {
              id(red).turn_off();
              id(yellow).turn_off();
              id(green).turn_on();
            }
            else if ((id(car_sensor).state < 0.15)) {
              id(red).turn_on();
              id(yellow).turn_off();
              id(green).turn_off();
            }
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/car.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing car (board: nodemcuv2; framework: arduino; platform: platformio/espressif8266 @ 2.6.2)
--------------------------------------------------------------------------------
Platform Manager: Installing platformio/espressif8266 @ 2.6.2
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Platform Manager: espressif8266 @ 2.6.2 has been installed!
The platform 'platformio/espressif8266 @ 2.6.2' has been successfully installed!
The rest of the packages will be installed later depending on your build environment.
Tool Manager: Installing toolchain-xtensa @ ~2.40802.191122
Tool Manager: Warning! More than one package has been found by toolchain-xtensa @ ~2.40802.191122 requirements:
 - platformio/toolchain-xtensa @ 2.100300.210717
 - mcspr/toolchain-xtensa @ 5.100300.210830
 - tasmota/toolchain-xtensa @ 5.100200.210303
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: toolchain-xtensa @ 2.40802.200502 has been installed!
Tool Manager: Installing platformio/framework-arduinoespressif8266 @ ~3.20704.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: framework-arduinoespressif8266 @ 3.20704.0 has been installed!
Tool Manager: Installing tool-esptool @ <2
Tool Manager: Warning! More than one package has been found by tool-esptool @ <2 requirements:
 - platformio/tool-esptool @ 1.413.0
 - volcas/tool-esptool @ 1.413.1
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-esptool @ 1.413.0 has been installed!
Tool Manager: Installing tool-esptoolpy @ ~1.20800.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-esptoolpy @ 1.20800.0 has been installed!
Tool Manager: Installing platformio/tool-scons @ ~4.40200.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: tool-scons @ 4.40200.0 has been installed!
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.3.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266WiFi> 1.0
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <noise-c> 0.1.3
|   |-- <libsodium> 1.10018.1
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/car/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-lx106-elf-g++: Permission denied
Compiling .pioenvs/car/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: xtensa-lx106-elf-g++: Permission denied
Compiling .pioenvs/car/src/esphome/components/api/api_pb2.cpp.o
sh: 1: xtensa-lx106-elf-g++: Permission denied
Compiling .pioenvs/car/src/esphome/components/api/api_pb2_service.cpp.o
sh: 1: xtensa-lx106-elf-g++: Permission denied
Compiling .pioenvs/car/src/esphome/components/api/api_server.cpp.o
sh: 1: xtensa-lx106-elf-g++: Permission denied
Compiling .pioenvs/car/src/esphome/components/api/list_entities.cpp.o
sh: 1: xtensa-lx106-elf-g++: Permission denied
Compiling .pioenvs/car/src/esphome/components/api/proto.cpp.o
sh: 1: xtensa-lx106-elf-g++: Permission denied
*** [.pioenvs/car/src/esphome/components/api/api_connection.cpp.o] Error 126
*** [.pioenvs/car/src/esphome/components/api/api_frame_helper.cpp.o] Error 126
*** [.pioenvs/car/src/esphome/components/api/api_pb2.cpp.o] Error 126
*** [.pioenvs/car/src/esphome/components/api/api_pb2_service.cpp.o] Error 126
*** [.pioenvs/car/src/esphome/components/api/api_server.cpp.o] Error 126
Compiling .pioenvs/car/src/esphome/components/api/subscribe_state.cpp.o
*** [.pioenvs/car/src/esphome/components/api/list_entities.cpp.o] Error 126
*** [.pioenvs/car/src/esphome/components/api/proto.cpp.o] Error 126
sh: 1: xtensa-lx106-elf-g++: Permission denied
*** [.pioenvs/car/src/esphome/components/api/subscribe_state.cpp.o] Error 126
========================= [FAILED] Took 127.96 seconds =========================
```
