### ISSUE TITLE
A/C control through AUX of heatpumpir works wrong

### ISSUE THREAD

**Issue by Aculeasis** [esphome/issues#2596]
### The problem

I have the A/C with the remote YKR-P/002E, what is named as UAX in heatpumpir library. I added the climate control, but it works with many problems. I think it is a sort of offset problem, because when I set 32C the remote sends 16C and 31C sends as 23C (default value) — 32 >> 1 = 16, 31 >> 1 = 15 and heatpumpir doesn't accept temp less than 16.

Found problems:
- Temp is always set 23 or 16 if 32 set.
- Swing mode messed up: Off works as Both and Both as Off. I need to keep Both for stop moving.
- Fan mode messed up: low sets medium, medium sets high, high sets auto.
- Auto mode (heat_cool) additional sets power off.

### Which version of ESPHome has the issue?

2021.10.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

nodemcu-like

### Component causing the issue

climate

### Example YAML snippet

```yaml
esphome:
  name: test
  platform: ESP8266
  board: esp01_1m

remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 30 # 50
  
climate:
  - platform: heatpumpir       # adjust to match your AC unit!
    name: "Living Room AC"
    protocol: aux
    horizontal_default:  auto
    vertical_default: auto
    min_temperature: 16
    max_temperature: 32
```

### Additional information

You can use tasmota-IR for debugging and testing, IRHVAC works correct for sending and reciving (ELECTRA_AC is AUX). For example:
```
{"IrReceived":{"Protocol":"ELECTRA_AC","Bits":104,"Data":"0xC37FE000A000C00000200008AA","Repeat":0,"IRHVAC":{"Vendor":"ELECTRA_AC","Model":-1,"Mode":"fan_only","Power":"On","Celsius":"On","Temp":23,"FanSpeed":"Auto","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}}}
{"IrReceived":{"Protocol":"ELECTRA_AC","Bits":104,"Data":"0xC37FE000A0008000002000086A","Repeat":0,"IRHVAC":{"Vendor":"ELECTRA_AC","Model":-1,"Mode":"Heat","Power":"On","Celsius":"On","Temp":23,"FanSpeed":"Auto","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}}}
{"IrReceived":{"Protocol":"ELECTRA_AC","Bits":104,"Data":"0xC37F0000A000C00000200008CA","Repeat":0,"IRHVAC":{"Vendor":"ELECTRA_AC","Model":-1,"Mode":"fan_only","Power":"On","Celsius":"On","Temp":23,"FanSpeed":"Auto","SwingV":"Off","SwingH":"Auto","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1}}}
```

While SwingX is auto, swing keep moving, off - stop.
