### ISSUE TITLE
First byte of encrypted telegram should be 0xDB

### ISSUE THREAD

**Issue by theFeverDog** [esphome/issues#2600]
### The problem

After updating to ESPHome 2021.10, the DSMR component does not seem to decrypt data from the P1 port correctly any longer, as I get the following error message:

> [E][dsmr:090]: First byte of encrypted telegram should be 0xDB, aborting.

The integration worked correctly with version 2021.09.x.
The decryption key is set in the secret.yaml. Updating the key using the service call ESPHome: slimmelezer_set_dsmr_key does also not work.

### Which version of ESPHome has the issue?

2021.10.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

slimeleezer

### Component causing the issue

DSMR

### Example YAML snippet

```yaml
uart:
  baud_rate: 115200
  rx_pin: D7

dsmr:
  id: dsmr_instance
  # For Luxembourg users set here your decryption key
  decryption_key: !secret decryption_key
```

### Anything in the logs that might be useful for us?

```txt
Only one error message is reported over and over in the log:

[E][dsmr:090]: First byte of encrypted telegram should be 0xDB, aborting.
```

### Additional information

This is using a Luxembourgish smart-meter, so the data of the P1 port is encrypted.
