### ISSUE TITLE
Nextion textbox not updating

### ISSUE THREAD

**Issue by lexam79** [esphome/issues#2608]
### The problem

Hello,

I have a Nextion screen (NX3224T024_011R) hooked up to a Wemos D1. It's been working fine for a few years now. A couple of days ago, I updated ESPHome to the latest version (v2021.10.2) and updated all my nodes too. Since then, my Nextion screen stopped working properly. While the 5 buttons I have on the screen work find (button presses are properly detected and actions triggered in Home Assistant fine), the one textbox I have is not updating (it keeps showing the placeholder I have programmed through the Nextion Editor).

The ESPHome code is this:

display:
  - platform: nextion
    id: nextion_display
    uart_id: soft_uart
    update_interval: 5s
    lambda: |-
      it.set_wait_for_ack(false);
      it.set_component_text("txtTemp", "test");

I've tried everything I could think of, to no avail. Any ideas?

Thank you

### Which version of ESPHome has the issue?

v2021.10.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.10.4

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

Nextion

### Example YAML snippet

```yaml
display:
  - platform: nextion
    id: nextion_display
    uart_id: soft_uart
    update_interval: 5s
    lambda: |-
      it.set_wait_for_ack(false);
      it.set_component_text("txtTemp", "test");
```

**Comment by jsuanet** [comment]
@lexam79 I have the same problem, you closed this issue, so what was the solution?

**Comment by lexam79** [comment]
@jsuanet, honestly, I'm not sure. I think that what fixed it was the fact that I removed the following lines from my sketch, which were not used anyway:

```
globals:
 - id: first_page             # First page of the display?
   type: bool
   restore_value: no
   
 - id: current_brightness             # Is display on?
   type: int
   restore_value: no
   initial_value: '-1'
```

I also removed the line:

`it.set_wait_for_ack(false);`

but I don't think that was it
