### ISSUE TITLE
ESP32-C3  ir can’t receiver anything 

### ISSUE THREAD

**Issue by liwei19920307** [esphome/issues#2612]
### The problem

ESP32-C3  ir can’t receive any ir code in web dubug log ,but use the same conf in ESP8266 work fine

### Which version of ESPHome has the issue?

2021.10.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32

### Board

esp_c3_13u

### Component causing the issue

remote_receiver:

### Example YAML snippet

```yaml
#esp32c3
remote_receiver:
  pin:
    number: 4
    inverted: true
  dump:
    - raw

#esp8266
remote_receiver:
  pin:
    number: 14
    inverted: true
  dump:
    - raw
```

### Additional information

IR Receiver Model：HX1838

**Comment by liwei19920307** [comment]
Try RF but still can't receive

````
remote_receiver:
  pin:
    number: 0
  dump:
    - rc_switch
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb
````
