### ISSUE TITLE
max31855 values shifted after updating ESPHome

### ISSUE THREAD

**Issue by theone11** [esphome/issues#2614]
### The problem

AFter updating my ESP device to 2021.10.2 (don't remember what version was before - maybe 1.16.2) my temperature sensors (sensing my water boiler pipes - in and out) have started reporting much higher (by +20 to 45C non linear) and not reasonable temperatures then just before the update (a few seconds later).

For example (see graph @9:13PM - time of update):
* From 50C to 95C
* From 30C to 60C

![image](https://user-images.githubusercontent.com/3348953/138567803-2c02a5a3-402c-4acf-bcb4-4629e845a456.png)

Also the internal reference temperature of the MAX31855 has jumped from room temperature of 25-30C to 52C.

Similar problem seems to be reported https://github.com/esphome/issues/issues/1676 by @NobleKangaroo

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

Custom

### Component causing the issue

max31855

### Example YAML snippet

```yaml
- platform: max31855
    name: "${friendly_name} Panel Out"
    id: panel_out
    cs_pin: GPIO01
    update_interval: 5s
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 3
    reference_temperature:
      id: panel_out_internal
      name: "${friendly_name} Panel Out Internal"
      filters:
        - median:
            window_size: 7
            send_every: 4
            send_first_at: 3
```
