### ISSUE TITLE
New ESPHome device not regsitering in ESPHome integration, but OTA programming and debug works fine

### ISSUE THREAD

**Issue by seanmahrt** [esphome/issues#2618]
### The problem

I flashed up a new node (Sonoff basic) and have had a strange issue where it doesn't actually seem to be registering with the rest of HomeAssistant.  ESPHome dashboard shows it fine, I can progam OTA and connect to the logger just fine.  I even cloned one of my existing module configs (that was created a year or so ago) and it still doesn't seem to register.

Did something change recently in the registration/detection mechanism?  I've never had this probem (usually fight with wifi or initial flashing issues).

I don't see anything wrong on the log on the device and the only thing in the log that seems weird is the following line.  It's possible it has always done this since I don't look at the logs unless it's broken.. :)

`2021-10-23 18:18:32,736 INFO 304 GET /devices (0.0.0.0) 3.54ms`

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.10.6

### What platform are you using?

ESP8266

### Board

Sonoff Basic

### Component causing the issue

???

### Example YAML snippet

```yaml
esphome:
  name: hottub
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "**"

wifi:
  ssid: "**"
  password: "**"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hottub Fallback Hotspot"
    password: "**"

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    name: "hottub_button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Hot Tub Pump"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF

status_led:
  pin:
    number: GPIO13
    inverted: yes
```

### Additional information

I have deleted the entry in ESPHome, and readded it by copying the code back in.  I didn't change the device/reprogram it to a new ID, as that really shouldn't be necessary.  I can ping hottub.local from within HomeAssistant, so it's not a DNS resolution issue.
