### ISSUE TITLE
Power board with low voltage on mains power points when switched on

### ISSUE THREAD

**Issue by marvin8** [esphome/issues#2619]
### The problem

When I run my ESPHome config on my Vivitar HA-1007-AU power board (see at the end of this post) all the relay’s seem to be switching ok, all the status LEDs seem to be working as expected however instead of full mains voltage on the power points I only get in the order of 35-40 V AC…

Does not seem to be a hardware issue as when I flash this power board with Tasmota with the [appropriate Tasmota template](https://templates.blakadder.com/vivitar_HA-1007-AU.html) voltage on the powerpoints is ~240V AC as expected.

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP8266

### Board

esp8285

### Component causing the issue

switch

### Example YAML snippet

```yaml
substitutions:
  location: shed1
  pretty_location: Shed Powerboard 1

esphome:
  name: kogan-vivitar-${location}
  platform: ESP8266
  board: esp8285

packages:
  wifi: !include common-wifi.yaml

api:

logger:

ota:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO01
      mode: INPUT_PULLUP
      inverted: true
    name:  ${pretty_location} Button
    on_press:
      - switch.toggle: socket1
      - switch.toggle: socket2
      - switch.toggle: socket3
      - switch.toggle: socket4
      - switch.toggle: usb
  - platform: status
    name: ${pretty_location} Status


switch:
  - platform: gpio
    name: ${pretty_location} Socket 1 Relay
    pin: GPIO04
    inverted: True
    id: socket1
  - platform: gpio
    name: ${pretty_location} Socket 2 Relay
    pin: GPIO13
    id: socket2
    inverted: True
  - platform: gpio
    name: ${pretty_location} Socket 3 Relay
    pin: GPIO12
    inverted: True
    id: socket3
  - platform: gpio
    name: ${pretty_location} Socket 4 Relay
    pin: GPIO14
    inverted: True
    id: socket4
  - platform: gpio
    name: ${pretty_location} USB Relay
    pin: GPIO16
    id: usb
```

### Anything in the logs that might be useful for us?

```txt
none
```
