### ISSUE TITLE
mdns provides a response for 1min then fails.

### ISSUE THREAD

**Issue by amerikiwi93** [esphome/issues#2623]
### The problem

ESP8226 responds to mdns (ss01s-light.local) requests after a few seconds then goes does not respond. Cannot download from addon, however lovelace works. Requres `use_address: 192.168.1.123` in the wifi section.

Immediately after the update:
```
root@OpenWrt:~# avahi-browse --resolve -at
...
= br-lan IPv4 ss01s-light                            _esphomelib._tcp     local
   hostname = [ss01s-light.local]
   address = [192.168.1.173]
   port = [6053]
   txt = ["version=2021.10.2" "mac=8cce4eef67d3" "platform=ESP8266" "board=esp01_1m"]
...
root@OpenWrt:~#
```

Approx 1min later
```
root@OpenWrt:~# avahi-browse --resolve -at
...
Failed to resolve service 'ss01s-light' of type '_esphomelib._tcp' in domain 'local': Timeout reached
...
root@OpenWrt:~#
```

Might be related to #2616 or "Fix MDNS for ESP8266 devices 2571"

### Which version of ESPHome has the issue?

2021.10.X

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

treatlife-ss01s

### Component causing the issue

mdns

### Example YAML snippet

```yaml
wifi:
  ssid: !secret wifi_ssid #wifi_iot_ssid
  password: !secret wifi_password #wifi_iot_password
  
  ap:
    ssid: ${device_name} AP
    password: !secret esphome_fallback_ap_password

  #use temporary static address for uploads
   use_address: 192.168.1.123
  
#enable WiFi hotspot after 1min of no wifi connectivity
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password
```

### Additional information

Only have ESP8226 devices to test on.
