### ISSUE TITLE
Can not compile anymore with ESP32 project

### ISSUE THREAD

**Issue by Micha70** [esphome/issues#2626]
### The problem

Since recent update of ESPHome I get a failure during compiling my ESP32 cam application.

`Generating partitions /data/esp32_cam/.pioenvs/esp32_cam/partitions.bin
/usr/bin/python3: can't open file '/data/cache/platformio/packages/framework-arduinoespressif32/tools/gen_esp32part.py': [Errno 2] No such file or directory
Compiling /data/esp32_cam/.pioenvs/esp32_cam/lib528/AsyncTCP-esphome/AsyncTCP.cpp.o
*** [/data/esp32_cam/.pioenvs/esp32_cam/partitions.bin] Error 2
`

### Which version of ESPHome has the issue?

V2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.5

### What platform are you using?

ESP32

### Board

ESP32 Cam

### Example YAML snippet

```yaml
esphome:
  name: esp32_cam
  platform: ESP32
  #board: esp32dev
  board: esp32cam
  #enable low power mode if WLAN is off
  on_boot:
    then:
      - delay: 40s
      - if:
          condition:
            not:
              wifi.connected:
          then:
            - deep_sleep.enter: deep_sleep_1
  

wifi:
  ssid: !secret myssid
  password: !secret mywifipassword
  # ...
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.178.71
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0 



  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Cam Fallback Hotspot"
    password: "XXX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


switch:
#  - platform: gpio
#    name: "blueLEDESPHome"
#    pin: 2
#    id: blueLEDESPHome
#    inverted: True
    

deep_sleep:
# ...
  id: deep_sleep_1
  run_duration: 20s
  sleep_duration: 10min
mqtt:
  # ...
  broker: 192.168.178.50
  username: !secret mqtt_username
  password: !secret mqtt_passwort
  birth_message:
  will_message:
  on_message:
    - topic: esp32_cam/ota_mode
      payload: 'ON'
      then:
      #  - light.turn_on: ESP32CamLight
        - deep_sleep.prevent: deep_sleep_1
        - mqtt.publish:
            topic: esp32_cam/ota_state
            payload: "active"
            qos: 1


    - topic: esp32_cam/ota_mode
      payload: 'OFF'
      then:
        #- light.turn_off: ESP32CamLight
        - output.set_level:
            id: esp32cam_light
            level: "0%"
        - mqtt.publish:
            topic: esp32_cam/ota_state
            payload: "inactive"
            qos: 1
        - delay: 2s
        - deep_sleep.enter: deep_sleep_1


esp32_camera:
  name: esp32_cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32


binary_sensor:
  - platform: status
    name: "ESP32Cam YT status"
    
sensor:
  - platform: wifi_signal
    name: "ESP32Cam YT WiFi Signal"
    update_interval: 60s
  - platform: adc
    pin: GPIO33
    name: "SupplyVoltage"
    filters:
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.0
          - 0.8 -> 3.804
          - 1.0 -> 4.8846
    update_interval: 5s

    
    
output:
  - platform: ledc
    pin: GPIO4
    channel: 2 # channel 1 is used for esp32_camera
    id: esp32cam_light
    inverted: false
light:
  - platform: monochromatic
    output: esp32cam_light
    name: "ESP32CamLight"
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esp32_cam.yaml...
WARNING 'esp32_cam': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
INFO Generating C++ source...
INFO Compiling app...
Processing esp32_cam (board: esp32cam; framework: arduino; platform: espressif32 @ 3.3.2)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <WiFi> 1.0
|-- <FS> 1.0
|-- <Update> 1.0
|-- <ESPAsyncWebServer-esphome> 2.0.0
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <DNSServer> 1.1.0
|-- <AsyncMqttClient-esphome> 0.8.6
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESPmDNS> 1.0
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/adc/adc_sensor.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/api/api_connection.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/api/api_pb2_service.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/api/api_server.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/api/list_entities.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/api/proto.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/api/user_services.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/api/util.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/binary_sensor/automation.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/binary_sensor/filter.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/deep_sleep/deep_sleep_component.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/esp32/core.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/esp32/gpio_arduino.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/esp32/gpio_idf.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/esp32/preferences.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/esp32_camera/esp32_camera.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/json/json_util.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/ledc/ledc_output.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/light/addressable_light.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/light/automation.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/light/esp_color_correction.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/light/esp_hsv_color.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/light/esp_range_view.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/light/light_call.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/light/light_json_schema.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/light/light_output.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/light/light_state.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/logger/logger.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/md5/md5.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mdns/mdns_component.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mdns/mdns_esp32_arduino.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mdns/mdns_esp_idf.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/custom_mqtt_device.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_binary_sensor.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_client.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_climate.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_component.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_cover.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_fan.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_light.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_number.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_select.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_sensor.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_switch.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/mqtt/mqtt_text_sensor.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/network/util.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/ota/ota_component.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/output/automation.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/output/float_output.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/sensor/automation.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/sensor/filter.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/sensor/sensor.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/status/status_binary_sensor.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/switch/automation.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/switch/switch.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/wifi/wifi_component.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/components/wifi_signal/wifi_signal_sensor.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/core/application.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/core/color.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/core/component.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/core/controller.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/core/entity_base.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/core/helpers.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/core/log.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/core/scheduler.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/esphome/core/util.cpp.o
Compiling /data/esp32_cam/.pioenvs/esp32_cam/src/main.cpp.o
Generating partitions /data/esp32_cam/.pioenvs/esp32_cam/partitions.bin
/usr/bin/python3: can't open file '/data/cache/platformio/packages/framework-arduinoespressif32/tools/gen_esp32part.py': [Errno 2] No such file or directory
Compiling /data/esp32_cam/.pioenvs/esp32_cam/lib528/AsyncTCP-esphome/AsyncTCP.cpp.o
*** [/data/esp32_cam/.pioenvs/esp32_cam/partitions.bin] Error 2
========================= [FAILED] Took 529.83 seconds =========================
```
