### ISSUE TITLE
OTA flash failure when software UART receives data during flash

### ISSUE THREAD

**Issue by DAVe3283** [esphome/issues#2629]
### The problem

After updating from 2021.9.3 to 2021.10.1, the ESP8266 will reboot during an OTA flash if receiving data on a software UART.

* If I disconnect the software RX pin, the flash completes successfully.
* If I use the hardware UART, the flash completes successfully even when receiving UART data.
* Version 2021.9.3 does not have this problem. 2021.10.1 and 2021.10.2 do have the problem. 

If it matters, the data received is from a PMS7003 ([PMSX003 component](https://esphome.io/components/sensor/pmsx003.html)), but the reboot + OTA failure occurs with just a UART and no sensors defined. See YAML below-- that exact YAML will replicate the OTA crash.

In this application, we need 2 UARTs, so even if we swap the PMS7003 to the hardware UART, then the other component runs the risk of crashing an OTA if it sends an update.

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

UART

### Example YAML snippet

```yaml
esphome:
  name: haks-test
  platform: ESP8266
  board: d1_mini

logger:
  level: VERBOSE

api:
  password: "cd8c22eeaa2ae263b303aec49206103f"

ota:
  password: "cd8c22eeaa2ae263b303aec49206103f"

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_pass
  domain: !secret iot_domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Haks-Test Fallback Hotspot"
    password: "cl766zRGasfA"

captive_portal:

uart:
  - id: uart_pms
    rx_pin: D5
    baud_rate: 9600
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/haks-test.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing haks-test (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.3.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <noise-c> 0.1.3
|   |-- <libsodium> 1.10018.1
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling /data/haks-test/.pioenvs/haks-test/src/main.cpp.o
Linking /data/haks-test/.pioenvs/haks-test/firmware.elf
Retrieving maximum program size /data/haks-test/.pioenvs/haks-test/firmware.elf
Checking size /data/haks-test/.pioenvs/haks-test/firmware.elf
Building /data/haks-test/.pioenvs/haks-test/firmware.bin
RAM:   [====      ]  39.0% (used 31984 bytes from 81920 bytes)
Flash: [====      ]  39.1% (used 408184 bytes from 1044464 bytes)
Creating BIN file "/data/haks-test/.pioenvs/haks-test/firmware.bin" using "/data/cache/platformio/packages/framework-arduinoespressif8266/bootloaders/eboot/eboot.elf" and "/data/haks-test/.pioenvs/haks-test/firmware.elf"
========================= [SUCCESS] Took 4.24 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of haks-test.****
INFO  -> 192.168.0.105
INFO Uploading /data/haks-test/.pioenvs/haks-test/firmware.bin (412336 bytes)
Uploading: [=========                                                   ] 15% 
ERROR Error sending data: [Errno 104] Connection reset by peer
```

**Comment by snh** [comment]
I too am experiencing this problem, in my case with a configuration similar to https://www.esphome-devices.com/devices/AirGradient-DIY.

**Comment by MallocArray** [comment]
Same here!  I'm doing the same project with AirGradient DIY with ESPHome and can flash it fine with USB, but if I try to update OTA, the device is rebooting mid flash.  I thought it may be due to the PMS5003 sending updates every second, so I tried to comment out the sensor, but I had left the UART section enabled.

Last night I downgraded esphome container to 1.18.00 and after flashing over USB I can now do OTA successfully. (Note: I did have to change my config file from .yml to .yaml for 1.18.0 to detect it.  

I thought it might be related to:
https://github.com/esphome/issues/issues/2309
as it see the same illegal instruction message, but I had tried disabling the captive portal and tweaking the output_power to 17.5db without any improvement on 2021.10.3

I have a very similar yaml file for the D1 Mini hardware setup mentioned by the OP

```yaml
esphome:
  name: airgradient-basement
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  # https://esphome.io/components/wifi.html
  ssid: "MiWiFiFyi"
  password: "NachoPassword"
  output_power: 17.5db


  # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "air-basement"
#     password: "asdf"
# captive_portal:

uart:
  # https://esphome.io/components/uart.html#uart
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: senseair_s8_uart

  - rx_pin: D5
    baud_rate: 9600
    id: pms5003_uart

i2c:
  sda: D2
  scl: D1

sensor:
  - platform: pmsx003
    # https://esphome.io/components/sensor/pmsx003.html?highlight=pms5003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
      id: pm1
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
      id: pm2
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
      id: pm10
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30
    uart_id: pms5003_uart

  - platform: senseair
    # https://esphome.io/components/sensor/senseair.html
    co2:
      name: "SenseAir S8 CO2 Value"
      id: co2
    update_interval: 30s
    uart_id: senseair_s8_uart

  # - platform: sht3xd
  #   # https://esphome.io/components/sensor/sht3xd.html?highlight=sht31
  #   # This may not work as mine is not a -d model
  #   temperature:
  #     name: "AirGradient Temperature"
  #   humidity:
  #     name: "AirGradient Humidity"
  #   address: 0x44
  #   update_interval: 60s



font:
  - file: './fonts/arial.ttf'
    id: font1
    size: 24

display:
  - platform: ssd1306_i2c
    # https://esphome.io/components/display/ssd1306.html?highlight=display
    model: "SSD1306 64x48"
    id: oled_display
    reset_pin: D0
    address: 0x3C
    pages:
      - id: display_pm2
        lambda: |-
          it.print(0, 0, id(font1), "PM2");
          it.printf(64, 24, id(font1), TextAlign::TOP_RIGHT, "%.0f",id(pm2).state);
      - id: display_co2
        lambda: |-
          it.print(0, 0, id(font1), "CO2");
          it.printf(64, 24, id(font1), TextAlign::TOP_RIGHT, "%.0f",id(co2).state);

# cycle through display pages on a timer
interval:
  - interval: 5s
    then:
      - display.page.show_next: oled_display
      - component.update: oled_display

```
