### ISSUE TITLE
Error with multiple SN74HC595

### ISSUE THREAD

**Issue by hirani89** [esphome/issues#2631]
### The problem

I have 2 shift registers controlling 16 relays. I get errors on the `number` part of the `pin` for the second shift register.
This was working fine until a few updates ago. I thought updating to the latest should fix this. But the issue remains.

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

D1 Mini Pro

### Component causing the issue

sn74hc595

### Example YAML snippet

```yaml
esphome:
  name: 16ch-relay
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi
  password: !secret wifi_pass
  fast_connect: true
  manual_ip:
    static_ip: 192.168.20.21
    gateway: 192.168.20.1
    subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "16Ch-Relay Fallback Hotspot"
    password: !secret ota_pass

captive_portal:

sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: D1
    clock_pin: D0
    latch_pin: D2
    sr_count: 2
    
switch:
  - platform: gpio
    name: "Relay 1"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 0
      # inverted: true
  - platform: gpio
    name: "Relay 2"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 1
      # inverted: true
  - platform: gpio
    name: "Relay 3"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 2
      # inverted: true
  - platform: gpio
    name: "Relay 4"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 3
      # inverted: true
  - platform: gpio
    name: "Relay 5"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 4
      # inverted: true
  - platform: gpio
    name: "Relay 6"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 5
      # inverted: true
  - platform: gpio
    name: "Relay 7"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 6
      # inverted: true
  - platform: gpio
    name: "Relay 8"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 7
      # inverted: true
  - platform: gpio
    name: "Relay 9"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 8
      # inverted: true
  - platform: gpio
    name: "Relay 10"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 9
      # inverted: true
  - platform: gpio
    name: "Relay 11"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 10
      # inverted: true
  - platform: gpio
    name: "Relay 12"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 11
      # inverted: true
  - platform: gpio
    name: "Relay 13"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 12
      # inverted: true
  - platform: gpio
    name: "Relay 14"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 13
      # inverted: true
  - platform: gpio
    name: "Relay 15"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 14
      # inverted: true
  - platform: gpio
    name: "Relay 16"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 15
      # inverted: true
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/16ch-relay.yaml...
Failed config

switch.gpio: [source /config/esphome/16ch-relay.yaml:95]
  platform: gpio
  name: Relay 9
  pin:  [source /config/esphome/16ch-relay.yaml:98]
    sn74hc595: sn74hc595_hub
    
    value must be at most 7.
    number: 8 [source /config/esphome/16ch-relay.yaml:100]
switch.gpio: [source /config/esphome/16ch-relay.yaml:102]
  platform: gpio
  name: Relay 10
  pin:  [source /config/esphome/16ch-relay.yaml:105]
    sn74hc595: sn74hc595_hub
    
    value must be at most 7.
    number: 9 [source /config/esphome/16ch-relay.yaml:107]
switch.gpio: [source /config/esphome/16ch-relay.yaml:109]
  platform: gpio
  name: Relay 11
  pin:  [source /config/esphome/16ch-relay.yaml:112]
    sn74hc595: sn74hc595_hub
    
    value must be at most 7.
    number: 10 [source /config/esphome/16ch-relay.yaml:114]
switch.gpio: [source /config/esphome/16ch-relay.yaml:116]
  platform: gpio
  name: Relay 12
  pin:  [source /config/esphome/16ch-relay.yaml:119]
    sn74hc595: sn74hc595_hub
    
    value must be at most 7.
    number: 11 [source /config/esphome/16ch-relay.yaml:121]
switch.gpio: [source /config/esphome/16ch-relay.yaml:123]
  platform: gpio
  name: Relay 13
  pin:  [source /config/esphome/16ch-relay.yaml:126]
    sn74hc595: sn74hc595_hub
    
    value must be at most 7.
    number: 12 [source /config/esphome/16ch-relay.yaml:128]
switch.gpio: [source /config/esphome/16ch-relay.yaml:130]
  platform: gpio
  name: Relay 14
  pin:  [source /config/esphome/16ch-relay.yaml:133]
    sn74hc595: sn74hc595_hub
    
    value must be at most 7.
    number: 13 [source /config/esphome/16ch-relay.yaml:135]
switch.gpio: [source /config/esphome/16ch-relay.yaml:137]
  platform: gpio
  name: Relay 15
  pin:  [source /config/esphome/16ch-relay.yaml:140]
    sn74hc595: sn74hc595_hub
    
    value must be at most 7.
    number: 14 [source /config/esphome/16ch-relay.yaml:142]
switch.gpio: [source /config/esphome/16ch-relay.yaml:144]
  platform: gpio
  name: Relay 16
  pin:  [source /config/esphome/16ch-relay.yaml:147]
    sn74hc595: sn74hc595_hub
    
    value must be at most 7.
    number: 15 [source /config/esphome/16ch-relay.yaml:149]
```
