### ISSUE TITLE
Scheduler deadlock

### ISSUE THREAD

**Issue by 5tan** [esphome/issues#2632]
### The problem

I can very easily put scheduler into a "deadlock state" using REST requests to the web server. In "deadlock state" scheduler won't dispatch any new REST requests (not even reboot request).

To reproduce the issue please compile & run attached yaml. Then start periodic requests to the web server: `while [ true ] ; do curl http://192.168.0.15/switch/my_switch/toggle -i -X POST  ; done`. Scheduler deadlock will happen in a few minutes.

Here is a demo video: https://user-images.githubusercontent.com/15819543/138690910-0db82fb3-50f8-45d8-ba38-2cd142b4f402.mp4 Deadlock happens at 02:46.

---

I have added a following log to diagnose the issue: 
```
diff --git a/usr/local/lib/python3.8/dist-packages/esphome/core/scheduler.cpp_ b/usr/local/lib/python3.8/dist-packages/esphome/core/scheduler.cpp
index a6d3e03..7efe953 100644
--- a/usr/local/lib/python3.8/dist-packages/esphome/core/scheduler.cpp_
+++ b/usr/local/lib/python3.8/dist-packages/esphome/core/scheduler.cpp
@@ -198,6 +198,7 @@ void HOT Scheduler::process_to_add() {
 
     this->items_.push_back(std::move(it));
     std::push_heap(this->items_.begin(), this->items_.end(), SchedulerItem::cmp);
+    ESP_LOGI(TAG, "queue size is %d", this->items_.size());
   }
   this->to_add_.clear();
 }
```
Here is a video showing the logs: https://user-images.githubusercontent.com/15819543/138692401-e2ccda85-eb6f-4677-a0ed-f686ea2a8a5f.mp4 Issue happens at 02:34. As you can see no more items from the queue/heap are being dispatched/popped. 

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

nodemcu-32s / Espressif ESP32-DevKitC-32E

### Component causing the issue

core/scheduler

### Example YAML snippet

```yaml
esphome:
  name: scheduler-esp32
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO

ota:

web_server:
  port: 80

interval:
  - interval: 1s
    then:
      - logger.log:
          format: "hello from interval"
          level: INFO

globals:
  - id: my_switch_status
    type: bool
    restore_value: no
    initial_value: "false"

script:
  - id: my_script
    mode: restart
    then:
      - logger.log:
          format: "hello from my script :)"
          level: INFO

switch:
  - platform: template
    id: my_switch
    name: my_switch
    lambda: return id(my_switch_status);
    turn_on_action:
      - script.execute: my_script
      - lambda: id(my_switch_status) = true;
    turn_off_action:
      - script.execute: my_script
      - lambda: id(my_switch_status) = false;
  - platform: restart
    name: reboot
```

### Additional information

Issue is very easy to reproduce within a few minutes on ESP32, but I was unable to reproduce it on ESP8266/sonoff_sv!
