### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by amblyo** [esphome/issues#2633]
### The problem

After update i cant compile anything...

Tried to setup a test device and get the same error.

Get error below when trying to compile this test config.

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
esphome:
  name: test
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "8f72efa1eb1f490720828d95d091543f"

wifi:
  ssid: "****"
  password: "****"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "wzWRUnmtWQOW"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/test.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing test (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 2.0.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <noise-c> 0.1.4
|   |-- <libsodium> 1.10018.1
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Error: Could not find 'eagle.flash.4m.ld' LD script in LDPATH '/data/test/.pioenvs/test /data/test/.pioenvs/test/ld /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/lib /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/ld /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/lib /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/lib/NONOSDK22x_190703'
Error: Could not find 'eagle.flash.4m.ld' LD script in LDPATH '/data/test/.pioenvs/test /data/test/.pioenvs/test/ld /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/lib /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/ld /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/lib /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/lib/NONOSDK22x_190703'
========================== [FAILED] Took 2.03 seconds ==========================
```

**Comment by amblyo** [comment]
Did a update to v2021.11.1 but no luck.

Tried with a esp32 and got no error.
Tried to compile a new esp8266 and got the same error.

INFO Reading configuration /config/esphome/test-esp8266.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing test-esp8266 (board: esp01_1m; framework: arduino; platform: platformio/espressif8266 @ 2.6.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
Error: Could not find 'eagle.flash.1m.ld' LD script in LDPATH '/data/test-esp8266/.pioenvs/test-esp8266 /data/test-esp8266/.pioenvs/test-esp8266/ld /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/lib /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/ld /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/lib /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/lib/NONOSDK22x_190703'
Error: Could not find 'eagle.flash.1m.ld' LD script in LDPATH '/data/test-esp8266/.pioenvs/test-esp8266 /data/test-esp8266/.pioenvs/test-esp8266/ld /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/lib /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/ld /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/lib /data/cache/platformio/packages/framework-arduinoespressif8266/tools/sdk/lib/NONOSDK22x_190703'
========================== [FAILED] Took 1.63 seconds ==========================

**Comment by mmakaay** [comment]
I've never seen this happen myself.
Can you share a minimal YAML configuration for which this is happening for you?

**Comment by amblyo** [comment]
This is a minimum yaml.

```
esphome:
  name: test-esp8266
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "0275f76b71bd3e2d347a9082c5383242"

wifi:
  ssid: "test"
  password: "testtest"
```
I get the same error on all my other configs that use esp8266.
