### ISSUE TITLE
Compilation problems when I'm trying to install from home assistant

### ISSUE THREAD

**Issue by yannickt** [esphome/issues#2639]
### The problem

I'm use ESPHome with home assistant. Since 2021.10.02 update, when I compile the code of component "teleinfo", i've got some errors. The compliation works well with the previous version (2021.09.?).

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.10.6

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

teleinfo

### Example YAML snippet

```yaml
esphome:
  name: linky
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "___"

wifi:
  ssid: "___"
  password: "___"
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Linky Fallback Hotspot"
    password: "___"

captive_portal:

#setup uart between the linky and the ESP
# historique : 1200
# linky : 9600
uart:
  id: uart_bus
  rx_pin: D7
  tx_pin: D6
  baud_rate: 1200
  parity: EVEN
  data_bits: 7


#setup teleinfo, update valut every 60s
teleinfo:
  id: myteleinfo
  update_interval: 60s
  historical_mode: true

sensor:
  #Linky HC value
  - platform: teleinfo
    tag_name: "HCHC"
    name: "Linky HC"
    teleinfo_id: myteleinfo
    state_class: "measurement"
    device_class: "energy"
    unit_of_measurement: "Wh"
  
  #Linky HP value
  - platform: teleinfo
    tag_name: "HCHP"
    name: "Linky HP"
    teleinfo_id: myteleinfo
    state_class: "measurement"
    device_class: "energy"
    unit_of_measurement: "Wh"

  
  #Linky Consumption
  - platform: teleinfo
    tag_name: "PAPP"
    name: "Linky Consommation"
    unit_of_measurement: "VA"
    icon: mdi:flash
    teleinfo_id: myteleinfo
    
   #Linky Intensity
  - platform: teleinfo
    tag_name: "IINST"
    name: "Linky Intensité"
    unit_of_measurement: "A"
    icon: mdi:flash
    teleinfo_id: myteleinfo
    
text_sensor:
  - platform: teleinfo
    tag_name: "OPTARIF"
    name: "optarif"
    teleinfo_id: myteleinfo
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/linky.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing linky (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 2.0.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <noise-c> 0.1.4
|   |-- <libsodium> 1.10018.1
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling /data/linky/.pioenvs/linky/src/esphome/components/teleinfo/sensor/teleinfo_sensor.cpp.o
Compiling /data/linky/.pioenvs/linky/src/esphome/components/teleinfo/text_sensor/teleinfo_text_sensor.cpp.o
Compiling /data/linky/.pioenvs/linky/src/esphome/components/text_sensor/filter.cpp.o
Compiling /data/linky/.pioenvs/linky/src/esphome/components/text_sensor/text_sensor.cpp.o
In file included from src/esphome/components/teleinfo/text_sensor/teleinfo_text_sensor.cpp:1:0:
src/esphome/components/teleinfo/text_sensor/teleinfo_text_sensor.cpp: In member function 'virtual void esphome::teleinfo::TeleInfoTextSensor::dump_config()':
src/esphome/core/log.h:194:57: error: initializer fails to determine size of '__c'
 #define LOG_STR(s) (reinterpret_cast<const LogString *>(PSTR(s)))
                                                         ^
src/esphome/core/log.h:97:90: note: in definition of macro 'esph_log_config'
   esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                          ^
src/esphome/components/text_sensor/text_sensor.h:13:5: note: in expansion of macro 'ESP_LOGCONFIG'
     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
     ^
src/esphome/core/log.h:195:28: note: in expansion of macro 'LOG_STR_ARG'
 #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
                            ^
src/esphome/core/log.h:195:40: note: in expansion of macro 'LOG_STR'
 #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
                                        ^
src/esphome/components/text_sensor/text_sensor.h:13:45: note: in expansion of macro 'LOG_STR_LITERAL'
     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
                                             ^
src/esphome/components/teleinfo/text_sensor/teleinfo_text_sensor.cpp:9:42: note: in expansion of macro 'LOG_TEXT_SENSOR'
 void TeleInfoTextSensor::dump_config() { LOG_TEXT_SENSOR("  ", tag.c_str(), this); }
                                          ^
src/esphome/core/log.h:194:57: error: array must be initialized with a brace-enclosed initializer
 #define LOG_STR(s) (reinterpret_cast<const LogString *>(PSTR(s)))
                                                         ^
src/esphome/core/log.h:97:90: note: in definition of macro 'esph_log_config'
   esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                          ^
src/esphome/components/text_sensor/text_sensor.h:13:5: note: in expansion of macro 'ESP_LOGCONFIG'
     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); 
     ^
src/esphome/core/log.h:195:28: note: in expansion of macro 'LOG_STR_ARG'
 #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
                            ^
src/esphome/core/log.h:195:40: note: in expansion of macro 'LOG_STR'
 #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
                                        ^
src/esphome/components/text_sensor/text_sensor.h:13:45: note: in expansion of macro 'LOG_STR_LITERAL'
     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
                                             ^
src/esphome/components/teleinfo/text_sensor/teleinfo_text_sensor.cpp:9:42: note: in expansion of macro 'LOG_TEXT_SENSOR'
 void TeleInfoTextSensor::dump_config() { LOG_TEXT_SENSOR("  ", tag.c_str(), this); }
                                          ^
In file included from src/esphome/components/teleinfo/sensor/teleinfo_sensor.cpp:1:0:
src/esphome/components/teleinfo/sensor/teleinfo_sensor.cpp: In member function 'virtual void esphome::teleinfo::TeleInfoSensor::dump_config()':
src/esphome/core/log.h:194:57: error: initializer fails to determine size of '__c'
 #define LOG_STR(s) (reinterpret_cast<const LogString *>(PSTR(s)))
                                                         ^
src/esphome/core/log.h:97:90: note: in definition of macro 'esph_log_config'
   esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                          ^
src/esphome/components/sensor/sensor.h:14:5: note: in expansion of macro 'ESP_LOGCONFIG'
     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
     ^
src/esphome/core/log.h:195:28: note: in expansion of macro 'LOG_STR_ARG'
 #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
                            ^
src/esphome/core/log.h:195:40: note: in expansion of macro 'LOG_STR'
 #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
                                        ^
src/esphome/components/sensor/sensor.h:14:45: note: in expansion of macro 'LOG_STR_LITERAL'
     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
                                             ^
src/esphome/components/teleinfo/sensor/teleinfo_sensor.cpp:12:38: note: in expansion of macro 'LOG_SENSOR'
 void TeleInfoSensor::dump_config() { LOG_SENSOR("  ", tag.c_str(), this); }
                                      ^
src/esphome/core/log.h:194:57: error: array must be initialized with a brace-enclosed initializer
 #define LOG_STR(s) (reinterpret_cast<const LogString *>(PSTR(s)))
                                                         ^
src/esphome/core/log.h:97:90: note: in definition of macro 'esph_log_config'
   esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                          ^
src/esphome/components/sensor/sensor.h:14:5: note: in expansion of macro 'ESP_LOGCONFIG'
     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
     ^
src/esphome/core/log.h:195:28: note: in expansion of macro 'LOG_STR_ARG'
 #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
                            ^
src/esphome/core/log.h:195:40: note: in expansion of macro 'LOG_STR'
 #define LOG_STR_LITERAL(s) LOG_STR_ARG(LOG_STR(s))
                                        ^
src/esphome/components/sensor/sensor.h:14:45: note: in expansion of macro 'LOG_STR_LITERAL'
     ESP_LOGCONFIG(TAG, "%s%s '%s'", prefix, LOG_STR_LITERAL(type), (obj)->get_name().c_str()); \
                                             ^
src/esphome/components/teleinfo/sensor/teleinfo_sensor.cpp:12:38: note: in expansion of macro 'LOG_SENSOR'
 void TeleInfoSensor::dump_config() { LOG_SENSOR("  ", tag.c_str(), this); }
                                      ^
*** [/data/linky/.pioenvs/linky/src/esphome/components/teleinfo/sensor/teleinfo_sensor.cpp.o] Error 1
*** [/data/linky/.pioenvs/linky/src/esphome/components/teleinfo/text_sensor/teleinfo_text_sensor.cpp.o] Error 1
========================= [FAILED] Took 38.36 seconds =========================
```
