### ISSUE TITLE
Hassio Setup Wizard does not clean name string

### ISSUE THREAD

**Issue by nickdaria** [esphome/issues#264]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Hassio Stable

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP32

**Affected component:** esphome

**Description of problem:**
The setup wizard does not clean the name when adding the entity to the .YAML config. Under the esphome component, entries with spaces result in a validation error, so the setup wizard should automatically remove spaces from the name when filling in the name property of the esphome component.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: garagedoor
  platform: ESP8266
  board: nodemcuv2
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
