### ISSUE TITLE
Deepsleep with wakeup_pin_mode: INVERT_WAKEUP prevents sleep 

### ISSUE THREAD

**Issue by Ralphy140** [esphome/issues#2641]
### The problem

Using MQTT with Deepsleep and a pin to wakeup an ESP32 where the pin state may change and stay changed for a long time. If the wakeup_pin_mode: INVERT_WAKEUP is set the device will not enter deepsleep instead comes out of sleep after 2-5 seconds no matter the time configured for sleep 

### Which version of ESPHome has the issue?

1.20.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10

### What platform are you using?

ESP32

### Board

Lolon D32

### Component causing the issue

wakeup_pin_mode

### Example YAML snippet

```yaml
binary_sensor:
  - platform: status
    name: "${devicename} Node Status"
    id: system_status
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLDOWN
      inverted: True
    name: "letter box flap"
    device_class: door

mqtt:
  broker: 172.16.254.25
  discovery: True
  discovery_retain: True
  username: mqtt-user
  password: !secret mqtt_password
  birth_message:
  will_message:


deep_sleep:
  run_duration: 60s
  sleep_duration: 36000s
  wakeup_pin: 14
  wakeup_pin_mode: INVERT_WAKEUP


#sensor:

#  - platform: adc
#    pin: GPIO35
#    name: "$devicename Battery"
#    update_interval: 10s
    #attenuation: 11db
    #filters:
    #  - multiply: 3.35
      
switch:

  - platform: restart
    name: "$devicename Restart"
```

### Anything in the logs that might be useful for us?

```txt
[10:28:56][I][deep_sleep:072]: Beginning Deep Sleep
[10:29:01][I][mqtt:214]: MQTT Connected!
[10:29:01][C][deep_sleep:017]: Setting up Deep Sleep...
[10:29:01][I][app:060]: setup() finished successfully!
[10:29:01][D][binary_sensor:036]: 'letter_box Node Status': Sending state ON
[10:29:01][I][app:099]: ESPHome version 2021.10.2 compiled on Oct 25 2021, 10:22:59
```

### Additional information

System  works as expected with the removal of the wakeup_pin_mode: INVERT_WAKEUP command and deepsleep for the specified duration is achieved
