### ISSUE TITLE
CAN Bus using mcp2515 not receiving extended id messages 

### ISSUE THREAD

**Issue by drawlusyk** [esphome/issues#2642]
### The problem

Hello,

I have setup 2x esp32 with 2x mcp2515 devices. I have terminated on both mcp2515 using the jumper. I can send messages back and forth that are NOT extended ids. Extended show as being sent but can not receive them on either of the two devices.
Is there something i am missing or is this an issue? Can anyone confirm extended id's work?

Regards,
Dennis

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32s

### Component causing the issue

mcp2515

**Comment by drawlusyk** [comment]
Hello. FYI I did a search in discord for mcp2515 and found this filtering.
I added the following. I did not even add any filtering options. Now i can at least see the receipt of extended id messages.

external_components:
  - source:
      type: git
      url: https://github.com/alexyao2015/esphome
      ref: feature/mcp2515-filters
    components: [ mcp2515 ]
    refresh: 0s

**Comment by danielschramm** [comment]
Hello, I did not forget this issue but weekends are currently very busy.

**Comment by danielschramm** [comment]
Hello,
I just setup a testbench like with:

2x USB-CAN Interface (different Brands and Toos)
1x Esp8266 D1 Mini with MCP2515.

Code Examples very similar the ESPHome Can Manual Page.

I'm transmitting Std and Ext Frames successfully and also I receive both.

[10:31:28][D][can standard id 0x123:074]: 00000000
[10:31:28][D][can extended id 0x123:069]: 02134677

Do you have a high load on your CAN Bus?
In combination with software SPI and the old MCP2515 a high busload will give you a high loss on receiving data packages.

https://github.com/alexyao2015/esphome seems to experiment with  hardware filters which this esphome driver currenty does not support. They would make a evertying complicated.

It would be best  to support the CAN Interface inside the ESP32 which has a huge input queue and with hat even on high load a software filter would ne no issue.

Best Regards,

Daniel

```

substitutions:
  devicename: can-test
  upper_devicename: CanTest


esphome:
  name: $devicename
  platform: ESP8266
  board: d1
  #board_flash_mode: dout


wifi:
  domain: '.pinguin.lan'
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_ssid_1
    password: !secret wifi_password_1
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2

captive_portal:

logger:
  logs:
    canbus: ERROR

ota:
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

spi:
  id: McpSpi
  clk_pin: GPIO16
  mosi_pin: GPIO5
  miso_pin: GPIO4

canbus:
  - platform: mcp2515
    id: my_mcp2515
    spi_id: McpSpi
    cs_pin: GPIO14
    can_id: 0x123
    bit_rate: 500kbps
    clock: 8MHZ
    on_frame:
    - can_id: 0x122
      use_extended_id: true
      then:
      - lambda: |-
          std::string b(x.begin(), x.end());
          ESP_LOGD("can extended id 0x123", "%s", &b[0] );
    - can_id: 0x123
      then:
      - lambda: |-
          std::string b(x.begin(), x.end());
          ESP_LOGD("can standard id 0x123", "%s", &b[0] );

time:
  - platform: sntp
    on_time:
      - seconds: /1
        then:
          - canbus.send:
              # Extended ID explicit
              use_extended_id: true
              can_id: 0x100
              data: [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08]
          - canbus.send:
              # Standard ID by default
              can_id: 0x101
              data: [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08]
          - lambda: |-
              ESP_LOGD("can TX id 0x100", "");

```
