### ISSUE TITLE
ESP32 camera (TTGO T-Cam) fails to load camera when MQTT-component is included

### ISSUE THREAD

**Issue by mycortex** [esphome/issues#2643]
### The problem

Camera fails if the config also includes the MQTT-component. If I remove/comment out the MQTT-component it loads fine.

The solution I found to make it work with the MQTT-component included is to add `setup_priority: -200` to the camera component. See line 72 in YAML below.

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32

### Board

LILYGO TTGO T-cam

### Component causing the issue

MQTT

### Example YAML snippet

```yaml
substitutions:
  devicename: pircam-kontor
  friendly_name: pircam_kontor

esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: 192.168.*.***
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: restart
    name: $friendly_name Restart

binary_sensor:
  - platform: gpio
    pin: GPIO33
    name: $friendly_name PIR
    device_class: motion

  - platform: gpio
    pin:
      number: GPIO34
      inverted: True
    name: $friendly_name Button

  - platform: status
    name: $friendly_name Status

sensor:
 - platform: wifi_signal
   name: $friendly_name WiFi Signal
   update_interval: 60s
 - platform: uptime
   name: $friendly_name Uptime
   update_interval: 60s

esp32_camera:
  name: $friendly_name Camera
  external_clock:
    pin: GPIO32
    frequency: 20MHz
  i2c_pins:
    sda: GPIO13
    scl: GPIO12
  data_pins: [GPIO5, GPIO14, GPIO4, GPIO15, GPIO18, GPIO23, GPIO36, GPIO39]
  vsync_pin: GPIO27
  href_pin: GPIO25
  pixel_clock_pin: GPIO19
  power_down_pin: GPIO26
  resolution: 800x600
  jpeg_quality: 10
  vertical_flip: true
  horizontal_mirror: true
  setup_priority: -200  #(when this line is added the camera loads fine. Without this line it fails)#

i2c:
  sda: GPIO21
  scl: GPIO22

text_sensor:
  - platform: homeassistant
    entity_id: sensor.alarm_status
    id: status_alarm
    internal: true

font:
  - file: "fonts/times-new-roman.ttf"
    id: tnr1
    size: 18
  - file: "fonts/times-new-roman.ttf"
    id: tnr2
    size: 22

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    rotation: 180
    lambda: |-
      it.print(64, 17, id(tnr1), TextAlign::CENTER, "Alarm:");
      it.print(64, 47, id(tnr2), TextAlign::CENTER, id(status_alarm).state.c_str());
```

### Anything in the logs that might be useful for us?

```txt
I get this error line in the device log:
[E][esp32_camera:095]:   Setup Failed: ERROR
Everything else is normal.

Serial logs shows this error:
[09:27:26][E][camera.c:1113] camera_probe(): Detected camera not supported.
[09:27:26][E][camera.c:1379] esp_camera_init(): Camera probe failed with error 0x20004
[09:27:26][E][esp32_camera:020]: esp_camera_init failed: ERROR
[09:27:26][E][component:103]: Component esp32_camera was marked as failed.
```
