### ISSUE TITLE
Regression: Compilation Error about Wire.h using Max44009 library

### ISSUE THREAD

**Issue by benv666** [esphome/issues#2644]
### The problem

Several of my sensor ESPs are equipped with a GY49 lux sensor that were working fine using the Max44009 library and a small custom sensor wrapper (see details below).
This was working fine but started giving a compilation error on the latest esphome docker images.
(tried this week, no clue when it broke exactly, but can't be more than 2 months ago)

The error:
```
Compiling .pioenvs/keuken_sensors/libecc/Max44009/Max44009.cpp.o
In file included from .piolibdeps/keuken_sensors/Max44009/Max44009.cpp:40:0:
.piolibdeps/keuken_sensors/Max44009/Max44009.h:31:18: fatal error: Wire.h: No such file or directory

**************************************************************
* Looking for Wire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Wire.h"
* Web  > https://platformio.org/lib/search?query=header:Wire.h
*
**************************************************************

compilation terminated.
Compiling .pioenvs/keuken_sensors/lib18f/WiFi/ETH.cpp.o
*** [.pioenvs/keuken_sensors/libecc/Max44009/Max44009.cpp.o] Error 1
```

My GY49 sensor wrapper:

```
#include "esphome.h"
#include "Max44009.h"

using namespace esphome;

class BenVGY49 : public PollingComponent, public Sensor {
 public:
 BenVGY49(const std::string &name, uint32_t update_interval) : PollingComponent(update_interval) {}
  Max44009 luxSensor = Max44009(0x4A, 4, 15);
  Sensor *lux_sensor = new Sensor();

  void setup() override {
    ESP_LOGD("BenVGY49", "Lux sensor MAX44009 Setup");
  }
  void loop() override {
  }

  void update() override {
    float lux = luxSensor.getLux();
    int err = luxSensor.getError();
    ESP_LOGD("BenVGY49", "The value of MAX44009 sensor is: %f lux, error state %d", lux, err);
    lux_sensor->publish_state(lux);
  }
  std::string unit_of_measurement() override { return "Lux"; }
  int8_t accuracy_decimals() override { return 2; } // 2 decimal places of accuracy.
};

```

### Which version of ESPHome has the issue?

docker esphome:latest [68a5a16b47c6]

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

n.a.

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

custom

### Example YAML snippet

```yaml
esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev
  includes:
    - BenVGY49.h
  libraries:
    - "Max44009"

sensor:
  - platform: custom
    lambda: |-
      auto gy49 = new BenVGY49("gy49", 15000);
      App.register_component(gy49);
      return {gy49->lux_sensor};
    id: lux_sensor
    sensors:
      - name: "${upper_devicename} MAX44009 Light Sensor"
        id: gy49_lux
        unit_of_measurement: "lux"
        accuracy_decimals: 1
        filters:
          - sliding_window_moving_average:
              window_size: 5
              send_every: 5
```

### Additional information

This worked fine up until at least august since I have an ESP running with firmware version 2021.8.2 with that custom sensor.
