### ISSUE TITLE
FAN - platform: ledc - Does not turn off when I use the MIN_POWER function

### ISSUE THREAD

**Issue by mag2bue** [esphome/issues#2649]
### The problem

FAN: If I put off in HA or toggle by web, the fan is still running with the min_power value and swiched not off.

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32

### Board

ESP32-S

### Component causing the issue

MOS

### Example YAML snippet

```yaml
output:
  - platform: ledc
    pin: GPIO19
    frequency: 100 Hz 
    id: ventilation_fan_pwm
 #   inverted: True
    min_power: 0.5
    max_power: 1
fan:
  - platform: speed
    output: ventilation_fan_pwm
    name: "Basement Ventilation Fan"
```

### Anything in the logs that might be useful for us?

```txt
[D][speed.fan:035]: Setting speed: 0.00 -> takes the min_power value!
```

### Additional information

Background: I would like to control a fan. If I control with 0-10V, it is too less. Therefore I want to work with MIN_POWER.

If I switch the fan off, (toggle) the min value is used and is therefore not switched off.
