### ISSUE TITLE
note: invalid template non-type parameter

### ISSUE THREAD

**Issue by vautieri2** [esphome/issues#2651]
### The problem

AllI did was update esphome and then try to intall to my chip...  I'm following the directions to use esp32-IDF 

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.0

### What platform are you using?

ESP32-IDF

### Board

heltec_wifi_kit_32

### Component causing the issue

src/esphome/core/preferences.h

### Example YAML snippet

```yaml
esphome:
  name: armour
  platform: ESP32
  board: heltec_wifi_kit_32

#https://community.home-assistant.io/t/inside-esp32-template-alarm-system-for-home-assistant/281913  
# BOOT 
  on_boot:
    then:
    
      # RESTORE ALARM STATE
      - script.execute: restore_alarm_state
# LOOP  
  on_loop:
    then:

      - script.wait: publish_states
      - script.wait: restore_alarm_state
      - script.wait: failed_to_arm
      - script.wait: check_sensor_status
      - script.wait: evaluate_sensor_status
      - script.wait: disarm_sequence
      - script.wait: arm_home_sequence
      - script.wait: arming_sequence
      - script.wait: arm_away_sequence
      - script.wait: pending_sequence                
      - script.wait: trigger_alarm 
      - script.wait: force_arm_sequence
      

      # Check and evaluate
      - if:
          condition:
            - lambda: 'return (id(alarm_state_int) != ${triggered});'
          then: 
            - script.execute: check_sensor_status
            - script.execute: evaluate_sensor_status      
sensor:
  - platform: uptime
    name: Uptime Sensor
    
# Enable logging
logger:
```

### Anything in the logs that might be useful for us?

```txt
note: invalid template non-type parameter

sphome::ESPPreferenceObject esphome::ESPPreferences::make_preference(uint32_t)
   ESPPreferenceObject make_preference(uint32_t type) {
                       ^
src/esphome/core/preferences.h:62:23: note:   template argument deduction/substitution failed:
src/esphome/core/preferences.h:58:100: error: no type named 'type' in 'struct std::enable_if<false, bool>'
   template<typename T, typename std::enable_if<std::is_trivially_copyable<T>::value, bool>::type = true>
                                                                                                    ^
src/esphome/core/preferences.h:58:100: note: invalid template non-type parameter
Compiling /data/armour/.pioenvs/armour/FrameworkArduino/IPAddress.cpp.o
*** [/data/armour/.pioenvs/armour/src/main.cpp.o] Error 1
========================= [FAILED] Took 37.12 seconds =========================
```

### Additional information

this compiled just fine before the update.. I think it was 2021.10.1
