### ISSUE TITLE
PR #2303 has breaking changes to UART "invert" but is not listed as such. Documentation not updated

### ISSUE THREAD

**Issue by stephenhouser** [esphome/issues#2653]
### The problem

The [PR #2303](https://github.com/esphome/esphome/pull/2303) has makes "invert" in UART bus invalid where it was previously optional and for ESP32 devices. It advises that `    This option has been removed. Please instead use invert in the tx/rx pin schemas.` but there is no documentation in https://esphome.io/components/uart.html?highlight=uart about this change nor how to reconfigure with "tx/rx pin schemas". 

### Which version of ESPHome has the issue?

v2021.10.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

uart bus

### Example YAML snippet

```yaml
uart:
  tx_pin: GPIO12
  rx_pin: GPIO13
  invert: true
  baud_rate: 9600
  parity: NONE
  data_bits: 8
  stop_bits: 1
  id: maxbotix_uart
```
