### ISSUE TITLE
Cannot add yaml with secret data as remote package

### ISSUE THREAD

**Issue by Nardol** [esphome/issues#2654]
### The problem

To be able to overload an ESPHome configuration hosted on Github, I wish to include it using package. But when checking the configuration or compile it, ESPHome returns it is an invalid YAML file. When downloading it directly from Github and include it as a local package, it works.

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Component causing the issue

core

### Example YAML snippet

```yaml
substitutions:
  off_on_boot: 'true'

api:
  encryption:
    key: !secret encryption_key

packages:
  teleinfokit: github://Nardol/teleinfokit-board/esphome/teleinfokit.yml@no_screen_on_boot
```

### Anything in the logs that might be useful for us?

```txt
esphome/teleinfokit.yml is not a valid YAML file. Please check the file contents.
  teleinfokit: github://Nardol/teleinfokit-board/esphome/teleinfokit.yml@no_screen_on_boot [source main.yml:11]
```

### Additional information

main.yml is the name I use for my yaml file which should include the package. But changing its name and/or extension does not change the issue
