### ISSUE TITLE
fatal error: WiFiUdp.h: No such file or directory

### ISSUE THREAD

**Issue by nygellyndley** [esphome/issues#2655]
### The problem

Hi,
I'm using Home Assistant to compile an ESPHome yaml.

This yaml worked  fine on an earlier HA/Esphome version but with the latest HA/ESPHome version it won't compile, failing with :

`In file included from src/esphome/components/captive_portal/captive_portal.h:6:0,
                 from src/esphome/components/captive_portal/captive_portal.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif8266/libraries/DNSServer/src/DNSServer.h:3:21: fatal error: WiFiUdp.h: No such file or directory`

So clearly it's missing some header files, but it's not clear to me if this an ESPHome issue or a Home Assistant issue (since the build/install is being initiation from the HA interface.

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

wifi

### Example YAML snippet

```yaml
substitutions:
  device_name: incubation-chamber
  friendly_name: Incubation Chamber

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 17

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: incubation-chamber
    password: !secret fallback_password

  # manual_ip:
  #   static_ip: 192.168.1.63
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/incubation-chamber.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing incubation-chamber (board: nodemcuv2; framework: arduino; platform: platformio/espressif8266 @ 2.6.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Library Manager: Installing ESP8266WiFi
Warning! Could not find the package with 'ESP8266WiFi' requirements for your system 'linux_armv7l'
Library Manager: Installing Wire
Warning! Could not find the package with 'Wire' requirements for your system 'linux_armv7l'
Library Manager: Installing ESP8266mDNS
Warning! Could not find the package with 'ESP8266mDNS' requirements for your system 'linux_armv7l'
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|-- <ESPAsyncWebServer-esphome> 2.0.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <Crypto> 0.2.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <AsyncMqttClient-esphome> 0.8.6
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <noise-c> 0.1.4
|   |-- <libsodium> 1.10018.1
|-- <DNSServer> 1.1.1
Compiling /data/incubation-chamber/.pioenvs/incubation-chamber/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling /data/incubation-chamber/.pioenvs/incubation-chamber/src/esphome/components/esp8266/preferences.cpp.o
Compiling /data/incubation-chamber/.pioenvs/incubation-chamber/src/esphome/components/gpio/switch/gpio_switch.cpp.o
In file included from src/esphome/components/captive_portal/captive_portal.h:6:0,
                 from src/esphome/components/captive_portal/captive_portal.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif8266/libraries/DNSServer/src/DNSServer.h:3:21: fatal error: WiFiUdp.h: No such file or directory

*****************************************************************
* Looking for WiFiUdp.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFiUdp.h"
* Web  > https://platformio.org/lib/search?query=header:WiFiUdp.h
*
*****************************************************************

 #include <WiFiUdp.h>
                     ^
compilation terminated.
*** [/data/incubation-chamber/.pioenvs/incubation-chamber/src/esphome/components/captive_portal/captive_portal.cpp.o] Error 1
Compiling /data/incubation-chamber/.pioenvs/incubation-chamber/src/esphome/components/i2c/i2c.cpp.o
========================== [FAILED] Took 6.32 seconds ==========================
```
