### ISSUE TITLE
Compile error on 1.13.0-dev in src/esphome/core/automation.h (works on 1.12.2)

### ISSUE THREAD

**Issue by shbatm** [esphome/issues#266]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Sonoff S31 Hass.io v1.13.0-dev (not working) WSL on Win10 v1.12.2 (working)
**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

Generic Sonoff / S31 with Voltage Monitoring.

**Description of problem:**
Errors trying to compile from within Hass.io Dashboard.  See error below.  Same yaml code compiles and works fine with 1.12.2 when compiled from a Windows machine.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: washing_machine
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "<REDACTED>"
  password: "<REDACTED>"

api:

logger:
  baud_rate: 0

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Washer Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Washer Status"

switch:
  - platform: gpio
    name: "Washer Relay"
    pin: GPIO12
    id: relay

output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: s31_blue_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Washer Blue LED"
    output: s31_blue_led

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: "Washer Current"
    voltage:
      name: "Washer Voltage"
    power:
      name: "Washer Power"
```

**Traceback (if applicable):**

```
Compiling /data/washing_machine/.pioenvs/washing_machine/lib4d9/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
In file included from src/esphome/components/api/service_call_message.h:4:0,
from src/esphome/components/api/api_server.h:14,
from src/main.cpp:4:
src/esphome/core/automation.h: In instantiation of 'bool esphome::Trigger<Ts>::is_running() [with Ts = {}]':
src/esphome/components/light/base_light_effects.h:72:34:   required from here
src/esphome/core/automation.h:58:48: error: request for member 'is_running' in '((esphome::Trigger<>*)this)->esphome::Trigger<>::automation_parent_', which is of pointer type 'esphome::Automation<>*' (maybe you meant to use '->' ?)
return this->automation_parent_.is_running();
^
Compiling /data/washing_machine/.pioenvs/washing_machine/lib4d9/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling /data/washing_machine/.pioenvs/washing_machine/lib4d9/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
src/esphome/core/automation.h: In member function 'bool esphome::Trigger<Ts>::is_running() [with Ts = {}]':
src/esphome/core/automation.h:59:3: warning: control reaches end of non-void function [-Wreturn-type]
}
^
*** [/data/washing_machine/.pioenvs/washing_machine/src/main.cpp.o] Error 1
```

**Additional information and things you've tried:**
