### ISSUE TITLE
psram error while compiling

### ISSUE THREAD

**Issue by maker999** [esphome/issues#2670]
### The problem

I updated esphome and when I try to compile a yaml file(which used to compile successfully) now gives me the following error:
src/esphome/core/helpers.h:10:29: fatal error: esp32-hal-psram.h: No such file or directory

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Example YAML snippet

```yaml
esphome:
  name: core_v2
  platform: ESP32
  board: nodemcu-32s
  libraries: 
    - Wire
    #- https://github.com/wifwucite/esphome-ble-controller
  includes:
    - uart_multi_esp.h

time:
  - platform: sntp
    id: sntp_time
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - if:
              condition:
                lambda: |-
                  auto time = id(sntp_time).now();
                  ESP_LOGD("main", "The current dawn time is %2d:%2d", id(dawn_hour), id(dawn_minute));
                  return (time.hour == id(dawn_hour))&&(time.minute == id(dawn_minute))&&id(dawn_enable);
              then:
              - script.execute:
                  id: dawn_simulation

wifi:
  networks:
  - ssid: "ssid"
    password: "123456"

captive_portal:

# Enable logging
logger:
  level: DEBUG #makes uart stream available in esphome logstream

# Enable Home Assistant API
#api:
ota:

globals:
  - id: active
    type: int
    initial_value: '0'  # different numbers represent different light modes
  - id: dawn_hour
    type: int
    restore_value: yes
    initial_value: '19'
  - id: dawn_minute
    type: int
    restore_value: yes
    initial_value: '30'
  - id: dawn_duration
    type: int
    restore_value: yes
    initial_value: '30'
  - id: uart_msg
    type: char[20]
    initial_value: "{'i','d','l','e'}"
  - id: last_msg
    type: std::string
  - id: dawn_enable
    type: bool
    initial_value: 'false'

pca9685:
  frequency: 500

i2c:
  sda: 18
  scl: 19
  scan: True
  id: pwm_bus

switch:
  - platform: template
    name: "Dawn Switch"
    optimistic: true
    id: dawn_switch
    lambda: |-
      if (id(active)) {
        return true;
      } else {
        return false;
      }
    on_turn_on:
      - if:
          condition:
            lambda: 'return (id(active) == 1);'
          then:
            - script.execute:
                id: dawn_simulation
    on_turn_off:
      - script.execute:
          id: stop_all_scripts
      - script.execute:
          id: turn_off_all_lights
  - platform: template
    name: "set_dawn"
    optimistic: true
    lambda: |-
      if (id(esp_text).state.find("set dawn") !=std::string::npos) {
        id(dawn_hour) = atoi( id(esp_text).state.substr( id(esp_text).state.find(":") - 2,  2).c_str() );
        id(dawn_minute) = atoi( id(esp_text).state.substr( id(esp_text).state.find(":") + 1 , 2).c_str() );
        ESP_LOGI("STATE", "The new dawn time is %2d:%2d", id(dawn_hour), id(dawn_minute));
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
        //if(id(last_msg).compare(id(esp_text).state)!=0){
        //  id(last_msg).assign(id(esp_text).state);
        //}
  - platform: template
    name: "dawn_toggle"
    optimistic: true
    lambda: |-
      if (id(esp_text).state == "dawn on") {
        id(dawn_enable) = true;
        ESP_LOGI("STATE", "dawn: ON");
        return true;
      } else if (id(esp_text).state == "dawn off"){
        id(dawn_enable) = false;
        ESP_LOGI("STATE", "dawn: OFF");
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
        //if(id(last_msg).compare(id(esp_text).state)!=0){
        //  id(last_msg).assign(id(esp_text).state);
        //}
  - platform: template
    name: "shower_switch"
    optimistic: true
    id: shower_switch
    lambda: |-
      if(id(esp_text).state == "shower") {
        id(light_shower_scene).execute();
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
  - platform: template
    name: "reading_switch"
    optimistic: true
    lambda: |-
      if(id(esp_text).state == "reading") {
        id(reading_scene).execute();
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
  - platform: template
    name: "idle_switch"
    optimistic: true
    lambda: |-
      if(id(esp_text).state == "idle") {
        id(turn_off_all_lights).execute();
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();

# light configuration
output:
  - platform: pca9685
    id: 'pca9685_hub0'
    channel: 0
  - platform: pca9685
    id: 'pca9685_hub1'
    channel: 1
  - platform: pca9685
    id: 'pca9685_hub2'
    channel: 2
  - platform: pca9685
    id: 'pca9685_hub3'
    channel: 3
  - platform: pca9685
    id: 'pca9685_hub4'
    channel: 4
  - platform: pca9685
    id: 'pca9685_hub5'
    channel: 5
  - platform: pca9685
    id: 'pca9685_hub6'
    channel: 6
  - platform: pca9685
    id: 'pca9685_hub7'
    channel: 7
  - platform: pca9685
    id: 'pca9685_hub8'
    channel: 8
  - platform: pca9685
    id: 'pca9685_hub9'
    channel: 9
  - platform: pca9685
    id: 'pca9685_hub10'
    channel: 10
  - platform: pca9685
    id: 'pca9685_hub11'
    channel: 11
  - platform: pca9685
    id: 'pca9685_hub12'
    channel: 12
  - platform: pca9685
    id: 'pca9685_hub13'
    channel: 13
  - platform: pca9685
    id: 'pca9685_hub14'
    channel: 14
  - platform: pca9685
    id: 'pca9685_hub15'
    channel: 15

light:
  - platform: rgbw
    id: indirect_edge_rgbw
    name: "Indirect Edge RGBW"
    red: pca9685_hub0
    green: pca9685_hub1
    blue: pca9685_hub2
    white: pca9685_hub3
  - platform: rgbw
    id: indirect_center_rgbw
    name: "Indirect Center RBGW"
    red: pca9685_hub4
    green: pca9685_hub5
    blue: pca9685_hub6
    white: pca9685_hub7
  - platform: monochromatic
    id: indirect_center_ww
    name: "Indirect Center WW"
    output: pca9685_hub8
  - platform: monochromatic
    id: indirect_center_inner_cw
    name: "Indirect Center Inner CW"
    output: pca9685_hub9
  - platform: monochromatic
    id: indirect_center_outer_cw
    name: "Indirect Center Outer CW"
    output: pca9685_hub10
  # direct lights
  - platform: monochromatic
    id: direct_panel_front_edge_cw
    name: "Direct Panel Front Edge CW"
    output: pca9685_hub11
  - platform: monochromatic
    id: direct_panel_back_edge_cw
    name: "Direct Panel Back Edge CW"
    output: pca9685_hub12



script:
  # stop all scripts
  - id: stop_all_scripts
    then:
      - logger.log: "Stopping all running scripts."
      - script.stop:
          id: dawn_simulation
      - logger.log: "Stopped all running scripts."
  - id: turn_off_all_lights
    then:
      - logger.log: "Turning off all lights."
      - light.turn_off: indirect_center_rgbw
      - light.turn_off: indirect_edge_rgbw
      - light.turn_off: indirect_center_inner_cw
      - light.turn_off: indirect_center_outer_cw
      - light.turn_off: indirect_center_ww
      - light.turn_off: direct_panel_back_edge_cw
      - light.turn_off: direct_panel_front_edge_cw
      - logger.log: "Turned off all lights."
  # dawn simulation
  - id: dawn_simulation
    then:
      - logger.log: "Starting dawn simulation."
      # phase 1/10
      - light.turn_on: 
          id: indirect_center_rgbw
          red: 0%
          blue: 10%
          green: 0%
          white: 0%
          transition_length: !lambda |-
            // output value must be in range 0 - 1.0
            return id(dawn_duration)*60/27;
      - delay: 1s
      # phase 2/20
      - light.turn_on:
          id: indirect_center_rgbw
          blue: 50%
          red: 25%
          green: 25%
          transition_length: 1s
      - light.turn_on:
          id: indirect_edge_rgbw
          red: 50%
          green: 25%
          transition_length: 1s
      - delay: 1s
      # phase 3&4/10
      - light.turn_on:
          id: indirect_center_rgbw
          blue: 100%
          white: 50%
          transition_length: 2s
      - light.turn_on:
          id: indirect_edge_rgbw
          red: 100%
          green: 50%
          white: 50%
          transition_length: 2s
      - delay: 2s
      # phase 5/10
      - light.turn_on:
          id: indirect_center_rgbw
          blue: 100%
          white: 100%
          transition_length: 1s
      - light.turn_on:
          id: indirect_edge_rgbw
          red: 100%
          green: 50%
          white: 100%
          transition_length: 1s
      - delay: 1s
      # phase 6&7/10
      - light.turn_on:
          id: indirect_center_inner_cw
          brightness: 50%
          transition_length: 2s
      - delay: 2s
      # phase 8&9/10
      - light.turn_on:
          id: indirect_center_inner_cw
          brightness: 100%
          transition_length: 2s
      - light.turn_on:
          id: indirect_center_outer_cw
          brightness: 50%
          transition_length: 2s
      - delay: 2s
      # phase 10/10
      - light.turn_on:
          id: indirect_center_outer_cw
          brightness: 100%
          transition_length: 1s
      - light.turn_on:
          id: indirect_center_ww
          brightness: 100%
          transition_length: 1s
      - delay: 1s
      - logger.log: "Finished dawn simulation."
  # reading scene
  - id: reading_scene
    then:
      - logger.log: "Entering reading scene."
      - light.turn_off: indirect_center_rgbw
      - light.turn_off: indirect_center_inner_cw
      - light.turn_off: indirect_center_outer_cw
      - light.turn_off: direct_panel_back_edge_cw
      - light.turn_off: direct_panel_front_edge_cw
      - light.turn_on:
          id: indirect_center_ww
          brightness: 10%
      - light.turn_on:
          id: indirect_edge_rgbw
          brightness: 10%
          red: 100%
          green: 50%
          blue: 0%
      - logger.log: "Entered reading scene."
    # light shower
  - id: light_shower_scene
    then:
      - logger.log: "Entering light shower scene."
      - light.turn_off: indirect_center_rgbw
      - light.turn_off: indirect_edge_rgbw
      - light.turn_off: indirect_center_inner_cw
      - light.turn_off: indirect_center_outer_cw
      - light.turn_off: indirect_center_ww
      - light.turn_off: direct_panel_back_edge_cw
      - light.turn_off: direct_panel_front_edge_cw
      - light.turn_on: 
          id: indirect_center_rgbw
          brightness: 100%
          blue: 100%
          red: 100%
          green: 100%
          white: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_edge_rgbw
          brightness: 100%
          blue: 100%
          red: 100%
          green: 100%
          white: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_inner_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_inner_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_outer_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_ww
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: direct_panel_front_edge_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: direct_panel_back_edge_cw
          brightness: 100%
          transition_length: 3s
      - logger.log: "Entered light shower scene."



uart:
  # Remote ESP 
  - id: esp_uart
    rx_pin: 14
    tx_pin: 27
    baud_rate: 9600


text_sensor:
  - platform: custom
    lambda: |-
      auto my_custom_sensor = new UartMultiESP(id(esp_uart));
      App.register_component(my_custom_sensor);
      return {my_custom_sensor};
    text_sensors:
      id: "esp_text"

binary_sensor:
  - platform: gpio
    id: test_button
    pin: 
      number: GPIO34
      inverted: True
    on_click:
      - min_length: 100ms
        max_length: 500ms
        then:
          - logger.log: "test button pressed."
          - lambda: |-
              id(active) = id(active) ? 0 : 1;
              ESP_LOGI("STATE", "active entered state %d", id(active));
```

### Anything in the logs that might be useful for us?

```txt
compilation terminated.
In file included from src/esphome/components/socket/socket.h:5:0,
                 from src/esphome/components/api/api_frame_helper.h:13,
                 from src/esphome/components/api/api_frame_helper.cpp:1:
src/esphome/components/socket/headers.h:116:23: fatal error: sys/ioctl.h: No such file or directory
compilation terminated.
*** [.pioenvs\core_mcu\src\esphome\components\api\api_connection.cpp.o] Error 1
*** [.pioenvs\core_mcu\src\esphome\components\api\api_frame_helper.cpp.o] Error 1
In file included from src/esphome/components/api/proto.h:4:0,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_pb2_service.h:5,
                 from src/esphome/components/api/api_pb2_service.cpp:3:
src/esphome/core/log.h:15:21: fatal error: esp_err.h: No such file or directory

*****************************************************************
* Looking for esp_err.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_err.h"
* Web  > https://platformio.org/lib/search?query=header:esp_err.h
*
*****************************************************************

compilation terminated.
*** [.pioenvs\core_mcu\src\esphome\components\api\api_pb2_service.cpp.o] Error 1
```
