### ISSUE TITLE
problem switching ESP-IDF

### ISSUE THREAD

**Issue by pantileionut** [esphome/issues#2679]
### The problem

Hello, I have problems testing esp-idf but I encounter the following error "Tool Manager: Installing platformio/toolchain-xtensa32 @ ~2.80400.0
Error: Could not find the package with 'platformio/toolchain-xtensa32 @ ~2.80400.0' requirements for your system 'linux_aarch64' "
there is no support for raspberry pi 4 64 bit? 
my apologies if there are typos or other "nonsense"
![esphome](https://user-images.githubusercontent.com/12047452/140422117-859fd8fd-dc9d-4a7b-8393-fde8555a8193.JPG)

### Which version of ESPHome has the issue?

2021.10.3 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.0

### What platform are you using?

ESP32-IDF

### Board

nodemcu-32s

### Component causing the issue

esp-idf

### Example YAML snippet

```yaml
esphome:
  name: test

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    # version: recommended

logger:

# Enable Home Assistant API
api:

ota:
  

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "2KMkB1V0z6lK"
```

### Anything in the logs that might be useful for us?

```txt
Error: Could not find the package with 'platformio/toolchain-xtensa32 @ ~2.80400.0' requirements for your system 'linux_aarch64'
```
