### ISSUE TITLE
thermostat component state inverted after reboot

### ISSUE THREAD

**Issue by nliaudat** [esphome/issues#2680]
### The problem

The thermostat component state (on/off) is inverted in hassio after esphome reboot.

In fact a thermostat in "auto" mode become "off" and a component in "off" mode become "idle"

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

thermostat

### Example YAML snippet

```yaml
https://github.com/nliaudat/esp32_8ch_motor_shield/blob/main/firmware/esphome_firmware_sample.yaml
```

### Anything in the logs that might be useful for us?

```txt
[I][restart:016]: Restarting device...
[I][app:130]: Rebooting safely...
[D][esp32.preferences:113]: Saving preferences to flash...
...
[I][ota:102]: Boot seems successful, resetting boot loop counter.
[D][esp32.preferences:113]: Saving preferences to flash...
```

### Additional information

Before esp reboot : 

![before_reboot](https://user-images.githubusercontent.com/6782613/140537339-2c30bd97-52a9-4646-8fa7-5eb8b18dbfbe.PNG)

After esp reboot : 
![after_reboot](https://user-images.githubusercontent.com/6782613/140538560-2ca0b2b6-f09a-48c8-b5e3-b56b0e49f4ac.PNG)

**Comment by nliaudat** [comment]
If I do an automation in hassio
```
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.bedroom
    data:
      target_temp_high: 18
      target_temp_low: 16
      hvac_mode: auto
```
esphome report : 
`[W][climate:053]:   Mode AUTO is not supported by this device!`
