### ISSUE TITLE
Status LED stopping RGB esp8266_pwm Light from working on connected pin

### ISSUE THREAD

**Issue by BertrumUK** [esphome/issues#2683]
### The problem

Since updating to ESPHome 2021.10.3 last night I noticed that whatever pin the status_led is connected to does not work as intended. The LED would light up for a second then go off. If I remove status_led from the configuration then the LED colour stays lit.

I have replicated this issue on a breadboard using the code below and a 4 pin LED using another Wemos D1 Mini. I tried rolling back to ESPHome 2021.10.2 but the issue persists. An older version of ESPHome 2021.8.2 would not start on my Pi4 so could not be tested..

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.1

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

status_led

### Example YAML snippet

```yaml
esphome:
  name: test-led
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'RogueOne'
  password: !secret wifipw
  manual_ip:
    static_ip: 192.168.0.100
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test LED"
    password: !secret wifipw

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:    

      
output:
  - platform: esp8266_pwm
    pin: D6
    id: red
  - platform: esp8266_pwm
    pin: D7
    id: green
  - platform: esp8266_pwm
    pin: D8
    id: blue
    
light:
  - platform: rgb
    name: "Test LED"
    red: red
    green: green
    blue: blue
    
status_led:
  pin: D6
```
