### ISSUE TITLE
ESP8266 - Restoring global variable of type std::vector<std::string> from flash causing bootloop

### ISSUE THREAD

**Issue by pkejval** [esphome/issues#2685]
### The problem

Hello, I just found bug when restoring saved variable of type std::vector<std::string>

When variable is set to restore: false no bootloop is present.
Program is crashing at last line in lambda:
`id(tag_list) = result;`

I tried clearing existing variable and assigning new values into:
```
            std::stringstream data(x);
            std::string line;
            
            id(tag_list).clear();
            while(std::getline(data,line,',')) {
              ESP_LOGD("main", "Inserting card %s", line.c_str());
              id(tag_list).push_back(line);
            }
```

Attached minimal YAML for easy reproduction.

Test data for sensor:
`97-C3-C9-1C,97-C3-C9-1A,97-C3-C9-1B,97-C3-C9-1Y,97-C3-C9-1X,97-C3-C9-1E`

### Which version of ESPHome has the issue?

v2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

nodemcu

### Example YAML snippet

```yaml
esphome:
  platform: ESP8266
  board: nodemcuv2
  esp8266_restore_from_flash: true
  includes:
    - sstream.h

globals:  
  - id: tag_list
  type: std::vector<std::string>
  restore_value: true

text_sensor:
  - platform: homeassistant
    id: allowed_tags
    entity_id: sensor.allowed_tags
    on_value:
      then:
        - lambda: |-
            std::vector<std::string> result;
            std::stringstream data(x);
            std::string line;
            
            while(std::getline(data,line,',')) {
              ESP_LOGD("main", "Inserting card %s", line.c_str());
              result.push_back(line);
            }

            id(tag_list) = result;
```

**Comment by oxan** [comment]
Yes, this ain't gonna work, because `std::string` holds a pointer to heap memory where the actual string is, and that doesn't get restored. I don't think that's something that will be changed anytime soon...

**Comment by pkejval** [comment]
@oxan Thanks for looking at it.
My no-so-good workaround is hardcoding initial values into YAML like so:

```
substitutions:
  allowed_tags: '{"ABC", "CBA"}'

globals:  
  - id: tag_list
  type: std::vector<std::string>
  restore_value: false
  initial_value: $allowed_tags
```
This way my code works as intended but initial values are not updated from HA... Should not be a big deal because HA is almost always available to update tags from HA (DB).
