### ISSUE TITLE
Intense LED flash when connecting power to H801 controller - round 2

### ISSUE THREAD

**Issue by PeterPolacek** [esphome/issues#2686]
### The problem

Hi i have same issue with h801 like in https://github.com/esphome/issues/issues/1783
Have someone solution for this?
Thank you.

i am using esphome: 2021.10.3

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

6.5

### What platform are you using?

ESP32

### Board

H801

### Component causing the issue

H801

### Example YAML snippet

```yaml
esphome:
  name: h801light
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 600
    # ...
    then:
      - light.dim_relative:
          id: light_1
          relative_brightness: 100%

wifi:
  ssid: ""
  password: ""
  
  manual_ip:
    static_ip: 
    gateway: 
    subnet: 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""
  
sensor:
  - platform: wifi_signal
    name: "WiFi Signal h801light"
    update_interval: 60s
#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w
light:
  - platform: rgbw
    id: light_1
    name: "H801 Light"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
```
