### ISSUE TITLE
Compile error after update to 2021.10.3

### ISSUE THREAD

**Issue by theflorianmaas** [esphome/issues#2687]
### The problem

I get this errors when I try to update existing nodes, This issue did not occour with the previous version. Any idea where and what to check?
Thank you

> INFO Reading configuration /config/esphome/Cam_terrazza.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing camext (board: esp32dev; framework: arduino; platform: espressif32 @ 3.3.2)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
Dependency Graph
|-- <WiFi> 1.0
|-- <Update> 1.0
|-- <ESPmDNS> 1.0
Compiling /data/camext/.pioenvs/camext/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-esp32-elf-g++: Permission denied
Compiling /data/camext/.pioenvs/camext/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: xtensa-esp32-elf-g++: Permission denied
Compiling /data/camext/.pioenvs/camext/src/esphome/components/api/api_pb2.cpp.o
sh: 1: xtensa-esp32-elf-g++: Permission denied
*** [/data/camext/.pioenvs/camext/src/esphome/components/api/api_connection.cpp.o] Error 126
*** [/data/camext/.pioenvs/camext/src/esphome/components/api/api_frame_helper.cpp.o] Error 126
Compiling /data/camext/.pioenvs/camext/src/esphome/components/api/api_pb2_service.cpp.o
*** [/data/camext/.pioenvs/camext/src/esphome/components/api/api_pb2.cpp.o] Error 126
sh: 1: xtensa-esp32-elf-g++: Permission denied
*** [/data/camext/.pioenvs/camext/src/esphome/components/api/api_pb2_service.cpp.o] Error 126
========================== [FAILED] Took 5.23 seconds ==========================

![image](https://user-images.githubusercontent.com/17377588/140638724-521cf419-22af-4e7e-89ef-880fbaf5c5d6.png)

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.1

### What platform are you using?

ESP32

### Board

ESP32-cam, ESP32 mini D1,  TTGO-CAM

### Component causing the issue

api_connection.cpp.o, api_pb2.cpp.o, api_pb2_service.cpp.o

### Example YAML snippet

```yaml
# ESP32-CAM

substitutions:
  node_name: "camext"
  device_verbose_name: "cam terrazza"
  static_ip: 192.168.178.105
  resolution: "1600x1200"
  #resolution: "800x600"
  jpeg_quality: "10"
  vertical_flip: "False"
  horizontal_mirror: "False"
  contrast: "0" 
  brightness: "2"
  saturation: "-1"
  password: "1234"  
  ota_password: "1234"

packages: 
  wifi: !include common/wifi.yaml
  device_base: !include common/device_esp32cam.yaml

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor Cam Terrazza"
    update_interval: 60s
```
