### ISSUE TITLE
Light Partition: turning on partition does not turn on power_supply anymore

### ISSUE THREAD

**Issue by 749** [esphome/issues#2688]
### The problem

Just updated to the latest version of ESPHome for the controller.

#### Expected behavior
During startup the partition "play_lamp" is turned on. For this the power_supply "relay" is turned which is connected to "lamp", the parent of the partition.

#### Current behavior
Partition turns on (seen in Home Assistant) but power_supply is not turned on

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

sonoff basic

### Component causing the issue

light/partition

### Example YAML snippet

```yaml
esphome:
  name: wohnzimmer-play-table-lamp
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 250
    then:
    - lambda: |-
        // Farbe nach boot gedimmtes weiß
        auto call = id(play_lamp).turn_on();
        call.set_transition_length(0);
        call.set_brightness(0.7);
        call.set_rgb(1, 1, 1);
        call.perform();

wifi:
  ssid: "..."
  password: "..."

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wohnzimmer Tablelamp"
    password: "..."

captive_portal:

# Enable logging
logger:
  baud_rate: 0 #disable uart log
#  level: INFO
#  hardware_uart: UART1

# Enable Home Assistant API
api:
  password: "..."

ota:
  password: "..."
  

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Spieletischlampe Button"
    on_press:
      - light.toggle: play_lamp

  - platform: status
    name: "Wohnzimmer: Spieletischlampe Controller"

power_supply:
  - pin: GPIO12
    id: relay
    enable_time: 1000ms
    keep_on_time: 200ms

status_led:
  pin:
    number: GPIO13
    inverted: yes

light:
  - platform: partition
    id: play_lamp
    name: "Spieletischlampe"
    segments:
      - id: lamp
        from: 1
        to: 105
  - platform: neopixelbus
    id: lamp
    type: GRBW
    variant: SK6812
    method: ESP8266_DMA
    pin: GPIO3
    num_leds: 106
    restore_mode: RESTORE_DEFAULT_OFF
    power_supply: relay
```

### Additional information

It was working on version 2021.9.3 and before.
