### ISSUE TITLE
Webserver Not Serving Complete Page When css And js Files Are Local On S31

### ISSUE THREAD

**Issue by sjmellen** [esphome/issues#2697]
### The problem

After reconfiguring my yaml file to serve the webserver-v1.min.js and css files locally, the webpage hangs when loading.  Sometimes a page refresh will rectify the problem.  Sometimes I have to refresh it several times.  I've seen the same issue on multiple machines (PCs, Android, etc) using multiple browsers (Chrome, Firefox, etc).

In Chrome, after enabling the developer tools, I've noticed in the "Networking" tab, "0.js" status stays at "pending".  As I've stated above, sometimes refreshing the page will get things unstuck resulting in all of the data being displayed (and apparently 0.js loads).

So far the Sonoff S31 is the only device I've seen this issue occur on.  I've also compiled and download firmware for a Martin Jerry SD-01 dimmer using the same HA and ESPHome versions and webserver doesn't hang on that device.

I thought perhaps this is a "low on memory" situation but when I compile the firmware for the S31 it's using 41016 bytes from 81920 bytes (RAM) and using 491008 bytes from 1023984 bytes (FLASH)... so only about half of each.  The MJ SD-01 uses about the same amount of memory.

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.1

### What platform are you using?

ESP8266

### Board

Sonoff S31 With Power Monitoring

### Component causing the issue

webserver

### Example YAML snippet

```yaml
web_server:
  port: 80
  css_include: "/config/esphome/esphome-docs/_static/webserver-v1.min.css"
  css_url: ""
  js_include: "/config/esphome/esphome-docs/_static/webserver-v1.min.js"
  js_url: ""
```

### Anything in the logs that might be useful for us?

```txt
With logging set to verbose I don't see any messages pertaining to the webserver when I attempt to access the server.
```
