### ISSUE TITLE
Binary sensors device classes

### ISSUE THREAD

**Issue by lcavalli** [esphome/issues#2702]
### The problem

Home Assistant 2021.11 has new/updated binary sensors device classes with respect to ESPHome.
- added "Running", "Tamper"
- removed "Update"

### Which version of ESPHome has the issue?

2021.10.3 

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

wemos d1 mini (d1_mini)

### Component causing the issue

Binary Sensor

### Example YAML snippet

```yaml
- platform: template
    id: tamp_zone
    name: "Zone tamper"
    device_class: "tamper"
```
