### ISSUE TITLE
esp32_touch causing reboot

### ISSUE THREAD

**Issue by Maelstrom96** [esphome/issues#2706]
### The problem

Esphome on ESP32 is bootlooping/crashing because of IDLE0 watchdog.

Seems to only be happening if I have 2 or more binary_sensors. Having a single one doesn't trigger the watchdog.

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

esp32_touch

### Example YAML snippet

```yaml
esphome:
  name: test-sensor
  platform: ESP32
  board: nodemcu-32s

# Testing with this worked, but the watchdog is still triggered, it just doesn't reboot
#esp32:
#  board: nodemcu-32s
#  framework:
#    type: esp-idf
#    version: recommended
#    sdkconfig_options:
#      CONFIG_FREERTOS_UNICORE: y
      
wifi:
  ssid: "AJ - 2.4Ghz"
  password: "nottherealpassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bed Sensor Fallback Hotspot"
    password: "nottherealpassword"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "nottherealpassword"

ota:
  password: "nottherealpassword"

esp32_touch:
   setup_mode: true
   iir_filter: 10ms
   
binary_sensor:
   - platform: esp32_touch
     name: "Left"
     pin: GPIO32
     threshold: 80
     id: left
     filters:
      - delayed_on: 20ms
      - delayed_off: 20ms
      - delayed_on_off: 20ms
   - platform: esp32_touch
     name: "Right"
     pin: GPIO33
     threshold: 70
     id: right
     filters:
      - delayed_on: 20ms
      - delayed_off: 20ms
      - delayed_on_off: 20ms
```

### Anything in the logs that might be useful for us?

```txt
[0;36m[D][esp32_touch:126]: Touch Pad 'Left' (T9): 1768[0m
[0;36m[D][esp32_touch:126]: Touch Pad 'Right' (T8): 1785[0m
E (8737) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (8737) task_wdt:  - IDLE0 (CPU 0)
E (8737) task_wdt: Tasks currently running:
E (8737) task_wdt: CPU 0: wifi
E (8737) task_wdt: CPU 1: IDLE1
E (8737) task_wdt: Aborting.
abort() was called at PC 0x4014c448 on core 0

ELF file SHA256: 0000000000000000

Backtrace: 0x40088bcc:0x3ffbf810 0x40088e49:0x3ffbf830 0x4014c448:0x3ffbf850 0x40087301:0x3ffbf870 0x4000bfed:0x3ffaf110 0x4008afcd:0x3ffaf120 0x4008cf03:0x3ffaf140 0x4008d556:0x3ffaf160 0x40081e55:0x3ffaf180 0x40081e86:0x3ffaf1a0 0x40086cd9:0x3ffaf1c0 0x4000beaf:0x3ffaf1e0 0x4012de58:0x3ffaf200 0x4012dee7:0x3ffaf220 0x4012df4a:0x3ffaf240 0x4012a988:0x3ffaf260 0x4012a9d9:0x3ffaf280 0x40160940:0x3ffaf2a0 0x40158d42:0x3ffaf2c0 0x400fd233:0x3ffaf2e0 0x400fdfc9:0x3ffaf420 0x40116f25:0x3ffaf440 0x40118a94:0x3ffaf480 0x40089e5a:0x3ffaf4b0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
[0;32m[I][logger:214]: Log initialized[0m
[0;35m[C][ota:452]: There have been 3 suspected unsuccessful boot attempts.[0m
```
