### ISSUE TITLE
.h file custom sensor no longer compliling

### ISSUE THREAD

**Issue by Morbidbystandard** [esphome/issues#2710]
### The problem

After updating to 2021.10.3 I can no longer compile and install my custom sensor esp 32 code. I get an error in ESPhome about the .h file and failed install message.
`Compiling /data/controller/.pioenvs/controller/src/main.cpp.o
Compiling /data/controller/.pioenvs/controller/FrameworkArduino/esp32-hal-dac.c.o
In file included from src/main.cpp:54:0:
src/uart_com.h: In member function 'virtual void scaleSensor::loop()':
src/uart_com.h:14:41: error: 'readStringUntil' was not declared in this scope
       String line = readStringUntil('\n');
                                         ^
Compiling /data/controller/.pioenvs/controller/FrameworkArduino/esp32-hal-gpio.c.o
Compiling /data/controller/.pioenvs/controller/FrameworkArduino/esp32-hal-i2c.c.o
*** [/data/controller/.pioenvs/controller/src/main.cpp.o] Error 1
========================== [FAILED] Took 5.01 seconds ==========================`

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.11.3 and supervisor-2021.10.8

### What platform are you using?

ESP32

### Board

Esp32 wrover

### Component causing the issue

custom uart sensor

### Example YAML snippet

```yaml
esphome:
  name: controller
  platform: ESP32
  board: esp-wrover-kit
  includes: uart_com.h

wifi:
  ssid: "****"
  password: "******"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "******"
    password: "******"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  
sensor:
- platform: custom
  lambda: |-
    auto EZO = new scaleSensor(id(uart_bus));
    App.register_component(EZO);
    return {EZO};
  sensors:
    name: "Ph Sensor"
    unit_of_measurement: Ph
    accuracy_decimals: 2
    filters:
      - offset: +0.22
    
switch:
  - platform: gpio
    pin: 32
    id: ph_relay
    inverted: yes
  - platform: template
    name: "Relay 1"
    icon: "mdi:trending-up"
    lambda: 'return id(ph_relay).state;'
    turn_on_action:
    - switch.turn_on: ph_relay
    - delay: 4000ms
    - switch.turn_off: ph_relay
    
  - platform: gpio
    pin: 33
    name: "Relay 2"
    inverted: yes
    
  - platform: gpio
    pin: 25
    name: "Relay 3"
    inverted: yes
    
  - platform: gpio
    pin: 26
    name: "Relay 4"
    inverted: yes
    
  - platform: gpio
    pin: 27
    name: "Relay 5"
    inverted: yes
    
  - platform: gpio
    pin: 14
    name: "Relay 6"
    inverted: yes
    
  - platform: gpio
    pin: 12
    name: "Relay 7"
    inverted: yes
    
  - platform: gpio
    pin: 13
    name: "Relay 8"
    inverted: yes
    
  - platform: uart
    name: "Mid Point Calibration"
    data: 'cal,mid,7'
    
  - platform: uart
    name: "Low Point Calibration"
    data: 'cal,low,4'
    
  - platform: uart
    name: "High Point Calibration"
    data: 'cal,high,10'
```

### Anything in the logs that might be useful for us?

```yaml
#include "esphome.h"

class scaleSensor : public PollingComponent, public UARTDevice, public sensor::Sensor{
 public:
  scaleSensor(UARTComponent *parent) : PollingComponent(1000), UARTDevice(parent) {}
  float weight = 0;
  
  void setup() override {
    // nothing to do here
  }
  
  void loop() override {
    while (available()) {
      String line = readStringUntil('\n');
      weight = line.toFloat();
    }
  }
  
  void update() {
    publish_state(weight);
  }
};
```
