### ISSUE TITLE
RDM6300 is only reading 4 out of 5 ID bytes

### ISSUE THREAD

**Issue by mrpraline** [esphome/issues#2714]
### The problem

I am using an RDM6300 reader together with an ESP32CAM module. 
When I let the reader read an RFID, it reports the trailing 4 bytes of the tag ID in home assistant. 
The tags were written with 5 byte ID's and the leading byte is missing.

The tags is (for example) reported as 000000006E455C6B instead of 0000005D6E455C6B

I first tried the example as written in the documentation.But after realizing that that only can provide 4 bytes i changed the string conversion to use 64 bit uints. However, that still only reports the trailing 4 bytes.

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.11.3

### What platform are you using?

ESP32

### Board

ESP32CAM

### Component causing the issue

rdm6300

### Example YAML snippet

```yaml
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 20 fps
  idle_framerate: 0.05 fps
  name: ${devicename} cam

uart:
  rx_pin: GPIO13
  baud_rate: 9600

rdm6300:
  id: reader
  on_tag:
    # from example code (only uses 4 bytes) 
    # - homeassistant.tag_scanned: !lambda 'return uint32_to_string(x);'
    # modified to 64 bit int, expecting to get 5 significant bytes
     - homeassistant.tag_scanned: !lambda 'return uint64_to_string(x);'
```
