### ISSUE TITLE
total_daily_energy has strange spikes (pulse_meter does not)

### ISSUE THREAD

**Issue by irekzielinski** [esphome/issues#2730]
### The problem

I have an optical pulse conter that counts flashes in my electricity meter.
- platform: pulse_meter (with total), works as expected and value increases over time as pulses are counted.
- platform: total_daily_energy - set up to track daily usage (value of this sensor sometimes will jump up, and count more than real usage)

In other words: total_daily_energy seems to count too much, more than the pulse_meter itself

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.11.2

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

total_daily_energy

### Example YAML snippet

```yaml
sensor:
  - platform: pulse_meter
    pin: D2
    unit_of_measurement: 'kW'
    device_class: 'power'
    name: 'Spa Power Consumption'
    id: spa_power_consumption
    internal_filter: 100ms
    timeout: 300s
    accuracy_decimals: 2
    filters:
      - multiply: 0.06
      - delta: 0.008
    total:
      name: "Spa Consumed Energy"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      device_class: 'energy'
      state_class: total_increasing
      filters:
        - multiply: 0.001
        
  - platform: total_daily_energy
    name: "Spa Consumed Energy Today"
    power_id: spa_power_consumption
    accuracy_decimals: 2
    unit_of_measurement: "kWh"
    device_class: 'energy'
    id: spa_consumed_energy
    min_save_interval: 30s
```
