### ISSUE TITLE
Compiling image for esp32cam failed because resolution is not supported

### ISSUE THREAD

**Issue by wildblue** [esphome/issues#2733]
### The problem

I especcially bought a 5 megapixel camera for my esp32cam module to run it with esphome.

As the camera supports images up to 2592x1944, i want to have the advantage in resolution from my new high quality camera module.

When compiling i get the following message:
Unknown value '2592X1944', valid options are '160X120', 'QQVGA', '176X144', 'QCIF', '240X176', 'HQVGA', '320X240', 'QVGA', '400X296', 'CIF', '640X480', 'VGA', '800X600', 'SVGA', '1024X768', 'XGA', '1280X1024', 'SXGA', '1600X1200', 'UXGA'.
  resolution: 2592x1944

### Which version of ESPHome has the issue?

2021-11-04

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021-11-04

### What platform are you using?

ESP32

### Board

Esp32cam

### Component causing the issue

Implementation of user-selectable resolutions for camera module

### Example YAML snippet

```yaml
resolution: 2592x1944
jpeg_quality: 10
idle_framerate: 1 fps
max_framerate: 20 fps
vertical_flip: false
horizontal_mirror: false
```

### Anything in the logs that might be useful for us?

```txt
Nope
```

### Additional information

Please fix this as soon as possible, as it is only a few bytes to change in your source...
