### ISSUE TITLE
Not connect to WPA2-PSK/WPA3-SAE mixed mode encryption SSID

### ISSUE THREAD

**Issue by jlazkano** [esphome/issues#2736]
### The problem

I am new in ESPHome.

I compile my first image for Xiaomi Bed Lamp 2, and I notice that the lamp doesn't connect to my SSID.

My actual SSID has WPA2-PSK/WPA3-SAE mixed mode encryption, if I change to WPA2-PSK it works.

I think that the device is trying to connect first to WPA3 and can not connect and doesn't try the second WPA2 mode.

### Which version of ESPHome has the issue?

2021.11.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.11.4

### What platform are you using?

ESP32

### Board

Xiaomi Bed Lamp 2

### Component causing the issue

wifi

### Example YAML snippet

```yaml
packages:
  bslamp2:
    url: https://github.com/mmakaay/esphome-xiaomi_bslamp2
    ref: dev
    files:
      - packages/core.yaml
      - packages/behavior_default.yaml
      - packages/ota_feedback.yaml
      - packages/activate_preset_svc.yaml
    refresh: 0s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "xxx"

wifi:
  ssid: "xxx"
  password: "xxx"


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "XLamp Fallback Hotspot"
    password: "xxx"
```
