### ISSUE TITLE
Tuya cover set position != current position (2 separate DP)

### ISSUE THREAD

**Issue by ficueu** [esphome/issues#2737]
### The problem

I have zemismart curtain motor which can be triggered by RF remote, wifi or by pushing curtain by hand. While the curtain is pushing by hand motor goes to endpoint and the curtain is finally opened or closed (pushing by hand triggers the motor).
The device has two separate DP for set position (_id: 2_) and current position (_id: 3_). 
Set position can be written and curtain will go to written position.
Current position can not be written, it shows position while curtain stops, no matter if it is triggered via wifi (using uart communication) or by hand.

By DP id: _2_ I can control curtain via esphome, position is right until I move the curtain by hand.
Changed DP id from _2_ to _3_ I see right curtain position, but I can't control it via esphome.

To fix this issue is need to add one more variable like as **control_datapoint**. While **control_datapoint** is enabled **position_datapoint** should be only use for store current position.

I'm not good in object-oriented programming language, but if nobody has enough time to fix it I will try to make pull request.

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.3

### What platform are you using?

ESP8266

### Component causing the issue

tuya cover

### Example YAML snippet

```yaml
uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600

tuya:

cover:
  - platform: "tuya"
    name: "Zasłona sypialnia"
    position_datapoint: 2
    invert_position: true
    device_class: curtain
```
