### ISSUE TITLE
Entity category: CONFIG seems not processed for switch

### ISSUE THREAD

**Issue by jgverweij** [esphome/issues#2747]
### The problem

My smartplug exposed 2 switches for On/off and Restart.
To avoid accidentially restarting with all switches in one room I try to use the new entity_category in 2021.11.

However, after adding entity_category to the code the Restart switch does not move to the Config card as expected.
```
switch:
  # Switch to restart the plug
  - platform: restart
    name: "${plug_name} Restart"
    entity_category: config
```

### Which version of ESPHome has the issue?

2021.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.5

### What platform are you using?

ESP8266

### Board

esp8285

### Additional information

![Screenshot](https://user-images.githubusercontent.com/78507418/142936711-ea24f47e-04e3-49dc-81de-51ae3f2087e4.png)
