### ISSUE TITLE
Status LED Light, still not playing well with other light on the same pin.

### ISSUE THREAD

**Issue by Lovely-Maisonette** [esphome/issues#2749]
### The problem

I stopped using the status_led high level component when I realized it did not work simultaneously with a light under the same pin. I started using it again when it became a platform under light, and thus, the same pin could be shared. But it is not really working.

My case:

A powerplug with a template switch to enable/disable the power LED light when the relay is active (at night the light is too strong). This works well, and it restores its states (LED state and Template Switch state) even after reboot or power loss.

But if I enable the light led_status platform AND there is a reboot or power loss (it would probably be the same with WIFI loss), after the blinking, the light stays always off regardless of the relay or template switch status (I presume the blinking finishes with an off state, and nothing happens afterwards). The template switch does show the right state, so this is clearly just the light platforms not playing nicely with each-other, as it was the case with the original status_led component.

### Which version of ESPHome has the issue?

ESPHome version 2021.11.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

stand alone problem

### What platform are you using?

ESP8266

### Board

https://templates.blakadder.com/bakibo_TP22Y.html

### Component causing the issue

status_led light platform

### Example YAML snippet

```yaml
light:

  # Commenting this out, all behaviors work (except the status blinking of course)
  - platform: status_led
    id: Status_led
    pin:
      number: ${LED1R}
      inverted: ${LED1Ri}

  # LED1
  - platform: rgb
    id: LED1
    icon: "mdi:led-on"
    blue: pwm1b
    red: pwm1r
    green: pwm1g
    default_transition_length: 1s

output:

  # LED1 B/R/G
  - platform: esp8266_pwm
    id: pwm1b
    pin:
      number: ${LED1B}
      inverted: ${LED1Bi}
  - platform: esp8266_pwm
    id: pwm1r
    pin:
      number: ${LED1R}
      inverted: ${LED1Ri}
  - platform: esp8266_pwm
    id: pwm1g
    pin:
      number: ${LED1G}
      inverted: ${LED1Gi}

  # Power-LED Enable/Disable
  - platform: template
    name: ${nice_name} Status LED (Disable/Enable)
    id: LED1_enabled
    restore_state: true
    entity_category: config
    icon: "mdi:led-on"
    # Publish the switch state, but turn on the LED only if the relay is on
    turn_on_action:
      - switch.template.publish:
          id: LED1_enabled
          state: ON
      - if:
          condition:
            switch.is_on: Relay1
          then:
            - light.turn_on: LED1
    turn_off_action:
      - switch.template.publish:
          id: LED1_enabled
          state: OFF
      - light.turn_off: LED1

esp8266:
  restore_from_flash: true
preferences:
  flash_write_interval: 1min
```

### Additional information

Commenting this block out, fixes the interference problem, but it removes the status feature
```
  - platform: status_led
    id: Status_led
    pin:
      number: ${LED1R}
      inverted: ${LED1Ri}
```

As a temporal workaround I am using

esphome:
  on_boot:
    priority: -100
    then:
      - delay: 4s
      - switch.toggle: LED1_enabled
      - switch.toggle: LED1_enabled

The 4s requirement seems to be another bug, not taking into account the booting time
