### ISSUE TITLE
ESP Touch

### ISSUE THREAD

**Issue by jb123567** [esphome/issues#2764]
### The problem

Since the latest update my ESP32 seems to reporting different values when using the ESP Touch intergration. It previously would report values of between 50 - 130, however now it is reporting values between 100 - 400 

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2012.11.4

### What platform are you using?

ESP32

### Board

WROOM

### Component causing the issue

ESPTouch

### Example YAML snippet

```yaml
esp32_touch:
   setup_mode: true
   low_voltage_reference: 0.8V
   high_voltage_reference: 2.4V
   voltage_attenuation: 1.5V
   iir_filter: 50ms
```
