### ISSUE TITLE
light component does not report brightness feature

### ISSUE THREAD

**Issue by jkolczasty** [esphome/issues#2767]
### The problem

light component does not report brightness feature to home assistant:
color_mode: unknown

but the same configuration used with esphome 1.17 works fine and reports:
color_mode: brightness

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.8.7

### What platform are you using?

ESP32

### Board

ESP32-WROOM

### Component causing the issue

light monochromatic with ledc(pwm) output

### Example YAML snippet

```yaml
light:
  - platform: monochromatic
    output: "nightlight_pwm"
    name: "nightlight"
    id: "nightlight"

output:
  - platform: ledc
    pin: GPIO12
    id: "nightlight_pwm"
```

### Additional information

Very same configuration works fine with esphome 1.17
