### ISSUE TITLE
I get an error compiling a device that has a pulse_meter_sensor implementation

### ISSUE THREAD

**Issue by VdR1960** [esphome/issues#2773]
### The problem

When compiling an error is thrown. This started after updating, without changing the yaml file. It has persisted over several ESPHome updates in the last few week. The device meanwhile was functional with the sensor. If I comment out the sensor implementation all is well (well, except not having the sensor I need). See snippet from the log below. Validation of the yaml file tells me the configuration is valid.

![compile error](https://user-images.githubusercontent.com/76566363/144433628-f07e56cb-25d4-4605-a292-fb04d9ff5468.jpg)

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.5

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

pulse_meter

### Example YAML snippet

```yaml
sensor:

  # Water flow sensor
  - platform: pulse_meter
    name: "Water flow"
    pin: D1
    unit_of_measurement: "ltr/min"
    internal_filter: 100ms
    accuracy_decimals: 1
    timeout: 30s                              # mininum flow is 2.0 ltr/min

    total:      
      name: 'Water consumption'
      unit_of_measurement: 'm3'
      accuracy_decimals: 3
      
      filters:
        - multiply: 0.001                     # 1.0 ltr/imp / 1000 ltr/m3
```

### Additional information

This device "water" also started showing the name of the yaml file on the card. No idea what that means or if it is related. See screenshot.

![yaml](https://user-images.githubusercontent.com/76566363/144435079-dbd6a46e-3173-4d7d-864a-4729c34d659d.jpg)
