### ISSUE TITLE
DMSR option REQUEST_PIN cannot be set in configuration .yaml 

### ISSUE THREAD

**Issue by Niiccoo** [esphome/issues#2777]
### The problem

My d1_mini P1 slimme meter uses D7 to trigger the request to read data form P1 meter. (and not D5). 
When I try to use the setting  request_pin: D7 I get an error. My set up works when I manually set D7 to high. Only the the result are poor and only getting few reliable reading a day.

INFO Reading configuration /config/esphome/meterp1.yaml...
Failed config
dsmr: [source /config/esphome/meterp1.yaml:58]
  id: dsmr_instance
  **[request_pin] is an invalid option for [dsmr]**. Please check the indentation.
  request_pin: D7 [source /config/esphome/meterp1.yaml:60]

The REQUEST_PIN is present in the `dsmr/__init__.py /` file:
`CONF_REQUEST_PIN = "request_pin" `

### Which version of ESPHome has the issue?

ESPHome Current version: 2021.11.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.5

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

dsmr

### Example YAML snippet

```yaml
uart:
  # D6 is GIO12
  - rx_pin: D6
    baud_rate: 115200
    id: uart_bus
    data_bits: 8
    parity: NONE
    stop_bits: 1

# Test om D7 aan en uit te zetten
switch:
  - platform: gpio
    pin: D7
    name: "Lees van slimmemeter"
    icon: "mdi:power-from-grid"

dsmr:
  id: dsmr_instance
  request_pin: D7
```
