### ISSUE TITLE
WIFI strength selection does not work with multiple APs

### ISSUE THREAD

**Issue by gsieben** [esphome/issues#2779]
### The problem

I have multiple access points with the same SSID. And there is a big trouble with that. 

The WIFI roaming does not work:

```
# Wifi - Settings
wifi:
  networks:
  - ssid: AsteriNet
    password: !secret wifi_password
```

With these settings the AP will be chosen randomly. Even if it has a particularly bad signal. So I tried it differently. 

To distinguish between them, I use the BSSID. According to the instructions, the ESPHOME device should choose the strongest signal. Unfortunately this does not happen. It always chooses the first AP in the list. Even if this signal is almost unreachable. 

```
# Wifi - Settings
wifi:
  networks:
  #- ssid: AsteriNet
  - bssid: xx:xx:xx:xx:01 # 6590
    password: !secret wifi_password
  #- ssid: AsteriNet
   - bssid: xx:xx:xx:xx:02 # 7490
    password: !secret wifi_password
  # Other options
  power_save_mode: none
  fast_connect: off
```

I suspect this is a bug in the implementation. Because even if the signal strength is not even enough for a connection, only the first AP in the list will be chosen anyway. 

### Which version of ESPHome has the issue?

Firmware: 2021.11.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Newest

### What platform are you using?

ESP32

### Board

ESP32 Dev Kit C 

### Component causing the issue

WIFI
