### ISSUE TITLE
Climare - Thermostat not updating mode or action

### ISSUE THREAD

**Issue by kubik369** [esphome/issues#2780]
### The problem

Hi,

I have a climate - thermostat setup. It appears to work correctly: it regulates the temperature around the set point, you can also set the set point from HA. However, ESPHome does not seem to report/update the state of the thermostat, it is always shown as being off in HA. I have attached a part of the logs, they are from a period when the heating was on, but as you can see, both Mode and Action are being logged as off. I am not sure whether this is a misconfiguration on my part, but it seems weird to me that it would show the mode and action being off if the heating is working. The current and target temperature is being shown correctly in HA. Thank you for your help :)

### Which version of ESPHome has the issue?

2021.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.5

### What platform are you using?

ESP8266

### Board

sonoff_dualr2_001

### Component causing the issue

climate

### Example YAML snippet

```yaml
climate:
  - platform: thermostat
    name: "Sliepky klíma"
    id: sliepky_klima
    visual:
      min_temperature: 10 °C
      max_temperature: 30 °C
      temperature_step: 0.1 °C
    sensor: sliepky_temperature
    default_target_temperature_low: 15 °C
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: relay2
    idle_action:
      - switch.turn_off: relay2
```

### Anything in the logs that might be useful for us?

```txt
[15:11:11][D][climate:381]: 'Sliepky klíma' - Sending state:
[15:11:11][D][climate:384]:   Mode: OFF
[15:11:11][D][climate:386]:   Action: OFF
[15:11:11][D][climate:404]:   Current Temperature: 17.50°C
[15:11:11][D][climate:410]:   Target Temperature: 17.50°C

[15:12:11][D][dallas.sensor:136]: 'Teplota u sliepok': Got Temperature=17.7°C

[15:12:11][D][climate:381]: 'Sliepky klíma' - Sending state:
[15:12:11][D][climate:384]:   Mode: OFF
[15:12:11][D][climate:386]:   Action: OFF
[15:12:11][D][climate:404]:   Current Temperature: 17.69°C
[15:12:11][D][climate:410]:   Target Temperature: 17.50°C
```

### Additional information

I am running the Home assistant OS VM, there wasn't such an option in the drop-down. It probably doesn't change anything, just wanted to include it for completion
