### ISSUE TITLE
TLC59208F component compile error

### ISSUE THREAD

**Issue by myradon** [esphome/issues#2785]
### The problem

Hi guys,

Recently I've updated to ESPHome 2021.11.03 (from v2021.09.x). While compiling an ESPHome device with TLC59208F-output component, it throws an error;

`src/esphome/components/tlc59208f/tlc59208f_output.cpp: In member function 'virtual void esphome::tlc59208f::TLC59208FOutput::setup()':
src/esphome/components/tlc59208f/tlc59208f_output.cpp:107:24: error: 'delayMicroseconds' was not declared in this scope
   delayMicroseconds(500);
                        ^
*** [.pioenvs/esph_testing_livingroom/src/esphome/components/tlc59208f/tlc59208f_output.cpp.o] Error 1`

I've read the docs and I can't find any update regarding new settings.  I've run a _Clean Build Files_ no luck. Updated to V1.11.04 no luck. API docs shows something about _delayMicroseconds_ but rest is out of my comfort zone.

### Which version of ESPHome has the issue?

2021.11.03 and 2021.11.04

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

ESP07

### Component causing the issue

TLC59208F

### Example YAML snippet

```yaml
`# TLC59208F LED-driver
tlc59208f:
  address: 0x20`

`# Individual outputs
output:
  - platform: tlc59208f
    id: "pwm_r"
    channel: 4
    inverted: false
  - platform: tlc59208f
    id: "pwm_g"
    channel: 3
    inverted: false
  - platform: tlc59208f
    id: "pwm_b"
    channel: 2
    inverted: false
  - platform: tlc59208f
    id: "pwm_ww"
    channel: 1
    inverted: false
    max_power: 0.6
  - platform: tlc59208f
    id: "pwm_cw"
    channel: 0
    inverted: false
    max_power: 0.5

 light:
  - platform: rgbww
    id: led
    name: light_${name}
    default_transition_length: 2s
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    cold_white: pwm_cw
    warm_white: pwm_ww
    cold_white_color_temperature: 6536K
    warm_white_color_temperature: 2000K
    constant_brightness: true
    color_interlock: false
    internal: false
    discovery: true`
```

### Anything in the logs that might be useful for us?

```txt
......
Compiling .pioenvs/esph_testing_livingroom/src/esphome/components/time/automation.cpp.o
Compiling .pioenvs/esph_testing_livingroom/src/esphome/components/time/real_time_clock.cpp.o
Compiling .pioenvs/esph_testing_livingroom/src/esphome/components/tlc59208f/tlc59208f_output.cpp.o
Compiling .pioenvs/esph_testing_livingroom/src/esphome/components/uptime/uptime_sensor.cpp.o
Compiling .pioenvs/esph_testing_livingroom/src/esphome/components/web_server/web_server.cpp.o
Compiling .pioenvs/esph_testing_livingroom/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling .pioenvs/esph_testing_livingroom/src/esphome/components/wifi/wifi_component.cpp.o
src/esphome/components/tlc59208f/tlc59208f_output.cpp: In member function 'virtual void esphome::tlc59208f::TLC59208FOutput::setup()':
src/esphome/components/tlc59208f/tlc59208f_output.cpp:107:24: error: 'delayMicroseconds' was not declared in this scope
   delayMicroseconds(500);
                        ^
*** [.pioenvs/esph_testing_livingroom/src/esphome/components/tlc59208f/tlc59208f_output.cpp.o] Error 1
========================= [FAILED] Took 10.12 seconds =========================
```
