### ISSUE TITLE
Nodemcu-32s - tca9548a - mcp23017 control problem

### ISSUE THREAD

**Issue by stefkamarton** [esphome/issues#2790]
### The problem

Hy,
I have an ESP32 (nodemcu-32s) and I connect tca9548 multiplexer to create virtual i2c buses.
```
i2c:
  - id: bus_a
    sda: GPIO14
    scl: GPIO12
    scan: true

tca9548a:
  - address: 0x72
    id: multiplex0
    i2c_id: bus_a
    channels:
      - bus_id: tca0
        channel: 0

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x27
    i2c_id: tca0

switch:
  - platform: gpio
    name: "MCP23017 Pin #0"
    pin:
      mcp23xxx: mcp23017_hub
      number: 0
      mode:
        output: true
      inverted: false
```
I try to connect my mcp23017 throughout tca9548A but I can't send data to mcp23017. 
If I disconnect my mcp23017 and I connect bme280 sensor, I receive data so I think, tca9548A works well.
If I connect mcp23017 to esp without tca9548A then It works well. 

Can you help me? 

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

i2c, tca9648A, mcp27018

### Example YAML snippet

```yaml
i2c:
  - id: bus_a
    sda: GPIO14
    scl: GPIO12
    scan: true

tca9548a:
  - address: 0x72
    id: multiplex0
    i2c_id: bus_a
    channels:
      - bus_id: tca0
        channel: 0

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x27
    i2c_id: tca0

switch:
  - platform: gpio
    name: "MCP23017 Pin #0"
    pin:
      mcp23xxx: mcp23017_hub
      number: 0
      mode:
        output: true
      inverted: false
```

### Anything in the logs that might be useful for us?

```txt
[D][switch:021]: 'MCP23017 Pin #0' Toggling OFF.
[D][switch:037]: 'MCP23017 Pin #0': Sending state OFF
[D][switch:021]: 'MCP23017 Pin #0' Toggling ON.
[D][switch:037]: 'MCP23017 Pin #0': Sending state ON
[D][switch:021]: 'MCP23017 Pin #0' Toggling OFF.
[D][switch:037]: 'MCP23017 Pin #0': Sending state OFF
[D][switch:021]: 'MCP23017 Pin #0' Toggling ON.
[D][switch:037]: 'MCP23017 Pin #0': Sending state ON
[D][switch:021]: 'MCP23017 Pin #0' Toggling OFF.
[D][switch:037]: 'MCP23017 Pin #0': Sending state OFF
[D][switch:021]: 'MCP23017 Pin #0' Toggling ON.
[D][switch:037]: 'MCP23017 Pin #0': Sending state ON
[D][switch:021]: 'MCP23017 Pin #0' Toggling OFF.
[D][switch:037]: 'MCP23017 Pin #0': Sending state OFF
[D][switch:021]: 'MCP23017 Pin #0' Toggling ON.
[D][switch:037]: 'MCP23017 Pin #0': Sending state ON
[D][switch:021]: 'MCP23017 Pin #0' Toggling OFF.
[D][switch:037]: 'MCP23017 Pin #0': Sending state OFF
```
