### ISSUE TITLE
Ethernet and i2c bus problem on boot

### ISSUE THREAD

**Issue by stefkamarton** [esphome/issues#2791]
### The problem

Hy,
I have an ESP32 (nodemcu-32s) and I connected LAN8720 component to my ESP, I don't use esp's WIFI, and I use i2c connection.
When I reset my ESP then it didn't connect to the internet through LAN8720. But If I've disconnect sda pin for a second, it begins work and get ip from dhcp and connect to the internet. Can you solve my problem?

```
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1

i2c:
  - id: bus_a
    sda: GPIO14
    scl: GPIO12
    scan: true

tca9548a:
  - address: 0x72
    id: multiplex0
    i2c_id: bus_a
    channels:
      - bus_id: tca0
        channel: 0
```

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

ethernet, LAN8720, i2c

### Example YAML snippet

```yaml
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1

i2c:
  - id: bus_a
    sda: GPIO14
    scl: GPIO12
    scan: true

tca9548a:
  - address: 0x72
    id: multiplex0
    i2c_id: bus_a
    channels:
      - bus_id: tca0
        channel: 0
```
