### ISSUE TITLE
Is api password needed when encryption key is set?

### ISSUE THREAD

**Issue by CyanoFresh** [esphome/issues#2794]
### The problem

Hi.
I am using now encryption key and api password. Should I use them both? Or settings encryption key is enough for security?

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
api:
  password: !secret manage_password
  encryption:
    key: $encryption_key
```
