### ISSUE TITLE
climate_action_to_string() can't be used in a text sensor

### ISSUE THREAD

**Issue by MrHaroldA** [esphome/issues#2798]
### The problem

When using the string representation of the current action of a climate component, you'll get an error compiling it:

```
text_sensor:
  - platform: template
    name: "${dev_name} HVAC state"
    update_interval: 10s
    lambda: return climate_action_to_string(id(${dev_machine_name}_climate).action);
```

Result:
```
Compiling /data/cellar/.pioenvs/cellar/src/main.cpp.o
/config/esphome/cellar.yaml: In lambda function:
/config/esphome/cellar.yaml:70:61: error: could not convert 'esphome::climate::climate_action_to_string(((int)cellar_climate->esphome::thermostat::ThermostatClimate::<anonymous>.esphome::climate::Climate::action))' from 'const esphome::LogString*' to 'esphome::optional<std::basic_string<char> >'
     lambda: return climate_action_to_string(id(${dev_machine_name}_climate).action);
                                                             ^
/config/esphome/cellar.yaml:71:3: warning: control reaches end of non-void function [-Wreturn-type]
     
   ^
*** [/data/cellar/.pioenvs/cellar/src/main.cpp.o] Error 1
```

This used to work up till a few versions ago.

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.5

### What platform are you using?

ESP8266

### Board

Sonoff TH10

### Component causing the issue

climate

### Example YAML snippet

```yaml
substitutions:
  dev_name: "Cellar"
  dev_machine_name: cellar

dallas:
  - pin: GPIO14

sensor:
  - platform: dallas
    name: "${dev_name} inside"
    index: 0
    id: inside

switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
    internal: yes

text_sensor:
  - platform: template
    name: "${dev_name} HVAC state"
    update_interval: 10s
    lambda: return climate_action_to_string(id(${dev_machine_name}_climate).action);
    
climate:
  - platform: thermostat
    id: "${dev_machine_name}_climate"
    name: "${dev_name}"
    min_idle_time: 60s
    min_cooling_off_time: 60s
    min_cooling_run_time: 30s

    default_target_temperature_high: 12 °C

    visual:
      min_temperature: 8 °C
      max_temperature: 16 °C
      temperature_step: 0.5 °C
    sensor: inside

    idle_action:
      - switch.turn_off: relay

    cool_action:
      - switch.turn_on: relay
```

### Anything in the logs that might be useful for us?

```txt
Compiling /data/cellar/.pioenvs/cellar/src/main.cpp.o
/config/esphome/cellar.yaml: In lambda function:
/config/esphome/cellar.yaml:70:61: error: could not convert 'esphome::climate::climate_action_to_string(((int)cellar_climate->esphome::thermostat::ThermostatClimate::<anonymous>.esphome::climate::Climate::action))' from 'const esphome::LogString*' to 'esphome::optional<std::basic_string<char> >'
     lambda: return climate_action_to_string(id(${dev_machine_name}_climate).action);
                                                             ^
/config/esphome/cellar.yaml:71:3: warning: control reaches end of non-void function [-Wreturn-type]
     
   ^
*** [/data/cellar/.pioenvs/cellar/src/main.cpp.o] Error 1
```
