### ISSUE TITLE
Using nextion and dallas on WT32-ETH01

### ISSUE THREAD

**Issue by xydix** [esphome/issues#2801]
### The problem

When Using nextion and dallas temp sensor on this (WT32-ETH01) board connection to the nextion is lost.
Getting "Nextion is not connected!" in the log.

```
dallas:
  - pin: GPIO 2
```
When only the added the nextion is OK and the sensor i found

But when i add.
```
  - platform: dallas
    address: 0x4E051660936EFF28
    name: "my temp"
    id: my_temp
```
I get "Nextion is not connected!" in the log.

After help on discord the solution seems to be adding:
```
dallas:
  - pin: GPIO 2
    setup_priority: -200
```

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

WT32-ETH01

### Component causing the issue

dallas / nextion

### Example YAML snippet

```yaml
uart:
  rx_pin: GPIO 35
  tx_pin: GPIO 4
  baud_rate: 9600


display:
  - platform: nextion
    id: nextiondisplay

dallas:
  - pin: GPIO 2
```
