### ISSUE TITLE
Unable to add custom build_flags

### ISSUE THREAD

**Issue by rwoldberg** [esphome/issues#2802]
### The problem

I am trying to add custom build_flags by adding esphome:platformio_options:build_flags.  The flags do not appear to be being added to platformio.ini.  If I change the name to esphome:platformio_options:build_flags_test then it will show up in platformio.ini.  I think the settings are being overwritten by the generated flags rather than being appended.  I think appending in this case should be the default or perhaps adding ${common.build_flags} similar to how ${common.lib_deps} is being added to the lib.deps section in platformio.ini.  

### Which version of ESPHome has the issue?

2021.11.4 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.5

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

esphome:platformio_options

### Example YAML snippet

```yaml
substitutions:
  device_name: test
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: nodemcu-32s
  libraries:
    - FS
    - SPI   
  platformio_options:
      build_flags: -DSomeFlag=1
    
wifi:
  ssid: !secret WiFiSSID
  password: !secret WiFiPassword
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret FallbackPassword

captive_portal:

# Enable logging
logger:
  level: debug
        
# Enable Home Assistant API
api:
  password: !secret APIPassword
```

**Comment by dbuezas** [comment]
Flags is an array. Try like this:

```yaml
esphome:
  platformio_options:
      build_flags: 
        - "-DSomeFlag=1"  #quotes are optional, notice the 1st (-) for the array element and the 2nd one for the "-D" flag
```
