### ISSUE TITLE
Buttons doesn't work via MQTT

### ISSUE THREAD

**Issue by definitio** [esphome/issues#2808]
### The problem

Sending `PRESS` via MQTT doesn't work.

### Which version of ESPHome has the issue?

2021.12

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.12

### What platform are you using?

ESP32

### Component causing the issue

button

### Example YAML snippet

```yaml
button:
  - platform: restart
    name: $device_name restart
```

### Anything in the logs that might be useful for us?

```txt
[W][mqtt.button:023]: 'restart': Received unknown status payload: PRESS
```
