### ISSUE TITLE
No ACK / ACK time-out using a Nextion NX3224T024 connected to Wemos D1 Mini 

### ISSUE THREAD

**Issue by JBS5** [esphome/issues#281]
I am trying to get a Nextion NX3224T024 to work connected to a Wemos D1 Mini.
Using the ESPHome 1.12.2 add-on on HASS.io running on a Intel NUC with Ubuntu.

A screenshot of the upload followed by the errors:

![](https://tweakers.net/ext/f/7LwTmSPOhfdP9ag89Gw4fHNK/full.png)

The YAML in ESPHome:

```
esphomeyaml:
  name: touchscreen
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'WLANJBSSAM'
  password: '7W7Zt66ybVpUajc3SyFx'
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.221
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0  

uart:
  rx_pin: D4
  tx_pin: D7
  baud_rate: 9600
  
binary_sensor:
  - platform: nextion
    page_id: 0
    component_id: 2
    name: "Nextion Component 2 Touch"

display:
  - platform: nextion
    lambda: |-
      it.set_component_text("t0", "hello");

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
```
Connected like this:

![](https://i.imgur.com/OPq436N.png)
![](https://i.imgur.com/XRqdZ3Q.png)
