### ISSUE TITLE
Component not found: Button On dev version on ESPHome

### ISSUE THREAD

**Issue by alpdmrel** [esphome/issues#2810]
### The problem

Tried to use button template component but I got the "Component not found: Button" on dev version.
I can upload the same code without any errors on regular version(2021.12.0).

### Which version of ESPHome has the issue?

dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

button

### Example YAML snippet

```yaml
button:
  - platform: template
    name: "Filter Coffee Start Button"
    id: filter_coffee_start_button
    on_press:
    - switch.turn_on: filter_coffee_start
    - delay: 500ms
    - switch.turn_off: filter_coffee_start
```
