### ISSUE TITLE
New NEC remote protocol does not work

### ISSUE THREAD

**Issue by seanomat** [esphome/issues#2815]
### The problem

Since the update to ESPhome 2021.12 and flashing the device with the new firmware the service remote_transmitter.transmit_nec does not work anymore.

As instructed I reversed the codes for "address" and "command".
Either way (original/reversed) does not work.
It worked before the update.

### Which version of ESPHome has the issue?

2021.12

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.0

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

remote_transmitter

### Example YAML snippet

```yaml
remote_transmitter:
  pin: "${component_remote_transmitter_pin}"
  # Set to 100% when working with RF signals, and 50% if working with IR leds
  carrier_duty_percent: 50%

api:
  services:
    - service: send_ir
      variables:
        address_str: string
        command_str: string
      then:
        - remote_transmitter.transmit_nec:
            address: !lambda 'return (int)strtol(address_str.c_str(), NULL, 16);'
            command: !lambda 'return (int)strtol(command_str.c_str(), NULL, 16);'
```

### Anything in the logs that might be useful for us?

```txt
nothing
```

### Additional information

To easily reproduce and test, I created a user defined service (see above) and passed address and command as parameters. This worked as expected before the firmware upgrade to the current version:

```yaml
service: esphome.livingroom_hub_sculpture_send_ir
data:
  address_str: '0x4040'
  command_str: '0x807F'
```

but not after:

```yaml
service: esphome.livingroom_hub_sculpture_send_ir
data:
  address_str: '0x0101'
  command_str: '0xFE01'
```

**Comment by petergebruers** [comment]
Please try `address_str: '0x0202'`

```python
def reverse_mask(x):
    x = ((x & 0x5555) << 1) | ((x & 0xAAAA) >> 1)
    x = ((x & 0x3333) << 2) | ((x & 0xCCCC) >> 2)
    x = ((x & 0x0F0F) << 4) | ((x & 0xF0F0) >> 4)
    x = ((x & 0x00FF) << 8) | ((x & 0xFF00) >> 8)
    return x

print(f"0x{reverse_mask(0x4040):04X}")
```

Gives: 0x0202

The command_str seems to be correct.

print(f"0x{reverse_mask(0x807F):04X}")
0xFE01

Was facing the same issue. I am not good at reversing bits, that's why I grabbed some code from the www...

**Comment by seanomat** [comment]
I tried your suggestion to no avail:

```yaml
service: esphome.livingroom_hub_sculpture_send_ir
data:
  address_str: '0x0202'
  command_str: '0xFE01'
```

I had problems to understand what has to be done, to revert the values. In the end I converted hex to bits, reversed the order and converted to hex again, as discussed in https://community.home-assistant.io/t/ir-change-in-nec-what-do-i-need-to-do/365840
