### ISSUE TITLE
2021.12 breaks ESP32-S2 build

### ISSUE THREAD

**Issue by misery** [esphome/issues#2816]
### The problem

Seems https://github.com/esphome/esphome/pull/2846 breaks the single core ESP32-S2. 2021.11.x works without problems.

```
src/esphome/components/esp32/core.cpp: In function 'void esphome::arch_init()':
src/esphome/components/esp32/core.cpp:50:3: error: 'disableCore1WDT' was not declared in this scope
   disableCore1WDT();
   ^~~~~~~~~~~~~~~
src/esphome/components/esp32/core.cpp:50:3: note: suggested alternative: 'disableCore0WDT'
   disableCore1WDT();
   ^~~~~~~~~~~~~~~
   disableCore0WDT
```

### Which version of ESPHome has the issue?

2021.12

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.12

### What platform are you using?

ESP32

### Board

esp32-s2-kaluga-1

### Component causing the issue

esp32/core

### Example YAML snippet

```yaml
esp32:
  board: esp32-s2-kaluga-1

esphome:
  name: test
  platformio_options:
    platform_packages:
      - framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.1
    platform:
      - https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
```

### Additional information

I know that esp-idf is recommended for ESP32-S2. I need components like MQTT that is arduino only at the moment.
