### ISSUE TITLE
Error while compiling ESP32 -->nodemcu-32s

### ISSUE THREAD

**Issue by ashrafmn** [esphome/issues#2822]
### The problem

I was able to continuously compile and upgrade to latest ESPHome version.
Only since the last two updates I'm not able to compile my only ESP32 device. Unlike all my other devices which are using ESP8266/esp01_1m boards are being successfully compiled with no issues.

Please note, this sane yaml file was working fine with no issues at all with previous ESPHome versions

### Which version of ESPHome has the issue?

Current version: 2021.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2021.12.1

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

sh: 1: xtensa-esp32-elf-g++: not found

### Example YAML snippet

```yaml
esphome:
   name: 'esp32sweather'
   platform: ESP32
   board: nodemcu-32s

    
    
wifi:
  ssid: 'yyyyyyyy'
  password: 'xxxxxxxxxx'
  fast_connect: on
  manual_ip:
   static_ip: 192.168.xx.xxx
   gateway: 192.168.xx.xxx
   subnet: 255.255.255.0
   dns1: 192.168.xx.xxx
  ap:
    ssid: 'esp32sweather'
    password: "12345678"


captive_portal:

api:
web_server:
  port: 80
logger:
  level: verbose

ota:

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org


sensor:
    
  - platform: dht
    model:  AM2302
    pin: GPIO25
    temperature:
      name: "esp32sweather DHT11 Temperature"
      id: dht11temp
    humidity:
      name: "esp32sweather DHT11 Humidity"
      id: dht11humid
    update_interval: 60s
    
    
  - platform: wifi_signal
    name: 'esp32sweather WiFi Signal'
    update_interval: 60s


switch:
  - platform: restart
    name: "esp32sweather Restart"



text_sensor:
  - platform: template
    name: "esp32sweather_MAC_Address"
    lambda: 'return {WiFi.macAddress().c_str()};'
    icon: mdi:fingerprint
    update_interval: 500s
    
  - platform: template
    name: "esp32sweather IP Address"
    lambda: 'return {WiFi.localIP().toString().c_str()};'
    icon: mdi:fingerprint
    update_interval: 500s
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esp32S_weather.yaml...
INFO Detected timezone 'Asia/Riyadh'
INFO Generating C++ source...
INFO Compiling app...
Processing esp32sweather (board: nodemcu-32s; framework: arduino; platform: platformio/espressif32 @ 3.3.2)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <WiFi> 1.0
|-- <FS> 1.0
|-- <Update> 1.0
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <DNSServer> 1.1.0
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESPmDNS> 1.0
Compiling /data/esp32sweather/.pioenvs/esp32sweather/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/esp32sweather/.pioenvs/esp32sweather/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/esp32sweather/.pioenvs/esp32sweather/src/esphome/components/api/api_pb2.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/esp32sweather/.pioenvs/esp32sweather/src/esphome/components/api/api_connection.cpp.o] Error 127
Compiling /data/esp32sweather/.pioenvs/esp32sweather/src/esphome/components/api/api_pb2_service.cpp.o
*** [/data/esp32sweather/.pioenvs/esp32sweather/src/esphome/components/api/api_frame_helper.cpp.o] Error 127
*** [/data/esp32sweather/.pioenvs/esp32sweather/src/esphome/components/api/api_pb2.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/esp32sweather/.pioenvs/esp32sweather/src/esphome/components/api/api_pb2_service.cpp.o] Error 127
========================== [FAILED] Took 5.22 seconds ==========================
```

### Additional information

I'm using pi 64bit device booting through USB.
