### ISSUE TITLE
modbus_controller input entity doesn't use multiply for getting the state

### ISSUE THREAD

**Issue by Bascht74** [esphome/issues#2827]
### The problem

Hi, 

I used modbus_controller for setting an input entity and there I used     `multiply: 100` to store a temperature of 24° C as 24 * 100 = 2400. 
That works perfectly, I can set a new temperature e.g. 24°C (see log). 
But later on the input entity is getting a new value and sets the entity to "2400". 

That is wrong! 

It has to use the multiply the other way around 2400 / 100 = 24.00. 
But that seems to be missing. 

Setting a filter as a workaround doesn't work because they are not supported in this input component.
So I had to use `lambda: "return x * 0.01;` as a workaround.

Can you fix that so that the multiply works in both ways...? 

Thx, 

Sebastian

### Which version of ESPHome has the issue?

2021.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

not relevant

### What platform are you using?

ESP32

### Board

m5stack-atom

### Component causing the issue

modbus_controller

### Example YAML snippet

```yaml
- platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    id: nilan_target_temperature_set
    mode: box
    unit_of_measurement: '°C'
    min_value: 15
    max_value: 30
    step: 1.0
    address: 1004
    force_new_range: true
    use_write_multiple: true
    entity_category: config
    skip_updates: 0
    multiply: 100
```

### Anything in the logs that might be useful for us?

```txt
[00:12:01][D][number:010]: 'Nilan Temperature set' - Setting
[00:12:01][D][number:029]:   Value: 24.000000
[00:12:01][D][modbus.number:055]: Updating register: connected Sensor=Nilan Temperature set start address=0x3EC register count=1 new value=2400.00 (val=2400.00)
[00:12:01][D][number:036]: 'Nilan Temperature set': Sending state 24.000000
[00:12:14][D][modbus.number:023]: Number new state : 2400.00
[00:12:14][D][number:036]: 'Nilan Temperature set': Sending state 2400.000000
```

### Additional information

I don't have a sensor component configured for modbus address 1004, only the input entity exists.
