### ISSUE TITLE
Compile error: esphome::parse_float()

### ISSUE THREAD

**Issue by gungner** [esphome/issues#2829]
### The problem

Upgraded from 2021.08 to 2021.12(.01) och got an compile error on esphome::parse_float(). 

error: 'parse_float' is not a member of 'esphome'

### Which version of ESPHome has the issue?

2021.12.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.12.01

### What platform are you using?

ESP8266

### Board

D1-mini

### Example YAML snippet

```yaml
mqtt:
  broker: 192.168.1.4
  port: 1883
  discovery: true
  client_id: house
  on_message:
    - topic: "warm-energy/sensor/house_total/state"
      then:
        lambda: |-
          static bool already_restored = false;
          if (already_restored)
            return;

          auto value = esphome::parse_float(x);
          if (value.has_value()) {
            id(last_usage) = value.value();
            already_restored = true;
          }
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/warm-energy/libfb2/ESP8266mDNS/ESP8266mDNS_Legacy.cpp.o
/config/warm-energy.yaml: In lambda function:
/config/warm-energy.yaml:36:20: error: 'parse_float' is not a member of 'esphome'
           auto value = esphome::parse_float(x);
                    ^
Archiving .pioenvs/warm-energy/lib813/libAsyncMqttClient-esphome.a
Compiling .pioenvs/warm-energy/libfb2/ESP8266mDNS/LEAmDNS.cpp.o
Compiling .pioenvs/warm-energy/libfb2/ESP8266mDNS/LEAmDNS_Control.cpp.o
*** [.pioenvs/warm-energy/src/main.cpp.o] Error 1
========================== [FAILED] Took 2.67 seconds ==========================
```

### Additional information

Did compile, and worked, without any problems in 2021.08. Compile error on both 2021.12.0 and 2021.12.1
