### ISSUE TITLE
PCF8574 working only with OUTPUT

### ISSUE THREAD

**Issue by bigstation17** [esphome/issues#283]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

PIP 1.12.2

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 mini

**Affected component:**

https://esphome.io/components/pcf8574.html

**Description of problem:**
I cannot use PCF8574 with INPUT or INPUT_PULLUP.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test_pcf8571
  platform: ESP8266
  board: d1_mini
  esphome_core_version: 1.12.2

wifi:
  ssid: xxx
  password: xxx

logger:
  level: VERBOSE

web_server:
  port: 80

i2c:
  sda: D6
  scl: D4
  scan: True

pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: False

switch:
  - platform: gpio
    name: "PCF8574 Pin #0"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 1
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: INPUT
      inverted: False

```

**Traceback (if applicable):**

```
Failed config

switch.gpio: [source test_pcf8571.yaml:32]
  platform: gpio
  name: PCF8574 Pin #0
  pin:  [source test_pcf8571.yaml:35]
    pcf8574: pcf8574_hub
    number: 1

    Unknown value 'INPUT', must be one of 'OUTPUT'. Got 'INPUT'
    mode: INPUT
    inverted: False
```

**Additional information and things you've tried:**
