### ISSUE TITLE
Modbus Controller Number incorrect documentation?

### ISSUE THREAD

**Issue by Strixx76** [esphome/issues#2830]
### The problem

When trying to add a Modbus Controller Number by copy/past the code from the docs i get the following error:

`[register_type] is an invalid option for [number.modbus_controller]. Please check the indentation.`

### Which version of ESPHome has the issue?

2021.12.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

Modbus Controller

### Example YAML snippet

```yaml
number:
  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_capacity_number
    name: "Battery Cap Number"
    address: 0x9001
    register_type: holding
    value_type: U_WORD
    lambda: "return  x * 1.0; "
    write_lambda: |-
      ESP_LOGD("main","Modbus Number incoming value = %f",x);
      uint16_t b_capacity = x ;
      payload.push_back(b_capacity);
      return x * 1.0 ;
    ## multiply is ignored because lamdba is used
    multiply: 1.0
```
