### ISSUE TITLE
SCD41 (Sensirion CO2, Temperature, and Humidity Sensor) periodically stops reporting measurements

### ISSUE THREAD

**Issue by Jsakkos** [esphome/issues#2832]
### The problem

The sensor will occasionally become unresponsive and send the message "Data not ready yet". Power cycling the device has no effect.

### Which version of ESPHome has the issue?

2021.12.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.5

### What platform are you using?

ESP8266

### Board

Wemos D1 mini 4mb

### Component causing the issue

i2c

### Example YAML snippet

```yaml
esphome:
  name: air-quality-1
  platform: ESP8266
  board: d1_mini
i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a
sensor:
  - platform: scd4x
    co2:
      name: "CO2"
      id: "co2"
    temperature:
      name: "Temperature"
      id: "temperature"
    humidity:
      name: "Humidity"
      id: "humidity"
    update_interval: 30s
```

### Anything in the logs that might be useful for us?

```txt
[17:51:01][W][scd4x:175]: Data not ready yet!
```

### Additional information

Seems similar to this issue with the SCD30: https://github.com/esphome/issues/issues/987
