### ISSUE TITLE
monochromatic light OFF state 100% brightness

### ISSUE THREAD

**Issue by obrador** [esphome/issues#2833]
### The problem

Hi, I don't know if that's an issue or if it's the normal behaviour. I've set up a monochromatic light with a PWM output, it works fine, but when I set brightness to 0%, the state turns automatically to "OFF" and the brightness become 100%. Light is off, it works in fact, but I would like brightness to be 0%. Is there a way to achieve that?

### Which version of ESPHome has the issue?

2021.12.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

No HA. I use OpenHab

### What platform are you using?

ESP8266

### Board

D1

### Component causing the issue

monochromatic light

### Example YAML snippet

```yaml
light:
  - platform: monochromatic
    name: "White LED strip"
    output: wled_strip

output:
  - platform: esp8266_pwm
    id: wled_strip
    pin: GPIO13
```

### Anything in the logs that might be useful for us?

```txt
No errors
```
