### ISSUE TITLE
Number entity update not shown in Home Assistant frontend

### ISSUE THREAD

**Issue by alve89** [esphome/issues#2834]
### The problem

I have a button and a number entity (YAML see below). A press of the button entity sets the new value to the number entity properly, but the display is not updated, not even on a refreshing of the page.
![image](https://user-images.githubusercontent.com/11487054/146348998-86fefcde-2388-49e7-9af1-4e25bf0ec8e8.png)

Is there anything else I need to configure to update the displayed value of the slider as well?

### Which version of ESPHome has the issue?

2021.12.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.2

### What platform are you using?

ESP8266

### Board

ESP-01

### Component causing the issue

Number

### Example YAML snippet

```yaml
button:
    # This is the digital button which is the equivalent of the physical button
  - platform: template
    name: "esp01s01_publicButton"
    id: "publicButton"
    on_press:
    - number.set:
        id: esp01s01_testSlider
        value: 1

number:
  - platform: template
    name: "testSlider"
    id: "esp01s01_testSlider"
    min_value: 0
    max_value: 5
    step: 1
    set_action:
      then:
```
```


### Anything in the logs that might be useful for us?

```
[10:50:35][D][button:013]: 'esp01s01_publicButton' Pressed.
[10:50:35][D][number:010]: 'testSlider' - Setting
[10:50:35][D][number:029]:   Value: 1.000000
```


### Additional information

I also tried to store the current value (so the number of clicks) of the button in a `global` variable and set this value for the slider - also no success. Neither the slider itself nor the number next to it shows anything else than `0`.
