### ISSUE TITLE
Documentation example issue for local packages

### ISSUE THREAD

**Issue by raidnet-ms** [esphome/issues#2840]
### The problem

In the documentation is reported an example that will not work as expected.

[Here](https://esphome.io/guides/configuration-types.html#config-substitutions) where the "wifi include" from a subfolder (/common):

```
# In config.yaml
substitutions:
  node_name: mydevice
  device_verbose_name: "My Device"

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
```

would not let the secrets to be loaded from the root secret file.
```
# In common/wifi.yaml
wifi:
  ssid: "your_ssid"
  password: !secret wifi_password
  domain: .yourdomain.lan
  fast_connect: true
```
  
Since with esphome 2021.12.x the secrets.yaml file must be placed in esphome files root or the "new device" configuration wizard would not be able to take values from it, I think that it should be found a way to let the subfolder common/wifi.yaml be able to reach the root secrets.yaml.

### Which version of ESPHome has the issue?

2021.12.x

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12

### What platform are you using?

any

### Board

any

### Component causing the issue

nesting wifi yaml files

### Example YAML snippet

```yaml
packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
```
