### ISSUE TITLE
restore_from_flash doesn't work

### ISSUE THREAD

**Issue by lexxnsk** [esphome/issues#2843]
### The problem

When I put restore_from_flash:true to my config - it enables led every time after power cycle, regardless of the previous state.
SO function doesn't work as expected.

### Which version of ESPHome has the issue?

2021.12.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Example YAML snippet

```yaml
esphome:
  name: ledbottle

esp8266:
  board: d1_mini
  restore_from_flash: true
```
