### ISSUE TITLE
xiaomi mijia got temperature/humidity but not sending status to HA

### ISSUE THREAD

**Issue by artek458** [esphome/issues#285]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio
**ESP (ESP32/ESP8266, Board/Sonoff):**
nodemcu-32s

**Affected component:**

https://esphome.io/components/sensor/xiaomi_mijia.html

**Description of problem:**

It seems that esphome doesn't send humidity, temperature and battery status to HA.
I can see in logs that xiaomi sends status to esp32:

> [D][esp32_ble_tracker:357]: Xiaomi MiJia 58:2D:34:31:F9:0D Got temperature=22.2°C, humidity=49.9%

But its not appears in HA. I integrate this node as any else before and have new entities but status is unknown.
Just for test, I added wifi signal sensor to the same node - working perfect and all data appears on home assistant apart of temp and humidity.
**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```esphome:
  name: esp32_xiaomi
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: 'ABC
  password: '123'
  manual_ip:
    static_ip: 192.168.1.81
    gateway: 192.168.1.1
    subnet: 255.255.255.0   

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:

sensor:
  - platform: xiaomi_mijia
    mac_address: 67:47:D7:FF:50:21
    temperature:
      name: "Xiaomi MiJia Temperature"
    humidity:
      name: "Xiaomi MiJia Humidity"
    battery_level:
      name: "Xiaomi MiJia Battery Level"
  - platform: wifi_signal
    name: "Xiaomi WiFi Signal Sensor"
    update_interval: 60s      

**Traceback (if applicable):**
<!--
Please copy the traceback here if compilation is failing. If possible, also connect to the ESP over USB and copy its logs into the backticks.
-->
```

```

**Additional information and things you've tried:**




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
