### ISSUE TITLE
sim800l plugin is incompatible newer cellular modules 

### ISSUE THREAD

**Issue by jraynes** [esphome/issues#2850]
### The problem

With the [impending shutdown of 2G cellular services](https://www.digi.com/blog/post/2g-3g-4g-lte-network-shutdown-updates)  I wanted to bring attention to the fact that the sim800l component in esphome does not work with newer LTE modules from Simcom. 

I have [this SIM7080G module from aliexpress](https://www.aliexpress.com/item/4001035720662.html). Instead of 2G GSM it uses LTE CAT-M which is fairly future proof from what I understand. According to Simcom's website[this module is "compatible with SIM868"](https://www.simcom.com/product/SIM7080G.html). In my own testing I can confirm this module uses the same AT commands defined in 3GPP TS 27.005 to send and receive text messages. But when I connect the module to my esp board via UART serial it does not seem to talk to the module at all:

```
[16:51:32][C][sim800l:279]: SIM800L:
[16:51:32][C][sim800l:280]:   RSSI: 0 dB
```

the entities are discovered in homeassistant however their states are stuck on "unknown" status.

I realized the default line speed for the SIM7080 module is 115200 baud so I tried to set that in my esphome YAML like so:

```
uart:
  baud_rate: 115200
  tx_pin: TX
  rx_pin: RX
```

But when I try to install it looks like the speed is hard coded in esphome:

```
INFO Reading configuration /config/esphome/modem.yaml...
Failed config


uart: [source /config/esphome/modem.yaml:48]
  - [source /config/esphome/modem.yaml:48]
    
    Component sim800l required baud rate 9600 for the uart bus.
    baud_rate: 115200 [source /config/esphome/modem.yaml:49]
    tx_pin: 
      number: 1
      mode: 
        output: True
        input: False
        open_drain: False
        pullup: False
        pulldown: False
      inverted: False
    rx_pin: 
      number: 3
      mode: 
        input: True
        output: False
        open_drain: False
        pullup: False
        pulldown: False
      inverted: False
    rx_buffer_size: 256
    stop_bits: 1
    data_bits: 8
    parity: NONE

```

I would love to see esphome support these newer modules. I have several laying around and would be happy to help with this effort.

### Which version of ESPHome has the issue?

v2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.3

### What platform are you using?

ESP32

### Board

esp32devkitv1

### Component causing the issue

sim800l

### Example YAML snippet

```
esphome:
  name: modem
  platform: ESP32
  board: esp32dev

logger:
 baud_rate: 0
 level: debug

api:
  services:
  - service: send_sms
    variables:
      recipient: string
      message: string
    then:
    - sim800l.send_sms:
        recipient: !lambda 'return recipient;'
        message: !lambda 'return message;'
  - service: dial
    variables:
      recipient: string
    then:
    - sim800l.dial:
        recipient: !lambda 'return recipient;'

text_sensor:
- platform: template
  id: sms_sender
  name: "Sms Sender"
- platform: template
  id: sms_message
  name: "Sms Message"

uart:
  baud_rate: 115200
  tx_pin: TX
  rx_pin: RX

sim800l:
  on_sms_received:
  - lambda: |-
      id(sms_sender).publish_state(sender);
      id(sms_message).publish_state(message);

```

**Comment by dougle03** [comment]
Have you tried this on a more recent version of ESPHome? I note you're using an Oct 21 build.... 
This may not solve your problem, but it's an obvious step to take.

**Comment by jesserockz** [comment]
There is a validation on the sim800l which enforces the baud rate.

Try changing these lines, either change the baud, or remove baud=9600 to not care.

https://github.com/esphome/esphome/blob/e152f128c8ed2975aa410ccde0ab85df3d3d8f4e/esphome/components/sim800l/__init__.py#L43-L45

**Comment by jraynes** [comment]
@jesserockz when I remove the line setting the baud rate I get:

```
INFO Reading configuration /config/esphome/modem.yaml...
Failed config

uart: [source /config/esphome/modem.yaml:48]
  
  'baud_rate' is a required option for [0].
  - [source /config/esphome/modem.yaml:49]
    tx_pin: TX
    rx_pin: RX
```

```
and when I try to set the baud rate to anything other than 9600 I get:

INFO Reading configuration /config/esphome/modem.yaml...
Failed config

uart: [source /config/esphome/modem.yaml:48]
  - [source /config/esphome/modem.yaml:48]
    
    Component sim800l required baud rate 9600 for the uart bus.
    baud_rate: 115200 [source /config/esphome/modem.yaml:49]
```

**Comment by jraynes** [comment]
@dougle03 I do not see an upgrade available:
![image](https://user-images.githubusercontent.com/17382944/147147055-b636397e-9e09-4307-8c60-118ba92e3493.png)

**Comment by jesserockz** [comment]
Can you try add this to your yaml:

```yaml
external_components:
  - source: github://esphome/esphome@sim800-remove-baud-rate-validation
    components: ["sim800l"]
```
