### ISSUE TITLE
esphome linter does not highlight correct section

### ISSUE THREAD

**Issue by nightweyr** [esphome/issues#2866]
### The problem

I am on esphome v2021.12.1 and was trying to test the emporia vue integration. 

This is a subset of the yaml that I was importing. esphome linter complains that `esphome: name` is invalid for this framework.

```yaml
esphome:
  name: test123

esp32:
  board: d-duino-32
  framework:
    type: esp-idf
    version: recommended

# Common section begin
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

# Enable logging
logger:

# FIXME web_server won't work
web_server:
```
esphome run for this yaml returned this error, without highlighting the correct section:

```
INFO Reading configuration /config/esphome/test123.yaml...
Failed config

json: None
  {}
async_tcp: None
  {}
```
After some trial and error, the problematic section was narrowed down to `webserver`. esphome linter has generally been very good about picking up where the problem is, but in this case, it was not able to determine the correct block.

### Which version of ESPHome has the issue?

2021.12.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
esphome:
  name: test123

esp32:
  board: d-duino-32
  framework:
    type: esp-idf
    version: recommended

# Common section begin
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

# Enable logging
logger:

# FIXME web_server won't work
web_server:
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/test123.yaml...
Failed config

json: None
  {}
async_tcp: None
  {}
```
```


### Additional information

_No response_
