### ISSUE TITLE
Cant add a Delay to Script without getting an error

### ISSUE THREAD

**Issue by DaveTiff** [esphome/issues#2867]
### The problem

Trying to add a delay to a script, put in the place according to 

[https://esphome.io/guides/automations.html?highlight=script](url) delay action

See below my Yamal & Error message

### Which version of ESPHome has the issue?

2021.10.3 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.4

### What platform are you using?

ESP8266

### Board

Sonoff POW

### Component causing the issue

Script

### Example YAML snippet

```yaml
script:
  - id: relayoff
    then:
      - delay: 1ms       
      if:
        condition:
          or:
            # If any of the Psudo switches are On (acc1, acc2, acc3)
            - switch.is_on: acc1
            - switch.is_on: acc2
            - switch.is_on: acc3            
        then:
  
        else:
          - switch.turn_off: relay
```

### Anything in the logs that might be useful for us?

```txt
ERROR Error while reading config: Invalid YAML syntax:

while parsing a block collection
  in "/config/esphome/sonoff-pow-aux.yaml", line 119, column 7:
          - delay: 1ms       
          ^
expected <block end>, but found '?'
  in "/config/esphome/sonoff-pow-aux.yaml", line 120, column 7:
          if:
          ^
```

**Comment by jesserockz** [comment]
The issue is not the delay, the issue is that your `if` is not indented and needs a `-` to be a part of the action list properly.

```yaml
script:
  - id: relayoff
    then:
      - delay: 1ms       
      - if:
          condition:
            or:
              # If any of the Psudo switches are On (acc1, acc2, acc3)
              - switch.is_on: acc1
              - switch.is_on: acc2
              - switch.is_on: acc3            
          then:
            ...
          else:
            - switch.turn_off: relay
```
