### ISSUE TITLE
SH1106 128x64 I2C Display not working correctly 

### ISSUE THREAD

**Issue by lordfiSh** [esphome/issues#287]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
NodeMCU Lua Lolin V3 Module ESP8266 ESP-12E

**Affected component:**
https://esphome.io/components/display/ssd1306.html

**Description of problem:**
Only a few lines are working, updating works too, rest is garbage
https://media.discordapp.net/attachments/429907082955718657/572140538900512769/unknown.png

maybe relevant:

- https://github.com/keirf/FlashFloppy/issues/219
- https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/issues/228

**Problem-relevant YAML-configuration entries:**
```yaml
i2c:
  sda: D1
  scl: D2
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(font), "Hello World!");
```

**Traceback (if applicable):**
n/a
```

```

**Additional information and things you've tried:**
n/a
