### ISSUE TITLE
Nextion Editor Simulator Connection

### ISSUE THREAD

**Issue by Londoneye02** [esphome/issues#2872]
### The problem

I try to connect to the Nextion Editor Simulator ("Debug") feature. This is to avoid having to deal with the physical screen (to avoid any damage) and because is just faster to do it this way.

ESPHome Logs shows the following:

```
[12:10:29][W][nextion:072]: Nextion is not connected! 
[12:10:29][E][uart:015]: Reading from UART timed out at byte 0!
```

And Nextion Editor 

![image](https://user-images.githubusercontent.com/29100907/147348057-d0532022-12d8-4e10-943f-13fa756ff2ec.png)

Connecting to a real screen with the exact same tft file works OK.

ESPHome logs show the following

```
[12:14:14][C][nextion:117]: Nextion:
[12:14:14][C][nextion:118]:   Device Model:     NX4832K035_011R
[12:14:14][C][nextion:119]:   Firmware Version: 163
[12:14:14][C][nextion:120]:   Serial Number:    ---------------------
[12:14:14][C][nextion:121]:   Flash Size:       33554432
[12:14:14][C][nextion:122]:   Wake On Touch:    True

```

I guess ESPHome tries to get this info at startup and the simulator does not provide it...

Is there a way to override this?

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

Nextion

### Example YAML snippet

```yaml
esphome:
  name: esphomethermo-v0
  platform: ESP8266
  board: d1_mini_lite

# Enable logging
logger:
  baud_rate: 0     # Disable UART logging (pins GPIO1/3 are used for Nextion communication)
  
uart:
  id: uart_1
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  
 
# Enable Home Assistant API
api:

ota:
  password: !secret OTA_password

wifi:
  ssid: !secret Wifi_ssid
  password: !secret Wifi_password
  
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.31
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphomethermo-V0"
    password: !secret OTA_password

captive_portal:


    
display:
  - platform: nextion
    id: nextion1
    update_interval: 5s
    uart_id: uart_1
    lambda: |-
      it.set_component_value("dActualTemp", 50);
      it.set_component_text("t0", "Hello World!");
```

### Anything in the logs that might be useful for us?

```txt
[12:10:29][W][nextion:072]: Nextion is not connected! 
[12:10:29][E][uart:015]: Reading from UART timed out at byte 0!
```
