### ISSUE TITLE
Incorrect number set when setting large numbers

### ISSUE THREAD

**Issue by johanericandersson** [esphome/issues#2875]
### The problem

When I try to set a number-entity, from Home Assistant, so it increases or decreases with another digit when dealing with numbers larger than 7 digits, the digits after the 7th gets all 0.
This happens only when the number increases or decreases with a digit, after that I can set the correct number and even change the number to a different one as long as the number of digits doesn't change.

E.g. changing from 9015153 to 90151534 results in 90151530. Changing from 9015153454 results in 9015153000.

### Which version of ESPHome has the issue?

2021.12.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.5

### What platform are you using?

ESP8266

### Board

lolin nodemcu v3

### Component causing the issue

number

### Example YAML snippet

```yaml
number:
  - platform: template
    name: ${device_name}_counter_lane1
    id: ${device_name}_counter_lane1
    optimistic: true
    min_value: -1
    max_value: 9000000000000000
    step: 1
    initial_value: -1

binary_sensor:
  - platform: gpio
    name: ${device_name}_lane1
    id: ${device_name}_lane1
    pin:
      number: GPIO14
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      lambda: |-
        if (id(${device_name}_counter_lane1).state >= 0) {
          auto call = id(${device_name}_counter_lane1).make_call();
          call.set_value(id(${device_name}_counter_lane1).state + 1);
          call.perform();
        }
```
