### ISSUE TITLE
Waveshare 7.5inV2 Not Working

### ISSUE THREAD

**Issue by lux4rd0** [esphome/issues#2880]
### The problem

I have one of the newer 7.5 inch V2 e-ink devices and I'm trying to make it work with ESPHome. It seems that there have been several other users experiencing the same issue - and a few older closed out Incidents as well:

- https://github.com/esphome/issues/issues/1296
- https://community.home-assistant.io/t/waveshare-e-ink-7-5-with-waveshare-esp32-wroom-32-controler/151346/14
- https://github.com/esphome/issues/issues/2216
- https://github.com/esphome/issues/issues/2121 (smaller display)

I've tried several different pin combinations and none of them bring to life the e-ink device. I have a Waveshare 4.2in that works just fine. I took all of those same configurations and was hoping to plug in my 7.5inV2 and - no go. I even tried several other pin examples from posts - and those didn't work either.

### Which version of ESPHome has the issue?

v2021.12.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.5

### What platform are you using?

ESP32

### Component causing the issue

Waveshare 7.5inV2

### Example YAML snippet

```yaml
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

display:
  - platform: waveshare_epaper
    id: esp13_epaper
    cs_pin: GPIO5
    dc_pin: GPIO19
    busy_pin: GPIO16
    reset_pin: GPIO17
    model: 7.50inV2
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
Nothing in the logs...

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

display:
  - platform: waveshare_epaper
    id: esp12_epaper
    cs_pin: GPIO12
    busy_pin: GPIO33
    reset_pin: GPIO21
    dc_pin: GPIO27
    model: 4.20in
    update_interval: 60s

This ^^^ works fine for the 4.2in product. Changing the model to 7.50inV2 should be all I need to do to make it work with the 7.5 inch V2 model... But it doesn't. I've used two brand new boards from Waveshare - assumed the first one was defective.
```

### Additional information

Ran through all of the Raspberry Pi demo examples - https://www.waveshare.com/wiki/7.5inch_e-Paper_HAT - worked fine. At this point, the hardware seems to be showing okay - it's just the ESPHome component that isn't working.
