### ISSUE TITLE
state_class 'total' not valid

### ISSUE THREAD

**Issue by Bascht74** [esphome/issues#2881]
### The problem

I try to set the state_class to `total` as described in the HA documentation here: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

But I get an error:
![image](https://user-images.githubusercontent.com/66269310/147611835-59c68d3c-a344-4df7-b713-9201f2771a84.png)
![image](https://user-images.githubusercontent.com/66269310/147611860-068b86e9-da56-4647-9325-1b375a5283c1.png)

According to the documentation of esphome total should be valid:

> state_class (Optional, string): The state class for the sensor. See https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes for a list of available options. Set to "" to remove the default state class of a sensor.

### Which version of ESPHome has the issue?

2021.12.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

./.

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

sensor

### Example YAML snippet

```yaml
- platform: dsmr
    energy_delivered_lux:
      name: ${upper_devicename} Energy Consumed Total
      id: energy_consumed_total
      state_class: "total"
      device_class: "energy"
      unit_of_measurement: "KWh"
```
