### ISSUE TITLE
Changing measurement parameters changes readings 

### ISSUE THREAD

**Issue by severeski** [esphome/issues#2886]
### The problem

When I change above and below for a ADC sensor i get different measurements.

![weird1](https://user-images.githubusercontent.com/11256474/147753606-37c18d40-3a94-4162-951a-092a61e0f0b7.png)

![weird2](https://user-images.githubusercontent.com/11256474/147753644-28775217-9f22-44c0-9e58-da32a85a2455.png)

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.12.7

### What platform are you using?

ESP32

### Board

nodemcu

### Example YAML snippet

```yaml
sensor:
  - platform: adc
    pin: GPIO33
    name: "Bed Sensor"
    update_interval: 1s
    attenuation: 11db
    on_value_range:
#     - above: 3.00
     - above: 2.01     
       then:
        - homeassistant.service:
           service: input_boolean.turn_on
           data:
            entity_id: input_boolean.bed_occupied
#     - below: 2.5
     - below: 2.00
       then:
        - homeassistant.service:
           service: input_boolean.turn_off
           data:
            entity_id: input_boolean.bed_occupied
```

### Additional information

The change of the parameters above / below changes the readout as shown in screenshots.
