### ISSUE TITLE
Incorrect VCC value on NodeMCU with dev version / 1.13.0-dev?

### ISSUE THREAD

**Issue by fredrikbaberg** [esphome/issues#289]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

 Add-on version: dev
 You are running the latest version of this add-on.
 System: HassOS 2.11  (armv7 / raspberrypi3)
 Home Assistant version: 0.92.2
 Supervisor version: 162

ESPHome version: 1.13.0-dev

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCUv2 8266 (may not be original, purchased from AliExpress a few years ago).

**Affected component:**

https://esphome.io/components/sensor/adc.html?highlight=adc#esp8266-measuring-vcc

**Description of problem:**

The `adc` component reports `64.0V`.
I'm powering the board through USB from either USB powerbank, computer or Raspberry Pi, tried with two different boards, and got the same result.

This seems to only occur using the 1.13.0-dev version, see Additional information.

**Problem-relevant YAML-configuration entries:**
```yaml

esphome:
  name: red
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_key
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_password

# Enable OTA updates
ota:
  password: !secret esphome_password

sensor:
- platform: adc
  pin: VCC
  name: "Red VCC Voltage"

text_sensor:
  - platform: version
    name: "ESPHome Version"

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

I started each of the Add-on version with the following common setting:
```
{
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "streamer_mode": true
}
```
Between each test I removed the build folder (`config/esphome/red/` in my case), since I encountered issues otherwise. Upload was done using USB (not OTA).

Result:

Add-on
- ESPHome (dev):
  ```
  'ESPHome Version': Sending state '1.13.0-dev May  4 2019, 11:46:08'
  'Red VCC Voltage': Got voltage=64.00V
  ```
- ESPHome (beta):
  ```
  'ESPHome Version': Sending state '1.12.2 May  4 2019, 11:51:58'
  'Red VCC Voltage': Got voltage=2.96V
  ```
- ESPHome:
  ```
  'ESPHome Version': Sending state '1.12.2 May  4 2019, 11:57:33'
  'Red VCC Voltage': Got voltage=2.96V
  ```
