### ISSUE TITLE
Could not use ADC GPIO on ESP32-DOIT-DEVKIT-V1(30pin)

### ISSUE THREAD

**Issue by huishizhao** [esphome/issues#2900]
### The problem

I have a ESP-WROOM-32 board with 30 GPIO pins, I checked the Pin out was same as ESP32-DOIT-DEVKIT-V1(30Pin), I would like to use GPIO13 and 15 to collect soil moisture, the config error  to ESP32 doesn't support ADC on this pin.
![99c36ea684b9d479f26a99b929566d109f7443dc](https://user-images.githubusercontent.com/80588197/147894722-f56f5ee9-f2df-4291-a09a-7e96f8cfe5ed.png)

 I check all board configuration in ESPHOME, as document description, ADC GPIO only allows GPIO 32-39. 
How to use ESPHOME ADC on a ESP32 board with 30 GPIO Pins?

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.4

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1(30Pin)

### Component causing the issue

adc

### Example YAML snippet

```yaml
esphome:
  name: soil-moisture
  platform: ESP32
  board: esp32doit-devkit-v1

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "cb6d103aa9453606479d64d9291f5c16"

wifi:
  ssid: "TP-LINK_*****"
  password: "********"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Soil-Moisture Fallback Hotspot"
    password: "LWFqQEmUl2bv"

captive_portal:
sensor:
  - platform: adc
    pin: GPIO13
    name: "soilmoisturesensor1"
    update_interval: 10s
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/soil-moisture.yaml...
Failed config

sensor.adc: [source /config/esphome/soil-moisture.yaml:26]
  platform: adc
  
  ESP32 doesn't support ADC on this pin.
  pin: GPIO13 [source /config/esphome/soil-moisture.yaml:27]
  name: soilmoisturesensor1
  update_interval: 10s
```
