### ISSUE TITLE
Problem with restoring  switch state on esp32 while rebooting / power cycling 

### ISSUE THREAD

**Issue by satekp** [esphome/issues#2910]
### The problem

After updating esphome to latest release (2021.12.3) . Switch output state is not restoring after reboot or power cycle .
  device: esp32 devlop board
  

### Which version of ESPHome has the issue?

2021.12.3 rel

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.12.7

### What platform are you using?

ESP32

### Board

doit esp32 dev-board v1. 

### Component causing the issue

switch platform gpio

### Example YAML snippet

```yaml
switch:
  - platform: gpio
    pin:
      number: 23
      inverted: true
    name: "LED1"
    id: swch1
    #restore_mode: RESTORE_DEFAULT_OFF
    
  - platform: gpio
    pin:
      number: 19
      inverted: true
    name: "LED2"
    id: swch2
    restore_mode: RESTORE_DEFAULT_OFF
```
