### ISSUE TITLE
sonoff basic OTA not working

### ISSUE THREAD

**Issue by jpgimenez** [esphome/issues#2921]
### The problem

I'm having problem with my sonoff basics updating OTA,

```
[D][ota:305]: OTA in progress: 0.3%

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 3584, room 16 
tail 0
chksum 0x30
csum 0x30
csum err
ets_main.c 
```
 the update works with a serial connector... 

### Which version of ESPHome has the issue?

v2021.12.3

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

sonoff basic

### Example YAML snippet

```yaml
esphome:
  name: test1
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi-ssid
    password: !secret wifi-password
    priority: 15
  - ssid: !secret wifi-ssid2
    password: !secret wifi-password2
    priority: 10
  power_save_mode: none

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
web_server:
  port: 80

binary_sensor:
  - platform: status
    name: "System Status"

# Example configuration entry
sensor:
  - platform: uptime
    name: "System Uptime"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
  - platform: restart
    name: "Restart"

output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO13
      inverted: True
```

### Anything in the logs that might be useful for us?

```txt
[D][ota:305]: OTA in progress: 0.3%

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 3584, room 16 
tail 0
chksum 0x30
csum 0x30
csum err
ets_main.c
```

### Additional information

I tested from my laptop, a pip installation, and also from home-assistant add-on, it fails the same way, sometimes sooner, sometimes later, but it fails.
