### ISSUE TITLE
Build fails when trying to use lambda on binary_sensor

### ISSUE THREAD

**Issue by nikolai5slo** [esphome/issues#2922]
### The problem

I want to negate binary sensor on "modbus_controller" platform. Since there is no invert because there are no pins on "modbus_controller" I tried to accomplish this with lambda. But when I try to use lambda build fails with following error:
```
esp_controller_1.yaml:395:4: error: no matching function for call to 'esphome::modbus_controller::ModbusBinarySensor::set_template(setup()::<lambda(esphome::modbus_controller::ModbusBinarySensor*, float, const std::vector<unsigned char>&)>)'
```

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

*

### What platform are you using?

ESP32

### Board

esp32dev (Prodino ESP)

### Component causing the issue

binary_sensor

### Example YAML snippet

```yaml
binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: relayboard1
    id: window_1
    name: "Window 1"
    device_class: window
    register_type: holding
    address: 0x82
    lambda: !lambda |-
      return !x;
```

### Anything in the logs that might be useful for us?

```txt
esp_controller_1.yaml: In function 'void setup()':
esp_controller_1.yaml:395:4: error: no matching function for call to 'esphome::modbus_controller::ModbusBinarySensor::set_template(setup()::<lambda(esphome::modbus_controller::ModbusBinarySensor*, float, const std::vector<unsigned char>&)>)'
In file included from src/esphome.h:18:0,
                 from src/main.cpp:3:
src/esphome/components/modbus_controller/binary_sensor/modbus_binarysensor.h:36:8: note: candidate: void esphome::modbus_controller::ModbusBinarySensor::set_template(esphome::modbus_controller::ModbusBinarySensor::transform_func_t&&)
   void set_template(transform_func_t &&f) { this->transform_func_ = f; }
        ^
src/esphome/components/modbus_controller/binary_sensor/modbus_binarysensor.h:36:8: note:   no known conversion for argument 1 from 'setup()::<lambda(esphome::modbus_controller::ModbusBinarySensor*, float, const std::vector<unsigned char>&)>' to 'esphome::modbus_controller::ModbusBinarySensor::transform_func_t&& {aka esphome::optional<std::function<esphome::optional<bool>(esphome::modbus_controller::ModbusBinarySensor*, bool, const std::vector<unsigned char>&)> >&&}'
```

**Comment by martgras** [comment]
Thanks - the compile bug will be fixed in PR#3020 
However you don't need a lambda and can use the invert filter

```yaml
binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: relayboard1
    id: window_1
    name: "Window 1"
    device_class: window
    register_type: holding
    address: 0x82
    filters:
      - invert:
```
