### ISSUE TITLE
ESP32 w/ TSL2561 crashes at high brightness

### ISSUE THREAD

**Issue by LeonEmm** [esphome/issues#2923]
### The problem

Hello everybody,

recently I changed from ESPEasy to ESPHome due a migration to Homeassistant. I have to ESP32 with a TSL2561 to measure my outside brightness. Since the first OTA Flash to ESPHome, my Sensor crashes at high Brigntess (>10,000lux). With the ESPEasy firmware nothing changed.
When the sensor crashes, the ESP is still reachable but is reporting 0lx. This happens on two ESP-Instances with the same configuration. Has anyone an Idea, why this happens?

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.8

### What platform are you using?

ESP32

### Board

ESP32 esp-wrover-kit

### Component causing the issue

TSL2561

### Example YAML snippet

```yaml
esphome:
  name: brightsouth
  platform: ESP32
  board: esp-wrover-kit

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  safe_mode: true
  password: "ascan"

wifi:
  ssid: "****"
  password: "****"
  reboot_timeout: 5min
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: ***.***.***.***
    # Set this to the IP address of the router. Often ends with .1
    gateway: ***.***.***.***
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Brighteast Fallback Hotspot"
    password: "*****"

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  frequency: 100kHz
  
sensor:
  - platform: tsl2561
    name: "Sensor South"
    address: 0x29
    update_interval: 240s
    integration_time: 14ms
    
binary_sensor:
  - platform: status
    name: "Sensor South Status"

button:
  - platform: restart
    name: "Sensor South Restart"
```

### Anything in the logs that might be useful for us?

```txt
No Error Messages reported.
```
