### ISSUE TITLE
Repeat turns into infinite loop if triggered again while first sequence still running.

### ISSUE THREAD

**Issue by MikeS1976** [esphome/issues#2929]
### The problem

On one of my ESPs i have a service that opens a door, and flashes a light for 15 times, then closed the door.
If the service is re-triggered while the light flashing is still running, it turns into an endless loop. (see first part of snippet below)

if i replace the repeat by the 2nd part of the snippet below and retrigger it does not end up in a loop.....:

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.8

### What platform are you using?

ESP8266

### Board

wemos d1 mini

### Component causing the issue

-

### Example YAML snippet

```yaml
api:
  services:
    - service: service_open_door
      then:
        - switch.turn_on: open_door
        - repeat:
            count: 15
            then:
              - light.turn_on: light_led_blue
              - delay: 0.1s
              - light.turn_off: light_led_blue
              - delay: 0.1s
        - switch.turn_off: open_door






`        - switch.turn_on: open_door
        - light.turn_on: light_led_blue
        - delay: 0.15s
        - light.turn_off: light_led_blue
        - delay: 0.15s
        - light.turn_on: light_led_blue
        - delay: 0.15s
        - light.turn_off: light_led_blue
        - delay: 0.15s
        - light.turn_on: light_led_blue
        - delay: 0.15s
        - light.turn_off: light_led_blue
        - delay: 0.15s
        - light.turn_on: light_led_blue
        - delay: 0.15s
        - light.turn_off: light_led_blue
        - delay: 0.15s
        - light.turn_on: light_led_blue
        - delay: 0.15s
        - light.turn_off: light_led_blue
        - delay: 0.15s
        - light.turn_on: light_led_blue
        - delay: 0.15s
        - light.turn_off: light_led_blue
        - delay: 0.15s
        - light.turn_on: light_led_blue
        - delay: 0.15s
        - light.turn_off: light_led_blue
        - delay: 0.15s
        - light.turn_on: light_led_blue
        - delay: 0.15s
        - light.turn_off: light_led_blue
        - delay: 0.15s
        - light.turn_on: light_led_blue
        - delay: 0.15s
        - light.turn_off: light_led_blue
        - delay: 0.15s
        - light.turn_on: light_led_blue
        - delay: 0.15s
        - light.turn_off: light_led_blue
        - delay: 0.15s
        - switch.turn_off: open_door`     
```

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

-
