### ISSUE TITLE
TCS34725 broke with recent changes, endian is wrong

### ISSUE THREAD

**Issue by ceandraka** [esphome/issues#2930]
### The problem

Previously working code to determine color of LED (red or green) now fails, and return values for RGB and clear are very small.

Loading a copy of 2021.10.3 or older as a custom component (change name throughout) fixes the issue. Expected percentages are in the range of 10-40%, but with new version they are well under 0.1%. Using older version of TCS34725 as custom component restores proper operation.

Pull request https://github.com/esphome/esphome/pull/2445 indicates that endian was swapped because documentation showed little endian in ESP but big endian in I2C. this was implemented on lines 185-190 in TCS34725.cpp. However, this calls read_byte_16 in i2c.cpp, which in turn calls read_bytes_16, which has the endian swap already.

Please remove lines 185-190 in the newest TCS34725.cpp to fix this issue.

Thanks

### Which version of ESPHome has the issue?

2021.11.0 and later

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.7

### What platform are you using?

ESP32

### Board

d1 mini and TCS34725

### Component causing the issue

TCS34725

### Example YAML snippet

```yaml
- platform: tcs34725old
    red_channel:
      name: "TCS34725 Red"
      internal: true
      id: red_bright

    green_channel:
      name: "TCS34725 Green"
      internal: true
      id: green_bright

    clear_channel:
      name: "TCS34725 Clear"
      internal: true
      id: clear_bright

    blue_channel:
      name: "TCS34725 Blue"
      internal: true
      id: blue_bright
      on_value:
        then:
          - script.execute: read_colors

    gain: 60x
#    integration_time: 2.4ms
    integration_time: 101ms
    address: 0x29
    update_interval: 200ms
```

### Anything in the logs that might be useful for us?

```txt
No error message, just wrong values for RGB and Clear
```

**Comment by ceandraka** [comment]
I took latest version (2021.12.3), copied files for tcs34725 to my external components directory, removed the 4 offending lines, tested, and it works properly. I will run this as an external component until it is fixed. Just lines 185-190 were commented out.

**Comment by martgras** [comment]
This should work as well now 
```yaml
external_components:
  - source: github://pr#3037
    refresh: 1h
    components: ["tcs34725"]
```
My PR removed the duplicate conversion - exactly the change you described - Thanks for debugging it to that level
Can't test but I don't expect a problem
