### ISSUE TITLE
ESP32 C3 devkit is not working

### ISSUE THREAD

**Issue by TAMCTec** [esphome/issues#2931]
### The problem

I download esphome from hassio, and run the first test with esp32 c3, with esp-idf framework. I haven't add any component yet, just the simple setup. After installed, it seem keep rebooting, printing the following information again and again.
```
[12:33:54]ESP-ROM:esp32c3-api1-20210207
[12:33:54]Build:Feb  7 2021
[12:33:54]rst:0x7 (TG0WDT_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
[12:33:54]Saved PC:0x40049a42
[12:33:54]SPIWP:0xee
[12:33:54]mode:QIO, clock div:1
[12:33:54]load:0x3fcd6100,len:0x17f4
[12:33:54]ets_loader.c 78
```

### Which version of ESPHome has the issue?

2021.12.3 dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2021.12.8

### What platform are you using?

ESP32-IDF

### Board

esp32-c3-devkitM-1

### Component causing the issue

None

### Example YAML snippet

```yaml
esphome:
  name: c3test

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "*********************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "C3Test Fallback Hotspot"
    password: "V6OmdKMap4I5"

# captive_portal:
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

**Comment by martgras** [comment]
Can you try if this works for you
```yaml
esphome:
  name: c3test
  platformio_options:
    board_build.flash_mode: dio  
esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

```

**Comment by martgras** [comment]
I think this is https://github.com/platformio/platform-espressif32/issues/622   because the fix hasn't merged into master

**Comment by markusg1234** [comment]
I have a similar issue if using ESP flasher to load the firmware. Also in the console it displays invalid header 0xffffffff.

Connecting the ESP32C3 to my Hass server and programing via USB works correctly.

**Comment by TAMCTec** [comment]
@martgras Yes it totally fix my problem! Thank you!

**Comment by TAMCTec** [comment]
@markusg1234 i have the similar problem before, have you try to erase flash before install?

**Comment by TAMCTec** [comment]
As my problem solved, I’m closing this issue.

**Comment by platima** [comment]
Yeah making it DIO worked for me

**Comment by mdaviesnz** [comment]
@platima Did you do anything else? Setting DIO didn't help in my case with a Wemos ESP32-C3

**Comment by platima** [comment]
For that exact issue all I did was DIO, but for my ESP32-C3 I ended up using a pile of changes in my YAML. Here's my header;

```
external_components:
  - source: github://pr#3454
    components:
      - deep_sleep

esphome:
  name: s01-blue
  comment: DFRobot Beetle monitoring garden status, solar powered w/ battery. Labelled Sensor01
  platformio_options:
    board_build.flash_mode: dio
    platform_packages:
      - espressif/toolchain-riscv32-esp @ https://github.com/Jason2866/crosstool-NG/releases/download/8.4.0/riscv32-esp-elf.tar.gz
      - espressif/toolchain-xtensa-esp32s2 @ https://github.com/Jason2866/crosstool-NG/releases/download/8.4.0/xtensa-esp32s2-elf.tar.gz
      
# Product page: https://wiki.dfrobot.com/SKU_DFR0868_Beetle_ESP32_C3#target_0
# Chip data sheet: https://www.espressif.com/sites/default/files/documentation/esp32-c3_hardware_design_guidelines_en.pdf

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
```
