### ISSUE TITLE
ESP8288 hardware UART not receiving data

### ISSUE THREAD

**Issue by escoand** [esphome/issues#2935]
### The problem

I tried to use the first hardware UART on ESP8266 but not receiving any data. Using the same configuration with any other GPIO is working without problems.

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

uart

### Example YAML snippet

```yaml
esphome:
  platform: ESP8266
  board: d1_mini

logger:
  hardware_uart: UART1

uart:
- id: uart1   # not working
  rx_pin: RX
  baud_rate: 4800
  data_bits: 8
  stop_bits: 1
  parity: ODD
- id: uart2    # working
  rx_pin: D1
  baud_rate: 4800
  data_bits: 8
  stop_bits: 1
  parity: ODD
```
