### ISSUE TITLE
GPIO pin loses LOW state during deep sleep mode

### ISSUE THREAD

**Issue by ministryofsillywalks** [esphome/issues#2939]
### The problem

I am trying to wake my ESP32 from deep sleep using "esp32_ext1_wakeup" with the mode "ANY_HIGH" 
I have various pins pulled down with the integrated resistors, as these pins are otherwise floating.
Looking at binary sensors while the esp is running they hold their low state perfectly.
However as soon as I send the esp to deep sleep it wakes up straight away again because the pins seem to return to the floating state or high and triggers the wakeup.
When connecting the pins to ground with hardware the board stays in deep sleep, but this sadly is not an option for my build outside of testing it on the breadboard.

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Board

ESP-WROOM-32

### Component causing the issue

deep sleep, gpio switch

### Example YAML snippet

```yaml
deep_sleep:
  esp32_ext1_wakeup:
    pins:
      - 13
      - 12
    mode: ANY_HIGH
  id: deep_sleep_1
  run_duration: 60min
  sleep_duration: 1440min

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode:
        input: true
        pulldown: true
    name: "13 DOWN"

    
  - platform: gpio
    pin:
      number: 12
      mode:
        input: true
        pulldown: true
    name: "12 DOWN"
```
