### ISSUE TITLE
Sensor HDC1080 communication failed!

### ISSUE THREAD

**Issue by 22MarioZ** [esphome/issues#294]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

PIO

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**Affected component:**

Sensor HDC1080

**Description of problem:**
When using the sensor HDC1080 I get the following error: 

>
[21:08:09][C][sensor.hdc1080:043]: HDC1080:
[21:08:09][C][sensor.hdc1080:044]: Address: 0x40
[21:08:09][E][sensor.hdc1080:046]: Communication with HDC1080 failed!
[21:08:09][C][sensor.hdc1080:048]: Update Interval: 60000 ms
[21:08:09][C][sensor.hdc1080:049]: Temperature 'temp'
[21:08:09][C][sensor.hdc1080:049]: Unit of Measurement: '°C'
[21:08:09][C][sensor.hdc1080:049]: Accuracy Decimals: 1
[21:08:09][C][sensor.hdc1080:049]: Icon: 'mdi:thermometer'
[21:08:09][C][sensor.hdc1080:050]: Humidity 'hum'
[21:08:09][C][sensor.hdc1080:050]: Unit of Measurement: '%'
[21:08:09][C][sensor.hdc1080:050]: Accuracy Decimals: 0
[21:08:09][C][sensor.hdc1080:050]: Icon: 'mdi:water-percent'
> 

Using the same sensor with the CloseCube library example the sensor is working without any problem.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: esp32hdc1080

esphome:
  name: $devicename
  platform: ESP32
  board: lolin32

wifi: !include common/wifi.yaml
mqtt: !include common/mqtt.yaml
ota: !include common/ota.yaml

logger:
  level: DEBUG

i2c:
  sda: 15
  scl: 13
  scan: False

sensor:
  - platform: hdc1080
    temperature:
      id: hdc1080_temp
      name: "temp"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      accuracy_decimals: 1
      filters:
        - offset: 0
    humidity:
      id: hdc1080_hum
      name: "hum"
      unit_of_measurement: "%"
      icon: "mdi:water-percent"
      accuracy_decimals: 0
    update_interval: 60s
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
