### ISSUE TITLE
fatal error: ../TypeTraits/FloatTraits.hpp: No such file or directory

### ISSUE THREAD

**Issue by dclobato** [esphome/issues#2945]
### The problem

While compiling the following code, I get the message that `FloatTraits.hpp` is missing

On the "Example YAML snippet" section, I pasted the result of `esphome config myfile.yaml`

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

does not apply

### What platform are you using?

ESP8266

### Board

sonoff pow r2

### Example YAML snippet

```yaml
substitutions:
  nomeDoNodo: tomadacabeceiradaniel
  nomeCurto: tmdcabdaniel
  dePrep: da
  emPrep: na
  NomeMaiusculas: Tomada da cabeceira do Daniel
  Nome: tomada da cabeceira do Daniel
  IP: 10.0.1.14
  GATEWAY: 10.0.1.1
  reboot_timeout: 10min
  default_state: ALWAYS_ON
esphome:
  name: tomadacabeceiradaniel
  build_path: binarios/tomadacabeceiradaniel
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
esp8266:
  board: esp01_1m
  framework:
    version: 2.7.4
    source: ~3.20704.0
    platform_version: platformio/espressif8266 @ 2.6.3
  restore_from_flash: false
  board_flash_mode: dout
logger:
  baud_rate: 0
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
  esp8266_store_log_strings_in_flash: true
uart:
- rx_pin:
    number: 3
    mode:
      input: true
      analog: false
      output: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
  baud_rate: 4800
  rx_buffer_size: 256
  stop_bits: 1
  data_bits: 8
  parity: NONE
button:
- platform: restart
  name: Reiniciar controlador da tomada da cabeceira do Daniel
  disabled_by_default: false
  entity_category: config
  device_class: restart
binary_sensor:
- platform: status
  name: Status da tomada da cabeceira do Daniel
  disabled_by_default: false
  device_class: connectivity
  entity_category: diagnostic
- platform: gpio
  pin:
    number: 0
    mode:
      input: true
      pullup: true
      analog: false
      output: false
      open_drain: false
      pulldown: false
    inverted: true
  name: Botão da tomada da cabeceira do Daniel
  on_press:
  - then:
    - switch.toggle:
        id: fakebutton
  disabled_by_default: false
switch:
- platform: safe_mode
  name: Reiniciar controlador da tomada da cabeceira do Daniel em modo de atualização
  disabled_by_default: false
  icon: mdi:restart-alert
  entity_category: config
- platform: template
  name: Tomada da cabeceira do Daniel
  icon: mdi:power-plug
  id: fakebutton
  optimistic: true
  restore_state: true
  turn_on_action:
    then:
    - switch.turn_on:
        id: relay
  turn_off_action:
    then:
    - switch.turn_off:
        id: relay
  disabled_by_default: false
  assumed_state: false
- platform: gpio
  restore_mode: ALWAYS_ON
  id: relay
  pin:
    number: 12
    mode:
      output: true
      analog: false
      input: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
  disabled_by_default: false
  interlock_wait_time: 0ms
  name: relay
  internal: true
sensor:
- platform: wifi_signal
  name: RSSI na tomada da cabeceira do Daniel
  update_interval: 10min
  disabled_by_default: false
  force_update: false
  unit_of_measurement: dBm
  accuracy_decimals: 0
  device_class: signal_strength
  state_class: measurement
  entity_category: diagnostic
- platform: uptime
  name: Uptime da tomada da cabeceira do Daniel
  unit_of_measurement: h
  update_interval: 30min
  filters:
  - lambda: !lambda |-
      return int((x + 1800.0) / 3600.0);
  disabled_by_default: false
  force_update: false
  icon: mdi:timer-outline
  accuracy_decimals: 0
  state_class: total_increasing
  entity_category: diagnostic
- platform: total_daily_energy
  min_save_interval: 3600s
  name: Energia total consumida na tomada da cabeceira do Daniel
  power_id: potencia
  filters:
  - multiply: 0.001
  unit_of_measurement: kWh
  device_class: energy
  disabled_by_default: false
  force_update: false
  state_class: total_increasing
  restore: true
  method: right
- platform: cse7766
  update_interval: 2s
  current:
    name: Corrente na tomada da cabeceira do Daniel
    filters:
    - median:
        window_size: 9
        send_every: 5
        send_first_at: 4
    - heartbeat: 30s
    - delta: 0.1
    disabled_by_default: false
    force_update: false
    unit_of_measurement: A
    accuracy_decimals: 2
    device_class: current
    state_class: measurement
  voltage:
    name: Tensão na tomada da cabeceira do Daniel
    filters:
    - median:
        window_size: 9
        send_every: 5
        send_first_at: 4
    - heartbeat: 30s
    - delta: 0.1
    disabled_by_default: false
    force_update: false
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement
  power:
    name: Potência na tomada da cabeceira do Daniel
    id: potencia
    filters:
    - median:
        window_size: 9
        send_every: 5
        send_first_at: 4
    - heartbeat: 30s
    - delta: 0.1
    disabled_by_default: false
    force_update: false
    unit_of_measurement: W
    accuracy_decimals: 1
    device_class: power
    state_class: measurement
  energy:
    name: Energia na tomada da cabeceira do Daniel
    filters:
    - median:
        window_size: 9
        send_every: 5
        send_first_at: 4
    - heartbeat: 30s
    - delta: 0.1
    disabled_by_default: false
    force_update: false
    unit_of_measurement: Wh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
wifi:
  fast_connect: true
  reboot_timeout: 10min
  ap:
    ssid: tmdcabdaniel Fallback
    password: !secret 'API_PASSWORD'
    manual_ip:
      static_ip: 192.168.9.10
      gateway: 192.168.9.1
      subnet: 255.255.255.0
      dns1: 192.168.9.1
      dns2: 0.0.0.0
    ap_timeout: 1min
  manual_ip:
    static_ip: 10.0.1.14
    gateway: 10.0.1.1
    subnet: 255.255.255.0
    dns1: 10.0.1.1
    dns2: 0.0.0.0
  domain: .local
  power_save_mode: NONE
  output_power: 20.0
  networks:
  - ssid: !secret 'WIFI_SSID'
    password: !secret 'WIFI_PASSWORD'
    priority: 0.0
  use_address: 10.0.1.14
captive_portal: {}
api:
  reboot_timeout: 10min
  password: !secret 'API_PASSWORD'
  port: 6053
ota:
  password: !secret 'API_PASSWORD'
  safe_mode: true
  port: 8266
  reboot_timeout: 5min
  num_attempts: 10
time:
- platform: sntp
  id: sntp_time
  timezone: <-03>3
  servers:
  - 10.0.1.17
  update_interval: 15min
text_sensor:
- platform: version
  name: Versão ESPHome da tomada da cabeceira do Daniel
  disabled_by_default: false
  icon: mdi:new-box
  hide_timestamp: false
  entity_category: diagnostic
- platform: wifi_info
  ip_address:
    name: Endereço IP da tomada da cabeceira do Daniel
    icon: mdi:ip-network
    disabled_by_default: false
    entity_category: diagnostic
  bssid:
    name: BSSID da tomada da cabeceira do Daniel
    disabled_by_default: false
    entity_category: diagnostic
web_server:
  auth:
    username: admin
    password: !secret 'API_PASSWORD'
  port: 80
  css_url: https://esphome.io/_static/webserver-v1.min.css
  js_url: https://esphome.io/_static/webserver-v1.min.js
  include_internal: false
  ota: true
status_led:
  pin:
    number: 13
    inverted: true
    mode:
      output: true
      analog: false
      input: false
      open_drain: false
      pullup: false
      pulldown: false
```
