### ISSUE TITLE
MODBUS switch does not skip updates

### ISSUE THREAD

**Issue by worker72** [esphome/issues#2951]
### The problem

The switch that I defined under the modbus platform does not skip updates. It is taken along every period.
All other modbus sensors and modbus numbers that I have defined in the YAML do follow the skip updates 

There is one sensor that I want to update every 10 seconds. All other devices are configured to skip_updates: 6

![image](https://user-images.githubusercontent.com/1201336/149675421-749aa312-0f8e-44c3-8fdc-a121833348d9.png)

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.3

### What platform are you using?

ESP8266

### Board

nodemcuv3

### Component causing the issue

modbus

### Example YAML snippet

```yaml
switch:
  - platform: modbus_controller
    modbus_controller_id: deye
    id: time_of_use
    name: "time of use"
    register_type: holding
    use_write_multiple: true
    address: 248
    bitmask: 1
    skip_updates: 6
```
