### ISSUE TITLE
Flash size is reported wrong after build

### ISSUE THREAD

**Issue by ktuulos** [esphome/issues#2953]
### The problem

I added a new Wemos D1 Mini device to ESPHome by first just clicking the plus sign and connecting to USB. After this, I added MQTT server information, changed debug level and edited board name to d1_mini to allow using full 4 MB of flash.

When I tried to install this updated scheme to device, it compiled well, but after compilation, it reported Flash amount wrong, to be 1 MB instead of 4 MB. I re-installed this to device again, no change. Below is the output from the build.

```
Processing kinkkumittari (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 2.6.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|-- <ESP8266WiFi> 1.0
|-- <AsyncMqttClient-esphome> 0.8.6
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266mDNS> 1.2
RAM:   [====      ]  37.9% (used 31024 bytes from 81920 bytes)
Flash: [====      ]  39.0% (used 407340 bytes from 1044464 bytes)
========================= [SUCCESS] Took 5.69 seconds =========================

```

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.12.10, supervisor-2021.12.2

### What platform are you using?

ESP8266

### Board

Wemos D1 mini v4.0

### Example YAML snippet

```yaml
esphome:
  name: kinkkumittari

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: INFO

mqtt:
  broker: 192.168.1.6
  topic_prefix: esphome/kinkkumittari
  discovery: false

# Enable Home Assistant API
api:

ota:
  password: "<edited out>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kinkkumittari Fallback Hotspot"
    password: "<edited out>"

captive_portal:
```
