### ISSUE TITLE
Write Modbus Controller Number writes in false registers

### ISSUE THREAD

**Issue by killee** [esphome/issues#2957]
### The problem

If I try to write registers the register address is false. It Seams that the address is with a factor 2.

I try to set the Register 0x18 (24) to 1. But the component write it to the register 0x30 (48). This happens for all other registers to.
For Switches it works correct.

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Turn on/off heat pump"
    address: 0x18
    value_type: S_WORD
    entity_category: config

log:
[10:12:06][D][modbus.number:055]: Updating register: connected Sensor=WP1 Turn on/off heat pump start address=0x0 register count=1 new value=0.00 (val=0.00)
[10:12:06][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x30 count 1
[10:12:06][V][modbus:184]: Modbus write: 01.06.00.30.00.00.89.C5 (8)
[10:12:06][V][modbus_controller:461]: Command sent 6 0x30 1
[10:12:06][V][modbus:058]: Modbus received Byte  1 (0X1)
[10:12:06][V][modbus:058]: Modbus received Byte  6 (0X6)
[10:12:06][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:12:06][V][modbus:058]: Modbus received Byte  48 (0X30)
[10:12:06][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:12:06][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:12:06][V][modbus:058]: Modbus received Byte  137 (0X89)

### Which version of ESPHome has the issue?

ESPHome 2022.1.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.10

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

Modbus Controller Number

### Example YAML snippet

```yaml
substitutions:
  devicename: heatpump-kille-com
  internalname: heatpump-kille-com
  pumpname: WP1

esphome:
  name: heatpump-kille-com
  platform: ESP32
  board: esp32dev


packages:
  sensor_gen: !include common/sensor_generic.yaml
  network: !include common/network_generic.yaml

# Enable Home Assistant API
api:

ota:
  password: "259a6727f07a1afd105efc57f0b60845"


logger:
  #level: INFO
  baud_rate: 0
  level: VERBOSE #makes uart stream available in esphome logstream
  #baud_rate: 0 #disable logging over uart
  #esp8266_store_log_strings_in_flash: false
  
uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1
  #invert: true

modbus:
  flow_control_pin: 5
  id: modbus1

modbus_controller:
  - id: heatpump
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    command_throttle: 10ms

switch:
  - platform: modbus_controller
    modbus_controller_id: heatpump
    id: switch_heat_pump
    name: "${pumpname} Turn on/off heat pump"
    register_type: holding
    address: 34
    bitmask: 1

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} High pressure switch"
    register_type: discrete_input
    address: 1
    entity_category: diagnostic 

sensor:
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Curent AC inlet temp"
    register_type: read
    address: 0
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Current DHW temp"
    register_type: read
    address: 1
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Error code"
    register_type: read
    address: 2
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Outsider pipe temp(AIN2)"
    register_type: read
    address: 3
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Compressor discharge temp(AIN1)"
    register_type: read
    address: 4
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Air temp(AIN3)"
    register_type: read
    address: 5
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} AC outlet water temp(IN3)"
    register_type: read
    address: 6
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} DHW pipe water temp(IN7)"
    register_type: read
    address: 7
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Solar pipe water temp(IN6)"
    register_type: read
    address: 8
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Outdoor Module temp"
    register_type: read
    address: 9
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Outdoor returned air temp"
    register_type: read
    address: 10
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Inner pipe temp(IN8)"
    register_type: read
    address: 11
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Expansion valve open degree"
    register_type: read
    address: 12
    unit_of_measurement: "°"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Water source inlet temp(AIN4)"
    register_type: read
    address: 13
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Water source outlet temp(AIN5)"
    register_type: read
    address: 14
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Solar water tank temp(IN4)"
    register_type: read
    address: 15
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: diagnostic 
    
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Compressor actual running frequency"
    register_type: read
    address: 16
    unit_of_measurement: "Hz"
    value_type: S_WORD
    entity_category: diagnostic 

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Actual water flow volume"
    register_type: read
    address: 17
    value_type: S_WORD
    entity_category: diagnostic 
    
number:
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Power off auto recovery"
    address: 0
    value_type: S_WORD
    entity_category: config


  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} DHW hysteresis Delta T"
    address: 1
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} AC hysteresis Delta T"
    address: 2
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Defrost entering temp"
    address: 3
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Water source antifreeze temp"
    address: 4
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Quit antifreeze temp"
    address: 5
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Defrost exit temp"
    address: 6
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Defrost time"
    address: 7
    unit_of_measurement: "min"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Defrost interval time"
    address: 8
    unit_of_measurement: "min"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} DHW electric heater start air temp"
    address: 9
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} AC electric heater start air temp"
    address: 10
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} DHW frequency limitation"
    address: 11
    #unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Air discharge protection temp"
    address: 12
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Defrost interval fact"
    address: 13
    #unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} G3 function"
    address: 14
    #unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Cooling target temp"
    address: 15
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Heating target temp"
    address: 16
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config
    
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} DHW target temp"
    address: 17
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Antibacterial target temp"
    address: 18
    unit_of_measurement: "°C"
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Fix frequency at testing"
    address: 19
    value_type: S_WORD
    unit_of_measurement: "Hz"
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Run set frequency"
    address: 20
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} EEV OPEN degree（Heating)"
    address: 21
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} EEV OPEN degree（coolinging)"
    address: 22
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} EEV control"
    address: 23
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Target overheat degree(heating)"
    address: 24
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} hTarget overheat degree(cooling)"
    address: 25
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} C4 and C6 control"
    address: 26
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} 2nd heat source selection"
    address: 27
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} 2nd heat source starting temp"
    address: 28
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Air temp to start Free cooling+ compressor cooling (SW1-2 must be set to ON to valid this parameter)"
    address: 29
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Solar antifreeze temp"
    address: 30
    value_type: S_WORD
    entity_category: config


  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Air temp differential on parameter 29 to start Full free cooling (SW1-2 must be set to ON to valid this parameter)"
    address: 31
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} (New) Pulse water flow switch lowest starting volume"
    address: 32
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Working mode"
    address: 33
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Turn on/off heat pump"
    address: 0x18
    value_type: S_WORD
    entity_category: config
```

### Anything in the logs that might be useful for us?

```txt
0:10:15][D][modbus.number:055]: Updating register: connecte[d Sensor=WP1 DHW hysteresis Delta T start address=0x0 register count=1 new value=3.00 (val=3.00)
[10:10:15][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x02 count 1
[10:10:15][V][modbus:184]: Modbus write: 01.06.00.02.00.03.68.0B (8)
[10:10:15][V][modbus_controller:461]: Command sent 6 0x2 1
[10:10:15][V][modbus:058]: Modbus received Byte  1 (0X1)
[10:10:15][V][modbus:058]: Modbus received Byte  6 (0X6)
[10:10:15][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:10:15][V][modbus:058]: Modbus received Byte  2 (0X2)
[10:10:15][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:10:15][V][modbus:058]: Modbus received Byte  3 (0X3)
[10:10:15][V][modbus:058]: Modbus received Byte  104 (0X68)

[10:09:47][D][modbus.number:055]: Updating register: connected Sensor=WP1 AC hysteresis Delta T start address=0x0 register count=1 new value=3.00 (val=3.00)
[10:09:47][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x04 count 1
[10:09:47][V][modbus:184]: Modbus write: 01.06.00.04.00.03.88.0A (8)
[10:09:47][V][modbus_controller:461]: Command sent 6 0x4 1
[10:09:47][V][modbus:058]: Modbus received Byte  1 (0X1)
[10:09:47][V][modbus:058]: Modbus received Byte  6 (0X6)
[10:09:47][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:09:47][V][modbus:058]: Modbus received Byte  4 (0X4)
[10:09:47][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:09:47][V][modbus:058]: Modbus received Byte  3 (0X3)
[10:09:47][V][modbus:058]: Modbus received Byte  136 (0X88)
[10:09:47][V][modbus:058]: Modbus received Byte  10 (0Xa)
[10:09:47][V][modbus_controller:055]: Modbus response queued
[10:09:47][V][component:200]: Components should block for at most 20-30ms.
[10:09:47][V][modbus_controller:063]: Process modbus response for address 0x4 size: 4
[10:09:47][V][modbus_controller:308]: Command ACK 0x4 1024 
[10:09:47][D][number:036]: 'WP1 AC hysteresis Delta T': Sending state 3.000000
[10:09:52][V][text_sensor:016]: 'heatpump-kille-com Uptime Human Readable': Received new state 42m 56s


[10:11:38][D][modbus.number:055]: Updating register: connected Sensor=WP1 Turn on/off heat pump start address=0x0 register count=1 new value=1.00 (val=1.00)
[10:11:38][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x30 count 1
[10:11:38][V][modbus:184]: Modbus write: 01.06.00.30.00.01.48.05 (8)
[10:11:38][V][modbus_controller:461]: Command sent 6 0x30 1
[10:11:38][V][modbus:058]: Modbus received Byte  1 (0X1)
[10:11:38][V][modbus:058]: Modbus received Byte  6 (0X6)
[10:11:38][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:11:38][V][modbus:058]: Modbus received Byte  48 (0X30)
[10:11:38][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:11:38][V][modbus:058]: Modbus received Byte  1 (0X1)
[10:11:38][V][modbus:058]: Modbus received Byte  72 (0X48)

[10:12:06][D][modbus.number:055]: Updating register: connected Sensor=WP1 Turn on/off heat pump start address=0x0 register count=1 new value=0.00 (val=0.00)
[10:12:06][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x30 count 1
[10:12:06][V][modbus:184]: Modbus write: 01.06.00.30.00.00.89.C5 (8)
[10:12:06][V][modbus_controller:461]: Command sent 6 0x30 1
[10:12:06][V][modbus:058]: Modbus received Byte  1 (0X1)
[10:12:06][V][modbus:058]: Modbus received Byte  6 (0X6)
[10:12:06][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:12:06][V][modbus:058]: Modbus received Byte  48 (0X30)
[10:12:06][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:12:06][V][modbus:058]: Modbus received Byte  0 (0X0)
[10:12:06][V][modbus:058]: Modbus received Byte  137 (0X89)
```

**Comment by martgras** [comment]
Can you please check the register addresses 
You are using 24 == 0x18 twice for different numbers 

```yaml
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Target overheat degree(heating)"
    address: 24
    value_type: S_WORD
    entity_category: config

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${pumpname} Turn on/off heat pump"
    address: 0x18
    value_type: S_WORD
    entity_category: config
```

I'm checking why the request is sent to address 30 but it would help to get the duplicate address out of the way first 
@stegm -  anything that rings a bell  - before I start taking a closer look at the "range - making" code

**Comment by stegm** [comment]
I have an assumption: During register range merging the start address of the sensors are changed to the one of the first sensor in range. I had to work around this in my select PR #3032. Maybe the switch implementation is not aware of this?

BTW  I  assume due to my last patch of the range algorithm, changing the start address should be no longer necessary at all. Perhaps I should take a look at this.

@killee Can you try it with only the switch sensor, nothing else? Can you also post the logs with "[C]" from the beginning?

**Comment by killee** [comment]
> I have an assumption: During register range merging the start address of the sensors are changed to the one of the first sensor in range. I had to work around this in my select PR #3032. Maybe the switch implementation is not aware of this?
> 
> BTW I assume due to my last patch of the range algorithm, changing the start address should be no longer necessary at all. Perhaps I should take a look at this.
> 
> @killee Can you try it with only the switch sensor, nothing else? Can you also post the logs with "[C]" from the beginning?

Only the switch in the firmware:
[13:44:57][I][app:102]: ESPHome version 2022.1.0 compiled on Jan 19 2022, 13:44:23
[13:44:57][C][wifi:488]: WiFi:
[13:44:57][C][wifi:350]:   Local MAC: 7C:9E:BD:46:51:04
[13:44:57][C][wifi:351]:   SSID: [redacted]
[13:44:57][C][wifi:352]:   IP Address: 192.168.83.76
[13:44:57][C][wifi:354]:   BSSID: [redacted]
[13:44:57][C][wifi:355]:   Hostname: 'heatpump-kille-com'
[13:44:57][C][wifi:357]:   Signal strength: -54 dB ▂▄▆█
[13:44:57][V][wifi:359]:   Priority: 0.0
[13:44:58][C][logger:233]: Logger:
[13:44:58][C][logger:234]:   Level: VERBOSE
[13:44:58][C][logger:235]:   Log Baud Rate: 0
[13:44:58][C][logger:236]:   Hardware UART: UART0
[13:44:58][C][uart.arduino_esp32:105]: UART Bus:
[13:44:58][C][uart.arduino_esp32:106]:   TX Pin: GPIO17
[13:44:58][C][uart.arduino_esp32:107]:   RX Pin: GPIO16
[13:44:58][C][uart.arduino_esp32:109]:   RX Buffer Size: 256
[13:44:58][C][uart.arduino_esp32:111]:   Baud Rate: 9600 baud
[13:44:58][C][uart.arduino_esp32:112]:   Data Bits: 8
[13:44:58][C][uart.arduino_esp32:113]:   Parity: NONE
[13:44:58][C][uart.arduino_esp32:114]:   Stop bits: 1
[13:44:58][C][modbus:129]: Modbus:
[13:44:58][C][modbus:130]:   Flow Control Pin: GPIO5
[13:44:58][C][modbus:131]:   Send Wait Time: 250 ms
[13:44:58][C][uptime.sensor:031]: Uptime Sensor 'heatpump-kille-com Uptime Sensor'
[13:44:58][C][uptime.sensor:031]:   State Class: 'total_increasing'
[13:44:58][C][uptime.sensor:031]:   Unit of Measurement: 's'
[13:44:58][C][uptime.sensor:031]:   Accuracy Decimals: 0
[13:44:58][C][uptime.sensor:031]:   Icon: 'mdi:timer-outline'
[13:44:58][V][uptime.sensor:031]:   Unique ID: '7c9ebd465104-uptime'
[13:44:58][C][template.text_sensor:021]: Template Sensor 'heatpump-kille-com Uptime Human Readable'
[13:44:58][C][template.text_sensor:021]:   Icon: 'mdi:clock-start'
[13:44:58][C][status:034]: Status Binary Sensor 'heatpump-kille-com online'
[13:44:58][C][status:034]:   Device Class: 'connectivity'
[13:44:58][C][modbus_controller.switch:014]: modbus_controller.switchModbus Controller Switch 'WP1 Turn on/off heat pump'
[13:44:58][C][captive_portal:144]: Captive Portal:
[13:44:58][C][web_server:162]: Web Server:
[13:44:58][C][web_server:163]:   Address: heatpump-kille-com.local:80
[13:44:58][C][ota:082]: Over-The-Air Updates:
[13:44:58][C][ota:083]:   Address: heatpump-kille-com.local:3232
[13:44:58][C][ota:086]:   Using Password.
[13:44:58][C][api:134]: API Server:
[13:44:58][C][api:135]:   Address: heatpump-kille-com.local:6053
[13:44:58][C][api:139]:   Using noise encryption: NO
[13:44:58][C][wifi_signal.sensor:009]: WiFi Signal 'heatpump-kille-com WiFi Signal Sensor'
[13:44:58][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[13:44:58][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[13:44:58][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[13:44:58][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[13:44:58][V][wifi_signal.sensor:009]:   Unique ID: '7c9ebd465104-wifisignal'
[13:44:58][C][mdns:084]: mDNS:
[13:44:58][C][mdns:085]:   Hostname: heatpump-kille-com
[13:44:58][V][mdns:086]:   Services:
[13:44:58][V][mdns:088]:   - _esphomelib, _tcp, 6053
[13:44:58][V][mdns:090]:     TXT: version = 2022.1.0
[13:44:58][V][mdns:090]:     TXT: mac = 7c9ebd465104
[13:44:58][V][mdns:090]:     TXT: platform = ESP32
[13:44:58][V][mdns:090]:     TXT: board = esp32dev
[13:44:58][C][modbus_controller:275]: ModbusController:
[13:44:58][C][modbus_controller:276]:   Address: 0x01
[13:44:58][C][modbus_controller:278]: sensormap
[13:44:58][C][modbus_controller:282]:  Sensor type=3 start=0x22 offset=0x0 count=1 size=2
[13:44:58][C][modbus_controller:284]: ranges
[13:44:58][C][modbus_controller:287]:   Range type=3 start=0x22 count=1 skip_updates=0
[13:45:01][D][api:098]: Accepted 192.168.83.74
[13:45:01][V][api.connection:763]: Hello from client: 'Home Assistant 2021.12.10 (192.168.83.74)'
[13:45:01][D][api.connection:779]: Home Assistant 2021.12.10 (192.168.83.74): Connected successfully
[13:45:08][D][switch:013]: 'WP1 Turn on/off heat pump' Turning ON.
[13:45:08][V][modbus_controller.switch:072]: write_state 'WP1 Turn on/off heat pump': new value = ON type = 3 address = 22 offset = 0
[13:45:08][D][switch:037]: 'WP1 Turn on/off heat pump': Sending state ON
[13:45:08][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x22 count 1
[13:45:08][V][modbus:184]: Modbus write: 01.06.00.22.00.01.E8.00 (8)
[13:45:08][V][modbus_controller:461]: Command sent 6 0x22 1
[13:45:09][V][modbus:058]: Modbus received Byte  1 (0X1)
[13:45:09][V][modbus:058]: Modbus received Byte  6 (0X6)
[13:45:09][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:45:09][V][modbus:058]: Modbus received Byte  34 (0X22)
[13:45:09][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:45:09][V][modbus:058]: Modbus received Byte  1 (0X1)
[13:45:09][V][modbus:058]: Modbus received Byte  232 (0Xe8)
[13:45:09][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:45:09][V][modbus_controller:055]: Modbus response queued
[13:45:12][D][switch:017]: 'WP1 Turn on/off heat pump' Turning OFF.
[13:45:12][V][modbus_controller.switch:072]: write_state 'WP1 Turn on/off heat pump': new value = OFF type = 3 address = 22 offset = 0
[13:45:12][D][switch:037]: 'WP1 Turn on/off heat pump': Sending state OFF
[13:45:12][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x22 count 1
[13:45:12][V][modbus:184]: Modbus write: 01.06.00.22.00.00.29.C0 (8)
[13:45:12][V][modbus_controller:461]: Command sent 6 0x22 1
[13:45:12][V][modbus:058]: Modbus received Byte  1 (0X1)
[13:45:12][V][modbus:058]: Modbus received Byte  6 (0X6)
[13:45:12][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:45:12][V][modbus:058]: Modbus received Byte  34 (0X22)
[13:45:12][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:45:12][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:45:12][V][modbus:058]: Modbus received Byte  41 (0X29)
[13:45:12][V][modbus:058]: Modbus received Byte  192 (0Xc0)
[13:45:12][V][modbus_controller:055]: Modbus response queued

**Comment by martgras** [comment]
Why switch ? 
Isn't number causing the problem while switch is ok?

**Comment by killee** [comment]
> Can you please check the register addresses You are using 24 == 0x18 twice for different numbers
> 
> ```yaml
>   - platform: modbus_controller
>     modbus_controller_id: heatpump
>     name: "${pumpname} Target overheat degree(heating)"
>     address: 24
>     value_type: S_WORD
>     entity_category: config
> 
>   - platform: modbus_controller
>     modbus_controller_id: heatpump
>     name: "${pumpname} Turn on/off heat pump"
>     address: 0x18
>     value_type: S_WORD
>     entity_category: config
> ```
> 
> I'm checking why the request is sent to address 30 but it would help to get the duplicate address out of the way first @stegm - anything that rings a bell - before I start taking a closer look at the "range - making" code

That was a testing mistake...
but also without dupple register I get the same result:
Some writing of different numbers:
[13:52:09][D][number:010]: 'WP1 Heating target temp' - Setting
[13:52:09][D][number:029]:   Value: 44.000000
[13:52:09][D][modbus.number:055]: Updating register: connected Sensor=WP1 Heating target temp start address=0x0 register count=1 new value=44.00 (val=44.00)
[13:52:09][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x20 count 1
[13:52:09][V][modbus:184]: Modbus write: 01.06.00.20.00.2C.89.DD (8)
[13:52:09][V][modbus_controller:461]: Command sent 6 0x20 1
[13:52:09][V][modbus:058]: Modbus received Byte  1 (0X1)
[13:52:09][V][modbus:058]: Modbus received Byte  6 (0X6)
[13:52:09][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:52:09][V][modbus:058]: Modbus received Byte  32 (0X20)
[13:52:09][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:52:09][V][modbus:058]: Modbus received Byte  44 (0X2c)
[13:52:09][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x26 count 1
[13:52:09][V][modbus:184]: Modbus write: 01.06.00.26.00.31.A9.D5 (8)
[13:52:09][V][modbus_controller:461]: Command sent 6 0x26 1
[13:52:09][V][modbus:058]: Modbus received Byte  1 (0X1)
[13:52:09][V][modbus:058]: Modbus received Byte  6 (0X6)
[13:52:09][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:52:09][V][modbus:058]: Modbus received Byte  38 (0X26)
[13:52:09][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:52:09][V][modbus:058]: Modbus received Byte  49 (0X31)
[13:52:09][V][modbus:058]: Modbus received Byte  169 (0Xa9)
[13:52:09][V][modbus:058]: Modbus received Byte  213 (0Xd5)
[13:52:09][V][modbus_controller:055]: Modbus response queued
[13:52:09][V][modbus_controller:063]: Process modbus response for address 0x26 size: 4
[13:52:09][V][modbus_controller:308]: Command ACK 0x26 9728 
[13:52:09][D][number:036]: 'WP1 Fix frequency at testing': Sending state 49.000000
[13:52:11][D][number:010]: 'WP1 EEV OPEN degree（coolinging)' - Setting
[13:52:11][D][number:029]:   Value: 349.000000
[13:52:11][D][modbus.number:055]: Updating register: connected Sensor=WP1 EEV OPEN degree（coolinging) start address=0x0 register count=1 new value=349.00 (val=349.00)
[13:52:11][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x2C count 1
[13:52:11][V][modbus:184]: Modbus write: 01.06.00.2C.01.5D.88.6A (8)
[13:52:11][V][modbus_controller:461]: Command sent 6 0x2C 1
[13:52:11][V][modbus:058]: Modbus received Byte  1 (0X1)
[13:52:11][V][modbus:058]: Modbus received Byte  6 (0X6)
[13:52:11][V][modbus:058]: Modbus received Byte  0 (0X0)
[13:52:11][V][modbus:058]: Modbus received Byte  44 (0X2c)
[13:52:11][V][modbus:058]: Modbus received Byte  1 (0X1)
[13:52:11][V][modbus:058]: Modbus received Byte  93 (0X5d)
[13:52:11][V][modbus:058]: Modbus received Byte  136 (0X88)
[13:52:11][V][modbus:058]: Modbus received Byte  106 (0X6a)
[13:52:11][V][modbus_controller:055]: Modbus response queued
[13:52:20][V][text_sensor:016]: 'heatpump-kille-com Uptime Human Readable': Received new state 5m 32s
[13:52:20][D][text_sensor:067]: 'heatpump-kille-com Uptime Human Readable': Sending state '5m 32s'
[13:52:20][V][sensor:074]: 'heatpump-kille-com Uptime Sensor': Received new state 331.863007
[13:52:20][D][sensor:125]: 'heatpump-kille-com Uptime Sensor': Sending state 331.86301 s with 0 decimals of accuracy

**Comment by killee** [comment]
> Why switch ? Isn't number causing the problem while switch is ok?

Exactly only numbers has incorect registers for the writing process.

**Comment by martgras** [comment]
I think I found it can you please try
```
external_components:
  - source:
      type: git
      url: https://github.com/martgras/esphome
      ref: modbus_number_write
    components: [modbus_controller]
```

**Comment by stegm** [comment]
@martgras Not sure if your patch solves everything. Assume someone change the offset in yaml to an odd address.

```yaml
  - platform: modbus_controller
    modbus_controller_id: heatpump
    id: switch_heat_pump
    name: "${pumpname} Turn on/off heat pump"
    register_type: holding
    address: 34
    offset: 1
    bitmask: 1
```
