### ISSUE TITLE
`partition` light creates a ghost entity in HA

### ISSUE THREAD

**Issue by nagyrobi** [esphome/issues#2959]
### The problem

I added a `partition` type light to my config, based on `single_light_id` segments like below.

The problem is that in HA, along with the expected `light.vbar_ossz` entity, another one ghostly appeared: `light.esphome_szines_dmxlight` which is not configured anywhere, to be created.

It disappears if I remove the partition light from config, it appears back when I re-add it.

The friendly name of this strange entity is empty string. Looks like the `entity_id` is composed of `light.esphome_` + name of node + `light`.

![kép](https://user-images.githubusercontent.com/1550668/150112755-4f2b13b1-32ed-4370-baa6-92fc45febca1.png)

It looks like it acts only on the first light, with id `dmx_bar_1`

The orginal entities of the lights and the partition light entitiy are all functioning normally, this extra one appears from nowhere, what's the reason?

### Which version of ESPHome has the issue?

v2022.1.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.10

### What platform are you using?

ESP8266

### Board

Wemos D1

### Component causing the issue

partition light

### Example YAML snippet

```yaml
light:
- platform: rgbw
  name: "VBar1"
  id: dmx_bar_1
  red: vbar1_red
  green: vbar1_green
  blue: vbar1_blue
  white: vbar1_amber
  icon: mdi:spotlight
  default_transition_length: 0s
  color_interlock: false
  restore_mode: RESTORE_DEFAULT_ON

- platform: rgbw
  name: "VBar2"
  id: dmx_bar_2
  red: vbar2_red
  green: vbar2_green
  blue: vbar2_blue
  white: vbar2_amber
  icon: mdi:spotlight
  default_transition_length: 0s
  color_interlock: false
  restore_mode: RESTORE_DEFAULT_ON

- platform: rgbw
  name: "VBar3"
  id: dmx_bar_3
  red: vbar3_red
  green: vbar3_green
  blue: vbar3_blue
  white: vbar3_amber
  icon: mdi:spotlight
  default_transition_length: 0s
  color_interlock: false
  restore_mode: RESTORE_DEFAULT_ON

- platform: rgbw
  name: "VBar4"
  id: dmx_bar_4
  red: vbar4_red
  green: vbar4_green
  blue: vbar4_blue
  white: vbar4_amber
  icon: mdi:spotlight
  default_transition_length: 0s
  color_interlock: false
  restore_mode: RESTORE_DEFAULT_ON

- platform: partition
  name: "VBar össz"
  default_transition_length: 0s
  restore_mode: RESTORE_DEFAULT_OFF
  segments:
    - single_light_id: dmx_bar_1
    - single_light_id: dmx_bar_2
    - single_light_id: dmx_bar_3
    - single_light_id: dmx_bar_4
  effects:
    - addressable_rainbow:
    - addressable_color_wipe:
```

### Anything in the logs that might be useful for us?

```txt
2022-01-19 12:01:14 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID szines-dmxlight already exists - ignoring light.esphome_szines_dmxlight
2022-01-19 12:01:14 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID szines-dmxlight already exists - ignoring light.esphome_szines_dmxlight
2022-01-19 12:01:14 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID szines-dmxlight already exists - ignoring light.esphome_szines_dmxlight

```

### Additional information

Attributes of the ghost entity:
```
supported_color_modes:
  - rgbw
friendly_name: ''
supported_features: 40
```
