### ISSUE TITLE
Warning during compilation

### ISSUE THREAD

**Issue by KixMan28** [esphome/issues#2962]
### The problem

During compilation I get warnings.

### Which version of ESPHome has the issue?

2022.1.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.12.10

### What platform are you using?

ESP32

### Board

mhetesp32minikit

### Component causing the issue

esp32-hal-spi.c

### Example YAML snippet

```yaml
substitutions:
  friendly_name: Temp Hub 2
  device_description: "Temperature hub for Livingroom, Kinga and Outdoor"

esphome:
  name: temp-hub-2
  platform: ESP32
  board: mhetesp32minikit
  comment: ${device_description}

wifi:
  ssid: !secret esphome_ssid2
  password: !secret esphome_pwd2
  manual_ip:
    static_ip: 192.168.1.171
    gateway: !secret esphome_gateway
    subnet: !secret esphome_subnet
    dns1: !secret esphome_dns1
    dns2: !secret esphome_dns2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${friendly_name} Hotspot'
    password: !secret fallback_password

text_sensor:
  - platform: wifi_info
    mac_address:
      name:  "${friendly_name} Mac Address"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  safe_mode: true
  num_attempts: 5
  password: !secret ota_password

web_server:
  port: 80

# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

sensor:
#  - platform: xiaomi_cgg1
  - platform: xiaomi_lywsd02
    mac_address: E7:2E:01:90:84:FA
    temperature:
      name: "Kinga Temperature"
    humidity:
      name: "Kinga Humidity"
    battery_level:
      name: "Kinga Battery Level"
  - platform: xiaomi_cgg1
    mac_address: E7:2E:00:C2:3C:47
    temperature:
      name: "Nappali Temperature"
    humidity:
      name: "Nappali Humidity"
    battery_level:
      name: "Nappali Battery Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:B5:B0:AA"
    bindkey: "8f5dfc5e8d778e2f029659ff59823aa3"
    temperature:
      name: "Outdoor Temperature"
    humidity:
      name: "Outdoor Humidity"
    battery_level:
      name: "Outdoor Battery Level"
```
```


### Anything in the logs that might be useful for us?

```txt
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c: In function 'spiTransferBytesNL':
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c:922:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_out8 = &result[c_longs-1];
                                       ^
/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c:923:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_data8 = &last_data;
                                        ^
```
```


### Additional information

_No response_
