### ISSUE TITLE
Binary_sensor used in BRUH motion sensor not working anymore on ESP32 board

### ISSUE THREAD

**Issue by wilfredsmit** [esphome/issues#2963]
### The problem

I've used the motion sensor used in BRUH's multisensor on an ESPRESSIF ESP32-WROOM-32 board. (I experimented with the data pins 19 en 35). Both configurations were working on a ESPHome firmware prior to version 2022.1.x 

After the firmware update. The motion sensor stopped working. I also have a TEMT6000 ambient light sensor on pin 34 which is still working as expected.

### Which version of ESPHome has the issue?

2022.1.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.10

### What platform are you using?

ESP32

### Board

ESPRESSIF ESP32-WROOM-32

### Component causing the issue

Passive Infrared Sensor

### Example YAML snippet

```yaml
esphome:
  name: sensor-node-05

esp32:
  board: esp32dev
  framework:
    type: arduino

# Binary sensors ####################################################
binary_sensor:
  # GPIO pin movement sensor
  - platform: gpio
    pin:
      number: 19
    name: sensor-node-05 Bewegingssensor
```

### Anything in the logs that might be useful for us?

```
[11:45:37][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Sensor node 05 Bewegingssensor'
[11:45:37][C][gpio.binary_sensor:015]:   Device Class: 'motion'
[11:45:37][C][gpio.binary_sensor:016]:   Pin: GPIO19
```
