### ISSUE TITLE
SONOFF Basic no longer connects to Unifi AP after update to 2022.1.1

### ISSUE THREAD

**Issue by user897943** [esphome/issues#2964]
### The problem

Prior to 2022.1.1 it was working absolutely fine, I had to tweak the framework to "latest", because "recommended" was doing the same thing where the SB was not connecting to my Unifi APs. After changing framework to "latest" it did.

However, whatever this new update to ESPHome did, it bricked the devices again.

My config (replaced private info with "xxxxxxx":

```
########################## SONOFF GENERAL CONFIG #############################
###########################  Aquarium BASIC  #################################

esphome:
  name: aquarium

esp8266:
  board: sonoff_basic
  framework:
    version: latest

wifi:
  ssid: Kumshott
  password: !secret xxxxxxxxxxxx
  power_save_mode: none
  reboot_timeout: 15s
  output_power: 20dB
  fast_connect: true
#  manual_ip:
#    static_ip: xxxxxxx
#    subnet: xxxxxxxx
#    gateway: xxxxxxxxx

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Aquarium Fallback Hotspot"
#    password: !secret xxxxxxxx

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret xxxxxxx

ota:
  safe_mode: true
  password: !secret passota

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Aquarium Lights Sonoff Button"
    on_press:
      then:
      - light.toggle: light1

output:
  - platform: gpio
    id: relay
    pin: GPIO12
    
light:
 - platform: binary
   name: "Aquarium Lights"
   id: light1
   output: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
sensor:
  - platform: wifi_signal
    name: "Aquarium Lights WiFi signal"
    update_interval: 60s

  - platform: uptime
    name: "Aquarium Lights device uptime"

text_sensor:
  - platform: version
    name: "Aquarium Lights ESPHome version"
```

### Which version of ESPHome has the issue?

2022.1.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

Sonoff Basic
