### ISSUE TITLE
ota.on_begin runs after the file is uploaded

### ISSUE THREAD

**Issue by maruel** [esphome/issues#2967]
### The problem

[ota.on_begin](https://esphome.io/components/ota.html?highlight=ota#ota-on-begin) event is called after the upload is completed while it's being applied. While it makes sense semantically, it's not what I expected from a user experience, I would consider the upload phase to be part of the OTA.

With the snippet below, notice that the LED changes colors after the upload, not before.

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

m5stak pico32

### Component causing the issue

ota

### Example YAML snippet

```yaml
# With a colored LED set as "led":
ota:
  (...)
  on_begin:
    then:
      - light.control:
          id: led
          state: on
          brightness: 100%
          red: 100%
          green: 0%
          blue: 100%
```

**Comment by martgras** [comment]
`on_begin` is called when uploading starts.

You are probably running into the issue described in the documentation:

An OTA update blocks the main loop during its operation. This means that you won’t be able to represent state changes using components that update their output only from within their loop() method. Explained differently: if you try to display the OTA progress using component X, but the update only appears after the OTA update finished, then component X cannot be used for providing OTA update feedback.

To verify try 

```yaml
on_begin:
    then:
      - logger.log: "OTA start"
      - light.control:
          id: led
          state: on
          brightness: 100%
          red: 100%
          green: 0%
          blue: 100%
```
