### ISSUE TITLE
fastled_clockless flickering when using addressable_lambda

### ISSUE THREAD

**Issue by Tyde** [esphome/issues#2970]
### The problem

I am using the `fastled_clockless` platform with a  `WS2812B` chipset on both esp32 and esp8266. With both devices I get the following issue:

Let's assume I use the following minimal example 
```YAML
esphome:
  name: ledstrip-particle
    
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""


ota:
  password: ""

wifi:
  ssid: <redacted>
  password: <redacted>

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ledstrip-Particle"
    password: "geAqcpjv3Ogv"

captive_portal:


light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO23
    num_leds: 149
    rgb_order: GRB
    name: "FastLED WS2811 Light"
    gamma_correct: 1.0
    effects: 
      - addressable_lambda: 
          name: "issue"
          update_interval: 10ms
          lambda: |-
            auto basecolor = esphome::Color(10, 7, 3);
            it.all()=basecolor;
      - addressable_lambda: 
          name: "issue high"
          update_interval: 10ms
          lambda: |-
            auto basecolor = esphome::Color(40, 28, 12);
            it.all()=basecolor;

```

When I use the light without the addressable_lambda effects the light is stable and doesnt flicker. As soon as I activate one of the effects, I see a noticable flickering in the lights. To investigate the issue I connected my Logic Analyzer and got the following data for the effect `issue`
![grafik](https://user-images.githubusercontent.com/1103207/150629088-aa6d9736-4bf3-4a47-bdbf-493a9aef8762.png)

It is clearly visible, that somehow the constant color value that I set at the output gets modified and about every second time there is an addition of 1 happening in the output values, which results in the flickering. If we just look at one pixel index we can also see that the values do change over time:
![grafik](https://user-images.githubusercontent.com/1103207/150629223-7e2cd935-5138-4ac2-8eab-5cc7606c7416.png)

This is mostly visible at low values, but looking at the data, this issue also happens when I set higher Color values. It just isn't as noticeable to the eye.

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.12.5

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

fastled

### Example YAML snippet

```yaml
esphome:
  name: ledstrip-particle
    
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""


ota:
  password: ""

wifi:
  ssid: <redacted>
  password: <redacted>

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ledstrip-Particle"
    password: "geAqcpjv3Ogv"

captive_portal:


light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO23
    num_leds: 149
    rgb_order: GRB
    name: "FastLED WS2811 Light"
    gamma_correct: 1.0
    effects: 
      - addressable_lambda: 
          name: "issue"
          update_interval: 10ms
          lambda: |-
            auto basecolor = esphome::Color(10, 7, 3);
            it.all()=basecolor;
      - addressable_lambda: 
          name: "issue high"
          update_interval: 10ms
          lambda: |-
            auto basecolor = esphome::Color(40, 28, 12);
            it.all()=basecolor;
```

**Comment by martgras** [comment]
Do you see the flickering with `update_interval: 1s` ?
10ms might be too fast

**Comment by Tyde** [comment]
Yes the issue persists with an `update_interval: 1s`
![grafik](https://user-images.githubusercontent.com/1103207/150632573-e99928b7-8f9e-4dbb-8591-e0d4b95c76d1.png)
The difference is now, that it of course only updates every second.

It is also visible in this video:
https://nextcloud.danielthiem.eu/s/pZ3s9x2eSBMkmrf

**Comment by martgras** [comment]
I know this is more trial & error but I had issues as well a few weeks ago. Can't remember the exact details but I ended up using neopixelbus instead of fastled and switched from SPI (default) to RMT mode
It's used to visualize air quality on a 8x4 Stick 
As you can see I also tested a couple of variants - or maybe I just don't notice the flickering  :)

```yaml
light:
  - platform: neopixelbus
    #platform: fastled_clockless
    type: GRB
    variant: WS2812
    method: ESP32_RMT_0
    #chipset: WS2812
    #rgb_order: GRB
    color_correct: [75%, 75%, 75%]
    restore_mode: ALWAYS_ON
    num_leds: 32
    name: "NeoPixel Light"
    id: neostick
    pin: 25

display:
  - platform: addressable_light
    id: led_matrix_display
    addressable_light_id: neostick
    width: 8
    height: 4
    update_interval: 5s
    lambda: |-
      static uint8_t last_iaq ;
       ....
```

These issues can be hard to track down as most of the functionality is in the underlying libraries (neopixel, fasted) and we have to isolate if it's due to the libraries or a esphome issue
