### ISSUE TITLE
esphome always give an error with RDM6300

### ISSUE THREAD

**Issue by holazit** [esphome/issues#2971]
### The problem

I can't compile anymore since I installed ESPHome 2022.1.0 with RDM6300 because I always get the error

`/config/badge_ext.yaml: In lambda function:
/config/badge_ext.yaml:125:32: error: 'uint32_to_string' was not declared in this scope
           payload: !lambda 'return uint32_to_string(x);'
                                ^
/config/badge_ext.yaml:126:3: warning: control reaches end of non-void function [-Wreturn-type]
*** [.pioenvs/badge_ext/src/main.cpp.o] Error 1`

I haven't changed my configuration, it matches the one in the esphome documentation.

### Which version of ESPHome has the issue?

2022.1.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

d1_mini_pro

### Component causing the issue

RDM6300

### Example YAML snippet

```yaml
esphome:
  name: badge_ext
  platform: ESP8266
  board: d1_mini_pro

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  manual_ip:
    static_ip: !secret wifi_static_ip_badge_ext
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
  ap:
    ssid: "badge_ext Hotspot"
    password: !secret password

captive_portal:

debug:

logger:

ota:
  password: !secret password

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt_username
  password: !secret mqtt_password

web_server:
  port: 80

uart:
  rx_pin: D4
  baud_rate: 9600

rdm6300:
  on_tag:
    then:
      - mqtt.publish:
          topic: badge/ext
          payload: !lambda 'return uint32_to_string(x);'
```
