### ISSUE TITLE
ac_dimmer trigger too slow

### ISSUE THREAD

**Issue by Th3M1k3y** [esphome/issues#2973]
### The problem

When using the ac_dimmer component I can't get it to trigger at the zero crossing.

I am not sure if it is a software or hardware problem, because it could very well also be the software triggering where it should, but the voltage needing come into the right rage for the zero point detect to notice it.

The problem I see is that it very consistently trigger 1.5ms too late, but if there were an option to delay the trigger I could just delay it by 8.5ms (50hz). That would solve the problem for me, as it would then just wait, and when it then trigger it would be at the next half wave.

![2022-01-23 18 44 13](https://user-images.githubusercontent.com/29869794/150692060-4635ea85-8983-4c06-aff1-5bf1ef712454.jpg)
.

### Which version of ESPHome has the issue?

2022.1.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

ac_trigger

### Example YAML snippet

```yaml
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: D2
    method: leading
    min_power: 0.5
    zero_means_zero: true
    zero_cross_pin:
      number: D8
      mode:
        input: true
      inverted: true
      
fan:
  platform: speed
  name: "${friendly_name} - Motor speed"
  id: fan_speed
  output: dimmer1
```
