### ISSUE TITLE
remote network device stays offline

### ISSUE THREAD

**Issue by redstorm1** [esphome/issues#2975]
### The problem

Home Assistant is on a 192.168.1.0/24 network and i have a second remote network 192.168.2.0/24, routing between networks is in place.
A ESP8266 on the 192.168.2.x network stay offline. 
Setting a static IP 192.168.2.200 on the ESP the device will stream logs and update OTA but stays offline in HA.
Pinging the ip of the device works from the home assistant server, pinging via name.local does. Adding an entry in the servers hosts file for the device enables ping via name.local but remains offline in HA.

### Which version of ESPHome has the issue?

2022.1.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

core-2021.12.10

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

esphome API

### Example YAML snippet

```yaml
esphome:
  name: terrace
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "0492ba9a250392029a52db84bd15c8dd"

wifi:
  ssid: "wifi"
  password: "pass"
  use_address: 192.168.2.200
  manual_ip:
    static_ip: 192.168.2.200
    gateway: 192.168.2.254
    subnet: 255.255.255.0
```

### Additional information

updating to status_use_ping, the device is shown online but not device or entity is available to configure in HA.

The networks are configured via a wireguard VPN with routing and firewalls updated and ping works from each network to each device and vice versa.

I suspect HA is not connecting out to192.168.2.200:6053 to the API on the ESP8266 even though it can ping it, and stream the logs and update over the air just does not connect to the API
