### ISSUE TITLE
Add Momentary Switch example and link to Button Documentation

### ISSUE THREAD

**Issue by borpin** [esphome/issues#2976]
### The problem

There is no example of a momentary switch on the Button documentation.  I'd suggest this is a very likely use of this so would be useful to include it.

Links between the Momentary switch docs and the Button docs would also benefit users.

### Which version of ESPHome has the issue?

Docs

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
A configuration that works for me and creates a Button Entity in HomeAssistant.


switch:
  - platform: gpio
    pin: GPIO4
    name: "Garage Door 2 Relay"
    id: relay
    restore_mode: ALWAYS_OFF
    internal: true

button:
  - platform: template
    name: "Garage Door 2"
    icon: "mdi:gate"
    on_press:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

**Comment by oxan** [comment]
A better implementation would be something like this, that avoids the unnecessary switch:
```yaml
output:
  - platform: gpio
    id: out
    pin: GPIO4

button:
  - platform: template
    on_press:
      - output.turn_on: out
      - delay: 500ms
      - output.turn_off: out
```

Momentary switches in general are a hack from when buttons didn't exist, so I'd rather remove them from the documentation than make them more prominent.

An `output` button would probably also be useful, so that you can do things like this:
```yaml
output:
  - platform: gpio
    id: out
    pin: GPIO4

button:
  - platform: output
    output: out
    duration: 500ms
```
