### ISSUE TITLE
ESP-07 with BME280 is not working

### ISSUE THREAD

**Issue by srg74** [esphome/issues#298]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io ESPHome add-on
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 ESP-07 module
**Affected component:**

https://esphome.io/components/sensor/bme280.html

**Description of problem:**
I have connected BME280 sensor and ESPhome is not communicating with sensor. Initially sensor where working but after 10 min stopped.
I uploaded i2c scan sketch and sensor is detected:
Scanning (SDA : SCL) - GPIO5 : GPIO4 - I2C device found at address 0x76 !
Then upload BME280 sketch to read data over serial port and everything is OK. But when I upload ESPhome it stop reading sensor again.
Please help to solve this issue.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: garage_door_opener
  platform: ESP8266
  board: esp07

wifi:
  ssid: "XXXXXX"
  password: "XXXXXX"

# Optional manual IP
  manual_ip:
    static_ip: 10.0.0.XX
    gateway: 10.0.0.XX
    subnet: 255.255.255.0
    dns1: 10.0.0.XX
    dns2: 192.168.1.XX

# Example configuration entry
#web_server:
#  port: 80
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'xxxx'

ota:
  password: 'xxxx'

# i2c bus
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: False

# BME280 sensor
sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 60s
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
Log:
[18:52:21][C][wifi:371]: WiFi:
[18:52:21][C][wifi:253]: SSID: 'XXXXX'[redacted]
[18:52:21][C][wifi:254]: IP Address: 10.0.0.XX
[18:52:21][C][wifi:256]: BSSID: XX:XX:XX:XX:XX:XX[redacted]
[18:52:21][C][wifi:257]: Hostname: 'garage_door_opener'
[18:52:21][C][wifi:261]: Signal strength: -55 dB ▂▄▆█
[18:52:21][C][wifi:262]: Channel: 9
[18:52:21][C][wifi:263]: Subnet: 255.255.255.0
[18:52:21][C][wifi:264]: Gateway: 10.0.0.X
[18:52:21][C][wifi:265]: DNS1: 10.0.0.X
[18:52:21][C][wifi:266]: DNS2: 192.168.1.X
[18:52:21][C][i2c:035]: I2C Bus:
[18:52:21][C][i2c:036]: SDA Pin: GPIO4
[18:52:21][C][i2c:037]: SCL Pin: GPIO5
[18:52:21][C][i2c:038]: Frequency: 50000 Hz
[18:52:21][I][i2c:040]: Scanning i2c bus for active devices...
[18:52:21][I][i2c:056]: Found no i2c devices!
[18:52:21][C][output.gpio:025]: GPIO Binary Output:
[18:52:21][C][output.gpio:026]: Pin: GPIO12 (Mode: OUTPUT)
[18:52:21][C][binary_sensor.gpio:022]: GPIO Binary Sensor 'Garage door opened'
[18:52:21][C][binary_sensor.gpio:023]: Pin: GPIO14 (Mode: INPUT)
[18:52:21][C][binary_sensor.gpio:022]: GPIO Binary Sensor 'Garage door closed'
[18:52:21][C][binary_sensor.gpio:023]: Pin: GPIO13 (Mode: INPUT)
[18:52:21][C][logger:142]: Logger:
[18:52:22][C][logger:143]: Level: DEBUG
[18:52:22][C][logger:144]: Log Baud Rate: 115200
[18:52:22][C][logger:145]: Hardware UART: UART0
[18:52:22][C][sensor.bme280:162]: BME280:
[18:52:22][C][sensor.bme280:163]: Address: 0x76
[18:52:22][E][sensor.bme280:166]: Communication with BME280 failed!
[18:52:22][C][sensor.bme280:175]: IIR Filter: OFF
[18:52:22][C][sensor.bme280:176]: Update Interval: 60000 ms
[18:52:22][C][sensor.bme280:178]: Temperature 'BME280 Temperature'
[18:52:22][C][sensor.bme280:178]: Unit of Measurement: '°C'
[18:52:22][C][sensor.bme280:178]: Accuracy Decimals: 1
[18:52:22][C][sensor.bme280:179]: Oversampling: 16x
[18:52:22][C][sensor.bme280:180]: Pressure 'BME280 Pressure'
[18:52:22][C][sensor.bme280:180]: Unit of Measurement: 'hPa'
[18:52:22][C][sensor.bme280:180]: Accuracy Decimals: 1
[18:52:22][C][sensor.bme280:180]: Icon: 'mdi:gauge'
[18:52:22][C][sensor.bme280:181]: Oversampling: 16x
[18:52:22][C][sensor.bme280:182]: Humidity 'BME280 Humidity'
[18:52:22][C][sensor.bme280:182]: Unit of Measurement: '%'
[18:52:22][C][sensor.bme280:182]: Accuracy Decimals: 1
[18:52:22][C][sensor.bme280:182]: Icon: 'mdi:water-percent'
[18:52:22][C][sensor.bme280:183]: Oversampling: 16x
[18:52:22][C][api:101]: API Server:
[18:52:22][C][api:102]: Address: 10.0.0.XX:6053
[18:52:22][C][ota:127]: Over-The-Air Updates:
[18:52:22][C][ota:128]: Address: 10.0.0.XX:8266
[18:52:22][C][ota:130]: Using Password.
