### ISSUE TITLE
Internal buffer full message

### ISSUE THREAD

**Issue by seblang** [esphome/issues#2981]
### The problem

I a trying to use teleinfo ESP.
All is going weel but when I start my module i have a message in logs "[teleinfo:060]: Internal buffer full" and no information are sended to HA

### Which version of ESPHome has the issue?

ESPHome version 2022.1.2 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2021.12.10

### What platform are you using?

ESP8266

### Board

esp_01s

### Example YAML snippet

```yaml
esphome:
  name: teleinfokit
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "XXXXXXXX"
  password: "XXXXXXXX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TeleInfoKit"
    password: !secret ap_key

captive_portal:

# Enable logging
logger:     
  baud_rate: 0   # disable logging via UART, help to avoid numerous crash with ESP_LOGD
  level: INFO   # INFO for less log, put DEBUG to view all the linky's "étiquettes" received  in the logs
  esp8266_store_log_strings_in_flash: False     #  :doc:`recommanded for ESP8266 </components/sensor/custom>`

# Enable Home Assistant API
api:
  password: XXXXXXXXXX

ota:
  password: !secret ota_pass
  id: my_ota


uart:
  id: uart_bus
  rx_pin: GPIO3
  baud_rate: 9600
  parity: EVEN
  data_bits: 7

teleinfo:
  id: myteleinfo
  update_interval: 30s
  historical_mode: false

sensor:
  - platform: teleinfo
    tag_name: "HCHC"
    id: hchc
    name: "Index Heures Creuses"
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    icon: mdi:flash
    device_class: energy
    state_class: total_increasing
    teleinfo_id: myteleinfo
    filters:
      - multiply: 0.001
  - platform: teleinfo
    tag_name: "HCHP"
    id: hchp
    name: "Index Heures Pleines"
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    icon: mdi:flash
    device_class: energy
    state_class: total_increasing
    teleinfo_id: myteleinfo
    filters:
      - multiply: 0.001
  - platform: teleinfo
    tag_name: "PAPP"
    id: papp
    name: "Puissance Actuelle"
    unit_of_measurement: "VA"
    state_class: "measurement"
    icon: mdi:flash
    teleinfo_id: myteleinfo
  - platform: teleinfo
    tag_name: "IINST"
    id: iinst
    name: "Intensité Actuelle"
    unit_of_measurement: "A"
    device_class: current
    state_class: "measurement"
    icon: mdi:flash
    teleinfo_id: myteleinfo
  - platform: teleinfo
    tag_name: "EAIT"
    id: EAIT
    name: "Energie active injectée totale"
    unit_of_measurement: "Wh"
    state_class: "measurement"
    icon: mdi:flash
    teleinfo_id: myteleinfo
  - platform: teleinfo
    tag_name: "EAST"
    id: EAST
    name: "Energie active soutirée totale"
    unit_of_measurement: "Wh"
    state_class: "measurement"
    icon: mdi:flash
    teleinfo_id: myteleinfo
  - platform: teleinfo
    tag_name: "SINSTS"
    id: SINSTS
    name: "Puissance app. Instantanée soutirée"
    unit_of_measurement: "W"
    device_class: current
    state_class: "measurement"
    icon: mdi:flash
    teleinfo_id: myteleinfo  
  - platform: teleinfo
    tag_name: "SINSTI"
    id: SINSTI
    name: "Puissance app. Instantanée Injecté"
    unit_of_measurement: "W"
    device_class: current
    state_class: "measurement"
    icon: mdi:flash
    teleinfo_id: myteleinfo
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/teleinfo.yaml...
INFO Starting log output from teleinfokit.local using esphome API
INFO Successfully connected to teleinfokit.local
[20:23:08][I][app:102]: ESPHome version 2022.1.2 compiled on Jan 25 2022, 20:12:19
[20:23:32][W][teleinfo:060]: Internal buffer full
```

**Comment by 0hax** [comment]
Hi,
Thanks for reporting the issue. Does it happen with earlier versions?
Like `2021.10.3` for example.

**Comment by gbrd** [comment]
I have this problem with esp32 not with esp8266 (standard mode)

**Comment by 0hax** [comment]
Can you try to bump `MAX_BUF_SIZE` to 4096 in `esphome/components/teleinfo/teleinfo.h` ?
Also please make sure there is no garbage on the lines due to incorrect wiring. (It happens often)

**Comment by gbrd** [comment]
I found 2 ideas that I didn't had time to test here : https://forum.hacf.fr/t/teleinfo-via-wifi/1077/286

- Increase uart buffer size with rx_buffer_size: 2048
- keep only one tag (just to test)
- try software serial (just to test)

**Comment by gbrd** [comment]
+ link to this maybe related closed not merged  pr

https://github.com/esphome/esphome/pull/3855

**Comment by 0hax** [comment]
Can you share your yaml config ?

**Comment by gbrd** [comment]
Here is my yaml config :
It work perfectly with my wemos d1 mini, not with a wemos esp32
```
esphome:
  name: 22-teleinfo
  friendly_name: Teleinfo

esp8266:
  board: d1_mini


# esp32:
#   board: esp32dev
#   framework:
#     type: arduino

# Enable logging
logger:
  #hardware_uart: UART1
  baud_rate: 0
  level: DEBUG
  #esp8266_store_log_strings_in_flash: False

# Enable Home Assistant API
api:
  encryption:
    key: "xxxx"

ota:
  password: "yyy"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.172
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.254

uart:
  id: uart_0
  #tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600 
  parity: EVEN
  data_bits: 7
  stop_bits: 1
  #debug: 
  #  direction: RX
  #  dummy_receiver: false
  #  after:
  #    delimiter: "\n"
  #  sequence:
  #    - lambda: UARTDebug::log_string(direction, bytes);
  

teleinfo:
  id: myteleinfo
  uart_id: uart_0
  update_interval: 10s
  historical_mode: false 
  
sensor:
  - platform: teleinfo #Heures Creuses Jours Bleus
    id: teleinfo_hc_blue
    tag_name: "EASF01"
    name: "HC bleu"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo
    on_value:
      - component.update: teleinfo_hc_blue_kwh
  - platform: template
    id: teleinfo_hc_blue_kwh
    state_class: total_increasing
    device_class: energy
    name: "HC bleu kWh"
    unit_of_measurement: "kWh"
    icon: mdi:flash
    lambda: |-
      return (id(teleinfo_hc_blue).state / 1000); 
    
  - platform: teleinfo # Heures Pleines Jours Bleus
    id: teleinfo_hp_blue
    tag_name: "EASF02"
    name: "HP bleu"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
    on_value:
      - component.update: teleinfo_hp_blue_kwh
  - platform: template
    id: teleinfo_hp_blue_kwh
    state_class: total_increasing
    device_class: energy
    name: "HP bleu kWh"
    unit_of_measurement: "kWh"
    icon: mdi:flash
    lambda: |-
      return (id(teleinfo_hp_blue).state / 1000); 
    
  - platform: teleinfo # Heures Creuses Jours Blancs
    id: teleinfo_hc_white
    tag_name: "EASF03"
    name: "HC blanc"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo   
    on_value:
      - component.update: teleinfo_hc_white_kwh
  - platform: template
    id: teleinfo_hc_white_kwh
    state_class: total_increasing
    device_class: energy
    name: "HC blanc kWh"
    unit_of_measurement: "kWh"
    icon: mdi:flash
    lambda: |-
      return (id(teleinfo_hc_white).state / 1000); 
     
  - platform: teleinfo # Heures Pleines Jours Blancs
    id: teleinfo_hp_white
    tag_name: "EASF04"
    name: "HP blanc"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo   
    on_value:
      - component.update: teleinfo_hp_white_kwh
  - platform: template
    id: teleinfo_hp_white_kwh
    state_class: total_increasing
    device_class: energy
    name: "HP blanc kWh"
    unit_of_measurement: "kWh"
    icon: mdi:flash
    lambda: |-
      return (id(teleinfo_hp_white).state / 1000); 
     
  - platform: teleinfo # Heures Creuses Jours Rouges
    id: teleinfo_hc_red
    tag_name: "EASF05"
    name: "HC rouge"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
    on_value:
      - component.update: teleinfo_hc_red_kwh
  - platform: template
    id: teleinfo_hc_red_kwh
    state_class: total_increasing
    device_class: energy
    name: "HC rouge kWh"
    unit_of_measurement: "kWh"
    icon: mdi:flash
    lambda: |-
      return (id(teleinfo_hc_red).state / 1000); 
    
  - platform: teleinfo # Heures Pleines Jours Rouges
    id: teleinfo_hp_red
    tag_name: "EASF06"
    name: "HP rouge"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
    on_value:
      - component.update: teleinfo_hp_red_kwh
  - platform: template
    id: teleinfo_hp_red_kwh
    state_class: total_increasing
    device_class: energy
    name: "HP rouge kWh"
    unit_of_measurement: "kWh"
    icon: mdi:flash
    lambda: |-
      return (id(teleinfo_hp_red).state / 1000); 
    
  # Puissance app. Instantanée soutirée 
  - platform: teleinfo
    id: teleinfo_power
    tag_name: "SINSTS"
    name: "power"
    unit_of_measurement: "VA"
    icon: mdi:flash
    teleinfo_id: myteleinfo

  - platform: teleinfo
    id: teleinfo_pcoup
    tag_name: "PCOUP"
    name: "Puissance app de coupure"
    unit_of_measurement: "VA"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
    filters:
      - multiply: 1000

  - platform: teleinfo
    id: teleinfo_pref
    tag_name: "PREF"
    name: "Puissance app de référence"
    unit_of_measurement: "kVA"
    icon: mdi:flash
    teleinfo_id: myteleinfo
        
  # Energie active soutirée totale
  - platform: teleinfo
    id: teleinfo_EAST
    tag_name: "EAST"
    name: "Energie active soutirée totale"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo
    
  - platform: teleinfo
    id: teleinfo_EASD01
    tag_name: "EASD01"
    name: "Energie active soutirée Distributeur, index 01"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
  - platform: teleinfo
    id: teleinfo_EASD02
    tag_name: "EASD02"
    name: "Energie active soutirée Distributeur, index 02"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
  - platform: teleinfo
    id: teleinfo_EASD03
    tag_name: "EASD03"
    name: "Energie active soutirée Distributeur, index 03"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
  - platform: teleinfo
    id: teleinfo_EASD04
    tag_name: "EASD04"
    name: "Energie active soutirée Distributeur, index 04"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
    
  - platform: teleinfo
    id: teleinfo_IRMS1
    tag_name: "IRMS1"
    name: "Courant efficace"
    unit_of_measurement: "A"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
    
  - platform: teleinfo
    id: teleinfo_URMS1
    tag_name: "URMS1"
    name: "Tension efficace"
    unit_of_measurement: "V"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
    
  - platform: teleinfo
    id: teleinfo_UMOY1
    tag_name: "UMOY1"
    name: "Tension moy"
    unit_of_measurement: "V"
    icon: mdi:flash
    teleinfo_id: myteleinfo    
    
  - platform: teleinfo
    id: teleinfo_SMAXSN
    tag_name: "SMAXSN"
    name: "Puissance app. max. soutirée n"
    unit_of_measurement: "VA"
    icon: mdi:flash
    teleinfo_id: myteleinfo   

#Puissance app max. soutirée n-1 SMAXSN-1 
  - platform: teleinfo
    id: teleinfo_SMAXSNm1
    tag_name: "SMAXSN-1"
    name: "Puissance app. max. soutirée n-1"
    unit_of_measurement: "VA"
    icon: mdi:flash
    teleinfo_id: myteleinfo   
    

text_sensor:
  - platform: teleinfo
    id: teleinfo_NTARF
    tag_name: "NTARF"
    name: "Numéro de l’index tarifaire en cours"
    teleinfo_id: myteleinfo
    
  - platform: teleinfo
    id: teleinfo_NJOURF
    tag_name: "NJOURF"
    name: "Numéro du jour en cours"
    teleinfo_id: myteleinfo
    
  - platform: teleinfo
    id: teleinfo_NJOURFp1
    tag_name: "NJOURF+1"
    name: "Numéro du prochain jour"
    teleinfo_id: myteleinfo
    
  - platform: teleinfo
    id: teleinfo_NGTF
    tag_name: "NGTF"
    name: "calendrier tarifaire"
    teleinfo_id: myteleinfo

  - platform: teleinfo
    id: teleinfo_LTARF
    tag_name: "LTARF"
    name: "tarif en cours"
    teleinfo_id: myteleinfo

```

**Comment by 0hax** [comment]
> Here is my yaml config : It work perfectly with my wemos d1 mini, not with a wemos esp32
> 
> ```
> esphome:
>   name: 22-teleinfo
>   friendly_name: Teleinfo
> 
> esp8266:
>   board: d1_mini
> 
> 
> # esp32:
> #   board: esp32dev
> #   framework:
> #     type: arduino
> 
> # Enable logging
> logger:
>   #hardware_uart: UART1
>   baud_rate: 0
>   level: DEBUG
>   #esp8266_store_log_strings_in_flash: False
> 
> # Enable Home Assistant API
> api:
>   encryption:
>     key: "xxxx"
> 
> ota:
>   password: "yyy"
> 
> wifi:
>   ssid: !secret wifi_ssid
>   password: !secret wifi_password
> 
>   manual_ip:
>     static_ip: 192.168.1.172
>     gateway: 192.168.1.1
>     subnet: 255.255.255.0
>     dns1: 192.168.1.254
> 
> uart:
>   id: uart_0
>   #tx_pin: GPIO1
>   rx_pin: GPIO3
>   baud_rate: 9600 
>   parity: EVEN
>   data_bits: 7
>   stop_bits: 1
>   #debug: 
>   #  direction: RX
>   #  dummy_receiver: false
>   #  after:
>   #    delimiter: "\n"
>   #  sequence:
>   #    - lambda: UARTDebug::log_string(direction, bytes);
>   
> 
> teleinfo:
>   id: myteleinfo
>   uart_id: uart_0
>   update_interval: 10s
>   historical_mode: false 
>   
> sensor:
>   - platform: teleinfo #Heures Creuses Jours Bleus
>     id: teleinfo_hc_blue
>     tag_name: "EASF01"
>     name: "HC bleu"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo
>     on_value:
>       - component.update: teleinfo_hc_blue_kwh
>   - platform: template
>     id: teleinfo_hc_blue_kwh
>     state_class: total_increasing
>     device_class: energy
>     name: "HC bleu kWh"
>     unit_of_measurement: "kWh"
>     icon: mdi:flash
>     lambda: |-
>       return (id(teleinfo_hc_blue).state / 1000); 
>     
>   - platform: teleinfo # Heures Pleines Jours Bleus
>     id: teleinfo_hp_blue
>     tag_name: "EASF02"
>     name: "HP bleu"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>     on_value:
>       - component.update: teleinfo_hp_blue_kwh
>   - platform: template
>     id: teleinfo_hp_blue_kwh
>     state_class: total_increasing
>     device_class: energy
>     name: "HP bleu kWh"
>     unit_of_measurement: "kWh"
>     icon: mdi:flash
>     lambda: |-
>       return (id(teleinfo_hp_blue).state / 1000); 
>     
>   - platform: teleinfo # Heures Creuses Jours Blancs
>     id: teleinfo_hc_white
>     tag_name: "EASF03"
>     name: "HC blanc"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo   
>     on_value:
>       - component.update: teleinfo_hc_white_kwh
>   - platform: template
>     id: teleinfo_hc_white_kwh
>     state_class: total_increasing
>     device_class: energy
>     name: "HC blanc kWh"
>     unit_of_measurement: "kWh"
>     icon: mdi:flash
>     lambda: |-
>       return (id(teleinfo_hc_white).state / 1000); 
>      
>   - platform: teleinfo # Heures Pleines Jours Blancs
>     id: teleinfo_hp_white
>     tag_name: "EASF04"
>     name: "HP blanc"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo   
>     on_value:
>       - component.update: teleinfo_hp_white_kwh
>   - platform: template
>     id: teleinfo_hp_white_kwh
>     state_class: total_increasing
>     device_class: energy
>     name: "HP blanc kWh"
>     unit_of_measurement: "kWh"
>     icon: mdi:flash
>     lambda: |-
>       return (id(teleinfo_hp_white).state / 1000); 
>      
>   - platform: teleinfo # Heures Creuses Jours Rouges
>     id: teleinfo_hc_red
>     tag_name: "EASF05"
>     name: "HC rouge"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>     on_value:
>       - component.update: teleinfo_hc_red_kwh
>   - platform: template
>     id: teleinfo_hc_red_kwh
>     state_class: total_increasing
>     device_class: energy
>     name: "HC rouge kWh"
>     unit_of_measurement: "kWh"
>     icon: mdi:flash
>     lambda: |-
>       return (id(teleinfo_hc_red).state / 1000); 
>     
>   - platform: teleinfo # Heures Pleines Jours Rouges
>     id: teleinfo_hp_red
>     tag_name: "EASF06"
>     name: "HP rouge"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>     on_value:
>       - component.update: teleinfo_hp_red_kwh
>   - platform: template
>     id: teleinfo_hp_red_kwh
>     state_class: total_increasing
>     device_class: energy
>     name: "HP rouge kWh"
>     unit_of_measurement: "kWh"
>     icon: mdi:flash
>     lambda: |-
>       return (id(teleinfo_hp_red).state / 1000); 
>     
>   # Puissance app. Instantanée soutirée 
>   - platform: teleinfo
>     id: teleinfo_power
>     tag_name: "SINSTS"
>     name: "power"
>     unit_of_measurement: "VA"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo
> 
>   - platform: teleinfo
>     id: teleinfo_pcoup
>     tag_name: "PCOUP"
>     name: "Puissance app de coupure"
>     unit_of_measurement: "VA"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>     filters:
>       - multiply: 1000
> 
>   - platform: teleinfo
>     id: teleinfo_pref
>     tag_name: "PREF"
>     name: "Puissance app de référence"
>     unit_of_measurement: "kVA"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo
>         
>   # Energie active soutirée totale
>   - platform: teleinfo
>     id: teleinfo_EAST
>     tag_name: "EAST"
>     name: "Energie active soutirée totale"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo
>     
>   - platform: teleinfo
>     id: teleinfo_EASD01
>     tag_name: "EASD01"
>     name: "Energie active soutirée Distributeur, index 01"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>   - platform: teleinfo
>     id: teleinfo_EASD02
>     tag_name: "EASD02"
>     name: "Energie active soutirée Distributeur, index 02"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>   - platform: teleinfo
>     id: teleinfo_EASD03
>     tag_name: "EASD03"
>     name: "Energie active soutirée Distributeur, index 03"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>   - platform: teleinfo
>     id: teleinfo_EASD04
>     tag_name: "EASD04"
>     name: "Energie active soutirée Distributeur, index 04"
>     unit_of_measurement: "Wh"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>     
>   - platform: teleinfo
>     id: teleinfo_IRMS1
>     tag_name: "IRMS1"
>     name: "Courant efficace"
>     unit_of_measurement: "A"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>     
>   - platform: teleinfo
>     id: teleinfo_URMS1
>     tag_name: "URMS1"
>     name: "Tension efficace"
>     unit_of_measurement: "V"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>     
>   - platform: teleinfo
>     id: teleinfo_UMOY1
>     tag_name: "UMOY1"
>     name: "Tension moy"
>     unit_of_measurement: "V"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo    
>     
>   - platform: teleinfo
>     id: teleinfo_SMAXSN
>     tag_name: "SMAXSN"
>     name: "Puissance app. max. soutirée n"
>     unit_of_measurement: "VA"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo   
> 
> #Puissance app max. soutirée n-1 SMAXSN-1 
>   - platform: teleinfo
>     id: teleinfo_SMAXSNm1
>     tag_name: "SMAXSN-1"
>     name: "Puissance app. max. soutirée n-1"
>     unit_of_measurement: "VA"
>     icon: mdi:flash
>     teleinfo_id: myteleinfo   
>     
> 
> text_sensor:
>   - platform: teleinfo
>     id: teleinfo_NTARF
>     tag_name: "NTARF"
>     name: "Numéro de l’index tarifaire en cours"
>     teleinfo_id: myteleinfo
>     
>   - platform: teleinfo
>     id: teleinfo_NJOURF
>     tag_name: "NJOURF"
>     name: "Numéro du jour en cours"
>     teleinfo_id: myteleinfo
>     
>   - platform: teleinfo
>     id: teleinfo_NJOURFp1
>     tag_name: "NJOURF+1"
>     name: "Numéro du prochain jour"
>     teleinfo_id: myteleinfo
>     
>   - platform: teleinfo
>     id: teleinfo_NGTF
>     tag_name: "NGTF"
>     name: "calendrier tarifaire"
>     teleinfo_id: myteleinfo
> 
>   - platform: teleinfo
>     id: teleinfo_LTARF
>     tag_name: "LTARF"
>     name: "tarif en cours"
>     teleinfo_id: myteleinfo
> ```
What is the UART config you are using when running it with esp32?
I have decoded the debug dump you pasted in a previous post and it all looks garbage. It's like the UART is not correctly configured.

**Comment by 0hax** [comment]
```
esphome:
  name: linky

esp8266:
  board: nodemcuv2
```

This is the esp8266 config which works right?
