### ISSUE TITLE
present not available for ThermostatClimate

### ISSUE THREAD

**Issue by Bascht74** [esphome/issues#2983]
### The problem

If you use `lambda: 'return (not(id(heater).away));` as documented [here](https://esphome.io/components/climate/index.html#lambda-calls)

you get:

```
/config/esphome/heizung-bad-eg.yaml: In lambda function:
/config/esphome/heizung-bad-eg.yaml:68:27: warning: 'esphome::climate::Climate::away' is deprecated (declared at src/esphome/components/climate/climate.h:198): away is deprecated, use preset instead [-Wdeprecated-declarations]
                 lambda: 'return (not(id(heater).away));'
```

But if you try to use the present function via `lambda: 'return id(heater).present != CLIMATE_PRESET_AWAY;'` you get: 
```
/config/esphome/heizung-bad-eg.yaml: In lambda function:
/config/esphome/heizung-bad-eg.yaml:68:22: error: 'class esphome::thermostat::ThermostatClimate' has no member named 'present'
                 lambda: 'return id(heater).present != CLIMATE_PRESET_AWAY;'
```
                

### Which version of ESPHome has the issue?

2022.1.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

./.

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

ThermostatClimate

### Example YAML snippet

```yaml
climate:
  - platform: thermostat
    name: "${upper_devicename}"
    id: heater
    sensor: thermometer_eg_bad_temperature
    default_target_temperature_low: 21 °C
    heat_deadband: 0.5 °C
    heat_overrun: 0.2 °C
    min_heating_off_time: 300s
    min_heating_run_time: 240s
    min_idle_time: 30s
    default_mode: heat
    heat_action:
      - switch.turn_on: shelly_relay
    idle_action:
      - switch.turn_off: shelly_relay
    visual:
      min_temperature: 16 °C
      max_temperature: 25 °C
      temperature_step: 0.5 °C
    away_config: 
      default_target_temperature_low: 16 °C

...
          - if:
              condition:
                lambda: 'return id(heater).present != CLIMATE_PRESET_AWAY;'
              then:             
                - climate.control:
                    id: heater
                    target_temperature: 21 °C
```

### Additional information

I use `id(heater).away` for now, but `preset` needs to be implemented if the statements above are right.
