### ISSUE TITLE
BLE Client Binary Output - howto write a value different from bool?

### ISSUE THREAD

**Issue by wettermann32** [esphome/issues#2986]
### The problem

I try to use BLE Client Binary Output to write the value 0x50 to a BT-Characteristic to trigger new measurement values from Radoneye sensor. Until now this is done by a custom component and works fine. Using now BLE Client i does not work. Reading values works fine, but no updates a generated. Debug Log message on write does never show up.

### Which version of ESPHome has the issue?

3.3.2 or 2022.1.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.12.10

### What platform are you using?

ESP32

### Board

lolin32

### Component causing the issue

BLE Client Binary Output

### Example YAML snippet

```yaml
esp32_ble_tracker:
  scan_parameters: 
    active: false

ble_client:
  - mac_address: c1:96:0d:53:e9:a6
    id: sensor_radon_eye

output:
  - platform: ble_client
    ble_client_id: sensor_radon_eye
    id: rtrigger
    service_uuid: '00001523-1212-efde-1523-785feabcd123'
    characteristic_uuid: '00001524-1212-efde-1523-785feabcd123'

fan:
  - platform: binary
    output: rtrigger
    name: "rtriggerFan"
    id: rtriggerfan
```

### Anything in the logs that might be useful for us?

```txt
[22:49:00][C][ble_binary_output:012]: BLE Binary Output:
[22:49:00][C][ble_binary_output:013]:   MAC address        : c1:96:0d:53:e9:a6
[22:49:00][C][ble_binary_output:014]:   Service UUID       : 00001523-1212-EFDE-1523-785FEABCD123
[22:49:00][C][ble_binary_output:015]:   Characteristic UUID: 00001524-1212-EFDE-1523-785FEABCD123
```

### Additional information

the fan component is used to write a value in a lambda:
      id(rtiggerfan).speed = 0x50;
      id(rtiggerfan).turn_on();
      id(rtiggerfan).turn_off();

So this might be the issue, but how can i write  just a value to my characteristic. Are there better ways?
