### ISSUE TITLE
Servo control with pca9685 as output

### ISSUE THREAD

**Issue by kobold81** [esphome/issues#2988]
### The problem

From reading the description of the servo component, I think controlling servos with the pca9685 channels as outputs seems possible. Connection to the pca9685 works as I also control some lights with it, but moving sliders in home assistant does not make the servos move.

Did I configure something wrong or is the servo compoent not intended to work with pca9685 as an output?

### Which version of ESPHome has the issue?

2022.1.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.12.10

### What platform are you using?

ESP32

### Board

esp32cam

### Component causing the issue

pca9685, servo

### Example YAML snippet

```yaml
# Enable Home Assistant API
api:
  password: ""
  services:
    - service: control_servo_1
      variables:
        level: float
      then:
        - servo.write:
            id: my_servo_1
            level: !lambda 'return level / 100.0;'
    
    - service: control_servo_2
      variables:
        level: float
      then:
        - servo.write:
            id: my_servo_2
            level: !lambda 'return level / 100.0;'

i2c:
  sda: 12
  scl: 13
  scan: true
  id: bus_a


pca9685:
  id: pca9685_1
  address: 0x40
  frequency: 60 #500

output:
  - platform: pca9685 #Ch5 - servo 1
    id: 'pca_channel5'
    channel: 5
  - platform: pca9685  #Ch6 - servo 2
    id: 'pca_channel6'
    channel: 6

servo:
  - id: my_servo_1
    output: pca_channel5

  - id: my_servo_2
    output: pca_channel6




Home Assistant:
automation.yaml:

#automation:
  - alias: Write Servo Value to ESP
    trigger:
      platform: state
      entity_id: input_number.servo_control1
    action:
      # Replace livingroom with the name you gave the ESP
      - service: esphome.esp32camera_control_servo1
        data_template:
          level: '{{ trigger.to_state.state | int }}'
          
  - alias: Write Servo2 Value to ESP
    trigger:
      platform: state
      entity_id: input_number.servo_control2
    action:
      # Replace livingroom with the name you gave the ESP
      - service: esphome.esp32camera_control_servo2
        data_template:
          level: '{{ trigger.to_state.state | int }}'




configuration.yaml:

input_number:
  servo_control1:
    name: Servo Control1
    initial: 0
    min: -100
    max: 100
    step: 1
    mode: slider
    
    
  servo_control2:
    name: Servo Control2
    initial: 0
    min: -100
    max: 100
    step: 1
    mode: slider
```

**Comment by randybb** [comment]
Since you have `id:` under your `pca9685:`, adding `pca9685_id: 'pca9685_1'` to your output definition will make any difference?
```yaml
output:
  - platform: pca9685 #Ch5 - servo 1
    id: 'pca_channel5'
    pca9685_id: 'pca9685_1'
    channel: 5
  - platform: pca9685  #Ch6 - servo 2
    id: 'pca_channel6'
    pca9685_id: 'pca9685_1'
    channel: 6
```
