### ISSUE TITLE
light.addressable_set command does not work

### ISSUE THREAD

**Issue by WiebKastanje** [esphome/issues#2989]
### The problem

**light.addressable_set** is not functioning with both **neopixelbus** and **fastled_clockless**.
No errormessages while compiling, no error messages when using this command. 
The LEDs do simply not act at all.

Tried many different colorsettings red: green: blue: white:
in **percentage %** as well as **!lambda ‘return 0.25'**

### Which version of ESPHome has the issue?

2022.1.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

all

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
light:          
  - platform: neopixelbus
    name: "Addressable"
    id: addressable
    pin: GPIO21
    num_leds: 38
    variant: SK6812
    type: GRBW           //any type is not working

on_turn_on:
   - light.addressable_set:
       id: addressable
       range_from: 1               //any number is not working
       range_to: 5                 //any number is not working
       color_brightness: 100%      //any percentage not working
       red: 100%                   //also !lambda return between 0 and 1 not working 
       green: 50%
       blue: 0%
       white: 50%
```

### Anything in the logs that might be useful for us?

```txt
no errors in the logs.
```

### Additional information

If you need me to test any change, let me know. I'm happy to provide assistance.
