### ISSUE TITLE
Weird Problem: Text Sensor not updating from HA sensors, all other sensor are fine

### ISSUE THREAD

**Issue by paul-at-pebbletech** [esphome/issues#2990]
### The problem

As suggested by Nick Rout from ESPHome group on HA community site I raising an issue here
Original post and diagnostics [https://community.home-assistant.io/t/weird-problem-text-not-updating-from-ha-sensors-all-other-sensor-are-fine/384415/16](url)
It appears others are also having the issue See [https://community.home-assistant.io/t/cant-get-a-sensor-value-from-the-homeassistant-text-sensor-or-from-sensor/297705](url)
Text sensors from HA are not received by the device but text values set by the device are seen in HA. The code has a pair of timers one just prints the values from the sensors. The other timer forces a value into one of the sensors. HA reports both sensor as unknown until the force event happens. Other HA sensors (Float / Binary) are fine and rxed by device. The bottom line is home assistant text based sensor values are not sent from HA. 
Simple Example Code

[simple log.txt](https://github.com/esphome/issues/files/7951315/simple.log.txt)

### Which version of ESPHome has the issue?

2022.1.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

core-2021.12.2

### What platform are you using?

ESP8266

### Board

D1 Mini clone

### Component causing the issue

text_sensor

### Example YAML snippet

```yaml
esphome:
  name: display_weather
  platform: ESP8266
  board: d1_mini
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

api:
  password: !secret api_password
  

ota:
  password: !secret ota_password

logger:
    baud_rate: 0     # Disable UART logging (pins GPIO1/3 are used for Nextion communication)
    # Enable fallback hotspot (captive portal) in case wifi connection fails
    level: VERY_VERBOSE
    logs: 
        api: VERY_VERBOSE
        homeassistant: VERY_VERBOSE
        api.service: VERY_VERBOSE
        sensor: VERY_VERBOSE
        scheduler: DEBUG


time:
  - platform: sntp
    id: sntp_time
    on_time:
      # Every 15 seconds
      - seconds: /15
        
        then:
          - lambda: |-
                std::string val = id(bsched).state;
                ESP_LOGD("main", "The current bsched is %s", val.c_str());
                val = id(input_text1).state;
                ESP_LOGD("main", "The current input_text1 is %s", val.c_str());
      
          # Every1 minutes
      - seconds: /30
        minutes: /2
        then:
            - lambda: |-
                  std::string val = id(bsched).state;
                  id(bsched).publish_state("ESP forced value");
                  ESP_LOGD("main", "Forcing current input_text1");

                
sensor:
 
  - platform: homeassistant   # Office temperature
    id: temperature_office
    entity_id: sensor.office_temperature_temperature
    internal: true
    
text_sensor:
  - platform:  homeassistant
    entity_id:  sensor.bschet
    name: "esp bsched rtn"
    id: bsched
    on_value:
      then:
        - lambda: |-
            ESP_LOGD("main", "The current schedba is %s", x.c_str());
            
  - platform: homeassistant
    name: "esp input test rtn"
    entity_id: input_text.text1
    id: input_text1
    on_value:
       then:
         - lambda:  ESP_LOGD("main", "The current input_text1 is %s", x.c_str());

  - platform: template
    name: "esp template test rtn"
    id: bscheda
    lambda: |-
      return {"Hello World"};
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
See logs attached all looks fine
```

### Additional information

Used the api instead to transfer the string sensor works as expected
` services:
    - service: update_schedule
      variables:
        my_string: string
      then:
        - globals.set:
            id: my_test_str
            value: !lambda 'return my_string;'`
