### ISSUE TITLE
DSMR: missing unit error when enableing gas consumption dsmr 5.0

### ISSUE THREAD

**Issue by dennisblokland** [esphome/issues#2993]
### The problem

The normale power consumption works fine but when i enable gas consumption it give me an error
`[12:28:11][E][dsmr:265]: 0-1:24.2.1(700101010000W)(00000000)
                                  ^
Missing unit`

### Which version of ESPHome has the issue?

2021.12.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.12.2

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

DSMR

### Example YAML snippet

```yaml
esphome:
  name: p1
  platform: ESP8266
  board: nodemcu
  

    
dsmr:
  id: dsmr_instance
  uart_id: uart_bus
  gas_mbus_id: 1

uart:
  - rx_pin:
      number: RX
      inverted: true
    rx_buffer_size: 1500
    baud_rate: 115200
    id: uart_bus  

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: Energy Consumed Tariff 1
    energy_delivered_tariff2:
      name: Energy Consumed Tariff 2
    energy_returned_tariff1:
      name: Energy Produced Tariff 1
    energy_returned_tariff2:
      name: Energy Produced Tariff 2
    power_delivered:
      name: Power Consumed
      unit_of_measurement: "W"
      accuracy_decimals: 0
      filters:
      - multiply: 1000
    power_returned:
      name: Power Produced
      unit_of_measurement: "W"
      accuracy_decimals: 0
      filters:
      - multiply: 1000
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    voltage_l2:
      name: "Voltage Phase 2"
    voltage_l3:
      name: "Voltage Phase 3"
    current_l1:
      name: "Current Phase 1"
    current_l2:
      name: "Current Phase 2"
    current_l3:
      name: "Current Phase 3"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_delivered_l2:
      name: "Power Consumed Phase 2"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_delivered_l3:
      name: "Power Consumed Phase 3"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_returned_l1:
      name: "Power Produced Phase 1"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_returned_l2:
      name: "Power Produced Phase 2"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_returned_l3:
      name: "Power Produced Phase 3"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    gas_delivered:
      name: "Gas Consumed"
      state_class: total_increasing


text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"


# Disable logging (uses the same uart as P1)
logger:
  level: DEBUG
  baud_rate: 0
  
# Enable Home Assistant API
api:

ota:
  #password: "SomeOtaPassword"

wifi:
  ssid: !secret wifi_ssid2
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHOME-P1"
    password: "configesp"

captive_portal:
```

### Additional information

I've tried all different gas_mbus_id's
