### ISSUE TITLE
Impossible to set api_key in secrets.yaml

### ISSUE THREAD

**Issue by raidnet-ms** [esphome/issues#2995]
### The problem

Every password can be substituted with !secret, except the api_key

### Which version of ESPHome has the issue?

2022.1.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.10

### What platform are you using?

ESP32

### Board

wemos battery

### Component causing the issue

api key

### Example YAML snippet

```yaml
api:
  password: !secret api_password
  encryption:
    key: !secret api_key
```

### Additional information

the device is unable to connect to api while correctly is available for ota
