### ISSUE TITLE
Refreshing web crashes nodemcu-32s

### ISSUE THREAD

**Issue by mplinuxgeek** [esphome/issues#2998]
### The problem

Refreshing the web page with the web component enabled causes a crash, without the web component the config works as expected.

### Which version of ESPHome has the issue?

2021.12.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

NJodeMCU32s

### Component causing the issue

web

### Example YAML snippet

```yaml
substitutions:
  devicename: "ble-gateway"
  devicename_upper: "BLE Gateway"
  
esphome:
  name: ble-gateway
  platform: ESP32
  #arduino_version: dev
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${devicename}
    password: !secret hotspot_password

ota:
  password: !secret ota_password

web_server:
  port: 80
  
# Enable Home Assistant API
#api:
#  password: ${password}

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  
logger:

status_led:
  pin: 
    number: GPIO2
    inverted: True

esp32_ble_tracker:

sensor:
```

### Anything in the logs that might be useful for us?

```txt
abort() was called at PC 0x401e0a7b on core 1

ELF file SHA256: 0000000000000000

Backtrace: 0x4008fa6c:0x3fff78d0 0x4008fce9:0x3fff78f0 0x401e0a7b:0x3fff7910 0x401e0ac2:0x3fff7930 0x401e03dd:0x3fff7950 0x401e04b4:0x3fff7970 0x400e614d:0x3fff7990 0x400e628b:0x3fff79b0 0x400d9e2a:0x3fff79e0 0x400e5b81:0x3fff7a30 0x400e5cdd:0x3fff7a60 0x400e5d5d:0x3fff7aa0 0x401ea66a:0x3fff7ac0 0x400e64e9:0x3fff7ae0 0x401e276a:0x3fff7b00 0x401e28d4:0x3fff7b30 0x401e2f2d:0x3fff7b50 0x40090d5e:0x3fff7b80

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
```
