### ISSUE TITLE
INA226 Max measured current its 0.818A

### ISSUE THREAD

**Issue by zac99** [esphome/issues#2999]
### The problem

The configuration has a current consumption above 1.5A and the INA226 mi shows a measurement of 0.818A. I set up two modals and they have the same reading.

### Which version of ESPHome has the issue?

2022.1.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.1

### What platform are you using?

ESP32

### Board

ESP-32WROOM-32

### Component causing the issue

INA226

### Example YAML snippet

```yaml
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a    

  
sensor:
  - platform: ina226
    address: 0x45
    shunt_resistance: 0.1 ohm
    current:
      name: "INA226 Current"
    power:
      name: "INA226 Power"
    bus_voltage:
      name: "INA226 Bus Voltage"
    shunt_voltage:
      name: "INA226 Shunt Voltage"
    max_current: 5.0A
    update_interval: 2s

  - platform: ina226
    address: 0x40
    shunt_resistance: 0.1 ohm
    current:
      name: "INA226_2 Current"
    power:
      name: "INA226_2 Power"
    bus_voltage:
      name: "INA226_2 Bus Voltage"
    shunt_voltage:
      name: "INA226_2 Shunt Voltage"
    max_current: 5.0A
    update_interval: 2s
```
