### ISSUE TITLE
Comile error on automation.h

### ISSUE THREAD

**Issue by mvturnho** [esphome/issues#300]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows running dev branch for esphome

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

**Description of problem:**
When compiling the yaml config i get the compile error on automation.h

```
In file included from src\esphome/components/binary_sensor/automation.h:4:0,
from src\main.cpp:3:
src/esphome/core/automation.h: In instantiation of 'bool esphome::Trigger<Ts>::is_running() [with Ts = {}]':
src\esphome/components/light/base_light_effects.h:72:34:   required from here
src/esphome/core/automation.h:58:48: error: request for member 'is_running' in '((esphome::Trigger<>*)this)->esphome::Trigger<>::automation_parent_', which is of pointer type 'esphome::Automation<>*' (maybe you meant to use '->' ?)
return this->automation_parent_.is_running();
^
src/esphome/core/automation.h: In member function 'bool esphome::Trigger<Ts>::is_running() [with Ts = {}]':
src/esphome/core/automation.h:59:3: warning: control reaches end of non-void function [-Wreturn-type]
}
^
```

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: schuur
  platform: ESP8266
  board: nodemcuv2
  on_boot:
      then:
          - light.turn_off: schuurlicht0

# Enable logging
logger:
  level: VERBOSE

i2c:
  sda: D2
  scl: D4
  scan: True

binary_sensor:
  - platform: gpio
    name: "motion1"
    pin:
      number: D6
      inverted: False
      mode: INPUT
    filters:
      - delayed_off: 30s
 
# PCF9685 16 channel PWM
pca9685:
  frequency: 500
  address: 0x40
#Outputs
output:
  - platform: pca9685
    id: 'output0'
    channel: 0

# Example configuration entry
light:
  - platform: monochromatic
    id: schuurlicht0
    name: "light0"
    output: output0
```

**Traceback (if applicable):**

```
$ esphome schuur.yaml compile
INFO Reading configuration...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d schuur
Processing schuur (framework: arduino; platform: espressif8266@1.8.0; board: nodemcuv2)

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz 80KB RAM (4MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 26 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <Wire> 1.0
Compiling .pioenvs\schuur\src\esphome\components\binary_sensor\automation.cpp.o
Compiling .pioenvs\schuur\src\esphome\components\binary_sensor\binary_sensor.cpp.o
Compiling .pioenvs\schuur\src\esphome\components\binary_sensor\filter.cpp.o
Compiling .pioenvs\schuur\src\esphome\components\gpio\binary_sensor\gpio_binary_sensor.cpp.o
Compiling .pioenvs\schuur\src\esphome\components\i2c\i2c.cpp.o
Compiling .pioenvs\schuur\src\esphome\components\light\addressable_light.cpp.o
Compiling .pioenvs\schuur\src\esphome\components\light\light_state.cpp.o
Compiling .pioenvs\schuur\src\esphome\components\logger\logger.cpp.o
Compiling .pioenvs\schuur\src\esphome\components\output\automation.cpp.o
Compiling .pioenvs\schuur\src\esphome\components\output\float_output.cpp.o
Compiling .pioenvs\schuur\src\esphome\components\pca9685\pca9685_output.cpp.o
Compiling .pioenvs\schuur\src\esphome\core\application.cpp.o
Compiling .pioenvs\schuur\src\esphome\core\component.cpp.o
Compiling .pioenvs\schuur\src\esphome\core\controller.cpp.o
Compiling .pioenvs\schuur\src\esphome\core\esphal.cpp.o
Compiling .pioenvs\schuur\src\esphome\core\helpers.cpp.o
Compiling .pioenvs\schuur\src\esphome\core\log.cpp.o
Compiling .pioenvs\schuur\src\esphome\core\preferences.cpp.o
Compiling .pioenvs\schuur\src\esphome\core\util.cpp.o
Compiling .pioenvs\schuur\src\main.cpp.o
Generating LD script .pioenvs\schuur\ld\eagle.app.v6.common.ld
Compiling .pioenvs\schuur\libb43\ESP8266WiFi\BearSSLHelpers.cpp.o
Compiling .pioenvs\schuur\libb43\ESP8266WiFi\CertStoreBearSSL.cpp.o
Compiling .pioenvs\schuur\libb43\ESP8266WiFi\ESP8266WiFi.cpp.o
In file included from src\esphome/components/binary_sensor/automation.h:4:0,
from src\main.cpp:3:
src/esphome/core/automation.h: In instantiation of 'bool esphome::Trigger<Ts>::is_running() [with Ts = {}]':
src\esphome/components/light/base_light_effects.h:72:34:   required from here
src/esphome/core/automation.h:58:48: error: request for member 'is_running' in '((esphome::Trigger<>*)this)->esphome::Trigger<>::automation_parent_', which is of pointer type 'esphome::Automation<>*' (maybe you meant to use '->' ?)
return this->automation_parent_.is_running();
^
src/esphome/core/automation.h: In member function 'bool esphome::Trigger<Ts>::is_running() [with Ts = {}]':
src/esphome/core/automation.h:59:3: warning: control reaches end of non-void function [-Wreturn-type]
}
^
*** [.pioenvs\schuur\src\main.cpp.o] Error 1
 [ERROR] Took 18.75 seconds

```

**Additional information and things you've tried:**

Removed all automation stuf from the yaml, to no effect.
