### ISSUE TITLE
Again. Intense Light flash on H801 on connecting power

### ISSUE THREAD

**Issue by volkerjaenisch** [esphome/issues#3001]
### The problem

There is a intense appx. 50ms long flash wenn connecting the H801 to power. 

As discussed (and solved!) here in #1783 as well as at Tasmota:
[Tasmota 649](https://github.com/arendst/Tasmota/issues/649)
[Tasmota 7165](https://github.com/arendst/Tasmota/issues/7165)

The Problem is that the GPIOs driving the MOSFETs are in an undefined state while starting the firmware. This was the cause bei tasmota and it is not far fetched that this is the problem with esphome also.

### Which version of ESPHome has the issue?

esphome 2022.1.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.12.7

### What platform are you using?

ESP8266

### Board

H801

### Component causing the issue

H801

### Example YAML snippet

```yaml
esphome:
  name: h801

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG
  hardware_uart: uart1

# Enable Home Assistant API
api:
  password: "xxxx"
ota:
  password: "xxxx"

wifi:
  ssid: "xxxx"
  password: "xxxx"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal h801light"
    update_interval: 60s

output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w
light:
  - platform: rgbw
    name: "H801 Light"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
```

### Anything in the logs that might be useful for us?

```txt
Nothing, sorry.
```

### Additional information

Beside this intensive flash everything works as expected.

This problem was solved in an older version see #1783 but has resurfaced. So I am quite sure that it can be solved quite easily, by tracking the code changes concerning the mentioned fix. 

I flashed the H801 utilizing esphome on the newest raspberryPiOS Buster on a raspberryPI4.
