### ISSUE TITLE
PMS5003ST reports wrong data in negative temperature with esp32

### ISSUE THREAD

**Issue by worldwidefelix** [esphome/issues#3013]
### The problem

PMS50003ST reporst frantic high data in negative temperatures.

![E4050966-8264-4DCF-8EC1-F022485B94DE](https://user-images.githubusercontent.com/59109996/152447471-1d845d0d-8053-44d6-99b4-857fca6d71fd.png

my esphome yaml:

      

### Which version of ESPHome has the issue?

2022.1.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.2.0

### What platform are you using?

ESP32

### Board

Esp32devkit4

### Component causing the issue

uart

### Example YAML snippet

```yaml
uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  
sensor:
  - platform: pmsx003
    type: PMS5003ST
    pm_1_0:
      name: "PM <1.0µm Concentration"
    pm_2_5:
      name: "PM <2.5µm Concentration"
    pm_10_0:
      name: "PMr <10.0µm Concentration"
    temperature:
      name: "pms-temp"
   humidity:
      name: "pms-humid"
    formaldehyde:
      name: "pms-formaldehude"
```
