### ISSUE TITLE
RDM6300 no longer compiles

### ISSUE THREAD

**Issue by tomlut** [esphome/issues#3015]
### The problem

The example code in the documents for the RDM6300 component:

```
rdm6300:
  # ...
  on_tag:
    then:
      - homeassistant.tag_scanned: !lambda 'return uint32_to_string(x);'
```
<https://esphome.io/components/binary_sensor/rdm6300.html#on-tag>

Now causes the build to fail with this error:

```
/config/esphome/nfc-scanner.yaml: In lambda function:
/config/esphome/nfc-scanner.yaml:98:32: error: 'uint32_to_string' was not declared in this scope
       - homeassistant.tag_scanned: !lambda 'return uint32_to_string(x);'
```

### Which version of ESPHome has the issue?

2022.1.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.2.1

### What platform are you using?

ESP32

### Board

mhetesp32minikit

### Component causing the issue

RDM6300

### Example YAML snippet

```yaml
rdm6300:
  uart_id: nfc_uart
  on_tag:
    then:
      - homeassistant.tag_scanned: !lambda 'return uint32_to_string(x);'
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

**Comment by maxill1** [comment]
Same problem here with identical Esphome and HA versions

**Comment by tomlut** [comment]
Still an issue with ESPHome 2022.3.0

**Comment by tomlut** [comment]
The Docs are updated, solving this issue:

```
rdm6300:
  # ...
  on_tag:
    then:
      - homeassistant.tag_scanned: !lambda 'return to_string(x);'
```
