### ISSUE TITLE
Compile api issue

### ISSUE THREAD

**Issue by aero83** [esphome/issues#302]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HassIO/Docker AMDx64

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 Mini
**Affected component:**

https://esphome.io/components/sensor/bme280.html

**Description of problem:**
When attempting to compile to change or update  I get this in the compile window. 
`[API] ConnectionError: HTTPConnectionPool(host='api.platformio.org', port=80): Max retries exceeded with url: /v2/lib/search?query=name%3A%22AsyncMqttClient%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71c7716510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) (incremented retry: max=5, total=1)
[API] ConnectionError: HTTPConnectionPool(host='api.platformio.org', port=80): Max retries exceeded with url: /v2/lib/search?query=name%3A%22AsyncMqttClient%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71c7716590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) (incremented retry: max=5, total=2)
[API] ConnectionError: HTTPConnectionPool(host='api.platformio.org', port=80): Max retries exceeded with url: /v2/lib/search?query=name%3A%22AsyncMqttClient%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71c7716850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) (incremented retry: max=5, total=3)
[API] ConnectionError: HTTPConnectionPool(host='api.platformio.org', port=80): Max retries exceeded with url: /v2/lib/search?query=name%3A%22AsyncMqttClient%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71c7716d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) (incremented retry: max=5, total=4)
[API] ConnectionError: HTTPConnectionPool(host='api.platformio.org', port=80): Max retries exceeded with url: /v2/lib/search?query=name%3A%22AsyncMqttClient%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71c7982610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) (incremented retry: max=5, total=5)
Error: [API] Could not connect to PlatformIO API Service. Please try later.`

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: alexander_room
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'NSA'
  password: 'redacted'

mqtt:
  broker: '192.168.10.45'
  username: ''
  password: ''
# Example configuration entry
i2c:
  sda: 5
  scl: 4
  scan: False
# Example configuration entry
sensor:
  - platform: bme280
    temperature:
      name: "Alexanders Room Temp"
      oversampling: 8x
    pressure:
      name: "Alexanders Room Pressure"
    humidity:
      name: "Alexanders Room Humidity"
    address: 0x76
    update_interval: 60s
# Enable logging
logger:

ota:
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
