### ISSUE TITLE
Modbus switch abnormal loop behavior

### ISSUE THREAD

**Issue by vladniko** [esphome/issues#3021]
### The problem

So, I am trying to send one write command only when a button was pressed  but I don't figure out why reset_day_counter_switch id executes in a loop sending data on the bus all time.
I've tried in the first attempt with switch but it always resets to on state and the loop happens again :(
Is there any way to implement the function I need until a fix? 

### Which version of ESPHome has the issue?

2022.1.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
uart:
  id: mod_bus
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 9600
  parity: EVEN
  data_bits: 8
  stop_bits: 1
  
modbus:
  flow_control_pin: GPIO12
  id: modbus1
  send_wait_time: 200ms

modbus_controller:
  - id: epever
    ## the Modbus device addr
    address: 0x1
    command_throttle: 100ms
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 5s
    
switch:
  - platform: modbus_controller
    modbus_controller_id: epever
    id: reset_day_counter_switch
    internal: true
    skip_updates: 10 
    custom_command: [0x01, 0x10, 0x60, 0x49, 0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00]
    
button:
  - platform: template
    name: "rst"
    id: rst_btn
    on_press:
      then:
        - switch.turn_on: reset_day_counter_switch
        - delay: 1s
        - switch.turn_off: reset_day_counter_switch
```
