### ISSUE TITLE
Restoring rotary encoded does not respect min/max values

### ISSUE THREAD

**Issue by sjtrny** [esphome/issues#3022]
### The problem

If the min/max range of a rotary encoder are narrowed in the config file then the device will restore with a value that can be outside the required range.

The restoration process should check the min-max value and clip appropriately.

### Which version of ESPHome has the issue?

2022.1.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
First config:

  - platform: rotary_encoder
    name: "fornuftig speed"
    resolution: 1
    min_value: 0
    max_value: 100

Second config:


  - platform: rotary_encoder
    name: "fornuftig speed"
    resolution: 1
    min_value: 0
    max_value: 10
```
