### ISSUE TITLE
Logging with MQTT throw some garbage

### ISSUE THREAD

**Issue by Francis-perso** [esphome/issues#3026]
### The problem

I'm trying to use MQTT to have some log infos, but despite "esphome logs xxx.yaml" finds its children, the MQTT server (Mosquitto) shows some garbage.

### Which version of ESPHome has the issue?

2022.1.2

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

ESP01_1M

### Component causing the issue

logger with MQTT

### Example YAML snippet

```yaml
logger:
  baud_rate: 0
  level: INFO
  on_message:
    level: INFO
    then:
    - wait_until: mqtt.connected
    - mqtt.publish_json:
        topic: domoticz/in
        payload: |-
          root["command"] = "addlogmessage";
          root["message"] = message;
          root["level"] = to_string(level);
```

### Anything in the logs that might be useful for us?

```txt
[01:20:24][I][mqtt:215]: MQTT Connected!
[01:20:24][I][app:062]: setup() finished successfully!
[01:20:24][I][app:102]: ESPHome version 2022.1.2 compiled on Feb  8 2022, 01:14:04
[01:20:24][I][i2c.arduino:053]: Results from i2c bus scan:
[01:20:24][I][i2c.arduino:059]: Found i2c device at address 0x38
```

### Additional information

Seen in MQTT logs (via mosquitto_sub -t domoticz/in) :

{"command":"addlogmessage","message":"[I][mqtt:215]: MQTT Connected!","level":"3"}
{"command":"addlogmessage","message":"[I][app:062]: setup() finished successfully!","level":"3"}
{"command":"addlogmessage","message":"ssfully!","level":"3"}
{"command":"addlogmessage","message":"[I][app:102]: ESPHome version 2022.1.2 compiled on Feb  8 2022, 01:14:04","level":"3"}
{"command":"addlogmessage","message":".2 compiled on %s","level":"3"}
{"command":"addlogmessage","message":".2 compiled on %s","level":"3"}
{"command":"addlogmessage","message":"[I][i2c.arduino:053]: Results from i2c bus scan:","level":"3"}
{"command":"addlogmessage","message":"[I][i2c.arduino:059]: Found i2c device at address 0x38","level":"3"}
{"command":"addlogmessage","message":"dress 0x%02X","level":"3"}
{"command":"addlogmessage","message":"dress 0x%02X","level":"3"}
{"command":"addlogmessage","message":"dress 0x%02X","level":"3"}
