### ISSUE TITLE
`http_request` fails on SSL request when `esp32_ble_tracker` is enabled

### ISSUE THREAD

**Issue by rplnt** [esphome/issues#3035]
### The problem

`http_request` component fails to connect over SSL when BLE tracker is enabled. It incorrectly reports `connection refused` (basically default error in the http client, but that's another issue). Tried various servers with different configurations, it reliably fails on my (unknown) board. Did not try to debug the network (to see at what point it fails) or any other boards.

- BLE + HTTP works fine
- HTTPS without BLE works fine

Not sure what the cause is, but there's not report of ESPHome not being able to make a HTTPS request, so this might help people to track down the issue. Also would be helpful if others could try to reproduce it on another hardware.

- Probably related: https://github.com/esphome/issues/issues/2112

### Which version of ESPHome has the issue?

2022.1.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

esp32_ble_tracker

### Example YAML snippet

```yaml
esphome:
  name:
esp32:
  board: esp32dev
  framework:
    type: arduino
api:
  password:
ota:
  password: 
wifi:
  ssid:
  password:
http_request:
esp32_ble_tracker:
interval:
  interval: 1min
  then:
    - http_request.get:
        url: https://example.com
        verify_ssl: false
```

### Anything in the logs that might be useful for us?

```txt
http_request fails with `connection refused`
```
