### ISSUE TITLE
Fluctuating pulse_meter readings 

### ISSUE THREAD

**Issue by kjoglum** [esphome/issues#3036]
### The problem

I have a Carlo Gavazzi EM340 energy meter with S0 output (defaults at 30ms pulse / 1000 pulses pr kWh), measuring the energy usage for a water heater included in a heating circuit with an air to water heat pump. I.e. the control system for the air to water heat pump controls the water heater through a contactor, meaning the water heater will only be allowed to be active if additional heating is needed to achieve desired flow temperature (and if temperature measured in the water heater itself is below threshold).

Following the guidelines from ESPHome homepage, I have used a Wemos D1 ESP32 to connect to the EM340 S0 (breadboard connection): 5v from ESP32 to EM340 S0 input (have also tried 3.3V with same results), and from EM340 S0 output to (1) ESP32 GND, via 10k resistor and (2) ESP32 GPIO12.

I am using the ESPHome pulse_meter setup, and I do get reading for both _instant_ and _total_ usage, however, the instant readings are fluctuating quite heavy (even when the EM340 itself reports 0), thus also causing a deviating _total_ usage (after 8 hrs today, the _total_ from pulse_meter is 3 kW above what is read directly from the EM340). The _instant_ value fluctuates between 0.2-3 kW when EM340 is reporting 0, also having some additional spikes at higher values.

Having read through different forum threads I have tried altering  the internal_filter without any luck. As my water heater is 2x7.5 kW, I have calculated 240 ms as the longest internal_filter I can use, still being able to detect highest possible consumption.

### Which version of ESPHome has the issue?

v2022.1.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

Wemos D1 ESP32

### Component causing the issue

pulse_meter

### Example YAML snippet

```yaml
sensor:
  - platform: pulse_meter
    pin: 
      number: 12
    unit_of_measurement: 'kW'
    name: 'VVB - Electricity Usage'
    id: vvbenergy_instant
    internal_filter: 240ms
    accuracy_decimals: 3
    timeout: 30 sec
    filters:
      - multiply: 0.06
    on_value: 
      - mqtt.publish:
          topic: vvbenergy/sensor/vvb_-_electricity_usage
          payload: !lambda |-
            return to_string(id(vvbenergy_instant).state);
      
    total:
      name: "VVB - Electricity Total"
      id: vvbenergy_total
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
      on_value: 
      - mqtt.publish:
          topic: vvbenergy/sensor/vvb_-_electricity_total/state
          payload: !lambda |-
            return to_string(id(vvbenergy_total).state);
```

### Additional information

I have correct measurements of the total home consumption, showing when the water heater actually is active. As shown in the screenshot below, the pulse_meater readings (red, following the kW axis)) fits quite ok with the periods when the heater actually is active, but fluctuates/spikes when the heater is off:

<img width="951" alt="Skjermbilde 2022-02-11 kl  19 56 35" src="https://user-images.githubusercontent.com/47720690/153652647-73236ab7-29f8-4e5d-bd9c-ab2846e8cffd.png">
