### ISSUE TITLE
ESP32 with neopixel bus flash of old status when turn on

### ISSUE THREAD

**Issue by cicinovec** [esphome/issues#3038]
### The problem

When turning on Neopixel light (effect or normal), there is always a flash of previous light 
e.g. when the light was red on 100% brightness before, then turned off and another day with effect turned on the light first flashes with 100% red and then transfers to effect

### Which version of ESPHome has the issue?

2022.1.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.2.6

### What platform are you using?

ESP32

### Board

ESP32 generic

### Component causing the issue

light

### Example YAML snippet

```yaml
esphome:
  name: bedroom-plant-led

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Plant-Led"
    password: !secret wifi_password

captive_portal:

light:
  - platform: neopixelbus
    type: GRB
    pin: GPIO23
    num_leds: 60
    variant: WS2812X
    restore_mode: ALWAYS_OFF
    name: "Bedroom LED light"
    id: bedroom_led
    #default_transition_length: 3s
    effects:
      - lambda:
          name: Wake Up 2
          update_interval: 5s
          lambda: |-
            static int state = 0;
            auto call = id(bedroom_led).turn_on();
            call.set_rgb(0.0, 0.0, 1.0);
            call.set_brightness(0.01 * (state)); // 1.0 is full brightness
            call.perform();
            state += 1;
            if (state > 100)
              state = 100;
```

### Anything in the logs that might be useful for us?

```txt
[09:20:30][D][light:035]: 'Bedroom LED light' Setting:
[09:20:30][D][light:046]:   State: ON
[09:20:30][D][light:107]:   Effect: 'Wake Up 2'
[09:20:30][D][light:035]: 'Bedroom LED light' Setting:
[09:20:30][D][light:050]:   Brightness: 43%
[09:20:30][D][light:058]:   Red: 0%, Green: 0%, Blue: 100%
[09:20:30][D][light:084]:   Transition length: 1.0s
[09:20:35][D][light:035]: 'Bedroom LED light' Setting:
[09:20:35][D][light:050]:   Brightness: 44%
[09:20:35][D][light:058]:   Red: 0%, Green: 0%, Blue: 100%
[09:20:35][D][light:084]:   Transition length: 1.0s
```
