### ISSUE TITLE
Docker fresh install "Can’t connect to ESP. Please make sure your YAML file contains an ‘api:’ line."

### ISSUE THREAD

**Issue by gvdhoven** [esphome/issues#3046]
### The problem

I spun up a fresh install of ESPHome next to my home assistant docker setup in order to create my ESPHome devices. The docker-compose part is this:

```
automation-esphome:
    image: esphome/esphome:latest
    container_name: automation-esphome
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    networks:
      f43lan:
        ipv4_address: 192.168.1.108
    ports:
      - 6052:6052
      - 6123:6123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/automation/esphome/config:/config
```

as you can see nothing special; All my containers which i should be able to reach either via SSL (Traefik) or internally on the network i have it setup on a separate IP since i don't want to expose my entire server + ports to the world.

The error message i get while installing the integration in HA is:
> "Can’t connect to ESP. Please make sure your YAML file contains an ‘api:’ line."

p.s. i have verified that ESPHome dashboard works while navigating to the IP so the docker instance is running.

**Q: What am i doing wrong to get the dashboard working in HA?**

Changing `networks:` to `network_mode: host` doesn't resolve the issue since HA still needs to be on a traefik network in order for me to host it myself with SSL.

### Which version of ESPHome has the issue?

latest docker image

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.0.dev20220204

### What platform are you using?

ESP32

### Board

n/a

### Component causing the issue

n/a

### Example YAML snippet

```yaml
n/a
```

### Anything in the logs that might be useful for us?

```txt
n/a
```

### Additional information

n/a
