### ISSUE TITLE
i2c - ssd1306 is not working after update to 2022.2.1

### ISSUE THREAD

**Issue by MiguelCosta** [esphome/issues#3051]
### The problem

Hi, 

after update to the last ESPHome version and upgrade the firmware of my ssd1306 the 2022.2.1 version, the lcd screen doesn't work.

![image](https://user-images.githubusercontent.com/645482/154361800-b8c95fde-2e59-471b-a24a-0e2fc988457f.png)

After rollback the firmware to the 2022.1.4 everything is OK

### Which version of ESPHome has the issue?

2022.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2022.2.7

### What platform are you using?

ESP32

### Board

esp32cam

### Component causing the issue

i2c

### Example YAML snippet

```yaml
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    update_interval: never
    id: esp32_display
    pages:
      - id: page1
        lambda: |-
          it.print(64, 0, id(my_font), TextAlign::TOP_CENTER, "Energia");
          it.print(0, 30, id(my_font_small), TextAlign::CENTER_LEFT , "Agora:");
          it.printf(128, 30, id(my_font_big), TextAlign::CENTER_RIGHT, "%sW", id(salamandra_energy_current).state.c_str());
          it.print(0, 50, id(my_font_small), TextAlign::CENTER_LEFT , "Hoje:");
          it.printf(128, 50, id(my_font_big), TextAlign::CENTER_RIGHT , "%skWh", id(salamandra_energy_daily).state.c_str());
```
