### ISSUE TITLE
Docker container won´t start without USB device connected

### ISSUE THREAD

**Issue by wassereimer86** [esphome/issues#3055]
### The problem

Docker container won´t start if the USB Device is not connected. But i always want to add the USB port to esphome if i want to add a new device via usb.

### Which version of ESPHome has the issue?

2022.2.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Board

-

### Component causing the issue

-

### Example YAML snippet

```yaml
esphome:
    container_name: esphome
    image: esphome/esphome
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /home/xxx/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - xxx:6052
      - xxx:6053
    restart: always
    environment:
      - NETWORK_ACCESS=internal
      - ESPHOME_DASHBOARD_USE_PING=true
```

### Anything in the logs that might be useful for us?

```txt
error gathering device information while adding custom device "/dev/ttyUSB0": no such file or directory
```
