### ISSUE TITLE
Disable cover stop button

### ISSUE THREAD

**Issue by archerne** [esphome/issues#3059]
### The problem

If no "stop_action" is set in a cover template ESPHome should pass a "supported_features: 3" instead of "supported_features: 11" so that there is no stop button in Home Assistant. 

### Which version of ESPHome has the issue?

2022.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.2.8

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

cover

### Example YAML snippet

```yaml
cover:
  - platform: template
    device_class: garage
    id: "garage_door_cover"
    name: "Garage Door"
    has_position: false
    open_action:
      - switch.turn_on: side_garage_relay
      - delay: 0.1s
      - switch.turn_off: side_garage_relay
      - cover.template.publish:
          id: garage_door_cover
          state: !lambda 'return COVER_OPERATION_OPENING;'
    close_action:
      - switch.turn_on: side_garage_relay
      - delay: 0.1s
      - switch.turn_off: side_garage_relay
      - cover.template.publish:
          id: garage_door_cover
          state: !lambda 'return COVER_OPERATION_CLOSING;'
    assumed_state: false
```
