### ISSUE TITLE
Cover Toggle not enabled for Endstop cover

### ISSUE THREAD

**Issue by terminusxx** [esphome/issues#3061]
### The problem

Cover.toggle works great on time duration covers but is not enabled on endstop covers. Looking at endstop_cover.cpp it is missing `supports_toggle` under traits and the` if call.get_toggle` block from the control section. Since endstop cover requires a duration for gate position I can't think of a reason why toggle wouldn't work with it. 

### Which version of ESPHome has the issue?

2022.2.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.2.8

### What platform are you using?

ESP32

### Component causing the issue

endstop_cover

### Example YAML snippet

```yaml
button:
  - platform: template
    name: "Back Gate Toggle"
    on_press:
      - cover.toggle: gate
      
output:
  - platform: gpio
    pin: 17
    id: sh_direction_pin1
    inverted: true
  - platform: gpio
    pin: 16
    id: sh_direction_pin2
    inverted: true

cover:
  - platform: endstop
    name: "Back Gate"
    device_class: gate
    id: gate
    open_action:
      - output.turn_off: sh_direction_pin1
      - output.turn_on: sh_direction_pin2
    open_duration: 27s
    open_endstop: openlimit

    close_action:
      - output.turn_off: sh_direction_pin2
      - output.turn_on: sh_direction_pin1
    close_duration: 27s
    stop_action:
      - output.turn_off: sh_direction_pin1
      - output.turn_off: sh_direction_pin2
    close_endstop: closedlimit
```
