### ISSUE TITLE
Opening multiple covers triggers watchdog

### ISSUE THREAD

**Issue by sentinelt** [esphome/issues#3066]
### The problem

I have custom board with ESP32 devkitc with 64 inputs based on 4 MCP23017 and  64 outputs based on 8 tpic6a595dw (driven by sn74hc595 ESPHome's component).

Currently I have 12 time-based covers and 12 lights defined in ESPHome's configuration file. Inputs are not defined yet.

When I  open or close circa 8 or more covers after a while ESP32 resets itself.

I watched the serial output through USB cable and it shows the reset is triggered by the watchdog. Just before the watchdog triggers there is a lot of ESP_ERR_NVS_NOT_ENOUGH_SPACE errors.

Is this a bug? Or have I hit some limit?

### Which version of ESPHome has the issue?

2022.2.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.12.9

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

time_based,preferences

### Example YAML snippet

```yaml
substitutions:
  node_name: solaris2

esphome:
  name: $node_name
esp32:
  board: esp32dev

wifi:
  networks:
    - ssid: "<ssid>"
      password: "<password>"

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:
web_server:
  port: 80

sn74hc595:
  - id: 'tpic6a595_0'
    data_pin: 16
    clock_pin: 17
    latch_pin: 18
    sr_count: 4
  - id: 'tpic6a595_1'
    data_pin: 4
    clock_pin: 23
    latch_pin: 19
    sr_count: 4
output:
  - platform: gpio
    id: out_port0_pin0
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 0
      inverted: false
  - platform: gpio
    id: out_port0_pin1
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 1
      inverted: false
  - platform: gpio
    id: out_port0_pin2
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 2
      inverted: false
  - platform: gpio
    id: out_port0_pin3
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 3
      inverted: false
  - platform: gpio
    id: out_port0_pin4
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 4
      inverted: false
  - platform: gpio
    id: out_port0_pin5
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 5
      inverted: false
  - platform: gpio
    id: out_port0_pin6
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 6
      inverted: false
  - platform: gpio
    id: out_port0_pin7
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 7
      inverted: false
  - platform: gpio
    id: out_port1_pin0
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 8
      inverted: false
  - platform: gpio
    id: out_port1_pin1
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 9
      inverted: false
  - platform: gpio
    id: out_port1_pin2
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 10
      inverted: false
  - platform: gpio
    id: out_port1_pin3
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 11
      inverted: false
  - platform: gpio
    id: out_port1_pin4
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 12
      inverted: false
  - platform: gpio
    id: out_port1_pin5
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 13
      inverted: false
  - platform: gpio
    id: out_port1_pin6
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 14
      inverted: false
  - platform: gpio
    id: out_port1_pin7
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 15
      inverted: false
  - platform: gpio
    id: out_port2_pin0
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 16
      inverted: false
  - platform: gpio
    id: out_port2_pin1
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 17
      inverted: false
  - platform: gpio
    id: out_port2_pin2
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 18
      inverted: false
  - platform: gpio
    id: out_port2_pin3
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 19
      inverted: false
  - platform: gpio
    id: out_port2_pin4
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 20
      inverted: false
  - platform: gpio
    id: out_port2_pin5
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 21
      inverted: false
  - platform: gpio
    id: out_port2_pin6
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 22
      inverted: false
  - platform: gpio
    id: out_port2_pin7
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 23
      inverted: false
  - platform: gpio
    id: out_port3_pin0
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 24
      inverted: false
  - platform: gpio
    id: out_port3_pin1
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 25
      inverted: false
  - platform: gpio
    id: out_port3_pin2
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 26
      inverted: false
  - platform: gpio
    id: out_port3_pin3
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 27
      inverted: false
  - platform: gpio
    id: out_port3_pin4
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 28
      inverted: false
  - platform: gpio
    id: out_port3_pin5
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 29
      inverted: false
  - platform: gpio
    id: out_port3_pin6
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 30
      inverted: false
  - platform: gpio
    id: out_port3_pin7
    pin:
      sn74hc595: 'tpic6a595_0'
      number: 31
      inverted: false
  - platform: gpio
    id: out_port4_pin0
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 0
      inverted: false
  - platform: gpio
    id: out_port4_pin1
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 1
      inverted: false
  - platform: gpio
    id: out_port4_pin2
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 2
      inverted: false
  - platform: gpio
    id: out_port4_pin3
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 3
      inverted: false
  - platform: gpio
    id: out_port4_pin4
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 4
      inverted: false
  - platform: gpio
    id: out_port4_pin5
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 5
      inverted: false
  - platform: gpio
    id: out_port4_pin6
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 6
      inverted: false
  - platform: gpio
    id: out_port4_pin7
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 7
      inverted: false
  - platform: gpio
    id: out_port5_pin0
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 8
      inverted: false
  - platform: gpio
    id: out_port5_pin1
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 9
      inverted: false
  - platform: gpio
    id: out_port5_pin2
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 10
      inverted: false
  - platform: gpio
    id: out_port5_pin3
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 11
      inverted: false
  - platform: gpio
    id: out_port5_pin4
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 12
      inverted: false
  - platform: gpio
    id: out_port5_pin5
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 13
      inverted: false
  - platform: gpio
    id: out_port5_pin6
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 14
      inverted: false
  - platform: gpio
    id: out_port5_pin7
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 15
      inverted: false
  - platform: gpio
    id: out_port6_pin0
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 16
      inverted: false
  - platform: gpio
    id: out_port6_pin1
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 17
      inverted: false
  - platform: gpio
    id: out_port6_pin2
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 18
      inverted: false
  - platform: gpio
    id: out_port6_pin3
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 19
      inverted: false
  - platform: gpio
    id: out_port6_pin4
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 20
      inverted: false
  - platform: gpio
    id: out_port6_pin5
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 21
      inverted: false
  - platform: gpio
    id: out_port6_pin6
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 22
      inverted: false
  - platform: gpio
    id: out_port6_pin7
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 23
      inverted: false
  - platform: gpio
    id: out_port7_pin0
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 24
      inverted: false
  - platform: gpio
    id: out_port7_pin1
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 25
      inverted: false
  - platform: gpio
    id: out_port7_pin2
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 26
      inverted: false
  - platform: gpio
    id: out_port7_pin3
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 27
      inverted: false
  - platform: gpio
    id: out_port7_pin4
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 28
      inverted: false
  - platform: gpio
    id: out_port7_pin5
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 29
      inverted: false
  - platform: gpio
    id: out_port7_pin6
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 30
      inverted: false
  - platform: gpio
    id: out_port7_pin7
    pin:
      sn74hc595: 'tpic6a595_1'
      number: 31
      inverted: false


light:
  - platform: binary
    name: "Korytarz przy wiatrołapie"
    output: out_port3_pin0
  - platform: binary
    name: "Schody do piwnicy"
    output: out_port3_pin1
  - platform: binary
    name: "WC lustro"
    output: out_port3_pin2
  - platform: binary
    name: "WC"
    output: out_port3_pin3
  - platform: binary
    name: "Łazienka lustro"
    output: out_port3_pin4
  - platform: binary
    name: "Łazienka"
    output: out_port3_pin5
  - platform: binary
    name: "Sypialnia"
    output: out_port4_pin0
  - platform: binary
    name: "Garaż"
    output: out_port4_pin4
  - platform: binary
    name: "Salon - LED pionowy przy tarasie"
    output: out_port5_pin6
  - platform: binary
    name: "Kuchnia - podświetlenia szafek"
    output: out_port6_pin0
  - platform: binary
    name: "Kuchnia - nad wyspą"
    output: out_port6_pin1
  - platform: binary
    name: "Schowanko"
    output: out_port6_pin3
cover:
  - platform: time_based
    name: "Roleta salon południe lewa"
    open_action:
      - output.turn_off: out_port0_pin1
      - output.turn_on: out_port0_pin0
    open_duration: 30s

    close_action:
      - output.turn_on: out_port0_pin1
      - output.turn_on: out_port0_pin0
    close_duration: 28s

    stop_action:
      - output.turn_off: out_port0_pin1
      - output.turn_off: out_port0_pin0
  - platform: time_based
    name: "Roleta salon południe prawa"
    open_action:
      - output.turn_off: out_port0_pin3
      - output.turn_on: out_port0_pin2
    open_duration: 30s

    close_action:
      - output.turn_on: out_port0_pin3
      - output.turn_on: out_port0_pin2
    close_duration: 28s

    stop_action:
      - output.turn_off: out_port0_pin3
      - output.turn_off: out_port0_pin2
  - platform: time_based
    name: "Roleta salon południowy-zachód lewa"
    open_action:
      - output.turn_off: out_port0_pin5
      - output.turn_on: out_port0_pin4
    open_duration: 30s

    close_action:
      - output.turn_on: out_port0_pin5
      - output.turn_on: out_port0_pin4
    close_duration: 28s

    stop_action:
      - output.turn_off: out_port0_pin5
      - output.turn_off: out_port0_pin4
  - platform: time_based
    name: "Roleta salon południowy-zachód prawa"
    open_action:
      - output.turn_off: out_port0_pin7
      - output.turn_on: out_port0_pin6
    open_duration: 30s

    close_action:
      - output.turn_on: out_port0_pin7
      - output.turn_on: out_port0_pin6
    close_duration: 28s

    stop_action:
      - output.turn_off: out_port0_pin7
      - output.turn_off: out_port0_pin6
  - platform: time_based
    name: "Roleta salon zachód lewa"
    open_action:
      - output.turn_off: out_port1_pin1
      - output.turn_on: out_port1_pin0
    open_duration: 30s

    close_action:
      - output.turn_on: out_port1_pin1
      - output.turn_on: out_port1_pin0
    close_duration: 28s

    stop_action:
      - output.turn_off: out_port1_pin1
      - output.turn_off: out_port1_pin0
  - platform: time_based
    name: "Roleta salon zachód prawa"
    open_action:
      - output.turn_off: out_port1_pin3
      - output.turn_on: out_port1_pin2
    open_duration: 30s

    close_action:
      - output.turn_on: out_port1_pin3
      - output.turn_on: out_port1_pin2
    close_duration: 28s

    stop_action:
      - output.turn_off: out_port1_pin3
      - output.turn_off: out_port1_pin2
  - platform: time_based
    name: "Roleta salon taras"
    open_action:
      - output.turn_off: out_port1_pin5
      - output.turn_on: out_port1_pin4
    open_duration: 30s

    close_action:
      - output.turn_on: out_port1_pin5
      - output.turn_on: out_port1_pin4
    close_duration: 28s

    stop_action:
      - output.turn_off: out_port1_pin5
      - output.turn_off: out_port1_pin4
  - platform: time_based
    name: "Roleta kuchnia"
    open_action:
      - output.turn_off: out_port1_pin7
      - output.turn_on: out_port1_pin6
    open_duration: 21s

    close_action:
      - output.turn_on: out_port1_pin7
      - output.turn_on: out_port1_pin6
    close_duration: 21s

    stop_action:
      - output.turn_off: out_port1_pin7
      - output.turn_off: out_port1_pin6
  - platform: time_based
    name: "Roleta schowanko"
    open_action:
      - output.turn_off: out_port2_pin1
      - output.turn_on: out_port2_pin0
    open_duration: 21s

    close_action:
      - output.turn_on: out_port2_pin1
      - output.turn_on: out_port2_pin0
    close_duration: 21s

    stop_action:
      - output.turn_off: out_port2_pin1
      - output.turn_off: out_port2_pin0
  - platform: time_based
    name: "Roleta łazienka"
    open_action:
      - output.turn_off: out_port2_pin3
      - output.turn_on: out_port2_pin2
    open_duration: 21s

    close_action:
      - output.turn_on: out_port2_pin3
      - output.turn_on: out_port2_pin2
    close_duration: 21s

    stop_action:
      - output.turn_off: out_port2_pin3
      - output.turn_off: out_port2_pin2
  - platform: time_based
    name: "Roleta sypialnia"
    open_action:
      - output.turn_off: out_port2_pin5
      - output.turn_on: out_port2_pin4
    open_duration: 21s

    close_action:
      - output.turn_on: out_port2_pin5
      - output.turn_on: out_port2_pin4
    close_duration: 21s

    stop_action:
      - output.turn_off: out_port2_pin5
      - output.turn_off: out_port2_pin4
  - platform: time_based
    name: "Roleta garderoba"
    open_action:
      - output.turn_off: out_port2_pin7
      - output.turn_on: out_port2_pin6
    open_duration: 21s

    close_action:
      - output.turn_on: out_port2_pin7
      - output.turn_on: out_port2_pin6
    close_duration: 21s

    stop_action:
      - output.turn_off: out_port2_pin7
      - output.turn_off: out_port2_pin6
```

### Anything in the logs that might be useful for us?

```txt
[D][cover:172]: 'Roleta garderoba' - Publishing:
[D][cover:175]:   Position: 0%
[D][cover:188]:   Current Operation: IDLE
[VV][api.service:086]: send_cover_state_response: CoverStateResponse {
                                                                        key: 3361204376
                                                                                         legacy_state: LEGACY_COVER_STATE_CLOSED
                        position: 0
                                     tilt: 0
                                              current_operation: COVER_OPERATION_IDLE
                                                                                     }
[VV][scheduler:186]: Running interval '' with interval=10000 last_execution=491431 (now=501435)
[D][cover:172]: 'Roleta salon południowy-zachód prawa' - Publishing:
[D][cover:175]:   Position: 0%
[D][cover:188]:   Current Operation: IDLE
[VV][api.service:086]: send_cover_state_response: CoverStateResponse {
                                                                        key: 4254214330
                                                                                         legacy_state: LEGACY_COVER_STATE_CLOSED
                        position: 0
                                     tilt: 0
                                              current_operation: COVER_OPERATION_IDLE
                                                                                     }
[V][component:199]: Component time_based.cover took a long time for an operation (0.06 s).
[V][component:200]: Components should block for at most 20-30ms.
[D][cover:172]: 'Roleta salon zachód prawa' - Publishing:
[D][cover:175]:   Position: 2%
[D][cover:188]:   Current Operation: CLOSING
[VV][api.service:086]: send_cover_state_response: CoverStateResponse {
                                                                        key: 946227043
                                                                                        legacy_state: LEGACY_COVER_STATE_CLOSED
                       position: 0.0235828
                                            tilt: 0
                                                     current_operation: COVER_OPERATION_IS_CLOSING
                                                                                                  }
[V][component:199]: Component time_based.cover took a long time for an operation (0.06 s).
[V][component:200]: Components should block for at most 20-30ms.
[D][cover:172]: 'Roleta salon zachód lewa' - Publishing:
[D][cover:175]:   Position: 0%
[D][cover:188]:   Current Operation: IDLE
[VV][api.service:086]: send_cover_state_response: CoverStateResponse {
                                                                        key: 1676042721
                                                                                         legacy_state: LEGACY_COVER_STATE_CLOSED
                        position: 0
                                     tilt: 0
                                              current_operation: COVER_OPERATION_IDLE
                                                                                     }
[V][component:199]: Component time_based.cover took a long time for an operation (0.06 s).
[V][component:200]: Components should block for at most 20-30ms.
[D][cover:172]: 'Roleta salon taras' - Publishing:
[D][cover:175]:   Position: 3%
[D][cover:188]:   Current Operation: CLOSING
[VV][api.service:086]: send_cover_state_response: CoverStateResponse {
                                                                        key: 91281130
                                                                                       legacy_state: LEGACY_COVER_STATE_CLOSED
                      position: 0.0257247
                                           tilt: 0
                                                    current_operation: COVER_OPERATION_IS_CLOSING
                                                                                                 }
[V][component:199]: Component time_based.cover took a long time for an operation (0.06 s).
[V][component:200]: Components should block for at most 20-30ms.
[D][cover:172]: 'Roleta salon zachód prawa' - Publishing:
[D][cover:175]:   Position: 0%
[D][cover:188]:   Current Operation: IDLE
[VV][api.service:086]: send_cover_state_response: CoverStateResponse {
                                                                        key: 946227043
                                                                                        legacy_state: LEGACY_COVER_STATE_CLOSED
                       position: 0
                                    tilt: 0
                                             current_operation: COVER_OPERATION_IDLE
                                                                                    }
[V][component:199]: Component time_based.cover took a long time for an operation (0.06 s).
[V][component:200]: Components should block for at most 20-30ms.
[D][cover:172]: 'Roleta salon taras' - Publishing:
[D][cover:175]:   Position: 0%
[D][cover:188]:   Current Operation: IDLE
[VV][api.service:086]: send_cover_state_response: CoverStateResponse {
                                                                        key: 91281130
                                                                                       legacy_state: LEGACY_COVER_STATE_CLOSED
                      position: 0
                                   tilt: 0
                                            current_operation: COVER_OPERATION_IDLE
                                                                                   }
[V][component:199]: Component time_based.cover took a long time for an operation (0.06 s).
[V][component:200]: Components should block for at most 20-30ms.
[VV][api.service:355]: on_ping_request: PingRequest {}
[VV][api.service:043]: send_ping_response: PingResponse {}
[VV][api.service:355]: on_ping_request: PingRequest {}
[VV][api.service:043]: send_ping_response: PingResponse {}
[VV][scheduler:186]: Running interval '' with interval=10000 last_execution=501431 (now=511431)
[VV][api.service:355]: on_ping_request: PingRequest {}
[VV][api.service:043]: send_ping_response: PingResponse {}
[VV][api.service:355]: on_ping_request: PingRequest {}
[VV][api.service:043]: send_ping_response: PingResponse {}
[VV][scheduler:186]: Running interval '' with interval=10000 last_execution=511431 (now=521431)
[VV][scheduler:186]: Running interval '' with interval=60000 last_execution=464321 (now=524321)
[D][esp32.preferences:114]: Saving preferences to flash...
[V][esp32.preferences:124]: nvs_set_blob('91280550', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('946226471', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('1676043229', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-40752498', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-933762324', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-1584195674', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('1466471067', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-1155597034', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('1032853729', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-903033865', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('719190930', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-881956998', len=8) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-830894668', len=44) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('23536854', len=44) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-855996261', len=44) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-738034106', len=44) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('1021256862', len=44) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-1519612499', len=44) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('-1186049112', len=44) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
[V][esp32.preferences:124]: nvs_set_blob('1531987422', len=44) failed: ESP_ERR_NVS_NOT_ENOUGH_SPACE
E (530574) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (530574) task_wdt:  - loopTask (CPU 1)
E (530574) task_wdt: Tasks currently running:
E (530574) task_wdt: CPU 0: ipc0
E (530574) task_wdt: CPU 1: IDLE1
E (530574) task_wdt: Aborting.
abort() was called at PC 0x4015b33c on core 0

ELF file SHA256: 0000000000000000

Backtrace: 0x40088bdc:0x3ffbf900 0x40088e59:0x3ffbf920 0x4015b33c:0x3ffbf940 0x400872f1:0x3ffbf960 0x40084fad:0x3ffb9d60 0x40087a91:0x3ffb9d80 0x40084d2b:0x3ffb9da0 0x40089e6a:0x3ffb9dc0

Rebooting...
```
