### ISSUE TITLE
Unable to compile ESP32 boards

### ISSUE THREAD

**Issue by jeffborg** [esphome/issues#3070]
### The problem

Seems some standard c++ libs are missing in esp32

### Which version of ESPHome has the issue?

2022.2.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

Generic ESP32

### Component causing the issue

core

### Example YAML snippet

```yaml
# any esp32 board will cause 

esphome:
  name: esp32test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "XXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Test Fallback Hotspot"
    password: "XXXXXXXX"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esp32test.yaml...
INFO Generating C++ source...
INFO Core config or version changed, cleaning build files...
INFO Compiling app...
Processing esp32test (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <WiFi> 1.0
|-- <FS> 1.0
|-- <Update> 1.0
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <DNSServer> 1.1.0
|-- <ESPmDNS> 1.0
Compiling .pioenvs/esp32test/src/esphome/components/api/api_connection.cpp.o
In file included from src/esphome/components/api/api_connection.h:3:0,
                 from src/esphome/components/api/api_connection.cpp:1:
src/esphome/core/component.h:3:18: fatal error: string: No such file or directory
compilation terminated.
Compiling .pioenvs/esp32test/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/esp32test/src/esphome/components/api/api_pb2.cpp.o
In file included from src/esphome/components/api/api_frame_helper.cpp:1:0:
src/esphome/components/api/api_frame_helper.h:2:19: fatal error: cstdint: No such file or directory
compilation terminated.
*** [.pioenvs/esp32test/src/esphome/components/api/api_connection.cpp.o] Error 1
*** [.pioenvs/esp32test/src/esphome/components/api/api_frame_helper.cpp.o] Error 1
Compiling .pioenvs/esp32test/src/esphome/components/api/api_pb2_service.cpp.o
In file included from src/esphome/components/api/proto.h:3:0,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_pb2.cpp:3:
src/esphome/core/component.h:3:18: fatal error: string: No such file or directory
compilation terminated.
*** [.pioenvs/esp32test/src/esphome/components/api/api_pb2.cpp.o] Error 1
In file included from src/esphome/components/api/proto.h:3:0,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_pb2_service.h:5,
                 from src/esphome/components/api/api_pb2_service.cpp:3:
src/esphome/core/component.h:3:18: fatal error: string: No such file or directory
compilation terminated.
*** [.pioenvs/esp32test/src/esphome/components/api/api_pb2_service.cpp.o] Error 1
========================== [FAILED] Took 4.32 seconds ==========================
```

### Additional information

All esp8266 boards I can compile with 2022.2.4 but none of the esp32's will build
