### ISSUE TITLE
Error while setting the time parameter for 'for Condition'.

### ISSUE THREAD

**Issue by Plazmin** [esphome/issues#3073]
### The problem

I cannot compile the program due to an error "expected float"

![esphome 2](https://user-images.githubusercontent.com/62091912/154913515-50ba54a9-b571-4e08-a8f9-2f55eb013a16.png)

![esphome 1](https://user-images.githubusercontent.com/62091912/154914183-3ab0afd4-3e15-4127-a524-25fb3e8438be.png)

If I change the type of the variable  _time_to_off_  to float, the problem persists.

### Which version of ESPHome has the issue?

2021.11.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2022.2.9

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

Automation "for Condition"

### Example YAML snippet

```yaml
# Variable definition
globals:
  - id: time_to_off
    type: int
    initial_value: '16200'


# Condition part
        - if:
            condition:
              for:
                time:
                  seconds: id(time_to_off)
                condition:
                  binary_sensor.is_on: max_switch_on_time
            then:
              - lambda: |-
                  id(max_switch_on_time).publish_state(false);
```
