### ISSUE TITLE
DSMR readings go on and off in energy after update from 21th december last year

### ISSUE THREAD

**Issue by jeroomdm** [esphome/issues#3082]
### The problem

I'm using the Zuidkwijk DSMR reader. Since an update on the 21th of december my readings go on and off.
If i go and look at the website of my dsmr reader i see all the readings are okay.

![220219](https://user-images.githubusercontent.com/5408131/155111912-207dc281-445c-4c47-aaac-411d10011b8f.png)
![220220](https://user-images.githubusercontent.com/5408131/155111917-70798907-cc64-4acb-be0e-740ce56b14d3.png)
![220221](https://user-images.githubusercontent.com/5408131/155111918-856bc3fa-6b5e-4fae-b2bf-0bf025d0b17a.png)
![220222](https://user-images.githubusercontent.com/5408131/155111919-92a90dac-033b-4e0c-9d7b-ca51a94f044f.png)

### Which version of ESPHome has the issue?

2022.x

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.

### What platform are you using?

ESP8266

### Board

zuidwijk dsmr

### Component causing the issue

dsmr

### Example YAML snippet

```yaml
---
substitutions:
  device_name: slimmelezer
  device_description: "DIY P1 module to read your smart meter"
     
esphome:
  name: ${device_name}
  comment: "${device_description}"
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: d1_mini
  name_add_mac_suffix: false
  project:
    name: zuidwijk.slimmelezer
    version: "1.0"
  on_boot:
    then:
      - if:
          condition:
            lambda: return id(has_key);
          then:
            - lambda: |-
                std::string key(id(stored_decryption_key), 32);
                id(dsmr_instance).set_decryption_key(key);
          else:
            - logger.log:
                level: info
                format: "Not using decryption key. If you need to set a key use Home Assistant service 'ESPHome:  ${device_name}_set_dsmr_key'"
 
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    ap_timeout: 15s
 
captive_portal:
 
# Enable logging
logger:
#  baud_rate: 0
 
# Enable Home Assistant API
api:
  services:
    service: set_dsmr_key
    variables:
      private_key: string
    then:
      - logger.log:
          format: Setting private key %s. Set to empty string to disable
          args: [private_key.c_str()]
      - globals.set:
          id: has_key
          value: !lambda "return private_key.length() == 32;"
      - lambda: |-
          if (private_key.length() == 32)
            private_key.copy(id(stored_decryption_key), 32);
          id(dsmr_instance).set_decryption_key(private_key);
 
ota:
 
web_server:
  port: 80
 
uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 1500
 
globals:
  - id: has_key
    type: bool
    restore_value: yes
    initial_value: "false"
  - id: stored_decryption_key
    type: char[32]
    restore_value: yes
 
dsmr:
  id: dsmr_instance
sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
      state_class: total_increasing
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
      state_class: total_increasing
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
      state_class: total_increasing
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
      state_class: total_increasing
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      name: "Power Produced"
      accuracy_decimals: 3
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    current_l1:
      name: "Current Phase 1"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_returned_l1:
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    gas_delivered_be:
      name: "Gas Consumed"
      state_class: total_increasing
  - platform: uptime
    name: "SlimmeLezer Uptime"
  - platform: wifi_signal
    name: "SlimmeLezer Wi-Fi Signal"
    update_interval: 60s
 
text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version_be:
      name: "DSMR Version"
  - platform: wifi_info
    ip_address:
      name: "SlimmeLezer IP Address"
    ssid:
      name: "SlimmeLezer Wi-Fi SSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
```

### Anything in the logs that might be useful for us?

```txt
Logs only showing uptime & wifi signal
[11:21:54][D][sensor:124]: 'SlimmeLezer Uptime': Sending state 46363.34375 s with 0 decimals of accuracy
[11:22:01][D][sensor:124]: 'SlimmeLezer Wi-Fi Signal': Sending state -25.00000 dBm with 0 decimals of accuracy
[11:22:54][D][sensor:124]: 'SlimmeLezer Uptime': Sending state 46423.34375 s with 0 decimals of accuracy
[11:23:01][D][sensor:124]: 'SlimmeLezer Wi-Fi Signal': Sending state -25.00000 dBm with 0 decimals of accuracy
```
