### ISSUE TITLE
BME680 crashes system after last update of ESPHome

### ISSUE THREAD

**Issue by rmeissn** [esphome/issues#3083]
### The problem

I've updated my ESP8266 setups from 2021.12 to 2022.2.4 today and started wondering, because one of the devices stopped sending values to HomeAssisstant. This is an indoor environment sensor station with two DHT22, a BH1750 and a BME680.
The device is shown in the ESPHome dashboard as "Online", but the Dashboard isn't able to connect to the device to show logs (Errno 111). I was able to wirelessly reflash the device successfully, but this didn't change anything.

So I started looking at the device itself. When powering it up, the small LED near the wifi antenna blinks 10 times. I started to pull some sensors and after pulling the BME680, the device only blinked once (instead of 10 times), started successfully and is reachable again. As soon as I plug the BME680 back in (and repowering the device) it stops working again.

As I haven't touched the device before and while updating, I guess there must be some software issue related to this behaviour. The device worked as expected 1min before updating it and stopped working after the update.

### Which version of ESPHome has the issue?

2022.2.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

bme680

### Example YAML snippet

```yaml
esphome:
  name: bme680
  platform: ESP8266
  board: nodemcuv2

logger:
  baud_rate: 0

api:

ota:
  password: "..."

wifi:
  ssid: "..."
  password: "..."
  output_power: 10 # in db
  domain: '...'

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bme680 Fallback Hotspot"
    password: "..."

captive_portal:

i2c:
  sda: D1
  scl: D2

bme680_bsec:
    # i2c address
    # -----------
    # Common values are:
    # - 0x76
    # - 0x77
    # Default: 0x76
    address: 0x77

    # Temperature offset
    # ------------------
    # Useful if device is in enclosure and reads too high
    # Default: 0
    temperature_offset: 0.3

    # IAQ calculation mode
    # --------------------
    # Available options:
    # - static (for fixed position devices)
    # - mobile (for on person or other moveable devices)
    # Default: static
    iaq_mode: static

    # Sample rate
    # -----------
    # Available options:
    # - lp (low power - samples every 3 seconds)
    # - ulp (ultra low power - samples every 5 minutes)
    # Default: lp
    sample_rate: ulp

    # Interval at which to save BSEC state
    # ------------------------------------
    # Default: 6h
    state_save_interval: 6h

sensor:
  - platform: bme680_bsec
    temperature:
      # Temperature in °C
      name: "BME680 Temperature"
      filters:
        - median:
            window_size: 3
            send_every: 3
    pressure:
      # Pressure in hPa
      name: "BME680 Pressure"
      filters:
        - median:
            window_size: 3
            send_every: 3
    humidity:
      # Relative humidity %
      name: "BME680 Humidity"
      filters:
        - median:
            window_size: 3
            send_every: 3
    gas_resistance:
      # Gas resistance in Ω
      name: "BME680 Gas Resistance"
      filters:
        - median:
            window_size: 3
            send_every: 3
    iaq:
      # Indoor air quality value
      name: "BME680 IAQ"
      filters:
        - median:
            window_size: 3
            send_every: 3
    iaq_accuracy:
      # IAQ accuracy as a numeric value of 0, 1, 2, 3
      name: "BME680 Numeric IAQ Accuracy"
    co2_equivalent:
      # CO2 equivalent estimate in ppm
      name: "BME680 CO2 Equivalent"
      icon: "mdi:molecule-co2"
      filters:
        - median:
            window_size: 3
            send_every: 3
    breath_voc_equivalent:
      # Volatile organic compounds equivalent estimate in ppm
      name: "BME680 Breath VOC Equivalent"
      filters:
        - median:
            window_size: 3
            send_every: 3
#
  - platform: dht
    model: DHT22
    pin: D5
    temperature:
      name: "DHT1 Temperature"
      filters:
        - median:
            window_size: 3
            send_every: 3
    humidity:
      name: "DHT1 Humidity"
      filters:
        - median:
            window_size: 3
            send_every: 3
    update_interval: 5min
#
  - platform: dht
    model: DHT22
    pin: D6
    temperature:
      name: "DHT2 Temperature"
      filters:
        - median:
            window_size: 3
            send_every: 3
    humidity:
      name: "DHT2 Humidity"
      filters:
        - median:
            window_size: 3
            send_every: 3
    update_interval: 5min
#
  - platform: bh1750
    name: "BH1750 Brightness"
    address: 0x23
    resolution: 1.0
    measurement_duration: 69
    update_interval: 5min
    filters:
      - median:
          window_size: 3
          send_every: 3


text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "BME680 IAQ Accuracy"
```
