### ISSUE TITLE
RGBW Lights strange behaviour since version 2022.2.4 (possibly earlier)

### ISSUE THREAD

**Issue by sparkydave1981** [esphome/issues#3084]
### The problem

I updated my RGBW downlights from 2021.12.x to 2022.2.4 and now they won't fully turn off, plus brightness control is erratic.

When turning the lights off from Home Assistant the light dims down to very low brightness but stays on even though HA reports it as off.  

Brightness control is not as it was previously with the control being erratic and not properly following that of the brightness slider in HA.  It seems that they stay very dim unless the brightness is set to 100%.

Other than updating the ESPhome version no other settings were changed and the lights worked perfectly previously.

### Which version of ESPHome has the issue?

2022.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.2.9

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

rgbw light (my9231)

### Example YAML snippet

```yaml
my9231:
 data_pin: GPIO13  # GPIO13 for AiLight
 clock_pin: GPIO15  # GPIO15 for AiLight
 num_channels: 4
 num_chips: 1

output:
  - platform: my9231
    id: output_blue
    channel: 1
  - platform: my9231
    id: output_red
    channel: 3
  - platform: my9231
    id: output_green
    channel: 2
  - platform: my9231
    id: output_white
    channel: 0

light:
  - platform: rgbw
    name: Living Room Downlight 3
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    color_interlock: true
    id: living
```

### Anything in the logs that might be useful for us?

```txt
No errors in log
```

**Comment by sparkydave1981** [comment]
I'm also finding some lights randomly turning on, but again, HA still thinks they are off so it's like they aren't reporting that state back.

**Comment by YvesZH** [comment]
I have the same issue with all my 'my9231' lights after i updating from 2021.12.x. to 2022.2.5.
After noticing the error, i activated the web server on the affected esp.  Even there the toggle button doesn't work (same effect), although everything is displayed correctly in the log.

**Comment by YvesZH** [comment]
another addition: the problems did not occur when i updated esphome to home assistant.  The problems started when I updated the esp/lamps from 2021.12.x to 2022.2.5 a few days later.

**Comment by sparkydave1981** [comment]
> I have the same issue with all my 'my9231' lights after i updating from 2021.12.x. to 2022.2.5. After noticing the error, i activated the web server on the affected esp. Even there the toggle button doesn't work (same effect), although everything is displayed correctly in the log.

Well I'm glad I'm not the only person with this problem, so hopefully it gets fixed for us.

In the meantime do you know how we can install an old version of ESPhome?  I tried with Docker but couldn't access the GUI as I obviously had something wrong...

**Comment by sparkydave1981** [comment]
> another addition: the problems did not occur when i updated esphome to home assistant (from 2021.12.x to 2022.2.5). The problems started when I updated the esp/lamps OTA from 2021.12.x to 2022.2.5 a few days later.

Yes, updating the version of ESPhome within HA doesn't really do anything until you send a new .bin file to the device itself.

**Comment by sparkydave1981** [comment]
Also, I have a forum thread about this [here](https://community.home-assistant.io/t/esphome-rgbw-lights-behaving-strange-since-upgrade-to-2022-2-4/396147).

**Comment by dylan09** [comment]
Did you use Home Assistant API integration or MQTT?

**Comment by YvesZH** [comment]
> Did you use Home Assistant API integration or MQTT?

I use HA API

**Comment by dylan09** [comment]
Ok. Than its not directly related to some of my problems. They began if I remember correctly with 2021.10.
There where some changes to ESPHome light integration.

maybe you could test your light with ```color_interlock: false```? Be careful with brightness if you switch on RGB and white together.

**Comment by YvesZH** [comment]
> Ok. Than its not directly related to some of my problems. They began if I remember correctly with 2021.10.
> There where some changes to ESPHome light integration.

I roll back to 2021.11.4 and its work as aspect (after compiling and uploading the ESP/lamps).  I remember the led-esp change (was nice), but it had nothing to do with it.  Do you know someone you could involve in this topic who can help?

**Comment by esplor** [comment]
I have the same problems with my Sonoff B1's rgbww.
After upgrading esphome to 2022.2.X it stopped working, would not change colours or even turn on/off.

The workaround for me was to set older framework version:

Complete config that works:
```
esphome:
  name: REPLACEME

esp8266:
  board: esp01_1m
# After upgrade ESPHOME 2022.2.X Sonoff B1 stopped working
  framework:
    version: 2.7.4

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

logger:
api:
ota:
web_server:

my9231:
  data_pin: GPIO12  # GPIO13 for AiLight
  clock_pin: GPIO14  # GPIO15 for AiLight
  num_channels: 6
  num_chips: 2

output:
  - platform: my9231
    id: output_blue
    channel: 0
  - platform: my9231
    id: output_red
    channel: 1
  - platform: my9231
    id: output_green
    channel: 2
  - platform: my9231
    id: output_warm_white
    channel: 4
  - platform: my9231
    id: output_cold_white
    channel: 5

light:
  - platform: rgbww
    name: REPLACEME
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold_white
    cold_white_color_temperature: 6500 K
    warm_white: output_warm_white
    warm_white_color_temperature: 2800 K
```
