### ISSUE TITLE
ESP32 home assistant sensors

### ISSUE THREAD

**Issue by sargas88** [esphome/issues#3096]
### The problem

Hi to All,
importing sensor from Home Assistant in ESP 32 is not working for me.
The same code work perfectly on a ESP8266 D1 mini board. 
I've also tried to use it in an "old" flashed ESP32 board (same board) that was initially flashed on May (about) and it work.

All the board with ESP32 that i've tried now doesn't work (TTGO T7 and classic nodemcu ESP32).

Any idea? is a know bug?

sensor:
  - platform: homeassistant
    name: "Temperatura esterna"
    entity_id: sensor.shelly1_xxxxxxxxx_temperature
    id: tempest 

### Which version of ESPHome has the issue?

2022.2.5

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

last

### What platform are you using?

ESP32

### Board

TTGO T7 and Nodemcu ESP32

### Component causing the issue

Home assistant sensors

### Example YAML snippet

```yaml
sensor:
  - platform: homeassistant
    name: "Temperatura esterna"
    entity_id: sensor.shelly1_68c63afb52f6_temperature
    id: tempest
```

### Anything in the logs that might be useful for us?

```txt
no log, on the web interface is reported NAN
```
