### ISSUE TITLE
Text Sensor Component to_lower filter converts all text to UPPERCASE instead of lowercase

### ISSUE THREAD

**Issue by rudiniemeijer** [esphome/issues#3097]
### The problem

The Text Sensor Component filter to_lower does a to_upper instead of a to_lower.

Reproduce:

text_sensor:
  - platform: homeassistant
    name: "Weather short"
    id: weather_short
    entity_id: sensor.knmi_thuis_korte_dagverwachting
    filters:
      - to_lower:

When the value "Cloudy and Occasional Rain" is provided to the sensor, instead of the expected value "cloudy and occasional rain" the sensor transmits "CLOUDY AND OCCASIONAL RAIN", like the to_upper filter.

### Which version of ESPHome has the issue?

2022.2.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.0b4

### What platform are you using?

ESP8266

### Component causing the issue

Text Sensor

### Example YAML snippet

```yaml
text_sensor:
  - platform: homeassistant
    name: "Weer kort"
    id: weer_kort
    entity_id: sensor.knmi_thuis_korte_dagverwachting
    filters:
      - to_lower:
      - prepend: "KNMI weer kort: "
      - append: "."
    internal: true
```

### Anything in the logs that might be useful for us?

```txt
[19:34:47][D][homeassistant.text_sensor:017]: 'sensor.knmi_thuis_korte_dagverwachting': Got state 'Vandaag en morgen zonnig en droog'
[19:34:47][D][text_sensor:067]: 'Weer kort': Sending state 'KNMI weer kort: VANDAAG EN MORGEN ZONNIG EN DROOG.'
```
