### ISSUE TITLE
http_request with on_message logger

### ISSUE THREAD

**Issue by quentin9696** [esphome/issues#3098]
### The problem

I try to make HTTP request on_message action with the logger component. This will help me to have a central logging with Loki, since I got a large number of device to manage. 

This syntax don't works with logger component. 

```yaml
logger:
  level: VERY_VERBOSE
  on_message:
    then:
      - http_request.post:
          url: http://xxx.xxx.xxx.xxx:3100/loki/api/v1/push
          headers:
            Content-Type: application/json
          body: !lambda |-
            return "{\"streams\": [{ \"stream\": { \"room\": \"desk\" }, \"values\": [ [ \"" + to_string(id(sntp_time).now().timestamp) + "000000000\", \"" + message + "\" ] ] }]}";
```

The same syntax works with a sensor, so it's not an issue with my Loki. Also, I capture network packets on my loki server and I can't see anything. I can get other packet comming from my ESP (prometheus metrics), so ESP is well connected on my wifi network and packets transit from it. 

FYI, here is a working workflow with a basic DHT sensor:

```yaml
sensor:
  - platform: dht
    pin: 4
    temperature:
      name: "temperature"
      id: "dht22_temperature"
      on_value:
        then:
          - http_request.post:
              url: http://192.168.0.137:3100/loki/api/v1/push
              headers:
                Content-Type: application/json
              body: !lambda |-
                return "{\"streams\": [{ \"stream\": { \"room\": \"desk\" }, \"values\": [ [ \"" + to_string(id(sntp_time).now().timestamp) + "000000000\", \"" + to_string(x) + "\" ] ] }]}";
    humidity:
      name: "humidity"
      id: "dht22_humidity"
    update_interval: 2s
    model: DHT22
```

### Which version of ESPHome has the issue?

ESPHome version 2022.2.5

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

esp-wrover-kit

### Component causing the issue

logger

### Example YAML snippet

```yaml
check issue description above
```
