### ISSUE TITLE
SX1509 component keypad engine doesn't to allow the creation of a binary sensor keypad with more than 4 rows or columns

### ISSUE THREAD

**Issue by gmarcc** [esphome/issues#3099]
### The problem

I'm trying to use SX1509's built in keypad engine to interface with a 6x5 keypad matrix. The DX1509 integration page indicates that the keypad engine can interface with up to 64 buttons set up in an 8x8 matrix, so a 6x5 keypad should work. While I can specify a 6x5 keypad matrix in the "sx1509:" section of the YAML file, ESPHome doesn't let me create a binary sensor that includes more than 4 rows or 4 columns.  When trying to do so, ESPHome shows the following error when trying to upload the code into the ESP8266: "value must be at most 4".  I think the ESPHome should allow for binary sensors with up to 8 rows and 8 columns per the documentation. Perhaps it's a bug.

### Which version of ESPHome has the issue?

2022.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.2.9

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

SX1509

### Example YAML snippet

```yaml
sx1509:
  - id: sx1509_hub1
    address: 0x3E
    keypad:
      key_rows: 6
      key_columns: 5
      sleep_time: 256

binary sensor:
  - platform: sx1509
    sx1509_id: sx1509_hub1
    name: "Button06"
    row: 5
    col: 0
  - platform: sx1509
    sx1509_id: sx1509_hub1
    name: "Button30"
    row: 6
    col: 0
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/master-bedroom-keypad-marc.yaml...
Failed config

binary_sensor.sx1509: [source /config/esphome/master-bedroom-keypad-marc.yaml:82]
  platform: sx1509
  sx1509_id: sx1509_hub1
  name: Button06
  
  value must be at most 4.
  row: 5 [source /config/esphome/master-bedroom-keypad-marc.yaml:85]
  col: 0
binary_sensor.sx1509: [source /config/esphome/master-bedroom-keypad-marc.yaml:202]
  platform: sx1509
  sx1509_id: sx1509_hub1
  name: Button30
  row: 0
  
  value must be at most 4.
  col: 5 [source /config/esphome/master-bedroom-keypad-marc.yaml:206]
```
