### ISSUE TITLE
Error with iir_filter for bme680

### ISSUE THREAD

**Issue by andreas-bulling** [esphome/issues#31]
Hi,

according to the documentation, the bme680 component should support an iir_filter. But when I configure the following:

```
  - platform: bme680
    temperature:
      name: ${device_upper} Temperature
      id: temperature
      oversampling: 16x
    pressure:
      name: ${device_upper} Pressure
      id: pressure
      oversampling: 16x
    humidity:
      name: ${device_upper} Relative Humidity
      id: humidity
      oversampling: 4x
    gas_resistance:
      name: ${device_upper} Gas Resistance
      id: gas_resistance
    heater:
      temperature: 200
      duration: 100ms
    address: 0x76
    update_interval: 15s
    iir_filter: 4x
```
I see an error when calling `esphomeyaml config`
```
Unknown value '4X', must be one of '127X', '3X', 'OFF', '31X', '15X', '63X', '1X', '7X'. Got '4x'
  iir_filter: 4x
```
I think this is a bug
