### ISSUE TITLE
web api control LED color not working 

### ISSUE THREAD

**Issue by pokebox** [esphome/issues#3101]
### The problem

After configuring the web server, use post to set the LED, the RGB color will not change as expected, the settings will be fixed by the configuration on HomeAssistant.

Use the following command to control the LED ：
`curl -X 'POST' 'http://esp32led/light/neopixel_light/turn_on?brightness=255&r=0&g=0&b=255&white_value=0&effect=None'`
`curl -X 'POST' 'http://esp32led/light/neopixel_light/turn_on?brightness=255&r=66&g=77&b=80&white_value=0&effect=None'`
RGB colors will not be set as expected.The color value will be fixed by the settings of HomeAssistant.

### Which version of ESPHome has the issue?

2022.2.5

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

web server/neopixelbus

### Example YAML snippet

```yaml
esphome:
  name: esp32led

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxxxxxxx"

ota:
  password: "xxxxxxxx"

wifi:
  networks:
  - ssid: "wifi2"
    password: "xxxxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Fallback Hotspot"
    password: "xxxxxxxx"


captive_portal:
web_server:
  port: 80

light:
  - platform: neopixelbus
    type: GRBW
    variant: SK6812
    pin: GPIO23
    num_leds: 144
    name: "NeoPixel Light"
    id: mylight
```
