### ISSUE TITLE
esp32-wroom-32d Unknown connection status after OTA update

### ISSUE THREAD

**Issue by Sangoku** [esphome/issues#3103]
### The problem

I am using a 
https://www.amazon.de/gp/product/B07MBZMYCX/ref=ppx_yo_dt_b_asin_image_o09_s00?ie=UTF8&psc=1
After each OTA update it wont connect to the wifi.

### Which version of ESPHome has the issue?

 2022.2.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

 2022.2.9

### What platform are you using?

ESP32

### Board

ARCELI NO R3 D1 R32 ESP32 ESP-32 340G

### Component causing the issue

Wifi Update

### Example YAML snippet

```yaml
esphome:
  name: pool-control

esp32:
  board: nodemcu-32s #esp32doit-devkit-v1 

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  services:
    - service: control_stepper_x
      variables:
        target: int
      then:
        - stepper.set_target:
            id: x_axis
            target: !lambda 'return target;'
            
            
    - service: control_stepper_y
      variables:
        target: int
      then:
        - stepper.set_target:
            id: y_axis
            target: !lambda 'return target;'
            
            
    - service: control_stepper_z
      variables:
        target: int
      then:
        - stepper.set_target:
            id: z_axis
            target: !lambda 'return target;'
            
            
    - service: control_stepper_a
      variables:
        target: int
      then:
        - stepper.set_target:
            id: a_axis
            target: !lambda 'return target;'


ota:
  password: "xxxxxxx"


wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password
```

### Anything in the logs that might be useful for us?

```txt
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
.
. endless loop
.

[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: WiFi Unknown connection status 0
[W][wifi:557]: �ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
�[I][logger:214]: Log initialized
```

### Additional information

As far i get it this is the last backup log output from 
https://esphome.io/api/wifi__component_8cpp_source.html 
line 557 
That is i all i could find out. No idea why it happens only after update...
Restarts work without problems. 

Tried diferent boards to.. no luck.
