### ISSUE TITLE
ESPHome won't boot and goes into safe mode when using some DS18*20 sensors.

### ISSUE THREAD

**Issue by AlexValery13** [esphome/issues#3107]
### The problem

I have a group of four old DS18B20 sensors. These sensors are over seven years old. All this time they worked under a proprietary device on the ATMega-32. 
These sensors are still operational under the Tasmota firmware. But if I change the firmware to ESPHome for the same ESP-12, then ESPHome does not work. ESPHome does not start the web interface and the API reports:
```
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from sauna-display.local using esphome API
WARNING Can't connect to ESPHome API for sauna-display.local: Timeout while connecting to ('192.168.13.153', 6053)
INFO Trying to reconnect to sauna-display.local in the background
```
If I disconnect "data" DS18B20 from GPIO4, then ESPHome starts up.

If I change
```
dallas:
  - pin: GPIO4
```
to another pin that does NOT have "data" DS18B20 connected to it, then ESPHome starts up.

If I do not change the hardware and change the firmware to Tasmota, then I get readings from all four sensors used.

If I use new sensors then this problem does not occur.

### Which version of ESPHome has the issue?

2022.2.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.2.9

### What platform are you using?

ESP8266

### Board

ESP-12

### Component causing the issue

Dallas

### Example YAML snippet

```yaml
esphome:
  name: test

esp8266:
  board:  esp01_1m

# Enable logging
logger:

# подключение DALLAS
dallas:
  - pin: GPIO4
    update_interval: 10s

# Enable Home Assistant API
api:
  password: !secret api_password
    
ota:
  password: !secret ota_password
    
web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sauna-Display Hotspot"
    password: !secret hotspot_password
    
captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from sauna-display.local using esphome API
WARNING Can't connect to ESPHome API for sauna-display.local: Timeout while connecting to ('192.168.13.153', 6053)
INFO Trying to reconnect to sauna-display.local in the background
```

### Additional information

![tsm](https://user-images.githubusercontent.com/43274291/156403701-847393a8-8b46-4868-bf8e-11dddf7162f1.JPG)
