### ISSUE TITLE
Wrong flash size during compilation

### ISSUE THREAD

**Issue by leodrivera** [esphome/issues#3110]
### The problem

Although it describes the correct size of the flash memory during the beginning of compilation (4 MB), at the end it says the flash has only 1 MB: 
`(Flash: [====      ]  43.3% (used 452773 bytes from 1044464 bytes)`

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.0

### What platform are you using?

ESP8266

### Board

ESP12-E

### Example YAML snippet

```yaml
esphome:
  name: leo-room-fan
  platform: ESP8266
  board: esp12e

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_fallback_password

captive_portal:

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/leo-room-fan.yaml...
INFO Detected timezone 'America/Sao_Paulo'
INFO Generating C++ source...
INFO Compiling app...
Processing leo-room-fan (board: esp12e; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
Compiling /data/leo-room-fan/.pioenvs/leo-room-fan/src/main.cpp.o
Linking /data/leo-room-fan/.pioenvs/leo-room-fan/firmware.elf
RAM:   [====      ]  41.7% (used 34188 bytes from 81920 bytes)
Flash: [====      ]  43.3% (used 452773 bytes from 1044464 bytes)
Building /data/leo-room-fan/.pioenvs/leo-room-fan/firmware.bin
```

**Comment by OttoWinter** [comment]
The reason it says 1MB is that platformio uses the [`eagle.flash.4m1m.ld`](https://github.com/platformio/platform-espressif8266/blob/master/boards/esp12e.json#L4) linker script for this board type (`esp12e`). First, it's good to cap it at 1/2 the flash size to allow OTA uploads (the updated binary is written past the end of the esp's storage, and then copied over on next boot). Next the additional storage is used for extra files (like SPIFFS storage), because it's quite uncommon to put so much code that is would exceed 1MB (that's only code, not additional files). If you do need the additional storage, you can make platformio choose another ld script:

```yaml
esphome:
  platformio_options:
    board_build.ldscript: eagle.flash.4m.ld
```

(https://docs.platformio.org/en/latest/platforms/espressif8266.html#flash-size) But that's only intended for advanced users (i.e. when developing custom code) as seen with the ugly syntax, because i don't think you can hit that limit with esphome code alone.
