### ISSUE TITLE
empty {} topic config json in mqtt discovery 

### ISSUE THREAD

**Issue by twocolors** [esphome/issues#3112]
### The problem

send empty {} json in config topic, all work fine in 2022.2.5
this bug is replay all board esp32

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
substitutions:
  device_name: livingroom-ac

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living Room Ac Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  level: WARN
  # level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
# api:

ota:
  password: !secret ota_password

web_server:

esp32_ble_tracker:
#  scan_parameters:
#    window: 120ms

mqtt:
  broker: !secret mqtt_host
  topic_prefix: esphome/${device_name}

text_sensor:
  - platform: version
    name: "Version"
  
  - platform: wifi_info
    ip_address:
      name: "Address"

  - platform: template
    id: uptime_human
    name: "Uptime"
```

**Comment by jerobins** [comment]
2022.2.6 and 2022.2.7 broke mqtt json publish - json published payload is empty '{}'.  Downgrade to 2022.2.5 resolves.

**Comment by basschipper** [comment]
I have the same issue, same platform, same board. Downgrade fixed this for now.

**Comment by isorin** [comment]
The problem exists in 2022.2.5 (and before) for multiple sensors coming from the BLE tracker.
It happens if the sensor doesn't publish data for some time after boot (or at least this seems to be the case).

**Comment by jesserockz** [comment]
I have just tried to reproduce this and can confirm it happens when `esp32_ble_tracker` is enabled (it is fine without it so maybe the tracker is using too much memory for the json to be built). I am investigating further

**Comment by isorin** [comment]
That's great, thanks!
Due to the way it behaves I am leaning more towards a race condition / clash of resources when preparing or publishing the mqtt json but I'm not familiar with the code so it is just a wild guess.

**Comment by jesserockz** [comment]
@isorin Please try out esphome/esphome#3289

```yaml
external_components:
  - source: github://pr#3289
    components: ["json"]
```
