### ISSUE TITLE
ESP32-S2 RTC GPIO Pins not supported

### ISSUE THREAD

**Issue by andrewpc** [esphome/issues#3116]
### The problem

Deep sleep component validates RTC wakeup pins for ESP 32 in config schema:

`valid_pins = [0, 2, 4, 12, 13, 14, 15, 25, 26, 27, 32, 33, 34, 35, 36, 37, 38, 39]`

These are correct for ESP32, however the S2 variant has a different set of pins which are defined here:

https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/gpio.html

Tested locally by adding pin 21 to my configured external deep_sleep component which wakes my TinyS2, although looking at the component code, there are lots of checks for ESP32, which Im not sure also apply to the S2, so it may need reworking there a bit too.

Thanks

### Which version of ESPHome has the issue?

2022.2.5 

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

TinyS2

### Component causing the issue

deep-sleep

### Example YAML snippet

```yaml
deep_sleep:
  run_duration: 180s
  sleep_duration: 120min
  wakeup_pin: 21
  wakeup_pin_mode: KEEP_AWAKE
```
