### ISSUE TITLE
state_class: total not valid

### ISSUE THREAD

**Issue by TyzzyT** [esphome/issues#3118]
### The problem

According to the [ESPHome docs](https://esphome.io/components/sensor/index.html), we can use all available options from the [Home Assistant state classes](https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes).
But when I try to use the state class _total_ I get an error: `Unknown value 'total', valid options are '', 'measurement', 'total_increasing'.`

I believe this is a bug, as the state class _total_ is valid for HA.

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.1

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

template

### Example YAML snippet

```yaml
- platform: template
    id: water_daily_consumption
    name: "${friendly_name} daily water consumption"
    unit_of_measurement: "L"
    accuracy_decimals: 0
    icon: "mdi:water"
    state_class: total
```

### Anything in the logs that might be useful for us?

```txt
Failed config

sensor.template: [source /config/esphome/wemos-d1mini-watermeter.yaml:325]
  platform: template
  id: water_daily_consumption
  name: Wemos watermeter daily water consumption
  unit_of_measurement: L
  accuracy_decimals: 0
  icon: mdi:water
  
  Unknown value 'total', valid options are '', 'measurement', 'total_increasing'.
  state_class: total [source /config/esphome/wemos-d1mini-watermeter.yaml:331]
```
