### ISSUE TITLE
Homeassistant ESPHome integration always resolves empty

### ISSUE THREAD

**Issue by yeralin** [esphome/issues#312]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Raspbian GNU/Linux 9 (stretch)
(Raspberry Pi 3B)

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 (NODEMCUV2 by espressif)

**Affected component:**
Homeassistant Integration
API (https://esphome.io/components/api.html)

**Description of problem:**
I made a simple pet feeder ran by ESP8266 hooked with servo. Everything appears to be working fine. I initially integrated it with Homeassistant (ran on my raspberry pi) successfully, and I'd been using it just fine for about a month. Then, I added a new sensor to my pet feeder to show on Homeassistant dashboard. Uploaded it via Wi-Fi on my board, but it did not appear on Homeassistant's dashboard, so I deleted the integration, and re-added it back again. However, when I tried to add the integration back, it found my ESP8266, but does not resolve any exposed metrics (sensors) and api calls:
![image](https://user-images.githubusercontent.com/8620461/57705003-0328ee80-7631-11e9-81ca-a7da35b22392.png)
As you can see, it found my smart_pet_feeder, but did not resolve any api "endpoints" from it. At first I thought it is a metadata issue, something got cached in FS/DB, and I just need to clean up homeassistant configurations folder. Tried to find anything that's related to esphome/smart_pet_feeder using grep, deleted those files, and restarted Homeassistant. The issue persisted. Then, I reinstalled my homeassistant by deleting previous virtualenv, creating a new one, and install homeassistant using pip. After successful reinstallation, I tried to integrated smart_pet_feeder, but once again it resolved empty. Then, I backed up and deleted homeassistant's configurations directory, reinstalled homeassistant, and started all fresh. **And still when I tried to do integration for my feeder, it resolved empty**
Next step, I pulled a homeassistant docker image on my laptop:
`docker run -p 8123:8123 homeassistant/home-assistant`, waited for it to fully initialize, went to the main page, tried to integrate my smart_pet_feeder with this fresh instance, and **it worked!**
![image](https://user-images.githubusercontent.com/8620461/57703981-163abf00-762f-11e9-9e24-b0c1e61d945b.png)

I believe that some metadata is persisted outside of virtualenv environment, and outside of `~/.homeassistant` configuration's directory that prevents me to successfully re-integrate my esphome instance with my homeassistant. Or maybe there is some deeper issue.

**Problem-relevant YAML-configuration entries:**
```yaml
...
api:
  services:
    # Update weight and time period of the feeder
    - service: change_target_weight
      variables:
        new_target_weight: int
      then:
        - lambda: |-
            id(target_weight) = new_target_weight;
    - service: change_feed_interval
      variables:
        new_feed_interval: int
      then:
        - lambda: |-
            id(feeder_interval) = new_feed_interval;
...
```
The yml file is quite large, you can access it here: https://github.com/yeralin/IoT/blob/master/applications/smart-feeder/smart-feeder.yml

**Traceback (if applicable):**
Does not apply

**Additional information and things you've tried:**
If you look at the yml file I posted, you might notice that my feeders name is actually `smart_feeder` that resolved to `smart_feeder.local`. I also thought that maybe the name got cached somewhere, so I renamed it to `smart_pet_feeder`, but that did not help as well.
