### ISSUE TITLE
heltec_wifi_kit_32_v2 WiFi Connection Issues

### ISSUE THREAD

**Issue by thefjordkeeper** [esphome/issues#3120]
### The problem

This board constantly has WiFi 4way handshake issues. It will connect to my 2.4Ghz network in 1 in 10 attempts. I'm using an older Netgear R6700v3. I also tried my neighbor's network, he has more advanced UniFi Access Point WiFi 6 Pros and had the same results.

I have attempted every WiFi configuration and trick in an attempt to track down the issue. This board is rock solid running Tasmota and Arduino sketches.

If a USA-based dev would like me to donate this Heltec for R&D, I would be happy to do so.

### Which version of ESPHome has the issue?

v2022.2.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.0

### What platform are you using?

ESP32

### Board

heltec_wifi_kit_32_v2

### Component causing the issue

wifi

### Example YAML snippet

```yaml
esphome:
  name: water-heater-power-monitor

esp32:
  board: heltec_wifi_kit_32_v2
  framework:
    type: arduino

# Enable logging
logger:
 level: verbose

# Enable Home Assistant API
api:

ota:
  password: "47d6e963b2d7675822e15167d3bde4bf"

web_server:
 port: 80

wifi:
  power_save_mode: none
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  
  manual_ip:
    static_ip: 192.168.1.100
    gateway: 192.168.1.1
    subnet: 255.255.255.0
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails

sensor:
  - platform: pulse_meter
    name: 'Water Heater - Power Consumption'
    id: sensor_energy_pulse_meter
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: 35
    # internal_filter: 100ms

text_sensor:
  - platform: wifi_info
    ip_address:
      id: IP
    ssid:
      id: SSID

font:
  - file: "fonts/Roboto-Regular.ttf"
    id: font1
    size: 12
  - file: "fonts/Roboto-Regular.ttf"
    id: font2
    size: 8

i2c:
  sda: 4
  scl: 15
  frequency: 800kHz

display:
  platform: ssd1306_i2c
  model: "SSD1306 128x64"
  reset_pin: 16
  address: 0x3C
  lambda: |-
   it.print( 64,0, (font1), TextAlign::TOP_CENTER, "Power Monitor");
   it.printf( 11,50, (font2), "IP: %s", id(IP).state.c_str());
   it.printf( 90,50, (font2), "SSID: %s", id(SSID).state.c_str());
```

### Anything in the logs that might be useful for us?

```txt
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:214]: Log initialized
[C][ota:461]: There have been 1 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving preferences to flash...
[I][app:029]: Running through setup()...
[V][app:030]: Sorting components by setup priority...
[I][i2c.arduino:161]: Performing I2C bus recovery
[V][i2c.arduino:033]: Scanning i2c bus for active devices...
[C][ssd1306_i2c:010]: Setting up I2C SSD1306...
[C][wifi:037]: Setting up WiFi...
[V][esp32.preferences:057]: nvs_get_blob('20045679'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[V][wifi_esp32:039]: Enabling STA.
[V][esp-idf:000]: I (349) wifi:
[V][esp-idf:000]: wifi driver task: 3ffaf548, prio:23, stack:3584, core=0
[V][esp-idf:000]: 

[V][esp-idf:000]: I (933) wifi:
[V][esp-idf:000]: wifi firmware version: dc30037
[V][esp-idf:000]: 

[V][esp-idf:000]: I (935) wifi:
[V][esp-idf:000]: config NVS flash: enabled
[V][esp-idf:000]: 

[V][esp-idf:000]: I (946) wifi:
[V][esp-idf:000]: config nano formating: disabled
[V][esp-idf:000]: 

[V][esp-idf:000]: I (958) wifi:
[V][esp-idf:000]: Init data frame dynamic rx buffer num: 32
[V][esp-idf:000]: 

[V][esp-idf:000]: I (971) wifi:
[V][esp-idf:000]: Init management frame dynamic rx buffer num: 32
[V][esp-idf:000]: 

[V][esp-idf:000]: I (984) wifi:
[V][esp-idf:000]: Init management short buffer num: 32
[V][esp-idf:000]: 

[V][esp-idf:000]: I (997) wifi:
[V][esp-idf:000]: Init dynamic tx buffer num: 32
[V][esp-idf:000]: 

[V][esp-idf:000]: I (1009) wifi:
[V][esp-idf:000]: Init static rx buffer size: 1600
[V][esp-idf:000]: 

[V][esp-idf:000]: I (1021) wifi:
[V][esp-idf:000]: Init static rx buffer num: 16
[V][esp-idf:000]: 

[V][esp-idf:000]: I (1033) wifi:
[V][esp-idf:000]: Init dynamic rx buffer num: 32
[V][esp-idf:000]: 

[V][esp-idf:000]: I (1148) wifi:
[V][esp-idf:000]: mode : sta (30:c6:f7:14:32:5c)
[V][esp-idf:000]: 

[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 0 - WIFI_READY
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 2 - STA_START
[V][wifi_esp32:460]: Event: WiFi STA start
[V][wifi_esp32:445]: Event: WiFi ready
[V][esp-idf:000]: I (1180) wifi:
[V][esp-idf:000]: Set ps type: 0

[V][esp-idf:000]: 

[D][wifi:373]: Starting scan...
[V][component:199]: Component ssd1306_base took a long time for an operation (0.22 s).
[V][component:200]: Components should block for at most 20-30ms.
[V][sensor:074]: 'Water Heater - Power Consumption': Received new state 0.000000
[D][sensor:125]: 'Water Heater - Power Consumption': Sending state 0.00000 W with 0 decimals of accuracy
[V][component:199]: Component ssd1306_base took a long time for an operation (0.22 s).
[V][component:200]: Components should block for at most 20-30ms.
[V][component:199]: Component ssd1306_base took a long time for an operation (0.22 s).
[V][component:200]: Components should block for at most 20-30ms.
[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 1 - SCAN_DONE
[V][wifi_esp32:454]: Event: WiFi Scan Done status=0 number=6 scan_id=128
[D][wifi:388]: Found networks:
[I][wifi:432]: - 'xxxx' (xxxxxxxx) [redacted]▂▄▆█
[D][wifi:433]:     Channel: 7
[D][wifi:434]:     RSSI: -48 dB

[I][wifi:248]: WiFi Connecting to 'xxxx'...
[V][wifi:250]: Connection Params:
[V][wifi:251]:   SSID: 'xxxx'
[V][wifi:254]:   BSSID: x
[V][wifi:274]:   Password: 'zzzzzz'[redacted]
[V][wifi:279]:   Channel: 7
[V][wifi:286]:   Manual IP: Static IP=192.168.1.100 Gateway=192.168.1.1 Subnet=255.255.255.0 DNS1=0.0.0.0 DNS2=0.0.0.0
[V][wifi:290]:   Hidden: NO
[V][esp-idf:000]: I (3441) wifi:
[V][esp-idf:000]: new:<7,2>, old:<1,0>, ap:<255,255>, sta:<7,2>, prof:1
[V][esp-idf:000]: 

[V][esp-idf:000]: I (4185) wifi:
[V][esp-idf:000]: state: init -> auth (b0)
[V][esp-idf:000]: 

[V][esp-idf:000]: I (4204) wifi:
[V][esp-idf:000]: state: auth -> assoc (0)
[V][esp-idf:000]: 

[V][esp-idf:000]: I (4220) wifi:
[V][esp-idf:000]: state: assoc -> run (10)
[V][esp-idf:000]: 

[V][component:199]: Component ssd1306_base took a long time for an operation (0.59 s).
[V][component:200]: Components should block for at most 20-30ms.
[V][component:199]: Component ssd1306_base took a long time for an operation (0.22 s).
[V][component:200]: Components should block for at most 20-30ms.
[V][component:199]: Component ssd1306_base took a long time for an operation (0.22 s).
[V][component:200]: Components should block for at most 20-30ms.
[V][component:199]: Component ssd1306_base took a long time for an operation (0.22 s).
[V][component:200]: Components should block for at most 20-30ms.
[V][esp-idf:000]: I (7316) wifi:
[V][esp-idf:000]: state: run -> init (fc0)
[V][esp-idf:000]: 

[V][esp-idf:000]: I (7317) wifi:
[V][esp-idf:000]: new:<7,0>, old:<7,2>, ap:<255,255>, sta:<7,2>, prof:1
[V][esp-idf:000]: 

[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 5 - STA_DISCONNECTED
[W][WiFiGeneric.cpp:391] _eventCallback(): Reason: 15 - 4WAY_HANDSHAKE_TIMEOUT
[W][wifi_esp32:495]: Event: Disconnected ssid='xxxx' bssid=xxxx[redacted] reason='4-Way Handshake Timeout'
[W][wifi:557]: WiFi Unknown connection status 0
```

### Additional information

Also, I have attempted to use this board with YAML that only contains wifi info, on both DHCP and manual IP, with the same outcome.

**Comment by gazoodle** [comment]
I have exactly the same error, but only when plugged into a breadboard. If I remove the Heltec board from the breadboard then it connects to WiFi just fine. This https://github.com/espressif/arduino-esp32/issues/3381 recommends changing the output power to 2db which isn't possible with ESPHome, but I did manage to get mine to work when in the breadboard using 10db.
```yaml
wifi: 
  manual_ip: 
    dns1: x.x.x.x
    gateway: x.x.x.x
    static_ip: x.x.x.x
    subnet: x.x.x.x
  password: !secret wifi_PWD
  ssid: !secret wifi_SSID
  output_power: 10
```
