### ISSUE TITLE
Unable to set Tuya Number in on_boot action

### ISSUE THREAD

**Issue by david-collett** [esphome/issues#3121]
### The problem

Hi,
I have a security sensor light which is a tuyamcu device. It has a number of configurable parameters which I have mapped to Tuya Numbers, for example:

```
number:
  - platform: tuya
    id: light_duration
    name: "Light Duration"
    number_datapoint: 104
    unit_of_measurement: "Seconds"
    min_value: 0
    max_value: 3600
    step: 1
```

This works great, but if power is cycled, the values revert to their defaults, so I need a way for esphome to restore them. I figure I could do this with globals that are saved/restored to eeprom and sent back to the tuyamcu on boot. However, as a simple test, even setting a new static default does not work. For example:

```
esphome:
  on_boot:
    priority: -100
    then:
      - number.set:
          id: light_duration
          value: 30
```

This does not work, and after a power cycle, the value is back to 10 (its default).

Is this expected behavior?
Is there another way I can save/restore Tuya Number values across power cycles.

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.2

### What platform are you using?

ESP8266

### Board

ESP-12

### Component causing the issue

tuya

### Example YAML snippet

```yaml
esphome:
  on_boot:
    priority: -100
    then:
      - number.set:
          id: light_duration
          value: 30

number:
  - platform: tuya
    id: light_duration
    name: "Light Duration"
    number_datapoint: 104
    unit_of_measurement: "Seconds"
    min_value: 0
    max_value: 3600
    step: 1
```

**Comment by david-collett** [comment]
Further to the above, I have just discovered that if I put a delay action above the number.set, it works.
For example:

```
esphome:
  on_boot:
    priority: -100
    then:
      - delay: 20s
      - number.set:
          id: light_duration
          value: 30
```

So I expect this is related to startup sequence and may be inadvertent. It would be nice if this worked intuitively, but there may be a reason why its not possible.  I don't know how many tuyamcu devices there are like this that have configuration variables that make sense to be persisted, but if its common, it would be cool to add it to Tuya Number itself, much like "restore_value" in template number.

Thanks
