### ISSUE TITLE
ESP32-Camera throwing authentication errors

### ISSUE THREAD

**Issue by Benchmaker** [esphome/issues#3122]
### The problem

When the Camera is in an "Unavailable" state in my Dashboard and clicked on, it prompts a logon alert stating that a login attempt was made from my device with invalid authentication.

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.1

### What platform are you using?

ESP32

### Board

ESP32

### Component causing the issue

Camera

### Example YAML snippet

```yaml
web_server:
  port: 80

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: Stove Camera

switch:
  - platform: gpio
    pin: 4
    name: "Camera LED"
```

### Additional information

![image](https://user-images.githubusercontent.com/11370930/157311873-9392390e-c6c3-4789-9315-249aef4f0195.png)
