### ISSUE TITLE
pcf8574 P0 ~ P4 cannot be controlled independently，But it can be controlled under special arrangement and combination

### ISSUE THREAD

**Issue by 1259197760** [esphome/issues#3124]
### The problem

The output of pcf8574p is pulled up through 10K resistor into ULN2803 to control the relay. The current problem is that P0 ~ P4 cannot be controlled independently, P5 ~ P7 is normal, and the problem of the circuit itself has been eliminated. P0 ~ P4 can control the output state when some pins need to output high level or low level
![1246](https://user-images.githubusercontent.com/80514476/157390797-6ccda88d-894b-490f-91aa-2b5136bef7f0.JPG)

For example, P1 ~ P3 can be controlled in the state shown above

### Which version of ESPHome has the issue?

Current version: 1.20.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.12.10

### What platform are you using?

ESP32

### Board

Goouuu-ESP32（ESP-WROOM-32）

### Component causing the issue

i2c

### Example YAML snippet

```yaml
esphome:
  name: esp32
  platform: ESP32
  board: nodemcu-32s
# Enable logging
logger:
# Example configuration entry

# Enable Home Assistant API
api:
ota:
  password: "17aeb76324ee4ac1af51b5e821063fc2"

wifi:
  ssid: "root"
  password: "13254751f"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Fallback Hotspot"
    password: "ojRSMHXIDY7l"

captive_portal:

i2c:
   - id: bus_a
     sda: GPIO21
     scl: GPIO22
     scan: true

spi:
   - id: bus_b
     clk_pin: GPIO18
     mosi_pin: GPIO23
     miso_pin: GPIO19


   - id: bus_c
     clk_pin: GPIO14
     mosi_pin: GPIO13
     miso_pin: GPIO12

uart:
   - id: bus_d
     tx_pin: GPIO1
     rx_pin: GPIO3
     baud_rate: 9600

   - id: bus_e
     tx_pin: GPIO17
     rx_pin: GPIO16
     baud_rate: 115200

sensor:
  - platform: homeassistant
    id: dht_temp
    entity_id: sensor.esp_cellar_temperature
    internal: true

  - platform: homeassistant
    id: dht_hum
    entity_id: sensor.esp_cellar_humidity
    internal: true


  - platform: dht
    pin: GPIO33
    temperature:
      name: "esp-cellar-temperature"
      id: dht_temp1
      accuracy_decimals: 1
      force_update: yes
    humidity:
      name: "esp-cellar-humidity"
      id: dht_hum1
      accuracy_decimals: 1
      force_update: yes
    update_interval: 30s
    model: DHT11

  - platform: wifi_signal
    name: "WiFi"
    update_interval: 60s
    id: wi_fi

time:
  - platform: homeassistant
    id: esptime
font:
  - file: 'BebasNeue-Regular.ttf'
    id: font1
    size: 28

  - file: 'BebasNeue-Regular.ttf'
    id: font2
    size: 48

  - file: 'arial.ttf'
    id: font3
    size: 25

image:
  - file: "h.png"
    id: my_image
    resize: 240x320
    type: rgb24
  
  - file: "1.png"
    id: my_image1
    resize: 55x55
    type: GRAYSCALE

  - file: "2.png"
    id: my_image2
    resize: 55x55
    type: GRAYSCALE

  - file: "3.png"
    id: my_image3
    resize: 55x55
    type: GRAYSCALE

  - file: "4.png"
    id: my_image4
    resize: 55x55
    type: GRAYSCALE

  - file: "x.png"
    id: my_image5
    resize: 240x320
    type: GRAYSCALE
  - file: "n.png"
    id: my_image6
    resize: 240x320
    type: GRAYSCALE
  - file: "kl.png"
    id: my_image7
    resize: 240x320
    type: GRAYSCALE
color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%

display:
  - platform: ili9341
    spi_id: bus_b
    model: TFT 2.4
    cs_pin: GPIO5
    dc_pin: GPIO2
    led_pin: GPIO32
    reset_pin: GPIO4
    update_interval: 2s
    lambda: |-
      it.image(0, 0, id(my_image));

      it.image(63, 150, id(my_image1));
      
      it.image(123, 150, id(my_image2));
      
      it.image(182, 150, id(my_image3));
      
      it.image(4, 150, id(my_image4));
      
      
      it.strftime(-4, 48, id(font2), TextAlign::BASELINE_LEFT, "%H:%M:%S", id(esptime).now());
      
      it.strftime(1, 90, id(font2), TextAlign::BASELINE_LEFT, "%Y-%m-%d", id(esptime).now());

      if (id(dht_temp).has_state()) {
        it.printf(224, 1, id(font3), TextAlign::TOP_RIGHT , "%.1f°C", id(dht_temp1).state);
       }

       if (id(dht_hum).has_state()) {
         it.printf(220, 45, id(font3), TextAlign::BASELINE_RIGHT , "%.1f°", id(dht_hum1).state);
      }

      it.printf(237, 48, id(font3), TextAlign::TOP_RIGHT , "%.1f", id(wi_fi).state);
      it.print(196, 68, id(font3), "db");

      it.line(0, 1, 240, 1);
      it.line(135, 1, 135, 51);
      it.line(0, 51, 240, 51);
      it.line(175, 51, 175, 95);
      it.line(0, 95, 240, 95);
      it.line(0, 145, 240, 145);
      it.line(120, 95, 120, 117);
      it.line(120, 117, 240, 117);
      it.line(0, 209, 240, 209);

xpt2046:
  id: touchscreen
  spi_id: bus_c
  cs_pin: GPIO15
  irq_pin: GPIO27
  update_interval: 50ms
  report_interval: 1s
  threshold: 400
  dimension_x: 240
  dimension_y: 320
  calibration_x_min: 3860
  calibration_x_max: 280
  calibration_y_min: 340
  calibration_y_max: 3860
  swap_x_y: false

output:
  - platform: ledc
    pin: GPIO32
    id: gpio_32_backlight_pwm

  - platform: ledc
    pin: GPIO25
    id: gpio_25
light:
  - platform: monochromatic
    output: gpio_25
    name: "Kitchen Light"

  - platform: monochromatic
    output: gpio_32_backlight_pwm
    name: "ILI9341 Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: false

switch:
  - platform: gpio
    name: "PCF8574 Pin #0"
    pin:
      pcf8574: pcf8574_hub
      number: 0
      mode: output
      inverted: false
  - platform: gpio
    name: "PCF8574 Pin #1"
    pin:
      pcf8574: pcf8574_hub
      number: 1
      mode: output
      inverted: false

  - platform: gpio
    name: "PCF8574 Pin #2"
    pin:
      pcf8574: pcf8574_hub
      number: 2
      mode: output
      inverted: false

  - platform: gpio
    name: "PCF8574 Pin #3"
    pin:
      pcf8574: pcf8574_hub
      number: 3
      mode: output
      inverted: false

  - platform: gpio
    name: "PCF8574 Pin #4"
    pin:
      pcf8574: pcf8574_hub
      number: 4
      mode: output
      inverted: false

  - platform: gpio
    name: "PCF8574 Pin #5"
    pin:
      pcf8574: pcf8574_hub
      number: 5
      mode: output
      inverted: false
  - platform: gpio
    name: "PCF8574 Pin #6"
    pin:
      pcf8574: pcf8574_hub
      number: 6
      mode: output
      inverted: false
  - platform: gpio
    name: "PCF8574 Pin #7"
    pin:
      pcf8574: pcf8574_hub
      number: 7
      mode: output
      inverted: false
```
