### ISSUE TITLE
Can't compile:  Failed to resolve component 'cxx'.

### ISSUE THREAD

**Issue by nicari92** [esphome/issues#3126]
### The problem

I'm trying to run a test yaml for my ESP32-C3 board via command line, but I'm having A LOT of problems.
The one I can't solve is this:

`fatal: not a git repository (or any of the parent directories): .git
CMake Error at C:/Users/stefa/.platformio/packages/framework-espidf/tools/cmake/build.cmake:191 (message):
  Failed to resolve component 'cxx'.`

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

ESP32-C3-DevKitC-02

### Component causing the issue

cmake

### Example YAML snippet

```yaml
esphome:
  name: esp32-c3

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: dev
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false
  variant: ESP32C3

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "..."

wifi:
  ssid: "..."
  password: "..."

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C3 Fallback Hotspot"
    password: "..."
```

### Anything in the logs that might be useful for us?

```txt
C:\Users\stefa\AppData\Local\Programs\Python\Python310\Scripts>esphome run test.yaml
←[32mINFO Reading configuration test.yaml...←[0m
←[33mWARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.←[0m
←[33mWARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.←[0m
←[32mINFO Generating C++ source...←[0m
←[32mINFO Compiling app...←[0m
Processing esp32-c3 (board: esp32-c3-devkitm-1; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-c3-devkitm-1.html
PLATFORM: Espressif 32 (3.5.0) > Espressif ESP32-C3-DevKitM-1
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-espidf 1.1.0+sha.cc98ce3
 - tool-cmake 3.16.4
 - tool-esptoolpy 1.30100.210531 (3.1.0)
 - tool-idf 1.0.1
 - tool-mconf 1.4060000.20190628 (406.0.0)
 - tool-ninja 1.9.0
 - toolchain-riscv32-esp 8.4.0+2021r2-patch2
 - toolchain-xtensa-esp32s2 8.4.0+2021r2-patch2
Reading CMake configuration...
-- Building ESP-IDF components for target esp32c3
-- Configuring incomplete, errors occurred!
See also "C:/Users/stefa/AppData/Local/Programs/Python/Python310/Scripts/.esphome/build/esp32-c3/.pioenvs/esp32-c3/CMakeFiles/CMakeOutput.log".
See also "C:/Users/stefa/AppData/Local/Programs/Python/Python310/Scripts/.esphome/build/esp32-c3/.pioenvs/esp32-c3/CMakeFiles/CMakeError.log".

fatal: not a git repository (or any of the parent directories): .git
CMake Error at C:/Users/stefa/.platformio/packages/framework-espidf/tools/cmake/build.cmake:191 (message):
  Failed to resolve component 'cxx'.
Call Stack (most recent call first):
  C:/Users/stefa/.platformio/packages/framework-espidf/tools/cmake/build.cmake:217 (__build_resolve_and_add_req)
  C:/Users/stefa/.platformio/packages/framework-espidf/tools/cmake/build.cmake:441 (__build_expand_requirements)
  C:/Users/stefa/.platformio/packages/framework-espidf/tools/cmake/project.cmake:399 (idf_build_process)
  CMakeLists.txt:3 (project)
```

### Additional information

Windows env variable: CXX=C:\MinGW\bin
