### ISSUE TITLE
ESP8266 - Multiple 'esp8266_pwm' causes Boot loop

### ISSUE THREAD

**Issue by 3ative** [esphome/issues#3145]
### The problem

I have 6 LED Lights (_- platform: monochromatic_) connected to **outputs** via - platform: esp8266_pwm.
when more than 4 are used the ESP chip goes in to boot loop and all lights flicker on, for a few seconds, go off and this repeats - I guess due to Boot loop.

### Which version of ESPHome has the issue?

2022.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.5

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

Either: light: (platform: monochromatic) or output: (platform: esp8266_pwm)

### Example YAML snippet

```yaml
light:
  - platform: monochromatic
    name: "${name} Candle 1"
    id: candle_1
    output: candle_1_pwm
...
  - platform: monochromatic
    name: "Candles ${name} 6"
    id: candle_6
    output: candle_6_pwm

output:
  - platform: esp8266_pwm
    id: candle_1_pwm
    pin: D1
  - platform: esp8266_pwm
    id: candle_2_pwm
    pin: D2
  - platform: esp8266_pwm
    id: candle_3_pwm
    pin: D3
  - platform: esp8266_pwm
    id: candle_4_pwm
    pin: D5
  - platform: esp8266_pwm
    id: candle_5_pwm
    pin: D6
  - platform: esp8266_pwm
    id: candle_6_pwm
    pin: D7
```
Full code can be seen here: https://github.com/3ative/Smart-Candles/blob/master/Code%20ESPHome.yaml

### Anything in the logs that might be useful for us?

```txt
Couldn't get a log wireless (Boot loop prevented it) However, Termite shows the following - FYI, this repeats:

41: 
 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 3460, room 16 
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4 
tail 4
chksum 0xc9
csum 0xc9
v0005ecb0
~ld
[1B][0;32m[I][logger:214]: Log initialized[1B][0m
[1B][0;35m[C][ota:461]: There have been 2 suspected unsuccessful boot attempts.[1B][0m
[1B][0;32m[I][app:029]: Running through setup()...[1B][0m
[1B][0;35m[C][esp8266_pwm:017]: Setting up ESP8266 PWM Output...[1B][0m
[1B][0;35m[C][esp8266_pwm:017]: Setting up ESP8266 PWM Output...[1B][0m
[1B][0;35m[C][esp8266_pwm:017]: Setting up ESP8266 PWM Output...[1B][0m
[1B][0;35m[C][esp8266_pwm:017]: Setting up ESP8266 PWM Output...[1B][0m
[1B][0;35m[C][esp8266_pwm:017]: Setting up ESP8266 PWM Output...[1B][0m
[1B][0;35m[C][esp8266_pwm:017]: Setting up ESP8266 PWM Output...[1B][0m
```

### Additional information

Everything has worked up to (and including) ESPHome V2022.2.6
