### ISSUE TITLE
Not found the Dallas sensors after uprade to ESPHOME v2022.3

### ISSUE THREAD

**Issue by itanczos** [esphome/issues#3153]
### The problem

Not available the Dallas sensors after uprade to ESPHOME v2022.3

### Which version of ESPHome has the issue?

2022.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.5

### What platform are you using?

ESP8266

### Board

sonoff basic

### Component causing the issue

dallas

### Example YAML snippet

```yaml
esphome:
  name: sonoffkazan
  platform: ESP8266
  board: sonoff_basic
  
# Enable logging
logger:
  hardware_uart: UART1
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false
  
# Enable Home Assistant API
api:

ota:
  password: "xxxxxx"

wifi:
  networks:
    - ssid: "xxxxxxx"
      password: "yyyyyyyyyyyyyyyy"
    - ssid: "zzzzzzzz"
      password: "aaaaaaaaaaaaaaa"
  domain: '.lan'
#  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoffkazan Fallback Hotspot"
    password: "asasasas"

# Sets time from Homeassistant
time:
  - platform: homeassistant
    id: homeassistant_time

captive_portal:

#web_server:
#  port: 80
#  auth:
#    username: user
#    password: password

dallas:
  pin: GPIO14
  update_interval: 30s

sensor:
  - platform: dallas
    address: 0x840118xxxxxxx
    name: "Pince hőmérséklete"
    
  - platform: dallas
    address: 0xE7012xxxxxxxx
    name: "Fűtési kör elmenő"

  - platform: dallas
    address: 0x4D01xxxxxxxxx
    name: "Fűtési kör visszatérő"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Kazán gomb"
    on_press:
      - switch.toggle: relay_1

  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "Fűtés kapcsoló"
    device_class: heat
    on_press:
      then:
        - switch.turn_on: relay_1
    on_release:
      then:
        - delay: 5min
        - switch.turn_off: relay_1
    filters:
      - delayed_on_off: 1000ms

  - platform: status
    name: Kazán relé státusz

switch:
  - platform: gpio
    pin: GPIO12
    id: relay_1
    name: "Kazán relé"
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

button:
  - platform: restart
    name: "Kazán Restart"
    
light:
- platform: status_led
  pin: 
    number: GPIO13
    inverted: true
  internal: true
#  name: "LED"
  id: "led"
```

### Anything in the logs that might be useful for us?

```txt
[03:29:41][C][dallas.sensor:076]:   Pin: GPIO14
[03:29:41][C][dallas.sensor:077]:   Update Interval: 30.0s
[03:29:41][W][dallas.sensor:080]:   Found no sensors!
```

### Additional information

Works with version 2022.2.6.
