### ISSUE TITLE
NodeMCU with BME680 (BSEC) and Motion sensor: Can't connect to ESPHome API for 192.168.28.142

### ISSUE THREAD

**Issue by johannwilken** [esphome/issues#3154]
### The problem

Good day,

I have a NodeMCU with BME680 (BSEC) and Motion sensor. I moved over to the New Esphome addon and since then i receive  "Can't connect to ESPHome API for 192.168.28.142" errors after updates (wirelessly), power outages and sometimes at random times. Then I have to delete device from esphome and reflash via cable (esp8266flasher). I have another exactly the same board with a DHT22 and a motion sensor and is working 100%. I just updated to the latest version (2022.3.0) and again receiving the same error: 

WARNING Can't connect to ESPHome API for 192.168.28.142: Error connecting to ('192.168.28.142', 6053): [Errno 111] Connect call failed ('192.168.28.142', 6053)

Device is connected to wifi and ping-able and ESPHome shows device online:

![mb1](https://user-images.githubusercontent.com/65971874/159014110-ce312b21-dda1-411c-81ad-05339c8fcda6.PNG)

![mb2](https://user-images.githubusercontent.com/65971874/159014156-76dbf83c-b391-4cd5-8531-7cfa01a34126.PNG)

Is there something wrong in my code or is it hardware related?

Please advise

### Which version of ESPHome has the issue?

2022.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3

### What platform are you using?

ESP8266

### Board

NodeMCU v2

### Component causing the issue

api

### Example YAML snippet

```yaml
esphome:
  name: mb-multi-sensor
  libraries:
   - SPI  

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.28.142
    gateway: 192.168.28.1
    subnet: 255.255.255.0
    dns1: 192.168.28.1
    dns2: 8.8.8.8 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mb-Multi-Sensor Fallback Hotspot"
    password: "password"
    
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a
 
bme680_bsec:
    # i2c address
    # -----------
    # Common values are:
    # - 0x76
    # - 0x77
    # Default: 0x76
    address: 0x77

    # Temperature offset
    # ------------------
    # Useful if device is in enclosure and reads too high
    # Default: 0
    temperature_offset: 0

    # IAQ calculation mode
    # --------------------
    # Available options:
    # - static (for fixed position devices)
    # - mobile (for on person or other moveable devices)
    # Default: static
    iaq_mode: static

    # Sample rate
    # -----------
    # This controls the sampling rate for gas-dependant sensors and will govern the interval
    # at which the sensor heater is operated.
    # By default this rate will also be used for temperature, pressure and humidity sensors
    # but these can be overridden on a per-sensor level if required.
    #
    # Available options:
    # - lp (low power - samples every 3 seconds)
    # - ulp (ultra low power - samples every 5 minutes)
    # Default: lp
    sample_rate: ulp

    # Interval at which to save BSEC state
    # ------------------------------------
    # Default: 6h
    state_save_interval: 6h

sensor:
  - platform: bme680_bsec
    temperature:
      # Temperature in °C
      name: "Master Bedroom Temperature"
      sample_rate: lp
      filters:
        - median
        - offset: -1
    pressure:
      # Pressure in hPa
      name: "Master Bedroom Pressure"
      sample_rate: lp
      filters:
        - median
    humidity:
      # Relative humidity %
      name: "Master Bedroom Humidity"
      sample_rate: lp
      filters:
        - median
    gas_resistance:
      # Gas resistance in Ω
      name: "Master Bedroom Gas Resistance"
      filters:
        - median
    iaq:
      # Indoor air quality value
      name: "Master Bedroom IAQ"
      filters:
        - median
    iaq_accuracy:
      # IAQ accuracy as a numeric value of 0, 1, 2, 3
      name: "Master Bedroom Numeric IAQ Accuracy"
    co2_equivalent:
      # CO2 equivalent estimate in ppm
      name: "Master Bedroom CO2 Equivalent"
      filters:
        - median
    breath_voc_equivalent:
      # Volatile organic compounds equivalent estimate in ppm
      name: "Master Bedroom Breath VOC Equivalent"
      filters:
        - median

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "Master Bedroom IAQ Accuracy" 
    
binary_sensor:
  - platform: gpio
    pin: GPIO12
    name: "Master Bedroom Motion"
    device_class: motion    

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
WARNING Can't connect to ESPHome API for 192.168.28.142: Error connecting to ('192.168.28.142', 6053): [Errno 111] Connect call failed ('192.168.28.142', 6053)
```
