### ISSUE TITLE
Binary Sensor device_class: 'co' not available.

### ISSUE THREAD

**Issue by jasonhun** [esphome/issues#3155]
### The problem

The 'co' device class listed as a valid device class on the documentation is not available.  An error says:

Unknown value 'co', did you mean 'cold'?

![co_example](https://user-images.githubusercontent.com/24816782/159029637-56b048e8-ed5d-424a-91e2-6769c30ced3b.jpg)

### Which version of ESPHome has the issue?

2022.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.5

### What platform are you using?

ESP8266

### Board

nodemcu

### Example YAML snippet

```yaml
binary_sensor:
  - platform: gpio
    id: co_alarm
    pin: 
      number: D2
    name: "CO Alarm"
    device_class: co
    filters:
      - delayed_off: 10ms
```
