### ISSUE TITLE
Unable to boot with as3935 sensor enabled

### ISSUE THREAD

**Issue by marek-obuchowicz** [esphome/issues#3164]
### The problem

After upgrade to 2022.3.0 (from 1.16), i noticed that my esphome device doesn't boot (ends in safe mode). After try&error, i figured out that disabling as3935 solves the issues. 

### Which version of ESPHome has the issue?

2022.3.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

as3935

### Example YAML snippet

```yaml
esphome:
  name: ...
  comment: ESP32 Garden Controller
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: ...
  password: ...
  fast_connect: true
  use_address: ...

api:
  password: ...

ota:
  password: ...

logger:
  level: DEBUG
  baud_rate: 115200

syslog:
  ip_address: ...

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True
  id: bus_0

uart:
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600

esp32_ble_tracker:

as3935_i2c:
  irq_pin: GPIO5
  indoor: False
  noise_level: 1
  spike_rejection: 2
  mask_disturber: False
  watchdog_threshold: 2

binary_sensor:
  - platform: template
    name: "Garden controller online"
    lambda: |-
      return true;
    device_class: connectivity

sensor:
  - platform: wifi_signal
    name: "Garden controller WiFi signal"
    update_interval: 60s

  - platform: bme280
    address: 0x76
    update_interval: 5min
    iir_filter: "2x"
    temperature:
      name: "Garden Temperature"
      oversampling: 4x
      id: garden_temperature
      accuracy_decimals: 2
      device_class: "temperature"
      state_class: "measurement"
    pressure:
      name: "Garden Atmospheric Pressure"
      id: garden_pressure
      oversampling: 4x
      accuracy_decimals: 2
      device_class: "pressure"
      state_class: "measurement"
    humidity:
      name: "Garden Humidity"
      id: garden_humidity
      oversampling: 16x
      accuracy_decimals: 2
      device_class: "humidity"
      state_class: "measurement"
  - platform: sds011
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
      device_class: "pm25"
      state_class: "measurement"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
      device_class: "pm10"
      state_class: "measurement"
    update_interval: 5min

  - platform: xiaomi_gcls002
    mac_address: ...
    temperature:
      name: "Plant Oleander Temperature"
      device_class: "temperature"
      state_class: "measurement"
    moisture:
      name: "Plant Oleander Moisture"
      device_class: "humidity"
      state_class: "measurement"
    conductivity:
      name: "Plant Oleander Soil Conductivity"
    illuminance:
      name: "Plant Oleander Illuminance"
      device_class: "illuminance"
      state_class: "measurement"

  - platform: xiaomi_gcls002
    mac_address: ...
    temperature:
      name: "Plant Lawn Temperature"
      device_class: "temperature"
      state_class: "measurement"
    moisture:
      name: "Plant Lawn Moisture"
      device_class: "humidity"
      state_class: "measurement"
    conductivity:
      name: "Plant Lawn Soil Conductivity"
    illuminance:
      name: "Plant Lawn Illuminance"
      device_class: "illuminance"
      state_class: "measurement"
```

### Anything in the logs that might be useful for us?

```txt
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
␛[0;32m[I][logger:214]: Log initialized␛[0m
␛[0;35m[C][ota:461]: There have been 8 suspected unsuccessful boot attempts.␛[0m
␛[0;36m[D][esp32.preferences:114]: Saving preferences to flash...␛[0m
␛[0;32m[I][app:029]: Running through setup()...␛[0m
␛[0;32m[I][i2c.arduino:161]: Performing I2C bus recovery␛[0m
␛[0;35m[C][uart.arduino_esp32:077]: Setting up UART...␛[0m
␛[0;35m[C][as3935:010]: Setting up AS3935...␛[0m
␛[0;35m[C][as3935:013]:   IRQ Pin: GPIO5␛[0m
␛[0;35m[C][bme280.sensor:082]: Setting up BME280...␛[0m
␛[0;36m[D][esp32_ble_tracker:217]: Starting scan...␛[0m
␛[0;35m[C][wifi:037]: Setting up WiFi...␛[0m
␛[0;32m[I][wifi:248]: WiFi Connecting to '<redacted>'...␛[0m
␛[0;36m[D][binary_sensor:036]: 'Garden controller online': Sending state ON␛[0m
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400d5dd3  PS      : 0x00060230  A0      : 0x800d5bde  A1      : 0x3ffccbe0
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x0000002a  A5      : 0x3f401670
A6      : 0x0000ea60  A7      : 0x00000000  A8      : 0x800d5b0d  A9      : 0x3ffccbc0
A10     : 0x0000000c  A11     : 0x00000003  A12     : 0xffffff0f  A13     : 0x00000000
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000005  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000081  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000

ELF file SHA256: 0000000000000000

Backtrace: 0x400d5dd3:0x3ffccbe0 0x400d5bdb:0x3ffccc00 0x401deafd:0x3ffccc20 0x401debd9:0x3ffccc40 0x400e0785:0x3ffccc60 0x400e36c6:0x3ffcccb0 0x400e7e4a:0x3ffcd270 0x4009133e:0x3ffcd290

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
␛[0;32m[I][logger:214]: Log initialized␛[0m
␛[0;35m[C][ota:461]: There have been 9 suspected unsuccessful boot attempts.␛[0m
␛[0;36m[D][esp32.preferences:114]: Saving preferences to flash...␛[0m
␛[0;32m[I][app:029]: Running through setup()...␛[0m
␛[0;32m[I][i2c.arduino:161]: Performing I2C bus recovery␛[0m
␛[0;35m[C][uart.arduino_esp32:077]: Setting up UART...␛[0m
␛[0;35m[C][as3935:010]: Setting up AS3935...␛[0m
␛[0;35m[C][as3935:013]:   IRQ Pin: GPIO5␛[0m
␛[0;35m[C][bme280.sensor:082]: Setting up BME280...␛[0m
␛[0;36m[D][esp32_ble_tracker:217]: Starting scan...␛[0m
␛[0;35m[C][wifi:037]: Setting up WiFi...␛[0m
␛[0;32m[I][wifi:248]: WiFi Connecting to '<redacted>'...␛[0m
␛[0;36m[D][binary_sensor:036]: 'Garden controller online': Sending state ON␛[0m
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400d5dd3  PS      : 0x00060230  A0      : 0x800d5bde  A1      : 0x3ffccbe0
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x0000002a  A5      : 0x3f401670
A6      : 0x0000ea60  A7      : 0x00000000  A8      : 0x800d5b0d  A9      : 0x3ffccbc0
A10     : 0x0000000c  A11     : 0x00000003  A12     : 0xffffff0f  A13     : 0x3ffccae0
A14     : 0x00000000  A15     : 0x3ffcb320  SAR     : 0x00000005  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000081  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000

ELF file SHA256: 0000000000000000

Backtrace: 0x400d5dd3:0x3ffccbe0 0x400d5bdb:0x3ffccc00 0x401deafd:0x3ffccc20 0x401debd9:0x3ffccc40 0x400e0785:0x3ffccc60 0x400e36c6:0x3ffcccb0 0x400e7e4a:0x3ffcd270 0x4009133e:0x3ffcd290

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
␛[0;32m[I][logger:214]: Log initialized␛[0m
␛[0;35m[C][ota:461]: There have been 10 suspected unsuccessful boot attempts.␛[0m
␛[0;36m[D][esp32.preferences:114]: Saving preferences to flash...␛[0m
␛[1;31m[E][ota:468]: Boot loop detected. Proceeding to safe mode.␛[0m
```
