### ISSUE TITLE
ESPHome id() pointer to int* Array 

### ISSUE THREAD

**Issue by petermh87** [esphome/issues#3168]
### The problem

I am trying to create a multi-dimentional array to represent devices throughout my house.

Overall I am trying to achieve an array of pointers relating to [Floor][Area][Device[&Sensor,&Switch] using the following:
```
script:
  - id: Device_Array
   then
     lambda
         int* Device_Array[2][5][4][2] = {{{{{id(SensorF0A0D0),id(SwitchF0A0D0)},{id(SensorF0A0D1),id(SwitchF0A0D1)},......etc......
```
Which I can then cycle through using nested for loops to identify the correct sensor/switch combo to display depending on which Floor, Area and Device the user has selected.

to test whether I can get the address of a &Sensor or &Switch I used:

```
script:
  - id: test_script
    then:
      lambda: |-
        ESP_LOGD("test: ", "Sensor pointer: %p", id(F0A0D0));
        ESP_LOGD("test: ", "Switch pointer: %p", id(F0A0D0_Sw));
```

and when triggered I get:-
[19:42:40][D][binary_sensor:036]: 'NSPanel Right Button': Sending state ON
[19:42:40][D][binary_sensor:036]: 'NSPanel Right Button': Sending state OFF
[19:42:40][D][test: :451]: sensor pointer: 0x3ffb52cc
[19:42:40][D][test: :452]: Switch pointer: 0x3ffb9868
[19:42:40][D][switch:021]: 'NSPanel Relay 2' Toggling OFF.
[19:42:40][D][switch:037]: 'NSPanel Relay 2': Sending state OFF

Which apppearsto give me the address of id(F0A0D0) and id(F0A0D0_Sw) respectively

However when I try to load this into a int* variable or int* array by using the following:-

```
script:
  - id: Device_Array
    then: # Create Array [Floors][Areas][Devices][&Sensor,&Switch]
      lambda: |-
        int* Pointer_Array = id(F0A0D0_Sw);
```

I get this compile warning:-

/config/esphome/nspanel.yaml:446:41: error: cannot convert 'esphome::template_::TemplateSwitch*' to 'int*' in initialization
         int* Pointer_Array = id(F0A0D0_Sw);

Can anyone help?

Many thanks

### Which version of ESPHome has the issue?

2022.03.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.5

### What platform are you using?

ESP32

### Board

NSPanel

### Example YAML snippet

```yaml
script:
  - id: Device_Array
    then: # Create Array [Floors][Areas][Devices][&Sensor,&Switch]
      lambda: |-
        int* Pointer_Array = id(F0A0D0_Sw);

  - id: test_script
    then:
      lambda: |-
        ESP_LOGD("test: ", "Sensor pointer: %p", id(F0A0D0));
        ESP_LOGD("test: ", "Switch pointer: %p", id(F0A0D0_Sw));
```

### Anything in the logs that might be useful for us?

```txt
/config/esphome/nspanel.yaml:446:41: error: cannot convert 'esphome::template_::TemplateSwitch*' to 'int*' in initialization
         int* Pointer_Array = id(F0A0D0_Sw);
```
