### ISSUE TITLE
esp8266 (NodeMCU V2 Amica, Wemos D1 mini): Can't connect to ESPHome API // Ping timed out!

### ISSUE THREAD

**Issue by luxing0815** [esphome/issues#3169]
### The problem

Since update to v2022.3.0 all my esp8266 have the problem that they are losing their connection to Home Assistant. With v2022.2.0 I didn't have any problems.

This is independent of their intended use and the connected components. For example, I use the esp8266 to control LED strips, as well as for garden irrigation, where they switch a 4-way relay only.

After restarting the system and rebooting the esp's, it takes only a few minutes until they mutually lose their connection and pings get lost on both sides.

I checked the history. The issue occurred immediately after the update. Until then there were only isolated connection problems. Maybe 2-5 connection issues per day. Now it's several hundred a day!

I have already restarted my wifi. And there are no abnormalities with other devices in my network. All my esp8266 have static ip and their wifi signal strength is -60db to -70db.

It might be the same issue as reported in #3154. However, the error for me is not related to any specific sensors.

### Which version of ESPHome has the issue?

2022.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.5

### What platform are you using?

ESP8266

### Board

NodeMCU V2 Amica, Wemos D1 mini

### Component causing the issue

api

### Example YAML snippet

```yaml
esphome:
  name: kitchen-rgbw-led-strip1
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.82
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen Led Strip 1 Hotspot"
    password: !secret ap_password

captive_portal:

globals:
  - id: my_global_int
    type: int
    restore_value: no
    initial_value: '0'

switch:
  - platform: template
    name: krls1_clr_forward
    lambda: |-
      return false;
    turn_on_action:
      - lambda: |-
          id(my_global_int) += 1;
          if (id(my_global_int) > 6) {
            id(my_global_int) = 1;
          }
          
          ESP_LOGD("krls1_clr_forward", "Global value is: %d", id(my_global_int));
          
          float r = 0.0, g = 0.0, b = 0.0;
          
          switch (id(my_global_int)) {
            case 1: r = 1.0; g = 0.0; b = 0.0; break;
            case 2: r = 0.5; g = 0.5; b = 0.0; break;
            case 3: r = 0.0; g = 1.0; b = 0.0; break;
            case 4: r = 0.0; g = 0.5; b = 0.5; break;
            case 5: r = 0.0; g = 0.0; b = 1.0; break;
            case 6: r = 0.5; g = 0.0; b = 0.5; break;
            default: break;
          }

          auto call = id(kitchen_rgbw_led_strip1).turn_on();
          call.set_transition_length(500);
          call.set_color_brightness(1.0);
          call.set_rgbw(r, g, b, 0.0);
          call.set_effect("None");
          call.perform();

  - platform: template
    name: krls1_clr_backward
    lambda: |-
      return false;
    turn_on_action:
      - lambda: |-
          id(my_global_int) = 0;

          ESP_LOGD("krls1_clr_backward", "Global value is: %d", id(my_global_int));
          
          auto call = id(kitchen_rgbw_led_strip1).turn_on();
          call.set_transition_length(500);
          call.set_color_brightness(0.0);
          call.set_white(1.0);
          call.set_effect("None");
          call.perform();

remote_receiver:
  pin:
    number: D2
    inverted: true
    mode: INPUT_PULLUP
  dump: lg

binary_sensor:
  - platform: remote_receiver
    name: krls1_ir_brighter
    lg:
      data: 0x00F700FF
      nbits: 32
    on_press:
      then:
       - light.dim_relative:
           id: kitchen_rgbw_led_strip1
           relative_brightness: 20%
    
  - platform: remote_receiver
    name: krls1_ir_darker
    lg:
      data: 0x00F7807F
      nbits: 32
    on_press:
      then:
       - light.dim_relative:
           id: kitchen_rgbw_led_strip1
           relative_brightness: -20%

  - platform: remote_receiver
    name: krls1_ir_off
    lg:
      data: 0x00F740BF
      nbits: 32
    on_press:
      then:
        - light.turn_off: kitchen_rgbw_led_strip1
    
  - platform: remote_receiver
    name: krls1_ir_on
    lg:
      data: 0x00F7C03F
      nbits: 32
    on_press:
      then:
        - light.turn_on: kitchen_rgbw_led_strip1
    
  - platform: remote_receiver
    name: krls1_ir_flash
    lg:
      data: 0x00F7D02F
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            effect: pulse

  - platform: remote_receiver
    name: krls1_ir_strobe
    lg:
      data: 0x00F7F00F
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            effect: strobe

  - platform: remote_receiver
    name: krls1_ir_fade
    lg:
      data: 0x00F7C837
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            effect: random

  - platform: remote_receiver
    name: krls1_ir_smooth
    lg:
      data: 0x00F7E817
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            effect: lambda

  - platform: remote_receiver
    name: krls1_ir_white
    lg:
      data: 0x00F7E01F
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 0%
            white: 100%
            red: 0%
            green: 0%
            blue: 0%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_red
    lg:
      data: 0x00F720DF
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 100%
            green: 0%
            blue: 0%
            effect: None
        
  - platform: remote_receiver
    name: krls1_ir_green
    lg:
      data: 0x00F7A05F
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 0%
            green: 100%
            blue: 0%
            effect: None
            
  - platform: remote_receiver
    name: krls1_ir_blue
    lg:
      data: 0x00F7609F
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 0%
            green: 0%
            blue: 100%
            effect: None
            
  - platform: remote_receiver
    name: krls1_ir_orange
    lg:
      data: 0x00F710EF
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 100%
            green: 50%
            blue: 0%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_light_green
    lg:
      data: 0x00F7906F
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 50%
            green: 100%
            blue: 0%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_medium_blue
    lg:
      data: 0x00F750AF
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 0%
            green: 50%
            blue: 100%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_light_orange
    lg:
      data: 0x00F730CF
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 100%
            green: 75%
            blue: 0%
            effect: None
  
  - platform: remote_receiver
    name: krls1_ir_light_blue
    lg:
      data: 0x00F7B04F
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 0%
            green: 100%
            blue: 100%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_purple
    lg:
      data: 0x00F7708F
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 75%
            green: 0%
            blue: 100%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_dark_yellow
    lg:
      data: 0x00F708F7
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 100%
            green: 82%
            blue: 28%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_light_turquoise
    lg:
      data: 0x00F78877
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 28%
            green: 82%
            blue: 100%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_light_purple
    lg:
      data: 0x00F748B7
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 82%
            green: 28%
            blue: 100%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_yellow
    lg:
      data: 0x00F728D7
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 100%
            green: 100%
            blue: 0%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_turquoise
    lg:
      data: 0x00F7A857
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 0%
            green: 75%
            blue: 100%
            effect: None

  - platform: remote_receiver
    name: krls1_ir_pink
    lg:
      data: 0x00F76897
      nbits: 32
    on_press:
      then:
        - light.turn_on: 
            id: kitchen_rgbw_led_strip1
            color_brightness: 100%
            white: 0%
            red: 100%
            green: 0%
            blue: 75%
            effect: None

output:
  - platform: esp8266_pwm
    id: krls1_pwm_white
    pin: D1
    max_power: 100%

  - platform: esp8266_pwm
    id: krls1_pwm_red
    pin: D5
    max_power: 100%

  - platform: esp8266_pwm
    id: krls1_pwm_green
    pin: D6
    max_power: 100%

  - platform: esp8266_pwm
    id: krls1_pwm_blue
    pin: D7
    max_power: 100%

light:
  - platform: rgbw
    name: "Kitchen RGBW LED Strip 1"
    id: kitchen_rgbw_led_strip1
    white: krls1_pwm_white
    red: krls1_pwm_red
    green: krls1_pwm_green
    blue: krls1_pwm_blue
    effects:
      - pulse:
          transition_length: 0.5s
          update_interval: 0.5s
      - strobe:
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - random:
          transition_length: 4s
          update_interval: 5s
      - lambda:
          name: Custom
          update_interval: 1s
          lambda: |-
            static int state = 0;
            auto call = id(kitchen_rgbw_led_strip1).turn_on();
            // Transition of 1000ms = 1s
            call.set_transition_length(1000);
            if (state == 0) {
              call.set_rgbw(.0, .0, .0, 1.0);
            } else if (state == 1) {
              call.set_rgbw(1.0, .0, 1.0, .0);
            } else if (state == 2) {
              call.set_rgbw(.0, .0, 1.0, .0);
            } else {
              call.set_rgbw(1.0, .0, .0, .0);
            }
            call.perform();
            state += 1;
            if (state == 4)
              state = 0;
```

### Anything in the logs that might be useful for us?

```txt
iot device:
===========
[08:33:40][I][app:102]: ESPHome version 2022.3.0 compiled on Mar 21 2022, 17:26:11
[08:33:40][C][wifi:491]: WiFi:
[08:33:40][C][wifi:353]:   Local MAC: F4:CF:A2:EC:09:EC
[08:33:40][C][wifi:354]:   SSID: [redacted]
[08:33:40][C][wifi:355]:   IP Address: 192.168.1.82
[08:33:40][C][wifi:356]:   BSSID: [redacted]
[08:33:40][C][wifi:358]:   Hostname: 'kitchen-rgbw-led-strip1'
[08:33:40][C][wifi:360]:   Signal strength: -61 dB ▂▄▆█
...
[08:33:41][V][mdns:086]:   Services:
[08:33:41][V][mdns:088]:   - _esphomelib, _tcp, 6053
[08:33:41][V][mdns:090]:     TXT: version = 2022.3.0
[08:33:41][V][mdns:090]:     TXT: mac = f4cfa2ec09ec
[08:33:41][V][mdns:090]:     TXT: platform = ESP8266
[08:33:41][V][mdns:090]:     TXT: board = nodemcuv2
[08:33:41][C][ota:085]: Over-The-Air Updates:
[08:33:41][C][ota:086]:   Address: 192.168.1.82:8266
[08:33:41][C][ota:089]:   Using Password.
[08:33:41][C][api:138]: API Server:
[08:33:41][C][api:139]:   Address: 192.168.1.82:6053
[08:33:41][C][api:143]:   Using noise encryption: NO
INFO 192.168.1.82: Ping timed out!
INFO Disconnected from ESPHome API for 192.168.1.82
WARNING Disconnected from API
INFO Successfully connected to 192.168.1.82
[08:34:46][D][api:102]: Accepted 192.168.1.80
[08:34:46][V][api.connection:809]: Hello from client: 'Home Assistant 2022.3.5 (192.168.1.80)'
[08:34:46][D][api.connection:827]: Home Assistant 2022.3.5 (192.168.1.80): Connected successfully
INFO 192.168.1.82: Ping timed out!
INFO Disconnected from ESPHome API for 192.168.1.82
WARNING Disconnected from API
WARNING Can't connect to ESPHome API for 192.168.1.82: Timeout while connecting to ('192.168.1.82', 6053)
INFO Trying to reconnect to 192.168.1.82 in the background
INFO Successfully connected to 192.168.1.82
INFO 192.168.1.82: Ping timed out!
INFO Disconnected from ESPHome API for 192.168.1.82
WARNING Disconnected from API
INFO Successfully connected to 192.168.1.82
[08:36:33][D][api:102]: Accepted 192.168.1.80
[08:36:33][V][api.connection:809]: Hello from client: 'Home Assistant 2022.3.5 (192.168.1.80)'
[08:36:33][D][api.connection:827]: Home Assistant 2022.3.5 (192.168.1.80): Connected successfully
[08:36:33][V][api.connection:893]: Cannot send message because of TCP buffer space
[08:36:33][V][api.connection:893]: Cannot send message because of TCP buffer space
[08:36:33][V][api.connection:893]: Cannot send message because of TCP buffer space
[08:36:33][V][api.connection:893]: Cannot send message because of TCP buffer space
...
```

### Additional information

home assistant:
==========
2022-03-22 08:33:27 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:34:08 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping timed out!
2022-03-22 08:34:08 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:34:38 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82: Timeout while connecting to ('192.168.1.82', 6053)
2022-03-22 08:34:38 INFO (MainThread) [aioesphomeapi.reconnect_logic] Trying to reconnect to kitchen-rgbw-led-strip1 @ 192.168.1.82 in the background
2022-03-22 08:34:46 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:35:29 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping timed out!
2022-03-22 08:35:29 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:35:29 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:36:26 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping timed out!
2022-03-22 08:36:26 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:36:33 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:36:38 WARNING (MainThread) [homeassistant.components.esphome] Error getting initial data for 192.168.1.82: Timeout waiting for response for <class 'api_pb2.ListEntitiesRequest'>
2022-03-22 08:36:48 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:36:48 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping Failed: Socket closed while reading data: 0 bytes read on a total of 1 expected bytes
2022-03-22 08:37:03 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:38:13 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping timed out!
2022-03-22 08:38:13 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:38:21 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:40:51 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping timed out!
2022-03-22 08:40:51 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:40:51 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:42:06 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping timed out!
2022-03-22 08:42:06 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:42:06 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:42:51 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping timed out!
2022-03-22 08:42:51 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:42:52 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:43:32 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping timed out!
2022-03-22 08:43:32 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:44:02 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82: Timeout while connecting to ('192.168.1.82', 6053)
2022-03-22 08:44:02 INFO (MainThread) [aioesphomeapi.reconnect_logic] Trying to reconnect to kitchen-rgbw-led-strip1 @ 192.168.1.82 in the background
2022-03-22 08:44:11 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:44:36 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping timed out!
2022-03-22 08:44:36 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:44:36 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:46:00 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping timed out!
2022-03-22 08:46:00 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:46:00 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:46:30 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Error while reading incoming messages: Error while reading data: [Errno 104] Connection reset by peer
2022-03-22 08:46:30 INFO (MainThread) [aioesphomeapi.reconnect_logic] Disconnected from ESPHome API for kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:46:30 INFO (MainThread) [aioesphomeapi.connection] kitchen-rgbw-led-strip1 @ 192.168.1.82: Ping Failed: Error while reading data: [Errno 104] Connection reset by peer
2022-03-22 08:46:30 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
2022-03-22 08:47:28 INFO (MainThread) [aioesphomeapi.reconnect_logic] Successfully connected to kitchen-rgbw-led-strip1 @ 192.168.1.82
