### ISSUE TITLE
2022.3.0 have an issue at binary sensor automation with GPIO switch.

### ISSUE THREAD

**Issue by noogugae** [esphome/issues#3174]
### The problem

Until 2022.2.6 binary sensor automation with GPIO switch works well, but after updateing 2022.3.0 GPIO switch doesn' work at all.
I removed the automation at binary sensor and move it to GPIO switch, then It works but that isn't what I want.
So I rolled back to 2022.2.6.
Is there any change at 2022.3.0?

### Which version of ESPHome has the issue?

2022.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.7

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

binary_sensor, GPIO

### Example YAML snippet

```yaml
#Below code works at 2022.2.6, but GPIO switch doesn't work at 2022.3.0
binary_sensor:
  - platform: gpio
    pin: GPIO13
    id: physical_button
    name: "LED Light Button"
    on_press:
      then:
        - lambda: |-
            if (id(led1_status).state == false) {
              id(led1_status).publish_state(true);
            } else {
              id(led1_status).publish_state(false);
            }  
  - platform: template
    id: led1_status
    name: "LED Light1 status"
switch:
  - platform: gpio
    pin: GPIO13
    name: "LED Light 1"
    id: led_1
    restore_mode: ALWAYS_OFF
    inverted: true
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: led_1

# after code changing like below at 2022.3.0, GPIO switch works but hardware switch status doesn't change led1_status_sensor

binary_sensor:
  - platform: gpio
    pin: GPIO13
    id: physical_button
    name: "LED Light Button"

  - platform: template
    id: led1_status
    name: "LED Light1 status"
switch:
  - platform: gpio
    pin: GPIO13
    name: "LED Light 1"
    id: led_1
    restore_mode: ALWAYS_OFF
    inverted: true
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: led_1
      - lambda: |-
          if (id(led1_status).state == false) {
            id(led1_status).publish_state(true);
          } else {
            id(led1_status).publish_state(false);
          }
```

### Anything in the logs that might be useful for us?

```txt
There is no error message but GPIO switch doesn't work.
```
