### ISSUE TITLE
Remote_transmitter initial state on inverted pin

### ISSUE THREAD

**Issue by cg6** [esphome/issues#3179]
### The problem

Remote_transmitter does not set the pin state during initializing when using an inverted pin. After a code is sent it works correctly - stays high after transmitting. I have worked around the issue by sending a code during on_boot.

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.9

### What platform are you using?

ESP32-IDF

### Board

ESP-C3-01M-Kit

### Component causing the issue

remote_transmitter

### Example YAML snippet

```yaml
remote_transmitter:
  pin:
    number: 3
    inverted: True
  # Output unmodulated
  carrier_duty_percent: 100%

# Invert works as expected except pin is held low between boot and first transmit
# This on_boot mitigates the issue
esphome:
  name: esp-c3-devkit
  on_boot:
    priority: 800
    then:
      - remote_transmitter.transmit_raw:
          code: [0]
```
