### ISSUE TITLE
ESP32Cam camera.record

### ISSUE THREAD

**Issue by leoMehlig** [esphome/issues#318]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io v0.93.0

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 Cam

**Affected component:**

ESP32 Cam

**Description of problem:**
The camera component works fine in home assistant, but when trying to record the stream it displays an error, that that is not supported. 

Did I do something wrong or is that just not supported?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: hallway_cam
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "***"
  password: "***"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: '***'

ota:
  password: '***'

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # test_pattern: true
  name: "Hallway Camera"
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

PS. Thanks for the great work here!!!
