### ISSUE TITLE
Remote_receiver on_raw lambda - the x vector has an extra value. Also data type query.

### ISSUE THREAD

**Issue by cg6** [esphome/issues#3180]
### The problem

When using a lambda within remote_receiver -> on_raw there are two issues:

1. The vector x has an extra element "-10000" appended. This element is not shown in the  remote_receiver -> dump: all output.
I assume this is the idle timeout, however I believe it should not be considered part of the code received and not passed in x.

2.  The data type of x is `std::vector<long int>`. The documentation [here ](https://esphome.io/components/remote_receiver.html) specifies `std::vector<int>`
My home assistant (where the compiler runs) is running on x86_64 - may be relevant.

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.9 on x86_64

### What platform are you using?

ESP32-IDF

### Board

ESP-C3-01M-Kit

### Component causing the issue

remote_receiver

### Example YAML snippet

```yaml
# This works. However the -10000 at the end of v1 should not be needed.

remote_receiver:
  pin:
    number: 9
    inverted: True
  dump: all
  on_raw:
    remote_transmitter.transmit_raw:
      transmitter_id : trred
      code: !lambda |-
          //TODO upate Test codes. 
          const std::vector<long int> v1 = {4088, -1542, 4096, -510, 4096, -1019, 510, -4096, 511, -4096, 1020, -10000};
          const std::vector<long int> v2 = {4088, -1542, 1019, -510, 513, -1019, 510, -509, 511, -510, 1020};
          if (x == v1) {return v2;}
          return x;
```

### Anything in the logs that might be useful for us?

```txt
remote_receiver dump output. This sequence results in `if (x == v1)` evaluating true - note the extra -10000 is not shown in this output.

[16:53:03][D][remote.raw:041]: Received Raw: 4088, -1542, 4096, -510, 4096, -1019, 510, -4096, 511, -4096, 1020
```
