### ISSUE TITLE
state_class  total not valid

### ISSUE THREAD

**Issue by magnetus26** [esphome/issues#3181]
### The problem

The problem
I try to set the state_class to total as described in the HA documentation here: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

But I get an error:
![image](https://user-images.githubusercontent.com/22038983/160260841-448d1fbe-2e14-418e-bc9f-b8da8761df40.png)

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.03.5

### What platform are you using?

ESP32

### Board

D1 Mini NodeMCU ESP32 ESP-WROOM-32

### Component causing the issue

pipsolar

### Example YAML snippet

```yaml
sensor:
  - platform: pipsolar
    pv_charging_power:
      id: inverter0_pv_charging_power
      name : "PV Charging Power"
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh
      device_class: "energy"
      state_class: "total"
      accuracy_decimals: 3
```

### Anything in the logs that might be useful for us?

```txt
looks like same issue as #2881 but in this case is an ESP32 board
```
