### ISSUE TITLE
EPEVER® MPPT Solar Charge Controller should use signed value for temperature

### ISSUE THREAD

**Issue by jonadis** [esphome/issues#3183]
### The problem

I have an EPEVER® MPPT Solar Charge Controller setup following the guide at: [https://esphome.io/cookbook/tracer-an.html](https://esphome.io/cookbook/tracer-an.html).
In the guide it shows an example for temperature measurement as:
```
  - platform: modbus_controller
    modbus_controller_id: epever
    id: device_temperature
    name: "Device temperature"
    address: 0x3111
    unit_of_measurement: °C
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
```
However in practice, when the actual temperature is below 0 deg C the value reported is around 650 deg C.  I was able to correct this by changing the line:
```
    value_type: U_WORD
```
to
```
    value_type: S_WORD
```
and now negative values are reported appropriately.  It is likely that other temperature measurement registers need similar adjustments but that is the only one that I've tested so far.

### Which version of ESPHome has the issue?

2022.3.1 (and others)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.7 (and others)

### What platform are you using?

ESP32

### Board

esp32-devkit-c

### Component causing the issue

modbus

### Example YAML snippet

```yaml
- platform: modbus_controller
    modbus_controller_id: epever
    id: device_temperature
    name: "Device temperature"
    address: 0x3111
    unit_of_measurement: °C
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
```
