### ISSUE TITLE
custom UART device unable to Compiling

### ISSUE THREAD

**Issue by Pro-Control** [esphome/issues#3186]
### The problem

try to use custom UART and flowing official guide without any modification on this link 

https://esphome.io/custom/uart.html 

I got this error

### Which version of ESPHome has the issue?

v2022.3.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.7

### What platform are you using?

ESP8266

### Board

d1

### Component causing the issue

Custom UART Device

### Example YAML snippet

```yaml
# DEVICE ###################################################
esphome:
  name: d1-test
  includes:
    - includes/my_custom_component.h
esp8266:
  board: d1_mini

substitutions:
  devicename: D1-Test
  
packages:
  device_base: !include common/device_base.yaml
  web_server: !include common/web_server.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  power_save_mode: "none"
  manual_ip:
    static_ip: 192.168.5.90
    gateway: !secret gateway
    subnet: !secret subnet
  ap:
    ssid: "$devicename Fallback"
    password: "$devicename$devicename"
  


#-----------------------------------------------------------

#-----------------------------------------------------------

# Communication ############################################
uart:
  id: uart_bus1
  tx_pin: GPIO4
  rx_pin: GPIO5
  baud_rate: 9600



custom_component:
- lambda: |-
    auto my_custom = new MyCustomComponent(id(uart_bus1));
    return {my_custom};
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/d1-test.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing d1-test (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|-- <ArduinoJson> 6.18.5
Compiling .pioenvs/d1-test/src/main.cpp.o
In file included from src/main.cpp:53:
src/my_custom_component.h: In member function 'virtual void MyCustomComponent::loop()':
src/my_custom_component.h:12:19: error: 'readString' was not declared in this scope; did you mean 'String'?
   12 |     String line = readString();
      |                   ^~~~~~~~~~
      |                   String
src/my_custom_component.h:13:13: error: 'parseInt' was not declared in this scope
   13 |     int i = parseInt();
      |             ^~~~~~~~
*** [.pioenvs/d1-test/src/main.cpp.o] Error 1
========================== [FAILED] Took 5.50 seconds ==========================
```
