### ISSUE TITLE
Reuse ESP32

### ISSUE THREAD

**Issue by GigaTech** [esphome/issues#3188]
### The problem

Home Assistant Log entry
`WARNING (MainThread) [homeassistant.components.esphome] Name of device esp-fridge-01 changed to esp-rfid-02, potentially due to IP reassignment`

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.7

### What platform are you using?

ESP32

### Board

ESP32 Woom-32

### Component causing the issue

WiFi

### Example YAML snippet

```yaml
esphome:
  name: esp-rfid-02
  platform: ESP32
  board: esp32dev

wifi:

  # use_address: 192.168.7.47
  # use_address: esp-fridge-01
  # use_address: esp-fridge-01.local
  
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.7.47
    gateway: !secret lan_gateway
    subnet: !secret lan_subnet
    dns1: !secret lan_dns1
```

### Additional information

Hi,

I have a bucket full of 'test' ESP32's that I write to and... test on bread board

Once the code is finalised I design/test a PCB and do further testing with other ESP32's soldered to the PCB.

So the question is, how to reuse an ESP32 that was previously 'registered' with ESPhome WITHOUT knowing what it was before, or it previous IP address?

As you can see I have tried `use_address` but to no avail

Thanks
