### ISSUE TITLE
Documentation on how to use multiple UART with ESP32

### ISSUE THREAD

**Issue by kryptonitecb3** [esphome/issues#3191]
### The problem

I'm attempting to use an ESP32 to control two RS-232C enabled devices. I have one device tested and working, however when I attempted to add the second UART bus to my yaml, the esphome addon for home assistant gives errors when I attempt to validate. I have found documentation on how to add multiple UARTs for sensors but nothing on how to use 'uart.write' with multiple UART buses.

If there is a way to accomplish this can the documentation on esphome.io be updated with an example.

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant OS 7.5, supervisor-2022.03.5, core-2022.3.7

### What platform are you using?

ESP32

### Board

board: esp32doit-devkit-v1

### Component causing the issue

uart

### Example YAML snippet

```yaml
esphome:
  name: ${devicename}
  comment: ${friendlyname}
  includes:
    - include/lgtv_uart.h

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

wifi:
  networks:
  ap: 

captive_portal:

api:

ota:

logger:

time:
  - platform: homeassistant
    id: ha_time
    on_time_sync:
      then:
        - logger.log: "${friendly_name} synchronized system clock with Home Assistant"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Sensor"
    icon: mdi:wifi-strength-1
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  - platform: custom
    lambda: |-
      auto lgtv_uart = new LGTVUARTComponent(id(uart_bus1));
      App.register_component(lgtv_uart);
      return {lgtv_uart};
    binary_sensors:
      name: "LG OLED TV Status"
      id: power

status_led:
  pin:
    number: GPIO25
    inverted: False

uart:
  - id: uart_bus1
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: NONE  
    tx_pin: GPIO17
    rx_pin: GPIO16
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n,\r,0"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);
  - id: uart_bus2
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: NONE  
    tx_pin: GPIO18
    rx_pin: GPIO19
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n,\r,0"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

interval:
  - interval: 30s
    then:
      - uart.write:              ##does not allow uart_id to be defined
          uart_id: uart_bus1
          data: "ka 00 ff\r"

switch:
  - platform: template
    name: "${friendly_name} LG TV RS-232"
    icon: mdi:television
    lambda: |-
      return id(power).state;
    turn_on_action:
      - switch.turn_on: tvon_switch
    turn_off_action:
      - switch.turn_on: tvoff_switch
  - platform: uart
    uart_id: uart_bus1
    id: tvon_switch
    data: "ka 00 01\r"
  - platform: uart
    uart_id: uart_bus1
    id: tvoff_switch
    data: "ka 00 00\r"

button:
  - platform: restart
    name: "${friendly_name} Restart"
  - platform: template
    name: "${friendly_name} LG TV RS-232 Off"
    icon: mdi:television-off
    id: tvoff_button
    on_press:
      - uart.write: 
        uart_id: uart_bus1
        data: "ka 01 00\r"
  - platform: template
    name: "${friendly_name} LG TV RS-232 On"
    icon: mdi:television-shimmer
    on_press:
      - uart.write: 
        uart_id: uart_bus1
        data: "ka 01 01\r"

  - platform: template
    name: "${friendly_name} Marantz RS-232 On"
#    icon: mdi:power-sleep
    on_press:
      - uart.write: 
        uart_id: uart_bus2
        data: "PWON\r"
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/office-remote-node.yaml...
INFO Detected timezone 'America/Chicago'
Failed config

interval: [source /config/esphome/office-remote-node.yaml:103]
  - [source /config/esphome/office-remote-node.yaml:103]
    interval: 30s
    then:  [source /config/esphome/office-remote-node.yaml:105]
      - [source /config/esphome/office-remote-node.yaml:105]
        uart.write:  [source /config/esphome/office-remote-node.yaml:106]
          
          [uart_id] is an invalid option for [uart.write].
          uart_id: uart_bus1 [source /config/esphome/office-remote-node.yaml:106]
          data: ka 00 ff
button.template: [source /config/esphome/office-remote-node.yaml:131]
  platform: template
  name: Office Remote LG TV RS-232 Off
  icon: mdi:television-off
  id: tvoff_button
  on_press:  [source /config/esphome/office-remote-node.yaml:136]
    
    Cannot have two actions in one item. Key 'uart.write' overrides 'uart_id'! Did you forget to indent the block inside the uart.write?.
    - [source /config/esphome/office-remote-node.yaml:136]
      uart.write: 
      uart_id: uart_bus1
      data: ka 01 00
button.template: [source /config/esphome/office-remote-node.yaml:139]
  platform: template
  name: Office Remote LG TV RS-232 On
  icon: mdi:television-shimmer
  on_press:  [source /config/esphome/office-remote-node.yaml:143]
    
    Cannot have two actions in one item. Key 'uart.write' overrides 'uart_id'! Did you forget to indent the block inside the uart.write?.
    - [source /config/esphome/office-remote-node.yaml:143]
      uart.write: 
      uart_id: uart_bus1
      data: ka 01 01
button.template: [source /config/esphome/office-remote-node.yaml:272]
  platform: template
  name: Office Remote Marantz RS-232 On
  on_press:  [source /config/esphome/office-remote-node.yaml:276]
    
    Cannot have two actions in one item. Key 'uart.write' overrides 'uart_id'! Did you forget to indent the block inside the uart.write?.
    - [source /config/esphome/office-remote-node.yaml:276]
      uart.write: 
      uart_id: uart_bus2
      data: PWON
button.template: [source /config/esphome/office-remote-node.yaml:279]
  platform: template
  name: Office Remote Marantz RS-232 Off
  on_press:  [source /config/esphome/office-remote-node.yaml:283]
    
    Cannot have two actions in one item. Key 'uart.write' overrides 'uart_id'! Did you forget to indent the block inside the uart.write?.
    - [source /config/esphome/office-remote-node.yaml:283]
      uart.write: 
      uart_id: uart_bus2
      data: PWSTANDBY
```

### Additional information

I have tried multiple variations, and indentions of uart.write and uart_id. Nothing has worked so far.

https://esphome.io/components/uart.html
https://esphome.io/cookbook/uart_text_sensor.html
https://esphome.io/custom/uart.html
https://esphome.io/components/logger.html#hardware-uarts

examples found:
https://community.home-assistant.io/t/esphome-define-2-uart/378129/5
https://github.com/esphome/issues/issues/488
https://github.com/esphome/issues/issues/521
