### ISSUE TITLE
Wrong Display Dimensions for ST7789

### ISSUE THREAD

**Issue by Coolie1101** [esphome/issues#3192]
### The problem

Trying to use a ST7789 (240x320) display configured as [ST7789V](https://esphome.io/components/display/st7789v.html), but the display view size is being rendered as 135 x 240 pixels instead of 240 x 320 pixels.

### Which version of ESPHome has the issue?

ESPHome version 2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Example YAML snippet

```yaml
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    rotation: 180
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    id: display1
    pages:
      - id: page0
        lambda: |-
          it.rectangle(0,  0, it.get_width(), it.get_height(), id(my_red));
          it.print(0, 0, id(font1), "Hello World!");
```

### Anything in the logs that might be useful for us?

```txt
[07:44:53][C][st7789v:119]: SPI ST7789V
[07:44:53][C][st7789v:119]:   Rotations: 180 °
[07:44:53][C][st7789v:119]:   Dimensions: 135px x 240px
[07:44:53][C][st7789v:120]:   CS Pin: GPIO5
[07:44:53][C][st7789v:121]:   DC Pin: GPIO16
[07:44:53][C][st7789v:122]:   Reset Pin: GPIO23
[07:44:53][C][st7789v:123]:   B/L Pin: GPIO4
[07:44:53][C][st7789v:124]:   Update Interval: 5.0s
```

### Additional information

![image](https://user-images.githubusercontent.com/28989417/160827348-73ce0933-99a7-449f-bdcf-95a8adcd176d.png)

![image](https://user-images.githubusercontent.com/28989417/160827283-94b95875-7954-4716-b587-21bfb5b3b689.png)
