### ISSUE TITLE
ESP8266 only accessible/visible when in adoption mode. 

### ISSUE THREAD

**Issue by UV-PWRD** [esphome/issues#3193]
### The problem

New to all this so forgive my oversights. This is my first ESP device. 

This is a Nodemcu V3 board and I'm trying to get it going with a Dallas temp sensor. 

I can make the board adoptable via the ESP Home Web Portal and have it connect to my home WiFi at which point I can browse to the web interface on the device and the device is visible in the ESP Home add on within Home Assistant. 

If I attempt to flash ANYTHING to the device, including the very same config that's on it after adoption, from that point forward the device will respond to ping only but I cannot access the web interface and the device is no longer visible in Home Assistant. 

I have tried flashing from the Nodemcu flash tool, ESP Home command line (Win 10 x64) and manually selecting the BIN and doing it OTA or from the ESP Home Web Portal all without success. 

I've tried custom binaries created by the ESP Home command line wizard as well as copy/paste the config from the yaml that contains the code used when the device is adoptable also. 

I've tried selecting Nodemcuv2 and also the generic esp01_1m boards.

I've also tried using a different wireless network (home vs office to rule out the Wifi/router) and I've also intentionally set the WiFi details wrong to force it to local AP mode, which I can connect to. 

Any help appreciated! 

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.2.6

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

Unsure

### Example YAML snippet

```yaml
esphome:
  name: hotwatertank

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "REDACTED"
  password: "REDACTED"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hotwatertank Fallback Hotspot"
    password: "REDCATED"

captive_portal:

dallas:
  - pin: GPIO4
```
