### ISSUE TITLE
Missing bsec.h header when compiling ESP-C3 with bme680_bsec sensor 

### ISSUE THREAD

**Issue by yukfai-wong** [esphome/issues#3195]
### The problem

Hi there, I am compiling on m1 mac. Somehow the bsec.h is missing even BSEC Software Library is already installed. No sure what causes the issue. Thanks.

### Which version of ESPHome has the issue?

2022.3.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

ESP-C3-32S

### Component causing the issue

bme680_bsec

### Example YAML snippet

```yaml
esphome:
  name: esp32c332s

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 3min

i2c:
  - id: bus_a
    scan: True
    sda: 4
    scl: 5
    
bme680_bsec:

sensor:
  - platform: bme680_bsec
    temperature:
      name: "BME680 Temperature"
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    iaq:
      name: "BME680 IAQ"
    co2_equivalent:
      name: "BME680 CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration esphome/esp32c332s.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32c332s (board: esp32-c3-devkitm-1; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf 3.40302.0 (4.3.2) 
 - tool-cmake 3.16.4 
 - tool-ninja 1.9.0 
 - toolchain-riscv32-esp 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32s2 8.4.0+2021r2-patch2
Reading CMake configuration...
Library Manager: Installing SPI
Library Manager: Installing boschsensortec/BSEC Software Library @ 1.6.1480

Unpacking  [------------------------------------]    0%
Unpacking  [------------------------------------]    2%
Unpacking  [#-----------------------------------]    5%
Unpacking  [##----------------------------------]    8%
Unpacking  [###---------------------------------]   10%
Unpacking  [####--------------------------------]   13%
Unpacking  [#####-------------------------------]   16%
Unpacking  [######------------------------------]   18%
Unpacking  [#######-----------------------------]   21%
Unpacking  [########----------------------------]   24%
Unpacking  [#########---------------------------]   27%
Unpacking  [##########--------------------------]   29%
Unpacking  [###########-------------------------]   32%
Unpacking  [############------------------------]   35%
Unpacking  [#############-----------------------]   37%
Unpacking  [##############----------------------]   40%
Unpacking  [###############---------------------]   43%
Unpacking  [################--------------------]   45%
Unpacking  [#################-------------------]   48%
Unpacking  [##################------------------]   51%
Unpacking  [###################-----------------]   54%
Unpacking  [####################----------------]   56%
Unpacking  [#####################---------------]   59%
Unpacking  [######################--------------]   62%
Unpacking  [#######################-------------]   64%
Unpacking  [########################------------]   67%
Unpacking  [#########################-----------]   70%
Unpacking  [##########################----------]   72%
Unpacking  [###########################---------]   75%
Unpacking  [############################--------]   78%
Unpacking  [#############################-------]   81%
Unpacking  [##############################------]   83%
Unpacking  [###############################-----]   86%
Unpacking  [################################----]   89%
Unpacking  [#################################---]   91%
Unpacking  [##################################--]   94%
Unpacking  [###################################-]   97%
Unpacking  [####################################]  100%
Library Manager: BSEC Software Library @ 1.6.1480 has been installed!
Generating assembly for certificate bundle...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Library Manager: Installing SPI
No dependencies
Compiling .pioenvs/esp32c332s/src/esphome/components/bme680_bsec/bme680_bsec.o
Compiling .pioenvs/esp32c332s/src/esphome/components/esp32/core.o
Compiling .pioenvs/esp32c332s/src/esphome/components/esp32/gpio_arduino.o
Compiling .pioenvs/esp32c332s/src/esphome/components/esp32/gpio_idf.o
Compiling .pioenvs/esp32c332s/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/esp32c332s/src/esphome/components/i2c/i2c.o
Compiling .pioenvs/esp32c332s/src/esphome/components/i2c/i2c_bus_arduino.o
Compiling .pioenvs/esp32c332s/src/esphome/components/i2c/i2c_bus_esp_idf.o
In file included from src/esphome/components/bme680_bsec/bme680_bsec.cpp:1:
src/esphome/components/bme680_bsec/bme680_bsec.h:12:10: fatal error: bsec.h: No such file or directory

**************************************************************
* Looking for bsec.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:bsec.h"
* Web  > https://registry.platformio.org/search?q=header:bsec.h
*
**************************************************************

 #include <bsec.h>
          ^~~~~~~~
compilation terminated.
Compiling .pioenvs/esp32c332s/src/esphome/components/logger/logger.o
Compiling .pioenvs/esp32c332s/src/esphome/components/mdns/mdns_component.o
*** [.pioenvs/esp32c332s/src/esphome/components/bme680_bsec/bme680_bsec.o] Error 1
========================== [FAILED] Took 9.20 seconds ==========================
```
