### ISSUE TITLE
ac_dimmer via port expander? 

### ISSUE THREAD

**Issue by BrownC0de** [esphome/issues#3205]
### The problem

Hi. There is a need to connect several triacs through a port expander (for example, pca9685, mcp23016).
But I don’t understand how to select the expander pins through the configurator? And is it possible?

### Which version of ESPHome has the issue?

 v2022.3.0 

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

ac_dimmer

### Example YAML snippet

```yaml
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: D7
    zero_cross_pin:
      number: D6
      mode:
        input: true
      inverted: yes
```
