### ISSUE TITLE
Cannot perform subsequent commands after successful initial run (external component fail) on Windows 10

### ISSUE THREAD

**Issue by spoonwzd** [esphome/issues#3208]
### The problem

First run works fine, but I am unable to perform any subsequent commands on the yaml - it always fails when referencing the external_component. I have to delete and recreate the entire project every time I want to make a change.

This behavior is identical regardless of the command, ie. run, clean, etc.

![image](https://user-images.githubusercontent.com/6536570/162566571-b74a4f92-2da3-41e1-8692-efb619d26b84.png)

### Which version of ESPHome has the issue?

2022.3.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32

### Board

ESP32-DevKitC

### Example YAML snippet

```yaml
substitutions:
  name: batt3
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO16
  rx_pin: GPIO17

external_components:
  - source: ${external_components_source}
    refresh: 0s
```

### Anything in the logs that might be useful for us?

```txt
←[32mINFO Reading configuration esp32-example.yaml...←[0m
←[32mINFO Updating https://github.com/syssi/esphome-jk-bms.git@main←[0m
Failed config

external_components: [source esp32-example.yaml:23]
  - [source esp32-example.yaml:23]

line 23 = source: ${external_components_source} as per yaml snippet
```

### Additional information

Running on Windows 10 21H2
Python 3.10.4
esphome 2022.3.2
