### ISSUE TITLE
ESP32-C3 Won't Stay Online

### ISSUE THREAD

**Issue by efaden** [esphome/issues#3209]
### The problem

Trying to use the ESP32 C3 as a BLE gateway for HA.  The device seems to come online and then after a minute or to goes offline until it gets reset.  I can't figure out why though.  Nothing seems to show in the log and I am connecting and uploading via serial?  Suggestions?

My config

```
esphome:
  name: testc3
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

external_components:
  - source: github://myhomeiot/esphome-components

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Testc3 Fallback Hotspot"
    password: ""
  
 
esp32_ble_tracker: 
  scan_parameters:
    interval: 320ms
    window: 120ms
    duration: 60s
    active: true
    
```

Log after a rest looks like this.... just stops there.
```

I (30) boot: ESP-IDF 4.3.2 2nd stage bootloader
I (30) boot: compile time 09:30:21
I (30) boot: chip revision: 3
I (32) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (39) boot.esp32c3: SPI Speed      : 80MHz
I (44) boot.esp32c3: SPI Mode       : DIO
I (48) boot.esp32c3: SPI Flash Size : 4MB
I (53) boot: Enabling RNG early entropy source...
I (58) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (77) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (84) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (92) boot:  3 app0             OTA app          00 10 00010000 001c0000
I (99) boot:  4 app1             OTA app          00 11 001d0000 001c0000
I (107) boot: End of partition table
I (111) boot_comm: chip revision: 3, min. application chip revision: 0
I (118) esp_image: segment 0: paddr=00010020 vaddr=3c0e0020 size=34000h (212992) map
I (159) esp_image: segment 1: paddr=00044028 vaddr=3fc8ec00 size=03aa8h ( 15016) load
I (162) esp_image: segment 2: paddr=00047ad8 vaddr=40380000 size=08540h ( 34112) load
I (171) esp_image: segment 3: paddr=00050020 vaddr=42000020 size=df25ch (914012) map
I (310) esp_image: segment 4: paddr=0012f284 vaddr=40388540 size=06568h ( 25960) load
I (315) esp_image: segment 5: paddr=001357f4 vaddr=50000000 size=00010h (    16) load
I (320) boot: Loaded app from partition at offset 0x10000
I (322) boot: Disabling RNG early entropy source...
I (339) cpu_start: Pro cpu up.
I (351) cpu_start: Pro cpu start user code
I (351) cpu_start: cpu freq: 160000000
I (351) cpu_start: Application information:
I (354) cpu_start: Project name:     testc3
I (359) cpu_start: App version:      2022.3.2
I (364) cpu_start: Compile time:     Apr  9 2022 09:33:19
I (370) cpu_start: ELF file SHA256:  9a46073191edd2c7...
I (376) cpu_start: ESP-IDF:          4.3.2
I (380) heap_init: Initializing. RAM available for dynamic allocation:
I (388) heap_init: At 3FC9A320 len 00025CE0 (151 KiB): DRAM
I (394) heap_init: At 3FCC0000 len 0001F060 (124 KiB): STACK/DRAM
I (401) heap_init: At 50000010 len 00001FF0 (7 KiB): RTCRAM
I (407) spi_flash: detected chip: generic
I (412) spi_flash: flash io: dio
I (416) sleep: Configure to isolate all GPIO pins in sleep state
```

### Which version of ESPHome has the issue?

2022.23.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

ESP32C3

### Component causing the issue

Unsure
