### ISSUE TITLE
Web API: switch level lost the state

### ISSUE THREAD

**Issue by vespadj** [esphome/issues#3210]
### Lever "ON" but state "OFF" and vice-versa.

v. 2022.3.2 WEB API (HTML page)

The lever of the switch looses state value and becomes a toggler if playing between it and other commands.

Work-around: Refresh page.

I also would like to suggest to ad a `target="_blank"` on esphome logo `href="https://esphome.io/web-api"`

### Which version of ESPHome has the issue?

2022.3.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

ESP32 Devkit-C v.4

### Component causing the issue

web, switch

### Example YAML snippet

```yaml
button:
  - platform: template
    name: "Turn switch on"
    on_press:
      then:
        - switch.turn_on: switch1
        - delay: 30 s
        - switch.turn_off: switch1

switch:
  - platform: gpio
    pin: GPIO33
    name: "Switch1"
    id: switch1
    # inverted: true
```

### Additional information

![Screenshot 1](https://user-images.githubusercontent.com/1891045/162583147-5b628503-dc69-47b0-a3f8-22f07fe98ea6.png)
![Screenshot 2](https://user-images.githubusercontent.com/1891045/162583149-025348c1-2407-4d49-88ce-2558cdb163b3.png)
