### ISSUE TITLE
Module TCA9548A(.cpp) 

### ISSUE THREAD

**Issue by jmBrosch** [esphome/issues#3215]
### The problem

The TCA9548A does not select channels properly. 

Reason: tca9548a.cpp - line44:   '**auto err = this->write_register(0x70, &channel_val, 1);**' needs to be replaced with: '**auto err = this->write(&channel_val, 1);**'

The TCA9548A does not have a register to address. The channel_mask is written to the to the chip address (default 0x70).
Function '**write_register(0x70...)**' in '**switch_to_channel(channel)**' causes  a write command _0x70 TX 0x70 channel_mask_ 
 (2 bytes) but it should be _0x70 TX channel_mask_ (1 byte).
Best regards
  Juergen

### Which version of ESPHome has the issue?

V2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

any

### What platform are you using?

ESP32

### Board

ESP32 D1 Mini

### Component causing the issue

TCA9548A I2C Multiplexer

### Example YAML snippet

```yaml
tca9548a:
  - address: 0x70
    id: multiplex0
    i2c_id: i2c0
    channels:
      - bus_id: multiplex0channel0
        channel: 0
      - bus_id: multiplex0channel1
        channel: 1
.
.
.
```

### Additional information

The TCA9548A does not have a register to address but only to write the channel mask to the chip address (default 0x70).
As it is right now they 'switch_to_channel (channel)' function causes  a write command _0x70 TX 0x70 (channel_mask)_ instead of _0x70 TX (channel_mask)_.
