### ISSUE TITLE
Compilation fails when using Template Switch with Switch Condition

### ISSUE THREAD

**Issue by brandond** [esphome/issues#322]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
virtualenv + pip

**ESP (ESP32/ESP8266, Board/Sonoff):**
esp8266

**Affected component:**
Template switch

**Description of problem:**

Compilation fails on a set of template switches and on-boot actions that worked under 1.12

```
src/main.cpp: In function 'void setup()':
src/main.cpp:350:69: error: no matching function for call to 'esphome::switch_::SwitchCondition<>::SwitchCondition(esphome::template_::TemplateSwitch*&)'
switch__switchcondition = new switch_::SwitchCondition<>(template0);
```

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: plug00
  platform: ESP8266
  board: esp01_1m
  arduino_version: 2.5.1
  board_flash_mode: dout
  build_path: esp8266
  on_boot:
    if:
      condition:
        switch.is_on: template0
      then:
        light.turn_on: led0_light
      else:
        light.turn_off: led0_light

wifi:
  ssid: 'x'
  password: 'x'
  fast_connect: True

mqtt:
  broker: 'x'

logger:
  level: DEBUG

debug:

ota:

sensor:
  - platform: wifi_signal
    name: "Smart Plug 00 WiFi Signal"
    filters:
      - sliding_window_moving_average:
          window_size: 4
          send_every: 4

switch:
 - platform: gpio
   id: switch0
   restore_mode: RESTORE_DEFAULT_OFF
   pin:
     number: 14
     mode: OUTPUT
 - platform: template
   id: template0
   icon: "mdi:power-plug"
   name: "Smart Plug 00 Power"
   restore_state: True
   turn_off_action:
     - light.turn_off: led0_light
     - switch.turn_off: switch0
   turn_on_action:
     - light.turn_on: led0_light
     - switch.turn_on: switch0
   lambda: "return id(switch0).state;"

binary_sensor:
  - platform: gpio
    id: button0
    pin:
      number: 4
      mode: INPUT
      inverted: True
    on_click:
      then:
        switch.toggle: template0

status_led:
  pin:
    number: 12
    mode: OUTPUT
    inverted: True

output:
  - platform: esp8266_pwm
    id: led0_output
    pin:
      number: 13
      mode: OUTPUT
      inverted: True

light:
  - platform: monochromatic
    id: led0_light
    output: led0_output
    default_transition_length: 0.5s
```

**Comment by davericher** [comment]
Can confirm on a Wemos D1 Mini, Latest Dev Docker image

```YAML
## BEGIN CONFIGURATION ##
substitutions:
  ## BOOTSTRAP
  <<: !include includes/common/substitutions.yaml
  ## Hardware
  <<: !include includes/hardware/nodemcuesp8266.yaml
  ## Identity
  room: office
  upper_room: Office
  devicename: square2
  upper_devicename: Square2
  static_ip: 192.168.1.200
  logger_level: DEBUG

esphome:
  name: $devicename
  platform: $platform
  board: $board
  build_path: builds/${devicename}
  arduino_version: $arduino
status_led:
  pin:
    number: $status_led
    inverted: True
wifi:
  ssid: !secret primary_ap
  password: !secret primary_ap_psk
  manual_ip:
    static_ip: $static_ip
    gateway: $gateway
    subnet: $subnet
    dns1: $dns1
    dns2: $dns2
api:
logger:
  level: $logger_level
ota:
  password: !secret ota_password

i2c:
  sda: D5
  scl: D6

display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    id: lcd
    lambda: |-
      it.printf("%f", id(ultra).has_state() && !isnan(id(ultra).state) ? id(ultra).state : -1);

# Sensors
binary_sensor:
  - <<: !include includes/common/statusBinarySensor.yaml

# Text Sensor
text_sensor:
  - <<: !include includes/common/versionTextSensor.yaml
  - <<: !include includes/common/wifiInfoTextSensor.yaml

# Sensors
sensor:
  - <<: !include includes/common/wifiSignalSensor.yaml
  - <<: !include includes/common/uptimeSensor.yaml
  - platform: ultrasonic
    id: ultra
    trigger_pin: D1
    echo_pin: D2
    name: "${upper_room} Ultrasonic Sensor"
    update_interval: 10s
    timeout: 5m
    on_value:
      then:
        - component.update: lcd
        - if:
            condition:
              - lambda: 'return id(ultra).has_state() && !isnan(id(ultra).state) && id(ultra).state <= 0.7;'
              - switch.is_off: psu
            then:
              - switch.turn_on: psu
            else:
              - if:
                  condition:
                    - lambda: 'return isnan(id(ultra).state) || ( id(ultra).has_state() && id(ultra).state > 0.7);'
                    - switch.is_on: psu
                  then:
                    - switch.turn_off: psu

# Individual switches
switch:
  - <<: !include includes/common/restartSwitch.yaml
  - <<: !include includes/common/shutdownSwitch.yaml
  - platform: gpio
    id: psu
    pin:
      number: D3
      inverted: yes
    name: "Workdesk power_supply"
    restore_mode: RESTORE_DEFAULT_OFF
```
![image](https://user-images.githubusercontent.com/6945951/58377828-40f21500-7f57-11e9-96cf-03e0cfa453d7.png)
