### ISSUE TITLE
ADC Resolution on ESP32

### ISSUE THREAD

**Issue by benquan** [esphome/issues#3221]
### The problem

I am reading a sensor whose current output is 2.4V. I connected it to a Wroom ESP32 dev board. I set the configuration to show me raw values (0 - 4095). and this is my configuration file:

```
sensor:

# TANK
  - platform: adc
    pin: GPIO35
    attenuation: 11db #ESP32 defaults to 0db measuring 0-1V, 11db = 0-3.9V
    update_interval: 5s
    id: water
    # accuracy_decimals: 1
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    name: "Water Tank"
    state_class: "measurement"
    raw: true
```

And these are the result readings:
<img width="1141" alt="Screen Shot 2022-04-15 at 10 45 26 AM" src="https://user-images.githubusercontent.com/3030645/163655671-29f9a83b-1ba3-4662-991b-a0624595314c.png">

My question is, why are the readings 512 points or 256 points apart? Why am I not getting the full 4095 points of detail? If its noice I would expect random numbers around 3500 but not stepped values.

256 point steps would be equivalent to a 4-bit resolution instead of the full 12 bit .

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.4.4

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

ADC

### Example YAML snippet

```yaml
sensor:

# TANK
  - platform: adc
    pin: GPIO35
    attenuation: 11db #ESP32 defaults to 0db measuring 0-1V, 11db = 0-3.9V
    update_interval: 5s
    id: water
    # accuracy_decimals: 1
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    name: "Water Tank"
    state_class: "measurement"
    raw: true
```
