### ISSUE TITLE
Web server (version: 2) showing wrong state/min/max on slider when sensors are on other than alphabetical order on YAML

### ISSUE THREAD

**Issue by savikko** [esphome/issues#3222]
### The problem

I have three Template Number sensors, which have this kind of config:
```yaml
  - platform: template
    name: "Sensor name"
    id: sensor_1
    optimistic: true
    restore_value: yes
    initial_value: 108
    min_value: 72
    max_value: 120
    step: 1
    mode: slider
```

On webserver version: 2 it shows sliders and I can control those but position of slider is off:
![image](https://user-images.githubusercontent.com/7020294/163674064-f29f65c7-4ae8-4438-9cf8-9fa6e6c00ef6.png)

Seems, that if min_value is something more than 0 or 1, it cannot determine right position for slider "handle".

Still, setting value via slider works.

### Which version of ESPHome has the issue?

2022.4.0b2

### What type of installation are you using?

pip

### What platform are you using?

ESP32

**Comment by jesserockz** [comment]
I am unable to reproduce this. I copied your template number yaml and the slider works as expected. When loading the page it starts in the correct position.

**Comment by savikko** [comment]
Thanks for taking time to investigate this.

I played with this a little bit more.

I originally used Edge (chromium based) and now tested Chrome and Firefox. Same happens on both.
From Devtools I see that input has correct value:
![image](https://user-images.githubusercontent.com/7020294/163939457-44e4f5cd-c55a-4c30-b889-7f4a949ad882.png)

Slider is still off. If I manually change the value (to html), slider goes to right position.

But then, if I am on the page and I change the value from Home Assistant, then ESPHome UI updates correctly.

So it kinda seems that this is only related to first load of the page. Not sure yet how to debug this more.

**Comment by savikko** [comment]
Little bit extra info:
When I first load this page, slider is on the left (at incorrect position).
Then, when I change the value from outside (on this case Home Assistant), slider moves to correct position.
Then it moves correctly but if I then move slider within ESPHome Webserver UI, it changes the value correctly but after this changes from Home Assistant does not reflect to slider position.
Value (column `State`) changes correctly.

**Comment by savikko** [comment]
I think this is somehow related to alphabetical ordering on Webserver UI.

You should be able to reproduce this issue with this kind of entities:
```
number:
  - platform: template
    name: "Third number"
    id: number_3
    optimistic: true
    min_value: 72
    max_value: 120
    initial_value: 90
    step: 0.1
    mode: slider
  - platform: template
    name: "Second number"
    id: number_2
    optimistic: true
    min_value: 1
    max_value: 15
    initial_value: 5
    step: 0.1
    mode: slider
  - platform: template
    name: "First number"
    id: number_1
    optimistic: true
    initial_value: 80
    min_value: 72
    max_value: 120
    step: 1
    mode: slider
```

That should result this:
![image](https://user-images.githubusercontent.com/7020294/163952490-a1517a18-8d6b-4639-89e9-1aadd74faffd.png)

Then, if you change name "First number" to "XFirst number", we get this:
![image](https://user-images.githubusercontent.com/7020294/163952780-33a20fe1-82e7-49a3-bd3e-43927c19dc86.png)

So now the "XFirst number" is ok but "Second number" is totally off.
