### ISSUE TITLE
SSD1306 i2c OLED contrast zero no longer turns off display

### ISSUE THREAD

**Issue by cbhiii** [esphome/issues#3223]
### The problem

When the contrast of the display is set to zero using either the `platform` settings or by using `on_value ... set_contrast(x)` from a sensor, the display will not turn off as it has in the past.

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.4.4

### What platform are you using?

ESP8266

### Board

d1 mini (esp8266mod)

### Component causing the issue

sd1306_i2c

### Example YAML snippet

```yaml
esphome:
  name: bedroom-dresser
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "-"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Dresser Fallback Hotspot"
    password: "-"

captive_portal:

time:
  - platform: homeassistant
    id: esptime
    
sensor:
  - platform: homeassistant
    id: decimal_time
    entity_id: sensor.decimal_time
    internal: true

  - platform: homeassistant
    id: outside
    entity_id: sensor.wx_temperature
    internal: true

  - platform: homeassistant
    id: inside
    entity_id: sensor.bedroom_temperature
    internal: true

  - platform: homeassistant
    id: days
    entity_id: sensor.chuck_days_on_earth
    internal: true

  - platform: wifi_signal
    name: "Bedroom dresser WiFi signal"
    update_interval: 60s

  - platform: bh1750
    id: light
    name: "Bedroom illuminance"
    address: 0x23
    update_interval: 2s
    #
    # set OLED display contrast based on lx illumination
    #
    on_value:
      then:
        lambda: id(oled).set_contrast(x);

  - platform: dht
    pin: D4
    temperature:
      name: "Bedroom temperature"
      filters:
        - calibrate_linear:
            - 12 -> 6.1
            - 25.8 -> 19.44
    humidity:
      name: "Bedroom humidity"
      filters:
        - calibrate_linear:
            - 0 -> 0
            - 31 -> 35
            - 28 -> 46
    update_interval: 60s

font:
  - file: "fonts/Tahoma.ttf"
    id: font1
    size: 10
  - file: "fonts/Tahoma-Bold.ttf"
    id: font2
    size: 16
  - file: "fonts/Tahoma.ttf"
    id: font3
    size: 18

i2c:
  scl: D2
  sda: D1

display:
  - platform: ssd1306_i2c
    id: oled
    model: "SSD1306 128x64"
    reset_pin: D0
    contrast: 1%
    update_interval: 2s
    lambda: |-
      it.strftime(67, -4, id(font2), TextAlign::TOP_CENTER, "%u", id(esptime).now());
      it.printf(127, -4, id(font2), TextAlign::TOP_RIGHT , "%.0f", id(decimal_time).state);
      it.printf(0, -4, id(font2), TextAlign::TOP_LEFT, "%.0f", id(days).state);
      it.rectangle(0, 16, 127, 48);
      it.line(63, 16, 63, 63);
      it.line(0, 39, 127, 39);
      it.printf(31, 27, id(font2), TextAlign::CENTER , "%.0f F", id(outside).state);
      it.printf(61, 18, id(font1), TextAlign::TOP_RIGHT , "O");
      it.printf(95, 27, id(font2), TextAlign::CENTER , "%.0f LX", id(light).state);
      it.printf(31, 51, id(font2), TextAlign::CENTER , "%.0f F", id(inside).state);
      it.printf(61, 41, id(font1), TextAlign::TOP_RIGHT , "I");
      it.strftime(95, 51, id(font2), TextAlign::CENTER, "%H:%M", id(esptime).now());
```

### Anything in the logs that might be useful for us?

```txt
no
```

### Additional information

This worked fine in the past few weeks, but I'm not able to notice when the change occurred.

I did some testing with other parameters and would love for it to be just a user error situation, but I don't think it is.

Thank you for the help with this.
