### ISSUE TITLE
Filters are not working with the Senseair Sensor.

### ISSUE THREAD

**Issue by darkxst** [esphome/issues#3228]
### The problem

I running a Senseair Co2 sensor, however for this component I can't seem to apply any filters such as moving average etc. It results in a build error about filters being invalid option

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.4

### What platform are you using?

ESP32

### Board

esp32-devkitC and Senseair S8

### Component causing the issue

senseair

### Example YAML snippet

```yaml
  - platform: senseair
    co2:
      name: "SenseAirL8"
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/climate-mu.yaml...
Failed config

sensor.senseair: [source /config/esphome/climate-mu.yaml:60]
  platform: senseair
  co2: 
    name: SenseAirL8
  update_interval: 60s
  
  [filters] is an invalid option for [sensor.senseair]. Please check the indentation.
  filters:  [source /config/esphome/climate-mu.yaml:66]
    - sliding_window_moving_average: 
        window_size: 15
        send_every: 15
```

**Comment by davidbb** [comment]
Filters need to go into the co2 YAML block as follows:

```
  - platform: senseair
    co2:
      name: "SenseAirL8"
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
    update_interval: 60s
```
