### ISSUE TITLE
ESP32 crashes when  webserver is displayed and using pulse_counter.

### ISSUE THREAD

**Issue by fpovoski** [esphome/issues#3230]
### The problem

Frequent resets when using webserver and pulse counter.  D1 Mini32 is supplied by 3A 5v supply.  No power related issues observed. Processor appears as having a high load when Webserver is accessed as it reports slow and without complete results.

### Which version of ESPHome has the issue?

2022.3.2 Apr 19 2022

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

MQTT/NODE-RED

### What platform are you using?

ESP32

### Board

D1 Mini 32

### Component causing the issue

We

### Example YAML snippet

```yaml
esphome:
  name: hwheater
  platform: ESP32
  board: wemos_d1_mini32
#  includes:
#    - hwheater/src/water_flow.h
    
ota:
  password: "trek6666"

wifi:
  ssid: "hill"
  password: "trek6666"
  fast_connect: true
  manual_ip:
    static_ip: 192.168.0.190
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.1
    dns2: 8.8.8.8
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HWheater Fallback Hotspot"
    password: "trek6666"
    

captive_portal:

globals:
  - id: my_global_int
    type: int
    restore_value: no
    initial_value: '0'


mqtt:
  broker: 192.168.0.100
  username: "john"
  password: "trek6666"
  
  on_message:
    - topic: hwheater/switch/hwheater_water_valve_closed/command
      payload: 'ON'
      then:
        - lambda: |-
           id(my_global_int) += 1;

esp32_ble_beacon:
  type: iBeacon
  uuid: 'c29ce823-e67a-4e71-bff2-abaa32e77a98'

web_server:
  port: 80

logger:
  level: Verbose
  
binary_sensor:
  - platform: status
    name: "HWheater Status"

sensor:

  - platform: ntc
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 50kOhm
    name: "HWheater Temperature"

  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 51kOhm
#    name: "HWheater Resistance Sensor"

  - platform: adc
    id: source_sensor
    pin: A0
    attenuation: auto
    update_interval: never
#    name: "HWheater ADC"
   
#  - platform: pulse_meter
#    pin: GPIO17
#    name: "HWheater Pulse Meter"
#    timeout: 5ms
#    internal_filter: 10ms
#    filters:
#       - heartbeat: 1s
#      - throttle_average: 1s
#       
#    total:
#      name: "HWheater Pulse Meter Total"
#      filters:
#        - throttle: 10s

  - platform: pulse_counter
    pin: GPIO17
    name: "HWheater Pulse Counter"
    update_interval: 1s
    total:
      name: "HWheater Pulse Total"
        
  - platform: wifi_signal
    name: "HWheater WiFi"
    update_interval: 30s
 
  - platform: uptime
    name: "HWheater Uptime"
    update_interval: 30s

interval:
  - interval: 30s
    then:
      - switch.turn_on: ntc_vcc
      - component.update: source_sensor
      - switch.turn_off: ntc_vcc  
  - interval: 60s
    then:
      - mqtt.publish:
          topic: hwheater/count
          payload: !lambda |-
            return to_string(id(my_global_int));

switch:
  - platform: restart
    name: "HWheater Restart"

  - platform: gpio
   # name: "HWheater Thermistor Power"
    pin: GPIO26
    restore_mode: ALWAYS_OFF
    id: ntc_vcc
  
  - platform: gpio
    name: "HWheater Water Valve Closed"
    restore_mode: ALWAYS_OFF
    pin: GPIO16
    
text_sensor:
  - platform: template
    name: "HWheater Device Sensor"
    lambda: |-
      return {"D1 Mini32"};
  - platform: version
    name: "HWheater Version"
  - platform: wifi_info
    ip_address:
      name: "HWheater IP Address"
    ssid:
      name: "HWheater Connected SSID"
    bssid:
      name: "HWheater Connected BSSID"
    mac_address:
      name: "HWheater Mac Wifi Address"
```

### Anything in the logs that might be useful for us?

```txt
15:23:34	[V]	[mqtt:405]	
Publish(topic='hwheater/sensor/hwheater_pulse_counter/state' payload='0.00' retain=1)
15:23:34	[D]	[pulse_counter:168]	
'HWheater Pulse Counter': Total : 0 pulses
15:23:34	[V]	[mqtt:405]	
Publish(topic='hwheater/sensor/hwheater_pulse_total/state' payload='0' retain=1)
15:23:34	[V]	[mqtt:405]	
Publish(topic='hwheater/sensor/hwheater_pulse_total/state' payload='0' retain=1)
15:23:34	[V]	[component:199]	
Component pulse_counter.sensor took a long time for an operation (0.07 s).
15:23:34	[V]	[component:200]	
Components should block for at most 20-30ms.
15:23:35	[D]	[pulse_counter:162]	
'HWheater Pulse Counter': Retrieved counter: 0.00 pulses/min
15:23:35	[V]	[sensor:074]	
'HWheater Pulse Counter': Received new state 0.000000

FREEZES HERE AND RESETS.

Also getting this error:

15:24:56	[E]	[json:034]	
Could not allocate memory for JSON document! Requested 5120 bytes, largest free heap block: 38656 bytes
15:24:56	[E]	[json:034]	
Could not allocate memory for JSON document! Requested 5120 bytes, largest free heap block: 38656 bytes
```

### Additional information

It appears the pulse counter freezes forcing a reset.
