### ISSUE TITLE
exception occur by Setting up BME680 via BSEC...

### ISSUE THREAD

**Issue by heizie** [esphome/issues#3231]
### The problem
- components
I've built up a terminal which based on Wemos D1 Mini. It is connected with a BME 680 sensor, an ssd1306 OLED, two led for showing doors' states and a button (with a 10 kOhm physical pull up sensor).
Both BME 680 and ssd 1306 OLED are using the same pin for i2c connetction.
- issue
everything seems fine in a couple days. but it will crash suddenly and the state-led blick fast (about 4-5 times per second)
I connect it to my PC and download the logs (pls see followings)

- how i could solve it temporary
re-flash the firmware via usb with same configuartion, but it will break down again after some days

full error log:
[logs.txt](https://github.com/esphome/issues/files/8519780/logs.txt)

more details:
https://heizie.github.io/posts/table_terminal/

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

BME 680 or i2c

### Example YAML snippet

```yaml
esphome:
  name: terminal-bedroom

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

font:
  - file: "Ubahn.ttf"
    id: normal_font
    size: 24

globals:
  - id: flag_dis
    type: int
    restore_value: no
    initial_value: '0'
    
# animation:
#   - file: "face.gif"
#     id: display_animation
#     resize: 128x64
#     type: BINARY

binary_sensor:
  - platform: gpio
    pin: 14
    id: display_button
    name: "display button"
    on_press:
      then:
        - if:
            condition:
              lambda: return id(flag_dis) == 0;
            then:
              - display.page.show: page1
              - globals.set:
                  id: flag_dis
                  value: '1'
              - logger.log: "10s timer setted"
              - delay: 10 s
              - display.page.show: page_off
              - globals.set:
                  id: flag_dis
                  value: '0'
              - logger.log: "time's up"
            else :
              display.page.show_next: terminal_display

i2c:
 - id: bus
   sda: 4
   scl: 5
   scan: true
   
bme680_bsec:
    address: 0x76
    temperature_offset: 7
    iaq_mode: static
    sample_rate: ulp
    state_save_interval: 6h

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: terminal_display
    pages:
      - id: page_off
        lambda: |-
            it.fill(COLOR_OFF);
      - id: page1
        lambda: |-
            it.printf(0, 3, id(normal_font), "1. Bus: %.0f min", id(display_181_frist).state);
            it.printf(0, 30, id(normal_font), "2. Bus: %.0f min", id(display_181_second).state);
      - id: page2
        lambda: |-
            it.printf(0, 2, id(normal_font), "temp. %.01f°C", id(room_temperature).state);
            it.printf(0, 30, id(normal_font), "humid. %.01f%%", id(room_humidity).state);
      - id: page3
        lambda: |-
            it.printf(0, 2, id(normal_font), "%s", id(weather_display).state.c_str());
            it.printf(0, 30, id(normal_font), "R.F. %.01f°C", id(display_real_feel).state);
      
      # - id: page3
      #   lambda: |-
      #     id(display_animation).next_frame();
      #     it.image(0, 0, id(display_animation), COLOR_ON, COLOR_OFF);
      # - id: page3
      #   lambda: |-
      #     it.filled_circle(20, 20, 14);
      #     it.filled_circle(108, 20, 14);
      # - id: page4
      #   lambda: |-
      #     it.filled_circle(15, 20, 14);
      #     it.filled_circle(103, 20, 14);
      # - id: page5
      #   lambda: |-
      #     it.filled_circle(25, 20, 14);
      #     it.filled_circle(113, 20, 14);


# interval:
#   - interval: 3s
#     then:
#       - display.page.show_next: terminal_display
#       - component.update: terminal_display

text_sensor:
  - platform: homeassistant
    id: weather_display
    entity_id: weather.lillweg_13

  - platform: bme680_bsec
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"
        
sensor:
  - platform: homeassistant
    id: display_181_frist
    entity_id: sensor.first_bus
    internal: true 
  - platform: homeassistant
    id: display_181_second
    entity_id: sensor.second_bus
    internal: true 
    
  - platform: homeassistant
    id: display_real_feel
    entity_id: sensor.lillweg_13_realfeel_temperature
    internal: true
    
  - platform: bme680_bsec
    temperature:
      # Temperature in °C
      name: "BME680 Temperature"
      id: room_temperature
      sample_rate: lp
      filters:
        - median
    pressure:
      # Pressure in hPa
      name: "BME680 Pressure"
      sample_rate: lp
      filters:
        - median
    humidity:
      # Relative humidity %
      name: "BME680 Humidity"
      id: room_humidity
      sample_rate: lp
      filters:
        - median
    gas_resistance:
      # Gas resistance in Ω
      name: "BME680 Gas Resistance"
      filters:
        - median
    iaq:
      # Indoor air quality value
      name: "BME680 IAQ"
      filters:
        - median
    iaq_accuracy:
      # IAQ accuracy as a numeric value of 0, 1, 2, 3
      name: "BME680 Numeric IAQ Accuracy"
    co2_equivalent:
      # CO2 equivalent estimate in ppm
      name: "BME680 CO2 Equivalent"
      filters:
        - median
    breath_voc_equivalent:
      # Volatile organic compounds equivalent estimate in ppm
      name: "BME680 Breath VOC Equivalent"
      filters:
        - median
        
light:
  - platform: binary
    id: bathroom_state
    name: "bathroom state"
    output: bathroom_output
    
  - platform: binary
    id: toilet_state
    name: "toilet state"
    output: toilet_output
    
status_led:
  pin: 
    number: 2
    inverted: true

output:
  - id: bathroom_output
    platform: gpio
    pin: GPIO12
    
  - id: toilet_output
    platform: gpio
    pin: GPIO13
    

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Terminal bedroom"
    password: " "

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
[C][status_led:014]: Setting up Status LED...
[C][ota:461]: There have been 0 suspected unsuccessful boot attempts.
[I][app:029]: Running through setup()...
[I][i2c.arduino:161]: Performing I2C bus recovery
[D][binary_sensor:034]: 'display button': Sending initial state ON
[C][light:036]: Setting up light 'bathroom state'...
[D][light:035]: 'bathroom state' Setting:
[D][light:040]:   Color mode: 
[C][light:036]: Setting up light 'toilet state'...
[D][light:035]: 'toilet state' Setting:
[D][light:040]:   Color mode: 
[C][bme680_bsec.sensor:016]: Setting up BME680 via BSEC...

User exception (panic/abort/assert)
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Panic core_esp8266_main.cpp:215 loop_task

>>>stack>>>

ctx: sys
sp: 3fffeee0 end: 3fffffb0 offset: 0000
3fffeee0:  40241c44 0000009e 3fff1e8c 40241c77  
3fffeef0:  000000fe 00000000 00000000 00000000  
3fffef00:  00000000 00000000 00000000 3fff1978  
3fffef10:  40000000 3fffd9d0 00026d3b 3fff1930  
3fffef20:  3fffdad0 00000000 3ffe85e0 4022e2be  
3fffef30:  40268c52 3fffdab0 00000000 4022e32b  
3fffef40:  00000000 3fffdad0 3fff1930 4022dc68  
3fffef50:  40000f49 40000f65 3fffdab0 40000f49  
3fffef60:  40000e19 0007d3bd 00000000 00000005  
3fffef70:  00000000 aa55aa55 000000ed 40105ab1  
3fffef80:  40105ab7 00000000 00000005 401011ec  
3fffef90:  4010000d d896ddef 0007d3bd 401000ac  
3fffefa0:  40259268 3fffef3c 40259219 3ffff1a8  
3fffefb0:  00000003 00000000 0000000a 00000000  
3fffefc0:  00000003 00000000 0000000a 00000000  
3fffefd0:  feefeffe feefeffe feefeffe feefeffe  
3fffefe0:  00000000 a0000000 00000000 0000001c  
3fffeff0:  00003000 feefeffe 00003000 3ffe8368  
3ffff000:  00000000 00000004 3ffff170 4023b244  
3ffff010:  3ffff100 3ffff103 00000000 feefeffe  
3ffff020:  feefeffe feefeffe 40236b45 3ffe8368  
3ffff030:  00000003 00000000 3ffff170 4023b244  
3ffff040:  4023b180 3ffff100 00000003 00000000  
3ffff050:  feefeffe feefeffe feefeffe 3ffff170  
3ffff060:  3ffe95c9 00000000 3ffff0c0 40236c74  
3ffff070:  00000003 feefeffe feefeffe 3ffe8368  
3ffff080:  00000003 00000000 3ffff170 4023b244  
3ffff090:  00000000 3ffe95c9 00000003 00000000  
3ffff0a0:  feefeffe feefeffe feefeffe 3ffe95c9  
3ffff0b0:  3fff281c 00000000 3ffff170 4023b445  
3ffff0c0:  00000004 ffffffff ffffffff 3ffe8368  
3ffff0d0:  0000000c 00000000 3ffff1c0 4023b244  
3ffff0e0:  feefeffe 3fff281c 0000000c feefeffe  
3ffff0f0:  feefeffe feefeffe feefeffe 3fff281c  
3ffff100:  3fff2828 00000000 3ffff1c0 4023b445  
3ffff110:  feefeffe feefeffe 00000000 feefeffe  
3ffff120:  3ffff260 0000000c 00302018 feefeffe  
3ffff130:  3ffff260 3ffff250 00000008 3ffe8368  
3ffff140:  00000003 00000003 333bbd2e 2689aded  
3ffff150:  26f80000 3fc90fdb feefeffe 3ffe929e  
3ffff160:  00000003 3ffe8368 000001f3 402388e9  
3ffff170:  3ffff310 3ffff300 00000010 ffff0208  
3ffff180:  3ffff310 3ffff300 00000010 3ffe8368  
3ffff190:  00000000 00000000 00000001 40100548  
3ffff1a0:  00000008 3ffff200 3fff2829 00000034  
3ffff1b0:  00000000 fffffffc 4022dd73 3fffefa0  
3ffff1c0:  3fff2859 3f800000 000001c2 4022ddb8  
3ffff1d0:  00000000 00000034 3fff2829 4022f770  
3ffff1e0:  3fff285d 3fff27d4 000001f3 40238925  
3ffff1f0:  3ffff260 3ffff250 00000008 3ffe929e  
3ffff200:  4022ab74 3fff2829 3fff1768 4022ab80  
3ffff210:  4022ab74 3fff2829 3fff1768 4022bc4c  
3ffff220:  00000003 3fff2829 3fff1768 4022bc70  
3ffff230:  00000012 3fff27d4 000001cf 4022bf05  
3ffff240:  3ffff310 3fff2829 3fff27d4 402132b1  
3ffff250:  75307530 3ffffb30 3ffe9629 3ffe9614  
3ffff260:  3ffe929e 0000018a 3fff1030 402131a8  
3ffff270:  3ffff310 3ffff300 00000010 3ffe929e  
3ffff280:  00000003 00000000 3fff27d4 4021346d  
3ffff290:  0000000d 0000018a 3fff1210 40204a2a  
3ffff2a0:  00000008 00000008 00000000 3ffffb38  
3ffff2b0:  3fff30fc 3ffffb37 3ffe929e 4021d12c  
3ffff2c0:  3ffff310 3ffff300 00000010 402019d0  
3ffff2d0:  3ffff2e0 3fff5acc 00000000 4021d158  
3ffff2e0:  3ffff310 3ffff300 00000010 4020f70a  
3ffff2f0:  3ffff310 3ffff300 00000010 4020f361  
3ffff300:  0000008b 3ffffb37 64300b86 3ffffb38  
3ffff310:  41cb2d34 00000000 64300b86 402010dc  
3ffff320:  3fff30fc 3ffffb37 64300b86 4020d93d  
3ffff330:  400a0008 41cb2d34 0000cccb 00000000  
3ffff340:  538c44d9 00000101 dada7530 40400000  
3ffff350:  40400000 012c0000 3efffee5 00000802  
3ffff360:  3ffffbf0 3fff1030 3ffff3e0 00000800  
3ffff370:  3ffffbf0 3fff1030 3ffff3e0 40201920  
3ffff380:  3ffff390 feefeffe feefeffe feefeffe  
3ffff390:  000000e5 000001be 00000000 feefeffe  
3ffff3a0:  000001be 000001c6 feefeffe feefeffe  
3ffff3b0:  feefeffe feefeffe feefeffe 3fff56d8  
3ffff3c0:  3fff30fc 0000000a 3fff30fc 402010b8  
3ffff3d0:  feefeffe feefeffe feefeffe 4020d590  
3ffff3e0:  00fe00e5 30050102 2c006475 97177001  
3ffff3f0:  c5038407 90045c00 40014001 30019001  
3ffff400:  30753075 64753075 64006400 30753000  
3ffff410:  64753075 30006400 64753075 64006400  
3ffff420:  30006400 30753075 64006475 30006400  
3ffff430:  64753075 2c006400 2c012c01 2c012c01  
3ffff440:  2c012c01 2c012c01 2c012c01 2c012c01  
3ffff450:  08012c01 08070807 08070807 08070807  
3ffff460:  08070807 08070807 08070807 70070807  
3ffff470:  70177017 70177017 70177017 70177017  
3ffff480:  70177017 70177017 ff177017 ffffffff  
3ffff490:  dcffffff dc05dc05 ffffff05 dcffffff  
3ffff4a0:  ff05dc05 ffffffff ffffffff ffffffff  
3ffff4b0:  ffffffff ffffffff ffffffff ffffffff  
3ffff4c0:  30ffffff feefef75 feefeffe feefeffe  
3ffff4d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff500:  feefeffe feefeffe feefeffe feefeffe  
3ffff510:  feefeffe feefeffe feefeffe feefeffe  
3ffff520:  feefeffe feefeffe feefeffe feefeffe  
3ffff530:  feefeffe feefeffe feefeffe feefeffe  
3ffff540:  feefeffe feefeffe feefeffe feefeffe  
3ffff550:  feefeffe feefeffe feefeffe feefeffe  
3ffff560:  feefeffe feefeffe feefeffe feefeffe  
3ffff570:  feefeffe feefeffe feefeffe feefeffe  
3ffff580:  feefeffe feefeffe feefeffe feefeffe  
3ffff590:  feefeffe feefeffe feefeffe feefeffe  
3ffff5a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff600:  feefeffe feefeffe feefeffe feefeffe  
3ffff610:  feefeffe feefeffe feefeffe feefeffe  
3ffff620:  feefeffe feefeffe feefeffe feefeffe  
3ffff630:  feefeffe feefeffe feefeffe feefeffe  
3ffff640:  feefeffe feefeffe feefeffe feefeffe  
3ffff650:  feefeffe feefeffe feefeffe feefeffe  
3ffff660:  feefeffe feefeffe feefeffe feefeffe  
3ffff670:  feefeffe feefeffe feefeffe feefeffe  
3ffff680:  feefeffe feefeffe feefeffe feefeffe  
3ffff690:  feefeffe feefeffe feefeffe feefeffe  
3ffff6a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff700:  feefeffe feefeffe feefeffe feefeffe  
3ffff710:  feefeffe feefeffe feefeffe feefeffe  
3ffff720:  feefeffe feefeffe feefeffe feefeffe  
3ffff730:  feefeffe feefeffe feefeffe feefeffe  
3ffff740:  feefeffe feefeffe feefeffe feefeffe  
3ffff750:  feefeffe feefeffe feefeffe feefeffe  
3ffff760:  feefeffe feefeffe feefeffe feefeffe  
3ffff770:  feefeffe feefeffe feefeffe feefeffe  
3ffff780:  feefeffe feefeffe feefeffe feefeffe  
3ffff790:  feefeffe feefeffe feefeffe feefeffe  
3ffff7a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff800:  feefeffe feefeffe feefeffe feefeffe  
3ffff810:  feefeffe feefeffe feefeffe feefeffe  
3ffff820:  feefeffe feefeffe feefeffe feefeffe  
3ffff830:  feefeffe feefeffe feefeffe feefeffe  
3ffff840:  feefeffe feefeffe feefeffe feefeffe  
3ffff850:  feefeffe feefeffe feefeffe feefeffe  
3ffff860:  feefeffe feefeffe feefeffe feefeffe  
3ffff870:  feefeffe feefeffe feefeffe feefeffe  
3ffff880:  feefeffe feefeffe feefeffe feefeffe  
3ffff890:  feefeffe feefeffe feefeffe feefeffe  
3ffff8a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff900:  feefeffe feefeffe feefeffe feefeffe  
3ffff910:  feefeffe feefeffe feefeffe feefeffe  
3ffff920:  feefeffe feefeffe feefeffe feefeffe  
3ffff930:  feefeffe feefeffe feefeffe feefeffe  
3ffff940:  00000004 00000000 0000000a 00000000  
3ffff950:  00000004 00000000 0000000a 00000000  
3ffff960:  feefeffe feefeffe feefeffe feefeffe  
3ffff970:  00000000 00000000 0000001f 40100548  
3ffff980:  00004000 feefeffe 3fffc228 40106249  
3ffff990:  4000050c 00000001 3ffffb00 4023b244  
3ffff9a0:  40106f25 00000030 0000001b ffffffff  
3ffff9b0:  4022e606 0000008e 00000027 00cffc30  
3ffff9c0:  e0034025 00000001 4020ca28 00000001  
3ffff9d0:  ffffffff 3fffc6fc 00000001 3fff197c  
3ffff9e0:  00000001 3fff197c 3fff1638 00000030  
3ffff9f0:  3ffe95c9 3ffffae3 00000000 40236c74  
3ffffa00:  00000002 3ffffaca 00000001 3ffe8368  
3ffffa10:  00000000 00000000 3ffffb50 4023b244  
3ffffa20:  4023b180 4027264c 00000000 00000000  
3ffffa30:  00000000 00000000 0000001f 40100548  
3ffffa40:  4027264c 00000000 3fffc228 40106249  
3ffffa50:  3ffffa90 00000000 00000015 0000079b  
3ffffa60:  3fff1430 477fff00 0000ffff 00000015  
3ffffa70:  3fff197c 7ff6bae1 00000023 00000002  
3ffffa80:  3fff1030 0000012c 3ffffb00 40201c30  
3ffffa90:  7530ffff 75307530 012cffff 7530ffff  
3ffffaa0:  ffffffff 012c012c ffffffff 4022e56d  
3ffffab0:  3eaaaaab 00000018 00800000 3ffffb20  
3ffffac0:  00000007 3ffffbd0 00000001 3ffffb90  
3ffffad0:  3ac800c8 00000002 3ffffb10 4022a1c6  
3ffffae0:  00000001 00000001 3ffffb30 3fff56d8  
3ffffaf0:  3ffffb50 3fff30fc 00000007 4020106d  
3ffffb00:  00000000 00000001 3ffffb38 40210108  
3ffffb10:  000000e0 00b2d8f2 00000000 4020d6d0  
3ffffb20:  3b5a737e 00000002 3b5a737e 40231d03  
3ffffb30:  01040800 0000003d 00000000 00000073  
3ffffb40:  4001002d 409a334f 409a45b1 4096a53e  
3ffffb50:  4095efea 00000000 dada7530 40400000  
3ffffb60:  40400000 012c0000 3efffee5 02000c02  
3ffffb70:  60433240 6073d542 03001042 8eeee140  
3ffffb80:  cb333340 a01aa041 05001641 6c3f0040  
3ffffb90:  00cccb89 00000000 8c44d900 0c010153  
3ffffba0:  00400900 cb896c3f 080000cc 34400a00  
3ffffbb0:  0041cb2d 09dad000 3b000073 1cff2616  
3ffffbc0:  00000024 00000063 00000064 78142d18  
3ffffbd0:  e065bd08 a912e8c2 00002300 3fff56d8  
3ffffbe0:  3fff30fc 0000000a 3fff30fc 4020d9e9  
3ffffbf0:  01040800 0000003d 00000000 000001ae  
3ffffc00:  00010030 4913a800 4c773140 44e10000  
3ffffc10:  bf004189 becccccd bf400000 be947ae1  
3ffffc20:  00000000 640055d8 00000000 00000000  
3ffffc30:  0002001c e101f400 00001900 00004080  
3ffffc40:  01904120 41700000 3f000000 00030010  
3ffffc50:  3ca3d70a 3b23d70a 3b23d70a 00050009  
3ffffc60:  00000000 09005801 22d0e500 0000003e  
3ffffc70:  00000000 9c1bda00 430be13e a0000040  
3ffffc80:  00000040 00000000 484b5e00 9ffe5dbd  
3ffffc90:  a03e4240 000000bf 00000000 b41f2100  
3ffffca0:  61b08abe 63f14140 000000be 00000000  
3ffffcb0:  4779a700 29bda53d bd1eb8c0 0a000c40  
3ffffcc0:  00000000 00000000 fe00e500 05010200  
3ffffcd0:  00647530 1770012c 03840797 045c00c5  
3ffffce0:  01400190 01900140 75307530 75307530  
3ffffcf0:  00640064 75300064 75307530 00640064  
3ffffd00:  75307530 00640064 00640064 75307530  
3ffffd10:  00647530 00640064 75307530 00640064  
3ffffd20:  012c012c 012c012c 012c012c 012c012c  
3ffffd30:  012c012c 012c012c 012c012c 07080708  
3ffffd40:  07080708 07080708 07080708 07080708  
3ffffd50:  07080708 07080708 17701770 17701770  
3ffffd60:  17701770 17701770 17701770 17701770  
3ffffd70:  17701770 ffffffff ffffffff 05dc05dc  
3ffffd80:  ffff05dc ffffffff 05dc05dc ffffffff  
3ffffd90:  ffffffff ffffffff ffffffff ffffffff  
3ffffda0:  ffffffff ffffffff ffffffff 00007530  
3ffffdb0:  5a5c0000 00000000 00000000 40201048  
3ffffdc0:  3fff5758 0002495c 3fff30fc 4020da32  
3ffffdd0:  3fff2b5c 00000003 3fff0e74 402325f4  
3ffffde0:  3fff5a30 3ffffe00 00000017 402326ac  
3ffffdf0:  3fff5758 00000009 3fff0e74 4021c511  
3ffffe00:  00000017 00000017 3fff5a44 3fff2b74  
3ffffe10:  0000002c 402200a6 00000020 4010123c  
3ffffe20:  3fff30c8 00000000 00000008 3fff2b74  
3ffffe30:  3fff0ffc 3fff0e74 00000001 402200c6  
3ffffe40:  3fff2e6c 00000010 0000001e 00000000  
3ffffe50:  00000000 00000000 00000000 00000000  
3ffffe60:  3ffffe68 0000000c 56573947 6f507761  
3ffffe70:  77303737 00000000 00000000 00000000  
3ffffe80:  00000000 00000000 00000000 00000000  
3ffffe90:  00000000 00000000 3ffffea0 00000002 <
3ffffea0:  00004c32 00000000 00000000 00000000  
3ffffeb0:  00000000 00000000 3fff2dcc 00000016  
3ffffec0:  0000001e 00000000 00000000 00000000  
3ffffed0:  00000000 00000000 00000000 00000000  
3ffffee0:  00000000 00000000 00000000 00000000  
3ffffef0:  3fff59ec 3fff59f0 3fff59f0 00000000  
3fffff00:  3fff595c 3fff5984 3fff59b4 3fffff68  
3fffff10:  00000001 3fff59f0 00000000 3fffff68  
3fffff20:  00000001 3fff59f0 3ffffef0 00000007  
3fffff30:  3fffff0c 00000001 3fffff0c 00000001  
3fffff40:  3fffff0c 00000001 3fffff0c 00000001  
3fffff50:  3fffff0c 00000001 3fffff0c 00000001  
3fffff60:  3fffff0c 00000001 3fff5884 feefeffe  
3fffff70:  3fff0f44 000000cc 3fff0f5c 000000b0  
3fffff80:  3fff0f58 3fff0f54 3ffffef8 3fff0f48  
3fffff90:  feefeffe feefeffe feefeffe 3fff1930  
3fffffa0:  3fffdad0 00000000 3fff191c 4022ddf8  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 3460, room 16 
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4 
tail 4
chksum 0xc9
csum 0xc9
v0007d3c0
~ld
[I][logger:214]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:461]: There have been 1 suspected unsuccessful boot attempts.
[I][app:029]: Running through setup()...
[I][i2c.arduino:161]: Performing I2C bus recovery
[D][binary_sensor:034]: 'display button': Sending initial state ON
[C][light:036]: Setting up light 'bathroom state'...
[D][light:035]: 'bathroom state' Setting:
[D][light:040]:   Color mode: 
[C][light:036]: Setting up light 'toilet state'...
[D][light:035]: 'toilet state' Setting:
[D][light:040]:   Color mode: 
[C][bme680_bsec.sensor:016]: Setting up BME680 via BSEC...

User exception (panic/abort/assert)
.....sth similar....
```
