### ISSUE TITLE
Switch/Button Error with espressif platform

### ISSUE THREAD

**Issue by JohnGalt1717** [esphome/issues#3235]
### The problem
I'm getting this, and it only happens if I add this:

```
switch:
  - platform: restart
    name: "Restart ESP 32"
  - platform: shutdown
    name: "Shutdown ESP 32"

```

```
src/esphome/components/ble_client/ble_client.cpp: In member function 'float esphome::ble_client::BLEClient::parse_char_value(uint8_t*, uint16_t)':
src/esphome/components/ble_client/ble_client.cpp:252:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 2) {
       ^~
src/esphome/components/ble_client/ble_client.cpp:255:5: note: here
     case 0x7:  // uint24.
     ^~~~
src/esphome/components/ble_client/ble_client.cpp:256:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 3) {
       ^~
src/esphome/components/ble_client/ble_client.cpp:259:5: note: here
     case 0x8:  // uint32.
     ^~~~
src/esphome/components/ble_client/ble_client.cpp:260:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 4) {
       ^~
src/esphome/components/ble_client/ble_client.cpp:264:5: note: here
     case 0xC:  // int8.
     ^~~~
src/esphome/components/ble_client/ble_client.cpp:268:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 2) {
       ^~
src/esphome/components/ble_client/ble_client.cpp:271:5: note: here
     case 0xF:  // int24.
     ^~~~
src/esphome/components/ble_client/ble_client.cpp:272:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 3) {
       ^~
src/esphome/components/ble_client/ble_client.cpp:275:5: note: here
     case 0x10:  // int32.
     ^~~~

```
### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

NA

### What platform are you using?

ESP32-IDF

### Board

Node-MCU-32

### Component causing the issue

Switch

### Example YAML snippet

```yaml
esphome:
  name: bmses

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

external_components:
  - source: github://syssi/esphome-jk-bms@main
    refresh: 0s

# Enable Home Assistant API
api:

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

time:
  - platform: homeassistant
    id: homeassistant_time

esp32_ble_tracker:

ble_client:
  - mac_address: xxxxx
    id: battery3
  - mac_address: yyyy
    id: battery4

jk_bms_ble:
  - ble_client_id: battery3
    throttle: 5s
    id: bms3

  - ble_client_id: battery4
    throttle: 5s
    id: bms4

binary_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms3
    balancing:
      name: "BMS 3 balancing"
    charging:
      name: "BMS 3 charging"
    discharging:
      name: "BMS 3 discharging"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms4
    balancing:
      name: "BMS 4 balancing"
    charging:
      name: "BMS 4 charging"
    discharging:
      name: "BMS 4 discharging"


switch:
  - platform: restart
    name: "Restart ESP 32"
  - platform: shutdown
    name: "Shutdown ESP 32"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms3
    charging:
      name: "BMS 3 Charging"
    discharging:
      name: "BMS 3 Discharging"
    balancer:
      name: "BMS 3 Balance"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms4
    charging:
      name: "BMS 4 Charging"
    discharging:
      name: "BMS 4 Discharging"
    balancer:
      name: "BMS 4 Balance"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

  - platform: total_daily_energy
    name: "BMS 3 Total Charging Energy Today"
    power_id: bms_3_charging_power
    unit_of_measurement: kWh
    icon: mdi:counter
    accuracy_decimals: 3
    min_save_interval: 1h
    restore: true
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    name: "BMS 3 Total Discharging Energy Today"
    power_id: bms_3_discharging_power
    unit_of_measurement: kWh
    icon: mdi:counter
    accuracy_decimals: 3
    min_save_interval: 1h
    restore: true
    filters:
      - multiply: 0.001

  - platform: jk_bms_ble
    jk_bms_ble_id: bms3
    min_cell_voltage:
      name: "BMS 3 min cell voltage"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    max_cell_voltage:
      name: "BMS 3 max cell voltage"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    min_voltage_cell:
      name: "BMS 3 min voltage cell"
    max_voltage_cell:
      name: "BMS 3 max voltage cell"
    delta_cell_voltage:
      name: "BMS 3 delta cell voltage"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    average_cell_voltage:
      name: "BMS 3 average cell voltage"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_1:
      name: "BMS 3 cell voltage 1"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_2:
      name: "BMS 3 cell voltage 2"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_3:
      name: "BMS 3 cell voltage 3"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_4:
      name: "BMS 3 cell voltage 4"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_5:
      name: "BMS 3 cell voltage 5"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_6:
      name: "BMS 3 cell voltage 6"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_7:
      name: "BMS 3 cell voltage 7"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_8:
      name: "BMS 3 cell voltage 8"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_9:
      name: "BMS 3 cell voltage 9"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_10:
      name: "BMS 3 cell voltage 10"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_11:
      name: "BMS 3 cell voltage 11"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_12:
      name: "BMS 3 cell voltage 12"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_13:
      name: "BMS 3 cell voltage 13"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_14:
      name: "BMS 3 cell voltage 14"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_15:
      name: "BMS 3 cell voltage 15"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_16:
      name: "BMS 3 cell voltage 16"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_17:
      name: "BMS 3 cell voltage 17"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_18:
      name: "BMS 3 cell voltage 18"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_19:
      name: "BMS 3 cell voltage 19"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_20:
      name: "BMS 3 cell voltage 20"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_21:
      name: "BMS 3 cell voltage 21"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_22:
      name: "BMS 3 cell voltage 22"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_23:
      name: "BMS 3 cell voltage 23"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_24:
      name: "BMS 3 cell voltage 24"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    total_voltage:
      name: "BMS 3 total voltage"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    current:
      name: "BMS 3 current"
      unit_of_measurement: A
      device_class: current
      state_class: measurement
      entity_category: diagnostic
    power:
      name: "BMS 3 power"
      unit_of_measurement: W
      device_class: energy
      state_class: measurement
      entity_category: diagnostic
    charging_power:
      id: bms_3_charging_power
      name: "BMS 3 charging power"
      unit_of_measurement: W
      device_class: energy
      state_class: measurement
      entity_category: diagnostic
    discharging_power:
      id: bms_3_discharging_power
      name: "BMS 3 discharging power"
      unit_of_measurement: W
      device_class: energy
      state_class: measurement
      entity_category: diagnostic
    temperature_sensor_1:
      name: "BMS 3 temperature sensor 1"
    temperature_sensor_2:
      name: "BMS 3 temperature sensor 2"
    power_tube_temperature:
      name: "BMS 3 power tube temperature"
    state_of_charge:
      name: "BMS 3 state of charge"
    capacity_remaining:
      name: "BMS 3 capacity remaining"
      unit_of_measurement: Ah
      device_class: current
      state_class: measurement
      entity_category: diagnostic
    total_battery_capacity_setting:
      name: "BMS 3 total battery capacity setting"
    charging_cycles:
      name: "BMS 3 charging cycles"
    total_charging_cycle_capacity:
      name: "BMS 3 total charging cycle capacity"
    total_runtime:
      name: "BMS 3 total runtime"
      internal: true
    balancing_current:
      name: "BMS 3 balancing current"
      unit_of_measurement: A
      device_class: current
      state_class: measurement
      entity_category: diagnostic

  - platform: total_daily_energy
    name: "BMS 4 Total Charging Energy Today"
    power_id: bms_4_charging_power
    unit_of_measurement: kWh
    icon: mdi:counter
    accuracy_decimals: 3
    min_save_interval: 1h
    restore: true
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "BMS 4 Total Discharging Energy Today"
    power_id: bms_4_charging_power
    unit_of_measurement: kWh
    icon: mdi:counter
    accuracy_decimals: 3
    min_save_interval: 1h
    restore: true
    filters:
      - multiply: 0.001

  - platform: jk_bms_ble
    jk_bms_ble_id: bms4
    min_cell_voltage:
      name: "BMS 4 min cell voltage"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    max_cell_voltage:
      name: "BMS 4 max cell voltage"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    min_voltage_cell:
      name: "BMS 4 min voltage cell"
    max_voltage_cell:
      name: "BMS 4 max voltage cell"
    delta_cell_voltage:
      name: "BMS 4 delta cell voltage"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    average_cell_voltage:
      name: "BMS 4 average cell voltage"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_1:
      name: "BMS 4 cell voltage 1"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_2:
      name: "BMS 4 cell voltage 2"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_3:
      name: "BMS 4 cell voltage 3"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_4:
      name: "BMS 4 cell voltage 4"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_5:
      name: "BMS 4 cell voltage 5"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_6:
      name: "BMS 4 cell voltage 6"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_7:
      name: "BMS 4 cell voltage 7"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_8:
      name: "BMS 4 cell voltage 8"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_9:
      name: "BMS 4 cell voltage 9"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_10:
      name: "BMS 4 cell voltage 10"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_11:
      name: "BMS 4 cell voltage 11"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_12:
      name: "BMS 4 cell voltage 12"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_13:
      name: "BMS 4 cell voltage 13"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_14:
      name: "BMS 4 cell voltage 14"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_15:
      name: "BMS 4 cell voltage 15"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_16:
      name: "BMS 4 cell voltage 16"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_17:
      name: "BMS 4 cell voltage 17"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_18:
      name: "BMS 4 cell voltage 18"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_19:
      name: "BMS 4 cell voltage 19"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_20:
      name: "BMS 4 cell voltage 20"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_21:
      name: "BMS 4 cell voltage 21"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_22:
      name: "BMS 4 cell voltage 22"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_23:
      name: "BMS 4 cell voltage 23"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    cell_voltage_24:
      name: "BMS 4 cell voltage 24"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    total_voltage:
      name: "BMS 4 total voltage"
      device_class: voltage
      state_class: measurement
      entity_category: diagnostic
    current:
      name: "BMS 4 current"
      unit_of_measurement: A
      device_class: current
      state_class: measurement
      entity_category: diagnostic
    power:
      name: "BMS 4 power"
      unit_of_measurement: W
      device_class: energy
      state_class: measurement
      entity_category: diagnostic
    charging_power:
      id: bms_4_charging_power
      name: "BMS 4 charging power"
      unit_of_measurement: W
      device_class: energy
      state_class: measurement
      entity_category: diagnostic
    discharging_power:
      id: bms_4_discharging_power
      name: "BMS 4 discharging power"
      unit_of_measurement: W
      device_class: energy
      state_class: measurement
      entity_category: diagnostic
    temperature_sensor_1:
      name: "BMS 4 temperature sensor 1"
    temperature_sensor_2:
      name: "BMS 4 temperature sensor 2"
    power_tube_temperature:
      name: "BMS 4 power tube temperature"
    state_of_charge:
      name: "BMS 4 state of charge"
    capacity_remaining:
      name: "BMS 4 capacity remaining"
      unit_of_measurement: Ah
      device_class: current
      state_class: measurement
      entity_category: diagnostic
    total_battery_capacity_setting:
      name: "BMS 4 total battery capacity setting"
    charging_cycles:
      name: "BMS 4 charging cycles"
    total_charging_cycle_capacity:
      name: "BMS 4 total charging cycle capacity"
    total_runtime:
      name: "BMS 4 total runtime"
      internal: true
    balancing_current:
      name: "BMS 4 balancing current"
      unit_of_measurement: A
      device_class: current
      state_class: measurement
      entity_category: diagnostic

text_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms3
    total_runtime_formatted:
      name: "BMS 3 total runtime formatted"
    errors:
      name: "BMS 3 Errors"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms4
    total_runtime_formatted:
      name: "BMS 4 total runtime formatted"
    errors:
      name: "BMS 4 Errors"
```

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/ble_client/ble_client.cpp: In member function 'float esphome::ble_client::BLEClient::parse_char_value(uint8_t*, uint16_t)':
src/esphome/components/ble_client/ble_client.cpp:252:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 2) {
       ^~
src/esphome/components/ble_client/ble_client.cpp:255:5: note: here
     case 0x7:  // uint24.
     ^~~~
src/esphome/components/ble_client/ble_client.cpp:256:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 3) {
       ^~
src/esphome/components/ble_client/ble_client.cpp:259:5: note: here
     case 0x8:  // uint32.
     ^~~~
src/esphome/components/ble_client/ble_client.cpp:260:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 4) {
       ^~
src/esphome/components/ble_client/ble_client.cpp:264:5: note: here
     case 0xC:  // int8.
     ^~~~
src/esphome/components/ble_client/ble_client.cpp:268:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 2) {
       ^~
src/esphome/components/ble_client/ble_client.cpp:271:5: note: here
     case 0xF:  // int24.
     ^~~~
src/esphome/components/ble_client/ble_client.cpp:272:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 3) {
       ^~
src/esphome/components/ble_client/ble_client.cpp:275:5: note: here
     case 0x10:  // int32.
     ^~~~
```
