### ISSUE TITLE
Incorrect platform chosen when calling external library

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [esphome/issues#3237]
### The problem

I am attempting to call an external library written for the ESP32, but the PlatformIO build process seems to indicate that it is seeking the platform of the host (x86-64) rather than the intended target of ESP32.

I've attempted with both the official Docker container and the HA addon.

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

TinyPico

### Component causing the issue

External Library

### Example YAML snippet

```yaml
Specifically:
~~~~~~~~~~~~
esphome:
  name: bt-test
  includes:
    - esp32_ble_keyboard.h
  libraries:
    - "t-vk/ESP32-BLE-Keyboard"


Full YAML:
~~~~~~~~~~~~

esphome:
  name: bt-test
  includes:
    - esp32_ble_keyboard.h
  libraries:
    - "t-vk/ESP32-BLE-Keyboard"

esp32:
  board: tinypico
  framework:
    type: arduino
    version: recommended


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: <password>

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bt-Test Fallback Hotspot"
    password: <password>

# captive_portal:
    

button:
  - platform: template
    id: bt_test_pp
    name: BT Test Play-Pause
    on_press:
      - lambda: (static_cast<Esp32BLEKeyboard *>(ble_keyboard))->bleKeyboard.write(KEY_MEDIA_PLAY_PAUSE)
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/bt-test.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing bt-test (board: tinypico; framework: arduino; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Library Manager: Installing t-vk/ESP32-BLE-Keyboard
Warning! Could not find the package with 't-vk/ESP32-BLE-Keyboard' requirements for your system 'linux_x86_64'
Dependency Graph
|-- <WiFi> 1.0
|-- <ESPmDNS> 1.0
|-- <Update> 1.0
Compiling .pioenvs/bt-test/src/main.cpp.o
Compiling .pioenvs/bt-test/lib18f/WiFi/WiFiClient.cpp.o
Compiling .pioenvs/bt-test/lib18f/WiFi/WiFiGeneric.cpp.o
Compiling .pioenvs/bt-test/lib18f/WiFi/WiFiMulti.cpp.o
In file included from src/main.cpp:25:0:
src/esp32_ble_keyboard.h:1:25: fatal error: BleKeyboard.h: No such file or directory

*********************************************************************
* Looking for BleKeyboard.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:BleKeyboard.h"
* Web  > https://registry.platformio.org/search?q=header:BleKeyboard.h
*
*********************************************************************

compilation terminated.
*** [.pioenvs/bt-test/src/main.cpp.o] Error 1
========================== [FAILED] Took 2.50 seconds ==========================
```
