### ISSUE TITLE
Missing data in RF transmit for rc_switch_raw

### ISSUE THREAD

**Issue by GhettoDubs** [esphome/issues#3238]
### The problem

I'm using a Sonoff RF bridge (v2.2) with hardware hack to decode/clone an Arlec Ceiling Fan remote.

When I transmit data the first sync bit is always missed.  This happens if I use raw signal or using custom protocol.  

Also the amplitude seems low compared to the original remote but I think this is separate issue.

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.4.5

### What platform are you using?

ESP8266

### Board

Sonoff RF hardware hacked v2.2

### Component causing the issue

RF Transmitter

### Example YAML snippet

```yaml
# Basic Config
esphome:
  name: rf-bridge
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:
  level: VERBOSE

# Device Specific Config

remote_receiver:
  pin: 
    number: GPIO04
#    inverted: true
  dump: raw
  filter: 10us
  tolerance: 40%
  idle: 10ms
  buffer_size: 2kb

remote_transmitter:
  pin: 5
  carrier_duty_percent: 100%

status_led:
  pin:
    number: GPIO13
    inverted: yes

switch:
  - platform: template
    name: "Fan raw"
    id: "upstairsfan"
    icon: "mdi:fan"
    optimistic: true
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [300,-4545,300,-900,900,-300,300,-900,900,-300,900,-300,900,-300,900,-300,
                 300,-900,300,-900,900,-300,900,-300,900,-300,300,-900,300,-900,
                 900,-300,900,-300,300,-900,900,-300,300,-900,300,-900,900,-300,
                 300,-900,900,-300,900,-300,300,-900,300,-900,300,-900,300,-900,
                 900,-300,300,-900,900,-300,300,-900,300,-5445,
                 300,-900,900,-300,300,-900,900,-300,900,-300,900,-300,900,-300,
                 300,-900,300,-900,900,-300,900,-300,900,-300,300,-900,300,-900,
                 900,-300,900,-300,300,-900,900,-300,300,-900,300,-900,900,-300,
                 300,-900,900,-300,900,-300,300,-900,300,-900,300,-900,300,-900,
                 900,-300,300,-900,900,-300,300,-900,300,-5445,
                 300,-900,900,-300,300,-900,900,-300,900,-300,900,-300,900,-300,
                 300,-900,300,-900,900,-300,900,-300,900,-300,300,-900,300,-900,
                 900,-300,900,-300,300,-900,900,-300,300,-900,300,-900,900,-300,
                 300,-900,900,-300,900,-300,300,-900,300,-900,300,-900,300,-900,
                 900,-300,300,-900,900,-300,300,-900,300,-5445,
                 300,-900,900,-300,300,-900,900,-300,900,-300,900,-300,900,-300,
                 300,-900,300,-900,900,-300,900,-300,900,-300,300,-900,300,-900,
                 900,-300,900,-300,300,-900,900,-300,300,-900,300,-900,900,-300,
                 300,-900,900,-300,900,-300,300,-900,300,-900,300,-900,300,-900,
                 900,-300,300,-900,900,-300,300,-900,300,-5445,
                 300,-900,900,-300,300,-900,900,-300,900,-300,900,-300,900,-300,
                 300,-900,300,-900,900,-300,900,-300,900,-300,300,-900,300,-900,
                 900,-300,900,-300,300,-900,900,-300,300,-900,300,-900,900,-300,
                 300,-900,900,-300,900,-300,300,-900,300,-900,300,-900,300,-900,
                 900,-300,300,-900,900,-300,300,-900,300,-900]
  - platform: template
    name: "Fan protocol"
    icon: "mdi:plus"
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '10100001100011001011111111110101'
          protocol: 
            pulse_length: 300
            sync: [1,15]
            one: [1,3]
            zero: [3,1]
          repeat: 
            times: 5
            wait_time: 0s
```

### Additional information

Captured using RTL-SDR and Universal Radio Hacker

Using raw output
![using raw](https://user-images.githubusercontent.com/24391663/164958564-3e10ab33-b0e7-42d0-99b7-7b65dba1ae63.PNG)

Using protocol output
![using protocol](https://user-images.githubusercontent.com/24391663/164958570-b14458e3-7b63-43a8-ad5c-dba26a49b0aa.PNG)
