### ISSUE TITLE
Failed to call service esphome.esp32_cam_front_camera_set_param. expected int for dictionary value @ data['value']. Got None

### ISSUE THREAD

**Issue by tiagofreire-pt** [esphome/issues#3240]
### The problem

While setting the wb_mode on esp32-camera, via Home Assistant service call, the value is expected to be a string but is asked for a integer:

```
service: esphome.esp32_cam_front_camera_set_param
data:
  name: wb_mode
  value: 'sunny'
```

Returns the following error:

```Failed to call service esphome.esp32_cam_front_camera_set_param. expected int for dictionary value @ data['value']. Got None```

Documentation says:

```
White Balance Setting:

    wb_mode (Optional, enum): The mode of white balace module. Defaults to auto.

            auto: Camera choose best white balance setting
            sunny: White balance sunny mode
            cloudy: White balance cloudy mode
            office: White balance office mode
            home: White balance home mode

```

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.4.2

### What platform are you using?

ESP32

### Board

esp32-cam

### Component causing the issue

esp32_camera

### Example YAML snippet

```yaml
api:
# --- Specific data : API custom services ---
  services:
    # change camera parameters on-the-fly
    - service: camera_set_param
      variables:
        name: string
        value: int
      then:
        - lambda: |-
            bool state_return = false;
            if (("contrast" == name) && (value >= -2) && (value <= 2)) { id(camera_front).set_contrast(value); state_return = true; }
            if (("brightness" == name) && (value >= -2) && (value <= 2)) { id(camera_front).set_brightness(value); state_return = true; }
            if (("saturation" == name) && (value >= -2) && (value <= 2)) { id(camera_front).set_saturation(value); state_return = true; }
            if (("special_effect" == name) && (value >= 0U) && (value <= 6U)) { id(camera_front).set_special_effect((esphome::esp32_camera::ESP32SpecialEffect)value); state_return = true; }
            if (("aec_mode" == name) && (value >= 0U) && (value <= 1U)) { id(camera_front).set_aec_mode((esphome::esp32_camera::ESP32GainControlMode)value); state_return = true; }
            if (("aec2" == name) && (value >= 0U) && (value <= 1U)) { id(camera_front).set_aec2(value); state_return = true; }
            if (("ae_level" == name) && (value >= -2) && (value <= 2)) { id(camera_front).set_ae_level(value); state_return = true; }
            if (("aec_value" == name) && (value >= 0U) && (value <= 1200U)) { id(camera_front).set_aec_value(value); state_return = true; }
            if (("agc_mode" == name) && (value >= 0U) && (value <= 1U)) { id(camera_front).set_agc_mode((esphome::esp32_camera::ESP32GainControlMode)value); state_return = true; }
            if (("agc_value" == name) && (value >= 0U) && (value <= 30U)) { id(camera_front).set_agc_value(value); state_return = true; }
            if (("agc_gain_ceiling" == name) && (value >= 0U) && (value <= 6U)) { id(camera_front).set_agc_gain_ceiling((esphome::esp32_camera::ESP32AgcGainCeiling)value); state_return = true; }
            if (("wb_mode" == name) && (value >= 0U) && (value <= 4U)) { id(camera_front).set_wb_mode((esphome::esp32_camera::ESP32WhiteBalanceMode)value); state_return = true; }
            if (("test_pattern" == name) && (value >= 0U) && (value <= 1U)) { id(camera_front).set_test_pattern(value); state_return = true; }
            
            if (true == state_return) {
              id(camera_front).update_camera_parameters();
            }
            else {
              ESP_LOGW("esp32_camera_set_param", "Error in name or data range");
            }
esp32_camera:
  id: "camera_front"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  
  name: camera_front
  # ... Frame Settings
  resolution: 800x600
  max_framerate: 10 fps
  idle_framerate: 0.1 fps
  # Picture settings
  jpeg_quality: 20
  brightness: 2
  contrast: -2
  saturation: 1
  vertical_flip: true
  horizontal_mirror: true
  
  special_effect: none
  # exposure settings
  aec_mode: auto
  aec2: false
  ae_level: 0
  aec_value: 300
  # gain settings
  agc_mode: auto
  agc_gain_ceiling: 2x
  agc_value: 0
  # white balance setting
  wb_mode: auto
```
