### ISSUE TITLE
The ESP is rebooted during the loading of the tft file

### ISSUE THREAD

**Issue by yaploxoigolyb** [esphome/issues#3243]
### The problem

During an attempt to download a txt file via esphome, the logger outputs the following:
```
[D][nextion_upload:175]: Requesting URL: http://192.168.1.4:8080/test.tft
E (102228) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (102228) task_wdt:  - loopTask (CPU 1)
E (102228) task_wdt: Tasks currently running:
E (102228) task_wdt: CPU 0: IDLE0
E (102228) task_wdt: CPU 1: loopTask
E (102228) task_wdt: Aborting.
abort() was called at PC 0x40156c4c on core 0

ELF file SHA256: 0000000000000000

Backtrace: 0x40088924:0x3ffbf820 0x40088ba1:0x3ffbf840 0x40156c4c:0x3ffbf860 0x40087019:0x3ffbf880 0x4018b073:0x3ffbc160 0x40158557:0x3ffbc180 0x4008b361:0x3ffbc1a0 0x40089bb2:0x3ffbc1c0

Rebooting...
```

Hardware: 
- Board: esp32doit-devkit-v1 (ESP32-WROOM)
- Display: NX3224T024_011

### Which version of ESPHome has the issue?

2022.3.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Example YAML snippet

```yaml
button:
  - platform: template
    name: dislpay updater
    id: update
    icon: "mdi:emoticon-outline"
    on_press:
      - lambda: 'id(teplomer)->upload_tft();'
```

_No response_
