### ISSUE TITLE
Sonoff RF Bridge not reporting RF

### ISSUE THREAD

**Issue by lowfat32** [esphome/issues#3246]
### The problem

After a couple of hours the RF Bridge requires a hard reboot as it quits reporting all received RF. This is with the 'Portisch' RF firmware. Can still connect to the rf bridges but the logs never show any received RF signals. Flashed a 2nd RF Bridge and continued to have the same issues on the newly flashed RF bridge. 

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.4.6

### What platform are you using?

ESP8266

### Board

Sonoff RF Bridge R2 1.0

### Component causing the issue

RF

### Example YAML snippet

```yaml
esphome:
   name: rfbridge
   platform: ESP8266
   board: esp01_1m

#Local MAC: 84:0D:8E:45:57:C4
wifi:
   ssid: 
   password: 
   domain: .mydomain.com
   

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 19200
#need to disable uart logging as it will interfere
logger:
  baud_rate: 0


web_server:
  port: 80
  
ota:  

# Enable Home Assistant API
api:
  services:
    - service: send_rf_code
      variables:
        sync: int
        low: int
        high: int
        code: int
      then:
        - rf_bridge.send_code:
            sync: !lambda 'return sync;'
            low: !lambda 'return low;'
            high: !lambda 'return high;'
            code: !lambda 'return code;'
    - service: send_rf_raw
      variables:
        raw: string
      then:
        - rf_bridge.send_raw:
            raw: !lambda 'return raw;'
            

switch:
  - platform: restart
    name: "RF Bridge Restart"
   
rf_bridge:
  on_code_received:
    then:
      - homeassistant.event:
          event: esphome.rf_code_received
          data:
            sync: !lambda 'char buffer [10];return itoa(data.sync,buffer,16);'
            low: !lambda 'char buffer [10];return itoa(data.low,buffer,16);'
            high: !lambda 'char buffer [10];return itoa(data.high,buffer,16);'
            code: !lambda 'char buffer [10];return itoa(data.code,buffer,16);'   
      - if:
          condition:
            lambda: |-
              return data.code == 0xB9CDA0;
          then:
            - binary_sensor.template.publish:
                id: kitchen_entry_motion
                state: ON
            - delay: 10s
            - binary_sensor.template.publish:
                id: kitchen_entry_motion
                state: OFF                 
      - if:
          condition:
            lambda: |-
              return data.code == 0xB9CDA8;
          then:
            - binary_sensor.template.publish:
                id: kitchen_entry_motion
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: kitchen_entry_motion
                state: OFF                 
      - if:
          condition:
            lambda: |-
              return data.code == 0xB9CDA9;
          then:
            - binary_sensor.template.publish:
                id: kitchen_entry_motion
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: kitchen_entry_motion
                state: OFF                
      - if:
          condition:
            lambda: |-
              return data.code == 0xED6DA0;
          then:
            - binary_sensor.template.publish:
                id: kitchen_proper_motion
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: kitchen_proper_motion
                state: OFF                
      - if:
          condition:
            lambda: |-
              return data.code == 0xED6DA9;
          then:
            - binary_sensor.template.publish:
                id: kitchen_proper_motion
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: kitchen_proper_motion
                state: OFF
      - if:
          condition:
            lambda: |-
              return data.code == 0x70796C;
          then:
            - binary_sensor.template.publish:
                id: front_door_motion
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: front_door_motion
                state: OFF
      - if:
          condition:
            lambda: |-
              return data.code == 0xCFDDA0;
          then:
            - binary_sensor.template.publish:
                id: washroom_motion
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: washroom_motion
                state: OFF
      - if:
          condition:
            lambda: |-
              return data.code == 0xCFDDA9;
          then:
            - binary_sensor.template.publish:
                id: washroom_motion
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: washroom_motion
                state: OFF
      - if:
          condition:
            lambda: |-
              return data.code == 0x7FD4E9;
          then:
            - binary_sensor.template.publish:
                id: printer_room_motion
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: printer_room_motion
                state: OFF
      - if:
          condition:
            lambda: |-
              return data.code == 0x7FD4E8;
          then:
            - binary_sensor.template.publish:
                id: printer_room_motion
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: printer_room_motion
                state: OFF
      - if:
          condition:
            lambda: |-
              return data.code == 0x7FD4E0;
          then:
            - binary_sensor.template.publish:
                id: printer_room_motion
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: printer_room_motion
                state: OFF                
      - if:
          condition:
            lambda: |-
              return data.code == 0x8B5C74;
          then:
            - binary_sensor.template.publish:
                id: scott_light_button
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: scott_light_button
                state: OFF
      - if:
          condition:
            lambda: |-
              return data.code == 0x19B5A2;
          then:
            - binary_sensor.template.publish:
                id: scott_remote_a
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: scott_remote_a
                state: OFF                
      - if:
          condition:
            lambda: |-
              return data.code == 0x19B5A8;
          then:
            - binary_sensor.template.publish:
                id: scott_remote_b
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: scott_remote_b
                state: OFF
      - if:
          condition:
            lambda: |-
              return data.code == 0x19B5A1;
          then:
            - binary_sensor.template.publish:
                id: scott_remote_c
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: scott_remote_c
                state: OFF
      - if:
          condition:
            lambda: |-
              return data.code == 0x19B5A4;
          then:
            - binary_sensor.template.publish:
                id: scott_remote_d
                state: ON
            - delay: 5s
            - binary_sensor.template.publish:
                id: scott_remote_d
                state: OFF
                
binary_sensor:
- platform: template
  name: kitchen_entry_motion
  id: kitchen_entry_motion
  device_class: motion
- platform: template
  name: kitchen_proper_motion
  id: kitchen_proper_motion
  device_class: motion
- platform: template
  name: front_door_motion
  id: front_door_motion
  device_class: motion
- platform: template
  name: washroom_motion
  id: washroom_motion
  device_class: motion
- platform: template
  name: printer_room_motion
  id: printer_room_motion
  device_class: motion  
- platform: template
  name: scott_light_button
  id: scott_light_button
- platform: template
  name: scott_remote_a
  id: scott_remote_a
- platform: template
  name: scott_remote_b
  id: scott_remote_b
- platform: template
  name: scott_remote_c
  id: scott_remote_c
- platform: template
  name: scott_remote_d
  id: scott_remote_d
```
