### ISSUE TITLE
MQTT `discovery: true` not respected on entity, when global default is `discovery: false`

### ISSUE THREAD

**Issue by bjeanes** [esphome/issues#3251]
### The problem

The [MQTT docs](https://esphome.io/components/mqtt.html#mqtt-component-base-configuration) say about the per-component `discovery` option:

> Manually enable/disable discovery for a component. Defaults to the global default.

However, if I set the global to `false` and `discovery: true` on a single sensor/entity, a discovery payload is not sent (states are published to MQTT and `state_topic` _is_ respected).

OTOH, if the default is `true`, `discovery: false` _does_ prevent that sensor from publishing to its discovery topic (though it continues to publish to its `state_topic`) as would b expected.

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

mqtt

### Example YAML snippet

```yaml
mqtt:
  broker: the-broker
  discovery: false

sensor:
  - platform: template
    name: "Test Sensor"
    id: test_sensor
    discovery: true
    state_topic: "sensor/test/state"
    lambda: |-
      return rand() % 100;
    update_interval: 60s
```

### Additional information

related feature request: be able to disable an entity from being exposed over the `api` component. Setting `internal: true` also suppresses MQTT states. 

I have two separate use cases to have some entities use MQTT but don't wish to forgo the benefits of the `api` transport for all other entities, so don't want _everything_ to use MQTT. 

I know, it's a bit weird to have some sensors publish state over MQTT and others over the API. However, there are some bluetooth sensors for which I have multiple ESPs that listen and they need to publish to a shared sensor. There is no way (that I have come across) to make an ESPHome component be divorced from the Home Assistant "device" so that multiple real-world devices can publish states to it.
