### ISSUE TITLE
ESP8266 web server component not working

### ISSUE THREAD

**Issue by bruvv** [esphome/issues#3253]
### The problem

When flashing a D1 mini as a stand alone sensor it is not possible to connect to the website. It broadcasts the AP SSID and my device connects perfectly fine but when going to http://192.168.4.1 I get error `ERR_CONNECTION_REFUSED` (chrome). Tested it on firefox, chrome, safari, edge and android (chrome and firefox) all of them are unable to connect. When enabled the component: `captive_portal` I do get the captive_portal where I can upload new OTA file or connect to a WIFI network, but I just want to have it as a stand alone device. Why? Because I am at work and want to measure the PM2.5 particles, and we are not allowed to connect devices to WIFI. When I am at home it connects to my home wifi and it is connected to home assistant just fine.

I found in the logs:
```
[V][wifi_esp8266:704]: DHCP server IP lease start: 192.168.4.100 
[V][wifi_esp8266:707]: DHCP server IP lease end: 192.168.4.200
```
But the IP that my devices are getting: `192.168.4.2` and `192.168.4.3`

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

n.a.

### What platform are you using?

ESP8266

### Board

D1 WEMOS MINI

### Component causing the issue

web_server

### Example YAML snippet

```yaml
---
substitutions:
  device_name: airquality
  friendly_name: "VINDRINKTNING Air Quality"
  device_description: "Measure your air quality pm2.5 and co2"
  baud_rate: '9600'
  ikea_pin: D4
esphome:
  name: '${device_name}'
  comment: '${device_description}'
  project:
    name: "pm25.ikea"
    version: "1.0.0"
  platform: esp8266
  board: d1_mini
  #platform: ESP32
  #board: esp32doit-devkit-v1
  #platform: ESP8266
  #board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #fast_connect: true
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${device_name}'
    #ap_timeout: 1s

#captive_portal:

web_server:
  local: true

# Enable logging
logger:
  level: VERBOSE

# Enable improv over serial
improv_serial:

# Enable Home Assistant API
api:

ota:
  #safe_mode: true
  #reboot_timeout: 10min
  #num_attempts: 5

time:
  - platform: homeassistant

# Sensors for ESP version and WIFI information
text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} - ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} - IP Address"
      icon: mdi:wifi
    ssid:
      name: "${friendly_name} - Connected SSID"
      icon: mdi:wifi-strength-2

uart:
  - id: uart_air
    rx_pin: '${ikea_pin}'
    baud_rate: '${baud_rate}'

sensor:
  - platform: pm1006
    id: ikea_air
    uart_id: uart_air
    pm_2_5:
      name: "$friendly_name"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 50
            send_every: 10
            send_first_at: 10
  - platform: template
    name: "$friendly_name - Power Usage"
    id: power_consumption
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    accuracy_decimals: 4
    filters:
      - heartbeat: 60s
  - platform: integration
    name: "$friendly_name - Consumed Energy"
    sensor: power_consumption
    time_unit: 'h'
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: 'Wh'
    restore: false
    integration_method: left

interval:
  - interval: 1min
    then:
      - sensor.template.publish:
          id: power_consumption
          state: 0.5696
```

### Anything in the logs that might be useful for us?

```txt
[W][wifi:442]: No matching network found!
[D][wifi:373]: Starting scan...
[I][wifi:136]: Starting fallback AP!
[V][wifi_esp8266:066]: Enabling AP.
mode : sta(58:bf:25:da:e0:f5) + softAP(5a:bf:25:da:e0:f5)
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100
[C][wifi:201]: Setting up AP...
[C][wifi:203]:   AP SSID: 'airquality'
[C][wiwifi evt: 8
fi:204]:   AP Password: ''
bcn 0
del if1
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100
[V][wifi_esp8266:704]: DHCP server IP lease start: 192.168.4.100
[V][wifi_esp8266:707]: DHCP server IP lease end: 192.168.4.200
[C][wifi:213]:   IP Address: 192.168.4.1
wifi evt: 7
scandone
wifi evt: 7
wifi evt: 7
add 1
aid 1
station: 68:2f:67:92:18:7a join, AID = 1
[V][wifi_esp8266:518]: Event: AP client connected MAC=68:2F:67:92:18:7A aid=1
wifi evt: 5
wifi evt: 7
[D][wifi:373]: Starting scan...
wifi evt: 7
scandone
[D][wifi:388]: Found networks:
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[W][wifi:442]: No matching network found!
wifi evt: 7
[V][wifi_esp8266:540]: Event: AP Distribute Station IP MAC=68:2F:67:92:18:7A IP=192.168.4.2 aid=1
wifi evt: 9
wifi evt: 7
[D][wifi:373]: Starting scan...
wifi evt: 7
scandone
[D][wifi:388]: Found networks:
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[W][wifi:442]: No matching network found!
wifi evt: 7
[D][wifi:373]: Starting scan...
wifi evt: 7
wifi evt: 7
scandone
[D][wifi:388]: Found networks:
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[W][wifi:442]: No matching network found!
[W][wifi:571]: Restarting WiFi adapter...
[V][wifi_esp8266:060]: Disabling STA.
del if0
mode : softAP(5a:bf:25:da:e0:f5)
[V][wifi_esp8266:534]: Event: Changed Mode old=AP+STA new=AP
wifi evt: 8
wifi evt: 7
wifi evt: 7
[D][sensor:124]: 'VINDRINKTNING Air Quality - Power Usage': Sending state 0.56960 W with 4 decimals of accuracy
[V][sensor:074]: 'VINDRINKTNING Air Quality - Consumed Energy': Received new state 0.018987
[D][sensor:124]: 'VINDRINKTNING Air Quality - Consumed Energy': Sending state 0.01899 Wh with 6 decimals of accuracy
wifi evt: 7
wifi evt: 7
[D][wifi:373]: Starting scan...
[V][wifi_esp8266:058]: Enabling STA.
mode : sta(58:bf:25:da:e0:f5) + softAP(5a:bf:25:da:e0:f5)
add if0
[V][wifi_esp8266:534]: Event: Changed Mode old=AP new=AP+STA
wifi evt: 8
wifi evt: 7
[V][sensor:074]: 'VINDRINKTNING Air Quality - Power Usage': Received new state 0.569600
wifi evt: 7
wifi evt: 7
[V][sensor:074]: 'VINDRINKTNING Air Quality - Power Usage': Received new state 0.569600
scandone
[D][wifi:388]: Found networks:
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[D][wifi:436]: - [redacted] [redacted]▂▄▆█
[W][wifi:442]: No matching network found!
wifi evt: 7
[D][wifi:373]: Starting scan...
```
