### ISSUE TITLE
On_value_range doesn't support (FOR CONDITION) to trigger an action when condition was true for a certain period of time

### ISSUE THREAD

**Issue by duojianghuji** [esphome/issues#3255]
### The problem

Dear all, I am building an esphome-driven sunshine shelter and have the following problem:

Apart from manual operation, the shelter’s opening or closing will be driven by the amount of light measured. The following code works without problems. I'm using the fan component for controlling the shelter motor. However, this might be a bit jumpy when the light scenario changes quickly (clouds moving in front of sun late at day), so you want the condition to be true for, say, at least 15 min.
I tried the FOR condition in the context of on_value_range, there seems no error in compiling but the automation just didn't work. I put the codes the example YAML snippet.

Is there a correct way to achieve my goal? Any help appreciated :slight_smile:

sensor:
  - platform: homeassistant
    id: light_intensity
    entity_id: input_number.light_intensity
    on_value_range:
      - above: 10
        then:
          - fan.turn_on: sun_shelter
      - below: 10
        then:
          - fan.turn_off: sun_shelter

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.4.7

### What platform are you using?

ESP32

### Board

ESP32

### Component causing the issue

Sensor component; Fan component

### Example YAML snippet

```yaml
sensor:
  - platform: homeassistant
    id: light_intensity
    entity_id: input_number.light_intensity
    on_value_range:
      - below: 10
        then:
          - if:
              condition:
                for:
                  time: 5s
                  condition:
                    - lambda: 'return id(light_intensity).state < 10.0 ;'
              then:
                - fan.turn_on: sun_shelter
```

### Additional information

I don't have a light senor in hand to test so I use a input number as the sun intensity for test.
