### ISSUE TITLE
Tuya curtain position data point is not updated locking position control

### ISSUE THREAD

**Issue by dennisvbussel** [esphome/issues#3260]
### The problem

Opening and closing the curtain by setting the slider to 0 or 100 % is always working. However setting the curtain to a certain position often results in no response at all.

The following command sequence is taken:
1. Send command curtain close (Datapoint 1 to 2)
2. Curtain position is reported (Datapoint 3 to 100)
3. Send command curtain position 50 (Datapoint 2 to 50)
4. Curtain does not move and the debug terminal reports (Not sending unchanged value)

It seems that Datapoint 2 and 3 are out of sync. I think Datapoint 2 should also be updated on open/close commands.

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.4.7

### What platform are you using?

ESP8266

### Board

Custom build pcb using nodemcuv2

### Component causing the issue

tuya cover

### Example YAML snippet

```yaml
substitutions:
  device_name: wk-gordijn-links
  friendly_name: Woonkamer gordijn links
  
# Main config
esphome:
  name: "${device_name}"
  platform: ESP8266
  board: nodemcuv2
  
logger:
  level: VERBOSE # ERROR/WARNING/INFO/DEBUG/VERBOSE/VERY_VERBOSE
  baud_rate: 0 # important because we are using uart0 to communicate with Tuya MCU

# Wireless config
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: wk-gordijn-links.local

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: !secret default_password

captive_portal:

# Enable Home Assistant API and OTA update
api:
ota:

# ESP Status LED
#status_led:
#  pin:
#    number: D4
#    inverted: True

uart:
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 9600
  
button:
  - platform: restart
    name: "${friendly_name} herstart"
  - platform: safe_mode
    name: "${friendly_name} Safe Mode"
    
# Register the Tuya MCU connection
tuya:

# Create a cover using the datapoint from above
cover:
  - platform: tuya
    name: "${friendly_name}"
    device_class: curtain
    control_datapoint: 1
    direction_datapoint: 5
    position_datapoint: 2
    position_report_datapoint: 3
    invert_position: True
    restore_mode: RESTORE
```

### Anything in the logs that might be useful for us?

```txt
Initial values of datapoints:
Datapoint 2: int value (value: 50)
Datapoint 3: int value (value: 100)

All position updates are updated to Datapoint 3 while leaving the datapoint 2 untouched.


Setting datapoint 2 to 50
Not sending unchanged value
```

### Additional information

[logs_wk-gordijn-links_logs.txt](https://github.com/esphome/issues/files/8599813/logs_wk-gordijn-links_logs.txt)
