### ISSUE TITLE
Incorrect sensor readings HTU21D

### ISSUE THREAD

**Issue by Operrr** [esphome/issues#3261]
### The problem

The HTU21D is giving too high temperature readings and too low humidity readings. Other sensors connected to the same microcontroller (for example ds18b20) give correct readings. I did not find information on the calibration of this sensor, what could be the problem? 

### Which version of ESPHome has the issue?

ESPHOME  2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2022.4.7 

### What platform are you using?

ESP8266

### Board

LOLIN Nodemcu v3

### Component causing the issue

htu21d

### Example YAML snippet

```yaml
esphome:
  name: workshop                    
  platform: ESP8266
  board: nodemcuv2                  
  board_flash_mode: dout            
wifi:                               
  ssid: x
  password: xxxxxx
captive_portal:
web_server:                         
  port: 8080
  auth:
    username: admin
    password: xxxxxx
logger:                             
api:                                
  password: "xxxxxx"              
ota:                                
  password: "xxxxxx"

################################## Sensor #####################################
dallas:
  - pin: D4                         
    update_interval: 30s
i2c:
  sda: D5
  scl: D6
  scan: True  

sensor:
  - platform: wifi_signal
    name: "Workshop WiFi Signal"
    update_interval: 60s
  - platform: dallas
    address: 0xf93c01f096cbc928     
    name: "Outside temperature"
    id: outside_temperature
    accuracy_decimals: 1
    resolution: 12
  - platform: htu21d
    address: 0x40
    temperature:
      name: "Workshop Inside Temperature"
      id: workshop_temperature 
    humidity:
      name: "Workshop Humidity"
      id: workshop_hummidity
    update_interval: 15s
```

### Anything in the logs that might be useful for us?

```txt
19:22:08 [D] [dallas.sensor:144] 'Outside temperature': Got Temperature=22.7°C
19:22:57 [D] [htu21d:065] Got Temperature=27.5°C Humidity=42.9%

on the control device temperature 22.6 humidity 55%
```
