### ISSUE TITLE
Switches in the ON position toggle when restarting via Restart Switch or after Upgrade

### ISSUE THREAD

**Issue by rainero84** [esphome/issues#3263]
### The problem

I've been using ESPHome for almost a year now, mostly for switches (on/off as well as power measurement). The switches are connected to PCs, routers, RPi 4 running home assistant, appliances (fridges, washing machine, dishwasher). The software has been rock solid and haven't had any issues.

Since version 2022.3.0 the behaviour of my switches changed: when updating the software or manually resetting the device from the web interface, switches/relays that are on at that point briefly switch off then on again. This has resulted in PCs switching off, my fridge beeping, washing & dishwasher cycles getting interrupted, internet connectivity loss, etc.

I first tried setting "restore_from_flash" to "true" and setting the "restore_mode" to "RESTORE_DEFAULT_ON" without success.

I then hooked up a scope to a D1 Mini and connected my probes to pins D4 (GPIO2 - internal LED) and D1 (GPIO5 - relay shield).

1. I verified that with release 2022.2.0
a. The relay remains powered on when restarting from the Web UI
b. The relay remains powered on when updating the firmware (I re-uploaded the 2022.2.0 bin).
In the image below, CH1 is connected to output D4, and CH2 is connected to the output D1.
![1_2022 02 0_web_restart_ch1d4_ch2D1](https://user-images.githubusercontent.com/29565637/166822875-f1c58dbc-a9e8-4dfc-9ed3-7e9238d9d5a3.png)

2. I verified that with release 2022.3.0:
a. The relay briefly switches off and back on when restarting from the Web UI
b. The relay briefly switches off and back off when updating the firmware (I re-uploaded the 2022.3.0 bin).
On the scope I saw where the restart occurred based on the LED Toggle. I could see that the output briefly dropped to ~0V 
![2_2022 03 0_web_restart_ch1d4_ch2D1](https://user-images.githubusercontent.com/29565637/166823138-58fa9663-d41d-4a97-ba04-d9511e5d7704.png)

3. Next I wanted to make sure that I didn't miss a potential glitch. I set up a trigger on my scope on a falling edge when dropping below 3V.
a. With release 2022.2.0 the scope did not trigger when restarted from the Web UI or upgrading the firmware
b. With release 2022.3.0 the scope did trigger, and shows that the output remains at ~0V for approximately 19.2ms
The image below applies to 3b and shows output D1 toggling off and back on (moved from CH2 to CH1 in this setup) 
![3_2022 03 0_restart_trigger](https://user-images.githubusercontent.com/29565637/166823906-f4d64bbe-7621-4860-b464-928af070dc79.png)

One last comment: eWelink and Tasmota also keep the switches on when performing a restarting

### Which version of ESPHome has the issue?

2022.3.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

D1 Mini, Sonoff Basic R2, Sonoff Pow R2

### Component causing the issue

esp8266/core

### Example YAML snippet

```yaml
esphome:
  name: examplenode
  build_path: ./build/examplenode

esp8266:
  board: d1_mini

captive_portal:

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:

ota:

# Create a web service listening on port 80
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  networks:
    - ssid: "Jarvis"
      password: !secret wifi_password_jarvis

switch:
  - platform: restart
    name: "ExampleNode Restart"
  - platform: gpio
    name: "examplenode Switch"
    id: gate_switch
    pin: D1

binary_sensor:
  - platform: status
    name: "ExampleNode Status"

sensor:
  - platform: uptime
    name: "ExampleNode Uptime Sensor"

  - platform: wifi_signal
    name: "ExampleNode WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ExampleNode IP Address
    ssid:
      name: ExampleNode Connected SSID
    mac_address:
      name: ExampleNode Mac Address
```

### Anything in the logs that might be useful for us?

```txt
Pins are reset before logging is available
```

### Additional information

See first Discord #dev post here:
https://discord.com/channels/429907082951524364/524177279270780928/969340482729701406

...and follow-up post here:
https://discord.com/channels/429907082951524364/524177279270780928/970053624845701130

From the second link:

> ...removing the following lines from core.cpp (src/esphome/components/esp8266) keeps the relay powered on when restarting via the web ui.
![core cpp](https://user-images.githubusercontent.com/29565637/166825354-3b82943f-9673-41bc-baa9-af34c2b7f74c.png)

>I do understand the original issue though - with a cold boot the pins are in an undefined state, and these should be set to something sensible.
>However, once the device has been powered on and is restarted while remaining powered on (whether this is due to lost wifi connection, upgrade, or manual reset), the pins were in a defined state before restart. I would think a device is more likely to restart than being completely switched off and back on again.
>In my opinion, especially for switches, outputs should remain powered on while restarting.
