### ISSUE TITLE
Setting "initial_value" in globals definition does not work with types other than String

### ISSUE THREAD

**Issue by Emanuele-Spatola** [esphome/issues#3265]
### The problem

This configuration does NOT work:
```yaml
  - id: my_boolean_variable
    type: bool
    initial_value: false
```
 and generate this error:
```
    Must be string, got <class 'bool'>. did you forget putting quotes around the value?.
    initial_value: False [source config.yml:51]
  - [source config.yml:53]
    id: my_boolean_variable
    type: bool
``` 

while this one is working fine
```yaml
  - id: my_boolean_variable
    type: bool
    initial_value: "false"
```
It seems a similar issue as https://github.com/esphome/issues/issues/440

### Which version of ESPHome has the issue?

2022.3.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32
