### ISSUE TITLE
shtc3 sensor under virtual i2c bus using tca9548a

### ISSUE THREAD

**Issue by matteobusolin** [esphome/issues#3276]
### The problem

Hi,
yesterday I tried to use the SHTC3 sensor under a TCA9548a i2c bus multiplexer. When the ESP32-POE-ISO board boot I can see from the logs I have a CRC error when the system is trying to read the sensor ID. If I connect directly the sensor to the i2c bus (without the TCA9548a) I can use the sensor with no problem.
I checked the TCA9548a connecting other devices in multiple virtual i2c bus line with no problem. When I connect also the SHTC3 the entirely virtual i2c bus line doesn't work.
I checked the cable connection (it's 5cm long) and there's no problem from it.

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

ESP32-POE-ISO

### Component causing the issue

i2c shtc3

### Example YAML snippet

```yaml
i2c:
  sda: 13
  scl: 16
  scan: true
  id: bus_a
  frequency: 50kHz

tca9548a:
  - address: 0x70
    id: multiplex0
    i2c_id: bus_a
    channels:
      - bus_id: multiplex0channel0
        channel: 0
      - bus_id: multiplex0channel1
        channel: 1
      - bus_id: multiplex0channel2
        channel: 2
      - bus_id: multiplex0channel3
        channel: 3
      - bus_id: multiplex0channel4
        channel: 4
      - bus_id: multiplex0channel5
        channel: 5
      - bus_id: multiplex0channel6
        channel: 6
      - bus_id: multiplex0channel7
        channel: 7

pcf8574:
  - id: 'pcf8574_hub_1'
    i2c_id: multiplex0channel0
    address: 0x20
    pcf8575: false

sensor:
  - platform: shtcx
    i2c_id: multiplex0channel2
    temperature:
      name: "Room Temperature"
    humidity:
      name: "Room Humidity"
    address: 0x70
    update_interval: 12s

  - platform: bh1750
    i2c_id: multiplex0channel2
    name: "Room Illuminance"
    address: 0x23
    update_interval: 12s
```
