### ISSUE TITLE
Boot Loop on AI Thinker ESP32-C Modules (2Mb Variant)

### ISSUE THREAD

**Issue by dmberrycom** [esphome/issues#3277]
### The problem

ESPHome image on ESP-C3-32S (2Mb Variant) is stuck in a boot loop after programming 

ESP-C3-13U (4Mb Variant) - Works Fine
ESP-C3-32S (2M Variant) - Boot Loop

https://docs.ai-thinker.com/en/esp32c3

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.5.4

### What platform are you using?

ESP32-IDF

### Board

Ai thinker ESP32-C3-32-S - 2MB 

### Component causing the issue

esphome

### Example YAML snippet

```yaml
esphome:
  name: esp32-c3-2mb
  platformio_options:
    board_build.flash_mode: dio  (tried adding these settings but they don't seem to apply)
    board_build.flash_size: 2MB  (tried adding these settings but they don't seem to apply)
    
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:
 deassert_rts_dtr: true
```

### Anything in the logs that might be useful for us?

```txt
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0xd (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:QIO, clock div:1
load:1z3fcd6100,len:0x19a0
ets_loader.c 78
```
