### ISSUE TITLE
pin validation

### ISSUE THREAD

**Issue by glmnet** [esphome/issues#3279]
### The problem

I've just tried this code which compiles happily
 
but does not work, it seems that gpio is not preconfiguring pins as input? I replaced to arduino and it complained that the pin mode is not valid (pull up) it did not complain pin was not an input so that was even weird.

Should pin be validated to be either input or output? (See logs)

### Which version of ESPHome has the issue?

2022.06.0-dev

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

NA

### What platform are you using?

ESP32-IDF

### Board

devkit

### Component causing the issue

gpio / pin

### Example YAML snippet

```yaml
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

binary_sensor:
  - platform: gpio
    pin:
      mode:
        pullup: True
      number: GPIO23
    name: Switch 1
```

### Anything in the logs that might be useful for us?

```txt
[19:04:24][D][esp-idf:000]: I (43) gpio: GPIO[23]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 
1| Pulldown: 0| Intr:0
```

### Additional information

I could send a fix for this no problem but wanted to discuss the approach first
