### ISSUE TITLE
Unexpected error with relay on newer firmwares

### ISSUE THREAD

**Issue by puerto-rico** [esphome/issues#3280]
### The problem

I flashed a new firmware via the update function to discover some odd behavior on the esp. after reboot

it has been running flawless with a 2x relay attached for more than a year. And that relay does not turn on a boot. default is off.
But something happened with one of the latest firmwares, not sure if is 3.2.0 but it worked 2 months ago.

What happens is that when the esp reboot's or get's powered on the relay turns on for a fraction of a sec. and then the relay closes again. this has never happened before. it is running: espressif8266 @ 3.2.0

### Which version of ESPHome has the issue?

ESPHome version 2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

 2022.3.8

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

Firmware

### Example YAML snippet

```yaml
esphome:
  name: hormann

esp8266:
  board: nodemcuv2

#Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "hidden"

wifi:
  ssid: hidden
  password: hidden

switch:
  - platform: gpio
    pin: 14
    inverted: True
    id: realy
    name: "Hormann Open"
    icon: "mdi:garage-open"
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: realy
  - platform: gpio
    pin: 12
    inverted: True
    id: closed
    name: "Hormann Closed"
    icon: "mdi:garage"
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: closed
```
