### ISSUE TITLE
PN532 over I2C stops responding after a while

### ISSUE THREAD

**Issue by chrispernold** [esphome/issues#3281]
### The problem

I had this RC522 module for a while in a jukebox for my kids to play different MP3s but was always leaning towards trying out the PN532 module as it seemed more integrated to the ESPHome landscape. Before moving over I used a version of the https://github.com/HausnerR/esphome-door-lock code to get it working similar to `on_tag `and `on_tag_removed`.

**Fast forwarding a few years and I've replaced the RC522 with a PN532 module, hoping I could stick to the default PN532 code in ESPHome and remove the custom scripts. While it works immediately after a boot of the NodeMCUV2 (over I2C) it stops responding after a while, let's say a few hours. Only a hard reset (unplugging the power cable) will get it back to responding to RFID cards/tags.**

The setup looks like the following: 

ESP device with RFID PN532 module reads a RFID card/tag e.g. 12-34-56-78 and send this information to a Node Red (via HA) flow that triggers an MP3 to be played on one of my Sonos speakers. 

If the RFID card/tag is removed it sends a 00-00-00-00 state that in turn pause the Sonos.

### Which version of ESPHome has the issue?

v2022.4.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.5

### What platform are you using?

ESP8266

### Board

NODEMCU V2

### Component causing the issue

PN532 over I2C

### Example YAML snippet

```yaml
esphome:
  name: node2-jukebox
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "XXXXXXX"
  password: "XXXXXXX"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: XXXXXXX
    # Set this to the IP address of the router. Often ends with .1
    gateway: XXXXXXX
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable logging
logger:
  level: debug
  
# Enable OTA updates
ota:
  password: "XXXXXXX"

# Enable Home Assistant API
api:
  password: "XXXXXXX"

switch:
  - platform: restart
    name: "node2 jukebox restart"

i2c:
  sda: D4
  scl: D3
  scan: true
  #id: pn532_board
  #frequency: 400kHz

pn532_i2c: # or rc522_i2c
  id: pn532_board
  update_interval: 1s
  on_tag:
    then:
    - text_sensor.template.publish:
        id: rfid_tag
        state: !lambda |
          return x;
    - delay: 0.2s #to fix slow component
  on_tag_removed:
    then:
    - text_sensor.template.publish:
        id: rfid_tag
        state: !lambda 'return "00-00-00-00";'

text_sensor:
  - platform: template
    name: "RFID Tag"
    id: rfid_tag
  - platform: template
    name: "RFID Tag removed"
    id: rfid_tag_removed
```

### Anything in the logs that might be useful for us?

```txt
It doesn't show any errors in debug mode and in very_verbose it shows amongst other errors the following 

Timed out waiting for readiness from PN532!

Component pn532 took a long time for an operation (0.17 s). <- this varies
```

### Additional information

Someone at the [HA community](https://community.home-assistant.io/t/no-tag-scnned-esp32-with-pn532-testes-oder-spi-and-i2c/348601/3) suggested the D1 mini board instead of the NodeMCU. So I'm thinking this could be a HW error where the signal gets out of sync somehow and the board is unable to get it back to sync. What do you think?
