### ISSUE TITLE
restore_from_flash causes boot loops after OTA

### ISSUE THREAD

**Issue by platima** [esphome/issues#3282]
### The problem

When I set `restore_from_flash: true` then flash via OTA I get some very odd behavior. Basically it'll flash, then it reboots, and then randomly reboots every 1-10s. It joins the wifi for a split second, but never long enough to flash again.

If I then flash with serial, it works fine, until the next OTA.

If I flash serial with `restore_from_flash: true`, then while it's running flash with `restore_from_flash: false` via OTA, it works fine, so it appears to be something specific to `restore_from_flash: true` _after_ an OTA flash.

Happy to grab any logs required!

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.5.4

### What platform are you using?

ESP8266

### Board

esp8285

### Component causing the issue

board

### Example YAML snippet

```yaml
esphome:
  name: csh-plgusbpm

esp8266:
  board: esp8285
  restore_from_flash: true
  
preferences:
  flash_write_interval: 1min
```
