### ISSUE TITLE
Wemos D1 Mini with DS18B20 no sensors found

### ISSUE THREAD

**Issue by JBS5** [esphome/issues#329]
On a Wemos D1 Mini v3.1 I'm trying to get a DS18B20 to work following this diagram (not a Wemos D1 on the picture, I know :-))

![](https://media.discordapp.net/attachments/429907082955718657/580458135236509697/Sketch_bb.png)

Black on Wemos GND
Red on Wemos 3V3
Yellow on Wemos D2
4.7K resistor as on the picture

My YAML in ESPHome:
```

esphome:
  name: projectname
  platform: ESP8266
  board: d1_mini


wifi:
  ssid: 'xxxx'
  password: 'xxxx'
  manual_ip:
# Set this to the IP of the ESP
    static_ip: 192.168.178.229
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0  


# Enable logging
logger:
  level: DEBUG


# Enable Home Assistant API
api:

ota:

dallas:
  - pin: GPIO4

```

Log:
[14:40:43][C][sensor.dallas:081]: DallasComponent:
[14:40:43][C][sensor.dallas:082]:   Pin: GPIO4 (Mode: OUTPUT)
[14:40:43](Message skipped because it was too big to fit in TCP buffer - This is only cosmetic)
[14:40:43][W][sensor.dallas:086]:   Found no sensors!

Any clue what I am missing?
