### ISSUE TITLE
A4988 frequency slow

### ISSUE THREAD

**Issue by camnewnham** [esphome/issues#3297]
### The problem

I'm setting up a stepper component and I have run into an issue where the motor won't turn any faster, but isn't having any torque issues and is otherwise running as normal.

The motor is configured at 1/16 microsteps, and won't turn faster than 1.5RPS. At 200 steps per rev this means the pin state is toggled at around 4800Hz. I've tested with multiple drivers (DRV8825, A4988 and TMC2100) all to the same result.

Increasing `stepper.set_speed` beyond this point doesn't have any effect. It seems that the loop speed is the limiting factor. 

ESPHome code:
```
script:
  - id: stop_stepper
    then: 
      - stepper.report_position:
          id: my_stepper
          position: 0
      - stepper.set_target:
          id: my_stepper
          target: 0
      - output.turn_off: led1
      
  - id: run_stepper
    then:
      - output.turn_on: led1
      - script.execute: stop_stepper
      - stepper.set_speed:
          id: my_stepper
          speed: 10000 steps/s
      - stepper.set_target:
          id: my_stepper
          target: -10000000
      - wait_until:
          condition:
            binary_sensor.is_on: endstop_0
          timeout: 30s
      - script.execute: stop_stepper

stepper:
  - platform: a4988
    id: my_stepper
    sleep_pin:
      number: D1
      inverted: true
    step_pin:
      number: D2
    dir_pin: 
      number: D3
      inverted: false
    max_speed: 10000 steps/s
    acceleration: inf
    deceleration: inf
```

For comparison, this loop running from an Arduino IDE deployment does manage to increase the frequency far beyond this:
```
void loop()
{
    digitalWrite(STEP,HIGH);
    delayMicroseconds(25);
    digitalWrite(STEP,LOW);
    delayMicroseconds(25);
}
```

Is there anything I can do to increase the loop frequency? Or could multiple steps be performed in the loop?

https://github.com/esphome/esphome-core/blob/254d059945932adb64f5cbe8f4928ea19b4f6f00/src/esphome/stepper/a4988.cpp#L32

Also: I have noticed that the stepper can be much choppier when controlled from ESPHome vs. the above Arduino IDE sketch - I assume this is also a loop timing issue?

### Which version of ESPHome has the issue?

2022.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.5.5

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

stepper
