### ISSUE TITLE
Wemos D1 Mini with DS18B20 no sensors found

### ISSUE THREAD

**Issue by JBS5** [esphome/issues#330]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
ESPHome 1.12.2 add-on on Hass.io in Docker on a NUC running Ubuntu.

**ESP (ESP32/ESP8266, Board/Sonoff):**
Wemos D1 Mini

**Affected component:**
dallas

**Description of problem:**
On a Wemos D1 Mini v3.1 I'm trying to get a DS18B20 to work following this diagram (not a Wemos D1 on the picture, I know :-))

![](https://media.discordapp.net/attachments/429907082955718657/580458135236509697/Sketch_bb.png)

Black on Wemos GND
Red on Wemos 3V3
Yellow on Wemos D2
4.7K resistor as on the picture

Any clue what I am missing?

**Problem-relevant YAML-configuration entries:**

I did not entered a sensor in the YAML because I want to get the address of the sensor first based on this instruction: https://esphome.io/components/sensor/dallas.html#getting-sensor-ids
Unfortunately, no 'found sensors' where displayed like shown on the instruction.

```yaml
esphome:
  name: projectname
  platform: ESP8266
  board: d1_mini


wifi:
  ssid: 'xxxx'
  password: 'xxxx'
  manual_ip:
# Set this to the IP of the ESP
    static_ip: 192.168.178.229
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0  


# Enable logging
logger:
  level: DEBUG


# Enable Home Assistant API
api:

ota:

dallas:
  - pin: GPIO4

```

**Traceback (if applicable):**
Log:
[14:40:43][C][sensor.dallas:081]: DallasComponent:
[14:40:43][C][sensor.dallas:082]:   Pin: GPIO4 (Mode: OUTPUT)
[14:40:43](Message skipped because it was too big to fit in TCP buffer - This is only cosmetic)
[14:40:43][W][sensor.dallas:086]:   Found no sensors!
```

```

**Additional information and things you've tried:**
I have tried some other pins for the yellow data wire.
