### ISSUE TITLE
TTGO T-Camera V162: Camera not working after update to latest ESPHome

### ISSUE THREAD

**Issue by EduardTheThird** [esphome/issues#3300]
### The problem

TTGO T-Camera V162 worked perfectly but after updating to the latest ESPHome the camera is not working anymore.
The error in the logs are: [13:20:31][E][esp32_camera:095]:   Setup Failed: ERROR.

The camera worked perfectly with the previous version and failed after updating to the newer version, without any yaml changes.

### Which version of ESPHome has the issue?

2022.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2022.5.5

### What platform are you using?

ESP32

### Board

TTGO T-Camera V162

### Component causing the issue

esp32_camera

### Example YAML snippet

```yaml
esphome:
  name: livingroom
  platform: ESP32
  board: esp-wrover-kit

binary_sensor:
  - platform: gpio
    pin: GPIO19
    name: living room pir
    device_class: motion
    filters:
      - delayed_off: 1s
      
  - platform: gpio
    pin:
      number: GPIO15
      inverted: True
    name: living room button
    filters:
      - delayed_off: 50ms

  - platform: status
    name: living room status

sensor:
  - platform: wifi_signal
    name: living room wifi signal
    update_interval: 10s
  - platform: uptime
    name: living room uptime
  - platform: bme280
    temperature:
      name: living room temperature
      oversampling: 16x
    pressure:
      name: living room temperature pressure
    humidity:
      name: living room humidity
    update_interval: 60s

    
esp32_camera:
  external_clock:
    pin: GPIO4
    frequency: 20MHz
  i2c_pins:
    sda: GPIO18
    scl: GPIO23
  data_pins: [GPIO34, GPIO13, GPIO14, GPIO35, GPIO39, GPIO38, GPIO37, GPIO36]
  vsync_pin: GPIO5
  href_pin: GPIO27
  pixel_clock_pin: GPIO25
  jpeg_quality: 10
  vertical_flip: true
  horizontal_mirror: false
  name: livingroom
  
i2c:
  sda: GPIO21
  scl: GPIO22

font:
  - file: "fonts/times-new-roman.ttf"
    id: tnr1
    size: 20
  - file: "fonts/times-new-roman.ttf"
    id: tnr2
    size: 35

time:
  - platform: homeassistant
    id: homeassistant_time

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    rotation: 180°
    address: 0x3C
    lambda: |-
      it.strftime(64, 0, id(tnr1), TextAlign::TOP_CENTER,"%d-%m-%Y", id(homeassistant_time).now());
      it.strftime(64, 64, id(tnr2), TextAlign::BASELINE_CENTER, "%H:%M", id(homeassistant_time).now());

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "!OTAPASSWORDSECRET"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Fallback Hotspot"
    password: "!PASSWORDSECRET"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
[13:20:31][C][esp32_camera:048]: ESP32 Camera:
[13:20:31][C][esp32_camera:049]:   Name: livingroom
[13:20:31][C][esp32_camera:050]:   Internal: NO
[13:20:31][C][esp32_camera:052]:   Data Pins: D0:34 D1:13 D2:14 D3:35 D4:39 D5:38 D6:37 D7:36
[13:20:31][C][esp32_camera:053]:   VSYNC Pin: 5
[13:20:31][C][esp32_camera:054]:   HREF Pin: 27
[13:20:31][C][esp32_camera:055]:   Pixel Clock Pin: 25
[13:20:31][C][esp32_camera:056]:   External Clock: Pin:4 Frequency:20000000
[13:20:31][C][esp32_camera:057]:   I2C Pins: SDA:18 SCL:23
[13:20:31][C][esp32_camera:058]:   Reset Pin: -1
[13:20:31][C][esp32_camera:076]:   Resolution: 640x480 (VGA)
[13:20:31][E][esp32_camera:095]:   Setup Failed: ERROR
```

### Additional information

I follow the following guide:
https://esphome.io/components/esp32_camera.html#configuration-for-ttgo-t-camera-v162
