### ISSUE TITLE
Not possible to use HA feature to reduce entity names

### ISSUE THREAD

**Issue by Bascht74** [esphome/issues#3301]
### The problem

I can assign the esphome device a name with: 

```
substitutions:
  upper_devicename: "Lampe Aussen Hausbeleuchtung"
  devicename: "lampe-aussen-hausbeleuchtung" #(upper case and space not allowed)
esphome:
  name: $devicename
```

but I cannot assign a friendly name for Home Assistant: 
`friendly_name: ${upper_devicename} #--> doesn't work`

If I give e.g. a light entity a name: 
```
light:
  - platform: binary
[...]
    name: "${upper_devicename} Balkon"
```

It doesn't show the right way in Home Assistant: 
![image](https://user-images.githubusercontent.com/66269310/169696146-a67d058f-f791-4541-9e2f-a54eb6174e15.png)

If I rename the device name into the "friendly one" it works: 
![image](https://user-images.githubusercontent.com/66269310/169696178-55308713-496b-4de4-867d-34f891b125ce.png)

But how can I set a "friendly" device name with uppercase and spaces via the yaml code?

Sebastian

### Which version of ESPHome has the issue?

2022.5.0 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.5.x

### What platform are you using?

ESP32-IDF

### Board

every

### Component causing the issue

esphome

### Example YAML snippet

```yaml
substitutions:
  upper_devicename: "Lampe Aussen Hausbeleuchtung"
  devicename: "lampe-aussen-hausbeleuchtung"

esphome:
  name: $devicename
#  friendly_name: ${upper_devicename} --> missing?

light:
  - platform: binary
    id: light1
    output: relay1
    name: "${upper_devicename} Balkon"
```

### Anything in the logs that might be useful for us?

```txt
nothing
```

### Additional information

It would be an alternative, if the `esphome name` accepts upper case and spaces and translates to lowe case and "-" were needed.

If you would be able to set an uppercase device name via the yaml you can make use of the truncating in Home Assistant (would be much clearer)
