### ISSUE TITLE
Bedjet: Error: Failed to call service climate/set preset mode.

### ISSUE THREAD

**Issue by mwolter805** [esphome/issues#3303]
### The problem

Within the Home Assistant frontend, when selecting a preset mode via the climate entity created by the integration, the following error is received.

Interestingly, the preset is sent and applied to the BedJet. So it works, but there is a toast error HA. 

Also, there are no errors related to this in the Home Assistant logs.  

![Screen Shot 2022-05-22 at 2 21 15 PM](https://user-images.githubusercontent.com/24851651/169716555-af730516-f9d9-4bc7-8aa6-75358f99352d.jpg)
![IMG_4085](https://user-images.githubusercontent.com/24851651/169716562-1f8f62da-a6a3-46d5-a0ab-f79c8de4f641.PNG)

```
Failed to call service climate/set preset mode. string value is None for dictionary value @ data['preset_mode']
```
Calling the service via developer tools does not have the same error toast.
```
service: climate.set_preset_mode
target:
  entity_id: climate.bed_esp32_matts_bedjet
data:
  preset_mode: "M1"
```

### Which version of ESPHome has the issue?

2022.5.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.4.6

### What platform are you using?

ESP32

### Board

Olimex ESP32-POE

### Component causing the issue

BedJet

### Example YAML snippet

```yaml
substitutions:
  name: bed-esp32
  friendly_name: Bed-ESP32
  ip_address: 192.168.6.12

esphome:
  name: $name
  platform: ESP32
  board: esp32-poe

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  use_address: $ip_address

mdns:
  disabled: true
  
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret api_password
  reboot_timeout: 0s

# Enable over-the-air flashing
ota:
  password: !secret ota_password
  on_begin:
    then:
      - logger.log: "Disconnecting BedJet for OTA update..."
      - switch.turn_off: matts_bedjet_enable

time:
  - platform: homeassistant
    id: time_ha
    
logger:
  baud_rate: 0 # disable UART logging
  level: error  # normal level for logger
#  level: debug # only use this level when debugging an issue
#  level: VERY_VERBOSE # only use this level if debug is not producing enough info to debug an issue
  logs:
    esp32_ble_tracker: error # normal level for this function
#    esp32_ble_tracker: debug # enable when discovering BLE devices

# Include the following until the include is added to bedjet, most likely in version 2022.6
external_components:
  - source: github://pr#3490
    components: [bedjet]

# Uptime Sensor    
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: utime

esp32_ble_tracker:

ble_client:

# Matts BedJet - Address
  - mac_address: 11:11:11:11:11:11
    id: matts_bedjet_ble

climate:

# Matts BedJet - Climate Entity
  - platform: bedjet
    id: matts_bedjet
    name: $friendly_name Matts BedJet
    ble_client_id: matts_bedjet_ble
    time_id: time_ha
    icon: mdi:hvac
    visual:
      min_temperature: 70 °F
      max_temperature: 85 °F

switch:

# Matts BedJet - Enable BLE
  - platform: ble_client
    ble_client_id: matts_bedjet_ble
    id: matts_bedjet_enable
    name: $friendly_name Matts BedJet Enable BLE
    icon: mdi:bluetooth-connect
```

### Anything in the logs that might be useful for us?

```txt
There are no errors in home assistant or on the ESP.
```
