### ISSUE TITLE
daly_bms component don`t read first 4 cells

### ISSUE THREAD

**Issue by Micha87** [esphome/issues#3306]
### The problem

hi,
unfortunately the DALY_BMS component does not read my first 4 cells. 

Installed are 16 cells, the values of the other cells come. 
Can I write or read any logs with here?

Thanks.

BR

### Which version of ESPHome has the issue?

 2022.5.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

Wemos D1

### Component causing the issue

daly_BMS

### Example YAML snippet

```yaml
esphome:
  name: dalybms

esp8266:
  board: d1_mini

web_server:
  port: 80
# Enable logging
logger:
 baud_rate: 0
# Enable Home Assistant API
api:

ota:
  password: "*****"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dalybms Fallback Hotspot"
    password: "WackYd84P5UF"

captive_portal:
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

daly_bms:
  update_interval: 20s

sensor:
  - platform: daly_bms
    voltage:
      name: "Battery Voltage"
    current:
      name: "Battery Current"
    battery_level:
      name: "Battery Level"
    max_cell_voltage:
      name: "Max Cell Voltage"
    max_cell_voltage_number:
      name: "Max Cell Voltage Number"
    min_cell_voltage:
      name: "Min Cell Voltage"
    min_cell_voltage_number:
      name: "Min Cell Voltage Number"
    max_temperature:
      name: "Max Temperature"
    max_temperature_probe_number:
      name: "Max Temperature Probe Number"
    min_temperature:
      name: "Min Temperature"
    min_temperature_probe_number:
      name: "Min Temperature Probe Number"
    remaining_capacity:
      name: "Remaining Capacity"
    cells_number:
      name: "Cells Number"
    temperature_1:
      name: "Temperature 1"
    temperature_2:
      name: "Temperature 2"
    cell_1_voltage:
      name: "Cell 01 Voltage"
    cell_2_voltage:
      name: "Cell 02 Voltage"
    cell_3_voltage:
      name: "Cell 03 Voltage"
    cell_4_voltage:
      name: "Cell 04 Voltage"
    cell_5_voltage:
      name: "Cell 05 Voltage"
    cell_6_voltage:
      name: "Cell 06 Voltage"
    cell_7_voltage:
      name: "Cell 07 Voltage"
    cell_8_voltage:
      name: "Cell 08 Voltage"  
    cell_9_voltage:
      name: "Cell 09 Voltage"
    cell_10_voltage:
      name: "Cell 10 Voltage"
    cell_11_voltage:
      name: "Cell 11 Voltage"
    cell_12_voltage:
      name: "Cell 12 Voltage"
    cell_13_voltage:
      name: "Cell 13 Voltage"
    cell_14_voltage:
      name: "Cell 14 Voltage"
    cell_15_voltage:
      name: "Cell 15 Voltage"
    cell_16_voltage:
      name: "Cell 16 Voltage"
text_sensor:
  - platform: daly_bms
    status:
      name: "BMS Status"


binary_sensor:
  - platform: daly_bms
    charging_mos_enabled:
      name: "Charging MOS"
    discharging_mos_enabled:
      name: "Discharging MOS"  
      
mqtt:
  broker: 192.168.11.10
  port: 1885
  username: ***
  password: ***
```

### Anything in the logs that might be useful for us?

```text
# logs here
```

[logs_dalybms_upload.txt](https://github.com/esphome/issues/files/8756773/logs_dalybms_upload.txt)
