### ISSUE TITLE
BedJet - HA frontend takes a long time to update (~30s)

### ISSUE THREAD

**Issue by mjoshd** [esphome/issues#3308]
### The problem

The BedJet accepts commands and responds right away but the HA front end takes some time to reflect changes (up to ~30 seconds).

BedJet info (from app):
```
App         V1.0.4 (6)
BedJet 3    V1.20 (140)   
Remote      V1.20 (182)
```

### Which version of ESPHome has the issue?

2022.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.5.5

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

bedjet

### Example YAML snippet

```yaml
# Full yaml (sensitive info redacted)

# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  device_name: REDACTED
  friendly_name: REDACTED
  icon: "mdi:bed-outline"

# https://esphome.io/components/esphome.html
esphome:
  name: ${device_name}

# https://esphome.io/devices/esp32.html
esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# https://esphome.io/components/logger.html
logger:
  baud_rate: 0

# https://esphome.io/components/api.html
api:
  password: REDACTED
  encryption:
    key: REDACTED

# https://esphome.io/components/ota.html
ota:
  password: REDACTED
  on_begin:
    then:
      - logger.log: "Disconnecting clients for OTA update..."
      - switch.turn_off: bedjet_1_ble_connection

# https://esphome.io/components/wifi.html
wifi:
  ssid: REDACTED
  password: REDACTED



##############################################################
##############################################################
##############################################################



# https://esphome.io/components/ble_client.html
ble_client:
  - mac_address: REDACTED
    id: ble_bedjet_1



# https://esphome.io/components/button/restart.html
# https://esphome.io/components/climate/bedjet.html#lambda-calls
button:
  - platform: restart
    name: ${friendly_name} Restart
  - platform: template
    name: "Check BedJet Firmware"
    on_press:
      then:
      - lambda: |-
          id(climate_bedjet_1).upgrade_firmware();



# https://esphome.io/components/climate/bedjet.html
# https://esphome.io/components/climate/index.html#base-climate-configuration
climate:
  - platform: bedjet
    id: climate_bedjet_1
    name: ${friendly_name}
    ble_client_id: ble_bedjet_1
    time_id: homeassistant_time
    # icon: ${icon}
    visual:
      min_temperature: 18.8889 °C
      max_temperature: 42.7778 °C



# https://esphome.io/components/esp32_ble_tracker.html
esp32_ble_tracker:
  scan_parameters:
    interval: 0s
    window: 0s
    # active: false


# https://esphome.io/components/switch/ble_client.html
# https://esphome.io/components/switch/restart.html
switch:
  - platform: ble_client
    ble_client_id: ble_bedjet_1
    name: ${friendly_name} BLE Connection
    id: bedjet_1_ble_connection



# https://esphome.io/components/time.html#home-assistant-time-source
time:
  - platform: homeassistant
    id: homeassistant_time
```

### Additional information

Creating issue [as requested](https://community.home-assistant.io/t/bedjet-integration/144822/24?u=mjoshd).
