### ISSUE TITLE
remote_transmitter: transmit_nec --> value must be at most 65535

### ISSUE THREAD

**Issue by moonraker46** [esphome/issues#3309]
### The problem

I do migrate my ESP devices step by step from Tasmota to ESPHome.

One device has an IRsender to send commands to a cheap lampion fairy light https://www.amazon.de/gp/product/B07SBZPKW9/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

This worked so far with Tasmota (I got those IR Codes with an IR Receiver and the official remote).

But using the same commands with ESPHome leads to the issue that ESPHome tells me when compiling the config: value must be at most 65535.

I guess this is because the ESPHome NEC IR command wants to use a 16Bit command but I do have a 32bit command. 

How can this be fixed?

```
remote_transmitter:
  pin: 16
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: "mode5"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x2FD09F6
        command: 0x40BF906F 
```

```
INFO Reading configuration /config/lichterkette.yaml...
Failed config

switch.template: [source /config/lichterkette.yaml:68]
  platform: template
name: mode5
  
  value must be at most 65535.
  turn_on_action: 
    remote_transmitter.transmit_nec: 
      
      value must be at most 65535.
      address: 50137590
      command: 1086296175
```

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

esp8285

### Component causing the issue

remote__transmitter

### Example YAML snippet

```yaml
remote_transmitter:
  pin: 16
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: "mode5"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x2FD09F6
        command: 0x40BF906F
```
