### ISSUE TITLE
Problems to compile custom sensor

### ISSUE THREAD

**Issue by oli737** [esphome/issues#3313]
### The problem

Having problem compile. Compile stop with error.
Same error for other code i try to compile.

Thank you very much.

### Which version of ESPHome has the issue?

2022.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant Core 2022.5.5 Home Assistant Supervisor 2022.05.3 Home Assistant OS 8.1 Kernel version 5.15.32-v8 Agent version 1.2.1

### What platform are you using?

ESP8266

### Board

Custom

### Component causing the issue

idk

### Example YAML snippet

```yaml
esphome:
  name: balkonuv
  platform: ESP8266
  board: esp01_1m

  includes:
    - SI1145.h

  libraries:
    - Wire
    - SPI
    - "https://github.com/adafruit/Adafruit_BusIO"
    - "https://github.com/adafruit/Adafruit_SI1145_Library"

wifi:
  networks:
    - ssid: "###censored###"
      password: "###censored###"
    - ssid: "###censored###"
      password: "###censored###" 
    - ssid: "###censored###"
      password: "###censored###"  
  power_save_mode: high
  output_power: 20
  manual_ip:
    static_ip: 192.168.178.19
    gateway: 192.168.178.1
    subnet: 255.255.255.0

logger:

api:

ota:

i2c:
    sda: GPIO5
    scl: GPIO4
    frequency: 100kHz

sensor:
  - platform: custom
    lambda: |-
      auto UV_sensor = new SI1145_sensor();
      App.register_component(UV_sensor);
      return {UV_sensor->visible_sensor, UV_sensor->ir_sensor, UV_sensor->uvindex_sensor};

    sensors:
      - name: "Visible Light"
        accuracy_decimals: 0
      - name: "IR Light"
        accuracy_decimals: 0
      - name: "UV Index"
        accuracy_decimals: 0

  - platform: adc
    id: bat_vcc
    pin: A0
    name: Battery
    update_interval: 15s
    filters:
      - multiply: 5.37
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/balkonuv.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing balkonuv (board: esp01_1m; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <Wire> 1.0
|-- <SPI> 1.0
|-- <Adafruit BusIO> 1.11.6+sha.515f63f
|-- <Adafruit SI1145 Library> 1.2.0+sha.f1b8257
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
Compiling /data/balkonuv/.pioenvs/balkonuv/src/main.cpp.o
/config/esphome/balkonuv.yaml: In lambda function:
/config/esphome/balkonuv.yaml:47:28: error: expected type-specifier before 'SI1145_sensor'
   47 |       auto UV_sensor = new SI1145_sensor();
      |                            ^~~~~~~~~~~~~
/config/esphome/balkonuv.yaml:49:89: error: could not convert '{<expression error>, <expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::sensor::Sensor*>'
   49 |       return {UV_sensor->visible_sensor, UV_sensor->ir_sensor, UV_sensor->uvindex_sensor};
      |                                                                                         ^
      |                                                                                         |
      |                                                                                         <brace-enclosed initializer list>
*** [/data/balkonuv/.pioenvs/balkonuv/src/main.cpp.o] Error 1
========================= [FAILED] Took 11.88 seconds =========================
```

### Additional information

none
