### ISSUE TITLE
Online ESP01 with static IP shows as offline, though it's online.

### ISSUE THREAD

**Issue by emiellr** [esphome/issues#3315]
### The problem

When an ESP is configured with a static IP in the YAML config file, ESPHome will still (I am assuming) use mDNS to check whether it's actually online. mDNS doesn't quite function properly on my network, so it will say offline while it definitely and verifiably isn't.

![image](https://user-images.githubusercontent.com/17954308/170451336-7eb47efd-932f-4745-8e7e-8b23ef160be5.png)

### Which version of ESPHome has the issue?

22.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.4.4

### What platform are you using?

ESP8266

### Board

ESP01s 1MB flash

### Component causing the issue

n/a

### Example YAML snippet

```yaml
esphome:
  name: shutter-dev

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "[redacted]"

ota:
  password: "[redacted]"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: [redacted]
    gateway: [redacted]
    subnet: [redacted]
    dns1: [redacted]

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "[redacted]"
    password: "[redacted]"

captive_portal:
    
switch:
  - platform: gpio
    name: Relay 1
    pin: GPIO0
    id: relay_1
    inverted: true
    restore_mode: always off
    icon: "mdi:window-shutter"
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay_2
    on_turn_off:
      - delay: 500ms
      - switch.turn_on: relay_2
    
    
  - platform: gpio
    internal: true
    name: Relay 2
    pin: GPIO2
    id: relay_2
    inverted: true
    restore_mode: always off
    icon: "mdi:window-shutter"
```

### Anything in the logs that might be useful for us?

```txt
n/a
```

### Additional information

n/a
