### ISSUE TITLE
CAN bus integration: using variable can_id_mask throws error

### ISSUE THREAD

**Issue by Jpsy** [esphome/issues#3321]
### The problem

Usage of the variable `can_id_mask` in the component CAN bus throws when compiling.
Even the example from the [ESPHome docs](https://esphome.io/components/canbus.html) does not compile:

The error message complains about `can_id` but it is actually triggered by using `can_id_mask`:
```
  Must be string, got <class 'NoneType'>. did you forget putting quotes around the value?.
  on_frame: 
    - 
      Unable to find action with the name 'can_id'.
      can_id: 64
      can_id_mask: 520110016
      use_extended_id: True
      remote_transmission_request: False
      then: 
        - lambda: return;
```

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.5.5

### What platform are you using?

ESP8266

### Board

D1 mini

### Component causing the issue

CAN bus

### Example YAML snippet

```yaml
# example from the docs (only spi & platform mcp2515 added)
spi:
  id: Mcp2515SPI
  clk_pin: D0
  mosi_pin: D1
  miso_pin: D2

canbus:
  - platform: mcp2515
    cs_pin: D5
    can_id: 4
    on_frame:
    - can_id:      0b00000000000000000000001000000
      can_id_mask: 0b11111000000000011111111000000
      use_extended_id: true
      remote_transmission_request: false
      then:
        - lambda: |-
            return;
```
