### ISSUE TITLE
yaml keys replaced

### ISSUE THREAD

**Issue by jimtng** [esphome/issues#3322]
### The problem

the substitution variable name, cannot be "no" (or I'd guess "false" etc)

Is this by design? It seems that the conversion is applied to keys when it shouldn't 

### Which version of ESPHome has the issue?

dev

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
substitutions:
  name: something
  no: nodemcu # <--- The "no" will be substituted into "False" here

esphome:
  name: ${name}
  name_add_mac_suffix: true
  platform: esp8266
  board: ${no} # <------ couldn't find a match because now substitutions dict has {"False": "nodemcu"}
```
