### ISSUE TITLE
ESP8266Wifi lib not found with version 2022.05.01

### ISSUE THREAD

**Issue by s3rgi** [esphome/issues#3324]
### The problem

With version 2022.05.01, for the esp8266 chip it does not find the wifi library to start the firmware compilation.
In version 2022.05.00 it compiles perfectly, see screenshots.

![2022-05-29_10-25_2022_5_1](https://user-images.githubusercontent.com/29262359/170859636-f81b7975-0e9d-41c6-8eac-0a77b270f37c.png)

![2022-05-29_10-32_2022_5_0](https://user-images.githubusercontent.com/29262359/170859688-6b12ee7d-cc88-4978-ba84-df6b00ec64fe.png)

### Which version of ESPHome has the issue?

2022.05.01

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2022.5.5

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

ESP8266WiFi

### Example YAML snippet

```yaml
esphome:
  name: lampsalhabgran
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: MyWifi
  password: superpass
  fast_connect: yes
```
