### ISSUE TITLE
Display Pages of st7920 Problem

### ISSUE THREAD

**Issue by SciTii** [esphome/issues#3326]
### The problem

It looks like pages are not working for the ST7920 display. 

When i do put traditional Lambda it displays it correctly but when i put 2 pages it is displaying nothing.

I have checked the same code for SD1306 and it is working without any problems

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.5.3

### What platform are you using?

ESP32

### Board

ESP32 R1 

### Component causing the issue

Display

### Example YAML snippet

```yaml
esphome:
  name: hydroponika-stacja-1

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:

api:
  password: !secret api_password
  encryption:
        key: !secret encryption_key
ota:
  safe_mode: true
  password: !secret ota_password
  id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  
  ap:
    ssid: "Hydroponika-Stacja-1"
    password: !secret wifi_password_fallback

captive_portal:

spi:
  clk_pin: GPIO19
  mosi_pin: GPIO13
  
font:
  - file: "fonts/conthrax.ttf"
    id: font1
    size: 9
    
  - file: "fonts/conthrax.ttf"
    id: font2
    size: 33

display:
  - platform: st7920
    setup_priority: -300
    width: 128
    height: 64
    id: display1
    cs_pin:
      number: GPIO22
      inverted: true
    pages:
      - id: page1
        lambda: |-
          it.print(0, 10, id(font1), "This is page 1!");
      - id: page2
        lambda: |-
          it.print(0, 10, id(font1), "This is page 2!");
```

### Additional information

Traditional Lambda woking without any problems

display:
  - platform: st7920
    setup_priority: -300
    width: 128
    height: 64
    id: display1
    cs_pin:
      number: GPIO22
      inverted: true
    lambda: |-
          it.print(0, 10, id(font1), "This is page 1!");
