### ISSUE TITLE
Constant disconnecting / reconnecting with too many sensors

### ISSUE THREAD

**Issue by Joerny** [esphome/issues#3328]
### The problem

I have an ESP8266 with two sensors (BMP280 & CCS881) and a display (SSD1306). The device is running fine up with a specific configuration. When I then add another sensor (via the HomeAssistant platform or copy an internal one via the copy platform) the internet connection gets unstable and I get a lot of the following messages:

```
[11:38:40][D][api.connection:159]: Home Assistant 2022.5.5 (192.168.1.38) requested disconnected
[11:38:40][D][api:102]: Accepted 192.168.1.38
[11:38:41][D][api.connection:827]: Home Assistant 2022.5.5 (192.168.1.38): Connected successfully
[11:38:41][D][sensor:124]: 'Arbeitszimmer Temperatur': Sending state 22.98000 °C with 1 decimals of accuracy
[11:38:42][D][sensor:124]: 'Arbeitszimmer Luftdruck': Sending state 1007.93805 hPa with 1 decimals of accuracy
[11:38:42][D][sensor:124]: 'Arbeitszimmer Luftfeuchtigkeit': Sending state 39.48633 % with 1 decimals of accuracy
[11:38:42][D][time:041]: Synchronized time: 2022-05-30 11:38:41
[11:38:48][D][api.connection:159]: Home Assistant 2022.5.5 (192.168.1.38) requested disconnected
[11:38:49][D][api:102]: Accepted 192.168.1.38
[11:38:49][D][api.connection:827]: Home Assistant 2022.5.5 (192.168.1.38): Connected successfully
[11:38:50][D][time:041]: Synchronized time: 2022-05-30 11:38:49

```
There are no additional error messages or hints even with a log level of VERY_VERBOSE.

Of course, OTA is then hardly possible and getting the information of the home assistant instance is not done.

Is there a limitation to the number of sensors?

### Which version of ESPHome has the issue?

2022.5.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.5.5

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

internal sensor (platform homeassistant)

### Example YAML snippet

```yaml
esphome:
  name: weather-control
  includes:
    - date_helper.h
    - date_helper.cpp

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "xxx"
  password: "xxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather Control Fallback Hotspot"
    password: "xxx"

time:
  - platform: homeassistant
    id: esptime

i2c:
  sda: D2
  scl: D1
  scan: true

sensor:
  - platform: bme280
    temperature:
      name: "Arbeitszimmer Temperatur"
      id: arbeitszimmer_temperatur
    pressure:
      name: "Arbeitszimmer Luftdruck"
      id: arbeitszimmer_luftdruck
    humidity:
      name: "Arbeitszimmer Luftfeuchtigkeit"
      id: arbeitszimmer_luftfeuchtigkeit
    address: 0x76
    update_interval: 15s
  - platform: template
    name: "Arbeitszimmer absolute Luftfeuchtigkeit"
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(arbeitszimmer_temperatur).state) /
        (id(arbeitszimmer_temperatur).state + 243.5)) * id(arbeitszimmer_luftfeuchtigkeit).state * mw) /
        ((273.15 + id(arbeitszimmer_temperatur).state) * r); // in grams/m^3
    accuracy_decimals: 2
    update_interval: 15s
    icon: 'mdi:water'
    unit_of_measurement: 'g/m³'
  - platform: template
    name: "Arbeitszimmer Taupunkt"
    lambda: |-
      return (243.5*(log(id(arbeitszimmer_luftfeuchtigkeit).state/100)+((17.67*id(arbeitszimmer_temperatur).state)/
      (243.5+id(arbeitszimmer_temperatur).state)))/(17.67-log(id(arbeitszimmer_luftfeuchtigkeit).state/100)-
      ((17.67*id(arbeitszimmer_temperatur).state)/(243.5+id(arbeitszimmer_temperatur).state))));
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'

  - platform: copy
    source_id: arbeitszimmer_luftdruck
    id: arbeitszimmer_luftdruck_smooth
    internal: true
    device_class: "pressure"
    unit_of_measurement: hPa
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          window_size: 8
          send_every: 8

# If one of the following sensors is removed the device is working fine.
  - platform: homeassistant
    entity_id: sensor.arbeitszimmer_luftdruck_min
    id: arbeitszimmer_luftdruck_min
    internal: true
  - platform: homeassistant
    entity_id: sensor.arbeitszimmer_luftdruck_max
    id: arbeitszimmer_luftdruck_max
    internal: true

  - platform: ccs811
    eco2:
      name: "Arbeitszimmer eCO2 Value"
    tvoc:
      name: "Arbeitszimmer Total Volatile Organic Compound"
    address: 0x5A
    temperature: arbeitszimmer_temperatur
    humidity: arbeitszimmer_luftfeuchtigkeit
#    baseline: 0xEEBE

font:
  - file: "gfonts://B612 Mono"
    id: font_legend
    size: 8
    glyphs: ['.', '↑', '↓', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'h', 'n', 'P', 'a', ' ', '-']
  - file: "gfonts://B612 Mono"
    id: font1
    size: 9
    glyphs: ['!', ',', '.', '"', '%', '(', ')', '+', '-', '=', '_', ':', '°', '0',
             '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
             'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
             'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
             'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
             'u', 'v', 'w', 'x', 'y', 'z', 'Ä', 'ä', 'Ö', 'ö', 'Ü', 'ü', 'ß', '/']
  - file: "gfonts://Roboto"
    id: font2
    size: 24
    glyphs: ['!', ',', '.', '"', '%', '(', ')', '+', '-', '=', '_', ':', '°', '0',
             '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
             'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
             'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
             'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
             'u', 'v', 'w', 'x', 'y', 'z', 'Ä', 'ä', 'Ö', 'ö', 'Ü', 'ü', 'ß', '/']

graph:
  - id: humidity_graph
    sensor: arbeitszimmer_luftdruck_smooth
    duration: 4h
    width: 128
    height: 64
    x_grid: 60min
#    y_grid: 10

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 250ms
    id: my_display
    pages:
      - id: display_clock
        lambda: |-
          int dayOfTheWeek = id(esptime).now().day_of_week - 1;
          it.printf(64, 0, id(font1), TextAlign::TOP_CENTER, "%s -- KW %d", dayNames[dayOfTheWeek], getCalendarWeek(id(esptime).now().year, id(esptime).now().day_of_year - 1, dayOfTheWeek));
          it.printf(64, 11, id(font1), TextAlign::TOP_CENTER, "%d. %s %d", id(esptime).now().day_of_month, monthNames[id(esptime).now().month - 1], id(esptime).now().year);
          it.strftime(64, 30, id(font2), TextAlign::TOP_CENTER, "%H:%M:%S", id(esptime).now());
      - id: display_humidity
        lambda: |-
          it.graph(0, 0, id(humidity_graph));
          it.printf(2, 2, id(font_legend), TextAlign::TOP_LEFT, "↑ %.1f hPa", id(arbeitszimmer_luftdruck_max).state);
          //it.printf(2, 61, id(font_legend), TextAlign::BOTTOM_LEFT, "↓ %.1f hPa", id(arbeitszimmer_luftdruck_min).state);

interval:
  - interval: 5s
    then:
      - display.page.show_next: my_display
      - component.update: my_display
```
