### ISSUE TITLE
AC Dimmer Component - Lights twinkle

### ISSUE THREAD

**Issue by alnavasa** [esphome/issues#3330]
### The problem

When using the AC Dimmer Component
(https://esphome.io/components/output/ac_dimmer.html#ac-dimmer-component)

Lights twinkle, 
ESP32, robotdyn AC dimmer module. 
Could this be caused by interferences?

### Which version of ESPHome has the issue?

Firmware: 2022.3.1 (May 24 2022, 19:53:27)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant Core 2022.5.5  Home Assistant Supervisor 2022.05.3  Home Assistant OS 8.1  Kernel version 5.15.41  Agent version 1.2.1

### What platform are you using?

ESP32

### Board

Robotdyn 4chrelay esp32 module

### Component causing the issue

AC Dimmer Component

### Example YAML snippet

```yaml
substitutions:
  node_name: per
  device_name: per


esphome:
  name: $node_name
  comment: $device_name
  
  
esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$node_name"
    password: !secret fallback_password

captive_portal:



text_sensor:
  - platform: template
    name: Uptime $device_name
    id: uptime_human
    entity_category: diagnostic
    icon: mdi:clock-start

  - platform: wifi_info
    ip_address:
      name: $device_name IP
      icon: mdi:wifi-cog
    ssid:
      name: $device_name SSID
      icon: mdi:wifi-cog
    bssid:
      name: $device_name BSSID
      icon: mdi:wifi-cog




sensor:
  - platform: wifi_signal
    name: "WiFi Signal $device_name"
    update_interval: 60s

  - platform: uptime
    name: Uptime $device_name System
    id: uptime_sensor
    update_interval: 60s
    entity_category: diagnostic
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();


  - platform: dallas
    address: 0x4a3c38f648cfbb28
    name: "ESP32 Temp"
    entity_category: diagnostic



#status_led:
#  pin:
#    number: GPIO2
    



button:
  - platform: restart
    name: "$device_name Restart"
    
  - platform: safe_mode
    name: "$device_name Room Restart (Safe Mode)"





i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false
  id: bus_a
  
dallas:
  - pin: 23


pcf8574:
  - id: 'relay_x8'
    address: 0x3B
    pcf8575: false


  - id: 'inputx16'
    address: 0x20
    pcf8575: true







binary_sensor:
  - platform: status
    name: "Status $device_name"
    
    
#  - platform: gpio
#    name: "PCF8574 Pin #00"
#    pin:
#      pcf8574: inputx16
#      # Use pin number 0
#      number: 0
#      # One of INPUT or OUTPUT
#      inverted: true

  - platform: gpio
    name: "PCF8574 Pin #01"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 1
      # One of INPUT or OUTPUT
      inverted: true

  - platform: gpio
    name: "PCF8574 Pin #02"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 2
      # One of INPUT or OUTPUT
      inverted: true

  - platform: gpio
    name: "PCF8574 Pin #03"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 3
      # One of INPUT or OUTPUT
      inverted: true

  - platform: gpio
    name: "PCF8574 Pin #04"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 4
      # One of INPUT or OUTPUT
      inverted: true

  - platform: gpio
    name: "PCF8574 Pin #05"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 5
      # One of INPUT or OUTPUT
      inverted: true

  - platform: gpio
    name: "PCF8574 Pin #06"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 6
      # One of INPUT or OUTPUT
      inverted: true

  - platform: gpio
    name: "PCF8574 Pin #07"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 7
      # One of INPUT or OUTPUT
      inverted: true

  - platform: gpio
    name: "PCF8574 Pin #08"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 8
      # One of INPUT or OUTPUT
      inverted: true


  - platform: gpio
    name: "PCF8574 Pin #09"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 9
      # One of INPUT or OUTPUT
      inverted: true


  - platform: gpio
    name: "PCF8574 Pin #10"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 10
      # One of INPUT or OUTPUT
      inverted: true


  - platform: gpio
    name: "PCF8574 Pin #11"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 11
      # One of INPUT or OUTPUT
      inverted: true


  - platform: gpio
    name: "PCF8574 Pin #12"
    pin:
      pcf8574: inputx16
      # Use pin number 0
      number: 12
      # One of INPUT or OUTPUT
      inverted: true


#  - platform: gpio
#    name: "PCF8574 Pin #13"
#    pin:
#      pcf8574: inputx16
#      # Use pin number 0
#      number: 13
#      # One of INPUT or OUTPUT
#      inverted: true


#  - platform: gpio
#    name: "PCF8574 Pin #14"
#    pin:
#      pcf8574: inputx16
#      # Use pin number 0
#      number: 14
#      # One of INPUT or OUTPUT
#      inverted: true
      
      
#  - platform: gpio
#    name: "PCF8574 Pin #15"
#    pin:
#      pcf8574: inputx16
#      # Use pin number 0
#      number: 15
#      # One of INPUT or OUTPUT
#      inverted: true














switch:



  - platform: gpio
    name: "X8 R1"
    pin:
      pcf8574: relay_x8
      # Use pin number 0
      number: 0
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false
    restore_mode: always_off

  - platform: gpio
    name: "X8 R2"
    pin:
      pcf8574: relay_x8
      # Use pin number 0
      number: 1
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false
    restore_mode: always_off

  - platform: gpio
    name: "X8 R3"
    pin:
      pcf8574: relay_x8
      # Use pin number 0
      number: 2
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false
    restore_mode: always_off

  - platform: gpio
    name: "X8 R4"
    pin:
      pcf8574: relay_x8
      # Use pin number 0
      number: 3
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false
    restore_mode: always_off

  - platform: gpio
    name: "X8 R5"
    pin:
      pcf8574: relay_x8
      # Use pin number 0
      number: 4
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false
    restore_mode: always_off

  - platform: gpio
    name: "X8 R6"
    pin:
      pcf8574: relay_x8
      # Use pin number 0
      number: 5
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false
    restore_mode: always_off

  - platform: gpio
    name: "X8 R7"
    pin:
      pcf8574: relay_x8
      # Use pin number 0
      number: 6
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false
    restore_mode: always_off
    
  - platform: gpio
    name: "X8 R8"
    pin:
      pcf8574: relay_x8
      # Use pin number 0
      number: 7
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false
    restore_mode: always_off
    
  - platform: gpio
    pin: GPIO25
    name: "Zumbador Caseta"
    restore_mode: always_off
    id: r1

#  - platform: gpio
#    pin: GPIO26
#    name: "R2"
#    restore_mode: always_off
#    id: r2
    
#  - platform: gpio
#    pin: GPIO33
#    name: "R3"
#    restore_mode: always_off
#    id: r3
    
#  - platform: gpio
#    pin: GPIO32
#    name: "R4"
#    restore_mode: always_off
#    id: r4



output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: GPIO17
    zero_cross_pin:
      number: GPIO16
      mode:
        input: true
      inverted: yes

  - platform: ac_dimmer
    id: dimmer2
    gate_pin: GPIO19
    method: leading
    min_power: 0.25
    max_power: 1
    zero_cross_pin:
      number: GPIO16
      mode:
        input: true
      inverted: yes

  - platform: ac_dimmer
    id: dimmer3
    gate_pin: GPIO18
    zero_cross_pin:
      number: GPIO16
      mode:
        input: true
      inverted: yes

  - platform: ac_dimmer
    id: dimmer4
    gate_pin: GPIO13
    zero_cross_pin:
      number: GPIO16
      mode:
        input: true
      inverted: yes


  - platform: gpio
    pin: GPIO26

    id: r2
    
  - platform: gpio
    pin: GPIO33

    id: r3
    
  - platform: gpio
    pin: GPIO32

    id: r4


      
      
      

light:
  - platform: monochromatic
    output: dimmer1
    name: Cocina 1
    restore_mode: always_off
    
  - platform: monochromatic
    output: dimmer2
    name: Cocina 2
    restore_mode: always_off
    
  - platform: monochromatic
    output: dimmer3
    name: Dimmerized Light 3
    restore_mode: always_off
    
  - platform: monochromatic
    output: dimmer4
    name: Dimmerized Light 4
    restore_mode: always_off
    
  - platform: binary
    name: "Pérgola"
    output: r2

  - platform: binary
    name: "Carpes"
    output: r3

  - platform: binary
    name: "Farola Césped"
    output: r4
```

### Anything in the logs that might be useful for us?

```txt
Nothing abnormal
```

### Additional information

I can record a video if needed

Not sure about the "home assistant type of installation, probably not relevant, but home assistant operating system installed on a VM on proxmox on a Intel nuc"
