### ISSUE TITLE
RGBWW leestrip warm and cold leds don't go to full brightness when setting CT

### ISSUE THREAD

**Issue by vandalon** [esphome/issues#3332]
### The problem

I've setup rgbww with constant_brightness specifically disabled. When changing Color Temp in HA and brightness to 255/100% both white channels don't go to full brightness, instead it seems constant_brightness is somehow activated. 
Enabling and disabling constant_brightness does not show any difference. Also tested with gamma_correct set to 1, but this also did not make any difference. When enabling color_interlock, all works as expected (meaning both white channels go to full brightness).

### Which version of ESPHome has the issue?

ESPHome version 2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.0

### What platform are you using?

ESP8266

### Board

esp01_1m (H801)

### Component causing the issue

rgbww

### Example YAML snippet

```yaml
light:
  - platform: rgbww
    cold_white: cw
    warm_white: ww
    cold_white_color_temperature: 6500K
    warm_white_color_temperature: 2500K
    id: woonkamer_voor_rgb
    name: "Woonkamer Voor"
    red: red
    green: green
    blue: blue
    constant_brightness: false
```

### Anything in the logs that might be useful for us?

```txt
no warnings or errors in the logs.
```
