### ISSUE TITLE
MAX7219 7-segment and 4-matrix issues

### ISSUE THREAD

**Issue by voed** [esphome/issues#3344]
### The problem

Hi. I am trying to create a clock with 4xMAX7219digit and MAX7219 7-segment displays that connected to one SPI bus with different CS pins.
![image](https://user-images.githubusercontent.com/10352360/172151148-1de0d6ac-915c-4664-972b-595146ad77c8.png)
First of all, i have installed it like on photo(letters upside), but the image on matrix was upside down. Not sure its software problem or just wrong PCB layout on my sample, but ok, i used `rotate_chip: 180`. But after this image was mirrored so i used `reverse_enable` too. That's added some issues with positioning but ok. 
Now more interesting, the second display. It has 8 digits so controlled by a single chip, right? With `num_chips: 1` only first 4 digits works.
Here's some examples:
```yaml
  - platform: max7219
    cs_pin: GPIO4
    num_chips: 1
    intensity: 0
    reverse_enable: false 
    lambda: |-
      it.print(0, "01234567");
```
`0123` (same with reverse_enable:true)

```yaml
  - platform: max7219
    cs_pin: GPIO4
    num_chips: 2 #two chips
    intensity: 0
    reverse_enable: false
    lambda: |-
      it.print(0, "01234567");
```
empty screen

```yaml
  - platform: max7219
    cs_pin: GPIO4
    num_chips: 2
    intensity: 0
    reverse_enable: true #two chips but reverse
    lambda: |-
      it.print(0, "01234567");
```
`012345` 

Is it conflicts with 7219digit somehow because of the same SPI bus or maybe i am doing something wrong?

### Which version of ESPHome has the issue?

 2022.5.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

Wemos mini32

### Component causing the issue

MAX7219

### Example YAML snippet

```yaml
spi:
  clk_pin: GPIO27
  mosi_pin: GPIO32

display:
  - platform: max7219digit
    cs_pin: GPIO25
    id: maxdigit
    num_chips: 4
    intensity: 0
    rotate_chip: 180
    reverse_enable: true
    lambda: |-
      it.print(0, 5, id(digit_font), TextAlign::CENTER_LEFT, "0123456789");

     
  - platform: max7219
    cs_pin: GPIO4
    id: max7seg
    num_chips: 1
    intensity: 0
    reverse_enable: false
    lambda: |-
      it.print(0, "01234567");
```
