### ISSUE TITLE
`on_boot`: Cannot do different tasks at different priorities

### ISSUE THREAD

**Issue by Joshfindit** [esphome/issues#335]
This code does not work, nor does any permutation I've tried:

```
  on_boot:
    priority: 90
      - then:
        - light.turn_on: fastled_light

    priority: -10
      - then:
        - mqtt.publish:
          topic: d1minilampapa102/status
          payload: "Booted"
```

Presumably because `priority:` and `then` are at the same hierarchy level as per https://esphome.io/components/esphome.html#esphome-on-boot
```
esphome:
  # ...
  on_boot:
    priority: -10
    # ...
    then:
```
