### ISSUE TITLE
Xiaomi Mi Flora Hub maximum number of devices?

### ISSUE THREAD

**Issue by coxtor** [esphome/issues#3350]
### The problem

I am sucessfully using an esp32 as a hub for my mi flora plantsensors. However, when I add more than 14 Sensors the hub wont start and remains in a bootloop. 
Is there a upper limit to connectable sensors?

### Which version of ESPHome has the issue?

v2022.5.1 

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Example YAML snippet

```yaml
sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:61:3B:C7'
    temperature:
      name: "Flora 1 Temperature"
    moisture:
      name: "Flora 1 Moisture"
    illuminance:
      name: "Flora 1 Illuminance"
    conductivity:
      name: "Flora 1 Soil Conductivity"
    battery_level:
      name: "Flora 1 Battery Level"
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:66:55:7F'
    temperature:
      name: "Flora 2 Temperature"
    moisture:
      name: "Flora 2 Moisture"
    illuminance:
      name: "Flora 2 Illuminance"
    conductivity:
      name: "Flora 2 Soil Conductivity"
    battery_level:
      name: "Flora 2 Battery Level"      
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:61:3B:AC'
    temperature:
      name: "Flora 3 Temperature"
    moisture:
      name: "Flora 3 Moisture"
    illuminance:
      name: "Flora 3 Illuminance"
    conductivity:
      name: "Flora 3 Soil Conductivity"
    battery_level:
      name: "Flora 3 Battery Level"      
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:60:05'
    temperature:
      name: "Flora 4 Temperature"
    moisture:
      name: "Flora 4 Moisture"
    illuminance:
      name: "Flora 4 Illuminance"
    conductivity:
      name: "Flora 4 Soil Conductivity"
    battery_level:
      name: "Flora 4 Battery Level"      
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:61:09'
    temperature:
      name: "Flora 5 Temperature"
    moisture:
      name: "Flora 5 Moisture"
    illuminance:
      name: "Flora 5 Illuminance"
    conductivity:
      name: "Flora 5 Soil Conductivity"
    battery_level:
      name: "Flora 5 Battery Level"      
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:5A:C6'
    temperature:
      name: "Flora 6 Temperature"
    moisture:
      name: "Flora 6 Moisture"
    illuminance:
      name: "Flora 6 Illuminance"
    conductivity:
      name: "Flora 6 Soil Conductivity"
    battery_level:
      name: "Flora 6 Battery Level"      
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:3B:B3'
    temperature:
      name: "Flora 7 Temperature"
    moisture:
      name: "Flora 7 Moisture"
    illuminance:
      name: "Flora 7 Illuminance"
    conductivity:
      name: "Flora 7 Soil Conductivity"
    battery_level:
      name: "Flora 7 Battery Level"      
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:93:F1'
    temperature:
      name: "Flora 8 Temperature"
    moisture:
      name: "Flora 8 Moisture"
    illuminance:
      name: "Flora 8 Illuminance"
    conductivity:
      name: "Flora 8 Soil Conductivity"
    battery_level:
      name: "Flora 8 Battery Level"      
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:D2:14'
    temperature:
      name: "Flora 9 Temperature"
    moisture:
      name: "Flora 9 Moisture"
    illuminance:
      name: "Flora 9 Illuminance"
    conductivity:
      name: "Flora 9 Soil Conductivity"
    battery_level:
      name: "Flora 9 Battery Level"   
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:D1:3B'
    temperature:
      name: "Flora 10 Temperature"
    moisture:
      name: "Flora 10 Moisture"
    illuminance:
      name: "Flora 10 Illuminance"
    conductivity:
      name: "Flora 10 Soil Conductivity"
    battery_level:
      name: "Flora 10 Battery Level"
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:60:E0'
    temperature:
      name: "Flora 11 Temperature"
    moisture:
      name: "Flora 11 Moisture"
    illuminance:
      name: "Flora 11 Illuminance"
    conductivity:
      name: "Flora 11 Soil Conductivity"
    battery_level:
      name: "Flora 11 Battery Level"   
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6b:61:16'
    temperature:
      name: "Flora 12 Temperature"
    moisture:
      name: "Flora 12 Moisture"
    illuminance:
      name: "Flora 12 Illuminance"
    conductivity:
      name: "Flora 12 Soil Conductivity"
    battery_level:
      name: "Flora 12 Battery Level"   
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:B4:BC'
    temperature:
      name: "Flora 13 Temperature"
    moisture:
      name: "Flora 13 Moisture"
    illuminance:
      name: "Flora 13 Illuminance"
    conductivity:
      name: "Flora 13 Soil Conductivity"
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6B:CE:64'
    temperature:
      name: "Flora 14 Temperature"
    moisture:
      name: "Flora 14 Moisture"
    illuminance:
      name: "Flora 14 Illuminance"
    conductivity:
      name: "Flora 14 Soil Conductivity"
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6b:B7:83'
    temperature:
      name: "Flora 15 Temperature"
    moisture:
      name: "Flora 15 Moisture"
    illuminance:
      name: "Flora 15 Illuminance"
    conductivity:
      name: "Flora 15 Soil Conductivity"
  - platform: xiaomi_hhccjcy01
    mac_address: '80:EA:CA:88:F3:E6'
    temperature:
      name: "Flora 16 Temperature"
    moisture:
      name: "Flora 16 Moisture"
    illuminance:
      name: "Flora 16 Illuminance"
    conductivity:
      name: "Flora 16 Soil Conductivity"      
  - platform: xiaomi_hhccjcy01
    mac_address: '80:EA:CA:89:66:21'
    temperature:
      name: "Flora 17 Temperature"
    moisture:
      name: "Flora 17 Moisture"
    illuminance:
      name: "Flora 17 Illuminance"
    conductivity:
      name: "Flora 17 Soil Conductivity"
```
