### ISSUE TITLE
Midea: Unable to change Fan Mode when Operation is anything other than Fan Only

### ISSUE THREAD

**Issue by mwolter805** [esphome/issues#3355]
### The problem

Hello,
I've noticed an issue where Fan Mode is changed to Auto when Fan Mode is actually set to a specific speed  and the current Operation is anything other than Fan Only. For instance, this prevents adjusting the fan speed when the current Operation is Cool. 

Below are the ESP logs when cycling through the following:
1. Off to Fan Only 
2. Fan to Low
3. Fan Only to Cool
4. Fan to Medium

<details>
<summary>Operation changed from Off to Fan Only</summary>

[07:39:35][D][AirConditioner:205]: New status data received. Parsing...
[07:39:35][D][ApplianceBase:154]: Destroying the request...
[07:39:35][D][climate:010]: 'Matts Midea AC' - Setting
[07:39:35][D][climate:014]:   Mode: FAN_ONLY
[07:39:35][D][AirConditioner:105]: Enqueuing a priority SET_STATUS(0x40) request...
[07:39:35][D][ApplianceBase:178]: Priority request queuing...
[07:39:36][D][ApplianceBase:075]: Getting and sending a request from the queue...
[07:39:36][D][ApplianceBase:162]: TX: AA 23 AC 8F 00 00 00 00 03 02 40 03 A5 50 7F 7F 00 30 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 B8 7B 
[07:39:36][D][ApplianceBase:063]: RX: AA 23 AC 00 00 00 00 00 03 02 C0 01 A5 50 7F 7F 00 30 00 00 04 5E 5D 00 00 00 00 00 00 00 00 00 00 CD C8 F4 
[07:39:36][D][AirConditioner:205]: New status data received. Parsing...
[07:39:36][D][climate:385]: 'Matts Midea AC' - Sending state:
[07:39:36][D][climate:388]:   Mode: FAN_ONLY
[07:39:36][D][climate:393]:   Fan Mode: HIGH
[07:39:36][D][climate:399]:   Preset: NONE
[07:39:36][D][climate:405]:   Swing Mode: OFF
[07:39:36][D][climate:408]:   Current Temperature: 22.00°C
[07:39:36][D][climate:414]:   Target Temperature: 21.00°C
[07:39:36][D][ApplianceBase:154]: Destroying the request...
[07:39:37][D][AirConditioner:178]: Enqueuing a GET_STATUS(0x41) request...
[07:39:37][D][ApplianceBase:173]: Enqueuing the request...
[07:39:37][D][ApplianceBase:075]: Getting and sending a request from the queue...
[07:39:37][D][ApplianceBase:162]: TX: AA 21 AC 8D 00 00 00 00 03 03 41 81 00 FF 03 FF 00 02 00 00 00 00 00 00 00 00 00 00 00 00 03 CE E2 28 
[07:39:37][D][ApplianceBase:063]: RX: AA 23 AC 00 00 00 00 00 03 03 C0 01 A5 50 7F 7F 00 30 00 00 04 5E 5D 00 00 00 00 00 00 00 00 00 00 CE 2A 90 
</details>

Even though it doesn't show in the logs below, the Fan Mode was successfully changed from High to Low.
<details>
<summary>Fan Mode changed from High to Low</summary>

[07:41:56][D][climate:010]: 'Matts Midea AC' - Setting
[07:41:56][D][climate:023]:   Fan: LOW
[07:41:56][D][AirConditioner:105]: Enqueuing a priority SET_STATUS(0x40) request...
[07:41:56][D][ApplianceBase:178]: Priority request queuing...
[07:41:56][D][ApplianceBase:063]: RX: AA 23 AC 00 00 00 00 00 03 03 C0 01 A5 50 7F 7F 00 30 00 00 04 5D 5C 00 00 00 00 00 00 00 00 00 00 55 83 B2 
[07:41:56][D][AirConditioner:205]: New status data received. Parsing...
[07:41:56][D][ApplianceBase:154]: Destroying the request...
[07:41:56][D][ApplianceBase:075]: Getting and sending a request from the queue...
[07:41:56][D][ApplianceBase:162]: TX: AA 23 AC 8F 00 00 00 00 03 02 40 03 A5 28 7F 7F 00 30 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 1D 3E 
[07:41:57][D][ApplianceBase:063]: RX: AA 23 AC 00 00 00 00 00 03 02 C0 01 A5 28 7F 7F 00 30 00 00 04 5D 5C 00 00 00 00 00 00 00 00 00 00 55 26 38 
</details>

<details>
<summary>Operation changed from Fan Only to Cool</summary>

[07:43:51][D][ApplianceBase:154]: Destroying the request...
[07:43:52][D][climate:010]: 'Matts Midea AC' - Setting
[07:43:52][D][climate:014]:   Mode: COOL
[07:43:52][D][AirConditioner:105]: Enqueuing a priority SET_STATUS(0x40) request...
[07:43:52][D][ApplianceBase:178]: Priority request queuing...
[07:43:52][D][ApplianceBase:075]: Getting and sending a request from the queue...
[07:43:52][D][ApplianceBase:162]: TX: AA 23 AC 8F 00 00 00 00 03 02 40 03 45 28 7F 7F 00 30 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 85 36 
[07:43:52][D][ApplianceBase:063]: RX: AA 23 AC 00 00 00 00 00 03 02 C0 01 45 28 7F 7F 00 30 00 10 04 5D 5B 00 00 00 00 00 00 00 00 00 00 C4 38 08 
[07:43:52][D][AirConditioner:205]: New status data received. Parsing...
[07:43:52][D][climate:385]: 'Matts Midea AC' - Sending state:
[07:43:52][D][climate:388]:   Mode: COOL
[07:43:52][D][climate:393]:   Fan Mode: LOW
[07:43:52][D][climate:399]:   Preset: ECO
[07:43:52][D][climate:405]:   Swing Mode: OFF
[07:43:52][D][climate:408]:   Current Temperature: 21.50°C
[07:43:52][D][climate:414]:   Target Temperature: 21.00°C
[07:43:52][D][ApplianceBase:154]: Destroying the request...
[07:43:53][D][AirConditioner:178]: Enqueuing a GET_STATUS(0x41) request...
[07:43:53][D][ApplianceBase:173]: Enqueuing the request...
[07:43:53][D][ApplianceBase:075]: Getting and sending a request from the queue...
[07:43:53][D][ApplianceBase:162]: TX: AA 21 AC 8D 00 00 00 00 03 03 41 81 00 FF 03 FF 00 02 00 00 00 00 00 00 00 00 00 00 00 00 03 C5 C2 51 
[07:43:53][D][ApplianceBase:063]: RX: AA 23 AC 00 00 00 00 00 03 03 C0 01 45 28 7F 7F 00 30 00 10 04 5D 5B 00 00 00 00 00 00 00 00 00 00 C5 66 D8 
</details>

In the following logs, you can see from the logs, ```Fan Mode: AUTO``` is received when changing the fan mode and the operation is Cool. 

<details>
<summary>Fan Mode changed from Low to Medium</summary>

[07:44:42][D][AirConditioner:205]: New status data received. Parsing...
[07:44:42][D][ApplianceBase:154]: Destroying the request...
[07:44:43][D][climate:010]: 'Matts Midea AC' - Setting
[07:44:43][D][climate:023]:   Fan: MEDIUM
[07:44:43][D][AirConditioner:105]: Enqueuing a priority SET_STATUS(0x40) request...
[07:44:43][D][ApplianceBase:178]: Priority request queuing...
[07:44:43][D][ApplianceBase:075]: Getting and sending a request from the queue...
[07:44:43][D][ApplianceBase:162]: TX: AA 23 AC 8F 00 00 00 00 03 02 40 03 45 66 7F 7F 00 30 00 90 04 00 00 00 00 00 00 00 00 00 00 00 00 00 F2 FB 
[07:44:43][D][ApplianceBase:063]: RX: AA 23 AC 00 00 00 00 00 03 02 C0 01 45 66 7F 7F 00 30 00 10 04 5D 5B 00 00 00 00 00 00 00 00 00 00 F5 71 60 
[07:44:43][D][AirConditioner:205]: New status data received. Parsing...
[07:44:43][D][climate:385]: 'Matts Midea AC' - Sending state:
[07:44:43][D][climate:388]:   Mode: COOL
[07:44:43][D][climate:393]:   Fan Mode: AUTO
[07:44:43][D][climate:399]:   Preset: ECO
[07:44:43][D][climate:405]:   Swing Mode: OFF
[07:44:43][D][climate:408]:   Current Temperature: 21.50°C
[07:44:43][D][climate:414]:   Target Temperature: 21.00°C
[07:44:43][D][ApplianceBase:154]: Destroying the request...
[07:44:44][D][AirConditioner:178]: Enqueuing a GET_STATUS(0x41) request...
[07:44:44][D][ApplianceBase:173]: Enqueuing the request...
[07:44:44][D][ApplianceBase:075]: Getting and sending a request from the queue...
[07:44:44][D][ApplianceBase:162]: TX: AA 21 AC 8D 00 00 00 00 03 03 41 81 00 FF 03 FF 00 02 00 00 00 00 00 00 00 00 00 00 00 00 03 F6 9E 44 
[07:44:44][D][ApplianceBase:063]: RX: AA 23 AC 00 00 00 00 00 03 03 C0 01 45 66 7F 7F 00 30 00 10 04 5D 5B 00 00 00 00 00 00 00 00 00 00 F6 93 3C 
</details>

Air Conditioner Model:
[Midea Duo MAP14HS1TBL](https://www.midea.com/us/air-conditioners/portable-air-conditioners/midea-duo-smart-inverter-14k-btu-portable-air-conditioner-with-heat-map14hs1tbl)
[Purchase Link](https://www.costco.com/midea-duo-smart-12k-btu-(doesacc)-4-in-1-inverter-portable-air-conditioner.product.100978219.html)
[User Manual](https://m.media-amazon.com/images/I/B1z6ZDDn33S.pdf)

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.5.5

### What platform are you using?

ESP8266

### Board

dudanov universal-iot-dongle

### Component causing the issue

Midea

### Example YAML snippet

```yaml
substitutions:
  name: matts-ac
  friendly_name: Matts AC

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Must be used once. It is necessary to comment out after the first firmware update.
  use_address: 192.168.6.65
  fast_connect: true  # reqired for hidden SSID
  
  # Enable fallback hotspot (for captive portal) in case wifi connection fails
  ap:
    ssid: ESPHome $friendly_name
    password: !secret ap_password

api:
  password: !secret api_password

mdns:
  disabled: true
  
ota:
  password: !secret ota_password

logger:
  baud_rate: 0 # disable UART logging
#  level: warn  # normal level for logger
  level: debug # only use this level when debugging an issue
#  level: VERY_VERBOSE # only use this level if debug is not producing enough info to debug an issue
#  logs:
#    esp32_ble_tracker: error # normal level for this integration
#    esp32_ble_tracker: debug # enable when discovering BLE devices  
  
# Define ESP-12F module
esp8266:
  board: esp12e

# UART config
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

esphome:
  name: $name
  platformio_options:
    upload_speed: 2000000

web_server:
  port: 80

climate:
# Climate Control
  - platform: midea
    name: $friendly_name Climate        # Use a unique name.
    # transmitter_id:             # Optional. Add this option to use IR transmitter.
    icon: mdi:hvac
#    autoconf: true              # Autoconfigure most options.
    autoconf: false
    beeper: false               # Beep on commands.
    visual:                     # Optional. Example of visual settings override.
      min_temperature: 17 °C    # min: 16
      max_temperature: 30 °C    # max: 30
      temperature_step: 0.5 °C
    supported_swing_modes:
      - VERTICAL                
    outdoor_temperature:        # May display incorrect values after long inactivity
      name: $friendly_name Outdoor Temp
    supported_modes:
      - FAN_ONLY
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    supported_presets:
      - ECO
      - BOOST
      - SLEEP
    custom_fan_modes:
      - SILENT
      - TURBO


switch:
# Beeper Control
  - platform: template
    name: $friendly_name Beeper
    icon: mdi:volume-source
    optimistic: true
    turn_on_action:
      midea_ac.beeper_on:
    turn_off_action:
      midea_ac.beeper_off:
    entity_category: config

sensor:
# Uptime Sensor    
  - platform: uptime
    name: $friendly_name Uptime
    id: utime
```

### Anything in the logs that might be useful for us?

```txt
[09:47:38][C][wifi:491]: WiFi:
[09:47:38][C][wifi:353]:   Local MAC: [redacted]
[09:47:38][C][wifi:354]:   SSID: [redacted]
[09:47:38][C][wifi:355]:   IP Address: 192.168.6.65
[09:47:38][C][wifi:356]:   BSSID: [redacted]
[09:47:38][C][wifi:358]:   Hostname: 'matts-ac'
[09:47:38][C][wifi:360]:   Signal strength: -69 dB ▂▄▆█
[09:47:38][C][wifi:364]:   Channel: 11
[09:47:38][C][wifi:365]:   Subnet: 255.255.255.0
[09:47:38][C][wifi:366]:   Gateway: 192.168.6.254
[09:47:38][C][wifi:367]:   DNS1: 192.168.8.12
[09:47:38][C][wifi:368]:   DNS2: 192.168.8.10
[09:47:38][C][logger:274]: Logger:
[09:47:38][C][logger:275]:   Level: DEBUG
[09:47:38][C][logger:276]:   Log Baud Rate: 0
[09:47:38][C][logger:277]:   Hardware UART: UART0
[09:47:38][C][uart.arduino_esp8266:102]: UART Bus:
[09:47:38][C][uart.arduino_esp8266:103]:   TX Pin: GPIO1
[09:47:38][C][uart.arduino_esp8266:104]:   RX Pin: GPIO3
[09:47:38][C][uart.arduino_esp8266:106]:   RX Buffer Size: 256
[09:47:38][C][uart.arduino_esp8266:108]:   Baud Rate: 9600 baud
[09:47:38][C][uart.arduino_esp8266:109]:   Data Bits: 8
[09:47:38][C][uart.arduino_esp8266:110]:   Parity: NONE
[09:47:38][C][uart.arduino_esp8266:111]:   Stop bits: 1
[09:47:38][C][uart.arduino_esp8266:113]:   Using hardware serial interface.
[09:47:38][C][template.switch:058]: Template Switch 'Matts AC Beeper'
[09:47:38][C][template.switch:058]:   Icon: 'mdi:volume-source'
[09:47:38][C][template.switch:059]:   Restore State: NO
[09:47:38][C][template.switch:060]:   Optimistic: YES
[09:47:38][C][uptime.sensor:031]: Uptime Sensor 'Matts AC Uptime'
[09:47:38][C][uptime.sensor:031]:   State Class: 'total_increasing'
[09:47:38][C][uptime.sensor:031]:   Unit of Measurement: 's'
[09:47:38][C][uptime.sensor:031]:   Accuracy Decimals: 0
[09:47:38][C][uptime.sensor:031]:   Icon: 'mdi:timer-outline'
[09:47:38][C][web_server:129]: Web Server:
[09:47:38][C][web_server:130]:   Address: 192.168.6.65:80
[09:47:38][C][midea:103]: MideaDongle:
[09:47:38][C][midea:104]:   [x] Period: 1000ms
[09:47:38][C][midea:105]:   [x] Response timeout: 2000ms
[09:47:38][C][midea:106]:   [x] Request attempts: 3
[09:47:38][C][midea:539]: ClimateTraits:
[09:47:38][C][midea:540]:   [x] Visual settings:
[09:47:38][C][midea:541]:       - Min: 17.0
[09:47:38][C][midea:542]:       - Max: 30.0
[09:47:38][C][midea:543]:       - Step: 0.5
[09:47:38][C][midea:545]:   [x] Supports current temperature
[09:47:38][C][midea:551]:   [x] Supported modes:
[09:47:38][C][midea:553]:       - OFF
[09:47:38][C][midea:553]:       - HEAT_COOL
[09:47:38][C][midea:553]:       - COOL
[09:47:38][C][midea:553]:       - HEAT
[09:47:38][C][midea:553]:       - FAN_ONLY
[09:47:38][C][midea:553]:       - DRY
[09:47:38][C][midea:556]:   [x] Supported fan modes:
[09:47:38][C][midea:558]:       - AUTO
[09:47:38][C][midea:558]:       - LOW
[09:47:38][C][midea:558]:       - MEDIUM
[09:47:38][C][midea:558]:       - HIGH
[09:47:38][C][midea:561]:   [x] Supported custom fan modes:
[09:47:38][C][midea:563]:       - silent
[09:47:38][C][midea:563]:       - turbo
[09:47:38][C][midea:566]:   [x] Supported presets:
[09:47:38][C][midea:568]:       - NONE
[09:47:38][C][midea:568]:       - BOOST
[09:47:38][C][midea:568]:       - ECO
[09:47:39][C][midea:568]:       - SLEEP
[09:47:39][C][midea:576]:   [x] Supported swing modes:
[09:47:39][C][midea:578]:       - OFF
[09:47:39][C][midea:578]:       - VERTICAL
```
