### ISSUE TITLE
SPI doesn't work on ESP32 S2

### ISSUE THREAD

**Issue by KTibow** [esphome/issues#3356]
### The problem

If you try to configure SPI on a S2 board, you get an error (I'll elaborate more later).

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

Technically an Adafruit Funhouse but configured as featheresp32-s2

### Component causing the issue

spi

### Example YAML snippet

```yaml
esphome:
  name: esp-funhouse

esp32:
  board: featheresp32-s2
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  password: "***"

wifi:
  ssid: "***"
  password: "***"

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Esp-Funhouse Fallback Hotspot"
    password: "***"

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/esp-funhouse/src/main.o
Linking .pioenvs/esp-funhouse/firmware.elf
/config/.esphome/platformio/packages/toolchain-xtensa-esp32s2/bin/../lib/gcc/xtensa-esp32s2-elf/8.4.0/../../../../xtensa-esp32s2-elf/bin/ld: .pioenvs/esp-funhouse/src/main.o:(.literal._Z5setupv+0x7c): undefined reference to `vtable for esphome::spi::SPIComponent'
collect2: error: ld returned 1 exit status
*** [.pioenvs/esp-funhouse/firmware.elf] Error 1
```

**Comment by KTibow** [comment]
Oh, and same goes for i2c.

**Comment by kbx81** [comment]
I have this all working on my FunHouse. Can you make sure you are running the latest version and try again? Here's my config: https://github.com/kbx81/esphome-configs/blob/main/dev/esp-funhouse.yaml

**Comment by KTibow** [comment]
Sure, give me a bit to get everything set up. Does it still not compile on an RPi?

**Comment by kbx81** [comment]
I have not tried compiling on an RPi, but I imagine that if your add-ons and/or source are all up-to-date, it should.

**Comment by KTibow** [comment]
Apparently not.
```
Processing esp-funhouse (board: featheresp32-s2; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
Tool Manager: Installing platformio/toolchain-esp32s2ulp @ ~1.22851.0
INFO Installing platformio/toolchain-esp32s2ulp @ ~1.22851.0
Error: Could not find the package with 'platformio/toolchain-esp32s2ulp @ ~1.22851.0' requirements for your system 'linux_aarch64'
```
I'll try to use Docker then.

**Comment by KTibow** [comment]
Not getting any errors, I'll assume this means the issue is resolved. However the display isn't doing anything. I might elaborate more in the Discord.

**Comment by KTibow** [comment]
After removing the `scan: false` section of the i2c section, it works! :smile: Thanks ESPHome!

**Comment by kbx81** [comment]
That's interesting -- I have `scan: false` in my config and it works just fine 🤔

**Comment by KTibow** [comment]
I needed to run it first with scanning enabled. Now it works fine with `scan: false`. Also, could you share the dps310 component?

**Comment by kbx81** [comment]
Sure, you can try the DPS310 component as an external component via my PR:

```yaml
external_components:
  - source: github://pr#3704
    components: [ dps310 ]
```

**Comment by kbx81** [comment]
...you might also want to try [this PR](https://github.com/esphome/esphome/pull/3728) as it fixes the SPI hardware interface selection which results in the display refreshing _significantly_ faster...

```yaml
external_components:
  - source: github://pr#3728
    components: [ spi ]
```
