### ISSUE TITLE
`on_boot`: Cannot do different tasks at different priorities

### ISSUE THREAD

**Issue by Joshfindit** [esphome/issues#336]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome installed on an Ubuntu vm via `pip install esphome`, communicating with a dockered hass.io  (and the mosquitto add-on)

**ESP (ESP32/ESP8266, Board/Sonoff):**

`platform: ESP8266`
*D1Mini with 3x APA102s attached to D3 and D4*

**Affected component:**

`on_boot`

**Description of problem:**
This code does not work, nor does any permutation I've tried:

```yaml
  on_boot:
    priority: 90
      - then:
        - light.turn_on: fastled_light

    priority: -10
      - then:
        - mqtt.publish:
          topic: d1minilampapa102/status
          payload: "Booted"
```

Presumably because `priority:` and `then` are at the same hierarchy level as per https://esphome.io/components/esphome.html#esphome-on-boot

```yaml
esphome:
  # ...
  on_boot:
    priority: -10
    # ...
    then:
```

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: d1minilampapa102
  upper_devicename: Lamp 3 - D1 Mini with APA102s
  ledpin: D3

esphome:
  name: $devicename
  platform: ESP8266
#  board: nodemcu-32s
  board: d1_mini
  on_boot:
    priority: 90
    then:
      - light.turn_on: fastled_light

    priority: -10
    then:
      - mqtt.publish:
        topic: d1minilampapa102/status
        payload: "Booted"

mqtt:
  broker: 192.168.7.20
  port: 1883
  username: REDACTED_USER
  password: REDACTED_PASS

wifi:
  ssid: "redacted"
  password: "redacted"

# Enable Home Assistant API
api:

# Enable logging
logger:
  level: WARN

# Enable OTA programming
ota:

# ------ Done basic setup


# ----

light:
  - platform: fastled_spi
    chipset: APA102
    data_pin: D3
    clock_pin: D4
    num_leds: 3
    rgb_order: BRG
    name: $upper_devicename
    id: fastled_light
    effects:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_flicker:
          name: Flicker Effect With Custom Values
          update_interval: 16ms
          intensity: 10%
```

**Traceback (if applicable):**

```
INFO Reading configuration...
ERROR Error while reading config: YAML file lamp3-D1Mini.yaml contains duplicate key "priority". Check lines 11 and 15.
```

**Additional information and things you've tried:**
### 1
```yaml
  on_boot:
    priority: 90
    - then:
      - light.turn_on: fastled_light

    priority: -10
    - then:
      - mqtt.publish:
        topic: d1minilampapa102/status
        payload: "Booted"
```

### 2
```yaml
  on_boot:
    priority: 90
      - then:
        - light.turn_on: fastled_light

  on_boot:
    priority: -10
    - then:
      - mqtt.publish:
        topic: d1minilampapa102/status
        payload: "Booted"
```

Etc

**Comment by OttoWinter** [comment]
The proper YAML syntax is: (see also on_value_range trigger docs)

```yaml
 on_boot:
    - priority: -10
	  then:
      - mqtt.publish:
        topic: d1minilampapa102/status
        payload: "Booted"
    - priority: 90
	  then:
      - mqtt.publish:
        topic: d1minilampapa102/status
        payload: "Booted2"
```
