### ISSUE TITLE
Splitting YAML files fails when using -platform: template. 

### ISSUE THREAD

**Issue by gsieben** [esphome/issues#3360]
### The problem

Hi guys,
I have splitted my configuration into single YAML files. Exactly as described on https://esphome.io/guides/configuration-types.html.
Works fine. The secrets.yaml problem I solved with a symbolic link. But as soon as a "- platform: template" section is in the splitted yaml, it doesn't work anymore. I have used for this the example in the documentation about the dew point. 

- platform: template
  name: ${acronym} Dew Point
  lambda: |-
    return (243.5*(log(id(bme_hum).state/100)+((17.67*id(bme_temp).state)/
    (243.5+id(bme_temp).state))/(17.67-log(id(bme_hum).state/100)-
    ((17.67*id(bme_temp).state)/(243.5+id(bme_temp).state))));
  unit_of_measurement: °C
  icon: "mdi:thermometer-alert"

It seems to be a bug. I have not found a workaround. 

Cheers Gabriel

### Which version of ESPHome has the issue?

ESPHome (2022.5.1)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2022.6.4

### What platform are you using?

ESP32

### Board

Immaterial

### Component causing the issue

Compiler

### Example YAML snippet

```yaml
**Main YAML:**
substitutions:
  devicename: hd-bad
  acronym: BAD

packages:
  device_base: !include modules/device_base.yaml
  wifi: !include modules/wifi.yaml

############ B U S ############ 
# I²C Bus
i2c:
  sda: GPIO19             # Normal 21 
  scl: GPIO22
  scan: True
  # frequency: 100kHz
  
# ONE Wire
dallas:
  - pin: GPIO16

#######################################
############ S E N S O R S ############ 
#######################################
sensor:
  - <<: !include modules/sensor/esp32.yaml
  - <<: !include modules/sensor/bme280.yaml
....



**bme280.yaml:**
- platform: bme280
  temperature:
    name: ${acronym} Temperature
    id: bme_temp
  pressure:
    name: ${acronym} Pressure
  humidity:
    name: ${acronym} Relativ Humidity
    id: bme_hum
  address: 0x76
  update_interval: 15s

- platform: template
  name: ${acronym} Absolute Humidity
  lambda: |-
    const float mw = 18.01534;    // molar mass of water g/mol
    const float r = 8.31447215;   // Universal gas constant J/mol/K
    return (6.112 * powf(2.718281828, (17.67 * id(bme_temp).state) /
      (id(bme_temp).state + 243.5)) * id(bme_hum).state * mw) /
      ((273.15 + id(bme_temp).state) * r); // in grams/m^3
  accuracy_decimals: 2
  update_interval: 15s
  icon: "mdi:water"
  unit_of_measurement: "g/m³"

- platform: template
  name: ${acronym} Dew Point
  lambda: |-
    return (243.5*(log(id(bme_hum).state/100)+((17.67*id(bme_temp).state)/
    (243.5+id(bme_temp).state)))/(17.67-log(id(bme_hum).state/100)-
    ((17.67*id(bme_temp).state)/(243.5+id(bme_temp).state))));
  unit_of_measurement: °C
  icon: "mdi:thermometer-alert"
```

### Additional information
![grafik](https://user-images.githubusercontent.com/2237858/173141900-366020bf-af56-4427-b3b4-7617e26bb94d.png)
