### ISSUE TITLE
`on_click` config should invalidate when `min_length` is higher than `max_length`, also `max_length` shouldn't default

### ISSUE THREAD

**Issue by nagyrobi** [esphome/issues#3361]
### The problem

`binary_sensor`'s both `min_length` and `max_length` are optional.
When the user wants to trigger something at _long-click_ but doesn't care about `max_length` (for example wants to run an automation after a button has been released after being kept pressed for more than `min_length: 1s`), the documentation suggests that being optional, `max_length` could be omitted.
However, the `max_length` is still in power with a default value of [350ms](https://deploy-preview-2029--esphome.netlify.app/components/binary_sensor/index.html?highlight=binary_sensor#on-click) so the automation will never be triggered, when `min_length` is higher than that.

A use case when `min_length` is higher than `max_length` doesn't exist, so the config validation should invalidate such a case.

Moreover, it would be more practical not to have any default value for `max_length`. When `max_length` is omitted, time should be only compared against `min_length` to cope with the user's original intention.

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6

### What platform are you using?

ESP32

### Board

WirelessTag WT32-ETH01

### Component causing the issue

binary_sensor

### Example YAML snippet

```yaml
binary_sensor:
- platform: gpio
  id: rot_enter
  pin:
    number: 36
    mode:
      input: true
  filters:
    - delayed_on: 50ms
    - delayed_off: 50ms
  on_press:
    - logger.log: "Rotary Pressed"
  on_click:
    min_length: 1s
    then:
      - logger.log: "Rotary Pressed Long"
```

### Anything in the logs that might be useful for us?

```txt
https://discord.com/channels/429907082951524364/984924650737897513
```
