### ISSUE TITLE
two sensors with same input not work with latest firmware

### ISSUE THREAD

**Issue by hidaba** [esphome/issues#3364]
### The problem

I measure water with two different intervals of time for statistics, but with the latest firmware it work only one, 
in this case work WaterGiardino

 `sensor:
  - platform: pulse_counter
    pin: D8
    name: 'Utilizzo Acqua Giardino'
    update_interval: 5s
    icon: 'mdi:water'
    unit_of_measurement: 'L/min'
    id: water_usage
    filters:
      - lambda: return (x / 396); # 396 = 6,6 * 60
      
  - platform: pulse_counter
    pin: D8
    name: "WaterGiardino"
    update_interval: 60s
    icon: 'mdi:water'
    unit_of_measurement: 'L'
    filters:
      - lambda: return (x / 370 ); `

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.2

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

pulse

### Example YAML snippet

```yaml
sensor:
  - platform: pulse_counter
    pin: D8
    name: 'Utilizzo Acqua Giardino'
    update_interval: 5s
    icon: 'mdi:water'
    unit_of_measurement: 'L/min'
    id: water_usage
    filters:
      - lambda: return (x / 396); # 396 = 6,6 * 60
      
  - platform: pulse_counter
    pin: D8
    name: "WaterGiardino"
    update_interval: 60s
    icon: 'mdi:water'
    unit_of_measurement: 'L'
    filters:
      - lambda: return (x / 370 ); `
```

### Anything in the logs that might be useful for us?

```txt
with the latest firmware work only the last sensor, the first it always 0
with 2022.4 and older work correctly
```
