### ISSUE TITLE
Tuya MCU does not work properly after a reboot

### ISSUE THREAD

**Issue by frankiboy1** [esphome/issues#3368]
### The problem

I have a couple of Tuya Sirens running esphome. The siren works properly after cold start. I can control volume, sound, duration and start playing the sounds. The sensors are also reporting correctly. If I reboot the device, most of the datapoints disappear and I'm left with only two sensors (temperature and humidity). The two sensors functions correctly, so it looks like the interface to the MCU is still up and running. Performing multiple reboots yield the same behaviour. The only way to get the datapoints back is to do a power cycle.

I don't have a serial interface connected, so I'm unable to look at the logs during boot. (I can solder the FTDI dongle on the device if these logs are required). I do get an error during boot, which states:

`[E][tuya:391]: Initialization failed at init_state 4`

After a cold start, esphome reports the following datapoints:

`[13:50:08][C][tuya:028]: Tuya:`
`[13:50:08][C][tuya:045]:   Datapoint 101: enum (value: 4)`
`[13:50:08][C][tuya:045]:   Datapoint 102: enum (value: 0)`
`[13:50:08][C][tuya:041]:   Datapoint 103: int value (value: 5)`
`[13:50:08][C][tuya:039]:   Datapoint 104: switch (value: OFF)`
`[13:50:08][C][tuya:041]:   Datapoint 105: int value (value: 254)`
`[13:50:08][C][tuya:041]:   Datapoint 106: int value (value: 48)`
`[13:50:08][C][tuya:041]:   Datapoint 107: int value (value: 10)`
`[13:50:08][C][tuya:041]:   Datapoint 108: int value (value: 35)`
`[13:50:08][C][tuya:041]:   Datapoint 109: int value (value: 30)`
`[13:50:08][C][tuya:041]:   Datapoint 110: int value (value: 80)`
`[13:50:08][C][tuya:039]:   Datapoint 112: switch (value: OFF)`
`[13:50:08][C][tuya:039]:   Datapoint 113: switch (value: OFF)`
`[13:50:08][C][tuya:039]:   Datapoint 114: switch (value: OFF)`
`[13:50:08][C][tuya:045]:   Datapoint 115: enum (value: 4)`
`[13:50:08][C][tuya:045]:   Datapoint 116: enum (value: 2)`
`[13:50:08][C][tuya:056]:   Product: '{"p":"ymf4oruxqx0xlogp","v":"1.0.3","m":0}'`

Available datapoints after a reboot:

`[13:51:50][C][tuya:028]: Tuya:`
`[13:51:50][C][tuya:041]:   Datapoint 105: int value (value: 253)`
`[13:51:50][C][tuya:041]:   Datapoint 106: int value (value: 48)`
`[13:51:50][C][tuya:056]:   Product: '{"p":"ymf4oruxqx0xlogp","v":"1.0.3","m":0}'`

This happens consistently. The same two datapoints are available after a reboot. Both of my Tuya Sirens show the same behaviour.

### Which version of ESPHome has the issue?

2022.5.1 and earlier

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.5 and earlier

### What platform are you using?

ESP8266

### Board

Tuya siren

### Component causing the issue

tuya

### Example YAML snippet

```yaml
# Register the Tuya MCU connection
tuya:
  # Datapoint 101: enum (value: 4)               Battery (1=high, 2=medium, 3=low, 4=USB powered)
  # Datapoint 102: enum (value: 6)               Chime Sound
  # Datapoint 103: int value (value: 3)          Duration
  # Datapoint 104: switch (value: OFF)           Sound Enable
  # Datapoint 105: int value (value: 256)        Temp in C
  # Datapoint 106: int value (value: 34)         Humidity
  # Datapoint 107: int value (value: 10)         Min temp trigger
  # Datapoint 108: int value (value: 35)         Max temp trigger
  # Datapoint 109: int value (value: 30)         Min humidity trigger
  # Datapoint 110: int value (value: 80)         Max humidity trigger
  # Datapoint 112: switch (value: OFF)           Unit (on=C, off=F)
  # Datapoint 113: switch (value: OFF)           Temp alarm enable
  # Datapoint 114: switch (value: OFF)           Humidity alarm enable
  # Datapoint 115: enum (value: 4)               Alarm triggered sensor (0=high temp, 1=high humidity, 2=low temp, 3=low humidity, 4/5=ok)
  # Datapoint 116: enum (value: 1)               Volume
  # Product: '{"p":"ymf4oruxqx0xlogp","v":"1.0.3","m":0}'

sensor:
  - platform: "tuya"
    name: "${device_name} Temperature"
    sensor_datapoint: 105
    unit_of_measurement: "C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: "tuya"
    name: "${device_name} Humidity"
    sensor_datapoint: 106
    unit_of_measurement: "%"
    accuracy_decimals: 0
  - platform: "tuya"
    id: tuya_battery_level
    sensor_datapoint: 101
    unit_of_measurement: ""
    accuracy_decimals: 0
    on_value:
      then:
        - lambda: |-
            if( x == 1.0 ) {
              id(battery_level).publish_state("High");
            } else if( x == 2.0) {
              id(battery_level).publish_state("Medium");
            } else if( x == 3.0) {
              id(battery_level).publish_state("Low");
            } else if( x == 4.0) {
              id(battery_level).publish_state("USB Powered");
            } else {
              id(battery_level).publish_state("Unknown");
            }

text_sensor:
  - platform: template
    name: "${device_name} Battery level"
    id: battery_level

select:
  - platform: template
    name: "${device_name} Sound"
    optimistic: true
    options:
      - Doorbell
      - Fur Elise
      - Big Ben
      - Ring Ring
      - Lone Ranger
      - Turkish March
      - High Pitched
      - Red Alert
      - Crickets
      - Beep
      - Dog Bark
      - Police Siren
      - Grandfather Clock
      - Phone Ring
      - Fire Truck
      - Clock Chime
      - Alarm Clock
      - School Bell
    set_action:
      then:
        - logger.log:
            format: "Selected sound: %s"
            args: ["x.c_str()"]
        - lambda: |-
            ESP_LOGD("frank", "New sound is %s", x.c_str());
            int value = 0;
            if( x == "Doorbell" ) {
              ESP_LOGD("frank", "Doorbell");
              value = 0;
            } else if( x == "Fur Elise") {
              value = 1;
            } else if( x == "Big Ben") {
              value = 2;
            } else if( x == "Ring Ring") {
              value = 3;
            } else if( x == "Long Ranger") {
              value = 4;
            } else if( x == "Turkish March") {
              value = 5;
            } else if( x == "High Pitched") {
              value = 6;
            } else if( x == "Red Alert") {
              value = 7;
            } else if( x == "Crickets") {
              value = 8;
            } else if( x == "Beep") {
              value = 9;
            } else if( x == "Dog Bark") {
              value = 10;
            } else if( x == "Police Siren") {
              value = 11;
            } else if( x == "Grandfather Clock") {
              value = 12;
            } else if( x == "Phone Ring") {
              value = 13;
            } else if( x == "Fire Truck") {
              value = 14;
            } else if( x == "Clock Chime") {
              value = 15;
            } else if( x == "Alarm Clock") {
              value = 16;
            } else if( x == "School Bell") {
              value = 17;
            }
            auto call = id(sound_select).make_call();
            call.set_value(value);
            call.perform();
  - platform: template
    name: "${device_name} Volume"
    optimistic: true
    options:
      - High
      - Medium
      - Low
    set_action:
      then:
        - lambda: |-
            int value = 0;
            if( x == "High" ) {
              value = 0;
            } else if( x == "Medium") {
              value = 1;
            } else if( x == "Low") {
              value = 2;
            }
            auto call = id(volume).make_call();
            call.set_value(value);
            call.perform();

button:
  - platform: template
    name: "${device_name} Enable"
    on_press:
      then:
        - switch.turn_on: enable_switch
  - platform: restart
    name: "${device_name} Restart"

switch:
  - platform: "tuya"
    id: enable_switch
    switch_datapoint: 104

number:
  - platform: "tuya"
    id: sound_select
    number_datapoint: 102
    min_value: 0
    max_value: 17
    step: 1
  - platform: "tuya"
    name: "${device_name} Duration"
    number_datapoint: 103
    min_value: 1
    max_value: 10
    step: 1
  - platform: "tuya"
    id: volume
    number_datapoint: 116
    min_value: 0
    max_value: 2
    step: 1
```

### Anything in the logs that might be useful for us?

```txt
[E][tuya:391]: Initialization failed at init_state 4
```
