### ISSUE TITLE
Validation error: [user_characters] is an invalid option for [display.lcd_gpio]

### ISSUE THREAD

**Issue by PimDoos** [esphome/issues#3369]
### The problem

When I add the `user_characters` to my configuration of the `lcd_gpio` component, the config no longer validates or builds.
However, if I look at the [docs](https://esphome.io/components/display/lcd_display.html#user-defined-characters) or the [source code](https://github.com/esphome/esphome/blob/8998c5f6dd5291c0bfb881dda4068627a51e037a/esphome/components/lcd_base/__init__.py#L35), this should be a supported configuration.

![image](https://user-images.githubusercontent.com/17709721/173446783-00a5a94b-fe3c-402d-9b08-24caf3ae1b19.png)

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.5

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

lcd_gpio

### Example YAML snippet

```yaml
esphome:
  name: lcd-example

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

display:
  - platform: lcd_gpio
    id: lcd
    dimensions: 16x2
    data_pins:
      - GPIO25
      - GPIO26
      - GPIO27
      - GPIO14
    enable_pin: GPIO32
    rs_pin: GPIO33
    lambda: |-
      it.print("Hello World!");
    user_characters:
      - position: 0
        data:
        - 0b00000
        - 0b01110
        - 0b10001
        - 0b00100
        - 0b01010
        - 0b00000
        - 0b00100
        - 0b00000
```

### Anything in the logs that might be useful for us?

```txt
[user_characters] is an invalid option for [display.lcd_gpio]. Please check the indentation.
  user_characters:  [source /config/esphome/lcd-example.yaml:38]
    - position: 0
      data: 
        - 0
        - 14
        - 17
        - 4
        - 10
        - 0
        - 4
        - 0
```
