### ISSUE TITLE
AC Dimmer flicks on brightness change

### ISSUE THREAD

**Issue by HFsi** [esphome/issues#3374]
### The problem

When changing the brightness on the AC dimmer component, the light flicks before reaching the state.
No errors in logs.
It´s worth mention, that this wasn´t happen with the previous version (2022.5)

### Which version of ESPHome has the issue?

2022.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.5

### What platform are you using?

ESP8266

### Board

D1 Mini Pro

### Component causing the issue

AC Dimmer

### Example YAML snippet

```yaml
esphome:
  name: dim-box
  platform: ESP8266
  board: d1_mini_pro
  comment: Control Luz Dimerizada del dpto

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 3h

web_server:
ota:

logger:
  logs:
    sensor: INFO

api:
  reboot_timeout: 3h

sensor:
    
  - platform: rotary_encoder
    name: "dim-box-encoder"
    internal: true
    pin_a: RX
    pin_b: TX
    on_clockwise:
      then:
        - if:
            condition:
              lambda: 'return(id(dimmed).remote_values.get_brightness() < 0.29);'
            then:
              - light.turn_on:
                  id: dimmed
                  brightness: 35%
            else:
              - light.dim_relative:
                  id: dimmed
                  relative_brightness: 0.5%
    on_anticlockwise:
      then:
        - if:
            condition:
              lambda: 'return(id(dimmed).remote_values.get_brightness() > 0.29);'
            then:
              - light.dim_relative:
                  id: dimmed
                  relative_brightness: -0.5%
    
binary_sensor:
  - platform: homeassistant
    id: sleep_mode
    entity_id: input_boolean.sleep_mode
    
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    id: encoder_button
    on_press:
      - light.toggle: dimmed
    
switch:
  - platform: restart
    name: "dim-box-restart"
      
output:
  - platform: esp8266_pwm
    pin: D8
    id: blue
    
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: D7
    method: trailing
    init_with_half_cycle: true
    min_power: 0.89
    max_power: 0.99
    zero_cross_pin:
      number: D6
      mode: INPUT
      inverted: yes


light:
  - platform: monochromatic
    output: dimmer1
    name: dim-box-dimmed
    id: dimmed
    default_transition_length: 200ms
    on_turn_on:
      - light.turn_off: status_led
#      - light.dim_relative:
#          id: dimmed
#          relative_brightness: 50%
    on_turn_off:
      - if:
          condition:
              - binary_sensor.is_off: sleep_mode
          then:
            - light.turn_on: status_led
        
  - platform: monochromatic
    name: dim-box-led
    id: status_led
    output: blue
    restore_mode: ALWAYS_OFF
```

### Anything in the logs that might be useful for us?

```txt
[01:03:25][D][light:035]: 'dim-box-dimmed' Setting:
[01:03:25][D][light:050]:   Brightness: 51%
[01:03:25][D][light:084]:   Transition length: 0.2s
[01:03:25][D][light:035]: 'dim-box-led' Setting:
[01:03:25][D][light:050]:   Brightness: 6%
[01:03:25][D][light:084]:   Transition length: 1.0s
[01:03:26][D][light:035]: 'dim-box-dimmed' Setting:
[01:03:26][D][light:050]:   Brightness: 52%
[01:03:26][D][light:084]:   Transition length: 0.2s
[01:03:26][D][light:035]: 'dim-box-led' Setting:
[01:03:26][D][light:050]:   Brightness: 7%
[01:03:26][D][light:084]:   Transition length: 1.0s
[01:03:26][D][light:035]: 'dim-box-dimmed' Setting:
[01:03:26][D][light:050]:   Brightness: 53%
[01:03:26][D][light:084]:   Transition length: 0.2s
[01:03:26][D][light:035]: 'dim-box-led' Setting:
[01:03:26][D][light:050]:   Brightness: 8%
[01:03:26][D][light:084]:   Transition length: 1.0s
```
