### ISSUE TITLE
ESP32-C3-12F Won't Stay Online

### ISSUE THREAD

**Issue by Yannik25** [esphome/issues#3375]
### The problem

Trying to use the ESP32 C3 - 12F as a replacement for  an Tuya Chip. Currently trying on a ESP-C3-12F-Kit. The device seems to come online and then after a minute or to goes offline until I reset the device. I can't figure out why though. Nothing seems to show in the log and I am connecting and uploading via serial? Suggestions?

My config

### Which version of ESPHome has the issue?

2022.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.6

### What platform are you using?

ESP32-IDF

### Board

ESP-C3-12F-Kit

### Example YAML snippet

```yaml
esphome:
  name: ceiling-light-first
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: ""
    password: ""
    
#RGBWW
output:
  - platform: ledc
    pin: 8
    id: pwm_red
  - platform: ledc
    pin: 18
    id: pwm_cw
  - platform: ledc
    pin: 5
    id: pwm_ww
  - platform: ledc
    pin: 3
    id: pwm_green
  - platform: ledc
    pin: 4
    id: pwm_blue
    
light:
  - platform: rgbww
    name: "Ceiling-Light-First"
    red: pwm_red
    green: pwm_green
    blue: pwm_blue
    cold_white: pwm_cw
    warm_white: pwm_ww
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
```

### Anything in the logs that might be useful for us?

```txt
[I][wifi:505]: WiFi Connected!
[C][wifi:353]:   Local MAC: 84:F7:03:3A:A7:E4
[C][wifi:354]:   SSID: [redacted]
[C][wifi:355]:   IP Address: 192.168.1.45
[C][wifi:357]:   BSSID: [redacted]
[C][wifi:358]:   Hostname: 'ceiling-light-first'
[C][wifi:360]:   Signal strength: -50 dB ▂▄▆█
[C][wifi:364]:   Channel: 11
[C][wifi:365]:   Subnet: 255.255.255.0
[C][wifi:366]:   Gateway: 192.168.1.1
[C][wifi:367]:   DNS1: 192.168.1.1
[C][wifi:368]:   DNS2: 0.0.0.0
[D][wifi:514]: Disabling AP...
[C][ota:085]: Over-The-Air Updates:
[C][ota:086]:   Address: ceiling-light-first.local:3232
[C][ota:089]:   Using Password.
[C][api:025]: Setting up Home Assistant API server...
[I][app:062]: setup() finished successfully!
[I][app:102]: ESPHome version 2022.6.0 compiled on Jun 16 2022, 09:15:06
[C][wifi:491]: WiFi:
[C][wifi:353]:   Local MAC: 84:F7:03:3A:A7:E4
[C][wifi:354]:   SSID: [redacted]
[C][wifi:355]:   IP Address: 192.168.1.45
[C][wifi:357]:   BSSID: [redacted]
[C][wifi:358]:   Hostname: 'ceiling-light-first'
[C][wifi:360]:   Signal strength: -50 dB ▂▄▆█
[C][wifi:364]:   Channel: 11
[C][wifi:365]:   Subnet: 255.255.255.0
[C][wifi:366]:   Gateway: 192.168.1.1
[C][wifi:367]:   DNS1: 192.168.1.1
[C][wifi:368]:   DNS2: 0.0.0.0
[C][logger:275]: Logger:
[C][logger:276]:   Level: DEBUG
[C][logger:277]:   Log Baud Rate: 115200
[C][logger:278]:   Hardware UART: UART0
[C][ledc.output:118]: LEDC Output:
[C][ledc.output:119]:   Pin GPIO8
[C][ledc.output:120]:   LEDC Channel: 0
[C][ledc.output:121]:   Frequency: 1000.0 Hz
[C][ledc.output:118]: LEDC Output:
[C][ledc.output:119]:   Pin GPIO18
[C][ledc.output:120]:   LEDC Channel: 1
[C][ledc.output:121]:   Frequency: 1000.0 Hz
[C][ledc.output:118]: LEDC Output:
[C][ledc.output:119]:   Pin GPIO5
[C][ledc.output:120]:   LEDC Channel: 2
[C][ledc.output:121]:   Frequency: 1000.0 Hz
[C][ledc.output:118]: LEDC Output:
[C][ledc.output:119]:   Pin GPIO3
[C][ledc.output:120]:   LEDC Channel: 3
[C][ledc.output:121]:   Frequency: 1000.0 Hz
[C][ledc.output:118]: LEDC Output:
[C][ledc.output:119]:   Pin GPIO4
[C][ledc.output:120]:   LEDC Channel: 4
[C][ledc.output:121]:   Frequency: 1000.0 Hz
[C][light:104]: Light 'Ceiling-Light-First'
[C][light:106]:   Default Transition Length: 1.0s
[C][light:107]:   Gamma Correct: 2.80
[C][mdns:084]: mDNS:
[C][mdns:085]:   Hostname: ceiling-light-first
[C][ota:085]: Over-The-Air Updates:
[C][ota:086]:   Address: ceiling-light-first.local:3232
[C][ota:089]:   Using Password.
[C][api:138]: API Server:
[C][api:139]:   Address: ceiling-light-first.local:6053
[C][api:143]:   Using noise encryption: NO
[D][esp-idf:000]: W (218384) wifi:
[D][esp-idf:000]: <ba-add>idx:1 (ifx:0, 3c:37:12:e3:61:b2), tid:6, ssn:2, winSize:64
[D][esp-idf:000]: 

[I][ota:105]: Boot seems successful, resetting boot loop counter.
[D][esp32.preferences:114]: Saving preferences to flash...
[E][api:127]: No client connected to API. Rebooting...
[I][app:127]: Forcing a reboot...
[D][esp-idf:000]: I (905110) wifi:
[D][esp-idf:000]: state: run -> init (0)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (905110) wifi:
[D][esp-idf:000]: pm stop, total sleep time: 702308130 us / 900785576 us

[D][esp-idf:000]: 

[D][esp-idf:000]: W (905113) wifi:
[D][esp-idf:000]: <ba-del>idx
[D][esp-idf:000]: 

[D][esp-idf:000]: W (905123) wifi:
[D][esp-idf:000]: <ba-del>idx
[D][esp-idf:000]: 

[D][esp-idf:000]: I (905134) wifi:
[D][esp-idf:000]: new:<11,0>, old:<11,0>, ap:<255,255>, sta:<11,0>, prof:1
[D][esp-idf:000]: 

[D][esp-idf:000]: I (905176) wifi:
[D][esp-idf:000]: flush txq
[D][esp-idf:000]: 

[D][esp-idf:000]: I (905176) wifi:
[D][esp-idf:000]: stop sw txq
[D][esp-idf:000]: 

[D][esp-idf:000]: I (905179) wifi:
[D][esp-idf:000]: lmac stop hw txq
[D][esp-idf:000]: 

ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380af4
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x19a0
load:0x403ce000,len:0x8d4
load:0x403d0000,len:0x2dc0
entry 0x403ce000
I (35) boot: ESP-IDF 4.3.2 2nd stage bootloader
I (35) boot: compile time 09:19:30
I (35) boot: chip revision: 3
I (37) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (44) boot.esp32c3: SPI Speed      : 80MHz
I (48) boot.esp32c3: SPI Mode       : DIO
I (53) boot.esp32c3: SPI Flash Size : 4MB
I (58) boot: Enabling RNG early entropy source...
I (63) boot: Partition Table:
I (67) boot: ## Label            Usage          Type ST Offset   Length
I (74) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (82) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (89) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (97) boot:  3 app0             OTA app          00 10 00010000 001c0000
I (104) boot:  4 app1             OTA app          00 11 001d0000 001c0000
I (112) boot: End of partition table
I (116) boot_comm: chip revision: 3, min. application chip revision: 0
I (123) esp_image: segment 0: paddr=00010020 vaddr=3c090020 size=1cd20h (118048) map
I (149) esp_image: segment 1: paddr=0002cd48 vaddr=3fc8e000 size=03258h ( 12888) load
I (152) esp_image: segment 2: paddr=0002ffa8 vaddr=40380000 size=00070h (   112) load
I (155) esp_image: segment 3: paddr=00030020 vaddr=42000020 size=8906ch (561260) map
I (248) esp_image: segment 4: paddr=000b9094 vaddr=40380070 size=0deb4h ( 57012) load
I (258) esp_image: segment 5: paddr=000c6f50 vaddr=50000000 size=00010h (    16) load
I (263) boot: Loaded app from partition at offset 0x10000
I (263) boot: Disabling RNG early entropy source...
I (279) cpu_start: Pro cpu up.
I (885) cpu_start: Pro cpu start user code
I (885) cpu_start: cpu freq: 160000000
I (885) cpu_start: Application information:
I (888) cpu_start: Project name:     ceiling-light-first
I (894) cpu_start: App version:      2022.6.0
I (899) cpu_start: Compile time:     Jun 16 2022 09:15:10
I (905) cpu_start: ELF file SHA256:  78df42b71f84d41d...
I (911) cpu_start: ESP-IDF:          4.3.2
I (916) heap_init: Initializing. RAM available for dynamic allocation:
I (923) heap_init: At 3FC95B50 len 0002A4B0 (169 KiB): DRAM
I (929) heap_init: At 3FCC0000 len 0001F060 (124 KiB): STACK/DRAM
I (936) heap_init: At 50000010 len 00001FF0 (7 KiB): RTCRAM
I (943) spi_flash: detected chip: generic
I (947) spi_flash: flash io: dio
I (951) sleep: Configure to isolate all GPIO pins in sleep state
```
