### ISSUE TITLE
http_request.get to https://script.google.com connection lost not response data

### ISSUE THREAD

**Issue by hmjvaline** [esphome/issues#3377]
### The problem

When using action http_request.get , the normal https web page can be connected normally, but it is connected to  google app script web pages,like https://script.google.com, the URL is https://script.google.com/macros /s/JrZw8O3T_Lh85FNxTUNk8MBragLWo8DsdhKjJ0q6qeWgaWSalCtj3g6ZiFDC9xPg/exec, mainly returns json data, the data can be received normally in the chrome browser, but the error connection lost status_code will be received in esphome, the request seems to be able to be sent, and the google app script can be received , but the response data is 0 bytes

### Which version of ESPHome has the issue?

2022.6.0

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

d1 mini

### Component causing the issue

http_request

### Example YAML snippet

```yaml
http_request :
   useragent : esphome/device 
   timeout : 5s

      - http_request.get:
         url: https://script.google.com/macros/s/JrZw8O3T_Lh85FNxTUNk8MBragLWo8DsdhKjJ0q6qeWgaWSalCtj3g6ZiFDC9xPg/exec
         headers:
          Content-Type: application/json
         verify_ssl: false
         on_response:
           then:
             - logger.log:
                 format: 'Response status: %d'
                 args:
                   - status_code
```

### Anything in the logs that might be useful for us?

```txt
[09:00:30][D][main:301]: Response status: -5
[09:00:30][W][http_request:081]: HTTP Request failed; URL: https://script.google.com/macros/s/JrZw8O3T_Lh85FNxTUNk8MBragLWo8DsdhKjJ0q6qeWgaWSalCtj3g6ZiFDC9xPg/exec; Error: connection lost
```
