### ISSUE TITLE
Media_player component not playing longer paths

### ISSUE THREAD

**Issue by iondulgheru** [esphome/issues#3381]
### The problem

I am trying to use the media_player component to play music directly from Home Assistant.
Some mp3 files were working, some were not.
I made some debugging, and the conclusion was that the problem is the file path length, including the filename.
I could reproduce this multiple times by renaming mp3 files that didn't work initially so they have a shorter filename, and after that they worked. 
An example of path that is not playing is "http://xxxx:8123/media/media/music_free_and_purchased/singles/Van%20Morrison%20-%20%5B1967%5D%20-%20%5BBlowin%20Your%20Mind%5D%20-%2001%20-%20Brown%20Eyed%20Girl.mp3?authSig=xxxx"
After I shorten the filename I can play it, the path being:
"http://xxxx:8123/media/media/music_free_and_purchased/singles/Van%20Morrison%20-%20%5B1967%5D%20-%20%5BBlowin%20Your%20Mind%5D%20-%2001%20-%20Bro.mp3?authSig=xxxx"

The board I am using is a esp32doit-devkit-v1 with a PCM5102 DAC.

There are no errors in logs. In Home Assistant the loading animation is shown instead of player controls when this problem occurs.

### Which version of ESPHome has the issue?

2022.6.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.6

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

media_player

### Example YAML snippet

```yaml
media_player:
  - platform: i2s_audio
    id: media_out
    name: ${friendly_name}
    dac_type: external
    i2s_lrclk_pin: GPIO5
    i2s_dout_pin: GPIO18
    i2s_bclk_pin: GPIO19
    mode: mono
```
