### ISSUE TITLE
BME280 suddenly starts reporting pressures around 700hPa instead of 1000hPa after deep sleep.

### ISSUE THREAD

**Issue by dbaarda** [esphome/issues#3383]
### The problem

The BME280 sensor seems to suddenly start reporting pressures around 700-760hPa after waking from a deep sleep, after previously reporting normal atmospheric pressures of around 1005-1025hPa (I'm at 34m altitude above sea-level). It doesn't happen always, but after a couple of hours of wake-report-sleep cycles every minute it suddenly starts doing it and then only a full reboot will make it start reporting the right pressure.

### Which version of ESPHome has the issue?

2022.6.0b4

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.6.6

### What platform are you using?

ESP32-IDF

### Board

Adafruit QT Py ESP32-C3 + PiicoDev Atmospheric Sensor BME280

### Component causing the issue

bme280

### Example YAML snippet

```yaml
esphome:
  name: underhouse
  platformio_options:
    board_build.flash_mode: dio

esp32:
# At some point the actual board might be supported.
#  board: adafruit_qt_py_esp32-c3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
  variant: ESP32C3

# Enable logging
logger:

ota:
  password: "<secret>"

mqtt:
  broker: 192.168.7.6
  username: "mqtt"
  password: "<secret>"
  discovery: true
  discovery_retain: true
  discovery_unique_id_generator: mac
  discovery_object_id_generator: device_name
  birth_message:
  will_message:
  shutdown_message:
  on_message:
    - topic: esp/sleep_mode
      payload: 'OFF'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: esp/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.allow: deep_sleep_1

wifi:
  ssid: "<secret>"
  password: "<secret>"
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Underhouse Fallback Hotspot"
    password: "<secret>"

i2c:
  sda: 5
  scl: 6
  scan: true
  id: bus_a

# We need to use globals to share sensor state without circular references.
globals:
   - id: temperature
     type: double
     restore_value: no
     initial_value: 'NAN'
   - id: pressure
     type: double
     restore_value: no
     initial_value: 'NAN'
   - id: humidity
     type: double
     restore_value: no
     initial_value: 'NAN'

# Example configuration entry
sensor:
  - platform: uptime
    name: "system uptime"

  - platform: wifi_signal
    name: "wifi strength"
    update_interval: 60s
    expire_after: 90s

  - platform: template
    name: "Dew Point Temperature"
    id: dewpoint_temperature
    filters:
      - lambda: |-
          return (243.5*(log(id(humidity)/100)+((17.67 * x)/
          (243.5 + x)))/(17.67-log(id(humidity)/100)-
          ((17.67 * x)/(243.5 + x))));
    icon: 'mdi:thermometer-alert'
    unit_of_measurement: °C
    update_interval: never
    expire_after: 90s

  - platform: template
    name: "Sea Level Pressure"
    id: sealevel_pressure
    filters:
      - lambda: |-
          const float STANDARD_ALTITUDE = 34.0; // in meters, see note
          return x / powf(1 - ((0.0065 * STANDARD_ALTITUDE) /
            (id(temperature) + (0.0065 * STANDARD_ALTITUDE) + 273.15)), 5.257); // in hPa
    unit_of_measurement: 'hPa'
    update_interval: never
    expire_after: 90s

  - platform: template
    name: "Absolute Humidity"
    id: absolute_humidity
    filters:
      - lambda: |-
          const float mw = 18.01534;    // molar mass of water g/mol
          const float r = 8.31447215;   // Universal gas constant J/mol/K
          return (6.112 * powf(2.718281828, (17.67 * id(temperature)) /
            (id(temperature) + 243.5)) * x * mw) /
            ((273.15 + id(temperature)) * r); // in grams/m^3
    accuracy_decimals: 2
    icon: 'mdi:water'
    unit_of_measurement: 'g/m³'
    update_interval: never
    expire_after: 90s

  - platform: bme280
    temperature:
      name: "Temperature"
      id: bme280_temperature
      oversampling: 4x
      expire_after: 90s
      on_value:
        then:
        - lambda: |-
            id(temperature) = x;
    pressure:
      name: "Pressure"
      id: bme280_pressure
      oversampling: 4x
      expire_after: 90s
      on_value:
        then:
        - lambda: |-
            id(pressure) = x;
    humidity:
      name: "Humidity"
      id: bme280_humidity
      oversampling: 4x
      expire_after: 90s
      on_value:
        then:
        - lambda: |-
            id(humidity) = x;
            id(dewpoint_temperature).publish_state(id(temperature));
            id(sealevel_pressure).publish_state(id(pressure));
            id(absolute_humidity).publish_state(id(humidity));
    address: 0x77
    update_interval: 60s

deep_sleep:
  id: deep_sleep_1
  run_duration: 1s
  sleep_duration: 54s
```

### Anything in the logs that might be useful for us?

```txt
Note that I've also very occasionally seen error messages logged about "failed to initialize bme280", but when that happens it completely fails to read values at all, and usually resolves itself in a following "wakeup". I'm not sure if these events happen before it starts reporting bad values. I don't think these are correlated, but they might both have the same cause.

Sorry I haven't got a saved sample.
```

### Additional information

This sounds suspiciously like the problem reported here that turned out to be using an uninitialised variable to set the control registers of the BMS280;

https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BME280-pressure-reading-wrong/td-p/6204

In Home Assistant, the graphs look like;

![homeassistant localnet_8123_history_entity_id=sensor underhouse_pressure start_date=2022-06-18T14_00_00 000Z](https://user-images.githubusercontent.com/2046387/174506791-51b69021-1d7e-442a-8240-e083568da15d.png)
