### ISSUE TITLE
Custom UART device and wifi

### ISSUE THREAD

**Issue by piechade** [esphome/issues#3384]
### The problem

I have running an esp32 with esphome, where I developed my own component based on UART.
The problem is that is not working like expected. After sometimes it's not responding anymore.
I enabled logging using RX/TX.

What i get is this, the last line is after power cycle.
https://rentry.co/xosx2

### Which version of ESPHome has the issue?

2022.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.6

### What platform are you using?

ESP32

### Example YAML snippet

```yml
esphome:
  name: smt100-dev

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_ed
      password: !secret wifi_password_ed

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smt100-Dev Fallback Hotspot"
    password: ""

captive_portal:

web_server:
  port: 80
  
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  debug:
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
  
  
sensor:
  - platform: smt100
    counts:
      name: "Garden Zone 1 Counts"
    dielectric_constant:
      name: "Garden Zone 1 Dielectric Constant"
      accuracy_decimals: 2
    temperature:
      name: "Garden Zone 1 Temperature"
      accuracy_decimals: 2
    moisture:
      name: "Garden Zone 1 Humidity"
      accuracy_decimals: 2
    voltage:
      name: "Garden Zone 1 Voltage"
      accuracy_decimals: 2
    update_interval: 10s

```
### Anything in the logs that might be useful for us?

```txt
[D][uart_debug:158]: <<< "18294,1.80,0.00,27.977,5.00\r\n"
w�Zkb�nK���noK����cR���~cV����cR���b�n����noK����cR���~c^����cR���b�n����noK����cR���~c^����cV��Rb�n����noK����cR���~c^����cR���b���cR���~c^����cR���b�n����noK����cR���~cV����cR��Rb�n����noK����cR���~c^����cR��Rb�n�
[D][uart_debug:158]: >>> "GetAllMeasurements!\r"
[D][sensor:125]: 'Garden Zone 1 Counts': Sending state 18302.00000  with 0 decimals of accuracy
```

### Additional information

(https://github.com/piechade/esphome/tree/c6a565f0fce53f04a45619677a7c6e59e66bf393/esphome/components/smt100)
