### ISSUE TITLE
esp32_camera image glitches at highest 2 resolutions since 1.19.0

### ISSUE THREAD

**Issue by SaturnusDJ** [esphome/issues#3385]
### The problem

(Continuation of https://github.com/esphome/issues/issues/2281)

Image glitches for ESP32CAM with version 1.19.0 and higher. No issue in 1.18.0 and lower.
There was a breaking change for cam in 1.19.0 but it _should_ be unrelated. Suspicious though.

640x480 (default), 800x600 and 1024x768 did work without problems in 1.19.0 and HA 2021.5.5. The higher resolutions of 1280x1024 and 1600x1200 resulted in the glitches.

The stream is a mix of normal images and broken images, see this example:

![ESP32Cam glitches](https://i.ibb.co/phngm57/esp32cam.png)
(The black brushes are privacy blockers.)

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.5.5

### What platform are you using?

ESP32

### Board

ESP32CAM

### Component causing the issue

esp32_camera

### Example YAML snippet

```yaml
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: Camera front door
  resolution: 1600x1200
#  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: false
#  max_framerate: 2 fps
#  idle_framerate: 0.1 fps
```
