### ISSUE TITLE
Reboot using a simple user-defined service

### ISSUE THREAD

**Issue by mario-tux** [esphome/issues#339]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io on RPi for HA 0.93.2

**ESP (ESP32/ESP8266, Board/Sonoff):**

nodemcu esp8266-12E lolin v3

**Affected component:**

Maybe https://esphome.io/components/api.html or basic automation building blocks.

**Description of problem:**
I'm trying to use a ESP8266 to send infrared commands to my AC unit. I had success using the transmitter component in esphome. Now I want to expose such commands to HA by means of user-defined services (https://esphome.io/components/api.html#user-defined-services). I started to face reboots of the unit upon service requests. I started to strip off all the not-involved components so now I got a simple user-defined service (with some nested if actions and comparisons on service variables) that reboot upon some specific HA requests. Maybe I'm doing something wrong with strings but it could be an esphome bug. I hope you are able to reproduce the problem.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp_test
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "hassio"
  password: "XXXXXXXXX"
  fast_connect: true

logger:
  level: "VERBOSE"

#api:
#  password: 'XXXXXXXXX'

ota:
  password: 'XXXXXXXXX'

api:
  password: 'XXXXXXXXX'
  services:
    - service: ac_set_state
      variables:
        op_mode: string
        temp: int
        fan_mode: string
        swing_mode: string
      then:
        - logger.log: "Setting up AC..."
        - if:
            condition:
              lambda: 'return op_mode.compare("cool") == 0;'
            then:
              - logger.log: "COOL"
              - if:
                  condition:
                    lambda: 'return fan_mode.compare("auto") == 0;'
                  then:
                    - if:
                        condition:
                          lambda: 'return temp == 16;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_auto_swing_manual_temp_16"
              - if:
                  condition:
                    lambda: 'return fan_mode.compare("low") == 0;'
                  then:
                    - if:
                        condition:
                          lambda: 'return temp == 16;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_16"
                    - if:
                        condition:
                          lambda: 'return temp == 17;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
              - if:
                  condition:
                    lambda: 'return fan_mode.compare("medium") == 0;'
                  then:
                    - if:
                        condition:
                          lambda: 'return temp == 16;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_16"
                    - if:
                        condition:
                          lambda: 'return temp == 17;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
                    - if:
                        condition:
                          lambda: 'return temp == 18;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_16"
                    - if:
                        condition:
                          lambda: 'return temp == 19;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
              - if:
                  condition:
                    lambda: 'return fan_mode.compare("high") == 0;'
                  then:
                    - if:
                        condition:
                          lambda: 'return temp == 16;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_16"
                    - if:
                        condition:
                          lambda: 'return temp == 17;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
                    - if:
                        condition:
                          lambda: 'return temp == 18;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_16"
                    - if:
                        condition:
                          lambda: 'return temp == 19;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
                    - if:
                        condition:
                          lambda: 'return temp == 20;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_16"
                    - if:
                        condition:
                          lambda: 'return temp == 21;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
                    - if:
                        condition:
                          lambda: 'return temp == 22;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_16"
                    - if:
                        condition:
                          lambda: 'return temp == 23;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
                    - if:
                        condition:
                          lambda: 'return temp == 24;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_16"
                    - if:
                        condition:
                          lambda: 'return temp == 25;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
                    - if:
                        condition:
                          lambda: 'return temp == 26;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_16"
                    - if:
                        condition:
                          lambda: 'return temp == 27;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
                    - if:
                        condition:
                          lambda: 'return temp == 28;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
                    - if:
                        condition:
                          lambda: 'return temp == 29;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"
                    - if:
                        condition:
                          lambda: 'return temp == 30;'
                        then:
                          - logger.log: "switch.turn_on: ac_mode_cool_fan_low_swing_manual_temp_17"

        - if:
            condition:
              lambda: 'return op_mode.compare("off") == 0;'
            then:
              - logger.log: "OFF"
              - logger.log: "switch.turn_on: ac_mode_off"

time:
  - platform: homeassistant
    id: homeassistant_time
```

**Traceback (if applicable):**

```
```
The compilation goes fine. On the output (network or serial) I can't spot anything of interest.

**Additional information and things you've tried:**
From HA I can invoke (multiple time) the service without any problem using the following params:
- `{ "op_mode": "cool", "temp": 16, "fan_mode": "medium", "swing_mode": "manual"}`
- `{ "op_mode": "off", "temp": 16, "fan_mode": "medium", "swing_mode": "manual"}`

I get a reboot on something related the long if statements queue in "fan_mode = high":
- `{ "op_mode": "cool", "temp": 16, "fan_mode": "high", "swing_mode": "manual"}`

It could be related to the string variables and their comparisons. I did a quick test replacing all with integer variables and integer comparisons: no reboots.
