### ISSUE TITLE
slow_pwm - Output glitches off after several hours of running

### ISSUE THREAD

**Issue by marshn** [esphome/issues#3393]
### The problem

I am using a slow_pwm output with a period of 4 seconds to indirectly control the state of an LED. The slow_pwm output initially operates correctly, but after several hours the operation becomes erratic.

When the slow_pwm output is set to 100% it would be expected to remain 'On' at all time. Initially this is the case, but after several hours running the output switches 'Off' briefly near the end of the period. Over time the problem becomes worse, with the output apparently flickering 'On' and 'Off' at random.

It appears that the problem was introduced by [PR #3004](https://github.com/esphome/esphome/pull/3004) into espHome 2022.2, file esphome/components/slow_pwm/slow_pwm_output.cpp. The 'now' time millisecond runtime value is cast to a float before being compared with a target value and loses precision, resulting in an incorrect result. The code was changed to improved readability, but in doing so an issue has been introduced which becomes apparent after several hours running.

[esphome/esphome/components/slow_pwm/slow_pwm_output.cpp](https://github.com/esphome/esphome/blob/99170f3eeb2c25413b8c428af9eea494136faf07/esphome/components/slow_pwm/slow_pwm_output.cpp#L48)

Line 48 in [99170f3](https://github.com/esphome/esphome/commit/99170f3eeb2c25413b8c428af9eea494136faf07)

In 2022.1 the comparison to determine the state of the output was:

```
 if (scaled_state > now - this->period_start_time_) {
    this->set_output_state_(true);
  } else {
    this->set_output_state_(false);
  }
```

The equivalent test introduced in 2002.2 is now:
```
  this->set_output_state_(now < this->period_start_time_ + scaled_state);
```
When the node has been running for just over 24 hours representative values of the variables involved may be as follows (with a 4 second period and the output set to 100%):

now = 86495996                                        (unsigned int,86495996 = 24 hours + 92 seconds)
this->period_start_time_ = 86492000           (unsigned int)
scaled_state = 4000.0                                 (float)

The 2022.1 and previous case would evaluate to:
scaled_state > now - this->period_start_time_
4000.0 > 86495996 - 86492000
4000.0 > 3996.0 = True - output correctly remains On

In the 2022.2 and onwards case this will evaluate to:
now < this->period_start_time_ + scaled_state
86495996 < 86492000 + 4000.0
86496000.0 < 86496000.0 = False - output erroneously switches Off until end of period

The output erroneously switched off when the 'now' value rounds up to the next second when converted to a float before the comparison is made (integer 86495996 is represented as float 86496000.0).

When the node starts up and the millisecond run time value is small both varsions work OK. Once the runtime can no longer be accurately represented once cast to a float the test produces incorrect results. As the runtime increases the results become more and more erratic.

There are also likely to be overflow issues once the sum of the 'now' time + the PWM period exceed the 32 bit integer value. To avoid overflow errors subtracting one time value from the other to obtain a delta is generally recommended (which the old code did). However, I'm not sure how the old code would handle the millisecond count rolling over after 49 days.

The similar change on line 43 of the same file, to determine the end of a period, will probably also cause erratic results. It may be that this change only causes the period length to jitter, rather than glitch the outout off, and may be less noticeable.

### Which version of ESPHome has the issue?

2022.2 onwards

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32-IDF

### Board

pico32

### Component causing the issue

slow_pwm

### Example YAML snippet

```yaml
output:
  - platform: slow_pwm
    id: power_led_pwm
    period: 4s
    restart_cycle_on_state_change: false
    state_change_action:
      - lambda: |-
          ESP_LOGI("main", "power_led_pwm output = %d", state);

switch:
  - platform: gpio
    name: ${device_name} Relay
    pin:
      number: GPIO25
      inverted: no
    id: switch_relay
    on_turn_on:
      - output.set_level:
          id: power_led_pwm
          level: 100%
    on_turn_off:
      - output.set_level:
          id: power_led_pwm
          level: 0%
```
