### ISSUE TITLE
Mireds are exported as float to HA

### ISSUE THREAD

**Issue by RubenKelevra** [esphome/issues#3399]
### The problem

I specified a `cwww` light with a `2700 K` and a `6500 K` channel. But HA does not work with Kelvin, but with mired. The conversion will lead to values beeing send to HA for min/max in float – which is completely unnecessary, as HA will only send integer mireds to the lamps.

### Which version of ESPHome has the issue?

2022.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.7

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

light

### Example YAML snippet

```yaml
output:
  - platform: esp8266_pwm
    zero_means_zero: true
    min_power: 0.005
    pin: D2
    frequency: 2000 Hz
    id: pwm_output_warm_white
  - platform: esp8266_pwm
    zero_means_zero: true
    min_power: 0.005
    pin: D5
    frequency: 2000 Hz
    id: pwm_output_cold_white

light:
  - platform: cwww
    name: $friendly_name
    cold_white: pwm_output_cold_white
    warm_white: pwm_output_warm_white
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true
```

### Additional information

These are the min/max mired shown in HA:

```yaml
      "light": [
        {
          "object_id": "kitchen_pendant_light",
          "key": 954997081,
          "name": "Kitchen Pendant Light",
          "unique_id": "kitchen-pendant-lightlightkitchen_pendant_light",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "supported_color_modes": [
            19
          ],
          "min_mireds": 153.8462,
          "max_mireds": 370.3704,
          "effects": [],
          "legacy_supports_brightness": true,
          "legacy_supports_rgb": false,
          "legacy_supports_white_value": false,
          "legacy_supports_color_temperature": true
        }
      ]
```
