### ISSUE TITLE
Simple esphome config, random light toggles?

### ISSUE THREAD

**Issue by dave** [esphome/issues#3403]
### The problem

I have a M5Stack Atom Light connected to an M5Stack PWM module. I've flashed it with the simplest esphome config I can come up with, which should just toggle the light when I press the button on the Atom. It works, but randomly (approximately every half hour) it toggles the light without any action - the time in between unintended toggles seems to be random - e.g. not repeating regularly. 

Is the config file below correct? Is there any way it could be improved / simplified? How would I go about debugging this? How would I go about telling if it's a bug with the Atom or with esphome?

Do these M5Stack devices have a reputation for being flaky like this? I also have [this issue open](https://github.com/esphome/issues/issues/3341) where this device reboots when lots of MQTT messages are received at once... 🤷‍♂️

### Which version of ESPHome has the issue?

Version: 2022.5.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32

### Board

M5Stack Atom

### Component causing the issue

not sure

### Example YAML snippet

```yaml
substitutions:
  device_name: light1
  friendly_name: Light 1

esphome:
  name: ${device_name}

esp32:
  board: m5stack-atom
  framework:
    type: arduino

output:
  - platform: ledc
    pin: GPIO22
    id: gpio_22
    frequency: 1220Hz

light:
  - platform: monochromatic
    output: gpio_22
    name: ${friendly_name} Light
    id: light_id

binary_sensor:
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: ${friendly_name} Button
    on_press:
      then:
        - light.toggle:
            id: light_id
            transition_length: 0s

logger:
  level: NONE

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "hogxyvZGcsFa"

captive_portal:
```
