### ISSUE TITLE
Nextion set_touch_sleep_timeout bounds are weird

### ISSUE THREAD

**Issue by nagyv** [esphome/issues#3410]
### The problem

The [set_touch_sleep_timeout code](https://esphome.io/api/nextion__commands_8cpp_source.html#l00020) checks if the parameter is within the bounds of 3-65535

The [Nextion instruction set](https://nextion.tech/instruction-set/) writes

> Sets internal No-touch-then-sleep timer to specified value in seconds min 3, max 65535, **default 0** (max: 18 hours 12 minutes 15 seconds) Nextion will auto-enter sleep mode if and when this timer expires. Note: Nextion device needs to exit sleep **to issue thsp=0** to disable sleep on no touch, otherwise once thsp is set, it will persist until reboot or reset.

Based on the above, the correct range would be `3-65535 or 0`

### Which version of ESPHome has the issue?

2022.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.7

### What platform are you using?

ESP8266

### Board

WEMOS-D1-MINI

### Component causing the issue

display/nexion

### Example YAML snippet

```yaml
button:
  - platform: template
    name: "Wake up"
    on_press:
      - logger.log: Wake up
      - lambda:
          id(internal_display).sleep(false);
          id(internal_display).set_touch_sleep_timeout(0);
```
