### ISSUE TITLE
DFRobot Lightning Distance Sensor AS3935/SEN0290 will not be found

### ISSUE THREAD

**Issue by moonilightshaker** [esphome/issues#3411]
### The problem

Hello,
the AS3935 from DFRobot [Link](https://www.dfrobot.com/product-1828.html) not be found under ESPHome.
On the same board with ESPEasy and Tasmota this sensor is found with an I2C scan. On Tasmota the sensor works fine.

Board: ESP32DEV
Interface: I2C

![Tasmota](https://user-images.githubusercontent.com/59542603/176501445-f2eb5c74-f243-4eaf-aee9-d36697b5b300.JPG)
![Tasmota2](https://user-images.githubusercontent.com/59542603/176501476-01b4cbdf-104d-4705-a53f-eb7e4048fe49.JPG)

### Which version of ESPHome has the issue?

v2022.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.1

### What platform are you using?

ESP32

### Board

DEV

### Component causing the issue

I2C

### Example YAML snippet

```yaml
i2c:
  sda: 21
  scl: 22
  scan: true

# Example configuration for I²C (decide for one!)
as3935_i2c:
  address: 0x3
  irq_pin: 14
  indoor: false
# Example shared configuration
sensor:
  - platform: as3935
    lightning_energy:
      name: "Lightning Energy"
    distance:
      name: "Distance Storm"
binary_sensor:
  - platform: as3935
    name: "Storm Alert"
```

### Anything in the logs that might be useful for us?

```txt
NO
```
