### ISSUE TITLE
Total daily energy does not reset due to missing SNTP time sync

### ISSUE THREAD

**Issue by mondbaron** [esphome/issues#3412]
### The problem

My `total_daily_energy` sensor on a Gosund SP111 (which is based on an `esp8285` platform) does not reset to zero but continues integrating. So far, I figured out, that this this issue started after a migration from Home Assistant API and `homeassistant` time source to MQTT and `sntp` time platform. 

For debugging purpose a added a `text_sensor`  to display the current time (see config below). This sensor starts counting from `01:00:00 - 01-01-1970` wich, I guess, happens due to a failed NTP sync while still respecting the `timezone: Europe/Berlin`.

All time-relevant components are provided in the attached yaml snippet.
The SNTP config seems to be accepted. The following lines do appear in the attached log snippet.

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.7

### What platform are you using?

ESP8266

### Board

Gosund SP111

### Component causing the issue

time/sntp

### Example YAML snippet

```yaml
[...]

esp8266:
  board: esp8285
  restore_from_flash: true

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - myntp1.mylocaldomain
      - myntp2.mylocaldomain
      - europe.pool.ntp.org

text_sensor:
  - platform: template
    name: "System Time (SNTP)"
    lambda: |-
      auto time_str = id(sntp_time).now().strftime("%H:%M:%S - %d-%m-%Y");
      return { time_str };

sensor:
  - platform: total_daily_energy
    name: Todays Usage
    power_id: power_wattage
    filters:
      - multiply: 0.001
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh
    
    [...]
```

### Anything in the logs that might be useful for us?

```txt
[20:02:44][I][ota:341]: OTA update finished!
[20:03:00][I][mqtt:216]: MQTT Connected!
[20:03:00][C][sntp:025]: Setting up SNTP...
[20:03:01][I][app:062]: setup() finished successfully!
[...]
.. correct Wifi/DHCP settings including good DNS servers ...
[...]
[20:03:01][C][sntp:050]: SNTP Time:
[20:03:01][C][sntp:051]:   Server 1: 'myntp1.mylocaldomain'
[20:03:01][C][sntp:052]:   Server 2: 'myntp2.mylocaldomain'
[20:03:01][C][sntp:053]:   Server 3: 'europe.pool.ntp.org'
[20:03:01][C][sntp:054]:   Timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
[...]
[20:03:38][D][text_sensor:067]: 'System Time (SNTP)': Sending state '01:00:45 - 01-01-1970'
[...]
```

### Additional information

I adapted a config from https://www.esphome-devices.com/devices/Gosund-SP111 and https://templates.blakadder.com/gosund_SP111_v1_4 to work with my Gosund SP111 v1.4.
