### ISSUE TITLE
Connectivity loss for just some ESPHome devices on WiFi network every GTK rekeying interval

### ISSUE THREAD

**Issue by climategadgets** [esphome/issues#3415]
### Expected Behavior
All ESPHome devices on the network stay connected.

### Actual Behavior
* Some (but not all) ESPHome devices on WiFi network lose connectivity every "GTK rekeying" interval set for that network;
* Different devices exhibit connectivity drops at different times, the usual trigger for the change being an arrival of a device previously not present on this network;
* Once the set of devices losing connectivity and staying connected gets determined, it can stay the same for extended periods of time (weeks to months).

### Charts
Two different time periods on the same set of devices with GTK rekeying intervals set to 3600 (default for the networking gear), and to 28800.
![image](https://user-images.githubusercontent.com/1731579/176836467-bbc76278-22e9-464b-a9a0-85e4c4b47b52.png)
![image](https://user-images.githubusercontent.com/1731579/176837053-a29ecbd3-cf0b-447d-b5f1-6e490475549a.png)

### Which version of ESPHome has the issue?

Last known affected version is 2021.10.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

Wemos D1

### Component causing the issue

wifi

### Example YAML snippet

```yaml
# Standard WiFi configuration with no gimmicks
---
esphome:
  name: <name
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: <ssid>
  password: <password>
```
