### ISSUE TITLE
ESP32-C3 & UART component error when compiling

### ISSUE THREAD

**Issue by bakermat** [esphome/issues#3419]
### The problem

When adding the UART component for a Lolin C3 Mini board the firmware doesn't compile and throws an error. When removing the UART component from the YAML file it compiles correctly.

I believe any board using these build flags runs into the issue, in case this helps:
```
-DARDUINO_USB_CDC_ON_BOOT=1
-DARDUINO_USB_MODE=1
```

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

 2022.6.7

### What platform are you using?

ESP32

### Board

lolin_c3_mini

### Component causing the issue

uart

### Example YAML snippet

```yaml
esphome:
  name: testy-mctestface
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: lolin_c3_mini
  variant: esp32c3
  framework: 
    type: arduino
    version: 2.0.3
    platform_version: 4.3.0

uart:
  rx_pin:
    number: 10
  baud_rate: 115200
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/bla.yaml...
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Generating C++ source...
INFO Compiling app...
Processing testy-mctestface (board: lolin_c3_mini; framework: arduino; platform: platformio/espressif32 @ 4.3.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <WiFi> 2.0.0
|-- <FS> 2.0.0
|-- <Update> 2.0.0
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <DNSServer> 2.0.0
|-- <ESPmDNS> 2.0.0
|-- <ArduinoJson> 6.18.5
|-- <Dsmr> 0.5.0
|-- <Crypto> 0.4.0
Compiling /data/testy-mctestface/.pioenvs/testy-mctestface/src/esphome/components/uart/uart_component_esp32_arduino.cpp.o
src/esphome/components/uart/uart_component_esp32_arduino.cpp: In member function 'virtual void esphome::uart::ESP32ArduinoUARTComponent::setup()':
src/esphome/components/uart/uart_component_esp32_arduino.cpp:90:25: error: cannot convert 'HWCDC*' to 'HardwareSerial*' in assignment
     this->hw_serial_ = &Serial;
                         ^~~~~~
*** [/data/testy-mctestface/.pioenvs/testy-mctestface/src/esphome/components/uart/uart_component_esp32_arduino.cpp.o] Error 1
========================== [FAILED] Took 4.59 seconds ==========================
```
```


### Additional information

_No response_

**Comment by Mosher23** [comment]
I have exactly same error here with adafruit_qt_py_c3 board

**Comment by Prologer** [comment]
Facing the same issues with 2022.8.0 and 
`esp32:
  board: lolin_c3_mini
  framework:
    type: arduino
    version: 2.0.4
    platform_version: 5.1.1`

**Comment by evlo** [comment]
ttgo t-01c3 also same 
```
    platform_version: 4.4.0
    version: 2.0.3
```

**Comment by evlo** [comment]
```
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0
```
did build for me

but again my board is actually `ttGO-T-01C3` and i did not look hot to make custom boards yet

**Comment by PaulAntonDeen** [comment]
I get the same issue with this configuration:
`esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0`
I tried multiple version and platform_versions. Have not been able to find one that compiles.

**Comment by TiddlyWiddly** [comment]
Same problem with this configuration

`esp32:
  board: lolin_c3_mini
  variant: esp32c3
  framework:
    type: arduino
    version: 2.0.5
    platform_version: 5.2.0`

**Comment by joostbijl** [comment]
I'm having this issue too. It looks like something is off with the pin assignment on the C3 compared to the D1?

```
esphome:
  name: ts27meter
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: lolin_c3_mini
  variant: esp32c3
  framework:
    type: arduino
    version: 2.0.5
    platform_version: 5.2.0

uart:
  rx_pin: 20
  baud_rate: 115200
  rx_buffer_size: 1500
```
the error is:
```
Compiling .pioenvs/ts27meter/src/esphome/core/application.cpp.o
src/esphome/components/uart/uart_component_esp32_arduino.cpp: In member function 'virtual void esphome::uart::ESP32ArduinoUARTComponent::setup()':
src/esphome/components/uart/uart_component_esp32_arduino.cpp:90:25: error: cannot convert 'HWCDC*' to 'HardwareSerial*' in assignment
     this->hw_serial_ = &Serial;
                         ^~~~~~
*** [.pioenvs/ts27meter/src/esphome/components/uart/uart_component_esp32_arduino.cpp.o] Error 1
```
When looking ath the uart_component_esp32_arduino.cpp file, it might be an issue with not correctly defining CONFIG_IDF_TARGET_ESP32C3 or incorrect assignment of pin numbers in the esphome yaml config?

**Comment by evlo** [comment]
```
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0
```

this did not work for you?

**Comment by evlo** [comment]
> I get the same issue with this configuration:
> 
> ```
> esp32:
>   board: lolin_s2_mini
>   variant: ESP32S2
>   framework:
>     type: arduino
>     version: 2.0.3
>     platform_version: 4.4.0
> ```
> 
> I tried multiple version and platform_versions. Have not been able to find one that compiles.

Why don't you use esp32-c3-devkitm-1 with the 2.03 and 4.4.0 ?

**Comment by evlo** [comment]
```
uart:
  id: uart_bus
  tx_pin: GPIO21
  rx_pin: GPIO20
  rx_buffer_size: 2048  
  baud_rate: 300
  data_bits: 7
  stop_bits: 1
  parity: EVEN
  debug: 
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
```

**Comment by joostbijl** [comment]
> would you mind trying building with
> 
> ```
> esp32:
>   board: esp32-c3-devkitm-1
>   framework:
>     type: arduino
>     version: 2.0.3
>     platform_version: 4.4.0
> uart:
>   tx_pin: GPIO21
>   rx_pin: GPIO20
> ```
> 
> I'm curious if it might be the port naming thing, altrought it should not be, it is now first and easiest thing I see.


Yes, this works. Thanks for the hint.

I did not think a second of trying another board than the one i actually have.

**Comment by TiddlyWiddly** [comment]
Sorry, I got this working and never came back to post my fix. 

This worked for me: 

`esphome:
  name: test-c3-pico
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
    board_build.variant: esp32c3

esp32:
  #board: lolin_c3_mini
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino
    version: 2.0.5
    platform_version: 5.2.0

uart:
  rx_pin: GPIO20
  tx_pin: GPIO21
  baud_rate: 115200`

**Comment by manuelsteiner** [comment]
Hi,

I have the adafruit_qt_py_s2 board and I am running in the same issue. When changing the underlying platformio framework to `esp-idf`, compilation is successful but either the ESP32 hangs or does not output any logs via UART on USB. I need to investigate further but I think it actually does not boot with a minimal config since no WIFI is joined or created.

When changing the board, logs are also not sent to the USB UART. Which is presumabily the case because the platformio config is wrong.

Has anyone had any progress enabling the UART and still getting the logger to output to USB with the arduino platform?

Any help would be appreciated.

**Comment by evlo** [comment]
> > would you mind trying building with
> > ```
> > esp32:
> >   board: esp32-c3-devkitm-1
> >   framework:
> >     type: arduino
> >     version: 2.0.3
> >     platform_version: 4.4.0
> > uart:
> >   tx_pin: GPIO21
> >   rx_pin: GPIO20
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm curious if it might be the port naming thing, altrought it should not be, it is now first and easiest thing I see.
> 
> Yes, this works. Thanks for the hint.
> 
> I did not think a second of trying another board than the one i actually have.

Now with esphome 2022.12.0 i have no success building working firmware

**Comment by LayerCakeMakes** [comment]
> Hi,
> 
> I have the `adafruit_qt_py_s2` board and I am running in the same issue. When changing the underlying platformio framework to `esp-idf`, compilation is successful but either the ESP32 hangs or does not output any logs via UART on USB. I need to investigate further but I think it actually does not boot with a minimal config since no WIFI is joined or created.
> 
> When changing the board, logs are also not sent to the USB UART. Which is presumabily the case because the platformio config is wrong.
> 
> Has anyone had any progress enabling the UART and still getting the logger to output to USB with the arduino platform?
> 
> Any help would be appreciated.

I'm having the same issues with UART but I also have boot issues with the arduino framework selected, it only joins every few boots ,so that might be a separate issue. If no network is joined the chip also gets quite hot.

**Comment by ssieb** [comment]
> When changing the board, logs are also not sent to the USB UART. Which is presumabily the case because the platformio config is wrong.

See https://esphome.io/components/logger.html#hardware-uarts

**Comment by manuelsteiner** [comment]
Thanks, 

I've been through that. I think it doesn't even boot with the esp-idf platform. But I'll investigate further to confirm that is actually the case.

When choosing a different board, I'd presumably have to re-configure a bunch of things, such as pins and so on to make things work?

**Comment by LayerCakeMakes** [comment]
@manuelsteiner I've just tried with ESP-IDF and it works fine for me. Only problem is the neopixel LED is not supported in the ESP-IDF framework so if you need it you're still out of luck.

```
...
esp32:
  board: adafruit_qtpy_esp32s2
  framework:
    type: esp-idf
...
```

**Comment by LayerCakeMakes** [comment]
> 

With a minimal config it boots and joins a network. I had to test the USB logging as I never use that feature, I just look wirelessly at the logs, I don't think it logs via USB by default, at least I did not get any messages.

**Comment by manuelsteiner** [comment]
@LayerCakeMakes Thank you for confirming.

**Comment by LayerCakeMakes** [comment]
@manuelsteiner USB logging works if you set `hardware_uart: USB_CDC`

**Comment by evlo** [comment]
@LayerCakeMakes can you post the minimal config with uart that works for you?

**Comment by LayerCakeMakes** [comment]
@evlo manuelsteiner and I are having the same issue but with the Adafruit QT Py S2 so this is probably not as helpful for you but here it is:
```
esphome:
  name: uartdemo

esp32:
  board: adafruit_qtpy_esp32s2
  framework:
    type: esp-idf

logger:
api:
ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  rx_pin: RX
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
```

**Comment by manuelsteiner** [comment]
That's weird. I tried again, even with a fresh board. Flashed fine but wouldn't come up and join a network or print logs on the serial port. Super strange that this works fine for you but I've tried with two boards now an neither feel like doing much.

**Comment by LayerCakeMakes** [comment]
Hmm it seems to me that booting is hit or miss. Sometimes I need to
disconnect the power supply completely, the reset button isn't enough...
Strange for sure

**Comment by manuelsteiner** [comment]
Ah interesting, thanks for that. Seems like there is something strange going on still and it's not just me.

**Comment by tomav** [comment]
Same issue here when adding uart block in my config for a Lolin S2 Mini board.
Using v2022.12.3 Docker version. Tested on 2 machines.

```
uart:
  id: uart_bus
  rx_pin: GPIO11
  baud_rate: 9600
  parity: EVEN
  data_bits: 7
```

```
Compiling .pioenvs/test/src/main.cpp.o
src/esphome/components/uart/uart_component_esp32_arduino.cpp: In member function 'virtual void esphome::uart::ESP32ArduinoUARTComponent::setup()':
src/esphome/components/uart/uart_component_esp32_arduino.cpp:90:25: error: cannot convert 'USBCDC*' to 'HardwareSerial*' in assignment
     this->hw_serial_ = &Serial;
                         ^~~~~~
*** [.pioenvs/test/src/esphome/components/uart/uart_component_esp32_arduino.cpp.o] Error 1
========================== [FAILED] Took 6.79 seconds ==========================
```

As suggested, I was able to compile using `esp-idf`. Build seems to work (teleinfo module) but have a lot of errors like :

```
[23:12:12][E][teleinfo:133]: No group found
[23:12:16][D][sensor:127]: 'WiFi Signal dB': Sending state -61.00000 dBm with 0 decimals of accuracy
[23:12:43][E][teleinfo:038]: bad crc: got 60 except 56
[23:12:43][E][teleinfo:038]: bad crc: got 60 except 50
[23:12:43][D][sensor:127]: 'Linky Index': Sending state 35917.92578 kWh with 0 decimals of accuracy
[23:12:43][E][teleinfo:038]: bad crc: got 34 except 41
[23:12:43][E][teleinfo:168]: Invalid value for tag EASF02
[23:12:43][E][teleinfo:038]: bad crc: got 41 except 72
[23:12:43][E][teleinfo:038]: bad crc: got 41 except 35
[23:12:43][E][teleinfo:038]: bad crc: got 32 except 88
[23:12:43][E][teleinfo:038]: bad crc: got 32 except 95
```

I don't know if these errors are related to `teleinfo` or the build itself yet.

**Comment by LayerCakeMakes** [comment]
As mentioned in #3988 I could get the UART to work with this minimal configuration (no log output via USB but I don't need that)

```
esphome:
  name: minimal-uart
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

esp32:
  board: adafruit_qtpy_esp32s2
  framework:
    type: arduino

logger:
api:
ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600
```

The important part is the extra flags.

**Comment by tomav** [comment]
Hi @LayerCakeMakes, I managed to compile a basic project with your suggestion and it works.
I'll try a full project as soon as I can to see if it behaves as expected. 
Thanks!

**Comment by tomav** [comment]
Confirmed: compiles and works as expected. Thanks @LayerCakeMakes

**Comment by piotrva** [comment]
I faced the same issue for dfrobot_beetle_esp32c3, but no issues for esp32-c3-devkitm-1.
It would however be nice to have an ability to use USB-CDC for a logger output.

**Comment by nebulous** [comment]
For those experiencing intermittent boots - I've noticed that on the esp32-s3-box-lite at least, that booting will fail and reboot before the wifi connect phase _unless_ I'm monitoring the logs via usb. 🤔

**Comment by screek-workshop** [comment]
> 

it's same from here.
which is very wired, only open the logs it can survive. 

i have a  lot c3 without ttl chip but only with usb-cdc.  
maybe is the logger wait something to open the port?

**Comment by evlo** [comment]
For (even my) refference - this is working settings I do use that boot with no logger attached, `- "-DARDUINO_USB_CDC_ON_BOOT=0"` is the key i think, however the board DOES have usb com port emulator


```
esphome:
  name: ${hostname}
  comment: ${comment}
  platformio_options: 
    board_build.flash_mode: dio
    board_build.extra_flags:
      #- "-DARDUINO_USB_MODE=0"
      - "-DARDUINO_USB_CDC_ON_BOOT=0"
  on_boot:
    priority: 300
    then:
      - light.turn_on:
          id: onboard_rgb
          brightness: 20%
          red: 0%
          green: 100%
          blue: 0%        

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
```

I was never able to get it working with esp idf
