### ISSUE TITLE
Conflict between I2S Media Player and ILI9341 display

### ISSUE THREAD

**Issue by jamesmyatt** [esphome/issues#3421]
### The problem

When using both the I2S media player and ILI9341 display, then the media player is unable to play anything. Specifically, playing media just stops immediately (see logs). The display is working fine.

Changing the display to a different driver, e.g. ssd1306_i2c, also works fine. So it's definitely an interaction between these two specific components.

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.6.?

### What platform are you using?

ESP32

### Board

ESP32 WROOM devkit

### Component causing the issue

i2s_audio and ili9341

### Example YAML snippet

```yaml
time:
  - platform: homeassistant
    id: esptime
    timezone: !secret timezone

# SPI bus
spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

# Display
font:
  - file: "gfonts://Bebas Neue@regular"
    id: font2
    size: 110
  - file: "gfonts://Ubuntu Condensed@regular"
    id: font3
    size: 24

color:
  - id: color_time
    red: 80%
    green: 90%
    blue: 100%
    white: 0%

display:
  - platform: ili9341
    model: TFT 2.4
    cs_pin: 5
    dc_pin: 16
    led_pin: 17
    reset_pin: 4
    rotation: 270°
    update_interval: 1s

    lambda: |-
      it.fill(Color::BLACK);

      // Print time in HH:MM format
      it.strftime(0, 200, id(font2), id(color_time), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());
      it.strftime(0, 230, id(font3), id(color_time), TextAlign::BASELINE_LEFT, "%A, %d %B %Y", id(esptime).now());

# Media player
media_player:
  - platform: i2s_audio
    name: "${devicename} Media Player"
    dac_type: external
    i2s_lrclk_pin: 33
    i2s_dout_pin: 26
    i2s_bclk_pin: 25
    mode: mono
    on_play:
      - logger.log: "Playback started!"
    on_pause:
      - logger.log: "Playback paused!"
    on_idle:
      - logger.log: "Playback finished!"
```

### Anything in the logs that might be useful for us?

```txt
[22:14:19][D][media_player:059]: 'eh-a9a730 Media Player' - Setting
[22:14:19][D][media_player:066]:   Media URL: http://192.168.1.6:8123/api/tts_proxy/303f39ed1f3700e1a17bd25528ae64c88b65f991_en_-_google_translate.mp3
[22:14:19][D][main:415]: Playback started!
[22:14:19][D][main:409]: Playback finished!
```

**Comment by nielsnl68** [comment]
I will check this out soon. In the main time could you update your script with the whole script (except the passwords etc.)
then i can compare with my results later.

**Comment by jamesmyatt** [comment]
Thanks @nielsnl68. I'll do this either tonight or tomorrow.

**Comment by jamesmyatt** [comment]
I've uploaded some configs to https://gist.github.com/jamesmyatt/39d0bd0d057110193d3a2e6b297869f6

* `not-working.yaml` - the full file that doesn't work
* `working.yaml` - reduced config above and that actually does work

These results are now using ESPHome 2022.9.1. I'll do some more digging.

**Comment by jamesmyatt** [comment]
OK I've added a `reduced.yaml` which is a simplified version that's also not working. And cutting it down more does get it to work, so my suspicion is that it's actually a RAM issue.

**Comment by jamesmyatt** [comment]
@nielsnl68 Did you get a chance to look at this?

**Comment by jamesmyatt** [comment]
Could the difference be the PSRAM? I'm using an ESP32 D1 mini clone, so it's using a WROOM module, while the espMuse uses the WROVER module.

Whether the display is attached or not shouldn't change anything.

**Comment by nielsnl68** [comment]
Also with my M5Atom Echo works still with the display running.

**Comment by laenbdarceq** [comment]
I can see the same exact problem with the very minimal configuration here below. The board I am using is this one : https://joy-it.net/en/products/SBC-NodeMCU-ESP32 (512kB SRAM, 4MB flash).

The display is 320x240 pixel and is used in grayscale mode, so the buffer should be around 75kB. esphome tells me it is using 43kB (out of 320kB available). So there should still be around 200kB available for the stream (128 kbps) buffering and other variables. Is there any big RAM user I miss here, or is it actually not a RAM issue ? 

``` yaml
esphome:
  name: sandbox
  platform: ESP32
  board: nodemcu-32s

logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

button:
  - platform: template
    id: start_audio
    name: "Start Audio"
    on_press:
      - logger.log: "Start Button Pressed"
      - media_player.volume_set:
          id: i2splayer
          volume: 0%
      - media_player.play_media:
          id: i2splayer
          media_url: !secret media_url
  - platform: template
    id: stop_audio
    name: "Stop Audio"
    on_press:
      - logger.log: "Stop Button Pressed"
      - media_player.stop:
          id: i2splayer

media_player:
  platform: i2s_audio
  name: ESPHome I2S Media Player
  id: i2splayer
  dac_type: external
  i2s_lrclk_pin: GPIO23
  i2s_dout_pin: GPIO22
  i2s_bclk_pin: GPIO21
  mode: mono
  on_play:
    then:
      # - light.turn_on: board_light
      - logger.log: "Playback started"
  on_idle:
    then:
      # - light.turn_off: board_light
      - logger.log: "Idle"
  on_pause:
    then:
      # - light.turn_off: board_light
      - logger.log: "Paused"

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

display:
  - platform: ili9341
    model: TFT 2.4
    cs_pin: 27
    dc_pin: 26
    led_pin: 25  ### see note below ###
    reset_pin: 33
    rotation: 270°
    color_palette: GRAYSCALE
    lambda: |-
      it.fill(Color::BLACK);
```
