### ISSUE TITLE
esp32-c3-devkitm-1 - arduino framework - wrong bootloader - "bootloader__80m.bin" instead of "bootloader_dio_80m.bin"

### ISSUE THREAD

**Issue by mihsu81** [esphome/issues#3424]
### The problem

The wrong bootloader is being selected when compiling for a lolin c3 mini for the android framework - "bootloader__80m.bin" instead of "bootloader_dio_80m.bin".
```
  framework:
    type: arduino
    version: dev
    platform_version: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
```

Error log:
```
Archiving /data/ble-gateway04/.pioenvs/ble-gateway04/libFrameworkArduino.a
Linking /data/ble-gateway04/.pioenvs/ble-gateway04/firmware.elf
RAM:   [==        ]  15.4% (used 50428 bytes from 327680 bytes)
Flash: [========  ]  76.1% (used 1396402 bytes from 1835008 bytes)
Building /data/ble-gateway04/.pioenvs/ble-gateway04/firmware.bin
esp32_create_combined_bin(["/data/ble-gateway04/.pioenvs/ble-gateway04/firmware.bin"], ["/data/ble-gateway04/.pioenvs/ble-gateway04/firmware.elf"])
usage: esptool merge_bin [-h] --output OUTPUT [--format {r,a,w}]
                         [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                         [--flash_mode {keep,qio,qout,dio,dout}]
                         [--flash_size FLASH_SIZE]
                         [--spi-connection SPI_CONNECTION]
                         [--target-offset TARGET_OFFSET]
                         [--fill-flash-size FILL_FLASH_SIZE]
                         <address> <filename> [<address> <filename> ...]
esptool merge_bin: error: argument <address> <filename>: [Errno 2] No such file or directory: '/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/bin/bootloader__80m.bin'
*** [/data/ble-gateway04/.pioenvs/ble-gateway04/firmware.bin] Explicit exit, status 2
========================= [FAILED] Took 110.11 seconds =========================
```

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.7

### What platform are you using?

ESP32

### Board

lolin c3 mini

### Example YAML snippet

```yaml
esphome:
  name: ble-gateway04
  platformio_options:
    board_build.variant: esp32c3
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: dev
    platform_version: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
```

### Anything in the logs that might be useful for us?

```txt
Archiving /data/ble-gateway04/.pioenvs/ble-gateway04/libFrameworkArduino.a
Linking /data/ble-gateway04/.pioenvs/ble-gateway04/firmware.elf
RAM:   [==        ]  15.4% (used 50428 bytes from 327680 bytes)
Flash: [========  ]  76.1% (used 1396402 bytes from 1835008 bytes)
Building /data/ble-gateway04/.pioenvs/ble-gateway04/firmware.bin
esp32_create_combined_bin(["/data/ble-gateway04/.pioenvs/ble-gateway04/firmware.bin"], ["/data/ble-gateway04/.pioenvs/ble-gateway04/firmware.elf"])
usage: esptool merge_bin [-h] --output OUTPUT [--format {r,a,w}]
                         [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                         [--flash_mode {keep,qio,qout,dio,dout}]
                         [--flash_size FLASH_SIZE]
                         [--spi-connection SPI_CONNECTION]
                         [--target-offset TARGET_OFFSET]
                         [--fill-flash-size FILL_FLASH_SIZE]
                         <address> <filename> [<address> <filename> ...]
esptool merge_bin: error: argument <address> <filename>: [Errno 2] No such file or directory: '/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/bin/bootloader__80m.bin'
*** [/data/ble-gateway04/.pioenvs/ble-gateway04/firmware.bin] Explicit exit, status 2
========================= [FAILED] Took 110.11 seconds =========================
```

**Comment by nielsnl68** [comment]
could you try the following:
```yaml
esp32:
  board: lolin_c3_mini
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0
```

This works for me, using the esphome *dev* branch.

**Comment by evlo** [comment]
When I tried
```
type: arduino
    version: 2.0.3
    platform_version: 4.4.0
```
I did end up with 
```
error: cannot convert 'HWCDC*' to 'HardwareSerial*' in assignment
     this->hw_serial_ = &Serial;
```

**Comment by mihsu81** [comment]
Your indentation is wrong.

Mine is:
```yaml
esp32:
  board: lolin_c3_mini
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0
```
