### ISSUE TITLE
SNTP time sync takes too long

### ISSUE THREAD

**Issue by delthia** [esphome/issues#3431]
### The problem

When trying to use a device with esphome on its own, it is useful for it to have the time synced so it can turn on or off at the desired intervals, but so far, it takes too long after booting up for the time to get synced, which is a problem in case the device reboots for any reason (for example, if there is a power outage, or it were to crash), near the time that it is supposed to execute an automation.

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

I'm not using homeassistant

### What platform are you using?

ESP8266

### Board

Sonoff Basic

### Example YAML snippet

```yaml
time:
  - platform: sntp
    on_time:
      - cron: '30 23 * * * 1-5'
        then:
          - switch.turn_off: relay
      - cron: '30 07 * * * 2-6'
        then:
          switch.turn_on: relay
```

### Additional information

Usually the time is synced every 15 minutes or so, but it also takes around that time for the time to get in sync (or at least for that to be shown in the logger) after the relay is plugged in. 8 minutes, as shown in the screenshot, is the lower I've seen after an evening of testing
![image](https://user-images.githubusercontent.com/101663529/178077597-ce8bf417-47bf-419e-a7bd-9f2fb980563d.png)
