### ISSUE TITLE
multiple (2) RDM6300 not working

### ISSUE THREAD

**Issue by eckinga** [esphome/issues#3439]
### The problem

Hello,

i want to use one esp32 for 2 RDM6300 rfid reader but I can't get to work cause I can't define both. One working well but for 2 i can't compile. Perhaps the component isn't mentioned for use with multiple?
But the doc says about id... what's that for?

Btw. If this is possible to solve how to get a different device_id for the second homeassistant.tag_scanned.

thanks
Christian

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.7.3

### What platform are you using?

ESP32

### Board

esp32-devkitv1

### Component causing the issue

rdm6300

### Example YAML snippet

```yaml
uart:
  - rx_pin: GPIO3
    baud_rate: 9600
    id: UART1

  - rx_pin: GPIO16
    baud_rate: 9600
    id: UART2

rdm6300: 
  - id: rdm1
    on_tag: 
      then: 
       - homeassistant.tag_scanned: "return to_string(x);"
    uart_id: UART1
  - id: rdm2
    on_tag: 
      then: 
       - homeassistant.tag_scanned: "return to_string(x);"
    uart_id: UART2
```

### Anything in the logs that might be useful for us?

```txt
Failed config

rdm6300: [source /config/esphome/door.yaml:52]
  
  expected a dictionary.
  - id: rdm1
    on_tag: 
      then: 
        - homeassistant.tag_scanned: return to_string(x);
    uart_id: UART1
  - id: rdm2
    on_tag: 
      then: 
        - homeassistant.tag_scanned: return to_string(x);
    uart_id: UART2
```
