### ISSUE TITLE
Binary_Sensor API Service call

### ISSUE THREAD

**Issue by Rodrigoah** [esphome/issues#344]
Hi, I am trying to use ESPHome as a remote for calling services on home assistant. 
I believe I am using the API call correctly as per https://esphome.io/components/api.html

However I get the following error when validating the yaml

```
 Failed config

binary_sensor.gpio: [source /config/esphome/LED_strip.yaml:31]
  platform: gpio
  pin: 
    number: D5
    mode: INPUT_PULLUP
    inverted: True
  name: Switch D5
  on_click:  [source /config/esphome/LED_strip.yaml:38]
    min_length: 50ms
    max_length: 350ms
    then:  [source /config/esphome/LED_strip.yaml:41]
      
      Cannot have two actions in one item. Key 'homeassistant.service' overrides 'service'! Did you forget to indent the block inside the action?.
      - [source /config/esphome/LED_strip.yaml:41]
        homeassistant.service: 
        service: light.toggle
        entity_id: light.ledes_cama
```

My code is the following:

```
binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    name: "Button D5"
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
      - homeassistant.service:
        service: light.toggle
        entity_id: light.ledes_cama
```
