### ISSUE TITLE
ESP32 Touch + Deep Sleep not working, fully implemented?

### ISSUE THREAD

**Issue by AndreasBVB** [esphome/issues#3440]
### The problem

Hi all,
New to the project but navigating with some basic C++ understandings.

I am trying to build a project using touch pins to detect moisture, while sending the device into deep sleep as much as possible so that it can be driven by batteries. What I have noticed is: any touch pin reading change, even though well above touch binary sensor thresholds, will wake up the device with a sensor OFF message and wake up reason 2: ESP_SLEEP_WAKEUP_EXT0, Wakeup caused by external signal using RTC_IO.

I checked the ESP32 implementation and found the "touchAttachInterrupt" needs to be called to specify the threshold, for example here:
https://randomnerdtutorials.com/esp32-touch-wake-up-deep-sleep/

I then searched around the entire ESPHome project but didn't find any call to this function. This makes me wonder if touch wake up from deep sleep has been fully implemented. Kindly suggest if I missed something. Thanks you!

### Which version of ESPHome has the issue?

2022.6.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.5

### What platform are you using?

ESP32

### Board

all ESP32 boards

### Example YAML snippet

```yaml
esphome:
  name: abcde-04aabb
  on_boot:
    priority: 900
    then:
      lambda: |-
        id(wake_up_reason) = esp_sleep_get_wakeup_cause();

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: NONE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

deep_sleep:
  run_duration: 10s
  sleep_duration: 3590s
  touch_wakeup: true
  wakeup_pin: T4
  wakeup_pin_mode: KEEP_AWAKE

esp32_touch:
  iir_filter: 10ms
  setup_mode: false

binary_sensor:
  - platform: esp32_touch
    name: esphome-leak
    device_class: moisture
    pin: T4
    threshold: 100

globals:
  - id: wake_up_reason
    type: int
    restore_value: no
    initial_value: '0'
    
sensor:
  - platform: template
    name: "Wake-up Reason"
    accuracy_decimals: 0
    lambda: |-
      return (id(wake_up_reason));

mqtt:
  broker: *****
  username: ******
  password: ******
  birth_message:
   topic: /status
   payload: "Online"
  will_message:
   topic: /status
   payload: "Offline"
```
