### ISSUE TITLE
https://esphome.io/components/sensor/bme280.html example uses wrong address for sensor

### ISSUE THREAD

**Issue by ldhagen** [esphome/issues#3442]
### The problem

Address 0x77 should be 0x76 

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.7.4

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

i2c

### Example YAML snippet

```yaml
sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x77
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
communication with BME280 failed!
```

### Additional information

Lots of folks failing with example address of 77 but some figured out they needed 76.
