### ISSUE TITLE
MCP23017: Input pins show events that are not there

### ISSUE THREAD

**Issue by gsieben** [esphome/issues#3445]
### The problem

I have pins 1-3 programmed as input with pull up:

```
# BUS: I²C 
i2c:
  sda: GPIO21 
  scl: GPIO22
  scan: True
  # frequency: 100kHz
```
...

```
mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20
```
...

```
  # door button
  - platform: gpio
    name: ${acronym} door
    pin:
      mcp23xxx: mcp23017_hub
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 100ms
```
...

These pins show every few seconds an event that can't be there because nothing is connected. I also used a different chip and a different powersoucre. I also tried an external pull-up resistor. All without success. The pins fluctuate all the time. 

Now I can only suspect a software bug. 

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2022.7.5

### What platform are you using?

ESP32

### Board

ESP32-DevKitC

### Component causing the issue

MCP23017

### Example YAML snippet

```yaml
can be seen above
```
