### ISSUE TITLE
Compilation errors on esp8266 - nodemcu after update

### ISSUE THREAD

**Issue by jambuu** [esphome/issues#3447]
### The problem

This board was compiled and flashed a long time ago with esphome and everything is fine and it is even running correctly. Nevertheless, I saw that it was possible to update and when I tried to update this device, I have received tons of compilation errors when it tries to compile main.cpp:

```
src/main.cpp:1:1: error: 'cd' does not name a type
    1 | cd// Auto generated code by esphome
      | ^~
```

I tried cleaning the build files assuming you have changed some core part of the api but the error appears on a clean build although the yaml file is validated successfully.

It seems somewhere in the toolchain, there is a `cd` hardcoded because my main.cpp starts as:
```
// Auto generated code by esphome
// ========== AUTO GENERATED INCLUDE BLOCK BEGIN ===========
#include "esphome.h"
using namespace esphome;
using std::isnan;
```

### Which version of ESPHome has the issue?

v2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.2

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

toolchain-xtensa

### Example YAML snippet

```yaml
esphome:
  name: flur
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "a"
  password: "b"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Flur Fallback Hotspot"
    password: "c"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "c"

ota:
  password: "d"

binary_sensor:
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
      inverted: True
    name: "ScreenPower"
    on_multi_click:
    - timing:
      - ON for at least 1.2s
      then:
        - logger.log: "Click and Hold"
        - homeassistant.event:
            event: esphome.power_screen_hold
            data:
              title: hold
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked"
        - homeassistant.event:
            event: esphome.power_screen_clicked
            data:
              title: single_click

  - platform: gpio
    pin:
      number: D4
      mode: INPUT_PULLUP
      inverted: True
    name: "Garage"
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Garage Short Clicked"
        - homeassistant.event:
            event: esphome.garage_clicked
            data:
              title: single_click
              
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: True
    name: "Temperature"
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Temperature Short Clicked"
        - homeassistant.event:
            event: esphome.temperature
            data:
              title: single_click
              
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    name: "Previous"
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Previous Short Clicked"
        - homeassistant.event:
            event: esphome.previous
            data:
              title: single_click
              
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "Next"
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at least 0.5s
      then:
        - logger.log: "Next Short Clicked"
        - homeassistant.event:
            event: esphome.next_clicked
            data:
              title: single_click
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/flur.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing flur (board: nodemcuv2; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
Compiling /data/flur/.pioenvs/flur/src/main.cpp.o
src/main.cpp:1:1: error: 'cd' does not name a type
    1 | cd// Auto generated code by esphome
      | ^~
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/stl_algobase.h:62,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/char_traits.h:39,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/string:40,
                 from src/esphome/core/component.h:3,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/ext/type_traits.h:162:35: error: 'bool __gnu_cxx::__is_null_pointer' redeclared as different kind of entity
  162 |   __is_null_pointer(std::nullptr_t)
      |                                   ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/ext/type_traits.h:157:5: note: previous declaration 'template<class _Type> bool __gnu_cxx::__is_null_pointer(_Type)'
  157 |     __is_null_pointer(_Type)
      |     ^~~~~~~~~~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/ext/type_traits.h:162:26: error: 'nullptr_t' is not a member of 'std'
  162 |   __is_null_pointer(std::nullptr_t)
      |                          ^~~~~~~~~
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/move.h:57,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/stl_pair.h:59,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/stl_algobase.h:64,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/char_traits.h:39,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/string:40,
                 from src/esphome/core/component.h:3,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/type_traits:200:27: error: 'size_t' has not been declared
  200 |   template <typename _Tp, size_t = sizeof(_Tp)>
      |                           ^~~~~~
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/type_traits:402:26: error: 'std::size_t' has not been declared
  402 |   template<typename _Tp, std::size_t _Size>
      |                          ^~~
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/type_traits:403:25: error: '_Size' was not declared in this scope
  403 |     struct is_array<_Tp[_Size]>
      |                         ^~~~~
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/type_traits:403:31: error: template argument 1 is invalid
  403 |     struct is_array<_Tp[_Size]>
      |                               ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/type_traits:508:42: error: 'nullptr_t' is not a member of 'std'
  508 |     struct __is_null_pointer_helper<std::nullptr_t>
      |                                          ^~~~~~~~~
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/type_traits:508:51: error: template argument 1 is invalid
  508 |     struct __is_null_pointer_helper<std::nullptr_t>
      |                                                   ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/type_traits:984:26: error: 'size_t' has not been declared
  984 |   template<typename _Tp, size_t _Num>
      |                          ^~~~~~
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/type_traits:985:49: error: '_Num' was not declared in this scope
  985 |     struct __is_nt_constructible_impl<true, _Tp[_Num]>
      |                                                 ^~~~
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/type_traits:985:54: error: template argument 2 is invalid
  985 |     struct __is_nt_constructible_impl<true, _Tp[_Num]>
      |                                                      ^
```
