### ISSUE TITLE
Cannot enable i2c

### ISSUE THREAD

**Issue by eatoff8** [esphome/issues#3455]
### The problem

I'm building out a multi sensor, and my final sensor to get set up is a BH1750 light level sensor via i2c.

I have a mmwave radar setup on one uart, and a air quality sensor on another.

If i enable i2c then i am unable to access my ESPhome device for logs or any sensors in HA. I am able to send new firmware, so i can disable it and it comes right back. I have tried disabling the other uarts in config and it will still lock up when I enable i2c. I'm not even enabling the sensor, just the i2c config

I have a separate board with the mmwave radar and the i2c working just fine. Its something about this board with the different setup that is giving issues

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.7.6

### What platform are you using?

ESP32

### Board

Wemos D1 Mini

### Component causing the issue

i2c

### Example YAML snippet

```yaml
substitutions:
  location: Kitchen
  devicename: multisensorkitchen
  LD1115H_INPUT_PIN: GPIO16
  TXPIN: GPIO17
  RXPIN: GPIO21

esphome:
  name: ${devicename}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-D89720"
    password: "pleN4KgVKrVe"

captive_portal:
  
#############################################################################################################################
uart:
  - id: uart_1
    tx_pin: ${TXPIN}
    rx_pin: ${RXPIN}
    baud_rate: 115200
    debug:
      direction: BOTH
      dummy_receiver: true
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);
  - id: uart_2
    rx_pin: GPIO22
    baud_rate: 9600
    
#i2c:
#  sda: 26
#  scl: 18
#  scan: true
#  id: bus_a

switch:
  - platform: safe_mode
    internal: true
    name: use_safe_mode

 
number:
- platform: template
  name: ${devicename}_motion_detection_sensitivity
  id: ${devicename}_motion_detection_sensitivity
  min_value: 1
  max_value: 1500
  initial_value: 120
  optimistic: true
  step: 1
  restore_value: true    
  mode: box
  set_action:
    - uart.write:
        id: uart_1
        data: !lambda
                    int cm = (int)x;
                    std::string cms = "th1=" + to_string(cm) +" \n";
                    return std::vector<unsigned char>(cms.begin(), cms.end());
    - delay: 1s
    - uart.write:
        id: uart_1
        data: "save\n"

- platform: template
  name: ${devicename}_presence_detection_sensitivity
  id: ${devicename}_presence_detection_sensitivity
  min_value: 1
  max_value: 4000
  initial_value: 250
  optimistic: true
  step: 1
  restore_value: true    
  mode: box
  set_action:
    - uart.write:
        id: uart_1
        data: !lambda
                    int cm = (int)x;
                    std::string cms = "th2=" + to_string(cm) +" \n";
                    return std::vector<unsigned char>(cms.begin(), cms.end());
    - delay: 1s
    - uart.write:
        id: uart_1
        data: "save\n"


- platform: template
  name: ${devicename}_delay_detection_time
  id: ${devicename}_delay_detection_time
  min_value: 1
  max_value: 60
  initial_value: 5
  optimistic: true
  step: 1
  restore_value: true    
  mode: box
  set_action:
    - uart.write:
        id: uart_1
        data: !lambda
                    int cm = (int)x;
                    std::string cms = "dtime=" + to_string(cm) +" \n";
                    return std::vector<unsigned char>(cms.begin(), cms.end());
    - delay: 1s
    - uart.write:
        id: uart_1
        data: "save\n"

- platform: template
  name: ${devicename}_gpio_pullup_mov_times
  id: ${devicename}_gpio_pullup_mov_times
  min_value: 1
  max_value: 60
  initial_value: 3
  optimistic: true
  step: 1
  restore_value: true    
  mode: box
  set_action:
    - uart.write:
        id: uart_1
        data: !lambda
                    int cm = (int)x;
                    std::string cms = "mov_sn=" + to_string(cm) +" \n";
                    return std::vector<unsigned char>(cms.begin(), cms.end());
    - delay: 1s
    - uart.write:
        id: uart_1
        data: "save\n"

- platform: template
  name: ${devicename}_gpio_pullup_occ_times
  id: ${devicename}_gpio_pullup_occ_times
  min_value: 1
  max_value: 60
  initial_value: 5
  optimistic: true
  step: 1
  restore_value: true    
  mode: box
  set_action:
    - uart.write:
        id: uart_1
        data: !lambda
                    int cm = (int)x;
                    std::string cms = "occ_sn=" + to_string(cm) +" \n";
                    return std::vector<unsigned char>(cms.begin(), cms.end());
    - delay: 1s
    - uart.write:
        id: uart_1
        data: "save\n"

binary_sensor:
- platform: gpio
  name: occup_${location}
  device_class: occupancy
  pin:
    number: ${LD1115H_INPUT_PIN}
    mode:
      input: true
      pulldown: true

sensor:
#  - platform: bh1750
#    name: ${location}_Illuminance
#    address: 0x23
#    update_interval: 30s
  - platform: pm1006
    uart_id: uart_2
    pm_2_5:
      name: "Kitchen Particulate Matter <2.5µm"

button:
  - platform: restart
    name: Restart $devicename
```

### Anything in the logs that might be useful for us?

```txt
OTA successful, then cannot connect to logs when updating
```
