### ISSUE TITLE
light.addressable_set for neopixelbus ignores default_transition_time

### ISSUE THREAD

**Issue by y8s** [esphome/issues#3456]
### The problem

I'm using a neopixel strip of 8 LEDs and controlling them over MQTT.
I am able to control them just fine individually using `range_from:` and `range_to:` and their color percents.

What doesn't work is having the color change fade slower than immediately. when using `light.addressable_set`. I currently have `default_transition_time` set to 20 seconds.

It DOES work with the regular light commands like `light.turn_on` or sending an MQTT command to the light command topic, but unfortunately that doesn't let me set them individually (that I know of--I'm relatively new to ESPHome)

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

light / neopixelbus / light.addressable_set

### Example YAML snippet

```yaml
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D2
    num_leds: 8
    name: 'Coffee Status LED'
    id: statusled
    restore_mode: RESTORE_AND_OFF
    default_transition_length: 20s
    
 
mqtt:
  broker: 192.168.1.255
  client_id: esphome_pulsecounter
  on_message:
    - topic: "coffee/cmnd"
      then:
        # - light.turn_on:
            # id: statusled
    - topic: "coffee/cmnd"
      payload: '8'
      then:
        - light.addressable_set:
            id: statusled
            range_from: 0
            range_to: 7
            red: 0
            blue: 0
            green: 100%
            color_brightness: 50%
        - logger.log: Coffee LED set to 8
          
    - topic: "coffee/cmnd"
      payload: '7'
      then:
        - light.addressable_set:
            id: statusled
            range_from: 7
            range_to: 7
            red: 0%
            green: 0%
            blue: 0%
           
        - light.addressable_set:
            id: statusled
            range_from: 0
            range_to: 6
            red: 10%
            green: 95%
            blue: 0%
            color_brightness: 50%
```

### Anything in the logs that might be useful for us?

#sending mqtt msg to coffee/cmnd with payload 8
```
[13:37:40][D][main:551]: Coffee LED set to 8               
```
#sending mqtt msg to coffee/light/coffee_status_led/command with payload {"state":"OFF"}
```
[13:37:53][D][light:035]: 'Coffee Status LED' Setting:     
[13:37:53][D][light:084]:   Transition length: 20.0s
```
#sending mqtt msg to coffee/light/coffee_status_led/command with payload {"state":"ON"}
```
[13:37:58][D][light:035]: 'Coffee Status LED' Setting:
[13:37:58][D][light:046]:   State: ON
[13:37:58][D][light:084]:   Transition length: 20.0s
```
#sending mqtt msg to coffee/cmnd with payload 8
```
[13:38:11][D][main:551]: Coffee LED set to 8               
```
