### ISSUE TITLE
BSSID & Channel settings ignored for hidden networks

### ISSUE THREAD

**Issue by Ulrar** [esphome/issues#3457]
### The problem

Hi,

I've been trying to force my ESP32s to connect to a hidden network on a specific access point. In the "normal" settings the doc says to use fast connect but that it may choose the wrong AP, and indeed it does. There's no bssid or channel fields there.
So I've tried instead using the `networks` block to define only one network, but add the bssid and channel fields that are supported there.

Unfortunately neither bssid nor channel seem to do anything when hidden is true.
If that's intended I think the doc could be a tad clearer on that, but I'm hoping that could be addressed to get these settings working with hidden networks, it would be a way to prevent connection to the wrong AP.

I've made sure the bssid letters are all uppercase.
I've tried setting only bssid or only channel, or both like here and same behavior.

Thanks !

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

doit devkit v1

### Component causing the issue

wifi

### Example YAML snippet

```yaml
wifi:
  networks:
    - ssid: !secret wifi_iot_ssid
      password: !secret wifi_iot_pass
      hidden: !secret wifi_iot_fast
      bssid: !secret U6_LR_2.4ghz_wifi_iot_mac
      channel: 1
      manual_ip:
        [...]
```

**Comment by ssieb** [comment]
```yaml
wifi:
  fast_connect: true
  networks:
    - ssid: !secret wifi_iot_ssid
      password: !secret wifi_iot_pass
      bssid: !secret U6_LR_2.4ghz_wifi_iot_mac
      channel: 1
      manual_ip:
```
If you think there's a way to make the docs clearer, then feel free to make a PR.
