### ISSUE TITLE
Updating a Device Wireless is not changing the runtime programm

### ISSUE THREAD

**Issue by majoto85** [esphome/issues#3458]
### The problem

Hello,

If I'm changing some values and updating the device wireless, nothing is changing. Updating manually with ESP-Home-Flasher works.

For example. I have a light wich turns on after booting. I changed color to check if the new version is working and it's still the old color.

Thank you and great work,
Tobias 

### Which version of ESPHome has the issue?

2022.06.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.7.5

### What platform are you using?

ESP32

### Board

LaskaKit ESP-VINDRIKTNING

### Example YAML snippet

```yaml
Before Updating Wireless (LED is Blue):

  on_boot:
    then:
      - light.addressable_set:
          id: status
          range_from: 2
          range_to: 2
          color_brightness: 0.2
          red: 0%
          green: 0%
          blue: 100%

After Updating Wireless (LED is still Blue):

  on_boot:
    then:
      - light.addressable_set:
          id: status
          range_from: 2
          range_to: 2
          color_brightness: 0.2
          red: 0%
          green: 100%
          blue: 0%
```
