### ISSUE TITLE
ALWAYS_ON option in GPIO output goes down for over 2ms during boot

### ISSUE THREAD

**Issue by mariuszchrobak** [esphome/issues#3461]
### The problem

I have few temperature / humidity sensors around the home, embedded in walls. One of them I decided to change temperature offset, which needed SW update (because I learned to not update if not needed...) from 2021.9 to 2022.6. After that ESP is not online - LED on ESP is blinking rapidly, maybe 10Hz. I tried to reset power few times, didn't help. 

For debugging I tried to connect it to UART to read debug data (thru Arduino board, and Arduino terminal). That didn't help because... ESP started to work normally. LED stopped rapidly blinking and it showed up in HA as available.
I thought that might be related to Logger and/or pin impedance (although it was working fine for over a year!) so first I tried to just connect RX and TX pins to pins of Arduino - no change, but then click to open COM terminal - magically started working.
Next step - tried to disable Logger in YAML - didn't help, even now connecting terminal does not help at all. ESP is completely bricked flashing like crazy.
Those sensors are small, no possible to just connect and flash wired... 

Schematic:
![Screenshot 2022-07-23 094400](https://user-images.githubusercontent.com/9673371/180607701-6e14d018-7f19-4483-a95a-0500941a4225.png)

### Which version of ESPHome has the issue?

v2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.7.0

### What platform are you using?

ESP8266

### Board

ESP-01s

### Component causing the issue

No idea, but using i2c, sht3xd

### Example YAML snippet

```yaml
esphome:
  name: office_sensor
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office Sensor Fallback Hotspot"
    password: ""

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  sda: GPIO2
  scl: GPIO0
  scan: True
  id: bus_a

sensor:
  - platform: sht3xd
    temperature:
      name: "Office SHT31 Temperature"
      filters:
      - lambda: return x;
      - median:
          window_size: 9
          send_every: 3
          send_first_at: 3
    humidity:
      name: "Office SHT31 Humidity"
      filters:
      - lambda: return x;
      - median:
          window_size: 9
          send_every: 3
          send_first_at: 3
    address: 0x44
    update_interval: 5s
    
switch:
  - platform: gpio
    pin: GPIO3
    name: "office_sensor HW Reset"
    restore_mode: ALWAYS_ON
```

### Anything in the logs that might be useful for us?

```txt
Either can't read logs at all, or it works fine showing full operation no errors.
```
