### ISSUE TITLE
ESPHome device webpage not updated when accessing through reverse-proxy

### ISSUE THREAD

**Issue by RoboMagus** [esphome/issues#3462]
### The problem

I'm trying to access my ESPHome devices from outside my local network (I have to deal with multiple separate networks).
I have configured a reverse proxy to redirect trafic as such: `esphome.my.domain/devices/plug1` is redirected to `192.168.4.x` for device 'plug1'.

However, when looking into the JS that's loaded on the webpage, everything that is dynamically loaded comes from a hardcoded `<address>/events` without taking a potential path prefix into account. As such it cannot deal with proxies. 😢 

### Which version of ESPHome has the issue?

2022.7.0-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/a

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

web_server

### Example YAML snippet

```yaml
esphome:
  name: plug1

esp8266:
  board: d1_mini
  restore_from_flash: true

wifi:
  id: wifiComponent
  ssid: !secret WiFi_ssid
  password: !secret WiFi_password
  fast_connect: on

ota:
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
```

### Anything in the logs that might be useful for us?

```txt
Nope. Its not reaching the ESP device at all.
```
