### ISSUE TITLE
Remote Transmitter Crash WT32-ETH01

### ISSUE THREAD

**Issue by DaAwesomeP** [esphome/issues#3463]
### The problem

Remote transmitter causes a crash on the WTH32-ETH01. The ESP is very stable and works fine up until the template switch is turned on.

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.7.6

### What platform are you using?

ESP32

### Board

WTH32-ETH01 V1.4

### Component causing the issue

remote_transmitter

### Example YAML snippet

```yaml
esphome:
  name: my-esp

esp32:
  board: esp-wrover-kit  # actually WT32-ETH01 V1.4, some GPIO mappings wrong
  framework:
    type: arduino

ethernet:
  domain: .my-domain  # REDACTED
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/New_York"
    servers:
     - 1.2.3.4  # REDACTED

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED

ota:
  password: "REDACTED"

binary_sensor:
  - platform: status
    name: "my-esp Status"

sensor:
  - platform: uptime
    name: "my-esp Uptime"

switch:
  - platform: restart
    name: "Restart my-esp"
  - platform: template
    name: Family Room Matrix A 1
    turn_on_action:
      - remote_transmitter.transmit_raw:
          carrier_frequency: 38kHz
          code: [10, -12252, 10, -1102, 10, -1102, 10, -1102, 10, -1102, 10, -1102, 10, -1102, 10, -1102, 10, -1102, 10, -2224, 10, -2224, 10, -2224, 10, -2224, 10, -2224, 10, -2224, 10, -2224, 10, -2224, 10, -2224, 10, -2224, 10, -1102, 10, -2224, 10, -2224, 10, -1102, 10, -1102, 10, -1102, 10, -1102, 10, -1102, 10, -2224, 10, -1102, 10, -1102, 10, -2224, 10, -2224, 10, -2224, 10, -40198, 10, -12252]

remote_transmitter:
  pin: GPIO19
  carrier_duty_percent: 50%
```
