### ISSUE TITLE
MQTT Publish trouble in Climate  (FAn_Mode) component

### ISSUE THREAD

**Issue by sincereman** [esphome/issues#3467]
### The problem

There is a problem in climate component is connected with publishing changes to mqtt topics.

There is nothing publishing in mqtt when value fan_mode was changed.  In a document https://esphome.io/components/climate/index.html described, that 

fan_mode_state_topic (Optional, string): The topic to publish fan mode changes to.
fan_mode_command_topic (Optional, string): The topic to receive fan mode commands on.

The command topic /command work well for fan_mode , the devices get a new value and aplly it but /state topic wasnt updated. The topic /state kept to  be empty.

In the same time  the modes that described in the part as
custom_fan_modes:
- MUTE
- TURBO
succesfully published in the topic /state in fan_mode

In other components of climate, except
 supported_presets: 
- ECO
- BOOST
- SLEEP
custom_presets:
- FREEZE_PROTECTION

that described in a similar issue https://github.com/esphome/issues/issues/3454, mqtt publishing works well

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

nodemcu v3

### Component causing the issue

https://esphome.io/components/climate/index.html

### Example YAML snippet

```yaml
climate:
  - platform: aux_ac
    name: AC_Energolux_Bedroom
    id: aux_id
    uart_id: ac_uart_bus
    period: 7s
    show_action: true
    display_inverted: false
    indoor_temperature:
      name: Energolux Bedroom AC Indoor Temperature
      id: ac_bedroom_indoor_temp
      internal: true
    display_state:
      name: Energolux Bedroom AC Display State
      id: ac_bedroom_display_state
      internal: false    
    visual:
      min_temperature: 16
      max_temperature: 32
      temperature_step: 0.5
    supported_modes:
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    custom_fan_modes:
      - MUTE
      - TURBO
    supported_presets:
      - SLEEP
    custom_presets:
      - CLEAN
      - FEEL
      - HEALTH
      - ANTIFUNGUS
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH
```
