### ISSUE TITLE
`on_press` > `while` not setting brightness until release

### ISSUE THREAD

**Issue by Joshfindit** [esphome/issues#347]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Ubuntu server, esphome installed via pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

`esp32dev`

**Affected component:**

https://esphome.io/components/binary_sensor/index.html?highlight=on_press

**Description of problem:**

`on_click` works to toggle the light and `on_press` works to dim the light, but the light is not updated until `on_press` is released.

Sequence of steps:
1. Monitor light in homeassistant
2. Press and hold the sensor
3. Light decreases slightly (presumably by 0.05) then stay at that brightness
4. Homeassistant shows the dimmer bar decreasing at the correct rate
5. About every second the lights flicker: going back up to previous brightness then dimming slightly by the same amount as step 3
6. Homeassistant still shows the dimmer bar decreasing at the correct rate
7. Release the sensor
8. Light changes to the 'correct' brightness (that is: the one shown in homeassistant)

**Problem-relevant YAML-configuration entries:**
```yaml
esp32_touch:
  setup_mode: false

binary_sensor:
  - platform: esp32_touch
    name: "GPIO27 (Touch)"
    id: mainbutton
    pin: GPIO27
    threshold: 500
    on_click:
      then:
        - light.toggle: mainlight
    on_press:
      - while:
          condition:
            binary_sensor.is_on: mainbutton
          then:
          - light.turn_on:
              id: mainlight
              brightness: !lambda |-
                float brightness;
                id(mainlight).current_values_as_brightness(&brightness);
                return brightness - 0.05f;
          - delay: 0.05s
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
Related to https://github.com/esphome/esphome/issues/111
