### ISSUE TITLE
mcp23x17 compile error

### ISSUE THREAD

**Issue by jjk0giap** [esphome/issues#3471]
### The problem

linking error while compile esphome with MCP23017 i2c expander.

### Which version of ESPHome has the issue?

2022.6.2, 2022.7.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.7.3

### What platform are you using?

ESP32

### Board

esp32-poe

### Component causing the issue

mcp23017

### Example YAML snippet

```yaml
i2c:
  scan: false
  frequency: 400kHz

mcp23017:
  - id: 'mcp23017_0'
    address: 0x20
  - id: 'mcp23017_1'
    address: 0x21
  - id: 'mcp23017_2'
    address: 0x22
  - id: 'mcp23017_3'
    address: 0x23
output:
  - platform: gpio
    id: ssr1_1
    pin:
      mcp23xxx: mcp23017_0
      number: 0
      mode: OUTPUT
      inverted: True
```

### Anything in the logs that might be useful for us?

```txt
Linking .pioenvs/main-lights-esp32/firmware.elf
.pioenvs/main-lights-esp32/src/esphome/components/mcp23x17_base/mcp23x17_base.cpp.o:(.rodata._ZTVN7esphome13mcp23x17_base12MCP23X17BaseE[vtable for esphome::mcp23x17_base::MCP23X17Base]+0x48): undefined reference to `esphome::mcp23xxx_base::MCP23XXXBase::read_reg(unsigned char, unsigned char*)'
.pioenvs/main-lights-esp32/src/esphome/components/mcp23x17_base/mcp23x17_base.cpp.o:(.rodata._ZTVN7esphome13mcp23x17_base12MCP23X17BaseE[vtable for esphome::mcp23x17_base::MCP23X17Base]+0x4c): undefined reference to `esphome::mcp23xxx_base::MCP23XXXBase::write_reg(unsigned char, unsigned char)'
collect2: error: ld returned 1 exit status
*** [.pioenvs/main-lights-esp32/firmware.elf] Error 1
```

### Additional information

worked fine on 2021.10.2 pip install
