### ISSUE TITLE
Unknown value 'total' for state_class attribute

### ISSUE THREAD

**Issue by bokub** [esphome/issues#3478]
### The problem

When compiling a firmware using the Docker version of ESPHome, I have the following error:

![2022-08-02_10-12](https://user-images.githubusercontent.com/17952318/182326909-0c730d93-131c-4b2d-b7d1-c78bced0d3a8.png)

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

No Home assistant

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

sensor I guess

### Example YAML snippet

```yaml
# Setup teleinfo, update value every 60s
teleinfo:
  id: myteleinfo
  update_interval: 60s
  historical_mode: true

sensor:
  # Linky BASE value
  - platform: teleinfo
    tag_name: "BASE"
    name: "Linky Index"
    teleinfo_id: myteleinfo
    state_class: "total"
    device_class: "energy"
    unit_of_measurement: "Wh"
```

### Anything in the logs that might be useful for us?

```txt
Unknown value 'total', valid options are '', 'measurement', 'total_increasing'.
```

### Additional information

Might be related to #2881
