### ISSUE TITLE
Web server doesn't support Bang-Bang Climate

### ISSUE THREAD

**Issue by anatoly-savchenkov** [esphome/issues#3479]
### The problem

Handling of "two_point_target_temperature" devices is broken in the web server. First of all settings are rendered improperly: target_temperature_high/low are missing, state is missing. Secondly, changing of the target temperature doesn't work as there is no `target_temperature` parameter but `target_temperature_high / target_temperature_low` two parameters.

The problem consists of 2 issues:
- improper code in the web_server.cpp. climate_json(), lines
```    if (traits.get_supports_two_point_target_temperature()) {
      root["current_temperature_low"] = obj->target_temperature_low;
      root["current_temperature_high"] = obj->target_temperature_low;
    } else {
```
should be something like these (also using of target temperature as Climate state is very questionable. I would use Action as State instead)
```    if (traits.get_supports_two_point_target_temperature()) {
      root["target_temperature_low"] = obj->target_temperature_low;
      root["target_temperature_high"] = obj->target_temperature_high;
      root["state"] = (obj->target_temperature_high + obj->target_temperature_low) / 2.0f;
    } else {
```
- lack of handling of target_temperature_high/low in the v2/esp-entity-table.ts file. Something similar to the code below should appear for target_temperature_high/low  producing 2 sliders.
```        <div>
          ${this.range(
            entity,
            "set",
            "target_temperature",
            entity.value,
            entity.min_temp,
            entity.max_temp,
            entity.step,
            0
          )}
        </div>
```

### Which version of ESPHome has the issue?

2022.06.02

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

Custom

### Component causing the issue

web_server

### Example YAML snippet

```yaml
web_server:
  port: 80
  version: 2

climate:
  - platform: bang_bang
    name: ${friendly_devicename} Heating Controller
    sensor: ${temperature_sensor}
    default_target_temperature_low: ${target_temperture_low} °C
    default_target_temperature_high: ${target_temperture_high} °C
    id: lytko_therm
    visual:
      min_temperature: ${min_temperature} °C
      max_temperature: ${max_temperature} °C
      temperature_step: ${temperature_step} °C

    heat_action:
      - switch.turn_on: heater

    idle_action:
      - switch.turn_off: heater
```

### Anything in the logs that might be useful for us?

```txt
[13:01:19][D][climate:010]: 'Lytko Heating Controller' - Setting
[13:01:19][W][climate:096]:   Cannot set target temperature for climate device with two-point target temperature!
```
