### ISSUE TITLE
error: 'VSPI' was not declared in this scope (also for SPI integration and the ESP32-S3 chip)

### ISSUE THREAD

**Issue by IgnacioHR** [esphome/issues#3483]
### The problem

Trying to use the SPI integration as follows 
```
spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11
  miso_pin: GPIO13
```
using a ESP32-S3 chip results in a compilation error:
```
Compiling .pioenvs/esphome-nevera/src/esphome/components/spi/spi.cpp.o
src/esphome/components/spi/spi.cpp: In member function 'virtual void esphome::spi::SPIComponent::setup()':
src/esphome/components/spi/spi.cpp:79:36: error: 'VSPI' was not declared in this scope
       this->hw_spi_ = new SPIClass(VSPI);  // NOLINT(cppcoreguidelines-owning-memory)
                                    ^~~~
src/esphome/components/spi/spi.cpp:79:36: note: suggested alternative: 'SPI'
       this->hw_spi_ = new SPIClass(VSPI);  // NOLINT(cppcoreguidelines-owning-memory)
                                    ^~~~
                                    SPI
```

### Which version of ESPHome has the issue?

v2022.7.0-dev 

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.8.1

### What platform are you using?

ESP32

### Board

ESP32S3

### Component causing the issue

spi

### Example YAML snippet

```yaml
esphome:
  name: esphome-nevera

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0
  variant: esp32s3

spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11
  miso_pin: GPIO13
```

### Additional information

Tried to add "includes: ..." to esphome to do

#define VSPI 2

but did not work. There might be something else required.

Link to the [ESP32S3 datasheet](https://espressif.com/sites/default/files/documentation/esp32-s3_datasheet_en.pdf)

Section 3.5.2 about SPI, the device contains 4 SPI busses on which only SPI2 and SPI3 are available externally. It looks like the yaml requires a new entry for us to select which bus to use (either SPI2 or SPI3 as te other 2 makes no sense)
