### ISSUE TITLE
HA doesn't show 'open' button for a lock

### ISSUE THREAD

**Issue by crixionz** [esphome/issues#3495]
### The problem

HA doesn't show an 'open' button for an ESPHome lock that *does* have an `open_action:` defined. Only 'lock' and 'unlock' are displayed.
If I understand [the HA docs](https://developers.home-assistant.io/docs/core/entity/lock/) correctly, the `SUPPORT_OPEN` flag might not be set, so HA acts accordingly. The lock in HA also has the attribute `supported_features: 1`. 
When viewing via the `web_server:` page, the lock has all three buttons (lock, unlock, open) and their respective actions are executed successfully.

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.8.4

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

lock

### Example YAML snippet

```yaml
lock:
  - platform: template
    name: "Nuki"
    id: templatenuki
    lambda: "return id(mynukilock).state; "
    open_action:
      - if:
          condition:
            binary_sensor.is_on: nukicontrolsenabled
          then:
            # - logger.log: "Nuki should open hehe"
            - lock.open: mynukilock
          else:
            - logger.log: "Nuki didn't open because controls are disabled!"
    unlock_action:
      - lock.unlock: mynukilock
    lock_action:
      - lock.lock: mynukilock
```
