### ISSUE TITLE
Wake on lan compiling error

### ISSUE THREAD

**Issue by ferdyvi** [esphome/issues#3498]
### The problem

Compiling yaml file failed with the example button code about wake on lan functionality:
button:
  - platform: wake_on_lan
    name: "Start the Server"
    target_mac_address: E9:48:B8:CA:58:A1

Error:
  Platform not found: 'button.wake_on_lan'.
  platform: wake_on_lan
  name: Start the Server
  target_mac_address: E9:48:B8:CA:58:A1

### Which version of ESPHome has the issue?

2022.6.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.8.5

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

Wake on lan

### Example YAML snippet

```yaml
# Example configuration entry
button:
  - platform: wake_on_lan
    name: "Start the Server"
    target_mac_address: E9:48:B8:CA:58:A1
```

### Anything in the logs that might be useful for us?

```txt
Platform not found: 'button.wake_on_lan'.
  platform: wake_on_lan
  name: Start the Server
  target_mac_address: E9:48:B8:CA:58:A1
```

### Additional information

configuration entry from online documentation
https://www.esphome.io/components/button/wake_on_lan.html
