### ISSUE TITLE
Sprinkler Controller Example:  initial_value cannot be used with lambda.

### ISSUE THREAD

**Issue by rb2k** [esphome/issues#3500]
### The problem

https://esphome.io/components/sprinkler.html#additional-tricks lists a number example that looks like this:

```
# Example configuration to set multiplier via number
number:
  - platform: template
    id: sprinkler_ctrlr_multiplier
    name: "Sprinkler Controller Multiplier"
    min_value: 0.1
    max_value: 10.0
    step: 0.1
    initial_value: 1.0
    lambda: "return id(lawn_sprinkler_ctrlr).multiplier();"
    set_action:
      - sprinkler.set_multiplier:
          id: lawn_sprinkler_ctrlr
          multiplier: !lambda 'return x;'
```

Trying to use this in esphome will result in:

```
  initial_value cannot be used with lambda.
```

Looking at https://esphome.io/components/number/template.html , that seems to be correct. The quote

> initial_value (Optional, float): The value to set the state to on setup if not restored with restore_value. Cannot be used with lambda. Defaults to min_value.

### Which version of ESPHome has the issue?

2022.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.8.5

### What platform are you using?

ESP8266

### Board

sonoff 4ch pro

**Comment by kbx81** [comment]
Oh no! That's what I get for trying to improve an example at the [last minute](https://github.com/esphome/esphome-docs/pull/1471/commits/78dd863ecb0a2d1348799c3bcd070e18c3e191af). 😆
Thanks for calling this out -- fix incoming...

**Comment by rb2k** [comment]
Ha, no problem :)

Do you have any ideas what the most elegant way is to set this number?
Otherwise it'll default to the minimum after startup.

So far used on_boot with a call to ```sprinkler.set_multiplier()```, just wondering if there's a more straight forward way to do things.

**Comment by kbx81** [comment]
Internal to the sprinkler controller, the multiplier value defaults to a value of `1` on start-up. You don't need to set it with `on_boot` unless you are looking for some specific behavior.

If you use the state lambda as shown in the example, the `number` component will reflect the value returned by the sprinkler controller's `multiplier()` accessor method, so you should see it default to 1 there, as well. Are you wanting it to assume a default value other than `1`?

**Comment by kbx81** [comment]
Now you've got me wondering if we need a `default_multipler_value` and possibly even `multiplier_min` and `multiplier_max` parameters for sanity checking. 😄 Perhaps something for v2...

**Comment by rb2k** [comment]
> Internal to the sprinkler controller, the multiplier value defaults to a value of `1` on start-up (this is not the smallest possible value). You don't need to set it with `on_boot` unless you are looking for some specific behavior.
> 
> If you use the state lambda as shown in the example, the `number` component will reflect the value returned by the sprinkler controller's `multiplier()` accessor method, so you should see it default to 1 there, as well. Are you wanting it to assume a default value other than `1`?

Ah yes. I didn't feel smart enough to remember what the default run time is and what the multiplier is set to, so I just did a default run time of 60 seconds and then the 'multiplier' will just tell me how many minutes each zone will run.

Ends up looking like this
<img width="492" alt="Screen Shot 2022-08-17 at 12 54 13 PM" src="https://user-images.githubusercontent.com/9519/185198023-85d37bb1-96ad-4442-80a4-f1afced99ed7.png">

I guess I could have just left the multiplier alone at 1 and somehow tried to set the duration for all the valves separately, but that seemed more complicated :)

**Comment by mitchelloharawild** [comment]
Regarding run durations, is there a neat way to restore set duration values on boot? Perhaps an option like `restore_mode` for the `sprinkler` component?
I'd like to set the run duration via a `number` component and then have the sprinkler component restore the set value on boot.

My relevant sprinkler input is:
```yaml
sprinkler:
  - id: irrigation_ctrlr
    main_switch: "Irrigation"
    auto_advance_switch: "Irrigation Auto Advance"
    valve_overlap: 5s
    valves:
      - valve_switch: "Zone 1"
        enable_switch: "Enable zone 1"
        run_duration: 60s
        valve_switch_id: zone1_relay
```


My number input is:

```yaml
number:
  - platform: template
    id: zone1_minutes
    min_value: 0
    step: 1
    max_value: 15
    name: "Zone 1 minutes"
    icon: "mdi:watering-can"
    unit_of_measurement: minutes
    update_interval: never
    entity_category: config
    mode: slider
    lambda: "return id(irrigation_ctrlr).valve_run_duration(0)/60;"
    set_action:
      - sprinkler.set_valve_run_duration:
          id: irrigation_ctrlr
          valve_number: 0
          run_duration: !lambda 'return x*60;'
      - component.update: zone1_minutes
```
