### ISSUE TITLE
on_value_range doesn't trigger when the value is higher during ESP startup

### ISSUE THREAD

**Issue by svh1985** [esphome/issues#3502]
### The problem

Hi,

I added some code to monitor the set max_temp value against the internal temperature sensor of a Shelly device.

But what I found is that if I set the max_temp to 70.0, but the device is anything higher than 70.0 during startup, the message is never triggered. 

The message is only triggered once the value falls below 70.0 and then goes over 70.0 again.

### Which version of ESPHome has the issue?

v2022.8.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
sensor:
  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${device_name} temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - logger.log: "Temperature exceeded ${max_temp}°C"
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${device_name}
              data_template:
                message: Temperature exceeded ${max_temp}°C
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0
```
