### ISSUE TITLE
Incorrect schema checking for the esp8266 block

### ISSUE THREAD

**Issue by ivlis** [esphome/issues#3503]
### The problem

Config:

```
esphome:
  name: ${device_id}
  build_path: ./.build/${device_id}

esp8266:
  board: esp01_1m
  esp8266_restore_from_flash: true
  early_pin_init: false
  framework:
    version: recommended
```

results in a very obscure error:
```
  File "/esphome/esphome/core/init.py", line 587, in target_platform
    return self.data[KEY_CORE][KEY_TARGET_PLATFORM]
KeyError: 'target_platform'
```

The expected behavior is to return an error as the key `esp8266_restore_from_flash` is not allowed, the correct key is `restore_from_flash`

### Which version of ESPHome has the issue?

2022.8.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

N/A

### Component causing the issue

esp8266
