### ISSUE TITLE
SM2135 insufficient current to light-up the leds

### ISSUE THREAD

**Issue by mvturnho** [esphome/issues#3506]
### The problem

I use a Spectrum smart lightbulb (WOJ14412) with the sm2135 led-driver (I have actualy 6 of them)
To make it work I have to edit the sources for the sm2135.

https://github.com/esphome/esphome/blob/dev/esphome/components/sm2135/sm2135.cpp
line 34: 
`static const uint8_t SM2135_CURRENT = (SM2135_20MA << 4) | SM2135_10MA;`

into 
`static const uint8_t SM2135_CURRENT = (SM2135_20MA << 4) | SM2135_20MA;`

I read another [issue ](https://github.com/esphome/issues/issues/2546) where was sugested to make a custom component.
but that is quite a hassle for such a simple thing. I sugest we add a config parameter to make this configurable and set the defaults to safe values. 
There is also a[ PR that got stale](https://github.com/esphome/esphome/pull/3621) but we could solve the issue with this driver in different bulbs.

### Which version of ESPHome has the issue?

latest version: ESPHome version 2022.8.0 compiled on Aug 20 2022, 14:29:13

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

sm2135

### Example YAML snippet

```yaml
substitutions:
  devicename: rgbulb5
  upper_devicename: RGBULB5

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    ap_timeout: 30s

api:
  password: 'secret'
  reboot_timeout: 0s

logger:
   level: DEBUG

ota:
  safe_mode: True
  password: !secret ota_password
  port: 3286
  

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${upper_devicename} IP

sm2135:
  data_pin: GPIO12
  clock_pin: GPIO14
  
output:
  - platform: sm2135
    id: output_green
    channel: 0
  - platform: sm2135
    id: output_blue
    channel: 1
  - platform: sm2135
    id: output_red
    channel: 2
  - platform: sm2135
    id: output_white
    channel: 3
  - platform: sm2135
    id: output_warmwhite
    channel: 4

light:
  - platform: rgbww
    name: ${upper_devicename}
    default_transition_length: 1s
    cold_white: output_white
    warm_white: output_warmwhite
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    color_interlock: true
    # Ensure the light turns on by default if the physical switch is actuated.
    restore_mode: ALWAYS_ON
```
