### ISSUE TITLE
PR #3561 yaml parser

### ISSUE THREAD

**Issue by MoneybaggMario** [esphome/issues#3507]
### The problem

Yaml parser is throwing an error in the line: id(ph_ezo).set_calibration_point_mid(7.00);.

It's saying because of the dot in 7.00 it's confusing the float value for a home assistant entity.

I solved this by just using the number 7 instead of 7.00.
![Screenshot (4)](https://user-images.githubusercontent.com/90293338/185770967-9e894377-ea47-45d5-9292-955690ca9b21.png)

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.8.6

### What platform are you using?

ESP32

### Board

esp wroom-32 dev board 30p

### Component causing the issue

ezo ph

### Example YAML snippet

```yaml
button:
- platform: template
  name: "PH 7 Calibrate" 
  id: ph_calibrate_7
  on_press:
   then: 
     - lambda: id(ph_ezo).set_calibration_point_mid(7.00); #solved by removing the .00
```
