### ISSUE TITLE
Upgrading from 2022.6.3 to 2022.8.0 causes WDT resets with AC dimmer

### ISSUE THREAD

**Issue by Azimath** [esphome/issues#3509]
### The problem

After upgrading ESPHome, my ac_dimmer based lights stopped working. The serial logs report that shortly after the brightness is set from home assistant, the ESP locks up and gets stuck in a boot loop. 
If I downgrade to 2022.6.3, I can send as many brightness as I want and the ESP remains functional. If I set logger to VERY_VERBOSE, the ESP seems to be stable. 
I've tested this on both an actual lamp and on a bare module with a waveform generator produced zero cross input. 
Replacing the ac dimmer with PWM on the test setup is stable, but obviously won't work for the real lamp.
The logs give no stack trace, only the WDT reset boot message.

### Which version of ESPHome has the issue?

2022.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.8.3

### What platform are you using?

ESP8266

### Board

ESP-12E

### Component causing the issue

ac_dimmer

### Example YAML snippet

```yaml
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 
      number: GPIO13
      inverted: true
    zero_cross_pin: GPIO12
    min_power: 0.2
    zero_means_zero: true
    
light:
  - platform: monochromatic
    output: dimmer1
    name: "test lamp"
    id: lamp
```

### Anything in the logs that might be useful for us?

```txt
[D][light:035]: 'test lamp' Setting:
[D][light:050]:   Brightness: 85%
[D][light:084]:   Transition length: 1.0s
[D][light:035]: 'test lamp' Setting:
[D][light:050]:   Brightness: 31%
[D][light:084]:   Transition length: 1.0s

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 3460, room 16
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4
tail 4
chksum 0xc9
csum 0xc9
v0007d8c0
~ld
[I][logger:243]: Log initialized
```
