### ISSUE TITLE
Installing platformio/tool-scons @ ~4.40200.0 fail

### ISSUE THREAD

**Issue by Ih8rain2** [esphome/issues#3511]
### The problem

It seems that after the latest update it failes to compile:
```
INFO Reading configuration /config/esphome/cam01.yaml...
WARNING GPIO0 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing cam01 (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 3.3.2)
--------------------------------------------------------------------------------
Tool Manager: Installing platformio/tool-scons @ ~4.40200.0
Error: Could not find the package with 'platformio/tool-scons @ ~4.40200.0' requirements for your system 'linux_aarch64'
```
I am using the latest update as add-on in HomeAssistant:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ESPHome
 ESPHome add-on for intelligently managing all your ESP8266/ESP32 devices
-----------------------------------------------------------
 Add-on version: 2022.8.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.8.6
 Home Assistant Supervisor: 2022.08.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] 30-dirs.sh: executing... 
[cont-init.d] 30-dirs.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:18:54] INFO: Waiting for dashboard to come up...
[16:18:54] INFO: Starting ESPHome dashboard...
2022-08-20 16:18:55,952 INFO Starting dashboard web server on unix socket /var/run/esphome.sock and configuration dir /config/esphome...
[16:18:56] INFO: Starting NGINX...
```

### Which version of ESPHome has the issue?

2022.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.8.6

### What platform are you using?

ESP32

### Board

esp32-cam

### Component causing the issue

Camera

### Example YAML snippet

```yaml
# Author by airijia.com
# ESP32-CAM
# Lovelace camera card https://github.com/custom-cards/camera-card
# Video tutorial https://youtu.be/-towjof_ixU
substitutions:
  # Modify variables based on your settings
  hostname: 'cam01' # device name
  ssid: 'xxxx'
  password: 'xxx'
esphome:
  name: $hostname
  platform: ESP32
  board: esp32dev
wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
api:
  reboot_timeout: 0s
ota:
logger:

# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
#  resolution: 1600x1200
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  vertical_flip: true

  
  # camera name
  name: Cam01
  # ... Frame Settings

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: $hostname light
```

### Anything in the logs that might be useful for us?

```txt
see above
```

### Additional information

Previously no issues compiling and uploading. Since latest update compiling issue failing to load a tool
