### ISSUE TITLE
.local domains are not accessible

### ISSUE THREAD

**Issue by ArnyminerZ** [esphome/issues#3517]
### The problem

My current ESPHome installation on a Raspberry Pi 4 doesn't manage to find the devices on the network.

Trying to access the device's logs on ESPHome Dashboard clearly shows there's an issue finding the device:
```
INFO Reading configuration config/test.yaml...
INFO Starting log output from test.local using esphome API
WARNING Can't connect to ESPHome API for test.local: Error resolving IP address: [Errno -2] Name or service not known
INFO Trying to reconnect to test.local in the background
```
Concerned about a misconfiguration of the docker container, which is ran over docker-compose, hereby my `docker-compose.yml`:
```yaml
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    user: 0:0
    environment:
      - HOME="/"
    ports:
      - "192.168.1.22:6052:6052"
      - "192.168.1.22:6123:6123"
    volumes:
      - /opt/esphome/config:/config:rw
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    privileged: true
    command: config/ dashboard
```
I've accessed by container's bash terminal with:
```shell
docker exec -it <container-id> bash
```
And trying to ping my device's hostname has issues with the DNS:
```shell
$ ping test.local
ping: test.local: Name or service not known
```
However, pinging the device's IP address (found with Fing on my Android mobile phone):
```shell
$ ping 192.168.1.55
PING 192.168.1.55 (192.168.1.55) 56(84) bytes of data.
64 bytes from 192.168.1.55: icmp_seq=1 ttl=254 time=83.2 ms
64 bytes from 192.168.1.55: icmp_seq=2 ttl=254 time=103 ms
64 bytes from 192.168.1.55: icmp_seq=3 ttl=254 time=137 ms
^C
--- 192.168.1.55 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 83.236/107.808/137.458/22.425 ms
```

### Which version of ESPHome has the issue?

2022.8.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

**Comment by ArnyminerZ** [comment]
I've tried removing the custom ports configuration and used the `network_mode` option as recommended by the installation guide:
```
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    user: 0:0
    environment:
      - HOME="/"
    network_mode: host
#    ports:
#      - "192.168.1.22:6052:6052"
#      - "192.168.1.22:6123:6123"
    volumes:
      - /opt/esphome/config:/config:rw
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    privileged: true
    command: config/ dashboard
```
But it doesn't fix the issue.
