### ISSUE TITLE
lywsd02 No muestra datos

### ISSUE THREAD

**Issue by makgiber1984** [esphome/issues#3518]
### The problem

![2022-08-24 20 39 18](https://user-images.githubusercontent.com/58627957/186497360-e27723a1-3d4e-443f-b2c5-c8a9186efa95.jpg)

![2022-08-24 19 40 08](https://user-images.githubusercontent.com/58627957/186497358-8eb875c4-45cc-4f6d-92a2-1024484552e1.jpg)

The lywsd02 model does not show the temperature and humidity data in Home assistant. I have tried to have the device only in the ESP32, and it doesn't work either, it always comes out in "unknown" data, it seems that it does not connect to the device. The device is newly purchased from the Xiaomi store, and the firmware version it has is 2.0.1_0060 (Hardware F3_A1), I think this may be the problem, since talking to other users who have the same device, it works correctly for them, but it has firmware version 1.1.2_009

![2022-08-24 19 40 00](https://user-images.githubusercontent.com/58627957/186497357-940b160b-498d-4029-9c55-61b17173f90d.jpg)
7

### Which version of ESPHome has the issue?

2022.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.8.6

### What platform are you using?

ESP32

### Board

az-delivery-devkit-v4

### Example YAML snippet

```yaml
esphome:
  name: gateway-ble

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "___________________________________"

ota:
  password: "-____----------___________"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gateway-Ble"
    password: "-----______"

captive_portal:

esp32_ble_tracker:

sensor:

  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:6D:82:5F
    temperature:
      name: "Planta del Dinero Temperatura"
    moisture:
      name: "Planta del Dinero Humedad"
    illuminance:
      name: "Planta del Dinero Iluminacion"
    conductivity:
      name: "Planta del Dinero Fertilidad"
    battery_level:
      name: "Planta del Dinero Bateria"

  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:6D:82:0D
    temperature:
      name: "Aloe Vera Temperatura"
    moisture:
      name: "Aloe Vera Humedad"
    illuminance:
      name: "Aloe Vera Iluminacion"
    conductivity:
      name: "Aloe Vera Fertilidad"
    battery_level:
      name: "Aloe Vera Bateria"
      
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:6D:81:71
    temperature:
      name: "Lengua de Suegra Temperatura"
    moisture:
      name: "Lengua de Suegra Humedad"
    illuminance:
      name: "Lengua de Suegra Iluminacion"
    conductivity:
      name: "Lengua de Suegra Fertilidad"
    battery_level:
      name: "Lengua de Suegra Bateria"
      
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:6D:82:18
    temperature:
      name: "Yuca Temperatura"
    moisture:
      name: "Yuca Humedad"
    illuminance:
      name: "Yuca Iluminacion"
    conductivity:
      name: "Yuca Fertilidad"
    battery_level:
      name: "Yuca Bateria"

  - platform: xiaomi_lywsd02
    mac_address: A4:C1:38:D0:A6:04
    temperature:
      name: "Temperatura Dormitorio"
    humidity:
      name: "Humedad Dormitorio"
```

### Anything in the logs that might be useful for us?

```txt
[21:02:35][D][esp32_ble_tracker:731]: Found device A4:C1:38:D0:A6:04 RSSI=-45
[21:02:35][D][esp32_ble_tracker:752]:   Address Type: PUBLIC
[21:02:38][D][xiaomi_ble:328]: Got Xiaomi HHCCJCY01 (C4:7C:8D:6D:82:5F):
[21:02:38][D][xiaomi_ble:331]:   Temperature: 32.6°C
[21:02:38][D][sensor:127]: 'Planta del Dinero Temperatura': Sending state 32.60000 °C with 1 decimals of accuracy
[21:02:38][D][esp32_ble_tracker:731]: Found device 9C:8C:6E:4A:D8:57 RSSI=-90
[21:02:38][D][esp32_ble_tracker:752]:   Address Type: PUBLIC
[21:02:39][D][esp32_ble_tracker:731]: Found device 70:28:45:62:99:D0 RSSI=-89
[21:02:39][D][esp32_ble_tracker:752]:   Address Type: PUBLIC
```

### Additional information

I have other "Mi Plant" devices in the same ESP32 and they give the information correctly as you can see in the images attached at the beginning.
