### ISSUE TITLE
Discrete / Unavailable sensor values in HA with deep sleep mode

### ISSUE THREAD

**Issue by Lefuneste83** [esphome/issues#352]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio on Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

https://esphome.io/components/mqtt.html#mqtt-last-will-birth

**Description of problem:**

Hi there. This may not be an issue apart from me being stupid... 
I have been struggling to understand the bahaviour I have since switching from api mode to MQTT mode in order to accomodate for deep sleep mode.  
I have this wireless weather station which has 10s uptime every 10min. It sends out various values for a bunch of sensors. While in api mode everything worked fine except that it would stop updating values after a while. The solution recommended by Otto was to switch to MQTT mode and indeed updates are much more reliable now.

The only remaining issue I have is that, whereas while in api mode I had my sensor values being displayed in HA lovelace as continuous values (in graphs) and last value received in entity cards, in MQTT mode, while everything updates fine every 10 min, I have discrete values in graphs (points displayed) and in entity cards, I have an "Unavailable" while in deep sleep (last value received is not displayed when in deep sleep).

This seems to be the purpose of the described procedure here as it is indeed the behaviour I am witnessing (ESPHome uses the last will testament and birth message feature of MQTT to achieve availability reporting for Home Assistant. If the node is not connected to MQTT, Home Assistant will show all its entities as unavailable (a feature 😉).) :
https://esphome.io/components/mqtt.html#mqtt-last-will-birth

I have spent several hours trying to understand how to get a continuous/last received value in HA lovelace, but have not suceeded to do so.

It seems to be the same issue as described here if I am not mistaking, but I am not sure.
https://github.com/esphome/issues/issues/320

Sorry if this is a very obvious thing I am missing...

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: meteo
  platform: ESP8266
  board: d1_mini
  
  includes:
    - SI1145.h
  libraries:
    - "Adafruit SI1145 Library"

wifi:
  ssid: "myssid"
  password: "mypwd"
  fast_connect: on

  manual_ip:
    static_ip: 192.168.0.XX
    gateway: 192.168.0.XX
    subnet: 255.255.255.0
    dns1: 192.168.0.XX
    dns2: 8.8.8.8
    
# Enable logging
logger:

# Enable Home Assistant API
ota:
  password: 'mypwd'

mqtt:
  broker: 192.168.0.XX
  username: login
  password: "mypwd"

i2c:
  sda: D2
  scl: D1
  scan: True
  frequency: 200kHz

sensor:
  - platform: wifi_signal
    name: "Meteo WiFi Signal Sensor"
    update_interval: 1s

  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      id: bme280_temperature
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
      id: bme280_pressure
      oversampling: 16x
    humidity:
      name: "BME280 Relative Humidity"
      id: bme280_humidity
    address: 0x76
    update_interval: 1s
  
  - platform: template
    name: "Absolute Humidity"
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_temperature).state) /
        (id(bme280_temperature).state + 243.5)) * id(bme280_humidity).state * mw) /
        ((273.15 + id(bme280_temperature).state) * r); // in grams/m^3
    accuracy_decimals: 2
    update_interval: 1s
  
  - platform: template
    name: "Equivalent sea level pressure"
    lambda: |-
      const float STANDARD_ALTITUDE = 260; // in meters, see note
      return id(bme280_pressure).state / powf(1 - ((0.0065 * STANDARD_ALTITUDE) /
        (id(bme280_temperature).state + (0.0065 * STANDARD_ALTITUDE) + 273.15)), 5.257); // in hPa
    update_interval: 1s

  - platform: custom
    lambda: |-
      auto UV_sensor = new SI1145_sensor();
      App.register_component(UV_sensor);
      return {UV_sensor->visible_sensor, UV_sensor->ir_sensor, UV_sensor->uvindex_sensor};

    sensors:
    - name: "Visible Light"
      unit_of_measurement: lux
    - name: "IR Light"
      unit_of_measurement: lux
    - name: "UV Index"
      unit_of_measurement: uvindex
      accuracy_decimals: 2
      
  - platform: tsl2561
    name: "TSL2561 Ambient Light"
    address: 0x39
    update_interval: 1s
      
deep_sleep:
  run_duration: 10s
  sleep_duration: 10min


```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
