### ISSUE TITLE
Compilation problem, default_target_temperature_low mandatory albeit being deprecated

### ISSUE THREAD

**Issue by posterberg** [esphome/issues#3525]
### The problem

It's not possible to compile the component without including default_target_temperature_low in the config for a heater device. This is odd since the documentation says that the option is deprecated.
The presets part of the config has default_target_temperature_low, but it doesn't seem to be sufficient.

### Which version of ESPHome has the issue?

2022-08-0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP8266

### Board

sonoff basic

### Component causing the issue

climate.thermostat

### Example YAML snippet

```yaml
climate:
  - platform: thermostat
    name: "esp_climate_bedroom_kp_thermostat"
    sensor: temperature
    heat_action:
      - switch.turn_on: relay
    idle_action:
      - switch.turn_off: relay
    min_heating_off_time: 300s
    min_heating_run_time: 10s
    min_idle_time: 59s
    heat_deadband: 0.5
    heat_overrun: 0.5
    preset:
      - name: home
        mode: heat
        default_target_temperature_low: 19
      - name: sleep
        mode: heat
        default_target_temperature_low: 17
      - name: away
        mode: heat
        default_target_temperature_low: 12
      - name: eco
        mode: heat
        default_target_temperature_low: 15
```

### Anything in the logs that might be useful for us?

```txt
Failed config

climate.thermostat: [source climate_radiator_bedroom/climate_radiator_bedroom.yaml:62]

  default_target_temperature_low must be defined in default config when using heat_action.
```
