### ISSUE TITLE
Captive portal doesn't show WiFi networks nearby

### ISSUE THREAD

**Issue by anatoly-savchenkov** [esphome/issues#3527]
### The problem

If only AP is configured, captive portal shows no networks nearby. This happens because WiFi scanning is started in `WiFiComponent::setup()` only in case of an STA being configured.

### Which version of ESPHome has the issue?

2022.8.0

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

Custom

### Component causing the issue

wifi

### Example YAML snippet

```yaml
wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

mdns:
  disabled: false

captive_portal:
```
