### ISSUE TITLE
1.13 Bug Report Thread

### ISSUE THREAD

**Issue by OttoWinter** [esphome/issues#353]
ESPHome v1.13 is currently in beta phase: [beta.esphome.io](https://www.youtube.com/watch?v=dQw4w9WgXcQ) [🎉](https://beta.esphome.io)

The version also brings a big refactor on the C++ generator side. However, that also means some components could have stopped working.

This thread is for quickly finding and reporting issues in the current beta release so that the 1.13 release can be as stable as possible. You can post it as a new issue, or use this thread with the form provided below (this thread is here so that creating a bug report is quicker)

Most errors will be on the "this config does not compile" side. I don't expect any errors that would limit an ESPs ability to roll back if there's an issue.

If you find an issue, please do report it! Thanks!

````md
Component: <COMPONENT THAT HAS ISSUE>
Description:
DESCRIPTION OF PROBLEM

Configuration:
```yaml
# PASTE YAML CONFIG HERE

```

Additional Info:

````

**Comment by oohlaf** [comment]
Component: Platform io compilation issue on hassio esphome 1.13
Description:
See build log below config.

Configuration:
```yaml
esphome:
  name: werkbank
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_password

ota:
  password: !secret esphome_password

output:
  - platform: ledc
    pin: 17
    id: gpio_17_red
  - platform: ledc
    pin: 5
    id: gpio_5_green
  - platform: ledc
    pin: 18
    id: gpio_18_blue
  - platform: ledc
    pin: 19
    id: gpio_19_white

light:
  - platform: rgbw
    name: "Werkbank"
    red: gpio_17_red
    green: gpio_5_green
    blue: gpio_18_blue
    white: gpio_19_white
```

Additional Info:
```
INFO Reading configuration...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/werkbank
Processing werkbank (platform: espressif32@1.6.0; framework: arduino; board: nodemcu-32s)
--------------------------------------------------------------------------------
LibraryManager: Installing id=1826 @ 1.0.3
Downloading...
Unpacking  [####################################]  100%
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/nodemcu-32s.html
PLATFORM: Espressif 32 > NodeMCU-32S
HARDWARE: ESP32 240MHz 320KB RAM (4MB Flash)
DEBUG: CURRENT(esp-prog) EXTERNAL(esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <AsyncTCP> 1.0.3
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <Preferences> 1.0
|-- <WiFi> 1.0
|-- <Update> 1.0
Compiling /data/werkbank/.pioenvs/werkbank/src/esphome/components/api/api_message.cpp.o
Compiling /data/werkbank/.pioenvs/werkbank/src/esphome/components/api/api_server.cpp.o
Compiling /data/werkbank/.pioenvs/werkbank/src/esphome/components/api/basic_messages.cpp.o
Compiling /data/werkbank/.pioenvs/werkbank/src/esphome/components/api/command_messages.cpp.o
In file included from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/tuple:40:0,
from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/functional:55,
from src/esphome/core/component.h:4,
from src/esphome/components/api/api_message.h:3,
from src/esphome/components/api/api_message.cpp:1:
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:104:2: error: invalid preprocessing directive #en
#en
^
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:25:0: error: unterminated #ifndef
#ifndef _USES_ALLOCATOR_H
^
In file included from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/memory:77:0,
from src/esphome/core/helpers.h:6,
from src/esphome/components/api/util.h:3,
from src/esphome/components/api/api_message.h:4,
from src/esphome/components/api/api_message.cpp:1:
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:25:0: error: unterminated #ifndef
#ifndef _USES_ALLOCATOR_H
^
In file included from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/tuple:40:0,
from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/functional:55,
from src/esphome/core/component.h:4,
from src/esphome/components/api/api_server.h:3,
from src/esphome/components/api/api_server.cpp:3:
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:104:2: error: invalid preprocessing directive #en
#en
^
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:25:0: error: unterminated #ifndef
#ifndef _USES_ALLOCATOR_H
^
In file included from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/tuple:40:0,
from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/functional:55,
from src/esphome/core/component.h:4,
from src/esphome/components/api/command_messages.h:3,
from src/esphome/components/api/command_messages.cpp:1:
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:104:2: error: invalid preprocessing directive #en
#en
^
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:25:0: error: unterminated #ifndef
#ifndef _USES_ALLOCATOR_H
^
In file included from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/tuple:40:0,
from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/functional:55,
from src/esphome/core/component.h:4,
from src/esphome/components/api/api_message.h:3,
from src/esphome/components/api/basic_messages.h:3,
from src/esphome/components/api/basic_messages.cpp:1:
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:104:2: error: invalid preprocessing directive #en
#en
^
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:25:0: error: unterminated #ifndef
#ifndef _USES_ALLOCATOR_H
^
In file included from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/memory:77:0,
from src/esphome/core/helpers.h:6,
from src/esphome/components/api/util.h:3,
from src/esphome/components/api/api_message.h:4,
from src/esphome/components/api/command_messages.h:5,
from src/esphome/components/api/command_messages.cpp:1:
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:25:0: error: unterminated #ifndef
#ifndef _USES_ALLOCATOR_H
^
In file included from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/memory:77:0,
from src/esphome/core/helpers.h:6,
from src/esphome/components/api/util.h:3,
from src/esphome/components/api/api_message.h:4,
from src/esphome/components/api/basic_messages.h:3,
from src/esphome/components/api/basic_messages.cpp:1:
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:25:0: error: unterminated #ifndef
#ifndef _USES_ALLOCATOR_H
^
In file included from /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/memory:77:0,
from src/esphome/core/helpers.h:6,
from src/esphome/components/light/light_color_values.h:3,
from src/esphome/components/light/light_effect.h:4,
from src/esphome/components/light/light_state.h:6,
from src/esphome/core/controller.h:11,
from src/esphome/components/api/api_server.h:4,
from src/esphome/components/api/api_server.cpp:3:
/root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/uses_allocator.h:25:0: error: unterminated #ifndef
#ifndef _USES_ALLOCATOR_H
^
*** [/data/werkbank/.pioenvs/werkbank/src/esphome/components/api/api_message.cpp.o] Error 1
*** [/data/werkbank/.pioenvs/werkbank/src/esphome/components/api/command_messages.cpp.o] Error 1
*** [/data/werkbank/.pioenvs/werkbank/src/esphome/components/api/basic_messages.cpp.o] Error 1
*** [/data/werkbank/.pioenvs/werkbank/src/esphome/components/api/api_server.cpp.o] Error 1
========================== [ERROR] Took 11.57 seconds ==========================
```

**Comment by OttoWinter** [comment]
@oohlaf Looks like a filesystem in your setup or in the build system truncated a file somehow. Please post more information about your setup, specifically what host is running Hass.io and it's architecture.

**Comment by oohlaf** [comment]
It's a Raspberry Pi 3 Model B with hassos 2.12 and ha 0.93.2

**Comment by tatunts** [comment]
Hello @OttoWinter.

After updating to version 1.13, I can no longer compile this project:

```yaml
esphome:
  name: ${project_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_psw}
  fast_connect: false
  ap:
    ssid: ${friendly_name}
    password: ${ap_psw}

logger:

web_server:

api:
  password: ${api_psw}

ota:

light:
  - platform: fastled_clockless
    id: magic_led
    name: "Móvel da sala"
    rgb_order: GRB
    pin: D1
#    max_refresh_rate: 16ms
    num_leds: 108
    chipset: WS2812B
    effects:
      - random:
      - addressable_rainbow:
          name: Rainbow
          speed: 5
          width: 128
      - addressable_color_wipe:
      - addressable_scan:
          name: Scan
          move_interval: 10ms
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - random:
          name: "RGB transition slow"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "RGB transition fast"
          transition_length: 4s
          update_interval: 5s              

binary_sensor:
  - platform: remote_receiver
    name: "IR TV sala volume mais"
    id: 'tv_lg_sala_vol_plus'
    filters:
      - delayed_off: 800ms
    lg:
      data: 0xC10040BF
      nbits: 32
#    raw:
#      data: [147, -315, 882, -421, 232, -164, 6792, -4553, 505, -1755, 532, -1711, 500, -707, 219, -840, 474, -610, 523, -650, 455, -655, 451, -1787, 478, -642, 489, -874, 234, -609, 523, -605, 504, -630, 499, -758, 375, -607, 499, -610, 523, -630, 475]

  - platform: remote_receiver
    name: "IR TV sala volume menos"
    id: 'tv_lg_sala_vol_minus'
    filters:
      - delayed_off: 800ms
    lg:
      data: 0xC100C03F
      nbits: 32
#    raw:
#      data: [152, -378, 868, -473, 186, -162, 442, -528, 734, -422, 816, -397, 3291, -4636, 527, -1716, 548, -1737, 474, -877, 233, -648, 483, -608, 523, -605, 502, -634, 498, -1735, 503, -607, 523, -627, 618, -573, 268, -783, 505, -701, 405, -656, 502]

  - platform: remote_receiver
    name: "IR TV sala energia"
    id: 'tv_lg_sala_vol_power'
    filters:
      - delayed_off: 800ms
    lg:
      data: 0x20DF10EF
      nbits: 32

sensor:
  - platform: wifi_signal
    id: wifi_measure
    update_interval: 60s

  - platform: template
    name: ${friendly_name} - Sinal Wifi
    unit_of_measurement: '%'
    accuracy_decimals: 0
    icon: "mdi:wifi"
    lambda: |-
        if (id(wifi_measure).state < -92.0)
          return 100.0;
        if (id(wifi_measure).state > -21.0)
          return 1.0;
        else
          return round(( -0.0154 * id(wifi_measure).state * id(wifi_measure).state ) - ( 0.3794 * id(wifi_measure).state ) + 98.182 );

  - platform: adc
    pin: A0
    name: 'planta_casa'
    id: 'planta_casa'
    update_interval: 3600s
    unit_of_measurement: '%'
    accuracy_decimals: 0
    icon: "mdi:water-percent"
    filters:
      - lambda: return (( ( x * 100.0 ) - 80.0 ) / ( 44.0 - 80.0 )) * 100.0;

remote_receiver:
  pin:
    number: GPIO2
    inverted: True
  dump: all
```

Here is the error log:

```
PS C:\Users\anton\Desktop\Casa> esphome casa_d1mini_sensor_planta.yaml config
[32mINFO Reading configuration...[0m
Failed config

binary_sensor.remote_receiver: [source casa_d1mini_sensor_planta.yaml:70]
  platform: remote_receiver
  name: IR TV sala volume mais
  id: tv_lg_sala_vol_plus
  filters:
    - [source casa_d1mini_sensor_planta.yaml:74]

      Expected string for time period with unit.
      delayed_off: 800ms [source casa_d1mini_sensor_planta.yaml:74]
  lg:
    data: 3238019263
    nbits: 32
binary_sensor.remote_receiver: [source casa_d1mini_sensor_planta.yaml:81]
  platform: remote_receiver
  name: IR TV sala volume menos
  id: tv_lg_sala_vol_minus
  filters:
    - [source casa_d1mini_sensor_planta.yaml:85]

      Expected string for time period with unit.
      delayed_off: 800ms [source casa_d1mini_sensor_planta.yaml:85]
  lg:
    data: 3238051903
    nbits: 32
binary_sensor.remote_receiver: [source casa_d1mini_sensor_planta.yaml:92]
  platform: remote_receiver
  name: IR TV sala energia
  id: tv_lg_sala_vol_power
  filters:
    - [source casa_d1mini_sensor_planta.yaml:96]

      Expected string for time period with unit.
      delayed_off: 800ms [source casa_d1mini_sensor_planta.yaml:96]
  lg:
    data: 551489775
    nbits: 32
```

Something changed when use the time syntax? 

Thanks!
