### ISSUE TITLE
Integration sensor has no protection against NaN

### ISSUE THREAD

**Issue by anatoly-savchenkov** [esphome/issues#3531]
### The problem

Integration sensor doesn't check for NaN values on the input and thus accumulated value can be spoiled forever by a single NaN coming from an input sensor. This is in particular possible when a sensor reports NaN as a connectivity issue indicator.

Someone may say that filter for a sensor providing data should filter out NaN values and this is probably the right approach. But (a) documentation is silent about this behavior of Integration sensor and (b) once you realize this, accumulated value is already "infected" with a NaN and cannot be restored. So, the fool proof way is to filter out NaNs inside of the Integration sensor.

I'm wondering how many other accumulating sensors have this problem. Total Daily Energy seems not to be vulnerable to this:
```
void TotalDailyEnergy::process_new_state_(float state) {
  if (std::isnan(state))
    return;
```

### Which version of ESPHome has the issue?

2022.8.0

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

Custom

### Component causing the issue

integration

### Example YAML snippet

```yaml
- platform: homeassistant
    id: mains_voltage
    entity_id: sensor.pzem_004t_v3_voltage
    internal: true
    filters:
      - delta: 0.01 # Prevent repetitive actions using the same value

#   ^^^^^^^^^ Output of this can be NaN

  - platform: template
    update_interval: 1s
    internal: true
    name: ${friendly_devicename} Power
    id: floor_power
    state_class: measurement
    device_class: power
    accuracy_decimals: 0
    unit_of_measurement: "W"
    icon: "mdi:flash"
    lambda: |-
      return id(heater).state * powf(id(mains_voltage).state, 2.0f) / ${floor_resistance};
    filters:
      - delta: 0.01 # Prevent repetitive actions using the same value

  - platform: integration
    name: ${friendly_devicename} Energy
    sensor: floor_power
    time_unit: h
    restore: true
    accuracy_decimals: 3
    unit_of_measurement: "kWh"
    icon: "mdi:flash"
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001 # Wh to kWh
```

### Anything in the logs that might be useful for us?

```txt
[10:50:38][D][homeassistant.sensor:024]: 'sensor.pzem_004t_v3_voltage': Got state 223.60
[10:50:38][V][sensor:076]: 'mains_voltage': Received new state 223.600006
[10:50:38][D][sensor:126]: 'mains_voltage': Sending state 223.60001  with 1 decimals of accuracy
[10:50:39][V][sensor:076]: 'Lytko 101 Power': Received new state 303.932892
[10:50:39][D][sensor:126]: 'Lytko 101 Power': Sending state 303.93289 W with 0 decimals of accuracy
[10:50:39][V][sensor:076]: 'Lytko 101 Energy': Received new state nan
[10:50:39][D][sensor:126]: 'Lytko 101 Energy': Sending state nan kWh with 3 decimals of accuracy
```
