### ISSUE TITLE
ESP32s3 neopixel

### ISSUE THREAD

**Issue by kj4dxk** [esphome/issues#3536]
### The problem

This is what I have in ESPhome-DEV and it works without the light but with the light I get compiler errors no matter which method I choose if I use - platform: neopixelbus or if I use - platform: fastled_clockless.

Is there a certain configuration that I can use?

### Which version of ESPHome has the issue?

ESPHome 2022.8.0 - 17th August 2022 - dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2022.8.7

### What platform are you using?

ESP32-S3

### Board

adafruit_qtpy_esp32s3_nopsram

### Component causing the issue

neopixel, fastled_clockless

### Example YAML snippet

```yaml
esp32:
board: adafruit_qtpy_esp32s3_nopsram
variant: esp32s3
framework:
type: arduino
version: 2.0.4
platform_version: 5.1.1

light:

platform: fastled_clockless
chipset: WS2812 #WS2812B
pin: GPIO39 # NEOPIXEL qt py esp32-s3
num_leds: 1
rgb_order: BRG
name: "FastLED WS2811 Light"
```

### Anything in the logs that might be useful for us?

```txt
no
```

### Additional information

no
