### ISSUE TITLE
Remote_receiver_remotereceivercomponent->set_filter_us: unsigned conversion from 'int' to 'uint8_t' 

### ISSUE THREAD

**Issue by Niorix** [esphome/issues#3537]
### The problem

I get build warning at any filter value, exclude 250
src\main.cpp: In function 'void setup()':
src\main.cpp:84:58: warning: unsigned conversion from 'int' to 'uint8_t' {aka 'unsigned char'} changes value from '350' to '94' [-Woverflow]
   84 |   remote_receiver_remotereceivercomponent->set_filter_us(350); 

### Which version of ESPHome has the issue?

2022.8.0

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

Remote Receiver

### Example YAML snippet

```yaml
esphome:
  name: wemos-test
  platform: ESP8266
  board: d1_mini

remote_receiver:
  pin: D0
  dump:
    - rc_switch
  tolerance: 50%
  filter: 350us
  idle: 4ms
  buffer_size: 2kb
```
