### ISSUE TITLE
http_request.post does not send Content-Length header

### ISSUE THREAD

**Issue by buffcode** [esphome/issues#3539]
### The problem

Currently `http_request.post` does not send a `Content-Length` header with the request. According to the [HTTP spec](https://httpwg.org/specs/rfc7230.html#header.content-length):

> A user agent that sends a request containing a message body MUST send a valid [Content-Length](https://httpwg.org/specs/rfc7230.html#header.content-length) header field if it does not know the server will handle HTTP/1.1 (or later) requests.

As such, some services may reject such HTTP requests.

### Which version of ESPHome has the issue?

2022.8.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.8.7

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

http_request

### Example YAML snippet

```yaml
- http_request.post:
    url: "http://1.2.3.4/"
    verify_ssl: false
    headers:
      Content-Type: application/json
    body: !lambda |-               
      return "foo";
```

### Additional information

ESP32's [`HTTPClient::sendRequest`](https://github.com/espressif/arduino-esp32/blob/77065bffb2c57704ee46ad0a43270e50860814f5/libraries/HTTPClient/src/HTTPClient.cpp#L714) already supports creating that header when a third parameter with the body size is passed, but this parameter is currently not passed in [`HttpRequestComponent`](https://github.com/esphome/esphome/blob/2650441013a587911d603e3e715e63ae7b808484/esphome/components/http_request/http_request.cpp#L76).

A workaround is to calculate the body size and set the custom header oneself. But this makes `http_request.post.json` unusable.
