### ISSUE TITLE
ESP home Compile error

### ISSUE THREAD

**Issue by Wriman** [esphome/issues#354]
I install the esp home, make new node. I make a Vaildate end its okay, and after i vant compiling and dowload the config and its not working.
I try reinstall th hassio, and reinstall the ESPhome, but its not work. 

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Rapsberry Pi3b+, Hassio12
**ESP (ESP32/ESP8266, Board/Sonoff):**
wemos d1 mini

**Affected component:**

**Description of problem:**
I install the esp home, make new node. I make a Vaildate end its okay, and after i vant compiling and dowload the config and its not working.
I try reinstall th hassio, and reinstall the ESPhome, but its not work. 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: wemos_d1_06
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: kenso
  password: openyoureyes

  manual_ip:
    static_ip: 192.168.8.150
    gateway: 192.168.8.8
    subnet: 255.255.255.0
    dns1: 192.168.8.8
    dns2: 8.8.8.8

logger:
  level: DEBUG

api:
  password: rapes123
ota:
  password: rapes123

binary_sensor:
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: True
    name: "wemos_06_switch"

output:
  - platform: esp8266_pwm
    id: blue_led_w06
    pin: D4
    frequency: 200 Hz
    inverted: True

light:
  - platform: monochromatic
    name: "WemosD1_06 Blue LED"
    output: blue_led_w06

sensor:
  - platform: ultrasonic
    trigger_pin: D2
    echo_pin: D1
    unit_of_measurement: "m"
    accuracy_decimals: 3
    update_interval: 1s
    name: "Ultrasonic_06"
```

**Traceback (if applicable):**

```
[API] ConnectionError: HTTPConnectionPool(host='api.platformio.org', port=80): Max retries exceeded with url: /v2/lib/search?query=name%3A%22ESP8266WiFi%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75fd6250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) (incremented retry: max=5, total=1)
```

**Additional information and things you've tried:**
Reinstall the addon, reinstall hassio
