### ISSUE TITLE
Lolin S2 Mini UART+UART or UART+I2C both crash the API

### ISSUE THREAD

**Issue by AndreasBVB** [esphome/issues#3544]
### The problem

Ref https://github.com/esphome/issues/issues/3012
Whenever I open another UART or an I2C on top of an existing UART, the board will boot, connect to WIFI but not the HA API. The OTA also works.

### Which version of ESPHome has the issue?

2022.8.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.5

### What platform are you using?

ESP32-IDF

### Board

Lolin S2 Mini

### Component causing the issue

uart, i2c

### Example YAML snippet

```yaml
substitutions:
  device_upper: LOLIN S2 MINI
  device_lower: ls2m
  device_name: ls2m

esphome:
  name: ${device_name}

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

# Enable logging
logger:
  #level: NONE

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #power_save_mode: HIGH
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret wifi_password

text_sensor:
  - platform: template
    name: ${device_upper} BRAND
    lambda: return {"Lolin"};
    update_interval: 7d
    entity_category: diagnostic
  - platform: template
    name: ${device_upper} HARDWARE
    lambda: return {"S2 Mini"};
    update_interval: 7d
    entity_category: diagnostic
  - platform: template
    name: ${device_upper} PERIPHERALS
    lambda: return {""};
    update_interval: 7d
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: ${device_upper} IP
    mac_address:
      name: ${device_upper} MAC

sensor:
  - platform: wifi_signal
    name: ${device_upper} WiFi Signal
    update_interval: 30s
  - platform: uptime
    update_interval: 30s
    name: ${device_upper} Uptime
  - platform: uptime
    update_interval: 1s
    id: ${device_lower}_uptime_internal

  - platform: senseair
    id: ${device_lower}_senseair
    co2:
      name: ${device_upper} CO2
      id: ${device_lower}_co2
    update_interval: 5s
    uart_id: uart_1
#  - platform: senseair
#    id: ${device_lower}_senseair_dup
#    co2:
#      name: ${device_upper} CO2 DUP
#      id: ${device_lower}_co2_dup
#    update_interval: 60s
#    uart_id: uart_0
#  - platform: bmp280
#    temperature:
#      name: ${device_upper} TEMP
#      oversampling: 16x
#    pressure:
#      name: ${device_upper} PRES
#    address: 0x77
#    update_interval: 60s


button:
  - platform: restart
    name: ${device_upper} RESTART
  - platform: template
    name: ${device_upper} BLINK LED
    entity_category: config
    on_press:
      - script.execute: blink_led

uart:
#  - id: uart_0
#    tx_pin: 37
#    rx_pin: 39
#    baud_rate: 9600
  - id: uart_1
    tx_pin: 17
    rx_pin: 18
    baud_rate: 9600

i2c:
  - id: bus_a
    sda: 7
    scl: 9
    scan: true

output:
  - platform: gpio
    id: led
    pin: GPIO15

script:
  - id: blink_led
    mode: single
    then:
      - output.turn_on: led
      - delay: 300ms
      - output.turn_off: led
      - delay: 200ms
      - output.turn_on: led
      - delay: 300ms
      - output.turn_off: led
      - delay: 200ms
      - output.turn_on: led
      - delay: 300ms
      - output.turn_off: led
      - delay: 200ms
```

### Anything in the logs that might be useful for us?

```txt
Cannot retrieve wireless log. No USB log after installation.
```
