### ISSUE TITLE
Adopted Athom plug not using encryption or OTA Password

### ISSUE THREAD

**Issue by mhaas** [esphome/issues#3548]
### The problem

I have several esp32 dev boards happily running ESPHome (via the Home Assistant add-on). The generated YAML file for each node contains something like the following:

```yaml
# Enable Home Assistant API
api:
  encryption:
    key: "ABCD..."

ota:
  password: "XYZ...."
````

Today, I received a new Athome Smart Plug and I imported the plug to ESPHome via the "adopt" feature. This worked beautifully, but the generated YAML is missing the api key and OTA password that I get when I create a fresh device:

````yaml
substitutions:
  name: athom-smart-plug-v2-abcde
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
````

When I check the logs of the plug after flashing the config, I see:

````
[15:19:40][C][ota:085]: Over-The-Air Updates:
[15:19:40][C][ota:086]:   Address: athom-smart-plug-v2-abcde.local:8266
[15:19:40][C][api:138]: API Server:
[15:19:40][C][api:139]:   Address: athom-smart-plug-v2-abcde.local:6053
[15:19:40][C][api:143]:   Using noise encryption: NO
````

I believe it would be great to have a OTA password set and also the encryption key. The downside is that this may break an existing integration of the device with Home Assistant.

### Which version of ESPHome has the issue?

ESPHome 2022.8.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.8

### What platform are you using?

ESP8266

### Board

athome plug v2 EU

### Additional information

ESPHome is amazing. I was blown by the "adopt" functionality.
