### ISSUE TITLE
Lolin C3 Mini UART#2 not useable

### ISSUE THREAD

**Issue by AndreasBVB** [esphome/issues#3559]
### The problem

Able to define two UART ports: UART0 TX-21/RX-20, UART1 TX-0/RX-1.
As long as a sensor is associated to UART1, the device will not boot. Log turned off.

### Which version of ESPHome has the issue?

2022.8.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.5

### What platform are you using?

ESP32-IDF

### Board

Lolin C3 Mini

### Component causing the issue

uart

### Example YAML snippet

```yaml
substitutions:
  device_upper: LOLIN C3 MINI
  device_lower: lc3m
  device_name: lc3m

esphome:
  name: ${device_name}
  platformio_options:
    board_build.flash_mode: dio
  
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:
  level: NONE

# Enable Home Assistant API
api:

ota:

wifi:
  output_power: "8.5"
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #power_save_mode: HIGH
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails

text_sensor:
  - platform: template
    name: ${device_upper} BRAND
    lambda: return {"Lolin"};
    update_interval: 7d
    entity_category: diagnostic
  - platform: template
    name: ${device_upper} HARDWARE
    lambda: return {"C3 Mini"};
    update_interval: 7d
    entity_category: diagnostic
  - platform: template
    name: ${device_upper} PERIPHERALS
    lambda: return {""};
    update_interval: 7d
    entity_category: diagnostic
  - platform: version
    name: ${device_upper} SOFTWARE
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: ${device_upper} IP
    mac_address:
      name: ${device_upper} MAC

sensor:
  - platform: wifi_signal
    name: ${device_upper} WiFi Signal
    update_interval: 30s
  - platform: uptime
    update_interval: 30s
    name: ${device_upper} Uptime
  - platform: uptime
    update_interval: 1s
    id: ${device_lower}_uptime_internal
#  - platform: senseair
#    co2:
#      name: "UART0 CO2"
#    update_interval: 10s
#    uart_id: uart_0
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "PM1"
    pm_2_5:
      name: "PM25"
    pm_10_0:
      name: "PM10"
    uart_id: uart_1
    update_interval: 60000ms

button:
  - platform: restart
    name: ${device_upper} RESTART

uart:
  - id: uart_0
    tx_pin: 21
    rx_pin: 20
    baud_rate: 9600
  - id: uart_1
    tx_pin: 0
    rx_pin: 1
    baud_rate: 9600
```
