### ISSUE TITLE
hx711 reports inaccurate results.

### ISSUE THREAD

**Issue by vamichael** [esphome/issues#356]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**D1 Mini:**

**Affected component:**

https://esphome.io/components/sensor/hx711.html?highlight=hx711

**Description of problem:**

Testing three different weights:

0 lbs reports: 8397548
8.34 lbs (gallon of water) reports: 24981314
200 lbs (me) reports: 20611480 (which is less than what a gallon of water reports)
--

--

--

**Problem-relevant YAML-configuration entries:**
```yaml

sensor:
  - platform: hx711
    name: "HX711 Value"
    dout_pin: D2
    clk_pin: D3
    gain: 128
    update_interval: 1s
    unit_of_measurement: kg
    filters:
      - lambda: |-
          auto first_mass = 0.0; 
          auto first_value = 8398500;
          auto second_mass = 3.78;
          auto second_value = 24981300;
          return x;

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

I've run the `SparkFun_HX711_Calibration` sketch using the same hardware which reports accurate values.
