### ISSUE TITLE
web_server local javascript - js_include | ReferenceError: actions is not defined

### ISSUE THREAD

**Issue by ferbar** [esphome/issues#3560]
### The problem

According to https://esphome.io/components/web_server.html?highlight=web_server js_include can be used for a local javascript file. However Chrome (at least version 101) seems to switch to strict mode which results in an error when assigning a not yet defined variable:

```
foo = "something"
```

https://github.com/esphome/esphome-docs/blob/current/_static/webserver-v1.js#L26

adding `const` before the assignemts of `actions` and `multi_actions` fixes the issue

### Which version of ESPHome has the issue?

2022.8.1

### What type of installation are you using?

git

### Which version of Home Assistant has the issue?

not related to HA

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
web_server:
  version: 1
  port: 80
  ota: false
  css_url: ""
  css_include: "_static/webserver-v1.min.css"
  js_include: "_static/webserver-v1.min.js"
  js_url: ""
```
