### ISSUE TITLE
segfault when compiling a light device

### ISSUE THREAD

**Issue by darrynlowe** [esphome/issues#3561]
### The problem

I upgraded to 2022.8.3 this morning, and found that my light bulbs are not compiling with a segfault `/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/cmath:557:14: internal compiler error: Segmentation fault` per the log file below. 

I've provided the YAML for the device below.

No changes were made to the YAML from the previous version (2022.8.1) where everything was compiling happily.

I have also tried cleaning the build files, but that did not help.

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.8.7

### What platform are you using?

ESP8266

### Board

NodeMCU

### Component causing the issue

light

### Example YAML snippet

```yaml
esphome:
  name: "${device_name}"
  name_add_mac_suffix: false
  platform: ESP8266
  esp8266_restore_from_flash: false
  board: esp8285
  project:
    name: "${project_name}"
    version: "${project_version}"

api:

ota:

#logger:

#web_server:
#  port: 80

wifi:
  ssid: "xxxxx.iot"
  password: "XXXXX"
  domain: ".xxxx.com"
  fast_connect: false

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${wifi_fallback_ssid}"
    password: "XXXXX"

captive_portal:

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

#sensor:
#  - platform: uptime
#    name: "${friendly_name} Uptime Sensor"
#  - platform: wifi_signal
#    name: "${friendly_name} RSSI"
#    update_interval: 60s

#switch:
#  - platform: restart
#    id: restart_switch
#    name: "${friendly_name} Restart"

#time:
#  - platform: homeassistant
#    id: homeassistant_time

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
  - platform: esp8266_pwm
    id: warm_white_output
    pin: GPIO13
  - platform: esp8266_pwm
    id: white_output
    pin: GPIO5

light:
  - platform: rgbww
    id: "${light_id}"
    name: "${friendly_name}"
    red: red_output
    green: green_output
    blue: blue_output
    warm_white: warm_white_output
    cold_white: white_output
    cold_white_color_temperature: 6000K
    warm_white_color_temperature: 3000K
    color_interlock: true
    restore_mode: ALWAYS_ON 
    on_turn_on:
      - light.turn_on:
          id: "${light_id}"
          color_temperature: 3000K

#text_sensor:
#  - platform: wifi_info
#    ip_address:
#      name: "${friendly_name} IP Address"
#      disabled_by_default: true
#    ssid:
#      name: "${friendly_name} SSID"
#      disabled_by_default: true
#    bssid:
#      name: "${friendly_name} BSSID"
#      disabled_by_default: true
#    mac_address:
#      name: "${friendly_name} MAC Address"
#      disabled_by_default: true
#
```

### Anything in the logs that might be useful for us?

```txt
Here is the segfault from compiling.

INFO Reading configuration /config/esphome/main-kitchen-5-4.yaml...
INFO Generating C++ source...
INFO Core config or version changed, cleaning build files...
INFO Deleting /data/main-kitchen-5-4/.pioenvs
INFO Deleting /data/main-kitchen-5-4/.piolibdeps
INFO Compiling app...
Processing main-kitchen-5-4 (board: esp8285; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
Library Manager: Installing ottowinter/ESPAsyncTCP-esphome @ 1.2.3
INFO Installing ottowinter/ESPAsyncTCP-esphome @ 1.2.3
Unpacking  [####################################]  100%
Library Manager: ESPAsyncTCP-esphome@1.2.3 has been installed!
INFO ESPAsyncTCP-esphome@1.2.3 has been installed!
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
INFO Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome@2.1.0 has been installed!
INFO ESPAsyncWebServer-esphome@2.1.0 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/AsyncTCP-esphome
INFO Installing esphome/AsyncTCP-esphome
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome@2.0.0 has been installed!
INFO AsyncTCP-esphome@2.0.0 has been installed!
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/api/api_connection.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/api/api_pb2_service.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/api/api_server.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/api/list_entities.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/api/proto.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/api/user_services.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/binary_sensor/automation.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling /data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/binary_sensor/filter.cpp.o
In file included from src/esphome/core/component.h:5,
                 from src/esphome/components/api/subscribe_state.h:3,
                 from src/esphome/components/api/subscribe_state.cpp:1:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/cmath: In function 'constexpr typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, int>::__type std::fpclassify(_Tp)':
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/cmath:557:14: internal compiler error: Segmentation fault
  557 |     { return __x != 0 ? FP_NORMAL : FP_ZERO; }
      |              ^~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
*** [/data/main-kitchen-5-4/.pioenvs/main-kitchen-5-4/src/esphome/components/api/subscribe_state.cpp.o] Error 1
========================== [FAILED] Took 4.14 seconds ==========================
```
