### ISSUE TITLE
RDM6300 NFC/RFID doesn't work

### ISSUE THREAD

**Issue by Rubquila** [esphome/issues#3562]
### The problem

I'm trying to use an RDM6300 NFC/RFID with the example on the esphome page, but it is not responding and I don't get any errors. I have tried with 2 modules and different ESP32. Has anyone gotten it to work?

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.7

### What platform are you using?

ESP32

### Board

ESP32Cam, NodeMCU

### Component causing the issue

UART rdm6300

### Example YAML snippet

```yaml
uart:
  rx_pin: GPIO03
  id: nfc_uart
  baud_rate: 9600

rdm6300:
  uart_id: nfc_uart
```
