### ISSUE TITLE
how should the bluetoot_proxy work?

### ISSUE THREAD

**Issue by evlo** [esphome/issues#3566]
### The problem

I don't understand how esphome bluetooth proxy_should work.

i have added
```
esp32_ble_tracker:
  scan_parameters:
    active: true
bluetooth_proxy:
```

to one of my existing esphome devices (climate)

I have tried removing it and adding it into home assistant, but no new entries in esphome integration, bluetooth integration says there are no unconfigured adapters. 

Will the bluetooth proxy discovered devices with with homekit controller if they are actually homekit compatible?

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

bluettoth_proxy

### Example YAML snippet

```yaml
esp32_ble_tracker:
  scan_parameters:
    active: true
bluetooth_proxy:
```

### Additional information

no logs, nothing from bluetooth proxy in debug log, also compile is not complaining about bluetooth_proxy being invalid line etc.
