### ISSUE TITLE
[BMP280] iir_filter option isn't used

### ISSUE THREAD

**Issue by Calimerorulez** [esphome/issues#3568]
### The problem

I've configured my BMP280 to use IIR_Filter:

```
  - platform: bmp280
    temperature:
      name: "airgradient-pro BMP280 temperature"
      oversampling: 16x
    pressure:
      name: "airgradient-pro BMP280 pressure"
      oversampling: 16x
    address: 0x76
    update_interval: 60s
    iir_filter: 16x
```
but the option is ignored:

```
[14:03:18][C][bmp280.sensor:098]: BMP280:
[14:03:18][C][bmp280.sensor:099]:   Address: 0x76
[14:03:18][C][bmp280.sensor:111]:   IIR Filter: OFF
```

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.1

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

bmp280
