### ISSUE TITLE
interlock wait time does not apply properly when quickly switching

### ISSUE THREAD

**Issue by ccrome** [esphome/issues#3572]
### The problem

The switch interlock should use the interlock_wait_time as a means of preventing *any* changes to GPIOs in an interlock group within a certain amount of time since the last change.

That is, if there are multiple requests to the the interlock group within a short amount of time, they should either be queued, or the last one should take precedence, but in no case should anything change within the interlock time.

This is slightly different from 'interlock doesn't work' issues I just filed.  (https://github.com/esphome/issues/issues/3571)

Since the reason we want a wait time for interlocking is that relays shouldn't be switched on rapidly, this should be prevented at all costs.  

An example YAML and capture is attached, using the fan settings to set the relays.  

The switch.turn_on() and switch.turn_off() seems to take effect immediately, rather than respecting the interlock, whicih causes a rapid switching on the relays, which would be horrible on a 3 speed motor.  

By using the fan slider (and using the keyboard to quickly switch between states)
![image](https://user-images.githubusercontent.com/286973/189553747-4f55239a-4b9f-482b-affe-a0280bb00cc2.png)

You can get rapid relay switches, even when the interlock_wait_time is set to 1 second.
![image](https://user-images.githubusercontent.com/286973/189553764-1e454fad-6007-40b2-9a45-9062ed805549.png)

I don't believe that should be able to happen.

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.9.2

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

switch

### Example YAML snippet

```yaml
fan:
  - platform: speed
    id: speed_fan
    output: fan_output_value
    name: "2 Speed Fan"
    speed_count: 3
    on_turn_on:
    - logger.log: "Fan Turned On"
    on_speed_set:
    - logger.log: "Fan Speed was changed"
    on_turn_off:
    - logger.log: "Fan Turned Off"

#relay outputs for 3-speed fan motor 
switch:
  - platform: gpio
    id: relay1
    pin: 16
    restore_mode: ALWAYS_OFF
    #only one should be on
    interlock: &interlock_group [relay1, relay2]
    interlock_wait_time: 1s
    name: "relay1"
  - platform: gpio
    id: relay2
    pin: 17
    restore_mode: ALWAYS_OFF
    interlock: *interlock_group
    interlock_wait_time: 1s
    name: "relay2"
  - platform: gpio
    id: relay3
    pin: 18
    restore_mode: ALWAYS_OFF
    interlock: *interlock_group
    interlock_wait_time: 1s
    name: "relay3"
    
output:
# 3-speed fan output_value    
  - platform: template
    id: fan_output_value
    type: float
    write_action:
      - if:
          condition:
            lambda: return ((state == 0));
          then:
            - switch.turn_off: relay1
            - switch.turn_off: relay2
            - switch.turn_off: relay3
      - if:
          condition:
            lambda: return ((state > 0) && (state <= .34));
          then:
            - switch.turn_on: relay1
            - switch.turn_off: relay2
            - switch.turn_off: relay3
      - if:
          condition:
            lambda: return ((state > .35) && (state <= .67));
          then:
            - switch.turn_on: relay2
            - switch.turn_off: relay1
            - switch.turn_off: relay3
      - if:
          condition:
            lambda: return ((state > .67));
          then:
            - switch.turn_on: relay3
            - switch.turn_off: relay1
            - switch.turn_off: relay2
```
