### ISSUE TITLE
Webserver Light not turning LEDs off as expected

### ISSUE THREAD

**Issue by jonilala796** [esphome/issues#3574]
### The problem

When doing an POST to the following path, I would expect that the color LEDs turn off and the white LEDs turn on:
http://_device-ip_/light/_id_/turn_on?brightness=255&r=0&g=0&b=0&white_value=255

But instead all color LEDs also turn on. The output from http://_device-ip_/light/_id_ is the following:
`{"id":"_device-id_","state":"ON","effect":"None","color_mode":"rgbw","brightness":255,"color":{"r":255,"g":255,"b":255,"w":255},"white_value":255}`

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

web_server/light

### Example YAML snippet

```yaml
web_server:
  port: 80

light:
  - platform: neopixelbus
    type: GRBW
    variant: SK6812
    pin: GPIO10
    num_leds: 240
    name: "device-name"
    default_transition_length: 0s
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_flicker:
```
