### ISSUE TITLE
TCS34725 does overexposure on auto (which leads to negative color temperatures) 

### ISSUE THREAD

**Issue by RubenKelevra** [esphome/issues#3575]
### The problem

I'm using a TCS34725 with `integration_time: auto` on a D1 mini. 

Around noon the color temperature is either NaN or is reported negative:

![IMG_20220912_213211](https://user-images.githubusercontent.com/614929/189741719-b4d0b656-7fb0-47de-b048-c2d3cae9bc27.jpg)

After 14:30 for the rest of the day (with obviously less intense sun hitting the sensor) the values are reported correctly:

![Screenshot_2022-09-12-21-31-36-861_io homeassistant companion android jpg](https://user-images.githubusercontent.com/614929/189743550-cb4fb5fb-0d97-4c71-9f97-ddf494981c44.png)
![Screenshot_2022-09-12-21-31-23-517_io homeassistant companion android jpg](https://user-images.githubusercontent.com/614929/189743589-de940546-6148-48e1-ab5e-445756a36906.png)
![Screenshot_2022-09-12-21-31-10-166_io homeassistant companion android jpg](https://user-images.githubusercontent.com/614929/189743620-c3d02f08-17c3-451f-ba0f-923e5da2b09a.png)
![Screenshot_2022-09-12-21-30-58-298_io homeassistant companion android jpg](https://user-images.githubusercontent.com/614929/189743641-aa25b6c7-aecc-4ae0-9082-072a71dacae8.png)

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.2

### What platform are you using?

ESP8266

### Board

D1_mini

### Component causing the issue

TCS34725

### Example YAML snippet

```yaml
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

substitutions:
  devicename: ambient-light-sensor
  friendly_name: "Ambient Light Sensor"

logger:
  esp8266_store_log_strings_in_flash: false

mdns:
  disabled: true
  

api:
  encryption: 
    key: !secret api_key-ambient-light-sensor

ota:
  password: !secret ota_password_ambient-light-sensor

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.8.27
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1
    dns2: !secret wifi_dns2
  fast_connect: true
  reboot_timeout: 5min


i2c:
  sda: D1
  scl: D2
  scan: true
  id: bus_a

sensor:
  - platform: tcs34725
    i2c_id: bus_a
    red_channel:
      name: "$friendly_name Red Channel relative"
      accuracy_decimals: 2
      filters:
        - exponential_moving_average:
            alpha: 0.05
            send_every: 2
            send_first_at: 2
        - or:
          - throttle: 10s
          - delta: 0.5
    green_channel:
      name: "$friendly_name Green Channel relative"
      accuracy_decimals: 2
      filters:
        - exponential_moving_average:
            alpha: 0.05
            send_every: 2
            send_first_at: 2
        - or:
          - throttle: 10s
          - delta: 0.5
    blue_channel:
      name: "$friendly_name Blue Channel relative"
      accuracy_decimals: 2
      filters:
        - exponential_moving_average:
            alpha: 0.05
            send_every: 2
            send_first_at: 2
        - or:
          - throttle: 10s
          - delta: 0.5
    clear_channel:
      name: "$friendly_name Clear Channel"
      accuracy_decimals: 5
      filters:
        - exponential_moving_average:
            alpha: 0.05
            send_every: 2
            send_first_at: 2
        - or:
          - throttle: 10s
          - delta: 0.5
    illuminance:
      name: "$friendly_name Illuminance"
      accuracy_decimals: 2
      filters:
        - exponential_moving_average:
            alpha: 0.05
            send_every: 2
            send_first_at: 2
        - or:
          - throttle: 10s
          - delta: 0.2
    color_temperature:
      name: "$friendly_name Color Temperature"
      accuracy_decimals: 2
      filters:
        - exponential_moving_average:
            alpha: 0.05
            send_every: 2
            send_first_at: 2
        - or:
          - throttle: 10s
          - delta: 0.5
    integration_time: auto
    glass_attenuation_factor: 1.0
    address: 0x29
    update_interval: 1s    

output:
  - platform: gpio
    pin: D3
    id: white_led
    inverted: false
  
light:
  - platform: binary
    output: white_led
    name: "$friendly_name White LED"
```

**Comment by RubenKelevra** [comment]
Example from today:

![Screenshot from 2022-09-13 13-30-58](https://user-images.githubusercontent.com/614929/189890261-11a3f8d9-d826-486c-9c74-c873e6116f21.png)

**Comment by RubenKelevra** [comment]
@jesserockz @dcousens @ @swifty99 maybe you can have a look at this? Thanks! :)

**Comment by swifty99** [comment]
that's not good. 
could you provide more information? the raw values of all 
```
    red_channel:
      name: "TCS34725 Red Channel"
    green_channel:
      name: "TCS34725 Green Channel"
    blue_channel:
      name: "TCS34725 Blue Channel"
    clear_channel:
      name: "TCS34725 Clear Channel"
    illuminance:
      name: "TCS34725 Illuminance"

```
would be helpful.
