### ISSUE TITLE
Display component not compiling on ESP-IDF

### ISSUE THREAD

**Issue by declan-wade** [esphome/issues#3576]
### The problem

The issue is that the attached YAML only compiles using the arduino framework, the compiler flags the same warnings but the ESP-IDF version has another line `cc1plus: some warnings being treated as errors` (see log). 
The only difference is that this is now an S2 board. 
Is this a bug or issue with the ESP-IDF framework? 

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.9

### What platform are you using?

ESP32

### Board

LOLIN S2 Mini

### Component causing the issue

Display

### Example YAML snippet

```yaml
esphome:
  name: mini-s2

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxx"

ota:
  password: "xxxx"

wifi:
  ssid: "ssid"
  password: "password"

font:
  - file: 'arial.ttf'
    id: font1
    size: 18
  - file: 'arial.ttf'
    id: font2
    size: 14

globals:
  - id: daytime
    type: bool
    initial_value: 'true'

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO9
  miso_pin: GPIO11

time:
  - platform: homeassistant
    id: esptime
    timezone: Australia/Perth
    on_time:
      - seconds: 0
        minutes: 30
        hours: 6
        then:
          - globals.set:
              id: daytime
              value: 'true'
      - seconds: 0
        minutes: 0
        hours: 23
        then:
          - globals.set:
              id: daytime
              value: 'false'

sensor:
  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.indoor_temperature
    internal: true

  - platform: homeassistant
    id: outside_temperature
    entity_id: sensor.outdoor_temperature
    internal: true
    
  - platform: homeassistant
    id: rain_today
    entity_id: sensor.jandakot_rain_since_9am
    internal: true  
    
  - platform: homeassistant
    id: rain_tomorrow
    entity_id: sensor.canning_vale_rain_chance_1
    internal: true  
  
  - platform: homeassistant
    id: max_temp_tomorrow
    entity_id: sensor.canning_vale_temp_max_1
    internal: true  
    
  - platform: homeassistant
    id: min_temp_tomorrow
    entity_id: sensor.canning_vale_temp_min_1
    internal: true 

display:
  - platform: ssd1306_spi
    model: "SSD1306 128x64"
    cs_pin: GPIO12
    dc_pin: GPIO11
    reset_pin: GPIO13
    id: my_display
    pages:
      - id: page1
        lambda: |-
          if(id(daytime)==true){
          it.printf(0, 0, id(font2), "Current temps:");
            if (id(inside_temperature).has_state()) {
              it.printf(127, 23, id(font2), TextAlign::TOP_RIGHT , "Inside: %.1f°C", id(inside_temperature).state);
            }
      
            if (id(outside_temperature).has_state()) {
              it.printf(127, 60, id(font2), TextAlign::BASELINE_RIGHT , "Outside: %.1f°C", id(outside_temperature).state);
            }
          }
          else {
            it.printf(127, 23, id(font1), TextAlign::TOP_RIGHT , "");
          }
      - id: page2
        lambda: |-
          if(id(daytime)==true){
            it.printf(0, 0, id(font2), "Rain:");
            if (id(inside_temperature).has_state()) {
              it.printf(127, 23, id(font2), TextAlign::TOP_RIGHT , "Today: %.1fmm", id(rain_today).state);
            }
      
            if (id(outside_temperature).has_state()) {
              it.printf(127, 60, id(font2), TextAlign::BASELINE_RIGHT , "Tomorrow: %.0f%%", id(rain_tomorrow).state);
            }
          }
          else {
            it.printf(127, 23, id(font1), TextAlign::TOP_RIGHT , "");
          }
      - id: page3
        lambda: |-
          if(id(daytime)==true){
            it.printf(0, 0, id(font2), "Forecast tomorrow:");
            if (id(inside_temperature).has_state()) {
              it.printf(127, 23, id(font2), TextAlign::TOP_RIGHT , "Max: %.0f°C", id(max_temp_tomorrow).state);
            }
      
            if (id(outside_temperature).has_state()) {
              it.printf(127, 60, id(font2), TextAlign::BASELINE_RIGHT , "Min: %.0f°C", id(min_temp_tomorrow).state);
            }
          }
          else {
            it.printf(127, 23, id(font1), TextAlign::TOP_RIGHT , "");
          }

interval:
  - interval: 10s
    then:
      - display.page.show_next: my_display
      - component.update: my_display
      - logger.log: daytime

binary_sensor:
  - platform: template
    name: daytime
    lambda: |- 
      if (id(daytime) == true) {
        return true;
      } else {
        return false;
      }
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/mini-s2.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing mini-s2 (board: esp32-s2-saola-1; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32S2 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40302.0 (4.3.2) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32s2 @ 8.4.0+2021r2-patch2
Reading CMake configuration...
Generating assembly for certificate bundle...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling .pioenvs/mini-s2/src/esphome/components/api/api_connection.o
Compiling .pioenvs/mini-s2/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/mini-s2/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/mini-s2/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/mini-s2/src/esphome/components/api/api_server.o
Compiling .pioenvs/mini-s2/src/esphome/components/api/list_entities.o
Compiling .pioenvs/mini-s2/src/esphome/components/api/proto.o
Compiling .pioenvs/mini-s2/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/mini-s2/src/esphome/components/api/user_services.o
Compiling .pioenvs/mini-s2/src/esphome/components/binary_sensor/automation.o
Compiling .pioenvs/mini-s2/src/esphome/components/binary_sensor/binary_sensor.o
Compiling .pioenvs/mini-s2/src/esphome/components/binary_sensor/filter.o
Compiling .pioenvs/mini-s2/src/esphome/components/display/display_buffer.o
Compiling .pioenvs/mini-s2/src/esphome/components/esp32/core.o
Compiling .pioenvs/mini-s2/src/esphome/components/esp32/gpio_arduino.o
Compiling .pioenvs/mini-s2/src/esphome/components/esp32/gpio_idf.o
Compiling .pioenvs/mini-s2/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/mini-s2/src/esphome/components/homeassistant/sensor/homeassistant_sensor.o
Compiling .pioenvs/mini-s2/src/esphome/components/homeassistant/time/homeassistant_time.o
Compiling .pioenvs/mini-s2/src/esphome/components/logger/logger.o
Compiling .pioenvs/mini-s2/src/esphome/components/md5/md5.o
Compiling .pioenvs/mini-s2/src/esphome/components/mdns/mdns_component.o
Compiling .pioenvs/mini-s2/src/esphome/components/mdns/mdns_esp32_arduino.o
Compiling .pioenvs/mini-s2/src/esphome/components/mdns/mdns_esp8266.o
Compiling .pioenvs/mini-s2/src/esphome/components/mdns/mdns_esp_idf.o
Compiling .pioenvs/mini-s2/src/esphome/components/network/util.o
Compiling .pioenvs/mini-s2/src/esphome/components/ota/ota_backend_arduino_esp32.o
Compiling .pioenvs/mini-s2/src/esphome/components/ota/ota_backend_arduino_esp8266.o
Compiling .pioenvs/mini-s2/src/esphome/components/ota/ota_backend_esp_idf.o
Compiling .pioenvs/mini-s2/src/esphome/components/ota/ota_component.o
Compiling .pioenvs/mini-s2/src/esphome/components/sensor/automation.o
Compiling .pioenvs/mini-s2/src/esphome/components/sensor/filter.o
Compiling .pioenvs/mini-s2/src/esphome/components/sensor/sensor.o
Compiling .pioenvs/mini-s2/src/esphome/components/socket/bsd_sockets_impl.o
Compiling .pioenvs/mini-s2/src/esphome/components/socket/lwip_raw_tcp_impl.o
Compiling .pioenvs/mini-s2/src/esphome/components/socket/socket.o
Compiling .pioenvs/mini-s2/src/esphome/components/spi/spi.o
Compiling .pioenvs/mini-s2/src/esphome/components/ssd1306_base/ssd1306_base.o
Compiling .pioenvs/mini-s2/src/esphome/components/ssd1306_spi/ssd1306_spi.o
Compiling .pioenvs/mini-s2/src/esphome/components/template/binary_sensor/template_binary_sensor.o
Compiling .pioenvs/mini-s2/src/esphome/components/time/automation.o
Compiling .pioenvs/mini-s2/src/esphome/components/time/real_time_clock.o
Compiling .pioenvs/mini-s2/src/esphome/components/wifi/wifi_component.o
Compiling .pioenvs/mini-s2/src/esphome/components/wifi/wifi_component_esp32_arduino.o
Compiling .pioenvs/mini-s2/src/esphome/components/wifi/wifi_component_esp8266.o
Compiling .pioenvs/mini-s2/src/esphome/components/wifi/wifi_component_esp_idf.o
Compiling .pioenvs/mini-s2/src/esphome/core/application.o
Compiling .pioenvs/mini-s2/src/esphome/core/color.o
Compiling .pioenvs/mini-s2/src/esphome/core/component.o
Compiling .pioenvs/mini-s2/src/esphome/core/component_iterator.o
Compiling .pioenvs/mini-s2/src/esphome/core/controller.o
Compiling .pioenvs/mini-s2/src/esphome/core/entity_base.o
Compiling .pioenvs/mini-s2/src/esphome/core/helpers.o
Compiling .pioenvs/mini-s2/src/esphome/core/log.o
Compiling .pioenvs/mini-s2/src/esphome/core/scheduler.o
Compiling .pioenvs/mini-s2/src/esphome/core/util.o
Compiling .pioenvs/mini-s2/src/main.o
Generating LD script .pioenvs/mini-s2/esp32s2_out.ld
Generating partitions .pioenvs/mini-s2/partitions.bin
Compiling .pioenvs/mini-s2/app_trace/app_trace.o
Compiling .pioenvs/mini-s2/app_trace/app_trace_util.o
Compiling .pioenvs/mini-s2/app_trace/host_file_io.o
Compiling .pioenvs/mini-s2/app_trace/gcov/gcov_rtio.o
Compiling .pioenvs/mini-s2/app_update/esp_ota_ops.o
Compiling .pioenvs/mini-s2/app_update/esp_app_desc.o
Archiving .pioenvs/mini-s2/esp-idf/app_trace/libapp_trace.a
/config/mini-s2.yaml: In lambda function:
/config/mini-s2.yaml:115:58: error: zero-length gnu_printf format string [-Werror=format-zero-length]
             it.printf(127, 23, id(font1), TextAlign::TOP_RIGHT , "");
                                                          ^~
/config/mini-s2.yaml: In lambda function:
/config/mini-s2.yaml:130:58: error: zero-length gnu_printf format string [-Werror=format-zero-length]
             it.printf(127, 23, id(font1), TextAlign::TOP_RIGHT , "");
                                                          ^~
/config/mini-s2.yaml: In lambda function:
/config/mini-s2.yaml:145:58: error: zero-length gnu_printf format string [-Werror=format-zero-length]
             it.printf(127, 23, id(font1), TextAlign::TOP_RIGHT , "");
                                                          ^~
Compiling .pioenvs/mini-s2/asio/asio/asio/src/asio.o
Compiling .pioenvs/mini-s2/bootloader_support/src/bootloader_common.o
Archiving .pioenvs/mini-s2/esp-idf/app_update/libapp_update.a
Compiling .pioenvs/mini-s2/bootloader_support/src/bootloader_common_loader.o
Compiling .pioenvs/mini-s2/bootloader_support/src/bootloader_clock_init.o
Compiling .pioenvs/mini-s2/bootloader_support/src/bootloader_flash.o
Compiling .pioenvs/mini-s2/bootloader_support/src/bootloader_mem.o
Compiling .pioenvs/mini-s2/bootloader_support/src/bootloader_random.o
Compiling .pioenvs/mini-s2/bootloader_support/src/bootloader_random_esp32s2.o
Compiling .pioenvs/mini-s2/bootloader_support/src/bootloader_utility.o
Compiling .pioenvs/mini-s2/bootloader_support/src/esp_image_format.o
Compiling .pioenvs/mini-s2/bootloader_support/src/flash_encrypt.o
Compiling .pioenvs/mini-s2/bootloader_support/src/secure_boot.o
Compiling .pioenvs/mini-s2/bootloader_support/src/flash_partitions.o
Compiling .pioenvs/mini-s2/bootloader_support/src/flash_qio_mode.o
Compiling .pioenvs/mini-s2/bootloader_support/src/bootloader_flash_config_esp32s2.o
Compiling .pioenvs/mini-s2/bootloader_support/src/bootloader_efuse_esp32s2.o
Compiling .pioenvs/mini-s2/bootloader_support/src/idf/bootloader_sha.o
Compiling .pioenvs/mini-s2/cbor/tinycbor/src/cborencoder_close_container_checked.o
Compiling .pioenvs/mini-s2/cbor/tinycbor/src/cborencoder.o
Compiling .pioenvs/mini-s2/cbor/tinycbor/src/cborerrorstrings.o
Compiling .pioenvs/mini-s2/cbor/tinycbor/src/cborparser_dup_string.o
Compiling .pioenvs/mini-s2/cbor/tinycbor/src/cborparser.o
Archiving .pioenvs/mini-s2/esp-idf/bootloader_support/libbootloader_support.a
Compiling .pioenvs/mini-s2/cbor/tinycbor/src/cborpretty_stdio.o
Compiling .pioenvs/mini-s2/cbor/tinycbor/src/cborpretty.o
Compiling .pioenvs/mini-s2/cbor/tinycbor/src/cbortojson.o
Compiling .pioenvs/mini-s2/cbor/tinycbor/src/cborvalidation.o
Compiling .pioenvs/mini-s2/cbor/tinycbor/src/open_memstream.o
Compiling .pioenvs/mini-s2/cmock/CMock/src/cmock.o
Compiling .pioenvs/mini-s2/coap/libcoap/src/address.o
Archiving .pioenvs/mini-s2/esp-idf/cmock/libcmock.a
Compiling .pioenvs/mini-s2/coap/libcoap/src/async.o
Compiling .pioenvs/mini-s2/coap/libcoap/src/block.o
Compiling .pioenvs/mini-s2/coap/libcoap/src/coap_event.o
cc1plus: some warnings being treated as errors
Compiling .pioenvs/mini-s2/coap/libcoap/src/coap_hashkey.o
*** [.pioenvs/mini-s2/src/main.o] Error 1
========================= [FAILED] Took 18.66 seconds =========================
```
