### ISSUE TITLE
component.update in script on DHT22 Sensor

### ISSUE THREAD

**Issue by StodaraHodan** [esphome/issues#3588]
### The problem

Hi,

i try to use the component.update function on a DHT22 Sensor in a Script. It works with a DH18B20 Sensor but i can't get it to work on the DHT, i set the id according to the documentation https://esphome.io/components/sensor/dht.html

I also tried calling the update method directly via the lamda  function, 

```
dallas:
  - id: dstemp
    pin: 2
    update_interval: never
  
sensor:
  - platform: dallas
    address: 0x44dd802912646128
    name: "DS18B20"
  - platform: dht
    model: DHT22
    #model: DHT22_TYPE2
    #model: AM2302
    pin: 0
    temperature:
      name: "DHT Temperature"
      id: dhttemp
    humidity:
      name: "DHT Humidity"
      id: dhthum
    update_interval: never
    #update_interval: 60s
    
script:
  - id: updatesensors
    then:
      - component.update: dstemp
      #- delay: 10m
      - component.update: dhttemp
      #- lambda: 'id(dhttemp).update();'
      #- delay: 10ms
      - component.update: dhthum
      #- lambda: 'id(dhthum).update();'
```

Error on compile (using Component.update):

```
INFO Reading configuration /config/test.yaml...
Failed config

script: [source /config/test.yaml:68]
  - id: updatesensors
    then: 
      - component.update: 
          id: dstemp
      - component.update: 
          
          ID 'dhttemp' of type sensor::Sensor doesn't inherit from PollingComponent. Please double check your ID is pointing to the correct value.
          id: dhttemp
      - component.update: 
          
          ID 'dhthum' of type sensor::Sensor doesn't inherit from PollingComponent. Please double check your ID is pointing to the correct value.
          id: dhthum
    mode: single
```

Error using update method:
```

INFO Reading configuration /config/test.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing test (board: esp01_1m; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- AsyncMqttClient-esphome @ 0.8.6
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/test/src/main.cpp.o
/config/test.yaml: In lambda function:
/config/test.yaml:73:16: error: 'class esphome::sensor::Sensor' has no member named 'update'
   73 |       - lambda: 'id(dhttemp).update();'
      |                ^~~~~~
/config/test.yaml: In lambda function:
/config/test.yaml:76:15: error: 'class esphome::sensor::Sensor' has no member named 'update'
   76 |       - lambda: 'id(dhthum).update();'
      |               ^~~~~~
*** [.pioenvs/test/src/main.cpp.o] Error 1
========================== [FAILED] Took 4.33 seconds ==========================
```

i am not quite sure if i did this correct because according to this site, the dht component DOES inherit from PollingComponent 

https://esphome.io/api/classesphome_1_1dht_1_1_d_h_t.html

Maybe someone can provide some insight on this, thanks in advance

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

Generic 8266 Board

### Component causing the issue

DHT
