### ISSUE TITLE
HMC5883L <---> QMC5883L doc need improvement

### ISSUE THREAD

**Issue by renarena** [esphome/issues#3590]
### The problem

There are 2 different sensors, HMC5883L and QMC5883L.
If its named GY-271 and looks like HMC5883L that doesnt mean you have a HMC5883L!
But you dont know this and esphome cannot read anything, if you have the one mimicking the other.

If you get an error about could not read anything and  your esp log says.
```
[i2c.arduino:053]: Results from i2c bus scan:
[i2c.arduino:059]: Found i2c device at address 0x0D
```
you actually have the QMC5883L, which has other address and need other values.

### Which version of ESPHome has the issue?

each / website documentation

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

HMC5883L

### Example YAML snippet

```yaml
sensor:
#doesnt work if you have a qmc5883l mimicking hmc5883l
  - platform: hmc5883l
    address: 0x68
    oversampling: 1x
    range: 130uT
    update_interval: 60s

works, but maybe yo dont know there is another one you need to use
  - platform: qmc5883l
    address: 0x0D
    oversampling: 64x      # 512x (default), 256x, 128x, 64x
    range: 800uT           # 200 uT, 800 uT
```

### Anything in the logs that might be useful for us?

```txt
[i2c.arduino:053]: Results from i2c bus scan:
[i2c.arduino:059]: Found i2c device at address 0x0D
```

### Additional information

On https://esphome.io/components/sensor/hmc5883l.html add a warning about breakout boards using another sensor then in technical data and add a  link to https://esphome.io/components/sensor/qmc5883l.html (and maybe vice versa)
