### ISSUE TITLE
Modubus fail  crc16 not found

### ISSUE THREAD

**Issue by albertbusoms** [esphome/issues#3592]
### The problem

Modbus, when updating the EspHome docker it no longer compiles
The following error appears:

Compiling .pioenvs/soterrani2/src/esphome/components/modbus/modbus.cpp.o
src/esphome/components/modbus/modbus.cpp: In member function 'bool esphome::modbus::Modbus::parse_modbus_byte_(uint8_t)':
src/esphome/components/modbus/modbus.cpp:71:29: error: 'crc16' was not declared in this scope
   71 |     uint16_t computed_crc = crc16(raw, data_offset + data_len);
      |                             ^~~~~

### Which version of ESPHome has the issue?

last

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

modbus

### Example YAML snippet

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: dev
    components: [ modbus, modbus_controller ]
    
modbus:
  id: modbus1
  send_wait_time: 2000ms
  
modbus_controller:
  - id: epever
    address: 0x01
    modbus_id: modbus1
    update_interval: 2s
    setup_priority: -10
    
  - id: epever2
    address: 0x02
    modbus_id: modbus1
    update_interval: 2s
    setup_priority: -10    
      
uart:
  id: mod_bus
  rx_pin: D6
  tx_pin: D5
  baud_rate: 9600
  stop_bits: 1

sensor:
  - platform: dht
    model: DHT11
    pin: D1
    
    temperature:
      accuracy_decimals: 1
      name: "Sotano temperatura"
    humidity:
      name: "Sotano Humitat"
    update_interval: 60s

  - platform: modbus_controller
    modbus_controller_id: epever
    id: voltatge_Xarxa
    name: voltatge_Xarxa 
    address: 0x2000
    unit_of_measurement: "V"
    register_type: holding
    skip_updates: 30
    value_type: S_DWORD
    accuracy_decimals: 1
    lambda: 
       union My_un {
         char temp[4];
         float foo;
       } un;
       un.temp[0] = data[3];
       un.temp[1] = data[2];
       un.temp[2] = data[1];
       un.temp[3] = data[0];
       ESP_LOGI("","foo=%f,0X%2X%2X%2X%2X",un.foo,un.temp[0],un.temp[1],un.temp[2],un.temp[3]);
       return un.foo ;
```

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/modbus/modbus.cpp: In member function 'bool esphome::modbus::Modbus::parse_modbus_byte_(uint8_t)':
src/esphome/components/modbus/modbus.cpp:71:29: error: 'crc16' was not declared in this scope
   71 |     uint16_t computed_crc = crc16(raw, data_offset + data_len);
      |                             ^~~~~
src/esphome/components/modbus/modbus.cpp:102:29: error: 'crc16' was not declared in this scope
  102 |     uint16_t computed_crc = crc16(raw, data_offset + data_len);
      |                             ^~~~~
src/esphome/components/modbus/modbus.cpp: In member function 'void esphome::modbus::Modbus::send(uint8_t, uint8_t, uint16_t, uint16_t, uint8_t, const uint8_t*)':
src/esphome/components/modbus/modbus.cpp:180:14: error: 'crc16' was not declared in this scope
  180 |   auto crc = crc16(data.data(), data.size());
      |              ^~~~~
src/esphome/components/modbus/modbus.cpp: In member function 'void esphome::modbus::Modbus::send_raw(const std::vector<unsigned char>&)':
src/esphome/components/modbus/modbus.cpp:207:14: error: 'crc16' was not declared in this scope
  207 |   auto crc = crc16(payload.data(), payload.size());
      |              ^~~~~
*** [.pioenvs/soterrani2/src/esphome/components/modbus/modbus.cpp.o] Error 1
========================== [FAILED] Took 4.92 seconds ==========================
```
