### ISSUE TITLE
Hydreon RG15 - platform not found

### ISSUE THREAD

**Issue by cazals-hass** [esphome/issues#3593]
### The problem

I have used the yaml recommended under ESP Home for the Hydreon RG15 and I cannot resolve the issue -  'platform not found sensor.hydreon_rgxx'

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.5

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

hydreon rg15

### Example YAML snippet

```yaml
esphome:
  name: rain-sensor
esp8266:
  board: d1_mini
# Enable logging
logger:
# Example RG-15 entry
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
sensor:
  - platform: hydreon_rgxx
    model: "RG_15"
    update_interval: 120s
    acc:
      name: "Rain"
    event_acc:
      name: "Rain Event"
    total_acc:
      name: "Rain Total"
    r_int:
      name: "Rain Intensity"
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/rain-sensor.yaml...
Failed config

sensor.hydreon_rgxx: [source /config/esphome/rain-sensor.yaml:18]
  
  ****Platform not found: 'sensor.hydreon_rgxx'.****
  platform: hydreon_rgxx
  model: RG_15
  update_interval: 120s
  acc: 
    name: Rain
  event_acc: 
    name: Rain Event
  total_acc: 
    name: Rain Total
  r_int: 
    name: Rain Intensity
```
