### ISSUE TITLE
adafruit Feather board and waveshare e-Paper Driver HAT revision 2.2 nor working

### ISSUE THREAD

**Issue by JeroenTuinstra** [esphome/issues#3594]
### The problem

The Waveshare Universal e-Paper Driver HAT (revision 2.2) in combination with the Adafruit HUZZAH32 Feather board (esp32-wroom-32e) and a waveshare 7.50inV2 screen is not working at all. 

Using the Waveshare ESP32 Driver Board everything works. However the above mentioned combination does not work. I know the e-Paper Driver HAT works as in Adruino IDE with the GxEPD library the HUZZAH32 Feather board can operate the 7.50inV2 screen with the e-Paper Driver HAT.

These are the current settings in ESPhome with the pin settings that worked in Adruino.

```
esp32:
  board: featheresp32
  framework:
    type: arduino

...

spi:
  clk_pin: 5
  mosi_pin: 18

display:
  - platform: waveshare_epaper
    cs_pin: 22
    dc_pin: 17
    busy_pin: 32
    reset_pin: 16
    model: 7.50inV2
    update_interval: 30sec
    lambda: |-
      it.print(563, 340, id(tm30), TextAlign::TOP_CENTER, "Hello World");
```
So the display doesn't do anything at all. No refresh, no redraw, no startup ... just as if nothing is attached to it. No error messages in the log file except this when level is set to VERBOSE: 

```
[13:06:40][V][component:199]: Component waveshare_epaper.display took a long time for an operation (0.76 s).
[13:06:40][V][component:200]: Components should block for at most 20-30ms.
```
But it does this also with a working display and header.

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

Adafruit HUZZAH32 Feather

### Component causing the issue

SPI

### Example YAML snippet

```yaml
spi:
  clk_pin: 5
  mosi_pin: 18

display:
  - platform: waveshare_epaper
    cs_pin: 22
    dc_pin: 17
    busy_pin: 32
    reset_pin: 16
    model: 7.50inV2
    update_interval: 30sec
    lambda: |-
      it.print(563, 340, id(tm30), TextAlign::TOP_CENTER, "Hello World");
```

**Comment by JeroenTuinstra** [comment]
It turns out you have to add ```reset_duration: 2ms``` to the ```display``` section.
```
display:
  - platform: waveshare_epaper
    cs_pin: 22
    dc_pin: 17
    busy_pin: 32
    reset_pin: 16
    model: 7.50inV2
    update_interval: 30sec
    reset_duration: 2ms
    lambda: |-
```
It was mentioned in the ESPHome documentation, but when you use the waveshare e-paper with the waveshare e-paper driver board, then you don't need that setting.
