### ISSUE TITLE
ESP32-C3 + SGP30 random resets

### ISSUE THREAD

**Issue by AndreasBVB** [esphome/issues#3596]
### The problem

Tried on both Lolin C3 Mini and Espressif official C3-DevKitM-1. Once the SGP30 I2C sensor (tried two different ones) is attached, the device will randomly reboot about 8-10 times a day. Not even sure if it's software problem or hardware. Because it happens randomly I have no idea what kind of log/trace to look for so kindly suggest.

### Which version of ESPHome has the issue?

2022.8.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.5

### What platform are you using?

ESP32-IDF

### Board

Lolin C3 Mini, Espressif-C3-DevKitM-1

### Component causing the issue

i2c

### Example YAML snippet

```yaml
substitutions:
  device_upper: SANDBOX ESP32C3
  device_lower: sandbox_esp32c3
  device_name: sandbox-esp32c3

esphome:
  name: ${device_name}
  platformio_options:
    board_build.flash_mode: dio
  
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:
  level: NONE

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

sensor:
  - platform: wifi_signal
    name: ${device_upper} WiFi Signal
    update_interval: 30s

  - platform: uptime
    update_interval: 30s
    name: ${device_upper} Uptime

  - platform: sgp30
    eco2:
      name: ${device_upper} eCO2
      id: ${device_lower}_eco2
      accuracy_decimals: 1
      force_update: true
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30
            send_first_at: 30
    tvoc:
      name: ${device_upper} TVOC
      id: ${device_lower}_tvoc
      accuracy_decimals: 1
      force_update: true
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30
            send_first_at: 30
    store_baseline: no
    baseline: #37022300
      eco2_baseline: 0x8F36
      tvoc_baseline: 0x941A
    address: 0x58
    update_interval: 1s

i2c:
  sda: 4
  scl: 5
  scan: false
  id: i2c_bus
```
