### ISSUE TITLE
ttgo t-display st7789v wont display on 2022.9.0

### ISSUE THREAD

**Issue by landonr** [esphome/issues#3597]
### The problem

I get a black screen after updating to 2022.9.0 on my TTGo Tdisplay st7789v. The backlight turns on and the display lambda gets called but in my test yaml a rectangle doesn't get drawn

### Which version of ESPHome has the issue?

2022.9.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

featheresp32

### Example YAML snippet

```yaml
esphome:
  name: tdisplaytest
  platform: ESP32
  board: featheresp32

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tdisplaytest Fallback Hotspot"
    password: "W3EzIrtpixFo"

captive_portal:

color:
  - id: color_red
    red: 1
    green: 0
    blue: 0

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19 

# TODO brightness
display:
  - platform: st7789v
    model: TTGO_TDISPLAY_135X240
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90°
    #brightness: 0.5
    update_interval: 5s
    lambda: |-
      ESP_LOGD("TEST", "display");
      it.rectangle(0, 0, 40, 40, id(color_red));
```

### Additional information

it works on 2022.8.3
