### ISSUE TITLE
"Total Power" reporting zero on Eastron SDM230m

### ISSUE THREAD

**Issue by mprowe** [esphome/issues#3600]
### The problem

I am using the sample code from here: [SDM Meter](https://esphome.io/components/sensor/sdm_meter.html).
My modified code is included (in full) below.
When run, the displayed value for "Total Power" is shown as zero.
![image](https://user-images.githubusercontent.com/14279344/191529394-0d6420a2-80cf-48c9-90c4-76a67d3bdd8e.png)

### Which version of ESPHome has the issue?

2022.9.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.5

### What platform are you using?

ESP32

### Board

doit-devkit-v1

### Component causing the issue

MODBUS SDM_METER total_power

### Example YAML snippet

```yaml
esphome:
  name: "esp32-sdm230m"
  platform: esp32
  board: esp32doit-devkit-v1

#The source of the "Healthy" LED IS: https://community.home-assistant.io/t/blink-how/307243/13
# output:
#   - platform: gpio
#     pin:
#       number: GPIO2
#       mode: output
#     id: Heathy
# interval:
#   - interval: 2s
#     then:
#       - output.turn_on: Heathy
#       - delay: 10ms
#       - output.turn_off: Heathy

#The source of "status LED" is: https://community.home-assistant.io/t/status-led-status-led-light-binary-light-light-components/443263/2
#Healthy = 0.2Hz (once every 5sec)
#Warning = 1Hz
#Error   = 2Hz
light:
  - platform: status_led
    pin: GPIO2
    id: led_status_light
    restore_mode: ALWAYS_ON
    internal: true
    effects:
    - strobe:
        name: "Slow Blink" # 0.05s on, 5s off
        colors:
          - state: true
            brightness: 100%
            duration: 5ms
          - state: false
            duration: 5s
    on_turn_on:
      - light.turn_on:
          id: led_status_light
          effect: "Slow Blink"
          
  #framework:
  #  type: arduino

# Enable logging
logger:
  baud_rate: 0
  level: VERY_VERBOSE

api:
#  encryption:
#    key: "yDpM1UDh5Pg/y2MxkbJ3sA7ZUrP7LXLR8fSMtMS9Eic="

ota:
  password: "a4169742d0654537e5068529e6545c51"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Sdm230M Fallback Hotspot"
    password: "1FMrHaHV7m7F"

captive_portal:


uart:
  - id: uart1
    # RX/TX are swopped to make PCB layout easer.
    tx_pin: GPIO16 #marked as RX2 on DOIT DEVKIT V1
    rx_pin: GPIO17 #marked as TX2.
    baud_rate: 9600
    stop_bits: 1
    parity: none

modbus:
  uart_id: uart1
  id: modbus1
  #No flow control required because using UART/RS485 module
  #flow_control_pin: GPIO18 #marked as D18 on DOIT DEVKIT V1

modbus_controller:
  - id: sdm230m
    address: 0x01
    modbus_id: modbus1
    update_interval: 10s

sensor:
  - platform: sdm_meter
  
    phase_a:
      current:
        name: "ESP32.SDM230M Current"
      voltage:
        name: "ESP32.SDM230M Voltage"
      active_power:
        name: "ESP32.SDM230M Active Power (P)"
      apparent_power:
        name: "ESP32.SDM230M Apparent Power (S)"
      reactive_power:
        name: "ESP32.SDM230M Reactive Power (Q)"
      power_factor:
        name: "ESP32.SDM230M Power Factor"
      phase_angle:
        name: "ESP32.SDM230M Phase Angle"
        
    frequency:
      name: "ESP32.SDM230M Frequency"
    total_power:
      name: "ESP32.SDM230M Total Power"
    import_active_energy:
      name: "ESP32.SDM230M Import Active Energy"
    export_active_energy:
      name: "ESP32.SDM230M Export Active Energy"
    import_reactive_energy:
      name: "ESP32.SDM230M Import Reactive Energy"
    export_reactive_energy:
      name: "ESP32.SDM230M Export Reactive Energy"
    update_interval: 10s
```

### Anything in the logs that might be useful for us?

```txt
## I don't think that this is significant(?)
## I think it is just telling me that it has read what it was told to read....
## My uninformed suspicion is that we are looking at the wrong address?

[14:47:29][D][sdm_meter:069]: SDMMeter: F=49.903 Hz, Im.A.E=51.130 Wh, Ex.A.E=0.042 Wh, Im.R.E=1.152 VARh, Ex.R.E=30.087 VARh, T.P=0.000 W
[14:47:29][V][sensor:076]: 'ESP32.SDM230M Total Power': Received new state 0.000000
[14:47:29][D][sensor:127]: 'ESP32.SDM230M Total Power': Sending state 0.00000 W with 2 decimals of accuracy
[14:47:29][VV][api.service:140]: send_sensor_state_response: SensorStateResponse {
  key: 3161811911
  state: 0
  missing_state: NO
}

## Is this just because we are reading the whole block of 80 address...
## ... rather than just the ones we want? 
[14:47:29][V][component:199]: Component modbus took a long time for an operation (1.46 s).
[14:47:29][V][component:200]: Components should block for at most 20-30ms.
```

### Additional information

I can't find a datasheet or address map for the Eastron SDM230m V2.0.
This is my device: [SDM230M[Datasheet]May22.pdf](https://github.com/esphome/issues/files/9617425/SDM230M.Datasheet.May22.pdf)
This is my schematic:
![image](https://user-images.githubusercontent.com/14279344/191531243-fd279972-650a-4302-9bcf-b24bf787854e.png)
