### ISSUE TITLE
xtensa-lx106-elf-g++: fatal error

### ISSUE THREAD

**Issue by breimann** [esphome/issues#3603]
### The problem

I can no longer update or create a new device. This started happening about 2 weeks ago.

It only produces this error with esp8266 devices (of which most of mine are). I have one esp32 and this updates completely fine.

### Which version of ESPHome has the issue?

2022.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.6

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

components don't seem to fix it

### Example YAML snippet

```yaml
esphome:
  name: bathroom-sensor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "D7YAFzIYkcjZP8kL26xuFLKPcVI8g0EPY0gjGBS0Mus="

ota:
  password: "57b623f17f329506494254afdc12e58f"
  
sensor:
  - platform: dht
    pin: D7
    model: dht22
    temperature:
      name: "Bathroom Temp"
    humidity:
      name: "Bathroom Humidity"
    update_interval: 30s

binary_sensor:
  - platform: gpio
    pin: D6
    name: "Bathroom Motion"
    device_class: motion

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bathroom-Sensor Fallback Hotspot"
    password: "zXQna82DcjrH"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/kitchen-sensor.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing kitchen-sensor (board: nodemcuv2; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- NeoPixelBus @ 2.6.9
|   |-- SPI @ 1.0
Compiling /data/kitchen-sensor/.pioenvs/kitchen-sensor/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/kitchen-sensor/.pioenvs/kitchen-sensor/src/esphome/components/binary_sensor/automation.cpp.o
Compiling /data/kitchen-sensor/.pioenvs/kitchen-sensor/src/esphome/components/binary_sensor/filter.cpp.o
Compiling /data/kitchen-sensor/.pioenvs/kitchen-sensor/src/esphome/components/captive_portal/captive_portal.cpp.o
xtensa-lx106-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [/data/kitchen-sensor/.pioenvs/kitchen-sensor/src/esphome/components/api/api_frame_helper.cpp.o] Error 1
xtensa-lx106-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [/data/kitchen-sensor/.pioenvs/kitchen-sensor/src/esphome/components/binary_sensor/automation.cpp.o] Error 1
========================= [FAILED] Took 35.63 seconds =========================
```
