### ISSUE TITLE
ESPHome 2022.9.1 VL53 issue

### ISSUE THREAD

**Issue by REHolt** [esphome/issues#3605]
### The problem

After installing the 2022.9.1 update my VL53 TOF sensor stopped working.  All data is shown as "Unavailable". All I get is:

Level 1': Sending state nan in with 5 decimals of accuracy

Looks like there may be a I2C bus problem?

### Which version of ESPHome has the issue?

2022.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.6

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

VL53 

### Example YAML snippet

```yaml
switch:
  - platform: restart
    name: "TOF-Test Device Restart"

  # The relay control pin (local only)
  - platform: gpio
    name: "relay1"
    pin: GPIO17
    inverted: false
    id: relay1

i2c:
  - id: i2cbus
    sda: GPIO21 
    scl: GPIO22
    scan: True

sensor:    
  - platform: vl53l0x
    name: "Sensor 1"
    id: sens_1
    i2c_id: i2cbus
    address: 0x41
    enable_pin: GPIO05
    timeout: 200us
    update_interval: 500ms
    unit_of_measurement: "m"  
    accuracy_decimals: 5
    long_range: true
    signal_rate_limit: 0.3
    filters:
      # - calibrate_linear:
      #     # Map 2" (from sensor) to 34.5" (true value)
      #     - 0.0508 -> 0.0635
      #     - 0.2032 -> 0.227584
      #     - 0.8763 -> 0.75184
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1

  - platform: vl53l0x
    name: "Sensor 2"
    id: sens_2
    i2c_id: i2cbus
    address: 0x42
    enable_pin: GPIO19
    timeout: 200us
    update_interval: 500ms
    unit_of_measurement: "m"
    accuracy_decimals: 5
    long_range: true
    signal_rate_limit: 0.3
    filters:
      # - calibrate_linear:
      #     # Map 2" (from sensor) to 34.5" (true value)
      #     - 0.0508 -> 0.0635
      #     - 0.2032 -> 0.227584
      #     - 0.8763 -> 0.75184
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1

  - platform: template
    name: "Level 1"
    id: level1
    unit_of_measurement: "in"
    lambda: |-
      return ((id(sens_1).state * 39.370));
    accuracy_decimals: 5
    update_interval: 10s
    on_value_range:
        - below: 3
          then:
          - delay: .5min
          - switch.turn_off: relay1
        - above: 14
          then:
          - switch.turn_on: relay1

  - platform: template
    name: "Available Water"
    id: available_water
    unit_of_measurement: "gal"
    lambda: |-
      return (((32.75-(id(level1).state-2.14)) * 1.7));
    accuracy_decimals: 1
    update_interval: 10s
```
