### ISSUE TITLE
AC Dimmer only works with Framework: arduino

### ISSUE THREAD

**Issue by jrmurdoch** [esphome/issues#3621]
### The problem

This component seems to only work if framework: arduino is set, Using other modules such as ESP32-C3 require Framework: esp-idf. 

Can this module be converted to work over both frameworks?

### Which version of ESPHome has the issue?

2022.9.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

ESP32-C3

### Component causing the issue

ac_dimmer

### Example YAML snippet

```yaml
output:
  - platform: ac_dimmer
    id: dimmer1
    method: leading
    gate_pin: GPIO6
    zero_cross_pin:
      number: GPIO7
      mode:
        input: true
      inverted: yes

light:
  - platform: monochromatic
    output: dimmer1
    name: Dimmerized Light
```
