### ISSUE TITLE
device_class: volume editor says invalid

### ISSUE THREAD

**Issue by level451** [esphome/issues#3625]
### The problem

The editor does not allow for device_class: volume - but the link for available does show volume.

sensor:

  - platform: template
    id: shower_water_used_last_event
    name: 'Water (Last Event)'
    device_class: volume
    state_class: measurement
    unit_of_measurement: 'gal'

### Which version of ESPHome has the issue?

2022.9.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

node

### Example YAML snippet

```yaml
- platform: template
    id: shower_water_used_last_event
    name: 'Water (Last Event)'
    device_class: volume
    state_class: measurement
    unit_of_measurement: 'gal'
```
