### ISSUE TITLE
deep_sleep.prevent doesn't work after upgrade to v1.13

### ISSUE THREAD

**Issue by nicoolaro** [esphome/issues#363]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
HassOS 2.12
ESPHome 1.13.0
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 - Wemos mini d1
**Affected component:**

Capacitive soil sensor

**Description of problem:**
Capacitive solil sensor connected to Wemos and battery in deep sleep. Sending OTA retained message via MQTT prevented Wemos for going to deep sleep as per docs.
After upgraing to v1.30 it doesn work anymore.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: wemos_plantmonitor
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: ****
  password: ****

# Enable logging
logger:

ota:

# Enable Home Assistant API
#api:
mqtt:
  discovery: true
  discovery_prefix: homeassistant
  client_id: plantsensor_1
  broker: ******
  username: *****
  password: *****
  birth_message:
    topic: wemos_plantmonitor/plantsensorstatus
    payload: online
  will_message:
    topic: wemos_plantmonitor/plantsensorstatus
    payload: offline
  on_message:
    topic: wemos_plantmonitor/ota_mode
    then:
      - if:
          condition:
            lambda: 'return x == "ON";'
          then:
            - deep_sleep.prevent: deep_sleep_1
      - if:
          condition:
            lambda: 'return x == "OFF";'
          then:
            - deep_sleep.enter: deep_sleep_1

deep_sleep:
  id: deep_sleep_1
  #If it takes very long time for the API to connect we have some time
  run_duration: 30sec
  #Sleep for a year 8760h
  sleep_duration: 58min

switch:
  - platform: restart
    name: "Wemos_PlantMonitor_restart"

#Get information about the battery status, not yet implemented good enough
sensor:
  - platform: adc 
    pin: A0
    id: moisture
    update_interval: 5s
    internal: true 
    accuracy_decimals: 1
    filters:
      - lambda: |-
          if (x > 0.70) {
            return 0;
          } else if (x < 0.50) {
            return 100;
          } else {
            return (0.70-x) / (0.70-0.5) * 100.0;
          }
  - platform: template
    name: plant_1_saturation
    id: plant1
    unit_of_measurement: "% Saturation"
    icon: "mdi:water-percent"
    accuracy_decimals: 1
    lambda: |-
      return id(moisture).state;



```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

Worked before ugrade to v1.30, tried v1.31. same...
