### ISSUE TITLE
When wifi not available

### ISSUE THREAD

**Issue by alimnette** [esphome/issues#3635]
### The problem

When my wifi is not available sometimes my module restarts in AP mode which is expected.
however when the wifi comes back it does not reconnect to it on its own and there is no timeout on the ap mode

### Which version of ESPHome has the issue?

2022.9.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.7

### What platform are you using?

ESP8266

### Board

sonoff r2 mini

### Component causing the issue

WiFi Component

### Example YAML snippet

```yaml
wifi:
  ssid: !secret Wifi_SSID
  password: !secret Wifi_Password
  ap:
    ssid: $name-AP
    password: !secret Wifi_AP_Password
  domain: .domain.iot
```
