### ISSUE TITLE
INA219 integration shunt_resistance limitation to 32ohms

### ISSUE THREAD

**Issue by hugokernel** [esphome/issues#3638]
### The problem

It is not possible to set a `shunt_resistance` higher than 32 ohms but there is no reason to have this limitation

```python
            cv.Optional(CONF_SHUNT_RESISTANCE, default=0.1): cv.All(
                cv.resistance, cv.Range(min=0.0, max=32.0)
            ),
```

I currently use INA219 for a 4-20mA current sensing with a 100ohms shunt resistor to have a higher resolution (I have hotfixed the ESPHome INA219 integration to make it work).

### Which version of ESPHome has the issue?

*

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
[...]
sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 100ohm
    current:
      name: "INA219 Current"
    power:
      name: "INA219 Power"
    bus_voltage:
      name: "INA219 Bus Voltage"
    shunt_voltage:
      name: "INA219 Shunt Voltage"
    max_voltage: 32.0V
    max_current: 3.2A
[...]
```

### Anything in the logs that might be useful for us?

```txt
`value must be at most 32.0.`
```
