### ISSUE TITLE
Wifi issues

### ISSUE THREAD

**Issue by pittbull** [esphome/issues#3640]
I am flashing my m5stack from your webpage, and it works perfectly.

But if I take the yaml from your git and install it from my local esphome it fails to connect to the assigned wifi. I have 2 networks at home and even if I tell it to connect it to one, it connects to the other. (UDM is running the wifi).

Any insights?

**Comment by nagyrobi** [comment]
How do you configure those networks in the yaml?

How is your wifi system set up?

**Comment by pittbull** [comment]
I pulled the .yaml from here: https://github.com/esphome/bluetooth-proxies/

and changed the wifi part:

```
substitutions:
  name: atom-bluetooth-proxy
  wifi_ap_password: "" <--- removed this

esphome:
  name: ${name}
  name_add_mac_suffix: true
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

esp32:
  board: m5stack-atom
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid <----- added this
  password: !secret wifi_password <---- added this

api:
logger:
ota:
improv_serial:
captive_portal:

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic

```
The device does connect, but it does not connect to my secondary wifi (for iot devices). I tried multiple times, and even with two other fresh devices, but they all connect to my main wifi, and not the one specified in the yaml.

I have also tried specifying the name and password in the yaml, but same results.
