### ISSUE TITLE
platform remote_receiver - support of multiple RAW codes

### ISSUE THREAD

**Issue by erd82** [esphome/issues#3641]
### The problem

Hello,

I am having the same problem as discussed before here: https://github.com/esphome/issues/issues/1239

When I press the same button on any IR remote several times, the IR receiver captures different raw values each time.
To catch all the different raw values and trigger the same switch in Home Assistant each time, I could simply use the following code example:

```
binary_sensor:
  - platform: remote_receiver
    name: "TV On/Off Button"
    raw:
      code: [869, -914, 869, -913, 1757, -1802, 1757, -914, 867, -915, 866, -915, 867, -915, 867, -1804, 867, -914, 1757, -914, 867]
    filters:
      - delayed_off: 200ms
  - platform: remote_receiver
    name: "TV On/Off Button"
    raw:
      code: [870, -915, 1760, -913, 869, -1805, 1783, -891, 893, -890, 893, -890, 894, -890, 869, -1803, 868, -916, 1759, -914, 894]
    filters:
      - delayed_off: 200ms
  - platform: remote_receiver
    name: "TV On/Off Button"
    raw:
      code: [912, -890, 1785, -889, 893, -1779, 1785, -890, 893, -890, 894, -890, 893, -890, 893, -1783, 890, -890, 1784, -889, 894]
    filters:
      - delayed_off: 200ms
```
This always toggles the same switch on and off in Home Assistant independently from the received raw code.

It would be great if Esphome could support multiple raw values in one binary sensor - something like:
```
binary_sensor:
  - platform: remote_receiver
    name: "TV On/Off Button"
    raw:
      code: [869, -914, 869, -913, 1757, -1802, 1757, -914, 867, -915, 866, -915, 867, -915, 867, -1804, 867, -914, 1757, -914, 867]
      code: [870, -915, 1760, -913, 869, -1805, 1783, -891, 893, -890, 893, -890, 894, -890, 869, -1803, 868, -916, 1759, -914, 894]
      code: [912, -890, 1785, -889, 893, -1779, 1785, -890, 893, -890, 894, -890, 893, -890, 893, -1783, 890, -890, 1784, -889, 894]
    filters:
      - delayed_off: 200ms
```

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.7

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

remote_receiver

### Example YAML snippet

```yaml
remote_receiver:
  pin:
    number: GPIO02
    inverted: true
    mode: INPUT_PULLUP
  dump: all
  idle: 25ms

binary_sensor:
  - platform: remote_receiver
    name: "TV On/Off Button"
    raw:
      code: [869, -914, 869, -913, 1757, -1802, 1757, -914, 867, -915, 866, -915, 867, -915, 867, -1804, 867, -914, 1757, -914, 867]
    filters:
      - delayed_off: 200ms
  - platform: remote_receiver
    name: "TV On/Off Button"
    raw:
      code: [870, -915, 1760, -913, 869, -1805, 1783, -891, 893, -890, 893, -890, 894, -890, 869, -1803, 868, -916, 1759, -914, 894]
    filters:
      - delayed_off: 200ms
  - platform: remote_receiver
    name: "TV On/Off Button"
    raw:
      code: [912, -890, 1785, -889, 893, -1779, 1785, -890, 893, -890, 894, -890, 893, -890, 893, -1783, 890, -890, 1784, -889, 894]
    filters:
      - delayed_off: 200ms
```
