### ISSUE TITLE
esphome with bluetooth_proxy does not see advertisements from bluecharm ibeacon bc021

### ISSUE THREAD

**Issue by apaperclip** [esphome/issues#3642]
### The problem

I have a Bluecharm bc021 beacon and esphome does not see the ibeacon advertisements from the device. I noticed this first when the iBeacon was not showing in home assistant.  I opened an [issue](https://github.com/home-assistant/core/issues/79387) with HA core and was directed over here. I turned on verbose and very_verbos logging and do not see any messages for the iBeacons mac or uuid.

Here

### Which version of ESPHome has the issue?

2022.10-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.10.b4

### What platform are you using?

ESP32

### Board

quinled dig uno with ethernet and generic esp32 dev board (wifi)

### Component causing the issue

bluetooth_proxy

### Example YAML snippet
diguno w/ ethernet

```
substitutions:
  name: esp32-bluetooth-proxy-3f84d0

esphome:
  platform: ESP32
  board: mhetesp32minikit
  name: ${name}
  name_add_mac_suffix: false

# Enable logging
logger:
  level: very_verbose

# Enable Home Assistant API
api:

ota:


esp32_ble_tracker:
  scan_parameters:
    active: false

bluetooth_proxy:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO5
```

generic esp32 over wifi
```
substitutions:
  name: esp32-bluetooth-proxy-304420
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

logger:
  level: verbose 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password



esp32_ble_tracker:
  scan_parameters:
    active: false

bluetooth_proxy:
```

### Additional information

Here is the info I provided in the HA ticket

Additional information
- I confirmed the bluecharm is advertising in ibeacon format in the settings. All other advertisement formats are not enabled.
- A ble scanner on my phone sees the bluecharms advertisements
- I've tested with an ibeacon simulator app (beacon simulator) and it is discovered as expected.
- I have active scan set to false in esphome to conserve battery power on my various sensors. I tried it with true as well but there was no change in behavior.
- I have several Xiaomi LYWSD03MMC's that were setup on 2022.9 with one of these esp32s and bluetooth_proxy that are getting temp/humidity data.
- The ethernet attached esp32 has pretty clean logs but the wifi attached displays some buffer errors and timeouts (presumably due to volume of advertisements in the area, I'll open a separate issue for that)
- I do have regular advertisements disabled, the only time the bluecharm transmits is on motion, perhaps this is not in an ibeacon format? To test i changed it to advertise all the time and still not picked up.
- here is the raw data of the bluecharm advertisement from motion captured with the nRF connect app on my phone.
`0x0201061AFF4C000215426C7565436861726D426561636F6E740EFE1355C50916802063040EFE135506096C69646479`
