### ISSUE TITLE
E1.31 with Hyperion NG not working properly after the first universe

### ISSUE THREAD

**Issue by perebusquets** [esphome/issues#3643]
### The problem

According to the documentation, the recommendation (and I think the only one for now) to use HyperionNG with addressable lights is to use the E1.31 protocol. 

In my case, when using said protocol with HyperionNG with a 480 RGB LED strip and setting a static color, the LED strips change color every 170 LEDs (IE: first 170 in green, next 170 in blue, next 170 in red,...).

This make me suspicious that for some reason the data for one color gets skipped between universes, making the next set of 170 LEDs grab the wrong color, but I'm not an expert on that matter so please don't get fixated on that.

Example picture, the color is supposed to be all red:
![PXL_20221004_184615019](https://user-images.githubusercontent.com/43433557/193901149-60888327-7905-428f-b562-7b6e32a46042.jpg)

### Which version of ESPHome has the issue?

2022.9.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

e131

**Comment by rspenc29** [comment]
I'm experiencing this issue as well. Version 2022.12.2.

**Comment by contagon** [comment]
Just hit this same problem and agree I would love to stick with esphome for this rather than be forced to use WLED. Was this an issue ever opened on Hyperion.NG to notify them of this issue? Also just attempted with HyperHDR and it has the same bug

**Comment by contagon** [comment]
Upon some further digging, it appears the E1.31 protocol can only function with a maximum of 170 LEDs per universe. Per the [WLED docs](https://kno.wled.ge/interfaces/e1.31-dmx/):
> 170 LEDs (510 DMX channels) are supported per universe.

As a workaround, I've partitioned my LED into multiple entities each with a different universe, and then input each into Hyperion as a different instance. Here's an example:

```
e131:
  method: multicast

light:
  - platform: neopixelbus
    id: main_led
    type: GRB
    variant: WS2812
    pin: GPIO16
    num_leds: 231
    internal: True

  - platform: partition
    name: Top
    segments:
      - id: main_led
        from: 224
        to: 230
      - id: main_led
        from: 0
        to: 151
    effects:
      - e131:
          name: Hyperion
          universe: 1

  - platform: partition
    name: Bottom
    segments:
      - id: main_led
        from: 152
        to: 223
    effects:
      - e131:
          name: Hyperion
          universe: 2
```
