### ISSUE TITLE
Reconfigure intergration spam

### ISSUE THREAD

**Issue by jLynx** [esphome/issues#3655]
### The problem

I woke up this morning to HOmeAssistant spamming me with my same esphome device telling me I need to reconfigure it. This device has been working untouched for 6+ months. Now ass of a sudden I am getting these errors telling me I need to enter in the encryption key. The device was originally made without a key (When that was the default), but when I try and press ok on the modal without a key it says it requires one.
![image](https://user-images.githubusercontent.com/4393979/194393470-d035f70f-aa6a-4d8e-9e33-35ba9f072122.png)
![image](https://user-images.githubusercontent.com/4393979/194393503-1ca2f59f-41c7-4285-9ad0-b5a253541a3b.png)

### Which version of ESPHome has the issue?

2022.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.09.1

### What platform are you using?

ESP8266

### Board

D1

### Example YAML snippet

```yaml
esphome:
  name: door-bell
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "adb951e565fe0ee841f39800695aab67"

wifi:
  ssid: "Mothership"
  password: "AAAAAAAAAAAAAA"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Door-Bell Fallback Hotspot"
    password: "VRBq7lqrAvon"

captive_portal:

binary_sensor:
  - platform: gpio
    name: "Door bell pressed"
    pin:
      number: D2
      mode: INPUT_PULLUP
    filters:
      - delayed_off: 1000ms
```
