### ISSUE TITLE
ESP rgbww light goes out of sync

### ISSUE THREAD

**Issue by nicolasbisi** [esphome/issues#3660]
### The problem

I have 2 lights that are being seen by Home Assistant, and I use a helper to control them both at the same time.
I notice that my lights are getting out of sync, or losing their limits after a while.
One way to easily force it to happen is to enable an effect (always used Random)
Before the effect is used, when I move the slider to the warmest colour, we can see that all the values match.
<img width="1384" alt="Screen Shot 2022-10-07 at 1 34 51 PM" src="https://user-images.githubusercontent.com/976098/194444085-c2cf6b96-802c-4522-b455-9356d7451c0e.png">

I then turn the random effect on, wait a while, turn it off and set it to the warmest colour again.
<img width="1367" alt="Screen Shot 2022-10-07 at 1 36 12 PM" src="https://user-images.githubusercontent.com/976098/194444100-263c88a4-4d3d-4445-b148-b546cb1041c5.png">

Setting the light individually makes no difference. The only way to fix this problem and get them back in sync is to power the off and back on.
The same happens with the coldest colour. They don't match after using an effect.

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.0 (but have seen it before)

### What platform are you using?

ESP8266

### Board

ESP8285 DMP-L1

### Component causing the issue

Light

### Example YAML snippet

```yaml
output:
  - platform: esp8266_pwm
    id: output_cw
    pin: GPIO12
    min_power: 0.0001
    zero_means_zero: true
  
  - platform: esp8266_pwm
    id: output_ww
    pin: GPIO14
    min_power: 0.001
    zero_means_zero: true
  
  - platform: esp8266_pwm
    pin: GPIO04
    id: output_r
    min_power: 0.001
    zero_means_zero: true
  
  - platform: esp8266_pwm
    pin: GPIO13
    id: output_g
    min_power: 0.001
    zero_means_zero: true
  
  - platform: esp8266_pwm
    pin: GPIO05
    id: output_b
    min_power: 0.001
    zero_means_zero: true

light:
  - platform: rgbww
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
    default_transition_length: 0s
    restore_mode: ALWAYS_OFF
    color_interlock: true
    name: Living Room TV Light 01
    red: output_r
    green: output_g
    blue: output_b
    warm_white: output_ww
    cold_white: output_cw
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2000 K
```
