### ISSUE TITLE
ESPhome not interpreting unicode characters from MQTT correctly

### ISSUE THREAD

**Issue by JeroenTuinstra** [esphome/issues#3672]
### The problem

When receiving from Home Assistant via MQTT a text value with a unicode character like the following:

```
Pr\u00e9sident
```
Which should be 
```
Président
```
Howerver ESPhome displays it literally - ```Pr\u00e9sident```. With API it works fine, but with MQTT not. MQTT is needed because of deep-sleep, which is incompatible with API (API refreshed to little, only once per 60 seconds). 

MQTT explorer interprets the character correctly, ESPhome does not. Basically any text outside english will not be useable through MQTT. MQTT is needed because of deep-sleep, which is incompatible with API (API refreshed to little, only once per 60 seconds). 

```
state = Adcom - 11 October 2022 14:00
last_updated = 2022-10-08T22:01:35.296268+00:00
last_changed = 2022-10-08T22:01:35.296268+00:00
summary = "Adcom"
description = "\n"
location = "Bureau du Pr\u00e9sident"
start = "2022-10-11T14:00:00+02:00"
end = "2022-10-11T17:00:00+02:00"
eta = 3
all_day = false
icon = "mdi:calendar"
friendly_name = "Adcom"
```

### Which version of ESPHome has the issue?

2022.9.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.10.1

### What platform are you using?

ESP32

### Board

Waveshare e-Paper EsP32 Driver Board (ESP-WROOM-ESP32)

### Component causing the issue

text-sensor, display

### Example YAML snippet

```yaml
text_sensor:
  - platform: mqtt_subscribe
    id: test
    topic: homeassistant/sensor/ical_exchange_event_1/location

display: 
  - platform: waveshare_epaper
    cs_pin: 15
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 7.50inV2
    update_interval: 10s
    rotation: 90°
    lambda: |-
      it.printf(241, 408, id(arial), TextAlign::CENTER, "%s", id(test).state.c_str());
```
