### ISSUE TITLE
Pulse Meter can't keep up with ~6k pulses/min

### ISSUE THREAD

**Issue by Xnyle** [esphome/issues#3673]
### The problem

I'm using a YF-B1 Water Flow Sensor. This is producing ~ 6k or more pulses per minute (11 pulses per liter per min per sec)
I tested Pulse Meter and Pulse Counter:

Pulse Counter can keep up, but I couldn't get the edge detection work properly with internal filter and falling edge only.
Pulse Meter has a count mode PULSE, that seems to work fine if set to 13 us.
But the meter then maxes out at ~1000 pulses / min.
I already tried to use throttle_average in order to take load of the system and not send every pulse via MQTT, that seems to improve the situation a bit, but might also be wishful thinking on my side.

Question is, is ~1000 pulses / min a known restriction on the esp8266 or do I have the wrong idea what's happening?

### Which version of ESPHome has the issue?

2022.9.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

NodeMCU

### Component causing the issue

pulse_meter

### Example YAML snippet

```yaml
- platform: pulse_meter
    pin: GPIO5
    timeout: 1h
    name: "Valve Flow"
    id: "valve_pulse"
    accuracy_decimals: 2
    internal_filter: 13us
    internal_filter_mode: PULSE
    unit_of_measurement: 'l/min'
    filters:
      - throttle_average: 10s
      - heartbeat: 60s
      - filter_out: nan
      - multiply: 0.00151515151 # (11 pulses per l/s)
    total:
      unit_of_measurement: 'l'
      id: valve_volume
      accuracy_decimals: 2
      name: 'Valve Volume'
      filters:
        - throttle_average: 10s
        - heartbeat: 60s
        - filter_out: nan
        - multiply: 0.00151515151  # (1/660 pulses per l)
```

### Anything in the logs that might be useful for us?

```txt
not really, looks fine from the logs, seems to ignore pulses on the interrupt level or something
```
