### ISSUE TITLE
esp8266 - compiling ERROR in firmware.elf

### ISSUE THREAD

**Issue by varadujagan** [esphome/issues#3678]
### The problem

Today only I updated my ESPhome to v2022.9.4  from v2022.9.1

when I try to install the update to all my esp devices. I came into some errors.
I'm having 2 types of devices with me ESP32 and esp8266. ES32 was compiled and updated without any problem. But when i try to compile for esp8266 then only face the error.  

### Which version of ESPHome has the issue?

v2022.9.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.3

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

Compiling the program

### Example YAML snippet

```yaml
esphome:
  name: esp-test

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "sQzcpVgKmxz4etMY0ih/JtoqL4JDx7xK1jOEw0Qu5Vo="

ota:
  password: "6bfc5e7d5159d2ffec8c95b03d3263b8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Test Fallback Hotspot"
    password: "UxWJpoQzfxJ4"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esp-test.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp-test (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Linking /data/esp-test/.pioenvs/esp-test/firmware.elf
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
*** [/data/esp-test/.pioenvs/esp-test/firmware.elf] Error 1
========================== [FAILED] Took 1.35 seconds ==========================
```

### Additional information

I try to re-install the esphome addon but no use.  
other than compiling everything works well.
