### ISSUE TITLE
http_request automations do not support digest authentication

### ISSUE THREAD

**Issue by ashp8i** [esphome/issues#3679]
### The problem

```
on_...:
  - http_request.post:
      url: https://esphome.io
      headers:
        Content-Type: application/json
      json:
        key: value
      verify_ssl: false
  # Short form
  - http_request.post: https://esphome.io
```

do not support digest authentication

### Which version of ESPHome has the issue?

2022.9.4 or any release that supports http_request

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.3

### What platform are you using?

ESP32

### Board

Shelly Plus i4 (ESP32-U4WDH)

### Component causing the issue

Web Server

### Anything in the logs that might be useful for us?

I get a 401 on any node where I have enabled authentication, works fine on nodes which do not require web server authentication.
