### ISSUE TITLE
Airthings Wave Plus: reporting in 

### ISSUE THREAD

**Issue by rsachoc** [esphome/issues#3681]
### The problem

Hi there, I have the Airthings Wave Plus, which I have configured per the YAML. Everything appears to be working correctly, expect that the Radon level is reporting in Bq/m3 as a unit as opposed to what I expect which is pCi/L as a unit (believe pCi/L is the US and Bq/m3 is the Canadian unit). The Airthings is configured in the app (and confirmed in the web dashboard as reporting in pCi/L), but being reported by Esphome as Bq/m3. Any ideas how I can get the Airthings reporting into HA as pCi/L?

### Which version of ESPHome has the issue?

2022.10.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.10.3

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

Airthings

### Example YAML snippet

```yaml
esphome:
  name: airthings-ble-hub

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

web_server:

ota:
  password: "password"
  
wifi:
  ssid: FiOS-JIULI
  password: brave026cut5452put

  ap:
    ssid: "Airthings-Ble-Hub"
    password: "1234567890"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

sensor:
  - platform: airthings_wave_plus
    ble_client_id: airthings_plus_01
    update_interval: 5min # default
    temperature:
      name: "Airthings Wave Plus Temperature"
    radon:
      name: "Airthings Wave Plus Radon"
    radon_long_term:
      name: "Airthings Wave Plus Radon Long Term"
    pressure:
      name: "Airthings Wave Plus Pressure"
    humidity:
      name: "Airthings Wave Plus Humidity"
    co2:
      name: "Airthings Wave Plus CO2"
    tvoc:
      name: "Airthings Wave Plus VOC"

ble_client:
  - mac_address: 04:EE:03:BC:55:EF
    id: airthings_plus_01
```

### Additional information

![image](https://user-images.githubusercontent.com/9214280/195218666-934aa525-3d94-48a7-b153-4d5240499c89.png)
