### ISSUE TITLE
[1.13.2] [remote_receiver] All binary sensors trigger at once

### ISSUE THREAD

**Issue by elmurato** [esphome/issues#369]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

 Add-on version: 1.13.2
 You are running the latest version of this add-on.
 System: HassOS 2.12  (armv7 / raspberrypi3)
 Home Assistant version: 0.93.2
 Supervisor version: 165

**ESP (ESP32/ESP8266, Board/Sonoff):**

MagicHome RGB WiFi controller with IR sensor/remote (ESP8266)

**Affected component:**

https://esphome.io/components/remote_receiver.html?highlight=remote%20receiver#binary-sensor

**Description of problem:**
With 1.13.2 all configured remote_receiver binary sensors trigger at once when pressing only one button on the remote. Is there some unknown breaking change or is this a bug?

**Problem-relevant YAML-configuration entries:**
```yaml
binary_sensor:
  - platform: remote_receiver
    name: "Button UP"
    internal: True
    nec:
      address: 0x00FF
      command: 0x906F
    on_press:
      then:
        - light.dim_relative:
            id: light_rgb
            relative_brightness: 10% 
  - platform: remote_receiver
    name: "Button DOWN"
    internal: True
    nec:
      address: 0x00FF
      command: 0xB847
    on_press:
      then:
        - light.dim_relative:
            id: light_rgb
            relative_brightness: -10%
  - platform: remote_receiver
    name: "Button OFF"
    internal: True
    nec:
      address: 0x00FF
      command: 0xF807
    on_press:
      then:
        - light.turn_off: light_rgb
  - platform: remote_receiver
    name: "Button ON"
    internal: True
    nec:
      address: 0x00FF
      command: 0xB04F
    on_press:
      then:
        - light.turn_on: light_rgb
```

**Traceback (if applicable):**

```
n/a
```

**Additional information and things you've tried:**
With 1.12.x this worked without any issues. I also tried it only with the "ON" and "OFF" button configuration to see if the issue is related to light.dim_relative, but it's not. Same problem.
