### ISSUE TITLE
'Show api key' in Dashboard not working

### ISSUE THREAD

**Issue by RoboMagus** [esphome/issues#3697]
### The problem

I just found out this feature, but it appears to be broken.

Looking at the code for this the expected config format is too restricted. 
It looks for the _exactly_ the following match in the yaml config file, and as such reordering with e.g. the `password` key is not compatible.
```
api:
  encryption:
    key: 
```
It also seems to not allow retrieving keys from the  `secrets.yaml` file.

### Which version of ESPHome has the issue?

2022.10.x-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Board

-

### Component causing the issue

Dashboard

### Example YAML snippet

```yaml
api:
  password: !secret hass_api_password
  encryption:
    # Key cannot be retrieved from Dashboard
    key: !secret api_encryption_key
```

### Anything in the logs that might be useful for us?
When clicking on `show api key`, a popup shows:
```txt
Unable to automatically extract API key. Open the configuration and look for api:.
```
