### ISSUE TITLE
No all devices_class listed work, fail validation 

### ISSUE THREAD

**Issue by egranto** [esphome/issues#3698]
### The problem

When i use the some off the device clases added a few releases ago in Homeassistant seems they are not part of the new validation that makes the new editor 
even on the error we had a link 
![1](https://user-images.githubusercontent.com/60528368/196032271-a36b2505-11ab-4856-8ef9-ebb045d99d9b.PNG)
But is clear on the HA table we could use more clases
![2](https://user-images.githubusercontent.com/60528368/196032335-7811ac44-8f74-4361-bfe9-10d7f4a47ae5.PNG)
and won't compile then 
![3](https://user-images.githubusercontent.com/60528368/196032423-de4d2d1c-d2c3-4270-aba2-66b10bbd2f3c.PNG)

### Which version of ESPHome has the issue?

2022.9.X

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.3

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

editor

### Example YAML snippet

```yaml
- platform: pulse_counter
    pin: D6 
    id: pulsoRX
    name: "${upper_devicename} Filament Used Counter"
    update_interval: 60s
    total:
      name: '${upper_devicename} Int Total Pulsos D3'

  - platform: template
    name: "${upper_devicename} Filament Used"
    id: flowRX
    lambda: |-
      return id(pulsoRX).state*100; 
    unit_of_measurement: 'mm/min'
    filters:  
      - calibrate_linear:
        - 100 -> 11
        - 0 -> 0
    accuracy_decimals: 3
    icon: "mdi:cog-counterclockwise"
    update_interval: 60s
    
  - platform: integration
    name: "${upper_devicename} Filament Used Total"
    id: Print
    sensor: flowRX
    time_unit: min  
    accuracy_decimals: 3
    device_class: distance
    unit_of_measurement: "mm"
    force_update: true

  - platform: integration
    name: "${upper_devicename} Filament Used Daily"
    id: Diario
    sensor: flowRX
    time_unit: min  
    device_class: distance
    accuracy_decimals: 3
    unit_of_measurement: "mm"
    force_update: true   
    restore: true
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/dora3d-tools.yaml...
INFO Detected timezone 'America/Costa_Rica'
Failed config

sensor.integration: [source /config/esphome/dora3d-tools.yaml:276]
  platform: integration
  name: Dora3D Filament Used Total
  id: Print
  sensor: flowRX
  time_unit: min
  accuracy_decimals: 3
  
  Unknown value 'distance', valid options are '', 'apparent_power', 'aqi', 'battery', 'carbon_dioxide', 'carbon_monoxide', 'current', 'date', 'duration', 'energy', 'frequency', 'gas', 'humidity', 'illuminance', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'pm1', 'pm10', 'pm25', 'power', 'power_factor', 'pressure', 'reactive_power', 'signal_strength', 'sulphur_dioxide', 'temperature', 'timestamp', 'volatile_organic_compounds', 'voltage'.
  device_class: distance
  unit_of_measurement: mm
  force_update: True
sensor.integration: [source /config/esphome/dora3d-tools.yaml:286]
  platform: integration
  name: Dora3D Filament Used Daily
  id: Diario
  sensor: flowRX
  time_unit: min
  
  Unknown value 'distance', valid options are '', 'apparent_power', 'aqi', 'battery', 'carbon_dioxide', 'carbon_monoxide', 'current', 'date', 'duration', 'energy', 'frequency', 'gas', 'humidity', 'illuminance', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'pm1', 'pm10', 'pm25', 'power', 'power_factor', 'pressure', 'reactive_power', 'signal_strength', 'sulphur_dioxide', 'temperature', 'timestamp', 'volatile_organic_compounds', 'voltage'.
  device_class: distance
  accuracy_decimals: 3
  unit_of_measurement: mm
  force_update: True
  restore: True
```

### Additional information

looks like the options in ESPHOME are hardcoded, if HA team add more devices clases looks like they are not be added on the same time to esphome validator, not a big deal but could be nice to had, more to change the unit of measurement "on the fly"
