### ISSUE TITLE
HLW8012 / BL0937 / CSE7759: Power != V*I

### ISSUE THREAD

**Issue by beveradb** [esphome/issues#37]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io on Raspberry Pi

**ESP (ESP32/ESP8266/Board/Sonoff):**

ESP8285, inside "Slitinto" / NX-SM110 smart plug ([PCB photos here](https://photos.app.goo.gl/ideYzXKV3By36xueA))

**Affected component:**

[HLW8012](https://esphomelib.com/esphomeyaml/components/sensor/hlw8012.html)

**Description of problem:**
I spent a while tweaking the `current_resistor` and `voltage_divider` settings to try and get realistic values, and eventually found values which show the Voltage and Power correctly (I'm using a heating element and multimeter to test, and also comparing with the values recorded by Tasmota).

However, for some reason the Current value is still off, and in fact doesn't even make sense given that the Power and Voltage values are correct - I'd have assumed Power was simply V*I but in this case I seem to have a correct Voltage and Power value but incorrect Current.

I own 8 of these plugs, and the issue is the same for all of them if I use the same YAML (below), so it's not an issue with an individual plug.

Here is an example of the ESPHome log entries the device outputs:
```
[21:16:20][D][sensor.hlw8012:067]: Got power=671.3W, current=8.4A
[21:16:40][D][sensor.hlw8012:075]: Got power=672.3W, voltage=228.2V
[21:17:00][D][sensor.hlw8012:067]: Got power=674.5W, current=8.3A
[21:17:20][D][sensor.hlw8012:075]: Got power=677.0W, voltage=228.4V
[21:17:40][D][sensor.hlw8012:067]: Got power=678.6W, current=8.4A
[21:18:00][D][sensor.hlw8012:075]: Got power=679.1W, voltage=230.3V
```
during this test, that 8.4A value should actually be 2.96A.

I'm happy to have a poke around in the ESPHomeLib code to try and understand how this is supposed to work and how it can be possible that I'm getting values which don't follow P=V*I, but I thought I'd ask here in case you had any idea.

It's worth noting that this chipset is the HJL-01/BL0937-based one, which gets special treatment in Tasmota. If you take a look at [xnrg_01_hlw8012.ino](https://github.com/arendst/Sonoff-Tasmota/blob/master/sonoff/xnrg_01_hlw8012.ino#L179), there's a `hlw_model_type` which varies the default reference values significantly.

For now this is usable for rough power usage monitoring, but I don't have a huge amount of confidence in the values and would love to try and improve ESPHome to have proper support for these devices!

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO03
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: 0.002452
    voltage_divider: 922
    current:
      name: "Heating Switch Current"
      unit_of_measurement: A
    voltage:
      name: "Heating Switch Voltage"
      unit_of_measurement: V
    power:
      name: "Heating Switch Power"
      id: switch_power
      unit_of_measurement: W
    change_mode_every: 1
    update_interval: 1s
```

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by beveradb** [comment]
Thanks for the prompt and informative response @OttoWinter, much appreciated!

Hmm, I'm still a bit confused - I thought the SEL pin toggled the CF1 pin output between Voltage and Current. I'll do some more reading.
I've actually got a Sonoff Pow too, so I'll do some testing with that first to understand how the HLW8012 component in ESPHome is _supposed_ to work.
Then I'll see if I can identify the correct resistors on the board to measure the values with a multimeter, both on my Sonoff Pow and on the NX-SM110 board.

**Comment by OttoWinter** [comment]
> I thought the SEL pin toggled the CF1 pin output between Voltage and Current.

You are correct :)

**Comment by beveradb** [comment]
Hmm, so I've just flashed my Sonoff Pow with ESPHome and I'm still getting weird values:

My test setup is using a lamp with LED bulb which draws a pretty consistent 0.022A at mains voltage (currently 236V), for a power usage of 5.2W:

![image](https://user-images.githubusercontent.com/757713/52481181-b521cc00-2ba5-11e9-991c-b8fc343326a1.png) ![image](https://user-images.githubusercontent.com/757713/52481193-b81cbc80-2ba5-11e9-8bf9-8b64e3bff022.png)


With the following YAML (`current_resistor` and `voltage_divider` as [suggested in the docs page](https://esphome.io/components/sensor/hlw8012.html))

```
sensor:
  - platform: hlw8012
    sel_pin: GPIO05
    cf_pin: GPIO14
    cf1_pin: GPIO13
    current_resistor: 0.001
    voltage_divider: 2351
    current:
      name: "Current"
      unit_of_measurement: A
    voltage:
      name: "Voltage"
      unit_of_measurement: V
    power:
      name: "Power"
      unit_of_measurement: W
    change_mode_every: 1
    update_interval: 10s
```

it seems to get the power usage right (from the CF pin, I guess), and the voltage and current are close but not quite accurate :

```
[13:39:27][D][sensor.hlw8012:075]: Got power=5.2W, voltage=217.0V
[13:39:47][D][sensor.hlw8012:067]: Got power=5.2W, current=0.1A
[13:40:07][D][sensor.hlw8012:075]: Got power=5.2W, voltage=217.8V
[13:40:27][D][sensor.hlw8012:067]: Got power=5.2W, current=0.1A
```

How did you identify which resistor(s) on the PCB are relevant to measure? Even on the Sonoff Pow which has a much more spaced-out board, I'm not really sure what to look for (I actually can't even find the HLW8012 chip on this!):

![image](https://user-images.githubusercontent.com/757713/52481801-71c85d00-2ba7-11e9-9e2f-da2bcc3a1ed4.png)
