### ISSUE TITLE
ERROR Circular dependency detected! After upgrade to 1.13.0. Can't compile.

### ISSUE THREAD

**Issue by MarekLe** [esphome/issues#370]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip on windows.

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 NODEMCU

**Affected component:**

**Description of problem:**
After upgrade to 1.13.0 can't compile configuration.
I got this error:
c:\Arduino\HA\GIT\ESPHome\Akwarium>esphome Akwarium.yaml compile
[32mINFO Reading configuration...[0m
[32mINFO Generating C++ source...[0m
[31mERROR Circular dependency detected![0m

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
substitutions:
  devicename: akwarium
  upper_devicename: "Test"
  ip_end: "202"
  
  param_czas_pompowania: "480s"
  #param_czas_pompowania: "10s"
  param_temp_graniczna_zasobnika: "25.0"
  
esphome:
  name: ${devicename} 
  platform: ESP8266
  board: nodemcu

web_server:
  port: 80

wifi:
  networks:
  - ssid: "ML-WIFI_Down"
    password: "4android" 

  manual_ip:
    static_ip: "192.168.1.${ip_end}"
    gateway: 191.168.1.1
    subnet: 255.255.255.0
  #use_address: 192.168.1.106

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'password'

ota:
  password: 'password'

dallas:
  - pin: GPIO14

light:
  - platform: binary
    name: "Swiatło w akwarium"
    output: output_light

output:
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
    id: output_light
    
sensor:
  - platform: dallas
    address: 0x070416C0D2C4FF28
    name: "Akwarium - temp. zasobnik"
    id: temp_zasobnik

  - platform: dallas
    address: 0xDB0316B4966DFF28
    name: "Akwarium - temp. zbiornik"
    id: temp_akwarium

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: false
    name: "Akwarium - zasobnik pełny"
    id: zasobnik_pelny
    on_press:
      then:
        # KONIEC NAPEŁNIANIA -> KONIEC PODMIANY
        - switch.turn_off: podmiana
        - switch.turn_off: dolewka
        - switch.turn_off: zawor

switch:
  - platform: gpio
    pin:
      number: GPIO05
      inverted: true
    name: "Akwarium - pompa"
    id: pompa
    restore_mode: ALWAYS_OFF
    on_turn_off:
      then:
        - if:
            condition:
              and:
                - switch.is_on: podmiana
                - binary_sensor.is_off: zasobnik_pelny
                # SKOŃCZYŁ POMPOWAĆ TO NAPEŁNIAMY
            then:
              - switch.turn_on: zawor
              - switch.turn_off: grzalka
        - if:
            condition:
              and:
                - binary_sensor.is_on: zasobnik_pelny
                # SYTUACJA BŁĘDNA!!! PRZERYWAMY!!!
            then:
              - switch.turn_off: podmiana
              - script.stop: podmiana_script
              - switch.turn_off: zawor
              - switch.turn_off: grzalka
              - switch.turn_off: pompa
        
  - platform: gpio
    pin:
      number: GPIO04
      inverted: true
    name: "Akwarium - ogrzewanie zasobnika"
    id: grzalka
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin:
      number: GPIO00
      inverted: true
    name: "Akwarium - zawór"
    id: zawor
    restore_mode: ALWAYS_OFF
  - platform: template
    optimistic: true
    name: "Akwarium - dolewka wody"
    id: dolewka
    on_turn_on:
      then:
        - switch.turn_off: podmiana
        - script.execute: stop_all
        - switch.turn_on: pompa
        - delay: 30s
        - switch.turn_off: pompa
        - switch.turn_off: dolewka
        - if:
            condition:
              and:
                - binary_sensor.is_off: zasobnik_pelny
            then:
              - switch.turn_on: zawor
    on_turn_off:
      then:
        - switch.turn_off: podmiana
        - script.execute: stop_all
  - platform: gpio
    pin: GPIO02
    name: "Akwarium - podmiana wody"
    id: podmiana
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - script.execute: podmiana_script
    on_turn_off:
        - script.execute: stop_all

script:
  - id: podmiana_script
    then:
      - while:
          condition:
            - switch.is_on: podmiana
          then:
          - if:
              condition:
                and:
                  - switch.is_on: podmiana
                  - sensor.in_range:
                      id: temp_zasobnik
                      below: ${param_temp_graniczna_zasobnika}
                  - binary_sensor.is_on: zasobnik_pelny
              then:
                - switch.turn_on: grzalka
              else:
                - switch.turn_off: grzalka
          - if:
              condition:
                and:
                  - switch.is_on: podmiana
                  - sensor.in_range:
                      id: temp_zasobnik
                      above: ${param_temp_graniczna_zasobnika}
                  - binary_sensor.is_on: zasobnik_pelny
              then:
                - script.execute: pompa_on_for
          - if:
              condition:
                and:
                  - switch.is_on: podmiana
                  - binary_sensor.is_off: zasobnik_pelny
                  - switch.is_off: pompa
              then:
                - switch.turn_on: zawor
          - delay: 5s

  - id: pompa_on_for
    then:
      - switch.turn_on: pompa
      - delay: ${param_czas_pompowania}
      - switch.turn_off: pompa

  - id: stop_all
    then:
        - script.stop: podmiana_script
        - switch.turn_off: zawor
        - switch.turn_off: grzalka
        - switch.turn_off: pompa

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
