### ISSUE TITLE
Sensor, Unable to find action with the name 'above'. 

### ISSUE THREAD

**Issue by MityaDVG** [esphome/issues#3701]
### The problem

In the sensor code, I started adding to turn on the above values, and when the value turned off the corresponding output. I did everything according to the documentation [https://esphome.io/components/sensor/index.html#sensor-on-value-range](url) but gives the following error as in the screenshot
![Screenshot 2022-10-17 170559](https://user-images.githubusercontent.com/90910957/196203822-36551dc9-8cdb-4692-b975-33f05c6b210e.png)

### Which version of ESPHome has the issue?

2022.9.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.4

### What platform are you using?

ESP32

### Board

wroom

### Component causing the issue

dallas

### Example YAML snippet

```yaml
dallas:
  - pin: 32
    id: otoplenie
  - pin: 33
    id: hot_wather

sensor:
  - platform: dallas
    dallas_id: otoplenie
    address: 0xd25b15b20164ff28
    name: "t_tvkotel_pod"
    id: t_tvkotel_pod
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 24.4 -> 24.4
    on_value_range:
      - above: 35
        then:
          - switch.turn_on: r4_pumb_tvkotel   
      - below: 34
        for:
          time: 5min
        then:
          - switch.turn_off: r4_pumb_tvkotel
```
