### ISSUE TITLE
PMSX003 update_interval errors

### ISSUE THREAD

**Issue by grucha532** [esphome/issues#3702]
### The problem

The update_interval does not work with PMS using the same syntax as with DHT22. I've tried a lot: with 'ms','s', without anything but number.

Without interval, everything works fine but the default interval is 1 sec, I guess...

Is there a way to set up an interval?

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.7

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

PMSX003

### Example YAML snippet

```yaml
# PMS7003
uart:
  rx_pin: 5
  tx_pin: 4
  baud_rate: 9600

sensor:

# DHT22
  - platform: dht
    pin: 13
    temperature:
      name: "Hall Temperature"
    humidity:
      name: "Hall Humidity"
    update_interval: 60s

# PMS7003
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
    update_interval: 60000ms
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esp-smogomierz.yaml...
Failed config

sensor.pmsx003: [source /config/esphome/esp-smogomierz.yaml:45]
  platform: pmsx003
  type: PMSX003
  pm_1_0: 
    name: Particulate Matter <1.0µm Concentration
  pm_2_5: 
    name: Particulate Matter <2.5µm Concentration
  pm_10_0: 
    name: Particulate Matter <10.0µm Concentration
  
  [update_interval] is an invalid option for [sensor.pmsx003]. Please check the indentation.
  update_interval: 60000ms [source /config/esphome/esp-smogomierz.yaml:53]
```
