### ISSUE TITLE
ESP32-Cam not compiling

### ISSUE THREAD

**Issue by SPYUK** [esphome/issues#3703]
### The problem

INFO Reading configuration /config/esphome/esp32cam.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/esp32cam
Processing esp32cam (board: esp32cam; framework: arduino; platform: espressif32@1.12.4)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10004.200129 (1.0.4) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa32 2.50200.80 (5.2.0)
Looking for AsyncTCP-esphome library in registry
Conflict: More than one library has been found by request {"name": "AsyncTCP-esphome", "requirements": "1.1.1"}:
AsyncTCP-esphome
================
#ID: 12172
Asynchronous TCP Library for ESP32

Keywords: async, tcp
Compatible frameworks: Arduino
Compatible platforms: Espressif 32, LibreTuya
Authors: Hristo Gochkov

AsyncTCP-esphome
================
#ID: 6798
Asynchronous TCP Library for ESP32

Keywords: async, tcp
Compatible frameworks: Arduino
Compatible platforms: Espressif 32
Authors: Hristo Gochkov

Automatically chose the first available library (use `--interactive` option to make a choice)
LibraryManager: Installing id=12172 @ 1.1.1
UndefinedPackageVersion: Could not find a version that satisfies the requirement '1.1.1' for your system 'linux_x86_64':
  File "/usr/local/lib/python3.6/dist-packages/platformio/builder/main.py", line 168:
    env.SConscript("$BUILD_SCRIPT")
  File "/root/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/root/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 286:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/root/.platformio/platforms/espressif32/builder/main.py", line 223:
    target_elf = env.BuildProgram()
  File "/root/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/platformio/builder/tools/platformio.py", line 62:
    env.ProcessProjectDeps()
  File "/root/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/platformio/builder/tools/platformio.py", line 131:
    project_lib_builder = env.ConfigureProjectLibBuilder()
  File "/root/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/platformio/builder/tools/piolib.py", line 1036:
    project.install_dependencies()
  File "/usr/local/lib/python3.6/dist-packages/platformio/builder/tools/piolib.py", line 868:
    lm.install(uri)
  File "/usr/local/lib/python3.6/dist-packages/platformio/managers/lib.py", line 281:
    force=force,
  File "/usr/local/lib/python3.6/dist-packages/platformio/managers/package.py", line 704:
    pkg_dir = self._install_from_piorepo(name, requirements)
  File "/usr/local/lib/python3.6/dist-packages/platformio/managers/lib.py", line 119:
    requirements or "latest", util.get_systype()
========================== [FAILED] Took 0.77 seconds ==========================

### Which version of ESPHome has the issue?

1.15.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.0

### What platform are you using?

ESP32

### Board

https://www.aliexpress.com/item/1005002259815873.html?spm=a2g0o.order_detail.0.0.1a51f19chvuwtn

### Component causing the issue

ESP32-Cam

### Example YAML snippet

```yaml
esphome:
  name: esp32cam
  platform: ESP32
  board: esp32cam

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Cam Fallback Hotspot"
    password: "QR55b8vZoufa"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: ESP-32 Cam
  # ...
```

### Anything in the logs that might be useful for us?

```txt
nothing
```

### Additional information

Board should work as AI Thinker
