### ISSUE TITLE
Total number of pulses not persistent for Pulse Counter Sensor

### ISSUE THREAD

**Issue by Bascht74** [esphome/issues#3707]
### The problem

I am using the pulse counter sensor for my gas meter. 
I used the pulse_counter.set_total_pulses service to set the total value to match my gas meter. 

If I install an ESPHome update the total value will be resetted. 
Even that the ESP32 has the possibilty to store the data persistent this is not used or offered. 

If the meter is reset and I use the pulse_counter.set_total_pulses service again the results in Home Assistant on the energy dashboard and my helper entites are strange, because they regocnize a strong gain von 0 to the high number I entered. 

Can this be corrected? 
I would be great if the integration can store the total number like the gobal variables do. The persistant storage of the total counter could be an optional parameter for the sensor.
I don't know if that would be possible on ESP8266 but Tasmota does store energy sums as well and they survive a reboot / firmware upgrade.

If that isn't an error but more like an feature request, please let me know. 
As a work-a-round I am wondering if I could store the total numer of pulses in a global variable and restore it on boot of the device? 

### Which version of ESPHome has the issue?

2022.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

not relevant

### What platform are you using?

ESP32

### Board

not relevant

### Component causing the issue

Pulse Counter Sensor

### Example YAML snippet

```yaml
sensor:
  - platform: pulse_counter
    id: gasverbrauch_aktuell
    name: "Gasverbrauch aktuell"
    pin:
      number: GPIO25
      mode:
        input: true
        pulldown: true
    count_mode:
      rising_edge: Increment
      falling_edge: Disable
    use_pcnt: true
    unit_of_measurement: "m³"
    state_class: "measurement"
    device_class: "gas"
    filters:
      - multiply: 0.01
    total:
      name: "Gasverbrauch gesamt"
      id: gasverbrauch_gesamt
      # persistent: true <- something like this would be very helpfull
      unit_of_measurement: "m³"
      state_class: "total_increasing"
      device_class: "gas"
      accuracy_decimals: 2
      filters:
        - multiply: 0.01
```

### Anything in the logs that might be useful for us?

```txt
./.
```

### Additional information

Great integration by the way. I really like the pulse_counter integration!
