### ISSUE TITLE
Strobe Effect Expected Color Temperature with unit, got 100%.

### ISSUE THREAD

**Issue by SamPhoenix91** [esphome/issues#3710]
### The problem

When trying to make a strobe effect including colour temperature;

`          colors:
            - state: true
              brightness: 100%
              color_temperature: 100%
              duration: 1s
`

It reports "Expected Color Temperature with unit, got 100%."
It happens with any percentage as far as I can tell and I cannot work out what input it will accept

### Which version of ESPHome has the issue?

v2022.9.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.1

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

light (hbridge)

### Example YAML snippet

```yaml
effects:
      - random:
      - strobe:
          name: Alternate
          colors:
            - state: true
              brightness: 100%
              color_temperature: 100%
              duration: 1s
            - state: true
              brightness: 100%
              color_temperature: 0%
              duration: 1s
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/light-test.yaml...
Failed config

light.hbridge: [source /config/esphome/light-test.yaml:58]
  platform: hbridge
  id: mainlight
  name: Hbridge Lights
  pin_a: pina
  pin_b: pinb
  effects: 
    - random: {}
    - strobe: 
        name: Alternate
        colors: 
          - state: True
            brightness: 100%
            
            Expected Color Temperature with unit, got 100%.
            color_temperature: 100%
            duration: 1s
          - state: True
            brightness: 100%
            color_temperature: 0%
            duration: 1s
    - strobe: 
    - lambda: 
        name: Breathing
        update_interval: 4s
        lambda: |-
          static int state = 0;
          static int color = 1;
          auto call = id(mainlight).turn_on(); //the id of your light
          call.set_transition_length(3000);
          if (state == 0) 
          {
          call.set_brightness(1.0);
          }
          else if (state == 1)
          {
          call.set_brightness(0.01);
          }
          call.perform();
          state ++;
          if (state == 2){
          state = 0;
          }
```
