### ISSUE TITLE
Assigning static IP wirelessly does not work

### ISSUE THREAD

**Issue by Zocker1999NET** [esphome/issues#3714]
### The problem

ESPHome loses access to the ESP32 when adding a "static_ip" to the config without rolling it out. It found the ESP before by using mDNS. When removing the static_ip config part, (I assume) Dashboard cannot find the ESP again.
*EDIT: In my case, the dashboard found the ESP again without restarting the Dashboard, but most probably because the ESP rebooted due to API inactivity and the DHCP server also knows about its static IP so the IP will not be assigned to another device.*

It could be really helpful if ESPHome Dashboard could fallback to mDNS discovery if the ESP cannot be reached by its static IP so it is possible to rollout a static IP configuration wireless.

Due to an issue with another ESP8266, I run ESPHome Dashboard with `ESPHOME_DASHBOARD_USE_PING=true`, but that didn't prevent the dashboard from detecting the ESP32 without a static IP.

### Which version of ESPHome has the issue?

2022.10.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

nodemcu v2

### Example YAML snippet

```yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # manual IP (stored in FB)
  manual_ip:
    static_ip: 10.11.11.84
    gateway: 10.11.11.1
    subnet: 255.255.255.0
    dns1: 10.11.11.10
```

**Comment by Fischelsberger** [comment]
You normally need to add "use_address" [see here](https://esphome.io/components/wifi.html#:~:text=server%20to%20use.-,use_address,-(Optional%2C%20string)).

so it should be like:
```yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # manual IP (stored in FB)
  use_address: the.old.ip.address
  manual_ip:
    static_ip: 10.11.11.84
    gateway: 10.11.11.1
    subnet: 255.255.255.0
    dns1: 10.11.11.10
```
Just compile and upload it afterwards.
After the Device is connected again you need to remove "use_address" again and need to reupload it again.
