### ISSUE TITLE
ESP32-C3-WROOM-02-N4 not woring

### ISSUE THREAD

**Issue by wunyee** [esphome/issues#3716]
### The problem

I'm testing ESP32-C3-WROOM-02-N4, connect 10uF to 3.3v and 10K pullup gpio2 ,8 ,9
download esphome from home assistant esphome addon webui
not add any component but it not booting

### Which version of ESPHome has the issue?

2022.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2022.10.5

### What platform are you using?

ESP32

### Board

ESP32-C3-WROOM-02-N4

### Component causing the issue

None

### Example YAML snippet

```yaml
esphome:
  name: test
  platformio_options:
    board_build.flash_mode: dio  
esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "68b64a6330bc2c4b3b47ce5aca4915f1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "rUMCwmAUUZCb"
```

### Anything in the logs that might be useful for us?

```txt
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0xd (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x19a0
load:0x403ce000,len:0x8d4
load:0x403d0000,len:0x2dc0
entry 0x403ce000
I (30) boot: ESP-IDF 4.3.2 2nd stage bootloader
I (30) boot: compile time 18:37:29
I (30) boot: chip revision: 3
I (32) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (39) boot.esp32c3: SPI Speed      : 80MHz
I (44) boot.esp32c3: SPI Mode       : DIO
I (48) boot.esp32c3: SPI Flash Size : 4MB
I (53) boot: Enabling RNG early entropy source...
I (58) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (77) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (84) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (92) boot:  3 app0             OTA app          00 10 00010000 001c0000
I (99) boot:  4 app1             OTA app          00 11 001d0000 001c0000
I (107) boot: End of partition table
I (111) boot: No factory image, trying OTA 0
I (116) boot_comm: chip revision: 3, min. application chip revision: 0
I (123) esp_image: segment 0: paddr=00010020 vaddr=3c090020 size=1b8e0h (112864) map
I (149) esp_image: segment 1: paddr=0002b908 vaddr=3fc8de00 size=031f8h ( 12792) load
I (151) esp_image: segment 2: paddr=0002eb08 vaddr=40380000 size=01510h (  5392) load
I (155) esp_image: segment 3: paddr=00030020 vaddr=42000020 size=813b4h (529332) map
I (242) esp_image: segment 4: paddr=000b13dc vaddr=40381510 size=0c764h ( 51044) load
I (252) esp_image: segment 5: paddr=000bdb48 vaddr=50000000 size=00010h (    16) load
I (256) boot: Loaded app from partition at offset 0x10000
I (298) boot: Set actual ota_seq=1 in otadata[0]
I (298) boot: Disabling RNG early entropy source...
I (309) cpu_start: Pro cpu up.
I (321) cpu_start: Pro cpu start user code
I (321) cpu_start: cpu freq: 160000000
I (322) cpu_start: Application information:
I (324) cpu_start: Project name:     c3test
I (329) cpu_start: App version:      2022.10.0
I (334) cpu_start: Compile time:     Oct 22 2022 18:37:01
I (340) cpu_start: ELF file SHA256:  c0ca18b8e35d91bc...
I (346) cpu_start: ESP-IDF:          4.3.2
I (351) heap_init: Initializing. RAM available for dynamic allocation:
I (358) heap_init: At 3FC95890 len 0002A770 (169 KiB): DRAM
I (364) heap_init: At 3FCC0000 len 0001F060 (124 KiB): STACK/DRAM
I (371) heap_init: At 50000010 len 00001FF0 (7 KiB): RTCRAM
I (378) spi_flash: detected chip: generic
I (382) spi_flash: flash io: dio
I (387) sleep: Configure to isolate all GPIO pins in sleep state
Terminal disconnected: FramingError: A framing error has been detected.
```
