### ISSUE TITLE
cse7766 not working after 1.13.2 update

### ISSUE THREAD

**Issue by bwanajag** [esphome/issues#373]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

hass.io 0.93.2
**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff POW R2
**Affected component:**

https://esphome.io/components/sensor/cse7766.html

**Description of problem:**
After compiling 1.13.2 and uploading, it streams the following
[16:57:44][W][cse7766:058]: Invalid checksum from CSE7766: 0x11 != 0x72

**Problem-relevant YAML-configuration entries:**
```yaml
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: "NPM Current"
    voltage:
      name: "NPM Voltage"
    power:
      name: "NPM Power"

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
