### ISSUE TITLE
Will not http_request POST when in wifi_component AP Mode

### ISSUE THREAD

**Issue by PatientLightning** [esphome/issues#3738]
### The problem

The http_request component will not send a POST request when the wifi_component is in Access Point Mode.

I would like to send an http_request to a client of the node when in AP mode, but it seems the request will not POST because the http_request component believes there is no network.
On the contrary, there is absolutely a network. The node is in AP mode and hosting it, and I can connect multiple clients and reach them all from each other.

Is there a setting where I can tell http_request to send in AP mode?

Thanks!

### Which version of ESPHome has the issue?

2022.10.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

ESP-WROOM-32 DEV KIT

### Component causing the issue

http_request

### Example YAML snippet

```yaml
wifi:
  #don't bother rebooting
  reboot_timeout: 0s
  #ssid: !secret wifi_ssid
  #password: !secret wifi_password

  # Enable fallback hotspot (captive portal) on purpose
  ap:
    ap_timeout: 15s
    ssid: "esphomeap"
    password: "password"


# action to send POST request
on_...:
  - http_request.post:
      url: http://192.168.4.40/json/state
      verify_ssl: false
      json: |-
        root["on"] = false;
        root["v"] = false;
```

### Anything in the logs that might be useful for us?

```txt
[W][http_request:037]: HTTP Request failed; Not connected to network
```
