### ISSUE TITLE
Data transmission via UART (string to number)

### ISSUE THREAD

**Issue by AFrolov203** [esphome/issues#3739]
### The problem

I have an Arduino UNO to which an ORP sensor is connected. I am transmitting data via UART to ESP32 (ESP Home). To do this, I use a Custom UART Text Sensor. Everything is displayed well in the Home Assistant. But I can’t figure out how to replace the code in order to get a numeric value.
I would be grateful if someone could help me…

### Which version of ESPHome has the issue?

2022.10.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.5

### What platform are you using?

ESP32

### Board

DEVKITC

### Component causing the issue

uart sensor (arduino)

### Example YAML snippet

```yaml
esphome:
  name: uart-orp
  includes:
    - uart_orp.h
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Uart-Orp Fallback Hotspot"
    password: "bGKBD3U2Neox"

text_sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new UartReadLineSensor(id(uart_bus));
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};
  text_sensors:
    id: "uart_readline"
    name: "ORP Sensor"
```
