### ISSUE TITLE
ESP32-CAM stops generating images after ~24h

### ISSUE THREAD

**Issue by Coren4** [esphome/issues#374]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io on Ubuntu Server 18
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32-CAM board. Something like this -> https://www.aliexpress.com/item/Low-Power-ESP32-ESP32-CAM-WiFi-Module-ESP32-S-Kit-Serial-Dual-core-WiFi-Bluetooth-Development/33002147011.html?spm=a2g0s.9042311.0.0.27424c4dsuiYiS
**Affected component:**

https://esphome.io/components/esp32_camera.html

**Description of problem:**
When I start board everything is fine.
In logs I see;
"[08:53:55][D][esp32_camera:157]: Got Image: len=29818"
But after some time like 24h it stops generating image, and mentioned log doesn't appear any more.

In my HA UI it is added like that:
```
camera_image: camera.cam_on_node_04
entities:
  - light.node_04_light
title: 04 Kamera TV
type: picture-glance
```

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp_home_node_04
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "ssid"
  password: "pass"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  name: cam_on_node_04
  # ... Frame Settings
  max_framerate: 1 fps
  brightness: 0
  contrast: 0
  saturation: 0

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: node_04_light

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
When image is not generated I can still control on-board LED.

So as You can see in my yaml I already tried to limit max_framerate to 1FPS, because I read about overheating, but still it didn't helped.

I have already heatsink added on main chip of ESP32, but apparently it did not help.

I see that it already change between max and idle mode, when I click on that card in HA - it starts to generate images faster in logs, and when card is closed it slows down.

Maybe it is overheating, is there anything more I could do to overcome that issue? Are there any cheap boards that You could suggest for 24h monitoring? Because maybe I bought wrong ones?

I have 3 boards like that with similar problems.
