### ISSUE TITLE
ESP32-C3 in DIO mode should allow use of GPIO12 and GPIO13

### ISSUE THREAD

**Issue by davidmonro** [esphome/issues#3744]
### The problem

I'm using a "luatos.com/t/esp32c3" board (airm2m_core_esp32c3 is the board type).
Attempting to use GPIO12 or GPIO13 in the config produces the following error:

This pin cannot be used on ESP32-C3s and is already used by the SPI/PSRAM interface (function: SPIHD).

However, this board uses DIO flash mode, so  GPIO12 and GPIO13 are not actually used for the flash interface, and should be available as general purpose IO pins.

(Google translated from the maker of the board at https://wiki.luatos.com/chips/esp32c3/board.html:
IO12 (GPIO12) and IO13 (GPIO13) are multiplexed for SPI signals SPIHD and SPIWP in QIO mode. In order to increase the number of available GPIOs, the development board chooses the DIO mode of 2-wire SPI. IO12 and IO13 are not connected to flash, and use their own compilation The software needs to pay attention to configure the flash as DIO mode.)

Currently, gpio_esp32_c3.py  just defines pins 12-17 as the PSRAM pins and doesn't pay attention the flash mode used for the board.

I don't know if it is possible to access the board config from within this code?

If not, perhaps it could be handled like the S3R8 and S3R8V chips where it throws a warning rather than an error for those pins?

### Which version of ESPHome has the issue?

2022.9.4 (but git dev branch is the same)

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

airm2m_core_esp32c3

**Comment by davidmonro** [comment]
This is still an issue.

**Comment by roommaster** [comment]
I‘m using the same board and want it be solved.

**Comment by fluppie** [comment]
Yes, using the Arduino IDE I can use the onboard leds of this board without any problem.
```
#define ledPin                 13  // D5
#define ledPinDataRequest      12  // D4
```

Doing this in ESPHome gives the famous error.
```
  This pin cannot be used on ESP32-C3s and is already used by the SPI/PSRAM interface (function: SPIWP).
  This pin cannot be used on ESP32-C3s and is already used by the SPI/PSRAM interface (function: SPIHD).
```
```
esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  comment: $device_comment
  name_add_mac_suffix: false
  project:
    name: "Generator"
    version: "1"
  platformio_options:
    board_build.flash_mode: dio

esp32:
#  board: airm2m_core_esp32c3
  board: esp32-c3-devkitm-1
  framework:
#    type: arduino
    type: esp-idf

output:
  - platform: gpio
    pin: 13  # D5
    id: LedPin

  - platform: gpio
    pin: 12  # D4
    id: LedPinDataRequest
```

**Comment by Soviet-Steve** [comment]
yep, not stale

**Comment by hailinmail** [comment]
+1

**Comment by hldh214** [comment]
FYI, since [2024.6.0](https://github.com/esphome/esphome/releases/tag/2024.6.0), the GPIO validation behavior has changed. Previously(https://github.com/esphome/esphome/pull/5982), setting the board to "airm2m_core_esp32c3" could avoid this issue. Now, you must also set `ignore_pin_validation_error` for each pin. for example:

```yaml
output:
  - platform: ledc
    pin: 
      number: LED1_BUILTIN
      ignore_pin_validation_error: true
```


Refs:
https://github.com/esphome/esphome/commit/f0ec900e4841a32023491f8482af3c4a07432adb
