### ISSUE TITLE
tr-502msv transmitting not working

### ISSUE THREAD

**Issue by ale1800** [esphome/issues#3748]
### The problem

Hi everyone, I have this RF remote from LIDL: tr-502msv that controls some RF sockets:
![remote](https://user-images.githubusercontent.com/53172176/199242773-30bca54d-6e4b-487c-a420-10706c33f938.jpg)
I can receive his messages:
![lidl](https://user-images.githubusercontent.com/53172176/199241386-a7fc6bfa-3465-46d2-a6bd-42796491b4bd.jpg)
But I can't reproduce them to turn on and off the plugs.
This is my configuration:
![config](https://user-images.githubusercontent.com/53172176/199241682-825a8f71-7012-4dbe-ba48-75a7f51eb134.jpg)
If I activate the switch nothing happens. If I change protocol to another one, like 5 or 6, I can receive something but without the last "1"
Is it a bug or I'm just interpreting in a wrong way the remote messages?
Thanks in advance

### Which version of ESPHome has the issue?

2022.10.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

rf receiver / rf transmitter

### Example YAML snippet

```yaml
remote_receiver:
  - id: RF_RX
    pin: 
      number: GPIO5
      inverted: True
    dump: 
      - rc_switch
    tolerance: 35%
    filter: 200us
    idle: 4ms
    buffer_size: 3kb

remote_transmitter:
  - id: RF_TX
    pin: GPIO18
    carrier_duty_percent: 100%

switch:
  - platform: template
    name: RF Power Button
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: RF_TX
          protocol: 2
          code: '10110000000000010001'
```

**Comment by zcftr29** [comment]
Hi [ale1800](https://github.com/ale1800),

I have a couple of set of these RF sockets (purchased from Lidl many years ago), and I would like to get them working with HA using my Broadlink RM Pro.  Unfortunately my controller has died so I have no way of learning the RF codes.  Is there any way you could provide me with a list of b64 codes to see if I can get them working again?

Many thanks in advance

**Comment by ale1800** [comment]
> Hi [ale1800](https://github.com/ale1800),
> 
> I have a couple of set of these RF sockets (purchased from Lidl many years ago), and I would like to get them working with HA using my Broadlink RM Pro. Unfortunately my controller has died so I have no way of learning the RF codes. Is there any way you could provide me with a list of b64 codes to see if I can get them working again?
> 
> Many thanks in advance

Hi @zcftr29, sure! But I only have the binary commands.
These are the commands to turn on and off the socket. It's not a standard protocol 2. I think that these commands are the "general ones", those who toggle all the sockets. If you want, as soo as I can, I can send you the  code for every button of the remote

```
    on_turn_on:
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: RF_TX
          protocol:
            pulse_length: 650
            inverted: True
            sync: [1, 10]
            zero: [1 ,2]
            one:  [2, 1]
          code: "10110000000000010001"
          repeat: 
            times: 10
            wait_time: 30ms
    on_turn_off:
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: RF_TX
          protocol:
            pulse_length: 650
            inverted: True
            sync: [1, 10]
            zero: [1 ,2]
            one:  [2, 1]
          code: "10110000000000000000"
          repeat: 
            times: 10
            wait_time: 30ms 
```
