### ISSUE TITLE
After upgrading to 1.13.xx is get errors uploading

### ISSUE THREAD

**Issue by balou2311** [esphome/issues#375]
After upgrading to 1.13.xx I get te following errors on al mij ESP32 devisces:

INFO Reading configuration...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/sensor_node1
Processing sensor_node1 (platform: espressif32@1.6.0; framework: arduino; board: nodemcu-32s)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/nodemcu-32s.html
PLATFORM: Espressif 32 > NodeMCU-32S
HARDWARE: ESP32 240MHz 320KB RAM (4MB Flash)
DEBUG: CURRENT(esp-prog) EXTERNAL(esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 30 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <AsyncMqttClient> 0.8.2
|   |-- <AsyncTCP> 1.0.3
|-- <AsyncTCP> 1.0.3
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <Preferences> 1.0
|-- <Wire> 1.0.1
|-- <WiFi> 1.0
|-- <Update> 1.0
Compiling /data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/api_message.cpp.o
Compiling /data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/api_server.cpp.o
Compiling /data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/basic_messages.cpp.o
Compiling /data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/command_messages.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/api_message.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/basic_messages.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/api_server.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/command_messages.cpp.o] Error 127
========================== [ERROR] Took 15.13 seconds ==========================
DO NOT DELETE ANY TEXT from this template! Otherwise the issue may be closed without a comment.
--> hassio on raspberry P 3B

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
 ESP32_wroom-32s

**Affected component:**

**Description of problem:**
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/api_message.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/basic_messages.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/api_server.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/sensor_node1/.pioenvs/sensor_node1/src/esphome/components/api/command_messages.cpp.o] Error 127
========================== [ERROR] Took 15.13 seconds ==========================

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: sensor_node1
  platform: esp32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret sensor_node1
    gateway: !secret IOTGW
    subnet: !secret IOTSubnet
    dns1: !secret IOTDNS1
    dns2: !secret IOTDNS2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:
mqtt:
  broker: !secret MQTT_broker
  username: !secret MQTT_username
  password: !secret MQTT_password
i2c:
  sda: 21
  scl: 22
  scan: True  
sensor:
#BT Sensor in de Badkamer 
  - platform: xiaomi_mijia
    mac_address: 58:2D:34:31:EB:A6
    temperature:
      name: "Badkamer Temperature"
    humidity:
      name: "Badkamer Humidity"
    battery_level:
      name: "Badkamer Battery Level"

  - platform: wifi_signal
    name: "WiFi Signal Sensor 1"
    update_interval: 60s

  - platform: bmp085
    temperature:
      name: "Werkkamer Temperature"
    pressure:
      name: "Werkkammer Pressure"
    update_interval: 60s
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
