### ISSUE TITLE
Validation error 'pin is a required option' for dallas component if update_interval set

### ISSUE THREAD

**Issue by sebcaps** [esphome/issues#3752]
### The problem

Configure dallas component in yaml file.
Set mandatory Id to a correct on (eg : ``D3``)
Add ``update_interval``option => **Validation** error raised

See screenshot below

### Which version of ESPHome has the issue?

2022.10.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

wemos d1 mini

### Component causing the issue

dallas

### Example YAML snippet

```yaml
esphome:
  name: termp

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "a1iFIUHGvlE6WMHzvnM8XLMC1AeKXeTdloalmbg4fY8="

ota:
  password: "9d100c2982921a20e3a5ced1bdde173a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Termp Fallback Hotspot"
    password: "6Ih2m6WeLp9j"

captive_portal:


dallas:
  - pin: D3
  - update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt


```

### Additional information

**Config without update_interval**
![image](https://user-images.githubusercontent.com/24374878/199303561-4d399a7a-e1a9-411e-9fe4-8ccc94d74a45.png)

**Config with update_interval**
![image](https://user-images.githubusercontent.com/24374878/199303791-49e1b8a0-aab4-4692-982b-b0c5c68f3e7f.png)
