### ISSUE TITLE
GPIO MCP23S17 switch ON when the node wifi reconnetted

### ISSUE THREAD

**Issue by dromegaweb** [esphome/issues#3753]
### The problem

When the esphome node reconnects after losing the wifi signal, the outputs go high following high input readings, all with the use of the MCP23S17 chip

### Which version of ESPHome has the issue?

2022.10.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.10.5

### What platform are you using?

ESP8266

### Board

ESP12E

### Component causing the issue

spi  mcp23s17

### Example YAML snippet

```yaml
substitutions:
  device_name: cantina
  friendly_name: "Cantina"

esphome:
  name: ${device_name} 
  platform: ESP8266
  board: esp12e

wifi:
  #use_address: cantina.local
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.2.111
    gateway: 192.168.2.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
  ap:                  # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "${device_name}"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

web_server:
  port: 80
  auth:
    username: admin
    password: admin

ota:

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

mcp23s17:
  - id: 'mcp23s17_hub'
    cs_pin: GPIO16
    deviceaddress: 0

# Individual outputs
# 0  Ventola Cantina
# 1  Luce esterna porta Cantina
# 2  Luce ingersso Cantina
# 3  Luce Vini


#switch:
#  - platform: gpio
#    name: "Ventola Cantina"
#    pin:
#      mcp23xxx: mcp23s17_hub
#      # Use pin number 0
#      number: 0
#      mode:
#        output: true
#      inverted: false
      
fan:
  - platform: binary
    id: ventolacantina
    name: "Ventola Cantina"   
    output: ventola_cantina

light:
  - platform: binary
    id: lucevini
    name: "Luce Vini"
    output: luce_vini
    restore_mode: always_off
    
  - platform: binary
    id: luceingressocantina
    name: "Luce ingresso Cantina"
    output: luce_ingresso_cantina
    restore_mode: RESTORE_AND_OFF
    
  - platform: binary
    id: luceesternaportacantina
    name: "Luce esterna porta Cantina"
    output: luce_esterna_porta_cantina
    restore_mode: RESTORE_AND_OFF

output:
  - id: luce_vini                   # Use pin number 3
    platform: gpio
    pin:
      mcp23xxx: mcp23s17_hub
      number: 3
      inverted: false
      mode:
        output: true

  - id: luce_ingresso_cantina       # Use pin number 2
    platform: gpio
    pin:
      mcp23xxx: mcp23s17_hub
      number: 2
      inverted: false
      mode:
        output: true

  - id: luce_esterna_porta_cantina   # Use pin number 1
    platform: gpio
    pin:
      mcp23xxx: mcp23s17_hub
      number: 1
      inverted: false
      mode:
        output: true

  - id: ventola_cantina
    platform: gpio
    pin:
      mcp23xxx: mcp23s17_hub        # Use pin number 0
      number: 0
      inverted: false
      mode:
        output: true

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
#  - platform: uptime
#    name: "${friendly_name} Uptime" 
  - platform: dht
    model: DHT22
    pin: GPIO4
    temperature:
      name: "Temperatura Cantina"
      id: temperatura_cantina
    humidity:
      name: "Umidità Cantina"
      id: umidita_cantina
    
binary_sensor:
  - platform: status    # Stato di: connesso o disconnesso
    name: "${friendly_name}"  

# Individual inputs
# 8  Pir Luce esterno Cantina
# 9  Pir Luce Vini
# 10 Pir Luce Ingersso Cantina
# 11 Tasto attivazione zona 1
# 12 Tasto attivazione zona 2
# 13 Tasto attivazione zona 1 e 2 singolarmante con tiner definito in HA
# 14 Tasto attivazione Ventola


  - platform: gpio
    name: "Pir Luce esterno Cantina"
    device_class: motion
    pin:
      mcp23xxx: mcp23s17_hub
      # Use pin number 8
      number: 8
      # One of INPUT or INPUT_PULLUP
      mode:
        input: true
        pullup: false
      inverted: false

      
  - platform: gpio
    name: "Pir Luce Vini"
    device_class: motion
    pin:
      mcp23xxx: mcp23s17_hub
      # Use pin number 9
      number: 9
      # One of INPUT or INPUT_PULLUP
      mode:
        input: true
        pullup: false
      inverted: false
      
  - platform: gpio
    name: "Pir Luce Ingersso Cantina"
    device_class: motion
    pin:
      mcp23xxx: mcp23s17_hub
      # Use pin number 10
      number: 10
      # One of INPUT or INPUT_PULLUP
      mode:
        input: true
        pullup: false
      inverted: false
```
