### ISSUE TITLE
ESP32 xiaomi mijia flower frequent updates

### ISSUE THREAD

**Issue by sendorm** [esphome/issues#376]
The code below checks for the mijia values every 30-40 seconds, not the intended per 3 hours. 
```
esp32_ble_tracker:
  scan_interval: 10800s

sensor:
  - platform: xiaomi_miflora
    mac_address: 'C4:7C:8D:64:36:6E'
    temperature:
      name: "Bonzai Temperature"
    moisture:
      name: "Bonzai Moisture"
    illuminance:
      name: "Bonzai Illuminance"
    conductivity:
      name: "Bonzai Soil Conductivity"
    battery_level:
      name: "Bonzai Battery Level"
```
