### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Sjeff** [esphome/issues#3764]
### The problem

I'm trying to get the shelly 1 plus to act as my garage door opener but something in the Cover template isn't right.

can someone point me in the right direction?

when i remove te cover completely i dont have any compiling errors

### Which version of ESPHome has the issue?

2022.10.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Board

Shelly 1 plus

### Component causing the issue

cover template

### Example YAML snippet

```yaml
substitutions:
  device_name: "Shelly Plus 1 Garage"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

esphome:
  name: shelly-plus-1-garage
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

wifi:
  ssid: !secret wifi_http_ssid
  password: !secret wifi_http_password
  fast_connect: true
  use_address: 192.168.5.186

logger:

api:
  password: !secret esphome_api_password
  encryption:
    key: !secret esphome_api_encryption_key

ota:
  password: !secret esphome_ota_password

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO26

switch:
  - platform: output
    id: relay
    name: "${device_name} Relay"
    output: "relay_output"

binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: "Garage Door Contact Sensor"
    id: contact_sensor
    internal: true
    filters:
      - invert:
      # Debounce the contact sensor to prevent rapid on/off/on events
      - delayed_on_off: 500ms

cover:
  - platform: template
    device_class: garage
    name: "Garage Door"
    lambda: |-
      if (id(contact_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: "relay"
      - delay: 0.5s
      - switch.turn_off: "relay"
    close_action:
      - switch.turn_on: "relay"
      - delay: 0.5s
      - switch.turn_off: "relay"

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${device_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: "relay"
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO32
    attenuation: 11db

  - platform: adc
    name: "${device_name} Relay Supply Voltage"
    pin: GPIO33
    attenuation: 11db
    filters:
      - multiply: 8

status_led:
  pin:
    number: GPIO0
    inverted: true
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /root/config/shelly-plus-1-garage.yaml...
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO0 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing shelly-plus-1-garage (board: esp32doit-devkit-v1; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40302.0 (4.3.2) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32s2 @ 8.4.0+2021r2-patch2
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling .pioenvs/shelly-plus-1-garage/src/main.o
Linking .pioenvs/shelly-plus-1-garage/firmware.elf
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x8): undefined reference to `esphome::cover::Cover::make_call()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0xc): undefined reference to `esphome::cover::CoverCall::set_position(float)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x10): undefined reference to `esphome::cover::CoverCall::set_tilt(float)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x14): undefined reference to `esphome::cover::CoverCall::set_command_stop()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x18): undefined reference to `esphome::cover::CoverCall::perform()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x1c): undefined reference to `esphome::cover::CoverCall::set_command_open()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x20): undefined reference to `esphome::cover::CoverCall::set_command_close()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection16send_cover_stateEPNS_5cover5CoverE+0x8): undefined reference to `esphome::cover::COVER_OPEN'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection15send_cover_infoEPNS_5cover5CoverE+0x4): undefined reference to `esphome::cover::Cover::get_device_class[abi:cxx11]()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
/root/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:6011: undefined reference to `esphome::cover::Cover::make_call()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o: in function `esphome::api::APIConnection::cover_command(esphome::api::CoverCommandRequest const&)':
/root/config/.esphome/build/shelly-plus-1-garage/src/esphome/components/api/api_connection.cpp:246: undefined reference to `esphome::cover::CoverCall::set_position(float)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /root/config/.esphome/build/shelly-plus-1-garage/src/esphome/components/api/api_connection.cpp:248: undefined reference to `esphome::cover::CoverCall::set_tilt(float)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /root/config/.esphome/build/shelly-plus-1-garage/src/esphome/components/api/api_connection.cpp:250: undefined reference to `esphome::cover::CoverCall::set_command_stop()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /root/config/.esphome/build/shelly-plus-1-garage/src/esphome/components/api/api_connection.cpp:251: undefined reference to `esphome::cover::CoverCall::perform()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /root/config/.esphome/build/shelly-plus-1-garage/src/esphome/components/api/api_connection.cpp:235: undefined reference to `esphome::cover::CoverCall::set_command_open()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /root/config/.esphome/build/shelly-plus-1-garage/src/esphome/components/api/api_connection.cpp:238: undefined reference to `esphome::cover::CoverCall::set_command_close()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /root/config/.esphome/build/shelly-plus-1-garage/src/esphome/components/api/api_connection.cpp:241: undefined reference to `esphome::cover::CoverCall::set_command_stop()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/components/api/api_connection.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()':
/root/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:657: undefined reference to `esphome::cover::Cover::get_device_class[abi:cxx11]()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o:(.literal._ZNSt17_Function_handlerIFN7esphome8optionalIfEEvEZ5setupvEUlvE_E9_M_invokeERKSt9_Any_data+0x4): undefined reference to `esphome::cover::COVER_CLOSED'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o:(.literal._Z5setupv+0x1d8): undefined reference to `esphome::template_::TemplateCover::TemplateCover()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o:(.literal._Z5setupv+0x1dc): undefined reference to `esphome::cover::Cover::set_device_class(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o:(.literal._Z5setupv+0x1e0): undefined reference to `esphome::template_::TemplateCover::set_state_lambda(std::function<esphome::optional<float> ()>&&)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o:(.literal._Z5setupv+0x1e4): undefined reference to `esphome::template_::TemplateCover::get_open_trigger() const'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o:(.literal._Z5setupv+0x1ec): undefined reference to `esphome::template_::TemplateCover::get_close_trigger() const'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o:(.literal._Z5setupv+0x1f0): undefined reference to `esphome::template_::TemplateCover::set_has_position(bool)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o:(.literal._Z5setupv+0x1f4): undefined reference to `esphome::template_::TemplateCover::set_optimistic(bool)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o:(.literal._Z5setupv+0x1f8): undefined reference to `esphome::template_::TemplateCover::set_assumed_state(bool)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o: in function `esphome::binary_sensor::Filter::Filter()':
/root/config/.esphome/build/shelly-plus-1-garage/src/esphome/components/binary_sensor/filter.h:12: undefined reference to `esphome::template_::TemplateCover::TemplateCover()'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o: in function `__gnu_cxx::new_allocator<esphome::binary_sensor::Filter*>::allocate(unsigned int, void const*)':
/root/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/ext/new_allocator.h:111: undefined reference to `esphome::cover::Cover::set_device_class(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o: in function `esphome::binary_sensor::Filter** std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<esphome::binary_sensor::Filter*>(esphome::binary_sensor::Filter* const*, esphome::binary_sensor::Filter* const*, esphome::binary_sensor::Filter**)':
/root/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/stl_algobase.h:368: undefined reference to `esphome::template_::TemplateCover::set_state_lambda(std::function<esphome::optional<float> ()>&&)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o: in function `setup()':
/root/config/.esphome/build/shelly-plus-1-garage/src/main.cpp:256: undefined reference to `esphome::template_::TemplateCover::get_open_trigger() const'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /root/config/.esphome/build/shelly-plus-1-garage/src/main.cpp:311: undefined reference to `esphome::template_::TemplateCover::get_close_trigger() const'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/main.o: in function `setup()':
/root/config/shelly-plus-1-garage.yaml:78: undefined reference to `esphome::template_::TemplateCover::set_has_position(bool)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /root/config/shelly-plus-1-garage.yaml:78: undefined reference to `esphome::template_::TemplateCover::set_optimistic(bool)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /root/config/shelly-plus-1-garage.yaml:78: undefined reference to `esphome::template_::TemplateCover::set_assumed_state(bool)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /root/config/shelly-plus-1-garage.yaml:78: undefined reference to `esphome::template_::TemplateCover::set_has_position(bool)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/core/controller.o:(.literal._ZN7esphome10Controller16setup_controllerEb+0x20): undefined reference to `esphome::cover::Cover::add_on_state_callback(std::function<void ()>&&)'
/root/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/shelly-plus-1-garage/src/esphome/core/controller.o: in function `esphome::Controller::setup_controller(bool)':
/root/config/.esphome/build/shelly-plus-1-garage/src/esphome/core/controller.cpp:41: undefined reference to `esphome::cover::Cover::add_on_state_callback(std::function<void ()>&&)'
collect2: error: ld returned 1 exit status
*** [.pioenvs/shelly-plus-1-garage/firmware.elf] Error 1
========================= [FAILED] Took 22.65 seconds =========================
```
