### ISSUE TITLE
The esp01s cannot drive the S8 CO2 sensor

### ISSUE THREAD

**Issue by louliangsheng** [esphome/issues#3766]
### The problem

The esp01s cannot drive the S8 CO2 sensor,however, when I swipe to another nodemcu, it can drive normally, and I can confirm that there is no problem with my esp01s. It can write the firmware normally and even drive other serial devices.

### Which version of ESPHome has the issue?

2022.10.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.11.0

### What platform are you using?

ESP8266

### Board

ESP01S

### Component causing the issue

senseair

### Example YAML snippet

```yaml
esphome:
  name: "airnut-co2"

esp8266:
  board: esp01_1m

api:

ota:

wifi:
  ssid: 'L'
  password: '1234567890'

  ap:
    ssid: "AirNut Fallback Hotspot"

captive_portal:

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600

sensor:
  - platform: senseair
    co2:
      name: "AirNut CO2 Sensor"
    update_interval: 20s
```
