### ISSUE TITLE
SM300D2 Sensor - Invalid Preamble - Reading Data Time out

### ISSUE THREAD

**Issue by EdDickens** [esphome/issues#3767]
### The problem

I have a new SM300D2 sensor connected to an ESP01. I’ve got the ESP flashed with a basic config to get things running. All the Entities show up in HA with no problems. The problem is actually reading from the sensor. Seem to be having the same issues [reported here](https://community.home-assistant.io/t/esphome-sdm300d2-issue/324891). From that thread it seems the issue was fixed at one point but I cannot get anything from the sensor.

### Which version of ESPHome has the issue?

2022.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.5

### What platform are you using?

ESP8266

### Board

ESP-01

### Component causing the issue

SM300D2

### Example YAML snippet

```yaml
esphome:
  name: air-quality

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:
#  password: !secret haapi_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi1_ssid
  password: !secret wifi1_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Quality Fallback Hotspot"
    password: !secret fb_password

captive_portal:

switch:
  - platform: restart
    id: AirQual_restart
    name: "Air Quality Restart"
    
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

sensor:
  - platform: sm300d2
    co2:
      name: "CO2"
      id: "AirQual_CO2"
    formaldehyde:
      name: "Formaldehyde"
      id: "AirQual_Formaldehyde"
    tvoc:
      name: "TVOC"
      id: "AirQual_TVOC"
    pm_2_5:
      name: "PM2.5"
      id: "AirQual_PM25"
    pm_10_0:
      name: "PM10"
      id: "AirQual_PM10"
    temperature:
      name: "Temperature"
      id: "AirQual_Temperature"
    humidity:
      name: "Humidity"
      id: "AirQual_Humidity"
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
[13:43:49][W][sm300d2:026]: Invalid preamble for SM300D2 response!
[13:44:50][E][uart:015]: Reading from UART timed out at byte 0!
[13:44:50][W][sm300d2:020]: Reading data from SM300D2 failed!
[13:45:50][E][uart:015]: Reading from UART timed out at byte 0!
[13:45:50][W][sm300d2:020]: Reading data from SM300D2 failed!
[13:46:50][E][uart:015]: Reading from UART timed out at byte 0!
[13:46:50][W][sm300d2:020]: Reading data from SM300D2 failed!
[13:47:50][W][sm300d2:026]: Invalid preamble for SM300D2 response!
[13:48:50][E][uart:015]: Reading from UART timed out at byte 0!
[13:48:50][W][sm300d2:020]: Reading data from SM300D2 failed!
```
