### ISSUE TITLE
Wrong timezone ESP32

### ISSUE THREAD

**Issue by Salvora** [esphome/issues#3769]
### The problem

I am not sure what changed but suddenly all my ESP32 devices report time wrong with -6 hours offset.
On the other hand my ESP8266 device reports the correct time.

I tested this using homeassistant time and sntp time.
Below are the configurations I have tested.

It reports the time as **UTC/GMT -3** hours instead it should be **UTC/GMT +3** hours.

I use tm1637 to display the time.

```yaml
time:
  - platform: homeassistant
    id: homeassistant_time
```

```yaml
time:
  - platform: sntp
    servers: 192.168.1.1
    id: ntp_time
```

```yaml
time:
  - platform: sntp
    id: ntp_time
```
```yaml
time:
  - platform: sntp
    id: ntp_time
    timezone: Europe/Istanbul
```

### Which version of ESPHome has the issue?

2022.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.5

### What platform are you using?

ESP32

### Board

devkit-v1

### Component causing the issue

time

### Example YAML snippet

```yaml
time:
  - platform: sntp
    servers: 192.168.1.1
    id: ntp_time
```

**Comment by ssieb** [comment]
Does the last one with the timezone work?  What do you see in the logs?

**Comment by Salvora** [comment]
I believe 2022.10.1 was working. Log is attached but in short, it correctly sees the time:
```

INFO Detected timezone 'Europe/Istanbul'
INFO Generating C++ source...
INFO Compiling app...
```

and sntp:

```
[17:58:17][C][sntp:050]: SNTP Time:
[17:58:17][C][sntp:051]:   Server 1: '192.168.1.1'
[17:58:17][C][sntp:052]:   Server 2: ''
[17:58:17][C][sntp:053]:   Server 3: ''
[17:58:17][C][sntp:054]:   Timezone: '<+03>-3'
```
[logs_emre-oda-esp32s-devkitv1_upload.txt](https://github.com/esphome/issues/files/9946824/logs_emre-oda-esp32s-devkitv1_upload.txt)

**Comment by ssieb** [comment]
> I believe 2022.10.1 was working.

Are you saying it changed between `2022.10.1` and `2022.10.2`?
Where do you see the time being wrong?  I don't see the time used anywhere in the logs.

**Comment by Salvora** [comment]
I see the time on the tm1637

Full yaml below:

```yaml
substitutions:
  devicename: "Emre Oda ESP32S"
  roomname: "Emre Oda"

esphome:
  name: emre-oda-esp32s-devkitv1

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino
    version: recommended

wifi:
  ssid: !secret esp_wifi_ssid
  password: !secret esp_wifi_pass
  id: emre_oda_esp32s_wi_fi

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename Devkitv1"
    password: !secret esp_ap_password
    ap_timeout: 5min

captive_portal:

# Enable logging
logger:
# Enable debugging
debug:

# Enable Home Assistant API
api:
  password: !secret esp_api_password
  encryption:
    key: !secret emre-oda-esp32s-devkitv1_enc_key
  id: api_config

ota:
  password: !secret esp_ota_password

time:
  - platform: sntp
    servers: 192.168.1.1
    id: ntp_time

esp32_ble_tracker:
  scan_parameters:
    interval: 60s
    active: True
  id: esp_ble_tracker

bluetooth_proxy:
  active: true

globals:
  - id: display_status
    type: bool
    restore_value: true
    initial_value: "true"

  - id: display_mode_global
    type: int
    restore_value: true
    initial_value: "1"

number:
  - platform: template
    id: display_intensity
    name: "$devicename Ekran Parlaklığı (0-7)"
    icon: mdi:brightness-5
    optimistic: true
    mode: slider
    initial_value: 0
    min_value: 0
    max_value: 7
    step: 1
    update_interval: 4000ms
    entity_category: "config"
    restore_value: true
    on_value:
      then:
        - component.update: tm1637_display

select:
  - platform: template
    id: display_mode
    name: "$devicename Ekran Modu"
    optimistic: true
    options:
      - Sıcaklık
      - Nem
      - Sıcaklık & Nem
      - Saat
      - Saat & Sıcaklık
    initial_option: "Saat & Sıcaklık"
    restore_value: true
    entity_category: "config"
    on_value:
      then:
        - lambda: |-
            if (id(display_mode).state == "Sıcaklık")
              id(display_mode_global) = 1;
            else if (id(display_mode).state == "Nem")
              id(display_mode_global) = 2;
            else if (id(display_mode).state == "Sıcaklık & Nem")
              id(display_mode_global) = 3;
            else if (id(display_mode).state == "Saat")
              id(display_mode_global) = 4;
            else if (id(display_mode).state == "Saat & Sıcaklık")
              id(display_mode_global) = 5;
            else {
              ESP_LOGI("main", "Nothing is selected!");
            }
        - component.update: tm1637_display

display:
  platform: tm1637
  id: tm1637_display
  clk_pin: 25
  dio_pin: 26
  update_interval: 500ms
  lambda: |-
    it.set_intensity(id(display_intensity).state);
    if (id(display_status) == false) {
      it.printf("    ");
    }
    else {
      static int i = 0;
      static int j = 0;
      i++;
      j++;
      switch (id(display_mode_global)) {
        case 1:
          it.printf("%.1f~", id(emre_oda_temp).state);
          break;
        case 2:
          it.printf("%3.0fP", id(emre_oda_humd).state);
          break;
        case 3:
          if ((i % 20) > 10)
            it.printf("%3.0fP", id(emre_oda_humd).state);
          else
            it.printf("%.1f~", id(emre_oda_temp).state);
          break;
        case 4:
          if ((i % 2) == 0)
            it.strftime("%H.%M", id(ntp_time).now());
          else
            it.strftime("%H%M", id(ntp_time).now());
          break;
        case 5:
          if ((i % 20) > 10)
            if ((j % 2) == 0)
              it.strftime("%H.%M", id(ntp_time).now());
            else
              it.strftime("%H%M", id(ntp_time).now());
          else
            it.printf("%.1f~", id(emre_oda_temp).state);
          break;
        default:
          if ((i % 20) > 10)
            it.printf("%3.0fP", id(emre_oda_humd).state);
          else
            it.printf("%.1f~", id(emre_oda_temp).state);
      }
    }
remote_transmitter:
  pin: 33
  carrier_duty_percent: 50%

# Monitor TV State
binary_sensor:
  - platform: gpio
    name: "$roomname TV Durumu"
    internal: True
    entity_category: "diagnostic"
    device_class: "power"
    id: emre_tv_power
    pin:
      number: 34 #Input only pin without internal pull-up or pull-down resistors

sensor:
  - platform: template
    name: Free HEAP
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    icon: "mdi:memory"
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: "b"
    update_interval: 60s
  - platform: debug
    free:
      name: Free MEM

  # DHT 22
  - platform: dht
    pin:
      number: 18
      mode:
        input: true
        pullup: False
    model: AM2302
    temperature:
      name: "$roomname DHT22 Sıcaklık"
      id: emre_oda_temp
      unit_of_measurement: "°C"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 2
      filters:
        - offset: -6.1
        - median:
            window_size: 7
            send_every: 4
            send_first_at: 3
    humidity:
      name: "$roomname DHT22 Nem"
      id: emre_oda_humd
      unit_of_measurement: "%"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 2
      filters:
        - median:
            window_size: 7
            send_every: 4
            send_first_at: 3
    update_interval: 10s

  # Wi-Fi
  - platform: wifi_signal
    name: "$devicename Wi-Fi Sinyal Gücü"
    update_interval: 60s
    id: emre_oda_esp32s_wifi_signal

  # Uptime Sensor
  - platform: uptime
    name: "$devicename Açık Süre"
    update_interval: 60s
    id: emre_oda_esp32s_uptime

button:
  # Restart Button
  - platform: restart
    name: "$devicename Restart"
    id: emre_oda_esp32s_restart

  # Remote Control Buttons
  - platform: template
    name: "$roomname TV Input"
    icon: mdi:exit-to-app
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DFD02F
            nbits: 32
  - platform: template
    name: "$roomname TV Ses Yükselt"
    icon: mdi:volume-plus
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF40BF
            nbits: 32
  - platform: template
    name: "$roomname TV Ses Azalt"
    icon: mdi:volume-minus
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DFC03F
            nbits: 32
  - platform: template
    name: "$roomname TV Mute"
    icon: mdi:volume-mute
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF906F
            nbits: 32
  - platform: template
    name: "$roomname TV Kanal İleri"
    icon: mdi:plus
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF00FF
            nbits: 32
  - platform: template
    name: "$roomname TV Kanal Geri"
    icon: mdi:minus
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF807F
            nbits: 32
  - platform: template
    name: "$roomname TV Yukarı"
    icon: mdi:arrow-up
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF02FD
            nbits: 32
  - platform: template
    name: "$roomname TV Aşağı"
    icon: mdi:arrow-down
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF827D
            nbits: 32
  - platform: template
    name: "$roomname TV Sağ"
    icon: mdi:arrow-right
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF609F
            nbits: 32
  - platform: template
    name: "$roomname TV Sol"
    icon: mdi:arrow-left
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DFE01F
            nbits: 32
  - platform: template
    name: "$roomname TV OK"
    icon: mdi:eslint
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF22DD
            nbits: 32
  - platform: template
    name: "$roomname TV Geri"
    icon: mdi:reply-outline
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF14EB
            nbits: 32
  - platform: template
    name: "$roomname TV Exit"
    icon: mdi:location-exit
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DFDA25
            nbits: 32
  - platform: template
    name: "$roomname TV Info"
    icon: mdi:information-outline
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF55AA
            nbits: 32
  - platform: template
    name: "$roomname TV Medya Durdur"
    icon: mdi:stop-circle-outline
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF8D72
            nbits: 32
  - platform: template
    name: "$roomname TV Medya Oynat"
    icon: mdi:play-circle-outline
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF0DF2
            nbits: 32
  - platform: template
    name: "$roomname TV Medya Duraklat"
    icon: mdi:pause-circle-outline
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF5DA2
            nbits: 32
  - platform: template
    name: "$roomname TV Önceki Medya"
    icon: mdi:skip-previous-circle-outline
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DFF10E
            nbits: 32
  - platform: template
    name: "$roomname TV Sonraki Medya"
    icon: mdi:skip-next-circle-outline
    on_press:
      then:
        - remote_transmitter.transmit_lg:
            data: 0x20DF718E
            nbits: 32

switch:
  # Display On/Off Switch for Display
  - platform: template
    name: "$devicename Ekran"
    icon: mdi:monitor
    device_class: "switch"
    entity_category: "config"
    lambda: |-
      if (id(display_status) == true) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - globals.set:
          id: display_status
          value: "true"
      - component.update: tm1637_display
    turn_off_action:
      - globals.set:
          id: display_status
          value: "false"
      - component.update: tm1637_display

  # TV Switches
  - platform: template
    name: "$roomname TV Güç"
    id: emre_tv_pswitch
    icon: mdi:power
    device_class: "switch"
    lambda: |-
      if (id(emre_tv_power).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x20DF10EF
          nbits: 32
    turn_off_action:
      - remote_transmitter.transmit_lg:
          data: 0x20DF10EF
          nbits: 32
      - lambda: |-
          id(emre_tv_power).publish_state(false);

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "$devicename IP Address"
      icon: mdi:ip
    ssid:
      name: "$devicename Connected SSID"
      icon: mdi:router-wireless
    bssid:
      name: "$devicename Connected BSSID"
      icon: mdi:router-wireless
    mac_address:
      name: "$devicename Wi-Fi MAC Address"
      icon: mdi:wifi-marker
      
  - platform: version
    name: "$devicename Version"
    icon: mdi:package-up

```

**Comment by ssieb** [comment]
I don't know what's happening with the timezone conversion in your case.  That's a strange end result for the timezone value and I can get the same type of result with the `Etc/*` names as well.  Use `timezone: TRT-3` instead.

**Comment by ssieb** [comment]
It's very strange that you say it's working properly with an 8266.  Can you paste logs from that?

**Comment by Salvora** [comment]
8266 logs attached.
[logs_gozde-oda-esp8266-nodemcuv2_logs.txt](https://github.com/esphome/issues/files/9947038/logs_gozde-oda-esp8266-nodemcuv2_logs.txt)

Below is the config:
```yaml
substitutions:
  devicename: "Gözde Oda ESP8266"
  roomname: "Gözde Oda"

esphome:
  name: gozde-oda-esp8266-nodemcuv2

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

wifi:
  ssid: !secret esp_wifi_ssid
  password: !secret esp_wifi_pass
  id: gozde_oda_esp8266_wi_fi

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename Nodemcuv2"
    password: !secret esp_ap_password
    ap_timeout: 5min

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_password
  encryption:
    key: !secret gozde-oda-esp8266-nodemcuv2_enc_key
  id: api_config

ota:
  password: !secret esp_ota_password
  
time:
  - platform: sntp
    servers: 192.168.1.1
    id: ntp_server
    
globals:
  - id: display_status
    type: bool
    restore_value: true
    initial_value: 'true'

  - id: display_mode_global
    type: int
    restore_value: true
    initial_value: '1'

number:
  - platform: template
    id: display_intensity 
    name: "$devicename Ekran Parlaklığı (0-7)"
    icon: mdi:brightness-5
    optimistic: true
    mode: slider
    initial_value: 0
    min_value: 0
    max_value: 7
    step: 1
    update_interval: 4000ms
    entity_category: "config"
    restore_value: true
    on_value:
      then:
        - component.update: tm1637_display

select:
  - platform: template
    id: display_mode
    name: "$devicename Ekran Modu"
    optimistic: true
    options:
      - Sıcaklık
      - Nem
      - Sıcaklık & Nem
      - Saat
      - Saat & Sıcaklık
    initial_option: "Saat & Sıcaklık"
    restore_value: true
    entity_category: "config"
    on_value:
      then:
        - lambda: |-
            if (id(display_mode).state == "Sıcaklık")
              id(display_mode_global) = 1;
            else if (id(display_mode).state == "Nem")
              id(display_mode_global) = 2;
            else if (id(display_mode).state == "Sıcaklık & Nem")
              id(display_mode_global) = 3;
            else if (id(display_mode).state == "Saat")
              id(display_mode_global) = 4;
            else if (id(display_mode).state == "Saat & Sıcaklık")
              id(display_mode_global) = 5;
            else {
              ESP_LOGI("main", "Nothing is selected!");
            }
        - component.update: tm1637_display

display:
    platform: tm1637
    id: tm1637_display
    clk_pin: D0
    dio_pin: D1
    update_interval: 500ms
    lambda: |-
      it.set_intensity(id(display_intensity).state);
      if (id(display_status) == false) {
        it.printf("    ");
      }
      else {
        static int i = 0;
        static int j = 0;
        i++;
        j++;
        switch (id(display_mode_global)) {
          case 1:
            it.printf("%.1f~", id(gozde_oda_temp).state);
            break;
          case 2:
            it.printf("%3.0fP", id(gozde_oda_humd).state);
            break;
          case 3:
            if ((i % 20) > 10)
              it.printf("%3.0fP", id(gozde_oda_humd).state);
            else
              it.printf("%.1f~", id(gozde_oda_temp).state);
            break;
          case 4:
            if ((i % 2) == 0)
              it.strftime("%H.%M", id(ntp_server).now());
            else
              it.strftime("%H%M", id(ntp_server).now());
            break;
          case 5:
            if ((i % 20) > 10)
              if ((j % 2) == 0)
                it.strftime("%H.%M", id(ntp_server).now());
              else
                it.strftime("%H%M", id(ntp_server).now());
            else
              it.printf("%.1f~", id(gozde_oda_temp).state);
            break;
          default:
            if ((i % 20) > 10)
              it.printf("%3.0fP", id(gozde_oda_humd).state);
            else
              it.printf("%.1f~", id(gozde_oda_temp).state);
        }
      }

sensor:
  # DHT 22
  - platform: dht
    pin:
      number: D7
      mode:
        input: true
        pullup: true
    model: AM2302
    temperature:
      name: "$roomname DHT22 Sıcaklık"
      id: "gozde_oda_temp"
      unit_of_measurement: "°C"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 2
      filters:
        - offset: -3.8
        - median:
            window_size: 7
            send_every: 4
            send_first_at: 3
    humidity:
      name: "$roomname DHT22 Nem"
      id: "gozde_oda_humd"
      unit_of_measurement: "%"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 2
      filters:
        - median:
            window_size: 7
            send_every: 4
            send_first_at: 3
    update_interval: 5s

  # Wi-Fi
  - platform: wifi_signal
    name: "$devicename Wi-Fi Sinyal Gücü"
    update_interval: 60s
    id: gozde_oda_esp8266_wifi_signal

  # Uptime Sensor
  - platform: uptime
    name: "$devicename Açık Süre"
    update_interval: 60s
    id: gozde_oda_esp8266_uptime

button:
  # Restart Button
  - platform: restart
    name: "$devicename Restart"
    id: gozde_oda_esp8266_restart

switch:
  # Display On/Off Switch
  - platform: template
    name: "$devicename Ekran"
    icon: mdi:monitor
    lambda: |-
      if (id(display_status) == true) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - globals.set:
          id: display_status
          value: 'true'
      - component.update: tm1637_display
    turn_off_action:
      - globals.set:
          id: display_status
          value: 'false' 
      - component.update: tm1637_display
             
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "$devicename IP Address"
      icon: mdi:ip
    ssid:
      name: "$devicename Connected SSID"
      icon: mdi:router-wireless
    bssid:
      name: "$devicename Connected BSSID"
      icon: mdi:router-wireless
    mac_address:
      name: "$devicename Wi-Fi MAC Address"
      icon: mdi:wifi-marker
      
  - platform: version
    name: "$devicename Version"
    icon: mdi:package-up
```
