### ISSUE TITLE
TuyaMCU Climate converting incorrect units F to C

### ISSUE THREAD

**Issue by jazzmonger** [esphome/issues#3784]
### The problem

TuyaMCU Climate Entity incorrectly reports C instead of F. Shoddy programming in the pellet stove's MCU does not allow changing from F to C, so the values are report in F and TuyaMCU thinks it's C

### Which version of ESPHome has the issue?

all versions

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2022.11.2 Supervisor 2022.10.2 Frontend 20221108.0 - latest

### What platform are you using?

ESP8266

### Board

 board: esp01_1m

### Component causing the issue

TuyaMCU Climate

### Example YAML snippet

```yaml
climate:
  - platform: tuya
    name: " Shop Test Stove ESPHome"
    switch_datapoint: 1
    target_temperature_datapoint: 106
    current_temperature_datapoint: 107
    eco_datapoint: 101
    eco_temperature: 62 °F
```

### Anything in the logs that might be useful for us?

```txt
1:28:52][D][sensor:126]: 'Shop Test Stove-Current Temp': Sending state 59.00000 °F with 0 decimals of accuracy
[11:28:52][D][climate:385]: ' Shop Test Stove ESPHome' - Sending state:
[11:28:52][D][climate:388]:   Mode: OFF
[11:28:52][D][climate:390]:   Action: OFF
[11:28:52][D][climate:399]:   Preset: NONE
[11:28:52][D][climate:408]:   Current Temperature: 59.00°C. <--- its 59deg F in my shop, not C
[11:28:52][D][climate:414]:   Target Temperature: 79.00°C
```

### Additional information

There appears to be no way to fix this problem.  I cannot define measurement units different from what they are and the MCU on these wood stoves doesnt allow selecting C.  It's hard coded to F.

![image](https://user-images.githubusercontent.com/52110065/201539078-1ce31153-e151-4843-8ae3-b4612ea94958.png)

If l lived in purgatory, this would be great.  It's not so good here.
