### ISSUE TITLE
Wrong addition of the total value

### ISSUE THREAD

**Issue by Marlo461** [esphome/issues#3786]
### The problem

I created a total water consumption meter based on measuring current consumption using an ultrasonic flow sensor.
Flow measurement works great for me, but I need to integrate this measured value to know the total water consumption.
I used the Integration Sensor component, which works, but after a long time when there is no flow and then the flow comes, it calculates a large value and after this addition calculates correctly again.
The picture shows this state:

![esphome integration value error](https://user-images.githubusercontent.com/96550831/201615254-1f5e576b-87cc-47e7-8d6b-8232d4b74169.png)

### Which version of ESPHome has the issue?

2022.10.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.11.2

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

Integration Sensor

### Example YAML snippet

```yaml
sensor:
  - platform: pulse_meter
    pin: GPIO0
    timeout: 1200ms
    id: my_flow_meter_liter_min
    name: 'aktualna spotreba vody l/min'
    unit_of_measurement: 'l/min'
    accuracy_decimals: 3
    filters:
      - multiply: 0.02
# from flowmeter: 1 liter = 50 pulse  
# https://esphome.io/components/sensor/pulse_meter.html    

  - platform: integration
    name: "celkova spotreba vody l"
    id: water_total_liters
    sensor: my_flow_meter_liter_min
    time_unit: min
    unit_of_measurement: 'l'
    device_class: water
    state_class: total_increasing
# https://esphome.io/components/sensor/integration.html
```
