### ISSUE TITLE
ESP32S2 - DAC problem

### ISSUE THREAD

**Issue by SmartieBjelovar** [esphome/issues#3787]
### The problem

DAC function is not available for ESP32S2 modules.  Internal DAC pins for ESP32S2 are GPIO17 and GPIO18 but esphome allows pins GPIO25 and GPIO26. 

Am I doing something wrong, is there any other way to use an internal DAC on ESP32S2?

### Which version of ESPHome has the issue?

2022.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.2

### What platform are you using?

ESP32-IDF

### Board

esp32-s2-saola-1

### Component causing the issue

esp32_dac

### Example YAML snippet

```yaml
esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf
    version: recommended
  variant: esp32s2

output:
  - platform: esp32_dac
    pin: GPIO17
    id: fan_speed
```

### Anything in the logs that might be useful for us?

```txt
output.esp32_dac: [source /config/esphome/fan-controller.yaml:12]
  platform: esp32_dac
  
  Unknown value '17', valid options are '25', '26'.
  pin: GPIO17
  id: fan_speed
```
