### ISSUE TITLE
Samsung remote receiver

### ISSUE THREAD

**Issue by DelukaDZ** [esphome/issues#379]
Thx for reading this and i hope you can point me in the right direction
I’m trying to only detect the power off button of my Samsung remote using a binary sensor
its works … kind off
This is YAML i gave so for

```
remote_receiver:
  pin: 
    number: GPIO14
    inverted: yes
    mode: INPUT_PULLUP
  dump: samsung

binary_sensor:
  - platform: remote_receiver
    name: "Samsung Remote"
    samsung:
      data : 0xE0E040BF
    filters:
      - delayed_off: 200ms
```

The problem is that the sensor triggers on every button i press on the Samsung remote. its not triggered with any other remote so part 1 seems to work alright
from what i found on the Esphome site everything could be alright
i’m sure i missing something but can’t see what
i’m running esphome 1.13.2
