### ISSUE TITLE
[set_level] is an invalid option for [output.ledc]. Please check the indentation.

### ISSUE THREAD

**Issue by wire67** [esphome/issues#3790]
### The problem

how to switch component ledc ON at 50% on boot? 

for instance it isn't possible to specify `set_level` as Configuration variable.
`[set_level] is an invalid option for [output.ledc]. Please check the indentation.`

is it necessary to use an action to switch component ledc ON at 50% on boot? 

### Which version of ESPHome has the issue?

v2022.10.2 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

doesn't show it under /config/system

### What platform are you using?

ESP32

### Board

espcam

### Component causing the issue

ledc

### Example YAML snippet

```yaml
# Configure the output
output:
  - platform: ledc
    ######################################################
    # One buzzer leg connected to GPIO, the other to GND
    ######################################################
    pin: GPIO16
    id: buzzer_out
    frequency: 1000 Hz
    channel: 2
```

### Anything in the logs that might be useful for us?

```txt
[22:45:24][C][ledc.output:118]: LEDC Output:
[22:45:24][C][ledc.output:119]:   Pin GPIO16
[22:45:24][C][ledc.output:120]:   LEDC Channel: 2
[22:45:24][C][ledc.output:121]:   Frequency: 1000.0 Hz
```

**Comment by wire67** [comment]
``` 
esphome:
  on_boot:
    priority: 0
    then:
      ######################################################
      # Must be turned on before setting frequency & level
      ######################################################
      - output.turn_on: buzzer_out
      ######################################################
      # Frequency sets the wave size
      ######################################################
      - output.ledc.set_frequency:
          id: buzzer_out
          frequency: "1000Hz"
      ######################################################
      # level sets the %age time the PWM is on
      ######################################################
      - output.set_level:
          id: buzzer_out
          level: "50%"
```
