### ISSUE TITLE
Esp32 servo.detach not working

### ISSUE THREAD

**Issue by StefWI** [esphome/issues#3794]
### The problem

Whether using the "servo.detach" instruction in the service section or "auto_detach_time" in the servo section or both, the servo does not detach.
The message" Servo detached on auto_detach_time" appears in the log but the servo remains impossible to move manually.

### Which version of ESPHome has the issue?

2022.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant Core 2022.11.2

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

servo

### Example YAML snippet

```yaml
esphome:
  name: srv-001

wifi:
  networks:
  - ssid: !secret wifi_ssid_1
    password: !secret wifi_password_1
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: esphome.name
    password: !secret captive_portal_password

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - logger.log: "Start servo change"
        - servo.write:
            id: servo_air_input
            level: !lambda 'return level / 100.0;'
        - delay: 2s
        - logger.log: "Done"
        - servo.detach: servo_air_input
        - logger.log: "Detached"
    

ota:

captive_portal:

output:
  - platform: ledc
    pin: GPIO16
    id: pwm_output
    frequency: 50 Hz
    
servo:
  - id: servo_air_input
    output: pwm_output
    auto_detach_time: 1s
```

### Anything in the logs that might be useful for us?

```txt
[16:10:38][D][main:188]: Start servo change
[16:10:38][D][servo:062]: Servo new target: 0.150000
[16:10:38][D][servo:050]: Servo reached target
[16:10:39][D][servo:028]: Servo detached on auto_detach_time
[16:10:40][D][main:041]: Done
[16:10:40][D][main:045]: Detached
```
