### ISSUE TITLE
esp32_camera always idle

### ISSUE THREAD

**Issue by SebastianBrase85** [esphome/issues#3800]
### The problem

With

- A AI-Thinker ESP32-CAM
- Using a esp32_camera: component
- Added to Home Assistant

The Camera will always show idle state and only deliver the idle framerate, no matter what I do in Home assistant. If I open the camera entity or make a panel on the dashboard, the status (and framerate) stays the same.

### Which version of ESPHome has the issue?

ESPHome version 2022.10.2 compiled on Nov 17 2022

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Home Assistant 2022.3.8

### What platform are you using?

ESP32

### Board

AI-Thinker ESP32-CAM

### Example YAML snippet

```yaml
esphome:
  name: espcam
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Esp Cam Fallback Hotspot"
    password: "UeGqYlVrJUt4"

captive_portal:

logger:
api:
ota:


esp32_camera:
  name: esp32_cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 20fps
  idle_framerate: 1fps
  resolution: 1280x1024

# Example configuration entry
#esp32_camera_web_server:
#  - port: 8080
#    mode: stream
#  - port: 8081
#    mode: snapshot

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

binary_sensor:
  - platform: status
    name: "ESP32Cam status"
    
sensor:
  - platform: wifi_signal
    name: "ESP32Cam WiFi Signal"
    update_interval: 60s
    
light:
  - platform: binary
    output: gpio_4
    name: "ESP32Cam light"
```
