### ISSUE TITLE
Wrong values reported from Xiaomi Mijia BLE Sensor

### ISSUE THREAD

**Issue by hmax42** [esphome/issues#3801]
### The problem

The battery value is interspersed with wrong values.
it looks like some kind of rolling counter
![image](https://user-images.githubusercontent.com/22865687/202488770-06dfc2b4-54a5-4443-94b1-5d65523923a8.png)

the picture clearly shows what the real battery value is.
the values are reported via mqtt, so the error clearly comes from esphome:

>vind1/sensor/cgdk2_battery_level/state 24
>vind1/sensor/cgdk2_battery_level/state 24
>vind1/sensor/cgdk2_battery_level/state 24
>vind1/sensor/cgdk2_battery_level/state 24
>vind1/sensor/cgdk2_battery_level/state 24
>vind1/sensor/cgdk2_battery_level/state 4
>vind1/sensor/cgdk2_battery_level/state 4
>vind1/sensor/cgdk2_battery_level/state 4
>vind1/sensor/cgdk2_battery_level/state 4
>vind1/sensor/cgdk2_battery_level/state 4
>vind1/sensor/cgdk2_battery_level/state 4
>vind1/sensor/cgdk2_battery_level/state 4
>vind1/sensor/cgdk2_battery_level/state 24
>vind1/sensor/cgdk2_battery_level/state 24
>vind1/sensor/cgdk2_battery_level/state 24

### Which version of ESPHome has the issue?

ESPHome version 2022.8.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.4.6 (but not related)

### What platform are you using?

ESP32

### Board

m5stamp esp32 picod4

### Component causing the issue

Xiaomi Mijia BLE Sensors

### Example YAML snippet

```yaml
- platform: xiaomi_cgdk2
    mac_address: "xxxxxxxxxxxxxxxxxx"
    bindkey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    temperature:
      name: "CGDK2 Temperature"
      filters:
        - heartbeat: 60s
    humidity:
      name: "CGDK2 Humidity"
      filters:
        - heartbeat: 60s
    battery_level:
      name: "CGDK2 Battery Level"
      filters:
        - heartbeat: 60s
```

### Additional information

no custom firmware
paired/acquired bind key via modified android app
