### ISSUE TITLE
Sperate header & cpp files for custom components

### ISSUE THREAD

**Issue by dtila** [esphome/issues#3803]
### The problem

The build is ok but the linker give me the error:

`/config/plantwatering.yaml:12: undefined reference to `PlantDiscovery::PlantDiscovery()'`

All the documentation for a custom component is the code is in the header file. Can you have code in header and cpp file, when you build a custom component for esphome?

In case, how you specify the cpp files to be linked?

### Which version of ESPHome has the issue?

docker version - latest

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
esphome:
  name: plantwatering
  includes:
    - plantDiscovery.h
    - plant.h

sensor:
  
custom_component:
  - lambda: |-
      auto plant = new PlantDiscovery();
      return {plant};
    components:
    - id: plants
```
