### ISSUE TITLE
Access point and BLE Tacker don't work together

### ISSUE THREAD

**Issue by met67** [esphome/issues#3811]
### The problem

On an ESP32, enabling BLE tracker breaks access point fall-back functionality.

### Which version of ESPHome has the issue?

 2022.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.3

### What platform are you using?

ESP32

### Board

D1 Mini32 and TTGO T-Display

### Component causing the issue

ble_tracker

### Example YAML snippet

```yaml
substitutions:
  devicename: d1-mini32-test
  upper_devicename: D1 Mini32 Test
  deviceid: d1_mini32_test

esphome:
  name: ${devicename}
esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "ssidsample"
  password: "password"
  ap:
    ssid: "${upper_devicename}"
captive_portal:

logger:
  level: DEBUG

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
```

### Anything in the logs that might be useful for us?

```txt
Logs shows nothing, but AP doesn't show up

[D][wifi:401]: Found networks:
[D][wifi:450]: - 'FASTWEB-4LE5A7'[redacted] (48:3E:5E:31:58:B3) [redacted]▂▄▆█
[D][wifi:450]: - 'SKYWIFI_ZGPZG'[redacted] (00:A3:88:60:54:14) [redacted]▂▄▆█
[W][wifi:455]: No matching network found!
[D][wifi:386]: Starting scan...
[D][esp32_ble_tracker:809]: Found device 71:36:73:D5:36:A2 RSSI=-98
[D][esp32_ble_tracker:830]:   Address Type: RANDOM
[D][esp32_ble_tracker:834]:   TX Power: 2
[D][wifi:401]: Found networks:
[D][wifi:450]: - 'FASTWEB-4LE5A7'[redacted] (48:3E:5E:31:58:B3) [redacted]▂▄▆█
[D][wifi:450]: - 'Vodafone-WiFi'[redacted] (90:35:6E:A2:98:9A) [redacted]▂▄▆█
[W][wifi:455]: No matching network found!
[D][wifi:386]: Starting scan...
[D][wifi:401]: Found networks:
[D][wifi:450]: - 'Vodafone-30268270'[redacted] (90:35:6E:A2:98:98) [redacted]▂▄▆█
[D][wifi:450]: - 'FASTWEB-ZSPTLG'[redacted] (E0:19:54:9A:D7:BC) [redacted]▂▄▆█
[W][wifi:455]: No matching network found!
[D][wifi:386]: Starting scan...
[D][wifi:401]: Found networks:
[D][wifi:450]: - 'FASTWEB-EF73CB'[redacted] (A4:91:B1:EF:73:CB) [redacted]▂▄▆█
[D][wifi:450]: - 'FASTWEB-ZSPTLG'[redacted] (E0:19:54:9A:D7:BC) [redacted]▂▄▆█
[W][wifi:455]: No matching network found!
[D][esp32_ble_tracker:809]: Found device C7:A9:FF:34:B9:71 RSSI=-96
[D][esp32_ble_tracker:830]:   Address Type: RANDOM
[D][wifi:386]: Starting scan...
[D][wifi:401]: Found networks:
[D][wifi:450]: - 'TIM-46671990'[redacted] (78:81:02:99:D3:CB) [redacted]▂▄▆█
[D][wifi:450]: - 'WOW FI - FASTWEB'[redacted] (E2:19:54:9A:D7:BC) [redacted]▂▄▆█
[W][wifi:455]: No matching network found!
[D][esp32_ble_tracker:809]: Found device 7C:64:56:3A:B5:47 RSSI=-92
[D][esp32_ble_tracker:830]:   Address Type: PUBLIC
[D][wifi:386]: Starting scan...
[D][wifi:401]: Found networks:
[D][wifi:450]: - 'Vodafone-C01930190'[redacted] (80:16:05:7E:5C:6D) [redacted]▂▄▆█
[D][wifi:450]: - 'TIM-46671990'[redacted] (78:81:02:99:D3:CB) [redacted]▂▄▆█
[W][wifi:455]: No matching network found!
[W][wifi:585]: Restarting WiFi adapter...
[D][esp32_ble_tracker:809]: Found device 02:00:3B:67:8A:2A RSSI=-102
[D][esp32_ble_tracker:830]:   Address Type: RANDOM
[D][wifi:386]: Starting scan...
[I][wifi:141]: Starting fallback AP!
[C][wifi:210]: Setting up AP...
[C][wifi:212]:   AP SSID: 'D1 Mini32 Test'
[C][wifi:213]:   AP Password: ''
[C][wifi:222]:   IP Address: 192.168.4.1
[D][wifi:401]: Found networks:
[D][wifi:450]: - 'Vodafone-33905904'[redacted] (64:59:F8:6C:13:88) [redacted]▂▄▆█
[D][wifi:450]: - 'Vodafone-WiFi'[redacted] (64:59:F8:6C:13:8A) [redacted]▂▄▆█
[W][wifi:455]: No matching network found!
```

### Additional information

If I remove the esp32_ble_tracker section, access point fall back works.
