### ISSUE TITLE
Can't merge the final build (esp32-c3)

### ISSUE THREAD

**Issue by hmax42** [esphome/issues#3813]
### The problem

i am trying to compile a simple ble-client for my m5stamp-c3, see yaml below

i tried:
- 2022.1.1 , my windows pc, don't know why it won't update any futher, brings the error message further down at the logs about not being able to merge
- 2022.8.3, 2022.9.4 on a fresh installed(last week) macbook pro (x86_64) with kali linux, same error
- 2022.11.1 won't even install see (https://github.com/esphome/issues/issues/3812)

i checkd the path given.
the error is correct there is not file named bootloader__80m.bin
ony files like bootloader_dio_80m.bin or bootloader_qio_80m.bin and some more

i would really like to use the esp32-c3 with esphome

### Which version of ESPHome has the issue?

2022.8.3, 2022.9.4

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
substitutions:
  devicename: blescannerc3
#  deviceplatform: ESP32
#  deviceboard: wemos_d1_mini32

<<: !include common_gen.yaml

esphome:
  name: ${devicename}
  platformio_options:
    platform_packages:
      - framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.4
    platform:
      - https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
    
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
      
esp32_ble_tracker:
  scan_parameters:
    active: false
    interval: 1ms
    window: 1ms
    duration: 1s

logger:

ble_client:
  - mac_address: '60:03:03:94:2c:76'
    id: airquality
  - mac_address: '60:03:03:94:33:23'
    id: airquality2


sensor:
  - platform: template
    name: "Xiaomei 1 Temperature"
    id: xiaomei1_temperature
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    filters:
      - throttle: 20s
      - heartbeat: 20s
  - platform: template
    name: "Xiaomei 1 CO2"
    id: xiaomei1_co2
    device_class: "carbon_dioxide"
    state_class: "measurement"
    unit_of_measurement: "ppm"
    filters:
      - throttle: 20s
      - heartbeat: 20s
  - platform: template
    name: "Xiaomei 1 TVOC"
    id: xiaomei1_tvoc
    state_class: "measurement"
    unit_of_measurement: "mg/m3"
    filters:
      - throttle: 20s
      - heartbeat: 20s
  - platform: template
    name: "Xiaomei 1 HCHO"
    id: xiaomei1_hcho
    state_class: "measurement"
    unit_of_measurement: "mg/m3"
    filters:
      - throttle: 20s
      - heartbeat: 20s
  - platform: ble_client
    ble_client_id: airquality
    name: "Airquality level"
    service_uuid: "fff0"
    characteristic_uuid: "fff4"
    icon: "mdi:air"
    update_interval: never
    internal: True
    notify: true
    lambda: |-
      uint8_t* pdata = (uint8_t*) x.data();
      float temperature =  float((pdata[6] << 8) + pdata[7])/10;
      float tvoc =  float((pdata[10] << 8) + pdata[11]) / 1000;
      float hcho =  float((pdata[12] << 8) + pdata[13]) / 1000;
      float co2 =  (pdata[16] << 8) + pdata[17] - 150;
      id(xiaomei1_temperature).publish_state(temperature);
      id(xiaomei1_hcho).publish_state(hcho);
      id(xiaomei1_tvoc).publish_state(tvoc);
      id(xiaomei1_co2).publish_state(co2);
      return (float)x.size();
  - platform: template
    name: "Xiaomei 2 Temperature"
    id: xiaomei2_temperature
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    filters:
      - throttle: 20s
      - heartbeat: 20s
  - platform: template
    name: "Xiaomei 2 CO2"
    id: xiaomei2_co2
    device_class: "carbon_dioxide"
    state_class: "measurement"
    unit_of_measurement: "ppm"
    filters:
      - throttle: 20s
      - heartbeat: 20s
  - platform: template
    name: "Xiaomei 2 TVOC"
    id: xiaomei2_tvoc
    state_class: "measurement"
    unit_of_measurement: "mg/m3"
    filters:
      - throttle: 20s
      - heartbeat: 20s
  - platform: template
    name: "Xiaomei 2 HCHO"
    id: xiaomei2_hcho
    state_class: "measurement"
    unit_of_measurement: "mg/m3"
    filters:
      - throttle: 20s
      - heartbeat: 20s
  - platform: ble_client
    ble_client_id: airquality2
    name: "Airquality level 2"
    service_uuid: "fff0"
    characteristic_uuid: "fff4"
    icon: "mdi:air"
    update_interval: never
    internal: True
    notify: true
    lambda: |-
      uint8_t* pdata = (uint8_t*) x.data();
      float temperature =  float((pdata[6] << 8) + pdata[7])/10;
      float tvoc =  float((pdata[10] << 8) + pdata[11]) / 1000;
      float hcho =  float((pdata[12] << 8) + pdata[13]) / 1000;
      float co2 =  (pdata[16] << 8) + pdata[17] - 150;
      id(xiaomei2_temperature).publish_state(temperature);
      id(xiaomei2_hcho).publish_state(hcho);
      id(xiaomei2_tvoc).publish_state(tvoc);
      id(xiaomei2_co2).publish_state(co2);
      return (float)x.size();
```

### Anything in the logs that might be useful for us?

```txt
Linking .pioenvs/blescannerc3/firmware.elf
RAM:   [==        ]  17.2% (used 56516 bytes from 327680 bytes)
Flash: [=======   ]  74.7% (used 1370146 bytes from 1835008 bytes)
Building .pioenvs/blescannerc3/firmware.bin
esp32_create_combined_bin([".pioenvs/blescannerc3/firmware.bin"], [".pioenvs/blescannerc3/firmware.elf"])
usage: esptool merge_bin [-h] --output OUTPUT [--format {r,a,w}]
                         [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                         [--flash_mode {keep,qio,qout,dio,dout}]
                         [--flash_size FLASH_SIZE]
                         [--spi-connection SPI_CONNECTION]
                         [--target-offset TARGET_OFFSET]
                         [--fill-flash-size FILL_FLASH_SIZE]
                         <address> <filename> [<address> <filename> ...]
esptool merge_bin: error: argument <address> <filename>: [Errno 2] No such file or directory: '/home/gon/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/bin/bootloader__80m.bin'
*** [.pioenvs/blescannerc3/firmware.bin] Explicit exit, status 2
```

**Comment by ssieb** [comment]
```yaml
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0 
```
