### ISSUE TITLE
Sonoff Basic Devices Offline After Upgrading Firmware to 2022.11.1

### ISSUE THREAD

**Issue by grantalewis** [esphome/issues#3816]
### The problem

I have 14 different devices running ESPHome, most of them Sonoff Basics. After recently updating from 2022.10.2 to 2022.11.1, I started the OTA update process but then noticed that a couple devices didn't come back online after updating, so I stopped the upgrade and then rolled back to 2022.10.2. 

The yaml for one of the offline devices is below. Although this same yaml has worked for literally years, something's evidently disagreeing with the new firmware. I noticed the breaking change, "Don’t Use Base Network Manual IP for WiFi AP" [esphome#3902](https://github.com/esphome/esphome/pull/3902), but that doesn't seem like it would cause this kind of a problem.

Any guidance greatly appreciated.

### Which version of ESPHome has the issue?

2022.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.5

### What platform are you using?

ESP8266

### Board

Sonoff Basic

### Component causing the issue

unknown

### Example YAML snippet

```yaml
esphome:
  name: attic-sonoff

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.48
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    gateway: 192.168.1.1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Attic-Sonoff Fallback Hotspot"
    password: [redacted]

captive_portal:

api:

logger:

ota:
  password: [redacted]

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Attic Sonoff ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Attic Sonoff IP
    ssid:
      name: Attic Sonoff SSID
    bssid:
      name: Attic Sonoff BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Attic Sonoff Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Attic Sonoff WiFi Signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: Attic Sonoff Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: Attic Sonoff Relay
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
```

### Anything in the logs that might be useful for us?

```txt
Nothing of note.
```
