### ISSUE TITLE
PID Thermostat incorrect value transfer

### ISSUE THREAD

**Issue by CCChelios** [esphome/issues#3818]
### The problem

My goal: for the thermostat (air temperature) to set the temperature of the thermostat (heat carrier temperature), I pass the temperature value through the output template, but instead of the value 0-85, I get 0 or 1 on the thermostat.

### Which version of ESPHome has the issue?

 2022.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

PID Climate

### Example YAML snippet

```yaml
output:
  - platform: template
    id: target_temperature_ten
    type: float
    write_action:
      - climate.control:
          id: thermostat_on_heater_1
          mode: "HEAT"
          target_temperature: !lambda return state * 85;

climate:
  - platform: thermostat # Thermostat TEN #1
    name: "Thermostat on heater #1"
    id: thermostat_on_heater_1
    sensor: coolant_temp
    min_heating_off_time: 0s
    min_heating_run_time: 0s
    min_idle_time: 0s
    heat_deadband: 5
    heat_overrun: 0
    heat_action:
      - switch.turn_on: ten1
    idle_action:
      - switch.turn_off: ten1
    visual:
      min_temperature: 0 °C
      max_temperature: 85 °C
    preset:
      - name: Home
        default_target_temperature_low: 85 °C

  - platform: pid
    name: "Air thermostat"
    id: air_thermostat
    sensor: air_temp
    default_target_temperature: 21°C
    heat_output: target_temperature_ten
    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301
    visual:
      min_temperature: 10 °C
      max_temperature: 30 °C
```
