### ISSUE TITLE
Flicker effect can accidentally turn off the light

### ISSUE THREAD

**Issue by Joshfindit** [esphome/issues#382]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Ubuntu, esphome `1.13.1` installed via `pip`

**ESP (ESP32/ESP8266, Board/Sonoff):**

TTGO T7 (`board: nodemcu-32s`)

**Affected component:**

https://esphome.io/components/light/index.html

**Description of problem:**
It seems as though if the flicker 'value' goes to 0 or below, then the light simply turns off so will not continue flickering.
To be fair, I was testing a ridiculous setup of flicker intensity values up to 90%

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: monochromatic
    name: $upper_devicename
    id: mainlight
    output: output_component1
    default_transition_length: 300ms
    effects:
      - flicker:
          name: Flicker 5%
          alpha: 95%
          intensity: 5%
      - flicker:
          name: Flicker 25%
          alpha: 95%
          intensity: 25%
      - flicker:
          name: Flicker 50%
          alpha: 95%
          intensity: 50%
      - flicker:
          name: Flicker 90%
          alpha: 95%
          intensity: 90%

output:
  - platform: ledc
    id: output_component1
    pin: $ledpin
    frequency: 50000
    bit_depth: 10
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

Continued thanks for esphome; greatly enjoying trying all sorts of things with it.
