### ISSUE TITLE
"ERROR Error binary size: Unknown error from ESP" on Shelly-Plus-1PM (ESP32-IDF)

### ISSUE THREAD

**Issue by pfichtner** [esphome/issues#3822]
### The problem

After flashing a [Shelly-Plus-1PM](https://www.esphome-devices.com/devices/Shelly-Plus-1PM) via Tasmota OTA (initially installed Tasmota on that device) using a stripped configuration (see "Example YAML snippet") linked there, the ESP boots successfully the  built firmware. 
But when trying to push an newly build firmware using ESPHome's OTA mechanism the log output is: 
```
[...]
INFO Successfully compiled program.
INFO Resolving IP address of shelly-ssr.local
INFO  -> 192.xxx.xxx.xxx
INFO Uploading /config/.esphome/build/thename/.pioenvs/thename/firmware.bin (829168 bytes)
ERROR Error binary size: Unknown error from ESP
```

Even worse: The workaround described in https://github.com/esphome/issues/issues/2514#issuecomment-935920531 does not work because including `web_server` as well as `captive_portal`result in `This feature is only available with frameworks ['arduino'].` error messages. 

### Which version of ESPHome has the issue?

2022.11.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

no HA and not relevant

### What platform are you using?

ESP32-IDF

### Board

Shelly-Plus-1PM

### Component causing the issue

core

### Example YAML snippet

```yaml
substitutions:
  device_name: "Shelly Plus 1PM"

esphome:
  name: shelly-plus-1pm
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO26

switch:
  - platform: output
    id: "relay"
    name: "${device_name} Relay"
    output: "relay_output"

binary_sensor:
  - platform: gpio
    name: "${device_name} Switch"
    pin: GPIO4
    on_press:
      then:
        - switch.turn_on: "relay"
    on_release:
      then:
        - switch.turn_off: "relay"
    filters:
      - delayed_on_off: 50ms
```

**Comment by pfichtner** [comment]
No ideas/help for this issue available? 

Here some additional information, I added 
```
logger: 
  level: VERY_VERBOSE
```

so this is the output during the ota-update: 
```
[D][ota:147]: Starting OTA Update from ::FFFF:192.XXX.XXX.XXX...
[V][ota:178]: OTA features is 0x01
[V][ota:198]: Auth: Nonce is efXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[V][ota:218]: Auth: CNonce is 0011YYYYYYYYYYYYYYYYYYYYYYYYYYYY
[V][ota:225]: Auth: Result is 08150815081508150815081508150815
[V][ota:233]: Auth: Response is 08150815081508150815081508150815
[V][ota:261]: OTA size is 864704 bytes
[VV][scheduler:026]: set_timeout(name='onerror', timeout=5000)
[V][component:200]: Component ota took a long time for an operation (0.06 s).
[V][component:201]: Components should block for at most 20-30ms.
[VV][scheduler:196]: Running timeout 'onerror' with interval=5000 last_execution=376391 (now=381392)
[VV][scheduler:196]: Running interval 'update' with interval=60000 last_execution=337571 (now=397571)
[VV][scheduler:196]: Running interval 'update' with interval=60000 last_execution=339147 (now=399148)
```

I fear unfortunately little purposeful, exciting it would be, what happens inside `ota_backend_esp_idf.cpp` (I guess at least), there are however unfortunately no log calls.

**Comment by ssieb** [comment]
Add <https://esphome.io/components/ota.html#on-error> to see what the error is.

**Comment by pfichtner** [comment]
Added
```
ota:
  on_error:
    then:
      - logger.log:
          format: "OTA update error %d"
          args: ["x"]
  on_state_change:
    then:
      - logger.log:
          format: "OTA state change %d"
          args: ["state"]
```

result is 
```
[D][ota:147]: Starting OTA Update from ::FFFF:192.xxx.xxx.xxx...
[D][main:183]: OTA state change 1
[V][ota:178]: OTA features is 0x01
[V][ota:198]: Auth: Nonce is a6XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[V][ota:218]: Auth: CNonce is e23aYYYYYYYYYYYYYYYYYYYYYYYYYYYY
[V][ota:225]: Auth: Result is 08150815081508150815081508150815
[V][ota:233]: Auth: Response is 08150815081508150815081508150815
[V][ota:261]: OTA size is 866016 bytes
[VV][scheduler:026]: set_timeout(name='onerror', timeout=5000)
[D][main:183]: OTA state change 3
[D][main:189]: OTA update error 255
[V][component:200]: Component ota took a long time for an operation (0.11 s).
[V][component:201]: Components should block for at most 20-30ms.
[VV][scheduler:196]: Running timeout 'onerror' with interval=5000 last_execution=269076 (now=274076)
[VV][scheduler:196]: Running interval 'update' with interval=60000 last_execution=219889 (now=279889)
```

**Comment by hunhejj** [comment]
Did you find a solution @pfichtner?

**Comment by pfichtner** [comment]
No, I didn't. I added the things suggested by @ssieb  and added the logs to the issue. The problem still occurs: After flashing ESPHome to the device it's no longer updateable via OTA (which is really bad especially for Shelly-Devices that are usually mounted inside walls)

**Comment by hunhejj** [comment]
Same here with a Shelly Plus i4. I really don't want to dismount the wall switch whenever I would like to update the firmware 😕 .

**Comment by mikegerwitz** [comment]
I just ran into the same issue with a new Shelly 1 PM.  I'm using the `esphome/esphome` Docker image.

**But it seems that I was able to work around it.**  I'm not entirely certain of the exact sequence of events that led to it, but considering how recent the comments above are, I want to write a reply before any further investigation in the hope that it may be of some help.

1. Like @pfichtner, I flashed Tasmota first so that I could do this all OTA.
2. I created a fairly minimal base ESPHome configuration, since Tasmota didn't leave much space available (~370KiB).  See below for that configuration.
3. OTA flashing via Tasmota worked, _and subsequent OTA flashing using esphome CLI also worked_.
4. I attempted to modify the configuration to introduce `api` and `logging`, to use with HomeAssistant.  I received the error `ERROR Error binary size: Unknown error from ESP`.

The tl;dr of this post is: I was able to get a web interface flashed via the CLI, and then used that web interface to upload a full firmware image.  See below for the actual error from the OTA from the logs.

Here is the configuration I used initially, which was small enough to flash from Tasmota, which is derived from https://www.esphome-devices.com/devices/shelly-1pm/ (commented out blocks are what I removed to reduce the size of the resulting firmware):

(I'm not endorsing this configuration; it just happens to be what I use for testing, since I'm just trying to verify that I can get a Shelly 1PM working with ESPHome.)

```yaml
substitutions:
  devicename: "shelly-1pm-test"
  max_temp: "70.0"

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  comment: "Shelly 1PM"

wifi:
  ssid: ...
  password: ...
  # needed for hidden network; skip scan
  fast_connect: true
  # LOW/HIGH messed up; esphome/issues/issues/1532
  power_save_mode: HIGH
  # TODO: ap

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s

  - platform: uptime
    name: Uptime Sensor

  - platform: hlw8012
    cf_pin: GPIO05
    cf1_pin: GPIO13 # needed to compile, not available on 1PM
    sel_pin: GPIO14 # needed to compile, not available on 1PM
    power:
      name: "${devicename} power"
      unit_of_measurement: W
      id: "shelly1pm_power"
      device_class: power
      state_class: measurement
      accuracy_decimals: 0
      filters:
      # Map from sensor -> measured value
      - calibrate_linear:
          - 0.0 -> 1.0
          - 110.33186 -> 20.62
          - 131.01909 -> 24.32
          - 341.33920 -> 62.08
          - 5561.41553 -> 1000.0
          - 2975.51221 -> 535.7
          - 9612.66309 -> 1720.0
          - 14891.35352 -> 2679.0
      # Make everything below 2W appear as just 0W.
      - lambda: if (x < 2) return 0; else return x;
    update_interval: 10s

      #  - platform: total_daily_energy
      #    name: "${devicename} daily energy"
      #    power_id: "shelly1pm_power"
      #    device_class: energy
      #    state_class: measurement
      #    filters:
      #      - multiply: 0.001
      #    unit_of_measurement: kWh

  - platform: ntc
    sensor: temp_resistance_reading
    name: "${devicename} temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
        #    on_value_range:
        #      - above: ${max_temp}
        #        then:
        #          - homeassistant.event:
        #              event: esphome.overheat
        #              data:
        #                title: "${devicename} has overheated."

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm

  - platform: adc
    id: temp_analog_reading
    pin: A0

#logger:
#api:
ota:

# https://esphome.io/components/time/homeassistant.html
#time:
#  - platform: homeassistant
#    id: homeassistant_time


# Device Specific Config
output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO00
      inverted: true

# TODO: light?
switch:
  - platform: gpio
    name: ${devicename}
    pin: GPIO15
    id: shelly_relay
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
    filters:
      - delayed_on_off: 50ms # small delay for debouncing
    name: "Switch ${devicename}"
    on_press:
      then:
        - switch.toggle: shelly_relay
    internal: true
    id: switchid
```

I was (at the time) using a 1-2 month old `esphome/esphome` container, but I was not using a development build AFAIK, so I don't think #2514 was my problem.

I tried enabling the web interface and flashing, which ended up working:

```yaml
captive_portal:
web_server:
  port: 80
  auth:
    username: ...
    password: ...
```

(`captive_portal` I assume is unnecessary, but I added it when I was playing around, and forgot to remove it, and so I want to include it here just in case it does somehow make a difference.)

That gave me a web interface.  I wrote my full ESPHome configuration (uncommenting the above lines, and adding an `ap` to `wifi`), and attempted to update via OTA on the command line again, and still received the same error.

But taking the resulting firmware and uploading via the web interface worked.

But updates via the command line continued to fail with the same error.  But, I now had logs via the web interface, and saw that this was the error:

```
03:32:02  [D] [ota:147]                                                                                                                                                                                                                                 
Starting OTA Update from 192.168.X.X...                                                                                                                                                                                                              
03:32:03  [W] [ota:379]                                                                                                                                                                                                                                 
Timed out reading 4 bytes of data                                                                                                                                                                                                                       
03:32:03  [W] [ota:253]                                                                                                                                                                                                                                 
Reading size failed! 
```

At this point, before writing this, I wanted to see if anything changed on the newest `esphome` Docker image, so I updated it.  Unfortunately, I'm not sure what the previous image was (but it was from late November or early December).

I found the string "Reading size failed" in the generated `ota_component.cpp`, and was going to try to debug it (e.g. starting with increasing the timeout), until I noticed that:

After I got an OTA failure on the command line, re-running it a second time succeeded.

So that's where I left off.  I do have a second stock Shelly 1PM, and I can see how the process goes with that, but I'm not yet sure if I'll do that tonight or not.  I'll post back when I do.

**Comment by mikegerwitz** [comment]
I decided to try flashing my second Shelly 1PM, using the same process I did before:

1. Flash with Tasmota;
2. Flash with minimal image (I re-used the previous binary I had already built);
3. Flash a full configuration OTA via the CLI using the latest `esphome/esphome` Docker image.

This time, OTA via the CLI seems to be working every time.

Just to remove any doubt in constructing my configuration from my above message, here it is, without secrets:

```yaml
substitutions:
  devicename: "shelly-1pm-test"
  max_temp: "70.0"

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  comment: "Shelly 1PM"

wifi:
  ssid: ...
  password: ...
  # needed for hidden network; skip scan
  fast_connect: true
  # LOW/HIGH messed up; esphome/issues/issues/1532
  power_save_mode: HIGH
  # TODO: fallback
  ap:
    ssid: "${devicename} fallback"
    password: ...

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s

  - platform: uptime
    name: Uptime Sensor

  - platform: hlw8012
    cf_pin: GPIO05
    cf1_pin: GPIO13 # needed to compile, not available on 1PM
    sel_pin: GPIO14 # needed to compile, not available on 1PM
    power:
      name: "${devicename} power"
      unit_of_measurement: W
      id: "shelly1pm_power"
      device_class: power
      state_class: measurement
      accuracy_decimals: 0
      filters:
      # Map from sensor -> measured value
      - calibrate_linear:
          - 0.0 -> 1.0
          - 110.33186 -> 20.62
          - 131.01909 -> 24.32
          - 341.33920 -> 62.08
          - 5561.41553 -> 1000.0
          - 2975.51221 -> 535.7
          - 9612.66309 -> 1720.0
          - 14891.35352 -> 2679.0
      # Make everything below 2W appear as just 0W.
      - lambda: if (x < 2) return 0; else return x;
    update_interval: 10s

  - platform: total_daily_energy
    name: "${devicename} daily energy"
    power_id: "shelly1pm_power"
    device_class: energy
    state_class: measurement
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: ntc
    sensor: temp_resistance_reading
    name: "${devicename} temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - homeassistant.event:
              event: esphome.overheat
              data:
                title: "${devicename} has overheated."

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm

  - platform: adc
    id: temp_analog_reading
    pin: A0

logger:
api:
ota:

captive_portal:
web_server:
  port: 80
  auth:
    username: ...
    password: ...

# https://esphome.io/components/time/homeassistant.html
time:
  - platform: homeassistant
    id: homeassistant_time


# Device Specific Config
output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO00
      inverted: true

# TODO: light?
switch:
  - platform: gpio
    name: ${devicename}
    pin: GPIO15
    id: shelly_relay
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
    filters:
      - delayed_on_off: 50ms # small delay for debouncing
    name: "Switch ${devicename}"
    on_press:
      then:
        - switch.toggle: shelly_relay
    internal: true
    id: switchid
```

I was honestly hoping that flashing would fail so that I could maybe provide more insight.
