### ISSUE TITLE
esp32 crashing with abort and backtrace

### ISSUE THREAD

**Issue by apaperclip** [esphome/issues#3827]
### The problem

I upgraded one of my three esp32  to 2022.10 from 2021.9.3 to test for stability/regression. All three have essentially the same config. I noticed the ble sensors were going unavailable in ha and tracked it to this esp32 was restarting. I added an uptime sensor and memory sensors and finally caught a restart while it was plugged in and capturing logs. Memory looks fine so I do not it is a leak. I have not noticed any consistent uptime related to the crashes, but I would need more occurrences to rule that out,  The last reported uptime was 121,837s about 45s before the restart.

### Which version of ESPHome has the issue?

2022.10.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.11.4

### What platform are you using?

ESP32

### Board

esp32 devkit

### Example YAML snippet

```yaml
substitutions:
  esphome_name: esphome_ble_02

esphome:
  name: esphome_ble_02
  platform: ESP32
  board: mhetesp32devkit

wifi:
  ssid: "asdf"
  password: "asdf"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome Ble 02 Fallback Hotspot"
    password: "asdf"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

debug:



esp32_ble_tracker:
  scan_parameters:
    window: 300ms
    interval: 300ms
    duration: 15s
    active: false
    
binary_sensor:
  - platform: ble_presence
    ibeacon_uuid: 'asdf'
    name: "mailbox"
    device_class: opening
  - platform: ble_presence
    ibeacon_uuid: 'asdf'
    name: "mailbox motion 02"
    device_class: moving


switch:
  - platform: gpio
    name: "${esphome_name} onboard_LED"
    pin: 2
    restore_mode: ALWAYS_OFF

  - platform: restart
    name: ${esphome_name} restart
    id: restart_switch

sensor:
  - platform: wifi_signal
    name: "${esphome_name} WiFi Signal"
    update_interval: 300s
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp01 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp01 Humidity 02"
    battery_level:
      name: "Temp01 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp02 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp02 Humidity 02"
    battery_level:
      name: "Temp02 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp03 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp03 Humidity 02"
    battery_level:
      name: "Temp03 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp04 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp04 Humidity 02"
    battery_level:
      name: "Temp04 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp05 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp05 Humidity 02"
    battery_level:
      name: "Temp05 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature: 
      name: "Temp06 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp06 Humidity 02"
    battery_level:
      name: "Temp06 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp07 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp07 Humidity 02"
    battery_level:
      name: "Temp07 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp08 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp08 Humidity 02"
    battery_level:
      name: "Temp08 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp09 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp09 Humidity 02"
    battery_level:
      name: "Temp09 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp10 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp10 Humidity 02"
    battery_level:
      name: "Temp10 Battery Level 02"  
  #- platform: xiaomi_lywsd03mmc
  #  mac_address: DE:AD:BE:EF:CA:FE
  #  bindkey: "asdf"
  #  temperature:
  #    name: "Temp11 Temperature 02"
  #    filters:
  #     - lambda: return x * (9.0/5.0) + 32.0;
  #    unit_of_measurement: "°F"
  #  humidity:
  #    name: "Temp11 Humidity 02"
  #  battery_level:
  #    name: "Temp11 Battery Level 02" 
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp12 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp12 Humidity 02"
    battery_level:
      name: "Temp12 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp13 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp13 Humidity 02"
    battery_level:
      name: "Temp13 Battery Level 02"
  - platform: xiaomi_lywsd03mmc
    mac_address: DE:AD:BE:EF:CA:FE
    bindkey: "asdf"
    temperature:
      name: "Temp14 Temperature 02"
      filters:
       - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Temp14 Humidity 02"
    battery_level:
      name: "Temp14 Battery Level 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp01 RSSI 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp02 RSSI 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp03 RSSI 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp04 RSSI 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp05 RSSI 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp06 RSSI 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp07 RSSI 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp08 RSSI 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp09 RSSI 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp10 RSSI 02"
  # - platform: ble_rssi
  #   mac_address: DE:AD:BE:EF:CA:FE
  #   name: "Temp11 RSSI 02"
  #- platform: ble_rssi
  #  mac_address: DE:AD:BE:EF:CA:FE
  #  name: "Temp12 RSSI 02"
  #  filters:
  #  - throttle: 180s
  #- platform: ble_rssi
  #  mac_address: DE:AD:BE:EF:CA:FE
  #  name: "Temp13 RSSI 02"
  #  filters:
  #  - throttle: 180s
  #- platform: ble_rssi
  #  mac_address: DE:AD:BE:EF:CA:FE
  #  name: "mailbox RSSI"
  #  filters:
  #  - throttle: 180s   
  - platform: uptime
    name: ble02 Uptime Sensor
  - platform: debug
    free:
      name: Free Memory
  - platform: template
    name: "Free Heap Memory"
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    icon: "mdi:memory"
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: "b"
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
11-23 02:40:12.807[D][esp32_ble_tracker:809]: Found device A4:C1:38:91:CC:F6 RSSI=-60
11-23 02:40:12.838[D][esp32_ble_tracker:830]:   Address Type: PUBLIC
11-23 02:40:15.758[D][esp32_ble_tracker:809]: Found device A4:C1:38:46:38:D1 RSSI=-89
11-23 02:40:15.805[D][esp32_ble_tracker:830]:   Address Type: PUBLIC
11-23 02:40:18.696[D][esp32_ble_tracker:264]: Starting scan...
11-23 02:40:18.696abort() was called at PC 0x401e42df on core 0
11-23 02:40:18.696
11-23 02:40:18.696ELF file SHA256: 0000000000000000
11-23 02:40:18.696
11-23 02:40:18.711Backtrace: 0x4008f7dc:0x3ffd8440 0x4008fa59:0x3ffd8460 0x401e42df:0x3ffd8480 0x401e4326:0x3ffd84a0 0x401e3c41:0x3ffd84c0 0x401e3d18:0x3ffd84e0 0x400d90ad:0x3ffd8500 0x401395b1:0x3ffd8520 0x401346d2:0x3ffd8540 0x40090ace:0x3ffd8570
11-23 02:40:18.711
11-23 02:40:18.727Rebooting...
11-23 02:40:18.727ets Jun  8 2016 00:22:57
11-23 02:40:18.727
11-23 02:40:18.727rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
11-23 02:40:18.727configsip: 0, SPIWP:0xee
11-23 02:40:18.727clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
11-23 02:40:18.727mode:DIO, clock div:2
11-23 02:40:18.727load:0x3fff0018,len:4
11-23 02:40:18.775load:0x3fff001c,len:1044
11-23 02:40:18.775load:0x40078000,len:8896
11-23 02:40:18.775load:0x40080400,len:5828
11-23 02:40:18.775entry 0x400806ac
11-23 02:40:19.375[I][logger:243]: Log initialized
11-23 02:40:19.375[C][ota:465]: There have been 0 suspected unsuccessful boot attempts.
11-23 02:40:19.390[D][esp32.preferences:113]: Saving 1 preferences to flash...
11-23 02:40:19.390[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
11-23 02:40:19.390[I][app:029]: Running through setup()...
11-23 02:40:19.406[C][switch.gpio:011]: Setting up GPIO Switch 'esphome_ble_02 onboard_LED'...
```
