### ISSUE TITLE
Remote Receiver doesnt find RF codes

### ISSUE THREAD

**Issue by Flagun** [esphome/issues#383]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32S

**Affected component:**
https://esphome.io/components/remote_receiver.html#remote-receiver-binary-sensor

**Description of problem:**
when I try to sniff the RF codes in the consol I get only this respond: 
[D][remote.sony:064]: Received Sony: data=0x00000000, nbits=0

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: rf_ble_gateway
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "xxx"
  password: "xxx"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxx"

ota:
  password: "xxx"
  
remote_receiver:
  pin: 
    number: GPIO32
    inverted: true
  dump: all

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

when changed to dump: - rc_switch nothing is showing in the console
when changed to raw, the data is showing
