### ISSUE TITLE
unable to conf. pin 14 on esp32s2 for ADC, datasheet specifies pin 14 as ADC2_CH3

### ISSUE THREAD

**Issue by Zixim** [esphome/issues#3835]
### The problem

```
esp32:
  board: esp32-s2-saola-1
  variant: esp32s2
  framework:
    type: esp-idf
    version: recommended
```
trying to configure pin 14 as ADC, getting error : 
```
Failed config

sensor.adc: [source /config/esphome/home-buttons-01.yaml:64]
  platform: adc
  
  ESP32S2 doesn't support ADC on this pin.
  pin: GPIO14
  name: Battery Voltage
  id: batt_volt
  update_interval: 10s
  attenuation: 11db
```

### Which version of ESPHome has the issue?

2022.11.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Component causing the issue

adc

### Example YAML snippet

```yaml
sensor:
  # battery voltage adc
  - platform: adc
    pin: GPIO14
    name: $devicename Battery Voltage
    id: batt_volt
    update_interval: 10s
    attenuation: 11db
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
