### ISSUE TITLE
[ESP32-IDF] PullUp doesnt work on IDF framework

### ISSUE THREAD

**Issue by mobrembski** [esphome/issues#3836]
### The problem

Hi All!

Just want to notice - when using ESP32-IDF framework (not Arduino one) unfortunately PullUp configuration doesnt work.
Please see my config.

After running build with following configration I2C doesnt work. But i discovered, that problem is located with lack of pull up.
I've checked debug logs (sorry, i havent saved them) - but ESPHome states that it sets pullup on 21/22 pin. Checked voltage on that pins, but they're not pulled up so I2C is not working.

It's not related to I2C itself or those two particular pins. I've tested pullups also by setting 21/22 pin to GPIO input with pull up - it also doesn't set proper pull up.

Switching to Arduino framework and it works correctly. However my board doesn't have Arduino-compatible ethernet PHY :(
So i will be very happy to have this fixed.

### Which version of ESPHome has the issue?

dev 29th November 2022

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

dtWonder 4 Relays Ethernet Board

### Component causing the issue

I2C/GPIO

### Example YAML snippet

```yaml
substitutions:
  device_name: "serverroom-node"
  friendly_name: "ServerRoom Node"
  project_name: "athom.smart-plug-v2"
  project_version: "1.0"
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${device_name}"
  name_add_mac_suffix: false
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32-evb
  framework:
     type: esp-idf
     sdkconfig_options:
       CONFIG_ETH_RMII_CLK_OUTPUT : y
       LOG_LOCAL_LEVEL: ESP_LOG_DEBUG

preferences:
  flash_write_interval: 2min

api:

ota:

mdns:
  disabled: false

# web_server:
#   port: 80

# Example configuration entry
debug:
  update_interval: 5s

# Logger must be at least debug (default)
logger:
  level: debug

wifi:
  ap:
    ap_timeout: 1min
  domain: .stal
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  networks:
  - ssid: 
    password: 
    priority: 0.0
  use_address: serverroom-node.stal

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime Sensor"
  - platform: bme280
    temperature:
      name: "${friendly_name} Temperature"
      oversampling: 16x
    pressure:
      name: "${friendly_name} Pressure"
    humidity:
      name: "${friendly_name} Humidity"
    address: 0x76
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
Unfortunately, havent saved logs from ESP-IDF, but you have to belive me that debug logs clearly states that it configures pins with PullUp enabled.
```
