### ISSUE TITLE
Custom Uart Sensor Not publishing

### ISSUE THREAD

**Issue by Morbidbystandard** [esphome/issues#3837]
### The problem

I'm not getting a string published using a custom uart sensor.

### Which version of ESPHome has the issue?

2022.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.4

### What platform are you using?

ESP32

### Board

esp-wrover

### Component causing the issue

Uart

### Example YAML snippet

```yaml
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  
sensor:
- platform: custom
  lambda: |-
    auto EZO = new scaleSensor(id(uart_bus));
    App.register_component(EZO);
    return {EZO};
  sensors:
    name: "Ph Sensor"
    unit_of_measurement: Ph
    accuracy_decimals: 2
    filters:
      - offset: +0.22
```

### Anything in the logs that might be useful for us?

```txt
#include "esphome.h"

class scaleSensor : public PollingComponent, public UARTDevice, public sensor::Sensor{
 public:
  scaleSensor(UARTComponent *parent) : PollingComponent(1000), UARTDevice(parent) {}
    float weight = weight;
  
  void setup() override {
    // nothing to do here
  }
  
  void loop() override {
     char character;
    while(available()){
      character = read();
      if(character == '\n')
      break;
    }
  }
  
  void update() {
    publish_state(weight);
  }
};
```
