### ISSUE TITLE
rp2040_pwm does not work properly for frequencies lower than ~2khz

### ISSUE THREAD

**Issue by JasonYuJjyu** [esphome/issues#3841]
### The problem

The output component rp2040_pwm does not function correctly when the frequency is set to below ~2khz. Doing so is desirable when using PWM to drive servos at 50hz.

The rp2040 clock divisor has a valid range of 1.f <= value < 256.f. Setting lower frequencies result in the divisor being set far beyond this range:

https://github.com/esphome/esphome/blob/c5f59fad626534c55d58ad6927ab994cafc6a7b3/esphome/components/rp2040_pwm/rp2040_pwm.cpp#L26

Fixing this for lower frequencies can be done by increasing the PWM wrap until the divisor becomes valid. Currently it is hard coded, maybe this could be user configurable.

### Which version of ESPHome has the issue?

v2022.11.3

### What type of installation are you using?

Docker

### What platform are you using?

RP2040

### Board

Raspberry PI pico w

### Component causing the issue

components/rp2040_pwm

### Example YAML snippet

```yaml
esphome:
  name: picow-servo-test

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

api:
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: my_servo
            level: !lambda 'return level / 100.0;'
    
output:
  - platform: rp2040_pwm
    id: pwm_output
    pin: 15
    frequency: 50hz

servo:
  - id: my_servo
    output: pwm_output
```
