### ISSUE TITLE
Waveshare E-Paper Display not working on rp2040

### ISSUE THREAD

**Issue by LouisMT** [esphome/issues#3844]
### The problem

I have a Raspberry Pi Pico W and a Waveshare Pico e-Paper 2.9 (B).

But the display won't work. The pins are according to the [schematic](https://www.waveshare.net/w/upload/6/62/Pico-ePaper-2.9.pdf).

I'm not sure if I can map the GPIO pins like this (GP8 = GPIO8)?

### Which version of ESPHome has the issue?

2022.11.3

### What type of installation are you using?

Docker

### What platform are you using?

RP2040

### Board

rpipicow

### Component causing the issue

waveshare_epaper

### Example YAML snippet

```yaml
esphome:
  name: epd

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

spi:
  clk_pin: GPIO10
  mosi_pin: GPIO11

display:
  - platform: waveshare_epaper
    cs_pin: GPIO9
    dc_pin: GPIO8
    busy_pin: GPIO13
    reset_pin: GPIO12
    model: 2.90in-b
    lambda: |-
      it.print(0, 0, id(roboto), "Hello World!");
```

### Anything in the logs that might be useful for us?

```txt
[C][spi:101]: SPI bus:
[C][spi:102]:   CLK Pin: GPIO10
[C][spi:104]:   MOSI Pin: GPIO11
[C][spi:106]:   Using HW SPI: NO
[C][waveshare_epaper:658]: Waveshare E-Paper
[C][waveshare_epaper:658]:   Rotations: 0 °
[C][waveshare_epaper:658]:   Dimensions: 128px x 296px
[C][waveshare_epaper:659]:   Model: 2.9in (B)
[C][waveshare_epaper:660]:   Reset Pin: GPIO12
[C][waveshare_epaper:661]:   DC Pin: GPIO8
[C][waveshare_epaper:662]:   Busy Pin: GPIO13
[C][waveshare_epaper:663]:   Update Interval: 1.0s
[E][waveshare_epaper:119]: Timeout while displaying image!
```
