### ISSUE TITLE
Presetting the integral sum of the PID controller

### ISSUE THREAD

**Issue by CCChelios** [esphome/issues#3845]
### The problem

How to set an unnecessary value of a variable integral_term at startup? The reset function exists, but the setting does not. I use pid climate to maintain the temperature in the house, the system will adapt in about 5 hours. After each reboot, it's not comfortable to wait. Or how to save the data.

### Which version of ESPHome has the issue?

 2022.11.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
- platform: pid
    name: "Air thermostat"
    id: air_thermostat
    sensor: air_temp
    default_target_temperature: 21°C
    heat_output: target_temperature_ten
    control_parameters:
      kp: 0.01
      ki: 0.00001
      kd: 0
    visual:
      min_temperature: 10 °C
      max_temperature: 30 °C
```
