### ISSUE TITLE
MQTT_Custom_Component not working

### ISSUE THREAD

**Issue by AquaMCU** [esphome/issues#3846]
### The problem

I tried to follow the documentation for the MQTT custom component. It does not work :( https://esphome.io/custom/custom_component.html#mqtt-custom-component

First I get:
src/lora_gateway.h:3:63: error: expected class-name before '{' token
 class LORAGateway : public Component, public CustomMQTTDevice {

When I add #include <custom_mqtt_device.h> I get the error
In file included from src/main.cpp:39:0:
src/lora_gateway.h:2:32: fatal error: custom_mqtt_device.h: No such file or directory

### Which version of ESPHome has the issue?

 v2022.11.1 

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
esphome:
  name: gateway
  libraries:
    - SPI
    - "LoRa"

  includes:
    - lora_gateway.h

  
esp32:
  board: heltec_wifi_lora_32_V2
  framework:
    type: arduino

logger:
   level: DEBUG

[...]
sensor:
- platform: custom
  lambda: |-
    auto LORA_Gatway = new LORAGateway();
    return {LORA_Gateway};
  sensors:
    name: "LORA Data"
```

### Anything in the logs that might be useful for us?

```txt
Please update the doc, so I can follow easyly. BTW. Awesome project!
```
