### ISSUE TITLE
Cannot run script with mode: queued and parameters

### ISSUE THREAD

**Issue by wizu** [esphome/issues#3848]
### The problem

I'm trying to send multiple sms messages in a loop with a delay between each message. I'm using a script for that.

### Which version of ESPHome has the issue?

2022.11.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.11.4

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

script

### Example YAML snippet

```yaml
script:
    -   id: send_sms
        mode: queued
        parameters:
            number: string
            message: string
        then:
            - sim800l.send_sms:
                id: sim
                recipient: !lambda return number;
                message: !lambda return message;
            - delay: 2s

sim800l:
    id: sim
    on_sms_received:
        - logger.log:
            format: "Incoming sms from '%s' message '%s'"
            args: ["sender.c_str()", "message.c_str()"]
        - lambda: |-
                    std::vector<std::string> phones = split(id(receivers).state);
                    for (std::vector<std::string>::iterator phone = phones.begin(); phone != phones.end(); ++phone) {
                        std::string phoneNumber(phone->c_str());
                        std::string fullMessage(message.c_str());
                        id(send_sms)->execute(phoneNumber, fullMessage);

                        //id(sim).send_sms(phone->c_str(), message.c_str());
                    }
                }
```

### Anything in the logs that might be useful for us?

```txt
In file included from src/esphome.h:41:0,
                 from src/main.cpp:3:
src/esphome/components/script/script.h: In instantiation of 'void esphome::script::QueueingScript<Ts>::loop() [with Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]':
src/esphome/components/script/script.h:106:5:   required from 'void esphome::script::QueueingScript<Ts>::execute(Ts ...) [with Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]'
/config/osp.yaml:84:57:   required from here
src/esphome/components/script/script.h:117:7: error: no matching function for call to 'esphome::script::QueueingScript<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::trigger()'
       this->trigger();
       ^
In file included from src/esphome/components/api/user_services.h:6:0,
                 from src/esphome/components/api/api_server.h:12,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/automation.h:95:8: note: candidate: void esphome::Trigger<Ts>::trigger(Ts ...) [with Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]
   void trigger(Ts... x) {
        ^
src/esphome/core/automation.h:95:8: note:   candidate expects 2 arguments, 0 provided
```

### Additional information

It is working with: 
`id(sim).send_sms(phone->c_str(), message.c_str());`
but it only sends sms to the last number from the phones list. split() is my function from other file, it is working great and I think that it is not releated. There should be some kind of delay and that's why I thought of script mode: queued
