### ISSUE TITLE
Time-Based cover actions issue

### ISSUE THREAD

**Issue by kluszczyn** [esphome/issues#385]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**Affected component:**

https://esphome.io/components/cover/time_based.html

**Description of problem:**
Actions `cover.open`, `cover.stop` and `cover.close` not working for time-based cover component.
Action `cover.control` is working as expected.

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: gpio
    name: "btn markiza down"
    id: markiza_down
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - cover.control:
            id: id_markiza
            position: 100%
        # - cover.open: id_markiza <-not working
    on_release:
      then:
        - cover.control:
            id: id_markiza
            stop: true
        # - cover.stop: id_markiza <-not working


cover:
  - platform: time_based
    name: "Markiza"
    id: id_markiza

    open_action:
      - switch.turn_off: relayB
      - delay: 200ms
      - switch.turn_on: relayA
    open_duration: 40s

    close_action:
      - switch.turn_off: relayA
      - delay: 200ms
      - switch.turn_on: relayB
    close_duration: 40s

    stop_action:
      - switch.turn_off: relayA
      - switch.turn_off: relayB

```

**Traceback (if applicable):**

```
N/A
```

**Additional information and things you've tried:**
