### ISSUE TITLE
Sensor on_value_range with multiple ranges does not trigger moving into the lowest range

### ISSUE THREAD

**Issue by t0mas** [esphome/issues#3852]
### The problem

I have a sensor defined like this:
`  - platform: pm1006
    update_interval: 20s
    pm_2_5:
      name: "Climate2 PM 2.5"
      on_value_range:
        - above: 0
          below: 15
          then:
            - light.turn_on:
                id: led3
                brightness: 25%
                red: 0%
                green: 100%
                blue: 0%
        - above: 15
          below: 25
          then:
            - light.turn_on:
                id: led3
                brightness: 36%
                red: 100%
                green: 75%
                blue: 0%
        - above: 25
          then:
            - light.turn_on:
                id: led3
                brightness: 30%
                red: 100%
                green: 0%
                blue: 0%`

When the pm2.5 value moves from lets say 6 to 16 it will turn from green to orange (the middle option), when it goes above 25 it will turn red (the lower one in the code). Then on the way back down it goes from red to orange, but after going below 15 it does not trigger the green action.

From the documentation I expect the first range to trigger if the value goes from somewhere above 15 to something below, but it does not seem to do so. Looking at the generated code it does create a sensor::ValueRangeTrigger() and sets the correct min and max values, then assigns it to an Automation that has the right light::LightControlAction() assigned to it.

Only difference I can see in the generated code compared to the other two ranges it the place at which it does this. The code for the first automation is spread out a bit more, because the definition of the light is in between. But semantically it shouldn't make a difference and it makes all the same calls.

Is there any way to debug what's happening and why it isn't triggering the green option?

### Which version of ESPHome has the issue?

2022.11.3

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

sensor

### Example YAML snippet

```yaml
# Simplified to isolate the issue:
esphome:
  name: esp-climate2

esp8266:
  board: d1_mini

wifi:
  ssid: "removed"
  password: "removed"

uart:
  rx_pin: D5
  tx_pin: D6
  baud_rate: 9600

sensor:
  - platform: pm1006
    update_interval: 20s
    pm_2_5:
      name: "Climate2 PM 2.5"
      on_value_range:
        - above: 0
          below: 15
          then:
            - light.turn_on:
                id: led3
                brightness: 25%
                red: 0%
                green: 100%
                blue: 0%
        - above: 15
          below: 25
          then:
            - light.turn_on:
                id: led3
                brightness: 36%
                red: 100%
                green: 75%
                blue: 0%
        - above: 25
          then:
            - light.turn_on:
                id: led3
                brightness: 30%
                red: 100%
                green: 0%
                blue: 0%

light:
  - platform: neopixelbus
    id: ledstrip
    type: GRB
    variant: WS2812
    pin: D7
    num_leds: 3
    internal: true
  - platform: partition
    id: led3
    internal: true
    segments:
      - id: ledstrip
        from: 2
        to: 2
```

**Comment by t0mas** [comment]
Problem found, in ```sensor/automation.h``` the ```ValueRangeTrigger``` uses this code:
```
in_range = local_min <= state && state <= local_max;
```
So the ranges are inclusive, while the labels "above" and "below" imply exclusive ranges. The documentation uses this example:

```
    on_value_range:
      - below: 5.0
        then:
          - switch.turn_on: relay_1
      - above: 5.0
        below: 10.0
        then:
          - switch.turn_on: relay_2
      - above: 10.0
        then:
          - switch.turn_on: relay_3
```

Which when it receives 5.0 as a value would trigger both relay_1 and relay_2 and then not re-trigger relay_1 once the value goes to (for example) 4.0. That's not a problem if the actions are fully independent, but if the actions override each other (like my example changing light colors) it will cause one of the ranges to seem like it never triggers.

This could be solved by changing the documentation to state that the ranges are inclusive and make the example ```below 4.99``` and ```below 9.99``` or change the code for the ranges to be exclusive so they fit the natural language of "above x" meaning "higher than x and not x itself"
