### ISSUE TITLE
Modbus Switch reset entire register

### ISSUE THREAD

**Issue by nurachese** [esphome/issues#3857]
### The problem

Hi all,
I'm new in ESPhome, please be patient with me :-)
I have an issue in Modbus Switch behaviour: I have a 16 inputs & 16 outputs modbus board, I configured the code with 16 Modbus Binary Sensors (perfectly working) and 16 Modbus Switches reading and writing on a 16 bit holding register (0x70).
Each activation of any switch activates the right output but at the same time resets all other 15.
It seems that the library is not taking into account the outputs state before sending the command.

Thank you in advance

Marcello 

### Which version of ESPHome has the issue?

2022.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.4

### What platform are you using?

ESP32

### Board

WT32-ETH01

### Component causing the issue

Modbus Controller Switch

### Example YAML snippet

```yaml
uart:
  id: modbusio
  tx_pin: GPIO17
  rx_pin: GPIO5
  baud_rate: 19200
  stop_bits: 1
modbus:
  id: modbus1


modbus_controller:    ## I simplified with only 2 inputs and 3 outputs
  - id: moduloio1
     address: 0x1
     modbus_id: modbus1
     setup_priority: -10
     update_interval: 100ms
binary_sensor:
  - platform: modbus_controller
     modbus_controller_id: moduloio1
     name: "Pulsanti luci ingresso"
     id: Pulsanti_luci_ingresso
     register_type: holding
     address: 0xC0  bitmask: 1
  - platform: modbus_controller
     modbus_controller_id: moduloio1
     name: "Pulsanti luci soggiorno"
     id: Pulsanti_luci_soggiorno
     register_type: holding
     address: 0xC0

switch:
  - platform: modbus_controller
     modbus_controller_id: moduloio1
     name: "Luce pulsanti luci ingresso/soggiorno/cucina"
     id: Luce_pulsanti_luci_ingresso_soggiorno_cucina
     register_type: holding
     address: 0x70
     bitmask: 1
  - platform: modbus_controller
     modbus_controller_id: moduloio1
     name: "Luce pulsante balcone soggiorno"
     id: Luce_pulsante_balcone_soggiorno
     register_type: holding
     address: 0x70
     bitmask: 2
  - platform: modbus_controller
     modbus_controller_id: moduloio1
	 name: "Luce pulsante balcone camere"
	 id: Luce_pulsante_balcone_camere
	 register_type: holding
	 address: 0x70
	 bitmask: 4
```

### Anything in the logs that might be useful for us?

```txt
[modbus_controller:113]: Duplicate modbus command found: type=0x3 address=192 count=1
[modbus_controller:113]: Duplicate modbus command found: type=0x3 address=112 count=1
```

**Comment by nurachese** [comment]
> ### The problem
> Hi all, I'm new in ESPhome, please be patient with me :-) I have an issue in Modbus Switch behaviour: I have a 16 inputs & 16 outputs modbus board, I configured the code with 16 Modbus Binary Sensors (perfectly working) and 16 Modbus Switches reading and writing on a 16 bit holding register (0x70). Each activation of any switch activates the right output but at the same time resets all other 15. It seems that the library is not taking into account the outputs state before sending the command.
> 
> Thank you in advance
> 
> Marcello
> 
> ### Which version of ESPHome has the issue?
> 2022.11.3
> 
> ### What type of installation are you using?
> Home Assistant Add-on
> 
> ### Which version of Home Assistant has the issue?
> 2022.11.4
> 
> ### What platform are you using?
> ESP32
> 
> ### Board
> WirelessTag WT32-ETH01
> 
> ### Component causing the issue
> Modbus Controller Switch
> 
> ### Example YAML snippet
> ```yaml
> uart:
>   id: modbusio
>   tx_pin: GPIO17
>   rx_pin: GPIO5
>   baud_rate: 19200
>   stop_bits: 1
> modbus:
>   id: modbus1
> 
> 
> modbus_controller:    ## I simplified with only 2 inputs and 3 outputs
>   - id: moduloio1
>     address: 0x1
>     modbus_id: modbus1
>     setup_priority: -10
>     update_interval: 100ms
> binary_sensor:
>   - platform: modbus_controller
>     modbus_controller_id: moduloio1
>     name: "Pulsanti luci ingresso"
>     id: Pulsanti_luci_ingresso
>     register_type: holding
>     address: 0xC0
>     bitmask: 1
>   - platform: modbus_controller
>     modbus_controller_id: moduloio1
>     name: "Pulsanti luci soggiorno"
>     id: Pulsanti_luci_soggiorno
>     register_type: holding
>     address: 0xC0
>     bitmask: 2
> switch:
>   - platform: modbus_controller
>     modbus_controller_id: moduloio1
>     name: "Luce pulsanti luci ingresso/soggiorno/cucina"
>     id: Luce_pulsanti_luci_ingresso_soggiorno_cucina
>     register_type: holding
>     address: 0x70
>     bitmask: 1
>   - platform: modbus_controller
>     modbus_controller_id: moduloio1
>     name: "Luce pulsante balcone soggiorno"
>     id: Luce_pulsante_balcone_soggiorno
>     register_type: holding
>     address: 0x70
>     bitmask: 2
>   - platform: modbus_controller
>     modbus_controller_id: moduloio1
>     name: "Luce pulsante balcone camere"
>     id: Luce_pulsante_balcone_camere
>     register_type: holding
>     address: 0x70
>     bitmask: 4
> ```
> 
> ### Anything in the logs that might be useful for us?
> ```
> [15:08:05][V][modbus_controller:156]: 2 modbus commands already in queue
> [15:08:05][V][modbus_controller:125]: Range : 70 Size: 1 (3) skip: 0
> [15:08:05][W][modbus_controller:113]: Duplicate modbus command found: type=0x3 address=112 count=1
> [15:08:05][V][modbus_controller:125]: Range : C0 Size: 1 (3) skip: 0
> [15:08:05][V][modbus_controller:036]: Sending next modbus command to device 1 register 0x70 count 1
> [15:08:05][V][modbus:194]: Modbus write: 01.06.00.70.00.02.09.D0 (8)
> 
> In this case I turned on the switch corresponding to bit #2, but since bit #8 was already on, the right command should be Modbus write: 01.06.00.70.00.0A+CRC, where 0xA=0x8+0x2
> I tried to solve by using lambdas but no success
> ```
> 
> ### Additional information
> _No response_

@martgras can you help me?

**Comment by nurachese** [comment]
Solved using @martgras modbus_number_write and template switches:

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/martgras/esphome
      #ref: modbus-fix
      #ref: modbus-duplicate
      #ref: modbus_controller
      ref: modbus_number_write
    components: [modbus_controller]

uart:
  id: modbusio
  tx_pin: GPIO17
  rx_pin: GPIO5
  baud_rate: 19200
  stop_bits: 1

modbus:
  #flow_control_pin: 5
  id: modbus1

modbus_controller:
  - id: moduloio1
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 100ms

binary_sensor:
- platform: modbus_controller
  modbus_controller_id: moduloio1
  name: "Pulsanti luci ingresso"
  id: Pulsanti_luci_ingresso
  register_type: holding
  address: 0xC0
  bitmask: 1
  #response_size: 2
- platform: modbus_controller
  modbus_controller_id: moduloio1
  name: "Pulsanti luci soggiorno"
  id: Pulsanti_luci_soggiorno
  register_type: holding
  address: 0xC0
  bitmask: 2

number:
  - platform: modbus_controller
    modbus_controller_id: moduloio1
    id: Uscite_modulo1
    name: "Uscite modulo1"
    address: 0x70
    value_type: U_WORD
    lambda: "return  x * 1.0; "
    write_lambda: |-
      ESP_LOGD("main","Modbus Number incoming value = %f",x);
      uint16_t uscite1 = x ;
      payload.push_back(uscite1);
      return x * 1.0 ;
    ## multiply is ignored because lamdba is used
    #multiply: 1.0
switch:
  - platform: template
    name: "Luce pulsanti luci ingresso/soggiorno/cucina"
    id: Luce_pulsanti_luci_ingresso_soggiorno_cucina
    lambda: |-
      uint16_t UsciteM1 = id(Uscite_modulo1).state;
      if (bitRead(UsciteM1,0)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
       - number.set:
          id: Uscite_modulo1
          value: !lambda |-
           return id(Uscite_modulo1).state + 1;
    turn_off_action:
       - number.set:
          id: Uscite_modulo1
          value: !lambda |-
           return id(Uscite_modulo1).state - 1;
  - platform: template
    name: "Luce pulsante balcone soggiorno"
    id: Luce_pulsante_balcone_soggiorno
    lambda: |-
      uint16_t UsciteM1 = id(Uscite_modulo1).state;
      if (bitRead(UsciteM1,1)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
       - number.set:
          id: Uscite_modulo1
          value: !lambda |-
           return id(Uscite_modulo1).state + 2;
    turn_off_action:
       - number.set:
          id: Uscite_modulo1
          value: !lambda |-
           return id(Uscite_modulo1).state - 2;
  - platform: template
    name: "Luce pulsante balcone camere"
    id: Luce_pulsante_balcone_camere
    lambda: |-
      uint16_t UsciteM1 = id(Uscite_modulo1).state;
      if (bitRead(UsciteM1,2)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
       - number.set:
          id: Uscite_modulo1
          value: !lambda |-
           return id(Uscite_modulo1).state + 4;
    turn_off_action:
       - number.set:
          id: Uscite_modulo1
          value: !lambda |-
           return id(Uscite_modulo1).state - 4;
```
