### ISSUE TITLE
Multiple `pid` climates cannot be differentiated in the logs

### ISSUE THREAD

**Issue by nagyrobi** [esphome/issues#3858]
### The problem

I made a central heating system with 7 climates, each with its own PID. When I try to run Autotune for all of them, unfortunately the log doesn't show which message belongs to which climate:
```
[09:07:09][I][pid.autotune:134]: PID Autotune:
[09:07:09][I][pid.autotune:179]:   Autotune is still running!
[09:07:17][I][pid.autotune:134]: PID Autotune:
[09:07:17][I][pid.autotune:179]:   Autotune is still running!
[09:07:19][I][pid.autotune:134]: PID Autotune:
[09:07:19][I][pid.autotune:179]:   Autotune is still running!
[09:07:27][I][pid.autotune:134]: PID Autotune:
[09:07:27][I][pid.autotune:179]:   Autotune is still running!
[09:07:29][I][pid.autotune:134]: PID Autotune:
[09:07:29][I][pid.autotune:179]:   Autotune is still running!
[09:07:37][I][pid.autotune:134]: PID Autotune:
[09:07:37][I][pid.autotune:179]:   Autotune is still running!
[09:07:39][I][pid.autotune:134]: PID Autotune:
[09:07:39][I][pid.autotune:179]:   Autotune is still running!
[09:07:47][I][pid.autotune:134]: PID Autotune:
[09:07:47][I][pid.autotune:179]:   Autotune is still running!
[09:07:49][I][pid.autotune:134]: PID Autotune:
[09:07:49][I][pid.autotune:179]:   Autotune is still running!
[09:07:57][I][pid.autotune:134]: PID Autotune:
[09:07:57][I][pid.autotune:179]:   Autotune is still running!
[09:07:59][I][pid.autotune:134]: PID Autotune:
[09:07:59][I][pid.autotune:179]:   Autotune is still running!
[09:08:07][I][pid.autotune:134]: PID Autotune:
[09:08:07][I][pid.autotune:179]:   Autotune is still running!
...
```
Although each climate has it's own `id` and `name`, it can't be told which of these logger messages belong to which climate...

It's not really useful to run the autotunes separately because they can influence each other (rooms of the same building) so for accurate measurement it's required to run them all in parallel.

Another annoying issue is that the INFO message "_Autotune is still running!_" is shown every 10 seconds per instance. An autotune procedure for a heating system takes several hours. Log is flooded even in INFO level.

With multiple PIDs running Autotune it gets even worse, and when one completes, the printed results disappear due to overscrolling as the other PID instances still running keep flooding the log with the same still running message.

After hours of running, result appears like this:

```
 PID Autotune finished!
 PID Autotune:
   State: Succeeded!
   Could not reliable determine oscillation amplitude, PID parameters may be inaccurate!
     Please make sure you eliminate all outside influences on the measured temperature.
   Oscillation Frequency is not symmetrical. PID parameters may be inaccurate!
     This is usually because the heat and cool processes do not change the temperature at the same rate.
     Please try reducing the positive_output value (or increase negative_output in case of a cooler)
   Calculated PID parameters ("Ziegler-Nichols PID" rule):

   control_parameters:
     kp: 0.59220
     ki: 0.00012
     kd: 735.99213
```
It can't be told these results belong to which PID instance.

Control parameters are used immediately after finish, so they can be noted down if one prepares sensors for these in advance even if the message is lost, however the very useful textual information can't be identified which PID it belongs to, and is lost when logs scroll over.

**Suggestion**

1. move the "_Autotune is still running!_" message to a Debug/Verbose level, instead of INFO, to avoid spamming the log
2. display the message "_For PID autotuner you need to set AUTO (also called heat/cool) mode!_" only once (at the start of Autotune), not repeatedly, to avoid spamming the log
3. add a tag or a string with _Name_ or _ID_ to the logs so we know from which PID climate instance the log messages are coming from

This way, we could start Autotune for multiple instances and with the log level set to INFO, we could have the separately identifiable results after several hours without them being scrolled over.

### Which version of ESPHome has the issue?

2022.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11

### What platform are you using?

ESP32

### Board

WirelessTag WT32-ETH01

### Component causing the issue

pid

### Example YAML snippet

```yaml
climate:
- platform: pid
  id: heat_01_pid
  name: ${zone_1_name} fűtés PID
  visual:
    min_temperature: 14
    max_temperature: 25
    temperature_step: 0.1
  sensor: heat_01_temp
  default_target_temperature: ${default_target_temp}
  heat_output: heat_01_pwm
  control_parameters:
    kp: 0.0
    ki: 0.0
    kd: 0.0

- platform: pid
  id: heat_02_pid
  name: ${zone_2_name} fűtés PID
  visual:
    min_temperature: 14
    max_temperature: 25
    temperature_step: 0.1
  sensor: heat_02_temp
  default_target_temperature: ${default_target_temp}
  heat_output: heat_02_pwm
  control_parameters:
    kp: 0.0
    ki: 0.0
    kd: 0.0

- platform: pid
  id: heat_03_pid
  name: ${zone_3_name} fűtés PID
  visual:
    min_temperature: 14
    max_temperature: 25
    temperature_step: 0.1
  sensor: heat_03_temp
  default_target_temperature: ${default_target_temp}
  heat_output: heat_03_pwm
  control_parameters:
    kp: 0.0
    ki: 0.0
    kd: 0.0

- platform: pid
  id: heat_04_pid
  name: ${zone_4_name} fűtés PID
  visual:
    min_temperature: 14
    max_temperature: 25
    temperature_step: 0.1
  sensor: heat_04_temp
  default_target_temperature: ${default_target_temp}
  heat_output: heat_04_pwm
  control_parameters:
    kp: 0.0
    ki: 0.0
    kd: 0.0

- platform: pid
  id: heat_05_pid
  name: ${zone_5_name} fűtés PID
  visual:
    min_temperature: 14
    max_temperature: 25
    temperature_step: 0.1
  sensor: heat_05_temp
  default_target_temperature: ${default_target_temp}
  heat_output: heat_05_pwm
  control_parameters:
    kp: 0.0
    ki: 0.0
    kd: 0.0

- platform: pid
  id: heat_06_pid
  name: ${zone_6_name} fűtés PID
  visual:
    min_temperature: 14
    max_temperature: 25
    temperature_step: 0.1
  sensor: heat_06_temp
  default_target_temperature: ${default_target_temp}
  heat_output: heat_06_pwm
  control_parameters:
    kp: 0.0
    ki: 0.0
    kd: 0.0

- platform: pid
  id: heat_07_pid
  name: ${zone_7_name} fűtés PID
  visual:
    min_temperature: 14
    max_temperature: 25
    temperature_step: 0.1
  sensor: heat_07_temp
  default_target_temperature: ${default_target_temp}
  heat_output: heat_07_pwm
  control_parameters:
    kp: 0.0
    ki: 0.0
    kd: 0.0
```

### Anything in the logs that might be useful for us?

_logs pasted in the section above_
