### ISSUE TITLE
Is the ESP32C3 deep_sleep with pin wake implementation correct?

### ISSUE THREAD

**Issue by pistifonok** [esphome/issues#3866]
### The problem

Hi,

im playing around with the Seeed Studio XIAO ESP32C3 and the pin wakeup function in the deep_sleep component not working.
Im far from an expert but i did some research and i think the deepsleep function doesn't gets the correct parameters. 

The esp_deep_sleep_enable_gpio_wakeup needs a "**gpio_pin_mask**" parameter.

[See documentation here!](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/system/sleep_modes.html?highlight=deep%20sleep#_CPPv433esp_deep_sleep_enable_gpio_wakeup8uint64_t33esp_deepsleep_gpio_wake_up_mode_t)

in the esphome code looks like it gets the pin number instead of the mask:

esp_deep_sleep_enable_gpio_wakeup(**gpio_num_t(this->wakeup_pin_->get_pin())**,
                                      static_cast<esp_deepsleep_gpio_wake_up_mode_t>(level));

ESP-Documentation:

esp_deep_sleep_enable_gpio_wakeup(**uint64_t gpio_pin_mask**, esp_deepsleep_gpio_wake_up_mode_t mode).

### Which version of ESPHome has the issue?

2022.11.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.4

### What platform are you using?

ESP32

### Board

seeed_xiao_esp32c3

### Component causing the issue

deep_sleep

### Example YAML snippet

```yaml
esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino
    version: 2.0.5
    platform_version: 5.2.0

...

deep_sleep:
  run_duration: 15s
  wakeup_pin: GPIO3
```

**Comment by pistifonok** [comment]
Hi, 

i've tested my "theory" and it is right.  
with the following config i can wake up the ESP:

```
deep_sleep:
  id: deep_sleep_1
  run_duration: 15s
  wakeup_pin: GPIO4
  wakeup_pin_mode: INVERT_WAKEUP
```

I used the GPIO4 as a number 4 witch is in binary '100' and therefore a mask for the GPIO2 (the third RTC-Pin). The ESP wakes up and goes back to sleep as it should by changing the state of the GPIO2.

It should be an easy fix but as i sad im not an expert to open a pull request :)

Thanks for your help and have a nice weekend!
