### ISSUE TITLE
Platform not found: sen5x

### ISSUE THREAD

**Issue by asaittam** [esphome/issues#3874]
### The problem

I am trying to use the Sensirion SEN55 sensor but ESPHome cannot find the 'sen5x' platform when I add its code as the example says in the editor. Other sensor platforms can be found by my system.

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.5

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

sen5x

### Example YAML snippet

```yaml
esphome:
  name: air-monitor-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ap_ota_pwd_air-monitor-1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid_air-monitor-1
    password: !secret ap_pwd_air-monitor-1

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  

sensor:
  - platform: sen5x
    id: sen55
    pm_1_0:
      name: " PM <1µm Weight concentration"
      id: pm_1_0
      accuracy_decimals: 1
    pm_2_5:
      name: " PM <2.5µm Weight concentration"
      id: pm_2_5
      accuracy_decimals: 1
    pm_4_0:
      name: " PM <4µm Weight concentration"
      id: pm_4_0
      accuracy_decimals: 1
    pm_10_0:
      name: " PM <10µm Weight concentration"
      id: pm_10_0
      accuracy_decimals: 1
    temperature:
      name: "Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Humidity"
      accuracy_decimals: 0
    voc:
      name: "VOC"
      algorithm_tuning:
        index_offset: 100
        learning_time_offset_hours: 12
        learning_time_gain_hours: 12
        gating_max_duration_minutes: 180
        std_initial: 50
        gain_factor: 230
    temperature_compensation:
      offset: 0
      normalized_offset_slope: 0
      time_constant: 0
    acceleration_mode: low
    store_baseline: true
    i2c_id: bus_a
    address: 0x69
    update_interval: 10s
```
