### ISSUE TITLE
Wemos NodeMCU ESP8266 not working after defining components

### ISSUE THREAD

**Issue by leodrivera** [esphome/issues#3875]
### The problem

I have a Wemos NodeMCU ESP8266 v3 - CH340 (https://botland.store/img/art/inne/10908_3.jpg) and I noticed that after installing esphome on it, the device stopped responding (it didn't even ping response).

The flashing process proceeds normally without any errors.

I performed the troubleshooting, seeking to isolate the problem. In this process, I did the following:

- Tried the proposed solution in these two issues(#3831 and #3583)
- Tested on a second board of the same model
- Removed Home Assistant API encryption

None of the previous attempts worked. Finally, as a last attempt, I compiled the code without any components, as shown below, and performed the flashing process:

```yaml
esphome:
  name: wemos-test

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_fallback_password

captive_portal:
```

Worked perfectly.

To confirm my suspicion, I added a simple remote_receiver component and flashed it again, as shown below, and the problem happened again.

```yaml
esphome:
  name: wemos-test

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_fallback_password

captive_portal:

remote_receiver:
  pin:
    number: D6
    inverted: true
    mode:
      input: true
      pullup: true
  dump: all
```

PS: I have other esps running in my HA (ESP-12f and ESP-01) and never had problems like that.
PS2: I've changed the board type to generic esp8266 (`esp01_1m`) and the number pin to the corresponding GPIO (`GPIO12`) and the result was the same.

### Which version of ESPHome has the issue?

2022.11.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.11.5

### What platform are you using?

ESP8266

### Board

Wemos NodeMCU ESP8266 v3 - CH340

### Component causing the issue

any component
