### ISSUE TITLE
ST7789V only work at height lower or equal to 230 pixels

### ISSUE THREAD

**Issue by Electronlibre2012** [esphome/issues#3877]
### The problem

Hello,

the custom of ST7789V component only work at height lower or equal to 230 pixels. I have a 2" TFT 320x240 and it can only run at 230x240, after there is a bootloop problem : 
```
[E][display:022]: Could not allocate buffer for display!
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x4000c46c  PS      : 0x00060b30  A0      : 0x800d9e6a  A1      : 0x3ffb1db0  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x0001c200  A5      : 0x00000000  
A6      : 0x000000f1  A7      : 0x00001c20  A8      : 0x80162784  A9      : 0x3ffb1d80  
A10     : 0x0000e100  A11     : 0x3f403919  A12     : 0x00000016  A13     : 0x3f401a20  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000004  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000000  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00001c1f  

ELF file SHA256: 0000000000000000

Backtrace: 0x4000c46c:0x3ffb1db0 0x400d9e67:0x3ffb1dc0 0x400de61e:0x3ffb1de0 0x401629e1:0x3ffb1e30 0x400de239:0x3ffb1e50 0x400e02c2:0x3ffb1ea0 0x400e5ada:0x3ffb1fb0 0x40089c0a:0x3ffb1fd0

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
[I][logger:258]: Log initialized
[C][ota:469]: There have been 10 suspected unsuccessful boot attempts.
```

### Which version of ESPHome has the issue?

2022.11.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.5

### What platform are you using?

ESP32

### Board

ESP-WROOM-32

### Component causing the issue

ST7789V

### Example YAML snippet

```yaml
image:
  - file: "/config/www/images/octoprint/octoprint128x128.png"
    id: my_image
    type: RGB24

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: Custom
    height: 240
    width: 240
    offset_height: 0
    offset_width: 0
    backlight_pin: GPIO22
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO17
    lambda: |-
      it.image(0, 0, id(my_image));
```

### Anything in the logs that might be useful for us?

```
 height: 230
```
works but i expected to use entire screen

so 
```
 height: 320
```
is what i expected to
