### ISSUE TITLE
neopixel bus color wipe effect  after 13.3 update

### ISSUE THREAD

**Issue by cooper2751** [esphome/issues#388]
hassio add on being used
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

nodemcu
**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**
using noepixel bus with a few color wipe effects updated to 13.3 lastnight 01-06-2019
now only the fist pixel responds
have since added a few standard effects that all work fine only issue with color wipe as does color wheel with no effect selected (for purpose of testing strip) 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```
esphome:
  name: stair_lights
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
  - ssid: 'VFast BC'
    password: '75436537'
  - ssid: vfast
    password: flintcottage2
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.130
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    



# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: neopixelbus
    type: grbw
    variant: SK6812
    num_leds: 104
    id: slight
    pin: GPIO3
    name: "stair lights"
    effects:
      - addressable_fireworks:
      - addressable_random_twinkle:           
      - addressable_color_wipe:         
      - addressable_color_wipe:
          name: Color Wipe Effect red B to T
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              white: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False
          
      - addressable_color_wipe:
          name: Color Wipe Effect red T to B
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              white: 0%
              num_leds: 10
          add_led_interval: 100ms
          reverse: true    
      
 
      
      - addressable_color_wipe:
          name: Color Wipe Effect white 100% B to T
          colors:
            - red: 0%
              green: 0%
              blue: 0%
              white: 100%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False
      - addressable_color_wipe:
          name: Color Wipe Effect white 100% T to B
          colors:
            - red: 0%
              green: 0%
              blue: 0%
              white: 100%
              num_leds: 1
          add_led_interval: 100ms
          reverse: true
          
      - addressable_color_wipe:
          name: Color Wipe Effect muilty B to T
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 100%
              green: 50%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 100%
              green: 100%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 0%
              green: 100%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 9%
              green: 58%
              blue: 100%
              white: 0%
              num_leds: 2
            - red: 41%
              green: 2%
              blue: 100%
              white: 0%
              num_leds: 2
            - red: 61%
              green: 0%
              blue: 100%
              white: 0%
              num_leds: 2              
          add_led_interval: 100ms
          reverse: False  
      - addressable_color_wipe:
          name: Color Wipe Effect muilty T to B
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 100%
              green: 50%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 100%
              green: 100%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 0%
              green: 100%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 9%
              green: 58%
              blue: 100%
              white: 0%
              num_leds: 2
            - red: 41%
              green: 2%
              blue: 100%
              white: 0%
              num_leds: 2
            - red: 61%
              green: 0%
              blue: 100%
              white: 0%
              num_leds: 2              
          add_led_interval: 100ms
          reverse: true  
              
       

          
                             
binary_sensor:
  - platform: gpio
    pin: D1
    name: "top 1"
    
  - platform: gpio
    pin: D2
    name: "top 2"
   
  - platform: gpio
    pin: D5
    name: "bottom 1"
    
    
  - platform: gpio
    pin: D6
    name: "bottom 2"
```

**Additional information and things you've tried:**
