### ISSUE TITLE
Deep Sleep constantly wakes up on its own when it went to sleep when no wifi

### ISSUE THREAD

**Issue by comet424** [esphome/issues#3881]
### The problem

i having issues with deep sleep

if your connected to wifi and home assistant..  and it goes to sleep  it works fine and the wake up button works fine

but 

if your connected to wifi and home assistant  first.. and you leave  the wifi range and then the esp32  goes into deep sleep.. something glitchs and keeps re awaking it.... so say its set for 15 min..   15 min goes  it then restarts  so its i guessing going into deep sleep the instantly re awakes...    randomy it will goto sleep...  but the wake up pin will not work.. and then it randomly  will re start up again coming out of deep sleeep

once  it gets wifi again  it will connect to wifi and home assistant.. buttons i have seem to work again but isnt able to talk to home assistant properly.. you gotta cycle the power..    so it can connect to wifi to work.. but glitchs after it goes to sleep  at the time its no longer connected to wifi

but when its connected to wifi and it goes to deep sleep.. it doesnt have an issue and doesnt randomly wake up etc

### Which version of ESPHome has the issue?

2022.11.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.0

### What platform are you using?

ESP32

### Board

esp32 wroom nodemcu

### Example YAML snippet

```yaml
deep_sleep:
  run_duration: 15min

######################
### Wake up Button ### 
######################
  wakeup_pin: 
    number: 25
    inverted: True
    mode: INPUT_PULLUP
#  esp32_ext1_wakeup:
#    pins: 
#      - 14
#      - 27
#      - 26
#      - 25
#    mode: any_high
    
################
### Switch's ###
################
binary_sensor:

##############
### Switch 1 #
##############
  - platform: gpio
    name: 'Vehicle1 Temp Switch #1'
    pin: 
      #number: 14
      number: 25
      mode:
        input: true
        pullup: true
```

### Anything in the logs that might be useful for us?

```txt
cant see logs as its in the car
```
