### ISSUE TITLE
DHT don't work any more with dev branch

### ISSUE THREAD

**Issue by Philippe12** [esphome/issues#3882]
### The problem

I try to use for test the dev branch and I can't communication with DTH (sonoff SI7021).

### Which version of ESPHome has the issue?

2023.1.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.2

### What platform are you using?

ESP32

### Board

sonoff thr316d

### Component causing the issue

DHT one wire

### Example YAML snippet

```yaml
sensor:
  - platform: dht
    pin: GPIO25
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 5s
```

### Anything in the logs that might be useful for us?

```txt
I configured a standard DHT sensor.
The communication work perfectly with 2022.11.5 but the I use the 2023.1.0-dev no more communication.

I look the signal with oscilosop and I can see the first pulse when the GPIO is in output (the timing look like good) but after nothing. I hop that the GPIO not switch in input mode.
```

### Additional information

I can do some test.
