### ISSUE TITLE
Unable to compile nodemcu-32s boards with 2022.12.0b2

### ISSUE THREAD

**Issue by PKuyten** [esphome/issues#3884]
### The problem

Trying to update 5 nodemcu-32s from production (2022.11.5) to beta (2022.12.0b2). The compiler throws an exception on xtensa-esp32-elf-g++

### Which version of ESPHome has the issue?

2022.12.0b2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.0

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

api/api_connection

### Example YAML snippet

```yaml
esphome:
  name: esphome-4f-couch

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret 4f-couch_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

captive_portal:

esp32_ble_tracker:

bluetooth_proxy:
  active: true

sensor:
  - platform: template
    name: "Couch Free Heap Memory"
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    icon: "mdi:memory"
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: "b"
    update_interval: 60s
  - platform: uptime
    name: "Couch Uptime"
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esphome-4f-couch.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-4f-couch (board: nodemcu-32s; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling /data/esphome-4f-couch/.pioenvs/esphome-4f-couch/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/esphome-4f-couch/.pioenvs/esphome-4f-couch/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/esphome-4f-couch/.pioenvs/esphome-4f-couch/src/esphome/components/api/api_pb2.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/esphome-4f-couch/.pioenvs/esphome-4f-couch/src/esphome/components/api/api_pb2_service.cpp.o
*** [/data/esphome-4f-couch/.pioenvs/esphome-4f-couch/src/esphome/components/api/api_connection.cpp.o] Error 127
*** [/data/esphome-4f-couch/.pioenvs/esphome-4f-couch/src/esphome/components/api/api_frame_helper.cpp.o] Error 127
*** [/data/esphome-4f-couch/.pioenvs/esphome-4f-couch/src/esphome/components/api/api_pb2.cpp.o] Error 127
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/esphome-4f-couch/.pioenvs/esphome-4f-couch/src/esphome/components/api/api_pb2_service.cpp.o] Error 127
========================== [FAILED] Took 5.32 seconds ==========================
```

### Additional information

This config is compiling on 2022.11.5, but does not compile with 2022.12.0b2
