### ISSUE TITLE
Upon some reboots, BMP280 sensor randomly gives randomly offset readings several times an hour

### ISSUE THREAD

**Issue by melyux** [esphome/issues#3890]
### The problem

I didn't have this problem the first time I started ESPHome with my BMP280. But after a few days, I restarted it. This time, I was met with seemingly slightly offset readings multiples times an hour at seemingly random intervals. This goes for both pressure and temperature

Pressure: 
<img width="600" alt="Screenshot 2022-12-10 at 2 21 11 PM" src="https://user-images.githubusercontent.com/10296053/206877516-6e7b36fb-4059-42b0-9458-52a94b11feb6.png">

Temperature: 
<img width="577" alt="Screenshot 2022-12-10 at 2 21 02 PM" src="https://user-images.githubusercontent.com/10296053/206877513-39aa042b-c589-4c44-ab4c-470f38d4434b.png">

* I tried with other BMP280 units but all produce the same result (on some boots).
* The problem persists regardless of oversampling values or not.

I'm wondering if this is the same problem that the BME280 had with #3383 that was fixed by @dbaarda in #3615 for the BME280. I don't know if the register logic is the same between these sister boards so I haven't tried replicating the changes to `bmp280.cpp` out of caution.

### Which version of ESPHome has the issue?

2022.11.5

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

ESP8285

### Component causing the issue

bmp280

### Example YAML snippet

```yaml
esphome:
  name: xxxxxxx

esp8266:
  board: esp8285

# Enable logging
logger:

ota:
  password: "xxxxxxx"

wifi:
  ssid: "xxxxxxx"
  password: "xxxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xxxxxxx"
    password: "xxxxxxx"

captive_portal:

mqtt:
  broker: xxxxxxx
  username: xxxxxxx
  password: xxxxxxx
  discovery: false
  topic_prefix: xxxxxxx

i2c:
  - id: bmp_i2c
    sda: GPIO4
    scl: GPIO5


sensor:

  - platform: bmp280
    address: 0x76 # Have to set this for some reason...
    temperature:
      name: "BMP280 Temperature"
      oversampling: 16x
      accuracy_decimals: 2
      filters: # Convert to Fahrenheit
        - multiply: 1.8
        - offset: 32.0
      unit_of_measurement: °F
    pressure:
      name: "Pressure"
      oversampling: 16x
      accuracy_decimals: 5
      filters:
        - multiply: 0.02952998330101 # Convert from hPa to inHg
      unit_of_measurement: inHg
    update_interval: 60s


switch:

  - platform: restart
    name: "Restart"
```

### Anything in the logs that might be useful for us?

```txt
[20:03:01][D][bmp280.sensor:175]: Got temperature=27.5°C pressure=994.6hPa
[20:03:01][D][sensor:126]: 'BMP280 Temperature': Sending state 81.44600 °F with 2 decimals of accuracy
[20:03:01][D][sensor:126]: 'Pressure': Sending state 29.37173 inHg with 5 decimals of accuracy
[20:04:01][D][bmp280.sensor:175]: Got temperature=27.3°C pressure=994.4hPa
[20:04:01][D][sensor:126]: 'BMP280 Temperature': Sending state 81.17599 °F with 2 decimals of accuracy
[20:04:01][D][sensor:126]: 'Pressure': Sending state 29.36589 inHg with 5 decimals of accuracy
[20:05:01][D][bmp280.sensor:175]: Got temperature=27.5°C pressure=994.7hPa
[20:05:01][D][sensor:126]: 'BMP280 Temperature': Sending state 81.41000 °F with 2 decimals of accuracy
[20:05:01][D][sensor:126]: 'Pressure': Sending state 29.37220 inHg with 5 decimals of accuracy
```
The 20:04:01 lines above are an example of an erroneous dip in both the temperature and the pressure (it's always both at the same time), surrounded by the readings one minutes before and after that are normal readings.
