### ISSUE TITLE
mdns ipv6: I always get a fe80 instead of an ip from my prefix

### ISSUE THREAD

**Issue by jeremyp3** [esphome/issues#3896]
### The problem

hello,

  I use ESPHome version 2022.12.0b3 with ESPIDF and IPV6 support. 
It is a ULA prefix in autoconfiguration. The problem is that when I use mdns to look up my device, it always returns the ipv6 in fe80 instead of the ipv6 it is autoconfigured with.

Is there any way to correct this behavior on my side ?

  I specify that if I use the ipv6 without MDNS, it works as expected. 

Thanks,

Jeremyp3

### Which version of ESPHome has the issue?

2022.12.0b3

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

az-delivery-devkit-v4

### Component causing the issue

MDNS

### Example YAML snippet

```yaml
esphome:
  name: meters-hub

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf
    sdkconfig_options:
#      CONFIG_MBEDTLS_CERTIFICATE_BUNDLE: n
      CONFIG_LWIP_IPV6_AUTOCONFIG: y
```
