### ISSUE TITLE
esp32-c3: xtensa-lx106-elf-g++: not found

### ISSUE THREAD

**Issue by Gloomyeye** [esphome/issues#3899]
### The problem

I am not able to compile a simple esphome config for my esp32-c3 with board esp32-c3-devkitm-1.

I bought the following esp32: https://www.reichelt.de/entwicklungsboard-esp32-c3-mini-1-esp32c3devkitm-p311730.html?&trstct=pos_1&nbc=1
Now, I created a new esp32-c3 test config file and try to compile this file. Everytime, I get the compile issue.

I am using esphome and homeassistant in a docker environment on a raspi4 (32bit os system).

### Which version of ESPHome has the issue?

2022.12.0b5

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.12.4

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1

### Component causing the issue

riscv32-esp-elf-g++: not found

### Example YAML snippet

```yaml
esphome:
  name: esp32-c3-deltasol

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rtNqto5QVuHDNGmwy49sAYuJF/AqmkODco6OGDqI590="

ota:
  password: "8128cdc333ff77136fdca21a774bcf70"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C3-Deltasol"
    password: "ticdAfDllBs2"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esp32-c3-deltasol.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-c3-deltasol (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling .pioenvs/esp32-c3-deltasol/src/esphome/components/api/api_connection.cpp.o
sh: 1: riscv32-esp-elf-g++: not found
Compiling .pioenvs/esp32-c3-deltasol/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: riscv32-esp-elf-g++: not found
Compiling .pioenvs/esp32-c3-deltasol/src/esphome/components/api/api_pb2.cpp.o
sh: 1: riscv32-esp-elf-g++: not found
*** [.pioenvs/esp32-c3-deltasol/src/esphome/components/api/api_connection.cpp.o] Error 127
*** [.pioenvs/esp32-c3-deltasol/src/esphome/components/api/api_frame_helper.cpp.o] Error 127
*** [.pioenvs/esp32-c3-deltasol/src/esphome/components/api/api_pb2.cpp.o] Error 127
Compiling .pioenvs/esp32-c3-deltasol/src/esphome/components/api/api_pb2_service.cpp.o
sh: 1: riscv32-esp-elf-g++: not found
*** [.pioenvs/esp32-c3-deltasol/src/esphome/components/api/api_pb2_service.cpp.o] Error 127
========================== [FAILED] Took 4.32 seconds ==========================
```
