### ISSUE TITLE
Unable to Flash Ai Thinker ESP32-Cam 

### ISSUE THREAD

**Issue by Chuffs** [esphome/issues#3900]
### The problem

Unable to compile due to permissions error.

extensa-esp32-elf-g++:  Permission Denied

### Which version of ESPHome has the issue?

2022.11.5

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

Ai Thinker ESP32-Cam

### Example YAML snippet

```yaml
esphome:
  name: weather-station

esp32:
  board: esp32cam
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1ea32afe4e4914b21345cc2bdb9ba533"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80
  auth:
    username: admin
    password: admin
```

### Anything in the logs that might be useful for us?

```txt
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 1.0
|-- FS @ 1.0
|-- Update @ 1.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- ESPmDNS @ 1.0
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/weather-station/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-esp32-elf-g++: Permission denied
Compiling .pioenvs/weather-station/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: xtensa-esp32-elf-g++: Permission denied
Compiling .pioenvs/weather-station/src/esphome/components/api/api_pb2.cpp.o
sh: 1: xtensa-esp32-elf-g++: Permission denied
*** [.pioenvs/weather-station/src/esphome/components/api/api_connection.cpp.o] Error 126
*** [.pioenvs/weather-station/src/esphome/components/api/api_frame_helper.cpp.o] Error 126
*** [.pioenvs/weather-station/src/esphome/components/api/api_pb2.cpp.o] Error 126
Compiling .pioenvs/weather-station/src/esphome/components/api/api_pb2_service.cpp.o
sh: 1: xtensa-esp32-elf-g++: Permission denied
*** [.pioenvs/weather-station/src/esphome/components/api/api_pb2_service.cpp.o] Error 126
========================== [FAILED] Took 5.46 seconds ==========================
```
