### ISSUE TITLE
Light RGBW can't get full brightness on LEDS

### ISSUE THREAD

**Issue by BDIs01** [esphome/issues#391]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASSIO 9.3.2
ESPHome 1.13.3
**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 

NodeMCU V2
**Affected component:**

Light RGBW

**Description of problem:**
I am having an issue with my RGBw setup and am unsure if this is a programming issue, but I don't know where else to ask this.

The Green and Red LEDs are not having an issue. I cannot get full brightness from the blue or white leds, they seem restricted.

I am using a NodeMCU v2. with 12v BTF-Lighting LEDS. The 12v side of the LEDs is wired to the 12v source, and the return to ground leg of each color channel goes through a n channel MOSFET. I have swapped the mosfets out with no change. If I MANUALLY short the mosfet, I get full brightness on that channel which leads me to believe the NodeMCU GPIOs are not sending enough voltage to fully close the MOSFET. My electrical knowledge is very limited but I am using this community to learn so there is obviously something I am not understanding. My config is below. Please be gentle!

Only the white and blue channels are affected on tray 1
all the channels are affected on tray 2

I am running HASSIO 93.2 with ESPHome 1.13.3

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

esphome:
  name: mastr_bed
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "xxxxx"
  password: "xxxxx"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
output:
  - platform: esp8266_pwm
    id: redpin1
    pin: D2
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: greenpin1
    pin: D3
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: bluepin1
    pin: D1
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: whitepin1
    pin: D0
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: redpin2
    pin: D7
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: greenpin2
    pin: D8
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: bluepin2
    pin: D6
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: whitepin2
    pin: D5
    frequency: 1000 Hz

#light:
#  - platform: binary
#    name: "Test_LED"
#    output: whitegpio
    
light:
  - platform: rgbw
    color_correct: 100,100,100,100
    name: "Tray 1"
    red: redpin1
    green: greenpin1
    blue: bluepin1
    white: whitepin1
  - platform: rgbw
    name: "Tray 2"
    red: redpin2
    green: greenpin2
    blue: bluepin2
    white: whitepin2


```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

I've tried physically moving wires to differnent pins.  The problem stays on the pin.  I've tried swapping MOSFETS with no change.  The LEDS work fin if I manually ground the MOSFETS.
