### ISSUE TITLE
midea component, remove defaults capabilities 

### ISSUE THREAD

**Issue by twocolors** [esphome/issues#3914]
### The problem

i have Lessar Ego LS-HE12KNA2AB/LU-HE12KNA2AB , this AC not support "VERTICAL" swing.

But the default this capabilities is add.

Please delete, default capabilities value

### Which version of ESPHome has the issue?

2022.12.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.12.5

### What platform are you using?

ESP32

### Component causing the issue

climate/midea

### Example YAML snippet

```yaml
climate:
  - platform: midea
    name: ${device_name}
    id: ${node_id}
    autoconf: false
    beeper: true
    period: 5s
    timeout: 2s
    num_attempts: 3
    outdoor_temperature:
      name: ${device_name} Outdoor Temperature
      id: ${node_id}_outdoor_temperature
    supported_swing_modes:
    supported_presets:
    custom_presets:
    supported_modes:
      - FAN_ONLY
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
```

### Anything in the logs that might be useful for us?

```txt
from HA

hvac_modes:
  - 'off'
  - heat_cool
  - cool
  - heat
  - fan_only
  - dry
min_temp: 17
max_temp: 30
target_temp_step: 0.5
fan_modes:
  - auto
  - low
  - medium
  - high
preset_modes:
  - none
  - sleep
swing_modes:
  - 'off'
  - vertical
current_temperature: 27.5
temperature: 29
fan_mode: auto
preset_mode: none
swing_mode: 'off'
friendly_name: livingroom-ac
supported_features: 57
```
```


### Additional information

_No response_
