### ISSUE TITLE
MAX7219 Digit Display - Not working anymore

### ISSUE THREAD

**Issue by majoto85** [esphome/issues#3916]
### The problem

Hello,

I updated to the latest ESPHome version (2022.12.0) and the MAX7219 digit display no longer works. I've reduced everything to the bare essentials to exclude other sources of error, but even a simple "Hello" is no longer displayed.

Thank you

### Which version of ESPHome has the issue?

2022.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.5

### What platform are you using?

ESP32

### Board

NodeMCU

### Component causing the issue

MAX7219 Digit Display

### Example YAML snippet

```yaml
display:
  - platform: max7219digit
    cs_pin: 5
    num_chips: 4
    intensity: 15
    id: my_display
    lambda: |-
            it.print(0, 0, id(digit_font), "HELLO!");
```

### Anything in the logs that might be useful for us?

```txt
No
```
