### ISSUE TITLE
graph scaling does not handle negative values

### ISSUE THREAD

**Issue by unhold** [esphome/issues#3918]
### The problem

The automatic scaling of the graph does not handle negative values correctly. If the minimum value is negative, the graph scale is rounded to the next higher grid step value. The drawn graph trace will then leave the graph area. See attached photo.

![graph-scaling-issue](https://user-images.githubusercontent.com/1915545/207733465-5787fabc-aeb4-4cd1-9d46-689ed068afbe.jpg)

The problem seems to be in the calculation of the minimum y grid value in the following line:
https://github.com/esphome/esphome/blob/9bf7c977751d3b4e5cef123372a07f43f35f597b/esphome/components/graph/graph.cpp#L125
Rounding towards 0 occurs, but rounding towards -INF (negative infinity) is required.
Correction could be something like the following line, but I don't have the capability to set up a dev environment and test the change at the moment:
int yn = int(ymin / y_per_div) - (ymin < 0 && fmodf(ymax, y_per_div) != 0 ? 1 : 0);

Also, it appears that there are some undocumented configuration options of the graph component.

### Which version of ESPHome has the issue?

2022.9.4 (and all others versions since the addition of graph)

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

LilyGO T5_V2.3_2.13, configured as board esp32dev

### Component causing the issue

graph

### Example YAML snippet

```yaml
graph:
  - id: aut_graph
    duration: 3h
    width: 122
    height: 85
    border: false
    x_grid: 1h
    y_grid: 10
    traces:
      - sensor: kst
      - sensor: aut

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 2.13in-ttgo-b73
    #rotation: 90
    full_update_every: 100
    update_interval: never
    lambda: |-
      it.graph(0, 0, id(aut_graph));
```

### Anything in the logs that might be useful for us?

```txt
[23:52:04][V][graph:157]: Updating graph. ymin 0.000000, ymax 10.000000
[23:52:05][V][graph:035]: Updating trace with value: -6.530000
```
