### ISSUE TITLE
HA and Hass.io Addon unable to connect to .local host over API

### ISSUE THREAD

**Issue by soberstadt** [esphome/issues#392]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io 165, HassOS 2.12

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, D1 Mini

**Affected component:**

https://esphome.io/components/api.html

**Description of problem:**
I tried to update a device (named `mqtt_arrow_5`) today to 1.13.3 and change from MQTT to use API. I flashed the new bin, but HomeAssistant and the Addon are not able to connect to `mqtt_arrow_5.local` but my local `esphome mqtt_arrow_5.yaml logs` can.

Locally from MacOS:
```
$ esphome mqtt_arrow_5.yaml logs 
INFO Reading configuration...
INFO Starting log output from mqtt_arrow_5.local using esphome API
INFO Connecting to mqtt_arrow_5.local:6053 (192.168.0.100)
INFO Successfully connected to mqtt_arrow_5.local
[23:28:36][I][app:063]: esphome version 1.13.3 compiled on Jun  2 2019, 23:20:15
```

On ESPHome Addon:
![image](https://user-images.githubusercontent.com/1080613/58775824-7caf5f00-8595-11e9-9dfa-667f24c83c96.png)

In Home Assistant:
![image](https://user-images.githubusercontent.com/1080613/58775863-9d77b480-8595-11e9-94ac-8732e23c0e2d.png)

When I `ping mqtt_arrow_5.local:6053` it resolves to `23.202.231.166`, but `ping mqtt_arrow_5.local` resolves to `192.168.0.100`. So I tried putting `192.168.0.100` into the Home Assistant integration registration it connected successfully.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: mqtt_arrow_5
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret mqtt_wifi_ssid
  password: !secret mqtt_wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret mqtt_password
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
