### ISSUE TITLE
http_request and json crash

### ISSUE THREAD

**Issue by Samuel-0-0** [esphome/issues#3920]
### The problem

如果目标地址不能访问，ESP有一定概率会崩溃。
If the target address cannot be accessed, there is a certain probability that the ESP crashes .

如果在ESP_LOGD中已经调用过id(http_request_data).get_string()，那么json::parse_json再次调用它时会崩溃。
If  id(http_request_data).get_string() has been called in ESP_ LOGD , then json:: parse_Json crashes when it is called again.

### Which version of ESPHome has the issue?

2022.11 ~ 2022.12b

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

http_request, json

### Example YAML snippet

```yaml
http_request:
  useragent: esphome/device
  id: http_request_data
  timeout: 10s

interval: 
  - interval: 30s 
    then:
      - http_request.get:
          url: $url
          headers:
            Content-Type: application/json
          verify_ssl: false
          on_response:
            then:
              - lambda: |-
                  //ESP_LOGD("main", "Got value: %s", id(http_request_data).get_string()); // ESP_LOGD1
                  auto data = id(http_request_data).get_string();
                  //ESP_LOGD("main", "Got value: %s", data); // ESP_LOGD2
                  json::parse_json(data, [](JsonObject root) {
                    id(print_state).publish_state(root["state"]);
                  }
```

### Additional information

If uncomment ESP_LOGD1, json:: parse_Json will crash.
If uncomment ESP_LOGD2, json:: parse_Json works well.

sorry my poor English
