### ISSUE TITLE
ESP32 boot loop - image size incorrect after upgrade (2022.11.5 -> 2022.12.0)

### ISSUE THREAD

**Issue by tubes41** [esphome/issues#3921]
### The problem

Performed an ESPHome upgrade on a DFRobot FireBeetle ESP32-E, from v2022.11.5 to v2022.12.0.
Upgrade was performed over USB via the ESPHome web interface.

ESP is now stuck in a boot loop, with logs only accessible via USB. Looks like an image / partition size issue?

### Which version of ESPHome has the issue?

2022.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.2

### What platform are you using?

ESP32

### Board

DFRobot FireBeetle ESP32-E

### Component causing the issue

Bluetooth Proxy

### Example YAML snippet

```yaml
esphome:
  name: esp-find-1

esp32:
  board: firebeetle32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_api

ota:
  password: !secret ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Find-1 Fallback Hotspot"
    password: "LvHRUFfY6BEA"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    active: true
bluetooth_proxy:   
  active: true
```

### Anything in the logs that might be useful for us?

```txt
ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
E (657) spi_flash: Detected size(4096k) smaller than the size in the binary image header(16384k). Probe failed.

assert failed: do_core_init startup.c:298 (flash_ret == ESP_OK)


Backtrace:0x40083725:0x3ffe3aa00x400930e5:0x3ffe3ac0 0x400987ad:0x3ffe3ae0 0x400f7482:0x3ffe3c10 0x40082e26:0x3ffe3c40 0x400792ba:0x3ffe3c90  |<-CORRUPTED
```
