### ISSUE TITLE
FastLED compilation warning

### ISSUE THREAD

**Issue by Murianwind** [esphome/issues#3926]
### The problem

When compiling, a warning message related to FastLED is displayed.

Compilation does not fail, but I do not want a warning message to be output.

### Which version of ESPHome has the issue?

2022.12.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2022.12.6

### What platform are you using?

ESP32

### Component causing the issue

FastLED

### Example YAML snippet

```yaml
substitutions:
  node_name: particulate-matter  # 수정! node 이름(ESPHOME 상의 이름)
  device_name: particulate-matter  # 수정! 제품명

esphome:
  name: ${node_name}
  on_boot:
    then:
      - light.turn_on:
          id: light_1
          effect: rainbow
          brightness: 30%
      - delay : 10s
      - light.turn_off:
          id: light_1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "*****"

ota:
  password: !secret ota_pwd

wifi:
  ssid: !secret main_ap_ssid
  password: !secret main_ap_pwd  #수정! 와이파이 비밀번호
  fast_connect: on
  ap:
    ssid: "particulate matter"
    password: !secret fallback_ap_pwd

captive_portal:

preferences: 
  flash_write_interval: 60min

time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-9
    servers:
      - time.windows.com
      - 0.pool.ntp.org
      - 1.pool.ntp.org

bluetooth_proxy:

esp32_ble_tracker:
  scan_parameters:
    duration: 10s
    active: false

uart:
  - id: uart_a
    rx_pin: 16
    tx_pin: 17
    baud_rate: 9600

  - id: uart_b
    rx_pin: 19
    tx_pin: 18
    baud_rate: 9600

light:
  - platform: fastled_clockless
    chipset: SK6812
    pin: GPIO14
    num_leds: 4
    rgb_order: BRG
    id: light_1
    name: "Sensor Lamp"
    effects:
      - addressable_color_wipe:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
```

### Anything in the logs that might be useful for us?

```txt
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:95,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/include/esp_intr.h:8:2: warning: #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead [-Wcpp]
 #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead
  ^~~~~~~
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h: In member function 'void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::startOnChannel(int)':
/data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:399:52: warning: 'esp_err_t rmt_set_pin(rmt_channel_t, rmt_mode_t, gpio_num_t)' is deprecated: use rmt_set_gpio instead [-Wdeprecated-declarations]
         rmt_set_pin(mRMT_channel, RMT_MODE_TX, mPin);
                                                    ^
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:97,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include/driver/rmt.h:930:11: note: declared here
 esp_err_t rmt_set_pin(rmt_channel_t channel, rmt_mode_t mode, gpio_num_t gpio_num)
           ^~~~~~~~~~~
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h: In instantiation of 'void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::startOnChannel(int) [with int DATA_PIN = 14; int T1 = 72; int T2 = 72; int T3 = 144; EOrder RGB_ORDER = (EOrder)129; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 5]':
/data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:381:26:   required from 'static void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::startNext(int) [with int DATA_PIN = 14; int T1 = 72; int T2 = 72; int T3 = 144; EOrder RGB_ORDER = (EOrder)129; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 5]'
/data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:312:26:   required from 'void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::showPixels(PixelController<RGB_ORDER>&) [with int DATA_PIN = 14; int T1 = 72; int T2 = 72; int T3 = 144; EOrder RGB_ORDER = (EOrder)129; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 5]'
/data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:283:18:   required from here
/data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:399:20: warning: 'esp_err_t rmt_set_pin(rmt_channel_t, rmt_mode_t, gpio_num_t)' is deprecated: use rmt_set_gpio instead [-Wdeprecated-declarations]
         rmt_set_pin(mRMT_channel, RMT_MODE_TX, mPin);
         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:97,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include/driver/rmt.h:930:11: note: declared here
 esp_err_t rmt_set_pin(rmt_channel_t channel, rmt_mode_t mode, gpio_num_t gpio_num)
           ^~~~~~~~~~~
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:399:20: warning: 'esp_err_t rmt_set_pin(rmt_channel_t, rmt_mode_t, gpio_num_t)' is deprecated: use rmt_set_gpio instead [-Wdeprecated-declarations]
         rmt_set_pin(mRMT_channel, RMT_MODE_TX, mPin);
         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:97,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include/driver/rmt.h:930:11: note: declared here
 esp_err_t rmt_set_pin(rmt_channel_t channel, rmt_mode_t mode, gpio_num_t gpio_num)
           ^~~~~~~~~~~
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:399:20: warning: 'esp_err_t rmt_set_pin(rmt_channel_t, rmt_mode_t, gpio_num_t)' is deprecated: use rmt_set_gpio instead [-Wdeprecated-declarations]
         rmt_set_pin(mRMT_channel, RMT_MODE_TX, mPin);
         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:97,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include/driver/rmt.h:930:11: note: declared here
 esp_err_t rmt_set_pin(rmt_channel_t channel, rmt_mode_t mode, gpio_num_t gpio_num)
           ^~~~~~~~~~~
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:399:20: warning: 'esp_err_t rmt_set_pin(rmt_channel_t, rmt_mode_t, gpio_num_t)' is deprecated: use rmt_set_gpio instead [-Wdeprecated-declarations]
         rmt_set_pin(mRMT_channel, RMT_MODE_TX, mPin);
         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/clockless_rmt_esp32.h:97,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/platforms.h:36,
                 from /data/particulate-matter/.piolibdeps/particulate-matter/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:31,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include/driver/rmt.h:930:11: note: declared here
 esp_err_t rmt_set_pin(rmt_channel_t channel, rmt_mode_t mode, gpio_num_t gpio_num)
           ^~~~~~~~~~~
```

**Comment by Olen** [comment]
Have the same, and it seems like controlling the leds from HA does not work either.

```
esp32:
  board: m5stack-atom
  framework:
    type: arduino
```
