### ISSUE TITLE
ADS1115 values difference in 1.13.3

### ISSUE THREAD

**Issue by phdelodder** [esphome/issues#393]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Docker

**ESP (ESP32/ESP8266, Board/Sonoff):** NodeMCU

**Affected component:** ADS1115

**Description of problem:**
The adc value of the ADS1115 difference with 1.12.2 vs 1.13.3. In 1.12.2 I get 0.8 vs 0.26 in 1.13.3. I can switch back and forward and for each version I get the same numbers. 

**Problem-relevant YAML-configuration entries:**
```yaml
- platform: ads1115
    multiplexer: 'A0_GND'
    gain: 6.144
    name: "ADS1115 Channel A0-GND"
    id: ads1115_1
    update_interval: 5s
    internal: true # Don't expose this sensor to HA, the template sensors will do that
    # Dry 2.734 - taken from in the air, probably should do it directly in dry soil
    # Wet 0.638 - taken from in a glass of water, probably should do it directly in saturated soil
    filters:
      - sliding_window_moving_average: # averages the last 10 results, probably overkill
          window_size: 10
          send_every: 10
      - lambda: |-
          if (x > 2.734) { 				// if over 2.734 volts, we are dry
            return 0;
          } else if (x < 0.638) { 			// if under 0.638 volts, we are fully saturated
            return 100;
          } else {
            return (2.734-x) / (2.734-0.638) * 100.0; 	// use a linear fit for any values in between
          }
  - platform: template
    name: "Greenhouse Zone 1 Soil Saturation"
    id: zone1saturation
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 0
    lambda: |-
      return id(ads1115_1).state;

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
