### ISSUE TITLE
Water usage from slimmelezer

### ISSUE THREAD

**Issue by peno64** [esphome/issues#3933]
### The problem

It is not possible to retrieve the water usage from slimmemeter. In the code I see in fields.h for example the definition of water_delivered but in the yaml configuration file it is not possible to specify it. It is also not documented in https://esphome.io/components/sensor/dsmr.html 
Belgium readers do send this data and I see the definition  in fields.h is correct so why is it tnot possible to specify it in the configation file?

### Which version of ESPHome has the issue?

2022.11.5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
substitutions:
  device_name: slimmelezer
  device_description: "DIY P1 module to read your smart meter"

esphome:
  name: ${device_name}
  comment: "${device_description}"
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: d1_mini
  name_add_mac_suffix: false
  project:
    name: zuidwijk.slimmelezer
    version: "2.0"

uart:
  baud_rate: 115200
  rx_pin: D7

dsmr:

sensor:
  - platform: dsmr
    water_delivered:
      name: "Water Consumed"
```

### Anything in the logs that might be useful for us?

```txt
Compiling this with: esphome compile water.yaml
gives:

Failed config

sensor.dsmr: [source water.yaml:23]
  platform: dsmr

  [water_delivered] is an invalid option for [sensor.dsmr]. Did you mean [power_delivered], [power_delivered_l3], [power_delivered_l2]?
  water_delivered:
    name: Water Consumed
```

**Comment by Calypoter** [comment]
Is there a way to add this option? I also would like to see it with esphome

**Comment by peno64** [comment]
See this: https://github.com/peno64/slimmemeter/wiki
Works perfect for me

**Comment by peturdainn** [comment]
And now it works out of the box so this issue can be closed I think

**Comment by Brewery-GIT** [comment]
just stumbled upon this, having the same issue. sorry to necro this, but I wanted to share:

* Belgian digital meter with P1 + Digital Watermeter coupled to this
* Dashboard from waterprovider showed usage, so coupling was OK.
* Slimmelezer showed Water Consumed as Unknown.

Checked the DSMR docs [https://esphome.io/components/sensor/dsmr/](url) and saw this:

```
   Optional. The id of the water meter. Default=2.
  water_mbus_id: 2
```

I added this to my yaml config for the slimmelezer, but changed it to 1 and installed it
water_mbus_id: **1**

Boom. Value immediately came in.
Might be useful if anyone else experiences this.

**Comment by kristofbriers** [comment]
> just stumbled upon this, having the same issue. sorry to necro this, but I wanted to share:
> 
> * Belgian digital meter with P1 + Digital Watermeter coupled to this
> * Dashboard from waterprovider showed usage, so coupling was OK.
> * Slimmelezer showed Water Consumed as Unknown.
> 
> Checked the DSMR docs [https://esphome.io/components/sensor/dsmr/](url) and saw this:
> 
> ```
>    Optional. The id of the water meter. Default=2.
>   water_mbus_id: 2
> ```
> 
> I added this to my yaml config for the slimmelezer, but changed it to 1 and installed it water_mbus_id: **1**
> 
> Boom. Value immediately came in. Might be useful if anyone else experiences this.

Is this in the ESPHome yaml file for the slimmelezer?

**Comment by Brewery-GIT** [comment]
> 
> Is this in the ESPHome yaml file for the slimmelezer?

yes, the one you save and install via ESPHome.
I put it under DSMR

dsmr:
  [other stuff already there]
  water_mbus_id: 1

**Comment by herriejr** [comment]
For other people not getting it to work and stumbling upon this thread, I had to add some additional configuration parameters to get it to work in my case.
Everything worked fine until the installation of the digital water meter. First of all I needed to add `water_mbus_id: 1` since no gas meter present. 

Then I got the following errors:

```
[D][dsmr:032]: Buffer overflow. Discarding the accumulated data
[V][dsmr:026]: Found telegram start symbol '/'
```
By then I already added `rx_buffer_size` because when compiling esphome gave me a warning. But I kept getting the same error. Then ChatGPT pointed me in the right direction. I still needed to add `max_telegram_length` under `dsmr`. I also updated esphome to the latest version, just in case.

```
uart:
  baud_rate: 115200
  rx_pin: RX
  rx_buffer_size: 3000
 
dsmr:
  id: dsmr_instance
  water_mbus_id: 1
  max_telegram_length: 2000
```

Aside from `water_mbus_id`, I also needed to add `rx_buffer_size` and `max_telegram_length`. Hope this helps other people getting it to work.
