### ISSUE TITLE
SDM120M - CRC Errors on 22.12.1 

### ISSUE THREAD

**Issue by Ralphy140** [esphome/issues#3939]
### The problem

Connecting to SDM120M using RS485 to UART adaptor is generating CRC errors and not populating sensors. single Modbus quey works fine so know i can comminicate with the modbus on the device correctly. Device works IF logger verbose is enabled. It seems that the code is processing the modbus data stream before all data has been received. Attached debug logs attached 
[logs_modbus-power_upload.txt](https://github.com/esphome/issues/files/10254817/logs_modbus-power_upload.txt)

[message (1).txt](https://github.com/esphome/issues/files/10254819/message.1.txt)

### Which version of ESPHome has the issue?

2022.12.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
uart:
  rx_pin: GPIO016
  tx_pin: GPIO017
  baud_rate: 9600 #if your energy meter is SDM230M or SDM120M than change the baud_rate: 2400
  stop_bits: 1
  debug:

  
sensor:
  - platform: sdm_meter
    phase_a:
      current:
        name: "SDM120M Current"
      voltage:
        name: "SDM120M Voltage"
      active_power:
        name: "SDM120M Power"
      power_factor:
        name: "SDM120M Power Factor"
      apparent_power:
        name: "SDM120M Apparent Power"
      reactive_power:
        name: "SDM120M Reactive Power"
      phase_angle:
        name: "SDM120M Phase Angle"
    frequency:
      name: "SDM120M Frequency"
    total_power:
      name: "SDM120M Total Power"
    import_active_energy:
      name: "SDM120M Import Active Energy"
    export_active_energy:
      name: "SDM120M Export Active Energy"
    import_reactive_energy:
      name: "SDM120M Import Reactive Energy"
    export_reactive_energy:
      name: "SDM120M Export Reactive Energy"
    update_interval: 10s
```
