### ISSUE TITLE
Bluetooth-proxy doesn't work for HA anymore

### ISSUE THREAD

**Issue by txitxo0** [esphome/issues#3951]
### The problem

Hi, 

After the last updates the bluetooth-proxy device I had working from 2 months ago just didn't proxy packets to HA anymore. 
I was following [this other issue](https://github.com/esphome/issues/issues/3913) related but it didn't fix mine.

I have been working in update the framework to use esp-idf as they ask me for and it is properly commented in docs ([in the warning section](https://esphome.io/components/bluetooth_proxy.html)) but nothing appears to fix this up. 

I am using an ESP32-wroom in an Esphome addon 2022.12.3 in a Home Assistant OS 2022.12.7

I am trying to proxying two different [xiaomi ble thermometers](https://esphome.io/components/sensor/xiaomi_ble.html#lywsd03mmc) who don't have very good coverage and they are both working before with the same atc firmware. One of them to be able to look at it is the one wich the MAC=A4:C1:38:BE:CE:9B

Apparently is working and the device log shows the sentence: "Proxying packet from ATC_BECE9B - A4:C1:38:BE:CE:9B. RSSI: -49 dB". But nothing wrong appears in logs from both sides, HA (aioesphome) or ESPHome device log. As we coment in the other issue, I added a free memory sensor to check if it was related to that, but nope... around of 105kB of free memory in the device

The rest of the behaviour of this devices who has two more sensors (PIR and illuminance) is working fine.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.7

### What platform are you using?

ESP32-IDF

### Board

esp32-wroom

### Component causing the issue

bluetooth proxy

### Example YAML snippet

```yaml
substitutions:
  name: "btproxy-estudio"
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

logger:
  level: VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.3.50
    gateway: 192.168.1.1
    subnet: 255.255.255.0

binary_sensor:
  - platform: gpio
    pin: GPIO26
    name: "${name}-motion"
    device_class: motion
    filters:
      - delayed_on: 250ms

sensor:
  - platform: adc
    pin: GPIO32
    name: "${name}-illuminance"
    device_class: illuminance
    unit_of_measurement: lx
    update_interval: 60s
    attenuation: auto
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0 * 1.67;
    
    # Uptime sensor
  - platform: template
    name: btproxy Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esp32-bluetooth-proxy-estudio.yaml...
INFO Starting log output from 192.168.3.50 using esphome API
INFO Successfully connected to 192.168.3.50
[12:51:23][I][app:102]: ESPHome version 2022.12.3 compiled on Dec 21 2022, 08:33:54
[12:51:23][I][app:104]: Project esphome.bluetooth-proxy version 1.0
[12:51:23][C][wifi:504]: WiFi:
[12:51:23][C][wifi:362]:   Local MAC: E0:5A:1B:75:8A:90
[12:51:23][C][wifi:363]:   SSID: [redacted]
[12:51:23][C][wifi:364]:   IP Address: 192.168.3.50
[12:51:23][C][wifi:366]:   BSSID: [redacted]
[12:51:23][C][wifi:367]:   Hostname: 'btproxy-estudio'
[12:51:23][C][wifi:369]:   Signal strength: -53 dB ▂▄▆█
[12:51:23][V][wifi:371]:   Priority: 0.0
[12:51:23][C][wifi:373]:   Channel: 6
[12:51:23][C][wifi:374]:   Subnet: 255.255.255.0
[12:51:23][C][wifi:375]:   Gateway: 192.168.1.1
[12:51:23][C][wifi:376]:   DNS1: 0.0.0.0
[12:51:23][C][wifi:377]:   DNS2: 0.0.0.0
[12:51:23][V][bluetooth_proxy:033]: Proxying packet from  - 46:B0:00:1B:87:C5. RSSI: -81 dB
[12:51:23][C][logger:293]: Logger:
[12:51:23][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'btproxy-estudio-motion'
[12:51:23][C][gpio.binary_sensor:015]:   Device Class: 'motion'
[12:51:23][C][gpio.binary_sensor:016]:   Pin: GPIO26
[12:51:23][C][template.sensor:023]: Template Sensor 'btproxy Free Memory'
[12:51:23][C][template.sensor:023]:   State Class: 'measurement'
[12:51:23][C][template.sensor:023]:   Unit of Measurement: 'kB'
[12:51:23][C][template.sensor:023]:   Accuracy Decimals: 1
[12:51:23][C][template.sensor:024]:   Update Interval: 60.0s
[12:51:23][C][bluetooth_proxy:065]: Bluetooth Proxy:
[12:51:23][C][bluetooth_proxy:066]:   Active: YES
[12:51:23][C][safe_mode.button:022]: Safe Mode Button 'Safe Mode Boot'
[12:51:23][C][safe_mode.button:022]:   Icon: 'mdi:restart-alert'
[12:51:23][C][adc:087]: ADC Sensor 'btproxy-estudio-illuminance'
[12:51:23][C][adc:087]:   Device Class: 'illuminance'
[12:51:23][C][adc:087]:   State Class: 'measurement'
[12:51:23][C][adc:087]:   Unit of Measurement: 'lx'
[12:51:23][C][adc:087]:   Accuracy Decimals: 2
[12:51:23][C][adc:097]:   Pin: GPIO32
[12:51:23][C][adc:099]:  Attenuation: auto
[12:51:23][C][adc:126]:   Update Interval: 60.0s
[12:51:23][C][esp32_ble_tracker:870]: BLE Tracker:
[12:51:23][C][esp32_ble_tracker:871]:   Scan Duration: 300 s
[12:51:23][C][esp32_ble_tracker:872]:   Scan Interval: 1100.0 ms
[12:51:23][C][esp32_ble_tracker:873]:   Scan Window: 1100.0 ms
[12:51:23][C][esp32_ble_tracker:874]:   Scan Type: ACTIVE
[12:51:23][C][esp32_ble_tracker:875]:   Continuous Scanning: True
[12:51:23][C][mdns:103]: mDNS:
[12:51:23][C][mdns:104]:   Hostname: btproxy-estudio
[12:51:23][V][mdns:105]:   Services:
[12:51:23][V][mdns:107]:   - _esphomelib, _tcp, 6053
[12:51:23][V][mdns:109]:     TXT: version = 2022.12.3
[12:51:23][V][mdns:109]:     TXT: mac = e05a1b758a90
[12:51:23][V][mdns:109]:     TXT: platform = ESP32
[12:51:23][V][mdns:109]:     TXT: board = esp32dev
[12:51:23][V][mdns:109]:     TXT: network = wifi
[12:51:23][V][mdns:109]:     TXT: project_name = esphome.bluetooth-proxy
[12:51:23][V][mdns:109]:     TXT: project_version = 1.0
[12:51:23][V][mdns:109]:     TXT: package_import_url = github://esphome/bluetooth-proxies/esp32-generic.yaml@main
[12:51:23][C][ota:093]: Over-The-Air Updates:
[12:51:23][C][ota:094]:   Address: 192.168.3.50:3232
[12:51:23][C][api:138]: API Server:
[12:51:23][C][api:139]:   Address: 192.168.3.50:6053
[12:51:23][C][api:143]:   Using noise encryption: NO
[12:51:23][C][improv_serial:032]: Improv Serial:
[12:51:24][V][bluetooth_proxy:033]: Proxying packet from ATC_162894 - A4:C1:38:16:28:94. RSSI: -32 dB
[12:51:26][V][bluetooth_proxy:033]: Proxying packet from ATC_162894 - A4:C1:38:16:28:94. RSSI: -33 dB
[12:51:26][V][bluetooth_proxy:033]: Proxying packet from ATC_BECE9B - A4:C1:38:BE:CE:9B. RSSI: -49 dB
[12:51:27][V][bluetooth_proxy:033]: Proxying packet from  - 46:B0:00:1B:87:C5. RSSI: -82 dB
[12:51:28][V][bluetooth_proxy:033]: Proxying packet from  - 46:B0:00:1B:87:C5. RSSI: -83 dB
```

### Additional information

![image](https://user-images.githubusercontent.com/12279324/208901815-bf0bd40c-73a3-4ed7-9d49-14563a5b9cf3.png)
![image](https://user-images.githubusercontent.com/12279324/208901916-034ac8a6-d35d-423b-b47d-42a33884b740.png)

**Comment by syphernl** [comment]
The BT Proxy in ESPHome 2022.12.x is also pretty unstable for me. 
I run it on two ESP32's currently.

For one ESP all devices in its vicinity showed as unavailable in HASS after a few hours. 
After a reboot of the ESP all devices are reachable again.

I still had `esphome logs` open to another ESP32 (which seems to work fine as all devices in its vicinity were showing as available) but this one showed:
```
[12:49:26][D][esp32_ble_tracker:327]: Starting scan...
[13:19:26][D][esp32_ble_tracker:327]: Starting scan...
[13:29:26][E][esp32_ble_tracker:344]: ESP-IDF BLE scan never terminated, rebooting to restore BLE stack...
```

**Comment by nagyrobi** [comment]
Works fine here, Olimex board. Passively proxying 11 Xiaomi sensors with pvvx firmware in BTHome mode.

**Comment by Ulrar** [comment]
The other issue's resolution did fix my Switchbot's, but I noticed yesterday that I had another device (Airthings Wave+) that was still misbehaving.
I thought it might be a range issue so I moved one of my bluetooth proxies close to it but no improvement.

Rolling back to 2022.11 solves the issue, so it is a problem present in all 2022.12.x versions. You can clearly tell when I rolled back : 
![image](https://user-images.githubusercontent.com/873423/209096386-7cc5f4c2-dee1-4dd8-bca4-d5887cdd881a.png)

The[ other issue](https://github.com/esphome/issues/issues/3913) was a problem with the ServiceData not being parsed correctly, so the integration's diagnostics still showed the devices but without the ServiceData.
In this case I've looked at it and it's a different issue, the diagnostics do not always show this device, it's completely missing from the list sometimes. And sometimes it's there.
The issue from HA's side is also different as it does log an error saying it failed to get the 'battery' attribute, but I suspect that's just weird error handling in the integration.

I've noticed that restarting HA always gets you one good reading on init, and moving proxies around also works once, so it looks to me like you can get one good reading per proxy per HA restart.
I'd say it's an ESPHome integration problem but reloading the proxy's integration doesn't seem to make a difference.

Is there a way to get something like a CPU Load sensor for the board ? I saw a few 'Too many BLE events' messages on one of my proxies so I wonder if they might be getting overloaded on 2022.12 somehow, but it's hard to tell, in VERY_VERBOSE there's just so much log it's hard to follow. That might be a red herring, I just saw that once while looking at something else, it might be unrelated.

Anyway I'm assuming this is related to OP's issue but maybe not, just wanted to chime in with some details in case it is.

**Comment by mutlucan96** [comment]
I also have a similar problem. Everything was working fine on 2022.11. I've updated it to 2022.12.3 via serial port. The proxy is working fine for somewhere between 1 hour to 24 hours. It's still connected, I can access logs via Wi-Fi, but there aren't any BLE logs anymore:
`INFO Reading configuration /config/esphome/salon2.yaml...
INFO Starting log output from 192.168.1.189 using esphome API
INFO Successfully connected to 192.168.1.189
[10:20:30][I][app:102]: ESPHome version 2022.12.2 compiled on Dec 20 2022, 09:41:52
[10:20:30][C][wifi:504]: WiFi:
[10:20:30][C][wifi:362]:   Local MAC: 94:B9:7E:FA:9F:AC
[10:20:30][C][wifi:363]:   SSID: 'Mutlu'[redacted]
[10:20:30][C][wifi:364]:   IP Address: 192.168.1.189
[10:20:30][C][wifi:366]:   BSSID: 3C:7C:3F:E0:8D:50[redacted]
[10:20:30][C][wifi:367]:   Hostname: 'salon2'
[10:20:30][C][wifi:369]:   Signal strength: -59 dB ▂▄▆█
[10:20:30][C][wifi:373]:   Channel: 1
[10:20:30][C][wifi:374]:   Subnet: 255.255.255.0
[10:20:30][C][wifi:375]:   Gateway: 192.168.1.1
[10:20:30][C][wifi:376]:   DNS1: 192.168.1.1
[10:20:30][C][wifi:377]:   DNS2: 8.8.8.8
[10:20:30][C][logger:293]: Logger:
[10:20:30][C][logger:294]:   Level: VERBOSE
[10:20:30][C][logger:295]:   Log Baud Rate: 115200
[10:20:30][C][logger:296]:   Hardware UART: UART0
[10:20:30][C][bluetooth_proxy:065]: Bluetooth Proxy:
[10:20:30][C][bluetooth_proxy:066]:   Active: YES
[10:20:30][C][esp32_ble_tracker:870]: BLE Tracker:
[10:20:30][C][esp32_ble_tracker:871]:   Scan Duration: 300 s
[10:20:30][C][esp32_ble_tracker:872]:   Scan Interval: 1100.0 ms
[10:20:30][C][esp32_ble_tracker:873]:   Scan Window: 1100.0 ms
[10:20:31][C][esp32_ble_tracker:874]:   Scan Type: PASSIVE
[10:20:31][C][esp32_ble_tracker:875]:   Continuous Scanning: True
[10:20:31][C][mdns:103]: mDNS:
[10:20:31][C][mdns:104]:   Hostname: salon2
[10:20:31][V][mdns:105]:   Services:
[10:20:31][V][mdns:107]:   - _esphomelib, _tcp, 6053
[10:20:31][V][mdns:109]:     TXT: version = 2022.12.2
[10:20:31][V][mdns:109]:     TXT: mac = 94b97efa9fac
[10:20:31][V][mdns:109]:     TXT: platform = ESP32
[10:20:31][V][mdns:109]:     TXT: board = nodemcu-32s
[10:20:31][V][mdns:109]:     TXT: network = wifi
[10:20:31][C][ota:093]: Over-The-Air Updates:
[10:20:31][C][ota:094]:   Address: 192.168.1.189:3232
[10:20:31][C][ota:097]:   Using Password.
[10:20:31][C][api:138]: API Server:
[10:20:31][C][api:139]:   Address: 192.168.1.189:6053
[10:20:31][C][api:141]:   Using noise encryption: YES
[10:20:38][V][esp32_ble_client:111]: [0] [52:C7:F9:B3:08:37] gattc_event_handler: event=41 gattc_if=4
[10:20:38][V][esp32_ble_client:111]: [1] [] gattc_event_handler: event=41 gattc_if=5
[10:20:38][V][esp32_ble_client:111]: [2] [70:F0:90:EA:7C:34] gattc_event_handler: event=41 gattc_if=6`

After I reboot the ESP, everything is working fine. I can see BLE signals are detected on the logs until I can't. I couldn't catch the logs when it stopped working because the browser crashed when I keep the logs open for a long time on VERBOSE mode.

This is my config:
`esphome:
  name: salon2
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Mutlu"
  password: "***"
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.189
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8
# Enable logging
#logger:
  #level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  password: "***"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: false

bluetooth_proxy:
  active: true`

I don't know if it's a coincidence but I feel like Bluetooth Proxy works longer when the log level is lower. When I set the log level to VERBOSE, it stopped working within an hour. When I set it to DEBUG it worked for hours. When I don't enable the logger at all, it works for more than a day.

**Comment by flacjacket** [comment]
Echoing the issues seen here with 2022.12, both with a serial update and an OTA update from 2022.11. I also have an Airthings Wave+ and it will connect successfully as an active bluetooth proxy device when HA starts up, but will go unavailable after 5 minutes. Rolling back ESPHome to 2022.11 OTA fixes the problem.

**Comment by grobius** [comment]
Sorry a newbie question, but how to you roll back to 2022.12 -> 2022.11? Remove ESPHome from HA and reinstall, the recompile devices?

**Comment by Ulrar** [comment]
@grobius You just need to use the container tagged `esphome/esphome:2022.11` and then update your devices as usual.
That said if you're using the Hass OS addon, I have no idea on how you'd do that sorry

**Comment by mutlucan96** [comment]
@grobius for the Home Assistant OS add-on, if you have a backup, only restore the ESPHome add-on then update your devices.

**Comment by grobius** [comment]
> @grobius You just need to use the container tagged `esphome/esphome:2022.11` and then update your devices as usual. That said if you're using the Hass OS addon, I have no idea on how you'd do that sorry

Thanks a lot!

**Comment by txitxo0** [comment]
Not for me. I have 5 LYWSD03MMC just two of them experiment problems because of coverge so I started to use the esphome bt proxy and no problems anymore until this release. After that they both doesn't work in that place with a poor coverage unless I move then close to the HA server itself. So for me it is still not working with (at least) this xiaomi ble thermometer.

I was trying a new configuration thinking it will be better, but apparently not and the problem persists. My current config is this below:

```
substitutions:
  name: "btproxy-estudio"

esphome:
  name: ${name}
  name_add_mac_suffix: false

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

logger:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

binary_sensor:
  - platform: gpio
    pin: GPIO26
    name: "${name}-motion"
    device_class: motion
    filters:
      - delayed_on: 250ms

sensor:
  - platform: adc
    pin: GPIO32
    name: "${name}-illuminance"
    device_class: illuminance
    unit_of_measurement: lx
    update_interval: 60s
    attenuation: auto
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0 * 1.67;
    
    # Uptime sensor
  - platform: template
    name: btproxy Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
```

**Comment by grobius** [comment]
> sdkconfig_options:
>       CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

Ok, out of curiosity what does the CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y enable?

Did you reflash the proxy over serial (not OTA), mine was not working at all until I reflashed via serial

**Comment by Ulrar** [comment]
Can't talk to that other issue but in my case yes, it's flashed over serial.
I do have other bluetooth devices working fine with the new firmware so it's something to do with the Airthings, or more likely with a type of announces

**Comment by txitxo0** [comment]
> > sdkconfig_options:
> >       CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
> 
> Ok, out of curiosity what does the CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y enable?
> 
> Did you reflash the proxy over serial (not OTA), mine was not working at all until I reflashed via serial

I read somewhere, for some boards the Bluetooth device is not enabled by default, so I just tried, but it didn't work better than before.


Yes, I burnt it directly via USB, not OTA to let the build format partitions and this stuff

**Comment by lio0909** [comment]
Same issue here. 
The log:
```[10:13:41][E][esp32_ble_tracker:344]: ESP-IDF BLE scan never terminated, rebooting to restore BLE stack...
[10:13:41][I][app:127]: Forcing a reboot...```
And after 5 minutes I get this:
```[10:18:43][I][ota:113]: Boot seems successful, resetting boot loop counter.
[10:18:43][D][esp32.preferences:113]: Saving 1 preferences to flash...
[10:18:43][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[10:18:44][D][esp32_ble_tracker:327]: Starting scan...
```
until it reboots completely, between 1 and 5-6 hours...

**Comment by Ulrar** [comment]
I haven't noticed any reboots, that might be a different problem.
I'll add an uptime sensor to confirm

**Comment by Ulrar** [comment]
My uptime sensor is at 58 hours so clearly it's not rebooting, that must be a different issue again

**Comment by lio0909** [comment]
ok, seems 2022.12.3 brings a lot of challenges... let's hope it gets fixed in a 2023.x.x version

**Comment by nagyrobi** [comment]
I've got 286 hours uptime on my Olimex board which also runs RF Bridge with 22 timed covers, and a relay, and web interface...

**Comment by wormiedk** [comment]
I think this issue: https://github.com/home-assistant/core/issues/82453#issuecomment-1374605386 Is related. After I downgraded to 2022.11.5 my airthings devices started working again

**Comment by mutlucan96** [comment]
2022.11.1 is also disconnecting and needs reboot sometimes but not as frequently.  I've made automation, when my Bluetooth entity goes unavailable, it reboots ESP.

**Comment by grobius** [comment]
> I think this issue: [home-assistant/core#82453 (comment)](https://github.com/home-assistant/core/issues/82453#issuecomment-1374605386) Is related. After I downgraded to 2022.11.5 my airthings devices started working again

thanks, I will test that. I asume that you reverted back to using the arduino framework? (  framework:
    type: arduino)

**Comment by Ulrar** [comment]
> I asume that you reverted back to using the arduino framework? ( framework: type: arduino)

That's right.
That said the issue in 2022.12 is present regardless of framework, from what I've seen

**Comment by wormiedk** [comment]
> > I asume that you reverted back to using the arduino framework? ( framework: type: arduino)
> 
> That's right. That said the issue in 2022.12 is present regardless of framework, from what I've seen

@Ulrar I just realised that my ESP crashes after 2-3 readouts from my airthings sensors. Could you share the complete config for ESPHOME 2023.11 that you are using?

**Comment by mkbrown** [comment]
Adding to the list of AirThings Wave+ issues… brand new wave+ device, with Olimex ESP32-EVB flashed with Bluetooth BLE proxy.

errors in Home Assistant integration page:

Retrying setup: Unable to fetch data: BT-MAC - BT-MAC: Failed to connect: No backend with an available connection slot that can reach address BT-MAC was …

and

Retrying setup: Could not find Airthings device with address BT-MAC

Other log messages:

Error fetching airthings_ble data: Unable to fetch data: 'battery'

Config entry 'Airthings Wave+ (serial#)' for airthings_ble integration not ready yet: Unable to fetch data: 'battery'; Retrying in background

BT-MAC Bluetooth device connection timed out but already unsubscribed

**Comment by Ulrar** [comment]
@wormiedk : I added an uptime sensor to one of mine to confirm it wasn't crashing a while ago, it's up to 200 hours now so clearly that's not my issue.
Config is just regular old bluetooth proxy : 

```
esphome:
  name: esp32-relay-livingroom

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  password: !secret esp32-relay-livingroom-password
  encryption:
    key: !secret esp32-relay-livingroom-key

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_pass
  fast_connect: !secret wifi_iot_fast
  domain: .mydomain.tld

mdns:
  disabled: true

ota:
  password: !secret esp32-relay-livingroom-ota

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

button:
  - platform: restart
    name: Restart

switch:
  - platform: safe_mode
    name: use_safe_mode

sensor:
  - platform: uptime
    name: Uptime Sensor
```

I'm seeing the same behavior as described by @mkbrown, on startup of either HA or the board I get one reading from the AirThings Wave+ and the integration setups fine.
Then every time I get `Error fetching airthings_ble data: Unable to fetch data: 'battery'`, including if I try to reload the integration, until I restart either the board of HA itself.
