### ISSUE TITLE
Midea_ir not working with Midea MSCI-12HRDN1 or MFF-12HRDN1

### ISSUE THREAD

**Issue by x-zvf** [esphome/issues#3960]
### The problem

Controls sent using the `midea_ir` platform are not recognized by my ACs (MSCI-12HRDN1, MFF-12HRDN1).
The signals of my remote `RG07G/BGE` are decoded correctly.

Using the `coolix` platform or `heatpumpir` with protocol `midea`, it works fine
 However, the read-back by the remote does not work (as that is using the midea protocol) and so, getting `midea_ir` to work would be great.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.12.8

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

midea_ir

### Example YAML snippet

```yaml
remote_receiver:
  id: rcvr
  pin:
    number: D2
    inverted: true
    mode:
      input: true
      pullup: true
  # high 55% tolerance is recommended for some remote control units
  tolerance: 55%
  dump: raw

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

climate: # not working
  - platform: midea_ir
    name: "This only reads back, but sending does not work"
    use_fahrenheit: false
    receiver_id: rcvr

climate: # working
  - platform: coolix
    name: "This sends, but can't read back the remote"
    receiver_id: rcvr

climate: # also works
  - platform: heatpumpir
    name: "This sends"
    protocol: midea
    horizontal_default: middle
    vertical_default: middle
    max_temperature: 30.0
    min_temperature: 17.0
```
