### ISSUE TITLE
esp-idf does not build on windows

### ISSUE THREAD

**Issue by evlo** [esphome/issues#3961]
### The problem

I have tried on multiple win10 and win11 computers, python 3.11.1, wheels installed, 
result is always what is in screenshot bellow
I think it is not permissions, but filename issue

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

t01-c3,esp32-cam

### Component causing the issue

pyYaml?

### Example YAML snippet

```yaml
esphome:
  name: ehidfdemo
esp32:
  board: esp32cam
  framework: 
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
```


### Anything in the logs that might be useful for us?

```txt
![image](https://user-images.githubusercontent.com/8813196/209432055-956e8402-02ea-4951-92a1-fae12f90648e.png)
```

### Additional information

maybe not exactly issue with esphome, but something in the build stuff it is using python, wheels, pip, some library, framework, etc.
