### ISSUE TITLE
ESP8266 incompatible with bluetooth_proxy?

### ISSUE THREAD

**Issue by issmirnov** [esphome/issues#3964]
### The problem

I have some ESP 8266 smart home plugs from Athom (v1, https://www.athom.tech/blank-1/us-v2-plug-for-esphome). 

I would like to use the newly released bluetooth_proxy and esp32_ble_tracker options to expand my homeassistant range.

I cannot get the config to compile, as esp32_ble_tracker depends on esp32 and esp32 can't be added since we already have esphome>platform:ESP8266.

Is the 8266 compatible with bluetooth_proxy?

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2022.12.8

### What platform are you using?

ESP8266

### Board

esp8285

### Component causing the issue

bluetooth_proxy

### Example YAML snippet

```yaml
substitutions:
  device_name: "smart-plug-5"
  friendly_name: "Elude Cluster"
  project_name: "athom.smart-plug"
  project_version: "1.0"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: false
  platform: ESP8266
  board: esp8285
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
esp32_ble_tracker:
  scan_parameters:
  interval: 1100ms
  window: 1100ms
bluetooth_proxy:
  active: true
  cache_services: true

# Enable Home Assistant API
api:

# ...
# etc etc, just wifi/ lights / switches here, nothing relevant to BLE
# ...
```
```


### Anything in the logs that might be useful for us?

```txt
> Please remove the `platform` key from the [esphome] block. You're already using the new style with the [esp8266] block.

This is caused by having both the esp32 block and the esphome>platform: ESP8266
```
