### ISSUE TITLE
ESP8266 devices won't connect with WPA3, while ESP32 does

### ISSUE THREAD

**Issue by acfnews** [esphome/issues#3971]
### The problem

I have several ESP32 and ESP8266 devices.
After migrating home devices (laptops/phones/iPads) onto WPA3 wifi network, it is now time for my ESP devices.

I successfully migrated a ESP32 device, but none of my ESP8266 boards will connect to a WPA3 wifi network.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP8266

### Board

demos-d1-mini

### Component causing the issue

wifi

### Example YAML snippet

```yaml
I am using a secret.yaml file with both the old and new network names:
`# Your Wi-Fi SSID and password
wifi_ssid: "XXX"
wifi_password: "YYYY"

wifi_ssid_wpa3: "333"
wifi_password_wpa3: "ZZZZ"`

In the devices config I have either:
`  platform: ESP8266
  board: d1_mini`
or
`  platform: ESP32
  board: esp32dev`

The wifi config looks like on all:
`wifi:
  networks:
  - ssid: !secret 'wifi_ssid'
    password: !secret 'wifi_password'
    priority: 1.0
  - ssid: !secret 'wifi_ssid_wpa3'
    password: !secret 'wifi_password_wpa3'
    priority: 1.5`
```

### Anything in the logs that might be useful for us?

```txt
the logs only show connecting to the old network, no errors
```

### Additional information

I have not yet hooked up via /dev/serial (sofar used the brilliant OTA), will do this next on my list. Maybe this reveals something more.
