### ISSUE TITLE
Pulse_meter Total resets to 0 at reboot

### ISSUE THREAD

**Issue by rs443** [esphome/issues#3974]
### The problem

I installed "Home Assistant Glow", which uses the pulse meter to measure power consumption, total and daily total. This works very well. I have not integrated esphome into home assistant yet.

However, when rebooting or updating I noticed the Total energy counter resets to 0. The daily total however keeps its value. This must be wrong, right?

I installed it today so I don't know if this is an issue that started in recent versions or not.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

AZ Delivery (esp01_1m)

### Component causing the issue

pulse_meter

### Example YAML snippet

```yaml
- platform: pulse_meter
    name: '${friendly_name} - Power Consumption'
    id: sensor_energy_pulse_meter
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: ${pulse_pin}
    internal_filter: 100ms
    on_value:
      then:
        - light.turn_on:
            id: led_red
        - delay: 0.5s
        - light.turn_off:
            id: led_red
    filters:
      - lambda: return x * ((60.0 / ${pulse_rate}) * 1000.0);
    total:
      name: '${friendly_name} - Total Energy'
      id: sensor_total_energy
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        - lambda: return x * (1.0 / ${pulse_rate});
  # Total day useage
  - platform: total_daily_energy
    name: '${friendly_name} - Daily Energy'
    id: sensor_total_daily_energy
    power_id: sensor_energy_pulse_meter
    unit_of_measurement: 'kWh'
    icon: mdi:circle-slice-3
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
```
```


### Anything in the logs that might be useful for us?

Before reboot:
18:35:47	[D]	[sensor:126]	'Glow - Total Energy': Sending state 2.86100 kWh with 3 decimals of accuracy

After reboot:
18:37:27	[D]	[sensor:126]	'Glow - Total Energy': Sending state 0.00100 kWh with 3 decimals of accuracy


### Additional information
