### ISSUE TITLE
Timezone question

### ISSUE THREAD

**Issue by jeff-h** [esphome/issues#398]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Docker, with docker-compose, running in Ubuntu 19.04 host. The relevant docker-compose fragment:

```
  esphome:
    image: esphome/esphome
    container_name: esphome
    volumes:
      - ${DOCKERDIR}/containers/esphome/config:/config:rw
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Pacific/Auckland
```

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266

**Description of problem:**

When I click "Show Logs", the logs are all 12 hours out from my timezone (eg instead of 21:43 it shows 09:43). Being in GMT+12 here it's hard to say whether it's swapping AM for PM, or whether it's showing in GMT / UTC.

You'll see I attempted to fix this by adding the `TZ` environment in docker-compose, but that hasn't helped.

Would you say this is a problem with my docker machine config (I do have other containers with the correct TZ) or do I need to tell ESPHome my TZ some other way?

The problem raised its head for me because I have my sensor data being collected in Home Assistant, where the historical data graph is showing the correct (ie local NZ) time, but I've just tried to import that data from Home Assistant into Node-RED which is showing the same (wrong) timestamps as ESPHome has.
