### ISSUE TITLE
Shelly 1 Plus - ESP32-U4WDH - Boot loop

### ISSUE THREAD

**Issue by akennerly** [esphome/issues#3984]
### The problem

Attempting to install ESPHome on Shelly 1 Plus. 

Using an example config for this device (YAML below), compiled and flashed using ESPHome Flasher 1.4.0 on Win10. The 
device appears to be in a boot loop after flashing.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.8

### What platform are you using?

ESP8266

### Board

Shelly 1 Plus

### Component causing the issue

wifi?

### Example YAML snippet

```yaml
esphome:
  name: shelly-plus-1
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  use_address: ${ipaddress}
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name}_AP
    password: !secret fallbackpass

logger:

api:
  password: !secret esphomeapipwd



The rest of the device config is from the example from here this source: https://www.esphome-devices.com/devices/Shelly-Plus-1
```

### Anything in the logs that might be useful for us?

I copied the entire log output as it was, it's too long to include here, therefore refer to this gist.

https://gist.github.com/akennerly/c5f484fdf15cf9cc2cd6e6d5bdb16143
