### ISSUE TITLE
FastLED: Unable to turn on leds with - light.addressable_set:

### ISSUE THREAD

**Issue by ChangappaMA** [esphome/issues#3986]
### The problem

Hi Team,

Trying to turn on LED strip based on the distance sensed from the sensor.
Unable to turn on the leds for the set range.
Works if the leds are turned on and then range is passed.

Code Snippet:

```yaml
- platform: homeassistant
    name: "Distance"
    entity_id: sensor.distance_1
    id: user_distance        
    on_value_range:
        - below: 0.70
          above: 0.60
          then:
            - light.addressable_set: ----> Does not work now, was working before last week's update.
                id: my_light
                range_from: 30
                range_to: 60
                red: 100%
                green: 100%
                blue: 100%
        - below: 0.60
          above: 0.50
          then:
            - light.turn_on:  --------> addressable range works fine
                id: my_light
            - light.addressable_set:
                id: my_light
                range_from: 0
                range_to: 30
                red: 1.0
                green: 0.0
                blue: 0.0
```

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.8

### What platform are you using?

ESP8266

### Component causing the issue

FastLED
