### ISSUE TITLE
waveshare_epaper 1.54inv2

### ISSUE THREAD

**Issue by jwillmer** [esphome/issues#3999]
### The problem

I only like to update the display once and then go to deep sleep. But if I use `component.update: epaper_display` it will only do a partial refresh and does look grainy. It will also not remember the `full_update_every` property so that it will never do a full display update when returning from deep sleep. When putting the update interval to: `update_interval: 2s` it works and looks good but then I don't have much control over it and it renders the image way to often - energy consumption on battery!

### Which version of ESPHome has the issue?

v2022.12.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

D1 Mini Pro

### Component causing the issue

MH-ET LIVE 1.54in E-Paper

### Example YAML snippet

```yaml
esphome:
  name: solar-status
  on_boot:
    priority: -900
    then:
      - wait_until: api.connected
      - script.execute: process
      
...

script:
  - id: process
    then:
    - ..
    - ...
    - logger.log: "Update display"
    - component.update: epaper_display
    - logger.log: "Sleep for 15 sec to let the e-paper complete the update process"
    - delay: 15s
    - if: 
        condition: 
          lambda: |-
            ...
            return isDayTime;
        then:
          - logger.log: "Sleep for 5 min during the sun is up"  
          - deep_sleep.enter:
              id: deep_sleep_1
              sleep_duration: 5min
        else:
          - logger.log: 
              format: "Sleep for %d hours during the sun is down" 
              args: [ 'id(night_sleep_hours)' ]
          - deep_sleep.enter:
              id: deep_sleep_1
              sleep_duration: !lambda return id(night_sleep_hours) * 3600000;

...

spi:
  clk_pin: D5
  mosi_pin: D7

display:
  - platform: waveshare_epaper
    # 200x200 Pixel
    id: epaper_display
    rotation: 90°
    cs_pin: D6
    dc_pin: D3
    busy_pin: D2
    reset_pin: D1
    model: 1.54inv2
   # full_update_every: 1
    update_interval: never
   # update_interval: 2s
   # reset_duration: 2ms
    lambda: |-
      ...
```

### Anything in the logs that might be useful for us?

```txt
...
[D][main:113]: Update display
[D][main:203]: Sleep for 15 sec to let the e-paper complete the update process
[VV][scheduler:026]: set_timeout(name='', timeout=15000)
[V][component:200]: Component script took a long time for an operation (0.13 s).
[V][component:201]: Components should block for at most 20-30ms.
[VV][api.service:470]: on_ping_request: PingRequest {}
[VV][api.service:043]: send_ping_response: PingResponse {}
[VV][scheduler:195]: Running timeout '' with interval=15000 last_execution=40888 (now=55894)
[D][main:134]: Sleep for 10 hours during the sun is down
[I][deep_sleep:116]: Beginning Deep Sleep
[I][deep_sleep:118]: Sleeping for 36000000000us
[E][waveshare_epaper:119]: Timeout while displaying image!
[VV][api.service:025]: send_disconnect_request: DisconnectRequest {}
```

### Additional information

![image](https://user-images.githubusercontent.com/1503577/210279560-60b59c01-1281-493e-b005-1243fb24f3d4.png)
