### ISSUE TITLE
DHT22 issue

### ISSUE THREAD

**Issue by mssmison** [esphome/issues#4]
I'm running into issues with my DHT22
```
[22:39:33][W][sensor.dht:141]: Requesting data from DHT failed!
[22:39:33][W][sensor.dht:076]: Invalid readings! Please check your wiring (pull-up resistor, pin number).
```
It works without issue on Tasmota.

My config is as follows (wifi info removed)

```
esphomeyaml:
  name: temp_humid_test
  platform: ESP8266
  board: d1_mini

sensor:
  - platform: dht
    pin: D2
    model: DHT22
    temperature:
      name: "temperature"
    humidity:
      name: "humidity"
    update_interval: 15s
```
