### ISSUE TITLE
Assumed state (template) switch not working on webserver UI

### ISSUE THREAD

**Issue by RoboMagus** [esphome/issues#4001]
### The problem

When declaring an `assumed_state` template switch, the webserver UI will continue to show a toggle switch. 
This will remove the option of having the user select the 'on' or 'off' commands.

### Which version of ESPHome has the issue?

2022.11.x-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/a

### What platform are you using?

ESP32

### Component causing the issue

webserver

### Example YAML snippet

```yaml
switch:
  - platform: template
    name: IR Candles
    assumed_state: true
    optimistic: false
    turn_on_action:
      - script.execute: candles_on
    turn_off_action:
      - script.execute: candles_off
```
