### ISSUE TITLE
Ethernet not coming up at boot with PoE

### ISSUE THREAD

**Issue by dunc623b** [esphome/issues#4006]
### The problem

Hi,

I have an Olimex ESP32-POE board and have been using it with ESPHome for at least 6 months with no issues, powered with PoE and not using the WiFi.

Yesterday I pushed out an OTA update to upgrade to latest version and it never came back online.

I've powered it up from USB so that I can see the logs, and it still boots fine, but the Ethernet part fails to start properly. Please see logs below

If I then flap the switch port where the device is connected, the Ethernet then starts up and connects fine and we're back in business.

This workaround is obviously no good when I'm actually powering the device with PoE though as flapping the port resets the device and we're back to the no connecting.

I found the following post, talking about GPIO12:  https://github.com/esphome/esphome/pull/2902

.... so thought it might be something to do with that as I have GPIO12 as the power pin, but that is what the sample config for an Olimex POE-32 says to use. I tried commenting out the power pin line anyway but then it doesn't work at all.

Hope someone can help.

Cheers,

Dunc

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.9

### What platform are you using?

ESP32

### Board

Olimex ESP32-POE

### Component causing the issue

Ethernet

### Example YAML snippet

```yaml
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  manual_ip:
    static_ip: 172.23.24.195
    gateway: 0.0.0.0
    subnet: 255.255.255.0
```

### Anything in the logs that might be useful for us?

```txt
[C][ethernet:028]: Setting up Ethernet...
[I][ethernet:105]: Starting ethernet connection
[W][ethernet:122]: Connecting via ethernet failed! Re-connecting...
[W][ethernet:122]: Connecting via ethernet failed! Re-connecting...
```
