### ISSUE TITLE
1.4" ST7735S Shield Colors

### ISSUE THREAD

**Issue by TimothyGaray** [esphome/issues#4009]
### The problem

I reviewed [#3285](https://github.com/esphome/issues/issues/3285) but I don't see a solution for this.

I bought several of these 1.4" shields which connect to Wemos D1 mini.  I tried a couple but get the same issue.
[ESP8266 TFT 1.4 Shield](https://www.aliexpress.us/item/2251832714188898.html?spm=a2g0o.order_detail.order_detail_item.3.76f5f19cnABRQo&gatewayAdapt=glo2usa&_randl_shipto=US)

It reports this is a ST7735S Driver IC.

Everything works fine except the colors are wrong when I try to display text.  I can get white or version of blue no mater what color definitions I use.  I tried yellow, red, and variations but they come out as blue.

If I invert the colors then I get a little bit closer but of course the background is white and the normal text is black but the color of the text I request is not just a variation of blue.

I've seen that there were color issues with the ST7735S library but I haven't seen how to get around it.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.5

### What platform are you using?

ESP8266

### Board

ESP8266 TFT 1.4 Shield

### Component causing the issue

display colors

### Example YAML snippet

```yaml
Color
  - id: my_yellow
    red: 80%
    green: 100%
    blue: 0%
    white: 0%
  - id: COLOR_CSS_TOMATO
    red:   1.0000
    green: 0.3882
    blue:  0.2784
    white: 0.0000


display:
  - platform: st7735
    model: "INITR_18REDTAB"
    #reset_pin: D4
    cs_pin: GPIO2
    dc_pin: GPIO0
    rotation: 0
    device_width: 130
    device_height: 131
    col_start: 0
    row_start: 0
    eight_bit_color: True
    invert_colors: False
    update_interval: 3s
    lambda: |-
      it.printf(64, 0, id(font2), my_yellow, TextAlign::TOP_CENTER, "Temps");
      it.strftime(5, 30, id(font1), TextAlign::BASELINE_LEFT, "Time: %m/%d/%Y  %H:%M", id(esptime).now());
      if (id(waterheatertemp).has_state()) {
        it.printf(5, 110, id(font2), id(COLOR_CSS_TOMATO), TextAlign::BASELINE_LEFT , "Wtr Htr: %.1f°F", id(waterheatertemp).state);
      }
```

### Additional information

Text and fonts are all displayed correctly - just not the color I would like.
