### ISSUE TITLE
 ledc component NOT working with esp32 s2 mini

### ISSUE THREAD

**Issue by soubhik-khan** [esphome/issues#4011]
### The problem

I’m unable to get the ledc component working with esp32 s2 mini. I tested with esp8266 d1 mini and esp32 d1 mini, it works well, but on s2 mini, there is no output on mosfet. I tried with GPIO 13, 14, 15,16 - non of the pins provide the voltage to the mosfet.

Logs on esphome web doesn't show any errors! 

### Which version of ESPHome has the issue?

v2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

 2023.1.1

### What platform are you using?

ESP32

### Board

Esp32 S2 mini

### Component causing the issue

ledc

### Example YAML snippet

```yaml
output:
  - platform: ledc
    pin: GPIO14
    id: pwm_output
light:
  - platform: monochromatic
    output: pwm_output
    name: "Living Room LED"  
    id: led_1
```
