### ISSUE TITLE
TVOC unit discrepency between home assistant and esphome

### ISSUE THREAD

**Issue by xconverge** [esphome/issues#4012]
### The problem

Home assistant warns about an unsupported unit when using ppb for volatile organic compound 

https://github.com/home-assistant/core/issues/85170

The ccs811 sensor and a few others typically report ppb https://github.com/esphome/esphome/blob/dev/esphome/components/ccs811/sensor.py#L43

I can simply multiply by 4.5 and manually set the units to get out of this situation using this reference in section 2.3

https://www2.dmu.dk/atmosphericenvironment/expost/database/docs/ppm_conversion.pdf

My question is should I just do this and move on or is there a PR that more people could benefit from here

Other recent references of people who might want to see this:
https://github.com/home-assistant/core/issues/85266#issuecomment-1373575626
https://github.com/home-assistant/core/issues/85344

### Which version of ESPHome has the issue?

2022.12.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.1.0

### What platform are you using?

ESP8266

**Comment by xconverge** [comment]
This is what I am using now as a workaround/fix, but if this issue had any traction we might want to make this part of the tvoc specific sensors or documentation

```
  - platform: ccs811
    eco2:
      name: "CCS811 eCO2 Value"
    tvoc:
      name: "CCS811 Total Volatile Organic Compound"
      unit_of_measurement: "µg/m³"
      filters:
        - multiply: 4.5
    address: 0x5A
    update_interval: 60s
    # https://esphome.io/components/sensor/ccs811.html#calibrating-baseline
    baseline: 0x2AC5
```
