### ISSUE TITLE
device_class preciptitation is missing

### ISSUE THREAD

**Issue by hmorkemo** [esphome/issues#4016]
### The problem

precipitation is listed as a device class in https://www.home-assistant.io/integrations/sensor/ ,
but specifying a sensor device_class: precipitation gives an error message when compiling an esphome device.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.1.1

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

hydreon_rgxx

### Example YAML snippet

```yaml
sensor:
  - platform: hydreon_rgxx
    model: "RG_15"
    update_interval: 60s
    acc:
      name: "Regn"
      device_class: precipitation
```
