### ISSUE TITLE
GET values from a JSON body response  example seems to be broken

### ISSUE THREAD

**Issue by danpadure** [esphome/issues#4017]
### The problem

I am trying to implement the example from here:
https://esphome.io/components/http_request.html?highlight=json#esphome-esp8266-disable-ssl-support

time:
    - platform: sntp
      #...
      on_time:
        #every 5 seconds
        - seconds: /5
          then:

            - http_request.get:
                url: http://192.168.12.161/sensor/duty-cycle
                verify_ssl: false
                headers:
                    Content-Type: application/json
                on_response:
                    then:
                      - lambda: |-
                            json::parse_json(id(http_request_data).get_string(), [](JsonObject root) {
                                id(number-duty_cycle_red).publish_state(root["sensor-duty-cycle"]);
                            });

I get this error:
Couldn't find ID 'http_request_data'. Please check you have defined an ID with that name in your configuration.

So it seems to me that parse_json line is incorrect
Can't seem to figure out what's wrong

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

d1 mini

### Component causing the issue

parse_json

### Example YAML snippet

```yaml
esphome:
  name: pwmreceiver

esp8266:
  board: d1_mini

# Enable logging
logger:
    #level: VERY_VERBOSE

# Enable Home Assistant API
# api:
#   password: "danparola"

number: 
    platform: template
    name: "duty_cycle_red"
    min_value: 0
    max_value: 100
    step: 0.1
    optimistic: True

ota:
  password: "danparola"


wifi:
    networks:
        - ssid: "zzzzz"
          password: "zzzzz"
        - ssid: "zzzzz"
          password: "zzzzz"
      

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "pwm-receiver Fallback Hotspot"
        password: "danparola"

captive_portal:
    


# Example configuration entry
web_server:
  port: 80




  # Example configuration entry
http_request:
    useragent: esphome
    timeout: 10s
    esp8266_disable_ssl_support: True


time:
    - platform: sntp
      #...
      on_time:
        #every 5 seconds
        - seconds: /5
          then:

            - http_request.get:
                url: http://192.168.12.161/sensor/duty-cycle
                verify_ssl: false
                headers:
                    Content-Type: application/json
                on_response:
                    then:
                      - lambda: |-
                            json::parse_json(id(http_request_data).get_string(), [](JsonObject root) {
                                id(number-duty_cycle_red).publish_state(root["sensor-duty-cycle"]);
                            });
```

### Anything in the logs that might be useful for us?

```txt
Couldn't find ID 'http_request_data'. Please check you have defined an ID with that name in your configuration.
```
