### ISSUE TITLE
BME280 is overheating and then shows inaccurate values

### ISSUE THREAD

**Issue by Shwamp** [esphome/issues#402]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome 1.13.4  , Hass.io 0.93.2

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 Mini

**Affected component:**

https://esphome.io/cookbook/bme280_environment.html?highlight=bme280

**Description of problem:**
Im using [this](https://www.banggood.com/BME280-Digital-Sensor-Temperature-Humidity-Atmospheric-Pressure-Sensor-Module-p-1354769.html?rmmds=search&cur_warehouse=USA) sensor for indoor / weather application. Currently setup on a breadboard like shown i the picture below
![IMG_3354](https://user-images.githubusercontent.com/28205516/58910032-d12d1880-8714-11e9-8ec6-524f7e9dff1c.jpg)
I noticed that the temperature readings of the BME280 sensor where 1-2 °C higher then another temperature sensor that I'm using (VMA324). And with a fast google search i found out that the sensor is overheating when its used with _oversampling_, high _update_interval_ and the wrong _power mode_.

According to the [datasheet](https://www.embeddedadventures.com/datasheets/BME280.pdf) when it is used for weather monitoring the following settings is recommended:

![Skärmavbild 2019-06-04 kl  21 00 36](https://user-images.githubusercontent.com/28205516/58906305-eb162d80-870b-11e9-9eba-228fa3202641.png)

The oversampling should be changed in the ESPHOME example code to "oversampling: 1x".

The datasheet also recommends the use of  _"forced mode"_, and what i found [here](https://github.com/finitespace/BME280/issues/23#issuecomment-298822853) the sensor should be put to sleep and then woken up to measure the temperature. The time used between the sensor should be either configurable or set to 60 seconds according to the datasheet. Maybe with a loop or something? 🤔 

![Skärmavbild 2019-06-04 kl  21 07 08](https://user-images.githubusercontent.com/28205516/58906669-bce51d80-870c-11e9-9bc3-68b0f7b19220.png)

Without the ability to set the sensor to the **forced power mode** it will continue to show wrong values.

I think that a warning about this kind of issue also should be put on the BME280 page to avoid other people making a similar kind of mistake 😅.

References:
[https://tinkerman.cat/post/low-power-weather-station-bme280-moteino](https://tinkerman.cat/post/low-power-weather-station-bme280-moteino)
[https://github.com/finitespace/BME280/issues/23](https://github.com/finitespace/BME280/issues/23)
[https://github.com/rwaldron/johnny-five/issues/1274](https://github.com/rwaldron/johnny-five/issues/1274)

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: bme280
    temperature:
      name: "Wemos d1 mini 1 BME280 Temperatur"
      oversampling: 1x
      id: "bme280_temperature"
    pressure:
      name: "Wemos d1 mini 1 BME280 Tryck"
      oversampling: 1x
      id: "bme280_pressure"
    humidity:
      name: "Wemos d1 mini 1 BME280 Humidity"
      oversampling: 1x
      id: "bme280_humidity"
    address: 0x76
    update_interval: 60s

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
