### ISSUE TITLE
ESP32-C3 with canbus component doesn't compile

### ISSUE THREAD

**Issue by bakermat** [esphome/issues#4023]
### The problem

I'm trying to use the CAN bus component with the ESP32-C3, without success. With the device type set to `esp32-c3-devkitm-1` and the correct GPIO pins, the compiling doesn't work with a message showing there's a deprecated driver.

I've tried it with an ESP32 and the device type set accordingly, that worked fine.

### Which version of ESPHome has the issue?

2023.1.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.1

### What platform are you using?

ESP32

### Board

ESP32-C3-MINI

### Component causing the issue

canbus

### Example YAML snippet

```yaml
esphome:
  name: ${device_name}
  comment: "${device_description}" 
  platformio_options:
    upload_speed: 921600
    platform: espressif32@5.3.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: 2.0.6

canbus:
  - platform: esp32_can
    tx_pin: GPIO1
    rx_pin: GPIO3
    can_id: 4
```

### Anything in the logs that might be useful for us?

```txt
Compiling /data/test-device/.pioenvs/test-device/src/esphome/components/esp32_can/esp32_can.cpp.o
In file included from src/esphome/components/esp32_can/esp32_can.cpp:5:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/driver/include/driver/can.h:13:2: warning: #warning driver/can.h is deprecated, please use driver/twai.h instead [-Wcpp]
 #warning driver/can.h is deprecated, please use driver/twai.h instead
  ^~~~~~~
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/driver/include/driver/can.h:15:10: fatal error: hal/can_types.h: No such file or directory
 #include "hal/can_types.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
*** [/data/test-device/.pioenvs/test-device/src/esphome/components/esp32_can/esp32_can.cpp.o] Error 1
```

### Additional information

Used an ESP32 board in the past, config worked fine. However since switching to an ESP32-C3 the code doesn't compile anymore.
