### ISSUE TITLE
TSL2591 Ambient Light Sensor Auto Gain Mode Reporting

### ISSUE THREAD

**Issue by 0x90ChuckTessela** [esphome/issues#4031]
### The problem

The TSL2591 Ambient Light Sensor component (https://esphome.io/components/sensor/tsl2591.html) does not currently expose its actual gain value when in "auto" gain mode.

When in "auto" gain mode, it properly adjusts the gain value and reports relative values across full spectrum, infrared, visible, and an estimated/calculated lux.  However, it does _not_ provide any indication via sensor value publishing of the _actual gain_ used for those readings.  When transitioning between extremes (very dark, to very bright or vice-versa) the auto gain mode appears to function correctly; however, without a "gain" readout for what is being used to determine the raw values/lux, it can create a misleading situation where low and high light values spanning an auto adjustment may be perceived as inverted.

This can lead to incorrect conclusions for automation and users where a room may be perceived as darker than before even though it is now brighter (or vice versa).

I believe the correct route would be to publish the actual gain value being used when in "auto" mode, as well as other modes, probably as a numeric value (e.g. 1x, 25x, 400x, 9500x).  This seems like it might be a feature request, but I can also see the case for filing it as a bug since it provides values that are potentially misleading relative to one another.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.2

### What platform are you using?

ESP32

### Component causing the issue

tsl2591

### Example YAML snippet

```yaml
sensor:
  - platform: tsl2591
    name: "${node_name} Light Sensor"
    id: "${node_id}_Light_Sensor"
    address: 0x29
    update_interval: 1s
    device_factor: 53
    gain: auto
    glass_attenuation_factor: 14.4
    integration_time: 500ms
    visible:
      name: "${node_name} TSL2591 Visible Light"
      id: "${node_id}_Visible_Light"
    infrared:
      name: "${node_name} TSL2591 Infrared Light"
      id: "${node_id}_Infrared_Light"
    full_spectrum:
      name: "${node_name} TSL2591 Full Spectrum Light"
      id: "${node_id}_Full_Spectrum_Light"
    calculated_lux:
      name: "${node_name} TSL2591 Lux"
      id: "${node_id}_i_lux"
```

### Additional information

The issue appears to be consistent across any version supporting the component.  It appears, based on https://github.com/esphome/feature-requests/issues/267 that this is a hold-over from the addition of "auto" mode.
