### ISSUE TITLE
Problem with a display SH1106 on the I2C bis

### ISSUE THREAD

**Issue by dnwalker68** [esphome/issues#4034]
### The problem

I have connected a SH1106 display to pins D1(SCL) and D2(SDA) on a Wemos D1mini. The display gets its supply voltage directly from the Wemos via the 3V3 and GND connections. When the Wemos is booted, a text output appears briefly on the display and then I have the problem that the Wemos no longer connects to my WLAN.

If I disconnect the power supply to the display, the Wemos boots without any problems and also connects to my WLAN.

Now one could assume it would be a problem with the power supply. But since the text is output on the display, I rule that out.

Since I could not eliminate the problem, I wanted to check the hardware structure and put the unmodified circuit into operation with EasyESP and set up the display there. Here the text is output without any problems and the WLAN connection is also absolutely stable.

So it can’t be the hardware because I haven’t changed it at all.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.4

### What platform are you using?

ESP8266

### Board

Wemos D1mini

### Component causing the issue

i2C

### Example YAML snippet

```yaml
esphome:
  name: bewaesserung

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "8a6a3e63fd149981876da0784f2b69b5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.195
    gateway: 192.168.1.1
    subnet: 255.255.255.0  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bewaesserung Fallback Hotspot"
    password: "REPlOmXz6sKO"

captive_portal:
    
    
web_server:
  port: 80
  auth:
    username: admin
    password: elektor45
    
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a
  # frequency: 10khz
  
switch:

#WLAN LED auf den Boards
  - platform: gpio
    pin: GPIO2
    restore_mode: ALWAYS_OFF
    id: WlanLed # die ID kann optional vergeben werden
    name: "Wlan Gartensteuerung"
    disabled_by_default: false
    internal: true
    inverted: true
#-----------------------

  - platform: restart
    name: "Bewaesserung Restart"

  - platform: gpio
    pin: GPIO16
    restore_mode: ALWAYS_OFF
    inverted: true
    name: "Beweasserung Pumpe"
#    disabled_by_default: false
    id: Gartensteuerung_Kanal_1

  - platform: gpio
    pin: GPIO14
    restore_mode: ALWAYS_OFF
    inverted: true
    name: "Beweasserung Beet_rechts"
#    disabled_by_default: false
    id: Gartensteuerung_Kanal_2
    
  - platform: gpio
    pin: GPIO12
    restore_mode: ALWAYS_OFF
    inverted: true
    name: "Beweasserung Beet_links"
#    disabled_by_default: false
    id: Gartensteuerung_Kanal_3
    
  - platform: gpio
    pin: GPIO13
    restore_mode: ALWAYS_OFF
    inverted: true
    name: "Beweasserung Rasen"
#    disabled_by_default: false
    id: Gartensteuerung_Kanal_4
    
#Restartbutton für Boards
  - platform: restart
    name: "Restart Beweasserung"  
#------------------------
  
interval:
  - interval: 5s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - switch.turn_on: WlanLed
        else:
          - switch.turn_off: WlanLed 
          
          
sensor:    
  - platform: wifi_signal
    name: "WiFi Beweasserung"
    update_interval: 60s   
    
    
  - platform: adc
    pin: A0
    name: "Bodenfeuchtigkeit"
    update_interval: 120s
    
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESPIPAddress
      id: ipadresse
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results    
     
    
display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
#    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(font1), "IP: %s", id(ipadresse).state.c_str());


font:
  - file: 'fonts/arial.ttf'
    id: font1
    size: 12
    glyphs:
      ['&', '@', '!', ',', '.', '?', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z','å', 'Ä', 'ä', 'Ö', 'ö', 'Ü', 'ü', '/',]

color:
  - id: red
    red: 100%
    green: 0%
    blue: 0%

  - id: grey
    red: 70%
    green: 70%
    blue: 70%
    
  - id: yellow
    red: 100%
    green: 100%
    blue: 0%

  - id: black
    red: 0%
    green: 0%
    blue: 0%
    
  - id: green
    red: 0%
    green: 100%
    blue: 50%
    
  - id: blue
    red: 0%
    green: 0%
    blue: 100%
```
