### ISSUE TITLE
On_value_range doesn't support "FOR" condition(?)

### ISSUE THREAD

**Issue by Tryfos** [esphome/issues#4044]
### The problem

Whenever I add the "for" condition (https://esphome.io/guides/automations.html#for-condition) to a on_value_range automation, all the conditions do not work (not just the "for" condition). The action is always triggered.
Is the "for" condition supported in a on_value_range automation?
This is similar to unresolved issue #3255 
I also compile the code just fine with no errors, but the automation does not work.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.5

### What platform are you using?

ESP8266

### Board

Flashed smart plug Moesrgb (esp01_1m)

### Component causing the issue

on_value_range condition

### Example YAML snippet

```yaml
sensor:
  - platform: hlw8012
    <<: !include common/devices/plugs/moesrgb/hlw8012_base.yaml
    power:
      name: $friendly_name power
      unit_of_measurement: W
      id: power
      on_value_range:
        - below: 7.5
          then:
            - if:
                condition:
                  - for:
                      time: 2s
                      condition:
                        sensor.in_range:
                          id: power
                          below: 7.5
                  - light.is_on: rgb_light
                then:
                  light.turn_off: rgb_light
```

### Additional information

If I remove the "for" condition and/or add any other conditions to the automation, it works as expected.
