### ISSUE TITLE
IR Receiver not parsing Magiquest results

### ISSUE THREAD

**Issue by mikerenna** [esphome/issues#4048]
### The problem

I have two different Magiquest wands for my kids and am attempting to leverage the ESPHome support for the protocol. However, I an not seeing any magiquest protocol results. With an "all" setting for the IR receiver, i see only pronto labeled results. if i set it to magiquest i get nothing, and if set to raw, i see plenty of data rows labeled as raw. Any idea what might be the issue here? I recognize that perhaps the wands are the problem. I have no way to prove they are sending maqiquest protocol beyond that they are marketed as Magiquest by the Great Wolf Lodge where my kids got them. Any ideas on how to troubleshoot this would be appreciated. Thanks in advance. -Mike
[logs_maqiquest-1_upload.txt](https://github.com/esphome/issues/files/10458554/logs_maqiquest-1_upload.txt)

### Which version of ESPHome has the issue?

2.0.6

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

IR Receiver

### Example YAML snippet

```yaml
remote_receiver:
  pin:
    number: GPIO32
    inverted: true
    mode:
      input: true
  dump: all
```

**Comment by F0rged** [comment]
I am fighting with the same issue. Did you ever figure this out?

**Comment by NeoMatrixJR** [comment]
Same, following.

**Comment by mikerenna** [comment]
Thanks Blake. I gave up on the idea. Would have been cool, but I was ultimately defeated. ☹ Thanks for the information. At least I know I’m not crazy.

**Comment by sreknob** [comment]
Following up here.
I was able to get it reliably working again on the current version just by telling the controller to stop dumping other codes.

Relevant config:
```
remote_receiver:
  pin:
    number: D5
    inverted: true
    mode:
      input: true
      pullup: true
  dump:
    - magiquest

binary_sensor:
  - platform: remote_receiver
    name: "Grant's Wand"
    id: grants_wand
    magiquest:
      wand_id: 0x020DF054

  - platform: remote_receiver
    name: "Luke's Wand"
    id: lukes_wand
    magiquest:
      wand_id: 0x020EA194
```

```
[13:01:21][I][app:102]: ESPHome version 2023.11.6 compiled on Dec  1 2023, 12:58:58
[13:06:07][I][ota:117]: Boot seems successful, resetting boot loop counter.
[16:09:12][I][remote.magiquest:079]: Received MagiQuest: wand_id=0x020DF054, magnitude=0x0C0B
[16:09:15][I][remote.magiquest:079]: Received MagiQuest: wand_id=0x020EA194, magnitude=0x0815
[16:09:15][I][remote.magiquest:079]: Received MagiQuest: wand_id=0x020EA194, magnitude=0x0C09
```
