### ISSUE TITLE
LEDC bit_depth calculation is not working properly on Arduino framework in ESPHome 2022.12.3 and dev

### ISSUE THREAD

**Issue by xvil** [esphome/issues#4050]
### The problem

I am using the esp32-c3-devkitm-1 board (or a board that's close enough to that one).
Important note: I used the ledc component from the dev branch

The LEDC component is working fine under the IDF framework.  With my configuration,
 ```
 - platform: ledc
    id: fan_speed
    pin: 
      number: GPIO04
    power_supply: fan_power
    channel: 0
    frequency: 25000 Hz
    inverted: true
    min_power: 0%
    max_power: 100%
```
I get a bit_depth resolution of 11 bits.

When I run the same configuration but using the arduino framework, it stops working.
After some investigations, it appears that:

- the computed bit depth for my frequency (25kHz) is still 11 bits but it's not accepted by the call to ledcSetup (returns 0 and not the actual frequency when successful)
- with a bit-depth of 10, it's working nicely.
- Since Arduino 2.0.2, the actual clock being used has changed (see https://github.com/espressif/arduino-esp32/blob/2.0.2/cores/esp32/esp32-hal-ledc.c), as it uses the XTAL clock if it's available, the AUTO CLK if not.  The ESP32C3-mini I use has the crystal for sure.
- Forcing the IDF esphome code to use LEDC_USE_XTAL_CLK instead of LEDC_AUTO_CLK gives the very same issue (only 10-bits can be used instead the computed 11-bits).

Using Arduino 2.0.1 (the version before the default clock change for LEDC in Arduino), ESPHome ledc component is actually working with 11-bits bit_depth.  The change in ledc implementation in arduino 2.0.2+ is then breaking the current and dev code of the ledc component in ESPHome.

### Which version of ESPHome has the issue?

2022.12.3, dev

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1

### Component causing the issue

ledc
