### ISSUE TITLE
Can't use MQTT on Raspberry Pico W

### ISSUE THREAD

**Issue by utdrmac** [esphome/issues#4055]
### The problem

```
$ esphome run garage.yaml --device /dev/tty.usbmodem144101
INFO Reading configuration garage.yaml...
Failed config

mqtt: [source garage.yaml:12]

  This feature is only available on ['esp32', 'esp8266'].
  broker: 10.10.10.10
  port: 1883
```

### Which version of ESPHome has the issue?

2022.11.5

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

RP2040

### Board

Raspberry Pi Pico W

### Component causing the issue

mqtt

### Example YAML snippet

```yaml
---
esphome:
  name: garage-pico

rp2040:
  board: rpipicow

  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

mqtt:
  broker: 10.10.10.203
  port: 1883

output:
  - platform: gpio
    pin:
      number: 32  # 25 for Pico (non-W)
      mode: output
    id: LED

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
