### ISSUE TITLE
Misleading error message in deep_sleep component run_duration

### ISSUE THREAD

**Issue by Doridian** [esphome/issues#4059]
### The problem

With the following ESPHome config:
```
deep_sleep:
  id: battery_deep_sleep
  run_duration: 5m # The error is this, it should be "5min"
  sleep_duration: 1h
```

I got a very misleading error which lead me down a completely wrong debug path:
```
deep_sleep: [source /config/esphome/base/lilygo-t5.yaml:34]
  id: battery_deep_sleep
  
  expected a dictionary.
  run_duration: 5m
  sleep_duration: 1h
```

The actual correct error should be more like what happens when you misconfigure `sleep_duration`, which will likely yield a user to the right solution almost immediately:
```
  Unknown value 'm', did you mean 'ms'?.
  sleep_duration: 1m
```

I assume this error happens because `run_duration` could be either a dictionary or a time spec? Does it simply do a "try parse as time spec, if not, try parse as dictionary" type of codepath? If so, that would explain this behaviour (and  likely in such case the solution would be to assume its a timespec, except if it actally **is** a dictionary type)

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.7

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
deep_sleep:
  id: battery_deep_sleep
  run_duration: 5m # The error is this, it should be "5min"
  sleep_duration: 1h
```
