### ISSUE TITLE
Bang Bang Climate HA oddities

### ISSUE THREAD

**Issue by chaolue** [esphome/issues#406]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff / Sonoff POW

**Affected component:**

Bang Bang Climate

**Description of problem:**
A number of issues when using the new climate component under Home Assistant through the ESPHome API:

1. I'm unable to set the 'target_temp_low' via a HA automation or service call. I receive the following HA error - `some but not all values in the same group of inclusion 'temperature' @ data[<temperature>]`

Example service call:
`{
  "entity_id": "climate.our_heater",
  "temperature": 20,
  "target_temp_low": 21
}`

2. Maybe my misunderstanding of how the new bang bang climate component should work; but shouldn't a heating-only climate device only need a min temperature?

3. Cosmetically, when the visual temperature_step is set in ESPHome, the climate component temperature (sensor) value is also rounded. I would have expected that the temperature step only effected the slider for setting the desired temperature, not the displaying of the actual read sensor temperature.

4. Also cosmetically, usually in HA when a climate device is not actually heating it's operation mode shows as 'Idle', while ESPHome climate devices stay in whatever operation mode they are set to (auto or heat) irrespective of whether it's heating or not. 

**Problem-relevant YAML-configuration entries:**
```yaml
climate:
  - platform: bang_bang
    sensor: dht_temperature
    name: Our Heater
    visual:
      min_temperature: 14
      max_temperature: 26
      temperature_step: 0.5
    default_target_temperature_low: 16
    default_target_temperature_high: 26
    away_config:
      default_target_temperature_low: 14
      default_target_temperature_high: 26
    heat_action:
    - switch.turn_on: relay
    idle_action:
    - switch.turn_off: relay

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
