### ISSUE TITLE
supplemental cooling/heating

### ISSUE THREAD

**Issue by 1iverea9er** [esphome/issues#4063]
### The problem

The problem is that `supplemental_heating_action` and `supplemental_cooling_action` are launched without taking into account the temperature difference defined by the `supplemental_cooling_delta` and `supplemental_heating_delta` parameters. That is (in my case), respectively, at temperatures of 24.7 and 25.3 C. Although it should, according to the documentation, at temperatures of 24.3 and 25.7, respectively.

### Which version of ESPHome has the issue?

2022.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.7

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

Climate

### Example YAML snippet

```yaml
climate:
  - platform: thermostat
    id: my_climate
    name: "TRV EXP"
    sensor: heatindex
    visual:
      min_temperature: 18
      max_temperature: 27
      temperature_step: 0.1
    min_cooling_off_time: 3s
    min_cooling_run_time: 3s
    min_heating_off_time: 3s
    min_heating_run_time: 3s
    max_cooling_run_time: 3s
    max_heating_run_time: 3s
    min_idle_time: 3s
    set_point_minimum_differential: 0.2 °C
    supplemental_cooling_delta: 0.3 °C
    supplemental_heating_delta: 0.3 °C
    cool_deadband: 0.0 °C
    cool_overrun: 0.0 °C
    heat_deadband: 0.0 °C
    heat_overrun: 0.0 °C
    cool_action:
      - if:
          condition:
            lambda: 'return id(ada);'
          then:
            - switch.turn_on: cooling
    supplemental_cooling_action:
      - script.execute: full_close
    heat_action:
      - if:
          condition:
            lambda: 'return id(ada);'
          then:
            - switch.turn_on: heating
    supplemental_heating_action:
      - script.execute: full_open
    idle_action:
      - switch.turn_off: cooling
      - switch.turn_off: heating
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 24.8 °C
        default_target_temperature_high: 25.2 °C
        mode: heat_cool
```
