### ISSUE TITLE
Compile error of hx711 in combination with esp-idf

### ISSUE THREAD

**Issue by earlyhost** [esphome/issues#4064]
### The problem

Using hx711 on an esp32 with esp-idf causes an error during compiling. the same yaml configuration with Arduino does work. 

### Which version of ESPHome has the issue?

2022.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.7

### What platform are you using?

ESP32-IDF

### Board

wemos_d1_mini32

### Component causing the issue

hx711

### Example YAML snippet

```yaml
esphome:
  name: "gate"

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: recommended

sensor:
  - platform: hx711
    id: hx711_value
    internal: true
    dout_pin: GPIO19
    clk_pin: GPIO18
    gain: 128
    update_interval: 120s
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/gate.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing gate (board: wemos_d1_mini32; framework: espidf; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40402.0 (4.4.2) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling /data/gate/.pioenvs/gate/src/main.o
Linking /data/gate/.pioenvs/gate/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/gate/.pioenvs/gate/src/main.o:(.literal._Z5setupv+0x2c0): undefined reference to `vtable for esphome::hx711::HX711Sensor'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/gate/.pioenvs/gate/src/main.o:(.literal._Z5setupv+0x2c4): undefined reference to `vtable for esphome::hx711::HX711Sensor'
collect2: error: ld returned 1 exit status
*** [/data/gate/.pioenvs/gate/firmware.elf] Error 1
========================= [FAILED] Took 101.36 seconds =========================
```
