### ISSUE TITLE
Documentation bug for "ST7789V TFT LCD"

### ISSUE THREAD

**Issue by bwims** [esphome/issues#4065]
### The problem

I recently obtained a TTGO ESP32 with display and thought it an ideal way to get started with ESPHome.

The problem is that the [documentation ](https://esphome.io/components/display/st7789v.html)for the device starts off with a simple example with an error in it.

The minimal config entry does not work:
```
# Example minimal configuration entry
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    model: TTGO TDisplay 135x240
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    lambda: |-
      it.print(0, 0, id(font), "Hello World!");

```

It throws this error:

`  Couldn't find ID 'font'. Please check you have defined an ID with that name in your configuration.
`

Would it be possible to provide a minimal configuration that works for this web page?

### Which version of ESPHome has the issue?

2022.11.5

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

Documentation

### Example YAML snippet

```yaml
See documentation web page extract abovt.
```
