### ISSUE TITLE
sprinkler.queue_valve fails without run_duration

### ISSUE THREAD

**Issue by benbkoch** [esphome/issues#4069]
### The problem

The docs state "If run_duration is not specified or is zero, the sprinkler controller will use the valve’s configured run duration" however if a run_duration is not specified, it generates the following error `Don't know what '0' means as it has no time *unit*! Did you mean '0s'?.`

### Which version of ESPHome has the issue?

stable

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
- seconds: 0
      minutes: 0
      hours: 5
      days_of_week: SUN
      then:
        - sprinkler.queue_valve:
            id: backyard_sprinklers
            valve_number: 1
```
