### ISSUE TITLE
ESP32s3 BT proxy + tracker Config bootloops on arduino, no boot on esp-idf

### ISSUE THREAD

**Issue by evlo** [esphome/issues#4072]
### The problem

With the yaml bellow, I cannot get module to boot or even compile

### Which version of ESPHome has the issue?

2022.12.6

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2022.1.7

### What platform are you using?

ESP32

### Board

esp32-s3-devkitc-1 (original)

### Component causing the issue

probably BT proxy

### Example YAML snippet

```yaml
substitutions:
  hostname: eh-btproxy-02
  device_id: eh_btproxy_02
  device_name: eh-btproxy-02
  comment: AC BT Proxy 02, ESP32s3

esphome:
  name: ${hostname}
  comment: ${comment}

esp32:
  variant: ESP32S3
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
logger:
  level: VERBOSE

web_server:
api:
ota:  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${hostname} Fallback"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
  on_ble_advertise:
    - then:
        - lambda: |-
            ESP_LOGD("ble_adv", "New BLE device");
            ESP_LOGD("ble_adv", "  address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  name: %s", x.get_name().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
                ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
            ESP_LOGD("ble_adv", "  Advertised service data:");
            for (auto data : x.get_service_datas()) {
                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
            }
            ESP_LOGD("ble_adv", "  Advertised manufacturer data:");
            for (auto data : x.get_manufacturer_datas()) {
                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
            }
  on_scan_end:
    - then:
        - lambda: |-
              ESP_LOGD("ble_auto", "The scan has ended!");

bluetooth_proxy:
  active: true
```

for esp-idf i added
```yaml
external_components:
  - source: github://pr#3500
    components:
      - web_server
      - web_server_idf
      - web_server_base
      - captive_portal
```

### Anything in the logs that might be useful for us?

arduino bootloop

```txt
[14:32:05]SPIWP:0xee
[14:32:05]Octal Flash Mode Enabled
[14:32:05]For OPI Flash, Use Default Flash Boot Mode
[14:32:05]mode:SLOW_RD, clock div:1
[14:32:05]load:0x3fce3808,len:0x43c
[14:32:05]load:0x403c9700,len:0xbec
[14:32:05]load:0x403cc700,len:0x2a3c
[14:32:05]entry 0x403c98d8
[14:32:05]ESP-ROM:esp32s3-20210327
[14:32:05]Build:Mar 27 2021
[14:32:05]rst:0xc (RTC_SW_CPU_RST),boot:0x18 (SPI_FAST_FLASH_BOOT)
[14:32:05]Saved PC:0x40377474
WARNING Decoded 0x40377474: esp_restart_noos at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/port/soc/esp32s3/system_internal.c:143 (discriminator 1)
```

***

esp-idf

```txt
c:/users/vladimir/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pioenvs/eh-btproxy-02/src/esphome/components/esp32_ble_client/ble_client_base.o:(.literal._ZN7esphome16esp32_ble_client13BLEClientBase7connectEv+0x8): undefined reference to `esp_ble_gattc_open'
c:/users/vladimir/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pioenvs/eh-btproxy-02/src/esphome/components/esp32_ble_client/ble_client_base.o: in function `esphome::esp32_ble_client::BLEClientBase::connect()':
C:\esphome\.esphome\build\eh-btproxy-02/src/esphome/components/esp32_ble_client/ble_client_base.cpp:65: undefined reference to `esp_ble_gattc_open'
c:/users/vladimir/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pioenvs/eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o:(.literal._ZN7esphome17esp32_ble_tracker15ESP32BLETracker9stop_scanEv+0x8): undefined reference to `esp_ble_gap_stop_scanning'
c:/users/vladimir/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pioenvs/eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o:(.literal._ZN7esphome17esp32_ble_tracker15ESP32BLETracker11start_scan_Eb+0x10): undefined reference to `esp_ble_gap_set_scan_params'
c:/users/vladimir/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pioenvs/eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o:(.literal._ZN7esphome17esp32_ble_tracker15ESP32BLETracker11start_scan_Eb+0x14): undefined reference to `esp_ble_gap_start_scanning'
c:/users/vladimir/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pioenvs/eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o: in function `esphome::esp32_ble_tracker::ESP32BLETracker::stop_scan()':
C:\esphome\.esphome\build\eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp:236: undefined reference to `esp_ble_gap_stop_scanning'
c:/users/vladimir/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pioenvs/eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o: in function `esphome::esp32_ble_tracker::ESP32BLETracker::start_scan_(bool)':
C:\esphome\.esphome\build\eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp:338: undefined reference to `esp_ble_gap_set_scan_params'
c:/users/vladimir/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\esphome\.esphome\build\eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp:341: undefined reference to `esp_ble_gap_start_scanning'
c:/users/vladimir/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pioenvs/eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o: in function `esphome::esp32_ble_tracker::ESP32BLETracker::loop()':
C:\esphome\.esphome\build\eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp:170: undefined reference to `esp_ble_gap_stop_scanning'
c:/users/vladimir/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\esphome\.esphome\build\eh-btproxy-02/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp:187: undefined reference to `esp_ble_gap_stop_scanning'
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\eh-btproxy-02\firmware.elf] Error 1
```

Also on upload I do get warnings
```
Warning: Image file at 0x0 is protected with a hash checksum, so not changing the flash size setting. Use the --flash_size=keep option instead of --flash_size=32MB in order to remove this warning, or use the --dont-append-digest option for the elf2image command in order to generate an image file without a hash checksum

WARNING: Flasher stub doesn't fully support flash size larger than 16MB, in case of failure use --no-stub.
```

full upload log
```
esptool.py v4.4
Serial port COM9
Connecting...
Chip is ESP32-S3 (revision v0.1)
Features: WiFi, BLE
Crystal is 40MHz
MAC: 68:b6:b3:3c:d5:7c
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 32MB
WARNING: Flasher stub doesn't fully support flash size larger than 16MB, in case of failure use --no-stub.
Flash will be erased from 0x00010000 to 0x0014afff...
Flash will be erased from 0x00000000 to 0x00003fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Compressed 1286368 bytes to 825941...
Wrote 1286368 bytes (825941 compressed) at 0x00010000 in 6.8 seconds (effective 1510.3 kbit/s)...
Hash of data verified.
Warning: Image file at 0x0 is protected with a hash checksum, so not changing the flash size setting. Use the --flash_size=keep option instead of --flash_size=32MB in order to remove this warning, or use the --dont-append-digest option for the elf2image command in order to generate an image file without a hash checksum
Compressed 15040 bytes to 10362...
Wrote 15040 bytes (10362 compressed) at 0x00000000 in 0.1 seconds (effective 817.5 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 144...
Wrote 3072 bytes (144 compressed) at 0x00008000 in 0.0 seconds (effective 651.1 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 1085.2 kbit/s)...
Hash of data verified.
```

Then I tried 
```ps1
esptool.exe write_flash 0 "C:\esphome\.esphome\build\eh-btproxy-02\.pioenvs\eh-btproxy-02\firmware.bin"
esptool.exe --no-stub write_flash 0 "C:\esphome\.esphome\build\eh-btproxy-02\.pioenvs\eh-btproxy-02\firmware.bin"
```
I get no warnings, but it still does not boot
```ps1
PS C:\esphome> esphome logs .\eh-btproxy-eps32s3-devkitC.yaml --device COM9
INFO Reading configuration .\eh-btproxy-eps32s3-devkitC.yaml...
INFO Starting log output from COM9 with baud rate 115200
[16:20:34]load:0x3fc955c0,len:0x4e08
[16:20:34]load:0x40374000,len:0x6c80
[16:20:34]load:0x42000020,len:0xfa2f8
[16:20:35]load:0x4037ac80,len:0xa93c
[16:20:35]load:0x50000000,len:0x10
[16:20:35]SHA-256 comparison failed:
[16:20:35]Calculated: b2372ceacb0e4a6afc7780137ca6a6061b34317b61e8c908f63b5c2daa340303
[16:20:35]Expected: 9c2439af2c53d5cc81e174a51a27dab15489f766fd1fcfae822c44e6d197b491
[16:20:35]Attempting to boot anyway...
[16:20:35]entry 0x40376fc8
[16:20:35]ESP-ROM:esp32s3-20210327
[16:20:35]Build:Mar 27 2021
[16:20:35]rst:0x7 (TG0WDT_SYS_RST),boot:0x18 (SPI_FAST_FLASH_BOOT)
[16:20:35]Saved PC:0x4037a278
WARNING Decoded 0x4037a278: _xt_panic at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/port/arch/xtensa/panic_handler_asm.S:28
[16:20:36]SPIWP:0xee
[16:20:36]Octal Flash Mode Enabled
[16:20:36]For OPI Flash, Use Default Flash Boot Mode
[16:20:36]mode:SLOW_RD, clock div:1
[16:20:36]load:0x3c100020,len:0x34560
[16:20:36]load:0x3fc955c0,len:0x4e08
[16:20:36]
ERROR Serial port closed!
```

I have tried building in esphome dashboard running as HA addon on HA yellow and result is the same
