### ISSUE TITLE
When using serveral AC_dimmer with, speed fan selection is no more working

### ISSUE THREAD

**Issue by SeByDocKy** [esphome/issues#4074]
### The problem

I got a mode where two ac_dimmer (classic robodyn) are defined to control a fan and water pump speed. In fact, when I am defining only one of the two, everything is working fine but as soon as I am defining both ac_dimmer and fan, the speed selection is not working correctly. Now it's behaving like a switch : at 0% it's off, at 100% it's fully turned on but any other intermediate value are not working

### Which version of ESPHome has the issue?

ESPHome version 2023.1.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.7

### What platform are you using?

ESP32

### Board

ESP32u (ESP32 WROOM32 with an external antenna

### Component causing the issue

ac_dimmer, fan

### Example YAML snippet

```yaml
substitutions:
  updates: 10s

esp32:
  board: esp32dev
  framework:
    # type: esp-idf
    type: arduino
    version: 2.0.6
    platform_version: 5.3.0   

esphome:
  name: ${name}    
    

logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
 
wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Geothermie Fallback Hotspot"
    password: "sebydocky"    

output:    
  - platform: ac_dimmer
    id: ${name}_dimmer_fan
    gate_pin: GPIO18
    zero_cross_pin:
      number: GPIO17
      mode: INPUT
      inverted: yes

  - platform: ac_dimmer
    id: ${name}_dimmer_circulateur_ac
    gate_pin: GPIO25
    zero_cross_pin:
      number: GPIO26
      mode: INPUT
      inverted: yes    

fan:
  - platform: speed
    output: ${name}_dimmer_fan
    id: ${name}_fan
    name: ${name}_soufflerie
  
  - platform: speed
    output: ${name}_dimmer_circulateur_ac
    id: ${name}_circulateur_ac
    name: ${name}_circulateur_ac

number:
  - platform: template
    name: ${name}_fan_number
    id: ${name}_fan_number
    optimistic: true
    initial_value: 0
    unit_of_measurement: '%'
    icon: mdi:fan
    min_value: 0
    max_value: 100
    step: 1
    mode: 'slider'
    on_value:
       then:
          - if: 
              condition:
                -  lambda: |-
                    return id(${name}_fan_number).state != 0;
              then:            
                - fan.turn_on:
                   id: ${name}_fan
                   speed: !lambda |-
                    return id(${name}_fan_number).state;
              else:
                - fan.turn_off: ${name}_fan


  - platform: template
    name: ${name}_circulateur_ac_number
    id: ${name}_circulateur_ac_number
    optimistic: true
    initial_value: 0
    unit_of_measurement: '%'
    icon: mdi:fan
    min_value: 0
    max_value: 100
    step: 1
    mode: 'slider'
    on_value:
       then:
          - if: 
              condition:
                -  lambda: |-
                    return id(${name}_circulateur_ac_number).state != 0;
              then:            
                - fan.turn_on:
                   id: ${name}_circulateur_ac
                   speed: !lambda |-
                    return id(${name}_circulateur_ac_number).state;
              else:
                - fan.turn_off: ${name}_circulateur_ac
```
