### ISSUE TITLE
Template cover not updating state in frontend

### ISSUE THREAD

**Issue by dieselrabbit** [esphome/issues#408]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io in docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff SV

**Affected component:**

https://esphome.io/components/cover/template.html

**Description of problem:**
The template cover entity is not updating is state in the Home Assistant frontend. The switch part of the template cover works, and the gpio binary_sensor updates its status just fine, but after opening and closing the cover, the cover entity in hass.io is stuck at 'closing', even after the binary_sensor updates to 'off'

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: big_garage_door_sonoff
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: '****'
  password: '****'

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: '****'

ota:
  password: '****'
  
status_led:
  pin:
    number: 13
    inverted: True

switch:
  - platform: gpio
    name: "Big Garage Door"
    pin: 12
    id: button
    
binary_sensor:
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: True
    name: "Big Garage Door"
    device_class: garage_door
    id: sensor

cover:
  - platform: template
    name: "Big Garage Door"
    device_class: garage
    lambda: |-
      if (id(sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }    
    open_action:
      - switch.turn_off: button
      - switch.turn_on: button
      - delay: 0.2s
      - switch.turn_off: button
    close_action:
      - switch.turn_off: button
      - switch.turn_on: button
      - delay: 0.2s
      - switch.turn_off: button
    stop_action:
      - switch.turn_off: button
      - switch.turn_on: button
      - delay: 0.2s
      - switch.turn_off: button
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
