### ISSUE TITLE
Tool Chain Error

### ISSUE THREAD

**Issue by arkansas-coder** [esphome/issues#4084]
### The problem

There appears to be a spelling error in the tool chain. Instead of `charset_normalizer` it has `~charset_normalizer`. See the log smippet below.

### Which version of ESPHome has the issue?

2022.12.6

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp32-C3-Dev1

### Example YAML snippet

```yaml
esphome:
  name: esp2

esp32:
  board: esp32dev
  variant: esp32C3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
    password: "xxxxxx"

ota:
    password: "xxxxxx"

wifi:
  ssid: "yyyyy"
    password: "xxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp2 Fallback Hotspot"
    password: "xxxxxx"
```

### Anything in the logs that might be useful for us?

```txt
Building wheels for collected packages: future
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492055 sha256=fab9217925f929a3c766fe3a672a71c8f0ba24fc9ce260efb01fa1722f596964
  Stored in directory: c:\users\uuuuu\appdata\local\pip\cache\wheels\83\31\5a\7539ed9c6ac3249781de831638629a4fe503168023e1a777e2
Successfully built future
Installing collected packages: pyparsing, msgpack, lockfile, charset-normalizer, urllib3, six, pyyaml, pycparser, packaging, idna, future, contextlib2, colorama, certifi, tqdm, schema, requests, click, cffi, requests-toolbelt, requests-file, cryptography, cachecontrol, idf-component-manager
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.0.1
    Uninstalling charset-normalizer-3.0.1:
      Successfully uninstalled charset-normalizer-3.0.1
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\uuuuu\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\~harset_normalizer\\md.cp311-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

*** Error 1
```

### Additional information

This is the first time I am trying to build firmware using ESPHome.
