### ISSUE TITLE
Shelly dimmer device class

### ISSUE THREAD

**Issue by sanderlv** [esphome/issues#4086]
### The problem

Hi all, for my shelly dimmer I use the default config: https://esphome.io/components/light/shelly_dimmer.html 

Since a while I now get: 
`Entity sensor.shelly_2_dimmer_01_current (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'A' which is not a valid unit for the device class ('power') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22.` 

For now I corrected it with":

device_class: "current"

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.7

### What platform are you using?

ESP8266

### Board

Shelly Dimmer

### Component causing the issue

shelly dimmer

### Example YAML snippet

```yaml
light:
  - platform: shelly_dimmer
    name: "${device_name}"
    id: dimmer
    icon: mdi:globe-light-outline
    power:
      name: "${device_name} Power"
      id: power_dimmer
    voltage:
      name: "${device_name} Voltage"
    current:
      name: "${device_name} Current"
      device_class: "current"
```

### Anything in the logs that might be useful for us?

```txt
Entity sensor.shelly_2_dimmer_01_current (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'A' which is not a valid unit for the device class ('power') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
```
