### ISSUE TITLE
I2S audio not working after update ESPhome firmware

### ISSUE THREAD

**Issue by Manhem** [esphome/issues#4088]
### The problem

After I update ESPhome firmware I lost the opportunity to use my Mediaplayer I build my own.
It's a ESP32 with UDA1443 using I2S.
The description I found at your place.

I can see the WiFi level.
But if I try to play a file, it starts and directly closes.
I have installed Music Assistant and here I can't find the player.
Home Assistants Media can find it but I can't play anything.
If I take a closer look the player is idle all the time.

Maybe I have put in the wrong board, but I have tried some different ones with the same result.
The old one I used was not working so I also try others.

What am I doing wrong or maybe a bug..

You can find a picture over my board down here.

### Which version of ESPHome has the issue?

2022.12.xx

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.xx

### What platform are you using?

ESP32

### Board

ESP32

### Component causing the issue

I2S ??

### Example YAML snippet

```yaml
substitutions:
  devicename: "mediaplayer-1"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
#  wifi_domain: !secret wifi_domain
#  api_password: !secret src/api_password
#  ota_password: !secret src/ota_password

esphome:
  name: ${devicename}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: "SP48vTwHlVxH4/gTVZd+YD4Q2euRBv7ND59+2bIRVfM="

ota:
  password: "31f579f71d90cf86945feb3b3aa678a5"
#  password: "08c3e7ca9a3440d528798b200e1e6081"


wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  fast_connect: true

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.33
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.253
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mediaplayer-1 Fallback Hotspot"
    password: "oGrIyPQJ692v"

captive_portal:

# Example configuration entry
media_player:
  - platform: i2s_audio
    name: Media Player
    dac_type: external
    i2s_lrclk_pin: GPIO33
    i2s_dout_pin: GPIO22
    i2s_bclk_pin: GPIO19
    mode: mono

sensor:
  - platform: wifi_signal
    name: "${devicename} Wi-Fi Signal"
    update_interval: 60s

text_sensor:
  - platform: version
    name: "${devicename} ESPhome version"
```

### Anything in the logs that might be useful for us?

```txt
Media Player changed to Idle triggered by service media_player.play_media
10:10:19 AM - 3 seconds ago - xxxxx
Media Player changed to Playing triggered by service media_player.play_media
```

### Additional information

![ESP32](https://user-images.githubusercontent.com/76493147/215051137-7ebb18bb-08e7-4ae6-87de-c321340cfd8d.png)
