### ISSUE TITLE
Home Assistant is asking me to update to ESPhome 2022.12.4 but docker stable is only at 2022.12.3

### ISSUE THREAD

**Issue by jmlc11** [esphome/issues#4089]
### The problem

Home assistant:
![image](https://user-images.githubusercontent.com/6006781/215125784-aa57cfb4-5631-4f31-b65a-a835f4fd7007.png)
ESPhome:
![image](https://user-images.githubusercontent.com/6006781/215125909-99179b40-83cb-475b-b147-2c7741d53077.png)
In docker compose:
![image](https://user-images.githubusercontent.com/6006781/215126787-b68a9861-93e2-4605-b468-dd9f8a307103.png)

### Which version of ESPHome has the issue?

Docker stable (2022.12.3)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.7

### What platform are you using?

ESP8266

### Board

esp-wrover-kit

### Example YAML snippet

```yaml
substitutions:
  name: btproxy
  board: esp-wrover-kit

esphome:
  name: ${name}

esp32:
  board: ${board}
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Livingroomtrack Fallback Hotspot"
    password: !secret password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password

ota:
  password: !secret password

esp32_ble_tracker:

bluetooth_proxy:
  active: True
```
