### ISSUE TITLE
WEMOS S2 mini suddenly no longer possible to upload over  USB

### ISSUE THREAD

**Issue by ferreto1978** [esphome/issues#4090]
### The problem

Begin January 2023 I uploaded 5 new WEMOS S2 mini boards (Lolin v1) using ESPHome over USB via the "manual" mode. That alml worked fine, as long as I put the board in boot mode (pressing the boot button on startup).
But suddenly, one day that didn't wan't to work anymore. I tried this on several different boards, on 3 different PC's and with 2 differnt browsers (Chrome and Brave). The strange part is that the previously configured boards can still be updated over WiFi, but not over USB. Even when re-installing the drivers, no luck.
Using the WEMOS D1 mini, that still works, and even older ESP32 and ESP8266 modules using various USB 2 serial drivers all turn out te be successfull.
It seems to still talk to the WEMOS S2 mini in some way though, because if I don't start it in the correct mode, it automatically resets it to the right mode (noticed this when I suddenly released the COM port changed). So up to that part it still seems to do "something".
With the Arduino IDE, I can upload any code to any of those boards, so the boards themselves seem to be working fine.
Browsing through the forums I learned about the ESPHome-Flasher (v1.4.0) but even that generates an error.
Clearly something was broken in an update specifically for the WEMOS S2 mini boards.

### Which version of ESPHome has the issue?

Latest version (since 23nd half january 2023)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Several version tried, all same result

### What platform are you using?

ESP32

### Board

WEMOS S2 mini

### Component causing the issue

ESPHome web ; ESPHome Flasher

### Example YAML snippet

```yaml
esphome:
  name: test-wemoss2mini

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  password: "***"

wifi:
  ssid: ***
  password: ***

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "***"
    password: "***"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
Not sure how to get to those logs, but using the ESPHome-Flasher, this is the output:
Using 'COM3' as serial port.
Connecting...
Unexpected error: Cannot configure port, something went wrong. Original message: PermissionError(13, 'A device attached to the system is not functioning.', None, 31)
```

### Additional information

With the Arduino IDE, I can upload any code to any of those boards, so the boards themselves and the drivers seem to be working fine.

**Comment by ferreto1978** [comment]
A few updates later, still issues with the Wemos S2 mini

**Comment by ferreto1978** [comment]
March 23, again a few updates later, still issues with the Wemos S2 mini.
Doen anyone else have this issue?

**Comment by nielsnl68** [comment]
I have the same board's and uploading local via USB.
What i see is that it tries first on high speed and false ad and then on a lower speed and that works.
I would suggest to set:
```yaml
# Example configuration entry
esphome:
  # ...
  platformio_options:
    upload_speed: 115200
```
and see of that will fix your issue.
