### ISSUE TITLE
DHT22/AM2302 Sensor Stopped after EspHome Update to 2022.12.8

### ISSUE THREAD

**Issue by gregoinc** [esphome/issues#4093]
### The problem

I have a Sonoff TH10 that has been running with no issues. After updating to EspHome 2022.12.8 the AM2302 (DHT22) has stopped working, and now shows this error in the logs.

`[22:07:21][W][dht:169]: Requesting data from DHT failed!
[22:07:21][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number).
[22:07:21][D][sensor:126]: 'Sonoff Outside Temperature': Sending state nan °C with 1 decimals of accuracy
[22:07:21][D][sensor:126]: 'Sonoff Outside Humidity': Sending state nan % with 0 decimals of accuracy`

Nothing else was changed. The EspHome 2022.12.8 update was installed, and then the new code pushed to the Sonoff. After that the errors began displaying. The Sonoff was power cycled and error remained.

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.7

### What platform are you using?

ESP8266

### Board

Sonoff TH10

### Component causing the issue

AM2302 Temperature Sensor

### Example YAML snippet

```yaml
sensor:
  - platform: dht
    model: am2302
    pin: GPIO14
    temperature:
      name: "Sonoff Outside Temperature"
    humidity:
      name: "Sonoff Outside Humidity"
    update_interval: 30s
```

### Anything in the logs that might be useful for us?

```txt
[22:07:21][W][dht:169]: Requesting data from DHT failed!
[22:07:21][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number).
[22:07:21][D][sensor:126]: 'Sonoff Outside Temperature': Sending state nan °C with 1 decimals of accuracy
[22:07:21][D][sensor:126]: 'Sonoff Outside Humidity': Sending state nan % with 0 decimals of accuracy
```
