### ISSUE TITLE
ili9341 display is white after updating to version 2022.12.0

### ISSUE THREAD

**Issue by Yaro69PL** [esphome/issues#4098]
### The problem

After updating to version 2012.12.0, the display based on ILI9341 stopped displaying the content and lights up completely white. The method of connecting the LED pin does not matter, i.e. through 3.3 kOhm to 3.3 V or to PWM.

Sorry for my English, I'm translating through a translator.

### Which version of ESPHome has the issue?

ESPHome 2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.01.1

### What platform are you using?

ESP32

### Board

ESP32 WROOM 32

### Component causing the issue

display

### Example YAML snippet

```yaml
display:
  - platform: ili9341
    model: TFT 2.4
    spi_id: spi1
    cs_pin: GPIO16
    dc_pin: GPIO05
    led_pin: GPIO04
    reset_pin: GPIO17
    rotation: 90
    lambda: |-
      it.fill(black);
      it.strftime(160, 10, id(font4), id(blue), TextAlign::TOP_CENTER, "%H:%M:%S", id(sntp_time).now());
      if (id(biuro_temperature).has_state()) {
```
