### ISSUE TITLE
When compiling with manual download for ESP32 you get a "Failed - Forbidden" message. Works fine for ESP8266

### ISSUE THREAD

**Issue by mikejlaurie** [esphome/issues#4102]
### The problem

I generally compile ESPHome projects and download the file "modern format" and then flash using  https://web.esphome.io/

I have previosly compiled for both ESP8266 and ESP32 boards. 

Recently when I compile for an ESP32 board and try download the file I get a "Failed-Forbidden" message. 

![2023-02-01_07-53-24](https://user-images.githubusercontent.com/7610224/215962934-17bc9537-a934-479c-821a-a049c5626a7e.jpg)

For ESP8266 the filename does not include xxx.yaml.bin  don't know if that is related. 

Compiling the same file for an ESP8266 works fine

Below I added the full esphome yaml file

Changing the ESP32 part to this makes it work 
`esp8266:
  board: d1_mini
`

I have experienced this on two differente platforms, HAOS running on a PI4 and HAOS running in a Virtualbox on a windows PC. 

### Which version of ESPHome has the issue?

2022.12.8 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.17

### What platform are you using?

ESP32

### Board

ESP32 Dev Kit, but the problem is the same for all ESP32 variants

### Component causing the issue

Downloading bin file in modern format

### Example YAML snippet

```yaml
esphome:
  name: tester

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YXO6ZPDNSjzNJ76ZccEb3h2/gNgPQAYaJPHJ+vvoEmQ="

ota:
  password: "337b16079861afaa45e7b083b19d23b7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tester Fallback Hotspot"
    password: "o0lDe4y7h14L"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
The logs show a successfull compile

--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- Wire @ 2.0.0
RAM:   [=         ]  12.8% (used 41844 bytes from 327680 bytes)
Flash: [=====     ]  54.1% (used 993393 bytes from 1835008 bytes)
========================= [SUCCESS] Took 6.93 seconds =========================
INFO Successfully compiled program.
```
