### ISSUE TITLE
Timeout on http_request no respected in all case

### ISSUE THREAD

**Issue by zoic21** [esphome/issues#4103]
### The problem

Hello,

I find an issue with http_request timeout, it's no respect in some case : 
- resolution timeout
- firewall port close
- maybe also if remote http server is no started

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

Olimex ESP32-GATEWAY

### Component causing the issue

http_request

### Example YAML snippet

```yaml
substitutions:
  water_max_duration : "2min"
  gas_max_duration : "2min"

esphome:
  name: esp-energy

esp32:
  board: esp32dev
  framework:
    type: arduino

globals:
   - id: water_alert
     type: int
     restore_value: no
     initial_value: '0'
   - id: gas_alert
     type: int
     restore_value: no
     initial_value: '0'

# Enable logging
logger:
  #level : INFO

web_server:
  port: 80
  auth:
   username: admin
   password: !secret web_server_password

ota:
  password: !secret ota_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  use_address: 192.168.1.244
  
mqtt:
  broker: !secret mqtt_ip
  username : !secret mqtt_username
  password : !secret mqtt_password
  
http_request:
  useragent: esphome/device
  timeout: 3s

text_sensor:
  - platform: version
    name: "Firmware control"
    
time:
  - platform: sntp
    servers: !secret ntp_ip
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"

sensor:
 - platform: pulse_meter
   pin:
      number: 13
      mode: INPUT_PULLUP
   id: water
   name: "Instant water consumption"
   unit_of_measurement: "L/min"
   timeout: 60s
   internal_filter: 50ms
   accuracy_decimals: 1
   filters:
    - delta: 0.1
   on_value:
       then:
        - if:
            condition:
              and:
                - lambda: return id(water).state == 0;
                - lambda: return id(water_alert) == 1;
            then:
              - globals.set:
                  id: water_alert
                  value: '0'
              - http_request.post:
                  url: !secret ntfy_url
                  headers:
                    Content-Type: text/plain
                    Tags: warning,droplet
                    Priority: urgent
                    Title: Evenèment
                    Authorization: !secret ntfy_auth
                  json:
                     topic: "loic"
                     message: "Consommation d'eau revenu à la normal"
        - if:
            condition:
              and:
                - lambda: return id(water_alert) == 0;
                - for:
                    time: ${water_max_duration}
                    condition:
                      - lambda: return id(water).state > 0;
            then:
              - globals.set:
                  id: water_alert
                  value: '1'
              - http_request.post:
                  url: !secret ntfy_url
                  headers:
                    Content-Type: text/plain
                    Tags: warning,droplet
                    Priority: urgent
                    Title: Evenèment
                    Authorization: !secret ntfy_auth
                  json:
                     topic: "loic"
                     message: "Consommation d'eau supérieure à 0 L/min pendant plus de  15min"
   total:
    name: "Total water consumption"
    unit_of_measurement: "m³"
    device_class: "water"
    accuracy_decimals: 2
    filters:
    - lambda: return (x * 0.001);
  
 - platform: pulse_meter
   pin:
      number: 14
      mode: INPUT_PULLUP
   id: gas
   name: "Instant gas consumption"
   unit_of_measurement: "L/min"
   timeout: 60s
   internal_filter: 200ms
   accuracy_decimals: 2
   filters:
    - lambda: return (x * 10);
   on_value:
       then:
        - if:
            condition:
              and:
                - lambda: return id(gas).state == 0;
                - lambda: return id(gas_alert) == 1;
            then:
              - globals.set:
                  id: gas_alert
                  value: '0'
              - http_request.post:
                  url: !secret ntfy_url
                  headers:
                    Content-Type: text/plain
                    Tags: warning,droplet
                    Priority: urgent
                    Title: Evenèment
                    Authorization: !secret ntfy_auth
                  json:
                     topic: "loic"
                     message: "Consommation de gaz revenu à la normal"
        - if:
            condition:
              and:
                - lambda: return id(gas_alert) == 0;
                - for:
                    time: ${gas_max_duration}
                    condition:
                      - lambda: return id(gas).state > 0;
            then:
              - globals.set:
                  id: gas_alert
                  value: '1'
              - http_request.post:
                  url: !secret ntfy_url
                  headers:
                    Content-Type: text/plain
                    Tags: warning,fire
                    Priority: urgent
                    Title: Evenèment
                    Authorization: !secret ntfy_auth
                  json:
                     topic: "loic"
                     message: "Consommation de gaz supérieure à 0 L/min pendant plus de  15min"
   total:
    name: "Total gas consumption"
    unit_of_measurement: "m³"
    device_class: "gas"
    accuracy_decimals: 2
    filters:
      - lambda: return (x * 0.01);
```

### Additional information

It's little embarrassing because of this issue #2853, I set timeout to 3s to prevent a reboot of ESP32 but since this timeout it's not respect it's restart my ESP32.

I known it vould be difficult to fix that but if my server is no here (due to security maintenance for exemple) I got a restart of my ESP32 and lost current consumption (since it's restart from 0).
