### ISSUE TITLE
ESP32-S2 - Media player - I2S - distorted audio

### ISSUE THREAD

**Issue by sgofferj** [esphome/issues#4106]
### The problem

I have set up an ESPHome media player with 2 MAX98753 with an ESP32-S2. Playback of either MP3 streams or local files is distorted. The first half second plays OK, then the audio stream is interrupted and sounds somewhat slower. I'm no expert but it sounds like I would imagine dropped frames sound.
An identical configuration on an ESP32 DevKit (without any S's) works perfectly fine.

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.7

### What platform are you using?

ESP32

### Board

esp32-s2-saola-1

### Component causing the issue

i2s

### Example YAML snippet

```yaml
esphome:
  name: player-1

esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret noise_key

ota:
  password: !secret ota-password

wifi:
  ssid: !secret ssid
  password: !secret wifi-password


status_led:
  pin:
    number: GPIO15
    inverted: true

media_player:
  - platform: i2s_audio
    name: Player 1
    id: player1
    dac_type: external
    i2s_lrclk_pin: GPIO33
    i2s_dout_pin: GPIO16
    i2s_bclk_pin: GPIO18
    mode: stereo

sensor:
  - platform: wifi_signal
    name: "Player 1 WiFi RSSI"
    id: player1_wifi_rssi
    update_interval: 60s

  - platform: rotary_encoder
    name: "Player 1 Encoder"
    id: player1_encoder
    min_value: 0
    max_value: 100
    resolution: 4
    publish_initial_value: True
    pin_a:
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
    pin_b:
      number: GPIO11
      inverted: true
      mode:
        input: true
        pullup: true
    on_clockwise:
      - media_player.volume_set:
          id: player1
          volume: !lambda 'return id(player1_encoder).state / 100;'
    on_anticlockwise:
      - media_player.volume_set:
          id: player1
          volume: !lambda 'return id(player1_encoder).state / 100;'


binary_sensor:
  - platform: status
    name: "Player 1 Status"
    id: player1_status
```

### Anything in the logs that might be useful for us?

```txt
nope, all fine in the logs
```
