### ISSUE TITLE
Device reports being offline when using Wifi -> use_address

### ISSUE THREAD

**Issue by svrooij** [esphome/issues#4109]
### The problem

I'm running esphome as a standalone container, it is set to use regular docker networking (no host mode).
I've set the static ip of all the devices with: `wifi` => `use_address: '192.168.x.x'`, this means logs just work, I can update them no problem. The issue I have is that al the devices report being offline in the main dashboard.

### Which version of ESPHome has the issue?

v2022.12.8

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.1

### What platform are you using?

ESP8266

### Component causing the issue

dashboard

### Example YAML snippet

```yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: '192.168.x.x'
  ap:
    ssid: ${device_name}
```

### Additional information

![image](https://user-images.githubusercontent.com/1292510/216280963-5e9b60ac-0c27-437e-ad69-e9ee7f5bf2fe.png)

And if I press the log button it just shows the correct log.
![image](https://user-images.githubusercontent.com/1292510/216281469-bf3cca6a-0ae0-4c02-8d9c-067a35f0f414.png)

Updating also works. So it's just the **online** check in the main dashboard.
