### ISSUE TITLE
AARCH64

### ISSUE THREAD

**Issue by OvCa77** [esphome/issues#411]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASS.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

Complier

**Description of problem:**
Error compiling on AARCH64

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: test
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "a"


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

```

**Traceback (if applicable):**

```
Compiling /data/test/.pioenvs/test/src/esphome/components/api/command_messages.cpp.o
Illegal instruction (core dumped)
*** [/data/test/.pioenvs/test/src/esphome/components/api/api_message.cpp.o] Error 132
Illegal instruction (core dumped)
*** [/data/test/.pioenvs/test/src/esphome/components/api/api_server.cpp.o] Error 132
Illegal instruction (core dumped)
*** [/data/test/.pioenvs/test/src/esphome/components/api/basic_messages.cpp.o] Error 132
Illegal instruction (core dumped)
*** [/data/test/.pioenvs/test/src/esphome/components/api/command_messages.cpp.o] Error 132
========================== [ERROR] Took 9.59 seconds ==========================
```

**Additional information and things you've tried:**
