### ISSUE TITLE
ESPHome device discovery for HAOS Addon not working with packages

### ISSUE THREAD

**Issue by ipetrovits** [esphome/issues#4111]
### The problem

If I put the API: configuration into a package, the HAOS discovery will not be able to read the api key.

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.0

### What platform are you using?

ESP8266

### Board

Sonoff S20

### Component causing the issue

api

### Example YAML snippet

```yaml
Config.yaml content:

packages:
  api: !include .packages/api.yaml

.packages/api.yaml content:

api:
  encryption:
    key: !secret api_key
```

### Additional information

Same behaviour can be observed when I press the device properties, then "Show API key" option. If that can retrieve the key, HA discovery works as well. If not (loading spinning for a long time), HA will be unable either.
