### ISSUE TITLE
Looking for pins_arduino.h dependency?

### ISSUE THREAD

**Issue by DaveTiff** [esphome/issues#4113]
### The problem

Has compiled ok before, just adding the new API Key

Get this error on 2 of my ESP nodes but not on all of them

/data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:29:10: fatal error: pins_arduino.h: No such file or directory

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.1

### What platform are you using?

ESP8266

### Board

nodemcu-32s

### Example YAML snippet

```yaml
esphome:
  name: office_curtains
  platform: ESP32
  board: nodemcu-32s
  
  on_boot:
    priority: 600
    # ...
    then:
    - delay: 1000ms 
    - switch.turn_off: blutooth_on_off

sensor:

  - platform: adc
    pin: A0
    attenuation: 11db
    name: "TEMT6000 Illuminance"
    device_class: illuminance
    unit_of_measurement: lx
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
    update_interval: 60s          

  - platform: wifi_signal
    name: "WiFi Sig - Office Curtains"
    update_interval: 60s   
    
    

  - platform: am43
    ble_client_id: office_am43
    battery_level:
      name: "Office Curtains battery"   
    illuminance:
      name: "Office Curtain light"
    update_interval: 60s      
     
      


esp32_ble_tracker:

ble_client:
  - mac_address: 02:08:E8:B8:24:93
    id: office_am43

cover:
  - platform: am43
    name: "Office Curtains"
    id: office_cover
    ble_client_id: office_am43

switch:
  - platform: ble_client
    id: blutooth_on_off
    name: "Office Curtains"

    
    ble_client_id: office_am43

button:    
  - platform: restart
    name: "Reboot Office Curtains"
```
