### ISSUE TITLE
Shelly Plus 1 4-Way Handshake Timeout

### ISSUE THREAD

**Issue by Faysho** [esphome/issues#4115]
### The problem

# Situation:
I just set up Home Assistant on my RPi 3B and wanted to add a Shelly Plus 1. I used the original yaml from the esphome website but removed the api password due to its deprecated status.
# The problem:
Its doesn't connect to my WiFi. I already checked the serial logs and it states "Event: Disconnected [...] reason='4-Way Handshake Timeout'".
# What I already tried:
- restarting the router -> no change
- assigning an static IP -> no change

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.1

### What platform are you using?

ESP32

### Board

Shelly Plus 1

### Component causing the issue

Wifi

### Example YAML snippet

```yaml
substitutions:
  device_name: "Shelly Plus 1"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

esphome:
  name: shelly-plus-1
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:
  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO26

switch:
  - platform: output
    id: "relay"
    name: "${device_name} Relay"
    output: "relay_output"

binary_sensor:
  - platform: gpio
    name: "${device_name} Switch"
    pin: GPIO4
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "${device_name} Button"
    pin:
      number: GPIO25
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 5ms

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${device_name} Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: "relay"
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO32
    attenuation: 11db

  - platform: adc
    name: "${device_name} Relay Supply Voltage"
    pin: GPIO33
    attenuation: 11db
    filters:
      - multiply: 8

status_led:
  pin:
    number: GPIO0
    inverted: true
```

### Anything in the logs that might be useful for us?

```txt
# Serial log
<27>[0;33m[W][wifi_esp32:633]: Event: Disconnected ssid='networkname' bssid=AA:AA:AA:AA:AA:AA reason='4-Way Handshake Timeout'
<27>[0;33m[W][wifi:549]: Error while connecting to network.
<27>[0;33m[W][wifi:585]: Restarting WiFi adapter...
```
