### ISSUE TITLE
ethernet_info ip_address error with ESP-IDF

### ISSUE THREAD

**Issue by TheOfficialMrBlah** [esphome/issues#4116]
### The problem

If ip_address from ethernet_info component is used in conjunction with esp-idf, an error occurs during compilation.
esphome/esphome#3811

### Which version of ESPHome has the issue?

2023.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.1

### What platform are you using?

ESP32-IDF

### Board

ESP32 DEV Board

### Component causing the issue

ethernet_info

### Example YAML snippet

```yaml
esphome:
  name: 'test'

esp32:
  board: esp32dev
  framework:
    type: esp-idf

ota:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO5

#network:
#    enable_ipv6: true

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: 'IP-Adresse'
```

### Anything in the logs that might be useful for us?

```txt
src/main.cpp:13:1: error: 'ethernet_info' does not name a type
 ethernet_info::IPAddressEthernetInfo *ethernet_info_ipaddressethernetinfo;
 ^~~~~~~~~~~~~
src/main.cpp: In function 'void setup()':
src/main.cpp:93:3: error: 'ethernet_info_ipaddressethernetinfo' was not declared in this scope
   ethernet_info_ipaddressethernetinfo = new ethernet_info::IPAddressEthernetInfo();
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:93:45: error: 'ethernet_info' does not name a type
   ethernet_info_ipaddressethernetinfo = new ethernet_info::IPAddressEthernetInfo();
                                             ^~~~~~~~~~~~~
Compiling /data/test/.pioenvs/test/asio/asio/asio/src/asio.o
*** [/data/test/.pioenvs/test/src/main.o] Error 1
========================= [FAILED] Took 31.31 seconds =========================
```

### Additional information

The Arduino framework works with the same configuration.
