### ISSUE TITLE
esptool write_flash: error: ... [Errno 2] No such file

### ISSUE THREAD

**Issue by vespadj** [esphome/issues#4117]
### The problem

```
[1] /dev/ttyUSB0 (CP2102 USB to UART Bridge Controller - CP2102 USB to UART Bridge Controller)
...
esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: '/home/vespadj/Documents/esphome_cfg/.esphome/build/livingroom/.pioenvs/livingroom/firmware.bin'

```
But file exists!

standard command:
```
cd; cd Documents/esphome_cfg;
docker run --rm -v "${PWD}":/config --device=/dev/ttyUSB0 -it esphome/esphome run livingroom.yaml

```
Via manual install via python, permission is denied on ttyUSB0.

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

**Comment by vespadj** [comment]
Re-do from zero with docker wizard, finally works.
I don't understand why...

OLD code, used in my many project:
```yaml
esphome:
  name: mydevice
  platform: ESP32
  board: esp32dev
  platformio_options: 
    platform: espressif32
    board: az-delivery-devkit-v4
    board_build.mcu: esp32
    board_build.f_cpu: 240000000L
```

NEW code:
```yaml
esphome:
  name: mydevice

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino
```
