### ISSUE TITLE
Wifi power save mode ignored after restart

### ISSUE THREAD

**Issue by elpedriyo** [esphome/issues#4118]
### The problem

Hello,

I am currently using  power_save_mode: none and I can see that the latency to the device reduces a lot. However after I restart the esp32, I notice how latency increases again. It continues like if it was as default, until I reflash the esp32 again.

You can see in here what was the latency after flashing the device with power_save_mode: none and after rebooting it
![image](https://user-images.githubusercontent.com/3207791/216734726-826e0e4f-d038-4a78-b44f-37a9de2063f6.png)

Kind regards

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

D1 mini

### Example YAML snippet

```yaml
esphome:
  name: livingroom  

# Example configuration entry
#dallas:
#  - pin: 16
#    update_interval: 2s
#  
#sensor:
#  - platform: dallas
#    address: 0xf30300a27931d028
#    name: "Temperature #1"
#  - platform: dallas
#    address: 0x7e0300a279319b28
#    name: "Temperature #2"
#  - platform: dallas
#    address: 0x080300a279c3c728
#    name: "Temperature #3"
switch:
#  - platform: gpio
#    name: "Luz led"
#    pin: 27
  - platform: gpio
    name: "Luz chip"
    pin: 2
esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino
  

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "trasto686"

ota:
  password: "trasto686"

wifi:
  ssid: "Amazonas"
  password: "******"
  power_save_mode: none
  output_power: 20dB
  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Livingroom Fallback Hotspot"
#    password: "XBt6aW0J9JGf"
#
#captive_portal:
#
```

**Comment by elpedriyo** [comment]
I have tried setting power save off in arduino ide on my esp32, and the setting persists after reboot without any issue, with expected latency levels. So I guess it is an issue on how esphome sets up the power saving setting

**Comment by ssieb** [comment]
Add this to your config:
```yaml
sensor:
  - platform: template
    name: wifi ps mode
    lambda: |-
      wifi_ps_type_t ps_type;
      esp_err_t err = esp_wifi_get_ps(&ps_type);
      ESP_LOGD("wifi_test", "get_ps returned %d", err);
      return ps_type;
```
See what is in the log and sensor value.

**Comment by elpedriyo** [comment]
This is what the log shows:
`[C][template.sensor:023]: Template Sensor 'wifi ps mode'
[C][template.sensor:023]:   State Class: ''
[C][template.sensor:023]:   Unit of Measurement: ''
[C][template.sensor:023]:   Accuracy Decimals: 1
[C][template.sensor:024]:   Update Interval: 60.0s`

**Comment by elpedriyo** [comment]
I have reflashed esp with your code and this is the report after flashing:
[V][sensor:076]: 'wifi ps mode': Received new state 0.000000
[D][sensor:127]: 'wifi ps mode': Sending state 0.00000  with 1 decimals of accuracy

And this other one after rebooting:
[V][sensor:076]: 'wifi ps mode': Received new state 1.000000
[D][sensor:127]: 'wifi ps mode': Sending state 1.00000 with 1 decimals of accuracy

**Comment by jesserockz** [comment]
Can you set the logger to `VERBOSE`
Check for this message during startup
```c++
    if (!this->wifi_apply_power_save_()) {
      ESP_LOGV(TAG, "Setting Power Save Option failed!");
    }
```

**Comment by elpedriyo** [comment]
I already have VERBOSE logger AFAIK: https://pastebin.com/xLt3THU9
But I can not find that message 
This is my currently yaml file: https://pastebin.com/wnY9jti1

**Comment by ssieb** [comment]
You will only see that from serial logs if you watch from boot.

**Comment by elpedriyo** [comment]
The logs I have pasted in there were taken from serial

**Comment by elpedriyo** [comment]
Here you have full log after OTA flashing, and reboot via reset button: https://pastebin.com/aFYiaUuA

**Comment by elpedriyo** [comment]
Just tried very verbose, and not showing either https://pastebin.com/eei1CFcV

**Comment by ssieb** [comment]
> The logs I have pasted in there were taken from serial

Sorry, I should have checked first.  Try this:
```yaml
external_components:
  - source: github://ssieb/esphome@wifipower
    components: [ wifi ]
```
Use verbose logging.
