### ISSUE TITLE
Bad package version `1.22.0-97-gc752ad5-5.2.0`

### ISSUE THREAD

**Issue by 0neday** [esphome/issues#4119]
### The problem

log is here
```
Processing yeelight-c900 (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
Configuring toolchain packages from a remote source...
Error! Failed to extract upstream toolchainconfigurations:
Bad package version `1.22.0-97-gc752ad5-5.2.0`
You can disable this feature via the `board_build.arduino.upstream_packages = no` setting in your `platformio.ini` file.
```
my yaml.conf esp32 with one core 
```
esphome:
  name: yeelight
  platformio_options:
    platform_packages:
      - framework-arduinoespressif32 @ https://github.com/pauln/arduino-esp32.git#solo-no-mac-crc/1.0.6

  # avoid loop reboot when enable BLE
  on_loop:
    - lambda: "vTaskDelay(10/portTICK_PERIOD_MS);"

esp32:
  board: esp32dev
```

### Which version of ESPHome has the issue?

v2022.12.8 

### What type of installation are you using?

Docker

### What platform are you using?

ESP32
