### ISSUE TITLE
OTA upgrade stops with connections reset by peer error

### ISSUE THREAD

**Issue by mbrudka** [esphome/issues#4125]
### The problem

Affected device: Sonoff Dual R3 (v2 probably).

esphome was flashed in two steps:
- tasmota using esptool.py and serial flashing
- minimal esphome (attached) upload using tasmota web config

esphome runs sonoff as expected. The relay joins WiFi. The more advanced version than a config below logs correctly and enables to manipulate switches. However, there is no way to upgrade esphome using OTA. The upload of firmware stalls for a while then an error is reported:

<pre>
INFO Uploading .esphome/build/gate/.pioenvs/gate/firmware.bin (955072 bytes)
Uploading: [=                                                           ] 1% 
ERROR Error sending data: [Errno 104] Connection reset by peer
</pre>

esphome logs:
<pre>
[D][sensor:127]: 'WiFi Signal': Sending state -53.00000 dBm with 0 decimals of accuracy
[19:10:54][D][ota:143]: Starting OTA Update from ::FFFF:................
[19:10:54][D][ota:312]: OTA in progress: 0.1%
INFO yard-gate: Error while reading incoming messages: Error while reading data: [Errno 104] Connection reset by peer
INFO yard-gate: Ping Failed: Error while reading data: [Errno 104] Connection reset by peer
INFO Disconnected from ESPHome API for yard-gate
WARNING Disconnected from API
INFO Successfully connected to yard-gate
</pre>

### Which version of ESPHome has the issue?

2022.9.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

ota

### Example YAML snippet

```yaml
# Basic Config
substitutions:
  device_name: gate

captive_portal:

esphome:
  name: ${device_name}

esp32:
  board: esp32dev

wifi:
  ssid: ""
  password: ""
  reboot_timeout: 0s
  # Enable fallback hotspot (captive portal) in case Wi-Fi connection fails
  ap:
    ssid: ""
    password: ""

ota:
  password: ""
logger:
  level: DEBUG
  logs:
    script: ERROR
```
