### ISSUE TITLE
PCF8574 initilization toggles output at boot

### ISSUE THREAD

**Issue by swifty99** [esphome/issues#4127]
### The problem

A similar issue was present a long time ago, and has been fixed. Now it is the opposite way. Any output which is not inverted in the beginning of boot will go on for short time.
For me this triggers relais at boot an may damage devices. Interlocking has probably no effect at this stage.

see: [PCF8574 initilization toggles output at boot (if inversed logic)](https://github.com/esphome/issues/issues/755)

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.4

### What platform are you using?

ESP8266

### Board

d1 mini, not important

### Component causing the issue

PCF8574 

### Example YAML snippet

```yaml
- platform: gpio
    name: "Office Displays Monitor"
    id: "sw_display"
    pin:
      pcf8574: pcf8574_hub
      # Use pin number A4
      number: 3
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode:
        output: true
      inverted: false
```
