### ISSUE TITLE
GPIO05 ADC Not Available on seeed_xiao_esp32c3

### ISSUE THREAD

**Issue by nkgiovannivl** [esphome/issues#4136]
### The problem

Setting GPIO05 is showing "ESP32C3 doesn’t support ADC on this pin." , but the reference pins shows me that GPIO05 it’s available.

![image](https://user-images.githubusercontent.com/48342344/217101466-24cee16f-9ba8-45e1-b673-8616faae4469.png)

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.2

### What platform are you using?

ESP32-IDF

### Board

seeed_xiao_esp32c3

### Component causing the issue

sensor platform: adc

### Example YAML snippet

```yaml
esphome:
  name: clamps-my
  platformio_options:
    board_build.flash_mode: dio  

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: esp-idf

sensor:                                      

  - platform: adc

    pin: GPIO5

    attenuation: auto

    accuracy_decimals: 5

    id: adc_sensor_ct5
```

### Additional information

The GPIO05 should be mapped on VARIANT_ESP32C3?

https://github.com/esphome/esphome/blob/034b47c23a08f9980bdae07bcafbcf22fc43dc2e/esphome/components/adc/sensor.py#L76
