### ISSUE TITLE
ESP32 WiFi No matching network found! When using !secrets

### ISSUE THREAD

**Issue by AussiSG** [esphome/issues#4142]
### The problem

As described in the title trying the use !secrets for my WiFi settings in the yaml code.
Which I also use for a lot of ESP8266 modules
They all connect properly but sadly enough the ESP32 module does not.

Checking the logs through USB gives the following warning:
[W][wifi:455]: No matching network found!

And also shows WiFi networks in it's environment. 

When I use the direct SSID and Password it connects properly.

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.2

### What platform are you using?

ESP32

### Board

esp-wrover-kit ( TTGO Camera V1.6.2. )

### Example YAML snippet

```yaml
esphome:
  name: doorbell-camera

esp32:
  board: esp-wrover-kit


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Doorbell-Camera Fallback Hotspot"
    password: "-"

captive_portal:

esp32_camera:
  external_clock:
    pin: GPIO4
    frequency: 20MHz
  i2c_pins:
    sda: GPIO18
    scl: GPIO23
  data_pins: [GPIO34, GPIO13, GPIO14, GPIO35, GPIO39, GPIO38, GPIO37, GPIO36]
  vsync_pin: GPIO5
  href_pin: GPIO27
  pixel_clock_pin: GPIO25
  jpeg_quality: 10
  vertical_flip: true
  horizontal_mirror: false

  # Image settings
  name: My Camera
  # ...
```

### Anything in the logs that might be useful for us?

```txt
[W][wifi:455]: No matching network found!
[W][wifi:585]: Restarting WiFi adapter...
[D][wifi:386]: Starting scan...
[D][esp32_camera:172]: Got Image: len=10243
[I][wifi:141]: Starting fallback AP!
```
