### ISSUE TITLE
Bedjet not seen by ESPHome

### ISSUE THREAD

**Issue by merak69** [esphome/issues#4146]
### The problem

I've flashed ESPHome 2022.12.8 via Home Assistant (and directly with esphomeflasher) on two different ESP32 devices and neither one sees my BedJet v3 device.  I've turned up logging and can see a bunch of devices but the BedJet is never listed.  I've tried removing the bedjet components from the yaml as well to no avail.

Thinking maybe my devices were bad, I flashed BLE-Scanner ([Link](https://github.com/gromeck/BLE-Scanner)) and it shows the BedJet right away.

Config (with obvious keys removed):
```
esphome:
  name: bedjet-esp

esp32:
  board: esp32dev

# Enable logging
logger:
  level: VERY_VERBOSE
  
# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedjet-Esp Fallback Hotspot"
    password: ""

captive_portal:

esp32_ble_tracker:

ble_client:
  - mac_address: e0:e2:e6:d4:d1:d2
    id: bedjet_ble_id1

bedjet:
  - id: bedjet_1
    ble_client_id: bedjet_ble_id1

climate:
  - platform: bedjet
    id: my_bedjet_climate_entity
    name: "My BedJet"
    bedjet_id: bedjet_1

fan:
  - platform: bedjet
    id: my_bedjet_fan_entity
    name: "My BedJet Fan"
    bedjet_id: bedjet_1

```

Hopefully it's just something stupid I'm doing but I've been banging my head on the desk for awhile now.  

Attached is a screenshot of the logs from BLE-Scanner showing the mac address listed above in the config.
![ble-scanner](https://user-images.githubusercontent.com/11600344/217685123-d7f37f96-e7a4-4f5a-b50a-80ca25d68a12.png)

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

ESP32-WROOM-32D
