### ISSUE TITLE
Can't validate/upload from esphome dashboard in HomeAssistant

### ISSUE THREAD

**Issue by icegothic** [esphome/issues#4150]
### The problem

I cannot validate or upload (wirelessly or via WebSerial) from HomeAssistant esphome addon dashboard.

Here is my configurations:

![firefox_1usIocXYgi](https://user-images.githubusercontent.com/16883752/217883089-710380f6-137c-4475-9ea0-20d052965330.png)

![firefox_mZ6dc2OCAa](https://user-images.githubusercontent.com/16883752/217883141-4b3adc76-2623-4c47-9174-a909dd3bfb05.png)

![firefox_E88AwBEBLy](https://user-images.githubusercontent.com/16883752/217883157-0510a355-a4f2-472d-9093-f0d99d637ccc.png)

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.3

### What platform are you using?

ESP8266

### Board

NodeMCU v1.0

### Component causing the issue

Don't know what to put here

### Example YAML snippet

```yaml
esphome:
  name: led

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EA5rN9IH2J9+5LuqX88+a3kz9FnLi4cqE4O0ut/a++c="

ota:
  password: "9a7ca130a8f9234b9c818e754ffb7c84"

wifi:
  ssid: wifissid
  password: wifipa

  ap:
    ssid: "Led Fallback Hotspot"
    password: "UR6ro62DAuyX"

captive_portal:

output:
  - platform: gpio
    id: "led"
    pin: D3

light:
  - platform: binary
    output: "led"
    name: "Test Led"
  id: myled
```

### Anything in the logs that might be useful for us?

```txt
- I'm also using "NGINX Home Assistant SSL proxy" addon (3.2.0) installed from Home Assistant
- Same behavior in Chrome or Edge.
	
- Via HomeAssistant ESPHome addon Dashboard
  - I can:
    - See flashed devices
  - I can't:
    - Validate configs
    - Upload wirelessly
    - Upload via USB cable (downloading .bin and installing it via web.esphome.io)
    - See logs
	
- Via ESPHome Dashboard (using http://{HomeAssistantIp}:6052)
  - I can:
    - See flashed devices
    - Validate configs
    - Upload wirelessly
    - See logs
  - I can't:
    - Upload via USB cable (downloading .bin and installing it via web.esphome.io)
      - Note: it seems to requires HTTPS support but url is giving a "ERR_SSL_PROTOCOL_ERROR" with HTTPS
      - I get the error: "Failed to initialize. Try resetting your device or holding the BOOT button while selecting your serial port until it starts preparing the installation."
	
- Manually: 
  - I can flash using "esphome.exe compile" to create the .bin from .yaml and "ESPHome-Flasher-1.4.0-Windows-x64.exe" to deploy.
```

### Additional information

My setup is an Home Assistant Supervised installation installed in docker running on Debian in WSL2 (bridged network) on Windows 11. Everything works great except this issue. I do have a router and a duckdns setup.

I'm new to the ESP world and have limited network configuration knowledge.
