### ISSUE TITLE
Regression on latest EspHome Beta for ssd1306_i2c device

### ISSUE THREAD

**Issue by Lefuneste83** [esphome/issues#4155]
### The problem

When deploying tried and tested yaml configuration to ESP TTgo Cam with OLED display

The device totally crashes on next reset with hundreds of error :

`[E][display:490]: clear: Clipping is not set.`

The yaml configuration has been working on the same device for several years beforehand.
This occurs on all my TTgo Cams

### Which version of ESPHome has the issue?

ESPHome (dev)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.3

### What platform are you using?

ESP32

### Board

ESP32 TTgp Cam

### Component causing the issue

ssd1306_i2c

### Example YAML snippet

```yaml
i2c:
  sda: GPIO21
  scl: GPIO22

font:
  - file: "fonts/times-new-roman.ttf"
    id: tnr1
    size: 20
  - file: "fonts/times-new-roman.ttf"
    id: tnr2
    size: 35

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    rotation: 180°
    address: 0x3C
    lambda: |-
      it.strftime(64, 0, id(tnr1), TextAlign::TOP_CENTER,"C1 %d-%m-%Y", id(homeassistant_time).now());
      it.strftime(64, 64, id(tnr2), TextAlign::BASELINE_CENTER, "%H:%M", id(homeassistant_time).now());
```

### Anything in the logs that might be useful for us?

```txt
[I][logger:258]: Log initialized
[C][ota:469]: There have been 8 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:175]: Performing I2C bus recovery
[D][binary_sensor:034]: 'ttgocam1 PIR': Sending initial state OFF
[D][binary_sensor:034]: 'ttgocam1 Button': Sending initial state OFF
[C][ssd1306_i2c:010]: Setting up I2C SSD1306...
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: 30:AE:A4:C2:D6:E4
[I][wifi:257]: WiFi Connecting to 'Robot'...
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
...
...
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
[E][display:490]: clear: Clipping is not set.
Terminal disconnected: NetworkError: The device has been lost.
```

### Additional information

Issue does not occur on regular ESHhome HA plugin, so it is likely due to an update to the ssd1306_i2c component
