### ISSUE TITLE
ATC mi-thermometer binding key is missing

### ISSUE THREAD

**Issue by rafacouto** [esphome/issues#4159]
### The problem

[LYWSD03MMC](https://esphome.io/components/sensor/xiaomi_ble.html?highlight=atc_mithermometer#lywsd03mmc) devices can be flashed with the ATC firmware and it also uses a bind key (like the original firmware) but esphome doesn't implement the `bindkey` attribute with the `atc_mithermometer` platform. It is convenient to use this bindkey as a basic security feature (crypted communications and OTA upgrades of the device).

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.2.3

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

atc_mithermometer

### Example YAML snippet

```yaml
- platform: atc_mithermometer                                                                                                
    mac_address: "A4:C1:38:xx:xx:xx"                                                                                           
    # bindkey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" (not implemented with atc platform)
    temperature:                                                                                                               
      name: "Bedroom Temperature"                                                                                              
    humidity:                                                                                                                  
      name: "Bedroom Humidity"                                                                                                 
    battery_level:                                                                                                             
      name: "Bedroom Battery Level"                                                                                            
    battery_voltage:                                                                                                           
      name: "Bedroom Batteryi Voltage"                                                                                         
    signal_strength:                                                                                                           
      name: "Bedroom Signal"
```
