### ISSUE TITLE
esp reboots if a text_sensor component get's a null/empty message

### ISSUE THREAD

**Issue by pfichtner** [esphome/issues#4161]
### The problem

I have a text_sensor using mqtt_subscribe platform (see below). 

If there is a message published without a payload (e.g. mosquitto_pub with parameter  -m '') the ESP crashes and reboots. the log statement cannot be retrieved so I guess it even wasn't executed. 
Don't know if this is `mqtt_subscribe` specific or if it's a general `text_sensor` problem. 

### Which version of ESPHome has the issue?

v2022.12.8

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32-IDF

### Board

Shelly-Plus-1PM

### Component causing the issue

text_sensor

### Example YAML snippet

```yaml
text_sensor:
  - platform: mqtt_subscribe
    name: some_name
    on_value:
      - then:
        - logger.log: "Logger Info"
```
