### ISSUE TITLE
  'id' is a required option for [script].

### ISSUE THREAD

**Issue by cvjensen** [esphome/issues#4165]
### The problem

Whenever I try to compile using parameters in a script i get this message:

```
Failed config

script: [source lightcontroller.yaml:73]

  'id' is a required option for [script].
  -
    Unable to find action with the name 'id'.
    id: let_there_be_light
    parameters:
      sensor: int
    mode: queued
    then:
      - logger.log: Running secor1 script
```

I even tried to copy the script from [here](https://esphome.io/guides/automations.html#script-parameters)

As soon as i remove the parameters part it seems to be working .

Why is that?

### Which version of ESPHome has the issue?

Version: 2022.10.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Example YAML snippet

```yaml
script:
  - id: let_there_be_light
    parameters:
      sensor: int
    mode: queued
    then:
      - logger.log: "Running secor1 script"
```
