### ISSUE TITLE
Broken UART on ESP32 GPIO4/5

### ISSUE THREAD

**Issue by ficueu** [esphome/issues#4166]
### The problem

I'm using for about year Zigbee to LAN board based on ESP32 with external component from Oxan. Now i'm tryin to update device but uart stops working. I checked few scenarios:
1: ESP32, ethernet, uart (GPIO4/5), latest esphome - stream server not working.
2: ESP32, WiFi, uart (GPIO4/5), latest esphome - stream server working.
3: ESP32, ethernet, uart (GPIO34/15), latest esphome - stream server working.
After that, i'm near 100% sure that is correlated with GPIO4/5 and ethernet. Version compiled about year ago working great in scenario 1 but i don't know what exactly version it was. 

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.8

### What platform are you using?

ESP32

### Board

ESP32-s (external ipx connector)

### Component causing the issue

uart, ethernet

### Example YAML snippet

```yaml
esphome:
  name: esp-lan

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  password: deleted

status_led:
  pin:
    number: 2
    inverted: true
    
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1
 
time:
  - platform: homeassistant
    id: homeassistant_time

external_components:
  - source: github://oxan/esphome-stream-server
  
stream_server:
  uart_id: uart_bus
  port: 1234

uart:
  - id: uart_bus
    rx_pin: GPIO4
    tx_pin: GPIO5
    baud_rate: 115200
```

### Anything in the logs that might be useful for us?

```txt
Stream server says that new client is connected, some data is sending to uart but device connected to the uart is not responding (while set uart do debug).
```
