### ISSUE TITLE
ESP32_camera on esp32-s3-WROOM-1 module gives watchdog reset

### ISSUE THREAD

**Issue by lecrams** [esphome/issues#4168]
### The problem

When I add the CAM32 component to my board yaml (see below) I get into a bootloop. Loggings can be found below.
Using the SSD1306 display which is also on the board without the camera definition has no problems

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.3

### What platform are you using?

ESP32

### Board

LilyGo T-camera-S3 with ESP32-S3 WROOM-1 module

### Component causing the issue

ESP32_CAM

### Example YAML snippet

```yaml
esphome:
  name: esp-lilycam

esp32:
  board: esp32-s3-devkitc-1
#  board: esp32cam 
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.1.1
  variant: esp32s3


# ESP32-CAM
esp32_camera:
  name: LilyCam
  external_clock:
    pin: GPIO38
    frequency: 20MHz
  i2c_pins:
    sda: GPIO5
    scl: GPIO4
  data_pins: [GPIO14, GPIO47, GPIO48, GPIO21, GPIO13, GPIO11, GPIO10, GPIO9]
  vsync_pin: GPIO8
  href_pin: GPIO18
  pixel_clock_pin: GPIO12
```

### Anything in the logs that might be useful for us?

```txt
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
Saved PC:0x40377508
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x43c
load:0x403b6000,len:0xbd0
load:0x403ba000,len:0x29c8
entry 0x403b61d8
E (183) psram: PSRAM ID read error: 0x00ffffff
E (5217) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (5217) task_wdt: - loopTask (CPU 1)
E (5217) task_wdt: Tasks currently running:
E (5217) task_wdt: CPU 0: IDLE
E (5217) task_wdt: CPU 1: IDLE
E (5217) task_wdt: Aborting.
```

**Comment by lecrams** [comment]
issue solved

**Comment by maxpersg** [comment]
> issue solved

can past the code for the yaml file? i'm getting similar issue as well. thanks1

**Comment by trikerman** [comment]
> ```yaml
> # ESP32-CAM
> esp32_camera:
>   name: LilyCam
>   external_clock:
>     pin: GPIO38
>     frequency: 20MHz
>   i2c_pins:
>     sda: GPIO5
>     scl: GPIO4
>   data_pins: [GPIO14, GPIO47, GPIO48, GPIO21, GPIO13, GPIO11, GPIO10, GPIO9]
>   vsync_pin: GPIO8
>   href_pin: GPIO18
>   pixel_clock_pin: GPIO12
> ```

ok, yaml file please?

**Comment by trikerman** [comment]
> issue solved

ok, yaml file please?

**Comment by lecrams** [comment]
this specific  issue was solved but the yaml for the camera part is still not working. Seems that that the PMU is not init correctlly

**Comment by webcharlyx** [comment]
PMU is [AXP2101](https://github.com/Xinyuan-LilyGO/LilyGo-Cam-ESP32S3#power-channel) -> Camera: ALDO1/ALDO2/ALDO4
[in this example](https://github.com/Xinyuan-LilyGO/LilyGo-Cam-ESP32S3/blob/master/examples/MinimalCameraExample/main.cpp#L42) they show how to adjust the three voltages.
with https://github.com/Xinyuan-LilyGO/LilyGo-Cam-ESP32S3/tree/master/lib/XPowersLib

I guess a new ESPhome component for AXP2101 is mandatory as first step.

**Comment by joopdo** [comment]
This still seems an issue with v2023.5.5.

**Comment by mrdis** [comment]
Hi, I managed to make it work by using the following YAML

```yaml
esphome:
  name: prova
  friendly_name: prova
  libraries:
    - XPowersLib=https://github.com/lewisxhe/XPowersLib.git
  includes:
    - AXP2101_component.h
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM -UARDUINO_USB_CDC_ON_BOOT"
```

I had to create the file "AXP2101_component.h" in the /config/esphome folder with this content:

```cpp
#include "esphome.h"

#define XPOWERS_CHIP_AXP2101
#include "XPowersLib.h"

#define I2C_SDA                     (7)
#define I2C_SCL                     (6)

class AXP2101Component : public Component {
 public:
  void setup() override {
    // This will be called once to set up the component
    // think of it as the setup() call in Arduino
    ESP_LOGD("custom", "Custom component setup");
    
    if (!PMU.begin(Wire, AXP2101_SLAVE_ADDRESS, I2C_SDA, I2C_SCL)) {
        Serial.println("Failed to initialize power.....");
        while (1) {
            delay(5000);
        }
    }
    //Set the working voltage of the camera, please do not modify the parameters
    PMU.setALDO1Voltage(1800);  // CAM DVDD  1500~1800
    PMU.enableALDO1();
    PMU.setALDO2Voltage(2800);  // CAM DVDD 2500~2800
    PMU.enableALDO2();
    PMU.setALDO4Voltage(3000);  // CAM AVDD 2800~3000
    PMU.enableALDO4();

    // TS Pin detection must be disable, otherwise it cannot be charged
    PMU.disableTSPinMeasure();
    
  }
  private:
    XPowersPMU  PMU;
};
```

**Comment by lecrams** [comment]
I assume that this code comes as addition to the 'normal' esp32 yaml like the vsync and datapin definitions?

**Comment by joopdo** [comment]
@Marcel, that's right. For example, here's my config with only the password scrubbed. This enables both camera and screen:

````
esphome:
  name: camera-2
  friendly_name: "Camera 2 - ESP32 S3"
  libraries:
    - XPowersLib=https://github.com/lewisxhe/XPowersLib.git
    - "Wire"
  includes:
    - AXP2101_component.h   
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM -UARDUINO_USB_CDC_ON_BOOT"

custom_component:
- lambda: |-
    auto axp2101 = new AXP2101Component();
    return {axp2101};
  components:
  - id: axp2101

esp32:
  board: esp32s3box
  framework:
    type: arduino

logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<scrub>"

ota:
  password: "4f9be56231e85ec6151e54196825efc3"

wifi:
  ssid: !secret wifi_ssid_2
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-S3 Fallback Hotspot"
    password: "<scrub>"
captive_portal:

psram:
time:
  - platform: homeassistant
    id: homeassistant_time  

font:
  - file: "nanum.ttf"
    id: tnr1
    size: 20

web_server:
  version: 2

i2c:
  sda: GPIO07
  scl: GPIO06

esp32_camera:
  name: camera-2
  external_clock:
     pin: GPIO38
     frequency: 20MHz
  i2c_pins:
    sda: GPIO05
    scl: GPIO04
  data_pins: [GPIO14, GPIO47, GPIO48, GPIO21, GPIO13, GPIO11, GPIO10, GPIO09]
  vsync_pin: GPIO8
  href_pin: GPIO18
  pixel_clock_pin: GPIO12
  vertical_flip: false
  horizontal_mirror: false
  resolution: 1024x768
 # agc_gain_ceiling: 128x
 # aec2:  true
  
  #vertical_flip: false
  max_framerate: 2 fps
  idle_framerate: 0.05 fps
  # ...
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot      

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    rotation: 180
    lambda: |-
      it.strftime(64, 0, id(tnr1), TextAlign::TOP_CENTER,"%m-%d-%Y", id(homeassistant_time).now());
      it.strftime(64, 64, id(tnr1), TextAlign::BASELINE_CENTER, "%I:%M:%S%p", id(homeassistant_time).now());
````
