### ISSUE TITLE
ESP Home 2023.2.0 Bluetooth proxy update failing

### ISSUE THREAD

**Issue by yestrdave** [esphome/issues#4169]
### The problem

Updated to ESP Home 2023.2.0 this morning then proceeded to update the Bluetooth proxies. I tried two firmware updates via wireless connection and then one with serial. This error is present with both methods

![image](https://user-images.githubusercontent.com/93943061/219044203-5a2bebad-5e33-4fc3-831a-9701d005f58e.png)

HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash

framework-espidf @ 3.40402.0 (4.4.2)
tool-cmake @ 3.16.4
tool-ninja @ 1.7.1
toolchain-esp32ulp @ 2.35.0-20220830
toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- Improv @ 1.2.3
*** [/data/house-garage-bluetooth-proxy/.pioenvs/house-garage-bluetooth-proxy/src/esphome/components/mdns/mdns_esp32_arduino.o] Source src/esphome/components/mdns/mdns_esp32_arduino.cpp' not found, needed by target /data/house-garage-bluetooth-proxy/.pioenvs/house-garage-bluetooth-proxy/src/esphome/components/mdns/mdns_esp32_arduino.o'.
========================== [FAILED] Took 6.05 seconds ==========================

### Which version of ESPHome has the issue?

2023.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.4

### What platform are you using?

ESP32

### Board

Atom Lite

### Component causing the issue

firmware update

### Example YAML snippet

```yaml
substitutions:
  name: "house-garage-bluetooth-proxy"
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

Left out wifi and static ip
```
