### ISSUE TITLE
pulse_meter stopped working after updating to 2023.2.0

### ISSUE THREAD

**Issue by Rvh91** [esphome/issues#4176]
### The problem

My water meter that uses the `pulse_meter` platform has stopped working after updating to 2023.2.0. No pulses are ever reported in home assistant or in the logs of  the device.

### Which version of ESPHome has the issue?

2023.2.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

WT32-ETH01 ESP32

### Component causing the issue

pulse_meter

### Example YAML snippet

```yaml
I'm using the following YAML


  - platform: pulse_meter
    pin: GPIO39
    name: "Water Pulse Meter"
    unit_of_measurement: "liter/min"
    icon: "mdi:water"
    internal_filter: 700ms
    internal_filter_mode: pulse
    total:
      name: "Water Meter Total"
      unit_of_measurement: "m³"
      id: water_meter_total
      accuracy_decimals: 3
      device_class: water
      state_class: total_increasing
      filters:
        - multiply: 0.001
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
