### ISSUE TITLE
RGB lights crashing  after upgrade to 2023.2.1

### ISSUE THREAD

**Issue by alfwro13** [esphome/issues#4177]
### The problem

After updating firmware in my ESPHome rgb lights the are crashing every couple of minutes with this error:

`INFO Reading configuration /config/esphome/rgb-light-office.yaml...
INFO Starting log output from 192.168.1.17 using esphome API
WARNING 192.168.1.17: Connection error occurred: Timeout waiting for response for <class 'api_pb2.ConnectRequest'> after 10.0s
WARNING Can't connect to ESPHome API for 192.168.1.17: Timeout waiting for response for <class 'api_pb2.ConnectRequest'> after 10.0s
INFO Trying to reconnect to 192.168.1.17 in the background
INFO Successfully connected to 192.168.1.17
[08:56:32][I][app:102]: ESPHome version 2023.2.1 compiled on Feb 16 2023, 08:22:53
[09:01:20][I][ota:113]: Boot seems successful, resetting boot loop counter.
WARNING 192.168.1.17: Connection error occurred: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 520, in send_message_await_response_complex
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 520, in send_message_await_response_complex
    await fut
  File "/usr/local/lib/python3.9/dist-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/dist-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 303, in _keep_alive_loop
    await self._ping()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 628, in _ping
    await self.send_message_await_response(PingRequest(), PingResponse)
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 537, in send_message_await_response
    res = await self.send_message_await_response_complex(
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 522, in send_message_await_response_complex
    raise TimeoutAPIError(
aioesphomeapi.core.TimeoutAPIError: Timeout waiting for response for <class 'api_pb2.PingRequest'> after 10.0s
INFO Disconnected from ESPHome API for 192.168.1.17
WARNING Disconnected from API
INFO Successfully connected to 192.168.1.17`

Prior to the upgrade they were working without issues (on December firmware 2022.12)

### Which version of ESPHome has the issue?

v2023.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP8266

### Board

esp01_1m

### Example YAML snippet

```yaml
esphome:
  name: rgb-light-office

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
<removed>

ota:
<removed>

wifi:
<removed>

captive_portal:

output:
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO14
    max_power: 80%
    frequency: 10 kHz
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO5
    max_power: 80%
    frequency: 10 kHz
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO12
    max_power: 80%
    frequency: 10 kHz
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO15
    max_power: 80%
    frequency: 10 kHz

globals:
  - id: action_state
    type: int
    restore_value: no
    initial_value: '0'

binary_sensor:
  - platform: gpio
    pin:   GPIO13
    name: "RGBW Controller Button"
    internal: true
    filters:
      - invert:
      - delayed_on_off: 20ms
    on_press:
      then:
        - lambda: id(action_state) = (id(action_state) + 1) % 5;
        - if:
            condition:
              lambda: 'return id(action_state) == 0;'
            then:
              - light.turn_off:  office_rgbw_lightstrip
        - if:
            condition:
              lambda: 'return id(action_state) == 1;'
            then:
              - light.turn_on:
                  id: office_rgbw_lightstrip
                  brightness: 100%
                  color_brightness: 80%
                  red: 0%
                  green: 0%
                  blue: 0%
                  white: 80% 
        - if:
            condition:
              lambda: 'return id(action_state) == 2;'
            then:
              - light.turn_on:
                  id: office_rgbw_lightstrip
                  brightness: 100%
                  red: 0%
                  green: 100%
                  blue: 0%
                  white: 0%
        - if:
            condition:
              lambda: 'return id(action_state) == 3;'
            then:
              - light.turn_on:
                  id: office_rgbw_lightstrip
                  brightness: 100%
                  red: 100%
                  green: 0%
                  blue: 0%
                  white: 0% 
        - if:
            condition:
              lambda: 'return id(action_state) == 4;'
            then:
              - light.turn_on:
                  id: office_rgbw_lightstrip
                  brightness: 100%
                  red: 0%
                  green: 0%
                  blue: 100%
                  white: 0% 
light:
  - platform: rgbw
    name: "Office RGB Light Strip"
    id: office_rgbw_lightstrip
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    restore_mode: ALWAYS_OFF
```
