### ISSUE TITLE
Script never completes

### ISSUE THREAD

**Issue by geoffoxholm** [esphome/issues#4181]
### The problem

I have a small script (in mode `single`) that toggles some GPIO switches. In order to debug I have a `text_sensor` that reports the state, and a `binary_sensor` that shows whether the script is running. When the issue happens the `text_sensor` is reporting that the script is mid-way through, and the `binary_sensor` reports that the script is running. The state never clears.

This issue is not predictable. It only happens sometimes. Of course it never seems to happen when I am recording the logs.

The script is triggered by a change to the `fireplace_ignition_switch`. This then calls the (mode `single`) script. When the script is running, the state of the `text_sensor` goes like this:

* Off
* Turning on

When the issue occurs it does not even get to the 'Waiting for action to complete'  message.

If I issue another change to `fireplace_ignition_switch` (by toggling the switch in HA) the log from the device correctly reports that the script is currently running (so it's not an issue of the device and Home Assistant being out of sync). 

### Which version of ESPHome has the issue?

v2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP8266

### Board

nodemcu

### Example YAML snippet

```yaml
esphome:
  name: esp-02
  on_boot:
    then:
      # explicitly set the control slider to 0
      - text_sensor.template.publish:
          id: fireplace_status
          state: 'Off (Clean Reboot)'

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: XXX
  services: 
    - service: set_state_off
      then:
        - switch.template.publish:
            id: fireplace_ignition_switch
            state: OFF
    - service: set_state_on
      then:
        - switch.template.publish:
            id: fireplace_ignition_switch
            state: ON
    - service: set_changing_off
      then:
        - script.stop: set_ignition

script:
  #
  # Script to toggle state, so that `single` can be used
  # Avoiding race conditions with on and off
  #
  - id: set_ignition
    mode: single
    parameters:
      new_state: bool
    then:
      - if:
          condition:
            lambda: return(new_state);
          then:
            #
            # TURN ON
            #
            - text_sensor.template.publish:
                id: fireplace_status
                state: 'Turning on'
            - switch.turn_on: internal_1
            - switch.turn_on: internal_3        
            - delay: 2s 
            - switch.turn_off: internal_1
            - switch.turn_off: internal_3
            - switch.template.publish:
                id: fireplace_ignition_switch
                state: ON
          else:
              #
              # TURN OFF
              #
              - text_sensor.template.publish:
                  id: fireplace_status
                  state: 'Turning off'
              - switch.turn_on: internal_1
              - switch.turn_on: internal_2
              - switch.turn_on: internal_3        
              - delay: 2s 
              - switch.turn_off: internal_1
              - switch.turn_off: internal_2
              - switch.turn_off: internal_3
              - switch.template.publish:
                  id: fireplace_ignition_switch
                  state: OFF
      - text_sensor.template.publish:
          id: fireplace_status
          state: 'Waiting for action to complete'
      - delay: 28s
      - if:
          condition:
            lambda: return(new_state);
          then:
            - text_sensor.template.publish:
                id: fireplace_status
                state: 'On'
          else:
            - text_sensor.template.publish:
                id: fireplace_status
                state: 'Off'

switch:
  - platform: gpio
    pin: GPIO5   #D1, relay 1
    name: "Relay 1"
    restore_mode: ALWAYS_OFF
    id: internal_1
  - platform: gpio 
    pin: GPIO4  #D2, relay 2
    name: "Relay 2"
    restore_mode: ALWAYS_OFF
    id: internal_2
  - platform: gpio 
    pin: GPIO0  #D3, relay 3
    restore_mode: ALWAYS_OFF
    name: "Relay 3" 
    id: internal_3
  - platform: gpio 
    pin: GPIO2  #D3, relay 4
    restore_mode: ALWAYS_OFF
    name: "Relay 4" 
    id: internal_4

  - platform: template
    name: "Fireplace Ignition"
    id: fireplace_ignition_switch
    icon: mdi:fireplace
    turn_on_action: # when toggled, perform the ignition sequence
      - then:
          - script.execute:
              id: set_ignition
              new_state: True
    turn_off_action:
      - then:
          - script.execute:
              id: set_ignition
              new_state: False

button:
  - platform: template
    name: "Increase Flame"
    id: fireplace_increase
    icon: mdi:thermometer-plus
    on_press:
      then:
        - if:
            condition:
              switch.is_on: fireplace_ignition_switch
            then:
              - switch.turn_on: internal_1
              - delay: 1s
              - switch.turn_off: internal_1
  - platform: template
    name: "Decrease Flame"
    id: fireplace_decrease
    icon: mdi:thermometer-minus
    on_press:
      then:
        - if:
            condition:
              switch.is_on: fireplace_ignition_switch
            then:
              - switch.turn_on: internal_3
              - delay: 1s
              - switch.turn_off: internal_3

text_sensor:
  - platform: template
    name: "Fireplace Status"
    id: fireplace_status
    update_interval: never

binary_sensor:
  - platform: template
    name: "State changing"
    id: state_changing
    entity_category: "diagnostic"
    lambda: |-
      return id(set_ignition).is_running();
```
