### ISSUE TITLE
Device does add any sensors or switches in home assistant

### ISSUE THREAD

**Issue by odechr** [esphome/issues#4185]
### The problem

After i removed and re-added my device in home assistant it doesnt wanna show all sensors and switches..
On the webserver it all shows..

First issue many days ago was that it always showed offline on esphome because it couldnt find trough mDNS, all my other devices does.. Then i put a static IP, then it worked again. 

Ive done many changes to the config so i had a lot of unavailable sensors and switches so i figured that i will remove the devices from home assistant and add it again.

Then i lost most of my sensors in HA.

Webserver:
![image](https://user-images.githubusercontent.com/57597773/219499344-76a5dff3-3fbf-4937-8a27-1ce2fb4871fe.png)

This is all i see in home assistant:

![image](https://user-images.githubusercontent.com/57597773/219499416-c8132add-67b2-4d03-9a01-bea82b4940d0.png)
 

### Which version of ESPHome has the issue?

2023.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.02.5

### What platform are you using?

ESP8266

### Board

Athom 2CH Relay

### Component causing the issue

All?

### Example YAML snippet

```yaml
substitutions:
  name: "door-relay1"
  friendly_name: "door-relay1"
  device_description: "door-relay1"
  relay1_restore_mode: RESTORE_DEFAULT_ON
  relay2_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${name}"
#  name_add_mac_suffix: true
 # on_boot:
 # - switch.turn_on: relay1

esp8266:
  board: esp8285
  restore_from_flash: true

api:

ota:

logger:

web_server:
  port: 80

wifi:
  ssid: "XXXXXXXXX"
  password: "XXXXXXXXXX"
  manual_ip:
    static_ip: 10.0.0.35
    gateway: 10.0.0.1
    subnet: 255.255.255.0

captive_portal:

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

#Styrer Elko bryter som er koblet på GPIO14
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Dørbryter"
    id: dor_bryter
    on_press:
      then:
        - button.press: vitruell_bryter

#Styrer NO på keypad som er koblet på GPIO2
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    name: "Keypad NO"
    id: keypad_no
    on_press:
      then:
        - button.press: vitruell_bryter

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"

#Virtuell bryter i Home Assistant
  - platform: template
    name: "Virtuell dørbryter"
    id: vitruell_bryter
    on_press:
      then:
        - switch.turn_off: relay1
        - delay: 5 sec
        - switch.turn_on: relay1

switch:
  # Relay
  - platform: gpio
    name: "${friendly_name} - 1"
    pin: GPIO5
    id: relay1
    restore_mode: ${relay1_restore_mode}

  - platform: gpio
    name: "${friendly_name} - 2"
    pin: GPIO4
    id: relay2
    restore_mode: ${relay2_restore_mode}

light:
  - platform: status_led
    name: "${friendly_name} Status LED"
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO16

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true

  - platform: version
    name: "ESPHome Version"
```

### Anything in the logs that might be useful for us?

```txt
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.2.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Oslo",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.01.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "truenas": {
      "version": "0.0.0",
      "requirements": []
    },
    "toshiba_ac": {
      "version": "2023.1.0",
      "requirements": [
        "toshiba-ac==0.3.1"
      ]
    },
    "amshan": {
      "version": "2022.10.2",
      "requirements": [
        "amshan[serial]==2.0.5"
      ]
    },
    "nordpool": {
      "version": "0.0.11",
      "requirements": [
        "nordpool>=0.2"
      ]
    },
    "frigate": {
      "version": "3.0.0",
      "requirements": []
    },
    "samsungtv_tizen": {
      "version": "1.6.1",
      "requirements": [
        "websocket-client>=0.56.0",
        "wakeonlan>=2.0.0",
        "numpy>=1.19.2"
      ]
    },
    "powercalc": {
      "version": "v1.3.5",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "xplora_watch": {
      "version": "v2.7.2",
      "requirements": [
        "pyxplora_api==2.5.21",
        "geopy==2.2.0",
        "dataclasses-json",
        "pydub"
      ]
    },
    "unifi_status": {
      "version": "0.3.8",
      "requirements": [
        "pyunifi==2.21"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "elvia": {
      "version": "0.1.0",
      "requirements": []
    },
    "dash_cast": {
      "version": "1.0.0",
      "requirements": []
    },
    "eventsensor": {
      "version": "3.0.0",
      "requirements": []
    },
    "alarmo": {
      "version": "v1.9.7",
      "requirements": []
    },
    "fontawesome": {
      "version": "2.1.5",
      "requirements": []
    },
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "sonoff": {
      "version": "3.4.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "posten": {
      "version": "0.1.1",
      "requirements": []
    },
    "samsungtv_smart": {
      "version": "0.11.6",
      "requirements": [
        "websocket-client!=1.4.0,>=0.58.0",
        "wakeonlan>=2.0.0",
        "aiofiles>=0.8.0",
        "casttube>=0.2.1"
      ]
    },
    "landroid_cloud": {
      "version": "2.3.4",
      "requirements": [
        "pyworxcloud==2.1.23"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "monitor_docker": {
      "version": "1.10",
      "requirements": [
        "aiodocker==0.21.0",
        "python-dateutil==2.8.2"
      ]
    },
    "blueiris": {
      "version": "1.0.15",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "esphome",
    "name": "ESPHome",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/esphome",
    "requirements": [
      "aioesphomeapi==13.3.1",
      "esphome-dashboard-api==1.2.3"
    ],
    "zeroconf": [
      "_esphomelib._tcp.local."
    ],
    "dhcp": [
      {
        "registered_devices": true
      }
    ],
    "codeowners": [
      "@OttoWinter",
      "@jesserockz"
    ],
    "dependencies": [
      "bluetooth"
    ],
    "after_dependencies": [
      "zeroconf",
      "tag"
    ],
    "iot_class": "local_push",
    "integration_type": "device",
    "loggers": [
      "aioesphomeapi",
      "noiseprotocol"
    ],
    "is_built_in": true
  },
  "data": {
    "config": {
      "entry_id": "10dbcc2115c28c9294474bd57683a963",
      "version": 1,
      "domain": "esphome",
      "title": "door-relay1",
      "data": {
        "host": "10.0.0.35",
        "port": 6053,
        "password": "",
        "noise_psk": "",
        "device_name": "door-relay1"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "zeroconf",
      "unique_id": "d8:bf:c0:f7:97:41",
      "disabled_by": null
    },
    "storage_data": {
      "device_info": {
        "uses_password": false,
        "name": "door-relay1",
        "friendly_name": "",
        "mac_address": "**REDACTED**",
        "compilation_time": "Feb 16 2023, 23:05:15",
        "model": "esp8285",
        "manufacturer": "Espressif",
        "has_deep_sleep": false,
        "esphome_version": "2023.2.1",
        "project_name": "",
        "project_version": "",
        "webserver_port": 80,
        "bluetooth_proxy_version": 0
      },
      "services": [],
      "api_version": {
        "major": 1,
        "minor": 7
      },
      "switch": [
        {
          "object_id": "door-relay1_-_1",
          "key": 1248222130,
          "name": "door-relay1 - 1",
          "unique_id": "door-relay1switchdoor-relay1_-_1",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "assumed_state": false,
          "device_class": ""
        },
        {
          "object_id": "door-relay1_-_2",
          "key": 1248222129,
          "name": "door-relay1 - 2",
          "unique_id": "door-relay1switchdoor-relay1_-_2",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "assumed_state": false,
          "device_class": ""
        }
      ],
      "sensor": [
        {
          "object_id": "door-relay1_uptime",
          "key": 1831148401,
          "name": "door-relay1 Uptime",
          "unique_id": "d8bfc0f79741-uptime",
          "disabled_by_default": false,
          "icon": "mdi:timer-outline",
          "entity_category": 2,
          "device_class": "duration",
          "unit_of_measurement": "s",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 0,
          "last_reset_type": 0
        }
      ],
      "text_sensor": [
        {
          "object_id": "door-relay1_ip_address",
          "key": 2558126427,
          "name": "door-relay1 IP Address",
          "unique_id": "d8bfc0f79741-wifiinfo-ip",
          "disabled_by_default": true,
          "icon": "",
          "entity_category": 2
        },
        {
          "object_id": "esphome_version",
          "key": 2314437119,
          "name": "ESPHome Version",
          "unique_id": "d8bfc0f79741-version",
          "disabled_by_default": false,
          "icon": "mdi:new-box",
          "entity_category": 2
        }
      ],
      "button": [
        {
          "object_id": "door-relay1_restart",
          "key": 4171473706,
          "name": "door-relay1 Restart",
          "unique_id": "door-relay1buttondoor-relay1_restart",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 1,
          "device_class": "restart"
        },
        {
          "object_id": "virtuell_drbryter",
          "key": 84764005,
          "name": "Virtuell d\u00f8rbryter",
          "unique_id": "door-relay1buttonvirtuell_drbryter",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": ""
        }
      ],
      "light": [
        {
          "object_id": "door-relay1_status_led",
          "key": 4031641665,
          "name": "door-relay1 Status LED",
          "unique_id": "door-relay1lightdoor-relay1_status_led",
          "disabled_by_default": true,
          "icon": "",
          "entity_category": 0,
          "supported_color_modes": [
            1
          ],
          "min_mireds": 0.0,
          "max_mireds": 0.0,
          "effects": [],
          "legacy_supports_brightness": false,
          "legacy_supports_rgb": false,
          "legacy_supports_white_value": false,
          "legacy_supports_color_temperature": false
        }
      ],
      "binary_sensor": [
        {
          "object_id": "door-relay1_status",
          "key": 2546735355,
          "name": "door-relay1 Status",
          "unique_id": "door-relay1binary_sensordoor-relay1_status",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 2,
          "device_class": "connectivity",
          "is_status_binary_sensor": true
        },
        {
          "object_id": "drbryter",
          "key": 379725481,
          "name": "D\u00f8rbryter",
          "unique_id": "door-relay1binary_sensordrbryter",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "",
          "is_status_binary_sensor": false
        },
        {
          "object_id": "keypad_no",
          "key": 59352157,
          "name": "Keypad NO",
          "unique_id": "door-relay1binary_sensorkeypad_no",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "",
          "is_status_binary_sensor": false
        }
      ]
    },
    "dashboard": "5c53de3b_esphome"
  }
}
```
