### ISSUE TITLE
Sonoff TH Origin 16A (THR316D) + Sonoff Temp and Humidity Sensor THS01 (SI7021) Invalid Readings 

### ISSUE THREAD

**Issue by paulguru** [esphome/issues#4189]
### The problem

Hi ESPHome team,

I'm struggling to get the Sonoff Temp and Humidity Sensor THS01 (SI7021) working on the Sonoff TH Origin 16A (THR316D). 

I used the yaml configuration of the Sonoff THR320D (https://www.esphome-devices.com/devices/Sonoff-THR320D) as the base for the configuration of the THR316D with some changes (since the THR316D uses a slightly different GPIO's). 

I ruled out hardware issues as the sensor works when using Tasmota32.bin firmware. 

FYI - I tried compiling using various board and framework options i.e. nodemcu-32s/esp32dev and esp-idf/arduino but this does not seem to have an effect. 

### Which version of ESPHome has the issue?

2023.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.2.5

### What platform are you using?

ESP32-IDF

### Board

nodemcu-32s

### Component causing the issue

DHT

### Example YAML snippet

```yaml
substitutions:
  device_name: sonoffth316d
  location: Garage
    
esphome:
  name: "${device_name}"
  friendly_name: Sonoff Elite TH 1
  # supply the external temp/hum sensor with 3v power by pulling this GPIO high
  on_boot:
    - priority: 90
      then:
      - switch.turn_on: TH_sensor_power


esp32:
  board: nodemcu-32s
  #board: esp32dev
  framework:
    type: esp-idf
  #  type: arduino
        
# Enable logging
logger:
  baud_rate: 0
#  level: VERBOSE
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXX"

ota:
  password: "XXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: XXXXX
    gateway: XXXXX
    subnet: XXXXX

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: !secret wifi_debug

#captive_portal:
 
#### TIME ####

time:
  - platform: homeassistant
    id: homeassistant_time
    
### BUTTON ###

button:
  - platform: restart
    name: $device_name Restart
    device_class: restart
    entity_category: diagnostic

### DISPLAY ###

display:
  platform: tm1621
  id: tm1621_display
  cs_pin: GPIO17
  data_pin: GPIO5
  read_pin: GPIO23
  write_pin: GPIO18
  lambda: |-
    it.printf(0, "%.1f", id(${device_name}_temp).state);
    it.display_celsius(true);
    it.printf(1, "%.1f", id(${device_name}_humi).state);
    it.display_humidity(true);


### BINARY SENSOR ###

binary_sensor:
  # single main button that also puts device into flash mode when held on boot
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_name} Button"
    on_press:
      then:
        - switch.toggle: relay_1

  - platform: status
    name: "${device_name} Status"


### SWITCH ###

switch:

# Main Relay GPIO21

  - platform: gpio
    name: ${device_name}_relay
    pin: GPIO21
    id: relay_1
    # after reboot, keep the relay off. this prevents light turning on after a power outage
    restore_mode: ALWAYS_OFF
    on_turn_on:
      light.turn_on: power_led
    on_turn_off:
      light.turn_off: power_led
    
    
  # dry contact relay switch
  - platform: gpio
    id: dryContRelay
    name: "Dry Contact Relay"
    pin:
      number: GPIO4
      inverted: true
    on_turn_on:
      light.turn_on: green_led
    on_turn_off:
      light.turn_off: green_led


  - platform: gpio
    pin:
      number: GPIO27
    #  inverted: false 
    id: TH_sensor_power
    restore_mode: ALWAYS_ON

### OUTPUT ###

# LEDs need gpio output defined
output:
  # Power LED
  - id: power_led_output
    platform: gpio
    pin: 16
    inverted: True

  # GREEN LED 
  - id: green_led_output
    platform: gpio
    pin: 13
    inverted: True
  
### LIGHT ###

light:
  # Power LED
  - platform: binary
    id: power_led
    name: "Power LED"
    output: power_led_output
    internal: true

  # Green LED
  - platform: binary
    id: green_led
    name: "Green LED"
    output: green_led_output
    internal: true

  # Blue LED (middle). Used as wifi status indicator.
  - platform: status_led
    name: "${device_name} Wifi LED"
    pin:
      number: GPIO15
      inverted: true
    id: wifi_led  
    internal: true   

### INTERVAL ###

interval:
  - interval: 60s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - light.turn_on: wifi_led
        else:
          - light.turn_off: wifi_led


### SENSOR ###

sensor:
  # "Sonoff THS01 - SI7021"
  - platform: dht
    pin: GPIO25
    model: SI7021
    temperature:
      name: "${location} Temperature"
      id: ${device_name}_temp
    humidity:
      name: "${location} Humidity"
      id: ${device_name}_humi
    update_interval: 60s

  - platform: wifi_signal
    name: $device_name Wifi RSSI
    update_interval: 60s

  - platform: uptime
    id: uptime_sensor
    internal: True
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();


#### TEXT SENSOR ####

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

  - platform: template
    name: $device_name Uptime
    id: uptime_human
    icon: mdi:clock-start

  - platform: wifi_info
    ip_address:
      name: $device_name IP
    mac_address:
      name: $device_name MAC Address
```

### Anything in the logs that might be useful for us?

```txt
Log file snippets:
1) Sensor startup messages
2) Sensor Error messages

1) Sensor startup messages // ########################
[11:02:44][C][dht:017]: DHT:
[11:02:44][C][dht:018]:   Pin: GPIO25
[11:02:44][C][dht:024]:   Model: DHT22 (or equivalent)
[11:02:44][C][dht:027]:   Update Interval: 60.0s
[11:02:44][C][dht:029]:   Temperature 'Garage Temperature'
[11:02:44][C][dht:029]:     Device Class: 'temperature'
[11:02:44][C][dht:029]:     State Class: 'measurement'
[11:02:44][C][dht:029]:     Unit of Measurement: '°C'
[11:02:44][C][dht:029]:     Accuracy Decimals: 1
[11:02:44][C][dht:030]:   Humidity 'Garage Humidity'
[11:02:44][C][dht:030]:     Device Class: 'humidity'
[11:02:44][C][dht:030]:     State Class: 'measurement'
[11:02:44][C][dht:030]:     Unit of Measurement: '%'
[11:02:44][C][dht:030]:     Accuracy Decimals: 0

2) Sensor Error messages // ######################

[11:03:43][W][dht:169]: Requesting data from DHT failed!
[11:03:43][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number).
[11:03:43][D][sensor:127]: 'Garage Temperature': Sending state nan °C with 1 decimals of accuracy
[11:03:43][D][sensor:127]: 'Garage Humidity': Sending state nan % with 0 decimals of accuracy
```

**Comment by Jenda987** [comment]
Maybe it's necessary to turn on power ...
switch:
  - platform: gpio
    id: power
    pin: GPIO27
    restore_mode: ALWAYS_ON

**Comment by paulguru** [comment]
> Maybe it's necessary to turn on power ...
> 
> ```
>   - platform: gpio
>     id: power
>     pin: GPIO27
>     restore_mode: ALWAYS_ON
> ```

Thanks @Jenda987, I have tried turning on the power (both as switch and as an outout). Neither seems to work.

**Comment by Beungoud** [comment]
There seems to be a timing problem in the dht component when running on an ESP32.
Looking at tasmota source code, they have a slightly different timing for ESP32 when using SI7021: https://github.com/arendst/Tasmota/blob/e80d053aa0bfb12ce1d4d6a2884be6c886d3669d/tasmota/tasmota_xsns_sensor/xsns_06_dht_v7.ino#L47

I tried this on a custom built dht component in esphome and it works. Currently working on a PR for this.

I miss an information: Does any one know how to detect if running on ESP32 or ESP8266 (#ifdef) in CPP code?

**Comment by popolite** [comment]
> 
`else if (this->model_ == DHT_MODEL_SI7021) {
#ifdef USE_ESP8266
    delayMicroseconds(500);
#else
    delayMicroseconds(400);
#endif
    this->pin_->digital_write(true);
    delayMicroseconds(40);
}`
Right?

**Comment by popolite** [comment]
> There seems to be a timing problem in the dht component when running on an ESP32. Looking at tasmota source code, they have a slightly different timing for ESP32 when using SI7021: https://github.com/arendst/Tasmota/blob/e80d053aa0bfb12ce1d4d6a2884be6c886d3669d/tasmota/tasmota_xsns_sensor/xsns_06_dht_v7.ino#L47

> I miss an information: Does any one know how to detect if running on ESP32 or ESP8266 (#ifdef) in CPP code?

in esphome/components/dht/dht.cpp
```
else if (this->model_ == DHT_MODEL_SI7021) {
#ifdef USE_ESP8266
    delayMicroseconds(500);
#else
    delayMicroseconds(400);
#endif
    this->pin_->digital_write(true);
    delayMicroseconds(40);
}
```
Instead of:
```
delayMicroseconds(500);
```
Right?

**Comment by erdembey** [comment]
Thank you for your my issues are also seems to be related with this.
If it's possible to generate a new bin files based on this modification i can try on my THR320 devices.
May be you can create a pull request.

> There seems to be a timing problem in the dht component when running on an ESP32. Looking at tasmota source code, they have a slightly different timing for ESP32 when using SI7021: https://github.com/arendst/Tasmota/blob/e80d053aa0bfb12ce1d4d6a2884be6c886d3669d/tasmota/tasmota_xsns_sensor/xsns_06_dht_v7.ino#L47
> 
> I tried this on a custom built dht component in esphome and it works. Currently working on a PR for this.
> 
> I miss an information: Does any one know how to detect if running on ESP32 or ESP8266 (#ifdef) in CPP code?

**Comment by erdembey** [comment]
@popolite status update, i've applied the updates you mentioned.
It's started working. I will be closely watching the results.
Thanks

**Comment by phazard** [comment]
I tried the workaround from @popolite , but it looks like i'm not changing the correct dht.cpp. could you please provide me with the correct path.
Thanks

**Comment by erdembey** [comment]
> I tried the workaround from @popolite , but it looks like i'm not changing the correct dht.cpp. could you please provide me with the correct path. Thanks

\esphome\components\dht\dht.cpp

**Comment by ilyagry** [comment]
I guess the problem is in interrupts lock

Tasmota code:
```
// Turn off interrupts temporarily because the next sections
  // are timing critical and we don't want any interruptions.
#ifdef ESP32
  {portMUX_TYPE mux = portMUX_INITIALIZER_UNLOCKED;
  portENTER_CRITICAL(&mux);
#else
  noInterrupts();
#endif
```
and ESPHOME (dht.cpp)

```
InterruptLock lock;
```
Probably ESP32 requires special interrupt lock commands (but I'm not C++ guru)

**Comment by Beungoud** [comment]
I just changed the timing here, and it works (some read failure, but ok most of the time).
You can try it by adding to your esphome configuration yaml:

```
external_components:
  source:
    type: git
    url: https://github.com/Beungoud/esphome
    ref: fix-esp32-dht-SI7021
  components: ["dht"]
 
```

**Comment by phazard** [comment]
@Beungoud ,I implemented your workaround and it looks good for me.

**Comment by dwildstr** [comment]
> ```
> external_components:
>   source:
>     type: git
>     url: https://github.com/Beungoud/esphome
>     ref: fix-esp32-dht-SI7021
>   components: ["dht"]
>  
> ```

This fix worked great for me until I upgraded to ESPHome 8.2, after which communication with my SI7021 became extremely sporadic. It's not obvious at all to me which of the (fairly minor-seeming) changes in 8.2 could have broken it, but rolling back my build to 8.1 made my SI7021 start working again.

**Comment by jlazkano** [comment]
Hello,

I have a THR316D device, is it officially supported? Couls you provide some basic stepts to flash with esphone?

Kind regards.

**Comment by erdembey** [comment]
> I just changed the timing here, and it works (some read failure, but ok most of the time). You can try it by adding to your esphome configuration yaml:
> 
> ```
> external_components:
>   source:
>     type: git
>     url: https://github.com/Beungoud/esphome
>     ref: fix-esp32-dht-SI7021
>   components: ["dht"]
>  
> ```

Will you please propose your fix to new release ?
It seems your fix still not included in the master.
Thanks

**Comment by mihaimdinca** [comment]
I apologize for off topic question, but is it normal for the esp on this device to have a almost steady internal temperature of 80 degrees Celsius?

**Comment by JanX2** [comment]
@mihaimdinca 
The temperature sensor needs to calibrated. 

You can use something like:

```
    filters:
     - multiply: 0.18
``` 

The factor will vary, of course.

**Comment by mihaimdinca** [comment]
I hope I was not misunderstood, I was referring to the internal esp32 temperature sensor

**Comment by JanX2** [comment]
> I hope I was not misunderstood, I was referring to the internal esp32 temperature sensor

https://www.danielmartingonzalez.com/en/calibrate-sensors-esphome/

**Comment by mihaimdinca** [comment]
I will look into it a bit more closely. Thank you very much.

**Comment by erdembey** [comment]
Can someone share a updated configuration for this setup. 
I can not use without fix-esp32-dht-SI7021 even though it's merged in latest version.

**Comment by mikenolet** [comment]
I too am having the same issue.  I am running the ESPHome add-on version 2024.7.2.  I have added the above mentioned YAML in the addon config but the error: 

Requesting data from DHT failed!
[20:37:52][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number)

This relates to a Sonoff THR316D with the plug in temperature sensor, model - WTS01, not certain if this is the same as the DHT.

**Comment by paulguru** [comment]
> I too am having the same issue. I am running the ESPHome add-on version 2024.7.2. I have added the above mentioned YAML in the addon config but the error:
> 
> Requesting data from DHT failed! [20:37:52][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number)
> 
> This relates to a Sonoff THR316D with the plug in temperature sensor, model - WTS01, not certain if this is the same as the DHT.

The DHT Temperature+Humidity Sensor component allows you to use the following sensors: 

DHT11 
DHT21/DHT22
AMS2301/AM2302
AM2120 
RHT03 
SI7021

**Comment by madzur** [comment]
I am having a similar issue with the Sonoff TH16 Origin and the WTS01 sensor. They are both sold as a bundle from Sonoff, having the RJ9 connection between the device and the sensor. I tried many solutions I could find online and I am not able to get the sensor to work.

ESPhome (version 2024.8.3) always gives me the error: [gpio.one_wire:078]: Found no devices!

Here is my config for reference:

```css

# Sonoff THR316 Smart Temperature and Humidity Monitoring Switch
# Assumes that a DS18B20 temperature sensor is connected
substitutions:
  friendly_name: "2-Boiler"
  name: 2-boiler

esphome:
  name: $name
  on_boot:
    - priority: 90
      then:
      # supply the external sensor with 3v power by pulling this GPIO high
      - switch.turn_on: sensor_power
      # Make sure the relay is in a known state at startup
      - switch.turn_off: relay
      # Default to running the climate control in Home mode
#      - climate.control:
#          id: climate_control
#          preset: "Home"

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "1234567890"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

#optional
web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: wifi_signal
    name: $friendly_name Wifi RSSI
    update_interval: 60s

  - platform: uptime
    id: uptime_sensor
    internal: True
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  - platform: template
    name: $friendly_name ESP32 Internal Temp
    device_class: temperature
    unit_of_measurement: °C
    id: esp32_temp
    lambda: return temperatureRead();

  # External DS18B20 Digital Temperature Sensor
#  - platform: dallas_temp
#    name: $friendly_name Temperature
#    id: temp
#    update_interval: 10s

switch:
  - platform: gpio
    name: $friendly_name
    pin: GPIO21
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - delay: 500ms
      - light.turn_on: switch_led
    on_turn_off:
      - delay: 500ms
      - light.turn_off: switch_led
  - platform: restart
    name: $friendly_name Restart

  # This is needed to power the external sensor.
  # It receives 3v3 from this pin, which is pulled up on boot.
  - platform: gpio
    pin: 27
    id: sensor_power
    restore_mode: ALWAYS_ON

text_sensor:
  - platform: template
    name: $friendly_name Uptime
    id: uptime_human
    icon: mdi:clock-start
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP
    ssid:
      name: $friendly_name SSID
    bssid:
      name: $friendly_name BSSID


light:
  - platform: status_led
    id: switch_led
    internal: True
    pin:
      number: GPIO16
      inverted: True
  - platform: status_led
    id: wifi_status_led
    internal: True
    pin:
      number: GPIO15
      inverted: True
  - platform: status_led
    id: auto_led
    internal: True
    pin:
      number: GPIO13
      inverted: True

interval:
  - interval: 30s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - light.turn_on: wifi_status_led
        else:
          - light.turn_off: wifi_status_led

# DS18B20 Digital Temperature Sensor Hub
one_wire:
  - platform: gpio
    pin: 25
    id: dallas

button:
  - platform: template
    name: Test 1-wire bus
    on_press:
     - lambda: |-
        id(dallas).search();
        id(dallas).dump_config();
```

**Comment by Wriman** [comment]
i have same problem, and no solution

**Comment by pekur** [comment]
Remove this part and you'll be fine. Or use another  ds18b20.

[
![Screenshot_20241129-213017](https://github.com/user-attachments/assets/3fd9ce89-f704-4ec8-824d-8308740609b4)
](url)

**Comment by erdembey** [comment]
> Remove this part

THS01 dont have that part ?

**Comment by pekur** [comment]
> > Remove this part
> 
> THS01 dont have that part ?

No, it doesn't have it. So THS01 works as it is with ESPHOME.

**Comment by madzur** [comment]
> Remove this part and you'll be fine. Or use another ds18b20.
> 
> [ ![Screenshot_20241129-213017](https://github.com/user-attachments/assets/3fd9ce89-f704-4ec8-824d-8308740609b4) ](url)

I bought a brand new ds18b20 and crimped a RJ9 connector at the end, according to the pinout at the end of this link: https://templates.blakadder.com/sonoff_THR316.html

However, my db18b20 only has 3 wires, inscead of 4 at the link above.
So, I used the following order (looking at the RJ9 connector from the bottom - latch facing away from me - and going left to right)
- Pin 1 VCC (I assume red wire)
- Pin 2 GPIO25 (I assume yellow wire)
- Pin 4 GND (I assume black wire)

Is this the same crimp order you have?

**Comment by alepee** [comment]
I got stucked as well and took some time to backport Tasmota solution into a WTS01 component for ESPHome. The PR has been created as a draft, I still need to update a few things.

In the meantime, if some of you wants to give it a try you can use is as an external component 😃 
https://github.com/esphome/esphome/pull/8539

**Comment by madzur** [comment]
> I got stucked as well and took some time to backport Tasmota solution into a WTS01 component for ESPHome. The PR has been created as a draft, I still need to update a few things.
> 
> In the meantime, if some of you wants to give it a try you can use is as an external component 😃 [esphome/esphome#8539](https://github.com/esphome/esphome/pull/8539)

Awesome work. I will test this once I have the opportunity to do so and will let you know my feedback.
I saw that you are working on including your changes in the master release, I hope swoboda1337 will review your changes and it can move forward.

Cheers.

**Comment by alepee** [comment]
I hope so. I'm not used to ESPHome PR review policy and don't have any idea when it will be merged 😅

**Comment by davet2001** [comment]
@alepee I had the same problem and your solution works really well! Thanks!
One possible enhancement would be to add an `update_interval` option. It currently reads once per second, which is way too much for a temperature sensor in a lot of cases.

**Comment by VitoTLT** [comment]
I'm not receiving any UART data from GPIO 25. Are you sure, that in THR316 GPIO25 using for WTS01 ? I've tried that WTS01 in Arduino and it sends UART data correctly. But when i connect this WTS01 in TRR316 - there is no UART data. The power to WTS01 delivered by GPIO27 switch (i've checked by multimeter). Also i've tried to look for raw UART data from GPIO 2,3,4,5,13,14,15,16,17,18,19,23,25,26,32,33 with no results...

**Comment by igo-r** [comment]
> One possible enhancement would be to add an `update_interval` option. It currently reads once per second, which is way too much for a temperature sensor in a lot of cases.

The update interval cannot be reduced it is embedded in the firmware of the MCU itself on the sensor wire.

**Comment by davet2001** [comment]
> The update interval cannot be reduced it is embedded in the firmware of the MCU itself on the sensor wire.

I see that the rate the data comes out of the sensor is fixed.

But the rate we send that back to HA can be slower. We dont have to send an update to HA or even the local ESP device on every received packet Could do once per 10s for example.

**Comment by igo-r** [comment]
> But the rate we send that back to HA can be slower. We dont have to send an update to HA or even the local ESP device on every received packet Could do once per 10s for example.

To do this, you need to use standard esphome tools
https://esphome.io/components/sensor/#throttle

**Comment by m8fas** [comment]
![Image](https://github.com/user-attachments/assets/ab425397-b431-46a2-a83a-5ae85c6c3dc7)
![Image](https://github.com/user-attachments/assets/119cc221-5277-4884-bfce-9cf72b6a4404)

guys, I'm using a Sonoff THR316D. I have a problem with the DS18B20 sensor; it's not giving me any readings. I've tried everything, but nothing works. Before flashing, it worked with the eWiLink software.
esphome:
  name: inverter-water-heater
  on_boot:
    priority: 800
    then:
      - output.turn_on: sensor_pwr

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

logger:
  baud_rate: 0
  level: DEBUG

captive_portal:

web_server:
  port: 80

output:
  - platform: gpio
    pin: GPIO27
    id: sensor_pwr

one_wire:
  - platform: gpio
    pin: GPIO25
    id: bus1

sensor:
  - platform: dallas_temp
    one_wire_id: bus1
    name: "Water Temperature"
    id: current_temp
    update_interval: 10s

display:
  - platform: tm1621
    id: my_display
    cs_pin: 17
    data_pin: 
      number: 5
      ignore_strapping_warning: true
    read_pin: 23
    write_pin: 18
    update_interval: 1s
    lambda: |-
      if (id(current_temp).has_state()) {
        it.printf(0, "%.1f", id(current_temp).state);
      } else {
        it.print(0, "---");
      }

switch:
  - platform: gpio
    name: "Heater Relay"
    pin: GPIO21
    id: relay1

[17:47:36.724][W][gpio.one_wire:083]:   Found no devices!

**Comment by kristjanbjarni** [comment]
> guys, I'm using a Sonoff THR316D. I have a problem with the DS18B20 sensor; it's not giving me any readings. I've tried everything, but nothing works. Before flashing, it worked with the eWiLink software. esphome: name: inverter-water-heater on_boot: priority: 800 then: - output.turn_on: sensor_pwr

The DS18B20 needs to have a 4.7k resistor to work reliably in ESPHome for some reason especially for long wires.

See: https://esphome.io/components/one_wire/

I had problems with my TH16 until I added the resistor.

**Comment by alepee** [comment]
Hi @m8fas ! Just a heads-up: you don't need a `dallas`/1-Wire setup for the WTS01 probe. It use a **RJ9/RJ10 (4P4C)** connector, the WTS01 is **not** a 1-Wire / DS18B20 sensor, it speaks a simple UART protocol at 9600 baud.

ESPHome has had native support for it for a few months now via the `wts01` sensor component: https://esphome.io/components/sensor/wts01

Minimal config (the THR316D wires the probe's data line to **GPIO25**):

```yaml
uart:
  rx_pin: GPIO25
  baud_rate: 9600

sensor:
  - platform: wts01
    name: "Temperature"
```

No `one_wire:` / `dallas:` block needed, remove those if you had them. That should get the probe reporting correctly.
