### ISSUE TITLE
Deep sleep mode doesn't work after updating

### ISSUE THREAD

**Issue by sunsetitaly** [esphome/issues#4190]
S O L V E D  --- Sorry my mistake

### The problem

After updating to version 2023.2.1 the deep sleep mode seems not work properly. The board (ESP-12) enters in deep sleep, it awakes but the run_duration is only few ms meanwhile it is set to 4s, therefore the data are not transfer to the entity card in HA.

### Which version of ESPHome has the issue?

2023.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.4

### What platform are you using?

ESP8266

### Board

ESP12

### Component causing the issue

deep sleep

### Example YAML snippet

```yaml
mqtt:
  broker: 192.168.1.63
  username: xxxxx
  password: xxxxx
  discovery: False
  discovery_retain: False
  birth_message:
    topic: $devicename/status
    payload: online
  will_message:
    topic: $devicename/status
    payload: offline
  on_message:
    - topic: $devicename/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
        - mqtt.publish:
            topic: $devicename/ota_mode_status
            payload: "active"
    
    - topic: $devicename/sleep_mode
      payload: 'ON'
      then:
        - mqtt.publish:
            topic: $devicename/ota_mode_status
            payload: "disabled"
        - deep_sleep.enter: deep_sleep_1

logger:
  level: DEBUG # WARN

ota:

api:
  

i2c:
  sda: D2
  scl: D1
  scan: false

output:
  - platform: gpio
    pin: D4
    id: gpio_d4
    inverted: true
  - platform: gpio
    pin: D3
    id: gpio_d3
   
    
# AHT10
  - platform: aht10
    temperature:
      name: "${devicename}_temperature"
      id: esp12_cuc_temp
      accuracy_decimals: 1
    humidity:
      name: "${devicename}_humidity"
      id: esp12__cuc_hum
      accuracy_decimals: 1


#battery
  - platform: adc
    pin: VCC
    name: "${devicename}_voltage"
    id: d1_pro_vbatt
    state_class: measurement
    device_class: battery
    update_interval: 4s
    #filters:
    #  - multiply: 1.0          # 1.23
    on_value_range:
      - below: 1.6    #min voltage ESP8266 is 2.58V
        then:
          - mqtt.publish:
              topic: $devicename/low_voltage
              payload: "true"

deep_sleep:
  id: deep_sleep_1
  run_duration: 4s
  sleep_duration: 10min
```

### Additional information

It was working fine before updating
