### ISSUE TITLE
Uptime Statistics Broken

### ISSUE THREAD

**Issue by DAVe3283** [esphome/issues#4193]
### The problem

After updating to ESPHome 2023.2.0 (through 2023.2.2 so far), all my ESPHome devices' Uptime is no longer recording statistics with the error `The state class '' of this entity is not supported.`:
![image](https://user-images.githubusercontent.com/6894502/219696592-bb96749c-de0f-41ed-919d-f3891793e86e.png)

It appears that the state_class was removed by esphome/esphome#4345. This PR appears to have been to resolve an error in Home Assistant, but I believe that error was actually this bug: home-assistant/core#88096.

If I manually add `state_class: total_increasing` back to my devices, I do not see the error mentioned in esphome/esphome#4345 as of Home Assistant 2023.2.5. I believe that PR should be reverted, since it seems to have been working around a bug in Home Assistant that has since been fixed.

I would be happy to provide a PR to fix this if my understanding of the situation is correct.

### Which version of ESPHome has the issue?

2023.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP32

### Board

Olimex ESP32-POE-ISO

### Component causing the issue

uptime

### Example YAML snippet

```yaml
esphome:
  name: haks-poe-prototype

esp32:
  board: esp32-poe-iso

logger:

api:

ota:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  power_pin: GPIO12

sensor:
  - platform: uptime
    name: Uptime
```
