### ISSUE TITLE
Wifi connection error: BLE timing configuration incompatible with esp-idf framework

### ISSUE THREAD

**Issue by bogie** [esphome/issues#4198]
### The problem

Sadly I do not have the log output anymore, however there was an error log during wifi connection which said that non-default ble window intervals were unsupported on wifi connections. After commenting out the section under esp32_ble_tracker the connection to my wifi worked without a hitch.

This should probably be reflected in the official documentation, however this issue might be specific to the esp32-c3 boards.

### Which version of ESPHome has the issue?

2023.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP32-IDF

### Board

esp32-c3-devkitm-1

### Component causing the issue

esp32_ble_tracker

### Example YAML snippet

```yaml
esphome:
  name: esphome-web-15d560
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3  

esp32:
  board: esp32dev
  variant: ESP32C3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"   

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 172.16.2.11
    gateway: 172.16.2.1
    subnet: 255.255.255.0
    
esp32_ble_tracker:
  scan_parameters:
# Adjust timing if the defaults do not work in your environment
#    interval: 1100ms
#    window: 1100ms
    active: true

button:
  - platform: safe_mode
    name: ${display_name} (Safe Mode)

bluetooth_proxy:
  active: true
```
