### ISSUE TITLE
Get "An error occurred saving" on large yaml file

### ISSUE THREAD

**Issue by kkellner** [esphome/issues#4199]
### The problem

I was happily coding along until I seemed to have added too much yaml and the ESPHome editor stopped saving with "An error occurred saving".  I figured it was something I just added to the yaml, but it turns out if I just delete 20 lines or so of anything in the yaml, even old yaml lines, it will save.  I was using Chrome, tried  Safari just in case, but get the same error.  I'm using Studio Code Server plugin to edit the yaml as a workaround.  See Example YAML snippet below for the full yaml that produces the issue.

### Which version of ESPHome has the issue?

2023.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

ESPHome yaml editor

### Example YAML snippet

```yaml
substitutions:
  devicename: esp32n06
  friendly_name: test
  device_description: esp32n06 test

esphome:
  name: $devicename
  comment: ${device_description}
  project:
    name: "kkellner.esp32n06"
    version: "1.0.0"

esp32:
  board: esp32dev   
  framework:
    type: arduino

globals:
 # The humidity level (percent) at which the humidifier water valve turns off
 - id: humidity_target_level
   type: float
   restore_value: true
   initial_value: 34.5f
 # The amount (percent) that the humidity can drop from target level before humidifier is turned on
 - id: humidity_tolerance_level
   type: float
   restore_value: true
   initial_value: 5.0f
 # The amount of time (seconds) the fan should remain running after the humidifier water valve is turned off
 - id: humidity_turn_off_fan_delay
   type: int
   restore_value: true
   initial_value: '600'
 # Maximum amount of time (seconds) the humidifier should remain on
 - id: humidity_max_on_time
   type: int
   restore_value: true
   initial_value: '7200'
 # The amount of time (seconds) to delay before turning on humidifier after the heat comes on (if current humidity below humidity_target_level - humidity_tolerance_level)
 - id: humidity_turn_on_delay
   type: int
   restore_value: true
   initial_value: '180'


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .redacted.net
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename
    password: !secret fallback_ap_password


# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  services:
    - service: set_humidity_target_level
      variables:
        new_value: float
      then:
        - globals.set:
            id: humidity_target_level
            value: !lambda 'return new_value;'
        - sensor.template.publish:
            id: humidity_target_level_id
            state: !lambda 'return new_value;'
    - service: set_humidity_tolerance_level
      variables:
        new_value: float
      then:
        - globals.set:
            id: humidity_tolerance_level
            value: !lambda 'return new_value;'
        - sensor.template.publish:
            id: humidity_tolerance_level_id
            state: !lambda 'return new_value;'
    - service: set_humidity_turn_off_fan_delay
      variables:
        new_value: int
      then:
        - globals.set:
            id: humidity_turn_off_fan_delay
            value: !lambda 'return new_value;'
        - sensor.template.publish:
            id: humidity_turn_off_fan_delay_id
            state: !lambda 'return new_value;'
    - service: set_humidity_max_on_time
      variables:
        new_value: int
      then:
        - globals.set:
            id: humidity_max_on_time
            value: !lambda 'return new_value;'
        - sensor.template.publish:
            id: humidity_max_on_time_id
            state: !lambda 'return new_value;'
    - service: set_humidity_turn_on_delay
      variables:
        new_value: int
      then:
        - globals.set:
            id: humidity_turn_on_delay
            value: !lambda 'return new_value;'
        - sensor.template.publish:
            id: humidity_turn_on_delay_id
            state: !lambda 'return new_value;'
    - service: turn_on_humidifier_if_needed
      then:
        - script.execute: turn_on_humidifier_if_needed_script



ota:
  password: !secret ota_password

status_led:
  pin:
    number: GPIO2
    inverted: False
    
#captive_portal:

#debug:

# Enable logging
logger:
  level: DEBUG
  #level: INFO

# web_server:
#   port: 80

time:
  - platform: homeassistant
    id: homeassistant_time 

i2c:
  - id: bus_a
    sda: GPIO21 # white
    scl: GPIO22 # blue
    scan: True

text_sensor:
  # Reports the ESPHome Version with compile date
  - platform: version
    name: "${friendly_name} ESPHome Version"

  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"

  - platform: template
    name: "${friendly_name} Status"
    update_interval: 60s
    lambda: |-
      if ((App.get_app_state() & STATUS_LED_ERROR) != 0u) {
        return {"ERROR"};
      } else if ((App.get_app_state() & STATUS_LED_WARNING) != 0u) {
        return {"WARN"};
      } 
      return {"OK"};
      
sensor:
  # - platform: wifi_signal
  #   id: wifisignal
  #   name: "${friendly_name} WiFi Signal Sensor"
  #   update_interval: 15s

  - platform: uptime
    name: "${friendly_name} uptime"
    id: uptime_sensor
    filters:
    - lambda: return x / 60.0;
    unit_of_measurement: minutes
    update_interval: 60s

  - platform: template
    name: ${friendly_name} humidity_target_level
    id: humidity_target_level_id
    accuracy_decimals: 1
    device_class: humidity
    unit_of_measurement: "%"
    lambda: |-
      return (id(humidity_target_level));
    filters:
    - delta: 0.01

  - platform: template
    name: ${friendly_name} humidity_tolerance_level
    id: humidity_tolerance_level_id
    accuracy_decimals: 1
    device_class: humidity
    unit_of_measurement: "%"
    lambda: |-
      return (id(humidity_tolerance_level));
    filters:
    - delta: 0.01

  - platform: template
    name: ${friendly_name} humidity_turn_off_fan_delay
    id: humidity_turn_off_fan_delay_id
    accuracy_decimals: 0
    device_class: duration
    unit_of_measurement: seconds
    lambda: |-
      return (id(humidity_turn_off_fan_delay));
    filters:
    - delta: 0.01

  - platform: template
    name: ${friendly_name} humidity_max_on_time
    id: humidity_max_on_time_id
    accuracy_decimals: 0
    device_class: duration
    unit_of_measurement: seconds
    lambda: |-
      return (id(humidity_max_on_time));
    filters:
    - delta: 0.01

  - platform: template
    name: ${friendly_name} humidity_turn_on_delay
    id: humidity_turn_on_delay_id
    accuracy_decimals: 0
    device_class: duration
    unit_of_measurement: seconds
    lambda: |-
      return (id(humidity_turn_on_delay));
    filters:
    - delta: 0.01

  # Temperature / Humidity / Pressure sensor (i2c bme280)
  # - platform: bme280
  #   temperature:
  #     name: "${friendly_name} temperature"
  #     oversampling: 16x
  #   pressure:
  #     name: "${friendly_name} pressure"
  #   humidity:
  #     name: "${friendly_name} humidity"
  #   address: 0x76
  #   update_interval: 10s
  #   iir_filter: 16x

  # Temperature / Humidity / Pressure sensor (i2c bme280)
  - platform: bme280
    address: 0x76
    update_interval: 5s
    iir_filter: 16x
    temperature:
      name: "${friendly_name} temperature"
      oversampling: 16x
      filters:
        - filter_out: nan
        - sliding_window_moving_average:
            window_size: 6
            send_every: 6
            send_first_at: 1
        - or:
          - delta: 0.5
          - throttle: 60s
    pressure:
      name: "${friendly_name} pressure"
      filters:
        - filter_out: nan
        - sliding_window_moving_average:
            window_size: 6
            send_every: 6
            send_first_at: 1
        - or:
          - delta: 0.5
          - throttle: 60s
    humidity:
      name: "${friendly_name} humidity"
      id: humidity_current
      filters:
        - filter_out: nan
        - sliding_window_moving_average:
            window_size: 6
            send_every: 6
            send_first_at: 1
        - or:
          - delta: 0.5
          - throttle: 60s
      on_value_range:
        - above: !lambda "return id(humidity_target_level);"
          then:
          - switch.turn_off: relay_humidifier
          - delay: !lambda "return id(humidity_turn_off_fan_delay) * 1000;"
          - switch.turn_off: relay_fan


switch:
  - platform: restart
    name: "${friendly_name} restart"
    icon: "mdi:restart"

  # Heat
  - platform: gpio
    name: "${friendly_name} heat"
    icon: "mdi:fire"
    id: relay_heat
    pin: GPIO19
    inverted: true
    restore_mode: ALWAYS_OFF
    interlock: [relay_cool]

  # Fan
  - platform: gpio
    name: "${friendly_name} fan"
    icon: "mdi:fan"
    id: relay_fan
    pin: GPIO18
    inverted: true
    restore_mode: ALWAYS_OFF

  # Cool
  - platform: gpio
    name: "${friendly_name} cool"
    icon: "mdi:snowflake"
    id: relay_cool
    pin: GPIO17
    inverted: true
    restore_mode: ALWAYS_OFF
    interlock: [relay_heat, relay_humidifier]

  # Humidifier 
  - platform: gpio
    name: "${friendly_name} humidifier"
    icon: "mdi:air-humidifier"
    id: relay_humidifier
    pin: GPIO16
    inverted: true
    restore_mode: ALWAYS_OFF
    interlock: [relay_cool]
    # If the humidifier goes on, the fan should go on, however maybe we don't want to force fan
    # on because the humidifier came on because the heat came on.
    #on_turn_on:
    #- delay: 500ms
    #- switch.turn_on: relay_fan

binary_sensor:
  
  #######################
  # Inputs (optocompiler)
  #######################
  - platform: gpio
    name: "${friendly_name} heat stage 1 status"
    icon: "mdi:fire"
    pin: 
      number: GPIO26
      inverted: True
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - switch.turn_off: relay_cool
        # Delay before we check for humidity level (lambda value must return value in milliseconds)
        - delay: !lambda "return id(humidity_turn_on_delay) * 1000;"
        - script.execute: turn_on_humidifier_if_needed_script


  - platform: gpio
    name: "${friendly_name} fan status"
    icon: "mdi:fan"
    pin: 
      number: GPIO27
      inverted: True
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 10ms
  
  - platform: gpio
    name: "${friendly_name} cool status"
    icon: "mdi:snowflake"
    pin: 
      number: GPIO14
      inverted: True
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - switch.turn_off: relay_heat
          
  - platform: gpio
    name: "${friendly_name} heat stage 2 status"
    icon: "mdi:fire-alert"
    pin: 
      number: GPIO12
      inverted: True
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - switch.turn_off: relay_cool

# Example configuration entry
script:
  - id: turn_on_humidifier_if_needed_script
    then:
    - lambda: |-
        if (id(humidity_current).state < (id(humidity_target_level) - id(humidity_tolerance_level)) ) {
          id(relay_humidifier).turn_on();
          id(relay_fan).turn_on();
          ESP_LOGI("heat_stage_1", "Turn humidifier on with current humidity level %f", (id(humidity_current).state) );
        }
```
