### ISSUE TITLE
matrix_keypad: requires that pins support output when not needed

### ISSUE THREAD

**Issue by Meetsch** [esphome/issues#4200]
### The problem

Using the matrix_keypad with ESP32 pins 34~39 (input only) it uselessly complains that the pin "does not support output pin mode".
But input only should be sufficient when the keypad has no LEDs (as the vast majority of keypads...).
Expected behavior: able to use input pins only.

### Which version of ESPHome has the issue?

2023.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

matrix_keypad

### Example YAML snippet

```yaml
#Keypad
#https://esphome.io/components/matrix_keypad.html
matrix_keypad:
  id: keypad
  rows:
    - pin: 34
    - pin: 35
    - pin: 32
    - pin: 33
  columns:
    - pin: 25
    - pin: 26
    - pin: 27
    - pin: 14
  keys: "123A456B789C*0#D"
  has_diodes: false
#https://esphome.io/components/key_collector.html
key_collector:
  - id: pincode_reader
    source_id: keypad
    min_length: 4
    max_length: 4
    end_keys: "#"
    end_key_required: true
    back_keys: "D"
    clear_keys: "C"
    allowed_keys: "0123456789"
    timeout: 10s
    on_progress:
      - logger.log:
          format: "input progress: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]
    on_result:
      - logger.log:
          format: "input result: '%s', started by '%c', ended by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)", "(end == 0 ? '~' : end)" ]
    on_timeout:
      - logger.log:
          format: "input timeout: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]
```

### Anything in the logs that might be useful for us?

```txt
matrix_keypad: [source /config/esphome/esphome-alarm-keypad.yaml:109]
  - id: keypad
    rows: 
      - 
        GPIO34 (34-39) does not support output pin mode.
        pin: 34
      - pin: 35
      - pin: 32
      - pin: 33
    columns: 
      - pin: 25
      - pin: 26
      - pin: 27
      - pin: 14
    keys: 123A456B789C*0#D
    has_diodes: False
```
