### ISSUE TITLE
"generate" global variable name inside a script?

### ISSUE THREAD

**Issue by cvjensen** [esphome/issues#4201]
### The problem

I want to be able to reuse this script to change multiple global variables, 
but I dont know how to change global variables when I cannot hardcode their name inside the function . 

Its a little hard to explain but I'm having multiple lightXX_common_state where XX is their unique integer.

```
globals:
  - id: light1_common_state
    type: int
    restore_value: no
    initial_value: "-1"
```

I really would like to be able to change the global variable
Inside the script:

```
script:
  - id: update_common_states
    parameters:
      sensor: string
      state: int
    mode: queued
    then:
      - if:
          condition:
            lambda: return (light_common_state < 0);
          then:
            - lambda: |-
                  //Are there any way to generate the "id(" + light_name + "_common_state)"
                  //So I can change the value of the global variable
```

I'm calling the script like so:

`- lambda: id(update_light)->execute(id(light1_common_state), "light1");`

Are there any way to "generate" the global variable name inside a script?
I know I can make XX if statements but are there a smarter way ?

### Which version of ESPHome has the issue?

Version: 2022.12.8

### What type of installation are you using?

pip

### What platform are you using?

ESP32
