### ISSUE TITLE
can't ping or visit device web server, but logging in ESPHome is normal

### ISSUE THREAD

**Issue by mac-city** [esphome/issues#4204]
### The problem

this issue is now over a year old, and is the same case with all my ESPHome devices.  I can no longer ping or reach the web server, yet device logs show up normally and it works fine in HA as well.  this is just a minor irritation

### Which version of ESPHome has the issue?

2023.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP8266

### Board

esp01_1m

### Example YAML snippet

```yaml
## LOHAS RGBW Smart Bulb with ESPHome

esphome:
  name: lohas19
  platform: ESP8266
  board: esp01_1m
  includes:
    - copychan.h



wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: redacted
    gateway: redacted
    subnet: redacted
    dns1: redacted

# Enable logging and direct connect to change firmware 
web_server:
  port: 80
  
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"


# Enable MQTT if you are using it over the HA API
#mqtt:
#  broker: '192.168.1.x'
#  username: 'MQTT_User'
#  password: 'MQTT_Password'

ota:
  
my9231:
 data_pin: GPIO13  
 clock_pin: GPIO15  
 num_channels: 6
 num_chips: 2 
 
output:
  - platform: my9231
    id: output_blue
    channel: 3
  - platform: my9231
    id: output_red
    channel: 5
  - platform: my9231
    id: output_green
    channel: 4
  - platform: my9231
    id: output_cw1
    channel: 1
  - platform: my9231
    id: output_cw2
    channel: 2
  - platform: custom
    type: float
    lambda: |-
      auto *copy = new CopyOutput();
      copy->channel_a = id(output_cw1);
      copy->channel_b = id(output_cw2);
      return {copy}; 
    outputs:
    - id: cw

light:
  - platform: rgbw
    name: "Lohas19"
    default_transition_length: 0s
    red: output_red
    green: output_green
    blue: output_blue
    white: cw
```
