### ISSUE TITLE
State topic option ignored for custom cover

### ISSUE THREAD

**Issue by definitio** [esphome/issues#421]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Python virtual environment

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**Affected component:**

https://esphome.io/components/cover/custom.html

**Description of problem:**
Custom cover publishes state to `<TOPIC_PREFIX>/<COMPONENT_TYPE>/<COMPONENT_NAME>/position/state`, that can't be changed via `state_topic` option, it does nothing.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
cover:
  - platform: custom
    lambda: |-
      auto custom_cover = new CustomCover();
      App.register_component(custom_cover);
      return {custom_cover};
    covers:
      - name: Cover
        state_topic: <room>/<device>/state
        command_topic: <room>/<device>/set
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
