### ISSUE TITLE
Cannot install lib

### ISSUE THREAD

**Issue by ezar** [esphome/issues#422]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

LibraryManager

**Description of problem:**
LibraryManager: Installing Roomba
Downloading...
Error: Can not unpack file '/data/roomba/.piolibdeps/_tmp_installing-7MVJnf-package/Roomba-1.4.zip'

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: roomba
  platform: ESP8266
  board: esp01_1m
  includes:
    - includes/ESPHomeRoombaComponent.h
  libraries:
    - Roomba=https://www.dropbox.com/s/hpesby96dhceyhw/Roomba-1.4.zip
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
