### ISSUE TITLE
Waveshare E-paper Images rendered as black squares

### ISSUE THREAD

**Issue by JeroenTuinstra** [esphome/issues#4226]
### The problem

Since version 2023.2.3 (not sure it started there, because I only update my firmware when necessary), images are rendered as black squares. These are PNG with a transparency layer. Before they would render correctly.

So the image is loaded as such: 

```
image:
  - file: "images/restafval2.png"
    id: Lrestafvalpic
    type: TRANSPARENT_BINARY
```
Then it is called upon like such in the display section:
```
it.image(255, 450, id(Lrestafvalpic));
```
This generates a black square.
This is the actual image used: 
![restafval2](https://user-images.githubusercontent.com/47460053/220464296-cc2c626f-e927-432a-acee-50e9fc66dde4.png)
This is the result:
![IMG_1486](https://user-images.githubusercontent.com/47460053/220464524-e1b4cddd-a53f-4666-898a-b0e24e873120.JPG)

### Which version of ESPHome has the issue?

2023.2.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.2.3

### What platform are you using?

ESP32

### Board

Firebeetle32

### Component causing the issue

display/it.image

### Example YAML snippet

```yaml
image:
  - file: "images/restafval2.png"
    id: Lrestafvalpic
    type: TRANSPARENT_BINARY

display:
  - platform: waveshare_epaper
    cs_pin: 22
    dc_pin: 21
    busy_pin: 5
    reset_pin: 13
    model: 7.50in-hd-b
    update_interval: never
    reset_duration: 2ms
    rotation: 90°
    id: epaper_display
    lambda: |-
      it.image(255, 450, id(Lrestafvalpic));
```

### Anything in the logs that might be useful for us?

```txt
No errors in the log.
```
