### ISSUE TITLE
single setup MAX7219 Digit Display - Not working

### ISSUE THREAD

**Issue by FS-MBG** [esphome/issues#4230]
### The problem

I would like to operate my own 7-segment display on a NodeMCU, i.e. with a MAX7219 or MAX7221 chip and some 7-segment digits. Connected via ESPHome integration in Home Assistant.

1. In the first attempt I had a MAX7221 on the breadboard connected via SDI to the NodeMCU, everything dark...no displays.

2. As a test for SDI, I connected a ready to use MAX7219 Led Module 8 Digit 7-Segment display to SDI of the NodeMCU, code unchanged...works!

3. Another test, a test program (Arduino IDE) on Arduino Uno only with SDI library (no other LED libraries) connected to the SDI interface on the breadboard ... works perfect!

From this I concluded that the ESPHome MAX7219 platform and MAX7221 are incompatible.

4. Today I got a MAX7219 chip. Results identical to 1. and 2. The chip does not react in the ESPHome environment.

any idea and advice welcome
Thanks in advance
Frank

### Which version of ESPHome has the issue?

2023.2.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP8266

### Board

NodeMCU Lua Lolin V3 Module ESP8266 ESP-12F WIFI

### Component causing the issue

max7219

### Example YAML snippet

```yaml
esp8266:
  board: nodemcuv2 #NodeMCU Lolin V3
...
spi:
  clk_pin:  D5 #GPIO14
  mosi_pin: D7 #GPIO13

display:
  - platform: max7219
    cs_pin: D8 #GPIO15
    num_chips: 1
    lambda: |-
      it.print("0.15"); # test figure
```

### Anything in the logs that might be useful for us?

```txt
no logs
```
