### ISSUE TITLE
can't set unique device name for adopted device when dev file exists with original name OR project name overrides import name

### ISSUE THREAD

**Issue by clomads** [esphome/issues#4239]
### The problem

I have a device yaml setup in the dashboard that's never been flashed directly which is my working/dev file. I've been downloading the bin files to flash via web.esphome.io - I have name_add_mac_suffix set to true and it works fine except for adopting back into ESPHome as a unique device. 

The MAC extension is shown up until given the option to rename, then it resets to the original non-appended name. Here's the kicker though: I can't even rename it something completely different.  It always reverts, tho the yaml file name has the mac appended.

I also noticed that the animation plays on the card for my working/dev file, not the newly added device.

For example:
PwrTool 500 is the default name and a device shows as PwrTool 500 12345x 
Adoption name change option defaults to same, but anything I put in there is resets to PwrTool 500 (pwrtool500-12345x.yaml)
Animation plays on original PwrTool 500

I originally thought it was because I was using substitutions, so I went through all the combinations I could of name and friendly_name I could, but it always works the same. 

The biggest issue with this is that the install process compiles with a MAC address, but the name staying without it means that mDNS stalls out looking for the wrong device name.

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.02.5

### What platform are you using?

ESP32

### Board

ESP32-C3 dev kit clone

### Example YAML snippet

```yaml
substitutions:
  # name: pwrtool500
  # fname: "PwrTool 500"
  project_name: "vdbxio.PwrTool 500"
  project_version: "0.9.1"
  
esphome:
  name: pwrtool500
  friendly_name: PwrTool 500
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://vdbxio/pwrtools/pt500/pwrtool500.yaml@main
  import_full_config: true
```

### Additional information

OK, so I just wrote this all up and it looks like it might be taking from the project name.

I noticed it was adopting fine on an older install (22.12.x), but friendly_name wasn't added until this month so I decided to update that one, but after updating, it does the same thing, but I wasn't using friendly_name and still got a capitalized and spaced PwrTool 500 as the name.

 I recompiled without the project info lines and now it's not even showing up in ESPHome dash on either install so IDK...
