### ISSUE TITLE
esp8266_restore_from_flash not working in 1.13.5

### ISSUE THREAD

**Issue by heidecjj** [esphome/issues#424]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, esp01_1m

**Affected component:**

[RGBWW Light](https://esphome.io/components/light/rgbww.html)

Other components that can store their state to flash might be affected as well.

**Description of problem:**
My RGBWW Lights do not restore their state after powerloss in ESPHome 1.13.5, but they do restore their state after powerloss in ESPHome 1.12.2.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: lumiman00
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: qio
  esp8266_restore_from_flash: true

light:
  - platform: rgbww
    name: "lamp00_light00"
    id: this_light
    red: pwm_red
    green: pwm_green
    blue: pwm_blue
    cold_white: pwm_cold
    warm_white: pwm_warm
    cold_white_color_temperature: 153 mireds
    warm_white_color_temperature: 500 mireds
    # I've tried with and without the next line
    # restore_mode: RESTORE_DEFAULT_ON
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
I've had `esp8266_restore_from_flash` set to `true` for all of my experiments. I appears that states are not being written to or read from flash in 1.13.5. Here are the steps I took to come to this conclusion:
- Upload yaml with 1.12.2
- Set light color to purple
- Power cycle light (it came back on as purple, 1.12.2 works)
- Upload yaml with 1.13.5 (`restore_mode` set to `RESTORE_DEFAULT_ON')
- After uploading 1.13.5, the light stayed purple
- Set light color to green
- Power cycle light (it came back on as white, 1.13.5 does not appear to read flash to restore light state)
- Set light color to blue
- Upload yaml with 1.12.2 (making sure to comment out `restore_mode` line)
- After uploading 1.12.2, the light changed colors to purple without me changing any colors. This indicates that 1.13.5 never overwrote the place in flash where 1.12.2 saved the light's state.
- Power cycle light (it came back on as purple, 1.12.2 works)

I observed the same behavior when I had `restore_mode` commented out in my yaml for 1.13.5.
