### ISSUE TITLE
iTag doesn't work with bluetooth proxy active: true

### ISSUE THREAD

**Issue by Protoncek** [esphome/issues#4240]
### The problem

Today i tried to enable "bluetooth proxy" active connection:
```
bluetooth_proxy:
  active: true
```
and if i have it enabled my iTag doesn't work...esphome's log output also says that it's not connected. If i comment out (=delete)  "active: true" it works again.

I tried with esp-idf platform and it works, so only problem is, as it seems, arduino platform.

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP32

### Board

ESP32 DEVKITV1

### Example YAML snippet

```yaml
esphome:
  name: bt-esp32-klet
  platform: ESP32
  board: esp32dev
  comment: BLE proxy

esp32_ble_tracker:  
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

#working version has active commented out:
bluetooth_proxy:
#  active: true

ble_client:
  # MAC address of your device/tag
  - mac_address: FF:FF:10:11:98:E1
    #FF:FF:10:10:B1:02 = drugi tag
    id: itag_red

binary_sensor:
  - platform: template
    id: red_button
    name: "Rdeč iTag"
    filters:
      delayed_off: 200ms    

# ------------------------------------------------------------------------------ SENSORs
sensor: 
#------------ BLE tipka --------------------     
  - platform: ble_client
    type: characteristic
    ble_client_id: itag_red
    name: "Rdeča iTag tipka"
    service_uuid: 'ffe0'
    characteristic_uuid: 'ffe1'
    notify: true
#    internal: true
    update_interval: never
    on_notify:
      then:
        - binary_sensor.template.publish:
            id: red_button
            state: ON
        - binary_sensor.template.publish:
            id: red_button
            state: OFF
        
# ------------ indikacija BATERIJE BLE tipke in signala----------------
  - platform: ble_client
    type: characteristic
    ble_client_id: itag_red
    name: "Rdeča iTag baterija"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    icon: 'mdi:battery'
    unit_of_measurement: '%'

  - platform: ble_client
    type: rssi
    ble_client_id: itag_red
    name: "Rdeča iTag tipka RSSI"
```

### Additional information

working version with "esp-idf" has this main config:
```
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: latest
    
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false
```
