### ISSUE TITLE
esp32dev don't connect to wifi

### ISSUE THREAD

**Issue by Ardaganbao** [esphome/issues#4242]
### The problem

Not able to match Wi-Fi network
then since all version from last Decembers 

working on ESPHOME 2022.11.4

config below is the auto generated one from ESPHOME

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

last one not beta

### What platform are you using?

ESP32

### Board

esp32dev AZ-delivery EPS32-WROOM-32

### Component causing the issue

esphome 

### Example YAML snippet

```yaml
esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "syA4BrHTZM0FwhwKQTOUnc92fbKNnq2BbRlSFgxR99Y="

ota:
  password: "84b09f341deeb3a721619f10ec6177ac"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "gxMOmISSL17D"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
[D][wifi:450]: - 'fox_dent' (70:4F:57:9E:B5:49) ▂▄▆█
[W][wifi:455]: No matching network found!
[D][wifi:386]: Starting scan...
[D][wifi:401]: Found networks:
[D][wifi:450]: - 'fox_dent' (70:4F:57:9E:B5:49) ▂▄▆█
[W][wifi:455]: No matching network found!
[D][wifi:386]: Starting scan...
[D][wifi:401]: Found networks:
[D][wifi:450]: - 'fox_dent' (70:4F:57:9E:B5:49) ▂▄▆█
[W][wifi:455]: No matching network found!
[D][wifi:386]: Starting scan...
[D][wifi:401]: Found networks:
[D][wifi:450]: - 'fox_dent' (70:4F:57:9E:B5:49) ▂▄▆█
[W][wifi:455]: No matching network found!
```

### Additional information

my wifi is call fox_dent
