### ISSUE TITLE
Differential control with two adjustable sensors, is that possible?

### ISSUE THREAD

**Issue by judie07** [esphome/issues#4249]
### A question/problem
Not 100% sure this is a bug, but i read through the important information in climate action vs climate mode. For a differential control, a second temperature is necessary, but since this must come from a sensor, the "default_target_temperature" that can be set via the frontend is not targeting.

„Differential control = keeping the temperature constant between two sensors.“

What I have already tried (without success) ->
default_target_temperature: _${default_target_temp}_
or
default_target_temperatur: _!lambda |-
                                   return id(setp).state;  ==> "This option is not templatable!"

**The background** is the Control of a Solar Pump which should enable a "sliding" operation of the Collector.

Keeping the Temperature Difference between e.g. TC and TR constant leads to a "gliding" operation of the Collector. Operation of the Collector. If TK decreases as a result of decreasing irradiation, the Difference between TK and TR also decreases. Difference between TK and TR decreases. The Controller then lowers the speed, which reduces the residence time of the time of the medium in the Collector and thus increases the difference TK - TR.

### Which version of ESPHome has the issue?

v2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.2.5

### What platform are you using?

ESP8266

### Board

WeMosD1 R2

### Component causing the issue

Climate Component - PID Climate

### Example YAML snippet

```yaml
....
captive_portal:
############################################
substitutions:
  devicename: solartec
  default_target_temp: '22 °C'
### Steuerung PWM Ausgang D5    
output:
  - platform: esp8266_pwm
    pin: D5
    frequency: 500Hz
    id: ventcontrol
    inverted: True
#### PID-Regelung Solar-S1 auf RL-S2
climate:
  - platform: pid
    visual:
      min_temperature: 5 °C
      max_temperature: 95 °C
      temperature_step: 1 °C 
    name: "PID Solar Controller"
    id: pid_solar
    sensor: sols1
    default_target_temperature: ${default_target_temp}
    heat_output: ventcontrol
    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301
      output_averaging_samples: 5      
      derivative_averaging_samples: 5  
    deadband_parameters:
      threshold_high: 0.5°C     
      threshold_low: -0.5°C
sensor:
### Sensors to Read PID information into Home Assistant ###
  - platform: homeassistant
    name: "Solar S1"
    entity_id: sensor.kollekt
    id: sols1
```
