### ISSUE TITLE
Daly BMS - Daly Charging MOS problem at two uart

### ISSUE THREAD

**Issue by marcinbc** [esphome/issues#4257]
### The problem

With two declared uart there is a problem with the Daly Charging MOS switches. Exactly the function uart.write: does not know to which uart to write. In addition, the bally BMS address function is missing, in the case of two BMS devices

### Which version of ESPHome has the issue?

Current version: 2023.2.4 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.2.5

### What platform are you using?

ESP32

### Board

esp32 wroom

### Component causing the issue

daly BMS uart.write:

### Example YAML snippet

```yaml
uart:
  - id: uart_1 #bms
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 9600
    rx_buffer_size: 512

  - id: uart_2 #modbus pzem004
    tx_pin: GPIO16
    rx_pin: GPIO17
    baud_rate: 9600
  
modbus:
  uart_id: uart_2
 # flow_control_pin: GPIO5
  id: modbus_2 # needed only for multiple buses


daly_bms:
  update_interval: 30s
  uart_id: uart_1
```

### Additional information

![Przechwycenie obrazu ekranu_2023-02-28_17-02-24](https://user-images.githubusercontent.com/72081001/221909426-82856590-8d99-446c-bc27-13f363e0ef69.png)

**Comment by randybb** [comment]
```yaml
  - uart.write:
      id: uart_1
      data: [...]
```
https://esphome.io/components/uart.html#uart-write-action
