### ISSUE TITLE
MCP23016 component communication issues

### ISSUE THREAD

**Issue by netixx** [esphome/issues#4259]
### The problem

While testing the mcp23016 component with the example config, I cannot get the output to trigger.

Digging into the datasheet here: https://docs.rs-online.com/9db4/0900766b80d770fa.pdf, page 13, it states:
> The MCP23016 has twelve 8-bit registers. They are configured to operate as six 16-bit register pairs, supporting the device’s 16 bit port. These pairs are formed based on their functions (e.g., GP0 and GP1 are grouped together). The I2C commands apply to one register pair to provide faster access. The first data byte following a command byte is written into the register pointed to by the command byte, while the second data is written into another register in the same pair. For example, if the first byte is sent to OLAT1 (command byte 03h), the next data byte will be written into the second register of that pair, OLAT0. If the first byte is written to OLAT0 (command byte 02h), the second byte will be written to OLAT1.

however, in the code, we only send a single byte for each registry.

### Which version of ESPHome has the issue?

2022.11.14

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

lolin-d32

### Component causing the issue

mcp23016

### Example YAML snippet

```yaml
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a
  frequency: 100kHz


# Example configuration entry
mcp23016:
  - id: mcp23016_hub
    address: 0x20
    i2c_id: bus_a

logger:
  level: VERY_VERBOSE

# Individual outputs
switch:
  - platform: gpio
    name: "MCP23016 Pin #0"
    pin:
      mcp23016: mcp23016_hub
      # Use pin number 0
      number: 0
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "MCP23016 Pin #1"
    pin:
      mcp23016: mcp23016_hub
      # Use pin number 0
      number: 1
      mode:
        output: true
      inverted: false
```

### Anything in the logs that might be useful for us?

```txt
I reworked the code, and had success with the following (I'm not particularely proud of the implementation :)):

#include "mcp23016.h"
#include "esphome/core/log.h"
#include <cstdio>

namespace esphome {
namespace mcp23016 {

static const char *const TAG = "mcp23016";

void MCP23016::setup() {
  ESP_LOGCONFIG(TAG, "Setting up MCP23016...");
  uint8_t iocon;
  if (!this->read_reg_(MCP23016_IOCON0, &iocon)) {
    this->mark_failed();
    return;
  }

  // Read current output register state
  this->read_reg_(MCP23016_OLAT0, &this->olat_0_);
  this->read_reg_(MCP23016_OLAT1, &this->olat_1_);

  // all pins input
  this->write_reg_(MCP23016_IODIR0, 0xFFFF);
  //this->write_reg_(MCP23016_IODIR1, 0xFF);
}
bool MCP23016::digital_read(uint8_t pin) {
  uint8_t bit = pin % 8;
  uint8_t reg_addr = pin < 8 ? MCP23016_GP0 : MCP23016_GP1;
  uint8_t value = 0;
  this->read_reg_(reg_addr, &value);
  return value & (1 << bit);
}
void MCP23016::digital_write(uint8_t pin, bool value) {
  this->update_reg_(pin, value, MCP23016_OLAT0);
}
void MCP23016::pin_mode(uint8_t pin, gpio::Flags flags) {
  if (flags == gpio::FLAG_INPUT) {
    this->update_reg_(pin, true, MCP23016_IODIR0);
  } else if (flags == gpio::FLAG_OUTPUT) {
    this->update_reg_(pin, false, MCP23016_IODIR0);
  }
}
float MCP23016::get_setup_priority() const { return setup_priority::BUS; }
bool MCP23016::read_reg_(uint8_t reg, uint8_t *value) {
  if (this->is_failed())
    return false;

  return this->read_byte(reg, value);
}
bool MCP23016::write_reg_(uint8_t reg, uint16_t value) {
  if (this->is_failed())
    return false;

  return this->write_byte_16(reg, value);
}
void MCP23016::update_reg_(uint8_t pin, bool pin_value, uint8_t reg_addr) {
  uint16_t reg_value = 0;
  // pin=0 bit=8
  // pin=1 bit=9
  // pin=8 bit=0
  // pin=9 bit=1
  uint8_t bit = pin < 8 ? 8 + pin : pin-8;
  if (reg_addr == MCP23016_OLAT0) {
    reg_value = (this->olat_0_ << 8) + this->olat_1_;
  } else {
    uint8_t reg_msb = 0;
    uint8_t reg_lsb = 0;
    this->read_reg_(reg_addr, &reg_msb);
    this->read_reg_(reg_addr+1, &reg_lsb);
    reg_value = (reg_msb << 8) + reg_lsb;
  }

  if (pin_value) {
    reg_value |= 1 << bit;
  } else {
    reg_value &= ~(1 << bit);
  }

  this->write_reg_(reg_addr, reg_value);

  if (reg_addr == MCP23016_OLAT0) {
    this->olat_0_ = (uint8_t)((reg_value & 0xFF00) >> 8);
  } else if (reg_addr == MCP23016_OLAT1) {
    this->olat_1_ = (uint8_t)(reg_value & 0x00FF);
  }
}

void MCP23016GPIOPin::setup() { pin_mode(flags_); }
void MCP23016GPIOPin::pin_mode(gpio::Flags flags) { this->parent_->pin_mode(this->pin_, flags); }
bool MCP23016GPIOPin::digital_read() { return this->parent_->digital_read(this->pin_) != this->inverted_; }
void MCP23016GPIOPin::digital_write(bool value) { this->parent_->digital_write(this->pin_, value != this->inverted_); }
float MCP23016GPIOPin::get_setup_priority() const { return setup_priority::HARDWARE_LATE; }
std::string MCP23016GPIOPin::dump_summary() const {
  char buffer[32];
  snprintf(buffer, sizeof(buffer), "%u via MCP23016", pin_);
  return buffer;
}

}  // namespace mcp23016
}  // namespace esphome

```
```


### Additional information

I also had a final issue with priorities, where the pin setup was firing *before* the component setup itself. This meant that the pin mode was reset, and the code wasn't working still (fixed in my implementation).
