### ISSUE TITLE
Device name used instead of hostname, results in device unreachable & Backend error code: 0000

### ISSUE THREAD

**Issue by kine90** [esphome/issues#4267]
### The problem

When I updated the following configuration (I copied only the interesting pars of the yaml) I got the alert that a hostname including "_" is not reccomended.
As I have a line setting the hostname in my wifi component, I tought it was enough to change that parameter to solve the problem, so I replaced "${device_name}.iot" with "nedis-switch-01.iot" and restarted the update.
After the OTA completed succesfully, ESPhome dashboard could not reach the device to pull logs .The error reported that it was still looking for "nedis_switch_01.iot", which makes me think the hostname parameter in WiFi component was ignored. Meanwhile, the device was perfectly connected to my HomeAssistant and working properly.

```
substitutions:
  device_name: nedis_switch_01

esphome:
  name: "${device_name}"
  build_path: ".esphome/build/nedis_switch_01"
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
  #min_version: 2023.3.0

libretuya:
  board: wb3s
  framework:
    version: 0.0.0
    source: https://github.com/kuba2k2/libretuya.git
  lt_config: {}
  loglevel: WARN
  sdk_silent: true
  gpio_recover: true

captive_portal:

web_server:
  port: 80

wifi:
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: ##EDITED##
  domain: .iot
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  networks:
    - ssid: #########
      password: ########
      priority: 0.0
  use_address: "${device_name}.iot"
```

### Which version of ESPHome has the issue?

v2023.1.0-dev Documentation

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3

### What platform are you using?

ESP8266

### Board

LibreTuya wb3s

### Component causing the issue

WiFi

### Example YAML snippet

```yaml
substitutions:
  device_name: nedis_switch_01

esphome:
  name: "${device_name}"
  build_path: ".esphome/build/nedis_switch_01"
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
  #min_version: 2023.3.0

libretuya:
  board: wb3s
  framework:
    version: 0.0.0
    source: https://github.com/kuba2k2/libretuya.git
  lt_config: {}
  loglevel: WARN
  sdk_silent: true
  gpio_recover: true

captive_portal:

web_server:
  port: 80

wifi:
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: ##EDITED##
  domain: .iot
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  networks:
    - ssid: #########
      password: ########
      priority: 0.0
  use_address: "${device_name}.iot"
```
```


### Anything in the logs that might be useful for us?

```txt
Please check which information is used to generate the URL to connect to the devices. Under default configurations it makes sense to look for ${device_name}.local, but if a different hostname is specified in WiFi component, that hostname must be used to connect.
```
