### ISSUE TITLE
Cannot have a component named the "Friendly Name"

### ISSUE THREAD

**Issue by jjross** [esphome/issues#4269]
### The problem

When you add the friendly name into the configuration it’s automatically prefixed to the Home Assistant entity name and entity ID of the exposed components.  This is expected.  

The problem is that when you specify the "name" of a component to be the same as the friendly name (because you would like the component to have the same name as the friendly name) then the system will duplicate the friendly name in both the entity ID and the entity name fields.  

ESPHome should not prefix the name of a component with the friendly name if the component's name is the same as the friendly name.  

For example, if I have a simple smart plug with a single relay and I would like to use it to control a fan I might give the device the friendly name "Bedroom Fan" and name the relay "Bedroom Fan".  Currently ESPHome will prefix the name with the friendly name so the entity becomes "Bedroom Fan Bedroom Fan" with an entity ID of "switch.bedroom_fan_bedroom_fan".

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.1

### What platform are you using?

ESP8266

### Board

Sonoff S31

### Example YAML snippet

```yaml
#Sonoff S31 Lite

substitutions:
  device_name: bedroom-fan #change
  friendly_name: Bedroom Fan #change
  comment: Sonoff S31 Lite | IP 192.168.30.184
  icon: "mdi:fan"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${comment}

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_NoT_ssid
  password: !secret wifi_NoT_password
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:
  baud_rate: 0  # (UART logging interferes with cse7766)

# Enable Home Assistant API
api:
  encryption: 
    key: !secret esp_home_api_encryption

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    id: button
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
  - platform: status
    name: Status

switch:
  - platform: gpio
    name: ${friendly_name}
    icon: ${icon}
    pin: GPIO12
    id: relay

  - platform: restart
    name: Reboot

  - platform: safe_mode
    name: Safe Mode

status_led:
  pin:
    number: 13
    mode: OUTPUT
    inverted: true

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
```
