### ISSUE TITLE
Cannot turn off bulb

### ISSUE THREAD

**Issue by Elkropac** [esphome/issues#4282]
### The problem

When sending turn off from HA, my light bulb does not turn off.
In logs, i can see, it receives
```
[22:53:58][D][light:035]: 'zemismart_bulb_a19_002_light_rgbw' Setting:
[22:53:58][D][light:046]:   State: OFF
```
But it stays on.
Also some color/brightness changes are laggy, i have to push it multiple times to be done.

I have two zemismart bulbs with the same config and it happens on both of them (i have had third, but it ended in bootloop after upgrade in december)

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.03

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

light tgbw

### Example YAML snippet

```yaml
light:
  - platform: rgbw
    id: light_01
    name: "${dev_name}_light_rgbw"
    default_transition_length: 0s
    color_interlock: true
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    effects: !include ../../.common/light_effects_01.yaml

my9231:
  data_pin: GPIO13
  clock_pin: GPIO15
  num_channels: 4
  num_chips: 1
#  bit_depth: 14

output:
  - platform: my9231
    id: output_blue
    channel: 1
  - platform: my9231
    id: output_red
    channel: 3
  - platform: my9231
    id: output_green
    channel: 2
  - platform: my9231
    id: output_white
    channel: 0
```

### Anything in the logs that might be useful for us?

```txt
it receives

[22:53:58][D][light:035]: 'zemismart_bulb_a19_002_light_rgbw' Setting:
[22:53:58][D][light:046]:   State: OFF
```
```


### Additional information

These are mine configuration from past, i have configured it using packages since then and added some light effects

https://www.esphome-devices.com/devices/Zemismart-Bulb-BR30
https://www.esphome-devices.com/devices/Zemismart-Bulb-A19
