### ISSUE TITLE
Can not set fan speed to 0

### ISSUE THREAD

**Issue by camohob** [esphome/issues#4285]
### The problem

When I set the speed from 2 (for example) to 0, the value is sent to the output and returned back to HA unchanged (2).
Why [minimum value](https://github.com/esphome/esphome/blame/1b328da26581a201c9aaaef7be9c7910797ee2db/esphome/components/fan/fan.cpp#L42) is 1? HA supports the value 0 but bounces when I try to set it to 0 and returns it back unchanged.

![Screenshot_1](https://user-images.githubusercontent.com/7923965/223382341-4b4511ae-83e8-482b-b2f4-c65bc10ce6af.png)

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.1

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

fan

### Example YAML snippet

```yaml
fan:
  - platform: speed
    id: fan_in
    output: fan_in_output
    name: "THE Fan"
    speed_count: 3
```
