### ISSUE TITLE
Inkplate 10 ver 1.3 new io expanders

### ISSUE THREAD

**Issue by nettle-m** [esphome/issues#4287]
### The problem

Soldered started delivering Inkplate 10 in version 1.3
which uses different gpio expanders -PCAL6416AHF
This version of inkplate could be identified by missing three touch buttons in front, which older revision had.
Older version of inkplate 10 had a mcp23017 expanders which are supported by ESPhome.

But PCAL6416AHF arent. This result in inplate 10 version 1.3 not working with esphome:

```
[E][component:113]: Component mcp23xxx_base was marked as failed.
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: *****
[D][wifi:386]: Starting scan...
[W][inkplate:265]: Power supply not detected
```

This is due to fact that power supply enable and config pins are connected via those expanders and with PCAL6416AHF expander not supported, power to display is not enabled.

Could anyone please add PCAL6416AHF expanders?
I am willing to test it and help if my knowledge be enough.
here is ver 1.3 schematics
https://github.com/SolderedElectronics/Soldered-Inkplate-10-hardware-design/blob/main/OUTPUTS/V1.3.0/Soldered%20Inkplate%2010%20Schematics.pdf

and here is software from Soldered which i found
https://github.com/SolderedElectronics/Soldered-PCAL6416A-IO-Expander-Arduino-Library

### Which version of ESPHome has the issue?

2023.2.4 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.1

### What platform are you using?

ESP32

### Board

Inkplate

### Component causing the issue

expander/display

### Example YAML snippet

```yaml
esphome:
  name: inkplate10-test
  friendly_name: inkplate10_test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "**"

ota:
  password: "**"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Inkplate10-Test Fallback Hotspot"
    password: "**"

captive_portal:


i2c:
  
mcp23017:
  - id: mcp23017_hub
    address: 0x20

display:
- platform: inkplate6
  id: inkplate_display
  model: inkplate_10
  update_interval: 60s

  ckv_pin: 32
  sph_pin: 33
  gmod_pin:
    mcp23xxx: mcp23017_hub
    number: 1
  gpio0_enable_pin:
    mcp23xxx: mcp23017_hub
    number: 8
  oe_pin:
    mcp23xxx: mcp23017_hub
    number: 0
  spv_pin:
    mcp23xxx: mcp23017_hub
    number: 2
  powerup_pin:
    mcp23xxx: mcp23017_hub
    number: 4
  wakeup_pin:
    mcp23xxx: mcp23017_hub
    number: 3
  vcom_pin:
    mcp23xxx: mcp23017_hub
    number: 5


  lambda: |-
    it.fill(COLOR_ON);
    it.line(0, 0, 1200, 825, COLOR_OFF);
    it.line(1200, 0, 0, 825, COLOR_OFF);
```
