### ISSUE TITLE
replacing character with a line break "\n" not returning line

### ISSUE THREAD

**Issue by 1liminal1** [esphome/issues#4292]
### The problem

Reopening issue as found doco and still does not work. 

Have added the correct replace filter to the YAML as per the ESPHome documentation provided for text sensors. No errors, It replaces the comma with seemingly a blank character as it appears on the display. But does not perform the linebreak. Values are printed in one line across the screen. as you can see in the "Shopping List" portion of the screen shot. 

```
  - platform: homeassistant
    entity_id: sensor.epshome_shopping_list
    id: alexa_shopping_list
    on_value:
      then:
         - lambda: 'id(data_updated) = true;'
    filters:
      - substitute:
          ", -> \n"
```
![image](https://user-images.githubusercontent.com/10505942/224463045-11a6c99e-ef76-4e05-b8fc-ba2e28706a61.png)

Just to add, here is the output of the sensor to see the comma

![image](https://user-images.githubusercontent.com/10505942/224463194-e0819ec1-089d-45c8-a06b-8ac5e2bf5318.png)

### Which version of ESPHome has the issue?

v2023.2.4 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant Core 2023.3.1

### What platform are you using?

ESP32

### Board

Generic Dev Board

### Component causing the issue

text_sensor

### Example YAML snippet

```yaml
above
```
