### ISSUE TITLE
error when want install "WiFi Signal Sensor" in esphome

### ISSUE THREAD

**Issue by lysiong** [esphome/issues#4298]
### The problem

ESPHOME always come out error when want install "WiFi Signal Sensor"

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.3.3

### What platform are you using?

ESP32

### Board

generic

### Example YAML snippet

```yaml
INFO Reading configuration /config/esphome/esp32-proxy1.yaml...
INFO Configuration is valid!
substitutions:
  name: esp32-proxy1
  friendly_name: Bluetooth Proxy
esphome:
  name: esp32-proxy1
  friendly_name: Bluetooth Proxy
  name_add_mac_suffix: false
  project:
    name: esphome.bluetooth-proxy
    version: '1.0'
  build_path: .esphome/build/esp32-proxy1
  platformio_options: {}
  includes: []
  libraries: []
  min_version: 2023.2.4
esp32:
  board: esp32dev
  framework:
    version: 4.4.2
    sdkconfig_options: {}
    advanced:
      ignore_efuse_mac_crc: false
    source: ~3.40402.0
    platform_version: platformio/espressif32 @ 5.2.0
    type: esp-idf
  variant: ESP32
wifi:
  ap:
    ap_timeout: 1min
  domain: .local
  reboot_timeout: 15min
  power_save_mode: LIGHT
  fast_connect: false
  enable_btm: false
  enable_rrm: false
  networks:
  - ssid: xxx
    password: xxx
    priority: 0.0
  use_address: esp32-proxy1.local
api:
  encryption:
    key: xxx
  port: 6053
  password: ''
  reboot_timeout: 15min
logger:
  baud_rate: 115200
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
ota:
  safe_mode: true
  port: 3232
  reboot_timeout: 5min
  num_attempts: 10
improv_serial: {}
dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
  import_full_config: false
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
    duration: 5min
    continuous: true
bluetooth_proxy:
  active: true
  cache_services: true
  connections:
  - {}
  - {}
  - {}
button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic
  disabled_by_default: false
  icon: mdi:restart-alert
  device_class: restart
sensor:
- platform: wifi_signal
  name: WiFi Signal Sensor
  update_interval: 60s
  disabled_by_default: false
  force_update: false
  unit_of_measurement: dBm
  accuracy_decimals: 0
  device_class: signal_strength
  state_class: measurement
  entity_category: diagnostic
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esp32-proxy1.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-proxy1 (board: esp32dev; framework: espidf; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40402.0 (4.4.2) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- Improv @ 1.2.3
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_connection.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_frame_helper.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_pb2.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_pb2_service.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_server.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/list_entities.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/proto.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/subscribe_state.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/user_services.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/bluetooth_proxy/bluetooth_connection.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/button/button.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/esp32/gpio.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/esp32/preferences.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/esp32_ble/ble.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/esp32_ble/ble_advertising.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/esp32_ble/ble_uuid.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/esp32_ble_client/ble_characteristic.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/esp32_ble_client/ble_client_base.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/esp32_ble_client/ble_service.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/improv_base/improv_base.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/improv_serial/improv_serial_component.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/logger/logger.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/md5/md5.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/mdns/mdns_component.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/mdns/mdns_esp32.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/mdns/mdns_esp8266.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/mdns/mdns_rp2040.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/network/util.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/ota/ota_backend_arduino_esp32.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/ota/ota_backend_arduino_esp8266.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/ota/ota_backend_arduino_rp2040.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/ota/ota_backend_esp_idf.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/ota/ota_component.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/safe_mode/button/safe_mode_button.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/socket/bsd_sockets_impl.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/socket/lwip_raw_tcp_impl.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/socket/socket.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/wifi/wifi_component.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/wifi/wifi_component_esp32_arduino.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/wifi/wifi_component_esp8266.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/wifi/wifi_component_esp_idf.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/wifi/wifi_component_pico_w.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/core/application.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/core/component.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/core/component_iterator.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/core/controller.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/core/helpers.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/core/log.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/core/scheduler.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/core/util.o
Compiling /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o
Linking /data/esp32-proxy1/.pioenvs/esp32-proxy1/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection17send_sensor_stateEPNS_6sensor6SensorEf+0x8): undefined reference to `esphome::sensor::Sensor::has_state() const'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection16send_sensor_infoEPNS_6sensor6SensorE+0x10): undefined reference to `esphome::sensor::Sensor::get_unit_of_measurement[abi:cxx11]()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection16send_sensor_infoEPNS_6sensor6SensorE+0x14): undefined reference to `esphome::sensor::Sensor::get_accuracy_decimals()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection16send_sensor_infoEPNS_6sensor6SensorE+0x18): undefined reference to `esphome::sensor::Sensor::get_device_class[abi:cxx11]()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection16send_sensor_infoEPNS_6sensor6SensorE+0x1c): undefined reference to `esphome::sensor::Sensor::get_state_class()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_connection.o: in function `esphome::api::APIConnection::send_sensor_state(esphome::sensor::Sensor*, float)':
/config/esphome/.esphome/build/esp32-proxy1/src/esphome/components/api/api_connection.cpp:414: undefined reference to `esphome::sensor::Sensor::has_state() const'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_connection.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/data/cache/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:1366: undefined reference to `esphome::sensor::Sensor::get_unit_of_measurement[abi:cxx11]()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/components/api/api_connection.o: in function `esphome::api::APIConnection::send_sensor_info(esphome::sensor::Sensor*)':
/config/esphome/.esphome/build/esp32-proxy1/src/esphome/components/api/api_connection.cpp:426: undefined reference to `esphome::sensor::Sensor::get_accuracy_decimals()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/esphome/.esphome/build/esp32-proxy1/src/esphome/components/api/api_connection.cpp:427: undefined reference to `esphome::sensor::Sensor::get_device_class[abi:cxx11]()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/esphome/.esphome/build/esp32-proxy1/src/esphome/components/api/api_connection.cpp:429: undefined reference to `esphome::sensor::Sensor::get_state_class()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o:(.literal._Z5setupv+0xb8): undefined reference to `vtable for esphome::wifi_signal::WiFiSignalSensor'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o:(.literal._Z5setupv+0xbc): undefined reference to `vtable for esphome::wifi_signal::WiFiSignalSensor'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o:(.literal._Z5setupv+0x104): undefined reference to `esphome::sensor::Sensor::Sensor()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o:(.literal._Z5setupv+0x108): undefined reference to `esphome::sensor::Sensor::set_device_class(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o:(.literal._Z5setupv+0x10c): undefined reference to `esphome::sensor::Sensor::set_state_class(esphome::sensor::StateClass)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o:(.literal._Z5setupv+0x110): undefined reference to `esphome::sensor::Sensor::set_unit_of_measurement(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o:(.literal._Z5setupv+0x114): undefined reference to `esphome::sensor::Sensor::set_accuracy_decimals(signed char)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o: in function `esphome::safe_mode::SafeModeButton::SafeModeButton()':
/config/esphome/.esphome/build/esp32-proxy1/src/esphome/components/safe_mode/button/safe_mode_button.h:10: undefined reference to `esphome::sensor::Sensor::Sensor()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o: in function `setup()':
/config/esphome/.esphome/build/esp32-proxy1/src/main.cpp:215: undefined reference to `esphome::sensor::Sensor::set_device_class(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/esphome/.esphome/build/esp32-proxy1/src/main.cpp:216: undefined reference to `esphome::sensor::Sensor::set_state_class(esphome::sensor::StateClass)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/esphome/.esphome/build/esp32-proxy1/src/main.cpp:217: undefined reference to `esphome::sensor::Sensor::set_unit_of_measurement(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/main.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()':
/data/cache/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:657: undefined reference to `esphome::sensor::Sensor::set_accuracy_decimals(signed char)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/core/controller.o:(.literal._ZN7esphome10Controller16setup_controllerEb+0x8): undefined reference to `esphome::sensor::Sensor::add_on_state_callback(std::function<void (float)>&&)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/esp32-proxy1/.pioenvs/esp32-proxy1/src/esphome/core/controller.o: in function `esphome::Controller::setup_controller(bool)':
/config/esphome/.esphome/build/esp32-proxy1/src/esphome/core/controller.cpp:29: undefined reference to `esphome::sensor::Sensor::add_on_state_callback(std::function<void (float)>&&)'
collect2: error: ld returned 1 exit status
*** [/data/esp32-proxy1/.pioenvs/esp32-proxy1/firmware.elf] Error 1
========================= [FAILED] Took 21.05 seconds =========================

```
