### ISSUE TITLE
Pi Pico W not rebooting after esphome update to 2023.3.0

### ISSUE THREAD

**Issue by freddiemare** [esphome/issues#4308]
### The problem

I only updated my pi pico w devices and they all stopped rebooting after updating esphome to 2023.3.0
I have one device still working and am busy trying to see the difference in breaking changes that were implemented any guide to what to look out for will be greatly helpful since I have no idea wah to look for besides the break-in change implementations.

### Which version of ESPHome has the issue?

2023.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.0

### What platform are you using?

RP2040

### Board

pi pico w

### Component causing the issue

dont know what component since no reboot

### Example YAML snippet

```yaml
esphome:
  name: plot35gate
  project:
    name: "plot35.gate"
    version: "1.0.2"

  on_boot:
    priority: -100.0 
    then:
       - switch.turn_on: gate_board_LED_switch
       - switch.turn_on: gate_light
    
rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:
 # level: DEBUG
  
# Enable Home Assistant API
api:
#  encryption:
#    key: !secret api_Gate_key
  reboot_timeout: 60sec 
  
ota:
  password: !secret ota_Gate_password

wifi:
  reboot_timeout: 30s
  output_power: 20db
  power_save_mode: none
  networks:
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2
      #fast_comnect: true
      bssid: 56:AF:97:A3:47:EE
      manual_ip:
        # Set this to the IP of the ESP
        static_ip: 192.168.2.131
        # Set this to the IP address of the router. Often ends with .1
        gateway: 192.168.2.1
        #The subnet of the network. 255.255.255.0 works for most home networks.
        subnet: 255.255.255.0
        dns1: 1.1.1.1
        dns2: 192.168.2.1

    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2
      #fast_connect: true
      bssid: F4:E5:F2:AC:52:9F
      hidden: True
      manual_ip:
        # Set this to the IP of the ESP
        static_ip: 192.168.2.131
        # Set this to the IP address of the router. Often ends with .1
        gateway: 192.168.2.1
        #The subnet of the network. 255.255.255.0 works for most home networks.
        subnet: 255.255.255.0
        dns1: 1.1.1.1
        dns2: 192.168.2.1
  ap:
    ssid: "Plot35Gate"
    password: "123456"

output:
  # Built-in LED
  - platform: gpio
    pin:
      number: 32 
      mode: output
    id: gate_board_LED

    # Relay 1 Outputs
  - platform: gpio
    pin: 
      number: 12  
      mode: output
    id: gpio_12
    inverted: true

    # Relay 2 Outputs
  - platform: gpio
    pin: 
      number: 13 
      mode: output
    id: gpio_13
    inverted: true

    # Relay 3 Outputs
  - platform: gpio
    pin: 
      number: 14 
      mode: output
    id: gpio_14
    inverted: true

    # Relay 4 Outputs Gate Lights
  - platform: gpio
    pin: 
      number: 15 
      mode: output
    id: gpio_15
    inverted: true

switch:
  - platform: output
    id: gate_board_LED_switch
    output: gate_board_LED
    name: "Gate Board LED"

  - platform: restart
    id: gate_restart
    name: "Gate Restart"

  - platform: output
    id: gate_light
    output: gpio_15
    name: Gate Light

  - platform: gpio
    pin: 12
    id: gate_open_trigger
    name: "Gate Open"
    icon: "mdi:gate"
    inverted: true
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: gate_open_trigger

  - platform: gpio
    pin: 13
    id: pedestrian_gate_open_trigger
    name: "Gate Open Pedestrian"
    icon: "mdi:gate"
    inverted: true
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: pedestrian_gate_open_trigger

binary_sensor:
  - platform: status
    name: "Gate Connection Status"
    id: gate_connection_status

  - platform: gpio
    id: gate_bell
    pin:
      number: 7
      inverted: true
      mode:
        input: true
        pullup: true
    icon:  "mdi:bell"
    name: "Gate Bell"

  - platform: gpio
    id: gate_IRBC_alarm
    pin:
      number: 8
      inverted: true
      mode:
        input: true
        pullup: true
    icon:  "mdi:gate-alert"
    name: "IRBC Alarm"

  - platform: gpio
    id: gate_status
    pin:
      number: 9
      inverted: true
      mode:
        input: true
        pullup: true
    icon:  "mdi:gate"
    name: "Gate Status"

  - platform: gpio
    id: tamper_alarm
    pin:
      number: 10
      inverted: false
      mode:
        input: true
        pullup: true
    icon:  "mdi:alarm-light"
    name: "Tamper Alarm"

  - platform: gpio
    id: gate_pir_movement
    pin:
      number: 11
      inverted: true
      mode:
        input: true
        pullup: true
    icon:  "mdi:motion-sensor"
    name: "Gate PIR Movement"
    device_class: motion

text_sensor:
  - platform: wifi_info
    ip_address:
      name: Gate IP Address
    ssid:
      name: Gate Connected SSID
    bssid:
      name: Gate Connected BSSID
    mac_address:
      name: Gate Mac Wifi Address
    scan_results:
      name: Gate Latest Scan Results

sensor:      
  - platform: duty_cycle
    update_interval: 1s
    pin: 
      number: 9
      inverted: yes
      #mode: INPUT_PULLUP
      mode:
        input: true
        pulldown: true
    name: "Gate Status DC"
    id: gate_status_dc
    internal: false

#         Duty Cycle    Period / s
  - platform: template
    update_interval: 1s
    name: "Gate Status TM"
    id: gate_state
    lambda: |-
      if (id(gate_status_dc).state == 0) {
        return 0;
      } else if (id(gate_status_dc).state < 20) {
        return 1;
      } else if (id(gate_status_dc).state < 60) {
        return 2;
      } else {
        return 3;
      }
    
    ## ADC for Battery Voltage Sensor    
  - platform: adc
    id: gate_battery_voltage_sensor
    name: "Gate Battery Voltage"
    pin: 26
    unit_of_measurement: "V"
    update_interval: 1s
    filters:
      - calibrate_linear:
          - 0.4776 ->  4.826
          #- 0.9876 -> 10.009
          #- 1.1852 -> 12.011
          #- 1.2842 -> 13.012
          - 1.8684 -> 18.946
      - median:
          window_size: 5
          send_every: 4
          send_first_at: 2
      - exponential_moving_average:
          alpha: 0.1
          send_every: 1

  - platform: internal_temperature
  #- platform: adc
    id: gate_CPU_Temp
    #pin: TEMPERATURE
    name: "Gate CPU Core Temperature"
    update_interval: 30s
    unit_of_measurement: "°C"
    entity_category: "diagnostic"
    device_class: "volume"
    state_class: "measurement"
    filters:
      - lambda: return 27 - (x - 0.706f) / 0.001721f;
     
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    id: gate_wifi_signal_db
    name: "Gate WiFi Signal dB"
    update_interval: 5s
    unit_of_measurement: "dB"
    entity_category: "diagnostic"
    device_class: "SIGNAL_STRENGTH"
    state_class: "measurement"
    
  - platform: copy # Reports the WiFi signal strength in %
    source_id: gate_wifi_signal_db
    name: "Gate WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);

    unit_of_measurement: "%"
    entity_category: "diagnostic"
```

### Anything in the logs that might be useful for us?

```txt
No logs since device is not booting
```

### Additional information

The yaml code was working on the previous version of esphome but stopped rebooting after update this morning.
