### ISSUE TITLE
Haier Climate not working

### ISSUE THREAD

**Issue by pruwait** [esphome/issues#4312]
### The problem

For my haier-as09tl4hra CRC ERROR, commands not working.
I have CRC error after some actions.

This works well: https://github.com/Oksion/esphaier

### Which version of ESPHome has the issue?

2023.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.0

### What platform are you using?

ESP8266

### Board

d-mini

### Example YAML snippet

```yaml
climate:
  - platform: haier
    name: Haier AC
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH
    update_interval: 10s      

uart:
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 9600
```

### Anything in the logs that might be useful for us?

```txt
crc error
```
