### ISSUE TITLE
[ezo] Bug in EzoCommandType enum

### ISSUE THREAD

**Issue by alfredopironti** [esphome/issues#4321]
### The problem

I'm having issues triggering the ezo callbacks (specifically "on_calibration"). Looking at the code, I identified the following, which seems a mistake:

https://github.com/esphome/esphome/blob/a31fb3c987b7011b7ccb7735f8210f2feaff1d90/esphome/components/ezo/ezo.h#L18

According to C++ rules, EZO_CALIBRATION gets implicitly assigned the value "4" (previous enum value +1), which is the same of the explicitly assigned EZO_SLEEP.

I believe the code ends up never reading the response from an issued EZO_CALIBRATION command, because looking at this line:
https://github.com/esphome/esphome/blob/a31fb3c987b7011b7ccb7735f8210f2feaff1d90/esphome/components/ezo/ezo.cpp#L67
the command gets confused with EZO_SLEEP, and it is removed from the queue before the reply can be parsed.

The fix should be simple, by updating the enum definition such that every item has a unique value.

However, I'm not submitting a PR as I don't have a test environment. Available if I can support in any other way.

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

ezo

### Example YAML snippet

```yaml
button: # Used to trigger sending the I2C message
  - platform: template
    name: "Retrieve pH calibration status"
    on_press:
      - lambda: |-
          id(ezo_ph).get_calibration();

text_sensor: # Used to see the outcome
  - platform: template
    name: "pH calibration status"
    id: ph_calibration_status

sensor:
  - platform: ezo
    id: ezo_ph
    address: 99
    name: "Swimming pool pH"
    unit_of_measurement: "pH"
    accuracy_decimals: 2
    update_interval: 10s
    on_calibration: # Note this callback never gets triggered
      - text_sensor.template.publish:
          id: ph_calibration_status
          state: "test state"
```
