### ISSUE TITLE
Failure to compile due to C header file

### ISSUE THREAD

**Issue by aaronpowell** [esphome/issues#4344]
### The problem

I went to install an update to one of my ESP8266 devices but when it starts compiling the payload there's an error that starts with:

```
src/esphome/core/helpers.h:550:41: error: invalid initialization of non-const reference of type 'esphome::Mutex&' from an rvalue of type '<brace-enclosed initializer list>'
```

Here's the full log:

```
INFO Reading configuration /config/esphome/1921681179.yaml...
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Generating C++ source...
INFO Compiling app...
Processing aaron-office-background (board: nodemcuv2; framework: arduino; platform: platformio/espressif8266 @ 2.6.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- FastLED @ 3.3.2
Compiling /data/aaron-office-background/.pioenvs/aaron-office-background/src/esphome/components/api/api_connection.cpp.o
Compiling /data/aaron-office-background/.pioenvs/aaron-office-background/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/aaron-office-background/.pioenvs/aaron-office-background/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/aaron-office-background/.pioenvs/aaron-office-background/src/esphome/components/api/api_pb2_service.cpp.o
In file included from src/esphome/components/api/proto.h:5:0,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_pb2.cpp:3:
src/esphome/core/helpers.h: In constructor 'esphome::LockGuard::LockGuard(esphome::Mutex&)':
src/esphome/core/helpers.h:550:41: error: invalid initialization of non-const reference of type 'esphome::Mutex&' from an rvalue of type '<brace-enclosed initializer list>'
   LockGuard(Mutex &mutex) : mutex_{mutex} { mutex_.lock(); }
                                         ^
In file included from src/esphome/components/api/proto.h:5:0,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome/components/api/api_connection.cpp:1:
src/esphome/core/helpers.h: In constructor 'esphome::LockGuard::LockGuard(esphome::Mutex&)':
src/esphome/core/helpers.h:550:41: error: invalid initialization of non-const reference of type 'esphome::Mutex&' from an rvalue of type '<brace-enclosed initializer list>'
   LockGuard(Mutex &mutex) : mutex_{mutex} { mutex_.lock(); }
                                         ^
In file included from src/esphome/components/api/api_frame_helper.cpp:5:0:
src/esphome/core/helpers.h: In constructor 'esphome::LockGuard::LockGuard(esphome::Mutex&)':
src/esphome/core/helpers.h:550:41: error: invalid initialization of non-const reference of type 'esphome::Mutex&' from an rvalue of type '<brace-enclosed initializer list>'
   LockGuard(Mutex &mutex) : mutex_{mutex} { mutex_.lock(); }
                                         ^
In file included from src/esphome/components/api/proto.h:5:0,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_pb2_service.h:5,
                 from src/esphome/components/api/api_pb2_service.cpp:3:
src/esphome/core/helpers.h: In constructor 'esphome::LockGuard::LockGuard(esphome::Mutex&)':
src/esphome/core/helpers.h:550:41: error: invalid initialization of non-const reference of type 'esphome::Mutex&' from an rvalue of type '<brace-enclosed initializer list>'
   LockGuard(Mutex &mutex) : mutex_{mutex} { mutex_.lock(); }
                                         ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-nonnull-compare" [enabled by default]
*** [/data/aaron-office-background/.pioenvs/aaron-office-background/src/esphome/components/api/api_pb2_service.cpp.o] Error 1
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-nonnull-compare" [enabled by default]
*** [/data/aaron-office-background/.pioenvs/aaron-office-background/src/esphome/components/api/api_frame_helper.cpp.o] Error 1
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-nonnull-compare" [enabled by default]
*** [/data/aaron-office-background/.pioenvs/aaron-office-background/src/esphome/components/api/api_connection.cpp.o] Error 1
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-nonnull-compare" [enabled by default]
*** [/data/aaron-office-background/.pioenvs/aaron-office-background/src/esphome/components/api/api_pb2.cpp.o] Error 1
========================== [FAILED] Took 7.22 seconds ==========================
```

### Which version of ESPHome has the issue?

2023.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.6

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

core or FastLED

### Example YAML snippet

```yaml
esphome:
  name: aaron-office-background

esp8266:
  board: nodemcuv2
  framework:
    version: 2.7.4

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<snip>"

ota:
  password: "<snip>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "<snip>"
    password: "<snip>"

captive_portal:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D2
    num_leds: 100
    rgb_order: GRB
    name: "Aaron's office background"
    effects:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
```

### Anything in the logs that might be useful for us?

```txt
I updated HA Core (from 2023.3.5) yesterday, and ESPHome update was 2 days ago (from 2023.3.0), and I hadn't installed any updates on this board for quite a while so it was possible a few "revisions" behind.
```

**Comment by aaronpowell** [comment]
Doing some more testing, it looks like the problem is using the `board` of `nodemcuv2` and the legacy framework together that's the problem.

**Comment by petergr20** [comment]
Same issue on board esp01_1m

[10:07:51][I][app:102]: ESPHome version 2023.2.4 compiled on Feb 28 2023, 17:23:39 --> OK

When try to compile with 

[10:08:29][I][app:102]: ESPHome version 2023.3.1 compiled on Mar 25 2023, 10:01:22 --> KO

**Comment by bonzai86** [comment]
I have the same issue on 2023.3.1 (introducing https://github.com/esphome/esphome/pull/4602)
Hope we're not out of luck, because we're using old arduino version due support of fastled.

**Comment by sparkydave1981** [comment]
The same problem has been reported in [this thread](https://github.com/esphome/issues/issues/3084):

https://github.com/esphome/issues/issues/3084#issuecomment-1473933233

**Comment by sparkydave1981** [comment]
I just tested out trying to compile the code for one of my devices which uses the older framework  on ESPhome version 2023.3.2 and it compiled without error.

```
esp8266:
  board: esp01_1m
  framework:
    version: 2.7.4
```
