### ISSUE TITLE
Warning on climate-bang compilation

### ISSUE THREAD

**Issue by Masterz69** [esphome/issues#4345]
### The problem

Using climate ```bang-bang```  controller.

On compiling project getting warnings like
```
Compiling /data/esp8266/.pioenvs/esp8266/src/esphome/components/climate/climate_traits.cpp.o
src/esphome/components/climate/climate.cpp: In member function 'void esphome::climate::Climate::save_state_()':
src/esphome/components/climate/climate.cpp:339:54: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct esphome::climate::ClimateDeviceRestoreState'; use assignment or value-initialization instead [-Wclass-memaccess]
  339 |   memset(&state, 0, sizeof(ClimateDeviceRestoreState));
      |                                                      ^
In file included from src/esphome/components/climate/climate.cpp:1:
src/esphome/components/climate/climate.h:125:8: note: 'struct esphome::climate::ClimateDeviceRestoreState' declared here
  125 | struct ClimateDeviceRestoreState {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
```

Issue stated as fixed https://github.com/esphome/issues/issues/3053#issue-1141382702, but still appears.

### Which version of ESPHome has the issue?

2023.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.5

### What platform are you using?

ESP8266

### Board

esp8285, d1_mini

### Component causing the issue

climate bang-bang controller

### Example YAML snippet

```yaml
climate:
  - platform: bang_bang
    name: ${climate_text}
    id: climate_${id}
    internal: False
    sensor: ${climate_sensor}
    visual:
      min_temperature:  ${visual_min}
      max_temperature:  ${visual_max}
      temperature_step: ${visual_step}
#    on_boot_restore_from: memory
    default_target_temperature_low: ${target_low}
    default_target_temperature_high: ${target_high}
    heat_action:
      - switch.turn_on: ${switch_on}
    idle_action:
      - switch.turn_off: ${switch_off}
```
