### ISSUE TITLE
CT clamp calibrate calibration issues. 

### ISSUE THREAD

**Issue by Billium28** [esphome/issues#4347]
### The problem

I thought I got it squared away w a space heater and a watt meter that shows amps. The watt meter is plugged in along w the CT clamp around the same power wire. Should be the same rating. 
I can fix esphome with this Calc. 
0.037 -> 11.6

That then showed correct in Esphome at about 11.6amps. Then I tried my laptop charger, it's off by double, much closer than before, but double. Esphome shows like 0.212A and watt meter shows 0.35.

Do I put in both these under the linear Calc? Or what happens if I get rid of all of it? How did I fix one thing but it shows so off when trying on a second device?

This will eventually go on a water heater line in breaker box so trying to get this right before installing it. 

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.03.2

### What platform are you using?

ESP32

### Board

Mini d2

### Component causing the issue

Code

### Example YAML snippet

```yaml
sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    id: waterheater_current
    name: "Waterheater Current"
    update_interval: 10s
    filters:
      - calibrate_linear:
          - 0 -> 0
          # Measured value of 0 maps to 0A
          # Known load: 11.6A
          # Value shown in logs: 0.037
          - 0.037 -> 11.6
    unit_of_measurement: 'A'

  - platform: adc
    pin: A0
    id: adc_sensor
    
  - platform: total_daily_energy
    name: "Total Daily Power"
    power_id: waterheater_current

  - platform: template
    id: _power
    name: "Waterheater Power"
    lambda: return id(waterheater_current).state * 122.5.0 / 1000; #Power = Current * Voltage (so change 230 to whatever your mains voltage is)
    unit_of_measurement: 'kW'
    update_interval: 10s
```
