### ISSUE TITLE
H801 RGBWW HA API connection constantly reconnects

### ISSUE THREAD

**Issue by Rothammel** [esphome/issues#4350]
### The problem

when the H801 is switched on, the API constantly reconnects. when the H801 is switched off, everything works normally.

![image](https://user-images.githubusercontent.com/42540450/227656693-a952857e-9baf-41f4-9f22-249d59ea8f7e.png)

### Which version of ESPHome has the issue?

2023.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.3

### What platform are you using?

ESP8266

### Board

H801

### Component causing the issue

RGBWW

### Example YAML snippet

```yaml
esphome:
  name: h801-stube
  friendly_name: h801-stube

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BqHhqa10yWIx......................JhL10I="

ota:
  password: "8d2e4d3c.................2b6b4d9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "H801-Stube Fallback Hotspot"
    password: "5SZLRbCt5CIq"

captive_portal:

web_server:
  port: 80
    
output:
  - platform: esp8266_pwm
    pin: 12
    #frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    #frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    #frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    #frequency: 1000 Hz
    id: pwm_w1
  - platform: esp8266_pwm
    pin: 4
    #frequency: 1000 Hz
    id: pwm_w2

light:
  - platform: rgbww
    name: "H801 Light"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    cold_white: pwm_w1
    warm_white: pwm_w2
```
