### ISSUE TITLE
ezo send custom failing compile

### ISSUE THREAD

**Issue by alexs-sentrytechnology** [esphome/issues#4352]
### The problem

I get a compile error when trying to use the ezo platform with some of the member functions. send_custom and set_led_state trigger a compile error, whereas set_tempcomp_value does not.

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.6

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

ezo

### Example YAML snippet

```yaml
esphome:
  name: ec-monitor

esp8266:
  board: esp01_1m

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - platform: ezo
    id: ec_ezo
    address: 0x64
    unit_of_measurement: "CN"
    on_value:
    - lambda : id(ec_ezo).send_custom("L,0");
```

### Anything in the logs that might be useful for us?

```txt
I get the following error message when trying to compile:

/config/esphome/reef-ec-monitor.yaml: In lambda function:
/config/esphome/reef-ec-monitor.yaml:17:15: error: 'class esphome::ezo::EZOSensor' has no member named 'send_custom'
   17 |     - lambda : id(ec_ezo).send_custom("L,0");
      |               ^~~~~~~~~~~

I've tried some of the other commands and some (such as set_tempcomp_value) seem to compile file ok, whereas others (set_led_state) also trigger this compile error.
```
