### ISSUE TITLE
[AsyncTCP.cpp:966] _poll(): pcb is NULL

### ISSUE THREAD

**Issue by kuradi** [esphome/issues#4359]
### The problem

couple wemos boards cant connect to wifi.

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.6

### What platform are you using?

ESP32

### Board

wemos mini

### Example YAML snippet

```yaml
esphome:
  name: vesikook

esp32:
  board: nodemcu-32s
  framework:
    type: arduino


wifi:
  ssid: "5E_iot"
  password: "****"
  reboot_timeout: 15min
  fast_connect: True
  manual_ip:
    static_ip: 192.168.11.105
    gateway: 192.168.11.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 8.8.4.4
logger:
  level: VERY_VERBOSE

ota:
  password: *******

mqtt:
  broker: 192.168.1.187
  port: 1883
  username: *******
  password: *******
  reboot_timeout: 15min
  discovery: False
  discovery_retain: False
  topic_prefix: HA/Vesi2

switch:
  - platform: restart
    name: "Restart vesikook"  

time:
  - platform: sntp
    id: aeg

sensor:
  - platform: pulse_counter
    pin: 32
    name: "Vesi 1. korrus_kook"
    id: vesi_1_korrus_kook
    update_interval: 5s
    filters:
    - lambda: return (x / 660.0);  # 660 = 11 * 60 sec
    unit_of_measurement: "L/sec"
    total:
      name: "Total Vesi 1. korrus_kook"
      unit_of_measurement: "L"
      accuracy_decimals: 3
      filters:
        - lambda: return (x / 660.0);    
    
  - platform: pulse_counter
    pin: 25
    name: "Vesi 1. korrus_soe"
    id: vesi_1_soe
    update_interval: 5s
    filters:
    - lambda: return (x / 660.0);  # 660 = 11 * 60 sec
    unit_of_measurement: "L/sec"
    total:
      name: "Total Vesi 1. korrus_soe"
      unit_of_measurement: "L"
      accuracy_decimals: 3
      filters:
        - lambda: return (x / 660.0);    

  - platform: total_daily_energy
    name: "Total Daily Vesi 1 korrus soe"
    power_id: vesi_1_soe
    
  - platform: total_daily_energy
    name: "Total Daily Vesi 1. korrus kook"
    power_id: vesi_1_korrus_kook
    
  - platform: uptime
    name: Vesikook Uptime Sensor
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
                int seconds = round(id(uptime_sensor).raw_state);
                int days = seconds / (24 * 3600);
                seconds = seconds % (24 * 3600);
                int hours = seconds / 3600;
                seconds = seconds % 3600;
                int minutes = seconds /  60;
                seconds = seconds % 60;
                return (
                  (days ? to_string(days) + "d " : "") +
                  (hours ? to_string(hours) + "h " : "") +
                  (minutes ? to_string(minutes) + "m " : "") +
                  (to_string(seconds) + "s")
                ).c_str();

  - platform: wifi_signal
    name: "Vesikook SSID"
    update_interval: 60s

text_sensor:
  - platform: template
    name: Vesikook Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
    
  - platform: wifi_info
    ip_address:
      name: Vesikook IP Address
    ssid:
      name: Vesikook Connected SSID
    mac_address:
      name: Vesikook Mac Address
    scan_results:
      name: Vesikook Latest Scan Results
```

### Anything in the logs that might be useful for us?

```txt
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[     6][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[I][logger:258]: Log initialized
[VV][esp32.preferences:070]: nvs_get_blob: key: 233825507, len: 4
[C][ota:469]: There have been 3 suspected unsuccessful boot attempts.
[VV][esp32.preferences:039]: s_pending_save: key: 233825507, len: 4
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[VV][esp32.preferences:122]: Checking if NVS data 233825507 has changed
[V][esp32.preferences:125]: sync: key: 233825507, len: 4
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[VV][sensor:093]: Sensor(0x3ffb2dcc)::add_filter(0x3ffb2ef0)
[VV][sensor.filter:029]: Filter(0x3ffb2ef0)::initialize(parent=0x3ffb2dcc next=0x0)
[VV][sensor:093]: Sensor(0x3ffb2fb8)::add_filter(0x3ffb3084)
[VV][sensor.filter:029]: Filter(0x3ffb3084)::initialize(parent=0x3ffb2fb8 next=0x0)
[VV][sensor:093]: Sensor(0x3ffb31a8)::add_filter(0x3ffb32f0)
[VV][sensor.filter:029]: Filter(0x3ffb32f0)::initialize(parent=0x3ffb31a8 next=0x0)
[VV][sensor:093]: Sensor(0x3ffb33b8)::add_filter(0x3ffb3484)
[VV][sensor.filter:029]: Filter(0x3ffb3484)::initialize(parent=0x3ffb33b8 next=0x0)
[I][app:029]: Running through setup()...
[V][app:030]: Sorting components by setup priority...
[VV][scheduler:062]: set_interval(name='', interval=60000, offset=8653)
[VV][scheduler:062]: set_interval(name='update', interval=60000, offset=4989)
[VV][scheduler:062]: set_interval(name='update', interval=60000, offset=14095)
[C][pulse_counter:147]: Setting up pulse counter 'Vesi 1. korrus_kook'...
[C][pulse_counter:061]:     PCNT Unit Number: 0
[C][pulse_counter:107]:     Filter Value: 13us (val=1023)
[VV][scheduler:062]: set_interval(name='update', interval=5000, offset=460)
[C][pulse_counter:147]: Setting up pulse counter 'Vesi 1. korrus_soe'...
[C][pulse_counter:061]:     PCNT Unit Number: 1
[C][pulse_counter:107]:     Filter Value: 13us (val=1023)
[VV][scheduler:062]: set_interval(name='update', interval=5000, offset=1472)
[VV][esp32.preferences:070]: nvs_get_blob: key: 1277898224, len: 4
[V][sensor:076]: 'Total Daily Vesi 1 korrus soe': Received new state 0.000000
[D][sensor:127]: 'Total Daily Vesi 1 korrus soe': Sending state 0.00000 L/sech with 4 decimals of accuracy
[VV][esp32.preferences:039]: s_pending_save: key: 1277898224, len: 4
[VV][esp32.preferences:070]: nvs_get_blob: key: 683091181, len: 4
[V][sensor:076]: 'Total Daily Vesi 1. korrus kook': Received new state 0.000000
[D][sensor:127]: 'Total Daily Vesi 1. korrus kook': Sending state 0.00000 L/sech with 4 decimals of accuracy
[VV][esp32.preferences:039]: s_pending_save: key: 683091181, len: 4
[V][text_sensor:016]: 'Vesikook Mac Address': Received new state 9C:9C:1F:E6:76:AC
[D][text_sensor:067]: 'Vesikook Mac Address': Sending state '9C:9C:1F:E6:76:AC'
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]:   Local MAC: 9C:9C:1F:E6:76:AC
[V][esp32.preferences:058]: nvs_get_blob('452029903'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[V][wifi_esp32:039]: Enabling STA.
[   327][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 0 - WIFI_READY
[V][wifi_esp32:444]: Event: WiFi ready
[   422][V][WiFiGeneric.cpp:338] _arduino_event_cb(): STA Started
[   422][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 2 - STA_START
[V][wifi_esp32:459]: Event: WiFi STA start
[VV][scheduler:225]: Running interval 'update' with interval=60000 last_execution=4294893356 (now=437)
[V][text_sensor:016]: 'Vesikook Uptime Human Readable': Received new state 0s
[D][text_sensor:067]: 'Vesikook Uptime Human Readable': Sending state '0s'
[V][sensor:076]: 'Vesikook Uptime Sensor': Received new state 0.448000
[D][sensor:127]: 'Vesikook Uptime Sensor': Sending state 0.44800 s with 0 decimals of accuracy
[VV][scheduler:225]: Running interval '' with interval=60000 last_execution=4294898787 (now=437)
[D][esp32.preferences:113]: Saving 2 preferences to flash...
[VV][esp32.preferences:122]: Checking if NVS data 683091181 has changed
[V][esp32.preferences:136]: NVS data not changed skipping 683091181  len=4
[VV][esp32.preferences:122]: Checking if NVS data 1277898224 has changed
[V][esp32.preferences:136]: NVS data not changed skipping 1277898224  len=4
[D][esp32.preferences:142]: Saving 2 preferences to flash: 2 cached, 0 written, 0 failed
[VV][scheduler:225]: Running interval 'update' with interval=60000 last_execution=4294902462 (now=437)
[V][text_sensor:016]: 'Vesikook Uptime Human Readable': Received new state 0s
[D][text_sensor:067]: 'Vesikook Uptime Human Readable': Sending state '0s'
[VV][scheduler:225]: Running interval 'update' with interval=5000 last_execution=4294961033 (now=437)
[D][pulse_counter:180]: 'Vesi 1. korrus_soe': Total : 0 pulses
[V][sensor:076]: 'Total Vesi 1. korrus_soe': Received new state 0.000000
[VV][sensor.filter:014]: Filter(0x3ffb3484)::input(0.000000)
[VV][sensor.filter:269]: LambdaFilter(0x3ffb3484)::new_value(0.000000) -> 0.000000
[VV][sensor.filter:021]: Filter(0x3ffb3484)::output(0.000000) -> SENSOR
[D][sensor:127]: 'Total Vesi 1. korrus_soe': Sending state 0.00000 L with 3 decimals of accuracy
[VV][scheduler:225]: Running interval 'update' with interval=5000 last_execution=4294962024 (now=437)
[D][pulse_counter:180]: 'Vesi 1. korrus_kook': Total : 0 pulses
[V][sensor:076]: 'Total Vesi 1. korrus_kook': Received new state 0.000000
[VV][sensor.filter:014]: Filter(0x3ffb3084)::input(0.000000)
[VV][sensor.filter:269]: LambdaFilter(0x3ffb3084)::new_value(0.000000) -> 0.000000
[VV][sensor.filter:021]: Filter(0x3ffb3084)::output(0.000000) -> SENSOR
[D][sensor:127]: 'Total Vesi 1. korrus_kook': Sending state 0.00000 L with 3 decimals of accuracy
[  3523][V][WiFiGeneric.cpp:353] _arduino_event_cb(): STA Connected: SSID: 5E_iot, BSSID: 68:d7:9a:81:24:a5, Channel: 1, Auth: WPA_WPA2_PSK
[  3524][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
[  3527][V][WiFiGeneric.cpp:367] _arduino_event_cb(): STA Got New IP:192.168.11.105
[V][wifi_esp32:477]: Event: Connected ssid='5E_iot' bssid=68:D7:9A:81:24:A5[redacted] channel=1, authmode=WPA/WPA2 PSK
[  3560][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  3560][D][WiFiGeneric.cpp:991] _eventCallback(): STA IP: 192.168.11.105, MASK: 255.255.255.0, GW: 192.168.11.1
[V][wifi_esp32:536]: Event: Got IP static_ip=192.168.11.105 gateway=192.168.11.1
[VV][scheduler:225]: Running interval 'update' with interval=5000 last_execution=4294966033 (now=3737)
[D][pulse_counter:174]: 'Vesi 1. korrus_soe': Retrieved counter: 0.00 pulses/min
[V][sensor:076]: 'Vesi 1. korrus_soe': Received new state 0.000000
[VV][sensor.filter:014]: Filter(0x3ffb32f0)::input(0.000000)
[VV][sensor.filter:269]: LambdaFilter(0x3ffb32f0)::new_value(0.000000) -> 0.000000
[VV][sensor.filter:021]: Filter(0x3ffb32f0)::output(0.000000) -> SENSOR
[D][sensor:127]: 'Vesi 1. korrus_soe': Sending state 0.00000 L/sec with 2 decimals of accuracy
[V][sensor:076]: 'Total Daily Vesi 1 korrus soe': Received new state 0.000000
[D][sensor:127]: 'Total Daily Vesi 1 korrus soe': Sending state 0.00000 L/sech with 4 decimals of accuracy
[VV][esp32.preferences:039]: s_pending_save: key: 1277898224, len: 4
[D][pulse_counter:180]: 'Vesi 1. korrus_soe': Total : 0 pulses
[V][sensor:076]: 'Total Vesi 1. korrus_soe': Received new state 0.000000
[VV][sensor.filter:014]: Filter(0x3ffb3484)::input(0.000000)[  3829][W][AsyncTCP.cpp:966] _poll(): pcb is NULL

[VV][sensor.filter:269]: LambdaFilter(0x3ffb3484)::new_value(0.000000) -> 0.000000
[VV][sensor.filter:021]: Filter(0x3ffb3484)::output(0.000000) -> SENSOR
[D][sensor:127]: 'Total Vesi 1. korrus_soe': Sending state 0.00000 L with 3 decimals of accuracy
[V][component:204]: Component pulse_counter.sensor took a long time for an operation (0.13 s).
[V][component:205]: Components should block for at most 20-30ms.
[  4328][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
[VV][scheduler:225]: Running interval 'update' with interval=5000 last_execution=4294967024 (now=4728)
[D][pulse_counter:174]: 'Vesi 1. korrus_kook': Retrieved counter: 0.00 pulses/min
[V][sensor:076]: 'Vesi 1. korrus_kook': Received new state 0.000000
[VV][sensor.filter:014]: Filter(0x3ffb2ef0)::input(0.000000)
[VV][sensor.filter:269]: LambdaFilter(0x3ffb2ef0)::new_value(0.000000) -> 0.000000
[VV][sensor.filter:021]: Filter(0x3ffb2ef0)::output(0.000000) -> SENSOR
[D][sensor:127]: 'Vesi 1. korrus_kook': Sending state 0.00000 L/sec with 2 decimals of accuracy
[V][sensor:076]: 'Total Daily Vesi 1. korrus kook': Received new state 0.000000
[D][sensor:127]: 'Total Daily Vesi 1. korrus kook': Sending state 0.00000 L/sech with 4 decimals of accuracy
[VV][esp32.preferences:039]: s_pending_save: key: 683091181, len: 4
[D][pulse_counter:180]: 'Vesi 1. korrus_kook': Total : 0 pulses
[V][sensor:076]: 'Total Vesi 1. korrus_kook': Received new state 0.000000
[VV][sensor.filter:014]: Filter(0x3ffb3084)::input(0.000000)
[VV][sensor.filter:269]: LambdaFilter(0x3ffb3084)::new_value(0.000000) -> 0.000000[  4828][W][AsyncTCP.cpp:966] _poll(): pcb is NULL

[VV][sensor.filter:021]: Filter(0x3ffb3084)::output(0.000000) -> SENSOR
[D][sensor:127]: 'Total Vesi 1. korrus_kook': Sending state 0.00000 L with 3 decimals of accuracy
[V][component:204]: Component pulse_counter.sensor took a long time for an operation (0.13 s).
[V][component:205]: Components should block for at most 20-30ms.
[  5329][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
[  5828][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
[  6328][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
[  6828][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
[  7328][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
[  7828][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
[  8334][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
[VV][scheduler:225]: Running interval 'update' with interval=5000 last_execution=3737 (now=8737)
[D][pulse_counter:174]: 'Vesi 1. korrus_soe': Retrieved counter: 0.00 pulses/min
[V][sensor:076]: 'Vesi 1. korrus_soe': Received new state 0.000000
[VV][sensor.filter:014]: Filter(0x3ffb32f0)::input(0.000000)
[VV][sensor.filter:269]: LambdaFilter(0x3ffb32f0)::new_value(0.000000) -> 0.000000
[VV][sensor.filter:021]: Filter(0x3ffb32f0)::output(0.000000) -> SENSOR
[D][sensor:127]: 'Vesi 1. korrus_soe': Sending state 0.00000 L/sec with 2 decimals of accuracy
[V][sensor:076]: 'Total Daily Vesi 1 korrus soe': Received new state 0.000000
[D][sensor:127]: 'Total Daily Vesi 1 korrus soe': Sending state 0.00000 L/sech with 4 decimals of accuracy
[D][pulse_counter:180]: 'Vesi 1. korrus_soe': Total : 0 pulses
[V][sensor:076]: 'Total Vesi 1. korrus_soe': Received new state 0.000000
[VV][sensor.filter:014]: Filter(0x3ffb3484)::input(0.000000)
[VV][sensor.filter:269]: LambdaFilter(0x3ffb3484)::new_value(0.000000) -> 0.000000
[VV][sensor.filter:021]: Filter(0x3ffb3484)::output(0.000000) -> SENSOR[  8833][W][AsyncTCP.cpp:966] _poll(): pcb is NULL

[D][sensor:127]: 'Total Vesi 1. korrus_soe': Sending state 0.00000 L with 3 decimals of accuracy
[V][component:204]: Component pulse_counter.sensor took a long time for an operation (0.12 s).
[V][component:205]: Components should block for at most 20-30ms.
[  9334][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
[VV][scheduler:225]: Running interval 'update' with interval=5000 last_execution=4728 (now=9728)
[D][pulse_counter:174]: 'Vesi 1. korrus_kook': Retrieved counter: 0.00 pulses/min
[V][sensor:076]: 'Vesi 1. korrus_kook': Received new state 0.000000
[VV][sensor.filter:014]: Filter(0x3ffb2ef0)::input(0.000000)
[VV][sensor.filter:269]: LambdaFilter(0x3ffb2ef0)::new_value(0.000000) -> 0.000000
[VV][sensor.filter:021]: Filter(0x3ffb2ef0)::output(0.000000) -> SENSOR
[D][sensor:127]: 'Vesi 1. korrus_kook': Sending state 0.00000 L/sec with 2 decimals of accuracy
[V][sensor:076]: 'Total Daily Vesi 1. korrus kook': Received new state 0.000000
[D][sensor:127]: 'Total Daily Vesi 1. korrus kook': Sending state 0.00000 L/sech with 4 decimals of accuracy
[D][pulse_counter:180]: 'Vesi 1. korrus_kook': Total : 0 pulses
[V][sensor:076]: 'Total Vesi 1. korrus_kook': Received new state 0.000000
[VV][sensor.filter:014]: Filter(0x3ffb3084)::input(0.000000)
[VV][sensor.filter:269]: LambdaFilter(0x3ffb3084)::new_value(0.000000) -> 0.000000
[VV][sensor.filter:021]: Filter(0x3ffb3084)::output(0.000000) -> SENSOR
[D][sensor:127]: 'Total Vesi 1. korrus_kook': Sending state 0.00000 L with 3 decimals of accuracy[  9833][W][AsyncTCP.cpp:966] _poll(): pcb is NULL

[V][component:204]: Component pulse_counter.sensor took a long time for an operation (0.12 s).
[V][component:205]: Components should block for at most 20-30ms.
[ 10333][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
[ 10833][W][AsyncTCP.cpp:966] _poll(): pcb is NULL
```

### Additional information

it started when i updated to 2023.3.1. before that it worked without problems
