### ISSUE TITLE
MCP23017 hangs ESP8266

### ISSUE THREAD

**Issue by marci144** [esphome/issues#436]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io docker on Ubuntu, but I'm having the same problem compiling under python 2.7 on a win10 machine
Please provide details about your environment below this line. -->
I have esp32 running with multiple MCP boards no problem. I tried today to install on esp8266, an esp12e irst and then a d1_mini. Same story when I add the configuration of MCP23017 the microcontroller hangs during the startup phase
**ESP (ESP32/ESP8266, Board/Sonoff):**
esp12e and d1-mini
Please provide details about which ESP you're using below.
-->

**Affected component:**

**Description of problem:**
the controller hangs during start-up 

(10:59:24.065) (COM3)  ets Jan  8 2013,rst cause:4, boot mode:(3,6)<CR>
(10:59:24.170) (COM3) <CR>
(10:59:24.170) (COM3) wdt reset<CR>
(10:59:24.170) (COM3) load 0x4010f000, len 1384, room 16 <CR>
(10:59:24.170) (COM3) tail 8<CR>
(10:59:24.170) (COM3) chksum 0x2d<CR>
(10:59:24.170) (COM3) csum 0x2d<CR>
(10:59:24.170) (COM3) vbb28d4a3<CR>
(10:59:24.170) (COM3) ~ld
(10:59:24.170) (COM3) <ESC>[0;32m[I][logger:116]: Log initialized<ESC>[0m<CR>
(10:59:24.170) (COM3) <ESC>[0;35m[C][ota:364]: There have been 6 suspected unsuccessful boot attempts.<ESC>[0m<CR>

**Problem-relevant YAML-configuration entries:**
```
i2c:
  sda: 5
  scl: 6
  scan: True

mcp23017:
  - id: 'mcp_hub1'
    address: 0x20
binary_sensor: 
  - platform: gpio
    name: "luci_marci_A#0"
    pin:
      mcp23017: mcp_hub1
      number: 0
      mode: INPUT_PULLUP
      inverted: False
    internal: true
    device_class: light

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
