### ISSUE TITLE
ESP32-S2 (S2 Mini board) can't connect to WiFi 'Auth Expired'

### ISSUE THREAD

**Issue by evolucja** [esphome/issues#4368]
### The problem

Hi, recently I've received another pack of few S2 Mini boards.
Unfortunately they are probably different manufacturer and I can't get them to connect to WiFi.

I uploaded the same .bin as works on my other S2 Mini boards.

However on those new I am receiving 'Auth Expired' error.

Searched all around the internet for a solution but nothing work.

Any idea?

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.6

### What platform are you using?

ESP32

### Board

S2 mini

### Example YAML snippet

```yaml
esphome:
  name: espek-10
  comment: "xxx"
            
esp32:
  board: lolin_s2_mini
  framework:
    type: arduino  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.0.0.50
    gateway: 10.0.0.1
    subnet: 255.255.255.0
  power_save_mode: none
    
logger:

api:

debug:
  
ota:
```

### Anything in the logs that might be useful for us?

```txt
[D][wifi:401]: Found networks:
[I][wifi:445]: - 'Apek_2G' [redacted]▂▄▆█
[D][wifi:446]:     Channel: 1
[D][wifi:447]:     RSSI: -59 dB
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[D][wifi:450]: - [redacted] [redacted]▂▄▆█
[I][wifi:257]: WiFi Connecting to 'Apek_2G'...
[W][wifi_esp32:494]: Event: Disconnected ssid='Apek_2G' bssid=[redacted] reason='Auth Expired'
[W][wifi:549]: Error while connecting to network.
[W][wifi:585]: Restarting WiFi adapter...
[I][wifi:257]: WiFi Connecting to 'Apek_2G'...
[W][wifi_esp32:494]: Event: Disconnected ssid='Apek_2G' bssid=[redacted] reason='Auth Expired'
[W][wifi:549]: Error while connecting to network.
[W][wifi:585]: Restarting WiFi adapter...
```

### Additional information

Also not working when I changed WiFi config to phone hotspot.
