### ISSUE TITLE
Excessive logging from ADC on GPIO 1 with esp-idf

### ISSUE THREAD

**Issue by clinta** [esphome/issues#4374]
### The problem

When setting up an ADC sensor with esp-idf on GPIO 1, there are frequent info log messages

```
[23:53:26][I][esp-idf:000]: I (381169) gpio: GPIO[1]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 

[23:53:27][I][esp-idf:000]: I (382158) gpio: GPIO[1]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 

[23:53:27][I][esp-idf:000]: I (382160) gpio: GPIO[1]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 

[23:53:27][I][esp-idf:000]: I (382162) gpio: GPIO[1]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 

```

### Which version of ESPHome has the issue?

v2023.4.0-dev

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

esp32-c3-devkitm-1

### Component causing the issue

adc

### Example YAML snippet

```yaml
esphome:
  platformio_options:
    board_build.flash_mode: dio
  name: office-light
  comment: Office Light
  build_path: .esphome/build/office-light
  friendly_name: ''
  includes: []
  libraries: []
  name_add_mac_suffix: false
  min_version: 2023.4.0
esp32:
  framework:
    version: 4.4.4
    sdkconfig_options: {}
    advanced:
      ignore_efuse_mac_crc: false
    components: []
    source: ~3.40404.0
    platform_version: platformio/espressif32 @ 5.3.0
    type: esp-idf
  board: esp32-c3-devkitm-1
  variant: ESP32C3
logger:
  baud_rate: 0
  level: INFO
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  logs: {}
sensor:
- platform: adc
  id: light_adc
  pin:
    number: 1
    mode:
      input: true
      output: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
    drive_strength: 20.0
  name: Office Light Light Voltage
  disabled_by_default: true
  update_interval: 1s
  attenuation: auto
  on_value:
  - then:
    - sensor.template.publish:
        id: light_level
        state: !lambda |-
          return x;
  force_update: false
  unit_of_measurement: V
  accuracy_decimals: 2
  device_class: voltage
  state_class: measurement
  raw: false
- platform: template
  name: Office Light Ambient Light Level
  id: light_level
  unit_of_measurement: lx
  device_class: illuminance
  lambda: !lambda |-
    return id(light_adc).state;
  update_interval: 4294967295
  filters:
  - calibrate_polynomial:
      degree: 2
      datapoints:
      - from: 1.47
        to: 160.0
      - from: 0.9
        to: 85.0
      - from: 0.36
        to: 35.0
      - from: 0.07
        to: 4.0
      - from: 0.03
        to: 1.0
      - from: 0.0
        to: 0.0
  - delta:
    - 5.0
    - false
```
