### ISSUE TITLE
For some TM1637 versions order of the chips is reversed 'reverse_enable' needed

### ISSUE THREAD

**Issue by OPSDZ** [esphome/issues#4375]
### The problem

for some version the order of the chips is reversed so you’ll see “56781234” instead of “12345678”.
reverse_enable option is an invalid for that issue .
So if that is possible add reverse_enable option
i'll really apreciate some help on this !

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.6

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

tm1637

### Example YAML snippet

```yaml
esphome:
  name: esp-test
  platform: ESP8266
  board: nodemcuv2
wifi:
  ssid: "TP 4M"
  password: "mojaliadato544"
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails


captive_portal:

# Enable logging
logger:
  baud_rate: 0
# Enable Home Assistant API
api:

  - platform: status
    name: " esp-test-Status "


display:
    platform: tm1637
    id: tm1637_display
    clk_pin: D5
    dio_pin: D6
    inverted: True
    intensity: 6
    length: 6
    lambda: |-
     it.print("012345");
```

### Additional information

![IMG20230331013210](https://user-images.githubusercontent.com/17110456/228996967-f1bb009f-0ce5-4ba4-9b51-65d2a4e33eac.jpg)
