### ISSUE TITLE
OTA fw upgrade from 1.12.2 to 1.13.5  - devices are not coming back online

### ISSUE THREAD

**Issue by ddean6232** [esphome/issues#438]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHOME Add-on version: 1.13.5
 You are running the latest version of this add-on.
 System: HassOS 2.10  (armv7 / raspberrypi3)
 Home Assistant version: 0.94.1
 Supervisor version: 166

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff Basic, NodeMCU, WEMOS

**Affected component:**

**Description of problem:**
Upgraded ESPHOME add-on from 1.12.2 to 1.13.5 with no problems
No configuration changes to any .YAML files (included all relevant files below)
Upgraded Sonoff Basic from 1.12.2 to 1.13.5 via OTA and has not come back online, powered off for a hard reboot, still not coming back online.
Same for NodeMCU board
Same for WEMOS board.

**Problem-relevant YAML-configuration entries:**
```yaml
SONOFF BASIC
esphome:
  name: sonoff4964d4
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'xxxx'
  password: 'xxxx'
  manual_ip:
    static_ip: 192.168.0.53
    gateway: 192.168.0.1
    subnet: 255.255.255.0


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#web_server:
#  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "4964D4 Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Bedroom Lamp 4964D4"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

WEMOS D1 MINI
esphome:
  name: minitemp
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'xxxx'
  password: 'xxxxx'
  manual_ip:
    static_ip: 192.168.0.63
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#web_server:
#  port: 80

dallas:
  - pin: D1
    update_interval: 5s

sensor:
  - platform: dallas
    address: 0xAB031554A2E2FF28
    name: "Thermo Temp"
    id: thermo

switch:
  - platform: gpio
    name: "Thermo Relay"
    pin: D7
    id: relay

time:
  - platform: homeassistant
    id: mytime
    on_time:
      - seconds: 0,10,20,30,40,50
        then:
          - display.page.show_next: my_display
          - component.update: my_display
font:
  - file: "OpenSans-Regular.ttf"
    id: my_font
    size: 14

image:
  - file: "logo.png"
    id: my_image
    resize: 128x32

i2c:
  sda: D5
  scl: D4
  scan: True

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    address: 0x3C
    id: my_display
    pages:
      - id: page1
        lambda: |-
          it.image(0, 0, id(my_image));
      # - id: page2
      #   lambda: |-
      #     it.print(0, 10, id(my_font), "This is page 2");
      - id: page3
        lambda: |-
         // Time
          it.printf(0, 10, id(my_font), "Relay: %s", id(relay).state ? "ON" : "OFF");
          it.strftime(85, 0, id(my_font), "%H:%M", id(mytime).now());    
         // LINE, draw a line from X start, Y start, X stop, Y stop
          it.line(0, 18, 128, 18);
          it.printf(0, 26, id(my_font), "Temp: %0.1fC", id(thermo).state);

NODEMCU
esphome:
  name: multisensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: 'xxxx'
  password: 'xxxx'
  manual_ip:
    static_ip: 192.168.0.61
    gateway: 192.168.0.1
    subnet: 255.255.255.0

api:

# Enable logging
logger:

ota:

sensor:
  - platform: dht
    model: DHT11
    pin: D7
    temperature:
      name: "Multisensor Temperature"
    humidity:
      name: "Multisensor Humidity"
    update_interval: 15s


output:
  - platform: esp8266_pwm
    pin: D1
    id: redgpio
  - platform: esp8266_pwm
    pin: D2
    id: greengpio
  - platform: esp8266_pwm
    pin: D3
    id: bluegpio

light:
  - platform: rgb
    name: "Multisensor Light"
    red: redgpio
    green: greengpio
    blue: bluegpio
   
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
The three upgraded devices have not acquired a wifi connection with the static ip indicated.  I used a wifi discovery app to verify this.
All other devices online but indicate they need an upgrade from 1.12.2 to 1.13.5.  I have not initiate any further upgrades
