### ISSUE TITLE
Esp8266 crashes on too big display for addressable led strip

### ISSUE THREAD

**Issue by mfbehrens99** [esphome/issues#4381]
### The problem

When I define define a display component on the adressable_light platform and it is too big for the LED Strip the esp8266 crashes on runtime.

Error should probably be catched on codegen

### Which version of ESPHome has the issue?

2023.2

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

wemos-d1-mini

### Component causing the issue

display

### Example YAML snippet

```yaml
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO2
    num_leds: 200
    name: "NeoPixel"
    id: "neopixel"


display:
  - platform: addressable_light
    id: led_matrix_display
    addressable_light_id: neopixel
    width: 30
    height: 810
    #rotation: 180°
    update_interval: 16ms
    lambda: |-
          it.print(0, 10, id(roboto), "Hello World!");

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 20
```
