### ISSUE TITLE
EZO Not Working

### ISSUE THREAD

**Issue by rspenc29** [esphome/issues#4383]
### The problem

I can't get the EZO pH module to work correctly. I have 2 modules and tried them both. I've tried both 3.3v and 5v with the ezo sensor as well as 2.2k and 4.7k pull-up resistors on both SDA and SCL. I also went all the way back to esphome release 2022.11.0 where the ezo sensor was initially implemented and it doesn't work with that either.

The pH sensor reading seems to work fine. It's reporting a reading in home assistant and the serial logger and the green light on the sensor lights up every time it reads.

Most or all of the automation triggers don't seem to work. `on_t` and `on_custom` are the only ones that actually get called but `x` is always the `?T` or in the case of `on_custom` it's `?i` or whatever command I tried to call. It's never the actual response from the sensor. And none of the other triggers are even called. 

### Which version of ESPHome has the issue?

2023.3.2, 2022.11.0, and probably everything in between

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

EZO

### Example YAML snippet

```yaml
i2c:
  - id: i2cBus1
    sda: 21
    scl: 22
    scan: true
sensor:
  - platform: ezo
    id: ph1
    name: "pH Sensor 1"
    i2c_id: i2cBus1
    address: 99
    unit_of_measurement: "pH"
    accuracy_decimals: 2
    update_interval: 10s
    on_device_information:
      then:
      - lambda: |-
          ESP_LOGI("main", "ph1_on_device_information %s", x.c_str());
    on_led:
      then:
      - lambda: |-
          ESP_LOGI("main", "ph1_on_led %d", x);
    on_slope:
      - lambda: |-
          ESP_LOGI("main", "ph1_on_slope %s", x.c_str());
    on_calibration:
      then:
      - lambda: |-
          ESP_LOGI("main", "ph1_on_calibration %s", x.c_str());
    on_t:
      then:
      - lambda: |-
          ESP_LOGI("main", "ph1_on_t %s", x.c_str());
    on_custom:
      then:
      - lambda: |-
          ESP_LOGI("main", "ph1_on_custom %s", x.c_str());
button:
  - platform: template
    name: "Set pH Calibration Mid (7)"
    on_press:
      - lambda: |-
          id(ph1).set_calibration_point_mid(7);
  - platform: template
    name: "Set pH Calibration Low (4)"
    on_press:
      - lambda: |-
          id(ph1).set_calibration_point_low(4);
  - platform: template
    name: "Get pH Sensor Info"
    on_press:
      - lambda: |-
          id(ph1).get_device_information();
  - platform: template
    name: "Update pH"
    id: phUpdate
    icon: "mdi:ph"
    on_press:
      - lambda: |-
          id(ph1).get_state();
  - platform: template
    name: "Get pH Slope"
    on_press:
      - lambda: |-
          id(ph1).get_slope();
  - platform: template
    name: "Get pH Calibration"
    on_press:
      - lambda: |-
          id(ph1).get_calibration();
  - platform: template
    name: "Get pH Temp Compensation"
    on_press:
      - lambda: |-
          id(ph1).get_t();
```
