### ISSUE TITLE
ESPHome compiles faulty firmware for ESP32 m5stack-core-esp32 

### ISSUE THREAD

**Issue by dom6770** [esphome/issues#4384]
### The problem

ESPHome compiles a faulty image, which cannot be used. OTA Update throws the error: `Error: Wrong Magic Byte`
Inspecting the .bin reveals some errors, although ESPHome itself reports after compilation: `INFO Successfully compiled program.` and let's me save an atom-matrix-**factory**.bin (atom-matrix.yaml)

Error copied from HxD:

`Assert failed in %s, %s:%d (%s)
�abort() was called at PC 0x%08x
�mosi_len <= 32�/IDF/components/bootloader_support/src/bootloader_flash.c�miso_len <= 32�miso_byte_num <= 4�bootloader_flash_read_sfdp�bootloader_flash_execute_command_common�end1>start1�/IDF/components/bootloader_support/include/bootloader_util.h�end2>start2�load_end > load_addr�/IDF/components/bootloader_support/src/esp_image_format.c�Calculated hash�Expected hash�bootloader_util_regions_overlap�verify_load_addresses�handle != NULL�/IDF/components/bootloader_support/src/esp32/bootloader_sha.c�data_len % 4 == 0�words_hashed % BLOCK_WORDS == 60 / 4�words_hashed % BLOCK_WORDS == 0�€`

At some point ESPHome did not create an atom-matrix-factory.bin, but an atom-matrix.bin instead, which has the following error:

`%s requested disconnected�api.connection�%s: tried to access without authentication.�%s: tried to access without full connection.� (esphome v2023.3.2)�2023.3.2�Espressif�m5stack-core-esp32�%s: Socket operation failed: %s errno=%d�%s: Connection reset�%s: Packet write failed %s errno=%d�%s: Connected successfully�%s: Helper init failed: %s errno=%d�%s: Network unavailable, disconnecting�%s: Connection closed�%s: Reading failed: %s errno=%d�%s didn't respond to ping request in time. Disconnecting...�basic_string::_M_construct null not valid�vector::_M_realloc_insert`

ESPHome used in HomeAssistant and in Docker (with latest and 2022.12 tag)

### Which version of ESPHome has the issue?

2023.03 & 2022.12

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.03.3

### What platform are you using?

ESP32

### Board

m5stack-core-esp32 

### Example YAML snippet

```yaml
esphome:
  name: atom-matrix
  friendly_name: "Atom Matrix"
  comment: "Atom Matrix for Xiaomi Mijia BLE Sensors"

esp32:
    board: m5stack-core-esp32 

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "c7871c846daeb5b8fb5170f4dc7bb9e2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .iot.home.local
  use_address: 192.168.178.4

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Atom-Matrix Fallback Hotspot"
    password: "BxujZmQgcYZN"

captive_portal: 

web_server:
  port: 80
  
esp32_ble_tracker:

sensor:
 - platform: pvvx_mithermometer
   mac_address: "A4:C1:38:58:AE:2F"
   temperature:
    name: "Living Room Temperature"
   humidity:
    name: "Living Room Humidity"
   battery_level:
    name: "Living Room Battery"
 - platform: pvvx_mithermometer
   mac_address: "A4:C1:38:4A:86:D1"
   temperature:
    name: "Fridge Temperature"
   humidity:
    name: "Fridge Humidity"
   battery_level:
    name: "Fridge Battery"
 - platform: pvvx_mithermometer
   mac_address: "A4:C1:38:24:15:92"
   temperature:
    name: "Bedroom Temperature"
   humidity:
    name: "Bedroom Humidity"
   battery_level:
    name: "Bedroom Battery"
 - platform: pvvx_mithermometer
   mac_address: "A4:C1:38:56:5A:52"
   temperature:
    name: "Bathroom Temperature"
   humidity:
    name: "Bathroom Humidity"
   battery_level:
    name: "Bathroom Battery"
 - platform: pvvx_mithermometer
   mac_address: "A4:C1:38:84:64:E2"
   temperature:
    name: "Balcony Temperature"
   humidity:
    name: "Balcony Humidity"
   battery_level:
    name: "Balcony Battery"
    
binary_sensor:
 - platform: status
   name: "Atom Matrix Status"
```

**Comment by dom6770** [comment]
I tried a core configuration with a different board:

```
esphome:
    name: livingroom
    platform: ESP32
    board: nodemcu-32s
```

ESPHome still produces a livingroom-factory.bin with an incorrect bytecode (should start with 0xE9, but does with 0xFF.

On the other hand
```
esphome:
    name: livingroom
    platform: ESP8266
    board: esp8285
```

works perfectly fine.
