### ISSUE TITLE
ESP32-S3 missing ADC2 register

### ISSUE THREAD

**Issue by jormus** [esphome/issues#4386]
### The problem

As given by vendor, there is a second register for getting ADC functionality.

I cannot map the correct pin in esphome yaml, because it is missing in the definitions (Lilygo epaper4.7 V2.4 - GPIO14)

epressif docs:
 -  https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32s3/api-reference/peripherals/gpio.html#gpio-rtc-gpio

datasheet Lilygo: 
 - https://raw.githubusercontent.com/Xinyuan-LilyGO/LilyGo-EPD47/master/schematic/T5-4.7-Plus.pdf

offending lines:
 - https://github.com/esphome/esphome/blob/878155a03d5dc912125248c6d4b86d6793068326/esphome/components/adc/sensor.py#L64

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.6

### What platform are you using?

ESP32

### Board

LilyGo-EPD47

### Component causing the issue

adc

### Example YAML snippet

```yaml
# board battery
  - platform: adc
    pin: GPIO14
    name: "${esp_name} Battery Voltage"
    id: batt_volt
    attenuation: 11db
    update_interval: never
    filters:
      - multiply: 2
```

### Anything in the logs that might be useful for us?

```txt
ESP32S3 doesn't support ADC on this pin.
```
