### ISSUE TITLE
PN532 component over I²C blocks code execution for 1s every update when bus read fails

### ISSUE THREAD

**Issue by tracestep** [esphome/issues#4389]
### The problem

I am using a PN532 over I²C for reading RFID tags on a access-control system, so reliability is important. I found that if the PN532 module failed for some reason after being initialized (for instance, by disconnecting SDA, SCL or removing power simulating a fail), the tag read operation on the component update would block for a whole second, halting reads of other devices on the bus and other operations (such as BLE).

I have traced the block to the `i2c_master_cmd_begin(port_, cmd, 20 / portTICK_PERIOD_MS)` call on `IDFI2CBus::readv` from `i2c_bus_esp_idf.cpp`, which apparently does not respect the `ticks_to_wait` parameter - see [https://github.com/espressif/esp-idf/issues/4999](https://github.com/espressif/esp-idf/issues/4999). The issue also happens on the Arduino framework, which itself uses esp-idf.

There are a few patches available, but Espressif apparently has not merged them yet. However, the issue can also be worked around by reducing the frequency of updates once the component has raised a `status_set_warning()`. I will link a PR once I finish testing it.

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.5

### What platform are you using?

ESP32-IDF

### Board

WT32-ETH01

### Component causing the issue

pn532, i2c

### Example YAML snippet

```yaml
i2c:
  scl: GPIO32
  sda: GPIO33
  scan: True
  frequency: 100kHz
  timeout: 2ms

pn532_i2c:
  update_interval: 250ms
  id: rfid
  on_tag:
    then:
      - binary_sensor.template.publish:
          id: tag_present
          state: ON
      - delay: 1s
      - binary_sensor.template.publish:
          id: tag_present
          state: OFF
```

### Anything in the logs that might be useful for us?

```txt
(note the 1 second lapse from "Reading ACK..." to "RX from 24 failed: timeout")

[Mon Apr  3 18:38:56 2023] [V][pn532:272]: Reading ACK...
[Mon Apr  3 18:38:57 2023] [VV][i2c.idf:141]: RX from 24 failed: timeout
[Mon Apr  3 18:38:57 2023] [W][pn532:098]: Requesting tag read failed!
[Mon Apr  3 18:38:57 2023] [W][esp32_ble_tracker:119]: Too many BLE events to process. Some devices may not show up.
[Mon Apr  3 18:38:58 2023] [VV][i2c.idf:183]: 0x24 TX 0000FF04FCD44A0100E100
[Mon Apr  3 18:38:58 2023] [VV][i2c.idf:220]: TX to 24 failed: not acked
[Mon Apr  3 18:38:58 2023] [V][pn532:272]: Reading ACK...
[Mon Apr  3 18:38:59 2023] [VV][i2c.idf:141]: RX from 24 failed: timeout
[Mon Apr  3 18:38:59 2023] [W][pn532:098]: Requesting tag read failed!
[Mon Apr  3 18:38:59 2023] [W][esp32_ble_tracker:119]: Too many BLE events to process. Some devices may not show up.
[Mon Apr  3 18:38:59 2023] [VV][i2c.idf:183]: 0x24 TX 0000FF04FCD44A0100E100
[Mon Apr  3 18:38:59 2023] [VV][i2c.idf:220]: TX to 24 failed: not acked
```
