### ISSUE TITLE
ESP32-S3-EYE - "E (225) cpu_start: Octal Flash option selected, but EFUSE not configured!"

### ISSUE THREAD

**Issue by fanningert** [esphome/issues#4391]
### The problem

I am testing the Espressif board ESP32-S3-EYE, but I get the error "E (225) cpu_start: Octal Flash option selected, but EFUSE not configured!" and the device is in a restart loop.

Device: https://github.com/espressif/esp-who/blob/master/docs/en/get-started/ESP32-S3-EYE_Getting_Started_Guide.md

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.6

### What platform are you using?

ESP32

### Board

Espressif ESP32-S3-EYE

### Component causing the issue

The board it self

### Example YAML snippet

```yaml
esphome:
  name: testcamera
  friendly_name: TestCamera

esp32:   
  variant: esp32s3
  board: esp32s3camlcd
  framework:
    type: arduino
    version: 2.0.7
    platform_version: 6.0.1

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
  password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

esp32_camera:
  name: My Camera
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  i2c_pins:
    sda: GPIO04
    scl: GPIO05
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO06
  href_pin: GPIO07
  pixel_clock_pin: GPIO13
  resolution: 1280x1024
  jpeg_quality: 10
  max_framerate: 30 fps
  vertical_flip: True
```

### Anything in the logs that might be useful for us?

```txt
...
ELF file SHA256: 6f10554403ebc252

E (246) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x2a (SPI_FAST_FLASH_BOOT)
Saved PC:0x4037700c
SPIWP:0xee
mode:DOUT, clock div:1
load:0x3fce3808,len:0x3ac
load:0x403c9700,len:0x9b4
load:0x403cc700,len:0x28fc
entry 0x403c98bc
E (225) cpu_start: Octal Flash option selected, but EFUSE not configured!

abort() was called at PC 0x40376be9 on core 0


Backtrace: 0x403773fe:0x3fceb260 0x4037d3d9:0x3fceb280 0x40383f2d:0x3fceb2a0 0x40376be9:0x3fceb320 0x403cd61b:0x3fceb350 0x403cd8da:0x3fceb380 0x403c9911:0x3fceb4b0 0x40045c01:0x3fceb570 |<-CORRUPTED
...
```
