### ISSUE TITLE
midea_ir fan control issues, fan only mode does not work at all

### ISSUE THREAD

**Issue by kevinmilner** [esphome/issues#4394]
### The problem

I have some Midea minisplit systems from 2015 (before the dongle) and I'm controlling them with `midea_ir`. Heat, cool, and follow me (thanks to https://github.com/esphome/feature-requests/issues/1627) all work great, but I'm having issues with fan control. That goes for fan only mode, as well as trying to control the fan speed in heat mode (but it works in cool mode).

Here's a summary table of what works:

| Mode     | Beeps When Mode Selected? | Actually Works? | Fan Speed Select Beeps? | Fan Speed Select Works? |
|----------|---------------------------|-----------------|-------------------------|-------------------------|
| heat     | yes                       | yes             | no                      | no                      |
| cool     | yes                       | yes             | yes                     | yes                     |
| fan only | no                        | no              | no                      | no                      |

As a test, I can get fan only mode to work via custom `remote_transmitter.transmit_midea` commands running on an interval (so long as I've disabled my follow me command running on an interval). For example, the following will successfully turn the fan on to high (and cause it to beep every 30s):

```
interval:
  - interval: 30s
    then:
      - remote_transmitter.transmit_midea:
          code: !lambda |-
            return {0xA1, 0x9C, 0x7E, 0xFF, 0xFF};
```

I tried different values for the 2nd byte with this test and they all worked as expected:

* `0x9C` fan mode, high
* `0x94` fan mode, medium
* `0x8C` fan mode, low
* `0xA4` fan mode, auto

Any idea what's going on? Is the `midea_ir` fan only mode sending different signals than my test codes (taken from [here](https://mpetroff.net/2015/07/decoding-a-midea-air-conditioner-remote/)) that worked?

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.1

### What platform are you using?

ESP32

### Board

ESP-WROOM-32

### Component causing the issue

midea_ir

### Example YAML snippet

```yaml
esphome:
  name: studio-minisplit

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

remote_transmitter:
  id: ir
  pin: GPIO17
  carrier_duty_percent: 50%
 
climate:
  - platform: midea_ir
    sensor: temp
    name: "Studio Minisplit"
    use_fahrenheit: true
    visual:
      min_temperature: 60 °F
      max_temperature: 88 °F
      temperature_step: 1 °F

sensor:
  - platform: homeassistant
    id: temp
    name: "Studio Temperature Sensor From Home Assistant"
    entity_id: sensor.temperature3
    filters:
    - lambda: return (x - 32.0) * (5.0/9.0);
   
interval:
  - interval: 10s
    then:
      - remote_transmitter.transmit_midea:
          code: !lambda |-
            return {0xA4, 0x82, 0x48, 0x7F, (uint8_t)(id(temp).state + 1)};
```
