### ISSUE TITLE
Docker: Pillow old version

### ISSUE THREAD

**Issue by trip5** [esphome/issues#4398]
### The problem

When adding BDF fonts (created in Fontforge) that use the 10646-1 codepage, ESPHome will hang (on Pillow), not allowing certain characters like the Euro symbol. All BDF fonts are interpreted as Latin-1 character sets only.  It may also have problems with Unicode TTF fonts.

I think this may have been fixed in recent versions of Pillow but after going into the container, I can see the version of Pillow is quite old and since it is system-owned, unsure how to update it.

Is my only way to update pillow by recreating the container myself?

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

ESP8266 / ESP32

### Component causing the issue

python pillow

### Example YAML snippet

```yaml
font: 
  - file: ehmtx/MatrixClock-Light8-Unicode.bdf #
    id: ehmtx_font
    glyphs:  |
      ! "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz€
```

### Anything in the logs that might be useful for us?

```txt
This is while compiling for the EspHoMaTriX (ehmtx) project:

https://github.com/lubeda/EsphoMaTrix
```

### Additional information

You can try out this font here:

https://github.com/darkpoet78/MatrixClockFonts/blob/main/8-series/MatrixClock-Light8-Unicode.bdf
