### ISSUE TITLE
Shelly Dimmer: Calibrating min and max brightness with helper value

### ISSUE THREAD

**Issue by Timmwardion** [esphome/issues#4400]
### The problem

Trying to calibrate min and max brightness settings in a high quality way.

I thought that maybe I could use a helper in HA and pull that in to ESPHome to dynamically control those parameters and really fine-tune things but it seems that these parameters are not template-able.

I've tried directly pulling an input helper value in using lambda, setting a global variable and using that global variable as the parameter value but both of those strategies fail with either an error regarding that option "not being template-able".

Here are the relevant bits of my ESPHome Template

```
globals:
  - id: g_max_brightness
    type: int
    initial_value: '500'

sensor:
 - platform: homeassistant
    name: "Helper Max Brightness"
    id: helper_max_brightness
    entity_id: input_number.calibrate_bathroomhallwaydimmer_high
    on_value:
      then:
        - globals.set:
            id: g_max_brightness
            value: !lambda 'return int(x);' 

light:
  - platform: shelly_dimmer
    name: "${device_name}"
    id: hallwaydimmer
    icon: mdi:globe-light-outline
    power:
      name: "${device_name} Power"
      id: power_dimmer
    voltage:
      name: "${device_name} Voltage"
    current:
      name: "${device_name} Current"
    min_brightness: 24
    #max_brightness: 500
    max_brightness: g_max_brightness
    firmware:
      version: "51.6"
      update: true
```

The alternative of course is to manually change the max and min brightness values and then run an install, but this would be a much more time consuming process to get right.

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.2

### What platform are you using?

ESP8266

### Board

Shelly Dimmer 2

### Component causing the issue

Shelly_Dimmer

### Example YAML snippet

```yaml
See above
```
