### ISSUE TITLE
 How to address the right uart bus in uart.write action?

### ISSUE THREAD

**Issue by ekesgin** [esphome/issues#4401]
### The problem

hi all,

I have configured a nodeMCU v3 with BME680 and a nextion tft display and it works fine.

I also want to add a DFRobot 24GHz mmWave sensor (SEN0395). Nextion tft screen and mmWave sensor work with UART bus. For this I have configured the following UART buses in my EspHome configuration. 

`uart:
  - id: uart_0
    rx_pin: 3
    tx_pin: 1
    baud_rate: 9600
  - id: uart_1
    rx_pin: 13
    tx_pin: 15
    baud_rate: 9600
`
I'v got this message in EspHome editor: 

'Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.'

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.2

### What platform are you using?

ESP8266

### Board

NodeMCU v3

### Component causing the issue

UART

### Example YAML snippet

```yaml
switch:
  - platform: safe_mode
    name: use_safe_mode

  - platform: template
    name: mmwave_sensor
    id: mmwave_sensor # do not change
    entity_category: config
    optimistic: true
    turn_on_action:
      - uart.write: "setUartOutput 1 0"
      - delay: 1s
      - uart.write: "saveConfig"
      - delay: 4s 
      - uart.write: "sensorStart"
    turn_off_action:
      - uart.write: "sensorStop"
      - delay: 2s

  - platform: template
    name: led
    id: led  # do not change
    entity_category: config
    optimistic: true
    turn_on_action:
      - switch.turn_off: mmwave_sensor
      - delay: 2s
      - uart.write: "setLedMode 1 0"
      - delay: 3s
      - lambda: |-
          leapmmw(id(uart_1)).getmmwConf("getLedMode 1");
      - delay: 2s 
      - switch.turn_on: mmwave_sensor
    turn_off_action:
      - switch.turn_off: mmwave_sensor
      - delay: 2s
      - uart.write: "setLedMode 1 1"
      - delay: 3s
      - lambda: |-
          leapmmw(id(uart_1)).getmmwConf("getLedMode 1");
      - delay: 2s
      - switch.turn_on: mmwave_sensor
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esphome-web-61e875.yaml...
Failed config

switch.template: [source /config/esphome/esphome-web-61e875.yaml:287]
  platform: template
  name: mmwave_sensor
  id: mmwave_sensor
  entity_category: config
  optimistic: True
  turn_on_action: 
    then: 
      - 
        Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.
        uart.write: 
          data: b'setUartOutput 1 0'
      - delay: 1s
      - 
        Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.
        uart.write: 
          data: b'saveConfig'
      - delay: 4s
      - 
        Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.
        uart.write: 
          data: b'sensorStart'
  turn_off_action: 
    then: 
      - 
        Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.
        uart.write: 
          data: b'sensorStop'
      - delay: 2s
  disabled_by_default: False
  restore_mode: RESTORE_DEFAULT_OFF
  assumed_state: False
  restore_state: False
switch.template: [source /config/esphome/esphome-web-61e875.yaml:302]
  platform: template
  name: led
  id: led
  entity_category: config
  optimistic: True
  turn_on_action: 
    then: 
      - switch.turn_off: 
          id: mmwave_sensor
      - delay: 2s
      - 
        Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.
        uart.write: 
          data: b'setLedMode 1 0'
      - delay: 3s
      - lambda: !lambda |-
          leapmmw(id(uart_1)).getmmwConf("getLedMode 1");
      - delay: 2s
      - switch.turn_on: 
          id: mmwave_sensor
  turn_off_action: 
    then: 
      - switch.turn_off: 
          id: mmwave_sensor
      - delay: 2s
      - 
        Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.
        uart.write: 
          data: b'setLedMode 1 1'
      - delay: 3s
      - lambda: !lambda |-
          leapmmw(id(uart_1)).getmmwConf("getLedMode 1");
      - delay: 2s
      - switch.turn_on: 
          id: mmwave_sensor
  disabled_by_default: False
  restore_mode: RESTORE_DEFAULT_OFF
  assumed_state: False
  restore_state: False
number.template: [source /config/esphome/esphome-web-61e875.yaml:327]
  platform: template
  name: distance
  id: distance
  entity_category: config
  min_value: 0.15
  max_value: 9.45
  step: 0.15
  unit_of_measurement: M
  mode: BOX
  lambda: !lambda |-
    leapmmw(id(uart_1)).getmmwConf("getRange");
    return {};
  set_action: 
    then: 
      - switch.turn_off: 
          id: mmwave_sensor
      - delay: 2s
      - 
        Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.
        uart.write: 
          data: !lambda |-
            std::string range = "setRange 0 " + str_sprintf("%.2f", x); return std::vector<unsigned char>(range.begin(), range.end());
      - delay: 3s
      - switch.turn_on: 
          id: mmwave_sensor
  disabled_by_default: False
  optimistic: False
  update_interval: 60s
number.template: [source /config/esphome/esphome-web-61e875.yaml:348]
  platform: template
  name: latency
  id: latency
  entity_category: config
  min_value: 1.0
  max_value: 600.0
  lambda: !lambda |-
    leapmmw(id(uart_1)).getmmwConf("getLatency");
    return {};
  step: 1.0
  unit_of_measurement: s
  mode: BOX
  set_action: 
    then: 
      - switch.turn_off: 
          id: mmwave_sensor
      - delay: 2s
      - 
        Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.
        uart.write: 
          data: !lambda |-
            std::string setL = "setLatency 0.1 " + str_sprintf("%.0f", x); return std::vector<unsigned char>(setL.begin(), setL.end());
      - delay: 3s
      - switch.turn_on: 
          id: mmwave_sensor
  disabled_by_default: False
  optimistic: False
  update_interval: 60s
number.template: [source /config/esphome/esphome-web-61e875.yaml:369]
  platform: template
  name: sensitivity
  id: sensitivity
  entity_category: config
  min_value: 0.0
  max_value: 9.0
  lambda: !lambda |-
    leapmmw(id(uart_1)).getmmwConf("getSensitivity");
    return {};
  step: 1.0
  set_action: 
    then: 
      - switch.turn_off: 
          id: mmwave_sensor
      - delay: 2s
      - 
        Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.
        uart.write: 
          data: !lambda |-
            std::string mss = "setSensitivity " + to_string((int)x); return std::vector<unsigned char>(mss.begin(), mss.end());
      - delay: 3s
      - switch.turn_on: 
          id: mmwave_sensor
  disabled_by_default: False
  mode: AUTO
  optimistic: False
  update_interval: 60s
button.template: [source /config/esphome/esphome-web-61e875.yaml:397]
  platform: template
  name: factory_reset_mmwMCU_${device_name}
  id: factory_reset_mmwMCU
  entity_category: diagnostic
  on_press: 
    - then: 
        - switch.turn_off: 
            id: mmwave_sensor
        - delay: 2s
        - 
          Too many candidates found for 'id' type 'uart::UARTComponent' Some are 'uart_0', 'uart_1'.
          uart.write: 
            data: b'resetCfg'
        - delay: 3s
        - switch.turn_on: 
            id: mmwave_sensor
  disabled_by_default: False
```

### Additional information

![image](https://user-images.githubusercontent.com/25054985/230925196-30987f85-7c95-47b2-8da1-a4ce6aade8fc.png)

this is where i get the code from.

https://github.com/igiannakas/mmwave-d1mini/blob/main/packages/leapmmw_sensor.yml 

Does anyone know how to fix it?
