### ISSUE TITLE
SX1509 output won't maintain state if second output switched right after

### ISSUE THREAD

**Issue by tracestep** [esphome/issues#4402]
### The problem

If I set/unset SX1509 port-expander outputs one right after another, such as in an automation (e.g.:)
```
then:
  - switch.turn_on: led1
  - switch.turn_on: led2
```
led1 will turn on for around 2ms, then turn off when led2 gets turned on. This behavior will only happen when there is a keypad configured with debouncing.

I saw that outputs are switched in the `SX1509Component::digital_write`, which uses a read-modify-write approach, reading the register data, toggling the corresponding bit, then writing:

```
void SX1509Component::digital_write(uint8_t pin, bool bit_value) {
  if ((~this->ddr_mask_) & (1 << pin)) {
    // If the pin is an output, write high/low
    uint16_t temp_reg_data = 0;
    this->read_byte_16(REG_DATA_B, &temp_reg_data);
    if (bit_value) {
      temp_reg_data |= (1 << pin);
    } else {
      temp_reg_data &= ~(1 << pin);
    }
    this->write_byte_16(REG_DATA_B, temp_reg_data);
  }
}
```
Using a logic analyzer, I can see that after turning on the first LED, when the register is read before turning on the second one (a little less than 1ms later), it reads as if it was still turned off. I suppose that's because of the debounce time, that, according to the SX1509 datasheet, is global for all IOs (_page 16_), even though the component sets `REG_DEBOUNCE_ENABLE` only for the keypad pins. The fact is that when the register is read before the debounce time has passed, it still holds the previous value.

I believe one solution would be to use a shadow variable to hold the state of the configured outputs and set/reset the bits based on that instead of the values on the SX1509 register.

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.5

### What platform are you using?

ESP32-IDF

### Board

WT32-ETH01

### Component causing the issue

sx1509

### Example YAML snippet

```yaml
# The issue can be reproduced with this configuration:
#   If you turn on the first LED, only the second will stay on; the first
#   one will only light up for 1 or 2 ms.
#
#   Obs: do not turn on VERY_VERBOSE logging for the i2c component, as,
#        with keypad scanning, logging alone will affect the timing and
#        the issue will not be reproducible. See the logic analyzer log below.

esphome:
  name: "sx1509"

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    version: recommended

logger:
  baud_rate: 115200
  level: DEBUG
  logs:
    i2c.idf: DEBUG
    api.service: INFO
    api.socket: INFO
    api.connection: INFO
    mdns: INFO
    component: INFO
    scheduler: INFO
    esp32.preferences: DEBUG
    switch: DEBUG

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

ota:
  password: !secret ota_password

api:
  encryption:
    key: !secret esphome_encryption_key

i2c:
  scl: GPIO32
  sda: GPIO33
  scan: True
  frequency: 100kHz

sx1509:
  - id: expander
    address: 0x3E
    keypad:
      key_rows: 4
      key_columns: 3
      sleep_time: 1024
      scan_time: 4
      debounce_time: 2

switch:
  - platform: gpio
    id: led1
    name: LED1
    restore_mode: ALWAYS_OFF
    pin:
      sx1509: expander
      number: 4
      mode:
        output: true
      inverted: false
    on_turn_on:
      then:
        - switch.turn_on: led2
  - platform: gpio
    id: led2
    name: LED2
    restore_mode: ALWAYS_OFF
    pin:
      sx1509: expander
      number: 5
      mode:
        output: true
      inverted: false
```

### Anything in the logs that might be useful for us?

```txt
----------------------------------------------------------------------------------------------------------------------------------
// File created on:  2023/04/10
// Sampling mode:Compression
// Internal sample rate = 1000000 Hz
// Memory depth:2KB
// Trigger Properties: Trigger position = 50%
//                    Trigger Voltages: 	Port A = 1.50V      Port B = 1.50V      
//                    Trigger Pass Counter1 
//                    Trigger Page1 
// Data Length:165.05ms	
// Total Length:2.048ms
--------------------------------------------------------------
// Channel name:      A0 A1 A2 A3 A4 A5 A6 A7      B0 B1 B2 B3 B4 B5 B6 B7      C0 C1 C2 C3 C4 C5 C6 C7      D0 D1 D2 D3 D4 D5 D6 D7      
// Signal Filter:     X  X  X  X  X  X  X  X       X  X  X  X  X  X  X  X       X  X  X  X  X  X  X  X       X  X  X  X  X  X  X  X       
//Sieve out the display of the data.
------------------------------------------------------------------------------------------------
Data are shown as hexadecimal values.


Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
1           Bus1(I2C) -73.601ms   Start     3E        Read      A-ACK     FF        D-ACK     FF        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Stop      
2           Bus1(I2C) -56.963ms   Start     3E        Write     A-ACK     27        D-ACK     Stop      

Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
3           Bus1(I2C) -56.601ms   Start     3E        Read      A-ACK     FF        D-ACK     FF        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Stop      
4           Bus1(I2C) -39.962ms   Start     3E        Write     A-ACK     27        D-ACK     Stop      

Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
5           Bus1(I2C) -39.601ms   Start     3E        Read      A-ACK     FF        D-ACK     FF        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Stop      
6           Bus1(I2C) -22.926ms   Start     3E        Write     A-ACK     27        D-ACK     Stop      

Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
7           Bus1(I2C) -22.557ms   Start     3E        Read      A-ACK     FF        D-ACK     FF        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Stop      
8           Bus1(I2C) -5.951ms    Start     3E        Write     A-ACK     27        D-ACK     Stop      

Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
9           Bus1(I2C) -5.029ms    Start     3E        Read      A-ACK     FF        D-ACK     FF        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Stop      
10          Bus1(I2C) -1.369ms    Start     3E        Write     A-ACK     10        D-ACK     Stop      

Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
11          Bus1(I2C) -992us      Start     3E        Read      A-ACK     07        D-ACK     06        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Data      D-ACK     Data      D-ACK     Stop      
12          Bus1(I2C) -370us      Start     3E        Write     A-ACK     10        D-ACK     07        D-ACK     16        D-ACK     Stop      

// **********************************
// LED1 turns on here (trigger = 0us)
// **********************************

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Stop      
13          Bus1(I2C) 571us       Start     3E        Write     A-ACK     10        D-ACK     Stop      

Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
14          Bus1(I2C) 900us       Start     3E        Read      A-ACK     07        D-ACK     06        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Data      D-ACK     Data      D-ACK     Stop      
15          Bus1(I2C) 1.475ms     Start     3E        Write     A-ACK     10        D-ACK     07        D-ACK     26        D-ACK     Stop      

// *****************************************************************
// LED1 turns off here, at the same time LED2 is turned on (1.844ms)
// *****************************************************************

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Stop      
16          Bus1(I2C) 22.434ms    Start     3E        Write     A-ACK     27        D-ACK     Stop      

Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
17          Bus1(I2C) 22.839ms    Start     3E        Read      A-ACK     FF        D-ACK     FF        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Stop      
18          Bus1(I2C) 40.031ms    Start     3E        Write     A-ACK     27        D-ACK     Stop      

Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
19          Bus1(I2C) 40.396ms    Start     3E        Read      A-ACK     FF        D-ACK     FF        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Stop      
20          Bus1(I2C) 57.03ms     Start     3E        Write     A-ACK     27        D-ACK     Stop      

Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
21          Bus1(I2C) 57.387ms    Start     3E        Read      A-ACK     FF        D-ACK     FF        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     Data      D-ACK     Stop      
22          Bus1(I2C) 74.031ms    Start     3E        Write     A-ACK     27        D-ACK     Stop      

Packet #    Name      TimeStamp   Start     Address   Read      A-ACK     Data      D-ACK     Data      D-NACK    Stop      Description         
23          Bus1(I2C) 74.396ms    Start     3E        Read      A-ACK     FF        D-ACK     FF        D-NACK    Stop      Master NACK         

Packet #    Name      TimeStamp   Start     Address   Write     A-ACK     
24          Bus1(I2C) 91.034ms    Start     3E        Write     A-ACK
```

### Additional information

Relevant packets are 11 and 14, where the registers are returned. Notice that the value returned on both is 0x07 0x06, even though, on packet 14, LED1 was already turned on. Packet 14 should have returned 0x07 0x16, and thus packet 15 should have been written as 0x07 0x36 for both LEDs to be turned on.
