### ISSUE TITLE
Missing update of adc sensor with Home Assistant

### ISSUE THREAD

**Issue by leofalp** [esphome/issues#441]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io intsalled on Ubuntu Server 18.04.2 LTS

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU v3
**Affected component:**

Platform acd update

**Description of problem:**
I have a little problem with a NodeMCUv3 with ESPHome connected to Home Assistant through WiFi.

The configuration is simple: i have a Dallas sensor for the temperature and all is powered from little solar panel and 18650 battery. so i need Deep Sleep to preserve the battery and i'd like to monitor the battery voltage so i've link the + of battery with A0 Pin with a resistor. 

All works fine! There's only the problem of updating value to home hassistant. The temperature is perfect but the voltage updates whenever it wants, maybe after days.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp5
  platform: ESP8266
  board: nodemcuv2
  
deep_sleep:
  run_duration: 120s
  sleep_duration: 9min

wifi:
  ssid: "GuaiFaiMini"
  password: "**"

logger:

api:
  password: '**'

ota:
  password: '**'

dallas:
  - pin: D2

sensor:
  - platform: dallas
    address: 0x1602131B06C8AA28
    name: "Temperatura esterna"
    id: "temp_ext"
  
  - platform: adc
    pin: A0
    name: "Tensione batteria esp5"
    id: "batt_esp5"
    update_interval: 5s
    filters:
      - multiply: 4.2
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
