### ISSUE TITLE
Wemos D1 Mini S2 touch support disabled

### ISSUE THREAD

**Issue by spuder** [esphome/issues#4411]
### The problem

The datasheet for the S2 (esp32) chip shows that touch sensors are available on pins 1-14

See section [3.3.4 in the datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-s2_datasheet_en.pdf)

If you attempt to enable the `esp32_touch`, it gives the following error: 

```yaml
esp32_touch:

binary_sensor:
  - platform: esp32_touch
    name: "ESP32 Touch Pad"
    pin: 13
    threshold: 1000

```

```
Failed config

esp32_touch: [source config.yaml:274]
  
  This feature is only available on ESP32.
  {}
```

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

Wemos D1 Mini S2 

### Component causing the issue

esp32_touch

### Example YAML snippet

```yaml
https://www.wemos.cc/en/latest/s2/s2_mini.html
```

**Comment by spuder** [comment]
Code validation lines: https://github.com/esphome/esphome/blob/6b67acbeb5fc6fae713ed81f7ee549f53a3d42ff/esphome/config_validation.py#L534-L541

**Comment by spuder** [comment]
```yaml
esphome:
  name: foobar3
  friendly_name: AnkerMake-M5

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  ```
