### ISSUE TITLE
Error: Could not find one of 'package.json' manifest files in the package

### ISSUE THREAD

**Issue by sns5400** [esphome/issues#4415]
### The problem

Afther make a simple yaml file i try to install this in my esp32  ESP-wroom-32D and receive this screen

![Probleem 2023-04-16_8-20-58](https://user-images.githubusercontent.com/13086722/232312931-5638bf59-d772-4f21-a6ec-ca082f7f9418.png)

### Which version of ESPHome has the issue?

ESPHome Current version: 2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.4.4

### What platform are you using?

ESP32

### Board

ESP-WROOM-32D

### Example YAML snippet

```yaml
esphome:
  name: esphome-web-997c98
  friendly_name: MyESP32

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BPnyoqItOQyX/fx1igaBzBjCFr9/4//JuD3tmetDFeE="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # optional manual ip
  manual_ip:
    static_ip: 192.168.1.26
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-997C98"
    password: "ps707300"

captive_portal:

output:
  - platform: gpio
    id: "my_little_LED"
    pin: 5

light:
  - platform: binary
    output: "my_little_LED"
    name: "My Little LED"
```

### Additional information

I found a simaler error here but there the speak about deleting  packages directory or platformio directory but i can not find such a name in the file system.

I run Home assistant on a rpi4 with unremovable memory e-mmc

How can i fix this problem
