### ISSUE TITLE
Multiple uart esp32 

### ISSUE THREAD

**Issue by fornell30** [esphome/issues#4417]
### The problem

Greetings to all. My problem is that I have defined 4 uarts to control arduinos and only uart 1 tx and uart 2 tx and rx work, the rest does not work. This is my yaml.

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.2

### What platform are you using?

ESP32

### Board

DEVkit

### Component causing the issue

uart

### Example YAML snippet

```yaml
uart:
  - id: uart_bus1
    baud_rate: 9600
    tx_pin: GPIO17
    rx_pin: GPIO16
  - id: uart_bus2
    tx_pin: GPIO25
    rx_pin: GPIO35
    baud_rate: 9600
  - id: uart_bus3
    tx_pin: GPIO26
    rx_pin: GPIO32
    baud_rate: 9600
  - id: uart_bus4
    tx_pin: GPIO27
    rx_pin: GPIO33
    baud_rate: 9600 
    
switch:
  - platform: uart
    uart_id: uart_bus1
    name: "subir toldo 1"
    data: 'up'
  - platform: uart
    uart_id: uart_bus1
    name: "bajar toldo 1"
    data: 'down'
  - platform: uart
    uart_id: uart_bus1
    name: "parar toldo 1"
    data: 'parar'
  - platform: uart
    uart_id: uart_bus1
    name: "reset toldo 1"
    data: 'rest'
  - platform: uart
    uart_id: uart_bus1
    name: "noche toldo 1"
    data: 'night'
  - platform: uart
    uart_id: uart_bus1
    name: "dia toldo 1"
    data: 'day'
  
  - platform: uart
    uart_id: uart_bus2
    name: "subir toldo 2"
    data: 'up'
  - platform: uart
    uart_id: uart_bus2
    name: "bajar toldo 2"
    data: 'down'
  - platform: uart
    uart_id: uart_bus2
    name: "parar toldo 2"
    data: 'parar'
  - platform: uart
    uart_id: uart_bus2
    name: "reset toldo 2"
    data: 'rest'
  - platform: uart
    uart_id: uart_bus2
    name: "noche toldo 2"
    data: 'night'
  - platform: uart
    uart_id: uart_bus2
    name: "dia toldo 2"
    data: 'day'

  - platform: uart
    uart_id: uart_bus3
    name: "subir toldo 3"
    data: 'up'
  - platform: uart
    uart_id: uart_bus3
    name: "bajar toldo 3"
    data: 'down'
  - platform: uart
    uart_id: uart_bus3
    name: "parar toldo 3"
    data: 'parar'
  - platform: uart
    uart_id: uart_bus3
    name: "reset toldo 3"
    data: 'rest'
  - platform: uart
    uart_id: uart_bus3
    name: "noche toldo 3"
    data: 'night'
  - platform: uart
    uart_id: uart_bus3
    name: "dia toldo 3"
    data: 'day'

  - platform: uart
    uart_id: uart_bus4
    name: "subir toldo 4"
    data: 'up'
  - platform: uart
    uart_id: uart_bus4
    name: "bajar toldo 4"
    data: 'down'
  - platform: uart
    uart_id: uart_bus4
    name: "parar toldo 4"
    data: 'parar'
  - platform: uart
    uart_id: uart_bus4
    name: "reset toldo 4"
    data: 'rest'
  - platform: uart
    uart_id: uart_bus4
    name: "noche toldo 4"
    data: 'night'
  - platform: uart
    uart_id: uart_bus4
    name: "dia toldo 4"
    data: 'day'

  - platform: gpio
    name: "Camara terraza"
    pin: GPIO22
    inverted: false
    restore_mode: RESTORE_DEFAULT_ON
    id: camara_terraza

 
    
text_sensor:
- platform: custom
  lambda: |-
    auto uarttoldo = new UartReadLineSensor(id(uart_bus1));
    App.register_component(uarttoldo);
    return {uarttoldo};
  text_sensors:
    id: "uarttoldo"
    name: "toldo_custom_uart"
  
- platform: custom
  lambda: |-
    auto uarttoldo2 = new UartReadLineSensor(id(uart_bus2));
    App.register_component(uarttoldo2);
    return {uarttoldo2};
  text_sensors:
    id: "uarttoldo2"
    name: "toldo2_custom_uart"
- platform: custom
  lambda: |-
    auto uarttoldo3 = new UartReadLineSensor(id(uart_bus3));
    App.register_component(uarttoldo3);
    return {uarttoldo3};
  text_sensors:
    id: "uarttoldo3"
    name: "toldo3_custom_uart"
- platform: custom
  lambda: |-
    auto uarttoldo4 = new UartReadLineSensor(id(uart_bus4));
    App.register_component(uarttoldo4);
    return {uarttoldo4};
  text_sensors:
    id: "uarttoldo4"
    name: "toldo4_custom_uart"
```
