### ISSUE TITLE
Ethernet PHY on ESP32 board consumes too much power on deep sleep

### ISSUE THREAD

**Issue by tracestep** [esphome/issues#4420]
### The problem

When I put the board on deep sleep (e.g,: `deep_sleep.enter`), the board still consumes over ~70 mA. I have traced the issue to the fact that, before entering deep sleep, the ethernet PHY on the board is not powered down / put into low power mode. I will link a PR which works at least for the LAN8720 on my board, but probably others, as it uses the esp-idf HAL.

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

Irrelevant

### What platform are you using?

ESP32-IDF

### Board

WT32-ETH01

### Component causing the issue

ethernet

### Example YAML snippet

```yaml
ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

deep_sleep:
  id: sleeper
  touch_wakeup: false
  esp32_ext1_wakeup:
    pins: [GPIO39, GPIO35, GPIO14]
    mode: ANY_HIGH

button:
  - id: button_sleep
    platform: template
    name: Sleep
    icon: mdi:sleep
    on_press:
      then:
        - deep_sleep.enter:
            id: sleeper
```
