### ISSUE TITLE
DALLAS DS18B20 configuration register check

### ISSUE THREAD

**Issue by apaex** [esphome/issues#4422]
### The problem

My sensor DS18B20 returns zeros in 0-5 bits of the configuration register: 

[23:24:24][D][dallas.sensor:084]:     0x8f06473b51760028
[23:26:11][VV][dallas.sensor:258]: Scratch pad: AD.01.4B.00.60.FF.03.10.7C (7C)
[23:26:11][W][dallas.sensor:263]: 'Wired temperature' - Scratch pad config register invalid!

In the configuration register 60, that is 1100000b
#3358 added a check that caused it to stop working.

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

dallas

### Example YAML snippet

```yaml
dallas:
  - pin: GPIO15
sensor:
  - platform: dallas
    address: 0x8F06473B51760028
    name: "Wired temperature"
    id: temperature_sensor
```

### Anything in the logs that might be useful for us?

```txt
[23:26:11][VV][dallas.sensor:258]: Scratch pad: AD.01.4B.00.60.FF.03.10.7C (7C)
[23:26:11][W][dallas.sensor:263]: 'Wired temperature' - Scratch pad config register invalid!
```
