### ISSUE TITLE
Throttle not working for MQTT

### ISSUE THREAD

**Issue by toad011** [esphome/issues#4423]
### The problem

I read information from my energy counter via SML.
Although I configured throttle for the sensor, MQTT is updated almost 100 times per second.
If I increase throttle to like 30s, it is adjusted in the logs and in home assistant, but mqtt still ignores it.

I tried to add debounce and discovery=false, but no effect.

### Which version of ESPHome has the issue?

v2023.3.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Board

esp32-cam

### Component causing the issue

mqtt

### Example YAML snippet

```yaml
esphome:
  name: esp32sml
  friendly_name: esp32sml

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xxx"

ota:
  password: "xxx"

wifi:
  ssid: xxx
  password: xxx

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Sml Fallback Hotspot"
    password: xxx

captive_portal:

uart:
  id: uart_bus
  rx_pin: GPIO13
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

sml:
  id: mysml
  uart_id: uart_bus

mqtt:
  broker: xxx
  username: xxx
  password: xxx
  discovery: false

sensor:
  - platform: sml
    name: "Total energy"
    sml_id: mysml
    obis_code: "1-0:1.8.0"
    unit_of_measurement: Wh
    accuracy_decimals: 1
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.1
      - throttle: 1s
      - debounce: 0.1s
  - platform: sml
    name: "Current Power"
    sml_id: mysml
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
    discovery: false
    filters:
      - throttle: 1s
      - debounce: 0.1s
```
