### ISSUE TITLE
Home Assistant Time never polls after the initial request

### ISSUE THREAD

**Issue by DAVe3283** [esphome/issues#4424]
### The problem

The [Home Assistant Time](https://esphome.io/components/time/homeassistant.html) component only updates when Home Assistant or ESPHome logging first connects to the ESP.

After some time (1-5 days), the local ESP clock has drifted significantly (sometimes a minute), which is really annoying when it is displaying the time.

I can get the time to re-sync by connecting to the logs with ESPHome, but that isn't a reasonable thing to need to do every couple days just to have an accurate clock displayed.

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.2

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

time/homeassistant

### Example YAML snippet

```yaml
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: d1_mini

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

globals:
  - id: GLOBAL_LAST_TIMESYNC
    type: char*
    restore_value: no
    initial_value: '"Never\0\0\0\0"'
  - id: GLOBAL_TIMESYNC_COUNT
    type: uint8_t
    restore_value: no
    initial_value: "0"

time:
  - platform: homeassistant
    id: ha_time
    update_interval: 30s
    on_time_sync:
      then:
        - lambda: |-
            std::strncpy(id(GLOBAL_LAST_TIMESYNC), id(ha_time).now().strftime("%H:%M:%S").c_str(), 8);
            id(GLOBAL_TIMESYNC_COUNT)++;
        - logger.log:
            format: "Synchronized system clock"
            level: WARN

display:
  - platform: ssd1306_i2c
    model: SSD1306 64x48
    address: 0x3C
    lambda: |-
      it.fill(COLOR_OFF);
      it.printf(32, 0, id(fnt9), COLOR_ON, TextAlign::TOP_CENTER, "%d %s", id(GLOBAL_TIMESYNC_COUNT), id(GLOBAL_LAST_TIMESYNC));
```

### Anything in the logs that might be useful for us?

Notably, "Synchronized system clock" only appears when connecting an additional ESPHome log viewer, or (re)connecting Home Assistant.
It does not appear every 30 seconds as expected from the YAML. In fact, after running for 24+ hours, it never re-synchronizes.

### Additional information

I added some debug code to components/homeassistant/time/homeassistant_time.cpp files and verified that it does call `api::global_api_server->request_time();`. However, the time is not actually updated. Not sure if there is an API problem, or what.
