### ISSUE TITLE
Two DS18B20s on one bus not working

### ISSUE THREAD

**Issue by jikama** [esphome/issues#443]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

https://esphome.io/components/sensor/dallas.html

**Description of problem:**
Connecting two configured DS18B20 will freeze the NodeMcu with ESPHOME. If one of the sensors is disconnected, the other one is functional and I see the value.

```
dallas:
   pin: D5
   update_interval: 10s
sensor:
 - platform: dallas
   address: 0x3F030997792F5828
   name: "Temperature #1"
   platform: dallas
   address: 0xD703139779A28828
   name: "Temperature #2"
```

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
