### ISSUE TITLE
Unable to compile bme680_bsec sensor on ESP32-C3

### ISSUE THREAD

**Issue by fran6120** [esphome/issues#4430]
### The problem

I have tried it with both esphome 2023.4.0 and 2023.5.0-dev.

If I set `framework: esp-idf` I can't compile it and it shows error `This feature is only available with frameworks ['arduino']`.

If I set `framework: arduino` I can't compile either, and this time the error shown is `This feature is only available on ['esp8266'].`

In each attempt always cleaning the build files

``` yaml
esphome:
  name: estacionc3
  friendly_name: estacionc3
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: lolin_c3_mini
  framework:
    type: arduino

logger:

api:

i2c:
  sda: GPIO7
  scl: GPIO6
  scan: True
  frequency: 400kHz

wifi:
  networks:
    - ssid: !secret wifi_ssid1
      password: !secret wifi_password1
      manual_ip:
        static_ip: 192.168.1.211
        gateway: 192.168.1.1
        subnet: 255.255.255.0
        dns1: 192.168.1.1
  fast_connect: true

bme680_bsec:
  address: 0x77
  temperature_offset: 0
  iaq_mode: static
  sample_rate: ulp
  state_save_interval: 6h

  - platform: bme680_bsec
    bme680_bsec_id: bme680_internal
    temperature:
      name: "Temperatura"
      id: temperatura_bme680
      sample_rate: lp
      filters:
        - median
    pressure:
      name: "Presión"
      id: presion_bme680
      sample_rate: lp
      filters:
        - median
    humidity:
      name: "Humedad Relativa"
      id: humedad_bme680
      sample_rate: lp
      filters:
        - median
    gas_resistance:
      name: "Resistencia Del GAS"
      filters:
        - median
    iaq:
      name: "Calidad Del Aire"
      filters:
        - median
    iaq_accuracy:
      name: "Índice Calidad De Aire"
    co2_equivalent:
      name: "CO2 Equivalente"
      filters:
        - median
    breath_voc_equivalent:
      name: "VOC Equivalente"
      filters:
        - median

text_sensor: 
  - platform: bme680_bsec
    iaq_accuracy:
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "BME680 Precisión Calidad De Aire"
```

### Which version of ESPHome has the issue?

2023.4.0, 2023.5.0-dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

ESP32C3 (Lolin C3 Mini)

### Component causing the issue

bme680_bsec

### Example YAML snippet

```yaml
esphome:
  name: estacionc3
  friendly_name: estacionc3
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

logger:

api:

i2c:
  sda: GPIO7
  scl: GPIO6
  scan: True
  frequency: 400kHz

wifi:
  networks:
    - ssid: !secret wifi_ssid1
      password: !secret wifi_password1
      manual_ip:
        static_ip: 192.168.1.211
        gateway: 192.168.1.1
        subnet: 255.255.255.0
        dns1: 192.168.1.1
  fast_connect: true

bme680_bsec:
  address: 0x77
  temperature_offset: 0
  iaq_mode: static
  sample_rate: ulp
  state_save_interval: 6h

  - platform: bme680_bsec
    bme680_bsec_id: bme680_internal
    temperature:
      name: "Temperatura"
      id: temperatura_bme680
      sample_rate: lp
      filters:
        - median
    pressure:
      name: "Presión"
      id: presion_bme680
      sample_rate: lp
      filters:
        - median
    humidity:
      name: "Humedad Relativa"
      id: humedad_bme680
      sample_rate: lp
      filters:
        - median
    gas_resistance:
      name: "Resistencia Del GAS"
      filters:
        - median
    iaq:
      name: "Calidad Del Aire"
      filters:
        - median
    iaq_accuracy:
      name: "Índice Calidad De Aire"
    co2_equivalent:
      name: "CO2 Equivalente"
      filters:
        - median
    breath_voc_equivalent:
      name: "VOC Equivalente"
      filters:
        - median

text_sensor: 
  - platform: bme680_bsec
    iaq_accuracy:
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "BME680 Precisión Calidad De Aire"
```
