### ISSUE TITLE
Modbus 'disable_crc: true' causes unhandled exception

### ISSUE THREAD

**Issue by bwcoetzer** [esphome/issues#4431]
### The problem

A modbus interface was built with an ESP32 and MAX485 modbus converter.  Data is sent to a Macbook running Coolterm that has the ability to loop received data back.  In debugging the modbus configuration the 'disable_crc:' was set to 'true'.  The compile and upload succeeded and while the data was not being looped back the interface transmitted read signals.  As soon as the data was looped back and received by the ESP32 an exception occurred.  Log file included.  Notable event at [12:26:23][D][modbus:106]: Modbus CRC Check failed, but ignored! C022!=07 (indicating that CRC check was disabled as configured).  That is however followed by an error message and Backtrace and ESP then reboots

[logs_rs485modbus-test_run.txt](https://github.com/esphome/issues/files/11285266/logs_rs485modbus-test_run.txt)

### Which version of ESPHome has the issue?

2023.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.4

### What platform are you using?

ESP32

### Board

ESP32 DEV WROOM-32  generic

### Component causing the issue

modbus controller

### Example YAML snippet

```yaml
uart:
  id: modbusdeye
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1
  debug:
      direction: BOTH
      dummy_receiver: true
      after:
        delimiter: "\n"
      sequence:
        - lambda: |-
            UARTDebug::log_hex(direction, bytes, 0x20);

modbus:
  flow_control_pin: 5
  id: modbus1
  disable_crc: true
  send_wait_time: 800ms

modbus_controller:
  - id: deye
    ## the Modbus device addr
    address: 0x1
    update_interval: 10s
    setup_priority: -10

sensor:
  - platform: modbus_controller
    name: "Voltage Phase 1"
    address: 07
    unit_of_measurement: "V"
    register_type: "read"
    value_type: FP32
```
```


### Anything in the logs that might be useful for us?

```txt
Notable event at [12:26:23][D][modbus:106]: Modbus CRC Check failed, but ignored! C022!=07 (indicating that CRC check was disabled as configured).  That is however followed by an error message and Backtrace and ESP then reboots
```

### Additional information

[logs_rs485modbus-test_run.txt](https://github.com/esphome/issues/files/11285276/logs_rs485modbus-test_run.txt)
