### ISSUE TITLE
[MAX7219digit] flip_x commit breaks reversed display

### ISSUE THREAD

**Issue by voed** [esphome/issues#4432]
### The problem

The last [commit ](https://github.com/esphome/esphome/pull/4555) from @rafal83 breaks rotated and reversed displays. My clock is installed upside down so i used to rotate & flip it and it worked fine:
```
    rotate_chip: 180
    reverse_enable: true
```
But with that commit the display is completely broken(see details)

### Which version of ESPHome has the issue?

2023.04

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.3

### What platform are you using?

ESP32

### Component causing the issue

MAX7219digit

### Example YAML snippet

```yaml
display:
  - platform: max7219digit
    cs_pin: GPIO25
    num_chips: 4
    intensity: 0
    rotate_chip: 180
    reverse_enable: false
    flip_x: false
    lambda: |-
      it.print(0, 5, id(digit_font), TextAlign::CENTER_LEFT, "1234567890");

```
<details>

![image](https://user-images.githubusercontent.com/10352360/233393003-4aa4b3d2-6275-4466-b248-f41badd1ecad.png)

</details>

==========================================================================

    reverse_enable: false
    flip_x: true

<details>

![image](https://user-images.githubusercontent.com/10352360/233393245-95368176-907e-4781-940a-0824d3971793.png)

</details>

==========================================================================

    reverse_enable: true
    flip_x: true

With reverse enable the text is even duplicated from both directions
<details>

![image](https://user-images.githubusercontent.com/10352360/233393370-015e4e75-b15e-49bd-bd93-3b6013866d20.png)

</details>

==========================================================================

    reverse_enable: true
    flip_x: false

<details>

![image](https://user-images.githubusercontent.com/10352360/233393771-a67f0f5b-dd92-489f-8165-0dcd61d3e442.png)

</details>
