### ISSUE TITLE
media_player starts with maximal volume

### ISSUE THREAD

**Issue by koemat** [esphome/issues#4433]
### The problem

Since update to ESPhome 2023.4.0 media players are starting with max volume. 

### Which version of ESPHome has the issue?

2023.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.5

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

i2s_audio, media_player

### Example YAML snippet

```yaml
i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO5

media_player:
  - platform: i2s_audio
    name: "${friendly_name}"
    dac_type: external    
    i2s_dout_pin: GPIO26    
    mode: mono
    mute_pin:
      number: GPIO21
      inverted: true
```
