### ISSUE TITLE
flip_x 

### ISSUE THREAD

**Issue by pepaferbar** [esphome/issues#4441]
### The problem

after update to ESPHome v2023.4.0 are MAX7219 Digit Display always flyp by x axis.
Configuration flip_x dont work

### Which version of ESPHome has the issue?

2023.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.5

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Example YAML snippet

```yaml
display:
  - platform: max7219digit
    id: digit
    cs_pin: D4
#    cs_pin: D2

    num_chips: 4
    rotate_chip: 180
    reverse_enable: false
#    num_chip_lines: 1
    flip_x: false
```
