### ISSUE TITLE
Multiple CORS Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by segeda** [esphome/issues#4442]
### The problem

I am trying to read `http://my-esphome.local/events` events stream. But server sends multiple (twice) `Access-Control-Allow-Origin` headers and browser rejects connection. I found out that this reason is https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMultipleAllowOriginNotAllowed.

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

m5stack-atom

### Component causing the issue

web_server

### Example YAML snippet

```yaml
esphome:
  name: m5stack-atom-lite
  friendly_name: M5Stack ATOM Lite

esp32:
  board: m5stack-atom
  framework:
    type: arduino

logger:
  level: INFO

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Stack-Atom-Lite"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
  ota: False
```

### Anything in the logs that might be useful for us?

```txt
curl -I http://m5stack-atom-lite.local/events                                                                

HTTP/1.1 500 Internal Server Error
Content-Length: 0
Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
Connection: close
Accept-Ranges: none
```

### Additional information

Error in browser console

`Acess to resource at 'http://m5stack-atom-lite.local/events' from origin 'http://localhost:8000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.`
