### ISSUE TITLE
Pulse counter counts when input remains high

### ISSUE THREAD

**Issue by dansity** [esphome/issues#4445]
### The problem

If I'm missing something please let me know, but I have this frustrating scenario:
I want to build a wind speed meter (anemometer) which has a reed switch with a magnet. Sometimes the wind stops and the magnet is in a position when the input remains high and the pulse counter keeps counting pulses. For me it seems like it is checking the pin every cycle and if it is high it adds a count. However it should only count if the state of the pin changes from low to high.
This is what I'm experiencing:
L H H H H H  - > 5 count registered however it should be only one when low goes high

### Which version of ESPHome has the issue?

2023.4.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

Pulse counter

### Example YAML snippet

```yaml
sensor:
- platform: pulse_counter 
  pin:
    number: GPIO5
    mode:
     input: true
     pullup: false
     inverted: false
  id: wind_speed
  unit_of_measurement: 'm/s'
  name: "WS"
  icon: 'mdi:weather-windy'
  internal filter: 13us
  filters:
  - multiply: 0.005560619
  - sliding_window_moving_average:
     window_size: 20
     send_every: 20
```

### Anything in the logs that might be useful for us?

```txt
Log shows 900+ pulses if the pin remains high
```
