### ISSUE TITLE
i2s_audio component missing from esphome

### ISSUE THREAD

**Issue by wbarber69** [esphome/issues#4446]
### The problem

Failed config

media_player.i2s_audio: [source /config/esphome/esp-muse-luxe-382d3c.yaml:52]
  
  Component media_player.i2s_audio requires component i2s_audio.
  platform: i2s_audio
  name: muse_luxe
  dac_type: external
  i2s_lrclk_pin: GPIO25
  i2s_dout_pin: GPIO26
  i2s_bclk_pin: GPIO5
  mode: stereo
  mute_pin: 
    number: GPIO21
    inverted: True

### Which version of ESPHome has the issue?

2023.40

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.5

### What platform are you using?

ESP32

### Board

Espmuse luxe

### Component causing the issue

I2s_audio

### Example YAML snippet

```yaml
media_player:
  - platform: i2s_audio
    name: muse_luxe
    dac_type: external
    i2s_lrclk_pin: GPIO25
    i2s_dout_pin: GPIO26
    i2s_bclk_pin: GPIO5
    mode: stereo
    mute_pin:
      number: GPIO21
      inverted: true
```

### Anything in the logs that might be useful for us?

```txt
Failed config

media_player.i2s_audio: [source /config/esphome/esp-muse-luxe-382d3c.yaml:52]
  
  Component media_player.i2s_audio requires component i2s_audio.
  platform: i2s_audio
  name: muse_luxe
  dac_type: external
  i2s_lrclk_pin: GPIO25
  i2s_dout_pin: GPIO26
  i2s_bclk_pin: GPIO5
  mode: stereo
  mute_pin: 
    number: GPIO21
    inverted: True
```
