### ISSUE TITLE
Wrong time with UTC+4 timezone

### ISSUE THREAD

**Issue by definitio** [esphome/issues#445]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Python virtual environment

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (Sonoff Dual)

**Affected component:**

https://esphome.io/components/time.html

**Description of problem:**
Time is UTC, offset is ignored, e.g. when local time is 17:00, esphome has 13:00.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
time:
  - platform: ...
    timezone: Europe/Saratov
    ...
```

**Traceback (if applicable):**

```
INFO Detected timezone '+04' with UTC offset 4
```

**Additional information and things you've tried:**
