### ISSUE TITLE
HTTP Request timeout

### ISSUE THREAD

**Issue by nejc-cc** [esphome/issues#4459]
### The problem

I found that if timeout in HTTP Request is set to anything lower than 1 second, the code doesn't work. It compiles but instead of actually making a HTTP request, it constantly gives back _connection refused_ errors.
I noticed this problem only on ESP32 devices. I tested the code on ESP32-Wroom-32 and on ESP32-C3 modules, same result.
The same code seems to work just fine on ESP8266 devices.

### Which version of ESPHome has the issue?

2023.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.6

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1, variant esp32c3

### Component causing the issue

HTTP Request

### Example YAML snippet

```yaml
esphome:
  name: kb-v2
  friendly_name: kb-v2
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3

substitutions:
  kb_ip: 192.168.2.189

wifi:
  networks:
    - ssid: !secret ssid
      password: !secret pass
  reboot_timeout: 0s
  power_save_mode: none

web_server:
  port: 80
  local: true

http_request:
  useragent: esphome/device
  timeout: 500ms
  follow_redirects: false

sensor:
  - platform: rotary_encoder
    name: "Encoder rotation"
    pin_a:
      number: GPIO0
      inverted: false
      mode:
        input: true
    pin_b:
      number: GPIO1
      inverted: false
      mode:
        input: true
    publish_initial_value: true
    min_value: -200
    max_value: 200
    filters:
      - debounce: 50ms
    on_clockwise:
      - http_request.post:
          url: http://$kb_ip/button/right_turn/press
          verify_ssl: false
    on_anticlockwise:
      - http_request.post:
          url: http://$kb_ip/button/left_turn/press
          verify_ssl: false
    internal: false
```

### Anything in the logs that might be useful for us?

```txt
Web server log shows error like these:
HTTP Request failed; URL: http://192.168.2.189/button/left_turn/press; Error: connection refused; Duration: 2 ms
```

### Additional information

Setting the timeout to anything greater than 999ms seems to fix the problem. Usually the requests take from 10 to 200 ms max in my setup, mostly around the 30-50 ms range. This is the reason why I wanted to set timeout to 500ms in the first place :)
