### ISSUE TITLE
Invalid YAML syntax:  unacceptable character #x0000

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [esphome/issues#4466]
### The problem

So kind of odd: I wanted to work on adding some features to one of my devices and I am seeing this issue in all my yaml files in ESPHome. It is making whatever I put at the first line in the YAML red under-squiggle.

I have looked at the files in all kinds of editors and there is nothing at the 519th position.

And nothing will compile and deploy, I rebuilt my ESPHome setup using latest, stable, dev (docker tags), same issue. Chrome, Firefox, Safari, same...

```
Invalid YAML syntax:

unacceptable character #x0000: special characters are not allowed
  in "<unicode string>", position 519
```

![image](https://user-images.githubusercontent.com/1039517/235156419-f6b95c3a-22e6-4d08-b651-989893423c48.png)

### Which version of ESPHome has the issue?

2023.5.0-dev20230428

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

NA

### What platform are you using?

ESP32

### Board

many types of 32's

### Component causing the issue

uncertain, core might be the right answer

### Example YAML snippet

```yaml
substitutions:
  devicename: AirMonFamRm
  hostname: air-mon-family-room
  friendlyname: Family Room Air Quality
  location: Inside
  floor: 2ndfloor
  room: FamilyRoom
  sensor_interval: 15s
  mqtt_interval: 30s
  
esphome:
  name: ${hostname}
  friendly_name: ${friendlyname}
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/air-mon-family-room.yaml...
ERROR Error while reading config: Invalid YAML syntax:

unacceptable character #x0000: special characters are not allowed
  in "<unicode string>", position 519
```
