### ISSUE TITLE
Reset: Software Watchdog|Fatal exception:4 flag:3

### ISSUE THREAD

**Issue by Masterz69** [esphome/issues#4470]
### The problem

Devices rebooting with unregular time periods but same error:

```
Reset: Software Watchdog|Fatal exception:4 flag:3 (Software Watchdog) epc1:0x4026688e epc2:0x00000000 epc3:0x00000
```

Initially used D1 mini, now Shelly Uni, but same staff happens - same error.
ESPHome from 2023.2.4 till 2023.3.2 used - no changes.
Sometimes it work couple of minutes, sometime several hours.

Only connected sensors: x6 DS18B20, nothing else.

Device information:
```
2023.3.2|Flash: 2048kB Speed:40MHz Mode:DOUT|Chip: 0x0078ebfb|SDK: 2.2.2-dev(38a443e)|Core: 3.0.2|Boot: 31|Mode: 1|CPU: 80|Flash: 0x0015400b|Reset: Software Watchdog|Fatal exception:4 flag:3 (Software Watchdog) epc1:0x4026688e epc2:0x00000000 epc3:0x00000
```

Any suggestions/ideas are welcome.

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.5

### What platform are you using?

ESP8266

### Board

Shelly Uni, D1 mini

### Component causing the issue

not sure

### Example YAML snippet

```yaml
substitutions:
  name: "sns-boiler"
  friendly_name: sns Boiler
  comment: Shelly Uni

  sensor_interval:     '9s'
  sensor_delta_temp: '0.05'

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${comment}

esp8266:
  board: esp_wroom_02
  restore_from_flash: true

...

dallas:
  - pin: 
      number: GPIO05
      mode:
        input: True
        pullup: True
    update_interval: ${sensor_interval}

sensor:  
  - platform: dallas
    address: 0xaf00000001b25428
    name: "Boil"
    filters:
      - filter_out: 85.0
      - delta: ${sensor_delta_temp}
```
