### ISSUE TITLE
Could not allocate memory for JSON document! Requested 272 bytes, largest free heap block: 272 bytes

### ISSUE THREAD

**Issue by zibous** [esphome/issues#4472]
### The problem

![d1mini-esp8266MOD-12F](https://user-images.githubusercontent.com/30198737/235361615-dabe5085-8519-4d30-b021-98ab856b7b99.png)

- Processing water-meter-d1mini (board: esp12e; framework: arduino; platform: platformio/espressif8266@3.2.0)
   - Jason Error
     Could not allocate memory for JSON document! Requested 272 bytes, largest free heap block: 272 bytes 
   - starts again and again at certain intervals
   
![d1Mini-wemos](https://user-images.githubusercontent.com/30198737/235361662-0a095cfc-5ac2-42bb-b206-ca14791647b0.png)

- Processing water-meter-d1mini (board: d1_mini; framework: arduino; platform: platformio/espressif8266@3.2.0)
   - works w/o errors

### Which version of ESPHome has the issue?

2023.5.0-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Home Assistant 2023.4.6 Frontend 20230411.1 - latest

### What platform are you using?

ESP8266

### Board

D1MINI

### Component causing the issue

JSON - Homeassistant API

### Example YAML snippet

```yaml
---
## ------------------------------------------------------------------
## WMBUS METER D1 MINI + CC1101 for Diehl IZAR RC 868 I R4 PL
##
## usage:  1. Using Homassistant API (discovery + devices)
##         2. Using HTTP Post to service server
##         3. Using wmbusmeters i a pipe
##
## this version shows all watermeters. Use this for the first test
##
## Remark:
##   Some Wemos D1 Min has memory problems, for me one is working
##   another one (same order) reboots with JSON Errors.
##   ESP8266-12F Mini NodeMcu mit ESP8266-12F
## ------------------------------------------------------------------
substitutions:
  device_name_short: "water-meter-d1mini"
  device_description: "Wasserzähler Wemos D1 Min, CUL - CC1101, IZAR module (Diehl IZAR RC 868 I R4 PL (SzczepanLeon) - my Watermeter"
  update_interval: 60s

  log_level: "DEBUG"
  appversion: "2.0.5"

  domain: !secret domain
  service_url: !secret service_host
  service_enabled: "false"
  service: "izar.watermeter"

  # additional sensors
  disabled_addOns: "true"

## ----------------------------------------------------------------
## HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
## ----------------------------------------------------------------
esp8266:
  # board: d1_mini
  board: esp12e
  restore_from_flash: true

esphome:
  name: ${device_name_short}
  comment: ${device_description}
  project:
    name: "OE9psj.wmbus-minid1"
    version: ${appversion}
  build_path: ./build/${device_name_short}

  # ----------------------------------------------------------------
  # External components for wmbusmeter
  # ----------------------------------------------------------------
  on_boot:
    # At this priority, pretty much everything should already be initialized.
    priority: -100.0
    then:
      - globals.set:
          id: boot_counter
          value: !lambda "return id(boot_counter)+=1;"
      - logger.log:
          level: INFO
          tag: "BOOT"
          format: "BOOTMESSAGE:${device_name_short} API is connected, Device ready!"
  on_shutdown:
    priority: 700
    then:
      - logger.log:
          level: INFO
          tag: "BOOT"
          format: "BOOTMESSAGE:${device_name_short} is down!"

## ----------------------------------------------------------------
## External components
## ----------------------------------------------------------------
external_components:
  # uses the latest version from SzczepanLeon
  # https://github.com/SzczepanLeon/esphome-components
  # You can make ESPHome check the repository every time by setting this option to 0s
  - source: github://SzczepanLeon/esphome-components@main
    refresh: 0s
    components: [wmbus]

  # use local component from
  # https://github.com/zdzichu6969/esphome-components
  - source:
      type: local
      path: custom_components
    components: [backup]

  # use local component from
  # https://github.com/TheStaticTurtle/esphome_syslog
  # - source:
  #     type: local
  #     path: custom_components
  #   components: [syslog]

  # use local component from
  # https://github.com/ssieb/custom_components/tree/master/components/heapmon
  # - source:
  #     type: local
  #     path: custom_components
  #   components: [heapmon]

## ---------------------------------------------------
## syslog service
## ---------------------------------------------------
# syslog:
#   ip_address: !secret syslog_server
#   port: !secret syslog_port
#   min_level: DEBUG
#   enable_logger: true

# ----------------------------------------------------------------
# Save your ESPHome device configuration in firmware and and
# recover it if you lost source files.
# ----------------------------------------------------------------
# Just download it from http://water-meter-izar.local/config.yaml
backup:
  auth:
    username: !secret web_username
    password: !secret web_password
  force_update: false


## ----------------------------------------------------------------
## Global variables
## ----------------------------------------------------------------
globals:
  - id: boot_counter
    type: int
    restore_value: yes
    initial_value: "0"

  - id: int_default
    type: int
    restore_value: no
    initial_value: "0"

  - id: float_default
    type: float
    restore_value: no
    initial_value: "0.00"

  - id: m3toliter
    type: float
    initial_value: "1000.00"
    restore_value: yes

  - id: last_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: current_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: hour_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: daily_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: yesterday_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: week_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: month_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: lastmonth_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: year_value
    type: float
    restore_value: yes
    initial_value: "0.00"

## ---------------------------------------------------
## WIFI Settings 3 wifis
## ---------------------------------------------------
wifi:
  networks:
    - ssid: !secret ssid3_name
      password: !secret ssid3_pswd
      priority: 0
    - ssid: !secret ssid1_name
      password: !secret ssid1_pswd
      priority: 1
    - ssid: !secret ssid2_name
      password: !secret ssid2_pswd
      priority: 2
  domain: !secret domain

## ---------------------------------------------------
## The captive portal component in ESPHome is a
## fallback mechanism for when connecting to the
## configured WiFi fails.
## ---------------------------------------------------
captive_portal:

logger:
  id: appslogger
  level: ${log_level}
  baud_rate: 0 #disable logging over uart

## ---------------------------------------------------
## OTA Updates
## ---------------------------------------------------
ota:
  password: !secret ota_pswd
  on_error:
    then:
      - logger.log:
          format: "OTA update error %d"
          args: ["x"]

## ----------------------------------------------------------------------
## LOCAL WEBSERVER Settings, local settings - no internet
## Include supporting javascript locally allowing it to work
## without internet access.
## local: true  ## without internet access.
## local: false ## with internet access.
## ----------------------------------------------------------------------
web_server:
  port: 80
  version: 2
  local: true

## ---------------------------------------------------
# Enable Home Assistant API
## ---------------------------------------------------
# Homeassistant service call:
# service: esphome.water_meter_set_water_val
# data:
#  water_val_hour: 0.03
#  water_val_day: 0.248
#  water_val_yesterday: 0.178
#  water_val_week: 0.248
#  water_val_month: 1.94
#  water_val_year: 14.256
#  water_val_lastmonth: 9.59
## ---------------------------------------------------
api:
  id: espapiwm2_d1
  port: 6053
  reboot_timeout: 0s
  services:
    - service: set_water_val
      variables:
        water_val_hour: float
        water_val_day: float
        water_val_yesterday: float
        water_val_week: float
        water_val_month: float
        water_val_year: float
        water_val_lastmonth: float
      then:
        - globals.set:
            id: hour_value
            value: !lambda |-
              if((water_val_hour) and (water_val_hour)>0.001){
                ESP_LOGI("main", "Set hourly value to: %f", water_val_hour);
                return (water_val_hour);
              }else{
                ESP_LOGI("main", "Skip setting hourly value");
                return id(hour_value);
              };
              id(waterhour).publish_state(id(hour_value));

        - globals.set:
            id: daily_value
            value: !lambda |-
              if((water_val_day) and (water_val_day)>0.001){
                ESP_LOGI("main", "Set daily value to: %f", water_val_day);
                return (water_val_day);
              }else{
                ESP_LOGI("main", "Skip setting hourly value");
                return id(hour_value);
              };
              id(waterday).publish_state(id(daily_value));

        - globals.set:
            id: yesterday_value
            value: !lambda |-
              if((water_val_yesterday) and (water_val_yesterday)>0.001){
                ESP_LOGI("main", "Set yesterday value to: %f", water_val_yesterday);
                return (water_val_yesterday);
              }else{
                ESP_LOGI("main", "Skip setting yesterday value");
                return id(yesterday_value);
              };
              id(wateryesterday).publish_state(id(hour_value));

        - globals.set:
            id: week_value
            value: !lambda |-
              if((water_val_week) and (water_val_week)>0.001){
                ESP_LOGI("main", "Set weekly value to: %f", water_val_week);
                return (water_val_week);
              }else{
                ESP_LOGI("main", "Skip setting weekly value");
                return id(week_value);
              };
              id(waterweek).publish_state(id(week_value));

        - globals.set:
            id: month_value
            value: !lambda |-
              if((water_val_month) and (water_val_month)>0.001){
                ESP_LOGI("main", "Set last montj value to: %f", water_val_month);
                return (water_val_month);
              }else{
                ESP_LOGI("main", "Skip setting monthly value");
                return id(week_value);
              };
              id(watermonth).publish_state(id(month_value));

        - globals.set:
            id: lastmonth_value
            value: !lambda |-
              if((water_val_lastmonth) and (water_val_lastmonth)>0.001){
                ESP_LOGI("main", "Set last month value to: %f", water_val_lastmonth);
                return (water_val_lastmonth);
              }else{
                ESP_LOGI("main", "Skip setting last month value");
                return id(lastmonth_value);
              };
              id(waterlastmonth).publish_state(id(lastmonth_value));

        - globals.set:
            id: year_value
            value: !lambda |-
              if((water_val_year) and (water_val_year)>0.001){
                ESP_LOGI("main", "Set last yearly value to: %f", water_val_year);
                return (water_val_year);
              }else{
                ESP_LOGI("main", "Skip setting last yearly value");
                return id(week_value);
              };
              id(wateryear).publish_state(id(year_value));

        - logger.log:
            format: "All new Values set: hour: %.1f, day: %.1f, week: %.1f, month: %.1f, lastmonth: %.1f, year: %.1f"
            args:
              [
                "id(hour_value)",
                "id(daily_value)",
                "id(week_value)",
                "id(month_value)",
                "id(lastmonth_value)",
                "id(year_value)",
              ]

## ---------------------------------------------------
## SNTP Time server
## ---------------------------------------------------
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - 0.at.pool.ntp.org
      - 0.pool.ntp.org
      - 1.pool.ntp.org

    on_time_sync:
      then:
        - logger.log: "Synchronized sntp clock"

    # reset hourly value
    on_time:
      - seconds: 0
        minutes: 0
        then:
          - globals.set:
              id: hour_value
              value: "0.00"
          - lambda: id(waterhour).publish_state(id(hour_value));
          - logger.log: Reset value hour, starting next hour

      # reset daily value and set yesterday value
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: id(yesterday_value)=id(daily_value);
          - lambda: id(wateryesterday).publish_state(id(yesterday_value));
          - lambda: id(daily_value)=0.00;
          - lambda: id(waterday).publish_state(id(daily_value));
          - logger.log: Set yesterday value and reset value daily, starting new day

      # reset weekly value, start new week
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_week: MON
        then:
          - globals.set:
              id: week_value
              value: "0.00"
          - lambda: id(waterweek).publish_state(id(week_value));
          - logger.log: Reset value weekly, starting new week

      # reset monthly value and set last month value
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_month: 1
        then:
          - globals.set:
              id: month_value
              value: "0.00"
          - lambda: id(watermonth).publish_state(id(month_value));
          - lambda: |-
              if(id(waterdisplay).state){
                id(lastmonth_value)=id(waterdisplay).state;
              }
          - logger.log: Reset value monthly, starting new month

      # new year, reset yearly value
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_month: 1
        months: JAN
        then:
          - globals.set:
              id: year_value
              value: "0.00"
          - lambda: id(wateryear).publish_state(id(year_value));
          - logger.log: Reset value yearly, starting new year

## ---------------------------------------------------
## Prepare for sending HTTP requests
## ---------------------------------------------------
http_request:
  id: http_request_data
  useragent: ${service}
  timeout: 10s

## ---------------------------------------------------
## Post resultdata to the service url
## ---------------------------------------------------
script:
  - id: post_device_state
    then:
      - if:
          condition:
            lambda: return "${service_enabled} =='true'";
          then:
            - logger.log: "Post new data to the ${service_url}${device_name_short}, service enabled: ${service_enabled}"
            - http_request.post:
                url: "${service_url}/${device_name_short}"
                verify_ssl: false
                headers:
                  Content-Type: application/json
                json: |-
                  root["device"] = "${device_name_short}";
                  root["waterdisplay"] = id(waterdisplay).state;
                  root["current"] = id(id(watercurrent)).state;
                  root["hour"] = id(waterhour).state;
                  root["day"] = id(waterday).state;
                  root["yesterday"] = id(wateryesterday).state;
                  root["week"] = id(waterweek).state;
                  root["month"] = id(watermonth).state;
                  root["lastmonth"] = id(waterhour).state;
                  root["year"] = id(wateryear).state;
                  root["bootcounter"] = id(bootcounter).state;
                  root["version"] = "${device_name_short} ${appversion}";
                  root["time"] = id(sntp_time).now().strftime("%Y-%m-%d %H:%M:%S");
                on_response:
                  then:
                    - lambda: |-
                        if (status_code == 200) {
                        } else {
                            ESP_LOGI ("http_post", "HTTP POST failed");
                        }

## ---------------------------------------------------
## WMBUS DEVICE D1MINI WEMOS --> CC1101
## ---------------------------------------------------
wmbus:
  mosi_pin: GPIO13  #D7  MOSI Attached to Hardware SPI controller MOSI SPI Interface
  miso_pin: GPIO12  #D6  MISO Attached to Hardware SPI controller MISO SPI Interface
  clk_pin: GPIO14   #D5  SCK  Attached to Hardware SPI controller CLK
  cs_pin: GPIO15    #D8  CSN  Attached to Hardware SPI controller, Controls Boot Mode; CS SPI Interface 10k Pull-Down, boot fails if pulled high !!!
  gdo0_pin: GPIO05  #D1  High Impedance !
  gdo2_pin: GPIO04  #D2  High Impedance !

  ## ---------------------------------------------------
  ## Using wmbusmeters i a pipe
  ## enable this if you have wmbusmeters installed
  ## ---------------------------------------------------
  ## clients:
  ##  - name: "wmbusmeters"
  ##    ip_address: !secret wmbusmeter_host
  ##    port: 7227
  ##    format: rtlwMBus
  ##    transport: UDP

  ## setting: wmbusmeters.conf
  ## loglevel: normal
  ## device: rtlwmbus:CMD(nc -lku 7227)
  ## donotprobe: /dev/ttyAMA0
  ## logtelegrams: false
  ## format: json
  ## logfile: /dev/stdout
  ## shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"

  ## ---------------------------------------------------
  ## led_pin: GPIO02  ## D4 Build_in LED
  ## ---------------------------------------------------
  # led_blink_time: "8s"

## ---------------------------------------------------
## SWITCHES
## ---------------------------------------------------
switch:
  # reset boot counter value
  - platform: template
    name: Reset Boot Counter
    turn_on_action:
      then:
        - lambda: |-
            id(boot_counter) = id(int_default);
            id(bootcounter).publish_state(id(boot_counter));
        - logger.log:
            level: INFO
            tag: "BOOT"
            format: "${device_name_short} reset boot counter o.k!"

  # reset all global vars
  - platform: template
    name: Reset values
    turn_on_action:
      then:
        - lambda: |-
            id(last_value) = id(float_default);
            id(boot_counter) = id(int_default);
            id(bootcounter).publish_state(id(boot_counter));
            id(current_value) = id(float_default);
            id(watercurrent).publish_state(id(current_value));
            id(hour_value) = id(float_default);
            id(waterhour).publish_state(id(hour_value));
            id(daily_value) = id(float_default);
            id(waterday).publish_state(id(daily_value));
            id(yesterday_value) = id(float_default);
            id(wateryesterday).publish_state(id(yesterday_value));
            id(week_value) = id(float_default);
            id(waterweek).publish_state(id(week_value));
            id(month_value) = id(float_default);
            id(watermonth).publish_state(id(month_value));
            id(lastmonth_value) = id(float_default);
            id(waterlastmonth).publish_state(id(lastmonth_value));
            id(year_value) = id(float_default);
            id(wateryear).publish_state(id(year_value));
        - logger.log: all values reset!

  - platform: restart
    name: "Restart"
    id: restart_switch

## ---------------------------------------------------
## SENSORS
## ---------------------------------------------------
sensor:
  # water display

  - platform: wmbus
    # Meter ID (usually from sticker). Can be specified as decimal or hex.
    # only hex is working for my watermeter !
    # see: https://github.com/SzczepanLeon/esphome-components/issues/6
    # edit watermeterid in the secrets file
    meter_id: !secret watermeterId
    type: izar
    ## settings to add the watermeterid to the lqi, rssi and total_water_m3
    add_prefix: false
    # The LQI value reported by the CC1101 is a 7 bit unsigned number with a range from 0 to 127.
    # Note that a lower value indicates a better link.
    # The LQI of a received packet will be bad (higher number) when there is lot of interference.
    lqi:
      id: wmbus_cc1101_lqi
      name: "Wlan CC1101 LQI"
      entity_category: "diagnostic"
    # The RSSI value reported by the CC1101 is a 8 bit signed number with an effective
    # range from -138 dBm to -10.5 dBm when the CC1101 is operating around 868 MHz.
    # RSSI stands for received signal strength (power) indication (in dBm).
    # A higher value indicates higher power.
    rssi:
      id: wmbus_cc1101_rssi
    total_water_m3:
      name: "Wasseruhr Anzeige"
      id: "waterdisplay"
      unit_of_measurement: "m³"
      state_class: total_increasing
      device_class: "water"
      accuracy_decimals: 3
      on_value:
        then:
          - lambda: |-
              ESP_LOGI("SENSOR", "Water Display value: %f, last value: %f", id(waterdisplay).state, id(last_value));
              if ((id(last_value) > 0.00) and (id(waterdisplay).state)>(id(last_value)) ) {
                id(current_value) = float( id(waterdisplay).state - id(last_value) ) * id(m3toliter);
                id(watercurrent).publish_state(id(current_value));
                id(hour_value)+=id(current_value);
                id(waterhour).publish_state(id(hour_value));
                id(daily_value)+=id(current_value);
                id(waterday).publish_state(id(daily_value));
                id(week_value)+=id(current_value);
                id(waterweek).publish_state(id(week_value));
                id(month_value)+=id(current_value);
                id(watermonth).publish_state(id(month_value));
                id(year_value)+=id(current_value);
                id(wateryear).publish_state(id(year_value));
                ESP_LOGI("SENSOR", "Set current value to %f litre and publish the data", id(watercurrent));
                if ( ${service_enabled} == true){
                  id(post_device_state).execute();
                }
              }else{
                id(current_value) = 0.00;
                id(watercurrent).publish_state(id(current_value));
                ESP_LOGI("SENSOR", "Reset current value to: %f", id(watercurrent));
              }
              id(last_value)=id(waterdisplay).state;

          - text_sensor.template.publish:
              id: watermeter_lastupdate
              state: !lambda |-
                char str[20];
                time_t currTime = id(sntp_time).now().timestamp;
                strftime(str, sizeof(str), "%Y-%m-%dT%H:%M:%S", localtime(&currTime));
                return (std::string) str;

  # water current
  - platform: template
    name: Wasser Aktuell
    id: "watercurrent"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    state_class: "measurement"
    device_class: "water"
    lambda: |-
      return (id(current_value));

  # water current hour
  - platform: template
    name: Wasser Stunde
    id: "waterhour"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    state_class: total_increasing
    device_class: "water"
    lambda: |-
      return (id(hour_value));

  # water today
  - platform: template
    name: Wasser Tag
    id: "waterday"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    device_class: "water"
    state_class: total_increasing
    lambda: |-
      return (id(daily_value));

  # water yesterday
  - platform: template
    name: Wasser Gestern
    id: "wateryesterday"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    device_class: "water"
    state_class: total_increasing
    lambda: |-
      return (id(yesterday_value));

  # water current week
  - platform: template
    name: Wasser Woche
    id: "waterweek"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    device_class: "water"
    state_class: total_increasing
    lambda: |-
      return (id(week_value));

  # water current month
  - platform: template
    name: Wasser Monat
    id: "watermonth"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    state_class: total_increasing
    device_class: "water"
    lambda: |-
      return (id(month_value));

  # water current year
  - platform: template
    name: Wasser Jahr
    id: "wateryear"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    state_class: total_increasing
    device_class: "water"
    lambda: |-
      return (id(year_value));

  # water last month
  - platform: template
    name: Wasser letzer Monat
    id: "waterlastmonth"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    state_class: "measurement"
    device_class: "water"
    lambda: |-
      return (id(lastmonth_value));

  # device boot counter
  - platform: template
    name: Boot counter
    id: bootcounter
    accuracy_decimals: 0
    state_class: "measurement"
    entity_category: "diagnostic"
    lambda: |-
      return (id(boot_counter));

  # device uptime human reading format
  # only internal used
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    internal: ${disabled_addOns}
    update_interval: ${update_interval}
    unit_of_measurement: seconds
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

  # Wifi quality RSSI
  # only internal used (memory bug D1MINI ??)
  - platform: wifi_signal
    name: Wlan Signal
    id: wifi_signal_db
    update_interval: 60s
    internal: true
    entity_category: "diagnostic"

  # Wifi quality RSSI in percentage
  # # Received Signal Strength (RSSI) is a measure of incoherent (raw) RF power in a channel.
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "Wlan ESP32 Qualität"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

  # CC1101 quality RSSI in percentage
  # Received Signal Strength (RSSI) is a measure of incoherent (raw) RF power in a channel.
  - platform: copy
    source_id: wmbus_cc1101_rssi
    name: "Wlan CC1101 RSSI"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

  #  Shows free space ESP.getFreeHeap
  # - platform: heapmon
  #   id: heapspace
  #   name: "Free Space"
  #   state_class: "measurement"
  #   entity_category: "diagnostic"

## ---------------------------------------------------
## BINARY SENSOR
## ---------------------------------------------------
binary_sensor:
  # simulate led state
  - platform: template
    name: Status Led
    id: statusled
    entity_category: "diagnostic"
    lambda: "return id(current_value) > 0;"

## ---------------------------------------------------
## TEXT SENSOR
## ---------------------------------------------------
text_sensor:
  # device version
  # disabled for api (memory ??)
  - platform: version
    name: Version
    id: appver
    internal: ${disabled_addOns}
    entity_category: "diagnostic"

  # device online time
  # disabled for api (memory ??)
  - platform: template
    name: Online seit
    id: uptime_human
    internal: ${disabled_addOns}
    icon: mdi:clock-start
    entity_category: "diagnostic"

  # waterdisplay last update
  - platform: template
    name: Zählerstand aktualisiert
    id: watermeter_lastupdate
    icon: mdi:clock-start
    entity_category: "diagnostic"

  # device timestamp
  # disabled for api (memory ??)
  - platform: template
    name: Timestamp
    id: systime
    entity_category: "diagnostic"
    internal: ${disabled_addOns}
    lambda: char str[20];
      time_t currTime = id(sntp_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%dT%H:%M:%S", localtime(&currTime));
      return (std::string) str;

  # simple rest get message for all watermeter data
  # curl -i http://water-meter-izar.local/text_sensor/watermeterdata
  - platform: template
    id: watermeterdata
    update_interval: ${update_interval}
    internal: true
    lambda: |-
      char buf[512];
      sprintf(buf, "%.3f|%.3f|%.3f|%.3f|%.3f|%.3f|%.3f|%.3f|%.3f|%s",
             id(waterdisplay).state,
             id(current_value),
             id(hour_value),
             id(daily_value),
             id(yesterday_value),
             id(week_value),
             id(month_value),
             id(lastmonth_value),
             id(year_value),
             id(systime).state.c_str()
             );
      std::string s = buf;
      return s;
```

### Anything in the logs that might be useful for us?

```txt
17:38:28][D][sensor:102]: 'Wlan CC1101 LQI': Sending state 128.00000  with 0 decimals of accuracy
[17:38:28][D][sensor:102]: 'wmbus_cc1101_rssi': Sending state -61.00000 dBm with 0 decimals of accuracy
[17:38:28][D][sensor:102]: 'Wlan CC1101 RSSI': Sending state 78.00000 % with 0 decimals of accuracy
[17:38:28][D][sensor:102]: 'Wasseruhr Anzeige': Sending state 470.40399 m³ with 3 decimals of accuracy
[17:38:28][I][SENSOR:615]: Water Display value: 470.403992, last value: 470.403992
[17:38:28][D][sensor:102]: 'Wasser Aktuell': Sending state 0.00000 L with 2 decimals of accuracy
[17:38:28][I][SENSOR:636]: Reset current value to: 0.000000
[17:38:28][D][text_sensor:064]: 'Zählerstand aktualisiert': Sending state '2023-04-30T17:38:28'
[17:38:28][E][json:039]: Could not allocate memory for JSON document! Requested 256 bytes, largest free heap block: 256 bytes
[17:38:28][E][json:039]: Could not allocate memory for JSON document! Requested 216 bytes, largest free heap block: 216 bytes
[17:38:28][D][sensor:102]: 'Wasser Stunde': Sending state 1.98364 L with 2 decimals of accuracy
[17:38:30][D][text_sensor:064]: 'Timestamp': Sending state '2023-04-30T17:38:30'
[17:38:33][D][text_sensor:064]: 'Online seit': Sending state '1m 43s'
[17:38:33][D][text_sensor:064]: 'Zählerstand aktualisiert': Sending state '2023-04-30T17:38:28'
[17:38:35][D][wmbus:120]: Meter ID [0x43410778] RSSI: -66 dBm LQI: 129 Mode: T1 not found in configuration T: 1944A511780741434418A271150013CC0975D8D510581CE0FD9F (26)
[17:38:35][D][sensor:102]: 'Wasser Aktuell': Sending state 0.00000 L with 2 decimals of accuracy
[17:38:36][D][sensor:102]: 'Wasser letzer Monat': Sending state 8224.40039 L with 2 decimals of accuracy
[17:38:44][D][wmbus:120]: Meter ID [0x43410778] RSSI: -66 dBm LQI: 132 Mode: T1 not found in configuration T: 1944A511780741434418A201150013CC6CB92484F56311E1B292 (26)
[17:38:45][I][wmbus:061]: Using driver 'izar' for ID [0x43430778] RSSI: -60 dBm LQI: 128 Mode: T1 T: 1944A511780743434418A251150013CED1877AE7EACE9035EFCC (26)
[17:38:45][D][sensor:102]: 'Wlan CC1101 LQI': Sending state 128.00000  with 0 decimals of accuracy
[17:38:45][D][sensor:102]: 'wmbus_cc1101_rssi': Sending state -60.00000 dBm with 0 decimals of accuracy
[17:38:45][D][sensor:102]: 'Wlan CC1101 RSSI': Sending state 80.00000 % with 0 decimals of accuracy
[17:38:45][D][sensor:102]: 'Wasseruhr Anzeige': Sending state 470.40399 m³ with 3 decimals of accuracy
[17:38:45][I][SENSOR:615]: Water Display value: 470.403992, last value: 470.403992
[17:38:45][D][sensor:102]: 'Wasser Aktuell': Sending state 0.00000 L with 2 decimals of accuracy
[17:38:45][I][SENSOR:636]: Reset current value to: 0.000000
[17:38:45][D][text_sensor:064]: 'Zählerstand aktualisiert': Sending state '2023-04-30T17:38:45'
[17:38:45][E][json:039]: Could not allocate memory for JSON document! Requested 152 bytes, largest free heap block: 152 bytes
[17:38:45][E][json:039]: Could not allocate memory for JSON document! Requested 112 bytes, largest free heap block: 112 bytes
[17:38:53][D][wmbus:120]: Meter ID [0x43410778] RSSI: -66 dBm LQI: 128 Mode: T1 not found in configuration T: 1944A511780741434418A211150013CC7B966D2FD4B0C83AAB90 (26)
[17:38:54][I][wmbus:061]: Using driver 'izar' for ID [0x43430778] RSSI: -60 dBm LQI: 128 Mode: T1 T: 1944A511780743434418A261150013CEE8F6A01A88BAFA58C4CB (26)
[17:38:54][D][sensor:102]: 'Wlan CC1101 LQI': Sending state 128.00000  with 0 decimals of accuracy
[17:38:54][D][sensor:102]: 'wmbus_cc1101_rssi': Sending state -60.00000 dBm with 0 decimals of accuracy
[17:38:54][D][sensor:102]: 'Wlan CC1101 RSSI': Sending state 80.00000 % with 0 decimals of accuracy
[17:38:54][D][sensor:102]: 'Wasseruhr Anzeige': Sending state 470.40399 m³ with 3 decimals of accuracy
[17:38:54][I][SENSOR:615]: Water Display value: 470.403992, last value: 470.403992
[17:38:54][D][sensor:102]: 'Wasser Aktuell': Sending state 0.00000 L with 2 decimals of accuracy
[17:38:54][I][SENSOR:636]: Reset current value to: 0.000000
[17:38:54][D][text_sensor:064]: 'Zählerstand aktualisiert': Sending state '2023-04-30T17:38:54'
[17:38:54][E][json:039]: Could not allocate memory for JSON document! Requested 152 bytes, largest free heap block: 152 bytes
[17:38:54][E][json:039]: Could not allocate memory for JSON document! Requested 200 bytes, largest free heap block: 200 bytes
[17:39:01][D][wmbus:120]: Meter ID [0x43410778] RSSI: -66 dBm LQI: 128 Mode: T1 not found in configuration T: 1944A511780741434418A221150013CC42E7B7D2B6C4A2578097 (26)
[17:39:02][I][wmbus:061]: Using driver 'izar' for ID [0x43430778] RSSI: -60 dBm LQI: 128 Mode: T1 T: 1944A511780743434418A271150013CEFFD9E9B1A9692383DDC9 (26)
```
```


### Additional information

_No response_
