### ISSUE TITLE
Restore_From_Flash suddenly stopped working after updating HA

### ISSUE THREAD

**Issue by rajkhan0714** [esphome/issues#4473]
### The problem

I updated Home Assistant yesterday and all of a sudden all my ESP devices stopped restoring states after power cut.

### Which version of ESPHome has the issue?

2023.4.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.6

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

restore_from_flash

### Example YAML snippet

```yaml
esphome:
  name: "bed-switch-esp01"

esp8266:
  board: esp01_1m
  board_flash_mode: qio
  restore_from_flash: true
  
preferences:
  flash_write_interval: 5min
  
# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  domain: .local
  reboot_timeout: 15min
  fast_connect: true
   

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp01BedSwitch Fallback"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_password

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  
switch:
  - platform: gpio
    name: "Light 1"
    pin: 3
    inverted: yes

  - platform: gpio    
    name: "Light 3"
    pin: 0
    inverted: yes
    
  - platform: gpio    
    name: "wipro power"
    pin: 1
    inverted: yes

  - platform: gpio    
    name: "fan"
    pin: 2
    inverted: yes

  - platform: restart
    id: bed_switch_esp01_restart
    name: “Restart”
```
