### ISSUE TITLE
[pulse_meter] fails reading higher frequencies

### ISSUE THREAD

**Issue by pkejval** [esphome/issues#4479]
### The problem

I found out that pulse_meter is unable to read more than 120 Hz of pulses (7500 RPM). With increasing frequency it then shows only these values - 8600 RPM, 10 000 RPM and 20 000 RPM - completely off values. pulse_counter sensor is working fine even with much higher frequencies.

It can be easily tested with XAML posted here. Just connect GPIO2 with GPIO22. I made ledc output where you can set frequency at runtime. RPMs are limited in both cases if set to PULSE or EDGE mode.

### Which version of ESPHome has the issue?

2023.4.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

wemos_d1_mini32

### Component causing the issue

pulse_meter

### Example YAML snippet

```yaml
number:
  - platform: template
    id: freq
    name: Frequency
    mode: BOX
    min_value: 0
    max_value: 10000
    initial_value: 100
    step: 1
    optimistic: true
    set_action:
      - lambda: 'id(pin_out).update_frequency(x);'

output:
  - platform: ledc
    pin: GPIO2
    id: pin_out

 sensor:
   - platform: pulse_meter
     id: RPM
     name: "Engine"
     pin: 
       number: GPIO22
       inverted: false
       mode:
         input: true
         pulldown: true
     unit_of_measurement: 'RPM'
     accuracy_decimals: 0
     timeout: 1.5s          
     filters:
       - lambda: 'return 100 * round(x / 100);'
```

### Anything in the logs that might be useful for us?

```txt
When I use pulse_counter I can measure RPM for hundreds, thousands of Hz without problem.

sensor:
  - platform: pulse_counter
    id: RPM
    name: "Engine"
    pin: 
      number: GPIO22
      inverted: false
      mode:
        input: true
        pulldown: true
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    filters:
      - lambda: 'return 100 * round(x / 100);'
    update_interval: 500ms
```
