### ISSUE TITLE
Unable to install platformio/tool-esptoolpy

### ISSUE THREAD

**Issue by alistair23** [esphome/issues#4486]
### The problem

When trying to build for a esp32dev board I get the following error

```
Tool Manager: Installing platformio/tool-esptoolpy @ ~1.40400.0
INFO Installing platformio/tool-esptoolpy @ ~1.40400.0
Error: Could not find the package with 'platformio/tool-esptoolpy @ ~1.40400.0' requirements for your system 'linux_x86_64'
```

### Which version of ESPHome has the issue?

v2023.4.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.0

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

platformio/tool-esptoolpy

### Example YAML snippet

```yaml
esphome:
  name: esp32-devkitc-water-level

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO33
    echo_pin: GPIO35
    name: "Ultrasonic Sensor"
    update_interval: 360s
    accuracy_decimals: 3
    filters:
      - offset: -0.335
      - multiply: -1
```

**Comment by alistair23** [comment]
So specifying this fixes the issue:

```
esp32:
  board: esp32dev
  framework:
    type: arduino
    platform_version: 5.2.0
```

Note that `platform_version`s
- 5.3.0
- 5.4.0
- 6.3.2

Also have the same error
