### ISSUE TITLE
FREENOVE ESP32-S3-WROOM-1

### ISSUE THREAD

**Issue by indevor** [esphome/issues#4492]
### The problem

To get the camera to work in this board you need:
https://github.com/Freenove/Freenove_ESP32_S3_WROOM_Board

![Freenove_ESP32_S3_WROOM](https://github.com/Freenove/Freenove_ESP32_S3_WROOM_Board/blob/main/Board.jpg)

1. Set up the yaml. 
Disable PSRAM using code for YAML: 

```
external_components:
  - source:
     type: git
      url: https://github.com/MichaKersloot/esphome_custom_components
   components: [ esp32_camera ]
```

This component uses

`this->config_.fb_location = CAMERA_FB_IN_DRAM;`

Or use a different board:

```
esp32:
 # board: esp32-s3-devkitc-1
  board: seeed_xiao_esp32s3
  variant: esp32s3 
  framework:
    type: arduino
    version: 2.0.8
    platform_version: 6.2.0
```

This board is configured to use PSRAM, then you can use the standard code without the component.
I'm not sure if it uses PSRAM with the other board, but on initialization it found it and everything works.

[00:19:08][C][psram:020]: PSRAM:
[00:19:08][C][psram:021]: Available: YES
[00:19:08][C][psram:024]: Size: 7 MB

However, everything is still very slow.

The Arduino code is much faster, ~30 fps 1270x720

### Which version of ESPHome has the issue?

2023.4.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.1

### What platform are you using?

ESP32

### Board

Freenove esp-32-s3-wroom-1 camera

### Example YAML snippet

```yaml
esphome:
  name: cam-bathroom
  friendly_name: cam-bathroom

esp32:
 # board: esp32-s3-devkitc-1
  board: seeed_xiao_esp32s3
  variant: esp32s3 
  framework:
    type: arduino
    version: 2.0.8
    platform_version: 6.2.0

  

# Enable logging
logger:
  level: DEBUG
# Enable Home Assistant API


captive_portal:

#external_components:
#  - source:
#      type: git
#      url: https://github.com/MichaKersloot/esphome_custom_components
#    components: [ esp32_camera ]

#pins for Freenove esp-32-s3-wroom-1, found in arduino sketch
esp32_camera:
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  
  
  # Image settings
  name: CameraESP32
  # ...


sensor:
  - platform: wifi_signal
    name: "ESP32Cam WiFi Signal Sensor"
    update_interval: 60s
```
