### ISSUE TITLE
HX711 remarkable spikes after Update to 2023.4.4 (Filter bug?)

### ISSUE THREAD

**Issue by AzonInc** [esphome/issues#4498]
### The problem

After updating to 2023.4.4 today, the HX711 Sensor has remarkable random false readings.

![image](https://user-images.githubusercontent.com/11911587/236671359-ec6aced7-176b-4609-adc7-82c134d02872.png)

I didn't change any configuration. But I guess it's a bug of the quantile filter - see my comment below with verbose logs.

After installing 2023.4.3 again, everything is fine. However 2023.4.4 might have a bug.

### Which version of ESPHome has the issue?

2023.4.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.2

### What platform are you using?

ESP32

### Board

D1 Mini

### Component causing the issue

HX711

### Example YAML snippet

```yaml
substitutions:
    name: "bed_scale" #used only as a host name
    friendly_name: "Bett Waage" #prefix of the sensors name in Home Assistant
    sensor_name: "bed_scale" #used only as a host name
    initial_zero_value: "2229000" #this raw data means 0 KG
    
  esphome:
    name: ${name}
    friendly_name: ${friendly_name}
  
  esp32:
    board: wemos_d1_mini32
  
  globals:
    - id: initial_zero
      type: float
      restore_value: yes
      initial_value: '${initial_zero_value}'
      
    - id: auto_tare_enabled
      type: bool
      restore_value: yes
      initial_value: 'true'
  
    - id: auto_tare_difference
      type: float
      restore_value: yes
      initial_value: '0'

  time:
    - platform: homeassistant
      id: homeassistant_time
  
  captive_portal:

  web_server:
    port: 80
  
  logger:
    level: INFO
  
  button:
    - platform: restart
      id: "${sensor_name}_restart"
      name: "${friendly_name} Neustarten"
    - platform: factory_reset
      id: "${sensor_name}_factory_reset"
      name: "${friendly_name} Einstellungen zurücksetzen"
    - platform: template
      id: "${sensor_name}_manual_tare_action_switch"
      name: "${friendly_name} Gewicht auf Null"
      icon: mdi:scale-balance
      on_press:
        - lambda: |-
            id(auto_tare_difference) = id(initial_zero) - id(${sensor_name}_hx711_value_raw).state;
  switch:
    - platform: template
      id: "${sensor_name}_continuous_tare_enabled"
      name: "${friendly_name} Automatisch auf Null setzen"
      lambda: |-
        return id(auto_tare_enabled);
      turn_on_action:
        - lambda: |-
            id(auto_tare_enabled) = true;
      turn_off_action:
        - lambda: |-
            id(auto_tare_enabled) = false;

  sensor:
    - platform: template
      id: "${sensor_name}_initial_zero"
      name: "${friendly_name} Initial Zero Value"
      lambda: |-
        return id(initial_zero);
      update_interval: 1s
      state_class: "measurement"
      
    - platform: template
      id: "${sensor_name}_auto_tare_difference"
      name: "${friendly_name} Auto Tare Difference"
      lambda: |-
        return id(auto_tare_difference);
      update_interval: 1s
      state_class: "measurement"
      
    - platform: homeassistant
      id: homeassistant_initial_zero
      entity_id: "input_number.${sensor_name}_initial_zero"
      on_value:
        then:
          - lambda: |-
              id(initial_zero) = x;
      state_class: "measurement"
    
    # RAW Scale input
    - platform: hx711
      id: "${sensor_name}_hx711_value_raw"
      name: "${friendly_name} Raw Value"
      internal: True
      dout_pin: GPIO21
      clk_pin: GPIO22
      gain: 128
      accuracy_decimals: 0
      update_interval: 0.2s
      filters:
        - quantile:
            window_size: 10
            send_every: 1
            send_first_at: 1
            quantile: .9
      on_value:
        then:
          - sensor.template.publish:
              id: "${sensor_name}_hx711_value"
              state: !lambda 'return id(${sensor_name}_hx711_value_raw).state;'
          - if:
              condition:
                and:
                  - lambda: 'return id(auto_tare_enabled);'
                  # current smart scale value is below approx. 10KG (raw value -275743) aka nobody is standing on the scale
                  - lambda: 'return id(${sensor_name}_hx711_value).state < 10.0;'
              then:
                - if:
                    condition:
                      # current raw scale value is below expected zero value
                      - lambda: 'return id(${sensor_name}_hx711_value_raw).state < (id(initial_zero) - id(auto_tare_difference));'
                    then:
                      # INcrease Auto-Tare offset to slowly align real zero value with expected zero value
                      - lambda: |-
                          id(auto_tare_difference) += 10;
                    else:
                      # DEcrease Auto-Tare offset to slowly align real zero value with expected zero value
                      - lambda: |-
                          id(auto_tare_difference) -= 10;
      
    # Mapped value to KG
    - platform: template
      id: "${sensor_name}_hx711_value"
      icon: mdi:scale
      name: "${friendly_name} Gewicht"
      internal: False
      filters:
        # apply auto_tare difference
        - lambda: 'return x + id(auto_tare_difference);'
        # apply rough calibration
        - calibrate_linear:
            # retrieve these values by evaluating the raw values with loads of known mass.
            # note that a bigger difference between measurements usually results in higher resolution,
            # so measure 0 Kg and the highest known mass you have (like f.ex. your own weight, measured by a normal scale with good accuracy)
            - ${initial_zero_value}.0 -> 0
            - 3731000 -> 65.0
        # map values below 0.1 to 0 (to decrease value changes due to random fluctuation)
        - lambda: |-
            if (x <= 0.1) {
              return 0.0;
            } else {
              return x;
            }
            
      unit_of_measurement: kg
      accuracy_decimals: 2
      update_interval: never
      device_class: "weight"
      state_class: "measurement"
  
    - platform: wifi_signal
      name: "${friendly_name} WiFi signal"
      update_interval: 10s
      
    - platform: uptime
      name: "${friendly_name} Uptime"
```

### Additional information

dout_pin: GPIO21
clk_pin: GPIO22
