### ISSUE TITLE
Compile error with "update_on_boot" of my9231

### ISSUE THREAD

**Issue by freegink** [esphome/issues#450]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** pip

**ESP (ESP32/ESP8266, Board/Sonoff):** Sonoff B1 R2

**Affected component:** My9231

**Description of problem:**
After adding property "update_on_boot", ESPHome indicated "update_on_boot" is an invalid option for my9321.  

And I checked the source code, it doesn't seem that the const "CONF_UPDATE_ON_BOOT" was used anywhere. Correct me if I'm wrong.

**Problem-relevant YAML-configuration entries:**
```yaml
my9231:
  data_pin: GPIO12
  clock_pin: GPIO14
  num_channels: 6
  num_chips: 2
  update_on_boot: false

```

**Traceback (if applicable):**

```
Failed config

my9231:
  - [source sonoff_b1_r2.yaml:27]
    data_pin: GPIO12
    clock_pin: GPIO14
    num_channels: 6
    num_chips: 2

    [update_on_boot] is an invalid option for [0]. Please check the indentation.
    update_on_boot: True
```

**Additional information and things you've tried:**
