### ISSUE TITLE
[FastLED] ESP32-S3 M5 AtomS3 lite / error: static assertion failed: Invalid pin specified

### ISSUE THREAD

**Issue by lboue** [esphome/issues#4501]
### The problem

# [FastLED] ESP32-S3 M5 AtomS3 lite / error: static assertion failed: Invalid pin specified
### Summary
Steps to reproduce
RGB LED is connected to GPIO35 but I can't build the file with that config:

### Config snippet 
```
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 35
    num_leds: 1
    rgb_order: GRB
    id: status_led
    name: AtomS3 lite Light
    effects:
      - random:
      - flicker:
      - addressable_rainbow:
```
### Pinout

Doc : [Schematic](https://docs.m5stack.com/en/core/AtomS3%20Lite)

### Error
```
/data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/fastpin.h: In instantiation of 'class FastPin<35>':
/data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/platforms/esp/32/clockless_rmt_esp32.h:178:23:   required from 'class ClocklessController<35, 60, 150, 90, (EOrder)66, 0, false, 5>'
/data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/chipsets.h:582:7:   required from 'class WS2812Controller800Khz<35, (EOrder)66>'
/data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/FastLED.h:105:52:   required from 'class WS2812B<35, (EOrder)66>'
src/esphome/components/fastled_base/fastled_light.h:150:41:   required from 'CLEDController& esphome::fastled_base::FastLEDLightOutput::add_leds(int) [with CHIPSET = WS2812B; unsigned char DATA_PIN = 35; EOrder RGB_ORDER = (EOrder)66]'
src/main.cpp:217:64:   required from here
/data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/fastpin.h:207:24: error: static assertion failed: Invalid pin specified
  static_assert(validpin(), "Invalid pin specified");
                ~~~~~~~~^~
In file included from /data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from /data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/platforms.h:36,
                 from /data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/FastLED.h:52,
                 from src/esphome/components/fastled_base/fastled_light.h:16,
                 from src/esphome.h:22,
                 from src/main.cpp:3:
/data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/platforms/esp/32/clockless_rmt_esp32.h: In instantiation of 'void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::startOnChannel(int) [with int DATA_PIN = 35; int T1 = 60; int T2 = 150; int T3 = 90; EOrder RGB_ORDER = (EOrder)66; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 5]':
/data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/platforms/esp/32/clockless_rmt_esp32.h:381:26:   required from 'static void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::startNext(int) [with int DATA_PIN = 35; int T1 = 60; int T2 = 150; int T3 = 90; EOrder RGB_ORDER = (EOrder)66; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 5]'
/data/m5-atoms3-c846d4/.piolibdeps/m5-atoms3-c846d4/FastLED/platforms/esp/32/clockless_rmt_esp32.h:312:26:   required from 'void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::showPixels(PixelController<RGB_ORDER>&) [with int DATA_PIN = 35; int T1 = 60; int T2 = 150; int T3 = 90; EOrder RGB_ORDER = (EOrder)66; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 5]'
```

### Which version of ESPHome has the issue?

2023.4.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.2

### What platform are you using?

ESP32

### Board

esp32-s3-devkitc-1

### Component causing the issue

fastled_clockless

### Example YAML snippet

```yaml
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: dev

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 35 # LED35
    num_leds: 1
    rgb_order: GRB
    id: status_led
    name: AtomS3 lite Light
```

### Anything in the logs that might be useful for us?

Using dev version doesn't fix this issue.

```
Library Manager: FastLED@3.3.2 has been installed!
INFO FastLED@3.3.2 has been installed!
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - framework-arduinoespressif32 @ 2.0.6+sha.237a3fe 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- FastLED @ 3.3.2
```

### Additional information

![image](https://user-images.githubusercontent.com/938089/236812194-d36cc8c7-5367-4f12-b6bc-31265691e39a.png)

Logfile:
[logs_m5-atoms3-c846d4_run.txt](https://github.com/esphome/issues/files/11420822/logs_m5-atoms3-c846d4_run.txt)

**Comment by Unfocused** [comment]
ESPHome curently uses an outdated version of FastLED, which doesn't properly support ESP32-S3. One of the issues is it disallows the wrong pins (I was affected by this too).

This PR updates FastLED to a version that supports ESP32-S3:
https://github.com/esphome/esphome/pull/4257

If you want to use/test it now, it's usable via:
```yaml
external_components:
  - source: github://pr#4257
    components: [fastled]
```

Note that it also merges `fastled_clockless` and `fastled_spi`, so you just use `fastled` as the platform.

**Comment by lboue** [comment]
Thans @Unfocused.
It doesn't work in my case with a WS2812C-2020 LED with PR 4257 witch updates FastLED to a version that supports ESP32-S3
```
external_components:
  - source: github://pr#4257
    components: [fastled]

# RGB	WS2812C-2020 LED
light:
  - platform: fastled #fastled_clockless 
    chipset: WS2812B
    pin: 35 # LED35
    num_leds: 1
    rgb_order: GRB
    id: status_led
    name: AtomS3 lite Light
```

But neopixelbus worksfine:

```
# RGB	WS2812C-2020 LED
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: 35
    num_leds: 1
    name: "NeoPixel Light"

```

**Comment by lboue** [comment]
I found a second workaround:

[ESP32 RMT LED Strip](https://esphome.io/components/light/esp32_rmt_led_strip.html?highlight=rmt#esp32-rmt-led-strip): This is a component using the ESP32 RMT peripheral to drive most addressable LED strips.
```
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 35
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    id: status_led
    name: AtomS3 lite Light
```
