### ISSUE TITLE
Addressable_light is unable to control all leds in display with a sparse array

### ISSUE THREAD

**Issue by ressu** [esphome/issues#4504]
### The problem

I have a display which consists of 90 addressable LEDs, the display is assembled into a 17x5 matrix where 5 LEDs fall outside of the display in the middle of the array. Since the array is sparse, the buffer needs to be 90 entries long, but since the [setup](https://github.com/esphome/esphome/blob/4b664b6f09a6eef16e380a953973eeda59ea2f19/esphome/components/addressable_light/addressable_light_display.cpp#LL13C6-L13C6) function creates the buffer based on the width and height of the display the buffer is only 85 entries long.

Aside from having a configurable option to set the lenght of the buffer, the only other alternative I can come up with is to take the size of the buffer from the number of leds in the light component

### Which version of ESPHome has the issue?

2023.4.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.2

### What platform are you using?

ESP8266

### Board

d1_mini_lite

### Component causing the issue

addressable_light

### Example YAML snippet

```yaml
light:
  - platform: neopixelbus
    variant: WS2812
    method:
      type: esp8266_dma
    pin: RX
    num_leds: 90
    name: "Clock"
    id: clock_face
    default_transition_length: 0s
    color_correct: [50%, 50%, 50%]
    restore_mode: ALWAYS_ON

display:
  - platform: addressable_light
    id: clock_display
    addressable_light_id: clock_face
    width: 17
    height: 5 
    update_interval: 1s
    pixel_mapper: |-
      int max_x = 17;
      int max_y = 5;
      y = (max_y - 1) - y;
      if (x % 2 == 0) {
        return x / 2 + y * ( max_x + 1 ) ;
      } else {
        return max_x + 1 - x + (x - 1) / 2 + y * ( max_x + 1 );
      }
    lambda: |-
          // Draw a bulls-eye pattern
          Color red = Color(0xFF0000);
          Color green = Color(0x00FF00);
          Color blue = Color(0x0000FF);
          it.rectangle(0, 0, 17, 5, red);
          it.rectangle(1, 1, 15, 3, green);
          it.rectangle(2, 2, 13, 1, blue);
```

### Additional information

An illustration of the physical LED mapping is available here: https://www.instructables.com/Lazy-Mini-Grid/#step4
