### ISSUE TITLE
Can not use gpio 0 for adc

### ISSUE THREAD

**Issue by Dzarda7** [esphome/issues#4505]
### The problem

Esp32 in esphome can not use gpio 0 for ADC. It will not let me compile it, even though it works in Arduino IDE. Same for ESP32 C3

### Which version of ESPHome has the issue?

2023.4.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

Esp32 and esp 32 C3 wroom modules

### Component causing the issue

adc

### Example YAML snippet

```yaml
# Example configuration entry
sensor:
  - platform: adc
    pin: 0
    name: "Living Room Brightness"
    update_interval: 60s
```
