### ISSUE TITLE
Repeat discovery of new devices

### ISSUE THREAD

**Issue by poldim** [esphome/issues#451]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HA in docker, running latest 0.94.3 build.  ESPHome in docker, running latest 0.13.6 build.

**ESP (ESP32/ESP8266, Board/Sonoff):**

Combination of Wemos D1 mini and Sonoff Basic for these three devices

**Affected component:**

Not sure if it's ESPHome or core HA issue.

**Description of problem:**
Using same standard wifi config for most of my devices.  These three are still in development so I don't want to add them to my production HA.  The appear repeatedly. These are up to 427 instances since I last restarted which is less than 24 hours ago.

![image](https://user-images.githubusercontent.com/16869713/59568119-3513e300-902b-11e9-9366-b2da0180d1de.png)

**POSSIBLY Problem-relevant YAML-configuration entries:**
```yaml
wifi:
  ssid: 'XXX'
  password: 'XXX'
  ap:
    ssid: HAN-ESPH
    password: 'XXX'
  reboot_timeout: XXX

api:

ota:

web_server:
  port: 80

logger:
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

[Tried to see if others are having a similar issue.
](https://www.reddit.com/r/homeassistant/comments/c0l2py/anyone_elses_discovery_showing_repeat_entries_on/
)
Recreated HA and ESPHome dockers
