### ISSUE TITLE
ESP32 I2S stopped playing mp3 from HTTPS

### ISSUE THREAD

**Issue by elik745i** [esphome/issues#4510]
### The problem

My local Home Assistant link is on https://

Im using ESP32 devkit v1 board hooked to external MAX DAC.
All was OK, but I have decided to update firmware and device stopped reading mp3 files from my local storage (Home Assistant media)
I cant play text to speech either, only radio works.

### Which version of ESPHome has the issue?

2023.4.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

20230503.3

### What platform are you using?

ESP32

### Board

devkit v1

### Component causing the issue

https

### Example YAML snippet

```yaml
esphome:
  name: audioplayer-01
  friendly_name: AudioPlayer_01

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key here"

ota:
  password: "pass here"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Audioplayer-01 Fallback Hotspot"
    password: "pass here"

captive_portal:

status_led:
  pin:
    number: GPIO2
    inverted: true

i2s_audio:
  i2s_lrclk_pin: GPIO14
  i2s_bclk_pin: GPIO27

media_player:
  - platform: i2s_audio
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_dout_pin: GPIO26
    mode: mono
```
