### ISSUE TITLE
 A component took a long time in a loop() cycle

### ISSUE THREAD

**Issue by phdelodder** [esphome/issues#452]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

**Description of problem:**
[app:077]: A component took a long time in a loop() cycle (0.4 s).
[V][app:078]: Components should block for at most 20-30ms in loop().
[V][app:079]: This will become a warning soon.

Currently I don't have more info. 

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: greenhouse
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: " "
  password: " "
  domain: " "
  fast_connect: True

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

i2c:

ads1115:
  - address: 0x48

mcp23017:
  - id: "mcp23017_hub"
    address: 0x20

switch:
  - platform: gpio
    id: mcp23017_pin_0
    name: "Greenhouse Valve 1"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 0
      number: 0
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
      inverted: False
    icon: "mdi:water-pump"
  - platform: gpio
    id: mcp23017_pin_1
    name: "Greenhouse Valve 2"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 1
      number: 1
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
      inverted: False
    icon: "mdi:water-pump"
  - platform: gpio
    id: mcp23017_pin_2
    name: "Greenhouse Valve 3"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 2
      number: 2
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
      inverted: False
    icon: "mdi:water-pump"
  - platform: gpio
    id: mcp23017_pin_3
    name: "Greenhouse Valve 4"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 3
      number: 3
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
    icon: "mdi:water-pump"
  - platform: gpio
    id: mcp23017_pin_4
    name: "Window 1 UP"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 4
      number: 4
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
      inverted: False
    internal: True
  - platform: gpio
    id: mcp23017_pin_5
    name: "Window 1 DOWN"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 5
      number: 5
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
      inverted: False
    internal: True
  - platform: gpio
    id: mcp23017_pin_6
    name: "Window 2 UP"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 6
      number: 6
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
      inverted: False
    internal: True
  - platform: gpio
    id: mcp23017_pin_7
    name: "Window 2 DOWN"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 7
      number: 7
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
      inverted: False
    internal: True

sensor:
  - platform: adc
    pin: VCC
    name: "Greenhouse VCC Voltage"
  - platform: wifi_signal
    name: "Greenhouse WiFi signal"
    update_interval: 60s
  - platform: uptime
    name: "Greenhouse Uptime"
  - platform: bme280
    temperature:
      name: "Greenhouse Temperature"
      id: bme280_temperature
      oversampling: 16x
    pressure:
      name: "Greenhouse Pressure"
      id: bme280_pressure
    humidity:
      name: "Greenhouse Humidity"
      id: bme280_humidity
    address: 0x76
    update_interval: 60s
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 6.144
    name: "ADS1115 Channel A0-GND"
    id: ads1115_1
    update_interval: 5s
    internal: true # Don't expose this sensor to HA, the template sensors will do that
    # Dry 2.734 - taken from in the air, probably should do it directly in dry soil
    # Wet 0.638 - taken from in a glass of water, probably should do it directly in saturated soil
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 12
      - lambda: |-
          if (x > 2.734) { 				// if over 2.734 volts, we are dry
            return 0;
          } else if (x < 0.638) { 			// if under 0.638 volts, we are fully saturated
            return 100;
          } else {
            return (2.734-x) / (2.734-0.638) * 100.0; 	// use a linear fit for any values in between
          }
  - platform: template
    name: "Greenhouse Zone 1 Soil Saturation"
    id: zone1saturation
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 0
    lambda: |-
      return id(ads1115_1).state;
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 6.144
    name: "ADS1115 Channel A1-GND"
    id: ads1115_2
    update_interval: 5s
    internal: true # Don't expose this sensor to HA, the template sensors will do that
    # Dry 2.802 - taken from in the air, probably should do it directly in dry soil
    # Wet 1.075 - taken from in a glass of water, probably should do it directly in saturated soil
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 12
      - lambda: |-
          if (x > 2.802) { 				// if over 2.802 volts, we are dry
            return 0;
          } else if (x < 1.075) { 			// if under 1.075 volts, we are fully saturated
            return 100;
          } else {
            return (2.802-x) / (2.802-1.075) * 100.0; 	// use a linear fit for any values in between
          }
  - platform: template
    name: "Greenhouse Zone 2 Soil Saturation"
    id: zone2saturation
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 0
    lambda: |-
      return id(ads1115_2).state;
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 6.144
    name: "ADS1115 Channel A2-GND"
    id: ads1115_3
    update_interval: 5s
    internal: true # Don't expose this sensor to HA, the template sensors will do that
    # Dry 2.827 - taken from in the air, probably should do it directly in dry soil
    # Wet 1.070 - taken from in a glass of water, probably should do it directly in saturated soil
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 12
      - lambda: |-
          if (x > 2.827) { 				// if over 2.827 volts, we are dry
            return 0;
          } else if (x < 1.070) { 			// if under 1.070 volts, we are fully saturated
            return 100;
          } else {
            return (2.827-x) / (2.827-1.070) * 100.0; 	// use a linear fit for any values in between
          }
  - platform: template
    name: "Greenhouse Zone 3 Soil Saturation"
    id: zone3saturation
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 0
    lambda: |-
      return id(ads1115_3).state;
  - platform: ads1115
    multiplexer: 'A3_GND'
    gain: 6.144
    name: "ADS1115 Channel A3-GND"
    id: ads1115_4
    update_interval: 5s
    internal: true # Don't expose this sensor to HA, the template sensors will do that
    # Dry 2.816 - taken from in the air, probably should do it directly in dry soil
    # Wet 1.077 - taken from in a glass of water, probably should do it directly in saturated soil
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 12
      - lambda: |-
          if (x > 2.816) { 				// if over 2.816 volts, we are dry
            return 0;
          } else if (x < 1.077) { 			// if under 1.077 volts, we are fully saturated
            return 100;
          } else {
            return (2.816-x) / (2.816-1.077) * 100.0; 	// use a linear fit for any values in between
          }
  - platform: template
    name: "Greenhouse Zone 4 Soil Saturation"
    id: zone4saturation
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 0
    lambda: |-
      return id(ads1115_4).state;
    
binary_sensor:
  - platform: status
    name: "Greenhouse Status"
  - platform: gpio
    id: window_1_state
    pin: 
      number: D5
      mode: INPUT_PULLUP
    name: "Greenhouse Window 1"
    filters:
      - delayed_on: 10ms
    device_class: "window"
    internal: true
  - platform: gpio
    id: window_2_state
    pin: 
      number: D7
      mode: INPUT_PULLUP
    name: "Greenhouse Window 2"
    filters:
      - delayed_on: 10ms
    device_class: "window"
    internal: true

cover:
  - platform: template
    name: "Greenhouse Window 1"
    id: window_1
    lambda: |-
      if (id(window_1_state).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_off: mcp23017_pin_5
      - switch.turn_on: mcp23017_pin_4
      # Failsafe: Turn off motors after 2min if endstop not reached.
      - delay: 2 min
      - switch.turn_off: mcp23017_pin_4
      - cover.stop: window_1
    close_action:
      - switch.turn_off: mcp23017_pin_4
      - switch.turn_on: mcp23017_pin_5
      # Failsafe: Turn off motors after 2min if endstop not reached.
      - delay: 2 min
      - switch.turn_off: mcp23017_pin_5
      - cover.stop: window_1
    stop_action:
      - switch.turn_off: mcp23017_pin_4
      - switch.turn_off: mcp23017_pin_5
  - platform: template
    name: "Greenhouse Window 2"
    id: window_2
    lambda: |-
      if (id(window_2_state).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_off: mcp23017_pin_7
      - switch.turn_on: mcp23017_pin_6
      # Failsafe: Turn off motors after 2min if endstop not reached.
      - delay: 2 min
      - switch.turn_off: mcp23017_pin_6
      - cover.stop: window_2
    close_action:
      - switch.turn_off: mcp23017_pin_6
      - switch.turn_on: mcp23017_pin_7
      # Failsafe: Turn off motors after 2min if endstop not reached.
      - delay: 2 min
      - switch.turn_off: mcp23017_pin_7
      - cover.stop: window_2
    stop_action:
      - switch.turn_off: mcp23017_pin_6
      - switch.turn_off: mcp23017_pin_7
      
text_sensor:
  - platform: version
    name: "Greenhouse ESPHome Version"
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
