### ISSUE TITLE
DS18B20 scratchpad invalid checksum error

### ISSUE THREAD

**Issue by MarkoPaasila** [esphome/issues#4522]
### The problem

DS18B20 (apparently clones) don't work anymore, and give the "scratchpad invalid checksum error".

### Which version of ESPHome has the issue?

2023.5.0 ->

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

devkit-c

### Component causing the issue

dallas

### Example YAML snippet

```yaml
dallas:
  - pin: GPIO19
    update_interval: 10s

sensor:
  - platform: dallas
    address: 0x8C062018C89DC028
    name: "temperature-outside1"
    id: t1
    accuracy_decimals: 4
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    icon: "mdi:thermometer"
    disabled_by_default: false
    filters:
      - offset: 0.0625
      - exponential_moving_average:
          alpha: 0.1
          send_every: 1
```

### Additional information

Downgrading to 2023.4.4 solves the issue.
