### ISSUE TITLE
sensor sun inaccurate

### ISSUE THREAD

**Issue by anhorbc** [esphome/issues#4527]
### The problem

Sunset calculation seems to be off, by about 2 hours before actual sunset. 
Sunrise calculation seems to be off by 4 hours and 44 minutes after actual sunset. 
GPS position is _very_ accurate. 

### Which version of ESPHome has the issue?

2023.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.3

### What platform are you using?

ESP32

### Board

wt32-eth01

### Component causing the issue

sun

### Example YAML snippet

```yaml
globals:
   - id: longitude
     type: float
     restore_value: no
     initial_value: 0.0f
   - id: latitude
     type: float
     restore_value: no
     initial_value: 0.0f
mqtt:
  broker: 192.168.3.1
  on_json_message:
    - topic: "alexandra/position"      
      then:
         - lambda: |-
              ESP_LOGD("custom", "Got message on topic alexandra/position ");
              float mylat;
              float mylong;
              if (x.containsKey("value")) {
                mylat = x["value"]["latitude"];
                mylong = x["value"]["longitude"];
                ESP_LOGD("custom", "Latitude: %f", mylat);
                ESP_LOGD("custom", "Longitude: %f", mylong);
                id(latitude) = mylat;
                id(longitude) = mylong; 
              }

            
time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Stockholm"
sun:
  latitude: id(latitude)
  longitude: id(longitude)
  on_sunrise:
    - then:
      - logger.log: Good morning!
  on_sunset:
    - then:
      - logger.log: Good evening!
sensor:
  - platform: sun
    name: Sun Elevation
    type: elevation
  - platform: sun
    name: Sun Azimuth
    type: azimuth
text_sensor:
  - platform: sun
    name: Sun Next Sunrise
    type: sunrise
  - platform: sun
    name: Sun Next Sunset
    type: sunset
```

### Additional information

At first I thought it might be a timezone issue as we in sweden during summertime use GMT+2, but that can't be the whole story as the sunrise value is off by 4:44 in the other direction.
