### ISSUE TITLE
ESPHome 2023.5.1 update failed with bluetooth-proxies/m5stack-atom-lite

### ISSUE THREAD

**Issue by timoverwoest** [esphome/issues#4528]
### The problem

Tried to update ESPHome firmware on m5stack-atom-lite bluetooth-proxy and it failed. Initially installed through https://esphome.github.io/bluetooth-proxies/

See log: 
Dashboard import requires the `esphome` -> `project` information to be provided.
  package_import_url: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main
  import_full_config: False

[logs_bluetooth-proxy_run.txt](https://github.com/esphome/issues/files/11523928/logs_bluetooth-proxy_run.txt)

### Which version of ESPHome has the issue?

2023.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.3

### What platform are you using?

ESP32

### Board

m5stack-atom

### Component causing the issue

dashboard_import:

### Example YAML snippet

```yaml
esphome:
  name: "bluetooth-proxy"
  friendly_name: "bluetooth-proxy"

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: [redacted]

ota:
  password: [redacted]

improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "bluetooth-proxy Fallback Hotspot"
    password: [redacted]

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic
```

### Anything in the logs that might be useful for us?

```txt
Dashboard import requires the `esphome` -> `project` information to be provided.
  package_import_url: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main
  import_full_config: False
```

### Additional information

<img width="693" alt="Scherm­afbeelding 2023-05-21 om 09 49 39" src="https://github.com/esphome/issues/assets/23740848/63acf491-209e-48f0-b432-a95f354e7f98">
