### ISSUE TITLE
compilation failed error 4

### ISSUE THREAD

**Issue by billedeclown01** [esphome/issues#4531]
### The problem

I try to had a feature on my air quality sensor wich is already compiled. When i try to compil the compilation failed. 
i just haded a filters offset on the temperatur data (line 155-156). I cant compil heaven if i delete the feature.

### Which version of ESPHome has the issue?

2023.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.3

### What platform are you using?

ESP8266

### Board

D1 mini

### Example YAML snippet

```yaml
esphome:
  name: capteur-qualite-air


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fTzVqkgItPjL3Mgg1WIst1Lphx9LPJ6M2m4U7Nj6gcE="

ota:
  password: "9915c47bbe235be40d9d0e38b172350a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Capteur Fallback Hotspot"
    password: "1RoQvmoylMGN"




esp8266:
  board: d1_mini
  framework:
    version: 2.7.4

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a

sensor:
  - platform: scd4x
    i2c_id: bus_a
    co2:
      id: CO2
      name: "CO2"
      on_value_range:
      - below: 450
        then:
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 1
              red: 0%
              green: 0%
              blue: 50%
      - above: 450
        below: 750
        then:
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 3
              red: 25%
              green: 50%
              blue: 0%
      - above: 750
        below: 900
        then:
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 4
              red: 50%
              green: 50%
              blue: 0%
      - above: 900
        below: 1000
        then:
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 8
              red: 50%
              green: 25%
              blue: 0%
      - above: 1000
        below: 1100
        then:
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 9
              red: 50%
              green: 0%
              blue: 0%
      - above: 1100
        then:
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_CO2
              range_from: 0
              range_to: 11
              red: 50%
              green: 0%
              blue: 0%
      
    temperature:
      name: "Temperature"
      filters:
        - offset: -3.0
      id: Temp
      on_value_range:
      - below: 10
        then:
          - light.addressable_set:
              id: Strip_Temp
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_Temp
              range_from: 0
              range_to: 1
              red: 0%
              green: 0%
              blue: 50%
      - above: 10
        below: 17
        then:
          - light.addressable_set:
              id: Strip_Temp
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_Temp
              range_from: 0
              range_to: 3
              red: 0%
              green: 50%
              blue: 50%
      - above: 17
        below: 22
        then:
          - light.addressable_set:
              id: Strip_Temp
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_Temp
              range_from: 0
              range_to: 4
              red: 0%
              green: 50%
              blue: 0%
      - above: 22
        below: 27
        then:
          - light.addressable_set:
              id: Strip_Temp
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_Temp
              range_from: 0
              range_to: 6
              red: 50%
              green: 50%
              blue: 0%
      - above: 27
        then:
          - light.addressable_set:
              id: Strip_Temp
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_Temp
              range_from: 0
              range_to: 11
              red: 50%
              green: 0%
              blue: 0%
      

    humidity:
      name: "Humidity"
      id: Hum
      # on_value:
      #     then:
      #       - light.addressable_set:
      #           id: Strip_Hum
      #           range_from: 0
      #           range_to: 2
      #           red: 0%
      #           green: 50%
      #           blue: 0%
      on_value_range:
      - below: 35
        then:
          - light.addressable_set:
              id: Strip_Hum
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_Hum
              range_from: 0
              range_to: 1
              red: 50%
              green: 0%
              blue: 0%
      - above: 35
        below: 45
        then:
          - light.addressable_set:
              id: Strip_Hum
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_Hum
              range_from: 0
              range_to: 2
              red: 50%
              green: 50%
              blue: 0%
      - above: 45
        below: 65
        then:
          - light.addressable_set:
              id: Strip_Hum
              range_from: 0
              range_to: 4
              red: 0%
              green: 50%
              blue: 0%
      - above: 65
        below: 75
        then:
          - light.addressable_set:
              id: Strip_Hum
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_Hum
              range_from: 0
              range_to: 7
              red: 50%
              green: 50%
              blue: 0%
      - above: 75
        then:
          - light.addressable_set:
              id: Strip_Hum
              range_from: 0
              range_to: 11
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_Hum
              range_from: 0
              range_to: 7
              red: 50%
              green: 0%
              blue: 0%
    update_interval: 1s

light:
  - platform: fastled_clockless
    chipset: WS2812b
    id: Strip_CO2
    pin: GPIO13
    num_leds: 10
    rgb_order: GRB
    name: "Strip_CO2"
  - platform: fastled_clockless
    chipset: WS2812b
    id: Strip_Temp
    pin: GPIO14
    num_leds: 10
    rgb_order: GRB
    name: "Strip_Temp"
  - platform: fastled_clockless
    chipset: WS2812b
    id: Strip_Hum
    pin: GPIO12
    num_leds: 10
    rgb_order: GRB
    name: "Strip_Hum"
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/capteur.yaml...
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Generating C++ source...
INFO Compiling app...
Processing capteur-qualite-air (board: d1_mini; framework: arduino; platform: platformio/espressif8266@2.6.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- Wire @ 1.0
|-- FastLED @ 3.3.2
Compiling /data/capteur-qualite-air/.pioenvs/capteur-qualite-air/src/main.cpp.o
xtensa-lx106-elf-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
*** [/data/capteur-qualite-air/.pioenvs/capteur-qualite-air/src/main.cpp.o] Error 4
========================= [FAILED] Took 25.29 seconds =========================
```
