### ISSUE TITLE
ESP32 i2s_audio

### ISSUE THREAD

**Issue by mmatus1112** [esphome/issues#4535]
### The problem

Hi all, I am having issues with my i2s_audio.

I am using an ESP32 with an external DAC → UDA1334A and my wiring diagram is as follows:

![image](https://github.com/esphome/issues/assets/72715377/3da586e9-505e-413f-8c0b-ad1a0fd48b53)

My ESPHOME configuration is:

`
esphome:

  name: audio-notifier-1

  friendly_name: audio_notifier_1

esp32:

  board: esp32dev

  framework:

    type: arduino

# Enable logging

logger:

# Enable Home Assistant API

api:

  encryption:

    key: "zEBCe37EmV8ZPmTFlEaWd8BE4YkT45DUVMV0OksMbRU="

ota:

  password: "14a502f63520e30fc336ef966b401601"

wifi:

  ssid: !secret wifi_ssid

  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails

  ap:

    ssid: "Audio-Notifier-1"

    password: "10zAAiH3qVA2"

captive_portal:

i2s_audio:

  i2s_lrclk_pin: GPIO33

  i2s_bclk_pin: GPIO19

media_player:

  - platform: i2s_audio

    name: ESPHome I2S Media Player

    dac_type: external

    i2s_dout_pin: GPIO22

    mode: stereo
`

I am able to see my media player on my Home Assistant and I can play TTS without any issues. The sound is really clear and really nice. However, when I try to play a 5 seconds mp3 sound (an alarm), I can only hear a "white" noise (like an old radio playing noise). I try playing the same audio in my PC speakers (Browser) and I can hear it without issues. 

I am unsure of what the issue is but I have exhausted my ideas on what the problem is. I have tried multiple devices, but I get the same problem. I would appreciate some help!!!

Thank you!

### Which version of ESPHome has the issue?

2023.5.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.5.3

### What platform are you using?

ESP32

### Component causing the issue

i2s_audio

### Example YAML snippet

```yaml
esphome:

  name: audio-notifier-1

  friendly_name: audio_notifier_1

esp32:

  board: esp32dev

  framework:

    type: arduino

# Enable logging

logger:

# Enable Home Assistant API

api:

  encryption:

    key: "zEBCe37EmV8ZPmTFlEaWd8BE4YkT45DUVMV0OksMbRU="

ota:

  password: "14a502f63520e30fc336ef966b401601"

wifi:

  ssid: !secret wifi_ssid

  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails

  ap:

    ssid: "Audio-Notifier-1"

    password: "10zAAiH3qVA2"

captive_portal:

i2s_audio:

  i2s_lrclk_pin: GPIO33

  i2s_bclk_pin: GPIO19

media_player:

  - platform: i2s_audio

    name: ESPHome I2S Media Player

    dac_type: external

    i2s_dout_pin: GPIO22

    mode: stereo
```
