### ISSUE TITLE
ESP32 RMT LED Strip Component not working with on RGBW led strip

### ISSUE THREAD

**Issue by AbbottWu** [esphome/issues#4536]
### The problem

When I use ESP32 RMT LED Strip for my sk6812 led strip, the RGB color control is fine, but the white channel isn’t work as it should be. The white leds cannot be controlled.

Causing the strip is work fine on Neopixel, the problem isn't related to the hardware. Though I have set `is_rgbw=true` in the config and the white control can be seen at Home Assistant, it cannot work.

### Which version of ESPHome has the issue?

2023.5.3 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.3

### What platform are you using?

ESP32-IDF

### Board

esp32c3

### Component causing the issue

ESP32 RMT LED

### Example YAML snippet

```yaml
light:
  - platform: esp32_rmt_led_strip
    is_rgbw: true
    rgb_order: GRB
    pin: GPIO19
    num_leds: 22
    rmt_channel: 0
    chipset: SK6812
    name: "Desk Lamp"
```

### Anything in the logs that might be useful for us?

```txt
[11:03:56][W][light:185]: 'Desk Lamp' - This color mode does not support setting white value!
[11:03:56][D][light:035]: 'Desk Lamp' Setting:
[11:03:56][D][light:054]:   Color brightness: 100%
[11:03:56][D][light:058]:   Red: 100%, Green: 100%, Blue: 100%
[11:03:56][D][light:084]:   Transition length: 1.0s
```

**Comment by ssieb** [comment]
Try:
```yaml
external_components:
  - source: github://pr#4886
    components: [ esp32_rmt_led_strip ]
```
although that might not work without the HA fix as well.
