### ISSUE TITLE
Fastled power management request

### ISSUE THREAD

**Issue by pauldogg** [esphome/issues#454]
Could not find FastLED.setMaxPowerInVoltsAndMilliamps or FastLED.setMaxPowerInMilliWatts
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

feather huzzah 8266 fastled spi
**ESP (ESP32/ESP8266, Board/Sonoff):**

feather huzzah 8266 
**Affected component:**

https://www.adafruit.com/product/2821

**Description of problem:**
after a system restart, if the lights come on, they are full brightness which is too bright. Would like to cap the brightness to prevent overdrawing the power supply.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
light:
  - platform: fastled_spi
    chipset: APA102
    data_pin: GPIO12
    clock_pin: GPIO15
    num_leds: 693
    rgb_order: BGR
    name: "Crown A"
    power_supply: Big_amp
```

**Traceback (if applicable):**

```
no error
```
no error
**Additional information and things you've tried:**
I've looked at the power supply, and the documentation to find a way to limit brightness of my 2000 leds, but can't figure out how to do this.
your help is greatly appreciated. oh and thank you for making such an amazing platform!
