### ISSUE TITLE
condition switch.is_on not handled correctly

### ISSUE THREAD

**Issue by zimbo86** [esphome/issues#4555]
### The problem

When a template switch "AdvancedMode" is ON the condition on binary_sensor RFID executes the "else" part insted of then "part".

```
binary_sensor:
  - platform: rc522
    uid: xx-xx-xx-xx-xx-xx
    name: "RFID1"
    internal: True
    on_press:
      if:
        condition:
          switch.is_on: AdvancedMode
        then:
          - homeassistant.service:
              service: switch.toggle
              data:
                entity_id: xxxxxxxxx
        else: 
          - logger.log:
              format: "Nothing"

switch: 
  - platform: template
    name: AdvancedMode  
    id: AdvancedMode
    internal: True
    turn_on_action:
      - logger.log:
          format: "AdvancedMode"
      - rtttl.play:
          rtttl: 'siren:d=8,o=5,b=100:g,g'
      - delay: 5000ms
      - switch.turn_off: AdvancedMode
```

### Which version of ESPHome has the issue?

2023.5.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.3

### What platform are you using?

ESP32

### Board

ESP32 CAM
