### ISSUE TITLE
Modbus Custom Command not working

### ISSUE THREAD

**Issue by Bjplms** [esphome/issues#4560]
### The problem

I would like to read an SDM smart meter behind a Growatt inverter, but no matter what data I enter in the custom_command, in the debug it always sends the same value that has no connection with what I enter in the config.

I have changed the config but the following comes in the log
Config: custom_command: [ 0x1, 0x4, 0x12, 0x00, 0x00, 0x64]
Log: 
09:27:46	[V]	[modbus:220]	
Modbus write raw: 01.04.12.00.00.64 (6)
09:27:46	[V]	[modbus_controller:486]	
Command sent 0 0xE524 2
09:27:46	[V]	[component:204]	
Component modbus_controller took a long time for an operation (0.24 s).
09:27:46	[V]	[component:205]	
Components should block for at most 20-30ms.
09:27:47	[D]	[modbus_controller:029]	
Modbus command to device=2 register=0xE524 countdown=0 no response received - removed from send queue

### Which version of ESPHome has the issue?

v2023.5.5

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

ESP8266-12F

### Component causing the issue

Modbus

### Example YAML snippet

```yaml
esphome:
  name: esphome-web-1611eb
  friendly_name: 123123

esp8266:
  board: esp01_1m

#Enable logging
logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  # baud_rate: 0 #disable logging over uart
  hardware_uart: UART0

web_server:
  port: 80

ota:

wifi:
  ssid: xxxxxx
  password: xxxxxxxxxxxxxxxx

uart:
  id: mod_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

modbus:
  send_wait_time: 200ms
  uart_id: mod_bus
  id: growatt

modbus_controller:
  - id: sdm
    address: 2
    modbus_id: growatt
    command_throttle: 100ms
    setup_priority: -10
    update_interval: 30s
sensor:
  - platform: modbus_controller
    modbus_controller_id: sdm
    name: "Total active energy"
    id: total_energy
    #    address: 0x156
    #    register_type: "read"
    ## reimplement using custom_command
    # 0x2 : modbus device address
    # 0x4 : modbus function code
    # 0x1 : high byte of modbus register address
    # 0x56: low byte of modbus register address
    # 0x00: high byte of total number of registers requested
    # 0x02: low byte of total number of registers requested
    custom_command: [ 0x1, 0x20, 0x00, 0x00, 0x00, 0x64]
    value_type: FP32
    unit_of_measurement: kWh
    accuracy_decimals: 1
```

### Anything in the logs that might be useful for us?

```txt
09:25:29	[V]	[modbus:220]	
Modbus write raw: 01.20.00.00.00.64 (6)
09:25:29	[V]	[modbus_controller:486]	
Command sent 0 0xE524 2
09:25:29	[V]	[component:204]	
Component modbus_controller took a long time for an operation (0.24 s).
09:25:29	[V]	[component:205]	
Components should block for at most 20-30ms.
09:25:29	[D]	[modbus_controller:029]	
Modbus command to device=2 register=0xE524 countdown=0 no response received - removed from send queue
```
