### ISSUE TITLE
d1_pro_mini: "Error binary size: Error: ESP has been flashed with wrong flash size." OTA does not work

### ISSUE THREAD

**Issue by ZhuDaHai** [esphome/issues#4562]
### The problem

Just build the Air-Gradient system and using its ESPHome fork to install the firmware. 
Direct cable (USB) connect firmware updates work fine and Air-Gradient is running properly.
However I cannot update the firmware OTA and get this following error when trying to do so:

> ERROR Error binary size: Error: ESP has been flashed with wrong flash size. Please choose the correct 'board' option (esp01_1m always works) and then flash over USB

I am clicking on "Flash Mode (Safe Mode)" control in the air-gradient device display of ESPHome and waiting for the reboot into safe mode before attempting the OTA update.

![AirGradient](https://github.com/esphome/issues/assets/14084743/6f099a9e-e020-465d-a41a-4e8f95ff2ba3)

### Which version of ESPHome has the issue?

2023.5.5 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.4

### What platform are you using?

ESP8266

### Board

d1_mini_pro

### Component causing the issue

ajfriesen / ESPHome-AirGradient

### Example YAML snippet

```yaml
esphome:
  name: air-gradient
  platform: ESP8266
  board: d1_mini_pro
  friendly_name: air-gradient

  project:
    name: ajfriesen.ESPHome-AirGradient
    version: "1.0"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  

# Create a switch for safe_mode in order to flash the device
# Solution from this thread:
# https://community.home-assistant.io/t/esphome-flashing-over-wifi-does-not-work/357352/1
switch:
  - platform: safe_mode
    id: AirGradient_safe_mode
    name: "Flash Mode (Safe Mode)"

button:
  - platform: template
    name: "Flash mode"
    id: flash_button
    icon: "mdi:cellphone-arrow-down"
    on_press:
      then:
        - switch.toggle: AirGradient_safe_mode

dashboard_import:
# package_import_url: github://esphome/esphome-project-template/project-template-esp32.yaml@v6
  package_import_url: github://ajfriesen/ESPHome-AirGradient/main/air-gradient.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Gradient Fallback Hotspot"
    password: !secret AG_fallback


captive_portal:

i2c:
  sda: D2
  scl: D1

font:
  - file: "fonts/monofont.ttf"
    id: opensans
    size: 10

display:
  - platform: ssd1306_i2c
    id: oled
    model: "SSD1306 64x48"
    pages:
      - id: page1
        lambda: |-
          it.printf(0, 0, id(opensans), "CO2: %.0fppm", id(co2).state);
          it.printf(0, 10, id(opensans), "PM25: %.0f", id(pm25).state);
          it.printf(0, 20, id(opensans), "Hmdty: %.0f", id(humidity).state);
          it.printf(0, 30, id(opensans), "Temp: %.0fC", id(temp).state);
      - id: page2
        lambda: |-
          it.printf(0, 0, id(opensans), "PM10 : %.0f", id(pm10).state);
          it.printf(0, 10, id(opensans), "PM25 : %.0f", id(pm25).state);
          it.printf(0, 20, id(opensans), "PM100: %.0f", id(pm100).state);
# Maybe add a page later

interval:
  - interval: 5s
    then:
      - display.page.show_next: oled
      - component.update: oled

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart_1
    
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart_2

sensor:
  - platform: sht3xd
    temperature:
      id: temp
      name: "Temperature"
    humidity:
      id: humidity
      name: "Humidity"
    address: 0x44
    update_interval: 5s

  - platform: pmsx003
    # type can be PMSX003, PMS5003S, PMS5003T, PMS5003ST
    # https://esphome.io/components/sensor/pmsx003.html
    type: PMSX003
    uart_id: uart_1
    pm_1_0:
      id: pm10
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      id: pm25
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      id: pm100
      name: "Particulate Matter <10.0µm Concentration"
#    formaldehyde:
#      id: hcho
#      name: "Formaldehyde (HCHO) concentration in µg per cubic meter"

  - platform: senseair
    uart_id: uart_2
    co2:
      id: co2
      name: "SenseAir CO2 Value"
    update_interval: 60s
```

### Additional information

FYI: I did NOT change the board option to 'esp01_1m' as this is not what was used in the Air-Gradient yaml and did not want to risk bricking the board.

Thank you. Please let me know if you need any further information.
