### ISSUE TITLE
ESPHome container stuck on "Starting dashboard web server"

### ISSUE THREAD

**Issue by kidzblvck** [esphome/issues#4565]
### The problem

I'm not sure if this was caused by an update or just something random, but my ESPHome container fails to start, the only log after starting the container is:
```
esphome    | 2023-06-08 00:47:40,480 INFO Starting dashboard web server on http://0.0.0.0:6052 and configuration dir /config...
```
It has been working without any issues for the last year or so.

This is my docker compose:
```
version: '3'
services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:latest
    volumes:
      - /home/user/docker/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
```

### Which version of ESPHome has the issue?

latest from docker hub

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266
