### ISSUE TITLE
ESP32 Crashes when making HTTP Request over Internet

### ISSUE THREAD

**Issue by LewisSpring** [esphome/issues#4569]
### The problem

When trying to make a HTTP request via the Internet, the ESP32 will crash and reboot.
HTTP requests via the LAN do not crash the ESP.

I have tested Internet and DNS connectivity at the site and have not found any issues.
I have ensured that the static IP information is correct.

### Which version of ESPHome has the issue?

2023.5.5, 2023.4.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Not Applicable

### What platform are you using?

ESP32

### Board

esp32dev (LILYGO T-Ethernet / T-INTERNET)

### Component causing the issue

http_request

### Components Installed

http_request, DS1307, Web_server, I2C, NTP, button, sensor, text_sensor, binary_sensor (GPIO, template), switch (GPIO, template), script

### Example YAML snippet

```yaml
- id: push_notification
    then:
    - logger.log: "push_notification"
    - http_request.post:
        url: https://api.pushover.net/1/messages.json
        headers:
          Content-Type: application/json
        json:
          token: $pushover_token
          user: !secret beam_pushover_user
          priority: "2"
          expire: "3600"
          retry: "30"
          title: $notification_title
          message: $notification_message
          sound: $notification_sound
        verify_ssl: false
        on_response:
          then:
            - logger.log:
                format: "Response status: %d"
                args:
                  - status_code
            - lambda: |-
                json::parse_json(id(http_request_data).get_string(), [](JsonObject root) {
                    id(HTTP_Error_Response).publish_state(root["errors"]);
                });
  - id: gsheet_log
    then:
      - logger.log: "gsheet_log "
      - http_request.post:
          url: !secret beam_ifttt
          headers:
            Content-Type: application/json
          json:
            device: $device_name
            event: !lambda |- 
              return id(event);
            rtc: !lambda |-
              return (id(ds1307_time).now().strftime("%Y-%m-%d %H:%M:%S"));
            ntp: !lambda |-
              return (id(ntp_time).now().strftime("%Y-%m-%d %H:%M:%S"));
            TZ: !lambda |-
              if (id(ntp_time).now().is_dst) {
                return "BST";
              } else {
                return "GMT";
              }
            contact_1: !lambda |-
              if (id(contact_1).state) {
                return "closed";
              } else {
                return "open";
              }        
#            contact_2: !lambda |-
#              if (id(contact_2).state) {
#                return "closed";
#              } else {
#                return "open";
#              }        
[...]           
          verify_ssl: false
```

### Anything in the logs that might be useful for us?

```txt
2023.5.5
================================
[D][main:452]: Sending blocked notification!
[195273][E][WiFiGeneric.cpp:1438] hostByName(): DNS Failed for api.pushover.net
[195274][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -1
[D][ma
assert failed: xEventGroupSetBits event_groups.c:596 (xEventGroup)


Backtrace:0x40083d75:0x3ffbc3d00x4008e151:0x3ffbc3f0 0x400938d9:0x3ffbc410 0x4008e66e:0x3ffbc540 0x4015dc2c:0x3ffbc560 0x4010cd11:0x3ffbc580 0x4010cdcd:0x3ffbc5b0 0x4010d557:0x3ffbc5d0 0x40116041:0x3ffbc630 0x40119297:0x3ffbc680 0x4011d592:0x3ffbc6b0 0x4010c551:0x3ffbc6d0 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
[I][logger:262]: Log initialized
[C][ota:469]: There have been 1 suspected unsuccessful boot attempts.


2023.4.4
================================
[ 51257][E][WiFiGeneric.cpp:1438] hostByName(): DNS Failed for maker.ifttt.com
[ 51258][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -1
[W][http_request:087]: HTTP Request failed; URL: https://maker.ifttt.com/trigger/[redacted]; Error: connection refused; Duration: 6 ms

assert failed: xEventGroupSetBits event_groups.c:596 (xEventGroup)


Backtrace:0x40083d75:0x3ffbc3d00x4008e151:0x3ffbc3f0 0x400938d9:0x3ffbc410 0x4008e66e:0x3ffbc540 0x4015ddd0:0x3ffbc560 0x4010cea1:0x3ffbc580 0x4010cf5d:0x3ffbc5b0 0x4010d6e7:0x3ffbc5d0 0x401161e5:0x3ffbc630 0x4011943b:0x3ffbc680 0x4011d736:0x3ffbc6b0 0x4010c6e1:0x3ffbc6d0 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
[I][logger:259]: Log initialized
[C][ota:469]: There have been 1 suspected unsuccessful boot attempts.
```

### Additional information

The code has worked successfully on versions before 2023.4.4, but I am unsure of which version worked as I did not record it. (regrettably!)

Original Discussion on Discord: https://discord.com/channels/429907082951524364/1113945162905833572
