### ISSUE TITLE
"Offline" esp triggers on_time_sync

### ISSUE THREAD

**Issue by l3ztum** [esphome/issues#4571]
### The problem

I have a esphome far from home wifi in my allotment garden. I've configured a RTC(ds1307) as described in the docs but with sntp instead of homeassistant: https://esphome.io/components/time/ds1307.html#full-configuration-example

I configured wifi once to set the rtc via sntp, flashed the esp32. clocks got synced.
Then i removed wifi from the config to make it truly independent and read the logs via usb.
rtc seems to configure system clock on boot but the on_time_sync of the time.sntp component got triggered. 

### Which version of ESPHome has the issue?

2023.5.5

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32-wroom-32

### Component causing the issue

time

### Example YAML snippet

```yaml
esphome:
  name: irrigation-system
  friendly_name: irrigation-system
  on_boot:
    then:
      # read the RTC time once when the system boots
      ds1307.read_time:

esp32:
  board: esp32dev
  framework:
    type: arduino

web_server:
  port: 80
  local: true

# Enable logging
logger:

ota:
  password: "<redacted>"

wifi:
  # networks:
  # # - ssid: !secret wifi_ssid
  # #   password: !secret wifi_password
  # - ssid: !secret wifi2_ssid
  #   password: !secret wifi2_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Irrigation-System"
    password: "<redacted>"
    ap_timeout: 10s
  power_save_mode: none

time:
  - platform: ds1307
    id: ds1307_time
    # repeated synchronization is not necessary unless the external RTC
    # is much more accurate than the internal clock
    update_interval: never
    on_time:
        # Every other day at 4am
      - cron: '0 0 18 1/2 * *'
        then:
        - sprinkler.start_full_cycle: irrigation_sprinkler
        - lambda: |-
            auto time = id(sntp_time).now();
            ESP_LOGD("lambda", "Starting irrigation at: %04d-%02d-%02d %02d:%02d:%02d", time.year, time.month, time.day_of_month, time.hour,
            time.minute, time.second);
  - platform: sntp
    id: sntp_time
    on_time_sync:
      then:
      # ... and update the RTC when the synchronization was successful
        - ds1307.write_time:
            id: ds1307_time
        - logger.log: "Synchronized system clock"
```

### Anything in the logs that might be useful for us?

```txt
[I][logger:262]: Log initialized
[C][ota:469]: There have been 1 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][i2c.arduino:183]: Performing I2C bus recovery
[D][number:012]: 'trigger_hour': Sending state 0.000000
[C][switch.gpio:011]: Setting up GPIO Switch 'main_valve'...
[D][switch:016]: 'main_valve' Turning OFF.
[D][switch:055]: 'main_valve': Sending state OFF
[D][switch:016]: 'main_valve' Turning OFF.
[D][ds1307:088]: Read  13:58:52 2023-06-09  CH:OFF RS:0 SQWE:OFF OUT:OFF
[D][time:045]: Synchronized time: 2023-06-09 15:58:52
[D][sprinkler:1434]: All valves stopped, including pumps
[C][ds1307:013]: Setting up DS1307...
[D][ds1307:088]: Read  13:58:52 2023-06-09  CH:OFF RS:0 SQWE:OFF OUT:OFF
[C][wifi:038]: Setting up WiFi...
[C][wifi:039]:   Local MAC: 3C:61:05:3E:AD:A8
[C][wifi:211]: Setting up AP...
[C][wifi:213]:   AP SSID: 'Irrigation-System'
[C][wifi:214]:   AP Password: '08152305'
[C][wifi:223]:   IP Address: 192.168.4.1
[C][web_server:099]: Setting up web server...
[C][ota:093]: Over-The-Air Updates:
[C][ota:094]:   Address: irrigation-system.local:3232
[C][ota:097]:   Using Password.
[C][sntp:028]: Setting up SNTP...
[I][app:062]: setup() finished successfully!
[D][switch:055]: 'Flower Garden': Sending state OFF
[D][sntp:078]: Synchronized time: 2023-06-09 15:58:52
[D][ds1307:101]: Write 13:58:52 2023-06-09  CH:OFF RS:0 SQWE:OFF OUT:OFF
[D][main:416]: Synchronized system clock
```

### Additional information

sntp seems to "sync" the default interval of every 15min

> [D][sntp:078]: Synchronized time: 2023-06-09 16:12:32
[D][ds1307:101]: Write 14:12:32 2023-06-09  CH:OFF RS:0 SQWE:OFF OUT:OFF
[D][main:416]: Synchronized system clock
[D][sntp:078]: Synchronized time: 2023-06-09 16:27:32
[D][ds1307:101]: Write 14:27:32 2023-06-09  CH:OFF RS:0 SQWE:OFF OUT:OFF
[D][main:416]: Synchronized system clock
