### ISSUE TITLE
SDS011 sensor returns "Checksum doesn't match" error

### ISSUE THREAD

**Issue by RandomDucklingGenerator** [esphome/issues#4572]
### The problem

Connecting SDS011 to ESPHome results with constant Checksum doesn't match. I checked datagrams, for example returned message looks like this:

AA-C0-2C-00-37-00-7E-23-04-AB

Where checksum is 04.
Calulcated checksum is: 260 (dec)

Calculated checksums differs from calculated.  I found that it might be a problem with how SDS011 calculates checksum. I found this stackoverflow thread: https://arduino.stackexchange.com/questions/23177/sds011-dust-sensor-checksum-error and I tried adding % 256 for calculated checksum. It solved problem in my custom C# code.

For above example: 260 % 256 = 4. Checksum is correct.

### Which version of ESPHome has the issue?

2023.5.5

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

SDS011

### Example YAML snippet

```yaml
uart:
  rx_pin: 16
  tx_pin: 17
  baud_rate: 9600

  - platform: sds011
    pm_2_5:
      name: "2.5µm Outside Particulate Matter Concentration"
    pm_10_0:
      name: "10.0µm Outside Particulate Matter Concentration"
    update_interval: 0min
```
