### ISSUE TITLE
MEMS microphone (INMP441) throws interrupt errors on ESP32-CAM

### ISSUE THREAD

**Issue by Jpsy** [esphome/issues#4573]
### The problem

My MEMS microphone (INMP441) throws interrupt errors on ESP32-CAM MCUs while working normally on a standard ESP32 MCU (MH-ET ESP32 MiniKIT). The error is:
```
[17:33:16][D][voice_assistant:105]: Requesting start...
[17:33:16][D][voice_assistant:085]: Starting...
[17:33:16][V][esp-idf:000]: E (127282) I2S: i2s_dma_intr_init(538): Register I2S Interrupt error
[17:33:16][V][esp-idf:000]: E (127284) I2S: i2s_driver_install(1950): I2S interrupt initailze failed
```
It happens at the very moment, I start the recording for Voice Assist.
It is immediately followed by a crash & reboot of the MCU.

On ESP32-CAM the available GPIOs are quite limited due to the many GPIOs used by the camera. But I tried many possible variations of available GPIOs and they all fail in the same way. The GPIOs I tried are: 2, 12, 13, 14, 15, 1 (TX), 3 (RX) in arbitrary combinations. RX and TX were only used as a last, helpless resort. The error happens without them too.

The identical ESPHome YAML config (with adapted GPIOs) works on a normal ESP32.

I am far from being an expert at these things, but could it be that ESP32-CAM or ESPHome's esp32cam board definitions are hard-wired to block the first internal I2S controller I2S0 of the ESP32? If so, a solution could be to make i2s_audio configurable to use I2S1. 

### Which version of ESPHome has the issue?

2023.5.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.1

### What platform are you using?

ESP32

### Board

ESP32-CAM (AI Thinker Clone)

### Component causing the issue

i2s_audio

### Example YAML snippet

```yaml
# switch off logging through RX/TX so we can use them as GPIOs
logger:
  baud_rate: 0

# MEMS microphone INMP441
i2s_audio:
  i2s_lrclk_pin: GPIO14  # LRCLK, WS, FS
  i2s_bclk_pin: GPIO13   # BLCK, SCK
microphone:
  - platform: i2s_audio
    id: mic_i2s
    i2s_din_pin: GPIO2  # DIN, SDIN, SD, SDATA, ADCDATA
    adc_type: external
    pdm: false     # quite sure that INMP441 is NOT PDM!
    channel: left  # open or gnd on L/R input of INMP441 => left, high level => right
voice_assistant:
  microphone: mic_i2s

binary_sensor:    
  - platform: gpio
    pin: 
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    name: Talk Switch
    internal: true
    on_press:
      - voice_assistant.start:
    on_release:
      - voice_assistant.stop:
```

### Anything in the logs that might be useful for us?

```txt
[17:33:16][D][voice_assistant:105]: Requesting start...
[17:33:16][D][voice_assistant:085]: Starting...
[17:33:16][V][esp-idf:000]: E (127282) I2S: i2s_dma_intr_init(538): Register I2S Interrupt error
[17:33:16][V][esp-idf:000]: E (127284) I2S: i2s_driver_install(1950): I2S interrupt initailze failed
```
