### ISSUE TITLE
Pulse does not allow min/max_brightness params

### ISSUE THREAD

**Issue by Normanras** [esphome/issues#4582]
### The problem

According to the [Pulse Light effect](https://esphome.io/components/light/index.html#pulse-effect) in the documentation, you can pass a `min_brightness` and `max_brightness`. However, when I try to do this in ESPhome, I get the error: 
```[min_brightness] is an invalid option for [pulse]. Please check the indentation.```

I've looked around at various tutorials or other pieces of documentation, but nothing points toward what the correct indentation should be or if this was deprecated but not yet removed from the docs. Is this parameter still possible?

What led me here is trying to create a pulse effect without the light turning completely off between intervals. 

### Which version of ESPHome has the issue?

2023.5.5 (I believe, docker with latest tag)

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.3.6

### What platform are you using?

ESP32

### Board

ESP32-DEVKITV1

### Component causing the issue

neopixel lights

### Example YAML snippet

```yaml
- pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
```
