### ISSUE TITLE
SSD1306 contrast issue since 2023.06 dev

### ISSUE THREAD

**Issue by zed984** [esphome/issues#4587]
### The problem

I have two devices with the same LCD driver SSD1306. One via I2C and one via SPI. Other sensors share the bus and work fine.
Both LCDs were working fine before I update to the 2022.06 dev branch, now both have the same symptoms. Updated today again to the latest 2022.07 dev release for the same.

### Which version of ESPHome has the issue?

2023-07-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

ESP32-C3-DEVKITM

### Component causing the issue

display

### Example YAML snippet

```yaml
esphome:
  name: esp-sense-test-2
  # https://github.com/esphome/issues/issues/2931
  platformio_options:
    board_build.flash_mode: dio  

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "secret"

ota:
  password: "secret"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Esp-Sense-Test-2"
    password: "y3jrdldaRInb"
    
i2c:
  sda: GPIO0
  scl: GPIO1
  scan: false
  id: bus_a

sensor:
  - platform: bme680 #bme680_bsec
    temperature:
      name: "Office temperature"
      id: "office_temperature"
    pressure:
      name: "Office pressure"
      id: "office_pressure"
    humidity:
      name: "Office humidity"
      id: "office_humidity"
    gas_resistance:
      name: "Office Gas Resistance"
      id: "office_gas_resistance"
    address: 0x77
    update_interval: 60s

  - platform: bh1750
    name: "Office Illuminance"
    id: "office_illuminance"
    address: "0x23"
    update_interval: 15s

binary_sensor:
  - platform: gpio
    pin: GPIO10
    name: "Office motion"
    id: "office_motion"
    device_class: motion

font:
  - file: "gfonts://Roboto@700"
    id: roboto_large
    size: 35
  - file: "gfonts://Roboto"
    id: roboto_small
    size: 20

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: "lcd"
    address: 0x3C

    lambda: |-
      it.printf(it.get_width()/2, 4, id(roboto_large), TextAlign::TOP_CENTER, "%.1f°C", office_temperature->state);
      it.printf(0, it.get_height(), id(roboto_small), TextAlign::BOTTOM_LEFT, "%.0f %%", office_humidity->state);
      it.printf(it.get_width(), it.get_height(), id(roboto_small), TextAlign::BOTTOM_RIGHT, "%5.0f lx", office_illuminance->state);
```

### Anything in the logs that might be useful for us?

```txt
[21:22:15][C][ssd1306_i2c:023]: I2C SSD1306
[21:22:15][C][ssd1306_i2c:023]:   Rotations: 0 °
[21:22:15][C][ssd1306_i2c:023]:   Dimensions: 128px x 64px
[21:22:15][C][ssd1306_i2c:024]:   Address: 0x3C
[21:22:15][C][ssd1306_i2c:025]:   Model: SSD1306 128x64
[21:22:15][C][ssd1306_i2c:027]:   External VCC: NO
[21:22:15][C][ssd1306_i2c:028]:   Flip X: YES
[21:22:15][C][ssd1306_i2c:029]:   Flip Y: YES
[21:22:15][C][ssd1306_i2c:030]:   Offset X: 0
[21:22:15][C][ssd1306_i2c:031]:   Offset Y: 0
[21:22:15][C][ssd1306_i2c:032]:   Inverted Color: NO
[21:22:15][C][ssd1306_i2c:033]:   Update Interval: 1.0s
```

### Additional information

![image](https://github.com/esphome/issues/assets/24846010/263dbbf9-8244-4238-aef4-ca2ad7fa40bc)

**Comment by MOST2K2** [comment]
Same here, please fix it asap, with invert=true i get a black screen.

**Comment by zed984** [comment]
>  with invert=true i get a black screen.

Confirmed that invert=true gives a black screen as well.
Also tried various contrast settings which has limited effect.

**Comment by jimmy-edison** [comment]
Same issue here with SSD1306 and SH1106
- platform: ssd1306_i2c
    model: "SSD1306 128x64"

- platform: ssd1306_i2c
    model: "SH1106 128x64"

**Comment by erik3rik** [comment]
Same issue here. Using a 
```
display:
  - platform: ssd1306_spi
    model: "SH1106 128x64"
```
Invert=true gives black screen. Invert=false gives a completely white screen. I'm using a quite low contrast of 10%.

Worked on 2023.5.5. Broke when updated to 2023.6.0. Started working again when reverting back to 2023.5.5 and re-installed the code on the ESP-32.

I notice that there are quite a few updates that mention "display" in the release docs. The only breaking one is:

`display: add BaseImage and provide only Image::get_pixel method`

But that is not something I use. I don't even use images on it, just text.

**Comment by Electronlibre2012** [comment]
Hello,

i thought that ```invert=true``` will solved the issue because before the font is black and the text is white (or whenever color you choose to buy) and with this option the font is white and the text is black but its so bad that i cant read anything on my tiny 128x64 pixels ssd1306...

Wait for a fix please

**Comment by rubendediegomartinez** [comment]
Same issue, using:

**Comment by randybb** [comment]
@zed984 There is no contrast issue - only your OLED is burn-in like an old CRT... But the problem is that the whole screen is white and not showing anything. Would be good to remove that "contrast" from description/issue name and close the other issues that people created without checking other issues first.

**Comment by randybb** [comment]
As [khenderick](https://github.com/khenderick) mentioned, display component _inkplate6_ (model _inkplate_6_plus_) is also affected.

**Comment by ggottwald** [comment]
waveshare_epaper is also affected

**Comment by erik3rik** [comment]
I saw this issue was labeled `ssd1306_i2c`. FYI it also affects my display using `ssd1306_spi` i.e. also over SPI.

**Comment by adryzzts** [comment]
Same here, after upgrade at 2023.6.0, two display ko, screen all white

**Comment by mariusbaumann** [comment]
Same here with Inkplate 6. It stays white since the 2023.6.0 update. But maybe helpful observation: The graphs are being plotted correctly. 
![IMG_3424](https://github.com/esphome/issues/assets/9386539/ac848b67-30a0-4148-86af-4cf8a7789049)

**Comment by billmaterial** [comment]
Exactly the same issue also, no text shown on the screen.

platform: ssd1306_i2c
model: "SSD1306 128x64"
address: 0x3C

The "Invert" function seems to be opposite now too.

**Comment by guillempages** [comment]
Could you try explicitly setting a black text? (I.e. passing "Color::BLACK" as a color parameter on your printed texts)
if this does not work, Color::WHITE might do the trick (though I hope not ;-) )
Or just explicitly "Color(0,0,0,0)"?
We are working on a fix, but would need confirmation that the suspected issue is actually the root cause.

@ayufan, FYI

**Comment by ayufan** [comment]
@mariusbaumann Can you test this fix https://github.com/esphome/issues/issues/4587?

**Comment by daernsinstantfortress** [comment]
> @guillempages As a quick test, could you try explicitly setting a black text? (I.e. passing "Color::BLACK" as a color parameter on your printed texts)
> if this does not work, could you try an explicit "Color(0,0,0,0)"?

On the Waveshare ePaper 2.9", the whole display has gone black (it would normally be white), but forcing the text to black does indeed draw white text on the black screen:

```
it.print(10, 10, id(main_sensor_unit), Color::BLACK, "CUPRA");
```
![image](https://github.com/esphome/issues/assets/7900720/08333ea9-a19d-4ded-b1c9-46f424a7a6c9)

**Comment by ayufan** [comment]
@daernsinstantfortress It is the same problem. The `waveshare` does have inverted logic for pixels:

```cpp
  if (!color.is_on()) {
    this->buffer_[pos] |= 0x80 >> subpos;
  } else {
    this->buffer_[pos] &= ~(0x80 >> subpos);
  }
```

**Comment by guillempages** [comment]
@daernsinstantfortress the "quickest" fix/workaround would be to add an explicit "it.fill(Color::WHITE);" at the begining of your display lambda, until the fix gets merged and released.
Or just wait for the latter.

**Comment by rubendediegomartinez** [comment]
> @zed984 There is no contrast issue - only your OLED is burn-in like an old CRT... But the problem is that the whole screen is white and not showing anything. Would be good to remove that "contrast" from description/issue name and close the other issues that people created without checking other issues first.

I deleted the contrast line and the problem remains.  Previously to the ESPHome 2023.6.0 the display runs perfectly

I can appreciate some characters but are ilegibles.
BR

**Comment by billmaterial** [comment]
I can also confirm Guillempages fix of placing "it.fill(Color::BLACK);" at the beginning of the lambda section works with my display:

platform: ssd1306_i2c
model: "SSD1306 128x64"
address: 0x3C

**Comment by randybb** [comment]
Mentioned fix works with SSD1306, can somebody test it with other displays?
```yaml
external_components:
  - source: github://pr#4991
    components: display
```
