### ISSUE TITLE
ESP32 WiFi Signal and Uptime broken

### ISSUE THREAD

**Issue by Xeroxxx** [esphome/issues#459]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32: esp-wrover-kit

**Affected component:**

Uptime and WiFi Signal

**Description of problem:**

Uptime and WiFi Signal is broken. They do not report to Hass.io via Hass.io API.

![image](https://user-images.githubusercontent.com/1109954/59711927-65ff3e00-920c-11e9-9fe1-b7eea952b70c.png)

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```
      
  - platform: uptime
    name: ESPFlora Uptime
  
  - platform: wifi_signal
    name: ESPFlora WiFi Signal
    update_interval: 120s

switch:
  - platform: restart
    name: ESPFlora Restart

binary_sensor:
  - platform: status
    name: ESPFlora Status

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_ota

ota:
  password: !secret esp_ota

```

**Additional information and things you've tried:**
