### ISSUE TITLE
White display after ESPHome 2023.6.0

### ISSUE THREAD

**Issue by rubendediegomartinez** [esphome/issues#4592]
### The problem

![image](https://github.com/esphome/issues/assets/82880022/cfa3d596-8b86-40a8-9a32-c902f320abd5)

Can't see any text in the display

### Which version of ESPHome has the issue?

2023.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.6.2 Supervisor 2023.06.2 Operating System 10.3

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

i2c

### Example YAML snippet

```yaml
display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    id: my_display
    contrast: 60%
    pages:
```
