### ISSUE TITLE
 SSD1306 OLED Display only showing complete white

### ISSUE THREAD

**Issue by Sn00kiT** [esphome/issues#4593]
### The problem

![20230622_123729](https://github.com/esphome/issues/assets/77878228/68ef07fb-3c4a-4e67-bf87-16003ef0cd42)
![20230622_123720](https://github.com/esphome/issues/assets/77878228/b35e3d91-31b9-4bf1-a55c-182ba1f123c0) OLED Display only showing complete white after update to 2023.06

### Which version of ESPHome has the issue?

2023.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.2

### What platform are you using?

ESP32

### Board

Devkit

### Component causing the issue

 SSD1306 128x64 and also 128x32

### Example YAML snippet

```yaml
font:
  - file: 'arial.ttf'
    id: font1
    size: 20  

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(font1),  "%.1f   °C   Int", id(Temperature).state);
      it.printf(0, 21, id(font1),  "%.1f    %%   Int", id(Humidity).state);
      it.printf(0, 42, id(font1),  "%.1f   °C   Ext", id(TemperatureExternal).state);
```

### Anything in the logs that might be useful for us?

Also happening on a ESP8266
