### ISSUE TITLE
Power consumption in deep sleep

### ISSUE THREAD

**Issue by maframan** [esphome/issues#4595]
### The problem

High power consumptation in deep sleep mode.
By the esp32 documentation, the power consumptation must be between 0.15 mA (when the ULP coprocessor is on) and 10 µA.
(reference https://lastminuteengineers.com/esp32-sleep-modes-power-consumption/#:~:text=one%20by%20one.-,ESP32%20Active%20Mode,about%20240%20mA%20of%20power.)
In my case with last esphome firmware the consumption is about 5,4mA

![image](https://github.com/esphome/issues/assets/24868793/9692f914-7403-430f-a4d8-08a7def32019)

### Which version of ESPHome has the issue?

ESPHome 2023.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.6.2 Supervisor 2023.06.2 Frontend 20230608.0 - latest

### What platform are you using?

ESP32

### Board

esp32-s3

### Component causing the issue

N/A

### Example YAML snippet

```yaml
esphome:
  name: power-test
  friendly_name: Power Test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MuOrmqcbCsc0Fzys5vl6xb8HC5day3wUK/0bQ+Mug20="

ota:
  password: "ebbce1662db9203bb2ea675c96c29e6a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power-Test Fallback Hotspot"
    password: "xxxxxxxxxxx"

captive_portal:


deep_sleep:
  run_duration: 2min
  wakeup_pin:
    number: GPIO04
    inverted: False
    mode: INPUT_PULLUP
  wakeup_pin_mode: KEEP_AWAKE
  id: deep_sleep_1
```

### Anything in the logs that might be useful for us?

```txt
N/A
```

### Additional information

N/A
