### ISSUE TITLE
In 2023.6.0, AirThings BLE config reported as invalid despite being identical to documentation

### ISSUE THREAD

**Issue by strikeir13** [esphome/issues#4598]
### The problem

My yaml config for Airthings Wave Plus is identical to the yaml in the Airthings documentation, but there is an error given that prevents compiling: `At least one of 'id:' or 'name:' is required!.` My yaml config is included below.

### Which version of ESPHome has the issue?

2023.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.2

### What platform are you using?

ESP8266

### Component causing the issue

`Airthings_wave`

### Example YAML snippet

```yaml
sensor:
#Airthing Wave Plus BLE tracker
  - platform: airthings_wave_plus
    ble_client_id: airthings01
    update_interval: 5min # default
    temperature:
      name: "WavePlus Temperature"
    radon:
      name: "WavePlus Radon"
    radon_long_term:
      name: "WavePlus Radon Long Term"
    pressure:
      name: "WavePlus Pressure"
    humidity:
      name: "WavePlus Humidity"
    co2:
      name: "WavePlus CO2"
    tvoc:
      name: "WavePlus VOC"

ble_client:
  - mac_address: xx:xx:xx:xx:xx:xx [redacted but config worked prior to 2023.6.x]
    id: airthings01

esp32_ble_tracker:
```

### Anything in the logs that might be useful for us?

```txt
"At least one of 'id:' or 'name:' is required!."
```
