### ISSUE TITLE
Waveshare 7.5 " keeps black after update to 2023.6.0

### ISSUE THREAD

**Issue by TomTesner** [esphome/issues#4599]
### The problem

Waveshare display keeps complete black  after update to 2023.6.0. Display is trying to refresh but keeps black.
Tested on two seperate displays - issue the same. Esp32 device is reachable all the time.
Display model: Waveshare_epaper 7.50inV2

### Which version of ESPHome has the issue?

Firmware: 2023.6.0 (Jun 22 2023, 19:09:19)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.6.2

### What platform are you using?

ESP32

### Board

ESP 32 esp-wrover-kit

### Component causing the issue

Display

### Example YAML snippet

```yaml
esphome:
  name: mcu-displej75
  platform: ESP32
  board: esp-wrover-kit

spi:
  clk_pin: 13
  mosi_pin: 14

i2c:
  sda: 19
  scl: 21

display:
  - platform: waveshare_epaper
    id: displej_75
    cs_pin: 15
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 7.50inV2
    update_interval: 600s
```
