### ISSUE TITLE
Midea climate FAN_ONLY mode an SWING missing

### ISSUE THREAD

**Issue by djwmarcx** [esphome/issues#4611]
### The problem

After the last update I did, my midea-based ACs are not reporting the FAN_ONLY mode neither the swing modes.

Taking a look to the lastest PRs performed over related stuff I have found this:

https://github.com/esphome/esphome/pull/4425

Reverting back that PR gets everything working again. 

As far as I understand, all MIDEA systems do have the FAN_ONLY and swing settings and they are not reported in the autoconf.

### Which version of ESPHome has the issue?

2023.6.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2023.6.1

### What platform are you using?

ESP8266

### Board

esp12e

### Component causing the issue

midea

### Example YAML snippet

```yaml
substitutions:
  static_ip: 10.1.1.82
  topic_prefix: /livingroom/dinning_ac
  devicename: livingroom_dinning_ac
  friendlyname: Aire Comedor

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp12e

wifi:
  <<: !include common/wifi.yaml
mqtt:
  <<: !include common/mqtt.yaml
ota:
  <<: !include common/ota.yaml

# Disable logging over UART (required)
logger:
  level: DEBUG
  baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: GPIO1 # hardware dependant
  rx_pin: GPIO3 # hardware dependant
  baud_rate: 9600

# Main settings
climate:
  - platform: midea
    name: ${friendlyname} # Use a unique name.
    period: 1s # Optional
    timeout: 2s # Optional
    num_attempts: 3 # Optional
    autoconf: true # Autoconfigure most options.
    beeper: false # Beep on commands.
    visual: # Optional. Example of visual settings override.
      min_temperature: 17 °C # min: 17
      max_temperature: 30 °C # max: 30
      temperature_step: 0.5 °C # min: 0.5
    custom_fan_modes:
      - SILENT
      - TURBO
    outdoor_temperature: # Optional. Outdoor temperature sensor (may display incorrect values after long inactivity).
      name: Temperatura Exterior ${friendlyname}

switch:
  - !include common/restart_switch.yaml
```
