### ISSUE TITLE
[ESP8266/ESP8285] final linking failure: liblto_plugin.so: file too short

### ISSUE THREAD

**Issue by hekmon** [esphome/issues#4613]
### The problem

I can not update my smart plug firmware for 2 versions now (2023.5.x and 2023.6.x). Final linking fails on ` liblto_plugin.so` with the error `file too short`. More details below.

### Which version of ESPHome has the issue?

at least v2023.5.X & v2023.6.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

esp8285

### Example YAML snippet

```yaml
substitutions:
  devicename: "smart-plug"
  friendlyname: "Smart Plug"
  # Higher value gives lower watt readout
  current_res: "0.00237"
  # Lower value gives lower voltage readout
  voltage_div: "731"


esphome:
  name: $devicename
  friendly_name: $friendlyname
  comment: "Nous Smart Wifi Socket A1T (Tasmota)"
  project:
    name: "NOUS.Smart-Wifi-Socket"
    version: "A1T"

esp8266:
  board: esp8285
  restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<redacted>"

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename}-AP"
    password: !secret wifi_ap_password

captive_portal:

# see: https://esphome.io/components/time.html
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server
#web_server:
#  port: 80

light:
  - platform: status_led
    id: led
    pin:
      number: GPIO13
      inverted: true

binary_sensor:
  - platform: status
    name: Status

  # toggle relay on/off
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
    id: "button_state"
    on_press:
      - switch.toggle: "button_switch"

switch:
  - platform: template
    name: Switch
    icon: mdi:power
    optimistic: true
    id: "button_switch"
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    pin: GPIO14
    id: relay

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    icon: mdi:wifi
    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime
    update_interval: 60s
    icon: mdi:clock-outline

  - platform: adc
    pin: VCC
    name: "VCC Volt"
    unit_of_measurement: V
    device_class: VOLTAGE
    state_class: measurement

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    update_interval: 5s
    current:
      name: Current
      unit_of_measurement: A
      device_class: CURRENT
      state_class: measurement
      accuracy_decimals: 3
    power:
      name: Power
      unit_of_measurement: W
      device_class: POWER
      state_class: measurement
      accuracy_decimals: 0
    voltage:
      name: Voltage
      unit_of_measurement: V
      device_class: VOLTAGE
      state_class: measurement
      accuracy_decimals: 1
    energy:
      name: Energy
      unit_of_measurement: Wh
      device_class: ENERGY
      state_class: total_increasing
      accuracy_decimals: 0

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
    ssid:
      name: "WiFi SSID"
      icon: mdi:wifi
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    icon: mdi:numeric
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.6.2
INFO Reading configuration /config/smart-plug.yaml...
INFO Detected timezone 'Etc/UTC'
INFO Generating C++ source...
INFO Compiling app...
Processing smart-plug (board: esp8285; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
Compiling .pioenvs/smart-plug/src/esphome/components/adc/adc_sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/esp8266/core.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/esp8266/gpio.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/esp8266/preferences.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/gpio/switch/gpio_switch.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/hlw8012/hlw8012.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/homeassistant/time/homeassistant_time.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/light/addressable_light.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/light/automation.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/light/esp_color_correction.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/light/esp_hsv_color.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/light/esp_range_view.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/light/light_call.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/light/light_json_schema.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/light/light_output.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/light/light_state.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/output/automation.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/output/float_output.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/pulse_counter/pulse_counter_sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/sensor/sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/status/status_binary_sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/status_led/light/status_led_light.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/switch/automation.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/switch/switch.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/template/switch/template_switch.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/text_sensor/filter.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/text_sensor/text_sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/time/automation.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/time/real_time_clock.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/uptime/uptime_sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/version/version_text_sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/wifi_info/wifi_info_text_sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/components/wifi_signal/wifi_signal_sensor.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/application.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/color.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/component.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/component_iterator.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/controller.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/entity_base.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/helpers.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/log.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/scheduler.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/string_ref.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/time.cpp.o
Compiling .pioenvs/smart-plug/src/esphome/core/util.cpp.o
Compiling .pioenvs/smart-plug/src/main.cpp.o
Generating LD script .pioenvs/smart-plug/ld/local.eagle.app.v6.common.ld
Compiling .pioenvs/smart-plug/lib6da/ESPAsyncTCP-esphome/AsyncPrinter.cpp.o
Compiling .pioenvs/smart-plug/lib6da/ESPAsyncTCP-esphome/ESPAsyncTCP.cpp.o
Compiling .pioenvs/smart-plug/lib6da/ESPAsyncTCP-esphome/ESPAsyncTCPbuffer.cpp.o
Compiling .pioenvs/smart-plug/lib6da/ESPAsyncTCP-esphome/SyncClient.cpp.o
Compiling .pioenvs/smart-plug/lib6da/ESPAsyncTCP-esphome/tcp_axtls.c.o
Compiling .pioenvs/smart-plug/lib181/Hash/Hash.cpp.o
Archiving .pioenvs/smart-plug/lib181/libHash.a
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/CertStoreBearSSL.cpp.o
Archiving .pioenvs/smart-plug/lib6da/libESPAsyncTCP-esphome.a
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/ESP8266WiFi.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/ESP8266WiFiAP.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/ESP8266WiFiSTA-WPS.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/ESP8266WiFiScan.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/WiFiClient.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/WiFiServer.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/WiFiServerSecureBearSSL.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/WiFiUdp.cpp.o
Compiling .pioenvs/smart-plug/libfb1/ESP8266WiFi/enable_wifi_at_boot_time.cpp.o
Compiling .pioenvs/smart-plug/lib05d/ESPAsyncWebServer-esphome/AsyncEventSource.cpp.o
Compiling .pioenvs/smart-plug/lib05d/ESPAsyncWebServer-esphome/AsyncWebSocket.cpp.o
Compiling .pioenvs/smart-plug/lib05d/ESPAsyncWebServer-esphome/WebAuthentication.cpp.o
Archiving .pioenvs/smart-plug/libfb1/libESP8266WiFi.a
Compiling .pioenvs/smart-plug/lib05d/ESPAsyncWebServer-esphome/WebHandlers.cpp.o
Compiling .pioenvs/smart-plug/lib05d/ESPAsyncWebServer-esphome/WebRequest.cpp.o
Compiling .pioenvs/smart-plug/lib05d/ESPAsyncWebServer-esphome/WebResponses.cpp.o
Compiling .pioenvs/smart-plug/lib05d/ESPAsyncWebServer-esphome/WebServer.cpp.o
Compiling .pioenvs/smart-plug/lib070/DNSServer/DNSServer.cpp.o
Archiving .pioenvs/smart-plug/lib070/libDNSServer.a
Compiling .pioenvs/smart-plug/libfb2/ESP8266mDNS/ESP8266mDNS.cpp.o
Compiling .pioenvs/smart-plug/libfb2/ESP8266mDNS/LEAmDNS.cpp.o
Compiling .pioenvs/smart-plug/libfb2/ESP8266mDNS/LEAmDNS_Control.cpp.o
Archiving .pioenvs/smart-plug/lib05d/libESPAsyncWebServer-esphome.a
Compiling .pioenvs/smart-plug/libfb2/ESP8266mDNS/LEAmDNS_Helpers.cpp.o
Compiling .pioenvs/smart-plug/libfb2/ESP8266mDNS/LEAmDNS_Structs.cpp.o
Compiling .pioenvs/smart-plug/libfb2/ESP8266mDNS/LEAmDNS_Transfer.cpp.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_core/ed25519/core_ed25519.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_core/ed25519/core_ristretto255.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_hash/crypto_hash.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_hash/sha256/cp/hash_sha256_cp.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_hash/sha256/hash_sha256.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_onetimeauth/crypto_onetimeauth.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_scalarmult/crypto_scalarmult.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_stream/chacha20/ref/chacha20_ref.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_stream/chacha20/stream_chacha20.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_stream/crypto_stream.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/crypto_verify/sodium/verify.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/sodium/codecs.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/sodium/core.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/sodium/runtime.c.o
Compiling .pioenvs/smart-plug/lib4e7/libsodium/sodium/utils.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/openssl/cipher-aesgcm.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/ref/cipher-aesgcm.c.o
Archiving .pioenvs/smart-plug/libfb2/libESP8266mDNS.a
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/ref/cipher-chachapoly.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/ref/dh-curve25519.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/ref/hash-blake2b.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/ref/hash-blake2s.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/ref/hash-sha256.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/sodium/cipher-aesgcm.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/sodium/cipher-chachapoly.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/sodium/dh-curve25519.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/sodium/hash-blake2b.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/backend/sodium/hash-sha256.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/crypto/aes/rijndael-alg-fst.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/crypto/blake2/blake2b.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/crypto/blake2/blake2s.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/crypto/chacha/chacha.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/crypto/donna/curve25519-donna-c64.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/crypto/donna/curve25519-donna.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/crypto/donna/poly1305-donna.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/crypto/sha2/sha256.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/crypto/sha2/sha512.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/crypto/x25519/x25519.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/cipherstate.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/dhstate.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/errors.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/handshakestate.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/hashstate.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/internal.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/names.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/patterns.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/rand_os.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/rand_sodium.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/randstate.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/signstate.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/symmetricstate.c.o
Compiling .pioenvs/smart-plug/libb64/noise-c/protocol/util.c.o
Archiving .pioenvs/smart-plug/libFrameworkArduinoVariant.a
Compiling .pioenvs/smart-plug/FrameworkArduino/Crypto.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/Esp-frag.cpp.o
Archiving .pioenvs/smart-plug/libb64/libnoise-c.a
Compiling .pioenvs/smart-plug/FrameworkArduino/Esp-version.cpp.o
Archiving .pioenvs/smart-plug/lib4e7/libsodium.a
Compiling .pioenvs/smart-plug/FrameworkArduino/Esp.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/FS.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/FSnoop.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/IPAddress.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/LwipDhcpServer-NonOS.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/LwipDhcpServer.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/LwipIntf.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/LwipIntfCB.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/MD5Builder.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/Print.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/Schedule.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/StackThunk.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/Stream.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/StreamSend.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/Tone.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/TypeConversion.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/Updater.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/WMath.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/WString.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/abi.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/aes_unwrap.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/base64.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/cbuf.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/cont.S.o
Compiling .pioenvs/smart-plug/FrameworkArduino/cont_util.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_app_entry_noextra4k.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_eboot_command.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_features.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_flash_quirks.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_flash_utils.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_i2s.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_main.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_non32xfer.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_noniso.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_phy.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_postmortem.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_si2c.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_sigma_delta.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_spi_utils.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_timer.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_vm.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_waveform_phase.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_waveform_pwm.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_wiring.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_wiring_analog.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_wiring_digital.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_wiring_pulse.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_wiring_pwm.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/core_esp8266_wiring_shift.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/crc32.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/debug.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/exc-c-wrapper-handler.S.o
Compiling .pioenvs/smart-plug/FrameworkArduino/exc-sethandler.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/flash_hal.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/gdb_hooks.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/heap.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/hwdt_app_entry.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/libb64/cdecode.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/libb64/cencode.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/libc_replacements.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/mmu_iram.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/reboot_uart_dwnld.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/spiffs/spiffs_cache.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/spiffs/spiffs_check.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/spiffs/spiffs_gc.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/spiffs/spiffs_hydrogen.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/spiffs/spiffs_nucleus.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/spiffs_api.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/sqrt32.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/stdlib_noniso.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/time.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/uart.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/umm_malloc/umm_info.c.o
Compiling .pioenvs/smart-plug/FrameworkArduino/umm_malloc/umm_integrity.c.o
Compiling .pioenvs/smart-plug/FrameworkArduino/umm_malloc/umm_local.c.o
Compiling .pioenvs/smart-plug/FrameworkArduino/umm_malloc/umm_malloc.cpp.o
Compiling .pioenvs/smart-plug/FrameworkArduino/umm_malloc/umm_poison.c.o
Archiving .pioenvs/smart-plug/libFrameworkArduino.a
Linking .pioenvs/smart-plug/firmware.elf
/config/.esphome/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /config/.esphome/platformio/packages/toolchain-xtensa/bin/../libexec/gcc/xtensa-lx106-elf/10.3.0/liblto_plugin.so: error loading plugin: /config/.esphome/platformio/packages/toolchain-xtensa/bin/../libexec/gcc/xtensa-lx106-elf/10.3.0/liblto_plugin.so: file too short
collect2: error: ld returned 1 exit status
*** [.pioenvs/smart-plug/firmware.elf] Error 1
========================= [FAILED] Took 152.44 seconds =========================
```

### Additional information

The board is currently running with an ESPHome firmware of version 2023.4.4.
