### ISSUE TITLE
Flashing ESP32 Error: The program size is greater than maximum allowed

### ISSUE THREAD

**Issue by guidokieboom** [esphome/issues#4619]
### The problem

When comp

### Which version of ESPHome has the issue?

ESPHome 2023.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.06

### What platform are you using?

ESP32

### Board

nodemcu ESP32 240MHz, 320KB RAM, 4MB Flash

### Component causing the issue

ota, api, esp32_ble_tracker, bluetooth_proxy, i2s_audio, media_player

### Example YAML snippet

```yaml
i2s_audio:
  i2s_lrclk_pin: GPIO33
  i2s_bclk_pin: GPIO19

media_player:
  - platform: i2s_audio
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_dout_pin: GPIO25 # changed from 22 to 25
    mode: mono
```

### Anything in the logs that might be useful for us?

```txt
Compiling /data/esp32-03/.pioenvs/esp32-03/src/main.cpp.o
Linking /data/esp32-03/.pioenvs/esp32-03/firmware.elf
RAM:   [==        ]  16.9% (used 55360 bytes from 327680 bytes)
Flash: [==========]  106.2% (used 1947941 bytes from 1835008 bytes)
Error: The program size (1947941 bytes) is greater than maximum allowed (1835008 bytes)
*** [checkprogsize] Explicit exit, status 1
========================= [FAILED] Took 299.28 seconds =========================
```
