### ISSUE TITLE
Reading scratchpad from Dallas Sensor failed

### ISSUE THREAD

**Issue by nicholh** [esphome/issues#462]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 - Sonoff Basic
**Affected component:**

https://esphome.io/components/sensor/dallas.html

**Description of problem:**
I am having an issue whereby I get the error Reading scratchpad from Dallas Sensor failed using a DS18B20 sensor

The interersting thing is that

it works after the first boot following a flash. After subsequent power cycles it gets this message.
I have an mqqt on_message section in the config - when i remove this it works for every boot. The on_message config works.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
mqtt:
  broker: hidden
  discovery: false
  topic_prefix: home/beer_chiller_thermostat
  on_message:
    - topic: home/beer_chiller_thermostat/climate/thermostat/target_temperature/command
      qos: 0
      then:
        - mqtt.publish:
            topic: some/topic
            payload: "Something happened!"

dallas:
  - pin:  GPIO14
    update_interval: 15s

sensor:
  - platform: dallas
    index: 0
    id: current_temperature
    name: current_temperature
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

I have treid removing the mqtt on_message section and it works fine.
