### ISSUE TITLE
Waveshare 7.5inV2 does not seem to be supported

### ISSUE THREAD

**Issue by TobnacTobi** [esphome/issues#4628]
### The problem

# Problem
The Waveshare E-Ink Display flashes, but does not show/draw anything.  
Seems to be related to https://github.com/esphome/issues/issues/2880

I want to build a E-Ink Dashboard with Home-Assistant, ESPHome and these components:  
- AZ-Delivery ESP32 Dev KitC **V2** (ESP32-WROMM-32) ([Amazon](https://www.amazon.de/gp/product/B074RGW2VQ))
- Waveshare 7.5 Inch E-Paper Display Hat Module V2 ([Amazon](https://www.amazon.de/gp/product/B075R4QY3L))  
- HASS, ESPHome, etc  

Now, I tested multiple GPIO combinations, different board-ids (nodemcu-32s, az-delivery-devkit-v4, esp32dev) and other display model configurations (`7.50in-bV2`, `7.50inV2`, `7.50inV2alt`) and most of them either don't work or show this behavior:  
When updating, the display flickers (as for an full update) but then stays black or shows some "random" pattern that looks like stars in the night sky.

The board is working, I have tested others of the same version. Maybe the board is not supported (since it's V2 instead of the suggested V4).  
I flash it via [ESPHome Web](https://web.esphome.io) and it works without any problems. I can read the logs as well.  
What seems **suspicious**: There is a ~3 pixel border around the black rectangle that appears ( i know it's not the physical border since it flashes black when updating).
This might be some code which tries to draw as well and hides my actual print message behind it.

I am very thankful for any help, this has taken me way too long already.

### Which version of ESPHome has the issue?

2023.6.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.6.2

### What platform are you using?

ESP32

### Board

AZ-Delivery ESP32 Dev KitC V2

### Component causing the issue

Waveshare 7.5 Inch E-Paper Display Hat Module V2

### Example YAML snippet

```yaml
esphome:
  name: helloworld
  friendly_name: HelloWorld

esp32:
  board: nodemcu-32s # also tried az-delivery-devkit-v4, esp32dev
  framework:
    type: arduino

logger: # Enable logging
api: # Enable Home Assistant API

ota:
  password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "Helloworld Fallback Hotspot"
    password: "WItLm8NwlS07"

captive_portal:

font:
  - file: 'fonts/OpenSans-Regular.ttf' # located in ~/home-assistant-config/esphome/fonts/OpenSans-Regular.ttf
    id: font1
    size: 8

# Example configuration entry
spi:
  clk_pin: 13
  mosi_pin: 14
 
 
# --- Display Layout -----------------------------------------------------------
display:
  - platform: waveshare_epaper
    cs_pin: 15
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    reset_duration: 2ms
    model: 7.50inV2
    update_interval: 20s
    lambda: |-
      ESP_LOGD("main", "logging01");
      it.print(0, 0, id(font1), "Hello World!"); # here i already tested rectangle, which also does not work
      ESP_LOGD("main", "logging02");
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

**Comment by alexd321** [comment]
similar here, have a very dark screen, like the contrast is wrong.

rolled back to 2023.6.3 and still the same issue. i dont remember which version i had installed when it was working

**Comment by TobnacTobi** [comment]
> rolled back to 2023.5.4 and still the same issue. i dont remember which version i had installed when it was working

Thanks for this hint!  
Desparate for any solution I installed the version `2022.12.2` of ESPHome and it immediately worked!  
It probably broke inbetween. I had a look at the Change-Logs but there's nothing specific for the 7.5inV2 that might break it.

Maybe this will work for you as well.  
I'm glad that I can continue my project now, thanks!

**Comment by alexd321** [comment]
Reloading with v2022.12.1 now. I would guess one of these commits broke it. I am not familiar enough with github to look at file history across multiple versions. https://github.com/esphome/esphome/commits/dev/esphome/components/waveshare_epaper

![image](https://github.com/esphome/issues/assets/69210910/2d568a72-977f-446d-9403-ed25712b7e1a)

**Comment by alexd321** [comment]
I suspect one of these waveshare files: 

https://github.com/esphome/esphome/compare/f83f1bf..bd6d6ca#diff-062684c9f1a454d53ffc74c0ef373f0f1bef8e954051d4b97536365b28bfdb37

**Comment by okueng** [comment]
Works well on my setup (firebeetle, waveshare hat, 7.5inV2) on 2023.9.3
Did you check the inverted: true in the doc? The switches on the hat are correctly set (B,0)?

Here is my yaml setup:
```
  - platform: waveshare_epaper
    id: eink_display
    cs_pin: GPIO14
    dc_pin: GPIO13
    busy_pin: 
      number: GPIO25
      inverted: true
    reset_pin: GPIO26
    model: 7.50inV2
    reset_duration: 2ms
```
