### ISSUE TITLE
update_interval for Dallas sensor triggers press for binary_sensors

### ISSUE THREAD

**Issue by Jtef** [esphome/issues#4629]
### The problem

I've defined a Dallas sensor for a DS18B20 and the update_interval triggers on_press (or on_click etc.) for binary sensors.
If I set the update interval to 30s for Dallas the relay on pin 16 turns on, and back off after another 30 seconds and continues to toggle every 30 sec. If I don't set the update_interval it gets the default of 60s and does the same thing (on and off after 60 sec and so on).

Thank you!

### Which version of ESPHome has the issue?

2023.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.3

### What platform are you using?

ESP32-IDF

### Board

Kincony KC868-E16S

### Component causing the issue

i2c

### Example YAML snippet

```yaml
esphome:
  name: kincony-kc868-e16s
  friendly_name: Kincony KC868-E16S
  platform: ESP32
  board: esp32dev

logger:

captive_portal:

i2c:
  sda: 16
  scl: 15
  scan: true
  id: bus_a

pcf8574:
  - id: 'pcf8574_hub_out_1'  # for output channel 1-8
    address: 0x21

  - id: 'pcf8574_hub_out_2'  # for output channel 9-16
    address: 0x25

  - id: 'pcf8574_hub_in_1'  # for input channel 1-8
    address: 0x22

  - id: 'pcf8574_hub_in_2'  # for input channel 9-16
    address: 0x24

switch:
  - platform: gpio
    name: "e16s-output14"
    pin:
      pcf8574: pcf8574_hub_out_2
      number: 5
      mode: OUTPUT
      inverted: true
    id: output14

  - platform: gpio
    name: "e16s-output15"
    pin:
      pcf8574: pcf8574_hub_out_2
      number: 6
      mode: OUTPUT
      inverted: true
    id: output15

  - platform: gpio
    name: "e16s-output16"
    pin:
      pcf8574: pcf8574_hub_out_2
      number: 7
      mode: OUTPUT
      inverted: true
    id: output16

binary_sensor:
  - platform: gpio
    name: "DI1 - Entrance Left B1"
    pin:
      pcf8574: pcf8574_hub_in_2
      number: 7
      mode: INPUT
      inverted: true
    internal: true
    on_press:
      then:
      - switch.toggle: output14

dallas:
  - pin: 16
    update_interval: 30s

sensor:
  - platform: dallas
    address: 0x453c430457d4c928
    name: "Livingroom Temperature"
    id: livingroom_temperature
  - platform: dallas
    address: 0x9d3c450457bfc728
    name: "Bedroom Temperature"
    id: bedroom_temperature

```
