### ISSUE TITLE
When use mqtt API ,the Subscribed topics and state_topic not contained the dev info

### ISSUE THREAD

**Issue by xiaozonglong** [esphome/issues#4632]
### The problem
notice the bold and italic text

Pressure voltage (sensor.**_c3_debug_7b55e0_pressure_voltage_**)
MQTT discovery data:
Topic: homeassistant/sensor/c3-debug-7b55e0/pressure_voltage/config
Payload
device_class: voltage
unit_of_measurement: V
state_class: measurement
name: Pressure voltage
state_topic: c3-debug/sensor/**_pressure_voltage_**/state
availability_topic: c3-debug/**status**
unique_id: ESPsensorpressure_voltage
object_id: c3-debug-7b55e0_pressure_voltage
device:
  identifiers: 6055f97b55e0
  name: c3-debug-7b55e0
  sw_version: esphome v2023.6.2 Jun 28 2023, 07:57:41
  model: airm2m_core_esp32c3
  manufacturer: espressif
platform: mqtt

### Which version of ESPHome has the issue?

2023.6.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

airm2m_core_esp32c3

### Example YAML snippet

```yaml
mqtt:
  broker: mqtt.***.cn
  port: ***
  username: ***
  password: ***
  discovery_object_id_generator: device_name

  - platform: adc
    name: "Pressure voltage"
    pin: 00
    attenuation: 11dB
    accuracy_decimals: 3
    update_interval: 2s
    filters:
      - multiply: 2.0  # The voltage divider requires us to multiply by 2
      - 
```
