### ISSUE TITLE
The pulse_width sensor is not properly documented

### ISSUE THREAD

**Issue by konikvranik** [esphome/issues#4638]
### The problem

I'd like to measure how long is my pump enabled. So I setup pulse width sensor to measure it.

My expectation is that I'll get time of running of the pump, but I got some weird values of unknown time unit.

So is it measuring time in seconds? If true, then it doesn't work properly. After more than minute of run I got value of 0.013.

### Which version of ESPHome has the issue?

2023.6.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

not related

### What platform are you using?

ESP8266

### Board

ESP-01

### Component causing the issue

pulse_width

### Example YAML snippet

```yaml
- platform: pulse_width
    pin:
      number: GPIO1
      inverted: True
    name: Doba běhu čerpadla
    id: cerpadlo_pulse_width
    on_value:
      then:
        - if:
            condition:
              lambda: 'return x > 20.0;'
            then:
              - globals.set:
                  id: global_pulsewidth_watertotal
                  value: !lambda 'return id(global_pulsewidth_watertotal) + (x * .4);'
```

### Anything in the logs that might be useful for us?

```txt
nope
```
