### ISSUE TITLE
Sprinkler starts valves when Standby switch is on. 

### ISSUE THREAD

**Issue by timota** [esphome/issues#4648]
### The problem

Sprinkler controller is configured with Standby switch. When Standby switch is on, and one of actions, like `sprinkler.next_valve, sprinkler.previous_valve` (others are not tested), are called - sprinkler starts valves. 

From one side,  according to documentation sprinkler should not start any valves in Standby mode, from other side - easy workaround exists - check if sprinkler in standby mode before triggering any actions. 

### Which version of ESPHome has the issue?

2023.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.3

### What platform are you using?

ESP32

### Board

esp32 devkit v4

### Component causing the issue

sprinkler

### Example YAML snippet

```yaml
sprinkler:
  - id: sp_ctrlr
    main_switch:
      name: Sprinklers
      id: sp_main_switch
    standby_switch: 
      name: SP StandBy
      id: sp_standby_sw
...

  - platform: nextion
    id: nxt_sp_btnForward
    page_id: ${sp_home_page_id}
    component_id: ${sp_btn_next_id}
    component_name: ${sp_home_page_id}.${sp_btn_next_objname}
    on_press:
      then:
        - sprinkler.next_valve: sp_ctrlr
```
