### ISSUE TITLE
Screen st7789v pin problem.

### ISSUE THREAD

**Issue by BrownC0de** [esphome/issues#4649]
### The problem

Hi. I designed PCB, including on the screen, 1.69 (st7789v)
Connected advice how:
  clk_pin: GPIO19  
  mosi_pin: GPIO21  
   cs_pin: GPIO18
   dc_pin: GPIO5  
   reset_pin: GPIO22 
   blk: GPIO16 (platform: monochromatic)
But when using the screen does not work. And I don't see any errors, not when configuring, not in the logs.
But if clk => GPIO21 and mosi =>GPIO19 swapped (I tested it in and on my board and on the node + external screen module)
That screen works. Tell me why is that? I looked all over the documentation and didn't find any information.

### Which version of ESPHome has the issue?

st7789v

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

tested nodemcu 32

### Component causing the issue

spi, display

### Example YAML snippet

```yaml
spi:
  clk_pin: GPIO19  
  mosi_pin: GPIO21    
  force_sw: false
display:
  - platform: st7789v
    model: Adafruit RR 280x240 #Custom
    rotation: 90
    id: "my_display"
    cs_pin: GPIO18
    dc_pin: GPIO5   
    reset_pin: GPIO22 
    eightbitcolor: true  
    pages:     
      - id: page1
        lambda: |-    
          it.strftime(120, 0, id(font_smoll), Color(0, 255, 0), TextAlign::TOP_CENTER, "%d.%m.%Y", id(sntp_time).now());
          it.strftime(10, 65, id(font_big), TextAlign::LEFT, "%H:%M:%S", id(sntp_time).now());
          it.printf(1, 150, id(font_smoll), Color(80, 160, 255), TextAlign::TOP_LEFT, "CO2");
          it.printf(240, 150, id(font_smoll), Color(80, 160, 255), TextAlign::TOP_RIGHT, "Hello World!");
          it.printf(240, 190, id(font_smoll), Color(80, 160, 255), TextAlign::TOP_RIGHT, "%.1f", id(sntp_time).now());
      - id: page2
        lambda: |-
          it.strftime(120, 0, id(font_smoll), Color(255, 0, 0), TextAlign::TOP_CENTER, "%d.%m.%Y", id(sntp_time).now());
          it.strftime(10, 65, id(font_big), TextAlign::LEFT, "%H:%M:%S", id(sntp_time).now());
          it.printf(1, 150, id(font_smoll), Color(80, 160, 0), TextAlign::TOP_LEFT, "CO2");
          it.printf(240, 150, id(font_smoll), Color(80, 160, 0), TextAlign::TOP_RIGHT, "%.1f", id(sntp_time).now());
          it.printf(240, 190, id(font_smoll), Color(80, 160, 0), TextAlign::TOP_RIGHT, "%.1f", id(sntp_time).now());	

font:                          
  - file: "gfonts://Roboto"
    id: font_big
    size: 65
   
  - file: "gfonts://Roboto"
    id: font_smoll
    size: 40
```

### Anything in the logs that might be useful for us?

```txt
Clear
```
