### ISSUE TITLE
Problems displaying negative numbers in PVVX MiThermometer Display

### ISSUE THREAD

**Issue by oukene** [esphome/issues#4658]
### The problem

Negative numbers are not displayed on some systems when using print_bignum and print_smallnum.

You are directly assigning a negative number to a 2-byte unsigned variable.

In the number of days system, there is no underflow and zero is always stored.

Please modify the print_bignum and print_smallnum functions so that negative numbers can be output through calculations.

### Which version of ESPHome has the issue?

2023.5.5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
esp32_ble_tracker:

ble_client:
- mac_address: "A4:C1:38:B1:CD:7F"
  id: pvvx_ble_display

display:
- platform: pvvx_mithermometer
  ble_client_id: pvvx_ble_display
  lambda: |-
    it.print_bignum(-23);
    it.print_unit(pvvx_mithermometer::UNIT_DEG_C);
    it.print_smallnum(-33);
    it.print_percent(true);
    it.print_happy(true);
    it.print_bracket(true);
```
