### ISSUE TITLE
Using Remote Transmitter in home assistant will cause Connection reset by peer

### ISSUE THREAD

**Issue by lijiazhiren** [esphome/issues#4661]
### The problem

in home assistant service
This code works fine with

[9005, -4584, 460, -1758, 491, -583, 536, -610, 512, -609, 509, -632, 492, -624, 495, -627, 493, -626, 492, -646, 475, -1757, 491, -1756, 496, -1737, 511, -1794, 457, -1757, 493, -1755, 494, -1757, 496, -1794, 454, -1775, 476, -644, 475, -683, 436, -669, 454, -643, 476, -644, 477, -606, 514, -624, 494, -646, 474, -1794, 456, -1756, 493, -1790, 462, -1794, 457, -1773, 476, -1757, 523]

This code is not working properly

[9134, -4368,  742, -1566,  770, -436,  770, -434,  770, -1538,  770, -436,  770, -1536,  770, -436,  772, -434,  770, -434,  770, -434,  770, -1536,  770, -434,  770, -436,  770, -434,  770, -436,  770, -434,  770, -436,  772, -434,  770, -436,  772, -434,  770, -434,  770, -1536,  770, -434,  772, -434,  770, -436,  770, -436,  770, -436,  770, -436,  770, -1536,  770, -436,  770, -1536,  770, -436,  768, -436,  770, -1538,  770, -436,  772, -19842,  796, -434,  772, -434,  770, -436,  770, -434,  770, -434,  770, -434,  770, -436,  770, -434,  770, -436,  770, -434,  770, -434,  772, -434,  770, -434,  770, -1536,  772, -434,  770, -436,  770, -436,  770, -436,  770, -434,  770, -436,  770, -434,  770, -436,  770, -434,  770, -434,  772, -434,  770, -434,  770, -434,  770, -436,  770, -1536,  770, -436,  770, -434,  772, -1536,  770, -39854,  9136, -4368,  742, -1564,  770, -436,  770, -434,  772, -1536,  770, -434,  772, -1536,  772, -434,  770, -434,  770, -436,  770, -436,  770, -1536,  770, -434,  770, -436,  770, -434,  772, -436,  770, -434,  770, -436,  770, -434,  772, -434,  770, -436,  770, -434,  770, -1538,  770, -436,  770, -434,  770, -436,  770, -434,  772, -434,  770, -436,  772, -1536,  770, -1536,  770, -1538,  770, -436,  770, -434,  770, -1536,  770, -434,  772, -19842,  794, -436,  770, -434,  770, -436,  770, -434,  770, -434,  772, -434,  770, -436,  770, -434,  770, -434,  770, -436,  770, -434,  770, -436,  770, -434,  770, -434,  772, -436,  770, -436,  770, -436,  770, -436,  770, -436,  770, -434,  770, -436,  770, -1536,  770, -436,  770, -436,  770, -434,  770, -436,  770, -434,  770, -436,  770, -1536,  770, -434,  770, -434,  770, -1536,  770]

Here is a tip from esphome

WARNING rf-text.local: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for rf-text.local
WARNING Disconnected from API
INFO Successfully connected to rf-text.local

The code that cannot be used normally is my air conditioner code. There are many. I use a component called (smartir)

But when I delete the switch component and button component, the air conditioner code can work normally in the home assistant

So this is caused by the insufficient performance of esp8266 or the problem of esphome?

### Which version of ESPHome has the issue?

2023.6.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.6.3 Supervisor 2023.06.4 Operating System 10.3

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

api:   services:

### Example YAML snippet

```yaml
api:
  services:
    - service: send_ir_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'
            carrier_frequency: 38kHz
            transmitter_id: hongwai_fashe

remote_transmitter:
  - id: hongwai_fashe
    pin: GPIO14
    carrier_duty_percent: 50%

  - id: Rf433_transmitter
    pin: GPIO5
    carrier_duty_percent: 100%

  - id: Rf315_transmitter
    pin: GPIO13
    carrier_duty_percent: 100%

remote_receiver:
  - id: IR_receiver
    pin:
      number: GPIO12
      inverted: True
    dump:
    - raw
    - nec

  - id: RF433_receiver
    pin:
      number: GPIO3
      inverted: True
    dump:
      - rc_switch
    tolerance: 60%
    filter: 50us
    idle: 3ms

  - id: RF315_receiver
    pin:
      number: GPIO4
    dump:
      - rc_switch
    tolerance: 60%
    filter: 50us
    idle: 3ms

switch:

button:
```

### Anything in the logs that might be useful for us?

```txt
WARNING rf-text.local: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for rf-text.local
WARNING Disconnected from API
INFO Successfully connected to rf-text.local
```
