### ISSUE TITLE
tm1637 - No colon when invert is true

### ISSUE THREAD

**Issue by jj-uk** [esphome/issues#4666]
### The problem

https://esphome.io/components/display/tm1637.html

When `inverted: true` is used, the colon feature doesn't work.
When `inverted: false` is used, the colon feature works as expected.

### Which version of ESPHome has the issue?

2023-6-4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.0

### What platform are you using?

ESP8266

### Board

esp12e

### Component causing the issue

tm1637 

### Example YAML snippet

```yaml
# set `inverted: false` and run. Colon shows.
# set `inverted: true` and run. Colon does not show.

display:
  platform: tm1637
  id: display_module
  clk_pin: GPIO5
  dio_pin: GPIO4
  length: 4
  inverted: false
  update_interval: 500ms
  lambda: |-
    it.print( "12.34" );
```
