### ISSUE TITLE
binary sensor with "delayed_on" for SW-420 never fires #466

### ISSUE THREAD

**Issue by jeffehobbs** [esphome/issues#467]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io/ESPHome add-on

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32-WROOM-32

**Affected component:**

binary_sensor

**Description of problem:**

If I add a "delayed_on" to the binary_sensor connected to the SW-420, the event never fires.

**Problem-relevant YAML-configuration entries:**

This code works fine:
```yaml

# Enables the SW-420 Vibration Sensor
binary_sensor:  
  - platform: gpio  
    name: Dryer  
    pin:
      number: GPIO13
      mode: INPUT
    device_class: vibration
    filters:
      - delayed_off: 5s

```

...but if I add a "delayed_on: 5s" to that YAML, the event will never fire.

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

Tried different measures of time (s, ms). Tried different order of statements. no luck.
