### ISSUE TITLE
esp8266 2 Analog sensors not working correctly

### ISSUE THREAD

**Issue by CodingGhost** [esphome/issues#4673]
### The problem

home assistant only sees the "feuchtigkeit" sensor but not the test sensor. BUT the "feuchtigkeit" sensor now contains the values of the test sensor. 100% reproducable.

### Which version of ESPHome has the issue?

2023.6.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.6.2

### What platform are you using?

ESP8266

### Board

nodemcuV3

### Component causing the issue

ADC

### Example YAML snippet

```yaml
sensor:
  - platform: adc
    name: feuchtigkeit
    id: soil_voltage
    update_interval: never
    pin: A0
    force_update: True
    accuracy_decimals: 3

  - platform: adc
    name: test
    id: vccv
    pin: VCC
    update_interval: 2s
    force_update: True
    accuracy_decimals: 3
```
