### ISSUE TITLE
RGBWW light on ESP32 not restoring properly after reboot

### ISSUE THREAD

**Issue by PaoloTK** [esphome/issues#4674]
### The problem

When I restore the light I observe the following:
- The RGB color and brightness are restored correctly
- The cold and warm white channels aren't restored correctly: the cold white channel is set to 100%, the warm white channel is set to 0%.

No matter what I have the cold and warm white channels set to, if they're at 0%, 100% or 32%, they always get restored CW at 100% and WW at 0% after reboot.

### Which version of ESPHome has the issue?

2023.6.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7

### What platform are you using?

ESP32

### Board

Quinled-Esp32

### Component causing the issue

RGBWW Light

### Example YAML snippet

```yaml
light:
  - platform: rgbww
    name: ${friendly_name}
    restore_mode: RESTORE_DEFAULT_OFF 
    id: rgbcct
    icon: "mdi:led-strip"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    cold_white: pwm_cw
    warm_white: pwm_ww
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2200 K
```
