### ISSUE TITLE
Can't configure more than one UART when using sdm_meter component.

### ISSUE THREAD

**Issue by luiscampiz** [esphome/issues#4675]
### The problem

Cant configure more than one UART when using sdm_meter component.

### Which version of ESPHome has the issue?

2023.6.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.1

### What platform are you using?

ESP32

### Board

denky32

### Component causing the issue

sdm_meter

### Example YAML snippet

```yaml
uart:
  - id: uart_1
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 2400
    rx_buffer_size: 512
  - id: uart_2
    tx_pin: GPIO27
    rx_pin: GPIO26
    baud_rate: 2400

sensor:
  - platform: sdm_meter
    id: sdm630m
    phase_a:
      current:
        name: "SDM630M L1 Current"
      voltage:
        name: "SDM630M L1 Voltage"
      active_power:
        name: "SDM630M L1 Power"
      power_factor:
        name: "SDM630M L1 Power Factor"
      apparent_power:
        name: "SDM630M L1 Apparent Power"
      reactive_power:
        name: "SDM630M L1 Reactive Power"
      phase_angle:
        name: "SDM630M L1 Phase Angle"     
    frequency:
      name: "SDM630M Frequency"
    total_power:
      name: "SDM630M Total Power"
    import_active_energy:
      name: "SDM630M Import Active Energy"
    export_active_energy:
      name: "SDM630M Export Active Energy"
    import_reactive_energy:
      name: "SDM630M Import Reactive Energy"
    export_reactive_energy:
      name: "SDM630M Export Reactive Energy"
    update_interval: 20s
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.6.4
INFO Reading configuration /config/esphome/esp35.yaml...
WARNING GPIO2 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

modbus: None
  
  Too many candidates found for 'uart_id' type 'uart::UARTComponent' Some are 'uart_1', 'uart_2'.
  []
```

### Additional information

The second UART is for an Inverter. The idea is using just one esp32 for the meter and the inverter.
IMHO the solution would be to add "uart_id" parameter to the component, and not to just use the first UART. Kind of like the GPS module. 

Very nice component, 
Thanks,

Luis.

**Comment by randybb** [comment]
How it should know to which UART is your modbus connected to? With only one it works automagically, with more you need to create this mapping. 
So just add this:
```yaml
modbus:
  uart_id: uart_1
```
or in case of more modbus busses:
```yaml
modbus:
  - id: modbus_sdm
         uart_id: uart_1

sensor:
  - platform: sdm_meter
    modbus_id: modbus_sdm
```
