### ISSUE TITLE
Playing sound on a device with display

### ISSUE THREAD

**Issue by alfwro13** [esphome/issues#4678]
### The problem

I have a Node MCU32 device (I have tried several different devices with the same result) with I2C ssd1306 display setup with update interval of 6s.
I also have MAX98357A DAC board connected to that device.
When mp3 music or TTS is played over the connected speaker when the screen refreshes audio breaks. Setting the update interval allows for most TTS announcements to play ok however playing any sort of mp3 music is unusable

### Which version of ESPHome has the issue?

v2023.6.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.1

### What platform are you using?

ESP32

### Board

nodemcu-32s, esp-wrover-kit

### Component causing the issue

I2C or I2S

### Example YAML snippet

```yaml
i2s_audio:
  i2s_lrclk_pin: 26
  i2s_bclk_pin: 27

media_player:
  - platform: i2s_audio
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_dout_pin: 25
    mode: mono

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true

display:
  - platform: ssd1306_i2c
    id: oled_display_a
    i2c_id: bus_a
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 6s
```

### Anything in the logs that might be useful for us?

```txt
no error messages
```
