### ISSUE TITLE
Automation of esp32_ble_tracker cannot be triggered after bluetooth_proxy is enabled

### ISSUE THREAD

**Issue by ysqspdk** [esphome/issues#4680]
### The problem

After using bluetooth_proxy, the automation of esp32_ble_tracker can be triggered before the device is connected to HomeAssistant through the API, but when the device is connected to HomeAssistant through the API, esp32_ble_tracker automation will no longer trigger.

In version 2023.5.5, the automation works fine.

### Which version of ESPHome has the issue?

2023.6.1-2023.6.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.1

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

bluetooth proxy

### Example YAML snippet

```yaml
esphome:
  name: test
  friendly_name: test
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ""

ethernet:
  type: LAN8720
  id: eth
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
  on_ble_advertise:
    - mac_address:
        - A4:C1:xx:xx:xx:xx
      then:
        - lambda: |-
            ESP_LOGD("ble_adv", "New BLE device");
            ESP_LOGD("ble_adv", "  address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  name: %s", x.get_name().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
                ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
            ESP_LOGD("ble_adv", "  Advertised service data:");
            for (auto data : x.get_service_datas()) {
                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
            }
            ESP_LOGD("ble_adv", "  Advertised manufacturer data:");
            for (auto data : x.get_manufacturer_datas()) {
                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
            }

bluetooth_proxy:
  id: ble_proxy
  active: true
  # cache_services: true
```

### Anything in the logs that might be useful for us?

```txt
␛[0;36m[D][ble_adv:044]: New BLE device␛[0m
␛[0;36m[D][ble_adv:045]:   address: A4:C1:xx:xx:xx:xx␛[0m
␛[0;36m[D][ble_adv:046]:   name: xxxx␛[0m
␛[0;36m[D][ble_adv:047]:   Advertised service UUIDs:␛[0m
␛[0;36m[D][ble_adv:051]:   Advertised service data:␛[0m
␛[0;36m[D][ble_adv:053]:     - 0x0000: (length 10)␛[0m
␛[0;36m[D][ble_adv:055]:   Advertised manufacturer data:␛[0m
␛[0;36m[D][ble_adv:057]:     - 0x0000: (length 1)␛[0m
␛[0;33m[W][component:204]: Component esp32_ble_tracker took a long time for an operation (0.56 s).␛[0m
␛[0;33m[W][component:205]: Components should block for at most 20-30ms.␛[0m
␛[0;36m[D][api:102]: Accepted 192.168.xx.xx␛[0m
␛[0;36m[D][api.connection:1030]: Home Assistant 2023.7.1 (192.168.xx.xx): Connected successfully␛[0m
␛[0;32m[I][ota:113]: Boot seems successful, resetting boot loop counter.␛[0m
␛[0;36m[D][esp32.preferences:114]: Saving 1 preferences to flash...␛[0m
␛[0;36m[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed␛[0m
␛[0;36m[D][esp32_ble_tracker:245]: Starting scan...␛[0m
␛[0;36m[D][esp32_ble_tracker:245]: Starting scan...␛[0m
␛[0;36m[D][esp32_ble_tracker:245]: Starting scan...␛[0m
```
