### ISSUE TITLE
Converting time to text

### ISSUE THREAD

**Issue by theniz** [esphome/issues#469]
yes

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

raspberry pi 3b+
**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**
 

**Description of problem:**
I want to send system time to nextion display.
As you know, there is no tool for date & time on nextion display.
So I need to convert system time to text.
I have tried several times to do it, but I didn't got any success.
Could please help me.....

2nd issue is How to send 'dim' command to nextion.
I found in this issues's article shown that we could control nextion's brightness through dim setting. then, how I can set dim on esphome?

Thanks in advance for yout reply.

**Problem-relevant YAML-configuration entries:**
```yaml
time:
  - platform: sntp
    id: s_time
    timezone: UTC-9
    servers:
      - 1.pool.ntp.org

display:
  - platform: nextion
    id: hamon01_display
    lambda: |-
      it.set_component_text_printf("t5", "%Y-%M-%D", id(s_time),now());
or 
      it.set_component_text_printf("t5", strftime("%Y-%M-%D %H:%M", id(s_time),now()));
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
