### ISSUE TITLE
Safe Mode button just restarts the MCU

### ISSUE THREAD

**Issue by ESP4Ever** [esphome/issues#4693]
### The problem

I have few projects based on ESP8266/ESP8285 with a "Safe Mode" soft button activated because it is the only way to make OTA working. 
However, this button requires to be pressed twice: first time it just reboots the MCU but didn't put it into a safe mode - is it an expected behavior?

### Which version of ESPHome has the issue?

2023.6.5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
# Soft Buttons
button:
  - platform: safe_mode
    id: safemode_btn
    name: "Safe Mode"
    entity_category: "diagnostic"
    disabled_by_default: true
```
