### ISSUE TITLE
Climate component activates cooling output when HEAT only mode selected

### ISSUE THREAD

**Issue by ESP4Ever** [esphome/issues#4694]
### The problem

Climate component + PID:
I'm trying to create an environmental controller which controls a mixing valve for heating and the fan speed for cooling.
Everything seems to be fine except that if the target temperature is lower than the current one and the HEAT mode selected, the cooling output is activated while I expect the Off(Heat) or Idle(Heat) mode instead (valve is closed, fan is stopped). If this is as this feature designed then what is the difference between Cool, Heat and Heat/Cool modes?

### Which version of ESPHome has the issue?

2023.6.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

the latest one

### What platform are you using?

ESP8266

### Component causing the issue

Climate + PID

### Example YAML snippet

```yaml
# PID Climate Controller
climate:
  - platform: pid
    id: pid_controller
    name: "PID Climate Controller"
    default_target_temperature: 20°C

    visual:
      min_temperature: 15
      max_temperature: 30
      temperature_step: 1.0

    sensor: temperature_sensor
    heat_output: valve_position
    cool_output: fan_speed

    control_parameters:
      kp: 0 #0.49460
      # ki: 0 #0.00487
      # kd: 0 #12.56301
      #min_integral: 0
      starting_integral_term: 0
      # output_averaging_samples: 5      # smooth the output over 5 samples
      # derivative_averaging_samples: 10  # smooth the derivative value over 10 samples
    
    # deadband_parameters:
    #   threshold_high: 1.0°C       # deadband within +/-0.5°C of target_temperature
    #   threshold_low: -1.0°C
    #   deadband_output_averaging_samples: 15

    on_state: #on_control
      - lambda: |-
          int mode = id( pid_controller).mode;
          int action = id( pid_controller).action;
          ESP_LOGD( "TEST: Climate", "Mode: %i", mode);
          ESP_LOGD( "TEST: Climate", "Action: %i", action);
          if( mode == CLIMATE_MODE_OFF) {
            id( pid_controller).reset_integral_term();
            auto call = id( valve).make_call();
            call.set_command_close();
            call.perform();
          }

output:
  # Output: HEATING
  - platform: template
    id: valve_position
    type: float
    write_action:
      lambda: |-
        static float last_position = id( valve).position;
        float position = float( int( state * 100 / 5) * 5) / 100;
        ESP_LOGD( "TEST: Climate", "Last valve position: %f", last_position);
        ESP_LOGD( "TEST: Climate", "Requested valve position: %f", position);

  # Output: COOLING
  - platform: template
    id: fan_speed
    type: float
    write_action:
      lambda: |-
        ESP_LOGD( "TEST: Climate", "Fan speed: %f", state);
```
