### ISSUE TITLE
Different invert values for UART TX and RX pin are supported for ESP-IDF framework but still invalid in config

### ISSUE THREAD

**Issue by ddv2005** [esphome/issues#4699]
### The problem

UART component for ESP-IDF framework support different invert values for UART TX and RX pin but validate_invert_esp32 still return an error.

### Which version of ESPHome has the issue?

2023.6.5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Example YAML snippet

```yaml
uart:
  - id: s21_uart
    tx_pin: 26
    rx_pin:
      number: 27
      inverted: true
    baud_rate: 2400
    data_bits: 8
    parity: EVEN
    stop_bits: 2
```

### Anything in the logs that might be useful for us?

```txt
Different invert values for TX and RX pin are not (yet) supported for ESP32.
  - id: s21_uart
    tx_pin: 26
    rx_pin: 
      number: 27
      inverted: True
    baud_rate: 2400
    data_bits: 8
    parity: EVEN
    stop_bits: 2
```
