### ISSUE TITLE
Critical! ble frequently stalls since 2022.12.0

### ISSUE THREAD

**Issue by xcray** [esphome/issues#4700]
### The problem

after upgrade the firmware to 2022.12.x, ble stack will works few hours after poweron, then stalled, no sensors updating anymore, while other components working normal. 
the latest normal release is 2021.11.5.
I had tried serial flash with ESPHome 2022.12.0 and almost every subsequent release, the issue is still exist.

### Which version of ESPHome has the issue?

2022.12.x-2023.6.x

### What type of installation are you using?

Home Assistant Add-on & Docker

### Which version of Home Assistant has the issue?

irrelevant

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

esp32_ble_tracker

### Example YAML snippet

```yaml
esp32_ble_tracker:
sensor:
  - platform: xiaomi_lywsd03mmc
    mac_address: "xxxxxx"
    bindkey: "xxxxxx"
    temperature:
      name: "LYWSD Temp"
    humidity:
      name: "LYWSD Humi"
    battery_level:
      name: "LYWSD BattLev"
  - platform: xiaomi_hhccjcy01
    mac_address: 'xxxxxx'
    temperature:
      name: "HHCC01 Temp"
    moisture:
      name: "HHCC01 Mois"
    illuminance:
      name: "HHCC01 Illum"
    conductivity:
      name: "HHCC01 SoilCond"
esp32_touch:
  setup_mode: false
  iir_filter: 10ms
binary_sensor:
  - platform: esp32_touch
    name: "Touch PinO27"
    pin: GPIO27
    threshold: 1000
```

### Anything in the logs that might be useful for us?

```txt
nothing logged
```
