### ISSUE TITLE
on the lastest ESPhome version with HA, SonOff Basic R1 lost connectivity

### ISSUE THREAD

**Issue by drumstick77** [esphome/issues#4701]
### The problem

All sonoff basic R1 lost connectivity from the 2nd last update. flashing via USB does not resolve the issue.

### Which version of ESPHome has the issue?

2023.6.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.2

### What platform are you using?

ESP8266

### Board

Sonoff basic R1

### Example YAML snippet

```yaml
esphome:
  name: sonoff-basic1
  friendly_name: SonOff Basic1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff-Basic1 Fallback Hotspot"
    password: "nK3q2d6pMHAS"

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes    

web_server:
```
