### ISSUE TITLE
Fingerprint Grow doesn't work anymore

### ISSUE THREAD

**Issue by stich86** [esphome/issues#4705]
### The problem

Hi guys,

i've using for about 3 years an R502 sensor with ESPHome (starting with early implementation of fingerprint_grow component and the the official one). 

Now on one of last update something has broken the componet. On first tests I've tried to replace the sensor with new one but no luck. Also changin ESP module doesn't seems to work.

If i use an empty R502 directly connected to PC using TTL2USB and SWGDemo code from Adafruit, the sensor is recognized and it can scan the fingerprints.

Any advice? There is a way to put UART in debug to see if the ESP see the module?

Thanks in advance 

### Which version of ESPHome has the issue?

2023.6.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.1

### What platform are you using?

ESP8266

### Board

Wemos Mini D1

### Component causing the issue

fingerprint_grow

### Example YAML snippet

```yaml
esphome:
  name: wemos_fingerprint
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: "xxxx"
  password: "xxxxx"
  reboot_timeout: 30s
  power_save_mode: none

uart:
  rx_pin: D1
  tx_pin: D2
  baud_rate: 57600

text_sensor:
  - platform: template
    name: "Impronta Rilevata"
    id: fingerprint_readed
    icon: "mdi:fingerprint"
  - platform: template
    name: "Stato Lettore"
    id: fingerprint_state
    icon: "mdi:gesture-spread"
  - platform: version
    name: "ESPHome Version"
  - platform: template
    name: "Uptime Wemos Fingerprint"
    update_interval: 42s
    icon: mdi:clock-start
    lambda: |-
      int seconds = (id(uptime_sec).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      if ( days ) {
        return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( hours ) {
        return { (String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( minutes ) {
        return { (String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else {
        return { (String(seconds) +"s").c_str() };
      }

switch:
  - platform: restart
    name: "Reboot Wemos Fingerprint"

fingerprint_grow:
  on_finger_scan_matched:
    - homeassistant.event:
        event: esphome.finger_scan_matched
        data:
          finger_id: !lambda 'return finger_id;'
          confidence: !lambda 'return confidence;'
    - if:
        condition:
          lambda: 'return confidence > 40;'
        then:
          - homeassistant.tag_scanned: !lambda |-
             switch (finger_id) {
               case 1:
                 return "1";
               case 2:
                 return "2";
               case 3:
                 return "3";
               case 4:
                 return "4";
               case 5:
                 return "5";
               case 6:
                 return "6";                 
               default:
                 return "person_unknown";
             }
          - text_sensor.template.publish:
              id: fingerprint_readed
              state: !lambda |-
                        switch (finger_id) {
                          case 1:
                            return "1";
                          case 2:
                            return "2";
                          case 3:
                            return "3";
                          case 4:
                            return "4";
                          case 5:
                            return "5";
                          case 6:
                            return "6";                            
                          default:
                            return "Unregistered Tag";
                         }
    - text_sensor.template.publish:
        id: fingerprint_state
        state: !lambda 'return "Finger Match!";'
    - fingerprint_grow.aura_led_control:
        state: BREATHING
        speed: 200
        color: BLUE
        count: 1
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 2        

  on_finger_scan_unmatched:
    - homeassistant.event:
        event: esphome.finger_scan_unmatched
    - text_sensor.template.publish:
        id: fingerprint_state
        state: !lambda 'return "Unathorized Finger!";'

  on_enrollment_scan:
    - homeassistant.event:
        event: esphome.finger_enrollment_scan
        data:
          finger_id: !lambda 'return finger_id;'
          scan_num: !lambda 'return scan_num;'
    - text_sensor.template.publish:
        id: fingerprint_state
        state: !lambda 'return "Enrolling into slot " + to_string(finger_id) + ", scanned " + to_string(scan_num) + " time(s)";'
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: BLUE
        count: 2
    - fingerprint_grow.aura_led_control:
        state: ALWAYS_ON
        speed: 0
        color: PURPLE
        count: 0

  on_enrollment_done:
    - homeassistant.event:
        event: esphome.finger_enrollment_done
        data:
          finger_id: !lambda 'return finger_id;'
    - text_sensor.template.publish:
        id: fingerprint_state
        state: !lambda 'return "Enrolled into slot " + to_string(finger_id);'
    - fingerprint_grow.aura_led_control:
        state: BREATHING
        speed: 100
        color: BLUE
        count: 2

  on_enrollment_failed:
    - homeassistant.event:
        event: esphome.finger_enrollment_failed
        data:
          finger_id: !lambda 'return finger_id;'
    - text_sensor.template.publish:
        id: fingerprint_state
        state: !lambda 'return "Failed to enroll into slot " + to_string(finger_id);'
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 2

sensor:
  - platform: fingerprint_grow
    fingerprint_count:
      name: "Fingerprint Count"
    status:
      name: "Fingerprint Status"
    capacity:
      name: "Fingerprint Capacity"
    security_level:
      name: "Fingerprint Security Level"
    last_finger_id:
      name: "Fingerprint Last Finger ID"
    last_confidence:
      name: "Fingerprint Last Confidence"
  - platform: uptime
    name: "Uptime Wemos Fingerprint (secs)"
    id: uptime_sec
  - platform: wifi_signal
    name: "Segnale WiFi Wemos Fingerprint"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Stato ESP Fingerprint"
  - platform: fingerprint_grow
    name: "Fingerprint Enrolling"

api:
  services:
    - service: fingerprint_grow_enroll
      variables:
        finger_id: int
        num_scans: int
      then:
        - fingerprint_grow.enroll:
            finger_id: !lambda 'return finger_id;'
            num_scans: !lambda 'return num_scans;'
    - service: fingerprint_grow_cancel_enroll
      then:
        - fingerprint_grow.cancel_enroll:
    - service: fingerprint_grow_delete
      variables:
        finger_id: int
      then:
        - fingerprint_grow.delete:
            finger_id: !lambda 'return finger_id;'
    - service: fingerprint_grow_delete_all
      then:
        - fingerprint_grow.delete_all:
  password: "elloello2"
  encryption:
    key: XXXXXXX
    reboot_timeout: 30s

logger:

ota:
  password: "XXXXX"
```
