### ISSUE TITLE
Sensor Name is used instead of Id in Id fields in API responses

### ISSUE THREAD

**Issue by decayofmind** [esphome/issues#4707]
### The problem

If both `name` and `id` are defined for the sensor, then `name` has precedence and used in both `/events` and `/sensor`

Example config: 

```
sensor:
  - platform: tsl2591
    name: "Ambient Light TSL2591"
    calculated_lux:
      id: ambient_light
      name: "TSL2591 Lux"
      filters:
        - filter_out: 65535
        - filter_out: nan
        - sliding_window_moving_average:
            window_size: 15
            send_every: 2
            send_first_at: 2
```

As per documentation I should query sensor by it's `id` using `/sensor/<id>` schema, however with the configuration above values will be accessible on `http://esphome.local/sensor/tsl2591_lux` and not on `http://esphome.local/sensor/ambient_light`

Event stream will use `name` instead of `id` as well:

```
event: state
data: {"id":"sensor-tsl2591_lux","name":"TSL2591 Lux","value":62.78326,"state":"62.7833 lx","icon":"mdi:brightness-6"}
```

### Which version of ESPHome has the issue?

2023.6.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

HUZZAH32 v2 feather
