### ISSUE TITLE
Unable to use the new sensors for DSMR Capacity tarif Belgium

### ISSUE THREAD

**Issue by phdelodder** [esphome/issues#4710]
### The problem

Trying to add the new sensors for the P1 Capactity tarif for Belgium. As per PR (https://github.com/esphome/esphome/pull/5081) 

Still unable to compile.

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Slimmelezer

### Component causing the issue

DSMR

### Example YAML snippet

```yaml
substitutions:
  name: slimmelezer
packages:
  zuidwijk.slimmelezer: github://zuidwijk/dsmr/slimmelezer.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: dsmr
    active_energy_import_current_average_demand:
      name: "Current Average Demand"
    active_energy_import_maximum_demand_running_month:
      name: "Maximum Month Demand"
    active_energy_import_maximum_demand_last_13_months:
      name: "13 Month Maximum Quarterly Demand"
```

### Anything in the logs that might be useful for us?

```txt
src/main.cpp:917:18: error: 'class esphome::dsmr::Dsmr' has no member named 'set_active_energy_import_current_average_demand'
  917 |   dsmr_instance->set_active_energy_import_current_average_demand(sensor_sensor_25);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:928:18: error: 'class esphome::dsmr::Dsmr' has no member named 'set_active_energy_import_maximum_demand_running_month'
  928 |   dsmr_instance->set_active_energy_import_maximum_demand_running_month(sensor_sensor_26);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:939:18: error: 'class esphome::dsmr::Dsmr' has no member named 'set_active_energy_import_maximum_demand_last_13_months'
  939 |   dsmr_instance->set_active_energy_import_maximum_demand_last_13_months(sensor_sensor_27);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*** [/data/slimmelezer/.pioenvs/slimmelezer/src/main.cpp.o] Error 1
```
