### ISSUE TITLE
Animation does not work without image component

### ISSUE THREAD

**Issue by TillFleisch** [esphome/issues#4719]
### The problem

The animation component won't work without the image component.

When adding an animation like this:
```
animation:
  - file: "nyan_64x32.gif"
    id: nyan_cat
    type: RGB565
    resize: 64x32
```

ESPHome will throw the following error:
```
Failed config

image: None
  
  'file' is a required option for [0].
  []
required key not provided
```

A workaround to this issue is adding a image component to the configuration:
```
image:
  - file: "pxArt.png"
    id: pxArt
```

The issue was not present prior to the 2023.7.0 update.

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

animation
