### ISSUE TITLE
ESP32 Improv BLE components's status_indicator writes like crazy

### ISSUE THREAD

**Issue by xrh0905** [esphome/issues#4723]
### The problem

The ESP32_Imporv components has an option to set an output as status indicator.
However, the component seems to be writing the output every loop, make it impossible for the LED to shows anything else.
Also, it filled up my logs.

Is this behavior expected?

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

esp32dev

### Component causing the issue

esp32_improv

### Example YAML snippet

```yaml
esp32_improv:
  authorizer: btn0
  status_indicator: imporvoutput

output:
  - platform: ledc
    pin: GPIO2
    id: led1output
  - platform: template
    id: statusoutput
    type: binary
    write_action:
      - output.set_level:
          id: led1output
          level: !lambda return state;
  - platform: template
    id: imporvoutput
    type: binary
    write_action:
      - light.control:
          id: statusled_internal
          state: !lambda return state;

light:
  - platform: status_led
    id: statusled_internal
    output: statusoutput
    restore_mode: ALWAYS_OFF
```

### Anything in the logs that might be useful for us?

```txt
15:48:20	[D]	[light:036]	
'statusled_internal' Setting:
15:48:20	[D]	[status_led:049]	
'statusled_internal': Setting state OFF
* Above lines repeats countless times every seconds.
```
