### ISSUE TITLE
Can't explicitly disable wifi BTM or RRM

### ISSUE THREAD

**Issue by joshuaspence** [esphome/issues#4725]
### The problem

`enable_btm` and `enable_rrm` can only be set to `true` for ESP32 devices using the `esp-idf` framework, but setting these to `false` on an ESP8266 isn't valid, instead the settings have to be omitted.

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

Wifi

### Example YAML snippet

```yaml
---
substitutions:
  enable_btm: 'false'
  enable_rrm: 'false'

esphome:
  name: 'test'

esp8266:
  board: 'esp01_1m'

wifi:
  enable_btm: '${enable_btm}'
  enable_rrm: '${enable_rrm}'
```

### Anything in the logs that might be useful for us?

```txt
Failed config

wifi: [source test.yaml:13]
  
  This feature is only available with frameworks ['esp-idf'].
  enable_btm: false
  
  This feature is only available with frameworks ['esp-idf'].
  enable_rrm: false
```
