### ISSUE TITLE
ESP 2023.7.0 failed config 

### ISSUE THREAD

**Issue by grssll** [esphome/issues#4728]
### The problem

After updating to 7.0 having following issue: can not update, download logs, download yaml.
INFO ESPHome 2023.7.0
INFO Reading configuration /config/esphome/esphome-web-34f45c.yaml...

Failed config

image: None
  
  'file' is a required option for [0].
  []
required key not provided

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp32dev

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.7.0
INFO Reading configuration /config/esphome/esphome-web-34f45c.yaml...

Failed config

image: None
  
  'file' is a required option for [0].
  []
required key not provided
```

**Comment by ssieb** [comment]
You didn't provide the config.

**Comment by chanchal1987** [comment]
I also faced the same issue with animation. I needed to add one dummy image to compile my old yaml.

**Comment by grssll** [comment]
Same on 2023.7.0.1 failed to install.
Failed config
image: None
  'id' is a required option for [0].
  []
required key not provided
My cofing file below:
```
substitutions:
  name: "Redia Centre" # Location and Entity Names (Capitals and Spaces Allowed)
  max_temp: "65" # Threshold for MAX Fan Speed and Alarm

esphome:
  name: "fan-redia-centre"
esp32:
  board: esp32dev
  framework:
    type: arduino

preferences:
  flash_write_interval: 10000s

# Enable logging
logger:
  logs:
    dallas.sensor: none
    number: none
    sensor: none
    light: none
    fan: none
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    

ota:
 

wifi:
  ssid: 
  password: 
  # Optional manual IP
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "
    password: "
    
captive_portal:

spi:
  mosi_pin: GPIO23
  clk_pin: GPIO18
  miso_pin: GPIO19

display:
  - platform: ili9xxx
    model: TFT 2.4
    cs_pin: GPIO5
    dc_pin: GPIO32
    reset_pin: GPIO33
    rotation: 270
    lambda: |-
      it.printf(0, 20, id(bold), Color(255, 0, 0), " %.1f", id(temp_sensor_1).state);
      it.print(250, 20, id(bold), Color(255, 255, 255), "/");
      it.printf(300, 20, id(bold), Color(0, 0, 255), " %.1f", id(rpm_1).state);
      auto red = Color(255, 0, 0);
        auto green = Color(0, 255, 0);
        auto blue = Color(0, 0, 255);
        auto white = Color(255, 255, 255);

color:
  - id: my_red50
    red: 100%
    green: 3%
    blue: 5%

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 80
  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: bold
    size: 60

  - file: "gfonts://Oswald"
    id: oswald
    size: 30

animation:
  - file: "fan.gif"
    id: my_animation
    resize: 50x50

# Testing 2 Channel 0-10v I2C DAC GP8403
external_components:
  - source: github://pr#4495
    components: gp8403
    refresh: 1min

i2c:
  - id: bus_a
    sda: 3
    scl: 1
    scan: true
    frequency: 400000Hz
  - id: bus_b
    sda: 21
    scl: 22
    scan: true

# Set voltage of 0-5v or 0-10v 
gp8403:
  i2c_id: bus_b
  id: gp8403_hub
  voltage: 10v
  address: 0x58
  

number:
  # Slider to set Min Temperature to start fan
  - platform: template
    id: set_temp
    name: $name Set Temp
    optimistic: True
    min_value: 25
    max_value: 65
    initial_value: 25
    step: 1
    restore_value: true # Restore setting between reboots
  - platform: template
    id: set_temp_1
    name: $name Set Temp 1
    optimistic: True
    min_value: 25
    max_value: 65
    initial_value: 25
    step: 1
    restore_value: true # Restore setting between reboots

sensor:
  - platform: ina219
    i2c_id: bus_a
    address: 0x45
    shunt_resistance: 0.01 ohm
    current:
      name: "Roof_fan_current"
    power:
      name: "Roof_fan_power"
    bus_voltage:
      name: "Roof_fan_voltage"
    max_voltage: 32 v
    max_current: 8 amp
    update_interval: 30sec 
    
  - platform: bme280
    i2c_id: bus_b
    address: 0x76
    humidity:
      name: roof humidity
      id: humid
      accuracy_decimals: 0
    temperature:
      name: $name Temperature
      id: temp_sensor
      accuracy_decimals: 0
      oversampling: 16x

       # Adjust fan speed(1-100%). Else, turn it off and set the speed to 1
      on_value:
        - lambda: !lambda |
            auto pct = map(x, id(set_temp).state, $max_temp, 1, 20);
            if (pct>1) {
              auto call = id(the_fan).turn_on(); call.set_speed(pct); call.perform();
            } else {
              auto call = id(the_fan).turn_off(); call.set_speed(1); call.perform();
            }

  - platform: bme280
    i2c_id: bus_b
    address: 0x77
    humidity:
      name: roof humidity 1
      id: humid_1
      accuracy_decimals: 0
    temperature:
      name: $name Temperature 1
      id: temp_sensor_1
      accuracy_decimals: 0
      oversampling: 16x

       # Adjust fan speed(1-100%). Else, turn it off and set the speed to 1
      on_value:
        - lambda: !lambda |
            auto pct = map(x, id(set_temp_1).state, $max_temp, 1, 20);
            if (pct>1) {
              auto call = id(the_fan_1).turn_on(); call.set_speed(pct); call.perform();
            } else {
              auto call = id(the_fan_1).turn_off(); call.set_speed(1); call.perform();
            }
  

# Reports RPM by pulse_counter
  - platform: pulse_counter
    pin:
      number: 27
      mode: INPUT_PULLUP
    name: $name RPM
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.333
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 10s
    accuracy_decimals: 0
  - platform: pulse_counter
    pin:
      number: 26
      mode: INPUT_PULLUP
    name: $name RPM 1
    id: rpm_1
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.333
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 10s
    accuracy_decimals: 0
  
switch:
  # Fan power (MOSFET)
  - platform: gpio
    pin: 2
    id: fan_power
  - platform: gpio
    pin: 3
    name: $name

fan:
  - platform: speed
    id: the_fan
    output: gp8403_0
    name: $name Fan
    speed_count: 20
    restore_mode: ALWAYS_OFF
  - platform: speed
    id: the_fan_1
    output: gp8403_1
    name: $name Fan 1
    speed_count: 20
    restore_mode: ALWAYS_OFF

light:
  # On-Board LED
  - platform: monochromatic
    id: d4_light
    output: d4_light_pwm
    effects:
      - pulse:
          name: flashfast
          transition_length: 0.0s
          update_interval: 0.04s
          
  - platform: monochromatic
    name: $name Fan
    output: gp8403_0
    gamma_correct: 1.2
  - platform: monochromatic
    name: $name Fan 1
    output: gp8403_1
    gamma_correct: 1.2
  

output:
  - platform: ledc
    id: fan_pwm
    pin:
      number: GPIO4
    min_power: 0.05 #Slowest Speed for Noctua Fans is 5% - Set to 0 for 'Other' Fans
    frequency: 22.5kHz #Pulse the fan fast to prevent noise
    
  - platform: gp8403
    channel: 0
    id: gp8403_0
  - platform: gp8403
    channel: 1
    id: gp8403_1
  
  - platform: ledc
    id: d4_light_pwm
    pin:
      number: GPIO16
      inverted: true
```
