### ISSUE TITLE
display full_update_every not working after uograde from 2023.6.3 to 2023.7.0

### ISSUE THREAD

**Issue by Vulle66** [esphome/issues#4730]
### The problem

I have 3 InkPlate6 displays running, after upgrading to ESPHome version 2023.7.0 the full_update_every is ignored. Before updating i was running with partial update every 10s and full_update_every 600 giving full update every 100 minutes. On version the full update is every 10s.

### Which version of ESPHome has the issue?

2023.7.o

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.2

### What platform are you using?

ESP32

### Board

Esp-wrover-kit

### Component causing the issue

Display 

### Example YAML snippet

```yaml
display:
- platform: inkplate6
  id: inkplate_display
  greyscale: false
  partial_updating: true
  update_interval: 10s
  full_update_every: 600
```
