### ISSUE TITLE
ESPHOME/BT Proxy - Missing dependencies

### ISSUE THREAD

**Issue by GaryOkie** [esphome/issues#4734]
### The problem

I'm unable to update an ESP32 BT-Proxy wirelessly using ESPHOME for past and current versions of HASS and ESPHOME. I am only able to update via ESP32 connection to a PC with a fresh rebuild.

The first issue I encountered was a failure with "e**spressif/toolchain-riscv32-esp**" not found. After much research, I finally found that I could specify this package in the esp32 bt proxy yaml:

esphome:
    platform_packages:
     - framework-espidf @ 3.40300.0
     - toolchain-riscv32-esp

The installation then proceeded nicely until it hit a roadblock with a fatal error.    Helpers.cpp references #include "esp_mac.h"  which is not found in the default configuration I have.  The provided URL registry search on platformio also turns up zip.   I guess this could be easily resolved if I knew what to add to the default configuration or if any manual additions for BT Proxy could be done automatically in an updated default config.

```
src/esphome/core/helpers.cpp:24:10: fatal error: esp_mac.h: No such file or directory

*****************************************************************
* Looking for esp_mac.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_mac.h"
* Web  > https://registry.platformio.org/search?q=header:esp_mac.h
```

There was another error about a pyparsing 2.3.1 incompatibility but that did not seem to be fatal. For some reason, the install process uninstalled the proper 3.1.0 pyparsing. Details are all in the diagnostic log attached to this issue.

### Which version of ESPHome has the issue?

The latest version.

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.2

### What platform are you using?

ESP32

### Board

Teyleten Robot ESP32S ESP32 ESP-WROOM-32 Development Board

### Component causing the issue

 esp_mac.h  not found

### Example YAML snippet

```yaml
#------------------------------------------------
#This is the default auto-generated BT Proxy YAML config with the one addition of toolchain-riscv32-esp.
#-----------------------------------------------
substitutions:
  name: esp32-bluetooth-proxy-578a40
  friendly_name: Bluetooth Proxy 578a40

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  platformio_options:
    platform_packages:
     - framework-espidf @ 3.40300.0
     - toolchain-riscv32-esp 

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    platform_version: 3.4.0
    
api:
  encryption:
    key: pq3a2D...................................


wifi:
  ssid: xxxxx
  password: xxxxx

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```

### Anything in the logs that might be useful for us?
[logs_update-all(1).txt](https://github.com/esphome/issues/files/12136791/logs_update-all.1.txt)

### Additional information

One other odd discrepancy is that the BT Proxy Device Info says this:

bluetooth-proxy  by esphome
Firmware: 2023.6.5 (Jul 10 2023, 04:16:51)
Hardware: 1.0 

But the Configuration panel says this:

Firmware 2023.7.0
