### ISSUE TITLE
alpha3 component sensors not working

### ISSUE THREAD

**Issue by jan-hofmeier** [esphome/issues#4736]
### The problem

When using the alpha3 component, no values are reported by the sensors, despite the pump being connected and no errors shown in the log.

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

alpha3

### Example YAML snippet

```yaml
ble_client:
  - mac_address: "04:ee:03:bc:d8:70"
    id: radiator_pump

sensor:
  - platform: alpha3
    ble_client_id: radiator_pump
    flow:
      name: "Radiator FLOW"
```

### Additional information

It seems on some pumps the requests and responses look different than on the pumps then I have to test. So I need more information, so I can implement a generic solution, that works for every pump.

If you run into this problem, please comment with the following information
- From which country is your pump
- What is written on the type label of the pump
- does it work with the attached [alpha3_denmark.zip](https://github.com/esphome/issues/files/12137363/alpha3_denmark.zip) external comonent
- If it doesn't work with the attached external comonent a bluetooth log if you can generate one

If neither the version upstream in esphome nor the modified external component works, I need a bluetooth log of the communication of the GO Remote app with the pump, to see how the requests and responses look like in your case. On Android this is called 'HCI Snoop log' and on iOS 'bluetooth debug'.
