### ISSUE TITLE
Component display.ili9xxx requires component spi

### ISSUE THREAD

**Issue by wojtekadams** [esphome/issues#4738]
### The problem

Is not possible to run display.ili9xxx where is not an SPI connection.

### Which version of ESPHome has the issue?

2023.7.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.3

### What platform are you using?

ESP32

### Board

esp32-s3-devkitc-1

### Component causing the issue

display/ili9xxx

### Example YAML snippet

```yaml
# LCD
display:
  - platform: ili9xxx
    model: ILI9486
    cs_pin: 14
    dc_pin: 27
    reset_pin: 33
    dimensions: 320x480
    data_rate: 20MHz
    rotation: 90
    #color_palette: IMAGE_ADAPTIVE
    lambda: |-
      it.fill(my_red);
      it.filled_rectangle(50, 60, 30, 42,my_red);
      it.print(0, 0, id(roboto), id(my_black), TextAlign::TOP_LEFT, "Hello World!");
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.7.0
INFO Reading configuration /config/esphome/elecrow-lcd.yaml...
Failed config

display.ili9xxx: [source /config/esphome/elecrow-lcd.yaml:94]
  
  Component display.ili9xxx requires component spi.
```

### Additional information

Link to product: [https://www.elecrow.com/esp-terminal-with-esp32-3-5-inch-parallel-480x320-tft-capacitive-touch-display-rgb-by-chip-ili9488.html?idd=3](url)
