### ISSUE TITLE
Modbus CRC Check failed! C022!=00 PZEM004T-V3

### ISSUE THREAD

**Issue by jonathanpalomino** [esphome/issues#4746]
### The problem

He conectado a los pines RX0 y TX0 sus correspondientes al PZEM-004T V3 (TX y RX) de 100A respectivamente. Sin embargo recibo los siguientes mensajes de error:
<html>
<body>

22:49:17 | [V] | [modbus:199] | Modbus write: 01.04.00.00.00.0A.70.0D (8)
-- | -- | -- | --
22:49:17 | [D] | [uart_debug:158] | >>> "p\r"
22:49:17 | [V] | [modbus:042] | Modbus received Byte  1 (0X1)
22:49:17 | [V] | [modbus:042] | Modbus received Byte  4 (0X4)
22:49:17 | [V] | [modbus:042] | Modbus received Byte  0 (0X0)
22:49:17 | [V] | [modbus:042] | Modbus received Byte  0 (0X0)
22:49:17 | [V] | [modbus:042] | Modbus received Byte  0 (0X0)
22:49:17 | [V] | [modbus:042] | Modbus received Byte  0 (0X0)
22:49:17 | [W] | [modbus:108] | Modbus CRC Check failed! C022!=00
22:49:17 | [W] | [modbus:108] | Modbus CRC Check failed! C022!=00
22:49:17 | [D] | [uart_debug:158] | <<< "\x01\x04\x00\x00\x00\n"
22:49:17 | [V] | [modbus:042] | Modbus received Byte  10 (0Xa)
22:49:17 | [V] | [modbus:042] | Modbus received Byte  112 (0X70)
22:49:17 | [V] | [modbus:042] | Modbus received Byte  13 (0Xd)
22:49:17 | [V] | [modbus:042] | Modbus received Byte  13 (0Xd)

</body>
</html>

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.0

### What platform are you using?

ESP32

### Board

ESP32-WROOM32

### Component causing the issue

pzemac

### Example YAML snippet

```yaml
esphome:
  name: esphome-web-a70328
  friendly_name: ESPHome Web a70328

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "g4j73gUOGwzTmfZ7Dm1fa4KBx2VhvDfP6xwQiAnJLkk="

# Servidor Web para poder consultar información por web
# https://esphome.io/components/web_server.html
web_server:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-A70328"
    password: "RtO60blWZypX"

captive_portal:
    

# Indicamos los pines donde hemos conectado TX y RX del dispositivo, teniendo en cuenta que siempre han de ser invertidos TX->RX, RX->TX
uart:
  id: energomonitor_uart
  rx_pin: GPIO1
  tx_pin: GPIO3
  baud_rate: 9600
  stop_bits: 2
  data_bits: 8
  parity: NONE
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

sensor:
  # Usaremos pzemac o pzem004t dependiendo de si estamos usando un PZEM-004T V3 o V1
  - platform: pzemac
    address: 1
    current:
      name: "Current"
      accuracy_decimals: 2
    voltage:
      name: "Voltage"
      accuracy_decimals: 2
    energy:
      name: "Energy"
      unit_of_measurement: Wh
      accuracy_decimals: 1
      id: p_energy
    power:
      name: "Power"
      unit_of_measurement: W
      accuracy_decimals: 2
      id: p_power
    frequency:
      name: "Frequency"
      unit_of_measurement: Hz
      accuracy_decimals: 2
    power_factor:
      name: "Power Factor"
      accuracy_decimals: 2
      id: p_power_factor
    update_interval: 20s
```

### Anything in the logs that might be useful for us?

```txt
He hecho la misma prueba con un ESP-WROOM-32 de 30 pines sin éxito
```

### Additional information

He hecho la prueba con 3 PZEM-004T V3 de 100A sin éxito.
Se hizo alimentación del modulo PZEM-004T V3 con transformador HI-LINK de 220V a 5v
