### ISSUE TITLE
Speed Fan component - issue with speed_count

### ISSUE THREAD

**Issue by ESP4Ever** [esphome/issues#4749]
### The problem

It looks like the speed_count setting is counted as a max_speed: when it is set to 10 the max speed is 10 at 100%

### Which version of ESPHome has the issue?

2023.6.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

latest

### What platform are you using?

ESP8266

### Component causing the issue

Speed Fan

### Example YAML snippet

```yaml
fan:
  - platform: speed
    id: fan1
    output: dimmer1
    name: "Ventilation Fan"
    speed_count: 10
    #restore_mode: ${fan_restore_mode}
    on_speed_set:
      lambda: |-
        if (id( fan1).state) {
          float temp = id( fan1).speed;
          ESP_LOGD( "TEST: temp", "speed: %f", temp);
        }
```
