### ISSUE TITLE
BME680 with BSEC: Unexpected humidity data with temperature offset

### ISSUE THREAD

**Issue by xaviergr** [esphome/issues#4752]
### The problem

I have a suspicion that my humidity readings with the bme680_bsec component are wrong so I did the following test:
Connect two bme680 sensors (side by side, and away from the board) on an esp32 board and use the bm680_bsec component to get temperature and humidity data in lp mode (sample every 3 seconds).

As expected the two sensors report slightly higher temperature than the actual temperature and both require different offsets to report the same temperature (-0.5 and -0.3). After adjusting the offset both sensors show the exact same temperature but the humidity between them is off by 2 points (68% vs 70% at 25C). This humidity mismatch will become even bigger if the temperature offset has a bigger difference between the two (e.g. if one of the sensors is inside an enclosure).

Is this unexpected behavior or should I assume that also the humidity sensor needs to be calibrated with a point of reference after the temperature compensation?

Another thing that bugs me is that if I don't use the bsec library (just the normal bme680 component) the humidity readings are completely different, even when trying to apply temperature compensation. Without bsec the only option is to use the generic sensor filter to apply a temperature offset, but this offset is only applied to temperature and humidity is not affected so the readings are way off.

Going further and to try to measure humidity adjusted by the temperature offset I found the following formula from Texas Instrument. But even with this, humidity readings can vary by up to 10% compared to the bsec library (given the same temperature offsets).
![image](https://github.com/esphome/issues/assets/1671631/f7f678fc-bb9f-4be9-85ff-7a7687b4503b)

My next step is to use bme680_bsec, bme680 and bme680+temperature compensation with a salt chamber to see who is closer to the expected 75% humidity. Until then if someone can give any additional hints it would be very helpful.

### Which version of ESPHome has the issue?

2023.7.0-dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

bme680

### Example YAML snippet

```yaml
bme680_bsec:
  - id: bsec0
    address: 0x77
    sample_rate: lp
    temperature_offset: 0.3
  - id: bsec1
    address: 0x76
    sample_rate: lp
    temperature_offset: 0.5

sensor:
  - platform: bme680_bsec
    bme680_bsec_id: bsec0
    temperature:
      name: "BSEC0 Temperature"
    humidity:
      name: "BSEC0 Humidity"

  - platform: bme680_bsec
    bme680_bsec_id: bsec1
    temperature:
      name: "BSEC1 Temperature"
    humidity:
      name: "BSEC1 Humidity"
```
