### ISSUE TITLE
Inkplate 10: Display does not want to show anything via ESPHome

### ISSUE THREAD

**Issue by xaxix** [esphome/issues#4755]
### The problem

After having so much fun with my Inkplate 6, it should now be the Inkplate 10. I created a new device in ESPHome, connected Inkplate 10 directly via USB and created the initial configuration. Inkplate 10 is online, but the display does not show anything. An example project in Arduino runs without problems.
Do I have an error somewhere? Is there another problem with the latest revision of Inkplate 10?
Soldered Inkplate 10: ESPRESSIF ESP32-WROVER-E
Home Assistent 2023.7.3
ESPHome 2023.7.0

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.3

### What platform are you using?

ESP32

### Board

Inkplate 10

### Component causing the issue

Display

### Example YAML snippet

```yaml
esphome:
  name: inkplate10
  friendly_name: inkplate10

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Inkplate10 Fallback Hotspot"
    password: "xxx"

captive_portal:

switch:
  - platform: restart
    name: "Inkplate Reboot"
    id: reboot

  - platform: gpio
    id: battery_read_mosfet
    pin:
      mcp23xxx: mcp23017_hub
      number: 9
      inverted: true

  - platform: template
    name: "Inkplate Greyscale mode"
    lambda: return id(inkplate_display).get_greyscale();
    turn_on_action:
      - lambda: id(inkplate_display).set_greyscale(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_greyscale(false);

  - platform: template
    name: "Inkplate Partial Updating"
    lambda: return id(inkplate_display).get_partial_updating();
    turn_on_action:
      - lambda: id(inkplate_display).set_partial_updating(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_partial_updating(false);

sensor:
  - platform: adc
    id: battery_voltage
    update_interval: never
    attenuation: 11db
    pin: 35
  - platform: template
    name: "Inkplate Battery Voltage"
    lambda: |-
      id(battery_read_mosfet).turn_on();
      delay(1);
      float adc = id(battery_voltage).sample();
      id(battery_read_mosfet).turn_off();
      return adc;
    filters:
      - multiply: 2

i2c:

mcp23017:
  - id: mcp23017_hub
    address: 0x20

font:
  - file: "calibri.ttf"
    id: my_font
    size: 80

display:
  - platform: inkplate6
    id: inkplate_display
    model: inkplate_6
    greyscale: false
    partial_updating: True
    update_interval: 60s
    full_update_every: 30

    ckv_pin: 32
    sph_pin: 33
    gmod_pin:
      mcp23xxx: mcp23017_hub
      number: 1
    gpio0_enable_pin:
      mcp23xxx: mcp23017_hub
      number: 8
    oe_pin:
      mcp23xxx: mcp23017_hub
      number: 0
    spv_pin:
      mcp23xxx: mcp23017_hub
      number: 2
    powerup_pin:
      mcp23xxx: mcp23017_hub
      number: 4
    wakeup_pin:
      mcp23xxx: mcp23017_hub
      number: 3
    vcom_pin:
      mcp23xxx: mcp23017_hub
      number: 5
      
    lambda: |-
      it.fill(COLOR_ON);
      it.line(400, 0, 400, 600, COLOR_OFF);
      it.printf(270, 345, id(my_font), COLOR_OFF, "Heute");
```

### Anything in the logs that might be useful for us?

22:27:51][C][logger:301]: Logger:
[22:27:51][C][logger:302]:   Level: DEBUG
[22:27:51][C][logger:303]:   Log Baud Rate: 115200
[22:27:51][C][logger:305]:   Hardware UART: UART0
[22:27:51][C][i2c.arduino:053]: I2C Bus:
[22:27:51][C][i2c.arduino:054]:   SDA Pin: GPIO21
[22:27:51][C][i2c.arduino:055]:   SCL Pin: GPIO22
[22:27:52][C][i2c.arduino:056]:   Frequency: 50000 Hz
[22:27:52][C][i2c.arduino:059]:   Recovery: bus successfully recovered
[22:27:52][I][i2c.arduino:069]: Results from i2c bus scan:
[22:27:52][I][i2c.arduino:075]: Found i2c device at address 0x20
[22:27:52][I][i2c.arduino:075]: Found i2c device at address 0x21
[22:27:52][I][i2c.arduino:075]: Found i2c device at address 0x51
[22:27:52][C][mcp23017:028]: MCP23017:
[22:27:52][C][switch.gpio:068]: GPIO Switch 'battery_read_mosfet'
[22:27:52][C][switch.gpio:091]:   Restore Mode: always OFF
[22:27:52][C][switch.gpio:031]:   Pin: 9 via MCP23XXX
[22:27:52][C][template.switch:068]: Template Switch 'Inkplate Greyscale mode'
[22:27:52][C][template.switch:091]:   Restore Mode: always OFF
[22:27:52][C][template.switch:057]:   Optimistic: NO
[22:27:52][C][template.switch:068]: Template Switch 'Inkplate Partial Updating'
[22:27:52][C][template.switch:091]:   Restore Mode: always OFF
[22:27:52][C][template.switch:057]:   Optimistic: NO
[22:27:52][C][template.sensor:022]: Template Sensor 'Inkplate Battery Voltage'
[22:27:52][C][template.sensor:022]:   State Class: ''
[22:27:52][C][template.sensor:022]:   Unit of Measurement: ''
[22:27:52][C][template.sensor:022]:   Accuracy Decimals: 1
[22:27:52][C][template.sensor:023]:   Update Interval: 60.0s
[22:27:52][C][restart:068]: Restart Switch 'Inkplate Reboot'
[22:27:52][C][restart:070]:   Icon: 'mdi:restart'
[22:27:52][C][restart:091]:   Restore Mode: always OFF
[22:27:52][C][adc:094]: ADC Sensor 'battery_voltage'
[22:27:52][C][adc:094]:   Device Class: 'voltage'
[22:27:52][C][adc:094]:   State Class: 'measurement'
[22:27:52][C][adc:094]:   Unit of Measurement: 'V'
[22:27:52][C][adc:094]:   Accuracy Decimals: 2
[22:27:52][C][adc:104]:   Pin: GPIO35
[22:27:52][C][adc:119]:  Attenuation: 11db
[22:27:52][C][adc:133]:   Update Interval: never
[22:27:52][C][psram:020]: PSRAM:
[22:27:52][C][psram:021]:   Available: YES
[22:27:52][C][psram:024]:   Size: 4095 KB
[22:27:52][C][inkplate:177]: Inkplate
[22:27:52][C][inkplate:177]:   Rotations: 0 °
[22:27:52][C][inkplate:177]:   Dimensions: 800px x 600px
[22:27:52][C][inkplate:178]:   Greyscale: NO
[22:27:52][C][inkplate:179]:   Partial Updating: NO
[22:27:52][C][inkplate:180]:   Full Update Every: 30
[22:27:52][C][inkplate:182]:   CKV Pin: GPIO32
[22:27:52][C][inkplate:183]:   CL Pin: GPIO0
[22:27:52][C][inkplate:184]:   GPIO0 Enable Pin: 8 via MCP23XXX
[22:27:52][C][inkplate:185]:   GMOD Pin: 1 via MCP23XXX
[22:27:52][C][inkplate:186]:   LE Pin: GPIO2
[22:27:52][C][inkplate:187]:   OE Pin: 0 via MCP23XXX
[22:27:52][C][inkplate:188]:   POWERUP Pin: 4 via MCP23XXX
[22:27:52][C][inkplate:189]:   SPH Pin: GPIO33
[22:27:52][C][inkplate:190]:   SPV Pin: 2 via MCP23XXX
[22:27:52][C][inkplate:191]:   VCOM Pin: 5 via MCP23XXX
[22:27:52][C][inkplate:192]:   WAKEUP Pin: 3 via MCP23XXX
[22:27:52][C][inkplate:194]:   Data 0 Pin: GPIO4
[22:27:52][C][inkplate:195]:   Data 1 Pin: GPIO5
[22:27:52][C][inkplate:196]:   Data 2 Pin: GPIO18
[22:27:52][C][inkplate:197]:   Data 3 Pin: GPIO19
[22:27:52][C][inkplate:198]:   Data 4 Pin: GPIO23
[22:27:52][C][inkplate:199]:   Data 5 Pin: GPIO25
[22:27:52][C][inkplate:200]:   Data 6 Pin: GPIO26
[22:27:52][C][inkplate:201]:   Data 7 Pin: GPIO27
[22:27:52][C][inkplate:203]:   Update Interval: 60.0s
[22:27:52][C][captive_portal:088]: Captive Portal:
[22:27:52][C][mdns:112]: mDNS:
[22:27:52][C][mdns:113]:   Hostname: inkplate10
[22:27:52][C][ota:093]: Over-The-Air Updates:
[22:27:52][C][ota:094]:   Address: inkplate10.local:3232
[22:27:52][C][ota:097]:   Using Password.
[22:27:52][C][api:138]: API Server:
[22:27:52][C][api:139]:   Address: inkplate10.local:6053
[22:27:52][C][api:141]:   Using noise encryption: YES
