### ISSUE TITLE
esphome 2023.7.1 broke i2s media players

### ISSUE THREAD

**Issue by elik745i** [esphome/issues#4757]
### The problem

After update to most recent esphome, media players stopped working, disappeared from entity lists in Home Assistant

### Which version of ESPHome has the issue?

2023.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.3

### What platform are you using?

ESP32

### Board

devboard

### Component causing the issue

recent update

### Example YAML snippet

```yaml
substitutions:
  device_name: wifi-stereo-01
  friendly_name: "wifi-stereo-01"
  device_description: "Fan with speed control"
  temperature_threshold_low: "25" # At what temperature, in celcius, should the fan turn on to its minimum speed
  temperature_threshold_high: "50" # At what temperature, in celcius, should the fan turn on to its maximum speed
  minimum_fan_speed: "15" # What is the minimum fan speed, as a percentage

esphome:
  friendly_name: WiFi_Stereo_01
  name: '${device_name}'
  comment: '${device_description}' 
  on_boot:
   - priority: 300.0 # after sensor setup, before WIFI initialization 
     then:
      - media_player.volume_set: !lambda "return 0.3;"
      #- lambda: |-
          #it.play_wav(file::jblst.pcm)

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret wifistereo01_enckey

ota:
  password: !secret wifistereo01_otapass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wifi-Stereo-01 Fallback Hotspot"
    password: !secret wifistereo01_fallbackpass

captive_portal:

status_led:
  pin:
    number: GPIO2
    inverted: true

i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO26 #not used, instead 13 and 14 used for Stereo left and right
    i2s_bclk_pin: GPIO27

# LR to be grounded

media_player:
  - platform: i2s_audio
    name: Stereo I2S Media Player
    dac_type: external
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO25
    mode: stereo

sensor:
  - platform: internal_temperature
    update_interval: 10s
    name: "${device_description} Temperature"
    id: temperature_sensor
    on_value:
      then:
        - script.execute: set_fan_state

# Example configuration entry with 2 sensors and filter
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

#Bluetooth proxy - not enough memory!
#esp32_ble_tracker:
  #scan_parameters:
    #interval: 1100ms
    #window: 1100ms
    #active: true

#bluetooth_proxy:
  #active: true

# Fan control

output:
  - platform: ledc
    pin: GPIO33
    id: pwm_output
    frequency: 1000Hz

fan:
  - platform: speed
    output: pwm_output
    name: "Stereo Fan"
    id: "the_fan"

# Sets the speed of the fan based on a linear calculation
# between the high and low temperature thresholds and
# the minimum specified fan speed
script:
  - id: set_fan_state
    then:
      - if:
          condition:
            lambda: |-
              return id(temperature_sensor).state < id(${temperature_threshold_low});
          then:
            - fan.turn_off: the_fan
          else:
            - fan.turn_on:
                id: the_fan
                speed: !lambda |-
                  if (id(temperature_sensor).state >= id(${temperature_threshold_high})) {
                    // Over upper threshold, fan speed at maximum
                    ESP_LOGD("Fan speed calc", "Temperature is above or equal to upper threshold so setting to max");
                    return 100;
                  }
                  else {
                    float calc_speed = ((100-id(${minimum_fan_speed})) / (id(${temperature_threshold_high})-id(${temperature_threshold_low})))*(id(temperature_sensor).state-id(${temperature_threshold_low}))+id(${minimum_fan_speed});
                    ESP_LOGD("Fan speed calc", "calculated speed = %f", calc_speed);
                    return calc_speed;
                  }

switch:
  - platform: restart
    name: "Stereo restart"
```

### Anything in the logs that might be useful for us?

```txt
no errors in logs
```
