### ISSUE TITLE
Component api took a long time for an operation (0.05 s)

### ISSUE THREAD

**Issue by fwmarcel** [esphome/issues#4765]
### The problem

My Status LED is always flashing fast. In the log i found following warnings.

[W][component:204]: Component api took a long time for an operation (0.05 s).
[W][component:205]: Components should block for at most 20-30ms.

### Which version of ESPHome has the issue?

2023.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.1

### What platform are you using?

ESP32

### Board

wemos_d1_mini32

### Component causing the issue

api

### Example YAML snippet

```yaml
substitutions:
  devicename: "desk"
  friendlyName: Desk

esphome:
  name: $devicename
  platformio_options: # Delete if you don't want to use NimBLE mode. More details: https://github.com/T-vK/ESP32-BLE-Keyboard#nimble-mode
    build_flags: -D USE_NIMBLE
  includes:
    - inc/keyboard.h
    - inc/keymap.h
  libraries:
    - ESP32 BLE Arduino@>=1.0.1
    - https://github.com/h2zero/NimBLE-Arduino/archive/refs/tags/1.3.2.zip
    - https://github.com/T-vK/ESP32-BLE-Keyboard/releases/download/0.3.1-beta/ESP32-BLE-Keyboard.zip

esp32:
  board: wemos_d1_mini32

logger:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

bluetooth_proxy:
  active: true

api:
  encryption:
    key: !secret api_password
  services:
      - service: send
        variables:
          message: string
          delay_ms: int
        then:
          lambda: |-
            (static_cast<Esp32BLEKeyboard *>(ble_keyboard))->release(message, delay_ms);
            
custom_component:
  - lambda: |-
      return {new Esp32BLEKeyboard(App.get_name(), "ESPHome")};
    components:
      - id: ble_keyboard
      
binary_sensor:
  - platform: custom
    lambda: |-
      auto kbd = static_cast<Esp32BLEKeyboard *>(ble_keyboard);
      return {kbd->connected_binarysensor};
    binary_sensors:
      - name: "$friendlyName Connected"
        device_class: "connectivity"

sensor:
  - platform: custom
    lambda: |-
      auto kbd = static_cast<Esp32BLEKeyboard *>(ble_keyboard);
      return {kbd->delay_sensor};
    sensors:
      - name: "$friendlyName Delay"
        unit_of_measurement: "ms"
        icon: "mdi:timer-outline"
        accuracy_decimals: 0

light:
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO16
    num_leds: 90
    type: GRB
    name: "$friendlyName Light"
    default_transition_length: 500ms
    restore_mode: RESTORE_AND_ON
    color_correct: [50%, 50%, 50%]
    effects:
      - random:
      - pulse:
      - flicker: 
      - addressable_rainbow:
      - addressable_scan:
          scan_width: 3
      - addressable_twinkle:
          twinkle_probability: 15%

status_led:
  pin:
    number: GPIO2
    inverted: true
```
