### ISSUE TITLE
Remote receiver module disables wifi power saving features

### ISSUE THREAD

**Issue by kkrell2016** [esphome/issues#4766]
### The problem

I have an ESP8266.

When I compile without remote receiver, the power saving for wifi works perfect. I checked it with a multimeter. It always shows changing currents.
As soon as I activate the remote receiver - even with a minimal configuration - the module always draws the same high current. 

It indicates to me, that for some reason all the saving functions are disabled.

In my case this is a problem because the power source is very limited. It is an intercom system and I would like to avoid having my own power connection.

### Which version of ESPHome has the issue?

ESPHome 2023.7.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
esphome:
  name: comelit
  friendly_name: comelit
  includes:
    - comelit.h

esp8266:
  board: esp01_1m    

# Enable logging
logger:
  #level: VERY_VERBOSE

ota:
  password: "ota_password"

#deep_sleep:
#  id: sleep1
#  run_duration: 10min
  #sleep_duration: 1min

#api:
  
wifi:
  ssid: "UPC6389776"
  password: "HNVCJCDM"
  power_save_mode: HIGH
  fast_connect: True
#  enable_on_boot: false
#  ap:
#    ssid: "Comelit Fallback"
#    password: "1234567890"

globals:
  - id: door
    type: int
    restore_value: no
    initial_value: '2'
  - id: code
    type: int
    restore_value: no
    initial_value: '0'
  - id: address
    type: int
    restore_value: no
    initial_value: '0'
  - id: description
    type: std::string
   
mqtt:
  broker: 192.168.0.80
  username: homeassist
  password: homeassist  
  keepalive: 30s

remote_transmitter:
  pin: GPIO13
  carrier_duty_percent: 100%

switch:
  - platform: template
    name: "Door"
    turn_on_action:
      - logger.log: "8min turn on"
      - remote_transmitter.transmit_raw:
          carrier_frequency: 25kHz
          code: !lambda return comelit_encode(id(door), 16);

remote_receiver:
  pin:
    number: GPIO4
    inverted: True
  dump: raw
  buffer_size: 3k
  on_raw:
    then:
      - lambda: |-
          id(code) = 0;
          id(address) = 0;
          ESP_LOGD("DEBUG", "RECEIVED RAW CODE OF LENGTH %u", size(x));
          char message[18];
          int bits = 0;
          if (size(x) == 38) {
            ESP_LOGD("DEBUG", "try decoding");
            for (auto it = x.begin() + 1; it != x.end() -1; it+=2) {
              if (-*it < 3500 && -*it > 1000)
              {
                message[bits] = 0;
                bits += 1;
              }
              else if (-*it < 6500 && -*it > 3500)
              {
                message[bits] = 1;
                bits += 1;
              }
              if (bits == 18) {
                int sum = 0;
                int checksum = 0;
                for (int i = 0; i < 14; i++)
                {
                  if (message[i] == 1) sum++;
                }
                checksum = (message[17] * 8) + (message[16] * 4) + (message[15] * 2) + message[14];
                if (checksum == sum) {
                  int msgCode[6];
                  int msgAddr[8];
                  for (int j = 0; j < 14; j++)
                  {
                    if (j < 6) msgCode[j] = message[j];
                    else msgAddr[j - 6] = message[j];
                  }
                  id(code) = (msgCode[5] * 32) + (msgCode[4] * 16) + (msgCode[3] * 8) + (msgCode[2] * 4) + (msgCode[1] * 2) + msgCode[0];
                  id(address) = (msgAddr[7] * 128) + (msgAddr[6] * 64) + (msgAddr[5] * 32) + (msgAddr[4] * 16) + (msgAddr[3] * 8) + (msgAddr[2] * 4) + (msgAddr[1] * 2) + msgAddr[0];
                  if (id(code) < 63)
                  {
                    ESP_LOGD("DEBUG", "RECEIVED COMMAND = %i", id(code));
                    ESP_LOGD("DEBUG", "RECEIVED address = %i", id(address));
                    ESP_LOGD("DEBUG", "CHECKSUM OK");
                    //auto capi = new esphome::api::CustomAPIDevice();
                    //capi->fire_homeassistant_event("esphome.comelit_receive", {{"address", std::to_string(id(address))}, {"comando", std::to_string(id(code))}});
                  } else {
                    id(code) = 0;
                    id(address) = 0;
                  }
                }
              }
            }
          }

# ------------------------------------------------------------------------------------------------------------
# DELETE THE FOLLOWING PART IF YOU DO NOT WANT TO GET A COMPLETE LOG OF ALL MESSAGES PASSING OVER THE BUS
# ------------------------------------------------------------------------------------------------------------

      - if:
          condition:
            lambda: 'return (id(code) > 0) && (id(address) > 0);'
          then:
            - lambda: |-
                std::string str = "";
                if (id(code) == 50){
                  str = "call within " + to_string(id(address));
                } else if (id(code) == 16) {
                  str = "external door opening from inside " + to_string(id(address));
                } else if (id(code) == 20) {
                  str = "indoor video startup " + to_string(id(address));
                } else if (id(code) == 17) {
                  str = "indoor audio startup " + to_string(id(address));
                } else if (id(code) == 29) {
                  if (id(address) == 1) {
                    str = "A staircase door opening";
                  } else if (id(address) == 2) {
                    str = "B staircase door opening";
                  } else if (id(address) == 4) {
                    str = "C staircase door opening";
                  }
                }
                else
                  str = "unknown command: addr:" + to_string(id(address)) + "code:" + to_string(id(code));
                id(description) = str;
                id(code) = 0;
                id(address) = 0;
            - if:
                condition:
                    lambda: 'return id(description) != "";'
                then:
                  - logger.log:
                      format: "Description code: %s"
                      args: ['id(description).c_str()']
#                  - homeassistant.service:
#                      service: logbook.log
#                      data:
#                        name: "Intercom:"
#                        entity_id: "binary_sensor.comelit_stato"
#                      data_template:
#                        message: "{{ com }}"
#                      variables:
#                        com: 'return id(description).c_str();'
                  - lambda: 'id(mysensor).publish_state(id(description));'

text_sensor:
  - platform: mqtt_subscribe
    name: "Doordata"
    id: mysensor
    topic: the/topic

    
#interval:
#  - interval: 8min
#    then:
#    - logger.log: "8min over"
#    - delay: 10s
#    - mqtt.publish:
#        topic: comelit/switch/door/bell_log
#        payload: 'hi auch'
#    - if:
#        condition: wifi.enabled
#        then:
#          - logger.log: "wifi enabled - switching off"
#          - delay: 10s
#          - wifi.disable:
#        else:
#          - logger.log: "wifi switching on"
#          - delay: 10s
#          - wifi.enable:
#    - deep_sleep.enter:
#        id: sleep1
```
