### ISSUE TITLE
wifi.disable power consumption

### ISSUE THREAD

**Issue by qwertz3** [esphome/issues#4768]
### The problem

The power consumption does not meet my expectations when I turn off wifi with "wifi.disable":

- after boot (enable_on_boot: False): ~22mA
- after wifi.enable (power_save_mode: NONE): ~74mA
- after wifi.enable (power_save_mode: HIGH): ~22mA..75mA (mostly below 50mA)
- after wifi.disable: remains ~74mA

My expectation would be that after switching off with "wifi.disable" power consumption would drop to 22mA again.

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
esphome:
  name: d1-mini

esp8266:
  board: d1_mini

logger:
  level: debug
  baud_rate: 0

#api:
#  reboot_timeout: 0s

ota:

wifi:
  enable_on_boot: False
  networks:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
  #power_save_mode: HIGH
  manual_ip:
    static_ip: 192.168.178.104
    gateway: 192.168.178.1
    subnet: 255.255.255.0
    dns1: 192.168.178.1
    dns2: 8.8.8.8

  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin: D1
    id: on_off
    on_click:
      - if:
          condition: wifi.enabled
          then:
            - wifi.disable:
          else:
            - wifi.enable:
```
