### ISSUE TITLE
PR #5011 [dsmr update to 0.7] seems to have broken previously working config.

### ISSUE THREAD

**Issue by EraYaN** [esphome/issues#4769]
### The problem

https://github.com/esphome/esphome/pull/5011 seems to have broken previously working DSMR (older protocol version) config

This device was previously on probably 2023.4.4

### Which version of ESPHome has the issue?

2023.7.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

Espressif DevKit

### Component causing the issue

dsmr

### Example YAML snippet

```yaml
esphome:
  name: dsmr
  friendly_name: Slimmer Meter DSMR

packages:
  wifi: !include common/wifi.yaml
  github: 
    url: https://github.com/EraYaN/esphome-configs
    ref: master
    files: 
      - base.yaml
    refresh: always
  encryption: !include common/encryption.yaml

esp32:
  board: esp32dev
  framework:
    type: arduino

uart:
  rx_pin:
    number: GPIO16
    inverted: true
  baud_rate: 9600
  data_bits: 7
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 1700
  # debug:
  #   direction: RX
  #   dummy_receiver: false
  #   after:
  #     delimiter: "\n"
  #   sequence:
  #     - lambda: UARTDebug::log_string(direction, bytes);

dsmr:
  crc_check: false
  max_telegram_length: 1700

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: dsmr_energy_delivered_tariff1
    energy_delivered_tariff2:
      name: dsmr_energy_delivered_tariff2
    power_delivered:
      name: dsmr_power_delivered

text_sensor:
  - platform: dsmr
    identification:
      name: "dsmr_identification"
    p1_version:
      name: "dsmr_p1_version"
    electricity_tariff:
      name: "dsmr_electricity_tariff"
    sub_equipment_id:
      name: "dsmr_sub_equipment_id"
    message_long:
      name: "dsmr_message_long"
    message_short:
      name: "dsmr_message_short"
```

### Anything in the logs that might be useful for us?

```txt
[22:41:28][I][app:102]: ESPHome version 2023.7.1 compiled on Aug  4 2023, 22:41:01
[22:41:29][W][component:204]: Component api took a long time for an operation (0.06 s).
[22:41:29][W][component:205]: Components should block for at most 20-30ms.
[22:41:30][W][component:204]: Component api took a long time for an operation (0.05 s).
[22:41:30][W][component:205]: Components should block for at most 20-30ms.
[22:41:31][W][dsmr:092]: Timeout while reading data for telegram
[22:41:41][W][dsmr:092]: Timeout while reading data for telegram
[22:41:51][W][dsmr:092]: Timeout while reading data for telegram
[endless repeats]
```

### Additional information

Landis Gyr E350 ZCF120ABdFs2
