### ISSUE TITLE
Sprinkler reset_resume() function not recognized

### ISSUE THREAD

**Issue by dgarciadonado** [esphome/issues#4774]
### The problem

It seems that the reset_resume() function cannot be used, it is flagged as Public but for some reason I cannot use. (I think I am calling it properly)
This function is very useful to completely clear the paused valves.

### Which version of ESPHome has the issue?

2023.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.2

### What platform are you using?

ESP32

### Board

Shelly 2.5 plus

### Component causing the issue

Sprinkler

### Example YAML snippet

```yaml
- platform: template
    name: ${upper_devicename} stop_all_valves
    id: stop_all_valves
    on_press:
      then:   
        - sprinkler.shutdown: main_sprinkler       
        - sprinkler.reset_resume: main_sprinkler
```

### Anything in the logs that might be useful for us?

```txt
Failed config

button.template: [source /config/esphome/sprinkler/general_modes.yaml:59]
  platform: template
  name: shelly_2_5_plus_riego stop_all_valves
  id: stop_all_valves
  on_press: 
    then: 
      - sprinkler.shutdown: main_sprinkler
      - 
        Unable to find action with the name 'sprinkler.reset_resume'.
        sprinkler.reset_resume: main_sprinkler
```
