### ISSUE TITLE
ESP32 keeps restarting - tuya component

### ISSUE THREAD

**Issue by autox86** [esphome/issues#4775]
### The problem

Hi all,

I am reading a OPR / PH / TEMP device from Tuya with a ESP32.
Unfortunately the ESP32 reboots every few minutes.

If tuya component is deactivated, it seem the ESP32 does not reboot.

Used hardware ESP32: https://rocketcontroller.com/product/astra-controller-4-relays-16a-8-gpio-input-dc-power-led-br4g8al/

Used Hardware Tuya:
https://de.aliexpress.com/item/1005004683327891.html?spm=a2g0o.order_list.order_list_main.11.544b5c5fZHaDpl&gatewayAdapt=glo2deu

Build in CB3S Chip is still in place, reading by connecting to TX/RX Pins.

My Tuya DP from iot.tuya.com

`
![image](https://github.com/esphome/issues/assets/25319095/0d142dcc-4ca1-484d-b5e7-9758c2e29216)
`

Can someone help here? 

### Which version of ESPHome has the issue?

2023.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.9

### What platform are you using?

ESP32

### Board

Espressif ESP32-D0WDQ6

### Component causing the issue

tuya

### Example YAML snippet

```yaml
esp32:
  #board: az-delivery-devkit-v4
  board: esp32dev
  framework:
    type: arduino


esphome:
  name: "${device_name}"

  on_boot:
        # buzzeron on startup
    then:
      - rtttl.play: 'A-Team:d=8,o=5,b=125:4d#6,a#,2d#6,16p,g#,4a#,4d#.,p,16g,16a#,d#6,a#,f6,2d#6,16p,c#.6,16c6,16a#,g#.,2a#'

# Enable logging
debug:
  update_interval: 2s

# Logger must be at least debug (default)

logger:
  level: VERY_VERBOSE
  hardware_uart: UART2
  baud_rate: 0


# Enable Home Assistant API
api:
  password: !secret api_pass2
  #no reboot in case HA is down - can require full reboot when HA is back
  reboot_timeout: 0s
ota:
  password: !secret ota_pass

wifi:
  #ssid: !secret wifi_ssid
  #password: !secret wifi_password
  ssid: "intial_ap"
  password: "asdfasdfasdfasdf"
  #power_save_mode: none
  # No reboot if Wifi is missing - can require full reboot when wifi is back
  reboot_timeout: 0s

# captive_portal:

# Enable Web server
web_server:
  port: 80

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

uart:
  id: uart_bus
  tx_pin: ${txd0}
  rx_pin: ${rxd0}
  baud_rate: 115200

tuya:
  ignore_mcu_update_on_datapoints: 
  - "143"
  - "142"
  - "141"
  - "138"
  - "137"
  - "136"
  - "128"
  - "127"
  - "126"
  - "123"
  - "122"
  - "121"
  - "118"
  - "117"
  - "116"
  - "113"
  - "112"
  - "111"
  
sensor:
  - platform: debug
    free:
      name: "Heap Free"
    #fragmentation:
     # name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

  # # Uptime sensor
  - platform: uptime
    name: "${friendly_name} Uptime ESP"
    id: wifi_uptime
    # unit_of_measurement: days
    update_interval: 5min
    entity_category: diagnostic
    # filters:
    #   - multiply: 0.000011574
  # WiFi Signal sensor
  - platform: wifi_signal
    name: "${friendly_name} WiFi ESP"
    id: wifi_sig
    update_interval: 5s
    icon: mdi:signal-variant

  # Reading tuya W2839 Pool ORP / PH / Temp
  - platform: "tuya"
    name: "${friendly_name} - Temperatur"
    id: tuya_temp
    sensor_datapoint: 8
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    #interval: 10s
    filters:
        - multiply: 0.1
  

  - platform: "tuya"
    name: "${friendly_name} - PH Wert"
    sensor_datapoint: 106
    state_class: "measurement"
    accuracy_decimals: 2
    filters:
        - multiply: 0.01

  - platform: "tuya"
    name: "${friendly_name} - ORP Wert"
    sensor_datapoint: 131
    unit_of_measurement: "mV"
    state_class: "measurement"


text_sensor:

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"



output:
  - platform: ledc
    pin: GPIO12
    id: rtttl_out

rtttl:
    output: rtttl_out
```

### Anything in the logs that might be useful for us?

```txt
Logs do not contain any info.
I have installed PIP version of ESPHome and logged to a file, but nothing...
```

### Additional information

The buzzer of the ESP32 seems on a strapping pin.
Not sure if this is really an issue:
