### ISSUE TITLE
Modbus controller "Number" and "select" components constantly refresh via MQTT

### ISSUE THREAD

**Issue by Alphaemef** [esphome/issues#4782]
### The problem

The" number" and "select" components publish their status as per the update_interval even when their values are entirely unchanged. If skip_updates are added, then they publish more rarely, but of course also with great delay. 

Any temporary or permanent fix ?

### Which version of ESPHome has the issue?

2023.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.2

### What platform are you using?

ESP32-IDF

### Board

az-delivery-devkit-v4

### Component causing the issue

number and select

### Example YAML snippet

```yaml
number:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: Maximum_battery_charge_current
    name: "Maximum battery charge current"
    address: 108
    unit_of_measurement: A
    value_type: U_WORD
#   skip_updates: ${skip_updates120}
```

### Anything in the logs that might be useful for us?

```txt
Message 7 received on slave0001/number/sun12k_slave_maximum_battery_charge_current/state at 13:25:
30.000000
QoS: 0 - Retain: false
Message 6 received on slave0001/number/sun12k_slave_maximum_battery_charge_current/state at 13:24:
30.000000
QoS: 0 - Retain: false
Message 5 received on slave0001/number/sun12k_slave_maximum_battery_charge_current/state at 13:24:
100.000000
QoS: 0 - Retain: false
Message 4 received on slave0001/number/sun12k_slave_maximum_battery_charge_current/state at 13:24:
100.000000
QoS: 0 - Retain: false
Message 3 received on slave0001/number/sun12k_slave_maximum_battery_charge_current/state at 13:24:
100.000000
QoS: 0 - Retain: false
Message 2 received on slave0001/number/sun12k_slave_maximum_battery_charge_current/state at 13:24:
100.000000
QoS: 0 - Retain: false
Message 1 received on slave0001/number/sun12k_slave_maximum_battery_charge_current/state at 13:24:
100.000000
QoS: 0 - Retain: false
Message 0 received on slave0001/number/sun12k_slave_maximum_battery_charge_current/state at 13:24:
100.000000
```
