### ISSUE TITLE
globals: type: int - intial_value is interpreted as a string

### ISSUE THREAD

**Issue by autox86** [esphome/issues#4783]
### The problem

Hi,

The "intial_value" seems to be written as a string while "int" is specified.

when defining globals like that:
```
globals:
  #if no flow sensors are attached, we need to assume if relays are on
  - id: assume_flow
    type: int
    restore_value: no
    initial_value: '0'
```

BR
Christian

### Which version of ESPHome has the issue?

2023.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.1

### What platform are you using?

ESP32-IDF

### Board

ESP32D

### Component causing the issue

globals

### Example YAML snippet

```yaml
when defining globals like that:

globals:
  #if no flow sensors are attached, we need to assume if relays are on
  - id: **assume_flow**
    type: int
    restore_value: no
    initial_value: '0'
```

Here is the piece reporting it as a string:

```
  #PH Injection - 
  - platform: template
    name: "${friendly_name} PH Dosierung"
    id: switch_ph
    turn_on_action:
      - lambda: |
            switch (assume_flow) {
            case 0: 
            id(relay_ph).turn_off();
            id(switch_ph).publish_state(id(relay_ph).state);
            case 1: 
              // No flow sensor, so checking SFA relay status is true
              if (id(relay_sfa).state) {
              id(relay_ph).turn_on();
              id(switch_ph).publish_sate(id(relay_ph).state);
              }
            }
```
```


### Anything in the logs that might be useful for us?

```txt
Error during compile:

/config/esphome/pooldosierung.yaml: In lambda function:
/config/esphome/pooldosierung.yaml:372:26: error: switch quantity not an integer
             switch (assume_flow) {
                          ^
```
```


### Additional information

_No response_
