### ISSUE TITLE
st7789v display cann't dispaly with platform: st7789v,but can display with platform: st7735

### ISSUE THREAD

**Issue by zwgmy** [esphome/issues#4786]
### The problem

st7789v display cann't dispaly with platform: st7789v,but can display with platform: st7735

### Which version of ESPHome has the issue?

 2023.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.1

### What platform are you using?

ESP32

### Board

esp32c3

### Component causing the issue

st7789v

### Example YAML snippet

```yaml
- platform: st7789v
    model: Custom
    height: 240
    width: 240
    offset_height: 0
    offset_width: 0
    rotation: 0
    eightbitcolor: true
    update_interval: 1s
    cs_pin: GPIO4
    dc_pin: GPIO5
    reset_pin: GPIO6
    backlight_pin: GPIO8
    lambda: |-
      it.print(0, 0, id(yahe16), "Hello World!");
```

### Anything in the logs that might be useful for us?

```txt
the display didn't work.
but use the platform: st7735 ,it can dispaly,but not very well.

  - platform: st7735
    model: "INITR_18BLACKTAB"
    reset_pin: GPIO6
    cs_pin: GPIO4
    dc_pin: GPIO5
    rotation: 0
    device_width: 240
    device_height: 240
    col_start: 80
    row_start: 0
    invert_colors: True
    eight_bit_color: true
    update_interval: 500ms
    lambda: |-
      it.image(0, 0, id(my_image));
      it.print(0, 200, id(yahe15), id(my_red), "Hello World!1234");
```

### Additional information

use arduino IDE include <Adafruit_ST7789.h>,the test program display well.
<img width="597" alt="屏幕截图 2023-08-13 210347" src="https://github.com/esphome/issues/assets/36669321/4012b3fb-478b-4bba-97c9-e535bb22c2cb">
