### ISSUE TITLE
Cover Button States

### ISSUE THREAD

**Issue by wernerhp** [esphome/issues#4788]
### The problem

Cover button states are not dependent on `CoverOperation`

### ■ button state
■ button is always enabled (when `stop_action` is set) regardless of the cover state and operation (even when `COVER_OPERATION_IDLE`)

Cover Open
![image](https://github.com/esphome/issues/assets/2578772/41434348-acc9-402b-a15f-988a09987d19) 
Cover Closed
![image](https://github.com/esphome/issues/assets/2578772/362ba4ae-7091-48f0-a2a6-9212aa59d264) 

■ button is expected to be
- **disabled** when `COVER_OPERATION_IDLE`
- **enabled** otherwise (`COVER_OPERATION_OPENING` or `COVER_OPERATION_CLOSING`)

### Stop direction change
The cover stop direction should be configurable.  
After stopping, covers may 
- ↓ ■ ↓ ■ ↓ ■ ↓ / continue in the same direction , or 
- ↓ ■ ↑ ■ ↓ ■ ↑ / continue in the opposite direction

### Instant operations 

The current behaviour has the opposite direction enabled when the cover is opening or closing.

↑ button is enabled during `COVER_OPERATION_CLOSING`
![image](https://github.com/esphome/issues/assets/2578772/d3734c34-7382-47e2-9615-b13600d692bf) 

↓ button is enabled during `COVER_OPERATION_OPENING`
![image](https://github.com/esphome/issues/assets/2578772/28604b04-e4f2-4ee8-aab6-251fb8c42712) 

Not all covers can instantly switch direction from opening to closing.  A window blind may be able to go from opening to closing without stopping, but a garage door motors may first needs to stop before operating in the opposite direction.

↑ and ↓ buttons should be configurable to enable/disable instant operations.

↑ and ↓ buttons are expected to be
- **enabled** when `COVER_OPERATION_IDLE`
- **disabled** otherwise (when `CoverOperation` is either `COVER_OPERATION_OPENING` or `COVER_OPERATION_CLOSING`)

### Which version of ESPHome has the issue?

2023.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.1

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
binary_sensor:
  - platform: gpio
    pin: 
      number: ${open_pin}
      inverted: true
      mode:
        input: true
        pullup: true
    id: cover_open
    internal: true
    name: "Cover Open"
    filters:
      delayed_on_off: 50ms
    on_state:
      lambda: |-
        if (id(cover_open).state && !id(cover_closed).state) {
          id(garage_door).position = cover::COVER_OPEN;
          id(garage_door).current_operation = CoverOperation::COVER_OPERATION_IDLE;
          id(garage_door).publish_state();
          id(status).publish_state("Open");
        } else if (!id(cover_open).state && !id(cover_closed).state) {
          if (id(garage_door).position == cover::COVER_OPEN) {
            id(garage_door).current_operation = CoverOperation::COVER_OPERATION_CLOSING;
            id(garage_door).publish_state();
            id(status).publish_state("Closing");
          } else if (id(garage_door).position == cover::COVER_CLOSED) {
            id(garage_door).current_operation = CoverOperation::COVER_OPERATION_OPENING;
            id(garage_door).publish_state();
            id(status).publish_state("Opening");
          }
        } else if (!id(cover_open).state && id(cover_closed).state) {
          id(garage_door).position = cover::COVER_CLOSED;
          id(garage_door).current_operation = CoverOperation::COVER_OPERATION_IDLE;
          id(garage_door).publish_state();
          id(status).publish_state("Closed");
        }

  - platform: gpio
    pin: 
      number: ${closed_pin}
      inverted: true
      mode:
        input: true
        pullup: true
    id: cover_closed
    internal: true
    name: "Cover Closed"
    filters:
      delayed_on_off: 50ms
    on_state:
      lambda: |-
        if (id(cover_open).state && !id(cover_closed).state) {
          id(garage_door).position = cover::COVER_OPEN;
          id(garage_door).current_operation = CoverOperation::COVER_OPERATION_IDLE;
          id(garage_door).publish_state();
          id(status).publish_state("Open");
        } else if (!id(cover_open).state && !id(cover_closed).state) {
          if (id(garage_door).position == cover::COVER_OPEN) {
            id(garage_door).current_operation = CoverOperation::COVER_OPERATION_CLOSING;
            id(garage_door).publish_state();
            id(status).publish_state("Closing");
          } else if (id(garage_door).position == cover::COVER_CLOSED) {
            id(garage_door).current_operation = CoverOperation::COVER_OPERATION_OPENING;
            id(garage_door).publish_state();
            id(status).publish_state("Opening");
          }
        } else if (!id(cover_open).state && id(cover_closed).state) {
          id(garage_door).position = cover::COVER_CLOSED;
          id(garage_door).current_operation = CoverOperation::COVER_OPERATION_IDLE;
          id(garage_door).publish_state();
          id(status).publish_state("Closed");
        }

output:
  - platform: gpio
    pin: 
      number: ${relay_1_pin}
      inverted: false
    id: relay_1

button:
  - platform: output
    output: relay_1
    id: button_1
    disabled_by_default: true
    duration: 500ms
    name: "Button 1"
    icon: "mdi:gesture-tap-button"

cover:
  - platform: template
    name: "Garage Door"
    device_class: garage
    id: garage_door
    open_action:
      - button.press: button_1
    close_action:
      - button.press: button_1
    stop_action:
      - button.press: button_1
    optimistic: false

text_sensor:
  - platform: template
    icon: mdi:information-outline
    id: status
    name: "Status"
    disabled_by_default: true
```
