### ISSUE TITLE
Webserver or GPIO-Switch: State of switch (on/off) is not updated when triggered by GPIO binary sensor

### ISSUE THREAD

**Issue by autox86** [esphome/issues#4797]
### The problem

Hi all,

I have a "momentary switch", let's call it button connected to a GPIO and GND --> binary sensor: GPIO
This button is toggle-ing the GPIO Switch with a relay attached.

In WebServer the following was observered:
Situation 1: Works like it should
1.) Device starting up
2.) Press the physical button
Result: the switch is moved from off to on

<img width="927" alt="image" src="https://github.com/esphome/issues/assets/25319095/6e55ee83-2ce6-4204-91e0-7ff6f93e3ed6">

Now, I am switching on/off in WebServer
![image](https://github.com/esphome/issues/assets/25319095/f82f4fe3-8144-4f4b-b26f-fe8bb9688844)

Second Try: Repeat Situation 1 and toggle the relay with the physical button attached to your GPIO
The result: The switch state is not updated

![image](https://github.com/esphome/issues/assets/25319095/a7977d21-00ae-4aa3-b938-7c9c4a050a07)
![image](https://github.com/esphome/issues/assets/25319095/373d4cfa-ea2e-4529-8a66-2c5697ba6d26)

If you now refresh the site (I am using chrome but edge has the same behavior), then the switch has the correct state and we are back to situation 1 as expected

### Which version of ESPHome has the issue?

2023.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.1

### What platform are you using?

ESP8266

### Board

ESP12e - 16xRelay Board with 2x Shift register

### Component causing the issue

webserver / switch gpio

### Example YAML snippet

```yaml
#Taster Wandlampe Wohnen
  - platform: gpio
    pin:
      number: ${sda}
      mode: INPUT_PULLUP
      inverted: True
    name: "Taster Wandlampe Wohnzimmer"
    on_press:
      - lambda: |-
          // store time of press and clear duration sensor
          id(global_press_time) = millis();
          id(sensor_press_duration).publish_state(0);
          id(relay_light_living).toggle();
      - script.execute: $sub_on_press
      - script.execute: script_30s_timer
    on_release:
      - lambda: |-
          // set duration sensor
          id(sensor_press_duration).publish_state(millis() - id(global_press_time) + id(number_debounce).state);
      - script.execute: $sub_on_release
      - script.stop: script_30s_timer
    filters:
      - delayed_on: !lambda return id(number_debounce).state;

  - platform: gpio
    name: "Wandlampe Wohnzimmer"
    id: relay_light_living
    restore_mode: always off
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 10
      number: 10
      inverted: false
    on_turn_on:
        - script.execute: $sub_on_turn_on
    on_turn_off:
        - script.execute: $sub_on_turn_off
```

### Anything in the logs that might be useful for us?

```txt
See screenshots, but no!
I think it's somehow a problem in visualizing it as after a browser refresh its working again
```

### Additional information

Love you guys
