### ISSUE TITLE
No Graph Line

### ISSUE THREAD

**Issue by 4noxx** [esphome/issues#4800]
### The problem

I added a graph for my epaper Display, but i see only the border.... no line

### Which version of ESPHome has the issue?

2023.8.0b3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.3

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
sensor:
  - platform: homeassistant
    id: temp_aussen
    entity_id: sensor.foxess_ambient_temperature

graph:
  - id: temp_aussen_graph
    sensor: temp_aussen
    duration: 1h
    width: 150
    height: 50

display:
  - platform: waveshare_epaper
    id: epaperdisplay
    cs_pin: 15
    dc_pin: 12
    update_interval: 120s
    busy_pin: 16
    reset_pin: 4
    model: 4.20in
    lambda: |-
      it.graph(200,10, id(temp_aussen_graph));
```
