### ISSUE TITLE
BLE Sensor notify config flag not working

### ISSUE THREAD

**Issue by clydebarrow** [esphome/issues#4802]
### The problem

The BLE Client Sensor component has a config option `notify` which should turn on notifications for the specified characteristic. This is not working (and thus the `on_notify` automation is never triggered) due to two typos in `ble_client_base.cpp`.

I have a fix for this and will include it in an upcoming PR.

### Which version of ESPHome has the issue?

2023.9.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

BLE Client Sensor

### Example YAML snippet

```yaml
sensor:
  - platform: ble_client
    type: characteristic
    ble_client_id: door
    name: Temperature
    service_uuid: '181A'
    characteristic_uuid: '2A6E'
    unit_of_measurement: '<C2><BA>C'
    accuracy_decimals: 1
    update_interval: 10s
    notify: true
    on_notify:
      then:
        - logger.log: "Notify event"
    lambda: |-
      return (float)(x[0] + (x[1] << 8)) / 100.0f;
```
