### ISSUE TITLE
SML checksum error after update to 2023.8.0

### ISSUE THREAD

**Issue by mvdberge** [esphome/issues#4805]
### The problem

After the update of ESPhome to 2023.8.0 I only receive the following error:

`Checksum error in received SML data`

When using manually installed ESPhome (via pip) and downgrading to the last version, everything is fine. So it must be a problem of version 2023.8.0.

### Which version of ESPHome has the issue?

2023.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.2

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

sml

### Example YAML snippet

```yaml
uart:
  id: uart_bus
  tx_pin: RX
  rx_pin: TX
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 512

sml:
  id: mysml
  uart_id: uart_bus

sensor:
  - platform: sml
    name: "Gesamt Energiebezug"
    id: gesamt_energiebezug
    sml_id: mysml
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
      - throttle: 60s
```

**Comment by Skeletitor** [comment]
Same Problem her.

Quick fix: use external sourcen from 'alengwenus'. Thankn you bdu

--- just add to you jaml START ---
external_components:
  - source:
      type: git
      url: https://github.com/alengwenus/esphome_components
    components: [ sml ]
--- just add to you jaml END ---

**Comment by Skeletitor** [comment]
https://github.com/esphome/esphome/pull/5250

I'm pretty sure this causes the issue

**Comment by Mat931** [comment]
Can you add this to your config and see if it fixes the error?

```yaml
external_components:
  - source: github://pr#5271
    components: [sml]
    refresh: always
```
