### ISSUE TITLE
After ESPHome 2023.8.0 update ESP-WROOM-32 CP2102 development board stuck in boot loop, draws more current

### ISSUE THREAD

**Issue by bmarr** [esphome/issues#4808]
### The problem

After updating the ESP-WROOM-32 CP2102 development board with ESPHome 2023.8.0 the module gets into a boot loop.

The module is used as a WiFi - Bluetooth Proxy only, and is located in a router closet less than 1 meter from the WiFi router, and is powered by a 0.5 meter USB type A to USB micro cable attached to a PUMA branded PMFS121 5V@1A USB type A wall adapter manufactured on 2012-08.

When I attach the module to the USB wall adapter that it has been using successfully for over a year, the module gets stuck in a boot loop. With these modules, a boot loop usually means insufficient current at the USB port.

When I attach the module to my laptop USB port, it boots normally after the update. I have tried other wall adapter USB power supplies that have higher than 5V@1A rating and the module boots normally.

The solution is to use a new power supply for this board.

However, why the significantly increased power draw during boot? The YAML file was not altered before the update.

### Which version of ESPHome has the issue?

2023.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.08.1

### What platform are you using?

ESP32-IDF

### Board

Generic ESP-WROOM-32 C2102 development module

### Component causing the issue

Power supply

### Example YAML snippet

```yaml
substitutions:
  name: esp32-ble-proxy-rocl
  wifi_ap_password: "aBcD1e2f3g4h"

esphome:
  name: ${name}
  name_add_mac_suffix: true
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Esphome-Ble-Proxy-RoCl"
    password: ${wifi_ap_password}

api:
  encryption:
    key: "REDACTED"
logger:
ota:
  password: "32characterhexstring"

improv_serial:

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/esp32-generic.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic
```

### Anything in the logs that might be useful for us?

```txt
I was unable to monitor CP2102 serial port logs when testing, however blue activity LED flashes the same pattern while in the reboot loop.
```

### Additional information

Successful boot log output from ESPHome add-on wireless log:

INFO ESPHome 2023.8.0
INFO Reading configuration /config/esphome/esp32-ble-proxy-rocl.yaml...
INFO Starting log output from esp32-ble-proxy-rocl.local using esphome API
INFO Successfully connected to esp32-ble-proxy-rocl.local
[10:20:44][I][app:102]: ESPHome version 2023.8.0 compiled on Aug 17 2023, 09:38:33
[10:20:44][I][app:104]: Project esphome.bluetooth-proxy version 1.0
[10:20:44][C][wifi:543]: WiFi:
[10:20:44][C][wifi:379]:   Local MAC: 44:17:93:7C:54:44
[10:20:44][C][wifi:380]:   SSID: [redacted]
[10:20:44][C][wifi:381]:   IP Address: 192.168.0.90
[10:20:44][C][wifi:383]:   BSSID: [redacted]
[10:20:44][C][wifi:384]:   Hostname: 'esp32-ble-proxy-rocl-7c5444'
[10:20:44][C][wifi:386]:   Signal strength: -69 dB ▂▄▆█
[10:20:44][C][wifi:390]:   Channel: 9
[10:20:44][C][wifi:391]:   Subnet: 255.255.255.0
[10:20:44][C][wifi:392]:   Gateway: 192.168.0.1
[10:20:44][C][wifi:393]:   DNS1: 192.168.0.1
[10:20:44][C][wifi:394]:   DNS2: 0.0.0.0
[10:20:44][C][logger:301]: Logger:
[10:20:44][C][logger:302]:   Level: DEBUG
[10:20:44][C][logger:303]:   Log Baud Rate: 115200
[10:20:44][C][safe_mode.button:022]: Safe Mode Button 'Safe Mode Boot'
[10:20:44][C][safe_mode.button:022]:   Icon: 'mdi:restart-alert'
[10:20:44][C][esp32_ble:238]: ESP32 BLE:
[10:20:44][C][esp32_ble:240]:   MAC address: 44:17:93:7C:54:46
[10:20:44][C][esp32_ble:241]:   IO Capability: none
[10:20:44][C][esp32_ble_tracker:617]: BLE Tracker:
[10:20:44][C][esp32_ble_tracker:618]:   Scan Duration: 300 s
[10:20:44][C][esp32_ble_tracker:619]:   Scan Interval: 1100.0 ms
[10:20:44][C][esp32_ble_tracker:620]:   Scan Window: 1100.0 ms
[10:20:44][C][esp32_ble_tracker:621]:   Scan Type: ACTIVE
[10:20:44][C][esp32_ble_tracker:622]:   Continuous Scanning: True
[10:20:44][C][mdns:112]: mDNS:
[10:20:44][C][mdns:113]:   Hostname: esp32-ble-proxy-rocl-7c5444
[10:20:44][C][ota:093]: Over-The-Air Updates:
[10:20:44][C][ota:094]:   Address: esp32-ble-proxy-rocl.local:3232
[10:20:44][C][ota:097]:   Using Password.
[10:20:44][C][api:138]: API Server:
[10:20:44][C][api:139]:   Address: esp32-ble-proxy-rocl.local:6053
[10:20:44][C][api:141]:   Using noise encryption: YES
[10:20:44][C][improv_serial:032]: Improv Serial:
