### ISSUE TITLE
LD2410. Error on Number config

### ISSUE THREAD

**Issue by shammysha** [esphome/issues#4810]
### The problem

When I've trying to put new ld2410 configuration schema in config, using examples from docs, I have an error

**Some but not all values in the same group of inclusion 'timeout'.**

```
number:
  - platform: ld2410
    ld2410_id: bathroom_emi
    timeout:
      name: ${devicename} Bathroom timeout
>>>
some but not all values in the same group of inclusion 'timeout'.
>>>
    max_move_distance_gate:
      name: ${devicename} Bathroom max move distance
.....
```

In https://github.com/esphome/esphome/blob/8bf112669f6e2f681aba0d00704ff682a8fc8d8e/esphome/components/ld2410/number/__init__.py#L31 I see definition of schema, as

```
CONFIG_SCHEMA = cv.Schema(
    {
        cv.GenerateID(CONF_LD2410_ID): cv.use_id(LD2410Component),
        cv.Inclusive(CONF_TIMEOUT, TIMEOUT_GROUP): number.number_schema(
            MaxDistanceTimeoutNumber,
            unit_of_measurement=UNIT_SECOND,
            entity_category=ENTITY_CATEGORY_CONFIG,
            icon=ICON_TIMELAPSE,
        ),
        cv.Inclusive(CONF_MAX_MOVE_DISTANCE_GATE, TIMEOUT_GROUP): number.number_schema(
            MaxDistanceTimeoutNumber,
            device_class=DEVICE_CLASS_DISTANCE,
            entity_category=ENTITY_CATEGORY_CONFIG,
            icon=ICON_MOTION_SENSOR,
        ),
        cv.Inclusive(CONF_MAX_STILL_DISTANCE_GATE, TIMEOUT_GROUP): number.number_schema(
            MaxDistanceTimeoutNumber,
            device_class=DEVICE_CLASS_DISTANCE,
            entity_category=ENTITY_CATEGORY_CONFIG,
            icon=ICON_MOTION_SENSOR,
        ),
        cv.Optional(CONF_LIGHT_THRESHOLD): number.number_schema(
            LightThresholdNumber,
            device_class=DEVICE_CLASS_ILLUMINANCE,
            entity_category=ENTITY_CATEGORY_CONFIG,
            icon=ICON_LIGHTBULB,
        ),
    }
)
```

Is this correct to adding parameters CONF_MAX_MOVE_DISTANCE_GATE and CONF_MAX_STILL_DISTANCE_GATE to TIMEOUT_GROUP?

### Which version of ESPHome has the issue?

2023.8.1

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Component causing the issue

ld2410

### Example YAML snippet

```yaml
number:
  - platform: ld2410
    ld2410_id: bathroom_emi
    timeout:
      name: ${devicename} Bathroom timeout
    max_move_distance_gate:
      name: ${devicename} Bathroom max move distance
    max_still_distance: 
      name: ${devicename} Bathroom max still distance      
    light_threshold:      
      name: ${devicename} Bathroom light treshold      

    g0:
      move_threshold: 
        name: ${devicename} Bathroom g0 move threshold
      still_threshold:
        name: ${devicename} Bathroom g0 still threshold
    g1:
      move_threshold: 
        name: ${devicename} Bathroom g1 move threshold
      still_threshold:
        name: ${devicename} Bathroom g1 still threshold    
    g2:
      move_threshold: 
        name: ${devicename} Bathroom g2 move threshold
      still_threshold:
        name: ${devicename} Bathroom g2 still threshold            
    g3:
      move_threshold: 
        name: ${devicename} Bathroom g3 move threshold
      still_threshold:
        name: ${devicename} Bathroom g3 still threshold     
    g4:
      move_threshold: 
        name: ${devicename} Bathroom g4 move threshold
      still_threshold:
        name: ${devicename} Bathroom g4 still threshold           
    g5:
      move_threshold: 
        name: ${devicename} Bathroom g5 move threshold
      still_threshold:
        name: ${devicename} Bathroom g5 still threshold       
    g6:
      move_threshold: 
        name: ${devicename} Bathroom g6 move threshold
      still_threshold:
        name: ${devicename} Bathroom g6 still threshold         
    g7:
      move_threshold: 
        name: ${devicename} Bathroom g7 move threshold
      still_threshold:
        name: ${devicename} Bathroom g7 still threshold        
    g8:
      move_threshold: 
        name: ${devicename} Bathroom g8 move threshold
      still_threshold:
        name: ${devicename} Bathroom g8 still threshold
```
