### ISSUE TITLE
Use of "clock" as an id results in compilation errors

### ISSUE THREAD

**Issue by clydebarrow** [esphome/issues#4813]
### The problem

If an id in a yaml file has the name "clock" then the compilation fails. It should fail on config validation with the message
`  ID 'clock' is reserved internally and cannot be used.`

### Which version of ESPHome has the issue?

2023.9.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

Any

### Example YAML snippet

```yaml
switch:
  - platform: template
    id: clock
    name: "Output switch"
    optimistic: true
```
