### ISSUE TITLE
HOSTNAME does not display in DHCP leases. network scans etc.

### ISSUE THREAD

**Issue by deanfourie1** [esphome/issues#4816]
### The problem

The hostname of my nodes just will not display on any DHCP lease information or any network scans.

It just displays the vendor, "espressif inc".

Is there a way to display the device "name" or "friendly-name" as the hostname. 

When I open the logs, it displays the correct hostname, however this does not display.

It does however work find on a ESP01_1m board but does not seem to work on any of my ESP32dev boards.

### Which version of ESPHome has the issue?

2023.8.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.3

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

networking/mdns

### Example YAML snippet

```yaml
esphome:
  name: pool-outputs
  friendly_name: "pool-outputs"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

# Example configuration entry for ESP32
i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a


# Example configuration entry
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

  # Optional manual IP
  manual_ip:
    static_ip: *********
    gateway: *********
    subnet: *********


# Example configuration entry
pcf8574:
  - id: 'pcf8574_hub_out_1'  # for output channel 1-8
    address: 0x24

  - id: 'pcf8574_hub_in_1'  # for input channel 1-8
    address: 0x22

# Individual outputs
switch:
  - platform: gpio
    name: "a8-light1"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "a8-light2"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 1
      mode: OUTPUT
      inverted: true
     
  - platform: gpio
    name: "a8-light3"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 2
      mode: OUTPUT
      inverted: true
     
  - platform: gpio
    name: "PumpAlarm"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 3
      mode: OUTPUT
      inverted: true
     
  - platform: gpio
    name: "TopStairLights"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 4
      mode: OUTPUT
      inverted: true
     
  - platform: gpio
    name: "BottomWallLights"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "TopWallLights"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 6
      mode: OUTPUT
      inverted: true
     
  - platform: gpio
    name: "PoolPump"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 7
      mode: OUTPUT
      inverted: true
     
binary_sensor:
  - platform: gpio
    name: "a8-input1"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 0
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "a8-input2"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 1
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "a8-input3"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 2
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "a8-input4"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 3
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "a8-input5"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 4
      mode: INPUT
      inverted: true

  - platform: gpio
    device_class: door
    name: "PoolCabinetTamper"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 5
      mode: INPUT

  - platform: gpio
    device_class: door
    name: "PoolCover"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 6
      mode: INPUT

  - platform: gpio
    name: "PumpStatus"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 7
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "a8-s3"
    pin:
      number: 32
      inverted: true

  - platform: gpio
    name: "a8-s4"
    pin:
      number: 33
      inverted: true
     
dallas:
  - pin: 14

sensor:
  - platform: dallas
    address: 0x0c0121128d004c28
    name: "PoolTemperature"

  - platform: aht10
    temperature:
      name: "PoolCabinetTemperature"
    humidity:
      name: "PoolCabinetHumidity"
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

This only appears to be an issue with ethernet devices and not wifi from my experience.
