### ISSUE TITLE
some issues with using simultaneous input and output GPIO (but mostly working!)

### ISSUE THREAD

**Issue by agoode** [esphome/issues#4825]
### The problem

I have a lighted button (standard 2-wire LED doorbell) that I have figured out how to power and detect the button press on using the YAML below. It is a little quirky and I wanted to make sure this kind of configuration stays supportable in the future without much hassle.

In this case, I define the GPIO both as an output and an input with pullup. This puts full voltage out of the pin (to power the light) but still detects when the button is pressed as a connection to ground. Without the separate output configuration, the light is very dimly lit. I tried some variations on the syntax but only this exact syntax works. So a few issues:

1. If I create the gpio output pin and set it to high (`inverted: true`), flash the board, then remove it this configuration, the output continues to stay high until I power cycle. This suggests some state that isn't getting reset on the board that might be an issue.
2. The syntax is a little weird, and I would like to continue to be able to exercise this functionality of the esp32 and not worry about it breaking in esphome. Is there anything I could do to help ensure this? I am happy to help if I can.

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

esp32dev

### Component causing the issue

gpio

### Example YAML snippet

```yaml
output:
  - platform: gpio
    pin: GPIO4
    inverted: true
    id: gpio_4

binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        output: true
        pullup: true
    filters:
      - delayed_on_off: 25ms
```
