### ISSUE TITLE
No hardware SPI support for ESP-IDF

### ISSUE THREAD

**Issue by clydebarrow** [esphome/issues#4827]
### The problem

The SPI component supports hardware SPI for Arduino, but not ESP-IDF. The software implementation that it falls back to has an apparent maximum speed of around 600kHz. The Arduino hw implementation has no problem with high speeds as expected.

1. The fact that a software implementation is always used for ESP-IDF should be documented;
2. The limitations of the sw implementation should be documented;
3. A warning should be issued if a clock rate greater than available is requested;
4. Hardware support on ESP-IDF should be implemented.

I am exploring option 4.

Example spi implementation with 4MHz clock requested:

```
esp32:
  board: esp32dev
  framework:
    type: esp-idf

spi:
  mosi_pin:
    number: GPIO26
  clk_pin:
    number: GPIO25

light:
  - platform: spi_rgb_led
    num_leds: 1
    color_correct: [80%, 60%, 100%]
    id: rgb_led
    name: "RGB LED"
    data_rate: 4MHz
```

If built for Arduino the results are as expected (clean 4MHz clock). On ESP-IDF the clock looks like this - a maximum speed of 609kHz, but with some clock cycles stretched (probably due to interrupts delaying the sw spi code.)

![spi_clock](https://github.com/esphome/issues/assets/2366188/3460b347-b6b1-4472-9eec-1e07a8ec94c3)

### Which version of ESPHome has the issue?

2023.9.0-dev

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

tinypico

### Component causing the issue

spi
