### ISSUE TITLE
WDT resets when using Waveshare e-paper

### ISSUE THREAD

**Issue by frog32** [esphome/issues#483]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio
**ESP (ESP32/ESP8266, Board/Sonoff):**

d1 mini and node MCU show the same behavior

**Affected component:**

waveshare e-paper

**Description of problem:**
I see WDT resets at the same interval that I use as update_interval which manifests in loosing connectivity to home assistant and the display cycling through inverted colors, black, white, black.

**Problem-relevant YAML-configuration entries:**
```yaml
font:
  - file: 'ComicNeue-Regular.ttf'
    id: comic
    size: 30

spi:
  clk_pin: D0
  mosi_pin: D1

display:
  - platform: waveshare_epaper
    cs_pin: D2
    dc_pin: D3
    busy_pin: D4
    reset_pin: D5
    model: 4.20in
    update_interval: 30s
    #full_update_every: 30
    lambda: |-
      it.printf(200, 0, id(comic), TextAlign::TOP_CENTER, "Test");
```

**Logs (if applicable):**

Very verbose and long https://pastebin.com/Lc2QJcVY

**Additional information and things you've tried:**

Changing the update interval changes the frequency at which the ESP restarts
