### ISSUE TITLE
ESP32C3 no IPv6 using Arduino Framework

### ISSUE THREAD

**Issue by wtremmel** [esphome/issues#4831]
### The problem

ESP32 does not get an IPv6 address assigned, either log output is missing or address is really not assigned

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.3

### What platform are you using?

ESP32

### Board

Wemos C3 Mini

### Component causing the issue

network

### Example YAML snippet

```yaml
esphome:
  name: arbeitszimmer-sensor
  platformio_options: 
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

esp32:
  board: lolin_c3_mini
  framework:
    type: arduino

network:
  enable_ipv6: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5

logger:
  level: VERY_VERBOSE

debug: 
  update_interval: 120s
```

### Anything in the logs that might be useful for us?

```txt
I will upload the complete log file
```
