### ISSUE TITLE
IPv6 cannot be turned off using ethernet

### ISSUE THREAD

**Issue by optimusprimespace** [esphome/issues#4834]
### The problem

When i set the ipv6 to false i still get an ipv6 address that i can ping with another computer. Is this a bug or a feature? :) Also i'm using ethernet not wifi, as written in the "Example YAML snippet".

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.4

### What platform are you using?

ESP32

### Board

olimex gateway

### Component causing the issue

ipv6

### Example YAML snippet

```yaml
network:
  enable_ipv6: false
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
```
