### ISSUE TITLE
Can't compile bme680_bsec sensor

### ISSUE THREAD

**Issue by UdoD5** [esphome/issues#4835]
According to https://esphome.io/components/sensor/bme680_bsec.html
the sensor should be available in the core. 
Unfortunately I can't compile with the given documentation.

### The problem

INFO ESPHome 2023.8.2
INFO Reading configuration /config/esphome/air-quality-01.yaml...
Failed config

sensor.bme680_bsec: [source /config/esphome/air-quality-01.yaml:38]
  
  Component sensor.bme680_bsec requires component bme680_bsec.
  platform: bme680_bsec
  temperature: 
    name: Temperatur
    id: bme680_temperature
  pressure: 
    name: Luftdruck
    id: bme680_pressure
  humidity: 
    name: Luftfeuchtigkeit
    id: bm680_humidity
  iaq: 
    name: Luftqualität
    id: iaq
  breath_voc_equivalent: 
    name: Atem VOC Equivalent
    id: bme680_breath_voc
  address: 118
  update_interval: 60s

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

 Home Assistant 2023.8.4 Supervisor 2023.08.1 Operating System 10.5 Frontend 20230802.1 

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

Sensor

### Example YAML snippet

```yaml
esphome:
  name: air-quality-01
  friendly_name: air-quality-01

esp8266:
  board: d1_mini_lite

# Enable logging
logger:
  level: ERROR
# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxx"

ota:

web_server:
  port: 80
  version: 1
  include_internal: true

wifi:
  ssid: "XXXX"
  password: "XXXX"
  fast_connect: true

i2c:
  sda: D2   #Wemos D1 Mini , GPIO05
  scl: D1   #Wemos D1 Mini , GPIO04
  scan: True
uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600
  
sensor:
  - platform: bme680_bsec
    temperature:
      name: "Temperatur"
      id: bme680_temperature
    pressure:
      name: "Luftdruck"
      id: bme680_pressure
    humidity:
      name: "Luftfeuchtigkeit"
      id: bm680_humidity
    iaq:
      name: "Luftqualität"
      id: iaq
    breath_voc_equivalent
      name: "Atem VOC Equivalent"
      id: bme680_breath_voc
    address: 0x76  #or 0x77
    update_interval: 60s
	
  # Absolute Luftfeuchtigkeit
  # calc based on temp and humid sensor via internal ID
  # humidity: bme680
  # temperature: bme680
  - platform: template
    name: "Absolute Luftfeuchte"
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme680_temperature).state) /
        (id(bme280_temperature).state + 243.5)) * id(bme680_humidity).state * mw) /
        ((273.15 + id(bme680_temperature).state) * r); // in grams/m^3
    accuracy_decimals: 2
    update_interval: 60s
    icon: 'mdi:water-percent-alert'
    unit_of_measurement: 'g/m³'
  # Luftdruck Seelevel
  # calc based on temp and pressure sensor via internal ID
  # pressure: bme280
  # temperature: bme280
  - platform: template
    name: "Luftdruck Seelevel"
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      const float STANDARD_ALTITUDE =  ((id(bme680_temperature).state + 273.15) / 0.0065) *
      (powf((STANDARD_SEA_LEVEL_PRESSURE / id(bme680_pressure).state), 0.190234) - 1); // in meter
      return id(bme680_pressure).state / powf(1 - ((0.0065 * STANDARD_ALTITUDE) /
      (id(bme680_temperature).state + (0.0065 * STANDARD_ALTITUDE) + 273.15)), 5.257); // in hPa
    update_interval: 60s
    unit_of_measurement: 'hPa'
    icon: 'mdi:weather-fog'
  # Taupunkt
  # calc based on temp and humidity sensor via internal ID
  # humidity: bme280
  # temperature: bme280
  - platform: template
    name: "Taupunkt"
    lambda: |-
      return (243.5*(log(id(bme680_humidity).state/100)+((17.67*id(bme680_temperature).state)/
      (243.5+id(bme680_temperature).state)))/(17.67-log(id(bme680_humidity).state/100)-
      ((17.67*id(bme680_temperature).state)/(243.5+id(bme680_temperature).state))));
    unit_of_measurement: °C
    update_interval: 60s
    icon: 'mdi:weather-fog'
  - platform: mhz19
    co2:
      name: "CO2 Gehalt"
      id: mhz19_co2
    temperature:
      name: "Temperature CO2 Sensor"
      id: mhz19_temperature
    update_interval: 60s
    automatic_baseline_calibration: false
    id: mhz19_id
```

**Comment by fyague** [comment]
I think you have missed the bme680_bsec component.


```
bme680_bsec:    #Add this

sensor:
  - platform: bme680_bsec
    temperature:
      name: "Temperatur"
      id: bme680_temperature
    pressure:
      name: "Luftdruck"
      id: bme680_pressure
...
```
