### ISSUE TITLE
No documentation for `interval` component

### ISSUE THREAD

**Issue by clydebarrow** [esphome/issues#4836]
### The problem

There is an `interval` component mentioned a few times in examples, but no documentation on it that I can find.

### Which version of ESPHome has the issue?

2023.9.0-dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

interval

### Example YAML snippet

```yaml
interval :
  - interval: 2min
    then: ...
```
