### ISSUE TITLE
UART Switch not sending CR / LF in string form

### ISSUE THREAD

**Issue by CountParadox** [esphome/issues#484]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io running on an Intel NUC using official image
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 - Wemos D1 Mini
**Affected component:**

https://esphome.io/components/switch/uart.html

**Description of problem:**
When sending a data string, including \r\n for carriage return and line feed, the characters "\r\n" are sent, rather than sending the actual CR and LF

For example, sending 

```
  - platform: uart
    name: "HDMI 1"
    data: 'INSP  10\r\n'
```

Results in the ESP sending
```
INSP  10\r\n
```
on a single line. 

As a result the UART command is not executed.

manually sending the hex as per the docs does seem to work:

```
  - platform: uart
    name: "HDMI 1"
    data: [0x49, 0x4E, 0x50, 0x53, 0x20, 0x20, 0x31, 0x30, 0x0D, 0x0A]
```

And correctly sends the CR and LF.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: sharptv
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'x'
  password: 'x'

api:

# Enable logging
logger:

ota:

mqtt:
  broker: 172.16.0.60
  username: rs232
  password: x

uart:
  baud_rate: 38400
  tx_pin: D4

switch:
  - platform: uart
    name: "Power On"
    data: [0x50, 0x4F, 0x57, 0x52, 0x20, 0x20, 0x20, 0x31, 0x0D, 0x0A]
    on_turn_on:
      then:
      - mqtt.publish:
          topic: esphome/rs232/sharp/state
          payload: "ON"

  - platform: uart
    name: "Power Off"
    data: [0x50, 0x4F, 0x57, 0x52, 0x20, 0x20, 0x20, 0x30, 0x0D, 0x0A]
    on_turn_on:
      then:
      - mqtt.publish:
          topic: esphome/rs232/sharp/state
          payload: "OFF"

  - platform: uart
    name: "HDMI 1"
    data: [0x49, 0x4E, 0x50, 0x53, 0x20, 0x20, 0x31, 0x30, 0x0D, 0x0A]
    on_turn_on:
      then:
      - mqtt.publish:
          topic: esphome/rs232/sharp/input
          payload: "HDMI1"

  - platform: uart
    name: "HDMI 2"
    data: [0x49, 0x4E, 0x50, 0x53, 0x20, 0x20, 0x31, 0x33, 0x0D, 0x0A]
    on_turn_on:
      then:
      - mqtt.publish:
          topic: esphome/rs232/sharp/input
          payload: "HDMI2"

  - platform: uart
    name: "HDMI 3"
    data: [0x49, 0x4E, 0x50, 0x53, 0x20, 0x20, 0x31, 0x38, 0x0D, 0x0A]
    on_turn_on:
      then:
      - mqtt.publish:
          topic: esphome/rs232/sharp/input
          payload: "HDMI3"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

When using string, the output of the serial commands will be like so, assuming you turn on TV Power, and then HDMI2:

```
POWR   1\r\nINPS  13\r\n
```

where it SHOULD be like:

```
POWR   1
INPS  13
```

See community forums for some other tests done
https://community.home-assistant.io/t/uart-switch-help/123245/18
