### ISSUE TITLE
[bluetooth_proxy:439]: Only one API subscription is allowed at a time

### ISSUE THREAD

**Issue by drthanwho** [esphome/issues#4841]
### The problem

Since I while my bluetooth sensors stopped comming through the esp bluetooth proxies to HA. On the other hand, on another HA that has bluetooth itself I can see the sensors comming through there so I know they are working. 

I hadn't found and errrors on the esp logs but just today I found the one bellow.

```[bluetooth_proxy:439]: Only one API subscription is allowed at a time```

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Component causing the issue

bluetooth_proxy

### Example YAML snippet

```yaml
esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

packages:
  wifi: !include common_substitutions/wifi.yaml
  device_base: !include common_substitutions/device_base.yaml

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: false

bluetooth_proxy:
  active: false
```
