### ISSUE TITLE
feat(docs): the AHT10 sensor docs needs updating

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [esphome/issues#4842]
### The problem

The docs said a log message will be generated at the `VERBOSE` level, but it has been updated to be a `WARNING` level. 

> When configured for humidity, the log ‘Components should block for at most 20-30ms in loop().’ will be generated in verbose mode. This is due to technical specs of the sensor and can not be avoided.

> ```
> [22:06:07][W][component:204]: Component aht10.sensor took a long time for an operation (0.08 s).
> [22:06:07][W][component:205]: Components should block for at most 20-30ms.
> ```

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.8.4

### What platform are you using?

ESP32-IDF

### Board

esp32dev

### Component causing the issue

aht10.sensor

### Example YAML snippet

```yaml
i2c:
  sda: 21
  scl: 22
  scan: True

sensor: 
  - platform: aht10
    temperature:
      name: "AHT10 Temperature"
    humidity:
      name: "ATH10 Humidity"
    update_interval: 60s`
```

### Additional information

https://esphome.io/components/sensor/aht10.html

https://github.com/esphome/issues/issues/4717#issuecomment-1686220731

https://github.com/esphome/esphome-docs/blob/current/components/sensor/aht10.rst?plain=1#L26C11-L26C11
