### ISSUE TITLE
M5Stamp-S3 needs 2 clicks from the rotary encoder to detect one in the programme 

### ISSUE THREAD

**Issue by boklubre** [esphome/issues#4846]
### The problem

As a test, I have set up a rotary encoder with an M5Stamp-C3 (pin_a: GPIO04, pin_b: GPIO05). This test was very successful. Every click on the rotary encoder generated a click in the programme.

Now I did the same in a project with an M5Stamp-S3. The integration was exactly the same, except for the pins (pin_a: GPIO44, pin_b: GPIO41). But now I have to click twice on the rotary encoder to generate a click in the programme.

Are there differences in the integration of the C3 and S3? 

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.3

### What platform are you using?

ESP32

### Board

M5Stamp-S3

### Component causing the issue

Rotary Encoder

### Example YAML snippet

```yaml
- platform: rotary_encoder
    name: "S - Rotary Encoder - Value"
    id: encoder
    on_clockwise:
      - logger.log: "Turned Clockwise"
    on_anticlockwise:
      - logger.log: "Turned Anticlockwise"
    pin_a:
      number: GPIO44
      inverted: true
      mode:
        input: true
        pullup: true
    pin_b:
      number: GPIO41
      inverted: true
      mode:
        input: true
        pullup: true
```
