### ISSUE TITLE
DSMR integration stops logging after connecting device to HA

### ISSUE THREAD

**Issue by dwainscheeren** [esphome/issues#4852]
### The problem

Hello,

I'm encountering an unusual problem with DSMR on my ESP32. Here's a breakdown:

When I flash the device and go to the ESP log I see the stats from my energy meter. I have set the update frequency to 10 seconds and I see every 10 seconds the data passing by.

But now the weird thing. When I add the device in HA (auto discovery) the readings of the DSMR directly stops. Then when I remove the device in HA it directly starts logging the data again when I went to the device log.

This is my device log when I just flash my yaml code on the device and **don't connect it to HA**:
![image](https://github.com/esphome/issues/assets/3868853/575dec6a-11e5-43d1-a013-f7d0b71a54ea)

Then as soon as I connect the device to HA it goes to this. After that connection it does 1 time a last reading and then just hangs on `Start requesting data from P1 port`
![image](https://github.com/esphome/issues/assets/3868853/ff03598d-77a7-486d-8658-01193558f7c9)

Then the device just doesn't do anything.  Then when I remove it in HA it starts logging again (see 11:56)
![image](https://github.com/esphome/issues/assets/3868853/503af2e2-ebab-45de-83c2-363b10531c55)

### Which version of ESPHome has the issue?

2023.8.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.9b3

### What platform are you using?

ESP32

### Board

ESP32

### Component causing the issue

DSMR

### Example YAML snippet

```yaml
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:

captive_portal:
    
web_server:
  port: 80

#DSMR part
logger:
  #baud_rate: 0
  level: VERBOSE

uart:
  rx_pin: GPIO33
  baud_rate: 115200
  rx_buffer_size: 1700

dsmr:
  request_pin: GPIO12
  request_interval: 10s
  max_telegram_length: 1700
#DSMR part end
 
sensor:
  #DSMR part
  - platform: dsmr
    energy_delivered_tariff1:
      id: dsmr_electricity_delivered_1
      name: "Energy Consumed Tariff 1"
      state_class: total_increasing
    energy_returned_tariff1:
      id: dsmr_electricity_returned_1
      name: "Energy Produced Tariff 1"
      state_class: total_increasing
    energy_delivered_tariff2:
      id: dsmr_electricity_delivered_2
      name: "Energy Consumed Tariff 2"
      state_class: total_increasing
    energy_returned_tariff2:
      id: dsmr_electricity_returned_2
      name: "Energy Produced Tariff 2"
      state_class: total_increasing
```

**Comment by dwainscheeren** [comment]
Today I tried adding/chaing logger to:
```yaml
# Enable logging
logger:
  baud_rate: 0
 ```
After that I connected the esphome device to HA and it starts working for some time, but now it just hangs. So its something that is causing it to stop reading data.

![image](https://github.com/esphome/issues/assets/3868853/d7700b70-8404-4712-b86f-e62c9ddafacc)

When I now go to the device log it only does reading a tem/hum sensor I attached for debugging to see if the device not hangs. 
![image](https://github.com/esphome/issues/assets/3868853/dd6239ab-f6c8-4044-89e7-55647fec5b50)
This one keeps loading only dsmr does nothing, no refresh, no error, nothing.
