### ISSUE TITLE
daly_BMS broke since last update

### ISSUE THREAD

**Issue by huppe101** [esphome/issues#4854]
### The problem

Previous to the last update, my Daly BMS integration worked fine:

My config file:
```
esphome:
  name: esphome-web-cc7f54
  friendly_name: Daly_BMS
  

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "="

ota:

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  rx_buffer_size: 512
  
daly_bms:
  update_interval: 1s
  
switch:
  - platform: restart
    name: "Daly BMS Restart"

sensor:
  - platform: daly_bms
    voltage:
      name: "Battery Voltage"
    cells_number:
      name: "Cells Number"
    temperature_1:
      name: "Temperature 1"
    cell_1_voltage:
      name: "Cell 1 Voltage"
    cell_2_voltage:
      name: "Cell 2 Voltage"
    cell_3_voltage:
      name: "Cell 3 Voltage"
    cell_4_voltage:
      name: "Cell 4 Voltage"
    cell_5_voltage:
      name: "Cell 5 Voltage"
    cell_6_voltage:
      name: "Cell 6 Voltage"
    cell_7_voltage:
      name: "Cell 7 Voltage"
    cell_8_voltage:
      name: "Cell 8 Voltage"
    cell_9_voltage:
      name: "Cell 9 Voltage"
    cell_10_voltage:
      name: "Cell 10 Voltage"
    cell_11_voltage:
      name: "Cell 11 Voltage"
    cell_12_voltage:
      name: "Cell 12 Voltage"
    cell_13_voltage:
      name: "Cell 13 Voltage"
    cell_14_voltage:
      name: "Cell 14 Voltage"
    cell_15_voltage:
      name: "Cell 15 Voltage"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Cc7F54"
    password: "EUwO91H1QWsC"

captive_portal:
```

Some sensors still work, but the individual voltages do not work anymore: (updated the 31st)
<img width="1174" alt="image" src="https://github.com/esphome/issues/assets/13587376/481628b8-1b83-428f-9f2c-75f0f429f624">

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.4

### What platform are you using?

ESP32

### Board

esp32dev
