### ISSUE TITLE
DNS resolution if fixed ip assigned

### ISSUE THREAD

**Issue by elgatho** [esphome/issues#4855]
### The problem

When fixed ip is assigned esphome doest'n pronounce hostname to dns server. Device is responding on mdns and ping, connection is ok
On dhcp is working

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.8

### What platform are you using?

ESP8266

### Board

wemos d1 mini

### Component causing the issue

dns

### Example YAML snippet

```yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan
  ap:
    ssid: ${device}
    password: !secret recovery_wifi_password

  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.19.1
    subnet: 255.255.255.0
    dns1: 192.168.19.1
    dns2: 192.168.0.56
```

### Anything in the logs that might be useful for us?

```txt
on static ip
nslookup sypialnia-wemos.lan 192.168.19.1
Server:  UnKnown
Address:  192.168.19.1

*** UnKnown can't find sypialnia-wemos.lan: Non-existent domain

on dhcp
>nslookup sypialnia-wemos.lan 192.168.19.1
Server:  UnKnown
Address:  192.168.19.1

Name:    sypialnia-wemos.lan
Address:  192.168.19.112
```

### Additional information

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  reboot_timeout: ${reboot_timeout}
  domain: .lan
  ap:
    ssid: ${device}
    password: !secret recovery_wifi_password

with dhcp is working
