### ISSUE TITLE
After update to 2023.8.3 device is not accessible 

### ISSUE THREAD

**Issue by daha76** [esphome/issues#4861]
### The problem

Hello,

Today I made an update from 2023.8.2 to 2023.8.3 of the ESPHome and firmware of my ESP8266 device. From that time ESPHome detected my device as online and I could ping it successfully, but I can't get logs or any data from it. ESPHome running as an addon of Home Assistant on RPi4. 
When I try to get logs this error pops up:

WARNING Can't connect to ESPHome API for heater.hdhome.sk: Error connecting to ('192.168.2.2', 6053): [Errno 111] Connect call failed ('192.168.2.2', 6053) (SocketAPIError)

I tried to restore the previous version but it didn't help, and OTA isn't working as well. When I tried to do OTA I got the same error.
One thing I noticed is that the MAC address of the device has been changed. I don't know why, but I updated my router's DHCP table to get the same IP address as before.
The device is not easily reachable, 200km away, so I don't know if I can repair it. Any ideas?

### Which version of ESPHome has the issue?

2023.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.4

### What platform are you using?

ESP8266

### Board

WemosD1 Mini

### Component causing the issue

Network

### Example YAML snippet
```yaml
esphome:
  name: heater
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "MytoChalupa"
  password: !secret wifi_passwd
  domain: .hdhome.sk

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heater Hotspot"
    password: !secret wifi_passwd

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret wifi_passwd
````

### Anything in the logs that might be useful for us?

```txt
WARNING Can't connect to ESPHome API for heater.hdhome.sk: Error connecting to ('192.168.2.2', 6053): [Errno 111] Connect call failed ('192.168.2.2', 6053) (SocketAPIError)
```
