### ISSUE TITLE
Mini D1 ESP32 doesn't boot with power on VCC pin after upgrade to ESPHOME 2023.8.1

### ISSUE THREAD

**Issue by c-MM** [esphome/issues#4864]
### The problem

After upgrading my D1 mini ESP32 boards (clones from AZdelivery on Amazon) to ESPHOME 2023.8.{1,2,3} they don't boot anymore when powered via the VCC and GND pins. They still work fine when powered via USB.

Flashing the boards via USB back to ESPHOME 2023.7.1 makes them work again when powered via VCC and GND pins.

I didn't try ESPHOME 2023.8.0 but the issue exists with 2023.8.1, 2023.8.2 and 2023.8.3.

### Which version of ESPHome has the issue?

2023.8.1, 2023.8.2 and 2023.8.3 (I suspect  2023.8.0 too)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.3

### What platform are you using?

ESP32

### Board

D1 mini ESP32 from AZdelivery (clone of Wemos D1 mini ESP32)

### Component causing the issue

core, boot

### Example YAML snippet

```yaml
substitutions:
  name: btp1
esphome:
  name: ${name}
  name_add_mac_suffix: false
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "eWVpMUZlZTlUaGllMnF1b282dUNoNGthaE1vaGNpaTc="

ota:
  password: "<password>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

improv_serial:

esp32_ble_tracker:
  scan_parameters:
    window: 1100ms
    interval: 1100ms
    active: true

bluetooth_proxy:
  active: true
```
