### ISSUE TITLE
Documentation for AP mode does not mention disabled services

### ISSUE THREAD

**Issue by danhawkes** [esphome/issues#4866]
### The problem

This relates to the issue described in https://github.com/esphome/issues/issues/642.

The docs for [Access Point](https://esphome.io/components/wifi#access-point-mode) mode make no mention of the fact that other services are disabled as a side effect.

 I think this is a significant foot-gun, because I've just done the following:

- Enabled `ap` and `ota`
- Set an incorrect primary WiFi password to test recovery via the access point
- now have a bricked device because there's no means of recovering from access point mode.

```yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret captive_portal_wifi_password

ota:
```

Can this please be added to the docs?

### Which version of ESPHome has the issue?

2023.5.5

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret captive_portal_wifi_password

ota:
```
