### ISSUE TITLE
ESP32-C3 Doesn't boot/connect after reset/repowering

### ISSUE THREAD

**Issue by martijnvwezel** [esphome/issues#4870]
### The problem

If you install the ESPHome on a ESP32C3 it works. However after a reboot/repower/restart if fails to work. Its hard to debug, because the moment you debug/open serial connection it works and keeps on working. If you update/install and keep it plugged it keeps working. After it lost its WiFi it gets a reboot and stops from working.

### Which version of ESPHome has the issue?

ESPHome 2023.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

latest and before

### What platform are you using?

ESP32

### Board

Muino Water Meter

### Example YAML snippet

```yaml
substitutions:
  name: muino-water-meter-ddb02c
packages:
  esphome.muino-water-meter: github://martijnvwezel/watermeter-esphome/muino-water-meter-esp32.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: redacted-key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

### Anything in the logs that might be useful for us?

```txt
Cannot log, otherwise it works..
```

### Additional information

This project: https://watermeter.muino.nl/
