### ISSUE TITLE
Compilation failed for D1mini32 variant (Could not find one of 'package.json' manifest files in the package)

### ISSUE THREAD

**Issue by sebcaps** [esphome/issues#4871]
### The problem

While trying to compile for wemos_d1_mini32 board the following YAML file got an error message

### Which version of ESPHome has the issue?

2023.8.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

wemos_d1_mini32

### Component causing the issue

N/A

### Example YAML snippet

```yaml
esphome:
  name: d1mini32
  friendly_name: D1MINI32

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3NUMfRA0zRIOut8+dp7MUX8BWpaYXdvdPQHP4C8+hi8="

ota:
  password: "8b00910ad44e008efafdf13b96dcb424"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1Mini32 Fallback Hotspot"
    password: "48aCdr6jVNm7"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.8.3
INFO Reading configuration /config/d1mini32.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing d1mini32 (board: wemos_d1_mini32; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
MissingPackageManifestError: Could not find one of 'package.json' manifest files in the package
```

### Additional information

Compilation was OK on 2023.7.x version of esphome.
Similar to #4272  & #4691.
But none of the solution works.
