### ISSUE TITLE
SPI Component does not work with Pico W currently

### ISSUE THREAD

**Issue by 6d6178** [esphome/issues#4874]
### The problem

Today I wanted to change the update_interval of a Raspberry Pi Pico W with a single MAX6675 attached.
The board hasn't been running since late May I think. Before the update, it was running as usual and provided the temperature to Home Assistant.

After applying the change in ESPHome, the new firmware compiled and was successfully uploaded to the board. Yet, no new values were available in Home Assistant and I couldn't access the log.

After some troubleshooting this evening I made the following observations:

- When initially setting up a Raspberry Pi Pico W from ESPHome, everything works fine
- When adding a SPI component, not even a sensor, the board will not function as wanted
- The board will then be reachable with ping and ota updates but not api/HomeAssistant
- Installing new versions still works. Installing the bare defaults again will result in a working board but without sensor.
- I tried several Pins for spi, but all of them didn't work
- Has been observed with several boards
- There are several related error messages, but all of them seem to be the result of the api component not starting
- I upgraded the ESPHome Version from 2023.3 to latest, but I assume it is not related anyway, since this seems to be a Pi Pico specific issue

### Which version of ESPHome has the issue?

2023.8.3

### What type of installation are you using?

Docker

### What platform are you using?

RP2040

### Board

Raspberry Pi Pico W

### Component causing the issue

spi

### Example YAML snippet

```yaml
esphome:
  name: pico-3
  friendly_name: pico-3

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: "xxx"
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Pico-3 Fallback Hotspot"
    password: "xxx"

spi:
  miso_pin: GPIO19
  clk_pin: GPIO18
```

### Anything in the logs that might be useful for us?

```txt
connecting to ('xxx.xxx.xxx.xxx', 6053): [Errno 113] Connect call failed ('xxx.xxx.xxx.xxx', 6053) (SocketAPIError)
INFO Trying to connect to pico-3.xxx in the background
```

**Comment by 6d6178** [comment]
It seems it was my mistake.
I remebered that some pins don't work for SPI. After some trying, I made it work with:
```

spi:
  clk_pin: GPIO2
  miso_pin: GPIO4
  mosi_pin: GPIO3

sensor:
  - platform: max6675
    name: "Thermocouple"
    cs_pin: GPIO5
    update_interval: 3s
```

I consider this "Issue" closed. I will look into documenting this behaviour.
Is there a way to improve the verbosity or framework so this can not be compiled with an invalid configuration?
