### ISSUE TITLE
native api port does not open on my esp32 s2

### ISSUE THREAD

**Issue by victorclaessen** [esphome/issues#4875]
### The problem

The API port on my board is not opening. First [I thought](https://github.com/esphome/feature-requests/issues/1444#issuecomment-1714237925) that this was related to the new wireguard component, but it also happens without the wireguard component, so apparently it's something else.

I have the following relevant configuration (I will put the complete YAML in the "Example YAML snippet" box)
```
api:
  port: 6053
  reboot_timeout: 0s
```

but esphome cannot connect to the API to read the logs, and home assistant cannot connect to the API either. nmap shows that the port is closed. Web interface and OTA work. (Wireguard also works, sorry for any confusion in that thread).
```
nmap -p 80,3232,6053 **redacted_ip**
Starting Nmap 7.80 ( https://nmap.org ) at 2023-09-12 18:31 CEST
Nmap scan report for **redacted_ip**
Host is up (0.055s latency).

PORT     STATE  SERVICE
80/tcp   open   http
3232/tcp open   mdtp
6053/tcp closed x11

Nmap done: 1 IP address (1 host up) scanned in 0.19 seconds
```

### Which version of ESPHome has the issue?

2023.9.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.9.1

### What platform are you using?

ESP32

### Board

unexpected maker feather s2 neo

### Component causing the issue

api

### Example YAML snippet

```yaml
substitutions:
  hostname: 'feather_matrix_test'
  address: **redacted_ip**
  comment: "test platform for SHT45 sensor"

esp32:
  board: lolin_s2_mini
  variant: ESP32S2

status_led:
  pin:
    number: 13
    inverted: True

power_supply:
  - id: "${hostname}_rgb_power"
    pin: 39
  - id: "${hostname}_matrix_power"
    pin: 4

light:
  - name: "${hostname} rgb led"
    platform: neopixelbus
    id: rgb
    variant: WS2812
    type: GRB
    num_leds: 1
    pin: 40
    power_supply: "${hostname}_rgb_power"
    effects:
      - pulse:
      - random:
      - strobe:
  - name: "${hostname} matrix"
    platform: fastled_clockless
    id: matrix
    chipset: WS2812
    rgb_order: GRB
    pin: 21
    power_supply: "${hostname}_matrix_power"
    num_leds: 25
    effects:
      - pulse:
      - random:
      - strobe:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:

binary_sensor:
  - name: "${hostname} boot button"
    platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true

i2c:
  sda: 08
  scl: 09
  scan: true
  id: stemma

sensor:
  - platform: sht4x
    temperature:
      name: "${hostname} temperature"
    humidity:
      name: "${hostname} humidity"
    address: 0x44
    update_interval: 1s
  - platform: uptime
    id: uptime_seconds
    internal: true
    update_interval: 1s

wifi:
  ssid: !secret wifi_grijs_ssid
  password: !secret wifi_grijs_password
  fast_connect: true
  use_address: $address
esphome:
    name: ${hostname}
    comment: ${comment}
web_server: 
  port: 80
  local: true

api:
  port: 6053
  reboot_timeout: 0s
ota:
logger:
  level: INFO
# time:
  # - platform: homeassistant
    # id: homeassistant_time

text_sensor:
  - platform: wifi_info
    ip_address:
      name: '${hostname} IP Address'
    ssid:
      name: '${hostname} Connected SSID'
    bssid:
      name: '${hostname} Connected BSSID'
    mac_address:
      name: '${hostname} MAC Address'
  - platform: version
    name: "${hostname} version"
  - platform: template
    name: ${hostname} uptime
    update_interval: 10s
    icon: mdi:clock-start
    lambda: |-
      int seconds = (id(uptime_seconds).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      if ( days ) {
        return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( hours ) {
        return { (String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( minutes ) {
        return { (String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else {
        return { (String(seconds) +"s").c_str() };
      }

switch:
  - platform: restart
    id: "${hostname}_restart_switch"
    name: "${hostname}_restart"
    disabled_by_default: true
```

### Anything in the logs that might be useful for us?

```txt
By the time I can connect via usb to the logger, esphome has already booted up so far that any line regarding the startup of the api component has already passed. :-(
```
