### ISSUE TITLE
No IPv6 with ESP8266 even with enable_ipv6 set to true

### ISSUE THREAD

**Issue by Nardol** [esphome/issues#4876]
### The problem

I've modified my ESPHome config to enable IPv6 for ESP8266.
But using ping or dig to query aaaa record on port 5353 of the device I have no IPv6 at all.
I have no compilation error but even in very_verbose log level, I also have nothing displayed about IPv6 at all, no error, nothing.
IPv6 for ESP8266 does not work in my case.

### Which version of ESPHome has the issue?

2023.9.0b1

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

network

### Example YAML snippet

```yaml
esphome:
  name: ballon-eau-chaude
  project:
    name: "Shelly.ballon_eau_chaude"
    version: "1.3.0"

esp8266:
  board: esp01_1m
  restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_key
  ap:
    password: !secret ap_key

network:
  enable_ipv6: true

captive_portal:

logger:
  baud_rate: 0
  level: ERROR # Same with very_verbose

api:
  encryption:
    key: !secret ballon_eau_chaude_encryption_key

ota:
  password: !secret ballon_eau_chaude_ota_pass

switch:
- platform: gpio
  name: "Ballon d'Eau Chaude"
  icon: "mdi:water-boiler"
  pin: GPIO4
  id: ballon

binary_sensor:
- platform: gpio
  pin:
    number: GPIO5
  name: "Switch Shelly 1"
  on_state:
    then:
    - switch.toggle: ballon
  internal: true
  id: switchid

time:
- platform: homeassistant
  id: my_timer
  timezone: Europe/Paris

button:
- platform: factory_reset
  name: Réinitialiser et redémarrer Ballon d'eau chaude
  entity_category: "diagnostic"
- platform: restart
  name: "Redémarrer Ballon d'eau chaude"
  entity_category: "diagnostic"
```

### Additional information

I can send a log in very_verbose if needed but when I read one, I had no reference to IPv6 at all.
Unfortunately I have no ESP8266 I can connect to directly using serial, only Wi-Fi.
And I have no other board to test with, all my ESP8266 are esp01_1m.
