### ISSUE TITLE
Sprinkler  repeat_number not operating correctly with latching valve 

### ISSUE THREAD

**Issue by philochardbleu** [esphome/issues#4878]
### The problem

I have an irrigation sprinker hydro indexing valve, and only one latching valve. I have four zones covered by the indexing valve. 
So, I want to repeat the same "on-off" sequence 4 times, each of them being separated by a valve_open_delay.
When repeat_number is 1, the switch_valve_on is operated correctly, but the switch_valve_off operates simultaneously with the switch_valve_on. If the repeat_number is more than one, the first pulse is correct but all the following are not correct.
If a valve_open_delay is set, it is not taken into account.

### Which version of ESPHome has the issue?

 2023.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.2

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

sprinkler

### Example YAML snippet

```yaml
sprinkler:
  - id: arrosage_ctrlr
    valve_pulse_duration: 1000ms
    manual_selection_delay: 2s
    repeat_number:
      id: arrosage_repetition_id
      name: arrosage_repetition
      initial_value: 4
      min_value: 1
      max_value: 4
      step: 1
      restore_value: true
      disabled_by_default: false
      mode: slider # Defines how the number should be displayed in the UI

    valves:
      - valve_switch: "Arrosage"
        valve_off_switch_id: arrosage_off
        valve_on_switch_id: arrosage_on
        run_duration_number:
          id: arrosage_duree_id
          name: arrosage_duree
          initial_value: 10
          min_value: 1
          max_value: 60
          step: 5
#          unit_of_measurement: min
          icon: "mdi:timer-outline"
          restore_value: true
          disabled_by_default: false
          mode: slider # Defines how the number should be displayed in the UI
 
switch:
  - platform: gpio
    id: arrosage_off
    name: arrosage_off
    pin: GPIO12
    internal: False
    inverted: True
  - platform: gpio
    id: arrosage_on
    name: arrosage_on
    pin: GPIO14
    internal: False
    inverted: False
```

### Additional information

![image](https://github.com/esphome/issues/assets/37799557/dee7f886-e145-4d97-8dcb-9a08a327262e)
