### ISSUE TITLE
Warning! Could not find the package with 'Update' requirements for your system 'linux_aarch64'

### ISSUE THREAD

**Issue by thisboyiscrazy** [esphome/issues#4879]
### The problem

When using the Web UI to install I get: 

Warning! Could not find the package with 'Update' requirements for your system 'linux_aarch64'
...
src/esphome/components/ota/ota_backend_arduino_esp32.cpp:8:10: fatal error: Update.h: No such file or directory

This is running a raspberry Pi.

When I compile from my computer it compiles just fine.

### Which version of ESPHome has the issue?

2023.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.2

### What platform are you using?

ESP32

### Board

LilyGo-T-Relay

### Example YAML snippet

```yaml
esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "68EfFdEfSEQzza/8pIO8tjIX0m72HI1U457xoEvbQQI="

ota:
  password: "94fa2de6391f14268aba82d709b80ac6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "w6bAUUXKyGSh"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.8.3
INFO Reading configuration /config/esphome/test.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing test (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Library Manager: Installing Update
Warning! Could not find the package with 'Update' requirements for your system 'linux_aarch64'
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
Compiling /data/test/.pioenvs/test/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling /data/test/.pioenvs/test/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling /data/test/.pioenvs/test/src/esphome/components/wifi/wifi_component.cpp.o
Compiling /data/test/.pioenvs/test/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
src/esphome/components/ota/ota_backend_arduino_esp32.cpp:8:10: fatal error: Update.h: No such file or directory

****************************************************************
* Looking for Update.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Update.h"
* Web  > https://registry.platformio.org/search?q=header:Update.h
*
****************************************************************

 #include <Update.h>
          ^~~~~~~~~~
compilation terminated.
*** [/data/test/.pioenvs/test/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o] Error 1
src/esphome/components/web_server_base/web_server_base.cpp:9:10: fatal error: Update.h: No such file or directory

****************************************************************
* Looking for Update.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Update.h"
* Web  > https://registry.platformio.org/search?q=header:Update.h
*
****************************************************************

 #include <Update.h>
          ^~~~~~~~~~
compilation terminated.
*** [/data/test/.pioenvs/test/src/esphome/components/web_server_base/web_server_base.cpp.o] Error 1
========================= [FAILED] Took 13.86 seconds =========================
```
