### ISSUE TITLE
The media player doesn't work over mqtt

### ISSUE THREAD

**Issue by AndreKR** [esphome/issues#4882]
### The problem

I have configured an I2S media player.

The media player is not discovered by Home Assistant.

I'm assuming the discovery message would be under `homeassistant/media_player`? In that case, it's not there:

![image](https://github.com/esphome/issues/assets/1188538/8861e5ad-a37e-4e28-8e62-1566df8ba0c1)

There is also nothing about this media player under the device topic, although I don't know if anything should be there, control flows from HA to ESPHome after all:

![image](https://github.com/esphome/issues/assets/1188538/9a150749-e96a-4d15-bd03-e10e4e66efbe)

### Which version of ESPHome has the issue?

2023.8.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.8.0

### What platform are you using?

ESP32

### Board

Sonoff TX Ultimate

### Component causing the issue

media_player/i2s_audio

### Example YAML snippet

```yaml
media_player:
  - platform: i2s_audio
    id: media_out
    name: Player
    dac_type: external
    i2s_dout_pin: GPIO15
    i2s_audio_id: audio_i2s
    i2s_comm_fmt: lsb
    mode: mono

i2s_audio:
  id: audio_i2s
  i2s_lrclk_pin: GPIO4
  i2s_bclk_pin: GPIO2
```
