### ISSUE TITLE
Float output get_min_power() returning 0

### ISSUE THREAD

**Issue by HenryColdCZ** [esphome/issues#4883]
### The problem

Problem observed at **ac_dimmer** component which is using float output

I set the **min_power** to 5%, and at lambda call: `id(dimmer_bojler).get_min_power()` I ask for that value, I get always 0

Compared the **max_power** which I set to 75% and at lamda call `id(dimmer_bojler).get_max_power()` I get correct value 0.75 

### Which version of ESPHome has the issue?

2023.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.2

### What platform are you using?

ESP32

### Board

ESPDUINO32

### Component causing the issue

Float output

### Example YAML snippet

```yaml
sensor:
  # get_min_power() returning always 0 even if set is 5% (0.05)
  - platform: template
    name: "Bojler dimmer min výkon"
    id: bojler_dimmer_min_power
    lambda: |-
      return id(dimmer_bojler).get_min_power();
    update_interval: 10s
    accuracy_decimals: 4

  # get_max_power() returning correct value 0.75 (75%)
  - platform: template
    name: "Bojler dimmer max výkon"
    id: bojler_dimmer_max_power
    lambda: |-
      return id(dimmer_bojler).get_max_power();
    update_interval: 10s
    accuracy_decimals: 4

output:
  - platform: ac_dimmer
    id: dimmer_bojler
    min_power: 5% 
    max_power: 75% 
    zero_means_zero: true 
    init_with_half_cycle: NO
    method: leading pulse
    gate_pin: 
      number: GPIO18
      inverted: no
      mode: 
        output: True
        #open_drain: True
    zero_cross_pin:
      number: GPIO19
      mode:
        input: True
        pulldown: false
        pullup: true 
      inverted: false
```
