### ISSUE TITLE
SNTP  on_time: sometime after reboot cron (every second) start after some minutes

### ISSUE THREAD

**Issue by Jan3726** [esphome/issues#4884]
### The problem

Lately i am noticing this problem:

I am using an action every seconds but sometime (after reboot) it start immediately to work every second, but sometime it takes also 10min to start the action.
I tried also to use all the component.update directly without the script, and also using sntp, but the problem is the same.
I can use also Interval_update: but i want it to be updated only if the switch is ON, it happens also with every minute cron

### Which version of ESPHome has the issue?

2023.8

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
time:
  - platform: homeassistant
    id: ntp
    timezone: Europe/Rome
    on_time:
      - seconds: /1
        then:
          - if:
             condition: 
              - lambda: return (id(ntp).now().is_valid());
             then:     
              - script.execute: un_secondo

script:
  - id: un_secondo
    mode: restart
    then:
         - if:
            condition:
              - switch.is_on: caloriferi_min_potenza
            then:
              - component.update: caloriferi_min_tempo_reale_s
              - component.update: caloriferi_min_s
              - component.update: caloriferi_step_min
              - component.update: caloriferi_step_max_min
              - component.update: caloriferi_max_min
              - component.update: mc_caloriferi_tot_min
         - if:
            condition:
              - switch.is_on: caloriferi_max_potenza
            then:
              - component.update: caloriferi_tempo_reale_s
              - component.update: caloriferi_s              
              - component.update: caloriferi_step_max
              - component.update: caloriferi_step_max_min
              - component.update: caloriferi_max_min
              - component.update: mc_caloriferi_tot_max
         - if:
            condition:
              - switch.is_on: rele_sanitario
            then:
              - component.update: sanitario_s
              - component.update: sanitario_tempo_reale_s              
              - component.update: sanitario_step
              - component.update: mc_sanitario_tot
         - if:
                 condition:
                  - switch.is_on: pausa_caloriferi_start
                 then:
                  - component.update: pausa_caloriferi_s
                  - component.update: pausa_caloriferi_step
```
