### ISSUE TITLE
Pico W bootloop on WiFi connect

### ISSUE THREAD

**Issue by oddstr13** [esphome/issues#4895]
### The problem

Last line logged is `[I][wifi:274]: WiFi Connecting to 'IoT'...`, followed by a reboot a few seconds later.
This happens more often than not, but after a few minutes it eventually manages to succeed (I counted 15 reboots once, haven't bothered counted other than that once).

Git bisect points to esphome/esphome#3509 being the breaking change, specifically, esphome/esphome@a9630ac847a292bc6ad671356804deb809eb6dc4 has the bootloop issue, while esphome/esphome@22c0b0ab does not.

### Which version of ESPHome has the issue?

a9630ac -> dev

### What type of installation are you using?

pip

### What platform are you using?

RP2040

### Board

Custom, but problem also present for plain Pico W

### Additional information

Discord thread; https://discord.com/channels/429907082951524364/1150959304589967461

**Comment by hostcc** [comment]
@oddstr13 , thanks for spotting that!
I can 100% reproduce this, including bisected versions (https://github.com/esphome/esphome/commit/a9630ac847a292bc6ad671356804deb809eb6dc4 - bootloop, https://github.com/esphome/esphome/commit/22c0b0ab - ok) and affected version eventually would boot in unpredictable amount of reboots.

**Comment by hostcc** [comment]
Took another attempt to pinpoint the issue - using current `dev` (@11f6e555f9607767991a93d9c6259ef627a39bda) reverted all the changes over `esphome/core` introduced by the #pr3509:
```
$ git rev-parse HEAD
11f6e555f9607767991a93d9c6259ef627a39bda
$ git diff 22c0b0ab..a9630ac  esphome/core/ | patch -p1 -R
patching file 'esphome/core/__init__.py'
patching file 'esphome/core/config.py'
patching file 'esphome/core/defines.h'
patching file 'esphome/core/helpers.cpp'
patching file 'esphome/core/helpers.h'
patching file 'esphome/core/log.h'
```

Once compiled and uploaded the RP2040W boots fine, both after being reset during upload and after power on.
So there is a change went to `esphome/core` introduced the issue - will attempt to investigate further.

Config is pretty minimal:
```yaml
---
rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

esphome:
  name: minimal

logger:
  level: VERY_VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk
```
