### ISSUE TITLE
ili9xxx compile fails with  color_palette: GRAYSCALE

### ISSUE THREAD

**Issue by clydebarrow** [esphome/issues#4896]
### The problem

Compiling a yaml with the ili9xxx component and setting `color_palette: GRAYSCALE` results in this compile time error:

```
INFO Generating C++ source...
ERROR ID uint8_t_2 is already registered
```

My PR https://github.com/esphome/esphome/pull/5406 has a fix for this.

### Which version of ESPHome has the issue?

2023.10.0-dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

ili9xxx

### Example YAML snippet

```yaml
- platform: ili9xxx
    model: TFT 2.4
    cs_pin: GPIO5
    dc_pin: GPIO4
    color_palette: GRAYSCALE
    reset_pin: GPIO22
    lambda: |-
      it.rectangle(0, 0, it.get_width(), it.get_height());
```
