### ISSUE TITLE
2023.9.0 and up breaks SPI communication with atm90e32 component 

### ISSUE THREAD

**Issue by descipher** [esphome/issues#4902]
### The problem

When updating to 2023.9.0b1 and up the atm90e32 fails to initialize during setup.

### Which version of ESPHome has the issue?

2023.9.0 and up

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

any

### What platform are you using?

ESP8266

### Board

esp12e

### Component causing the issue

spi atm90e32

### Example YAML snippet

```yaml
esphome:
  name: power-meter-2

esp8266:
  board: esp12e

spi:
  clk_pin: 14
  miso_pin: 12
  mosi_pin: 13

substitutions:
# Change the disp_name to something you want
  disp_name: PM
  update_time: 15s

  current_cal: '15270'
  phase_a_voltage_cal: '4470'
  phase_c_voltage_cal: '4479'

sensor:
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: ${disp_name} L1 Volts
        accuracy_decimals: 2
      current:
        name: ${disp_name} CT1 Amps
        id: "ct1Amps"
      power:
        name: ${disp_name} CT1 Watts
        accuracy_decimals: 1
        id: "ct1Watts"
      gain_voltage: ${phase_a_voltage_cal}
      gain_ct: ${current_cal}
    phase_c:
      voltage:
        name: ${disp_name} L2 Volts
        accuracy_decimals: 2
      current:
        name: ${disp_name} CT2 Amps
        id: "ct2Amps"
      power:
        name: ${disp_name} CT2 Watts
        accuracy_decimals: 1
        id: "ct2Watts"
      gain_voltage: ${phase_c_voltage_cal}
      gain_ct: ${current_cal}
    frequency:
      name: ${disp_name} Freq
    line_frequency: 60Hz
    gain_pga: 2x
    chip_temperature:
      name: ${disp_name} IC Temperature
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} Total Amps
    id: "totalAmps"
    lambda: return id(ct1Amps).state + id(ct2Amps).state;
    accuracy_decimals: 2
    unit_of_measurement: A
    update_interval: ${update_time}
    device_class: current
  - platform: template
    name: ${disp_name} Total Watts
    id: "totalWatts"
    lambda: return id(ct1Watts).state + id(ct2Watts).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}
```
```


### Anything in the logs that might be useful for us?

```txt
[13:54:47][C][spi:067]: SPI bus:
[13:54:47][C][spi:068]:   CLK Pin: GPIO14
[13:54:47][C][spi:069]:   SDI Pin: GPIO12
[13:54:47][C][spi:070]:   SDO Pin: GPIO13
[13:54:47][C][spi:072]:   Using HW SPI: SPI
[13:54:47][C][:160]: ATM90E32:
[13:54:47][C][atm90e32:161]:   CS Pin: GPIO5
[13:54:47][E][atm90e32:163]: Communication with ATM90E32 failed!
```
```


### Additional information

_No response_
