### ISSUE TITLE
ESP8266 not functioning when UART connected. Connecting after power up works fine.

### ISSUE THREAD

**Issue by DracoTomes** [esphome/issues#4904]
### The problem

Hello,

I'm setting up an ESP8266 that is connected via UART. The ESP is a NodeMCU from AZ-Delivery, it's currently on a breadboard.
GPIO13 and PGIO15 are used for the UART bus. When the MCU receives power while the GPIOs are connected it will not work completely. It is not outputting to hardware UART / USB cable and will not do any automations. It seems GPIO15 is also pulled high since the TX LED on the RS-485 Transceiver will light up. The only way I can interact with the device is to flash a new firmware OTA, even though the usual ESPHome API is not reachable.
If I unplug the cables on GPIO13 and GPIO15 the device will boot normally.
Afterwards I plug in the cables and the device will function using this UART bus for modbus commands... until the next reboot.

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

UART

### Example YAML snippet

```yaml
esphome:
  name: "test-board"
  friendly_name: Test Board

esp8266:
  board: nodemcuv2

logger:
  level: VERBOSE
  baud_rate: 0

uart:
  tx_pin: GPIO015
  rx_pin: GPIO013
  baud_rate: 9600

modbus:
  id: modbus1

modbus_controller:
  - id: test
    address: 11
    modbus_id: modbus1
```
