### ISSUE TITLE
External Packages Do Not Refresh

### ISSUE THREAD

**Issue by FriedCheese2006** [esphome/issues#4906]
### The problem

When defining a remote package, the refresh option shows an error for "not a valid value" using the [provided example](https://esphome.io/guides/configuration-types.html?highlight=packages#remote-git-packages):
![image](https://github.com/esphome/issues/assets/49689423/954a37ed-7429-49df-b0ac-2413d4eb6bbf).

### Which version of ESPHome has the issue?

2023.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.2

### What platform are you using?

ESP32

### Component causing the issue

packages

### Example YAML snippet

```yaml
substitutions:
  # Set the device name
  name: media-room-tiny-radar
  # Set the friendly name
  friendly_name: Media Room Tiny Radar
  # Provide the wifi SSID
  wifi: !secret wifi_ssid
  #Provide the wifi password
  wifi_pass: !secret wifi_password
  #Provide an OTA password:
  ota_pass: "trustbutverifywalkingwithabigstick"

packages:
  micro_radar: github://FriedCheese2006/HomeAssistant/ESPHome/ESP32_Micro_Radar/ESP32_S2/ESP32_Mini_Radar.yaml
  refresh: 1d

### No modifications needed below here ###
####################################################################################

esphome:
  name: $name
  friendly_name: $friendly_name
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_cpu: 80000000L
  name_add_mac_suffix: false
```

**Comment by FriedCheese2006** [comment]
Yep, and to revise the main URL to the full version. TY much!

```
packages:
  micro_radar:
    url: https://github.com/FriedCheese2006/HomeAssistant
    file: ESPHome/ESP32_Micro_Radar/ESP32_S2/ESP32_Mini_Radar.yaml
    refresh: 1h
```
