### ISSUE TITLE
Stop working MAX7219 7-Segment Display after update 2023.09 (HA can't connect to API)

### ISSUE THREAD

**Issue by DieMetRik** [esphome/issues#4911]
### The problem

After update from ESPHome 2023.08.3
One of my device goes down

Device Unknow in HA at now
I can update ESP throw OTA wo any problem.
Then try to log wirelessly:
````
WARNING Can't connect to ESPHome API for 192.168.1.116: Error connecting to ('192.168.1.116', 6053): [Errno 111] Connect call failed ('192.168.1.116', 6053) (SocketAPIError)
````
After small investigation:
If comment this section:
````
display:
    platform: max7219
    id: max7219_display
    cs_pin: D8
    num_chips: 1
    intensity: 15
    update_interval: 1s
    lambda: |-
      it.print(0, id(display_data).state.c_str());
````
Afterthat ESP Api work good

### Which version of ESPHome has the issue?

2023.09

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.09.3

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

max7219

### Example YAML snippet

```yaml
substitutions:
  device_name: temperature-display
  device_ip: 192.168.1.116
  platform: ESP8266
  board: d1_mini
  device_description: "Дисплей температуры и ppm в гостиной"

esphome:
  name: ${device_name}
  platform: ${platform}
  board: ${board}
  comment: ${device_description}

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "J2+3oqEO6eDX0EleMvkLcTooGO0x2MaNFk+C/nFkRbU="
# Password for OTA update

ota:
  password: !secret ota_password
# Wifi settings
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${device_ip}
    gateway: 192.168.1.1
    subnet: 255.255.255.0
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} ap
    password: !secret ap_password

captive_portal:
spi:
  clk_pin: D5
  mosi_pin: D7

display:
    platform: max7219
    id: max7219_display
    cs_pin: D8
    num_chips: 1
    intensity: 15
    update_interval: 1s
    lambda: |-
      it.print(0, id(display_data).state.c_str());

# # SENSOR AREA
text_sensor:
  - platform: homeassistant
    id: display_data
    entity_id: sensor.livingroom_screen_data
    internal: true
    disabled_by_default: true
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.9.0
INFO Reading configuration /config/esphome/temperature-display.yaml...
INFO Starting log output from 192.168.1.116 using esphome API
WARNING Can't connect to ESPHome API for 192.168.1.116: Error connecting to ('192.168.1.116', 6053): [Errno 111] Connect call failed ('192.168.1.116', 6053) (SocketAPIError)
INFO Trying to connect to 192.168.1.116 in the background
```
