### ISSUE TITLE
OTA with esp-idf not working

### ISSUE THREAD

**Issue by TimelessNL** [esphome/issues#4916]
### The problem

The OTA functionality does not seem to work, the update itself is successful but after reboot it is still running the previous firmware.

### Which version of ESPHome has the issue?

2023.9.0b2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

Shelly Plus 1PM

### Component causing the issue

OTA

### Example YAML snippet

```yaml
esphome:
  name: ${hostname}
  comment: "Shelly Plus 1PM"
  project:
    name: "ESPHome.Shelly"
    version: "Shelly Plus 1PM"
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

preferences:
  flash_write_interval: 1d

ota:
  password: !secret ota_password
```

### Anything in the logs that might be useful for us?

```txt
INFO Uploading /config/.esphome/build/shelly/.pioenvs/shelly/firmware.bin (859616 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
```

### Additional information

The OTA section on the webportal is also not present, I cannot upload a image via the webinterface.
![afbeelding](https://github.com/esphome/issues/assets/10838968/35804ca7-9ea2-49da-b91c-b52e6a47c5fe)

**Comment by TimelessNL** [comment]
The OTA log output from the device:
![afbeelding](https://github.com/esphome/issues/assets/10838968/50256b1e-8c5a-4c87-8ae4-3a81fa60ff39)

**Comment by nerdyjan** [comment]
same here with 2024.8.3 and Shelly PM mini Gen3 (https://devices.esphome.io/devices/Shelly-PM-Mini-Gen3)

**Comment by hannesb** [comment]
same with 2024.10.2 and firebeetle esp32-c3

**Comment by hannesb** [comment]
Got it working now by specifing the newest version of the ESP-IDF framework:
```
esp32:
  board: dfrobot_beetle_esp32c3
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
```
