### ISSUE TITLE
BP5758D creeping on when turned off (possibly a sleep mode issue)

### ISSUE THREAD

**Issue by dwildstr** [esphome/issues#4920]
### The problem

A recent flash of LibreTiny to some bulbs running BK7231N/BP5758D chipsets has resulted in bulbs which turn fully off but, after being turned off, slowly creep back up to about 10% brightness. This is the same behavior I reported exactly a year ago (by sheer coincidence) when the same bulbs ran OpenBeken ([OpenBK issue linked here](https://github.com/openshwprojects/OpenBK7231T_App/issues/221)) with what is likely the same cause, which is to say improperly entering sleep mode. 

In OpenBK the fix for this bug is in [PR#242](https://github.com/openshwprojects/OpenBK7231T_App/pull/242); I haven't had a chance to do a head-to-head comparison of code but it seems likely that there is analogous code in esphome/components/bp5758d/bp5758d.cpp that needs a similar fix.

### Which version of ESPHome has the issue?

2023.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.3

### What platform are you using?

ESP8266

### Board

cb2l (bk72xx platform; not an option above)

### Component causing the issue

bp5758d

### Example YAML snippet

```yaml
bk72xx:
  board: cb2l

api:

ota:
  password: !secret ota_password

bp5758d:
  data_pin: P8
  clock_pin: P7
 
output:
  - platform: bp5758d
    id: bp5758d_red
    channel: 3
    current: 20
  - platform: bp5758d
    id: bp5758d_green
    channel: 2
    current: 20
  - platform: bp5758d
    id: bp5758d_blue
    channel: 1
    current: 20
  - platform: bp5758d
    id: bp5758d_cw
    channel: 5
    current: 30
  - platform: bp5758d
    id: bp5758d_ww
    channel: 4
    current: 30

light:
  - platform: rgbww
    name: Light
    red: bp5758d_red
    green: bp5758d_green
    blue: bp5758d_blue
    cold_white: bp5758d_cw
    warm_white: bp5758d_ww
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    color_interlock: true
```
