### ISSUE TITLE
Compile Error after Upgrade SPI Touch Related

### ISSUE THREAD

**Issue by corbyschmitz** [esphome/issues#4922]
### The problem

After upgrading to ESPHome 2023.9.1 (from 2023.8.3), I am receiving a compilation error for one of my devices. The configuration and code worked properly under 2023.8.3. 

### Which version of ESPHome has the issue?

2023.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.3

### What platform are you using?

ESP32

### Board

ESP32-2432S028R - i.e. Cheap Yellow Display

### Component causing the issue

SPI

### Example YAML snippet

```yaml
esphome:
  name: entryway-display
  friendly_name: entryway-display

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: <REDACTED>

ota:
  password: <REDACTED>

wifi:
  ssid: !secret wifi_iot
  password: !secret iot_password

# ============================================================ 
# ESPHome Display related setup
#
# Create a font to use, add and remove glyphs as needed. 
font:
  - file: '/config/fonts/Arimo-Regular.ttf'
    id: arimo24
    size: 24
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖ abcdefghijklmnopqrstuvwxyzåäö"
  - file: '/config/fonts/Arimo-Regular.ttf'
    id: arimo96
    size: 96
    glyphs: ":0123456789"

# Create a Home Assistant blue color
color:
  - id: ha_blue
    hex: 51c0f2
  - id: black
    hex: "ffffff"

# Create images
image:
  - file: "/config/images/cheshire-cat-bk.gif"
    id: cheshire_visible
    type: RGB24
  - file: "/config/images/cheshire-cat-invisible-bk.gif"
    id: cheshire_invisible
    type: RGB24

# ============================================================ 
# Home Assistant related setup
#
light:
  #backlight
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: backlight
    restore_mode: ALWAYS_ON
  #RGB rear
  - platform: rgb
    name: RGB
    id: led
    red: led_red
    green: led_green
    blue: led_blue
    restore_mode: ALWAYS_OFF

# ============================================================ 
# Hardware related setup
#
# Setup SPI for the display. The ESP32-2432S028R uses separate SPI buses for display and touch
spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

binary_sensor:
  - platform: touchscreen
    name: GoCrazy
    x_min: 0
    x_max: 320
    y_min: 0
    y_max: 180  

output:
  #backlight
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm
  #RGB LED
  - platform: ledc
    pin: GPIO4
    id: led_red
    inverted: true
  - platform: ledc
    pin: GPIO16
    id: led_green
    inverted: true
  - platform: ledc
    pin: GPIO17
    id: led_blue
    inverted: true

# Setup the ili9xxx platform
#
# Display is used as 240x320 by default so we rotate it to 90°
#
# We print date and time wth the strftime() function, see the ESPHome documentation to 
# format date and atime to your locale.
#
display:
  - platform: ili9xxx
    model: ili9341
    spi_id: tft
    cs_pin: GPIO15
    dc_pin: GPIO2
    rotation: 90
    id: myDisplay
    pages:
      - id: invisible
        lambda: |-
          it.fill(id(black));
          it.image(0,0, id(cheshire_invisible));
      - id: visible
        lambda: |-
          it.fill(id(black));
          it.image(0,0, id(cheshire_visible));
switch:
  - platform: template
    id: insanity
    name: insanity
    restore_mode: ALWAYS_OFF
    optimistic: true
    #turn_on_action:
    on_turn_on:
      - display.page.show: visible
      - component.update: myDisplay
    #turn_off_action:
    on_turn_off:
      - display.page.show: invisible
      - component.update: myDisplay
       
# Set up the xpt2046 touch platform
touchscreen:
  platform: xpt2046
  spi_id: touch
  cs_pin: GPIO33
  interrupt_pin: GPIO36
  update_interval: 50ms
  report_interval: 1s
  threshold: 400
  calibration_x_min: 3860
  calibration_x_max: 280
  calibration_y_min: 340
  calibration_y_max: 3860
  swap_x_y: false
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.9.1
INFO Reading configuration /config/esphome/entryway-display.yaml...
WARNING GPIO12 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO15 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO2 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing entryway-display (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
|-- noise-c @ 0.1.4
|-- SPI @ 2.0.0
Compiling .pioenvs/entryway-display/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/display/display.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/display/display_buffer.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/display/rect.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/font/font.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/ili9xxx/ili9xxx_display.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/image/image.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/ledc/ledc_output.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/light/addressable_light.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/light/automation.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/light/esp_color_correction.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/light/esp_range_view.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/light/light_call.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/light/light_json_schema.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/light/light_output.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/light/light_state.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/output/automation.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/output/float_output.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/psram/psram.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/socket/lwip_sockets_impl.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/spi/spi.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/spi/spi_arduino.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/spi/spi_esp_idf.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/switch/automation.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/switch/switch.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/template/switch/template_switch.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/wifi/wifi_component_libretiny.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/core/application.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/core/component.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/core/component_iterator.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/core/controller.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/core/entity_base.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/core/helpers.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/core/log.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/core/scheduler.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/core/string_ref.cpp.o
Compiling .pioenvs/entryway-display/src/esphome/core/util.cpp.o
Compiling .pioenvs/entryway-display/src/main.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:288:24: error: expected primary-expression before 'return'
   touch->set_interface(return new SPIClass(HSPI));
                        ^~~~~~
*** [.pioenvs/entryway-display/src/main.cpp.o] Error 1
========================= [FAILED] Took 15.57 seconds =========================
```

### Additional information

Commenting out the touchscreen and related binary sensor still results in the compile errors. Only commenting out the SPI touch interface allows compilation (without the touchscreen and binary sensor). Happy to provide any other details as needed. The configuration is based on the example yaml for the board noted here:
https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/tree/main/Examples/ESPHome
