### ISSUE TITLE
Max6675 wrong SPI frequency

### ISSUE THREAD

**Issue by zolzounet** [esphome/issues#4932]
### The problem

Max6675 always report 0°C

### Which version of ESPHome has the issue?

2023.10.0-dev

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

Xiao ESP32C3 + generic MAX6675 

### Component causing the issue

max6675

### Example YAML snippet

```yaml
esphome:
  name: fourpid      

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino

api:
  encryption:
    key: !secret clef                                

ota:
  password: !secret ota_password


packages:
  wifi: !include common/wifi.yaml

spi:
  clk_pin: GPIO8
  mosi_pin: GPIO10
  miso_pin: GPIO9

sensor:

  - platform: max6675
    name: temperature
    id: four_temp
    cs_pin: GPIO4
    accuracy_decimals: 2
    update_interval: 1s
```

### Additional information

In max6675.h replacing spi::DATA_RATE_1KHZ by spi::DATA_RATE_1MHZ fixed my problem.
