### ISSUE TITLE
bk72xx - not supporting fastled_clockless

### ISSUE THREAD

**Issue by MnM001** [esphome/issues#4935]
### The problem

Have a device with BK72xx (BK7231T chipset) - Globe Fairy Lights.
Doing the yaml for it it I get the error below:

![image](https://github.com/esphome/issues/assets/15014858/a9ea292b-f352-40bd-8a43-7c7f8e5b4d9c)

Is this going to supported soon?

Also I cant select BK72xx for the platform below so ESP32 was selected instead so I can progress with this bug report.

### Which version of ESPHome has the issue?

2023.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.3

### What platform are you using?

ESP8266

### Board

Tuya Globe Fairy Lights

### Component causing the issue

bk72xx:

### Example YAML snippet

```yaml
bk72xx:
  board: generic-bk7231t-qfn32-tuya

light:
  - platform: fastled_clockless
    chipset: WS2812b
    pin: D4
    num_leds: 115
    rgb_order: RGB
    name: "TestFairyLights"
```
