### ISSUE TITLE
Substitutions Don't Work in Package Definition

### ISSUE THREAD

**Issue by barndawgie** [esphome/issues#4939]
### The problem

I created the following configuration:
```yaml
---
substitutions:
  github_ref: main

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: ${github_ref}
    file: econet_heatpump_water_heater.yaml
```

I expected this to work, but instead get the error:
```
Not a valid git ref.
    ref: ${github_ref}
```

If I replace `${github_ref}` with `main` it works.

### Which version of ESPHome has the issue?

2023.9.1

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

m5Stack ATOM Lite

### Example YAML snippet

```yaml
---
substitutions:
  github_ref: main

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: ${github_ref}
    file: econet_heatpump_water_heater.yaml
```

### Anything in the logs that might be useful for us?

```txt
Failed config

packages: [source example-esp32.yaml:10]
  econet:
    url: https://github.com/esphome-econet/esphome-econet

    Not a valid git ref.
    ref: ${github_ref}
    file: econet_heatpump_water_heater.yaml
```
```


### Additional information

_No response_
