### ISSUE TITLE
ESP-IDF v5 + ESP32-C6: 'UART_SCLK_APB' was not declared in this scope

### ISSUE THREAD

**Issue by leoshusar** [esphome/issues#4946]
### The problem

I am trying to compile for ESP32-C6, but I'm running into a `'UART_SCLK_APB' was not declared in this scope` issue.

### Which version of ESPHome has the issue?

2023.9.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

esp32-c6-devkitc-1

### Component causing the issue

uart

### Example YAML snippet

```yaml
esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  framework:
    platform_version: https://github.com/stintel/platform-espressif32#esp32-c6-test
    type: esp-idf
    version: 5.1.1

uart:
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600
```

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/uart/uart_component_esp_idf.cpp: In member function 'uart_config_t esphome::uart::IDFUARTComponent::get_config_()':
src/esphome/components/uart/uart_component_esp_idf.cpp:51:28: error: 'UART_SCLK_APB' was not declared in this scope; did you mean 'UART_SCLK_RTC'?
   51 |   uart_config.source_clk = UART_SCLK_APB;
      |                            ^~~~~~~~~~~~~
      |                            UART_SCLK_RTC
```

### Additional information

I found the same problem [here](https://github.com/espressif/esp-idf/issues/12314#issuecomment-1736935717) and the suggestion to change `UART_SCLK_APB` to `UART_SCLK_DEFAULT` worked, I was able to compile successfully with it.

Since the logger component [already uses](https://github.com/esphome/esphome/blob/050fa0d4c17ac240abf2ebafdc27fdab1d53135d/esphome/components/logger/logger.cpp#L244) `UART_SCLK_DEFAULT`:
```cpp
#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 0, 0)
      uart_config.source_clk = UART_SCLK_DEFAULT;
#endif
```

would it be ok to just change it in the [uart component](https://github.com/esphome/esphome/blob/050fa0d4c17ac240abf2ebafdc27fdab1d53135d/esphome/components/uart/uart_component_esp_idf.cpp#L51) too?
