### ISSUE TITLE
ledc error when using with generic-bk7231t-qfn32-tuya

### ISSUE THREAD

**Issue by Gamerayers** [esphome/issues#4947]
### The problem

Using a generic-bk7231t-qfn32-tuya with the LibraTiny code works, but when I transferred over to ESPHome official with Beken support, it appears that the support for ledc for Beken chips is not available. 

Component output.ledc requires component esp32.
  platform: ledc
  id: output_component1
  pin: P7

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.0

### What platform are you using?

ESP32

### Board

WB8P

### Component causing the issue

ledc

### Example YAML snippet

```yaml
esphome:
  name: guestpole
  friendly_name: guestpole

bk72xx:
  board: generic-bk7231t-qfn32-tuya
  framework:
    version: dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ****

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Guestpole Fallback Hotspot"
    password: 
    
# Enable web server
web_server:
  port: 80

captive_portal:
   
output:
  - platform: ledc
    id: output_component1
    pin: P7
  - platform: ledc
    id: output_component2
    pin: P8
  - platform: ledc
    id: output_component3
    pin: P9
  - platform: ledc
    id: output_component4
    pin: P24

light:
  - platform: rgbw
    name: "GuestPoleLamp"
    id: guestpolelamp
    gamma_correct: 0
    red: output_component1
    green: output_component2
    blue: output_component3
    white: output_component4
    color_interlock: false
    restore_mode: RESTORE_AND_OFF
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.9.3
INFO Reading configuration /config/guestpole.yaml...
Failed config

output.ledc: [source /config/guestpole.yaml:37]
  
  Component output.ledc requires component esp32.
  platform: ledc
  id: output_component1
  pin: P7
output.ledc: [source /config/guestpole.yaml:40]
  
  Component output.ledc requires component esp32.
  platform: ledc
  id: output_component2
  pin: P8
output.ledc: [source /config/guestpole.yaml:43]
  
  Component output.ledc requires component esp32.
  platform: ledc
  id: output_component3
  pin: P9
output.ledc: [source /config/guestpole.yaml:46]
  
  Component output.ledc requires component esp32.
  platform: ledc
  id: output_component4
  pin: P24
```
