### ISSUE TITLE
Another one xtensa-lx106-elf-g++: not found

### ISSUE THREAD

**Issue by andiaa734** [esphome/issues#4959]
### The problem

Upgraded to ESPHome 2023.9.3

Host is RPi4, 
uname -a: Linux hostname 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

/boot/config.txt
[all]
arm_64bit=1

Switiching to arm_64bit=0 HA will no longer start

Home Assistant 2023.10.1
Supervisor 2023.10.0
Frontend 20231005.0 - latest

Full output from compilation:

INFO ESPHome 2023.9.3
INFO Reading configuration /config/esphome/myDevice.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing myDevice (board: esp12e; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/myDevice /src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-lx106-elf-g++: not found
Compiling .pioenvs/myDevice /src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: xtensa-lx106-elf-g++: not found
Compiling .pioenvs/myDevice/src/esphome/components/api/api_pb2.cpp.o
sh: 1: xtensa-lx106-elf-g++: not found
*** [.pioenvs/myDevice/src/esphome/components/api/api_connection.cpp.o] Error 127
Compiling .pioenvs/myDevice/src/esphome/components/api/api_pb2_service.cpp.o
*** [.pioenvs/myDevice/src/esphome/components/api/api_frame_helper.cpp.o] Error 127
*** [.pioenvs/myDevice/src/esphome/components/api/api_pb2.cpp.o] Error 127
sh: 1: xtensa-lx106-elf-g++: not found
*** [.pioenvs/myDevice/src/esphome/components/api/api_pb2_service.cpp.o] Error 127
========================== [FAILED] Took 3.30 seconds ==========================

Read almost all related issues to this error message. Some issues are for older versions of esphome and the possible solutions did not work for me.
So, any other suggestions?

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.1

### What platform are you using?

ESP8266

### Board

ESP12-F

### Component causing the issue

api

### Example YAML snippet

```yaml
substitutions:
  device_name: "ambilight1"

  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp12e


wifi:
  ssid: "myawesomewifi"
  password: "mytopsecretpassword"
  domain: .fritz.box
  
#Enable logging
logger:

#Enable Home Assistant API
api:

ota:

output:

  - platform: esp8266_pwm
    pin: GPIO5
    id: red_gpio

    
  - platform: esp8266_pwm
    pin: GPIO16
    id: blue_gpio


  - platform: esp8266_pwm
    pin: GPIO14
    id: green_gpio


  - platform: esp8266_pwm
    pin: GPIO12
    id: warm_white_gpio


  - platform: esp8266_pwm
    pin: GPIO4
    id: cold_white_gpio



light:

  - platform: rgbcct
    name: "${device_name}"
    id: ambilight
    red: red_gpio
    green: green_gpio
    blue: blue_gpio
    warm_white: warm_white_gpio
    cold_white: cold_white_gpio
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2400 K
    # In Kelvin or Mireds
    max_warm_color_temperature: 370 mireds  # Optional defaults to 500 mireds
    max_cold_color_temperature: 153 mireds  # Optional defaults to 153 mireds
    constant_brightness: false  # Optional defaults to false, make white brightness levels combine to max_combined_white_level
    max_combined_white_level: 1  # Optional defaults to 1, reduce if light is unable to support max brightness


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${device_name}"


web_server:
  port: 80
```
