### ISSUE TITLE
Duty Cycle Sensor Error on Compile - previously worked.

### ISSUE THREAD

**Issue by Brianckramer** [esphome/issues#496]
Hassio Addon on Ubuntu Virtual machine

Wemos D1 Mini

duty-cycle
https://esphome.io/components/sensor/duty_cycle.html

Compile error

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: dogfence
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "********"
  password: "********"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: duty_cycle
    pin: D1
    id: loop
    filters:
      - sliding_window_moving_average:
          window_size: 2
          send_every: 2
          
binary_sensor:
  - platform: template
    name: "Dog Fence Loop"
    device_class: problem
    lambda: |-
      if (id(loop).state > 10) {
        // Loop Alarm is ON.
        return true;
      } else {
        // Loop alarm is OFF.
        return false;
      }
```

**Logs (if applicable):**

```
src/main.cpp:11:30: error: 'esphome::duty_cycle::DutyCycleSensor* loop' redeclared as different kind of symbol
duty_cycle::DutyCycleSensor *loop;
^
In file included from src/esphome/core/esphal.h:3:0,
from src/esphome/core/helpers.h:9,
from src/esphome/components/api/util.h:3,
from src/esphome/components/api/api_message.h:4,
from src/esphome.h:2,
from src/main.cpp:3:
/root/.platformio/packages/framework-arduinoespressif8266@2.20402.4/cores/esp8266/Arduino.h:222:6: error: previous declaration of 'void loop()'
void loop(void);
^
src/main.cpp: In function 'void setup()':
src/main.cpp:104:8: error: assignment of function 'void loop()'
loop = new duty_cycle::DutyCycleSensor();
^
src/main.cpp:104:8: error: cannot convert 'esphome::duty_cycle::DutyCycleSensor*' to 'void()' in assignment
src/main.cpp:105:9: error: request for member 'set_update_interval' in 'loop', which is of non-class type 'void()'
loop->set_update_interval(60000);
^
src/main.cpp:122:27: error: no matching function for call to 'esphome::Application::register_sensor(void (&)())'
App.register_sensor(loop);
^
src/main.cpp:122:27: note: candidate is:
In file included from src/esphome.h:23:0,
from src/main.cpp:3:
src/esphome/core/application.h:52:8: note: void esphome::Application::register_sensor(esphome::sensor::Sensor*)
void register_sensor(sensor::Sensor *sensor) { this->sensors_.push_back(sensor); }
^
src/esphome/core/application.h:52:8: note:   no known conversion for argument 1 from 'void()' to 'esphome::sensor::Sensor*'
src/main.cpp:123:9: error: request for member 'set_name' in 'loop', which is of non-class type 'void()'
loop->set_name("loop");
^
src/main.cpp:124:9: error: request for member 'set_internal' in 'loop', which is of non-class type 'void()'
loop->set_internal(true);
^
src/main.cpp:125:9: error: request for member 'set_unit_of_measurement' in 'loop', which is of non-class type 'void()'
loop->set_unit_of_measurement("%");
^
src/main.cpp:126:9: error: request for member 'set_icon' in 'loop', which is of non-class type 'void()'
loop->set_icon("mdi:percent");
^
src/main.cpp:127:9: error: request for member 'set_accuracy_decimals' in 'loop', which is of non-class type 'void()'
loop->set_accuracy_decimals(1);
^
src/main.cpp: In lambda function:
src/main.cpp:133:17: error: request for member 'state' in 'loop', which is of non-class type 'void()'
if (loop->state > 10) {
^
src/main.cpp: In function 'void setup()':
src/main.cpp:141:9: error: request for member 'set_filters' in 'loop', which is of non-class type 'void()'
loop->set_filters({sensor_slidingwindowmovingaveragefilter});
^
src/main.cpp:142:9: error: request for member 'set_pin' in 'loop', which is of non-class type 'void()'
loop->set_pin(new GPIOPin(5, INPUT, false));
^
In file included from src/esphome.h:23:0,
from src/main.cpp:3:
src/esphome/core/application.h: In instantiation of 'C* esphome::Application::register_component(C*) [with C = void()]':
src/main.cpp:106:30:   required from here
src/esphome/core/application.h:81:5: error: static assertion failed: Only Component subclasses can be registered
static_assert(std::is_base_of<Component, C>::value, "Only Component subclasses can be registered");
^
src/main.cpp: In lambda function:
src/main.cpp:140:3: warning: control reaches end of non-void function [-Wreturn-type]
});
^
*** [/data/dogfence/.pioenvs/dogfence/src/main.cpp.o] Error 1
========================== [ERROR] Took 10.70 seconds ==========================


```

**Additional information and things you've tried:**
Validates fine, fails on Compile.
