### ISSUE TITLE
Add notice to configure an ESPHome device to enable Home Assistant service calls before calling a Home Assistant service.

### ISSUE THREAD

**Issue by PenKlad** [esphome/issues#4960]
### The problem

It would be helpful if the heading "homeassistant.service Action"  at 

https://esphome.io/components/api.html#homeassistant-service-action

included a sentence alerting users that in order for ESPHome to call a Home Assistant service the device must be configured to "Allow the device to make Home Assistant service calls".

Thanks

### Which version of ESPHome has the issue?

all

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

all

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

none

### Example YAML snippet

```yaml
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: True
    name: Doorbell Take A Snapshot
    id: doorbell_snapshot_button
    on_press:
      then:
        - homeassistant.service:  #NOTE: THE DEVICE MUST BE CONFIGURED TO: "Allow the device to make Home Assistant service calls"
            service: script.doorbell_snapshot
```

### Anything in the logs that might be useful for us?

```txt
N/A
```

### Additional information

IMHO it would be useful to alert users in the documentation about enabling ESPhome devices to make Home Assistant calls before calling a Home Assistant service.
