### ISSUE TITLE
Modern format is missing when downloading manually

### ISSUE THREAD

**Issue by valentapat** [esphome/issues#4963]
### The problem

When compiling a manual download, there is no Modern / Legacy menu, the compilation will start without this selection.

Home Assistant 2023.10.1
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

ESPHome 
Current version: 2023.9.3 
![B2C773F9-7693-475C-9EEA-32511C944290](https://github.com/esphome/issues/assets/17265945/8de340f0-1c34-4131-b10a-15c3705c9be9)
![38872663-21FB-470F-967F-0B6697ACF159](https://github.com/esphome/issues/assets/17265945/41e77d08-5024-41d3-ad36-46fea03a8337)

### Which version of ESPHome has the issue?

2023.9.3 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.1

### What platform are you using?

ESP8266

### Board

wemos d1 mini

### Component causing the issue

no

### Example YAML snippet

```yaml
esphome:
  name: branka

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "----------------------"

ota:
  password: "------------"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Branka Fallback Hotspot"
    password: "!secret fallback_password"

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password    

button:
  - platform: restart
    name: "Branka Restart"

switch:
  - platform: gpio
    name: "zamek branka"
    id: zamek_branka 
    pin: D7
    inverted: true

  - platform: gpio
    name: "motor brana"
    id: motor_brana
    pin: D6
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Tlacitko"
    id: tlacitko
    filters:
      - delayed_on_off: 10ms   
    on_click:
      then:
      - switch.turn_on: zamek_branka
      - delay: 500ms
      - switch.turn_off: zamek_branka  
      - mqtt.publish:
          topic: stat/branka/tlacitko
          payload: 'on'    

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
compilation is ok.
```
