### ISSUE TITLE
OTA almost impossible with remote_receiver on the ESP8266

### ISSUE THREAD

**Issue by Mat931** [esphome/issues#4964]
### The problem

I have a modified Sonoff RF Bridge with ESPHome where I connected the receiver directly to the ESP8266 according to these instructions: https://community.home-assistant.io/t/sonoff-rf-bridge-with-esphome/112676/6
Over the years the success rate of OTA updates has been decreasing to a point where they are almost impossible. As a workaround I am rebooting the ESP to safe mode before each update. I think the many GPIO interrupts from the receiver overwhelm the ESP during the update process and suggest detaching the interrupt pin before starting an OTA update.

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.1

### What platform are you using?

ESP8266

### Board

Sonoff RF Bridge (Receiver directly wired to the ESP)

### Component causing the issue

remote_receiver, ota

### Example YAML snippet

```yaml
esphome:
  name: sonoff-rfbridge
  friendly_name: "Sonoff RF Bridge"
  project:
    name: "Sonoff.RF Bridge"
    version: "R2 V1.0"

esp8266:
  board: esp8285

...

logger:
  esp8266_store_log_strings_in_flash: false
  tx_buffer_size: 1024
  baud_rate: 0

api:
  encryption:
    key: !secret api_encryption_key
  services:
    - service: beep
      variables:
        duration: int
      then:
        - rf_bridge.beep:
            duration: !lambda 'return duration;'

ota:
  id: my_ota
  password: !secret ota_password

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 19200

rf_bridge:

remote_receiver:
  - id: remote_receiver_433
    pin: 4
    filter: 100us
    tolerance: 35%
    idle: 5ms

remote_transmitter:
  pin: 5
  carrier_duty_percent: 100%

status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: remote_receiver
    receiver_id: remote_receiver_433
    name: "Remote A On"
    internal: yes
    rc_switch_raw:
      code: ${remote_a_on}
      protocol: 1
    filters:
      delayed_off: 1s
    on_press:
      - switch.template.publish:
          id: RemoteA
          state: ON
  - platform: remote_receiver
    receiver_id: remote_receiver_433
    name: "Remote A Off"
    internal: yes
    rc_switch_raw:
      code: ${remote_a_off}
      protocol: 1
    filters:
      delayed_off: 1s
    on_press:
      - switch.template.publish:
          id: RemoteA
          state: OFF

switch:
  - platform: template
    name: "Remote A"
    id: RemoteA
    optimistic: yes
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: ${remote_a_on}
          protocol:
            pulse_length: 30
          repeat:
            times: 3
            wait_time: 0s
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: ${remote_a_off}
          protocol:
            pulse_length: 300
          repeat:
            times: 3
            wait_time: 0s

sensor:
  - platform: uptime
    name: Uptime

button:
  - platform: restart
    name: "Reboot"
  - platform: safe_mode
    name: "Reboot (Safe Mode)"
```

### Anything in the logs that might be useful for us?

```txt
RAM:   [=====     ]  51.1% (used 41896 bytes from 81920 bytes)
Flash: [=====     ]  47.6% (used 486951 bytes from 1023984 bytes)
========================= [SUCCESS] Took 10.59 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of sonoff-rfbridge.local
INFO  -> 10.9.1.12
INFO Uploading /data/build/sonoff-rfbridge/.pioenvs/sonoff-rfbridge/firmware.bin (491104 bytes)
INFO Compressed to 340050 bytes
Uploading: [===                                                         ] 4% 
ERROR Error sending data: timed out
```

### Additional information

Not sure if it's related to this but connecting the wireless logger always fails if Home Assistant is already connected to the API and if the logger is connected the API connection fails.

This is the log message that appears when HA tries to connect:
```
[16:29:23][D][api:102]: Accepted <HA IP>
[16:29:23][W][api.connection:083]: <HA IP>: Socket operation failed: HANDSHAKESTATE_SETUP_FAILED errno=11
```

Trying to connect the logger when HA is connected:
```
INFO ESPHome 2023.9.3
INFO Reading configuration /config/esphome/sonoff-rfbridge.yaml...
INFO Starting log output from sonoff-rfbridge.local using esphome API
WARNING sonoff-rfbridge.local: Connection error occurred: EOF received
WARNING Can't connect to ESPHome API for sonoff-rfbridge.local: Connection closed (APIConnectionError)
INFO Trying to connect to sonoff-rfbridge.local in the background
WARNING sonoff-rfbridge.local: Connection error occurred: EOF received
WARNING sonoff-rfbridge.local: Connection error occurred: EOF received
```
