### ISSUE TITLE
Software slows down after a few hours until sensor malfunction

### ISSUE THREAD

**Issue by eddimangit** [esphome/issues#4965]
### The problem

Hi, I am running ESPHome stabely on an ESP32 board for some month in an unchanged configuration. Since the pre-last update, I face problems with the performance.
Today I added debug information about memory heap and loop time.
I cannot see a trend in the memory heap values, and loop time, but serial communication with my fingerprint sensor, or the gpio, which initiates the fingerprint read, seem to not work anymore after ~3,5 hours.

I see a slow down of log printout after a day of operation. There are also error messages saying that the communication with the fingerprint sensor is not working. I guess it is because of a general slow down of code execution.

Although my configuration is quiet large and the power values are received from the smart power meter every second via serial line, I never faced problems so far.

I know this information will not help too much to circle the issue. Please contact me, if I can help to generate more helpful analysis data!

Best regards,
Eckhard

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.1

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

not clear

### Example YAML snippet

```yaml
esphome:
  name: "rolladen-fingerprint"
  on_boot:
    priority: 200
    then:
        delay: 2s
        
esp32:
  board: nodemcu-32s


# Enable logging
logger:
  level: debug

debug:
  update_interval: 5s

psram:

# Enable Home Assistant API
api:
  password: 

  services:
  - service: enroll
    variables:
      finger_id: int
      num_scans: int
    then:
      - fingerprint_grow.enroll:
          finger_id: !lambda 'return finger_id;'
          num_scans: !lambda 'return num_scans;'
  - service: cancel_enroll
    then:
      - fingerprint_grow.cancel_enroll:
  - service: delete
    variables:
      finger_id: int
    then:
      - fingerprint_grow.delete:
          finger_id: !lambda 'return finger_id;'
  - service: delete_all
    then:
      - fingerprint_grow.delete_all:
  - service: reset_state
    then:
      - text_sensor.template.publish:
          id: fingerprint_state
          state: "No State"
ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 172.20.20.202
    gateway: 172.20.20.2
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-52Ea39"
    password: ""

captive_portal:

i2c:
  scl: GPIO22 #D1
  sda: GPIO21 #D2
  scan: True  

uart:
  - id: uart_1
    rx_pin: GPIO27 #D6
    tx_pin: GPIO26 #D5
    baud_rate: 57600
    
  - id: uart_2
    rx_pin: GPIO5 #D4
    tx_pin: GPIO17 #D3
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1
    

sml:
  id: mysml
  uart_id: uart_2


mcp23017:
  - id: 'mcp23017_hub1'
    address: 0x20
  - id: 'mcp23017_hub2'
    address: 0x21  

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"
  
  - platform: wifi_signal
    name: "Rolladen Wifi Signal"
    update_interval: 60s

  - platform: pulse_counter
    pin: 
      number: GPIO25
      mode: INPUT
    name: "Gasverbrauch"
    update_interval : 60s
    filters:
      - lambda: |-
          static float total_value = 0.0;
          total_value += x * 0.01;
          return total_value;
    unit_of_measurement: "m³"
    accuracy_decimals: 2
    icon: 'mdi:fire'

  - platform: fingerprint_grow
    fingerprint_count:
      name: "Garage Fingerprint Count"
    last_finger_id:
      name: "Garage Fingerprint Last Finger ID"
    last_confidence:
      name: "Garage Fingerprint Last Confidence"
    status:
      name: "Garage Fingerprint Status"
    capacity:
      name: "Garage Fingerprint Capacity"
    security_level:
      name: "Garage Fingerprint Security Level"

  - platform: sml
    name: "Total Energy"
    sml_id: mysml
    server_id: "090149534b0004ff3a09"
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 2
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
  
  - platform: sml
    name: "Actual Total Energy"
    sml_id: mysml
    server_id: "090149534b0004ff3a09"
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: energy
    state_class: measurement
 
  - platform: sml
    name: "Actual Energy L1"
    sml_id: mysml
    server_id: "090149534b0004ff3a09"
    obis_code: "1-0:36.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: energy
    state_class: measurement

  - platform: sml
    name: "Actual Energy L2"
    sml_id: mysml
    server_id: "090149534b0004ff3a09"
    obis_code: "1-0:56.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: energy
    state_class: measurement

  - platform: sml
    name: "Actual Energy L3"
    sml_id: mysml
    server_id: "090149534b0004ff3a09"
    obis_code: "1-0:76.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: energy
    state_class: measurement

text_sensor:
  - platform: template
    id: fingerprint_state
    name: "Garage Fingerprint State"

  - platform: sml
    name: "Manufacturer"
    sml_id: mysml
    server_id: "090149534b0004ff3a09"
    obis_code: "129-129:199.130.3"
    format: text

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

fingerprint_grow:
  password:       # Existing password, can be omitted if it's the default of 0x00
#  new_password:   # set password
#  new_password: 0x00        # set default password (unlock)

  sensing_pin: GPIO14 #D7
  uart_id: uart_1
  on_finger_scan_matched:
    - homeassistant.event:
        event: esphome.test_node_finger_scan_matched
        data:
          finger_id: !lambda 'return finger_id;'
          confidence: !lambda 'return confidence;'
    - fingerprint_grow.aura_led_control:
        state: BREATHING
        speed: 200
        color: BLUE
        count: 1
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Authorized finger"
  on_finger_scan_unmatched:
    - homeassistant.event:
        event: esphome.test_node_finger_scan_unmatched
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 2
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Unauthorized finger"
  on_enrollment_scan:
    - homeassistant.event:
        event: esphome.test_node_enrollment_scan
        data:
          finger_id: !lambda 'return finger_id;'
          scan_num: !lambda 'return scan_num;' 
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: BLUE
        count: 2
    - fingerprint_grow.aura_led_control:
        state: ALWAYS_ON
        speed: 0
        color: PURPLE
        count: 0
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Finger scanned"
  on_enrollment_done:
    - homeassistant.event:
        event: esphome.test_node_enrollment_done
        data:
          finger_id: !lambda 'return finger_id;'
    - fingerprint_grow.aura_led_control:
        state: BREATHING
        speed: 100
        color: BLUE
        count: 2
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Enrolled fingerprint"
  on_enrollment_failed:
    - homeassistant.event:
        event: esphome.test_node_enrollment_failed
        data:
          finger_id: !lambda 'return finger_id;'
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 4
    - text_sensor.template.publish:
        id: fingerprint_state
        state: "Failed to enroll fingerprint"

switch:
  - platform: restart
    name: "Rolladen-Fingerprint Restart"
    
    #mcp23017 shuttercontrol main power on
  - platform: gpio
    name: "r_power"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 7
      inverted: true
      mode:
        output: true
    id: ri_power

#mc23017 
  - platform: gpio
    name: "Gäste WC UP"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 8
      inverted: true
      mode:
        output: true
    id: gwc_up
      

#mc23017 
  - platform: gpio
    name: "Gäste WC DN"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 8
      inverted: true
      mode:
        output: true
    id: gwc_dn
      
#mc23017 
  - platform: gpio
    name: "Küche Fenster UP"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 9
      inverted: true
      mode:
        output: true
    id: kufe_up
      
#mc23017 
  - platform: gpio
    name: "Küche Fenster DN"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 9
      inverted: true
      mode:
        output: true
    id: kufe_dn
      

#mc23017 
  - platform: gpio
    name: "Küche Tür UP"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 10
      inverted: true
      mode:
        output: true
    id: kutu_up
      

#mc23017 
  - platform: gpio
    name: "Küche Tür DN"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 10
      inverted: true
      mode:
        output: true
    id: kutu_dn
      

#mc23017 
  - platform: gpio
    name: "Wohnzimmer Fenster UP"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 11
      inverted: true
      mode:
        output: true
    id: wofe_up
      

#mc23017 
  - platform: gpio
    name: "Wohnzimmer Fenster DN"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 11
      inverted: true
      mode:
        output: true
    id: wofe_dn
      

#mc23017 
  - platform: gpio
    name: "Wohnzimmer Tür links UP"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 12
      inverted: true
      mode:
        output: true
    id: wotuli_up
      

#mc23017 
  - platform: gpio
    name: "Wohnzimmer Tür links DN"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 12
      inverted: true
      mode:
        output: true
    id: wotuli_dn
      

#mc23017 
  - platform: gpio
    name: "Wohnzimmer Tür rechts UP"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 13
      inverted: true
      mode:
        output: true
    id: woture_up
      

#mc23017 
  - platform: gpio
    name: "Wohnzimmer Tür rechts DN"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 13
      inverted: true
      mode:
        output: true
    id: woture_dn
      

#mc23017 
  - platform: gpio
    name: "OG Bad Fenster Garage UP"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 14
      inverted: true
      mode:
        output: true
    id: ogbadga_up
      

#mc23017 
  - platform: gpio
    name: "OG Bad Fenster Garage DN"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 14
      inverted: true
      mode:
        output: true
    id: ogbadga_dn
      

#mc23017 
  - platform: gpio
    name: "OG Annika Fenster Garage UP"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 15
      inverted: true
      mode:
        output: true
    id: oganfega_up
      

#mc23017 
  - platform: gpio
    name: "OG Annika Fenster Garage DN"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 15
      inverted: true
      mode:
        output: true
    id: oganfega_dn
      


#mc23017 
  - platform: gpio
    name: "DG Niklas Fenster Sandbirke UP"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 0
      inverted: true
      mode:
        output: true
    id: dgnifesa_up
  
#mc23017 
  - platform: gpio
    name: "DG Niklas Fenster Sandbirke DN"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 0
      inverted: true
      mode:
        output: true
    id: dgnifesa_dn
      

#mc23017 
  - platform: gpio
    name: "DG Niklas Fenster Garage UP"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 1
      inverted: true
      mode:
        output: true
    id: dgnifega_up
      

#mc23017 
  - platform: gpio
    name: "DG Niklas Fenster Garage DN"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 1
      inverted: true
      mode:
        output: true
    id: dgnifega_dn
      

#mc23017 
  - platform: gpio
    name: "Garage Fenster UP"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 2
      inverted: true
      mode:
        output: true
    id: gafe_up
      

#mc23017 
  - platform: gpio
    name: "Garage Fenster DN"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 2
      inverted: true
      mode:
        output: true
    id: gafe_dn
      

#mc23017 
  - platform: gpio
    name: "DG Niklas Dachfenster UP"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 4
      inverted: true
      mode:
        output: true
    id: dgnidafe_up
      

#mc23017 
  - platform: gpio
    name: "DG Niklas Dachfenster DN"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 4
      inverted: true
      mode:
        output: true
    id: dgnidafe_dn

  
#mc23017 
  - platform: gpio
    name: "Treppe Fenster unten UP"
    pin:
      mcp23xxx: mcp23017_hub1
      number: 3
      inverted: true
      mode:
        output: true
    id: treFeunt_up
  
#mc23017 
  - platform: gpio
    name: "Treppe Fenster unten DN"
    pin:
      mcp23xxx: mcp23017_hub2
      number: 3
      inverted: true
      mode:
        output: true
    id: trefeunt_dn
```
