### ISSUE TITLE
Web_server not showing everything configured in yaml

### ISSUE THREAD

**Issue by evlo** [esphome/issues#4968]
### The problem

For the XML bellow I get this displayed - so entries like debug or version are missing

![image](https://github.com/esphome/issues/assets/8813196/5db9a114-53ac-452d-978f-22442ab86b64)

happens of multiple devices using this same config

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.1

### What platform are you using?

ESP8266

### Board

local bytes plug

### Component causing the issue

web_server

### Example YAML snippet

```yaml
substitutions:
  device_name: EH Plug 04
  hostname: eh-plug-04
  device_id: eh_plug-04
  comment: "Plug 04, Local bytes"  
  main_icon: "power-socket"
  relay_restore_mode: RESTORE_DEFAULT_ON

esphome:
  name: $hostname
  comment: $comment

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${hostname} Fallback
  #use_address: eh-plug-minimal.local

esp8266:
  board: esp01_1m
  restore_from_flash: true

time:
  - platform: sntp
    timezone: Europe/Prague

web_server:
ota:

debug:

############################################################################
logger:
  level: VERBOSE
  baud_rate: 0
  logs:
    aioesphomeapi.connection: debug
############################################################################
text_sensor:
  - platform: version
    name: "ESPHome"
    id: esp_version
    hide_timestamp: true
    icon: "mdi:numeric"
    internal: True
  - platform: wifi_info
    ip_address:
      name: "IP"
      id: ip
      disabled_by_default: False
      icon: "mdi:wifi-settings"
      internal: True
    mac_address:
      name: "MAC"
      id: mac
      icon: "mdi:wifi-marker"
      internal: True
    scan_results:
      name: "Last wifi scan"
      icon: "mdi:wifi-sync"
      internal: True
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

globals:
  - id: totalEnergy
    type: float
    restore_value: yes
    initial_value: '0.0' 
  - id: voltage_multiply
    type: float
    restore_value: true
    initial_value: "0.3"    
  - id: power_multiply 
    type: float
    restore_value: true
    initial_value: "0.133"    
  - id: current_multiply 
    type: float
    restore_value: true
    initial_value: "0.805"
############################################################################

api:
 
binary_sensor:
  # Push Button (Toggles Relay When Pressed)
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "${device_name} Button"
    on_click:

      - max_length: 1s
        then:
          if:
            condition:
              switch.is_off: disable_button
            then:
              switch.toggle: relay
      
      - min_length: 1.5s
        max_length: 5s
        then:
          switch.toggle: disable_led
      
      - min_length: 8s
        max_length: 12s
        then:
          switch.toggle: disable_button
          
  - platform: status
    name: "${device_name} Server Status"

switch:
  # Relay (As Switch)
  - platform: gpio
    name: "${device_name}"
    icon: "mdi:${main_icon}"
    pin: GPIO14
    id: relay
    restore_mode: "${relay_restore_mode}"
    on_turn_on:
      if:
        condition:
          switch.is_off: disable_led
        then:
          light.turn_on:
            id: led
    on_turn_off:
      - light.turn_off:
          id: led
  
  - platform: template
    name: "${device_name} Disable LED"
    id: disable_led
    icon: "mdi:led-variant-off"
    #restore_state: true
    restore_mode: "${relay_restore_mode}"
    optimistic: true
    on_turn_on:
      - light.turn_off: led
      - delay: 0.1s
      - light.turn_on: led
      - delay: 0.1s
      - light.turn_off: led
      - delay: 0.1s
      - light.turn_on: led
      - delay: 0.1s
      - light.turn_off: led
    on_turn_off:
      - light.turn_on: led
      - delay: 0.1s
      - light.turn_off: led
      - delay: 0.1s
      - light.turn_on: led
      - delay: 0.1s
      - light.turn_off: led
      - delay: 0.7s
      - if:
          condition:
            switch.is_on: relay
          then:
            light.turn_on: led


  
  - platform: template
    name: "${device_name} Disable Button"
    id: disable_button
    icon: "mdi:toggle-switch-off-outline"
    #restore_state: true
    restore_mode: "${relay_restore_mode}"
    optimistic: true
    on_turn_on:
      #Flash thrice
      - light.turn_off: led
      - delay: 0.15s
      - light.turn_on: led
      - delay: 0.15s
      - light.turn_off: led
      - delay: 0.15s
      - light.turn_on: led
      - delay: 0.15s
      - light.turn_off: led
      - delay: 0.15s
      - light.turn_on: led
      - delay: 0.15s
        #Final state
      - if:
          condition:
            switch.is_off: relay
          then:
            light.turn_off: led
    on_turn_off:
      - light.turn_on: led
      - delay: 0.15s
      - light.turn_off: led
      - delay: 0.15s
      - light.turn_on: led
      - delay: 0.15s
      - light.turn_off: led
      - delay: 0.15s
      - light.turn_on: led
      - delay: 0.15s
      - light.turn_off: led
      - delay: 0.7s
      - if:
          condition:
            switch.is_on: relay
          then:
            light.turn_on: led

sensor:
  - platform: wifi_signal
    name: "${device_name} WiFi Status"
    update_interval: 60s
    
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO4
    cf1_pin: GPIO5
    change_mode_every: 3
    update_interval: 6s
    
    voltage:
      name: "${device_name} Voltage"
      id: voltage
      unit_of_measurement: V
      accuracy_decimals: 1
      filters:
        - lambda: return x * id(voltage_multiply);
        
    power:
      name: "${device_name} Power"
      id: power
      unit_of_measurement: W
      accuracy_decimals: 0
      filters:
        - lambda: return x * id(power_multiply);
        
    current:
      name: "${device_name} Current"
      id: current
      unit_of_measurement: A
      accuracy_decimals: 3
      filters:
        - lambda: return x * id(current_multiply);
          
    # Total daily energy sensor
    energy:
      name: "Energy"
      id: energy
      unit_of_measurement: kWh
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      on_value:
        then:
          - lambda: |-
              static float previous_energy_value = 0.0;
              float current_energy_value = id(energy).state;
              id(totalEnergy) += current_energy_value - previous_energy_value;
              previous_energy_value = current_energy_value;
  - platform: template
    name: "Total Energy"
    id: total_energy
    unit_of_measurement: kWh
    device_class: "energy"
    state_class: "total_increasing"
    icon: "mdi:lightning-bolt"
    accuracy_decimals: 3
    lambda: |-
      return id(totalEnergy);
    update_interval: 10s

  - platform: total_daily_energy
    name: "Total Daily Energy"
    id: daily_energy
    restore: true
    power_id: power
    unit_of_measurement: kWh
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    icon: mdi:lightning-bolt-outline

output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: binary
    output: state_led
    id: led
```
```


### Anything in the logs that might be useful for us?

```txt
In LOG everything mising is visible and reported i.e `'EH Plug 04 WiFi Status': Sending state -53.00000 dBm with 0 decimals of accuracy`
```

### Additional information

Might be just issue with yaml I'm using

**Comment by evlo** [comment]
fixed the issue, so internal explicitly false, disabled_by_default True, and removed include_internal: True from webserver config
```
web_server:

text_sensor:
  - platform: version
    name: "ESPHome"
    id: esp_version
    hide_timestamp: true
    icon: "mdi:numeric"
    internal: False
    disabled_by_default: True
  - platform: wifi_info
    ip_address:
      name: "IP"
      id: ip
      icon: "mdi:wifi-settings"
      internal: False
      disabled_by_default: True
    mac_address:
      name: "MAC"
      id: mac
      icon: "mdi:wifi-marker"
      internal: False
      disabled_by_default: True
    scan_results:
      name: "Last wifi scan"
      icon: "mdi:wifi-sync"
      internal: False
      disabled_by_default: True
  - platform: debug
    device:
      name: "Device Info"
      internal: False
      disabled_by_default: True
    reset_reason:
      name: "Reset Reason"
      internal: False
      disabled_by_default: True
```
