### ISSUE TITLE
Bootlooping and freezing when using wifi and esp32_ble_tracker on NodeMCU-32s

### ISSUE THREAD

**Issue by AlecTBM** [esphome/issues#4972]
### The problem

When using wifi and esp32_ble_tracker and climate ir on NodeMCU-32s (ESP-WROOM-32) , it bootloops when connecting to wifi on 2023.9.3 and 2023.8.3
I am not using HA api, but are using MQTT.
When removing either wifi, esp32_ble_tracker or climate, the rest works.

One thing I notice is that the flash is over 90% full. Is this a case of just packing to much in?

### Which version of ESPHome has the issue?

2023.8 and 2023.9

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

Unknown, possible wifi, esp32_ble_tracker or ir climate

### Example YAML snippet

```yaml
esphome:
  name: bletest
  on_boot:
  - priority: -100
    then:
      - light.turn_on: status
      - delay: 10s
      - esp32_ble_tracker.start_scan:
          continuous: true

esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    
esp32_ble_tracker:
  scan_parameters:
    continuous: false

# Enable logging
logger:
  level: debug

web_server:

# MQTT
mqtt:
  broker: !secret mqtt_broker
  id: mqtt_client
ota:
  password: "6090fa5ac07128a2beecd1cb2c30d9d8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "bletest Fallback Hotspot"
    password: "A030B7911264"

captive_portal:

remote_transmitter:
  pin: 
    number: GPIO23
    inverted: false
  carrier_duty_percent: 50%


climate:
  - platform: heatpumpir
    protocol: mitsubishi_fd
    name: "Stue"
    horizontal_default: "auto"
    vertical_default: "auto"
    max_temperature: 31
    min_temperature: 16

debug:
  update_interval: 5s

light:
  - platform: status_led
    id: status
    name: "Status"
    pin: GPIO2

sensor:
  - platform: uptime
    name: Uptime Sensor
    update_interval: 5s

  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
  
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:29:C9:13"
    temperature:
      name: "Utebod Temperature"
    humidity:
      name: "Utebod Humidity"
    battery_level:
      name: "Utebod Battery-Level"
    battery_voltage:
      name: "Utebod Battery-Voltage"

  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:5B:98:67"
    temperature:
      name: "Bad Temperature"
    humidity:
      name: "Bad Humidity"
    battery_level:
      name: "Bad Battery-Level"
    battery_voltage:
      name: "Bad Battery-Voltage"

  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:48:12:FE"
    temperature:
      name: "Soverom Temperature"
    humidity:
      name: "Soverom Humidity"
    battery_level:
      name: "Soverom Battery-Level"
    battery_voltage:
      name: "Soverom Battery-Voltage"
        

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"
  - platform: version
    name: "ESPHome Version"
```

### Additional information

I have for over a year used some NodeMCU-32s with ESPHome, Mija BLE thermometers (pvvx_mithermometer) and climate component controlling an AC over IR.
In september this year, I was doing an update of these that then had worked without issue since november 2022 (the last time I had updated them). But I could not get them to boot up properly. After some testing I found out that if I removed the ble_tracker parts, it worked. At the time this was on 2023.8.3, and on 2023.7 it worked, but was unstable (reboots after a few hours), I then went back and did some test and found the last version I could find stable was 2023.3.

I have now done some more tests and logging all the versions from 2022.12 to 2023.9.3, and I just get bootlooping with the configuration that works on 2023.3.

Original yaml:
[bletest original.txt](https://github.com/esphome/issues/files/12885606/bletest.original.txt)
Log file showing the compiling on 2023.9.3 and the ota log of the bootloop.
[logs_bletest_run 2023.9.3 compilinf + ota log bootloop.txt](https://github.com/esphome/issues/files/12885613/logs_bletest_run.2023.9.3.compilinf.%2B.ota.log.bootloop.txt)
Log file showing the serial log while it bootloops.
[logs 2023.9.3 serial log bootloop.txt](https://github.com/esphome/issues/files/12885614/logs.2023.9.3.serial.log.bootloop.txt)

I tried to remove the BLE components, and then the rest worked. Yaml:
[bletest without BLE.txt](https://github.com/esphome/issues/files/12885607/bletest.without.BLE.txt)
Log file from serial showing normal operation:
[bletest_logs 2023.9.3 serial log without BLE.txt](https://github.com/esphome/issues/files/12885629/bletest_logs.2023.9.3.serial.log.without.BLE.txt)

I then added back the BLE and removed the wifi, it also worked. Yaml:
[bletest without wifi.txt](https://github.com/esphome/issues/files/12885608/bletest.without.wifi.txt)
Log from serial over that the device receive everything over BLE as it should.
[bletest_logs 2023.9.3 serial log without WIFI.txt](https://github.com/esphome/issues/files/12885636/bletest_logs.2023.9.3.serial.log.without.WIFI.txt)

For being complete, here is a log over compiling and OTA log of everything working okey in 2023.3:
[logs_bletest_run 2023.3.2 compiling + OTA log.txt](https://github.com/esphome/issues/files/12885652/logs_bletest_run.2023.3.2.compiling.%2B.OTA.log.txt)
