### ISSUE TITLE
ESP32 does not boot when x_grid > duration in graph component

### ISSUE THREAD

**Issue by bucovaina** [esphome/issues#4981]
### The problem

Edge case, I know. But by ESP32 with an ILI9341 gets stuck in a boot loop (I think) when I define a graph where x_grid is larger than duration in the graph component.

I totally agree that this is a stupid configuration, I accidentally did it so. The configuration passed though and was uploaded to the ESP with a boot loop as a result.

It would be nice if the `esphome run` command would do a check on this and bail out if it found out that x_grid > duration in any graph.

### Which version of ESPHome has the issue?

2023.09

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

I don't use Home Assistant with this ESP, api is disabled due to MQTT component

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

graph

### Example YAML snippet

```yaml
graph:
  - id: p1port
    duration: 1hours
    x_grid: 10hours
    y_grid: 1.0 
    width: 240 
    height: 110 
    traces:
      - sensor: injection
        line_type: SOLID
        line_thickness: 5
        color: yellow
      - sensor: usage
        line_type: SOLID
        line_thickness: 5
        color: red 
  - id: boiler
    duration: 1hours
    x_grid: 10hours
    y_grid: 1000.0
    width: 240 
    height: 110 
    traces:
      - sensor: boilerpower
        line_type: SOLID
        line_thickness: 3
        color: blue
```
