### ISSUE TITLE
Servo component seems to ignore transition length

### ISSUE THREAD

**Issue by tuct** [esphome/issues#4984]
### The problem

When using the servo component, it seems the transition length is ignored / not working.
Regardless of what I set, I see in the logs the reached a new position in the same sec as it was set.
Here is a link to similar reportings:
https://community.home-assistant.io/t/servo-transition-length-2s-not-working/509970/4

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

none

### What platform are you using?

ESP32

### Board

esp32-devkit4

### Component causing the issue

servo

### Example YAML snippet

```yaml
number:
  - platform: template
    id: servo_pos
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 10
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: lid_servo
            level: !lambda 'return x / 100.0;'
        
servo:
  - id: lid_servo
    output: pwm_servo
    transition_length: 50s
    auto_detach_time: 1s
```

### Anything in the logs that might be useful for us?

```txt
https://esphome.io/api/servo_8cpp_source   
Those lines seem to be reached without delay
   if (this->target_value_ == this->current_value_ && this->state_ == STATE_ATTACHED) {
     this->state_ = STATE_TARGET_REACHED;
     this->start_millis_ = millis();  // set current stamp for potential auto_detach_time_ check
     ESP_LOGD(TAG, "Servo reached target");
   }
So i expect something wrong here:
   if (this->target_value_ != this->current_value_ && this->state_ == STATE_ATTACHED) {
     if (this->transition_length_) {
       float new_value;
       float travel_diff = this->target_value_ - this->source_value_;
       uint32_t target_runtime = abs((int) ((travel_diff) * this->transition_length_ * 1.0f / 2.0f));
       uint32_t current_runtime = millis() - this->start_millis_;
       float percentage_run = current_runtime * 1.0f / target_runtime * 1.0f;
       if (percentage_run > 1.0f) {
         percentage_run = 1.0f;
       }
       new_value = this->target_value_ - (1.0f - percentage_run) * (this->target_value_ - this->source_value_);
       this->internal_write(new_value);
     } else {
       this->internal_write(this->target_value_);
     }
   }
```
