### ISSUE TITLE
Web Server number slider dpi problem

### ISSUE THREAD

**Issue by samuelolteanu** [esphome/issues#4988]
### The problem

Both on windows and android, number sliders don't show correctly unless I zoom way out.

![Captură](https://github.com/esphome/issues/assets/85267083/90c42702-20c6-44bb-b2a1-3776b7f3afcc)
![Screenshot_20231016_052410_Kiwi Browser](https://github.com/esphome/issues/assets/85267083/e73a3d9d-1e69-4a42-8092-8f0cb9de477b)

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.3

### What platform are you using?

ESP8266

### Component causing the issue

web_server

### Example YAML snippet

```yaml
- platform: template
    name: Servo Control
    id: servo_number
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: True
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
