### ISSUE TITLE
ESPHome device 'visit' link has incorrect IP 

### ISSUE THREAD

**Issue by balvant813** [esphome/issues#4993]
### The problem

Visit link in ESPHome device does not have correct ip. This happens IP is defined as substitution (and/or) used in !include yaml code.  e.g. ip is defined as 192.168.20.032, visit link opens at 192.168.20.26!

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
------------- esp32bleproxy-032.yaml -----------------
substitutions:
 device_name: esp32bleproxy-032-bpoff # hostname & entity_id
 transition_length: 1.5s # transition when turning on/off
 ip_address: 192.168.20.032
esphome:
  name:  ${device_name}
  friendly_name:  ${device_name}
esp32:
  board: esp32dev
  framework:
    type: arduino
# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxx"
wifi: !include wifi_20.yaml

------ wifi_20.yaml ---------------
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: ${ip_address}
  manual_ip:
    static_ip: ${ip_address}
    gateway: 192.168.20.1
    subnet: 255.255.255.0
    dns1: 192.168.20.1
```
