### ISSUE TITLE
Platformio board_dir location unreachable after removing /config/esphome/.esphome directory?

### ISSUE THREAD

**Issue by Goodwillson** [esphome/issues#4994]
### The problem

In previous versions was possible to save custom board configuration into /config/esphome/.esphome/build/[your-esphome-device]/boards directory. This location does not exist anymore. I didnt find path where I could access location which platformio looks for the configuration files by default. I guess it all happens inside plugin container now, which is not accessible from HassOS. I tried to set full path like boards_dir: /config/esphome/boards, but that doesnt work either. How I could make it working again while keeping the boards condiguration outside of yaml file?

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2023.6.1

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
esphome:
  name: liligo-t5-47-epaper-plus
  platformio_options:
    board_dir: boards
    #include https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/master/platformio/boards/lilygo-t5-47-plus.json as custom board
    board: lilygo-t5-47-plus

esp32:
  variant: esp32s3
  board: lilygo-t5-47-plus
```
