### ISSUE TITLE
Error in esphomeyaml with output custom component

### ISSUE THREAD

**Issue by ProASV** [esphome/issues#50]
Python 2.7.15
Windows 10

Example one:
esp32_test.yaml :

```
esphomeyaml:
  name: esp32_test
  platform: ESP32
  board: esp32dev

wifi:
  ssid: 'TEST'
  password: 'TESTTESTTEST'

logger:
api:
ota:

output:
  - platform: custom
    type: float
    lambda: |-
      return 0;

    outputs:
      id: custom_float

```

Compiling:

```
esphomeyaml esp32_test.yaml compile
INFO Reading configuration...
Failed config

output.custom: [source esp32_test.yaml:18]
  platform: custom

  [type] is an invalid option for [output.custom].
  type: float
  lambda: return 0;

  'platform' is a required option for [outputs].
  outputs:  [source esp32_test.yaml:24]
    id: custom_float

```
Example two:

```
esphomeyaml:
  name: esp32_test
  platform: ESP32
  board: esp32dev

wifi:
  ssid: 'TEST'
  password: 'TESTTESTTEST'

logger:

# Enable Home Assistant API
api:

ota:


output:
  - platform: custom
#    type: float
    lambda: |-
      return 0;

    outputs:
      id: custom_float

```

Compiling:

```
esphomeyaml esp32_test.yaml compile

INFO Reading configuration...
Failed config

output.custom: [source esp32_test.yaml:18]

  type not specified!. Got '{"platform": "custom", "lambda": "return 0;", "outputs": {"id": "custom_float"}}'
  platform: custom
  lambda: return 0;
  outputs:
    id: custom_float
```

**Comment by brandond** [comment]
What version of esphome are you using? This passes config validation for me, although it's not valid as the lambda needs to return an instance of your custom component, not a value.

```yaml
output:
  - platform: custom
    type: float
    lambda: |-
      return nullptr;
    outputs:
      id: custom_float
```
