### ISSUE TITLE
error compiling yaml with touchscreen 

### ISSUE THREAD

**Issue by lecrams** [esphome/issues#5002]
### The problem

When I try to build a yaml which contains code for a touch controller I get the following error: 
/config/esphome/ESPTouchTFT.yaml:225:16: error: base operand of '->' has non-pointer type 'esphome::touchscreen::TouchPoint'

the yaml code to get this error is:
# Set up the xpt2046 touch platform
touchscreen:
  platform: xpt2046
  spi_id: touch
  cs_pin: GPIO33
  interrupt_pin: GPIO36
  update_interval: 50ms
  report_interval: 1s
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              id(touch).x,
              id(touch).y,
              id(touch).x_raw,
              id(touch).y_raw
              );  
  threshold: 400
  calibration_x_min: 3860
  calibration_x_max: 280
  calibration_y_min: 340
  calibration_y_max: 3860
  swap_x_y: false      

What am I doing wrong? The yaml code was taken from:
https://esphome.io/components/touchscreen/xpt2046#configuration-variables.

### Which version of ESPHome has the issue?

2023.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.3

### What platform are you using?

ESP32

### Component causing the issue

yellow tft

### Example YAML snippet

```yaml
# Set up the xpt2046 touch platform
touchscreen:
  platform: xpt2046
  spi_id: touch
  cs_pin: GPIO33
  interrupt_pin: GPIO36
  update_interval: 50ms
  report_interval: 1s
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              id(touch).x,
              id(touch).y,
              id(touch).x_raw,
              id(touch).y_raw
              );  
  threshold: 400
  calibration_x_min: 3860
  calibration_x_max: 280
  calibration_y_min: 340
  calibration_y_max: 3860
  swap_x_y: false
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/esp-touch-tft/src/main.cpp.o
In file included from src/esphome/components/api/proto.h:4,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/config/esphome/ESPTouchTFT.yaml: In lambda function:
/config/esphome/ESPTouchTFT.yaml:225:16: error: base operand of '->' has non-pointer type 'esphome::touchscreen::TouchPoint'
               id(touch).x,
                ^~
src/esphome/core/log.h:108:88: note: in definition of macro 'esph_log_i'
   esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                        ^~~~~~~~~~~
/config/esphome/ESPTouchTFT.yaml:224:7: note: in expansion of macro 'ESP_LOGI'
           ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
       ^   ~~~~
/config/esphome/ESPTouchTFT.yaml:226:16: error: base operand of '->' has non-pointer type 'esphome::touchscreen::TouchPoint'
               id(touch).y,
                ^~
src/esphome/core/log.h:108:88: note: in definition of macro 'esph_log_i'
   esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                        ^~~~~~~~~~~
/config/esphome/ESPTouchTFT.yaml:224:7: note: in expansion of macro 'ESP_LOGI'
           ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
       ^   ~~~~
/config/esphome/ESPTouchTFT.yaml:227:16: error: base operand of '->' has non-pointer type 'esphome::touchscreen::TouchPoint'
               id(touch).x_raw,
                ^~
src/esphome/core/log.h:108:88: note: in definition of macro 'esph_log_i'
   esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                        ^~~~~~~~~~~
/config/esphome/ESPTouchTFT.yaml:224:7: note: in expansion of macro 'ESP_LOGI'
           ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
       ^   ~~~~
/config/esphome/ESPTouchTFT.yaml:228:16: error: base operand of '->' has non-pointer type 'esphome::touchscreen::TouchPoint'
               id(touch).y_raw
                ^~
src/esphome/core/log.h:108:88: note: in definition of macro 'esph_log_i'
   esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                        ^~~~~~~~~~~
/config/esphome/ESPTouchTFT.yaml:224:7: note: in expansion of macro 'ESP_LOGI'
           ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
       ^   ~~~~
*** [.pioenvs/esp-touch-tft/src/main.cpp.o] Error 1
```
