### ISSUE TITLE
entity_category: config is not recognized anymore after 2023.10.0 upgrade

### ISSUE THREAD

**Issue by anatoly-savchenkov** [esphome/issues#5004]
### The problem

`entity_category: config` is not recognized anymore for sensors (template sensor in my case) after 2023.10 upgrade. Error is 
````
Unknown value 'config', valid options are '', 'diagnostic'.
````

### Which version of ESPHome has the issue?

2023.10.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
sensor:
  - platform: template
    name: ${friendly_devicename} NTC Reference Resistance
    accuracy_decimals: 0
    unit_of_measurement: "Ω"
    entity_category: config
    icon: "mdi:flash"
    lambda: |-
      return ${ntc_ref_resistance};
```

### Anything in the logs that might be useful for us?

```txt
sensor.template: [source lytko-101-v2.yaml:530]
platform: template
name: Bathroom Heating Resistance
accuracy_decimals: 1
unit_of_measurement: Ω
Unknown value 'config', valid options are '', 'diagnostic'.
entity_category: config
update_interval: 60s
icon: mdi:heat-wave
lambda: return 813.8;
```
