### ISSUE TITLE
ssd1306_i2c does not work after upgrade to 2023.10.1

### ISSUE THREAD

**Issue by erik3rik** [esphome/issues#5008]
### The problem

When upgrading to 2023.10.1, my display gets blank.

I use:

```

i2c:
  sda: GPIO21
  scl: GPIO22
  frequency: 400kHz
  scan: true
  
display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    contrast: 35%
    id: oled_display
    flip_y: true
    pages: []     # pages exist, but excluded for the sake of minimalism

```

When rolling back to 2923.9.3 the display starts working again.

### Which version of ESPHome has the issue?

2023.10.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.0

### What platform are you using?

ESP32

### Board

az-delivery-devkit-v4

### Component causing the issue

display/i2c

### Example YAML snippet

```yaml
i2c:
  sda: GPIO21
  scl: GPIO22
  frequency: 400kHz
  scan: true
  
display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    contrast: 35%
    id: oled_display
    flip_y: true
    pages: []     # pages exist, but excluded for the sake of minimalism
```

### Anything in the logs that might be useful for us?

```txt
No errors in log. Logs look identical for 2023.10.1 and 2023.9.3, but the display is only working in 2023.9.3.
```
