### ISSUE TITLE
Problem with turning on the "heating/cooling" mode when pressing the "SMART" button on the Whirlpool (Galactic) DG11J1-91 IR remote control

### ISSUE THREAD

**Issue by TokarevSergey** [esphome/issues#5014]
### The problem

At this stage the situation is like this.

If the air conditioner is turned off.
and press "SMART" on the remote control
![image](https://github.com/esphome/issues/assets/98225056/6d20be8b-856d-42b9-917c-862069b7ce84)

Then the air conditioner turns on
![image](https://github.com/esphome/issues/assets/98225056/c2ce94db-7f03-4da8-b839-645b21934bd5)

And in the Home Assistant integration the following happens: the temperature is set to 23 degrees and the “Heating/Cooling” mode does not turn on.
![image](https://github.com/esphome/issues/assets/98225056/cc0ccbd7-82e3-472e-bddc-2e70089a71c6)

after clicking any of these buttons
![image](https://github.com/esphome/issues/assets/98225056/dcd4b2e8-64c1-4c37-9da9-d829055c5165)

Then the air conditioner turns off
![image](https://github.com/esphome/issues/assets/98225056/7d20dc47-b8dd-4ba6-b28c-5f59b95b4ac3)

And what happens when you integrate Home Assistant is that it turns on.
![image](https://github.com/esphome/issues/assets/98225056/509d5cb7-1924-429e-9818-7f4075bed237)

And if you continue to press the buttons on the integration board, the mode changes, but the air conditioner does not turn on until you turn it on from the remote control.
![image](https://github.com/esphome/issues/assets/98225056/3ab3119e-bc8a-45c2-a8e9-b76a8fd39617)

Please help me figure it out. Below is my configuration, maybe I configured something wrong?

esphome:
  name: s08ir
  platform: ESP8266
  board: esp_wroom_02

wifi:
  ssid: "DomWiFi"
  password: "Dom1WiFi2"
  fast_connect: true

logger:
  level: DEBUG

api:
  password: "s08ir"

ota:
  password: "s08ir"

status_led:
  pin:
    number: GPIO4

remote_receiver:
  id: "s08_receiver"
  pin: 
    number: GPIO5
    inverted: true
  dump: all

remote_transmitter:
  id: "s08_transmitter"
  pin: 
    number: GPIO14
    inverted: false
  carrier_duty_percent: 55%
  

binary_sensor:
  - platform: gpio
    name: "s08_button"
    id: "s08_button"
    pin:
      number: GPIO13
      inverted: true
    internal: true

sensor:
  - platform: homeassistant
    id: current_temperature
    entity_id: sensor.ble_temperature_e72e0172f902
    device_class: temperature
    state_class: measurement

climate:
  - platform: whirlpool
    name: "Кондиционер спальня"
    model: DG11J1-91
    id: "konditsioner_spalnya"
    sensor: current_temperature
    receiver_id: "s08_receiver"
    transmitter_id: "s08_transmitter"
    visual:
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C

### Which version of ESPHome has the issue?

2023.10.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.3

### What platform are you using?

ESP8266

### Board

Universal IR remote control Smart9 S08 based on esp8266

### Component causing the issue

Climate Components / IR Remote Climate / whirlpool Climate / model DG11J1-91  

### Example YAML snippet

```yaml
esphome:
name: s08ir
platform: ESP8266
board: esp_wroom_02

wifi:
ssid: "DomWiFi"
password: "Dom1WiFi2"
fast_connect: true

logger:
level: DEBUG

api:
password: "s08ir"

ota:
password: "s08ir"

status_led:
pin:
number: GPIO4

remote_receiver:
id: "s08_receiver"
pin:
number: GPIO5
inverted: true
dump: all

remote_transmitter:
id: "s08_transmitter"
pin:
number: GPIO14
inverted: false
carrier_duty_percent: 55%

binary_sensor:

platform: gpio
name: "s08_button"
id: "s08_button"
pin:
number: GPIO13
inverted: true
internal: true
sensor:

platform: homeassistant
id: current_temperature
entity_id: sensor.ble_temperature_e72e0172f902
device_class: temperature
state_class: measurement
climate:

platform: whirlpool
name: "Кондиционер спальня"
model: DG11J1-91
id: "konditsioner_spalnya"
sensor: current_temperature
receiver_id: "s08_receiver"
transmitter_id: "s08_transmitter"
visual:
min_temperature: 16 °C
max_temperature: 30 °C
temperature_step: 1 °C
```

### Additional information

I use this information and this device to control my air conditioner as described in the link below:
https://github.com/esphome/issues/issues/4650#
