### ISSUE TITLE
Canbus.send causes compile time error if can_id not provided. 

### ISSUE THREAD

**Issue by skykingjwc** [esphome/issues#5016]
### The problem

If canbus.send is called without specifying a can_id a compile time error occurs.  According to the docs, if a single canbus is defined then canbus.send should use the id of the single canbus, unless overridden.  This config variable is marked as optional in the docs so it should not be necessary if only one canbus is defined

### Which version of ESPHome has the issue?

23.10.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.1

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

canbus

### Example YAML snippet

```yaml
#does not work 
switch:
  - platform: output
    output: myoutput
    id:  myid
    name:  myname
    on_turn_on:
       - canbus.send: "mudOn"

#works
switch:
  - platform: output
    output: myoutput
    id:  myid
    name:  myname
    on_turn_on:
       - canbus.send:
          data: "test"
          can_id: 17  #<--- should not need this
```

### Anything in the logs that might be useful for us?

```txt
Error at compile
File "/esphome/esphome/components/canbus/__init__.py", line 20, in validate_id
    can_id = config[CONF_CAN_ID]
KeyError: 'can_id'
```
