### ISSUE TITLE
Current Based Cover' - Malfunction detected during opening. Current flow detected in close circuit

### ISSUE THREAD

**Issue by Brembo427** [esphome/issues#5021]
### The problem

Hey guys just trying to build a simple low voltage smart roller shutter controller using an athom. relay-board-x2 with an INA219 I2C Digital current monitor. have written up a basic current based cover into the YAML. 

when I go to open or close the cover it will run for about a second then stop and throw Malfunction detected during opening. Current flow detected in close circuit, in the logs. every time without fail.

regardless of I do inside the YAML in terms of current limits, times or delays it does the exact same thing. 

Its running a basic 2 wire 12-volt dc motor which drives the roller shutter. if I manually force relays on, I can simulate opening and closing manually. 

please help?

### Which version of ESPHome has the issue?

2023.10.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10

### What platform are you using?

ESP8266

### Board

athom relay board x2

### Component causing the issue

i2c

### Example YAML snippet

```yaml
substitutions:

  name: "shutter"
packages:
  athom.relay-board-x2: github://athom-tech/athom-configs/athom-relay-board-x2.yaml
 
esphome:
  name: ${name}
  name_add_mac_suffix: false

api:
  encryption:
    key: i9JEJ7IOJFhSyGWdJ57iIDu86AeZ8tWlJ2rGkJUqLDs=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: GPIO12  
  scl: GPIO13

sensor:
   - platform: ina219
     address: 0x40
     shunt_resistance: 0.1 ohm
     current:
      id: "current"
      name: "Current"
     power:
      name: "Power"
     bus_voltage:
      name: "Bus Voltage"
     shunt_voltage:
      name: "Shunt Voltage"
     max_voltage: 32.0V
     max_current: 3.2A
     update_interval: 0.5s

cover:
  - platform: current_based
    name: "Current Based Cover"

    open_sensor: current
    open_moving_current_threshold: 1.7
    open_obstacle_current_threshold: 3.0
    open_duration: 24s
    open_action:
      - switch.turn_on: relay1
      - switch.turn_off: relay2

    close_sensor: current
    close_moving_current_threshold: 1.0
    close_obstacle_current_threshold: 2.5
    close_duration: 24s
    close_action:
      - switch.turn_on: relay2
      - switch.turn_off: relay1

    stop_action:
      - switch.turn_off: relay1
      - switch.turn_off: relay2

    obstacle_rollback: 30%
    start_sensing_delay: 1.0s
```

### Anything in the logs that might be useful for us?

```txt
[I][current_based.cover:069]: 'Current Based Cover' - Malfunction detected during opening. Current flow detected in close circuit

[I][current_based.cover:090]: 'Current Based Cover' - Malfunction detected during closing. Current flow detected in open circuit
```
