### ISSUE TITLE
Uptime Should Return a Datetime Rather than a Counter

### ISSUE THREAD

**Issue by barndawgie** [esphome/issues#5023]
### The problem

Currently, the ESPHome Uptime integration returns a monotonically increasing string. This is a pain for usage in Home Assistant and drives higher storage needs.

As implemented, this would intuitively be a `duration` device class, but [per the documentation](https://developers.home-assistant.io/docs/core/entity/sensor#available-device-classes) durations "Should not update only due to time passing."

Instead, uptime should match the [Home Assistant uptime sensor](https://www.home-assistant.io/integrations/uptime/) which provides the datetime of last boot.

### Which version of ESPHome has the issue?

2023.10.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

m5Stack ATOM

### Component causing the issue

uptime

### Example YAML snippet

```yaml
sensor:
- platform: uptime
  name: ESPHome Uptime
  device_class: duration
  unit_of_measurement: s
  icon: mdi:timer-check
  entity_category: diagnostic
  disabled_by_default: false
  force_update: false
  accuracy_decimals: 0
  state_class: total_increasing
  update_interval: 60s
```
