### ISSUE TITLE
Captive portal fails to launch on ESP32 (arduino framework)

### ISSUE THREAD

**Issue by tomatensaus** [esphome/issues#5024]
### The problem

I have a device flashed with network credentials that does not match my network
I expect the captive portal to start and enable me to change the network AP and password

Looking at the serial log I see the message about starting the fallback AP repeats many times per second as if the AP does not start up successfully and then retries.

My android phone managed to scan and find the fallback AP but I am unable to get an IP Address from it, reports
 "IP Configuration Failure"

When changing to Logger: 
level: VERBOSE (Fallback AP works)
level: VERY_VERBOSE (Fallback AP Works)
level: DEBUG (Fallback AP fails to start)
This is perhaps a timing issue when starting the fallback AP

### Which version of ESPHome has the issue?

2023.10.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2023.10.1

### What platform are you using?

ESP32

### Board

ESP32 Devkit C

### Component causing the issue

wifi

### Example YAML snippet

```yaml
#################################### GLOBALS ####################################
substitutions:
  device_name: inverterdemo
  friendly_name: InverterDemo
  inverter_modbus_controller: esphome_modbus
  inverter_modbus_id: modbus_master
  identity_prefix: demo_esphome_
  inverter_network_name: "inverterdemo.local"
  software_version: "1.0"

####### Config
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  comment: "Inverter Home Assistant integration"
  project:
    name: "My.Inverter_Demo"
    version: ${software_version}

esp32:
  board: esp32dev
  #board: nodemcu-32s

logger:
  level: DEBUG

#debug:
#  update_interval: 5s

api:

ota:
#  password: !secret inverter_ota_password


wifi:
  power_save_mode: none
  networks:
    - ssid: notvalidwifi
      password: password

  #use_address: ${inverter_network_name}
  # in case wifi connection details was changed
  ap:
    ssid: "${friendly_name}Hotspot"
    password: password

captive_portal:

# improv_serial:

web_server:
  port: 80

#home assistant time....to be replaced for mqtt integration
time:
  - platform: homeassistant
    id: homeassistant_time

uart:
  id: mod_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1

#===================================================================
sensor:
  - platform: wifi_signal
    name: WiFi ${device_name}
    id: wifi_s
    internal: true
    update_interval: 60s
  - platform: template
    name: Wifi logger signal
    unit_of_measurement: '%'
    accuracy_decimals: 0
    icon: mdi:wifi
    lambda: |-
          if (id(wifi_s).state < -92.0)
            return 1.0;
          if (id(wifi_s).state > -21.0)
            return 100.0;
          else
            return round(( -0.0154 * id(wifi_s).state * id(wifi_s).state ) - ( 0.3794 * id(wifi_s).state ) + 98.182 );
    update_interval: 60s
  - platform: uptime
    filters:
        - lambda: return x / 3600;
    unit_of_measurement: hours
    name: Wifi logger Uptime


text_sensor:
  - platform: wifi_info
    ssid:
        name: Wifi logger SSID
        id : logger_wifi_network
    bssid:
        name: Wifi logger MAC
        id: logger_bssid_id
    ip_address:
        name: Wifi IP Address
        id : logger_ip_addr
```

### Anything in the logs that might be useful for us?

```txt
[17:27:14][W][wifi:497]: No matching network found!
[17:27:16][I][wifi:156]: Starting fallback AP!
[17:27:16][C][wifi:230]: Setting up AP...
[17:27:16][C][wifi:232]:   AP SSID: 'InverterDemo Fallback Hotspot'
[17:27:16][C][wifi:233]:   AP Password: 'fixmywifi'
[17:27:17][C][wifi:242]:   IP Address: 192.168.4.1
[17:27:17][I][wifi:156]: Starting fallback AP!
[17:27:17][C][wifi:230]: Setting up AP...
[17:27:17][C][wifi:232]:   AP SSID: 'InverterDemo Fallback Hotspot'
[17:27:17][C][wifi:233]:   AP Password: 'fixmywifi'
[17:27:17][C][wifi:242]:   IP Address: 192.168.4.1
[17:27:17][I][wifi:156]: Starting fallback AP!
[17:27:17][C][wifi:230]: Setting up AP...
[17:27:17][C][wifi:232]:   AP SSID: 'InverterDemo Fallback Hotspot'
```
