### ISSUE TITLE
Error while compiling after update esphome with board esp32-c3-devkitm-1

### ISSUE THREAD

**Issue by proasnet** [esphome/issues#5027]
### The problem

I have had a functioning weather station for about a year, which I always update to a new version of esphome without any problems.
I wanted to do an update today, but the compilation shows the following error.
Only this device has problem with update, other without problems.

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.1

### What platform are you using?

ESP32

### Board

LaskaKit Meteo Mini 

### Example YAML snippet

```yaml
substitutions:
  name: weatherstation
  friendly_name: "Weather Station"
  device_description: "Weather Station"

esphome:
  name: ${name}
  comment: ${device_description}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

api:

ota:
 
web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

wifi:
  ssid: !secret wifi_ssid_2
  password: !secret wifi_password

  ap:
    ssid: "Weatherstation Fallback Hotspot"
    password: "Jirka8011"

captive_portal:

time:
  - platform: sntp
    id: sntp_time
    servers: "pool.ntp.org"

interval:
  - interval: 60s
    then: 
      - sensor.integration.reset: rain_per_min
  

#deep_sleep:
#  run_duration: 10s
#  sleep_duration: 1min

# definice i2c
i2c:
  sda: 19
  scl: 18
  scan: true

sensor:
# citac na rychlost vetru
  - platform: pulse_meter
    pin:
      # Don't forget to add a pulling resistor, see README
      number: GPIO6
      mode: INPUT
    id: wind_speed
    unit_of_measurement: 'm/s'
    name: "${friendly_name} wind speed"
    icon: 'mdi:weather-windy'
    internal_filter: 100us
    timeout: 5s
    filters:
      - multiply: 0.005560619
      - sliding_window_moving_average:
          window_size: 20
          send_every: 20

  - platform: copy
    name: '${friendly_name} wind speed average'
    icon: 'mdi:weather-windy'
    id: wind_speed_avg
    source_id: wind_speed
    unit_of_measurement: 'm/s'
    filters:
      - throttle_average: 5s

  - platform: copy
    name: '${friendly_name} wind speed (km/h)'
    id: wind_speed_kmh
    source_id: wind_speed
    unit_of_measurement: 'km/h'
    icon: 'mdi:weather-windy'
    filters:
      - multiply: 3.6

  - platform: copy
    name: '${friendly_name} wind speed average (km/h)'
    icon: 'mdi:weather-windy'
    id: wind_speed_kmh_avg
    source_id: wind_speed_avg
    unit_of_measurement: 'km/h'
    filters:
      - multiply: 3.6
  
# směr větru
  - platform: adc
    id: source_sensor
    pin: GPIO3
    name: ADC
    attenuation: 11db
    internal: true
    update_interval: 1s
    accuracy_decimals: 2

  - platform: resistance
    sensor: source_sensor
    id: resistance_sensor
    configuration: DOWNSTREAM
    resistor: 32kOhm
    internal: true
    name: Resistance Sensor
    accuracy_decimals: 2
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 3
    on_value:
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 32000
              below: 33000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "N"
            - sensor.template.publish:
                id: wind_heading
                state: 0.0
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 8000
              below: 8500
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "NE"
            - sensor.template.publish:
                id: wind_heading
                state: 45.0
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 900
              below: 1100
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "E"
            - sensor.template.publish:
                id: wind_heading
                state: 90.0
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 2100
              below: 2300
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "SE"
            - sensor.template.publish:
                id: wind_heading
                state: 135.0
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 3800
              below: 4000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "S"
            - sensor.template.publish:
                id: wind_heading
                state: 180.0
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 15500
              below: 16500
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "SW"
            - sensor.template.publish:
                id: wind_heading
                state: 225.0
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 110000
              below: 120000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "W"
            - sensor.template.publish:
                id: wind_heading
                state: 270.0
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 63000
              below: 65000
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "NW"
            - sensor.template.publish:
                id: wind_heading
                state: 315.0

  - platform: template
    name: "${friendly_name} wind heading"
    id: wind_heading
    unit_of_measurement: "°"
     
# citac na mnozstvi deste
  - platform: pulse_counter
    pin:
      # Don't forget to add a pulling resistor, see README
      number: GPIO7
      mode: INPUT
    unit_of_measurement: 'mm'
    name: "${friendly_name} rain gauge"
    icon: 'mdi:weather-rainy'
    id: rain_gauge
    internal: true
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 13us
    update_interval: 60s
    filters:
      # Each 0.011" (0.2794mm) of rain causes one momentary contact closure
      - multiply: 0.2794
    accuracy_decimals: 4

# déšť za minutu a za den
  - platform: integration
    name: "${friendly_name} rainfall per min"
    id: rain_per_min
    time_unit: min
    unit_of_measurement: 'mm'
    icon: 'mdi:weather-rainy'
    sensor: rain_gauge

  - platform: total_daily_energy
    name: "${friendly_name} total daily rain"
    power_id: rain_gauge
    unit_of_measurement: 'mm'
    icon: 'mdi:weather-rainy'
    # x60 To convert to aggregated rain amount
    filters:
      - multiply: 60

  - platform: bme280
    address: 0x77
    update_interval: 60s
    iir_filter: 16x
    temperature:
      name: "${friendly_name} Temperature"
      #id: bme280_temperature
      oversampling: 16x
    humidity:
      name: "${friendly_name} Humidity"
      #id: bme280_humidity
      oversampling: 16x
    pressure:
      name: "${friendly_name} Pressure"
      #id: bme280_pressure
      oversampling: 16x

  - platform: bh1750
    name: "${friendly_name} Illuminance"
    id: illuminance
    unit_of_measurement: 'lux'
    address: 0x23
    update_interval: 60s

# napětí baterie
  - platform: adc
    pin: GPIO1
    name: "${friendly_name} Outside Battery"
    accuracy_decimals: 2
    update_interval: 60s
    attenuation: 11db
    filters:
      - multiply: 1.77

button:
  - platform: restart
    name: "ESP_Restart"

text_sensor:
  - platform: template
    name: "${friendly_name} wind cardinal direction"
    id: wind_dir_card
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.10.3
INFO Reading configuration /config/esphome/weatherstation.yaml...
INFO Detected timezone 'Europe/Prague'
INFO Generating C++ source...
INFO Compiling app...
Processing weatherstation (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.0.1
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Wire @ 2.0.0
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/weatherstation/src/esphome/components/adc/adc_sensor.cpp.o
In file included from src/esphome/components/adc/adc_sensor.h:3,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
src/esphome/core/component.h:3:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~
compilation terminated.
Compiling .pioenvs/weatherstation/src/esphome/components/api/api_connection.cpp.o
*** [.pioenvs/weatherstation/src/esphome/components/adc/adc_sensor.cpp.o] Error 1
In file included from src/esphome/components/api/api_connection.h:3,
                 from src/esphome/components/api/api_connection.cpp:1:
src/esphome/components/api/api_frame_helper.h:2:10: fatal error: cstdint: No such file or directory
 #include <cstdint>
          ^~~~~~~~~
compilation terminated.
*** [.pioenvs/weatherstation/src/esphome/components/api/api_connection.cpp.o] Error 1
========================= [FAILED] Took 10.56 seconds =========================
```

### Additional information

Problem is with this board
esp32-c3-devkitm-1
If I change to another to new test.yaml without any sensors, compile working.
It doesn't matter what the framework is, there will always be a compile error.
