### ISSUE TITLE
MQTT Component doesn't honor availability topic configuration

### ISSUE THREAD

**Issue by climategadgets** [esphome/issues#5030]
### Expected Behavior
Providing `availability.topic` for an MQTT Component makes the component advertise its availability on the given topic.

### Actual Behavior
* Providing `availability.topic` makes ESPHome correctly advertise the availability topic in Home Assistant Discovery Packet
* However, it does not make the component publish its availability on the provided topic
* Yet, availability is still published, but only at `${topic_prefix}/status`.

### Which version of ESPHome has the issue?

2023.2.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Irrelevant, behavior is traceable with observing MQTT topics

### What platform are you using?

ESP32

### Board

LILYGO TTGO T-Relay

### Component causing the issue

mqtt

### Example YAML snippet

```yaml
mqtt:
  broker: $IP_ADDRESS
  topic_prefix: /esphome/${MAC}
  log_topic: /esphome-log/${MAC}

switch:
  - platform: gpio
    name: "t-relay-3-r3"
    id: R3
    pin: GPIO05
    availability:
      topic: /esphome/${MAC}/switch/t-relay-3-r3/status
```

### Anything in the logs that might be useful for us?

```txt
It looks like the availability topic is not picked up somewhere, the boot message states the following (note just two topics):


[19:58:19][C][mqtt.switch:041]: MQTT Switch 't-relay-3-r3': 
[19:58:19][C][mqtt.switch:042]:   State Topic: '/esphome/${MAC}/switch/t-relay-3-r3/state'
[19:58:19][C][mqtt.switch:042]:   Command Topic: '/esphome/${MAC}/switch/t-relay-3-r3/command'

```
```


### Additional information

Here's the fragment of the Home Assistant Discovery Packet rendered with the configuration above - the availability topic is advertised correctly:

```
{
  "name": "t-relay-3-r3",
  "stat_t": "/esphome/${MAC}/switch/t-relay-3-r3/state",
  "cmd_t": "/esphome/${MAC}/switch/t-relay-3-r3/command",
  "avty_t": "/esphome/${MAC}/switch/t-relay-3-r3/status",
```
