### ISSUE TITLE
2023 Mopeka Devices & esp32_ble_tracker

### ISSUE THREAD

**Issue by TelecomRob** [esphome/issues#5035]
### The problem

Hello, I'm having issues with the esp32_ble_tracker not picking up all ble devices when scanning. It is pick up other bluetooth devices but not a 2023 Model Mopeka Pro check Universal M1017 Sensor. I'm wondering if Mopeka changes the chipset on the boards or encrypted it as if I run a scan using Arduino BLE scanner can see the device.

I have poked around other threads and it seems other people have been having issues with the 2023 Model Mopeka Pro check Universal M1017 Sensor in regards to esp32_ble_tracker not seeing them.

Screenshot of CLI:
![image](https://github.com/esphome/issues/assets/145357807/e8677b1c-efd0-4e94-8589-5cfbeb76edb1)

Screenshot of HA proving esp32_ble_tracker is detecting other devices:
![Screenshot 2023-10-26 093134](https://github.com/esphome/issues/assets/145357807/27cf5f40-cc8c-45e0-8136-b55fa304eb47)

### Which version of ESPHome has the issue?

2023.10.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
esphome:
name: mopeka

esp32:
board: esp32dev
framework:
type: arduino

Enable logging
logger:

Enable Home Assistant API
api:
password: ""

ota:
password: ""

wifi:
ssid: "abc12345"
password: "abc12345"

Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
ssid: "Mopeka Fallback Hotspot"
password: "abc12345"

captive_portal:

Enable Bluetooth Proxy Components
esp32_ble_tracker:
scan_parameters:
interval: 320ms
window: 120ms
duration: 60s
active: true

bluetooth_proxy:
active: true

mqtt:
broker: 192.168.1.94
username: ""
password: ""
client_id: "mopeka"

sensor:

platform: mopeka_pro_check
mac_address: 4c:3c:19:88:3f:4c
tank_type: 20LB_V
temperature:
name: "Propane test temp"
level:
name: "Propane test level"
distance:
name: "Propane test distance"
battery_level:
name: "Propane test battery level"
```

### Additional information

How Arduino BLE see device when scan:
Advertised Device: Name: , Address: 4c:3c:19:88:3f:4c, manufacturer data: 4c0010061b1940e8a878, txPower: 12, rssi: -10
