### ISSUE TITLE
Unable to use CANBUS with SN65HVD230DR using ESP32C6

### ISSUE THREAD

**Issue by UmerSoftwares** [esphome/issues#5041]
### The problem

I have made a circuit with ESP32C6 that is supposed to run ESPHOME. I am unable to configure CANBUS in ESPHOME.

My yaml file is

```
esphome:
  name: "esp32c6"
  friendly_name: C6
  platformio_options:
    board_upload.flash_size: 4MB

esp32:
  board: "esp32-c6-devkitc-1"
  variant: "ESP32C6"
  framework:
    platform_version: https://github.com/stintel/platform-espressif32#esp32-c6-test
    #platform_version: https://github.com/platformio/platform-espressif32.git
    type: esp-idf
    version: 5.1.0
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: ""
  password: ""

canbus:
  - platform: esp32_can
    tx_pin: GPIO12
    rx_pin: GPIO11
    can_id: 4
    bit_rate: 1kbps
    on_frame:
    - canbus.send:
        data: [ 0x11, 0x20, 0x30 ]
        can_id: 23 # override the can_id configured in the can bus
```

The error I am getting is:
```
>esphome run device1.yaml
INFO ESPHome 2023.11.0-dev
INFO Reading configuration device1.yaml...
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
Failed config

canbus.esp32_can: [source device1.yaml:31]
  platform: esp32_can
  tx_pin: GPIO12
  rx_pin: GPIO11
  can_id: 4

  ESP32C6 is not supported by component esp32_can.
  bit_rate: 1kbps

  'can_id' is a required option for [on_frame].
  on_frame:s
    - canbus.send:
        data:
          - 17
          - 32
          - 48
        can_id: 23
```

I can not find what I should use instead of esp32_can in platform to make it work with ESP32 C6.

### Which version of ESPHome has the issue?

2023.11.0.dev0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

ESP32C6 WROOM1

### Component causing the issue

CANBUS

### Example YAML snippet

```yaml
esphome:
  name: "esp32c6"
  friendly_name: C6
  platformio_options:
    board_upload.flash_size: 4MB

esp32:
  board: "esp32-c6-devkitc-1"
  variant: "ESP32C6"
  framework:
    platform_version: https://github.com/stintel/platform-espressif32#esp32-c6-test
    #platform_version: https://github.com/platformio/platform-espressif32.git
    type: esp-idf
    version: 5.1.0
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: ""
  password: ""

canbus:
  - platform: esp32_can
    tx_pin: GPIO12
    rx_pin: GPIO11
    can_id: 4
    bit_rate: 1kbps
    on_frame:
    - canbus.send:
        data: [ 0x11, 0x20, 0x30 ]
        can_id: 23 # override the can_id configured in the can bus
```

### Anything in the logs that might be useful for us?

```txt
>esphome run device1.yaml
INFO ESPHome 2023.11.0-dev
INFO Reading configuration device1.yaml...
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
Failed config

canbus.esp32_can: [source device1.yaml:31]
  platform: esp32_can
  tx_pin: GPIO12
  rx_pin: GPIO11
  can_id: 4

  ESP32C6 is not supported by component esp32_can.
  bit_rate: 1kbps

  'can_id' is a required option for [on_frame].
  on_frame:s
    - canbus.send:
        data:
          - 17
          - 32
          - 48
        can_id: 23
```
