### ISSUE TITLE
Minimal image is too big to esp01 OTA

### ISSUE THREAD

**Issue by tgrosz** [esphome/issues#5046]
### The problem

The minimal image (only board, wifi, ota) is 300+k in size, so it makes OTA unusable on esp01.

### Which version of ESPHome has the issue?

2023.10

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.3

### What platform are you using?

ESP8266

### Board

Esp01

### Component causing the issue

Ota

### Example YAML snippet

```yaml
esphome:
  name: wall-tablet
  friendly_name: wall-tablet

esp8266:
  board: esp01

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
