### ISSUE TITLE
Bang Bang Climate idle action not being triggered

### ISSUE THREAD

**Issue by l1c2d3** [esphome/issues#505]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

Lolin32 with integrated OLED
**Affected component:**

https://esphome.io/components/climate/bang_bang.html

**Description of problem:**
I'm currently testing a thermostat build (not yet connected to my HVAC system), with an ESP32 with integrated OLED, SHT31 Temperature sensor, and 3 relays (Fan, Cool, Heat).

When I set the thermostat to Cool, Fan and Cool relays activate. When the temperature is within range, the idle action is set to turn the cool relay off, but this never happens. 

In Auto mode it's working properly, when the temp condition is met, fan (with an automation) and cool relays turn off.

I would also like to know if idle is shown as state, this to create an automation to delay 5 min turning on the compressor after it changes from idle to cool.

Thank you in advance for your help.

**Problem-relevant YAML-configuration entries:**
```yaml
climate:
  - platform: bang_bang
    id: therm_test
    name: "Thermostat Test"
    sensor: sht_temp
    default_target_temperature_low: 13 °C
    default_target_temperature_high: 24 °C
    cool_action:
      - switch.turn_on: fan
      - switch.turn_on: cool
    idle_action:
      - switch.turn_off: cool
      - switch.turn_off: heat
    heat_action:
      - switch.turn_on: fan
      - switch.turn_on: heat
    visual:
      min_temperature: 10 °C
      max_temperature: 32 °C
      temperature_step: .5

```

**Logs (if applicable):**

```
[13:06:03][D][sht3xd:059]: Got temperature=21.40°C humidity=44.85%
[13:06:03][D][sensor:092]: 'SHT Temperature': Sending state 21.39529 °C with 1 decimals of accuracy
[13:06:03][D][climate:172]: 'Thermostat Test' - Sending state:
[13:06:03][D][climate:175]:   Mode: COOL
[13:06:03][D][climate:177]:   Current Temperature: 21.40°C
[13:06:03][D][climate:181]:   Target Temperature: Low: 14.00°C High: 24.00°C

```

**Additional information and things you've tried:**
