### ISSUE TITLE
Light Partition Doesn't Pass Through Color Temperature

### ISSUE THREAD

**Issue by scolby33** [esphome/issues#5050]
### The problem

I have two CW/WW LED strips, each connected to two channels of a Shelly RGBW2 running ESPHome.

With a configuration like so, Home Assistant sees two light entities with `min/max_color_temp_kelvin`, `min/max_mireds`, and `supported_color_modes: color_temp`, as expected:

When I try to combine the two sets of lights using a light partition, there is only `supported_color_modes: brightness` and the color temperature is not controllable from HA:
```yaml
light:
  - platform: "cwww"
    name: "Right"
    cold_white: "red"
    warm_white: "green"
    cold_white_color_temperature: "6000K"
    warm_white_color_temperature: "3000K"
    default_transition_length: "0s"
    restore_mode: "RESTORE_DEFAULT_OFF"
    id: "channel_1"
    internal: true
  - platform: "cwww"
    name: "Left"
    cold_white: "blue"
    warm_white: "white"
    cold_white_color_temperature: "6000K"
    warm_white_color_temperature: "3000K"
    default_transition_length: "0s"
    restore_mode: "RESTORE_DEFAULT_OFF"
    id: "channel_2"
    internal: true
  - platform: "partition"
    name: "CW/WW Strips"
    segments:
      - single_light_id: "channel_1"
      - single_light_id: "channel_2"
    default_transition_length: "0s"
    restore_mode: "RESTORE_DEFAULT_OFF"
```

### Which version of ESPHome has the issue?

2023.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.5

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

light/partiton

### Example YAML snippet

```yaml
See above in "the problem" section, where I describe the two involved configurations.
```

### Anything in the logs that might be useful for us?

```txt
No specific logs.
```

### Additional information

<img width="991" alt="Screenshot 2023-10-29 at 20 00 56" src="https://github.com/esphome/issues/assets/9711846/b0588632-b199-46ad-8c0a-a2ca877a98be">
<img width="1231" alt="Screenshot 2023-10-29 at 19 58 42" src="https://github.com/esphome/issues/assets/9711846/159adff7-fc2b-471a-8f14-ff4fe2e586ff">
