### ISSUE TITLE
C6 4MB flash bootloops

### ISSUE THREAD

**Issue by samuelolteanu** [esphome/issues#5052]
### The problem

I managed to get ESPHome working on [WeAct] ESP32-C6-A-N8 but flashing on ESP32-C6-A-N4 will result in bootloop.
Curiously, the 8mb board had a demo with flashing rgb but the other one did not. I was not inspired enogh to see its logs before flashing esphome. There also was an abnormal difference in price between those two, same vendor.
This did not help:
```
esphome:
  # ...
  platformio_options:
    upload_speed: 115200
    board_build.f_flash: 40000000L

```

Older/different version of esp-idf did not compile. Esptool reports 4mb.
[logs.txt](https://github.com/esphome/issues/files/13209492/logs.txt)

### Which version of ESPHome has the issue?

2023.10.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

ESP32-C6-A-N4

### Component causing the issue

SPI, maybe?

### Example YAML snippet

```yaml
esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  framework:
    platform_version: https://github.com/stintel/platform-espressif32#esp32-c6-test
    type: esp-idf
    version: 5.1.0


esphome:
  name: c6-n4-1
  friendly_name: c6-n4-1

logger:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
captive_portal:


button:
  - platform: safe_mode
    name: safe mode
```

### Anything in the logs that might be useful for us?

```txt
E (650) spi_flash: Detected size(4096k) smaller than the size in the binary image header(8192k). Probe failed.
```
