### ISSUE TITLE
there is no only_fan mode and the receiver is not decoding remote commands.

### ISSUE THREAD

**Issue by ssrsmart** [esphome/issues#5053]
### The problem

the climate works fine and accurate, but there is no only_fan mode, also the receiver is not decoding the OEM commands, but when I control the ac from the broadlink remote it decode the commands. the remote code AKB75415305

### Which version of ESPHome has the issue?

2023.10.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.5

### What platform are you using?

ESP8266

### Board

D1_mini

### Example YAML snippet

```yaml
captive_portal:

remote_transmitter:
  pin: D2
  id: ir_transmitter
  carrier_duty_percent: 50%

remote_receiver:
  id: rcvr
  pin:
    number: D7
    inverted: True
    mode:
      input: True
      pullup: True
  dump: all
  tolerance: 55%

climate:
  - platform: climate_ir_lg
    name: "AC"
    receiver_id: rcvr
    transmitter_id: ir_transmitter
```
