### ISSUE TITLE
esp32_camera fails when using esp-idf framework

### ISSUE THREAD

**Issue by protectivedad** [esphome/issues#5056]
### The problem

Using esp-idf framework with esp32_camera causes the camera to fail. I found the solution but I don't know enough to properly implement it. The esp32_camera component hard codes version 1.0.0 for the espressif/esp32-camera library. This causes the problem. If I comment out and allow it to use the current version (2.0.4) it errors on the compile because of a problem which is detailed [ When using esp-idf, libraries downloaded by PlatformIO are not found, but there is workaround #281 ](https://github.com/platformio/platformio-docs/issues/281)

This is where I don't know how to implement the solution the build directory `CMakeLists.txt ` file needs:
```
list(APPEND EXTRA_COMPONENT_DIRS .piolibdeps/projectname)
```
added to it. After that it compiles and runs fine.

I haven't put a lot of tracing and debug information in this because the esp32_camera is using an old 1.0.0 library and probably should be updated.

### Which version of ESPHome has the issue?

2023.10.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

esp32-cam

### Example YAML snippet

```yaml
Works:
esp32:
  board: esp32dev
  framework:
    type: arduino 

Doesn't work:
esp32:
  board: esp32dev
  framework:
    type: esp-idf
```

### Anything in the logs that might be useful for us?

```txt
[D][esp-idf:000]: I (179) sccb: pin_sda 26 pin_scl 27


[D][esp-idf:000]: I (180) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 

[D][esp-idf:000]: I (219) sccb: SCCB_Probe start

[D][esp-idf:000]: E (711) camera: Detected camera not supported.

[D][esp-idf:000]: E (711) camera: Camera probe failed with error 0x20004

[E][esp32_camera:024]: esp_camera_init failed: ERROR
[E][component:113]: Component esp32_camera was marked as failed.
```

**Comment by protectivedad** [comment]
Alright that's solved. The reason I'm using esp-idf is to use tls mqtt. That seemed to use up the sockets so I increased the max sockets from 10 to 16. So my working yaml is:
```
packages:
  wifi: !include ../Default/wifi.yml
  ota: !include ../Default/ota.yml
  web_server: !include ../Default/web_server.yml
  mqtt: !include ../Default/mqtt.yml

esphome:
  name: test-esp32-cam-camera
  libraries:
    - espressif/esp32-camera

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_LWIP_MAX_SOCKETS: "16"

logger:

# Example configuration entry
esp32_camera:
  id: espcam
  external_clock:
    pin: GPIO0
    frequency: 10MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: 'Test ESP32-Cam Camera'
  resolution: 1024x768
  jpeg_quality: 30

  brightness: 2 # -2 to 2
  contrast: 1 # -2 to 2
  special_effect: none
  # exposure settings
  aec_mode: auto
  aec2: false
  ae_level: 0
  aec_value: 300
  # gain settings
  agc_mode: auto
  agc_gain_ceiling: 2x
  agc_value: 0
  # white balance setting
  wb_mode: auto

output:
  - platform: ledc
    pin: GPIO4
    channel: 2
    id: led

light:
  - platform: monochromatic
    output: led
    name: 'Test ESP32-Cam Light'

esp32_camera_web_server:
  - port: 8081
    mode: snapshot
  - port: 8080
    mode: stream
```
with this patch to esphome:
```
--- a/__main__.py
+++ b/__main__.py
@@ -403,6 +403,12 @@ def command_compile(args, config):
     exit_code = write_cpp(config)
     if exit_code != 0:
         return exit_code
+
+    if CORE.using_esp_idf:
+        if os.path.islink(os.path.abspath(CORE.relative_build_path(""))+"/components"):
+            os.unlink(os.path.abspath(CORE.relative_build_path(""))+"/components")
+        os.symlink(".piolibdeps/"+CORE.name, os.path.abspath(CORE.relative_build_path(""))+"/components", True)
+
     if args.only_generate:
         _LOGGER.info("Successfully generated source code.")
         return 0
--- a/components/esp32_camera/__init__.py
+++ b/components/esp32_camera/__init__.py
@@ -278,10 +278,6 @@ async def to_code(config):
 
     cg.add_define("USE_ESP32_CAMERA")
 
-    if CORE.using_esp_idf:
-        cg.add_library("espressif/esp32-camera", "1.0.0")
-        add_idf_sdkconfig_option("CONFIG_RTCIO_SUPPORT_RTC_GPIO_DESC", True)
-
     for conf in config.get(CONF_ON_STREAM_START, []):
         trigger = cg.new_Pvariable(conf[CONF_TRIGGER_ID], var)
         await automation.build_automation(trigger, [], conf)
```
