### ISSUE TITLE
Wrong id in Prometheus metrics

### ISSUE THREAD

**Issue by LinFor** [esphome/issues#5067]
### The problem

Prometheus export ignores sensor ids, using sensor names instead.

For example, i declare some sensor with different id (**test_heater_1**) and name (**dallas 08**):
```
  - platform: dallas
    id: test_heater_1
    address: 0xbc3ce1d44463fd28
    name: "dallas 08"
    resolution: 12
    accuracy_decimals: 2
```

But on /metrics endpoint it appears with different id (**dallas_08**), probably generated from name:
```
esphome_sensor_failed{id="dallas_08",name="dallas 08"} 0
esphome_sensor_value{id="dallas_08",name="dallas 08",unit="°C"} 31.19
```

### Which version of ESPHome has the issue?

2023.10.1 Nov 2 2023, 14:26:06

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

none

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

prometheus

### Example YAML snippet

```yaml
prometheus:
  include_internal: true
sensor:
  - platform: dallas
    id: test_heater_1
    address: 0xbc3ce1d44463fd28
    name: "dallas 08"
    resolution: 12
    accuracy_decimals: 2
```

### Anything in the logs that might be useful for us?

```txt
esphome_sensor_failed{id="dallas_08",name="dallas 08"} 0
esphome_sensor_value{id="dallas_08",name="dallas 08",unit="°C"} 31.19
```
