### ISSUE TITLE
ESP32-C6 absolute humidity sensor causes rebooting

### ISSUE THREAD

**Issue by ByteFloor** [esphome/issues#5071]
### The problem

I'm trying to use absolute_humidity sensor with ESP32-C6-DevKitC-1 board. After flashing the board, status LED starts blinking fast and the board keeps rebooting. If I remove the absolute_humidity sensor from YAML everything else works.

### Which version of ESPHome has the issue?

2023.11.0-dev20231104

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

ESP32-C6-DevKitC-1

### Component causing the issue

Absolute Humidity

### Example YAML snippet

```yaml
esphome:
  name: esp32c6
  friendly_name: esp32c6

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    platform_version: 6.4.0
    version: 5.1.1

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "7NoMdzi9ROCIGxwHsvy5RTJVGOvbBJlms/S+OfmDUx0="

ota:
  password: "68081a9bb599b4394f38dad5272887d9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: High

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C6 Fallback Hotspot"
    password: "sNApLSpmiDlL"

captive_portal:

web_server:
  port: 80

status_led:
  pin:
   number: 10

# sht3xd 
i2c:
  sda: 6
  scl: 7
  scan: false

sensor:
# Temperature and relative humidity
  - platform: sht3xd
    temperature:
      name: "Temperature in Living room"
      id: air_temperature
    humidity:
      name: "Relative humidity in Living room"
      id: relative_humidity
    address: 0x44
    update_interval: 60s

# Absolute humidity
  - platform: absolute_humidity
    name: Absolute humidity in Living room
    temperature: air_temperature
    humidity: relative_humidity
```

### Anything in the logs that might be useful for us?

```txt
ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0x15 (USB_UART_HPSYS),boot:0x1c (SPI_FAST_FLASH_BOOT)
Saved PC:0x40800802
SPIWP:0xee
mode:DIO, clock div:2
load:0x4086c410,len:0xd10
load:0x4086e610,len:0x2dc8
load:0x40875728,len:0x17d0
entry 0x4086c410
I (23) boot: ESP-IDF 5.1.1 2nd stage bootloader
I (23) boot: compile time Nov  4 2023 22:24:31
I (24) boot: chip revision: v0.0
I (26) boot.esp32c6: SPI Speed      : 80MHz
I (31) boot.esp32c6: SPI Mode       : DIO
I (35) boot.esp32c6: SPI Flash Size : 8MB
I (40) boot: Enabling RNG early entropy source...
I (46) boot: Partition Table:
I (49) boot: ## Label            Usage          Type ST Offset   Length
I (56) boot:  0 otadata          OTA data         01 00 00009000 00002000
I (64) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (71) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (79) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (86) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (94) boot: End of partition table
I (98) boot: No factory image, trying OTA 0
I (103) esp_image: segment 0: paddr=00010020 vaddr=420b0020 size=31e30h (204336) map
I (153) esp_image: segment 1: paddr=00041e58 vaddr=40800000 size=0e1c0h ( 57792) load
I (167) esp_image: segment 2: paddr=00050020 vaddr=42000020 size=aca48h (707144) map
I (312) esp_image: segment 3: paddr=000fca70 vaddr=4080e1c0 size=06ac8h ( 27336) load
I (323) boot: Loaded app from partition at offset 0x10000
I (350) boot: Set actual ota_seq=1 in otadata[0]
I (351) boot: Disabling RNG early entropy source...
I (361) cpu_start: Unicore app
I (361) cpu_start: Pro cpu up.
W (371) clk: esp_perip_clk_init() has not been implemented yet
I (377) cpu_start: Pro cpu start user code
I (377) cpu_start: cpu freq: 160000000 Hz
I (378) cpu_start: Application information:
I (380) cpu_start: Project name:     esp32c6
I (385) cpu_start: App version:      2023.11.0-dev
I (391) cpu_start: Compile time:     Nov  4 2023 22:24:05
I (397) cpu_start: ELF file SHA256:  f94480aefcfde3f8...
I (403) cpu_start: ESP-IDF:          5.1.1
I (407) cpu_start: Min chip rev:     v0.0
I (412) cpu_start: Max chip rev:     v0.99 
I (417) cpu_start: Chip rev:         v0.0
I (422) heap_init: Initializing. RAM available for dynamic allocation:
I (429) heap_init: At 40819A10 len 00062C00 (395 KiB): D/IRAM
I (435) heap_init: At 4087C610 len 00002F54 (11 KiB): STACK/DIRAM
I (442) heap_init: At 50000000 len 00003FE8 (15 KiB): RTCRAM
I (449) spi_flash: detected chip: generic
I (453) spi_flash: flash io: dio
I (457) sleep: Configure to isolate all GPIO pins in sleep state
I (464) sleep: Enable automatic switching of GPIO sleep configuration
I (471) coexist: coex firmware version: 80b0d89
I (476) coexist: coexist rom version 5b8dcfa
I (481) app_start: Starting scheduler on CPU0
I (486) main_task: Started on CPU0
I (490) main_task: Calling app_main()
I (595) main_task: Returned from app_main()
Guru Meditation Error: Core  0 panic'ed (Illegal instruction). Exception was unhandled.

Core  0 register dump:
MEPC    : 0x420a9520  RA      : 0x420a8566  SP      : 0x4081f3c0  GP      : 0x408121f0  
TP      : 0x407ee434  T0      : 0xfffffffd  T1      : 0x80000000  T2      : 0x8155f974  
S0/FP   : 0x00000000  S1      : 0x40200000  A0      : 0x60000000  A1      : 0x3feaafc3  
A2      : 0x60000000  A3      : 0x7ff00000  A4      : 0x00000000  A5      : 0x3fe00000  
A6      : 0x000000fe  A7      : 0x00000001  S2      : 0x3feaafc3  S3      : 0x40200000  
S4      : 0x3feaafc3  S5      : 0x3feaafc3  S6      : 0x60000000  S7      : 0x00000002  
S8      : 0x00000007  S9      : 0x00000018  S10     : 0x00000000  S11     : 0x00000000  
T3      : 0x69636564  T4      : 0x20312068  T5      : 0x74697720  T6      : 0x25203836  
MSTATUS : 0x00001881  MTVEC   : 0x40800001  MCAUSE  : 0x00000002  MTVAL   : 0x000027a2  
MHARTID : 0x00000000  

Stack memory:
4081f3c0: 0x420b5000 0x4201537a 0x60000000 0x3feaafc3 0x00000001 0x40823024 0x00000001 0x420159f0
4081f3e0: 0x60000000 0x3feaafc3 0x00000000 0x40200000 0x00000000 0x00000000 0x4081a804 0x40807204
4081f400: 0x420b5000 0x3f4a56ca 0x43937961 0x4081c1a4 0x420b0000 0x420b0000 0x41ae62e0 0x420a8274
4081f420: 0x40880000 0x4082abf4 0x00000000 0x40200000 0x00000519 0x40823024 0x60000000 0x3feaafc3
4081f440: 0x00000001 0x429e13ce 0x43937961 0x420003ea 0x420b0000 0x41ae62e0 0x4081c154 0x420005dc
4081f460: 0x4082016c 0x00000024 0x420b5000 0x00000102 0x4082016c 0x00000008 0x40814ca8 0x42014468
4081f480: 0x00000000 0x00000005 0x00000005 0x40823024 0x00000000 0x00000000 0x00000000 0x00000000
4081f4a0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x420070d8
4081f4c0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f4e0: 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
4081f500: 0x00000154 0x4081f220 0x0000071b 0x408155ec 0x408155ec 0x4081f504 0x408155e4 0x00000018
4081f520: 0x4081fa80 0x4081fa80 0x4081f504 0x00000000 0x00000001 0x4081d500 0x706f6f6c 0x6b736154
4081f540: 0x00032a00 0x0082058c 0x00000000 0x4081f4f0 0x00000001 0x00000000 0x40823050 0x42048fd8
4081f560: 0x00000000 0x4081a3e8 0x4081a450 0x4081a4b8 0x00000000 0x00000000 0x00000001 0x00000000
4081f580: 0x00000000 0x4082aba8 0x420a9b9e 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f5a0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f5c0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f5e0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f600: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f620: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f640: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x40000000 0x00000204 0x3b305b1b
4081f660: 0x5b6d3633 0x735b5d44 0x6f736e65 0x39303a72 0x203a5d33 0x6c655227 0x76697461 0x75682065
4081f680: 0x6964696d 0x69207974 0x694c206e 0x676e6976 0x6f6f7220 0x203a276d 0x646e6553 0x20676e69
4081f6a0: 0x74617473 0x39372065 0x3833302e 0x25203836 0x74697720 0x20312068 0x69636564 0x736c616d
4081f6c0: 0x20666f20 0x75636361 0x79636172 0x6d305b1b 0x29303000 0x6d305b1b 0x6e6f6900 0x6d305b1b
4081f6e0: 0x305b1b0a 0x0000006d 0x4081f600 0x00000204 0x3b305b1b 0x5b6d3333 0x6f5b5d57 0x313a6174
4081f700: 0x3a5d3630 0x73614c20 0x6f422074 0x7720746f 0x61207361 0x6e75206e 0x646e6168 0x2064656c
4081f720: 0x65736572 0x77202c74 0x206c6c69 0x636f7270 0x20646565 0x73206f74 0x20656661 0x65646f6d
4081f740: 0x206e6920 0x65722030 0x72617473 0x5b1b7374 0x35006d30 0x2c302e35 0x3a776720 0x32393120
4081f760: 0x3836312e 0x312e322e 0x6d305b1b 0x305b1b0a 0x5b1b006d 0x5b006d30 0x00006d30 0x6d30006d
4081f780: 0x5b1b0a00 0x00006d30 0x00006d30 0x6d305b00 0xa5a5a500 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
4081f7a0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5



ELF file SHA256: f94480aefcfde3f8

Rebooting...
```
