### ISSUE TITLE
NeoPixelBus TM1914

### ISSUE THREAD

**Issue by ivanduda** [esphome/issues#5072]
### The problem

Hello. I'm installing the esphome component, neopixel bus. Does not work with addressable LED strip TM1914. I tried configurations with different methods. In HA the object is visible and controlled, but the LED strip does not work.

### Which version of ESPHome has the issue?

 2023.10.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.11.0

### What platform are you using?

ESP32

### Board

esp32-Wroom

### Example YAML snippet

```yaml
esphome:
  name: pixel
  friendly_name: pixel

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

  # a workaround for the latest bug in the neopixel lib bug


# Enable Home Assistant API
api:
  encryption:
    key: "wXuatXXsEa2Iwp//quJJE="

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.3.11
    gateway: 192.168.3.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pixel Fallback Hotspot"
    password: "s58aWewbcVCr"

captive_portal:

# Example configuration entry
light:
  - platform: neopixelbus
    name: "TM1914"
    variant : TM1914
    pin: GPIO23
    num_leds: 10
```
