### ISSUE TITLE
433mhz not transmitting correct signal

### ISSUE THREAD

**Issue by mikekay1** [esphome/issues#508]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 NodeMCU
**Affected component:**

**Description of problem:**
Working in PlatformIO perfectly using RC-Switch code below fires with no repeats and works Infinitely.

**PlatformIO Code-Working**
```
#include <RCSwitch.h>

RCSwitch mySwitch = RCSwitch();

void setup() {
 mySwitch.enableTransmit(0);
 mySwitch.setProtocol(1, 396); 
 Serial.begin(9600);
}

void loop() {
 mySwitch.send("010000000100010100000001");
 Serial.print("Sent Code [On]\n");
 delay(5000);
 mySwitch.send("010000000100010100000011");
 Serial.print("Sent Code [Off]\n");
 delay(5000);
}
```

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: nodemcu_patiolights
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: --
  password: --
    
  manual_ip:
    static_ip: 192.168.1.198
    gateway: 192.168.1.1
    subnet: 255.255.255.0
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: --

ota:
  password: --
  
remote_transmitter:
  pin: D1
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%
  
switch:
  - platform: template
    name: Patio_Lights_Power_Button
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '010000000100010100000001'
          protocol: 
            pulse_length: 396
            sync: [1,31]
            zero: [1,3]
            one: [3,1]
            inverted: false
          repeat: 10
```
_Using known RCSwitch protocol-1 values from https://github.com/sui77/rc-switch/blob/a9da9c36820b02fc5613dfe2437e1187bcf5b402/RCSwitch.cpp#L76_
**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I have tried almost every combination of things possible to get this to work -- in HA the switch doesn't do anything. 

I have confirmed that in the Logs on the ESPhome it is saying it's sending the code. I just don't have the hardware to actually see what was sent. Tried different PINs to no avail.

The outputted values from RC-Switch dumped are in this picture and are all confirmed working using platformIO.

https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/9/1/911884470427008b9d26f40ea0742a382cce09f1.png

**Comment by mikekay1** [comment]
Just keeping this thread updated with my own answers as a log for someone else...

**Resolution**
```
esphome:
  name: nodemcu_patiolights
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid:--
  password: --
    
  manual_ip:
    static_ip: 192.168.1.198
    gateway: 192.168.1.1
    subnet: 255.255.255.0
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: --

ota:
  password: --
  
remote_transmitter:
  pin: D1
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%
  
switch:

  - platform: template
    name: LED_Controller_Power_ON
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '010000000100010100000001'
          protocol: 
            pulse_length: 396
            sync: [1,31]
            zero: [1,3]
            one: [3,1]
            inverted: false
          repeat: 3
  - platform: template
    name: LED_Controller_Power_OFF
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '010000000100010100000011'
          protocol: 
            pulse_length: 396
            sync: [1,31]
            zero: [1,3]
            one: [3,1]
            inverted: false
          repeat: 3
          
  - platform: template
    name: LED_Controller_Power_LIGHT
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '010000000100010100000100'
          protocol: 
            pulse_length: 396
            sync: [1,31]
            zero: [1,3]
            one: [3,1]
            inverted: false
          repeat: 3

  - platform: template
    name: LED_Controller_Power_100
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '010000000100010100000111'
          protocol: 
            pulse_length: 396
            sync: [1,31]
            zero: [1,3]
            one: [3,1]
            inverted: false
          repeat: 3
          
  - platform: template
    name: LED_Controller_Power_50
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '010000000100010100001000'
          protocol: 
            pulse_length: 396
            sync: [1,31]
            zero: [1,3]
            one: [3,1]
            inverted: false
          repeat: 3
          
  - platform: template
    name: LED_Controller_Power_25
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '010000000100010100001001'
          protocol: 
            pulse_length: 396
            sync: [1,31]
            zero: [1,3]
            one: [3,1]
            inverted: false
          repeat: 3
```

**Description of Resolution:**
Not sure if specifying the values for sync,zero,one, inverted made it work because the defaults weren't 'kicking in'. Or whether the repeat 3 is what did it. Not sure but if I had to make an educated guess my bug is somehow related to [this](https://github.com/esphome/issues/issues/120)
