### ISSUE TITLE
mccgq02hl not publishing to esphome/HA

### ISSUE THREAD

**Issue by pauldogg** [esphome/issues#5081]
### The problem

using: [components/miot_mccgq02hl
](https://github.com/dentra/esphome-components/tree/master/components/miot_mccgq02hl)

Values are not published to HA or Esphome, even though connection is successful.

### Which version of ESPHome has the issue?

Firmware: 2023.10.6 (Nov 6 2023, 12:35:23)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core: 2023.11.1, OS 11.1, Frontend: 20231030.1

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

ble

### Example YAML snippet

```yaml
external_components:
  - source: github://dentra/esphome-components

binary_sensor:
  - platform: miot_mccgq02hl
    # String (Required), device MAC-address.
    mac_address: XX:XX:XX:XX:XX:XX
    # String, (Optional), device bind key. Will use "xiaomi_account" from "miot" if absent to automaticaly get the bindkey.
    bindkey: XXXXXXXXXXXXXXXXX
     # String, (Optional), the name of binary sensor
    name: ${upper_devicename} Door
    # BinarySensor (Optional), Light intensivity: on - strong light, off - weak light
    light:
      name: ${upper_devicename} Light
    # BinarySensor (Optional), Alert enabled when door/window has opened for a long (device configured) time
    alert:
      name: ${upper_devicename} Alert
    # Sensor (Optional), Battey Level, %
    battery_level:
      name: ${upper_devicename} Door Battery
    # Sensor (Optional), Battey Voltage, V
    battery_voltage:
      name: ${upper_devicename} Door Voltage
```

### Anything in the logs that might be useful for us?

```txt
device firmware is: 2.1.0_0059

I have XX'd out the private data.

[13:06:32][D][miot:126]: Got MiBeacon: XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX (22)
[13:06:32][D][miot:129]:    [098B] (encrypted) XX:XX:XX:XX:XX:XX RSSI=-48 (excellent)
[13:06:32][D][miot:135]:   Data: AD.0B.B6.82
[13:06:35][D][miot:126]: Got MiBeacon: XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX (22)
[13:06:35][D][miot:129]:    [098B] (encrypted) XX:XX:XX:XX:XX:XX RSSI=-47 (excellent)
[13:06:35][D][miot:135]:   Data: 77.04.EB.51
```

### Additional information

The Esphome logs show a change of state when the device is open or closed, but this data doesn't show up in Esphome front end or in HA.
