### ISSUE TITLE
The dashboard_import -> package_import_url does not support codeberg.org repositories

### ISSUE THREAD

**Issue by hellerbarde** [esphome/issues#5086]
### The problem

1. I don't want to keep my Git repositories on Github or Gitlab. 
2. `dashboard_import -> package_import_url` only supports shorthand Git specifications, which uses esphome.git.GitFile.from_shorthand to parse the URL.
3. That in turn only supports a select set of Git providers, namely Github and Gitlab. 
4. This leaves me at an impasse.

I would suggest that the `dashboard_import` section would support the same configuration block as `packages`.

### Which version of ESPHome has the issue?

2023.10.6

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

dashboard_import

### Example YAML snippet

```yaml
dashboard_import:
  package_import_url: https://my-own-server.example.com/hellerbarde/quinled-esphome/quinled-rgbw.yaml@main
  import_full_config: false
```
