### ISSUE TITLE
Setting up 4 IR transmitters with ESP32

### ISSUE THREAD

**Issue by cypht** [esphome/issues#5096]
### The problem

I am trying to setup 4 IR transmitters with an ESP32. But only two work properly, the 3rd and 4th do not work. BUt they work if put induvidually.

I have set carrier_duty_percent to 50% for each and setup up 4 individual id's for each. Is there anything else I am missing or is this a limitation of esp32?

These are individual iR LED's attached directly to GPIO pin and GND. 

### Which version of ESPHome has the issue?

2023.10.6

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

nodemcu-32s

### Component causing the issue

ir_transmitter

### Example YAML snippet

```yaml
esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

remote_transmitter:
  - id: ir_transmit_living_ac1
    pin: GPIO19
    carrier_duty_percent: 50%
  - id: ir_transmit_living_ac2
    pin: GPIO13
    carrier_duty_percent: 50%
  - id: ir_transmit_dining
    pin: GPIO32
    carrier_duty_percent: 50%

climate:
  - platform: daikin_brc
    name: "Living Room AC One"
    transmitter_id: ir_transmit_living_ac1
    supports_heat: false
    on_control:
      - lambda: |-
          if (x.get_mode() != CLIMATE_MODE_OFF) {
              x.set_mode("COOL");
          }
  - platform: daikin_brc
    name: "Living Room AC Two"
    transmitter_id: ir_transmit_living_ac2
    supports_heat: False
    on_control:
      - lambda: |-
          if (x.get_mode() != CLIMATE_MODE_OFF) {
              x.set_mode("COOL");
          }
  - platform: daikin_brc
    name: "Dining Room AC"
    transmitter_id: ir_transmit_dining
    supports_heat: False
    on_control:
      - lambda: |-
          if (x.get_mode() != CLIMATE_MODE_OFF) {
              x.set_mode("COOL");
          }
```
