### ISSUE TITLE
LD2410 Sensor - If timeout specified, other numbers are no longer optional

### ISSUE THREAD

**Issue by dafunkydan** [esphome/issues#5097]
### The problem

If `timeout: ` in your configuration is your only configuration under 'number', you get the Validation-Error `some but not all values in the same group of inclusion`.
In Order to use timeout, you have to specify at least `light_threshold` / `max_move_distance_gate` / `max_still_distance_gate` as well - they are no longer 'Optional' as documented, but become mandatory.

### Which version of ESPHome has the issue?

2023.10.6

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

ld2410

### Example YAML snippet

```yaml
#To reproduce this Error, configure only timeout as number
number:
  - platform: ld2410
    timeout:
      id: timeout_detection

#To solve that, define the following numbers as well (remove Hashtag)
#    light_threshold:
#      id: light_threshold
#    max_move_distance_gate:
#      id: max_move_distance_gate
#    max_still_distance_gate:
#      id: max_still_distance_gate
```
