### ISSUE TITLE
http_request response body truncated

### ISSUE THREAD

**Issue by gituser-rk** [esphome/issues#5098]
### The problem

when requesting a status json from a gen1 shelly with the http_request component I get a truncated json body back.

i.e. http://192.168.178.58/status gives back this json (which is 1145 byte):
{"wifi_sta":{"connected":true,"ssid":"Tosse_T","ip":"192.168.178.58","rssi":-79},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":false},"time":"22:39","unixtime":1699738764,"serial":24707,"has_update":true,"mac":"E8DB84D7S828","cfg_changed_cnt":17,"actions_stats":{"skipped":0},"relays":[{"ison":true,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"overpower":false,"source":"cloud"}],"meters":[{"power":0.00,"overpower":0.00,"is_valid":true,"timestamp":1699742364,"counters":[0.000, 0.000, 0.000],"total":83231597}],"inputs":[{"input":0,"event":"","event_cnt":0}],"temperature":22.24,"overtemperature":false,"tmp":{"tC":22.24,"tF":72.03, "is_valid":true},"temperature_status":"Normal","ext_sensors":{"temperature_unit":"C"},"ext_temperature":{"0":{"hwID":"28f8ca75d0034cdd","tC":5.06,"tF":41.11}},"ext_humidity":{},"update":{"status":"pending","has_update":true,"new_version":"20230913-113709/v1.14.0-gcb84623","old_version":"20220209-094317/v1.11.8-g8c7bb8d","beta_version":"20231107-164450/v1.14.1-rc1-g0617c15"},"ram_total":50456,"ram_free":37260,"fs_size":233681,"fs_free":148843,"uptime":52964766}

when logging the response body I saw only this fragment:
{"wifi_sta":{"connected":true,"ssid":"Tosse_T","ip":"192.168.178.58","rssi":-79},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":false},"time":"22:39","unixtime":1699738764,"serial":24707,"has_update":true,"mac":"E8DB84D7S828","cfg_changed_cnt":17,"actions_stats":{"skipped":0},"relays":[{"ison":true,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"overpower":false,"source":"cloud"}],"meters":[{"power":0.00,"overpower":0.00,"is

you see, it's truncated after 942 characters. 

### Which version of ESPHome has the issue?

2023.10.6

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

lolin32

### Component causing the issue

http_request

### Example YAML snippet

```yaml
esphome:
  name: wallclock-yvonne
  friendly_name: wallclock-yvonne

time:
  - platform: sntp
    id: ntp
    timezone: Europe/Berlin
    servers: 172.16.1.1
    on_time:
      - seconds: 0
        minutes: /15
        then:
          - http_request.get: 
              url: http://192.168.178.58:80/status
              verify_ssl: false
              on_response:
                then:
                  - logger.log:
                      format: 'Response status: %d, Duration: %u ms'
                      args:
                        - status_code
                        - duration_ms
                  - lambda: |-
                      if (status_code == 200) {
                        const char* httpResponse = id(http_request_data).get_string();
                        std::string httpResponseStr = httpResponse;
                        //ESP_LOGD("http_response", "Response %s", httpResponseStr.c_str());
                        
                        json::parse_json(httpResponseStr, [](JsonObject root) {

                          id(temperature).publish_state(root["ext_temperature][0]["tC"]);
                        });                          
                      } else {
                        //ESP_LOGD("http_response", "Failed connection to remote sensor. Status code: %d", status_code);
                        id(temperature).publish_state(99);
                      }              

esp32:
  board: lolin32
  framework:
    type: arduino

# Enable logging
logger:

api:
  reboot_timeout: 0s

ota:
  password: "dh7shdas7dsdhsd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Wallclock"
    password: "GDgfd3dghsfmsfsaksKff"

captive_portal:

spi:
  clk_pin: 18
  mosi_pin: 23

sensor:
  - platform: template
    name: "temperature"
    id: temperature
  - platform: adc
    pin: 33
    name: "LDR"
    id: lumiosity
    update_interval: 0.2s
    filters:
    - multiply: 12

http_request:
  useragent: esphome/device
  timeout: 2s
  id: http_request_data
  

font:
  - file: "userdata_fonts/Arial-Narrow.ttf"
    id: digit_font1
    #size: 9
    size: 11
    glyphs:
       [':', '°', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'C', '.', ',', 'a', 'n']
display:
  - platform: max7219digit
    id: display_max
    setup_priority: -100
    cs_pin: 15
    num_chips: 6
    intensity: 5
    scroll_speed: 20ms
    scroll_delay: 5s
    scroll_dwell: 1s
    scroll_mode: CONTINUOUS
    lambda: |-
       it.intensity((int)id(lumiosity).state);
       it.strftime(24, -3, id(digit_font1), "%H:%M", id(ntp).now());
        if (id(temperature).state <= -10.0) {
          //too long, save some space
          it.printf(0, -1, id(digit_font1), "%.1f°", id(temperature).state);                        
        } else if (id(temperature).state < 10.0 && id(temperature).state >= 0.0) {
          it.printf(0, -1, id(digit_font1), "   %.1f°", id(temperature).state);     
        } else if (id(temperature).state < 0.0 && id(temperature).state > -10.0) {
          it.printf(0, -1, id(digit_font1), "  %.1f°", id(temperature).state);
        } else {
          it.printf(0, -1, id(digit_font1), " %.1f°", id(temperature).state);
        }
```

### Additional information

when changing the URL to a openweathermap API call, I'm able to retrieve the temperature within the jsaon with this code. but the response body (json) size is only below 500 byte ...
