### ISSUE TITLE
Fastled not clearing previous color

### ISSUE THREAD

**Issue by ministryofsillywalks** [esphome/issues#510]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

FastLed

**Description of problem:**
When switching to an effect the previous settings don't get cleared.
For example I have an effect which turns the first 20 Leds one color and doesn't do anything to the others. These then retain their color from the previous settings.
This isn't too bad as I can just turn them off in the effect.
I feel like fastled is missing the option
FastLED.clear();

However when I turn off the light coming from an effect it reverts to the previous static color for a second and then turns off.
For example if I come from a static white light and switch to rainbow then that works.
Turning off the light from rainbow has the leds flash white for one second and only then turn off.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: badezimmer
  platform: ESP8266
  board: nodemcuv2

wifi:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Badezimmer Licht"
    pin: D0
    
light:
  - platform: fastled_spi
    chipset: WS2801
    data_pin: D5
    clock_pin: D6
    num_leds: 60
    rgb_order: RGB
    name: "FastLED WS2801 Light"
    effects:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
      - addressable_lambda:
          name: "NightLight"
          update_interval: 16ms
          lambda: |-
            it.range(0, 20) = light::ESPColor(255, 0, 18);
            it.range(21, 60) = light::ESPColor(0, 0, 0);

      - addressable_lambda:
         
          name: "Christmas RedGreen"
          lambda: |-
       
            for (int i = 1; i <  it.size(); i+=2) {
            it[i] = light::ESPColor(255, 0, 18);
            }
            
            for (int i = 0; i <  it.size(); i+=2) {
            it[i] = light::ESPColor(0, 0, 0);
            }

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
