### ISSUE TITLE
MAX6675 Reporting 0.0C when no device is connected.

### ISSUE THREAD

**Issue by schmidty1913** [esphome/issues#5101]
### The problem

MAX6675 Reporting 0.0C when no device is connected.

### Which version of ESPHome has the issue?

ESPHome version 2023.10.6 compiled on Nov 12 2023, 21:35:59

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

ESP32 2 Channel 5V Relay Module

### Component causing the issue

MAX6675

### Example YAML snippet

```yaml
captive_portal:

spi:
  miso_pin: 4
  clk_pin: 19

#virtual button to turn on heater
button:
- platform: template
  id: virtual_heater_on
  name: "Heater On"
  on_press:
    then:
      - if:
          condition:
            binary_sensor.is_off: high_temperature_safety
          then:
            - output.turn_on: heater_relay
            - binary_sensor.template.publish:
                  id: heater
                  state: ON
  
#virtual button to turn off heater
- platform: template
  id: virtual_heater_off
  name: "Heater Off"
  on_press:
    - output.turn_off: heater_relay
    - binary_sensor.template.publish:
                  id: heater
                  state: OFF

binary_sensor:
- platform: template
  name: "Heater"
  id: heater
  publish_initial_state: True

#heater status
- platform: template
  device_class: safety
  name: "High Temperature Safety"
  id: high_temperature_safety

light:
 #internal output to status of heater
- platform: status_led
  name: "Heater Status"
  id: heater_status
  pin: 23

output:
#internal output to actually control the relay
- platform: gpio
  id: second_relay
  pin: 17

#internal output to actually control the relay
- platform: gpio
  id: heater_relay
  pin: 16
  
#temperature sensor with high temp protections  
sensor:
- platform: max6675
  name: "sand battery skin temperature"
  cs_pin: 18
  update_interval: 10s
  filters:
  - timeout: 
      timeout: 60s
      value: -101.0
  on_value_range:
    - below: -100.0
      then:
        - logger.log: "temperature not real"
        - binary_sensor.template.publish:
            id: high_temperature_safety
            state: ON
        - output.turn_off: heater_relay
        - binary_sensor.template.publish:
            id: heater
            state: OFF
  # High Temperature Safety On
    - above: 240.0
      then:
        - logger.log: "temperature too high"
        - binary_sensor.template.publish:
            id: high_temperature_safety
            state: ON
        - output.turn_off: heater_relay
        - binary_sensor.template.publish:
                  id: heater
                  state: OFF
  # High Temperature Safety Off
    - above: -100.0
      below: 201.0
      then:
        - logger.log: "temperature back to normal"
        - binary_sensor.template.publish:
            id: high_temperature_safety
            state: OFF
```

### Anything in the logs that might be useful for us?

```txt
[21:49:30][D][max6675:046]: 'sand battery skin temperature': Got temperature=0.0°C
[21:49:30][D][sensor:094]: 'sand battery skin temperature': Sending state 0.00000 °C with 1 decimals of accuracy
```

### Additional information

Board being used:
https://a.co/d/6JzUKae
Sensor being used:
https://a.co/d/h8DliEY
