### ISSUE TITLE
Dashboard shows all non-API devices offline

### ISSUE THREAD

**Issue by ldeffenb** [esphome/issues#5112]
### The problem

After upgrading to ESPHome 2023.11.0 just now, all of my non-API-using ESPHome devices show offline in the dashboard.  The Visit link still works, and the device can be updated over-the-air, so the nodename.local mDNS is actually working.

I'm wondering if https://github.com/esphome/esphome/pull/5725 may have broken the dashboard for non-API (MQTT-only) devices?

None of my devices have fixed IPs, but they all use DHCP.

### Which version of ESPHome has the issue?

ESPHome 2023.11.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

nodemcu + shelly

### Example YAML snippet

```yaml
esphome:
  name: office

esp8266:
  board: esp01_1m

# Enable logging
logger:
#  level: DEBUG
  level: WARN
  
# Enable Home Assistant API
#api:
#  encryption:
#    key: "SGEa3pJJqtvtilDRy++gJMLvD1STvfp1+j1v+DTT89I="

ota:
  password: "b37d01de184bb2593aa591647df07c5f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office Fallback Hotspot"
    password: "GPxtOZJSDdx7"

captive_portal:

mqtt:
  broker: 192.168.10.4
  topic_prefix: "esphome/office"
  discovery: true

# from https://www.esphome-devices.com/devices/Shelly-1PM
web_server:
  port: 80
  auth:
    username: admin
    password: admin
```

### Additional information

Devices with the API enabled seem to show online properly.   It's only my MQTT-only devices that show this issue, both before and after flashing them to the latest release.  They showed online perfectly fine before the ESPHome update was installed.
