### ISSUE TITLE
Wifi not connecting after update to 2023.11.0

### ISSUE THREAD

**Issue by grego1981** [esphome/issues#5116]
### The problem

I have updated 2 wemos NodeMCU to the new version and after that the devices went offline, I have hooked them up to USB and get the following logs. No change has been made to my wifi network. Also although from the log the local AP is activated, it is not scanned by any of my devices. 

### Which version of ESPHome has the issue?

2023.11.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.2

### What platform are you using?

ESP8266

### Board

Wemos NodeMCU

### Component causing the issue

uart

### Example YAML snippet

```yaml
esphome:
  name: children-bedroom-air-sensor
  friendly_name: children_bedroom_air_sensor

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG
  hardware_uart: UART0
  #baud_rate: 0
# Enable Home Assistant API
api:
  encryption:
    key: "Xn0Yye6o1Sf4hs5aZd9e2Lt0sSZKix6NmSL8nNVTwMo="

web_server:
  port: 80
  version: 2
  include_internal: true

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Children-Bedroom-Air-Sensor"
    password: "42yUjEbMJ4DM"

captive_portal:

uart:
  rx_pin: GPIO4
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"
```

### Anything in the logs that might be useful for us?

```txt
[C][ota:473]: There have been 1 suspected unsuccessful boot attempts.
[I][app:029]: Running through setup()...
[C][uart.arduino_esp8266:059]: Setting up UART bus...
[C][wifi:038]: Setting up WiFi...
[C][wifi:051]: Starting WiFi...
[C][wifi:052]:   Local MAC: 2C:3A:E8:2F:7F:09
[D][wifi:441]: Starting scan...
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][wifi:456]: Found networks:
[D][wifi:458]:   No network found!
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][wifi:441]: Starting scan...
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][wifi:456]: Found networks:
[D][wifi:458]:   No network found!
[D][wifi:441]: Starting scan...
[D][wifi:456]: Found networks:
[D][wifi:458]:   No network found!
[D][wifi:441]: Starting scan...
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][wifi:456]: Found networks:
[D][wifi:458]:   No network found!
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][wifi:441]: Starting scan...
[D][pm1006:091]: Got PM2.5 Concentration: 0 µg/m³
[D][sensor:093]: 'Particulate Matter 2.5µm Concentration': Sending state 0.00000 µg/m³ with 0 decimals of accuracy
[D][wifi:456]: Found networks:
[D][wifi:458]:   No network found!
[D][wifi:441]: Starting scan...
[I][wifi:165]: Starting fallback AP!
[C][wifi:239]: Setting up AP...
[C][wifi:241]:   AP SSID: 'Children-Bedroom-Air-Sensor'
[C][wifi:242]:   AP Password: '42yUjEbMJ4DM'
[C][wifi:251]:   IP Address: 192.168.4.1
```
