### ISSUE TITLE
MQTT Client with default config for HomeAssistant broken in ESPHome 2023.11.1

### ISSUE THREAD

**Issue by KidA001** [esphome/issues#5136]
### The problem

Using basic MQTT Client config for HomeAssistant as described [here](https://esphome.io/components/mqtt.html#:~:text=.-,Using%20with%20Home%20Assistant) causes ESPHome to throw an error when compiling `error: 'const struct esp_mqtt_event_t' has no member named 'qos' qos(event.qos)` (Full stack trace below)

### Which version of ESPHome has the issue?

2023.11.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.1

### What platform are you using?

ESP32

### Board

ESP32S3

### Component causing the issue

MQTT

### Example YAML snippet

Using basic MQTT Config. This config has not changed and has been used in previous versions without issue
```yaml
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_un
  password: !secret mqtt_pw
```

### Anything in the logs that might be useful for us?

Full ESP YAML:

```yaml
esphome:
  name: propane-tank-main-house
  friendly_name: Propane Tank Main House
  on_boot:
    then:
      - output.turn_on: pwr_pin
      - delay: 1s
  on_shutdown:
    then:
      - output.turn_off: pwr_pin
      - logger.log: "Goodnight sweet prince"

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.1.1

# Deep sleep
deep_sleep:
  run_duration: 10s
  sleep_duration: 6h

# Enable logging
logger:


ota:
  password: redacted

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Propane-Tank-Main-House"
    password: redacted

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_un
  password: !secret mqtt_pw

output:
  - platform: gpio
    pin: GPIO35
    id: pwr_pin

    
sensor:
  - platform: adc
    pin: GPIO10
    name: "Remote Hall"
    update_interval: 2s
    attenuation: 11db
    unit_of_measurement: "%"
    filters:
      # (𝑛 − min / max−min) × 100
      # full: 1.48
      # empty: 1.9
      - lambda: return ((1.48 - 1.9) / -0.419999 ) * 100;
```

### Additional information

Full stack trace
```text
INFO ESPHome 2023.11.2
INFO Reading configuration /config/esphome/propane-tank-main-house.yaml...
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING GPIO35 is used by the PSRAM interface on ESP32-S3R8 / ESP32-S3R8V and should be avoided on these models
INFO Generating C++ source...
INFO Compiling app...
Processing propane-tank-main-house (board: esp32-s3-devkitc-1; framework: arduino; platform: platformio/espressif32@5.1.1)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch3 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch3
Dependency Graph
|-- AsyncTCP-esphome @ 2.0.1
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/propane-tank-main-house/src/esphome/components/mqtt/custom_mqtt_device.cpp.o
Compiling .pioenvs/propane-tank-main-house/src/esphome/components/mqtt/mqtt_backend_esp32.cpp.o
Compiling .pioenvs/propane-tank-main-house/src/esphome/components/mqtt/mqtt_client.cpp.o
Compiling .pioenvs/propane-tank-main-house/src/esphome/components/mqtt/mqtt_component.cpp.o
In file included from src/esphome/components/mqtt/mqtt_backend_esp32.cpp:4:
src/esphome/components/mqtt/mqtt_backend_esp32.h: In constructor 'esphome::mqtt::Event::Event(const esp_mqtt_event_t&)':
src/esphome/components/mqtt/mqtt_backend_esp32.h:38:19: error: 'const struct esp_mqtt_event_t' has no member named 'qos'
         qos(event.qos),
                   ^~~
src/esphome/components/mqtt/mqtt_backend_esp32.h:39:19: error: 'const struct esp_mqtt_event_t' has no member named 'dup'
         dup(event.dup),
                   ^~~
*** [.pioenvs/propane-tank-main-house/src/esphome/components/mqtt/mqtt_backend_esp32.cpp.o] Error 1
In file included from src/esphome/components/mqtt/mqtt_client.h:13,
                 from src/esphome/components/mqtt/mqtt_component.h:11,
                 from src/esphome/components/mqtt/mqtt_component.cpp:1:
src/esphome/components/mqtt/mqtt_backend_esp32.h: In constructor 'esphome::mqtt::Event::Event(const esp_mqtt_event_t&)':
src/esphome/components/mqtt/mqtt_backend_esp32.h:38:19: error: 'const struct esp_mqtt_event_t' has no member named 'qos'
         qos(event.qos),
                   ^~~
src/esphome/components/mqtt/mqtt_backend_esp32.h:39:19: error: 'const struct esp_mqtt_event_t' has no member named 'dup'
         dup(event.dup),
                   ^~~
In file included from src/esphome/components/mqtt/mqtt_client.h:13,
                 from src/esphome/components/mqtt/custom_mqtt_device.h:7,
                 from src/esphome/components/mqtt/custom_mqtt_device.cpp:1:
src/esphome/components/mqtt/mqtt_backend_esp32.h: In constructor 'esphome::mqtt::Event::Event(const esp_mqtt_event_t&)':
src/esphome/components/mqtt/mqtt_backend_esp32.h:38:19: error: 'const struct esp_mqtt_event_t' has no member named 'qos'
         qos(event.qos),
                   ^~~
src/esphome/components/mqtt/mqtt_backend_esp32.h:39:19: error: 'const struct esp_mqtt_event_t' has no member named 'dup'
         dup(event.dup),
                   ^~~
In file included from src/esphome/components/mqtt/mqtt_client.h:13,
                 from src/esphome/components/mqtt/mqtt_client.cpp:1:
src/esphome/components/mqtt/mqtt_backend_esp32.h: In constructor 'esphome::mqtt::Event::Event(const esp_mqtt_event_t&)':
src/esphome/components/mqtt/mqtt_backend_esp32.h:38:19: error: 'const struct esp_mqtt_event_t' has no member named 'qos'
         qos(event.qos),
                   ^~~
src/esphome/components/mqtt/mqtt_backend_esp32.h:39:19: error: 'const struct esp_mqtt_event_t' has no member named 'dup'
         dup(event.dup),
                   ^~~
*** [.pioenvs/propane-tank-main-house/src/esphome/components/mqtt/custom_mqtt_device.cpp.o] Error 1
*** [.pioenvs/propane-tank-main-house/src/esphome/components/mqtt/mqtt_component.cpp.o] Error 1
*** [.pioenvs/propane-tank-main-house/src/esphome/components/mqtt/mqtt_client.cpp.o] Error 1
========================== [FAILED] Took 3.69 seconds ==========================
```

**Comment by ssieb** [comment]
Do you have a `custom_components` directory?  I tested compiling and there's no issue.

**Comment by KidA001** [comment]
> Do you have a `custom_components` directory? I tested compiling and there's no issue.

Not in the `config/esphome` dir, but I do have `config/custom_components` - would that effect ESPHome?

**Comment by KidA001** [comment]
Seems like this issue was specific to the board settings I was using, I updated to:
```yaml
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework:
    type: arduino
    version: 2.0.5
    platform_version: 5.2.0
```

And that fixed my issues
