### ISSUE TITLE
problems flashing my lights that have an esp01 and don't have USB

### ISSUE THREAD

**Issue by compujunk** [esphome/issues#5137]
### The problem

I have the following problem, I have about 30 WiFi lamps with an esp01 in them and ESPHome on them. Now a few things have changed in the config and I want to flash the new firmware on the lamps, but I keep getting the message:

"ERROR Error binary size: Error: ESP has been flashed with wrong flash size. Please choose the correct 'board' option (esp01_1m always works) and then flash over USB"

The problem is that I don't have a USB connection on those lamps, so opening them and then flashing them via serial is not an option either.
How can I still flash these lamps with the current ESPHome? Previously I never had this problem with those lamps.
My Sonoff Basics also have that message, but I can still flash them via serial, even though they are often in hard-to-reach places.

### Which version of ESPHome has the issue?

2023.11.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.3

### What platform are you using?

ESP8266

### Board

esp01

### Example YAML snippet

```yaml
substitutions:
  devicename: eettafellamp1
  friendly_name: eettafellamp1

packages:
  device_base: !include common/device_base.yaml

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  build_path: ./build/${devicename}

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap:
    ssid: "Fallback $devicename"
    password: !secret wifi_password

captive_portal:

web_server:
 port: 80

light:
  - platform: cwww
    name: $friendly_name
    id: $devicename
    cold_white: output_component1
    warm_white: output_component2
    cold_white_color_temperature: 3500 K
    warm_white_color_temperature: 2000 K

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: 14
  - platform: esp8266_pwm
    id: output_component2
    pin: 12

sensor:
  - platform: homeassistant
    entity_id: sensor.licht_sensor
    id: licht_sensor
    on_value_range:
        - above: 1000
          then:
            - light.turn_on: $devicename
        - below: 950
          then:
            - light.turn_off: $devicename
```
