### ISSUE TITLE
BPI-Leaf-S3  can not bootstart

### ISSUE THREAD

**Issue by kylin7226** [esphome/issues#5143]
### The problem

BPI-Leaf-S3  can not boot start

### Which version of ESPHome has the issue?

2023.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.3

### What platform are you using?

ESP32-IDF

### Board

Banana Pi BPI-Leaf-S3

### Example YAML snippet

```yaml
esphome:
  name: s3-test

esp32:
  board: bpi_leaf_s3
  framework:
    type: esp-idf


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lDvXJXBBgqAm+GCZSwoeo+IEUbGcAhtkanjKVWkns3s="

ota:
  password: "447cafbe6e5b69bea6b3c40887c2cf1d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.199.xx
    subnet: 255.255.255.0
    gateway: 192.168.199.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S3-Test Fallback Hotspot"
    password: "LTBt7zvE7IeC"

captive_portal:
    
web_server:

# Example configuration entry
output:
  - platform: ledc
    pin: GPIO48
    id: gpio_48

# Example usage in a light
light:
  - platform: monochromatic
    output: gpio_48
    name: "S3 Light"
```

### Anything in the logs that might be useful for us?

```txt
Using 'COM5' as serial port.
Showing logs:
[00:42:13]ESP-ROM:esp32s3-20210327
[00:42:13]Build:Mar 27 2021
[00:42:13]rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[00:42:13]Saved PC:0x400454d5
[00:42:13]SPIWP:0xee
[00:42:13]mode:QIO, clock div:1
[00:42:13]load:0x3fce3808,len:0x162c
[00:42:13]ets_loader.c 78 
[00:42:14]
Serial port closed!
```

### Additional information

but in Tasmota32-CDC is ok,
the tasmota logs:
Using 'COM5' as serial port.
Showing logs:
[00:36:18].1 (PSRAM)
[00:36:18]00:00:00.139 UFS: FlashFS mounted with 312 kB free
[00:36:18]00:00:00.140 TFS: File '.settings' not found
[00:36:18]00:00:00.140 TFS: File '.settings.lkg' not found
[00:36:18]00:00:00.141 CFG: Use defaults
[00:36:18]00:00:00.252 QPC: Reset
[00:36:18]00:00:00.357 BRY: Trying to expand FS by 4096 kB
[00:36:18]00:00:00.754 BRY: Successfully resized FS, restarting00:00:01.942 HTP: Web server active on tasmota-C18B0C-2828 with IP address 192.168.4.1
[00:36:19]00:00:02.918 APP: Restarting
[00:36:19]ESP-ROM:esp32s3-20210327
[00:36:19]Build:Mar 27 2021
[00:36:19]rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[00:36:19]Saved PC:0x40375c3d
[00:36:19]SPIWP:0xee
[00:36:19]mode:DIO, clock div:1
[00:36:19]load:0x3fce3808,len:0x128
[00:36:19]load:0x403c9700,len:0xb90
[00:36:19]load:0x403cc700,len:0x28cc
[00:36:19]SHA-256 comparison failed:
[00:36:19]Calculated: 6ff891185212526dc4a8a02f94359cdb7c96c9ee016fd617c4433ef60c921ae8
[00:36:19]Expected: 2fccfe0baabcabc13349ed33dd0cb9dda386de5630d8160a25c7b2d9a6dc3df3
[00:36:19]Attempting to boot anyway...
[00:36:19]entry 0x403c98b8
[00:36:19]
[00:36:19]00:00:00.001-289/12 CMD: Using USB CDC
[00:36:19]00:00:00.002-289/12 HDW: ESP32-S3 v0.1 (PSRAM)
[00:36:19]00:00:00.014-287/12 UFS: FlashFS mounted with 4404 kB free
[00:36:19]00:00:00.023 CFG: Loaded from File, Count 2
[00:36:19]00:00:00.024 FRC: Some settings have been reset (2)
[00:36:19]00:00:00.142 BRY: Berry initialized, RAM used=5172 bytes
[00:36:19]00:00:00.149 TFS: File '.drvset003' not found
[00:36:19]00:00:00.152 Project tasmota - Tasmota Version 13.2.0(tasmota32)-2_0_14(2023-10-19T09:05:32)
[00:36:20]00:00:00.202 WIF: WifiManager active for 3 minutes
[00:36:20]00:00:00.876 HTP: Web server active on tasmota-C18B0C-2828 with IP address 192.168.4.1

**Comment by ssieb** [comment]
You need to set the platformio options to use the DIO flash mode.
```yaml
esphome:
  ...
  platformio_options:
    board_build.flash_mode: dio
```
