### ISSUE TITLE
Changing set-point in PID-controller affects derivative

### ISSUE THREAD

**Issue by Newspaperman57** [esphome/issues#5145]
### The problem

Changing the set-point in the PID-controller caused the derivative term to see a change, and pull the output hard in the direction the change was in.

I'm working with 30 seconds of sampling, so even though the error in the derivative term was only for 1 sample, it strongly affects the output for 30 seconds.

In this example i first changed the setpoint 1 degree down, and then 40 seconds later 1 degree up. Notice how the derivative term gets low for 30 seconds and shutting the output completely off (Which actually isn't affecting anything in this example since P also pulls the output to 0), and then settles when the anomaly exits the running average.
But when i increase the setpoint by 1 degree, it again goes very high, causing the output to be 100% for 30 seconds, which in my case is enough to overshoot the target by 5-10 degrees (Allowable temperature-swing is 2-3 degrees in my case, which the PID is tuned for)

![image](https://github.com/esphome/issues/assets/1321620/96fe128b-a949-4ba7-95ff-48b0066b0b22)

### Which version of ESPHome has the issue?

2023.11.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

NodeMCU

### Component causing the issue

pid

### Additional information

I have already identified and fixed the problem:

https://github.com/esphome/esphome/pull/4737

Using the fixed code the derivative no longer changes, only the proportional:
![image](https://github.com/esphome/issues/assets/1321620/927807ae-9f65-497d-b813-7844f400528c)

**Comment by nagyrobi** [comment]
Can you please post your pid climate config (including tuned values)?

**Comment by Newspaperman57** [comment]
Thank you for your comment.

Note that i have identified the problem in the code and submitted a PR back in April that went unnoticed:
https://github.com/esphome/esphome/pull/4737

I don't believe the tuned values i'm using are relevant for this bug, but to give an idea of my use case i was using a dallas probe and a slow_pwm output with a period of 1s on a repurposed 3d-printer bed for keeping newly hatched chicks warm. The heater was quite overpowered for this task, only using 5-7% dutycycle most of the time. 10 seconds at full power meant a temperature-increase of more than 10 degrees and taking up to a minute to cool down again, potentially hurting the chicks.

I have quite a lot of experience with PID-controllers from my education as software-engineer, custom built 3d-printers, stabilization in hobby-grade quadcopters, and other diy projects using arduinos and esp's before i started using homeassistant, so i'm very confident in the tuned values being correct for my setup.
I was not experiencing oscillation, and only saw overshoot when changing the target temperature, which i identified as being caused by the derivative reacting erroneously to the change.

Here is an untested example-config from the documentation of the modules, using a dallas temperature probe and a slow_pwm output with a period of 1s:

```
# Example configuration entry
dallas:
  - pin: 23

# Individual sensors
sensor:
  - platform: dallas
    address: 0x1c0000031edd2a28
    name: "Livingroom Temperature"
    id: temperature_sensor
    
# Example configuration entry
output:
  - platform: slow_pwm
    pin: D1
    id: heater
    period: 1s

# Example configuration entry
climate:
  - platform: pid
    name: "PID Climate Controller"
    sensor: temperature_sensor
    default_target_temperature: 21°C
    heat_output: heater
    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301
      output_averaging_samples: 5      # smooth the output over 5 samples
      derivative_averaging_samples: 5  # smooth the derivative value over 10 samples
```
