### ISSUE TITLE
Wrong I2C Timing on ESP32S2

### ISSUE THREAD

**Issue by swifty99** [esphome/issues#5151]
### The problem

Moving from ESP32 to ESP32S2 boards I2C sensors were blocking.

I did a bus timing and the clock is slowed down by a factor of 80.

bus monitored at default i2c values with sensor ads1115:
![image](https://github.com/esphome/issues/assets/6912030/fa000ea2-a614-4950-a900-133341565294)

bus monitoring settings to 800kHz I2C frequency:
![image](https://github.com/esphome/issues/assets/6912030/3eca7621-c929-40f1-9044-d1147860b531)
no blocking at this speed setting

Same sensor, same SW on a ESP32 has correct timings.

### Which version of ESPHome has the issue?

2023.11

### What type of installation are you using?

local, windows

### Which version of Home Assistant has the issue?

2023.11.1

### What platform are you using?

ESP32-IDF

### Board

lolin_s2_mini

### Component causing the issue

i2c, ads1115

### Example YAML snippet

```yaml
i2c:
  sda: GPIO13
  scl: GPIO14
  scan: true
  id: bus_a
  frequency: 800kHz
    


ads1115:
  - address: 0x48
    continuous_mode: true

 
  - platform: ads1115
    multiplexer: 'A0_GND'
    id: lv_batt_volt
    gain: 4.096
```
