### ISSUE TITLE
Latest release breaks distance sensor

### ISSUE THREAD

**Issue by jl-678** [esphome/issues#5155]
### The problem

I have ESPHome connected to an ESP32 board with an Ultrasonic distance senor measuring the level of salt in my water softener system. I have the last 90 days, I have monitored the distance readings to understand the high and low level of salt.

All of a sudden, the measurement went from .11/.12 to 1.02. There was no change in salt levels, and the only modification was a firm upgrade. See the image below for a graphic example of the spike on the far right:

![Screenshot 2023-11-25 1 49 51 PM](https://github.com/esphome/issues/assets/17790404/c651da0c-7fa7-4598-a5fe-0443168e0f9e)

Notice how the levels are stable until 11/17 when I refilled the salt at which point it dropped to .11/.12 and then recently it jumped to a meter for no apparent reason.

### Which version of ESPHome has the issue?

2003.11.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.3

### What platform are you using?

ESP32

### Board

KeeYees ESP32

### Example YAML snippet

```yaml
sensor:
  - platform: ultrasonic
    trigger_pin: 22
    echo_pin: 23
    name: "Ultrasonic Sensor"
    update_interval: 300s
```
