### ISSUE TITLE
RP2040 PIO LED Strip library causes device to fail when using more than 2 strips

### ISSUE THREAD

**Issue by Binvention** [esphome/issues#5158]
### The problem

I am trying to hook up 5 rgb led strips to a pi pico w and I got it working no problem for a single led strip however once I got past two strips it then either fails to connect to wifi or if it does eventually connect to wifi it fails to connect to the api socket. The rp2040 chip also gets very hot when I tried to connect all 5 (thought I killed my pico w until I uploaded a different sketch and confirmed it still works). It looks like its making the wifi connection drop periodically but I'm not sure. I've tried different combinations of using pio 0 and 1 but that doesn't seem to make a difference in getting me past 2 led strips even though its suppose to be able to handle 4 per pio

### Which version of ESPHome has the issue?

2023.11.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.3

### What platform are you using?

RP2040

### Board

Pi Pico W

### Component causing the issue

RP2040 PIO LED Strip

### Example YAML snippet

```yaml
light:
  - platform: partition
    name: "LEDs"
    segments:
      - id: strip0
        from: 0
        to: 49
      - id: strip1
        from: 0
        to: 49
      # - id: strip2
        # from: 0
        # to: 49
      # - id: strip3
      #   from: 0
      #   to: 49
      # - id: strip4
      #   from: 0
      #   to: 49
  - platform: rp2040_pio_led_strip
    id: strip0
    chipset: ws2812b
    pin: GPIO18
    num_leds: 50
    rgb_order: RGB
    pio: 1
    internal: true
  - platform: rp2040_pio_led_strip
    id: strip1
    chipset: ws2812b
    pin: GPIO19
    num_leds: 50
    rgb_order: RGB
    pio: 1
    internal: true
  - platform: rp2040_pio_led_strip
    id: strip2
    chipset: ws2812b
    pin: GPIO20
    num_leds: 50
    rgb_order: RGB
    pio: 1
    internal: true
  # - platform: rp2040_pio_led_strip
  #   id: strip3
  #   chipset: ws2812b
  #   pin: GPIO21
  #   num_leds: 50
  #   rgb_order: RGB
  #   pio: 0
  #   internal: true
  # - platform: rp2040_pio_led_strip
  #   id: strip4
  #   chipset: ws2812b
  #   pin: GPIO22
  #   num_leds: 50
  #   rgb_order: RGB
  #   pio: 1
  #   internal: true
```
