### ISSUE TITLE
Cannot use lambda for `remote_transmitter.transmit_haier` code

### ISSUE THREAD

**Issue by catlee** [esphome/issues#5159]
### The problem

I'm trying to write a lambda to generate the infrared codes for my haier AC unit.

My config looks something like this:
```yaml
  - platform: template
    id: set_away
    name: Set Away
    on_press:
      - remote_transmitter.transmit_haier:
          code: !lambda |-
            return {1,2,3};
```

I get a build error:
```make
Compiling .pioenvs/haier/src/main.cpp.o
<unicode string>: In function 'void setup()':
<unicode string>:78:4: error: cannot convert 'setup()::<lambda()>' to 'const std::vector<unsigned char>&'
In file included from src/esphome.h:43,
                 from src/main.cpp:3:
src/esphome/components/remote_base/haier_protocol.h:31:45: note:   initializing argument 1 of 'void esphome::remote_base::HaierAction<Ts>::set_code(const std::vector<unsigned char>&) [with Ts = {}]'
   31 |   void set_code(const std::vector<uint8_t> &code) { data_ = code; }
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
*** [.pioenvs/haier/src/main.cpp.o] Error 1
```

### Which version of ESPHome has the issue?

2023.12.0-dev

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

remote_base

### Example YAML snippet

```yaml
- platform: template
    id: set_away
    name: Set Away
    on_press:
      - remote_transmitter.transmit_haier:
          code: !lambda |-
            return {1,2,3};
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/haier/src/main.cpp.o
<unicode string>: In function 'void setup()':
<unicode string>:78:4: error: cannot convert 'setup()::<lambda()>' to 'const std::vector<unsigned char>&'
In file included from src/esphome.h:43,
                 from src/main.cpp:3:
src/esphome/components/remote_base/haier_protocol.h:31:45: note:   initializing argument 1 of 'void esphome::remote_base::HaierAction<Ts>::set_code(const std::vector<unsigned char>&) [with Ts = {}]'
   31 |   void set_code(const std::vector<uint8_t> &code) { data_ = code; }
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
*** [.pioenvs/haier/src/main.cpp.o] Error 1
```
