### ISSUE TITLE
[hidden] is an invalid option for [wifi]. Please check the indentation.

### ISSUE THREAD

**Issue by DRXAquosus** [esphome/issues#5165]
### The problem

Trying to configure connecting to a hidden wifi network, config editor shows the error "[hidden] is an invalid option for [wifi]. Please check the indentation." whenever I add the "hidden" parameter to the wifi section.  

I also tried with the multiple network method and while it will accept the hidden parameter it gives an error for the fast_connect parameter. ([fast_connect] is an invalid option for [0]. Please check the indentation.)

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

OS 2023.11.3

### What platform are you using?

ESP32

### Board

Atom Echo

### Component causing the issue

Wifi

### Example YAML snippet

```yaml
Single Network Configuration - Produces the "[hidden] is an invalid option for [wifi]. Please check the indentation." error:
wifi:
  ssid: wifi-name1
  password: Password
  fast_connect: True
  hidden: True
  domain: .custom.domain.us
  enable_btm: true
  enable_rrm: true
  manual_ip:
    static_ip: 10.x.x.xxx
    subnet: 255.255.255.0
    gateway: 10.x.x.x
    dns1: 10.x.xx.xx
    dns2: 10.x.xx.xx


Multiple Network Configuration - Produces the "[fast_connect] is an invalid option for [0]. Please check the indentation." error
wifi:   
  domain: .custom.domain.us
  enable_btm: true
  enable_rrm: true
  networks:
  - ssid: wifi-name1
    fast_connect: True
    password: Password
    hidden: true
    manual_ip:
      static_ip: 10.x.x.xxx
      subnet: 255.255.255.0
      gateway: 10.x.x.x
      dns1: 10.x.xx.xx
      dns2: 10.x.xx.xx
  - ssid: wifi-name2
    password: Password
```

### Additional information

Single Network Configuration:
![image](https://github.com/esphome/issues/assets/45409262/588e3406-16db-4320-b82f-196b66b6e1cd)

Multiple Network Configuration:
![image](https://github.com/esphome/issues/assets/45409262/3414b9dd-805f-46ea-8c1c-1502fa6d11d7)
