### ISSUE TITLE
External components git retrieval and include reference trouble

### ISSUE THREAD

**Issue by Jjbasso** [esphome/issues#5166]
### The problem

With the breaking fix that removed writing files to /config/esphome/.esphome, I have noticed that my include external component files I use to pull from git no longer seem to write to my HA directory structure on my yellow. For now I have manually moved the files here to get my code working.  Not sure what I am doing wrong with the Git download. Here is the git repo that I am pulling. 

https://github.com/Jjbasso/sauna_util/tree/master/esphome/components/emc2101

Here is my main yaml file. 

```
external_components:
  - source:
      type: git
      url: https://github.com/Jjbasso/sauna_util/
      ref: master
    components: [ emc2101 ]
    refresh: 0s

packages:
  remote_package:
    url: https://github.com/Jjbasso/sauna_util/
    ref: master 
    files: [config.yaml, fan.yaml, gesture.yaml, display.yaml]
    refresh: 0s

substitutions:
  config_name: sauna-util-controller
  config_board: ttgo-t7-v14-mini32
  config_logger_level: DEBUG
  config_api_enc_key: !secret api_key
  config_ota_pwd: !secret ota_password
  config_wifi_ssid: !secret wifi_ssid
  config_wifi_pwd: !secret wifi_password
  config_ap_fallback_ssid: "Sauna-Util Fallback Hotspot"
  config_ap_fallback_pwd: !secret recovery_password
  
  gesture_prox_off_delay: '10'
  gesture_update_interval: 1s
  gesture_proximity_gain: 8x
  gesture_ambient_light_gain: 16x
  gesture_gain: 8x
  gesture_pri_led_drive: 100mA 
  gesture_led_drive: 12.5mA 
  gesture_wait_time: 2.8ms
  gesture_prox_min: "25"
  gesture_prox_max: "40"

  display_id: oled_display
  display_alarm_threshold: "90"

esphome:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:

  - platform: adc
    id: analog
    pin: GPIO36
    attenuation: 11db

  - platform: ct_clamp
    name: "Sauna Utility Room Current" 
    id: current
    sensor: analog
    sample_duration: 2000ms
    update_interval: 10000ms
    filters:
      - calibrate_linear:
        - 0.000 -> 0
        - 0.0178 -> 1.78
      - lambda: |-
         if (x < 5) {
           return 0.00;
         } else {
           return x;
           }

switch:
  - platform: gpio
    restore_mode: ALWAYS_OFF
    name: "Sauna Heating Element 1"
    icon: "mdi:heating-coil"
    id: element_1
    pin:
      number: 27
      
  - platform: gpio
    restore_mode: ALWAYS_OFF
    name: "Sauna Heating Element 2"
    icon: "mdi:heating-coil"
    id: element_2
    pin:
      number: 25
      
  - platform: gpio
    restore_mode: ALWAYS_OFF
    name: "Sauna Heating Element 3"
    icon: "mdi:heating-coil"
    id: element_3
    pin:
      number: 19
```
For now I have created the directories and copied the files by hand but want to pull it from git so I can keep the code in my repos.   This is the directory structure below. 

![image](https://github.com/esphome/issues/assets/15962691/b7870744-bae7-417d-be0f-d061a989129b)

Here is one of the custom components.  If this is not the correct directory and it was also moved to the data directory, how would I write the include path?
```
esphome:
  libraries:
    - Wire
    - SPI
    - "Adafruit BusIO"
    - "Adafruit EMC2101"
  includes:
    - components/emc2101/fan_controller.h
    
sensor:
   # Setup fan sensors
  - platform: custom
    lambda: |-
      auto sauna_util_fan_controller = new emc2101_sensors();
      App.register_component(sauna_util_fan_controller);
      return {sauna_util_fan_controller->internal_temperature_sensor, sauna_util_fan_controller->external_temperature_sensor, sauna_util_fan_controller->rpm_sensor};

    sensors:
    - name: "Sauna Utility Processor Temperature"
      unit_of_measurement: "°F"
      device_class: "temperature"
      state_class: "measurement"

    - name: "Sauna Utility External Temperature"
      unit_of_measurement: "°F"
      device_class: "temperature"
      state_class: "measurement"
      on_value_range:
      - above: $display_alarm_threshold
        then:
          - output.turn_on: buzzer
      - below: $display_alarm_threshold
        then:
          - output.turn_off: buzzer

    - name: "Sauna Utility Fan RPM"
      unit_of_measurement: "rpm"
      state_class: "measurement"

output:
  - platform: custom
    type: float
    lambda: |-
      auto sauna_utility_fan_speed = new emc2101_fan_speed();
      App.register_component(sauna_utility_fan_speed);
      return {sauna_utility_fan_speed};    
    
    outputs:
      id: sauna_utility_fan_speed

fan:
  - platform: speed
    output: sauna_utility_fan_speed
    name: "Sauna Utility Fan Speed"
``` 

Jeffrey B.

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.3

### What platform are you using?

ESP32

### Board

dev board

### Component causing the issue

Issue with git retrieval 

### Example YAML snippet

```yaml
See above.
```

### Anything in the logs that might be useful for us?

```txt
Just that when the files are not copied there the build fails.  No other errors that I can see in the logs.
```
