### ISSUE TITLE
Segmented 8x8  with  esp32_rmt_led_strip  on  WS2812 2d

### ISSUE THREAD

**Issue by geeneo** [esphome/issues#5169]
### The problem

I want to segment my 8x8 2d panel to display statuses of  5 areas.

Switching on and off is very sluggish and does not work all the time.
 

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
esphome:
  name: bedroom-indcator
  friendly_name: BedRoom_Indcator


esp32:
  board: esp32dev
  framework:
    type: arduino


logger:
  logs:
    component: ERROR

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret esphome_web_username
    password: !secret esphome_web_password


text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} - ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} - IP Address"
      icon: mdi:wifi
    ssid:
      name: "${friendly_name} - Connected SSID"
      icon: mdi:wifi-strength-2

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO2
    rmt_channel: 0
    num_leds: 64
    rgb_order: GRB
    name: "Mike Bed Light"
    id: mike_bed
    restore_mode: ALWAYS_OFF
    gamma_correct: 1.0
    default_transition_length: 10ms
    max_refresh_rate: 16ms
    effects: 
      - addressable_lambda:
          name: "on"
          update_interval: 16ms
          lambda: |-
                  it[0] = light::ESPColor(255, 0, 0);
                  it[1] = light::ESPColor(255, 0, 0);
                  it[2] = light::ESPColor(255, 0, 0);
                  it[8] = light::ESPColor(255, 0, 0);
                  it[9] = light::ESPColor(255, 0, 0);
                  it[10] = light::ESPColor(255, 0, 0);
                  it[16] = light::ESPColor(255, 0, 0);
                  it[17] = light::ESPColor(255, 0, 0);
                  it[18] = light::ESPColor(255, 0, 0);

      - addressable_lambda:
          name: "none"
          update_interval: 16ms
          lambda: |-
                  it[0] = light::ESPColor(0, 0, 0);
                  it[1] = light::ESPColor(0, 0, 0);
                  it[2] = light::ESPColor(0, 0, 0);
                  it[8] = light::ESPColor(0, 0, 0);
                  it[9] = light::ESPColor(0, 0, 0);
                  it[10] = light::ESPColor(0, 0, 0);
                  it[16] = light::ESPColor(0, 0, 0);
                  it[17] = light::ESPColor(0, 0, 0);
                  it[18] = light::ESPColor(0, 0, 0);


    on_turn_on:
      - delay: 200ms
      - logger.log: "Turning on"
      - light.turn_on:
          brightness: 10%
          id: mike_bed
          effect: "on"




  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO2
    rmt_channel: 0
    num_leds: 64
    rgb_order: GRB
    name: "Esta Bed Light"
    id: esta_bed
    restore_mode: ALWAYS_OFF
    gamma_correct: 1.0
    max_refresh_rate: 16ms
    #on_state: 
    effects: 
      - addressable_lambda:
          name: "on"
          update_interval: 16ms
          lambda: |-
                  static int state = 0;
                  it[5] = light::ESPColor(0, 0, 255);
                  it[6] = light::ESPColor(0, 0, 255);
                  it[7] = light::ESPColor(0, 0, 255);
                  it[13] = light::ESPColor(0, 0, 255);
                  it[14] = light::ESPColor(0, 0, 255);                  
                  it[15] = light::ESPColor(0, 0, 255);
                  it[21] = light::ESPColor(0, 0, 255);
                  it[22] = light::ESPColor(0, 0, 255);
                  it[23] = light::ESPColor(0, 0, 255);


    on_turn_on:
      - delay: 200ms
      - logger.log: "Turning on"      
      - light.turn_on:
          brightness: 10%
          id: esta_bed
          effect: "on"


  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO2
    rmt_channel: 0
    num_leds: 64
    rgb_order: GRB
    name: "Mike G Light"
    id: mikeg
    restore_mode: ALWAYS_OFF
    gamma_correct: 1.0
    max_refresh_rate: 16ms
    effects: 
      - addressable_lambda:
          name: "on"
          update_interval: 16ms
          lambda: |-
                  static int state = 0;
                  it[40] = light::ESPColor(255, 255, 255);
                  it[41] = light::ESPColor(255, 255, 255);
                  it[42] = light::ESPColor(255, 255, 255);
                  it[48] = light::ESPColor(255, 255, 255);
                  it[49] = light::ESPColor(255, 255, 255);                  
                  it[50] = light::ESPColor(255, 255, 255);
                  it[56] = light::ESPColor(255, 255, 255);
                  it[57] = light::ESPColor(255, 255, 255);
                  it[58] = light::ESPColor(255, 255, 255);
                  
    on_turn_on:
      - delay: 200ms
      - logger.log: "Turning on"            
      - light.turn_on:
          brightness: 10%
          id: mikeg
          effect: "on"


  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO2
    rmt_channel: 0
    num_leds: 64
    rgb_order: GRB
    name: "Esta G Light"
    id: estag
    restore_mode: ALWAYS_OFF
    gamma_correct: 1.0
    max_refresh_rate: 16ms
    effects: 
      - addressable_lambda:
          name: "on"
          update_interval: 16ms
          lambda: |-
                  static int state = 0;
                  it[45] = light::ESPColor(0, 255, 0);
                  it[46] = light::ESPColor(0, 255, 0);
                  it[47] = light::ESPColor(0, 255, 0);
                  it[53] = light::ESPColor(0, 255, 0);
                  it[54] = light::ESPColor(0, 255, 0);                  
                  it[55] = light::ESPColor(0, 255, 0);
                  it[61] = light::ESPColor(0, 255, 0);
                  it[62] = light::ESPColor(0, 255, 0);
                  it[63] = light::ESPColor(0, 255, 0);
                  
    on_turn_on:
      - delay: 200ms
      - logger.log: "Turning on"            
      - light.turn_on:
          brightness: 10%
          id: estag
          effect: "on"



  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO2
    rmt_channel: 0
    num_leds: 64
    rgb_order: GRB
    name: "Main Gate Light"
    id: maingate
    restore_mode: RESTORE_AND_OFF
    gamma_correct: 1.0
    max_refresh_rate: 16ms
    effects: 
      - addressable_lambda:
          name: "on"
          update_interval: 16ms
          lambda: |-
                  static int state = 0;
                  it[26] = light::ESPColor(255, 255, 0);
                  it[27] = light::ESPColor(255, 255, 0);
                  it[28] = light::ESPColor(255, 255, 0);
                  it[29] = light::ESPColor(255, 255, 0);
                  it[34] = light::ESPColor(255, 255, 0);
                  it[35] = light::ESPColor(255, 255, 0);
                  it[36] = light::ESPColor(255, 255, 0);
                  it[37] = light::ESPColor(255, 255, 0);

    on_turn_on:
      - delay: 200ms
      - logger.log: "Turning on"            
      - light.turn_on:
          brightness: 10%
          id: maingate
          effect: "on"




  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO2
    rmt_channel: 0
    num_leds: 64
    rgb_order: GRB
    name: "All Light"
    id: all
    restore_mode: RESTORE_AND_OFF
    gamma_correct: 1.0
    max_refresh_rate: 16ms
    effects: 
      - addressable_lambda:
          name: "on"
          update_interval: 16ms
          lambda: |-
                  static int state = 0;
                  it[0] = light::ESPColor(255, 0, 0);
                  it[1] = light::ESPColor(255, 0, 0);
                  it[2] = light::ESPColor(255, 0, 0);
                  it[8] = light::ESPColor(255, 0, 0);
                  it[9] = light::ESPColor(255, 0, 0);
                  it[10] = light::ESPColor(255, 0, 0);
                  it[16] = light::ESPColor(255, 0, 0);
                  it[17] = light::ESPColor(255, 0, 0);
                  it[18] = light::ESPColor(255, 0, 0);
                  it[5] = light::ESPColor(0, 0, 255);
                  it[6] = light::ESPColor(0, 0, 255);
                  it[7] = light::ESPColor(0, 0, 255);
                  it[13] = light::ESPColor(0, 0, 255);
                  it[14] = light::ESPColor(0, 0, 255);                  
                  it[15] = light::ESPColor(0, 0, 255);
                  it[21] = light::ESPColor(0, 0, 255);
                  it[22] = light::ESPColor(0, 0, 255);
                  it[23] = light::ESPColor(0, 0, 255);
                  it[40] = light::ESPColor(255, 255, 255);
                  it[41] = light::ESPColor(255, 255, 255);
                  it[42] = light::ESPColor(255, 255, 255);
                  it[48] = light::ESPColor(255, 255, 255);
                  it[49] = light::ESPColor(255, 255, 255);                  
                  it[50] = light::ESPColor(255, 255, 255);
                  it[56] = light::ESPColor(255, 255, 255);
                  it[57] = light::ESPColor(255, 255, 255);
                  it[58] = light::ESPColor(255, 255, 255);
                  it[45] = light::ESPColor(0, 255, 0);
                  it[46] = light::ESPColor(0, 255, 0);
                  it[47] = light::ESPColor(0, 255, 0);
                  it[53] = light::ESPColor(0, 255, 0);
                  it[54] = light::ESPColor(0, 255, 0);                  
                  it[55] = light::ESPColor(0, 255, 0);
                  it[61] = light::ESPColor(0, 255, 0);
                  it[62] = light::ESPColor(0, 255, 0);
                  it[63] = light::ESPColor(0, 255, 0);
                  it[26] = light::ESPColor(255, 255, 0);
                  it[27] = light::ESPColor(255, 255, 0);
                  it[28] = light::ESPColor(255, 255, 0);
                  it[29] = light::ESPColor(255, 255, 0);
                  it[34] = light::ESPColor(255, 255, 0);
                  it[35] = light::ESPColor(255, 255, 0);
                  it[36] = light::ESPColor(255, 255, 0);
                  it[37] = light::ESPColor(255, 255, 0);
                  it[45] = light::ESPColor(0, 255, 0);
                  it[46] = light::ESPColor(0, 255, 0);
                  it[47] = light::ESPColor(0, 255, 0);
                  it[53] = light::ESPColor(0, 255, 0);
                  it[54] = light::ESPColor(0, 255, 0);                  
                  it[55] = light::ESPColor(0, 255, 0);
                  it[61] = light::ESPColor(0, 255, 0);
                  it[62] = light::ESPColor(0, 255, 0);
                  it[63] = light::ESPColor(0, 255, 0);


    on_turn_on:
      - delay: 200ms
      - logger.log: "Turning on"            
      - light.turn_on:
          brightness: 10%
          id: all
          effect: "on"

switch:
  - platform: restart
    name: "Restart Light"
```
