### ISSUE TITLE
Typo in ESPRangeView::fade_to_black

### ISSUE THREAD

**Issue by nordeep** [esphome/issues#517]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp8266
**Affected component:**

https://esphome.io/components/light/index.html

**Description of problem:**
It look like a typo in function ESPRangeView::fade_to_black - https://www.esphome.io/api/addressable__light_8cpp_source.html#l00114 code is - c.fade_to_white(amnt); must be c.fade_to_black(amnt);

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: redstick
  platform: ESP8266
  board: nodemcuv2
  includes:
    - myfastled.h

wifi:
  ssid: !secret ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

# Example configuration entry
globals:
  - id: auto_mode_b
    type: bool
    restore_value: yes
    initial_value: 'false'

substitutions:
  # Modify variables based on your settings
  hostname: 'RedStick'

sensor:
  - platform: wifi_signal
    name: $hostname WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: $hostname Uptime
  - platform: adc
    pin: A0
    name: "Brightness"
    update_interval: 10s
    on_value:
      then:
        - if:
            condition:
              - binary_sensor.is_on: auto_mode
            then:
              - light.control:
                  id: redstick_light
                  brightness: !lambda "float y=x/0.5; if(y<0.1) y=0.3; return y;"

text_sensor:
  - platform: version
    name: $hostname ESPHome Version
  - platform: wifi_info
    ssid:
      name: $hostname WiFi

# Example configuration entry
switch:
  - platform: restart
    name: $hostname Restart
  - platform: template
    name: "Auto Mode Switch"
    lambda: |-
      if (id(auto_mode_b)) {
        return true;
      } else {
        return false;
      }
    id: auto_mode_switch
    turn_on_action: 
      - lambda: "id(auto_mode_b)=true;"
    turn_off_action:
      - lambda: "id(auto_mode_b)=false;"

binary_sensor:
  - platform: status
    name: $hostname status
  - platform: template
    name: $hostname auto mode
    lambda: |-
      if (id(auto_mode_b)) {
        return true;
      } else {
        return false;
      }
    id: auto_mode


# Example configuration entry
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO05
    num_leds: 8
    rgb_order: GRB
    name: $hostname Light
    id: redstick_light
    effects:
      - addressable_flicker:
      - addressable_flicker:
          name: Flicker Effect With Custom Values
          update_interval: 16ms
          intensity: 5%
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False
      - addressable_scan:
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 100ms
      - addressable_twinkle:
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_lambda:
          name: "Confetti"
          update_interval: 100ms
          lambda: |-
            // it.size() - Number of LEDs
            // it[num] - Access the LED at index num.
            // Set the LED at num to the given r, g, b values
            // it[num] = ESPColor(r, g, b);
            // Get the color at index num (ESPColor instance)
            // it[num].get();
  
            it.all().fade_to_black(50);
            for (int x=0; x<1; x++) {
              int pos = random16(it.size());
              it[pos] = ESPHSVColor(0 + random8(64), 200, 128);
            }
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
