### ISSUE TITLE
Cannot compile NSPanel Advanced

### ISSUE THREAD

**Issue by sergiobaiao** [esphome/issues#5171]
### The problem

I'm trying to compile a customized version of NSPanel for Home Assistant. This is the code:

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.11.2

### What platform are you using?

ESP32

### Board

NSPanel

### Example YAML snippet

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "sala" 
  wifi_ssid: my_secret_ssid
  wifi_password: my_secret_password

  nextion_update_url: "http://192.168.0.244:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s
esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
api:
  reboot_timeout: 15min
binary_sensor:
  - name: ${device_name} Display state
    id: display_state
    platform: template
    lambda: |-
      return (id(current_page).state != "screensaver");      
light:
  # Add the display as a light in Home Assistant
  - name: ${device_name} Display
    id: display_light
    icon: mdi:tablet-dashboard
    platform: monochromatic
    output: display_output
    default_transition_length: 0s
    on_turn_on:
      then:
        - lambda: |-
            ESP_LOGD("light.display_light", "Turn-on");
            if (current_page->state == "screensaver") disp1->goto_page(wakeup_page_name->state.c_str());
            timer_reset_all->execute(wakeup_page_name->state.c_str());
    on_turn_off:
      then:
        - lambda: |-
            ESP_LOGD("light.display_light", "Turn-off");
            disp1->goto_page("screensaver");

output:
  # Output required by `display_light` to send the commands to Nextion
  - id: display_output
    platform: template
    type: float
    write_action:
      - lambda: |-
          ESP_LOGV("output.display_output", "state: %f", state);
          uint8_t current_brightness = int(round(display_light->current_values.is_on() ? (display_light->current_values.get_brightness() * 100.0f) : 0.0));
          ESP_LOGV("output.display_output", "current_brightness: %i%%", current_brightness);
          set_brightness->execute(current_brightness);
    
script:
  # Updates the existing `page_changed` script to update the `display_light` status when a page changes
  - id: !extend page_changed
    then:
      - lambda: |-
          ESP_LOGD("script.page_changed(custom)", "page: %s", page.c_str());
          ESP_LOGV("script.page_changed(custom)", "is_on(): %s", display_light->current_values.is_on() ? "True" : "False");
          if (page == "screensaver" and display_light->current_values.is_on()) {
            auto call = display_light->turn_off();
            call.perform();
          } else if (page != "screensaver" and (not display_light->current_values.is_on())) {
            auto call = display_light->turn_on();
            call.perform();
          }

  # Updates the existing `set_brightness` script to update the `display_light` status when a new brightness level is set
  - id: !extend set_brightness
    then:
      - lambda: |-
          ESP_LOGD("script.set_brightness(custom)", "brightness: %i%%", brightness);
          uint8_t current_brightness = int(round(display_light->current_values.is_on() ? (display_light->current_values.get_brightness() * 100.0f) : 0.0));
          ESP_LOGV("script.set_brightness(custom)", "current_brightness: %i%%", current_brightness);
          if (brightness != current_brightness) {
            if (current_page->state != "screensaver" and brightness > 0) {
              auto call = display_light->turn_on();
              call.set_brightness(static_cast<float>(id(display_last_brightness)) / 100.0f);
              call.perform();
            } else if (display_light->current_values.is_on()) {
              auto call = display_light->turn_off();
              call.set_brightness(0);
              call.perform();
            }
          }

##### My customization - End #####
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.11.6
INFO Reading configuration /config/nspanel-sala.yaml...
INFO Detected timezone 'Etc/UTC'
INFO Generating C++ source...
INFO Compiling app...
Processing sala (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/sala/src/main.o
Linking .pioenvs/sala/firmware.elf
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x8): undefined reference to `esphome::light::LightState::make_call()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0xc): undefined reference to `esphome::light::LightCall::set_state(bool)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x10): undefined reference to `esphome::light::LightCall::set_brightness(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x14): undefined reference to `esphome::light::LightCall::set_color_mode(esphome::light::ColorMode)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x18): undefined reference to `esphome::light::LightCall::set_color_brightness(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x1c): undefined reference to `esphome::light::LightCall::set_red(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x20): undefined reference to `esphome::light::LightCall::set_green(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x24): undefined reference to `esphome::light::LightCall::set_blue(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x28): undefined reference to `esphome::light::LightCall::set_white(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x2c): undefined reference to `esphome::light::LightCall::set_color_temperature(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x30): undefined reference to `esphome::light::LightCall::set_cold_white(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x34): undefined reference to `esphome::light::LightCall::set_warm_white(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x38): undefined reference to `esphome::light::LightCall::set_transition_length(unsigned int)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x3c): undefined reference to `esphome::light::LightCall::set_flash_length(unsigned int)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x40): undefined reference to `esphome::light::LightCall::set_effect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13light_commandERKNS0_19LightCommandRequestE+0x44): undefined reference to `esphome::light::LightCall::perform()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection16send_light_stateEPNS_5light10LightStateE+0x4): undefined reference to `esphome::light::LightState::get_traits()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection16send_light_stateEPNS_5light10LightStateE+0x8): undefined reference to `esphome::light::LightState::supports_effects()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection16send_light_stateEPNS_5light10LightStateE+0xc): undefined reference to `esphome::light::LightState::get_effect_name[abi:cxx11]()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection15send_light_infoEPNS_5light10LightStateE+0x8): undefined reference to `esphome::light::LightState::get_effects() const'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o: in function `esphome::api::APIConnection::light_command(esphome::api::LightCommandRequest const&)':
/config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:401: undefined reference to `esphome::light::LightState::make_call()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:403: undefined reference to `esphome::light::LightCall::set_state(bool)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:405: undefined reference to `esphome::light::LightCall::set_brightness(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:407: undefined reference to `esphome::light::LightCall::set_color_mode(esphome::light::ColorMode)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:409: undefined reference to `esphome::light::LightCall::set_color_brightness(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:411: undefined reference to `esphome::light::LightCall::set_red(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:412: undefined reference to `esphome::light::LightCall::set_green(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:413: undefined reference to `esphome::light::LightCall::set_blue(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:416: undefined reference to `esphome::light::LightCall::set_white(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:418: undefined reference to `esphome::light::LightCall::set_color_temperature(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:420: undefined reference to `esphome::light::LightCall::set_cold_white(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:422: undefined reference to `esphome::light::LightCall::set_warm_white(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:424: undefined reference to `esphome::light::LightCall::set_transition_length(unsigned int)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:426: undefined reference to `esphome::light::LightCall::set_flash_length(unsigned int)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:428: undefined reference to `esphome::light::LightCall::set_effect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:429: undefined reference to `esphome::light::LightCall::perform()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o: in function `esphome::api::APIConnection::send_light_state(esphome::light::LightState*)':
/config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:340: undefined reference to `esphome::light::LightState::get_traits()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:354: undefined reference to `esphome::light::LightState::supports_effects()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:357: undefined reference to `esphome::light::LightState::get_effect_name[abi:cxx11]()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/components/api/api_connection.o: in function `esphome::api::APIConnection::send_light_info(esphome::light::LightState*)':
/config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:362: undefined reference to `esphome::light::LightState::get_traits()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:383: undefined reference to `esphome::light::LightState::supports_effects()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/build/sala/src/esphome/components/api/api_connection.cpp:389: undefined reference to `esphome::light::LightState::get_effects() const'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.literal._ZN7esphome13monochromatic24MonochromaticLightOutput11write_stateEPNS_5light10LightStateE[esphome::monochromatic::MonochromaticLightOutput::write_state(esphome::light::LightState*)]+0x0): undefined reference to `esphome::light::LightState::current_values_as_brightness(float*)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.literal._ZNSt17_Function_handlerIFvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEZ5setupvEUlS5_E100_E9_M_invokeERKSt9_Any_dataOS5_+0x8): undefined reference to `esphome::light::LightState::turn_off()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.literal._ZNSt17_Function_handlerIFvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEZ5setupvEUlS5_E100_E9_M_invokeERKSt9_Any_dataOS5_+0xc): undefined reference to `esphome::light::LightState::turn_on()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.literal._Z5setupv+0x14b4): undefined reference to `esphome::light::LightState::LightState(esphome::light::LightOutput*)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.literal._Z5setupv+0x14b8): undefined reference to `esphome::light::LightState::set_restore_mode(esphome::light::LightRestoreMode)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.literal._Z5setupv+0x14bc): undefined reference to `esphome::light::LightState::set_default_transition_length(unsigned int)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.literal._Z5setupv+0x14c0): undefined reference to `esphome::light::LightState::set_flash_transition_length(unsigned int)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.literal._Z5setupv+0x14c4): undefined reference to `esphome::light::LightState::set_gamma_correct(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.literal._Z5setupv+0x14c8): undefined reference to `esphome::light::LightState::add_effects(std::vector<esphome::light::LightEffect*, std::allocator<esphome::light::LightEffect*> > const&)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.literal._Z5setupv+0x14cc): undefined reference to `esphome::light::LightState::add_new_target_state_reached_callback(std::function<void ()>&&)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o: in function `esphome::monochromatic::MonochromaticLightOutput::write_state(esphome::light::LightState*)':
/config/.esphome/build/sala/src/esphome/components/monochromatic/monochromatic_light_output.h:20: undefined reference to `esphome::light::LightState::current_values_as_brightness(float*)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o: in function `std::_Function_handler<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), setup()::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)#102}>::_M_invoke(std::_Any_data const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
/config/nspanel-sala.yaml:77: undefined reference to `esphome::light::LightState::turn_off()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o: in function `operator()':
/config/nspanel-sala.yaml:78: undefined reference to `esphome::light::LightCall::perform()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/nspanel-sala.yaml:80: undefined reference to `esphome::light::LightState::turn_on()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o: in function `std::_Function_handler<void (unsigned int), setup()::{lambda(unsigned int)#76}>::_M_invoke(std::_Any_data const&, unsigned int&&)':
/config/nspanel-sala.yaml:93: undefined reference to `esphome::light::LightState::turn_on()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o: in function `operator()':
/config/nspanel-sala.yaml:95: undefined reference to `esphome::light::LightCall::set_brightness(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/nspanel-sala.yaml:99: undefined reference to `esphome::light::LightCall::perform()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/nspanel-sala.yaml:97: undefined reference to `esphome::light::LightState::turn_off()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o: in function `setup()':
/config/.esphome/packages/566b10a3/nspanel_esphome_core.yaml:2921: undefined reference to `esphome::light::LightState::LightState(esphome::light::LightOutput*)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:1366: undefined reference to `esphome::light::LightState::set_restore_mode(esphome::light::LightRestoreMode)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:1366: undefined reference to `esphome::light::LightState::set_default_transition_length(unsigned int)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()':
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:657: undefined reference to `esphome::light::LightState::set_flash_transition_length(unsigned int)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o: in function `setup()':
/config/.esphome/packages/566b10a3/nspanel_esphome_core.yaml:2925: undefined reference to `esphome::light::LightState::set_gamma_correct(float)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/packages/566b10a3/nspanel_esphome_core.yaml:2925: undefined reference to `esphome::light::LightState::add_effects(std::vector<esphome::light::LightEffect*, std::allocator<esphome::light::LightEffect*> > const&)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/packages/566b10a3/nspanel_esphome_core.yaml:2927: undefined reference to `esphome::light::LightState::add_new_remote_values_callback(std::function<void ()>&&)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/.esphome/packages/566b10a3/nspanel_esphome_core.yaml:2933: undefined reference to `esphome::light::LightState::add_new_target_state_reached_callback(std::function<void ()>&&)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/main.o:(.rodata._ZTVN7esphome13monochromatic24MonochromaticLightOutputE[vtable for esphome::monochromatic::MonochromaticLightOutput]+0xc): undefined reference to `esphome::light::LightOutput::create_default_transition()'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/core/controller.o:(.literal._ZN7esphome10Controller16setup_controllerEb+0x38): undefined reference to `esphome::light::LightState::add_new_remote_values_callback(std::function<void ()>&&)'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/sala/src/esphome/core/controller.o: in function `esphome::Controller::setup_controller(bool)':
/config/.esphome/build/sala/src/esphome/core/controller.cpp:23: undefined reference to `esphome::light::LightState::add_new_remote_values_callback(std::function<void ()>&&)'
collect2: error: ld returned 1 exit status
*** [.pioenvs/sala/firmware.elf] Error 1
========================= [FAILED] Took 31.67 seconds =========================
```
