### ISSUE TITLE
dfplayer problems with play_folder, set_volume and others

### ISSUE THREAD

**Issue by xkonni** [esphome/issues#5174]
### The problem

Using a dfplayer with pretty much the default configuration.

sdcard:

```
01/
  /001.MP3
  /002.MP3
  /003.MP3
```

It does play the first file with `dfplayer.start`, it does randomly loop all files with `dfplayer.random` and I can change the volume with `dfplayer.volume_up/down`. Pretty much all functions without arguments are fine.

Functions with arguments however simply do nothing if the argument is not zero.

e.g. 

`dfplayer.set_volume 0` changes the volume to 0
log shows  `[11:41:30][D][dfplayer:034]: Send Command 0x6 arg 0000`

`dfplayer.set_volume 1` does not change the volume
log shows [11:41:36][D][dfplayer:034]: Send Command 0x6 arg 0x01`

`dfplayer.play_folder 0 0` plays the first file

log

```
[D][dfplayer:034]: Send Command 0xf arg 0000
[D][dfplayer:123]: Command 0x4c arg 0x01
```

`dfplayer.play_folder 1 1` does not play

log

```
[D][dfplayer:034]: Send Command 0xf arg 0x101
```

I copied the dfplayer files from git and use them a custom component. Behavior is unchanged and can add debug output, but so far I do not see what the actual problem is.

### Which version of ESPHome has the issue?

2023.9 to 2023.11.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.12.0.dev20231107

### What platform are you using?

ESP8266

### Board

wemos d1

### Component causing the issue

dfplayer

### Example YAML snippet

```yaml
esphome:
  name: player1
  friendly_name: player1
  platform: ESP8266
  board: d1_mini

external_components:
  - source: components

...

- service: dfplayer_play_folder
    variables:
      folder: int
      file: int
    then:
      - logger.log: 
          format: "play_folder %d and file %d"
          args: [ 'folder', 'file' ]
      - dfplayer.play_folder:
          folder: !lambda 'return folder;'
          file: !lambda 'return file;'

...

  - service: dfplayer_set_volume
    variables:
      volume: int
    then:
      - dfplayer.set_volume: !lambda 'return volume;'

...

- service: dfplayer_start
    then:
      - dfplayer.start

  - service: dfplayer_pause
    then:
      - dfplayer.pause

  - service: dfplayer_stop
    then:
      - dfplayer.stop

  - service: dfplayer_random
    then:
      - dfplayer.random

  - service: dfplayer_volume_up
    then:
      - dfplayer.volume_up

  - service: dfplayer_volume_down
    then:
      - dfplayer.volume_down
```
