### ISSUE TITLE
Feature request: 55% bigger partitions with two phase OTA

### ISSUE THREAD

**Issue by afarago** [esphome/issues#5175]
### The problem

It would be possible to increase the size of available program size with moving away from equal partition sizes and a two phase OTA. 

Reference: Tasmota Safeboot - https://tasmota.github.io/docs/Safeboot/

### Which version of ESPHome has the issue?

2023.11.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
substitutions:
  device_name: safe_boot

esphome:
  name: ${device_name}

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "$device_name"
    password: !secret wifi_password
    
ota:
  password: !secret ota_password
  safe_mode: yes

logger:
  level: error
```

### Additional information

As an example I have checked the a safeboot size of a minimal (wifi and ota) app, and it ended up with 753k.
This would leave 1Mb bigger space for a program size on ESP32.

Workflow would be
1) reboot to safe_boot to partition 1
2) update the app on partition 2
3) boot back to real app on partition 2

Pros
- +1 MB program size
- main app could even get rid of the full OTA code - resulting in even smaller code, it would just need to boot back to safeboot app on partition 1

Cons - The alternative cost is that an OTA update should ideally
- more reboots for OTA - this should anyhow be infrequent
- failed OTA would lose the ability to fallback to the previous version, and would fallback to safe_boot

Not sure about the partitioning of ESP8266.

reference information and architecture: https://tasmota.github.io/docs/Safeboot/
