### ISSUE TITLE
I want to issue a command through MQTT JSON and esphome parse JSON to perform the action

### ISSUE THREAD

**Issue by hasspi88** [esphome/issues#5185]
### The problem

```
{
  "SetProperty" : {
    "switch" : value, }
}
``` 
I've tried a lot of things like on-massage and automation, but they all get an error and send the MQTT data in the format
{
  "SetProperty" : {
    "switch" : value, }
} When esphome receives the switch value 1 on the switch and receives switch0 off, the cut contains the SetProperty field

### Which version of ESPHome has the issue?

ESPHome by Nabu Casa | Fund development | 2023.11.2 Documentation

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

esp12e

### Component causing the issue

mqtt

### Example YAML snippet

```yaml
esphome:
  name: mq
  friendly_name: mq

esp8266:
  board: esp12e
#external_components:
  # use rtttl and dfplayer from ESPHome's dev branch in GitHub
#  - source:
#      type: git
#      url: https://github.com/esphome/esphome
#      ref: beta
#    components: [ switch , mqtt ]
mqtt:
  broker: 192.168.10.160
  port: 1883
  username: ism
  password: admin888
  client_id: mq10001
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "T3Nz9Ippk8By/rAyx8t3Q8o4D0c1eh5u88DAndztm2s="

ota:
  password: "d50b3a5af7e0e727d5ee3d8c26fa8e14"

wifi:
  ssid: "aikuai"
  password: "06336170007"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mq Fallback Hotspot"
    password: "qTz2H7U7btu4"

captive_portal:
output:
  - platform: gpio
    pin: 12
    id: 'generic_out'
switch:
  - platform: output
    name: "Generic Output"
    output: 'generic_out'

    on_turn_on:
      then:
        - mqtt.publish_json:
            topic: "/sys/mq10001/pub"  # 发布主题
            payload: '{"properties":{"switch":1}}'  # 修改开关状态的 JSON 格式
    on_turn_off:
      then:
        - mqtt.publish_json:
            topic: "/sys/mq10001/pub"  # 发布主题
            payload: '{"properties":{"switch":0}}'  # 修改开关状态的 JSON 格式
```
