### ISSUE TITLE
Textbox of text input component does not show up on webserver v2

### ISSUE THREAD

**Issue by stleusc** [esphome/issues#5188]
### The problem

In reference to  PR [#3638](https://github.com/esphome/esphome/pull/3638)...

I added a text input to my config and it all works great.
I usually have the js code on my own server since the devices have no internet acces.
So I copied the js file and put it onto my local server.

Compiled, and I can see it is pulling from the server and all is working as expected.

```
web_server:
  port: 80
  js_url: http://192.168.1.200/esphome/webserver-v2.min.js
```

THEN I decided to make the js file LOCAL to the device with this config:

```
web_server:
  port: 80
  local: true
  js_url: http://192.168.1.200/esphome/webserver-v2.min.js
```

And suddenly the textbox is gone and the 'table' shows nothing in that spot.

So to be clear, the feature works just fine as soon as I remove ```local:true``` from the webserver config!
That means, I know that the self-hosted js file is working. I can see the browser download it from my local server and rendering is ok.

### Which version of ESPHome has the issue?

2023.11.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

unrelated

### What platform are you using?

ESP32

### Example YAML snippet

Broken
```yaml

web_server:
  port: 80
  local: true
  js_url: http://192.168.1.200/esphome/webserver-v2.min.js
```

Working
```yaml
web_server:
  port: 80
  js_url: http://192.168.1.200/esphome/webserver-v2.min.js
```
