### ISSUE TITLE
MHZ19B stopped working

### ISSUE THREAD

**Issue by jensenbln** [esphome/issues#5191]
### The problem

After one of the latest updated MHZ19B sensor stopped working.
It was all working fine, but since one of the last updates (sorry, i dont know which one) i get an error in reading co2.

### Which version of ESPHome has the issue?

ESPHome 2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.3

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

MHZ19B

### Example YAML snippet

```yaml
logger:
  baud_rate: 0

uart:
  rx_pin: GPIO3 
  tx_pin: GPIO1
  baud_rate: 9600

sensor:
  - platform: dht
    pin: GPIO21
    model: DHT22
    temperature:
      name: "Wohnzimmer Temperature"
    humidity:
      name: "Wohnzimmer Humidity"
    update_interval: 60s
  - platform: mhz19
    co2:
      name: "CO2 Wohnzimmer"
      id: co2living
#    temperature:
#      name: "MH-Z19 Wohnzimmer Temperature"
#      accuracy_decimals: 1
#      filters:
#        - offset: -1
    update_interval: 60s
    automatic_baseline_calibration: false
    id: living
```

### Anything in the logs that might be useful for us?

```txt
[09:03:16][E][uart:015]: Reading from UART timed out at byte 0!
[09:03:16][W][mhz19:034]: Reading data from MHZ19 failed!
[09:03:16][W][component:214]: Component mhz19.sensor took a long time for an operation (0.11 s).
[09:03:16][W][component:215]: Components should block for at most 20-30ms.
```
