### ISSUE TITLE
ESPHome Pulse Meter sensor loosing pulses

### ISSUE THREAD

**Issue by teargas666** [esphome/issues#5198]
### The problem

Hi. I've used the code from the following link: https://esphome.io/components/sensor/pulse_meter.html 

I used it with my Orno WE520, but if it's not lost connection to my WiFi I've problems where ESPhome loosing pulses and after 10 days there is difference ~30 kWh... What can I do to prevent that situation? 

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

nodemcu

### Example YAML snippet

```yaml
esphome:
  name: energy_meter
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: xxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxx

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "xxxxxxxxxxxx"

captive_portal:

sensor:
  - platform: pulse_meter
    pin: D8
    unit_of_measurement: 'kW'
    name: "Active Power"
    internal_filter: 100ms
    accuracy_decimals: 3
    id: orno_we_520_active_power
    filters:
      - multiply: 0.075  # 800 pulses/kW
    total:
      name: "Active Energy"
      id: orno_we_520_power_active_energy
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      filters:
        - multiply: 0.00125
```
