### ISSUE TITLE
Mopeka temperature reading incorrect at -1 deg C

### ISSUE THREAD

**Issue by doctorkb** [esphome/issues#5209]
### The problem

In their app, Mopeka reports temperature of -1 deg C.  ESPHome plug-in reporting temperature of 255 deg C.

Also, in their app, Mopeka reports temperature of -2 deg C.  ESPHome plug-in reporting temperature of 254 deg C.

### Which version of ESPHome has the issue?

2023.12.0-dev (Dec 8 2023, 15:50:58)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.0

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

mopeka_pro_check

### Example YAML snippet

```yaml
- platform: mopeka_pro_check
    mac_address: C2:05:04:9C:7E:FC
    tank_type: 20LB_V
    temperature:
      name: "Propane temp"
    level:
      name: "Propane level"
    distance:
      name: "Propane distance"
    battery_level:
      name: "Propane battery level"
```

### Anything in the logs that might be useful for us?

```txt
[16:03:29][D][sensor:094]: 'Propane temp': Sending state 255.00000 °C with 0 decimals of accuracy
[16:03:49][D][sensor:094]: 'Propane temp': Sending state 254.00000 °C with 0 decimals of accuracy
```

### Additional information

Using DEV branch as my sensor is one of the "Universal" ones that was only added to support list two weeks ago.
