### ISSUE TITLE
Bluetooth proxy seems to be keeping connection to SwitcBot Curtain open

### ISSUE THREAD

**Issue by syphernl** [esphome/issues#5216]
### The problem

A few weeks ago I replaced my Switchbot Curtain v2 with v3's. They have been working very well thus far.
However.. after linking them to HomeAssistant I notice the following:

- The SwitchBot app claims the device is offline. Likely because ESPHome keeps the connection open constantly and my phone therefor cannot connect to the Switchbot. This worked fine with my v2 Switchbots.
- The battery on one of them seems to be draining rather quickly as it is dropping somewhere around 6% per day. It is currently at 37% while they have only been in use for ~3 weeks and 1x open and 1x close per day. The other is currently at 92%. Both are added to HomeAssistant via the SwitchBot integration and are controlled as a "cover group". (the v2 seemed to link together between "master" and "slave" SwitchBot where I only needed to add the "master" to HASS to be able to open/close them both at the same time)

### Which version of ESPHome has the issue?

2023.11.4

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2023.12.1

### What platform are you using?

ESP32-IDF

### Board

esp32dev

### Component causing the issue

bluetooth_proxy

### Example YAML snippet

```yaml
esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk

logger:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```
