### ISSUE TITLE
LOLIN C3 Mini V2.1.0 not booting after being flashed

### ISSUE THREAD

**Issue by bluestreak101** [esphome/issues#5218]
### The problem

After loading any program I get either of the following behaviors:

1. The device get stuck into a crash/boot loop and was able to capture the following output which it spits out 30 odd times before it restarts:

      invalid header: 0xffffffff

2. The device appears to be stuck with the following output:

      ESP-ROM:esp32c3-api1-20210207
      Build:Feb  7 2021
      rst:0x15 (USB_UART_CHIP_RESET),boot:0xd (SPI_FAST_FLASH_BOOT)
      Saved PC:0x4038c122
      SPIWP:0xee
      mode:DIO, clock div:1
      load:0x3fcd6100,len:0x38c
      load:0x403ce000,len:0x6ac
      load:0x403d0000,len:0x24e4
      entry 0x403ce000

I first noticed an issue when I tried to do an OTA update to the board which had been working and was flashed with esphome previously. The OTA would fail at around 20% so I tried to update it via USB when I started to see the first error.

During the course of troubleshooting I made a fairly blank yaml in esphome incase it was something in my setup. So far it yields the same result.

Flashing with first install always gets the 2nd output above.

I can use the ArdunioIDE to load an example sketch ok to scan for Wireless and even connect.

I've tried a few variations of the config attached after doing as much searching as I can but I'm getting limited search results now.

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

LOLIN C3 Mini

### Example YAML snippet

```yaml
esphome:
  name: esph-wifi
  friendly_name: esph-wifi
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "abc"

ota:
  password: "abc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  domain: .abc.com

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esph-Wifi Fallback Hotspot"
    password: "ABC"

captive_portal:
    
web_server:
  port: 80
```

### Anything in the logs that might be useful for us?

```txt
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x4204b058
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x38c
load:0x403ce000,len:0x6ac
load:0x403d0000,len:0x24e4
entry 0x403ce000
```
