### ISSUE TITLE
C++ code generator puts #include after declaration of components

### ISSUE THREAD

**Issue by RFDarter** [esphome/issues#5221]
### The problem

I was using a yaml file like this:
`esphome:
  name: chicken-coop-light
  friendly_name: chicken_coop_light
  includes:
    - coopSettings.h

globals:
  - id: coopSettings
    type: CoopSettings
    restore_value: yes`

I defined a Struct with the name CoopSettings in the coopSettings.h file, but since the code generator is puting the include statements after the declaration of the components i get a error while compiling.

`src/main.cpp:17:36: error: 'CoopSettings' was not declared in this scope`

Shouldn't the include statement put befor the declaration of the components?

### Which version of ESPHome has the issue?

2023.11.06

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
esphome:
  name: chicken-coop-light
  friendly_name: chicken_coop_light
  includes:
    - coopSettings.h

globals:
  - id: coopSettings
    type: CoopSettings
    restore_value: yes
```

### Anything in the logs that might be useful for us?

```txt
`src/main.cpp:17:36: error: 'CoopSettings' was not declared in this scope`
```
