### ISSUE TITLE
"Inaccessibility of continuous_mode_ Setting in ADS1115Component in ESPHome"

### ISSUE THREAD

**Issue by echavet** [esphome/issues#5227]
### The problem

Hello ESPHome Team,

I am currently working with the ADS1115Component in ESPHome and have come across a potential issue concerning the `continuous_mode_` property. While the method `set_continuous_mode(bool mode)` exists within the ADS1115Component class, it seems there is no way to invoke this method from the ESPHome configuration (YAML file). This property is crucial as it determines the operating mode (continuous or single-shot) of the ADS1115, and it is utilized in the `setup()` method of the component.

However, without the ability to set this property through the ESPHome YAML configuration, users cannot specify the desired operating mode for the ADS1115 sensor. This limits the functionality and flexibility of the ADS1115 integration within ESPHome.

To address this issue, I propose the following:
1. Extend the YAML configuration schema for the ADS1115 component to include an option for setting the continuous mode.
2. Handle this new configuration option in the `to_code` function within the Python script, linking it to the `set_continuous_mode` method.

By implementing these changes, it would allow users to configure the operating mode of the ADS1115 sensor directly from the YAML file, enhancing usability and ensuring that the sensor operates as intended in various applications.

Thank you for considering this issue. Any suggestions or feedback on this matter would be greatly appreciated.

Best regards

### Which version of ESPHome has the issue?

main

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
substitutions:
  name: "current-sensor"
  friendly_name: Capteur De Courant

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

logger:  
  hardware_uart: UART0
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid3
  password: !secret wifi_password3

# Activer l'accès à l'API Home Assistant
api:

ota:

i2c:

ads1115:
  - address: 0x48

select:
  - platform: template 
    name: "Gain ads 1"
    id: gain_select
    #setup_priority : -100.0 ## late
    options:      
      - "6.144"
      - "4.096"
      - "2.048"
      - "1.024"
      - "0.512"
      - "0.256"
    optimistic: true
    on_value:
      - lambda: |-                    
          if (x == "6.144") id(ads_1).set_gain(esphome::ads1115::ADS1115_GAIN_6P144);
          else if (x == "4.096") id(ads_1).set_gain(esphome::ads1115::ADS1115_GAIN_4P096);
          else if (x == "2.048") id(ads_1).set_gain(esphome::ads1115::ADS1115_GAIN_2P048);
          else if (x == "1.024") id(ads_1).set_gain(esphome::ads1115::ADS1115_GAIN_1P024);
          else if (x == "0.512") id(ads_1).set_gain(esphome::ads1115::ADS1115_GAIN_0P512);
          else if (x == "0.256") id(ads_1).set_gain(esphome::ads1115::ADS1115_GAIN_0P256);

sensor:
  - platform: ads1115     # question du continuous mode ?
    multiplexer: 'A0_GND'
    gain: 2.048
    name: "ADS1115 Channel A0-GND"
    id: ads_1
    continuous_mode : true

  - platform: ct_clamp
    sensor: ads_1
    name: ${name} 1
    update_interval: 30s
    filters:
      - calibrate_linear:
          - 0 -> 0
          - 0.03 -> 3.45
          - 0.11 -> 16.6
```

### Anything in the logs that might be useful for us?

```txt
no! sorry. No error. No trace. Just an impossible use case:

I'm just trying to define the continous_mode and can't find a way. Except overriding the component.
```
