### ISSUE TITLE
BL0942 not showing up on the Energy Dashboard

### ISSUE THREAD

**Issue by ShonP40** [esphome/issues#5230]
### The problem

The entities this component generates work just fine (including showing the total used kWh)
But I can’t add the energy usage entity to the energy dashboard for whatever reason (it’s just not showing up there)

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

ESP8266

### Board

LoraTap 20A boiler switch (modified with an ESP12-F)

### Component causing the issue

Belling BL0942 Energy Monitor

### Example YAML snippet

```yaml
uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 4800
  stop_bits: 1

sensor:
  - platform: bl0942
    uart_id: uart_bus
    voltage:
      name: '${friendly_name} Voltage'
    current:
      name: '${friendly_name} Current'
    power:
      name: '${friendly_name} Power'
      filters:
        multiply: -1
    energy:
      name: '${friendly_name} Energy'
    frequency:
      name: "${friendly_name} Frequency"
      accuracy_decimals: 2

    update_interval: 60s
```

### Additional information

![image](https://github.com/esphome/issues/assets/13995143/10b246e5-394e-4515-93a3-b238efa568c9)
