### ISSUE TITLE
Animation does not work with remote files

### ISSUE THREAD

**Issue by telefonmann** [esphome/issues#5232]
### The problem

I would like to show an animation on a display connected to an esp32. Showing local and remote images does work. Showing local animations does work as well. But animations from remote files do not work. Error message is:

`Could not find file '/config/esphome/https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating...`

It seems the file is being searched locally. But the documentation says "Animation inherits all options from the image component", so as displaying remote images does work, I expect the remote animations to work as well.

Thanks in advance!

### Which version of ESPHome has the issue?

2023.11.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

D1 mini ESP32

### Example YAML snippet

```yaml
animation:
  - file: https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif
    type: RGB24
    id: dummy
    resize: 100x100
```
