### ISSUE TITLE
Missing characters

### ISSUE THREAD

**Issue by andrewigali** [esphome/issues#5233]
### The problem

I don't know how long this problem has existed (there was no such problem in the past), with ESPHome 2023.11.6 when I create a new FW, it does not display the accented letters (even without an accent).

Example:
ESPHome code:
esphome:
  name: eloszoba-erzekelok
  friendly_name: Előszoba érzékelők

binary_sensor:
  - platform: gpio
    pin: GPIO35
    name: "Bejárati ajtó"
    device_class: door

Normally, I should receive such an entity identifier in HA: binary_sensor.eloszoba_erzekelok_bejarati_ajto
Instead I get: binary_sensor.elszoba_rzkelk_bjati_ajt

So the following accents are not converted to unaccented ones: á, é, í, ó, ő, ü, ű (these are also used in Hungarian words).

Maybe I'm wrong but it seems that UTF-8 encoding doesn't work if friendly_name: Előszoba érzékelők is entered under esphome:.
Neither in friendly_name nor in entity ID.

Is it possible to correct this?

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.6

### What platform are you using?

ESP32

### Board

ESP32 Wemos D1, ESP32 WROOM 38pin

### Example YAML snippet

```yaml
esphome:
  name: eloszoba-erzekelok
  friendly_name: Előszoba érzékelők


binary_sensor:
  - platform: gpio
    pin: GPIO35
    name: "Bejárati ajtó"
    device_class: door
```
