### ISSUE TITLE
restore_mode seems to be inversed

### ISSUE THREAD

**Issue by jellewie** [esphome/issues#5238]
### The problem

When I compile the switch to "relay_restore_mode: ALWAYS_ON" it will be OFF on boot.
When I compile the switch to "relay_restore_mode: ALWAYS_OFF" it will be ON on boot.
When I compile the switch to "relay_restore_mode: RESTORE_DEFAULT_ON" it will default to OFF on boot.
When I compile the switch to "relay_restore_mode: RESTORE_DEFAULT_OFF" it will default to ON on boot.

This is completely the opposite of what I would expect would happen. The switch is also not defined as inverted, So this seems like a bug to me.
A friend of mine also confirmed to have the same results on their own HA/ESPHOME/PLUG, so it does not appear to be a local issue.

### Which version of ESPHome has the issue?

ESPHome 2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.1

### What platform are you using?

ESP8266

### Board

athom smart plug v2

### Example YAML snippet

```yaml
Full code that I used:

substitutions:
  device_name: "smart-plug-16"
  project_name: "athom.smart-plug-v2"
  project_version: "1.1"       
  project_comment: "new"
  relay_restore_mode: ALWAYS_ON 

esp8266:
  early_pin_init: false
  board: esp8285
#  restore_from_flash: true
#preferences:
#  flash_write_interval: 1min

esphome:
  name: "${device_name}"
  name_add_mac_suffix: false
  comment: "${project_comment}"
  project:
    name: "${project_name}"
    version: "${project_version}"

api:     
  reboot_timeout: 12h
ota: 
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:  
    ssid: "${device_name} FH"
  reboot_timeout: 12h
captive_portal:

dashboard_import:
  package_import_url: github://jellewie/ESPHOME-configs/blob/main/smart-plug-01.yaml

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: status 
    name: "${device_name} status"
    disabled_by_default: true
  - platform: gpio
    pin:
      number: 5
      mode: INPUT_PULLUP
      inverted: true
    name: "${device_name} Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button

sensor:
  - platform: cse7766
    update_interval: 1s
    current:
      name: "${device_name} Current"
      disabled_by_default: true
      filters:
        - lambda: if (id(relay).state){ return x; } else { return 0.0; }
        - sliding_window_moving_average:
            window_size: 60
            send_every: 60
    voltage:
      name: "${device_name} Voltage"
      disabled_by_default: true
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 60
    power:
      name: "${device_name} Power"
      id: power_sensor
      filters:
          - lambda: if (id(relay).state){ return x; } else { return 0.0; }
          - sliding_window_moving_average:
              window_size: 1
              send_every: 60
    energy:
      name: "${device_name} Energy"
      unit_of_measurement: kWh
      filters:
        - multiply: 0.001  #Multiplication factor from W to kW is 0.001
        - sliding_window_moving_average:
            window_size: 60
            send_every: 60
  - platform: total_daily_energy
    name: "${device_name} Total Daily Energy"
    disabled_by_default: true
    restore: true
    power_id: power_sensor
    unit_of_measurement: kWh
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  
  - platform: uptime  # Extra sensor to keep track of plug uptime
    name: "${device_name} Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 0
    disabled_by_default: true
  - platform: wifi_signal # Extra sensor for WiFi signal
    name: "${device_name} WiFi"
    update_interval: 300s
    disabled_by_default: true

switch:
  - platform: gpio
    name: "${device_name}"
    pin: GPIO12 #Red + Relay
    id: relay
    restore_mode: ${relay_restore_mode}

  - platform: template
    name: "${device_name} State"
    lambda: if (id(power_sensor).state > 5 ) {return true;} else {return false;}
    turn_on_action:
      - switch.toggle: relay
    turn_off_action:
      - switch.toggle: relay
    disabled_by_default: true

light:
  - platform: status_led
    name: "${device_name} Status LED"
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO13 #Blue
      
text_sensor:
  - platform: wifi_info 
    ip_address:
      name: "${device_name} IP"
      disabled_by_default: true
    mac_address:
      name: "${device_name} MAC"
      disabled_by_default: true

button:
  - platform: restart
    id: restart_button
    name: "${device_name} Restart"
    disabled_by_default: true

time:
  - platform: sntp
    id: my_time
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
