### ISSUE TITLE
Setting color temperature on CW/WW breaks once CC/CW values have been set directly

### ISSUE THREAD

**Issue by patagonaa** [esphome/issues#5241]
### The problem

When using the "Cold White + Warm White Light" (`light` integration with the platform `cwww`), setting and publishing a CW/WW value breaks setting the values via temperature+brightness.

For example, a cwww light can not be set to max brightness once the `random` effect has been active (as that sets the CW/WW values directly).

This happens, because the method where the CW/WW values are calculated from the color temperature, the `white` value (which is used to calculate the brightness, basically) is set to the current max CW/WW value if `white` is not also being set:
https://github.com/esphome/esphome/blob/cd06dc77ee6693595356a72032731701c66c91ce/esphome/components/light/light_call.cpp#L352-L360

However, in the color mode `COLD_WARM_WHITE` this code targets (which is used for platform `cwww` and `rgbww` with `color_interlock: true`), a `white` value is never set (as the brightness is instead controlled by the `brightness` value).

So once both CW and WW are set below 1, it is impossible to get back to full brightness because the `white` value is never set.

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

BK72XX

### Component causing the issue

light

### Example YAML snippet

```yaml
output:
  - platform: template
    id: output_cw
    type: float
    write_action:
      - logger.log:
              format: "CW: %.1f"
              args: [ 'state' ]
  - platform: template
    id: output_ww
    type: float
    write_action:
      - logger.log:
              format: "WW: %.1f"
              args: [ 'state' ]

light:
  - platform: cwww
    name: "Test"
    cold_white: output_cw
    warm_white: output_ww
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    default_transition_length: 0s
    effects:
      - random:
```
