### ISSUE TITLE
XPT2046 touchsreen component - 2023.12.0 - compiler/editor marks some documented options as invalid

### ISSUE THREAD

**Issue by Zoogara** [esphome/issues#5249]
### The problem

2023.12, XPT2046 touchscreen component.

Options `report_interval:` and `swap_x_y:` are reported as invalid by the compiler and editor, making installation impossible without removing them.

Options still appear in documentation.

### Which version of ESPHome has the issue?

2023.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12

### What platform are you using?

ESP32

### Board

DevKitC

### Component causing the issue

xpt2046

### Example YAML snippet

```yaml
touchscreen:
  platform: xpt2046
  id: touchscreen1
  cs_pin: 21
  interrupt_pin: 27
  update_interval: 50ms
  report_interval: 1s
  threshold: 350
  calibration_x_min: 280
  calibration_x_max: 3806
  calibration_y_min: 185
  calibration_y_max: 3884
  swap_x_y: false
```
