### ISSUE TITLE
2023.12.0 breaks ESP32 IR fan from working

### ISSUE THREAD

**Issue by billmaterial** [esphome/issues#5252]
### The problem

Updating to 2023.12.0 breaks ESP32 IR fan switches from working ("FAN On/Off" switch entity not found) and the other IR fan controls not working.

### Which version of ESPHome has the issue?

2023.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

ESP32

### Board

ESP32-DEV

### Component causing the issue

IR

### Example YAML snippet

```yaml
esphome:
  name: esphome-web-d62e00
  friendly_name: ESPHome Web d62e00
  on_boot:
    priority: -100
    then: 
    - lambda: id(my_display).set_contrast(.01);


esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
 #level: VERBOSE
 baud_rate: 115200
 deassert_rts_dtr: true

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxx"

ota:
  password: !secret ota_password

wifi:
#  power_save_mode: none
  fast_connect: off
  networks:
  - ssid: !secret wifi_ssid_Ghz
    password: !secret wifi_password_both
  - ssid: !secret wifi_ssid_GHz
    password: !secret wifi_password_both

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-D62E00"
    password: "xxxxxxxxxxx"

captive_portal:

# Time
time:
  - platform: homeassistant
    id: esptime

# Wifi Sensor
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 10s
    entity_category: "diagnostic"

# Example configuration entry
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
      id: esp_connected_ssid
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results

# Status Light entry
light:
  - platform: status_led
    name: "Switch state"
    id: switch_state
    pin: 
      number: 2
      mode: OUTPUT

# display brightness entry
  - platform: monochromatic
    name: "Display Brightness"
    id: display_brightness
    output: oled_brightness

output:
  - platform: template
    id: oled_brightness
    type: float
    write_action:
      - lambda: |-
          id(my_display).set_contrast(id(display_brightness).remote_values.get_brightness());

# Example configuration entry
remote_receiver:
  - id: ir_rx
    pin:
      number: 16
      inverted: true
      mode:
        input: true
        pullup: true
    dump: nec

  - id: rf_rx
    pin:
      number: 19
      inverted: false
      mode:
        input: true
        pullup: true
    dump:
      - rc_switch
      - raw
    tolerance: 60% #50%
    filter: 4us #250us
    idle: 4ms #4ms
    buffer_size: 2kb

# Example configuration entry
remote_transmitter:
  - id: ir_tx
    pin: 23
    carrier_duty_percent: 50%
  
  - id: rf_tx
    pin: 18
    carrier_duty_percent: 100%


# GPIO 2 input sensor
binary_sensor:
  - platform: homeassistant
    entity_id: light.esphome_web_d62e00_switch_state
    id: led_status
    internal: true

#  - platform: remote_receiver
#    name: "fan on-off"
#    rc6:
#      address: 0x00FF
#      command: 0x01FF



# Dislay invert switch
switch:
  - platform: template
    name: "Display Invert" 
    id: display_invert
    optimistic: true
    device_class: switch
    turn_on_action:
      - lambda: |-
          id(my_display).init_invert(true);
          id(my_display).setup();
    turn_off_action:
      - lambda: |-
          id(my_display).init_invert(false);
          id(my_display).setup();

# Fan IR Commands  
  - platform: template
    name: "FAN On/Off"
    turn_on_action:
      remote_transmitter.transmit_nec:
        transmitter_id: ir_tx
        address: 0xFF00
        command: 0xFE01
  - platform: template
    name: "FAN Turn off screen"
    turn_on_action:
      remote_transmitter.transmit_nec:
        transmitter_id: ir_tx
        address: 0xFF00
        command: 0xFF00
  - platform: template
    name: "FAN Speed"
    turn_on_action:
      remote_transmitter.transmit_nec:
        transmitter_id: ir_tx
        address: 0xFF00
        command: 0xFE04
  - platform: template
    name: "FAN Swing"
    turn_on_action:
      remote_transmitter.transmit_nec:
        transmitter_id: ir_tx
        address: 0xFF00
        command: 0xF708
  - platform: template
    name: "FAN ION"
    turn_on_action:
      remote_transmitter.transmit_nec:
        transmitter_id: ir_tx
        address: 0xFF00
        command: 0xF20D
  - platform: template
    name: "FAN Timer"
    turn_on_action:
      remote_transmitter.transmit_nec:
        transmitter_id: ir_tx
        address: 0xFF00
        command: 0xF609
# RF Controls
  - platform: template
    name: "Office Light Switch On"
    turn_on_action:
      remote_transmitter.transmit_raw:
        transmitter_id: rf_tx
#        code: [501, -144, 156, -291, 317, -147, 156, -145, 158, -291, 316, -289, 317, -289, 318, -290, 316, -150, 153, -296, 312, -151, 154, -149, 154, -149, 154, -295, 168, -135, 163, -135, 154, -147]
        code: [547, -106, 191, -257, 339, -128, 178, -123, 179, -270, 338, -267, 339, -268, 337, -271, 335, -126, 175, -272, 335, -128, 173, -130, 173, -129, 174, -274, 188, -115, 182, -115, 173, -132,
               516, -127, 171, -279, 327, -132, 170, -133, 170, -277, 329, -277, 328, -281, 325, -281, 326, -135, 166, -282, 325, -137, 164, -142, 161, -139, 164, -284, 177, -125, 173, -125, 163, -140,
               509, -134, 162, -286, 321, -142, 160, -142, 161, -287, 320, -287, 319, -287, 319, -287, 319, -144, 157, -290, 317, -145, 158, -145, 157, -147, 156, -289, 173, -130, 167, -132, 157, -145,
               503, -142, 154, -294, 314, -149, 153, -148, 155, -292, 315, -292, 315, -291, 314, -296, 310, -149, 153, -294, 313, -148, 154, -151, 152, -149, 153, -296, 167, -135, 162, -137, 151, -148,
               501, -144, 153, -294, 314, -148, 153, -151, 152, -295, 312, -295, 311, -296, 311, -295, 311, -151, 148, -303, 302, -161, 141, -161, 142, -158, 149, -301, 156, -147, 156, -137, 151, -150,
               496, -154, 146, -299, 309, -152, 149, -156, 142, -305, 306, -300, 306, -301, 305, -299, 310, -154, 143, -301, 312, -149, 151, -152, 152, -153, 149, -298, 165, -138, 159, -138, 150, -151,
               499, -146, 150, -296, 312, -151, 151, -151, 152, -296, 312, -294, 311, -296, 311, -299, 308, -150, 151, -296, 311, -152, 151, -151, 152, -151, 151, -296, 166, -137, 161, -137, 151, -150]
        repeat:
          times: 20
          wait_time: 500us
  - platform: template
    name: "Office Light Switch Off"
    turn_on_action:
      remote_transmitter.transmit_raw:
        transmitter_id: rf_tx
        code: [501, -147, 149, -296, 312, -150, 152, -150, 153, -296, 312, -294, 312, -296, 310, -297, 310, -152, 149, -298, 310, -153, 149, -298, 164, -139, 310, -152, 150, -292, 148, -153,
               497, -148, 149, -305, 303, -153, 148, -155, 149, -308, 296, -302, 308, -300, 307, -299, 307, -154, 148, -299, 309, -154, 147, -300, 163, -140, 310, -154, 147, -293, 148, -157,
               485, -163, 131, -321, 291, -159, 150, -154, 149, -298, 310, -298, 308, -297, 310, -297, 309, -154, 147, -300, 309, -152, 149, -300, 162, -141, 310, -152, 149, -293, 147, -154,
               496, -149, 148, -299, 309, -155, 146, -156, 148, -304, 304, -297, 305, -302, 309, -300, 307, -154, 148, -299, 309, -153, 148, -301, 161, -141, 310, -151, 150, -293, 147, -153,
               497, -149, 148, -301, 307, -154, 148, -155, 148, -299, 310, -297, 309, -298, 308, -300, 297, -173, 128, -320, 299, -155, 147, -297, 165, -139, 311, -154, 147, -293, 148, -152,
               499, -147, 149, -300, 308, -154, 148, -154, 149, -309, 294, -303, 308, -297, 310, -298, 308, -154, 148, -299, 306, -157, 149, -298, 163, -140, 310, -153, 149, -291, 149, -154,
               487, -157, 149, -298, 312, -151, 149, -152, 151, -298, 310, -296, 311, -296, 310, -300, 307, -153, 149, -300, 308, -151, 151, -298, 164, -139, 310, -154, 148, -292, 148, -152]
        repeat:
          times: 20
          wait_time: 500us

# Display ssd1306 128x64
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True
  id: bus_a
  frequency: 400kHz

# Fonts
font:
  - file: "fonts/SourceCodePro-Regular.ttf"
    id: my_font
    size: 12
  - file: "fonts/SourceCodePro-Regular.ttf"
    id: my_font_small
    size: 10


# Setup Display
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    update_interval: 1s
    contrast: 1%
    id: my_display 
    lambda: |-
      if (id(esp_connected_ssid).has_state()){
        it.printf(64, 0, id(my_font_small), TextAlign::TOP_CENTER, "%s", id(esp_connected_ssid).state.c_str());
      }
      it.printf(0, 28, id(my_font), TextAlign::BASELINE_LEFT, "WiFi Signal");
      if (id(wifi_signal_db).has_state()){
        it.printf(127, 28, id(my_font), TextAlign::BASELINE_RIGHT, "%1.0fdB", id(wifi_signal_db).state);
      }
      
      it.printf(0, 45, id(my_font), TextAlign::BASELINE_LEFT, "LED State");
      if ((id(led_status).state) == 0) {
        it.printf(127, 45, id(my_font), TextAlign::BASELINE_RIGHT, "OFF");
      }
      if ((id(led_status).state) == 1) {
        it.printf(127, 45, id(my_font), TextAlign::BASELINE_RIGHT, "ON");
      }

      it.strftime(64, 50, id(my_font), TextAlign::TOP_CENTER, "%H:%M:%S", id(esptime).now());
```
