### ISSUE TITLE
Duplicated items (but reallly not) after last update

### ISSUE THREAD

**Issue by VladNord** [esphome/issues#5260]
### The problem

```
deep_sleep:
  run_duration: 3min
  sleep_duration: 1min
  id: deep_sleep_1
  wakeup_pin: 39
  wakeup_pin_mode: INVERT_WAKEUP

```

Error the following:
 Pin 39 is used in multiple places

```
mi:
  
  id: mi1
  ce_pin: 4
  csn_pin: 5
  reset_pin: 0
```

Same situation with MI custom component, where is reset pin  perceived as duplicated gpio0

### Which version of ESPHome has the issue?

2023.12.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12

### What platform are you using?

ESP32

**Comment by sheaur** [comment]
Add "allow_other_uses: true"

**Comment by VladNord** [comment]
> ```
> deep_sleep:
>   run_duration: 3min
>   sleep_duration: 1min
>   id: deep_sleep_1
>   wakeup_pin: 39
>   allow_other_uses: true
>   wakeup_pin_mode: INVERT_WAKEUP
> ```

<img width="836" alt="image" src="https://github.com/esphome/issues/assets/51515620/71de7b9b-19cd-4650-a659-2fc3d05f7d10">

not possible :(

**Comment by sheaur** [comment]
Where is the other pin 39?

**Comment by VladNord** [comment]
> Where is the other pin 39?

```
binary_sensor:

#ac_in
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
      allow_other_uses: true
    name: "Home AC IN"
    id: home_ac_in
    device_class: power
    filters:
      - delayed_on_off: 1s
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: home_ac_in
            then:
              - deep_sleep.prevent: deep_sleep_1
              - rtttl.play: ${ac_on_song}
        - if:
            condition:
              - binary_sensor.is_off: home_ac_in
            then:
              - deep_sleep.prevent: deep_sleep_1
              - rtttl.play: ${ac_off_song}
```

**Comment by sheaur** [comment]
Delete "allow_other_uses: true" in deep_sleep and try

**Comment by VladNord** [comment]
> Delete "allow_other_uses: true" in deep_sleep and try

<img width="640" alt="image" src="https://github.com/esphome/issues/assets/51515620/ea312d1f-17b0-42df-a7d3-6229ca760bf3">

Done

**Comment by taygs** [comment]
I'm having a similar problem, started with 2023.12.0

I have 3x MCP23017's and I'm getting the same "Pin X is used in multiple places." messages for all GPIOs.

Still works in 2023.11.6.

![image](https://github.com/esphome/issues/assets/36367818/1ead1ccd-764f-4f91-ab80-5a9a6a024bd7)

**Comment by ssieb** [comment]
@taygs that was fixed in the last point release.

**Comment by taygs** [comment]
@ssieb I'm now on 2023.12.2 and still have the messages.

**Comment by fixed77** [comment]
2023.12.2. problem is not resolved.

**Comment by ssieb** [comment]
@sheaur @VladNord you're putting it in the wrong place.  It needs to be in the pin schema as described in the docs.

**Comment by jesserockz** [comment]
@taygs @fixed77 can you please paste your entire config files so I can attempt to reproduce?

I cannot reproduce the error with the above screenshot config only as it works just fine which points to something else in your config.

**Comment by ssieb** [comment]
I tried the following using 2023.12.0 and there were no errors:
```yaml
mcp23017:
  - id: mcp23017_1
  - id: mcp23017_2

binary_sensor:
  - platform: gpio
    id: mcp23017_pin_1
    pin:
      number: 1
      mcp23xxx: mcp23017_1
  - platform: gpio
    id: mcp23017_pin_2
    pin:
      number: 1
      mcp23xxx: mcp23017_2
```
