### ISSUE TITLE
"ssd1351_spi" fails to display anything other than numbers

### ISSUE THREAD

**Issue by 3ative** [esphome/issues#5261]
### The problem

"ssd1351_spi" now can only display numbers after 2023.12.0 / 2023.12.1 update.  

Not working here are:
* Graphs
* %s values: I.E. "id(xxxxxx).state.c_str()"

### Which version of ESPHome has the issue?

2023.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

ESP32

### Board

Generic ESP32 Dev Board

### Component causing the issue

display:   - platform: ssd1351_spi

### Example YAML snippet

```yaml
text_sensor:
  - platform: template
    id: co2_warning

graph:
  - id: graph1
    duration: 60min
    x_grid: 10min
    y_grid: 500
    width: 123
    height: 50
    traces:
      - sensor: pms25
        line_type: SOLID
        line_thickness: 1
        color: oled_yellow

display:
  - platform: ssd1351_spi
    id: oled
    model: "SSD1351 128x128"
    reset_pin: GPIO16
    brightness: 0.5 # Default 1.0
    cs_pin: GPIO04
    dc_pin: GPIO05
    lambda: |-
      it.printf(68, 44, id(verdana), TextAlign::CENTER, "%s", id(co2_warning).state.c_str());
      it.graph(2, 62, id(graph1), oled_grid);
```

### Anything in the logs that might be useful for us?

```txt
[16:29:22][W][component:214]: Component display took a long time for an operation (0.10 s).
[16:29:22][W][component:215]: Components should block for at most 20-30ms.
```

### Additional information

The graph is ok for a few minutes then freezes.

Rebooting and re-flashing (_OTA & USB_) didn't help. 😣
