### ISSUE TITLE
Changed sensor name after update

### ISSUE THREAD

**Issue by heggi** [esphome/issues#5266]
### The problem

My temperature sensor changed the name from `esphome_temperature_test_temperature_1` to `esphome_web_394f6f_temperature_1` after firmware update to 2023.12.1
Firmware's sensor name stays the same (`esphome_temperature_test_firmware`)
Other ESP devices didn't change any sensor's names.

### Which version of ESPHome has the issue?

2023.12.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

d1_mini

### Example YAML snippet

```yaml
esphome:
  name: esphome-web-394f6f
  friendly_name: ESPHome Temperature Test

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxx"

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
    
dallas:
  - pin: D4
    update_interval: 10s

sensor:
  - platform: dallas
    index: 0
    name: "Temperature #1"
```
