### ISSUE TITLE
Sonoff mini default config gives error

### ISSUE THREAD

**Issue by txitxo0** [esphome/issues#5267]
### The problem

Using the provided config in docs for sonoff mini, there is an error regarding the pin 13. "Pin 13 is used in multiple places"

So, the proble should be in here:
```
status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # the 4 lines below define the Blue LED light on Sonoff Mini, to expose in HomeAssistant remove line "internal: true"
  - platform: monochromatic
    name: ${device_name}_blueled
    output: blue_led
    internal: true # hides the Blue LED from HomeAssistant
    ```

![image](https://github.com/esphome/issues/assets/12279324/acb5f7d3-0a2c-4cc0-a817-502e7d51ec3b)

### Which version of ESPHome has the issue?

2023.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

esp8266_pwm

### Board

Sonoff mini

### Component causing the issue

output

### Example YAML snippet

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # the 4 lines below define the Blue LED light on Sonoff Mini, to expose in HomeAssistant remove line "internal: true"
  - platform: monochromatic
    name: ${device_name}_blueled
    output: blue_led
    internal: true # hides the Blue LED from HomeAssistant

### Anything in the logs that might be useful for us?

Pin 13 is used in multiple places
