### ISSUE TITLE
Entities dissapeared after 5810 pull 

### ISSUE THREAD

**Issue by Csontikka** [esphome/issues#5268]
### The problem

https://github.com/esphome/esphome/pull/5810

A lot (switch) entities comes from the esphome has been disappeared. Not renamed, disappeared!
Maybe the problem with the string sanitizing procedure does not handle right all of the used characters
The affected entities contains hungarian characters.
Entities not containing hungarian characters works as expected

example yaml in details:

The special chars:
öőúáűüóíÖÜÓŐÚÉÁŰÍ

### Which version of ESPHome has the issue?

2023.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.1

### What platform are you using?

ESP8266

### Board

esp32,

### Example YAML snippet

```yaml
- platform: gpio
    pin: GPIO27
    name: Csepegtet**ő** (elől)
    id: relay5
    on_turn_on:
    - script.execute: script_relay5
    on_turn_off:
    - script.stop: script_relay5
```

### Anything in the logs that might be useful for us?

```txt
in HA log there is nothing relevant
```
