### ISSUE TITLE
Scratch Pad checksum invalid - Just started after update yesterday 12-21-23

### ISSUE THREAD

**Issue by ghalpha** [esphome/issues#5273]
### The problem

So anytime I try to use one of the two Dallas sensors I have in ANY other logic I get a checksum error. However if I drop all references to the values they work fine. I can't even reference them to a sensor that does nothing. Nothing has changed with the hardware or wiring in over a year at this point as it controls the temperature of my server rack. 
![image](https://github.com/esphome/issues/assets/37425390/abfd1494-d706-4f84-bd9e-ee4bec4922e6)


### Which version of ESPHome has the issue?

2023.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

ESP32

### Board

ESP-WROOM-32 Development Board

### Component causing the issue

Dallas/OneWire

### Example YAML snippet

```yaml
# SETUP GPIO FOR DALLAS SENSOR 
dallas:
  - pin: GPIO16
    update_interval: 2s
# GET TEMP/HUMIDITY FROM ONE WIRE                                                                                                                                                                                                        
  - platform: dallas
    address: 0x0f3c6df64853ab28
    name: "Intake Temperature"
    id: intakeTemp
    filters:
      - filter_out: NaN
      - lambda: return x * (9.0/5.0) + 32.0;
      - heartbeat: 10s
    unit_of_measurement: °F
    accuracy_decimals: 1
    
  - platform: dallas
    address: 0x0a3ca8f6487e3e28  
    name: "Exhaust Temperature"  
    id: exhaustTemp
    filters:
      - filter_out: NaN
      - lambda: return x * (9.0/5.0) + 32.0;
      - heartbeat: 10s
    unit_of_measurement: °F
    accuracy_decimals: 1
---------This now causes the sensor to keep flipping and was supposed to only fail over if the sensor failed. Now it blinks back and forth because when I move to my backup I2C sensor it clears the fault and flips back. I've set the lambda to just my I2C sensor for now and the sensors work fine but the way I designed my controller I need the Dallas sensors to work.--------------------
  # This converts the F to C for use in the Climate PID
  - platform: template
    name: Control Temperature
    id: controlTemp
    lambda: |-
      if (id(exhaustTemp).has_state()) {
          return id(exhaustTemp).raw_state;
      } else {
          return id(controllerTemperature).raw_state;
      }
    update_interval: 1s
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - heartbeat: 5s
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
