### ISSUE TITLE
Devices with esp32-c3-devkitm-1 Inaccessible after updating 2023.12.*

### ISSUE THREAD

**Issue by lensherm** [esphome/issues#5276]
### The problem

After this update none of the 4 SwitchBot Plug Mini devices are connecting to wifi. The LED on them keeps blinking blue, indicating no network connectivity. The captive portal hotspot wifi is available and showing up, but once I enter the password and authenticate onto the wifi, no DHCP assignment takes place. Manually assigning the network info on my PC doesn't do anything either, as the device doesn't appear at the 192.168.4.1 address. Looks like the wifi/network component of esphome is somehow malfunctioning after this update.

### Which version of ESPHome has the issue?

2023.12.*

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
substitutions:
  name: compressor-switch
  friendly_name: Compressor Switch

esphome:
  name: ${name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

web_server:
  port: 80


# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "SwitchBot Plug Hotspot"
    password: !secret esphome_fallback_ap_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret esphome_api_password

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Bluetooth Proxying
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

switch:
  - platform: gpio
    name: "Relay"
    id: "relay"
    device_class: outlet
    pin: 6
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - light.turn_on: white_led
    on_turn_off:
      then:
        - light.turn_off: white_led

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: 2
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.toggle: relay
      
light:
  - platform: binary
    internal: true
    name: "white led"
    id: "white_led"
    output: white_output
    
output:
  - id: white_output
    platform: gpio
    pin: GPIO7
    inverted: true

# set blue led as status
status_led:
  pin:
    number: GPIO8
    inverted: true

sensor:
  - platform: hlw8012
    sel_pin:
      number: 20
      inverted: true
    cf_pin: 18
    cf1_pin: 19
    model: BL0937
    voltage_divider: 1467
    current:
      name: "Current"
    voltage:
      name: "Voltage"
    power:
      name: "Power"
    energy:
      name: "Energy"
    update_interval: 1s
    change_mode_every: 4
```

**Comment by lensherm** [comment]
Was able to get the device into safe mode and flash it with the bluetooth proxy config removed. The offending piece seems to be `esp32_ble_tracker:`

**Comment by clydebarrow** [comment]
Have you tried setting the scan parameters to more reasonable values?
```
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

```
this basically dedicates all the shared 2.4GHz transceiver time to BLE, the window should be smaller than the interval to allow time for WiFi operations. The defaults are 320ms/30ms.

**Comment by ssieb** [comment]
Even with the default settings, it still has some trouble.  There's a workaround at https://github.com/esphome/issues/issues/3668#issuecomment-1287568813 that seems to work.

**Comment by clydebarrow** [comment]
The C3 is not a really good candidate for a BLE proxy, being a single core. Seems like it can be made to work, but it's always going to be rather marginal for the job I would think.

**Comment by clydebarrow** [comment]
Since the issue seems to be that the WiFi needs exclusive control of the RF section for a fairly long time when first connecting (and presumably reconnecting), you could try something like this:

```
esp32_ble_tracker:
  scan_parameters:
    continuous: false

api:
  on_client_connected:
     - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
     - esp32_ble_tracker.stop_scan:

 ```

Since without the API connection (which requires WiFi connected) there is no point in scanning anyway, and if the WiFi drops the API connection will drop, allowing a reconnect.
