### ISSUE TITLE
Multiple deep_sleep components

### ISSUE THREAD

**Issue by jeff-h** [esphome/issues#528]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (nodemcu v2)

**Affected component:**

https://esphome.io/components/deep_sleep.html

**Description of problem:**
It's unclear whether multiple deep_sleep definitions are allowed. In the absence of anything stating you can't, my hope was that you can due to the precedent in other components. However, there's a validation error thrown when I have more than one.

**Problem-relevant YAML-configuration entries:**
```yaml
deep_sleep:
  # awake 40s in every 2 mins
  - id: sleep_a_little
    run_duration: 40s
    sleep_duration: 80s 

  # awake 40s in every 6 mins
  - id: sleep_a_lot 
    run_duration: 40s
    sleep_duration: 320s 
```

**Logs (if applicable):**

```
The live YAML validator reports "expected a dictionary".
```

**Additional information and things you've tried:**

I'd like my ESP8266 to sleep a little during the day, and a lot at night (it's running off a battery and solar panel, so there's reasonably ample power in the day). I was hoping to have a `time` component switch between the two `deep_sleep` definitions.
