### ISSUE TITLE
ESPHome 2023.12.3 killed my Sonoff Mini devices

### ISSUE THREAD

**Issue by MT31972** [esphome/issues#5280]
### The problem

I have several Sonoff Mini devices which worked quite well until I upgraded from 2023.11.6 to 2023.12.3. 
After update they don't appear in my wifi (and HomeAssistant) anymore and they started recovery AP.
When I connect to recovery AP I can reach them by ping 192.168.4.1, but when try to update them from windows commandline I get an error.

esphome run --device 192.168.4.1 C:\Users\marku\Downloads\wzlichtwandlinks.yaml
...
RAM:   [====      ]  39.0% (used 31932 bytes from 81920 bytes)
Flash: [====      ]  42.6% (used 436403 bytes from 1023984 bytes)
============================================= [SUCCESS] Took 5.64 seconds =============================================
INFO Successfully compiled program.
INFO Connecting to 192.168.4.1
ERROR Connecting to 192.168.4.1:8266 failed: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte (sorry for german, connection is refused, wrong port?).

First I thought that maybe I have some wifi issues, but after the third device shows the same issue, I suppose it might be related to ESPHome version. Other Sonoff devices or Gosund sockets updated without any issues.

### Which version of ESPHome has the issue?

2023.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12

### What platform are you using?

ESP8266

### Board

sonoff mini

### Example YAML snippet

```yaml
substitutions:
  plug_name: "wzlichtwandlinks"
  friendly_name: "Wand Links"

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi50_name
  password: !secret wifi50_pwd
  domain: .tondorf
  use_address: 192.168.90.207

 # manual IP
  manual_ip:
    static_ip: 192.168.90.207
    gateway: 192.168.90.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name}"
    password: !secret esp_fallback_hs_pwd

# Enable logging
logger:
#  level: VERBOSE
  
# Enable Home Assistant API
api:
  encryption:
    key: !secret esp_api_key

ota:
  safe_mode: True
  password: !secret esp_ota_pwd

time:
  - platform: homeassistant
    id: homeassistant_time

status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - light.toggle: 
          id: ${plug_name}_light

  - platform: gpio
    name: "${friendly_name} Switch"
    pin: GPIO04
    id: ${plug_name}_switch
    on_press:
      then:
        - light.turn_on:
            id: ${plug_name}_light
    on_release:
      then:
        - light.turn_off:
            id: ${plug_name}_light

output:
  - platform: gpio
    pin: GPIO12
    id: ${plug_name}_relay

light:
  - platform: binary
    name: "${friendly_name} Licht"
    id: ${plug_name}_light
    output: ${plug_name}_relay
```

### Anything in the logs that might be useful for us?

```txt
No
```
