### ISSUE TITLE
Fallback AP does not work on cb2s module

### ISSUE THREAD

**Issue by hackintoshlover** [esphome/issues#5283]
### The problem

I have 2 channel wireless switch with tuyamcu which contains wifi module CB2S.
I successfuly added esphome and it works amazing with home assistant.
The only problem is when my network goes down or when i relocate the device, the device does not start AP mode automatically.
The same setup works perfectly with esp32 or esp8266 whenever it does not find the registered network, it automatically goes into AP mode. 
Kindly help with CB2S, since right now the only way to upload code in the device is recompiling the code with new wifi credentials and uploading it.
Also when i press factory reset nothing it just restarts the device, be it any device like esp32 or esp8266 or CB2S or anything else.

### Which version of ESPHome has the issue?

 LibreTiny Esphome 2023.9.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.3

### What platform are you using?

BK72XX

### Board

CB2S

### Component causing the issue

captive portal

### Example YAML snippet

```yaml
esphome:
  name: zen-2c5w

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

logger:

web_server:

captive_portal:

mdns:

api:
  password: ""

ota:
  password: ""

wifi:
  ssid: myssid
  password: mypassword
  ap:

button:
  - platform: restart
    name: Restart
  - platform: factory_reset
    name: Reset
    
debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

sensor:
  - platform: uptime
    name: Uptime

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

tuya:
  # DPIDs processed from schema model: 000003p01m

switch:
  - platform: tuya
    switch_datapoint: 1
    name: Switch 1
  - platform: tuya
    switch_datapoint: 2
    name: Switch 2

binary_sensor:
  - platform: tuya
    sensor_datapoint: 103
    name: Pair Result 1
  - platform: tuya
    sensor_datapoint: 104
    name: Pair Result 2
  - platform: tuya
    sensor_datapoint: 110
    name: Clear Result 1
  - platform: tuya
    sensor_datapoint: 111
    name: Clear Result 2
```
