### ISSUE TITLE
Pin xx is used in multiple places.

### ISSUE THREAD

**Issue by kecajtop** [esphome/issues#5286]
### The problem

As the title description. Adding allow_other_uses flag hasn't got any effect. I made this component some times ago form exsiting code sn74hc595 and sn74hc165. Was working fine until a recent update.

### Which version of ESPHome has the issue?

2023.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

ESP32

### Board

dt-r008

### Component causing the issue

dtr0xx_io

### Example YAML snippet

```yaml
substitutions:
  devicename: dt-r008
  upper_devicename: DT-R008
  friendly_name: DT-R008
  device_icon: mdi:chip
  key: !secret key_dt-r008
  ota: !secret ota_dt-r008
  IP: !secret IP_dt-r008
  fallback_pass: !secret fallback_pass_dt-r008
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ssid_ha: !secret wifi_ssid_ha
  wifi_password_ha: !secret wifi_password_ha
  log_level: DEBUG

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml
  generic: !include common/generic.yaml
  esp32_only: !include common/esp32_only.yaml

esphome:
  name: $devicename

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://kecajtop/dtr0xx_io@master
    refresh: 60s
    components:
      - dtr0xx_io
  - source: github://TheStaticTurtle/esphome_syslog
    components: [syslog]

#ethernet:
#  type: JL1101
#  mdc_pin: 23
#  mdio_pin: 18
#  clk_mode: GPIO17_OUT
#  power_pin: 0
#  phy_addr: 1

syslog:
    ip_address: "192.168.2.2"
    port: 514
    enable_logger: false

dtr0xx_io:
  - id: dtr0xx_io_hub
    dingtian_clk_pin: GPIO14
    dingtian_q7_pin: GPIO16
    dingtian_sdi_pin: GPIO13
    dingtian_pl_pin: GPIO32
    dingtian_rck_pin: GPIO15

output:
  - platform: ledc
    pin: GPIO2
    id: gpio_2

  - platform: gpio
    name: ${friendly_name} Input Close
    id: input_2
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 6
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    #on_press:
    #  then:
    #    - switch.toggle: relay_2

  - platform: gpio
    name: ${friendly_name} Input Open
    id: input_3
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 5
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    #on_press:
    #  then:
    #    - switch.toggle: relay_3
    #    - script.execute: backlight_toggle

  - platform: gpio
    name: ${friendly_name} Input 4
    id: input_4
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 4
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
#    on_press:
#      then:
#        - switch.toggle: relay_4
#       - script.execute: backlight_toggle

  - platform: gpio
    name: ${friendly_name} Input 5
    id: input_5
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 3
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
#    on_press:
#      then:
#        - switch.toggle: relay_5
#        - script.execute: backlight_toggle

  - platform: gpio
    name: ${friendly_name} Input 6
    id: input_6
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 2
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
#    on_press:
#      then:
#        - switch.toggle: relay_6
#        - script.execute: backlight_toggle

  - platform: gpio
    name: ${friendly_name} Input 7
    id: input_7
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 1
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
#    on_press:
#      then:
#        - switch.toggle: relay_7
#        - script.execute: backlight_toggle

  - platform: gpio
    name: ${friendly_name} Input 8
    id: input_8
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 0
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
#    on_press:
#      then:
#        - switch.toggle: relay_8
#        - script.execute: backlight_toggle

  - platform: gpio
    name: ${friendly_name} Input 9
    id: input_9
    pin:
      number: 34
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
#    on_press:
#      then:
#      - script.execute: backlight_toggle


switch:
  - platform: gpio
    name: ${friendly_name} Gate Button
    id: relay_1
    restore_mode: ALWAYS_OFF
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 7
      inverted: false

  - platform: gpio
    name: ${friendly_name} Relay 2
    id: relay_2
    restore_mode: ALWAYS_OFF
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 6
      inverted: false

  - platform: gpio
    name: ${friendly_name} Relay 3
    id: relay_3
    restore_mode: ALWAYS_OFF
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 5
      inverted: false

  - platform: gpio
    name: ${friendly_name} Relay 4
    id: relay_4
    restore_mode: ALWAYS_OFF
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 4
      inverted: false

  - platform: gpio
    name: ${friendly_name} Relay 5
    id: relay_5
    restore_mode: ALWAYS_OFF
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 3
      inverted: false

  - platform: gpio
    name: ${friendly_name} Relay 6
    id: relay_6
    restore_mode: ALWAYS_OFF
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 2
      inverted: false

  - platform: gpio
    name: ${friendly_name} Relay 7
    id: relay_7
    restore_mode: ALWAYS_OFF
    interlock: [relay_8]
    interlock_wait_time: 250ms
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 1
      inverted: false

  - platform: gpio
    name: ${friendly_name} Relay 8
    id: relay_8
    restore_mode: ALWAYS_OFF
    interlock: [relay_7]
    interlock_wait_time: 250ms
    pin:
      dtr0xx_io: dtr0xx_io_hub
      number: 0
      inverted: false
```

### Anything in the logs that might be useful for us?

```txt
N/A
```

### Additional information

I did try to use flag allow_other_uses but dosn't work. I made this component some times ago form exsiting code sn74hc595 and sn74hc165. Was working fine until a recent update. 

```
Failed config

binary_sensor.gpio: [source <unicode string>:175]
  platform: gpio
  id: input_1
  name: DT-R008 Input Light
  pin: 
    dtr0xx_io: dtr0xx_io_hub
    number: 7
    inverted: True
    
    [allow_other_uses] is an invalid option for [pin].
    allow_other_uses: True
  filters: 
    - delayed_on: 10ms
    - delayed_off: 10ms
```
