### ISSUE TITLE
remote_transmitter.transmit_rc5 component breaks in Esphome 2023.12.x

### ISSUE THREAD

**Issue by makzdot** [esphome/issues#5287]
### The problem

First of all. Thanks for this great project! It's awesome!

Sinds the latest update my remote_transmitter component stopped working partially. Downgrading to 2023.11.x it all works again.

Samsung component still works, for example
  - platform: template
    name: Samsung Enter
    on_press:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E016E9

For my Cambridge Audio Amplifier everything stopped working and the components do not show up in HA anymore. Here is the relevant config:

remote_transmitter:
  pin: 12
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "MakzAmp Input: HifiBerry"
    icon: mdi:music
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x10
        command: 0x69

  - platform: template
    name: "MakzAmp Input: TV"
    icon: mdi:apple
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x10
        command: 0x6A

  - platform: template
    name: "MakzAmp: On"
    icon: mdi:audio-video
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x19
        command: 0x0E

  - platform: template
    name: "MakzAmp: Off"
    icon: mdi:audio-video-off
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x19
        command: 0x0F
        
  - platform: template
    name: "MakzAmp: Volume Up"
    icon: mdi:volume-plus
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x10
        command: 0x10

  - platform: template
    name: "MakzAmp: Volume Down"
    icon: mdi:volume-minus
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x10
        command: 0x11

The only possible relevant change I found was: https://github.com/esphome/esphome/pull/4995

I hope someone can help!

Best regards,
Max

### Which version of ESPHome has the issue?

2023.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

ESP32

### Board

featheresp32

### Component causing the issue

remote_transmitter

### Example YAML snippet

```yaml
remote_transmitter:
  pin: 12
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "MakzAmp Input: HifiBerry"
    icon: mdi:music
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x10
        command: 0x69

  - platform: template
    name: "MakzAmp Input: TV"
    icon: mdi:apple
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x10
        command: 0x6A

  - platform: template
    name: "MakzAmp: On"
    icon: mdi:audio-video
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x19
        command: 0x0E

  - platform: template
    name: "MakzAmp: Off"
    icon: mdi:audio-video-off
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x19
        command: 0x0F
        
  - platform: template
    name: "MakzAmp: Volume Up"
    icon: mdi:volume-plus
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x10
        command: 0x10

  - platform: template
    name: "MakzAmp: Volume Down"
    icon: mdi:volume-minus
    on_press:
      remote_transmitter.transmit_rc5:
        address: 0x10
        command: 0x11
```

### Anything in the logs that might be useful for us?

```txt
I found nothing relevant in the logs
```

### Additional information

Could be related to this change?: https://github.com/esphome/esphome/pull/4995
