### ISSUE TITLE
Graphical menu - doesn't work properly w/o pages

### ISSUE THREAD

**Issue by latonita** [esphome/issues#5288]
### The problem

In case I don't use Pages in my display, graphical menu can't be closed. It never returns back to my display lambda and stays on screen after `display_menu:hide:`
@MrMDavidson, Either code shall be fixed with proper switching back or documentation - to state that you have to use `pages` even with only one page.

### Which version of ESPHome has the issue?

2023.12.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Anything in the logs that might be useful for us?

```txt
Apparently this code doesn't work properly, if 'pages' are not used for the 'display'.
In case I have no 'pages', then get_active_page() returns nullptr

void GraphicalDisplayMenu::on_before_show() {
  if (this->display_ != nullptr) {
    this->previous_display_page_ = this->display_->get_active_page();
    this->display_->show_page(this->display_page_.get());
    this->display_->clear();
  } else {
    this->update();
  }
}

void GraphicalDisplayMenu::on_before_hide() {
  if (this->previous_display_page_ != nullptr) {
    this->display_->show_page((display::DisplayPage *) this->previous_display_page_);
    this->display_->clear();
    this->update();
    this->previous_display_page_ = nullptr;
  } else {
    this->update();
  }
```

**Comment by MrMDavidson** [comment]
In future can you please include the relevant configuration and problem scenario in your issue?

Without pages you will need to use "advanced" mode. Eg.
```yaml
graphical_display_menu:
  id: my_menu
  items:
    # ... other items here
    - type: command
      text: Exit Menu System
      on_value:
        then:
          - display_menu.hide: my_menu

display:
  - platform: ...
    lambda: |-
      const auto width = it.get_width();
      const auto height = it.get_height();

      if (id(my_menu).is_active()) {
        it.menu(0, 0, id(my_menu), width, height);
      } else {
        it.print(0, 0, id(font), "Menu is hidden, other drawing would go here here");
      }
```
