### ISSUE TITLE
Frequency is mandatory for pca9685

### ISSUE THREAD

**Issue by djtef** [esphome/issues#5301]
### The problem

The configuration variable "_frequency_" is supposed to be optional according to the documentation but it is required for the compilation.

### Which version of ESPHome has the issue?

2023.9.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

pca9685

### Example YAML snippet

```yaml
i2c:
  sda: 27
  scl: 14
  id: bus_a
  
pca9685:
  i2c_id: bus_a

output:
  - platform: pca9685
    channel: 0
    id: pwm01

light:
  - platform: monochromatic
    name: 'main light'
    output: pwm01
```

### Anything in the logs that might be useful for us?

```txt
esphome compile pca9685.yaml
INFO ESPHome 2023.9.3
INFO Reading configuration pca9685.yaml...
Failed config

pca9685: [source pca9685.yaml:26]

  Frequency is required.
  - i2c_id: bus_a
```

### Additional information

With the frequency it is OK :
```
i2c:
  sda: 27
  scl: 14
  id: bus_a
  
pca9685:
  i2c_id: bus_a
  frequency: 1000

output:
  - platform: pca9685
    channel: 0
    id: pwm01

light:
  - platform: monochromatic
    name: 'main light'
    output: pwm01
```
