### ISSUE TITLE
RGBW bulbs state OFF but still are DIM.

### ISSUE THREAD

**Issue by ThrashinVictim** [esphome/issues#5302]
### The problem

I just updated to ESPHOME 2023.12.5. And for some reason my Wallfire E27 bulbs state they are OFF but still glow very dim.

This didn't happen until I updated.
I searched and found a post from March 7th that stated the same issue but was unresolved.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
esphome:
  name: smart-bulb-1-right

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:

# WebServer
web_server:
  port: 80

my9231:
  data_pin: GPIO13
  clock_pin: GPIO15
  num_channels: 4
  num_chips: 1
  bit_depth: 8

output:
  - platform: my9231
    id: output_red
    channel: 3
  - platform: my9231
    id: output_green
    channel: 2
  - platform: my9231
    id: output_blue
    channel: 1
  - platform: my9231
    id: output_cold_white
    channel: 0

light:
  - platform: rgbw
    name: smart-bulb-1-right
    red: output_red
    green: output_green
    blue: output_blue
    white: output_cold_white
```
