### ISSUE TITLE
Entities renamed in 12.x from 11.x (and earlier)

### ISSUE THREAD

**Issue by jshep321** [esphome/issues#5311]
### The problem

I suspect this problem is related to https://github.com/esphome/esphome/pull/5983

I have a air quality sensor that has sensor names including the greek mu character.  The sensor name in esphome yaml file had the mu and the home assistant sensor name would convert the (mu)g to "ug".  In 12.x the mu character was not converted but simply dropped.  This might be preferable behavior, but broke sensors as they were all renamed entities after updating the device.

yaml excerpt:
```yaml
sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
```

### Which version of ESPHome has the issue?

2023.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.4

### What platform are you using?

ESP32

### Board

Adafruit HUZZAH32

### Component causing the issue

text parser
