### ISSUE TITLE
Servo component: After power loss, servo snaps to idle position first time servo.write is called

### ISSUE THREAD

**Issue by derekpovah** [esphome/issues#5313]
### The problem

The first time `servo.write` is called after a node has restarted, the servo will snap to its idle position at full speed, then run to the newly set position.

Seems to happen when you mess with `transition_length` and `restore`. Different combinations and lengths will either reproduce or not reproduce the issue.

### Which version of ESPHome has the issue?

2023.12.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

servo

### Example YAML snippet

```yaml
# Straight out of the Servo Component docs with an added transition_length and restore
# Example configuration entry
servo:
  - id: my_servo
    output: pwm_output
    restore: True
    transition_length: 3s

# Example output platform
# On ESP32, use ledc output
output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D1
    frequency: 50 Hz
```

### Additional information

Not surprisingly, calling `internal_write` directly doesn't cause the snap to idle issue since it essentially bypasses all of the time calculations in the loop.

Potentially related: #4984, #5292
