### ISSUE TITLE
again: fatal error: SPI.h: No such file or directory

### ISSUE THREAD

**Issue by olekdata** [esphome/issues#5315]
### The problem

external library compilation error

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.12.4

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

RadioLib @ 5.7.0

### Example YAML snippet

```yaml
esphome:
  name: stacja-pogody
  friendly_name: stacja-pogody

  #includes:
  #  - Bresser5in1.h

  libraries:
    - SPI
    - "jgromes/RadioLib@^5.3.0"


esp8266:
  board: d1_mini


# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: "jw6Zuq1G14bjfMkswZlvKHYRlfOYkujChAsc/gGdPag="

ota:
  password: "8257e45a9eb872880214ffb37b3d216e"



wifi:
  networks:
  - ssid: !secret wifi_ssidK
    password: !secret wifi_passwordK
  - ssid: !secret wifi_ssidN
    password: !secret wifi_passwordN
  - ssid: !secret wifi_ssidA
    password: !secret wifi_passwordA

  manual_ip:
    static_ip: 192.168.1.213
    gateway: 192.168.1.1
    subnet: 255.255.255.0  
    dns1: 192.168.1.1  


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stacja-Pogody Fallback Hotspot"
    password: "YMoAYwlUkrfO"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/stacja-pogody.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing stacja-pogody (board: d1_mini; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- SPI @ 1.0
|-- RadioLib @ 5.7.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
Compiling .pioenvs/stacja-pogody/src/main.cpp.o
Compiling .pioenvs/stacja-pogody/lib353/RadioLib/Module.cpp.o
Compiling .pioenvs/stacja-pogody/lib353/RadioLib/modules/CC1101/CC1101.cpp.o
Compiling .pioenvs/stacja-pogody/lib353/RadioLib/modules/LLCC68/LLCC68.cpp.o
In file included from .piolibdeps/stacja-pogody/RadioLib/src/Module.cpp:1:
.piolibdeps/stacja-pogody/RadioLib/src/Module.h:7:12: fatal error: SPI.h: No such file or directory

*************************************************************
* Looking for SPI.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:SPI.h"
* Web  > https://registry.platformio.org/search?q=header:SPI.h
*
*************************************************************

    7 |   #include <SPI.h>
      |            ^~~~~~~
compilation terminated.
*** [.pioenvs/stacja-pogody/lib353/RadioLib/Module.cpp.o] Error 1
In file included from .piolibdeps/stacja-pogody/RadioLib/src/modules/CC1101/CC1101.h:5,
                 from .piolibdeps/stacja-pogody/RadioLib/src/modules/CC1101/CC1101.cpp:1:
.piolibdeps/stacja-pogody/RadioLib/src/modules/CC1101/../../Module.h:7:12: fatal error: SPI.h: No such file or directory

*************************************************************
* Looking for SPI.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:SPI.h"
* Web  > https://registry.platformio.org/search?q=header:SPI.h
*
*************************************************************

    7 |   #include <SPI.h>
      |            ^~~~~~~
compilation terminated.
*** [.pioenvs/stacja-pogody/lib353/RadioLib/modules/CC1101/CC1101.cpp.o] Error 1
In file included from .piolibdeps/stacja-pogody/RadioLib/src/modules/LLCC68/LLCC68.h:8,
                 from .piolibdeps/stacja-pogody/RadioLib/src/modules/LLCC68/LLCC68.cpp:1:
.piolibdeps/stacja-pogody/RadioLib/src/modules/LLCC68/../../Module.h:7:12: fatal error: SPI.h: No such file or directory

*************************************************************
* Looking for SPI.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:SPI.h"
* Web  > https://registry.platformio.org/search?q=header:SPI.h
*
*************************************************************

    7 |   #include <SPI.h>
      |            ^~~~~~~
compilation terminated.
*** [.pioenvs/stacja-pogody/lib353/RadioLib/modules/LLCC68/LLCC68.cpp.o] Error 1
========================== [FAILED] Took 2.60 seconds ==========================
```

### Additional information

similar problem and solution in [#2911](https://github.com/esphome/issues/issues/2911) doesn't help
