### ISSUE TITLE
Modbus components slows down over time (and finally makes esphome go away)

### ISSUE THREAD

**Issue by henrykuijpers** [esphome/issues#5316]
### The problem

I'm running a Modbus readout on an ESP32 (wroom32 dev board), in combination with a MAX485 board (the one that has DI, RE, DE, RO).

Often see messages in the logs about operations taking a lot of time.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32

### Board

ESP32 

### Component causing the issue

wroom32 (nodemcu-32s)

### Example YAML snippet

```yaml
substitutions:
  name: modbus-esp
  friendly_name: Modbus

esphome:
  name: ${name}
  comment: ${friendly_name}
  platform: esp32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

  ap:
    ssid: $friendly_name Wifi
    password: !secret wifi_password
    
captive_portal:

logger:
  level: VERY_VERBOSE
  baud_rate: 0

api:

ota:

switch:
  - platform: restart
    name: ${friendly_name} Restart

web_server:
  port: 80

#serial port
uart:
  id: mod_uart
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1
      
modbus:
  flow_control_pin: 4
  send_wait_time: 500ms
  uart_id: mod_uart
  id: mod_bus

modbus_controller:
  - id: SDM120M
    modbus_id: mod_bus
    address: 1
    setup_priority: -10

sensor:
  # General
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} AvgFreq
    register_type: read
    address: 0x0046
    value_type: FP32
    unit_of_measurement: Hz
    state_class: "measurement"
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Total System Power
    register_type: read
    address: 0x0034
    value_type: FP32
    unit_of_measurement: W
    state_class: "measurement"
    device_class: "power"
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Total Active Energy
    register_type: read
    address: 0x0156
    value_type: FP32
    unit_of_measurement: kWh
    state_class: "total_increasing"
    device_class: "energy"
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Average Line to Neutral Voltage
    register_type: read
    address: 0x002A
    value_type: FP32
    unit_of_measurement: V
    state_class: "measurement"
    device_class: "voltage"
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Average Line Current
    register_type: read
    address: 0x002E
    value_type: FP32
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: A
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Sum Line Current
    register_type: read
    address: 0x0030
    value_type: FP32
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: A
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Total System Power
    register_type: read
    address: 0x0034
    value_type: FP32
    unit_of_measurement: W
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Total System VA
    register_type: read
    address: 0x0038
    value_type: FP32
    device_class: ""
    state_class: "measurement"
    unit_of_measurement: VA
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Total System VAr
    register_type: read
    address: 0x003C
    value_type: FP32
    device_class: ""
    state_class: "measurement"
    unit_of_measurement: VAr
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Total System Power Factor
    register_type: read
    address: 0x003E
    value_type: FP32
    device_class: "power_factor"
    state_class: "measurement"
    unit_of_measurement: ""
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Import Active Energy
    register_type: read
    address: 0x0048
    value_type: FP32
    unit_of_measurement: kWh
    state_class: "total_increasing"
    device_class: "energy"
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Export Active Energy
    register_type: read
    address: 0x004A
    value_type: FP32
    unit_of_measurement: kWh
    state_class: "total_increasing"
    device_class: "energy"
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Neutral Current
    register_type: read
    address: 0x00E0
    value_type: FP32
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: A
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Total Reactive Energy
    register_type: read
    address: 0x0158
    value_type: FP32
    unit_of_measurement: kVArh
    state_class: "total_increasing"
    device_class: "energy"
    accuracy_decimals: 3

  # Power
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 1 Power
    register_type: read
    address: 0x000C
    value_type: FP32
    unit_of_measurement: W
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 3
    
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 2 Power
    register_type: read
    address: 0x000E
    value_type: FP32
    unit_of_measurement: W
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 3
    
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 3 Power
    register_type: read
    address: 0x0010
    value_type: FP32
    unit_of_measurement: W
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 3
    
  # Volts
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 1 Voltage
    register_type: read
    address: 0x0000
    value_type: FP32
    unit_of_measurement: V
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 3
    
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 2 Voltage
    register_type: read
    address: 0x0002
    value_type: FP32
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: V
    accuracy_decimals: 3
    
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 3 Voltage
    register_type: read
    address: 0x0004
    value_type: FP32
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: V
    accuracy_decimals: 3
    
  # Current
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 1 Current
    register_type: read
    address: 0x0006
    value_type: FP32
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: A
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 2 Current
    register_type: read
    address: 0x0008
    value_type: FP32
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: A
    accuracy_decimals: 3
    
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 3 Current
    register_type: read
    address: 0x00A0
    value_type: FP32
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: A
    accuracy_decimals: 3
    
  # Apparent Power
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 1 Apparent Power
    register_type: read
    address: 0x0012
    value_type: FP32
    device_class: ""
    state_class: "measurement"
    unit_of_measurement: VA
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 2 Apparent Power
    register_type: read
    address: 0x0014
    value_type: FP32
    device_class: ""
    state_class: "measurement"
    unit_of_measurement: VA
    accuracy_decimals: 3
    
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 3 Apparent Power
    register_type: read
    address: 0x0016
    value_type: FP32
    device_class: ""
    state_class: "measurement"
    unit_of_measurement: VA
    accuracy_decimals: 3
    
  # Reactive Power
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 1 Reactive Power
    register_type: read
    address: 0x0018
    value_type: FP32
    device_class: ""
    state_class: "measurement"
    unit_of_measurement: VAr
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 2 Reactive Power
    register_type: read
    address: 0x001A
    value_type: FP32
    device_class: ""
    state_class: "measurement"
    unit_of_measurement: VAr
    accuracy_decimals: 3
    
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 3 Reactive Power
    register_type: read
    address: 0x001C
    value_type: FP32
    device_class: ""
    state_class: "measurement"
    unit_of_measurement: VAr
    accuracy_decimals: 3
    
  # Power Factor
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 1 Power Factor
    register_type: read
    address: 0x001E
    value_type: FP32
    device_class: "power_factor"
    state_class: "measurement"
    unit_of_measurement: ""
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 2 Power Factor
    register_type: read
    address: 0x0020
    value_type: FP32
    device_class: "power_factor"
    state_class: "measurement"
    unit_of_measurement: ""
    accuracy_decimals: 3
    
  - platform: modbus_controller
    modbus_controller_id: SDM120M
    name: ${friendly_name} Phase 3 Power Factor
    register_type: read
    address: 0x0022
    value_type: FP32
    device_class: "power_factor"
    state_class: "measurement"
    unit_of_measurement: ""
    accuracy_decimals: 3
```

### Anything in the logs that might be useful for us?

```txt
16:02:11 | [W] | [component:214] | Component modbus took a long time for an operation (0.05 s).

(The message is apparently a feature, and it's fine that it takes a bit of time to process everything.)

After a while it starts increasing to 0.10 s, 0.20 s, ... And then suddenly it goes offline. ESP32 is still turned on (LEDs still burning), but the web interface is gone and there is no way to interact with it.
```
