### ISSUE TITLE
Analog threshold binary sensor cannot reliably publish initial state

### ISSUE THREAD

**Issue by agoode** [esphome/issues#5325]
### The problem

In `setup()`, there is a call to `this->sensor_->get_state();`. It is later checked for NaN, and if true, then the initial value is published as `FALSE`.

Code:
https://github.com/esphome/esphome/blob/773cd0f414bf917d150606b2b7b0166d60d98563/esphome/components/analog_threshold/analog_threshold_binary_sensor.cpp#L10

Because only `binary_sensor` implements `publish_initial_state()` (it is not implemented by `sensor`), the value read during `setup()` is almost always going to be NaN. Later, upon the first `update()`, the first real value is collected from the sensor and the state is for the first time valid.

This results in spurious triggers (exactly what `publish_initial_state()` is meant to avoid).

What do you think about not publishing the initial state from `setup()` but instead doing so the first time the underlying sensor has a value? This will avoid the spurious triggers and is a reasonable way to do this kind of threshold given that `sensor` won't have a valid state in `setup()`.

As an alternative, we could implement something like `publish_initial_state()` for `sensor`, but that is a huge project.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.4

### What platform are you using?

ESP32-IDF

### Component causing the issue

analog_threshold

### Example YAML snippet

```yaml
esphome:
  name: water-meter
  friendly_name: Water meter

esp32:
  board: adafruit_qtpy_esp32s2
  framework:
    type: esp-idf
    platform_version: 6.4.0
    version: 5.1.2
    sdkconfig_options:
      CONFIG_ESP_CONSOLE_USB_CDC: n

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - globals.set:
              id: pulse_count
              value: '0'

globals:
  - id: pulse_count
    type: int

i2c:
  sda: 41
  scl: 40
  scan: true
  frequency: 400kHz

sensor:
  - platform: mmc5983
    field_strength_z:
      id: magnet_z
    update_interval: 50ms

  - platform: copy
    source_id: magnet_z
    name: "Magnetic field strength"
    filters:
      - throttle: 1s
    entity_category: DIAGNOSTIC

  - platform: template
    id: total_daily_water
    name: "Total daily water consumption"
    unit_of_measurement: gal
    device_class: water
    state_class: total_increasing
    accuracy_decimals: 3
    update_interval: 1s
    lambda: "return id(pulse_count) / 64.0;"

binary_sensor:
  - platform: analog_threshold
    id: magnet_threshold
    sensor_id: magnet_z
    threshold:
      lower: -0.0137
      upper: 0.0063
    on_state:
      then:
        - lambda: "id(pulse_count)++;"

# Enable logging
logger:

# Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
