### ISSUE TITLE
As a continuation of the #3761

### ISSUE THREAD

**Issue by Opontios** [esphome/issues#5330]
> I'm going to close this one since we have multiple reports of everything working correctly with Yale and August locks with the latest ESPHome. I also have migrated 29 Yale locks to be serviced by ESPHome Bluetooth proxies now without any issues for a few months.

Greetings!
I've thoroughly red the post and still have this issue with the mentioned above error. My setup is HASS OS with latest core and ESPHOME, and I use a m5stack Atom Echo for a proxy. The lock/unlock commands are executed almost instantaneously, but the state of the door sensor is not updated if you open the door manually, I guess because of the disconnection, or is this the normal behavior  for the particular setup? My lock is Yale Linus Smart lock.
[logs_atom-bluetooth-proxy-827a08_run.txt](https://github.com/esphome/issues/files/13810889/logs_atom-bluetooth-proxy-827a08_run.txt)
```
substitutions:
  name: atom-bluetooth-proxy-827a08
  friendly_name: Bluetooth Proxy

packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/m5stack-atom-lite.yaml@main

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

api:
  encryption:
    key: ---------------------------------

logger:
ota:
improv_serial:

dashboard_import:
  package_import_url: github://esphome/firmware/bluetooth-proxy/m5stack-atom-lite.yaml@main

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: false

bluetooth_proxy:
  active: true

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic
```

_Originally posted by @Opontios in https://github.com/esphome/issues/issues/3761#issuecomment-1874100685_
