### ISSUE TITLE
ESPHome 2023.12.5 linking error for ESP32

### ISSUE THREAD

**Issue by u17194907425** [esphome/issues#5331]
### The problem

Compile minimal firmware and in the end see this:

```
Linking .pioenvs/compile-bug/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: BFD (crosstool-NG esp-2021r2-patch5) 2.35.1.20201223 assertion fail /builds/idf/crosstool-NG/.build/xtensa-esp32-elf/src/binutils/bfd/elf32-xtensa.c:9102
/data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/lib/no-rtti/libc.a(lib_a-svfiprintf.o): in function `_svfiprintf_r':
/builds/idf/crosstool-NG/.build/xtensa-esp32-elf/src/newlib/newlib/libc/stdio/vfprintf.c:1401:(.text+0x1138): dangerous relocation: ufloat.s: cannot encode: .literal
collect2: error: ld returned 1 exit status
*** [.pioenvs/compile-bug/firmware.elf] Error 1
```

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.1

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Example YAML snippet

```yaml
esphome:
  name: compile-bug
  friendly_name: compile-bug

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fr0pC00dwsi9Fue64hrTMCYcTuHIen/QjiN90FqehO8="

ota:
  password: "d7e02135ec424428ca757f193293556c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
