### ISSUE TITLE
Variable x unknown with on_stt_end with assist

### ISSUE THREAD

**Issue by dflvunoooooo** [esphome/issues#5334]
### The problem

If I add the option `on_stt_end` to the voice_assistant component and try to check the response, I get the error `Couldn't find ID 'x'. Please check you have defined an ID with that name in your configuration`. The response should, according to the manual, be "available to automations as the variable x" [link](https://esphome.io/components/voice_assistant.html#voice-assistant). 

### Which version of ESPHome has the issue?

12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.0

### What platform are you using?

ESP32

### Component causing the issue

voice_assistant

### Example YAML snippet

```yaml
…
  on_stt_end:
    then:
      - if:
          condition:
            - lambda: |-
                return id(x).state == 'Entschuldigung, das habe ich nicht verstanden';
          then:
            - light.turn_on:
 …
```

### Anything in the logs that might be useful for us?

```txt
on_stt_end: 
    then: 
      - if: 
          condition: 
            and: 
              - 
                Couldn't find ID 'x'. Please check you have defined an ID with that name in your configuration.
```
