### ISSUE TITLE
CAN bus doesn't work on ESP32S3 when GPIO19 & GPIO20 are used as RX, TX

### ISSUE THREAD

**Issue by strange-v** [esphome/issues#5335]
### The problem

When the CAN bus is configured to use pins GPIO19 & GPIO20 as RX & TX - CAN communication doesn't work. The issue is that pins 19 and 20 are, by default, connected to the internal USB PHY and must be routed back to the GPIO matrix.

After adding
> gpio_hal_iomux_func_sel(GPIO_PIN_MUX_REG[19], PIN_FUNC_GPIO);
gpio_hal_iomux_func_sel(GPIO_PIN_MUX_REG[20], PIN_FUNC_GPIO);

everything works fine.

Probably, it is worth modifying the esp32_can component, so when the target is ESP32S3 and pins are 19 & 20, it applies the mentioned re-mappings. Alternatively, it might be done on a pin level. Sorry, I am not yet very familiar with the architecture of ESPHome, and it's hard to say precisely where the fix should be done.

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.12.0

### What platform are you using?

ESP32

### Board

esp32-s3-devkitc-1

### Component causing the issue

esp32_can

### Example YAML snippet

```yaml
button:
  - platform: template
    name: Test
    id: my_button
    on_press:
      then:
        - canbus.send:
            data: [ 0x01, 0x02, 0x03 ]

canbus:
  - platform: esp32_can
    tx_pin: GPIO20
    rx_pin: GPIO19
    can_id: 2
    bit_rate: 125kbps
    on_frame:
    - can_id: 4
      use_extended_id: false
      then:
      - lambda: |-
          std::string b(x.begin(), x.end());
          ESP_LOGD("can id 4", "%s", &b[0] );
```

### Additional information

SN65HVD234 CAN bus transceiver is used in those tests
