### ISSUE TITLE
Wemos D1 R2 cannot connect to WiFi & no fallback access point displayed

### ISSUE THREAD

**Issue by vdiogo** [esphome/issues#5336]
### The problem

I have a couple of wemos d1 r2 where I started by installing a custom yaml, and after multiple code adjustments attempting to get them connected to wifi first, and setting a fallout AP in case if of no connection, I decided to install the standard ESP8266 yaml, but got the same outcome: no connection to WiFi and no AP displayed

I have looked into all of the issues already open and couldn't find a similar one.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.0

### What platform are you using?

ESP8266

### Board

wemos d1 r2

### Component causing the issue

wifi

### Example YAML snippet

```yaml
esphome:
  name: visonicstd
  friendly_name: visonicstd

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ENsZ3rcnM2B6R0yWn4TV3mnTANmAATnN7A+ZS6DTaMM="

ota:
  password: "f9ae8f671484fa1c0362daef4321a452"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Visonicstd Fallback Hotspot"
    password: "5HRTlICXBqxo"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/visonicstd.yaml...
INFO Starting log output from visonicstd.local using esphome API
WARNING Can't connect to ESPHome API for visonicstd.local: Error resolving IP address: [Errno -5] No address associated with hostname (APIConnectionError)
INFO Trying to connect to visonicstd.local in the background
```
