### ISSUE TITLE
deep_sleep <-> binary_sensor.gpio: Collission when same gpio is used twice

### ISSUE THREAD

**Issue by webcharlyx** [esphome/issues#5340]
### The problem

2023.10.1 was compiling properly and working fine with this config.
After update to 2023.12.5 compiling is now no longer possible.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

deep_sleep, binary_sensor.gpio

### Example YAML snippet

```yaml
binary_sensor:
  - platform: gpio
    pin: 15
    name: "PIR_Sensor"
    device_class: motion
    filters:
      - delayed_on: 500ms
      - delayed_off: 1s
    #(re-)start the 5min countdown for deepsleep-begin:
    on_press:
      then:
        - script.stop: countdown_5min
        - script.execute: countdown_5min

deep_sleep:
#### TODO: fix the sleep-wake-loop when OTA was set OFF again
  id: deep_sleep_1
  wakeup_pin_mode: INVERT_WAKEUP   # weather IGNORE (default) nor INVERT_WAKEUP prevented the sleep-wake-loop when OTA was set OFF again
  #run_duration: 300s
  sleep_duration: 60min
# Using this new feature to wake on any of the Pins going HIGH
  esp32_ext1_wakeup:
    pins:
      # for IR wakeup use
      - 15
    mode: ANY_HIGH
```

### Anything in the logs that might be useful for us?

```txt
esphome> esphome compile .\keypanel.yaml
INFO ESPHome 2023.12.5
INFO Reading configuration .\keypanel.yaml...
WARNING GPIO15 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO12 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO15 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

binary_sensor.gpio: [source <unicode string>:254]

  Pin 15 is used in multiple places.
  platform: gpio
  pin:
    number: 15
    mode:
      input: True
      output: False
      open_drain: False
      pullup: False
      pulldown: False
    inverted: False
    ignore_strapping_warning: False
    drive_strength: 20.0
  name: PIR_Sensor
  device_class: motion
  filters:
    - delayed_on: 500ms
    - delayed_off: 1s
  on_press:
    - then:
        - script.stop:
            id: countdown_5min
        - script.execute:
            id: countdown_5min
  disabled_by_default: False
deep_sleep: [source <unicode string>:793]

  Pin 15 is used in multiple places.
  id: deep_sleep_1
  wakeup_pin_mode: INVERT_WAKEUP
  sleep_duration: 60min
  esp32_ext1_wakeup:
    pins:
      - number: 15
        mode:
          input: True
          output: False
          open_drain: False
          pullup: False
          pulldown: False
        inverted: False
        ignore_strapping_warning: False
        drive_strength: 20.0
    mode: ANY_HIGH
```
