### ISSUE TITLE
MCP23017 Switch config order

### ISSUE THREAD

**Issue by alexyao2015** [esphome/issues#535]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP12-E

**Affected component:**

MCP23017
https://esphome.io/components/mcp23017.html

**Description of problem:**
Output switch is required to be after the mcp23017 configuration entry. There is no indication of this in the docs that this was intentional. 

YAMLs were copied directly from the docs but the only difference is the order where switch is in the config.

Please fix it to allow it in any order or add this detail to the docs.

**Problem-relevant YAML-configuration entries:**
```yaml
WORKING:
mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20

# Individual outputs
switch:
  - platform: gpio
    name: "MCP23017 Pin #0"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 0
      number: 0
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
      inverted: False







NOT WORKING:
# Individual outputs
switch:
  - platform: gpio
    name: "MCP23017 Pin #0"
    pin:
      mcp23017: mcp23017_hub
      # Use pin number 0
      number: 0
      # One of INPUT, INPUT_PULLUP or OUTPUT
      mode: OUTPUT
      inverted: False

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
