### ISSUE TITLE
ESPHome Thermostat should have a single setpoint  for when auto is not used. 

### ISSUE THREAD

**Issue by towerclimber87** [esphome/issues#5352]
### The problem

ESPHome Thermostat should have a single setpoint  for when auto is not used.   example. I want the temp to be set to 70 and i have mode set to Cool. then cool room to 70, when Heat is selected, heat room to 70.  with the curent setup. Amazon Alexa is not able to change the set temp.  Home Assistant has a generic thermostat that works well and has a single setpoint.  for those that dont want manual. 

### Which version of ESPHome has the issue?

Current version: 2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.2

### What platform are you using?

ESP32

### Board

Wemos D1 Mini ESP32

### Component causing the issue

Cliamte

### Example YAML snippet

```yaml
climate:
  - platform: thermostat
    name: "Livingroom Thermostat"
    id: climate_thermostat
    sensor: livingroom_temp_onboard_1
    min_heating_off_time: 30s
    min_heating_run_time: 30s
    min_cooling_off_time: 30s
    min_cooling_run_time: 30s    
    set_point_minimum_differential: 0
    min_idle_time: 30s
    cool_action:
      - switch.turn_on: ac_relay
      - switch.turn_off: heater_relay
      - homeassistant.service:
          service: input_boolean.turn_off
          data_template:
             entity_id: input_boolean.livingroom_heat_trigger
      - homeassistant.service:
          service: input_boolean.turn_on
          data_template:
             entity_id: input_boolean.livingroom_ac_trgger
    heat_action:
      - switch.turn_on: heater_relay
      - switch.turn_off: ac_relay
      - homeassistant.service:
          service: input_boolean.turn_on
          data_template:
             entity_id: input_boolean.livingroom_heat_trigger
      - homeassistant.service:
          service: input_boolean.turn_off
          data_template:
             entity_id: input_boolean.livingroom_ac_trgger
    idle_action:
      - switch.turn_off: ac_relay
      - switch.turn_off: heater_relay
      - homeassistant.service:
          service: input_boolean.turn_off
          data_template:
             entity_id: input_boolean.livingroom_heat_trigger
      - homeassistant.service:
          service: input_boolean.turn_off
          data_template:
             entity_id: input_boolean.livingroom_ac_trgger
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 70 °F
        default_target_temperature_high: 70 °F        
    visual:
      min_temperature: 18.89
      max_temperature: 25
      temperature_step: 1
```

### Anything in the logs that might be useful for us?

```txt
This is the HA that works well. 
  - platform: dualmode_generic
    name: Bedroom Thermostat
    heater: input_boolean.bedroom_heat_trgger
    cooler: input_boolean.bedroom_ac_trgger
    target_sensor: sensor.h5075_23cd_temperature
    min_temp: 63
    max_temp: 78
    target_temp: 68
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      minutes: 1
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    away_temp: 63
    precision: 1.0
```
