### ISSUE TITLE
YAML file name missing from config error messages

### ISSUE THREAD

**Issue by marshn** [esphome/issues#5354]
### The problem

In build error messages the yaml file name has been replaced by "\<unicode string\>".

An error in the yaml, like this one:
```
binary_sensor:
  - platform: gpio
    asdf: asdf
    pin: 
      number: GPIO0 
```

v2023.12.5 outputs an error message like this:
```
Failed config

binary_sensor.gpio: [source <unicode string>:484]
  platform: gpio

  [asdf] is an invalid option for [binary_sensor.gpio]. Please check the indentation.
  pin:
    number: GPIO0
```

2023.11.6 and earlier versions produced an error message like this:
```
Failed config

binary_sensor.gpio: [source Fused_Spur-ESP32.yaml:484]
  platform: gpio

  [asdf] is an invalid option for [binary_sensor.gpio]. Please check the indentation.
  asdf: asdf
  pin:
    number: GPIO0
```

Edit: I have just noticed that this issue is very similar to https://github.com/esphome/issues/issues/5310

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32-IDF

### Board

esp32 

### Example YAML snippet

```yaml
binary_sensor:
  - platform: gpio
    asdf: asdf
    pin: 
      number: GPIO0
```

### Anything in the logs that might be useful for us?

```txt
Failed config

binary_sensor.gpio: [source <unicode string>:484]
  platform: gpio

  [asdf] is an invalid option for [binary_sensor.gpio]. Please check the indentation.
  pin:
    number: GPIO0
```
