### ISSUE TITLE
ENS160 requires one hour warmup each boot (should be 3min)

### ISSUE THREAD

**Issue by jxmesw1** [esphome/issues#5355]
### The problem

[According to the docs](https://esphome.io/components/sensor/ens160.html), the ENS160 eCO2/tVOC sensor requires a one-hour warmup the _very first time_ it's powered up. For subsequent boots or restarts, it's three minutes before readings are available. 
However, I'm experiencing an issue whereby I have to wait a full hour for readings every time I reboot my ESP. This should be three minutes rather than an hour.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.2

### What platform are you using?

ESP8266

### Board

NodeMCU

### Component causing the issue

ENS160

### Example YAML snippet

```yaml
- platform: ens160
    eco2:
      name: "Lounge eCO2"
    tvoc:
      name: "Lounge TotalVOC"
    aqi:
      name: "Lounge AQI"
    update_interval: 30s
    address: 0x53
    compensation:
      temperature: "lounge_temp"
      humidity: "lounge_humi"
```

### Anything in the logs that might be useful for us?

```txt
[14:26:08][VV][i2c.arduino:141]: 0x53 TX 20
[14:26:08][VV][i2c.arduino:117]: 0x53 RX 8B
[14:26:08][V][ens160:156]: Status: ENS160 STATAS bit    0x1
[14:26:08][V][ens160:158]: Status: ENS160 STATER bit    0x0
[14:26:08][V][ens160:160]: Status: ENS160 VALIDITY FLAG 0x02
[14:26:08][V][ens160:161]: Status: ENS160 NEWDAT bit    0x1
[14:26:08][V][ens160:163]: Status: ENS160 NEWGPR bit    0x1
```

### Additional information

I sometimes see a message in the log saying something along the lines of "One hour warmup required..." although this is not always the case. I think this depends on when I look at the log, e.g. as soon as the ESP has booted
