### ISSUE TITLE
The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h

### ISSUE THREAD

**Issue by riverscn** [esphome/issues#5357]
### The problem

driver/rmt.h is deprecated.
Should use driver/rmt_tx.h and/or driver/rmt_rx.h instead.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

m5stack-atoms3

### Component causing the issue

esp32_rmt_led_strip

### Example YAML snippet

```yaml
light:
  - platform: esp32_rmt_led_strip
    name: "Indicator"
    id: "indicator"
    rgb_order: GRB
    pin: GPIO35
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
```

### Anything in the logs that might be useful for us?

```txt
In file included from src/esphome/components/esp32_rmt_led_strip/led_strip.h:12,
                 from src/esphome.h:22,
                 from src/main.cpp:3:
/config/.esphome/platformio/packages/framework-espidf/components/driver/deprecated/driver/rmt.h:18:2: warning: #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h" [-Wcpp]
   18 | #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"
```
