### ISSUE TITLE
fastled_clockless won't compile, ESP32, ESPhome version 2023.12.5

### ISSUE THREAD

**Issue by psitech** [esphome/issues#5364]
### The problem

A fastled_clockless sketch won't compile without errors.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2024.1.2

### What platform are you using?

ESP32

### Board

ESP32-C3 Supermini

### Component causing the issue

light

### Example YAML snippet

```yaml
esphome:
  name: rgbledstrip
  friendly_name: RGB LED strip

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "boFycI7HZ13/b0buThFBC2nrYHQ/upyh/eJeR2d4Xkc="

ota:
  password: "d215d40850361e4bdd3ba49dfdcc7d3c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# ---------- this compiles fine ----------------------
# light:
#  - platform: neopixelbus
#    type: GRB
#    variant: WS2812
#    pin: GPIO6
#    num_leds: 144
#    name: "LED strip"
#    default_transition_length: '0s'
#    effects:
#      - addressable_rainbow:
#          name: Rainbow
#          speed: 10
#          width: 144   
         
# ---------- FastLED won't compile without errors ----------------------
light:
 - platform: fastled_clockless
   chipset: WS2812
   pin: GPIO6
   num_leds: 144
   rgb_order: BRG
   name: "LED strip"
   default_transition_length: '0s'
   effects:
     - addressable_rainbow:
         name: Rainbow
         speed: 10
         width: 144
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/rgb-led-strip.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing rgbledstrip (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Removing unused dependencies...
Library Manager: Removing NeoPixelBus @ 2.7.3
INFO Removing NeoPixelBus @ 2.7.3
Library Manager: Removing dependencies...
INFO Removing dependencies...
Library Manager: NeoPixelBus@2.7.3 has been removed!
INFO NeoPixelBus@2.7.3 has been removed!
Library Manager: Installing fastled/FastLED @ 3.3.2
INFO Installing fastled/FastLED @ 3.3.2
Unpacking  [####################################]  100%
Library Manager: FastLED@3.3.2 has been installed!
INFO FastLED@3.3.2 has been installed!
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.0.1
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|-- ArduinoJson @ 6.18.5
|-- FastLED @ 3.3.2
Compiling .pioenvs/rgbledstrip/libb07/FastLED/FastLED.cpp.o
Compiling .pioenvs/rgbledstrip/libb07/FastLED/bitswap.cpp.o
Compiling .pioenvs/rgbledstrip/libb07/FastLED/colorpalettes.cpp.o
Compiling .pioenvs/rgbledstrip/libb07/FastLED/colorutils.cpp.o
In file included from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/clockless_rmt_esp32.h:95,
                 from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from .piolibdeps/rgbledstrip/FastLED/platforms.h:36,
                 from .piolibdeps/rgbledstrip/FastLED/FastLED.h:52,
                 from .piolibdeps/rgbledstrip/FastLED/FastLED.cpp:2:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/esp_hw_support/include/esp_intr.h:8:2: warning: #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead [-Wcpp]
 #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead
  ^~~~~~~
In file included from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/clockless_rmt_esp32.h:95,
                 from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from .piolibdeps/rgbledstrip/FastLED/platforms.h:36,
                 from .piolibdeps/rgbledstrip/FastLED/FastLED.h:52,
                 from .piolibdeps/rgbledstrip/FastLED/bitswap.cpp:2:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/esp_hw_support/include/esp_intr.h:8:2: warning: #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead [-Wcpp]
 #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead
  ^~~~~~~
In file included from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/clockless_rmt_esp32.h:95,
                 from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from .piolibdeps/rgbledstrip/FastLED/platforms.h:36,
                 from .piolibdeps/rgbledstrip/FastLED/FastLED.h:52,
                 from .piolibdeps/rgbledstrip/FastLED/colorpalettes.cpp:4:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/esp_hw_support/include/esp_intr.h:8:2: warning: #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead [-Wcpp]
 #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead
  ^~~~~~~
In file included from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/clockless_rmt_esp32.h:95,
                 from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from .piolibdeps/rgbledstrip/FastLED/platforms.h:36,
                 from .piolibdeps/rgbledstrip/FastLED/FastLED.h:52,
                 from .piolibdeps/rgbledstrip/FastLED/colorutils.cpp:7:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/esp_hw_support/include/esp_intr.h:8:2: warning: #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead [-Wcpp]
 #warning esp_intr.h is deprecated, please include esp_intr_alloc.h instead
  ^~~~~~~
In file included from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastled_esp32.h:3,
                 from .piolibdeps/rgbledstrip/FastLED/platforms.h:36,
                 from .piolibdeps/rgbledstrip/FastLED/FastLED.h:52,
                 from .piolibdeps/rgbledstrip/FastLED/FastLED.cpp:2:
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h: In static member function 'static void _ESPPIN<PIN, MASK>::hi()':
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h:16:17: error: 'gpio_dev_t' {aka 'volatile struct gpio_dev_s'} has no member named 'out1_w1ts'; did you mean 'out_w1ts'?
       else GPIO.out1_w1ts.val = MASK;
                 ^~~~~~~~~
                 out_w1ts
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h: In static member function 'static void _ESPPIN<PIN, MASK>::lo()':
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h:21:17: error: 'gpio_dev_t' {aka 'volatile struct gpio_dev_s'} has no member named 'out1_w1tc'; did you mean 'out_w1tc'?
       else GPIO.out1_w1tc.val = MASK;
                 ^~~~~~~~~
                 out_w1tc
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h: In static member function 'static void _ESPPIN<PIN, MASK>::set(_ESPPIN<PIN, MASK>::port_t)':
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h:26:17: error: 'gpio_dev_t' {aka 'volatile struct gpio_dev_s'} has no member named 'out1'; did you mean 'out'?
       else GPIO.out1.val = val;
                 ^~~~
                 out
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h: In static member function 'static void _ESPPIN<PIN, MASK>::toggle()':
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h:32:31: error: no match for 'operator^=' (operand types are 'volatile gpio_dev_s::<unnamed union>' and 'long unsigned int')
       if(PIN < 32) { GPIO.out ^= MASK; }
                      ~~~~~~~~~^~~~~~~

< stuff deleted >

In file included from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from .piolibdeps/rgbledstrip/FastLED/platforms.h:36,
                 from .piolibdeps/rgbledstrip/FastLED/FastLED.h:52,
                 from .piolibdeps/rgbledstrip/FastLED/colorutils.cpp:7:
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/clockless_rmt_esp32.h: In member function 'void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::startOnChannel(int)':
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/clockless_rmt_esp32.h:399:52: warning: 'esp_err_t rmt_set_pin(rmt_channel_t, rmt_mode_t, gpio_num_t)' is deprecated: use rmt_set_gpio instead [-Wdeprecated-declarations]
         rmt_set_pin(mRMT_channel, RMT_MODE_TX, mPin);
                                                    ^
In file included from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/clockless_rmt_esp32.h:97,
                 from .piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastled_esp32.h:8,
                 from .piolibdeps/rgbledstrip/FastLED/platforms.h:36,
                 from .piolibdeps/rgbledstrip/FastLED/FastLED.h:52,
                 from .piolibdeps/rgbledstrip/FastLED/colorutils.cpp:7:
/data/cache/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/driver/include/driver/rmt.h:930:11: note: declared here
 esp_err_t rmt_set_pin(rmt_channel_t channel, rmt_mode_t mode, gpio_num_t gpio_num)
           ^~~~~~~~~~~
*** [.pioenvs/rgbledstrip/libb07/FastLED/colorutils.cpp.o] Error 1
========================= [FAILED] Took 15.85 seconds =========================
```

### Additional information

Compile errors from log above:
.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h:16:17: error: 'gpio_dev_t' {aka 'volatile struct gpio_dev_s'} has no member named 'out1_w1ts'; did you mean 'out_w1ts'?

.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h:21:17: error: 'gpio_dev_t' {aka 'volatile struct gpio_dev_s'} has no member named 'out1_w1tc'; did you mean 'out_w1tc'?

.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h:26:17: error: 'gpio_dev_t' {aka 'volatile struct gpio_dev_s'} has no member named 'out1'; did you mean 'out'?

.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h:32:31: error: no match for 'operator^=' (operand types are 'volatile gpio_dev_s::<unnamed union>' and 'long unsigned int')

.piolibdeps/rgbledstrip/FastLED/platforms/esp/32/fastpin_esp32.h:51:34: error: cannot convert 'volatile gpio_dev_s::<unnamed union>*' to '_ESPPIN<PIN, MASK>::port_ptr_t' {aka 'volatile long unsigned int*'} in return

**Comment by ssieb** [comment]
It needs a newer fastled library.  There are already issues open for this.  But you should use the RMT component anyway.

**Comment by psitech** [comment]
Thanks for your reply. A newer FastLED lib seems obvious.
Wasn't aware of using the RMT component as preferred - I will look into that.

**Comment by psitech** [comment]
RMT component works fine.
For reference here is the working code:

```
esphome:
  name: rgbledstrip
  friendly_name: RGB LED strip

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "boFycI7HZ13/b0buThFBC2nrYHQ/upyh/eJeR2d4Xkc="

ota:
  password: "d215d40850361e4bdd3ba49dfdcc7d3c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO6
    num_leds: 144
    rmt_channel: 0
    chipset: ws2812
    name: "LED strip"
    effects:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 144
```
