### ISSUE TITLE
WaveShare 4.20 V2 not displaying

### ISSUE THREAD

**Issue by RacoJo** [esphome/issues#5369]
### The problem

Hello,
I wanted to know is someone achieve to display from a 4.20in V2 (it's writtent v2 in a sticker on the back and rev2.2).

Because it's working well when I upload an example from WaveShare with arduino IDE, but not with esphome.

Is this because 4.20in-bv2 is not my version ? I tried :  

4.20in-bv2 
4.20in-bv2 with busy inverted : true
4.20in
4.20in with busy inverted : true

So many different pins configuration also, but it's not working...

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12

### What platform are you using?

ESP8266

### Board

d1 mini

### Example YAML snippet

```yaml
'''
esphome:
  name: einktest
  friendly_name: einktest

esp8266:
  board: d1_mini


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: 

ota:
  password: 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dashboard-Eink1 Fallback Hotspot"
    password: 

captive_portal:

spi:
  clk_pin: D5
  mosi_pin: D7

display:
  - platform: waveshare_epaper
    cs_pin: D8
    dc_pin: D3
    update_interval: 00s
    busy_pin: 
      number: D2
      inverted: true
    reset_pin: D4
    model: 4.20in
    reset_duration: 2ms
    lambda: |-
      it.rectangle(140,0,140,150);
'''
```
