### ISSUE TITLE
Multiple instances of DSMR fails if sensors are not equal

### ISSUE THREAD

**Issue by jeroen85** [esphome/issues#5372]
### The problem

I have two P1 meters connected to a ESP32-C3.
It appears this only works correctly if the sensor list for both instances are equal.

As soon as the defined sensors for each instance deviate from each other, the system will not compile.

It will generate a lot of warnings about a redefined sensor list
```
In file included from src/esphome/core/util.cpp:2:
src/esphome/core/defines.h:4: warning: "DSMR_SENSOR_LIST" redefined
 #define DSMR_SENSOR_LIST(F, sep) F(energy_delivered_tariff1) sep F(power_delivered)
 
src/esphome/core/defines.h:3: note: this is the location of the previous definition
 #define DSMR_SENSOR_LIST(F, sep) F(energy_delivered_tariff1) sep F(energy_delivered_tariff2)
```

to stop with an error
```
Compiling .pioenvs/meterkast-new/lib13d/WiFi/WiFiAP.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:663:14: error: 'class esphome::dsmr::Dsmr' has no member named 'set_energy_delivered_tariff2'; did you mean 'set_energy_delivered_tariff1'?
   dsmr_p1_1->set_energy_delivered_tariff2(sensor_sensor_3);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
              set_energy_delivered_tariff1
Compiling .pioenvs/meterkast-new/lib13d/WiFi/WiFiClient.cpp.o
*** [.pioenvs/meterkast-new/src/main.cpp.o] Error 1
```

If both sensor lists are equal, it compiles without any issue.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Component causing the issue

dsmr

### Example YAML snippet

```yaml
uart:
#DSMR P1-meter    
- rx_pin: GPIO7
  baud_rate: 115200
  id: uart_dsmr_p1_1

- rx_pin: GPIO3
  baud_rate: 115200
  id: uart_dsmr_p1_2


dsmr:
- id: dsmr_p1_1
  uart_id: uart_dsmr_p1_1
  request_interval: 5s
  request_pin: GPIO6

- id: dsmr_p1_2
  uart_id: uart_dsmr_p1_2
  request_interval: 5s
  request_pin: GPIO2


sensor:  
#DSMR P1 meter 1
- platform: dsmr
  dsmr_id: dsmr_p1_1
  energy_delivered_tariff1:
    name: "Energy Consumed Tariff 1"
  energy_delivered_tariff2:
    name: "Energy Consumed Tariff 2"

#DSMR P1 meter 2
- platform: dsmr
  dsmr_id: dsmr_p1_2
  energy_delivered_tariff1:
    name: "Energy Consumed Tariff 1"
  power_delivered:
    name: "Power Consumed"
    accuracy_decimals: 3
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/meterkast-new/src/main.cpp.o
In file included from src/esphome/components/api/api_frame_helper.h:7,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/defines.h:4: warning: "DSMR_SENSOR_LIST" redefined
 #define DSMR_SENSOR_LIST(F, sep) F(energy_delivered_tariff1) sep F(power_delivered)
 
src/esphome/core/defines.h:3: note: this is the location of the previous definition
 #define DSMR_SENSOR_LIST(F, sep) F(energy_delivered_tariff1) sep F(energy_delivered_tariff2)
 
Archiving .pioenvs/meterkast-new/lib03f/libAsyncTCP-esphome.a
Compiling .pioenvs/meterkast-new/lib13d/WiFi/WiFi.cpp.o
Compiling .pioenvs/meterkast-new/lib13d/WiFi/WiFiAP.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:663:14: error: 'class esphome::dsmr::Dsmr' has no member named 'set_energy_delivered_tariff2'; did you mean 'set_energy_delivered_tariff1'?
   dsmr_p1_1->set_energy_delivered_tariff2(sensor_sensor_3);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
              set_energy_delivered_tariff1
Compiling .pioenvs/meterkast-new/lib13d/WiFi/WiFiClient.cpp.o
*** [.pioenvs/meterkast-new/src/main.cpp.o] Error 1
========================= [FAILED] Took 12.76 seconds =========================
```

### Additional information

Related to
https://github.com/esphome/feature-requests/issues/2062
https://github.com/esphome/esphome/pull/4299
