### ISSUE TITLE
For condition not working

### ISSUE THREAD

**Issue by Pro-Control** [esphome/issues#5378]
### The problem

Hi 
When set For Condition to trigger an action when the condition was true for 10s not trigger  Relay in my case

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Example YAML snippet

```yaml
- platform: template
    name: "Source 1 Status"
    id: "Source_1_Status"
    on_value:
      then:
        - if:
            condition:
              for:
                time: 10s
                condition:
                  - text_sensor.state:
                      id: "Source_1_Status"
                      state: "Normal"
            then:
              - switch.turn_on: "Source_1_Relay"
```
