### ISSUE TITLE
data_template for homeassistant.event action must be explicitly defined as a lambda

### ISSUE THREAD

**Issue by Slalamander** [esphome/issues#5394]
### The problem

When using `data_template` and accompanying `variables` tag in the `homeassistant.event` action, the lambda code for the variables must be explicitly declared as a lambda (using `!lambda`). The provided example in the [api documentation](https://esphome.io/components/api#homeassistant-event-action) (which is for `homeassistant.service`) does not do this. 

In the yaml snippet, `brightness_inp` is defined in the explicit way, whereas `range_inp` is defined as shown in the documentation. In the additional information, `brightness` is set to the input value integer, whereas `range` is the lambda code as defined in the ESP config.

I'm not sure if this is a bug or an error in the documentation, however.

### Which version of ESPHome has the issue?

2023.12.6

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2024.1.2

### What platform are you using?

ESP32

### Board

az-delivery-devkit-v4

### Component causing the issue

api

### Example YAML snippet

```yaml
- homeassistant.event:
          event: esphome.led_panel_range_set
          data_template:
            brightness: '{{ brightness_inp }}'
            range: '{{ range_inp }}'
          variables:
            brightness_inp: !lambda 'return brightness_val;'
            range_inp: |-
              return id(led_strip_rgb_range).state;
```

### Additional information

The event data is returned in home assistant as:
```
event_type: esphome.led_panel_range_set
data:
  device_id: xxx
  brightness: 100
  range: return id(led_strip_rgb_range).state;
origin: LOCAL
time_fired: "xxx"
context:
  id: xxx
  parent_id: null
  user_id: null
```
