### ISSUE TITLE
LEDC set_level not working

### ISSUE THREAD

**Issue by legomind** [esphome/issues#54]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**Affected component:**

LEDC (https://esphome.io/components/output/ledc.html)

**Description of problem:**
The output component works just fine when the brightness is set in home assistant.
But when I use set_level as described here: (https://esphome.io/components/output/index.html#output-set-level-action), the brightness of the light does not change in home assistant.

I have tried both lamba and pure yaml methods, neither work.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: dht
    pin: 22
    model: DHT22
    update_interval: 10s
    temperature:
      name: 'Temperature'
      id: habitat_temp
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: '°F'
      on_value:
        - then:
          - lambda: !lambda |-
              ESP_LOGD("main", "%f => Recommended dim level %f", x, (x >= 100) ? 60.0 : 100.0);
              id(habitat_heatlamp).set_level((x >= 100) ? 0.5 : 1);
    humidity:
      name: 'Humidity'
      id: habitat_humid

output:
  - platform: ledc
    pin: 23
    frequency: 10khz
    id: habitat_heatlamp

light:
  - platform: monochromatic
    name: 'Heatlamp'
    output: habitat_heatlamp
    default_transition_length: 0s
    gamma_correct: 0
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
