### ISSUE TITLE
ESP 32 C 3 boards failing to boot after 2023.12.8 upgrade - M5stack C3 Stamp

### ISSUE THREAD

**Issue by dat12s** [esphome/issues#5409]
### The problem

No issues installing and updating ESP Home configurations to multiple ESP 32 C3 boards up to and including ESP Home 2023.12.7
Carried out ESP Home Upgrade to 2023.12.8 and then carried out "Upgrade All" for the devices (wirelessly) and noted that the first C3 to upgrade was not responding, Stopped the remaining upgrades and carried out checks on the failed unit.

Connected to the C3 via usb for the logs and noted that it was failing to boot, carried out a further installation starting with clean build files and again the C3 failed to boot after installation.
All Ic2 modules removed from board and installation repeated with the same result - C3 not booting.
Carried out the same installation (via usb) on a brand new C3 (M5stack C3 Stamp) and this unit also fails to boot.
I have cautiously carried out upgrades to 2023.12.8 on my remaining devices which are various ES32 devices and Rpi Pico with no issues being apparent currently.

I have restored the 2023.12.7 backup for ESP Home taken when ESP Home was upgrade to 2023.12.8  with no effect, no installation to any C3 will now boot, for the sake of completeness I the re upgraded ESP Home to 2023.12.8 with no change to the results – C3 not booting.

### Which version of ESPHome has the issue?

2023.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

HA Core 2024.1.4 / Supervisor  2023.12.1 / OS 11.4 / Frontend 20240104.0

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1 (M5Stack C3 Stamp)

### Component causing the issue

C3 Failing to Boot after 2023.12.8 update (download by USB directly connected to HA PC)

### Example YAML snippet

```yaml
esphome:
  name: enviromental
  friendly_name: Enviromental

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "JjMojvHBxwl8oKnoPedAI+ht0NpAg0WNRRLNiQkZCvg="

ota:
  password: "d5554dec615889138ec9ba8d4f147f24"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.0.166
    gateway: 192.168.0.1
    subnet: 255.255.255.0  


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "LbdRUBnSYcai"

captive_portal:
  
web_server:
  port: 80

i2c:
  sda: 7
  scl: 8
  scan: true
  id: bus_a

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO2
    num_leds: 1
    name: "Test_Led"
    id: led

sensor:

  - platform: wifi_signal
    name: "ESP32 C3 Test WiFi Signal"
    update_interval: 60s
    accuracy_decimals: 1

  - platform: bh1750
    name: "External Light Level"
    address: 0x23
    update_interval: 60s  
    id: light_lux 
   
  - platform: aht10
    variant: AHT20
    address: 0x38
    temperature:
      name: "External Temp"
      id: oat
      accuracy_decimals: 1  
    humidity:
      name: "External Hum"
      id: oah
      accuracy_decimals: 1 
    update_interval: 60s 

  - platform: absolute_humidity
    name: Absolute Humidity
    temperature: oat
    humidity: oah

  - platform: ms5611
    temperature:
      name: "Enclosure Temperature"
      id: etemp
    pressure:
      name: "Barametric Pressure"
      id: bpressure
    address: 0x77
    update_interval: 60s

  - platform: template
    name: "Dew Point"
    lambda: |-
      return (243.5*(log(id(oah).state/100)+((17.67*id(oat).state)/
      (243.5+id(oat).state)))/(17.67-log(id(oah).state/100)-
      ((17.67*id(oat).state)/(243.5+id(oat).state))));
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'  

switch:
  - platform: gpio
    pin: 6
    inverted: false
    name: "Relay #1"
    id: relay1

  - platform: gpio
    pin: 5
    inverted: false
    name: "Relay #2"
    id: relay2

  - platform: gpio
    pin: 4
    inverted: false
    name: "Relay #3"
    id: relay3

binary_sensor:

  - platform: gpio
    pin:
      number: 3
      inverted: true 
      mode:
        input: true
        pullup: true

    name: "Relay Toggle"
    id: toggle
     
    on_press:
      then:
        switch.toggle: relay1
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.12.8
INFO Reading configuration /config/esphome/enviromental.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing enviromental (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.0.1
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/enviromental/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/json/json_util.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/socket/lwip_sockets_impl.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/web_server/list_entities.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/web_server/web_server.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/wifi/wifi_component_libretiny.cpp.o
Compiling .pioenvs/enviromental/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/application.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/color.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/component.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/component_iterator.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/controller.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/entity_base.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/helpers.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/log.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/ring_buffer.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/scheduler.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/string_ref.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/time.cpp.o
Compiling .pioenvs/enviromental/src/esphome/core/util.cpp.o
Compiling .pioenvs/enviromental/src/main.cpp.o
Building .pioenvs/enviromental/bootloader.bin
Generating partitions .pioenvs/enviromental/partitions.bin
Creating esp32c3 image...
Successfully created esp32c3 image.
Compiling .pioenvs/enviromental/lib5f4/AsyncTCP-esphome/AsyncTCP.cpp.o
Compiling .pioenvs/enviromental/lib64d/WiFi/WiFi.cpp.o
Compiling .pioenvs/enviromental/lib64d/WiFi/WiFiAP.cpp.o
Compiling .pioenvs/enviromental/lib64d/WiFi/WiFiClient.cpp.o
Compiling .pioenvs/enviromental/lib64d/WiFi/WiFiGeneric.cpp.o
Archiving .pioenvs/enviromental/lib5f4/libAsyncTCP-esphome.a
Compiling .pioenvs/enviromental/lib64d/WiFi/WiFiMulti.cpp.o
Compiling .pioenvs/enviromental/lib64d/WiFi/WiFiSTA.cpp.o
Compiling .pioenvs/enviromental/lib64d/WiFi/WiFiScan.cpp.o
Compiling .pioenvs/enviromental/lib64d/WiFi/WiFiServer.cpp.o
Compiling .pioenvs/enviromental/lib64d/WiFi/WiFiUdp.cpp.o
Compiling .pioenvs/enviromental/lib01c/FS/FS.cpp.o
Compiling .pioenvs/enviromental/lib01c/FS/vfs_api.cpp.o
Compiling .pioenvs/enviromental/libbc6/Update/HttpsOTAUpdate.cpp.o
Archiving .pioenvs/enviromental/lib64d/libWiFi.a
Compiling .pioenvs/enviromental/libbc6/Update/Updater.cpp.o
Compiling .pioenvs/enviromental/lib1da/ESPAsyncWebServer-esphome/AsyncEventSource.cpp.o
Compiling .pioenvs/enviromental/lib1da/ESPAsyncWebServer-esphome/AsyncWebSocket.cpp.o
Archiving .pioenvs/enviromental/lib01c/libFS.a
Compiling .pioenvs/enviromental/lib1da/ESPAsyncWebServer-esphome/WebAuthentication.cpp.o
Archiving .pioenvs/enviromental/libbc6/libUpdate.a
Compiling .pioenvs/enviromental/lib1da/ESPAsyncWebServer-esphome/WebHandlers.cpp.o
Compiling .pioenvs/enviromental/lib1da/ESPAsyncWebServer-esphome/WebRequest.cpp.o
Compiling .pioenvs/enviromental/lib1da/ESPAsyncWebServer-esphome/WebResponses.cpp.o
Compiling .pioenvs/enviromental/lib1da/ESPAsyncWebServer-esphome/WebServer.cpp.o
Compiling .pioenvs/enviromental/lib333/DNSServer/DNSServer.cpp.o
Archiving .pioenvs/enviromental/lib333/libDNSServer.a
Compiling .pioenvs/enviromental/lib915/ESPmDNS/ESPmDNS.cpp.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_core/ed25519/core_ed25519.c.o
Archiving .pioenvs/enviromental/lib1da/libESPAsyncWebServer-esphome.a
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_core/ed25519/core_ristretto255.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_hash/crypto_hash.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_hash/sha256/cp/hash_sha256_cp.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_hash/sha256/hash_sha256.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_onetimeauth/crypto_onetimeauth.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_scalarmult/crypto_scalarmult.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_stream/chacha20/ref/chacha20_ref.c.o
Archiving .pioenvs/enviromental/lib915/libESPmDNS.a
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_stream/chacha20/stream_chacha20.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_stream/crypto_stream.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/crypto_verify/sodium/verify.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/sodium/codecs.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/sodium/core.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/sodium/runtime.c.o
Compiling .pioenvs/enviromental/lib004/libsodium/sodium/utils.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/openssl/cipher-aesgcm.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/ref/cipher-aesgcm.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/ref/cipher-chachapoly.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/ref/dh-curve25519.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/ref/hash-blake2b.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/ref/hash-blake2s.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/ref/hash-sha256.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/sodium/cipher-aesgcm.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/sodium/cipher-chachapoly.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/sodium/dh-curve25519.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/sodium/hash-blake2b.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/backend/sodium/hash-sha256.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/crypto/aes/rijndael-alg-fst.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/crypto/blake2/blake2b.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/crypto/blake2/blake2s.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/crypto/chacha/chacha.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/crypto/donna/curve25519-donna-c64.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/crypto/donna/curve25519-donna.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/crypto/donna/poly1305-donna.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/crypto/sha2/sha256.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/crypto/sha2/sha512.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/crypto/x25519/x25519.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/cipherstate.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/dhstate.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/errors.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/handshakestate.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/hashstate.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/internal.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/names.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/patterns.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/rand_os.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/rand_sodium.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/randstate.c.o
Archiving .pioenvs/enviromental/lib004/libsodium.a
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/signstate.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/symmetricstate.c.o
Compiling .pioenvs/enviromental/libf6b/noise-c/protocol/util.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/Esp.cpp.o
Archiving .pioenvs/enviromental/libf6b/libnoise-c.a
Compiling .pioenvs/enviromental/FrameworkArduino/FirmwareMSC.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/HWCDC.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/IPAddress.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/IPv6Address.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/MD5Builder.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/Print.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/Stream.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/StreamString.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/Tone.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/USB.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/USBCDC.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/USBMSC.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/WMath.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/WString.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/base64.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/cbuf.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-adc.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-bt.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-cpu.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-dac.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-gpio.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-i2c-slave.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-i2c.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-ledc.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-matrix.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-misc.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-psram.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-rgb-led.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-rmt.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-sigmadelta.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-spi.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-time.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-timer.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-tinyusb.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-touch.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/esp32-hal-uart.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/firmware_msc_fat.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/libb64/cdecode.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/libb64/cencode.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/main.cpp.o
Compiling .pioenvs/enviromental/FrameworkArduino/stdlib_noniso.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/wiring_pulse.c.o
Compiling .pioenvs/enviromental/FrameworkArduino/wiring_shift.c.o
Archiving .pioenvs/enviromental/libFrameworkArduino.a
Linking .pioenvs/enviromental/firmware.elf
RAM:   [=         ]  11.1% (used 36492 bytes from 327680 bytes)
Flash: [=====     ]  49.6% (used 909752 bytes from 1835008 bytes)
Building .pioenvs/enviromental/firmware.bin
Creating esp32c3 image...
Successfully created esp32c3 image.
esp32_create_combined_bin([".pioenvs/enviromental/firmware.bin"], [".pioenvs/enviromental/firmware.elf"])
Wrote 0xf19f0 bytes to file /data/build/enviromental/.pioenvs/enviromental/firmware-factory.bin, ready to flash to offset 0x0
========================= [SUCCESS] Took 31.87 seconds =========================
INFO Successfully compiled program.
esptool.py v4.6.2
Serial port /dev/ttyACM1
Connecting....
Chip is ESP32-C3 (revision v0.3)
Features: WiFi, BLE
Crystal is 40MHz
MAC: 34:b4:72:12:a7:f4
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x00010000 to 0x000f1fff...
Flash will be erased from 0x00000000 to 0x00003fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Compressed 924144 bytes to 572834...
Wrote 924144 bytes (572834 compressed) at 0x00010000 in 16.2 seconds (effective 456.8 kbit/s)...
Hash of data verified.
Compressed 12944 bytes to 9299...
Wrote 12944 bytes (9299 compressed) at 0x00000000 in 0.5 seconds (effective 229.9 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 144...
Wrote 3072 bytes (144 compressed) at 0x00008000 in 0.1 seconds (effective 430.9 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 576.8 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
INFO Successfully uploaded program.
INFO Starting log output from /dev/ttyACM1 with baud rate 115200
[00:20:19]ESP-ROM:esp32c3-api1-20210207
[00:20:19]Build:Feb  7 2021
[00:20:19]rst:0xf (BROWNOUT_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
[00:20:19]SPIWP:0xee
[00:20:19]mode:DIO, clock div:1
[00:20:19]load:0x3fcd6100,len:0x438
[00:20:19]load:0x403ce000,len:0x918
[00:20:19]load:0x403d0000,len:0x24e4
[00:20:19]entry 0x403ce000
```

**Comment by kk3844** [comment]
Can confirm that I'm having a similar issue on 2023.12.8.  Boards flashed with the previous version work fine.  Any board that has been upgraded no longer connects to WiFi after wireless upgrade.  I flashed a new board with 12.8 and the board works as long as it is connected via USB.  If you power the board off, then power it on to connect over WiFi, it never comes up.  Bringing it back to serial shows garbage on the log.

**Comment by kk3844** [comment]
Adding further information -- After downgrading HA/ESPHome back to 2023.12.7, the previously online unit came back online almost as if it wasn't updated.  The newly installed unit still shows offline.  These are ESP-WROOM-32 units.

**Comment by clydebarrow** [comment]
The yaml given in in the first comment here builds and runs fine on a C3 for me (I did remove the static IP address, otherwise changed nothing.) The sensors fail of course since there is no hardware for them.

I tested this against the current dev branch and 2023.12.9 from the command line - same results.

**Comment by vecijazz** [comment]
Same problem here. I installed an older version (pip install esphome==2023.11.3) and it's work.

**Comment by clydebarrow** [comment]
Are you using Bluetooth?

**Comment by vecijazz** [comment]
Not for the moment.

**Comment by dat12s** [comment]
No

**Comment by haldi4803** [comment]
@dat12s 
try this! Worked for me.

```
esphome:
  name: $device_name
  friendly_name: $friendly_name
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_cpu: 80000000L

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
```
