### ISSUE TITLE
cover.toggle service does not update optimistic cover state

### ISSUE THREAD

**Issue by samuelmcconnell** [esphome/issues#5412]
### The problem

I have a simple open/closed template cover in optimistic mode. Toggling it from Home Assistant correctly sets the open/closed state, but if I use cover.toggle within my ESPhome config, it does not.

### Which version of ESPHome has the issue?

2023.12.8

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

Lilygo T-RELAY 4

### Component causing the issue

cover

### Example YAML snippet

```yaml
esphome:
  name: garagedoors
  friendly_name: "Garage Door Controller"
  comment: "Lilygo T-RELAY 4"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
  password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Door Opener Fallback"
    password: "..."

captive_portal:
     

switch:
  - platform: gpio
    name: "Relay1"
    id: relay1
    pin: 21
    internal: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 0.2s
      - switch.turn_off: relay1
  - platform: gpio
    name: "Relay2"
    id: relay2
    pin: 19
    internal: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 0.2s
      - switch.turn_off: relay2

binary_sensor:
  - platform: gpio
    pin:
      number: 2
      mode:
        input: true
        pullup: true
    name: north_button
    internal: true
    on_press:
      then:
        - cover.toggle: north_gdo
  - platform: gpio
    pin:
      number: 14
      mode:
        input: true
        pullup: true
    name: south_button
    internal: true
    on_press:
      then:
        - cover.toggle: south_gdo

cover:
  - platform: template
    name: "South Garage Door"
    id: south_gdo
    device_class: garage
    open_action:
      - switch.turn_on: relay1
    close_action:
      - switch.turn_on: relay1
    toggle_action:
      - switch.turn_on: relay1
    optimistic: true
  - platform: template
    name: "North Garage Door"
    id: north_gdo
    device_class: garage
    open_action:
      - switch.turn_on: relay2
    close_action:
      - switch.turn_on: relay2
    toggle_action:
      - switch.turn_on: relay2
    optimistic: true
```
