### ISSUE TITLE
Dallas DS18B20 temperature sensor stopped working after update to 23.12.8

### ISSUE THREAD

**Issue by abarcellona** [esphome/issues#5418]
### The problem

I have 2 devices, one ESP32 and another ESP8266. Both use DS18B20 sensors. They were working without any problem, but after latest update I get the error "Scratch pad checksum invalid!"

### Which version of ESPHome has the issue?

23.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.5

### What platform are you using?

ESP32

### Board

ESP32 WROOM

### Component causing the issue

1-wire DS18B20 temperature sensor

### Example YAML snippet

```yaml
esphome:
  name: esp32-wroom-1
  friendly_name: esp32-wroom-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0f13hxwS+i3T6Nb5Aig9BYYzw5CR4Lamyxgb5oDbWx4="

ota:
  password: "187e5a5e40de27f91b2a4a98d6c249aa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.2.36
    gateway: 192.168.2.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Wroom-1 Fallback Hotspot"
    password: "1234567890"

captive_portal:
    
# Dallas DS18B20
dallas:
  - pin: GPIO04

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:
  - platform: dallas
    address: 0xd200000061324828
    name: "Temperatura ESP32-1"
  - platform: mics_4514
    nitrogen_dioxide:
      name: Nitrogen Dioxide
      unit_of_measurement: PPM
      accuracy_decimals: 2
    carbon_monoxide:
      name: Carbon Monoxide
      unit_of_measurement: PPM
      accuracy_decimals: 2
    hydrogen:
      name: Hydrogen
      unit_of_measurement: PPM
      accuracy_decimals: 2
    ethanol:
      name: Ethanol
      unit_of_measurement: PPM
      accuracy_decimals: 2
    methane:
      name: Methane
      unit_of_measurement: PPM
      accuracy_decimals: 2
    ammonia:
      name: Ammonia
      unit_of_measurement: PPM
      accuracy_decimals: 2
    update_interval: 15s
```

### Anything in the logs that might be useful for us?

```txt
NFO ESPHome 2023.12.8
INFO Reading configuration /config/esphome/esp32-wroom-1.yaml...
INFO Updating https://github.com/ssieb/esphome@ds
INFO Starting log output from 192.168.2.36 using esphome API
INFO Successfully connected to esp32-wroom-1 @ 192.168.2.36 in 0.113s
INFO Successful handshake with esp32-wroom-1 @ 192.168.2.36 in 0.116s
[14:31:28][I][app:102]: ESPHome version 2023.12.8 compiled on Jan 20 2024, 17:56:39
[14:31:28][C][wifi:573]: WiFi:
[14:31:28][C][wifi:405]:   Local MAC: D8:BC:38:E4:8A:34
[14:31:28][C][wifi:410]:   SSID: 'NETGEAR53'[redacted]
[14:31:28][C][wifi:411]:   IP Address: 192.168.2.36
[14:31:28][C][wifi:413]:   BSSID: 68:FF:7B:2F:1F:4A[redacted]
[14:31:28][C][wifi:414]:   Hostname: 'esp32-wroom-1'
[14:31:28][C][wifi:416]:   Signal strength: -60 dB ▂▄▆█
[14:31:28][C][wifi:420]:   Channel: 5
[14:31:28][C][wifi:421]:   Subnet: 255.255.255.0
[14:31:28][C][wifi:422]:   Gateway: 192.168.2.1
[14:31:28][C][wifi:423]:   DNS1: 0.0.0.0
[14:31:28][C][wifi:424]:   DNS2: 0.0.0.0
[14:31:28][C][logger:439]: Logger:
[14:31:28][C][logger:440]:   Level: DEBUG
[14:31:28][C][logger:441]:   Log Baud Rate: 115200
[14:31:28][C][logger:443]:   Hardware UART: UART0
[14:31:28][C][i2c.arduino:053]: I2C Bus:
[14:31:28][C][i2c.arduino:054]:   SDA Pin: GPIO21
[14:31:28][C][i2c.arduino:055]:   SCL Pin: GPIO22
[14:31:28][C][i2c.arduino:056]:   Frequency: 50000 Hz
[14:31:28][C][i2c.arduino:059]:   Recovery: bus successfully recovered
[14:31:28][I][i2c.arduino:069]: Results from i2c bus scan:
[14:31:28][I][i2c.arduino:075]: Found i2c device at address 0x75
[14:31:28][C][dallas.sensor:075]: DallasComponent:
[14:31:28][C][dallas.sensor:076]:   Pin: GPIO4
[14:31:28][C][dallas.sensor:077]:   Update Interval: 60.0s
[14:31:28][D][dallas.sensor:082]:   Found sensors:
[14:31:28][D][dallas.sensor:084]:     0x973ce10457cfc128
[14:31:28][C][dallas.sensor:089]:   Device 'Temperatura ESP32-1'
[14:31:28][C][dallas.sensor:089]:     Device Class: 'temperature'
[14:31:28][C][dallas.sensor:089]:     State Class: 'measurement'
[14:31:28][C][dallas.sensor:089]:     Unit of Measurement: '°C'
[14:31:28][C][dallas.sensor:089]:     Accuracy Decimals: 1
[14:31:28][C][dallas.sensor:097]:     Address: 0xd200000061324828
[14:31:28][C][dallas.sensor:098]:     Resolution: 12
[14:31:28][C][mics_4514:035]: MICS 4514:
[14:31:28][C][mics_4514:036]:   Address: 0x75
[14:31:28][C][mics_4514:037]:   Update Interval: 15.0s
[14:31:28][C][mics_4514:038]:   Nitrogen Dioxide 'Nitrogen Dioxide'
[14:31:28][C][mics_4514:038]:     State Class: 'measurement'
[14:31:28][C][mics_4514:038]:     Unit of Measurement: 'PPM'
[14:31:28][C][mics_4514:038]:     Accuracy Decimals: 2
[14:31:28][C][mics_4514:039]:   Carbon Monoxide 'Carbon Monoxide'
[14:31:28][C][mics_4514:039]:     State Class: 'measurement'
[14:31:28][C][mics_4514:039]:     Unit of Measurement: 'PPM'
[14:31:28][C][mics_4514:039]:     Accuracy Decimals: 2
[14:31:28][C][mics_4514:040]:   Methane 'Methane'
[14:31:28][C][mics_4514:040]:     State Class: 'measurement'
[14:31:28][C][mics_4514:040]:     Unit of Measurement: 'PPM'
[14:31:28][C][mics_4514:040]:     Accuracy Decimals: 2
[14:31:28][C][mics_4514:041]:   Ethanol 'Ethanol'
[14:31:28][C][mics_4514:041]:     State Class: 'measurement'
[14:31:28][C][mics_4514:041]:     Unit of Measurement: 'PPM'
[14:31:28][C][mics_4514:041]:     Accuracy Decimals: 2
[14:31:28][C][mics_4514:042]:   Hydrogen 'Hydrogen'
[14:31:28][C][mics_4514:042]:     State Class: 'measurement'
[14:31:28][C][mics_4514:042]:     Unit of Measurement: 'PPM'
[14:31:28][C][mics_4514:042]:     Accuracy Decimals: 2
[14:31:28][C][mics_4514:043]:   Ammonia 'Ammonia'
[14:31:28][C][mics_4514:043]:     State Class: 'measurement'
[14:31:28][C][mics_4514:043]:     Unit of Measurement: 'PPM'
[14:31:28][C][mics_4514:043]:     Accuracy Decimals: 2
[14:31:28][C][captive_portal:088]: Captive Portal:
[14:31:28][C][mdns:115]: mDNS:
[14:31:28][C][mdns:116]:   Hostname: esp32-wroom-1
[14:31:28][C][ota:097]: Over-The-Air Updates:
[14:31:28][C][ota:098]:   Address: 192.168.2.36:3232
[14:31:28][C][ota:101]:   Using Password.
[14:31:28][C][api:139]: API Server:
[14:31:28][C][api:140]:   Address: 192.168.2.36:6053
[14:31:28][C][api:142]:   Using noise encryption: YES
[14:31:41][D][sensor:094]: 'Carbon Monoxide': Sending state 0.00000 PPM with 2 decimals of accuracy
[14:31:41][D][sensor:094]: 'Nitrogen Dioxide': Sending state 0.00000 PPM with 2 decimals of accuracy
[14:31:41][D][sensor:094]: 'Methane': Sending state 0.00000 PPM with 2 decimals of accuracy
[14:31:41][D][sensor:094]: 'Ethanol': Sending state 0.00000 PPM with 2 decimals of accuracy
[14:31:41][D][sensor:094]: 'Hydrogen': Sending state 0.00000 PPM with 2 decimals of accuracy
[14:31:41][D][sensor:094]: 'Ammonia': Sending state 0.00000 PPM with 2 decimals of accuracy
[14:31:41][W][component:214]: Component mics_4514.sensor took a long time for an operation (0.06 s).
[14:31:41][W][component:215]: Components should block for at most 20-30ms.
[14:31:52][W][dallas.sensor:257]: 'Temperatura ESP32-1' - Scratch pad checksum invalid!
[14:31:52][D][sensor:094]: 'Temperatura ESP32-1': Sending state nan °C with 1 decimals of accuracy


### Additional information

_No response_
