### ISSUE TITLE
x9c Electronic Pot

### ISSUE THREAD

**Issue by SABristol** [esphome/issues#5419]
### The problem

Repeatedly setting x9c output.set_level to 1 causes the output to initially set the pot to max then gradually decrement it down.  

### Which version of ESPHome has the issue?

2023.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.3

### What platform are you using?

ESP32

### Board

az-delivery-devkit-v4

### Component causing the issue

x9c

### Example YAML snippet

```yaml
# Repeat press of test button causes decreasing pot position value
button:
  - platform: template
    name: "Pot Output"
    on_press:
      then:
        - output.set_level:
            id: bcm_digi_pot
            level: 1

# X9C Electronic Potentiometer (0-1)
output:
  - platform: x9c
    id: bcm_digi_pot
    cs_pin: GPIO25
    inc_pin: GPIO26
    ud_pin: GPIO27
    initial_value: 0.01
```

### Anything in the logs that might be useful for us?

```txt
Repeatedly hitting the test button causes the measured pot position to change.
```
