### ISSUE TITLE
Component SEN5x uses incorrect device classes 

### ISSUE THREAD

**Issue by tomlut** [esphome/issues#5431]
### The problem

See https://github.com/home-assistant/core/issues/108827

The SEN5x component uses VOC and NOX device classes for the VOC and NOx sensors supplied by this component respectively. 

However these sensors report a unit-less index rather than in µg/m³ which is the only unit the device classes allow. 

The suggestion in the closed HA issue linked above was to move these sensors to the AQI device class. 

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2024.1.5

### What platform are you using?

ESP32

### Board

QuinLED ESP32

### Component causing the issue

SEN5x

### Example YAML snippet

```yaml
sensor:
  - platform: sen5x
    id: sen54
    pm_1_0:
      name: " PM <1µm"
      id: pm_1_0
      accuracy_decimals: 1
    pm_2_5:
      name: " PM <2.5µm"
      id: pm_2_5
      accuracy_decimals: 1
    pm_4_0:
      name: " PM <4µm"
      id: pm_4_0
      accuracy_decimals: 1
    pm_10_0:
      name: " PM <10µm"
      id: pm_10_0
      accuracy_decimals: 1
    temperature:
      name: "Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Humidity"
      accuracy_decimals: 0
    voc:
      name: "VOC"
    nox:
      name: "NOX"
    temperature_compensation:
      offset: 0
      normalized_offset_slope: 0
      time_constant: 0
    acceleration_mode: low
    store_baseline: true
    address: 0x69
    update_interval: 10s
```

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:714
Integration: Sensor (documentation, issues)
First occurred: 17:25:25 (2 occurrences)
Last logged: 17:25:25

Entity sensor.voc (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('volatile_organic_compounds') it is using; expected one of ['µg/m³']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
Entity sensor.nox (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('nitrous_oxide') it is using; expected one of ['µg/m³']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
```

**Comment by tomlut** [comment]
Additionally I am unable to override this with customize in home assistant.
```
sensor.nox:
  device_class: aqi

sensor.voc:
  device_class: aqi
```

**Comment by tomlut** [comment]
I am able to override it in ESPHome.
```
    voc:
      name: "VOC"
      device_class: aqi
    nox:
      name: "NOX"
      device_class: aqi
```
