### ISSUE TITLE
bk72xx cb2s not sending the mdns for the discovered+adopt feature

### ISSUE THREAD

**Issue by chrwei** [esphome/issues#5435]
### The problem

I'm making a device template using the combo of name_add_mac_suffix: true and dashboard_import.  this works fine on esp8266 devices.  Using the same yaml and only changing the "esp8266: board: d1_mini" to "bk72xx: board: cb2s" results in a working device but it does not show up in the dashboard to be adopted.  mdns packet capture shows the bk72xx isn't sending the right packets to make it work.  i have tried pip on windows and home assistant installs, both have the same behavior.

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

pip

### What platform are you using?

BK72XX

### Board

colorock cr-mini-n2 (cb2s based)

### Component causing the issue

mdns?

### Example YAML snippet

```yaml
substitutions:
  device_name: "thingie"
  device_friendly_name: "thingie"

esphome:
  name: "${device_name}"
  friendly_name: ${device_friendly_name}
  name_add_mac_suffix: true
  project:
    name: "foo.${device_friendly_name}"
    version: "1.0.0"

dashboard_import:
  package_import_url: github://chrwei/esphome_templates/test/test.yaml@main

#esp8266:
#  board: d1_mini

bk72xx:
  board: cb2s

# Enable logging
logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap: {}

web_server:

captive_portal:

text_sensor:
  - platform: version
    name: ESPHome Version
```

### Additional information

wireshark capture zip file (2KB) https://www.dropbox.com/scl/fi/gx8n34zqkvf3spbje2pxs/mdnscap.zip?rlkey=gju38y2ejj2oqjszva2ck7d4t&dl=0

.232 is the esp8266 and .181 is the bk72xx.  capture is power on one, then power on the other.
