### ISSUE TITLE
building esp32-cam fails

### ISSUE THREAD

**Issue by mhanuel26** [esphome/issues#5436]
### The problem

I am getting the following error when building esp32-cam board.

![image](https://github.com/esphome/issues/assets/2257779/aa07f085-153a-4298-a760-23ec1e2df64e)

My yaml file is 

```
esphome:
  name: esp_cam02
  friendly_name: ESPHome Web 10f03c

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5p05ed0dv58CsE8wiOgnhEBFKxbxGJpRI7mAqfkWwaM="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-10F03C"
    password: "SdLL1OD9MAYE"

captive_portal:
    
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]

  # the order of the data_pins is significant, don't mix up the order

  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  name: esp_cam02
  idle_framerate: 0.1fps

output:
  - platform: ledc
    pin: GPIO4
    channel: 2 # channel 1 is used for esp32_camera
    id: led
light:
  - platform: monochromatic
    output: led
    name: espcam_02 light
```

![image](https://github.com/esphome/issues/assets/2257779/d953ffeb-74c2-4846-a549-2bf2b36a9a79)

I am not sure how to debug this, can someone help with some guidance?

Thank you in advance,
Manuel

### Which version of ESPHome has the issue?

2023.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.5

### What platform are you using?

ESP32

### Board

esp32-cam

### Component causing the issue

linkin the project.
