### ISSUE TITLE
ESP32 S2 UART1 logger doesn work with esp-idf

### ISSUE THREAD

**Issue by beikeland** [esphome/issues#5439]
### The problem

```yaml
esp32:
  board: lolin_s2_mini
  framework:
    type: esp-idf
logger:
  hardware_uart: UART1
 ```
Above config compiles and runs but no log output is available on gpio17. It does work with Arduino framework.
 
 I also tried using a `uart:` component to see if I got any output, and when using config below uart works with esp-idf. (leaving `logger:` on `UART1` results in no output from either `logger:` or `uart:` component.
 ```yaml
 logger:
  hardware_uart: USB_CDC
uart:
  tx_pin: 17
  rx_pin: 18
  baud_rate: 115200
interval:
  - interval: 1s
    then:
      - uart.write: ".. testing ..\r\n"
```
 

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

lolin_s2_mini

### Component causing the issue

logger

### Example YAML snippet

```yaml
esphome:
  name: esp32-s2
  friendly_name: esp32-s2

esp32:
  board: lolin_s2_mini
  framework:
    type: esp-idf

logger:
  hardware_uart: UART1
```
