### ISSUE TITLE
FT63x6: No calibration option

### ISSUE THREAD

**Issue by 5of9** [esphome/issues#5441]
### The problem

[calibration] is an invalid option for [touchscreen.ft63x6]. Please check the indentation.
alternative
[calibration_x_min] is an invalid option for [touchscreen.ft63x6]. Please check the indentation.

Is this missing in FT63x6? I also tried calibration_x_min: (deprecated but works on xpt2046)

### Which version of ESPHome has the issue?

2023.12.7

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

FT63x6

### Example YAML snippet

```yaml
touchscreen:
  platform: ft63x6 #display w cam
  address: 0x38
  id: my_touchscreen
  transform:
    mirror_x: true
    mirror_y: true
    swap_xy: false
  calibration:
    x_min: 10
    x_max: 320
    y_min: 39
    y_max: 441
```

**Comment by nielsnl68** [comment]
This is been fixed in[ PR#5997](https://github.com/esphome/esphome/pull/5997). You can use this   When you use this as an external_components then you have the `calibration` back,


```yaml
external_components:
  - source: github://pr#5997
    components: [ display, touchscreen, ft63x6 ]
    refresh: 0sec
```
