### ISSUE TITLE
Light: platform: neopixelbus variant: WS2812 effects: addressable_color_wipe: reverse: true does not clear the previous state of LEDs

### ISSUE THREAD

**Issue by danielbrunt57** [esphome/issues#5454]
### The problem

When using `reverse: true` in `addressable_color_wipe`, it does not clear the pevious state of the LED's like it does with `reverse: false` (default).  I had to code additional logic to clear the LED strip before activating my effect otherwise the previously lit LED's from effect addressable_scan effect would remain and move from right to left as the color_wipe prgressed.  My band-aid code:
```
      - addressable_scan:
          name: "Scan Effect"
          move_interval: 15ms
          scan_width: 5
      - addressable_color_wipe:
          name: Blue Progress
          colors:
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 30
          add_led_interval: 300ms
          reverse: False
      - addressable_color_wipe:
          name: Yellow Progress
          colors:
            - red: 100%
              green: 100%
              blue: 0%
              num_leds: 30
          add_led_interval: 300ms
          reverse: True
      - addressable_color_wipe:
          name: Erase
          colors:
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 30
          add_led_interval: 15ms
          reverse: False
```
```
  - platform: template
    name: "is Closing"
    id: close_movement_sensor
    disabled_by_default: True
    on_press:
      then:
        - sensor.duty_time.reset: parking_light_duty_time
        - light.turn_on:
            id: parking_light_indicator
            effect: Erase
        - delay: 600ms
        - light.turn_on:
            id: parking_light_indicator
            effect: Yellow Progress
            brightness: 100%
            red: 0%
            green: 0%
            blue: 0%
```

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.5

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

light

### Example YAML snippet

```yaml
esphome:
  name: my-garage-door
  friendly_name: My Garage Door
  on_boot:
    priority: 100
    then:
      - binary_sensor.template.publish:
          id: open_movement_sensor
          state: False
      - binary_sensor.template.publish:
          id: close_movement_sensor
          state: False
      - if: 
          condition:
            binary_sensor.is_on:
              id: open_contact_sensor
          then:
            light.turn_on:
              id: parking_light_indicator
              effect: Slow Pulse
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
        
esp8266:
  board: d1_mini
  restore_from_flash: True

logger:

api:
  encryption:
    key: "<redacted>"

ota:
  password: "<redacted>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Distance-Sensor Fallback Hotspot"
    password: "<redacted>"

captive_portal:

binary_sensor:
  - platform: template
    name: Vehicle
    device_class: presence
    lambda:
      if (id(parking_sensor).state < id(yellow_trigger_level).state) {
        return true;
      } else {
        return false;
      }

  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    name: "is Open"
    id: open_contact_sensor
    disabled_by_default: True
    internal: False
    on_press:
      - then:
        - binary_sensor.template.publish:
            id: open_movement_sensor
            state: False
        - binary_sensor.template.publish:
            id: close_movement_sensor
            state: False
        - sensor.duty_time.reset: parking_light_duty_time
        - light.turn_on: 
            id: parking_light_indicator
            effect: Scan Effect
#            effect: Red Color Wipe
            brightness: 50%
            red: 100%
            green: 0%
            blue: 0%

    on_release:
      - binary_sensor.template.publish:
          id: close_movement_sensor
          state: True

  - platform: template
    name: "is Opening"
    id: open_movement_sensor
    disabled_by_default: True
    on_press:
      then:
        - sensor.duty_time.reset: parking_light_duty_time
        - light.turn_on: 
            id: parking_light_indicator
            effect: Blue Progress
            brightness: 100%
    
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: True
    name: "is Closed"
    id: closed_contact_sensor
    disabled_by_default: True
    internal: False
    on_press:
      then:
        - sensor.duty_time.reset: parking_light_duty_time
        - light.turn_off:
            id: parking_light_indicator
        - binary_sensor.template.publish:
            id: open_movement_sensor
            state: False
        - binary_sensor.template.publish:
            id: close_movement_sensor
            state: False
    on_release:
      - sensor.duty_time.start: parking_light_duty_time
      - binary_sensor.template.publish:
          id: open_movement_sensor
          state: True

  - platform: template
    name: "is Closing"
    id: close_movement_sensor
    disabled_by_default: True
    on_press:
      then:
        - sensor.duty_time.reset: parking_light_duty_time
        - light.turn_on:
            id: parking_light_indicator
            effect: Erase
        - delay: 600ms
        - light.turn_on:
            id: parking_light_indicator
            effect: Yellow Progress
            brightness: 100%
            red: 0%
            green: 0%
            blue: 0%

cover:
  - platform: feedback
    name: "Garage Door"
    id: endstop_cover
    device_class: garage
    has_built_in_endstop: True
    max_duration: 12s

    open_action:
      - switch.turn_on: relay
    open_duration: 10s
    open_endstop: open_contact_sensor
    open_sensor: open_movement_sensor

    close_action:
      - switch.turn_on: relay
    close_duration: 10s
    close_endstop: closed_contact_sensor
    close_sensor: close_movement_sensor

    stop_action:
      - switch.turn_on: relay

light:
  - platform: neopixelbus
    variant: WS2812
    pin: D8
    num_leds: 30
    type: grb
    name: "Parking Light Indicator"
    id: parking_light_indicator
    restore_mode: ALWAYS_OFF
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 750ms
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 50ms
          update_interval: 100ms
          min_brightness: 0%
          max_brightness: 100%
      - addressable_scan:
          name: "Scan Effect"
          move_interval: 15ms
          scan_width: 5
      - addressable_color_wipe:
          name: Blue Progress
          colors:
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 30
          add_led_interval: 300ms
          reverse: False
      - addressable_color_wipe:
          name: Yellow Progress
          colors:
            - red: 100%
              green: 100%
              blue: 0%
              num_leds: 30
          add_led_interval: 300ms
          reverse: True
      - addressable_color_wipe:
          name: Erase
          colors:
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 30
          add_led_interval: 15ms
          reverse: False

sensor:
  - platform: duty_time
    id: parking_light_duty_time
    name: Parking Light Duty Time
    update_interval: 1s
    lambda: "return id(closed_contact_sensor).state == false;"
    restore: false
    last_time:
      name: Parking Light Last Turn-On Time
    on_value_range:
      above: 60
      then:
        - light.turn_off: parking_light_indicator

  - platform: ultrasonic
    id: parking_sensor
    trigger_pin: D1
    echo_pin: D2
    unit_of_measurement: "m"
    accuracy_decimals: 1
    update_interval: 1s
    timeout: 4.0m
    pulse_time: 10us
    filters:
      - delta: .02
    on_value:
      then:
        - if:
            condition:
              and:
                - binary_sensor.is_on: open_contact_sensor
                - sensor.duty_time.is_running: parking_light_duty_time
            then:
              - if:
                  condition:
                    - lambda: |-
                       return id(red_trigger_level).state < id(parking_sensor).state;
                    - lambda: |- 
                       return id(parking_light_duty_time).state < 60;
                  then:
                    light.turn_on: 
                      id: parking_light_indicator
                      effect: Slow Pulse
                      brightness: 100%
                      red: 100%
                      green: 0%
                      blue: 0%
              - if:
                  condition:
                    - lambda: |-
                       return (id(green_trigger_level).state < id(parking_sensor).state && id(parking_sensor).state < id(red_trigger_level).state);
                    - lambda: |- 
                       return id(parking_light_duty_time).state < 60;
                  then:
                    light.turn_on: 
                      id: parking_light_indicator
                      effect: none
                      brightness: 100%
                      red: !lambda |-
                        return ((id(parking_sensor).state - id(green_trigger_level).state) / (id(red_trigger_level).state - id(green_trigger_level).state));
                      green: !lambda |-
                        return ((id(red_trigger_level).state - id(parking_sensor).state) / (id(red_trigger_level).state - id(green_trigger_level).state));
                      blue: 0%
              - if:
                  condition:
                    - lambda: |-
                       return  id(parking_sensor).state < id(green_trigger_level).state and id(parking_sensor).state < id(green_trigger_level).state - 0.2;
                    - lambda: |- 
                       return id(parking_light_duty_time).state < 60;
                  then:
                    - light.turn_on: 
                        id: parking_light_indicator
                        effect: Fast Pulse
                        brightness: 100%
                        red: 0%
                        green: 100%
                        blue: 0%
                    - delay : 1s
                    - light.dim_relative:
                        id: parking_light_indicator
                        relative_brightness: 50%
                        transition_length: 5s
              - if:
                  condition:
                    - lambda: |-
                       return  id(parking_sensor).state < id(green_trigger_level).state - 0.2;
                    - lambda: |- 
                       return id(parking_light_duty_time).state < 60;
                  then:
                    - light.turn_on:
                        id: parking_light_indicator
                        effect: none
                        brightness: 75%
                        red: 0%
                        green: 100%
                        blue: 0%

  - platform: copy
    name: 'parking_sensor'
    source_id: parking_sensor
    filters:
      - delta: 0.05

  - platform: homeassistant
    name: "Red Trigger Level"
    id: "red_trigger_level"
    entity_id: input_number.red_trigger_level

  - platform: homeassistant
    name: "Yellow Trigger Level"
    id: "yellow_trigger_level"
    entity_id: input_number.yellow_trigger_level

  - platform: homeassistant
    name: "Green Trigger Level"
    id: "green_trigger_level"
    entity_id: input_number.green_trigger_level

switch:
  - platform: gpio
    pin: D7
    name: "Garage Door Relay"
    id: relay
    internal: False
    # Toggle the relay with a 0.5s pulse simulating a manual button press
    on_turn_on:
    - delay : 500ms
    - switch.turn_off: relay

time:
  - platform: sntp
    id: my_time
```
### Anything in the logs that might be useful for us?

No

### Additional information

I think that's it...
