### ISSUE TITLE
Wrong driver for waveshare e-ink displays

### ISSUE THREAD

**Issue by SO5HMI** [esphome/issues#5455]
### The problem

esp32:
  board: esp32dev
  framework:
    type: arduino

pi:
  clk_pin: 13
  mosi_pin: 14

display:
  - platform: waveshare_epaper
    id: eink
    cs_pin: 15
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 4.2in
    update_interval: 10s
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");

I use original waveshare esp32 e-ink driver board with no other sensors connected

In this config the display doesnt change, but if i change the model to different i see Hello World but in the corner and the not used part of the display has w/b random noise.

working display models:
1.54in - display is changing but, screen is black
1.54inv2 - works part of display according to resolution
2.90in- display is changing but, screen is black
2.90inv2 - works part of display according to resolution
4.2in - not working
4.2in-bv2 - not working
5.83in - not working
5.83inv2 - not working
7.50in - not working
7.50in-bV2 - not working
7.50inV2 - not working

i used this display a half year a go and its working great.

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core 2024.1.6

### What platform are you using?

ESP32

### Board

waveshare E-Paper ESP32 Driver Board

### Component causing the issue

SPI, 

### Example YAML snippet

```yaml
esphome:
  name: panel-salon
  friendly_name: Panel Salon

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:

ota:

wifi:
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
 
captive_portal:
    
#i2c:
#  sda: 21
# scl: 22
#  scan: true
#  id: bus_a

spi:
  clk_pin: 13
  mosi_pin: 14
  
font:
  - file: 'config/fonts/liberation/LiberationSansNarrow-Bold.ttf'
    id: font1
    size: 20 

#sensor:
#  - platform: bme280
#    temperature:
#      name: "Salon temperatura"
#      oversampling: 16x
#      accuracy_decimals: 1
#    pressure:
#      name: "Salon cisnienie"
#      accuracy_decimals: 1
#    humidity:
#      name: "Salon wilgotnosc"
#      accuracy_decimals: 1
#    address: 0x76
#    update_interval: 60s

#pn532_i2c:
 # update_interval: 1s


display:
  - platform: waveshare_epaper
    id: eink
    cs_pin: 15
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 1.54inv2
    update_interval: 10s
    lambda: |-
      it.print(0, 0, id(font1), "1.54inv2");
```
