### ISSUE TITLE
ESP32 Logs & Connection to Home Assistant/ESPHome don't work when `lcd_gpio` display device is defined

### ISSUE THREAD

**Issue by adelin-diac** [esphome/issues#5469]
### The problem

I am trying to make a simple temperature and humidity sensor. Everything works fine, until I include the `display: lcd_gpio` component. The LCD component I am using is an LCD1602. I have it powered via the 5V pin of the ESP.

When I include this, the connection of the ESP32 to Home Assistant or ESPHome doesn't work. The device appears offline, but it's own AP Hotspot isn't visible. Weirdly, I can ping the device to its local IP address, and I can update the firmware using Over-The-Air updates. Once updated, if the `display` yaml block is included, the logs fail to show. This happens even if the ESP is not physically connected to the LCD display.

If i comment out the `display` code, the ESP works fine. I am able to access its logs wirelessly, and view it in Home Assistant. 

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.1.5

### What platform are you using?

ESP32

### Board

ESP32-WROOM-32

### Component causing the issue

lcd_gpio (LCD1602)

### Example YAML snippet

```yaml
esphome:
  name: fyp-temp-sensor
  friendly_name: FYP Temp Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Home Assistant Stuff
logger:
api:
  encryption:
    key: "my-encryption-key"
ota:
  password: "my-ota-pass"
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Manual IP for convenience when pinging
  manual_ip:
    static_ip: 192.168.137.109
    gateway: 192.168.137.1
    subnet: 255.255.255.0
  # Fallback Access Point - If WiFi fails, can still communicate with it
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Fyp-Temp-Sensor Fallback Hotspot"
    password: "pass"
captive_portal:

#################################################################################
sensor:
  ############################
  ## TEMP & HUMIDITY SENSOR ##
  ############################
  - platform: dht
    pin: GPIO23
    model: DHT11
    temperature:
      id: zone_air_temperature_sensor
      name: "FYP Temperature"
    humidity:
      id: zone_air_relative_humidity_sensor
      name: "FYP Relative Humidity"
    update_interval: 60s

  ##################
  ## LIGHT SENSOR ##
  ##################
  - platform: adc
    id: illuminance_sensor
    pin: GPIO35
    name: "LDR Light Sensor"
    attenuation: auto
    update_interval: 15s
    filters:
      - lambda: |-
          const float max_voltage = 3.12; // Maximum voltage
          const float min_voltage = 0.08; // Minimum voltage
          float percentage = ((x - min_voltage) / (max_voltage - min_voltage)) * 100.0;
          return (percentage < 0) ? 0 : (percentage > 100) ? 100 : percentage; // Keep value between 0 and 100
    unit_of_measurement: "%"
    accuracy_decimals: 2
    icon: "mdi:brightness-5"
#################
## LCD Display ##
#################
display:
  - platform: lcd_gpio
    dimensions: 16x2
    id: lcd_display
    data_pins:
      - GPIO32
      - GPIO25
      - GPIO26
      - GPIO27
    enable_pin: GPIO14
    rs_pin: GPIO13

# script:
#   - id: display_hello
#     then:
#       - lambda: |-
#           id(lcd_display).print(0, 0, "Hello World");

# button:
#   - platform: template
#     id: test
#     name: TEST
#     on_press:
#       - script.execute: display_hello
```

### Anything in the logs that might be useful for us?

```txt
abort() was called at PC 0x4015ae23 on core 1


Backtrace:0x40083b59:0x3ffb23c00x4008bb9d:0x3ffb23e0 0x4009111d:0x3ffb2400 0x4015ae23:0x3ffb2480 0x4015ae6a:0x3ffb24a0 0x4015af63:0x3ffb24c0 0x4015b89b:0x3ffb24e0 0x400d940f:0x3ffb2500 0x400d914e:0x3ffb2520 0x4016d561:0x3ffb2540 0x400e0943:0x3ffb2560 0x400df6ea:0x3ffb25b0 0x400e159a:0x3ffb25e0 0x400ec446:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
```

**Comment by adelin-diac** [comment]
UPDATE: 

Retried this with a new ESP32 dev board. Still getting the same problem.

I tried it with the LCD screen connected to 5V, and disconnected. It doesn't make a difference. The problem occurs when the yaml configuration for `display` is included.

**Comment by adelin-diac** [comment]
Updated my code to include a lambda function at it now works. Unsure why, this fixes it, so would appreciate any info if anyone might know?
```
display:
  - platform: lcd_gpio
    dimensions: 16x2
    id: lcd_display
    data_pins:
      - GPIO32
      - GPIO25
      - GPIO26
      - GPIO27
    enable_pin: GPIO14
    rs_pin: GPIO13
    lambda: |-
      it.print(0, 0, "Hello World");
```
