### ISSUE TITLE
can not compile of upload 

### ISSUE THREAD

**Issue by maartenkr** [esphome/issues#547]
DO NOT DELETE ANY TEXT from this template! Otherwise the issue may be closed without a comment.
-->

**Operating environment/Installation (Hass.io/Docker/pip/etc.): Hass.io

`[API] ConnectionError: HTTPConnectionPool(host='api.platformio.org', port=80): Max retries exceeded with url: /v2/lib/search?query=name%3A%22ArduinoJson-esphomelib%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x75fddab0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) (incremented retry: max=5, total=1)`

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP8266

**Affected component:**

**Description of problem:**
i can nog compile of upload

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

`esphome:
  name: 'room2'
  platform: ESP32
  board: mhetesp32devkit
wifi:
  ssid: 'ESP32'
  password: '12345678'
  power_save_mode: none 
api:
web_server:
  port: 80
logger:
ota:
  password: 'Mariska4'
# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

sensor:
  - platform: xiaomi_mijia
    mac_address: 58:2D:34:33:9C:6E
    temperature:
      name: "Kamer Gijs Temperature"
    humidity:
      name: "Kamer Gijs Humidity"
    battery_level:
      name: "Kamer Gijs Battery Level"
  - platform: xiaomi_mijia
    mac_address: 72:C6:DC:28:89:BC
    temperature:
      name: "Kamer 2 Temperature"
    humidity:
      name: "Kamer 2 Humidity"
    battery_level:
      name: "Kamer 2 Battery Level"
      
time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: 0
        hours: 4
        days_of_week: MON-SUN
        then:
           - switch.toggle: restart_switch
switch:
  - platform: restart
    name: "Room2 ESP32 reset"
    id: restart_switch`

**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
