### ISSUE TITLE
lock state of a switch until state of  

### ISSUE THREAD

**Issue by sp2003** [esphome/issues#5470]
### The problem

I'm trying to compile a config for an ESP32 board with 8 relays ([](https://devices.esphome.io/devices/ESP32E-Relay-X8)) and I want relay 5 to turn off and stay in that state until relay 6 is turned on. When relay 6 is turned off, relay 5 is free to switch on or off.

I have written this:

```
- platform: gpio
  pin: GPIO14
  name: 6 enable/disable PdC
  id: relay6
  on_switch.is_on:
    if:
      condition:
        switch.turn_off: relay5

```
But when I validate the config, it fails. If I change "on_switch.is_on" to "on_turn_on" and remove the "if" and "condition" lines, the validation goes well and the automation works, but only once when the state of relay 6 changes. However, I don't get what I want because the trigger only works on state changes.

I have also tried the option 
`interblock: [relay5]
`but obviously it only works in one direction.

Where am I going wrong?

![photo_2024-02-06_12-32-16](https://github.com/esphome/issues/assets/34820831/11b0ff10-6c86-4532-8f74-8fd722a55848)

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.1.6

### What platform are you using?

ESP32

### Board

ESP32 Realy Board x8
