### ISSUE TITLE
i2s audio external dac - internal dac's GPIO25 & GPIO26 trigger on audio play so they cannot be used as 

### ISSUE THREAD

**Issue by tomliekens** [esphome/issues#5471]
### The problem

i2s audio is configured to use external DAC
GPIO25 is configured as DAC to control a LED dimmer with stable variable voltage (inverted)

As soon as audio starts, the led's get triggered. at the end of the sound fragment the led's get triggered once again.
It seems even though external audio dac is configured, ESPHOME triggers also the internal DAC when playing audio.
And so both DAC's on GPIO25 and 26 cannot be used in projects with I2S audio and external audio DAC at the moment.

many thx if someone can fix this!

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.12.9

### What platform are you using?

ESP32

### Board

SparkFun Thing Plus - ESP32 WROOM (U.FL)

### Component causing the issue

i2s audio

### Example YAML snippet

```yaml
esphome:
  name: "esphome-delorean"
  friendly_name: ESPHome_DeLorean

esp32:
  board: esp32dev
  framework:
    type: arduino

# Example configuration entry

# Enable logging
logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-9C938C"
    password: "uXPSKc3DWcMB"

captive_portal:

i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO23
    i2s_bclk_pin: GPIO22

media_player:
  - platform: i2s_audio
    id: media_out
    name: Delorean Media Player
    dac_type: external
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO32


output:
  - platform: esp32_dac
    pin: GPIO25
    id: dac_output
    inverted: true

  - platform: monochromatic
    output: "dac_output"
    name: "Delorean_flux_bands"
    gamma_correct: 1.4
```
