### ISSUE TITLE
TASMOTA reverts back to ESPHOME randomly when uploading the firmware OTA, after restoring configuration or changing settings

### ISSUE THREAD

**Issue by omaramin-2000** [esphome/issues#5487]
### The problem

When I upload the tasmota firmware from esphome OTA and try to restore configurations, modify settings, or restart, it gets the esp device back to the last esphome firmware with all saved configurations including the wifi SSID and password, without even re-configuring from the captive portal as written in the YAML snippet below.

### Which version of ESPHome has the issue?

Latest

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

Esp32-Wrover-E

### Example YAML snippet

```yaml
esphome:
  name: universal-remote
  platform: ESP32
  board: esp32dev
  on_boot:
    - lambda: |-
          // Get the boot cycle count from the global variable
          int boot_cycle_count = id(boot_cycle_count_var);
          // Get the uptime sensor state
          float uptime = id(uptime_sensor).state;
          // Check if the uptime is less than 10 seconds
          if (uptime < 10.0) {
            // Increment the boot cycle count
            boot_cycle_count++;
            // Check if the boot cycle count is 7
            if (boot_cycle_count == 7) {
              // Trigger the factory reset action
              id(factory_reset_button).press();
            }
          } else {
            // Reset the boot cycle count
            boot_cycle_count = 0;
          }
          // Update the global variable with the new boot cycle count
          id(boot_cycle_count_var) = boot_cycle_count;

globals:
  # Define a global variable to store the boot cycle count
  - id: boot_cycle_count_var
    type: int
    restore_value: no
    initial_value: '0'

sensor:
  # Define an uptime sensor to measure the time between boot cycles
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    update_interval: 5s
  # Define a sensor to measure wifi signal
  - platform: wifi_signal
    update_interval: 10s
    id: wifi_signal_db
  - platform: uptime
    name: Uptime
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    

# Enable Wifi
wifi:
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ESP32-universal-remote
    ap_timeout: 1min
captive_portal: 

# Enable Home Assistant API
api: 

ota: 

# GPIO2 Led
status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button"
    on_multi_click:
      # Long press
      - timing:
          - ON for at least 10s
        then:
          - button.press: factory_reset_button

# Enable IR receiver
remote_receiver:
  pin: GPIO35
  dump: all

# Enable IR transmitter
remote_transmitter:
  pin: GPIO23
  carrier_duty_percent: 50%

# Enable Web Server
web_server:
  port: 80
  version: 2
  local: true

http_request:
  useragent: esphome/device
  timeout: 10s

# Enable logging
logger:
  level: VERBOSE

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID

  - platform: restart
    name: "Restart"
  - platform: factory_reset
    name: "Factory Reset Button"
    id: factory_reset_button
```
