### ISSUE TITLE
AC Dimmer Component - zero_cross_pin

### ISSUE THREAD

**Issue by Casavalentino** [esphome/issues#5490]
### The problem

From the manual I see: 
zero_cross_pin: "you can have several dimmers controlled with the same zero cross detector, in such case duplicate the zero_cross_pin config on each output."

I tried to compile a code for multiple ac_dimmer output!

output:
  - platform: ac_dimmer
    id: OUT_CH1
    gate_pin: GPIO25
    zero_cross_pin:
      number: GPIO15
      mode: INPUT
      inverted: yes
    min_power: 10%
    method: leading pulse
    init_with_half_cycle: False

  - platform: ac_dimmer
    id: OUT_CH3
    gate_pin: 4
    zero_cross_pin:
      number: 15
      mode: INPUT
      inverted: yes
    min_power: 10%
    method: leading pulse
    init_with_half_cycle: False

with a single instance the code runs fine. No problem.
When I activate the second instance, I get this error:

"Pin 15 is used in multiple places."

![1](https://github.com/esphome/issues/assets/82965322/592733ae-63ba-48fa-9115-d9b412204619)
![2](https://github.com/esphome/issues/assets/82965322/fe1180b8-51cc-4d99-87b8-e7b83dfd5d2c)
![1](https://github.com/esphome/issues/assets/82965322/7f21e12f-8158-4ac5-b630-6f435501f872)
![2](https://github.com/esphome/issues/assets/82965322/afe143d1-ff8b-4c97-89c9-e5901b49aa37)

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

20240207.1

### What platform are you using?

ESP32

### Board

ESP32-DEVKITC-32E

### Component causing the issue

platform: ac_dimmer

### Example YAML snippet

```yaml
output:
  - platform: ac_dimmer
    id: OUT_CH1
    gate_pin: GPIO25
    zero_cross_pin:
      number: GPIO15
      mode: INPUT
      inverted: yes
    min_power: 10%
    method: leading pulse
    init_with_half_cycle: False

  - platform: ac_dimmer
    id: OUT_CH3
    gate_pin: 4
    zero_cross_pin:
      number: 15
      mode: INPUT
      inverted: yes
    min_power: 10%
    method: leading pulse
    init_with_half_cycle: False
```

### Anything in the logs that might be useful for us?

```txt
This component has not been fully tested yet, if you are testing this component please share your experience with the dimmer hardware and light model and configuration here https://github.com/esphome/feature-requests/issues/278

See also: AC Dimmer Component

Pin 15 is used in multiple places.
```
