### ISSUE TITLE
[Bug] Atom Echo does not connect to wifi with hidden SSID

### ISSUE THREAD

**Issue by o-su** [esphome/issues#5491]
### The problem

Steps to reproduce
Case1: Try to connect to wifi with hidden SSID --> Connection fails
Case2:
Make SSID visible, connect Atom Echo to wifi --> Connected, works as expected
Hide SSID again --> Echo immediately disconnects and wont connect back again

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.6

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
substitutions:
  name: m5stack-atom-echo-10b448
  friendly_name: M5Stack Atom Echo 10b448
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: secret
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

### Anything in the logs that might be useful for us?

```txt
[W][wifi:524]: No matching network found!
```
