### ISSUE TITLE
improv_serial not working with mqtt

### ISSUE THREAD

**Issue by JonasGhost** [esphome/issues#5493]
### The problem

It is not possible to set wifi credential over serial without being connected to wifi or removing the mqtt component from the configuration.

if mDNS is enabled it will run into a boot loop.

### Which version of ESPHome has the issue?

 2023.12.9

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

improv_serial

### Example YAML snippet

```yaml
esphome:
  name: esp-ds18b20
  friendly_name: esp_ds18b20
  name_add_mac_suffix: True
substitutions:
  site: site1
  mqtt_topic_prefix: a
  mqtt_broker: broker.hivemq.com


esp32:
  board: esp32dev
  framework:
    type: esp-idf
    

# Enable logging
logger:

dallas:
  - pin: GPIO4
    id: RL
  - pin: GPIO5
    id: VL
  - pin: GPIO16
    id: AU
  - pin: GPIO17
    id: IN
  - pin: GPIO18
    id: WW

sensor:
  - platform: dallas
    name: "RL"
    dallas_id: RL
    index: 0
  - platform: dallas
    name: "VL"
    dallas_id: VL
    index: 0
  - platform: dallas
    name: "AU"
    dallas_id: AU
    index: 0
  - platform: dallas
    name: "IN"
    dallas_id: IN
    index: 0
  - platform: dallas
    name: "WW"
    dallas_id: WW
    index: 0

mqtt:
  id: mqtt_1
  broker: ${mqtt_broker}
  discovery: false
  topic_prefix: ${mqtt_topic_prefix}/${site} 
  birth_message:
    topic: null
    payload: online
  will_message:
    topic: null
    payload: offline
  shutdown_message: 
    topic: null
    payload: offline
  log_topic: null
  
    
mdns:
  disabled: True

ota:

wifi:
  ssid: "init"
  password: "initinit"

    

improv_serial:
  

esp32_improv:
  authorizer: none
```
