### ISSUE TITLE
on_boot: different behavior if connected to WiFi or not. 

### ISSUE THREAD

**Issue by fxmike08** [esphome/issues#5496]
### The problem

Scenario:

1.  When device boot and is able to connect to Wi-Fi the led is turned on (`switch.turn_on: led` from `on_boot` section). 
2. When device boot and is **not** able to connect to Wi-Fi led is always off.

:heavy_exclamation_mark:  **Note**: On an older version of ESPHOME I didn't this problem.

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

latest

### What platform are you using?

ESP32

### Board

esp32dev

### Example YAML snippet

```yaml
esphome:
  name: esphome-web-672700
  friendly_name: ESPHomeTest
  on_boot:
    priority: -1000
    then:
      - switch.turn_on: led # problem here

esp32:
  board: esp32dev
  framework:
    type: arduino

switch:
  - platform: gpio
    pin:
      number: 15
      mode:
        output: True
        pullup: true
    id: led
    name: "Led"
binary_sensor:
  - platform: gpio
    id: sw
    pin:
      number: 23
      mode:
        input: true
        pullup: True
    name: sw
    on_release: 
      then:
        - lambda: |
            id(led).toggle();   
           
web_server:
  port: 80
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "*****"

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-672700"
    password: "pAArFGt0VQsq"

captive_portal:
```
