### ISSUE TITLE
ESPHome throws Error 127 on compile

### ISSUE THREAD

**Issue by agnoam** [esphome/issues#5498]
### The problem

I have an add-on of the `esphome` in HomeAssistant running on *Raspberry Pi 3b+*, and everything was working perfectly.
Until one day, approx. 3 weeks ago. I tried to update my d1-mini-pro that runs the `esphome` firmware on it. 
The update failed with `Error 127` on `api_connection.cpp.o` file.

Logs attached below.

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2.1

### What platform are you using?

ESP8266

### Board

d1 mini pro

### Example YAML snippet

```yaml
esphome:
  name: project-name
  friendly_name: my-project

  compile_process_limit: 1
  
# Turn on the INBUILT Led
status_led:
  pin: D4

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results

switch:
  - platform: gpio
    pin: D1
    name: controlled_pin1
    id: pin_1
    interlock: [pin_2]

  - platform: gpio
    pin: D2
    name: controlled_pin2
    id: pin_2
    interlock: [pin_1]

esp8266:
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<Generated encryption key>"

ota:


wifi:
  ssid: !secret some_wifi_ssid
  password: !secret some_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "<AccessPoint SSID>"
    password: "<SSID Password>"

captive_portal:
```

### Anything in the logs that might be useful for us?
```txt
Processing <project-name> (board: d1_mini_pro; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 16MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
Compiling .pioenvs/<project-name>/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-lx106-elf-g++: not found
*** [.pioenvs/<project-name>/src/esphome/components/api/api_connection.cpp.o] Error 127
========================= [FAILED] Took 126.50 seconds =========================
```
