### ISSUE TITLE
How to use pin from SX1509 in AC dimmer

### ISSUE THREAD

**Issue by IvanHorban** [esphome/issues#5500]
### The problem

I have esp32 and SX1509 expander. I want to use one of the outputs of the SX1509 as a gate pin for a AC dimmer. How can I do this?

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2.2

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

i2c, SX1509, ac_dimmer

### Example YAML snippet

```yaml
esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "NGyY0g1xjJSsK7LlvpjujNNnczizwM8u2d40LXAhUUE="

ota:
  password: "1d4e28018deabb2e0d66e526b854800e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "hkyQK1jAw4Vc"

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true

sx1509:
  - id: sx1509_hub1
    address: 0x3E

output:
  - platform: sx1509
    sx1509_id: sx1509_hub1
    id: 'sx1509_output'
    pin: 0

  - platform: ac_dimmer
    id: dimmer1
    gate_pin: sx1509_output
    zero_cross_pin:
      number: 12
      mode:
        input: true
      inverted: yes

# lights can then use the configured output
light:
  - platform: monochromatic
    output: dimmer1
    name: Dimmerized Light
```
