### ISSUE TITLE
CSE7766 hard to use since ESPHome 2024.2.0

### ISSUE THREAD

**Issue by DAVe3283** [esphome/issues#5501]
### The problem

With the updates to cse7766 in ESPHome 2024.2.0 (esphome/esphome#6095 and esphome/esphome#6180), it now publishes sensor readings as fast at they come in from the cse7766.

This initially sounds like a good idea, because the user can choose how to filter them. But a couple subtle edge cases are very hard to handle with filters, and were handled quite nicely on the old setup that published all values at once.

- Not using any filters isn't really possible due to the \~10 Hz update rate of the cse7766 when under load. The obvious solution is [throttle_average](https://esphome.io/components/sensor/#throttle-average).
- But under very low and no-load (e.g. Sonoff S31 with the relay off), the cse7766 only has a valid current and power reading very infrequently. Maybe every minute or two.
  - If using [throttle_average](https://esphome.io/components/sensor/#throttle-average), it starts reporting Unknown for current and power, when we really know it to be 0.
    - Extending the timeframe we average over partially solves this, but then results in very unresponsive measurements.
  - If using [throttle](https://esphome.io/components/sensor/#throttle), we miss short transients that could/would meaningfully impact the average value, making the readings less useful.
- Readings are no longer published at the same time, which reduces the accuracy of downstream calculations (such as power factor or apparent power). Though the accuracy may have been dubious to begin with, publishing the voltage, power, and current readings at different times feels like a regression since it makes those calculations worse.

I can't come up with a filter stack to address most of these problems without major downsides.
I propose reverting to the previous behavior: esphome/esphome#6265

<details><summary>Original, inaccurate/incomplete problem statement</summary>

[esphome#6095](https://github.com/esphome/esphome/pull/6095) introduced a bug where the energy output of the CSE7766 will not publish when there is no power consumption.

An attempt to publish an initial 0 was included ([esphome/components/cse7766/cse7766.cpp:166](https://github.com/esphome/esphome/blob/75af4c3d629768ba257d55a89fe40a266ef2fee2/esphome/components/cse7766/cse7766.cpp#L166)) but it does not actually work:
![image](https://github.com/esphome/issues/assets/6894502/188f321c-b33f-4bd8-83a8-a696f1b19b74)

Due to the way it was rearchitected, energy only updates when power is present, and now updates at \~10 Hz, so a filter is basically required to not spam Home Assistant to death. But due to energy now only _sometimes_ publishing values, it makes selecting a filter very difficult.

Using the obvious [throttle_average](https://esphome.io/components/sensor/#throttle-average) filter causes the energy to report Unknown not just at startup, but again any time power consumption drops to 0!
[heartbeat](https://esphome.io/components/sensor/#heartbeat) and [throttle](https://esphome.io/components/sensor/#throttle) kind of work, but still suffer from the initial Unknown state.

IMO the only real fix for this is to publish the energy sensor at the same time/rate as the other sensors, even if there is no new energy value. Since a filter is basically required now, it will be handled just like the other sensors and behave consistently.

I will push a PR tomorrow, but I have a fix working on an outlet now. I will try to also update the documentation at the same time.
</details>

### Which version of ESPHome has the issue?

2024.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2.2

### What platform are you using?

ESP8266

### Board

Sonoff S31

### Component causing the issue

cse7766

### Example YAML snippet

```yaml
esphome:
  name: s31
  friendly_name: S31
  comment: Sonoff S31 Smart Outlet

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0

api:

ota:

wifi:
  ap:

captive_portal:

uart:
  rx_pin: RX
  baud_rate: 4800

switch:
  - platform: gpio
    name: None
    id: relay
    pin: GPIO12

binary_sensor:
  - platform: gpio
    id: power_button
    entity_category: diagnostic
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

sensor:
  - platform: cse7766
    current:
      name: Current
      id: current
    voltage:
      name: Voltage
      id: voltage
    power:
      name: Power
      id: power
    energy:
      name: Energy

status_led:
  pin: GPIO13
```

**Comment by bvarick** [comment]
the `update_interval` is also not being recognized, I'm not sure if these are connected: https://github.com/esphome/issues/issues/5504

**Comment by z3liff** [comment]
I'm having the same issue as @DAVe3283 after the update to 2024.2.0 -- energy reports 'unknown' until power consumption occurs.  Once power consumption stops, the energy value goes back to 'unknown'.

**Comment by DAVe3283** [comment]
The more I think about this, the more I think reverting the original breaking change (esphome/esphome#6095) is the solution.

The way the component works, the individual outputs drift out of sync with each other, which makes calculating things like power factor or apparent power impossible, since they have to be measured over the same time period.

The original implementation intentionally averaged everything together over a _single_ time period, which enabled calculating downstream values (power factor, apparent power) that had meaning. Notice how after only 2 hours of uptime, the sensors are now reporting over a 15-second window, instead of simultaneously as they should:

```
[12:05:09][D][sensor:093]: 'Uptime': Sending state 10122.79492 s with 0 decimals of accuracy
[12:05:22][D][sensor:093]: 'Energy': Sending state 0.53937 Wh with 0 decimals of accuracy
[12:05:25][D][sensor:093]: 'Voltage': Sending state 120.19772 V with 1 decimals of accuracy
[12:05:32][D][sensor:093]: 'Current': Sending state 0.20806 A with 2 decimals of accuracy
[12:05:37][D][sensor:093]: 'Power': Sending state 23.99924 W with 1 decimals of accuracy
```

I don't know how to solve this with filters, and think the original solution of building the averaging into the component itself was the right answer.

**Comment by raftheunis87** [comment]
I'm seeing the same issue here.

**Comment by DAVe3283** [comment]
Updated the description to better capture the issues I am having and the struggles finding a filter stack to get reasonable behavior with the new component.

**Comment by DAVe3283** [comment]
Even with the fix to the `throttle_average` filter (esphome/esphome#6275) this component doesn't fully work correctly.

The main remaining issue for me is energy reports Unknown with either a `throttle` or `heartbeat` filter until some energy is actually consumed, when it should report 0 after startup. And running without a filter leads to an insane number of published states back to Home Assistant while power is being used.

Logs with `heartbeat` filter and no energy use show the filter inexplicably didn't receive the initial 0 the cse7766 publishes:
```
[08:08:32][VV][scheduler:225]: Running interval 'heartbeat' with interval=30000 last_execution=35122 (now=65122)
[08:08:32][VV][sensor.filter:411]: HeartbeatFilter(0x3fff6114)::interval(has_value=NO, last_input=nan)
```

It sounds like there may be a bug in the `heartbeat` filter, but I don't see anything obvious looking at the code, so it might be an architectural issue with filters in general?

**Comment by spridgeon84** [comment]
My Sonoff s31s with the CSE7766 are unusable since the update. Even using the throttle_average code, the wifi connection is extremely unstable, it can take up to 10 minutes just to connect to the the device to read the logs. Commenting out the sensor immediately fixes the issue.

**Comment by DAVe3283** [comment]
Energy is fixed by esphome/esphome#6286 for me!

I put up a PR to add power factor and active power calculations into the cse7766 component directly, since it is harder to do it downstream with the new architecture: esphome/esphome#6292

**Comment by popy2k14** [comment]
> My Sonoff s31s with the CSE7766 are unusable since the update. Even using the throttle_average code, the wifi connection is extremely unstable, it can take up to 10 minutes just to connect to the the device to read the logs. Commenting out the sensor immediately fixes the issue.

Same for me.
Is there any fix?

**Comment by spridgeon84** [comment]
> > My Sonoff s31s with the CSE7766 are unusable since the update. Even using the throttle_average code, the wifi connection is extremely unstable, it can take up to 10 minutes just to connect to the the device to read the logs. Commenting out the sensor immediately fixes the issue.
> 
> Same for me. Is there any fix?

The fix in https://github.com/esphome/esphome/pull/6292 worked for me

**Comment by popy2k14** [comment]
> > > My Sonoff s31s with the CSE7766 are unusable since the update. Even using the throttle_average code, the wifi connection is extremely unstable, it can take up to 10 minutes just to connect to the the device to read the logs. Commenting out the sensor immediately fixes the issue.
> > 
> > 
> > Same for me. Is there any fix?
> 
> The fix in [esphome/esphome#6292](https://github.com/esphome/esphome/pull/6292) worked for me

ok, thx.
Is this for now just in the dev branch?

**Comment by popy2k14** [comment]
With this code it cannot be controlled over HA anymore:

```
sensor:
  - platform: cse7766
    current:
      name: Current
      filters:
        - throttle_average: 2s      
    voltage:
      name: Voltage
      filters:
        - throttle_average: 2s      
    power:
      name: Power
      id: power
      filters:
        - throttle_average: 2s
      on_value_range:
        - above: 2.0
          then:
            - light.turn_on: led
        - below: 1.0
          then:
            - light.turn_off: led  
```

But with this:

```
sensor:
  - platform: cse7766
    current:
      name: Current
      filters:
        - throttle_average: 2s      
    voltage:
      name: Voltage
      filters:
        - throttle_average: 2s      
    power:
      name: Power
      id: power
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 1
        - or:
            - throttle: 180s
            - delta: 0.5 
      on_value_range:
        - above: 2.0
          then:
            - light.turn_on: led
        - below: 1.0
          then:
            - light.turn_off: led  
```

Filters on power, it commes down in the logs after 2 minutes and comes online in HA and can be controlled.
Any hints?
