### ISSUE TITLE
[update_interval] is an invalid option for [sensor.cse7766]. Please check the indentation.

### ISSUE THREAD

**Issue by bvkrieken** [esphome/issues#5504]
### The problem

After receiving the latest update to the ESPHome add-on for Home assistant I get the following error when I try to update an athom-smart-plug-v2 device. The error is:

[update_interval] is an invalid option for [sensor.cse7766]. Please check the indentation.

### Which version of ESPHome has the issue?

2024.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2.2

### What platform are you using?

ESP8266

### Board

athom-smart-plug-v2

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.2.0
INFO Reading configuration /config/esphome/athom-smart-plug-v2-f1971b.yaml...
INFO Detected timezone 'Europe/Amsterdam'
Failed config

sensor.cse7766: [source /data/packages/43f53298/athom-smart-plug-v2.yaml:86]
  platform: cse7766
  
  [update_interval] is an invalid option for [sensor.cse7766]. Please check the indentation.
  update_interval: 10s
  current: 
    name: Current
    filters: 
      - lambda: if (x < 0.060) return 0.0; else return x;
  voltage: 
    name: Voltage
  power: 
    name: Power
    id: power_sensor
    filters: 
      - lambda: if (x < 3.0) return 0.0; else return x;
  energy: 
    name: Energy
    id: energy
    unit_of_measurement: kWh
    filters: 
      - multiply: 0.001
    on_value: 
      then: 
        - lambda: |-
            static float previous_energy_value = 0.0;
            float current_energy_value = id(energy).state;
            id(total_energy) += current_energy_value - previous_energy_value;
            previous_energy_value = current_energy_value;
```

**Comment by bvarick** [comment]
I have the same issue. I didn't have update_interval specified before and it defaulted to 60s. After the update, its updating every 1s. I tried to change it by specifying  `update_interval: 60s` and it gave me this error.

**Comment by bvarick** [comment]
This was the change for cse7766 that was included in 2024.2.0: https://github.com/esphome/esphome/pull/6180

**Comment by DAVe3283** [comment]
You need to add a filter on the output sensors to avoid the insane update speed in 2024.2.0. I recommend also pulling in my fix for the energy sensor until that gets approved/merged/released:

```yaml
substitutions:
  update_interval: 30s

external_components:
  - source: github://pr#6261
    components: [ cse7766 ]

sensor:
  - platform: cse7766
    current:
      name: Current
      id: current
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: Voltage
      id: voltage
      filters:
        - throttle_average: ${update_interval}
    power:
      name: Power
      id: power
      filters:
        - throttle_average: ${update_interval}
    energy:
      name: Energy
      filters:
        - throttle: ${update_interval}
```

**Comment by jwpine** [comment]
same issue on multiple devices. Was this not thoroughly tested?

**Comment by DAVe3283** [comment]
IMO a better solution to this due to other side effects (e.g. https://github.com/esphome/issues/issues/5501#issuecomment-1957720730) is to revert to the old behavior. I submitted #6265 to do that, and you can use that until it gets merged/released:

```yaml
external_components:
  - source: github://pr#6265
    components: [ cse7766 ]

# Continue to use your previous cse7766 setup just like before the 2024.2.0 update!
```

**Comment by bvkrieken** [comment]
And where would I change this in the HASS add-on interface?

**Comment by Jimmythebib** [comment]
Hi @bvkrieken noob here offering my two cents. I pasted the YAML code above suggested by @DAVe3283 into my ESPHome device by going to the ESPHome page on my HA admin panel and clicking the edit link below the respective device. I had access to the YAML config there and added the lines below the packages definition indenting accordingly. I clicked Save and then Install which took a couple of mins.
The issue went away.

**Comment by bvkrieken** [comment]
No joy, I get this error when I do that:

INFO ESPHome 2024.2.0
INFO Reading configuration /config/esphome/athom-smart-plug-v2-f1971b.yaml...
ERROR Error while reading config: Invalid YAML syntax:

mapping values are not allowed here
  in "/config/esphome/athom-smart-plug-v2-f1971b.yaml", line 7, column 15

It has a problem with the # character in this line: 
- source: github://pr#6265

**Comment by DAVe3283** [comment]
That is odd, as it works for most of us. You could try putting it in quotes:

```yaml
external_components:
  - source: "github://pr#6261"
    components: [ cse7766 ]
```

Here is my entire file for a Sonoff S31 that works fine on 2024.2.0:

```yaml
substitutions:
  name: garage-extension-cord
  friendly_name: Garage Extension Cord
  update_interval: 30s
  relay_restore_mode: RESTORE_DEFAULT_OFF

packages:
  mdns: !include common/disable-mdns.yaml # Disable mDNS (it can't traverse from my IoT network anyway)
  s31:
    url: https://PigLab.ReaperLegion.net/home-automation/hass/esphome/packages/sonoff.git
    file: S31-4MB.yaml

# Fix for https://github.com/esphome/issues/issues/5501 and 5504
external_components:
  - source: github://pr#6265
    components: [ cse7766 ]

# Credentials
api:
  encryption:
    key: !secret garage_extension_cord_key

ota:
  password: !secret garage_extension_cord_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  ap:
    password: !secret garage_extension_cord_ota
```

When I get weird compile errors, I usually hit the little 3-dot dropdown on the device and say Clean Build Files, then it usually works fine.

**Comment by bvkrieken** [comment]
That seems to have fixed it, thanks a lot! 🙏

**Comment by jwpine** [comment]
Is there a place to see when the next update comes out that rolls back the cause of this issue?

**Comment by DAVe3283** [comment]
If the proposed rollback works for you, leave a comment or thumbs up on the PR (espome/esphome#6265) so the maintainers know it works right and people want it.

**Comment by solideus** [comment]
Fully configuration of UART parameters works for me, without external_components:

```
uart:
  rx_pin: GPIO16
  baud_rate: 4800
  id: uart_cse
  data_bits: 8
  parity: EVEN
  stop_bits: 1
```

**Comment by calas80** [comment]
The solution is this:

```
uart:
  rx_pin: RX
  baud_rate: 4800
  data_bits: 8
  parity: NONE
  stop_bits: 1
```


The important thing is **parity: NONE**. 
after setting the UART like this, the filters:
```
filters:
  - throttle_average: 10s
```
 work
