### ISSUE TITLE
esp32-cam stops working

### ISSUE THREAD

**Issue by Iv711** [esphome/issues#551]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32-cam (https://ru.aliexpress.com/item/32990986108.html?spm=a2g0s.9042311.0.0.418f33edynENUb)
**Affected component:**

https://esphome.io/components/esp32_camera.html
https://esphome.io/cookbook/pir.html

**Description of problem:**
Immediately I apologize for the English language, I use Google.
"ESP32" freezes after 10-20 hours of operation. The camera ceases to give the image, the sensors hang. But restart.switch works programmatically. After the reboot, the board starts working normally, but again for several hours.
I'll try. All sensors and cameras are hanging, including uptime. except the reset button.

**Problem-relevant YAML-configuration entries:**
```yaml
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  power_down_pin: GPIO32
  pixel_clock_pin: GPIO22
  resolution: 640x480
  jpeg_quality: 10
  name: $hostname cam
  
binary_sensor:
  - platform: gpio
    pin: GPIO2
    name: $hostname pir Sensor
    device_class: motion
  - platform: status
    name: $hostname status    
  - platform: gpio
    pin: GPIO16
    name: $hostname button

sensor:
  - platform: wifi_signal
    name: $hostname WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: $hostname Uptime

text_sensor:
  - platform: version
    name: $hostname ESPHome Version
  - platform: wifi_info
    ssid:
      name: $hostname WiFi

switch:      
  - platform: restart
    name: $hostname restart

```

**Logs (if applicable):**

**Additional information and things you've tried:**
