### ISSUE TITLE
D1 mini with BME280 configuration failure after update ESPhome container.

### ISSUE THREAD

**Issue by RPiNut** [esphome/issues#5514]
### The problem

After updating ESPHome to the lastest docker image, I would like to update my sensors to the latest version, but there was only one error. The BME280 sensor wouldn't update anymore. I hope there is a configuration edit after the BME280 SPI module is added and I didn't found the diffrence. I did try ` - Platform: bme280_i2c` but that made the errors just worse. The last working version was 2023.12.9.

The error mentioned: 

````
Failed config

sensor.bme280: [source /config/d1-mini.yaml:37]
  
  Platform not found: 'sensor.bme280'.
````

### Which version of ESPHome has the issue?

2024.02.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.2.2, but not related to Home Assistant.

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

sensor.bme280

### Example YAML snippet

```yaml
i2c:
  sda: D2
  scl: D1
  scan: False
#  id: bus_a

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      id: bme280_temperature
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 12
            send_every: 1
    pressure:
      name: "BME280 Pressure"
      id: bme280_pressure
    humidity:
      name: "BME280 Humidity"
      id: bme280_humidity
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 12
            send_every: 1
    address: 0x76
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.2.0
INFO Reading configuration /config/d1-mini.yaml...
Failed config

sensor.bme280: [source /config/d1-mini.yaml:37]
  
  Platform not found: 'sensor.bme280'.
  platform: bme280
  temperature: 
    name: BME280 Temperature
    oversampling: 1x
    id: bme280_temperature
    accuracy_decimals: 2
    filters: 
      - sliding_window_moving_average: 
          window_size: 12
          send_every: 1
  pressure: 
    name: BME280 Pressure
    oversampling: 1x
    id: bme280_pressure
  humidity: 
    name: BME280 Humidity
    oversampling: 1x
    id: bme280_humidity
    accuracy_decimals: 2
    filters: 
      - sliding_window_moving_average: 
          window_size: 12
          send_every: 1
  address: 118
  update_interval: 60s
```

### Additional information

The line 37 of the information above, starts in the configuration at line 36 with `sensor:` After ` - Platform: bme280` all lines have red underline.
