### ISSUE TITLE
MHZ19B : no CO2 values reported since ESPHOME update 2024.02

### ISSUE THREAD

**Issue by guidokieboom** [esphome/issues#5517]
### The problem

Since ESPHOME 2024.02 my ESP32 device with MH-Z19B sensor stopped reporting CO2 values. 
<img width="600" alt="Screenshot 2024-02-23 at 09 08 10" src="https://github.com/esphome/issues/assets/65387179/48eed8ac-0d98-4032-93f1-2e724c06745e">

In the upgrade release notes a 'breaking change' is mentioned, but no update of user manual given.
_PMSx003 add relevant device and state classes to default config [esphome#5633](https://github.com/esphome/esphome/pull/5633) by [@wheimbigner](https://github.com/wheimbigner) (breaking-change)_

### Which version of ESPHome has the issue?

2024.02

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.02.02

### What platform are you using?

ESP32

### Component causing the issue

MH-Z19B

### Example YAML snippet

```yaml
# PMSX sensor 
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0μm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5μm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0μm Concentration"
    uart_id: uart_pmsx
```

### Anything in the logs that might be useful for us?

```txt
see above screenshot
```
