### ISSUE TITLE
Shelly Plus 2PM - binary_sensor does not work and cant update

### ISSUE THREAD

**Issue by LukasJerabek** [esphome/issues#5523]
### The problem

If I wire up my shelly plus 2pm behind a switch to a covers with default shelly firmware, I can use the buttons on the wall and manipulate from the shelly app. Once I put in my configuration over esphome in home assistant, my buttons does not do anything, but I can control them from the homeassistant.

Also I have noticed that my futher uploads of changed config doesnt do anything, diagnostics is always the same and behavior does not change. So there are actually two problems - binary_sensor missing, not able to upload any change anymore.

Below is my configuration and after that also diagnostics from esphome. binary_sensor is missing in diagnostics.

### Which version of ESPHome has the issue?

2024.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2024.2.2 Supervisor 2024.02.0 Operating System 11.5 Frontend 20240207.1

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

binary_sensor

### Example YAML snippet

```yaml
esphome:
  name: roleta-loznice
  friendly_name: Roleta Loznice

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: <hidden>

ota:
  password: <hidden>

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: Shelly Roleta Loznice Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: Shelly Roleta Loznice Uptime

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Roleta-Loznice Fallback Hotspot"
    password: <hidden>
  manual_ip:
    static_ip: 192.168.1.235
    gateway: 192.168.1.1
    subnet: 255.255.255.0

captive_portal:

binary_sensor:
  - id: key1
    platform: gpio
    pin:
      number: GPIO05
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      then:
        - cover.open: cover1
    on_release:
      then:
        - cover.stop: cover1
  - id: key2
    platform: gpio
    pin:
      number: GPIO18
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      then:
        - cover.close: cover1
    on_release:
      then:
        - cover.stop: cover1

cover:
  - platform: time_based
    name: "Roleta loznice"
    id: cover1
    open_action:
      - switch.turn_on: relay1
    open_duration: 21000ms
    close_action:
      - switch.turn_on: relay2
    close_duration: 21000ms
    stop_action:
      - switch.turn_off: relay1
      - switch.turn_off: relay2

switch:
  - platform: gpio
    name: "Roleta loznice 1"
    pin: GPIO12
    id: relay1
    interlock: [relay2]
  - platform: gpio
    name: "Roleta loznice 2"
    pin: GPIO13	
    id: relay2
    interlock: [relay1]
```

### Anything in the logs that might be useful for us?

```txt
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.2.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.1",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Prague",
    "os_name": "Linux",
    "os_version": "6.1.74-haos",
    "supervisor": "2024.02.0",
    "host_os": "Home Assistant OS 11.5",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {},
  "integration_manifest": {
    "domain": "esphome",
    "name": "ESPHome",
    "after_dependencies": [
      "zeroconf",
      "tag"
    ],
    "codeowners": [
      "@OttoWinter",
      "@jesserockz",
      "@kbx81",
      "@bdraco"
    ],
    "config_flow": true,
    "dependencies": [
      "assist_pipeline",
      "bluetooth"
    ],
    "dhcp": [
      {
        "registered_devices": true
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/esphome",
    "integration_type": "device",
    "iot_class": "local_push",
    "loggers": [
      "aioesphomeapi",
      "noiseprotocol",
      "bleak_esphome"
    ],
    "requirements": [
      "aioesphomeapi==21.0.2",
      "esphome-dashboard-api==1.2.3",
      "bleak-esphome==0.4.1"
    ],
    "zeroconf": [
      "_esphomelib._tcp.local."
    ],
    "is_built_in": true
  },
  "data": {
    "config": {
      "entry_id": "70dbfbe6a2486a5f66874c710581f487",
      "version": 1,
      "minor_version": 1,
      "domain": "esphome",
      "title": "Roleta Loznice",
      "data": {
        "host": "192.168.1.235",
        "port": 6053,
        "password": "",
        "noise_psk": "**REDACTED**",
        "device_name": "roleta-loznice"
      },
      "options": {
        "allow_service_calls": false
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "d4:8a:fc:40:ff:d8",
      "disabled_by": null
    },
    "storage_data": {
      "device_info": {
        "uses_password": false,
        "name": "roleta-loznice",
        "friendly_name": "Roleta Loznice",
        "mac_address": "**REDACTED**",
        "compilation_time": "Feb 21 2024, 20:35:17",
        "model": "esp32doit-devkit-v1",
        "manufacturer": "Espressif",
        "has_deep_sleep": false,
        "esphome_version": "2023.12.9",
        "project_name": "",
        "project_version": "",
        "webserver_port": 80,
        "voice_assistant_version": 0,
        "legacy_bluetooth_proxy_version": 0,
        "bluetooth_proxy_feature_flags": 0,
        "suggested_area": ""
      },
      "services": [],
      "api_version": {
        "major": 1,
        "minor": 9
      },
      "cover": [
        {
          "object_id": "roleta_loznice",
          "key": 98192789,
          "name": "Roleta loznice",
          "unique_id": "roleta-loznicecoverroleta_loznice",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "assumed_state": true,
          "supports_stop": true,
          "supports_position": true,
          "supports_tilt": false,
          "device_class": ""
        }
      ],
      "sensor": [
        {
          "object_id": "shelly_roleta_loznice_wifi_signal_strength",
          "key": 3260561446,
          "name": "Shelly Roleta Loznice Wifi Signal Strength",
          "unique_id": "d48afc40ffd8-wifisignal",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 2,
          "device_class": "signal_strength",
          "unit_of_measurement": "dBm",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "shelly_roleta_loznice_uptime",
          "key": 3229142024,
          "name": "Shelly Roleta Loznice Uptime",
          "unique_id": "d48afc40ffd8-uptime",
          "disabled_by_default": false,
          "icon": "mdi:timer-outline",
          "entity_category": 2,
          "device_class": "duration",
          "unit_of_measurement": "s",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        }
      ],
      "text_sensor": [],
      "switch": [
        {
          "object_id": "roleta_loznice_1",
          "key": 1772960321,
          "name": "Roleta loznice 1",
          "unique_id": "roleta-lozniceswitchroleta_loznice_1",
          "disabled_by_default": false,
          "icon": "mdi:electric-switch",
          "entity_category": 0,
          "assumed_state": false,
          "device_class": ""
        }
      ]
    },
    "dashboard": "5c53de3b_esphome"
  }
}
```
