### ISSUE TITLE
sensors not showing up in HA

### ISSUE THREAD

**Issue by anhorbc** [esphome/issues#5527]
### The problem

Using an external component to catch wmbus messages regarding water flow. 
Verbose output from esphome:
[20:36:03][D][wmbus:097]: Using driver 'flowiq2200' for ID [0x23543977] RSSI: -43 dBm LQI: 128 Frame: C1 B T: 4D44372C773954233A168D20F7D4F50D217D0BC39BE478CE95273F0C312E95A5C062857D970FC239AFFE71AA0E7C7455849B742FA591E80187906C3DB1BBF1689758905DEE4534BB8D9284C1F2C7 (78)
[20:36:03][V][wmbus:283]: Validating CRC for ELL payload
[20:36:03][V][crc:046]:     calculated: 0xB424, read: 0xB424
[20:36:03][D][wmbus:104]: Decrypted T : 4D44372C773954233A168D20F7D4F50D2124B47804FF230000000004134BD501004413C7C50100426C0132023B000092013B9C01A2013B000006FF1B257001197001A1015B0791015B12A101670F (78)
[20:36:03][V][drivers:573]: Found register '04FF23' with '00000000'
[20:36:03][V][sensor:043]: 'My lqi': Received new state 128.000000
[20:36:03][D][sensor:094]: 'My lqi': Sending state 128.00000  with 0 decimals of accuracy
[20:36:03][V][sensor:043]: 'My RSSI': Received new state -43.000000
[20:36:04][D][sensor:094]: 'My RSSI': Sending state -43.00000 dBm with 0 decimals of accuracy
[20:36:04][V][wmbus:121]: Publishing 'status' = 0.0000
[20:36:04][V][sensor:043]: 'status': Received new state 0.000000
[20:36:04][D][sensor:094]: 'status': Sending state 0.00000  with 0 decimals of accuracy
[20:36:04][V][wmbus:121]: Publishing 'target_water_m3' = 116.1670
[20:36:04][V][sensor:043]: 'target_water_m3': Received new state 116.167000
[20:36:04][D][sensor:094]: 'target_water_m3': Sending state 116.16700 m³ with 3 decimals of accuracy
[20:36:04][V][wmbus:121]: Publishing 'total_water_m3' = 120.1390
[20:36:04][V][sensor:043]: 'total_water_m3': Received new state 120.139000
[20:36:04][D][sensor:094]: 'total_water_m3': Sending state 120.13900 m³ with 3 decimals of accuracy
[20:36:04][V][wmbus:121]: Publishing 'volume_flow_lh' = 0.0000
[20:36:04][V][sensor:043]: 'volume_flow_lh': Received new state 0.000000
[20:36:04][D][sensor:094]: 'volume_flow_lh': Sending state 0.00000 l/h with 0 decimals of accuracy

The sensor debug messages are suggesting that the sensor values are sent to HA, but as seen in the following image, no such sensors are showing up. What could be the problem?

![image](https://github.com/esphome/issues/assets/60405237/40626a40-c862-4e0e-92c2-47abe9da188d)

### Which version of ESPHome has the issue?

2024.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2.3

### What platform are you using?

ESP32

### Board

featheresp32

### Component causing the issue

https://github.com/SzczepanLeon/esphome-components

### Example YAML snippet

```yaml
esphome:
  name: feather-g
  friendly_name: Feather-G

esp32:
  board: featheresp32
  framework:
    type: arduino
substitutions:

  ## all watermeters wmid: "0", your watermeter: wmid: !secret watermeterId
  ## wmid: "0"
  #wmid: 23543977

  ## logger settings, use DEBUG or VERBOSE to see the telegram data
  log_level: "VERBOSE"    # In production mode use "WARN"
  log_wmbus: "VERBOSE"    # Loglevel for wmbus meters component
  log_baudrate: "115200"     # Disable uart logger messages log baudrate=0
# Enable logging
logger:
  id: appslogger
  level: ${log_level}
  baud_rate: ${log_baudrate}
  logs:
    wmbus: ${log_wmbus}
    wMBus-lib: ${log_wmbus}


# Enable Home Assistant API
api:
  encryption:
    key: "a72NxtL4P7JC+2r0wJE21k0uM4DGGhC/BZg6cz5XdCI="

ota:
  password: "762f91cef501fe6560972b5775d592c7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.0.115
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Featherg Fallback Hotspot"
    password: "PV3JIhFqje1Z"

captive_portal:

time:
  - platform: sntp
    id: time_sntp

external_components:
  - source: github://SzczepanLeon/esphome-components@main
    refresh: 0d
    components: [ wmbus ]

wmbus:
  mosi_pin: GPIO18
  miso_pin: GPIO19
  clk_pin:  GPIO21
  cs_pin:   GPIO14
  gdo0_pin: GPIO15
  gdo2_pin: GPIO16
  log_unknown: true
  clients:
    - name: "wmbusmeters_udp"
      ip_address: "192.168.0.76"
      port: 9022
      format: RTLWMBUS
      transport: TCP

sensor:
  - platform: wmbus
    meter_id: 0x23543977
    type: flowiq2200
    key: "MY_SECRET_KEY"
    add_prefix: false
    mode: C1
    total_water_m3:
      id: total_water_m3
    target_water_m3:
      id: target_water_m3
    volume_flow_lh:
      id: volume_flow_lh
    max_flow_lh:
      id: max_flow_lh
    status:
      id: status
    lqi:
      name: "My lqi"
    rssi:
      name: "My RSSI"
```
