### ISSUE TITLE
Gpio turn_on in select template only works when status_led is on

### ISSUE THREAD

**Issue by geonux** [esphome/issues#5528]
### The problem

I'm having a rather strange problem with my Wemos D1 Mini: the two outputs (connected to LEDs) only turns on when the status LED is activated.
If I remove the "light" block containing the status led or disabling the light in HA, the two outputs don't work.

I can't understand the link between the status led and the other outputs. Did I forget something? 

### Which version of ESPHome has the issue?

2024.2.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

select

### Example YAML snippet

```yaml
---
substitutions:
  name: wemos-d1-mini_1
  restore_mode: RESTORE_DEFAULT_OFF
  friendly_name: Wemos D1 Mini
  up_signal_pin: GPIO12
  down_signal_pin: GPIO13

packages:
  common: !include modules/devices/wemos-d1-mini.yaml

light:
  - platform: status_led
    name: "Status LED"
    restore_mode: RESTORE_DEFAULT_ON
    pin:
      number: GPIO2
      inverted: true

# LED Outputs start at 0
output:
  - platform: gpio
    pin: ${up_signal_pin}
    id: up_signal
  - platform: gpio
    pin: ${down_signal_pin}
    id: down_signal

select:
  - platform: template
    name: Mode
    id: heat_mode
    options:
     - "Confort"
     - "Eco"
     - "Hors gel"
     - "Arrêt"
    initial_option: "Eco"
    optimistic: true
    set_action:
      - lambda:  !lambda |-
          if (x == "Eco") {
              id(up_signal).turn_off();  
              id(down_signal).turn_off();
          } else {
              id(up_signal).turn_on();  
              id(down_signal).turn_on();
          }
```

### Additional information

Initially, I tried to manage the "select" statement as below, without much success. Everything works fine with the status LED on, but nothing when it's off.
Even more stunning with this configuration:  when Wemos started up, all the leds (led status and the two GPIO) were flashing together during wifi synchronization ?!? 

```yaml
select:
  - platform: template
    name: Mode
    id: heat_mode
    options:
     - "Confort"
     - "Eco"
     - "Hors gel"
     - "Arrêt"
    initial_option: "Eco"
    optimistic: true
    on_value:
      - lambda:  !lambda |-
          switch(i) {
            case 0:
              ESP_LOGD("option", "Confort");
              id(up_signal).turn_off();  
              id(down_signal).turn_off();
              break;
            case 2:
              ESP_LOGD("option", "Hors gel");
              id(up_signal).turn_off();  
              id(down_signal).turn_on();
              break;
            case 3:
              ESP_LOGD("option", "Arrêt");
              id(up_signal).turn_on();  
              id(down_signal).turn_off();
              break;
            case 1:
            default :
              ESP_LOGD("option", "Eco");
              id(up_signal).turn_on();  
              id(down_signal).turn_on();
          }
```
