### ISSUE TITLE
ESP8266 2024.2.1 update unsuccessful

### ISSUE THREAD

**Issue by emefff** [esphome/issues#5539]
### The problem

EPS82 shows segmentation fault during updating ESPHome 2024.2.1

### Which version of ESPHome has the issue?

2024.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2.3 (Core)

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

compiler error

### Example YAML snippet

```yaml
############# NOTHING SPECIAL HERE, THIS WORKED FOR YEARS ##############

esphome:
  name: esphome--8
  platformio_options:
    board_build.f_cpu: 81000000L #board temp lower

esp8266:
  board: d1_mini
 

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ********REDACTED**********

ota:
  password: ********REDACTED**********

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 8.5dB #8.5-20db
  manual_ip:
    static_ip: ********REDACTED**********
    gateway: ********REDACTED**********
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome--8 Fallback Hotspot"
    password: ********REDACTED**********

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time
    
deep_sleep: #Wemos D1 does not wake up with standard libraries!!  connect D0 pin with the RST pin, remove when flashing via USB necessary
  run_duration: 20s #35°C board temp without DS! Temp readings useless
  sleep_duration: 280s #880s 
  id: deep_sleep_1
    
dallas:
  - pin: GPIO13
    update_interval: 15s #15s

sensor:
  - platform: dallas
    address: 0xbb0821305517ba28
    name: "Mobil_3 ESP Dallas Onboard Temperature"
    accuracy_decimals: 1
    filters:
      - offset: -1.4 
      - filter_out: nan
      - filter_out: 85.0    
  - platform: wifi_signal
    name: "Mobil_3 ESP WiFi Signal"
    update_interval: 300s # defaults to 60s
    accuracy_decimals: 1
  - platform: dht
    pin: 14
    model: DHT22
    #model necessary here!
    temperature:
      name: "Mobil_3 ESP DHT Temperature"
      filters:
      #- sliding_window_moving_average: #https://community.home-assistant.io/t/delay-sensor-reading-on-boot/404753 
      #    window_size: 10
      #    send_every: 10
      #    send_first_at: 10
    humidity:
      name: "Mobil_3 ESP DHT Humidity"
      filters:
      #- sliding_window_moving_average: #https://community.home-assistant.io/t/delay-sensor-reading-on-boot/404753 
      #    window_size: 10
      #    send_every: 10
      #    send_first_at: 10
    update_interval: 15s #15s
```

### Anything in the logs that might be useful for us?

```txt
log during update (2nd try):
####################################
INFO ESPHome 2024.2.1
INFO Reading configuration /config/esphome/esphome--8.yaml...
INFO Detected timezone 'Europe/Vienna'
INFO Generating C++ source...
INFO Compiling app...
Processing esphome--8 (board: d1_mini; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 81MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
Compiling .pioenvs/esphome--8/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling .pioenvs/esphome--8/src/esphome/components/wifi_signal/wifi_signal_sensor.cpp.o
Compiling .pioenvs/esphome--8/src/esphome/core/application.cpp.o
Compiling .pioenvs/esphome--8/src/esphome/core/color.cpp.o
Compiling .pioenvs/esphome--8/src/esphome/core/component.cpp.o
Compiling .pioenvs/esphome--8/src/esphome/core/component_iterator.cpp.o
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/string:55,
                 from src/esphome/core/component.h:6,
                 from src/esphome/core/component_iterator.h:3,
                 from src/esphome/core/component_iterator.cpp:1:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/basic_string.h:3073:6: internal compiler error: Segmentation fault
 3073 |     };
      |      ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
*** [.pioenvs/esphome--8/src/esphome/core/component_iterator.cpp.o] Error 1
========================== [FAILED] Took 6.62 seconds ==========================
######################################################
```

### Additional information

Perhaps just a typo somewhere. Not a big problem for me personally, this one just measures temp and humidity in my toilet :-)
