### ISSUE TITLE
ESP32 esp32_dev 2024.2.1 updates unsuccessful (multiple errors)

### ISSUE THREAD

**Issue by emefff** [esphome/issues#5540]
### The problem

Three ESP32s show errors (segmentation faults + other errors) during updating ESPHome 2024.2.1

### Which version of ESPHome has the issue?

2024.2.3 (Core)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2.1

### What platform are you using?

ESP32

### Board

esp32_dev

### Component causing the issue

different (see below)

### Example YAML snippet

```yaml
########## all three boards have similar yamls, only one is show (nr.2 just for me to remind). If more info needed, will post below ########

esphome:
  name: esphome--2
  platformio_options:
    board_build.f_cpu: 81000000L 

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ********REDACTED**********

ota:
  password: ********REDACTED**********

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 15dB
  manual_ip:
    static_ip: ********REDACTED**********
    gateway: ********REDACTED**********
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome--2 Fallback Hotspot"
    password: ********REDACTED**********

captive_portal:
time:
  - platform: homeassistant
    id: homeassistant_time
    
dallas:
  - pin: 5
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a    


sensor:
  - platform: ccs811
    eco2:
      name: "Wohnzimmer ESP CCS811 eCO2 Value"
    tvoc:
      name: "Wohnzimmer ESP CCS811 Total Volatile Organic Compound"
    address: 0x5A
    temperature: temp_dht 
    humidity: humid_dht
    baseline: 0xBDB6 
    update_interval: 60s
  - platform: dallas
    address: 0x7100000bfd790428
    name: "Vorraum oben ESP Dallas Temperature"
    accuracy_decimals: 1  
    filters:
      - filter_out: nan
      - filter_out: 85.0    
  - platform: dallas
    address: 0xe400000bfecaf628
    name: "Wohnzimmer ESP Dallas External Temperature"
    accuracy_decimals: 1
    filters:
      - filter_out: nan
      - filter_out: 85.0    
  - platform: dallas
    address: 0x4400000bfeef0d28
    name: "Wohnzimmer unten ESP Dallas Temperature"
    accuracy_decimals: 1
    filters:
      - filter_out: nan
      - filter_out: 85.0    
  - platform: dallas
    address: 0x9f00000bfc1fb128
    name: "Wohnzimmer oben ESP Dallas Temperature"
    accuracy_decimals: 1
    filters:
      - filter_out: nan
      - filter_out: 85.0    
  - platform: dallas
    address: 0x1700000bfc30d528
    name: "Wohnzimmer ESP Dallas Onboard Temperature"
    accuracy_decimals: 1
    filters:
      - filter_out: nan
      - filter_out: 85.0    
  - platform: dallas
    address: 0x0600000bfbe93b28
    name: "Computerkabinett ESP Dallas Temperature"
    accuracy_decimals: 1
    filters:
      - filter_out: nan
      - filter_out: 85.0    
  - platform: dht
    pin: 23
    temperature:
      name: "Wohnzimmer ESP DHT Temperature"
      id: temp_dht
    humidity:
      name: "Wohnzimmer ESP DHT Humidity"
      id: humid_dht
    update_interval: 60s
  - platform: bh1750
    name: "Wohnzimmer  ESP BH Illuminance"
    address: 0x23
    update_interval: 60s
  - platform: uptime
    name: "Wohnzimmer ESP Uptime"
    update_interval: 300s # defaults to 60s
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1
  - platform: wifi_signal
    name: "Wohnzimmer ESP WiFi Signal"
    update_interval: 300s # defaults to 60s
    accuracy_decimals: 1
  - platform: adc
    pin: 36
    name: "Wohnzimmer MQ-2 Gas und Rauch analog"
    attenuation: 11dB
    update_interval: 30s #24s
    unit_of_measurement: '%'
    id: wohnzimmer_smoke_analog_sensor
    filters:
     lambda: |- 
       return (x * 100/3.3);

button:
  - platform: restart
    name: "Wohnzimmer Restart"
    id: wz_restart_button
    disabled_by_default: true
    on_press:
      then:
        - logger.log: Button Pressed

status_led:
  pin:
    number: GPIO2
    
binary_sensor:
  - platform: gpio
    pin: 35
    device_class: motion
    id: vorraum_radar_binary_sensor
    #disabled_by_default: true
    name: "Vorraum Radar Sensor"
    internal: true
    #on_click:
    #  min_length: 50ms
    #  max_length: 2000ms
    on_press:
      then:
        - switch.turn_on: vorraum_radar_switch
  - platform: gpio
    pin: 16
    device_class: smoke
    id: wohnzimmer_smoke_digital_sensor
    #disabled_by_default: true
    name: "Wohnzimmer MQ-2 Gas und Rauch digital"
    internal: true
    #on_click:
    #  min_length: 50ms
    #  max_length: 2000ms
    on_press:
      then:
        - switch.turn_on: wohnzimmer_smoke_switch   

switch: 
  - platform: gpio
    pin: 13
    name: "Vorraum Radar Switch"
    #disabled_by_default: true
    id: vorraum_radar_switch
    on_turn_on:
    - delay: 30s
    - switch.turn_off: vorraum_radar_switch
  - platform: gpio
    pin: 14
    name: "Wohnzimmer Smoke Switch"
    #disabled_by_default: true
    id: wohnzimmer_smoke_switch
    on_turn_on:
    - delay: 60s
    - switch.turn_off: wohnzimmer_smoke_switch
```

### Anything in the logs that might be useful for us?

```txt
######## LOG DEVICE NR 2 ########
INFO ESPHome 2024.2.1
INFO Reading configuration /config/esphome/esphome--2.yaml...
INFO Detected timezone 'Europe/Vienna'
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing esphome--2 (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 81MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.0.1
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|-- Wire @ 2.0.0
Compiling .pioenvs/esphome--2/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/gpio/switch/gpio_switch.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/homeassistant/time/homeassistant_time.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/i2c/i2c.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/i2c/i2c_bus_arduino.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/i2c/i2c_bus_esp_idf.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/restart/button/restart_button.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/sensor/sensor.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/socket/lwip_sockets_impl.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/status_led/status_led.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/switch/automation.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/switch/switch.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/text_sensor/filter.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/text_sensor/text_sensor.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/time/automation.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/time/real_time_clock.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/uptime/uptime_sensor.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/wifi/wifi_component_libretiny.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/components/wifi_signal/wifi_signal_sensor.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/core/application.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/core/color.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/core/component.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/core/component_iterator.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/core/controller.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/core/entity_base.cpp.o
Compiling .pioenvs/esphome--2/src/esphome/core/helpers.cpp.o
In file included from /data/cache/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/deque:64,
                 from /data/cache/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/queue:60,
                 from src/esphome/components/sensor/filter.h:3,
                 from src/esphome/components/sensor/sensor.h:7,
                 from src/esphome/core/application.h:16,
                 from src/esphome/core/entity_base.cpp:2:
/data/cache/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/stl_deque.h: In instantiation of '#'<invalid tree code>' not supported by dump_decl#<declaration error>':
src/esphome/core/entity_base.cpp:96:1:   required from here
/data/cache/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/stl_deque.h:209:7: internal compiler error: Segmentation fault
       operator+=(difference_type __n) _GLIBCXX_NOEXCEPT
       ^~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
*** [.pioenvs/esphome--2/src/esphome/core/entity_base.cpp.o] Error 1
/tmp/ccnPsf4m.s: Assembler messages:
/tmp/ccnPsf4m.s: Internal error in subseg_set_rest at /builds/idf/crosstool-NG/.build/xtensa-esp32-elf/src/binutils/gas/subsegs.c:126.
Please report this bug.
*** [.pioenvs/esphome--2/src/esphome/core/helpers.cpp.o] Error 1
========================= [FAILED] Took 36.12 seconds =========================
```
