### ISSUE TITLE
wifi_info: address_0 required if address_1 needed

### ISSUE THREAD

**Issue by Nardol** [esphome/issues#5551]
### The problem

To display both IPv4 and IPv6 addresses, there are new sub-sensors of `ip_address` in `wifi_info` component.
The main `ip_address` sensor already displays IPv4, so I did not remove it to avoid strange behavior with an entity not existing anymore in Home Assistant.
To avoid IPv4 displayed twice, I did not add `address_0` and only 1 and 2 to display both local and global IPv6.
IPv4 was displayed right but both `address_1` and 2 were displayed as unknown.
When I added an `address_0` sub-sensor which I marked as internal, my IPv6 addresses were also displayed.
It looks we have to put an `address_0` sensor if we need `address_1`. Same if only defining a 0 and 2, `address_2` is marked as unknown.
It has to begin with 0 and range must have no blank.

### Which version of ESPHome has the issue?

2024.3.0-dev

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2024.2.4

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

wifi_info

### Example YAML snippet

```yaml
esphome:
  name: diffuseur-bureau

esp8266:
  board: esp01_1m

web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_key

network:
  enable_ipv6: true
  min_ipv6_addr_count: 2

text_sensor:
- platform: wifi_info
  ip_address:
    name: Adresse IP Diffuseur bureau
    address_1:
      name: IPv6 locale
    address_2:
      name: IPv6 globale
```

### Additional information

Also observed by @jeremyp3 with an ESP32 az-delivery devkitc so not specific to ESP8266.
I have no ethernet device to try with.
