### ISSUE TITLE
Deleted switches still provided to Home Assistant

### ISSUE THREAD

**Issue by tomlut** [esphome/issues#5561]
### The problem

I changed some switches to buttons in all of my 28 ESPHome devices. All went well, after flashing the buttons work great, except the switches are still being provided by ESPHome to Home Assistant and so they can not be deleted. Even after a HA restart. 

![Screenshot 2024-03-02 at 12-17-47 Settings – Home Assistant](https://github.com/esphome/issues/assets/10679300/b6ffe7ea-cd74-4012-9b55-7251a1fb7cc3)

![Untitled](https://github.com/esphome/issues/assets/10679300/2dd1a7e7-633d-4433-91d4-20c2dbdcc819)

Deleting all my devices from the ESPHome HA integration and re-adding them might work but this should not have to be done for a component deletion. 

### Which version of ESPHome has the issue?

2024.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2024.2.5

### What platform are you using?

ESP32

### Board

QinLED ESP32

### Component causing the issue

Switch

### Example YAML snippet

```yaml
## Before
switch:
  - platform: restart
    name: "Doorbell Upstairs Restart"

# After (there is no switch config at all)
button:
  - platform: restart
    name: "Doorbell Upstairs Restart"
```
