### ISSUE TITLE
Modbus: read 3 registers, sum up the values.

### ISSUE THREAD

**Issue by vladT0** [esphome/issues#5563]
### The problem

Hi all,

Please help me to find a solution how to read 3 registers, sum up the values, and convert them into one result. I tried using register_count=3, but it didn't help me.

### Which version of ESPHome has the issue?

2024.2.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
- platform: modbus_controller
    modbus_controller_id: ${inverter_id}_0
    name: "Meter Power1"
    id: ${inverter_id}_Meter_Power1
    register_type: read
    register_count: 1
    address: 31026
    unit_of_measurement: "kW"
    device_class: power
    value_type: S_WORD
    accuracy_decimals: 3
    filters:
    - multiply: 1

  - platform: modbus_controller
    modbus_controller_id: ${inverter_id}_0
    name: "Meter Power2"
    id: ${inverter_id}_Meter_Power2
    register_type: read
    address: 31027
    unit_of_measurement: "kW"
    device_class: power
    value_type: S_WORD
    accuracy_decimals: 3
    filters:
    - multiply: 1

  - platform: modbus_controller
    modbus_controller_id: ${inverter_id}_0
    name: "Meter Power3"
    id: ${inverter_id}_Meter_Power3
    register_type: read
    address: 31028
    unit_of_measurement: "kW"
    device_class: power
    value_type: S_WORD
    accuracy_decimals: 3
    filters:
    - multiply: 1
```
