### ISSUE TITLE
Substitutions in `!include`d files do not get updated with the values passed in `vars`

### ISSUE THREAD

**Issue by fakuivan** [esphome/issues#5568]
### The problem

`vars` in `!include` do not get substituted in entries for the `substitutions` components on the imported file, making the following fail:

```yaml
---
# main file
...
  !include
    file: my_file.yaml
    vars:
      my_id: some_id
---
# my_file.yaml
substitutions:
  # this fails
  sensor_name: Sensor of id $my_id

binary_sensor:
  name: $sensor_name
  id: $my_id
```

This is a result of how `vars` in `!include` is processed as substitutions in `substitute_vars`.

https://github.com/esphome/esphome/blob/357ac3b85f6cff3c93ec8a3c29daca1e945a4fda/esphome/yaml_util.py#L286-L316

Specifically this line, where the contents of the `substitutions` section is swapped by what's in `vars`, instead of first substituted and then swapped back in. It'll probably be a good idea to specify how substitutions are to be merged in cases like this.

### Which version of ESPHome has the issue?

2024.3.0-dev

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
---
# main file
esphome:
  name: test

packages:
  included: !include
    file: included.yaml
    vars:
      included_sensor_id: included_sensor

host:

---
# included.yaml

substitutions:
  included_sensor_id_nested: $included_sensor_id

sensor:
  - id: $included_sensor_id_nested
    platform: template
    name: Inlcuded sensor
```

### Anything in the logs that might be useful for us?

```txt
WARNING Found '$included_sensor_id' (see substitutions->included_sensor_id_nested) which looks like a substitution, but 'included_sensor_id' was not declared
WARNING Found '$included_sensor_id' (see substitutions->included_sensor_id_nested) which looks like a substitution, but 'included_sensor_id' was not declared
WARNING Found '$included_sensor_id' (see sensor->0->id) which looks like a substitution, but 'included_sensor_id' was not declared
```

**Comment by ssieb** [comment]
What is the point of doing substitutions like that?

**Comment by fakuivan** [comment]
The same point as using substitutions in the first place, avoiding repetition, for example:

```yaml
---
# main file
esphome:
  name: test

packages:
  included: !include
    file: included.yaml
    vars:
      value: some value

host:

---
# included.yaml

substitutions:
  frequently_used_value: ${value} and more

...
- $frequently_used_value
- $frequently_used_value
- $frequently_used_value
- $frequently_used_value
- $frequently_used_value
```

that's the first thing I can come up with, I'm sure there are more uses

**Comment by Xiretza** [comment]
Is there any workaround for this? This is a really annoying limitation for more complex configurations

**Comment by jpeletier** [comment]
Since https://github.com/esphome/esphome/pull/10806 you can do:

```yaml
substitutions:
  value: hello
  frequently_used_value: ${value} and more
``` 

In fact, you could do:

```yaml
# main file
substitutions:
  value: hello

packages:
  included: !include included.yaml

sensor:
  - platform: template
    name: ${frequently_used_value}

---
# included.yaml

substitutions:
  frequently_used_value: ${value} and more

sensor:
  - platform: template
    name: ${frequently_used_value} again
```

Package vars are local to the included package and then disappear and won't affect substitutions. Not something perhaps convenient but it works now like this for backward compatibility.

Please close the issue if this solves it for you.

**Comment by WolfWildWeird** [comment]
Hi! I'm running into a very similar bug regarding nested substitutions inside an `!include` block. 
When passing a nested substitution into `vars:`, the YAML parser either crashes or fails to resolve it correctly.

Here are my tests and the temporary workaround I found.

**Attempt 1: Using `${}` syntax**
```yaml
substitutions:
  wifi:
    power: 10.0

<<: !include { file: component/wifi.yaml, vars: { power: ${wifi.power} } }

```

**Error:**

```text
while parsing a flow mapping 
  in "MyConfig.yaml", line 66, column 59
expected ',' or '}', but got '{'

```

**Attempt 2: Using `$` syntax**

```yaml
<<: !include { file: component/wifi.yaml, vars: { power: $wifi.power } }

```

**Error:**

```text
Expected decibel with unit, got {'power': 10.0}.power.

```

**Attempt 3: Using bracket syntax**

```yaml
<<: !include { file: component/wifi.yaml, vars: { power: ${wifi['power']} } }

```

**Error:**
Same parsing issue as Attempt 1.

**Temporary Workaround:**
Flattening the substitution variable name (removing the nested structure) works perfectly.

```yaml
substitutions:
  wifi_power: 10.0

<<: !include { file: component/wifi.yaml, vars: { power: $wifi_power } }

```

*For context, here is the relevant section of `component/wifi.yaml`:*

```yaml
wifi:
  # [...]
  output_power: ${ power | default(20.0) }

```

Hope this helps pinpoint the parsing issue! Let me know if you need any more tests on my end.

**Comment by jpeletier** [comment]
@WolfWildWeird You have a YAML syntax error. Quote the value for `power`:

```yaml
<<: !include { file: "component/wifi.yaml", vars: { power: "${wifi.power}" } }
```

In any case, I do not recommend to use `<<` YAML operator for reusable components. Better use a package:

main.yaml:
```yaml
substitutions:
  wifi:
    power: 10.0

packages:
  my_wifi_package: !include
    file: component/wifi.yaml
    vars:
      power: ${wifi.power}
```

wifi.yaml:
```yaml
wifi:
  ssid: MyHomeNetwork
  password: VerySafePassword
  output_power: ${power}
```

**Comment by fakuivan** [comment]
Afaik this should have been fixed in `2026.5.0`. Got codex to try it out and came back with:

> Confirmed fixed in ESPHome **2026.5.0** by [[esphome/esphome#16274](https://github.com/esphome/esphome/pull/16274)](https://github.com/esphome/esphome/pull/16274).
>
> Tested with:
>
> ```yaml
> # main.yaml
> esphome:
>   name: test
>
> packages:
>   included: !include
>     file: included.yaml
>     vars:
>       included_sensor_id: included_sensor
>
> host:
> ```
>
> ```yaml
> # included.yaml
> substitutions:
>   nested_id: $included_sensor_id
>
> sensor:
>   - platform: template
>     id: $nested_id
>     name: Included sensor
> ```
>
> - **2026.4.5:** exits 2; `$included_sensor_id` remains unresolved and causes an invalid ID.
> - **2026.5.0:** exits 0 with `Configuration is valid!`; `nested_id` and the sensor ID both resolve to `included_sensor`.
>
> Closing as fixed in 2026.5.0 should be appropriate.

So I'll be closing this out.

**Comment by Xiretza** [comment]
To confirm it for real, rather than boiling an ocean to get something statistically resembling an answer out of a Large Lying Model:

`test.yaml`:

```yaml
esphome:
  name: test

packages:
  included: !include
    file: included.yaml
    vars:
      included_sensor_id: included_sensor

host:
```

`included.yaml`:

```yaml
substitutions:
  included_sensor_id_nested: $included_sensor_id

sensor:
  - id: $included_sensor_id_nested
    platform: template
    name: Inlcuded sensor
```

On `2026.4.0`:

```
$ esphome config test.yaml
INFO ESPHome 2026.4.0
INFO Reading configuration test.yaml...
WARNING The string '$included_sensor_id' looks like an expression, but could not resolve all the variables: Could not resolve substitution variable 'included_sensor_id_nested': 'included_sensor_id' is undefined (see substitutions->included_sensor_id_nested in included.yaml 4:8)
Failed config

sensor.template: [source included.yaml:5]

  IDs must only consist of upper/lowercase characters, the underscorecharacter and numbers. The character '$' cannot be used.
  id: $included_sensor_id
  platform: template
  name: Inlcuded sensor
```

On `2026.5.0`:

```
$ esphome config test.yaml
INFO ESPHome 2026.5.0
INFO Reading configuration test.yaml...
substitutions:
  included_sensor_id_nested: included_sensor
esphome:
  name: test
  min_version: 2026.5.0
  build_path: build/test
  friendly_name: ''
  platformio_options: {}
  environment_variables: {}
  includes: []
  includes_c: []
  libraries: []
  name_add_mac_suffix: false
  debug_scheduler: false
  areas: []
  devices: []
host:
  mac_address: 98:35:69:AB:F6:79
sensor:
  - platform: template
    id: included_sensor
    name: Inlcuded sensor
    disabled_by_default: false
    force_update: false
    accuracy_decimals: 1
    update_interval: 60s

INFO Configuration is valid!
```

Took me all of 5 minutes. You, too, can use your brain!
