### ISSUE TITLE
Illegal instruction with RP2040 in ESPHome 2024.2.2

### ISSUE THREAD

**Issue by mansson** [esphome/issues#5574]
### The problem

My yaml worked in 2024.2.1 but fail to build in 2024.2.2

_"/data/cache/platformio/packages/framework-arduinopico/boot2/boot2_w25q080_2_padded_checksum.S:8: Internal error (Illegal instruction)."_

Enclosing files.
[logs_esphome1_run(2).txt](https://github.com/esphome/issues/files/14513412/logs_esphome1_run.2.txt)
[source.txt](https://github.com/esphome/issues/files/14513407/source.txt)

I'm not sure what you mean by "type of installation" I run HAOS on a Raspberry pi 4. Maybe there is a docker inside, It's not obvious to me.

### Which version of ESPHome has the issue?

2024.2.2

### What type of installation are you using?

HAOS

### Which version of Home Assistant has the issue?

2024.2.5

### What platform are you using?

RP2040

### Board

Raspberry pi pico WH

### Component causing the issue

n.a.

### Example YAML snippet

```yaml
esphome:
  name: esphome1
  friendly_name: esphome1
# compile_process_limit: 1

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "edited"

ota:
#  password: "edited"
  password: "edited"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

 # Optional manual IP
  manual_ip:
    static_ip: 192.168.2.250
    gateway: 192.168.2.1
    subnet: 255.255.255.0

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Esphome1 Fallback Hotspot"
    password: "edited"

# RP2040 send/receive not yet in mainline NOTE: quotes added here not to upset markdown. Editors note.
external_components:
  "- source: github://pr#5974"
    components: [ remote_transmitter, remote_receiver ]

remote_transmitter:
  pin: 
    number: GPIO18
  carrier_duty_percent: 50%

remote_receiver:
  pin: GPIO20
  dump: nexa
  buffer_size: 10kb

switch: 
  - platform: gpio
    pin: GPIO16
    name: "ESPHome1 GPIO16"

  - platform: gpio
    pin: GPIO17
    name: "ESPHome1 GPIO17"

  - platform: template
    name: RF Power Button pin 1
    optimistic: true
    turn_on_action:
      - remote_transmitter.transmit_nexa:
          device: 0x38DDB4A
          state: 1
          group: 0
          channel: 15
          level: 0
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/esphome1/FrameworkArduinoBootloader/boot2_w25q080_2_padded_checksum.S.o
/data/cache/platformio/packages/framework-arduinopico/boot2/boot2_w25q080_2_padded_checksum.S: Assembler messages:
/data/cache/platformio/packages/framework-arduinopico/boot2/boot2_w25q080_2_padded_checksum.S:8: Internal error (Illegal instruction).
Please report this bug.
*** [.pioenvs/esphome1/FrameworkArduinoBootloader/boot2_w25q080_2_padded_checksum.S.o] Error 1
Compiling .pioenvs/esphome1/src/esphome/components/api/api_connection.cpp.o
/tmp/ccE0pOUp.s: Assembler messages:
/tmp/ccE0pOUp.s:128: Internal error (Illegal instruction).
Please report this bug.
*** [.pioenvs/esphome1/FrameworkArduinoVariant/picow_init.cpp.o] Error 1
/tmp/ccSMR7Uv.s: Assembler messages:
/tmp/ccSMR7Uv.s:46: Internal error (Illegal instruction).
Please report this bug.
*** [.pioenvs/esphome1/FrameworkArduinoVariant/picow_digital.cpp.o] Error 1
/tmp/ccnmP3ya.s: Assembler messages:
/tmp/ccnmP3ya.s:64: Internal error (Illegal instruction).
Please report this bug.
*** [.pioenvs/esphome1/src/esphome/components/api/api_connection.cpp.o] Error 1
```

### Additional information

I also tried without github://pr#5974 in case it was now merged, but the result was similar.
