### ISSUE TITLE
BME280 :    Platform not found: 'sensor.bme280'.

### ISSUE THREAD

**Issue by hpb-55** [esphome/issues#5577]
### The problem

since ESPHome version 2024.x.x, ESP32 boards with BME280 sensors do not compile anymore
Last known working version ESPHome 2023.12.9
No changes to yaml files have been applied.

Restoring to 2023.12.9, everything compiles 

### Which version of ESPHome has the issue?

2024.xx.x

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.xx.x

### What platform are you using?

ESP32

### Board

D1 Mini ESP32

### Component causing the issue

BME280

### Example YAML snippet

```yaml
..
i2c:

  


sensor:

  


  - platform: bme280
    temperature:
      name: "ESP32Heizraum2 BME280 Temperatur"
      id: ESP32Heizraum2_BME280_Temperatur
```

### Anything in the logs that might be useful for us?

```txt
NFO ESPHome 2024.2.2
INFO Reading configuration /config/esphome/esp32-heizraum2.yaml...
...
Failed config

sensor.bme280: [source /config/esphome/esp32-heizraum2.yaml:72]
  
  Platform not found: 'sensor.bme280'.
  platform: bme280


...
```

### Additional information

![Unbenannt](https://github.com/esphome/issues/assets/75421799/30603559-6bcc-4084-9a15-bf145bd380f8)
