### ISSUE TITLE
Can't detect i2c device

### ISSUE THREAD

**Issue by AussieMakerGeek** [esphome/issues#5580]
### The problem

I have tried multiple different json settings but I can't seem to get my AS3935 lightning sensor to be detected by ESPHome.

On Tasmota firmware it worked fine, Loading a generic 'i2c scan' arduino program onto the device (such as [this](https://learn.adafruit.com/scanning-i2c-addresses/arduino)), reliably finds the sensor on 0x03.
![image](https://github.com/esphome/issues/assets/2359847/b1f08c17-57d7-40ac-a5c4-dd04f9d55f56)
![image](https://github.com/esphome/issues/assets/2359847/cbae8701-27b8-426b-bc74-07a3e7412c48)

But ESPHome refuses to detect anything:
![image](https://github.com/esphome/issues/assets/2359847/441509e3-a72b-40ae-ac8f-c019731946c8)

### Which version of ESPHome has the issue?

2024.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.0

### What platform are you using?

ESP8266

### Board

D1 Mini (clone)

### Component causing the issue

i2c

### Example YAML snippet

```yaml
esphome:
  name: lightning-sensor
  friendly_name: Lightning Sensor
esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<redacted>"

ota:
  password: "<redacted>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lightning-Sensor"
    password: "<redacted>"

captive_portal:

i2c:
  sda: D2
  scl: D1
  #Also tried GPIO4/5
  scan: true
  frequency: 100kHz #Tried various speeds, and omitting..

as3935_i2c:
  irq_pin: GPIO13
  indoor: false

sensor:
  - platform: as3935
    lightning_energy:
      name: "Lightning Energy"
    distance:
      name: "Distance Storm"
binary_sensor:
  - platform: as3935
    name: "Storm Alert"
```

### Anything in the logs that might be useful for us?

```txt
Provided in screenshots
```

### Additional information

No external pullups, but I don't believe i should need them because it works with other firmware.
