### ISSUE TITLE
DFRobot I2C Lightning Distance Sensor AS3935/SEN0290 not found

### ISSUE THREAD

**Issue by aver-ua** [esphome/issues#5581]
### The problem

Hi!
DFRobot Lightning Distance Sensor AS3935 not found.
But there is no problem with this board under Tasmota 13.4.0 (sensors)
![as3935_esphome_1](https://github.com/esphome/issues/assets/12016649/66044751-0728-43e3-8130-8072c5e40907)
![as3935_tasmota_1](https://github.com/esphome/issues/assets/12016649/9609b655-3eca-4b29-89a0-0ef5dc4b3c0d)
![as3935_tasmota_2](https://github.com/esphome/issues/assets/12016649/a6975762-e18d-4066-994c-547adcfec13f)
![as3935_tasmota_3](https://github.com/esphome/issues/assets/12016649/f7de58ed-85c5-44f1-8972-fd6d904ff9a5)

### Which version of ESPHome has the issue?

2024.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.0

### What platform are you using?

ESP8266

### Board

NodeMCU v3

### Component causing the issue

I2C

### Example YAML snippet

```yaml
i2c:
  - id: bus_a # as3935
    scl: GPIO14
    sda: GPIO12
    scan: True
    frequency: 400kHz #tried different frequencies and without specifying (default)

as3935_i2c:
  irq_pin: GPIO13
  address: 0x03
  indoor: False

sensor:
  - platform: as3935
    lightning_energy:
      name: "Lightning Energy"
    distance:
      name: "Distance Storm"
binary_sensor:
  - platform: as3935
    name: "Storm Alert"
```

### Anything in the logs that might be useful for us?

```txt
[09:07:09][C][i2c.arduino:053]: I2C Bus:
[09:07:09][C][i2c.arduino:054]:   SDA Pin: GPIO12
[09:07:09][C][i2c.arduino:055]:   SCL Pin: GPIO14
[09:07:09][C][i2c.arduino:056]:   Frequency: 400000 Hz
[09:07:09][C][i2c.arduino:059]:   Recovery: bus successfully recovered
[09:07:09][I][i2c.arduino:069]: Results from i2c bus scan:
[09:07:09][I][i2c.arduino:071]: Found no i2c devices!
```
