### ISSUE TITLE
Substitutins not parsed in !extend

### ISSUE THREAD

**Issue by Masterz69** [esphome/issues#5594]
### The problem

Using packages to define relays in configuration like `sw_relay_1` etc. by passing `${id}` to package.
Trying to create package to extend relays with some functions by using `!extend`.

But discovered - substitutions not parsed while using `!extend` configration.

```yaml
switch:      
  - id: !extend sw_relay_${id}
```
causing
`
  Source for extension of ID 'sw_relay_${id}' was not found.
  id: !extend sw_relay_${id}
`

### Which version of ESPHome has the issue?

2023.12.7

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet
main file:
```yaml
packages:
  config_pulse_${id}: !include
    file: config_pulse.yaml
    vars:
      id: ${id}
  relay_base_${id}: !include
    file: relay_base.yaml
    vars:
      id: ${id}

switch:      
  - id: !extend sw_relay_${id}

...
```
relay_base.yaml:
```yaml
switch:      
  - platform: template
    id: sw_relay_${id}
...
```

**Comment by Masterz69** [comment]
`!extend` can't find source too in following case:

package.yaml:
```yaml
switch:      
  - platform: template
    id: sw_relay_${id}
```
main.yaml
```yaml
packages:
  package: !include { file: package.yaml, vars: { id: 1 } }

switch:
  - id: !extend sw_relay_1
```
