### ISSUE TITLE
Use GP2Y1010AU in Lolin v3 NodeMCU with Esphome

### ISSUE THREAD

**Issue by baozinihao321** [esphome/issues#560]
**Operating environment/Installation (Hass.io):**

**ESP (ESP8266, Board):**

Lolin V3 NodeMCU ESP8266
**Affected component:**

https://esphome.io/components/sensor/adc.html

**Description of problem:**
Hi, I'm new to Esphome and I'm quite confused about how to use a time sequence based air-condition sensor(Sharp GP2Y1010AU/GP2Y1014AU) in Lolin v3 NodeMCU(ESP8266).
It needs to set led pin to LOW and wait 280ms and read the ADC sensor value (A0 in nodemcu) and then change the led pin to HIGH.
I only know how to make the ADC sensor work in a regular interval, but how to add the GPIO output condition to finish the job. If anyone knows the solution, please leave a comment below.
Thanks.

**Problem-relevant YAML-configuration entries:**
```yaml
- platform: adc
    pin: A0
    name: "Dust"
    unit_of_measurement: "mg/m3"
    accuracy_decimals: 8
    filters:
      - lambda: return x * 3.3 * 0.17 - 0.1;
    update_interval: 20ms

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
