### ISSUE TITLE
Inkplate 10 partial update doesn't work

### ISSUE THREAD

**Issue by xaxix** [esphome/issues#5604]
### The problem

My Inkplate 10 does not perform partial updates. A complete screen refresh is performed every time.

### Which version of ESPHome has the issue?

2024.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Never worked

### What platform are you using?

ESP32

### Board

Inkplate 10 (pca6416a)

### Example YAML snippet

```yaml
display:
- platform: inkplate6
  id: inkplate_display_10
  model: inkplate_10
  greyscale: false
  partial_updating: true
  update_interval: 60s
  full_update_every: 30
  rotation: 0°

  ckv_pin: 32
  sph_pin: 33
  gmod_pin:
    pca6416a: pca6416a_hub
    number: 1
  gpio0_enable_pin:
    pca6416a: pca6416a_hub
    number: 8
  oe_pin:
    pca6416a: pca6416a_hub
    number: 0
  spv_pin:
    pca6416a: pca6416a_hub
    number: 2
  powerup_pin:
    pca6416a: pca6416a_hub
    number: 4
  wakeup_pin:
    pca6416a: pca6416a_hub
    number: 3
  vcom_pin:
    pca6416a: pca6416a_hub
    number: 5
```
