### ISSUE TITLE
ESP32-S3 devboard get warnings about microphone and microphone is not working

### ISSUE THREAD

**Issue by n00btotal** [esphome/issues#5605]
### The problem

When installing the YAML i get this:

`INFO ESPHome 2024.2.2
INFO Reading configuration /config/esphome/voicer-two.yaml...
WARNING GPIO3 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-tflite-micro@None
INFO Compiling app...
Processing voicer-two (board: esp32-s3-devkitc-1; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - framework-espidf @ 3.40406.240122 (4.4.6) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- noise-c @ 0.1.4
Compiling .pioenvs/voicer-two/src/esphome/components/api/api_connection.o
Compiling .pioenvs/voicer-two/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/voicer-two/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/voicer-two/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/voicer-two/src/esphome/components/api/api_server.o
Compiling .pioenvs/voicer-two/src/esphome/components/api/list_entities.o
Compiling .pioenvs/voicer-two/src/esphome/components/api/proto.o
Compiling .pioenvs/voicer-two/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/voicer-two/src/esphome/components/api/user_services.o
Compiling .pioenvs/voicer-two/src/esphome/components/binary_sensor/automation.o
Compiling .pioenvs/voicer-two/src/esphome/components/binary_sensor/binary_sensor.o
Compiling .pioenvs/voicer-two/src/esphome/components/binary_sensor/filter.o
Compiling .pioenvs/voicer-two/src/esphome/components/captive_portal/captive_portal.o
Compiling .pioenvs/voicer-two/src/esphome/components/esp32/core.o
Compiling .pioenvs/voicer-two/src/esphome/components/esp32/gpio.o
Compiling .pioenvs/voicer-two/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/voicer-two/src/esphome/components/esp32_rmt_led_strip/led_strip.o
Compiling .pioenvs/voicer-two/src/esphome/components/i2s_audio/i2s_audio.o
Compiling .pioenvs/voicer-two/src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.o
Compiling .pioenvs/voicer-two/src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.o
Compiling .pioenvs/voicer-two/src/esphome/components/light/addressable_light.o
Compiling .pioenvs/voicer-two/src/esphome/components/light/automation.o
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp: In member function 'void esphome::i2s_audio::I2SAudioMicrophone::start_()':
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::chan_mask' [-Wmissing-field-initializers]
   };
   ^
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::total_chan' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::left_align' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::big_edin' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::bit_order_msb' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::skip_msk' [-Wmissing-field-initializers]
Compiling .pioenvs/voicer-two/src/esphome/components/light/esp_color_correction.o
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp: In static member function 'static void esphome::i2s_audio::I2SAudioSpeaker::player_task(void*)':
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::chan_mask' [-Wmissing-field-initializers]
   };
   ^
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::total_chan' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::left_align' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::big_edin' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::bit_order_msb' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::skip_msk' [-Wmissing-field-initializers]`

When I run the code the microphone part is not working. (Almost except for some pins) identical code does works in an ordinary ESP32 (not S3 devboard).

### Which version of ESPHome has the issue?

2024.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.1

### What platform are you using?

ESP32

### Board

YD-ESP32-23  2022 v1.3

### Component causing the issue

i2s_audio i2s_speaker

### Example YAML snippet

```yaml
esphome:
  name: "voicer-two"
  friendly_name: voicer two
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Qq5E8DKeVbdr6YGVNoA6nZl+0l/iAMVt4MILlISOyy4="

ota:
  password: "8e39f15b437d9ec527c0bb9dbdc86212"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Voicer-One Fallback Hotspot"
    password: "T47DTHYGknv4"

captive_portal:


micro_wake_word:
  model: okay_nabu
  on_wake_word_detected:
    - voice_assistant.start

i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO3
    i2s_bclk_pin: GPIO2
  - id: i2s_out
    i2s_lrclk_pin: GPIO6
    i2s_bclk_pin: GPIO20

microphone:
  - platform: i2s_audio
    adc_type: external
    pdm: false
    id: mic_i2s
    channel: right
    bits_per_sample: 32bit
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO4  #SD Pin from the INMP441 Microphone

speaker:
  - platform: i2s_audio
    i2s_audio_id: i2s_out
    id: assistant_media_player
    dac_type: external
    i2s_dout_pin: GPIO8
    mode: mono


voice_assistant:
  microphone: mic_i2s
  id: va
  noise_suppression_level: 3
  auto_gain: 31dBFS
  volume_multiplier: 2
  use_wake_word: false
  speaker: assistant_media_player
  on_wake_word_detected: 
    - light.turn_on:
        id: led_light
  on_listening: 
    - light.turn_on:
        id: led_light
        effect: "Scan Effect With Custom Values"
        red: 63%
        green: 13%
        blue: 93%
  on_stt_end:
    - light.turn_on:
        id: led_light
        effect: "None"
        red: 0%
        green: 100%
        blue: 0%
  on_error: 
    - light.turn_on:
        id: led_light
        effect: "None"
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - switch.turn_off: use_wake_word
          - delay: 1sec 
          - switch.turn_on: use_wake_word      
  on_client_connected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - micro_wake_word.start
  on_client_disconnected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - micro_wake_word.stop
          - voice_assistant.stop:

binary_sensor:
  - platform: status
    name: API Connection
    id: api_connection
    filters:
      - delayed_on: 1s
    on_press:
      - if:
          condition:
            switch.is_on: use_wake_word
          then:
            - micro_wake_word.start
    on_release:
      - if:
          condition:
            switch.is_on: use_wake_word
          then:
            - micro_wake_word.stop
            - voice_assistant.stop:


switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - lambda: id(va).set_use_wake_word(true);
      - if:
          condition:
            not:
              - voice_assistant.is_running
          then:
            - micro_wake_word.start
    on_turn_off:
      - voice_assistant.stop
      - micro_wake_word.stop
      - lambda: id(va).set_use_wake_word(false);

light:
  - platform: esp32_rmt_led_strip
    rmt_channel: 0
    chipset: WS2812
    rgb_order: GRB
    id: led_light
    pin: GPIO17      # DIN pin of the LED Strip
    num_leds: 9      # change the Number of LEDS according to your LED Strip.
    name: "Light"
    default_transition_length: 0.5s
    effects:
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 50ms
          scan_width: 2
```

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp: In member function 'void esphome::i2s_audio::I2SAudioMicrophone::start_()':
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::chan_mask' [-Wmissing-field-initializers]
   };
   ^
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::total_chan' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::left_align' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::big_edin' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::bit_order_msb' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp:62:3: warning: missing initializer for member 'i2s_driver_config_t::skip_msk' [-Wmissing-field-initializers]
Compiling .pioenvs/voicer-two/src/esphome/components/light/esp_color_correction.o
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp: In static member function 'static void esphome::i2s_audio::I2SAudioSpeaker::player_task(void*)':
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::chan_mask' [-Wmissing-field-initializers]
   };
   ^
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::total_chan' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::left_align' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::big_edin' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::bit_order_msb' [-Wmissing-field-initializers]
src/esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp:56:3: warning: missing initializer for member 'i2s_driver_config_t::skip_msk' [-Wmissing-field-initializers]
```
