### ISSUE TITLE
EspHome not update firmware with config changes

### ISSUE THREAD

**Issue by MiguelAngelLV** [esphome/issues#5609]
### The problem

I am using EspHome 2024.2.2  and, sometimes, when I change any configuration and update my device,  the firmware create use old configurare, maybe cache.

The sensors is commented in the config but, after install (wireless or usb) the are present in the firmware. I try use clean, but the problem persists.

I try use other empty ESP32, but esphome install the old version of my firmware.

The only way to update is create a new esphome config with another name, copy the config and install it.

### Which version of ESPHome has the issue?

2024.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.1

### What platform are you using?

ESP32

### Board

lolin32lite

### Example YAML snippet

```yaml
esphome:
  name: piscinaph
  friendly_name: piscinaph

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "8tWlYanRxb1chkwZzAJqc/VlJws8JA0QY2kpdegXlpo="

ota:
  password: "76164a9bdeb76650adaf1f4f567e2041"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Piscinaph Fallback Hotspot"
    password: "O3mO8fKRykgD"

captive_portal:
    

uart:
  tx_pin: GPIO32
  rx_pin: GPIO33
  baud_rate: 115200

tuya:


# sensor:
#   - platform: tuya
#     sensor_datapoint: 8
#     name: Temperatura
#     device_class: temperature
#     filters: 
#       - multiply: 0.1
#   - platform: tuya
#     sensor_datapoint: 106
#     name: pH
#     device_class: ph
#     filters: 
#       - multiply: 0.01
#   - platform: tuya
#     sensor_datapoint: 111
#     name: TDS
#     unit_of_measurement: ppm
#   - platform: tuya
#     sensor_datapoint: 131
#     name: ORP
#     unit_of_measurement: mV
#   - platform: tuya
#     sensor_datapoint: 136
#     name: Conductividad
#     unit_of_measurement: ms
#     filters: 
#       multiply: 0.01
#   - platform: tuya
#     name: Sal
#     sensor_datapoint: 116
#     unit_of_measurement: ppm
```
