### ISSUE TITLE
2024.3.0 fails to compile in logger component

### ISSUE THREAD

**Issue by vladm** [esphome/issues#5612]
### The problem

works ok with 2024.2.x, after pulling new images for 2024.3, config fails to compile.

### Which version of ESPHome has the issue?

2024.3.0, 2024.3.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32-c6-devkitc-1

### Component causing the issue

logger

### Example YAML snippet

```yaml
esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.1.3
    source: https://github.com/tasmota/esp-idf/releases/download/v5.1.3.240313/esp-idf-v5.1.3.zip
    platform_version: https://github.com/platformio/platform-espressif32

logger:
  level: DEBUG

debug:
  update_interval: 10s


i2c:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".home.lan"
  enable_rrm: true
  enable_btm: true
  reboot_timeout: 5min
  power_save_mode: none

sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name:  WiFi Signal
    update_interval: 60s

switch:
  - platform: gpio
    pin:
      number: GPIO20
      inverted: false
    name: Strike
    id: strike
    on_turn_on:
    - delay: 333ms
    - switch.turn_off: strike

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
```

### Anything in the logs that might be useful for us?

```txt
....
Compiling .pioenvs/test/src/esphome/components/wifi/wifi_component.o
src/esphome/components/logger/logger_esp32.cpp: In member function 'void esphome::logger::Logger::pre_setup()':
src/esphome/components/logger/logger_esp32.cpp:120:12: error: enumeration value 'UART_SELECTION_USB_CDC' not handled in switch [-Werror=switch]
  120 |     switch (this->uart_) {
      |            ^
Compiling .pioenvs/test/src/esphome/components/wifi/wifi_component_esp32_arduino.o
Compiling .pioenvs/test/src/esphome/components/wifi/wifi_component_esp8266.o
Compiling .pioenvs/test/src/esphome/components/wifi/wifi_component_esp_idf.o
cc1plus: some warnings being treated as errors
*** [.pioenvs/test/src/esphome/components/logger/logger_esp32.o] Error 1
==================================================================== [FAILED] Took 27.37 seconds ====================================================================
Total reclaimed space: 0B
```

**Comment by DAVe3283** [comment]
This should be fixed by esphome/esphome#6323 which should be included in 2024.3.1 when that comes out.

**Comment by vladm** [comment]
same for me - still fails as shown above by @jkremlacek

**Comment by mastersf** [comment]
same errors, as before. This fix didn't work

**Comment by DAVe3283** [comment]
It looks like the 2024.3.1 release didn't include esphome/esphome#6323. It was merged to dev a while back, so it will either get picked for 2024.3.2 (hopefully) or eventually be in 2024.4.0.

You should be able to use the dev version of ESPHome as a workaround for now.

**Comment by ssieb** [comment]
Or use the PR as an external component.

**Comment by pepijndevos** [comment]
The following works for me, but if I update to newer version I get an error that the logger tries to convert an int to an uart type

```
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.1.3
    source: https://github.com/tasmota/esp-idf/releases/download/v5.1.3.240313/esp-idf-v5.1.3.zip
    platform_version: 6.5.0
```

**Comment by jjcszxh** [comment]
esphome3.1，
In file included from src/esphome/components/esp32_rmt_led_strip/led_strip.h:12,
                 from src/esphome/components/esp32_rmt_led_strip/led_strip.cpp:2:
/config/.esphome/platformio/packages/framework-espidf/components/driver/deprecated/driver/rmt.h:18:2: warning: #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h" [-Wcpp]
   18 | #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"
      |  ^~~~~~~
Compiling .pioenvs/esp32-c6/src/esphome/components/switch/switch.o
Compiling .pioenvs/esp32-c6/src/esphome/components/text_sensor/filter.o
src/esphome/components/logger/logger_esp32.cpp: In member function 'void esphome::logger::Logger::pre_setup()':
src/esphome/components/logger/logger_esp32.cpp:120:12: error: enumeration value 'UART_SELECTION_USB_CDC' not handled in switch [-Werror=switch]
  120 |     switch (this->uart_) {
      |            ^
Compiling .pioenvs/esp32-c6/src/esphome/components/text_sensor/text_sensor.o
Compiling .pioenvs/esp32-c6/src/esphome/components/uptime/uptime_sensor.o
cc1plus: some warnings being treated as errors
*** [.pioenvs/esp32-c6/src/esphome/components/logger/logger_esp32.o] Error 1
========================= [FAILED] Took 46.36 seconds =========================

**Comment by DAVe3283** [comment]
As ssieb mentioned, to fix the logger error before 2024.4.0 comes out, you need to use the PR as an external component to get the changes:

```yaml
# Until ESPHome 2024.4.0 (https://github.com/esphome/esphome/pull/6323)
external_components:
  - source: github://pr#6323
    components: [ logger ]
```

**Comment by jkremlacek** [comment]
Confirming compilation works again with 2024.3.2. Thank you for the fix @DAVe3283

**Comment by vladm** [comment]
hmm @jkremlacek  for some reason I cant complete 2024.3.2, now it fails at the very end of build process: 

`
Building .pioenvs/esp32c6-2/firmware.bin
Creating esp32c6 image...

A fatal error occurred: Contents of segment at SHA256 digest offset 0xb0 are not all zero. Refusing to overwrite.
*** [.pioenvs/esp32c6-2/firmware.bin] Error 2
================================================ [FAILED] Took 84.20 seconds ================================================
Total reclaimed space: 0B
`

my config 
`
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.1.3
    source: https://github.com/tasmota/esp-idf/releases/download/v5.1.3.240325/esp-idf-v5.1.3.zip
    platform_version: 6.5.0
`

**Comment by DAVe3283** [comment]
@vladm I ran into that bug a long while back on the ESP32-C6 but that was fixed (at least for me) in recent ESP-IDF frameworks. (e.g. espressif/esp-idf#7160)

There are [other reports](https://community.platformio.org/t/esp32-c6-espidf-error-when-using-components-folder-led-strip-h/37006) that a flash size mismatch can cause this.

I am able to compile with the exact framework you list. Try cleaning your build files and compiling again. If that doesn't work, make sure your flash size is set right, as a lot of ESP32-C6 stuff is not fully baked yet. Here is my config, take not of all the nonsense needed to get flash size correct:

```yaml
esphome:
  name: soda-fountain
  friendly_name: Soda Fountain
  comment: Soda Fountain Controller
  # OLIMEX ESP32-C6-EVB
  # Claims 512K RAM, 4MB flash
  # platformio esp32-c6-devkitm-1 claims 320K RAM which appears wrong per the datasheet
  # platformio esp32-c6-devkitc-1 has RAM right, but has 8MB flash, we actually have 4MB
  platformio_options:
    board_upload.maximum_size: 4194304
  min_version: "2024.3.2" # Fix logger compile error on ESP32-C6 esphome#6323

esp32:
  board: esp32-c6-devkitc-1 # at least until https://github.com/platformio/platform-espressif32/issues/1152 is added
  variant: esp32c6          # ditto ↑
  flash_size: 4MB # upload.flash_size
  framework:
    type: esp-idf
    platform_version: 6.5.0 # Need at least 6.4 for ESP32-C6

    # Tasmota's release of 5.1.3 works, first-party release does not LOL
    version: 5.1.3
    source: https://github.com/tasmota/esp-idf/releases/download/v5.1.3.240325/esp-idf-v5.1.3.zip

    # Fix flash size by ensuring IDF flash size is also set (was defaulting to 2MB?!?)
    # See https://github.com/esphome/issues/issues/5404
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
```

But either way, that appears to be an ESP-IDF or PlatformIO bug, not a ESPHome issue. Unless it is actually caused by esphome/issues#5404, but the workaround is shown above.

**Comment by vladm** [comment]
Thank you so much @DAVe3283 . Adding the below line fixed the issue for me (i have 8MB version). 
Odd that it wasn't needed in 2024.2.x versions.

```
  framework:
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
```

**Comment by mcmx** [comment]
I'm running ESPHOME 2024.4.0 this is working for me, in my case I'm using **esp32-c6-devkitm-1**, thanks @DAVe3283 

```
esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    platform_version: 6.5.0
    version: 5.1.3
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
```
