### ISSUE TITLE
Warning in log : comparison is always true due to limited range of data type [-Wtype-limits]

### ISSUE THREAD

**Issue by github-k8n** [esphome/issues#5615]
### The problem

```
src/esphome/components/wifi/wifi_component_esp_idf.cpp: In member function 'esphome::wifi::WiFiSTAConnectStatus esphome::wifi::WiFiComponent::wifi_sta_connect_status_()':
src/esphome/components/wifi/wifi_component_esp_idf.cpp:751:35: warning: comparison is always true due to limited range of data type [-Wtype-limits]
     if (this->num_ipv6_addresses_ >= USE_NETWORK_MIN_IPV6_ADDR_COUNT) {
```

```
/data/cache/platformio/packages/framework-espidf/components/wpa_supplicant/esp_supplicant/src/esp_common.c:571:16: warning: 'get_operating_class_ie' defined but not used [-Wunused-function]
 static uint8_t get_operating_class_ie(uint8_t *ie, size_t len)
                ^~~~~~~~~~~~~~~~~~~~~~
```

So far everything looks ok, devices get IPv4 and three IPv6 addresses. Just the two warning in the log.. not sure if they are benign or if they might have already been there in previous versions... 

### Which version of ESPHome has the issue?

2024.3.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

wemos_d1_mini32

### Example YAML snippet

```yaml
yaml:

INFO ESPHome 2024.3.0
INFO Reading configuration /config/esphome/esp-bt-fa2679.yaml...
substitutions:
  wifi_ssid: XXX
  wifi_password: XXX
  api_password: XXX
  api_key: XXX
  devicename: esp-bt-fa2679
  description: ESP32 Bluetooth Proxy DG
  ota_pw: XXX
  ap_pw: XXX
  api_device_key: XXX
  target_bssid: 2C:91:AB:B5:B4:77
esphome:
  name: esp-bt-fa2679
  comment: ESP32 Bluetooth Proxy DG
  build_path: build/esp-bt-fa2679
  friendly_name: ''
  area: ''
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
  min_version: 2024.3.0
esp32:
  board: wemos_d1_mini32
  framework:
    version: 4.4.6
    sdkconfig_options: {}
    advanced:
      ignore_efuse_mac_crc: false
    components: []
    source: ~3.40406.0
    platform_version: platformio/espressif32@5.4.0
    type: esp-idf
  flash_size: 4MB
  variant: ESP32
wifi:
  reboot_timeout: 0s
  power_save_mode: HIGH
  networks:
  - ssid: XXX
    password: XXX
    priority: 0.0
  - ssid: XXX
    bssid: 2C:91:AB:B5:B4:77
    password: XXX
    priority: 4.0
  ap:
    password: XXX
    ap_timeout: 1min
  enable_btm: true
  enable_rrm: true
  domain: .local
  fast_connect: false
  passive_scan: false
  enable_on_boot: true
  use_address: esp-bt-fa2679.local
network:
  enable_ipv6: true
  min_ipv6_addr_count: 0
binary_sensor:
- platform: template
  name: esp-bt-fa2679 connected to target AP
  id: wifi_target_ap
  entity_category: diagnostic
  disabled_by_default: false
text_sensor:
- platform: wifi_info
  bssid:
    name: esp-bt-fa2679 wifi connected bssid
    id: wifi_bssid
    entity_category: diagnostic
    on_value:
    - then:
      - if:
          condition:
            text_sensor.state:
              id: wifi_bssid
              state: 2C:91:AB:B5:B4:77
          then:
          - binary_sensor.template.publish:
              id: wifi_target_ap
              state: true
          else:
          - binary_sensor.template.publish:
              id: wifi_target_ap
              state: false
    disabled_by_default: false
    update_interval: 1s
interval:
- interval: 1min
  then:
  - if:
      condition:
        for:
          time: 10min
          condition:
            binary_sensor.is_off:
              id: wifi_target_ap
      then:
      - button.press:
          id: button_restart
  startup_delay: 0s
api:
  encryption:
    key: XXX
  port: 6053
  password: ''
  reboot_timeout: 15min
ota:
  password: XXX
  safe_mode: true
  version: 2
  port: 3232
  reboot_timeout: 5min
  num_attempts: 10
logger:
  baud_rate: 0
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
sensor:
- platform: wifi_signal
  name: esp-bt-fa2679 wifi signal db
  id: wifi_signal_db
  update_interval: 60s
  entity_category: diagnostic
  disabled_by_default: false
  force_update: false
  unit_of_measurement: dBm
  accuracy_decimals: 0
  device_class: signal_strength
  state_class: measurement
button:
- platform: restart
  name: esp-bt-fa2679 restart
  id: button_restart
  disabled_by_default: false
  entity_category: config
  device_class: restart
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
    duration: 5min
    continuous: true
bluetooth_proxy:
  active: true
  cache_services: true
  connections:
  - {}
  - {}
  - {}

INFO Configuration is valid!



Log:
INFO ESPHome 2024.3.0
INFO Reading configuration /config/esphome/esp-bt-fa2679.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp-bt-fa2679 (board: wemos_d1_mini32; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/noise-c @ 0.1.4
INFO Installing esphome/noise-c @ 0.1.4
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.4 has been installed!
INFO noise-c@0.1.4 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10018.1
INFO Installing esphome/libsodium @ 1.10018.1
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10018.1 has been installed!
INFO libsodium@1.10018.1 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40406.240122 (4.4.6) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- noise-c @ 0.1.4

[..]

Compiling .pioenvs/esp-bt-fa2679/src/esphome/components/wifi_info/wifi_info_text_sensor.o
Compiling .pioenvs/esp-bt-fa2679/src/esphome/components/wifi_signal/wifi_signal_sensor.o
src/esphome/components/wifi/wifi_component_esp_idf.cpp: In member function 'esphome::wifi::WiFiSTAConnectStatus esphome::wifi::WiFiComponent::wifi_sta_connect_status_()':
src/esphome/components/wifi/wifi_component_esp_idf.cpp:751:35: warning: comparison is always true due to limited range of data type [-Wtype-limits]
     if (this->num_ipv6_addresses_ >= USE_NETWORK_MIN_IPV6_ADDR_COUNT) {
Compiling .pioenvs/esp-bt-fa2679/src/esphome/core/application.o

[..]

Compiling .pioenvs/esp-bt-fa2679/wpa_supplicant/esp_supplicant/src/esp_common.o
Compiling .pioenvs/esp-bt-fa2679/wpa_supplicant/esp_supplicant/src/esp_wpa2.o
Compiling .pioenvs/esp-bt-fa2679/wpa_supplicant/esp_supplicant/src/esp_wpa_main.o
Compiling .pioenvs/esp-bt-fa2679/wpa_supplicant/esp_supplicant/src/esp_wpas_glue.o
/data/cache/platformio/packages/framework-espidf/components/wpa_supplicant/esp_supplicant/src/esp_common.c:571:16: warning: 'get_operating_class_ie' defined but not used [-Wunused-function]
 static uint8_t get_operating_class_ie(uint8_t *ie, size_t len)
                ^~~~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs/esp-bt-fa2679/wpa_supplicant/esp_supplicant/src/esp_wps.o
Compiling .pioenvs/esp-bt-fa2679/wpa_supplicant/esp_supplicant/src/esp_wpa3.o
Compiling .pioenvs/esp-bt-fa2679/wpa_supplicant/esp_supplicant/src/esp_hostap.o
Compiling .pioenvs/esp-bt-fa2679/wpa_supplicant/src/crypto/tls_mbedtls.o

[..]

Linking .pioenvs/esp-bt-fa2679/firmware.elf
RAM:   [==        ]  17.0% (used 55556 bytes from 327680 bytes)
Flash: [========  ]  75.1% (used 1377433 bytes from 1835008 bytes)
Building .pioenvs/esp-bt-fa2679/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
```
