### ISSUE TITLE
heltec_wifi_kit_32_v2 i2c issues after 2023.11.0

### ISSUE THREAD

**Issue by viotemp1** [esphome/issues#5617]
### The problem

After 2023.11.0, I cannot compile anymore. The issues are related to Pin xx is used in multiple places.

The config with pin 4 & 15 is working fine with 2023.11.0.
I tried the following:
```
i2c:
    sda: 
      number: 4
      allow_other_uses: true
    scl: 
      number: 15
      allow_other_uses: true
    frequency: 800kHz
    scan: True
    id: ${roomname}_i2c_bus
```
and the error is Pin 4 is used in multiple places. and Pin 15 is used in multiple places.
I tried also commenting sda/scl and, but is not compiling also:
```
i2c:
    # sda: 
    #   number: 4
    #   allow_other_uses: true
    # scl: 
    #   number: 15
    #   allow_other_uses: true
    frequency: 800kHz
    scan: True
    id: ${roomname}_i2c_bus
```
Error: Pin 21 is used in multiple places and Pin 22 is used in multiple places. I do not use 21 and 22 anywhere in my config.

### Which version of ESPHome has the issue?

2024.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.0

### What platform are you using?

ESP32

### Board

Heltec WiFi Kit 32

### Component causing the issue

i2c

### Example YAML snippet

```yaml
i2c:
    sda: 
      number: 4
      allow_other_uses: true
    scl: 
      number: 15
      allow_other_uses: true
    frequency: 800kHz
    scan: True
    id: ${roomname}_i2c_bus
```
