### ISSUE TITLE
[ESP32-C3] ESPHome touch wakeup function missing set_touch_wakeup

### ISSUE THREAD

**Issue by JustEnoughDucks** [esphome/issues#5620]
### The problem

Hello, I am trying to make a simple doorbell that deep sleeps constantly, wakes up when the doorbell is pressed, lights an LED, measures the battery, sends a button press + battery level to Home Assistant, then fades the LED and returns to sleep.

I am getting a strange error that it is simply missing the `set_touch_wakeup` member. How can this be? This code is used across dozens of installations. Is there a fundamental incompatibility with the ESP32-C3. I found an old issue about it not being supported, but there was a fix merged in 2022.

### Which version of ESPHome has the issue?

2024.2.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

NA

### What platform are you using?

ESP32

### Board

SEEED Xiao ESP32-C3

### Component causing the issue

deep sleep

### Example YAML snippet

```yaml
on_boot:
    - priority: -100
      then: # At this priority, pretty much everything should already be initialized.
        - logger.log: "Starting sensor updates..."
        - binary_sensor.template.publish:
            id: doorbell_pressed
            state: ON
        - output.turn_on: meas_gnd
        - repeat:
            count: 3
            then:
              #Sensor updates are turned off and manually requested on boot. 
              #Then the ESP goes back to sleep when they're done (unless told to stay awake)

              # Request sensor updates
              - component.update: LIION
              - delay: 100ms
              - component.update: bat_v
              - component.update: bat_percent
        - output.turn_off: meas_gnd

  on_shutdown:
    priority: -100
    then:
      - if:
          condition:
            - binary_sensor.is_on: battery_updated
          then:
            - logger.log: "Data from all bettery received"
          else:
            - logger.log: "Battery update missing"

      # Reset data update sensors states
      - binary_sensor.template.publish:
          id: battery_updated
          state: OFF

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Deep sleep configuration
deep_sleep:
  run_duration: 3s
  touch_wakeup: True
  wakeup_pin: 
    number: 2
    mode: 
      input: True
      output: False
      open_drain: False
      pullup: False
      pulldown: True
    inverted: False
    ignore_strapping_warning: False
    drive_strength: 20.0
  id: sleep_routine

```

### Anything in the logs that might be useful for us?

```txt
/config/dumb-doorbell.yaml: In function 'void setup()':
/config/dumb-doorbell.yaml:244:18: error: 'class esphome::deep_sleep::DeepSleepComponent' has no member named 'set_touch_wakeup'; did you mean 'touch_wakeup_'?
```
