### ISSUE TITLE
LAN8720: 'esp_eth_mac_new_esp32' was not declared in this scope

### ISSUE THREAD

**Issue by anhorbc** [esphome/issues#5625]
### The problem

When trying to add a LAN8720 module to a ESP32-C3 the compiler fails with the following message:
src/esphome/components/ethernet/ethernet_component.cpp: In member function 'virtual void esphome::ethernet::EthernetComponent::setup()':
src/esphome/components/ethernet/ethernet_component.cpp:129:24: error: 'esp_eth_mac_new_esp32' was not declared in this scope
   esp_eth_mac_t *mac = esp_eth_mac_new_esp32(&mac_config);
                        ^~~~~~~~~~~~~~~~~~~~~
src/esphome/components/ethernet/ethernet_component.cpp:129:24: note: suggested alternative: 'esp_eth_mac_new_w5500'
   esp_eth_mac_t *mac = esp_eth_mac_new_esp32(&mac_config);
                        ^~~~~~~~~~~~~~~~~~~~~
                        esp_eth_mac_new_w5500
*** [.pioenvs/esp32-water/src/esphome/components/ethernet/ethernet_component.cpp.o] Error 1

### Which version of ESPHome has the issue?

2024.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.1

### What platform are you using?

ESP32

### Board

ESP32-C3-Supermini

### Component causing the issue

Ethernet

### Example YAML snippet

```yaml
esphome:
  name: esp32-c3
  friendly_name: ESP32-C3

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  password: "xxx"

ethernet:
  type: LAN8720
  mdc_pin: GPIO05
  mdio_pin: GPIO04
  clk_mode: GPIO0_OUT
  phy_addr: 0
```
