### ISSUE TITLE
ac_dimmer  multiple zero_cross_pin issue

### ISSUE THREAD

**Issue by fre69** [esphome/issues#5633]
### The problem

When we have 2 or 4 ways module we have only 1 zero cross pin but we need to repeat 

### Which version of ESPHome has the issue?

2024.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.3

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

ac_dimmer

### Example YAML snippet

```yaml
output:
  - platform: ac_dimmer
    id: dimmer1
    method: leading pulse
    gate_pin: GPIO26
    zero_cross_pin: GPIO33
  - platform: ac_dimmer
    id: dimmer2
    method: leading pulse
    gate_pin: GPIO27
    zero_cross_pin: GPIO33
```

### Anything in the logs that might be useful for us?

```txt
Esphome don't want to compile because it detect pin already used, but it's what we must do in this case.
The message is  Pin 33 is used in multiple places.
```
