### ISSUE TITLE
waveshare_epaper driver 2.90inv2-r2

### ISSUE THREAD

**Issue by ToViNi** [esphome/issues#5651]
### The problem

This driver fixes display problems with my WeACT displays, but when used with 270 deg rotation, the display image is mirrored in x axes.

### Which version of ESPHome has the issue?

2024.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.3

### What platform are you using?

ESP32

### Board

dev

### Component causing the issue

2.90inv2-r2

### Example YAML snippet

```yaml
display:
  - platform:  waveshare_epaper
    model:     2.90inv2-r2
    rotation:  270°
```

### Additional information

2.90inv2 displays correct
