### ISSUE TITLE
how to use media_player.i2s_audio on the IDF Plattform?

### ISSUE THREAD

**Issue by pimp1310** [esphome/issues#5653]
### The problem

Hello,

i tried to add the media_player to my ESP32 Wroom32 with the IDF Plattform. but i always get the error its only supported under Adruino....

### Which version of ESPHome has the issue?

2024.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.3

### What platform are you using?

ESP32-IDF

### Board

ESP32 Wroom 32

### Component causing the issue

media_player / i2s_audio

### Example YAML snippet

```yaml
# Example configuration entry
media_player:
  - platform: i2s_audio
    id: external_speaker
    dac_type: external
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO33
    mode: mono
```
