### ISSUE TITLE
on_turn_off fires after a REST turn_off, even if it was already turned off

### ISSUE THREAD

**Issue by samuelalexmclean** [esphome/issues#5658]
### Background

I'm trying to sync up two smart light switches (one which legitimately controls an outdoor light, and another which isn't actually connected to anything - back when I had dumb switches, these were wired together for a classic multiway switching setup).

Because I'm insane I'm trying to do this with peer to peer http_request calls (so my lights will keep working if HA / MQTT goes offline, so long as the router stays up). This was a neat property of the device_groups feature in Tasmota. I'm aware there's an unofficial port of this for ESPHome but I'm trying to keep my install clean.

### Problem

I thought this would be as simple as the following code on the master switch `.21` talking to the slave `.20`.
```
light:
  - platform: binary
    name: "Foyer Light"
    output: relay4
    id: light4
    on_turn_on:
    - http_request.post: "http://192.168.0.20/light/foyer_light/turn_on"
    on_turn_off:
    - http_request.post: "http://192.168.0.20/light/foyer_light/turn_off"
```
The subordinate would then have the same setup, but making an http_request to `.21` instead of `.20`.

The problem here (from observation, I haven't read the code) is that on_turn_off is triggered every time a device receives a turn_off instruction, **regardless of whether the device took any action**. I had imagined a device that was turned off, when receiving an off command, would do nothing (since the state hasn't actually changed). But it will send an off command to the other device, which will send an off command back, so on ad infinitum. This is worse than just spamming the network because (if I physically interact with the switch) the little bit of latency is enough for the two to get madly out of sync, so they'll start sending ons and offs back and forth in a frantic game of ping pong that turns my house into a disco.

I am puzzling my way through a solution for this, where each light makes two calls: first, it GETs the actual state of the remote, then only issues the POST if it's actually going to have an effect. But I thought the behaviour of the API here was surprising, and am curious to know if it's WAI (or if there is some other, much more obvious way to do this).

### Which version of ESPHome has the issue?

Latest

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Latest

### What platform are you using?

ESP8266
