### ISSUE TITLE
Call on_turn_on with restore_mode

### ISSUE THREAD

**Issue by Anonym-tsk** [esphome/issues#566]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Docker

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP8266

**Affected component:** GPIO Output, GPIO Switch

**Description of problem:**
I want to make LED indicator of relay. Turn on LED if relay is turned on.
I configured `on_turn_on` action of `switch` to turn on led. But if i use `restore_mode: RESTORE_DEFAULT_ON`, `on_turn_on` is not called on start and led is off.

**Problem-relevant YAML-configuration entries:**
```yaml
output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led

switch:
  - platform: gpio
    pin: GPIO15
    id: relay
    name: 'Relay'
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by glmnet** [comment]
I wouldn't expect it to work that way.

You could have a [on_boot](https://esphome.io/components/esphome.html#on-boot) automation for that.

**Comment by Anonym-tsk** [comment]
But i think, it's trivial and needed feature.
We have `interlock`, but don't have `lock`.

**Comment by glmnet** [comment]
The default option is `RESTORE_DEFAULT_OFF`
do you think the `on_turn_off` should be called in the case it turned off when it "restores" ?

**Comment by Anonym-tsk** [comment]
Well, maybe `restore_mode` for output component is better solution?

**Comment by glmnet** [comment]
in that case you can use the already available restore mode for light (your LED is a light)

```yaml
light:
  - platform: binary
    id: led
    restore_mode: RESTORE_DEFAULT_ON
    output: output_gpio0 # you'll have to rename the id of the output to this
````
