### ISSUE TITLE
XPT2046 Touchscreen Calibration Issue

### ISSUE THREAD

**Issue by nbartzeliotis** [esphome/issues#5660]
### The problem

XPT2046 Touchscreen Calibration is off in 2024.3.1 and doesn't work as expected.

Even after a fresh calibration it looks like only a portion of the screen is used and some areas cannot be used. 
I used the following code to test the calibration. 

```
auto touch = id(my_touchscreen)->get_touch();
if (touch) {
  auto red = Color(255, 0, 0);
  it.filled_circle(touch.value().x, touch.value().y, 10, red);
}
```

I've played around with the transform options and just leaving swap_xy set to true seems to be the best config. 

When sliding a stylus to the right of the display I see the y_raw value increasing whilst I was expecting x_raw to increase.
This is because x is increasing as well and not y. 
Likewise, when sliding the stylus from top to bottom, I see x_raw increasing whilst expecting y_raw to increase as y is increasing and not x. 

Can someone do a quick check in case x_raw has been swapped with y_raw somewhere? 
Happy to provide more info if this doesn't make much sense.
![image](https://github.com/esphome/issues/assets/36970791/cd1db853-1a46-4e57-bb66-9d3d3abd374b)

### Which version of ESPHome has the issue?

2024.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.3

### What platform are you using?

ESP32

### Board

TTGO T-Call V1.3 ESP32

### Component causing the issue

xpt2046

### Example YAML snippet

```yaml
touchscreen:
  platform: xpt2046
  id: my_touchscreen
  cs_pin: 12
  calibration:
    x_min: 178
    x_max: 3748
    y_min: 275
    y_max: 3924
  transform:
    swap_xy: true
  update_interval: 50ms
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );
```
