### ISSUE TITLE
NS Panel Wifi not connected

### ISSUE THREAD

**Issue by minimag450** [esphome/issues#5662]
### The problem

I have an NS panel that worked more than a year ago on a different Fritzbox and with an older version of ESPHome. Now I've built a house and redone everything. I have a different Fritzbox, changed the IP_addresses, Homeassistant and also updated ESPHome. Now I wanted to flash the NS panel with the current version of Blackymaas. But it does not work. I install everything on the connected computer via the ESPHome web interface. Connect works and at the end it also says that the download was successful. But I don't get a log file. If I then click on the 3 dots on the right next to ESP-Device in the web interface, the message "An error occurred. Improv Wi-Fi Serial not detected".

### Which version of ESPHome has the issue?

2024.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.2

### What platform are you using?

ESP32

### Board

NS-Panel

### Example YAML snippet

```yaml
substitutions:
  # Settings - Editable values
  device_name: "ns-panel-eingang-neu"
  friendly_name: "NS Panel Eingang Neu"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
#  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  nextion_update_url: http://homeassistant:8123/local/nspanel_blank.tft
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s
```

### Anything in the logs that might be useful for us?

```txt
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6652
ho 0 tail 12 room 4
load:0x40078000,len:15060
load:0x40080400,len:3836
entry 0x4008069c
I (29) boot: ESP-IDF 4.4.6 2nd stage bootloader
I (29) boot: compile time 12:41:32
I (29) boot: Multicore bootloader
I (32) boot: chip revision: v3.0
I (36) boot.esp32: SPI Speed      : 40MHz
I (41) boot.esp32: SPI Mode       : DIO
I (45) boot.esp32: SPI Flash Size : 4MB
I (50) boot: Enabling RNG early entropy source...
I (55) boot: Partition Table:
I (59) boot: ## Label            Usage          Type ST Offset   Length
I (66) boot:  0 otadata          OTA data         01 00 00009000 00002000
I (74) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (81) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (89) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (96) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (104) boot: End of partition table
I (108) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=31e40h (204352) map
I (190) esp_image: segment 1: paddr=00041e68 vaddr=3ffb0000 size=02fbch ( 12220) load
I (195) esp_image: segment 2: paddr=00044e2c vaddr=40080000 size=0b1ech ( 45548) load
I (215) esp_image: segment 3: paddr=00050020 vaddr=400d0020 size=d2a78h (862840) map
I (527) esp_image: segment 4: paddr=00122aa0 vaddr=4008b1ec size=097ach ( 38828) load
I (553) boot: Loaded app from partition at offset 0x10000
I (553) boot: Disabling RNG early entropy source...
I (565) cpu_start: Multicore app
I (565) cpu_start: Pro cpu up.
I (565) cpu_start: Starting app cpu, entry point is 0x40081e70
I (0) cpu_start: App cpu up.
I (583) cpu_start: Pro cpu start user code
I (583) cpu_start: cpu freq: 160000000
I (583) cpu_start: Application information:
I (588) cpu_start: Project name:     ns-panel-eingang
I (594) cpu_start: App version:      2024.3.0
I (599) cpu_start: Compile time:     Apr  1 2024 12:38:35
I (605) cpu_start: ELF file SHA256:  dd5d6d5560ce837b...
I (611) cpu_start: ESP-IDF:          4.4.6
I (615) cpu_start: Min chip rev:     v0.0
I (620) cpu_start: Max chip rev:     v3.99 
I (625) cpu_start: Chip rev:         v3.0
I (630) heap_init: Initializing. RAM available for dynamic allocation:
I (637) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (643) heap_init: At 3FFB8870 len 00027790 (157 KiB): DRAM
I (649) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (655) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (662) heap_init: At 40094998 len 0000B668 (45 KiB): IRAM
I (670) spi_flash: detected chip: generic
I (673) spi_flash: flash io: dio
I (678) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
bkcmd=0���sleep=0���bkcmd=0���sleep=0���rest���ets Jul 29 2019 12:21:46
```

### Additional information

when I flash a D1 mini via the ESPHome website, the WLAN works
