### ISSUE TITLE
ds

### ISSUE THREAD

**Issue by macledefa** [esphome/issues#5671]
### The problem

The problem is that after every press of the HA button, the code works well, turning on my computer. But exactly 1 minute after, the relay activate for like 6 / 7 seconds, turning off my PC.

### Which version of ESPHome has the issue?

esp

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
status_led:
  pin:
    number: GPIO13
    inverted: True

button:
  - platform: template
    name: "Allumer mon PC"
    id: sw_pc_power
    on_press:
      - output.turn_on: out_relay
      - delay: 0.5s
      - output.turn_off: out_relay

output:
  - platform: gpio
    id: out_relay
    #Inverts relay operation, this avoids force shutdown behavior on some motherboards. Uncomment here and replace the above lambda if you are having this problem.
    #inverted: True
    pin: GPIO12
```
