### ISSUE TITLE
Light.addressable_set not responding

### ISSUE THREAD

**Issue by cklit** [esphome/issues#568]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io 96.5 on Ubuntu 18.04, running ESPHome 1.13.6

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 NodeMCUv2

**Affected component:**
Light component

**Description of problem:**
I'm not able to get the light.addressable_set action to work. As you can see in the configuration below, I've made a test-action that triggers whenever my input_number goes above 1. 
It does send the "Hello world"-message, but nothing happens on my LEDs.

No errors in the logs what-so-ever.

Appreciate any help :)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: beolamp14
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: 'xxxxxxxxxx'
  password: 'xxxxxxxxxxx'


# Example configuration entry
api:

web_server:
  port: 80

# Enable logging
logger:

ota:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D5
    num_leds: 12
    rgb_order: GRB
    name: "BeoLamp14"
    id: led
  
sensor:
  - platform: homeassistant
    name: "Volumio volume"
    entity_id: input_number.volumesensor #from HA
    id: volume
    on_value:
      if:
        condition:
          lambda: 'return id(volume).state > 1.0;'
        then:
          - logger.log: "Hello World"
          - light.addressable_set:
              id: led
              range_from: 0
              range_to: 11
              red: 100%
              green: 50%
              blue: 0%
```

**Logs (if applicable):**

```
[09:59:49][D][homeassistant.sensor:019]: 'input_number.volumesensor': Got state 6.00
[09:59:49][D][sensor:092]: 'Volumio volume': Sending state 6.00000  with 1 decimals of accuracy
[09:59:49][D][main:395]: Hello World

```

**Additional information and things you've tried:**

**Comment by cklit** [comment]
If I change it to this:

```
  - platform: homeassistant
    name: "Volumio volume"
    entity_id: input_number.volumesensor #from HA
    id: volume
    on_value:
      if:
        condition:
          lambda: 'return id(volume).state > 1.0;'
        then:
          - logger.log: "Hello World"
          - light.turn_on:
              id: led
          - light.addressable_set:
              id: led
              range_from: 10
              range_to: 11
              red: 1.0
              green: 0.0
              blue: 0.0
```

And change the input_number slider quickly, I can see that the entered range of LEDs actually flicker, but as you can see no colors change.
Video is attached.
![ezgif-3-ddef2f373a4d](https://user-images.githubusercontent.com/23294994/62539146-d31a7180-b854-11e9-831d-777d9f037adb.gif)
