### ISSUE TITLE
addition of "homeassistant.service:" causes the sonoff basic to be unable to connect to wifi

### ISSUE THREAD

**Issue by anthonykeane** [esphome/issues#5680]
### The problem

_First off I have a reasonable workaround, so I am only reporting cos others may experiance the same issue, I don't require a soluation._

Setup: ESP addon Current version: 2024.3.1 

I tried on a Blue and also a Laptop

**Background**:

I have a Eufy security camera with a floodlight. The only way to activate the floodlight is via the Eufy app (or homeassistant). But I need a physical switch on the wall for the others in my home.

I am attempting to add a Sonoff Basic (powered by esphome) behind a wall switch, the idea is that I can detect the switch change and then take an action to toggle the floodlight.

To achieve this is pretty straightforward with the sonoff basic with the normal physical light switch opening /closing GPIO14 and GND

So, in my code below the switch activates a call to HA to toggle the light.eufy_floodlight_light entity.

**The Problem**

The below code should do the trick, note this code has coimmented out the problem area and works as it stands 

```
esphome:
  name: sonoff-template
  friendly_name: Sonoff_template

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED"

ota:
  password: "REDACTED"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff-Template Fallback Hotspot"
    password: !secret wifi_password

captive_portal:
    
web_server:
  port: 80
  version: 2


binary_sensor:
  - platform: gpio
    name: GPIO14
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    # on_press:
    #   then:
    #     - homeassistant.service:
    #         service: light.toggle
    #         data:
    #           entity_id: light.eufy_floodlight_light
        # - light.toggle: light_1
  - platform: gpio
    name: GPIO0
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_2
    # on_state:
    #   then:
    #     - homeassistant.service:
    #         service: light.toggle
    #         data:
    #           entity_id: light.eufy_floodlight_light
        # - light.toggle: light_2

  - platform: status
    name: "My sonoff Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "eufy floodlight light"
    id: light_1
    output: relay_1


status_led:
  pin:
    number: GPIO13
    inverted: yes
```

However when I uncomment this code;

```
    # on_press:
    #   then:
    #     - homeassistant.service:
    #         service: light.toggle
    #         data:
    #           entity_id: light.eufy_floodlight_light

```

the sonoff cannot find any wifi in the scan 

Note: this log entry was before I added the **fast_connect: true** did not find any SSIDs
```
[D][wifi:462]: Starting scan...
[D][wifi:477]: Found networks:
[D][wifi:479]:   No network found!
[D][wifi:462]: Starting scan...
```

Here is the logs without the "homeassistant.service:" where all works as expected

```
[D][wifi:477]: Found networks:
[I][wifi:520]: - 'NoneShallPass' (18:82:8C:D5:6A:04) ▂▄▆█
[D][wifi:522]:     Channel: 1
[D][wifi:523]:     RSSI: -59 dB
[D][wifi:525]: - 'REDACTED' (REDACTED) ▂▄▆█
[D][wifi:525]: - 'REDACTED' (REDACTED) ▂▄▆█
[D][wifi:525]: - 'REDACTED' (REDACTED) ▂▄▆█
[D][wifi:525]: - 'REDACTED' (REDACTED) ▂▄▆█
[D][wifi:525]: - 'REDACTED' (REDACTED) ▂▄▆█
[D][wifi:525]: - 'REDACTED' (REDACTED) ▂▄▆█
[D][wifi:525]: - 'REDACTED' (REDACTED) ▂▄▆█
[D][wifi:525]: - 'REDACTED' (REDACTED) ▂▄▆█

[I][wifi:303]: WiFi Connecting to 'REDACTED'...
[I][wifi:594]: WiFi Connected!
[C][wifi:408]:   Local MAC: REDACTED
[C][wifi:413]:   SSID: 'REDACTED'
[C][wifi:416]:   IP Address: 192.168.0.104
[C][wifi:419]:   BSSID: REDACTED
[C][wifi:421]:   Hostname: 'sonoff-template'
[C][wifi:423]:   Signal strength: -63 dB ▂▄▆█
[C][wifi:427]:   Channel: 1
[C][wifi:428]:   Subnet: 255.255.255.0
[C][wifi:429]:   Gateway: 192.168.0.1
[C][wifi:430]:   DNS1: 192.168.0.1
[C][wifi:431]:   DNS2: 0.0.0.0
[D][wifi:603]: Disabling AP...
[C][ota:096]: Over-The-Air Updates:
[C][ota:097]:   Address: sonoff-template.local:8266
[C][ota:100]:   Using Password.
[C][ota:103]:   OTA version: 2.
[C][api:025]: Setting up Home Assistant API server...
[I][app:062]: setup() finished successfully!
[W][wifi:165]: Warning cleared
[W][api:152]: Warning set: unspecified
[I][app:102]: ESPHome version 2024.3.1 compiled on Apr  6 2024, 12:29:49
[C][wifi:580]: WiFi:
[C][wifi:408]:   Local MAC: REDACTED
[C][wifi:413]:   SSID: 'REDACTED'
[C][wifi:416]:   IP Address: 192.168.0.104
[C][wifi:419]:   BSSID: 18:82:8C:D5:6A:04
[C][wifi:421]:   Hostname: 'sonoff-template'
[C][wifi:423]:   Signal strength: -64 dB ▂▄▆█
[C][wifi:427]:   Channel: 1
[C][wifi:428]:   Subnet: 255.255.255.0
[C][wifi:429]:   Gateway: 192.168.0.1
[C][wifi:430]:   DNS1: 192.168.0.1
[C][wifi:431]:   DNS2: 0.0.0.0
[C][logger:166]: Logger:
[C][logger:167]:   Level: DEBUG
[C][logger:169]:   Log Baud Rate: 115200
[C][logger:170]:   Hardware UART: UART0
[C][captive_portal:088]: Captive Portal:
[C][mdns:115]: mDNS:
[C][mdns:116]:   Hostname: sonoff-template
[C][ota:096]: Over-The-Air Updates:
[C][ota:097]:   Address: sonoff-template.local:8266
[C][ota:100]:   Using Password.
[C][ota:103]:   OTA version: 2.
[C][api:139]: API Server:
[C][api:140]:   Address: sonoff-template.local:6053
[C][api:142]:   Using noise encryption: YES
[D][api:102]: Accepted 192.168.0.15
[W][api:165]: Warning cleared
[W][api.connection:091]: : Socket operation failed: BAD_INDICATOR errno=11
[D][api:102]: Accepted 192.168.0.15
[W][api.connection:091]: : Socket operation failed: HANDSHAKESTATE_READ_FAILED errno=11
[W][api:152]: Warning set: unspecified
[D][api:102]: Accepted 192.168.0.15
[W][api:165]: Warning cleared
[W][component:232]: Component api took a long time for an operation (292 ms).
[W][component:233]: Components should block for at most 30 ms.
[D][api:102]: Accepted 192.168.0.15
[D][api.connection:197]: aioesphomeapi (192.168.0.15) requested disconnected
[W][component:232]: Component api took a long time for an operation (288 ms).
[W][component:233]: Components should block for at most 30 ms.
[D][api.connection:1159]: Home Assistant 2024.4.1 (192.168.0.15): Connected successfully
[D][ota:154]: Starting OTA Update from 192.168.0.15...
[W][ota:152]: Warning set: unspecified
[D][ota:330]: OTA in progress: 0.3%
[D][ota:330]: OTA in progress: 9.3%
[D][ota:330]: OTA in progress: 17.2%
[D][ota:330]: OTA in progress: 29.6%
[D][ota:330]: OTA in progress: 42.1%
[D][ota:330]: OTA in progress: 54.5%
[D][ota:330]: OTA in progress: 66.9%
[D][ota:330]: OTA in progress: 76.0%
[D][ota:330]: OTA in progress: 83.5%
[D][ota:330]: OTA in progress: 95.2%
[I][ota:363]: OTA update finished!
[W][ota:165]: Warning cleared
[I][app:134]: Rebooting safely...
[W][wifi_esp8266:500]: Event: Disconnected ssid='REDACTED' bssid=REDACTED reason='Association Leave'

```
Here are the logs with this uncommented;

```
D][ota:330]: OTA in progress: 0.3%
[D][ota:330]: OTA in progress: 13.3%
[D][ota:330]: OTA in progress: 25.3%
[D][ota:330]: OTA in progress: 36.2%
[D][ota:330]: OTA in progress: 49.2%
[D][ota:330]: OTA in progress: 62.3%
[D][ota:330]: OTA in progress: 69.7%
[D][ota:330]: OTA in progress: 81.9%
[D][ota:330]: OTA in progress: 91.7%
[I][ota:363]: OTA update finished!
[W][ota:165]: Warning cleared
[I][app:134]: Rebooting safely...
[W][wifi_esp8266:500]: Event: Disconnected ssid='REDACTED' bssid=REDACTED reason='Association Leave'

 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x4010f000, len 3460, room 16 
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4 
tail 4
chksum 0xc9
csum 0xc9
v00083750
@cp:B0
ld
[I][logger:034]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:483]: There have been 0 suspected unsuccessful boot attempts.
[I][app:029]: Running through setup()...
[D][binary_sensor:034]: 'button_1': Sending initial state OFF
[D][binary_sensor:034]: 'button_2': Sending initial state OFF
[C][light:035]: Setting up light 'sonoff Light'...
[D][light:036]: 'sonoff Light' Setting:
[D][light:041]:   Color mode: 
[D][binary_sensor:034]: 'My sonoff Status': Sending initial state OFF
[C][wifi:038]: Setting up WiFi...
[C][wifi:051]: Starting WiFi...
[C][wifi:052]:   Local MAC: REDACTED
[I][wifi:303]: WiFi Connecting to 'REDACTED'...
[W][wifi:152]: Warning set: unspecified
[W][wifi_esp8266:497]: Event: Disconnected ssid='REDACTED' reason='Probe Request Unsuccessful'
[W][wifi:630]: Error while connecting to network.
[D][wifi:673]: Retrying with hidden networks...
[I][wifi:303]: WiFi Connecting to 'REDACTED'...
[W][wifi_esp8266:497]: Event: Disconnected ssid='REDACTED' reason='Probe Request Unsuccessful'
[W][wifi:630]: Error while connecting to network.
[D][wifi:673]: Retrying with hidden networks...
[I][wifi:303]: WiFi Connecting to 'REDACTED'...
[D][wifi:673]: Retrying with hidden networks...
[I][wifi:172]: Starting fallback AP!
[C][wifi:253]: Setting up AP...
[C][wifi:255]:   AP SSID: 'Sonoff-Template Fallback Hotspot'
[C][wifi:256]:   AP Password: 'REDACTED'
[C][wifi:265]:   IP Address: 192.168.4.1
[I][wifi:303]: WiFi Connecting to 'REDACTED'...
[W][wifi_esp8266:497]: Event: Disconnected ssid='REDACTED' reason='Probe Request Unsuccessful'
[W][wifi:630]: Error while connecting to network.
[D][wifi:673]: Retrying with hidden networks...[I][wifi:303]: WiFi Connecting to 'REDACTED'...
[W][wifi_esp8266:497]: Event: Disconnected ssid='REDACTED' reason='Probe Request Unsuccessful'
[W][wifi:630]: Error while connecting to network.
[D][wifi:673]: Retrying with hidden networks...[I][wifi:303]: WiFi Connecting to 'REDACTED'...
[W][wifi_esp8266:497]: Event: Disconnected ssid='REDACTED' reason='Probe Request Unsuccessful'
[W][wifi:630]: Error while connecting to network.
[D][wifi:673]: Retrying with hidden networks...[I][wifi:303]: WiFi Connecting to 'REDACTED'...
[W][wifi_esp8266:497]: Event: Disconnected ssid='REDACTED' reason='Probe Request Unsuccessful'
[W][wifi:630]: Error while connecting to network.
[D][wifi:673]: Retrying with hidden networks...

```

Note the although the **fallback** is initiated in the logs is is not broadcast and cannot be seen on a phone of PC

### Which version of ESPHome has the issue?

Current version: 2024.3.1 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2024.4.1 Supervisor 2024.03.1 Operating System Frontend 20240404.1

### What platform are you using?

ESP8266

### Board

Sonoff Basic (original)

### Component causing the issue

homeassistant.service

### Example YAML snippet
```
esphome:
  name: sonoff-template
  friendly_name: Sonoff_template

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED"

ota:
  password: "REDACTED"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff-Template Fallback Hotspot"
    password: !secret wifi_password

captive_portal:
    
web_server:
  port: 80
  version: 2


binary_sensor:
  - platform: gpio
    name: GPIO14
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    # on_press:
    #   then:
    #     - homeassistant.service:
    #         service: light.toggle
    #         data:
    #           entity_id: light.eufy_floodlight_light
        # - light.toggle: light_1
  - platform: gpio
    name: GPIO0
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_2
    # on_state:
    #   then:
    #     - homeassistant.service:
    #         service: light.toggle
    #         data:
    #           entity_id: light.eufy_floodlight_light
        # - light.toggle: light_2

  - platform: status
    name: "My sonoff Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "eufy floodlight light"
    id: light_1
    output: relay_1


status_led:
  pin:
    number: GPIO13
    inverted: yes
```
