### ISSUE TITLE
Issue compiling existing components as external components (for development/debugging)

### ISSUE THREAD

**Issue by JohnSmith-LT** [esphome/issues#5682]
### The problem

Not 100% sure but this looks like an issue.

So for some background: The TM1638 chip is supported but there are several flavours of board. The QYF board has a 16 key keypad as well as 8x 7 digit displays but these displays are wired differently than expected by the library. I have this board working now so will try to submit a PR at some point.

So for development purposes I took the TM1638 folder, dropped it into /esphome/config/my_components/ as usual, set my YAML as usual and compiled...

```
external_components:
  # use all components from a local folder
  - source:
      type: local
      path: my_components
    components: [ tm1638 ]
```

The local tm1638.cpp is compiled fine but the board never logs the setup info... If I comment the above out then the board works fine (albeit the display is not correct since the bits are all wrong)

After days of head scratching, building blank components from scratch and getting them to log, I added this line to the to_code section:

`await cg.register_component(var, config)`

So now the first 3 lines of to code become:

    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)
    await display.register_display(var, config)

I assumed that display.register_display should register it, triggering setup but without the additional register_component call the local sensor code isn't run, although the code compiles fine?

Does anyone know why this is or why display.register.display doesn't work? Also, why does the code work fine when not running locally? 

### Which version of ESPHome has the issue?

ESPHome 2023.10.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

All

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

Several

### Example YAML snippet

```yaml
external_components:
  # use all components from a local folder
  - source:
      type: local
      path: my_components
    components: [ tm1638 ]

# Setup the TM1638 example configuration entry
time:
  - platform: homeassistant
    timezone: "Europe/London"
    id: homeassistant_time

display:
  - platform: tm1638
    id: tm1638_display
    dio_pin: GPIO13 #D7
    clk_pin: GPIO12 #D6
    stb_pin: GPIO14 #D5
    intensity: 1
    update_interval: 500ms
    lambda: |-
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H.%M", id(homeassistant_time).now());
      else
        it.strftime("%H%M", id(homeassistant_time).now());
```

### Anything in the logs that might be useful for us?

```txt
No errors or anything, component can be seen to compile fine.
```
