### ISSUE TITLE
Flash size cannot be modified (always hardcoded in platformio.ini)

### ISSUE THREAD

**Issue by derMicro** [esphome/issues#5685]
### The problem

Good Morning :)

I am experimenting with a Shelly Gen3 Mini, whose MCU is an ESP32-C3. However, unlike the normal C3, the Shelly has 512KB RAM and 8MB flash. With a custom.json it was possible to increase the RAM, but adjusting the flash size does not work with any of the options offered. Either the process in post_build.py (partition.csv) fails or the change in size is simply ignored.
[https://community.shelly.cloud/topic/661-shelly-c3f8-specification/](https://community.shelly.cloud/topic/661-shelly-c3f8-specification/)

with

>  board_build.flash_size: 8MB
>  board_upload.maximum_size: 8388608
> **not working** 
>
> <img width="537" alt="image" src="https://github.com/esphome/issues/assets/125592865/e0c75d82-04dd-45c5-980a-fd8e96ab6822">
>
> <img width="377" alt="image" src="https://github.com/esphome/issues/assets/125592865/1f65cc9c-e657-416a-95fc-7c5969a923fc">
> 
> 
> ```
> esphome:
>   name: ${name}
>   friendly_name: ${friendly_name}
>   build_path: "../config/esphome/_builds/${name}"
>   name_add_mac_suffix: false
>   project:
>     name: esphome.bluetooth-proxy
>     version: "1.0"
>   platformio_options:
>     board_dir: boards
>     board: shelly-esp32-c38f
>     #board_build.f_cpu : 160000000L
>     #board_build.f_flash: 40000000L
>     #board_build.flash_mode: dio
>     board_build.flash_size: 8MB
>     board_upload.maximum_size: 8388608
>     #board_build.partitions: "/config/_my/_esphome/partitions/lab-bluetoothproxy-shelly.csv"
> ```

with 
> board_upload.flash_size: 8MB
>  **not working**
>
> <img width="836" alt="image" src="https://github.com/esphome/issues/assets/125592865/4c15e36d-4fe4-4117-8e76-caca6b93b78d">
> 

with

> custom partitions.csv
>  **not working**
> 
> <img width="1004" alt="image" src="https://github.com/esphome/issues/assets/125592865/5a9b7362-cebb-4dca-b283-4cbc6b9cc42c">
> 
> <img width="519" alt="image" src="https://github.com/esphome/issues/assets/125592865/76d82ee5-fd48-45b4-9e90-c03c7f769c8e">
> 
> <img width="457" alt="image" src="https://github.com/esphome/issues/assets/125592865/a26a61cd-0b40-4bae-9fa6-a23777a6a369">
> 
> <img width="586" alt="image" src="https://github.com/esphome/issues/assets/125592865/c686394d-7645-4d5c-912e-3cd2a00c62e8">
> 

Tested with and without custom board json, no modifications were made by me in platformio.ini, sdkconfig.xxx or sdkconfig.xxx.esphomeinternal, moving the project files to the config/esphome folder is only for debugging.

Any ideas?

### Which version of ESPHome has the issue?

2024.3.x

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.x

### What platform are you using?

ESP32-IDF

### Board

Shelly ESP32-C38F

### Component causing the issue

core flash

### Example YAML snippet

```yaml
Board Config
{
  "build": {
    "arduino":{
      "ldscript": "esp32c3_out.ld",
      "partitions": "default_8MB.csv"
    },
    "core": "esp32",
    "f_cpu": "160000000L",
    "f_flash": "40000000L",
    "flash_mode": "dio",
    "extra_flags": "-DARDUINO_ESP32C3_DEV",
    "mcu": "esp32c3",
    "variant": "esp32c3"
  },
  "connectivity": [
    "wifi",
    "bluetooth"
  ],
  "debug": {
    "openocd_target": "esp32c3.cfg"
  },
  "frameworks": [
    "arduino",
    "espidf"
  ],
  "name": "Shelly ESP32-C38F",
  "upload": {
    "flash_size": "8MB",
    "maximum_ram_size": 524288,
    "maximum_size": 8388608,
    "require_upload_port": true,
    "speed": 460800
  },
  "url": "https://devices.esphome.io/devices/Shelly-Plus-1-Mini",
  "vendor": "Shelly"
}

partitions.csv
otadata,  data, ota,    0x9000,   0x2000,
phy_init, data, phy,    0xb000,   0x1000,
nvs,      data, nvs,    0xc000,   0x10000,
app0,     app,  ota_0,  0x20000,  0x200000,
app1,     app,  ota_1,  0x220000, 0x200000,
nvs2,     data, nvs,    0x420000, 0x3e0000,
```
