### ISSUE TITLE
Enable ESP32c6 to display chip temperature correctly, it is currently unable to display

### ISSUE THREAD

**Issue by jjcszxh** [esphome/issues#5687]
### The problem

Enable ESP32c6 to display chip temp
![20240408124534](https://github.com/esphome/issues/assets/77478989/5ca649af-a46f-499b-891f-2f174173b6a5)
erature correctly, it is currently unable to display

IDF document：https://docs.espressif.com/projects/esp-idf/en/latest/esp32c6/api-reference/peripherals/temp_sensor.html

### Which version of ESPHome has the issue?

2024.3.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

ESP32C6

### Component causing the issue

internal_temperature

### Example YAML snippet

```yaml
- platform: internal_temperature
    name: ${node_internal_temperature_name}
    update_interval: 60s
```
