### ISSUE TITLE
TSL2591 integration time parameter is not templatable

### ISSUE THREAD

**Issue by bakerkj** [esphome/issues#5691]
### The problem

I am unable to use a template to configure the `integration_time` parameter of the the TSL2591. I'd like to be able to do this so I can adjust the integration time depending on the sensing needs (low integration time for bright light; high integration time for dim light).

Thanks!

### Which version of ESPHome has the issue?

2024.3.2 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.2

### What platform are you using?

ESP32

### Board

not applicable

### Component causing the issue

tsl2591

### Example YAML snippet

```yaml
esphome:
  name: testing
  platform: ESP32
  board: wemos_d1_mini32

i2c:
  sda: 21
  scl: 22

sensor:
  - platform: tsl2591
    address: 0x29
    update_interval: 1s
    integration_time: !lambda return 100;
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.3.2
INFO Reading configuration /config/esphome/illuminance-sensor.yaml...
Failed config

sensor.tsl2591: [source /config/esphome/illuminance-sensor.yaml:11]
  platform: tsl2591
  address: 41
  update_interval: 1s
  
  This option is not templatable!.
  integration_time: !lambda |-
    return 100;
```
