### ISSUE TITLE
"Visit" tries to use wrong IP when multiple networks are defined

### ISSUE THREAD

**Issue by Hiekkaharju** [esphome/issues#5694]
### The problem

Steps to reproduce :
-define web_server:
-define two or more networks(==SSID), at least one with manual_ip, (first) one with DHCP=without manual_ip
-start device when only the DHCP network is available (or it is clearly strongest)
-try to "VISIT" the device - it will try to access the manual IP, not device_name.local (or dhcp IP) as it should

ESPHome will in the same situation succesfully wirelessly access e.g. Log or install new fw, apparently correctly using the DHCP ip, - thus the bug is only about "visit"

referring to YAML snippet: Even when network "some_ssid" does not exist at all, and both Esphome and the target device are connected to "!secret wifi_ssid", "Visit" will try to open 192.168.4.10

### Which version of ESPHome has the issue?

 2024.3.2  (and earlier)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.2

### What platform are you using?

ESP32

### Component causing the issue

dashboard ???

### Example YAML snippet

```yaml
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid:   some_ssid
      password: !secret wifi_password
      manual_ip:
        static_ip: 192.168.4.10
        gateway: 192.168.4.10
        subnet: 255.255.255.0
```

### Additional information

As side note or related "feature": Esphome shows "VISIT" for a device, if web_server: is defined, even when fw for a new device has never been built aka installed and the device never been connected, even via USB. If the wifi configuration is as in yaml snippet,  "visit" tries to open a browser page from 192.168.4.10
