### ISSUE TITLE
No PT1000 with MAX31865 at NodeMCU (ESP8266)

### ISSUE THREAD

**Issue by Itsch001** [esphome/issues#5697]
### The problem

I try to use PT1000 with a MAX31865. No matter, what I set up, it only recognizes PT100. When I connect a 120Ω resistance as sensor, it gets 48°C. When I use a 1000Ω, it says “RTD High Threshold between measurements”.
The reference resistor is 4700Ω.

### Which version of ESPHome has the issue?

2024.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.3

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

MAX31865

### Example YAML snippet

```yaml
spi:
  clk_pin: GPIO14
  miso_pin: GPIO12
  mosi_pin: GPIO13

sensor:
  - platform: max31865
    name: "BBQ Temperature"
    icon: "mdi:hamburger"
    cs_pin: GPIO15
    reference_resistance: "4300 Ω"
    rtd_nominal_resistance: "1000 Ω"
```

### Anything in the logs that might be useful for us?

```txt
[21:15:47][W][max31865:034]: RTD High Threshold between measurements
[21:15:47][E][max31865:101]: SPI bus read all 0 or all 1 (0xFFFF), check MAX31865 wiring & power.
[21:15:47][D][sensor:093]: 'BBQ Temperature': Sending state nan °C with 2 decimals of accuracy
```

### Additional information

the log output with the 120Ω connected is
`[21:29:42][D][sensor:093]: 'BBQ Temperature': Sending state 48.52332 °C with 2 decimals of accuracy`
changing the default values back to 470Ω / 100Ω doesn’t seem to have an effect.
