### ISSUE TITLE
Device crashes when the graph drawing a line from outside to inside

### ISSUE THREAD

**Issue by chiahsing** [esphome/issues#5703]
### The problem

In the graph component, when a trace with continuous set to true, and its previous value >= max_value and the new value < max_value, it crashes the device. Same thing seems to happen to min_value side as well.

Example YAML is a template sensor which is uptime % 16, and the graph is configured with max_value=15. It crashes when the template sensor goes from 15 to 0. Setting the max_value to 15.5, or setting continuous to false makes the issue go away.

### Which version of ESPHome has the issue?

2024.3.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

graph

### Example YAML snippet

```yaml
esphome:
  name: nodemcu-32

logger:

network:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

api:
  encryption:
    key: !secret api_key

esp32:
  board: esp32dev

spi:
  mosi_pin: GPIO23
  clk_pin: GPIO18

debug:
  update_interval: 5s

sensor:
  - platform: uptime
    id: uptime_sensor
    update_interval: 1s
  - platform: template
    id: template_sensor
    update_interval: 1s
    lambda: |-
      return static_cast<int>(id(uptime_sensor).state) % 16;

graph:
  - id: template_graph
    duration: 1min
    width: 100
    height: 100
    x_grid: 15s
    y_grid: 5
    min_value: 0
    max_value: 15
    traces:
      - sensor: template_sensor
        # continuous: true  # uncomment this will crashes the devices after 16s

display:
  - platform: waveshare_epaper
    cs_pin: GPIO26
    dc_pin: GPIO27
    model: 2.13inv3
    update_interval: 1s
    lambda: |-
      it.graph(0, 0, id(template_graph));
```
