### ISSUE TITLE
web_server with local: true does not include css_include or js_include

### ISSUE THREAD

**Issue by pzich** [esphome/issues#5704]
### The problem

When creating a `web_server` that uses `css_include` or `js_include`, the includes are not included if `local: true` is set.

```
web_server:
  local: true            # When this is set...
  css_include: "css.css" # this CSS...
  js_include: "js.js"    # and this JS are not included
```

The problem seems to stem from the fact that setting `local: true` adds the `USE_WEBSERVER_LOCAL` define, which causes `WebServer::handle_index_request()` to [serve](https://github.com/esphome/esphome/blob/7d99676fe88858ef29e7bd21c81eb5b1bebb8349/esphome/components/web_server/web_server.cpp#L174-L179) the [statically encoded](https://github.com/esphome/esphome/blob/7d99676fe88858ef29e7bd21c81eb5b1bebb8349/esphome/components/web_server/server_index.h) `INDEX_GZ`.

This `INDEX_GZ` doesn't have the conditionally-added [`<link>`](https://github.com/esphome/esphome/blob/7d99676fe88858ef29e7bd21c81eb5b1bebb8349/esphome/components/web_server/web_server.cpp#L188-L190) and [`<script>`](https://github.com/esphome/esphome/blob/7d99676fe88858ef29e7bd21c81eb5b1bebb8349/esphome/components/web_server/web_server.cpp#L348-L352) tags that get added in the "non-local" index.

Interestingly, the corresponding `/0.css` and `/0.js` are still created and served.

---

I see a few different options for fixing this:
- Create several different `INDEX_GZ`s that do/don't include the `<link>` and `<script>` tags as requested
- Always include the `<link>` and `<script>` tags, and let them either 404/500/etc., or serve empty files when nothing is included
- Generate the `INDEX_GZ`/`server_index.h` dynamically at compile time
- Use the "non-local" index, but make sure the contents of `css_url`/`js_url` are included along with `css_include`/`js_include`

### Which version of ESPHome has the issue?

2024.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

web_server

### Example YAML snippet

```yaml
web_server:
  local: true            # Try toggling this on and off
  css_include: "css.css" # See this...
  js_include: "js.js"    # and this are not included when local: true
  css_url: ""            # When the _urls are empty
  js_url: ""             # there are no
```

### Additional information

It might be good to decouple "local" from "gzip" and/or "inline" into separate conventions.

Right now, a configuration like
```
web_server:
  local: false
  css_include: "css.css"
  css_url: ""
  js_include: "js.js"
  js_url: ""
```
actually _is_ all local, but is served as separate files (`/` (index) uncompressed, and `/0.css` and `/0.js` gzip compressed).

While `local: true` is served up as one static gzip compressed index page with CSS and JS inlined.

I'm thinking that at compile time `local: true` could essentially `curl` (or otherwise obtain) the `css_url` and `js_url`, join it with `css_include` and `js_include`, then (optionally?) gzip compress these and serve them up as `/0.css` and `/0.js`, or if `inline` is desired, inline all of that into the index page and then (optionally) gzip that.
