### ISSUE TITLE
TUYA ESPHome 2024.4.0 compiliation error after eco datapoint changes

### ISSUE THREAD

**Issue by Bl00d-B0b** [esphome/issues#5717]
### The problem

after update tuya climate to 2024.4.0 and make changes with eco I reveive a compiliation error

/config/esphome/bedroom-thermostat.yaml: In function 'void setup()':
/config/esphome/bedroom-thermostat.yaml:177:32: error: invalid conversion from 'const char*' to 'uint8_t' {aka 'unsigned char'} [-fpermissive]
In file included from src/esphome.h:59,
                 from src/main.cpp:3:
src/esphome/components/tuya/climate/tuya_climate.h:49:27: note:   initializing argument 1 of 'void esphome::tuya::TuyaClimate::set_eco_id(uint8_t)'
   49 |   void set_eco_id(uint8_t eco_id) { this->eco_id_ = eco_id; }
      |                   ~~~~~~~~^~~~~~

### Which version of ESPHome has the issue?

2024.4.0 

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

BK72XX

### Board

wb3s

### Example YAML snippet

```yaml
climate:
  - platform: tuya
    name: "Thermostat"
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    preset:
      eco:
        datapoint: 5
        temperature: 18
    temperature_multiplier: 0.5
    visual:
      min_temperature: 15
      max_temperature: 25
      temperature_step: 0.5
```
