### ISSUE TITLE
ESP32 restarts the second time the internal-adc microphone is used

### ISSUE THREAD

**Issue by FluffStufff** [esphome/issues#5718]
### The problem

When activating the voice assist microphone on an ESP32 setup using the internal-adc it will correctly trigger the first time, but hang and reboot the entire ESP32 the second time.

This behavior does not happen when using an external mic over I2S, as demoed in the example YAML

The behavior appears to affect a wide range of ESP32's and happens on 3.3 or 5v power.

It can be tested with no extra hardware required, the internal-adc microphone can be set to disconnected pins and the crash will still occur. all you need to to trigger the 'button' by bridging pin 14 to ground with a jumper

### Which version of ESPHome has the issue?

2024.4.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

Microphone component

### Example YAML snippet

```yaml
i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO27
    i2s_bclk_pin: GPIO26
  - id: i2s_out
    i2s_lrclk_pin: GPIO2
    i2s_bclk_pin: GPIO15
    
microphone:
  - platform: i2s_audio
    id: mic_i2s_internal
    i2s_audio_id: i2s_in
    adc_type: internal
    adc_pin: GPIO32

  - platform: i2s_audio
    i2s_audio_id: i2s_in
    adc_type: external
    pdm: false
    id: mic_i2s_external
    i2s_din_pin: GPIO16
    bits_per_sample: 32bit

voice_assistant:
  #crashes on second trigger
  microphone: mic_i2s_internal
  #works
  #microphone: mic_i2s_external
  use_wake_word: false

binary_sensor:
  - platform: gpio
    name: "Handset Button"
    id: handset_button
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        - voice_assistant.start
    on_release:
      then:
        - voice_assistant.stop
```

### Additional information

This Issue can be tested with no extra hardware required, the internal-adc microphone can be set to disconnected pins and the crash will still occur. all you need to do is trigger the 'button' by bridging pin 14 to ground with a jumper. the second attempt should fail.
