### ISSUE TITLE
Dooya RF Remote possible off-by-one

### ISSUE THREAD

**Issue by pedrovanzella** [esphome/issues#5721]
### The problem

When receiving an RF Remote with the Dooya protocol, ESPHome detects it with ID `0x00b2c5a9`. However, both a Flipper Zero and a HackRF Portapack with the Mayhem firmware read the same remote as ID `0x004d3a56`. If you add `0x00b2c5a9` and `0x004d3a56`, you get `0x00ffffff`, so this is probably an off-by-one error somewhere.

The Button, Check and Channel codes also look weird. Channel 0 reads as 127, and channel 1 as 126, and so on. Button Up, short press reads as Code 14, check 1, and long press as Code 14 check 14.

If I try to send the decoded content back through an RF Transmitter with the Dooya protocol and all the same data (ID, Channel, Button, Check etc), my blinds don't respond, and I'm not able to decode the signal in the Flipper or the HackRF, even though I do see some signal being output, indicating the transmitter is indeed trying to send something.

If I plug in the data from the Flipper dump, I'm not able to get the blinds to respond either. Note that I can control the blinds from the Flipper or the HackRF with those dumps.

Reference: https://github.com/esphome/esphome/pull/6488

### Which version of ESPHome has the issue?

2024.4.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Example YAML snippet

```
remote_receiver:
  pin: GPIO04
  dump: dooya
  tolerance: 50%
  filter: 250us
  idle: 7ms

remote_transmitter:
  pin: GPIO05
  carrier_duty_percent: 100%

cover:
  - platform: template
    id: blind_0
    name: "Blind Chan 0"
    optimistic: true
    assumed_state: true
    open_action: 
      - remote_transmitter.transmit_dooya:
          id: 0x004d3a56
          channel: 127
          button: 14
          check: 14
```

**Comment by ms40724** [comment]
I have the same problem, sending the same decoded content back with the Dooya protocol does not work as expected.

**Comment by deejaybeam** [comment]
Same problem here - sending captured values does not work.

**Comment by jesserockz** [comment]
It is not off by one, the 1s and 0s are flipped completely.

```py
>>> correct = 0x004d3a56
>>> bin(correct)
'0b010011010011101001010110'
>>> wrong = 0x00b2c5a9
>>> bin(wrong)
'0b101100101100010110101001'
```

**Comment by jesserockz** [comment]
Try the linked PR:
```yaml
external_components:
  - source: github://pr#6947
    components: remote_base
```
