### ISSUE TITLE
ESP32 (Wroom) doent work with Dallas DS18B20 Sensor

### ISSUE THREAD

**Issue by StrSebastian** [esphome/issues#5730]
### The problem

I tested 300 Versions of these kind of yaml. 
And all kinds of configuratiosn nothing worked. 
Sensor not found or jost nothing in the log.
I also uses all kind of resostors. 
Also multible or single sensors.
But what makes me sure about the issu: it worked first try with Arduino IDE. Got the right temprature with example code.
My guess is, the bug is somewhere in the lib ob HA build pipline.

### Which version of ESPHome has the issue?

2024.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.3

### What platform are you using?

ESP32

### Board

Wroom 32

### Component causing the issue

Dallas Sensor DS18B20 

### Example YAML snippet

```yaml
I tested 300 Versions of these kind of yaml. 
And all kinds of configuratiosn nothing worked. 
Sensor not found or jost nothing in the log.
I also uses all kinds of resostors. 
Also multible or single sensors.
But what makes me sure about the issu: it worked first try with Arduino IDE. Got the right temprature with example code.
My guess is, the bug is somewhere in the lib ob HA.
dallas:
  pin:
    number: GPIO26<Optional tested>
    mode:
      input: true <Optional tested> 
      pullup: true<Optional tested>
  update_interval: 5s
```

### Anything in the logs that might be useful for us?

```txt
nop.
```

### Additional information

https://community.simon42.com/t/probleme-mit-esp32-und-dallas-temperatur-sensor/4522/15

**Comment by sbrk-r** [comment]
Try commenting out mode/input/pullup and have a hardware pullup, see if it works. Maybe mode is overriding something crucial. 

I see open feature request asking for advanced pin options, so must not be supported currently..? Maybe it was added without closing FR [FR 2499 ](https://github.com/esphome/feature-requests/issues/2499)

I use configuration like this on many boards with no issues:

```
dallas:
  - pin: GPIO16
    id: ow0
    update_interval: 10s

sensor:
  - platform: dallas
    #address: 0x6c0000052b7f0828
    dallas_id: ow0
    index: 0
    name: "ow0_t0"
    accuracy_decimals: 2
```
