### ISSUE TITLE
INA219 component not returning signed power

### ISSUE THREAD

**Issue by tomlut** [esphome/issues#5732]
### The problem

This is a bi-directional device. 

A negative current and a positive voltage should produce a negative power (P = I x V).

However the power reported by ESPHome is always positive for the INA219. This makes it impossible to track battery state of charge without a work-around.

![Screenshot 2024-04-25 at 00-17-25 History – Home Assistant](https://github.com/esphome/issues/assets/10679300/65310202-91a4-4363-ac30-d1b48155c755)
![Screenshot 2024-04-25 at 00-17-52 History – Home Assistant](https://github.com/esphome/issues/assets/10679300/e88b656b-4eac-4479-82da-8773addc91c8)
![Screenshot 2024-04-25 at 00-17-39 History – Home Assistant](https://github.com/esphome/issues/assets/10679300/977c89c5-9459-44bd-b12c-8a4bedbbff5b)

### Which version of ESPHome has the issue?

2024.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2024.4.4

### What platform are you using?

ESP32

### Board

QuinLED ESP32

### Component causing the issue

INA219

### Example YAML snippet

```yaml
sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    current:
      name: "Shed Battery Current"
      filters:
        - multiply: -1
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 1
    power:
      name: "Shed Battery Power"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 1
    bus_voltage:
      name: "Shed Battery Voltage"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 1
    shunt_voltage:
      name: "Shed Shunt Voltage"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 1
    max_voltage: 15.0V
    max_current: 3A
    update_interval: 6s
```
