### ISSUE TITLE
ESP restarts when I send long command via api.service

### ISSUE THREAD

**Issue by Vizualni** [esphome/issues#5733]
### The problem

ESP restarts when I send long command via api.service, but it doesn't when I send it directly as remote_transmitter.transmit_raw. The blue LED light flashes on the board when it goes through the API service and I can verify in the logs that it starts again.

Here is the config I am using:

```yaml
esphome:
  name: klima_dnevni
  friendly_name: KlimaDnevni

esp8266:
  board: nodemcu

# Enable logging
logger:
  level: NONE

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  encryption:
    key: "foobar"
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 38kHz              
            code: !lambda 'return command;'
switch:
  - platform: template
    name: "Send payload"
    turn_on_action:
      remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz  
        code: [305, -33377, 122, -41051, 426, -426, 426, -426, 396, -426, 457, -396, 426, -426, 426, -24789, 3380, -1705, 396, -1279, 396, -457, 396, -457, 396, -457, 426, -1249, 426, -426, 426, -426, 426, -426, 426, -396, 457, -1249, 426, -426, 426, -1279, 396, -1310, 396, -457, 396, -1279, 396, -1310, 396, -1279, 396, -1310, 426, -1249, 457, -396, 426, -426, 426, -1279, 426, -396, 426, -426, 426, -426, 426, -426, 426, -426, 426, -426, 396, -457, 396, -457, 396, -457, 396, -426, 426, -1279, 396, -457, 396, -1279, 426, -426, 426, -426, 426, -426, 426, -1249, 426, -1279, 426, -426, 426, -396, 426, -426, 426, -426, 426, -457, 396, -426, 426, -426, 396, -457, 396, -457, 396, -457, 396, -426, 396, -457, 396, -457, 396, -457, 396, -426, 457, -396, 426, -1279, 426, -1249, 426, -1279, 426, -426, 426, -1249, 426, -457, 396, -1310, 396, -1279, 396, -34169, 3319, -1736, 396, -1310, 396, -426, 396, -457, 396, -457, 396, -1279, 396, -457, 396, -457, 396, -457, 426, -396, 457, -1249, 426, -426, 426, -1249, 457, -1249, 426, -426, 426, -1279, 396, -1310, 396, -1310, 396, -1279, 396, -1310, 396, -426, 396, -457, 396, -1310, 426, -396, 457, -396, 426, -426, 426, -426, 426, -426, 426, -396, 426, -426, 426, -426, 426, -426, 426, -457, 396, -426, 396, -1310, 396, -457, 396, -426, 396, -457, 396, -457, 396, -1310, 396, -426, 396, -457, 426, -426, 426, -426, 426, -396, 457, -396, 426, -426, 426, -426, 426, -426, 426, -396, 426, -426, 426, -426, 426, -457, 396, -457, 396, -426, 396, -457, 396, -457, 396, -457, 396, -426, 426, -1279, 396, -457, 396, -1310, 426, -396, 426, -1279, 426, -396, 426, -34169, 3319, -1705, 426, -1279, 426, -396, 457, -396, 426, -426, 426, -1279, 426, -396, 426, -426, 426, -457, 396, -457, 396, -1279, 396, -457, 396, -1310, 396, -1279, 396, -457, 396, -1310, 426, -1249, 426, -1279, 426, -1249, 426, -1279, 426, -426, 426, -396, 426, -1310, 396, -457, 365, -487, 365, -457, 365, -487, 365, -487, 396, -457, 365, -457, 396, -457, 365, -487, 365, -487, 365, -487, 396, -426, 396, -457, 396, -457, 396, -457, 396, -426, 426, -426, 396, -457, 396, -1310, 396, -457, 396, -457, 365, -1340, 365, -487, 365, -457, 365, -487, 365, -487, 365, -487, 365, -457, 365, -1340, 396, -457, 396, -457, 396, -1279, 396, -457, 396, -457, 396, -426, 426, -426, 396, -457, 396, -457, 396, -487, 365, -457, 365, -487, 396, -457, 365, -487, 365, -487, 365, -487, 365, -457, 365, -487, 365, -1310, 365, -487, 396, -1310, 396, -457, 396, -426, 396, -457, 396, -457, 396, -457, 396, -426, 396, -457, 396, -457, 396, -487, 365, -487, 365, -457, 365, -487, 365, -487, 365, -487, 365, -457, 365, -487, 365, -487, 365, -1340, 365, -1340, 365, -487, 365, -457, 396, -457, 396, -426, 396, -487, 365, -487, 365, -457, 396, -457, 365, -518, 335, -518, 335, -1340, 365, -1340, 335, -518, 335, -487, 365, -487, 335, -518, 335, -518, 335, -487, 365, -487, 396, -457, 365, -487, 365, -487, 365, -457, 396, -457, 396, -457, 365, -487, 365, -457, 396, -457, 396, -487, 335, -1370, 335, -487, 365, -487, 365, -487, 335, -518, 335, -518, 335, -1340, 335, -1370, 335, -487, 365, -487, 365, -487, 365, -487, 365, -487, 365, -457, 396, -457, 365, -1340, 365, -487, 365, -487, 365, -487, 335, -518, 335, -518, 335, -487, 365, -487, 335, -518, 335, -518, 335, -1340, 365, -1340, 335, -518, 365, -457, 396, -457, 396, -457, 365, -1340, 365, -101502]


ota:
  password: "foobar"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Klima Fallback Hotspot"
    password: "foobar"


remote_transmitter:
  pin: 5
  carrier_duty_percent: 50%

captive_portal:
```

When I take the same payload that's in the provided YAML and send it via developer tools > services like this:

![Screenshot 2024-04-24 at 20 09 35](https://github.com/esphome/issues/assets/454988/4e275c8b-8fcf-4325-b9a7-c325f662cfb1)

my esp restarts. When I send it by calling the "Send Payload" action, it works. 

### Which version of ESPHome has the issue?

2024.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.3

### What platform are you using?

ESP8266

### Board

nodemcu
