### ISSUE TITLE
Custom wake word isn't working - wake word component is marked as failed

### ISSUE THREAD

**Issue by jherby2k** [esphome/issues#5743]
### The problem

After following the instructions at https://esphome.io/components/micro_wake_word.html, I am having trouble getting my custom wake word to work. **okay_nabu** works great, and my custom .tflite file works well with openWakeWord.

[hey_greenwood.json](https://github.com/esphome/issues/files/15136936/hey_greenwood.json)
[logs_basement-office-speaker_run.txt](https://github.com/esphome/issues/files/15136919/logs_basement-office-speaker_run.txt)

### Which version of ESPHome has the issue?

2024.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.4

### What platform are you using?

ESP32

### Board

onju

### Component causing the issue

micro_wake_word

### Example YAML snippet

```yaml
micro_wake_word:
  #model: okay_nabu # this works fine
  model: http://home_assisant_ip_address:8123/local/microwakeword/hey_greenwood.json # also tried https://fqdn
  on_wake_word_detected:
    - if:
        condition: media_player.is_playing
        then:
          - media_player.pause
    - voice_assistant.start:
        wake_word: !lambda return wake_word;
```

### Anything in the logs that might be useful for us?

```txt
[21:25:14][C][micro_wake_word:057]: microWakeWord:
[21:25:14][C][micro_wake_word:058]:   Wake Word: hey greenwood
[21:25:14][C][micro_wake_word:059]:   Probability cutoff: 0.500
[21:25:14][C][micro_wake_word:060]:   Sliding window size: 10
[21:25:14][E][component:082]:   Component micro_wake_word is marked FAILED
```
