### ISSUE TITLE
issue with fastled_clocklesss using WS2812 colors

### ISSUE THREAD

**Issue by deanfourie1** [esphome/issues#5747]
### The problem

using the fastled_clockless integration with the WS2812 LEDs,
When specifying colors such as

green: 100% 

does not show green, it shows a light blue instead.

Stating red: 100% shows purple.

### Which version of ESPHome has the issue?

2024.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.4

### What platform are you using?

ESP32

### Board

esp32minikit

### Component causing the issue

fastled_clockless

### Example YAML snippet

```yaml
on_boot:
    priority: -1000
    then: 
      - if:
          condition:
            - sun.is_above_horizon:
          then:
              light.turn_on:
                id: led
                brightness: 100%
                green: 100%

          else:
             - light.turn_on:
                id: led
                brightness: 20%
                green: 0%
                red: 100%



light:
  - platform: fastled_clockless
    id: "led"
    name: "LED"
    pin: 23
    chipset: WS2812
    num_leds: 1
    rgb_order: GRB
```

### Anything in the logs that might be useful for us?

```txt
Nothing
```
