### ISSUE TITLE
Graph draws out of the specified boundary

### ISSUE THREAD

**Issue by chiahsing** [esphome/issues#5748]
### The problem

The graph component doesn't check the y-coordinate and can draw out of the boundary.

### Which version of ESPHome has the issue?

2024.4.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
esphome:
  name: debug

logger:

network:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

api:
  encryption:
    key: !secret api_key

esp32:
  board: esp32dev

spi:
  mosi_pin: GPIO23
  clk_pin: GPIO18

debug:
  update_interval: 5s

sensor:
  - platform: uptime
    id: uptime_sensor
    update_interval: 1s
  - platform: template
    id: template_sensor
    update_interval: 1s
    lambda: |-
      return static_cast<int>(id(uptime_sensor).state) % 16;

graph:
  - id: template_graph
    duration: 1min
    width: 100
    height: 100
    x_grid: 15s
    y_grid: 5
    min_value: 5
    max_value: 10
    traces:
      - sensor: template_sensor
        continuous: true

display:
  - platform: waveshare_epaper
    cs_pin: GPIO26
    dc_pin: GPIO27
    reset_pin: GPIO14
    busy_pin: GPIO12
    model: 2.13inv3
    update_interval: 1s
    lambda: |-
      it.graph(20, 20, id(template_graph));
```
