### ISSUE TITLE
[cst816][pca9554] is an invalid option for [interrupt_pin]

### ISSUE THREAD

**Issue by lboue** [esphome/issues#5769]
### The problem

Hello.

I'm looking for the right ESPHome syntax to configure a touchscreen connected via a PCA9554 I/O expander. This is the YAML config:
```
touchscreen:
  platform: cst816
  id: cst816_touchscreen
  interrupt_pin:
      pca9554: pca9554a_device
      number: 3
```
And I am getting this error: ```[pca9554] is an invalid option for [interrupt_pin]. Please check the indentation.```

I didn't find it here:
* [Touchscreen Components](https://esphome.io/components/touchscreen/index.html)
* [cst816 Touch Screen Controller](https://esphome.io/components/touchscreen/cst816.html)

Regards

### Which version of ESPHome has the issue?

2024.4.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.1

### What platform are you using?

ESP32-IDF

### Board

Adafruit Qualia ESP32-S3

### Component causing the issue

touchscreen

### Example YAML snippet

```yaml
# PCA9554 I/O Expander
# https://esphome.io/components/pca9554.html
pca9554:
  - id: pca9554a_device
    address: 0x3F

# 2.1" 480x480 round display use CST826 touchscreen with I2C Address at 0x15
touchscreen:
  platform: cst816
  id: cst816_touchscreen
  interrupt_pin:
      pca9554: pca9554a_device
      number: 3
```

### Additional information
Testing with this screen: [Round RGB 666 TTL TFT Display - 2.1" 480x480 - Capacitive Touch - TL021WVC02CT-B1323](https://www.adafruit.com/product/5792)
