### ISSUE TITLE
mitsubishi Climate do not return current Temp

### ISSUE THREAD

**Issue by sosso-b** [esphome/issues#5771]
### The problem

Since the last update Current version: 2024.4.2
mitsubishi Climate return always 0 for the current temperature when i change to daikin then i get directly back the current temperature.
Since that i never add any issue everything was working nice for more then 3 years 

![image](https://github.com/esphome/issues/assets/81828092/f06e818b-1875-4fc7-b284-1da726010c18)

### Which version of ESPHome has the issue?

Current version: 2024.4.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%

climate:
  - platform: mitsubishi       # adjust to match your AC unit!
    name: "Clim etage"
    sensor: temp_etage


# Creation du sensor

sensor:
  - platform: homeassistant
    name: "Current temperature"
    entity_id: sensor.smoke_sensor_2
    id: temp_etage
    internal: true
    accuracy_decimals : 1
```

**Comment by killer0071234** [comment]
I got the same issue, but the temperature at the climate object in HA is always 0°C.
The sensor object itself shows the correct temperature.
Esphome version: 2024.4.2

my yaml snippet:
```
  - platform: dallas
    index: 0
    name: "Temperatur"
    id: klima_temperatur
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15

remote_receiver:
  id: rcvr
  pin:
    number: D6
    inverted: True
    mode: INPUT_PULLUP
  tolerance: 25%

remote_transmitter:
  pin: D5
  carrier_duty_percent: 50%

climate:
  - platform: mitsubishi
    name: "Vorraum"
    receiver_id: rcvr
    id: klima
    icon: mdi:air-conditioner
    sensor: klima_temperatur
    visual:
      min_temperature: 18
      max_temperature: 26
      temperature_step: 0.5
```
I am not sure when it started to show just 0 value, because I did not use it during the winter months.

BR Daniel
