### ISSUE TITLE
sprinkler unexpected valve_overlap behavior 

### ISSUE THREAD

**Issue by jotaj91** [esphome/issues#5777]
### The problem

When i use the sprinkler component with a valve_overlap with more than two valves i have an unexpected behavior when i pause a cycle after the first valve_overlap starts. After i resume the paused cycle, the next valve_overlap period will be cero and  the rest of the cycle behaves as usual. I also tested this with a pump_start_pump_delay and now both valves turn off for the duration of the pump_start_pump_delay instead of both valves being on during the valve_overlap.

### Which version of ESPHome has the issue?

2024.4.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32-s3-devkitc-1

### Component causing the issue

sprinkler

### Example YAML snippet

```yaml
sprinkler:
  - id: irrigation_ctrlr
    main_switch: "greenhouse_1_main_switch"
    auto_advance_switch: "greenhouse 1 Auto Advance"
    reverse_switch: "greenhouse 1 Reverse"
    valve_overlap: 2s
    pump_start_pump_delay: 1s
```
