### ISSUE TITLE
MAC Address interpreted as integer by esphome.helpers

### ISSUE THREAD

**Issue by mrbubble62** [esphome/issues#5796]
### The problem

Hex MAC Addresses containing a letter (A,B,C,D,E ) have no issue
If the MAC Address has no alpha characters E.G 49:42:07:00:25:59

> INFO ESPHome 2024.4.1
INFO Reading configuration /config/esphome/bluetooth-proxy-3-7944b8.yaml...
Failed config
>
>sensor.inkbird_ibsth1_mini: [source /config/esphome/bluetooth-proxy-3-7944b8.yaml:65]
  platform: inkbird_ibsth1_mini
>  
  >Must be string, got <class 'esphome.helpers.EInt'>. did you forget putting quotes around the value?.
  mac_address: 38648233559
  temperature: 
 >   name: Garage Freezer Temperature
  battery_level: 
    name: Garage Freezer Battery Level

If I put the MAC address in quotes the device is ignored and never shows up in the Inkbird integration.

This MAC address works fine 49:42:08:00:25:3A, if I place quotes around it, the device is ignored.
Is there some other way to markup the input stop the helper converting this to a number?

### Which version of ESPHome has the issue?

2024.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.0

### What platform are you using?

ESP32-IDF

### Component causing the issue

esp32_ble_tracker/inkbird_ibsth1_mini

### Example YAML snippet

```yaml
esp32_ble_tracker:

sensor:
  - platform: inkbird_ibsth1_mini
    mac_address: 49:42:08:00:25:3A # this works
    temperature:
      name: "Garage Fridge Temperature"
    battery_level:
      name: "Garage Fridge Battery Level"
  - platform: inkbird_ibsth1_mini
    mac_address: 49:42:07:00:25:59 # this errors
    temperature:
      name: "Garage Freezer Temperature"
    battery_level:
      name: "Garage Freezer Battery Level"
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.4.1
INFO Reading configuration /config/esphome/bluetooth-proxy-3-7944b8.yaml...
Failed config

sensor.inkbird_ibsth1_mini: [source /config/esphome/bluetooth-proxy-3-7944b8.yaml:65]
  platform: inkbird_ibsth1_mini
  
  Must be string, got <class 'esphome.helpers.EInt'>. did you forget putting quotes around the value?.
  mac_address: 38648233559
  temperature: 
    name: Garage Freezer Temperature
  battery_level: 
    name: Garage Freezer Battery Level
```
