### ISSUE TITLE
Unable to compile ESP32-S3-box-3 project with update 2024.5.0

### ISSUE THREAD

**Issue by redwngsrul** [esphome/issues#5800]
### The problem

As the title states, since upgrading my ESPHome base add-on, I am unable to compile the file for my ESP32-S3-Box-3. I have several other ESPHome devices that upgraded just fine. They are not Box-3 units, but rather other ESP8266 and ESP32 dev board devices.

### Which version of ESPHome has the issue?

2024.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.3

### What platform are you using?

ESP32-IDF

### Board

ESP32-S3-Box-3

### Component causing the issue

tflite-micro

### Example YAML snippet

```yaml
substitutions:
  name: esp32-s3-box-3-6412b8
  friendly_name: House-y
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_enc_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: template
    name: "Mute when absent"
    id: mute_when_absent
    icon: mdi:account-right-arrow
    optimistic: true
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF

number:
  - platform: template
    name: "Presence duration"
    id: radar_delayed_off
    icon: mdi:account-clock
    optimistic: true
    restore_value: true
    initial_value: 60
    min_value: 0
    step: 5
    max_value: 300
    unit_of_measurement: s
    entity_category: config
    mode: box

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
    name: "Presence detect"
    disabled_by_default: false
    device_class: "occupancy"
    filters:
      - delayed_off: !lambda return id(radar_delayed_off).state * 1000;
    on_release:
      then:
        - if:
            condition: 
              switch.is_on: mute_when_absent
            then:
              - switch.turn_on: mute
              - light.turn_off: led
    on_press:
      then:
        - if:
            condition: 
              switch.is_on: mute_when_absent
            then:
              - switch.turn_off: mute
              - light.turn_on: led
```

### Anything in the logs that might be useful for us?

```txt
Here is the last line of my compile where it reaches error and stops:

Compiling .pioenvs/esp32-s3-box-3-6412b8/components/esp-tflite-micro/tensorflow/lite/micro/micro_context.o
xtensa-esp32s3-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [.pioenvs/esp32-s3-box-3-6412b8/components/esp-tflite-micro/tensorflow/lite/micro/micro_allocation_info.o] Error 1
```

### Additional information

Additional warnings in the log file:

```Compiling .pioenvs/esp32-s3-box-3-6412b8/src/esphome/components/font/font.o
src/esphome/components/esp_adf/microphone/esp_adf_microphone.cpp: In static member function 'static void esphome::esp_adf::ESPADFMicrophone::read_task(void*)':
src/esphome/components/esp_adf/microphone/esp_adf_microphone.cpp:110:3: warning: missing initializer for member 'i2s_driver_config_t::chan_mask' [-Wmissing-field-initializers]
   };
   ^
src/esphome/components/esp_adf/microphone/esp_adf_microphone.cpp:110:3: warning: missing initializer for member 'i2s_driver_config_t::total_chan' [-Wmissing-field-initializers]
src/esphome/components/esp_adf/microphone/esp_adf_microphone.cpp:110:3: warning: missing initializer for member 'i2s_driver_config_t::left_align' [-Wmissing-field-initializers]
src/esphome/components/esp_adf/microphone/esp_adf_microphone.cpp:110:3: warning: missing initializer for member 'i2s_driver_config_t::big_edin' [-Wmissing-field-initializers]
src/esphome/components/esp_adf/microphone/esp_adf_microphone.cpp:110:3: warning: missing initializer for member 'i2s_driver_config_t::bit_order_msb' [-Wmissing-field-initializers]
src/esphome/components/esp_adf/microphone/esp_adf_microphone.cpp:110:3: warning: missing initializer for member 'i2s_driver_config_t::skip_msk' [-Wmissing-field-initializers]
Compiling .pioenvs/esp32-s3-box-3-6412b8/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.o
Compiling .pioenvs/esp32-s3-box-3-6412b8/src/esphome/components/ili9xxx/ili9xxx_display.o
src/esphome/components/esp_adf/speaker/esp_adf_speaker.cpp: In static member function 'static void esphome::esp_adf::ESPADFSpeaker::player_task(void*)':
src/esphome/components/esp_adf/speaker/esp_adf_speaker.cpp:77:3: warning: missing initializer for member 'i2s_driver_config_t::chan_mask' [-Wmissing-field-initializers]
   };
   ^
src/esphome/components/esp_adf/speaker/esp_adf_speaker.cpp:77:3: warning: missing initializer for member 'i2s_driver_config_t::total_chan' [-Wmissing-field-initializers]
src/esphome/components/esp_adf/speaker/esp_adf_speaker.cpp:77:3: warning: missing initializer for member 'i2s_driver_config_t::left_align' [-Wmissing-field-initializers]
src/esphome/components/esp_adf/speaker/esp_adf_speaker.cpp:77:3: warning: missing initializer for member 'i2s_driver_config_t::big_edin' [-Wmissing-field-initializers]
src/esphome/components/esp_adf/speaker/esp_adf_speaker.cpp:77:3: warning: missing initializer for member 'i2s_driver_config_t::bit_order_msb' [-Wmissing-field-initializers]
src/esphome/components/esp_adf/speaker/esp_adf_speaker.cpp:77:3: warning: missing initializer for member 'i2s_driver_config_t::skip_msk' [-Wmissing-field-initializers]```


Additionally, I have had recent issue with my ESP32-S3-Box-3 compiling any new ESPHome updates. I am forced to Clean All Build Files for the device before installing the update. This above error occurs after I clean all build files and then try to compile. If I proceed with another attempt to compile/install without cleaning build files immediately after this first attempt, I receive a much shorter compile log which is concluded with a different error as shown here:

```Compiling .pioenvs/esp32-s3-box-3-6412b8/components/esp-tflite-micro/tensorflow/lite/micro/micro_allocation_info.o
Compiling .pioenvs/esp32-s3-box-3-6412b8/components/esp-tflite-micro/tensorflow/lite/micro/micro_allocator.o
Compiling .pioenvs/esp32-s3-box-3-6412b8/components/esp-tflite-micro/tensorflow/lite/micro/micro_interpreter.o
Compiling .pioenvs/esp32-s3-box-3-6412b8/components/esp-tflite-micro/tensorflow/lite/micro/micro_interpreter_context.o
Compiling .pioenvs/esp32-s3-box-3-6412b8/components/esp-tflite-micro/tensorflow/lite/micro/micro_interpreter_graph.o
Compiling .pioenvs/esp32-s3-box-3-6412b8/components/esp-tflite-micro/tensorflow/lite/micro/micro_log.o
Compiling .pioenvs/esp32-s3-box-3-6412b8/components/esp-tflite-micro/tensorflow/lite/micro/micro_op_resolver.o
xtensa-esp32s3-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [.pioenvs/esp32-s3-box-3-6412b8/components/esp-tflite-micro/tensorflow/lite/micro/micro_interpreter_context.o] Error 1
```

Here is associated error log from the ESPHome add-on to HA at the time of my attempt to compile/install:

```2024-05-16 07:57:33,170 ERROR Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f60e9304610>>, <Future finished exception=WebSocketClosedError()>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tornado/ioloop.py", line 774, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.11/dist-packages/tornado/gen.py", line 786, in run
    yielded = self.gen.send(value)
              ^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/dashboard/web_server.py", line 254, in _redirect_stdout
    self.write_message({"event": "line", "data": text})
  File "/usr/local/lib/python3.11/dist-packages/tornado/websocket.py", line 332, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError```
