### ISSUE TITLE
Esp32 runs hotter on Esphome 2024.5.0 firmware

### ISSUE THREAD

**Issue by Tmbao** [esphome/issues#5801]
### The problem

I have observed that my ESP32 Bluetooth proxy seems to run hotter after updating to 2024.5.0. There is no other logic changes made to the board and the ambient temperature has been staying pretty much the same. 

![Screenshot_20240516-230428](https://github.com/esphome/issues/assets/7766181/4ef4fdc6-33cc-4aab-b190-7d174f05dbe2)

The issue isn't observed on my other esp32 boards which aren't used as Bluetooth proxy 

### Which version of ESPHome has the issue?

2024.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.3

### What platform are you using?

ESP32-IDF

### Example YAML snippet

```yaml
substitutions:
  name: esp32-bluetooth-proxy
  friendly_name: Bluetooth Proxy

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ap:

api:
logger:
ota:
improv_serial:

dashboard_import:
  package_import_url: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
```
