### ISSUE TITLE
Sensor "on_value_range" actions not triggered when using multiple, unless value moves from outside range

### ISSUE THREAD

**Issue by shed909** [esphome/issues#581]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io with ESPHome add on

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (NoceMCU v3 Lolin board)

**Affected component:**

https://esphome.io/components/sensor/index.html#on-value-range

**Description of problem:**
Specifically when using two triggers/actions, the action specified under "on_value_range" within a TSL2561 sensor only triggers if the value moves from outside the range specified.

Eg, when using:
```
    on_value_range:
      - above: 20
        then:
          - cover.open: door
      - below: 5
        then:
          - cover.close: door
```
If I open my "cover.door" via Home Assistant while my TSL2561's value is below 5 and wait a few sensor intervals, ESPHome does not trigger the "- cover.close: door" action (even though the esphome logs report that it is open).
If I shine a light into the TSL2561 sensor, causing it to go above 5, then take it away so it falls below 5, it triggers the action reliably.

However, if I use just:
```
    on_value_range:
      - below: 5
        then:
          - cover.close: door
```
The automation triggers "- cover.close: door" immediately whenever the sensor evaluates as below 5.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp01
  platform: ESP8266
  board: nodemcuv2
  esp8266_restore_from_flash: True

wifi:
  ssid: "nope"
  password: "nope"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: nope

  services:
    - service: control_stepper
      variables:
        target: int
      then:
        - stepper.set_target:
            id: door_stepper
            target: !lambda 'return target;'
            
ota:
  password: nope

i2c:
  sda: D4
  scl: D3
  scan: True

sensor:
  # Lux Sensor
  - platform: tsl2561
    name: "Lux Sensor"
    id: luxsensor
    icon: mdi:brightness-7
    update_interval: 60s
    # Day:Open Night:Close Automation
    on_value_range:
      - above: 20
        then:
          - cover.open: door
      - below: 5
        then:
          - cover.close: door
  # Temp/Humidity
  - platform: dht
    model: dht11
    pin: D2
    temperature:
      name: "Chicken House Temperature"
    humidity:
      name: "Chicken House Humidity"
    update_interval: 60s
  # Wifi Signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

# Status Sensor
binary_sensor:
  - platform: status
    name: "ESP01 Status"

# Stepper Motor
stepper:
  - platform: a4988
    step_pin: D6
    dir_pin: D7
    sleep_pin: D5
    max_speed: 200 steps/s
    id: door_stepper

# Stepper Open/Close Cover
cover:
  - platform: template
    name: "Door"
    id: door
    device_class: door
    open_action:
      - stepper.set_target:
          id: door_stepper
          target: -1000
    close_action:
      - stepper.set_target:
          id: door_stepper
          target: 1000
    stop_action:
      - stepper.set_target:
          id: door_stepper
          target: !lambda return id(door_stepper).current_position;
    optimistic: True
```

**Logs (if applicable):**

```
[21:35:46][D][cover:072]: 'Door' - Setting
[21:35:46][D][cover:082]:   Command: OPEN
[21:35:46][D][cover:152]: 'Door' - Publishing:
[21:35:46][D][cover:158]:   State: OPEN
[21:35:46][D][cover:168]:   Current Operation: IDLE
[21:36:04][D][tsl2561:126]: Got illuminance=2.9lx
[21:36:04][D][sensor:092]: 'Lux Sensor': Sending state 2.94932 lx with 1 decimals of accuracy
[21:37:04][D][tsl2561:126]: Got illuminance=2.9lx
[21:37:04][D][sensor:092]: 'Lux Sensor': Sending state 2.94932 lx with 1 decimals of accuracy

```

**Additional information and things you've tried:**
- Waiting a few sensor reporting intervals - up to 20
- Rebooting the board (state is remembered via "esp8266_restore_from_flash: True") to try and force it to evaluate my value range again (maybe esp and HA clash when I open/close in HA?)
- Setting a delay with "- delay: 10s" before both of my cover.close/cover.open actions
- Setting both the "above" and "below" values for both of my ranges
