### ISSUE TITLE
Discrepancy with config of HLW8012 component (BL0937) between ESP82xx and BK27xx platforms

### ISSUE THREAD

**Issue by jordan875** [esphome/issues#5812]
### The problem

When using the HLW8012 component with model BL0937 on Beken BK2731N, the "voltage_divider" value must be half of what it is with the same config on ESP82xx to achieve the same voltage reading.

The power (wattage) output reads the same (and correctly) with the same "current_resistor" value between platforms.

**Background:**
I have multiple smart plugs that were delivered with CB2S modules containing BK2731N chips. In one smart plug I transplanted an ESP-02S module with ESPHome installed. I flashed ESPHome to the CB2S module in another identical smart plug. Using the same config (accounting for pin naming differences) is not possible between the two platforms, all sensors from BL0937 read zero.  If the "cf" and "cf1" pins are inverted for the BK2731, values are generated but they are correct. (On ESP only the "sel" pin is inverted.) If all BL0937 pins are inverted for the BK2731, the sensors show values, but the voltage shown is double the true voltage. This can be reduced to what seems to be the correct voltage by halving the "voltage_divider" value. 

### Which version of ESPHome has the issue?

2024.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.3

### What platform are you using?

BK72XX

### Board

CB2S

### Component causing the issue

hlw8012

### Example YAML snippet

```yaml
**Config on BK2731N:**

sensor:
  - platform: hlw8012
    model: BL0937
    cf_pin:
      number: P6
      inverted: true
    cf1_pin: 
      number: P7
      inverted: true
    sel_pin:
      number: P26
      inverted: true
    current_resistor: "0.001"
    voltage_divider: "1560"
    current:
      name: "${name} Current"
      unit_of_measurement: A
      accuracy_decimals: 3
      state_class: measurement
      device_class: current
    voltage:
      name: "${name} Voltage"
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
    power:
      name: "${name} Wattage"
      unit_of_measurement: W
      id: wattage
      state_class: measurement
      device_class: power
    change_mode_every: 4
    update_interval: 10s
```

**Config on ESP:**
```
  - platform: hlw8012
    model: BL0937
    cf_pin: GPIO5
    cf1_pin: GPIO4
    sel_pin:
      number: GPIO14
      inverted: true
    current_resistor: "0.001"
    voltage_divider: "780"
    current:
      name: "${name} Current"
      unit_of_measurement: A
      accuracy_decimals: 3
      state_class: measurement
      device_class: current
    voltage:
      name: "${name} Voltage"
      unit_of_measurement: V
      state_class: measurement
      device_class: voltage
    power:
      name: "${name} Wattage"
      unit_of_measurement: W
      id: wattage
      state_class: measurement
      device_class: power
    change_mode_every: 4
    update_interval: 10s
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

**Comment by jordan875** [comment]
Adding a comment to remove the stale marker as this remains an issue

**Comment by jordan875** [comment]
I did look into it a little bit when it happened, but I can't quite remember what I came up with. I am also using 230/240/250V. In the end I found a config that seems to work - I think I remember that something still wasn't quite right, but after calibrating with another device I arrived at the following that gives fairly realistic readings. Give it a try and see if it makes your readings make more sense.

```
sensor:
  - platform: hlw8012
    model: BL0937
    cf_pin:
      number: P6 # yours might differ
      inverted: true
    cf1_pin: 
      number: P7 # yours might differ
      inverted: true
    sel_pin:
      number: P26 # yours might differ
      inverted: true
    current_resistor: "0.001"
    voltage_divider: "790"
```

On separate note, I'd be cautious about using any Tuya smart plug for charging a Tesla (even at 9 amps) because in many cases they aren't very well designed to handle such a current for long periods. Apologies if I am telling you something you already know!
