### ISSUE TITLE
ADS1115 readings started fluctuate after short WiFi outage

### ISSUE THREAD

**Issue by Masterz69** [esphome/issues#5814]
### The problem

WiFi network was not available for couple of minutes during software upgrade.
Devices reconnected to WiFi & HA with no issues, not rebooted as downtime was short.
But: ADS1115 readings started to fluctuate much after WiFi outage and till device manually rebooted.

Fluctuates all 4 channels, providing config for one channel.

### Which version of ESPHome has the issue?

2024.4.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

ESP-Wroom32

### Component causing the issue

ads1115

### Example YAML snippet

```yaml
esp32:
  board: esp32dev
  framework:
    type: arduino

i2c:
  sda: GPIO21
  scl: GPIO22
  frequency: 800kHz

sensor:
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 6.144
    id: adc_vcc
    name: 'Voltage Supply'
    update_interval: 2s
    accuracy_decimals: 2
```

### Additional information

![image](https://github.com/esphome/issues/assets/15225823/e5499642-d84d-47ab-991c-364227bb5b5e)

Left side - short outages during WiFi upgrade.
Right side - after device restart.
