### ISSUE TITLE
AGS10 CONNECTION PROBLEM WITH TCA9548A

### ISSUE THREAD

**Issue by mehmetkrkmz94** [esphome/issues#5815]
### The problem

Hello. I want to use the ags10 air quality sensor and aht10 temperature sensor with tca9548a i2c multiplexer on esphome. I couldn't find a source. my code is below. When I write the code this way, I get "required key not provided." on line 42. I get an error. But when I delete the ags10 codes, it does not give any warning. installation is provided. I would be very happy if you could help me with this.

### Which version of ESPHome has the issue?

2024.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.4

### What platform are you using?

ESP32

### Board

WEMOS D1 MINI ESP32

### Component causing the issue

i2c

### Example YAML snippet

```yaml
esphome:
  name: ######
  friendly_name: #########

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "###############"

ota:
  password: "##############"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "##"
    password: "##"

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: True
  id: i2c0

tca9548a:
  - address: 0x70
    id: m0
    i2c_id: i2c0
    channels:
      - bus_id: m0channel0
        channel: 0
      - bus_id: m0channel1
        channel: 1
      - bus_id: m0channel2
        channel: 2
      - bus_id: m0channel3
        channel: 3
      - bus_id: m0channel4
        channel: 4
      - bus_id: m0channel5
        channel: 5
      - bus_id: m0channel6
        channel: 6
      - bus_id: m0channel7
        channel: 7

web_server:
  port: 80
  auth:
    username: ##
    password: '##'

text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: IP Adresi
    bssid:
      name: BSSID
    ssid:
      name: SSID

switch:
  - platform: gpio
    id: relay1
    pin: GPIO25
    name: "Röle-1"
  
  - platform: restart
    name: Yeniden Başlat

sensor:
  - platform: aht10
    i2c_id: m0channel0
    variant: AHT10
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
  
  - platform: ags10
    i2c_id: m0channel1
    tvoc:
      name: TVOC
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.5.0
INFO Reading configuration /config/esphome/ortam-izleme-v2.yaml...
Failed config

tca9548a: [source /config/esphome/test.yaml:39]
  - address: 0x70
    id: m0
    i2c_id: i2c0
    channels: 
      - bus_id: m0channel0
        channel: 0
      
      required key not provided.
      - bus_id: m0channel1
        channel: 1
      - bus_id: m0channel2
        channel: 2
      - bus_id: m0channel3
        channel: 3
      - bus_id: m0channel4
        channel: 4
      - bus_id: m0channel5
        channel: 5
      - bus_id: m0channel6
        channel: 6
      - bus_id: m0channel7
        channel: 7
```
