### ISSUE TITLE
AP fallback not working after upgrading ESPHome to 2024.5.0

### ISSUE THREAD

**Issue by rp2019433** [esphome/issues#5818]
### The problem

After upgrading ESPHome to version 2024.5.0, WiFi AP fallback (captive portal) is not working anymore. AP network is created and visible to any device that wants to connect, but it's not possible to join the ESPHome AP network.

This function is working properly in version 2024.3. Below affected configuration section:
```
wifi:
  ap:
    ssid: "device fallback"
    password: ""

captive_portal:
```

https://esphome.io/components/captive_portal.html

### Which version of ESPHome has the issue?

2024.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.4

### What platform are you using?

ESP32-IDF

### Board

Sonoff NSPanel

### Example YAML snippet

```yaml
wifi:
  ap:
    ssid: "device fallback"
    password: ""

captive_portal:
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
