### ISSUE TITLE
Update 2024.5.0, ESP8266 problem with modbus module connected to RX/TX pins

### ISSUE THREAD

**Issue by rnorth** [esphome/issues#5820]
### The problem

After upgrading to 2024.5.0 and applying updated firmware OTA, it is no longer possible to connect to the device via the API. This ESPHome device has a modbus MAX3485 module connected to the TX/RX UART pins of the ESP8266. *It seems that this issue, #5790 and #5816 have a common element: use of UART.*

### Which version of ESPHome has the issue?

2024.5.0 

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

NodeMCU

### Component causing the issue

Modbus / UART

### Example YAML snippet

```yaml
Relevant elements:


esp8266:
  board: nodemcuv2

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  reboot_timeout: 1min

uart:
  id: mod_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
  stop_bits: 1
  debug:
    direction: BOTH
    dummy_receiver: false
    # after:
    #   delimiter: [0xF8,0xF7,0xF6,0xF5]
```
```


### Anything in the logs that might be useful for us?

```txt
INFO Successfully connected to ... in 0.003s
WARNING ...: Connection error occurred: ...: EOF received
WARNING Can't connect to ESPHome API for ...: ...: EOF received (SocketClosedAPIError)
```
