### ISSUE TITLE
Firmware update failure due to binary size error

### ISSUE THREAD

**Issue by z3liff** [esphome/issues#5823]
### The problem

I upgraded to 2024.5.0 and now both 8266 devices I use are failing intermittently to update over the network.  I get an "unknown error from ESP" when the firmware should upload.  If I reboot the ESP8266, it will update.  It appears to be a random failure, as sometimes the update works without a reboot.  I never noticed any such issue before upgrading to 2024.5.0.

After this issue, and all the other issues detailed in #5821 I decided to revert to an earlier version of ESPHome (2024.4.2).  Initial flash attempt for 1 of the 2 ESP 8266 devices failed to go from 2024.5.0 to 2024.4.2.  Multiple firmware flashes once running 2024.4.2 have succeeded without issue, which leads me to believe this is an issue explicitly present in 2024.5.0.

### Which version of ESPHome has the issue?

2024.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.4

### What platform are you using?

ESP8266

### Board

D1 Mini

### Example YAML snippet

```yaml
substitutions:
  name: haks-kitchen
  friendly_name: Kitchen HAKS

packages:
  haks:
    url: https://PigLab.ReaperLegion.net/home-automation/hass/esphome/packages/haks.git
    files:
      - core.yaml
      - WiFi.yaml
      - BME280.yaml
      - PMS7003.yaml
      - OLED_US_kPa.yaml

api:
  encryption:
    key: !secret haks_key

ota:
  password: !secret haks_ota
  version: 2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  ap:
    password: !secret haks_ota

# Sunrise/sunset for OLED day/night mode (reduce burn-in)
sun:
  latitude: !secret latitude
  longitude: !secret longitude
```

### Anything in the logs that might be useful for us?

```txt
esp8266_copy_factory_bin([".pioenvs/haks-kitchen/firmware.bin"], [".pioenvs/haks-kitchen/firmware.elf"])
======================== [SUCCESS] Took 116.45 seconds ========================
INFO Successfully compiled program.
INFO Connecting to xxxxxxx
INFO Uploading /data/build/haks-kitchen/.pioenvs/haks-kitchen/firmware.bin (601856 bytes)
INFO Compressed to 412367 bytes
ERROR Error binary size: Unknown error from ESP
```
