### ISSUE TITLE
Issue with accuracy_decimals

### ISSUE THREAD

**Issue by roykrikke** [esphome/issues#5830]
### The problem

https://esphome.io/components/sensor/index.html >> states:
_accuracy_decimals (Optional, int): Manually set the number of decimals to use when reporting values. This does not impact the actual value reported to Home Assistant, it just sets the number of decimals to use when displaying it._

The part: _"This does not impact the actual value reported to Home Assistant" in my view is not correct."_

When I use this this with modbus component:
```
sensor:
- platform: modbus_controller
  modbus_controller_id: ${device_name}
  name: "${device_name}_phase_1_line_to_neutral_volts"
  id: "${device_name}_phase_1_line_to_neutral_volts"
  <<: &volts_sensor
    address: 0
    register_type: read
    value_type: FP32
    register_count: 4
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
```
    
Output was:
`[20:21:49][D][sensor:094]: 'pv_phase_1_line_to_neutral_volts': Sending state 229.98114 V with 0 decimals of accuracy`

With this config I see 0 decimals in HA History of the entity.

But when is did this (i added _accuracy_decimals: 2_):
sensor:
```
- platform: modbus_controller
  modbus_controller_id: ${device_name}
  name: "${device_name}_phase_1_line_to_neutral_volts"
  id: "${device_name}_phase_1_line_to_neutral_volts"
  <<: &volts_sensor
    address: 0
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
    register_count: 4
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
```
 
Output was:
`[20:48:36][D][sensor:094]: 'pv_phase_3_line_to_neutral_volts': Sending state 229.44279 V with 2 decimals of accuracy`

With this config I see 2 decimals in HA History of the entity.

Is something wrong or is the documentation outdated or am I missing the documentation somehow?

### Which version of ESPHome has the issue?

Core 2024.5.4 Supervisor 2024.05.1 Operating System 12.3 Frontend 20240501.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP32
