### ISSUE TITLE
Door with limit switch error if in middle of stroke

### ISSUE THREAD

**Issue by Ventosinos** [esphome/issues#5838]
### The problem

Hi everyone,

I'm new to EspHome, and my first project shows a weird behaviour. I hope someone could help me, because I have no idea about where is the problem.

I have an ESP32-CAM controlling a motor through a H-Bridge (DRV 8871). It also has two limit switches on each top.  I'm using an ESP32 CAM because I would like to add a camera in the future.

I set up two binay sensors, one for each limit switch. I also set up two switches, one for each conection of the H-Bridge.

When the door is at the lower endstop (door closed) position, I can open the door without any problems.
When it is at the upper enstop (door open) position, I can close the door without any problems.
But when the door is at the middle of the stroke, when I turn on any of the switches, the door goes on the direction I selected, but after a few seconds, it stops and the ESP reboots. 

I read the YAML time after time, and I couldn't find anything out of normal.

### Which version of ESPHome has the issue?

2024.3.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.4.3

### What platform are you using?

ESP32

### Board

Official Espressif ESP32 cam

### Component causing the issue

Binary_sensor or switch

### Example YAML snippet

```
esphome:
  name: galineiro
  friendly_name: Galiñeiro

esp32:
  board: esp32cam
  framework: 
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "B/VR99HqWdSz8CCF4niG+rBz8w9rQoKhyK2pK1oiLm4="

ota:
  password: "b041f5dd23f3a0ca6b9b59f43535bb60"

wifi:
  networks:
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  - ssid: !secret wifi_ssid3
    password: !secret wifi_password3
  
  manual_ip:
    static_ip: 192.168.1.11
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.4.4

  ap:
    ssid: "Galineiro Fallback Hotspot"
    password: "Galiñeiro"

captive_portal:

web_server:
  port: 80
 
text_sensor:
  - platform: wifi_info
    ip_address:
      name: Direccion IP
    ssid:
      name: Nome da rede
    mac_address:
      name: MAC
    scan_results:
      name: Redes Dispoñibles

#Controladores, cara o drv do motor. Pines 13 e 33
switch:
- platform: gpio
  pin: GPIO13 #12 #GPIO2
  name: "Abrir galiñeiro"
  id: abrir_gali
- platform: gpio
  pin: GPIO33 #15
  name: "Cerrar galiñeiro"
  id: cerrar_gali

# Sensores, desde o final de carrera NO. Cando a porta chega ao final de carrera, accionase, e desde o com chega unha señal que fai que pare. Ao mesmo tempo, o final de carrera desconecta o abrir.
#O gpio 2 non vai coa wifi
binary_sensor:
- platform: gpio
  pin: GPIO14 #1 #4 2 no va, 13 no va, 16 no carga. Quitar o led 
  name: Galiñeiro Aberto
  id: gali_aberto
- platform: gpio
  pin: GPIO4
  name: Galiñeiro Cerrado
  id: gali_cerrado

```

### Anything in the logs that might be useful for us?

> Logs only show the first activation of the switch:
> INFO ESPHome 2024.3.2
> INFO Reading configuration /config/galineiro.yaml...
> INFO Starting log output from 192.168.1.11 using esphome API
> INFO Successfully connected to galineiro @ 192.168.1.11 in 0.027s
> INFO Successful handshake with galineiro @ 192.168.1.11 in 0.088s
> [14:20:20][I][app:102]: ESPHome version 2024.3.2 compiled on May 22 2024, 13:57:55
> [14:20:20][C][wifi:580]: WiFi:
> [14:20:21][C][wifi:408]:   Local MAC: A0:B7:65:60:03:00
> [14:20:21][C][wifi:413]:   SSID: [redacted]
> [14:20:21][C][wifi:416]:   IP Address: 192.168.1.11
> [14:20:21][C][wifi:420]:   BSSID: [redacted]
> [14:20:21][C][wifi:421]:   Hostname: 'galineiro'
> [14:20:21][C][wifi:423]:   Signal strength: -27 dB ▂▄▆█
> [14:20:21][C][wifi:427]:   Channel: 11
> [14:20:21][C][wifi:428]:   Subnet: 255.255.255.0
> [14:20:21][C][wifi:429]:   Gateway: 192.168.1.1
> [14:20:21][C][wifi:430]:   DNS1: 192.168.1.1
> [14:20:21][C][wifi:431]:   DNS2: 8.8.4.4
> [14:20:21][C][logger:166]: Logger:
> [14:20:21][C][logger:167]:   Level: DEBUG
> [14:20:21][C][logger:169]:   Log Baud Rate: 115200
> [14:20:21][C][logger:170]:   Hardware UART: UART0
> [14:20:21][C][switch.gpio:068]: GPIO Switch 'Abrir galiñeiro'
> [14:20:21][C][switch.gpio:091]:   Restore Mode: always OFF
> [14:20:21][C][switch.gpio:031]:   Pin: GPIO13
> [14:20:21][C][switch.gpio:068]: GPIO Switch 'Cerrar galiñeiro'
> [14:20:21][C][switch.gpio:091]:   Restore Mode: always OFF
> [14:20:21][C][switch.gpio:031]:   Pin: GPIO33
> [14:20:21][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Galiñeiro Aberto'
> [14:20:21][C][gpio.binary_sensor:016]:   Pin: GPIO14
> [14:20:21][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Galiñeiro Cerrado'
> [14:20:21][C][gpio.binary_sensor:016]:   Pin: GPIO4
> [14:20:21][C][wifi_info:013]: WifiInfo Mac Address 'MAC'
> [14:20:21][C][captive_portal:088]: Captive Portal:
> [14:20:21][C][web_server:169]: Web Server:
> [14:20:21][C][web_server:170]:   Address: 192.168.1.11:80
> [14:20:21][C][mdns:115]: mDNS:
> [14:20:21][C][mdns:116]:   Hostname: galineiro
> [14:20:21][C][ota:096]: Over-The-Air Updates:
> [14:20:21][C][ota:097]:   Address: 192.168.1.11:3232
> [14:20:21][C][ota:100]:   Using Password.
> [14:20:21][C][ota:103]:   OTA version: 2.
> [14:20:21][C][api:139]: API Server:
> [14:20:21][C][api:140]:   Address: 192.168.1.11:6053
> [14:20:21][C][api:142]:   Using noise encryption: YES
> [14:20:21][C][wifi_info:011]: WifiInfo SSID 'Nome da rede'
> [14:20:21][C][wifi_info:010]: WifiInfo Scan Results 'Redes Dispoñibles'
> [14:20:21][C][wifi_info:009]: WifiInfo IPAddress 'Direccion IP'
> [14:20:26][D][switch:012]: 'Cerrar galiñeiro' Turning ON.
And then it reboots
### Additional information
If someone wants to see the problem, here is a link:
https://youtube.com/shorts/D6BWDud5Eug?feature=share
I'm not a youtuber, I published the video there because I couldn't attach the file (>10 MB)
