### ISSUE TITLE
Could not inherit MQTTClientComponent with my custom class

### ISSUE THREAD

**Issue by ahsan-kaukab** [esphome/issues#5840]
### The problem

Hello I am trying to inherit MQTTClientComponent with my own custom class as below
```
class MQTTWLRRComponent : public Component , public MQTTClientComponent 
{
...
...
};
```

but when i try to compile it its gives error as below
![image](https://github.com/esphome/issues/assets/71211526/e5e69a52-e120-4fa8-bb1a-850fcce7ed8f)

I have added following lines in my esphome/core/defines.h
`#define USE_MQTT`

so defines file look like this
![image](https://github.com/esphome/issues/assets/71211526/ced608aa-2aa6-450c-b96d-26178956b72d)

Ias there any thing that I am missing ?

### Which version of ESPHome has the issue?

1.21.0b3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

My custom Component

### Example YAML snippet

```yaml
esphome:
  name: myespdevice  # Change to avoid underscore warning
  platform: ESP32
  board: esp32dev

external_components:
  - source: "./components"
  
wifi:
  ssid: "your_ssid"
  password: "your_password"

mqtt:
  broker: "your_mqtt_broker"
  username: "your_username"
  password: "your_password"

logger:
  level: DEBUG

ota:

mqtt_wl_rr:
  id: my_mqtt_wl_rr
  component_name: "mqtt_wl_rr"
  mqtt_topic: "your_device_prefix/mqtt_wl_rr/config"
  mac_address: "00:11:22:33:44:55"
```

### Anything in the logs that might be useful for us?

```txt
flinux@192:~/Desktop/esphome_component_bthome-master$ esphome compile esphome.yaml 
INFO ESPHome 2024.5.0
INFO Reading configuration esphome.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing myespdevice (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/myespdevice/src/esphome/components/mqtt_wl_rr/mqtt_wl_rr.cpp.o
Compiling .pioenvs/myespdevice/src/main.cpp.o
In file included from src/esphome/components/mqtt_wl_rr/mqtt_wl_rr.cpp:1:
src/esphome/components/mqtt_wl_rr/mqtt_wl_rr.h:8:1: error: expected class-name before '{' token
 {
 ^
In file included from src/esphome.h:35,
                 from src/main.cpp:3:
src/esphome/components/mqtt_wl_rr/mqtt_wl_rr.h:8:1: error: expected class-name before '{' token
 {
 ^
*** [.pioenvs/myespdevice/src/esphome/components/mqtt_wl_rr/mqtt_wl_rr.cpp.o] Error 1
*** [.pioenvs/myespdevice/src/main.cpp.o] Error 1
```
