### ISSUE TITLE
remote_transmitter.transmit_rc_switch_raw & protocol :8 NO DATA TRANSMITTED

### ISSUE THREAD

**Issue by pieca2** [esphome/issues#5841]
### The problem

HI,
Got an 433Mhz RF emitter and receiver on an ESP32.
Both my emitter and receiver are working properly.

I'm capturing this data (protocol:8) from my remote :
`[I][remote.rc_switch:261]: Received RCSwitch Raw: protocol=8 data='0110101001101010011010011001101010101010101010100110100110101010'`

sending this data with protocol:8  doesn't send any RF signal : 

```
remote_transmitter.transmit_rc_switch_raw:
          code: '0110101001101010011010011001101010101010101010100110100110101010'
          protocol: 8
          repeat:
            times: 3
            wait_time: 0s
```

But sending the same data with protocol:2 does send the right signal (but with the wrong protocol...)

```
remote_transmitter.transmit_rc_switch_raw:
          code: '0110101001101010011010011001101010101010101010100110100110101010'
          protocol: 2
          repeat:
            times: 3
            wait_time: 0s
```

Trying to send anything with protocol:8 doesn't seems to do anything...
Others protocols are working fine...

Any help should be really appreciated

### Which version of ESPHome has the issue?

2024.5.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.3

### What platform are you using?

ESP32

### Board

mini D1 ESP32 WROOM

### Component causing the issue

FS1000A or STX882 : same issue

### Example YAML snippet

```yaml
remote_receiver:
  pin: GPIO26
  dump:
    - rc_switch
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb

remote_transmitter:
  pin: GPIO27
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%

switch:
  - platform: template
    name: TestSwitch
    optimistic: true
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '0110101001101010011010011001101010101010101010100110100110101010'
          protocol: 8
          repeat:
            times: 3
            wait_time: 0s
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '0110101001101010011010011001101010101010101010100110101010101010'
          protocol: 8
          repeat:
            times: 3
            wait_time: 0s
```

### Anything in the logs that might be useful for us?

```txt
#With Protocol 8 : NO DATA TRANSMITED

[17:08:14][D][switch:012]: 'Atmos speakers' Turning ON.
[17:08:15][D][switch:055]: 'Atmos speakers': Sending state ON

#With Protocol 2 : DATA IS TRANSMITTED
[17:09:53][D][switch:012]: 'Atmos speakers' Turning ON.
[17:09:53][D][switch:055]: 'Atmos speakers': Sending state ON
[17:09:53][I][remote.rc_switch:261]: Received RCSwitch Raw: protocol=2 data='0110101001101010011010011001101010101010101010100110100110101010'
[17:09:53][I][remote.rc_switch:261]: Received RCSwitch Raw: protocol=2 data='0110101001101010011010011001101010101010101010100110100110101010'
[17:09:53][I][remote.rc_switch:261]: Received RCSwitch Raw: protocol=2 data='011010100110101001101001100110101010101010101010011010011010101'
```

### Additional information

replacing : protocol: 8 by protocol:2 send the data...
No RC data seems to be send when protocol:8 is used
