### ISSUE TITLE
Climate ignoring current_temperature_state_topic

### ISSUE THREAD

**Issue by kerryland** [esphome/issues#5844]
### The problem

I have a climate configuration (see below) that defines `current_temperature_state_topic: "bedroom/temp"`, which, to my understanding, means that the climate control will obtain the "current temperature" from the given queue.

If I publish a message of "25" to that queue (with mqttx, or Home Assistant service) nothing appears in the Home Assistant dashboard -- the "current temperature" remains "0".

![image](https://github.com/esphome/issues/assets/398113/c079bd1b-4902-4d25-ad5f-cab072385d35)

Home Assistant mqtt publish example:
```yaml
service: mqtt.publish
data:
  topic: bedroom/temp
  payload: "25"
```

### Which version of ESPHome has the issue?

2024.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.3

### What platform are you using?

ESP8266

### Board

DIY

### Component causing the issue

climate

### Example YAML snippet

```yaml
esphome:
  name: daikin-heatpump
  friendly_name: daikin heatpump

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
  password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Daikin-Heatpump Fallback Hotspot"
    password: "..."

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  
remote_transmitter:
  pin: GPIO16
  carrier_duty_percent: 50%

climate:
  - platform: daikin
    name: "Daikin Heatpump"
    current_temperature_state_topic: "bedroom/temp"
```
