### ISSUE TITLE
Two different buses, one bus shadows another

### ISSUE THREAD

**Issue by Limych** [esphome/issues#5852]
### The problem

I'm trying to update an outdoor temperature and humidity sensor to ESPHome. The device worked perfectly under Tuya. By analyzing the printed circuit board and using trial firmware, all internal elements were found.

Among others, there is an HTU21D sensor operating via an I2C bus and a display similar to the TM1638. They use a common clock pin (SCL for I2C, CLK for display)

When working separately, everything functions correctly. But when adding both components at the same time, the display does not work. Although no errors are given.

### Which version of ESPHome has the issue?

2024.5.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.4

### What platform are you using?

ESP8266

### Board

Konlen WiFi TH Sensor (TYWE3S inside)

### Component causing the issue

tm1638

### Example YAML snippet

```yaml
esphome:
  name: "konlen-wifi-th-sensor"
  platform: ESP8266 
  board: esp_wroom_02

i2c:
  sda: GPIO14
  scl:
    number: GPIO12
    allow_other_uses: True
  scan: False

sensor:
  - platform: htu21d
    model: htu21d
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"

display:
  platform: tm1638
  id: gn1638_display
  stb_pin: GPIO13
  clk_pin:
    number: GPIO12
    allow_other_uses: True
  dio_pin: GPIO4
  intensity: 1 # 0...7
  #update_interval: 1s
  lambda: |-
    it.print("0123");
```
