### ISSUE TITLE
Using IR Climate will reset the WiFi connection of the AC.

### ISSUE THREAD

**Issue by Machaeon** [esphome/issues#5855]
### The problem

After receiving a command from the IR Climate component, the air conditioner disconnects from WiFi. Reconnection using the mobile app is required.
```
climate:
- platform: gree
  name: "AC"
  sensor: current_temperature
  model: yac
```

### Which version of ESPHome has the issue?

2024.5.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

core-2024.5.5

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

IR Remote Climate
