### ISSUE TITLE
Esp32S3 bootloop with arduino and esp-idf

### ISSUE THREAD

**Issue by vekexasia** [esphome/issues#5858]
### The problem

I've been trying to get an ESP32-S3-WROOM-1-N16R8 to be working into ESPHome.

I've done the following schematic :
![image](https://github.com/esphome/issues/assets/200523/6253e0e0-db00-425c-8282-34d3a2a103f7)

As u can see i am attaching to the esp32 via a programming header from which I provide +5V.

Programming goes fine, I did it countless times. But i was unable to find any working esphome configuration that let the module boot and attach to WiFi. only sporadically I was able to get it connect... and I'm not sure why.

### Things I tried 

- both arduino and esp-idf
- injecting another +5V to make sure there was enough power.
- measured with multimeter
- desoldered and resoldered and changed module
- espidf with platform_version 6.6.0 and version latest
- with and wthout psram
- I'm flashing using the web esphome flasher with modern format

------
Here logs for arduino 

```
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x29 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x43c
load:0x403c9700,len:0xbec
load:0x403cc700,len:0x2a3c
entry 0x403c98d8
E (179) psram: PSRAM ID read error: 0x00ffffff
.[0;32m[I][logger:156]: Log initialized.[0m
.[0;35m[C][ota:483]: There have been 4 suspected unsuccessful boot attempts..[0m
.[0;36m[D][esp32.preferences:114]: Saving 1 preferences to flash....[0m
.[0;36m[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed.[0m
.[0;32m[I][app:029]: Running through setup()....[0m
.[0;35m[C][wifi:038]: Setting up WiFi....[0m
.[0;35m[C][wifi:051]: Starting WiFi....[0m
.[0;35m[C][wifi:052]:   LocalÂ MAC: F4:12:FA:DC:97:98.[0m
.[0;36m[D][wifi:462]: Starting scan....[0m
.[0;33m[W][component:157]: Component wifi set Warning flag: unspecifieüESP-ROM:esp32s3-20210327
```

With the following config:

``` 
esphome:
  name: testdiovan
  friendly_name: testdiovan
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_ESP32S3_DEV"
      # Has PSRAM
      - "-DBOARD_HAS_PSRAM"
      - "-DARDUINO_USB_MODE=1"
      - "-DARDUINO_RUNNING_CORE=1"
      - "-DARDUINO_EVENT_RUNNING_CORE=1"
    #board_build.flash_mode: dio
    #board_build.f_flash: 40000000L
    #board_build.flash_size: 16MB
    
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: arduino
    #platform_version: 6.6.0
    #sdkconfig_options:
      #CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      #CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      #CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
    #  CONFIG_ESPTOOLPY_FLASHSIZE_16MB: y
      #CONFIG_AUDIO_BOARD_CUSTOM: "y"
      #CONFIG_TESTaaaaa: "y"
      

psram:
  mode: octal
  speed: 80MHz
```  

-----

LOG with esp-idf
```
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x29 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:2
load:0x3fce3818,len:0x1750
load:0x403c9700,len:0x4
load:0x403c9704,len:0xc00
load:0x403cc700,len:0x2e04
entry 0x403c9908
.[0;32mI (30) boot: ESP-IDF 5.1.2 2nd stage bootloader.[0m
.[0;32mI (30) boot: compile time May 27 2024 22:01:20.[0m
.[0;32mI (30) boot: Multicore bootloader.[0m
.[0;32mI (33) boot: chip revision: v0.1.[0m
.[0;32mI (37) boot.esp32s3: Boot SPI Speed : 40MHz.[0m
.[0;32mI (42) boot.esp32s3: SPI Mode       : DIO.[0m
.[0;32mI (46) boot.esp32s3: SPI Flash Size : 16MB.[0m
.[0;32mI (51) boot: Enabling RNG early entropy source....[0m
.[0;32mI (56) boot: Partition Table:.[0m
.[0;32mI (60) boot: ## Label            Usage          Type ST Offset   Length.[0m
.[0;32mI (67) boot:  0 otadata          OTA data         01 00 00009000 00002000.[0m
.[0;32mI (75) boot:  1 phy_init         RF data          01 01 0000b000 00001000.[0m
.[0;32mI (82) boot:  2 app0             OTA app          00 10 00010000 007c0000.[0m
.[0;32mI (90) boot:  3 app1             OTA app          00 11 007d0000 007c0000.[0m
.[0;32mI (97) boot:  4 nvs              WiFi data        01 02 00f90000 0006d000.[0m
.[0;32mI (105) boot: End of partition table.[0m
.[0;32mI (109) esp_image: segment 0: paddr=00010020 vaddr=3c0a0020 size=2f3ach (193452) map.[0m
.[0;32mI (165) esp_image: segment 1: paddr=0003f3d4 vaddr=3fc97200 size=00c44h (  3140) load.[0m
.[0;32mI (167) esp_image: segment 2: paddr=00040020 vaddr=42000020 size=9e9f4h (649716) map.[0m
.[0;32mI (333) esp_image: segment 3: paddr=000dea1c vaddr=3fc97e44 size=03bc8h ( 15304) load.[0m
.[0;32mI (337) esp_image: segment 4: paddr=000e25ec vaddr=40374000 size=13174h ( 78196) load.[0m
.[0;32mI (369) boot: Loaded app from partition at offset 0x10000.[0m
.[0;32mI (369) boot: Disabling RNG early entropy source....[0m
.[0;32mI (381) cpu_start: Multicore app.[0m
.[0;32mI (381) octal_psram: vendor id    : 0x0d (AP).[0m
.[0;32mI (381) octal_psram: dev id       : 0x02 (generation 3).[0m
.[0;32mI (384) octal_psram: density      : 0x03 (64 Mbit).[0m
.[0;32mI (390) octal_psram: good-die     : 0x01 (Pass).[0m
.[0;32mI (395) octal_psram: Latency      : 0x01 (Fixed).[0m
.[0;32mI (400) octal_psram: VCC          : 0x01 (3V).[0m
.[0;32mI (405) octal_psram: SRF          : 0x01 (Fast Refresh).[0m
.[0;32mI (411) octal_psram: BurstType    : 0x01 (Hybrid Wrap).[0m
.[0;32mI (417) octal_psram: BurstLen     : 0x01 (32 Byte).[0m
.[0;32mI (423) octal_psram: Readlatency  : 0x02 (10 cycles@Fixed).[0m
.[0;32mI (429) octal_psram: DriveStrength: 0x00 (1/1).[0m
.[0;32mI (435) MSPI Timing: PSRAM timing tuning index: 5.[0m
.[0;32mI (439) esp_psram: Found 8MB PSRAM device.[0m
.[0;32mI (444) esp_psram: Speed: 80MHz.[0m
.[0;32mI (448) cpu_start: Pro cpu up..[0m
.[0;32mI (452) cpu_start: Starting app cpu, entry point is 0x40375ed4.[0m
.[0;32mI (0) cpu_start: App cpu up..[0m
.[0;32mI (748) esp_psram: SPI SRAM memory test OK.[0m
.[0;32mI (757) cpu_start: Pro cpu start user code.[0m
.[0;32mI (757) cpu_start: cpu freq: 240000000 Hz.[0m
.[0;32mI (757) cpu_start: Application information:.[0m
.[0;32mI (760) cpu_start: Project name:     testdiovan.[0m
.[0;32mI (766) cpu_start: App version:      2024.5.2.[0m
.[0;32mI (771) cpu_start: Compile time:     May 27 2024 22:01:04.[0m
.[0;32mI (777) cpu_start: ELF file SHA256:  968bda9fce6200dd....[0m
.[0;32mI (783) cpu_start: ESP-IDF:          5.1.2.[0m
.[0;32mI (787) cpu_start: Min chip rev:     v0.0.[0m
.[0;32mI (792) cpu_start: Max chip rev:     v0.99 .[0m
.[0;32mI (797) cpu_start: Chip rev:         v0.1.[0m
.[0;32mI (802) heap_init: Initializing. RAM available for dynamic allocation:.[0m
.[0;32mI (809) heap_init: At 3FCA00B8 len 00049658 (293 KiB): DRAM.[0m
.[0;32mI (815) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM.[0m
.[0;32mI (822) heap_init: At 600FE010 len 00001FD8 (7 KiB): RTCRAM.[0m
.[0;32mI (828) esp_psram: Adding pool of 8192K of PSRAM memory to heap allocator.[0m
.[0;32mI (836) spi_flash: detected chip: gd.[0m
.[0;32mI (840) spi_flash: flash io: dio.[0m
.[0;32mI (845) sleep: Configure to isolate all GPIO pins in sleep state.[0m
.[0;32mI (851) sleep: Enable automatic switching of GPIO sleep configuration.[0m
.[0;32mI (858) app_start: Starting scheduler on CPU0.[0m
.[0;32mI (863) app_start: Starting scheduler on CPU1.[0m
.[0;32mI (863) main_task: Started on CPU0.[0m
.[0;32mI (873) main_task: Calling app_main().[0m
.[¦ç.[0;32m[I][logger:156]: Log initialized.[0m
.[0;35m[C][ota:483]: There have been 5 suspected unsuccessful boot attempts..[0m
.[0;36m[D][esp32.preferences:114]: Saving 1 preferences to flash....[0m
.[0;36m[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed.[0m
.[0;32m[I][app:029]: Running through setup()....[0m
.[0;35m[C][wifi:038]: Setting up WiFi....[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (999) pp: pp rom version: e7ae62f.[0m
.[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (1005) net80211: net80211 rom version: e7ae62f.[0m
.[0m
.[0;36m[D][esp-idf:000]: I (1016) wifi:.[0m
.[0;36m[D][esp-idf:000]: wifi driver task: 3fcaf500, prio:23, stack:6656, core=0.[0m
.[0;36m[D][esp-idf:000]: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1027) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: wifi firmware version: 91b9630.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1046) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: wifi certification version: v7.0.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1056) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: config NVS flash: enabled.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1076) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: config nano formating: disabled.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1097) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: Init data frame dynamic rx buffer num: 32.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1107) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: Init static rx mgmt buffer num: 5.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1128) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: Init management short buffer num: 32.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1148) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: Init dynamic tx buffer num: 32.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1169) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: Init tx cache buffer num: 32.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1179) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: Init static tx FG buffer num: 2.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1199) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: Init static rx buffer size: 1600.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1210) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: Init static rx buffer num: 10.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1230) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: Init dynamic rx buffer num: 32.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (1251) wifi_init: rx ba win: 6.[0m
.[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (1251) wifi_init: tcpip mbox: 32.[0m
.[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (1261) wifi_init: udp mbox: 6.[0m
.[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (1261) wifi_init: tcp mbox: 6.[0m
.[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (1271) wifi_init: tcp tx win: 5744.[0m
.[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (1281) wifi_init: tcp rx win: 5744.[0m
.[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (1292) wifi_init: tcp mss: 1440.[0m
.[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (1292) wifi_init: WiFi IRAM OP enabled.[0m
.[0m
.[0;36m[D][esp-idf:000]: .[0;32mI (1302) wifi_init: WiFi RX IRAM OP enabled.[0m
.[0m
.[0;35m[C][wifi:051]: Starting WiFi....[0m
.[0;35m[C][wifi:052]:   LocalÂ MAC: F4:12:FA:DC:97:98.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: .[0;32mI (1323) phy_init: phy_version 620,ec7ec30,Sep  5 2023,13:49:13.[0m
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1366) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: mode : sta (f4:12:fa:dc:97:98).[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: 
.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: I (1367) wifi:.[0m
.[0;36m[D][esp-idf:000].[1;31m[wifi].[0;36m: enable tsf.[0m
.[0;36m[D][esp-idf:°ESP-ROM:esp32s3-20210327
```

with following config

```
esphome:
  name: testdiovan
  friendly_name: testdiovan
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 40000000L
    board_build.flash_size: 16MB
    
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
 # partitions: "/config/esphome/16mb.csv"
  framework:
    type: esp-idf
    version: latest
    platform_version: 6.6.0
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"
      CONFIG_ESP32_S3_BOX_BOARD: "y"

psram:
  mode: octal
  speed: 80MHz
   
# Enable logging
logger:
  hardware_uart: uart0
```

### Which version of ESPHome has the issue?

2024.5.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5

### What platform are you using?

ESP32

### Board

ESP32-S3-WROOM-1-N16R8

### Component causing the issue

who knows
