### ISSUE TITLE
Updating Device Failed

### ISSUE THREAD

**Issue by benyaffe** [esphome/issues#5859]
### The problem

Firmware OTA update of my ESP Bluetooth Proxy fails via the home assistant add-in.  Log attached.

[logs_esp32-bluetooth-proxy-83f6c4_run.txt](https://github.com/esphome/issues/files/15463279/logs_esp32-bluetooth-proxy-83f6c4_run.txt)

### Which version of ESPHome has the issue?

2024.5.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.4

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
substitutions:
  name: esp32-bluetooth-proxy-83f6c4
  friendly_name: Bluetooth Proxy - Under Bed - 83f6c4
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: [[redacted]]
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
