### ISSUE TITLE
[Climate] Fan mode Middle appears after High

### ISSUE THREAD

**Issue by loongyh** [esphome/issues#5860]
### The problem

The fan mode _Middle_ is ordered after _High_ which causes this weird quirk in the frontend:

![1](https://github.com/esphome/issues/assets/20846761/0ebf79ce-c7e0-4378-9773-cff1b7fa85cf)

Proper ordering should be Auto, Low, Medium, Middle, High.

Looking at the entity's state attributes, _Middle_ is indeed defined after _High_ in `fan_modes`:

![2](https://github.com/esphome/issues/assets/20846761/ee332580-b164-41cb-af5b-d0b1f819d4f7)

Home Assistant orders the fan modes according to what is passed in the entity's `fan_modes` attribute.
Could this be caused by [Middle being enumed after High in ClimateFanMode](https://github.com/esphome/esphome/blob/497cf8742f495918ed368eafdeafe72d53c5b9e2/esphome/components/climate/climate_mode.h#L60)?

I'm using a [custom component](https://github.com/echavet/MitsubishiCN105ESPHome) as in attached YAML snippet but after skimming through the code I don't see anything relevant to fan mode ordering.

### Which version of ESPHome has the issue?

2024.5.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.5

### What platform are you using?

ESP32

### Component causing the issue

climate

### Example YAML snippet

```yaml
external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

logger:
  level: INFO

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: 17
  rx_pin: 16

climate:
  - platform: cn105
    name: "AC"
    supports:
      mode: [COOL, DRY]
      fan_mode: [AUTO, LOW, MEDIUM, MIDDLE, HIGH]
      swing_mode: ["OFF", VERTICAL]
    visual:
      min_temperature: 16
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
    compressor_frequency_sensor:
      name: AC Compressor Frequency
      icon: mdi:hvac
    vertical_vane_select:
      name: AC Vane
      icon: mdi:arrow-oscillating
```
