### ISSUE TITLE
Overriding a library fails if the name contains a slash

### ISSUE THREAD

**Issue by sasodoma** [esphome/issues#5863]
### The problem

When a library with a custom name and a repo link is used as a PlatformIO lib_dep, the custom name should only be the name of the library, not `<owner>/<name>`. When PlatformIO parses the `lib_deps` and encounters a dependency in the format `custom-name=repo-link` the part before the `=` sign is the custom name that will be used for the folder where the library is installed. As can be seen in the function `_parse_custom_name()` in the file [meta.py](https://github.com/platformio/platformio-core/blob/develop/platformio/package/meta.py), the custom name cannot contain a forward slash.

The [ESPHome documentation](https://esphome.io/components/esphome.html#libraries) on the other hand, suggests that you use the full version of the name when overriding a library. This results in an error when compiling. Using just the library name, without the owner and the slash, results in the library being correctly overridden.

There are two possible fixes:

- Change the documentation, to only specify the library name when overriding a library, or
- Change the function [`Library.as_lib_dep()`](https://github.com/esphome/esphome/blob/5ae32e81c360a73f7ebe14d330d6e9d58eac324a/esphome/core/__init__.py#L455) to not return the owner and the slash.

I can make a pull request with either of the fixes, but I don't know which one would be preferred.

### Which version of ESPHome has the issue?

2024.5.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
# Example configuration entry
esphome:
  # ...
  libraries:
    # a library from PlatformIO
    - espressif/esp32-camera

    # a library bundled with Arduino
    - Wire

    # this is specified by the docs and doesn't work
    # use the git version of a library used by a component
    - esphome/Improv=https://github.com/improv-wifi/sdk-cpp.git#v1.0.0

    # this works
    - Improv=https://github.com/improv-wifi/sdk-cpp.git#v1.0.0
```
