### ISSUE TITLE
Automatic pausing of esp32_ble_tracker not working

### ISSUE THREAD

**Issue by hachi** [esphome/issues#5871]
### The problem

I'm not exactly sure of the edge case I'm hitting, but there is an automatic pause feature in esp32_ble_tracker that is not happening when I use ble_client.connect in automation.

According to @jesserockz:

"If you remove the manual stop, you should see _Pausing scan to make connection..._ in the logs"
"the auto stop was added 18 months ago"
"part of the bluetooth proxy upgrades"

My example YAML supplied is sort of working, but completely breaks if I remove the esp32_ble_tracker.stop_scan

The "Pausing scan" message is never emitted by my device.

### Which version of ESPHome has the issue?

Version: 2024.5.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32-IDF

### Board

WESP32

### Component causing the issue

esp32_ble_tracker

### Example YAML snippet

```yaml
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: false
  on_ble_advertise:
    - mac_address:
        - 9C:1D:58:93:5B:DE
      then:
        - lambda: |-
            ESP_LOGV("ble_adv", "Detected HPA250B");

script:
  - id: air_filter_toggle_power
    then:
      - esp32_ble_tracker.stop_scan:
      - lambda: |-
          ESP_LOGI("ble_client_lambda", "Request connect to HPA-250B Air Filter");
      - ble_client.connect:
          id: air_filter
      - lambda: |-
          ESP_LOGI("ble_client_lambda", "Sending handshake to HPA-250B Air Filter");
      - ble_client.ble_write:
          id: air_filter
          service_uuid: 0000fff0-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ffe9-0000-1000-8000-00805f9b34fb
          value: [0x4d, 0x41, 0x43, 0x2b, 0x9c, 0x1d, 0x58, 0x93, 0x5b, 0xde]
```

### Anything in the logs that might be useful for us?

```txt
[09:56:23][V][ble_adv:054]: Detected HPA250B
[09:56:24][V][ble_adv:054]: Detected HPA250B
[09:56:24][I][ble_client_lambda:061]: Request connect to HPA-250B Air Filter
[09:56:24][I][esp32_ble_client:067]: [0] [9C:1D:58:93:5B:DE] 0x00 Attempting BLE connection
[09:56:24][V][ble_adv:054]: Detected HPA250B
[09:56:24][V][ble_adv:054]: Detected HPA250B
```
