### ISSUE TITLE
on_page nextion not being triggered

### ISSUE THREAD

**Issue by vekexasia** [esphome/issues#5875]
### The problem

Hello, 

I fully own my nextion hmi. It seems [on_page ](https://esphome.io/components/display/nextion.html#on-page)
is never called.

### Which version of ESPHome has the issue?

2024.5.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.5

### What platform are you using?

ESP32

### Board

ESP32-S3-WROOM-1-N16R8

### Component causing the issue

nextion

### Example YAML snippet

```yaml
display:
  - platform: nextion
    id: disp1
    uart_id: tf_uart
    tft_url: $tft_url
    on_page: 
      then: 
        - logger.log: "ciao"
```

### Anything in the logs that might be useful for us?

```txt
nothing besides that touch events are being propagaged
```

### Additional information

using idf
