### ISSUE TITLE
SSD1306 OLED Display brightness doesn't go to 0

### ISSUE THREAD

**Issue by JiriPrchal** [esphome/issues#5876]
### The problem

After upgrade to 2024.5.4 the OLED brightness doesn't go lower then aprox. 40%, either switch off doesn't work. Display always lights. Previous working version was someone from past year.

### Which version of ESPHome has the issue?

2024.5.4

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2024.5.5

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

ssd1306_i2c

### Example YAML snippet

```yaml
display:
 - platform: ssd1306_i2c
   model: "SH1106 128x64"
   id: oled
   update_interval: 2s

   pages:
...

light:
 - platform: monochromatic
   name: "$devicename brightness"
   output: oled_bc
   restore_mode: ALWAYS_ON
   gamma_correct: 1

output:
 - platform: template
   id: "oled_bc"
   type: float
   write_action:
      then:
       - lambda: id(oled).set_contrast(state);
```
