### ISSUE TITLE
[Documentaion] Display Menu small correction

### ISSUE THREAD

**Issue by roykrikke** [esphome/issues#5879]
### The problem

On [page ](https://esphome.io/components/display_menu/) there is a small mistake on [section "select"](https://esphome.io/components/display_menu/#select) 

On the code below the part: on_value: is not working and also not showing in the logging.
```
lcd_menu:
  items:
    - type: select
      immediate_edit: false
      text: 'My Color'
      select: my_color
      on_enter:
        then:
          lambda: 'ESP_LOGI("display_menu", "select enter: %s, %s", it->get_text().c_str(), it->get_value_text().c_str());'
      on_leave:
        then:
          lambda: 'ESP_LOGI("display_menu", "select leave: %s, %s", it->get_text().c_str(), it->get_value_text().c_str());'
      on_value:
        then:
          lambda: 'ESP_LOGI("display_menu", "select value: %s, %s", it->get_text().c_str(), it->get_value_text().c_str());'

select:
  - platform: template
    id: my_color
    optimistic: true
    options:
      - 'Red'
      - 'Green'
      - 'Blue'
```
But when I add the code below to select it is working as expected. I would be good if de documention would be updated accordingly.
```
select:
  - platform: template
    id: my_color
    optimistic: true
    options:
      - 'Red'
      - 'Green'
      - 'Blue'
    on_value:
      then:
        lambda: 'ESP_LOGI("color", "option: %s (index %d)", x.c_str(), i);'
```

### Which version of ESPHome has the issue?

 2024.5.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32
