### ISSUE TITLE
problems with touchdisplay buttons

### ISSUE THREAD

**Issue by pantileionut** [esphome/issues#5882]
### The problem

I'm trying to make a graphic interface and I'm having problems with binary_sensor: -platform: touchscreen
although I have set the id for each display page, it seems that certain buttons get mixed up and if I have the same action area on the touchscreen but with different pages, both sensors are activated

### Which version of ESPHome has the issue?

2024.5.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.05

### What platform are you using?

ESP32

### Board

esp32s3

### Component causing the issue

touchscreen

### Example YAML snippet

```yaml
- platform: touchscreen
    name: buton pompa filtrare
    id: buton_pompa_filtrare
    x_min: 32
    x_max: 112
    y_min: 230
    y_max: 310
    page_id: main_page
    on_press:
      then:
        - display.page.show: page_pompa_filtrare

   - platform: touchscreen
     name: buton close filtrare
     id: buton_close_filtrare
     x_min: 32
     x_max: 142
     y_min: 270
     y_max: 320
     page_id: page_pompa_filtrare
     on_press:
       then:
         - display.page.show: main_page
```

### Additional information

![image](https://github.com/esphome/issues/assets/12047452/6a89c749-2a7c-4e7d-8d8f-f040a14508a1)
