### ISSUE TITLE
Component not found: globals.

### ISSUE THREAD

**Issue by Tihomir971** [esphome/issues#5885]
### The problem

After upgrading to 2024.5.5, and Home Assistant to 2024.6.0 Global Variables stop working: "Component not found: globals."

### Which version of ESPHome has the issue?

2024.5.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.0

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
globals:
# Value to consider completely dry. Auto-calibrated.
  - id: dryValue
    type: double
    restore_value: no
    initial_value: '2.2'
  # Value to consider completely wet. Auto-calibrated.
  - id: wetValue
    type: double
    restore_value: no
    initial_value: '1.1'
```
