### ISSUE TITLE
ST7735 causing API issue

### ISSUE THREAD

**Issue by eherranzr** [esphome/issues#5890]
### The problem

I have a Wemos D1 mini used for an air quality sensor that workds flawlessly. 
However, when trying to add an ST7735 display via SPI I get an issue.

### Which version of ESPHome has the issue?

2024.5.5

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.5.5

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

display

### Example YAML snippet

```yaml
esphome:
  name: sensor-aire
  friendly_name: Sensor Aire

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.1.177

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor Aire Fallback Hotspot"
    password: #redacted

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  safe_mode: true
  password: #redacted

binary_sensor:
  - platform: status
    name: "Sensor Aire Status"
    id: system_status

uart:
                 #5V >> VCC
                 #GND >> GND
  rx_pin: GPIO3 #RX >> TX (Y)
  tx_pin: GPIO12 #D6 >> RX (EXT)
  baud_rate: 9600

i2c:
             #3V3 >> VCC
             #GND >> GND
             #GND >> WAK
  sda: GPIO4 #D2 >> SDA
  scl: GPIO5 #D1 >> SCL
  frequency: 100kHz

spi:
                    #3V3 >> VCC
                    #3V3 >> LED
                    #GND >> GND
  clk_pin: GPIO14   #D5 >> SCK
  mosi_pin: GPIO13  #D7 >> SDA

sensor:
  - platform: pmsx003
    id: pmsa003
    type: PMSX003
    
    pm_1_0:
      id: pm_1_0
      name: "Sensor Aire PM <1.0 µm"
      # filters:
      # - sliding_window_moving_average:
      #     window_size: 30
      #     send_every: 10

    pm_2_5:
      id: pm_2_5
      name: "Sensor Aire PM <2.5 µm"
      filters:
      # - sliding_window_moving_average:
      #     window_size: 30
      #     send_every: 10
      on_value:
        lambda: |-
          // https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
          if (id(pm_2_5).state < 9.0) {
            // good
            id(pm_2_5_aqi).publish_state((50.0 - 0.0) / (9.0 - 0.0) * (id(pm_2_5).state - 0.0) + 0.0);
          } else if (id(pm_2_5).state < 35.4) {
            // moderate
            id(pm_2_5_aqi).publish_state((100.0 - 51.0) / (35.4 - 9.1) * (id(pm_2_5).state - 9.1) + 51.0);
          } else if (id(pm_2_5).state < 55.4) {
            // usg
            id(pm_2_5_aqi).publish_state((150.0 - 101.0) / (55.4 - 35.5) * (id(pm_2_5).state - 35.5) + 101.0);
          } else if (id(pm_2_5).state < 125.4) {
            // unhealthy
            id(pm_2_5_aqi).publish_state((200.0 - 151.0) / (125.4 - 55.5) * (id(pm_2_5).state - 55.5) + 151.0);
          } else if (id(pm_2_5).state < 225.4) {
            // very unhealthy
            id(pm_2_5_aqi).publish_state((300.0 - 201.0) / (225.4 - 125.5) * (id(pm_2_5).state - 125.5) + 201.0);
          } else if (id(pm_2_5).state < 325.4) {
            // hazardous
            id(pm_2_5_aqi).publish_state((500.0 - 301.0) / (325.4 - 225.5) * (id(pm_2_5).state - 225.5) + 301.0);
          } 

    pm_10_0:
      id: pm_10
      name: "Sensor Aire PM <10.0 µm"
      filters:
      # - sliding_window_moving_average:
      #     window_size: 30
      #     send_every: 10
      on_value:
        lambda: |-
          // https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
          if (id(pm_10).state < 54.0) {
            // good
            id(pm_10_aqi).publish_state((50.0 - 0.0) / (54.0 - 0.0) * (id(pm_10).state - 0.0) + 0.0);
          } else if (id(pm_10).state < 154.0) {
            // moderate
            id(pm_10_aqi).publish_state((100.0 - 51.0) / (154.0 - 55.0) * (id(pm_10).state - 55.0) + 51.0);
          } else if (id(pm_10).state < 55.4) {
            // usg
            id(pm_10_aqi).publish_state((150.0 - 101.0) / (254.0 - 155.0) * (id(pm_10).state - 155.0) + 101.0);
          } else if (id(pm_10).state < 125.4) {
            // unhealthy
            id(pm_10_aqi).publish_state((200.0 - 151.0) / (354.0 - 255.0) * (id(pm_10).state - 255.0) + 151.0);
          } else if (id(pm_10).state < 225.4) {
            // very unhealthy
            id(pm_10_aqi).publish_state((300.0 - 201.0) / (424.0 - 355.0) * (id(pm_10).state - 355.0) + 201.0);
          } else if (id(pm_10).state < 325.4) {
            // hazardous
            id(pm_10_aqi).publish_state((500.0 - 301.0) / (604.0 - 425.0) * (id(pm_10).state - 425.0) + 301.0);
          }
    update_interval: 300s  

  - platform: template
    name: "Sensor Aire PM <2.5 AQI"
    unit_of_measurement: "AQI"
    icon: "mdi:air-filter"
    accuracy_decimals: 0
    id: pm_2_5_aqi
  - platform: template
    name: "Sensor Aire PM <10 AQI"
    unit_of_measurement: "AQI"
    icon: "mdi:air-filter"
    accuracy_decimals: 0
    id: pm_10_aqi
  - platform: template
    name: "Sensor Aire AQI"
    lambda: |-
      if (id(pm_10_aqi).state>id(pm_2_5_aqi).state) {
        return id(pm_10_aqi).state;
      } else {
        return id(pm_2_5_aqi).state;
      }
    unit_of_measurement: "AQI"
    icon: "mdi:air-filter"
    accuracy_decimals: 0
    id: pm_aqi

  - platform: ccs811
    eco2:
      name: "eCO2"
      id: co2
    tvoc:
      name: "Total Volatile Organic Compound"
      id: tvoc
    address: 0x5A
    temperature: temperature
    humidity: humidity
    update_interval: 60s
    #baseline will be set after initial run with fresh air
    #baseline: 0x3CB8

  - platform: bme280_i2c
    temperature:
      id: temperature
      name: "Temperatura"
    pressure:
      id: pressure
      name: "Presion atmosférica"
    humidity:
      id: humidity
      name: "Humedad"
    address: 0x76
    update_interval: 60s

  - platform: bh1750
    name: "Iluminación"
    address: 0x23
    update_interval: 60s
    id: illumination

  - platform: wifi_signal
    name: "Sensor Aire WiFi Signal"
    update_interval: 60s

time:
  - platform: homeassistant
    id: esptime
    timezone: Europe/Madrid

######### EVERYTHING WORKDS FINE UNTIL HERE. ADDING THE BELOW CAUSING ISSUES WITH API CONNECTION

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_gray
    red: 50%
    green: 50%
    blue: 50%
  - id: my_orange
    red: 100%
    green: 65%
    blue: 0%

# Grab font from https://fonts.google.com/specimen/Roboto and place in same directory as this file
font:
  - file: "Roboto-Medium.ttf"
    id: sz_16
    size: 16
  - file: "Roboto-Medium.ttf"
    id: sz_13
    size: 13
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/³µΩ'
  - file: "Roboto-Medium.ttf"
    id: sz_8
    size: 8

display:
  - platform: st7735
    model: "INITR_BLACKTAB"
    reset_pin: GPIO0    #D3 >> RESET
    cs_pin: GPIO15      #D8 >> CS
    dc_pin: GPIO2       #D4 >> A0
    rotation: 270
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 5s
    lambda: |-
      it.rectangle(0,  0, it.get_width(), it.get_height(), id(my_blue));
      it.rectangle(0, 14, it.get_width(), it.get_height(), id(my_blue));   // header bar

      it.strftime(3,  3, id(sz_8), id(my_yellow), TextAlign::TOP_LEFT, "%d-%m-%Y %H:%M", id(esptime).now());

      if (id(system_status).state) {
        it.print(157, 3, id(sz_8), id(my_green), TextAlign::TOP_RIGHT, "Sensor conectado");
      } else {
        it.print(157, 3, id(sz_8), id(my_red), TextAlign::TOP_RIGHT, "Sensor desconectado");
      }

      int r = 17;

      it.print(3,    r, id(sz_16), id(my_gray),   TextAlign::TOP_LEFT,  "PM:");

      auto color = id(my_red);
      if (id(pm_aqi).state <= 50) color = id(my_green);
      else if (id(pm_aqi).state <= 100) color = id(my_yellow);
      else if (id(pm_aqi).state <= 150) color = id(my_orange);
      /*it.printf(157, r, id(sz_16), color, TextAlign::TOP_RIGHT, "%0.0f AQI", id(pm_aqi).state);*/
      it.printf(157, r, id(sz_16), color, TextAlign::TOP_RIGHT, "999 AQI", id(pm_aqi).state);


      r += 19;
      it.print(3,    r, id(sz_13), id(my_gray),   TextAlign::TOP_LEFT,  "PM:");
      /*it.printf(157, r, id(sz_13), id(my_yellow), TextAlign::TOP_RIGHT, "%0.0f/%0.0f/%0.0f µg/m³", id(pm_1_0).state, id(pm_2_5).state, id(pm_10).state);*/
      it.printf(157, r, id(sz_13), id(my_yellow), TextAlign::TOP_RIGHT, "999/999/999 µg/m³", id(pm_1_0).state, id(pm_2_5).state, id(pm_10).state);

      r += 17;
      auto color1 = id(my_red);
      if (id(co2).state <= 450) color1 = id(my_green);
      else if (id(co2).state <= 600) color1 = id(my_yellow);
      else if (id(co2).state <= 100) color1 = id(my_orange);
      /*it.printf(3,   r, id(sz_13), color1, TextAlign::TOP_LEFT, "CO2: %0.0f ppm", id(co2).state); */
      it.printf(3,   r, id(sz_13), color1, TextAlign::TOP_LEFT, "CO2: 9999 ppm", id(co2).state);
      auto color2 = id(my_red);
      if (id(co2).state <= 220) color2 = id(my_green);
      else if (id(co2).state <= 660) color2 = id(my_yellow);
      else if (id(co2).state <= 1430) color2 = id(my_orange);
      /*it.printf(157, r, id(sz_13), color2, TextAlign::TOP_RIGHT,  "TVOC: %0.0f ppb", id(tvoc).state);*/
      it.printf(157, r, id(sz_13), color2, TextAlign::TOP_RIGHT,  "TVOC: 9999 ppb", id(tvoc).state);


      r += 16;
      it.print(80,    r, id(sz_16), id(my_gray),   TextAlign::TOP_CENTER,  "Ambiente");

      r += 19;
      /*float temp_f = id(temp).state * (9.0/5.0) + 32.0;*/
      /*float temp2_f = id(temp2).state * (9.0/5.0) + 32.0;*/
      it.printf(3,   r, id(sz_13), id(my_yellow), TextAlign::TOP_LEFT, "%0.1flx", id(illumination).state); 
      /*it.printf(4,   r, id(sz_13), id(my_yellow), TextAlign::TOP_LEFT, "%0.1f°F", temp_f); */
      it.printf(80, r, id(sz_16), id(my_yellow), TextAlign::TOP_CENTER, "%0.1f°C", id(temperature).state); 
      /*it.printf(157, r, id(sz_13), id(my_yellow), TextAlign::TOP_RIGHT,  "%0.1f%", id(humidity).state);*/

      r += 19;
      /*it.printf(3,   r, id(sz_13), id(my_yellow), TextAlign::TOP_LEFT,  "%0.1f hPa", id(pressure).state);*/
      /*it.printf(156, r, id(sz_13), id(my_yellow), TextAlign::TOP_RIGHT, "%0.1f kΩ",  id(gas_resistance).state/1000.0);*/
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.5.5
INFO Reading configuration /config/sensor-aire.yaml...
INFO Starting log output from 192.168.1.177 using esphome API
INFO Successfully connected to sensor-aire @ 192.168.1.177 in 0.055s
WARNING sensor-aire @ 192.168.1.177: Connection error occurred: sensor-aire @ 192.168.1.177: EOF received
WARNING Can't connect to ESPHome API for sensor-aire @ 192.168.1.177: sensor-aire @ 192.168.1.177: EOF received (SocketClosedAPIError)
INFO Trying to connect to sensor-aire @ 192.168.1.177 in the background
```
