### ISSUE TITLE
Sonoff Basic R1 does not connect to WiFi after upgrade from 2024.5.3 to 2024.5.4

### ISSUE THREAD

**Issue by erwinschoonhoven** [esphome/issues#5894]
### The problem

Sonoff Basic R1 never comes on WiFi after upgrade from 2024.5.3 to 2024.5.4. After (serial) flashing back to 2024.5.3 it's back on WiFi and operating as expected. Tried serial flashing to 2024.5.4 and 2024.5.5 to check logs but this device did not show me anything after upgrade so I went back again to 2024.5.3 for a working device.
I use a MAC whitelist and my WiFi password has a $ character in it, but that should not be an issue I hope.

### Which version of ESPHome has the issue?

2024.5.4

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

Sonoff Basic R1

### Component causing the issue

switch

### Example YAML snippet

```yaml
esphome:
  name: garden-power
  friendly_name: Garden Power

esp8266:
  board: esp01_1m

logger:
  level: VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
```
