### ISSUE TITLE
Keeping states - in RAM and/or Flash - description not clear or not working

### ISSUE THREAD

**Issue by starbrights** [esphome/issues#5897]
### The problem

I am try to run (on BK7321 - maybe that is part of problem) a rollershutter. That all works fine but I could find out
* what state can survive an reboot
* what state can survive a repower

I found a few different things about it and it is very time consuming to test (need to flash, need to cut power/wifi) but although I invest quite some time I don't get a final clue.

It seem that *(esp_)restore_from_flash* is not supported for my chip. Ok.
But I found also (in globals) the *restore_value* - these doesn't seem to work for me. Not for reboot nor for repower (power off/on).
On the other hand, if I do an *App.safe_reboot();* I can observe that in this case the position of the cover (which is an internal variable obviously) is saved. I also get in log: 
`[D][lt.preferences:132]: Saving 2 preferences to flash: 0 cached, 2 written, 0 failed`
But which one and how to control that is unclear.

I need to run it (most of the time) without a server in background that controls it. So the rollershutter works mostly "offline" - that is why I need some stability about position.
It would be perfect (to not wear out the flash) to have manual control WHEN the status will be saved. It is not needed after each change, but lets the once the wifi gets disconnected....

### Which version of ESPHome has the issue?

ESPHome version 2024.5.4

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

-

### What platform are you using?

BK72XX

### Board

moes curtain switch

### Component causing the issue

cover, output, binary_sensor, switch

### Example YAML snippet

```yaml
####################################################
# short up/down: cover up/down
# any key if cover is moving: stop
# stop while not moving: cover to pref_pos
#
# long stop: set a new pref_pos
# long up:   switch up (overrule cover)
# long down: switch down (overrule cover)
#
# long long up: reboot
# long long stop: toggle timer (middle red)
# long long down: toogle LED
####################################################
esphome:
  name: moes
  on_boot:
    priority: -10
    then:
      - output.turn_on: gpio_backlight

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

web_server:

captive_portal:

mdns:

#api:
#  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:  
    password: !secret wifi_ap_password
  power_save_mode: high  # Optionen: none, light, high
  output_power: 15dB  # Reduziert die Sendeleistung

mqtt:
  broker: "192.168.3.20"
  id: mqtt_moes_client

button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

sensor:
  - platform: uptime
    name: Uptime

globals:
  - id: pref_pos
    type: int
    initial_value: '55'
  - id: timer_active
    type: bool
    initial_value: 'true'
  - id: backlight_active
    type: bool
    initial_value: 'true'

cover:
  - platform: time_based
    name: moes1
    id: my_cover
    open_action:
      - switch.turn_on: switch_up
      - output.turn_on: output_led_up
    open_duration: 26000ms
    close_action:
      - switch.turn_on: switch_down
      - output.turn_on: output_led_down
    close_duration: 25000ms
    stop_action:
      - switch.turn_off: switch_up
      - switch.turn_off: switch_down
      - output.turn_off: output_led_up
      - output.turn_off: output_led_down
#    assumed_state: no  
#    assumed_state: true
    on_open:
      - logger.log: "Cover is/should fully open!"
      - switch.turn_on: switch_up
    on_closed:
      - logger.log: "Cover is/should fully closed!"
      - switch.turn_on: switch_down


output:
  - platform: gpio
    id: output_led_up
    pin: P14
  - platform: gpio
    id: output_led_down
    pin: P23
  - platform: gpio
    id: output_led_stop
    pin: P8
  - platform: gpio
    id: gpio_backlight
    pin: P11

binary_sensor:
  - platform: gpio
    id: binary_switch_up
    pin:
      number: P24
      inverted: true
      mode: INPUT_PULLUP
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.01s
        then:
        - logger.log: "press up detected"
        - lambda: |-
            ESP_LOGD("main", "cover.current_operation %i", id(my_cover).current_operation);
            if (id(my_cover).current_operation == CoverOperation::COVER_OPERATION_IDLE) {
              // Cover is idle
              auto call = id(my_cover).make_call();
              call.set_command_open();
              call.perform();
              ESP_LOGD("main", "cover.open");
            } else if (id(my_cover).current_operation == CoverOperation::COVER_OPERATION_OPENING) {
              // Cover is currently opening
              auto call = id(my_cover).make_call();
              call.set_command_stop();
              call.perform();
              ESP_LOGD("main", "already opening: cover.stop");
            } else if (id(my_cover).current_operation == CoverOperation::COVER_OPERATION_CLOSING) {
              // Cover is currently closing
              auto call = id(my_cover).make_call();
              call.set_command_stop();
              call.perform();
              ESP_LOGD("main", "cover.stop");
            }
      - timing:
          - ON for 3s to 7s
        then:
        - logger.log: "long press up detected"
        - switch.turn_on: switch_up

      - timing:
          - ON for at least 7s
        then:
        - logger.log: "very long press up detected"
        - lambda: |-
            App.safe_reboot();
 
  - platform: gpio
    id: binary_switch_down
    pin:
      number: P7
      inverted: true
      mode: INPUT_PULLUP
    on_multi_click:
      - timing:
          - ON for at most 1s
        then:
        - logger.log: "press down detected"
        - lambda: |-
            ESP_LOGD("main", "cover.current_operation %i", id(my_cover).current_operation);
            if (id(my_cover).current_operation == CoverOperation::COVER_OPERATION_IDLE) {
              // Cover is idle
              auto call = id(my_cover).make_call();
              call.set_command_close();
              call.perform();
              ESP_LOGD("main", "idle - cover.close");
            } else if (id(my_cover).current_operation == CoverOperation::COVER_OPERATION_OPENING) {
              // Cover is currently opening
              auto call = id(my_cover).make_call();
              call.set_command_stop();
              call.perform();
              ESP_LOGD("main", "already opening - cover.stop");
            } else if (id(my_cover).current_operation == CoverOperation::COVER_OPERATION_CLOSING) {
              // Cover is currently closing
              auto call = id(my_cover).make_call();
              call.set_command_stop();
              call.perform();
              ESP_LOGD("main", "closing - cover.stop");
            }
      - timing:
          - ON for 1s to 3s
        then:
        - logger.log: "long press down detected"
        - lambda: |-
            if (id(backlight_active)) {
              ESP_LOGI("stop", "switch backlight off");
              id(gpio_backlight).turn_off();
            } else {
              ESP_LOGI("stop", "switch backlight on");
              id(gpio_backlight).turn_on();
            }
            id(backlight_active) = !id(backlight_active); 
      - timing:
          - ON for 3s to 5s
        then:
        - logger.log: "very long press down detected"
        - switch.turn_on: switch_down

  - platform: gpio
    id: binary_switch_stop
    pin:
      number: P10
      inverted: true
      mode: INPUT_PULLUP
    on_multi_click:
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "press stop detected"
          - lambda: |-
                ESP_LOGD("main", "stop: cover.current_operation %i", id(my_cover).current_operation);
                if (id(my_cover).current_operation == CoverOperation::COVER_OPERATION_IDLE) {
                  ESP_LOGD("main", "act pos %i -> pref pos %i", int(id(my_cover).position*100), id(pref_pos));
                    if (abs(int(id(my_cover).position*100) - id(pref_pos))>1) {
                      char payload[4];
                      sprintf(payload, "%d", id(pref_pos));
                      ESP_LOGD("main", "publish mqtt command to pos %s", payload);
                      id(mqtt_moes_client).publish("moes/cover/moes1/position/command", payload);
                    } else {
                      ESP_LOGD("main", "no action needed, already at right pos");
                    }
                } else {
                  auto call = id(my_cover).make_call();
                  call.set_command_stop();
                  call.perform();
                  ESP_LOGD("main", "pressed stop while running - cover.stop");
                }

      - timing:
          - ON for 1s to 3s
        then:
          - logger.log: "Long press stop detected"
          - lambda: |-
              id(timer_active) = !id(timer_active);
              ESP_LOGD("main", "timer_active: %i",id(timer_active));
              if (id(timer_active)) {
                id(output_led_stop).turn_off(); // green LED
              } else {
                id(output_led_stop).turn_on();  // red LED
              }
      - timing:
          - ON for 3s to 10s
        then:
          - logger.log: "Very long press stop detected"
          - lambda: |-
              id(pref_pos) = int(id(my_cover).position*100 + 0.5);
              ESP_LOGD("main", "set new pref_pos %i",id(pref_pos));
                
switch:
  - platform: gpio
    id: switch_up
    name: Relay up
    pin: P6
    interlock: [switch_down]
  - platform: gpio
    id: switch_down
    name: Relay down
    pin: P9
    interlock: [switch_up]

status_led:
  pin: P26

time:
  - platform: sntp
    id: sntp_time
    servers: 192.168.3.1
    on_time:    
    # Every morning on weekdays
      - days_of_week: MON-FRI
        hours: 06
        minutes: 30
        seconds: 0
        then:
         - if:
            condition:
              - lambda: 'return id(timer_active);'
            then:
              - cover.open: my_cover
            else:
              - logger.log: "Timer is inactive, skipping action."
    # Every evening on weekdays
      - days_of_week: MON-FRI
        hours: 21
        minutes: 00
        seconds: 0
        then:
         - if:
            condition:
              - lambda: 'return id(timer_active);'
            then:
             - cover.close: my_cover
            else:
              - logger.log: "Timer is inactive, skipping action."
    # Every morning on weekends
      - days_of_week: SAT,SUN
        hours: 8
        minutes: 00
        seconds: 0
        then:
         - if:
            condition:
              - lambda: 'return id(timer_active);'
            then:
              - cover.open: my_cover
            else:
              - logger.log: "Timer is inactive, skipping action."

    # Every evening on weekends
      - days_of_week: SAT,SUN
        hours: 21
        minutes: 30
        seconds: 0
        then:
         - if:
            condition:
              - lambda: 'return id(timer_active);'
            then:
              - cover.open: my_cover
            else:
              - logger.log: "Timer is inactive, skipping action."

interval:
  - interval: 30s
    then:
      - mqtt.publish:
          topic: moes/timer_active
          payload: !lambda 'return String(id(timer_active)).c_str();'

      - mqtt.publish:
          topic: moes/pos
          payload: !lambda 'return String(id(my_cover).position).c_str();'

      - mqtt.publish:
          topic: moes/pref
          payload: !lambda 'return String(id(pref_pos)).c_str();'

      - mqtt.publish:
          topic: moes/backlight
          payload: !lambda 'return String(id(backlight_active)).c_str();'
```
