### ISSUE TITLE
GPIO Pin 0 does not support pullup pin mode (i2c)

### ISSUE THREAD

**Issue by rradar** [esphome/issues#59]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

esp8285

**Affected component:**

i2c

**Description of problem:**

I tried to compile a old sketch with the new esphome version 1.10.1 and get the following error message:

> Failed config
> 
> i2c: [source espm3-i2c.yaml:19]
>   
>   GPIO Pin 0 does not support pullup pin mode. Please choose another pin. Got '0'
>   sda: 0
>   scl: 2
>   scan: False

I need to use these pins for i2c communication because this board (esp m3) offers no others.

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: ...
  platform: ESP8266
  board: esp8285

[...]

i2c:
  sda: 0
  scl: 2
  scan: False
```

**Additional information and things you've tried:**

It always worked with older versions of esphome...
