### ISSUE TITLE
id(some_sensor).state is not updated when reading failed

### ISSUE THREAD

**Issue by john-arvid** [esphome/issues#590]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

https://esphome.io/components/sensor/dht.html

**Description of problem:**
I am trying to check when a temperature read fails, for example if the sensor or wire breaks.
So when disconnecting a DHT22 sensor the id(some_sensor).state is not updated, but keeps the last value.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: esp01_mill04

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret wpa

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
web_server:
  port: 80

switch:
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO0
    id: relay1
    name: $devicename " Relay"
    
sensor:
  - platform: dht
    pin: GPIO3
    model: AM2302
    temperature:
      id: temp1
      name: $devicename " Temperature"
                    
    humidity:
      name: $devicename " Humidity"
    update_interval: 10s
    
script:
  - id: test1
    then:
      - lambda: !lambda |-
          ESP_LOGD("main", "State is: %f", id(temp1).state);

interval:
  - interval: 10s
    then:
      - script.execute: test1

climate:
  - platform: bang_bang
    name: test
    id: my_climate
    sensor: temp1
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 22 °C
    visual:
      min_temperature: 5 °C
      max_temperature: 25 °C
      temperature_step: 0.5 °C

    heat_action:
      - switch.turn_on: relay1
    idle_action:
      - switch.turn_off: relay1

```
