### ISSUE TITLE
M5stack Atom Echo's button doesn't trigger Assist

### ISSUE THREAD

**Issue by Defozo** [esphome/issues#5903]
### The problem

I uploaded the binary provided on https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/.
I believe the Atom Echo should trigger voice recognition when the button is pressed but this doesn't happen.

### Which version of ESPHome has the issue?

2024.5.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.2

### What platform are you using?

ESP32

### Board

M5Stack Atom Echo

### Additional information

I can confirm the button works hardware-wise as I enabled it in HASS and the presses are correctly detected.

**Comment by JustEnoughDucks** [comment]
Is it correctly sending your voice over?

I can use a debug session and the Atom Echo will hear me and interpret commands, but indeed the button doesn't trigger the voice assistant

**Comment by Defozo** [comment]
Yes, it's successfully transmitting the voice over. Even though I haven't listened to the sample myself, the recognition via Whisper appears to be working exceptionally well.

**Comment by pablowako** [comment]
bump
This issue persists, at least for me.

Both the center button and the side button have no use, and don't trigger anything. Cant even see it in the logs

**Comment by CodyReichert** [comment]
I noticed this too. Pretty sure it is a bug in [the default yaml config](https://github.com/esphome/wake-word-voice-assistants/blob/main/m5stack-atom-echo/m5stack-atom-echo.yaml), but I didn't install from that source so I'm not sure if it uses the same thing (you'd see a reference to that default yaml on github in your device's yaml), but basically everything else works just fine, so a config issue would make sense.

**Comment by chiro79** [comment]
I have the same issue.
Looking at the yaml configuration, everything seems ok. Then, if you look at the logs when you click the button, it says that:

> [16:16:38.998][D][binary_sensor:044]: 'Button' >> ON
> [16:16:39.148][D][binary_sensor:044]: 'Button' >> OFF
> [16:16:39.180][W][micro_wake_word:356]: Wake word detection is already running

So, the current config is not triggering voice assistant, but enabling (again) wake word detection.

**Comment by chiro79** [comment]
I have it working, not sure if this is clean or if it is the way it should be done, but I tested it all I could and it is working for me. I'm using the official yaml file via package, and I have added the following at the end of the configuration file:

```yaml
binary_sensor:
  - id: !extend echo_button
    on_multi_click:
      - timing:
          - state: true
            min_length: 50ms
          - state: false
            min_length: 50ms
        then:
          - if:
              condition:
                switch.is_on:
                  id: timer_ringing
              then:
                - switch.turn_off:
                    id: timer_ringing
              else:
                - script.execute:
                    id: button_pressed
        invalid_cooldown: 1s
      - timing:
          - state: true
            min_length: 10s
        then:
          - button.press:
              id: factory_reset_btn
        invalid_cooldown: 1s

script:
  - id: button_pressed
    then:
      - if:
          condition:
            - lambda: !lambda |-
                return id(wake_word_engine_location).current_option() == "On device";
          then:
            - if:
                condition:
                  and:
                    - not:
                        and:
                          - voice_assistant.is_running: {}
                then:
                  - voice_assistant.start:
                      silence_detection: true
                else:
                  - script.execute: stop_wake_word
                  - voice_assistant.stop: {}
                  - wait_until:
                      condition:
                        and:
                          - and:
                              - not:
                                  voice_assistant.is_running: {}
                              - not:
                                  speaker.is_playing: {}
                  - script.execute: start_wake_word
      - if:
          condition:
            - lambda: !lambda |-
                return id(wake_word_engine_location).current_option() == "In Home Assistant";
          then:
            - if:
                condition:
                  not:
                    - speaker.is_playing: {}
                then:
                  - script.execute: stop_wake_word
                  - delay: 500ms
                  - voice_assistant.start:
                      silence_detection: true
                  - wait_until:
                      condition:
                        and:
                          - and:
                              - not:
                                  voice_assistant.is_running: {}
                              - not:
                                  speaker.is_playing: {}
                  - script.execute: start_wake_word
                else:
                  - script.execute: stop_wake_word
                  - voice_assistant.stop: {}
                  - wait_until:
                      condition:
                        and:
                          - and:
                              - not:
                                  voice_assistant.is_running: {}
                              - not:
                                  speaker.is_playing: {}
                  - script.execute: start_wake_word
    mode: restart
    parameters: {}
```
