### ISSUE TITLE
Will not update firmware. Platform tag required 

### ISSUE THREAD

**Issue by dualtronic** [esphome/issues#5904]
### The problem

Cannot flash firmware on M5 Stack ESP32 (bluetooth proxy).  Requires Platform tag, but also fails when including that tag because the online configuration already uses new platform (ESP32:) description tag.

### Which version of ESPHome has the issue?

2024.6.0b2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.2

### What platform are you using?

ESP32

### Board

ESP32 (M5Stack Atom)

### Component causing the issue

ESPHome

### Example YAML snippet

```yaml
substitutions:
  name: esp32-bluetooth-proxy-9d2178
  friendly_name: Bluetooth Proxy 9d2178
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: DHrH6oy3Sx2YBWzk0jnPsk9qLM6oOHzc1vdOaLcgsQo=
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

### Anything in the logs that might be useful for us?

```txt
Installation trace below:

INFO ESPHome 2024.6.0b2
INFO Reading configuration /config/esphome/esp32-bluetooth-proxy-9d2178.yaml...
Failed config

At least one platform must be specified for 'ota'; add 'platform: esphome' for original OTA functionality
```
