### ISSUE TITLE
Pulse Meter not working correctly after updating from 2023.5.4 to 2024.5.5

### ISSUE THREAD

**Issue by reflexsa** [esphome/issues#5905]
### The problem

Before the update I have accurate readings (lose maybe 0.1kWh over a month compared to my meter) and the 'live' power usage is also accurate to the load.
After the update it has massive spikes in the readings, such as 400kW. 
This is not the first time the "pulse_meter" sensor seems to have broken after an update.

To roll back I included this which fixes the issues **(I'm not exactly sure at which version number the problem was introduced as I skipped several updates):**
```
external_components:
  - source: github://esphome/esphome@2023.5.4
    components: [pulse_meter]
```

### Which version of ESPHome has the issue?

2024.5.5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Nodemcu

### Component causing the issue

Pulse Meter

### Example YAML snippet

```yaml
sensor:
  - platform: pulse_meter
    pin: GPIO14
    internal_filter: 50ms
    internal_filter_mode: PULSE
    #changed filter from 50ms
    timeout: 10 min
    unit_of_measurement: 'kW'
    name: 'Power Meter1 8266'
    filters:
      - multiply: 0.06
    total:
      device_class: "energy"
      name: "Total power check1 8266"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      filters:
        - multiply: 0.001
```
