### ISSUE TITLE
SSD1327: Grayscale images render as all-white rectangles

### ISSUE THREAD

**Issue by Wuestengecko** [esphome/issues#5918]
### The problem

When drawing a GRAYSCALE image on an `ssd1327_i2c` display, a white rectangle appears instead.

### Which version of ESPHome has the issue?

2024.5.5

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Component causing the issue

ssd1327_i2c

### Example YAML snippet

```yaml
image:
  - file: ota-download.48.png
    id: img_ota_download_48
    type: GRAYSCALE

display: # {{{2
  id: my_display
  platform: ssd1327_i2c
  model: "SSD1327 128x128"
  address: 0x3C
  reset_pin: $pin_disp_reset
  brightness: 1.0
  update_interval: 5s
  pages:
    - id: ota_page
      lambda: |-
        it.image(40, 24, id(img_ota_download_48));
        it.print(64, 24+48+8, id(font_small), TextAlign::TOP_CENTER, "Downloading");
```

### Additional information

The issue is that [an `Image` in `GRAYSCALE` mode treats the "white" component as one-bit alpha channel](https://github.com/esphome/esphome/blob/c18056bdda129136f05b52388e738ceec8242e62/esphome/components/image/image.cpp#L121-L126), while `ColorUtil::color_to_grayscale4`, which ssd1327\_base uses in [`draw_absolute_pixel_internal`](https://github.com/esphome/esphome/blob/c18056bdda129136f05b52388e738ceec8242e62/esphome/components/ssd1327_base/ssd1327_base.cpp#L138-L151), instead [treats it as the brightness value](https://github.com/esphome/esphome/blob/c18056bdda129136f05b52388e738ceec8242e62/esphome/components/display/display_color_utils.h#L106-L109):

```cpp
Color Image::get_grayscale_pixel_(int x, int y) const {
  const uint32_t pos = (x + y * this->width_);
  const uint8_t gray = progmem_read_byte(this->data_start_ + pos);
  uint8_t alpha = (gray == 1 && transparent_) ? 0 : 0xFF;
  return Color(gray, gray, gray, alpha);
}


class ColorUtil {
  static uint32_t color_to_grayscale4(Color color) {
    uint32_t gs4 = esp_scale8(color.white, 15);
    return gs4;
  }
};
```

As a workaround / quick fix, changing `get_grayscale_pixel` to pass `gray` again instead of `alpha` makes the images render correctly.

(Another workaround is to only use BINARY images, which work fine.)
