### ISSUE TITLE
BK7231N update error occurred on 6/20/2024.

### ISSUE THREAD

**Issue by percy10442** [esphome/issues#5921]
### The problem

Update encountered an error

### Which version of ESPHome has the issue?

2024.6.0 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.3

### What platform are you using?

BK72XX

### Example YAML snippet

```yaml
esphome:
  name: upk2esphome-bk7231n
  name_add_mac_suffix: False
  friendly_name: 大客房開關
bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

web_server:

captive_portal:

mdns:

api:
  encryption:
    key: "25ZD5FX80T5UCsW5a98/x+PXqud/x5vlnbwViWHThBQ="

ota:
  - platform: esphome
    password: "f25c26d5bed26227a6531d66b3bda23d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
#  - platform: libretiny
#    version:
#      name: LibreTiny Version

#sensor:
#  - platform: uptime
#    name: Uptime

output:
  - platform: gpio
    id: output_led_1
    pin:
      number: P14
      inverted: true
  - platform: gpio
    id: output_led_2
    pin:
      number: P20
      inverted: true

light:
  - platform: binary
    id: light_switch_1
    output: output_led_1
  - platform: binary
    id: light_switch_2
    output: output_led_2

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P23
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1
  - platform: gpio
    id: binary_switch_2
    pin:
      number: P28
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_2

switch:
  - platform: gpio
    id: switch_1
    name: 大客房燈開關1
    pin: P24
    on_turn_on:
      - light.turn_off: light_switch_1
    on_turn_off:
      - light.turn_on: light_switch_1
  - platform: gpio
    id: switch_2
    name: 大客房燈開關2
    pin: P26
    on_turn_on:
      - light.turn_off: light_switch_2
    on_turn_off:
      - light.turn_on: light_switch_2
```

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/debug/debug_libretiny.cpp: In member function 'void esphome::debug::DebugComponent::get_device_info_(std::string&)':
src/esphome/components/debug/debug_libretiny.cpp:15:3: error: 'str' has not been declared
   15 |   str::string reset_reason = get_reset_reason_();
      |   ^~~
In file included from src/esphome/components/sensor/sensor.h:3,
                 from src/esphome/components/debug/debug_component.h:9,
                 from src/esphome/components/debug/debug_libretiny.cpp:1:
src/esphome/components/debug/debug_libretiny.cpp:21:37: error: 'reset_reason' was not declared in this scope; did you mean 'reset_reason_'?
   21 |   ESP_LOGD(TAG, "Reset Reason: %s", reset_reason.c_str());
      |                                     ^~~~~~~~~~~~
src/esphome/core/log.h:95:89: note: in definition of macro 'esph_log_d'
   95 |   esp_log_printf_(ESPHOME_LOG_LEVEL_DEBUG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                         ^~~~~~~~~~~
src/esphome/components/debug/debug_libretiny.cpp:21:3: note: in expansion of macro 'ESP_LOGD'
   21 |   ESP_LOGD(TAG, "Reset Reason: %s", reset_reason.c_str());
      |   ^~~~~~~~
Compiling .pioenvs/bigroom2/src/esphome/components/esphome/ota/ota_esphome.cpp.o
*** [.pioenvs/bigroom2/src/esphome/components/debug/debug_libretiny.cpp.o] Error 1
========================= [FAILED] Took 34.08 seconds =========================
========== [ERROR] /config/esphome/bigroom2.yaml ==========
```
