### ISSUE TITLE
multiple definition of 'enum esphome::ota::OTAResponseTypes'

### ISSUE THREAD

**Issue by shammysha** [esphome/issues#5923]
### The problem

Have two servers (let's say "Test" and "Prod") with same configs and same versions of esphome.
When building firmware on Test - I see, that generated esphome.h contains OTA strings

```
#include "esphome/components/ota/automation.h"
#include "esphome/components/ota/ota_backend.h"
#include "esphome/components/ota/ota_backend_arduino_esp32.h"
#include "esphome/components/ota/ota_backend_arduino_esp8266.h"
#include "esphome/components/ota/ota_backend_arduino_libretiny.h"
#include "esphome/components/ota/ota_backend_arduino_rp2040.h"
#include "esphome/components/ota/ota_backend_esp_idf.h"
```
Firmware compiled succesfully
Log: [test.log](https://github.com/user-attachments/files/15908839/test.log)

But when I trying to build firmware on Prod - I see that esphome.h contains one more string (see at the end of code):

```
#include "esphome/components/ota/automation.h"
#include "esphome/components/ota/ota_backend.h"
#include "esphome/components/ota/ota_backend_arduino_esp32.h"
#include "esphome/components/ota/ota_backend_arduino_esp8266.h"
#include "esphome/components/ota/ota_backend_arduino_libretiny.h"
#include "esphome/components/ota/ota_backend_arduino_rp2040.h"
#include "esphome/components/ota/ota_backend_esp_idf.h"
#include "esphome/components/ota/ota_component.h"
```
And here I got error on compiling firmware
```
In file included from src/esphome/components/ota/ota_component.cpp:2:
src/esphome/components/ota/ota_backend.h:14:6: error: multiple definition of 'enum esphome::ota::OTAResponseTypes'
   14 | enum OTAResponseTypes {
      |      ^~~~~~~~~~~~~~~~
```
Log: [prod.log](https://github.com/user-attachments/files/15908847/prod.log)

This happens because "ota_component.h" and "ota_backend.h" have same definitions

What I must do to exclude ota_component.h from generated esphome.h on Prod?

### Which version of ESPHome has the issue?

ESPHome 2024.6.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

No matter

### What platform are you using?

ESP8266

### Board

any

### Component causing the issue

OTA

### Example YAML snippet

```yaml
# main script
# ------------------
substitutions:
  devicename: "corridor-entry"
  deviceid: "corridor_entry"
esp8266:
  board: esp12e
packages:
  conf: !include
    file: config-template.yaml

binary_sensor:  
  - platform: gpio
    name: ${devicename}
    pin:
      number: GPIO13
      mode: 
        input: true


# config-template.yaml
# ------------------
substitutions:
  wifi_use_address: ${devicename}.local
  log_level: INFO
  log_baud_rate: '115200'

esphome:
  name: ${devicename}
  
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass
      priority: 10
    - ssid: !secret wifi_garage_ssid
      password: !secret wifi_pass    
      priority: 9
    - ssid: !secret himki_wifi_ssid
      password: !secret himki_wifi_pass
      priority: 8
  
  ap:
    ssid: ${devicename}
    password: !secret ap_pass

  use_address: ${wifi_use_address}    

# Enable Home Assistant API
api:
#   password: !secret hass_pass
  encryption:
    key: !secret hass_key
    
ota:
  - platform: esphome
    password: !secret ota_pass

captive_portal:

logger:
  level: ${log_level}
  baud_rate: ${log_baud_rate}

button:
  - platform: safe_mode
    name: ${devicename} Safe Mode Boot
    entity_category: diagnostic

  - platform: restart
    id: module_restart_btn
    name: ${devicename} Restart
    entity_category: diagnostic    

sensor:
  - platform: uptime
    name: ${devicename} Uptime

  - platform: wifi_signal
    name: ${devicename} WiFi Signal
    update_interval: 60s

binary_sensor:
  - platform: status
    name: ${devicename} Status
```
