### ISSUE TITLE
2024.6.1: `status_code` was not declared in this scope or HttpContainer has no member named `status_code`

### ISSUE THREAD

**Issue by andrewjswan** [esphome/issues#5925]
### The problem

In lambda function, error: `status_code` was not declared in this scope
or
In lambda function, error: `class std::shared_ptr<esphome::http_request::HttpContainer>` has no member named `status_code`

### Which version of ESPHome has the issue?

2024.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.3

### What platform are you using?

ESP32

### Board

Esp32 Node MCU

### Component causing the issue

HTTP Request https://esphome.io/components/http_request.html

### 2024.5.3 Config
```yaml
script:
  - id: send_state
    then:
      - http_request.get: 
          url: !lambda |-
            return ((std::string) "https://api.site.com/ping?key=" + id(my_key).state).c_str();
          on_response:
            then:
              - lambda: |-
                  if (status_code == 200)
                  {
                    id(send_status).publish_state(true);
                    id(ok)++;
                  }
                  else
                  {
                    id(send_status).publish_state(false);
                    id(error)++;
                  }
              - component.update: quality
    mode: queued
```

### 2024.6.1 Config
```yaml
script:
  - id: send_state
    then:
      - http_request.get: 
          url: !lambda |-
            return ((std::string) "https://api.site.com/ping?key=" + id(my_key).state).c_str();
          on_response:
            then:
              - lambda: |-
                  if (response.status_code == 200)
                  {
                    id(send_status).publish_state(true);
                    id(ok)++;
                  }
                  else
                  {
                    id(send_status).publish_state(false);
                    id(error)++;
                  }
              - component.update: quality
    mode: queued
```

### Anything in the logs that might be useful for us?

When building with **ESPHome 2024.6.1**, if I specify in the config as it was in 2024.5.3 ie current Documentation, section `http_request.get Action`:
```yaml
      on_response:
        then:
          - logger.log:
              format: 'Response status: %d, Duration: %u ms'
              args:
                - status_code
                - duration_ms
```
the error is:
```
In lambda function:\nsvitlobot.yaml:83:11: error: 'status_code' was not declared in this scope
```

When building with **ESPHome 2024.6.1**, if I specify it as in the current documentation in the `on_response Trigger` section:
```yaml
        on_response:
          then:
            - logger.log:
                format: "Response status: %d, Duration: %u ms"
                args:
                  - response.status_code
                  - response.duration_ms
```
then the error is:
```
In lambda function:\nsvitlobot.yaml:82:20: error: 'class std::shared_ptr<esphome::http_request::HttpContainer>' has no member named 'status_code'
```

### Additional information

This configuration was built without problems on 2024.5.3
