### ISSUE TITLE
Comments in lambda causes compiling warning

### ISSUE THREAD

**Issue by john-arvid** [esphome/issues#593]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

**Description of problem:**
When compiling it gives a warning that a comment is a multiline comment. The code still works as expected.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: esp01_mill04

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret wpa

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
web_server:
  port: 80

globals:
  - id: counter
    type: int
    restore_value: no
    initial_value: '0'
  - id: check_counter
    type: int
    restore_value: no
    initial_value: '0'
  - id: error_bool
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: max_temp
    type: int
    restore_value: no
    initial_value: '27'

switch:
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    pin: GPIO0
    id: relay1
    name: $devicename " Relay"
    
sensor:
  - platform: dht
    pin: GPIO3
    model: AM2302
    temperature:
      id: temp1
      name: $devicename " Temperature"
      on_value:
        then:
          - lambda: !lambda |-
              //If there has been an error before
              if (id(counter) != id(check_counter)) { 
                // Reset counters, since everything is back to normal 
                id(check_counter) = 0;
                id(counter) = 0;
              }
              
              id(counter) += 1;

    humidity:
      name: $devicename " Humidity"
    update_interval: 10s
    
script:
  - id: test1
    then:
      - lambda: !lambda |-
          // Increase counter to be used in error checks
          id(check_counter) += 1; 
          // Check if any difference (If there is a problem with the sensor the counter won't be increased) 
          if (id(counter) != id(check_counter)) {
            // Put a message in the logs //
            ESP_LOGE("main", "Something is wrong with the sensor, turning off heater");
            // Set the heater in OFF mode //
            auto call = id(my_climate).make_call();
            call.set_mode("OFF");
            call.perform();
            
            id(error_bool) = true;
          }
          // Just as an absolute safeguard, not really necesarry (Not tested) 
          else if (id(temp1).state > id(max_temp)) {
            // Put a message in the logs //
            ESP_LOGE("main", "It is too hot here, turning off heater");
            // Set the heater in OFF mode 
            auto call = id(my_climate).make_call();
            call.set_mode("OFF");
            call.perform();
            
            id(error_bool) = true;
          }
          else if (id(error_bool)) {
            // Reset the error bool 
            id(error_bool) = false;
            // Set the heater back in AUTO mode 
            auto call = id(my_climate).make_call();
            call.set_mode("AUTO");
            call.perform();
          }
          
          // Reset variables once in a while
          if (id(check_counter) > 1000) {
            id(check_counter) = 0;
            id(counter) = 0;
          }

interval:
  - interval: 10s
    then:
      - script.execute: test1

climate:
  - platform: bang_bang
    name: test
    id: my_climate
    sensor: temp1
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 22 °C
    visual:
      min_temperature: 5 °C
      max_temperature: 25 °C
      temperature_step: 0.5 °C

    heat_action:
      - switch.turn_on: relay1
    idle_action:
      - switch.turn_off: relay1

```

**Logs (if applicable):**

```
Compiling .pioenvs/esp01_mill04/src/main.cpp.o
src/main.cpp:144:3: warning: multi-line comment [-Wcomment]
   //       - lambda: !lambda "//If there has been an error before\nif (id(counter) != id(check_counter))\
   ^
src/main.cpp:167:3: warning: multi-line comment [-Wcomment]
   //     - lambda: !lambda "// Increase counter to be used in error checks\nid(check_counter)\
   ^
Linking .pioenvs/esp01_mill04/firmware.elf

```

**Additional information and things you've tried:**

Tried to remove the first comment, but then it gives a warning about the next.
Have tried to comment inline with the code, tried with /* */.
