### ISSUE TITLE
the new one_wire  / dallas_temp are not working (Found no devices!)

### ISSUE THREAD

**Issue by Links2004** [esphome/issues#5936]
### The problem

after updateing to 2024.6.1 i get "Found no devices!" for my one wire bus.
this happens with multiple devices ESP32 and ESP32-C3 based

where there any changes other the the rename like to the timing, internal pullups?

example ESP32-C3:

log:
```
[17:01:45][C][gpio.one_wire:016]: GPIO 1-wire bus:
[17:01:45][C][gpio.one_wire:017]:   Pin: GPIO5
[17:01:45][W][gpio.one_wire:078]:   Found no devices!
```

changes to yaml for the braking changes:
```diff
--- a/esp32-keller-technik-ac.yaml
+++ b/esp32-keller-technik-ac.yaml
@@ -29,6 +29,7 @@ api:
     key: "bbbbbbbbbbbbbbbbbbbb"
 
 ota:
+  platform: esphome
   password: "aaaaaaaaaaaaaaa"
 
 wifi:
@@ -100,11 +102,12 @@ status_led:
     number: 8
     inverted: true
 
-dallas:
-  - pin: 5
-    update_interval: 10s
+one_wire:
+  - platform: gpio
+    pin: 5
     id: DA1
 
+
 # UART config
 uart:
   tx_pin: 4
@@ -209,23 +212,25 @@ sensor:
     lambda: |-
       return (id(midea_climate).preset == CLIMATE_PRESET_ECO);
 
-  - platform: dallas
+  - platform: dallas_temp
     address: 0x04c3ed7312646128
+    update_interval: 10s
     id: temp_room
     name: "Room"
-    dallas_id: DA1
+    one_wire_id: DA1
     filters:
     - median:
         window_size: 6
         send_every: 1
         send_first_at: 1
 
-  - platform: dallas
+  - platform: dallas_temp
     icon: mdi:snowflake-thermometer
     address: 0xbe9d177312646128
+    update_interval: 10s
     name: "Evaporator"
     id: temp_evaporator
-    dallas_id: DA1
+    one_wire_id: DA1
     filters:
     - median:
         window_size: 6
```

### Which version of ESPHome has the issue?

2024.6.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32 c3 super mini

### Component causing the issue

dallas_temp

### Example YAML snippet

```yaml
one_wire:
  - platform: gpio
    pin: 5
    id: DA1

sensors:
  - platform: dallas_temp
    address: 0x04c3ed7312646128
    update_interval: 10s
    id: temp_room
    name: "Room"
    one_wire_id: DA1
    filters:
    - median:
        window_size: 6
        send_every: 1
        send_first_at: 1

  - platform: dallas_temp
    icon: mdi:snowflake-thermometer
    address: 0xbe9d177312646128
    update_interval: 10s
    name: "Evaporator"
    id: temp_evaporator
    one_wire_id: DA1
    filters:
    - median:
        window_size: 6
        send_every: 1
        send_first_at: 1
```

### Anything in the logs that might be useful for us?

```txt
did work 100% with 2024.5.5 and flashing back via 2024.5.5 solves the problem.
```
