### ISSUE TITLE
error: 'class esphome::http_request::HttpRequestArduino' has no member named 'get_string'

### ISSUE THREAD

**Issue by DaveOke** [esphome/issues#5945]
### The problem

Lambda @ https://esphome.io/cookbook/http_request_sensor.html fails with: error: 'class esphome::http_request::HttpRequestArduino' has no member named 'get_string'

Happned after upgrading to 2024.6.1

UPDATE: Followed new instructions and all is well again.

### Which version of ESPHome has the issue?

2024.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.3

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

lambda

### Example YAML snippet

```yaml
http_request:
  useragent: esphome/device
  id: http_request_id
  verify_ssl: false

interval:
    - interval: 60s
      then:
        - http_request.get:
            url: http://10.0.1.8:1880/api/humidity
            on_response:
              then:
                - lambda: |-
                    json::parse_json(id(http_request_id).get_string(), [](JsonObject root) {
                        id(humidity).publish_state(root["value"]);
                    });
```

### Anything in the logs that might be useful for us?

```txt
/config/esphome/Co2.yaml: In lambda function:
/config/esphome/Co2.yaml:57:41: error: 'class esphome::http_request::HttpRequestArduino' has no member named 'get_string'
   57 |                     json::parse_json(id(http_request_id).get_string(), [](JsonObject root) {
      |                                         ^~~~~~~~~~
```

**Comment by pksoft585** [comment]
Explanation is in documentation there: [https://esphome.io/components/http_request.html#get-values-from-a-json-body-response](url):

```yaml
- http_request.get:
    url: http://10.0.1.8:1880/api/humidity
    capture_response: true
    on_response:
      then:
        - lambda: |-
            json::parse_json(body, [](JsonObject root) -> bool {
                id(humidity).publish_state(root["value"]);
                return true;
            });```

**Comment by andrewjswan** [comment]
> ```yaml
> capture_response: true
> ```

In ESP IDF i get:
```
HTTP_CLIENT: Body received in fetch header state
```
in Arduino i get or `empty body` or stuck on get

**Comment by pksoft585** [comment]
I'm using Arduino framework without problem - but on ESP32 (WT32-ETH01):

```yaml
esp32:
  board: esp-wrover-kit
  framework:
    type: arduino
...

http_request:
  useragent: esphome/device
  timeout: 10s
  id: http_req
  follow_redirects: False
  redirect_limit: 1
  verify_ssl: false

...

              - http_request.get:
                  headers:
                    content-Type: application/json
                  url: !secret url_ble
                  capture_response: true
                  on_response:
                    - if:
                        condition:
                          lambda: |-
                            return response->status_code == 200;
                        then:
                          - logger.log: "Get value from BLE temperature..."
                          - lambda: |-
                              json::parse_json(body, [](JsonObject root) -> bool {
                                  id(ble_temperature).publish_state(root["value"]);
                                  return true;
                              });
                        else:
                          - logger.log: "Get value from BLE temperature - error!!!"

...
```
