### ISSUE TITLE
!remove not working if id is constructed from substitution

### ISSUE THREAD

**Issue by Masterz69** [esphome/issues#5948]
### The problem

`!remove` do not "see" component which name is not static like `sensor_x`, but have substitution inside: `sensor_${id}`.
Error about 'source not found' shown then.

### Which version of ESPHome has the issue?

2024.4.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
----- main file -----

packages: !include { file: xxx.yaml, vars: { id: 1 } }
sensor:
  - id: !remove sensor_1

----- xxx.yaml -----

sensor:
 - platform: template
   id: sensor_${id}
```
