### ISSUE TITLE
Web Server Version 3 Modbus Components

### ISSUE THREAD

**Issue by creepystefan** [esphome/issues#5953]
### The problem

Hello.
Web Server (Version 3) Sorting don`t work with Modbus_Controller Components.

### Which version of ESPHome has the issue?

2024.5.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.4

### What platform are you using?

ESP32

### Board

ESP

### Component causing the issue

modbus

### Example YAML snippet

```yaml
web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
  version: 3
 

- platform: modbus_controller
    name: "interne Temperatur"
    web_server_sorting_weight: 2
    force_new_range: true
    address: 0x0D
    register_type: "holding"
    value_type: U_WORD
    device_class: "TEMPERATURE"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    accuracy_decimals: 2
    filters:
     - multiply: 0.1
```

### Anything in the logs that might be useful for us?

```txt
[web_server_sorting_weight] is an invalid option for [sensor.modbus_controller]. Please check the indentation.
  web_server_sorting_weight: 2
  force_new_range: True
  address: 13
  register_type: holding
  value_type: U_WORD
  device_class: TEMPERATURE
  unit_of_measurement: °C
  icon: mdi:thermometer
  accuracy_decimals: 2
  filters: 
    - multiply: 0.1
```

### Additional information

Hello.
Web Server (Version 3) Sorting don`t work with Modbus_Controller Components.
