### ISSUE TITLE
web UI does not load

### ISSUE THREAD

**Issue by deanfourie1** [esphome/issues#5956]
### The problem

Using ESPhome with Homeassistant,

I have enabled the web server on the ESP32 via esphome, but the page does not load. If it does load, if it loads it only loads basics like WiFI settings and OTA, no logs and no entity controls.

### Which version of ESPHome has the issue?

2024.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.4

### What platform are you using?

ESP32

### Board

esp32minikit

### Component causing the issue

web

### Example YAML snippet

```yaml
web_server:
  port: 80
  log: true
  local: True
  include_internal: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
```

### Anything in the logs that might be useful for us?

```txt
Nothing abnormal in the logs.
```
