### ISSUE TITLE
[modbus_controller] Float registers are sent as integer values

### ISSUE THREAD

**Issue by Petapton** [esphome/issues#5973]
### The problem

In the new server part of the modbus controller integration, when a register is set to return a float value, an integer-encoded value is written on the serial line (upon read command).
This is due to a straight call to `number_to_payload` instead of `float_to_payload` in `ModbusController::on_modbus_read_registers`.

For example, in the yaml below, 0x00 0x00 0x00 0x01 is transmitted.

### Which version of ESPHome has the issue?

2024.6

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Component causing the issue

modbus_controller

### Example YAML snippet

```yaml
...

modbus_controller:
  - modbus_id: modbus_server
    address: 0x1
    server_registers:
      - address: 0x2004
        value_type: FP32
        read_lambda: |-
          return 1.44;

...
```
