### ISSUE TITLE
Can non longer do an OTA update with ESP32 in safe_mode after ESPHOME update 2024.6.0 when using on_begin: action under ota:

### ISSUE THREAD

**Issue by Dilbert66** [esphome/issues#5976]
### The problem

Latest changes related to safe_mode and OTA configuration seems to have broken the ability to do an OTA update if the device goes into safe_mode (either manually via a switch or via 10 failed boot attempts) when there is an on_begin action specified for the ota:  I keep getting connection refused.  When the on_begin section is on, the esphome.ota component does not load (no log dump display) during transition to safe_mode. The esphome.ota does show up fine and ota works when the offending on_begin is removed.  

My safe mode and ota config options:
```
ota:
   password: !secret ota_password
   platform: esphome
   on_begin:
          switch.turn_off: connection_status_switch 
          
safe_mode:
```

### Which version of ESPHome has the issue?

2024.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core: 2024.6.4

### What platform are you using?

ESP32

### Board

ESP32-c3 and esp32-d1 mini

### Component causing the issue

OTA and safe_mode

**Comment by randybb** [comment]
Any logs? I have tested it on S3 and no issues.

**Comment by Dilbert66** [comment]
I'm doing a few more tests.  I suspect it's a custom component I'm loading that is affecting it as when I use a barebones config, the ota component loads fine in safe mode. I will post more info later.

**Comment by Dilbert66** [comment]
Ok, found the culprit. I thought I had commented that out when testing. Anyhow it's an on_begin  action under the ota that's causing the failure:
```
ota:
   password: !secret ota_password
   platform: esphome
   on_begin:
          switch.turn_off: connection_status_switch 
```
