### ISSUE TITLE
Error Compiling new config for bk7231-qfn32-tuya device

### ISSUE THREAD

**Issue by mebuttle** [esphome/issues#5978]
### The problem

I keep receiving a file not found error when trying to compile for a fresh install on a BKN7231N device.
Linking .pioenvs/bar-fridges/raw_firmware.elf
|-- Image 1: raw_firmware.elf
/data/cache/platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: cannot find crti.o: No such file or directory
/data/cache/platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
|-- Generated file not found: .pioenvs/bar-fridges/raw_firmware.elf
*** [.pioenvs/bar-fridges/raw_firmware.elf] Error 1

### Which version of ESPHome has the issue?

2024.6.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.3

### What platform are you using?

BK72XX

### Board

BNETA - BK7231n

### Component causing the issue

Compile

### Example YAML snippet

```yaml
esphome:
  name: bar-fridges
  friendly_name: Bar Fridges

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hz6zslidjqS7d6Sf0izA7I2lahAzfJcAjUFSRBGY9pA="

ota:
  - platform: esphome
    password: "9002da242a8a4cddcfd62c17ad3b7dcd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 196.168.19.131

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bar-Fridges Fallback Hotspot"
    password: "fNQdq6JixR28"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.6.3
INFO Reading configuration /config/esphome/bar-fridges.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing bar-fridges (board: generic-bk7231n-qfn32-tuya; framework: arduino; platform: libretiny @ 1.5.1)
--------------------------------------------------------------------------------
Warning! Non-Git installations are NOT SUPPORTED.
HARDWARE: BK7231N 120MHz, 256KB RAM, 1.03MB Flash
 - framework-arduino-api @ 2022.8.24+sha.237b10a 
 - framework-beken-bdk @ 0.0.0+v2021.06.07.sha.6491b8c 
 - library-flashdb @ 1.2.0+sha.d5c892f 
 - library-freertos @ 9.0.0+sha.95cc959 
 - library-freertos-port @ 2023.5.23+sha.a917d93 
 - library-lwip @ 2.1.3-bdk+sha.4ee4d34 
 - library-printf @ 6.1.0+sha.28a79bd 
 - library-uf2ota @ 5.0.0+sha.f955412 
PLATFORM VERSIONS:
 - libretiny @ 1.5.1
 - ltchiptool @ 4.11.1
CUSTOM OPTIONS:
 - fw_name = esphome
 - fw_version = 2024.6.3
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.3
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 1.1.0
|-- noise-c @ 0.1.4
Linking .pioenvs/bar-fridges/raw_firmware.elf
|-- Image 1: raw_firmware.elf
/data/cache/platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: cannot find crti.o: No such file or directory
/data/cache/platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
|-- Generated file not found: .pioenvs/bar-fridges/raw_firmware.elf
*** [.pioenvs/bar-fridges/raw_firmware.elf] Error 1
========================= [FAILED] Took 26.93 seconds =========================
```
