### ISSUE TITLE
ESP32 Bootloop

### ISSUE THREAD

**Issue by crippit** [esphome/issues#598]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io running on Docker on a Ubuntu Machine
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**Affected component:**

Booting ESPHome

**Description of problem:**
When flashing an ESP32 with ESPHome the device bootloops and throws an error in the console. The ESP32 seems irrelevant and the issue has been replicated on both an ESP32 (NodeMCU) and ESP32 Cam (AI Thinker). Flashing with other code works, so eliminates an issue with the board.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32cam
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "xxx"
  password: "xxxyyyzzz"
  manual_ip:
    static_ip: 192.168.0.99
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: My Camera
  # ...
  
  # Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: esp32cam light

```

**Logs (if applicable):**

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

```

**Additional information and things you've tried:**
