### ISSUE TITLE
Strange behavior with DS18B20

### ISSUE THREAD

**Issue by deanfourie1** [esphome/issues#5983]
### The problem

When I setup the one_wire component on its own, it finds my DS18B20 sensor and displays the ID,  However, when I setup the DS18B20 device as a sensor, with the address specified, I get the error no sensors found.

With the following code,

```
one_wire:
  - platform: gpio
    pin: GPIO14
```

![image](https://github.com/esphome/issues/assets/71812804/a9defdff-2e22-4c82-8743-4dc2f9b05bda)

And with the following code,

```
one_wire:
  - platform: gpio
    pin: GPIO14

sensor:
  - platform: dallas_temp
    address: 0x950121128170a628
    name: "Temp"
```

![image](https://github.com/esphome/issues/assets/71812804/c9a35211-100d-4461-b346-e7358c2efa5c)

### Which version of ESPHome has the issue?

2024.6.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.4

### What platform are you using?

ESP32

### Board

Kinkony KC868-A8

### Component causing the issue

dallas_temp
