### ISSUE TITLE
Register count is an invalid option for number

### ISSUE THREAD

**Issue by ricmik** [esphome/issues#5985]
### The problem

  [register_count] is an invalid option for [number.modbus_controller]. Did you mean [register_type]?

### Which version of ESPHome has the issue?

2024.6.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

modbus_controller

### Example YAML snippet

```yaml
number:
  - platform: modbus_controller
    name: "Duration Holiday"
    address: 1100
    value_type: S_WORD
    min_value: 1
    max_value: 365
    icon: mdi:fan-clock
    unit_of_measurement: "d"
    register_count: 5
```

### Additional information

I am trying to optimize the Modbus communication.

I get the same error for "binary_sensor", but for "sensor" it works.
