### ISSUE TITLE
HTU21D doesn't work after deep sleep

### ISSUE THREAD

**Issue by ezar** [esphome/issues#599]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 / Lolin32

**Affected component:**

htu21d

**Description of problem:**
Temperature & Humidity htu21d doesn't read after deep sleep. First read works fine, but no other read occurs. 
Dallas temperature sensor works fine every time.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32_pool
  platform: ESP32
  board: lolin_d32

wifi:
  ssid: 'xxxxxxxxxx'
  password: 'xxxxxxxxxxx'

mqtt:
  broker: 'xxxxxxxxxxx'
  username: 'xxxxxxxxxx'
  password: 'xxxxxxxxxxx'
  discovery: False
  discovery_retain: False
  birth_message:
  will_message:
  on_message:
    topic: esp32_pool/ota_mode
    payload: "ON"
    then:
      - deep_sleep.prevent: deep_sleep_1
      - logger.log: "OTA_mode enabled, halting deep sleep"

# Enable logging
logger:
  level: DEBUG

deep_sleep:
  id: deep_sleep_1
  run_duration: 5s
  sleep_duration: 45min

dallas:
  - pin: 15
  
i2c:
  sda: 21
  scl: 22
  scan: True
  
switch:
  - platform: restart
    name: "Pool Restart"
  - platform: shutdown
    name: "Pool Shutdown"
    id: shutdown1
    
sensor:
  - platform: uptime
    name: "Pool Uptime Sensor"
  - platform: wifi_signal
    name: "Pool WiFi Signal Sensor"
    update_interval: 15s
  - platform: dallas
    address: 0x000416849074FF28
    name: "Pool Temperature"  
  - platform: htu21d
    temperature:
      name: "Pool External Temperature"
    humidity:
      name: "Pool External Humidity"
    update_interval: 60s
  - platform: adc
    pin: 34
    attenuation: 11db
    name: "Pool Voltage Battery"
#     on_value_range:
#       below: 3.00
#       then:
#         - switch.turn_on:
#             id: shutdown1

binary_sensor:
  - platform: status
    name: "Pool Status"

# Enable Home Assistant API
#api:

ota:

```

**Logs (if applicable):**

```


```

**Additional information and things you've tried:**
