### ISSUE TITLE
SGP4x featureset should be updated for newer devices

### ISSUE THREAD

**Issue by mericas** [esphome/issues#5995]
### The problem

sgp4x.ccp determines if the device is a SGP40 or SGP41 based on the lower 9 bits of the featureset returned by SGP4X_CMD_GET_FEATURESET.  These 9 bits are compared against 0x0020 for SGP40 and 0x0040 for SGP41.  Unfortunately some newer devices (in particular ones from Adafruit) return a featureset of 0x3240, resulting in the code mistaking the device for a SGP41.

### Which version of ESPHome has the issue?

2024.5.5

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

Adafruit QT Py S3 with 2MB PSRAM WiFi Dev Board with STEMMA QT

### Component causing the issue

sgp4x

### Example YAML snippet

```yaml
sensor:
  - platform: sgp4x
    voc:
      name: "VOC Index"
#   should fail on a SGP40
    nox:
      name: "NOX Index"
    compensation:
      humidity_source: humidity
      temperature_source: temperature
```

### Additional information

[Adafruit Forum post](https://forums.adafruit.com/viewtopic.php?t=202391)
[Adafruit issue](https://github.com/adafruit/Adafruit_CircuitPython_SGP40/issues/19)

In addition to the featureset update, recent chips need a longer self-test timeout value ([see](https://github.com/adafruit/Adafruit_SGP40/commit/14449d797463f4e074888bf97a8c9a4345469089))

The feature id is not documented as far as I can tell.  In particular I don't know what the upper 2 bytes are for SGP41 and if there are multiple feature ids for that device as well.
