### ISSUE TITLE
Neopixel RGBW - White/RGB channel toggle

### ISSUE THREAD

**Issue by daned33** [esphome/issues#600]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip 1.13.6

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1

**Affected component:**

Neopixel

**Description of problem:**

as per issue https://github.com/esphome/issues/issues/117 "Neopixel White LED are independent / unable to TurnOff"

This issue seems to persist after your changes https://github.com/esphome/esphome-core/pull/552 

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: neopixelbus
    type: RGBW
    variant: SK6812
    method: BIT_BANG
    pin: GPIO15
    num_leds: 10
    name: "TEST RGBW"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

I have made a home assistant automation that is a bandaid fix

```yaml
- alias: RGB on white off
  trigger:
    platform: state
    entity_id: sensor.bedside_rgb
  condition:
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.sensor.bedside_white.last_changed)) > 1 }}"
  action:
  - service: light.turn_on
    data:
        entity_id: light.bedside
        white_value: 0
  - service: light.turn_on
    data:
        entity_id: light.bedside
        brightness: 150
        
- alias: white on RGB off
  trigger:
    platform: state
    entity_id: sensor.bedside_white
  condition:
    - condition: template
      value_template: "{{ (as_timestamp(now())-as_timestamp(states.sensor.bedside_rgb.last_changed)) > 1 }}"
  action:
  - service: light.turn_on
    data:
        entity_id: light.bedside
        brightness: 1
        rgb_color: [255,255,255]
```
