### ISSUE TITLE
http_request now produce an unspecified error and exit container instead of reporting the client code error

### ISSUE THREAD

**Issue by vargr-cg** [esphome/issues#6010]
### The problem

Older versions of http request were reporting client error codes when connections was failing  such as " -1"  from the on_response trigger

This could be used for determining if a device was up or not and publish state for a sensor or a switch for example.
It now fails with an unspecified error  wich is cleared later. 

The container now  exits and no return code or other data are provided.

### Which version of ESPHome has the issue?

2024.6.6

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2024.7.0

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

http_request

### Example YAML snippet

```yaml
esphome:
  name: ir_0
esp8266:
  board: esp01_1m
  framework:
    version: 3.0.2 
  restore_from_flash: true

http_request:
  id: http_request_data
  esp8266_disable_ssl_support: true
  #timeout: 0.5s

### ... sensor,  switches, etc 


script:
####### get fbr state ############
    - id: get_fbr_state
      mode: single
      then:
        - http_request.get:
             url: "http://192.168.0.253:54243/device.xml"
             capture_response: true
             on_response:
               then:
                 - lambda: |-
                    if (response->status_code == 200) {
                      id(fbx_oo).publish_state(true);
                    } else {
                      id(fbx_oo).publish_state(false);
                    };

# or 
    - id: get_lgtv_state
      mode: single
      then:
        - http_request.get:
            url: "http://192.168.0.251/binary_sensor/tv_state"
            #capture_response: true
            on_response:
               then:
                - logger.log:
                    format: "LGTV request Status code %d"
                    args:
                      - response->status_code
                - lambda: |-
                    if (response->status_code == 200) {
                      id(lg_oo).publish_state(true);
                    } else if (response->status_code == -1 ) {
                      id(lg_oo).publish_state(false);
                    };
```

### Anything in the logs that might be useful for us?

```txt
[17:14:20][W][http_request.arduino:104]: HTTP Request failed; URL: http://192.168.0.253:54243/device.xml; Error: connection failed
[17:14:20][E][component:164]: Component http_request set Error flag: unspecified

[17:14:21][E][component:176]: Component http_request cleared Error flag
```

**Comment by rwdnnz** [comment]
I'm facing a similar issue with the later releases of ESPHome 2024.6.x where a 404 from my API is being treated as a failed request.

```yaml
- http_request.get:
          capture_response: true
          headers:
            content-Type: application/json
          url: !lambda |-
            return ((std::string) "${music_control_api}/lookup?key=" + x);
          on_response:
            - if:
                condition:
                  lambda: "return response->status_code == 200;"
                then:
                  - lambda: |-
                      id(tag_found_in_db).publish_state(true);
                      json::parse_json(body, [](JsonObject root) -> bool {
                      id(artist).publish_state(root["artist"]);
                      id(album).publish_state(root["album"]);
                      return true;
                      });
                  - output.turn_on: play_button_led
                else:
                    - output.turn_on: play_button_led
                    - delay: 0.5s
                    - output.turn_off: play_button_led
                    - delay: 0.5s
```

Which results in a failed request when a 404 is returned and we never get into the else statement now.

```
[06:44:17][E][http_request.arduino:112]: HTTP Request failed; URL: http://music-control-api.example.com/lookup?key=53-53-FF-99-BA-00-01; Code: 404
[06:44:17][E][component:164]: Component http_request set Error flag: unspecified
...
[06:44:18][E][component:176]: Component http_request cleared Error flag
```
