### ISSUE TITLE
hostname is not set correctly on arduino framework since 2024.6.0b1 revision.

### ISSUE THREAD

**Issue by NewoPL** [esphome/issues#6014]
### The problem

hostname is not set correctly on arduino framework since 2024.6.0b1 revision.
after ota you cannot connect to the device using the device name
the device is seen on the network esp32c3-FDD71C instead of its name from config.yaml.

### Which version of ESPHome has the issue?

2024.6.0b1 till the 20246.6

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

unrelevant

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1

### Example YAML snippet

```yaml
esphome:
  name: curtains-02
  friendly_name: Curtains 02
  on_boot:
    - lambda: |-
        id(device_ota).set_auth_password("${ota_old_password}");

esp32: 
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: recommended

wifi:
  domain: .lan
  networks:
    - ssid: ${wifi_ssid}
      password: ${wifi_password}
```
