### ISSUE TITLE
Component beken_spi_led_strip crashes device

### ISSUE THREAD

**Issue by michal4132** [esphome/issues#6016]
### The problem

After adding beken_spi_led_strip to the YAML configuration and uploading it, the device fails to connect to WiFi and does not create a fallback AP. Unfortunately, I do not have access to the logs at this time.

### Which version of ESPHome has the issue?

2024.6.4

### What type of installation are you using?

pip

### What platform are you using?

BK72XX

### Board

generic-bk7231n-qfn32-tuya

### Component causing the issue

beken_spi_led_strip

### Example YAML snippet

```yaml
light:
  - platform: beken_spi_led_strip
    rgb_order: GRB
    pin: P16
    num_leds: 30
    chipset: ws2812
    name: "My Light"
```
