### ISSUE TITLE
Compile Error with Remote Receiver and Pico w

### ISSUE THREAD

**Issue by sensorware** [esphome/issues#6021]
### The problem

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
COMPILER ERROR LOG
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

INFO ESPHome 2024.6.6
INFO Reading configuration /config/esphome/433-sample.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/5974/head
INFO Generating C++ source...
INFO Compiling app...
Processing 433-sample (board: rpipicow; framework: arduino; platform: https://github.com/maxgerhardt/platform-raspberrypi.git)
--------------------------------------------------------------------------------
HARDWARE: RP2040 133MHz, 264KB RAM, 2MB Flash
 - framework-arduinopico @ 1.30702.0 (3.7.2) 
 - tool-rp2040tools @ 1.0.2 
Flash size: 2.00MB
Sketch size: 1.00MB
Filesystem size: 1.00MB
Maximium Sketch size: 1044480 EEPROM start: 0x101ff000 Filesystem start: 0x100ff000 Filesystem end: 0x101ff000
Dependency Graph
|-- WiFi @ 1.0.0
|-- LEAmDNS @ 1.2
|-- Updater @ 1.0
|-- noise-c @ 0.1.4
|-- MD5Builder @ 1.0.0
|-- lwIP-Ethernet @ 1
|-- lwIP_CYW43 @ 1
|-- SPI @ 1.0
Compiling .pioenvs/433-sample/src/main.cpp.o
/config/esphome/433-sample.yaml: In function 'void setup()':
/config/esphome/433-sample.yaml:189:60: error: no matching function for call to 'esphome::remote_receiver::RemoteReceiverComponent::set_tolerance(int)'
In file included from src/esphome/components/remote_base/abbwelcome_protocol.h:5,
                 from src/esphome.h:37,
                 from src/main.cpp:3:
src/esphome/components/remote_base/remote_base.h:192:8: note: candidate: 'void esphome::remote_base::RemoteReceiverBase::set_tolerance(uint32_t, esphome::remote_base::ToleranceMode)'
  192 |   void set_tolerance(uint32_t tolerance, ToleranceMode tolerance_mode) {
      |        ^~~~~~~~~~~~~
src/esphome/components/remote_base/remote_base.h:192:8: note:   candidate expects 2 arguments, 1 provided
*** [.pioenvs/433-sample/src/main.cpp.o] Error 1
========================= [FAILED] Took 29.01 seconds =========================

### Which version of ESPHome has the issue?

2024.6.6 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.7.1

### What platform are you using?

RP2040

### Board

PICO WH

### Example YAML snippet

```yaml
esphome:
  name: 433mhz-sample
  friendly_name: 433mhz-sample

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

sensor:
  - platform: adc
    pin: TEMPERATURE
    name: "Core Temperature"
    unit_of_measurement: "°C"
    filters:
      - lambda: return 27 - (x - 0.706f) / 0.001721f;   
  - platform: adc
    pin: TEMPERATURE
    name: "Core Temperature (F)"
    unit_of_measurement: "°F"
    filters:
        - lambda: return ((27 - (x - 0.706f) / 0.001721f) * 9.0f/5.0f) + 32;

output:
  - platform: gpio
    pin: 32
    id: PicoStatusLED

interval:
  - interval: 500ms
    then:
      - output.turn_on: PicoStatusLED
      - delay: 250ms
      - output.turn_off: PicoStatusLED

external_components:
  - source: github://pr#5974
    components: [remote_transmitter, remote_receiver]
    refresh: always
  
remote_receiver:
  pin: 
    number: 0
  dump: rc_switch
  tolerance: 25
  filter: 250us
  idle: 4ms
  buffer_size: 10kb
  
binary_sensor:
  - platform: remote_receiver
    name: "Door Remote - A"
    rc_switch_raw:
      code: '000011101011110011110100'

  - platform: remote_receiver
    name: "Door Remote - B"
    rc_switch_raw:
      code: '111111110101111101110001'

  - platform: remote_receiver
    name: "Door Remote - C"
    rc_switch_raw:
      code: '111111110101111101110010'

  - platform: remote_receiver
    name: "Door Remote - D"
    rc_switch_raw:
      code: '111111110101111101111000'      

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "="

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "433Mhz-Sample Fallback Hotspot"
    password: ""
```

### Additional information

This sample worked 8 weeks ago.
