### ISSUE TITLE
ESP32-C3 consumptions and internal temperature peak

### ISSUE THREAD

**Issue by Rihan9** [esphome/issues#6029]
### The problem

Hi all,
I'm not sure if here is the correct plate to write about it.
I recently bought some devKit for ESP32-C3 (SuperMini version with and without led, you can easily find them on aliexpress) to use them as brain on my multi-sensor device (presence, light, temperature and humidity). I then noticed that the temperature sensor have some strange peaks of temperature and realize that the problem was on the esp board. I remove all the attached sensor, write a simple yaml configuration and let the esp run alone through the night. I didn't solve the issue, so something is strange on the esp itself.
I'm posting here* the code and here** the screenshot of the internal temperature monitoring.

I have already tried to change the device. The results showed here are from the second device

I'm going to disable one peripheral at a time and restart the monitoring. I'll post in this issue the results.

*
```
esphome:
  name: esp32c3-test
  friendly_name: Esp32-C3 Test
  platformio_options:
    board_build.f_cpu: 80000000L

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: **OMITTED**

ota:
  password: **OMITTED**

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C3-Test Fallback Hotspot"
    password: **OMITTED**

captive_portal:

uart:
  id: uart_bus
  rx_pin: 
    number: GPIO20
    mode:
      input: true
      pullup: true
  tx_pin: 
    number: GPIO21
    mode:
      input: true
      pullup: true
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  data_bits: 8

i2c:
  sda: GPIO10
  scl: GPIO09
  scan: false
  id: bus_a

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    entity_category: "diagnostic"

light:
  - platform: status_led
    name: "Status Led"
    pin:
      number: GPIO08
      inverted: true
```

**
![image](https://github.com/esphome/issues/assets/33684020/ca5852ee-e1fd-4976-8f5b-574b6c83b985)

### Which version of ESPHome has the issue?

2024.5.5

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.6.4

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1

**Comment by Rihan9** [comment]
Hi,
I completed the tests with UART and I2C disabled, with the same behavior. I noticed that 2 board with a different start time have the consumption peak at the same hour

**Comment by gabest11** [comment]
```
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_CTRL_MODEM_SLEEP: y
```
