### ISSUE TITLE
ESP32-C6 ADC issue / error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; 

### ISSUE THREAD

**Issue by lboue** [esphome/issues#6038]
### The problem

**ESP32-C6 ADC issue**

error: 'class esphome::adc::ADCSensor' has no member named 'channel2_'; 

### Which version of ESPHome has the issue?

2024.6.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.7.2

### What platform are you using?

ESP32-IDF

### Example YAML snippet

```yaml
esphome:
  name: c6-can
  friendly_name: C6 CAN

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: "5.2.2"
    platform_version: 6.7.0
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

sensor:
  - platform: adc
    id: source_sensor
    pin: GPIO0
```
