### ISSUE TITLE
ESP32-S3 won't compile anymore. `src/esphome/components/sensor/automation.cpp' not found

### ISSUE THREAD

**Issue by ronald-winter** [esphome/issues#6040]
### The problem

During the developement of a project  esphome suddenly does not compile anymore. it worked fine in the beginning. Suddenly files in src/esphome/components/sensor/ seemed to be missing. Different files pop up on retrys.

### Which version of ESPHome has the issue?

2024.6.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2024.7.2 Supervisor 2024.06.2 Operating System 12.4 Frontend 20240705.0

### What platform are you using?

ESP32-IDF

### Board

esp32-s3-devkitc-1

### Example YAML snippet

```yaml
esphome:
  name: voiceassistant
  friendly_name: VoiceAssistant

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CImxVOEESvL0TEZbI2U+i4BFRY2WbuJfw/8YU0/1Z7E="

ota:
  - platform: esphome
    password: "0ace4a32073e923d84e28c95f406e8e0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Voiceassistant Fallback Hotspot"
    password: "dhoYgQeBcp3A"

captive_portal:

# Example configuration entry
esp32_touch:
  setup_mode: False
  measurement_duration: 0.25ms

binary_sensor:
  - platform: esp32_touch
    name: "ESP32 Touch Pad GPIO5"
    id: esp32_touch_pad
    pin: GPIO5
    threshold: 150000
    internal: False
```

### Anything in the logs that might be useful for us?

```txt
Processing voiceassistant (board: esp32-s3-devkitc-1; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - framework-espidf @ 3.40407.240606 (4.4.7) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.4
*** [.pioenvs/voiceassistant/src/esphome/components/sensor/automation.o] Source `src/esphome/components/sensor/automation.cpp' not found, needed by target `.pioenvs/voiceassistant/src/esphome/components/sensor/automation.o'.
========================== [FAILED] Took 5.80 seconds ==========================
```
