### ISSUE TITLE
Tuya climate: preset eco only works with boolean datapoints

### ISSUE THREAD

**Issue by szupi-ipuzs** [esphome/issues#6048]
### The problem

I have this fairly old esp8266-based tuyamcu [heater](https://www.grzejnik.net/warmtec-ewr-2000-grzejnik-elektryczny-2000w-wifi-p-879.html) that have recently converted it to esphome.
It supports 2 modes: "boost" and "eco" - that can be selected by setting datapoint 4 to 0 or 1 appropriately.

Unfortunately when trying to set this up via the "eco" preset in tuya/climate component I'm getting the following error:

```
Setting eco: ON
Attempt to set datapoint 4 with incorrect type
```

Indeed, looking at the code I can see that it assumes a boolean datapoint will be used for the eco mode. In my case this is an enum. 
Also, by looking at [the configs that people submit](https://github.com/search?q=boost+repo%3Amake-all%2Ftuya-local+path%3A*.yaml&type=Code&ref=advsearch&l=&l=&p=4) to github/make-all/tuya-local we can see that there are tuya devices that report their mode (ie presets) using datapoints of many types: strings, booleans and enums.

So to correctly support all of these devices, the component should allow to specify the datapoint type for a preset along with the mapping that is used for converting the datapoint value to selected preset - mayabe similarly as it is done in github/make-all/tuya-local configs.

### Which version of ESPHome has the issue?

2024.6.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Component causing the issue

tuya/climate

### Example YAML snippet

```yaml
climate:
  - platform: "tuya"
    name: "Heater"
    switch_datapoint: 7
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    supports_heat: True
    supports_cool: False
    preset:
      eco:
        datapoint: 4
    visual:
      min_temperature: 15
      max_temperature: 35
      temperature_step: 1
```

**Comment by dexn** [comment]
I have the exact same problem. This is what I did as a workaround
```
uart:
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 9600

tuya:

climate:
  - platform: tuya
    name: "Heater"
    id: heater
    switch_datapoint: 7
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    supports_heat: true
    # Using fan_mode for eco because eco_mode does not support enum
    fan_mode:
      datapoint: 4
      high_value: 0
      low_value: 1
    visual:
      min_temperature: 18
      max_temperature: 30
      temperature_step: 1

number:
  - platform: "tuya"
    name: "Timer"
    id: timer
    icon: mdi:timer
    unit_of_measurement: min
    mode: box
    number_datapoint: 8
    min_value: 0
    max_value: 120
    step: 1

switch:
  - platform: "tuya"
    name: "Child Lock"
    id: childlock
    icon: mdi:lock
    switch_datapoint: 6
```
I made a feature request for someone to hopefully solve this.
https://github.com/esphome/feature-requests/issues/2849
