### ISSUE TITLE
IR Remote Climate - mitsubishi hvac not processing IR sent

### ISSUE THREAD

**Issue by anna111134** [esphome/issues#6049]
### The problem

I have tried using the mitsubishi component under IR remote climate however none IR signals are accepted/received by the hvac system. In contrast, the HeatpumpIR library (almost) works perfectly. The only issue is the off command puts it into some hibernation mode rather than off off like the remote does.

Looking at the mitsubishi.cpp file I believe it might not be quite mapped? https://github.com/esphome/esphome/blob/dev/esphome/components/mitsubishi/mitsubishi.cpp

### Which version of ESPHome has the issue?

latest

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

latest

### What platform are you using?

ESP8266

### Board

Athom AR01

### Component causing the issue

IR Remote Climate

### Example YAML snippet

```yaml
climate:
  - platform: mitsubishi
    name: "Heatpump"
    set_fan_mode: "quiet_4levels"
    supports_dry: "true"
    supports_fan_only: "true"
    receiver_id: "ac_receiver"
```

### Anything in the logs that might be useful for us?

```txt
An example of the payload received (via a different tasmota device): {"IrSend":{"Protocol":"MITSUBISHI_HEAVY_152","Bits":152,"Data":"0xAD513CE51A0CF308F700FFC03FC83700FF807F","Repeat":0,"IRHVAC":{"Vendor":"MITSUBISHI_HEAVY_152","Model":-1,"Command":"Control","Mode":"Heat","Power":"On","Celsius":"On","Temp":25,"FanSpeed":"Auto","SwingV":"Off","SwingH":"Off","Quiet":"Off","Turbo":"Off","Econo":"Off","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":-1,"iFeel":"Off","SensorTemp":null}}}
```
