### ISSUE TITLE
M5stack POESP32

### ISSUE THREAD

**Issue by BeFygo** [esphome/issues#6054]
### The problem

Defining   "framework:    type: esp-idf " with the POESP32 makes it not boot on POE

When the "framework" is not defined the device boots on POE just fine but then doesnt work as BLEProxy (config just fine but nog connections)

### Which version of ESPHome has the issue?

2024.6.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.6.1

### What platform are you using?

ESP32

### Board

M5STACK POESP32

### Example YAML snippet

```yaml
esphome:
  name: m5stack-bleproxy
  friendly_name: M5Stack BLEproxy

esp32:
  board: m5stack-core-esp32
#  framework:
#    type: esp-idf
    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  - platform: esphome
    password: "***"


ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  power_pin: GPIO5  
  phy_addr: 1    

switch:
  - platform: gpio
    id: gate_relay16
    pin: GPIO16
    name: "Gate Switch 16"

#  - platform: gpio
#    id: gate_relay17
#    pin: GPIO17
#    name: "Gate Switch 17"  

esp32_ble_tracker:
  scan_parameters:
  #  interval: 1100ms
  #  window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
```
