### ISSUE TITLE
Uptime Sensor with type timestamp does not work when using MQTT instead of API

### ISSUE THREAD

**Issue by gribber** [esphome/issues#6065]
### The problem

The state of the entity will be Unknown when enabling the new timestamp type for the uptime sensor for all devices that using mqtt instead of api

The reason for this happening is that Home Assistant is expecting another time format, the device_class is set to timestamp and according to:
https://developers.home-assistant.io/docs/core/entity/sensor/
"Timestamp. Requires native_value to return a Python datetime.datetime object, with time zone information, or None."
The format given is unix timestamp

### Which version of ESPHome has the issue?

2024.7.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.7.3

### What platform are you using?

ESP8266

### Board

wemos d1 mini

### Component causing the issue

Uptime sensor

### Example YAML snippet

```yaml
mqtt:
  - <mqtt settings..>

sensor:
- platform: uptime
  id: sensor_last_boot_time
  name: "Last boot time"
  type: timestamp
  entity_category: diagnostic
```

### Anything in the logs that might be useful for us?

```txt
Home Assistant logs:
WARNING (MainThread) [homeassistant.components.mqtt.sensor] Invalid state message '1721497216' from 'esphome/uptimetest/sensor/last_boot_time/state'
```

### Additional information

states.sensor.uptimetest_last_boot_time:
<template TemplateState(<state sensor.uptimetest_last_boot_time=unknown; device_class=timestamp, icon=mdi:timer-outline, friendly_name=uptimetest Last boot time @ 2024-07-20T21:10:57.284983+02:00>)>

**Comment by elratt0r** [comment]
Workaround:

```
time:
  - platform: sntp
    id: hatime
    servers:
      - ...
    on_time_sync: 
      then:
        - component.update: last_restart

text_sensor:
  - platform: template
    name: "Last Restart Time"
    id: last_restart
    update_interval: never
    device_class: timestamp
    icon: "mdi:timer-outline"
    entity_category: "diagnostic"
    lambda: |-
      return id(hatime).utcnow().strftime("%Y-%m-%dT%H:%M:%S+00:00");
```

Looking into extending the ha mqtt component to also accept utc-timestamp, as adding datetime to the sensor component here would break the sensor(float)/text_sensor(string) continuity.
Maybe trying to decode the payload with `dt_util.utc_from_timestamp()` [here](https://github.com/home-assistant/core/blob/2edcda47b04f2760ca88156274c03701c4fbc794/homeassistant/components/mqtt/sensor.py#L293) could be a solution. That's how the esphome component interprets the timestamp for sensor.
