### ISSUE TITLE
Extremely long (1000ms) timeout stalling loop with SHT4X component when sensor is NOT Connected

### ISSUE THREAD

**Issue by fpovoski** [esphome/issues#6070]
### The problem

Extremely long (1000ms) timeout stalling loop with SHT4X component when sensor is NOT Connected. This simply should not be occurring. Sensor should be marked offline at boot without attempts to access device that is not connected.

yaml:
i2c:
id: bus_a
  sda: GPIO21
  scl: GPIO22
  scan: false
  frequency: 100khz
  timeout: 10ms
id: bus_b
  sda: GPIO16
  scl: GPIO17
  scan: False
  frequency: 800khz
  timeout: 10ms

sensor: 
platform: sht4x
  i2c_id: bus_a
  address: 0x44
  heater_max_duty: 0.0
  heater_power: "Low"
  heater_time: "Short"
  update_interval: 2s
  temperature:
    name: ${fdevicename} Temperature 5
  humidity:
    name: ${fdevicename} Humidity 5

debug:
[05:42:33][D][sht4x:080]: Sensor read failed
[05:42:33][W][component:237]: Component sht4x.sensor took a long time for an operation (1007 ms).
[05:42:33][W][component:238]: Components should block for at most 30 ms.
[05:42:33][D][sensor:094]: 'AVfan1 Uptime': Sending state 20.88600 s with 0 decimals of accuracy
[05:42:35][D][sht4x:080]: Sensor read failed
[05:42:35][W][component:237]: Component sht4x.sensor took a long time for an operation (1008 ms).
[05:42:35][W][component:238]: Components should block for at most 30 ms.
[05:42:37][D][sht4x:080]: Sensor read failed
[05:42:37][W][component:237]: Component sht4x.sensor took a long time for an operation (1007 ms).
[05:42:37][W][component:238]: Components should block for at most 30 ms.
[05:42:39][D][sht4x:080]: Sensor read failed
[05:42:39][W][component:237]: Component sht4x.sensor took a long time for an operation (1007 ms).
[05:42:39][W][component:238]: Components should block for at most 30 ms.

Same behavior with heater on or off
Same behavior on ESP32 and ESP32-S3 

![SHT4X_issue](https://github.com/user-attachments/assets/8406a2cc-2bf7-4ae5-8381-ea625398e782)

### Which version of ESPHome has the issue?

Release 2024.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Release 2024.7.8

### What platform are you using?

ESP32

### Board

Espressif ESP32-S3-DevKitM-1, ESP32andmore.com GrowMore Hub, ESP32andmore.com ECB

### Component causing the issue

SHT40X

### Example YAML snippet

```yaml
i2c:
id: bus_a
  sda: GPIO21
  scl: GPIO22
  scan: false
  frequency: 100khz
  timeout: 10ms
id: bus_b
  sda: GPIO16
  scl: GPIO17
  scan: False
  frequency: 800khz
  timeout: 10ms

sensor: 
platform: sht4x
  i2c_id: bus_a
  address: 0x44
  heater_max_duty: 0.0
  heater_power: "Low"
  heater_time: "Short"
  update_interval: 2s
  temperature:
    name: ${fdevicename} Temperature 5
  humidity:
    name: ${fdevicename} Humidity 5
```

### Anything in the logs that might be useful for us?

```txt
[05:42:33][D][sht4x:080]: Sensor read failed
[05:42:33][W][component:237]: Component sht4x.sensor took a long time for an operation (1007 ms).
[05:42:33][W][component:238]: Components should block for at most 30 ms.
[05:42:33][D][sensor:094]: 'AVfan1 Uptime': Sending state 20.88600 s with 0 decimals of accuracy
[05:42:35][D][sht4x:080]: Sensor read failed
[05:42:35][W][component:237]: Component sht4x.sensor took a long time for an operation (1008 ms).
[05:42:35][W][component:238]: Components should block for at most 30 ms.
[05:42:37][D][sht4x:080]: Sensor read failed
[05:42:37][W][component:237]: Component sht4x.sensor took a long time for an operation (1007 ms).
[05:42:37][W][component:238]: Components should block for at most 30 ms.
[05:42:39][D][sht4x:080]: Sensor read failed
[05:42:39][W][component:237]: Component sht4x.sensor took a long time for an operation (1007 ms).
[05:42:39][W][component:238]: Components should block for at most 30 ms.
```

### Additional information

![SHT4X_issue](https://github.com/user-attachments/assets/a54970d6-7cd4-486d-8dcb-9344860e8bb7)
 
What I love the most is: UNTESTED RELEASES OF ESPHOME
