### ISSUE TITLE
Circular dependency detected in lambda 

### ISSUE THREAD

**Issue by ayasystems** [esphome/issues#6073]
### The problem

I can not access to Energy value from lamda function 

### Which version of ESPHome has the issue?

2024.5.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

pzemac / mqtt

### Example YAML snippet

```yaml
esphome:
  name: pzem-jardin 
  name_add_mac_suffix: False
  comment: ES8266_4M PZEM Jardín

esp8266:
  board: nodemcuv2
  framework:
   version: recommended

# Enable logging
logger:
  level: ERROR
  logs:
    mqtt.component: ERROR
    mqtt.client: ERROR

mqtt:
  broker: mqtt.xxxxxx.com
  username: xxxx
  password: xxxxx
  id: pzemJardin
  discovery: false
  topic_prefix: esphome/pzemJardin
ota:
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
web_server:
  port: 80
wifi:
  ssid: xxxxxxxxxxxxx
  password: xxxxxxxxxxxxx
  domain: ".xxxxxxxxxxx.com"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "pzem-jardin_Hotspot"
    password: "xxxxxxxxxxxxxxx"

captive_portal:

# Example configuration entry
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

modbus:


sensor:
  
  - platform: pzemac           
    energy:
      name: "PZEM-004T V3 Energy"
      id: "energy"    
      filters:
        - round: 0  
        - or:
          - throttle: 45s
          - delta: 1      
                          
    power:
      name: "PZEM-004T V3 Power"
      id: "power"
      filters:
        - round: 0  
        - or:
          - throttle: 45s
          - delta: 10    
      on_value:
        then:
        - mqtt.publish_json:
            topic: domoticz/in
            payload: |-
              char buffer[256]; 
              root["idx"] = 283; 
              sprintf(buffer,  "%1.1f;%1.0f", id(power).state, id(energy).state);
              root["svalue"] = buffer; 
              root["parse"] = false;
              root["nvalue"] = 0;                                     
    current:
      name: "PZEM-004T V3 Current"  
      filters:
        - round: 1  
        - or:
          - throttle: 45s
          - delta: 0.5     
                   
    update_interval: 1s
```

### Additional information

If i put on_value section into Energy section code is compiling without problem, only brakes into Energy section

It is working fine:

 ```
- platform: pzemac           
    energy:
      name: "PZEM-004T V3 Energy"
      id: "energy"    
      filters:
        - round: 0  
        - or:
          - throttle: 45s
          - delta: 1      
      on_value:
        then:
        - mqtt.publish_json:
            topic: domoticz/in
            payload: |-
              char buffer[256]; 
              root["idx"] = 283; 
              sprintf(buffer,  "%1.1f;%1.0f", id(power).state, id(energy).state);
              root["svalue"] = buffer; 
              root["parse"] = false;
              root["nvalue"] = 0;                         
    power:
      name: "PZEM-004T V3 Power"
      id: "power"
      filters:
        - round: 0  
        - or:
          - throttle: 45s
          - delta: 10    
                               
    current:
      name: "PZEM-004T V3 Current"  
      filters:
        - round: 1  
        - or:
          - throttle: 45s
          - delta: 0.5     
```
