### ISSUE TITLE
SHT4x: constantly runs heater, even when dutycycle set to 0

### ISSUE THREAD

**Issue by RagingRoosevelt** [esphome/issues#6078]
### The problem

I have a SHT-41 that starts off reading the expected ambient temp, then over time increases up to around 90F where it remains until I pull the plug.  I've measured it with a laser thermometer and confirmed that the readings are valid.  It seems like it's running the heater full-tilt.  

### Which version of ESPHome has the issue?

2024.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.1

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1

### Component causing the issue

SHT4X

### Example YAML snippet

```yaml
sensor:
  - platform: sht4x
    i2c_id: i2c_bus_0
    address: 0x44
    temperature:
      name: "SHT41 Temperature"
    humidity:
      name: "SHT41 Relative Humidity"
    heater_time: Short
    heater_max_duty: 0.0
    update_interval: 15s
```

### Additional information

I tried removing different combinations of the `heater_time` and `heater_max_duty` keys (remove one, the other, both) and it didn't help.
