### ISSUE TITLE
Prevent servo from returning to idle_level at boot

### ISSUE THREAD

**Issue by hawkeye217** [esphome/issues#609]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

D1-mini
**Affected component:**

https://esphome.io/components/servo.html

**Description of problem:**
I'm using the `servo` component to control some blinds I've attached an MG-995 servo to. According to the docs, on startup the servo returns to the `idle_level`, and this causes the servo to move the blinds slightly and stay energized, which is unfortunate if the device happens to lose the api or wifi connection and restarts.  

I added an `on_boot` directive to the `esphome:` section and experimented a bit with the priority in order to detach the servo.  This mostly works, but there still is a slight movement of the servo on boot.  

Is there any way to prevent the servo from returning to the `idle_level` state on boot altogether?

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: lrblinds
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 400
    then:
      - servo.detach: my_servo  

wifi:
  ssid: "myssid"
  password: "mypassword"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

servo:
  - id: my_servo
    output: pwm_output

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D3
    frequency: 50 Hz
    
cover:
  - platform: template
    name: "Living Room Blinds"
    optimistic: true
    open_action:
      - servo.write:
          id: my_servo
          level: -34%
      - delay: 750ms
      - servo.detach: my_servo
    close_action:
      - servo.write:
          id: my_servo
          level: 100.0%
      - delay: 1000ms
      - servo.detach: my_servo          
    stop_action:
      - servo.detach: my_servo

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
