### ISSUE TITLE
Unable to install ESPHome haier configuration

### ISSUE THREAD

**Issue by bart1604** [esphome/issues#6090]
### The problem

I'm new to ESPHome, so there is a good chance I'm doing something wrong here.

I've installed ESPHome and want to push the configuration wirelessly. For now just the default configuration is used given by the haier climate ESPHome page itself.

But for some reason i get an error when trying to install the configuration

### Which version of ESPHome has the issue?

2024.7.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.7.3

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Example YAML snippet

```yaml
substitutions:
  name: esphome-web-ee5b09
  friendly_name: ESPHome Haier Zolder

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

# Example configuration entry
climate:
  - platform: haier
    id: haier_ac
    protocol: hOn
    name: Haier AC
    uart_id: ac_port
    wifi_signal: true
    beeper: true
    display: true
    visual:
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    supported_modes:
    - 'OFF'
    - HEAT_COOL
    - COOL
    - HEAT
    - DRY
    - FAN_ONLY
    supported_swing_modes:
    - 'OFF'
    - VERTICAL
    - HORIZONTAL
    - BOTH
  supported_presets:
    - AWAY
    - ECO
    - BOOST
    - SLEEP
  on_alarm_start:
    then:
      - logger.log:
          level: WARN
          format: "Alarm activated. Code: %d. Message: \"%s\""
          args: [ code, message]
  on_alarm_end:
    then:
      - logger.log:
          level: INFO
          format: "Alarm deactivated. Code: %d. Message: \"%s\""
          args: [ code, message]
  on_status_message:
    then:
      - logger.log:
          level: INFO
          format: "New status message received, size=%d, subcmd=%02X%02X"
          args: [ 'data_size', 'data[0]', 'data[1]' ]
```

### Anything in the logs that might be useful for us?

```txt
The logs when trying to install the config:



INFO ESPHome 2024.7.2
INFO Reading configuration /config/esphome/esphome-web-ee5b09.yaml...
ERROR Error while reading config: Invalid YAML syntax:

while parsing a block collection
  in "/config/esphome/esphome-web-ee5b09.yaml", line 47, column 3
expected <block end>, but found '?'
  in "/config/esphome/esphome-web-ee5b09.yaml", line 71, column 3
```
