### ISSUE TITLE
invert_position_report can not be found for Tuya cover

### ISSUE THREAD

**Issue by SamGeens** [esphome/issues#6112]
### The problem

invert_position_report configuration variable can't be set due to `Failed config` message.

![image](https://github.com/user-attachments/assets/48ec0800-2f0e-4615-9ed2-c0a3a95bffe5)

It is however available in the [documentation](https://github.com/esphome/esphome-docs/blob/current/components/cover/tuya.rst):
![image](https://github.com/user-attachments/assets/92a84f98-fc01-4602-8725-284418b63418)

And also in [code](https://github.com/esphome/esphome/tree/4a7570770b0b36cfc2495ad3795d4ae3c7df66bb/esphome/components/tuya/cover):
![Uploading image.png…]()

### Which version of ESPHome has the issue?

2024.4.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.4

### What platform are you using?

ESP8266

### Example YAML snippet

```
# Make sure logging is not using the serial port
logger:
  baud_rate: 0

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:
  id: "tuyadevice"

# Create a cover using the tuya datapoint
cover:
  - platform: "tuya"
    name: "Position"
    device_class: shutter
    control_datapoint: 1
    position_datapoint: 2
    min_value: 0
    max_value: 100
    invert_position_report: True
```
