### ISSUE TITLE
spaces are translated to underscores in project name

### ISSUE THREAD

**Issue by 532910** [esphome/issues#6115]
### The problem

I'd like to have spaces in author and  project names, like here:
![image](https://github.com/user-attachments/assets/f3d706ae-a3b8-4a93-b628-d09e13f1d5f6)

but instead of spaces I got underscores:
```
esphome:
  project:
    name: 'Shelly.Plus Plug S'
    version: '2.0'
```
![image](https://github.com/user-attachments/assets/e39baca2-bb2b-4295-afa7-27bb96782f6f)

### Which version of ESPHome has the issue?

2024.7.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32
