### ISSUE TITLE
The object ID cannot be generated correctly when the entity object name contains multi-byte characters

### ISSUE THREAD

**Issue by HessianZ** [esphome/issues#6116]
### The problem

The object ID cannot be generated correctly when the entity object name contains multi-byte characters

And sensor entity id property is ignored in object id generate logic in `esphome/cpp_helpers.py -- setup_entity(var, config)`

```python
async def setup_entity(var, config):
    """Set up generic properties of an Entity"""
    add(var.set_name(config[CONF_NAME]))
    if not config[CONF_NAME]:
        add(var.set_object_id(sanitize(snake_case(CORE.friendly_name))))
    else:
        add(var.set_object_id(sanitize(snake_case(config[CONF_NAME]))))
    add(var.set_disabled_by_default(config[CONF_DISABLED_BY_DEFAULT]))
    if CONF_INTERNAL in config:
        add(var.set_internal(config[CONF_INTERNAL]))
    if CONF_ICON in config:
        add(var.set_icon(config[CONF_ICON]))
    if CONF_ENTITY_CATEGORY in config:
        add(var.set_entity_category(config[CONF_ENTITY_CATEGORY]))
```

For example:
```c
// sensor.aht10:
  //   platform: aht10
  //   variant: AHT20
  //   i2c_id: bus_a
  //   update_interval: 60s
  //   id: sensor_aht20
  //   temperature:
  //     name: 户外温度
  //     id: aht20_temp
  //     accuracy_decimals: 1
  //     filters:
  //     - filter_out: 0.0
  //       type_id: sensor_filteroutvaluefilter_id
  //     - median:
  //         window_size: 3
  //         send_every: 3
  //         send_first_at: 1
  //       type_id: sensor_medianfilter_id
  //     disabled_by_default: false
  //     force_update: false
  //     unit_of_measurement: °C
  //     device_class: temperature
  //     state_class: measurement
  //   humidity:
  //     name: 户外湿度
  //     id: aht20_humi
  //     accuracy_decimals: 1
  //     filters:
  //     - filter_out: 0.0
  //       type_id: sensor_filteroutvaluefilter_id_2
  //     - median:
  //         window_size: 3
  //         send_every: 3
  //         send_first_at: 1
  //       type_id: sensor_medianfilter_id_2
  //     disabled_by_default: false
  //     force_update: false
  //     unit_of_measurement: '%'
  //     device_class: humidity
  //     state_class: measurement
  //   address: 0x38
  sensor_aht20 = new aht10::AHT10Component();
  sensor_aht20->set_update_interval(60000);
  sensor_aht20->set_component_source("aht10.sensor");
  App.register_component(sensor_aht20);
  sensor_aht20->set_i2c_bus(bus_a);
  sensor_aht20->set_i2c_address(0x38);
  sensor_aht20->set_variant(aht10::AHT20);
  aht20_temp = new sensor::Sensor();
  App.register_sensor(aht20_temp);
  aht20_temp->set_name("\346\210\267\345\244\226\346\270\251\345\272\246");
  aht20_temp->set_object_id("____");
  aht20_temp->set_disabled_by_default(false);
  aht20_temp->set_device_class("temperature");
  aht20_temp->set_state_class(sensor::STATE_CLASS_MEASUREMENT);
  aht20_temp->set_unit_of_measurement("\302\260C");
  aht20_temp->set_accuracy_decimals(1);
  aht20_temp->set_force_update(false);
  sensor_filteroutvaluefilter_id = new sensor::FilterOutValueFilter(0.0f);
  sensor_medianfilter_id = new sensor::MedianFilter(3, 3, 1);
  aht20_temp->set_filters({sensor_filteroutvaluefilter_id, sensor_medianfilter_id});
  sensor_aht20->set_temperature_sensor(aht20_temp);
  aht20_humi = new sensor::Sensor();
  App.register_sensor(aht20_humi);
  aht20_humi->set_name("\346\210\267\345\244\226\346\271\277\345\272\246");
  aht20_humi->set_object_id("____");
  aht20_humi->set_disabled_by_default(false);
  aht20_humi->set_device_class("humidity");
  aht20_humi->set_state_class(sensor::STATE_CLASS_MEASUREMENT);
  aht20_humi->set_unit_of_measurement("%");
  aht20_humi->set_accuracy_decimals(1);
  aht20_humi->set_force_update(false);
  sensor_filteroutvaluefilter_id_2 = new sensor::FilterOutValueFilter(0.0f);
  sensor_medianfilter_id_2 = new sensor::MedianFilter(3, 3, 1);
  aht20_humi->set_filters({sensor_filteroutvaluefilter_id_2, sensor_medianfilter_id_2});
  sensor_aht20->set_humidity_sensor(aht20_humi);
```

generated the object

### Which version of ESPHome has the issue?

2024.7.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
esphome:
  name: human-sensor-2
  friendly_name: 人体传感器2
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "jt4qgONd0oLvyWQfHPhCNM61S6cLlnzyq6U5c+VpJD8="
ota:
  - platform: esphome
    password: "gmKBpwO4HviwRQZ0DN9s"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".lan"
  use_address: "human-sensor-2.lan"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "humen-sensor-2"
    password: "esphome.hessian.me"

captive_portal:


switch:
  - platform: gpio
    name: "BuiltinLED"
    pin: 10
    id: sw_builtin_led
  - platform: gpio
    name: "LedStrip"
    pin: 2
    id: sw_led_strip

binary_sensor:
  - platform: gpio
    pin: 3
    name: "MotionDetective"
    device_class: motion

i2c:
  sda: GPIO7
  scl: GPIO5
  scan: true
  id: bus_a

sensor:
  - platform: aht10
    variant: AHT20
    i2c_id: bus_a
    update_interval: 60s
    id: sensor_aht20
    temperature:
      name: "户外温度"
      id: aht20_temp
      accuracy_decimals: 1
      filters:
      - filter_out: 0.0
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 1
    humidity:
      name: "户外湿度"
      id: aht20_humi
      accuracy_decimals: 1
      filters:
      - filter_out: 0.0
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 1
  - platform: bmp280
    i2c_id: bus_a
    address: 0x77
    update_interval: 60s
    id: sensor_bmp280
    pressure:
      name: "大气压"
      id: bmp280_pressure
    temperature:
      name: "bmp280温度"
      id: bmp280_temp
      accuracy_decimals: 1
      filters:
      - filter_out: 0.0
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 1
```

### Anything in the logs that might be useful for us?

```txt
homeassistant  | 2024-08-03 10:49:29.376 ERROR (MainThread) [homeassistant.components.sensor] Platform esphome does not generate unique IDs. ID human-sensor-2sensor____ is already used by sensor.human_sensor_2 - ignoring sensor.human-sensor-2_____
```
