### ISSUE TITLE
2024.7.3 Broke Platform Dallas_temp

### ISSUE THREAD

**Issue by ESP32andmore** [esphome/issues#6119]
### The problem

Release 2024.7.3, Dallas_temp on ESP32 gets "Scratch pad checksum invalid!" Works fine in 2024.6.6

13:55:05 | [W] | [component:170] | Component dallas_temp.sensor cleared Warning flag
13:55:05 | [W] | [dallas.temp.sensor:139] | 'AVfan1 Temperature 3' - Scratch pad checksum invalid!
13:55:05 | [W] | [component:157] | Component dallas_temp.sensor set Warning flag: scratch pad checksum invalid
13:55:05 | [W] | [dallas.temp.sensor:139] | 'AVfan1 Temperature 1' - Scratch pad checksum invalid!
13:55:05 | [W] | [component:157] | Component dallas_temp.sensor set Warning flag: scratch pad checksum invalid
13:55:05 | [W] | [dallas.temp.sensor:139] | 'AVfan1 Temperature 2' - Scratch pad checksum invalid!
13:55:05 | [W] | [component:157] | Component dallas_temp.sensor set Warning flag: scratch pad checksum invalid

### Which version of ESPHome has the issue?

2024.7.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

No relevant but latest

### What platform are you using?

ESP32

### Board

ESP32andmore.com ECB

### Component causing the issue

One-wire: Dallas_temp

### Example YAML snippet

```yaml
- platform: dallas_temp
    address: ${dallasaddress1}
    update_interval: 2s
    #index: 0
    id: temp1
    filters:
      - filter_out: NaN
      - offset: 0.0
      #- lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°C"
    name: ${fdevicename} Temperature 1
```

### Anything in the logs that might be useful for us?

```txt
13:55:05 | [W] | [component:170] | Component dallas_temp.sensor cleared Warning flag
13:55:05 | [W] | [dallas.temp.sensor:139] | 'AVfan1 Temperature 3' - Scratch pad checksum invalid!
13:55:05 | [W] | [component:157] | Component dallas_temp.sensor set Warning flag: scratch pad checksum invalid
13:55:05 | [W] | [dallas.temp.sensor:139] | 'AVfan1 Temperature 1' - Scratch pad checksum invalid!
13:55:05 | [W] | [component:157] | Component dallas_temp.sensor set Warning flag: scratch pad checksum invalid
13:55:05 | [W] | [dallas.temp.sensor:139] | 'AVfan1 Temperature 2' - Scratch pad checksum invalid!
13:55:05 | [W] | [component:157] | Component dallas_temp.sensor set Warning flag: scratch pad checksum invalid
```

**Comment by ssieb** [comment]
Nothing changed in .7.x.  What was the last version that worked?
What is in the logs for the `one_wire:` section?

**Comment by ESP32andmore** [comment]
Samuel,
Attached are two logs from same board and sensors programmed with .6.x and .7.x back to back
.7.x , the one-wire component finds no devices:

[08:42:06][C][gpio.one_wire:020]: GPIO 1-wire bus:
[08:42:06][C][gpio.one_wire:021]:   Pin: GPIO27
[08:42:06][W][gpio.one_wire:078]:   Found no devices!

.6.x, does find the sensors:

[08:59:57][C][gpio.one_wire:020]: GPIO 1-wire bus:
[08:59:57][C][gpio.one_wire:021]:   Pin: GPIO27
[08:59:57][C][gpio.one_wire:080]:   Found devices:
[08:59:57][C][gpio.one_wire:082]:     0x8b3ca8f64935b228 (DS18B20)
[08:59:57][C][gpio.one_wire:082]:     0x783c0af6490d3628 (DS18B20)
[08:59:57][C][gpio.one_wire:082]:     0xc13c01f09642c928 (DS18B20)
[08:59:57][C][gpio.one_wire:082]:     0x043c6ef649772f28 (DS18B20)







________________________________

**Comment by ssieb** [comment]
I've double-checked and there were no changes that would directly affect this between those versions.
How are the sensors wired, including lengths?
I've done some tweaking of the timings, so you can try this:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/ssieb/esphome
      ref: onewire
    components: [ one_wire, gpio ]
    refresh: 1min
```
