### ISSUE TITLE
esp32_ble_tracker set_scan_interval doesn't change the interval immediately

### ISSUE THREAD

**Issue by westenberg** [esphome/issues#612]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32

**Affected component:**
https://esphome.io/components/esp32_ble_tracker.html

**Description of problem:**
I use an api service to set the set_scan_interval on the esp32_ble_tracker so I can change the polling interval when e.g. motion is detected. Changing set_scan_interval works but it looks like it finishes the current interval first before it sets the new interval. This makes the function unusable for dynamic updates because when setting a 24h interval and going back to 5s it needs to finish the 24h interval first.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: zolder
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: ""
  password: ""

logger:

api:
  password: ""
  services:
    - service: ble_start_scan
      then:
        - lambda: |-
            id(ble_tracker).set_scan_interval(10);
    - service: ble_stop_scan
      then:
        - lambda: |-
            id(ble_tracker).set_scan_interval(86400);

ota:
  password: ""
  
esp32_ble_tracker:
  id: ble_tracker
  scan_interval: 60s
  
binary_sensor:
  - platform: ble_presence
    mac_address: 12:34:56:78:90:AB
    name: Device

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I think the solution would be to cancel the previous interval immediately and set the new interval.
