### ISSUE TITLE
Sonoff RF Bridge R2 V2.2

### ISSUE THREAD

**Issue by Blackspell01** [esphome/issues#6121]
### The problem

I used this [method ](https://community.home-assistant.io/t/new-sonoff-rf-bridge-board-need-flashing-help/344326/16) to bypass the secondary chip on the Sonoff device. My goal is to migrate from a wemos d1 mini to the rf bridge. I have already decoded the rf code for my blinds and they work on the esp 8266. I copied the yaml code and created a new project in esphome (see example code below) but unfortunately the rf bridge fails to control my blinds. 

### Which version of ESPHome has the issue?

-

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Sonoff RF Bridge

### Example YAML snippet

```yaml
esphome:
  name: sonoff-rf
  platform: ESP8266
  board: esp8285

api:
logger: 
ota:
  platform: esphome
web_server:
wifi:
  ssid: "****"
  password: "****"
  ap: {}
captive_portal:

status_led:
  pin:
    number: GPIO13
    inverted: yes

remote_transmitter:
  pin: GPIO5
  carrier_duty_percent: 100%


cover:
  - platform: time_based
    device_class: blind
    name: "Rollo 3"
    has_built_in_endstop: true
    icon: "mdi:window-shutter"
    open_duration: 26s
    open_action:
      - switch.turn_on: rollo3_up
    close_action:
      - switch.turn_on: rollo3_down
    close_duration: 26s


switch:
  - platform: template
    name: Rollo 3 up
    id: rollo3_up
    icon: "mdi:window-shutter-open"
    entity_category: config
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [5890,-1780,890,-890,890,-890,1780,-1780,1780,-890,890,-1780,890,-890,890,-890,890,-890,890,-890,890,-890,6780,-1780,1780,-890,890,-890,890,-1780,890,-890,1780,-890,890,-890,5890,-890,890,-1780,1780,-890,890,-890,890,-890,890,-890,890,-890,890,-890,5000]
  - platform: template
    name: Rollo 3 down
    id: rollo3_down
    icon: "mdi:window-shutter-open"
    entity_category: config
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [5890,-1780,890,-890,890,-890,1780,-1780,1780,-890,890,-1780,890,-890,890,-890,890,-890,890,-890,1780,-890,5890,-1780,1780,-890,890,-890,890,-1780,890,-890,1780,-890,890,-890,5890,-890,890,-1780,1780,-890,890,-890,890,-890,890,-890,890,-890,890,-890,5000]
```
