### ISSUE TITLE
manual_ip setting prevents IPv6 on wired Ethernet

### ISSUE THREAD

**Issue by dwmw2** [esphome/issues#6126]
### The problem

When specifying Legacy IP addresses with `manual_ip`, no IPv6 address is picked up.

This works on wifi but not wired Ethernet.

### Which version of ESPHome has the issue?

dev

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32-IDF

### Board

Olimex ESP32-Gateway

### Component causing the issue

Ethernet

### Example YAML snippet

```yaml
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  manual_ip:
        static_ip: 172.31.31.238
        gateway: 172.31.31.1
        subnet: 255.255.255.0
        dns1: 172.31.31.1
```

### Anything in the logs that might be useful for us?

```txt
No IPv6 address is detected.
```

### Additional information

I think this would *probably* fix it for Ethernet but I'm wary of testing because I don't have easy serial access to this unit to fix it.

```
--- a/esphome/components/ethernet/ethernet_component.cpp
+++ b/esphome/components/ethernet/ethernet_component.cpp
@@ -472,13 +472,13 @@ void EthernetComponent::start_connect_() {
     if (err != ESP_ERR_ESP_NETIF_DHCP_ALREADY_STARTED) {
       ESPHL_ERROR_CHECK(err, "DHCPC start error");
     }
+  }
 #if USE_NETWORK_IPV6
-    err = esp_netif_create_ip6_linklocal(this->eth_netif_);
-    if (err != ESP_OK) {
-      ESPHL_ERROR_CHECK(err, "Enable IPv6 link local failed");
-    }
-#endif /* USE_NETWORK_IPV6 */
+  err = esp_netif_create_ip6_linklocal(this->eth_netif_);
+  if (err != ESP_OK) {
+    ESPHL_ERROR_CHECK(err, "Enable IPv6 link local failed");
   }
+#endif /* USE_NETWORK_IPV6 */
 
   this->connect_begin_ = millis();
   this->status_set_warning();

```
