### ISSUE TITLE
Invalid color mode 'cwww'

### ISSUE THREAD

**Issue by robercy** [esphome/issues#6131]
### The problem

Warning messages in log file.

### Which version of ESPHome has the issue?

all

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

all

### What platform are you using?

ESP8266

### Board

sonoff

### Example YAML snippet

```yaml
.
.
.
output:
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO0
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO3
#
light:
  - platform: cwww
    name: Output
    id: controller
    icon: $device_icon
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    state_topic: $prefix/$device_name/out
    command_topic: $prefix/$device_name/cmd/out
    retain: true
    effects:
      - random:
      - random:
          name: "My Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
#
.
.
.
```

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.mqtt.light.schema_json
Source: components/mqtt/light/schema_json.py:365
integration: MQTT (documentation, issues)
First occurred: 09:12:29 (5 occurrences)
Last logged: 09:12:29

Invalid color mode 'cwww' received for entity light.bedroom_mirror_output
Invalid color mode 'cwww' received for entity light.dining_room_stripled_inner_output
Invalid color mode 'cwww' received for entity light.dining_room_stripled_outer_output
Invalid color mode 'cwww' received for entity light.home_theater_stripled_output_cwww
Invalid color mode 'cwww' received for entity light.living_room_stripled_output
```
