### ISSUE TITLE
thermostat not sending target temperature when heating or cooling is selected, which is required for google assistant.

### ISSUE THREAD

**Issue by spike11302000** [esphome/issues#6134]
### The problem

I'm having a issue trying esphome working with google assistant. when specify setting the mode to heating or cooling, google home does not get the current temperature set point. I submitted a issues on the home assistant github and they told me it because the thermostat isn't sending target temperature when in those modes. setting the mode to heat/cool works though.

### Which version of ESPHome has the issue?

2024.7.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.8.0

### What platform are you using?

ESP32

### Component causing the issue

climate/thermostat

### Example YAML snippet

```yaml
climate:
  - platform: thermostat
    name: "Climate"
    id: "my_climate"
    sensor: "dht_temp"
    min_idle_time: 6s

    idle_action: 
      - switch.turn_off: heat_output
      - switch.turn_off: cool_output
      - switch.turn_off: fan_output
  
    min_heating_off_time: 6s
    min_heating_run_time: 6s
    heat_action: 
      - switch.turn_on: heat_output
      - switch.turn_off: cool_output
      - switch.turn_off: fan_output

    min_cooling_off_time: 6s
    min_cooling_run_time: 6s
    cool_action: 
      - switch.turn_on: cool_output
      - switch.turn_off: heat_output
      - switch.turn_off: fan_output
    
    min_fanning_off_time: 0s
    min_fanning_run_time: 0s
    fan_only_action: 
      - switch.turn_on: fan_output
      - switch.turn_off: heat_output
      - switch.turn_off: cool_output
    on_state: 
      - component.update: "my_display"
```

### Additional information

when set to "heat/cool"
![Screenshot_20240808-001720](https://github.com/user-attachments/assets/7375b4c4-f51f-4608-b574-9f8e631e9f0f)

when set to either cool/heat
![Screenshot_20240808-001709](https://github.com/user-attachments/assets/ad05f72f-9a55-4d8a-b88b-61800c43e3c9)

Home Assistant entity state
![image](https://github.com/user-attachments/assets/680f14e1-732e-4ec3-9bf1-0ff7afab87f0)

Issue posted on home assistant
https://github.com/home-assistant/core/issues/123330
