### ISSUE TITLE
 Guru Meditation Error when using sprinkler controller with valves without pump_switch_id.

### ISSUE THREAD

**Issue by hetii** [esphome/issues#6148]
### The problem

Hi.
When I have a mix of valves with and  without  pump_switch_id, esp32 crash when switching zones.
Error: EXCVADDR: 0x00000010 indicate null pointer to structure.

```
    sprinkler:
      - id: mysprinklerctrl
        valve_open_delay: 1s
        next_prev_ignore_disabled: true
        pump_switch_off_during_valve_open_delay: false
      ...
      - valve_switch_id: valve_switch_12
        pump_switch_id: pump_switch
        ...
      - valve_switch_id: valve_over_pressure
        # pump_switch_id: pump_switch
```
Enabling valve_over_pressure zone after valve_switch_12 cause:

```
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core  1 register dump:
PC      : 0x400dfda5  PS      : 0x00060930  A0      : 0x800dfe2c  A1      : 0x3ffb2610  
A2      : 0x3ffb457c  A3      : 0x3ffcab7c  A4      : 0x00000000  A5      : 0x00000001  
A6      : 0x3ffb4718  A7      : 0x00000010  A8      : 0x800dfda5  A9      : 0x3ffb25f0  
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x3f418213  A13     : 0x3ffb8ab0  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000020  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000010  LBEG    : 0x40089c90  LEND    : 0x40089ca6  LCOUNT  : 0xffffffff  

Backtrace:0x400dfda2:0x3ffb26100x400dfe29:0x3ffb2630 0x400dfe65:0x3ffb2650 
0x400dfe81:0x3ffb2670 0x400dfea9:0x3ffb2690 0x400e0864:0x3ffb26b0 0x400e0de5:0x3ffb2720
0x400e0fa9:0x3ffb2740 0x40186fc1:0x3ffb2760 0x400ece5b:0x3ffb2780 0x400ea7e9:0x3ffb27d0
0x400edb76:0x3ffb2800 0x40100665:0x3ffb2820
```

My usecase is to have a special zone enabled only when over pressure event happen to drain it out, so when enabled pump should be off and valve open for short time.

Regards.

### Which version of ESPHome has the issue?

2024.6.1 Aug 13 2024, 07:34:55

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32dev
