### ISSUE TITLE
MQTT_CLIENT: Subscribe message cannot be created

### ISSUE THREAD

**Issue by ginkel** [esphome/issues#6150]
### The problem

Hi there,

all of a sudden [1], newly updated esphome devices are emitting the following error periodically (once per second):

```
[17:39:30][D][esp-idf:000]: E (30480) MQTT_CLIENT: Subscribe message cannot be created
```

I do have MQTT configured:

```
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

  on_message:
    [...]
```

The log message is emitted by https://github.com/espressif/esp-mqtt/blob/master/mqtt_client.c#L1923

On my MQTT broker everything seems fine, though, i.e., I can see topics being subscribed to by the device and messages published.

Any ideas?

Thanks,
Thilo

[1] I updated esphome and changed config at once, shame on me...

### Which version of ESPHome has the issue?

2024.7.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

ESP32-C3-WROOM-02
