### ISSUE TITLE
Sprinkler controller do not honor valve_overlap settings.

### ISSUE THREAD

**Issue by hetii** [esphome/issues#6168]
### The problem

Hi.

Sprinkler controller do not honor valve_overlap settings when change zone by web ui switches or by calling sprinkler.next_valve / sprinkler.previous_valve actions.

It's only honored when auto_advanced is enabled eg when main switch is on and normal cycle is in progress.

Best Regards.

### Which version of ESPHome has the issue?

2024.6.1 Aug 17 2024, 10:44:05

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
sprinkler:
  - id: irrigation_controller
    valve_overlap: 5s
    next_prev_ignore_disabled: true
    pump_switch_off_during_valve_open_delay: false
....
```
