### ISSUE TITLE
Sprinkler controller keep internally wrong active_valve value.

### ISSUE THREAD

**Issue by hetii** [esphome/issues#6169]
### The problem

Hi.
Sprinkler controller when using sprinkler.next_valve / sprinkler.previous_valve actions or
when change zones by web ui switches, set internally wrong active_valve value.

It's always set to previously used, not the current progressing one (eg. valve 6 active and progressing, but 4 reported):

![obraz](https://github.com/user-attachments/assets/dba745c8-f58a-4374-9fac-bcc94099d343)
![obraz](https://github.com/user-attachments/assets/75f6a955-d69d-4bae-84f1-f937b6c28cda)

This affect the pause functionality as when resume it start from previously used one.

Also web us switches don't allow to switch one valve back from the current working one as the controller assume it's already active.

As a side effect this provide wrong progress_status in my code as the value of  id(irrigation_controller).active_valve() is wrong.

I notice when I added  valve_overlap: 1s it fix the issue, but then https://github.com/esphome/issues/issues/6168 popup.
Also seams that adding delay by valve_open_delay: 1s fix it but then https://github.com/esphome/issues/issues/5740 popup

Best Regards.

### Which version of ESPHome has the issue?

2024.6.1 Aug 17 2024, 10:44:05

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
sprinkler:
  - id: irrigation_controller
    next_prev_ignore_disabled: true
    pump_switch_off_during_valve_open_delay: false

...

  # Expose Valve Progress:
  - platform: template
    id: progress_percent
    name: "Valve Progress %"
    update_interval: $sensor_update_frequency
    icon: "mdi:progress-clock"
    web_server_sorting_weight: 7
    lambda: |-
      size_t active_valve = id(irrigation_controller).active_valve().value_or(0);
      uint32_t time_remaining_active_valve = id(irrigation_controller).time_remaining_active_valve().value_or(0);
      uint32_t valve_run_duration_adjusted = id(irrigation_controller).valve_run_duration_adjusted(active_valve);
      int progress_percent = round((( valve_run_duration_adjusted - time_remaining_active_valve) * 100 / valve_run_duration_adjusted));
      std::string progress_percent_as_string = std::to_string(progress_percent);

      ESP_LOGI("ValveProgress", "active_valve: %i, time_remaining_active_valve: %i, valve_run_duration_adjusted: %i, progress_percent: %i", active_valve, time_remaining_active_valve, valve_run_duration_adjusted, progress_percent);
      return progress_percent_as_string +"%";
```
