### ISSUE TITLE
binary_sensor, remote_receiver, keeloq: code field should not be required

### ISSUE THREAD

**Issue by lhartmann** [esphome/issues#6173]
### The problem

Using a `binary_sensor` tied to a `remote_receiver` with `keeloq` protocol.

Documentation describes `address` and `command` as required fields, but does not mention `code`. [See here](https://github.com/esphome/esphome-docs/blob/84b7857577df89d5d1d957d9b5214df897b4f4d0/components/remote_receiver.rst?plain=1#L308).

`KEELOQ_SCHEMA` defines `code` as required, [see here](https://github.com/esphome/esphome/blob/10147d8e0eddaa86ac388946f28288432a1c47af/esphome/components/remote_base/__init__.py#L702C1-L703C1).

The mentioned code seems to be the encrypted portion of a keeloq frame, [see here](https://github.com/esphome/esphome/blob/10147d8e0eddaa86ac388946f28288432a1c47af/esphome/components/remote_base/__init__.py#L739).

This encrypted portion is a rolling code and, ideally, would never be reused. Having this field required makes the keeloq binary sensor useless with a proper transmitter.

### Which version of ESPHome has the issue?

2024.7.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1

### Component causing the issue

binary_sensor

### Example YAML snippet

```yaml
remote_receiver:
  rmt_channel: 2
  pin: GPIO1
  dump: keeloq

binary_sensor:
  - platform: remote_receiver
    id: blue_right
    keeloq:
      address: 0x12345678
      command: 0x02
#     editor error: "'code' is a required option for [keeloq]."
```
