### ISSUE TITLE
mcp23s17 works on framework: arduino but not on framework: esp-idf

### ISSUE THREAD

**Issue by pihiandreas** [esphome/issues#6176]
### The problem

While trying to finalize @angelnu 's work on the ade7953_spi-component (f.e. for the Shelly Pro4PM), I found that there is some issue in the generic SPI-components implementation for _esp-idf_.  

An esphome-image with only the Pro4PMs 4 relay switches (controlled over Spi + mcp23s17) works flawlessly using
```
esp32:
  framework: arduino

```
but only one(#4) of four relays switch when using:
```
esp32:
  framework: esp-idf

```  
The only framework-specific implementations I could find are `components/spi/spi_arduino.cpp` vs `components/spi/spi_esp_idf.cpp`.

Does anyone have some good ideas where to investigate further?? 

### Which version of ESPHome has the issue?

2024.08.0-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Not related to Home Assistant

### What platform are you using?

ESP32-IDF

### Board

shelly pro4pm / esp32doit-devkit-v1

### Component causing the issue

components/spi or components/mcp23s17

### Example YAML snippet

```yaml
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

spi:
  - id: spi_bus_1
    clk_pin: GPIO32
    mosi_pin: GPIO33
    miso_pin: GPIO39

mcp23s17:
  - id: 'mcp23s17_hub'
    spi_id: spi_bus_1
    cs_pin: GPIO16
    deviceaddress: 0

switch:
  - platform: gpio
    name: "${relay_1}"
    id: relay_1
    pin:
      mcp23xxx: mcp23s17_hub
      number: 8
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "${relay_2}"
    id: relay_2
    pin:
      mcp23xxx: mcp23s17_hub
      number: 13
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "${relay_3}"
    id: relay_3
    pin:
      mcp23xxx: mcp23s17_hub
      number: 14
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "${relay_4}"
    id: relay_4
    pin:
      mcp23xxx: mcp23s17_hub
      number: 12
      mode:
        output: true
      inverted: false
```

### Anything in the logs that might be useful for us?

```txt
nothing related shown in logs on loglevel: VERY_VERBOSE
```
