### ISSUE TITLE
Unable to compile GPIO output when integrated with ESP32 S3 Box 3 with Wake Word Home Assistant

### ISSUE THREAD

**Issue by Tace03** [esphome/issues#6178]
### The problem

Hi, I am trying to control some sensors based on speech using Wake Word Home Assistant with model ESP32 S3 Box 3. I am using the Dock provided in the set to connect and control sensors through GPIO.

Up until this point of trials, I have been testing with 'switch', 'binary_sensor' and all of them was fine, until I encountered this error with 'output' component, specifically on gpio platform.

Every other components inside the YAML file seemed to be compiled well, except for the output component I have just described. The error message I will put as in the form below

### Which version of ESPHome has the issue?

ESPHome version 2024.7.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

ESP32 S3 Box 3

### Component causing the issue

Any sensor that can be used as Binary Output running on GPIO

### Example YAML snippet

```yaml
# This is just my addition to the components
# The original YAML code is taken from https://github.com/esphome/wake-word-voice-assistants/blob/main/esp32-s3-box-3/esp32-s3-box-3.yaml

output:
  - platform: gpio
    id: laser
    pin: GPIO13

switch:
  - platform: template
    optimistic: True
    name: "test laser gpio"
    on_turn_on:
      then:
    on_turn_off: 
      then:
```

### Anything in the logs that might be useful for us?

```txt
HARDWARE: ESP32S3 240MHz, 320KB RAM, 16MB Flash
 - framework-espidf @ 3.40407.240606 (4.4.7) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.4
|-- ESPMicroSpeechFeatures @ 1.0.0
Compiling .pioenvs/esp32-s3-box-3-054d50/src/main.o
Linking .pioenvs/esp32-s3-box-3-054d50/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: missing --end-group; added as last command line option
/data/cache/platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: .pioenvs/esp32-s3-box-3-054d50/src/main.o:(.literal._Z5setupv+0x10c): undefined reference to `vtable for esphome::gpio::GPIOBinaryOutput'
/data/cache/platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: .pioenvs/esp32-s3-box-3-054d50/src/main.o:(.literal._Z5setupv+0x110): undefined reference to `vtable for esphome::gpio::GPIOBinaryOutput'
collect2: error: ld returned 1 exit status
*** [.pioenvs/esp32-s3-box-3-054d50/firmware.elf] Error 1
========================= [FAILED] Took 133.64 seconds =========================
```
