### ISSUE TITLE
Esphome can't connect to home assistant after update to version 2024.8.0

### ISSUE THREAD

**Issue by Totix92** [esphome/issues#6180]
### The problem

I am using a ESP32-C3 supermini in my Bosch-Midea air conditioner, for remote control.
Everything has always worked fine, when I updated the firmware to ESPHome 2024.8.0, installed without problems, but now neither Home Assistant, nor the ESPHome addon see the ESP32 that appears disconnected, but the ESP32 connects to the WiFi without apparently any problem.
The web server is unreachable.
![Schermata del 2024-08-21 11-38-31](https://github.com/user-attachments/assets/94b53126-ea7d-423d-aafc-b3015fb0889b)

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.8.2

### What platform are you using?

ESP32

### Board

ESP32-C3 supermini

### Example YAML snippet

```yaml
esphome:
  name: bosch-climate-3000i
  friendly_name: Bosch Climate 3000i
  area: Cucina

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "UKCAmFVwyCyhdOUMAymnYnx+vkymNo9cyirrteNOklI="

ota:
  - platform: esphome
    password: "5301b4924b12e50ccd54327287fc9036"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bosch-Climate-3000I"
    password: "c223vn7adRYM"

captive_portal:

# UART settings for Midea dongle (required)
uart:
  tx_pin: 21         # hardware dependant
  rx_pin: 20         # hardware dependant
  baud_rate: 9600

# Main settings
climate:
  - platform: midea
    name: "Cucina"         # Use a unique name.
    period: 1s                  # Optional
    timeout: 2s                 # Optional
    num_attempts: 3             # Optional
    autoconf: true              # Autoconfigure most options.
    beeper: true                # Beep on commands.
    visual:                     # Optional. Example of visual settings override.
      min_temperature: 17 °C    # min: 17
      max_temperature: 30 °C    # max: 30
      temperature_step: 1 °C  # min: 0.5
    supported_modes:            # Optional. All capabilities in this section may be detected by autoconf.
      - FAN_ONLY
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    custom_fan_modes:           # Optional
      - SILENT
      - TURBO
    supported_presets:          # Optional. All capabilities in this section may be detected by autoconf.
      - ECO
      - BOOST
      - SLEEP
    custom_presets:             # Optional. All capabilities in this section may be detected by autoconf.
      - FREEZE_PROTECTION
    supported_swing_modes:      # Optional
      - VERTICAL
      - HORIZONTAL
      - BOTH
    outdoor_temperature:        # Optional. Outdoor temperature sensor (may display incorrect values after long inactivity).
      name: "Temp"


switch:
  - platform: template
    name: "Climate Cucina Beeper"
    icon: mdi:volume-source
    restore_mode: 'RESTORE_DEFAULT_ON'
    optimistic: true
    turn_on_action:
      midea_ac.beeper_on:
    turn_off_action:
      midea_ac.beeper_off:

binary_sensor:
  - platform: status
    name: "Climate Cucina Connection Status"
    id: climate_cucina_connection_status

text_sensor:
  - platform: template
    name: "Uptime Human Readable"
    id: uptime_human
    icon: mdi:clock-start

  - platform: version
    name: "Climate Cucina ESPHome Version"
    id: climate_cucina_esphome_version

  - platform: wifi_info
    ip_address:
      name: "Climate Cucina IP Address"
      id: climate_cucina_ip_address
      icon: mdi:ip-network

sensor:
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  - platform: wifi_signal
    name: "Climate Cucina WiFi Signal"
    id: climate_cucina_wifi_signal
    update_interval: 30s

  - platform: copy
    source_id: climate_cucina_wifi_signal
    name: "Climate Cucina signal percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

  - platform: internal_temperature
    name: "Internal Temperature"
    icon: "mdi:thermometer"

time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

button:
  - platform: restart
    name: "Climate Cucina Restart"
    id: climate_cucina_restart
    icon: "mdi:restart"

  - platform: shutdown
    name: "Climate Cucina Shutdown"
    id: climate_cucina_shutdown

  - platform: safe_mode
    name: "Climate Cucina Safe Mode"
    id: climate_cucina_safe_mode

  - platform: factory_reset
    name: "Climate Cucina Factory Reset"

web_server:
  port: 80
```
