### ISSUE TITLE
Failed to load packages. esp32-generic.yaml does not exist in repository. after upgrading from 2024.07 to 2024.08

### ISSUE THREAD

**Issue by proffalken** [esphome/issues#6182]
### The problem

The ESPHome upgrade itself worked fine, now I'm trying to update my devices.

These are stock ESPHome Bluetooth Proxies installed via the website.

I have checked the repo at https://github.com/esphome/bluetooth-proxies/tree/main/esp32-generic and the file exists.

Here is the output in HomeAssistant:

![image](https://github.com/user-attachments/assets/7b0c1bcb-aa1c-460e-81bf-9fac869cd88e)

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.08.x

### What platform are you using?

ESP32

### Board

Generic ESP32

### Component causing the issue

Bluetooth Proxy

### Example YAML snippet

```yaml
substitutions:
  name: esp32-bluetooth-proxy-a955fc
  friendly_name: bluetooth-proxy-garden
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: <API KEY>

ota:
    platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```

### Anything in the logs that might be useful for us?

```txt
Failed to load packages. esp32-generic.yaml does not exist in repository.
```

### Additional information

I have not made any changes to the configuration, I have just tried to run the update by clicking the button in the ESPHome UI.

I have automations that rely on devices being seen by specific BT Proxies, so I don't really want to have to remove and re-add these devices if possible.
