### ISSUE TITLE
[LVGL] Tileview and page scrollbar mode not working

### ISSUE THREAD

**Issue by Samywamy10** [esphome/issues#6184]
### The problem

When I use `scrollbar_mode` on either a `tileview` or a `page`, the yml file validation doesn't fail, but when compiling I get the error:
```
error: 'lv_tileview_set_scrollbar_mode' was not declared in this scope
```

Minimal yaml
```yml
lvgl:
  touchscreens:
    - my_touchscreen
  pages:
    - id: main_page
      widgets:
        - tileview:
            id: tileview_id
            scrollbar_mode: active #error here
            tiles:
              - id: page_1
                row: 0
                column: 0
                dir: HOR
                widgets:
                  - obj:
                      bg_color: 0x000000
```

I get the same error when setting this on a page too. I believe we need to use `page_scrollbar_mode` as per: https://forum.lvgl.io/t/how-to-hide-the-scrollbar-in-titleview/4140 - but this is not available in yaml

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.8.1

### What platform are you using?

ESP32-IDF

### Board

esp32-s3-devkitc-1

### Component causing the issue

lvgl

### Example YAML snippet

```yaml
lvgl:
  touchscreens:
    - my_touchscreen
  pages:
    - id: main_page
      widgets:
        - tileview:
            id: tileview_id
            scrollbar_mode: active #error here
            tiles:
              - id: page_1
                row: 0
                column: 0
                dir: HOR
                widgets:
                  - obj:
                      bg_color: 0x000000
```

### Anything in the logs that might be useful for us?

```txt
error: 'lv_tileview_set_scrollbar_mode' was not declared in this scope
```
