### ISSUE TITLE
LVGL `lvgl.update` -> `disp_bg_color` is erroring

### ISSUE THREAD

**Issue by Samywamy10** [esphome/issues#6190]
### The problem

I'm trying to set a background color dynamically. I tried via something like `lvgl.page.update` but this doesn't exist (as I'm setting bg color by page). Instead tried to set and update the whole `disp_bg_color` but getting the error below. Looks like it's not working ([docs seem to suggest it should](https://esphome.io/components/lvgl/#lvgl-update))

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.8.1

### What platform are you using?

ESP32-IDF

### Board

esp32-s3-devkitc-1

### Component causing the issue

lvgl

### Example YAML snippet

```yaml
text_sensor:
  - platform: homeassistant
    id: living_room_ac_state
    entity_id: climate.living_room_ac
    internal: true
    on_value: 
      then:
        - if:
            condition:
              - text_sensor.state: 
                  id: living_room_ac_state
                  state: "heat"
            then:
              - lvgl.page.show: ac_on_page
              - lvgl.image.update:
                  id: img_ac_mode
                  src: fire
                  
        - if:
            condition:
              - text_sensor.state: 
                  id: living_room_ac_state
                  state: "cool"
            then:
              - lvgl.page.show: ac_on_page
              - lvgl.image.update:
                  id: img_ac_mode
                  src: ice
              - lvgl.update: #HERE IS THE ERROR
                  disp_bg_color: 0x0000FF
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/circle/src/main.cpp.o
/config/esphome/cirlcescreen.yaml: In function 'void setup()':
/config/esphome/cirlcescreen.yaml:153:4: error: no matching function for call to 'esphome::lvgl::LvglAction<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::LvglAction(setup()::<lambda(std::__cxx11::string)>)'
                   disp_bg_color: 0x0000FF
    ^
In file included from src/esphome.h:59,
                 from src/main.cpp:3:
src/esphome/components/lvgl/lvgl_esphome.h:178:12: note: candidate: 'esphome::lvgl::LvglAction<Ts>::LvglAction(std::function<void(esphome::lvgl::LvglComponent*)>&&) [with Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]'
   explicit LvglAction(std::function<void(LvglComponent *)> &&lamb) : action_(std::move(lamb)) {}
            ^~~~~~~~~~
src/esphome/components/lvgl/lvgl_esphome.h:178:12: note:   no known conversion for argument 1 from 'setup()::<lambda(std::__cxx11::string)>' to 'std::function<void(esphome::lvgl::LvglComponent*)>&&'
src/esphome/components/lvgl/lvgl_esphome.h:176:32: note: candidate: 'esphome::lvgl::LvglAction<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::LvglAction(const esphome::lvgl::LvglAction<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&)'
 template<typename... Ts> class LvglAction : public Action<Ts...>, public Parented<LvglComponent> {
                                ^~~~~~~~~~
src/esphome/components/lvgl/lvgl_esphome.h:176:32: note:   no known conversion for argument 1 from 'setup()::<lambda(std::__cxx11::string)>' to 'const esphome::lvgl::LvglAction<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&'
src/esphome/components/lvgl/lvgl_esphome.h:176:32: note: candidate: 'esphome::lvgl::LvglAction<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::LvglAction(esphome::lvgl::LvglAction<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&&)'
src/esphome/components/lvgl/lvgl_esphome.h:176:32: note:   no known conversion for argument 1 from 'setup()::<lambda(std::__cxx11::string)>' to 'esphome::lvgl::LvglAction<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&&'
*** [.pioenvs/circle/src/main.cpp.o] Error 1
========================== [FAILED] Took 8.60 seconds ==========================
```
