### ISSUE TITLE
 Neopixel Strobe effect (White channel issue)

### ISSUE THREAD

**Issue by tiaanv** [esphome/issues#620]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
Wemos D1 Mini

**Affected component:**
NeopixelBus

**Description of problem:**
When implementing the Strobe Effect, the white channel seems to stay on when using the state: False attribute.  As a workaround I have set a secondary Strobe state setting everything to 0%, this seems to work. 

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: neopixelbus
    type: GRBW
    pin: GPIO3
    num_leds: 65
    method: ESP8266_DMA
    name: "NeoPixel Light"
    effects:
      - strobe:
          name: Workaround
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              white: 0%
              duration: 200ms
            - state: True
              brightness: 0%
              red: 0%
              green: 0%
              blue: 100%
              white: 0%
              duration: 200ms
      - strobe:
          name: Does Not Work
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              white: 0%
              duration: 200ms
            - state: False
              duration: 200ms   
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
N/A
```

**Additional information and things you've tried:**
[Edit]
After spending some time trying to understand the code structure, this piece code is my first theory (stab in the dark really).
**base_light_effects.h** line 102+
```c
    if (!color.is_on()) {
      // Don't turn the light off, otherwise the light effect will be stopped
      call.set_brightness_if_supported(0.0f);
      call.set_state(true);
    }
```
My understanding is, that this part of the code for "state: False" is setting the brightness to 0, rather than setting the light to off state for reasons in the comment.  With my playing around, it is clear that setting the brightness on a RGBW light, leaves the white channel alone.  Should probably add something here to also set the white channel to 0.0f ?

Not sure if this is helpful.
