### ISSUE TITLE
Compiler warning after the update to version 2024.8.0

### ISSUE THREAD

**Issue by Dolphin1220** [esphome/issues#6201]
### The problem

There are warnings (yellow text) in the log.

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.8.2

### What platform are you using?

ESP8266

### Board

D1-Mini

### Example YAML snippet

```yaml
remote_receiver:
  id: rcvr
  pin:
    number: D6
    inverted: True
    mode:
      input: True
      pullup: True
  tolerance: 55%
  dump: nec

remote_transmitter:
  pin: D7
  carrier_duty_percent: 50%

sensor:
  - platform: dht
    model: DHT22
    pin: D2
    temperature:
      name: "Temperature"
      id: temp
    humidity:
      name: "Humidity"
      id: hum
      accuracy_decimals: 1
    update_interval: 5s

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

button:
  - platform: template
    name: "Power"
    on_press:
     - remote_transmitter.transmit_nec:
        address: 0x7E01
        command: 0xF708
    icon: "mdi:power"

  - platform: template
    name: "Speed"
    on_press:
     - remote_transmitter.transmit_nec:
        address: 0x7E01
        command: 0xFA05
    icon: "mdi:speedometer"
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/klima/src/esphome/components/wifi_signal/wifi_signal_sensor.cpp.o
Compiling .pioenvs/klima/src/esphome/core/application.cpp.o
Compiling .pioenvs/klima/src/esphome/core/bytebuffer.cpp.o
src/esphome/core/bytebuffer.cpp: In member function 'float esphome::ByteBuffer::get_float()':
src/esphome/core/bytebuffer.cpp:86:11: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   86 |   return *(float *) &value;
      |           ^~~~~~~~~~~~~~~~
src/esphome/core/bytebuffer.cpp: In member function 'void esphome::ByteBuffer::put_float(float)':
src/esphome/core/bytebuffer.cpp:129:61: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  129 | void ByteBuffer::put_float(float value) { this->put_uint32(*(uint32_t *) &value); }
```
