### ISSUE TITLE
REST API 401 Unauthorized

### ISSUE THREAD

**Issue by MorganMLGman** [esphome/issues#6203]
### The problem

I am trying to access REST API, but it returns 401 Unauthorized, despite that I can access webpage without any problems with the same user and password.

![image](https://github.com/user-attachments/assets/3714cef7-5ccf-48c6-9999-15199f9a213c)
![image](https://github.com/user-attachments/assets/60e7dc2a-0a3e-4ffc-af4e-d386c3d9d7e8)

### Which version of ESPHome has the issue?

2024.8.0, 2024.7.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP8266

### Board

esp8285, esp32-c3-devkitm-1, esp32-s3-devkitc-1, wt32-eth01

### Component causing the issue

api/rest api

### Example YAML snippet

```yaml
web_server:
  port: 80
  local: true
  ota: true
  include_internal: True
  version: 2
  auth: 
    username: !secret web_user
    password: !secret web_password

---

web_server:
  port: 80
  local: true
  ota: false
  include_internal: True
  version: 3
  auth: 
    username: !secret web_user
    password: !secret web_password
```

### Anything in the logs that might be useful for us?

```txt
No
```

### Additional information

No
