### ISSUE TITLE
Unable to update ESP32 in Safe Mode via OTA with new OTA/Safe Mode segregatiion 

### ISSUE THREAD

**Issue by yokokito** [esphome/issues#6206]
### The problem

I have updated my ESPHOME implementation in a NSPANEL to the latest version 2024.8.0. I changed the YAML file to update the OTA and SAFE_MODE sections with the new approach. No more changes. It compiled perfectly and I uploaded the bin file via OTA without problem.

I try the same now, and it is not possible to update it via OTA in SafeMode.

 ERROR Connecting to 192.168.0.131:3232 failed: [WinError 10061] 

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

NS-PANEL (SONOFF)

### Example YAML snippet

```yaml
safe_mode:  
   num_attempts: 3

ota:
 - platform: esphome   
   on_begin:
     then:
      - lambda: 'id($NspanelID).goto_page("12");'   
      - lambda: |-
             id(persiana).set_update_interval(0);
             id(persiana).call_setup();
             id(termostato).set_update_interval(0);
             id(termostato).call_setup();       
   on_progress:
     then:
      - lambda: id($NspanelID).send_command_printf("firmware.progress.val=%.0f", x); 
      - lambda: id($NspanelID).set_component_text_printf("firmware.t0", "%.0f", x);       

 
 
   on_error:
     then:
       - logger.log:
           format: "OTA update error %d"
           args: ["x"]
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.8.0
INFO Reading configuration nspanel1_rec.yaml...
INFO Connecting to 192.168.0.131
ERROR Connecting to 192.168.0.131:3232 failed: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
```

### Additional information

My previous ESPHOME version  before the upgrade to 2024.8.0 was from June (I do not remember the version).

I try to update via OTA in a Windows Terminal --> esphome run nspanel_2.yaml --device 192.168.0.131
