### ISSUE TITLE
SONOFF D1 Dimmer - Turning off using the RF remote causes off/on/off procedure

### ISSUE THREAD

**Issue by rb0135** [esphome/issues#6214]
### The problem

Using the standard 433mhz remote that comes with the D1 Dimmer, turning the lights on works fine. Dimming works fine with the buttons.

However, when turning the lights off with the remote causes the lights to turn off, then turn back on to the previous dimmed setting then tuns off, all within .5-1 sec.

This did not happen when using the Sonoff firmware (meaning it isnt the globes that are causing this with the device).

Utilising HA Light Card, this does not happen either. The lights just turn off.

### Which version of ESPHome has the issue?

2024.8.1

### What type of installation are you using?

Home Assistant Add-on AND RF 433Mhz Remote

### Which version of Home Assistant has the issue?

2024.8.3

### What platform are you using?

ESP8266

### Board

Sonoff D1 Dimmer

### Example YAML snippet

```yaml
# Example configuration entry
esphome:
  name: bar-lights

# Restore from flash if you want to keep the last state at power up
esp8266:
  board: esp8285
  restore_from_flash: true

# Make sure your WiFi will connect
packages:
  wifi: !include common/wifi-iot.yaml

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "<my special key"

# Make sure you can upload new firmware OTA
ota:
  platform: esphome

# D1 dimmer uses hardware serial port on the default pins @ 9600 bps
uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600

# And finally the light component
# gamma correction equal to zero gives linear scale,
# exactly what's needed for this device
light:
  - platform: sonoff_d1
    use_rm433_remote: true
    name: Bar Lights
    restore_mode: RESTORE_DEFAULT_OFF
    gamma_correct: 0.0
    default_transition_length: 1s
```

### Anything in the logs that might be useful for us?

Just adding that I found this in the logs... Seems Esphome sees the RF set State to Off, then the state is set to ON, then the OFF procedure runs

Here is a log capture of it doing so. It seems it accepts the off command from the remote, but maybe esphome code turns them on again to turn them off.

[13:19:32][I][sonoff_d1:212]: [0243] RF sets dimmer state to OFF, raw brightness=10
[13:19:32][I][sonoff_d1:203]: [0243] Setting dimmer state to ON, raw brightness=10
[13:19:32][D][sonoff_d1:145]: [0244] Acknowledge received
[13:19:32][D][light:036]: 'Bar Lights' Setting:
[13:19:32][D][light:047]:   State: OFF
[13:19:32][D][light:051]:   Brightness: 9%
[13:19:32][D][light:085]:   Transition length: 1.0s
[13:19:32][I][sonoff_d1:203]: [0244] Setting dimmer state to ON, raw brightness=9
[13:19:32][D][sonoff_d1:145]: [0245] Acknowledge received
[13:19:32][I][sonoff_d1:203]: [0245] Setting dimmer state to ON, raw brightness=8
[13:19:32][D][sonoff_d1:145]: [0246] Acknowledge received
[13:19:32][I][sonoff_d1:203]: [0246] Setting dimmer state to ON, raw brightness=7
[13:19:32][D][sonoff_d1:145]: [0247] Acknowledge received
[13:19:32][I][sonoff_d1:203]: [0247] Setting dimmer state to ON, raw brightness=6
[13:19:32][D][sonoff_d1:145]: [0248] Acknowledge received
[13:19:32][I][sonoff_d1:203]: [0248] Setting dimmer state to ON, raw brightness=5
[13:19:32][D][sonoff_d1:145]: [0249] Acknowledge received
[13:19:33][I][sonoff_d1:203]: [0249] Setting dimmer state to ON, raw brightness=4
[13:19:33][D][sonoff_d1:145]: [0250] Acknowledge received
[13:19:33][I][sonoff_d1:203]: [0250] Setting dimmer state to ON, raw brightness=3
[13:19:33][D][sonoff_d1:145]: [0251] Acknowledge received
[13:19:33][I][sonoff_d1:203]: [0251] Setting dimmer state to ON, raw brightness=2
[13:19:33][D][sonoff_d1:145]: [0252] Acknowledge received
[13:19:33][I][sonoff_d1:203]: [0252] Setting dimmer state to ON, raw brightness=1
[13:19:33][D][sonoff_d1:145]: [0253] Acknowledge received
[13:19:33][I][sonoff_d1:203]: [0253] Setting dimmer state to OFF, raw brightness=1
[13:19:33][D][sonoff_d1:145]: [0254] Acknowledge received
[13:19:50][D][esp8266.preferences:238]: Saving preferences to flash...
