### ISSUE TITLE
on_canalsatld Trigger not fully implemented

### ISSUE THREAD

**Issue by Elix-g** [esphome/issues#6218]
### The problem

Configuring a trigger 'on_canalsatid' in a remote_receiver component, leads to a compile error, although documented [here](https://www.esphome.io/components/remote_receiver):

```
/opt/esphome/dashboard/irgw-01.yaml: In function 'void setup()':
/opt/esphome/dashboard/irgw-01.yaml:46:98: error: no matching function for call to 'esphome::Automation<esphome::remote_base::CanalSatLDData>::Automation(esphome::remote_base::CanalSatLDTrigger*&)'
   46 |         data_template:
      |                                                                                                  ^
In file included from src/esphome/components/api/api_server.h:7,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/automation.h:236:12: note: candidate: 'esphome::Automation<Ts>::Automation(esphome::Trigger<Ts ...>*) [with Ts = {esphome::remote_base::CanalSatLDData}]'
  236 |   explicit Automation(Trigger<Ts...> *trigger) : trigger_(trigger) { this->trigger_->set_automation_parent(this); }
      |            ^~~~~~~~~~
src/esphome/core/automation.h:236:39: note:   no known conversion for argument 1 from 'esphome::remote_base::CanalSatLDTrigger*' {aka 'esphome::remote_base::RemoteReceiverTrigger<esphome::remote_base::CanalSatLDProtocol>*'} to 'esphome::Trigger<esphome::remote_base::CanalSatLDData>*'
  236 |   explicit Automation(Trigger<Ts...> *trigger) : trigger_(trigger) { this->trigger_->set_automation_parent(this); }
      |                       ~~~~~~~~~~~~~~~~^~~~~~~
src/esphome/core/automation.h:234:32: note: candidate: 'constexpr esphome::Automation<esphome::remote_base::CanalSatLDData>::Automation(const esphome::Automation<esphome::remote_base::CanalSatLDData>&)'
  234 | template<typename... Ts> class Automation {
      |                                ^~~~~~~~~~
src/esphome/core/automation.h:234:32: note:   no known conversion for argument 1 from 'esphome::remote_base::CanalSatLDTrigger*' {aka 'esphome::remote_base::RemoteReceiverTrigger<esphome::remote_base::CanalSatLDProtocol>*'} to 'const esphome::Automation<esphome::remote_base::CanalSatLDData>&'
src/esphome/core/automation.h:234:32: note: candidate: 'constexpr esphome::Automation<esphome::remote_base::CanalSatLDData>::Automation(esphome::Automation<esphome::remote_base::CanalSatLDData>&&)'
src/esphome/core/automation.h:234:32: note:   no known conversion for argument 1 from 'esphome::remote_base::CanalSatLDTrigger*' {aka 'esphome::remote_base::RemoteReceiverTrigger<esphome::remote_base::CanalSatLDProtocol>*'} to 'esphome::Automation<esphome::remote_base::CanalSatLDData>&&'
*** [.pioenvs/irgw-01/src/main.cpp.o] Error 1
```

### Which version of ESPHome has the issue?

2024.8.1

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

remote_receiver / CanalSatLD

### Example YAML snippet

```yaml
remote_receiver:
  dump: all
  pin:
    number: GPIO5
    inverted: true
  on_nec:
    - homeassistant.event:
        event: esphome.ir_code_received
        data_template:
          address: !lambda |-
            return format_hex(x.address);
          command: !lambda |-
            return format_hex(x.command);
          message: NEC IR code received
  on_canalsat:
    - homeassistant.event:
        event: esphome.ir_code_received
        data_template:
          device: !lambda |-
            return format_hex(x.device);
          address: !lambda |-
            return format_hex(x.address);
          command: !lambda |-
            return format_hex(x.command);
          message: CanalSat IR code received
  on_canalsatld:
    - homeassistant.event:
        event: esphome.ir_code_received
        data_template:
          device: !lambda |-
            return format_hex(x.device);
          address: !lambda |-
            return format_hex(x.address);
          command: !lambda |-
            return format_hex(x.command);
          message: CanalSatLD IR code received
```
