### ISSUE TITLE
Failed to load packages. m5stack/m5stack-atom-lite.yaml does not exist in repository

### ISSUE THREAD

**Issue by aselling** [esphome/issues#6220]
### The problem

After updating my Atom M5Stack Lite that I use for bluetooth proxies with Home Assistant late in august all of my M5Atom went offline.

I have reinstalled them through: https://esphome.io/projects/index.html
They show up in Home Assistant and I have adopted them and they are online.

But now they won't compile

Error message says:
```
INFO ESPHome 2024.8.1
INFO Reading configuration /config/esphome/m5stack-atom-lite-8538f8.yaml...
Failed config

packages: [source /config/esphome/m5stack-atom-lite-8538f8.yaml:5]
  
  Failed to load packages. m5stack/m5stack-atom-lite.yaml does not exist in repository.
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack/m5stack-atom-lite.yaml@main
```

Here is the Yaml-code: 
```yaml
substitutions:
  name: m5stack-atom-lite-8538f8
  friendly_name: Bluetooth Proxy garage
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack/m5stack-atom-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: xxxxxx


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  static_ip: 192.168.1.232
  gateway: 192.168.1.1
  subnet: 255.255.255.0
  dns1: 192.168.1.1
```

### Which version of ESPHome has the issue?

2024.8.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.8.3

### What platform are you using?

ESP32

### Board

m5stack-atom-lite
