### ISSUE TITLE
unable to upload file using ota inside esphome

### ISSUE THREAD

**Issue by jpmangoit** [esphome/issues#6221]
### The problem

General issue report
I'm getting an error when trying to upload firmware using the ESPHome OTA process. Here are the error logs:
Starting update from 192.168.168.182...
[16:23:31][W][esphome.ota:130]: Magic bytes do not match! 0x50-0x4F-0x53-0x54-0x20
[16:23:31][E][component:164]: Component esphome.ota set Error flag: unspecified
[16:23:34][E][component:176]: Component esphome.ota cleared Error flag

when i'm uploading the same file using arduino framwork it uploads successfully but with esp-idf. i 'm always gettting this error.

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

esp32dev

### Component causing the issue

webserver/ota

### Example YAML snippet

```yaml
name: livingroom

ESP32 Configuration - ESP-IDF for SSL support
esp32:
board: esp32dev
framework:
type: esp-idf

Enable Home Assistant
api:
encryption:
key: ${API_KEY}
ota:
password: ${OTA_PASSWORD}
platform: esphome

Enable logging
logger:
level: WARN

WIFI Configuration
wifi:
ssid: ${wifi_ssid}
password: ${wifi_password}
power_save_mode: none

Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
ssid: ${AP_ssid}
password: ${AP_password}

captive_portal:
```
