### ISSUE TITLE
ESPHome and LD2410 sensor

### ISSUE THREAD

**Issue by leonardus1973** [esphome/issues#6226]
### The problem

Hello! Some mounth ago I've tested the install guide for LD2410 sensor in home assistant (ESPHome) and all works fine.
now I've some problem with graphic card.
can you help me?
![Immagine 2024-09-04 184525](https://github.com/user-attachments/assets/95757a73-1d25-4439-89a7-43b8b524c14c)
![Immagine 2024-09-04 184614](https://github.com/user-attachments/assets/918811cb-5151-4bf0-8aaf-ca529a6bceba)
 help me?

### Which version of ESPHome has the issue?

2024.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2024.8.1 Supervisor 2024.08.0 Operating System 12.4 Frontend

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
type: vertical-stack
title: Sensore Movimento LD2410
cards:
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - entity: switch.diy_ld2410_radar_engineering_mode
            name: Engineering Mode
            state_color: true
          - entity: switch.diy_ld2410_radar_control_bluetooth
            name: Control Bluetooth
            state_color: true
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - entity: button.diy_ld2410_restart_radar
            name: Restart Sensor
          - entity: button.diy_ld2410_query_params
            name: Query Params
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: number.diy_ld2410_radar_end_zone_1
            name: End Zone 1
            state_color: true
          - entity: number.diy_ld2410_radar_end_zone_2
            name: End Zone 2
            state_color: true
          - entity: number.diy_ld2410_radar_end_zone_3
            name: End Zone 3
            state_color: true
          - entity: number.diy_ld2410_radar_timeout
            name: Radar Time Out
            state_color: true
          - entity: select.diy_ld2410_radar_distance_resolution
            name: Radar Distance Resolution
            state_color: true
          - entity: number.diy_ld2410_g0_move_threshold
            name: Soglia Spostamento G0
          - entity: number.diy_ld2410_g1_move_threshold
            name: Soglia Spostamento G1
          - entity: number.diy_ld2410_g2_move_threshold
            name: Soglia Spostamento G2
          - entity: number.diy_ld2410_g3_move_threshold
            name: Soglia Spostamento G3
          - entity: number.diy_ld2410_g4_move_threshold
            name: Soglia Spostamento G4
          - entity: number.diy_ld2410_g5_move_threshold
            name: Soglia Spostamento G5
          - entity: number.diy_ld2410_g6_move_threshold
            name: Soglia Spostamento G6
          - entity: number.diy_ld2410_g7_move_threshold
            name: Soglia Spostamento G7
          - entity: number.diy_ld2410_g8_move_threshold
            name: Soglia Spostamento G8
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: number.diy_ld2410_g0_still_threshold
            name: Soglia Ferma G0
          - entity: number.diy_ld2410_g1_still_threshold
            name: Soglia Ferma G1
          - entity: number.diy_ld2410_g2_still_threshold
            name: Soglia Ferma G2
          - entity: number.diy_ld2410_g3_still_threshold
            name: Soglia Ferma G3
          - entity: number.diy_ld2410_g4_still_threshold
            name: Soglia Ferma G4
          - entity: number.diy_ld2410_g5_still_threshold
            name: Soglia Ferma G5
          - entity: number.diy_ld2410_g6_still_threshold
            name: Soglia Ferma G6
          - entity: number.diy_ld2410_g7_still_threshold
            name: Soglia Ferma G7
          - entity: number.diy_ld2410_g8_still_threshold
            name: Soglia Ferma G8
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: number.diy_ld2410_radar_max_move_distance
            name: Soglia Max Distanza Movimento
          - entity: number.diy_ld2410_radar_max_still_distance
            name: Soglia Max Distanza Fermo
      - type: horizontal-stack
        cards:
          - type: entity
            entity: sensor.diy_ld2410_esp_cpu_speed
            name: CPU Speed
          - type: entity
            entity: sensor.diy_ld2410_esp_free_memory
            name: Free Memory
  - type: horizontal-stack
    cards:
      - type: entity
        entity: sensor.diy_ld2410_radar_firmware_version
        name: Firmvare Version
      - type: entity
        entity: sensor.diy_ld2410_rssi
        name: RSSI
  - type: horizontal-stack
    cards:
      - type: entity
        entity: sensor.diy_ld2410_uptime
        name: Uptime
      - type: entity
        entity: sensor.diy_ld2410_esp_temperature
        name: ESP Tempertature
  - type: horizontal-stack
    cards:
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_zone_1_occupancy
        name: Zone 1
        state_color: true
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_zone_2_occupancy
        name: Zone 2
        state_color: true
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_zone_3_occupancy
        name: Zone 3
        state_color: true
  - type: horizontal-stack
    cards:
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_target
        name: Radar Target Acquisito
        state_color: true
  - type: horizontal-stack
    cards:
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_moving_target
        name: Radar Target Movimento
        state_color: true
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_still_target
        name: Radar Target Fermo
        state_color: true
  - type: horizontal-stack
    cards:
      - type: entity
        entity: sensor.diy_ld2410_radar_moving_distance
        name: Distanza Movimento
        state_color: true
      - type: entity
        name: Distanza Fermo
        state_color: true
        entity: sensor.diy_ld2410_radar_still_distance
```
-------------------------------------------------------------------
GRAPHIC CARD:
type: vertical-stack
title: Sensore Movimento LD2410
cards:
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - entity: switch.diy_ld2410_radar_engineering_mode
            name: Engineering Mode
            state_color: true
          - entity: switch.diy_ld2410_radar_control_bluetooth
            name: Control Bluetooth
            state_color: true
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - entity: button.diy_ld2410_restart_radar
            name: Restart Sensor
          - entity: button.diy_ld2410_query_params
            name: Query Params
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: number.diy_ld2410_radar_end_zone_1
            name: End Zone 1
            state_color: true
          - entity: number.diy_ld2410_radar_end_zone_2
            name: End Zone 2
            state_color: true
          - entity: number.diy_ld2410_radar_end_zone_3
            name: End Zone 3
            state_color: true
          - entity: number.diy_ld2410_radar_timeout
            name: Radar Time Out
            state_color: true
          - entity: select.diy_ld2410_radar_distance_resolution
            name: Radar Distance Resolution
            state_color: true
          - entity: number.diy_ld2410_g0_move_threshold
            name: Soglia Spostamento G0
          - entity: number.diy_ld2410_g1_move_threshold
            name: Soglia Spostamento G1
          - entity: number.diy_ld2410_g2_move_threshold
            name: Soglia Spostamento G2
          - entity: number.diy_ld2410_g3_move_threshold
            name: Soglia Spostamento G3
          - entity: number.diy_ld2410_g4_move_threshold
            name: Soglia Spostamento G4
          - entity: number.diy_ld2410_g5_move_threshold
            name: Soglia Spostamento G5
          - entity: number.diy_ld2410_g6_move_threshold
            name: Soglia Spostamento G6
          - entity: number.diy_ld2410_g7_move_threshold
            name: Soglia Spostamento G7
          - entity: number.diy_ld2410_g8_move_threshold
            name: Soglia Spostamento G8
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: number.diy_ld2410_g0_still_threshold
            name: Soglia Ferma G0
          - entity: number.diy_ld2410_g1_still_threshold
            name: Soglia Ferma G1
          - entity: number.diy_ld2410_g2_still_threshold
            name: Soglia Ferma G2
          - entity: number.diy_ld2410_g3_still_threshold
            name: Soglia Ferma G3
          - entity: number.diy_ld2410_g4_still_threshold
            name: Soglia Ferma G4
          - entity: number.diy_ld2410_g5_still_threshold
            name: Soglia Ferma G5
          - entity: number.diy_ld2410_g6_still_threshold
            name: Soglia Ferma G6
          - entity: number.diy_ld2410_g7_still_threshold
            name: Soglia Ferma G7
          - entity: number.diy_ld2410_g8_still_threshold
            name: Soglia Ferma G8
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: number.diy_ld2410_radar_max_move_distance
            name: Soglia Max Distanza Movimento
          - entity: number.diy_ld2410_radar_max_still_distance
            name: Soglia Max Distanza Fermo
      - type: horizontal-stack
        cards:
          - type: entity
            entity: sensor.diy_ld2410_esp_cpu_speed
            name: CPU Speed
          - type: entity
            entity: sensor.diy_ld2410_esp_free_memory
            name: Free Memory
  - type: horizontal-stack
    cards:
      - type: entity
        entity: sensor.diy_ld2410_radar_firmware_version
        name: Firmvare Version
      - type: entity
        entity: sensor.diy_ld2410_rssi
        name: RSSI
  - type: horizontal-stack
    cards:
      - type: entity
        entity: sensor.diy_ld2410_uptime
        name: Uptime
      - type: entity
        entity: sensor.diy_ld2410_esp_temperature
        name: ESP Tempertature
  - type: horizontal-stack
    cards:
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_zone_1_occupancy
        name: Zone 1
        state_color: true
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_zone_2_occupancy
        name: Zone 2
        state_color: true
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_zone_3_occupancy
        name: Zone 3
        state_color: true
  - type: horizontal-stack
    cards:
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_target
        name: Radar Target Acquisito
        state_color: true
  - type: horizontal-stack
    cards:
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_moving_target
        name: Radar Target Movimento
        state_color: true
      - type: entity
        entity: binary_sensor.diy_ld2410_radar_still_target
        name: Radar Target Fermo
        state_color: true
  - type: horizontal-stack
    cards:
      - type: entity
        entity: sensor.diy_ld2410_radar_moving_distance
        name: Distanza Movimento
        state_color: true
      - type: entity
        name: Distanza Fermo
        state_color: true
        entity: sensor.diy_ld2410_radar_still_distance
----------------------------------------------------------------------
