### ISSUE TITLE
duty_cycle: Spikes in the duty cycle values measuring very slow (0.1 Hz) PWM

### ISSUE THREAD

**Issue by zeirix** [esphome/issues#6228]
### The problem

Hello everybody,

I'm using the `duty_cycle` module to monitor a very slow PWM signal (about 0.1 Hz) from a legacy (likely analog) control system.

The plot shows some spikes in the values, which look too regular in amplitude to come from the measured value:
![grafik](https://github.com/user-attachments/assets/d259bf8c-f0fe-499d-85e0-78ef8677ca07)

Could this be a race condition between the measurement of the signal cycles and the static `update_interval` ?

### Which version of ESPHome has the issue?

2024.8.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp-wrover-kit

### Component causing the issue

duty_cycle

### Example YAML snippet

```yaml
sensor:
  - platform: duty_cycle
    pin: GPIO4
    name: Duty Cycle Sensor
    update_interval: 60s
    state_topic: /esp32/duty
```
