### ISSUE TITLE
Connection refuse in softAP

### ISSUE THREAD

**Issue by Sebclem** [esphome/issues#623]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 
**Affected component:**

https://esphome.io/components/wifi.html 
Soft AP and OTA, Webserver

**Description of problem:**
When my wifi is not rechable, esphome start the softAP, i can connect to it but can't do nothing.
OTA give me `ERROR Connecting to livingroombme.local:8266 failed: [Errno 111] Connection refused`
If i try to acces to the webserver i have the same issue.
This work great in "normal" mode. (Connected to my wifi)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: livingroombme
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "IMERIRR"
  password: ""
  ap: 
    ssid: "livingroombme"
    channel: 4
  reboot_timeout: 0s

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:

web_server:
  port: 80

ota:
i2c:
  sda: 4
  scl: 5
  scan: True
sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 2s

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
