### ISSUE TITLE
Boot sequence hangs until MQTT client component connects

### ISSUE THREAD

**Issue by Alphaemef** [esphome/issues#6236]
### The problem

If MQTT client is configured but can not connect to the server, components that load with a boot priority lower than the MQTT Component. 

I.e:
If both API and MQTT are connected, and MQTT disconnects API continues to work until the reboot teimout. At which point the ESP will startup without API. Once the MQTT connects, the API will connect. 

If API setup_priority is changed to 201, this alleviates the issue. Other components with lower priority do not load either, i.e modbus

### Which version of ESPHome has the issue?

2024.8.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

esp32

### Component causing the issue

MQTT Client Component

### Example YAML snippet

```yaml
mqtt:
  broker: ${broker}
  port: ${port}
  username: ${name}
  password: ${pass}
  discovery_unique_id_generator: mac
  id: mqtt_client
  skip_cert_cn_check: false
  idf_send_async: false
  certificate_authority:  | 
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
```
