### ISSUE TITLE
Unable to flash ESP32-POE

### ISSUE THREAD

**Issue by MaxDucy** [esphome/issues#6238]
### The problem

I'm trying to flash Olimex ESP32-POE to use as an IR Remote Climate. And I keep getting this log when I flashed with ESPHome Web

```
invalid header: 0x20747375
invalid header: 0x20747375
invalid header: 0x20747375
invalid header: 0x20747375
invalid header: 0x20747375
invalid header: 0x20747375
invalid header: 0x20747375
invalid header: 0x20747375
ets Jul 29 2019 12:21:46
```

### Which version of ESPHome has the issue?

2024.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.4.4

### What platform are you using?

ESP32

### Board

Olimex ESP32-POE

### Example YAML snippet

```yaml
esphome:
  name: daikin-server-room
  friendly_name: Daikin IR Server Room

esp32:
  board: esp32-poe
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "something"

ota:
    platform: esphome
    password: "somethingsomething"


ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  manual_ip:
    static_ip: 1xx.xx.x.xxx
    gateway: 1xx.xx.x.xxx
    subnet: xxx.xxx.xxx.0


web_server:
  
remote_transmitter:
  pin: GPIO2
  carrier_duty_percent: 50%

climate:
  - platform: daikin_arc
    name: "Daikin Server Room AC"
```
