### ISSUE TITLE
How to add XL9535 relay board?

### ISSUE THREAD

**Issue by mahnunchik** [esphome/issues#6254]
### The problem

I'm trying to add XL9535 relay board according to the documentation https://esphome.io/components/xl9535.html

But there is no option for XL9535.

<img width="447" src="https://github.com/user-attachments/assets/86dc7ed1-6f9b-4624-b5f6-ea216e387a64">

I don't have any ESP* boards, I'd like to add relay board connected by I2C to Raspberry PI.

### Which version of ESPHome has the issue?

2024.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.9.2

### What platform are you using?

ESP32

### Board

XL9535 relay board, NO ESP

### Component causing the issue

How to connect it?

### Example YAML snippet

```yaml
# Example configuration entry
xl9535:
  - id: xl9535_hub
    address: 0x20

# Individual outputs
switch:
  - platform: gpio
    name: XL9535 Pin 0
    pin:
      xl9535: xl9535_hub
      number: 0
      mode:
        output: true
      inverted: false
```

### Additional information

![photo_2024-09-16_22-00-07](https://github.com/user-attachments/assets/5b8a8b5d-929f-45eb-bc19-2ccc8cda3b42)

My XL9535 relay board
