### ISSUE TITLE
01:42:01][D][sht3xd:079]: Retrying to reconnect the sensor.  

### ISSUE THREAD

**Issue by AbianTang** [esphome/issues#6269]
### The problem

[01:38:57][I][i2c.arduino:096]: Results from i2c bus scan:
[01:38:57][I][i2c.arduino:102]: Found i2c device at address 0x44

01:42:01][D][sht3xd:079]: Retrying to reconnect the sensor.  

delete  frequency: 800khz
  timeout: 10ms

CRC8 Checksum invalid at pos 1! 0xFF != 0xAC，Frequent and repeated reboots

### Which version of ESPHome has the issue?

2024.7.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.7.3

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
i2c:
  sda: D3
  scl: D2
  scan: true
  frequency: 800khz
  timeout: 10ms

delete  frequency: 800khz
  timeout: 10ms

CRC8 Checksum invalid at pos 1! 0xFF != 0xAC
```
