### ISSUE TITLE
UDP binary sensor not working for buttons

### ISSUE THREAD

**Issue by bruxy70** [esphome/issues#6271]
### The problem

I have a binary sensor for a gpio input connected to Hoermann RF receiver. When the button is pressed, the receiver will close the relay (and therefore the gpio binary_sensor) for 0.5s (and then open it again).
When I configure this binary sensor as UDP transmitter, it will not send the signal.
As a workaround, I configure an on_press automation to toggle a relay, and have a template binary sensor to return the relay state. And then use this as UDP transmitter and it works fine (as the binary sensor state will toggle on each 0.5s impulse and stay there).

### Which version of ESPHome has the issue?

2024.9.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.9.2

### What platform are you using?

ESP8266

### Board

sonoff basic + Hoermann RF receiver

### Component causing the issue

UDP

### Example YAML snippet

```yaml
udp:
  encryption: !secret udp_encryption_key
  binary_sensors:
    - switch_garaz

binary_sensor:
  - platform: gpio
    id: btn_garaz
    pin:
      number: ${button_gpio}
      mode: INPUT_PULLUP
      inverted: True
```
