### ISSUE TITLE
NSPanel FW 2024.9.1 Update failing

### ISSUE THREAD

**Issue by callmebackdraft** [esphome/issues#6278]
### The problem

When trying to update to 2024.9.1 it fails asking me to file a bug report

config is in the yaml drop 

### Which version of ESPHome has the issue?

2023.11.6 > 2024.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.9.3

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
# Note: this may not be needed if the pull request has been merged.
# Check https://github.com/esphome/esphome/pull/2956 for current status.
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h

substitutions:
  room: woonkamer
  entity1: light.table_lights
  thermo_heat: input_boolean.tut_thermo_fire
  thermo_cool: input_boolean.tut_thermo_cool
  tft_url: http://192.168.2.15:8123/local/nspanel/NSPanel_Woonkamer.tft

esphome:
  name: nspanel-${room}

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0
  logs:
    rtttl: none
    # homeassistant: none
    # binary_sensor: none
    # nextion: none
    ledc.output: none
    resistance: none
    ntc: none
    sensor: none
    climate: none
    # homeassistant.sensor: none

ota:
  platform: esphome
# Call Services: Play rtttl string and TFT Upload
api:
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda "return song_str;"
    - service: upload_tft
      then:
        - lambda: "id(nspanel)->upload_tft();"

binary_sensor:
  # binary_sensor: Read Button1 Component and Toggle Entity1
  - platform: nextion
    id: button1
    page_id: 0
    component_id: 1
    on_press:
      - homeassistant.service:
          service: homeassistant.toggle
          data:
            entity_id: $entity1

  # binary_sensor: Match Button1 Component's State to Entity1's State
  - platform: homeassistant
    id: entity1
    entity_id: $entity1
    on_state:
      - lambda: 'id(nspanel).send_command_printf("main.button1.val=%d",id(entity1).state);'

  # binary_sensor: Entity1's Up/Down Buttons
  - platform: nextion
    id: button1_up
    page_id: 0
    component_id: 2

    # Add 10% to Entity1's Brightness
    on_press:
      - homeassistant.service:
          service: homeassistant.turn_on
          data:
            entity_id: $entity1
          data_template:
            brightness_step_pct: "10"

  - platform: nextion
    id: button1_dwn
    page_id: 0
    component_id: 3

    # Sub 10% from Entity1's Brightness
    on_press:
      - homeassistant.service:
          service: homeassistant.turn_on
          data:
            entity_id: $entity1
          data_template:
            brightness_step_pct: "-10"

  # binary_sensor: Thermostat Controls
  - platform: nextion
    id: my_thermo_button
    page_id: 0
    component_id: 4
    on_state:
      - if:
          condition:
            binary_sensor.is_on: my_thermo_button
          then:
            - climate.control:
                id: my_thermostat
                mode: HEAT_COOL
      - if:
          condition:
            binary_sensor.is_off: my_thermo_button
          then:
            - climate.control:
                id: my_thermostat
                mode: "OFF"

  - platform: nextion
    id: thermo_up
    page_id: 0
    component_id: 5
    on_press:
      - climate.control:
          id: my_thermostat
          target_temperature_low: !lambda |-
            return id(my_thermostat).target_temperature_low + 0.5;
          target_temperature_high: !lambda |-
            return id(my_thermostat).target_temperature_high + 0.5;

  - platform: nextion
    id: thermo_dwn
    page_id: 0
    component_id: 6
    on_press:
      - climate.control:
          id: my_thermostat
          target_temperature_low: !lambda |-
            return id(my_thermostat).target_temperature_low - 0.5;
          target_temperature_high: !lambda |-
            return id(my_thermostat).target_temperature_high - 0.5;

  # binary_sensor: Page.Thermo's High-Low Buttons
  - platform: nextion
    id: thermostat_low_up
    page_id: 1
    component_id: 1
    on_click:
      - climate.control:
          id: my_thermostat
          target_temperature_low: !lambda |-
            return id(my_thermostat).target_temperature_low + 0.5;

  - platform: nextion
    id: thermostat_low_dwn
    page_id: 1
    component_id: 2
    on_click:
      - climate.control:
          id: my_thermostat
          target_temperature_low: !lambda |-
            return id(my_thermostat).target_temperature_low - 0.5;

  - platform: nextion
    id: thermostat_high_up
    page_id: 1
    component_id: 3
    on_click:
      - climate.control:
          id: my_thermostat
          target_temperature_high: !lambda |-
            return id(my_thermostat).target_temperature_high + 0.5;

  - platform: nextion
    id: thermostat_high_dwn
    page_id: 1
    component_id: 4
    on_click:
      - climate.control:
          id: my_thermostat
          target_temperature_high: !lambda |-
            return id(my_thermostat).target_temperature_high - 0.5;

  # binary_sensor: Physical Buttons and Relays
  - platform: gpio
    id: panel_button_relay1
    name: NSP ${room} button1
    pin:
      number: 14
      inverted: true
    on_click:
      - switch.toggle: relay1

  - platform: gpio
    id: panel_button_relay2
    name: NSP ${room} button2
    pin:
      number: 27
      inverted: true
    on_click:
      - switch.toggle: relay2

  # binary_sensor: Any Button Beep
  - platform: nextion
    id: beeper
    page_id: 9
    component_id: 1
    on_press:
      - rtttl.play: "beep:d=32,o=7,b=100: c"

sensor:
  - platform: homeassistant
    entity_id: $entity1
    id: button1_brt
    internal: true
    attribute: brightness
    filters:
      - lambda: return (x / 255) * 100;
    on_value:
      then:
        - lambda: 'id(nspanel).set_component_text_printf("light1level", "%.0f %%", x );'
        - lambda: |-
            if (id(button1_brt)>0) {
              id(nspanel).send_command_printf("main.button1.val=1");
            }

  # sensor: Low & High temperatures from Climate
  - platform: template
    id: my_low_trg
    lambda: |-
      return id(my_thermostat).target_temperature_low;
    update_interval: 0.5s
    on_value:
      - lambda: 'id(nspanel).set_component_text_printf("thermolowtemp", "%.1f", x);'

  - platform: template
    id: my_high_trg
    lambda: |-
      return id(my_thermostat).target_temperature_high;
    update_interval: 0.5s
    on_value:
      - lambda: 'id(nspanel).set_component_text_printf("thermohightemp", "%.1f", x);'

  # sensor: Read internal Temp Sensor
  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  - platform: adc
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 12db

  - platform: ntc
    id: temperature
    name: NSP ${room} Temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    on_value:
      - lambda: 'id(nspanel).set_component_text_printf("ThermValue", "%.1f ""\xb0""C", x);'

# switch: Panel Buttons to control Relays
switch:
  - platform: gpio
    id: relay1
    name: NSP ${room} relay1
    icon: mdi:electric-switch
    pin:
      number: 22
    # switch Relay1 Bar On/Off - Add one per Page
    on_turn_on:
      - lambda: id(nspanel).set_component_value("main.LeftBottomBtn", 1);
    on_turn_off:
      - lambda: id(nspanel).set_component_value("main.LeftBottomBtn", 0);

  - platform: gpio
    id: relay2
    name: NSP ${room} relay2
    icon: mdi:electric-switch
    pin:
      number: 19
    # switch Relay2 Bar On/Off - Add one per Page
    on_turn_on:
      - lambda: id(nspanel).set_component_value("main.RightBottomBtn", 1);
    on_turn_off:
      - lambda: id(nspanel).set_component_value("main.RightBottomBtn", 0);

  # switch: Display Power Pin 4 On
  - platform: gpio
    id: panel_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON

# Display Brightness Slider for HA
number:
  platform: template
  name: NSP ${room} brightness
  id: brightness
  update_interval: never
  entity_category: config
  unit_of_measurement: "%"
  optimistic: true
  min_value: 0
  max_value: 100
  step: 10
  initial_value: 20
  on_value:
    - lambda: "id(nspanel).set_backlight_brightness(x/100);"

# ESP Thermostat Setup
climate:
  - platform: thermostat
    id: my_thermostat
    name: NSP ${room} thermostat
    sensor: temperature
    min_cooling_off_time: 0s
    min_cooling_run_time: 0s
    min_heating_off_time: 0s
    min_heating_run_time: 0s
    min_idle_time: 0s
    visual:
      min_temperature: 15 °C
      max_temperature: 30 °C

    ### Updated for ESPHome v2022.10.0 Onwards
    default_preset: Home                      ### NEW! Use this to set Preset
    # on_boot_restore_from: memory            ### Use this to "Restore From Memeory" (A Saved State) OR...
    on_boot_restore_from: default_preset      ### Use this to set Preset to start on every Boot
    preset:
      - name: Home
        default_target_temperature_low: 23.0
        default_target_temperature_high: 26.0
        mode: AUTO
    ###########################################

    heat_action:
      - homeassistant.service:
          service: homeassistant.turn_on
          data:
            entity_id: ${thermo_heat}
    cool_action:
      - homeassistant.service:
          service: homeassistant.turn_on
          data:
            entity_id: ${thermo_cool}
    idle_action:
      - homeassistant.service:
          service: homeassistant.turn_off
          data:
            entity_id: ${thermo_heat}
      - homeassistant.service:
          service: homeassistant.turn_off
          data:
            entity_id: ${thermo_cool}
    on_state:
      then:
        - lambda: |-
            if (id(my_thermostat).mode != 0) {
              id(nspanel).set_component_value("main.thermo", 1);
            } else {
              id(nspanel).set_component_value("main.thermo", 0);
            };
        # Find the Half-way point between Target High and Target Low Temperature
        - lambda: 'id(nspanel).set_component_text_printf("main.thermotemp", "%.1f ""\xb0""C", ((id(my_thermostat).target_temperature_high - id(my_thermostat).target_temperature_low)/2) + id(my_thermostat).target_temperature_low);'

# Display Setup
display:
  - platform: nextion
    id: nspanel
    uart_id: tf_uart
    tft_url: ${tft_url}
    on_setup:
      - rtttl.play: "KnRider:d=4,o=6,b=120:16d.5,32d#.5,32d.5,8a.5"
      - lambda: |-
          id(nspanel).goto_page("main");

# Ringtone support
rtttl:
  id: buzzer
  output: buzzer_out

# Beeper Output
output:
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

# UART for Display
uart:
  id: tf_uart
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200

# ESP Restart button
button:
  - platform: restart
    name: NSP ${room} restart
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.9.1
INFO Reading configuration /config/esphome/nspanel-woonkamer.yaml...
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1018, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1005, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 485, in command_run
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 194, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 206, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 684, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 186, in wrapped
    await coro(conf)
  File "/data/external_components/b5254113/esphome/components/nextion/display.py", line 92, in to_code
    await display.register_display(var, config)
  File "/esphome/esphome/components/display/__init__.py", line 123, in register_display
    await cg.register_component(var, config)
  File "/esphome/esphome/cpp_helpers.py", line 53, in register_component
    raise ValueError(
ValueError: Component ID nspanel was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.
```
