### ISSUE TITLE
Sprinkler - Valve_overlap doesn't seem to work, Main valve cycles when switching valves

### ISSUE THREAD

**Issue by andrewwong2000** [esphome/issues#6279]
### The problem

I have an esp32 running esphome sprinkler. The configuration is 8 station valves, 1 main valve with no pump.
esphome version is 2024.9.1 Sep 27 2024, 15:14:57

I am expecting Zone 1 -> 2 to keep Zone 1 open for 5 seconds when I switch to Zone 2.. but it doesn't seem to do this.

Also I notice that the Main valve relay blinks when I change zones.. instead of staying on.

Appreciate any help. Thank you.

My config is like this:

.
.
.

# Define your relays for the pump and watering zones
switch:
  - platform: restart
    name: "Restart $devicename"

  - platform: gpio
    id: main_relay
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    pin: GPIO32
    inverted: true
    name: "Main Solenoid"
    
  - platform: gpio
    id: zone1
    pin: GPIO33
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    inverted: true
    name: "Zone 1"
    
  - platform: gpio
    id: zone2
    pin: GPIO25
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    inverted: true
    name: "Zone 2"

.
.
.

sprinkler:
  - id: $devicename
    main_switch: "Sprinklers"
    auto_advance_switch: "Zone Auto Advance"
    reverse_switch: "Zone Reverse"
    valve_overlap: 5s
    manual_selection_delay: 2s
    next_prev_ignore_disabled: true
    valves:
      - valve_switch: "Front Verge 1"
        enable_switch: "Enable Front Lawn"
        pump_switch_id: main_relay
        run_duration: 900s
        valve_switch_id: zone1        
      - valve_switch: "Front Lawn 2"
        enable_switch: "Enable Front Lawn"
        pump_switch_id: main_relay
        run_duration: 900s
        valve_switch_id: zone2        

### Which version of ESPHome has the issue?

2024.9.1 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.9.3

### What platform are you using?

ESP32-IDF

### Component causing the issue

sprinkler

### Example YAML snippet

```yaml
substitutions:
  name: esphome-web-122bac
  friendly_name: ESPHome Sprinkler
  devicename: home_sprinkler
  upper_devicename: "Home Sprinkler"
  uom: Min # this overrides the uom in sprinkler -> run_duration 
  esphome_name: home_sprinkler
  sensor_update_frequency: 1s
  esphome_board: esp32-2MB


esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'


esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

# Define your relays for the pump and watering zones
switch:
  - platform: restart
    name: "Restart $devicename"

  - platform: gpio
    id: main_relay
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    pin: GPIO32
    inverted: true
    name: "Main Solenoid"
    
  - platform: gpio
    id: zone1
    pin: GPIO33
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    inverted: true
    name: "Zone 1"
    
  - platform: gpio
    id: zone2
    pin: GPIO25
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    inverted: true
    name: "Zone 2"
    
  - platform: gpio
    id: zone3
    pin: GPIO26
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    inverted: true
    name: "Zone 3"
    
  - platform: gpio
    id: zone4
    pin: GPIO27
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    inverted: true
    name: "Zone 4"
    
  - platform: gpio
    id: zone5
    pin: GPIO23
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    inverted: true
    name: "Zone 5"
    
  - platform: gpio
    id: zone6
    pin: GPIO22
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    inverted: true
    name: "Zone 6"
    
  - platform: gpio
    id: zone7
    pin: GPIO21
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    inverted: true
    name: "Zone 7"

  - platform: gpio
    id: zone8
    pin: GPIO19
    restore_mode: RESTORE_DEFAULT_OFF # Prevents GPIO pin from going high during boot
    internal: true # Prevents GPIO switch NAME from showing up in Home Assistant
    inverted: true
    name: "Zone 8"

sprinkler:
  - id: $devicename
    main_switch: "Sprinklers"
    auto_advance_switch: "Zone Auto Advance"
    reverse_switch: "Zone Reverse"
    valve_overlap: 5s
    manual_selection_delay: 2s
    next_prev_ignore_disabled: true
    valves:
      - valve_switch: "Front Verge 1"
        enable_switch: "Enable Front Lawn"
        pump_switch_id: main_relay
        run_duration: 900s
        valve_switch_id: zone1        
      - valve_switch: "Front Lawn 2"
        enable_switch: "Enable Front Lawn"
        pump_switch_id: main_relay
        run_duration: 900s
        valve_switch_id: zone2        
      - valve_switch: "Front Lawn 3"
        enable_switch: "Enable Front Lawn"
        pump_switch_id: main_relay
        run_duration: 900s
        valve_switch_id: zone3
      - valve_switch: "Front Edge 4"
        enable_switch: "Enable Front Lawn"
        pump_switch_id: main_relay
        run_duration: 900s
        valve_switch_id: zone4
      - valve_switch: "Back Lawn 5"
        enable_switch: "Enable Back Lawn"
        pump_switch_id: main_relay
        run_duration: 900s
        valve_switch_id: zone5
      - valve_switch: "Back Lawn 6"
        enable_switch: "Enable Back Lawn"
        pump_switch_id: main_relay
        run_duration: 900s
        valve_switch_id: zone6
      - valve_switch: "Back Edge 7"
        enable_switch: "Enable Back Lawn"
        pump_switch_id: main_relay
        run_duration: 900s
        valve_switch_id: zone7
      - valve_switch: "Back Edge 8"
        enable_switch: "Enable Back Lawn"
        pump_switch_id: main_relay
        run_duration: 900s
        valve_switch_id: zone8

###############################################
# Text sensors with general information.
###############################################
text_sensor:
  - platform: version # Expose ESPHome version as sensor.
    name: $esphome_name ESPHome Version
    hide_timestamp: false
  - platform: wifi_info
    ip_address:
      name: "$esphome_name IP"
    ssid:
      name: "$esphome_name SSID"
    bssid:
      name: "$esphome_name BSSID"

# Expose Time Remaining as a sensor.
  - platform: template
    id: time_remaining
    name: $upper_devicename Time Remaining
    update_interval: $sensor_update_frequency
    icon: "mdi:timer-sand"
    lambda: |-
      int seconds = round(id($devicename).time_remaining_active_valve().value_or(0));
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;

      std::string result;

      if (days > 0) {
          result += std::to_string(days) + "d ";
      }
      if (hours > 0) {
          result += std::to_string(hours) + "h ";
      }
      if (minutes > 0) {
          result += std::to_string(minutes) + "m ";
      }
      result += std::to_string(seconds) + "s";

      return result;
    




  # Expose Progress Percent as a sensor.
  - platform: template
    id: progress_percent
    name: $upper_devicename Progress %
    update_interval: $sensor_update_frequency
    icon: "mdi:progress-clock"
    lambda: |-
      int progress_percent = round(((id($devicename).valve_run_duration_adjusted(id($devicename).active_valve().value_or(0)) - id($devicename).time_remaining_active_valve().value_or(0)) * 100 / id($devicename).valve_run_duration_adjusted(id($devicename).active_valve().value_or(0))));
      std::string progress_percent_as_string = std::to_string(progress_percent);
      return progress_percent_as_string +"%";

  # Expose Valve Status as a sensor.
  - platform: template
    id: valve_status
    name: $upper_devicename Status
    update_interval: never
    icon: "mdi:information-variant"

  - platform: template # Expose the board type as a sensor
    id: espboard_type
    icon: "mdi:developer-board"
    name: $esphome_name ESPBoard
    lambda: |-
      return to_string("${esphome_board}");

sensor:
  # Uptime sensor.
  - platform: uptime
    name: $upper_devicename Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: $upper_devicename WiFi Signal
    update_interval: 60s

button:
  - platform: template
    id: sprinkler_pause
    name: "Pause"
    icon: "mdi:pause"
    on_press:
      then:
        - if:
            condition:
              # Check if the sprinkler is currently running
              lambda: 'return id($devicename).paused_valve().has_value();'
            then:
              - text_sensor.template.publish:
                  id: valve_status
                  state: "Paused"
              - sprinkler.pause: $devicename
            else:
              - text_sensor.template.publish:
                  id: valve_status
                  state: "Running"
              - sprinkler.resume: $devicename
  - platform: template
    id: sprinkler_next_station
    name: "Next Station"
    icon: "mdi:next"
    on_press:
      then:
        - if:
            condition:
              # Check if the sprinkler is currently running
              lambda: 'return id($devicename).paused_valve().has_value();'
            then:
              - sprinkler.next_valve: $devicename
            else:
              - sprinkler.next_valve: $devicename
```

### Anything in the logs that might be useful for us?

```txt

16:06:12	[D]	[sprinkler:1562]	Valve cycle interrupted - NOT flagging valve as complete and stopping current valve
16:06:12	[D]	[switch:016]		'Zone 6' Turning OFF.
16:06:12	[D]	[switch:055]		'Zone 6': Sending state OFF
16:06:12	[D]	[switch:016]		'Main Solenoid' Turning OFF.
16:06:12	[D]	[switch:055]		'Main Solenoid': Sending state OFF
16:06:12	[D]	[sprinkler:1427]	USER is starting valve 6 for 900 seconds, cycle 1 of 1
16:06:12	[D]	[switch:012]		'Zone 7' Turning ON.
16:06:12	[D]	[switch:055]		'Zone 7': Sending state ON
16:06:12	[D]	[switch:012]		'Main Solenoid' Turning ON.
16:06:12	[D]	[switch:055]		'Main Solenoid': Sending state ON
16:06:12	[D]	[switch:055]		'Back Lawn 6': Sending state OFF
16:06:12	[D]	[switch:055]		'Back Edge 7': Sending state ON
```
