### ISSUE TITLE
Erratic behavior of dhcp hostname while resuming from fallback AP hostanme goes back to esp32-<ENDOFMYMAC>.lan

### ISSUE THREAD

**Issue by ouinouin** [esphome/issues#6280]
### The problem

Hi, 
i m not 100% sure its the only case where the hostname doesnt follow the  esphome "name" directive in the config file.
i have the same behavior if i force the .lan or leave the naming with .local.
my guessing is that when my ap has some issues with wifi (thanks iphone that triggers erratic behavior of wifi on my openwrt router), then alle my esphomes (5 in total) goes to fallback accespoint mode , then i generally need to restart the wifi of my router for them to reassociate. they generally does reassociate well, but then instead of talking their coorect names like "linky.lan" "epever.lan" "inverter.lan" , they reappear with a hostname like ESP32--<ENDOFMYMACADDR>.lan , my wild guess, (i absolutely didnt dig further than doing a couple of tests, i d like to have enough competencies to dig into the sdk) is that at boot, esphome behaves correctly and take the name to make the dhcp query , but for any reason, while reconnecting in some occasions like coming back from ap mode, then ther might be some hardcoded hostanme value deep in the ESP sdk that resurfaces.
ofr info, while having this strange behavior in esphome, all the tasmota behaves correctly in the same conditions.

### Which version of ESPHome has the issue?

2024.9.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.9

### What platform are you using?

ESP32

### Board

M5 stack, and various other esp32 boards exhibit the same behavior

### Component causing the issue

wifi

### Example YAML snippet

```yaml
esphome:
  name: "linky-nicol"
  friendly_name: "linky-nicol"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    

# Enable logging
logger:
  baud_rate: 0

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "blablable"

ota:
  - platform: esphome
    password: "blablabla"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".lan"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Linky-Nicol Fallback Hotspot"
    password: "blablabla"
  #use_address: "192.168.9.105"
captive_portal:

button:
  - platform: restart
    name: "restart Linky esp32"


# Example configuration entry
uart:
  id: uart_bus
  rx_pin: GPIO6
  tx_pin: GPIO7
  baud_rate: 9600
  parity: EVEN
  data_bits: 7

teleinfo:
  id: myteleinfo
  update_interval: 5s
  historical_mode: false

sensor:
  - platform: teleinfo
    tag_name: "EAST"
    name: "Linky Energie Soutirée"
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: teleinfo
    tag_name: "IRMS1"
    name: "Linky Courant Efficace"
    unit_of_measurement: A
    device_class: current
    state_class: measurement
  # Tension Efficace, phase 1
  - platform: teleinfo
    tag_name: "URMS1"
    name: "Linky Tension Efficace"
    unit_of_measurement: V
    device_class: voltage
    state_class: measurement
  # Puissance app. de référence
  # - platform: teleinfo
  #   tag_name: "PREF"
  #   name: "Linky Puissance Apparente Référence"
  #   state_class: measurement
  #   device_class: apparent_power
  #   unit_of_measurement: VA
  #   filters:
  #     - multiply: 1000
  # Puissance app. de coupure
  - platform: teleinfo
    tag_name: "PCOUP"
    name: "Linky Puissance Apparente Coupure"
    state_class: measurement
    device_class: apparent_power
    unit_of_measurement: VA
    filters:
      - multiply: 1000
  # Puissance app. Instantanée Soutirée
  - platform: teleinfo
    tag_name: "SINSTS"
    name: "Linky Puissance Apparente Instantanée Soutirée"
    unit_of_measurement: VA
    state_class: measurement
    device_class: apparent_power
  # Puissance app. max. soutirée
  # - platform: teleinfo
  #   tag_name: "SMAXSN"
  #   name: "Linky Puissance Apparente Maximale Soutirée"
  #   unit_of_measurement: VA
  #   state_class: measurement
  #   device_class: apparent_power
  # Point n de la courbe de charge active soutirée
  - platform: teleinfo
    tag_name: "CCASN"
    name: "Linky Puissance Active Soutirée"
    unit_of_measurement: W
    state_class: measurement
    device_class: power
  # Point n-1 de la courbe de charge active soutirée
  - platform: teleinfo
    tag_name: "CCASN-1"
    name: "Linky Puissance Active Soutirée N-1"
    unit_of_measurement: W
    state_class: measurement
    device_class: power
```
