### ISSUE TITLE
RGBWW Light + MQTT - Invalid color mode 'cwww' received

### ISSUE THREAD

**Issue by nima-1102** [esphome/issues#6281]
### The problem

RGB works without any problems with the RGBWW Light, but as soon as you want to set the cold/warm white temperature via the Homeassistant GUI, the lamp temperature changes as desired, but a warning appears. The last RGB color is then displayed as the current light color and not the current cold/warm white temperature.

### Which version of ESPHome has the issue?

2024.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.9.3

### What platform are you using?

BK72XX

### Board

WBLC5

### Component causing the issue

mqtt / rgbww

### Example YAML snippet

```yaml
bk72xx:
  board: generic-bk7231t-qfn32-tuya


mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password


sm2135:
  clock_pin: P26
  data_pin: P24
  rgb_current: 15mA
  cw_current: 35mA
  separate_modes: false


output:
  - platform: sm2135
    id: output_blue
    channel: 0
    min_power: 0.2
    max_power: 0.9
    zero_means_zero: true
  - platform: sm2135
    id: output_green
    channel: 1
    min_power: 0.2
    max_power: 0.9
    zero_means_zero: true
  - platform: sm2135
    id: output_red
    channel: 2
    min_power: 0.2
    max_power: 0.9
    zero_means_zero: true
  - platform: sm2135
    id: output_warm
    channel: 3
    min_power: 0.2
    max_power: 0.9
    zero_means_zero: true
  - platform: sm2135
    id: output_cold
    channel: 4
    min_power: 0.2
    max_power: 0.9
    zero_means_zero: true


light:
  - platform: rgbww
    id: light_rgbww
    name: "Test Light"
    color_interlock: true
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
    default_transition_length: 0s
```

### Anything in the logs that might be useful for us?

```txt
logger: homeassistant.components.mqtt.light.schema_json
Source: components/mqtt/light/schema_json.py:365
integration: MQTT (documentation, issues)
First occurred: September 27, 2024 at 23:56:21 (3 occurrences)
Last logged: 00:00:00

Invalid color mode 'cwww' received for entity light.test_light
```

### Additional information

MQTT Payload of the Warm / Cold Temp change: 
`{"color_mode":"cwww","state":"ON","brightness":133,"color":{"c":0,"w":255}}`

color_interlock is required for the SM2135 LED driver.

**Comment by ssieb** [comment]
We need more information.  That error message is from HA, the mqtt integration.  It's not an esphome error.
Is that mqtt payload what is getting sent to esphome?
Is the light changing to what you want, but the color displayed in HA is wrong?

**Comment by nima-1102** [comment]
> We need more information. That error message is from HA, the mqtt integration. It's not an esphome error. Is that mqtt payload what is getting sent to esphome? Is the light changing to what you want, but the color displayed in HA is wrong?

This is the payload which, after I have changed the light from e.g. OFF or RGB to cold/warm white temperature via the Home Assistant GUI, ESPHome stores as a state in mqtt under "lamp-gu10-2/light/test-light/state". Yes, the light changes color temperature, but color displayed in HA is wrong because the data is not changed due to "Invalid color mode".

I don't know if ESPHome sets the color_mode incorrectly or if the color_mode is just not defined in Home Assistant.

**Comment by nima-1102** [comment]
That's still a problem.

**Comment by kquinsland** [comment]
I am also getting this error from one of my ESPHome lights:

```log
WARNING (MainThread) [homeassistant.components.mqtt.light.schema_json] Invalid color mode 'cwww' received for entity light.monitor_task_lamp_primary               
```

And from the `homeassistant/light/monitor-task-lamp/primary/config` topic:

```json
{
    "schema": "json",
    "clrm": true,
    "supported_color_modes": [
        "color_temp"
    ],
    "brightness": true,
    "min_mirs": 153.8462,
    "max_mirs": 370.3704,
    "name": "Primary",
    "ic": "mdi:wall-sconce-flat-outline",
    "stat_t": "monitor-task-lamp/light/primary/state",
    "cmd_t": "monitor-task-lamp/light/primary/command",
    "avty_t": "monitor-task-lamp/status",
    "uniq_id": "deadbeefcafe-light-3f562d65",
    "obj_id": "monitor-task-lamp_primary",
    "dev": {
        "ids": "deadbeefcafe",
        "name": "Monitor Task Lamp",
        "sw": "1.0.374fa35 (ESPHome 2025.12.7)",
        "mdl": "monitor-task-lamp",
        "mf": "kquinsland",
        "sa": "Desk",
        "cns": [
            [
                "mac",
                "deadbeefcafe"
            ]
        ]
    }
}
```

It's not clear to me where the `cwww` aspect is coming from? 

For what it's worth, the light has this yaml config:

```yaml
light:
  - name: "Primary"
    platform: cwww
    id: leds
    icon: "mdi:wall-sconce-flat-outline"
    cold_white: out_pwm_cw
    warm_white: out_pwm_ww
    warm_white_color_temperature: 2700K
    cold_white_color_temperature: 6500K
    constant_brightness: true
```

This is with ESPHome `2025.12.7` and Home Assistant `2026.1.2`
