### ISSUE TITLE
RGBWW Light + MQTT - Exception in _state_received

### ISSUE THREAD

**Issue by nima-1102** [esphome/issues#6282]
### The problem

When the ESPHome device boots, an incomplete MQTT payload is set for the RGBWW light, which triggers an error in Home Assistant. The light should be turned off in this example, so the state is missing in the payload.

### Which version of ESPHome has the issue?

2024.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.9.3

### What platform are you using?

BK72XX

### Board

WBLC5

### Component causing the issue

mqtt / rgbww

### Example YAML snippet

```yaml
bk72xx:
  board: generic-bk7231t-qfn32-tuya


mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password


sm2135:
  clock_pin: P26
  data_pin: P24
  rgb_current: 15mA
  cw_current: 35mA
  separate_modes: false


output:
  - platform: sm2135
    id: output_blue
    channel: 0
    min_power: 0.2
    max_power: 0.9
    zero_means_zero: true
  - platform: sm2135
    id: output_green
    channel: 1
    min_power: 0.2
    max_power: 0.9
    zero_means_zero: true
  - platform: sm2135
    id: output_red
    channel: 2
    min_power: 0.2
    max_power: 0.9
    zero_means_zero: true
  - platform: sm2135
    id: output_warm
    channel: 3
    min_power: 0.2
    max_power: 0.9
    zero_means_zero: true
  - platform: sm2135
    id: output_cold
    channel: 4
    min_power: 0.2
    max_power: 0.9
    zero_means_zero: true


light:
  - platform: rgbww
    id: light_rgbww
    name: "Light"
    color_interlock: true
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
    default_transition_length: 0s
```

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.mqtt.client
Source: util/logging.py:95
integration: MQTT (documentation, issues)
First occurred: 00:00:00 (1 occurrences)
Last logged: 00:00:00

Exception in _state_received when handling msg on 'lampe-gu10-2/light/licht/state': '{"color":{}}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 1276, in _message_callback msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 420, in _state_received if values["state"] == "ON": ~~~~~~^^^^^^^^^ KeyError: 'state'
```

### Additional information

MQTT Payload on boot: `{"color":{}}`
