### ISSUE TITLE
MQTT not working in AP wifi mode.

### ISSUE THREAD

**Issue by yougin18** [esphome/issues#6285]
### The problem

Hi. ESP32 start as AP wifi and publish some mqtt.  Android phone connect  to esp32 
 and starts mqtt broker. But mqtt broker not receives any messages from esp32 and even not connect with esphome. But if smartphone act as access point then all works fine.When both devices connected to wifi router, mqtt works fine too. Is it normal and broker must work on access point ?

### Which version of ESPHome has the issue?

2024.9.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

without

### What platform are you using?

ESP32

### Board

ESP32-C3

### Component causing the issue

MQTT

### Example YAML snippet

```yaml
esphome:
  name: airm2m-esp32c3
 
esp32:
  board: airm2m_core_esp32c3
  framework:
    type: arduino



wifi:
  ap:
    ssid: "Hotspot"
    password: "W1PBGyrokfLz"

  
mqtt:
  broker: 192.168.4.100
  port : 1883
  


sensor:

  - platform: adc
    pin: GPIO4
    name: "MQ2 Smoke Sensor"
    update_interval: 9s
    id: raam_voor
    raw: true
    on_value:
      - mqtt.publish:
          topic: "sensors"
          payload: !lambda |-
            return esphome::to_string(id(raam_voor).state);
```
