### ISSUE TITLE
CST816S - component setup fails if the touchscreen controller is in standby state

### ISSUE THREAD

**Issue by dsolera** [esphome/issues#6293]
### The problem

The CST816 touchscreen component, during setup() and particularly continue_setup(), reads a register from the I2C bus asking the touchsreen controller its chip ID register. If this read fails, the component is marked as failed and no further action can be done to recover it.

The problem is that the CST816S chip (the one I'm using) enters a **standby state** after 2 seconds of touch inactivity. When in this mode, the chip **does not** respond to I2C commands until it is awaken by a touch ([see datasheet](https://files.waveshare.com/upload/5/51/CST816S_Datasheet_EN.pdf)).

Thus, initialization of the component **always fails**, unless you **keep tapping on the screen until the component is loaded**. If the component is initialized correctly, then touch works fine indefinitely. Moreover, when the chip is in standby, it doesn't even appear in I2C bus scans.

I tried checking the source code of the component and it appears that the chip ID is not really used, so maybe it could be possible to accept it via config and, if provided, to avoid asking the chip ID on setup or maybe just issuing a warning without marking the component as failed. Unfortunately I'm not skilled enough to provide a MR.

I'm not sure if other variants of this chip have the same issue.

### Which version of ESPHome has the issue?

2024.9.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

nodemcu-32s

### Component causing the issue

cst816

### Example YAML snippet

```yaml
i2c:
  - id: i2c_bus0
    sda: GPIO21
    scl: GPIO4
    scan: true

touchscreen:
  platform: cst816
  id: touchscreen0
  i2c_id: i2c_bus0
  interrupt_pin: GPIO23
  reset_pin: GPIO32
  address: 0x15
```
