### ISSUE TITLE
Since summer 1 update on 2 broke my reading of temperature sensor

### ISSUE THREAD

**Issue by Frazou1** [esphome/issues#6297]
### The problem

Since summer we got many update and 1 update on 2 broke reading of temperature sensor. The last one from september 29 broke again the sensor and before this one they work fine.

### Which version of ESPHome has the issue?

Add-on version: 2024.9.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

 System: Home Assistant OS 13.1  (amd64 / qemux86-64)  Home Assistant Core: 2024.10.0  Home Assistant Supervisor: 2024.09.1

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

platform: dallas_temp

### Example YAML snippet

```yaml
esphome:
  name: esp-pool
  friendly_name: ESP_Pool

esp8266:
  board: esp01_1m

one_wire:
  - platform: gpio
    pin: GPIO2

sensor:
  - platform: dallas_temp
    address: 0x2b0000006b68e128
    name: "Temperature Piscine"
    id: temp

  - platform: template
    name: "Temperature_F"
    id: temperature_f
    lambda: return id(temp).state * 9/5+32;
    update_interval: 3s
```

### Anything in the logs that might be useful for us?

```txt
[09:51:40][D][sensor:093]: 'Temperature_F': Sending state nan  with 1 decimals of accuracy
[09:52:14][W][component:170]: Component dallas_temp.sensor cleared Warning flag
[09:52:14][W][dallas.temp.sensor:074]: 'Temperature Piscine' - reading scratch pad failed bus reset
[09:52:14][W][component:157]: Component dallas_temp.sensor set Warning flag: bus reset failed
```
