### ISSUE TITLE
Changing wifi reboot_timeout takes no effect

### ISSUE THREAD

**Issue by Garfield-Z** [esphome/issues#6320]
### The problem

Changing reboot_timeout to 3min under wifi: section did not work, the device still reboot in 15min (default) after losing wifi connection. 

### Which version of ESPHome has the issue?

2024.9.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.1

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

wifi

### Example YAML snippet

```yaml
esphome:
  name: esp32-wrover-e-1
  platformio_options:
    # board_upload.flash_size: 16MB
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216
    board_build.partitions: "../../../config/esphome/custom_partitions_16M.csv"
  on_boot:
    priority: 600
    then:
    - light.turn_on:
        id: back_light
        brightness: 50%

esp32:
  board: esp32dev
  framework:
    type: arduino
  flash_size: 16MB

# Enable logging
logger:
  level: DEBUG
  logs:
    esp32_hall: WARN

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 3min

captive_portal:
```
