### ISSUE TITLE
ESP32 S3 Devkit C1 N16R8, PSRAM not available issue

### ISSUE THREAD

**Issue by Pippisbruffi** [esphome/issues#6323]
### The problem

I have an ESP32 S3 devkit c1, with the chip ESP32 S3 WROOM-1 N16R8. Bought it on amazon.
According to specs, this board should have 8MB octal PSRAM (https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf?fbclid=IwZXh0bgNhZW0CMTAAAR3ryTziZRIMpcfKcU-akfbPZaN9pxXm8lTWps2fhamjYP7o9QXbzWqfy5Q_aem_usxq7OwijM-jg0wNH5VvmA)
Anyway, when I use it in esphome, the log reports

PSRAM:
Available: NO

I attach my full config.

### Which version of ESPHome has the issue?

2024.9.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

ESP32 S3 Devkit C1 (N16R8)

### Example YAML snippet

```yaml
esphome:
  name: assist10
  friendly_name: Assist10

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WcSHYdgL7RpyaPk9Ua7H21gqPUkzcbn3q2cKp+UVteY="

ota:
  - platform: esphome
    password: "f7dc0b4ac26f5e9d83fe5055da2c7c1a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Assist10 Fallback Hotspot"
    password: "LE0YCqaN3rfA"

captive_portal:
    
psram:
  mode: octal
  
i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO6 ##mic WS
    i2s_bclk_pin: GPIO5 ##mic SCK
  - id: i2s_out
    i2s_lrclk_pin: GPIO10 ##ampli LRC
    i2s_bclk_pin: GPIO11 ##ampli BCLK

microphone:
  - platform: i2s_audio
    i2s_audio_id: i2s_in
    id: mic
    adc_type: external
    i2s_din_pin: GPIO4 ##mic SD
    pdm: false
    channel: left
    ##bits_per_sample: 24bit

media_player:
  - platform: i2s_audio
    i2s_audio_id: i2s_out
    id: big_speaker
    dac_type: external
    name: stogazio
    i2s_dout_pin: 
      number: GPIO12 ##ampli DIN
      ##allow_other_uses: true
    ##i2s_mode: primary
    ##on_play: 
      ##then:
        ##- switch.turn_off: use_wake_word

voice_assistant:
  microphone: mic
  use_wake_word: true
  noise_suppression_level: 2
  ##auto_gain: 31dBFS
  volume_multiplier: 24
  media_player: big_speaker
  id: assist
  on_stt_end: 
    - rtttl.play: 'siren2:d=32,o=7,b=100:g'
  on_wake_word_detected:
    then:
      - rtttl.play: 'siren:d=32,o=7,b=100:f'
      - light.turn_on:
          id: onboardled
          brightness: 100%
          red: 0%
          green: 0%
          blue: 100%
  on_client_connected: 
    then:
      - light.turn_on:
          id: onboardled
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0%
  on_client_disconnected: 
    then:
      - light.turn_on:
          id: onboardled
          brightness: 100%
          red: 100%
          green: 0%
          blue: 0%


      

switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      ##- media_player.stop: 
      - delay: 1s
      - lambda: id(assist).set_use_wake_word(true);
      - voice_assistant.start_continuous
    on_turn_off:
      - voice_assistant.stop
      - delay: 1s
      - lambda: id(assist).set_use_wake_word(false);

output:
  - platform: ledc
    pin: 
      number: GPIO13
    id: buzzer
    frequency: "1000Hz"
    ##inverted: True
  ##- platform: gpio
    ##pin: 
      ##number: GPIO7
      ##allow_other_uses: true
    ##id: set_low_speaker

light:
  - platform: esp32_rmt_led_strip
    id: onboardled 
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "My Light"

rtttl:
  output: buzzer
  id: pippo
  gain: 0.5

button:
  - platform: restart
    name: "Reboot assistente"
```

**Comment by Nasimovy** [comment]
hey i have the same boards and psram is found with following code 

```
esphome:
  name: testesp32s3
  friendly_name: testESP32-S3-N16-R8

  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"  
    board_build.arduino.memory_type: qio_opi


psram:
  mode: octal
  speed: 80MHz

```


```
[15:01:59][C][psram:020]: PSRAM:
[15:01:59][C][psram:021]:   Available: YES
[15:01:59][C][psram:024]:   Size: 8191 KB
```
