### ISSUE TITLE
Compilation warnings for logger component with ESP IDF version 5.3.0+

### ISSUE THREAD

**Issue by rvalitov** [esphome/issues#6325]
### The problem

Compilation warnings:
```
src/esphome/components/logger/logger_esp32.cpp: In function 'void esphome::logger::init_usb_serial_jtag_()':
src/esphome/components/logger/logger_esp32.cpp:40:50: warning: 'void esp_vfs_dev_usb_serial_jtag_set_rx_line_endings(esp_line_endings_t)' is deprecated: Please use usb_serial_jtag_vfs_set_rx_line_endings instead [-Wdeprecated-declarations]
   40 |   esp_vfs_dev_usb_serial_jtag_set_rx_line_endings(ESP_LINE_ENDINGS_CR);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
In file included from src/esphome/components/logger/logger_esp32.cpp:14:
.platformio/packages/framework-espidf/components/vfs/include/esp_vfs_usb_serial_jtag.h:19:6: note: declared here
   19 | void esp_vfs_dev_usb_serial_jtag_set_rx_line_endings(esp_line_endings_t mode) __attribute__((deprecated("Please use usb_serial_jtag_vfs_set_rx_line_endings instead")));
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/logger/logger_esp32.cpp:42:50: warning: 'void esp_vfs_dev_usb_serial_jtag_set_tx_line_endings(esp_line_endings_t)' is deprecated: Please use usb_serial_jtag_vfs_set_tx_line_endings instead [-Wdeprecated-declarations]
   42 |   esp_vfs_dev_usb_serial_jtag_set_tx_line_endings(ESP_LINE_ENDINGS_CRLF);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
.platformio/packages/framework-espidf/components/vfs/include/esp_vfs_usb_serial_jtag.h:21:6: note: declared here
   21 | void esp_vfs_dev_usb_serial_jtag_set_tx_line_endings(esp_line_endings_t mode) __attribute__((deprecated("Please use usb_serial_jtag_vfs_set_tx_line_endings instead")));
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/logger/logger_esp32.cpp:60:37: warning: 'void esp_vfs_usb_serial_jtag_use_driver()' is deprecated: Please use usb_serial_jtag_vfs_use_driver() instead [-Wdeprecated-declarations]
   60 |   esp_vfs_usb_serial_jtag_use_driver();
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from src/esphome/components/logger/logger_esp32.cpp:13:
.platformio/packages/framework-espidf/components/vfs/include/esp_vfs_dev.h:63:6: note: declared here
   63 | void esp_vfs_usb_serial_jtag_use_driver(void) __attribute__((deprecated("Please use usb_serial_jtag_vfs_use_driver() instead")));
```

I will make a PR.

### Which version of ESPHome has the issue?

dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

ESP32-C6

### Component causing the issue

logger

### Example YAML snippet

```yaml
esphome:
  name: esphome
  friendly_name: ESPHome
  platformio_options:
    board_build.flash_mode: dio 

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
     
# Enable logging
logger:
  level: VERBOSE
```

### Additional information

I would like to resolve this issue to support newer ESP32 boards that require a newer version of ESP IDF other than officially supported by ESPHome.
