### ISSUE TITLE
Validation failure when using mcp9600 with the tca9548a on an i2c bus.

### ISSUE THREAD

**Issue by kyfalcon** [esphome/issues#6326]
### The problem

Seems that the tca9548a is not passing i2c bus frequency on to the mcp9600. This is causing a validation failure saying a required key is missing. The error message is not very descriptive as to what the actual issue is. 

### Which version of ESPHome has the issue?

2024.9.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

ESP32-S3-LCD-4.3

### Component causing the issue

api/i2c

### Example YAML snippet

```yaml
esphome:
  name: esphome-web-4bc1bc
  friendly_name: esphome-web-4bc1bc
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
api:
  
ota:
  - platform: esphome

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

web_server:
  port: 80   

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG

i2c:
  sda: GPIO8
  scl: GPIO9
  scan: false
  id: i2c0
  frequency: 10kHz

tca9548a:
  - address: 0x70
    id: multiplex0
    i2c_id: i2c0
    channels:
      - bus_id: multiplex0channel0
        channel: 0
      - bus_id: multiplex0channel1
        channel: 1

sensor:
  - platform: mcp9600
    i2c_id: multiplex0channel0
    hot_junction:
      id: temp3
      name: "Thermocouple Temperature 3"
    cold_junction:
      id: ambient3
      name: "Ambient Temperature 3"
    thermocouple_type: K
    address: 0x65
    update_interval: 10s
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.9.2
INFO Reading configuration /config/43-display.yaml...
Failed config

tca9548a: [source /config/43-display.yaml:52]
  
address: 0x70
  id: multiplex0
  i2c_id: i2c0
  channels: 
    required key not provided.
bus_id: m0c0
    channel: 0
```
