### ISSUE TITLE
Can not compile Http_request.get for tasmota request

### ISSUE THREAD

**Issue by olemde** [esphome/issues#6328]
### The problem

I copied this from the esphome description, but could not compile it:

`http_request:
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false
  #id: http_request_test

time:
  - platform: sntp
    id: sntp_time
    timezone: 'Europe/Berlin'

interval:
  - interval: 1min
    then:
      - http_request.get:
           url: http://192.168.1.76/cm?cmnd=Power #status%2010
           headers:
             Content-Type: application/json              
           capture_response: true
           on_response:
             then:
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {id(POWER).publish_state(root["vol"]);return true;});`

Error message is:
`http_request: [source tasmota2.yaml:29]

  Component not found: http_request.
  useragent: esphome/device
  timeout: 10s
  verify_ssl: False
interval: [source tasmota2.yaml:40]
  - interval: 1min
    then:
      -
        Unable to find action with the name 'http_request.get'.
        http_request.get:
          url: http://192.168.1.76/cm?cmnd=Power
          headers:
            Content-Type: application/json
          capture_response: True
          on_response:
            then:
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {id(POWER).publish_state(root["vol"]);return true;});`

### Which version of ESPHome has the issue?

2023.10.1

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

ESP32-S

### Example YAML snippet

```yaml
http_request:
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false
  #id: http_request_test

time:
  - platform: sntp
    id: sntp_time
    timezone: 'Europe/Berlin'

interval:
  - interval: 1min
    then:
      - http_request.get:
           url: http://192.168.1.76/cm?cmnd=Power #status%2010
           headers:
             Content-Type: application/json              
           capture_response: true
           on_response:
             then:
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {id(POWER).publish_state(root["vol"]);return true;});
```
