### ISSUE TITLE
2024.10.0 not setting ignore_efuse_mac_crc

### ISSUE THREAD

**Issue by latargere** [esphome/issues#6333]
### The problem

After updating to 2024.10.0, my devices with ignore_efuse_mac_crc don’t boot anymore.
Error is:
Base MAC address from BLK3 of EFUSE version error

Rolling back to 2024.9.2 and everything works again.

### Which version of ESPHome has the issue?

2024.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.2

### What platform are you using?

ESP32

### Component causing the issue

Boot

### Example YAML snippet

```yaml
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true
```

### Anything in the logs that might be useful for us?

```txt
Base MAC address from BLK3 of EFUSE version error
```

**Comment by gzxto1** [comment]
Same Problem here with my ULANZI Display, but not having configured the option
`ignore_efuse_mac_crc: true`

Rollback fixed it again


*************************************
```
esp32:
  board: esp32dev
```
 
*************************************

[14:50:24][W][esp-idf:000]: E (155944) system_api: Base MAC address from BLK3 of EFUSE version error, version = 0

**Comment by snipes040** [comment]
I have this issue as well, has broken both my Yeelight 1s led lightstrips that I flashed ESPhome with :)  I also have the ignore_efuse_mac_crc: true config entry.

**Comment by phbaer** [comment]
Same here, some esp32-based ceiling light. Rolled back to 2024.9.x

**Comment by randybb** [comment]
There is a new ignore `ignore_efuse_custom_mac:` introduced in this release as EFUSE can be used for storing any data, but can be used for MAC address as well. 
I agree, if you specifically say that there is a MAC with a wrong CRC in EFUSE, then it means there is a stored MAC too.

This is what I have for my xiaomi bs2 lamps:
```
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_custom_mac: true
      ignore_efuse_mac_crc: true
```
