### ISSUE TITLE
Can't control `valve` in `web_server`

### ISSUE THREAD

**Issue by tetele** [esphome/issues#6337]
### The problem

If you have both `web_server:` and a `valve` in your config, accessing the web page at `http://<device_name>.local` only exposes the `valve` state and no way to control it - open, close, set position

![Screenshot_20241016_212111_Chrome](https://github.com/user-attachments/assets/03c5f653-5154-4751-b5f1-11933398777d)

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
web_server:
  include_internal: true
  version: 3

output:
  - platform: slow_pwm
    id: output_valve
    period: 3s
    pin:
      number: GPIO16
      inverted: true

valve:
  - platform: template
    name: "Test ESPHome valve"
    has_position: true
    optimistic: true
    open_action:
      - output.set_level:
          id: output_valve
          level: 100%
    close_action:
      - output.set_level:
          id: output_valve
          level: 0%
    position_action:
      - output.set_level:
          id: output_valve
          level: !lambda 'return pos;'
```
