### ISSUE TITLE
PN7160 post-read IRQ times out with 50kHz I2C bus

### ISSUE THREAD

**Issue by ducky64** [esphome/issues#6339]
### The problem

When the I2C bus frequency is left at the default (50kHz), PN7160 fails on startup:
```
[W][pn7160:1162]: Timed out waiting for IRQ state
[W][pn7160_i2c:030]: read_nfcc_() post-read timeout waiting for IRQ line to clear
[W][pn7160:1111]: Error receiving message
[E][pn7160:1130]: Error in response to command: 60 00 09 02 01 20 04 04 61 12 50 05
[E][pn7160:244]: Error sending reset command
[E][pn7160:606]: Failed to reset NCI core
```

This repeats a few times before:
```
[E][pn7160:718]: Too many initialization failures -- check device connections
[E][component:119]: Component pn7160 was marked as failed.
[E][component:164]: Component pn7160 set Error flag: unspecified
```

Upping the frequency to 100kHz and beyond solves the problem. Perhaps there should be a note in the documentation about this?

Extending the wait timeout does not make a difference (other than making each cycle take longer). Perhaps it's the next read IRQ being detected?

Ignoring the results of the post-read check also makes things work. Perhaps it makes sense for the error to be non-fatal? If the expectation is the IRQ would have cleared in the specified timespan, maybe just log a warning?

### Which version of ESPHome has the issue?

2024.6.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

custom ESP32-S3 + PN7160

### Component causing the issue

pn7160

### Example YAML snippet

```yaml
This breaks:
i2c:
  scl: GPIO17
  sda: GPIO18

pn7160_i2c:
  irq_pin: GPIO47
  ven_pin: GPIO39


This works:
i2c:
  scl: GPIO17
  sda: GPIO18
  frequency: 400kHz  # must be at least 100kHz or a fatal timeout happens

pn7160_i2c:
  irq_pin: GPIO47
  ven_pin: GPIO39
```
