### ISSUE TITLE
esp32_ble_tracker variable crash

### ISSUE THREAD

**Issue by oerix** [esphome/issues#6341]
### The problem

In the midsts of adding bluetooth proxy support for a esphome device using the yaml file, I discovered that adding the following variable under `esp32_ble_tracker:` crashes Zigbee2mqtt and the MqttBroker.

```
esp32_ble_tracker:
  id: ${name}_ble_tracker
```

### Which version of ESPHome has the issue?

2024.10.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.10.2

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
esp32_ble_tracker:
  id: ${name}_ble_tracker
  scan_parameters:
    interval: 1500ms
    window: 750ms
    active: true

bluetooth_proxy:
  active: true
```

### Anything in the logs that might be useful for us?

```txt
Unfortunately, I don't have any logs at this moment in time. However, this issue could maybe be reproduced using the code line above.
```
