### ISSUE TITLE
If setuptools is required to use the esp-idf platform, then it should be installed by installing esphome.

### ISSUE THREAD

**Issue by nkinnan** [esphome/issues#6343]
### The problem

If setuptools is required to use the esp-idf platform, then it should be installed by installing esphome.

```
ModuleNotFoundError: No module named 'pkg_resources':
<... snip ...>
  File "C:\Users\nkinnan\.platformio\platforms\espressif32\builder\frameworks\espidf.py", line 29:
    import pkg_resources
```

resolved by `pip install setuptools`

`platform: arduino` did not require setuptools and compiled fine with default esphome install

This was the entire config, literally only this:

```yaml
substitutions:
  name: "test-esp32-0x25-full"
  friendly_name: "test-esp32-0x25-full"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32dev
  framework:
    type: esp-idf
```

On Windows 11 if it matters.

### Which version of ESPHome has the issue?

Version: 2024.10.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32-IDF

### Board

n/a

### Component causing the issue

esp32

### Example YAML snippet

```yaml
substitutions:
  name: "test-esp32-0x25-full"
  friendly_name: "test-esp32-0x25-full"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32dev
  framework:
    type: esp-idf
```

### Anything in the logs that might be useful for us?

```txt
ModuleNotFoundError: No module named 'pkg_resources':
<... snip ...>
  File "C:\Users\nkinnan\.platformio\platforms\espressif32\builder\frameworks\espidf.py", line 29:
    import pkg_resources
```

### Additional information

Win 11 cmd.exe: pip install esphome

I uninstalled and reinstalled esphome several times with pip.  I deleted the .platformio directory several times.  I deleted the .esphome directory several times.  The only thing that worked was manually pip installing setuptools.  Related: https://github.com/esphome/issues/issues/5766
