### ISSUE TITLE
Missing .local in domain name for Athom Smart Plug V2

### ISSUE THREAD

**Issue by rmaeder** [esphome/issues#6348]
### The problem

This problem looks similar to issue #3283 . I tried to adopt an Athom Smart Plug V2.
Adopting seems to succeed, it does show up in the ESPHome dashboard, but I cannot visit it, or update it.
The link under the "VISIT" button uses the domain name `athom-smart-plug-v2-ecXXX` *without* `.local` appended; this does not work. Other devices, such as an Apollo Multisensor Mk1 use a domain name of `apollo-msr-1-XXXX.local`, which usually works.

On the second try, I was able to update it, but the link is still wrong.

### Which version of ESPHome has the issue?

2024.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10

### What platform are you using?

ESP32

### Board

athom

### Example YAML snippet

```yaml
substitutions:
  name: athom-smart-plug-v2-ecXXXX
  friendly_name: Smart Plug V2 ecXXXX
packages:
  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: XXXXXXXX=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

### Additional information

Is there a way to set the host name, and include the .local part?
