### ISSUE TITLE
2024.10.0 breaks the web_server_sorting_weight option

### ISSUE THREAD

**Issue by denes44** [esphome/issues#6349]
### The problem

The `2024.10.0` version gives an error message for the `web_server_sorting_weight` setting on a `restart` `button`.
The same code compiles without problems on `2024.9.2`

### Which version of ESPHome has the issue?

2024.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.3

### What platform are you using?

ESP32-IDF

### Board

adafruit_feather_esp32s3

### Component causing the issue

button.restart

### Example YAML snippet

```yaml
button:
  - platform: restart
    name: Restart
    id: _restart
    entity_category: config
    web_server_sorting_weight: 1
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.10.0
INFO Reading configuration /config/esphome/project.yaml...
INFO Detected timezone 'Europe/Budapest'
Failed config

button.restart: [source /config/esphome/common/project-core.yaml:77]
  platform: restart
  name: Restart
  id: _restart
  entity_category: config
  
  [web_server_sorting_weight] is an invalid option for [button.restart]. Please check the indentation.
  web_server_sorting_weight: 1
```

**Comment by fra87** [comment]
Not an expert, but it seems to me [the changelog](https://esphome.io/changelog/2024.10.0.html#web-server-grouping) explicitly address this issue:

> This is also a breaking change as the previous `web_server_sorting_weight` has been moved into a new `web_server` -> `sorting_weight` configuration entry for the entity.

So try changing it into

```
button:
  - platform: restart
    name: Restart
    id: _restart
    entity_category: config
    web_server:
      sorting_weight: 1
```
