### ISSUE TITLE
ignore_efuse_mac_crc is not supported on ESP32C3

### ISSUE THREAD

**Issue by fra87** [esphome/issues#6353]
### The problem

After updating to 2024.10.0, trying to install a working project results in the error in the title.

### Which version of ESPHome has the issue?

2024.10.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

ESP32-C3 Super Mini

### Example YAML snippet

```yaml
---
# Test snippet for ESP32-C3 SuperMini

esphome:
  name: 'esph-test'

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false

api:

ota:
  - platform: esphome
    id: component_ota
    password: !secret ota_password
   
wifi:
  id: component_wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

### Anything in the logs that might be useful for us?

```txt
Failed config

esp32: None
  
  ignore_efuse_mac_crc is not supported on ESP32C3.
  board: lolin_c3_mini
  framework: 
    version: 4.4.8
    sdkconfig_options: 
      COMPILER_OPTIMIZATION_SIZE: y
    advanced: 
      ignore_efuse_mac_crc: False
      ignore_efuse_custom_mac: False
    components: []
    source: ~3.40408.0
    platform_version: platformio/espressif32@5.4.0
    type: esp-idf
```

### Additional information

I used the configuration part from the docs, together with minimal additional info: https://esphome.io/components/esp32.html#esp-idf-framework

Changing `lolin_c3_mini` to `esp32-c3-devkitm-1` doesn't change anything in the outcome

**SOLVED** by removing the following lines from the configuration

```
    advanced:
      ignore_efuse_mac_crc: false
```

The script seem to be working (I tested only "standalone", without home assistant integration and with the webserver).
However I don't know how much this can affect fuctionalities, so please advise if this shall be removed or replaced with something else
