### ISSUE TITLE
Globals cannot use types from esphome.includes.

### ISSUE THREAD

**Issue by Spamfast** [esphome/issues#6356]
### The problem

The code generated from the 'globals' YAML key is inserted into main.cpp before the #includes from esphome.includes.

This means that only those types exposed by the default #include set can be used as globals.

### Which version of ESPHome has the issue?

2024.10.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32

### Board

M5Stack AtomS3

### Component causing the issue

globals

### Example YAML snippet

```yaml
globals:
- id: button_i2c_interlock
  type: 'std::mutex'

esphome:
  includes:
  - components/concurrency_headers.h
```

### Additional information

```
/**
 * @file components/concurrency_headers.h
 *
 * Header to include for ESPHome lambdas to provide concurrency support.
 *
 * @version $Id: concurrency_headers.h 2307 2024-10-20 17:26:40Z spamfast $
 */

#ifndef _UTM_COMPONENTS_CONCURRENCY_HEADERS_H_
#define _UTM_COMPONENTS_CONCURRENCY_HEADERS_H_

#include <mutex>

#endif // ndef _UTM_COMPONENTS_CONCURRENCY_HEADERS_H_
```
