### ISSUE TITLE
Remote Transmitter Crashes and high temperature on GB3S

### ISSUE THREAD

**Issue by titoyoan** [esphome/issues#6357]
### The problem

Hi, I'm using Remote Transmitter with LibreTiny in ESPHome. When I include Remote Transmitter my microprocessor raise a high temperature and crashes. Perhaps sometimes I am able to send a command but most of the times it crashes.
I do not have to do anything, just booting up it crashes.

my base config is:

bk72xx:
  board: cb3s

remote_transmitter:
  pin:
    number: GPIO26
    inverted: true
  carrier_duty_percent: 50%

I'm using this on a Tuya IR Blaster. This is enough to make it crash.
I have not any log or other information, is impossible to know what is happening, and there is no log.

### Which version of ESPHome has the issue?

2024.10.0

### What type of installation are you using?

pip

### What platform are you using?

BK72XX

### Board

CB3S

### Component causing the issue

Remote Transmitter

### Example YAML snippet

```yaml
bk72xx:
  board: cb3s

remote_transmitter:
  pin:
    number: GPIO26
    inverted: true
  carrier_duty_percent: 50%
```

### Anything in the logs that might be useful for us?

```txt
nothing...
```

### Additional information

Really high temperature in the board.
