### ISSUE TITLE
addressable color_wipe always turns on white color to 100%

### ISSUE THREAD

**Issue by morris2009** [esphome/issues#6358]
### The problem

If i use the addressable color_wipe effect with an RGBW led (neopixelbus:sk6812) the white led always turns on 100% which is so bright you almost can't see the color_wipe effect.
Trying to turn the white led's off before selection of the effect, or after selection of the effect doesn't work. I tried setting up the effect in YAML to have 0% white, but that doesn't work.
Other effects work fine, and are adjustable after they are selected.

### Which version of ESPHome has the issue?

esphome-2024-9.0-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.10.1

### What platform are you using?

ESP32

### Component causing the issue

neopixelbus

### Example YAML snippet

```yaml
light:
  - platform: neopixelbus
    type: GRBW
    variant: sk6812
    pin: 32
    num_leds: 6
    name: badge_leds
    icon: mdi:ledstrip
    effects:
      - addressable_color_wipe:      
      - addressable_color_wipe:
          name: custom color wipe
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              white: 0%
              num_leds: 2
      - addressable_rainbow: 
      - addressable_scan:
      - addressable_random_twinkle:
      - addressable_twinkle:
      - addressable_fireworks:
```
