### ISSUE TITLE
Libraries compilation failing

### ISSUE THREAD

**Issue by vi350** [esphome/issues#6360]
### The problem

Project was previously compiled with ESPHome version 2024.7.2 in the end of july. I've updated esphome container recently to the 2024.9.2. Device had gone buggy, I decided to reboot it via install (ota update), which led to such and error:

```
INFO ESPHome 2024.9.2
INFO Reading configuration /config/ceiling-light.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing ceiling-light (board: lolin_s2_mini; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32S2 240MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s2 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
Compiling .pioenvs/ceiling-light/lib895/libsodium/crypto_hash/sha256/cp/hash_sha256_cp.c.o
Compiling .pioenvs/ceiling-light/lib895/libsodium/crypto_hash/sha512/cp/hash_sha512_cp.c.o
/tmp/ccZFnzkL.s: Assembler messages:
/tmp/ccZFnzkL.s:3358: Error: junk at end of line, first unrecognized character valued 0x9
/tmp/ccZFnzkL.s:3360: Error: unrecognized symbol type ""
/tmp/ccZFnzkL.s:3360: Error: junk at end of line, first unrecognized character is `+'
/tmp/ccZFnzkL.s:3361: Warning: missing closing `"'
/tmp/ccZFnzkL.s:3361: Error: unknown opcode or format name 'crypto_hash_sha256_update'
/tmp/ccZFnzkL.s:3366: Error: bad register name: 	sp
/tmp/ccZFnzkL.s:3366: Error: junk at end of line, first unrecognized character valued 0x9
/tmp/ccZFnzkL.s:3366: Internal error in demand_empty_rest_of_line at /builds/idf/crosstool-NG/.build/xtensa-esp32s2-elf/src/binutils/gas/read.c:3788.
Please report this bug.
*** [.pioenvs/ceiling-light/lib895/libsodium/crypto_hash/sha256/cp/hash_sha256_cp.c.o] Error 1
/tmp/ccupP7qe.s: Assembler messages:
/tmp/ccupP7qe.s:7610: Error: junk at end of line, first unrecognized character valued 0x9
/tmp/ccupP7qe.s:7612: Error: unrecognized symbol type ""
/tmp/ccupP7qe.s:7612: Error: junk at end of line, first unrecognized character is `+'
/tmp/ccupP7qe.s:7613: Warning: missing closing `"'
/tmp/ccupP7qe.s:7613: Error: unknown opcode or format name 'crypto_hash_sha512_update'
/tmp/ccupP7qe.s:7618: Error: bad register name: 	sp
/tmp/ccupP7qe.s:7618: Error: junk at end of line, first unrecognized character valued 0x9
/tmp/ccupP7qe.s:7618: Internal error in demand_empty_rest_of_line at /builds/idf/crosstool-NG/.build/xtensa-esp32s2-elf/src/binutils/gas/read.c:3788.
Please report this bug.
*** [.pioenvs/ceiling-light/lib895/libsodium/crypto_hash/sha512/cp/hash_sha512_cp.c.o] Error 1
========================= [FAILED] Took 10.43 seconds =========================
```

### Which version of ESPHome has the issue?

2024.9.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

lolin_s2_mini

### Component causing the issue

.pioenvs/ceiling-light/lib895/libsodium/crypto_hash/sha256/cp/hash_sha256_cp.c.o

### Example YAML snippet

```yaml
esphome:
  name: ceiling-light
  friendly_name: ceiling-light

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

# Enable logging
logger:

api:
  encryption:
    key: "*"

ota:
  - platform: esphome
    password: "*"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "*"
    password: "*"
  power_save_mode: none
  output_power: 8.5

captive_portal:
    

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true
    name: "switch"
    id: wall_switch
    filters:
      - delayed_on: 200ms
      - delayed_off: 200ms
    on_state:
      - light.toggle: ceiling_light

light:
  - platform: cwww
    id: ceiling_light
    name: "light"
    cold_white: gpio_cold
    warm_white: gpio_warm
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    constant_brightness: true
    gamma_correct: 3.5
    default_transition_length: 2s
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: rgb
    id: ceiling_light_rgb
    name: "rgb"
    red: gpio_red
    green: gpio_green
    blue: gpio_blue
    gamma_correct: 2.5
    default_transition_length: 2s
    restore_mode: RESTORE_DEFAULT_OFF


output:
  - platform: ledc
    id: gpio_red
    pin: GPIO10
  - platform: ledc
    id: gpio_green
    pin: GPIO8
  - platform: ledc
    id: gpio_blue
    pin: GPIO6
  - platform: ledc
    id: gpio_cold
    pin: GPIO14
  - platform: ledc
    id: gpio_warm
    pin: GPIO13
```
