### ISSUE TITLE
i2c: This driver is an old driver, please migrate your application code to adapt driver/i2c_master.h

### ISSUE THREAD

**Issue by rvalitov** [esphome/issues#6366]
### The problem

I'm using ESP32-C6 with latest ESP-IDF. It shows the warning during compilation:
```
i2c: This driver is an old driver, please migrate your application code to adapt driver/i2c_master.h
```

### Which version of ESPHome has the issue?

2024.10.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

esp32-c6-devkitc-1

### Component causing the issue

i2c

### Example YAML snippet

```yaml
esphome:
  name: garage_sensors
  friendly_name: Garage Sensors
  platformio_options:
    board_build.flash_mode: dio 

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
     
# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: ""

wifi:
  ssid: ""
  password: ""
 
i2c:
  sda: 6
  scl: 7
  scan: true
    
sensor:
  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 30s
```
