### ISSUE TITLE
tsens: legacy driver is deprecated, please migrate to driver/temperature_sensor.h

### ISSUE THREAD

**Issue by rvalitov** [esphome/issues#6367]
### The problem

A warning is shown:
```
tsens: legacy driver is deprecated, please migrate to driver/temperature_sensor.h
```

### Which version of ESPHome has the issue?

2024.10.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

esp32-c6-devkitc-1

### Component causing the issue

internal_temperature

### Example YAML snippet

```yaml
esphome:
  name: test
  friendly_name: Test
  platformio_options:
    board_build.flash_mode: dio 

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y

     
# Enable logging
logger:
  level: VERBOSE

sensor:
  - platform: internal_temperature
    id: esp_internal_temperature
    name: "Internal Temperature"
```
