### ISSUE TITLE
update via notification/entity updates wrong device

### ISSUE THREAD

**Issue by 532910** [esphome/issues#6373]
### The problem

With several devices described as follows:

`config/esphome/socket-hall.yaml`:
```Yaml
packages:
  main: !include common/ShellyPlugS.yaml
wifi:
  use_address: socket-hall.mydomain.tld
```

`config/esphome/socket-kitchen.yaml`:
```Yaml
packages:
  main: !include common/ShellyPlugS.yaml
wifi:
  use_address: socket-kitchen.mydomain.tld
```

update via notification/entity updates only the last device:

 `update.socket_kitchen_firmware` works as expected: socket-kitchen gets updated
  `update.socket_hall_firmware` triggers update for socket-kitchen

`UPDATE ALL` button from esphome tab works fine and updates all devices.

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.3

### What platform are you using?

ESP32

### Board

not related

### Component causing the issue

not related
