### ISSUE TITLE
Status sensor does not check if required network component is missing

### ISSUE THREAD

**Issue by rvalitov** [esphome/issues#6383]
### The problem

Compilation of status binary sensor leads to error if network component is not used. Error:
```
src/esphome/components/status/status_binary_sensor.cpp:3:10: fatal error: esphome/components/network/util.h: No such file or directory
    3 | #include "esphome/components/network/util.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs\garage-sensors\src\esphome\components\status\status_binary_sensor.cpp.o] Error 1
```

If something is missing for other components, then this info is displayed properly and beautifully about missing component, for example:
```
sensor.uptime: [source zigbee.yaml:96]

  This option requires component time.
  platform: uptime
  id: esp_last_booted
  type: timestamp
  name: Last booted
```

So if network component is missing a similar message should be displayed:
```
  This option requires component network.
  platform: status
  name: Status
```

### Which version of ESPHome has the issue?

2024.10.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

ESP32-C6

### Example YAML snippet

```yaml
esphome:
  name: sensor
  friendly_name: Sensor
  platformio_options:
    board_build.flash_mode: dio 

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
      CONFIG_ZB_ENABLED: y
      CONFIG_ZB_ZED: y
      CONFIG_ZB_RADIO_NATIVE: y
      ZB_ED_ROLE: y

binary_sensor:    
  - platform: status
    name: Status
```
