### ISSUE TITLE
TuyaClimate sets the wrong mode, missing "Auto" mode?

### ISSUE THREAD

**Issue by fabianoarruda** [esphome/issues#6384]
### The problem

I think I've found a bug, but I was not sure if this should be posted here as a bug, or directly as a feature request because I think I know what is the possible cause for it. So, perhaps the possible solution should be posted as feature request? If that's the case let me know.

Anyway, here is the explanation for the problem: I'm currently using a device with TuyaClimate with an IR Thermostat from Moes. All modes work as expected, however the Auto mode does not work, because it's not mapping that value to TuyaClimate. According to the documentation, I should use  `active_state` to map the hvac modes with the datapoint from Tuya. However the docs refers to only these options: `heating_value`, `cooling_value`, `drying_value` and `fanonly_value`. But when I look on the datapoint specs extracted from Tuya Cloud, it has the following possible values on Datapoint 4:

```
0: "cold",
1: "warm",
2: "auto",
3: "wind",
4: "dehumidify"
```
Looks like mode 2 is missing in TuyaClimate. As you can see in logs bellow, when datapoint changes to `2`, it will not recognize it correctly and will just set mode again to the same value it was (1).

So, maybe the component is missing an `auto_value` under `active_state`?

### Which version of ESPHome has the issue?

2024.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.3

### What platform are you using?

BK72XX

### Board

Moes S16Pro

### Component causing the issue

TuyaClimate

### Example YAML snippet

```yaml
esphome:
  name: termostato-criancas
  friendly_name: Termostato Crianças

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:
  #level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Termostato-Criancas Hotspot"
    password: ""

captive_portal:
    
########################
### IR BLASTER SETUP ###
########################
remote_transmitter:
  id: ir_t
  pin: P7
  carrier_duty_percent: 50%
remote_receiver:
  id: ir_r
  pin: 
    number: P8
    inverted: true
  dump: all

######################
### TUYA MCU SETUP ###
######################
uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

tuya:

###############
### SENSORS ###
###############
sensor:

  # WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 120s
  
  - platform: uptime
    name: Uptime

  - platform: tuya
    name: "Umidade"
    sensor_datapoint: 12
    unit_of_measurement: "%"
  
  - platform: tuya
    name: "Temperatura"
    sensor_datapoint: 2
    unit_of_measurement: "°C"
    filters:
      - multiply: 0.1

text_sensor:
  # ESPHome version
  - platform: version
    hide_timestamp: true
    name: "ESPHome Version"
  # IP address and connected SSID
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
    ssid:
      name: "Connected SSID"
      icon: mdi:wifi-strength-2
  
binary_sensor:
  - platform: status
    name: Status


#######################
### CLIMATE DEVICES ###
#######################
climate:
# THIS IS THE TUYA CLIMATE ENTITY
# IT RELAYS STATE CHANGES TO THE SECONDARY CLIMATE ENTITY WHICH PROCESSES THEM AS IR COMMANDS
  - platform: tuya
    name: "AC"
    id: climate_primary_criancas
    visual:
      min_temperature: 17
      max_temperature: 30
      temperature_step: 1
    switch_datapoint: 1
    target_temperature_datapoint: 3
    target_temperature_multiplier: 1
    current_temperature_datapoint: 2
    current_temperature_multiplier: 0.1
    supports_heat: true
    supports_cool: true
    active_state:
      datapoint: 4
      cooling_value: 0
      heating_value: 1
      fanonly_value: 3
      drying_value: 4
    fan_mode:
      datapoint: 5
      auto_value: 0
      low_value: 1
      medium_value: 2
      high_value: 3
    # AUTOMATION THAT WHENEVER THE DATAPOINTS UPDATE THOSE STATUSES SHOULD ALSO BE UPDATED ON THE SECONDARY CLIMATE ENTITY
    on_state:
      
      - lambda: |-
          // ESP_LOGD("main", " --------------------------    primary mode: %d", id(climate_primary_criancas).mode);
          // ESP_LOGD("main", " --------------------------    secondary mode: %d", id(climate_secondary_criancas).mode);
          
          if (id(climate_primary_criancas).mode != (id(climate_secondary_criancas).mode)) {
            auto call = id(climate_secondary_criancas).make_call();
            call.set_mode(id(climate_primary_criancas).mode);
            call.perform();
          }
          else if (id(climate_primary_criancas).fan_mode != (id(climate_secondary_criancas).fan_mode)) {
            auto call = id(climate_secondary_criancas).make_call();
            call.set_fan_mode(id(climate_primary_criancas).fan_mode);
            call.perform();
          }
          else if (id(climate_primary_criancas).target_temperature != (id(climate_secondary_criancas).target_temperature)) {
            auto call = id(climate_secondary_criancas).make_call();
            call.set_target_temperature(id(climate_primary_criancas).target_temperature);
            call.perform();
          }


  # THIS THE THE SECONDARY HIDDEN CLIMATE DEVICE THAT PROCESSES THE COMMANDS FROM THE PRIMARY ENTITY AS IR COMMANDS
  
  
  - platform: climate_ir_lg

    name: "IR"
    id: climate_secondary_criancas
    
    receiver_id: ir_r
    
    header_high: 3265us # AC Units from LG in Brazil use these timings
    header_low: 9856us
    
    internal: true
    visual:
      min_temperature: 17
      max_temperature: 30
      temperature_step: 1
```

### Anything in the logs that might be useful for us?

```txt
# Here Datapoint 4 is set to 1 (heating) and mode is set to HEAT as expected

[16:32:52][D][tuya:355]: Datapoint 4 update to 1
[16:32:52][D][climate:396]: 'AC' - Sending state:
[16:32:52][D][climate:399]:   Mode: HEAT
[16:32:52][D][climate:401]:   Action: HEATING
[16:32:52][D][climate:404]:   Fan Mode: LOW
[16:32:52][D][climate:419]:   Current Temperature: 27.20°C
[16:32:52][D][climate:425]:   Target Temperature: 24.00°C
[16:32:52][D][climate:011]: 'IR' - Setting
[16:32:52][D][climate:015]:   Mode: HEAT
[16:32:52][D][climate.climate_ir_lg:076]: climate_lg_ir mode code: 0x03
[16:32:52][D][climate.climate_ir_lg:191]: Sending climate_lg_ir code: 0x880C905
[16:32:52][D][remote_transmitter:077]: Sending remote code...
[16:32:52][D][climate:396]: 'IR' - Sending state:
[16:32:52][D][climate:399]:   Mode: HEAT
[16:32:52][D][climate:404]:   Fan Mode: LOW
[16:32:52][D][climate:416]:   Swing Mode: OFF
[16:32:52][D][climate:425]:   Target Temperature: 24.00°C


# And here you can see Datapoint is set to 2 (auto) but state is wrongly 
# set to HEAT (1), I guess because it was the previous known value

[16:34:53][D][tuya:355]: Datapoint 4 update to 2
[16:34:53][D][climate:396]: 'AC' - Sending state:
[16:34:53][D][climate:399]:   Mode: HEAT
[16:34:53][D][climate:401]:   Action: IDLE
[16:34:53][D][climate:404]:   Fan Mode: LOW
[16:34:53][D][climate:419]:   Current Temperature: 27.20°C
[16:34:53][D][climate:425]:   Target Temperature: 24.00°C
```
