### ISSUE TITLE
LVGL slider indicator - radius parameter not working

### ISSUE THREAD

**Issue by derMicro** [esphome/issues#6387]
### The problem

Obviously the “radius” parameter for the slider indicator is ignored, I have tried it with several values, it always stays with the default configuration.

<img width="756" alt="image" src="https://github.com/user-attachments/assets/b3482282-ef73-4ea4-a233-373d033164c1">

Default in SquareLine-Studio (LVGL 8.3.11)
<img width="889" alt="image" src="https://github.com/user-attachments/assets/86bcfafb-beda-40a7-a05e-c8672e4e3add">

radius 0 in SquareLine-Studio (LVGL 8.3.11)
<img width="866" alt="image" src="https://github.com/user-attachments/assets/d2d2b67a-ff52-45a8-a43b-501d3ed9cfdc">

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10

### What platform are you using?

ESP32

### Board

esp32-s3-devkitc-1

### Component causing the issue

LVGL

### Example YAML snippet

```yaml
- slider:
                  id: lvgl_sliderbrightness_papi
                  x: 0
                  y: -13
                  align: CENTER
                  width: 84
                  height: 208
                  min_value: 0
                  max_value: 255
                  bg_opa: "0%"
                  indicator:
                    bg_color: 0x888888
                    bg_opa: "100%"
                    radius: 0 #<----------
                  knob:
                    bg_color: 0xFFFFFF
                    bg_opa: "0%"
                    radius: 2
                    pad_left: 0
                    pad_right: 0
                    pad_top: -40
                    pad_bottom: -20
                    outline_color: 0xe0e0e0
                    outline_opa: "100%"
                    outline_pad: -11
                    outline_width: 2
                  on_release:
                    - homeassistant.service:
                        service: light.turn_on
                        data:
                          entity_id: light.sz_nightlight_papi
                          brightness: !lambda return int(x);
```

**Comment by clydebarrow** [comment]
It works just fine for me - indicator radius zero on the left, 20px on the right.

<img width="712" alt="Screenshot 2024-10-28 at 7 18 21 PM" src="https://github.com/user-attachments/assets/5c2ab8a0-0eb0-46ed-8a37-fc203d774059">

```yaml
    - slider:
                  x: 20
                  align: left_mid
                  width: 84
                  height: 208
                  value: 50
                  bg_opa: "100%"
                  indicator:
                    bg_color: 0x888888
                    bg_opa: "100%"
                    radius: 0 #<----------
                  knob:
                    bg_color: 0xFFFFFF
                    bg_opa: "0%"
                    radius: 2
                    pad_left: 0
                    pad_right: 0
                    pad_top: -40
                    pad_bottom: -20
                    outline_color: 0xe0e0e0
                    outline_opa: "100%"
                    outline_pad: -11
                    outline_width: 2
    - slider:
                  id: lvgl_sliderbrightness_papi
                  x: -20
                  align: right_mid
                  width: 84
                  height: 208
                  value: 50
                  bg_opa: "100%"
                  indicator:
                    bg_color: 0x888888
                    bg_opa: "100%"
                    radius: 20 #<----------
                  knob:
                    bg_color: 0xFFFFFF
                    bg_opa: "0%"
                    radius: 2
                    pad_left: 0
                    pad_right: 0
                    pad_top: -40
                    pad_bottom: -20
                    outline_color: 0xe0e0e0
                    outline_opa: "100%"
                    outline_pad: -11
                    outline_width: 2
```
