### ISSUE TITLE
Web Server Not Working With Wifi Credentials

### ISSUE THREAD

**Issue by alexyao2015** [esphome/issues#639]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, Nodemcu
**Affected component:**

Wifi and AP mode

**Description of problem:**
When ESPhome is unable to find the wifi network, it creates an AP, however connecting to it doe s not allow for reflashing. Serial just shows it constantly scanning for a network with no way to access the web server even though it is enabled in the config. Accessing 192.168.4.1 while connected to the AP will not load. Removing the wifi credentials in the original config allows the web server to function properly but does not make sense if the original network cannot be found. 

Potentially the captive portal in dev will resolve this? 
**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
First YAML, Not working
esphome:
  name: demo
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "I do not exist"
  password: "fake password"

  ap:
   ssid: "DEMO"

# Enable logging
logger:
  baud_rate: 115200

web_server:
  port: 80


Second YAML, working
esphome:
  name: demo
  platform: ESP8266
  board: nodemcuv2

wifi:
  ap:
   ssid: "DEMO"

# Enable logging
logger:
  baud_rate: 115200

web_server:
  port: 80
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
First YAML with Wifi Credentials
[1B][0;32m[I][app:028]: Running through setup()...[1B][0m
[1B][0;35m[C][wifi:029]: Setting up WiFi...[1B][0m
[1B][0;36m[D][wifi:272]: Starting scan...[1B][0m
[1B][0;36m[D][wifi:287]: Found networks:[1B][0m
(List of networks found)
[1B][0;33m[W][wifi:331]: No matching network found![1B][0m
[1B][0;35m[C][wifi:138]: Setting up AP...[1B][0m
[1B][0;35m[C][wifi:140]:   AP SSID: 'DEMO'[1B][0m
[1B][0;35m[C][wifi:141]:   AP Password: ''[1B][0m
[1B][0;35m[C][wifi:150]:   IP Address: 192.168.4.1[1B][0m
[1B][0;36m[D][wifi:272]: Starting scan...[1B][0m
[1B][0;36m[D][wifi:287]: Found networks:[1B][0m
(List of networks found)
[1B][0;33m[W][wifi:331]: No matching network found![1B][0m
[1B][0;36m[D][wifi:272]: Starting scan...[1B][0m

Loops endlessly. Notice no mention of webserver.




Second YAML without Wifi Credentials

[1B][0;32m[I][app:028]: Running through setup()...[1B][0m
[1B][0;35m[C][wifi:029]: Setting up WiFi...[1B][0m
[1B][0;35m[C][wifi:138]: Setting up AP...[1B][0m
[1B][0;35m[C][wifi:140]:   AP SSID: 'DEMO'[1B][0m
[1B][0;35m[C][wifi:141]:   AP Password: ''[1B][0m
[1B][0;35m[C][wifi:150]:   IP Address: 192.168.4.1[1B][0m
[1B][0;35m[C][web_server:068]: Setting up web server...[1B][0m
[1B][0;32m[I][app:060]: setup() finished successfully![1B][0m
[1B][0;32m[I][app:096]: esphome version 1.13.6 compiled on Aug 31 2019, 23:50:12[1B][0m
[1B][0;35m[C][logger:137]: Logger:[1B][0m
[1B][0;35m[C][logger:138]:   Level: DEBUG[1B][0m
[1B][0;35m[C][logger:139]:   Log Baud Rate: 115200[1B][0m
[1B][0;35m[C][logger:140]:   Hardware UART: UART0[1B][0m
[1B][0;35m[C][wifi:372]: WiFi:[1B][0m
[1B][0;35m[C][wifi:254]:   SSID: [1B][5m''[1B][6m[1B][0m
[1B][0;35m[C][wifi:255]:   IP Address: 0.0.0.0[1B][0m
[1B][0;35m[C][wifi:257]:   BSSID: [1B][5mFF:FF:FF:FF:FF:FF[1B][6m[1B][0m
[1B][0;35m[C][wifi:258]:   Hostname: 'demo'[1B][0m
[1B][0;35m[C][wifi:262]:   Signal strength: 31 dB [1B][0;32mâ–‚â–„â–†â–ˆ[1B][0m[1B][0m
[1B][0;35m[C][wifi:263]:   Channel: 1[1B][0m
[1B][0;35m[C][wifi:264]:   Subnet: 0.0.0.0[1B][0m
[1B][0;35m[C][wifi:265]:   Gateway: 0.0.0.0[1B][0m
[1B][0;35m[C][wifi:266]:   DNS1: 0.0.0.0[1B][0m
[1B][0;35m[C][wifi:267]:   DNS2: 0.0.0.0[1B][0m
[1B][0;35m[C][web_server:125]: Web Server:[1B][0m
[1B][0;35m[C][web_server:126]:   Address: demo.local:80[1B][0m

```

**Additional information and things you've tried:**
Related to esphome/feature-requests#86
