### ISSUE TITLE
[http_request] Empty Response Body

### ISSUE THREAD

**Issue by marcin212** [esphome/issues#6392]
### The problem

The http request component is not loading content despite setting capture_response to true. From my debugging, it looks like if the response does not contain the Content-Length header, the content is not loaded. Many REST endpoints do not return this header. It would be useful to add an option that attempts to load the content up to the maximum capacity of the defined buffer.

https://esphome.io/components/http_request.html#get-values-from-a-json-body-response

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Component causing the issue

http_request

### Example YAML snippet

```yaml
http_request:

script:
  - id: update_weather
    then: 
      - http_request.get:
          url: !lambda |-
            std::string url = "https://api.open-meteo.com/v1/forecast?latitude=0.000&longitude=0.000&current=temperature_2m,relative_humidity_2m,surface_pressure&forecast_days=1";
            ESP_LOGI("main", "URL: %s", url.c_str());
            return url.c_str();
          headers:
            Content-Type: application/json
          capture_response: true  
          on_response:
            then:
              - logger.log:
                  format: 'Response status: %d, Duration: %u ms'
                  args:
                    - response->status_code
                    - response->duration_ms
              - lambda: |-
                  ESP_LOGI("main", "Response: %s", body.c_str());
                  json::parse_json(body, [](JsonObject root) -> bool {
                    id(outside_temp).publish_state(root["current"]["temperature_2m"]);
                    id(outside_hum).publish_state(root["current"]["relative_humidity_2m"]);
                    id(outside_pressure).publish_state(root["current"]["surface_pressure"]);
                    return true;
                  });

button:
  - platform: template
    name: "Force Update Weather Button"
    on_press:
      - script.execute: update_weather
```

### Anything in the logs that might be useful for us?

```txt
Response: 
Could not allocate memory for JSON document! Requested 0 bytes, free heap: 34816
```

### Additional information

![2024-10-30_tNbqIKgMHlZtGPs3](https://github.com/user-attachments/assets/cdd4f79b-79c8-4e76-8d2a-9771b1fc216f)
