### ISSUE TITLE
X9C on ESP32 C3 Supermini changes only in one direction

### ISSUE THREAD

**Issue by Apfelsafft** [esphome/issues#6399]
### The problem

Hi,
I am trying to connect a X9C103 board to the supermini. 
The problem is that the poti moves only in one direction. No matter if I increase or decrease the value, the amount is only running into one direction.
I tried it on two X9C breakout boards and on different pins of the C3 (GPIO2, 3 & 4 or GPIO10, 20, 21 or GPIO 10, 8, 9)
When conneecting the boards to a ESP32-S3 it works fine. 

Also tried to increase step_delay from 1us to 10us to 100us. 

No matter what, it seems as if UP/DN information is not send on a C3 supermini.

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2024.10.4 OS 13.2

### What platform are you using?

ESP32

### Board

ESP32-C3 Supermini

### Component causing the issue

X9C

### Example YAML snippet

```yaml
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

output:
  - platform: x9c
    id: swc1
    cs_pin: GPIO10
    inc_pin: GPIO20
    ud_pin: GPIO21
    initial_value: 0.01
    step_delay: 1us 

switch:
  - platform: template
    name: "Function 1"
    id: fc1
    optimistic: true
    on_turn_on:
    - output.set_level:
       id: swc1
       level: 0.9  
    - delay: 1000ms
    - output.set_level:
       id: swc1
       level: 0.01    
    - switch.turn_off: fc1
```

### Additional information

I am using a X9C103 breakout board. It ist the greenisch rectangular one, where you have the control pins on one side and the resistor pins on the other.
To measure the resistance, I connected RL to GND and the wiper to RH to work as a rheostat. Measuring between wiper and GND.
