### ISSUE TITLE
Using GPIO0 / GPIO2 pins on the ESP-01

### ISSUE THREAD

**Issue by manju-rn** [esphome/issues#640]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266  ESP-01
**Affected component:**

Remote Transmitter https://www.esphome.io/components/remote_transmitter.html
This affects only the Remote Transmitter, Remote Receiver just works fine

**Description of problem:**
ESP-01 does not boot when a remote transmitter is connected to the GPIO2 pin. However, if the signal pin for Remote transmitter is connected after the ESP is booted successfully, then everything works fine including the operation of the Remote Transmitter.

Please see the below test cases for details:
Negative:
1. ESP-01 is connected via UART adapter and have a Remote Transmitter (3 Pin) signal pin connected to the GPIO 2 of the ESP-01. 
2. ESP-01 shows a constant blue light and does not boot up.  
Believe that the GPIO 2 is pulled Low and hence does not allow the ESP to boot up.  

Positive 1:
1. ESP-01 is connected via UART adapter.  Remote Transmitter is NOT yet connected to the GPIO2.
2. After ESP-01 successfully boots up, the Signal pin of the Remote transmitter is then connected to the GPIO2 pin.  This works successfully.

Positive 2:
1. ESP-01 is connected via UART adapter and have a Remote Receiver (3 Pin) signal pin connected to the GPIO 2 of the ESP-01. 
2. ESP-01 boots up and the operation of the Remote Receiver works fine 

So the question is whether this issue of the GPIO2 pulled low is only an issue during Remote Transmitter and  how do I make sure that the GPIO 2 pin is not Low during boot up and subsequently made after boot up?  I can do that in the Arduino code, but how do we specify this in the YAML file?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: esp8266node
  platform: ESP8266
  board: esp01_1m
  includes:

remote_transmitter:
  pin: 2
  carrier_duty_percent: 50%

wifi:
  networks:
  - ssid: !secret myssid
    password: !secret mypass
    hidden: True
  ap:
    ssid: !secret standssid
    password: !secret standpass

web_server:
  port: 8080


# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:

switch:
  - platform: template
    name: espfanspeed
    turn_on_action:
       - remote_transmitter.transmit_raw:
           code: [1258, -442,  1240, -442,  398, -1284,  1242, -442,  1240, -442,  400, -1284,  398, -1284,  398, -1284,  398, -1284,  398, -1284,  1242, -442,  398, -8018]
           carrier_frequency: 38kHz
           repeat: 
             times: 3
sensor:


**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Tried to directly hard code the GPIO 2 to low in the main.cpp before the App.setup is called.

  // ========= YOU CAN EDIT AFTER THIS LINE =========
  digitalWrite(2,LOW);
  App.setup();
}



<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
