### ISSUE TITLE
Max and min temperature limits not only for show

### ISSUE THREAD

**Issue by ThomasNygards** [esphome/issues#6401]
### The problem

In the help, the following is written for [Climate Component](https://esphome.io/components/climate/#config-climate))

**visual** (_Optional_): Visual settings for the climate device - these do not affect operation and are solely for controlling how the climate device shows up in the frontend.

**min_temperature** (_Optional_, float): The minimum temperature the climate device can reach. Used to set the range of the frontend gauge.

**max_temperature** (_Optional_, float): The maximum temperature the climate device can reach. Used to set the range of the frontend gauge.

This gives the impression that max and min temperatures should not affect the limits of the controller,
but in fact they do.
With this configuration 

```
climate:
  - platform: pid
    id: stigarror_controller
    name: "Stigarrör PID Controller"
    sensor: utgaende_element_och_golv
    default_target_temperature: 30°C
    heat_output: shunt_percentage
    control_parameters:
      kp: 0.3460
      ki: 0.000187
      kd: 0
      output_averaging_samples: 5      # smooth the output over 3 samples
      derivative_averaging_samples: 5  # smooth the derivative value over 3 samples
    deadband_parameters:
      threshold_high: 0.5°C       # deadband within +/-0.5°C of target_temperature
      threshold_low: -0.5°C`
```

I get
**Error: Provided temperature 30.4 is not valid. Accepted range is 10.0 to 30.0**

If I change the config to

```
climate:
  - platform: pid
    id: stigarror_controller
    name: "Stigarrör PID Controller"
    sensor: utgaende_element_och_golv
    default_target_temperature: 30°C
    heat_output: shunt_percentage
    visual:
      min_temperature: 10
      max_temperature: 45
    control_parameters:
      kp: 0.3460
      ki: 0.000187
      kd: 0
      output_averaging_samples: 5      # smooth the output over 3 samples
      derivative_averaging_samples: 5  # smooth the derivative value over 3 samples
    deadband_parameters:
      threshold_high: 0.5°C       # deadband within +/-0.5°C of target_temperature
      threshold_low: -0.5°C
```

then all works fine. I.e. I added:
```
    visual:
      min_temperature: 10
      max_temperature: 45
```

My automation is:

```
id: '1696702239366'
alias: Update pid target temperature
description: 'updates pid thermostat based on stigarrör måltemp '
trigger:
  - platform: state
    entity_id:
      - input_number.stigarror_maltemp
condition: []
action:
  - data:
      temperature: '{{ states(''input_number.stigarror_maltemp'')| float(0) }}'
    target:
      entity_id: climate.stigarror_pid_controller
    action: climate.set_temperature
mode: single
```

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.2

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
That's HA.  How are you setting the temperature?  It's not the esphome climate component giving that message.

**Comment by ThomasNygards** [comment]
> That's HA. How are you setting the temperature? It's not the esphome climate component giving that message.

Ok. anyhow, this is the action in the automation that sets the temperature:

```
action:
  - data:
      temperature: '{{ states(''input_number.stigarror_maltemp'')| float(0) }}'
    target:
      entity_id: climate.stigarror_pid_controller
    action: climate.set_temperature
```
