### ISSUE TITLE
Time Component timezone acting in the opposite direction

### ISSUE THREAD

**Issue by leofig-rj** [esphome/issues#6403]
### The problem

Using the Time Component.
When I define timezone: America/Sao_Paulo, the result is three hours more than GMT0.
It should have been three hours less.

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.0b6

### What platform are you using?

ESP32-IDF

### Board

esp32dev

### Component causing the issue

Time Component

### Example YAML snippet

```yaml
time:
  - platform: ds1307
    id: time_ds1307
    i2c_id: i2c_bus
    timezone: America/Sao_Paulo
```
