### ISSUE TITLE
ESP32-S3 | Failed config sensor.adc: GPIO14 is not a reserved pin.

### ISSUE THREAD

**Issue by fuef** [esphome/issues#6406]
/bug
### The problem

ESP32-S3's ADC2 channel GPIO14 coexists with WiFi just fine - e.g. [L274](https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/2325b3a1640344611885fd2c37c89259d9645bf2/examples/demo/demo.ino#L274). The [corresponding errata](https://docs.espressif.com/projects/esp-idf/en/v5.3/esp32s3/api-reference/peripherals/adc_oneshot.html#hardware-limitations) wording is less restrictive than it used to be for ESP32 platform a few years ago.

The internet is full of misconceptions and wrong beliefs. It could be about time to remove one of them in [ESP32-S3 ADC2 part](https://esphome.io/components/sensor/adc.html#esp32-pins).

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

Lilygo T5 4.7 Inch E-Paper ESP32-S3 V2.4

### Component causing the issue

sensor.adc

### Example YAML snippet

```yaml
---
esphome:
  on_boot:
    then:
      pcf8563.read_time:
  name: lilygo-t547plus
  platformio_options:
    board_build.flash_size: 16MB
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: qio
    board_build.psram_type: opi
    board_upload.maximum_size: 16777216
    build_flags:
      - "-DARDUINO_USB_MODE=1"
      - "-DARDUINO_USB_CDC_ON_BOOT=1"
  libraries:
    - SPI

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

sensor:
  - platform: adc
    id: battery_voltage
    pin:
      number: GPIO14
      ignore_pin_validation_error: true

time:
  - platform: sntp
    id: internet_time

font:
  - file: fonts/NotoSans-Bold.ttf
    id: font_clock
    size: 300
    glyphs: ":0123456789"

external_components:
  - source: github://nickolay/esphome-lilygo-t547plus
    components: ["t547"]

display:
  - platform: t547
    update_interval: 30s
    lambda: >
      it.strftime(it.get_width()/2, it.get_height()/2-150, id(font_clock),
      TextAlign::TOP_CENTER, "%H:%M", id(internet_time).now());
```

### Anything in the logs that might be useful for us?

```txt
esphome compile t547plus.yaml
INFO ESPHome 2024.10.2
INFO Reading configuration t547plus.yaml...
Failed config

sensor.adc: [source t547plus.yaml:47]
  platform: adc
  id: battery_voltage
  
  GPIO14 is not a reserved pin.
  pin: 
    number: GPIO14
    ignore_pin_validation_error: True
```

### Additional information

All the possible surrounding evidence is [logged in here](https://community.home-assistant.io/t/how-to-fix-adc2-on-esp32-s3-platform/766162).

Switching to `esp32.framework.type`: `esp-idf` results in exactly the same set of errors.
