### ISSUE TITLE
T-ETH-Lite Ehternet not working

### ISSUE THREAD

**Issue by halogen28372** [esphome/issues#6408]
### The problem

When using the Lilygo T-ETH-Lite with W5500 the Ethernet connection doens't work when using the esp-idf framework.  It does work when using the Arduino framework.

### Which version of ESPHome has the issue?

 2024.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.3

### What platform are you using?

ESP32

### Board

Lilygo T-ETH-Lite ESP32-S3-WR0OM-1

### Component causing the issue

ethernet

### Example YAML snippet

```yaml
esphome:
  name: multisensor-lilygo-01
  friendly_name: multisensor-lilygo-01

esp32:
  board: esp32s3box
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""


ota:
  - platform: esphome
    password: ""


# Ethernet configuration for W5500 with specified pins
ethernet:
  type: W5500
  clk_pin: GPIO10          # SCLK
  mosi_pin: GPIO12         # MOSI
  miso_pin: GPIO11         # MISO
  cs_pin: GPIO9            # CS
  interrupt_pin: GPIO13    # INT
  reset_pin: GPIO14        # RST
```
