### ISSUE TITLE
Dashboard status light not working across subnets/zones

### ISSUE THREAD

**Issue by tvwerkhoven** [esphome/issues#641]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Home-built

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP8266, Wemos D1 mini pro v2.0.0

**Affected component:** esphome dashboard status light/board ping

**Description of problem:** The status light on the esphome dashboard does not appear to work for boards on a different subnet/zones.

I have two network zones:
1. Default: 172.16.0.0/24, access to everything
2. IoT: 172.16.1.0/24, access to LAN only, where I run my IoT devices.

Everything else works:
1. I can ping the board across zones
2. I can reach the esphome webserver across zones
3. I can push OTA updates across zones
4. I can see the status of esphome.io boards on the **same** zone (either default or IoT)

the only thing not working is the status light **across** zones.

**Problem-relevant YAML-configuration entries:** not sure this is relevant, see below
```yaml
esphome:
  name: esp_bedroom
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: "SSID-IoT"
  password: "passwd"
  fast_connect: True # Required to connect to hidden SSIDs
  domain: ".lan"

# Enable logging - set to different hardware
# https://quinled.info/2019/05/19/quinled-dig-uno-esphome-home-assistant-sample-configuration/
logger:
  hardware_uart: uart1

web_server:
  port: 80

ota:

i2c:
  sda: 4
  scl: 5
  scan: True

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Example configuration entry
sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
      id: bme_280_temp
    pressure:
      name: "BME280 Pressure"
      id: bme_280_press
    humidity:
      name: "BME280 Humidity"
      id: bme_280_rh
    address: 0x76
    update_interval: 60s

```

**Logs (if applicable):** N/A

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

In the Safari Developer Tools I can see a fetch for `ping` being sent out every second, so some mechanism is working.
