### ISSUE TITLE
Entities of two devices mixing up and devices not working reliably

### ISSUE THREAD

**Issue by stefangries** [esphome/issues#6412]
### The problem

Two of my ESPHome devices show very strange behavior. Since I had problems with them, I removed them from Home Assistant and wanted to set them up again. Now the following always happens:

- I add the first device. It is added correctly. In my case, it is a device with the IP *.205 and the name "Ulanzi Wohnzimmer". The device has 8 entities.
- I add the second device (IP *.147, name "Ulanzi Schlafzimmer"). Sometimes I get the message that the device has already been added. The device does not appear in the list. However, the first device is given more entities. If you look at the list, you will see a mix of entities from the first and second device.

Here is a video of the situation:
![image](https://github.com/user-attachments/assets/a029b8fc-09bb-4720-afa8-d927b860f784)

I have already tried in various ways to remove both devices, add them again, change their host names, change API passwords... none of it helped.

This issue appeared after upgrading my devices to ESPHome 2024.10.0. 
For me, I can only solve this issue by going back to the Addon Version ESPHome 2024.9.2 (and downgrading the devices firmware as well). The issue is still present in ESPHome 2024.10.3. 

FYI: This issue has been discussed in the Home Assistant Forum before:
https://community.home-assistant.io/t/entities-of-two-devices-mixing-up/784624

### Which version of ESPHome has the issue?

2024.10.X

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
substitutions:
  devicename: "ulanzi-wohnzimmer"
  friendly_name: Ulanzi Wohnzimmer
  matrix_pin: GPIO32 
  buzzer_pin: GPIO15
  battery_pin: GPIO34 
  ldr_pin: GPIO35 
  left_button_pin: GPIO26 
  mid_button_pin: GPIO27 
  right_button_pin: GPIO14 
  scl_pin: GPIO22 
  sda_pin: GPIO21 

esphome:
  comment: "Ulanzi TC001 Wohnzimmer"
  name: $devicename
  friendly_name: $friendly_name
  on_boot:
    then:
      - ds1307.read_time:

ota:
  id: my_ota
  platform: esphome
  password: "XXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ulanzi Wohnzimmer AP"
    password: "XXXXXX"

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/lubeda/EsphoMaTrix
    refresh: 60s 
    components: [ ehmtx ]   
  
esp32:
  board: esp32dev

web_server:

image:
   - file: 1pixel.gif
     id: breaking20237
animation:
  - file: 1pixel.gif
    id: breaking202371

font: 
  # adapt the filename to your local settings
  - file: fonts/Calcium.ttf
    id: ehmtx_font
    size: 16
    glyphs:  |
      !?"%‰()+*=,-_.:°µ²³0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnÖÄÜöäüopqrstuvwxyz€$@<>/

ehmtx:
  id: rgb8x32
  matrix_component: ehmtx_display
  icons2html: true
  clock_time: 5           # duration to display the clock after this time the date is display until next "show_screen"
  clock_interval: 60      # show the clock at least each x seconds
  screen_time: 6          # duration to display a screen or a clock/date sequence
  date_format: "%d.%m"    # defaults "%d.%m." (use "%m.%d." for the US)
  time_format: "%H:%M"    # defaults "%H:%M" (use "%I:%M%p" for the US)
  show_date: false        # show the date for show_screen - show_clock seconds otherwise only shows the clock for show_screen seconds, defaults to true
  show_dow: false         # draw the day of week indicator on the bottom of the clock screen
  week_start_monday: true # default monday is first day of week, false = sunday
  yoffset: 8              # the text is aligned BASELINE_LEFT, the baseline defaults to 6
  xoffset: 1              # the text is aligned BASELINE_LEFT, the left defaults to 1
  time_component: ehmtx_time
  font_id: ehmtx_font
  icons: 
    - id: ha
      lameid: 7956
    - id: tempc
      lameid: 2422
    - id: plug
      lameid: 403
    - id: humidity
      lameid: 51764
    - id: co2
      lameid: 30662
    - id: washingmachine
      lameid: 26671
    - id: dishwasher
      lameid: 17590
    - id: eggtimer
      lameid: 42893
    - id: rainbow
      lameid: 1629
    - id: music
      lameid: 17668
    - id: notification
      lameid: 33655
    - id: checkmark
      lameid: 10722
    - id: crossmark
      lameid: 13064
    - id: attentionmark
      lameid: 40526
    - id: printthreed
      lameid: 10527

binary_sensor:
#  - platform: status
#    name: "$friendly_name Status"
  - platform: gpio
    pin:
      number: $left_button_pin
      inverted: true
    name: "Button Links"
#    on_press:
#      then:
#        - number.decrement: screen_brightness
  - platform: gpio
    pin: 
      inverted: true
      number: $mid_button_pin
      mode: INPUT_PULLUP
    name: "Button Mitte"
#    on_press:
#      then:
#        - switch.toggle: displaycontrol
  - platform: gpio
    pin: 
      number: $right_button_pin
      inverted: true
    name: "Button Rechts"
    on_press:
      then:
#        - number.increment: screen_brightness
# example to switch to next screen
        lambda: |-
          id(rgb8x32)->skip_screen();
logger:
  level: INFO

# Enable Home Assistant API
api:
  services:
    - service: alarm
      variables:
        icon_name: string
        texts: string
      then:
        lambda: |-
          id(rgb8x32)->add_screen(icon_name,texts,7,7,true);
          id(rgb8x32)->force_screen(icon_name);
    - service: brightness
      variables:
        brightness: int
      then:
        lambda: |-
          id(rgb8x32)->set_brightness(brightness);
    - service: icons
      then:
        lambda: |-
          id(rgb8x32)->show_all_icons();
    - service: skip_screen
      then:
        lambda: |-
          id(rgb8x32)->skip_screen();
    - service: tuneplay
      variables:
        tune: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return tune;'

number:
  - platform: template
    name: "Displayhelligkeit"
    id: screen_brightness
    min_value: 0
    max_value: 255
    update_interval: 1s
    step: 25
    lambda: |-
      return id(rgb8x32)->get_brightness();
    set_action:
      lambda: |-
        id(rgb8x32)->set_brightness(x);

switch:
  - platform: template
    name: "Display"
    id: displaycontrol
    icon: "mdi:power"
    restore_mode: ALWAYS_ON
    lambda: |-
      return id(rgb8x32)->show_display;
    turn_on_action:
      lambda: |-
        id(rgb8x32)->set_display_on();
    turn_off_action:
      lambda: |-
        id(rgb8x32)->set_display_off();

sensor:
#  - platform: sht3xd   # Bringt nur Quatsch-Werte, da interner Sensor
#    temperature:
#      name: "$friendly_name Temperature"
#    humidity:
#      name: "$friendly_name Humidity"
#    update_interval: 60s
  - platform: adc
    pin: $battery_pin
    name: "Akku"
    id: battery_voltage
    update_interval: 10s
    device_class: battery
    accuracy_decimals: 0
    attenuation: auto
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
      - multiply: 1.6
      - lambda: |-
          int value = ((x - 3) / 0.69 * 100.00);
          if (value > 100) {
            return 100;
          } else {
            return value;
          }
    unit_of_measurement: '%'
  - platform: adc
    id: light_sensor
    name: "Raumhelligkeit"
    pin: $ldr_pin
    update_interval: 10s
    attenuation: auto
    unit_of_measurement: lx
    device_class: illuminance
    accuracy_decimals: 0
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0 - 15 ;
    on_value:
      then:
         lambda: |-  
          int cbright = (0.266*x)+42;
          id(rgb8x32)->set_brightness(cbright);
    
output:
  - platform: ledc
    pin: $buzzer_pin
    id: rtttl_out

rtttl:
  output: rtttl_out

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

light:
  - platform: neopixelbus
    id: ehmtx_light
    type: GRB
    variant: WS2812
    pin: $matrix_pin
    num_leds: 256
    color_correct: [30%, 30%, 30%]
    name: "$friendly_name Light"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      lambda: |-
         id(ehmtx_display)->set_enabled(false);
    on_turn_off:
       lambda: |-
         id(ehmtx_display)->set_enabled(true);
    internal: True # Braucht man in HA nicht...

time:
  - platform: homeassistant
    on_time_sync:
      then:
        ds1307.write_time:
  - platform: ds1307
    update_interval: never
    id: ehmtx_time
  
display:
  - platform: addressable_light
    id: ehmtx_display
    addressable_light_id: ehmtx_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (y % 2 == 0) {
        return (y * 32) + x;
      }
      return (y * 32) + (31 - x);
    rotation: 0°
    update_interval: 16ms
    auto_clear_enabled: true
    lambda: |-
      id(rgb8x32)->tick();
      id(rgb8x32)->draw();
```
