### ISSUE TITLE
[midea] Follow me action accepts non-finite float, compressor turns off in heat mode

### ISSUE THREAD

**Issue by DjordjeMandic** [esphome/issues#6413]
### The problem

About a title, to make it clear right away, I didn't check it in cool mode but I think that same happens also. Integration reads 37c as current temperature after NAN is sent via follow me action. Sometimes i get failed readings from DHT22 sensor, which get accepted by follow me action. Follow me action should check for validity of temperature float parameter before casting it to uint8_t

And here is history graph for samsung ar12txhqasineu/ar3500 showing the issue 
![image](https://github.com/user-attachments/assets/28f15b2f-6064-4271-be2a-a6f7d9a32abd)

### Which version of ESPHome has the issue?

2024.10.3-dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

midea

### Example YAML snippet

```yaml
esphome:
  on_boot:
    - number.set:
        id: climate_follow_me_error_cnt
        value: 0

number:
  - platform: template
    id: climate_follow_me_error_cnt
    internal: true
    entity_category: "diagnostic"
    optimistic: true
    min_value: 0
    max_value: 9999999
    step: 1
    on_value:
      then:
        - sensor.template.publish:
            id: climate_follow_me_error_cnt_sensor
            state: !lambda "return x;"

script:
  - id: update_follow_me
    parameters:
      temp: float
    mode: queued
    then:
      - midea_ac.follow_me:
          temperature: !lambda "return temp;"
          beeper: false               # Optional. Beep on update.
      - logger.log: 
          level: INFO
          format: "Follow me temperature updated to %i, actual %.1f"
          args: ['lroundf(id(dht_temp_follow_me).state)', 'id(dht_temp_follow_me).state']
          tag: "MideaFollowMe"

climate:
  - platform: midea
    id: midea_climate
    name: Living room AC        # Use a unique name.
    period: 1s                  # Optional
    timeout: 2s                 # Optional
    num_attempts: 3             # Optional
    autoconf: false              # Autoconfigure most options.
    beeper: true                # Beep on commands.
    visual:                     # Optional. Example of visual settings override.
      min_temperature: 17 °C    # min: 17
      max_temperature: 30 °C    # max: 30
      temperature_step: 1 °C    # min: 1
    supported_modes:            # All capabilities in this section detected by autoconf.
      - FAN_ONLY                # This capability is always used.
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    custom_fan_modes: 
      - SILENT
      - TURBO
    supported_presets:          # All capabilities in this section detected by autoconf.
      - BOOST
      - SLEEP  
    custom_presets:             # All capabilities in this section detected by autoconf.
      - FREEZE_PROTECTION
    supported_swing_modes:
      - VERTICAL                # This capability is always used.
    outdoor_temperature:        # Optional. Outdoor temperature sensor (may display incorrect values after long inactivity).
      name: AirCon Outdoor Air Temperature
    on_state: 
      then:
        lambda: |-
          if (x.current_temperature >= 37.0f) {
            auto call = id(climate_follow_me_error_cnt).make_call();
            call.number_increment(true);
            call.perform();
            ESP_LOGW("FollowMe", "Follow me transaction failed, ac got temp: %.1f", x.current_temperature);
          }

sensor:
  - platform: dht
    pin: GPIO5
    temperature:
      id: dht_temp
      name: "Living Room Temperature"
    humidity:
      id: dht_humi
      name: "Living Room Humidity"
    update_interval: 3s
  - platform: copy
    source_id: dht_temp
    id: dht_temp_follow_me
    internal: true
    filters:
      - throttle: 10s
      - heartbeat: 45s             # Maximum interval between updates.
      - debounce: 1s
    on_value:
      if:
        condition:
          switch.is_on: follow_room_temp_sw
        then:
          - script.execute: 
              id: update_follow_me
              temp: !lambda "return x;"
  - platform: template
    name: "Follow Me Error Count"
    id: climate_follow_me_error_cnt_sensor
    icon: mdi:counter
    accuracy_decimals: 0
    state_class: "total"
    entity_category: "diagnostic"
```

### Anything in the logs that might be useful for us?

```txt
Log might be helpful:

Nov 06 18:25:58	1	kern	info		- samsungac MideaFollowMe - - - ﻿[I][MideaFollowMe:191]: Follow me temperature updated to 24, actual 23.6
.
.
.
Nov 08 04:47:34	1	kern	warning	- samsungac dht - - - ﻿[W][dht:177]	Falling edge for bit 39 failed!
Nov 08 04:47:34	1	kern	warning	- samsungac dht - - - ﻿[W][dht:060]	Invalid readings! Please check your wiring (pull-up resistor, pin number) and consider manually specifying the DHT model using the model option.
Nov 08 04:47:34	1	kern	warning	- samsungac component - - - ﻿[W][component:157]	Component dht.sensor set Warning flag: unspecified
Nov 08 04:47:37	1	kern	warning	- samsungac component - - - ﻿[W][component:170]	Component dht.sensor cleared Warning flag
Nov 08 04:47:47	1	kern	warning	- samsungac component - - - ﻿[W][component:237]	Component sensor took a long time for an operation (186 ms).
Nov 08 04:47:47	1	kern	warning	- samsungac component - - - ﻿[W][component:238]	Components should block for at most 30 ms.
Nov 08 04:47:48	1	kern	warning	- samsungac FollowMe - - - ﻿[W][FollowMe:379]	Follow me transaction failed, ac got temp: 37.0
```
```


### Additional information
