### ISSUE TITLE
pulse_counter incorrect with higher frequencies (kHz)

### ISSUE THREAD

**Issue by gmanic** [esphome/issues#6416]
### The problem

I use higher frequencies (10-200 kHz) to implement a capacitive tank monitor via an ESP32 (-> hardware pulse counter).

These higher frequencies are not counted correctly, I even get negative values from the pulse_counter (while only incrementing) - this should be impossible.
I would tend to think that the counter overflow is not properly setup to count such high pulse counts correctly.
This is possible, as a ESP32 frequency monitor up to / above 1 MHz has been successfully implemented.

Correct values read with a scope on that GPIO are between like 60kHz and 150kHz, while the sensor yaml below shows like -130kHz and 45kHz.

### Which version of ESPHome has the issue?

2024.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.0

### What platform are you using?

ESP32

### Board

esp32 D1 mini

### Component causing the issue

pulse_counter

### Example YAML snippet

```yaml
sensor:
  - platform: pulse_counter
    pin: 
      number: GPIO15
      mode:
        input: true
        pulldown: true
    internal_filter: 2us
    update_interval: 1s
    id: grau_tanklevel
    device_class: frequency
    state_class: measurement
    unit_of_measurement: "kHz"
    filters:
      - multiply: 0.001
      - multiply: 60
```

### Additional information

 My understanding of the src is, that in case the hw-pcnt (esp32) is used, the variable counter (via pulse_counter_t) is defined as int16_t, while the software pcnt uses int32_t.
The +/- problem seems to be directly related to overflows.
