### ISSUE TITLE
Breaking compile error on ESPHome 2024.10.3 in toolchain-xtensa file stl_pair.h for all ESPHome devices

### ISSUE THREAD

**Issue by WesselHa** [esphome/issues#6417]
### The problem

All devices in ESPHome fail to upgrade from 2024.10.2 to 2024.10.3 due to generic compiler error in toolchain-xtensa, file stl_pair.h. Seemingly two syntax errors, one stray character and "#inclede". Logging of all device is similar.

See log.

### Which version of ESPHome has the issue?

ESPHome 2024.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2024.11.1, Supervisor 2024.1.2, Operating System 13.2

### What platform are you using?

ESP8266

### Board

board: esp01_1m; framework: arduino; platform: platformio/espressif8266@4.2.1

### Component causing the issue

toolchain-xtensa

### Example YAML snippet

```yaml
esphome:
  name: gistkast-controller
  friendly_name: Gistkast Controller

esp8266:
  board: esp01_1m

switch:
  - platform: gpio
    pin: 14
    name: Heater
  - platform: gpio
    pin: 12
    name: Cooler

one_wire:
  - platform: gpio
    pin: GPIO16

sensor:
  - platform: dallas_temp
    address: 0x7901145ebdd02728
    name: "Sensor 1"
    accuracy_decimals: 2
    filters:
      - offset: 0.242
  - platform: dallas_temp
    address: 0x6801145eb7ab0f28
    name: "Sensor 2"
    accuracy_decimals: 2
    filters:
      - offset: -0.133
  - platform: dallas_temp
    address: 0xea01144a80c3aa28
    name: "Sensor 3"
    accuracy_decimals: 2
    filters:
      - offset: -0.070
  - platform: dallas_temp
    address: 0x58011913e5edad28
    name: "Sensor 4"
    accuracy_decimals: 2
    filters:
      - offset: -0.195
  - platform: dallas_temp
    address: 0xbb01144a724eaa28
    name: "Sensor 5"
    accuracy_decimals: 2
    filters:
      - offset: -0.008
  - platform: dallas_temp
    address: 0x7401144a9c9faa28
    name: "Sensor 6"
    accuracy_decimals: 2
    filters:
      - offset: 0.242
  - platform: dallas_temp
    address: 0x3801144ac0d0aa28
    name: "Sensor 7"
    accuracy_decimals: 2
    filters:
      - offset: 0.055
  - platform: dallas_temp
    address: 0xea01144b120caa28
    name: "Sensor 8"
    accuracy_decimals: 2
    filters:
      - offset: -0.133

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
  platform: esphome
  password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gistkast-Controller"
    password: "..."

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.10.3
INFO Reading configuration /config/esphome/gistkast-controller.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing gistkast-controller (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.6
Compiling .pioenvs/gistkast-controller/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/gistkast-controller/src/esphome/components/api/api_frame_helper.cpp.o
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/stl_algobase.h:64,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/deque:60,
                 from src/esphome/components/api/api_frame_helper.h:3,
                 from src/esphome/components/api/api_connection.h:5,
                 from src/esphome/components/api/api_connection.cpp:1:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/stl_pair.h:49:5: error: stray '\16' in program
   49 |  */J/** @file bits/stl_pair.h
      |     ^
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/stl_pair.h:57:2: error: invalid preprocessing directive #inclede; did you mean #include?
Compiling .pioenvs/gistkast-controller/src/esphome/components/api/api_pb2.cpp.o
```

### Additional information

All devices with different ESP8266 boards same issue. None compiles.
Also, compiling from ESPHome ad-on of HA makes no difference. New install or upgrade, same issue.
