### ISSUE TITLE
ERROR Error binary size: Error: ESP does not have enough space to store OTA file. Please try flashing a minimal firmware (remove everything except ota)

### ISSUE THREAD

**Issue by deanfourie1** [esphome/issues#6420]
### The problem

When attempting to update ESP8266 devices, I get the following error in esphome.

`ERROR Error binary size: Error: ESP does not have enough space to store OTA file. Please try flashing a minimal firmware (remove everything except ota)`

This appears to be only effecting the board

```
esp8266:
  board: esp01_1m
```

### Which version of ESPHome has the issue?

2024.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.1

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

not sure?

### Example YAML snippet

```yaml
esphome:
  name: camper-wall-lights
  friendly_name: camper-wall-lights

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

web_server:
  port: 80
  log: true
  local: True
  version: 3
  include_internal: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    bssid: 
  fast_connect: true
  power_save_mode: none

  # Optional manual IP
  manual_ip:
    static_ip: 
    gateway: 
    subnet: 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Camper-Wall-Lights"
    password: ""

captive_portal:

output:
  - platform: gpio
    pin: GPIO0
    id: wall_lights

light:
  - platform: binary
    name: "Camper Wall Lights"
    output: wall_lights

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime

time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Device Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: IP Address
    bssid:
      name: Connected BSSID

  # human readable update text sensor from sensor:uptime
  - platform: template
    name: Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
```
