### ISSUE TITLE
Waveshare E-Paper driver and 7.5v2 Epaper display update_interval does not work

### ISSUE THREAD

**Issue by hblockx** [esphome/issues#6421]
### The problem

For me using the epaper display is drawing everything perfectly but 
update_interval does not change the update interval. For me the screen keeps refreshing every second, no matter what value is being set...

### Which version of ESPHome has the issue?

2024.10.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

waveshare epaper driver board

### Example YAML snippet

```yaml
display:
  - platform: waveshare_epaper
    id: screen1
    cs_pin: 15
    dc_pin: 27
    busy_pin:
      number: 25
      inverted: true 
    reset_pin: 26
    model: 7.50inV2
    reset_duration: 2ms
    update_interval: 100s
    lambda: |
      it.image(1, 1, id(image1));
```
