### ISSUE TITLE
Modbus error function code: 0x3 exception: 2 (ESP32 + RS485 Module)

### ISSUE THREAD

**Issue by michelmalle** [esphome/issues#6423]
### The problem

Hello,

I try to read out several values of my Siemens 7KT1666 (MID) Smartmeter and facing the following issue:

- Using the tool "ModbusRtuMaster" on my Macbook + USB RS486 RTU adapter gets me a valid Modbus connection and the ability to read out the slave device.
- Trying the same using an ESP32 + RS485 module gets me Modbus Exception Codes
- Error appears with and without terminating by 120 Ohm resistor

[19:58:24][D][modbus:125]: Modbus error function code: 0x83 exception: 2
[19:58:24][E][modbus_controller:092]: Modbus error function code: 0x3 exception: 2 
[19:58:24][E][modbus_controller:101]: Modbus error - last command: function code=0x3  register address = 0x1  registers count=1 payload size=0

I attached the logfile.
[logs_sm-modbus_run.txt](https://github.com/user-attachments/files/17707652/logs_sm-modbus_run.txt)

Any ideas, what I could try to fix that?

Thanks!
Michel

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.9.3

### What platform are you using?

ESP32

### Board

JZK TTL to RS485

### Example YAML snippet

```yaml
esphome:
  name: sm-modbus
  friendly_name: SM-Modbus

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sm-Modbus Fallback Hotspot"
    password: "xxx"

captive_portal:

web_server:


############### MODBUS CONFIGURATION ##############
uart:
  id: uart_1
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 38400 # Laut Setting am Smartmeter: default: 9600
  parity: NONE
  stop_bits: 1


modbus:
  id: modbus_1
  uart_id: uart_1 

modbus_controller:
  - id: energy_meter
    address: 0x01  # Modbus-Adresse des Smartmeters
    modbus_id: modbus_1
    update_interval: 10s #später hochsetzen......

sensor:
  - platform: modbus_controller
    modbus_controller_id: energy_meter
    name: "Spannung_L1"
    register_type: holding # "holding": function code 3 / "read": function code 4
    address: 0001  # Adresse für Spannung L1 mit Offset -1
    value_type: U_WORD
    unit_of_measurement: "V"
    filters:
      - multiply: 0.01 # Eventuell anpassen je nach Skala des Zählers
```

### Anything in the logs that might be useful for us?

```txt
[19:57:54][D][modbus:125]: Modbus error function code: 0x83 exception: 2
[19:57:54][E][modbus_controller:092]: Modbus error function code: 0x3 exception: 2 
[19:57:54][E][modbus_controller:101]: Modbus error - last command: function code=0x3  register address = 0x1  registers count=1 payload size=0
```
