### ISSUE TITLE
Ethernet module W5500 does not work with dhcp

### ISSUE THREAD

**Issue by Allkorolev** [esphome/issues#6431]
### The problem

There is an ESP32 with an Ethernet module W5500. 
If you set to work with manual_ip, then the web interface will load, if you do not specify manual_ip, i.e. We switch the module to the mode of obtaining an IP address via dhcp, then it is not possible to log into the module, it says that there is no connection to the site, although the module receives an IP address - this can be seen from the router settings.

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.0

### What platform are you using?

ESP32

### Example YAML snippet

```yaml
ethernet:
  type: W5500
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  cs_pin: GPIO5
  interrupt_pin: GPIO32
  reset_pin: GPIO33
  clock_speed: 25Mhz
  #manual_ip:
  #  static_ip: 10.10.0.229
  #  gateway: 10.10.0.1
  #  subnet: 255.255.255.0
```
