### ISSUE TITLE
ESPHome ac-dimmer with MCP23S17 Component

### ISSUE THREAD

**Issue by NytoxRex0** [esphome/issues#6432]
### The problem

The "_Gate_Pin_" from _AC_Dimmer_ component is not available to use for pins of the _MCP23S17_. This device should be more than fast enough for this application, please alter the code to allow this configuration.

### Which version of ESPHome has the issue?

2024.8.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.9.1

### What platform are you using?

ESP32

### Board

WROOM-S2

### Component causing the issue

ac-dimmer, MCP23S17

### Example YAML snippet

```yaml
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

mcp23s17:
  - id: 'mcp23s17_hub'
    cs_pin: GPIO02
    deviceaddress: 0

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 
      mcp23xxx: mcp23s17_hub
      # Use pin number 0
      number: 0
      # One of INPUT or INPUT_PULLUP
      mode:
        output: true
      inverted: false
    zero_cross_pin:
      number: GPIO35
      mode:
        input: true
      inverted: yes

light:
  - platform: monochromatic
    output: dimmer1
    name: Dimmerized Light
```
