### ISSUE TITLE
Flesh writes Wear Leveling

### ISSUE THREAD

**Issue by vgdh** [esphome/issues#6439]
### The problem

It is not clear is ESPhome uses Wear Leveling for  **Global Variables** with options: **restore_value: true** and **esp8266_restore_from_flash** or no.
If no it should be doing so. https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/storage/wear-levelling.html
How often can I write into it until the flash will die?

### Which version of ESPHome has the issue?

 2024.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

latest

### What platform are you using?

ESP8266

### Example YAML snippet

```yaml
globals:
  - id: saved_position_1
    type: int
    initial_value: '0'
    restore_value: true
```
