### ISSUE TITLE
Icorrect MODBUS implementation of CRC calculation for "Write Multiple registers (0x10)" 

### ISSUE THREAD

**Issue by RooNix47** [esphome/issues#6440]
### The problem

Using modbus component in "SERVER" mode, when master try to write registers using 0x10 command "Write Multiple registers" then errors with crc calculation formulae apears. 

actual code for selecting data for CRC
`    
// the response for write command mirrors the requests and data starts at offset 2 instead of 3 for read commands
    if (function_code == 0x5 || function_code == 0x06 || function_code == 0xF || function_code == 0x10) {
      data_offset = 2;
      data_len = 4;
    }
`
Using this for function_code == 0x10 is incorrect because length of frame is not still, and additional  number based on data length should be added when function_code == 0x10.

Proposal to add separate if function for Write Multiple Register function code. 

### Which version of ESPHome has the issue?

2024.10.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32

### Board

custom ESP32 board

### Component causing the issue

MODBUS

### Example YAML snippet

```yaml
uart:
  - id: uart_modbus_server
    tx_pin: 23
    rx_pin: 22
    baud_rate: 9600
    stop_bits: 1
    parity: NONE

modbus:
   id: modbus_server
   uart_id: uart_modbus_server
   flow_control_pin: 18
   role: server


modbus_controller:
  - modbus_id: modbus_server
    address: 7
    server_registers:
      - address: 0
        value_type: U_WORD
        read_lambda: |-
          return id(mod_00_controller_vendor).state;
      - address: 1
        value_type: U_WORD
        read_lambda: |-
          return id(mod_01_controller_state).state;
```
