### ISSUE TITLE
LVGL display image

### ISSUE THREAD

**Issue by kevin75001** [esphome/issues#6447]
### The problem

Trying to display an image (100x100 blue square) using LVGL result to an unavailable device

### Which version of ESPHome has the issue?

2024.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32

### Board

Waveshare ESP32-S3 7inch capacitive

### Component causing the issue

lvgl/image

### Example YAML snippet

```yaml
esphome:
  name: tablette-rdc
  friendly_name: Home Display
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

external_components:
  - source: github://pr#7611
    refresh: 0min
    components: [lvgl,image]
    
  - source: github://pr#7356
    components: [ch422g]
    refresh: 0min

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG

i2c:
  sda: GPIO08
  scl: GPIO09
  scan: True
  id: bus_a

display:
  - platform: rpi_dpi_rgb
    id: my_display
    auto_clear_enabled: false
    update_interval: never
    color_order: RGB
    pclk_frequency: 14MHz
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: false
    hsync_back_porch: 10 #30
    hsync_front_porch: 20 #210 
    hsync_pulse_width: 10 #30
    vsync_back_porch: 10 #4
    vsync_front_porch: 10 #4
    vsync_pulse_width: 10 #4
    data_pins:
      red:
        - 1         #r3
        - 2         #r4
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7

font:
  - file: "gfonts://Roboto"
    id: chu_nano
    size: 12

  - file: "gfonts://Roboto"
    id: temp_salon_fnt
    size: 48

  - file: "gfonts://Material+Symbols+Outlined"
    id: icons_50
    size: 50
    glyphs: ["\U0000e425"] # mdi-timer
    
ch422g:
  - id: ch422g_hub

touchscreen:
  platform: gt911
  id: my_touch
  interrupt_pin: GPIO4
  reset_pin:
    ch422g: ch422g_hub
    number: 1 #edit: It's on IO1
    mode: OUTPUT
  on_touch:
    - lambda: |-
        ESP_LOGI("Touch", "Touch detected at x=%d, y=%d", touch.x, touch.y);


time:
  - platform: homeassistant
    id: time_comp
    on_time:
        seconds: 0
        minutes: /1
        then:
          - lvgl.label.update:
              id: ntm
              text:
                time_format: "%H:%M"
                time: !lambda return id(time_comp).now();
          - lvgl.label.update:
              id: date
              text:
                time_format: "%A %d %B %Y"
                time: !lambda return id(time_comp).now();
          - lvgl.label.update:
              id: temp_salon_lbl
              text: !lambda return id(temp_salon).state;
          - lvgl.label.update:
              id: temp_ext_lbl
              text: !lambda return id(temp_ext).state;
          - lvgl.label.update:
              id: temp_olivia_lbl
              text: !lambda return id(temp_olivia).state;
          - lvgl.label.update:
              id: temp_oscar_lbl
              text: !lambda return id(temp_oscar).state;
          - lvgl.label.update:
              id: consigne_rdc_lbl
              text: !lambda return id(consigne_rdc).state;
          - lvgl.arc.update:
              id: arc_id
              value: !lambda |-
                          auto n = parse_number<float>(id(consigne_rdc).state);
                          return n.has_value() ? n.value() : NAN;

lvgl:
  displays: my_display
  touchscreens:
    - touchscreen_id: my_touch
  buffer_size: 25%
  pages:
    - id: home_page
      widgets:
        - obj:
            height: 480
            width: 800
            pad_all: 10
            border_width: 0
            bg_color: 0x000000
            radius: 0
            widgets:
              # Thermostat
              - obj:
                  x: 60
                  y: 60
                  height: 260
                  width: 300
                  border_width: 0
                  radius: 0
                  bg_opa: 0%
                  widgets:
                    # Temperature
                    - label:
                        align: CENTER
                        id: temp_salon_lbl
                        text_color: 0xFFFFFF
                        text_align: CENTER
                        text_font: temp_salon_fnt
                        text: "0.0"
                    # Consigne   
                    - label:
                        id: consigne_rdc_lbl
                        text_color: 0xFF00FF
                        text_align: CENTER
                        y: 150
                        x: 150
                        text: "0.0"
              - label:
                 id: ntm
                 text_color: 0xFFFFFF
                 align: TOP_RIGHT
                 text_font: temp_salon_fnt
                 text:
                   time_format: "%H:%M"
                   time: !lambda return id(time_comp).now();
              - label:
                 id: date
                 text_color: 0xFFFFFF
                 align: TOP_LEFT
                 text:
                   time_format: "%A %d %B %Y"
                   time: !lambda return id(time_comp).now();
              - label:
                  id: temp_ext_lbl
                  text_color: 0xFFFFFF
                  x: 400
                  y: 60
                  text_font: temp_salon_fnt
                  text: "0.0"
              - label:
                  id: temp_olivia_lbl
                  text_color: 0xFFFFFF
                  x: 400
                  y: 150
                  text_font: temp_salon_fnt
                  text: "0.0"
              - label:
                  id: temp_oscar_lbl
                  text_color: 0xFFFFFF
                  x: 400
                  y: 250
                  text_font: temp_salon_fnt
                  text: "0.0"
              - arc:
                  x: 60
                  y: 60
                  id: arc_id
                  height: 300
                  width: 300
                  value: 21
                  min_value: 10
                  max_value: 30
                  adjustable: true

              - image:
                  align: CENTER
                  src: cat_image
                  id: img_id
                  radius: 11
                  clip_corner: true
                  
image:
  - file: test.jpg
    id: cat_image
    resize: 100x100
           
text_sensor:
  - platform: homeassistant
    name: "Temperature salon"
    entity_id: climate.rdc
    id: temp_salon
    attribute: current_temperature
    filters:
    - append: "°"

  - platform: homeassistant
    name: "Temperature ext"
    entity_id: sensor.temperature_25
    id: temp_ext
    filters:
    - append: "°"
    - prepend: "Ext: "
  - platform: homeassistant
    name: "Temperature ext"
    entity_id: sensor.chambre_olivia
    id: temp_olivia
    filters:
    - append: "°"
    - prepend: "Olivia: "
  - platform: homeassistant
    name: "Temperature ext"
    entity_id: sensor.chambre_oscar
    id: temp_oscar
    filters:
    - append: "°"
    - prepend: "Oscar: "
    
  - platform: homeassistant
    name: "Consigne"
    entity_id: climate.rdc
    id: consigne_rdc
    attribute: temperature
#    filters:
#    - append: "°"

# Enable Home Assistant API
api:
  encryption:
    key: "<hidden>"

ota:
  - platform: esphome
    password: "<hidden>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tablette-Rdc Fallback Hotspot"
    password: "<hidden>"
```

### Anything in the logs that might be useful for us?

```txt
Nothing, compilation / upload work well
```
