### ISSUE TITLE
Output Component compress unput range

### ISSUE THREAD

**Issue by 1iverea9er** [esphome/issues#6448]
### The problem

I am trying to use the `Output Component` (`Slow PWM Output`) to generate pulses to control the heater. 

The heater I use heats up very quickly and cools down very slowly. Therefore, the adjustment range is shifted from the average value (from 50% to the value of 90%). I also had to use the `inverted: true` parameter. Thus, to compensate, I used the `min_power: 0.90` parameter so that the regulation occurs in the range of 90-100% the input signal. 

In the component management tests, I used the `Monochromatic Light` component. 

I expected my configuration to keep the resolution of the `Monochromatic Light` component 0-100% with step=1 (i.e. 90-100% with step=0.1 of `Output Component`), but in fact it cut before the resolution indicated by the `min_power` & `max_power` parameters, that is, in the range of 90-100% with step=1.

Thus, changes in the brightness of the `Monochromatic Light` in the range of 0-90% do not affect the output of the `Output component` in any way

### Which version of ESPHome has the issue?

2024.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

Output Component

### Example YAML snippet

```yaml
output:
  - platform: slow_pwm
    pin: GPIO5
    id: slow_pwm_output
    period: 30s
    inverted: true
    min_power: 0.9
    max_power: 1


light:
  - platform: monochromatic
    output: slow_pwm_output
    name: Dimmerized Light
```

### Additional information

A similar behavior was obtained for the `AC Dimmer Component`
