### ISSUE TITLE
light platform neopixelbus: pulse effect not working properly

### ISSUE THREAD

**Issue by mibcat** [esphome/issues#6449]
### The problem

The pulse effect which is working fine for monochrome LED is not working properly for (at least) neopixelbus LED.

Regardless of the **transition_length** settings (on_length / off_length) the LED is light up immediately **without a ramp**.

From the [description](https://esphome.io/components/light/index.html#pulse-effect) I would expect this:

```txt
    I   ▲                                                       
        │                                                       
        │                                                       
        │                                                       
100 %  ─┼              **********                               
        │             *          *                              
        │            *            *                             
        │           *              *                            
        │          *                *                  *        
        │         *                  *                *         
        │        *                    *              *          
        │       *                      *            *           
        │      *                        *          *            
  0 %  ─┼     *                          **********             
        └─────┬────────┬────────┬────────┬────────┬────────────►
              │        │        │        │        │             
              0        1s       2s       3s       4s             
```

But I got this:

```txt
    I   ▲                                                       
        │                                                       
        │                                                       
        │                                                       
100 %  ─┼     **********                          *******       
        │     *         *                         *             
        │     *          *                        *             
        │     *           *                       *             
        │     *            *                      *             
        │     *             *                     *             
        │     *              *                    *             
        │     *               *                   *             
        │     *                *                  *             
  0 %  ─┼     *                 *******************             
        └─────┬────────┬────────┬────────┬────────┬────────────►
              │        │        │        │        │             
              0        1s       2s       3s       4s           t
```

### Which version of ESPHome has the issue?

ESPHome 2024.10.3

### What type of installation are you using?

pipx

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32

### Board

ESP-32 Dev Kit C V4

### Component causing the issue

light platform neopixelbus

### Example YAML snippet

```yaml
esphome:
  name: esp32-test
  platform: ESP32
  board: esp32dev
  comment: "Test device"

# Enable logging
logger:
  level: INFO

wifi:
  ssid: tbd
  password: !secret wifi_password

# Enable Home Assistant API
api:
  id: API
  encryption:
    key: !secret haa_key

# Enable OTA
ota:
  - platform: esphome
    password: !secret ota_password

light:
  # ===========================================================================
  # Indicator LED (APA106 RGB LED)
  # ===========================================================================
  - platform: neopixelbus
    name: LED neopixel
    pin: GPIO13
    method: ESP32_I2S_1
    type: RGB
    variant: APA106
    num_leds: 1
    restore_mode: ALWAYS_OFF
    effects:
      - pulse:
          name: pulse 1
          transition_length: 1.0s
          update_interval: 2.0s
      - pulse:
          name: pulse 2
          transition_length: 1.0s
          update_interval: 4.0s

  - platform: monochromatic
    name: LED monochrome
    output: ID_LED_MONOCHROME
    restore_mode: ALWAYS_OFF
    effects:
      - pulse:
          name: pulse 1
          transition_length: 1.0s
          update_interval: 2.0s
      - pulse:
          name: pulse 2
          transition_length: 1.0s
          update_interval: 4.0s
                 
output:
  - platform: ledc
    pin: GPIO26
    id: ID_LED_MONOCHROME
    frequency: 1220Hz
```
