### ISSUE TITLE
#warning "legacy adc calibration driver is deprecated

### ISSUE THREAD

**Issue by derMicro** [esphome/issues#6455]
### The problem

Compiling .pioenvs/p-ku-ble-shellyproxy/src/esphome/components/api/api_connection.cpp.o
In file included from src/esphome/components/adc/adc_sensor.h:10,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
/data/cache/platformio/packages/framework-espidf/components/esp_adc/deprecated/include/esp_adc_cal.h:17:2: warning: #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h" [-Wcpp]
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:11:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
      
Compiling .pioenvs/p-bdo-ble-shellyproxy/src/main.cpp.o
In file included from src/esphome/components/adc/adc_sensor.h:10,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-espidf/components/esp_adc/deprecated/include/esp_adc_cal.h:17:2: warning: #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h" [-Wcpp]
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:11:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~

### Which version of ESPHome has the issue?

2024.11.0 and older

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32-IDF

### Board

ESP32-C3

### Component causing the issue

adc / platformio/espressif32@6.9.0 and 6.7.0 framework-espidf @ 3.50301.0 and 3.50202.0 

### Example YAML snippet

```yaml
sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
    
  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 12db
```

**Comment by edwardtfn** [comment]
Hey @derMicro, do you mind giving PR#7942 a try and let me know the results?
```yaml
external_components:
  - source: github://pr#7940
    components:
      - adc
```

**Comment by edwardtfn** [comment]
Could you please try pr7942 again?

**Comment by edwardtfn** [comment]
Mmmm... This is weird... I can compile with your yaml with no warnings when using esphome/esphome#7942.
I will look a bit more at this.

**Comment by edwardtfn** [comment]
> Exciting ;)
> But this shows me that it makes sense to also report warnings that come from IDF releases that are not yet supported, so that we have enough time.

Yeah, but I think this case specifically is not related to any difference between v5.1.5 and v5.3.1, but something specifically with ESP32-C3 when using any of the idf v5.x.x. Or maybe even this specific board not flagging the `USE_ESP32_VARIANT_ESP32C3` used to define when curve fitting calibration should be used.

**Comment by edwardtfn** [comment]
Please don't leave out the sensor... 😉
Let's make it work. 🙂

By the way, I was expecting this fixed with pr7942, not the pr7940 that I mentioned first.

**Comment by edwardtfn** [comment]
This is not related to the board, as I'm successfully compiling with the exact same settings as you (except by using my passwords).

So, please try this:
```yaml
external_components:
  - source: github://pr#7942
    refresh: 30s
    components:
      - adc
```

and if that still not working, please try this (which points to the same branch used by that pr:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: adc-new-library-espidf-5
    refresh: 30s
    components:
      - adc
```

**Comment by edwardtfn** [comment]
Yeah, that wasn't merged yet.

**Comment by AberDino** [comment]
FYI, I have two Shelly Plus 1PM devices which I recently (three weeks ago or so) flashed with ESPHome. Main reason for doing so, was to be able to calibrate the voltage and power consumption readings, which, for this particular model, was not possible through the native Shelly web interface.

Tonight I updated ESPHome to 2024.12.0 and also received this "legacy adc driver is deprecated" warning. I then included the 'external_components' code as per above, and the warning disappeared.

However, the update to 2024.12.0 caused three further 'warning' messages to appear, which I don't think I had before (but maybe I did...), and one of them you have already fixed @edwardtfn:

> warning: '--' expression of 'volatile'-qualified type is deprecated [-Wvolatile] (and same with '++')

> Warning! Flash memory size mismatch detected. Expected 4MB, found 2MB!
> Please select a proper value in your `sdkconfig.defaults` or via the `menuconfig` target!

> #warning "legacy pcnt driver is deprecated, please migrate to use driver/pulse_cnt.h"

The successful fix for the first warning as per [this page](https://github.com/esphome/esphome/pull/7954).

The successful workaround for the second warning as per [this issue](https://github.com/esphome/issues/issues/6569). 

And for the third warning, I included 'CONFIG_PCNT_SUPPRESS_DEPRECATE_WARN: y' as part of the sdkconfig_options. As it's simply suppressing this warning I don't really consider this a proper fix though, and I'd much rather get the device to use the new driver, but don't know where to start.

I can confirm that with the above fixes / workarounds, the firmware compiles without any warnings.

**Comment by markl3001** [comment]
If you use the Shelly just as BLE proxy, why don't you use the native firmware?

**Comment by Bjk8kds** [comment]
> ```yaml
> pr#7942
> ```

Thanks, pr#7942 works for me even without refresh 30s.
Esphome 2024.12.0

**Comment by edwardtfn** [comment]
> > #warning "legacy pcnt driver is deprecated, please migrate to use driver/pulse_cnt.h"
> 
> And for the third warning, I included 'CONFIG_PCNT_SUPPRESS_DEPRECATE_WARN: y' as part of the sdkconfig_options. As it's simply suppressing this warning I don't really consider this a proper fix though, and I'd much rather get the device to use the new driver, but don't know where to start.

It's just a warning, so you shouldn't worry that much about this... but it should be reported on it's own new issue. 😉

**Comment by matphillips** [comment]
I noticed this warning also, so added 
```
external_components:
  - source: github://pr#7942
    refresh: 30s
    components:
      - adc
```
but the code won't compile, I get this error:

```
streamdeck.yaml: In function 'void setup()':
streamdeck.yaml:342:35: error: cannot convert 'adc1_channel_t' to 'adc_channel_t'
In file included from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/adc/adc_sensor.h:135:35: note:   initializing argument 1 of 'void esphome::adc::ADCSensor::set_channel1(adc_channel_t)'
  135 |   void set_channel1(adc_channel_t channel) {
      |                     ~~~~~~~~~~~~~~^~~~~~~
```

The code from the yaml that uses ADC is:
```
sensor:
  # Battery monitoring
  - platform: adc
    name: "Battery Voltage"
    id: battery_voltage
    pin: GPIO9
    attenuation: auto
    accuracy_decimals: 2
    update_interval: 5s
    unit_of_measurement: V
    device_class: "voltage"
    icon: "mdi:car-battery"
    filters:
      - multiply: 2
      - median:
          window_size: 10
          send_every: 6
          send_first_at: 1
```

**Comment by AberDino** [comment]
Hi @edwardtfn, any idea when your fix will be merged into the "main" code?

**Comment by catdogmaus** [comment]
I have exact same warnings when using humidity sensors. I asked about that in HA forums and it turns out there are **lots** of people with same problems with legacy adc driver.

**Comment by coltography** [comment]
Is this something I can ignore or is there going to be a breaking update to this some day?

**Comment by Bjk8kds** [comment]
> Is this something I can ignore or is there going to be a breaking update to this some day?

just add the external components, prevention is better.

**Comment by coltography** [comment]
I'm not quite sure what that means or how to do that.

**Comment by jcd420** [comment]
just add

```
external_components:
  - source: github://pr#7942
    refresh: 30s
    components:
      - adc
```

it worked for me.

**Comment by cosmicDustOfLightLength** [comment]
```
Compiling .pioenvs/lilygo-t-display-s3-amoled/esp_eth/src/esp_eth.c.o
/config/esphome/lilygo-t-display-s3-amoled.yaml: In function 'void setup()':
/config/esphome/lilygo-t-display-s3-amoled.yaml:437:36: error: cannot convert 'adc1_channel_t' to 'adc_channel_t'
  437 |     min_value: 18
      |                                    ^             
      |                                    |
      |                                    adc1_channel_t
In file included from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/adc/adc_sensor.h:160:35: note:   initializing argument 1 of 'void esphome::adc::ADCSensor::set_channel1(adc_channel_t)'
  160 |   void set_channel1(adc_channel_t channel) {
      |                     ~~~~~~~~~~~~~~^~~~~~~
.
.
.
Compiling .pioenvs/lilygo-t-display-s3-amoled/esp_http_client/esp_http_client.c.o
*** [.pioenvs/lilygo-t-display-s3-amoled/src/main.cpp.o] Error 1
========================= [FAILED] Took 14.14 seconds =========================
```

```
external_components:
  - source: github://pr#7942
    refresh: 30s
    components:
      - adc

esp32:
  board: esp32s3box
  variant: esp32s3
  framework:
    type: esp-idf
    version: latest
  flash_size: 16MB
```

```
# DIY MQ-2 Smoke & Gas Sensor for Home Assistant
  - platform: adc
    pin: GPIO10
    name: "Gas (Carbon/Methane/Propane)"
    update_interval: 1s
    accuracy_decimals: 3
    icon: mdi:meter-gas-outline
    attenuation: 12dB
    filters:
      - or:
        - throttle: 180s
        - delta: 0.01
```
