### ISSUE TITLE
warning: 'void sntp_setservername(u8_t, const char*)' is deprecated:

### ISSUE THREAD

**Issue by derMicro** [esphome/issues#6458]
### The problem

Compiling .pioenvs/p-sz-ble-sensecapnightlight/src/esphome/components/socket/bsd_sockets_impl.cpp.o
src/esphome/components/sntp/sntp_component.cpp: In member function 'virtual void esphome::sntp::SNTPComponent::setup()':
src/esphome/components/sntp/sntp_component.cpp:34:21: warning: 'void sntp_setservername(u8_t, const char*)' is deprecated: use esp_sntp_setservername() instead [-Wdeprecated-declarations]
   34 |   sntp_setservername(0, strdup(this->server_1_.c_str()));
      |   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/esphome/components/sntp/sntp_component.cpp:5:
/data/cache/platformio/packages/framework-espidf@3.50202.0/components/lwip/include/apps/esp_sntp.h:249:6: note: declared here
  249 | void sntp_setservername(u8_t idx, const char *server)
      |      ^~~~~~~~~~~~~~~~~~
src/esphome/components/sntp/sntp_component.cpp:36:23: warning: 'void sntp_setservername(u8_t, const char*)' is deprecated: use esp_sntp_setservername() instead [-Wdeprecated-declarations]
   36 |     sntp_setservername(1, strdup(this->server_2_.c_str()));
      |     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cache/platformio/packages/framework-espidf@3.50202.0/components/lwip/include/apps/esp_sntp.h:249:6: note: declared here
  249 | void sntp_setservername(u8_t idx, const char *server)
      |      ^~~~~~~~~~~~~~~~~~
src/esphome/components/sntp/sntp_component.cpp:39:23: warning: 'void sntp_setservername(u8_t, const char*)' is deprecated: use esp_sntp_setservername() instead [-Wdeprecated-declarations]
   39 |     sntp_setservername(2, strdup(this->server_3_.c_str()));
      |     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cache/platformio/packages/framework-espidf@3.50202.0/components/lwip/include/apps/esp_sntp.h:249:6: note: declared here
  249 | void sntp_setservername(u8_t idx, const char *server)
      |      ^~~~~~~~~~~~~~~~~~
src/esphome/components/sntp/sntp_component.cpp:45:12: warning: 'void sntp_init()' is deprecated: use esp_sntp_init() instead [-Wdeprecated-declarations]
   45 |   sntp_init();
      |   ~~~~~~~~~^~
/data/cache/platformio/packages/framework-espidf@3.50202.0/components/lwip/include/apps/esp_sntp.h:255:6: note: declared here
  255 | void sntp_init(void)
      |      ^~~~~~~~~

### Which version of ESPHome has the issue?

2024.11.0 and older

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32-IDF

### Board

esp32-s3-devkitc-1

### Component causing the issue

sntp / platformio/espressif32@6.7.0 framework-espidf @ 3.50202.0

### Example YAML snippet

```yaml
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Zurich
    servers:
      - 192.168.166.1
    on_time_sync:
      - script.execute: time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update

script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: lvgl_clock_minute
          text:
            format: "%02d"
            args: [ 'id(sntp_time).now().minute' ]

      - lvgl.label.update:
          id: lvgl_clock_hour
          text:
            format: "%02d"
            args: [ 'id(sntp_time).now().hour' ]
      - lvgl.label.update:
          id: lvgl_clock_longdate
          text:
            format: "%s, %02d.%02d.%04d"
            args: 
              - '(new const char *[7]{"Sunntig", "Määntig", "Ziischtig", "Mittwuch", "Dunschtig", "Friitig", "Samschtig"})[id(sntp_time).now().day_of_week-1]'
              - 'id(sntp_time).now().day_of_month'
              - 'id(sntp_time).now().month'
              - 'id(sntp_time).now().year'
```
