### ISSUE TITLE
Display - warning: suggest braces around empty body in an 'else' statement

### ISSUE THREAD

**Issue by derMicro** [esphome/issues#6459]
### The problem

Compiling .pioenvs/p-sz-ble-sensecapnightlight/src/esphome/components/esp32/core.cpp.o
src/esphome/components/display/rect.cpp: In member function 'void esphome::display::Rect::info(const std::string&)':
src/esphome/components/display/rect.cpp:94:57: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
   94 |     ESP_LOGI(TAG, "%s ** IS NOT SET **", prefix.c_str());
      |                                                         ^
```      
   framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    
   and
framework:
    type: esp-idf
    version: 5.2.2
    platform_version: 6.7.0
    #(working on 2024.10.x)
```

### Which version of ESPHome has the issue?

2024.11.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32-IDF

### Board

esp32-s3-devkitc-1 (sensecap indicator)

### Component causing the issue

display 

### Example YAML snippet

```yaml
display:
  - platform: st7701s
    id: sensecap_display
    auto_clear_enabled: false
    data_rate: 4MHz
    update_interval: never
    spi_mode: MODE3
    color_order: RGB
    dimensions:
      width: 480
      height: 480
    invert_colors: true
    transform:
      mirror_x: true
      mirror_y: true
    cs_pin:
      pca9554: pca9554a_device
      number: 4
    reset_pin:
      pca9554: pca9554a_device
      number: 5
    de_pin: GPIO18
    hsync_pin: GPIO16
    vsync_pin: GPIO17
    pclk_pin: GPIO21
    init_sequence:
      - 1 # select canned init sequence number 1
      - delay 5ms
      - [ 0xE0, 0x1F ]  # Set sunlight readable enhancement
    data_pins:
      red:
        - GPIO4         #r1
        - GPIO3         #r2
        - GPIO2         #r3
        - GPIO1         #r4
        - GPIO0         #r5
      green:
        - GPIO10        #g0
        - GPIO9         #g1
        - GPIO8         #g2
        - GPIO7         #g3
        - GPIO6         #g4
        - GPIO5         #g5
      blue:
        - GPIO15        #b1
        - GPIO14        #b2
        - GPIO13        #b3
        - GPIO12        #b4
        - GPIO11        #b5
```
