### ISSUE TITLE
Failure to compile Google Fonts

### ISSUE THREAD

**Issue by fawick** [esphome/issues#6472]
### The problem

After updating to 2024.11.1 (from 2024.10.2), the font block prevents compilation. 

EDIT: While the message is 100% correct it could be more helpful if it would state that the error has been in the font all along. 

```
INFO ESPHome 2024.11.1
INFO Reading configuration /config/esphome/og1floorheater.yaml...
INFO Detected timezone 'Europe/Berlin'
Failed config

font: [source /config/esphome/og1floorheater.yaml:233]
  
  Font Roboto@400@False@v1.ttf is missing 1 glyph:
      → (b'\\u2192').
  - file: gfonts://Roboto
    id: roboto_small
    size: 24
    glyphs: 
      - !"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz€@
      - →
  - file: gfonts://Roboto
    id: roboto_large
    size: 56
    glyphs: 
      - !"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqr
  ```
  
  
  The YAML block in the configuration looks like this:
  
 ```yaml
 font:
  - file: 'gfonts://Roboto'
    id: roboto_small
    size: 24
    glyphs: [
      "!\"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz€@",
      "\u2192", # →
      ]
  - file: "gfonts://Roboto"
    id: roboto_large
    size: 56
    glyphs: [
      "!\"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz€@",
      "\u2192", # →
      ]
```

### Which version of ESPHome has the issue?

2024.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32

### Board

m5stack-coreink

### Component causing the issue

font

### Example YAML snippet

```yaml
- file: 'gfonts://Roboto'
    id: roboto_small
    size: 24
    glyphs: [
      "!\"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz€@",
      "\u2192", # →
      ]
  - file: "gfonts://Roboto"
    id: roboto_large
    size: 56
    glyphs: [
      "!\"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz€@",
      "\u2192", # →
      ]
```

### Anything in the logs that might be useful for us?

```txt
Compilation log:

INFO ESPHome 2024.11.1
INFO Reading configuration /config/esphome/og1floorheater.yaml...
INFO Detected timezone 'Europe/Berlin'
Failed config

font: [source /config/esphome/og1floorheater.yaml:233]
  
  Font Roboto@400@False@v1.ttf is missing 1 glyph:
      → (b'\\u2192').
  - file: gfonts://Roboto
    id: roboto_small
    size: 24
    glyphs: 
      - !"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz€@
      - →
  - file: gfonts://Roboto
    id: roboto_large
    size: 56
    glyphs: 
      - !"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqr
```

### Additional information

EDIT: It would be great if ESPHome would be more explicit that this is new behaviour and indicated a problem in the font not in the code:

```
ESPHome versions since 2024.11.0 introduced testing for missing glyphs in the compilation phase. The missing glyph is most likely a problem of the font itself. Check the documentation."

```
