### ISSUE TITLE
lvgl style does not perceive the setting bg_grad: xxxx

### ISSUE THREAD

**Issue by LGhost1973** [esphome/issues#6474]
### The problem

```
lvgl:
   gradients:
     - id: grad_bkgrd
       direction: ver
       dither: ordered
       stops:
         - color: 0xFF0000
           position: 0
         - color: 0xFFFFFF
           position: 42
         - color: 0xFFFFFF
           position: 212            
         - color: 0xFF0000
           position: 255
   style_definitions:
     - id: style_main
       bg_color: 0x999999
       outline_width: 6
       outline_color: 0x000000
       radius: 10
       bg_grad: grad_bkgrd 
```

### Which version of ESPHome has the issue?

last

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

last

### What platform are you using?

ESP32
