### ISSUE TITLE
Unable to load binary to ESP32 board

### ISSUE THREAD

**Issue by kryptonitecb3** [esphome/issues#6478]
### The problem

I'm trying to switch my arduino based esp32 device to the esp-idf framework. According to the docs this has to be done by serial. However when I physcially connect my device, the development board recommended at the bottom of the "https://esphome.io/projects/?type=bluetooth" page, will not allow me to load the firmware. I've swapped usb cables, tried different boards, used usb and a usb to serial adapter.

When I try a flashing using chrome I get a "Failed to initialize" error, for both direct using usb and usb to serial.

When I try using esphome-flasher I get a "Unexpected error: The firmware binary is invalid (magic byte=FF, should be E9)

I have tried holding down the "BOOT" button, the "EN", both at the same time. Each time I get the same error. (I started using clothes pins to make sure they were pressed and to free up my hands while trying to get the flashing process to work)

I'm using the current version of esphome-flasher, ESPHome-Flasher-1.4.0-Ubuntu-x64.exec, on Ubuntu 24.04.1 LTS.
 

using chrome:
![Screenshot from 2024-11-22 09-01-55](https://github.com/user-attachments/assets/f04a2a2b-9d3b-4446-9a91-ed97c92e1a17)

using direct usb connection with esphome-flasher:
![Screenshot from 2024-11-22 09-04-40](https://github.com/user-attachments/assets/f71157eb-6938-49af-9eea-2bbdffaea096)

using usb to serial with esphome-flasher:
![Screenshot from 2024-11-22 09-06-00](https://github.com/user-attachments/assets/2d77a44f-79d0-41ce-8651-d4069b92ad42)

esphome-flasher is able to read serial output from an unaltered device, which failed using esphome-flasher:
![Screenshot from 2024-11-22 09-06-45](https://github.com/user-attachments/assets/14d8fbb2-f12e-4d6f-8db2-cb098c82929d)

trying to flash to these devices, from the link at the bottom of the "https://esphome.io/projects/?type=bluetooth" page
![Screenshot from 2024-11-22 09-22-15](https://github.com/user-attachments/assets/078eef28-796e-45fe-a954-733416f7b481)

### Which version of ESPHome has the issue?

ESPHome 2024.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2024.11.2 Supervisor 2024.11.4 Operating System 13.2 Frontend 20241106.2

### What platform are you using?

ESP32-IDF

### Board

ESP-WROOM-32 ESP32 ESP-32S Development Board

### Component causing the issue

install

### Example YAML snippet

```yaml
esphome:
  name: test-node
  comment: "ESP32 dev board espif"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  networks:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

api:
  encryption:
    key: !secret key

ota:
  - platform: esphome

logger:

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

status_led:
  pin:
    number: GPIO2
#    inverted: True #true=always on
```
