### ISSUE TITLE
[web server] no status shown for sensors

### ISSUE THREAD

**Issue by froido** [esphome/issues#648]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32 Feather 

**Affected component:**
web server

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

Hi,

there is a problem with showing the states on the web server. There are no states shown in the web frontend, even though they are updating in the serial console. I tried this with a couple of sensors and binaries.

Config: Adafruit ESP32 Feather as standalone webserver

### YAML-File:
```
esphome:
  name: pump
  platform: ESP32
  board: featheresp32

web_server:
  port: 80

wifi:
  ap:
    ssid: "esp32-pump"
    password: "esp32-pump!"
  reboot_timeout: 0s
  
# Enable logging
logger:

sensor:
  - platform: esp32_hall
    name: "ESP32 Hall Sensor"
    update_interval: 2s
    id: bla

```

### Serial-Log:
![serial](https://user-images.githubusercontent.com/32556063/64100164-50a9a280-cd6b-11e9-99ed-d0df47728d22.PNG)

### Web-Frontend:
![frontend](https://user-images.githubusercontent.com/32556063/64100193-615a1880-cd6b-11e9-98ce-5ffc36fe9cab.jpg)
