### ISSUE TITLE
SX1509 - ESPHOME - Binary input - switches states when not grounded

### ISSUE THREAD

**Issue by TesaTesa** [esphome/issues#6480]
### The problem

Hello, 
maybe its not an issue, maybe Im missing something important.
Trying to configure the SX1509 expander to act as a independent binary inputs expander (need 8 of them acting as a binary switches). Im trying to do it without matrix - defining independent pins.
Im trying to make configuration avoiding matrix, Pin 1 to GND for example. When circuit is open, it goes on/off all the time. 

Tried : 
mode:
        input: true
        pullup: true/false
      inverted: true
filters : 

When grounded it stays off/or on - related to the configuration.

What is the issue here / what im I missing ?

### Which version of ESPHome has the issue?

2024.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.1

### What platform are you using?

ESP32

### Component causing the issue

i2C sx1509

### Example YAML snippet

```yaml
- platform: gpio
    name: "SX1509 Pin #0"
    pin:
      sx1509: sx1509_hub
      # Use pin number 1 on the SX1509
      number: 1
      mode: INPUT # doesnt matter if there is pullup or not, the behaviour is the same

      inverted: true
    filters:
      - delayed_on: 100ms
 
i2c:
  sda: GPIO8
  scl: GPIO9
  frequency: 300kHz

sensor:
  - platform: homeassistant
    name: "Temp"
    id: Temp
    entity_id: sensor.teplota_garaz_temperature

    
  - platform: am2320
    temperature:
      name: "Teplota"
      id: T
    humidity:
      name: "Vlhkost"
      id: H
    update_interval: 60s

  - platform: homeassistant
    entity_id: sensor.gw2000a_v2_1_3_outdoor_temperature
    name: "Teplota Venku"
    id: teplotaout

font:
  - file: "fonts/JetB.ttf"
    id: JetB
    size: 20
    extras:
    - file: "fonts/material.ttf"
      glyphs: ["\U000F07FA",  # BUCHANKA
               "\U000F050F",  # TEPLOTA
               "\U000F058E",  # VLHKOST
               "\U000F1897"]  # OUTSIDE

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(JetB), "\U000F07FA\U000F050F%.1f°C", id(T).state);
      it.printf(0, 20, id(JetB), "\U000F07FA\U000F058E%.1f%%", id(H).state);
      it.printf(0, 40, id(JetB), "\U000F1897\U000F050F%.1f°C", id(teplotaout).state);


sx1509:
  - id: sx1509_hub
    address: 0x3E
```

### Additional information

I didnt modify the sx1509. As it comes, I have used it - no jumpers, etc modified...
