### ISSUE TITLE
MY9231/MY9291 LED driver broken since ESPHome 2024.11.0

### ISSUE THREAD

**Issue by Styx85** [esphome/issues#6483]
### The problem

Since ESPHome version 2024.11.0 my two E14 LEDs are not working anymore. Same for 2024.11.1.
Interestingly, it compiles fine, there are no errors and the log also reports everything working but the LED itself is not responding.
So no on/off switching, colormode, and so on.
When I switch back to an older Version (for example 2024.9) it is working like a charm. It worked until 2024.10.
How can I add any useful logs? So far, there are no obvious errors.

### Which version of ESPHome has the issue?

2024.11.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

my9231

### Example YAML snippet

```yaml
substitutions:
  friendly_name: E14 LED 2

esphome:
  name: e14led02
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  use_address: xxx

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot E1402"
    password: !secret fallback_password 

web_server:
  port: 80
  
captive_portal:

# Enable logging to ESPHome
logger:
  # Disable logging to serial
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: 'xxx'

# Example configuration entry
ota:
  - platform: esphome
    password: !secret ota_password

safe_mode:

my9231:
 data_pin: GPIO13  
 clock_pin: GPIO15  
 num_channels: 6
 num_chips: 2 
 
output:
  - platform: my9231
    id: output_blue
    channel: 1
  - platform: my9231
    id: output_red
    channel: 3
  - platform: my9231
    id: output_green
    channel: 2
  - platform: my9231
    id: output_cold_white
    channel: 4


light:
  - platform: rgbw
    name: "E14 LED 2"
    default_transition_length: 0s
    red: output_red
    green: output_green
    blue: output_blue
    white: output_cold_white
```
