### ISSUE TITLE
Compilation Error regarding - lvgl.bar.update

### ISSUE THREAD

**Issue by al9bob** [esphome/issues#6485]
### The problem

Receiving an error when compiling script at every instance of the  lvgl.bar.update: function

### Which version of ESPHome has the issue?

2024.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.3

### What platform are you using?

ESP32

### Board

esp32-s3-devkitc-1

### Component causing the issue

LVGL

### Example YAML snippet

```yaml
Snippet of the function causing the error:
     - lvgl.bar.update:
          id: energybar_c
          value: !lambda return(id(energyReading_c));

Snippet of the default global value of the variable:
  - id: energyReading_c
    type: float
    initial_value: '0'

Snippet of the bar graph:
                - bar:
                    x: 5
                    y: 5
                    id: energybar_c
                    height: 300
                    width: 16
                    value: 750
                    min_value: 0
                    max_value: 9000
                    bg_opa: TRANSP
```

### Anything in the logs that might be useful for us?

```txt
/config/esphome/esphome-waveshare43-test.yaml: In lambda function:
/config/esphome/esphome-waveshare43-test.yaml:915:59: error: too few arguments to function 'void lv_bar_set_value(lv_obj_t*, int32_t, lv_anim_enable_t)'
     then:
                                                           ^
In file included from .piolibdeps/esphome-waveshare43-test/lvgl/lvgl.h:53,
                 from src/esphome/components/lvgl/lvgl_proxy.h:13,
                 from src/esphome/components/image/image.h:6,
                 from src/esphome.h:37,
                 from src/main.cpp:3:
.piolibdeps/esphome-waveshare43-test/lvgl/src/widgets/lv_bar.h:90:6: note: declared here
 void lv_bar_set_value(lv_obj_t * obj, int32_t value, lv_anim_enable_t anim);
      ^~~~~~~~~~~~~~~~
```

### Additional information

This code was functional back in mid October, I just had to correct a typo in a label and these errors are occurring. I attempted to recompile the original functional code with the same errors and issues.
