### ISSUE TITLE
ESP32 boards randomly crash when momentary button is pressed

### ISSUE THREAD

**Issue by dsolera** [esphome/issues#6486]
### The problem

I have a simple momentary push button connected to a GPIO of the board.
Randomly, but especially after boot, the board crashes and restarts when I press the button.

I verified this behavior in all of the following configurations:
- nodemcu-32s board
- wemos_d1_mini32 board
- different GPIOs
- different physical buttons
- internal pullup resistor enabled
- internal pullup resistor enabled, added external 68k pullup resistor
- added 100 pF capacitor in parallel to external 68k pullup

In all cases I'm using the arduino framework and neopixelbus library with a WS2818 led light. It is important to note that the board crashes randomly both when turning on or turning off the leds.

I have some more capacitors on order so I can provide further filtering/stabilization to the 5V supply, but I really doubt that is the issue.

### Which version of ESPHome has the issue?

2024.11.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32

### Board

wemos_d1_mini32 and nodemcu-32s

### Component causing the issue

gpio binary_sensor

### Example YAML snippet

```yaml
esphome:
  name: bedside-lamp

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG          

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.nnn
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedside-Lamp Fallback Hotspot"
    password: "xxxxxxx"

captive_portal:

globals:
  - id: sunset_started_at
    type: int
    initial_value: '0'
    restore_value: false
  - id: sunrise_started_at
    type: int
    initial_value: '0'
    restore_value: false

time:
  - platform: homeassistant
    id: ha_time
    timezone: Europe/Rome

light:
  - platform: neopixelbus
    variant: WS2812
    id: main_light
    name: "Bedside-Lamp Light"
    pin: GPIO27 
    num_leds: 28
    type: GRB
    method: esp32_i2s # Faster?
    internal: false
    restore_mode: ALWAYS_OFF
    default_transition_length: 500ms
    color_correct: [ 95%, 95%, 95% ] # De-facto limits the brightness
    on_turn_off: 
      then:
        - switch.turn_off: blue_led
    effects:
      - addressable_twinkle:
          name: "Twinkle"
          twinkle_probability: 10%
          progress_interval: 8ms
      - lambda:
          name: "Sunset"
          update_interval: 15s
          lambda: |-
            if(id(sunset_started_at) == 0 || initial_run) {
              id(sunset_started_at) = id(ha_time).now().timestamp;
            }

            float br = ((15.0 * 60.0) - (float)(id(ha_time).now().timestamp - id(sunset_started_at))) / (15.0 * 60.0);
            if(br >= 0.1) {
              auto call = id(main_light).make_call();
              if(initial_run) {
                call.set_rgb(1.0, 0.63, 0.0); // These are copied from button double_press
              }
              call.set_transition_length(0);
              call.set_brightness(br);
              call.perform();
            }
            else {
              auto call = id(main_light).turn_off();
              call.set_brightness(1.0); // Also restore full brightness
              call.set_transition_length(0);
              call.perform();
              id(sunset_started_at) = 0;
            }
      - lambda:
          name: "Sunrise"
          update_interval: 15s
          lambda: |-
            if(id(sunrise_started_at) == 0 || initial_run) {
              id(sunrise_started_at) = id(ha_time).now().timestamp;

              id(blue_led).turn_on();
            }

            float br = 0.1 + (float)(id(ha_time).now().timestamp - id(sunrise_started_at)) / (15.0 * 60.0);
            if(br < 0.98) {
              auto call = id(main_light).make_call();
              if(initial_run) {
                call.set_rgb(0.67, 0.26, 1.0); // 170, 66, 255
              }
              call.set_transition_length(0);
              call.set_brightness(br);
              call.perform();
            }
            else {
              id(blue_led).turn_off();

              auto call = id(main_light).make_call();
              call.set_brightness(1.0); // Also restore full brightness
              call.set_effect("Twinkle");
              call.perform();
              id(sunrise_started_at) = 0;
            }

switch:
  - platform: gpio
    id: blue_led
    internal: true
    pin: GPIO2

sensor:
  - platform: wifi_signal
    name: "Bedside-Lamp RSSI"
    update_interval: 60s
  - platform: uptime
    name: "Bedside-Lamp Uptime"
    update_interval: 60s
  - platform: internal_temperature
    name: "Bedside-Lamp Internal Temperature"

binary_sensor:
  - platform: status
    name: "Bedside-Lamp Status"
    
  - platform: gpio
    id: main_button
    internal: true
    pin: 
      number: GPIO25
      inverted: true
      mode:
        input: true
        pullup: false # 68k external pullup
    on_press:
      - light.toggle: main_light
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - light.turn_on:
            id: main_light
            # These are copied to Sunset effect lambda
            red: 1.0 # 255
            green: 0.63 # 161
            blue: 0.0
            brightness: 100%
            effect: "Sunset"

button:
  - platform: restart
    name: "Bedside-Lamp Restart"
```
