### ISSUE TITLE
Webserver V3 - `entity_category: diagnostic` overrides `sorting_group_id`

### ISSUE THREAD

**Issue by apbarratt** [esphome/issues#6488]
### The problem

I would like to have my diagnostic entities at the bottom of my web server page.

I have placed all my other entities into sorting groups and placed a restart button in `entity_category: diagnostic`.
It seems this `entity_category` naturally floats to the top of the page.

I attempted to override this by creating another sorting_group with the heaviest weight just for diagnostic, but it would appear `entity_category: diagnostic` is overriding the `sorting_group_id: diagnostic` and so placing the item at the top of the page.

Here are my sorting groups:
```
web_server:
  version: 3
  local: false
  sorting_groups:
    - id: switches
      name: "Switches"
      sorting_weight: 10
    - id: thermostats
      name: "Thermostats"
      sorting_weight: 20
    - id: schedule
      name: "Schedule"
      sorting_weight: 30
    - id: sensors
      name: "Sensors"
      sorting_weight: 40
    - id: diagnostic
      name: "Diagnostic"
      sorting_weight: 50
```

and here is the button in question:
```
button:      
  - platform: restart
    name: Restart
    entity_category: diagnostic
    web_server:
      sorting_group_id: diagnostic
```
I'd also note it is the only item I have specifically defined an entity_category for.

I note that the documentation for the web server component states:
> If you don’t provide a web_server_sorting_group on the component, the entity_category will be used as the group.
https://esphome.io/components/web_server.html#entity-grouping

<img width="1360" alt="Screenshot 2024-11-25 at 20 55 01" src="https://github.com/user-attachments/assets/77ee16d2-8071-4bdb-834f-408245a09f37">

### Which version of ESPHome has the issue?

2024.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.3

### What platform are you using?

ESP32

### Board

ESP32 Relay X4 32E

### Component causing the issue

web_server

### Example YAML snippet

```yaml
substitutions:
  device_name: vivarium
  friendly_name: Vivarium

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  on_boot:
    priority: -100.0
    then:
      - script.execute: checkTime

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: INFO

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  - platform: http_request

http_request:
  verify_ssl: false

mqtt:
  broker: !secret hivemq_bridge
  port: 8883
  username: vivarium
  password: !secret vivarium_mqtt_password
  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
    WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
    ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
    h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
    0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
    A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
    T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
    B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
    B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
    KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
    OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
    jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
    qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
    rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
    HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
    hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
    ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
    3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
    NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
    ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
    TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
    jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
    oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
    4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
    mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
    emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
    -----END CERTIFICATE-----

improv_serial:

wifi:
  # reboot_timeout: 0s
  networks:
  - ssid: !secret skua_wifi_ssid
    password: !secret skua_wifi_password
  - ssid: !secret hillend_house_wifi_ssid
    password: !secret hillend_house_wifi_password
  - ssid: !secret hillend_garage_wifi_ssid
    password: !secret hillend_garage_wifi_password
  - ssid: !secret hedgehog_wifi_ssid
    password: !secret hedgehog_wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vivarium"
    password: "this is the password"

captive_portal:

web_server:
  version: 3
  local: false
  sorting_groups:
    - id: switches
      name: "Switches"
      sorting_weight: 10
    - id: thermostats
      name: "Thermostats"
      sorting_weight: 20
    - id: schedule
      name: "Schedule"
      sorting_weight: 30
    - id: sensors
      name: "Sensors"
      sorting_weight: 40
    - id: diagnostic
      name: "Diagnostic"
      sorting_weight: 50

i2c:

one_wire:
  - platform: gpio
    pin: GPIO23

sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: "Room Temperature"
      icon: mdi:home-thermometer-outline
      web_server:
        sorting_group_id: sensors
        sorting_weight: 30
    humidity:
      name: "Room Humidity"
      icon: mdi:water-percent
      web_server:
        sorting_group_id: sensors
        sorting_weight: 40
  - platform: dallas_temp
    id: coolEndSensor
    name: Cool End
    icon: mdi:thermometer-low
    address: 0x393cb8e3813b0a28
    web_server:
      sorting_group_id: sensors
      sorting_weight: 20
  - platform: dallas_temp
    id: hotEndSensor
    name: Hot End
    icon: mdi:thermometer-high
    address: 0x9c3cfee381aec828
    web_server:
      sorting_group_id: sensors
      sorting_weight: 10

output:
  - platform: gpio
    pin: GPIO32
    id: relay_pin_1
  - platform: gpio
    pin: GPIO33
    id: relay_pin_2
  - platform: gpio
    pin: GPIO25
    id: relay_pin_3
  - platform: gpio
    pin: GPIO26
    id: relay_pin_4

switch:
  - platform: output
    id: relay_hot_end
    output: relay_pin_1
  - platform: output
    id: relay_cool_end
    output: relay_pin_2
  - platform: output
    name: "Light"
    icon: mdi:lightbulb-fluorescent-tube-outline
    id: relay_light
    output: relay_pin_3
    web_server:
      sorting_group_id: switches
      sorting_weight: 10
  - platform: output
    id: relay_4
    name: "Spare Socket"
    icon: mdi:power-socket-uk
    output: relay_pin_4
    web_server:
      sorting_group_id: switches
      sorting_weight: 20

climate:
  - platform: thermostat
    name: "Hot End"
    icon: mdi:lightbulb-on-outline
    id: hotEndThermostat
    sensor: hotEndSensor
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    visual:
      min_temperature: 0
      max_temperature: 35
      temperature_step: 1

    heat_action:
      - switch.turn_on: relay_hot_end
    idle_action:
      - switch.turn_off: relay_hot_end
    default_preset: Day
    on_boot_restore_from: DEFAULT_PRESET
    preset:
      - name: Day
        default_target_temperature_low: 30 °C
        mode: "OFF"
    web_server:
      sorting_group_id: thermostats
      sorting_weight: 10
  - platform: thermostat
    name: "Cool End"
    icon: mdi:lightbulb-night-outline
    id: coolEndThermostat
    sensor: coolEndSensor
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    visual:
      min_temperature: 0
      max_temperature: 35
      temperature_step: 1
    heat_action:
      - switch.turn_on: relay_cool_end
    idle_action:
      - switch.turn_off: relay_cool_end
    default_preset: Night
    on_boot_restore_from: DEFAULT_PRESET
    preset:
      - name: Night
        default_target_temperature_low: 16 °C
        mode: "HEAT"
    web_server:
      sorting_group_id: thermostats
      sorting_weight: 20

datetime:
  - platform: template
    id: daytime
    name: Daytime
    icon: mdi:weather-sunset-up
    type: time
    optimistic: True
    initial_value: "08:00"
    restore_value: true
    on_time:
      then:
        - climate.control:
            id: hotEndThermostat
            mode: "HEAT"
        - switch.turn_on: relay_light
    on_value:
      then:
        - script.execute: checkTime
    web_server:
      sorting_group_id: schedule
      sorting_weight: 10

  - platform: template
    id: nighttime
    name: Nighttime
    icon: mdi:weather-sunset-down
    type: time
    optimistic: True
    initial_value: "20:00"
    restore_value: true
    on_time:
      then:
        - climate.control:
            id: hotEndThermostat
            mode: "OFF"
        - switch.turn_off: relay_light
    on_value:
      then:
        - script.execute: checkTime
    web_server:
      sorting_group_id: schedule
      sorting_weight: 20

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.uk.pool.ntp.org
      - 1.uk.pool.ntp.org
      - 2.uk.pool.ntp.org

button:      
  - platform: restart
    name: Restart
    entity_category: diagnostic
    web_server:
      sorting_group_id: diagnostic

script:
  - id: checkTime
    mode: queued
    then:
      - if:
          condition:
            - lambda: |-
                auto now = id(sntp_time).now();
                int timeNow = now.hour * 100 + now.minute;
                int timeDay = id(daytime).hour * 100 + id(daytime).minute;
                int timeNight = id(nighttime).hour * 100 + id(nighttime).minute;
                bool isDaytime = timeNow > timeDay && timeNow < timeNight;
                ESP_LOGI("custom", isDaytime ? "Daytime" : "Nighttime");
                return isDaytime;
          then:
            - climate.control:
                id: hotEndThermostat
                mode: "HEAT"
            - switch.turn_on: relay_light
          else:
            - climate.control:
                id: hotEndThermostat
                mode: "OFF"
            - switch.turn_off: relay_light
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
