### ISSUE TITLE
[`micro_wake_word`] on ESP32-S3-DevKitC-1: `Could not allocate the streaming model's tensor arena.`

### ISSUE THREAD

**Issue by muhlba91** [esphome/issues#6489]
### The problem

When enabling `micro_wake_word`, it works successfully once, but the second/third/... time microWakeWord wants to activate, I receive:
```
[17:02:04][E][micro_wake_word:032]: Could not allocate the streaming model's tensor arena.
[17:02:04][E][micro_wake_word:268]: Failed to initialize a wake word model.
[17:02:04][E][micro_wake_word:161]: Failed to load the wake word model(s) or allocate buffers
[17:02:04][E][component:164]: Component micro_wake_word set Error flag: unspecified
```

### Which version of ESPHome has the issue?

2024.11.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.11.3

### What platform are you using?

ESP32-IDF

### Board

ESP32-S3-DevKitC-1

### Component causing the issue

micro_wake_word

### Example YAML snippet

```yaml
---
substitutions:
  # Device information
  # Requirements for the device name: https://esphome.io/components/esphome.html
  deviceid:esp32-s3-devboard
  devicename: "ESP32-S3-DevBoard"

  # Password and Encryption Key for Home Assistant API, OTA Updates, and Web UI
  password: password
  api_encryption_key: 3ag4ZEn9Xk0TIJ5e18e3nj107SRz73D32ThOJKSlpLs=

  # Wifi connection data
  ssid: Tuxnet
  wifi_password: password

esphome:
  name: ${deviceid}

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"
      # CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      # Settings based on https://github.com/espressif/esp-adf/issues/297#issuecomment-783811702
      CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "16"
      CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "512"
      CONFIG_ESP32_WIFI_STATIC_TX_BUFFER: "y"
      CONFIG_ESP32_WIFI_TX_BUFFER_TYPE: "0"
      CONFIG_ESP32_WIFI_STATIC_TX_BUFFER_NUM: "8"
      CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM: "32"
      CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED: "y"
      CONFIG_ESP32_WIFI_TX_BA_WIN: "16"
      CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED: "y"
      CONFIG_ESP32_WIFI_RX_BA_WIN: "32"
      CONFIG_LWIP_MAX_ACTIVE_TCP: "16"
      CONFIG_LWIP_MAX_LISTENING_TCP: "16"
      CONFIG_TCP_MAXRTX: "12"
      CONFIG_TCP_SYNMAXRTX: "6"
      CONFIG_TCP_MSS: "1436"
      CONFIG_TCP_MSL: "60000"
      CONFIG_TCP_SND_BUF_DEFAULT: "65535"
      CONFIG_TCP_WND_DEFAULT: "65535"  # Adjusted from linked settings to avoid compilation error
      CONFIG_TCP_RECVMBOX_SIZE: "512"
      CONFIG_TCP_QUEUE_OOSEQ: "y"
      CONFIG_TCP_OVERSIZE_MSS: "y"
      CONFIG_LWIP_WND_SCALE: "y"
      CONFIG_TCP_RCV_SCALE: "3"
      CONFIG_LWIP_TCPIP_RECVMBOX_SIZE: "512"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

i2s_audio:
  - id: i2s_out
    # i2s_output data pin is GPIO8
    i2s_lrclk_pin:
      number: GPIO4
    i2s_bclk_pin:
      number: GPIO5
  - id: i2s_in
    # data line is GPIO18
    i2s_lrclk_pin:
      number: GPIO16
    i2s_bclk_pin:
      number: GPIO17

wifi:
  ssid: ${ssid}
  password: ${wifi_password}
  # power_save_mode: none
  on_connect:
    - delay: 5s

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${deviceid}
    password: ${wifi_password}
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0
      dns1: 1.1.1.1
      dns2: 1.0.0.1

captive_portal:

logger:
  level: DEBUG

api:
  encryption:
    key: ${api_encryption_key}

safe_mode:
  disabled: true
  num_attempts: 10

ota:
  - platform: esphome

web_server:
  port: 80
  auth:
    username: admin
    password: ${password}

time:
  - platform: sntp
    id: sntp_time

microphone:
  - platform: i2s_audio
    id: i2s_microphone
    i2s_din_pin: GPIO18
    adc_type: external
    pdm: false
    sample_rate: 16000
    bits_per_sample: 32bit
    i2s_audio_id: i2s_in
    channel: left

speaker:
  - platform: i2s_audio
    id: i2s_speaker
    sample_rate: 16000
    i2s_dout_pin: GPIO8
    bits_per_sample: 32bit
    i2s_audio_id: i2s_out
    dac_type: external
    channel: mono

voice_assistant:
  id: va
  microphone: i2s_microphone
  speaker: i2s_speaker
  noise_suppression_level: 4
  auto_gain: 31dBFS
  volume_multiplier: 4.0
  use_wake_word: false
  on_client_disconnected:
    - voice_assistant.stop:
  on_listening:
    - light.turn_on:
        id: esp32s3_rgb_led
        blue: 100%
        red: 0%
        green: 0%
        brightness: 75%
        transition_length: 50ms
  on_stt_vad_end:
    - light.turn_on:
        id: esp32s3_rgb_led
        blue: 100%
        red: 100%
        green: 100%
        brightness: 75%
        transition_length: 50ms
  on_tts_start:
    - light.turn_on:
        id: esp32s3_rgb_led
        blue: 0%
        red: 0%
        green: 100%
        brightness: 75%
        transition_length: 50ms
  on_end:
    - delay: 5s
    - wait_until:
        not:
          voice_assistant.is_running:
    - light.turn_off:
        id: esp32s3_rgb_led
        transition_length: 50ms
    - micro_wake_word.start:
  on_error:
    - light.turn_on:
        id: esp32s3_rgb_led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 75%
        transition_length: 50ms
    - delay: 5s
    - light.turn_off:
        id: esp32s3_rgb_led
        transition_length: 50ms
    - micro_wake_word.start:

micro_wake_word:
  on_wake_word_detected:
    - light.turn_on:
        id: esp32s3_rgb_led           
        red: 30%
        green: 30%
        blue: 70%
        brightness: 60%
        transition_length: 50ms
    - delay: 2s
    - voice_assistant.start:
        wake_word: !lambda return wake_word;
  models:
    - model: https://github.com/esphome/micro-wake-word-models/raw/main/models/v2/okay_nabu.json
  vad:
    model: https://github.com/esphome/micro-wake-word-models/raw/main/models/v2/vad.json

binary_sensor:
  - platform: status
    name: API Connection
    id: api_connection
    filters:
      - delayed_on: 1s

switch:
  - platform: template
    name: "Assistant Switch"
    id: use_no_wake_word
    optimistic: true
    entity_category: config
    on_turn_on:
      - micro_wake_word.start:
    on_turn_off:
      - micro_wake_word.stop:
light:
  - platform: esp32_rmt_led_strip
    id: esp32s3_rgb_led
    name: "ESP32-S3 RGB LED"
    chipset: ws2812
    pin: GPIO48
    num_leds: 1
    restore_mode: ALWAYS_OFF
    rmt_channel: 0
    rgb_order: GRB
```
```


### Anything in the logs that might be useful for us?

```txt
[17:01:39][D][ring_buffer:034]: Created ring buffer with size 2048
[17:01:39][D][micro_wake_word:399]: Resetting buffers and probabilities
[17:01:39][D][micro_wake_word:194]: State changed from IDLE to START_MICROPHONE
[17:01:39][D][micro_wake_word:107]: Starting Microphone
[17:01:39][D][micro_wake_word:194]: State changed from START_MICROPHONE to STARTING_MICROPHONE
[17:01:39][D][micro_wake_word:194]: State changed from STARTING_MICROPHONE to DETECTING_WAKE_WORD
[17:01:42][D][micro_wake_word:160]: The 'Okay Nabu' model sliding average probability is 0.976 and most recent probability is 0.996
[17:01:42][D][micro_wake_word:123]: Wake Word 'Okay Nabu' Detected
[17:01:42][D][micro_wake_word:194]: State changed from DETECTING_WAKE_WORD to STOP_MICROPHONE
[17:01:42][D][micro_wake_word:129]: Stopping Microphone
[17:01:42][D][micro_wake_word:194]: State changed from STOP_MICROPHONE to STOPPING_MICROPHONE
[17:01:42][D][micro_wake_word:194]: State changed from STOPPING_MICROPHONE to IDLE

...

[17:02:01][D][i2s_audio.speaker:120]: Stopping Speaker
[17:02:01][D][i2s_audio.speaker:126]: Stopped Speaker
[17:02:01][D][voice_assistant:413]: Speaker has finished outputting all audio
[17:02:01][D][voice_assistant:511]: State changed from RESPONSE_FINISHED to IDLE
[17:02:01][D][voice_assistant:518]: Desired state set to IDLE
[17:02:04][E][micro_wake_word:032]: Could not allocate the streaming model's tensor arena.
[17:02:04][E][micro_wake_word:268]: Failed to initialize a wake word model.
[17:02:04][E][micro_wake_word:161]: Failed to load the wake word model(s) or allocate buffers
[17:02:04][E][component:164]: Component micro_wake_word set Error flag: unspecified
```
```


### Additional information

The voice assistant runs on an ESP32-S3-DevKitC-1 board with an INMP441 mic. The pipeline works when no wake word detection is used, and the voice assistant performs actions.

Interestingly, microWakeWord functions exactly once. After the response is done, and it wants to activate again, it fails. It also fails if I toggle the switch multiple times - there is no way to recover other than restarting the device.
