### ISSUE TITLE
ESPHome Opentherm does not work on GPIO14 and GPIO15 with ESP32

### ISSUE THREAD

**Issue by calebns** [esphome/issues#6491]
### The problem

No Opentherm communication if GPIO14 or GPIO15 is used.

**Test setup:**
Just a basic opetherm configuration
```
opentherm:
  in_pin: GPIO04
  out_pin: GPIO15

  dhw_enable: true
 ```
 Oscilloscope attached to GPIO15
 
 **Expected**:
 Waveforms indicating periodic Opentherm communication
 
 **Result**:
 No communication visible
 
 **Suspected root cause:**
 `opentherm.cpp` does configure pin mode and direction, but does not reset the GPIO first. That means, the code does not touch GPIO mapping matrix and relies on the default values set up by SDK. In this case, GPIO14&15 are special and after boot are not mapped as GPIOs.

### Which version of ESPHome has the issue?

2024.11

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11

### What platform are you using?

ESP32

### Board

WT32-ETH01

### Component causing the issue

opetherm

### Anything in the logs that might be useful for us?

```txt
It seems that opentherm.cpp does not configure pins to be GPIOs but instead relies on defaults.

bool OpenTherm::initialize() {
#ifdef ESP8266
  OpenTherm::instance = this;
#endif
  this->in_pin_->pin_mode(gpio::FLAG_INPUT);
  this->out_pin_->pin_mode(gpio::FLAG_OUTPUT);
  this->out_pin_->digital_write(true);
```

Tests done, both help:
1. I load yaml configuration which made the GPIO14 to be GPIO switch. After powering up the board everything was working as expected - GPIO14 behaves like a regular switch. If then I move GPIO14 to be opentherm out_pin and load the new firmware without powering off the board, the opentherm communication is OK and stays that way until power is removed. After cold reboot, communication is lost.

2. Adding a simple virtual switch with lambda function to yaml and turning it on just after board boots makes the opentherm work on GPIO14 & GPIO15
```
switch:
  - platform: template
    name: "s2"
    turn_on_action:
      - lambda: 'gpio_reset_pin(GPIO_NUM_15); gpio_set_direction(GPIO_NUM_15, GPIO_MODE_OUTPUT);'

opentherm:
  in_pin: GPIO04
  out_pin: GPIO15

  dhw_enable: true
```
```


### Additional information

_No response_
