### ISSUE TITLE
Servos jerk on detach (ESP32-IDF LEDC)

### ISSUE THREAD

**Issue by VV-Cephai** [esphome/issues#6492]
### The problem

On detaching a servo it sometimes jerks to a different position right after detaching. I am using LEDC on ESP32 (ESP IDF) as output component and have inverted set to True (due to an inverting level shifter). 
It seems that the detach action cuts off the PWM output imideately when it is triggered, cutting possibly ongoing control pulses short. 
So, if the auto detach triggers while the servo control pulse is being played, the last truncated pulse might be interpreted as a new position the servo tries to reach then.
To me, the problem seems to lie in the calls to ledc_stop() in ledc_output.cpp lines 129 and 131.
(https://github.com/esphome/esphome/blob/cf835d15806481c50361cd6d8d193cc7b0b0175e/esphome/components/ledc/ledc_output.cpp#L129)
From the code, I believe that inverting the channel makes no difference.
The Arduino framework does not seem to have this problem (but I have not fully tested it yet), as it does not seem to treat the 0 and max duty cycles differently. (It increments max_duty by 1, but then just calls ledc_set_duty() and ledc_update_duty()).
(https://github.com/espressif/arduino-esp32/blob/3dd4b0d112c16311c39efc10e8eda9f63e513775/cores/esp32/esp32-hal-ledc.c#L181)

Does the way the Arduino framework handles this have any disadvantages (e.g. no true 100% and or 0% duty cycles)? If not this might be a better way to go.

### Which version of ESPHome has the issue?

2024.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.3

### What platform are you using?

ESP32-IDF

### Board

esp32dev

### Component causing the issue

LEDC

### Example YAML snippet

```yaml
esphome:
  name: "servo-test"
  friendly_name: "servo_test"
  on_boot:
    priority: 600
    then:
      - valve.template.publish:
          id: vent_iris
          state: CLOSED

esp32:
  board: esp32dev
  framework:
    type: esp-idf

api:

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: ledc
    pin: GPIO33
    id: servo_pwm
    frequency: 100Hz
    inverted: True
    channel: 4

servo:
  - id: servo_1
    output: servo_pwm
    min_level: 7.5%
    max_level: 24.0%
    idle_level: 24.0%
    restore: True
    auto_detach_time: 500ms
    transition_length: 4s

valve:
  - platform: template
    name: "vent_iris"
    id: "vent_iris"
    has_position: True
    optimistic: True
    open_action:
      - servo.write:
          id: servo_1
          level: -1.0
    close_action:
      - servo.write:
          id: servo_1
          level: 0.0
    position_action:
      - servo.write:
          id: servo_1
          level: !lambda 'return -pos;'
```
