### ISSUE TITLE
watchdog non functional during stuck http request on rp2040

### ISSUE THREAD

**Issue by afflux** [esphome/issues#6493]
### The problem

I recently had a lockup after one or two weeks of uptime on my rp2040 based project. I'd normally expect it to reboot after 8.3s [due to the watchdog](https://github.com/esphome/esphome/blob/a3ef2ed7fd109fc6885de3dee7245d637d5ae2a9/esphome/components/rp2040/core.cpp#L22), but it didn't happen, stayed locked for roughly 10 minutes, when I noticed the problem and did a manual reset (can't really attach a debugger at the install location)

Last log message received is shown below, indicating a http_request. At precisely this time, state updates stop arriving on my home assistant instance.

Since the watchdog never triggered, I assume it was fed somewhere, so I look at all usages of `feed_wdt()` in `.esphome/build/project/src/`, and I find four (outside of `Application::setup()` and `Application::loop()`):
1. [i2c bus recovery](https://github.com/esphome/esphome/blob/a3ef2ed7fd109fc6885de3dee7245d637d5ae2a9/esphome/components/i2c/i2c_bus_arduino.cpp#L272) (only called during `setup()`)
2. various places in [`ESPHomeOTAComponent::handle_()`](https://github.com/esphome/esphome/blob/a3ef2ed7fd109fc6885de3dee7245d637d5ae2a9/esphome/components/esphome/ota/ota_esphome.cpp#L87)
3. display_buffer (yes, used a lot, but not in contexts that could loop forever)
4. [http_request action](https://github.com/esphome/esphome/blob/a3ef2ed7fd109fc6885de3dee7245d637d5ae2a9/esphome/components/http_request/http_request.h#L206-L208) and the [corresponding container implementation](https://github.com/esphome/esphome/blob/a3ef2ed7fd109fc6885de3dee7245d637d5ae2a9/esphome/components/http_request/http_request_arduino.cpp#L150)

Just from looking at the code, the http_request handling seems inconsistent:
1. [this `feed_wdt()`](https://github.com/esphome/esphome/blob/a3ef2ed7fd109fc6885de3dee7245d637d5ae2a9/esphome/components/http_request/http_request.h#L207) is unconditional, and the loop does not care if `container->read` returned 0 or even less than zero. If `container->read()` ends up returning -1, you'll get an endless loop. There is a second call to `feed_wdt()` in the `container->read()` implementation, but it will also not care if the http client returned 0 bytes, still causing an endless loop if the network had a hiccup.
2. Both the container and the action are tracking how many bytes were read, and the action is using both (`container->get_bytes_read()` and `read_index`). Due to 1., it can diverge - shouldn't this be unified?
3. Unlike [documented](https://github.com/esphome/esphome-docs/blob/5d624ed617a1e6a72052b884be12572d31c9e524/components/http_request.rst?plain=1#L25), the timeout set on the http_request actually sets the TCP connection timeout, and there is no timeout handling for the total http request (source for [rp2040](https://github.com/earlephilhower/arduino-pico/blob/e16c459598b86ce67d8b83ac5b1384dcb8c982ae/libraries/HTTPClient/src/HTTPClient.cpp#L448-L451) and [esp8266](https://github.com/esp8266/Arduino/blob/bb79e9076e8402c81c24efbabd19f1baab1c6bd1/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp#L305-L308))
4. [The call to `yield()` is not actually doing anything on rp2040](https://github.com/earlephilhower/arduino-pico/blob/e16c459598b86ce67d8b83ac5b1384dcb8c982ae/cores/rp2040/delay.cpp#L49), presumably because FreeRTOS is not linked in

Pretty sure that the combination of points 1, 3 and 4 caused lockup.

I'm happy to open a pull request to clean the http_request handling code, but I'm not familiar at all with FreeRTOS and platform.io, so I'm not sure what needs to happen to get `yield()` working on `rp2040` - but maybe that should be a second issue.

### Which version of ESPHome has the issue?

e819185de18f2f1d4f9b3e2c96190d1cefe53422

### What type of installation are you using?

pip

### What platform are you using?

RP2040

### Board

Pico W

### Component causing the issue

http_request

### Example YAML snippet

```yaml
script:
  - id: update_foo
    mode: single
    then:
      - http_request.post:
          url: http://foo/bar
          capture_response: true
          max_response_buffer_size: 6kB
time:
  - platform: sntp
    id: sntp_time
    timezone: Etc/UTC
    servers:
      - 192.168.1.1

    on_time:
      - seconds: 0
        minutes: /15
        then:
          - script.execute: update_foo
```

### Anything in the logs that might be useful for us?

```txt
2024-11-24T17:15:00.042574+01:00 rpclock http_request.arduino <feff>[D][http_request.arduino:123]: Content-Length: 4736
[followed by silence]
```

**Comment by afflux** [comment]
Correction, setTimeout does in fact also control the read timeout, not only the connect timeout (for rp2040, source is [here](https://github.com/earlephilhower/ArduinoCore-API/blob/abeee393931108f17e5e2313a01f49337a6507ee/api/Stream.cpp#L33-L42))

**Comment by afflux** [comment]
I can reproduce the issue on this config:

```yaml
esphome:
  name: test-2040

rp2040:
  board: rpipicow

script:
  - id: update_foo
    mode: single
    then:
      - http_request.post:
          url: http://192.168.1.10:9999/foo
          capture_response: true
          max_response_buffer_size: 6kB
          on_response:
            then:
              - lambda: |-
                  ESP_LOGE("http_request.post", "got response");

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  on_connect:
    - delay: 5s
    - script.execute: update_foo

# Enable logging
logger:
  level: VERY_VERBOSE

time:
  - platform: sntp
    id: sntp_time
    timezone: Etc/UTC
    servers:
      - 192.168.1.1

    on_time:
      - seconds: 0
        minutes: /5
        then:
          - script.execute: update_foo
      - seconds: /2
        minutes: '*'
        then:
          - lambda: ESP_LOGI("alive", "alive");

http_request:
  verify_ssl: false
```


And this web server in slow_http.py:

```python
import asyncio
from aiohttp import web

routes = web.RouteTableDef()

@routes.post('/foo')
async def hello(request):
    response = web.StreamResponse()
    response.content_length = 4
    await response.prepare(request)
    await asyncio.sleep(120)
    await response.write(b"done")
    return response


def init(argv):
    app = web.Application()
    app.add_routes(routes)
    return app
```

Run with `python -m aiohttp.web -H '0.0.0.0' -P 9999 slow_http:init`


Serial log output:

```txt
[I][app:100]: ESPHome version 2024.12.0-dev compiled on Nov 30 2024, 13:14:04
[C][http_request:013]: HTTP Request:
[C][http_request:014]:   Timeout: 4500ms
[C][http_request:015]:   User-Agent: ESPHome/2024.12.0-dev (https://esphome.io)
[C][http_request:016]:   Follow redirects: YES
[C][http_request:017]:   Redirect limit: 3
[D][sntp:072]: Synchronized time: 2024-11-30 13:14:31
[I][alive:057]: alive
[HTTP-Client][begin] url: http://192.168.1.10:9999/foo
[HTTP-Client][begin] host: 192.168.1.10 port: 9999 url: /foo
[HTTP-Client][sendRequest] type: 'POST' redirCount: 0
[HTTP-Client] connected to 192.168.1.10:9999
[HTTP-Client] sending request header
-----
POST /foo HTTP/1.1
Host: 192.168.1.10:9999
User-Agent: ESPHome/2024.12.0-dev (https://esphome.io)
Accept-Encoding: identity;q=1,chunked;q=0.1,*;q=0
Connection: keep-alive
Content-Length: 0

-----
'HTTP-Client][handleHeaderResponse] RX: 'HTTP/1.1 200 OK
'HTTP-Client][handleHeaderResponse] RX: 'Content-Length: 4
'HTTP-Client][handleHeaderResponse] RX: 'Content-Type: application/octet-stream
'HTTP-Client][handleHeaderResponse] RX: 'Date: Sat, 30 Nov 2024 12:14:33 GMT
'HTTP-Client][handleHeaderResponse] RX: 'Server: Python/3.11 aiohttp/3.10.10
'HTTP-Client][handleHeaderResponse] RX: '
[HTTP-Client][handleHeaderResponse] code: 200
[HTTP-Client][handleHeaderResponse] size: 4
[D][http_request.arduino:125]: Content-Length: 4
[followed by silence]
```
