### ISSUE TITLE
i2c timeout does not work on ESP32-S3

### ISSUE THREAD

**Issue by giulianob** [esphome/issues#6504]
### The problem

The timeout value passed to `i2c_set_timeout` when using IDF framework is incorrect for the ESP32-S3 because of a change in how the timeout is calculated on the S3:
- https://www.esp32.com/viewtopic.php?t=32281#p114099
- https://github.com/espressif/esp-idf/issues/11397#issuecomment-1550967441

Currently ESPHome always calculates the timeout as `ms * 80` which is the same issue as in the thread above.

I found out after following the sht3x-d sample which says to use a timeout of 10ms but the sensor would still timeout. I removed the timeout and it worked fine after reading this: https://www.esp32.com/viewtopic.php?t=32762

### Which version of ESPHome has the issue?

2024.11.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.3

### What platform are you using?

ESP32-IDF

### Board

Lolin ESP32-S3 Mini

### Component causing the issue

api/i2c

### Example YAML snippet

```yaml
esphome:
  name: lolin-s3-mini-test
  friendly_name: lolin s3 mini test
  platformio_options:
    board_build.arduino.memory_type: qio_qspi
    board_build.flash_mode: dio
    board_upload.ram_size: 327680
    board_upload_maximum_size: 4193404
    board_upload_speed: 460800

esp32:
  flash_size: 4MB
  variant: esp32s3
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

sensor:
  - platform: sht3xd
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    address: 0x44
    update_interval: 60s

i2c:
  sda: 35
  scl: 36
  scan: True
  frequency: 100khz
  timeout: 10ms
```
