### ISSUE TITLE
ESPHome Climate_IR Fujitsu AC: Dry Mode

### ISSUE THREAD

**Issue by memphisraynz** [esphome/issues#6508]
### The problem

Dry mode for Fujitsu is not showing in Home Assistant even though it appears to be in [fujitsu_general.cpp] and in the Fujitsu General Namespace reference (https://esphome.io/api/namespaceesphome_1_1fujitsu__general)

### Which version of ESPHome has the issue?

2024.11.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.1

### What platform are you using?

ESP32

### Board

esp-wrover-kit

### Component causing the issue

climate_ir

### Example YAML snippet

```yaml
esphome:
  name: aircon-remote-ble
  platform: ESP32
  board: esp-wrover-kit
  
wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password  
  domain: .lan

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret esphome_api

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%
  
climate:
  - platform: fujitsu_general
    name: "Living Room AC"
```
