### ISSUE TITLE
pulse_meter causing restarts under timer group 1 watchdog

### ISSUE THREAD

**Issue by excitron** [esphome/issues#6512]
### The problem

When using pulse_meter, esp32 frequently restarts at irregular intervals. Reset reason is “Timer Group 1 Watchdog” or “Software Reset CPU”. Will attach more logs to show both of these.

Switching to pulse_counter and the issue goes away.

Screenshot of uptime sensor over 24h showing the irregular restarts. No such restarts occur after switching to pulse_counter.
![IMG_5224](https://github.com/user-attachments/assets/1906ea34-ebba-4afd-a4e3-f8cd318d4b82)

### Which version of ESPHome has the issue?

2024.11.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

Freenove esp32-wroom

### Component causing the issue

pulse_meter

### YAML Config

```yaml
- platform: pulse_meter
    pin: 
      number: GPIO14
      allow_other_uses: true
    name: 'Anemometer'
    id: sensor_pulse_meter
    unit_of_measurement: 'm/s'
    device_class: wind_speed
    state_class: measurement
    internal_filter: 10ms #max rpm 100 => ~50m/s or 129mph
    internal_filter_mode: PULSE #disregard rising-falling edge time
    timeout: 1 min #after x seconds, assume 0m/s
    filters:
      - multiply: 0.0167 #0.05/rotation. 1rps = 251mm/s. 1m/s = 3.98rps
    total:
      name: "Anemometer Total Pulses"
      state_class: total_increasing
```

### Anything in the logs that might be useful for us?

```txt
[D][debug:137]: Reset Reason: Software Reset CPU
```
