### ISSUE TITLE
Airthings Wave Plus temperature integer should be signed

### ISSUE THREAD

**Issue by ionrae** [esphome/issues#6513]
### The problem

It got cold, but the AirThings Wave Plus thinks it's on the surface of the sun.

Looks like the temperature in Celsius is a signed value, but the `WavePlusReadings` struct in `airthings_wave_plus.h` is casting it as an unsigned value, so it's rolling over at freezing.

![Screenshot 2024-12-02 at 6 28 55 PM](https://github.com/user-attachments/assets/80df6878-1e32-42f1-8d3a-d3ae822b2337)
32 F == 0 C
![Screenshot 2024-12-02 at 6 28 34 PM](https://github.com/user-attachments/assets/fefc953f-4332-4784-af6a-878d0b9bfd48)
1211.58 F == 655.32 C
Which I assume should be -0.03 C, or 31.95 F.

### Which version of ESPHome has the issue?

2024.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.3

### What platform are you using?

ESP32

### Board

Olimex ESP32-PoE

### Component causing the issue

airthings_wave_plus

### YAML Config

```yaml
ble_client:
  - mac_address: FC:A8:9B:__:__:__ # MAC/serial redacted
    id: airthingsShop

sensor:

    - platform: airthings_wave_plus
      name: Airthings Wave shop
      ble_client_id: airthingsShop
      update_interval: 310s
      battery_update_interval: 6h
      temperature:
        name: "AirThings shop temperature"
        filters:
          - skip_initial: 3
      radon:
        name: "AirThings shop radon"
        filters:
          - skip_initial: 3
      radon_long_term:
        name: "AirThings shop radon long-term"
        filters:
          - skip_initial: 3
      pressure:
        name: "AirThings shop pressure"
        filters:
          - skip_initial: 3
      humidity:
        name: "AirThings shop humidity"
        filters:
          - skip_initial: 3
      co2:
        name: "AirThings shop CO2"
        filters:
          - skip_initial: 3
      tvoc:
        name: "AirThings shop VOC"
        filters:
          - skip_initial: 3
      battery_voltage:
        name: "AirThings shop battery"
        filters:
          - skip_initial: 3
```
