### ISSUE TITLE
ESP32S3 with SPI display using LVGL runtime fails entirely

### ISSUE THREAD

**Issue by ESP32andmore** [esphome/issues#6515]
### The problem

On ESP32S3 Board with SPI display executable fails entirely:
[23:18:47]ESP-ROM:esp32s3-20210327
[23:18:47]Build:Mar 27 2021
[23:18:47]rst:0x15 (USB_UART_CHIP_RESET),boot:0x8 (SPI_FAST_FLASH_BOOT)
[23:18:47]Saved PC:0x40378c15
[23:18:47]SPIWP:0xee
[23:18:47]mode:DIO, clock div:1
[23:18:47]load:0x3fce3808,len:0x43c
[23:18:47]load:0x403c9700,len:0xbec
[23:18:47]load:0x403cc700,len:0x2a3c
[23:18:47]entry 0x403c98d8
[23:18:47]ESP-ROM:esp32s3-20210327
[23:18:47]Build:Mar 27 2021
[23:18:47]rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[23:18:47]Saved PC:0x420e5e2e
[23:18:47]SPIWP:0xee
[23:18:47]mode:DIO, clock div:1
[23:18:47]load:0x3fce3808,len:0x43c
[23:18:47]load:0x403c9700,len:0xbec
[23:18:47]load:0x403cc700,len:0x2a3c
[23:18:47]entry 0x403c98d8
[23:18:47]ESP-ROM:esp32s3-20210327
The YAML is a WORKING version using Clyde's external component slightly modified for the "merge" changes

### Which version of ESPHome has the issue?

2024.11.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.3

### What platform are you using?

ESP8266

### Board

GrowMore HUB

### Component causing the issue

LVGL

### YAML Config

```yaml
# Four automatically controlled fan outputs (P1-P4), each set by four target temperatures, maintained by four Dallas sensor's temperatures. MQTT disabled. Home Assistant API enabled. DHCP enabled.
# Other control configurations available with modification of Dallas platform LAMBDA function.
substitutions:
  devicename: growmore
  fdevicename: GrowMore
  tdevicename: ""

  ip: 192.168.0.204 # For static IP adressing

  lightbulb:      "\U000F0335"
  ceiling_light:  "\U000F0769"
  floor_lamp:     "\U000F08DD"
  string_lights:  "\U000F12BA"
  fan:            "\U000F0210"
  fan_off:        "\U000F081D"
  fan_auto:       "\U000F171D"
  chev_down:      "\U000F0140"

  ssid: !secret wifi_ssid
  password: !secret wifi_password

  alarm_temp: "40" # Threshold for alarm when implemented
  ptemp: "20"
  itemp: "0.1"
  minfanspeed: "2"

# Connect your Dallas sensors with logger: DEBUG enabled (factory flash default).
# Open the ESPHome webtool, connect to the ECB board, view the "Logs" window, hit "Reset",
# and search for Dallas scan addresses and replace the below addresses with your unique ones.
# Example Scan
#[18:16:42][D][dallas.sensor:084]:     0x8b3ca8f64935b228 4
#[18:16:42][D][dallas.sensor:084]:     0x783c0af6490d3628 2
#[18:16:42][D][dallas.sensor:084]:     0xc13c01f09642c928 1
#[18:16:42][D][dallas.sensor:084]:     0x043c6ef649772f28 3
  dallasaddress1: "0x7300000069fa4028"
  dallasaddress2: "0xf60000006a3b8c28"
  dallasaddress3: "0x080000006a5df928"
  dallasaddress4: "0x830000006a113d28"

esphome:
  name: ${devicename}
  friendly_name: ${fdevicename}

  on_boot:
    priority: -100
    then:
    - logger.log:
        format: "Growtest BOOT"
        #args: [ 'x' ]
        level: ERROR

    - lvgl.slider.update:
            id: fan1_target_slider
            value: !lambda return id(set_target_temp_1).state;
    - lvgl.slider.update:
          id: fan1_speed_slider
          value: !lambda return id(fan1_speed).speed;
    - lvgl.label.update:
            id: fan1_target_text
            text:
              format: "%3.0f"
              args: [ 'id(set_target_temp_1).state' ]
    - lvgl.label.update:
        id: fan1_speed_text
        text:
          format: "%3.0d"
          args: [ 'id(fan1_speed).speed' ]

    - lvgl.slider.update:
            id: fan2_target_slider
            value: !lambda return id(set_target_temp_2).state;
    - lvgl.slider.update:
          id: fan2_speed_slider
          value: !lambda return id(fan2_speed).speed;
    - lvgl.label.update:
            id: fan2_target_text
            text:
              format: "%3.0f"
              args: [ 'id(set_target_temp_2).state' ]
    - lvgl.label.update:
        id: fan2_speed_text
        text:
          format: "%3.0d"
          args: [ 'id(fan2_speed).speed' ]

    - lvgl.slider.update:
            id: fan3_target_slider
            value: !lambda return id(set_target_temp_3).state;
    - lvgl.slider.update:
          id: fan3_speed_slider
          value: !lambda return id(fan3_speed).speed;
    - lvgl.label.update:
            id: fan3_target_text
            text:
              format: "%3.0f"
              args: [ 'id(set_target_temp_3).state' ]
    - lvgl.label.update:
        id: fan3_speed_text
        text:
          format: "%3.0d"
          args: [ 'id(fan3_speed).speed' ]

    - lvgl.slider.update:
            id: fan3_target_slider
            value: !lambda return id(set_target_temp_4).state;
    - lvgl.slider.update:
          id: fan4_speed_slider
          value: !lambda return id(fan4_speed).speed;
    - lvgl.label.update:
            id: fan4_target_text
            text:
              format: "%3.0f"
              args: [ 'id(set_target_temp_4).state' ]
    - lvgl.label.update:
        id: fan4_speed_text
        text:
          format: "%3.0d"
          args: [ 'id(fan4_speed).speed' ]



    - delay: 2s
    - lvgl.widget.hide: boot_screen

        #- lambda: |-
          #id(cpu_speed) = ESP.getCpuFreqMHz();
          #id(active_page) = 0;
          #id(update_display) = 0;


esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: arduino
    #type: esp-idf
    #sdkconfig_options:
    #  CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
    #  CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
    #  CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
    #  CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
    #  CONFIG_SPIRAM_RODATA: y

psram:
  mode: quad
  speed: 80MHz

preferences:
  flash_write_interval: 10min
    
wifi:
  ssid: ${ssid}
  password: ${password}
  #fast_connect: true
  #example static IP settings
  #manual_ip:
    #static_ip: ${ip}
    #gateway: 192.168.0.1
    #subnet: 255.255.255.0
    #dns1: 192.168.0.1
    #dns2: 8.8.8.8
  on_connect:
    - lvgl.widget.show: lbl_wifistatus
  on_disconnect:
    - lvgl.widget.hide: lbl_wifistatus
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${fdevicename} Fallback Hotspot
    password: "esphome1"
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.2
      subnet: 255.255.255.0

    
captive_portal:

ota:
  - platform: esphome
    password: "esphome1"

#mqtt:
  #broker: 192.168.0.100   # use your own MQTT server address and credentials
  #username: "john"
  #password: "trek6666"
  #reboot_timeout: 0s

api:
  encryption:
    key: "itqzvhZMJj8wuTJX0GTOuL/ffESFROzUlmcO0u2+sfo="  #use your own HA generated Key
  reboot_timeout: 0s
  
web_server:
  port: 80
  #css_url:  https://esphome.io/_static/webserver-v3.min.css
  version: 3
  log: True

debug:
  update_interval: 5s

logger:
  level: Error

globals:
  - id: fan1_sum
    type: float
    restore_value: no
    initial_value: '0'
  - id: fan2_sum
    type: float
    restore_value: no
    initial_value: '0'
  - id: fan3_sum
    type: float
    restore_value: no
    initial_value: '0'
  - id: fan4_sum
    type: float
    restore_value: no
    initial_value: '0'
  - id: target1
    type: int
    restore_value: True
    initial_value: '26'
  - id: target2
    type: int
    restore_value: True
    initial_value: '26'
  - id: target3
    type: int
    restore_value: True
    initial_value: '26'
  - id: target4
    type: int
    restore_value: True
    initial_value: '26'
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: '0'
  - id: active_page
    type: int
    restore_value: no
    initial_value: '0'
  - id: update_display
    type: bool
    restore_value: no
    initial_value: '1'
  - id: ticker
    type: int
    restore_value: no
    initial_value: '0'
  - id: cent_fahr_var
    type: int
    restore_value: yes
    initial_value: '0'


#external_components:
# - source: github://clydebarrow/esphome@lvgl_original
#   refresh: 10min
#   components: [ lvgl ]

time:
  - platform: sntp
    id: sntp_time
    timezone: America/New_York
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    on_time:
      - hours: 2,3,4,5
        minutes: 5
        seconds: 0
        then:
          - switch.turn_on: switch_antiburn
      - hours: 2,3,4,5
        minutes: 35
        seconds: 0
        then:
          - switch.turn_off: switch_antiburn
#-------------------------------------------
# Select
#-------------------------------------------
select:
  - platform: template
    name: ${tdevicename} Display Page
    icon: mdi:monitor
    web_server:
      sorting_weight: 4
    entity_category: "Config"
    id: select_page
    optimistic: true
    options:
      - "temp_page"
      - "speed_page"
      - "fan1_page"
      - "fan2_page"
      - "fan3_page"
      - "fan4_page"
      - "status_page"
      - "settings_page"
    on_value:
      then:
        - if:
            condition:
              lambda: 'return id(select_page).state == "temp_page";'
            then:
              - lvgl.page.show:
                  id: temp_page
        - if:
            condition:
              lambda: 'return id(select_page).state == "speed_page";'
            then:
              - lvgl.page.show:
                  id: speed_page
        - if:
            condition:
              lambda: 'return id(select_page).state == "fan1_page";'
            then:
              - lvgl.page.show:
                  id: fan1_page
        - if:
            condition:
              lambda: 'return id(select_page).state == "fan2_page";'
            then:
              - lvgl.page.show:
                  id: fan2_page
        - if:
            condition:
              lambda: 'return id(select_page).state == "fan3_page";'
            then:
              - lvgl.page.show:
                  id: fan3_page
        - if:
            condition:
              lambda: 'return id(select_page).state == "fan4_page";'
            then:
              - lvgl.page.show:
                  id: fan4_page
        - if:
            condition:
              lambda: 'return id(select_page).state == "status_page";'
            then:
              - lvgl.page.show:
                  id: status_page
        - if:
            condition:
              lambda: 'return id(select_page).state == "settings_page";'
            then:
              - lvgl.page.show:
                  id: settings_page

button:
  - platform: template
    name: ${tdevicename} Page Next
    web_server:
      sorting_weight: 2
    entity_category: "Config"
    icon: mdi:skip-next
    id: button_page_next
    on_press:
      then:
        lvgl.page.next:

  - platform: template
    name: ${tdevicename} Page Back
    web_server:
      sorting_weight: 3
    entity_category: "Config"
    icon: mdi:skip-previous
    id: button_page_back
    on_press:
      then:
        lvgl.page.previous:



#-------------------------------------------
# Switches
#-------------------------------------------
switch:
  - platform: template
    name: Antiburn
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
            - lvgl.pause:  

  - platform: restart
    name: ${tdevicename} Restart

#  - platform: gpio
#    name: ${tdevicename} Relay 0
#    pin: GPIO16
#    id: relay_0
#    restore_mode: restore_default_off

  - platform: template
    id: auto_fan1
    name: ${tdevicename} Auto Mode 1
    web_server:
      sorting_weight: 1
    icon: mdi:tune
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true      
    turn_on_action:   
      then:
        - lvgl.widget.update:
            id: fan1_auto_button
            state:
              checked: true
        - lvgl.label.update:
            id: fan1_auto_text
            text: "AUTO"
        - lvgl.label.update:
            id: fan1_auto_icon
            text: ${fan_auto}

    turn_off_action:
      then:
        - fan.turn_off : fan1_speed
        - lambda: !lambda |-
              float fan_set_speed = 1.0;
              auto calloff = id(fan1_speed).turn_off();           
              calloff.set_speed(fan_set_speed);
              calloff.perform();
        - lvgl.widget.update:
            id: fan1_auto_button
            state:
              checked: false 
        - lvgl.label.update:
            id: fan1_auto_text
            text: "MAN"
        - lvgl.label.update:
            id: fan1_auto_icon
            text: ${fan_off}     

  - platform: template
    id: auto_fan2
    name: ${tdevicename} Auto Mode 2
    web_server:
      sorting_weight: 2
    icon: mdi:tune
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    turn_on_action:   
      then:
        - lvgl.widget.update:
            id: fan2_auto_button
            state:
              checked: true
        - lvgl.label.update:
            id: fan2_auto_text
            text: "AUTO"
        - lvgl.label.update:
            id: fan2_auto_icon
            text: ${fan_auto}    
    turn_off_action:
      then:
        - fan.turn_off : fan2_speed
        - lambda: !lambda |-
              float fan_set_speed = 1.0;
              auto calloff = id(fan2_speed).turn_off();           
              calloff.set_speed(fan_set_speed);
              calloff.perform();
        - lvgl.widget.update:
            id: fan2_auto_button
            state:
              checked: false 
        - lvgl.label.update:
            id: fan2_auto_text
            text: "MAN"
        - lvgl.label.update:
            id: fan2_auto_icon
            text: ${fan_off}  

  - platform: template
    id: auto_fan3
    name: ${tdevicename} Auto Mode 3
    web_server:
      sorting_weight: 3
    icon: mdi:tune
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true  
    turn_on_action:   
      then:
        - lvgl.widget.update:
            id: fan3_auto_button
            state:
              checked: true
        - lvgl.label.update:
            id: fan3_auto_text
            text: "AUTO"
        - lvgl.label.update:
            id: fan3_auto_icon
            text: ${fan_auto}    
    turn_off_action:
      then:
        - fan.turn_off : fan3_speed
        - lambda: !lambda |-
              float fan_set_speed = 1.0;
              auto calloff = id(fan3_speed).turn_off();           
              calloff.set_speed(fan_set_speed);
              calloff.perform();
        - lvgl.widget.update:
            id: fan3_auto_button
            state:
              checked: false 
        - lvgl.label.update:
            id: fan3_auto_text
            text: "MAN"
        - lvgl.label.update:
            id: fan3_auto_icon
            text: ${fan_off}  

  - platform: template
    id: auto_fan4
    name: ${tdevicename} Auto Mode 4
    web_server:
      sorting_weight: 4
    icon: mdi:tune
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True  
    turn_on_action:   
      then:
        - lvgl.widget.update:
            id: fan4_auto_button
            state:
              checked: true
        - lvgl.label.update:
            id: fan4_auto_text
            text: "AUTO"
        - lvgl.label.update:
            id: fan4_auto_icon
            text: ${fan_auto}    
    turn_off_action:
      then:
        - fan.turn_off : fan4_speed
        - lambda: !lambda |-
              float fan_set_speed = 1.0;
              auto calloff = id(fan4_speed).turn_off();           
              calloff.set_speed(fan_set_speed);
              calloff.perform();
        - lvgl.widget.update:
            id: fan4_auto_button
            state:
              checked: false 
        - lvgl.label.update:
            id: fan4_auto_text
            text: "MAN"
        - lvgl.label.update:
            id: fan4_auto_icon
            text: ${fan_off}  

  - platform: template
    id: cent_fahr_web
    name: ${tdevicename} Temp Display
    web_server:
      sorting_weight: 1
    entity_category: "Config"
    icon: mdi:temperature-fahrenheit
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True  
    on_turn_on:
            - lvgl.widget.update:
                id: cent_fahr_dis
                state:
                  checked: true
    on_turn_off:
            - lvgl.widget.update:
                id: cent_fahr_dis
                state:
                  checked: false
        #- globals.set:
            #id: cent_fahr_var
            #value: '1.0'
        #- lvgl.dropdown.update:
            #id: cent_fahr_dis
            #selected_index: 2
  
    #turn_off_action:
      #then:
        #- globals.set:
            #id: cent_fahr_var
            #value: '0.0'
        #- lvgl.dropdown.update:
            #id: cent_fahr_dis
            #selected_index: 1

      
  #- platform: gpio
    #pin: GPIO04
    #id: ntc_vcc   

       
       
#-------------------------------------------
# lvgl
#-------------------------------------------    
lvgl:
  displays:
    - my_display

  touchscreens:
    - touchscreen_id: my_touchscreen
```

### Anything in the logs that might be useful for us?

```txt
The YAML is a WORKING version using Clive's external component slightly modified for the "merge" changes:
[23:18:47]ESP-ROM:esp32s3-20210327
[23:18:47]Build:Mar 27 2021
[23:18:47]rst:0x15 (USB_UART_CHIP_RESET),boot:0x8 (SPI_FAST_FLASH_BOOT)
[23:18:47]Saved PC:0x40378c15
[23:18:47]SPIWP:0xee
[23:18:47]mode:DIO, clock div:1
[23:18:47]load:0x3fce3808,len:0x43c
[23:18:47]load:0x403c9700,len:0xbec
[23:18:47]load:0x403cc700,len:0x2a3c
[23:18:47]entry 0x403c98d8
[23:18:47]ESP-ROM:esp32s3-20210327
[23:18:47]Build:Mar 27 2021
[23:18:47]rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[23:18:47]Saved PC:0x420e5e2e
[23:18:47]SPIWP:0xee
[23:18:47]mode:DIO, clock div:1
[23:18:47]load:0x3fce3808,len:0x43c
[23:18:47]load:0x403c9700,len:0xbec
[23:18:47]load:0x403cc700,len:0x2a3c
[23:18:47]entry 0x403c98d8
[23:18:47]ESP-ROM:esp32s3-20210327
```
