### ISSUE TITLE
LVGL Spinbox triggers on_value when updated by lvgl.spinbox.update

### ISSUE THREAD

**Issue by uglide** [esphome/issues#6517]
The problem
I'm attempting to follow the documentation for Spinbox here https://esphome.io/cookbook/lvgl#climate-control

The problem with the spinbox is that it triggers on_value when it's programmatically updated by a sensor trigger. Because of that, the code gets stuck in an endless loop.

The correct behavior: do not trigger on_value when updating spinbox programmatically via lvgl.spinbox.update

Which version of ESPHome has the issue?
2024.11.2

What type of installation are you using?
pip

Which version of Home Assistant has the issue?
No response

What platform are you using?
ESP32-IDF

Board
esp32-s3-devkitc-1

Component causing the issue
lvgl

YAML Config

```
sensor:
  - platform: homeassistant
    id: room_thermostat
    entity_id: climate.room_thermostat
    attribute: temperature
    on_value:
      - lvgl.spinbox.update:
          id: spinbox_id
          value: !lambda return x;

lvgl:
    ...
    pages:
      - id: thermostat_control
        widgets:
          - obj:
              align: BOTTOM_MID
              y: -50
              layout:
                type: FLEX
                flex_flow: ROW
                flex_align_cross: CENTER
              width: SIZE_CONTENT
              height: SIZE_CONTENT
              widgets:
                - button:
                    id: spin_down
                    on_click:
                      - lvgl.spinbox.decrement: spinbox_id
                    widgets:
                      - label:
                           text: "-"
                - spinbox:
                    id: spinbox_id
                    align: CENTER
                    text_align: CENTER
                    width: 50
                    range_from: 15
                    range_to: 35
                    step: 0.5
                    rollover: false
                    digits: 3
                    decimal_places: 1
                    on_value:
                      then:
                        - homeassistant.action:
                            action: climate.set_temperature
                            data:
                              temperature: !lambda return x;
                              entity_id: climate.room_thermostat
                - button:
                    id: spin_up
                    on_click:
                      - lvgl.spinbox.increment: spinbox_id
                    widgets:
                      - label:
                          text: "+"
```
