### ISSUE TITLE
ESPHome WS2812 broke after update

### ISSUE THREAD

**Issue by Simonv92** [esphome/issues#6519]
### The problem

I have updated my devices to the latest ESPHome release (2024.11.2).
After the update 1 Wemos D1 Mini which was controlling a strip of 92x WS2812 led started to have some problems… Led controls seems to not work fine, the first 9 leds start to flicker in different colors. What can it be? before the update everything was working just fine.
Below I attach the code for the D1 Mini.

### Which version of ESPHome has the issue?

2024.11.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.3

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Component causing the issue

NeoPixelBus Light

### YAML Config

```yaml
# Output Socket 
switch:
  - platform: gpio
    pin: D5
    name: "Socket 1"
    id: switch1
  - platform: gpio
    pin: D6
    name: "Socket 2"
    id: switch2
  - platform: gpio
    pin: D7
    name: "Socket 3"
    id: switch3
  - platform: gpio
    pin: D8
    name: "Socket 4"
    id: switch4

# Output Lights    
light:
  - platform: monochromatic
    name: "Keyboard Light"
    output: light1
    default_transition_length: 2s
  - platform: monochromatic
    name: "Desk Light"
    output: light2
    default_transition_length: 2s
  - platform: binary
    name: "Status"
    output: lightS
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    method: ESP8266_UART0
    pin: GPIO1
    num_leds: 92
    name: "NeoPixel Light"
    default_transition_length: 2s
    id: neo
    effects:
      - addressable_rainbow:
          name: Rainbow
          speed: 10
          width: 1
    
# Output Lights
output:
  - platform: esp8266_pwm
    id: light1
    pin: D1
  - platform: esp8266_pwm
    id: light2
    pin: D2
  - platform: gpio
    id: lightS
    pin: D4

# Input Switch
binary_sensor:
  # Device Status
  - platform: status
    name: "Desk Status:"
  # Keyboard Tray -> NC Cloce - NA Open
  - platform: gpio
    pin: D0
    name: "Keyboard Tray"
    device_class: opening 
  - platform: gpio
    pin: D3
    name: "Desk Light"
    device_class: opening
    
# Current Sensor
sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    name: "Desk Consumption:"
    update_interval: 10s
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0 -> 0
          - 0.659 -> 7.65
      - multiply: 33
          
  # ADC reading
  - platform: adc
    pin: A0
    id: adc_sensor
    update_interval: 10s
```
