### ISSUE TITLE
sorting_group_id must not trow error id web_server is disabled

### ISSUE THREAD

**Issue by nliaudat** [esphome/issues#6525]
### The problem

If you have a lot of sorting_group_id and want to disable the web_server, EspHome give dependencies errors : 

  web_server:
    This option requires component web_server.
    sorting_group_id: sorting_group_climate

### Which version of ESPHome has the issue?

latest

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32 devkit-C

### Component causing the issue

web_server

### YAML Config

```yaml
web_server:
  port: 80
  version: 3
  sorting_groups:
    - id: sorting_group_sensors
      name: "Sensors"
      sorting_weight: 2

sensor:
  - platform: dallas_temp
    address: ${dallasaddress_input} 
    id: dallas_input_temp
    web_server:
      sorting_group_id: sorting_group_sensors
```

### Additional information

If setting sorting_group_id for all the components, the web_server cannot be disabled. 
I am waiting for if conditions in yaml ;)
