### ISSUE TITLE
ESP32 S3 BOX 3 not working when updating to 2024.11.3

### ISSUE THREAD

**Issue by SneakieGargamel** [esphome/issues#6529]
### The problem

When I configure my S3 box3 with https://www.home-assistant.io/voice_control/s3_box_voice_assistant/ everthing works fine. 
It will install 2024.11.1 and the S3 box 3 is running, but not connected to Home Assistant. 
When I try to connect it to Home Assistant, ESPHome will upload 2024.11.3 to my S3 Box 3.
But then the screen will turn white and after rebooting the screen doesnt turn on.

I cannot get my S3 box 3 working with 2024.11.3

### Which version of ESPHome has the issue?

2024.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.1

### What platform are you using?

ESP32

### Board

S3 box 3, esp32-s3-devkitc-1

### YAML Config

```yaml
esphome:
  name: esp32-s3-box-3
  friendly_name: ESP32 S3 Box 3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "123="

ota:
  - platform: esphome
    password: "123"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.173
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-S3-Box-3 Fallback Hotspot"
    password: "123"

captive_portal:
```
