### ISSUE TITLE
Errors with component SIM800L

### ISSUE THREAD

**Issue by tiagofreire-pt** [esphome/issues#653]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hassio

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32-WROOM-32

**Affected component:**
SIM800L

**Description of problem:**
Errors are generated using this component: https://github.com/esphome/esphome/pull/522

Also, there is no documentation available in http://esphome-io.

**Problem-relevant YAML-configuration entries:**
```yaml
uart:
  tx_pin: GPIO27
  rx_pin: GPIO14
  baud_rate: 9600
  software_buffer_size: 512

sim800l:
  id: sms
  on_sms_received:
    lambda: |-
      ESP_LOGD("main", "Received sms from %s: %s", sender.c_str(), message.c_str());

binary_sensor:
  platform: gpio
  name: "Send sms"
  pin: GPIO4
  on_press:
    lambda: |-
      id(sms).send_sms("+48634826384236482", "Hello there from ESPHome");

```

**Logs (if applicable):**

```
INFO Reading configuration...
INFO Detected timezone 'WET' with UTC offset 0 and daylight savings time from 03/29/20 01:00:00 to 10/25/20 02:00:00
Failed config

uart: 
  - [source config/miflora.yaml:104]
    tx_pin: GPIO27
    rx_pin: GPIO14
    baud_rate: 9600
    
    [software_buffer_size] is an invalid option for [0]. Please check the indentation.
    software_buffer_size: 512 [source config/miflora.yaml:107]
sim800l: [source config/miflora.yaml:110]
  
  Component not found: sim800l.
  id: sms
  on_sms_received: 
    lambda: ESP_LOGD("main", "Received sms from %s: %s", sender.c_str(), message.c_str());

```
