### ISSUE TITLE
online_image can run forever, never succeeding, erroring or tripping watchdog.

### ISSUE THREAD

**Issue by nspitko** [esphome/issues#6530]
### The problem

I'm running a waveshare s3 LCD device that has a relatively simple task: Update the image once per minute from an external source (via online_image), and show the time.

This mostly works! With two caveats:
1) online_image is very slow, and often will not update within the 1 minute window. This is mostly OK for my use case, but seems really weird

2) sometimes, online_image gets "stuck". It doesn't succeed or error, it just continues to run seemingly forever. It's been blocking for a suspiciously consistent amount of time for over two hours now, so it seems unlikely any kind of timeout is working.

```
[15:19:11][W][component:237]: Component online_image took a long time for an operation (4501 ms).
[15:19:11][W][component:238]: Components should block for at most 30 ms.
[15:19:16][W][component:237]: Component online_image took a long time for an operation (4501 ms).
[15:19:16][W][component:238]: Components should block for at most 30 ms.
[15:19:20][W][component:237]: Component online_image took a long time for an operation (4501 ms).
[15:19:20][W][component:238]: Components should block for at most 30 ms.
[15:19:25][W][component:237]: Component online_image took a long time for an operation (4501 ms).
[15:19:25][W][component:238]: Components should block for at most 30 ms.
[15:19:30][W][component:237]: Component online_image took a long time for an operation (4501 ms).
[15:19:34][W][component:238]: Components should block for at most 30 ms.
[15:19:34][W][component:237]: Component online_image took a long time for an operation (4501 ms).
[15:19:34][W][component:238]: Components should block for at most 30 ms.
[15:19:38][W][component:237]: Component online_image took a long time for an operation (4501 ms).
[15:19:39][W][component:238]: Components should block for at most 30 ms.
```

Unsure how to approach debugging this given the intermittent nature of this, and the fact that it's not hitting any timeouts/watchdogs.

### Which version of ESPHome has the issue?

2024.11.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.3

### What platform are you using?

ESP32-IDF

### Board

:ESP32-S3-Touch-LCD-7

### Component causing the issue

online_image

### YAML Config

```yaml
esphome:
  name: esp-lcd-7-01
  friendly_name: esp-lcd-7-01
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM -DCONFIG_SPIRAM_CACHE_WORKAROUND"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.8.1
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "60"
      #CONFIG_SPIRAM_RODATA: y

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Fkl+ghNOTztAxsaiBJbLfD3iJQHn0OTt7wrzQ+W8FRY="

ota:
  - platform: esphome
    password: "a59eb7b4f54a93a9c0cea9dbcb273fd0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
  #  - component.update: bg
    - script.execute: bg_update

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Lcd-7-01 Fallback Hotspot"
    password: "uG0Wmhq4Bafn"

captive_portal:

globals:
  - id: backgroundGroups
    type: std::vector<std::string>
    restore_value: no
    initial_value: '{"Test"}'

  - id: backgroundCounts
    type: int[6]
    restore_value: no
    initial_value: '{1147}'

  - id: bgIdx 
    type: int 
    initial_value: "0"
    #restore_value: yes

  - id: bgGroupIdx 
    type: int 
    initial_value: "4"
    #restore_value: yes

  - id: onAltBG
    type: bool

  - id: isBusy 
    type: bool 
    initial_value: "false"

i2c:
  sda: GPIO08
  scl: GPIO09
# scan: True
  id: bus_a

ch422g:
  - id: ch422g_hub
    #address: 0x24

psram:
  mode: octal
  speed: 80MHz

# Define display
display:
  - platform: rpi_dpi_rgb
    id: my_display
    auto_clear_enabled: false
    update_interval: never
    color_order: RGB
    pclk_frequency: 16MHZ
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    reset_pin:
      ch422g: ch422g_hub
      number: 3
    enable_pin:
      ch422g: ch422g_hub
      number: 2  
    
    hsync_back_porch: 16
    hsync_front_porch: 16
    hsync_pulse_width: 8
    vsync_back_porch: 16
    vsync_front_porch: 16
    vsync_pulse_width: 8

    data_pins:
      red:
        - 1         #r3
        - 2         #r4
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7
        
    show_test_card: false
      

   
touchscreen:
  platform: gt911
  id: my_touch
  # Uncomment below if you got the janky OTHER i2c address this time 
  #address: 0x14  
  # Probably fixed by adding reset_pin via CH422 though
  interrupt_pin: GPIO4
  # DEFINE RESET PIN for consistent i2c address selection
  # CTP_RST is wired to IO1 of CH422G
  reset_pin:
    ch422g: ch422g_hub
    number: 1
    mode: OUTPUT
  on_touch:
    - lambda: |-
        ESP_LOGI("Touch", "Touch detected at x=%d, y=%d", touch.x, touch.y);
# Define fonts
font:
  - file: "gfonts://Roboto"
    id: roboto_big
    size: 58
    #bpp: 4



lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touch
  pages:
    - id: main_page
      #layout:
      #  type: flex
      #  flex_flow: column_wrap
      width: 800
      height: 480
      scrollable: false
      #bg_color: 0x000000
      #bg_opa: cover
      #bg_image_src: placeholder
      #pad_all: 5
      widgets:
        - image:
            align: CENTER
            src: placeholder
            id: img_bg
        #- label:
        #    text_color: 0x000000
        #    text: "Time..."
        #    text_font: roboto_big
        #     id: text_time_shadow
        #    text_align: CENTER
        #    x: 2
        #    y: 202
        #    width: 800
        - label:
            text_color: 0xFFFFFF
            text: "Time..."
            text_font: roboto_big
            id: text_time
            text_align: CENTER
            x: 0
            y: 415
            width: 800
            bg_color: 0x000000
            bg_opa: "50%"



image:
  - file: "assets/test3.png"
    id: placeholder
    type: RGB565
    resize: 1x1


http_request:

online_image:
  - url: "http://192.168.1.102:8123/local/images/test.png"
    format: png
    id: bg
    type: RGB565
    on_download_finished:
      - lvgl.image.update:
          id: img_bg
          src: bg
      - lambda: |- 
          ESP_LOGI("Image", "Image1 downloaded!");
          id( isBusy ) = false;
      - online_image.release: bg2
    on_error: 
      - lambda: |- 
          ESP_LOGI("Image", "Image1 download failed!");
          id( isBusy ) = false;
          id( onAltBG ) = !id( onAltBG );

  - url: "http://192.168.1.102:8123/local/images/test.png"
    format: png
    id: bg2
    type: RGB565
    on_download_finished:
      - lambda: |- 
          ESP_LOGI("Image", "Image2 downloaded!");
          id( isBusy ) = false;
      - lvgl.image.update:
          id: img_bg
          src: bg2
      - online_image.release: bg
    on_error: 
      - lambda: |- 
          ESP_LOGI("Image", "Image2 download failed!");
          id( isBusy ) = false;
          id( onAltBG ) = !id( onAltBG );


time:
  - platform: homeassistant
    id: esptime
    on_time_sync:
      - script.execute: time_update
    on_time:
      - minutes: '*'
        seconds: '*'
        then:
          - script.execute: time_update

      - minutes: '*'
        seconds: '0'
        then: 
          - script.execute: bg_update


script:
  - id: time_update
    then:
      - component.update: my_display
      - lvgl.label.update:
          id: text_time
          text:
            time_format: "%B %e   %I:%M %p"
            time: !lambda return id(esptime).now();

  - id: bg_update 
    then:
      - lambda: |- 
          if( id( isBusy ) )
          {
            char buf[256];
            sprintf(buf, "http://192.168.1.102:8123/local/images/800x480/%s (%i).png", id(backgroundGroups)[ id(bgGroupIdx) ].c_str(), id(bgIdx) + 1 );
            ESP_LOGI("Images", "Skipping image (Busy with %s)\n", buf);
            return;
          }

          id( isBusy ) = true;
          if( id(bgIdx) >= id(backgroundCounts)[  id(bgGroupIdx) ] )
          {
            id(bgIdx) = 0;
            id(bgGroupIdx) = id(bgGroupIdx) + 1;
            if( id( bgGroupIdx ) >= id(backgroundGroups).size() )
              id(bgGroupIdx) = 0;
          }

          char buf[256];
          sprintf(buf, "http://192.168.1.102:8123/local/images/800x480/%s%%20(%i).png", id(backgroundGroups)[ id(bgGroupIdx) ].c_str(), id(bgIdx) + 1 );

          ESP_LOGI("Images", "Next image: %s\n", buf);
          
          if( id( onAltBG ) )
          {
            id(bg).set_url( buf );
            id(bg).update();
          }
          else 
          {
            id(bg2).set_url( buf );
            id(bg2).update();
          }
          
          id(bgIdx) = id(bgIdx) + 1;
          id( onAltBG ) = !id( onAltBG );

debug:

sensor:
  - platform: template
    name: "bgIdx"
    lambda: |-
      return id(bgIdx);
    update_interval: 60s
    device_class: "distance"
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"
```

### Additional information

The example script cycles through images named "Test (1).png" with an incrementing index. check globals for the number of images to cycle through. These are 800x480 images, but can be smaller obviously.

Note this took several days to happen, so it's not going to be fun/easy to diagnose.
