### ISSUE TITLE
LVGL image mode not recognized

### ISSUE THREAD

**Issue by V1pr** [esphome/issues#6531]
### The problem

If I set the ```mode:``` on the image the build fails with ```error: 'lv_img_set_mode' was not declared in this scope```

### Which version of ESPHome has the issue?

2024.11.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

Guition display board (ESP-S3)

### Component causing the issue

image

### YAML Config

```yaml
widgets:
                    - image:
                        mode: REAL
                        x: 0
                        y: 0
                        offset_x: 1px
                        offset_y: 1px
                        height: 35px
                        width: 35px
                        id: idokep_fc_hour1_icon
                        src: idokep_fc_icon_000_small
                        bg_opa: TRANSP
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/guition-esp32-s3-4848s040/src/main.o
guition-esp32-s3-4848s040-display_esphome.yaml: In function 'void setup()':
guition-esp32-s3-4848s040-display_esphome.yaml:2227:3: error: 'lv_img_set_mode' was not declared in this scope
guition-esp32-s3-4848s040-display_esphome.yaml:2227:3: note: suggested alternative: 'lv_img_set_zoom'
*** [.pioenvs/guition-esp32-s3-4848s040/src/main.o] Error 1
```

### Additional information

The correct lvgl should be ```lv_img_set_size_mode``` according to the LVGL 8.4 docs
