### ISSUE TITLE
Incorrect ID when using friendly_name

### ISSUE THREAD

**Issue by bzumik1** [esphome/issues#6538]
### The problem

The following characters—ě, š, č, ř, ž, ý, á, í, é, and potentially others—are not being correctly translated into entity IDs. When using the `friendly_name` attribute, Czech special characters are incorrectly converted. For instance, I have the `friendly_name` set to `Klimatizace` and an entity named `ložnice`. I would expect the ID to be `klimatizace_loznice`, but instead, it is translated as `klimatizace_lo_nice`. Prior to adding the `friendly_name`, the entity name `ložnice` was correctly converted to `loznice`.

### Which version of ESPHome has the issue?

2024.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.1

### What platform are you using?

ESP32

### Board

not relevant

### YAML Config

```yaml
substitutions:
  name: esp-samsung-ac
  friendly_name: Klimatizace SAMSUNG

packages:
  common: github://bzumik1/HomeAssistant/EspHome/templates/common.yaml@main

esp32:
  board: m5stack-atom

esp32_improv:
  authorizer: none
  wifi_timeout: 5min



# AC CONFIGURATION  
uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main
    components: [samsung_ac]

samsung_ac:
  # debug_log_messages: true
  # debug_log_messages_raw: true

  capabilities: 
    vertical_swing: true
    presets:
      sleep: true
      quiet: true
      fast: true
      longreach: true
      windfree: true
      eco: true

  devices:
    # BEDROOM
    - address: "20.00.00" # unit address
      error_code:
        name: "Klimatizace - ložnice error"

      # You could use the ESPHome/Homeassist climate control
      climate:
        name: "Klimatizace - ložnice"

      # And/or use seperate controls/sensors
      room_temperature:
        name: "Klimatizace - ložnice teplota"
      room_humidity:
        name: "Klimatizace - ložnice vlhkost"
      target_temperature:
        name: "Klimatizace - ložnice požadovaná teplota"
      power:
        name: "Klimatizace - ložnice vypínač"
      automatic_cleaning:
        name: "Klimatizace - ložnice automatické čištění"
      mode:
        name: "Klimatizace - ložnice mód"
    
    # LIVING ROOM
    - address: "20.00.01" # unit address
      error_code:
        name: "Klimatizace - obývák error"

      # You could use the ESPHome/Homeassist climate control
      climate:
        name: "Klimatizace - obývák"

      # And/or use seperate controls/sensors
      room_temperature:
        name: "Klimatizace - obývák teplota"
      room_humidity:
        name: "Klimatizace - obývák vlhkost"
      target_temperature:
        name: "Klimatizace - obývák požadovaná teplota"
      power:
        name: "Klimatizace - obývák vypínač"
      automatic_cleaning:
        name: "Klimatizace - obývák automatické čištění"
      mode:
        name: "Klimatizace - obývák mód"
    
    # OUTDOOR UNIT
    - address: "10.00.00"
      error_code:
        name: "Klimatizace - venkovní jednotka error"
      outdoor_temperature:
        name: "Klimatizace - venkovní teplota"
      outdoor_instantaneous_power:
        name: "Klimatizace - výkon"
      outdoor_cumulative_energy:
        name: "Klimatizace - spotřeba"
      outdoor_current:
        name: "Klimatizace - proud"
      outdoor_voltage:
        name: "Klimatizace - napětí"
```
