### ISSUE TITLE
RF Switch from Home Assistant

### ISSUE THREAD

**Issue by AquaMCU** [esphome/issues#654]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

I am using ESPhome 1.13.6. I want to replace my current Home Assistant setup with a ESPhome stand alone solution.

**ESP (ESP32/ESP8266, Board/Sonoff):**

D1_mini with a RF Transmitter connected to D0.

**Affected component:**

remote_transmitter

**Description of problem:**
I try to migrate the following Home Assistant configuration into ESP home. I can see, that the module transmits (Using a frequency scanner on 433MHz) but the switch does not open

HOME ASSISTANT CONFIG:
      Gartentor:
        pulselength: 370
        code_on: 21
        code_off: 20
        signal_repetitions: 10
        protocol: 1

**Problem-relevant YAML-configuration entries:**
```yaml
remote_transmitter:
  pin: D0
  carrier_duty_percent: 100%

switch:
#  - platform: gpio
#    name: "TM"
#    pin: D0
#    id: TM

  - platform: template
    name: door
    id: door
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
#          code: '00010100000101000001010000010100'
#          protocol: 
#            pulse_length: 396
#            sync: [1,31]
#            zero: [1,3]
#            one: [3,1]
#            inverted: false
#          repeat:
#            times: 10
#            wait_time: 50ms

           code: '00010100'
           protocol: 1
           repeat: 
             times: 10
             wait_time: 50ms

```

**Logs (if applicable):**

```
[D][switch:029]: 'door' Toggling ON.
[D][remote_transmitter:066]: Sending remote code...
```

**Additional information and things you've tried:**
I tried to change and tweak all parameters including the commented out ones. Can you please help me with the configuration?
