### ISSUE TITLE
`BETA` Warning on deprecated expression on `pulse_counter`

### ISSUE THREAD

**Issue by edwardtfn** [esphome/issues#6544]
### The problem

Another warning message coming with IDF v5.1.5:

### Which version of ESPHome has the issue?

2024.12.0b1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32-IDF

### Board

esp32-c3-devkitm-1

### Component causing the issue

pulse_counter

### YAML Config

```yaml
It's just a warning and everything looks to be working fine, but this will show up on the logs when compiling.
```

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/pulse_counter/pulse_counter_sensor.cpp: In static member function 'static void esphome::pulse_counter::BasicPulseCounterStorage::gpio_intr(esphome::pulse_counter::BasicPulseCounterStorage*)':
src/esphome/components/pulse_counter/pulse_counter_sensor.cpp:32:12: warning: '++' expression of 'volatile'-qualified type is deprecated [-Wvolatile]
   32 |       arg->counter++;
      |       ~~~~~^~~~~~~
src/esphome/components/pulse_counter/pulse_counter_sensor.cpp:35:12: warning: '--' expression of 'volatile'-qualified type is deprecated [-Wvolatile]
   35 |       arg->counter--;
      |       ~~~~~^~~~~~~
```

### Additional information

```yaml
esphome:
  name: "bedroom-bed-presence"
  friendly_name: Bedroom - Bed presence
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: ElevatedSensors.BedPresenceMk1
    version: DIY
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable wifi
wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# Enable esphome OTA updates
ota:
- platform: esphome

################################################################################
packages:
  remote_package:
    url: https://github.com/ElevatedSensors/sensor-configs
    ref: main
    files: [bed-presence-mk1/base.yaml]
    refresh: 1s

# See https://github.com/ElevatedSensors/sensor-configs/blob/main/bed-presence-mk1/sensor.yaml for a detailed
# description of available substitutions.
#
# substitutions:
#   trigger_percentile: '0.75'
#   averaging_window_samples: '5'
#   fast_delayed_on: '0ms'
#   fast_delayed_off: '0ms'
#   standard_delayed_on: '0s'
#   standard_delayed_off: '1s'
#   reporting_delta: '1.0'
#   reporting_interval_max: '180s'
#   calibrate_100: '408000'
#   calibrate_0: '276000'
```
