### ISSUE TITLE
light.addressable_set is not being sent to home-assistant

### ISSUE THREAD

**Issue by oliv3r** [esphome/issues#6546]
### The problem

I have a LED strip with an IR remote (e.g. button) to configure my ledstrip with. Using the configuration from https://github.com/esphome/esphome-devices/pull/947 I can make everything work as expected. However, changing a color using the remote (e.g. using `light.addresseable_set` works for about a second, but then switches to whatever home-assistant thinks the color should be. Changing of the color is also never displayed in home-assistant, but does show up in the log.

![image](https://github.com/user-attachments/assets/7cee4044-4e06-4016-a4bc-a8258bdfc71f)
![image](https://github.com/user-attachments/assets/25db62a5-9aaa-4184-82f2-eae3a1a74d2b)

No idea why it says 'turned off' however ...

Because of this, it seems like `light.addressable_set` never updates home assistant with this state-change.

Note, that I also tried to (or rather, my initial configuration) was to just change the leds, e.g. without doing two steps,  but that didn't seem to make a difference. The `light.turn_on` action is needed because a) if the light is off, changing the color, should turn it on; b) if the light is performing some effect, we need to disable whatever effect is running.

These are limitations from the remote control only, using HA we have all color/effect options/combinations that work just fine.

### Which version of ESPHome has the issue?

2024.11.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

BK72XX

### Board

LSC/Tuya

### Component causing the issue

light

### YAML Config

```yaml
substitutions:
  device_name: "lsc-battletron-strip-3m"
  friendly_name: "LSC Battletron Desk Strip 3 meter"
  device_description: "3 meter 'neon' LED strip from Action, the Battletron Desk strip, by LSC Smart Connect - 3206528"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  name_add_mac_suffix: true
  min_version: 2024.6.6

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    password: !secret fallback_hotspot_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password

improv_serial:

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

  - platform: wifi_info
    ip_address:
      name: IP
    mac_address:
      name: MAC
    ssid:
      name: SSID
    bssid:
      name: BSSID

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic

  - platform: safe_mode
    name: Safe mode
    entity_category: diagnostic

  - platform: factory_reset
    name: Factory reset
    entity_category: diagnostic

remote_receiver:
  pin:
    number: P26
    inverted: true
    mode:
      input: true

binary_sensor:
  - platform: gpio
    name: "Button"
    pin:
      number: P28
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      - light.toggle: color_light

  - platform: remote_receiver
    name: "Light On"
    nec:
      address: 0xFF00
      command: 0xBA45
    on_press:
      then:
        - light.turn_on: color_light

  - platform: remote_receiver
    name: "Light Off"
    nec:
      address: 0xFF00
      command: 0xB847
   on_press:
      then:
        - light.turn_off: color_light

  - platform: remote_receiver
    name: "Color Red"
    nec:
      address: 0xFF00
      command: 0xBB44
   on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "none"
        - light.addressable_set:
            id: color_light
            red: 100%
            green: 0%
            blue: 0%

  - platform: remote_receiver
    name: "Color Green"
    nec:
      address: 0xFF00
      command: 0xBF40
    on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "none"
        - light.addressable_set:
            id: color_light
            red: 0%
            green: 100%
            blue: 0%

  - platform: remote_receiver
    name: "Color Blue"
    nec:
      address: 0xFF00
      command: 0xBC43
    on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "none"
        - light.addressable_set:
            id: color_light
            red: 0%
            green: 0%
            blue: 100%

  - platform: remote_receiver
    name: "Color Orange"
    nec:
      address: 0xFF00
      command: 0xF807
   on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "none"
        - light.addressable_set:
            id: color_light
            red: 100%
            green: 50%
            blue: 0%

  - platform: remote_receiver
    name: "Color Light Green"
    nec:
      address: 0xFF00
      command: 0xEA15
   on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "none"
        - light.addressable_set:
            id: color_light
            red: 50%
            green: 100%
            blue: 50%

  - platform: remote_receiver
    name: "Color Cyan"
    nec:
      address: 0xFF00
      command: 0xF609
   on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "none"
        - light.addressable_set:
            id: color_light
            red: 0%
            green: 100%
            blue: 100%

  - platform: remote_receiver
    name: "Color Yellow"
    nec:
      address: 0xFF00
      command: 0xE916
   on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "none"
        - light.addressable_set:
            id: color_light
            red: 100%
            green: 100%
            blue: 0%

  - platform: remote_receiver
    name: "Color Random"
    nec:
      address: 0xFF00
      command: 0xE619
   on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "Random"

  - platform: remote_receiver
    name: "Color Magenta"
    nec:
      address: 0xFF00
      command: 0xF20D
    on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "none"
        - light.addressable_set:
            id: color_light
            red: 100%
            green: 0%
            blue: 100%

  - platform: remote_receiver
    name: "Brighter"
    nec:
      address: 0xFF00
      command: 0xF30C
    on_press:
      then:
        - light.dim_relative:
            id: color_light
            relative_brightness: +5%

  - platform: remote_receiver
    name: "Color White"
    nec:
      address: 0xFF00
      command: 0xE718
    on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "none"
        - light.addressable_set:
            id: color_light
            red: 100%
            green: 100%
            blue: 100%

  - platform: remote_receiver
    name: "Dimmer"
    nec:
      address: 0xFF00
      command: 0xA15E
    on_press:
      then:
        - light.dim_relative:
            id: color_light
            relative_brightness: -5%

  - platform: remote_receiver
    name: "Color Wipe"
    nec:
      address: 0xFF00
      command: 0xF708
    on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "Color Wipe"

  - platform: remote_receiver
    name: "Color Rainbow"
    nec:
      address: 0xFF00
      command: 0xE31C
    on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "Rainbow"

  - platform: remote_receiver
    name: "Color Twinkle"
    nec:
      address: 0xFF00
      command: 0xA55A
    on_press:
      then:
        - light.turn_on:
            id: color_light
            effect: "Twinkle"

power_supply:
    id: led_power
    pin: P8

light:
  - platform: beken_spi_led_strip
    id: color_light
    name: "Color Light"
    pin: P16
    chipset: WS2812
    num_leds: 36
    rgb_order: GRB
    power_supply: led_power
    effects:
     - random:
     - pulse:
     - strobe:
     - flicker:
     - addressable_rainbow:
     - addressable_color_wipe:
     - addressable_scan:
     - addressable_twinkle:
     - addressable_random_twinkle:
     - addressable_fireworks:

sensor:
  - platform: uptime
    name: "Uptime"
```

### Anything in the logs that might be useful for us?

```txt
Logs are not very useful in this case.
```
