### ISSUE TITLE
IR transmitter repeat wait_time stopeed working

### ISSUE THREAD

**Issue by sisaenkov** [esphome/issues#655]
After upgrading from 1.12.x to 1.13.x stopped working **wait_time** in repeat section.

The part of configuration below:

```
    platform: template
    id: bedroomtvkodi
    name: Bedroom TV Kodi
    turn_on_action:
      remote_transmitter.transmit_samsung:
        data: 0xE0E0807F
        repeat:
          times: 3
          wait_time: 1s
```

It looks like this parameter is ignored and all IR-commands are sent without delay.
