### ISSUE TITLE
Hardware SPI not working on Raspberry Pi Pico W

### ISSUE THREAD

**Issue by torndar** [esphome/issues#6551]
### The problem

I have an ILI9xxx [1] display connected and the test screen loads but painfully slowly (multiple seconds) and I saw in the log output that it is using software SPI. I'm happy to help test any changes.

```
[08:59:21][C][spi:064]: SPI bus:
[08:59:21][C][spi:065]:   CLK Pin: GPIO2
[08:59:21][C][spi:066]:   SDI Pin: GPIO3
[08:59:21][C][spi:067]:   SDO Pin: GPIO4
[08:59:21][C][spi:074]:   Using software SPI
```

[1] https://esphome.io/components/display/ili9xxx

### Which version of ESPHome has the issue?

2024.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.3

### What platform are you using?

RP2040

### Board

rpipicow

### Component causing the issue

spi

### YAML Config

```yaml
esphome:
  name: bedroomenvsensor
  friendly_name: BedroomEnvSensor

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Bedroomenvsensor"
    password: ""

output:
  - platform: gpio
    pin:
      number: LED
      mode: output
    id: LED

#interval:
#  - interval: 500ms
#    then:
#      - output.turn_on: LED
#      - delay: 250ms
#      - output.turn_off: LED

i2c:
  # "raw" pins not physical pins https://datasheets.raspberrypi.com/picow/PicoW-A4-Pinout.pdf
  sda: GPIO20 
  scl: GPIO21

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76

spi:
  - miso_pin: GPIO3
    mosi_pin: GPIO4
    clk_pin: GPIO2
    #interface: hardware

display:
  - platform: ili9xxx
    model: ili9341
    dc_pin: GPIO06
    reset_pin: GPIO05
    invert_colors: false
    show_test_card: true
```

**Comment by clydebarrow** [comment]
> [08:59:21][C][spi:065]:   CLK Pin: GPIO2
> [08:59:21][C][spi:066]:   SDI Pin: GPIO3
> [08:59:21][C][spi:067]:   SDO Pin: GPIO4

That pin configuration is not supported by the RP2040. If you swap the SDI and SDO pins it will work. Add `interface: hardware` to the spi config to ensure that you do get hardware

**Comment by torndar** [comment]
I finally got around to updating my config but hardware SPI seems to boot loop

If I flip the SPI config to the snippet below and flip the wires around to match it works and shows the test card fine.

```
    miso_pin: GPIO3
    mosi_pin: GPIO4
```

## CONFIG:
```
esphome:
  name: bedroomenvsensor
  friendly_name: BedroomEnvSensor

safe_mode:
  num_attempts: 3

rp2040:
  board: rpipicow

# Enable logging
logger:
  level: "VERBOSE"

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXX"

ota:
  - platform: esphome
    password: "XXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Bedroomenvsensor"
    password: "XXXXXX"

output:
  - platform: gpio
    pin:
      number: LED
      mode: output
    id: LED

#interval:
#  - interval: 500ms
#    then:
#      - output.turn_on: LED
#      - delay: 250ms
#      - output.turn_off: LED

i2c:
  # "raw" pins not physical pins https://datasheets.raspberrypi.com/picow/PicoW-A4-Pinout.pdf
  sda: GPIO20 
  scl: GPIO21

sensor:
  - platform: bme280_i2c
    temperature:
      id: temperature
      name: "BME280 Temperature"
    pressure:
      name: "BME280 Pressure"
    humidity:
      id: humidity
      name: "BME280 Humidity"
    address: 0x76

spi:
  - clk_pin: GPIO2
    miso_pin: GPIO4
    mosi_pin: GPIO3
    #interface: hardware
  
font:
    # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20

time:
  - id: currenttime
    platform: homeassistant

display:
  - platform: ili9xxx
    model: ili9341
    dc_pin: GPIO06
    reset_pin: GPIO05
    invert_colors: false
    show_test_card: true
    color_order: BGR
#    transform: 
#      swap_xy: false
#      mirror_x: false
#      mirror_y: true
#    update_interval: 10s
#    lambda: |-
#      // %% - literal % sign
#      //auto time = id(currenttime).now();
#      it.printf(0, 0, id(roboto_20), "Temperature: %.1f°C", id(temperature).state);
#      it.printf(0, 20, id(roboto_20), "Humidity: %.1f%%", id(humidity).state);
#      it.strftime(0, 40, id(roboto_20), "%Y-%m-%d %H:%M", id(currenttime).now());
#      //it.print(0, 0, id(roboto_20), COLOR_ON, TextAlign::CENTER, "Just\U000f05d4here. Already\U000F02D1this.", COLOR_OFF);
```
## LOGS:

```
tail -F /dev/ttyACM0 
[D][esphome.ota:293]: Progress: 77.1%

[D][esphome.ota:293]: Progress: 89.1%

[I][esphome.ota:326]: Update complete

[W][component:170]: Component esphome.ota cleared Warning flag

[I][app:132]: Rebooting safely...

tail: '/dev/ttyACM0' has become inaccessible: No such file or directory
tail: '/dev/ttyACM0' has appeared;  following new file
[D][ili9xxx:034]: Setting up ILI9xxx

[D][spi_device:362]: mode 0, data_rate 40000kHz

[V][ili9xxx:420]: Command EF, length 3, bits 03

[V][ili9xxx:420]: Command CF, length 3, bits 00

[V][ili9xxx:420]: Command ED, length 4, bits 64

[V][ili9xxx:420]: Command E8, length 3, bits 85

[V][ili9xxx:420]: Command CB, length 5, bits 39

[V][ili9xxx:420]: Command F7, length 1, bits 20

[V][ili9xxx:420]: Command EA, length 2, bits 00

[V][ili9xxx:420]: Command C0, length 1, bits 23

[V][ili9xxx:420]: Command C1, length 1, bits 10

[V][ili9xxx:420]: Command C5, length 2, bits 3E

[V][ili9xxx:420]: Command C7, length 1, bits 86

[V][ili9xxx:420]: Command 36, length 1, bits 48

[V][ili9xxx:420]: Command 37, length 1, bits 00

[V][ili9xxx:420]: Command 3A, length 1, bits 55

[V][ili9xxx:420]: Command B1, length 2, bits 00

[V][ili9xxx:420]: Command B6, length 3, bits 08

[V][ili9xxx:420]: Command F2, length 1, bits 00

[V][ili9xxx:420]: Command 26, length 1, bits 01

[V][ili9xxx:420]: Command E0, length 15, bits 0F

[V][ili9xxx:420]: Command E1, length 15, bits 00

[V][ili9xxx:420]: Command 11, length 0, bits 29

[V][ili9xxx:424]: Delay 150ms

[V][ili9xxx:420]: Command 29, length 0, bits 00

[V][ili9xxx:424]: Delay 150ms

[D][ili9xxx:030]: Wrote MADCTL 0x48

[C][bme280.sensor:091]: Setting up BME280...

[C][wifi:048]: Setting up WiFi...

[C][wifi:061]: Starting WiFi...

[C][wifi:062]:   Local MAC: 28:CD:C1:05:6A:18

[D][wifi:482]: Starting scan...

[V][bme280.sensor:210]: Sending conversion request...

tail: '/dev/ttyACM0' has become inaccessible: No such file or directory
tail: '/dev/ttyACM0' has appeared;  following new file
[C][wifi:062]:   Local MAC: 28:CD:C1:05:6A:18

[D][wifi:482]: Starting scan...

[W][component:157]: Component wifi set Warning flag: scanning for networks

[V][wifi_pico_w:212]: Scan done!

[D][wifi:497]: Found networks:

[elided]

[I][wifi:313]: WiFi Connecting to 'MINE'...

[V][wifi:315]: Connection Params:

[V][wifi:316]:   SSID: 'MINE'

[V][wifi:319]:   BSSID: B4:FB:E4:44:7F:10

[V][wifi:349]:   Password: 'XXXXXXXX'

[V][wifi:354]:   Channel: 6

[V][wifi:363]:   Using DHCP IP

[V][wifi:365]:   Hidden: NO

[I][wifi:617]: WiFi Connected!

[C][wifi:428]:   Local MAC: 28:CD:C1:05:6A:18

[C][wifi:433]:   SSID: 'MINE'

[C][wifi:436]:   IP Address: 10.70.3.140

[C][wifi:439]:   BSSID: B4:FB:E4:44:7F:10

[C][wifi:441]:   Hostname: 'bedroomenvsensor'

[C][wifi:443]:   Signal strength: -69 dB ▂▄▆█

[V][wifi:445]:   Priority: 0.0

[C][wifi:447]:   Channel: 6

[C][wifi:448]:   Subnet: 255.255.255.0

[C][wifi:449]:   Gateway: 10.70.3.1

[C][wifi:450]:   DNS1: 10.70.3.1

[C][wifi:451]:   DNS2: 0.0.0.0

[D][wifi:626]: Disabling AP...

[I][app:062]: setup() finished successfully!

[W][safe_mode:099]: SAFE MODE IS ACTIVE

[W][component:170]: Component wifi cleared Warning flag

[I][app:100]: ESPHome version 2024.11.3 compiled on Dec 30 2024, 22:03:38

[C][wifi:600]: WiFi:

[C][wifi:428]:   Local MAC: 28:CD:C1:05:6A:18

[C][wifi:433]:   SSID: 'MINE'

[C][wifi:436]:   IP Address: 10.70.3.140

[C][wifi:439]:   BSSID: B4:FB:E4:44:7F:10

[C][wifi:441]:   Hostname: 'bedroomenvsensor'

[C][wifi:443]:   Signal strength: -69 dB ▂▄▆█

[V][wifi:445]:   Priority: 0.0

[C][wifi:447]:   Channel: 6

[C][wifi:448]:   Subnet: 255.255.255.0

[C][wifi:449]:   Gateway: 10.70.3.1

[C][wifi:450]:   DNS1: 10.70.3.1

[C][wifi:451]:   DNS2: 0.0.0.0

[C][logger:185]: Logger:

[C][logger:186]:   Level: VERBOSE

[C][logger:188]:   Log Baud Rate: 115200

[C][logger:189]:   Hardware UART: USB_CDC

[C][mdns:116]: mDNS:

[C][mdns:117]:   Hostname: bedroomenvsensor

[V][mdns:118]:   Services:

[V][mdns:120]:   - _http, _tcp, 80

[V][mdns:122]:     TXT: version = 2024.11.3

[C][esphome.ota:073]: Over-The-Air updates:

[C][esphome.ota:074]:   Address: bedroomenvsensor.local:2040

[C][esphome.ota:075]:   Version: 2

[C][esphome.ota:078]:   Password configured

[C][safe_mode:018]: Safe Mode:

[C][safe_mode:019]:   Boot considered successful after 60 seconds

[C][safe_mode:021]:   Invoke after 3 boot attempts

[C][safe_mode:022]:   Remain in safe mode for 300 seconds

[W][safe_mode:031]: SAFE MODE IS ACTIVE
```
