### ISSUE TITLE
remote_receiver broken after 2024.4.2

### ISSUE THREAD

**Issue by tomaszduda23** [esphome/issues#6552]
### The problem

remote_receiver broken after 2024.4.2. raw show data but completely random values.

### Which version of ESPHome has the issue?

2024.9.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### YAML Config

```yaml
remote_receiver:
  pin:
    number: 19
    # inverted: True
    mode:
      input: true
      pullup: true
  dump:
    - raw
    - rc_switch
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb
```

### Additional information

This fix the issue
```yaml
external_components:
  - source: github://esphome/esphome@2024.4.2
    components: [ remote_base, remote_receiver ]
    refresh: 0s
```

**Comment by tomaszduda23** [comment]
It can be solved by using this config:
```yaml
remote_receiver:
  pin:
    number: 19
    mode:
      input: true
  dump:
    - rc_switch
  idle: 4ms
  tolerance: 60%
  filter: 4us
```
