### ISSUE TITLE
esp32_ble_tracker.register_client allows registering more clients than the device supports (try to allocate too many ble clients)

### ISSUE THREAD

**Issue by tomaszduda23** [esphome/issues#6553]
### The problem

esphome tries to allocate 4 ble devices and last one fails. It seems that it should be:
2 connections for ble proxy
1 connetion for ble client

```
[V][esp32_ble_client:121]: [0] [] gattc_event_handler: event=0 gattc_if=4
[V][esp32_ble_client:127]: [0] [] gattc registered app id 1
[V][esp32_ble:367]: (BLE) gattc_event [esp_gatt_if: 5] - 0
[V][esp32_ble_client:121]: [1] [] gattc_event_handler: event=0 gattc_if=5
[V][esp32_ble_client:127]: [1] [] gattc registered app id 2
[V][esp32_ble:367]: (BLE) gattc_event [esp_gatt_if: 6] - 0
[V][esp32_ble_client:121]: [2] [] gattc_event_handler: event=0 gattc_if=6
[V][esp32_ble_client:127]: [2] [] gattc registered app id 3
[V][esp32_ble:367]: (BLE) gattc_event [esp_gatt_if: 0] - 0
[V][esp32_ble_client:121]: [3] [] gattc_event_handler: event=0 gattc_if=0
[E][esp32_ble_client:131]: [3] [] gattc app registration failed id=4 code=128
```

### Which version of ESPHome has the issue?

2024.9.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### YAML Config

```yaml
esp32:
  board: esp32doit-devkit-v1
esp32_ble:
  io_capability: keyboard_only

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true  <- this makes esphome to tires to allocate 4 connections

ble_client:
- mac_address: "yyy"
  id: pvvx_ble_display
  on_passkey_request:
    then:
      - logger.log: "Authenticating with passkey"
      - ble_client.passkey_reply:
          id: pvvx_ble_display
          passkey: xyz

display:
- platform: pvvx_mithermometer
  ble_client_id: pvvx_ble_display
  update_interval: 24h
  validity_period: 0s
  disconnect_delay: 30s
  time_id: homeassistant_time
  id: display_bathroom
```
