### ISSUE TITLE
74HC595 problem with CS

### ISSUE THREAD

**Issue by roma6868** [esphome/issues#6564]
### The problem

Hello

I'm working with an ESP8266 D1mini esphome + home assistant.
My ESP8266 is connected to a 74HC595 which itself is connected to a UDN2981A and it controls relays.
I had problems with random activation of relays.

I decided to connect a signal analyzer on the communication bus between the ESP8266 and 74hc595 to see what is happening.
The CLK and MOSI signals are well opposite each other, but the CS pin signal is delayed by about 50us, which is really strange.

I tried to communicate with the 74hc595 by HW_SPI or by the GPIOs I have the same problem of delay of the CS pin compared to the CLK and MOSI.
I also tested with an ESP32 Wroom 32 I have the same problem.

The CS pin should be active throughout the data transmission to 74hc595 at my place this is not the case.

To check if the problem came from the HW side of my ESP I tried to communicate via the SPI with an MCP3008 all the signals are well synchronized

### Which version of ESPHome has the issue?

2024.11.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.12.3

### What platform are you using?

ESP8266

### Board

 ESP8266 D1mini esphome

### Component causing the issue

SPI

### YAML Config

```yaml
#-------------------------------------------------------------------------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------------------------------------------------------------------------

# ESP8266 D1 mini
# https://i0.wp.com/randomnerdtutorials.com/wp-content/uploads/2019/05/ESP8266-WeMos-D1-Mini-pinout-gpio-pin.png?quality=100&strip=all&ssl=1

# RST        | RST     |
# ADC0       | ADC0    | 
# WAKE       | GPIO16  |
# SCLK       | GPIO14  |  HW_SCK (74HC595)
# MISO       | GPIO12  |   
# MOSI       | GPIO13  |  HW_MOSI (74HC595)
# CS         | GPIO15  |  HW_CS (74HC595) 
# 3.3v       | GPIO25  |


# TXD0        | GPIO1  | 
# RXD0        | GPIO3  |
# SCL         | GPIO5  |
# SDA         | GPIO4  |
# FLASH       | GPIO0  |
# GPIO2       | GPIO2  |
# GND         | GND    |
# 5V          | 5V     |

#-------------------------------------------------------------------------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------------------------------------------------------------------------

esphome:
  name: esp8266-pac-chauffage
  friendly_name: ESP8266_PAC_chauffage

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Pac-Chauffage"
    password: "123456"

captive_portal:


  # https://esphome.io/guides/configuration-types#config-pin-schema
# LED STATE
light:
  - platform: status_led
    name: "Switch state"
    # Advanced:
    pin:
      number: GPIO3 #GPIO2 # => LED blue sur le PCB
      inverted: true
      #mode:
      #  input: true
      #  pullup: true

switch:
  - platform: gpio
    pin: GPIO2
    id: LED_state

  - platform: gpio
    name: "SN74HC595[1][0]"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 0
      inverted: false

  - platform: gpio
    name: "SN74HC595[1][1]"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 1
      number: 1
      inverted: false

  - platform: gpio
    name: "SN74HC595[1][2]"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 2
      number: 2
      inverted: false

  - platform: gpio
    name: "SN74HC595[1][3]"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 3
      number: 3
      inverted: false
    
  - platform: gpio
    name: "SN74HC595[1][4]"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 4
      number: 4
      inverted: false

  - platform: gpio
    name: "SN74HC595[1][5]"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 5
      number: 5
      inverted: false

  - platform: gpio
    name: "SN74HC595[1][6]"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 6
      number: 6
      inverted: false

  - platform: gpio
    name: "SN74HC595[1][7]"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 7
      number: 7
      inverted: false

interval:
  - interval: 1s
    then: 
      - switch.toggle: LED_state
      # - component.update: ADC_panneau_thermique_eau_IN #possibilite de mettre a jour une fonction avec cette commande

# Example configuration entry
sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: GPIO13
    clock_pin: GPIO14
    #oe_pin: GPIO5
    latch_pin: 
      number: GPIO15
      mode: 
        output: True
        input: False
        open_drain: False
        pullup: False
        pulldown: False
      inverted: False
      #ignore_pin_validation_error: False
      #ignore_strapping_warning: False
      #drive_strength: 20.0
    sr_count: 1
    type: gpio



# Example with SPI
#spi:
#  clk_pin: GPIO14
#  mosi_pin: GPIO13
#  miso_pin: GPIO12
#sn74hc595:
#  - id: sn74hc595_hub
#    latch_pin: GPIO15
#    oe_pin: GPIO05
#    sr_count: 1
#    type: spi
```

###### Tram capture of the communication between ESP8266 and the 74hc595
![396696818-a50d413f-077e-4999-8f96-07378fa1790b](https://github.com/user-attachments/assets/f0b61150-1bb1-428a-b85b-f7671b3b1df5)
