### ISSUE TITLE
packages 'extend' yaml syntax not expanding correctly

### ISSUE THREAD

**Issue by Kriechi** [esphome/issues#6572]
### The problem

I'm trying to use packages, as documented [here](https://esphome.io/components/packages), specifically the `extend` yaml syntax to use a common setting while overriding it for a specific device, as documented [here](https://esphome.io/components/packages).

Validating the config or compile using the CLI fails with an error:
`Source for extension of ID 'mqtt_client' was not found.`

Expected behaviour: validate and compile without error and correctly extending / changing the parameter as intended. The `reboot_timeout` parameter should be correctly overridden for this device.

The printed error message actually correctly picks up the correct section from the `common.yaml` but it looks like the text substitution fails.

### Which version of ESPHome has the issue?

2024.12.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

any

### What platform are you using?

ESP8266

### Board

any

### Component causing the issue

any

### YAML Config

```yaml
# smart_plug.yaml
packages:
  common: !include common.yaml

mqtt:
  id: !extend mqtt_client
  reboot_timeout: 0s

esphome:
  name: smart-plug

esp8266:
  board: esp01_1m

################################
# common.yaml
wifi:
  ssid: ssid
  password: password

mqtt:
  id: mqtt_client
  broker: broker.example.com
  port: 1883
  username: username
  password: password
  discovery_unique_id_generator: mac
```

### Anything in the logs that might be useful for us?

```txt
$ esphome config smart_plug.yaml
INFO ESPHome 2024.12.0
INFO Reading configuration smart_plug.yaml...
Failed config

mqtt: [source common.yaml:5]
  
  Source for extension of ID 'mqtt_client' was not found.
  id: !extend mqtt_client
  broker: broker.example.com
  port: 1883
  username: username
  password: password
  discovery_unique_id_generator: mac
  reboot_timeout: 0s
```
