### ISSUE TITLE
No sensor readings via Modbus

### ISSUE THREAD

**Issue by stawek7902** [esphome/issues#6575]
### The problem

After updating from 2024.11 to version 2024.12, error 705 is returned on the Modbus instead of the sensor value. 

### Which version of ESPHome has the issue?

2024.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.

### What platform are you using?

ESP32

### Board

Kincony KC868-A2

### Component causing the issue

Modbus controller

### YAML Config

```yaml
uart:
  id: uart_bus
  rx_pin: GPIO35
  tx_pin: GPIO32
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  stop_bits: 1
  debug:
    direction: BOTH

modbus:
  id: modbus1
  uart_id: uart_bus
  send_wait_time: 800ms

modbus_controller:
  - id: modbus_device1
    address: 1
    modbus_id: modbus1
    command_throttle: 1000ms
.....
sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_device1
    id: napieciessr1
    name: "P1 napiecie SSR1 BOJLER"
    unit_of_measurement: "V"
    value_type: FP32
    custom_command: [0x1, 0x4, 0x00, 0x00, 0x00, 0x01]
    accuracy_decimals: 1
```

### Anything in the logs that might be useful for us?

```txt
[D][uart_debug:114]: >>> 01:04:00:00:00:01:31:CA
[11:25:12][E][modbus_controller:705]: not enough data for value
[11:25:12][D][modbus_controller.sensor:025]: Sensor new state: 0.00
[11:25:13][D][sensor:094]: 'P1 napiecie SSR1 BOJLER': Sending state 0.00000 V with 1 decimals of accuracy
[11:25:13][D][uart_debug:114]: <<< 01:04:02:43:6F:C8:2C
```

### Additional information

Before the firmware change, the readings were correct. No errors or warnings.
