### ISSUE TITLE
Mqtt topic name is wrong when name_add_mac_suffix is used

### ISSUE THREAD

**Issue by Hadatko** [esphome/issues#6584]
### The problem

Imagine we have two different devices. I set name_add_mac_suffix = true. Both connect tothe  same mqtt infrastracture. For HA config messages (discovery) they are using correct topic name` <name>_<mac>`. But for data they are using `<name>`. This endup in state that two different devices are pushing data to the same topics.

### Which version of ESPHome has the issue?

tested several from 2024.6.0 to the 2024.12.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2024.10.3

### What platform are you using?

ESP32

### Component causing the issue

mqtt

### YAML Config

```yaml
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.11.0
  name_add_mac_suffix: true
  project:
    name: cervenka.lettis_invertor
    version: "1.0.0"
mqtt:
  broker: ${mqtt_ip}
  username: ${mqtt_user}
  password: ${mqtt_pass}
  # discovery_unique_id_gene
```
