### ISSUE TITLE
Fan speed can not be 0 

### ISSUE THREAD

**Issue by Potyike** [esphome/issues#6586]
### The problem

When I set the fan speed to 0 (turn the fan off) esphome reports the last used speed value (instead of 0) to home assistant.  On the fan's 'more info' dialog the fan is off, on the dashboard the state is 'off' but the speed is the last used value (ie. 100%) 

<img width="578" alt="2" src="https://github.com/user-attachments/assets/28c17ee8-f2a8-43b9-8685-e9d3347e0062" />
<img width="917" alt="1" src="https://github.com/user-attachments/assets/e84d37f9-c933-4231-a95a-f9bbfc18b2ea" />

### Which version of ESPHome has the issue?

2024.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.2

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

fan

### YAML Config

```yaml
fan:
  - platform: template
    id: supply_fan
    speed_count: 2
    name: Supply Fan
    restore_mode: RESTORE_DEFAULT_OFF
    on_speed_set:
      then:
        - if:
            condition:
              lambda: return (id(supply_fan).speed == 1) ;
            then:
             - output.turn_on: supply_low_high
             - output.turn_on: supply_on_off
        - if:
            condition:
              lambda: return (id(supply_fan).speed == 2);
            then:
              - output.turn_off: supply_low_high
              - output.turn_on: supply_on_off
        - if:
            condition:
              lambda: return (id(supply_fan).state == 0);
            then:
              - output.turn_off: supply_low_high
              - output.turn_off: supply_on_off
   
    on_turn_off:
      - output.turn_off: supply_low_high
      - output.turn_off: supply_on_off
```

### Additional information

#3115  #4285
