### ISSUE TITLE
Compile of esp32 btproxy fails in HA/ESPHome Builder

### ISSUE THREAD

**Issue by meliora** [esphome/issues#6588]
### The problem

When compiling a btproxy for ESP32 in RPI4 with 64-bit kernel and 32-bit userspace the compile fails for missing "tasmota/tool-mklittlefs" v3.2.0 for system 'linux_armv7l'.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.5

### What platform are you using?

ESP32-IDF

### Board

Nodemcu 32S

### YAML Config

```yaml
esphome:
  name: esp32-btproxy
  friendly_name: esp32-btproxy

esp32:
  board: esp32dev
  framework:
    type: esp-idf  

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
  - platform: esphome
    password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Btproxy Fallback Hotspot"
    password: "..."

esp32_ble_tracker:
  scan_parameters: 
    interval: 1100ms
    window: 1100ms
    active: True

bluetooth_proxy:
  active: True
      
captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/esp32-btproxy.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.3.2
INFO Compiling app...
Processing esp32-btproxy (board: esp32dev; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
Tool Manager: Installing tasmota/tool-mklittlefs @ ^3.2.0
INFO Installing tasmota/tool-mklittlefs @ ^3.2.0
UnknownPackageError: Could not find the package with 'tasmota/tool-mklittlefs @ ^3.2.0' requirements for your system 'linux_armv7l'
```

### Additional information

Running on Raspberry Pi 4, Debian 11.11 (bullseye), aarch64 kernel, armv7 userspace.

**Comment by perseus177** [comment]
Same problem

**Comment by bradweingartner** [comment]
Experiencing a similar issue on Raspberry Pi 2 running Home Assistant.

I'd like to note that the error occurs on currently running and previously successfully compiled code.

`Tool Manager: Installing tasmota/tool-mklittlefs @ ^3.2.0
INFO Installing tasmota/tool-mklittlefs @ ^3.2.0
UnknownPackageError: Could not find the package with 'tasmota/tool-mklittlefs @ ^3.2.0' requirements for your system 'linux_armv7l'`

**Comment by sca075** [comment]
Same problem updating the S3 box 3 for voice assistant. Downgraded ESPHome it was possible to update the device.

**Comment by ssieb** [comment]
I don't know what would be pulling that in since esphome doesn't use it and why tasmota.  But support for ARMv7 is getting dropped very soon if not already and I can't imagine trying to compile on a Pi2 anyway.

**Comment by sca075** [comment]
```
NOTICE: Current idf-component-manager default lock file version is 2.0.0, but found 1.0.0 in /data/build/esp32-s3-box-3-05ad68/dependencies.lock. Recreating lock file with the current version.
Manifest files have changed, solving dependencies.
.....NOTICE: Updating lock file at /data/build/esp32-s3-box-3-05ad68/dependencies.lock
Processing 1 dependencies:
[1/1] idf (5.1.5)
-- Configuring incomplete, errors occurred!
See also "/data/build/esp32-s3-box-3-05ad68/.pioenvs/esp32-s3-box-3-05ad68/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:266 (message):
  Failed to resolve component 'jsmn'.
Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:308 (__build_resolve_and_add_req)
  /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:603 (__build_expand_requirements)
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:604 (idf_build_process)
  CMakeLists.txt:3 (project)
```
Should I open another issue for this?

**Comment by ssieb** [comment]
That's a completely different issue that has been filed a few times already.  You have to set an earlier idf version.  There's a pending fix to the online package if you're using that.

**Comment by sca075** [comment]
@ssieb thanks I did had this issue with the esphome.voice-asssistant..  
```
substitutions:
  name: esp32-s3-box-3-05ad68
  friendly_name: ESP32 S3 Box 3 05ad68

packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
```
and it happens with the last two releases of  ESPHome builders in HA, it looks I couldn't update the device since last November because of this and I'm sorry but I don't get from what side the lock is raised as you guys are not writing I guess this firmware.

It isn't important for me but.. just to let you guys know about that.. really appreciate your work and clarifications.. please relax a little for the coming days ;) I'm sure it will be fixed later on.
