### ISSUE TITLE
assert failed: sntp_servermode_dhcp sntp.c:770 (Required to lock TCPIP core functionality!)

### ISSUE THREAD

**Issue by bitflippersanonymous** [esphome/issues#6591]
### The problem

Attempting to add support for seeed_xiao_esp32c6.
I fixed a few compilation and library errors, and the upload works, but it crashes in setup. 
See diff.txt for code changes.

Is there a better way to get a full stack trace?

Something is failing this check:  LWIP_ASSERT_CORE_LOCKED
https://github.com/espressif/esp-idf/blob/master/components/lwip/port/include/lwipopts.h

[02:06:40]------------------------------------------
[02:06:40]Software Info:
[02:06:40]------------------------------------------
[02:06:40]  Compile Date/Time : Dec 22 2024 01:32:05
[02:06:40]  ESP-IDF Version   : v5.3.2-174-g083aad99cf-dirty
[02:06:40]  Arduino Version   : 3.1.0
[02:06:40]------------------------------------------
[02:06:40]Board Info:
[02:06:40]------------------------------------------
[02:06:40]  Arduino Board     : Seeed Studio XIAO ESP32C6
[02:06:40]  Arduino Variant   : XIAO_ESP32C6

[02:06:40]============ Before Setup End ============
[02:06:40][   321][V][esp32-hal-uart.c:421] uartBegin(): UART0 baud(115200) Mode(800001c) rxPin(17) txPin(16)
[02:06:40][   321][V][esp32-hal-uart.c:510] uartBegin(): UART0 not installed. Starting installation
[02:06:40][   322][V][esp32-hal-uart.c:575] uartBegin(): UART0 initialization done.
[02:06:40][   438][V][NetworkEvents.cpp:113] _checkForEvent(): Network Event: 101 - WIFI_READY
[02:06:40][   490][V][STA.cpp:186] _onStaEvent(): STA Started
[02:06:40][   490][V][NetworkEvents.cpp:113] _checkForEvent(): Network Event: 110 - STA_START
[02:06:40][   491][V][STA.cpp:110] _onStaArduinoEvent(): Arduino STA Event: 110 - STA_START
[02:06:42][  2787][V][WiFiGeneric.cpp:80] _arduino_event_cb(): SCAN Done: ID: 128, Status: 0, Results: 1
[02:06:42][  2787][V][NetworkEvents.cpp:113] _checkForEvent(): Network Event: 102 - SCAN_DONE
[02:06:42]
[02:06:42]**assert failed: sntp_servermode_dhcp /IDF/components/lwip/lwip/src/apps/sntp/sntp.c:770 (Required to lock TCPIP core functionality!)**

### Which version of ESPHome has the issue?

2025.1.0-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Running ESPHome directly

### What platform are you using?

ESP32

### Board

Seeed Studio XIAO ESP32c6

### Component causing the issue

components/wifi/wifi_component_esp32_arduino.cpp ... I think

### YAML Config

```yaml
esphome:
  name: "seeedyarduino"

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: arduino
    platform_version: https://github.com/pioarduino/platform-espressif32

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "Yh0WgEsy+jl/WN9LYP29hVXhdYgqlfzT3hHAkYEogZI="

ota:
  - platform: esphome
    password: "ddd13e9043bd4d6dac6c6ac778275c90"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
  ssid: "Foo Fallback Hotspot"
  password: "UcWHCoypa4vt"

#captive_portal:

# GPIO configuration for the LED
output:
  - platform: gpio
    pin: GPIO15
    id: led_output

# Light component to control the LED
light:
  - platform: binary
    output: led_output
    name: "ESP32-C6 LED"
    id: blink_led

# Automation to blink the LED
interval:
  - interval: 1s
    then:
      - light.toggle: blink_led
```

### Anything in the logs that might be useful for us?

```txt
A similar esp-idf project works:
esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf
    platform_version: https://github.com/bitflippersanonymous/platform-espressif32
```

### Additional information

[diff.txt](https://github.com/user-attachments/files/18220566/diff.txt)
