### ISSUE TITLE
esp32-c6-devkitm-1 board not recognized in ESPHome 2024.12.2

### ISSUE THREAD

**Issue by jaydeethree** [esphome/issues#6593]
### The problem

I just started upgrading my ESPHome setup to the 2024.12.x versions, but builds are failing for my ESP32-C6 boards because their board type (esp32-c6-devkitm-1) is not recognized. I have confirmed that this board type exists in the platformio fork:

https://github.com/pioarduino/platform-espressif32/blob/main/boards/esp32-c6-devkitm-1.json

I also tried cleaning my build files but that did not help.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.5

### What platform are you using?

ESP32

### Board

esp32-c6-devkitm-1

### YAML Config

```yaml
esphome:
  name: test-01
  friendly_name: test-01

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

uart:
  rx_pin: GPIO4
  tx_pin: GPIO5
  baud_rate: 9600

sensor:
  - platform: senseair
    co2:
      name: "Carbon Dioxide"
    update_interval: 60s
    id: senseair_s8
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/co2-sensor-02.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing test-01 (board: esp32-c6-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
UnknownBoard: Unknown board ID 'esp32-c6-devkitm-1'
```
