### ISSUE TITLE
Cannot set expire_after on template binary sensor

### ISSUE THREAD

**Issue by brandond** [esphome/issues#66]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip + virtualenv

**ESP (ESP32/ESP8266, Board/Sonoff):**
esp01_1m

**Affected component:**
Template binary sensor

**Description of problem:**

Error during compile reporting that expire_after is an invalid option for this platform.

**Problem-relevant YAML-configuration entries:**
```yaml
binary_sensor:
  - platform: template
    id: motion
    name: "PIR00 Motion Sensor"
    filters: []
    expire_after:
    device_class: motion
    lambda: "return {};"
```

**Traceback (if applicable):**
```
  [expire_after] is an invalid option for [binary_sensor.template].
```
