### ISSUE TITLE
Error and fail with  "Take Control" over newly added device

### ISSUE THREAD

**Issue by catdogmaus** [esphome/issues#6605]
### The problem

When attempting to "Take Control" over newly added device I get error:

```INFO Reading configuration /config/esphome/esphome-web-469370.yaml...
Failed config

wifi: [source /config/esphome/esphome-web-469370.yaml:22]
  
  Please specify at least an SSID or an Access Point to create.
  domain: .local
  reboot_timeout: 15min
  power_save_mode: LIGHT
  fast_connect: False
  enable_btm: False
  enable_rrm: False
  passive_scan: False
  enable_on_boot: True
  networks: []
  use_address: esphome-web-469370.local
```

I have this with several ESP32-D and ESP32 devices I did attempted to add to HA ESPHome dashboard.
As workaround - when I open yaml created after that error and add manually 

`wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password`

I am able to install it and proceed with actual setup.
I have latest version at moment 2024.12.2 installed

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.5

### What platform are you using?

ESP32-IDF

### Board

ESP-wroom-32, ESP32-wroom-D

### YAML Config

```yaml
esphome:
  name: esphome-web-469370
  friendly_name: Moretti
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
```

### Anything in the logs that might be useful for us?

```txt
2024-12-25 14:43:47,922 INFO Running command 'esphome --dashboard run /config/esphome/esphome-web-469370.yaml --device OTA'
2024-12-25 14:43:49,215 INFO 304 GET /devices (0.0.0.0) 7.80ms
2024-12-25 14:43:50,141 INFO Process exited with return code 2
```
