### ISSUE TITLE
HBridge restore mode does not work

### ISSUE THREAD

**Issue by felipecrs** [esphome/issues#6608]
### The problem

I am trying to convert my breaker to use the new hbridge component:

- https://devices.esphome.io/devices/Tomzn-TOB9-VAP

But `restore_mode` doesn't work. Is this a known issue? There's nothing in documentation about it.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

pip

### What platform are you using?

BK72XX

### Board

cbu

### Component causing the issue

hbridge

### YAML Config

```yaml
switch:
  - platform: hbridge
    id: hbridge0
    on_pin: GPIO24
    off_pin: GPIO26
    pulse_length: 60ms
    wait_time: 30ms
    restore_mode: ALWAYS_OFF
```

**Comment by felipecrs** [comment]
@dwmw2, since you implemented the H-Bridge component (https://github.com/esphome/esphome/pull/7421), maybe you'd be the best one to answer this.

**Comment by felipecrs** [comment]
My workaround:

```yaml
esphome:
  project:
    name: TOMZN.TOB9-VAP
    version: v1
  on_boot: 
    priority: 900
    then:
      switch.turn_off: hbridge0
```
