### ISSUE TITLE
dim_relative with esp32_rmt

### ISSUE THREAD

**Issue by mathisloge** [esphome/issues#6612]
### The problem

I want to set a dim_relative action for  a esp32_rmt_led_strip. I've tested it with an lvgl light and for that one the light slowly turns on. However, with the following light it doesn't work. It just stays off until the transition length has passed. After that it just turns on to the max value.

(I've also tested with the latest dev branch) 

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32-s3-devkitc-1

### Component causing the issue

esp32_rmt_led_strip

### YAML Config

```yaml
esphome:
  name: "repro"
  friendly_name: "Repro"
  name_add_mac_suffix: true
  min_version: 2024.12.2
  platformio_options:
    board_build.flash_mode: dio
    
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    version: "5.3.1"
    platform_version: 6.9.0

logger:
  level: DEBUG

wifi:
  ssid: "photobox"
  password: "photobox-matnel"

web_server:
  port: 80

ota:
  - platform: esphome

api:
  on_client_connected:
    - logger.log: "Starting DIM EFFECT"
    - light.dim_relative:
        id: daylight
        relative_brightness: 100%
        transition_length: 60s
        brightness_limits:
          min_brightness: 0%
          max_brightness: 100%
          limit_mode: CLAMP

light:
  - platform: esp32_rmt_led_strip
    id: daylight
    rgb_order: GRB
    pin: GPIO43
    num_leds: 24
    chipset: ws2812
    name: "Light"
```

### Anything in the logs that might be useful for us?

```txt
You will see 
[10:01:12][D][main:171]: Starting DIM EFFECT
[10:01:12][D][light:036]: 'Light' Setting:
[10:01:12][D][light:047]:   State: ON
[10:01:12][D][light:051]:   Brightness: 100%
[10:01:12][D][light:085]:   Transition length: 60.0s

But then nothing happens until the 60s have passed
```
