### ISSUE TITLE
Display issue after 2024.10 with qspi_dbi (Lilygo T4 S3)

### ISSUE THREAD

**Issue by pixelwave** [esphome/issues#6615]
### The problem

I am using the provided code snipped from ESPHome for the Lilygo T4 S3.

From ESPHome [Quad SPI Displays Lilygo T4-S3](https://esphome.io/components/display/qspi_dbi.html) :

```
# Lilygo T4 S3
substitutions:
  comment: "Lilygo T4-S3 Sandbox"
  device_name: lilygo-t4-s3
  friendly_name: Lilygo T4-S3
  # Variables

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    # Required to achieve sufficient PSRAM bandwidth
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_ESPTOOLPY_FLASHSIZE_16MB: y # fix warning about 2mb found

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
  - platform: esphome
    password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lilygo-T4-S3 Fallback Hotspot"
    password: "..."


# Lilygo T4 S3 Configuration
spi:
  id: quad_spi
  type: quad
  clk_pin: 15
  data_pins: [14, 10, 16, 12]

i2c:
  sda: 6
  scl: 7

touchscreen:
  - platform: cst226
    id: my_touchscreen
    interrupt_pin: 8
    reset_pin: 17

font:
  - file: "gfonts://Roboto"
    id: font_std
    size: 40
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/\\[]|&@#'"
  - file: "gfonts://Roboto@700"
    id: font_title
    size: 40
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/\\[]|&@#'"

display:
  - platform: qspi_dbi
    model: RM690B0
    data_rate: 80MHz
    spi_mode: mode0
    dimensions:
      width: 450
      height: 600
      offset_width: 16
    color_order: rgb
    invert_colors: false
    brightness: 255
    cs_pin: 11
    reset_pin: 13
    enable_pin: 9
    #update_interval: never
    auto_clear_enabled: false
    # Define Pages
    pages:
      - id: page_1
        lambda: |-
          it.print(it.get_width()/2, it.get_height()/2-20, id(font_title), TextAlign::CENTER, "PAGE 1");
          it.print(it.get_width()/2, it.get_height()/2+20, id(font_std), TextAlign::CENTER, "23%");
      - id: page_2
        lambda: |-
          it.print(it.get_width()/2, it.get_height()/2-20, id(font_title), TextAlign::CENTER, "PAGE 2");
          it.print(it.get_width()/2, it.get_height()/2+20, id(font_std), TextAlign::CENTER, "100%");

psram:
  mode: octal
  speed: 80MHz
# ---

captive_portal:

# Define Touch Areas
binary_sensor:
  - platform: touchscreen
    name: BTN_1
    x_min: 0
    x_max: 450
    y_min: 0
    y_max: 300
    page_id: page_1
    on_press:
      - logger.log: "BTN_1 touched."
      - display.page.show: page_2
  - platform: touchscreen
    name: BTN_2
    x_min: 0
    x_max: 450
    y_min: 300
    y_max: 600
    page_id: page_2
    on_press:
      - logger.log: "BTN_2 touched."
      - display.page.show: page_1
```

But the Display gets corrupted when it updates / I change pages.

https://github.com/user-attachments/assets/1f72f252-033d-41b9-89b3-964a72d7a7f3

The only solution is to add:

```
external_components:
  - source: github://esphome/esphome@2024.10
    components: [qspi_dbi]
```

### Which version of ESPHome has the issue?

2024.12.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32
