### ISSUE TITLE
Touchpad sleep and measurement settings not working

### ISSUE THREAD

**Issue by IndyJoeA** [esphome/issues#6617]
### The problem

The esp32_touch configuration variables **sleep_duration** and **measurement_duration** seem to not be working in the latest version of ESPHome. This is on a project where they were utilized correctly before updating. I'm thinking it has to do with the upgrade to ESP-IDF 5 in this latest version. During compilation, I receive the following message:

![image](https://github.com/user-attachments/assets/05a9f6cd-a972-4bde-a9d6-b57d5c7c2f24)

Here's a screenshot of my data coming from this project, you can see that before the upgrade the data was smoothed out since these settings were working, but after the upgrade the data is jumping around:

![image](https://github.com/user-attachments/assets/67644a59-ee0c-4972-97fa-66d63d82f0aa)

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Component causing the issue

esp32_touch

### YAML Config

```yaml
esphome:
  name: tank-monitor
  friendly_name: Tank Monitor

esp32:
  board: node32s
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"

ota:
  - platform: esphome
    password: "redacted"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tank-Monitor Fallback Hotspot"
    password: "redacted"

captive_portal:
    
esp32_touch:
  setup_mode: false
  sleep_duration: 163840us
  measurement_duration: 3072us
  iir_filter: 2000ms

binary_sensor:
  - platform: esp32_touch
    id: touch_pin12
    pin: GPIO12
    threshold: 0

sensor:
  - platform: template
    name: "Tank Level"
    id: tank_level_pct
    unit_of_measurement: "%"
    lambda: return id(touch_pin12).get_value();
    filters:
      - clamp:
         min_value: 141
         max_value: 226
         ignore_out_of_range: false
      - calibrate_linear:
         method: least_squares
         datapoints:
           - 141 -> 100
           - 226 -> 0
      - sliding_window_moving_average: 
         window_size: 10
         send_every: 10     
    update_interval: 4s

udp:
  update_interval: 5s
  port: 18511
  addresses: ["192.168.50.243"]
  sensors:
    - tank_level_pct
```
