### ISSUE TITLE
[web_server] Sorting puts un-configured entities first

### ISSUE THREAD

**Issue by clydebarrow** [esphome/issues#6622]
### The problem

The web server component allows a sorting priority to be set on a per-entity basis, and the docs say:

> You can set a sorting_weight on each entity. Smaller numbers will be displayed first, defaults to 50

However, any entity that does not have a `web_server` key in its config gets displayed before any that do, which is unexpected. The default of 50 is applied only if there is a `web_server` key with no `sorting_weight` key.

### Which version of ESPHome has the issue?

2025.1.0-dev

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

Any

### Component causing the issue

web_server

### YAML Config

```yaml
esphome:
  platformio_options:
    board_build.flash_mode: dio
  name: sorting

esp32:
  board: esp32-s3-devkitc-1

wifi:
  networks:
   - ssid: !secret wifi_ssid
     password: !secret wifi_password

web_server:
  version: 3

logger:

sensor:
  - platform: template
    name: "Should come after explicitly sorted"
    lambda: return 1.0;
  - platform: template
    name: "Should be shown first"
    lambda: return 2.0;
    web_server:
      sorting_weight: 10
```

### Additional information

<img width="699" alt="Screenshot 2024-12-31 at 2 23 08 PM" src="https://github.com/user-attachments/assets/be896568-da62-47a6-9df8-013136651596" />
