### ISSUE TITLE
#warning "legacy pcnt driver is deprecated"

### ISSUE THREAD

**Issue by nliaudat** [esphome/issues#6623]
### The problem

#warning "legacy pcnt driver is deprecated, please migrate to use driver/pulse_cnt.h"

with latest esphome version (framework-espidf @ 3.50105.0 (5.1.5))

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Component causing the issue

esp32-devkit-4

### YAML Config

```yaml
sensor:

  - platform: pulse_counter
    pin: GPIO32
    # count_mode: rising_edge 
    use_pcnt: true
    internal_filter: 1us
    name: "Pulse Meter 2"
    total:
        name: "total pulse_meter_2"
    id : ${id_prefix}pulse_meter_2

  - platform: pulse_meter
    pin: GPIO33
    name: "pulse_meter_1"
    internal_filter: 1us
    internal_filter_mode: EDGE  
    # timeout: 10s
    total:
        name: "total pulse_meter_1"
    id : ${id_prefix}pulse_meter_1
```
