### ISSUE TITLE
Using "bg_image_src" for button (LVGL)

### ISSUE THREAD

**Issue by pixelwave** [esphome/issues#6624]
### The problem

Is use ESPHome with LVGL and I am trying to have a button with a background image. 

Expected outcome is that the button shows the image but it stays blue with the label "#<"?

My code:

```
lvgl:
#...
- button:
    x: 20
    y: 20
    width: 195
    height: 195
    id: btn_high
    bg_image_src: img_btn_high


image:
  - file: "btn_high.png"
    id: img_btn_high
    type: RGB565#
    resize: 195x195
```

### Which version of ESPHome has the issue?

2024.12.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32
