### ISSUE TITLE
Frequent reboots exception:9 flag:2 (Exception) epc1:0xeba85d94 epc2:0x00000000 epc3:0x00000000 excvaddr:0

### ISSUE THREAD

**Issue by AbianTang** [esphome/issues#6627]
### The problem

2024.12.2|Flash: 4096kB Speed:40MHz Mode:DOUT|Chip: 0x00fc0835|SDK: 2.2.2-dev(38a443e)|Core: 3.1.2|Boot: 31|Mode: 1|CPU: 80|Flash: 0x001660c4|Reset: Exception|Fatal exception:9 flag:2 (Exception) epc1:0xeba85d94 epc2:0x00000000 epc3:0x00000000 excvaddr:0x

<img width="2211" alt="截屏2025-01-02 19 56 03" src="https://github.com/user-attachments/assets/41cf5154-74ce-4197-abed-174a61940cfd" />

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

12.7

### What platform are you using?

ESP8266

### Board

nodemcuv2

### YAML Config

```yaml
captive_portal:



debug:
  update_interval: 5s


# Example configuration entry
light:
  - platform: status_led
    name: "Switch state"
    pin:
     number: D4
     inverted: true

sensor:
  
  


  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    device_class: "signal_strength"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: "signal_strength"

  - platform: bmp280_i2c
    i2c_id: bus2
    temperature:
      name: "BMP280 Temperature"
      oversampling: 16x
    pressure:
      name: "BMP280 Pressure"
    address: 0x76  
    update_interval: 1s  
    
  # DHT11 sensors on bus_a

  - platform: adc
    pin: VCC
    name: "VCC Voltage"
    id: vcc_voltage
    update_interval: 3s

  - platform: sht3xd
    i2c_id: bus2
    temperature:
      name: "Living Room Temperature"
      id: inside_temperature
    humidity:
      name: "Living Room Humidity"
      id: humidityok
    update_interval: 1s
    heater_enabled: False

  - platform: debug
    free:
      name: "Heap Free"
    fragmentation:
      name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
      
      

  - platform: template
    name: "Dew Point Magnus-Tetens"
    unit_of_measurement: "°C"
    id: dew_point
    update_interval: 3s
    lambda: |-
      float temperature = id(inside_temperature).state;
      float humidity = id(humidityok).state;

      // Check if the sensor values are valid
      if (isnan(temperature) || isnan(humidity) || humidity < 0 || humidity > 100) {
        return NAN;  // Handle invalid sensor values
      }

      // Define constants for Magnus-Tetens equation
      const float a = 17.271;
      const float b = 237.7;

      // Calculate alpha
      float alpha = (a * temperature) / (b + temperature) + log(humidity / 100.0);

      // Calculate Dew Point
      return (b * alpha) / (a - alpha);
```

### Anything in the logs that might be useful for us?

```txt
2024.12.2|Flash: 4096kB Speed:40MHz Mode:DOUT|Chip: 0x00fc0835|SDK: 2.2.2-dev(38a443e)|Core: 3.1.2|Boot: 31|Mode: 1|CPU: 80|Flash: 0x001660c4|Reset: Exception|Fatal exception:9 flag:2 (Exception) epc1:0xeba85d94 epc2:0x00000000 epc3:0x00000000 excvaddr:0x
```
