### ISSUE TITLE
Stereo i2s misrophones doesn't work

### ISSUE THREAD

**Issue by boskikak** [esphome/issues#6631]
### The problem

When connecting 2 microphones as left and right channels, sound is not recorded after data channel: stereo. After changing to the left channel, only the left works and vice versa. I use INMP411 microphones connected together by pins SD, WS, SCK.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12

### What platform are you using?

ESP32-IDF

### Board

ESP32-S3

### Component causing the issue

i2s

### YAML Config

```yaml
esphome:
  name: echo
  friendly_name: echo
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"

   
psram:
  mode: octal  # quad for N8R2 and octal for N16R8
  speed: 120MHz


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""
  on_client_connected:
       then:
          - delay: 500ms
          - micro_wake_word.start:
  on_client_disconnected:
        then:
          - voice_assistant.stop: 

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  on_connect:
    - script.execute: start


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:

output:
  - platform: ledc
    pin: GPIO20
    id: buzzer

rtttl:
  output: buzzer
  id: my_rtttl 

button:
  - platform: restart
    name: Reboot

  - platform: template
    name: assist
    on_press: 
      - voice_assistant.stop:
      - delay: 1s   
      - micro_wake_word.stop:
      - delay: 1s  
      - voice_assistant.start_continuous
      - delay: 1s  
      - voice_assistant.stop:
      - delay: 1s   
      - micro_wake_word.start:

micro_wake_word:
  models:
    - model: alexa
  on_wake_word_detected:
    then:
      - voice_assistant.start:
          wake_word: !lambda return wake_word;

i2s_audio:
  - id: i2s_in # For microphone
    i2s_lrclk_pin: GPIO6  #WS 
    i2s_bclk_pin: GPIO7 #SCK

microphone:
  - platform: i2s_audio
    id: va_mic
    adc_type: external
    i2s_din_pin: GPIO4 #SD
    pdm: false
    channel: stereo
    i2s_audio_id: i2s_in
    bits_per_channel: 32bit
    sample_rate: 24000


voice_assistant:
  id: va
  microphone: va_mic
  noise_suppression_level: 3.0
  volume_multiplier: 2.0
  on_listening:
    - rtttl.play: 'two_short:d=4,o=5,b=100:16e6,16e6'
  on_error:
          - micro_wake_word.start:  
  on_end:
        then:
          - wait_until:
              not:
                voice_assistant.is_running:
          - micro_wake_word.start:  

script:
  - id: start
    then:
    - wait_until:
       wifi.connected:
    - logger.log: "polaczono"
    - delay: 1s 
    - voice_assistant.stop:
    - delay: 1s   
    - micro_wake_word.stop:
    - delay: 1s  
    - voice_assistant.start_continuous
    - delay: 1s  
    - voice_assistant.stop:
    - delay: 1s   
    - micro_wake_word.start:
```
