### ISSUE TITLE
EAP-TLS does not work with framework arduino

### ISSUE THREAD

**Issue by Rudd-O** [esphome/issues#6635]
### The problem

Various devices (Freenove ESP32-WROOM and M5Stack Atom) fail when using EAP-TLS and compiled with framework `arduino`, which correctly works when using framework `esp-idf`.

I no longer have logs from my router when the WROOM device was failing, but when the Atom fails, this is what my router says:

```
Fri Jan  3 13:16:43 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-STARTED e8:9f:6d:06:b9:48
Fri Jan  3 13:16:43 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
Fri Jan  3 13:16:43 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-STARTED e8:9f:6d:06:b9:48
Fri Jan  3 13:16:43 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
Fri Jan  3 13:16:44 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-FAILURE2 e8:9f:6d:06:b9:48
Fri Jan  3 13:16:44 2025 daemon.warn hostapd: wlan_cis_2g_ent: STA e8:9f:6d:06:b9:48 IEEE 802.1X: authentication failed - EAP type: 13 (TLS)
Fri Jan  3 13:16:44 2025 daemon.info hostapd: wlan_cis_2g_ent: STA e8:9f:6d:06:b9:48 IEEE 802.1X: Supplicant used different EAP type: 3 (unknown)
Fri Jan  3 13:16:49 2025 daemon.info hostapd: wlan_cis_2g_ent: STA e8:9f:6d:06:b9:48 IEEE 802.11: deauthenticated due to local deauth request
```

Note the device is sending to the supplicant the wrong EAP type.

This should either be fixed, or documented that EAP-TLS simply doesn't work reliably with framework `arduino`

### Which version of ESPHome has the issue?

core-2024.12.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

Irrelevant

### What platform are you using?

ESP32

### Board

M5Stack Atom / Freenove ESP32-WROOM-S

### Component causing the issue

wifi

### YAML Config

```yaml
wifi:
  networks:
  - ssid: !secret wifi_ssid_ent
    eap:
      identity: bluetooth-proxy.dragonfear
      certificate_authority: wi-fi/ca.pem
      certificate: wi-fi/certs/bluetooth-proxy/cert.pem
      key: wi-fi/certs/bluetooth-proxy/key.pem
  - ssid: !secret wifi_recovery_ssid
    password: !secret wifi_recovery_password
```
```


### Anything in the logs that might be useful for us?

```txt
See above.
```
