### ISSUE TITLE
Xiao ESP32C3 Wifi

### ISSUE THREAD

**Issue by puravida13** [esphome/issues#6637]
### The problem

I have multiple ESP32 devices of diferent dev boards and ESP32 types working perfectly in ESPHOME. (Thank You).....But all of a sudden a few days ago, I noticed only my Xiao ESP32C3 devices were unable to connect to wifi.  Returning Auth Expired errors.  I tried going to static IP, tried changing authentication methods, tried changing framework from arduino to esp-idf...(which helped but was unstable and sending random errors upon connection....I tried changing the decibals to 8.5...nothing seems to work....I cant get a stable connection, if any at all, via wifi...I'll attach logs as best I know how.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

Seeed Studio Xiao ESP32C3

### Component causing the issue

Wifi

### YAML Config

```yaml
substitutions:
  name: esphome-web-8640fc
  friendly_name: ESPHome mmWave Kitchen

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ap: {}
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.211
    gateway: 192.168.1.254
    subnet: 255.255.255.0

esp32_ble:
  enable_on_boot: false

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32c3.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

ld2410:
  id: ld2410_radar
  
uart:
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

number:
  - platform: ld2410
    timeout:
..........
```

### Anything in the logs that might be useful for us?

```txt
[17:34:26][W][wifi:653]: Error while connecting to network.
[17:34:26][D][wifi:697]: Retrying with hidden networks...
[17:34:26][I][wifi:313]: WiFi Connecting to 'XXXXXXX'...
[17:34:27][D][sensor:094]: 'Radar Detection Distance': Sending state 165.00000 cm with 0 decimals of accuracy
[17:34:28][W][wifi_esp32:545][arduino_events]: Event: Disconnected ssid='XXXXXX' bssid=[redacted] reason='Auth Expired'
[17:34:28][W][wifi:653]: Error while connecting to network.
```
