### ISSUE TITLE
Pulse Counter incremental meter

### ISSUE THREAD

**Issue by craigueh** [esphome/issues#664]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASS.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

pulse counter

**Description of problem:**
I'm not certain if this should be classed as an issue or feature request so apologies in advance.

The pulse counter counts pulses and displays in pulses/min
This is useful for say a water flow meter to easily display L/min but is no good for tracking actual usage either for metering or in my use case to calculate water flow since previous backwash on a water filter to know when to run the next backwash.

I've tried extrapolating back from pulses/min then divide by 60 to get pulses per second so as to have a finer resolution on actual pulses counted.
This produces a number but trying to use a lambda with a static int to sum all all pulses counted results in wildly varying numbers, none close to the actual expected flow. I tried dividing by 17 (pulses per litre /min) to get the litres /s and sum these up to total daily flow but again the numbers are way off.

I think there should be a separate pulse counter that increments with each actual individual pulse counted since a given time/period. This would be most accurate instead of trying to extrapolate the data from a multiplied pulses/min and back again to pulses/sec etc.

Can this be done?

**Problem-relevant YAML-configuration entries:**
```yaml

sensor:
  - platform: pulse_counter
    id: water_pulse
    pin: D3
    name: "Pulse Counter"
    update_interval: 1s

  - platform: template
    name: "Water Flow Rate"
    id: water_flow_rate
    accuracy_decimals: 1
    unit_of_measurement: "L/min"
    icon: "mdi:water"
    lambda: return (id(water_pulse).state /17)* 1;
    update_interval: 3s
    # meter is 1 pulse per gallon so divide by 17 gives litre/min
  - platform: template
    name: "Water Usage"
    id: water_usage
    accuracy_decimals: 3
    unit_of_measurement: "L"
    icon: "mdi:water"
    lambda: |-
      static int num_executions = 0;
      ESP_LOGD("main", "I am at execution number %d", num_executions);
      if (id(water_pulse).state) {
        num_executions += 1;
      }
      return num_executions /17;
    # in Homeassistant this is divided by 60 to get litres per second and then statistics function is used to record total daily usage. 
    update_interval: 1s


I also tried this but it won't compile:

sensor:
  - platform: pulse_counter
    id: water_pulse
    pin: D3
    name: "Pulse Counter"
    update_interval: 3s
  - platform: template
    name: "Total pulses"
    lambda: |-
      static float total_value = 0.0;
      # 0.05 because of update_interval 3s
      total_value += id(water_pulse).value * 0.05;
      return total_value;
  - platform: template
    name: "Water Flow Rate"
    id: water_flow_rate
    accuracy_decimals: 1
    unit_of_measurement: "L/min"
    icon: "mdi:water"
    lambda: return (id(water_pulse).state /17);
    update_interval: 3s
    # meter is 1 pulse per gallon so divide by 17 gives litre/min

^
src/main.cpp: In lambda function:
src/main.cpp:179:35: error: 'class esphome::pulse_counter::PulseCounterSensor' has no member named 'value'
total_value += water_pulse->value * 0.05;
^
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
