### ISSUE TITLE
use ld2420 Restart at irregular intervals Fatal exception:4 flag:3 (Software Watchdog) epc1:0x4026f762 epc2:0x00000000 epc3:0x0000

### ISSUE THREAD

**Issue by AbianTang** [esphome/issues#6641]
### The problem

use ld2420 Restart at irregular intervals Fatal exception:4 flag:3 (Software Watchdog) epc1:0x4026f762 epc2:0x00000000 epc3:0x0000,
<img width="2174" alt="截屏2025-01-04 14 40 42" src="https://github.com/user-attachments/assets/8a60ae7f-eab1-4d37-baf3-c8c7d8f125c3" />
<img width="2229" alt="截屏2025-01-04 14 40 51" src="https://github.com/user-attachments/assets/39c929c9-500a-44c0-b1b0-9fc51bcc5148" />
<img width="227" alt="截屏2025-01-04 14 51 01" src="https://github.com/user-attachments/assets/1629a07f-18b9-4962-9b70-fd6d753cfe0e" />

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.7

### What platform are you using?

ESP8266

### Board

1

### Component causing the issue

ld2420

### YAML Config

```yaml
captive_portal:



i2c:
- id: bus1
  sda: D5
  scl: D6
  scan: True
  frequency: 400kHz






light:
  - platform: status_led
    name: "Switch state"
    pin:
     number: D4
     inverted: true


ld2410:

sensor:  

  - platform: bmp280_i2c
    i2c_id: bus1
    temperature:
      name: "BMP280 Temperature"
      oversampling: 16x
      accuracy_decimals: 4
    pressure:
      name: "BMP280 Pressure"
      accuracy_decimals: 4
    address: 0x76
    update_interval: 15s 
    

  - platform: aht10
    variant: AHT20
    i2c_id: bus1
    temperature:
      name: "Living Room Temperature"
      id: temperature1
      accuracy_decimals: 4
    humidity:
      name: "Living Room Humidity"
      id: humidity1
      accuracy_decimals: 4
    update_interval: 15s
    

  - platform: template
    name: "Dew Point Magnus-Tetens"
    unit_of_measurement: "°C"
    id: dew_point_Magnus_Tetens
    update_interval: 16s
    lambda: |-
      float temperature = id(temperature1).state;
      float humidity = id(humidity1).state;

      // Check if the sensor values are valid
      if (isnan(temperature) || isnan(humidity) || humidity < 0 || humidity > 100) {
        return NAN;  // Handle invalid sensor values
      }

      // Define constants for Magnus-Tetens equation
      const float a = 17.271;
      const float b = 237.7;

      // Calculate alpha
      float alpha = (a * temperature) / (b + temperature) + log(humidity / 100.0);

      // Calculate Dew Point
      return (b * alpha) / (a - alpha);  

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    device_class: "signal_strength"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: "signal_strength"

  - platform: adc
    pin: vcc
    name: "VCC Voltage"
    id: vcc_voltage
    update_interval: 180s    

  - platform: uptime
    name: Uptime
    type: seconds
    id: sys_uptime
    update_interval: 60s

  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy        
  - platform: debug
    free:
      name: "Heap Free"
    fragmentation:
      name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
   

switch:
  - platform: gpio
    pin: D1
    name: "Living Room Open window"
    device_class: switch
    id: relay1
    interlock: [relay2]
    on_turn_on:
    - delay: 14s
    - switch.turn_off: relay1
    - logger.log: "Switch Turned On!"
    

  - platform: gpio
    pin: D2
    name: "Living Room Closs window"
    device_class: switch  
    id: relay2
    interlock: [relay1]
    on_turn_on:
    - delay: 15s
    - switch.turn_off: relay2
    - logger.log: "Switch Turned Off!"


  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"    


binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: D3
    name: gpio out pin presence
    device_class: presence 

debug:
  update_interval: 1s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address

  - platform: ld2410
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"   

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"    

      


uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1         
  



select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level
```

### Anything in the logs that might be useful for us?

```txt
2024.12.2|Flash: 4096kB Speed:40MHz Mode:DOUT|Chip: 0x00a7e3df|SDK: 2.2.2-dev(38a443e)|Core: 3.1.2|Boot: 31|Mode: 1|CPU: 80|Flash: 0x001660c4|Reset: Software Watchdog|Fatal exception:4 flag:3 (Software Watchdog) epc1:0x4026f762 epc2:0x00000000 epc3:0x0000
```

**Comment by smashedr** [comment]
At a glance, you are using the wrong baud rate. The documentation says `115200`. Try update your `uart:` to this:

```yaml
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200
```

Also, I believe GPIO01/03 are used for serial logging. You might try disabling serial logging:

```yaml
logger:
  baud_rate: 0
```

The alternative is to use GPIO16/17.

I have had no issues with this sensor and this setup and I am using a couple of them.

Package: https://github.com/smashedr/esphome-configs?tab=readme-ov-file#ld2420
Source: https://github.com/smashedr/esphome-configs/blob/master/include/ld2420/ld2420.yaml
Config: https://github.com/smashedr/esphome-configs/blob/master/esptest48.yaml
