### ISSUE TITLE
ESPHome Modbus Controller - allow_duplicate_commands - slows modbus flow

### ISSUE THREAD

**Issue by PeterPolacek** [esphome/issues#6644]
### The problem

Using allow_duplicate_commands slow modbus commands flow.

I have multiple modbus devices with specific commands. 
Every device has 4 channels to dimming light. When i want to dim every light in specific device i need to send 4 commands with same head but different body. That shows ,,Duplicate modbus command found,, warning and sends only first of these commands. When i use allow_duplicate_commands feature, everything seems to be fine and esp sends 4 commands, but it took some strange time for it. So every command is sent with some delay (maybe around 200-400ms ?)
Is some way for fix this issue?

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.3

### What platform are you using?

ESP32

### YAML Config

```yaml
- id: dimmer_1
    address: 0x4
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 60s
    command_throttle: 50ms
    offline_skip_updates: 10
    allow_duplicate_commands: true

output:
  - platform: modbus_controller
    modbus_controller_id: dimmer_1
    id: Modbus_dimmer_1_1
    use_write_multiple: true
    address: 8
    value_type: U_QWORD_R
    write_lambda: |-
      uint16_t value = x * 255;
      payload.push_back(0x0003);
      payload.push_back(0x0001);
      payload.push_back(value);
      payload.push_back(0x0000);
      return x;

  - platform: modbus_controller
    modbus_controller_id: dimmer_1
    id: Modbus_dimmer_1_2
    use_write_multiple: true
    address: 8
    value_type: U_QWORD_R
    write_lambda: |-
      uint16_t value = x * 255;
      payload.push_back(0x0003);
      payload.push_back(0x0002);
      payload.push_back(value);
      payload.push_back(0x0000);
      return x;

  - platform: modbus_controller
    modbus_controller_id: dimmer_1
    id: Modbus_dimmer_1_3
    use_write_multiple: true
    address: 8
    value_type: U_QWORD_R
    write_lambda: |-
      uint16_t value = x * 255;
      payload.push_back(0x0003);
      payload.push_back(0x0003);
      payload.push_back(value);
      payload.push_back(0x0000);
      return x;

  - platform: modbus_controller
    modbus_controller_id: dimmer_1
    id: Modbus_dimmer_1_4
    use_write_multiple: true
    address: 8
    value_type: U_QWORD_R
    write_lambda: |-
      uint16_t value = x * 255;
      payload.push_back(0x0003);
      payload.push_back(0x0004);
      payload.push_back(value);
      payload.push_back(0x0000);
      return x;
```
