### ISSUE TITLE
rp2040 - UART debug not working

### ISSUE THREAD

**Issue by jraynes** [esphome/issues#6645]
### The problem

I cannot get UART debug working with my rp2040 running ESPhome.

I believe the YAML below should result in every single UART character received or sent to the debug log. I should be able to see those debug messages live when viewing logs via the esphome console.  But when I connect the board to a FT232 adapter plugged into my laptop and send some text in PuTTY I get nothing in debug:

<img width="523" alt="image" src="https://github.com/user-attachments/assets/e6ac56d0-957b-4289-846b-53b9d114dd80" />

It looks like the board is receiving the ASCII I'm sending it because its being echoed back to me. But why is nothing being logged?

### Which version of ESPHome has the issue?

2024.12

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12

### What platform are you using?

RP2040

### Board

Pi Pico W

### Component causing the issue

uart/logger

### YAML Config

```yaml
logger:
  level: VERY_VERBOSE
  baud_rate: 0
uart:
  baud_rate: 9600
  tx_pin: GPIO12
  rx_pin: GPIO13
  debug:
    direction: BOTH
    dummy_receiver: true
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes,':');
```
