### ISSUE TITLE
display: Could not allocate buffer for display!

### ISSUE THREAD

**Issue by janick** [esphome/issues#6646]
### The problem

Trying to use ESPHome on a [Langbon L8](https://openhasp.haswitchplate.com/0.6/devices/lanbon-l8/#lcd-configuration) device but declaring a corresponding ```display``` causes the device to fail to boot because it can't allocate the display buffer.

See discussion here: https://community.home-assistant.io/t/interesting-touch-switch-lanbon-l8/264112/145?u=janick

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.0

### What platform are you using?

ESP32

### Board

Langbon L8

### YAML Config

```yaml
spi:
  clk_pin: GPIO19
  mosi_pin: GPIO23
  miso_pin: GPIO25

i2c:
  sda: GPIO4
  scl: GPIO0

output:
  - platform: ledc
    pin: GPIO26
    id: moodRed
  - platform: ledc
    pin: GPIO32
    id: moodGreen
  - platform: ledc
    pin: GPIO33
    id: moodBlue
  - platform: gpio
    pin: GPIO12
    id: relay_1
  - platform: gpio
    pin: GPIO14
    id: relay_2
  - platform: gpio
    pin: GPIO27
    id: relay_3

light:
  - platform: rgb
    name: "Mood Light"
    red: moodRed
    green: moodGreen
    blue: moodBlue

display:
  - id: langbon_L8
    platform: st7789v
    model: Custom
    height: 320
    width: 240
    offset_height: 0
    offset_width: 0
    backlight_pin: GPIO5
    cs_pin: GPIO22
    dc_pin: GPIO21
    reset_pin: GPIO18
    auto_clear_enabled: false
    update_interval: never
```

### Anything in the logs that might be useful for us?

```txt
Rebooting...
[I][logger:171]: Log initialized
[C][safe_mode:079]: There have been 2 suspected unsuccessful boot attempts
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[D][spi:035]: Setting up SPI bus...
[I][i2c.arduino:218]: Performing I2C bus recovery
[C][light:021]: Setting up light 'Mood Light'...
[D][light:036]: 'Mood Light' Setting:
[D][light:041]:   Color mode: RGB
[D][light:085]:   Transition length: 1.0s
[C][st7789v:011]: Setting up SPI ST7789V...
[D][spi_device:362]: mode 0, data_rate 20000kHz
[E][display:017]: Could not allocate buffer for display!
```

### Additional information

Platform works fine with openHASP.
