### ISSUE TITLE
Modbus entity id prefix

### ISSUE THREAD

**Issue by avilleret** [esphome/issues#6649]
### The problem

I have several devices running the same code (modbus controller for ventilation unit).
Only the `esphome` component `name` and `friendly_name' differ across the devices.
When I set a `friendly_name` it appears in the entity name but not in the entity id:
![2025-01-05-222355_550x81_scrot](https://github.com/user-attachments/assets/9769287e-9811-4cbe-9367-a46ab70684e0)

I expect the friendly name to appear also in the entity id to be able to differentiate them. 
For now it is quite difficult to know if `sensor.air_pressure_3` belongs to `Inspirair Attic` or `Inspirair Basement` or anyone else.
Also I don't know if the numbering will be consistent upon reboot.
Is there a way to automatically add the device friendly name as a prefix to entity ID ?

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2025.1.0

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

modbus

### YAML Config

```yaml
esphome:
  name: inspirair-test
  friendly_name: Test Name

esp32:
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  networks:
  - ssid: !secret ssid1
    password: !secret password1

captive_portal:

uart:
  baud_rate: 9600
  tx_pin: GPIO17
  rx_pin: GPIO16

modbus:
  id: modbus1

modbus_controller:
  - id: modbus_device
    ## the Modbus device addr
    address: 0x2
    modbus_id: modbus1
    setup_priority: -10

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    id: output_air_temperature
    register_type: holding
    address: 0x0161
    unit_of_measurement: "°C"
    lambda: return x * 0.01;
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: Air Pressure
    register_type: holding
    address: 0x0166
    unit_of_measurement: "Pa"
    lambda: return x * 0.1;
    accuracy_decimals: 2
```

### Additional information

Please note that the `output_air_temperature` entity doesn't appear in the Home Assistant Entities list
