### ISSUE TITLE
Binary Sensor in Remote Receiver not working properly for MagiQuest

### ISSUE THREAD

**Issue by lmdrumm** [esphome/issues#6650]
### The problem

The Binary sensor functionality for MagiQuest in Remote Receiver is not properly filtering the magnitude when an optional magnitude is included. It still properly filters to only trigger for the correct wand ID, but does so for all magnitude values despite having a specific magnitude in the code. 

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.0

### What platform are you using?

ESP8266

### Board

nodemcu

### YAML Config

```yaml
# suitable for esp8266 based devices
substitutions:
  name: wand-sensor-1
  friendly_name: wand-sensor-1
  wand_retrigger_timeout: 2s

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  # You can set this to true if you want to share exact config (therefore also name field) among many.
  # Unique MAC will be added to name.
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
  libraries:
   - Wire
   - IRremote

esp8266:
  board: nodemcuv2

remote_receiver:
  pin:
    # This has to match the correct GPIO pin for your device
    # GPIO2 corresponds to pin D4 on a Wemos D1 mini
    # https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
    # If you're using a different device, keep in mind that some pins have specific purposes and you'll need
    # to do some trialing and reading before you'll know for sure
    number: GPIO14
    # Depending on your device, if this is not correct, you'll get a warning in
    # the logs on boot suggesting you change it
    inverted: True
  dump: magiquest

binary_sensor:
- platform: remote_receiver
  name: "Child 1 Wand"
  magiquest:
    wand_id: !secret wand_child1_address
    magnitude: 0x0C08
  filters:
  - delayed_off: ${wand_retrigger_timeout}

# Repeat this for as many wands as you have
# - platform: remote_receiver
#   name: "Child 2 Wand"
#   magiquest:
#     wand_id: !secret wand_2_address
#   filters:
#   - delayed_off: ${wand_retrigger_timeout}

# Enable logging
logger:

# Allow Over-The-Air updates
ota:
  platform: esphome

# Enable Home Assistant API communication
api:
  encryption:
    key: !secret home_assistant_api_key

wifi:
  # only 2.4Ghz wifi networks work!! No 5Ghz!! Combined should be fine though?
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Edit "domain" to match your own networking setup if you have a local domain at home
  # domain: ".home"
  # This is needed so that the device connects to wifi quickly when you plug it in
  fast_connect: true
  # Without this, there's an unbearable delay after someone waves the wand
  power_save_mode: none

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP
# captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
[23:32:00][D][binary_sensor:036]: 'Child 1 Wand': Sending state ON
[23:32:00][I][remote.magiquest:079]: Received MagiQuest: wand_id=0x028AA9CC, magnitude=0x092B
[23:32:02][D][binary_sensor:036]: 'Child 1 Wand': Sending state OFF
[23:32:02][D][binary_sensor:036]: 'Child 1 Wand': Sending state ON
[23:32:02][I][remote.magiquest:079]: Received MagiQuest: wand_id=0x028AA9CC, magnitude=0x0804
[23:32:04][I][remote.magiquest:079]: Received MagiQuest: wand_id=0x028AA9CC, magnitude=0x080C
[23:32:06][I][remote.magiquest:079]: Received MagiQuest: wand_id=0x028AA9CC, magnitude=0x0808
[23:32:07][I][remote.magiquest:079]: Received MagiQuest: wand_id=0x028AA9CC, magnitude=0x080C
[23:32:09][D][binary_sensor:036]: 'Child 1 Wand': Sending state OFF
[23:32:11][D][binary_sensor:036]: 'Child 1 Wand': Sending state ON
[23:32:11][I][remote.magiquest:079]: Received MagiQuest: wand_id=0x028AA9CC, magnitude=0x0C08
[23:32:13][D][binary_sensor:036]: 'Child 1 Wand': Sending state OFF
```
