### ISSUE TITLE
won't connect to wifi after unplugging the power

### ISSUE THREAD

**Issue by ufacek** [esphome/issues#6652]
### The problem

I have this board Wemos D1 Mini Wifi ESP8266 ESP-12F, I set it up, leave it connected via wifi and everything works, as soon as I disconnect it from the power, it won't connect back to wifi.
I've tried everything, even in the settings, but it still won't connect.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.5

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini Wifi ESP8266 ESP-12F

### Component causing the issue

wifi connection

### YAML Config

```yaml
esphome:
  name: rychlost
  friendly_name: rychlost fan

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG
   
# Enable Home Assistant API
api:
  encryption:
    key: "aYIN8Lk7lyNa+XisNKDGnfJ8bvhk+wKLOAFHANF5vMo="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.68.122
    gateway: 192.168.68.1
    subnet: 255.255.255.0
  use_address: 192.168.68.122
  reboot_timeout: 50s
  power_save_mode: none

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "QiHIvvNSDb5G"

captive_portal:

# Example configuration entry
binary_sensor:
  - platform: status
    name: "rychlost fan"

# OneWire bus configuration
one_wire:
  - platform: gpio
    pin: 13  # Replace with your GPIO pin connected to the Dallas sensor

# Dallas Sensor Configuration
sensor:
  - platform: dallas_temp
    address: 0x2ee357851e64ff28  # Adresa senzoru (najdete v logu po prvním spuštění)
    name: "Fan Temperature Sensor"
    accuracy_decimals: 1
    update_interval: 5s

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

# PWM Fan Control via MOSFET
output:
  - platform: esp8266_pwm
    id: fan_pwm
    pin: 14
    frequency: 30000 Hz  # Adjust frequency for your fan's optimal PWM control

fan:
  - platform: speed
    output: fan_pwm
    name: "Fan Speed Control"
    speed_count: 100  # 0-100% speed control
```

### Anything in the logs that might be useful for us?

```txt
Logs test.yaml
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/test.yaml...
INFO Starting log output from 192.168.68.122 using esphome API
WARNING Can't connect to ESPHome API for rychlost @ 192.168.68.122: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.68.122', port=6053))]: [Errno 113] Connect call failed ('192.168.68.122', 6053) (SocketAPIError)
INFO Trying to connect to rychlost @ 192.168.68.122 in the background
```
