### ISSUE TITLE
ESPHome devices keep disconnecting from HA API 

### ISSUE THREAD

**Issue by oulianxian** [esphome/issues#6654]
### The problem

ESPHome devices keep disconnecting from HA API 
![Snipaste_2025-01-07_17-50-48](https://github.com/user-attachments/assets/074897c0-b1c7-4ed3-8762-383e117f2b22)

### Which version of ESPHome has the issue?

2024.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.0

### What platform are you using?

ESP32

### YAML Config

```yaml
substitutions:
  name: hezou-c3-001
  friendly_name: hezou c3 001
  ip: 192.168.31.43

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

ota:
  platform: esphome
  password: !secret ota_password

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret encryption
  on_client_connected:
    - logger.log: "API Client Connected, starting BLE scan."
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - logger.log: "API Client Disconnected, stopping BLE scan."
        - esp32_ble_tracker.stop_scan:

wifi:
  ssid: oulianxian
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.31.1
    subnet: 255.255.255.0
  ap:
    ssid: "Fallback Hotspot"
    password: "qazxsw123"

web_server:
  port: 80
  version: 1

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    continuous: False
    active: True
    interval: 320ms
    window: 300ms

sensor:
  - platform: wifi_signal
    name: "${name} wifi signal"
    update_interval: 60s
  - platform: uptime
    name: "${name} Uptime Sensor"
    update_interval: 60s
  # 光照传感器 GY-30 (BH1750)
  - platform: bh1750
    name: "${name} Light Level"
    address: 0x23  # 默认地址 0x23，如果无效可以尝试 0x5C
    update_interval: 2s
    i2c_id: bus_a
    filters:
      - delta: 2  # 值变化超过 X 时才上报  实验或调试场景1   智能灯光控制2

binary_sensor:
  # 雷达存在传感器 (GPIO10)
  - platform: gpio
    id: radar_presence
    pin: GPIO10
    name: "${name} Radar Presence"
    device_class: occupancy
    filters:
      - delayed_on: 1s  # 延迟 1 秒触发，避免误报
      - delayed_off: 5s  # 延迟 5 秒关闭，确保人体离开后不会立即关闭
  # 人体红外传感器 (GPIO2)
  - platform: gpio
    id: pir_motion
    pin: GPIO2
    name: "${name} PIR Motion"
    device_class: motion
  - platform: status
    name: "${name} Status"
    on_press:
      - logger.log: "Device restarted!"

switch:
  - platform: restart
    name: "${name} Restart"
    id: restart_button

# I2C 配置
i2c:
  sda: GPIO4  # 合宙 ESP32-C3 的 SDA 引脚
  scl: GPIO5  # 合宙 ESP32-C3 的 SCL 引脚
  id: bus_a
  scan: True
  # frequency: 100kHz  # 降低频率以解决通信问题
```
