### ISSUE TITLE
MAC address in logs and in the network are different when using ETHERNET W5500, nmap in homeassistant cannot find the esp32 device because of this

### ISSUE THREAD

**Issue by sermaster2477** [esphome/issues#6658]
### The problem

I have a lot of devices based on esp32 in conjunction with w5500 and disabled wifi.
They are all connected to homeassistant and all behave the same in terms of mac address.
I think that they display the mac address from the wifi module in the log,
and the ethernet module is assigned a mac address calculated from the wifi module but increased.
In connection with this, nmap cannot correctly detect the device on the network, since the mac addresses do not match.
When using the wifi module for communication, no problems arise, devices are automatically detected by nmap.
I see the following picture LOG ESP32 tells me that the MAC address is C4:D8:D5:94:7E:18 and the router that issued the IP address,
reports that my ESP32 device uses the following mac address on the network C4:D8:D5:94:7E:1B why is this happening?
I think that this is automatically implemented inside the W5500 driver library to reduce problems with duplicating MAC addresses in the network.
In the ethernet component, there is no way to set the MAC address manually, like for example the IP address of the w5500 module.
I think that it would be correct to take into account which communication module is used and display the assigned MAC in the Module Log.
If WiFi is not declared, then you need to send the MAC address that is actually used in the network.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

ETHERNET W5500

### YAML Config

```yaml
esphome:
  name: mibc-esp32-prot
  friendly_name: mibc-esp32-prot
  comment: "mibc-esp32-prot"


esp32:
  board: esp32dev
  framework:
    type: arduino




# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "U6+gp0HqRPejMf+XAjp6oJqt7DgcAJWWayeDIQcSFjQ="

ota:
  - platform: esphome
    password: "c45d8acd906fe2991d4d6ffc558440f4"

#wifi:
#  networks:
#  - hidden: true
#    ssid: !secret wifi_ssid
#    password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Mbic32Hp Fallback Hotspot"
#    password: "2kuub8gTKCcg"

#captive_portal:


ethernet:
  type: W5500
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  cs_pin: GPIO15
  interrupt_pin: GPIO0
  reset_pin: GPIO5 



button:                  
  - platform: restart
    name: "Restart"
```

### Anything in the logs that might be useful for us?

```txt
there are no errors, the devices work perfectly. The MAC address is just different in the log and on the network.
```
