### ISSUE TITLE
remote_transmitter rcswitch needs wait_time 0 to be received

### ISSUE THREAD

**Issue by Jojo-1000** [esphome/issues#6662]
### The problem

See also issue #1828 that was closed for inactivity

I wanted to control my 433Mhz remote controlled sockets, and the rc-switch examples work while esphome does not out of the box. I confirmed that the codes are all correct. Adding `wait_time: 0ms` makes it function as expected.

I can confirm the issue still applies, and I include signal traces that show the reason for this. I propose to change the wait_time default to zero and possibly add a warning about this setting. It seems that the previous version sent the SYN at the end which also worked.

### Which version of ESPHome has the issue?

2024.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.3

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

remote_transmitter

### YAML Config

```yaml
esphome:
  name: rfsender
  friendly_name: RFSender

esp8266:
  board: nodemcuv2

remote_transmitter:
  carrier_duty_percent: 100%
  pin:
    number: D8
    mode:
      output: true

button:
  - platform: template
    name: RC blink
    on_press:
      - script.execute: blink_timer
script:
  - id: blink_timer
    mode: restart
    then:
      - remote_transmitter.transmit_rc_switch_type_b:
          repeat:
            times: 5
            wait_time: 0ms # <- remove this to make it stop working
          address: 1
          channel: 1
          state: on
          protocol: 1
      - delay: 1s
      - remote_transmitter.transmit_rc_switch_type_b:
          repeat:
            times: 5
            wait_time: 0ms # <- remove this to make it stop working
          address: 1
          channel: 1
          state: off
          protocol: 1
      - delay: 1s
      - script.execute: blink_timer

# Enable logging
logger:
  level: VERY_VERBOSE
  logs:
    remote_transmitter.esp8266: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "!secret"

ota:
  - platform: esphome
    password: "!secret"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Funksender Fallback Hotspot"
    password: "!secret"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
not working verbose log snippet (the timings themselves are correct):
[00:41:54][VV][remote_base:149]: Sending times=5 wait=25000ms: 350, -10850, 350, -1050, 350, -1050, 350, -1050, 1050, -350, 350, -1050, 1050, -350, 350, -1050, 1050, -350, 350, -1050, 350, -1050, 350, -1050, 1050, -350, 350, -1050, 1050, -350, 350, -1050, 1050, -350, 350, -1050, 1050,
[00:41:54][VV][remote_base:162]:   -350, 350, -1050, 1050, -350, 350, -1050, 1050, -350, 350, -1050, 350, -1050

working verbose log snippet:
[00:58:38][VV][remote_base:149]: Sending times=5 wait=0ms: 350, -10850, 350, -1050, 350, -1050, 350, -1050, 1050, -350, 350, -1050, 1050, -350, 350, -1050, 1050, -350, 350, -1050, 350, -1050, 350, -1050, 1050, -350, 350, -1050, 1050, -350, 350, -1050, 1050, -350, 350, -1050, 1050, -350,
[00:58:39][VV][remote_base:162]:   350, -1050, 1050, -350, 350, -1050, 1050, -350, 350, -1050, 1050, -350
```

### Additional information

Traces on the signal pin:
**Working signal with `wait_time=0ms`:**
![image](https://github.com/user-attachments/assets/6a4b36ef-e187-4308-93c2-58455531d672)
(the U bits are due to insufficient sampling rate but work fine)

**Non-working signal with default `wait_time`:**
![image](https://github.com/user-attachments/assets/a117ad52-bd46-439d-b69d-f6b13969db67)
I don't know the underlying protocol in detail, but the Pulseview protocol decoder seems to detect the wait time as sync. The actual sync is decoded as data and then messes up the entire signal.
