### ISSUE TITLE
`Device Info` and `Reset Reason` always unknown for AtomS3 Lite

### ISSUE THREAD

**Issue by wrfz** [esphome/issues#6663]
### The problem

`Device Info` and `Reset Reason` are always `unknown`

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.1

### What platform are you using?

ESP32

### Board

AtomS3 Lite

### Component causing the issue

debug

### YAML Config

```yaml
esphome:
    name: hpsu-can
    friendly_name: HPSU.CAN
    platformio_options:
        build_unflags:
            - "-std=gnu++11"
            - "-fno-rtti"
        build_flags:
            - "-std=gnu++17"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source: github://Trunks1982/Daikin-Rotex-HPSU-CAN

logger:
  level: INFO

api:
  encryption:
    key: !secret hpsu_can_api_encryption_key

ota:
  platform: esphome
  password: !secret hpsu_can_ota_password

web_server:
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

captive_portal:

time:
  - platform: homeassistant

debug:
  update_interval: 5s

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Seconds
  - platform: uptime
    type: timestamp
    name: Uptime Timestamp
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

button:
  - platform: restart
    name: "Rotex ESP Restart"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID

canbus:
  - platform: esp32_can
    id: can_bus
    can_id: 0x680
    tx_pin: GPIO5
    rx_pin: GPIO6
    bit_rate: 20kbps

daikin_rotex_can:
  id: rotext_hpsu
  canbus_id: can_bus
  update_interval: 30
```
