### ISSUE TITLE
ESP32, st7789V printf problem  (at ESP8266 working perfectly)

### ISSUE THREAD

**Issue by Darek0203** [esphome/issues#6667]
### The problem

When I run the program (compiling works fine) the printf instruction does not display the values ​​of the variables "licz" or "lqi"
In the logs I can see that "licz" is read correctly (it has a float value, consistent with the actual indication of the wmbus transmitter), lqi too.

### Which version of ESPHome has the issue?

2024.11.3   or 2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.1

### What platform are you using?

ESP32

### Board

ESP32 with st7789v on one board

### YAML Config

```yaml
esphome:
  name: licznik-wody-z-lcd
  friendly_name: licznik wody z lcd

esp32:
  board: esp-wrover-kit
  #flash_size: 16MB

external_components:
  - source: github://SzczepanLeon/esphome-components@3.2.3
    components: [ wmbus ]
    
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxx"

ota:
  - platform: esphome
    password: "xxxx"

web_server:
  port: 80
  version: 2
  auth:
    username: "xxx"
    password: "xxx"

wifi:
  ssid: "xxxx"  
  password: "xxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xxxxx"
    password: "xxxxx"

mqtt:
   broker: xxxxxx
   username: xxxxx
   password: xxxxx

time:
  platform: sntp  

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_gray
    red: 50%
    green: 50%
    blue: 50%
font:
  - file: 'Robot.ttf'
    id: font1
    size: 30  
  - file: 'Robot.ttf'
    id: font2
    size: 20     
    
captive_portal:

wmbus:
  mosi_pin: GPIO26
  miso_pin: GPIO25
  clk_pin:  GPIO27
  cs_pin:   GPIO33
  gdo0_pin: GPIO17
  gdo2_pin: GPIO21



sensor:
      
  - platform: wmbus
    meter_id: 0x210exxxx
    type: izar 
    add_prefix: false
    
    lqi:
      name: "My lqi"
      id: lqi
    rssi:
      name: "My RSSI"
    total_water_m3:
      id: licz
      name: "stan licznika m3"  
    last_month_total_water_m3:
      name: "stan licznika w poprzednim miesiącu m3" 


spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19
display:
 - platform: st7789v
   model: TTGO TDisplay 135x240
   cs_pin: GPIO5
   dc_pin: GPIO16
   reset_pin: GPIO23
   rotation: 270  
   lambda: |-
       it.printf(1, 1, id(font1), "Akt %.3f m3   %d", id(licz).state, lqi->state);
```

### _**this working perfectly**_

esphome:
  name: licznik-wody
  friendly_name: licznik wody

esp8266:
  board: nodemcuv2 

external_components:
  - source: github://SzczepanLeon/esphome-components@3.2.3
    components: [ wmbus ]

# Enable logging
logger: 
  level: DEBUG

#mqtt:
   #broker: xxxxxx
   #username: xxxxxx
   #password: xxxxxxxxxx

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxx"

# Serwer with a statistic data and OTA board update
web_server:
  port: 80
  version: 2
  auth:
    username: "xxx"
    password: "xxx"

wifi:
  ssid: "xxxxxxxxxx"  
  password: "xxxxxxxxxxx"
 
  
    # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xxxxxxxxxxxxxxxx"
    password: "xxxxxxxx"

time:
  platform: sntp  

font:
  - file: 'Robot.ttf'
    id: font1
    size: 30  
  - file: 'Robot.ttf'
    id: font2
    size: 20    

captive_portal:

wmbus:
  mosi_pin: GPIO13
  miso_pin: GPIO12
  clk_pin:  GPIO14
  cs_pin:   GPIO2
  gdo0_pin: GPIO16
  gdo2_pin: GPIO15

sensor:
  - platform: wmbus
    meter_id: 0x210xxxx
    type: izar 
    add_prefix: false
  
    lqi:
      name: "My lqi"
    rssi:
      name: "My RSSI"
    total_water_m3:
      name: "stan licznika m3"  
      id: licz 
    last_month_total_water_m3:
      name: "stan licznika w poprzednim miesiącu m3" 
   
i2c:
  sda: GPIO04
  scl: GPIO05
  scan: True
  id: bus_a
  frequency: 400kHz
 

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x32"
    reset_pin: GPIO10
    address: 0x3C
    lambda: |-
      it.printf(1, 1, id(font1), TextAlign::TOP_LEFT , "%.3f", id(licz).state);
