### ISSUE TITLE
ili9xxx should not force loading of PSRAM

### ISSUE THREAD

**Issue by numo68** [esphome/issues#6669]
### The problem

The `ili9xxx` platform unconditionally pulls in the psram via
```
def AUTO_LOAD():
    if CORE.is_esp32:
        return ["psram"]
    return []
```

Unfortunately not every ESP32 module has it and there are side-effects. For example if one is using esp-idf, the Wi-Fi will try to enable some extra buffers and produce warnings such as

```
E (642) quad_psram: PSRAM ID read error: 0xffffffff, PSRAM chip not found or not supported
E (647) esp_psram: PSRAM enabled but initialization failed. Bailing out.
...
[W][esp-idf:000]: W (1376) wifi_init: WiFi cache TX buffers should be disabled when initialize SPIRAM failed
```

To make things worse I cannot even set the number of such buffers to zero via `CONFIG_ESP[32]_WIFI_CACHE_TX_BUFFER_NUM` in `sdkconfig_options`. I am not familiar with the handling of that but it seems that the  following in `Kconfig`

```
config ESP_WIFI_CACHE_TX_BUFFER_NUM
            int "Max number of WiFi cache TX buffers"
            depends on SPIRAM
            range 16 128
            default 32
```
always takes priority.

Disabling `CONFIG_SPIRAM` via `sdkconfig_options` does not work as the `psram` component forces it to true.

In my opinion the ESPHome should not silently set any defines that describe the hardware *capabilities*, especially not if it is not a hard requirement for the configuration. Using the PSRAM should be an explicit decision (if not required) or can be pulled in (if required), but in the latter case has to fail when started on a platform that does not have one. The functionality of the WiFi should not be affected depending on whether one has a specific display configured, that violates the principle of the least surprise.

I have no idea how to fix it with the least breakage. What I would suggest is
- the `psram` component fails if configured and no PSRAM is actually present
- components *requiring* PSRAM such as `esp32_camera` autoload it
- components *benefiting* from it might get a `use_psram` option similar to what `esp32_rmt_led_strip` if needed, and perhaps suggest configuring psram if neither the component nor the option is there

Ideas?

### Which version of ESPHome has the issue?

2025.1.0-dev

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

AZ Delivery ESP32 D1 Mini

### Component causing the issue

ili9xxx

### YAML Config

```yaml
esphome:
  name: minimal

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_WIFI_CACHE_TX_BUFFER_NUM: "0"
      CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM: "0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

display:
  - platform: ili9xxx
    model: TFT 2.4
    id: tft
    cs_pin: 22
    dc_pin: 21
    transform:
      mirror_y: true
    invert_colors: false
    data_rate: 20MHz
```

### Additional information

```
.esphome/build/minimal/sdkconfig.minimal.esphomeinternal:
CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM=0
CONFIG_ESP_WIFI_CACHE_TX_BUFFER_NUM=0
```
```
.esphome/build/minimal/sdkconfig.minimal
CONFIG_ESP_WIFI_CACHE_TX_BUFFER_NUM=32
CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM=32
```
