### ISSUE TITLE
sdm_meter - Home Assistant Entities stay online if meter is no longer reachable

### ISSUE THREAD

**Issue by BOFH90** [esphome/issues#6671]
### The problem

If I disconnect the SDM230, the entities in HA retain the last state and do not enter the unknown state, even after some hours/days.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.2

### What platform are you using?

ESP32

### Board

KinCony KC868-A32

### Component causing the issue

sdm_meter

### YAML Config

```yaml
uart:
  id: mod_bus
  tx_pin: GPIO14
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1

sensor:
  - platform: sdm_meter
    phase_a:
      active_power:
        name: "DG Zaehler 01 Power"
    import_active_energy:
      name: "DG Zaehler 01 Import"
    export_active_energy:
      name: "DG Zaehler 01 Export"
    update_interval: 30s
    address: 1
  - platform: sdm_meter
    phase_a:
      active_power:
        name: "DG Zaehler 02 Power"
    import_active_energy:
      name: "DG Zaehler 02 Import"
    export_active_energy:
      name: "DG Zaehler 02 Export"
    update_interval: 30s
    address: 2
```
