### ISSUE TITLE
EAP-TLS reauthentication misbehavior

### ISSUE THREAD

**Issue by Rudd-O** [esphome/issues#6674]
### The problem

When my stations configured to use EAP-TLS (all ESP-IDF, ESP32) reauthenticate, almost always they "misbehave".  This causes them to go offline in Home Assistant, until they retry (from a few seconds later up to a minute later) and then reauthentication succeeds.  This happens roughly every 1 hour.

### Which version of ESPHome has the issue?

core-2024.12.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

any

### What platform are you using?

ESP32-IDF

### Board

At least one of:

- nodemcu-32s
- m5stack-atom
- mhetesp32minikit (KeeYees ESP32)

Interesting exceptions:

- Problem **does not** appear to happen with the Nabu Casa Voice Assistant preview edition

### Component causing the issue

wifi

### YAML Config

```yaml
substitutions:
  name: "master-bedroom-bed"
  friendly_name: Master bedroom bed

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  # XTVTX ESP32 (wroom)
  board: nodemcu-32s
  framework:
    type: esp-idf

logger:
  level: debug
  logs:
    esp32_ble: debug
    sensor: info
    mdns: debug
    adc: info
    resistance: info
    internal_temperature: info
substitutions:
  name: "master-bedroom-bed"
  friendly_name: Master bedroom bed

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  # XTVTX ESP32 (wroom)
  board: nodemcu-32s
  framework:
    type: esp-idf

logger:
  level: debug
  logs:
    esp32_ble: debug
    sensor: info
    mdns: debug
    adc: info
    resistance: info
    internal_temperature: info


wifi:
  reboot_timeout: 120min
  networks:
  - ssid: !secret wifi_ssid_ent
    eap:
      identity: master-bedroom-bed.dragonfear
      certificate_authority: wi-fi/ca.pem
      certificate: wi-fi/certs/master-bedroom-bed/cert.pem
      key: wi-fi/certs/master-bedroom-bed/key.pem
  - ssid: !secret wifi_recovery_ssid
    password: !secret wifi_recovery_password

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

number:
  - platform: template
    optimistic: true
    id: resistance_threshold_for_occupant_1
    name: Resistance threshold for occupant 1
    min_value: 0
    max_value: 212184185438208
    step: 1000
    icon: mdi:omega
    entity_category: config
    unit_of_measurement: Ω
    restore_value: True
  - platform: template
    id: resistance_threshold_for_occupant_2
    optimistic: true
    name: Resistance threshold for occupant 2
    min_value: 0
    max_value: 212184185438208
    step: 1000
    icon: mdi:omega
    entity_category: config
    unit_of_measurement: Ω
    restore_value: True

binary_sensor:
  - platform: template
    id: occupant_1
    name: Occupant 1
    device_class: occupancy
    icon: mdi:bed
    lambda: |
      if (id(variable_resistance_1).state < id(resistance_threshold_for_occupant_1).state) {
        return true;
      }
      return false;
    filters:
      delayed_off: 5s
#    on_state:
#      - if:
#          condition:
#            lambda: "return id(occupant_1).state;"
#          then:
#            - lambda: >
#                id(occupant_1).set_icon("mdi:bed");
#          else:
#            - lambda: >
#                id(occupant_1).set_icon("mdi:bed-empty");
  - platform: template
    id: occupant_2
    name: Occupant 2
    device_class: occupancy
    icon: mdi:bed
    lambda: |
      if (id(variable_resistance_2).state < id(resistance_threshold_for_occupant_2).state) {
        return true;
      }
      return false;
    filters:
      delayed_off: 5s
#    on_state:
#      - if:
#          condition:
#            lambda: "return id(occupant_2).state;"
#          then:
#            - lambda: >
#                id(occupant_2).set_icon("mdi:bed");
#          else:
#            - lambda: >
#                id(occupant_2).set_icon("mdi:bed-empty");

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
    icon: mdi:restart
  - platform: safe_mode
    name: Safe mode restart
    entity_category: diagnostic
    icon: mdi:restart-alert

sensor:
- platform: uptime
  name: Uptime
  entity_category: diagnostic

- platform: wifi_signal
  name: "Wi-Fi signal strength"
  update_interval: 10s
  entity_category: "diagnostic"
- platform: internal_temperature
  name: "Device temperature"
  update_interval: 10s
  entity_category: "diagnostic"

- platform: adc
  id: resistance_voltage_1
  name: Resistance voltage 1
  pin: GPIO35
  attenuation: 11dB
  accuracy_decimals: 5
  update_interval: 0.2s
  filters:
    - median:
        window_size: 25
        send_every: 5
        send_first_at: 1
    - calibrate_linear:
      - 0.142 -> 0.0
      - 3.171 -> 3.33
  entity_category: "diagnostic"
  disabled_by_default: True
- platform: resistance
  id: variable_resistance_1
  name: Variable resistance 1
  sensor: resistance_voltage_1
  configuration: UPSTREAM
  resistor: 462kOhm
  reference_voltage: 3.33V
  icon: mdi:resistor
  entity_category: "diagnostic"
  disabled_by_default: True

- platform: adc
  id: resistance_voltage_2
  name: Resistance voltage 2
  pin: GPIO32
  attenuation: 11dB
  accuracy_decimals: 5
  update_interval: 0.2s
  filters:
    - median:
        window_size: 25
        send_every: 5
        send_first_at: 1
    - calibrate_linear:
      - 0.142 -> 0.0
      - 3.171 -> 3.33
  entity_category: "diagnostic"
  disabled_by_default: True
- platform: resistance
  id: variable_resistance_2
  name: Variable resistance 2
  sensor: resistance_voltage_2
  configuration: UPSTREAM
  resistor: 470kOhm
  reference_voltage: 3.33V
  icon: mdi:resistor
  entity_category: "diagnostic"
  disabled_by_default: True
```

### Anything in the logs that might be useful for us?

```txt
# AP logs:

Mon Jan 13 09:06:19 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-STARTED e0:5a:1b:a2:a4:f8
Mon Jan 13 09:06:19 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
Mon Jan 13 09:06:22 2025 daemon.notice radiusd[28250]: (7203) Login incorrect (eap_tls: (TLS) Cannot continue, as the peer is misbehaving.): [master-bedroom-bed.dragonfear] (from client localhost port 1 cli E0-5A-1B-A2-A4-F8)
Mon Jan 13 09:06:23 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-FAILURE2 e0:5a:1b:a2:a4:f8
Mon Jan 13 09:06:23 2025 daemon.notice hostapd: wlan_cis_2g_ent: AP-STA-DISCONNECTED e0:5a:1b:a2:a4:f8
Mon Jan 13 09:06:23 2025 daemon.warn hostapd: wlan_cis_2g_ent: STA e0:5a:1b:a2:a4:f8 IEEE 802.1X: authentication failed - EAP type: 13 (TLS)
Mon Jan 13 09:06:23 2025 daemon.info hostapd: wlan_cis_2g_ent: STA e0:5a:1b:a2:a4:f8 IEEE 802.11: authenticated
Mon Jan 13 09:06:23 2025 daemon.info hostapd: wlan_cis_2g_ent: STA e0:5a:1b:a2:a4:f8 RADIUS: stopped accounting session FA1746F1F1F27B73
Mon Jan 13 09:06:23 2025 daemon.info hostapd: wlan_cis_2g_ent: STA e0:5a:1b:a2:a4:f8 IEEE 802.11: associated (aid 1)
Mon Jan 13 09:06:23 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-STARTED e0:5a:1b:a2:a4:f8
Mon Jan 13 09:06:23 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
Mon Jan 13 09:06:26 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-RETRANSMIT2 e0:5a:1b:a2:a4:f8
Mon Jan 13 09:06:29 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-RETRANSMIT2 e0:5a:1b:a2:a4:f8
Mon Jan 13 09:06:35 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-RETRANSMIT2 e0:5a:1b:a2:a4:f8
Mon Jan 13 09:06:47 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-RETRANSMIT2 e0:5a:1b:a2:a4:f8
Mon Jan 13 09:06:47 2025 daemon.notice radiusd[28250]: (7212) Login OK: [master-bedroom-bed.dragonfear] (from client localhost port 1 cli E0-5A-1B-A2-A4-F8)
Mon Jan 13 09:06:47 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-SUCCESS2 e0:5a:1b:a2:a4:f8
Mon Jan 13 09:06:59 2025 daemon.info hostapd: wlan_cis_2g_ent: STA e0:5a:1b:a2:a4:f8 IEEE 802.11: authenticated
Mon Jan 13 09:06:59 2025 daemon.info hostapd: wlan_cis_2g_ent: STA e0:5a:1b:a2:a4:f8 IEEE 802.11: associated (aid 1)
Mon Jan 13 09:06:59 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-STARTED e0:5a:1b:a2:a4:f8
Mon Jan 13 09:06:59 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
Mon Jan 13 09:07:02 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-RETRANSMIT2 e0:5a:1b:a2:a4:f8
Mon Jan 13 09:07:02 2025 daemon.notice radiusd[28250]: (7220) Login OK: [master-bedroom-bed.dragonfear] (from client localhost port 1 cli E0-5A-1B-A2-A4-F8)
Mon Jan 13 09:07:02 2025 daemon.notice hostapd: wlan_cis_2g_ent: CTRL-EVENT-EAP-SUCCESS2 e0:5a:1b:a2:a4:f8
Mon Jan 13 09:07:02 2025 daemon.info hostapd: wlan_cis_2g_ent: STA e0:5a:1b:a2:a4:f8 WPA: pairwise key handshake completed (RSN)
Mon Jan 13 09:07:02 2025 daemon.notice hostapd: wlan_cis_2g_ent: EAPOL-4WAY-HS-COMPLETED e0:5a:1b:a2:a4:f8
Mon Jan 13 09:07:02 2025 daemon.notice hostapd: wlan_cis_2g_ent: AP-STA-CONNECTED e0:5a:1b:a2:a4:f8 auth_alg=open
Mon Jan 13 09:07:02 2025 daemon.info hostapd: wlan_cis_2g_ent: STA e0:5a:1b:a2:a4:f8 RADIUS: starting accounting session 36FBD77C53AA03E7
Mon Jan 13 09:07:02 2025 daemon.info hostapd: wlan_cis_2g_ent: STA e0:5a:1b:a2:a4:f8 IEEE 802.1X: authenticated - EAP type: 13 (TLS)
Mon Jan 13 09:07:02 2025 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-CIS) e0:5a:1b:a2:a4:f8
Mon Jan 13 09:07:02 2025 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-CIS) 10.250.1.29 e0:5a:1b:a2:a4:f8
Mon Jan 13 09:07:02 2025 daemon.info dnsmasq-dhcp[1]: DHCPREQUEST(br-CIS) 10.250.1.29 e0:5a:1b:a2:a4:f8
Mon Jan 13 09:07:02 2025 daemon.info dnsmasq-dhcp[1]: DHCPACK(br-CIS) 10.250.1.29 e0:5a:1b:a2:a4:f8 master-bedroom-bed
```
