### ISSUE TITLE
binary_sensor publish_state(false) not working

### ISSUE THREAD

**Issue by 1iverea9er** [esphome/issues#6679]
### The problem

This code not working if initial state of `binary_sensor` is `unknown`
`id(my_binary_sensor).publish_state(false);`

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.2

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

binary_sensor

### YAML Config

```yaml
esphome:
  on_boot:
      priority: 800
      then:
          - delay: 1min
          - lambda: |-
                      id(warning).publish_state(false);


binary_sensor:
  # Sensor water detect
  - platform: gpio
    name: "Leakage detect"
    id: warning
    device_class: moisture
    pin:
      number: $pin_warning_detect
      inverted: true
      mode:
        input: true
        pullup: true



```

### Additional information

But as the same time `on` state publish worked...
`id(my_binary_sensor).publish_state(true);`
