### ISSUE TITLE
Unable to sucessfully compile, always getting errors compiling api components when framework type set to arduino

### ISSUE THREAD

**Issue by FauxPalindrome** [esphome/issues#6680]
### The problem

I haven't been able to successfully compile for months.. using different (brand new) boards of different models.
I don't get the compile error when the framework type is set to _esp-idf_. Only when it's set to _arduino_.
HA server is a VM (Virtualbox) in a Win11 Host. I'm doing all this from a different computer.

Steps: 

1. ESPHome Web > "Prepare for first use"
2. Connect to Wi-Fi
3. Move on to Home Assistant, 1 new device discovered in ESPHome Device Builder
4. Take Control > Give a name
5. Install new configuration > get this error:
```
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/esphome-web-ddfbc8.yaml...
Failed config

wifi: [source /config/esphome/esphome-web-ddfbc8.yaml:22]
  
  Please specify at least an SSID or an Access Point to create.
  domain: .local
  reboot_timeout: 15min
  power_save_mode: LIGHT
  fast_connect: False
  enable_btm: False
  enable_rrm: False
  passive_scan: False
  enable_on_boot: True
  networks: []
  use_address: esphome-web-ddfbc8.local
``` 
At this point, the yaml config looks like this:
```
esphome:
  name: esphome-web-ddfbc8
  friendly_name: 'ESP32 #10'
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:

``` 

Obviously the Wi-Fi credentials weren't not saved by ESPHome Web so I go ahead and add them to the config, compile, and there they are. Framework type has to be set to _esp-idf_, otherwise, if it's set to _arduino_ I get the api compile error.
When set to  _esp-idf_ and sucessfully compiled, the ESPHome integration picks up the new device.

These 3 installation methods give me the compiling error:
- Wirelessly
- Plug into this computer
- Manual download

Haven't tried plugging into the computer running ESPHome Device Builder since it's a VM running HAOS and it can get pretty complicated at this point.

Here's the compile error:
```python
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/esphome-web-ddfbc8.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-web-ddfbc8 (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
Compiling .pioenvs/esphome-web-ddfbc8/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/esphome-web-ddfbc8/src/esphome/components/api/api_frame_helper.cpp.o
during RTL pass: final
In file included from src/esphome/components/api/api_frame_helper.cpp:1:
src/esphome/components/api/api_frame_helper.h: In member function 'virtual std::__cxx11::string esphome::api::APIPlaintextFrameHelper::getpeername()':
src/esphome/components/api/api_frame_helper.h:151:77: internal compiler error: in gen_decl_die, at dwarf2out.c:26475
   std::string getpeername() override { return this->socket_->getpeername(); }
                                                                             ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
*** [.pioenvs/esphome-web-ddfbc8/src/esphome/components/api/api_frame_helper.cpp.o] Error 1
during RTL pass: final
In file included from src/esphome/components/api/api_connection.h:7,
                 from src/esphome/components/api/api_connection.cpp:1:
src/esphome/components/api/api_pb2_service.h: In member function 'virtual void esphome::api::APIServerConnectionBase::on_get_time_response(const esphome::api::GetTimeResponse&)':
src/esphome/components/api/api_pb2_service.h:94:67: internal compiler error: in gen_decl_die, at dwarf2out.c:26475
   virtual void on_get_time_response(const GetTimeResponse &value){};
                                                                   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
*** [.pioenvs/esphome-web-ddfbc8/src/esphome/components/api/api_connection.cpp.o] Error 1
========================== [FAILED] Took 1.79 seconds ==========================
``` 

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.2 (and many previous ones)

### What platform are you using?

ESP32

### Board

esp32dev, esp32-s3

### Component causing the issue

api

### YAML Config

```yaml
esphome:
  name: esp32-no10
  friendly_name: "ESP32 #10"
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino
    
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp32no10_api_key

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.86.194
    gateway: 192.168.86.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esp32no10_ap_ssid
    password: !secret esp32no10_ap_password
```
