### ISSUE TITLE
AddressableLightDisplay does not switch the parent AddressableLight

### ISSUE THREAD

**Issue by andrewjswan** [esphome/issues#6687]
### The problem

AddressableLightDisplay does not switch the parent AddressableLight.
That is, I turn on the effect on the AddressableLight, it is displayed.
Then I call: `id(display).set_enabled(true);`
It should switch the parent AddressableLight to the mode of operation without the effect and the display of the AddressableLightDisplay information should begin, but this does not happen, the effect continues to be displayed. 

https://github.com/esphome/esphome/blob/49c01c26f1847debfa53dc7e31b6434debcfd40e/esphome/components/addressable_light/addressable_light_display.h#L30-L34

If I manually turn off the effect (None), then the display of AddressableLightDisplay is there.
Then I call: `id(display).set_enabled(false);`
But nothing happens.

https://github.com/esphome/esphome/blob/49c01c26f1847debfa53dc7e31b6434debcfd40e/esphome/components/addressable_light/addressable_light_display.h#L25-L28

It looks like `light_state_` is not updated when the firmware is running.

https://github.com/esphome/esphome/blob/49c01c26f1847debfa53dc7e31b6434debcfd40e/esphome/components/addressable_light/addressable_light_display.h#L24C9-L24C21

### Which version of ESPHome has the issue?

 2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.2

### What platform are you using?

ESP32

### Board

Node MCU

### Component causing the issue

AddressableLightDisplay

### YAML Config

```yaml
switch:
  - platform: template
    name: Display
    icon: mdi:shuffle
    lambda: |-
      return id(esp_display).get_enabled();
    turn_on_action:
      - lambda: |-
          id(esp_display).set_enabled(true);
    turn_off_action:
      - lambda: |-
          id(esp_display).set_enabled(false);

font:
  - file: https://github.com/trip5/Matrix-Fonts/raw/refs/heads/main/8-series/MatrixChunky8.ttf
    id: px8_font
    size: 8
    glyphs: |-
      01234:56789

display:
  - platform: addressable_light
    id: esp_display
    addressable_light_id: esp_light
    width: 16
    height: 16
    update_interval: 1s
    lambda: |-
      it.strftime(4, 1, id(px8_font), "%H", id(esp_time).now());
      it.strftime(4, 9, id(px8_font), "%M", id(esp_time).now());
```

### Anything in the logs that might be useful for us?

```txt

```
