### ISSUE TITLE
several Segmentation fault when compiling for ESP32 cam

### ISSUE THREAD

**Issue by ThomasFTL** [esphome/issues#6688]
### The problem

Since version 2024.12.01 ESPHome can no longer compile for the ESP32 cam. I cannot say whether this only affects the cam or the ESP32 in general, as the other projects are built with ESP8266.
The beta version compiles without errors.

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.2

### What platform are you using?

ESP32

### Board

ESP32 Cam

### YAML Config

```yaml
# Steuerung der Teich-Cam
esphome:
  name: teich-cam
  friendly_name: Teich Cam
  platform: ESP32
  board: esp32cam


# Enable logging
logger:
  level: WARN

  
# Enable Home Assistant API
api:


ota:
  - platform: esphome


wifi:
  networks:
    - ssid: !secret secret_wifi_ssid
      password: !secret secret_wifi_password
  manual_ip:
    static_ip: !secret secret_ip
    gateway: !secret secret_gateway
    subnet: 255.255.255.0
    dns1: !secret secret_dns

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Teich-Cam"
    password: !secret secret_ap_password

captive_portal:


web_server:
  port: 80
  ota: False



esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
    

esp32_camera:
  name: Teich-Kamera
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1600x1200
  jpeg_quality: 10
  #vertical_flip: False

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4 


  - platform: ledc
    id: pwm_servoh
    pin: GPIO15
    frequency: 50 Hz
    #channel: 2


light:
  - platform: binary
    output: gpio_4
    name: Licht Teichkamera

sensor:
  # Wifi-Signalstärke
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: wifisignal
    update_interval: 60s

button:
  - platform: restart
    name: "Reset"


text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Addresse
    ssid:
      name: ESP verbundene SSID
    mac_address:
      name: ESP MAC WiFi Addresse
    scan_results:
      name: ESP letztes Scan-Ergebnis
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.12.4
INFO Reading configuration /config/esphome/teich-cam.yaml...
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO15 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing teich-cam (board: esp32cam; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/teich-cam/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/teich-cam/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/teich-cam/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/teich-cam/src/esphome/components/api/api_pb2_service.cpp.o
during GIMPLE pass: eh
src/esphome/components/api/api_pb2_service.cpp: In member function 'bool esphome::api::APIServerConnectionBase::send_hello_response(const esphome::api::HelloResponse&)':
src/esphome/components/api/api_pb2_service.cpp:11:6: internal compiler error: Segmentation fault
 bool APIServerConnectionBase::send_hello_response(const HelloResponse &msg) {
      ^~~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
*** [.pioenvs/teich-cam/src/esphome/components/api/api_pb2_service.cpp.o] Error 1
during GIMPLE pass: eh
src/esphome/components/api/api_pb2.cpp: In member function 'virtual bool esphome::api::HelloRequest::decode_varint(uint32_t, esphome::api::ProtoVarInt)':
src/esphome/components/api/api_pb2.cpp:596:6: internal compiler error: Segmentation fault
 bool HelloRequest::decode_varint(uint32_t field_id, ProtoVarInt value) {
      ^~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
*** [.pioenvs/teich-cam/src/esphome/components/api/api_pb2.cpp.o] Error 1
during GIMPLE pass: eh
src/esphome/components/api/api_frame_helper.cpp: In function 'bool esphome::api::is_would_block(ssize_t)':
src/esphome/components/api/api_frame_helper.cpp:16:6: internal compiler error: Segmentation fault
 bool is_would_block(ssize_t ret) {
      ^~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
*** [.pioenvs/teich-cam/src/esphome/components/api/api_frame_helper.cpp.o] Error 1
during GIMPLE pass: eh
src/esphome/components/api/api_connection.cpp: In constructor 'esphome::api::APIConnection::APIConnection(std::unique_ptr<esphome::socket::Socket>, esphome::api::APIServer*)':
src/esphome/components/api/api_connection.cpp:31:1: internal compiler error: Segmentation fault
 APIConnection::APIConnection(std::unique_ptr<socket::Socket> sock, APIServer *parent)
 ^~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
*** [.pioenvs/teich-cam/src/esphome/components/api/api_connection.cpp.o] Error 1
========================== [FAILED] Took 7.41 seconds ==========================
```
