### ISSUE TITLE
Binary input timing conversions

### ISSUE THREAD

**Issue by maslyankov** [esphome/issues#6690]
### The problem

When using timing with Xs it does not work:

```
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO34
      inverted: true
    name: "${friendly_name} Factory Button"
    on_multi_click:
      - timing:
          - ON for at least 3s
        then:
          - lambda: |-
              ESP_LOGI("button", "[Factory Button] Hold Detected! Doing Factory Reset in 5 seconds...");
          - uart.write: "[Factory Button] Hold Detected! Doing Factory Reset in 5 seconds...\n"  # Reboot message to be written to UART
          - delay: 5s
          - button.press: factory_reset_button
```

When using timing with ms equivalent it works:

```
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO34
      inverted: true
    name: "${friendly_name} Factory Button"
    on_multi_click:
      - timing:
          - ON for at least 3000ms
        then:
          - lambda: |-
              ESP_LOGI("button", "[Factory Button] Hold Detected! Doing Factory Reset in 5 seconds...");
          - uart.write: "[Factory Button] Hold Detected! Doing Factory Reset in 5 seconds...\n"  # Reboot message to be written to UART
          - delay: 5s
          - button.press: factory_reset_button
```

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by ssieb** [comment]
What do you see in the logs?  Set the logger to verbose to see multi-click progress messages.

**Comment by smashedr** [comment]
I saw this out of the corner of my eye, and it made me curious to test my buttons, at least since 12+ (which has been somewhat buggy) and they all work with no issues. I have a few different buttons all with timings, here are a couple examples, that I just tested.

2024.11.3:
```yaml
binary_sensor:
  # https://esphome.io/#binary-sensor-components
  - platform: gpio
    name: "Touch 1 - ${box_num}"
    id: touch_1
    icon: mdi:gesture-tap-box
    pin:
      number: 23
      mode: INPUT_PULLUP
    on_multi_click:
      - timing:
          - ON for at most 0.9s
        then:
          - logger.log: "Single Click - Start Voice"
          - script.execute: va_start
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "1+ Second Touch - Toggle Wake"
          - rtttl.play: "s:d=4,o=6,b=100:16d"
          - switch.toggle: micro_wake_toggle
```

2024.12.2:
```yaml
platform: gpio
name: "Physical Button ${box_num}"
icon: mdi:radiobox-marked
entity_category: diagnostic
disabled_by_default: true
pin:
  number: ${pin}
  mode: INPUT_PULLUP
filters:
  - invert:
on_multi_click:
  - timing:
      - ON for at least 3s
    then:
      - logger.log: "3 Second Reset"
      - button.press: btn_restart
  - timing:
      - ON for at most 2.9s
      - OFF for at least 0.1s
    then:
      - logger.log: "Single Click"
      - light.toggle: main_led

```
