### ISSUE TITLE
Waveshare 2.13" v3 display seems to have the wrong height

### ISSUE THREAD

**Issue by Duckle29** [esphome/issues#6693]
### The problem

I've been playing around with a simple display on the waveshare 2.13" V4 display. (newest) regardless, reading the specs for both the V3 and V4, both are 250x122px displays, however `it.get_height()` returns 128
[manuals and specs for the display](https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT_Manual#Resources)

I noticed this when using `get_height()` to try and position a graph. I would do a PR, but have 5 minutes before I have to head out, so wanted to post an issue instead, as it's possible I'm missing some nuance or something. 

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.2

### What platform are you using?

ESP32

### Board

Waveshare E-paper ESP32 Driver board Rev 3

### Component causing the issue

waveshare_epaper

### YAML Config

```yaml
esphome:
  name: e-paper-test
  friendly_name: E-paper test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "xxxx"

ota:
  - platform: esphome
    password: "xxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "E-Paper-Test Fallback Hotspot"
    password: xxxx

captive_portal:

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

globals:
  - id: init_boot
    type: bool
    restore_value: False
    initial_value: "0"

sensor:
  - platform: homeassistant
    entity_id: sensor.scd30_1_co2
    id: scd30_co2
    internal: True
    on_value: 
      then:
        - if:
            condition:
              lambda: 'return !id(init_boot);'
            then: 
              - component.update: disp
              - globals.set: 
                  id: init_boot
                  value: "1"
            
        
  - platform: homeassistant
    entity_id: sensor.scd30_1_rh
    id: scd30_rh
    internal: True
  - platform: homeassistant
    entity_id: sensor.scd30_1_t
    id: scd30_t
    internal: True

graph:
  - id: co2_graph
    height: 61
    width: 220
    duration: 
      days: 0
      hours: 8
    border: True
    y_grid: 250
    min_range: 1000
    traces:
      - sensor: scd30_co2
        line_type: SOLID
        line_thickness: 2
        continuous: True

font:
  # gfonts://family[@weight]
  - file:
      type: gfonts
      family: Literata
      weight: 700
    id: literata_b
    size: 25
    extras:
      - file: "gfonts://Material+Symbols+Outlined"
        glyphs: [
          "\ue1ff", # Thermometer
          "\uf87e", # Humidity %
          "\ue7b0", # CO2
        ]
  - file:
      type: gfonts
      family: Literata
      weight: 700
    id: literata_med_b
    size: 20

  - file:
      type: gfonts
      family: Literata
      weight: 400
    id: literata_smol
    size: 13

display:
  - platform: waveshare_epaper
    id: disp
    cs_pin: GPIO15
    dc_pin: GPIO27
    reset_pin: GPIO26
    busy_pin: GPIO25
    model: 2.13inv3
    full_update_every: 30
    rotation: 270
    update_interval: 60s
    pages: 
      - id: home_screen
        lambda: |-
          if(id(scd30_co2).has_state())
          {
            it.printf(10, 0, id(literata_b), "\ue1ff%.1f°C", id(scd30_t).state);
            it.printf(it.get_width() -10, 0, id(literata_b), TextAlign::RIGHT, "\uf87e%.1f%%", id(scd30_rh).state);
            it.printf(it.get_width()/2, 30, id(literata_med_b), TextAlign::CENTER_HORIZONTAL, "%.0fppm", id(scd30_co2).state);
            
            int y_grid = 250;
            int graph_width = 220;
            int graph_height = 61; // display-height/2
            int graph_start_x = it.get_width() - graph_width; // Right adjust graph
            int graph_start_y = it.get_height() - graph_height; // Bottom adjust graph
            ESP_LOGD("custom", "%.1f %.1f", float(it.get_height()), float(it.get_width()));
            // Generate y-axis labels
            int co2_val = id(scd30_co2).state;
            int graph_lim = (int((co2_val + 1) / y_grid)+1) * y_grid; // Round up to nearest 'y_grid'

            it.printf(it.get_width()-220, graph_start_y, id(literata_smol), TextAlign::CENTER_RIGHT, "%d", graph_lim);
            //it.graph(graph_start_x, 61, id(co2_graph)); // This works
            it.graph(graph_start_x, graph_start_y, id(co2_graph)); // This places the graph over the bottom edge

          } else {
            it.print(it.get_width()/2, it.get_height()/2, id(literata_b), TextAlign::CENTER, "Starting");
          }
```

### Anything in the logs that might be useful for us?

```txt
Debug log of `get_height()` and `get_width()` `[09:06:30][D][custom:140]: 128.0 250.0`
```
