### ISSUE TITLE
esp-idf framework not compiling - error in esphome i think

### ISSUE THREAD

**Issue by yen-yum-yum** [esphome/issues#6694]
### The problem

While complileng yaml to create bin - ( for future use with web tool) i get foll error src/esphome/components/uart/uart_component_esp_idf.cpp: In member function 'virtual bool esphome::uart::IDFUARTComponent::peek_byte(uint8_t*)':
src/esphome/components/uart/uart_component_esp_idf.cpp:153:62: error: 'portTICK_RATE_MS' was not declared in this scope; did you mean 'portTICK_PERIOD_MS'?
  153 |     int len = uart_read_bytes(this->uart_num_, data, 1, 20 / portTICK_RATE_MS);
      |                                                              ^~~~~~~~~~~~~~~~
      |                                                              portTICK_PERIOD_MS
src/esphome/components/uart/uart_component_esp_idf.cpp: In member function 'virtual bool esphome::uart::IDFUARTComponent::read_array(uint8_t*, size_t)':
src/esphome/components/uart/uart_component_esp_idf.cpp:177:65: error: 'portTICK_RATE_MS' was not declared in this scope; did you mean 'portTICK_PERIOD_MS'?
  177 |     uart_read_bytes(this->uart_num_, data, length_to_read, 20 / portTICK_RATE_MS);
      |                                                                 ^~~~~~~~~~~~~~~~
      |                                                                 portTICK_PERIOD_MS
Compiling .pioenvs/living-mini-sensor/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
*** [.pioenvs/living-mini-sensor/src/esphome/components/uart/uart_component_esp_idf.cpp.o] Error 1     - understand its some depreciated function - sorry i cant help more - i dont have tech skills 

### Which version of ESPHome has the issue?

ESPHome 2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

 Core 2025.1.2 Supervisor 2024.12.3 Operating System 14.1 Frontend 20250109.0

### What platform are you using?

ESP32

### Board

Elcrow Esp32 -C3 using esp32 c3fn4 /fh4

### Component causing the issue

i dont know whats meant by it - board is meant to run a Ld2410c sensor and double as blutooth proxy

### YAML Config

```yaml
#This is a custom firmware for Human Presence Sensor 1U
# https://screek.io/1u

esphome:
  name: living-mini-sensor
  comment: Screek Human Presence Sensor 1U
  friendly_name: living_mini_sensor
  name_add_mac_suffix: True
  on_boot:
    priority: 900
    then:
       lambda: |-
        id(cpu_speed) = ESP.getCpuFreqMHz() ;
  project: 
    name: Screek.Human_Presence_Sensor
    version: 1U
  min_version: 2023.6.1

globals:
   - id: cpu_speed
     type: int
     restore_value: no
     initial_value: '0'

external_components:
  # - source: github://screek-workshop/custom_components_support_for_screek_1u
  - source:
      type: git
      url: https://github.com/screek-workshop/custom_components_support_for_screek_1u
      ref: master
    # components: [ ld2410, uart ]
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    
    

#improv_serial:

logger:
  baud_rate: 0
# Enable the ESP32 BLE Tracker Hub
esp32_ble_tracker:
# Enable Bluetooth Proxy
bluetooth_proxy:


api:
   encryption:
    key: "usxsJ9ygtMy31FdqZ8y6I5I/A/klCVU8wMBpZC8NReE="

  # encryption:
    # key: "YOUR-API-PASSWORD"

ota:
  # This won't work for the original firmware(we use diffrent ota password),
  # so if you want to turn it into your own OTA, 
  # make sure to completely flash your custom yaml in the firmware once.
  # after that, you may always ota with your own password.
  - platform: esphome
    password: "9788813cb324d1cb092a577500accbc6"


# By automatically importing to the console, 
# subsequent adjustments can be easily made without having to manually fix a specific name.
# dashboard_import:
#  package_import_url: github://screekworkshop/screek-human-sensor/1u/yaml/Screek-Humen-Dectet-1u.yaml@2023.06
#  import_full_config: False
wifi:
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
     # priority: 10.0
    #- ssid: !secret wifi_ssid
     # password: !secret wifi_password
     # priority: 5.0
  output_power: 19dBm
  #power_save_mode: NONE
  reboot_timeout: 10min

  ap:
    ssid: "living-screek"
    password: ""

captive_portal:

#web_server:
 # port: 80

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

sensor:
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"

  #- platform: internal_temperature
   #  id: sys_esp_temperature
    # name: ESP Temperature
     #unit_of_measurement: °C
     #device_class: TEMPERATURE
     #update_interval: 1s
     #entity_category: "diagnostic"

  #- platform: template
   # id: sys_esp_temperature
    #name: ESP Temperature
    #lambda: return temperatureRead();
    #unit_of_measurement: °C
    #device_class: TEMPERATURE
    #update_interval: 5s
    #entity_category: "diagnostic"

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 10s

  - platform: wifi_signal 
    name: RSSI
    id: wifi_signal_db
    update_interval: 5s
    entity_category: "diagnostic"

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"

  - platform: ld2410
    moving_distance:
      name : Moving Distance
      id: moving_distance
    still_distance:
      name: Still Distance
      id: still_distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    light:
      name: Sun Light
light:
  - platform: status_led
    name: sys_status
    pin: GPIO10
    internal: True
    restore_mode: ALWAYS_OFF

    

time:
  - platform: sntp
    id: time_sntp

uart:
  id: uart_ld2410
  tx_pin: GPIO20
  rx_pin: GPIO21
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  timeout: 150s
  id: ld2410_radar
  # max_move_distance : 6m
  # max_still_distance: 0.75m
  # g0_move_threshold: 10
  # g0_still_threshold: 20
  # g1_move_threshold: 10
  # g1_still_threshold: 20
  # g2_move_threshold: 20
  # g2_still_threshold: 21
  # g3_move_threshold: 30
  # g3_still_threshold: 31
  # g4_move_threshold: 40
  # g4_still_threshold: 41
  # g5_move_threshold: 50
  # g5_still_threshold: 51
  # g6_move_threshold: 60
  # g6_still_threshold: 61
  # g7_move_threshold: 70
  # g7_still_threshold: 71
  # g8_move_threshold: 80
  # g8_still_threshold: 81

button:
  - platform: template
    name: "Enable LD2410 BLE"
    # disabled_by_default: True
    entity_category: "config"
    icon: mdi:bluetooth
    on_press:
      lambda: |-
        id(ld2410_radar) -> ble_control(true);

  - platform: template
    name: "Disable LD2410 BLE"
    # disabled_by_default: True
    entity_category: "config"
    icon: mdi:bluetooth-off
    on_press:
      lambda: |-
        id(ld2410_radar) -> ble_control(false);

  - platform: template
    name: "LD2410 Reboot"
    icon: mdi:radar
    entity_category: "config"
    on_press:
      lambda: |-
        // auto* radar = LD2410Component::get(ld2410); 
        // radar -> roboot();
        id(ld2410_radar) -> reboot();

  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: Factory Reset
    id: factory_reset_all
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ESP32 IP Address"
    ssid:
      name: "ESP32 Connected SSID"
    bssid:
      name: "ESP32 Connected BSSID"
    mac_address:
      name: "ESP32 MAC Address"
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.12.4
INFO Reading configuration /config/esphome/living-mini-sensor.yaml...
INFO Detected timezone 'Asia/Calcutta'
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.3.2
INFO Compiling app...
Processing living-mini-sensor (board: esp32-c3-devkitm-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50105.0 (5.1.5) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.10.2 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 12.2.0+20230208
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.6
Compiling .pioenvs/living-mini-sensor/src/esphome/components/uart/uart_component_esp_idf.cpp.o
Compiling .pioenvs/living-mini-sensor/src/esphome/components/web_server_idf/web_server_idf.cpp.o
Compiling .pioenvs/living-mini-sensor/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/living-mini-sensor/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
src/esphome/components/uart/uart_component_esp_idf.cpp: In member function 'virtual bool esphome::uart::IDFUARTComponent::peek_byte(uint8_t*)':
src/esphome/components/uart/uart_component_esp_idf.cpp:153:62: error: 'portTICK_RATE_MS' was not declared in this scope; did you mean 'portTICK_PERIOD_MS'?
  153 |     int len = uart_read_bytes(this->uart_num_, data, 1, 20 / portTICK_RATE_MS);
      |                                                              ^~~~~~~~~~~~~~~~
      |                                                              portTICK_PERIOD_MS
src/esphome/components/uart/uart_component_esp_idf.cpp: In member function 'virtual bool esphome::uart::IDFUARTComponent::read_array(uint8_t*, size_t)':
src/esphome/components/uart/uart_component_esp_idf.cpp:177:65: error: 'portTICK_RATE_MS' was not declared in this scope; did you mean 'portTICK_PERIOD_MS'?
  177 |     uart_read_bytes(this->uart_num_, data, length_to_read, 20 / portTICK_RATE_MS);
      |                                                                 ^~~~~~~~~~~~~~~~
      |                                                                 portTICK_PERIOD_MS
Compiling .pioenvs/living-mini-sensor/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
*** [.pioenvs/living-mini-sensor/src/esphome/components/uart/uart_component_esp_idf.cpp.o] Error 1
========================= [FAILED] Took 37.86 seconds =========================
```

### Additional information

it compliles without any problem if i change framework to arduino from esp-idf  which was what was reccomended by esphome docs for blutooth .proxy.    device is also  working fine with arduino framework .. sorry cant be of more help -
