### ISSUE TITLE
No degree symbol on TM1638 7-segment/button/LED Module

### ISSUE THREAD

**Issue by PAINKILLER0928** [esphome/issues#6696]
### The problem

Hi there,

Beautiful integration of the [TM1638 board](https://github.com/esphome/esphome/tree/dev/esphome/components/tm1638).

I'm only missing the degree symbol on the 7-segment display, which would be useful for displaying temperature values.

It's implemented in the TM1637 integration with the "~"  sign.

In the header file "[esphome/components/tm1638/sevenseg.h](https://github.com/esphome/esphome/blob/dev/esphome/components/tm1638/sevenseg.h)" at line # 102 there's "0x01" mapped to "~".

If it's supposed to work like the TM1637 integration, it should be something like 0x63 to light up the Segments A, B, F and G?

Best regards,
Harry

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.2

### What platform are you using?

ESP32

### Board

ESP32-DevKitC V4

### Component causing the issue

TM1638

### YAML Config

```yaml
esphome:
  name: "esphome-lab"
  friendly_name: "esphome-lab"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  
# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxx"

ota:
  - platform: esphome
    password: "xxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip: 
    static_ip: 192.168.xxx.xxx
    subnet: 255.255.255.0
    gateway: 192.168.xxx.xxx
    dns1: 192.168.xxx.xxx
    dns2: 8.8.8.8
  
  domain: .xxxxxx.intra

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Epshome-Lab Fallback Hotspot"
    password: "xxxxxx"

captive_portal:

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org

globals:
- id: page
  type: int
  initial_value: '1'

output:
  - platform: tm1638
    id: TM1638Led1
    led: 0

  - platform: tm1638
    id: TM1638Led2
    led: 1
  
  - platform: tm1638
    id: TM1638Led3
    led: 2
  
  - platform: tm1638
    id: TM1638Led4
    led: 3
  
  - platform: tm1638
    id: TM1638Led5
    led: 4
  
  - platform: tm1638
    id: TM1638Led6
    led: 5
  
  - platform: tm1638
    id: TM1638Led7
    led: 6
  
  - platform: tm1638
    id: TM1638Led8
    led: 7


sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

  - platform: homeassistant
    entity_id: sensor.gw1100a_v2_2_0_outdoor_temperature
    id: "temp_out"
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1

  - platform: homeassistant
    entity_id: sensor.gw1100a_v2_2_0_indoor_temperature
    id: "temp_in"
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
  
       
binary_sensor:

  - platform: status
    name: "ESP32 HomeLab Status"

  - platform: tm1638
    name: "TM1638 Button 1"
    id: TM1638Button1
    key: 0
    filters:
      - delayed_on: 10ms
    on_press: 
      then:
        - globals.set: 
            id: page
            value: '1'

  - platform: tm1638
    name: "TM1638 Button 2"
    id: TM1638Button2
    key: 1
    filters:
      - delayed_on: 10ms
    on_press: 
      then:
        - globals.set: 
            id: page
            value: '2'

  - platform: tm1638
    name: "TM1638 Button 3"
    id: TM1638Button3
    key: 2
    filters:
      - delayed_on: 10ms
    on_press: 
      then:
        - globals.set: 
            id: page
            value: '3'
        
  - platform: tm1638
    name: "TM1638 Button 4"
    id: TM1638Button4
    key: 3
    filters:
      - delayed_on: 10ms
    on_press: 
      then:
        - globals.set: 
            id: page
            value: '4'

  - platform: tm1638
    name: "TM1638 Button 5"
    id: TM1638Button5
    key: 4
    filters:
      - delayed_on: 10ms
    on_press: 
      then:
        - globals.set: 
            id: page
            value: '5'

  - platform: tm1638
    name: "TM1638 Button 6"
    id: TM1638Button6
    key: 5
    filters:
      - delayed_on: 10ms
    on_press: 
      then:
        - globals.set: 
            id: page
            value: '6'

  - platform: tm1638
    name: "TM1638 Button 7"
    id: TM1638Button7
    key: 6
    filters:
      - delayed_on: 10ms
    on_press: 
      then:
        - globals.set: 
            id: page
            value: '7'

  - platform: tm1638
    name: "TM1638 Button 8"
    id: TM1638Button8
    key: 7
    filters:
      - delayed_on: 10ms
    on_press: 
      then:
        - globals.set: 
            id: page
            value: '8'

display:
  platform: tm1638
  clk_pin: GPIO25
  dio_pin: GPIO26
  stb_pin: GPIO27
  intensity: 1
  update_interval: 500ms
  lambda: |-
      switch (id(page)){
        case 1:
          it.print("        ");
          it.strftime(" %H.%M.%S", id(sntp_time).now());
          id(TM1638Led1).turn_on();
          id(TM1638Led2).turn_off();
          id(TM1638Led3).turn_off();
          id(TM1638Led4).turn_off();
          id(TM1638Led5).turn_off();
          id(TM1638Led6).turn_off();
          id(TM1638Led7).turn_off();
          id(TM1638Led8).turn_off();
          break;
        case 2:
          it.print("        ");
          it.strftime("%d.%m.%Y", id(sntp_time).now());
          id(TM1638Led1).turn_off();
          id(TM1638Led2).turn_on();
          id(TM1638Led3).turn_off();
          id(TM1638Led4).turn_off();
          id(TM1638Led5).turn_off();
          id(TM1638Led6).turn_off();
          id(TM1638Led7).turn_off();
          id(TM1638Led8).turn_off();
          break;
        case 3:
          it.print("        ");
          it.printf("o %.1f~C", id(temp_out).state);
          id(TM1638Led1).turn_off();
          id(TM1638Led2).turn_off();
          id(TM1638Led3).turn_on();
          id(TM1638Led4).turn_off();
          id(TM1638Led5).turn_off();
          id(TM1638Led6).turn_off();
          id(TM1638Led7).turn_off();
          id(TM1638Led8).turn_off();
          break;
        case 4:
          it.print("        ");
          it.printf("i %.1f~C", id(temp_in).state);
          id(TM1638Led1).turn_off();
          id(TM1638Led2).turn_off();
          id(TM1638Led3).turn_off();
          id(TM1638Led4).turn_on();
          id(TM1638Led5).turn_off();
          id(TM1638Led6).turn_off();
          id(TM1638Led7).turn_off();
          id(TM1638Led8).turn_off();
          break;
        case 5:
          it.print("        ");
          it.print("~~~~");
          id(TM1638Led1).turn_off();
          id(TM1638Led2).turn_off();
          id(TM1638Led3).turn_off();
          id(TM1638Led4).turn_off();
          id(TM1638Led5).turn_on();
          id(TM1638Led6).turn_off();
          id(TM1638Led7).turn_off();
          id(TM1638Led8).turn_off();
          break;
        case 6:
          it.print("        ");
          it.print("Page6");
          id(TM1638Led1).turn_off();
          id(TM1638Led2).turn_off();
          id(TM1638Led3).turn_off();
          id(TM1638Led4).turn_off();
          id(TM1638Led5).turn_off();
          id(TM1638Led6).turn_on();
          id(TM1638Led7).turn_off();
          id(TM1638Led8).turn_off();
          break;
        case 7:
          it.print("        ");
          it.print("Page7");
          id(TM1638Led1).turn_off();
          id(TM1638Led2).turn_off();
          id(TM1638Led3).turn_off();
          id(TM1638Led4).turn_off();
          id(TM1638Led5).turn_off();
          id(TM1638Led6).turn_off();
          id(TM1638Led7).turn_on();
          id(TM1638Led8).turn_off();
          break;
        case 8:
          it.print("        ");
          it.print("Page8");
          id(TM1638Led1).turn_off();
          id(TM1638Led2).turn_off();
          id(TM1638Led3).turn_off();
          id(TM1638Led4).turn_off();
          id(TM1638Led5).turn_off();
          id(TM1638Led6).turn_off();
          id(TM1638Led7).turn_off();
          id(TM1638Led8).turn_on();
          break;
      }
```

### Anything in the logs that might be useful for us?

```txt

```
