### ISSUE TITLE
http_request does not send data over LAN connection

### ISSUE THREAD

**Issue by Allkorolev** [esphome/issues#6697]
### The problem

Hello, I've encountered a problem. 
The http_request component does not send data to an external http server; when trying to send data, the device reboots.
The module is used for LAN transmission - W5500
At the same time, there are no problems with Wi-Fi connection. 
Problems with the network can be ruled out, because... I checked it initially, the problem is in the http_request component

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.2

### What platform are you using?

ESP32

### Component causing the issue

http_request

### YAML Config

```yaml
esphome:
  name: $devicename
  comment: Base Device
  project:
    name: "base.device"
    version: $device_version
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: $api_key

ethernet:
  type: W5500
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  cs_pin: GPIO5
  interrupt_pin: GPIO32
  reset_pin: GPIO33

web_server:
  version: 3
  port: 80
  auth:
    username: admin
    password: admin

status_led:
  pin:
    number: "$status_led_pin"

one_wire:
  - platform: gpio
    pin: "$dallas_pin"
    


i2c:
  sda: "$i2c_sda_pin"
  scl: "$i2c_scl_pin"
  scan: true

uart:
  rx_pin: "$uart_rx_pin"
  tx_pin: "$uart_tx_pin"
  baud_rate: 9600

ads1115:
  - address: 0x48
    continuous_mode: true

time:
  - platform: sntp
    id: sntp_time
    on_time:
      - seconds: 10
        minutes: /5
        then:
          - script.execute: send_data_to_server

http_request:
  timeout: 5s
  verify_ssl: false
  id: send_data_url


script:
  - id: send_data_to_server
    then:
      - if:
          condition:
            lambda: 'return id(send_rp5) == 1 && !id(rp5_key).state.empty();'
          then:
            - if:
                condition:
                  lambda: 'return id(activation_status).state == "Activated";'
                then:
                  - logger.log:
                      format: "*****   Sending Data   *****"
                      level: INFO
                      tag: "LOG"     
                  - http_request.post:
                      id: send_data_url
                      url: !lambda |-
                            std::string url = "http://sgate.rp5.ru/?";

                            if (!std::isnan(id(bme_temperature).state)) {
                                url += "T=" + std::to_string(id(bme_temperature).state);
                            }
                            if (!std::isnan(id(bme_hum).state)) {
                                url += "&U=" + std::to_string(id(bme_hum).state);
                            }
                            if (!std::isnan(id(wind_direction_sensor).state)) {
                                url += "&DD=" + std::to_string(static_cast<int>(id(wind_direction_sensor).state));
                            }
                            if (!std::isnan(id(wspeed).state)) {
                                url += "&FF=" + std::to_string(id(wspeed).state);
                            }
                            url += "&updated=" + std::to_string(static_cast<int>(id(unix_time_sensor).state));
                            url += "&api_key=" + id(rp5_key).state;

                            return url;
                      on_response:
                        then:
                          - lambda: |-
                              float duration_seconds = response->duration_ms / 1000.0;  
                              if (response->status_code == 200) {
                                ESP_LOGI("LOG", "Send data, code: %d, Time: %.3f s", response->status_code, duration_seconds);
                              }
```

### Anything in the logs that might be useful for us?

```txt
[15:10:10][I][LOG:1471]: *****   Sending data to server   *****
[15:10:10][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
[15:10:10][V][json:058]: Size after shrink 148 bytes
WARNING base-device @ 10.10.0.136: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for base-device @ 10.10.0.136
WARNING Disconnected from API
INFO Successfully connected to base-device @ 10.10.0.136 in 0.004s
INFO Successful handshake with base-device @ 10.10.0.136 in 0.081s
```

### Additional information

As can be seen from the logs, an attempt to send data is launched and the device immediately reboots.
