### ISSUE TITLE
[lvgl] bg_image_src

### ISSUE THREAD

**Issue by ok5max** [esphome/issues#6698]
### The problem

Attribute **bg_image_src** does not display the background image. In esphome version 2024.11.2 it worked. Now I have only white background.

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.5

### What platform are you using?

ESP32-IDF

### Board

ESP32-S3

### Component causing the issue

lvgl

### YAML Config

```yaml
image:
  - file: "images/background.png"
    id: img_background
    type: RGB565

lvgl:
  displays:
    - main_display
  touchscreens:
    - main_touch
  pages:
    - id: main_page
      bg_image_src: img_background
      bg_image_opa: 35% #35%
      scrollbar_mode: "OFF"
      scrollable: false
      widgets:
        - obj:
            border_opa: TRANSP
            bg_opa: TRANSP
            align: CENTER
            width: 480
            height: 345
            #pad_all: 10
            scrollable: false
            layout:
              pad_column: 0
              type: GRID
              grid_rows: [FR(60),FR(40),FR(70),FR(20),FR(60),FR(40),FR(70),FR(20),FR(20)]
              grid_columns: [FR(220),FR(20),FR(220)]
            widgets:
...
```

### Anything in the logs that might be useful for us?

```txt

```
