### ISSUE TITLE
lcd_pcf8574 Display platform suddenly scrolling text after latest ESPHome Update

### ISSUE THREAD

**Issue by Routhinator** [esphome/issues#6703]
### The problem

I have a few ESP32 sensor units that have LCDs on them and I use the `lcd_pcf8574` module to create a static, non scrolling display for them.

This is the code that has worked for 1 year:

```yaml
# LCD Configuration
display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    update_interval: 2s
    setup_priority: -100
    id: main_display
    user_characters:
      - position: 0
        data:
          - 0b01110
          - 0b11011
          - 0b10001
          - 0b11111
          - 0b11111
          - 0b11111
          - 0b11111
          - 0b11111
      - position: 1
        data:
          - 0b00100
          - 0b00100
          - 0b01010
          - 0b01010
          - 0b10001
          - 0b11111
          - 0b11111
          - 0b01110
      - position: 2
        data:
          - 0b01110
          - 0b01010
          - 0b01010
          - 0b01110
          - 0b01110
          - 0b11111
          - 0b11111
          - 0b01110
      - position: 3
        data:
          - 0b00000
          - 0b01110
          - 0b10011
          - 0b10101
          - 0b10001
          - 0b01110
          - 0b00000
          - 0b00000
      - position: 4
        data:
          - 0b00000
          - 0b00000
          - 0b00001
          - 0b00010
          - 0b10100
          - 0b01000
          - 0b00000
          - 0b00000
    lambda: |-
      it.printf(0, 0, "%s%6.1f %s", "\x03", id(pressure).state, "hPa");
      it.printf(0, 1, "%s: %5.0f%s", "CO2", id(co2).state, "ppm");
      it.printf(0, 2, "%s: %5.0f", "IAQ", id(iaq).state);
      it.printf(13, 0, "%s%5.1f%s", "\x08", 100.0, "%");
      it.printf(13, 1, "%s%5.1f%s", "\x01", id(humidity).state, "%");
      it.printf(13, 2, "%s%5.1f%s", "\x02", id(temperature).state, "C");
      it.printf(0, 3, "%s%s %s", "IAQ", "\x04", id(iaq_accuracy).state.c_str());
```

Yesterday I updated ESPHome and the firmware build for 2024.12.4, and suddenly, all the text on the screen is marqueed, scrolling and looks like hell. I cannot find any release notes or documentation that state this should be happening or why it might be happening, so I presume something was broken here.

There were no compilation errors, just this strangely broken behaviour.. 

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.3

### What platform are you using?

ESP32

### Board

KeeYees NodeMCU ESP32

### Component causing the issue

lcd_pcf8574

### YAML Config

```yaml
substitutions:
  name: esp32-sensor-pack-chris-office
  friendly_name: Chris' Office Sensor Pack

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.sensor_pack
    version: '1.0-dev'
  on_boot:
    then:
      - lambda: |-
          id(main_display).no_backlight();
      - binary_sensor.template.publish:
          id: backlight
          state: OFF

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "e3c1eALtQEtlvdYmZVpkWXHrjilTCXII8MMfnPE31rk="

# Allow Over-The-Air updates
ota:
  platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:


dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5dB
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp32-sensor-pack-chris-office"
    password: "dUyvPkjUDmDr"

captive_portal:

# i2c addresses
i2c:
  scl: GPIO22
  sda: GPIO21
  scan: false

# Sensors config
sensor:
  - platform: bme680_bsec
    temperature:
      name: "Temperature"
      id: temperature
    pressure:
      name: "Pressure"
      id: "pressure"
    humidity:
      name: "Humidity"
      id: humidity
    iaq:
      name: "Indoor Air Quality"
      id: iaq
    co2_equivalent:
      name: "CO2 Equivalent"
      id: co2
    breath_voc_equivalent:
      name: "Breath VOC Equivalent"
      id: breath_voc
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 60s
  - platform: template
    name: "Altitude"
    icon: "mdi:image-filter-hdr"
    lambda: |-
      return 36;
    id: "altitude"
    unit_of_measurement: "m"
    device_class: ""
    state_class: "measurement"
    accuracy_decimals: 0
  # BLE Device List for Tracking
  - platform: ble_rssi
    ibeacon_uuid: 64001c56-b667-464c-9f0b-da6144c38e39
    name: "Chris Pixel 7 Pro BLE RSSI value"

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "Indoor Air Quality Accuracy"
      id: iaq_accuracy

  - platform: template
    name: "Indoor Air Quality Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    id: iaq_classification
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO27
      inverted: true
      mode:
        input: true
        pullup: true
    name: "LCD Button"
    filters:
      - delayed_on: 100ms
    on_press:
      then:
        - binary_sensor.template.publish:
            id: backlight
            state: ON
        - binary_sensor.template.publish:
            id: backlight
            state: OFF
  - platform: template
    id: backlight
    name: "LCD Backlight"
    filters:
      - delayed_off: 60s
    on_press:
      then:
        - lambda: |-
            id(main_display).backlight();
    on_release:
      then:
        - lambda: |-
            id(main_display).no_backlight();
  - platform: gpio
    pin: 
      number: GPIO26
    name: "PIR Sensor"
    filters: 
      - delayed_off: 10s
    device_class: motion
  - platform: gpio
    pin: 
      number: GPIO25
    name: "Microwave Sensor"
    filters: 
      - delayed_off: 10s
    device_class: motion

# BSEC BME680 Configuration
bme680_bsec:
    # id
    # -----------
    # Identifier for this component, useful when working with multiple devices.
    # Must be unique, and can be used in the sensor sections to refer to the correct device.
    # Default: auto-computed
    id: bme680_internal

    # i2c address
    # -----------
    # Common values are:
    # - 0x76
    # - 0x77
    # Default: 0x76
    address: 0x77

    # Temperature offset
    # ------------------
    # Useful if device is in enclosure and reads too high
    # For example, if it reads 5C too high, set this to 5
    # This also corrects the relative humidity readings
    # Default: 0
    temperature_offset: 3

    # IAQ calculation mode
    # --------------------
    # Available options:
    # - static (for fixed position devices)
    # - mobile (for on a person or other moveable devices)
    # Default: static
    iaq_mode: static

    # Sample rate
    # -----------
    # Available options:
    # - lp (low power - samples every 3 seconds)
    # - ulp (ultra-low power - samples every 5 minutes)
    # Default: lp
    sample_rate: lp

    # Interval at which to save BSEC state
    # ------------------------------------
    # Default: 6h
    state_save_interval: 6h

# LCD Configuration
display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    update_interval: 2s
    setup_priority: -100
    id: main_display
    user_characters:
      - position: 0
        data:
          - 0b01110
          - 0b11011
          - 0b10001
          - 0b11111
          - 0b11111
          - 0b11111
          - 0b11111
          - 0b11111
      - position: 1
        data:
          - 0b00100
          - 0b00100
          - 0b01010
          - 0b01010
          - 0b10001
          - 0b11111
          - 0b11111
          - 0b01110
      - position: 2
        data:
          - 0b01110
          - 0b01010
          - 0b01010
          - 0b01110
          - 0b01110
          - 0b11111
          - 0b11111
          - 0b01110
      - position: 3
        data:
          - 0b00000
          - 0b01110
          - 0b10011
          - 0b10101
          - 0b10001
          - 0b01110
          - 0b00000
          - 0b00000
      - position: 4
        data:
          - 0b00000
          - 0b00000
          - 0b00001
          - 0b00010
          - 0b10100
          - 0b01000
          - 0b00000
          - 0b00000
    lambda: |-
      it.printf(0, 0, "%s%6.1f %s", "\x03", id(pressure).state, "hPa");
      it.printf(0, 1, "%s: %5.0f%s", "CO2", id(co2).state, "ppm");
      it.printf(0, 2, "%s: %5.0f", "IAQ", id(iaq).state);
      it.printf(13, 0, "%s%5.1f%s", "\x08", 100.0, "%");
      it.printf(13, 1, "%s%5.1f%s", "\x01", id(humidity).state, "%");
      it.printf(13, 2, "%s%5.1f%s", "\x02", id(temperature).state, "C");
      it.printf(0, 3, "%s%s %s", "IAQ", "\x04", id(iaq_accuracy).state.c_str());

# Bluetooth Tracker          
esp32_ble_tracker:
```

### Anything in the logs that might be useful for us?

```txt
No errors
```
