### ISSUE TITLE
Graph control does not respect displays with  transform:   swap_xy: true

### ISSUE THREAD

**Issue by raymondjstone** [esphome/issues#6711]
### The problem

Graph control does not respect displays with  transform:   swap_xy: true

Graph does not render correctly when axis of display are swapped

### Which version of ESPHome has the issue?

2025.1.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1

### What platform are you using?

ESP32

### Board

CYB

### Component causing the issue

Graph

### YAML Config

```yaml
# Display is used as 240x320 by default so we rotate it to 90°
display:
  - platform: ili9xxx
    model: ili9341
    invert_colors: false
    spi_id: tft
    cs_pin: GPIO15
    dc_pin: GPIO2
    transform:
      swap_xy: true
    dimensions:
      width: 320
      height: 240
    id: my_display
    pages:
      - id: page1
        lambda: |-
          it.fill(id(Color::BLACK));
      - id: page2
        lambda: |-
          it.graph(10, 10, id(multi_temperature_graph));
```

### Anything in the logs that might be useful for us?

```txt

```
