### ISSUE TITLE
VL53l1x Does not read values. Sensor is OK (Tested with Arduino Nano)

### ISSUE THREAD

**Issue by Tokn59** [esphome/issues#6713]
### The problem

The sensor is not read. The sensor is detected by I2C bus but no readings are gotten from the sensor.

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

ESP32-C3-MINI

### Component causing the issue

VL53 Sensor

### YAML Config

```yaml
esphome:
  name: esphome-web-04a320
  friendly_name: ESP32_C3_TOF
  min_version: 2024.11.0
  name_add_mac_suffix: false

  libraries:
    - "Wire"
    - "VL53L1x"

  includes:
  - tof_vl53l1x.h

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    
    

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
  ap:
    ssid: "Air Quality Fallback Hotspot"
    password: !secret ap_password 
  
web_server:
  port: 80

captive_portal:


i2c:
  sda: GPIO08
  scl: GPIO10
  scan: True  
  frequency: 400kHz

# Example configuration entry
font:
  - file: "fonts/arial.ttf"
    id: arial12
    size: 12
  - file: "fonts/Orbitron Bold.ttf"
    id: orbitronb
    size: 48   
  - file: "fonts/Orbitron Bold.ttf"
    id: orbitronbs
    size: 36     


# Simple configuration entry example
sensor:
  - platform: vl53l0x
    name: "VL53L0x Distance"
    address: 0x29
    update_interval: 60s
    timeout: 200us
    long_range: true
    id: distance
    unit_of_measurement: "m"

display:
  - platform: ssd1306_i2c
    model: "SSD1306_128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(arial12), "Distance:");   
      it.printf(0, 2, id(arial12), TextAlign::TOP_CENTER , "%.0f", id(distance).state);
#it.printf(150, 145, id(orbitronb), TextAlign::TOP_CENTER , "%.0f", id(dht11_hum).state);
```

### Anything in the logs that might be useful for us?

```txt
I tried using different libraries:

https://github.com/soldierkam/vl53l1x_sensor
https://github.com/pololu/vl53l1x-arduino

Same results
```

### Additional information

THANKS FOR YOUR HELP !!!!!
