### ISSUE TITLE
Deep_sleep wake_up pin and  same pin for adc

### ISSUE THREAD

**Issue by fran6120** [esphome/issues#6720]
### The problem

First of all I don't know if it's a bug or something fixable by code or it's a hardware limitation.

I have an adc platform sensor configured on GPIO4 of an esp32-c3. In raw mode I get an approximate value of about 3700.

If I configure the deep_sleep component with the wake_pin function sharing GPIO4 with the option allow_other_uses: true, in the adc sensor in raw mode I get an approximate value of about 1500.

I understand that the pin sharing between adc and deep_sleep is interfering.

Could the wake_up pin be configured in the esp32 shutdown routine just before entering deep_sleep? And at power-up, configure it only for adc?

Sorry if what I'm saying is nonsense.

Thank you very much.

``` yaml
deep_sleep:
  id: control_deep_sleep
  wakeup_pin: 
    number: GPIO4
    allow_other_uses: true
  wakeup_pin_mode: IGNORE

  - platform: adc 
    pin: 
      number: GPIO4
      allow_other_uses: true
    name: ADC Capacitivo
    id: "sensor_lluvia_tarar"
    icon: mdi:resistor-nodes
    attenuation: 12db
    raw: true
    samples: 10
    accuracy_decimals: 0
    unit_of_measurement: "adc"
    setup_priority: 599
    update_interval: 0ms
    filters:
      - delta: 40
```

### Which version of ESPHome has the issue?

2024.12.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32-c3

### Component causing the issue

deep_sleep

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```
