### ISSUE TITLE
RF Component not Valid

### ISSUE THREAD

**Issue by AquaMCU** [esphome/issues#673]
DOCKER

ESP8266 D1 mini

**Affected component:**

remote_transmitter.transmit_rc_switch_raw Action

**Description of problem:**
The validation of the code shows errors. 

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: outside
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "XXX"
  password: "XXX"

logger:

api:
  password: 'XXX'

ota:
  password: 'XXX'

remote_transmitter:
  pin: D0
  carrier_duty_percent: 100%
  
switch:
  - platform: template
    name: RF
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
        code: '000000000000000000010101'
        protocol: 1
        
web_server:
  port: 80

```

**Logs (if applicable):**

```
INFO Reading configuration...
Failed config

switch.template: [source /config/outside.yaml:22]
  platform: template
  name: RF
  turn_on_action:  [source /config/outside.yaml:25]
    
    'then' is a required option for [0].
    - [source /config/outside.yaml:25]
      
      [remote_transmitter.transmit_rc_switch_raw] is an invalid option for [0]. Please check the indentation.
      remote_transmitter.transmit_rc_switch_raw: 
      
      [code] is an invalid option for [0]. Please check the indentation.
      code: 000000000000000000010101
      
      [protocol] is an invalid option for [0]. Please check the indentation.
      protocol: 1
```

**Additional information and things you've tried:**
Tried to change indents introduced then but nothing works.
All examples are not using the then.

**Comment by glmnet** [comment]
You need to indent `code` and `protocol`

```yaml
switch:
  - platform: template
    name: RF
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '000000000000000000010101'
          protocol: 1
```
