### ISSUE TITLE
Extremely long (1000ms) timeout stalling loop with SHT4X component when sensor is NOT Connected.

### ISSUE THREAD

**Issue by ESP32andmore** [esphome/issues#6733]
### The problem

Extremely long (1000ms) timeout stalling loop with SHT4X component when sensor is NOT Connected. Sensor should be marked offline at I2C scan without attempts to read or write to the device in the "loop" when sensor is not connected and not found in boot scan.

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.0

### What platform are you using?

ESP32

### Board

ESP32andmore ECB (ESP32-WROOM)

### Component causing the issue

SHT40

### YAML Config

```yaml
i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True
    frequency: 400khz
  - id: bus_b
    sda: GPIO16
    scl: GPIO17
    scan: True
    frequency: 800khz

sensor:
  - platform: sht4x
    i2c_id: bus_a
    address: 0x44
    heater_max_duty: 0.00
    heater_power: "Low"
    heater_time: "Short"
    update_interval: 2s
    temperature:
      name: ${fdevicename}SHT40 Temp
      id: SHT40T
      filters:
        - filter_out: NaN
        - filter_out: nan
        - offset: 0.0
      icon: mdi:thermometer

    humidity:
      name: ${fdevicename}SHT40 Humidity
      id: SHT40H
      filters:
        - filter_out: NaN
        - filter_out: nan
        - offset: 0.0
      icon: mdi:humidity
```

### Anything in the logs that might be useful for us?

```txt
[23:12:40][365344][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263
[23:12:40][D][sht4x:080]: Sensor read failed
[23:12:40][W][component:237]: Component sht4x.sensor took a long time for an operation (1006 ms).
[23:12:40][W][component:238]: Components should block for at most 30 ms.
```
