### ISSUE TITLE
Ethernet + Touchscreen (I2C)

### ISSUE THREAD

**Issue by pixelwave** [esphome/issues#6735]
### The problem

I am trying to get my [Lilygo T-ETH ELite](https://lilygo.cc/products/t-eth-elite-1?_pos=1&_sid=f48f6a5fc&_ss=r&variant=44498204983477) running in combination with a [1.69" WAVESHARE Touchscreen](https://www.waveshare.com/1.69inch-touch-lcd-module.htm).

After a ton of troubleshooting I got this far that the touchscreen is working, shows an image and the touch also works with coordinate feedback in the logs.

But only when using WIFI. As soon as I comment the WIFI block and uncomment the `ethernet:` part the touch does not work anymore. I get no touch coordinate output in the logs. 

Is there an ethernet-specific implementation issue that conflicts with i2c touch? What I can see in the logs when using `ethernet:` are some conflicts with the interrupt service?

I attached ethernet and wifi log output.

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

Lilygo T-ETH ELite (ESP32S3) + 1.69" WAVESHARE Touchscreen

### Component causing the issue

ethernet

### YAML Config

```yaml
# Display Bench

# Lilygo T-ETH ELITE ESP32-S3
# ->  PINs available
#     1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 
#     15, 16, 17, 18, 38, 39, 40, 41, 42, 46

substitutions:
  comment: 'Lilygo TElite + 1.69" Touchscreen'
  device_name: sbx-display-bench
  friendly_name: (SBX) Display Bench
  # DISPLAY 
  LCD_DIN: GPIO11 # MOSI -> IO9 and IO11 are labelled WRONG!
  LCD_CLK: GPIO10
  LCD_CS: GPIO40
  LCD_DC: GPIO41
  LCD_RST: GPIO13
  LCD_BL: GPIO2
  # TOUCH
  TP_SDA: GPIO17
  TP_SCL: GPIO18
  TP_RST: GPIO4
  TP_IRQ: GPIO7
  # GREEN ONBOARD LED
  GREEN_LED: GPIO38

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${comment}

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

# Example configuration entry
psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger: # level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
- platform: esphome
  password: "..."

# # Ethernet (T-ETH-ELite)
# ethernet:
#   type: W5500
#   clk_pin: GPIO48
#   mosi_pin: GPIO21
#   miso_pin: GPIO47
#   cs_pin: GPIO45
#   interrupt_pin: GPIO14
#   #reset_pin: GPIOXX

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sbx-Display-Bench"
    password: "..."

captive_portal:

# ############################################## #

# + DISPLAY CONFIGURATION ---------------------- #

# SPI Bus Configuration
spi:
  clk_pin: ${LCD_CLK} # New pin for SPI CLK
  mosi_pin: ${LCD_DIN} # New pin for SPI MOSI
  interface: spi3

# ILI9xxx Display configuration
display:
- platform: ili9xxx
  model: ST7789V
  id: display1
  cs_pin: ${LCD_CS} # Chip Select
  dc_pin: ${LCD_DC} # Data/Command
  reset_pin: ${LCD_RST} # Reset
  rotation: 0 # Orientation -> Portrait
  invert_colors: true # Set to true if colors are inverted
  color_order: rgb
  #show_test_card: true       # Displays a test card for debugging
  auto_clear_enabled: false # for lvgl
  #data_rate: 80MHz
  dimensions:
    width: 240
    height: 280
    offset_height: 20

# - DISPLAY CONFIGURATION ---------------------- #

# + TOUCH CONFIGURATION ------------------------ #

# I2C Bus for Touchscreen
i2c:
  id: bus_touch
  sda: ${TP_SDA} # TP SDA
  scl: ${TP_SCL} # TP SCL
  #scan: true  # Optional: to detect the touchscreen on the I²C bus

  # Touchscreen Configuration
touchscreen:
- platform: cst816
  id: my_touchscreen
  display: display1
  i2c_id: bus_touch # Explicitly assign the correct I2C bus
  #skip_probe: true
  #address: 0x15  # Replace with the detected address
  interrupt_pin: ${TP_IRQ} # TP INT
  reset_pin: ${TP_RST} # TP RST
  on_touch:
    then:
    # calibrate touch
    - lambda: |-
        ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
            touch.x,
            touch.y,
            touch.x_raw,
            touch.y_raw
            );

# - TOUCH CONFIGURATION ------------------------ #

# ############################################## #


# ########################################## #
# + GUI CONFIGURATION ---------------------- #

# FONT Configuration
font:
- file: "gfonts://Roboto@700"
  id: font_value_small
  size: 35
  glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/\\[]|&@#'"
  bpp: 4
- file: "gfonts://Roboto@700"
  id: font_value_big
  size: 50
  glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/\\[]|&@#'"
  bpp: 4

# LVGL Configuration
lvgl:

  # BASE
  disp_bg_color: 0x0 # Base Background Color

  # Page Definitions
  pages:
  # PAGE: Relay Control
  - id: p_main
    bg_color: 0x0
    widgets:

    # Test Image
    - image:
        #align: CENTER
        src: img_test2
        x: 0
        y: 0
        width: 240
        height: 280

image:
# Test Image
- file: "assets/waveshare/test.png"
  id: img_test
  type: RGB565
  resize: 240x280
# Test Image
- file: "assets/waveshare/esp32.png"
  id: img_test2
  type: RGB565
  resize: 240x280

# - GUI CONFIGURATION ---------------------- #
# ########################################## #


# Define a PWM output on the ESP32
output:
- platform: ledc
  pin: ${LCD_BL}
  id: backlight_pwm
- platform: gpio
  pin: ${GREEN_LED}
  id: led_output

# Define a monochromatic, dimmable light for the backlight
light:
- platform: monochromatic
  output: backlight_pwm
  name: "Display Backlight"
  id: back_light
  restore_mode: ALWAYS_ON
- platform: binary
  name: "Green LED (IO38)"
  output: led_output
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

[ethernet_logs.txt](https://github.com/user-attachments/files/18717456/ethernet_logs.txt)
[wifi_logs.txt](https://github.com/user-attachments/files/18717455/wifi_logs.txt)

**Comment by pixelwave** [comment]
GPIO Interrupt Conflict (?) ..the error:
`[14:32:53][E][esp32:068]: attach_interrupt(): call to gpio_install_isr_service() failed, error code: 259`

.. suggests that ESPHome is failing to attach an interrupt service routine (ISR) for my touchscreen.

This might be because the Ethernet driver is using or reserving the same GPIO interrupt system?  Is there something like a limit of interrupt pins useable?

_"Ensure that you have enough available IRQ channels to use. If you've already installed ISRs for other GPIOs, you may have hit the limit. Check if any other resources are using GPIO interrupts and make sure they're being properly released."_

- Ethernet IRQ is PIN14

- I2C Touch IRQ is PIN7

**Comment by pixelwave** [comment]
**Root Cause**

The primary issue is an interrupt service conflict between the Ethernet W5500 (using GPIO14 for its interrupt) and the CST816 touchscreen (using GPIO7 for its interrupt). The ESP32-S3’s GPIO interrupt service can only be installed once per core, and Ethernet’s initialization preempts the touchscreen’s interrupt setup, resulting in the error gpio_install_isr_service(500): GPIO isr service already installed.

**Comment by pixelwave** [comment]
Now I tried to switch the ethernet component from interrupt to polling mode:

```
ethernet:
  type: W5500
  clk_pin: GPIO48
  mosi_pin: GPIO21
  miso_pin: GPIO47
  cs_pin: GPIO45
  #interrupt_pin: GPIO14
  reset_pin: GPIO13
  polling_interval: 10ms  # Polling every 10 ms, adjust as needed
```

The expectation was that switching to polling_interval would remove the need for the W5500’s interrupt (GPIO14) and thus prevent the gpio_install_isr_service from being installed by Ethernet, allowing the touchscreen’s interrupt (GPIO7) to attach. However, the logs show that gpio_install_isr_service is still being installed, causing the conflict:

```
[08:37:43][D][esp-idf:000]: E (1849) gpio: gpio_install_isr_service(500): GPIO isr service already installed
[08:37:43]
[08:37:43][E][esp32:068]: attach_interrupt(): call to gpio_install_isr_service() failed, error code: 259
[08:37:43][D][touchscreen:016]: Attach Touch Interupt
[08:37:43][C][cst816.touchscreen:037]: CST816 Touchscreen setup complete
```
