### ISSUE TITLE
Misleading error message with multiple scripts

### ISSUE THREAD

**Issue by asteinarson** [esphome/issues#6738]
### The problem

I got the error message: 
```
script: [source esp32-issue.yaml:362]
    'id' is a required option for [script].
```

in the case where the script very clearly has an ID: 
```
script:
  - id: reset_gussbo_shunt_pos
    parameters:
      pos: int
    then: # ... 
```

The real error was a misplaced action, several scripts down in the source, I show the issue here: 
```
  - id: iterate_gussbo_shunt_pos
    parameters:
      old_ratio: float 
    lambda: !lambda "old_ratio = id(gussbo_shunt_ratio).state"  # <---- This line ! 
    then:
      if:
```

So there was a config error (an action placed outside of the `then` block (the lambda above). 

However, a misplaced action in one script is a different thing to a missing ID in another script (which was reported - an false). 

The offending line is #423 in the YAML file. 

Agreeably not a big error - but a misleading error message it is :-) 

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.8

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

config parser

### YAML Config

```yaml
esphome:
  name: esp32-shunt

esp32:
  board: esp32doit-devkit-v1

i2c:
  sda: GPIO21 #GPIO18
  scl: GPIO22 #GPIO19
  scan: true
  id: bus_a

ads1115:
  - address: 0x48
    id: ads1115_48 
  - address: 0x49
    id: ads1115_49 

sensor:
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    name: "A0_GND_48"
    id: A0_GND_48
    ads1115_id: ads1115_48 
    update_interval: 5s

  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 4.096
    name: "A1_GND_48"
    id: A1_GND_48
    ads1115_id: ads1115_48 
    update_interval: 5s

  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 4.096
    name: "A2_GND_48"
    id: A2_GND_48
    ads1115_id: ads1115_48 
    update_interval: 5s

  - platform: ads1115
    multiplexer: 'A3_GND'
    gain: 4.096
    name: "A3_GND_48"
    id: A3_GND_48
    ads1115_id: ads1115_48 
    update_interval: 5s

  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    name: "A0_GND_49"
    id: A0_GND_49
    ads1115_id: ads1115_49 
    update_interval: 5s 

  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 4.096
    name: "A1_GND_49"
    id: A1_GND_49
    ads1115_id: ads1115_49 
    update_interval: 5s 

  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 4.096
    name: "A2_GND_49"
    id: A2_GND_49
    ads1115_id: ads1115_49 
    update_interval: 5s 

  - platform: ads1115
    multiplexer: 'A3_GND'
    gain: 4.096
    name: "A3_GND_49"
    id: A3_GND_49
    ads1115_id: ads1115_49 
    update_interval: 5s 


  - platform: resistance
    id: resistance_a0_49
    sensor: A0_GND_49
    configuration: UPSTREAM
    resistor: 9.91kOhm
    name: Resistance NTC A0-49

  - platform: ntc
    sensor: resistance_a0_49
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    id: t_het_ror
    name: Temp het rör 
    filters:
      - exponential_moving_average:
          alpha: 0.3
          send_every: 10 


  - platform: resistance
    id: resistance_a1_49
    sensor: A1_GND_49
    configuration: UPSTREAM
    resistor: 9.91kOhm
    name: Resistance NTC A1-49

  - platform: ntc
    sensor: resistance_a1_49
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    id: t_fram_gs
    name: T fram GS 
    filters:
      - exponential_moving_average:
          alpha: 0.3
          send_every: 10 


  - platform: resistance
    id: resistance_a2_49
    sensor: A2_GND_49
    configuration: UPSTREAM
    resistor: 9.91kOhm
    name: Resistance NTC A2-49

  - platform: ntc
    sensor: resistance_a2_49
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    id: t_fram_gussbo
    name: T fram Gussbo 
    filters:
      - exponential_moving_average:
          alpha: 0.3 
          send_every: 10


  - platform: resistance
    id: resistance_a3_49
    sensor: A3_GND_49
    configuration: UPSTREAM
    resistor: 9.91kOhm
    name: Resistance NTC A2-49

  - platform: ntc
    sensor: resistance_a3_49
    calibration:
      b_constant: 3950   
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    id: t_retur
    name: T retur
    filters:
      - exponential_moving_average:
          alpha: 0.3 
          send_every: 10


  - platform: resistance
    id: resistance_a0_48
    sensor: A0_GND_48
    configuration: UPSTREAM
    resistor: 9.91kOhm
    name: Resistance NTC A0-48

  - platform: ntc
    sensor: resistance_a0_48
    calibration:
      b_constant: 3950   
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    id: t_tank_hot
    name: T tank hot (3)
    filters:
      - exponential_moving_average:
          alpha: 0.3 
          send_every: 10


  - platform: resistance
    id: resistance_a1_48
    sensor: A1_GND_48
    configuration: UPSTREAM
    resistor: 9.91kOhm
    name: Resistance NTC A1-48

  - platform: ntc
    sensor: resistance_a1_48
    calibration:
      b_constant: 3950   
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    id: t_ute
    name: T ute
    filters:
      - exponential_moving_average:
          alpha: 0.3 
          send_every: 10


binary_sensor:
#  - platform: gpio
#    pin: GPIO14
#    name: "in_pump_bdt"
#    id: in_pump_bdt 

#  - platform: gpio
#    pin: GPIO12
#    name: "in_pump_u"
#    id: in_pump_u

switch:
  - platform: gpio
    pin: GPIO14
    name: "out_gussbo_open"
    id: out_gussbo_open
    interlock: [out_gussbo_close]

  - platform: gpio
    pin: GPIO27
    name: "out_gussbo_close"
    id: out_gussbo_close
    interlock: [out_gussbo_open]

  - platform: gpio
    pin: GPIO26
    name: "out_gs_open"
    id: out_gs_open
    interlock: [out_gs_close]

  - platform: gpio
    pin: GPIO25   
    name: "out_gs_close"
    id: out_gs_close
    interlock: [out_gs_open]

  - platform: gpio
    pin: GPIO33
    name: "out_gussbo_cp"
    id: out_gussbo_cp

  - platform: gpio
    pin: GPIO32   
    name: "out_gs_cp"
    id: out_gs_cp


globals:
  - id: gussbo_shunt_pos
    type: int
    restore_value: no
    initial_value: '270' # That is fully open 
  - id: gussbo_shunt_delta
    type: int
    restore_value: no
    initial_value: '0'
  - id: gussbo_shunt_range
    type: int
    restore_value: no
    initial_value: '270'

number:
  - platform: template
    name: "Shunt steps"
    id: shunt_steps
    unit_of_measurement: times
    step: 1
    initial_value: 9
    min_value: 2
    max_value: 100
    optimistic: true
    restore_value: true

  - platform: template
    name: "Shunt step delay"
    id: shunt_step_delay
    unit_of_measurement: s
    step: 10
    initial_value: 120
    min_value: 5
    max_value: 600
    optimistic: true
    restore_value: true

  - platform: template
    name: "Gussbo shunt ratio"
    id: gussbo_shunt_ratio
    step: 0.01
    initial_value: 1.0
    min_value: 0.0
    max_value: 1.0
    optimistic: true
    restore_value: true


#  - platform: template
#    name: "Test Result"
#    id: test_result
#    initial_value: 0 
#    optimistic: true   
#    restore_value: false

  - platform: template
    name: "Test Counter"
    id: test_counter
    unit_of_measurement: s
    step: 1
    initial_value: 0
    min_value: -600
    max_value: 600
    optimistic: true
    restore_value: false

  - platform: template
    name: "Real Counter"
    id: real_counter
    unit_of_measurement: s
    step: 1
    initial_value: 0
    min_value: -600
    max_value: 600
    optimistic: true
    restore_value: false


button:
  - platform: template
    name: "Run shunt steps"
    id: run_shunt_steps
    icon: "mdi:emoticon-outline"
    on_press:
      - script.execute: 
          id: set_gussbo_shunt_pos 
          ratio: !lambda "return id(gussbo_shunt_ratio).state - 0.01;"

  - platform: template
    name: "Reset shunt pos to"
    id: reset_shunt_pos
    icon: "mdi:emoticon-outline"
    on_press:
      - script.execute: 
          id: reset_gussbo_shunt_pos 
          pos: !lambda "return id(real_counter).state;"  

script:
  - id: test_script
    then:
      - number.increment: real_counter

  # This will set the SW state of the shunt position.
  # It can be done when knowing the shunt valve is in a certain position ("pos") 
  - id: reset_gussbo_shunt_pos
    parameters:
      pos: int
    then:
      - lambda: |- 
          id(gussbo_shunt_pos) = pos;
      - number.set:
          id: gussbo_shunt_ratio
          value: !lambda "return (float)pos / id(gussbo_shunt_range);"
      - number.set: 
          id: test_counter
          value: !lambda "return id(gussbo_shunt_pos);"

  # This will set the shunt (physically) to the given ration (between 0 and 1). 
  # The SW state for the shunt is updated accordingly 
  - id: set_gussbo_shunt_pos
    mode: queued
    parameters:
      ratio: float # Between 0 and 1
    then:
      - logger.log:
          format: "start: gussbo_shunt_pos: %d   gussbo_shunt_delta: %d" 
          args: ["id(gussbo_shunt_pos)", "id(gussbo_shunt_delta)"]
      - lambda: |-
          int new_pos = int( ratio * id(gussbo_shunt_range) );
          id(gussbo_shunt_delta) = new_pos - id(gussbo_shunt_pos); 
          id(gussbo_shunt_pos) = new_pos;
      - number.set:
          id: gussbo_shunt_ratio
          value: !lambda "return ratio;"
      - logger.log:
          format: "after lambda: gussbo_shunt_pos: %d   gussbo_shunt_delta: %d" 
          args: ["id(gussbo_shunt_pos)", "id(gussbo_shunt_delta)"]
      - if:
          condition: 
            lambda: 'return id(gussbo_shunt_delta)>0;'
          then: 
            #- switch.turn_on: out_gussbo_open 
            - delay: !lambda "return id(gussbo_shunt_delta) * 1000;"
            #- switch.turn_off: out_gussbo_open
          else:
            if:
              condition: 
                lambda: 'return id(gussbo_shunt_delta)<0;'
              then: 
                #- switch.turn_on: out_gussbo_close 
                - delay: !lambda "return -id(gussbo_shunt_delta) * 1000;"
                #- switch.turn_off: out_gussbo_close
      - number.set: 
          id: test_counter
          value: !lambda "return id(gussbo_shunt_pos);"
      - number.set: 
          id: real_counter
          value: !lambda "return id(gussbo_shunt_delta);"
      - logger.log: "set_gussbo_shunt_pos - stop"

  # Loop through shunt positions in increasing or decreasing way
  # Use configuration values for number of steps and delay on each step
  - id: iterate_gussbo_shunt_pos
    parameters:
      old_ratio: float 
    lambda: !lambda "old_ratio = id(gussbo_shunt_ratio).state"
    then:
      # Record old position first 
      if:
        condition: 
          lambda: "return id(gussbo_shunt_ratio).state > 0.5" 
        then:
          # Go to maximum and then iterate backwards 
          - script.execute:
              id: set_gussbo_shunt_pos
              ratio: 1.0 
          - script.execute:
              id: iterate_gussbo_shunt_body 
              increment: !lambda "return -id(gussbo_shunt_range) / id(shunt_steps).state"
        else:
          # Go to minimum and then iterate forwards 
          - script.execute:
              id: set_gussbo_shunt_pos
              ratio: 0.0 
          - script.execute:
              id: iterate_gussbo_shunt_body 
              increment: !lambda "return id(gussbo_shunt_range) / id(shunt_steps).state"

  - id: iterate_gussbo_shunt_body
    then:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: "1guc197"

wifi:
  ssid: "..."
  password: "..."

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Shunt"
    password: "..."

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
# Full error message from the terminal: 

(venv) astein@astein-hp-x2-g4:~/repos/esp/esp32-shunt$ esphome config esp32-issue.yaml
INFO ESPHome 2024.12.4
INFO Reading configuration esp32-issue.yaml...
Failed config

script: [source esp32-issue.yaml:356]
  
  'id' is a required option for [script].
  - 
    Unable to find action with the name 'id'.
    id: test_script
    then: 
      - number.increment: real_counter
  - id: reset_gussbo_shunt_pos
    parameters: 
      pos: int
    then: 
      - lambda: id(gussbo_shunt_pos) = pos;
      - number.set: 
          id: gussbo_shunt_ratio
(venv) astein@astein-hp-x2-g4:~/repos/esp/esp32-shunt$
```
