### ISSUE TITLE
Multiple SDL displays do not handle events properly and touchscreens/binary_sensors aren't configurable

### ISSUE THREAD

**Issue by bdm310** [esphome/issues#6745]
### The problem

**Problem**
When defining multiple SDL displays, each display ends up with its own event handler that gets called in the update loop. Depending on when events occur and which instance of the display class calls `SDL_PollEvent` first, a different instance actually processes the event. Usually this is the first window created, but not always. Since it is the first window usually, the second window input sort of doesn't ever work. Also, the event loop doesn't distinguish between events on different windows so touch events happen on all windows at the same location if you click in any one window.

A related issue is that when multiple SDL displays are defined, you get a "Too many candidates" error as the `CONF_SDL_ID` code for touchscreens is sort of assuming you will only have one display. You can work around this by defining sdl_id explicitly in those config blocks but this is undocumented and completely unnecessary as the ID should just be set to the relevant display anyway.

The config issue also arises for the SDL binary_sensor, though this is slightly more difficult to figure a solution out for as encoders (and certainly binary_sensors) aren't mapped directly to displays like touchscreens are.

**Potential Solutions**
Determining if input happened on any particular window is easy with `e.window.windowID == SDL_GetWindowID(this->window_)`. This nearly directly solves the multiple touch input issue, though you still have the multiple event loops race condition happening. It would seem that the SDL objects would need a refactor to have a single, global event loop that can then distribute out events to all the windows. This is how SDL is expecting to be used anyway.

Touchscreens should link `CONF_SDL_ID` directly to whatever display they're attached to.

binary_sensors could be handled by treating the keyboard events as global and ignoring what window they're actually entered on. This seems like a fine approach in the short term as there is no other form of keyboard input anyway.

I started in on this and realized that a refactor over to a single event loop is a bit outside my knowledge scope at the moment and also not relevant to the work I'm trying to get done.

### Which version of ESPHome has the issue?

2025.2.0-dev

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### YAML Config

```yaml
esphome:
  name: sdl

host:

logger:

display:
  - platform: sdl
    id: disp0
    dimensions:
      width: 320
      height: 320
    auto_clear_enabled: false 
  - platform: sdl
    id: disp1
    dimensions:
      width: 640
      height: 640
    auto_clear_enabled: false 

touchscreen:
  - platform: sdl
    id: touch0
    display: disp0
    sdl_id: disp0

  - platform: sdl
    id: touch1
    display: disp1
    sdl_id: disp1

binary_sensor:
  - platform: sdl
    id: key_up1
    key: SDLK_a
    sdl_id: disp0
  - platform: sdl
    id: key_down1
    key: SDLK_d
    sdl_id: disp0
  - platform: sdl
    id: key_enter1
    key: SDLK_s
    sdl_id: disp0

  - platform: sdl
    id: key_up2
    key: SDLK_j
    sdl_id: disp1
  - platform: sdl
    id: key_down2
    key: SDLK_l
    sdl_id: disp1
  - platform: sdl
    id: key_enter2
    key: SDLK_k
    sdl_id: disp1

lvgl:
  #log_level: INFO
  - id: lvgl_0
    displays: disp0

    encoders:
      group: disp0_group
      enter_button: key_enter1
      sensor:
        left_button: key_up1
        right_button: key_down1

    touchscreens:
      touchscreen_id: touch0

    layout:
      type: flex

    widgets:
      - label:
          text: "Hello 1"
      - button:
          group: disp0_group
          widgets:
            - label: 
                text: "Button"
      - button:
          group: disp0_group
          widgets:
            - label: 
                text: "Button"

  - id: lvgl_1
    displays: disp1

    encoders:
      group: disp1_group
      enter_button: key_enter2
      sensor:
        left_button: key_up2
        right_button: key_down2

    touchscreens:
      touchscreen_id: touch1

    layout:
      type: flex

    widgets:
      - label:
          text: "Hello 2"
      - button:
          group: disp1_group
          widgets:
            - label: 
                text: "Button"
      - button:
          group: disp1_group
          widgets:
            - label: 
                text: "Button"
```

### Anything in the logs that might be useful for us?

```txt

```
