### ISSUE TITLE
SPI block after I2C block results in pin mis-config

### ISSUE THREAD

**Issue by bdm310** [esphome/issues#6746]
### The problem

The `external_i2c` bus in the attached config shares the default SPI pins on this board. If you flip the config blocks, putting SPI after I2C, nothing on that bus works. A scope trace shows a correct I2C scan followed by what looks like a long string of clock output on the default SPI_CLK pin.

Haven't tried to find the root cause but it would seem that something about the SPI block causes the default pin config to get messed up even though the SPI lines are moved off the defaults.

Found on an m5stamp-s3.

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp32-s3-devkitc-1

### Component causing the issue

spi

### YAML Config

```yaml
# SPI block must be before I2C otherwise the I2C config gets clobbered and the bus doesn't work
spi:
  id: spi_bus
  mosi_pin: GPIO5
  clk_pin: GPIO6

i2c:
  - id: external_i2c
    sda: GPIO13
    scl: GPIO15
    scan: false
  - id: internal_i2c
    sda: GPIO11
    scl: GPIO12
    scan: false
```

### Anything in the logs that might be useful for us?

```txt

```
