### ISSUE TITLE
Interval component does not delay startup with setting

### ISSUE THREAD

**Issue by WallyDW** [esphome/issues#6751]
### The problem

The startup_delay seems to have no influence on the execution of the component.

I have a startup_delay of 30s now to get my uart up and running (15s was more than enough with the same settings with on_boot).
The interval is set to 5min.
The first detected execution after a boot will be around 5 minutes in.
My guess is that the startup_delay is ignored and there actually is an execution at 0s, which I can not detect because the logger is not online at that time to see it, but it is just a guess.

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.3

### What platform are you using?

ESP32

### Board

ESP32-DevkitC-32E

### Component causing the issue

Interval

### YAML Config

```yaml
esphome:
  name: onkyo
  friendly_name: Onkyo

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
#  baud_rate: 0
  tx_buffer_size: 256
  level: DEBUG

ota:
  - platform: esphome
    password: !secret esphome_ota_pass


wifi:
  output_power: 20db
  fast_connect: true
  ssid: DWsh
  password: !secret dwsh_pass
  manual_ip:
    static_ip: 10.10.12.58
    subnet: 255.255.255.0
    gateway: 10.10.12.1
    dns1: 10.10.12.1

api:
  encryption:
    key: !secret api_key
  services:
    - service: write
      variables:
        command: string
      then:
        - uart.write:
            id: uart_onkyo
            data: !lambda |-
              std::string str = command;
              std::vector<uint8_t> vec(str.begin(), str.end());
              return vec;
        - uart.write:
            id: uart_onkyo
            data: "\r"

uart:
  - id: uart_onkyo
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: NONE
    rx_buffer_size: 128
    tx_pin:
      number: GPIO17
      inverted: false
    rx_pin:
      number: GPIO16
      inverted: false
    debug:
      direction: RX
      dummy_receiver: true
      after:
        bytes: 16
      sequence:
        - lambda: |-
            UARTDebug::log_string(direction, bytes);
            std::string str(bytes.begin(), bytes.end());
            if (str.substr(0,2)=="!1") {
              if (str.substr(2,3)=="PWR") {
                if (str.substr(5,2)=="00") {
                  id(power).publish_state(false);
                }
                if (str.substr(5,2)=="01") {
                  id(power).publish_state(true);
                }
              }
            }

binary_sensor:
  - platform: template
    name: "Power"
    icon: mdi:power
    id: "power"

interval:
  - interval: 5min
    startup_delay: 30s
    then:
      - uart.write:
          id: uart_onkyo
          data: "!1PWRQSTN"
      - uart.write:
          id: uart_onkyo
          data: "\r"
```

### Anything in the logs that might be useful for us?

```txt
Nothing.
I have debug on, so I can see when the uart connection is accessed, but if the is an access attempt before I get the logger online, I do not know.
```
