### ISSUE TITLE
ADC128S102 wrong channel setting

### ISSUE THREAD

**Issue by gkasprow** [esphome/issues#6756]
### The problem

When using ADC128S102 in single channel mode - all works.
But when using 2 or more channels, the results are mixed in some random way, but in the same way until the power cycle.
The issue is caused by wrong control of the channel register. 
The sensor component writes only 2 bytes instead of 4.
In this way it sets che channel for _next_ measurement cycle.
When using only single and the same channel, only first measurement can be wrong, if the channel is not 0; channel 0 is default one.
But when I cycle through channels, while reading result, I set the mux that will be taken into account during next transfer.
This is unlike MCP ADC where same transfer defines measurement channel and gets result.
So the SPI transfer must be done twice, first one sets the channel number, the next one reads results.
I looked into the component codes and there is only single SPI transfer, and this is what I observe on the scope

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.2

### What platform are you using?

ESP32

### Board

own

### Component causing the issue

ADC128S102

### YAML Config

```yaml
# Example configuration entry for ESP32
i2c:
  sda: GPIO33
  scl: GPIO32
  scan: true
  id: bus_a

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO12
  miso_pin: GPIO13

pca9554:
  - id: 'pca9554a_device'
    address: 0x20


# Individual outputs
switch:
  - platform: gpio
    name: "PCF9554A Pin #4"
    pin:
      pca9554: pca9554a_device
      # Use pin number 4
      number: 4
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true

  # Example configuration entry
adc128s102:
  - id: myadc
    cs_pin: GPIO15
    data_rate: 1MHz
    spi_mode: 3
  - id: myadc2
    cs_pin: GPIO2
    data_rate: 1MHz
    spi_mode: 3
  - id: myadc3
    cs_pin: GPIO4
    data_rate: 1MHz
    spi_mode: 3
  - id: myadc4
    cs_pin: GPIO16
    data_rate: 1MHz
    spi_mode: 3
  - id: myadc5
    cs_pin: GPIO17
    data_rate: 1MHz
    spi_mode: 3



sensor:
  - platform: adc128s102           # Attached to pin 0 of the ADC128S102.
    update_interval: 5s
    adc128s102_id: myadc
    id: Temp_room0
    name: "Temp_room0"
    channel: 0                     # ADC128S102 channel    
  - platform: adc128s102           # Attached to pin 0 of the ADC128S102.
    update_interval: 5s
    adc128s102_id: myadc
    id: Temp_room1 
    name: "Temp_room1"
    channel: 1                     # ADC128S102 channel    
  - platform: adc128s102           # Attached to pin 0 of the ADC128S102.
    update_interval: 5s
    adc128s102_id: myadc
    id: Temp_room2
    name: "Temp_room2"
    channel: 2                     # ADC128S102 channel  
  - platform: adc128s102           # Attached to pin 0 of the ADC128S102.
    update_interval: 5s
    adc128s102_id: myadc
    id: Temp_room3 
    name: "Temp_room3"
    channel: 3                     # ADC128S102 channel  
  - platform: adc128s102           # Attached to pin 0 of the ADC128S102.
    update_interval: 5s
    adc128s102_id: myadc
    id: Temp_room4 
    name: "Temp_room4"
    channel: 4          
  - platform: adc128s102
    update_interval: 5s 
    adc128s102_id: myadc
    id: Temp_room5
    name: "Temp_room5"
    channel: 5
  - platform: adc128s102           # Attached to pin 0 of the ADC128S102.
    update_interval: 5s
    adc128s102_id: myadc
    id: Temp_room6 
    name: "Temp_room6"
    channel: 6                     # ADC128S102 channel    
  - platform: adc128s102           # Attached to pin 0 of the ADC128S102.
    update_interval: 5s
    adc128s102_id: myadc
    id: Temp_room7
    name: "Temp_room7"
    channel: 7                     # ADC128S102 channel
```

### Anything in the logs that might be useful for us?

```txt
just swapped values, nothing interesting
```

### Additional information

I wrote readout using lambdas and it works properly

    
# Example configuration entry for ESP32
i2c:
  sda: GPIO33
  scl: GPIO32
  scan: true
  id: bus_a

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO12
  miso_pin: GPIO13

spi_device:
     id: spidev
     cs_pin: GPIO15
     data_rate: 2MHz
     spi_mode: 3
     bit_order: msb_first

pca9554:
  - id: 'pca9554a_device'
    address: 0x20

# Individual outputs
switch:
  - platform: gpio
    name: "PCF9554A Pin #4"
    pin:
      pca9554: pca9554a_device
      # Use pin number 4
      number: 4
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: true

  - platform: gpio
    pin: GPIO2
    id: SPI_IO0
    inverted: true

  - platform: gpio
    pin: GPIO4
    id: SPI_IO1
    inverted: true

  - platform: gpio
    pin: GPIO16
    id: SPI_IO2    
    inverted: true  

  - platform: gpio
    pin: GPIO17
    id: SPI_IO3   
    inverted: true   

sensor:
  - platform: template
    update_interval: 5s
    name: "ADC128S102 Channel 4"
    lambda: |-
      uint16_t command = 0x2000; // Command to read channel 4
      uint16_t response = 0;
      uint16_t raw_value = 0;
      //switch channel
      id(spidev).enable();
      id(spidev).write_byte16(command);
      id(spidev).disable();
      //read measurement
      id(spidev).enable();
      raw_value= ((id(spidev).read_byte() <<8 ) | id(spidev).read_byte())& 0x0FFF;
      id(spidev).disable();
      return raw_value;
  - platform: template
    update_interval: 5s
    name: "ADC128S102 Channel 0"
    lambda: |-
      uint16_t command = 0x0000; // Command to read channel 0
      uint16_t response = 0;
      uint16_t raw_value = 0;
      //switch channel
      id(spidev).enable();
      id(spidev).write_byte16(command);
      id(spidev).disable();
      //read measurement
      id(spidev).enable();
      raw_value= ((id(spidev).read_byte() <<8 ) | id(spidev).read_byte())& 0x0FFF;
      id(spidev).disable();
      return raw_value;
