### ISSUE TITLE
Calibrate Polynom large deviation

### ISSUE THREAD

**Issue by svenwanzenried** [esphome/issues#6757]
### The problem

I have a sensor that i know 16 value pairs that i can use for calibration. I entered those into calibrate_polynom like this:
```
filters:
      - calibrate_polynomial: 
          degree: 15
          datapoints: 
            - 4.912 -> -20
            - 4.847 -> -10
            - 4.745 -> 0
            - 4.593 -> 10
            - 4.379 -> 20
            - 4.096 -> 30
            - 3.746 -> 40
            - 3.336 -> 50
            - 2.910 -> 60
            - 2.474 -> 70
            - 2.062 -> 80
            - 1.692 -> 90
            - 1.373 -> 100
            - 1.107 -> 110
            - 0.888 -> 120
            - 0.714 -> 130
```
when i complile and then go and see the generated code, the calculated coefficients are as follows:

`new sensor::CalibratePolynomialFilter({272.3190044159892f, -491.73498698723415f, 758.1690023562696f, -708.0236399110872f, 367.3716402263235f, -76.49795074844224f, -18.30770521401655f, 13.309207372209585f, -1.561910247966864f, -0.5945074719955947f, 0.19961256847315312f, -0.02166238066555004f, 0.003324484446335152f, -0.0012184545045273963f, 0.00020149738713248462f, -1.1371224259828572e-05f})`

I went to Excel to see this fit, and it turns out to be quite bad as can be seen in following picture:
Picture contains fit for degree of polinomial 4, 10 and 15 (calculated by esphome) and degree 15 calculated by numpy.polyfit()

![Image](https://github.com/user-attachments/assets/10b4025c-2b13-4acc-ba5e-c262fc53636f)

![Image](https://github.com/user-attachments/assets/588e6996-bd71-4a36-a642-9954d3a2baa0)

As you can see, POLY15 calculated by Python is spot-on, while POLY15 deviates quite a lot in the lower value range
Can someone explain to me, why this deviation exists?

### Which version of ESPHome has the issue?

Version: 2024.12.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

esp32 devkit v1

### YAML Config

```yaml
esphome:
  name: esphome-web-58aa88
  friendly_name: ESPHome Solar Temperature
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

sensor:
 
  - platform: adc
    pin: GPIO36
    name: Solar Temperature Roof Voltage
    id: solar_temperature_roof_adc
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 4
    update_interval: 5s
    filters:
      - sliding_window_moving_average: 
          window_size: 12
          send_every: 3
          send_first_at: 3
      - multiply: 4.858  # Multiplication of voltage divider

  - platform: copy
    source_id: solar_temperature_roof_adc
    name: Solar Temperature Roof
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - calibrate_polynomial: 
          degree: 15
          datapoints: 
            - 4.912 -> -20
            - 4.847 -> -10
            - 4.745 -> 0
            - 4.593 -> 10
            - 4.379 -> 20
            - 4.096 -> 30
            - 3.746 -> 40
            - 3.336 -> 50
            - 2.910 -> 60
            - 2.474 -> 70
            - 2.062 -> 80
            - 1.692 -> 90
            - 1.373 -> 100
            - 1.107 -> 110
            - 0.888 -> 120
            - 0.714 -> 130

  - platform: adc
    pin: GPIO39
    name: Solar Temperature Tank
    update_interval: 5s
```

### Anything in the logs that might be useful for us?

```txt

```
