### ISSUE TITLE
802.11 Minimum data rate not being adhered to

### ISSUE THREAD

**Issue by iotola** [esphome/issues#6764]
### The problem

When a wifi access point set a standard minimum data rate of 24 mbit/s I have found that ESP32 do not adhere to it generally dropping to 6 mbit/s. However ESP8266 work as expected sticking to a minimum of 24 mbit/s
I have tried minimum data rates with both arduino and IDF frameworks for ESP32.
Setting `power_save_mode: none` helps but this can only be enabled when a Bluetooth is disabled.

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.4

### What platform are you using?

ESP32

### Board

This effects all ESP32s I have, including nodemcu-32s and ESP32C3

### Component causing the issue

wifi

### YAML Config

```yaml
esphome:
  name: bb
  friendly_name: BB
  platformio_options:
    board_build.flash_mode: dio
  includes:
  - idfWifi.h
  - idfWifi.c

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxx="

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BB"
    password: "xxxxxxxxx"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt

```
