### ISSUE TITLE
Problems displaying negative numbers in PVVX MiThermometer Display - Fixed

### ISSUE THREAD

**Issue by pgolis** [esphome/issues#6765]
### The problem

Negative numbers are not displayed on some systems when using print_bignum and print_smallnum. When the nubmer is negative, on display it is  showed as 0 or 0.1.

### Which version of ESPHome has the issue?

 2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.4

### What platform are you using?

ESP32-IDF

### Board

ESP-WROM-32

### Component causing the issue

PVVX MiThermometer Display

### YAML Config

```yaml
esphome:
  name: lcd-xiaomi
  friendly_name: lcd-xiaomi

esp32:
  board: esp32dev
  framework:
    type: esp-idf  # Switching to ESP-IDF

# Fixed negative numbers
external_components:
  - source: my_components

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "PqUfe4a5mVMI5iEZ7OApTVBUNHpm6eHyYqm3oS4bqlY="


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lcd-Xiaomi Fallback Hotspot"
    password: "AFj6mCxCAY6e"

captive_portal:

sensor:
  - platform: wifi_signal  # Reports the WiFi signal strength in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy  # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

  # Sensors from Home Assistant
  - platform: homeassistant
    id: ha_temperature
    entity_id: sensor.infactory_th_1_175_temperature
    internal: true  # Prevents sending this to HA again

  - platform: homeassistant
    id: ha_humidity
    entity_id: sensor.infactory_th_1_175_humidity
    internal: true

# Enable BLE tracker for ESP-IDF
esp32_ble_tracker:

ble_client:
  - mac_address: 58:2D:34:83:F4:DC
    id: pvvx_ble_display

display:
  - platform: pvvx_mithermometer
    ble_client_id: pvvx_ble_display
    auto_clear_enabled: False
    lambda: |-
      double temp = id(ha_temperature).state;
      double humidity = id(ha_humidity).state * 10;
      it.print_bignum(temp);
      it.print_unit(pvvx_mithermometer::UNIT_DEG_C);
      it.print_smallnum(humidity);
      it.print_percent();
      it.print_battery();
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

I have fixed the issue in `pvvx_mithermometer/display/pvvx_display.h`
Tested with [Qingping Temp & RH Monitor (CGG1-Mijia)](https://pvvx.github.io/CGG1) and [Xiaomi Mijia (LYWSD03MMC)](https://pvvx.github.io/ATC_MiThermometer)

Changed lines are:

```
void print_bignum(float bignum) { this->bignum_ = static_cast<int16_t>(bignum * 10); }
void print_smallnum(float smallnum) { this->smallnum_ = static_cast<int16_t>(smallnum); }
  int16_t bignum_ = 0;
  int16_t smallnum_ = 0;
```

The fixed version is in the attachment: [pvvx_display.zip](https://github.com/user-attachments/files/18851951/pvvx_display.zip)

You can use it in your external component https://esphome.io/components/external_components
