### ISSUE TITLE
ESP01s only in save-mode when using UART GPIO3 for serial

### ISSUE THREAD

**Issue by dagobert** [esphome/issues#6766]
### The problem

I am using an ESP01s for reading SML data over serial RX GPIO3. Until now I used Tasmota.

When creating a esphome yaml with UART configured the ESP is booting probably "crashes" and goes into failsave. I have disabled serial logging but that does not help.

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.02.1

### What platform are you using?

ESP8266

### Board

esp01s

### Component causing the issue

UART or Logging

### YAML Config

```yaml
esphome:
  name: ${devicename}
  friendly_name: ${upper_devicename}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0
  logs:
    sml: INFO
    sml_sensor: INFO

...

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# see: https://esphome.io/components/time.html
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server
web_server:
  port: 80

uart:
  id: uart_bus
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
#  debug:

sml:
  id: mysml
  uart_id: uart_bus

# The following can be omitted
  - platform: restart
    #id: restart
    name: "${sensorname_prefix} restart"

# diagnostic sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${sensorname_prefix} IP Address"
    ssid:
      name: "${sensorname_prefix} Wifi SSID"
    bssid:
      name: "${sensorname_prefix} Wifi BSSID"
```

### Anything in the logs that might be useful for us?

```txt

```
