### ISSUE TITLE
Compiler segmentation fault

### ISSUE THREAD

**Issue by vipk31** [esphome/issues#677]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** hassio

**ESP (ESP32/ESP8266, Board/Sonoff):**ESP8266

**Affected component:**

**Description of problem:**
can not Compiling 
![esphome](https://user-images.githubusercontent.com/12049629/65332977-dd68b300-dbe9-11e9-9b72-81970f27b513.PNG)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: lalaa
  platform: ESP8266
  board: esp01_1m
  build_path: lalaa
  platformio_options: {}
  esp8266_restore_from_flash: false
  arduino_version: espressif8266@1.8.0
  includes: []
  libraries: []
  board_flash_mode: dout
wifi:
  fast_connect: false
  domain: .local
  power_save_mode: NONE
  reboot_timeout: 5min
  networks:
  - password: yyyyyyyy
    ssid: xxxxxx
  use_address: lalaa.local
logger:
  logs: {}
  esp8266_store_log_strings_in_flash: true
  level: DEBUG
  baud_rate: 115200
  tx_buffer_size: 512
  hardware_uart: UART0
api:
  password: '123654'
  reboot_timeout: 5min
  port: 6053
ota:
  password: '123654'
  safe_mode: true
  port: 8266



```

**Logs (if applicable):**

```
INFO Reading configuration...
INFO Generating C++ source...
INFO Core config or version changed, cleaning build files...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/lalaa
Processing lalaa (framework: arduino; platform: espressif8266@1.8.0; board: esp01_1m)
--------------------------------------------------------------------------------
LibraryManager: Installing id=305 @ 1.2.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz 80KB RAM (1MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 27 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.2.0
|   |-- <ESP8266WiFi> 1.0
Compiling /data/lalaa/.pioenvs/lalaa/src/esphome/components/api/api_message.cpp.o
Compiling /data/lalaa/.pioenvs/lalaa/src/esphome/components/api/api_server.cpp.o
Compiling /data/lalaa/.pioenvs/lalaa/src/esphome/components/api/basic_messages.cpp.o
Compiling /data/lalaa/.pioenvs/lalaa/src/esphome/components/api/command_messages.cpp.o
xtensa-lx106-elf-g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
*** [/data/lalaa/.pioenvs/lalaa/src/esphome/components/api/api_message.cpp.o] Error 4
========================== [ERROR] Took 17.85 seconds ==========================

```

**Additional information and things you've tried:**
