### ISSUE TITLE
LVGL Swipe does not work as intended

### ISSUE THREAD

**Issue by phellarv** [esphome/issues#6777]
### The problem

When I start a swipe gesture on a button, the on_press event trigger for the button is registered.
When I stop the swipe gesture on top of a button, the on_release event trigger for the button is registered.
I reckon this goes for all widgets that have a on_press/on_release event trigger.

### Which version of ESPHome has the issue?

2025.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.4

### What platform are you using?

ESP32

### Board

GUITION 1.8” 360x360 ESP32-S3-JC3636W518

### Component causing the issue

lvgl

### YAML Config

```yaml
lvgl:
  #full_refresh: true # redraw whole display every time so very slow
  displays:
    - main_display
  touchscreens:
    - my_touchscreen
  on_idle:
    timeout: 240s  # Turn off back light if idle for 10 secs
    then:
      - logger.log: "LVGL is idle"
      - light.turn_off: 
          id: backlight
          transition_length: 5s          
      - lvgl.pause:
          show_snow: true # Prevent burn-in  disp_bg_color: black
  top_layer:
    widgets:
      - obj:
          id: boot_screen
          x: 0
          y: 0
          width: 100%
          height: 100%
          bg_color: 0xffffff
          bg_opa: COVER
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - label:
                align: CENTER
                y: -40
                text_font: mdi_120
                text: "\U000F07D1"
            - spinner:
                align: CENTER
                y: 95
                height: 50
                width: 50
                spin_time: 1s
                arc_length: 60deg
                arc_width: 8
                indicator:
                  arc_color: 0x18bcf2
                  arc_width: 8
          on_press:
            - lvgl.widget.hide: boot_screen
      - obj:
          id: voice_screen
          x: 0
          y: 0
          width: 100%
          height: 100%
          bg_color: 0xffffff
          bg_opa: COVER
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - label:
                align: CENTER
                text_font: mdi_120
                text: "\U000F036C"
                y: -40
            - spinner:
                align: CENTER
                y: 95
                height: 50
                width: 50
                spin_time: 1s
                arc_length: 60deg
                arc_width: 8
                indicator:
                  arc_color: 0x18bcf2
                  arc_width: 8
      - buttonmatrix:
          align: bottom_mid
          styles: header_footer
          pad_all: 0
          outline_width: 0
          id: top_layer
          items:
            styles: header_footer
          rows:
            - buttons:
              - id: page_dill
                text: " "
              - id: page_prev
                text: "\uF053"
                on_press:
                  then:
                    lvgl.page.previous:
              - id: page_home
                text: "\uF015"
                on_press:
                  then:
                    lvgl.page.show: main_page
              - id: page_next
                text: "\uF054"
                on_press:
                  then:
                    lvgl.page.next:
              - id: page_dall
                text: " "
  theme:
    button:
      bg_color: black
      bg_opa: TRANSP
      border_color: black
      border_width: 0
      text_color: 0xD3D3D3
      checked: # set some button colors to be different in checked state
        bg_color: black
        text_color: yellow
    buttonmatrix:
      bg_color: black
      bg_opa: TRANSP
      border_color: black
      border_width: 0
      text_color: 0xD3D3D3
      checked: # set some button colors to be different in checked state
        bg_color: black
        text_color: yellow
        bg_opa: TRANSP
    arc:
      arc_opa: TRANSP
      border_opa: TRANSP
      bg_opa: TRANSP
      indicator:
        opa: TRANSP
        bg_opa: TRANSP
        border_opa: TRANSP
        arc_width: 30
      knob:
        bg_color: 0x00FF00
        bg_opa: COVER
        border_width: 2
        text_color: 0xFFFFFF
  style_definitions:
    - id: header_footer
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0x0077b3
      text_color: 0xFFFFFF
      width: 80%
      height: 50
    - id: font_style
      text_font: roboto_24
      #text_font: unscii_16
      align: center
      text_color: 0xFFFFFF
      #bg_opa: cover
      bg_opa: TRANSP
      bg_color: 0
      radius: 4
      pad_all: 2
    - id: meter_style
      text_font: unscii_8
      #state_default: null
  pages:
    - id: main_page
      bg_color: black
      on_swipe_right:
        - lvgl.page.previous:
      on_swipe_left:
        - lvgl.page.next:
      widgets:
        - obj: # Meter
            height: 100% # needed to be explicitily defined for my round display to not have weird corder line overlappting gauge
            width: 100%
            #bg_opa: TRANSP
            bg_color: 0
            border_width: 0
            outline_width: 0
            shadow_width: 0
            pad_all: 14
            align: center
            #scrollbar_mode: "off"
            widgets:
              - meter: # Gradient color  arc
                  height: 100%
                  width: 100%
                  border_width: 0
                  outline_width: 0
                  align: center
                  bg_color: 0
                  styles: meter_style
                  #bg_opa: TRANSP
                  scales:
                    angle_range: 180 # sets the total angle to 180 = starts mid left and ends mid right
                    range_to: 9
                    range_from: 0
                    ticks:
                      count: 0 
                    indicators:
                      - line:
                          id: power_meter_input
                          width: 8
                          color: 0xFFFFFF
                          r_mod: 12 #sets line length by this much difference from the scale default radius
                          value: 5
                      - arc:
                          color: 0x00FF00
                          r_mod: 10 #radius difference from the scale default radius
                          width: 25
                          start_value: 0
                          end_value: 3
                      - arc:
                          color: 0xFFFF00 
                          r_mod: 10 #radius difference from the scale default radius
                          width: 25
                          start_value: 3
                          end_value: 6
                      - arc:
                          color: 0xFF3000
                          r_mod: 10 #radius difference from the scale default radius
                          width: 25
                          start_value: 6
                          end_value: 9
              - obj: # to cover the middle part of meter indicator line
                  height: 80%
                  width: 80%
                  radius: 40%
                  align: CENTER
                  border_width: 0
                  pad_all: 0
                  bg_color: 0x000000
              - label:
                  styles: font_style
                  text_font: roboto_30 # override font size
                  id: main_lbl_forbruk_akkurat_na
                  y: -90
                  on_long_press:
                    then:
                      lvgl.page.show: page_power_info
              - label:
                  styles: font_style
                  text_font: mdi_30 # override font size
                  id: flash_icon_1
                  text: "\U000F0241"
                  text_color: yellow
                  x: -60
                  y: -90
                  on_long_press:
                    then:
                      lvgl.page.show: page_power_info
              - label:
                  styles: font_style
                  text_font: mdi_30 # override font size
                  id: lbl_temp_inne_icon
                  text: "\U000F0F54"
                  text_color: red
                  y: -7
                  x: 10
                  on_long_press:
                    then:
                      lvgl.page.show: thermostat_page
              - label:
                  styles: font_style
                  text_font: roboto_30 # override font size
                  id: main_lbl_temp_inne
                  y: -7
                  x: 75
                  on_long_press:
                    then:
                      lvgl.page.show: thermostat_page
              - label:
                  styles: font_style
                  text_font: mdi_30 # override font size
                  id: lbl_pris_akkurat_na_icon
                  text: "\U000F0114"
                  text_color: green
                  y: -50
                  x: -50
                  on_long_press:
                    then:
                      lvgl.page.show: page_power_info
              - label:
                  styles: font_style
                  text_font: roboto_20 # override font size
                  id: main_lbl_pris_akkurat_na
                  y: -50
                  x: 0
                  on_long_press:
                    then:
                      lvgl.page.show: page_power_info
              - label:
                  styles: font_style
                  text_font: mdi_30 # override font size
                  id: lbl_temp_outside_icon
                  text: "\U000F0F55"
                  text_color: blue
                  y: -7
                  x: -120
                  on_long_press:
                    then:
                      lvgl.page.show: weather_status
              - label:
                  styles: font_style
                  text_font: roboto_30 # override font size
                  id: main_lbl_temp_outside
                  y: -7
                  x: -55
                  on_long_press:
                    then:
                      lvgl.page.show: weather_status
              - buttonmatrix:
                  align: CENTER
                  pad_all: 0
                  outline_width: 0
                  border_color: black
                  border_width: 0
                  border_opa: TRANSP
                  x: 0
                  y: 40
                  width: 300
                  height: 50
                  bg_color: black
                  text_color: 0xD3D3D3
                  id: btnmtx_lights
                  text_font: mdi_42
                  items:
                    shadow_opa: TRANSP
                    bg_color: black
                    text_color: 0xD3D3D3
                    border_color: black
                    border_width: 0
                    border_opa: TRANSP
                    checked: # set some button colors to be different in checked state
                      bg_color: black
                      text_color: yellow
                      bg_opa: TRANSP
                  rows:
                    - buttons:
                      - id: ceiling_light_symbol
                        text: "\U000F0769"
                        control:
                          checkable: true
                        on_release:
                          then:
                            - homeassistant.action:
                                action: light.toggle
                                data:
                                  entity_id: light.taklampe_1_stue
                            - delay: 2ms
                            - homeassistant.action:
                                action: input_button.press
                                data:
                                  entity_id: input_button.lagre_lys
                        on_long_press:
                          then:
                            lvgl.page.show: page_sliders_light
                      - id: coffee_maker_symbol
                        text: "\U000F109F"
                        control:
                          checkable: true
                        on_release:
                          then:
                            - homeassistant.action:
                                action: switch.toggle
                                data:
                                  entity_id: switch.kaffetrakter_1_kjokken
                      - id: reading_light_symbol
                        text: "\U000F08DD"
                        control:
                          checkable: true
                        on_release:
                          then:
                            - homeassistant.action:
                                action: light.toggle
                                data:
                                  entity_id: light.readinglight_1_stue
                            - delay: 2s
                            - homeassistant.action:
                                action: input_button.press
                                data:
                                  entity_id: input_button.lagre_lys
                        on_long_press:
                          then:
                            lvgl.page.show: page_sliders_light
              - buttonmatrix:
                  align: CENTER
                  pad_all: 0
                  outline_width: 0
                  border_color: black
                  border_width: 0
                  border_opa: TRANSP
                  x: 0
                  y: 90
                  width: 150
                  height: 50
                  bg_color: black
                  text_color: 0xD3D3D3
                  id: post_garbage
                  text_font: mdi_30
                  items:
                    shadow_opa: TRANSP
                    bg_color: black
                    text_color: 0xD3D3D3
                    border_color: black
                    border_width: 0
                    border_opa: TRANSP
                  rows:
                    - buttons:
                      - id: post_symbol
                        text: "\U000F06EE"
                        on_release:
                          then:
                            - lvgl.page.show: page_posten_info
                      - id: paperwaste_symbol
                        text: "\U000F1001"
                        on_release:
                          then:
                            - lvgl.page.show: page_paperwaste_info
                      - id: restwaste_symbol
                        text: "\U000F0A79"
                        on_release:
                          then:
                            - lvgl.page.show: page_restwaste_info
    - id: page_posten_info
      bg_color: black
      skip: true
      widgets:
        - label:
            styles: font_style
            text_font: mdi_42 # override font size
            id: posten_relative_next_icon
            align: center
            x: 0            
            y: -120
            text: "\U000F06EE"
        - label:
            styles: font_style
            text_font: roboto_24 # override font size
            id: posten_relative_next_label
            align: center
            x: 0
            y: -30
            text: "Neste gang posten leveres:"
        - label:
            styles: font_style
            text_font: roboto_40 # override font size
            id: pst_lbl_posten_relative_next
            align: center
            x: 0
            y: 50
            text: "Dato"
    - id: page_paperwaste_info
      skip: true
      bg_color: black
      widgets:
        - label:
            styles: font_style
            text_font: mdi_42 # override font size
            id: paperwaste_relative_next_icon
            align: center
            x: 0            
            y: -120
            text: "\U000F1001"
        - label:
            styles: font_style
            text_font: roboto_24 # override font size
            id: paperwaste_relative_next_label
            align: center
            x: 0
            y: -30
            text: "Neste gang papirsøpla hentes:"
        - label:
            styles: font_style
            text_font: roboto_40 # override font size
            id: pws_lbl_paperwaste_relative_next
            align: center
            x: 0
            y: 50
            text: "Dato"
    - id: page_restwaste_info
      skip: true
      bg_color: black
      widgets:
        - label:
            styles: font_style
            text_font: mdi_42 # override font size
            id: lbl_restwaste_relative_next_icon
            align: center
            x: 0            
            y: -120
            text: "\U000F0A79"
        - label:
            styles: font_style
            text_font: roboto_24 # override font size
            id: lbl_restwaste_relative_next_text
            align: center
            x: 0
            y: -30
            text: "Neste gang restsøpla hentes:"
        - label:
            styles: font_style
            text_font: roboto_40 # override font size
            id: rss_lbl_restwaste_relative_next
            align: center
            x: 0
            y: 50
            text: "Dato"
    - id: weather_status
      skip: true
      bg_color: black
      widgets:
        - obj:
            align: CENTER
            width: 228
            height: 250
            pad_all: 10
            bg_color: black
            layout:
              pad_column: 0
              type: GRID
              grid_rows: [FR(48), FR(13), FR(13), FR(13), FR(13)]
              grid_columns: [FR(10), FR(40), FR(40), FR(10)]
            widgets:
              - label:
                  text: "\U000F14E4"
                  id: wth_lbl_weather_condition_icon
                  text_font: icons_100
                  text_color: white
                  text_align: CENTER
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 2
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: START

              - label:
                  text: "Unknown"
                  id: wth_lbl_weather_condition_name
                  text_align: CENTER
                  text_color: white
                  text_font: roboto_20
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 2
                  grid_cell_column_span: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER

              - label:
                  text: "Vind:"
                  text_font: roboto_20
                  text_color: white
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 1

              - label:
                  text: "--.- m/s"
                  id: wth_lbl_status_wind
                  text_color: white
                  text_font: roboto_20
                  text_align: RIGHT
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 2
                  grid_cell_x_align: STRETCH

              - label:
                  text: "Lufttrykk:"
                  text_color: white
                  text_font: roboto_20
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 1

              - label:
                  text: "--- hPa"
                  id: wth_lbl_pressure_status
                  text_color: white
                  text_font: roboto_20
                  text_align: RIGHT
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 2
                  grid_cell_x_align: STRETCH

              - label:
                  text: "Fuktighet:"
                  text_color: white
                  text_font: roboto_20
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 1

              - label:
                  text: "-- %"
                  text_color: white
                  text_font: roboto_20
                  id: wth_lbl_humidity_status
                  text_align: RIGHT
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 2
                  grid_cell_x_align: STRETCH

              - label:
                  text: "Temp:"
                  text_font: roboto_20
                  text_color: white
                  grid_cell_row_pos: 4
                  grid_cell_column_pos: 1

              - label:
                  text: "--.- °C"
                  text_font: roboto_20
                  text_color: white
                  id: wth_lbl_temp_outside
                  text_align: RIGHT
                  grid_cell_row_pos: 4
                  grid_cell_column_pos: 2
                  grid_cell_x_align: STRETCH
    - id: page_sliders_light
      skip: true
      bg_color: black
      widgets:
        - label:
            align: CENTER
            styles: font_style
            text_font: roboto_30 # override font size
            y: -100 #negative = higher
            x: 0
            text: "Taklampe"        
        - slider:
            id: dimmer_slider_taklampe
            align: CENTER
            x: 0
            y: -50
            width: 180
            height: 30
            pad_all: 8
            min_value: 0
            max_value: 255
            on_release:
              - homeassistant.action:
                  action: light.turn_on
                  data:
                    entity_id: light.taklampe_1_stue
                    brightness: !lambda return int(x);
        - label:
            align: CENTER
            styles: font_style
            text_font: roboto_30 # override font size
            y: 0 #negative = higher
            x: 0
            text: "Stålampe"        
        - slider:
            id: dimmer_slider_lampe
            align: CENTER
            x: 0
            y: 50
            width: 180
            height: 30
            pad_all: 8
            min_value: 0
            max_value: 255
            on_release:
              - homeassistant.action:
                  action: light.turn_on
                  data:
                    entity_id: light.readinglight_1_stue
                    brightness: !lambda return int(x);
    - id: thermostat_page
      bg_color: black
      widgets:
        - meter:
            height: 100%
            width: 100%
            border_width: 0
            align: CENTER
            bg_opa: TRANSP
            border_color: 0x000000
            bg_color: 0x000000
            scales:
              - range_from: 15
                range_to: 30
                angle_range: 180
                ticks:
                  count: 75
                  width: 4
                  length: 60
                indicators:
                  - tick_style:
                      start_value: 15
                      end_value: 30
                      color_start: 0x0000FF
                      color_end: 0xFF0000
              - range_from: 150
                range_to: 300
                angle_range: 180
                ticks:
                  count: 0
                indicators:
                  - line:
                      id: thm_ind_temp_needle
                      color: 0xFFFF00
                      width: 8
                      r_mod: 2
                      value: 20
        - obj: # to cover the middle part of meter indicator line
            height: 240
            width: 240
            radius: 120
            align: CENTER
            border_width: 0
            pad_all: 0
            bg_color: 0x000000
        - label:
            id: thm_lbl_temp_inn
            text: "--.-°C"
            align: CENTER
            y: 0
            text_font: roboto_40
            text_color: white
        - arc:
            align: CENTER
            height: 310
            width: 310
            #radius: 175
            border_width: 0
            x: 0
            y: 0 # distance down from top
            id: thm_arc_bar_thermostat
            value: 20
            min_value: 15
            max_value: 30
            adjustable: true
            end_angle: 0
            start_angle: 180
            arc_width: 20
            arc_opa: TRANSP
            border_opa: TRANSP
            bg_opa: TRANSP
            border_color: 0x000000
            indicator:
              opa: TRANSP
              bg_opa: TRANSP
              border_opa: TRANSP
              border_color: 0x000000
              arc_width: 30
            knob:
              bg_color: 0x00FF00
              bg_opa: COVER
              border_width: 2
              text_color: 0xFFFFFF            
            on_release:
              - homeassistant.action:
                  action: input_number.set_value
                  data:
                      entity_id: input_number.temperatur_1_stue_komfort
                      value: !lambda return x;
            on_value:
              - lvgl.label.update:
                  id: thm_lbl_komfort_temp
                  text_font: roboto_24
                  text:
                    format: "%.0f°C"
                    args: [ 'x' ]
        - label:
            id: thm_lbl_komfort_temp
            text: "--.-°C"
            align: CENTER
            y: -40
            text_font: roboto_30
            text_color: white
    - id: page_power_info
      bg_color: black
      widgets:
        - obj: # Meter
            height: 100% # needed to be explicitily defined for my round display to not have weird corder line overlappting gauge
            width: 100%
            #bg_opa: TRANSP
            bg_color: 0
            border_width: 0
            outline_width: 0
            shadow_width: 0
            pad_all: 14
            align: center
            #scrollbar_mode: "off"
            widgets:
              - meter: # Gradient color  arc
                  height: 100%
                  width: 100%
                  border_width: 0
                  outline_width: 0
                  align: center
                  bg_color: 0
                  styles: meter_style
                  #bg_opa: TRANSP
                  scales:
                    angle_range: 180 # sets the total angle to 180 = starts mid left and ends mid right
                    range_to: 9
                    range_from: 0
                    ticks:
                      count: 0 
                    indicators:
                      - line:
                          id: power_ind_power_meter_input
                          width: 8
                          color: 0xFFFFFF
                          r_mod: 12 #sets line length by this much difference from the scale default radius
                          value: 5
                      - arc:
                          color: 0x00FF00
                          r_mod: 10 #radius difference from the scale default radius
                          width: 25
                          start_value: 0
                          end_value: 3
                      - arc:
                          color: 0xFFFF00 
                          r_mod: 10 #radius difference from the scale default radius
                          width: 25
                          start_value: 3
                          end_value: 6
                      - arc:
                          color: 0xFF3000
                          r_mod: 10 #radius difference from the scale default radius
                          width: 25
                          start_value: 6
                          end_value: 9
              - obj: # to cover the middle part of meter indicator line
                  height: 80%
                  width: 80%
                  radius: 40%
                  align: CENTER
                  border_width: 0
                  pad_all: 0
                  bg_color: 0x000000
              - label: # gauge lower and higher range indicators
                  styles: font_style
                  text_font: roboto_20 # override font size
                  y: 20 #negative = higher
                  x: -150
                  text: "0"
              - label:
                  styles: font_style
                  text_font: roboto_20 # override font size
                  y: 20 #negative = higher
                  x: 150
                  text: "10"
              - label:
                  styles: font_style
                  id: power_lbl_pris_hittil_i_dag
                  y: -60 #negative = higher
              - label:
                  styles: font_style
                  id: power_lbl_forbruk_hittil_i_dag
                  y: -35 #negative = higher
              - label:
                  styles: font_style
                  text_font: roboto_40 # override font size
                  id: power_lbl_forbruk_akkurat_na
                  y: 0
              - label:
                  styles: font_style
                  id: power_lbl_pris_akkurat_na
                  text_color: 0xFFFF00
                  y: 35
              - label:
                  styles: font_style
                  id: power_lbl_pris_denne_maned
                  y: 60
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

Could not paste the whole YAML, since my stuff is modular.
But contact Duckboot on Discord, I'm in the ESPHome server.
