### ISSUE TITLE
Could not compile after today update to 2025.2.0

### ISSUE THREAD

**Issue by mihailmoise** [esphome/issues#6778]
### The problem

I've just changed yesterday from Raspberry PI 4 to NUC and successfully recompiled the YAML for a touch display.
Compiling today the same YAML w/ LVGL for board esp32-s3-touch-lcd-4.3b from Waveshare fails with next error.
Single change in between was the ESPHome Device Builder update.

Compiling .pioenvs/lvgl-touch-display--hol-1/src/esphome/components/lvgl/lvgl_esphome.cpp.o
In file included from src/esphome/components/lvgl/lvgl_esphome.cpp:3:
src/esphome/components/lvgl/lvgl_esphome.cpp: In function 'void* lv_custom_mem_alloc(size_t)':
src/esphome/core/log.h:128:3: error: expected unqualified-id before '::' token
  128 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_ERROR, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |   ^~
src/esphome/components/lvgl/lvgl_esphome.cpp:37:14: note: in expansion of macro 'esph_log_e'
   37 |     esphome::esph_log_e(TAG, "Failed to allocate %zu bytes", size);
      |              ^~~~~~~~~~
*** [.pioenvs/lvgl-touch-display--hol-1/src/esphome/components/lvgl/lvgl_esphome.cpp.o] Error 1
========================== [FAILED] Took 3.86 seconds ==========================

### Which version of ESPHome has the issue?

2025.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.4

### What platform are you using?

ESP32

### Board

esp32-s3-touch-lcd-4.3b

### YAML Config

```yaml
substitutions:
  page_main: page_hol_1

  lightbulb:                  "\U000F0335"
  lightbulb_multiple:         "\U000F1255"
  lightbulb_group:            "\U000F1253"
  lightbulb_outline:          "\U000F0336"
  lightbulb_multiple_outline: "\U000F1256"
  lightbulb_group_outline:    "\U000F1254"
  ceiling_light: "\U000F0769"
  lamp:          "\U000F06B5"
  floor_lamp:    "\U000F08DD"
  string_lights: "\U000F12BA"

  icon_font: light_80
  text_font: roboto_24  

esphome:
  name: lvgl-touch-display--hol-1
  friendly_name: LVGL Touch Display - Hol 1
  compile_process_limit: 1
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

external_components:
  - source: github://pr#6363
    refresh: 0min
    components: [lvgl]

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG

i2c:
  sda: GPIO08
  scl: GPIO09
#  scan: True
  id: bus_a
  frequency: 400kHz

# Enable Home Assistant API
api:
  encryption:
    key: "u5m80XDW0CecmYKt5gkPSL/3ELJeYvf0IppInaqP/r8="
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
#          - lvgl.widget.show: lbl_hastatus
          - lvgl.widget.hide: boot_screen
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
#          - lvgl.widget.hide: lbl_hastatus
          - lvgl.widget.show: boot_screen

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: yes

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ssid_util
    password: !secret wifi_password_util

captive_portal:

display:
  - platform: rpi_dpi_rgb
    id: display_hol_1
    auto_clear_enabled: false
    update_interval: never
    color_order: RGB
    pclk_frequency: 14MHz
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    reset_pin:
      ch422g: ch422g_hub
      number: 3
    hsync_back_porch: 16 #30
    hsync_front_porch: 16 #210
    hsync_pulse_width: 8 #30
    vsync_back_porch: 16 #4
    vsync_front_porch: 16 #4
    vsync_pulse_width: 8 #4
    data_pins:
      red:
        - 1         #r3
        - 2         #r4
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7

font:
  - file: 
      type: gfonts
      family: Roboto
      weight: 700
    id: roboto_24_b
    size: 24
  - file: 
      type: gfonts
      family: Roboto
      weight: 400
    id: roboto_24
    size: 24
  - file: 
      type: gfonts
      family: Roboto
      weight: 700
    id: roboto_36_b
    size: 36
  - file: 
      type: gfonts
      family: Roboto
      weight: 700
    id: roboto_40_b
    size: 40
  - file: 
      type: gfonts
      family: Gruppo
      weight: 400
    id: font_gruppo_40
    size: 40
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: light_40
    size: 40
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F1253",  # mdi-lightbulb-group
      "\U000F1255",  # mdi-lightbulb-multiple
      "\U000F0336",  # mdi-lightbulb-outline
      "\U000F1254",  # mdi-lightbulb-group-outline
      "\U000F1256",  # mdi-lightbulb-multiple-outline
      "\U000F0769",  # mdi-ceiling-light
      "\U000F06B5",  # mdi-lamp
      "\U000F08DD",  # mdi-floor-lamp
      "\U000F12BA",  # mdi-string-lights
    ]      
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: light_60
    size: 60
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F1253",  # mdi-lightbulb-group
      "\U000F1255",  # mdi-lightbulb-multiple
      "\U000F0336",  # mdi-lightbulb-outline
      "\U000F1254",  # mdi-lightbulb-group-outline
      "\U000F1256",  # mdi-lightbulb-multiple-outline
      "\U000F0769",  # mdi-ceiling-light
      "\U000F06B5",  # mdi-lamp
      "\U000F08DD",  # mdi-floor-lamp
      "\U000F12BA",  # mdi-string-lights
    ]      
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: light_80
    size: 80
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F1253",  # mdi-lightbulb-group
      "\U000F1255",  # mdi-lightbulb-multiple
      "\U000F0336",  # mdi-lightbulb-outline
      "\U000F1254",  # mdi-lightbulb-group-outline
      "\U000F1256",  # mdi-lightbulb-multiple-outline
      "\U000F0769",  # mdi-ceiling-light
      "\U000F06B5",  # mdi-lamp
      "\U000F08DD",  # mdi-floor-lamp
      "\U000F12BA",  # mdi-string-lights
    ]      
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: weather_70
    size: 70
    bpp: 4
    glyphs: &mdi-weather-glyphs
      - "\U000F0590" # mdi-weather-cloudy
      - "\U000F0F2F" # mdi-weather-cloudy-alert
      - "\U000F0E6E" # mdi-weather-cloudy-arrow-right
      - "\U000F0591" # mdi-weather-fog
      - "\U000F0592" # mdi-weather-hail
      - "\U000F0F30" # mdi-weather-hazy
      - "\U000F0898" # mdi-weather-hurricane
      - "\U000F0593" # mdi-weather-lightning
      - "\U000F067E" # mdi-weather-lightning-rainy
      - "\U000F0594" # mdi-weather-clear-night
      - "\U000F0F31" # mdi-weather-night-partly-cloudy
      - "\U000F0595" # mdi-weather-partly-cloudy
      - "\U000F0F32" # mdi-weather-partly-lightning
      - "\U000F0F33" # mdi-weather-partly-rainy
      - "\U000F0F34" # mdi-weather-partly-snowy
      - "\U000F0F35" # mdi-weather-partly-snowy-rainy
      - "\U000F0596" # mdi-weather-pouring
      - "\U000F0597" # mdi-weather-rainy
      - "\U000F0598" # mdi-weather-snowy
      - "\U000F0F36" # mdi-weather-snowy-heavy
      - "\U000F067F" # mdi-weather-snowy-rainy
      - "\U000F0599" # mdi-weather-sunny
      - "\U000F0F37" # mdi-weather-sunny-alert
      - "\U000F14E4" # mdi-weather-sunny-off
      - "\U000F059A" # mdi-weather-sunset
      - "\U000F059B" # mdi-weather-sunset-down
      - "\U000F059C" # mdi-weather-sunset-up
      - "\U000F0F38" # mdi-weather-tornado
      - "\U000F059D" # mdi-weather-windy
      - "\U000F059E" # mdi-weather-windy-variant

ch422g:
  - id: ch422g_hub
#    address: 0x24 

touchscreen:
  platform: gt911
  id: touch_hol_1
  interrupt_pin: GPIO4
  address: 0x5D #0x14
  reset_pin:
    ch422g: ch422g_hub
    number: 1
    mode: OUTPUT
  on_release:
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - switch.turn_on: backlight

text_sensor:
  - platform: homeassistant
    id: hol_1_light
    name: "Hol 1"
    entity_id: light.hol_1
    on_value: 
      then:
        - lvgl.widget.update:
            id: hol_1_panel_1_button
            state:
              checked: !lambda return (0 == x.compare(std::string{"on"}));
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - lvgl.widget.update:
            id: hol_1_panel_1_dimmer
            state:
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - if:
            condition: 
              text_sensor.state:
                id: hol_1_light
                state: 'on'
            then:
              - lvgl.label.update:
                  id: label_button_hol_1_1_icon
                  text: $lightbulb_multiple
            else:
              - lvgl.label.update:
                  id: label_button_hol_1_1_icon
                  text: $lightbulb_multiple_outline
  - platform: homeassistant
    id: hol_2_light
    name: "Hol 2"
    entity_id: light.hol_2
    on_value: 
      then:
        - lvgl.widget.update:
            id: hol_1_panel_2_button
            state:
              checked: !lambda return (0 == x.compare(std::string{"on"}));
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - lvgl.widget.update:
            id: hol_1_panel_2_dimmer
            state:
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - if:
            condition: 
              text_sensor.state:
                id: hol_2_light
                state: 'on'
            then:
              - lvgl.label.update:
                  id: label_button_hol_1_2_icon
                  text: $lightbulb_multiple
            else:
              - lvgl.label.update:
                  id: label_button_hol_1_2_icon
                  text: $lightbulb_multiple_outline
  - platform: homeassistant
    id: hol_3_light
    name: "XMas"
    entity_id: light.christmas_living_light
    on_value: 
      then:
        - lvgl.widget.update:
            id: hol_1_panel_3_button
            state:
              checked: !lambda return (0 == x.compare(std::string{"on"}));
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - lvgl.widget.update:
            id: hol_1_panel_3_dimmer
            state:
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - if:
            condition: 
              text_sensor.state:
                id: hol_3_light
                state: 'on'
            then:
              - lvgl.label.update:
                  id: label_button_hol_1_3_icon
                  text: $lightbulb
            else:
              - lvgl.label.update:
                  id: label_button_hol_1_3_icon
                  text: $lightbulb_outline
  - platform: homeassistant
    id: hol_4_light
    name: "Scara"
    entity_id: light.lumini_scara
    on_value: 
      then:
        - lvgl.widget.update:
            id: hol_1_panel_4_button
            state:
              checked: !lambda return (0 == x.compare(std::string{"on"}));
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - if:
            condition: 
              text_sensor.state:
                id: hol_4_light
                state: 'on'
            then:
              - lvgl.label.update:
                  id: label_button_hol_1_4_icon
                  text: $lightbulb
            else:
              - lvgl.label.update:
                  id: label_button_hol_1_4_icon
                  text: $lightbulb_outline
  - platform: homeassistant
    id: hol_1_light_brightness
    entity_id: light.hol_1
    attribute: brightness
    on_value:
      - lvgl.slider.update:
          id: hol_1_panel_1_dimmer
          value: !lambda |-
            if(x == "None" or x == "nan" or x == "nan "){
              return 0;
            } else {
              return stoi(x);
            }
  - platform: homeassistant
    id: hol_2_light_brightness
    entity_id: light.hol_2
    attribute: brightness
    on_value:
      - lvgl.slider.update:
          id: hol_1_panel_2_dimmer
          value: !lambda |-
            if(x == "None" or x == "nan" or x == "nan "){
              return 0;
            } else {
              return stoi(x);
            }
  - platform: homeassistant
    id: hol_3_light_brightness
    entity_id: light.christmas_living_light
    attribute: brightness
    on_value:
      - lvgl.slider.update:
          id: hol_1_panel_3_dimmer
          value: !lambda |-
            if(x == "None" or x == "nan" or x == "nan "){
              return 0;
            } else {
              return stoi(x);
            }
  - platform: homeassistant
    id: icon_owm
    entity_id:  weather.openweathermap
    on_value:
      - lvgl.label.update:
          id: label_button_hol_1_1_text
          text: !lambda |- 
                //return x.c_str();
                std::map<std::string, std::string> weather_text_map
                {
                  {"cloudy", "cer noros"},
                  {"cloudy-alert", "cer noros"},
                  {"cloudy-arrow-right", "cer noros"},
                  {"fog", "ceata"},
                  {"hail", "grindina"},
                  {"hazy", "cetos"},
                  {"hurricane", "uragan"},
                  {"lightning", "fulgera"},
                  {"lightning-rainy", "ploaie cu fulgere"},
                  {"clear-night", "noapte senina"},
                  {"night-partly-cloudy", "cer partial noros"},
                  {"partlycloudy", "cer partial noros"},
                  {"partly-lightning", "fulgera"},
                  {"partly-rainy", "ploaie"},
                  {"partly-snowy", "ninsoare"},
                  {"partly-snowy-rainy", "ploaie cu ninsoare"},
                  {"pouring", "ploaie"},
                  {"rainy", "ploaie"},
                  {"snowy", "ninsoare"},
                  {"snowy-heavy", "ninsoare"},
                  {"snowy-rainy", "ploaie cu ninsoare"},
                  {"sunny", "soare"},
                  {"sunny-alert", "soare"},
                  {"sunny-off", "soare"},
                  {"sunset", "apus"},
                  {"sunset-down", "apus"},
                  {"sunset-up", "apus"},
                  {"tornado", "tornada"},
                  {"windy", "vânt"},
                  {"windy-variant", "vânt"},
                };
                static char buf[25];
                std::string cond;
                cond = weather_text_map[id(icon_owm).state.c_str()];
                snprintf(buf, sizeof(buf), "%s", cond.c_str());
                return buf;
      - lvgl.label.update:
          id: label_button_hol_1_1
          text_font: weather_70
          text: !lambda |-
                std::map<std::string, std::string> weather_icon_map
                {
                  {"cloudy", "\U000F0590"},
                  {"cloudy-alert", "\U000F0F2F"},
                  {"cloudy-arrow-right", "\U000F0E6E"},
                  {"fog", "\U000F0591"},
                  {"hail", "\U000F0592"},
                  {"hazy", "\U000F0F30"},
                  {"hurricane", "\U000F0898"},
                  {"lightning", "\U000F0593"},
                  {"lightning-rainy", "\U000F067E"},
                  {"clear-night", "\U000F0594"},
                  {"night-partly-cloudy", "\U000F0F31"},
                  {"partlycloudy", "\U000F0595"},
                  {"partly-lightning", "\U000F0F32"},
                  {"partly-rainy", "\U000F0F33"},
                  {"partly-snowy", "\U000F0F34"},
                  {"partly-snowy-rainy", "\U000F0F35"},
                  {"pouring", "\U000F0596"},
                  {"rainy", "\U000F0597"},
                  {"snowy", "\U000F0598"},
                  {"snowy-heavy", "\U000F0F36"},
                  {"snowy-rainy", "\U000F067F"},
                  {"sunny", "\U000F0599"},
                  {"sunny-alert", "\U000F0F37"},
                  {"sunny-off", "\U000F14E4"},
                  {"sunset", "\U000F059A"},
                  {"sunset-down", "\U000F059B"},
                  {"sunset-up", "\U000F059C"},
                  {"tornado", "\U000F0F38"},
                  {"windy", "\U000F059D"},
                  {"windy-variant", "\U000F059E"},
                };
                return weather_icon_map[id(icon_owm).state.c_str()].c_str();

sensor:
  - platform: homeassistant
    id: outside_condition
    entity_id: sensor.openweathermap_temperature
    on_value:
      - lvgl.label.update:
          id: label_button_hol_1_2
          text_font: roboto_36_b
          text:
            format: "%.1f°C"
            args: [ 'x' ]
  - platform: homeassistant
    id: fcst_temp_low
    entity_id: sensor.forecast_today_temperature_low
    on_value: 
      then:
        - lvgl.label.update:
            id: label_button_hol_1_2_low
            text:
              format: "%.1f°C"
              args: [ 'x' ]
  - platform: homeassistant
    id: fcst_temp_high
    entity_id: sensor.forecast_today_temperature_high
    on_value: 
      then:
        - lvgl.label.update:
            id: label_button_hol_1_2_high
            text:
              format: "%.1f°C"
              args: [ 'x' ]

switch:
  - platform: template
    name: Antiburn
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
  - platform: template
    name: Entire LCD
    id: switch_entire_lcd
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - switch.turn_on: backlight
    turn_off_action:
      then:
        - switch.turn_off: backlight
        - lvgl.pause:
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: Backlight
    id: backlight
    pin:
      ch422g: ch422g_hub
      number: 2
      mode:
        output: true
      inverted: False
    restore_mode: ALWAYS_ON
  - platform: restart
    name: "Display Restart"

lvgl:
  displays:
    - display_id: display_hol_1
  touchscreens:
    - touchscreen_id: touch_hol_1
  on_idle:
    - timeout: 120s
      then:
        - switch.turn_off: backlight
        - lvgl.pause:
  buffer_size: 25%
  top_layer:
    widgets:
      - obj:
          id: boot_screen
          x: 0
          y: 0
          width: 100%
          height: 100%
          bg_color: 0x000000
          bg_opa: COVER
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - spinner:
                align: CENTER
                y: 0
                height: 240
                width: 240
                spin_time: 1s
                arc_length: 60deg
                arc_width: 16
                arc_rounded: true
                indicator:
                  arc_color: 0x183c72
                  arc_width: 15
          on_press:
            - lvgl.widget.hide: boot_screen
      - label:
          id: lbl_datetime
          x: 0
          y: 0
          width: 100%
          text_align: center
          text_font: font_gruppo_40
          text_color: 0x808080
          bg_opa: TRANSP
  page_wrap: true
  theme:
    obj:
      bg_color: 0x000000
      bg_opa: cover
      border_color: 0x000000
      border_width: 0
    button:
      bg_color: 0x303030
      text_color: 0x44739E
      border_color: 0x44739E
      checkable: true
      checked:
        text_color: 0xFFFF00
        border_color: 0xFFFF00
        bg_color: 0x303030
      pressed:
        border_color: 0xff6600
        text_color: 0xff6600
        bg_color: 0x505050
    slider:
      knob:
        width: 20
        height: 20

  style_definitions:
    - id: obj_style
      border_width: 0
      radius: 0
      pad_top: 50
      pad_bottom: 20
      pad_left: 10
      pad_right: 10
      height: 100%
      pad_row: 0
      pad_column: 0
    - id: button_style
      border_width: 2
      width: 140
      height: 100%
      align: center
    - id: slider_style
      height: 100%
      width: 18
      pad_all: 8
      translate_x: 0

  pages:
    - id: page_hol_1
      radius: 0
      pad_all: 0
      bg_opa: cover
      bg_color: 0x000000
      pad_row: 0
      pad_column: 0
      layout:
        type: flex
        flex_flow: ROW
      widgets:
        - obj:
            id: panel_hol_1_1
            styles: obj_style
            width: 200
            layout:
              type: flex
              flex_flow: ROW
            pad_row: 0
            pad_column: 15
            widgets:
              - button:
                  id: hol_1_panel_1_button
                  styles: button_style
                  widgets:
                    - label:
                        text_font: light_60
                        align: top_left
                        text: $lightbulb_multiple_outline
                        id: label_button_hol_1_1_icon
                    - label:
                        text_font: weather_70
                        align: center
                        text: "\U000F0599"
                        id: label_button_hol_1_1
                    - label:
                        text_font: roboto_24
                        align_to:
                          id: label_button_hol_1_1
                          x: 0
                          y: 0
                          align: OUT_BOTTOM_MID
                        text: "soare"
                        width: 100%
                        text_align: center
                        id: label_button_hol_1_1_text
                    - label:
                        align: bottom_mid
                        text: "Hol 1"
                        text_font: roboto_24
                  on_click:
                    - homeassistant.service:
                        service: light.toggle
                        data:
                          entity_id: light.hol_1
              - slider:
                  id: hol_1_panel_1_dimmer
                  styles: slider_style
                  min_value: 0
                  max_value: 255
                  on_release:
                    - homeassistant.action:
                        action: light.turn_on
                        data:
                          entity_id: light.hol_1
                          brightness: !lambda return int(x);
        - obj:
            id: panel_hol_1_2
            styles: obj_style
            width: 200
            layout:
              type: flex
              flex_flow: ROW
            pad_row: 0
            pad_column: 15
            widgets:
              - button:
                  id: hol_1_panel_2_button
                  styles: button_style
                  widgets:
                    - label:
                        text_font: light_60
                        align: top_left
                        text: $lightbulb_multiple_outline
                        id: label_button_hol_1_2_icon
                    - label:
                        text_font: roboto_24
                        align_to:
                          id: label_button_hol_1_2
                          x: 0
                          y: -1
                          align: OUT_TOP_MID
                        text: ""
                        width: 100%
                        text_align: center
                        id: label_button_hol_1_2_high
                    - label:
                        text_font: $icon_font
                        align: center
                        text: $lightbulb_outline
                        id: label_button_hol_1_2
                    - label:
                        text_font: roboto_24
                        align_to:
                          id: label_button_hol_1_2
                          x: 0
                          y: 1
                          align: OUT_BOTTOM_MID
                        text: ""
                        width: 100%
                        text_align: center
                        id: label_button_hol_1_2_low
                    - label:
                        align: bottom_mid
                        text: "Hol 2"
                        text_font: roboto_24
                  on_click:
                      - homeassistant.service:
                          service: light.toggle
                          data:
                            entity_id: light.hol_2
              - slider:
                  id: hol_1_panel_2_dimmer
                  styles: slider_style
                  min_value: 0
                  max_value: 255
                  on_release:
                    - homeassistant.action:
                        action: light.turn_on
                        data:
                          entity_id: light.hol_2
                          brightness: !lambda return int(x);
        - obj:
            id: panel_hol_1_3
            styles: obj_style
            width: 200
            layout:
              type: flex
              flex_flow: ROW
            pad_row: 0
            pad_column: 15
            widgets:
              - button:
                  id: hol_1_panel_3_button
                  styles: button_style
                  widgets:
                    - label:
                        text_font: light_60
                        align: top_left
                        text: $lightbulb_outline
                        id: label_button_hol_1_3_icon
                    - label:
                        text_font: roboto_24
                        text: "XMas"
                        width: 100%
                        text_align: center
                        align: center
                        id: label_button_hol_1_3_text
                    - label:
                        align: bottom_mid
                        text: " "
                        text_font: roboto_24
                  on_click:
                    - homeassistant.service:
                        service: light.toggle
                        data:
                          entity_id: light.christmas_living_light
              - slider:
                  id: hol_1_panel_3_dimmer
                  styles: slider_style
                  min_value: 0
                  max_value: 255
                  on_release:
                    - homeassistant.action:
                        action: light.turn_on
                        data:
                          entity_id: light.christmas_living_light
                          brightness: !lambda return int(x);
        - obj:
            id: panel_hol_1_4
            styles: obj_style
            width: 200
            widgets:
              - button:
                  id: hol_1_panel_4_button
                  styles: button_style
                  widgets:
                    - label:
                        text_font: light_60
                        align: top_left
                        text: $lightbulb_outline
                        id: label_button_hol_1_4_icon
                    - label:
                        text_font: roboto_24
                        align: center
                        text: "Scara"
                        width: 100%
                        text_align: center
                        #id: label_button_hol_1_4
                    - label:
                        align: bottom_mid
                        text: " "
                        text_font: roboto_24
                  on_click:
                    - homeassistant.service:
                        service: light.turn_on
                        data:
                          entity_id: light.lumini_scara

time:
  - platform: homeassistant
    id: time_comp
  - platform: homeassistant
    id: time_antiburn
    on_time:
      - hours: 2,3,4,5
        minutes: 5
        seconds: 0
        then:
          - switch.turn_on: switch_antiburn
      - hours: 2,3,4,5
        minutes: 35
        seconds: 0
        then:
          - switch.turn_off: switch_antiburn
  - platform: sntp
    id: sntp_time
    timezone: Europe/Bucharest
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

interval:
  - interval: 5s
    then:
      if:
        condition:
          time.has_time:
        then:
          - lvgl.label.update:
              id: lbl_datetime
              text: !lambda |-
                std::map<std::string, std::string> month_text_map
                {
                  {"Jan", "Ianuarei"},
                  {"Feb", "Februarie"},
                  {"Mar", "Martie"},
                  {"Apr", "Aprilie"},
                  {"May", "Mai"},
                  {"Jun", "Iunie"},
                  {"Jul", "Iulie"},
                  {"Aug", "August"},
                  {"Sep", "Septembrie"},
                  {"Oct", "Octombrie"},
                  {"Nov", "Noiembrie"},
                  {"Dec", "Decembrie"}
                };
                //std::locale::global(std::locale("ro_RO.utf8"));
                static char buf[25];
                std::string cond;
                cond = id(sntp_time).now().strftime("%d %b %Y  %I:%M");
                snprintf(buf, sizeof(buf), "%s", cond.c_str());
                //return id(sntp_time).now().strftime("%d %b %Y  %I:%M").c_str();
                return buf;
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.2.0
INFO Reading configuration /config/esphome/lvgl-touch-display--hol-1.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/6363/head
INFO Detected timezone 'Europe/Bucharest'
INFO Detected timezone 'Europe/Bucharest'
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.5.1
INFO Compiling app...
Processing lvgl-touch-display--hol-1 (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 512KB RAM, 8MB Flash
 - framework-espidf @ 3.50105.0 (5.1.5) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 12.2.0+20230208 
 - toolchain-xtensa-esp32s3 @ 12.2.0+20230208
Reading CMake configuration...
Dependency Graph
|-- lvgl @ 8.4.0
|-- noise-c @ 0.1.6
Compiling .pioenvs/lvgl-touch-display--hol-1/src/esphome/components/lvgl/lvgl_esphome.cpp.o
In file included from src/esphome/components/lvgl/lvgl_esphome.cpp:3:
src/esphome/components/lvgl/lvgl_esphome.cpp: In function 'void* lv_custom_mem_alloc(size_t)':
src/esphome/core/log.h:128:3: error: expected unqualified-id before '::' token
  128 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_ERROR, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |   ^~
src/esphome/components/lvgl/lvgl_esphome.cpp:37:14: note: in expansion of macro 'esph_log_e'
   37 |     esphome::esph_log_e(TAG, "Failed to allocate %zu bytes", size);
      |              ^~~~~~~~~~
*** [.pioenvs/lvgl-touch-display--hol-1/src/esphome/components/lvgl/lvgl_esphome.cpp.o] Error 1
========================== [FAILED] Took 3.86 seconds ==========================
```
