### ISSUE TITLE
Mi Flora conductivity

### ISSUE THREAD

**Issue by mclaudiopt** [esphome/issues#678]
Hello to all
it is already known that battery level is not beeing reported for mi flora, unfortunelly in my case also conductivity is also not beeing reported

this is my config 
```
esphome:
  name: esp32
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "Fibra"
  password: "Fiesta77"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:

sensor:
  - platform: xiaomi_miflora
    mac_address: 'C4:7C:8D:6A:71:FC'
    temperature:
      name: "Xiaomi MiFlora Temperature"
    moisture:
      name: "Xiaomi MiFlora Moisture"
    illuminance:
      name: "Xiaomi MiFlora Illuminance"
    conductivity:
      name: "Xiaomi MiFlora Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora Battery Level"

  - platform: wifi_signal
    name: "WiFi ESP32"
    update_interval: 60s      
      
```
![image](https://user-images.githubusercontent.com/48178294/65385659-7225fa80-dd29-11e9-8005-cb2c49f9e62a.png)

any help?
