### ISSUE TITLE
Bug: TLC5971 'num_chips' offset

### ISSUE THREAD

**Issue by JanPetterMG** [esphome/issues#6780]
### The problem

There seems to be an offset bug in the `num_chips` parameter of the `TLC5971` component.

Setup: 3 Adafruit TLC59711 boards, chained together, providing 36 channels total (12 each) of LED outputs.

Issue: Setting `num_chips` to 3 results in 24 operative channels, utilizing only the two first boards in the chain. The third board behaves strangely with the outputs "floating", resulting in random flickering and brightness. Channel 25 (first on the third board) needs to be turned *on* in order to stop this unwanted behavior. Unlogical, I know, but that's what I found out, after building and testing a bunch of different setups..

Workaround: Setting `num_chips` to 4 instead of 3, and the issue is gone. All 36 channels are now operative.

### Which version of ESPHome has the issue?

2025.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.4

### What platform are you using?

RP2040

### Board

Pico 2 W

### Component causing the issue

tlc5971

### YAML Config

```yaml
esphome:
  name: tlc5971_bug

rp2040:
  board: rpipico2w
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git#develop
    version: dev

api:

logger:
  level: VERBOSE

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

light:
  - platform: monochromatic
    name: "00"
    output: out_00
  - platform: monochromatic
    name: "01"
    output: out_01
  - platform: monochromatic
    name: "02"
    output: out_02
  - platform: monochromatic
    name: "03"
    output: out_03
  - platform: monochromatic
    name: "04"
    output: out_04
  - platform: monochromatic
    name: "05"
    output: out_05
  - platform: monochromatic
    name: "06"
    output: out_06
  - platform: monochromatic
    name: "07"
    output: out_07
  - platform: monochromatic
    name: "08"
    output: out_08
  - platform: monochromatic
    name: "09"
    output: out_09
  - platform: monochromatic
    name: "10"
    output: out_10
  - platform: monochromatic
    name: "11"
    output: out_11
  - platform: monochromatic
    name: "12"
    output: out_12
  - platform: monochromatic
    name: "13"
    output: out_13
  - platform: monochromatic
    name: "14"
    output: out_14
  - platform: monochromatic
    name: "15"
    output: out_15
  - platform: monochromatic
    name: "16"
    output: out_16
  - platform: monochromatic
    name: "17"
    output: out_17
  - platform: monochromatic
    name: "18"
    output: out_18
  - platform: monochromatic
    name: "19"
    output: out_19
  - platform: monochromatic
    name: "20"
    output: out_20
  - platform: monochromatic
    name: "21"
    output: out_21
  - platform: monochromatic
    name: "22"
    output: out_22
  - platform: monochromatic
    name: "23"
    output: out_23
  - platform: monochromatic
    name: "24"
    output: out_24
  - platform: monochromatic
    name: "25"
    output: out_25
  - platform: monochromatic
    name: "26"
    output: out_26
  - platform: monochromatic
    name: "27"
    output: out_27
  - platform: monochromatic
    name: "28"
    output: out_28
  - platform: monochromatic
    name: "29"
    output: out_29
  - platform: monochromatic
    name: "30"
    output: out_30
  - platform: monochromatic
    name: "31"
    output: out_31
  - platform: monochromatic
    name: "32"
    output: out_32
  - platform: monochromatic
    name: "33"
    output: out_33
  - platform: monochromatic
    name: "34"
    output: out_34
  - platform: monochromatic
    name: "35"
    output: out_35

output:
  - platform: tlc5971
    id: out_00
    channel: 0
  - platform: tlc5971
    id: out_01
    channel: 1
  - platform: tlc5971
    id: out_02
    channel: 2
  - platform: tlc5971
    id: out_03
    channel: 3
  - platform: tlc5971
    id: out_04
    channel: 4
  - platform: tlc5971
    id: out_05
    channel: 5
  - platform: tlc5971
    id: out_06
    channel: 6
  - platform: tlc5971
    id: out_07
    channel: 7
  - platform: tlc5971
    id: out_08
    channel: 8
  - platform: tlc5971
    id: out_09
    channel: 9
  - platform: tlc5971
    id: out_10
    channel: 10
  - platform: tlc5971
    id: out_11
    channel: 11
  - platform: tlc5971
    id: out_12
    channel: 12
  - platform: tlc5971
    id: out_13
    channel: 13
  - platform: tlc5971
    id: out_14
    channel: 14
  - platform: tlc5971
    id: out_15
    channel: 15
  - platform: tlc5971
    id: out_16
    channel: 16
  - platform: tlc5971
    id: out_17
    channel: 17
  - platform: tlc5971
    id: out_18
    channel: 18
  - platform: tlc5971
    id: out_19
    channel: 19
  - platform: tlc5971
    id: out_20
    channel: 20
  - platform: tlc5971
    id: out_21
    channel: 21
  - platform: tlc5971
    id: out_22
    channel: 22
  - platform: tlc5971
    id: out_23
    channel: 23
  - platform: tlc5971
    id: out_24
    channel: 24
  - platform: tlc5971
    id: out_25
    channel: 25
  - platform: tlc5971
    id: out_26
    channel: 26
  - platform: tlc5971
    id: out_27
    channel: 27
  - platform: tlc5971
    id: out_28
    channel: 28
  - platform: tlc5971
    id: out_29
    channel: 29
  - platform: tlc5971
    id: out_30
    channel: 30
  - platform: tlc5971
    id: out_31
    channel: 31
  - platform: tlc5971
    id: out_32
    channel: 32
  - platform: tlc5971
    id: out_33
    channel: 33
  - platform: tlc5971
    id: out_34
    channel: 34
  - platform: tlc5971
    id: out_35
    channel: 35

tlc5971:
  clock_pin: GPIO18
  data_pin: GPIO19
  num_chips: 3 # 3=buggy, 4=ok. - There's 3 Adafruit TLC59711 boards chained together (12ch each, 36 in total)
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

I have another setup with only 2 boards connected, no issues there, as well as multiple with only one. The issue seems to appear only when there's at least 3 boards connected.

I've checked the logs, nothing unusual.

Side note, in the tests directory, there seems to be 3 different tests with incompatible configuration. Some platforms *(not all)* are referencing a `lat_pin` witch doesn't exist for this component. They probably came from the `tlc5947` component, witch is very similar and serves the same purpose for some related boards. Should probably be removed.
- https://github.com/esphome/esphome/blob/302008356471506fdd37d9a0cbe2548642cbaa15/tests/components/tlc5971/test.esp32-ard.yaml#L4
- https://github.com/esphome/esphome/blob/302008356471506fdd37d9a0cbe2548642cbaa15/tests/components/tlc5971/test.esp8266-ard.yaml#L4
- https://github.com/esphome/esphome/blob/302008356471506fdd37d9a0cbe2548642cbaa15/tests/components/tlc5971/test.rp2040-ard.yaml#L4
