### ISSUE TITLE
RP2040: 'PICO_VSYS_PIN' not defined

### ISSUE THREAD

**Issue by JanPetterMG** [esphome/issues#6781]
### The problem

Build error when using the ADC component on the RP2040 platform.
Complains about `PICO_VSYS_PIN` not being declared in a "nice to have, but non-required" line of code.

I'm using the official Pico W successor, Pico 2 W. Well, I know it's not "supported" according to the documentation, but everything works as expected nevertheless, except the ADC. 
It's probably just a pointer in a file somewhere, that I'm not aware of, because the ADC works, the internal temperature sensor is a perfect example of that. It's just a missing declaration in a helper line that throws the whole build.
I'm willing to try fixing this "issue" myself, If I only knew where to look... Any help is appreciated.

Ref.: https://github.com/esphome/feature-requests/issues/2837#issuecomment-2544595373

### Which version of ESPHome has the issue?

2025.3.0-dev20250218

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.1.4

### What platform are you using?

RP2040

### Board

Pico 2 W

### YAML Config

```yaml
esphome:
  name: adc

rp2040:
  board: rpipico2w
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git#develop
    version: dev

api:

logger:
  level: VERBOSE

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: adc
    pin: 29
    name: "VCC"

  - platform: internal_temperature # Technically a ADC channel too, this part of the build works, and the temperature readings are correct.
    name: "Internal temperature"
```

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/adc/adc_sensor_rp2040.cpp: In member function 'virtual float esphome::adc::ADCSensor::sample()':
src/esphome/components/adc/adc_sensor_rp2040.cpp:89:24: error: 'PICO_VSYS_PIN' was not declared in this scope
   89 |   float coeff = pin == PICO_VSYS_PIN ? 3.0f : 1.0f;
      |                        ^~~~~~~~~~~~~
*** [.pioenvs/adc/src/esphome/components/adc/adc_sensor_rp2040.cpp.o] Error 1
```

### Additional information

Here's the line throwing the (otherwise successful) build:
https://github.com/esphome/esphome/blob/302008356471506fdd37d9a0cbe2548642cbaa15/esphome/components/adc/adc_sensor_rp2040.cpp#L89

**Comment by JanPetterMG** [comment]
Still an issue, but I've found a workaround:
```
esphome:
  platformio_options:
    build_flags:
      - -DPICO_VSYS_PIN=29
```

**Disclaimer:**
While I'm able to compile past this `PICO_VSYS_PIN` "issue", none of my existing devices are able to compile a working build any more, due to what's apparently looks like a typo, completely unrelated to this issue. I've tried to pin to an old "known good" version, but the typo comes from a dependency, so I'm not exactly sure how to "roll back" properly (yet)...
