### ISSUE TITLE
Update 2025.2.0 ESP32 S2 Mini captive portal shows nothing

### ISSUE THREAD

**Issue by ralf2105** [esphome/issues#6784]
### The problem

i have the next problem with the update of esphome builder. when my esp32 s2 mini goes into AP mode, i can connect to it, enter the IP 192.168.4.1 but the captive portal cannot be called up where i can then select my wifi. i can ping the ip but the browser shows no entry. I have already tried everything possible. removed captive_portal, removed webserver, assigned a fixed ip, changed wifi access data etc. as soon as i install the same firmware with a version before 2025.2.0 it works without problems.

### Which version of ESPHome has the issue?

2025.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.4

### What platform are you using?

ESP32

### Board

S2 Mini

### YAML Config

```yaml
wifi:
  ssid: "enteryourwifissid"
  password: "enteryourwifipassword"

  ap:
    ssid: "Backup_WIFI
    password: "123456789#!ABC"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt

```
