### ISSUE TITLE
vl53l0x is marked as failed once I upgraded to ESPHome 2025.2.0

### ISSUE THREAD

**Issue by alexruffell** [esphome/issues#6793]
### The problem

I have a VL53L0X measuring salt level in my water softener tank. It worked fine up until the 2025.2.0 update where the sensor was marked as failed. Going back to the older version fixes the issue. While I don't know why, I found a fix but I believe there is some bug somewhere.

I am using esp-idf:
```
esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: esp-idf
    version: recommended
```

To fix the issue I had to comment out frequency. Before doing so I tried to go down to 100khz but that did not work. Before the update it was happy with 400khz.
```
i2c:
  - id: bus_a
    sda: 16
    scl: 18
    scan: true
    #frequency: 400khz
    #timeout (Optional, Time): Set the I²C bus timeout. Defaults to the framework defaults (100us on esp32 with esp-idf,
    #50ms on esp32 with Arduino, 1s on esp8266 and 1s on rp2040). Maximum on esp-idf is 13ms.
    timeout: 50ms
```

The documentation for the sensor says that the default timeout is 10ms, however the examples on the same page use 200us. I tried both and both work... no idea which one I should actually use as the documentation is contradictory.
```
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: ${update_interval_wifi}
    device_class: signal_strength

  - platform: vl53l0x
    name: "Sensor to salt"
    icon: "mdi:format-vertical-align-bottom"
    #address (Optional, int): Manually specify the i2c address of the sensor. Defaults to 0x29. If an address other the 0x29 is
    #specified, the sensor will be dynamically re-addressed at startup. A dynamic re-address of sensor requires the enable_pin
    #configuration variable to be assigned. If more then one VL53L0X sensor is used on the same i2c bus, a unique address must
    #be specified per sensor.
    address: 0x29
    #enable_pin (Optional, Pin Schema): The pin connected to XSHUT on vl53l0x to enable/disable sensor. Required if not using
    #address 0x29 which is the cause if you have multiple VL53L0X on the same i2c bus. In this case you have to assign a different
    #pin to each VL53L0X.
    update_interval: 2s
    #signal_rate_limit (Optional, float): Set the return signal rate limit in units of MCPS (mega counts per second). This is the
    #minimum signal amplitude detected by the sensor necessary for it to report a valid reading. Setting a lower value may increase
    #the range of the sensor but also increases the chance of getting inaccurate readings. Defaults to 0.25.
    signal_rate_limit: 0.25
    #long_range (Optional, boolean): Set the sensor in long range mode. The signal_rate_limit is overruled to 0.1. Defaults to false.
    long_range: true
    #timeout (Optional, Time): Sensor setup timeout. Default to 10ms.
    timeout: 200us
    id: sensor_to_salt_cm
    state_class: measurement
    unit_of_measurement : "cm"
    accuracy_decimals: 1
    filters:
      - filter_out: nan
      - offset: ${distance_calibration}
      - lambda: return (x*100); #convert from m to cm
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
          send_first_at: 1
      - or:
        - throttle: ${sensor_reporting_throttle}
        - delta: 1.0
    on_value:
      - sensor.template.publish:
          id: saltLevel
          state: !lambda 'return ${distance_sensor_to_bottom} - id(sensor_to_salt_cm).state ;'

      - sensor.template.publish:
          id: saltTankLevel  #Percentage
          state: !lambda |-
                    x = (id(saltLevel).state / ${top_lvl_7})*100;
                    ESP_LOGD("DEBUG", "saltLevel / top_lvl_7 = %f", x);
                    return x;
```

### Which version of ESPHome has the issue?

2025.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.4

### What platform are you using?

ESP32-IDF

### Board

lolin_s2_mini

### Component causing the issue

vl53l0x

### YAML Config

```yaml
substitutions:
  devicename: water-softener
  friendly_devicename: "Water Softener"
  device_description: "Water Softener with TOF200C sensor"
  #Distance between bottom of tank and lower edge of lip where sensor is attached.
  #Edge lip bottom to the bottom of canisater is 96.5cm but sensor is a bit lower down so about 95cm?
  #Value in cm as sensor readings are converted to cm right away
  distance_sensor_to_bottom: "90.0"
  #Whirlpool WHES48 has 9 markers starting from 0. 8th can/should be ignored as it is too far up
  #Distance from bottom to top of level number
  top_lvl_7: "79.5" #100%
  top_lvl_6: "70.5" #89
  top_lvl_5: "61.0" #77
  top_lvl_4: "51.5" #65
  top_lvl_3: "42.0" #53
  top_lvl_2: "32.5" #41
  top_lvl_1: "22.5" #28
  top_lvl_0: "12.5" #16
  #Set to 4hrs. Needs to be very long otherwise it overrides the frequency set in the main sensor
  update_interval_s: "360s"
  #Only reason not to set it very long it for wifi troubleshooting
  update_interval_wifi: "120s"
  distance_calibration: "-0.045" #Add 4.5cm expressed in meters. Why is it so off, used to be less. Degraded over time?
  sensor_reporting_throttle: "360s"

esphome:
  name: ${devicename}
  comment: ${device_description}  
  friendly_name: ${friendly_devicename}

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: esp-idf
    version: recommended
  
wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename}"
    password: !secret iot_wifi_password

#Faster than DHCP. Also use if can't reach because of name change
  manual_ip:
    static_ip: 10.1.3.200
    gateway: 10.1.2.1
    subnet: 255.255.254.0
    dns1: 10.1.0.50
    dns2: 10.1.0.51

#Manually override what address to use to connect to the ESP.
#Defaults to auto-generated value. Example, if you have changed your
#static IP and want to flash OTA to the previously configured IP address.
  use_address: 10.1.3.200
  
logger:
    #baud_rate: 0 #disabled

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"
  
ota:
  - platform: esphome
    #password: !secret ota_password
  
web_server:
  port: 80
  version: 2
  include_internal: true
  ota: false

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: ha_time

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      icon: "mdi:ip-outline"
      update_interval: ${update_interval_wifi}
    dns_address:
      name: "DNS"
      icon: "mdi:dns-outline"
      update_interval: ${update_interval_wifi}
    ssid:
      name: "SSID"
      icon: "mdi:wifi-settings"
      update_interval: ${update_interval_wifi}
    bssid:
      name: "BSSID"
      icon: "mdi:wifi-settings"
      update_interval: ${update_interval_wifi}
    mac_address:
      name: "MAC"
      icon: "mdi:network-outline"
    scan_results:
      name: "Wifi Scan"
      icon: "mdi:wifi-refresh"
      update_interval: ${update_interval_wifi}
      disabled_by_default: true

i2c:
  - id: bus_a
    sda: 16
    scl: 18
    scan: true
    #frequency: 400khz
    #timeout (Optional, Time): Set the I²C bus timeout. Defaults to the framework defaults (100us on esp32 with esp-idf,
    #50ms on esp32 with Arduino, 1s on esp8266 and 1s on rp2040). Maximum on esp-idf is 13ms.
    timeout: 50ms

binary_sensor:
  - platform: status
    name: "Status"
    id: connection_status
    entity_category: diagnostic

  - platform: gpio
    pin:
      number: 7
      mode:
        input: true
        pulldown: true
    name: Input 1

  - platform: gpio
    pin:
      number: 9
      mode:
        input: true
        pulldown: true
    name: Input 2

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: ${update_interval_wifi}
    device_class: signal_strength

  - platform: vl53l0x
    name: "Sensor to salt"
    icon: "mdi:format-vertical-align-bottom"
    #address (Optional, int): Manually specify the i2c address of the sensor. Defaults to 0x29. If an address other the 0x29 is
    #specified, the sensor will be dynamically re-addressed at startup. A dynamic re-address of sensor requires the enable_pin
    #configuration variable to be assigned. If more then one VL53L0X sensor is used on the same i2c bus, a unique address must
    #be specified per sensor.
    address: 0x29
    #enable_pin (Optional, Pin Schema): The pin connected to XSHUT on vl53l0x to enable/disable sensor. Required if not using
    #address 0x29 which is the cause if you have multiple VL53L0X on the same i2c bus. In this case you have to assign a different
    #pin to each VL53L0X.
    update_interval: 2s
    #signal_rate_limit (Optional, float): Set the return signal rate limit in units of MCPS (mega counts per second). This is the
    #minimum signal amplitude detected by the sensor necessary for it to report a valid reading. Setting a lower value may increase
    #the range of the sensor but also increases the chance of getting inaccurate readings. Defaults to 0.25.
    signal_rate_limit: 0.25
    #long_range (Optional, boolean): Set the sensor in long range mode. The signal_rate_limit is overruled to 0.1. Defaults to false.
    long_range: true
    #timeout (Optional, Time): Sensor setup timeout. Default to 10ms.
    timeout: 200us
    id: sensor_to_salt_cm
    state_class: measurement
    unit_of_measurement : "cm"
    accuracy_decimals: 1
    filters:
      - filter_out: nan
      - offset: ${distance_calibration}
      - lambda: return (x*100); #convert from m to cm
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
          send_first_at: 1
      - or:
        - throttle: ${sensor_reporting_throttle}
        - delta: 1.0
    on_value:
      - sensor.template.publish:
          id: saltLevel
          state: !lambda 'return ${distance_sensor_to_bottom} - id(sensor_to_salt_cm).state ;'

      - sensor.template.publish:
          id: saltTankLevel  #Percentage
          state: !lambda |-
                    x = (id(saltLevel).state / ${top_lvl_7})*100;
                    ESP_LOGD("DEBUG", "saltLevel / top_lvl_7 = %f", x);
                    return x;

          
      - sensor.template.publish:
          id: saltTankLevelNumber
          #Numbers in tank are not spaced evenly because tank is narrow at the bottom, and gets wider as you go up so
          #I can't use a simple formula as the one further below in the code:
          state: !lambda |-
                    if (id(saltLevel).state <= ${top_lvl_0}) {
                        x = 0;
                    }
                    else if ((id(saltLevel).state > ${top_lvl_0}) and (id(saltLevel).state <= ${top_lvl_1})) {
                        x = 1;
                    }
                    else if ((id(saltLevel).state > ${top_lvl_1}) and (id(saltLevel).state <= ${top_lvl_2})) {
                        x = 2; 
                    }
                    else if ((id(saltLevel).state > ${top_lvl_2}) and (id(saltLevel).state <= ${top_lvl_3})) {
                        x = 3; 
                    }
                    else if ((id(saltLevel).state > ${top_lvl_3}) and (id(saltLevel).state <= ${top_lvl_4})) {
                        x = 4; 
                    }
                    else if ((id(saltLevel).state > ${top_lvl_4}) and (id(saltLevel).state <= ${top_lvl_5})) {
                        x = 5;
                    }
                    else if ((id(saltLevel).state > ${top_lvl_5}) and (id(saltLevel).state <= ${top_lvl_6})) {
                        x = 6;
                    }
                    else if ((id(saltLevel).state > ${top_lvl_6}) and (id(saltLevel).state <= ${top_lvl_7})) {
                        x = 7;
                    }
                    else if (id(saltLevel).state > ${top_lvl_7}) {
                        x = 8;
                        ESP_LOGD("ALERT", "SALT TANK TOO FULL! LEVEL 7 is 100");
                    }
                    return x;
    
      
#Salt Level   
  - platform: template
    id: saltLevel
    name: "Salt Level"
    icon: "mdi:arrow-expand-vertical"
    #lambda: return ${distance_sensor_to_bottom} - id(sensor_to_salt_cm).state ;
    state_class: measurement
    unit_of_measurement: "cm"
    accuracy_decimals: 1
    update_interval: ${update_interval_s}

#Salt Tank Fill Percentage    
  - platform: template
    id: saltTankLevel
    name: "Salt Tank Level"
    icon: "mdi:arrow-expand-vertical"
    state_class: measurement
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: ${update_interval_s}
    # lambda: |-
    #   auto d = (id(saltLevel).state / ${top_lvl_7})*100;
    #   ESP_LOGD("DEBUG", "top_lvl_7 / saltLevel = %f", d);
    #   return d;

#Manufacturer specific Tank Fill Level  
  - platform: template
    id: saltTankLevelNumber
    name: "Salt Tank Level Number"
    icon: "mdi:arrow-expand-vertical"
    #lambda: return (${distance_sensor_to_bottom} - id(sensor_to_salt_cm).state) / ${cm_per_salt_level_marker};
    state_class: measurement
    unit_of_measurement: "Lvl"
    accuracy_decimals: 0
    update_interval: ${update_interval_s}
    filters:
      - filter_out: nan

button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
    entity_category: diagnostic

  - platform: restart
    name: "Restart"
    entity_category: diagnostic
```

### Anything in the logs that might be useful for us?

```txt

```
