### ISSUE TITLE
Problem with Display

### ISSUE THREAD

**Issue by oli737** [esphome/issues#6798]
### The problem

It compiles but the display does not work anymore after this.
Before this change in esphome it worked without any problem for 24/7 for months.
After installing old Verion with platform: ESP32 it works again as before.

2.8" TFT_LCD 240x320
Driver IC: ILI9341

https://www.amazon.de/DollaTek-LCD-Bildschirm-SPI-Modul-Schnittstelle-TFT-Farbbildschirm/dp/B07QFVBPMX

### Which version of ESPHome has the issue?

2025.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2025.2.4 Supervisor 2025.02.1 Operating System 14.2 Frontend 20250214.0

### What platform are you using?

ESP32

### Board

Wemos ESP 32 D1 Mini

### YAML Config

```yaml
esphome:
name: stock-tft-2-8
friendly_name: xxxxx
comment: 192.168.xxx.xxx
#platform: ESP32
#board: nodemcu-32s
platformio_options:
board_build.mcu: esp32
board_build.f_cpu: 240000000L

esp32:
board: nodemcu-32s

(# Show the config before)
```

### Anything in the logs that might be useful for us?

```txt

```
