### ISSUE TITLE
ADE7880 Reverse Energy Calculation Bug

### ISSUE THREAD

**Issue by giacomo892** [esphome/issues#6801]
### The problem

I'm using a Shelly 3EM converted to esphome but looks like there are problems with the reverse and forward
energy calculations:
See for instance the Phase B from the screenshot:
1)The forward energy gets negative and decreases and soon the current changes flow (I've this CT applied on a photovoltaic inverter output) while the forward energy should not decrease but rather the reverse energy should increase.
2)The reverse energy unit by default is VARh which I don't get, it should he Wh since it is just the returned energy to the grid. 

![Image](https://github.com/user-attachments/assets/cfce128c-5187-40dd-a359-be1c41a679ff)

Available to help for further debug.

Thanks!

### Which version of ESPHome has the issue?

2025.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Latest

### What platform are you using?

ESP8266

### Board

Shelly 3EM

### Component causing the issue

ADE7880

### YAML Config

```yaml
esphome:
  name: shelly-3em
  friendly_name: Shelly 3EM "A"

esp8266:
  board: esp01_1m

# Enable logging
logger:
level: INFO

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: "hhh"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Shelly-3EM"
    password: "0vfggggg"

captive_portal:

web_server:

i2c:
  sda: GPIO12
  scl: GPIO14
  frequency: 200kHz

status_led:
  pin:
    number: GPIO2

switch:
  - id: relay
    name: Shelly 3EM Relay
    platform: gpio
    pin:
      number: GPIO15

binary_sensor:
  - id: button
    name: Shelly 3EM Button
    platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true

sensor:
  - id: ade7880_device
    platform: ade7880
    update_interval: 2s
    irq0_pin:
      number: GPIO13
    irq1_pin:
      number: GPIO5
    reset_pin:
      number: GPIO16
    phase_a:
      name: Phase A
      voltage: 
        name: Voltage
        filters:
          - or:
            - throttle: 500s
            - delta: 1
        accuracy_decimals: 0
      current: 
        name: Current
        filters:
          - or:
            - throttle: 500s
            - delta: 0.1
        accuracy_decimals: 3
      active_power: 
        name: Active Power
        filters:
          - or:
            - throttle: 500s
            - delta: 5
        accuracy_decimals: 0
      power_factor: Power Factor
      forward_active_energy:
        name: Forward Active Energy
        filters:
          - or:
            - throttle: 500s
            - delta: 10
        accuracy_decimals: 0
      reverse_active_energy: 
        name: Reverse Active Energy
        unit_of_measurement: "Wh"
        filters:
          - or:
            - throttle: 500s
            - delta: 10
        accuracy_decimals: 0
      calibration:
        current_gain: 3119480
        voltage_gain: -773306
        power_gain: -1333558
        phase_angle: 168
    phase_b:
      name: Phase B
      voltage: 
        name: Voltage
        filters:
          - or:
            - throttle: 500s
            - delta: 1
        accuracy_decimals: 0
#      current: 
#        name: Current
#        filters:
#          - or:
#            - throttle: 500s
#            - delta: 0.3
#        accuracy_decimals: 1
      active_power: 
        name: Active Power
        filters:
          - or:
            - throttle: 500s
            - delta: 5
        accuracy_decimals: 0
      power_factor: Power Factor
      forward_active_energy:
        name: Forward Active Energy
        filters:
          - or:
            - throttle: 500s
            - delta: 100
        accuracy_decimals: 0
      reverse_active_energy: 
        name: Reverse Active Energy
        unit_of_measurement: "Wh"
        filters:
          - or:
            - throttle: 500s
            - delta: 10
      calibration:
        current_gain: 3104486
        voltage_gain: -731979
        power_gain: -1329670
        phase_angle: 164
    phase_c:
      name: Phase C
      voltage: 
        name: Voltage
        filters:
          - or:
            - throttle: 500s
            - delta: 1
        accuracy_decimals: 0
#      current: 
#        name: Current
#        filters:
#          - or:
#            - throttle: 500s
#            - delta: 0.3
#        accuracy_decimals: 1
      active_power: 
        name: Active Power
        filters:
          - or:
            - throttle: 500s
            - delta: 5
        accuracy_decimals: 0
#      power_factor: Power Factor
      forward_active_energy:
        name: Forward Active Energy
        filters:
          - or:
            - throttle: 500s
            - delta: 100
        accuracy_decimals: 0
      reverse_active_energy: 
        name: Reverse Active Energy
        unit_of_measurement: "Wh"
        filters:
          - or:
            - throttle: 500s
            - delta: 10
      calibration:
        current_gain: 3130199
        voltage_gain: -775362
        power_gain: -1326034
        phase_angle: 156
#    neutral:
#      name: Neutral
#      current: Current
#      calibration:
#        current_gain: 267178313
```

### Anything in the logs that might be useful for us?

```txt

```
