### ISSUE TITLE
Lock doesn't support mode RESTORE_DEFAULT_ON

### ISSUE THREAD

**Issue by JohnMcLear** [esphome/issues#6802]
### The problem

I have a relay on GPIO16

```
output:
  - platform: gpio
    pin:
      number: GPIO16
      mode: input_pullup
      inverted: True
    id: 'relay1'
```

And a lock

```
lock:
  - platform: output
    name: "Lock"
    output: 'relay1'
    id: 'lockymclockface'
```

I can't set ``restore_mode`` like I would to solve this problem with a switch - This means that after reboot the lock unlocks for a few milliseconds until I ``on_boot`` sets the lock back to locked.  Obviously this is not desirable.

I managed to work around this by doing this.  I can only apologize for my hacky solution, this is just to keep me moving forward:
```
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev
  on_boot:
    priority: 200  # Runs early in boot
    then:
      - lambda: gpio_reset_pin(GPIO_NUM_16); // Reset pin state
      - delay: 500ms
      - lambda: gpio_set_direction(GPIO_NUM_16, GPIO_MODE_OUTPUT);
      - lambda: gpio_set_level(GPIO_NUM_16, 0); // Set pin LOW immediately
      - lock.lock:
          id: lockymclockface
```

Am I missing the less hacky way to do this?  I can't modify the PCB which has the ESP32 & Relay on a single unit.

I have to invert the Lock as it's a strike plate (break circuit to unlock).

Thanks for everyone great work on this project :)

### Which version of ESPHome has the issue?

2024.6.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

Single relay board

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```
