### ISSUE TITLE
External component issue - Not loading

### ISSUE THREAD

**Issue by grego1981** [esphome/issues#6809]
### The problem

After the latest HA upgrade of ESPHome, I can no longer use custom platform so I created an external component to use with my project as ACS712 sensor cannot work otherwise. I have created the component and uploaded to a public repo in github [.](https://github.com/grego1981/acs712_exte) Below my yaml code. How can I see if ESPhome is even trying to contact the external component repo??

### Which version of ESPHome has the issue?

2025.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.4

### What platform are you using?

ESP32

### Board

lolin32

### Component causing the issue

external component ACS712

### YAML Config

```yaml
esphome:
  name: oldprdmn
  friendly_name: oldprdmn
  external_components:
    - source:
        type: git
        url: https://github.com/grego1981/acs712_exte
        ref: main  # Or specify a branch/tag

  libraries:
    - https://github.com/RobTillaart/ACS712.git
esp32:
  board: esp32dev
  framework:
    type: arduino
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "mykey"

ota:
  - platform: esphome

wifi:
  networks:
    - ssid: wifi
      password: wifipass

  ap:
    ssid: "Fallback"
    password: "fallback"
web_server:
  port: 80
  version: 2
  include_internal: true
  ota: true  #not in idf
captive_portal:
i2c:
# Example configuration entry
sensor:
  - platform: dht
    pin: GPIO27
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 10s
  - platform: ina226
    shunt_resistance: 0.01 ohm
    bus_voltage:
      name: "Battery Voltage"
      id: volts
      accuracy_decimals: 2
    update_interval: 10s
  - platform: acs712_external
    name: "Current"
    id: current
    unit_of_measurement: A
    accuracy_decimals: 2
  - platform: acs712_external
    name: "Watts"
    id: watts
    unit_of_measurement: W
    accuracy_decimals: 2
  - platform: template
    name: 'Time Left (min)'
    id: timeleft
    unit_of_measurement: minutes
    update_interval: 30s
    lambda: 'return ((id(volts).state * 5.0) / id(watts).state) * 0.5 * 60.0;'
# Wifi signal
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
binary_sensor:
  - platform: gpio
    pin: 
     number: GPIO34
     inverted: true
    name: "AC Input"
    device_class: power
button:
  - platform: restart
    name: "UPS Manager Restart"
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.2.0
INFO Reading configuration /config/esphome/oldprdmn.yaml...
INFO Unable to import component acs712_external.sensor: No module named 'esphome.components.acs712_external'
INFO Unable to import component acs712_external.sensor: No module named 'esphome.components.acs712_external'
Failed config

sensor.acs712_external: [source /config/esphome/oldprdmn.yaml:66]
  
  Platform not found: 'sensor.acs712_external'.
  platform: acs712_external
  name: Current
  id: current
  unit_of_measurement: A
  accuracy_decimals: 2
sensor.acs712_external: [source /config/esphome/oldprdmn.yaml:71]
  
  Platform not found: 'sensor.acs712_external'.
  platform: acs712_external
  name: Watts
  id: watts
  unit_of_measurement: W
  accuracy_decimals: 2
```
