### ISSUE TITLE
prometheus component exposes metrics in format that is not compliant with standard

### ISSUE THREAD

**Issue by m-studer** [esphome/issues#6813]
### The problem

The prometheus component can be used to expose metrics on the `/metrics` endpoint.

Prometheus publish standards for [exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format) and the [metrics naming](https://prometheus.io/docs/practices/naming/).

The ESPHome prometheus component respects neither. 

This is not a bug per se, it is an explicit feature of the current code.

### Which version of ESPHome has the issue?

2025.2.0, but present since the [introduction of the prometheus component](https://github.com/esphome/esphome/pull/1032) in [1.15.0](https://esphome.io/changelog/v1.15.0) 

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

No Home Assistant involved

### What platform are you using?

ESP8266

### Board

D1 mini

### Component causing the issue

prometheus

### YAML Config

```yaml
esphome:
  name: raumfuhler-serverraum-3ug
  friendly_name: Raumfühler Serverraum 3.UG

esp8266:
  board: esp01_1m

# Enable logging
logger:

prometheus:

ota:
  - platform: esphome
    password: !secret datacenter_3ug_ota_pw

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_psk

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Raumfuhler-Serverraum-3Ug"
    password: !secret datacenter_3ug_fallback_ap_pw

captive_portal:

i2c:
  sda: GPIO4
  scl: GPIO5

web_server:
  port: 9123

bme680_bsec:
  address: 0x77

sensor:
  - platform: bme680_bsec
    temperature:
      name: "Serverraum 3.UG Temperatur"
      filters:
        - calibrate_linear:
            - 26.0 -> 23.0
            - 6.2 -> 4.1
    pressure:
      name: "Serverraum 3.UG Luftdruck"
    humidity:
      name: "Serverraum 3.UG Luftfeuchtigkeit"
    iaq:
      name: "Serverraum 3.UG IAQ"
    co2_equivalent:
      name: "Serverraum 3.UG CO2"
    breath_voc_equivalent:
      name: "Serverraum 3.UG VOC"
```

### Anything in the logs that might be useful for us?

```txt
Not a bug
```

### Additional information

The above YAML config produces a metric like this:
```
#TYPE esphome_sensor_value gauge
#TYPE esphome_sensor_failed gauge
esphome_sensor_failed{id="serverraum_3_ug_temperatur",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG Temperatur"} 0
esphome_sensor_value{id="serverraum_3_ug_temperatur",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG Temperatur",unit="°C"} 25.6
esphome_sensor_failed{id="serverraum_3_ug_luftdruck",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG Luftdruck"} 0
esphome_sensor_value{id="serverraum_3_ug_luftdruck",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG Luftdruck",unit="hPa"} 963.4
esphome_sensor_failed{id="serverraum_3_ug_luftfeuchtigkeit",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG Luftfeuchtigkeit"} 0
esphome_sensor_value{id="serverraum_3_ug_luftfeuchtigkeit",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG Luftfeuchtigkeit",unit="%"} 21.4
esphome_sensor_failed{id="serverraum_3_ug_iaq",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG IAQ"} 0
esphome_sensor_value{id="serverraum_3_ug_iaq",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG IAQ",unit="IAQ"} 48
esphome_sensor_failed{id="serverraum_3_ug_co2",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG CO2"} 0
esphome_sensor_value{id="serverraum_3_ug_co2",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG CO2",unit="ppm"} 590.3
esphome_sensor_failed{id="serverraum_3_ug_voc",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG VOC"} 0
esphome_sensor_value{id="serverraum_3_ug_voc",node="raumfuhler-serverraum-3ug",friendly_name="Raumfühler Serverraum 3.UG",name="Serverraum 3.UG VOC",unit="ppm"} 0.7
#TYPE esphome_text_sensor_value gauge
#TYPE esphome_text_sensor_failed gauge
```

This poses 4 issues:

1. all sensor metrics bear the same name, they only differentiate in their tags
2. there is no `HELP` string
3. Lots of static information gets transmitted in every datagram in the tags
4. The `esphome_text_sensor_value` family gets introduced, even though the config includes no text sensor

These four issues have differnt severity

1. Is the most critical. It is a direct violation of the metrics name scheme as published by prometheus. Moreover, as the Prometheus TSDB holds tags in RAM, it increases resource consumption on the consuming server.
2. the `HELP` string is optional, this issue is therefore of low severity
3. Metric tags are not the right place to convey node metadata. This could be addressed by fixing issue 1.  
4. This is not pretty, but compliant with the standard. If a code change were to be done, this could be fixed in the same go.

Without the need for temporary data structures we could make the metrics standard-compliant by giving them this structure:

```
#TYPE serverraum_3_ug_temperatur gauge
serverraum_3_ug_temperatur{name="Serverraum 3.UG Temperatur",unit="°C"} 25.6
#TYPE serverraum_3_ug_luftdruck gauge
serverraum_3_ug_luftdruck{name="Serverraum 3.UG Luftdruck",unit="hPa"} 963.4
#TYPE serverraum_3_ug_luftfeuchtigkeit gauge
serverraum_3_ug_luftfeuchtigkeit{name="Serverraum 3.UG Luftfeuchtigkeit",unit="%"} 21.4
#TYPE serverraum_3_ug_iaq gauge
serverraum_3_ug_iaq{name="Serverraum 3.UG IAQ",unit="IAQ"} 48
#TYPE serverraum_3_ug_co2 gauge
serverraum_3_ug_co2{name="Serverraum 3.UG CO2",unit="ppm"} 590.3
#TYPE serverraum_3_ug_voc gauge
serverraum_3_ug_voc{name="Serverraum 3.UG VOC",unit="ppm"} 0.7
```

Additional changes could be discussed:
1. This removes the `_failed` sensor for each metric. If there were a need for it, it could be kept.
2. Sensors which map to the HomeAssistant state class `total_increasing` could be exposed as a `counter` instead of a `gauge`.
3. introduce a suffix to the name indicating the unit (demanded with `SHOULD` in the standard)
4. Add a `HELP` expression. I see the biggest issue for this in having a good data source.

As it should be obvious by now, the standard-compliant metrics will not be compatible with the current format, so this constitutes a breaking change. There are three ways I see to approach this:
1. Make the change, communicate it in the release notes
2. Introduce a mandatory config property (like `style`) in the `prometheus` yaml config, so at least the breaking change will not be silent
3. leave the `prometheus` component as it is and introduce an `openmetrics` component that is compliant with [the OpenMetrics](https://github.com/prometheus/OpenMetrics/blob/main/specification/OpenMetrics.md) standard. This could optionally go along with a sunsetting of the `prometheus` component.

I would favor option 3 and leave the decision for sunsetting the `prometheus` component to more senior contributors.
