### ISSUE TITLE
Pulse Counter driver is deprecated

### ISSUE THREAD

**Issue by ximex** [esphome/issues#6815]
### The problem

legacy pcnt driver is deprecated, please migrate to use driver/pulse_cnt.h

### Which version of ESPHome has the issue?

2025.4.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

esp32-c6-devkitc-1

### Component causing the issue

pulse_counter

### YAML Config

```yaml
# only relevant config added

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

sensor:
  - platform: pulse_counter
    pin: GPIO3
    name: "PWM Fan RPM"
    id: fan_pulse
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    filters:
      - multiply: 0.5
    update_interval: 5s

output:
  - platform: ledc
    pin: GPIO2
    id: fanhub_pwm

fan:
  - platform: speed
    output: fanhub_pwm
    name: "PWM Fan"
```

### Anything in the logs that might be useful for us?

```txt
In file included from src/esphome/components/pulse_counter/pulse_counter_sensor.h:10,
                 from src/esphome/components/pulse_counter/pulse_counter_sensor.cpp:1:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/pcnt.h:15:2: warning: #warning "legacy pcnt driver is deprecated, please migrate to use driver/pulse_cnt.h" [-Wcpp]
   15 | #warning "legacy pcnt driver is deprecated, please migrate to use driver/pulse_cnt.h"
      |  ^~~~~~~


In file included from src/esphome/components/pulse_counter/pulse_counter_sensor.h:10,
                 from src/esphome/components/pulse_counter/automation.h:5,
                 from src/esphome.h:63,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/pcnt.h:15:2: warning: #warning "legacy pcnt driver is deprecated, please migrate to use driver/pulse_cnt.h" [-Wcpp]
   15 | #warning "legacy pcnt driver is deprecated, please migrate to use driver/pulse_cnt.h"
      |  ^~~~~~~
```
