### ISSUE TITLE
Online Image Fails to Download

### ISSUE THREAD

**Issue by KosieKramer** [esphome/issues#6816]
### The problem

I have a Waveshare 7" ePaper connected to ESP32 board, displaying WiFi QR code.
It's been working perfectly on ESPHome 2024.12.4
Error in the logs reported as "PNG decoder engine not initialized" on ESPHome 2025.2.1

### Which version of ESPHome has the issue?

2025.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.5

### What platform are you using?

ESP32

### Board

Wave ESP32 with E-Paper Interface (W15823)

### Component causing the issue

online_image

### YAML Config

```yaml
esphome:
  name: esp32-epaper-01
  on_boot:
      priority: 200.0
      then:
        - component.update: eink_display
        - wait_until:
            condition:
              lambda: 'return ((id(data_updated) == true) && (id(image_downloaded) == true));'
        - delay: 5s
        - logger.log: "Initial sensor data received: Refreshing display..."
        - lambda: 'id(initial_data_received) = true;'
        - script.execute: update_screen

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  domain: xxxxx
  power_save_mode: none
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: True

substitutions:
  dn: epaper-01
  udn: ePaper 01

globals:
  - id: data_updated
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: image_downloaded
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: initial_data_received
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: recorded_display_refresh
    type: int
    restore_value: yes
    initial_value: '0'
  
script:
  - id: update_screen
    then:
      - lambda: 'id(data_updated) = false;'
      - lambda: 'id(image_downloaded) = false;'
      - component.update: eink_display
      - lambda: 'id(recorded_display_refresh) += 1;'
      - lambda: 'id(display_last_update).publish_state(id(homeassistant_time).now().timestamp);'

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - if:
              condition:
                lambda: 'return ((id(data_updated) == true) && (id(image_downloaded) == true));'
              then:
                - logger.log: "Sensor data updated: Refreshing display..."
                - script.execute: update_screen
              else:
                - logger.log: "No sensors updated - skipping display refresh."

font:
  - file: 'fonts/Aptos-Display.ttf'
    id: font_1
    size: 64
  - file: 'fonts/Aptos-Display.ttf'
    id: font_2
    size: 30
  - file: 'fonts/consola.ttf'
    id: font_2b
    size: 30
  - file: 'fonts/Aptos-Display.ttf'
    id: font_3
    size: 50

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

display:
  - platform: waveshare_epaper
    id: eink_display
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin:
      number: GPIO25
      inverted: True
    reset_pin: GPIO26
    model: 7.50inV2alt
    rotation: 270
    update_interval: never
    lambda: |-
      {
        // int th = 10;
        // it.filled_rectangle(0, 0, th, it.get_height());
        // it.filled_rectangle(0, 0, it.get_width(), th);
        // it.filled_rectangle(0, it.get_height()-th, it.get_width(), it.get_height());
        // it.filled_rectangle(it.get_width()-th, 0, it.get_width(), it.get_height());

        it.image(50, 80, id(mdi_wifi));
        it.print(120, 70, id(font_1), "Guest Wi-Fi");

        if (id(initial_data_received) == false) {
          it.print(35, 690, id(font_2b), "Loading...");
        } else {
          it.image(it.get_width()/2, 170, id(scanme), ImageAlign::CENTER_HORIZONTAL);

          it.image(it.get_width()/2, 286, id(qr_image), ImageAlign::CENTER_HORIZONTAL, COLOR_OFF, COLOR_ON);
          
          it.printf(35, 650, id(font_2b), "Wi-Fi SSID: %s", id(guest_ssid).state.c_str());
          it.printf(35, 690, id(font_2b), "  Password: %s", id(guest_password).state.c_str());
        }
      }

sensor:
  - platform: wifi_signal
    name: ${udn} RSSI
    update_interval: 60s
    state_class: measurement

  - platform: uptime
    name: ${udn} Uptime

  - platform: template
    name: ${udn} Last Update
    device_class: timestamp
    entity_category: "diagnostic"
    id: display_last_update

  - platform: template
    name: ${udn} Display Refresh
    accuracy_decimals: 0
    unit_of_measurement: "Refreshes"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    lambda: 'return id(recorded_display_refresh);'

text_sensor:
  - platform: homeassistant
    entity_id: sensor.guest_ssid
    id: guest_ssid
    on_value:
      then:
        - component.update: image_url
        - lambda: |-
            id(data_updated) = true;

  - platform: homeassistant
    entity_id: sensor.guest_password
    id: guest_password
    on_value:
      then:
        - component.update: image_url
        - lambda: |-
            id(data_updated) = true;

  - platform: homeassistant
    entity_id: image.guest_wifi_qr_code
    attribute: entity_picture
    id: guest_qr_token

  - platform: template
    id: image_url
    lambda: |-
      std::string url = "https://xxxxx" + id(guest_qr_token).state;
      return url;
    update_interval: never
    on_value: 
      then:
        - lambda: 'id(qr_image).set_url(x);'
        - component.update: qr_image

http_request:
  verify_ssl: false

online_image:
  - url: "https://xxxxx"
    format: png
    id: qr_image
    on_download_finished:
      - then:
        - lambda: 'id(image_downloaded) = true;'

image:
  - file: mdi:wifi
    id: mdi_wifi
    resize: 60x60
  - file: mdi:arrow-down-right-bold
    id: mdi_arrow_down_right_bold
    resize: 60x60
  - file: 'images/scanme.png'
    id: scanme

button:
  - platform: restart
    name: ${udn} Restart
  - platform: template
    name: ${udn} Refresh Screen
    entity_category: config
    on_press:
      - script.execute: update_screen
```

### Anything in the logs that might be useful for us?

```txt
As soon as the image download starts, the following error is thrown:
PNG decoder engine not initialized
```
