### ISSUE TITLE
ESP32S3_EYE - esp32_camera - Doesn't work without error

### ISSUE THREAD

**Issue by Rubquila** [esphome/issues#6824]
### The problem

When I program an ESP32-S3 devkit C1 (ESP32-S3-CAM), the compilation apparently goes well and returns no serious errors. The code is loaded onto the board correctly and the log shows no errors either, but the camera entity appears as idle.
Device:
[https://vi.aliexpress.com/item/1005007654767335.html?spm=a2g0o.order_list.order_list_main.152.7b77194dQcNDie&gatewayAdapt=glo2vnm#nav-description](https://vi.aliexpress.com/item/1005007654767335.html?spm=a2g0o.order_list.order_list_main.152.7b77194dQcNDie&gatewayAdapt=glo2vnm#nav-description)

### Which version of ESPHome has the issue?

2025.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.5

### What platform are you using?

ESP32-IDF

### Board

ESP32-S3 devkit C1 (ESP32-S3-CAM)

### Component causing the issue

esp32_camera

### YAML Config

```yaml
esphome:
  name: esphome-web-04ef1c
  friendly_name: Prueba
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


esp32_camera:
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13

  # Image settings
  name: Camera
  max_framerate: 1.0 fps
  idle_framerate: 0.1 fps
  aec2: false
  aec_mode: auto
  ae_level: 0
  aec_value: 300
  agc_mode: auto
  wb_mode: home
  agc_gain_ceiling: 8x
  resolution: 1024x768
  vertical_flip: false
  horizontal_mirror: false
  contrast: 2
  brightness: 2
  saturation: -2
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.2.1
INFO Reading configuration /config/esphome/esphome-web-04ef1c.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.5.1
INFO Updating https://github.com/espressif/esp32-camera.git@v2.0.9
INFO Compiling app...
Processing esphome-web-04ef1c (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - framework-espidf @ 3.50105.0 (5.1.5) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.10.2 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 12.2.0+20230208 
 - toolchain-xtensa-esp32s3 @ 12.2.0+20230208
Reading CMake configuration...
Generating assembly for certificate bundle...
No dependencies
Compiling .pioenvs/esphome-web-04ef1c/src/esphome/components/api/api_connection.cpp.o
[...]
Compiling .pioenvs/esphome-web-04ef1c/src/esphome/components/esphome/ota/ota_esphome.cpp.o
Compiling .pioenvs/esphome-web-04ef1c/src/esphome/components/logger/logger.cpp.o
In file included from src/esphome/components/esp32_camera/esp32_camera.cpp:4:
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'virtual void esphome::esp32_camera::ESP32Camera::dump_config()':
src/esphome/components/esp32_camera/esp32_camera.cpp:58:56: warning: 'camera_config_t::<unnamed union>::pin_sscb_sda' is deprecated: please use pin_sccb_sda instead [-Wdeprecated-declarations]
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |                                                        ^~~~~~~~~~~~
src/esphome/core/log.h:99:101: note: in definition of macro 'esph_log_config'
   99 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:3: note: in expansion of macro 'ESP_LOGCONFIG'
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |   ^~~~~~~~~~~~~
In file included from src/esphome/components/esp32_camera/esp32_camera.h:9,
                 from src/esphome/components/esp32_camera/esp32_camera.cpp:3:
components/esp32-camera/driver/include/esp_camera.h:123:13: note: declared here
  123 |         int pin_sscb_sda __attribute__((deprecated("please use pin_sccb_sda instead")));           /*!< GPIO pin for camera SDA line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:56: warning: 'camera_config_t::<unnamed union>::pin_sscb_sda' is deprecated: please use pin_sccb_sda instead [-Wdeprecated-declarations]
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |                                                        ^~~~~~~~~~~~
src/esphome/core/log.h:99:101: note: in definition of macro 'esph_log_config'
   99 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:3: note: in expansion of macro 'ESP_LOGCONFIG'
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |   ^~~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:123:13: note: declared here
  123 |         int pin_sscb_sda __attribute__((deprecated("please use pin_sccb_sda instead")));           /*!< GPIO pin for camera SDA line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:56: warning: 'camera_config_t::<unnamed union>::pin_sscb_sda' is deprecated: please use pin_sccb_sda instead [-Wdeprecated-declarations]
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |                                                        ^~~~~~~~~~~~
src/esphome/core/log.h:99:101: note: in definition of macro 'esph_log_config'
   99 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:3: note: in expansion of macro 'ESP_LOGCONFIG'
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |   ^~~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:123:13: note: declared here
  123 |         int pin_sscb_sda __attribute__((deprecated("please use pin_sccb_sda instead")));           /*!< GPIO pin for camera SDA line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:75: warning: 'camera_config_t::<unnamed union>::pin_sscb_scl' is deprecated: please use pin_sccb_scl instead [-Wdeprecated-declarations]
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |                                                                           ^~~~~~~~~~~~
src/esphome/core/log.h:99:101: note: in definition of macro 'esph_log_config'
   99 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:3: note: in expansion of macro 'ESP_LOGCONFIG'
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |   ^~~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:127:13: note: declared here
  127 |         int pin_sscb_scl __attribute__((deprecated("please use pin_sccb_scl instead")));           /*!< GPIO pin for camera SCL line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:75: warning: 'camera_config_t::<unnamed union>::pin_sscb_scl' is deprecated: please use pin_sccb_scl instead [-Wdeprecated-declarations]
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |                                                                           ^~~~~~~~~~~~
src/esphome/core/log.h:99:101: note: in definition of macro 'esph_log_config'
   99 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:3: note: in expansion of macro 'ESP_LOGCONFIG'
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |   ^~~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:127:13: note: declared here
  127 |         int pin_sscb_scl __attribute__((deprecated("please use pin_sccb_scl instead")));           /*!< GPIO pin for camera SCL line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:75: warning: 'camera_config_t::<unnamed union>::pin_sscb_scl' is deprecated: please use pin_sccb_scl instead [-Wdeprecated-declarations]
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |                                                                           ^~~~~~~~~~~~
src/esphome/core/log.h:99:101: note: in definition of macro 'esph_log_config'
   99 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:58:3: note: in expansion of macro 'ESP_LOGCONFIG'
   58 |   ESP_LOGCONFIG(TAG, "  I2C Pins: SDA:%d SCL:%d", conf.pin_sscb_sda, conf.pin_sscb_scl);
      |   ^~~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:127:13: note: declared here
  127 |         int pin_sscb_scl __attribute__((deprecated("please use pin_sccb_scl instead")));           /*!< GPIO pin for camera SCL line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'void esphome::esp32_camera::ESP32Camera::set_i2c_pins(uint8_t, uint8_t)':
src/esphome/components/esp32_camera/esp32_camera.cpp:242:17: warning: 'camera_config_t::<unnamed union>::pin_sscb_sda' is deprecated: please use pin_sccb_sda instead [-Wdeprecated-declarations]
  242 |   this->config_.pin_sscb_sda = sda;
      |                 ^~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:123:13: note: declared here
  123 |         int pin_sscb_sda __attribute__((deprecated("please use pin_sccb_sda instead")));           /*!< GPIO pin for camera SDA line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:242:17: warning: 'camera_config_t::<unnamed union>::pin_sscb_sda' is deprecated: please use pin_sccb_sda instead [-Wdeprecated-declarations]
  242 |   this->config_.pin_sscb_sda = sda;
      |                 ^~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:123:13: note: declared here
  123 |         int pin_sscb_sda __attribute__((deprecated("please use pin_sccb_sda instead")));           /*!< GPIO pin for camera SDA line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:242:17: warning: 'camera_config_t::<unnamed union>::pin_sscb_sda' is deprecated: please use pin_sccb_sda instead [-Wdeprecated-declarations]
  242 |   this->config_.pin_sscb_sda = sda;
      |                 ^~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:123:13: note: declared here
  123 |         int pin_sscb_sda __attribute__((deprecated("please use pin_sccb_sda instead")));           /*!< GPIO pin for camera SDA line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:243:17: warning: 'camera_config_t::<unnamed union>::pin_sscb_scl' is deprecated: please use pin_sccb_scl instead [-Wdeprecated-declarations]
  243 |   this->config_.pin_sscb_scl = scl;
      |                 ^~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:127:13: note: declared here
  127 |         int pin_sscb_scl __attribute__((deprecated("please use pin_sccb_scl instead")));           /*!< GPIO pin for camera SCL line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:243:17: warning: 'camera_config_t::<unnamed union>::pin_sscb_scl' is deprecated: please use pin_sccb_scl instead [-Wdeprecated-declarations]
  243 |   this->config_.pin_sscb_scl = scl;
      |                 ^~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:127:13: note: declared here
  127 |         int pin_sscb_scl __attribute__((deprecated("please use pin_sccb_scl instead")));           /*!< GPIO pin for camera SCL line (legacy name) */
      |             ^~~~~~~~~~~~
src/esphome/components/esp32_camera/esp32_camera.cpp:243:17: warning: 'camera_config_t::<unnamed union>::pin_sscb_scl' is deprecated: please use pin_sccb_scl instead [-Wdeprecated-declarations]
  243 |   this->config_.pin_sscb_scl = scl;
      |                 ^~~~~~~~~~~~
components/esp32-camera/driver/include/esp_camera.h:127:13: note: declared here
  127 |         int pin_sscb_scl __attribute__((deprecated("please use pin_sccb_scl instead")));           /*!< GPIO pin for camera SCL line (legacy name) */
      |             ^~~~~~~~~~~~
Compiling .pioenvs/esphome-web-04ef1c/src/esphome/components/logger/logger_esp32.cpp.o
Compiling .pioenvs/esphome-web-04ef1c/src/esphome/components/logger/logger_esp8266.cpp.o
[...]
Compiling .pioenvs/esphome-web-04ef1c/bootloader/soc/esp32s3/rtc_io_periph.c.o
Compiling .pioenvs/esphome-web-04ef1c/bootloader/spi_flash/spi_flash_wrap.c.o
Archiving .pioenvs/esphome-web-04ef1c/bootloader/esp-idf/soc/libsoc.a
Generating partitions .pioenvs/esphome-web-04ef1c/partitions.bin
Generating an empty partition .pioenvs/esphome-web-04ef1c/ota_data_initial.bin
Archiving .pioenvs/esphome-web-04ef1c/bootloader/esp-idf/spi_flash/libspi_flash.a
Archiving .pioenvs/esphome-web-04ef1c/bootloader/esp-idf/micro-ecc/libmicro-ecc.a
Linking .pioenvs/esphome-web-04ef1c/bootloader.elf
Building .pioenvs/esphome-web-04ef1c/bootloader.bin
Creating esp32s3 image...
Successfully created esp32s3 image.
Linking .pioenvs/esphome-web-04ef1c/firmware.elf
RAM:   [=         ]  11.4% (used 37368 bytes from 327680 bytes)
Flash: [=====     ]  45.7% (used 838789 bytes from 1835008 bytes)
Building .pioenvs/esphome-web-04ef1c/firmware.bin
Creating esp32s3 image...
Successfully created esp32s3 image.
esp32_create_combined_bin([".pioenvs/esphome-web-04ef1c/firmware.bin"], [".pioenvs/esphome-web-04ef1c/firmware.elf"])
Wrote 0xdcdf0 bytes to file /data/build/esphome-web-04ef1c/.pioenvs/esphome-web-04ef1c/firmware.factory.bin, ready to flash to offset 0x0
esp32_copy_ota_bin([".pioenvs/esphome-web-04ef1c/firmware.bin"], [".pioenvs/esphome-web-04ef1c/firmware.elf"])
======================== [SUCCESS] Took 351.73 seconds ========================
INFO Successfully compiled program.
INFO Connecting to 192.168.---- port 3232...
INFO Connected to 192.168.----
INFO Uploading /data/build/esphome-web-04ef1c/.pioenvs/esphome-web-04ef1c/firmware.bin (839152 bytes)
Uploading: [============================================================] 100% Done...

INFO Upload took 77.06 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.----- using esphome API
INFO Successfully connected to esphome-web-04ef1c @ 192.168.---- in 7.598s
INFO Successful handshake with esphome-web-04ef1c @ 192.168.---- in 1.097s
[22:52:32][I][app:100]: ESPHome version 2025.2.1 compiled on Feb 27 2025, 22:47:04
[22:52:32][C][wifi:600]: WiFi:
[22:52:32][C][wifi:428]:   Local MAC: ----
[22:52:32][C][wifi:433]:   SSID: [redacted]
[22:52:32][C][wifi:436]:   IP Address: 192.168.----
[22:52:32][C][wifi:439]:   BSSID: [redacted]
[22:52:32][C][wifi:441]:   Hostname: 'esphome-web-04ef1c'
[22:52:32][C][wifi:443]:   Signal strength: -42 dB ▂▄▆█
[22:52:32][C][wifi:447]:   Channel: 9
[22:52:32][C][wifi:448]:   Subnet: 255.255.255.0
[22:52:32][C][wifi:449]:   Gateway: 192.168.----
[22:52:32][C][wifi:450]:   DNS1: 192.168.----
[22:52:32][C][wifi:451]:   DNS2: 192.168.----
[22:52:32][D][api.connection:1446]: Home Assistant 2025.2.5 (192.168.----): Connected successfully
[22:52:32][C][logger:177]: Logger:
[22:52:32][C][logger:178]:   Max Level: DEBUG
[22:53:21][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[22:53:21][D][esp32.preferences:114]: Saving 1 preferences to flash...
[22:53:21][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
```

### Additional information

-The example code for the Freenove board, using external_components, returns additional errors on compilation, so I use esphome's own component.
-The pins are correct according to the manufacturer's schematic.
-I have rebooted and reconnected the power to the device.
-Could it be something related to the idle state? How to disable it?

**Comment by Rubquila** [comment]
Problem solved.
Using the custom external component esp32cam indicated on the reference (MichaKersloot), but also using the framwork type "arduino".

Please, this should be indicated on the esphome [reference](https://esphome.io/components/esp32_camera.html):

```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/MichaKersloot/esphome_custom_components
    components: [ esp32_camera ]
```

Finally the code is:

```
esphome:
  name: esphome-web-04ef1c
  friendly_name: Prueba
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/MichaKersloot/esphome_custom_components
    components: [ esp32_camera ]

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_camera:
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13

  # Image settings
  name: Camera
  aec2: false
  aec_mode: auto
  ae_level: 0
  aec_value: 300
  agc_mode: auto
  wb_mode: home
  agc_gain_ceiling: 8x
  resolution: 800X600
  vertical_flip: false
  horizontal_mirror: false
  contrast: 2
  brightness: 2
  saturation: -2
```
