### ISSUE TITLE
When using PID Autotune: pid.climate took a long time for an operation

### ISSUE THREAD

**Issue by yiancar** [esphome/issues#6825]
### The problem

I have updated to 2025.2.1.
Since then the PID autotune seems to be breaking my temperature sensor readings.

Everything works as normal.
I start the autotune process.
Once the first crossing happens I start getting:
[23:29:48][W][component:237]: Component pid.climate took a long time for an operation (58 ms).
[23:29:48][W][component:238]: Components should block for at most 30 ms.

And my temperature sensors (template and dallas_temp) stop updating.
This causes everything to stay in a stanstill

### Which version of ESPHome has the issue?

2025.2.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

Climate and PID autotune

### YAML Config

```yaml
esphome:
  name: secondary-hp-pump-controller
  friendly_name: Secondary HP Pump Controller

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

captive_portal:

substitutions:
  initial_kp_hp: "1.01859"
  initial_ki_hp: "0.01376"
  initial_kd_hp: "18.84389"

globals:
  - id: ufh_pwd_level
    type: float
    initial_value: "0.5"
  - id: hp_pwd_level
    type: float
    initial_value: "0.5"

number:
  - platform: template
    name: "Minimum UFH Pump Duty"
    id: min_ufh_pump_duty
    initial_value: 0.15
    min_value: 0
    max_value: 1
    step: 0.01
    optimistic: true
    entity_category: config
    restore_value: true
  - platform: template
    name: "Maximum UFH Pump Duty"
    id: max_ufh_pump_duty
    initial_value: 0.90
    min_value: 0
    max_value: 1
    step: 0.01
    optimistic: true
    entity_category: config
    restore_value: true
  - platform: template
    name: "Minimum HP Pump Duty"
    id: min_hp_pump_duty
    initial_value: 0.15
    min_value: 0
    max_value: 1
    step: 0.01
    optimistic: true
    entity_category: config
    restore_value: true
  - platform: template
    name: "Maximum HP Pump Duty"
    id: max_hp_pump_duty
    initial_value: 0.90
    min_value: 0
    max_value: 1
    step: 0.01
    optimistic: true
    entity_category: config
    restore_value: true
  - platform: template
    name: "PID HP Proportional"
    initial_value: ${initial_kp_hp}
    min_value: 0
    max_value: 100
    step: 0.001
    optimistic: true
    entity_category: config
    restore_value: true
    on_value:
      then:
        if:
          condition:
            lambda: 'return x != 1;'
          then:
            - climate.pid.set_control_parameters:
                id: PID_HP_Controller
                kp: !lambda "return x;"
                ki: !lambda "return id(PID_HP_Controller).get_ki();"
                kd: !lambda "return id(PID_HP_Controller).get_kd();"
  - platform: template
    name: "PID HP Integral"
    id: integral
    initial_value: ${initial_ki_hp}
    min_value: 0
    max_value: 1
    step: 0.001
    optimistic: true
    entity_category: config
    restore_value: true
    on_value:
      then:
        if:
          condition:
            lambda: 'return x != 1;'
          then:
           - climate.pid.set_control_parameters:
               id: PID_HP_Controller
               kp: !lambda "return id(PID_HP_Controller).get_kp();"
               ki: !lambda "return x;"
               kd: !lambda "return id(PID_HP_Controller).get_kd();"
  - platform: template
    name: "PID HP Derivative"
    id: derivative
    initial_value: ${initial_kd_hp}
    min_value: 0
    max_value: 100
    step: 0.001
    optimistic: true
    entity_category: config
    restore_value: true
    on_value:
      then:
        if:
          condition:
            lambda: 'return x != 1;'
          then:
           - climate.pid.set_control_parameters:
               id: PID_HP_Controller
               kp: !lambda "return id(PID_HP_Controller).get_kp();"
               ki: !lambda "return id(PID_HP_Controller).get_ki();"
               kd: !lambda "return x;"
    
one_wire:
  - platform: gpio
    pin: GPIO14
    id: onewire_bus_1

sensor:
  - platform: dallas_temp
    one_wire_id: onewire_bus_1
    address: 0xf600000059a31728
    name: LLH Hot HP
    id: LLH_Hot_HP
    update_interval: 15s
    filters:
      - filter_out: NAN

  - platform: dallas_temp
    one_wire_id: onewire_bus_1
    address: 0x0700000038a5e728
    name: LLH Hot UFH
    id: LLH_Hot_UFH
    update_interval: 15s
    filters:
      - filter_out: NAN

  - platform: dallas_temp
    one_wire_id: onewire_bus_1
    address: 0x4600000055dfb128
    name: LLH Cold HP
    id: LLH_Cold_HP
    update_interval: 15s
    filters:
      - filter_out: NAN

  - platform: dallas_temp
    one_wire_id: onewire_bus_1
    address: 0x1800000056e0ef28
    name: LLH Cold UFH
    id: LLH_Cold_UFH
    update_interval: 15s
    filters:
      - filter_out: NAN

  - platform: template
    id: HP_Delta
    name: HP Delta
    unit_of_measurement: "°C"
    update_interval: 50s
    icon: "mdi:delta"
    lambda: |- 
            return (id(LLH_Hot_HP).state - id(LLH_Cold_HP).state);

  - platform: duty_cycle
    name: UFH Downstairs Pump Power
    id: UFH_Down_Pump_Reported_PWM
    device_class: power
    unit_of_measurement: "W"
    update_interval: 30s
    icon: "mdi:lightning-bolt"
    pin: 
      number: GPIO16
      mode:
        input: true
        pullup: true
    filters:
      - lambda: |-
                if (x > 70) {
                  return 0;
                } else {
                  return x;
                }
    on_raw_value:
      then:
        - if:
            condition:
              lambda: 'return id(UFH_Down_Pump_Reported_PWM).state >= 74 && id(UFH_Down_Pump_Reported_PWM).state <= 76;'
            then:
              - lambda: id(UFH_Down_Pump_State).publish_state("Warning");
        - if:
            condition:
              for:
                time: 5s
                condition:
                  lambda: 'return id(UFH_Down_Pump_Reported_PWM).state >= 84 && id(UFH_Down_Pump_Reported_PWM).state <= 86;'
            then:
              - lambda: id(UFH_Down_Pump_State).publish_state("Electrical Error");
        - if:
            condition:
              for:
                time: 30s
                condition:
                  lambda: 'return id(UFH_Down_Pump_Reported_PWM).state >= 89 && id(UFH_Down_Pump_Reported_PWM).state <= 91;'
            then:
              - lambda: id(UFH_Down_Pump_State).publish_state("Electrical Error");
        - if:
            condition:
              lambda: 'return id(UFH_Down_Pump_Reported_PWM).state >= 94 && id(UFH_Down_Pump_Reported_PWM).state <= 96;'
            then:
              - lambda: id(UFH_Down_Pump_State).publish_state("Standby");
        - if:
            condition:
              lambda: 'return id(UFH_Down_Pump_Reported_PWM).state > 0 && id(UFH_Down_Pump_Reported_PWM).state <= 70;'
            then:
              - lambda: id(UFH_Down_Pump_State).publish_state("On");
            else:
              - lambda: id(UFH_Down_Pump_State).publish_state("Power Off");
  - platform: duty_cycle
    name: UFH Upstairs Pump Power
    id: UFH_Up_Pump_Reported_PWM
    device_class: power
    unit_of_measurement: "W"
    icon: "mdi:lightning-bolt"
    update_interval: 30s
    pin: 
      number: GPIO15
      mode:
        input: true
        pullup: true
    filters:
      - lambda: |-
                if (x > 70) {
                  return 0;
                } else {
                  return x;
                }
    on_raw_value:
      then:
        - if:
            condition:
              lambda: 'return id(UFH_Up_Pump_Reported_PWM).state >= 74 && id(UFH_Up_Pump_Reported_PWM).state <= 76;'
            then:
              - lambda: id(UFH_Up_Pump_State).publish_state("Warning");
        - if:
            condition:
              for:
                time: 5s
                condition:
                  lambda: 'return id(UFH_Up_Pump_Reported_PWM).state >= 84 && id(UFH_Up_Pump_Reported_PWM).state <= 86;'
            then:
              - lambda: id(UFH_Up_Pump_State).publish_state("Electrical Error");
        - if:
            condition:
              for:
                time: 30s
                condition:
                  lambda: 'return id(UFH_Up_Pump_Reported_PWM).state >= 89 && id(UFH_Up_Pump_Reported_PWM).state <= 91;'
            then:
              - lambda: id(UFH_Up_Pump_State).publish_state("Electrical Error");
        - if:
            condition:
              lambda: 'return id(UFH_Up_Pump_Reported_PWM).state >= 94 && id(UFH_Up_Pump_Reported_PWM).state <= 96;'
            then:
              - lambda: id(UFH_Up_Pump_State).publish_state("Standby");
        - if:
            condition:
              lambda: 'return id(UFH_Up_Pump_Reported_PWM).state > 0 && id(UFH_Up_Pump_Reported_PWM).state <= 70;'
            then:
              - lambda: id(UFH_Up_Pump_State).publish_state("On");
            else:
              - lambda: id(UFH_Up_Pump_State).publish_state("Power Off");
  - platform: duty_cycle
    name: HP Pump Power
    id: HP_Pump_Reported_PWM
    device_class: power
    unit_of_measurement: "W"
    icon: "mdi:lightning-bolt"
    update_interval: 30s
    pin: 
      number: GPIO10
      mode:
        input: true
        pullup: true
    filters:
      - lambda: |-
                if (x > 70) {
                  return 0;
                } else {
                  return x;
                }
    on_raw_value:
      then:
        - if:
            condition:
              lambda: 'return id(HP_Pump_Reported_PWM).state >= 74 && id(HP_Pump_Reported_PWM).state <= 76;'
            then:
              - lambda: id(HP_Pump_State).publish_state("Warning");
        - if:
            condition:
              for:
                time: 5s
                condition:
                  lambda: 'return id(HP_Pump_Reported_PWM).state >= 84 && id(HP_Pump_Reported_PWM).state <= 86;'
            then:
              - lambda: id(HP_Pump_State).publish_state("Electrical Error");
        - if:
            condition:
              for:
                time: 30s
                condition:
                  lambda: 'return id(HP_Pump_Reported_PWM).state >= 89 && id(HP_Pump_Reported_PWM).state <= 91;'
            then:
              - lambda: id(HP_Pump_State).publish_state("Electrical Error");
        - if:
            condition:
              lambda: 'return id(HP_Pump_Reported_PWM).state >= 94 && id(HP_Pump_Reported_PWM).state <= 96;'
            then:
              - lambda: id(HP_Pump_State).publish_state("Standby");
        - if:
            condition:
              lambda: 'return id(HP_Pump_Reported_PWM).state > 0 && id(HP_Pump_Reported_PWM).state <= 70;'
            then:
              - lambda: id(HP_Pump_State).publish_state("On");
            else:
              - lambda: id(HP_Pump_State).publish_state("Power Off");

binary_sensor:
  - platform: template
    id: HP_Secondary_Pumps_Off
    internal: True
    lambda: |-
            if (id(HP_Down_Pump).state == "Off" && id(HP_Up_Pump).state == "Off") {
              return true;
            } else {
              return false;
            }

text_sensor:
  - platform: template
    name: UFH Downstairs Pump State
    id: UFH_Down_Pump_State
    icon: "mdi:state-machine"
  - platform: template
    name: UFH Upstairs Pump State
    id: UFH_Up_Pump_State
    icon: "mdi:state-machine"
  - platform: template
    name: HP Pump State
    id: HP_Pump_State
    icon: "mdi:state-machine"
  - platform: homeassistant
    id: HP_Down_Pump
    entity_id: sensor.ecodan_ashp_water_pump_13
  - platform: homeassistant
    id: HP_Up_Pump
    entity_id: sensor.ecodan_ashp_water_pump_2

output:
  - platform: ledc
    pin: GPIO17
    frequency: 2000Hz
    id: UFH_Down_Pump_PWM
    inverted: True
  - platform: ledc
    pin: GPIO18
    frequency: 2000Hz
    id: UFH_Up_Pump_PWM
    inverted: True
  - platform: ledc
    pin: GPIO9
    frequency: 2000Hz
    id: HP_Pump_PWM
    inverted: True
  - platform: template
    id: HP_Pump_PWM_Calculated
    type: float
    write_action:
      - output.set_level:
          id: HP_Pump_PWM
          level: !lambda |-
            float level = 0;

            ESP_LOGD("main", "state %f", (state));

            if(id(PID_HP_Controller).action == 0) {
              ESP_LOGD("main", "PID HP Controller Off");
            } else if(id(PID_HP_Controller).action == 2) {
              ESP_LOGD("main", "PID HP Controller Cooling");
              if ((state) == 0) {
                level = id(hp_pwd_level);
              } else {
                level = (((((state)/2)+0.5) * (id(max_hp_pump_duty).state - id(min_hp_pump_duty).state)) + id(min_hp_pump_duty).state) ;
              }
            } else if(id(PID_HP_Controller).action == 3) {
              ESP_LOGD("main", "PID HP Controller Heating");
              if ((state) == 0) {
                level = id(hp_pwd_level);
              } else {
                level = ((((1-(state))/2) * (id(max_hp_pump_duty).state - id(min_hp_pump_duty).state)) + id(min_hp_pump_duty).state);
              }
            } else {
              ESP_LOGE("main", "PID HP Controller Unknown State");
            }

            if (level < id(min_hp_pump_duty).state) {
              ESP_LOGD("main", "PID HP Controller Limiting To Minimum HP Pump Duty (Max Speed)", (id(min_ufh_pump_duty).state));
              level = id(min_hp_pump_duty).state;
            } else if (level > id(max_hp_pump_duty).state) {
              ESP_LOGD("main", "PID HP Controller Limiting To Maximum HP Pump Duty (Min Speed)", (id(max_ufh_pump_duty).state));
              level = id(max_hp_pump_duty).state;
            }

            id(hp_pwd_level) = level;
            ESP_LOGD("main", "HP Pump PWM Calculated %f", level);
            return level;
        
climate:
  - platform: pid
    name: "PID HP Controller"
    id: PID_HP_Controller
    sensor: HP_Delta
    default_target_temperature: 5
    cool_output: HP_Pump_PWM_Calculated
    heat_output: HP_Pump_PWM_Calculated
    control_parameters:
      kp: 0.0
      ki: 0.0
      kd: 0.0
      # kp: ${initial_kp_hp}
      # ki: ${initial_ki_hp}
      # kd: ${initial_kd_hp}
      output_averaging_samples: 3
    visual:
      min_temperature: -10
      max_temperature: 10
      temperature_step: 0.1

button:
  - platform: template
    name: "PID HP Autotune"
    on_press:
      - climate.pid.autotune: PID_HP_Controller
```

### Anything in the logs that might be useful for us?

```txt

```
