### ISSUE TITLE
Shelly Dimmer component - Potential Bug - Incorrect max_brightness range

### ISSUE THREAD

**Issue by forrel35** [esphome/issues#6828]
### The problem

The `shelly_dimmer` component for Shelly Dimmer 2 has a documented `max_brightness` parameter range of 0 to 1000. However, when using higher wattage bulbs (e.g., Philips IR 100W, Exo Terra Intense Basking Spot 50W), setting `max_brightness: 1000` results in the bulbs not reaching their maximum brightness/power.

When the brightness slider is set to 100% in Home Assistant, the bulbs only draw approximately 60% of their declared wattage (Philips IR 100W draws ~60W, Exo Terra Intense Basking Spot 50W draws ~35W).  Visually, it is also apparent that they are not emitting light at their full intensity.

Increasing the `max_brightness` value above 1000 (e.g., 1700, 1860, 2500) in the `shelly_dimmer` component YAML configuration makes it possible to achieve the bulb's full power when the brightness slider is set to 100% in Home Assistant. For the Philips IR 100W bulb, an optimal `max_brightness` value is around 2500.  At this value, a 100% brightness slider in Home Assistant corresponds to a power draw of ~100W by the bulb.

Setting `max_brightness` to values higher than 2500 causes the bulb's full power to be reached even when the brightness slider is set below 100% in Home Assistant (e.g., 100W power draw with the brightness slider set to 90%).

**Potentially, the issue may lie not only in incorrect documentation but also in the component's source code.** It is possible that there is a bug in the component's logic that causes the 0-1000 range to be incorrectly interpreted or implemented, even if the original design intention was correct.

The absence of any error messages in the ESPHome logs during firmware compilation with a `max_brightness` value exceeding 1000 suggests that the component correctly handles higher values, but not necessarily that the logic within the 0-1000 range operates as intended.

When editing the YAML configuration and entering a value exceeding 1000 for `max_brightness`, no red underline or error message is displayed.

**Expected behavior:**

The documentation and/or code of the `shelly_dimmer` component should be verified. **The `max_brightness` parameter range should be correct and allow achieving full brightness/power for various types of bulbs within the 0-1000 range (or another correct range).** If the 0-1000 range is inherently correct, the component's code should be analyzed for logical errors that may be causing the described behavior.  In any case, the component documentation should reflect the actual, correct `max_brightness` range and the potential need to adjust it for higher wattage bulbs if necessary.  The default maximum `max_brightness` value (if 1000 is the default) should be chosen to enable maximum brightness for common bulb types, or the documentation should clearly state the potential need to adjust this value.

**Actual behavior:**

The `max_brightness` range suggested in the documentation (0-1000) is insufficient to achieve the full power of Philips IR 100W and Exo Terra Intense Basking Spot 50W bulbs. Setting `max_brightness: 1000` results in limiting the brightness/power of the bulbs to approximately 60% of their nominal value.

### Steps to reproduce

1. Flash ESPHome firmware onto a Shelly Dimmer 2 device.
2. Configure the `shelly_dimmer` component in the YAML configuration, using the value `max_brightness: 1000`.
3. Connect a Philips IR 100W or Exo Terra Intense Basking Spot 50W bulb to the Shelly Dimmer 2.
4. Start Home Assistant and add the Shelly Dimmer 2 brightness entity to the interface.
5. Set the brightness to 100% using the slider in Home Assistant.
6. Measure the bulb's power consumption using the Shelly Dimmer 2 parameters in Home Assistant or an external power meter.
7. Observe that the power consumption is significantly lower than the bulb's nominal power (approximately 60W for Philips IR 100W and 35W for Exo Terra Intense Basking Spot 50W).
8. Change the `max_brightness` value in the YAML configuration to a higher value, e.g., `max_brightness: 2500`.
9. Re-flash the ESPHome firmware onto the Shelly Dimmer 2.
10. Repeat steps 5-7.
11. Observe that with `max_brightness: 2500` and the brightness slider at 100% in Home Assistant, the power consumption of the Philips IR 100W bulb is close to 100W.

### Which version of ESPHome has the issue?

2025.2.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.5

### What platform are you using?

ESP8266

### Board

Shelly Dimmer 2

### Component causing the issue

shelly_dimmer

### YAML Config

```yaml
substitutions:
  device_name: Shelly Dimmer 2 ID54
  device_name_lower: shelly-dimmer2-id54
  max_temp: "70" # °C

esphome:
  name: ${device_name_lower}

esp8266:
  board: esp01_1m
  restore_from_flash: true

wifi:
  ssid: !secret wifi_iot_parter_ssid
  password: !secret wifi_iot_parter_password
  domain: !secret local_domain

  manual_ip:
    static_ip: 192.168.48.154
    gateway: 192.168.48.5
    subnet: 255.255.255.0
    dns1: 192.168.48.5

  ap:
    ssid: ${device_name_lower}
    password: !secret fallback_hotspot_password
    manual_ip:
      static_ip: 192.168.4.2
      gateway: 192.168.4.1
      subnet: 255.255.255.0

captive_portal:

logger:
    baud_rate: 0

api:
  encryption:
    key: !secret api_password
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${device_name} - IP Address
    ssid:
      name: ${device_name} - Connected SSID
    bssid:
      name: ${device_name} - Connected BSSID
    mac_address:
      name: ${device_name} - Device MAC Address

  - platform: version
    name: ${device_name} - ESPHome Version

switch:
  - platform: gpio
    name: ${device_name} - Automations ON/OFF
    icon: mdi:cogs
    pin: GPIO0 # use dummy GPIO so we can use restore_mode default_on
    restore_mode: RESTORE_DEFAULT_ON
    id: automations_switch

button:
  - platform: restart
    id: restart_button
    name: ${device_name} - Restart

uart:
    tx_pin: 1
    rx_pin: 3
    baud_rate: 115200

light:
    - platform: shelly_dimmer
      name: ${device_name}
      id: dimmer
      power:
        name: ${device_name} - Light Power
      voltage:
        name: ${device_name} - Light Voltage
      current:
        name: ${device_name} - Light Current
      min_brightness: 20
      max_brightness: 2500
      leading_edge: false #choose between leading edge and trailing edge (use trailing edge for led dimming)
      restore_mode: RESTORE_DEFAULT_OFF
      default_transition_length: 1s
      gamma_correct: 2.8 #change this to your liking. Default value is 2.8, but 0 prevents some brightness pops for me
      firmware:
        version: "51.6"
        update: false

sensor: #Important: don't change this sensor-part unless you know what you are doing. These sensors will shut the light down when overheating temperature is reached.
  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: Temperature
    id: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value:
      then:
        - if:
            condition:
              - sensor.in_range:
                  id: temperature
                  above: ${max_temp}
              - light.is_on: dimmer
            then:
              - light.turn_off: 
                  id: dimmer
              - logger.log: "Switch turned off because temperature exceeded ${max_temp}°C"
              - homeassistant.service:
                  service: persistent_notification.create
                  data:
                    title: Message from ${device_name}
                  data_template:
                    message: Switch turned off because temperature exceeded ${max_temp}°C
    on_value_range:
      - above: ${max_temp}
        then:
          - logger.log: "Temperature exceeded ${max_temp}°C"
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${device_name}
              data_template:
                message: Temperature exceeded ${max_temp}°C

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm

  - platform: adc
    id: temp_analog_reading
    pin: A0

  - platform: uptime
    name: ${device_name} - Uptime Sensor
    id: uptime_sec

  - platform: wifi_signal
    name: ${device_name} - WiFi Signal
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
[15:52:46][C][shelly_dimmer:118]: ShellyDimmer:
[15:52:46][C][shelly_dimmer:119]:   NRST Pin: GPIO5
[15:52:46][C][shelly_dimmer:120]:   BOOT0 Pin: GPIO4
[15:52:46][C][shelly_dimmer:122]:   Leading Edge: NO
[15:52:46][C][shelly_dimmer:123]:   Warmup Brightness: 100
[15:52:46][C][shelly_dimmer:126]:   Minimum Brightness: 20
[15:52:46][C][shelly_dimmer:127]:   Maximum Brightness: 2500
[15:52:46][C][shelly_dimmer:129]:   Update Interval: 10.0s
[15:52:46][C][shelly_dimmer:131]:   STM32 current firmware version: 51.6 
[15:52:46][C][shelly_dimmer:132]:   STM32 required firmware version: 51.6
```

### Additional information

![Image](https://github.com/user-attachments/assets/06027fa2-92b5-47e3-83c7-d50caafee86c)

![Image](https://github.com/user-attachments/assets/f226cba2-798d-465f-9a1e-c955d48e42f4)

![Image](https://github.com/user-attachments/assets/043986ce-56ba-4b9a-95e9-8b22c7ad2da2)
