### ISSUE TITLE
H-bridge switch turns on on boot, despite being set to ALWAYS_OFF

### ISSUE THREAD

**Issue by AnyOldName3** [esphome/issues#6833]
### The problem

I've got the h-bridge switch component driving an h-bridge that drives an IR cut filter on a camera (basically a solenoid with a spring that holds the armature at whichever end it was last sent to that you energise with one polarity to put the filter in front of the camera, and the other polarity to remove it). It mostly works perfectly. However, when the device boots, it behaves as if I'd set `restore_mode: ALWAYS_ON` despite having set `ALWAYS_OFF`, applying a pulse to put the solenoid in the on position. It does that even if I set `restore_mode` to something else. I want it to apply the pulse to put it in the off position instead. It knows which position it's sent it to as it always starts by showing as on when it connects to Home Assistant, so it's not just a spurious pulse during the boot sequence.

### Which version of ESPHome has the issue?

2025.2.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2025.1.4

### What platform are you using?

ESP32

### Board

ESP32-CAM with Ai-Thinker configuration

### Component causing the issue

H-bridge Switch

### YAML Config

```yaml
# this is a stripped-down minimal repro

esphome:
  name: NAME_WAS_HERE
  friendly_name: FRIENDLY_NAME_WAS_HERE

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: KEY_WAS_HERE

ota:
  - platform: esphome
    password: PASSWORD_WAS_HERE

wifi:
  <<: !include network-common.yaml

captive_portal:

switch:
  - platform: hbridge
    id: ir_cut
    name: "IR Filter"
    # I'm aware 12 is a strapping pin, but I've tried 14, which isn't, and the issue still occurs
    on_pin: GPIO12
    off_pin: GPIO13
    pulse_length: 50ms
    wait_time: 50ms
    restore_mode: ALWAYS_OFF
```

### Anything in the logs that might be useful for us?

```txt
Nothing *seems* exciting. It says:

[00:24:34][C][switch.hbridge:068]: H-Bridge Switch 'IR Filter'
[00:24:34][C][switch.hbridge:091]:   Restore Mode: always OFF
[00:24:34][C][switch.hbridge:032]:   On Pin: GPIO12
[00:24:34][C][switch.hbridge:033]:   Off Pin: GPIO13
[00:24:34][C][switch.hbridge:034]:   Pulse length: 50 ms
[00:24:34][C][switch.hbridge:036]:   Wait time 50 ms

so it knows the right restore mode even though it's not obeying it.
```
