### ISSUE TITLE
New ESPhome devices will not show/update via HA/Settings notifications - only older/existing?

### ISSUE THREAD

**Issue by NOTORIOUSVR** [esphome/issues#6834]
### The problem

Not exactly sure where/why/how this is happening. I did a quick search on here and google and didn’t immediately turn up anything - more just about not being able to update ESPhome devices at all however that is not my issue.

I can update all of my ESPhome devices through the webconsole, however HA normally notifies of ‘updates’ for all devices including ESPhome devices after updating core ESPhome to a new version.

What I noticed is that all my old devices show up in HA for requiring an update after the core update which is how it’s always been, however the newer devices I’ve added to ESPhome do not show up there. I have to go to the webpanel of ESPhome to update the devices for some reason?

I see functionally no difference in code between and old and new device,.

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.5

### What platform are you using?

ESP8266

### YAML Config

```yaml
name: lr-bt-proxy
  friendly_name: lr_bt_proxy

esp32:
  board: mhetesp32devkit
  framework:
    type: esp-idf

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_pass

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "blahblahblah123"

ota:
  - platform: esphome
    password: "blahblah1234"

web_server:
 port: 80
  
## BLUETOOTH HA PROXY
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```

### Anything in the logs that might be useful for us?

```txt
I wish I could identify when this started (in what version) but others are starting to report the same thing.

https://community.home-assistant.io/t/new-esphome-devices-will-not-show-update-via-ha-settings-notifications-only-older-existing/
```
