### ISSUE TITLE
climate thermostat: setting visual temperature_step to 0.1 triggers an error in HomeAssistant

### ISSUE THREAD

**Issue by robertnino** [esphome/issues#6835]
### The problem

I have a climate thermostat on top of an opentherm component.

```
[...]
climate:
  - platform: thermostat
    [...]
    visual:
      min_temperature: 20
      max_temperature: 30
      temperature_step:
        # target_temperature: 0.1
        # current_temperature: 0.1
      [...]
  - platform: thermostat
    [...]
    visual:
      min_temperature: 20
      max_temperature: 30
      temperature_step: 0.1
      [...]

```

When setting the temperature_step to 0.1, the thermostat does not show in Homeassistant at all.
Looking at the logs, it does show the following error:
```
ERROR (MainThread) [homeassistant.components.mqtt.mixins] Error 'value must be one 
of [0.1, 0.5, 1] for dictionary value @ data['precision']' when processing MQTT discovery message topic: 'homeassistant/climate/opentherm-t1/
central_heating/config', message: '{'temp_step': 0.100000001, 'precision': 0.100000001, 'preset_modes': ['home'], 'temperature_unit': 'C', 'max_humidity': 99, 'mode_command_topic': 'home/opentherm-t1/climate/central_heating/mode/command', 'temperature_command_topic': 'home/openther
m-t1/climate/central_heating/target_temperature/command', 'min_humidity': 30, ...
```

Values `0.5` and `1` work as expected, but for `0.1`, it looks like it is being converted  to `0.100000001`.

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

lolin_c3_mini

### Component causing the issue

climate/thermostat

### YAML Config

```yaml
substitutions:
  name: opentherm-t2
  location: Test

esphome:
  name: $name
  comment: "water heater controller"
  area: ${location}
  name_add_mac_suffix: false
  project:
    name: voinea.tamasi
    version: "2.1.0"
  platformio_options:
    upload_speed: 115200
    board_build.flash_mode: dio
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.flash_size: 4MB

  on_boot:
    priority: 400
    then:
      - light.turn_on:
          id: status_led
          color_mode: RGB
          red: 1
          green: 0
          blue: 0
          brightness: 25%

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

#Enable logging
logger:
  level: DEBUG

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    then:
      - light.turn_on:
          id: status_led
          color_mode: RGB
          red: 0
          blue: 0
          green: 1
          brightness: 25%

globals:
  - id: median_temperature
    type: float
    initial_value: "22.0"
    restore_value: no
  - id: median_humidity
    type: float
    initial_value: "50"
    restore_value: no
  - id: homeassistant_online
    type: bool
    initial_value: "false"
    restore_value: no

mqtt:
  id: mqtt_client
  broker: anta
  username: $location$name
  password: $name$location
  client_id: $name
  topic_prefix: home/$name
  discovery_unique_id_generator: mac
  on_connect:
    then:
      - repeat:
          count: 5
          then:
            - light.turn_on:
                id: status_led
                color_mode: RGB
                red: 0
                green: 1
                blue: 0
                brightness: 5%
            - delay: 200ms
            - light.turn_on:
                id: status_led
                color_mode: RGB
                red: 0
                green: 1
                blue: 0
                brightness: 50%
            - delay: 500ms
      - light.turn_off: status_led

  on_message:
    - topic: home/median/temperature
      qos: 1
      then:
        - globals.set:
            id: median_temperature
            value: !lambda |-
              auto n = parse_number<float>(x);
              return n.has_value() ? n.value() : NAN;
    - topic: home/median/humidity
      qos: 1
      then:
        - globals.set:
            id: median_humidity
            value: !lambda |-
              auto n = parse_number<float>(x);
              return n.has_value() ? n.value() : NAN;
    - topic: homeassistant/status
      qos: 1
      then:
        - globals.set:
            id: homeassistant_online
            value: !lambda |-
              return x == "online";

opentherm:
  out_pin: 1
  in_pin: 0

output:
  - platform: opentherm
    t_set:
      id: temp_ch_setpoint
      min_value: 20
      max_value: 45
      auto_max_value: true
      zero_means_zero: true

number:
  - platform: opentherm
    t_dhw_set:
      name: DHW Setpoint Temp
      min_value: 30.0
      max_value: 60.0
      step: 0.5
      restore_value: true
      entity_category: "diagnostic"
      mode: "box"
    max_t_set:
      id: max_t_set
      name: Max CH Setpoint Temp
      min_value: 30.0
      max_value: 45
      step: 0.5
      restore_value: true
      entity_category: "diagnostic"
      mode: "box"

sensor:
  - platform: wifi_signal
    name: Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: Uptime

  - platform: opentherm
    rel_mod_level:
      name: Relative modulation level
      accuracy_decimals: 0
    t_boiler:
      name: Boiler Water Temperature
      accuracy_decimals: 1
    t_dhw:
      name: DHW Temperature
      accuracy_decimals: 1
    t_ret:
      name: Return Water Temperature
      accuracy_decimals: 1
    t_exhaust:
      name: Boiler Exhaust Temperature
      accuracy_decimals: 1
      filters:
        - lambda: |-
            return float(x) / 256.0;
    t_dhw_set_ub:
      name: DHW Setpoint Max
      accuracy_decimals: 1
    t_dhw_set_lb:
      name: DHW Setpoint Min
      accuracy_decimals: 1
    max_t_set_ub:
      id: ch_setpoint_max
      name: CH Setpoint Max
      accuracy_decimals: 1
    max_t_set_lb:
      name: CH Setpoint Min
      accuracy_decimals: 1
    t_dhw_set:
      name: DHW Setpoint
      accuracy_decimals: 1
    max_t_set:
      name: CH Setpoint Max
      accuracy_decimals: 1
      on_value:
        then:
          - lambda:
              float current = id(temp_ch_setpoint).state;
              if (current > 0.0)
              {
                float o = 0;
                o  = x - id(temp_ch_setpoint).get_min_value();
                o /= id(temp_ch_setpoint).get_max_value() - id(temp_ch_setpoint).get_min_value();

                if (current != x)
                {
                  ESP_LOGD("climate_t", "max_t_set changed Setting output to %f from %f", o, current);
                  id(temp_ch_setpoint).set_level(o);
                }
              }


    oem_diagnostic_code:
      name: OEM Diagnostic Code

  - platform: template
    id: temp_sensor_mix
    lambda: |-
      if (id(mqtt_client)->is_connected() && id(homeassistant_online))
      {
        return id(median_temperature);
      }
      // return id(temperature_sensor).state;
      return NAN;
    update_interval: 60s
    state_class: "measurement"
    device_class: "temperature"


  - platform: template
    id: humidity_sensor_mix
    lambda: |-
      if (id(mqtt_client)->is_connected() && id(homeassistant_online))
      {
        return id(median_humidity);
      }
      return NAN;
    update_interval: 60s

binary_sensor:
  - platform: opentherm
    fault_indication:
      name: Fault Indication
    ch_active:
      name: CH active
    dhw_active:
      name: DHW active
    flame_on:
      name: Flame On
    diagnostic_indication:
      name: Diagnostic Event

switch:
  - platform: restart
    name: Restart

  - platform: opentherm
    ch_enable:
      name: Central Heating Enabled
      restore_mode: RESTORE_DEFAULT_OFF
    dhw_enable:
      name: Domestic Hot Water Enabled
      restore_mode: RESTORE_DEFAULT_ON

light:
  - platform: esp32_rmt_led_strip
    id: status_led
    rgb_order: GRB
    pin: 7
    num_leds: 1
    rmt_channel: 1
    chipset: WS2812

climate:
  - platform: thermostat
    id: climate_t
    internal: false
    name: Central Heating
    sensor: temp_sensor_mix
    humidity_sensor: humidity_sensor_mix
    heat_deadband: 0.1
    heat_overrun: 0.1
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    heat_action:
      then:
        - lambda:
            ESP_LOGD("climate_t", "Ch State (%f) Min (%f) Max (%f)",
                                      id(max_t_set).state,
                                      id(temp_ch_setpoint).get_min_value(),
                                      id(temp_ch_setpoint).get_max_value()
                    );
            float o = 0;
            o  = id(max_t_set).state - id(temp_ch_setpoint).get_min_value();
            o /= id(temp_ch_setpoint).get_max_value() - id(temp_ch_setpoint).get_min_value();

            ESP_LOGD("climate_t", "Setting output to %f", o);

            id(temp_ch_setpoint).set_level(o);

    idle_action:
      - output.set_level:
          id: temp_ch_setpoint
          level: 0
    visual:
      min_temperature: 20
      max_temperature: 30
      temperature_step: 0.1
        # target_temperature: "0.5"
        # current_temperature: "0.5"
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 22.5
```

### Anything in the logs that might be useful for us?

```txt
Mar 03 22:30:25 hass hass[31588]: 2025-03-03 22:30:25.113 ERROR (MainThread) [homeassistant.components.mqtt.mixins] Error 'value must be one 
of [0.1, 0.5, 1] for dictionary value @ data['precision']' when processing MQTT discovery message topic: 'homeassistant/climate/opentherm-t1/
central_heating/config', message: '{'temp_step': 0.100000001, 'precision': 0.100000001, 'preset_modes': ['home'], 'temperature_unit': 'C', 'm
ax_humidity': 99, 'mode_command_topic': 'home/opentherm-t1/climate/central_heating/mode/command', 'temperature_command_topic': 'home/openther
m-t1/climate/central_heating/target_temperature/command', 'min_humidity': 30, 'unique_id': 'xxxxxxxxxxxx-climate-9c3c9c56', 'preset_mode_comm
and_topic': 'home/opentherm-t1/climate/central_heating/preset/command', 'current_humidity_topic': 'home/opentherm-t1/climate/central_heating/
current_humidity/state', 'min_temp': 20, 'availability_topic': 'home/opentherm-t1/status', 'temperature_state_topic': 'home/opentherm-t1/clim
ate/central_heating/target_temperature/state', 'action_topic': 'home/opentherm-t1/climate/central_heating/action/state', 'device': {'name': '
opentherm-t1', 'identifiers': 'xxxxxxxxxxxx', 'suggested_area': 'kitchen', 'model': 'tamasi', 'manufacturer': 'voinea', 'connections': [['mac
', 'xxxxxxxxxxxx']], 'sw_version': '2.1.0 (ESPHome 2024.12.4)'}, 'mode_state_topic': 'home/opentherm-t1/climate/central_heating/mode/state', 
'name': 'Central Heating', 'modes': ['off', 'heat'], 'max_temp': 30, 'preset_mode_state_topic': 'home/opentherm-t1/climate/central_heating/pr
eset/state', 'current_temperature_topic': 'home/opentherm-t1/climate/central_heating/current_temperature/state', 'platform': 'mqtt'}'
```
