### ISSUE TITLE
fatal error: Killed signal terminated program cc1plus (stuck with firmware upgrade)

### ISSUE THREAD

**Issue by guidokieboom** [esphome/issues#6839]
### The problem

While trying to upgrade device with ESPHOME 2024.12 to 2025.2.2 I get fatal errors and firmware update fails. I've tried both wireless (via wifi) and connected to USB on RPi4-2Gb. The free memory of the RPi4 is approx. 1Gb.
Could anyone help me in directing to a solution or other way to obtain support?

<img width="817" alt="Image" src="https://github.com/user-attachments/assets/e4c62fb6-e34c-47d6-8582-f645ca9944af" />

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.03

### What platform are you using?

ESP32

### Board

ESP32WROOM

### YAML Config

```yaml
esphome:
  name: esp32-04
  comment: BT proxy 

esp32:
  board: esp32dev
  framework:
    type: esp-idf

substitutions:
  hostname: esp32-04

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.2.126   
    gateway: 192.168.2.254
    subnet: 255.255.255.0
  ap:
    ssid: "ESP32_04 Fallback Hotspot"
    password: "xxxxxxxxx"

captive_portal:

web_server:
  port: 80

logger: 
  level: DEBUG

api:
  encryption: 
    key: "xxxxxxxxxxxxxxxxxxxxx"
ota:
#  safe_mode: True
  platform: esphome
  password: !secret esphome_password
  
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: false


bluetooth_proxy:


binary_sensor:
  - platform: status
    name: $hostname Status
    
switch:
  - platform: restart
    name: $hostname restart

sensor:
  - platform: wifi_signal
    name: $hostname WiFi
    update_interval: 600s
```

### Anything in the logs that might be useful for us?

```txt
firmware updates have been working well for past years in earlier versions.
```
