### ISSUE TITLE
id(sntp_time).now() returns in UTC after waking up from deep sleep w/o network

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [esphome/issues#6840]
### The problem

After the time have been acquired, I put the ESP32-C3 to sleep. Upon waking up, I check the current hour and determine what action shall be taken.

From the logs, I can see that the `id(currTime).now().hour` was returning UTC time instead of local time (UTC+8), until the network is connected and time synchronized.

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32-IDF

### Board

ESP32C3 Super mini (Using esp32-c3-devkitm-1)

### Component causing the issue

time/sntp

### YAML Config

```yaml
:
  name: music-player
  friendly_name: music player
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

  on_boot: 
    priority: 500
    then:
      # - if:
      #     condition:
      #       - lambda: 'return id(needTurnOffDF);'
      #     then: 
      #       - dfplayer.sleep
      #       - delay: 1s
      #       - output.turn_off: dfplayerEnable
      #       - globals.set: 
      #           id: needTurnOffDF
      #           value: '0'
      - if:
          condition:
            - binary_sensor.is_on: keepAwake
          then:
            - deep_sleep.prevent: deep_sleep_1
            - logger.log:
                format: "Last time fix is %u."
                args: [ 'id(lastTimeFix)']
            - wifi.enable: 
            - globals.set: 
                id: lastTimeFix
                value: '0'
          else: 
            - wifi.disable: 
            - lambda: 'id(lastTimeFix) += 1;'
            - if: 
                condition: 
                  - not: 
                      - time.has_time: 
                then:
                  - lambda: "id(lastTimeFix) = 201;"
            - logger.log:
                format: "Last time fix is %u."
                args: [ 'id(lastTimeFix)']
            - if:
                condition: 
                  - lambda: 'return id(lastTimeFix) > 23;'
                then: 
                  - deep_sleep.prevent: deep_sleep_1
                  - wifi.enable: 
                  - lambda: 'id(loopCounter_1) = 0;'
                  - while:
                      condition: 
                        - lambda: 'return id(lastTimeFix) > 0;'
                        - lambda: 'return id(loopCounter_1) < 60;'                               
                      then:
                        - logger.log:
                            format: "Last time fix is %u, waiting for %d/300"
                            args: [ 'id(lastTimeFix)', 'id(loopCounter_1)*5']
                        - delay: 5s
                        - lambda: 'id(loopCounter_1) += 1;'
                  - globals.set: 
                      id: lastTimeFix
                      value: '0'
                  - delay: 4s
                  - deep_sleep.allow: deep_sleep_1
            - deep_sleep.prevent: deep_sleep_1
            - button.press: playTargetSong
            - delay: 5s
            - if:
                condition: 
                  - lambda: 'return id(needTurnOffDF);'
                then: 
                  - delay: !lambda 'return (id(songLengths)[id(currTime).now().hour]) * 1000 + 500;'
                  - logger.log: "Finished playing song"
                  - dfplayer.sleep
                  - delay: 1s
                  - output.turn_off: dfplayerEnable
                  - globals.set: 
                      id: needTurnOffDF
                      value: '0'
                  - button.press: sleepTilNextHour
                  
                else: 
                  - deep_sleep.allow: deep_sleep_1
                  - if:
                      condition: 
                        - time.has_time: 
                        - lambda: 'return id(currTime).now().hour >= 18;'
                      then:
                        - deep_sleep.enter: 
                            id: deep_sleep_1
                            sleep_duration: 14h
                      else: 
                        - logger.log: 'No need to play song now, sleeping until next hour'
                        - button.press: sleepTilNextHour
                                 

                                
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

globals:
  - id: lastTimeFix
    type: unsigned char
    restore_value: True
    initial_value: '200'
  - id: needTurnOffDF
    type: bool
    restore_value: True
    initial_value: '0'
  - id: targetVolume
    type: unsigned char
    restore_value: True
    initial_value: '10'
  - id: songLengths
    type: short[24] # no need unsigned, already long enough 
    restore_value: False
    # Song lengths in seconds
    #                0    1    2    3    4    5    6    7    8    9    10   11   12   13   14   15   16   17   18   19   20   21   22   23
    initial_value: '{0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   253, 228, 182, 231, 214, 259, 213, 210, 285,   0,   0,   0,   0}'
  - id: loopCounter_1
    type: unsigned char
    restore_value: False
    initial_value: '0'
  - id: loopCounter_2
    type: unsigned char
    restore_value: False
    initial_value: '0'

  
# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED"
  reboot_timeout: 0s
  actions:
    - action: music_player_set_volume
      variables:
        volume_0_30: int
      then:
        - dfplayer.set_volume: !lambda 'return volume_0_30;'
        - lambda: 'id(targetVolume) = volume_0_30;'
    - action: dfplayer_play_mp3
      variables:
        file: int
      then:
        - output.turn_on: dfplayerEnable
        - delay: 1s
        - dfplayer.set_device: TF_CARD
        - delay: 0.25s
        - dfplayer.set_volume: !lambda 'return id(targetVolume);'
        - delay: 0.25s
        - dfplayer.play_mp3: !lambda 'return file;'
    - action: dfplayer_off
      then:
        - dfplayer.sleep
        - delay: 2s
        - output.turn_off: dfplayerEnable
    - action: dfplayer_reset
      then:
        - output.turn_on: dfplayerEnable
        - delay: 1s
        - dfplayer.reset



ota:
  - platform: esphome
    password: "REDACTED"

wifi:
  enable_on_boot: True
  output_power: 8.5
  # fast_connect: True
  networks: 
    - bssid: REDACTED_BSSID_1
      password: !secret wifi_password
      priority: 8
      manual_ip: 
        gateway: 192.168.0.1
        static_ip: REDACTED
        subnet: 255.255.255.0
        dns1: REDACTED
    - bssid: REDACTED_BSSID_2
      password: !secret wifi_password
      priority: 6
      manual_ip: 
        gateway: 192.168.0.1
        static_ip: REDACTED
        subnet: 255.255.255.0
        dns1: REDACTED
  power_save_mode: none

uart:
  baud_rate: 9600
  # rx_pin: 20
  tx_pin: 21

dfplayer:
  id: player
  # on_finished_playback:
  #   then:
  #     logger.log: 'Playback finished event'

time:
  # - platform: homeassistant
  - platform: sntp
    id: currTime
    # UTC+8
    timezone: Asia/Hong_Kong
    on_time_sync: 
      then:
        - lambda: "id(lastTimeFix) = 0;"
        - delay: 3s
        - if:
            condition: 
              - time.has_time: 
              - binary_sensor.is_off: keepAwake
            then: 
              - wifi.disable: 
            
output:
  - platform: gpio
    id: onboard_led
    pin: 8
  - platform: gpio
    id: dfplayerEnable
    pin: 
      number: 3
      mode: 
        output: True
        pulldown: True

binary_sensor:
  - platform: gpio
    pin: 
      number: 4
      mode:
        input: True
        pulldown: True
    id: mute_switch
    name: Mute Music Player
  - platform: gpio
    pin: 
      number: 1
      allow_other_uses: True
      mode:
        input: True
        pulldown: True
    id: keepAwake
    filters: 
      - delayed_off: 
          seconds: 2
    on_press: 
      then:
        - deep_sleep.prevent: deep_sleep_1
        - output.turn_on: onboard_led
    on_release: 
      then:
        - logger.log: "Released keep awake"
        - while:
            condition: 
              - or: 
                - not: 
                  - wifi.connected: 
                - not: 
                    - time.has_time:               
            then:
              - delay: 5s
        - output.turn_off: onboard_led
        - deep_sleep.allow: deep_sleep_1
        - button.press: sleepTilNextHour

sensor:
  - platform: adc
    pin: 0
    name: Music Player Battery Voltage
    accuracy_decimals: 2
    attenuation: 2.5db
    filters: 
      # - offset: -0.052
      - multiply: 4.081373
          
# Treat template buttons as async functions
button:
  # Problem: Play target song does not play as expected
  # Investigating: id(currTime).now().hour returns UTC unexpectedly
  - platform: template
    id: playTargetSong
    name: "Play target song"
    on_press: 
      then:
        # debug
        - logger.log:
            format: "Hour: %d, DoW: %d"
            args: [ 'id(currTime).now().hour', 'id(currTime).now().day_of_week']
        - if: 
            condition: 
              - time.has_time: 
              - lambda: 'return id(currTime).now().hour >= 11;' # After 11:00
              - lambda: 'return id(currTime).now().hour <= 18;' # Before 18:59 (if change this, change 14h as well)
              - lambda: 'return id(currTime).now().day_of_week >= 2;'  # Monday (1 is sunday)
              - lambda: 'return id(currTime).now().day_of_week <= 6;'  # Friday
              # - binary_sensor.is_off: mute_switch
            then: 
              - output.turn_on: dfplayerEnable
              - delay: 2s
              - dfplayer.set_device: TF_CARD
              - delay: 0.3s
              - dfplayer.set_volume: !lambda 'return (id(mute_switch).state ? 0 : id(targetVolume));'
              - delay: 0.3s
              - dfplayer.play_mp3: !lambda 'return id(currTime).now().hour;'
              - globals.set: 
                  id: needTurnOffDF
                  value: '1'
            else: 
              - globals.set: 
                  id: needTurnOffDF
                  value: '0'
  - platform: template
    id: sleepTilNextHour
    on_press: 
      then:
        - dfplayer.sleep
        - delay: 1s
        - output.turn_off: dfplayerEnable
        - lambda: 'id(loopCounter_2) = 0;'
        - while: 
            condition:
              - not: 
                  - time.has_time: 
              - lambda: 'return id(loopCounter_2) < 60;'
            then: 
              - deep_sleep.prevent: deep_sleep_1
              - logger.log:
                  format: "Waiting for time, loop %d of 60"
                  args: ['id(loopCounter_2)']
              - output.turn_on: onboard_led
              - delay: 0.2s
              - output.turn_off: onboard_led
              - delay: 4.8s
              - lambda: 'id(loopCounter_2) += 1;'
        # But this one prints local time...
        - lambda: |-          
            char str[30];
            time_t curTime = id(currTime).now().timestamp;
            strftime(str, sizeof(str), "%H:%M:%S (%a)", localtime(&curTime));
            ESP_LOGD("custom", "Time is now: %s", str);
        - logger.log:
            format: "Sleeping for %d s"
            args: [ '(((59 - id(currTime).now().minute)*60) + (59 - id(currTime).now().second))']
        - deep_sleep.allow: deep_sleep_1
        - deep_sleep.enter: 
            id: deep_sleep_1
            sleep_duration: !lambda |-
              auto dur = (((59 - id(currTime).now().minute)*60) + (59 - id(currTime).now().second)) *1000;
              return (dur > 0) ? dur : 1000;
                  
                  
deep_sleep: 
  id: deep_sleep_1
  run_duration: 30s
  sleep_duration: 24h
  wakeup_pin: 
      number: 1
      allow_other_uses: True
```

### Anything in the logs that might be useful for us?

```txt
[17:57:57][D][wifi:472]: Disabling WIFI...
[17:57:57][D][main:045]: Last time fix is 1.
[17:57:57][D][button:010]: 'Play target song' Pressed.
[17:57:57][D][main:1018]: Hour: 9, DoW: 6
...
[17:58:02][I][wifi:617]: WiFi Connected!
...
[17:58:02][D][sntp:066]: Synchronized time: 2025-03-07 17:58:01
...
[17:58:03][D][custom:358]: Time is now: 17:58:03 (Fri)
[17:58:03][D][main:361]: Sleeping for 116 s
```

### Additional information

The esp is supposed to instruct a DFPlayer Mini to play a song every hour between 11:00 and 18:00 local time on Mon-Fri. To conserve battery, deep_sleep is used whenever it it not playing anything.
