### ISSUE TITLE
PM1006 Sensor uses the wrong GPIO pin

### ISSUE THREAD

**Issue by konomikitten** [esphome/issues#6841]
### The problem

I'm currently using the Ikea VINDRIKTNING Air quality sensor with the LOLIN D1 mini v4.0.0. When the Ikea VINDRIKTNING Air quality sensor was added to ESPHome the commit was made in mind with the LOLIN D1 mini V3.1.0. This version of the D1 mini has D2 as GPIO4. The problem is in the latest version of the D1 mini D2 is GPIO2, which obviously makes a lot more sense.

This leads to the configuration using the wrong pin:

```yml
uart:
  rx_pin: D2
  baud_rate: 9600
```

output from config:

```yml
uart:
- rx_pin:
    number: 4
    mode:
      input: true
      output: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  baud_rate: 9600
  rx_buffer_size: 256
  stop_bits: 1
  data_bits: 8
  parity: NONE
```

Changing the config to be:

```yml
uart:
  rx_pin:
    number: 2
  baud_rate: 9600
```

Produces the correct configuration:

```yml
uart:
- rx_pin:
    number: 2
    mode:
      input: true
      output: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  baud_rate: 9600
  rx_buffer_size: 256
  stop_bits: 1
  data_bits: 8
  parity: NONE
```

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

LOLIN D1 mini v4.0.0

### Component causing the issue

uart

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

Original commit: https://github.com/esphome/esphome/pull/2038
LOLIN D1 mini v4.0.0: https://www.wemos.cc/en/latest/d1/d1_mini.html
LOLIN D1 mini v3.1.0: https://www.wemos.cc/en/latest/d1/d1_mini_3.1.0.html
