### ISSUE TITLE
ESP8266 - Captive Portal Blank Page

### ISSUE THREAD

**Issue by hiscorebob** [esphome/issues#6842]
### The problem

Captive Portal in AP Mode is blank. A forced refresh only shows "data:text/html" on an Android Mobile Device.
Also the page http://192.168.4.1 does not load in a browser when connected to the AP.

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini v4.0

### Component causing the issue

captive_portal

### YAML Config

```yaml
wifi:
  ssid: "WIFINAME"
  password: "PASSWORD"
  fast_connect: True
  reboot_timeout: 0s
  ap:
    ssid: "APNAME"
    password: password
    #ap_timeout: 20s
captive_portal:

web_server:
  log: False
  ota: False
  version: 3
```

### Anything in the logs that might be useful for us?

```txt
No error in logs. AP Web Server Startup is logged, as well as connected Client
```

### Additional information

Tried also with web_server version2, same thing.
