### ISSUE TITLE
Display doesn't work anymore after update to 2025.2 (ili9xxx)

### ISSUE THREAD

**Issue by andreas-bulling** [esphome/issues#6843]
### The problem

I have two displays based on the ili9xxx platform (model: ILI9342). Everything was working fine with the 2025.0 (and I think also 2025.1) but after updating to 2025.2 the display, upon a reboot, only shows noisy/scrumbled pixels instead of the text I want to show. I didn't change the yaml so the error must be caused by the new version. The touchscreen still works as before. 

This is what I see in the logfile now:
`[21:31:02][E][component:082]:   Component display is marked FAILED`

And I found an old issue about this. Thing is - it was working fine before and the display plus esp32 is an integrated package so I'd assume the esp should be powerful enought...

https://github.com/esphome/issues/issues/4315

Here is the relevant yaml snippet (I guess)

```
display:
  - platform: ili9xxx
    model: ILI9342
    spi_id: lcd
    cs_pin:
      number: GPIO15
      ignore_strapping_warning: true
    dc_pin:
      number: GPIO02
      ignore_strapping_warning: true
    rotation: 180
    color_order: RGB
    invert_colors: false
    lambda: |-
       SOME_DISPLAY_CODE

# Define a monochromatic, dimmable light for the backlight
light:
  - platform: monochromatic
    output: backlight_pwm
    name: "${device_upper} Backlight"
    id: back_light
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: rgb
    name: "${device_upper} LED"
    red: output_red
    id: led
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF
```

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```
