### ISSUE TITLE
Thermostat climate startup_delay not taken into account when used with IR remote climate

### ISSUE THREAD

**Issue by Malakai-DB** [esphome/issues#6844]
### The problem

The `startup_delay` from the thermostat component isn't taken into account when there is an IR remote climate component defined.
When the board boots, it sends some IR commands to the AC unit (the AC unit beeps a few times, but stays off), without waiting for the `startup_delay` to pass. In my case, I have defined `min_cooling_off_time` to `60s`, and I would expect the board to wait that amount of time before sending those IR commands at boot.

### Which version of ESPHome has the issue?

2024.12.4

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

Orvibo CT10_v1.7

### Component causing the issue

thermostat / climate_ir

### YAML Config

```yaml
substitutions:
  name: my-ir
  friendly_name: My-IR
  receiver_pin: GPIO05
  transmitter_pin: GPIO14
  homeassistant_sensor_name: "Room temperature"
  homeassistant_sensor_id: room_temperature
  receiver_id: ir_receiver
  climate_ir_platform: ballu
  climate_ir_name: "My AC"
  climate_ir_id: my_ac
  climate_thermostat_name: "My Cooling"
  climate_thermostat_id: my_cooling
  preset_startup_target_temp: "27.5 °C"
  preset_home_target_temp: "26.5 °C"
  preset_away_target_temp: ${preset_startup_target_temp}
  climate_control_id: my_ac

esp8266:
  board: esp01_1m

api:
  encryption:
    key: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${name}
  ap:
    ssid: "${friendly_name} Fallback AP"
    password: !secret ap_password

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

logger:

captive_portal:

mdns:
  disabled: true

button:
  - platform: restart
    name: "Restart"

sensor:
  - platform: uptime
    type: seconds
    name: "Uptime"
  - platform: wifi_signal
    name: "RSSI"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""
    icon: "mdi:access-point"

text_sensor:
  - platform: wifi_info
    ssid:
      name: "SSID"
      icon: "mdi:access-point-network"
      update_interval: 60s
    bssid:
      name: "BSSID"
      icon: "mdi:access-point-network"
      update_interval: 60s

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Paris

remote_receiver:
  id: "${receiver_id}"
  pin: 
    number: "${receiver_pin}"
    inverted: true
    mode:
      input: true
      pullup: true

remote_transmitter:
  pin: "${transmitter_pin}"
  carrier_duty_percent: 50%

sensor:
  - platform: homeassistant
    name: "${homeassistant_sensor_name}"
    entity_id: "sensor.${homeassistant_sensor_id}"
    id: "${homeassistant_sensor_id}"

climate:
  - platform: "${climate_ir_platform}"
    name: "${climate_ir_name}"
    id: "${climate_ir_id}"
    supports_heat: false
    receiver_id: "${receiver_id}"
    visual:
      min_temperature: 22
      max_temperature: 29
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
  - platform: thermostat
    name: "${climate_thermostat_name}"
    id: "${climate_thermostat_id}"
    sensor: "${homeassistant_sensor_id}"
    visual:
      min_temperature: 22
      max_temperature: 29
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
    cool_deadband: 1
    cool_overrun: 0
    min_cooling_off_time: 60s
    min_cooling_run_time: 60s
    min_fan_mode_switching_time: 10s
    min_idle_time: 30s
    startup_delay: true
    default_preset: startup
    on_boot_restore_from: memory
    preset:
      - name: startup
        default_target_temperature_high: "${preset_startup_target_temp}"
        fan_mode: 'AUTO'
        swing_mode: 'OFF'
        mode: 'COOL'
      - name: home
        default_target_temperature_high: "${preset_home_target_temp}"
      - name: away
        default_target_temperature_high: "${preset_away_target_temp}"
    cool_action:
      - climate.control:
          id: "${climate_control_id}"
          mode: 'COOL'
    target_temperature_change_action:
      - climate.control:
          id: "${climate_control_id}"
          target_temperature: !lambda "return int(id(${climate_thermostat_id}).target_temperature);"
    idle_action:
      - climate.control:
          id: "${climate_control_id}"
          mode: 'OFF'
    fan_mode_auto_action:
      - climate.control:
          id: "${climate_control_id}"
          fan_mode: 'AUTO'
    fan_mode_low_action:
      - climate.control: 
          id: "${climate_control_id}"
          fan_mode: 'LOW'
    fan_mode_medium_action:
      - climate.control: 
          id: "${climate_control_id}"
          fan_mode: 'MEDIUM'
    fan_mode_high_action:
      - climate.control: 
          id: "${climate_control_id}"
          fan_mode: 'HIGH'
    swing_off_action:
      - climate.control: 
          id: "${climate_control_id}"
          swing_mode: 'OFF'
    swing_both_action:
      - climate.control: 
          id: "${climate_control_id}"
          swing_mode: 'BOTH'
    swing_vertical_action:
      - climate.control: 
          id: "${climate_control_id}"
          swing_mode: 'VERTICAL'
    swing_horizontal_action:
      - climate.control: 
          id: "${climate_control_id}"
          swing_mode: 'HORIZONTAL'
```

### Anything in the logs that might be useful for us?

```txt
rl<break>
$<0xdc><0x9f>|<break>
<0x84>l<0xe0>|<0x03><0x0c><0x04><0x0c><0x84><0x0c>$<0xec><0x04>b|<0x8f><0x82><0x03><0xe4><0x1b><0x92>s<0xb2><0x9c><0x1f><0x83><0x04>b<0x84><0xfb>on<0xbe><break>
$oN<0xdc><0xe3><0xec><0x0c>c<0x1c>plHb<0x07>l3$<break>
N<0xb8><0x02><0x82><0x02><0x0c><0x04><0x86><0x8e>l<0x04><0x8c><0x9c><0x04><0x0c><0x04>b<0x04>n<0xe2>|<0x02><0xec><0x04><0x8e><0x84><0x04><0x8f>p<0x0c><0x84><0xfb>Nn<0xef><break>
l<0x84><0x8f>l <0x03><0xdf><0xdb><0xdb>oo<0xef>o<0x7f><0xfb><0xef><0xf2>o{<0xf7><0xdb><0xdb>o<0xee><0xf7>{<0xb7><0xdf><0xce>n~<0xfb>o<0xfe><0x1c><0x02><0x04><0x0c>r<0x8c><0x9c><0xdc><0x9c><0x1c><0x80><0x8c><0x02><0x0c>#<0x0c>o<0xe3>|<0x02><0x04><0x8e><0x80><0x04>b<0x84><0xfb>on<0xee><0x02><0x04><0x0c>$`<0x02><0x90><0x1b><0x12>no<0x04>l <0x02><0x0f><0x02>n{<0x8f><0x92><0xdb>N<0x0c><0x08>0<0x0c><0x04>6`<0x02><0x0e>{$<0x8e><0xef><break>
<0x0c><0x0c><0x10><0x1c><0x04><0x92>`<0x03><0xdc><0x03><0x0c><0x04><0x0c><0x04><0x8f><0x90>d<0xdc>l <0x03><0xfc><0x82>n<0x9c><0x0f>l<break>
<0xff><break>
<0xff><break>
<0xef><0xfb><0xfb><0xef><0x7f><0xfb><0xfb>o<0xef><0x7f><0xdb>{<0xfb><0xfb>o<0x7f><0xef><0xef><0xf7><0xb7>w<0xdf>{7<0xbe>s<0xdb><0x9b><0xf3><0xf7><0x9f><0xbe><0xe3>r<0x93><0x02>$<0xdc>o<0xe0><0x0c><0x83>o<0xc2><0x03><0x0c>$`<0x03><0x84><0xe2>{<0x92>l<0x8c>$<0x1b><0x84><0x04><0x0c><0x04><0xfe><0x1b>[0<0x1b>32m[I][lggger<0x9a><0x9a><0xa2><0xea><0xe9> Lgg initialized<0x1b>[0m
<0x1b>[0;35m[C][safe_mode:079]: There have been 0 suspected unsuccessful boot<0xbf>}twum<0x7f>w{<0xdb>[<0xbf>m<0xed><0xeb><0xdb>[<0xbf><0xbb><0xbb><0xbb>m[m][}<0x7f>~<0xbb><0xcb><0xca><0xea><0xe9><0xbf>Sunning>vlrough setup()...<0x1b>[0m
<0x1b>[0;35m[C][remote_receiver.esp8266:034]: Setting <0xb5><0x02><0x92><0x95><0xb5><0x9d><0xd1><0x95><0x81>Receiver...<0x1b>[0m
<0x1b>[0;32m[I][thermostat.climate:1026]: Custom preset startup requested<0x1b>[0m
<0x1b>[0;36m[D][clmm}wu;<0xbf><0xbd><0xbd>]<0xbb><0xbf><0xb7>omwmow<0xbf>}{<0xb7><0xbf><0xad><0xbf>[<0xb5><0x97>W<0xcb><0xeb>m[0m<0xed><0xcb><0x9b>[<;36m[D][climate:015]:   Mode: OFF<0x1b>[0m
<0x1b>[0;36m[D][remote_transmitter:075]<0x1a> Sefding remgte ccde...<0x1b>[0m
<break>
<break>
<break>
<0xff><break>
<0xff><break>
<0xff><break>
<break>
<break>
<0x1b>[0;36m[D][climate:396]: 'My AC' <0xad><0xbf>[uowmow<0xbf>{w}wu<0xbb><0xdb>[<0xbf>m<0xed><0xeb><0xdb>[<0xbf><0xbb><0xbb><0xb7>m[d][snmmyw<0xb5><0xa7><0xa6><0xca><0xea><0xe9><  Mode: OFF<0x1b>[0m
<0x1b>[0;36m[D][climate:404]:   Fan Mode: AUTO<0x1b>[0m
<0x1b>[0;36m[D][climate:416]:   Swing Mode: OFF<0x1b>[0m
<0x1b>[0;36m[D][climate:425]:   Target Temperature: 24.00<0xc2><0xb0>C<0x1b>[0m
<0x1b>[0;36m[D][{omm}wu<0xbb><0xbf><0xbd><0xbd>]<0xbb><0xbf><0xb7>omwmog<0xbf>}C<0xb7><0xbf><0xad><0xbf><0xaa><0xd6><0x97>W<0xcb><0xeb>m[<0xbe>[s<0xb9><0xb3>+<0xda><0x9a><0xb2>jm<0x11>um<0x8d><0xb1><0xa5><0xb5><0x85><0xd1><0x95><0xe9>024]:   Fan: AUTO<0x1b>[0m
<0x1b>[0;36m[D][remote_transmitter:075M<0x1a> Sendin<0xb3><0x92><0x95><0xb5><0x9d><0xd1><0x95><0x81>cgde...<0x1b>[0m
<break>
<break>
<break>
<0xfc><break>
<break>
<0xfe><break>
<break>
<0xfe><break>
<0xff><0x1b>[0;36m[D][climate:396]: 'My AC' -<0xb8>[]<0xeb><0xb5><0xbd><0xdd><0xfd>{w}wu<0xbb><0xdb>[?m<0xed><0xf5><0xbb><0xab><0xdb><0xdb><0xbb>km<0xd9>um<0xed><0xb9><0xb5><0xb5><0xf5><0xdd><0x95><0xe9>399]:<p Mode: OFF<0x1b>[0m
<0x1b>[0;36m[D][climate:404]:   Fan Mode: AUTO<0x1b>[0m
<0x1b>[0;36m[DM[climate:416]:   Swing Mode: OFF<0x1b>[0m
<0x1b>[0;36m[D][climate:425]:   Target Temperature: 24.00<0xc2><0xb0>C<0x1b>[0m
<0x1b>[0;36m[D][comm}wu<0xbb><0xbf><0xbd><0xbd>]<0xbb><0xbf><0xb7>omwmow<0xbf>}{<0xb7><0xbf><0xad><0xbf>[ewwi<0xb7><0xd6><0xb6><0xe5>k5<0xca><0x9b>[>;36m[D][climate:037]:   Swing: OFF<0x1b>[0m
<0x1b>[0;36m[D][remote_transmitter:075M: Sefding remgte cgde...<0x1b>[0m
<break>
<0xff><break>
<0xff><break>
<0xfe><break>
<0xff><break>
<break>
<break>
<0xff><break>
<0x1b>[0;36m[D][climate:396]: 'My AC' -<0xbf>[uowmow<0xbf>{w}wu<0xbb><0xdb>[<0xbf>m<0xed><0xeb><0xdb>[<0xbf><0xbb><0xbb><0xb7>m[w][snmm}vu:399]:<00Mode: OFF<0x1b>[0m
<0x1b>[0;36m[D][climate:404]:   Fan Mode: AUTO<0x1b>[0m
<0x1b>[0;36m[DM[climate:416]:   Swing Mode: OFF<0x1b>[0m
<0x1b>[0;36m[D][climate:425]:   Target Temperature: 24.00<0xc2><0xb0>C<0x1b>[0m
<0x1b>[0;36m[D][somm}wu<0xbb><0xbf><0xbd><0xbd>]<0xbb><0xbf><0xb7>omwm<0xb7><0xd7><0xeb><0xed><0x9d><0xbf><0xad><0xbf>[uvwiog<0xdb>[<0xbe>m<0xcd><0xcb><0x9b>[<;36m[D][climate:040]:   Target Temperature: 25.00<0x1b>[0m
<0x1b>[0;36m[D][remoteC42af3mitter:075]<0x9a><0x9a><0x95><0xb9><0x91><0xa5><0xb9><0x9d><0x81>remote code...<0x1b>[0m
<break>
<break>
<break>
<0xff><break>
<0xff><break>
<break>
<0xff><break>
<0xfe><0x1b>[0;36m[D][{omm}<0x7f>u<0xbb><0xbb><0xbd><0xb7>]<0xbb><0xbf><0xb7>omwmow<0xbf>}{<0xb7><0xbf><0xad>?<0xab>Y<0xcb><0xa5><0xbd><0x9d><0xfd>svyve:<0x1b>[<0x9c>[C<0xa1><0xa3>+<0xda><0x9a><0xb2>jm<0x11>um<0x8d><0xb1><0xa5><0xb5><0x85><0xd1><0x95><0xe9>399]:   Mode: OFF<0x1b>[0m
<0x1b>[0;36m[D][climate:404]:   Faf Mcde: AUTG<0x1b>[0m
<0x1b>[0;36m[D][climate:416]:   Swing Mode: OFF<0x1b>[0m
<0x1b>[0;36m[D][climate:425]:   Target Temperaturu<0xbb><0xbf><0xbb><0xb5><0xaf><0xbf><0xbf><0xfb><0xbf>{<0xdb>[<0xbf>m<0xed><0xeb><0xdb>[<0xbf><0xbb><0xbb><0xb7>m[w][snimyve<0xbb><0xbb>=6]:>'<0xa6>ZW<0xcb><0xeb><0x81>Cooling' - Sending state:<0x1b>[0m
<0x1b>[0;36m[D][climate:399]:   Mode: COCL<0x1b>[0m
<0x1b>[0;36m[D][climate:401]:   Action: OFF<0x1b>[0m
<0x1b>[0;36m[D][climate:404]:   Fan Mode: AUTO<0x1b>[0m
<0x1b>[0;36m[D][climawu<0xbb><0xb7><0xbd><0xbb>]<0xbb><0xbf><0xbf><0xdf><0xaf><0xd7><0xdd><0xbd><0xb5><0xfd>_{u{uw<0xbb><0xbf>{wy{wu~<0x9b>[<0xbf>m<0xcd><0xca><0x9b>[>;36m[D][climate:416]:   Swing Mode: OFF<0x1b>[0m
<0x1b>[0;36m[D][climate:419]:   C522ef4 Temperature: nan<0xc2><0xb0>C<0x1b>[0m
<0x1b>[0;36m[D][climate:425]:   Target Temperature: 27.50<0xc2><0xb0>C<0x1b>[0m
<0x1b>[0;32m[I][thermostat.{omm}wu<0xbb><0xbd><0xbf><0xbb><0xb7>]<0xbb><0xbf>{u{wom<0xa0><0x7f>{<0xb5><0xaf><0xd7><0x97><0xdb><0xdd><0xf5><0xc9><0xdd><0xd5><0xfd><0xf9>y~<0x7f>nief<0x9b>[<m
<0x1b>[0;36m[D][climate:011]: 'My AC' - Setting<0x1b>[0m
<0x1b>[0;36m[D][clima4e:015]:   Mgde: GFF<0x1b>[0m
<0x1b>[0;36m[D][remote_transmitter:075]: Sending remote code...<0x1b>[0m
<break>
<0xff><break>
<0xff><break>
<break>
<break>
<0xf8><break>
<break>
<0xff><0xdb>[<0xbe>;36m[D][climate:396]: 'My AC' - Sending state:<0x1b>[0m
<0x1b>[0;36m[D][climate:3<0x19><0x19>M<0x1a>   Mgde: GFF<0x1b>[0m
<0x1b>[0;36m[D][climate:404]:   Fan Mode: AUTO<0x1b>[0m
<0x1b>[0;36m[D][climate:416]:   Swing Mode: OFF<0x1b>[0m<0xcd><0xeb><0xdb>[<0xbf><0xbb><0xbb><0xb7>m[w][{oim}wu<0xbb><0xb7><0xbb><0xb5>]<0xbb><0xbf><0xbf><0x9f>W}{wew<0xbf>Wem~eryture: 25.00<0xc2><0xb0>C<0x1b>[0m
<0x1b>[0;36m[D][climate:396]: 'My Cooling' - Sending sta4e<0x9a><0xa3>+j5
<0x1b>[0;36m[D][climate:399]:   Mode: COOL<0x1b>[0m
<0x1b>[0;36m[D][climate:401]:   Action: OFF<0x1b>[0m
<0x1b>[0;36m[D][climatu<0xbf><0xb7><0xbf><0xb7>]<0xbb>?<0xbf><0xbf>w}o<0xbf>mo<0x7f>u<0xbb><0xbf>}UWo<0xdb>[<0xbf>m<0xed><0xcb><0xdb>[<0xbe>;<0xb3><0xb7>m[<0xb6>W<0xab>.+<0xab>+<0xd1><0x95><0xe9>413]:   Custom Preset: startup<0x1b>[0m
<0x1b>[0;36m[D][climate:416]:   Swinc Mcde: GFF<0x1b>[0m
<0x1b>[0;36m[D][climate:419]:   Current Temperature: nan<0xc2><0xb0>C<0x1b>[0m
<0x1b>[0;36m[D][climate:425]:   Target Tempu{}wu{u<0xbb><0xbf><0xbb><0xb7><0xaf>m<0xdb><0xbf>{<0xdb>[<0xbf>m<0xed><0xeb><0xdb>[<0xbf><0xbb>;5m[<0xbb>W<0xab>W<0xcb><0xa5><0xe9>>6>]:<0x9e><0xaa><0x16><0x17>W<0xcb><0xeb><0x81>up WiFi...<0x1b>[0m
<0x1b>[0;35m[C][wifi:061]: Starting WiFi...<0x1b>[0m
<0x1b>[0<0x1b>35m[C<0xad><0xab>W<0xcb><0xa5><0xe9>062]:   Lgcal MAC: 80:7D:3A:72:BF:3E<0x1b>[0m
<0x1b>[0;36m[D][wifi:482]: Starting scan...<0x1b>[0m<0xed><0xeb><0x9b>[>;<0xb3><0xb7>[+V<0xb5>5<0x95><0xb9><0xcd><0xbd><0xc9><0xe9>093]: 'Uptime': Sending state 1.10800 s with 0 decimals of accuracy<0x1b>[0m
<0x1b>[0;33m[W][cgmpgnent:157]: Component wifi set Warning flag: scanning for networks<0x1b>[0m
<0x1b>[0;36m[D][climate:396]<0xbb><0xbf><0xb7>omwmow<0xbf>}{<0xb7><0xbf><0xad><0xbf>[uowmow<0xbf>{t<0xbd>W<0xd6><0xda>[<0xbe>m<0xcd><0xcb><0xdb>[>;36m[F][climate:399]:   Mode: OFF<0x1b>[0m
```

### Additional information

I had a hard time to extract the boot logs (don’t know why some parts seem scrambled).
Forum discussion : https://community.home-assistant.io/t/esphome-thermostat-ir-off-signal-delay-on-boot/843011
