### ISSUE TITLE
SGP30 sensor chip should be read every second, independent of the update_interval setting

### ISSUE THREAD

**Issue by FvanEgmond** [esphome/issues#6848]
### The problem

According to the hardware specs, the SGP30 sensor only provides correct values if this is polled every second. 
in ESPHome, this functions well when the update_interval setting is set to 1 second. 
But this drowns Home Assistant (recorder) with values, so I do like the option to set the interval to higher settings, e.g. 60 seconds. 
But then the code should function to still poll the chip every second, but only _report_ the value every 60 seconds. 
Can the code be altered to do so?   
Thanks in advance!

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.1

### What platform are you using?

ESP32

### Board

esp32-wroom-32u

### Component causing the issue

sgp30

### YAML Config

```yaml
- platform: sgp30
    eco2:
      name: "Study CO2"
      accuracy_decimals: 1
    tvoc:
      name: "Study TVOC"
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt

```
