### ISSUE TITLE
Updating to 2025.2 "kills" Shelly if Bluetooth is enabled

### ISSUE THREAD

**Issue by lbschenkel** [esphome/issues#6853]
### The problem

I have a number of relays from Shelly that I have tried updating from 2024.12 to 2025.2.
Every single one of them, after updating, do not boot properly even with a minimal config.
Hopefully they do boot in safe mode, as I can ping them and do a new OTA.

This happens the moment I enable the `esp32_ble_tracker` component. Without it everything works. Even with a minimal config that disables everything else, it always boots in safe mode.

Downgrading to 2024.12 fixes the issue completely.

I do not have serial logs at the moment because they are all inside the wall behind light switches and I was hoping to be able to avoid the work of taking them off. But if that's not reproducible by anyone else and I'm the only one having this issue, I can do that.

### Which version of ESPHome has the issue?

2025.2.x

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32-IDF

### Board

shelly

### Component causing the issue

esp32_ble_tracker

### YAML Config

```yaml
# minimal config reproducing the issue

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

i2c:
  sda: GPIO26
  scl: GPIO25

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
ota:
- platform: esphome
logger:
  logs:
    ble_gateway: INFO
api:

esp32_ble_tracker:
```

### Anything in the logs that might be useful for us?

```txt
(Not right now as they're embedded in the wall and I didn't take them off yet.)
```
