### ISSUE TITLE
web_server v3 with local: true and connected through wifi ap does not serve icons

### ISSUE THREAD

**Issue by nagi121** [esphome/issues#6854]
### The problem

I configured an ESP32 with wifi as access point only. The goal is to see the sensor values in a smartphone browser  without internet access.

The web_server is configured with version: 3 and local: true. 

I expected to see something like this:

![Image](https://github.com/user-attachments/assets/99cfe86d-52d2-4b3e-9540-90276f318e76)

but I see this:

![Image](https://github.com/user-attachments/assets/ec7d83dc-f1b2-49ed-9036-f2d3793d83d7)

The option local: true suggests that the web server works even without internet access. This is true for most parts, but not for the icons.

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.1

### What platform are you using?

ESP32

### Board

az-delivery-devkit-v4

### Component causing the issue

web_server

### YAML Config

```yaml
...
esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino
...
wifi:
  ap:
    ssid: "jbd-bms-AP"
    password: !secret wifi_password

web_server:
  port: 80
  local: true
  version: 3
  sorting_groups:
    - id: sorting_group_B_general
      name: "B Status"
      sorting_weight: 100
    - id: sorting_group_B_cells
      name: "B Zellen"
      sorting_weight: 120
...
api:
  reboot_timeout: 0s
...
binary_sensor:
  - platform: jbd_bms
    jbd_bms_id: bms_b
    online_status:
      name: "B online status"
      web_server:
        sorting_group_id: sorting_group_B_status
        sorting_weight: 10
    charging:
      name: "B charging status"
      web_server:
        sorting_group_id: sorting_group_B_status
        sorting_weight: 25
    discharging:
      name: "B discharging status"
      web_server:
        sorting_group_id: sorting_group_B_status
        sorting_weight: 35
    balancing:
      name: "B balancing"
      web_server:
        sorting_group_id: sorting_group_B_cells
        sorting_weight: 10

switch:
  - platform: jbd_bms
    jbd_bms_id: bms_b
    charging:
      name: "B charging enabled"
      web_server:
        sorting_group_id: sorting_group_B_status
        sorting_weight: 20
    discharging:
      name: "B discharging enabled"
      web_server:
        sorting_group_id: sorting_group_B_status
        sorting_weight: 30
...
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

I understand that the webserver v3 uses "iconify-icon" to allow the browser to load the icons from the web. I suspect this won't work if the client browser doesn't have internet access because it is connected exclusively to the ESP32's access point.
