### ISSUE TITLE
Unable to add ESP32 device. Error 137

### ISSUE THREAD

**Issue by Bluemethyst** [esphome/issues#6856]
### The problem

After writing the inital firmware to my ESP32 from https://web.esphome.io/ i went to adopt it in ESPHome Builder but im getting this error when trying to install anything to it:

```
Killed
*** Error 137
Reading CMake configuration...
-- git rev-parse returned 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'
-- Building ESP-IDF components for target esp32
-- Configuring incomplete, errors occurred!
See also "/data/build/esphome-web-7340fc/.pioenvs/esphome-web-7340fc/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:548 (message):
  /root/.platformio/penv/.espidf-5.1.5/bin/python: Error while finding module
  specification for 'idf_component_manager.prepare_components'
  (ModuleNotFoundError: No module named 'idf_component_manager')

Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:604 (idf_build_process)
  CMakeLists.txt:3 (project)
```

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

 2025.2.5 

### What platform are you using?

ESP32

### YAML Config

```yaml
esphome:
  name: esphome-web-7340fc
  friendly_name: bedroom
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: redacted
  password: redacted

sensor:
  - platform: dht
    pin: 17
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    update_interval: 15s
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

[logs_esphome-web-7340fc_run.txt](https://github.com/user-attachments/files/19176689/logs_esphome-web-7340fc_run.txt)
