### ISSUE TITLE
wk2132 i2c to uart converter

### ISSUE THREAD

**Issue by edouardreg** [esphome/issues#6858]
### The problem

Hello,

I use a DFR0627 (DFROBOT gravity module) wich is based on a WK2132 i2c to uart converter.
The purpose is to add two more uart ports to my esp32 wich is monitoring several water tanks levels.

I already use two JSN-SR04T sensors to two esp32 hardwares uart with succes

But with the wk2132_i2c: component it seems impossible to use the JSN-SR04T sensor on the uarts created by the converter.
As soon as I indicate as "uart_id: " for the JSN-04T one of the wk2132's uarts id there is a "required key missin" error in the yaml editor.

I think it's perhaps because the JSN-SR04T needs to define rx and tx pins and don't know how manage the virtual ports ?

How can we resolve this ?

Thanks by advance

### Which version of ESPHome has the issue?

latest

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.1

### What platform are you using?

ESP32

### Board

esp32 devkitc v4

### Component causing the issue

platform: "jsn_sr04t"

### YAML Config

```yaml
esphome:
  name: test
  friendly_name: Test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "J9bC3TCR3KZNKFB3SLVvVcv1bgdmExI0Jced7eVKCpk="

ota:
  - platform: esphome
    password: "4707758c3950dc1c3f0f046956c725b8"

 
wifi:
  ap: {}

captive_portal:

i2c:
  sda: GPIO26
  scl: GPIO27
  scan: true
  id: bus_i2c_b
  frequency: 800kHz

wk2132_i2c:
  - address: 0x70
    id: wk2132_bridge_i2c
    uart:
      - id: i2c_uart_0
        channel: 0
        baud_rate: 9600

      - id: i2c_uart_1
        channel: 1
        baud_rate: 9600
     
sensor:
# JSN-SR04M2 
  - platform: "jsn_sr04t"
    name: "Distance_SR04M_cuves"
    uart_id: i2c_uart_0
    update_interval: 3s
    state_class: measurement
    unit_of_measurement: "m"
```

### Anything in the logs that might be useful for us?

```txt
message "required key not provided." at line 46 (uart:) into the esphome's yaml editor
```

**Comment by edouardreg** [comment]
After that, if using esp-idf  

`esp32:
  board: esp32dev
  framework:
    type: esp-dif`

It's not working. With arduino framework, it's OK : you get the JSN-SR04T value, but also an error 
`[E][weikai:406]: Receive frame error FSR=00101000` with each distance value received...

**Comment by timdaman** [comment]
I have another data point here. I am seeing exactly the same behavior.

My configuration is very large (I have most of the houses sensors on one micro controller) so I will post extracts and add the full YAML content to the end.

Here is my wk2132 configuration
```
  - address: 0x70
    i2c_id: i2c_uart_expander_bus
    id: wk2132_bridge_i2c_2
    uart:
      - id: rainbarrel_level_uart
        channel: 0
        baud_rate: 9600
```

When I added that it passed validation. However when I try to use it with a02yyuw

```
sensor:
  - platform: a02yyuw
    uart_id: rainbarrel_level_uart
    name: rainbarrel airgap
    unit_of_measurement: "cm"
    accuracy_decimals: 00
    filters:
      - multiply: 0.1 # Convert MM to CM
      - throttle: 60s
```

The uart key on `wk2132_bridge_i2c_2` raises a problem `required key not provided.`

<img width="328" alt="Image" src="https://github.com/user-attachments/assets/698770ed-ee46-42d3-b287-2a7571df899e" />

When I remove the `uart_id` from "rainbarrel airgap" the error clears on `wk2132_bridge_i2c_2`

<img width="328" alt="Image" src="https://github.com/user-attachments/assets/b3ce72e2-ed01-4df5-8c27-2badc167259b" />


**Full YAML below**
```
substitutions:
  devicename: basement-1
  name: basement-1

esphome:
  name: ${devicename}
  on_boot:
    priority: 800
    then:
      - if:
          condition:
            binary_sensor.is_on: humidifier_open_sensor
          then:
            - button.press: humidifer_close_drain_button

packages:
  wesp32:  !include packages/wesp32.yaml
  # bluetooth:  !include packages/esp32_bluetooth_proxy.yaml
  mmwave: !include packages/ld2410.yaml

uart:
  - tx_pin: GPIO33
    rx_pin: GPIO34
    baud_rate: 256000
    id: diningroom_mmwave_uart


dfrobot_sen0395:
  - id: bathroom_mmwave
    uart_id: bathroom_mmwave_uart



i2c:
  - sda: 4
    scl: 15
    scan: true
    id: i2c_gpio_expander_bus
  - sda: GPIO14
    scl: GPIO05
    scan: true
    # frequency: 400kHz
    id: i2c_uart_expander_bus

wk2132_i2c:
  - address: 0x50
    i2c_id: i2c_uart_expander_bus
    id: wk2132_bridge_i2c_1
    uart:
      - id: kitchen_airsensor_uart
        channel: 0
        baud_rate: 9600
        parity: EVEN
      - id: bathroom_mmwave_uart
        channel: 1
        baud_rate: 115200
  - address: 0x70
    i2c_id: i2c_uart_expander_bus
    id: wk2132_bridge_i2c_2
    uart:
      - id: rainbarrel_level_uart
        channel: 0
        baud_rate: 9600

mcp23017:
  - id: 'gpio_expander_1'
    address: 0x20
    i2c_id: i2c_gpio_expander_bus

sensor:
  - platform: a02yyuw
    uart_id: rainbarrel_level_uart
    name: rainbarrel airgap
    unit_of_measurement: "cm"
    accuracy_decimals: 00
    filters:
      - multiply: 0.1 # Convert MM to CM
      - throttle: 60s
  - platform: xgzp68xx
    i2c_id: i2c_gpio_expander_bus
    id: xgzp6897
    # temperature:
    #     name: "Temperature"
    pressure:
        name: "Furnace Differential Pressure"
        filters:
            - offset: -26
            # - sliding_window_moving_average:
            #     window_size: 10
            #     send_every: 5
    update_interval: 60s
  - platform: gcja5
    uart_id: kitchen_airsensor_uart
    pm_1_0:
      name: "Kitchen Particulate Matter <1.0µm Concentration"
      filters:
        - throttle_average: 30s
    pm_2_5:
      name: "Kitchen Particulate Matter <2.5µm Concentration"
      id: kitchen_pm_2_5
      filters:
        - throttle_average: 30s
    pm_10_0:
      name: "Kitchen Particulate Matter <10.0µm Concentration"
      filters:
        - throttle_average: 30s
    pmc_0_3:
      name: "Kitchen Count of  <0.3µm in .1L"
      filters:
        - throttle_average: 30s
    pmc_0_5:
      name: "Kitchen Count of  <0.5µm in .1L"
      filters:
        - throttle_average: 15s
  - platform: template
    name: "Kitchen PM 2.5 AQI"
    icon: "mdi:air-filter"
    accuracy_decimals: 0
    state_class: measurement
    device_class: aqi
    id: kitchen_pm_2_5_aqi
 # This next block of code converts the PM2.5 measurement into an AQI
  # Based on the US EPA algorithm
  - platform: copy
    source_id: kitchen_pm_2_5
    id: kitchen_pm_2_5_avg
    internal: true
    accuracy_decimals: 0
    filters:
    - sliding_window_moving_average:
        window_size: 5
        send_every: 5
    on_value:
      lambda: |-
        // https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
        if (id(kitchen_pm_2_5_avg).state < 12.0) {
          // good
          id(kitchen_aqi_text).publish_state("Good");
          id(kitchen_pm_2_5_aqi).publish_state((50.0 - 0.0) / (12.0 - 0.0) * (id(kitchen_pm_2_5_avg).state - 0.0) + 0.0);
        } else if (id(kitchen_pm_2_5_avg).state < 35.4) {
          // moderate
          id(kitchen_aqi_text).publish_state("Moderate");
          id(kitchen_pm_2_5_aqi).publish_state((100.0 - 51.0) / (35.4 - 12.1) * (id(kitchen_pm_2_5_avg).state - 12.1) + 51.0);
        } else if (id(kitchen_pm_2_5_avg).state < 55.4) {
          // Unhealthy for Sensitive Groups
          id(kitchen_aqi_text).publish_state("Unhealthy for Sensitive Groups");
          id(kitchen_pm_2_5_aqi).publish_state((150.0 - 101.0) / (55.4 - 35.5) * (id(kitchen_pm_2_5_avg).state - 35.5) + 101.0);
        } else if (id(kitchen_pm_2_5_avg).state < 150.4) {
          // unhealthy
          id(kitchen_aqi_text).publish_state("Unhealthy");
          id(kitchen_pm_2_5_aqi).publish_state((200.0 - 151.0) / (150.4 - 55.5) * (id(kitchen_pm_2_5_avg).state - 55.5) + 151.0);
        } else if (id(kitchen_pm_2_5_avg).state < 250.4) {
          // very unhealthy
          id(kitchen_aqi_text).publish_state("Very Unhealthy");
          id(kitchen_pm_2_5_aqi).publish_state((300.0 - 201.0) / (250.4 - 150.5) * (id(kitchen_pm_2_5_avg).state - 150.5) + 201.0);
        } else if (id(kitchen_pm_2_5_avg).state < 350.4) {
          // hazardous
          id(kitchen_aqi_text).publish_state("Hazardous");
          id(kitchen_pm_2_5_aqi).publish_state((400.0 - 301.0) / (350.4 - 250.5) * (id(kitchen_pm_2_5_avg).state - 250.5) + 301.0);
        } else if (id(kitchen_pm_2_5_avg).state < 500.4) {
          // hazardous 2
          id(kitchen_aqi_text).publish_state("Hazardous");
          id(kitchen_pm_2_5_aqi).publish_state((500.0 - 401.0) / (500.4 - 350.5) * (id(kitchen_pm_2_5_avg).state - 350.5) + 401.0);
        }       
  - platform: sen5x
    i2c_id: i2c_uart_expander_bus
    id: sen54
    pm_1_0:
      name: "NOC PM <1µm Weight concentration"
      id: noc_pm_1_0
      accuracy_decimals: 1
    pm_2_5:
      name: "NOC PM <2.5µm Weight concentration"
      id: noc_pm_2_5
      accuracy_decimals: 1
    pm_4_0:
      name: "NOC PM <4µm Weight concentration"
      id: noc_pm_4_0
      accuracy_decimals: 1
    pm_10_0:
      name: "NOC PM <10µm Weight concentration"
      id: noc_pm_10_0
      accuracy_decimals: 1
    temperature:
      name: "NOC Temperature"
      accuracy_decimals: 1
    humidity:
      name: "NOC Humidity"
      accuracy_decimals: 0
    voc:
      name: "NOC VOC"
      algorithm_tuning:
        index_offset: 100
        learning_time_offset_hours: 12
        learning_time_gain_hours: 12
        gating_max_duration_minutes: 180
        std_initial: 50
        gain_factor: 230
    temperature_compensation:
      offset: 0
      normalized_offset_slope: 0
      time_constant: 0
    acceleration_mode: low
    store_baseline: true
    address: 0x69
    update_interval: 60s
  - platform: template
    name: "NOC PM 2.5 AQI"
    icon: "mdi:air-filter"
    accuracy_decimals: 0
    state_class: measurement
    device_class: aqi
    id: noc_pm_2_5_aqi
  - platform: copy
    source_id: noc_pm_2_5
    id: noc_pm_2_5_avg
    internal: true
    accuracy_decimals: 0
    filters:
    - sliding_window_moving_average:
        window_size: 5
        send_every: 5
    on_value:
      lambda: |-
        // https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
        if (id(noc_pm_2_5_avg).state < 12.0) {
          // good
          id(noc_aqi_text).publish_state("Good");
          id(noc_pm_2_5_aqi).publish_state((50.0 - 0.0) / (12.0 - 0.0) * (id(noc_pm_2_5_avg).state - 0.0) + 0.0);
        } else if (id(noc_pm_2_5_avg).state < 35.4) {
          // moderate
          id(noc_aqi_text).publish_state("Moderate");
          id(noc_pm_2_5_aqi).publish_state((100.0 - 51.0) / (35.4 - 12.1) * (id(noc_pm_2_5_avg).state - 12.1) + 51.0);
        } else if (id(noc_pm_2_5_avg).state < 55.4) {
          // Unhealthy for Sensitive Groups
          id(noc_aqi_text).publish_state("Unhealthy for Sensitive Groups");
          id(noc_pm_2_5_aqi).publish_state((150.0 - 101.0) / (55.4 - 35.5) * (id(noc_pm_2_5_avg).state - 35.5) + 101.0);
        } else if (id(noc_pm_2_5_avg).state < 150.4) {
          // unhealthy
          id(noc_aqi_text).publish_state("Unhealthy");
          id(noc_pm_2_5_aqi).publish_state((200.0 - 151.0) / (150.4 - 55.5) * (id(noc_pm_2_5_avg).state - 55.5) + 151.0);
        } else if (id(noc_pm_2_5_avg).state < 250.4) {
          // very unhealthy
          id(noc_aqi_text).publish_state("Very Unhealthy");
          id(noc_pm_2_5_aqi).publish_state((300.0 - 201.0) / (250.4 - 150.5) * (id(noc_pm_2_5_avg).state - 150.5) + 201.0);
        } else if (id(noc_pm_2_5_avg).state < 350.4) {
          // hazardous
          id(noc_aqi_text).publish_state("Hazardous");
          id(noc_pm_2_5_aqi).publish_state((400.0 - 301.0) / (350.4 - 250.5) * (id(noc_pm_2_5_avg).state - 250.5) + 301.0);
        } else if (id(noc_pm_2_5_avg).state < 500.4) {
          // hazardous 2
          id(noc_aqi_text).publish_state("Hazardous");
          id(noc_pm_2_5_aqi).publish_state((500.0 - 401.0) / (500.4 - 350.5) * (id(noc_pm_2_5_avg).state - 350.5) + 401.0);
        }

ld2410:
  - id: diningroom_mmwave
    uart_id: diningroom_mmwave_uart

binary_sensor:
  - platform: gpio
    name: rain barrel flow
    device_class: running
    pin:
      mcp23xxx: gpio_expander_1
      number: 5
      mode: 
        input: true
        pullup: true
    filters:
      - invert:
      - delayed_on: 1s
  - platform: gpio
    name: basement bathroom pir
    device_class: motion
    pin:
      mcp23xxx: gpio_expander_1
      number: 6
      mode: 
        input: true
    filters: 
      - delayed_off: 10s 
  - platform: gpio
    name: kitchenr pir
    device_class: motion
    pin:
      mcp23xxx: gpio_expander_1
      number: 7
      mode:
        input: true
    filters:
      - delayed_off: 2s
  - platform: gpio
    name: basement bathroom shower
    device_class: running
    pin:
      mcp23xxx: gpio_expander_1
      number: 8
      mode:
        input: true
    filters:
      - delayed_on: .1s
  - platform: gpio
    name: gear room door
    device_class: door
    pin:
      mcp23xxx: gpio_expander_1
      number: 9
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: .1s
  - platform: gpio
    name: basement bathroom mmwave
    device_class: occupancy
    pin:
      mcp23xxx: gpio_expander_1
      number: 10
      mode:
        input: true
  - platform: ld2410
    ld2410_id: diningroom_mmwave
    has_target:
      name: Diningroom Presence
    has_moving_target:
      name: Diningroom Moving
    has_still_target:
      name: Diningroom Still
    out_pin_presence_status:
      name: Diningroom out pin presence status
  - platform: gpio
    name: entry area
    device_class: motion
    pin:
      number: 32
      mode:
        input: true
    filters:
      - delayed_off: 3s
  - platform: gpio
    name: noc door
    device_class: door
    pin:
      mcp23xxx: gpio_expander_1
      number: 15
      mode:
        input: true
        pullup: true
    filters: 
      - delayed_off: 1s 
  - platform: gpio
    name: basement pir
    device_class: motion
    pin:
      mcp23xxx: gpio_expander_1
      number: 11
      mode:
        input: true
  - platform: gpio
    name: noc pir
    device_class: occupancy
    pin:
      mcp23xxx: gpio_expander_1
      number: 12
      mode:
        input: true
    filters: 
      - delayed_off: 1s 
  - platform: gpio
    pin:
      mcp23xxx: gpio_expander_1
      number: 13
      mode:
        input: true
        pullup: true
    name: Humidifier Open Sensor
    id: humidifier_open_sensor
    on_release:
      then:
        - switch.turn_off: close_humidifer_relay
    on_press:
      - delay: 4min
      - if:
          condition:
            binary_sensor.is_on: humidifier_open_sensor
          then:
            - homeassistant.service:
                service: notify.notify
                data:
                  message: "Humidifer autoflush stuck open and is wasting water"
  
  - platform: gpio
    pin:
      mcp23xxx: gpio_expander_1
      number: 14
      mode:
        input: true
        pullup: true
    name: Humidifer Closed Sensor
    id: humidifier_close_sensor
    on_release:
      then:
        - switch.turn_off: open_humidifer_relay
  - platform: gpio
    name: "Diningroom GPIO Presence"
    pin: GPIO35
  - platform: gpio
    name: "Kitchen GPIO Presence"
    pin: GPIO36

switch:
  - platform: dfrobot_sen0395
    dfrobot_sen0395_id: bathroom_mmwave
    type: start_after_boot
    name: load bathroom mmwave config
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - dfrobot_sen0395.settings:
          id: bathroom_mmwave
          detection_segments:
            # Define between one and four segments
            - [0cm, 3m]
          output_latency:
            delay_after_detect: 0s
            delay_after_disappear: 10s
          sensitivity: 2


  - platform: ld2410
    ld2410_id: diningroom_mmwave
    bluetooth:
      name: "Diningroom mmwave bluetooth"
  - platform: gpio
    # internal: true
    pin:
      number: GPIO02
      drive_strength: 40mA
      mode:
        output: true
    name: "Open Humidifier Drain"
    id: open_humidifer_relay
    interlock: [close_humidifer_relay]
    restore_mode: ALWAYS_OFF

  - platform: gpio
    # internal: true
    pin:
      number: GPIO12
      drive_strength: 40mA
      mode:
        output: true
    name: "Close Humidifier Drain"
    id: close_humidifer_relay
    interlock: [open_humidifer_relay]
    interlock_wait_time: 1s
    restore_mode: ALWAYS_ON

button:
  - platform: template
    name: "Humidifer: Open Drain Valve"
    id: humidifer_open_drain_button
    on_press:
      - switch.turn_on: open_humidifer_relay
  - platform: template
    name: "Humidifer: Close Drain Valve"
    id: humidifer_close_drain_button
    on_press:
      - switch.turn_on: close_humidifer_relay

number:
  - platform: ld2410
    ld2410_id: diningroom_mmwave
    timeout:
      name: Diningroom timeout
    max_move_distance_gate:
      name: Diningroom max move distance gate
    max_still_distance_gate:
      name: Diningroom max still distance gate

text_sensor:
  - platform: template
    name: "Kitchen AQI Description"
    icon: "mdi:air-filter"
    id: kitchen_aqi_text
  - platform: template
    name: "NOC AQI Description"
    icon: "mdi:air-filter"
    id: noc_aqi_text

interval:
  - interval: 48h
    then:
      - button.press: humidifer_open_drain_button
      - delay: 100s
      - button.press: humidifer_close_drain_button
```
