### ISSUE TITLE
ESP8266: unable to connect to 802.11n only AP

### ISSUE THREAD

**Issue by 532910** [esphome/issues#6859]
### The problem

steps to reproduce:
1. flash the yaml below, api and ota parts could be removed
2. configure `option require_mode n` for `wifi-device` in openwrt:

```
config wifi-device radio2
        option type mac80211
        option path platform/10180000.wmac
        option band 2g
        option require_mode n
        option htmode HT20
        option channel 1

config wifi-iface iot
        option ifname iot
        option device radio2
        option network lan
        option mode ap
        option ssid iot
        option key KEY
        option encryption psk2+aes
```

The result is "Station does not support mandatory HT PHY - reject association" on openwrt side.

### Which version of ESPHome has the issue?

 2025.2.2

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Component causing the issue

wifi

### YAML Config

```yaml
esphome:
  name: test

esp8266:
  board: esp01_1m
  early_pin_init: false
  restore_from_flash: false

wifi:
  use_address: 10.8.18.11
  power_save_mode: NONE
  fast_connect: false
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mdns:
  disabled: true

ota:
  platform: esphome
  password: !secret ota_password

api:
  encryption:
    key: !secret api_key
```

### Anything in the logs that might be useful for us?

```txt
daemon.info hostapd: iot: STA 40:f5:20:22:ca:7e IEEE 802.11: authenticated
daemon.info hostapd: iot: STA 40:f5:20:22:ca:7e IEEE 802.11: Station does not support mandatory HT PHY - reject association
```
