### ISSUE TITLE
Fans - preset_modes forced to alphanumeric sort

### ISSUE THREAD

**Issue by Cossid** [esphome/issues#6861]
### The problem

All fans that implement the `preset_modes` option are forced into an alphanumeric sort based on (apparently) how c++ std::set stores them.  I have verified that that is not an issue with Python code generation, HA, or the API communcation (works fine with Tasmota/MQTT and keeps ordering), but rather the fact it is a list/set in ESPHome.  A dictionary would probably resolve the issue, but would be a breaking change.

I tried multiset as a test, and that seems to still have sort issues as well.

This would be a breaking change for two reasons:
* preset_mode can be saved, and it is currently identified by find/index, so loading saves after the change could have unexpected consequences
* Switching to dictionary would be a configuration breaking change, requiring keys be added.

This is a pretty minor issue, and I wouldn't expect it to be prioritized very high.

### Which version of ESPHome has the issue?

All (including 2025.2.2-dev)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

BK72XX

### Board

N/A

### Component causing the issue

fan, speed_fan, template_fan, etc...

### YAML Config

```yaml
fan:
  - platform: speed
    output: my_output_1
    name: "Living Room Fan"
    preset_modes:
      - "Turtle"
      - "Low"
      - "Medium"
      - "High"

# or

fan:
  - platform: speed
    output: my_output_1
    name: "Living Room Fan"
    preset_modes:
      - "High"
      - "Medium"
      - "Low"
      - "Turtle"
```

### Anything in the logs that might be useful for us?

```txt
[15:09:13][C][speed.fan:###]:   Supported presets:
[15:09:13][C][speed.fan:###]:     - High
[15:09:13][C][speed.fan:###]:     - Low
[15:09:13][C][speed.fan:###]:     - Medium
[15:09:13][C][speed.fan:###]:     - Turtle

set presets always come out alphanumeric sorted because of the backing set, and are then conveyed that way to HA.
```

### Additional information

Platform isn't relevant, just the data backing `preset_modes` in fan_traits.h and inherited classes.
