### ISSUE TITLE
Web server doesn't support IPv6 on esp32

### ISSUE THREAD

**Issue by stikonas** [esphome/issues#6862]
### The problem

I've enabled IPv6 on my esp32 board yet web server only listens on port 80 over IPv4

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

Shelly 1pm gen3

### Component causing the issue

web_server

### YAML Config

```yaml
esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: arduino
    version: recommended

network:
  enable_ipv6: true
```

### Anything in the logs that might be useful for us?

```txt

```
