### ISSUE TITLE
SEN5x reports incorrect values for SEN55 PMx

### ISSUE THREAD

**Issue by radeklat** [esphome/issues#6864]
### The problem

I recently bought 3 SEN55 sensors and all of them report completely wrong PMx values. In a room with air circulation behing a PM filter, all 3 report the PMx values in thousands. Not only would that be more of a visible smoke, it should actually be even outside of the range of the sensor (Datasheet states 1000 is the upper range). Nearby Awair Element air quality sensor reports < 10 PMx concentration.

Thank you for all your help.

CC @martgras and @anbreww

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

firebeetle32

### Component causing the issue

sen5x

### YAML Config

```yaml
sensor:
  - platform: sen5x
    id: sen55
    pm_1_0:
      name: "SEN55 PM1"
      id: sen55_pm1
      accuracy_decimals: 0
    pm_2_5:
      name: "SEN55 PM2.5"
      id: sen55_pm2_5
      accuracy_decimals: 0
    pm_4_0:
      name: "SEN55 PM4"
      id: sen55_pm4
      accuracy_decimals: 0
    pm_10_0:
      name: "SEN55 PM10"
      id: sen55_pm10
      accuracy_decimals: 0
    temperature:
      name: "SEN55 Temperature"
      id: sen55_temperature
      accuracy_decimals: 1
    humidity:
      name: "SEN55 Humidity"
      id: sen55_humidity
      accuracy_decimals: 1
    voc:
      name: "SEN55 VOC"
      id: sen55_voc
      accuracy_decimals: 1
    nox:
      name: "SEN55 NOx"
      id: sen55_nox
      accuracy_decimals: 1
    store_baseline: true
    update_interval: 30s
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

A graph of the reported values without any conversion:

![Image](https://github.com/user-attachments/assets/439b077b-5b85-4c2a-b629-f8016fb5682e)

I noticed a few things:
- There a static offset between PM1 and the other PM values.
- The other PM values are always identical.
- The sensor doesn't react to smoke at all (I tried to blow a match in it's direction - no change).
- The VOC sensor does react to VOCs (such as open nail polish remover), so I don't think it's a connection issue.

I find it suspicious that all 3 sensors would be broken the same way. One of them was purchased months apart, so they are likely not even the same batch. What else can I do to diagnose the issue? From my limited knowledge of C code and comparing it to the Datasheet, I can't spot anything wrong.

**Comment by mweinelt** [comment]
The PM values are just cumulative, that is why they are so close to another. I agree that, ideally, we would get buckets for the different sizes that do not overlap. For that you need to subtract the value of the next smaller PM size from each PM value.

<img width="1576" height="372" alt="Image" src="https://github.com/user-attachments/assets/a1b41327-bbd6-40b2-8651-383ee0646d1a" />

https://sensirion.com/media/documents/6791EFA0/62A1F68F/Sensirion_Datasheet_Environmental_Node_SEN5x.pdf

**Comment by radeklat** [comment]
Thank you for clarifying that the PM values are the cumulative. I updated the configuration:

```yaml
sensor:
  - platform: sen5x
    id: sen55
    pm_1_0:
      name: "SEN55 PM1"
      id: sen55_pm1
      accuracy_decimals: 0
    pm_2_5:
      name: "SEN55 PM2.5"
      id: sen55_pm2_5
      accuracy_decimals: 0
      filters:
        - lambda: return x - id(sen55_pm1).raw_state;
    pm_4_0:
      name: "SEN55 PM4"
      id: sen55_pm4
      accuracy_decimals: 0
      filters:
        - lambda: return x - id(sen55_pm2_5).raw_state;
    pm_10_0:
      name: "SEN55 PM10"
      id: sen55_pm10
      accuracy_decimals: 0
      filters:
        - lambda: return x - id(sen55_pm4).raw_state;
```

However, the values are still nonsensical:
- The PM 1.0 and PM 2.5 don't seem to react to environment. Only accumulate into what looks like a logarithm plot.
- The values for PM 2.5 suggest a wildfire, not a air in closed office.
- The value for PM 1 is way outside of the sensor resolution (0-1000)

When I blow smoke from a match at the sensor, it only temporarily elevated PM 4 and 10, which is possible. However, smoke should be mainly PM1 and 2.5. Those were not elevated at all. Perhaps because they are already out of range for some reason? This test was also in a small, closed room. So elevated PM1/2.5 from the smoke should be measured for some time.

See the updated graphs with measurement over ~12 days:

Logarithmic scale
<img width="2594" height="1283" alt="Image" src="https://github.com/user-attachments/assets/0ec0a4ef-177d-4a1e-9136-acd2b3865635" />

Linear scale
<img width="2594" height="1280" alt="Image" src="https://github.com/user-attachments/assets/63af8adc-e8c6-4209-a68e-a28f90e96bee" />

Smoke from blown match:
<img width="2778" height="1370" alt="Image" src="https://github.com/user-attachments/assets/6cb12a2b-60e7-42be-a39a-739c4638023a" />
