### ISSUE TITLE
Problem with A01NYUB Waterproof Ultrasonic Sensor¶

### ISSUE THREAD

**Issue by TheAbonimater** [esphome/issues#6865]
### The problem

Hi,

I have an issue with A01NYUB Sensor. 
The version I have needs a trigger on it RX pin (0xff) 
Looks like it doesn't work with the buildin A01NYUB Sensor of ESPHome. Previously I used a custom component in YAML to have it working but this is no longer supported.

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.5

### What platform are you using?

ESP8266

### Board

esp_wroom_02

### Component causing the issue

A01NYUB

### YAML Config

```yaml
esphome:
  name: test-level

esp8266:
  board: esp_wroom_02

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rain-Water-Level"
    password: "NNlawcFfWrgM"

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "0NDZMhYiWl6ZpJKdqByg7YHfFRgO25EfilBz0gzbaJY="

ota:
  - platform: esphome
    password: "9bb27045506c6189cc9363d3edb5519b"

uart:
  id: uart_bus
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 9600

#deep_sleep:
 # run_duration: 60s
 # sleep_duration: 2h


sensor:
  - platform: "a01nyub"
    name: "Distance"
    unit_of_measurement: "cm"
    uart_id: uart_bus

  - platform: uptime
    name: "Uptime Sensor"

#OLD Version
#sensor:
  #- platform: costume
   # lambda: |-
   #   auto height_sensor = new A01NYUB_Sensor(500, id(uart_bus));
   #   App.register_component(height_sensor);
   #   return {height_sensor};
   # sensors:
   #   name: "Rainwater Level"
    #  unit_of_measurement: "cm"
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

OLD .h file for the custom component

```
#include "esphome.h"

class A01NYUB_Sensor : public PollingComponent, public UARTDevice, public Sensor {
  public:

    A01NYUB_Sensor(uint32_t update_interval, UARTComponent *parent) : PollingComponent(update_interval), UARTDevice(parent) {}

    void update() override {

      byte frame[5];
      int pos = 0;
      float value = 0.0;

      //write(0x00); // Try this
     // write(0x55); // Try this
      //write(0x01); // Try this
	  write(0xFF);
      while (available()) {

        frame[pos] = read();

        pos++;

        if (pos == 4) {

	  if ((frame[0] == 0xFF) && (((frame[0] + frame[1] + frame[2]) & 0x00ff) == frame[3])){
            value = ((frame[1] << 8) + frame[2]) / 10.0;
            publish_state(value);
          }
          break;


        }
      }
    }
};

```
