### ISSUE TITLE
Only one RMT channel light works after updating to newest release

### ISSUE THREAD

**Issue by Firemogle** [esphome/issues#6867]
### The problem

Using the esp32_rmt_led_strip config previously worked with two separate light strings, one on board and one external, after flashing to the newest version tonight only the onboard works.

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32-IDF

### Board

WROOM ESP32 N8R8

### Component causing the issue

esp32_rmt_led_strip

### YAML Config

```yaml
substitutions:
  devicename: kitchen_cabinet_eth_va

packages:
  base_board: !include 
    file: packages/poe_board_base_2.6.yaml
    vars:
      devicename: ${devicename}
  voice_board: !include 
    file: packages/va_board_2.0.yaml
    vars:
      devicename: ${devicename}
  sen55: !include 
    file: packages/sen55.yaml
    vars:
      devicename: ${devicename}
  headboard: !include 
    file: packages/add_light.yaml
    vars:
      pin: GPIO48
      length: 200
      color_line: RGB
      name: kitchen_cabinet
  stove: !include 
    file: packages/partition_light.yaml
    vars:
      name: stove
      parent: kitchen_cabinet
      start: 80
      end: 99
  cabinet_top: !include 
    file: packages/partition_light.yaml
    vars:
      name: cabinet_top
      parent: kitchen_cabinet
      start: 0
      end: 39
  cabinet_bottom: !include 
    file: packages/partition_light.yaml
    vars:
      name: cabinet_bottom
      parent: kitchen_cabinet
      start: 40
      end: 79

light:
  - id: !extend kitchen_cabinet
    internal: true 
    
  - id: !extend cabinet_top
    segments:
      - id: kitchen_cabinet
        from: 179
        to: 199
  - id: !extend cabinet_bottom
    segments:
      - id: kitchen_cabinet
        from: 100
        to: 179

sensor:   
  - id: !extend sen55
    i2c_id: i2c_channel
  - platform: bme280_i2c
    temperature:
      name: ${devicename}_ext_temp
      oversampling: 16x
    pressure:
      name: ${devicename}_ext_pressure
    address: 0x76
    i2c_id: i2c_channel
    update_interval: 60s  


add_light.yaml
packages:
  light_effects: !include 
    file: light_effects.yaml
    vars:
      devicename: ${name}

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: ${pin}
    num_leds: ${length}
    rgb_order: ${color_line}
    name: ${name}
    id: ${name}
    effects:
      - addressable_color_wipe:
          name: Chiefs
          colors:
            - red: 89%
              green: 9%
              blue: 21%
              num_leds: 25
              gradient: true
            - red: 89%
              green: 9%
              blue: 21%
              num_leds: 75
              gradient: true
            - red: 100%
              green: 72%
              blue: 9%
              num_leds: 25
              gradient: true
            - red: 100%
              green: 72%
              blue: 9%
              num_leds: 75
              gradient: true
          add_led_interval: 200ms
          reverse: False
      - addressable_color_wipe:
          name: Jayhawks
          colors:
            - red: 91%
              green: 0%
              blue: 5%
              num_leds: 25
              gradient: true
            - red: 91%
              green: 0%
              blue: 5%
              num_leds: 75
              gradient: true
            - red: 0%
              green: 32%
              blue: 73%
              num_leds: 25
              gradient: true
            - red: 0%
              green: 32%
              blue: 73%
              num_leds: 75
              gradient: true
          add_led_interval: 200ms
          reverse: False
      - addressable_color_wipe:
          name: Christmas stripes
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 50
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 50
          add_led_interval: 100ms
          reverse: False
      - addressable_color_wipe:
          name: Independence Day
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 20
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 20
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 20
          add_led_interval: 33ms
          reverse: false
      - addressable_lambda:
          name: Blue Sparkle
          update_interval: 12ms
          lambda:
            static int state = 0;
      
            if (initial_run){
              state = 0;
      
              it.all() = Color(0,0,255);
            } else {
      
              it.all() = Color(0,0,255);
              for (int i = it.size() / 30; i > 0; i--) {
                int p = rand() % it.size();
                it[p] = Color(255,255,255);
              }
            }
      - addressable_lambda:
          name: Gold Glitter
          update_interval: 12ms
          lambda:
            static int state = 0;
      
            if (initial_run){
              state = 0;
      
              it.all() = Color(218,32,32);
      
              ESP_LOGD("custom", "Gold Glitter");
            } else {
      
              it.all() = Color(218,32,32);
      
              if(state==0){
                int i = rand() % it.size();
                it[i] = Color::WHITE;
                state += 1;
              } else {
                state += 1;
                state = state % 10;
              }
            }
      - addressable_lambda:
          name: Rainbow
          lambda: |-

            if (initial_run) {
              it.all() = Color(0, 0, 0);
            }
            
            uint8_t led_change = 24; //(higher is more change) the difference in hue for each led down the strip
            float speed = 4; //(lower is faster) the speed the first led colour changes at (therefore affecting all)
            unsigned long time = millis() / speed;
            int repetitions = time / 1529;
            uint16_t hue = time - (1529 * repetitions);
            
            for (int i = 0; i < it.size(); i++) {
              if (hue >= 0 && hue < 255) {
                uint8_t green = hue;
                it[i] = Color(255, green, 0);
              } else if (hue >= 255 && hue < 510) {
                uint8_t red = hue - 255;
                it[i] = Color((255 - red), 255, 0);
              } else if (hue >= 510 && hue < 765) {
                uint8_t blue = hue - 510;
                it[i] = Color(0, 255, blue);
              } else if (hue >= 765 && hue < 1020) {
                uint8_t green = hue - 765;
                it[i] = Color(0, (255 - green), 255);
              } else if (hue >= 1020 && hue < 1275) {
                uint8_t red = hue - 1020;
                it[i] = Color(red, 0, 255);
              } else if (hue >= 1275 && hue < 1530) {
                uint8_t blue = hue - 1275;
                it[i] = Color(255, 0, (255 - blue));
              }
              hue+=led_change;
              if (hue >= 1530) {
                hue-=1530;
              }
            }

voice_light.yaml
packages:
  light_effects: !include 
    file: light_effects.yaml
    vars:
      devicename: ${name}

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: ${pin}
    num_leds: ${length}
    rgb_order: ${color_line}
    name: ${name}
    id: ${name}
    effects:
      - addressable_color_wipe:
          name: voice_listen
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 9
              gradient: true
          add_led_interval: 100ms
          reverse: False
      - addressable_color_wipe:
          name: voice_thinking
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 3
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 3
              gradient: true
          add_led_interval: 50ms
          reverse: False
      - addressable_color_wipe:
          name: voice_replying
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 3
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 9%
              blue: 90%
              num_leds: 3
              gradient: true
          add_led_interval: 50ms
          reverse: true
      - addressable_color_wipe:
          name: timer_tick
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 90%
              blue: 9%
              num_leds: 3
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 90%
              blue: 9%
              num_leds: 3
              gradient: true
          add_led_interval: 50ms
          reverse: true
      - addressable_color_wipe:
          name: timer_ring
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 90%
              blue: 9%
              num_leds: 3
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
              gradient: true
            - red: 0%
              green: 90%
              blue: 9%
              num_leds: 3
              gradient: true
          add_led_interval: 50ms
          reverse: false

va_board2.0.yaml
packages:
  string_light: !include 
    file: voice_light.yaml
    vars:
      pin: GPIO07
      length: 12
      color_line: GRB
      name: ${devicename}_status
  va_adf: !include 
    file: audio.yaml
    vars:
      devicename: ${devicename}
  voice: !include 
    file: voice.yaml
    vars:
      devicename: ${devicename}

light:
  - id: !extend ${devicename}_status
    internal: true 
    rmt_symbols: 48

sensor:
  - platform: bme280_i2c
    temperature:
      name: ${devicename}_Temperature
      oversampling: 16x
    pressure:
      name: ${devicename}_Pressure
    humidity:
      name: ${devicename}_Humidity
    address: 0x77
    update_interval: 60s
    i2c_id: i2c_channel 
  - platform: veml7700
    address: 0x10
    update_interval: 60s
    ambient_light: ${devicename}_Ambient_Light
    full_spectrum: ${devicename}_Full_Spectrum
    infrared: ${devicename}_Infrared
    ambient_light_counts: ${devicename}_AMB_LIGHT_COUNT
    full_spectrum_counts: ${devicename}_FS_COUNT
    i2c_id: i2c_channel
```

### Anything in the logs that might be useful for us?

```txt
Logs show the light is on and no change to lights
```

### Additional information

I have tried to play with the rmt_symbols: config and initially it worked, but the latest flash I have tried it has done nothing.
