### ISSUE TITLE
MDI colour image no longer displaying

### ISSUE THREAD

**Issue by dtswk** [esphome/issues#6870]
### The problem

I had some code that was working prior to the most recent esphome home upgrade & device update.

The screen is working, I am seeing the bars, text etc.  However the mdi images are not displaying.

It was displaying a mdi image in colour (color) after the esphome upgrade I was prompted to also update the device.  After which I got an error saying type needed to be added to the image.  I have tried type of RGB, RGB565 and no image is displayed and no errors.   However if I set it to Binary the image does show up in monochome.

No image displayed
  - file: "mdi:party-popper"
    id: party_icon
    resize: 60x60

Image displayed (type = binary)
  - file: "mdi:emoticon-neutral-outline"
    id: neutral_icon
    resize: 60x60
    type: binary

Happy to do testing or provide more information etc

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.3

### What platform are you using?

ESP8266

### Board

Lilygo H569 T-Display-S3

### YAML Config

```yaml
substitutions:
  name: esphome-web-c1310c
  friendly_name: Matt Desktop Display

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 80000000L
    board_build.partitions: default_16MB.csv
    board_build.arduino.memory_type: qio_opi
  project:
    name: esphome.web
    version: dev

external_components:
  - source: github://landonr/lilygo-tdisplays3-esphome
    components: [tdisplays3]

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  flash_size: 16MB

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32s3.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: "Button 1 - Open Blind"
    on_press:
      then:
        - homeassistant.service:
            service: cover.open_cover
            data:
              entity_id: cover.matt_office_blind

  - platform: gpio
    pin:
      number: GPIO14
      inverted: true
    name: "Button 2 - Close Blind"
    on_press:
      then:
        - homeassistant.service:
            service: cover.close_cover
            data:
              entity_id: cover.matt_office_blind

output:
  - platform: ledc
    pin: GPIO38
    id: gpio38
    frequency: 2000

light:
  - platform: monochromatic
    output: gpio38
    name: "Backlight"
    restore_mode: RESTORE_DEFAULT_ON

# You can either setup the backlight as a switch like below or make it dimmable using a light output like above
# switch:
#   - platform: gpio
#     pin: GPIO38
#     name: "Backlight"
#     id: backlight
#     internal: true
#     restore_mode: RESTORE_DEFAULT_ON

display:
  - platform: tdisplays3
    id: disp
    update_interval: 1s
    rotation: 270
    lambda: |-
      // Display Current Time at the Top
      if (id(ha_time).now().is_valid()) {
        it.strftime(10, 10, id(roboto), "%H:%M %d-%b-%Y", id(ha_time).now());
      }

      // Display Battery Level Gauge
      auto battery_level = id(battery_sensor).state;
      if (!isnan(battery_level)) {
        it.printf(10, 40, id(roboto), "Battery: %.1f%%", battery_level);
        it.filled_rectangle(10, 60, int(battery_level * 0.8), 10, Color(0, 255, 0)); // Green horizontal bar
      }

      // Display Solar Production Gauge in kW
      auto solar_production = id(solar_sensor).state / 1000.0;
      if (!isnan(solar_production)) {
        it.printf(10, 80, id(roboto), "Solar: %.2f kW", solar_production);
        it.filled_rectangle(10, 100, int(solar_production * 20), 10, Color(255, 255, 0)); // Yellow horizontal bar
      }

      // Display AC Load Gauge in kW
      auto ac_load = id(ac_load_sensor).state / 1000.0;
      if (!isnan(ac_load)) {
        it.printf(10, 120, id(roboto), "AC Load: %.2f kW", ac_load);
        it.filled_rectangle(10, 140, int(ac_load * 20), 10, Color(255, 0, 0)); // Red horizontal bar
      }
      // Determine Sunset Time
      auto now = id(ha_time).now();
      bool before_sunset = now.hour < 18; // Replace '18' with actual sunset hour if available

      // Choose forecast based on time
      float forecast = before_sunset ? id(forecast_today).state : id(forecast_tomorrow).state;

      // Display Forecast Icon on the Right Side
      if (!isnan(forecast)) {
        if (forecast < 25) {
          it.image(it.get_width()-20, 85, id(sad_icon), ImageAlign::CENTER_RIGHT);
        } else if (forecast < 50) {
          it.image(it.get_width()-20, 85, id(neutral_icon), ImageAlign::CENTER_RIGHT);
        } else if (forecast < 80) {
          it.image(it.get_width()-20, 85, id(happy_icon), ImageAlign::CENTER_RIGHT);
        } else {
          it.image(it.get_width()-20, 85, id(party_icon), ImageAlign::CENTER_RIGHT);
        }
      }


#it.image(it.get_width(), 0, id(my_image), ImageAlign::TOP_RIGHT);

# Used for example above

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 16
  # - file: "fonts/OpenSans-Bold.ttf"
  #   id: font
  #   size: 16    

time:
  - platform: homeassistant
    id: ha_time

sensor:
  - platform: homeassistant
    entity_id: sensor.battery_percent
    id: battery_sensor
    name: "Battery Percentage"

  - platform: homeassistant
    entity_id: sensor.net_solar_production
    id: solar_sensor
    name: "Solar Production"

  - platform: homeassistant
    entity_id: sensor.ac_loads
    id: ac_load_sensor
    name: "AC Loads"

  - platform: homeassistant
    entity_id: sensor.solcast_pv_forecast_forecast_today
    id: forecast_today
    internal: true

  - platform: homeassistant
    entity_id: sensor.solcast_pv_forecast_peak_forecast_tomorrow
    id: forecast_tomorrow
    internal: true

image:
  - file: "mdi:emoticon-sad-outline"
    id: sad_icon
    resize: 60x60
    type: binary

  - file: "mdi:emoticon-neutral-outline"
    id: neutral_icon
    resize: 60x60
    type: binary

  - file: "mdi:emoticon-happy-outline"
    id: happy_icon
    resize: 60x60
    type: binary

  - file: "mdi:party-popper"
    id: party_icon
    resize: 60x60
    type: binary
```

### Anything in the logs that might be useful for us?

```txt

```
