### ISSUE TITLE
Multiple neopixel busses fail silently ESP32-S2

### ISSUE THREAD

**Issue by asolochek** [esphome/issues#6871]
### The problem

The ESP32-S2 has only one i2s bus, and the neopixelbus uses the i2s bus method by default. This results in multiple neopixels connected to different GPIOs to only be controllable together. 

If multiple neopixelbusses are instantiated on ESP32-S2 (or more than 2 on ESP32) the additional busses should default to use the bit_bang method. 

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/a

### What platform are you using?

ESP32

### Board

adafruit feather esp32-s2 tft

### Component causing the issue

neopixelbus

### YAML Config

```yaml
substitutions:
  room: General
  project_name: ESPHome.Project
  project_version: 1.0.0
  log_level: INFO
  flash_write_interval: 5min
  i2c_frequency: 100kHz
  i2c_sda_pin: GPIO42
  i2c_scl_pin: GPIO41
  neopixel_power_pin: GPIO34
  neopixel_power_id: neopixel_power
  board_type: adafruit_feather_esp32s2_tft
  i2c_power_pin: GPIO21
  spi_mosi_pin: GPIO35
  spi_miso_pin: GPIO37
  spi_sck_pin: GPIO36
  neopixel_pin: GPIO33
  name: hdc302x-test
  friendly_name: HDC302x Test
  hostname: test-rev-tft
  device_description: ESP Test Device

esphome:
  name: neopix-test
  friendly_name: Neopix Test
  comment: ESP Test Device
  area: General
  project:
    name: ESPHome.Project
    version: 1.0.0
  platformio_options:
    board_build.flash_mode: dio
  min_version: 2025.2.2
  build_path: build/neopix-test
  includes: []
  libraries: []
  name_add_mac_suffix: false
esp32:
  board: adafruit_feather_esp32s2_tft
  framework:
    version: 2.0.5
    advanced:
      ignore_efuse_custom_mac: false
    source: ~3.20005.0
    platform_version: platformio/espressif32@5.4.0
    type: arduino
  flash_size: 4MB
  variant: ESP32S2
preferences:
  flash_write_interval: 5min
external_components:
- source:
    path: components
    type: local
  refresh: 1d
  components: all
logger:
  id: base_logger
  level: INFO
  hardware_uart: UART0
  logs:
    component: ERROR
    i2c.arduino: INFO
    api.service: INFO
    api.connection: INFO
    esp32.preferences: INFO
    sensor.filter: INFO
    scheduler: INFO
    sensor: INFO
    light.addressable: INFO
    text.sensor: INFO
  baud_rate: 115200
  tx_buffer_size: 512
  deassert_rts_dtr: false
api:
  port: 6053
  password: 
  reboot_timeout: 15min
ota:
- platform: esphome
  id: my_ota
  password: 
  version: 2
  port: 3232
button:
- platform: restart
  id: restart_button
  name: Restart
  entity_category: config
  disabled_by_default: false
  icon: mdi:restart
  device_class: restart
mdns:
  disabled: false
  services: []
binary_sensor:
- platform: status
  name: Status
  entity_category: diagnostic
  disabled_by_default: false
  device_class: connectivity
sensor:
- platform: uptime
  name: Uptime Sensor
  id: uptime_sensor
  internal: true
  disabled_by_default: false
  force_update: false
  unit_of_measurement: s
  icon: mdi:timer-outline
  accuracy_decimals: 0
  device_class: duration
  state_class: total_increasing
  entity_category: diagnostic
  update_interval: 60s
  type: seconds
- platform: wifi_signal
  name: WiFi Signal
  id: wifi_signal_db
  update_interval: 60s
  entity_category: diagnostic
  disabled_by_default: false
  force_update: false
  unit_of_measurement: dBm
  accuracy_decimals: 0
  device_class: signal_strength
  state_class: measurement
- platform: copy
  source_id: wifi_signal_db
  name: WiFi Signal Percent
  filters:
  - lambda: !lambda |-
      return min(max(2 * (x + 100.0), 0.0), 100.0);
  unit_of_measurement: '%'
  entity_category: diagnostic
  device_class: ''
  disabled_by_default: false
  force_update: false
  accuracy_decimals: 0
  state_class: measurement
text_sensor:
- platform: template
  name: Last Restart
  id: device_last_restart
  icon: mdi:clock
  entity_category: diagnostic
  disabled_by_default: false
  update_interval: 60s
- platform: template
  name: Uptime
  icon: mdi:clock-start
  entity_category: diagnostic
  lambda: !lambda |-
    int seconds = (id(uptime_sensor).state);
    int days = seconds / (24 * 3600);
    seconds = seconds % (24 * 3600);
    int hours = seconds / 3600;
    seconds = seconds % 3600;
    int minutes = seconds /  60;
    seconds = seconds % 60;
    if ( days > 3650 ) {
      return { "Starting up" };
    } else if ( days ) {
      return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
    } else if ( hours ) {
      return { (String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
    } else if ( minutes ) {
      return { (String(minutes) +"m "+ String(seconds) +"s").c_str() };
    } else {
      return { (String(seconds) +"s").c_str() };
    }
  disabled_by_default: false
  update_interval: 60s
- platform: wifi_info
  ip_address:
    name: IP Address
    entity_category: diagnostic
    disabled_by_default: false
    update_interval: 1s
  ssid:
    name: Connected SSID
    entity_category: diagnostic
    disabled_by_default: false
    update_interval: 1s
  mac_address:
    name: Mac Address
    entity_category: diagnostic
    disabled_by_default: false
time:
- platform: homeassistant
  id: ha_time
  timezone: PST8PDT,M3.2.0,M11.1.0
  update_interval: 60min
  on_time_sync:
  - then:
    - if:
        condition:
          lambda: !lambda |-
            return id(device_last_restart).state == "";
        then:
        - text_sensor.template.publish:
            id: device_last_restart
            state: !lambda |-
              return id(ha_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");
i2c:
- id: bus_a
  sda: 42
  scl: 41
  frequency: 100000.0
  scan: false
  setup_priority: 700.0
wifi:
  id: wifi_id
  domain: 
  fast_connect: true
  manual_ip:
    static_ip: 
    gateway: 
    subnet: 255.255.0.0
    dns1: 0.0.0.0
    dns2: 0.0.0.0
  reboot_timeout: 15min
  power_save_mode: LIGHT
  passive_scan: false
  enable_on_boot: true
  networks:
  - ssid: 
    password: 
    priority: 0.0
  use_address: 10.3.1.112
light:
- platform: neopixelbus
  id: neopixel_led
  method:
    bus: 0
    type: esp32_i2s
  type: GRB
  variant: ws2812
  pin: 33
  num_leds: 1
  name: NeoPixel
  restore_mode: RESTORE_DEFAULT_OFF
  effects:
  - strobe:
      name: blink red
      colors:
      - state: true
        red: 1.0
        green: 0.0
        blue: 0.0
        brightness: 1.0
        duration: 250ms
        color_brightness: 1.0
        white: 1.0
        cold_white: 1.0
        warm_white: 1.0
        transition_length: 0s
      - state: true
        red: 0.0
        green: 0.0
        blue: 0.0
        brightness: 0.0
        duration: 250ms
        color_brightness: 1.0
        white: 1.0
        cold_white: 1.0
        warm_white: 1.0
        transition_length: 0s
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
  invert: false
- platform: neopixelbus
  id: neopixel_ext
  method:
    type: bit_bang
  type: GRB
  variant: ws2812
  pin: 10
  num_leds: 1
  name: NeoPixel Ext
  restore_mode: RESTORE_DEFAULT_OFF
  effects:
  - strobe:
      name: blink red
      colors:
      - state: true
        red: 1.0
        green: 0.0
        blue: 0.0
        brightness: 1.0
        duration: 250ms
        color_brightness: 1.0
        white: 1.0
        cold_white: 1.0
        warm_white: 1.0
        transition_length: 0s
      - state: true
        red: 0.0
        green: 0.0
        blue: 0.0
        brightness: 0.0
        duration: 250ms
        color_brightness: 1.0
        white: 1.0
        cold_white: 1.0
        warm_white: 1.0
        transition_length: 0s
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
  invert: false
- platform: neopixelbus
  id: neopixel_ext2
  method:
    type: bit_bang
  type: GRB
  variant: ws2812
  pin: 12
  num_leds: 1
  name: NeoPixel Ext2
  restore_mode: RESTORE_DEFAULT_OFF
  effects:
  - strobe:
      name: blink red
      colors:
      - state: true
        red: 1.0
        green: 0.0
        blue: 0.0
        brightness: 1.0
        duration: 250ms
        color_brightness: 1.0
        white: 1.0
        cold_white: 1.0
        warm_white: 1.0
        transition_length: 0s
      - state: true
        red: 0.0
        green: 0.0
        blue: 0.0
        brightness: 0.0
        duration: 250ms
        color_brightness: 1.0
        white: 1.0
        cold_white: 1.0
        warm_white: 1.0
        transition_length: 0s
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
  invert: false
switch:
- platform: gpio
  id: neopixel_power
  restore_mode: ALWAYS_ON
  pin:
    number: 34
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
    ignore_pin_validation_error: false
    ignore_strapping_warning: false
    drive_strength: 20.0
  disabled_by_default: false
  interlock_wait_time: 0ms
  name: neopixel_power
  internal: true
- platform: gpio
  id: i2c_power
  restore_mode: ALWAYS_ON
  pin:
    number: 21
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
    ignore_pin_validation_error: false
    ignore_strapping_warning: false
    drive_strength: 20.0
  disabled_by_default: false
  interlock_wait_time: 0ms
  name: i2c_power
  internal: true
spi:
- clk_pin:
    number: 36
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
    ignore_pin_validation_error: false
    ignore_strapping_warning: false
    drive_strength: 20.0
  mosi_pin:
    number: 35
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
    ignore_pin_validation_error: false
    ignore_strapping_warning: false
    drive_strength: 20.0
  miso_pin:
    number: 37
    mode:
      input: true
      output: false
      open_drain: false
      pullup: false
      pulldown: false
    inverted: false
    ignore_pin_validation_error: false
    ignore_strapping_warning: false
    drive_strength: 20.0
  interface: any
  type: single
  interface_index: 0
status_led:
  pin:
    number: 13
    inverted: false
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
    ignore_pin_validation_error: false
    ignore_strapping_warning: false
    drive_strength: 20.0
```

### Anything in the logs that might be useful for us?

```txt

```
