### ISSUE TITLE
builds_flags syntax changed with latest esphome

### ISSUE THREAD

**Issue by yanivf38** [esphome/issues#6874]
### The problem

prior to 2025.2.2 everything worked as expected were my build flags looked like this -
```
esphome:
  platformio_options:
    build_flags:
      - DARDUINO_USB_MODE=1
      - DARDUINO_USB_CDC_ON_BOOT=1
  ```
but with the latest build, I need to add an extra dash to the build flags and make it look like this
```
esphome:
  platformio_options:
    build_flags:
      - -DARDUINO_USB_MODE=1
      - -DARDUINO_USB_CDC_ON_BOOT=1
```

### Which version of ESPHome has the issue?

esphome 2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.3

### What platform are you using?

ESP32

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```
