### ISSUE TITLE
C_INCLUDE_PATH env of the host interferes with the cross compiler

### ISSUE THREAD

**Issue by attila-lendvai** [esphome/issues#6875]
### The problem

i'm on Guix that configures quite a few things through env variables.

to successfully compile my first esphome project i had to do this:

```
unset C_INCLUDE_PATH
unset CPLUS_INCLUDE_PATH
```

in full context for reference:

```
guix shell --container --emulate-fhs --user=hacker --no-cwd --network --share=/home/alendvai/workspace/homeaut/esphome-venv=/home/hacker/ python python-pip nss-certs bash coreutils glibc file grep gcc-toolchain less which git -- bash --init-file <(echo "source bin/activate; export TERM=$TERM; unset C_INCLUDE_PATH; unset CPLUS_INCLUDE_PATH; export PATH=~/.local/bin:\$PATH")
```

otherwise i get the error:

`Failed to determine sizeof(time_t)`

### Which version of ESPHome has the issue?

Version: 2025.2.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

esp32-c6-devkitc-1

### YAML Config

```yaml
esphome:
  name: street-keypad

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "x"

ota:
  - platform: esphome
    password: "x"

wifi:
  ssid: "x"
  password: "x"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Street-Keypad Fallback Hotspot"
    password: "x"

captive_portal:

sensor:
  - platform: uptime
    name: Uptime Sensor

button:
  - platform: restart
    name: "Keypad Restart"
  - platform: safe_mode
    name: "Keypad (Safe Mode)"  

wiegand:
  - id: keypad1
    d0: GPIO10
    d1: GPIO11
    on_key:
      - lambda: ESP_LOGI("KEY", "received key %d", x);
    on_tag:
      - lambda: ESP_LOGI("TAG", "received tag %s", x.c_str());
      - homeassistant.tag_scanned: !lambda 'return x.c_str();'
    on_raw:
      - lambda: ESP_LOGI("RAW", "received raw %d bits, value %llx", bits, value);
```

### Anything in the logs that might be useful for us?

```txt

```
