### ISSUE TITLE
RC Switch not sending correct codes in ESPHome

### ISSUE THREAD

**Issue by Algtronic** [esphome/issues#6877]
### The problem

I have latest ESPHome in Hassio with D1 mini board. With the following code I have no response on receiver.
However, with the same controller, same 433 code I have response on transmitter when flashing using ArduinoIDE.

RCSwitch mySwitch = RCSwitch();

void setup() {

  Serial.begin(9600);
  
  mySwitch.enableTransmit(D2);

}

void loop() {
  mySwitch.send("00000001000000000111101100010110");//00000001000000000111101100010110
  delay(1000);
}

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.2.5

### What platform are you using?

ESP8266

### Board

D1 mini

### Component causing the issue

remote_transmitter

### YAML Config

```yaml
remote_transmitter:
  pin: D2
  carrier_duty_percent: 100%

button:
  - platform: template
    name: "Template Button"
    on_press:
    - remote_transmitter.transmit_rc_switch_raw:
        code: '00000001000000000111101100010110'
        protocol: 1
```

### Anything in the logs that might be useful for us?

```txt

```
