### ISSUE TITLE
After latest update  2025.3.0 my hub75 display dont display text anymore or not always

### ISSUE THREAD

**Issue by jl-p** [esphome/issues#6881]
### The problem

After i upgraded my wordclock and status screen wont show any text anymore. sometimes some lines work . some lines i couldnt reproduce, i added logging and that showed the text should had been there.
i downgraded my esphome to the 2025.2.2 and everything works again. 

### Which version of ESPHome has the issue?

2025.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

latest official

### What platform are you using?

ESP32

### Board

devkitv1

### Component causing the issue

hub75 

### YAML Config

```yaml
esphome:
  name: wordclock
  friendly_name: WordClock

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
# Enable Home Assistant API

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails





substitutions:
  DelayTimePage2: 10s
  xscrollpadding: "4" # in pix 








captive_portal:

external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main



 
 

globals:
- id: page
  type: int
  initial_value: "1"
- id: WhichCounter
  type: int
  initial_value: "0"

text_sensor:
  - platform: homeassistant
    name: "WC_Datum"
    entity_id: sensor.wordclock_Datum
    id: WC_Datum
  - platform: homeassistant
    name: "WC_Week"
    entity_id: sensor.wordclock_Week
    id: WC_Week
  - platform: homeassistant
    name: "WC_Weeknr"
    entity_id: sensor.wordclock_weeknr
    id: WC_Weeknr    
  - platform: homeassistant
    name: "WC_LINE_1"
    entity_id: sensor.wordclock_regel1
    id: WC_LINE_1
  - platform: homeassistant
    name: "WC_LINE_2"
    entity_id: sensor.wordclock_regel2
    id: WC_LINE_2
  - platform: homeassistant
    name: "WC_LINE_3"
    entity_id: sensor.wordclock_regel3
    id: WC_LINE_3
  - platform: homeassistant
    name: "WC_LINE_4"
    entity_id: sensor.wordclock_regel4
    id: WC_LINE_4
  - platform: homeassistant
    name: "SS_LINE_1"
    entity_id: input_text.SS_LINE_1
    id: SS_LINE_1
  - platform: homeassistant
    name: "SS_LINE_2"
    entity_id: input_text.SS_LINE_2
    id: SS_LINE_2
  - platform: homeassistant
    name: "SS_LINE_3"
    entity_id: input_text.SS_LINE_3
    id: SS_LINE_3
  - platform: homeassistant
    name: "SS_LINE_4"
    entity_id: input_text.SS_LINE_4
    id: SS_LINE_4
  - platform: homeassistant
    name: "SS_LINE_5"
    entity_id: input_text.SS_LINE_5
    id: SS_LINE_5
  - platform: homeassistant
    name: "SS_LINE_6"
    entity_id: input_text.SS_LINE_6
    id: SS_LINE_6
  - platform: homeassistant
    name: "WordclockTotal"
    entity_id: sensor.WordclockTotal
    id: WordclockTotal
  - platform: homeassistant
    name: "Matrix Text"
    entity_id: input_text.WordclockTotal
    id: led_matrix_text
    on_value:
      - if:
          condition:
            text_sensor.state:
              id: led_matrix_text
              state: ""
          else:
            - script.execute: start
  - platform: homeassistant
    name: "status_johan"
    entity_id: input_text.Status_johan
    id: status_johan

  - platform: homeassistant
    name: "Wordclock_printer_state"
    entity_id: sensor.wordclock_printer_state
    id: Wordclock_printer_state
  - platform: homeassistant
    name: "Wordclock_printer"
    entity_id: sensor.wordclock_printer
    id: Wordclock_printer
  - platform: homeassistant
    name: "Wordclock_printer_status"
    entity_id: sensor.wordclock_printer_status
    id: Wordclock_printer_status
    on_value:
      - if:
          condition:
            text_sensor.state:
              id: Wordclock_printer_status
              state: "Finish"
          then:
            - script.execute: start
  - platform: homeassistant
    name: "Printer Error"
    entity_id: binary_sensor.x1c_00m00a280101426_print_error
    id: pp_printer_Error



sensor:






binary_sensor:

  - platform: homeassistant
    name: "Wasmachine Status"
    entity_id: input_boolean.pp_wasmachine
    id: pp_wasmachine_bool
  - platform: homeassistant
    name: "pp_vaatwasser"
    entity_id: input_boolean.pp_vaatwasser
    id: pp_vaatwasser_bool
  - platform: homeassistant
    name: "pp_droger"
    entity_id: input_boolean.pp_droger
    id: pp_droger_bool
  - platform: homeassistant
    name: "Printer Status"
    entity_id: input_boolean.pp_bambu
    id: pp_printer_bool



color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%

time:
  - platform: homeassistant
    id: esptime
  - platform: sntp
    # ...
    on_time:
      # Every 5 minutes
      - seconds: 0
        minutes: /2
        then:
          - display.page.show: !lambda |-
                if (id(WhichCounter) == 0) {
                return id(page1);
                } else {
                  return id(page2);
                } 

font:
  - file: "fonts/led-counter-7.regular.ttf"
    id: led
    size: 10   
  - file: "fonts/square-dot-digital-7.regular.ttf"
    id: square
    size: 10  
  - file: "fonts/square-dot-digital-7.regular.ttf"
    id: square20
    size: 20  
  - file: "fonts/square-dot-digital-7.regular.ttf"
    id: square40
    size: 40  



animation:
- file: "wasmachine30.gif"
  id: my_wasmachine
  resize: 13x15
  type: RGB
- file: "dryer30.gif"
  id: my_dryer
  resize: 13x15
  type: RGB
- file: "dish30.gif"
  id: my_dish
  resize: 15x15
  type: RGB
- file: "3dprint15.gif"
  id: my_3dprinter
  resize: 15x15
  type: RGB


display:
  - platform: hub75_matrix_display
    id: matrix
    width: 192
    height: 32
    update_interval: 50ms    
    latch_blanking: 5
    clock_phase: false
    pages:
      - id: page1
        lambda: |-      

          if (strcmp(id(Wordclock_printer_status).state.c_str(), "pause") != 0 && strcmp(id(pp_printer_Error).state.c_str(), "on") != 0) {
            //it.printf(0, 0, id(square), id(my_red), "%s %s", id(WC_Datum).state.c_str(),id(WC_Week).state.c_str());
            if(id(SS_LINE_3).state.length()>2) {
              it.strftime(it.get_width()/2, 4, id(square), id(my_blue.fade_to_white(125)),TextAlign::CENTER, "%A %d %B", id(esptime).now());

              if (strcmp(id(SS_LINE_3).state.c_str(), "Koffie Water bijvullen") == 0){
                it.strftime(it.get_width()/2, 15, id(square20),id(my_white), TextAlign::CENTER, "%H:%M:%S", id(esptime).now()); 
                it.printf(it.get_width()/2, 26, id(square),id(my_red),TextAlign::CENTER,"%s",id(SS_LINE_3).state.c_str());  
              }
              else{
                it.strftime(it.get_width()/2, 19, id(square40),id(my_white), TextAlign::CENTER, "%H:%M:%S", id(esptime).now()); 
                it.printf(it.get_width()/2, 26, id(square),id(my_red),TextAlign::CENTER,"%s",id(SS_LINE_3).state.c_str()); 
              }
            }
            else{
              if(id(WC_LINE_3).state.length()>2) {
                // ESP_LOGD("custom", "Lijn 3 groter dan 2 %s", id(WC_LINE_1).state.c_str());
                // ESP_LOGD("custom", "Lijn 3 groter dan 2 %s", id(WC_LINE_2).state.c_str());
                // ESP_LOGD("custom", "Lijn 3 groter dan 2 %s", id(WC_LINE_3).state.c_str());
                it.printf(it.get_width()/2, 12, id(square),TextAlign::CENTER, "%s",id(WC_LINE_1).state.c_str());
                it.printf(it.get_width()/2, 20, id(square),id(my_blue.fade_to_white(125)),TextAlign::CENTER,"%s",id(WC_LINE_2).state.c_str());
                it.printf(it.get_width()/2, 27, id(square),TextAlign::CENTER, "%s",id(WC_LINE_3).state.c_str());
              }
              else{
                if(id(WC_LINE_2).state.length() >2) {
                  if(id(WC_LINE_1).state.length()>13){
                    // ESP_LOGD("custom", "L2 > 2 L1 >13 %s", id(WC_LINE_1).state.c_str());
                    // ESP_LOGD("custom", "L2 > 2 L1 >13 %s", id(WC_LINE_2).state.c_str());
                    it.printf(it.get_width()/2-10,15 , id(square),TextAlign::CENTER, "%s",id(WC_LINE_1).state.c_str());
                    it.printf(it.get_width()/2-10, 26, id(square),id(my_blue.fade_to_white(125)),TextAlign::CENTER,"%s",id(WC_LINE_2).state.c_str());
                    
                  }
                  else{
                    // ESP_LOGD("custom", "L2 > 2 L1 <14 %s", id(WC_LINE_1).state.c_str());
                    // ESP_LOGD("custom", "L2 > 2 L1 <14 %s", id(WC_LINE_2).state.c_str());
                    it.printf(it.get_width()/2-10,15 , id(square20),TextAlign::CENTER, "%s",id(WC_LINE_1).state.c_str());
                    it.printf(it.get_width()/2-10, 26, id(square20),id(my_blue.fade_to_white(125)),TextAlign::CENTER,"%s",id(WC_LINE_2).state.c_str());
                  }
                }
                else{
                    // ESP_LOGD("custom", "L2 < 3  %s", id(WC_LINE_1).state.c_str());
                    it.printf(it.get_width()/2,22 , id(square20),TextAlign::CENTER, "%s",id(WC_LINE_1).state.c_str());
                }
              }
            }
          }   
          //
          //    WASMACHINE 
          //       
          if(id(pp_wasmachine_bool).state) {
            id(my_wasmachine).next_frame();
            it.image(1, 1, id(my_wasmachine), COLOR_ON, COLOR_OFF);
          }
          if(strcmp(id(SS_LINE_2).state.c_str(), "De Wasmachine is Klaar") == 0) {                
                id(my_wasmachine).set_frame(1);
                it.image(1, 1, id(my_wasmachine), COLOR_ON, COLOR_OFF);

                it.line(1, 1+6, 1+5, 1+13,my_green);
                it.line(1+5, 1+13, 1+11, 1,my_green);
                it.line(1, 1+7, 1+5, 1+14,my_green);
                it.line(1+5, 1+14, 1+12, 1,my_green);
          }      
          //
          //    Droger 
          //


          if(id(pp_droger_bool).state) {
            //// ESP_LOGD("display", "my_dryer  is ON.");
             id(my_dryer).next_frame();
             it.image(1, 17, id(my_dryer), COLOR_ON, COLOR_OFF);
          }

          if(strcmp(id(SS_LINE_4).state.c_str(), "De Droger is Klaar") == 0) {                
                id(my_dryer).set_frame(1);
                it.image(1, 17, id(my_dryer), COLOR_ON, COLOR_OFF);
                it.line(1, 17+6, 1+5, 17+13,my_green);
                it.line(1+5, 17+13, 1+11, 17,my_green);
                it.line(1, 17+7, 1+5, 17+14,my_green);
                it.line(1+5, 17+14, 1+12, 17,my_green);
          }          
          //
          //    Vaatwasser
          //


          if(id(pp_vaatwasser_bool).state) {
            //// ESP_LOGD("display", "vaatwasser  machine is ON.");
             id(my_dish).next_frame();
             it.image(175, 1, id(my_dish), COLOR_ON, COLOR_OFF);
          }
          if(strcmp(id(SS_LINE_1).state.c_str(), "De Vaatwasser is klaar") == 0) {                
                id(my_dish).set_frame(1);
                it.image(175, 1, id(my_dish), COLOR_ON, COLOR_OFF);
                
                it.line(175, 1+6, 175+7, 1+13,my_green);
                it.line(175+7, 1+13, 175+13, 1,my_green);
                it.line(175, 1+7, 175+7, 1+14,my_green);
                it.line(175+7, 1+14, 175+14, 1,my_green);
          }


          //
          //    Printer
          //


            if(strcmp(id(Wordclock_printer_status).state.c_str(), "pause") != 0) {
                      // ESP_LOGD("custom", "%s %s", id(WC_Datum).state.c_str(),id(WC_Week).state.c_str());
                      it.printf(16, 0, id(square), id(my_red), "%s %s", id(WC_Datum).state.c_str(),id(WC_Week).state.c_str());
                      //it.printf(152, 0, id(square), id(my_red), "%s", id(WC_Week).state.c_str());

            }
          if(id(pp_printer_bool).state) {          
            if(strcmp(id(Wordclock_printer_status).state.c_str(), "pause") == 0) {
                if(strcmp(id(pp_printer_Error).state.c_str(), "on") == 0) {
                  //// ESP_LOGD("display", "bambu error.");
                  it.printf(25, -2, id(square), id(my_red), "Bambu Heeft een error");
                  it.strftime(it.get_width()/2, 13, id(square20),id(my_white), TextAlign::CENTER, "%H:%M:%S", id(esptime).now()); 
                  it.printf(it.get_width()/2, 22, id(square),id(my_red),TextAlign::CENTER,"%s",id(SS_LINE_5).state.c_str());  
                  it.printf(it.get_width()/2, 28, id(square),id(my_red),TextAlign::CENTER,"%s",id(SS_LINE_6).state.c_str());  
                  id(my_3dprinter).set_frame(1);
                  it.image(175, 17, id(my_3dprinter), COLOR_ON, COLOR_OFF);
                  it.line(175, 17, 189, 28,my_red);
                  it.line(175, 28, 189, 17,my_red);
                }
                else{
                  it.printf(25, 0, id(square), id(my_red), "Bambu staat op pause");
                  it.strftime(it.get_width()/2, 19, id(square40),id(my_white), TextAlign::CENTER, "%H:%M:%S", id(esptime).now()); 
                  id(my_3dprinter).set_frame(1);
                  it.image(175, 17, id(my_3dprinter), COLOR_ON, COLOR_OFF);
                  it.line(175, 17, 189, 28,my_red);
                  it.line(175, 28, 189, 17,my_red);
                }

            }
            else if(strcmp(id(Wordclock_printer_status).state.c_str(), "finish") == 0) {    

                  id(my_3dprinter).set_frame(1);
                  it.image(175, 17, id(my_3dprinter), COLOR_ON, COLOR_OFF);
                  it.line(175, 24, 182, 28,my_green);
                  it.line(182, 28, 189, 17,my_green);
                  
            }
            else {
                    if (strcmp(id(SS_LINE_1).state.c_str(), "De Vaatwasser is klaar") == 0 || id(pp_vaatwasser_bool).state) {
                      it.printf(150, 23, id(square), id(my_white),"%s", id(Wordclock_printer).state.c_str()); 
                    }
                    else {
                      it.printf(165, 7, id(square), id(my_white),"%s", id(Wordclock_printer).state.c_str());
                    }
                  id(my_3dprinter).next_frame();
                  it.image(175, 17, id(my_3dprinter), COLOR_ON, COLOR_OFF);              
            }
          }







     
      - id: page2
        lambda: |-      




          it.printf(1,1 , id(square20), "%D",id(WhichCounter));
          
          
          



      - id: page3
        lambda: |-      


           it.filled_rectangle(0,0,it.get_width(),8,my_red);
           it.filled_rectangle(0,0,8,63,my_red);
           it.filled_rectangle(184,0,8,63,my_red);
           it.filled_rectangle(0,24,it.get_width(),8,my_red);


            

     


  
    


switch:
  - platform: hub75_matrix_display
    matrix_id: matrix
    name: "Power"
    id: power
    restore_mode: ALWAYS_ON

number:
  - platform: hub75_matrix_display
    matrix_id: matrix
    name: "Brightness"
    id: schermbrightness


 

script:
  - id: start
    mode: restart
    then:
      - logger.log: "Script started."
      - repeat:
          count: 15
          then:
            - delay: 2s
            - number.to_min: schermbrightness
            - logger.log: "Setting brightness to minimum."
            - delay: 500ms
            - number.to_max: schermbrightness
            - logger.log: "Setting brightness to maximum."
      - delay: 60s
      - display.page.show: !lambda |-
            return id(page1);
```

### Anything in the logs that might be useful for us?

```txt
the logs looks normal but no text on my display
```
