### ISSUE TITLE
uptime sensor doesn't get triggered under large values

### ISSUE THREAD

**Issue by yeralin** [esphome/issues#689]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Raspbian GNU/Linux 9 (stretch)
(Raspberry Pi 3B)

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 (NODEMCUV2 by espressif)

**Affected component:**
Uptime sensor

**Description of problem:**
When I set update interval to some large value (ex. `1h`), and let the ESP run 
autonomously, the automation does not get triggered. If I change the interval to a smaller value (ex. `10min`), everything will work as expected. 

Interestingly enough, this issue does not occur when ESP is connected to Hass instance on my raspberry.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: uptime
     id: uptime_sensor
     update_interval: 1h
     on_value:
       then:
         - logger.log: "Test"
```
For my fool configuration, refer to https://github.com/yeralin/IoT/blob/master/applications/smart-feeder/smart-feeder.yml

**Additional information and things you've tried:**
I don't use SNTP or HomeAssistant time bc I want to ensure that ESP will work even in case when internet is down or raspberry pi is turned off.
