### ISSUE TITLE
Component micronova : On/off problem

### ISSUE THREAD

**Issue by cguhring67** [esphome/issues#6895]
### The problem

Hi,
Yesterday, I installed a new ESP to control my Micronova-controlled stove. I'm using the micronova component which worked immediately.

But the Off action is problematic and I have the same problem as mentionned here : https://github.com/eni23/micronova-controller, but even worse :

When switching off, the Final cleaning takes forever (and the fumes motor stay on - after 1:30 hours, it was already running). Impossible to re-turn it On via ESPHome. Via the panel of the stove, a long-press on "on/off" triggers a new "On". But If I power-cycle the stove while in this forever "Final cleaning", it restarts as Working in "modulation" and feeds pellets...
So, I need to apply the solution of eni23 : send 10 times 0x5a to RAM 0x58 with a delay of 100ms.

I have tried to write this in the custom_button: 

```
button:
  - platform: micronova
    custom_button:
      id: poele_on_off
      name: "Marche/arrêt"
      icon: mdi:power
      on_press:
        - repeat:
            count: 10
            then:
              - memory_location: 0x00
              - memory_address: 0x58
              - memory_data: 0x5a      
              - delay: 100ms
```      

but on compile, I receive this error : 

INFO ESPHome 2025.3.1
INFO Reading configuration /config/esphome/wt32-poele.yaml...
Failed config

button.micronova: [source /config/esphome/wt32-poele.yaml:130]
  platform: micronova
  
  'memory_data' is a required option for [custom_button].
  custom_button: 
    id: poele_on_off
    name: Marche/arrêt
    icon: mdi:power
    on_press: 
      - repeat: 
          count: 10
          then: 
            - 
              Unable to find action with the name 'memory_location'.
              memory_location: 0
            - memory_address: 88
            - memory_data: 90
   
I tried also to create a custom_button that writes 0x00 on RAM 0x21 (force off) but nothing happens.

Additionnaly, I would like to be able to add more than one "custom_button", and more than one "memory_address_sensor". If this is possible, can you please tell me how ?

And finally, I would also change the "working text" like on the stove panel : when the room temperature is >= preset temp, the stove itself set its power to minimum and shows "moduele" on the LED display.
I tried this code in the "room temperature sensor" : 

```
      on_value:
        - lambda: |-
            if (id(poele_statut_raw) == 4) {
              if (x >= id(temperature_cible).state) {
                id(poele_statut).publish_state("Modulation");
              }
              else {
                id(poele_statut).publish_state("Travaille");
              } 
            }
```
But obtain on compile " ERROR Circular dependency detected! Please run with -v option to see what functions failed to complete."

### Which version of ESPHome has the issue?

2025.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.4

### What platform are you using?

ESP32

### Board

WT32-ETH

### Component causing the issue

micronova

### YAML Config

```yaml
esphome:
  name: wt32-poele
  friendly_name: wt32-poele

esp32:
  board: wt32-eth01
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "###encryption_key###"

ota:
  - platform: esphome
    password: "###ota_password###"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
    

uart:
  tx_pin: GPIO33
  rx_pin: GPIO32
  baud_rate: 1200
  data_bits: 8
  parity: NONE
  stop_bits: 2

micronova:
  enable_rx_pin: GPIO17
  update_interval: 10s

text_sensor:
  - platform: micronova
    stove_state:
      name: "Statut Poêle"
      id: poele_statut
      filters:
        - substitute:
          - "Off -> Eteint"
          - "Start -> Démarrage"
          - "Pellets loading -> Allumage"
          - "Ignition -> Démarrage"
          - "Working -> Travaille"
          - "Brazier Cleaning -> Nettoyage régulier"
          - "Final Cleaning -> Extinction"
          - "No pellets alarm -> Plus de pellets"
          - "No ignition alarm -> Allumage raté"
          - "Undefined alarm -> Autre alarme"

sensor:
  - platform: micronova
    room_temperature:
      id: temperature_piece
      name: "Température pièce"
      filters:
        - quantile:
            window_size: 7
            send_every: 1
            quantile: .9
        - sliding_window_moving_average:
            window_size: 25
            send_every: 1
#      on_value:
#        - lambda: |-
#            if (id(poele_statut_raw) == 4) {
#              if (x >= id(temperature_cible).state) {
#                id(poele_statut).publish_state("Modulation");
#              }
#              else {
#                id(poele_statut).publish_state("Travaille");
#              } 
#            }
    fumes_temperature:
      id: temperature_fumees
      name: "Température des fumées"
    stove_power:
      id: puissance_actuelle
      name: "Puissance actuelle"
    fan_speed:
      fan_rpm_offset: 240
      name: "Vitesse ventilateur"
    memory_address_sensor:
      memory_location: 0x00
      memory_address: 0x21
      id: poele_statut_raw
      name: "Statut poêle brut"

  - platform: dht
    model: DHT22
    pin: GPIO14
    temperature:
      name: "Temperature Salon"
    humidity:
      name: "Humidité Salon"
    update_interval: 10s     

number:
  - platform: micronova
    thermostat_temperature:
      id: temperature_cible
      name: Temperature cible
      step: 1
    power_level:
      id: puissance_poele
      name: Puissance


switch:
  - platform: micronova
    stove:
      name: Stove on/off switch


#button:
#  - platform: micronova
#    custom_button:
#      id: poele_on_off
#      name: "Marche/arrêt"
#      icon: mdi:power
#      on_press:
#        - repeat:
#            count: 10
#            then:
#              - memory_location: 0x00
#              - memory_address: 0x58
#              - memory_data: 0x5a      
#              - delay: 100ms      
#    custom_button:
#      id: force_off
#      name: "Extinction forcée"
#      memory_location: 0x00
#      memory_address: 0x21
#      memory_data: 0x00
```

### Anything in the logs that might be useful for us?

```txt

```
