### ISSUE TITLE
Pip complaints during install

### ISSUE THREAD

**Issue by Sc00tz** [esphome/issues#6896]
### The problem

I'm trying to compile a yaml config for a muse proto that I want to use as a voice assistant. I am getting this error when I go to install it:

INFO ESPHome 2025.3.1
INFO Reading configuration /config/esphome/muse-voice-assistant.yaml...
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING `attenuation: 11db` is deprecated, use `attenuation: 12db` instead
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING RMT_LED_STRIP support for IDF version < 5 is deprecated and will be removed soon.
INFO Generating C++ source...
INFO Compiling app...
Processing raspiaudio-muse-proto (board: esp-wrover-kit; framework: espidf; platform: platformio/espressif32@5.3.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40408.0 (4.4.8) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Installing ESP-IDF's Python dependencies
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
*** Error 1
Reading CMake configuration...
-- Building ESP-IDF components for target esp32
-- Configuring incomplete, errors occurred!
See also "/data/build/raspiaudio-muse-proto/.pioenvs/raspiaudio-muse-proto/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:463 (message):
  /usr/bin/python3: Error while finding module specification for
  'idf_component_manager.prepare_components' (ModuleNotFoundError: No module
  named 'idf_component_manager')

Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:476 (idf_build_process)
  CMakeLists.txt:3 (project)

========================== [FAILED] Took 2.19 seconds ==========================

### Which version of ESPHome has the issue?

2025.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.03.3

### What platform are you using?

ESP32-IDF

### Board

esp-wrover-kit

### Component causing the issue

pip/venv/addon?

### YAML Config

```yaml
substitutions:
  name: raspiaudio-muse-proto
  friendly_name: RaspiAudio Muse Proto

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.2.0
  name_add_mac_suffix: true

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.3.0

logger:

api:
  encryption:
    key: "[REDACTED]"

ota:
  platform: esphome
  password: "[REDACTED]"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: "[REDACTED]"

captive_portal:

# Battery monitoring
sensor:
  - platform: adc
    pin: GPIO33
    name: "Battery Level"
    update_interval: 60s
    id: battery_level
    attenuation: 11db
    filters:
      - multiply: 2
    unit_of_measurement: "V"
    accuracy_decimals: 2
    entity_category: diagnostic

# SD Card detection - no pullup on GPIO34
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO34
      mode:
        input: true
    name: "SD Card Present"
    id: sd_card_present
    device_class: connectivity
    entity_category: diagnostic
  
  # Action button (IO0)
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: Button
    id: action_button
    on_multi_click:
      - timing:
          - ON for at least 50ms
          - OFF for at least 50ms
        then:
          - if:
              condition:
                switch.is_on: timer_ringing
              then:
                - switch.turn_off: timer_ringing
              else:
                - voice_assistant.start:
      - timing:
          - ON for at least 10s
        then:
          - button.press: factory_reset_btn

# I2S Audio Configuration
i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO5

microphone:
  - platform: i2s_audio
    id: board_microphone
    channel: left
    i2s_din_pin: GPIO35
    adc_type: external
    pdm: false

# Amplifier control (GPIO21)
output:
  - platform: gpio
    pin: GPIO21
    id: amplifier_enable
    inverted: true

# Configure the speaker
speaker:
  - platform: i2s_audio
    id: board_external_speakers
    dac_type: external
    i2s_dout_pin: GPIO26
    channel: mono

# Media player with amplifier control
media_player:
  - platform: speaker
    id: muse_media_player
    name: ${friendly_name} Speaker
    announcement_pipeline:
      speaker: board_external_speakers
      format: WAV
    codec_support_enabled: false
    buffer_size: 6000
    files:
      - id: timer_finished_wave_file
        file: https://github.com/esphome/wake-word-voice-assistants/raw/refs/heads/main/sounds/timer_finished.wav
      - id: wake_word_detected_file
        file: https://www.pacdv.com/sounds/interface_sound_effects/beep-3.wav
    on_announcement:
      - if:
          condition:
            - microphone.is_capturing:
          then:
            - voice_assistant.stop:
            - script.execute: reset_led
      - output.turn_off: amplifier_enable  # Enable amplifier when announcement starts
      - light.turn_on:
          id: board_led
          blue: 100%
          red: 0%
          green: 0%
          brightness: 100%
          effect: none
    on_idle:
      - output.turn_on: amplifier_enable  # Disable amplifier when idle
      - script.execute: start_wake_word_listening

# Standard voice_assistant component
voice_assistant:
  id: va
  microphone: board_microphone
  media_player: muse_media_player
  use_wake_word: true  # Enable wake word detection through Home Assistant
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  on_wake_word_detected:
    - media_player.speaker.play_on_device_media_file:
        media_file: wake_word_detected_file
        announcement: true
  on_listening:
    - output.turn_off: amplifier_enable  # Enable amplifier when listening
    - light.turn_on:
        id: board_led
        blue: 100%
        red: 0%
        green: 0%
        effect: "Slow Pulse"
  on_stt_vad_end:
    - light.turn_on:
        id: board_led
        blue: 100%
        red: 0%
        green: 0%
        effect: "Fast Pulse"
  on_tts_start:
    - light.turn_on:
        id: board_led
        blue: 60%
        red: 20%
        green: 20%
        effect: none
  on_end:
    - delay: 100ms
    - script.execute: start_wake_word_listening
  on_error:
    - light.turn_on:
        id: board_led
        blue: 0%
        red: 100%
        green: 0%
        effect: none
    - delay: 2s
    - script.execute: reset_led
  on_client_connected:
    - delay: 2s
    - script.execute: start_wake_word_listening
  on_client_disconnected:
    - voice_assistant.stop:
  on_timer_finished:
    - voice_assistant.stop:
    - wait_until:
        not:
          microphone.is_capturing:
    - switch.turn_on: timer_ringing
    - light.turn_on:
        id: board_led
        red: 0%
        green: 100%
        blue: 0%
        brightness: 100%
        effect: "Fast Pulse"
    - wait_until:
        - switch.is_off: timer_ringing
    - light.turn_off: board_led
    - switch.turn_off: timer_ringing

light:
  - platform: esp32_rmt_led_strip
    id: board_led
    name: LED
    disabled_by_default: false
    entity_category: config
    pin: GPIO22
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    rmt_channel: 0
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

button:
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
    
  # Add a safe mode button
  - platform: safe_mode
    name: Safe Mode Restart
    
script:
  - id: reset_led
    then:
      - if:
          condition:
            - switch.is_on: use_listen_light
          then:
            - light.turn_on:
                id: board_led
                red: 100%
                green: 89%
                blue: 71%
                brightness: 60%
                effect: none
          else:
            - light.turn_off: board_led
  
  - id: start_wake_word_listening
    then:
      - wait_until:
          and:
            - media_player.is_idle:
            - speaker.is_stopped:
      - voice_assistant.start_continuous:

switch:
  - platform: template
    name: Use listen light
    id: use_listen_light
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - script.execute: reset_led
    on_turn_off:
      - script.execute: reset_led
  - platform: template
    id: timer_ringing
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_off:
      # Turn off the repeat mode and disable the pause between playlist items
      - lambda: |-
              id(muse_media_player)
                ->make_call()
                .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_REPEAT_OFF)
                .set_announcement(true)
                .perform();
              id(muse_media_player)->set_playlist_delay_ms(speaker::AudioPipelineType::ANNOUNCEMENT, 0);
      # Stop playing the alarm
      - media_player.stop:
          announcement: true
    on_turn_on:
      # Turn on the repeat mode and pause for 1000 ms between playlist items/repeats
      - lambda: |-
            id(muse_media_player)
              ->make_call()
              .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_REPEAT_ONE)
              .set_announcement(true)
              .perform();
            id(muse_media_player)->set_playlist_delay_ms(speaker::AudioPipelineType::ANNOUNCEMENT, 1000);
      - media_player.speaker.play_on_device_media_file:
          media_file: timer_finished_wave_file
          announcement: true
      - delay: 15min
      - switch.turn_off: timer_ringing

# Gain control for the MAX98357A codec
select:
  - platform: template
    name: "Amplifier Gain"
    id: amplifier_gain
    optimistic: true
    entity_category: config
    options:
      - "3 dB"
      - "6 dB"
      - "9 dB"
      - "12 dB"
      - "15 dB"
    initial_option: "12 dB"
    on_value:
      - lambda: |-
          if (x == "3 dB") {
            pinMode(23, OUTPUT);
            digitalWrite(23, HIGH);
          } else if (x == "6 dB") {
            pinMode(23, OUTPUT);
            digitalWrite(23, LOW);
          } else if (x == "9 dB") {
            pinMode(23, INPUT);  // Disconnected
          } else if (x == "12 dB") {
            pinMode(23, OUTPUT);
            digitalWrite(23, LOW);
          } else if (x == "15 dB") {
            pinMode(23, OUTPUT_OPEN_DRAIN);
            digitalWrite(23, LOW);  // Connect to GND through 100kΩ
          }
```

### Anything in the logs that might be useful for us?

```txt
I did try this again with the current beta version of the add-on, same results so I went back to the normal release version.
```

**Comment by MallocArray** [comment]
I'm struggling to see what the real error from pip is, but have you considered addressing several of the deprecated messages, such as the attenuation value?

Is there a reason to keep your frameworks pinned to specific versions that the messages say aren't recommended?
```
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.3.0
```

I'm running various devices with just straight esp-idf and letting esphome get the recommended one.  I did have to recently remove the rmt_channel parameter as it wasn't supported with the newest version, but was an easy modification.
