### ISSUE TITLE
waveshare_epaper 2.90inv2-r2 does not work after ESP32C3 deep sleep

### ISSUE THREAD

**Issue by GraffJosh** [esphome/issues#6898]
### The problem

Using the waveshare_epaper 2.90inv2-r2 with a Xaio ESP32C3 works great until I put the device in deep sleep. After wake it no longer updates the display until I power cycle the entire device. 

I tried using https://github.com/esphome/esphome/pull/6209 with this and 4.2" display. The 4.2 will work after deepsleep (though it does go through a full refresh sequence which is less than ideal). This 2.9 won't work at all. 

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3

### What platform are you using?

ESP32

### Board

SEEED Xaio ESP32C3

### Component causing the issue

waveshare_epaper

### YAML Config

```yaml
esphome:
  name: dinghy
  friendly_name: Dinghy
  on_boot:
    - priority: 600
      then:
      - deep_sleep.prevent: very_deep_sleep

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
deep_sleep:
  id: very_deep_sleep
  run_duration: 
    default: 
      minutes: 2
  sleep_duration: 
    hours: 1
  wakeup_pin_mode: KEEP_AWAKE
  wakeup_pin: 
    number: GPIO2
    allow_other_uses: true
    inverted: true

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO2
      allow_other_uses: true
      inverted: True
      mode:
        input: True
        pullup: True
    name: "Button"

    on_double_click: 
      then:
      - globals.set: 
          id: last_click
          value: "2"
      - light.turn_on:
          id: button_light
          brightness: 100%
          red: 100%
          green: 0%
          blue: 0%
      - delay: 2s
      - light.turn_off:
          id: button_light
      - deep_sleep.allow: very_deep_sleep
      - deep_sleep.enter: very_deep_sleep
spi:
  clk_pin: GPIO9
  mosi_pin: GPIO10
display:
  - platform: waveshare_epaper
    id: eink_display
    cs_pin: 
      number: GPIO7
    dc_pin: GPIO5
    reset_pin: GPIO21
    busy_pin: GPIO6
    reset_duration: 2ms
    model: 2.90inv2-r2
    rotation: 90
    update_interval: 10s
    full_update_every: 30
    auto_clear_enabled: True
    pages:
      - id: page1
        lambda: |-
          int x = 10;
          int y = 0;
          it.strftime(x, y, id(robotoSmall), TextAlign::TOP_LEFT, "%H:%M", id(platformtime).now());
```

### Anything in the logs that might be useful for us?

```txt

```
