### ISSUE TITLE
wifi connection issues with v 2025.3.1

### ISSUE THREAD

**Issue by airmonitor** [esphome/issues#6899]
### The problem

Good day,

I upgraded to version 2025.3.1 a few days ago and observed that my ESP32, which was previously running successfully on the balcony, lost its connection to the Wi-Fi network. When I moved it closer to the access point, it connected successfully.

This issue did not occur with the previous version, where the ESP32 was operating smoothly on the balcony and transferring data to Home Assistant as expected.

I am curious if this is an unusual coincidence or if any of you have noticed similar behavior?

I've played with additional wifi parameters but those didn't helped much.

### Which version of ESPHome has the issue?

2025.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.4

### What platform are you using?

ESP32

### YAML Config

```yaml
esphome:
  name: "airmonitor01-balcony"
  friendly_name: "airmonitor01-balcony"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "adsfasfdasdf"

ota:
  - platform: esphome
    password: "asfasdfasdfasdf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  fast_connect: False
  output_power: 20.0dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wifi Fallback Hotspot"
    password: "asdfsadfasdfasdf"

captive_portal:

# Example configuration entry for ESP32
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a
# Example configuration entry
sensor:
  - platform: mics_4514
    i2c_id: bus_a
    nitrogen_dioxide:
      name: Nitrogen Dioxide
    carbon_monoxide:
      name: Carbon Monoxide
    hydrogen:
      name: Hydrogen
    ethanol:
      name: Ethanol
    methane:
      name: Methane
    ammonia:
      name: Ammonia
    update_interval: 60s
  - platform: sen5x
    i2c_id: bus_a
    id: sen55
    pm_1_0:
      name: " PM <1µm Weight concentration"
      id: pm_1_0
      accuracy_decimals: 1
    pm_2_5:
      name: " PM <2.5µm Weight concentration"
      id: pm_2_5
      accuracy_decimals: 1
    pm_4_0:
      name: " PM <4µm Weight concentration"
      id: pm_4_0
      accuracy_decimals: 1
    pm_10_0:
      name: " PM <10µm Weight concentration"
      id: pm_10_0
      accuracy_decimals: 1
    temperature:
      name: "Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Humidity"
      accuracy_decimals: 0
    voc:
      name: "VOC"
      algorithm_tuning:
        index_offset: 100
        learning_time_offset_hours: 12
        learning_time_gain_hours: 12
        gating_max_duration_minutes: 180
        std_initial: 50
        gain_factor: 230
    temperature_compensation:
      offset: 0
      normalized_offset_slope: 0
      time_constant: 0
    acceleration_mode: low
    store_baseline: true
    address: 0x69
    update_interval: 60s
    auto_cleaning_interval: 86400s
```

### Anything in the logs that might be useful for us?

```txt

```
