### ISSUE TITLE
on_value is not triggered on Copy Sensors

### ISSUE THREAD

**Issue by ghisch** [esphome/issues#6901]
### The problem

Hello, I'm trying to use on_value with a copy sensor from an homeassistant sensor but it's not working.

### Which version of ESPHome has the issue?

ESPHome 2025.3.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

ESP32S3

### Component causing the issue

Copy Sensor

### YAML Config

```yaml
sensor:
  - platform: homeassistant
    id: source
    entity_id: sensor.source
    on_value:
      then:
       - logger.log: "Source sensor updated"

  - platform: copy
    id: copy
    source_id: source
    on_value:
      then:
       - logger.log: "Copy sensor updated"
```

### Anything in the logs that might be useful for us?

```txt
With this config, the "Source sensor updated" log appears, the other message doesn't
```

### Additional information

I tried with on_value, on_raw_value, on_state, nothing works.
I don't understand why because in the source code of the copy component, we can see publish_state used, which should trigger the on_value.

**Comment by SullyP** [comment]
Hi @ghisch,

I have seen the same issue with sensor but this is not due to a bug in esphome, this is due to a conflict between _<<: !include_ and _packages_.

This is the discussion that put me on it: https://community.home-assistant.io/t/using-includes-strategically/219726

I try to add an _on_value_ mechanism on a sensor named _real_power_ defined into the main.yaml.

On my _engine_common.yaml_ i put this:
```
sensor:
  - platform: copy
    source_id: real_power
    name: "Real Power Internal"
    id: real_power_internal
    internal: 'True'
    on_raw_value: 
      then:
        - logger.log: "EXECUTE FROM COPY1"
    on_value: 
      then:
        - logger.log: "EXECUTE FROM COPY2"
    on_value_range: 
      above: -9999
      then:
        - logger.log: "EXECUTE FROM COPY3"
```

And i included this file in my custom_engine.yaml
```
<<: !include engine_common.yaml

sensor:
  - platform: template
    name: "Relay 1 Countdown"
    id: relay1_tempo_counter
    device_class: "duration"
    state_class: "measurement"
    filters:
      - clamp:
          min_value: 0
```

The fact that i have sensor entry defined in both custom_engine.yaml and engine_common.yaml is the main issue.

See that like if include copy/paste the content of engine_common.yaml file in top of custom_engine.yaml.
The compiler will see two sensor entries and would ignore the first one, so my _real_power_internal_ doesn't exist, so i will never see any logs from it.

The solution:

1. First way : Move the  _real_power_internal_ sensor into custom_engine.yaml
2. Second way: use package instead of include
    - "All definitions from packages will be merged with your device’s main configuration in a non-destructive way. This allows overriding (parts of) configuration contained in the package(s). Substitutions in your main configuration will override substitutions with the same name in a package." see https://esphome.io/components/packages.html
