### ISSUE TITLE
Wide variance with S8 sensor with 2025.3.0

### ISSUE THREAD

**Issue by MallocArray** [esphome/issues#6902]
### The problem

I'm tracking a possible issue with 2025.3.0 and Sensair S8 sensor reporting much wider spikes of values, compared with 2025.2.2 and earlier.

Below is a screenshot that was primarily running 2025.3.0 with regular spikes swinging 20-70+ ppm while the device is outside, where it hasn't shown these types of spikes in the past.  Around 1:15 pm I reverted it to 2025.2.2 and it is much smoother.

![Image](https://github.com/user-attachments/assets/c3ff802f-0440-41b8-86e8-da5fcd5e6dc8)

Zoomed in view:

![Image](https://github.com/user-attachments/assets/95ddd8ef-5dc7-4924-bb92-3a2752d27d7a)

### Which version of ESPHome has the issue?

2025.3.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

ESp23-C3

### Component causing the issue

senseair

### YAML Config

```yaml
substitutions:
  co2_offset: '0'

sensor:
  - platform: senseair
    co2:
      name: "CO2"
      id: co2
      filters:
        - skip_initial: 1  # Sometimes returns 0 at first boot instead of valid data
        - offset: $co2_offset
    id: senseair_s8
    uart_id: senseair_s8_uart
```

### Anything in the logs that might be useful for us?

```txt

```
