### ISSUE TITLE
ESP32-S3 Invalid Header Bootloop

### ISSUE THREAD

**Issue by LuhiFox** [esphome/issues#6906]
## Issue Description
The ESP32-S3 device experiences a continuous bootloop when attempting to flash firmware, with logs showing repeated "invalid header: 0xffffffff" errors.

## Error Details
- Serial monitor shows: `invalid header: 0xffffffff` repeatedly during boot attempts
- ESP32-S3 resets continuously, unable to properly initialize
- Device manages to start the ROM bootloader but fails to load the application
- The issue persists across multiple attempts with different firmware versions

## Attempted Solutions
- Completely erased flash memory using ESP Flash Download Tool
- Attempted flashing with different SPI modes and speeds
- Tried Arduino IDE examples (all of them worked successfully)
- Manually flashed bootloader and partition table
- Used different flashing methods (Web-ESPHome, ESPHome-Flasher, esptool, Flash Download Tool)
- Tested with three different computers running both Linux and Windows operating systems
- Tried multiple different USB cables to eliminate connection issues
- Ensured no external hardware components are connected to the ESP modules that could interfere with the boot process

## Current Status
The device continues to display "invalid header: 0xffffffff" errors despite all troubleshooting attempts.

Importantly, the same issue has been reproduced with three identical ESP32-S3 modules from the same manufacturing batch. Interestingly, four other modules from the same batch have been running successfully for over 4 months without issues, which makes this problem even more puzzling.

### Which version of ESPHome has the issue?

2025.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.4

### What platform are you using?

ESP32

### Board

ESP32-S3-Zero

### Component causing the issue

Bootloader

### YAML Config

```yaml
esphome:
  name: test
  friendly_name: Test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: recommended
  variant: ESP32S3
  flash_size: 4MB

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "QFyKNThk4m7kfmB1lKQd6CMsTykLoBB8e7sJju9WF4k="

ota:
  - platform: esphome
    password: "66bfea37e88616275cecd7c1a23aa7c2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "dn06EC06Uiu0"

captive_portal:
    

light:
  - platform: status_led
    id: status_light
    output: status_output
  - platform: neopixelbus
    id: esp32s3_rgb_led
    type: RGB
    variant: WS2812
    pin: GPIO21
    num_leds: 1
    icon: mdi:led-outline
    entity_category: config
    restore_mode: ALWAYS_OFF
    method:
      type: esp32_rmt
      channel: 0

switch:
  - platform: restart
    name: $hostname restart
    
  - platform: template
    id: status_led_switch
    # name: "Status LED Switch"
    optimistic: true
    on_turn_on:
      - light.turn_on: 
          id: esp32s3_rgb_led
          red: 100%
          green: 0%
          blue: 0%
          brightness: 50%
          transition_length: 50ms
    on_turn_off:
      - light.turn_off: 
          id: esp32s3_rgb_led
          transition_length: 50ms

output:
  - platform: template
    id: status_output
    type: binary
    write_action:
      - if:
          condition:
             lambda: return state > 0;
          then:
            - if:
                condition:
                  switch.is_off: status_led_switch
                then:
                  switch.turn_on: status_led_switch
          else:
            - if:
                condition:
                  switch.is_on: status_led_switch
                then:
                  switch.turn_off: status_led_switch
```

### Anything in the logs that might be useful for us?

```txt
...
[16:22:41]invalid header: 0xffffffff
[16:22:41]invalid header: 0xffffffff
[16:22:41]invalid header: 0xffffffff
[16:22:41]invalid header: ESP-ROM:esp32s3-20210327
[16:22:41]Build:Mar 27 2021
[16:22:41]rst:0x7 (TG0WDT_SYS_RST),boot:0x2b (SPI_FAST_FLASH_BOOT)
[16:22:41]Saved PC:0x40048836
[16:22:41]invalid header: 0xffffffff
[16:22:41]invalid header: 0xffffffff
[16:22:41]invalid header: 0xffffffff
...
```

### Additional information

https://github.com/user-attachments/assets/30c66617-46a9-4aa4-9ace-4a2683008f04
