### ISSUE TITLE
Multiple displays with pages can not resolve which display to use when switching pages

### ISSUE THREAD

**Issue by pgtest** [esphome/issues#6908]
### The problem

Using an ESP32 with two  GC9A01A (driver ili9xxx) displays on SPI bus. 

Works and compiles when I do not add page switching, loading or similar. 

When adding for example lvgl.page.next the compiler throws : Too many candidates found for 'lvgl_id' type 'lvgl::LvglComponent' Some are 'lvgl_1', 'lvgl_2'. 
These are defined as ids under lvgl: and each have displays: display_1 and display_2 respectively. so the pages should be callable.

In the code at the bottom.
use logger ... no problem.
comment out logger and add lvgl.page.next instead - compiler error as above. (lvgl.page.load etc same ... can not find unique reference)

might be user error.... 

### Which version of ESPHome has the issue?

2025.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.4

### What platform are you using?

ESP32

### Board

ESp32 dev kit C

### Component causing the issue

Lvgl multiple displays and pages

### YAML Config

```yaml
esphome:
  name: esp32-round-display-1
  friendly_name: ESP32-Round-display-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "zZ0qZ781+X1f+8IOyPRI0dfSGIRYzWHpxhNbWttZhDk="

ota:
  - platform: esphome
    password: "4f9e6e243285579954b791adabbe8c14"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Round-Display-1"
    password: "X2MBZyBXW9dk"

captive_portal:
    
# Example configuration entry - single controller
spi:
  - id: lcd
    clk_pin: GPIO18
    mosi_pin: GPIO23
    interface: hardware

# spi_device:
#     id: spidev
#     cs_pin: GPIOXX
#     data_rate: 2MHz
lvgl:
  - id: lvgl_1
    displays: display_1
    buffer_size: 25%
    text_font: montserrat_16
    pages:
      - id: power_page
   
        widgets:
          - meter:
              bg_color: silver
              align: TOP_MID
              height: 240
              width: 240
              scales:
              - range_from: 12000 #-100 # scale for the needle value
                range_to: -12000 #400
                angle_range: 240      
                rotation: 150
                indicators:
                - arc:
                    color: my_green
                    end_value: -12000
                    r_mod: 20
                    start_value: -1000
                    width: 20
                    opa: 75%
                - arc:
                    color: my_blue
                    end_value: -1000
                    r_mod: 20
                    start_value: 1000
                    width: 20
                    opa: 75%
                - arc:
                    color: my_red
                    end_value: 1000
                    r_mod: 20
                    start_value: 12000
                    width: 20
                    opa: 75%
                - line:
                    id: power_needle1
                    width: 4
                    color: 0xFF0000
                    r_mod: -4
                - tick_style:
                    start_value: -12
                    end_value: 12
                    color_start: my_red
                    color_end: my_green
                    width: 1
              - range_from: 12 # scale for the value labels
                range_to: -12
                angle_range: 240
                rotation: 150
                ticks:
                  width: 1
                  count: 61 #51
                  length: 10
                  color: 0x000000
                  major:
                    stride: 5
                    width: 2
                    length: 10
                    color: 0x404040
                    label_gap: 15
              widgets:
              - label:
                  id: power_text
                  text: "kW"
                  align: CENTER
                  y: 45
              - label:
                  text: "Power Export is Green"
                  align: CENTER
                  y: 65
      - id: sun_page
        widgets:
          - meter:
              bg_color: silver
              align: TOP_MID
              height: 240
              width: 240
              scales:
                - range_from: 0 #-100 # scale for the needle value
                  range_to: 12000 #400
                  angle_range: 240        
                  rotation: 150
                  indicators:
                    - arc:
                        color: my_green
                        end_value: 12000
                        r_mod: 20
                        start_value: 0
                        width: 20
                        opa: 75%
                    - line:
                        id: sunpower_needle1
                        width: 4
                        color: 0xFF0000
                        r_mod: -4
                    - tick_style:
                        start_value: 0
                        end_value: 12
                        color_start: my_red
                        color_end: my_green
                        width: 1
                - range_from: 0 # scale for the value labels
                  range_to: 12
                  angle_range: 240
                  rotation: 150
                  ticks:
                    width: 1
                    count: 31 #51
                    length: 10
                    color: 0x000000
                    major:
                      stride: 5
                      width: 2
                      length: 10
                      color: 0x404040
                      label_gap: 15
              widgets:
                - label:
                    id: sunpower_text1
                    text: "kW"
                    align: CENTER
                    y: 45
                - label:
                    text: "Sun power in"
                    align: CENTER
                    y: 65

  - id: lvgl_2
    displays: display_2
    buffer_size: 25%
#    default_font: montserrat_26
    text_font: montserrat_16
    widgets:

      - meter:
          bg_color: silver
          align: TOP_MID
          height: 240
          width: 240
          scales:
            - range_from: 0 #-100 # scale for the needle value
              range_to: 12000 #400
              angle_range: 240              
              rotation: 150
              indicators:
                - arc:
                    color: my_green
                    end_value: 12000
                    r_mod: 20
                    start_value: 0
                    width: 20
                    opa: 75%
                - line:
                    id: sunpower_needle2
                    width: 4
                    color: 0xFF0000
                    r_mod: -4
                - tick_style:
                    start_value: 0
                    end_value: 12
                    color_start: my_red
                    color_end: my_green
                    width: 1
            - range_from: 0 # scale for the value labels
              range_to: 12
              angle_range: 240
              rotation: 150
              ticks:
                width: 1
                count: 61 #51
                length: 10
                color: 0x000000
                major:
                  stride: 5
                  width: 2
                  length: 10
                  color: 0x404040
                  label_gap: 15
          widgets:
            - label:
                id: sunpower_text2
                text: "kW"
                align: CENTER
                y: 45
            - label:
                text: "Sun power in"
                align: CENTER
                y: 65
                  

                
display:
  - platform: ili9xxx
    model: GC9A01A
    id: display_1
    spi_id: lcd
    cs_pin: GPIO22
    dc_pin: 
      number: GPIO16       # Set DC pin to GPIO2
      mode: OUTPUT
      allow_other_uses: true  # Allows sharing of this pin
    reset_pin: GPIO04
    invert_colors: true
    color_palette: 8BIT
    update_interval: never # 10s  # Updates every 10 seconds instead of 1
    dimensions:
      height: 240
      width: 240


  - platform: ili9xxx
    model: GC9A01A
    id: display_2
    spi_id: lcd
    cs_pin: GPIO15
    dc_pin:
      number: GPIO16       # Set DC pin to GPIO2
      mode: OUTPUT
      allow_other_uses: true  # Allows sharing of this pin
    invert_colors: true
    color_palette: 8BIT
    update_interval: never #10s  # Updates every 10 seconds instead of 1
    dimensions:
      height: 240
      width: 240


color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_orange
    red: 100%
    green: 50%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_teal
    red: 0%
    green: 100%
    blue: 100%
  - id: my_gray
    red: 70%
    green: 70%
    blue: 70%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%



sensor:
  - platform: homeassistant
    entity_id: sensor.el_in_ut
    id: power_in_ut
    on_value:
      - lvgl.indicator.update:
          id: power_needle1
          value: !lambda return x;
      - lvgl.label.update:
          id: power_text
          text:
            format: "%.3f kW"
            args: [ 'x/1000' ]
  - platform: homeassistant
    entity_id: sensor.soleffekt_in
    id: sunpower2
    on_value:
      - lvgl.indicator.update:
          id: sunpower_needle1
          value: !lambda return x;
      - lvgl.label.update:
          id: sunpower_text1
          text:
            format: "%.3f kW"
            args: [ 'x/1000' ]
      - lvgl.indicator.update:
          id: sunpower_needle2
          value: !lambda return x;
      - lvgl.label.update:
          id: sunpower_text2
          text:
            format: "%.3f kW"
            args: [ 'x/1000' ]

  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_a: GPIO13
    pin_b: GPIO14
    on_clockwise:
#      then:
#        lvgl.page.next: 
      - logger.log: "Turned Clockwise"
```

### Anything in the logs that might be useful for us?

```txt
Attempted usage: 2 displays ... one show "static" info i.e. no pages, and the other multiple pages switchable with rotary knob.

SPI bus is single with two devices with their own Chip Select.
```
