### ISSUE TITLE
generic-rtl8720cf-2mb-992k doesn't seem to have valid pins for hardware UART 0 and 1

### ISSUE THREAD

**Issue by fcol95** [esphome/issues#6909]
### The problem

Trying to use UART0 on a rtl8720cf config (WBR3) board.
It seems whatever I do, I can't seem to have it working.
Both for a generic uart component and for the logger component with UART0 as hardware_uart.
The first gives an error when setupping (see below), the second just doesn't output any logging on the interface.
When trying to set it up for the generic uart component, getting this error where it can't associate to the proper hardware pins, and trigger the "SoftwareSerial is not implemented for this chip" error.
The log below can't seem to find and print the proper pins for UART 0 or 1 too (UART 2 seems to be correct though, and I manage to have the logger output on that one, but my component is on UART0).
Here's the error:
```
[I][app:029]: Running through setup()...
[V][app:030]: Sorting components by setup priority...
[VV][scheduler:063]: set_interval(name='', interval=60000, offset=2966)
[C][uart.lt:049]: Setting up UART...
[E][uart.lt:081]:   SoftwareSerial is not implemented for this chip. Only hardware pins are supported:
[E][uart.lt:083]:     TX=255, RX=255
[E][uart.lt:086]:     TX=255, RX=255
[E][uart.lt:089]:     TX=16, RX=15
[E][component:119]: Component uart was marked as failed.
[E][component:164]: Component uart set Error flag: unspecified
[C][wifi:048]: Setting up WiFi...
```
Here's the config extract:
```
uart:
 - id: hlw8112_uart
   tx_pin: PA14
   rx_pin: PA13
   baud_rate: 38400
   data_bits: 8
   stop_bits: 1
```
Pin association found in the WBR3 specification here: https://developer.tuya.com/en/docs/iot/wbr3-module-datasheet?id=K9dujs2k5nriy.

Odly enough it seems to be only board component in the code base that has a "_0" and "_1" suffixes for both 
SERIAL0_RX/SERIAL0_TX and SERIAL1_RX/SERIAL1_TX entries in the dictionary in "boards.py" file. Could be related?
![Image](https://github.com/user-attachments/assets/19f94188-f61f-4e71-bb41-596e334c8225)

### Which version of ESPHome has the issue?

2025.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.4

### What platform are you using?

RTL87XX

### Board

WBR3

### Component causing the issue

UART

### YAML Config

```yaml
esphome:
  name: pow-meter-pc311
  friendly_name: pow-meter-pc311
  on_boot:
    - priority: 600
      then:
        - output.turn_on: HLW8112_SCLK
        - output.turn_on: HLW8112_SCSN
        - output.turn_on: ZB25VQ80_SCSN

rtl87xx:
  board: generic-rtl8720cf-2mb-992k
  framework:
    version: 0.0.0
    source: https://github.com/prokoma/libretiny#55aacc8 # Temporary Fix for RTL8720CF OTA!

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

mdns:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "pow-meter-pc311"
    password: !secret wifi_ap_password

captive_portal:
  
# NOTE: Software uart unimplemented on rtl8720cf and UART0 fails to init!!! 
uart: # Ensure modif is done on R3 to pull down SPIEN! (SPI unsupported yet for rtl8720cf)
 - id: hlw8112_uart
   tx_pin: PA14 # SDO/TX of HLW8112
   rx_pin: PA13 # SDI/RX of HLW8112
   baud_rate: 38400 # NOTE: Ensure SCLK (PA4) and SCSN (PA7) are high.
   data_bits: 8
   stop_bits: 1
   parity: EVEN # TODO: Check if not ODD?

# Enable Logging
logger:
  level: VERY_VERBOSE
  hardware_uart: UART2 # L_RX and L_TX on J1 - Note: UART0 (U0TX and U0RX on J3) doesn't seem to work with generic-rtl8720cf-2mb-992k config!
    
output:
  - platform: gpio
    id: HLW8112_SCLK
    pin: PA4
  - platform: gpio
    id: HLW8112_SCSN
    pin: PA7
  - platform: gpio
    id: ZB25VQ80_SCSN
    pin: PA11

# external_components:
#   - source:
#       type: git
#       url: https://github.com/fcol95/esphome
#       ref: hlw8112
#     components: [ hlw8112 ]
```

### Anything in the logs that might be useful for us?

```txt
== RAM Start ==
I [      0.000] LibreTiny v1.7.0+sha.55aacc8 on generic-rtl8720cf-2mb-992k, compiled at Mar 30 2025 22:13:07, GCC 10.3.1 (-Os)
[I][logger:050]: Log initialized
[VV][lt.preferences:064]: fdb_kv_get_blob: key: 233825507, len: 4
[C][safe_mode:079]: There have been 0 suspected unsuccessful boot attempts
[VV][lt.preferences:041]: s_pending_save: key: 233825507, len: 4
[D][lt.preferences:104]: Saving 1 preferences to flash...
[VV][lt.preferences:113]: Checking if FDB data 233825507 has changed
[V][lt.preferences:115]: sync: key: 233825507, len: 4
[D][lt.preferences:132]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[V][app:030]: Sorting components by setup priority...
[VV][scheduler:063]: set_interval(name='', interval=60000, offset=2966)
[C][uart.lt:049]: Setting up UART...
[E][uart.lt:081]:   SoftwareSerial is not implemented for this chip. Only hardware pins are supported:
[E][uart.lt:083]:     TX=255, RX=255
[E][uart.lt:086]:     TX=255, RX=255
[E][uart.lt:089]:     TX=16, RX=15
[E][component:119]: Component uart was marked as failed.
[E][component:164]: Component uart set Error flag: unspecified
[C][wifi:048]: Setting up WiFi...
[C][wifi:061]: Starting WiFi...
[C][wifi:062]:   Local MAC: B8:06:0D:4A:7D:FB
[VV][lt.preferences:061]: NVS length does not match (0!=98)
[V][wifi_lt:035]: Enabling STA.
interface 0 is initialized
                          interface 1 is initialized

Initializing WIFI ...
WIFI initialized
                [V][wifi_lt:270][wifievent]: Event: WiFi STA start
[D][wifi:482]: Starting scan...
[VV][scheduler:225]: Running interval '' with interval=60000 last_execution=4294904398 (now=299)
[W][component:157]: Component wifi set Warning flag: scanning for networks
[V][wifi_lt:264][wifievent]: Event: WiFi Scan Done status=0 number=23 scan_id=0
[D][wifi:497]: Found networks:
[I][wifi:540]: - 'FIZZ56132' (0E:24:6B:1A:63:06) ▂▄▆█
[D][wifi:542]:     Channel: 9
[D][wifi:543]:     RSSI: -48 dB
[D][wifi:545]: - '<' (00:00:00:00:00:00) ▂▄▆█
[D][wifi:545]: - 'HELIX8A30' (48:4B:D4:28:8A:34) ▂▄▆█
[D][wifi:545]: - 'FIZZ56132_Ext2' (C4:41:1E:DF:AF:42) ▂▄▆█
[D][wifi:545]: - 'Bob' (1E:9D:72:2E:5F:C6) ▂▄▆█
[D][wifi:545]: - 'Roberto Tozzi' (60:6C:63:2F:5B:C8) ▂▄▆█
[D][wifi:545]: - 'BELL083' (0C:AC:8A:EE:CC:69) ▂▄▆█
[D][wifi:545]: - 'VIRGIN872' (A8:9A:93:15:97:FE) ▂▄▆█
[D][wifi:545]: - 'Danielle' (E2:DB:D1:2A:C7:53) ▂▄▆█
[D][wifi:545]: - 'TP-Link_Guest_C3D3' (3E:84:6A:A9:C3:D3) ▂▄▆█
[D][wifi:545]: - 'BELL985' (F0:82:61:3E:37:AA) ▂▄▆█
[D][wifi:545]: - 'VIDEOTRON6384' (60:31:97:FC:72:58) ▂▄▆█
[D][wifi:545]: - 'TP-Link_C3D3' (3C:84:6A:A9:C3:D3) ▂▄▆█
[D][wifi:545]: - 'Helix101' (F8:79:0A:EA:A7:27) ▂▄▆█
[D][wifi:545]: - 'Helix12' (F4:C1:14:56:1E:AE) ▂▄▆█
[D][wifi:545]: - 'Helix12' (F0:21:E0:B9:97:86) ▂▄▆█
[D][wifi:545]: - 'BELL790' (F0:B4:D2:2A:00:59) ▂▄▆█
[D][wifi:545]: - 'VIDEOTRON1235_2GEXT' (3C:37:86:79:07:07) ▂▄▆█
[D][wifi:545]: - 'VIDEOTRON1235' (BC:99:11:FB:92:DC) ▂▄▆█
[D][wifi:545]: - 'Patator' (90:8D:78:5B:E3:E5) ▂▄▆█
[D][wifi:545]: - 'Venus' (F8:79:0A:DD:2E:18) ▂▄▆█
[D][wifi:545]: - 'silent' (42:0F:C1:68:4E:75) ▂▄▆█
[D][wifi:545]: - 'verite24' (20:AA:4B:5E:7F:BF) ▂▄▆█
[I][wifi:313]: WiFi Connecting to 'FIZZ56132'...
[V][wifi:315]: Connection Params:
[V][wifi:316]:   SSID: 'FIZZ56132'
[V][wifi:319]:   BSSID: 0E:24:6B:1A:63:06
[V][wifi:349]:   Password: ''
[V][wifi:354]:   Channel: 9
[V][wifi:363]:   Using DHCP IP
[V][wifi:365]:   Hidden: NO

[Driver]: set ssid [-]

[Driver]: set BSSID: 0e:24:6b:1a:63:06

[Driver]: set ssid [FIZZ56132]

[Driver]: start auth to 0e:24:6b:1a:63:06

[Driver]: auth alg = 2

[Driver]: auth success, start assoc
                                   [V][wifi_lt:264][wifievent]: Event: WiFi Scan Done status=0 number=0 scan_id=0

[Driver]: association success(res=33)

[Driver]: set pairwise key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4)

[Driver]: set group key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4) keyid:1
                                                                           [V][wifi_lt:283][wifievent]: Event: Connected ssid='FIZZ56132' bssid=0E:24:6B:1A:63:06 channel=9, authmode=WPA PSK

Interface 0 IP address : 192.168.50.25[V][wifi_lt:328][wifievent]: Event: Got IP static_ip=192.168.50.25 gateway=192.168.50.1
[C][logger:177]: Logger:
[C][logger:178]:   Max Level: VERY_VERBOSE
[C][logger:179]:   Initial Level: VERY_VERBOSE
[C][logger:181]:   Log Baud Rate: 115200
[C][logger:182]:   Hardware UART: UART2
[C][uart.lt:101]: UART Bus:
[C][uart.lt:102]:   Type: software
[C][uart.lt:106]:   TX Pin: 2
[C][uart.lt:107]:   RX Pin: 3
[C][uart.lt:109]:   RX Buffer Size: 256
[C][uart.lt:111]:   Baud Rate: 38400 baud
[C][uart.lt:112]:   Data Bits: 8
[C][uart.lt:113]:   Parity: NONE
[C][uart.lt:114]:   Stop bits: 1
[E][component:082]:   Component uart is marked FAILED
[C][gpio.output:010]: GPIO Binary Output:
[C][gpio.output:011]:   Pin: 4
[C][gpio.output:010]: GPIO Binary Output:
[C][gpio.output:011]:   Pin: 7
[C][gpio.output:010]: GPIO Binary Output:
[C][gpio.output:011]:   Pin: 11
[C][captive_portal:089]: Captive Portal:
[C][web_server:285]: Web Server:
[C][web_server:286]:   Address: pow-meter-pc311-water-heater.local:80
[C][mdns:116]: mDNS:
[C][mdns:117]:   Hostname: pow-meter-pc311-water-heater
[V][mdns:118]:   Services:
[V][mdns:120]:   - _esphomelib, _tcp, 6053
[V][mdns:122]:     TXT: friendly_name = pow-meter-pc311-water-heater
[V][mdns:122]:     TXT: version = 2025.3.2
[V][mdns:122]:     TXT: mac = b8060d4a7dfb
[V][mdns:122]:     TXT: platform = RTL8720CF
[V][mdns:122]:     TXT: board = generic-rtl8720cf-2mb-992k
[V][mdns:122]:     TXT: network = wifi
[V][mdns:122]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[V][mdns:120]:   - _http, _tcp, 80
[C][esphome.ota:073]: Over-The-Air updates:
[C][esphome.ota:074]:   Address: pow-meter-pc311-water-heater.local:8892
[C][esphome.ota:075]:   Version: 2
[C][esphome.ota:078]:   Password configured
[C][safe_mode:018]: Safe Mode:
[C][safe_mode:019]:   Boot considered successful after 60 seconds
[C][safe_mode:021]:   Invoke after 10 boot attempts
[C][safe_mode:022]:   Remain in safe mode for 300 seconds
[C][api:140]: API Server:
[C][api:141]:   Address: pow-meter-pc311-water-heater.local:6053
[C][api:143]:   Using noise encryption: YES
[C][lt.component:013]: LibreTiny:
[C][lt.component:014]:   Version: v1.7.0+sha.55aacc8 on generic-rtl8720cf-2mb-992k, compiled at Mar 30 2025 22:12:02, GCC 10.3.1 (-Os)
[C][lt.component:015]:   Loglevel: 3
[D][api:103]: Accepted 192.168.50.12
[W][component:170]: Component api cleared Warning flag
[VV][api.socket:696]: 192.168.50.12: Handshake complete!
[VV][api.service:661]: on_hello_request: HelloRequest {
                                                         client_info: 'ESPHome Logs 2025.3.2'
                                                                                               api_version_major: 1
                                                                                                                     api_version_minor: 10
                                                                                                                                          }
[V][api.connection:1782]: Hello from client: 'ESPHome Logs 2025.3.2' | 192.168.50.12 | API Version 1.10
[VV][api.service:013]: send_hello_response: HelloResponse {
                                                             api_version_major: 1
                                                                                   api_version_minor: 10
                                                                                                          server_info: 'pow-meter-pc311-water-heater (esphome v2025.3.2)'
                                                                                                                                                                           name: 'pow-meter-pc311-water-heater'
                  }
[VV][api.service:670]: on_connect_request: ConnectRequest {
                                                             password: ''
                                                                         }
[D][api.connection:1801]: ESPHome Logs 2025.3.2 (192.168.50.12): Connected successfully
[VV][api.service:019]: send_connect_response: ConnectResponse {
                                                                 invalid_password: NO
                                                                                     }
[VV][api.service:742]: on_subscribe_logs_request: SubscribeLogsRequest {
                                                                          level: LOG_LEVEL_VERY_VERBOSE
                                                                                                         dump_config: YES
                                                                                                                         }
[I][app:100]: ESPHome version 2025.3.2 compiled on Mar 30 2025, 22:39:09
[C][wifi:600]: WiFi:
[C][wifi:428]:   Local MAC: B8:06:0D:4A:7D:FB
[C][wifi:433]:   SSID: 'FIZZ56132'
[C][wifi:436]:   IP Address: 192.168.50.25
[C][wifi:439]:   BSSID: 0E:24:6B:1A:63:06
[C][wifi:441]:   Hostname: 'pow-meter-pc311-water-heater'
[C][wifi:443]:   Signal strength: -48 dB ▂▄▆█
[V][wifi:445]:   Priority: 0.0
[C][wifi:447]:   Channel: 9
[C][wifi:448]:   Subnet: 255.255.255.0
[C][wifi:449]:   Gateway: 192.168.50.1
[C][wifi:450]:   DNS1: 192.168.50.3
[C][wifi:451]:   DNS2: 192.168.50.3
[C][logger:177]: Logger:
[C][logger:178]:   Max Level: VERY_VERBOSE
[C][logger:179]:   Initial Level: VERY_VERBOSE
[C][logger:181]:   Log Baud Rate: 115200
[C][logger:182]:   Hardware UART: UART2
[C][uart.lt:101]: UART Bus:
[C][uart.lt:102]:   Type: software
[C][uart.lt:106]:   TX Pin: 2
[C][uart.lt:107]:   RX Pin: 3
[C][uart.lt:109]:   RX Buffer Size: 256
[C][uart.lt:111]:   Baud Rate: 38400 baud
[C][uart.lt:112]:   Data Bits: 8
[C][uart.lt:113]:   Parity: NONE
[C][uart.lt:114]:   Stop bits: 1
[E][component:082]:   Component uart is marked FAILED
[C][gpio.output:010]: GPIO Binary Output:
[C][gpio.output:011]:   Pin: 4
[C][gpio.output:010]: GPIO Binary Output:
[C][gpio.output:011]:   Pin: 7
[C][gpio.output:010]: GPIO Binary Output:
[C][gpio.output:011]:   Pin: 11
[C][captive_portal:089]: Captive Portal:
[C][web_server:285]: Web Server:
[C][web_server:286]:   Address: pow-meter-pc311-water-heater.local:80
[C][mdns:116]: mDNS:
[C][mdns:117]:   Hostname: pow-meter-pc311-water-heater
[V][mdns:118]:   Services:
[V][mdns:120]:   - _esphomelib, _tcp, 6053
[V][mdns:122]:     TXT: friendly_name = pow-meter-pc311-water-heater
[V][mdns:122]:     TXT: version = 2025.3.2
[V][mdns:122]:     TXT: mac = b8060d4a7dfb
[V][mdns:122]:     TXT: platform = RTL8720CF
[V][mdns:122]:     TXT: board = generic-rtl8720cf-2mb-992k
[V][mdns:122]:     TXT: network = wifi
[V][mdns:122]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[V][mdns:120]:   - _http, _tcp, 80
[C][esphome.ota:073]: Over-The-Air updates:
[C][esphome.ota:074]:   Address: pow-meter-pc311-water-heater.local:8892
[C][esphome.ota:075]:   Version: 2
[C][esphome.ota:078]:   Password configured
[C][safe_mode:018]: Safe Mode:
[C][safe_mode:019]:   Boot considered successful after 60 seconds
[C][safe_mode:021]:   Invoke after 10 boot attempts
[C][safe_mode:022]:   Remain in safe mode for 300 seconds
[C][api:140]: API Server:
[C][api:141]:   Address: pow-meter-pc311-water-heater.local:6053
[C][api:143]:   Using noise encryption: YES
[C][lt.component:013]: LibreTiny:
[C][lt.component:014]:   Version: v1.7.0+sha.55aacc8 on generic-rtl8720cf-2mb-992k, compiled at Mar 30 2025 22:12:02, GCC 10.3.1 (-Os)
[C][lt.component:015]:   Loglevel: 3
```
