### ISSUE TITLE
esp32_camera_web_server stopped working in 2025.3.3

### ISSUE THREAD

**Issue by adamkobor** [esphome/issues#6910]
### The problem

The esp32_camera_web_server stopped working in 2025.3.3 (see the attached logs).

```
[08:01:37][E][esp32_camera_web_server:097]:   Setup Failed
[08:01:37][E][component:082]:   Component esp32_camera_web_server is marked FAILED
```

### Which version of ESPHome has the issue?

2025.3.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

ESP32CAM

### YAML Config

```yaml
substitutions:
  display_name: esp32cam

esphome:
  name: $display_name
  friendly_name: esp32cam

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: #######

ota:
  - platform: esphome
    password: ########

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

captive_portal:

# Sensors
sensor:
   - platform: wifi_signal
     name: ${display_name} WiFi Signal
     
esp32_camera:
  name: ${display_name} stream
  external_clock:
    pin: GPIO0
    frequency: 10MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: SVGA
  jpeg_quality: 30  # max. 63
  max_framerate: 24.0fps
  idle_framerate: 0.2fps
  vertical_flip: false
  horizontal_mirror: false
  brightness: 1 # -2 to 2
  contrast: 0 # -2 to 2
  saturation: 1
  special_effect: none
  # exposure settings
  aec_mode: auto
  aec2: false
  ae_level: 0
  aec_value: 300
  # gain settings
  agc_mode: auto
  agc_gain_ceiling: 2x
  agc_value: 0
  # white balance setting
  wb_mode: auto

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

switch:
  - platform: restart
    name: esp-cam restart
binary_sensor:
  - platform: status
    name: esp-cam status
```

### Anything in the logs that might be useful for us?

```txt

```
