### ISSUE TITLE
[SOLVED] WiFi always connects to weakest AP (mesh network)

### ISSUE THREAD

**Issue by vador31** [esphome/issues#6919]
### The problem

I have 2 AP with same SSID (mesh network) and my ESP32-C3 Super Mini Plus (with external antenna) ALWAYS connects to the farest AP :/

I have tried "power_save_mode: none" but it had no effect (and it's not compatible with BLE).

I've also tried to put BSSID of each AP in the config but it had no effect.

### Which version of ESPHome has the issue?

2025.3.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

HAOS 2025.4.1

### What platform are you using?

ESP32

### Board

ESP32-C3 Super Mini Plus

### Component causing the issue

wifi

### YAML Config

```yaml
esphome:
  name: chauffage
  friendly_name: Chauffage
  on_boot:
    priority: -100
    then:
      - lambda: |-
          ESP_LOGI("Boot", "STOP BLE...");
          id(ble_tracker).stop_scan();
          id(ble_tracker).set_scan_continuous(false);
          id(ble_tracker).set_scan_active(false);
      - ble.disable:

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  level: debug # none error warn info debug verbose very_verbose

# Clé Home Assistant
api:
  encryption:
    key: "##############"

ota:
  - platform: esphome
    password: "##############"

wifi:
  #~ reboot_timeout: 3min
  fast_connect: false
  power_save_mode: light # none est incompatible avec BLE
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      bssid: 5C:E9:31:C3:B0:1E # routeur
      manual_ip:
        static_ip: 192.168.1.251
        gateway: 192.168.1.1
        subnet: 255.255.255.0
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      bssid: 24:2F:D0:44:6A:59 # CPL
      manual_ip:
        static_ip: 192.168.1.251
        gateway: 192.168.1.1
        subnet: 255.255.255.0

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    active: false
    continuous: false
    interval: 1100ms
    window: 1100ms

sensor:
  - platform: wifi_signal
    name: "Qualité WiFi dBm"
    id: wifi_signal_db
    update_interval: 15s
    entity_category: "diagnostic"
    disabled_by_default: true
    icon: mdi:wifi
  - platform: copy
    source_id: wifi_signal_db
    name: "Qualité WiFi %"
    id: wifi_signal_percent
    entity_category: "diagnostic"
    disabled_by_default: true
    icon: mdi:wifi
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    device_class: "signal_strength"

switch:
  - platform: gpio
    pin:
      number: GPIO8
      inverted: false
      mode:
        input: false
        output: true
        pullup: false
        pulldown: true
    id: led
    name: "Led bleue"
    icon: 'mdi:lightbulb'
    disabled_by_default: false
    internal: true
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: false
        output: true
        pullup: true
        pulldown: false
    name: "Cumulus mode HA"
    icon: 'mdi:home-assistant'
    disabled_by_default: false
    internal: false
  - platform: gpio
    pin:
      number: GPIO1
      inverted: true
      mode:
        input: false
        output: true
        pullup: true
        pulldown: false
    name: "Cumulus"
    icon: 'mdi:thermometer-water'
    disabled_by_default: false
    internal: false
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
      mode:
        input: false
        output: true
        pullup: true
        pulldown: false
    name: "Radiateurs mode stop = HG"
    icon: 'mdi:sun-snowflake-variant'
    disabled_by_default: false
    internal: false
  - platform: gpio
    pin:
      number: GPIO3
      inverted: true
      mode:
        input: false
        output: true
        pullup: true
        pulldown: false
    name: "GPIO 3"
    icon: 'mdi:power-plug-outline'
    disabled_by_default: false
    internal: false
  - platform: gpio
    pin:
      number: GPIO9
      inverted: true
      mode:
        input: false
        output: true
        pullup: true
        pulldown: false
    name: "GPIO 9"
    icon: 'mdi:power-plug-outline'
    disabled_by_default: false
    internal: false
  - platform: gpio
    pin:
      number: GPIO10
      inverted: true
      mode:
        input: false
        output: true
        pullup: true
        pulldown: false
    name: "GPIO 10"
    icon: 'mdi:power-plug-outline'
    disabled_by_default: false
    internal: false
  - platform: gpio
    pin:
      number: GPIO20
      inverted: true
      mode:
        input: false
        output: true
        pullup: true
        pulldown: false
    name: "GPIO 20"
    icon: 'mdi:power-plug-outline'
    disabled_by_default: false
    internal: false
  - platform: gpio
    pin:
      number: GPIO21
      inverted: true
      mode:
        input: false
        output: true
        pullup: true
        pulldown: false
    name: "GPIO 21"
    icon: 'mdi:power-plug-outline'
    disabled_by_default: false
    internal: false

globals:
  - id: enservice
    type: bool
    restore_value: no
    initial_value: 'false'
    
interval:
    - interval: 1s
      then:
        - if:
            condition: ble.enabled
            then:
              if:
                condition:
                  switch.is_off: led
                then:
                  - switch.turn_on: led
            else:
              if:
                condition:
                  switch.is_on: led
                then:
                  - switch.turn_off: led
        - if:
            condition: 
              wifi.connected:
            then:
              - lambda: |-
                  if (!id(enservice))
                  {
                    if (!id(startBLE).is_running())
                    {
                      ESP_LOGI("BLE", "Je tente de démarrer le BLE...");
                      id(startBLE).execute();
                    }
                  }
            else:
              - lambda: |-
                  if (id(enservice))
                  {
                    id(enservice)=false;
                    ESP_LOGE("Watchdog", "WiFi HS --> arrêt du scan BLE...");
                    id(ble_tracker).stop_scan();
                    id(ble_tracker).set_scan_continuous(false);
                    id(ble_tracker).set_scan_active(false);
                  }
              - ble.disable:

script:
  - id: startBLE
    mode: single
    then:
      - delay: 60s
      - ble.enable:
      - delay: 5s
      - if:
          condition: ble.enabled
          then:
            - lambda: |-
                ESP_LOGI("Watchdog", "Le Watchdog WiFi démarre...");
                id(enservice)=true;
                ESP_LOGI("Watchdog", "Le scan BLE démarre...");
                id(ble_tracker).set_scan_active(true);
                id(ble_tracker).set_scan_continuous(true);
                id(ble_tracker).start_scan();
          else:
            - lambda: |-
                ESP_LOGE("BLE", "Le BLE ne démarre pas...");
            - delay: 60s
```

### Anything in the logs that might be useful for us?

```txt
[11:03:13][W][wifi:690]: Restarting WiFi adapter...
[11:03:18][D][wifi:482]: Starting scan...
[11:03:24][D][wifi:497]: Found networks:
[11:03:24][I][wifi:541]: - 'Skynet' (24:2F:D0:44:6A:59) [redacted]▂▄▆█
[11:03:24][D][wifi:542]:     Channel: 2
[11:03:24][D][wifi:543]:     RSSI: -85 dB
[11:03:24][I][wifi:541]: - 'Skynet' (5C:E9:31:C3:B0:1E) [redacted]▂▄▆█
[11:03:24][D][wifi:542]:     Channel: 7
[11:03:24][D][wifi:543]:     RSSI: -58 dB
[11:03:24][D][wifi:546]: - ''[redacted] (8E:E9:31:C3:B0:1E) [redacted]▂▄▆█
[11:03:24][D][wifi:546]: - ''[redacted] (26:2F:D0:45:6A:59) [redacted]▂▄▆█
[11:03:24][I][wifi:313]: WiFi Connecting to 'Skynet'...
[11:03:25][I][wifi:617]: WiFi Connected!
[11:03:25][C][wifi:428]:   Local MAC: DC:1E:D5:1C:5A:70
[11:03:25][C][wifi:433]:   SSID: 'Skynet'[redacted]
[11:03:25][C][wifi:436]:   IP Address: 192.168.1.251
[11:03:25][C][wifi:440]:   BSSID: 24:2F:D0:44:6A:59[redacted]
[11:03:25][C][wifi:441]:   Hostname: 'chauffage'
[11:03:25][C][wifi:443]:   Signal strength: -81 dB ▂▄▆█
[11:03:25][C][wifi:447]:   Channel: 2
[11:03:25][C][wifi:448]:   Subnet: 255.255.255.0
[11:03:25][C][wifi:449]:   Gateway: 192.168.1.1
[11:03:25][C][wifi:450]:   DNS1: 0.0.0.0
[11:03:25][C][wifi:451]:   DNS2: 0.0.0.0
[11:03:25][C][api:026]: Setting up Home Assistant API server...
```
