### ISSUE TITLE
Light state after reboot

### ISSUE THREAD

**Issue by Rink76** [esphome/issues#692]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff Basic

**Affected component:**

Restore_mode

**Description of problem:**

Initially I used a GPIO Switch to control my light. The option "restore_mode: ALWAYS_OFF" prevented the light from switching on after a reboot.

Because I wanted my light to show-up as light. in Hassio, not as switch. I changed some configuration. Configuration works fine, but on reboot the light is always switched on.

**Problem-relevant YAML-configuration entries:**
```yaml
# Generic ESP8266
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

#
# Binary Sensor Components
#
binary_sensor: 
 
  # GPIO Binary Sensor
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${upper_devicename} Switch"
    on_press:
      - light.toggle: bulb

#   
# Output Components
#
output:
 
  # ESP8266 Software PWM Output
  - platform: gpio
    pin:
      number: GPIO12
      inverted: false
    id: relay

#
# Light Components
#
light:
  - platform: binary
    name: "${upper_devicename} Relais"
    output: relay
    id: bulb
    restore_mode: ALWAYS_OFF


```

**Logs (if applicable):**

```


```

**Additional information and things you've tried:**

Changed inverted from false to true, now the light stays off after a reboot.

```yaml
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
    id: relay
```
But now my light switch reports "on" when the bulb (GPIO12) is "off" and "off" when the bulb is "on".

```yaml
light:
  - platform: binary
    name: "${upper_devicename} Relais"
    output: relay
    id: bulb
    restore_mode: ALWAYS_OFF
```
Is there any way to invert the light switch as well, or a different approach to keep the light switched off after reboot ?

Thanks in advance!
