### ISSUE TITLE
LVGL widget update unexpected behaviour

### ISSUE THREAD

**Issue by pmannk** [esphome/issues#6920]
### The problem

When calling lvgl.label.update and using a global map, the incorrect label is updated
I'm importing weather information from Home Assistant using a text sensor.
I have a sensor for todays weather, and another for tomorrows as follows:

```
text_sensor:
  # Todays Forecast
  - platform: homeassistant #Current Condition Name
    id: w_today_cond
    entity_id: sensor.forecast_today_owm
    on_value:
      then:
        - logger.log: "fr_cond_today updated"
        - lvgl.label.update:
            id: lbl_weather_today_icon
            text: !lambda |-
              auto it_icon = id(weather_icon_map).find(x);
              if (it_icon != id(weather_icon_map).end()) {
                  return it_icon->second;
              } else {
                  return "\U000F0453";
              }
        - lvgl.label.update:
            id: lbl_weather_today_name
            text: !lambda |-
              auto it_name = id(weather_name_map).find(x);
              if (it_name != id(weather_name_map).end()) {
                  return it_name->second;
              } else {
                  return x.c_str();
              }

  # Tomorrows forecast
  - platform: homeassistant
    id: w_tomorrow_cond
    entity_id: sensor.forecast_tomorrow_owm
    on_value:
      then:
        - logger.log: "fr_cond_tomorrow updated"
        - lvgl.label.update:
            id: lbl_weather_tomorrow_icon
            text: !lambda |-
              auto it_icon = id(weather_icon_map).find(x);
              if (it_icon != id(weather_icon_map).end()) {
                  return it_icon->second;
              } else {
                  return "\U000F0453";
              }
        - lvgl.label.update:
            id: lbl_weather_tomorrow_name
            text: !lambda |-
              auto it_name = id(weather_name_map).find(x);
              if (it_name != id(weather_name_map).end()) {
                  return it_name->second;
              } else {
                  return x.c_str();
              }

```
The lambdas above update labels on two different pages.

```
.........
  pages:
    - id: weather_forecast
      widgets:
        - obj:
            align: CENTER
            width: 100%
            height: 100%
            radius: 0
            pad_all: 10
            bg_color: black
            text_color: 0x008000
            border_width: 0
            layout:
              pad_column: 0
              type: GRID
              grid_rows: [FR(48), FR(13), FR(13), FR(13), FR(13), FR(13), FR(13)]
              grid_columns: [FR(10), FR(40), FR(40), FR(10)]
            widgets:
              - label:
                  text: "\U000F14E4"
                  text_color: 0x008000
                  id: lbl_weather_today_icon
                  text_font: icons_conditions
                  text_align: CENTER
                  border_width: 0
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 2
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: CENTER

              - label:
                  text: "Unknown"
                  id: lbl_weather_today_name
                  text_align: CENTER
                  text_font: montserrat_28
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 2
                  grid_cell_column_span: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER
.........

    - id: weather_tomorrow
      widgets:
        - obj:
            align: CENTER
            width: 100%
            height: 100%
            radius: 0
            pad_all: 10
            bg_color: black
            text_color: 0x800080
            border_width: 0
            layout:
              pad_column: 0
              type: GRID
              grid_rows: [FR(24), FR(24), FR(13), FR(13), FR(13), FR(13)]
              grid_columns: [FR(10), FR(40), FR(40), FR(10)]
            widgets:
              - label:
                  text: "\U000F14E4"
                  text_color: 0x800080
                  id: lbl_weather_tomorrow_icon
                  text_font: icons_conditions
                  text_align: CENTER
                  border_width: 0
                  grid_cell_row_pos: 0
                  grid_cell_row_span: 2
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 2
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: CENTER

              - label:
                  text: "Tomorrow"
                  id: lbl_weather_tomorrow_header
                  text_align: CENTER
                  text_font: montserrat_28
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 2
                  grid_cell_column_span: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: END

              - label:
                  text: "Unknown"
                  id: lbl_weather_tomorrow_name
                  text_align: CENTER
                  text_font: montserrat_28
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 2
                  grid_cell_column_span: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: START
.........

```

And globals are font are defined as follows:

```
globals:
  - id: weather_icon_map
    type: std::map<std::string, std::string>
    initial_value: '{
      {"cloudy", "\U000F0590"},
      {"cloudy-alert", "\U000F0F2F"},
      {"cloudy-arrow-right", "\U000F0590"},
      {"fog", "\U000F0591"},
      {"hail", "\U000F0592"},
      {"hazy", "\U000F0591"},
      {"hurricane", "\U000F059D"},
      {"lightning", "\U000F0593"},
      {"lightning-rainy", "\U000F067E"},
      {"clear-night", "\U000F0594"},
      {"night-partly-cloudy", "\U000F0594"},
      {"partlycloudy", "\U000F0595"},
      {"partly-lightning", "\U000F0593"},
      {"partly-rainy", "\U000F0597"},
      {"partly-snowy", "\U000F0598"},
      {"partly-snowy-rainy", "\U000F067F"},
      {"pouring", "\U000F0596"},
      {"rainy", "\U000F0597"},
      {"snowy", "\U000F0598"},
      {"snowy-heavy", "\U000F0598"},
      {"snowy-rainy", "\U000F067F"},
      {"sunny", "\U000F0599"},
      {"sunny-alert", "\U000F0F2F"},
      {"sunny-off", "\U000F14E4"},      
      {"sunset", "\U000F059A"},
      {"sunset-down", "\U000F059B"},
      {"sunset-up", "\U000F059C"},
      {"tornado", "\U000F059D"},
      {"windy", "\U000F059D"},
      {"windy-variant", "\U000F059E"}
    }'
  
  - id: weather_name_map
    type: std::map<std::string, std::string>
    initial_value: '{
      {"cloudy", "Cloudy"},
      {"cloudy-alert", "Cloudy"},
      {"cloudy-arrow-right", "Cloudy"},
      {"fog", "Fog"},
      {"hail", "Hail"},
      {"hazy", "Haze"},
      {"hurricane", "Hurricane"},
      {"lightning", "Lightning"},
      {"lightning-rainy", "Lightning"},
      {"clear-night", "Clear Night"},
      {"night-partly-cloudy", "Partly Cloudy"},
      {"partlycloudy", "Partly Cloudy"},
      {"partly-lightning", "Lightning"},
      {"partly-rainy", "Rainy"},
      {"partly-snowy", "Snowy"},
      {"partly-snowy-rainy", "Snowy"},
      {"pouring", "Pouring"},
      {"rainy", "Rainy"},
      {"snowy", "Snowy"},
      {"snowy-heavy", "Heavy Snow"},
      {"snowy-rainy", "Snowy"},
      {"sunny", "Sunny"},
      {"sunny-alert", "Sunny"},
      {"sunny-off", "Sunny"},
      {"sunset", "Sunset"},
      {"sunset-down", "Sunset"},
      {"sunset-up", "Sunrise"},
      {"tornado", "Tornado"},
      {"windy", "Windy"},
      {"windy-variant", "Windy"}
    }'

font:
  - file: "base_configs/fonts/materialdesignicons-webfont.ttf"
    id: icons_conditions
    size: 150
    bpp: 4
    glyphs: [
      "\U000F0594", # clear-night
      "\U000F0590", # cloudy
      "\U000F0F2F", # exceptional
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partlycloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # sunny
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      "\U000F059A", # sunset
      "\U000F059B", # sunset-down
      "\U000F059C", # sunset-up      
      "\U000F14E4", # sunny-off
      "\U000F0453", # loading
      ]

```

When the HA sensor updates, the "_name_" label updates fine, however the "_icon_" label is exhibiting very strange behaviour.

- On the lvgl display, the "today" page reflects the icon state of tomorrows forecast
- On the lvgl display, the "tomorrow" page reflects the default state defined on the lvgl label (U000F14E4)

I've tried creating dedicated _weather_icon_map_, _weather_name_map_ and _font_ definitions for the second label, however it always seems to revert to this behaviour.
If I comment out _one_ of the Home Assistant sensors, the remaining sensor works as expected, updating the correct lvgl label and page

### Which version of ESPHome has the issue?

2025.3.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.4

### What platform are you using?

ESP32-IDF

### Board

esp32-s3

### Component causing the issue

lvgl

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```
