### ISSUE TITLE
ld2420.cpp references undeclared operating_selector_ — compile fails in ESPHome 2025.2.0

### ISSUE THREAD

**Issue by brianseaders** [esphome/issues#6928]
### The problem

The LD2420 component fails to compile in ESPHome 2025.2.0 due to references to `operating_selector_` in ld2420.cpp that are not declared in the LD2420Component class. This causes a hard compiler failure even with minimal valid YAML configuration.

### Which version of ESPHome has the issue?

2025.2.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A — not applicable

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

ld2420

### YAML Config

```yaml
esphome:
  name: gpt-test
  friendly_name: GPT TEST

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "xwZAt/o8OnkbM/DQMMRNrtJr3NpmEQzB6nUPe16kRjI="

ota:
  - platform: esphome
    password: "ef96dc7a8d381405b21220f7f0bf8635"

wifi:
  ssid: "test"
  password: "12345678"

  ap:
    ssid: "Gpt-Test Fallback Hotspot"
    password: "3ewPru113TbA"

captive_portal:

uart:
  id: uart_ld2420
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000

ld2420:
  uart_id: uart_ld2420
  id: radar

sensor:
  - platform: uptime
    name: "Uptime Sensor"
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: ld2420
    ld2420_id: radar
    moving_distance:
      name: "LD2420 Moving Distance"

binary_sensor:
  - platform: status
    name: "Device Online"

  - platform: ld2420
    ld2420_id: radar
    has_target:
      name: "LD2420 Has Target"
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs\gpt-test\src\esphome\components\sensor\filter.cpp.o
src/esphome/components/ld2420/ld2420.cpp: In member function 'virtual void esphome::ld2420::LD2420Component::dump_config()':
src/esphome/components/ld2420/ld2420.cpp:88:45: error: 'class esphome::ld2420::LD2420Component' has no member named 'operating_selector_'
   LOG_SELECT(TAG, "  Operating Mode", this->operating_selector_);
                                             ^~~~~~~~~~~~~~~~~~~
src/esphome/components/ld2420/ld2420.cpp:88:3: error: 'LOG_SELECT' was not declared in this scope
   LOG_SELECT(TAG, "  Operating Mode", this->operating_selector_);
   ^~~~~~~~~~
src/esphome/components/ld2420/ld2420.cpp:88:3: note: suggested alternative: 'LOG_SECRET'
   LOG_SELECT(TAG, "  Operating Mode", this->operating_selector_);
   ^~~~~~~~~~
   LOG_SECRET
src/esphome/components/ld2420/ld2420.cpp: In member function 'virtual void esphome::ld2420::LD2420Component::setup()':
src/esphome/components/ld2420/ld2420.cpp:140:11: error: 'class esphome::ld2420::LD2420Component' has no member named 'operating_selector_'
     this->operating_selector_->publish_state(OP_SIMPLE_MODE_STRING);
           ^~~~~~~~~~~~~~~~~~~
src/esphome/components/ld2420/ld2420.cpp:145:11: error: 'class esphome::ld2420::LD2420Component' has no member named 'operating_selector_'
     this->operating_selector_->publish_state(OP_NORMAL_MODE_STRING);
           ^~~~~~~~~~~~~~~~~~~
src/esphome/components/ld2420/ld2420.cpp: In member function 'void esphome::ld2420::LD2420Component::set_operating_mode(const string&)':
src/esphome/components/ld2420/ld2420.cpp:296:11: error: 'class esphome::ld2420::LD2420Component' has no member named 'operating_selector_'
     this->operating_selector_->publish_state(state);
           ^~~~~~~~~~~~~~~~~~~
src/esphome/components/ld2420/ld2420.cpp:315:11: error: 'class esphome::ld2420::LD2420Component' has no member named 'operating_selector_'
     this->operating_selector_->publish_state(OP_SIMPLE_MODE_STRING);
           ^~~~~~~~~~~~~~~~~~~
*** [.pioenvs\gpt-test\src\esphome\components\ld2420\ld2420.cpp.o] Error 1
============================================= [FAILED] Took 146.58 seconds =============================================
PS C:\esphome-test>
```

**Comment by swoboda1337** [comment]
If you add the select to the yaml it will build: https://esphome.io/components/sensor/ld2420.html#select
```
select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode
```
