### ISSUE TITLE
VBUS Resol

### ISSUE THREAD

**Issue by proasnet** [esphome/issues#6932]
### The problem

System log for core has error with Resol sensor

### Which version of ESPHome has the issue?

2025.3.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.2

### What platform are you using?

ESP8266

### YAML Config

```yaml
substitutions:
  name: "resol"
  friendly_name: "Resol Kotelna 0NP"
  device_description: "Monitor and control Resol Deltasol by VBUS"
    

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid_0
  password: !secret wifi_password

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
      ref: vbus
    components: [ vbus ]
    refresh: 1min

uart:
  id: resol
  rx_pin: GPIO3
  baud_rate: 9600

vbus:
  uart_id: resol

sensor:
  - platform: vbus
    model: deltasol_cs_plus
    temperature_1:
      name: Temperature 1
    temperature_2:
      name: Temperature 2
    temperature_3:
      name: Temperature 3
    heat_quantity:
      name: Heat Quantity
    pump_speed_1:
      name: Pump Speed 1

button:
    - platform: restart
      name: "ESP_Restart"
```

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.sensor
Zdroj: components/sensor/__init__.py:548
integrace: Senzor (dokumentace, problémy)
První výskyt: 18:26:39 (1 výskyty)
Naposledy logováno: 18:26:39

Entity sensor.heat_quantity (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
```
