### ISSUE TITLE
ESP camera with esp-ifd no aec, agc and auto white balance

### ISSUE THREAD

**Issue by Koejongen** [esphome/issues#6936]
### The problem

While programming a waveshare ESP32-S3 ETH and using arduino ide to program the example CameraWebServer the camera worked like it should. With auto exposure, auto white balance and auto gain ceiling working as it should.
Using ESPhome with the esp32 camera component and using the arduino frame work the camera doesnt work anymore, resulting in this error in the log: 
[22:30:13][E][esp32_camera:123]:   Setup Failed: ESP_FAIL
[22:30:13][E][component:082]:   Component esp32_camera is marked FAILED

But using ESPhome with the esp-idf framework the camera works but the auto exposure, auto white balance and auto gain ceiling doesnt work. because of that the camera produces a very dark image that does not automatically adjust to a changing environment. It also does not change when setting the aec, agc and wb manually 

### Which version of ESPHome has the issue?

2025.3.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.1

### What platform are you using?

ESP32

### Board

Waveshare ESP32-S3 ETH

### Component causing the issue

ESP32 Camera

### YAML Config

```yaml
esphome:
  name: poe-esp32
  friendly_name: ESP CAM
#  on_boot:
#    priority: 700
#    then:
#      - switch.turn_off: relay1
#      - lambda: |-        
#          delay(100);

psram:
  mode: octal
  speed: 80MHz

esp32:
  board: esp32-s3-devkitc-1
  framework:
    #type: esp-idf
    #sdkconfig_options:
    #  CONFIG_LWIP_MAX_SOCKETS: "16"
    type: esp-idf
    version: "5.3.1"
    platform_version: 6.9.0
    #type: arduino
  flash_size: 16MB

switch:
  - platform: gpio
    name: ${display_name} Relay1
    id: relay1
    pin: GPIO8
    restore_mode: ALWAYS_OFF
    setup_priority: 800
  - platform: ld2450
    ld2450_id: ld2450_radar
    bluetooth:
      name: "Bluetooth"
    multi_target:
      name: Multi Target Tracking"

esp32_camera:
  setup_priority: 200
  id: cam_1
  external_clock:
    pin: GPIO3
    frequency: 20MHz
  i2c_pins:
    sda: GPIO48
    scl: GPIO47
  data_pins: [GPIO41, GPIO45, GPIO46, GPIO42, GPIO40, GPIO38, GPIO15, GPIO18]
  vsync_pin: GPIO1
  href_pin: GPIO2
  pixel_clock_pin: GPIO39
  max_framerate: 20 fps   
  idle_framerate: 0.1 fps 
  resolution: SVGA
  jpeg_quality: 10
  frame_buffer_count: 1
  #power_down_pin: GPIO08  
  name: "My Cam"
  aec_mode: AUTO
  aec2: True
  #aec_mode: MANUAL
  #aec_value: 1200
  brightness: 2
  wb_mode: HOME
  agc_mode: AUTO
  vertical_flip: False
  horizontal_mirror: True

uart:
  id: uart_ld2450
  tx_pin: GPIO43
  rx_pin: GPIO44
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  id: ld2450_radar
  uart_id: uart_ld2450
  throttle: 1000ms

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "Timeout"
    zone_1:
      x1:
        name: Zone-1 X1
      y1:
        name: Zone-1 Y1
      x2:
        name: Zone-1 X2
      y2:
        name: Zone-1 Y2
    zone_2:
      x1:
        name: Zone-2 X1
      y1:
        name: Zone-2 Y1
      x2:
        name: Zone-2 X2
      y2:
        name: Zone-2 Y2
    zone_3:
      x1:
        name: Zone-3 X1
      y1:
        name: Zone-3 Y1
      x2:
        name: Zone-3 X2
      y2:
        name: Zone-3 Y2

select:
  - platform: ld2450
    ld2450_id: ld2450_radar
    baud_rate:
      name: "Baud rate"
    zone_type:
      name: "Zone Type"

button:
  - platform: ld2450
    ld2450_id: ld2450_radar
    factory_reset:
      name: "LD2450 Factory Reset"
      entity_category: "config"
    restart:
      name: "LD2450 Restart"
      entity_category: "config"

text_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    version:
      name: "LD2450 Firmware"
    mac_address:
      name: "LD2450 BT MAC"
    target_1:
      direction:
        name: "Target-1 Direction"
    target_2:
      direction:
        name: "Target-2 Direction"
    target_3:
      direction:
        name: "Target-3 Direction"

sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: Presence Target Count
  - platform: ld2450
    ld2450_id: ld2450_radar
    still_target_count:
      name: Still Target Count
  - platform: ld2450
    ld2450_id: ld2450_radar
    moving_target_count:
      name: Moving Target Count
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_1:
      x:
        name: Target-1 X
      y:
        name: Target-1 Y
      speed:
        name: Target-1 Speed
      angle:
        name: Target-1 Angle
      distance:
        name: Target-1 Distance
      resolution:
        name: Target-1 Resolution
    target_2:
      x:
        name: Target-2 X
      y:
        name: Target-2 Y
      speed:
        name: Target-2 Speed
      angle:
        name: Target-2 Angle
      distance:
        name: Target-2 Distance
      resolution:
        name: Target-2 Resolution
    target_3:
      x:
        name: Target-3 X
      y:
        name: Target-3 Y
      speed:
        name: Target-3 Speed
      angle:
        name: Target-3 Angle
      distance:
        name: Target-3 Distance
      resolution:
        name: Target-3 Resolution
    zone_1:
      target_count:
        name: Zone-1 All Target Count
      still_target_count:
        name: Zone-1 Still Target Count
      moving_target_count:
        name: Zone-1 Moving Target Count
    zone_2:
      target_count:
        name: Zone-2 All Target Count
      still_target_count:
        name: Zone-2 Still Target Count
      moving_target_count:
        name: Zone-2 Moving Target Count
    zone_3:
      target_count:
        name: Zone-3 All Target Count
      still_target_count:
        name: Zone-3 Still Target Count
      moving_target_count:
        name: Zone-3 Moving Target Count
  - platform: sen5x
    id: sen54
    pm_1_0:
      name: " PM <1µm Weight concentration"
      id: pm_1_0
      accuracy_decimals: 1
    pm_2_5:
      name: " PM <2.5µm Weight concentration"
      id: pm_2_5
      accuracy_decimals: 1
    pm_4_0:
      name: " PM <4µm Weight concentration"
      id: pm_4_0
      accuracy_decimals: 1
    pm_10_0:
      name: " PM <10µm Weight concentration"
      id: pm_10_0
      accuracy_decimals: 1
    temperature:
      name: "Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Humidity"
      accuracy_decimals: 0
    voc:
      name: "VOC"
      algorithm_tuning:
        index_offset: 100
        learning_time_offset_hours: 12
        learning_time_gain_hours: 12
        gating_max_duration_minutes: 180
        std_initial: 50
        gain_factor: 230
    temperature_compensation:
      offset: 0
      normalized_offset_slope: 0
      time_constant: 0
    nox:
      name: "NOx"
      algorithm_tuning:      
        index_offset: 100
        learning_time_offset_hours: 12
        learning_time_gain_hours: 12
        gating_max_duration_minutes: 180
        std_initial: 50
        gain_factor: 230 
    acceleration_mode: medium
    store_baseline: true
    i2c_id: bus_a
    address: 0x69
    update_interval: 10s


i2c:
  - id: bus_a
    sda: GPIO17
    scl: GPIO16
    scan: true


# Enable logging
logger:
  level: VERBOSE
  
api:
  encryption:
    key: "esy2KJzewoqObUbB3UqiekE92/rl4Kq5iG0UkwTaBK8="

ota:
  - platform: esphome
    password: "72ae6a612470a55b7efb13f04782cae0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Poe-Esp32 Fallback Hotspot"
    password: "gj5cdVhFOmQX"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt

```
