### ISSUE TITLE
PMSA003I still sometimes marked failed on boot with ESP32-C3

### ISSUE THREAD

**Issue by j9brown** [esphome/issues#6937]
### The problem

As has been previously reported, the PMSA003I sometimes takes long enough to initialize that the component is marked as failed after setup.  This problem was somewhat remedied by https://github.com/esphome/esphome/pull/7064 which retries a few times, but it still occurs.

Evidently the component needs to wait a bit longer.  Perhaps it would make sense to retry until a given amount of time has elapsed instead of retrying a specific number of times.

The logs show the component was marked as failed.  I don't have a snapshot of it because I remotely rebooted the board and the problem went away again.  It's intermittent.

### Which version of ESPHome has the issue?

2025.3.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.1

### What platform are you using?

ESP32

### Board

ESP32-C3

### Component causing the issue

pmsa003i

### YAML Config

```yaml
# MINUET INTEGRATED CONFIGURATION
#
# ESPHome device configuration for connecting Minuet to an existing WiFi network
# and integrated it with Home Assistant or some other front-end using the ESPHome API
# instead of the built-in standalone web interface.
#
# Please modify this configuration and secrets.yaml to suit your needs.
esphome:
  name: van-minuet
  friendly_name: Van Minuet

# Configure logging.
logger:
  level: DEBUG
  baud_rate: 921600

# Set up WiFi to connect to your network.
wifi:
  id: minuet_wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light
  fast_connect: true
  domain: .plucky.lan

# Enable over-the-air software updates.
ota:
  - platform: esphome
    password: !secret minuet_over_the_air_update_password

# Enable the ESPHome API to control the device and retrieve logs.
# Typically used by ESPHome Builder and Home Assistant.
api:
  encryption:
    key: !secret minuet_api_encryption_key

# Organize the configuration into packages for extensibility.
packages:
  # Include the core logic (required).
  <<: !include minuet/core.yaml

  # Include the controls for configuring wifi (optional).
  <<: !include minuet/wifi.yaml

  # Include the web interface (optional).
  # Commented out by default assuming you're integrating Minuet with another front-end.
  <<: !include minuet/web.yaml

  # Include configuration for an accessory plugged into the expansion port (optional).
  # Choose at most one of these packages to uncomment.
  <<: !include
    file: minuet/light-accessory/addressable-led-strip.yaml
    vars:
      name: 'Light'
      num_leds: 19
      chipset: WS2811
      rgb_order: RGB
      is_wrgb: true
      is_rgbw: false
  # <<: !include
  #   file: minuet/light-accessory/dimmable-light.yaml
  #   vars:
  #     name: 'Light'

  # Add more packages here to support for your custom features.

  # Air quality monitoring
  air_quality:
    sensor:
      - platform: bmp3xx_i2c
        i2c_id: minuet_i2c
        temperature:
          id: air_temperature_bmp390
          name: "Air Temperature (BMP390)"
          oversampling: 16x
        pressure:
          id: air_pressure
          name: "Air Pressure"
          oversampling: 16x
        iir_filter: 4x
        update_interval: 15s
      - platform: scd4x
        i2c_id: minuet_i2c
        co2:
          name: "Air CO2"
          id: air_co2
          accuracy_decimals: 0
          filters:
            - sliding_window_moving_average:
                window_size: 12
                send_every: 3
        temperature:
          name: "Air Temperature"
          id: air_temperature
          accuracy_decimals: 1
          filters:
            - sliding_window_moving_average:
                window_size: 12
                send_every: 3
        humidity:
          name: "Air Humidity"
          id: air_humidity
          accuracy_decimals: 1
          filters:
            - sliding_window_moving_average:
                window_size: 12
                send_every: 3
        ambient_pressure_compensation_source: air_pressure
        update_interval: 5s # SCD41 internally updates every 5 seconds
      - platform: pmsa003i
        i2c_id: minuet_i2c
        pm_1_0:
          name: "Air PM 1.0"
          id: air_pm_1_0
          accuracy_decimals: 1
          filters:
            - sliding_window_moving_average:
                window_size: 20
                send_every: 5
        pm_2_5:
          name: "Air PM 2.5"
          id: air_pm_2_5
          accuracy_decimals: 1
          filters:
            - sliding_window_moving_average:
                window_size: 20
                send_every: 5
        pm_10_0:
          name: "Air PM 10.0"
          id: pm_10
          accuracy_decimals: 1
          filters:
            - sliding_window_moving_average:
                window_size: 20
                send_every: 5
        # pmc_0_3:
        #   name: "Air PMC >0.3µm"
        #   accuracy_decimals: 1
        #   filters:
        #     - sliding_window_moving_average:
        #         window_size: 20
        #         send_every: 20
        # pmc_0_5:
        #   name: "Air PMC >0.5µm"
        #   accuracy_decimals: 1
        #   filters:
        #     - sliding_window_moving_average:
        #         window_size: 20
        #         send_every: 20
        # pmc_1_0:
        #   name: "Air PMC >1µm"
        #   accuracy_decimals: 1
        #   filters:
        #     - sliding_window_moving_average:
        #         window_size: 20
        #         send_every: 20
        # pmc_2_5:
        #   name: "Air PMC >2.5µm"
        #   accuracy_decimals: 1
        #   filters:
        #     - sliding_window_moving_average:
        #         window_size: 20
        #         send_every: 20
        # pmc_5_0:
        #   name: "Air PMC >5µm"
        #   accuracy_decimals: 1
        #   filters:
        #     - sliding_window_moving_average:
        #         window_size: 20
        #         send_every: 20
        # pmc_10_0:
        #   name: "Air PMC >10µm"
        #   accuracy_decimals: 1
        #   filters:
        #     - sliding_window_moving_average:
        #         window_size: 20
        #         send_every: 20
        update_interval: 3s # PMSA003I internally updates every 2.3 s
```

### Anything in the logs that might be useful for us?

```txt
```
