### ISSUE TITLE
MR60BHA2: no Distance to detection object being reported using latest yaml

### ISSUE THREAD

**Issue by wigledav** [esphome/issues#6938]
### The problem

Seeed Studio MR60BHA2 is operating and delivering 5 parameters successfully into Home Assistant (presence, HR, Respiratory, Illuminance, and target Number) but Distance to detection object remains as 'unknown'.
I have tried with both standard Seeed code and also this yaml example updated 

(https://github.com/limengdu/MR60BHA2_ESPHome_external_components/tree/main/example)
/mr60bha2.yam

### Which version of ESPHome has the issue?

ESP Home Device Builder 2025.3.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core: 2025.3.4 / Super: 2025.04.0 / OS: 15.0 / Front end: 20250306.0

### What platform are you using?

ESP32-IDF

### Board

Seeed MR60BHA2 with ESP32C6

### Component causing the issue

sensor.distance

### YAML Config

```yaml
# template from https://github.com/limengdu/MR60BHA2_ESPHome_external_components

substitutions:
  name: "seeedstudio-mr60bha2-kit"
  friendly_name: "Seeed Studio MR60BHA2 Kit"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "seeedstudio.mr60bha2_kit"
    version: "3.5"
  platformio_options:
    board_upload.maximum_size: 4194304
  min_version: "2024.3.2" # Fix logger compile error on ESP32-C6 esphome#6323

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB # upload.flash_size
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/limengdu/MR60BHA2_ESPHome_external_components
      ref: main
    components: [ seeed_mr60bha2 ]
    refresh: 0s

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Mr06Bha2-Uart-Mode"
    password: ""

captive_portal:

# For XIAO ESP32C6 Onboard LED
light:
  - platform: status_led
    name: "Switch state"
    pin: GPIO15

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 17
  tx_pin: 16
  parity: NONE
  stop_bits: 1

seeed_mr60bha2:
  id: my_seeed_mr60bha2

binary_sensor:
  - platform: seeed_mr60bha2
    has_target:
      name: "Person Information"

sensor:
  - platform: bh1750
    name: "Seeed MR60BHA2 Illuminance"
    address: 0x23
    update_interval: 1s
  - platform: seeed_mr60bha2
    breath_rate:
      name: "Real-time respiratory rate"
    heart_rate:
      name: "Real-time heart rate"
    distance:
      name: "Distance to detection object"
    num_targets:
      name: "Target Number"
```

### Anything in the logs that might be useful for us?

```txt
No errors during compilation or upload
```

### Additional information

Appreciate your support and if anyone else has the issue. Thanks !
