### ISSUE TITLE
[lvgl] ESPHome 2025.4.0 - negative values for padding no longer possible?

### ISSUE THREAD

**Issue by derMicro** [esphome/issues#6945]
### The problem

Since the slider button in round is pretty ugly and I'm trying to get close to the HomeAssistant style in my LVGL theme, I configured the slider button with negative pad_left and pad_right values so that the button is a narrow bar.

Since the release of LVGL in Esphome this has worked, even the official LVGL (8.4) documentation does not state that the padding values must be greater than or equal to 0.
In various forums, it has also been repeatedly pointed out in questions about the design that individual elements can be made narrower with negative paddings.
Example: https://forum.lvgl.io/t/hot-to-change-the-size-of-the-knob-on-a-slider/14974
Why is this no longer possible with ESPHome 2025.4.0?

ESP-IDF 5.3.1
Platform version 6.9.0

I have also tried it with ESP-IDF 5.4.1 and Pioarduino 54.03.20.

```
lvgl:
  style_definitions:
    - id: slider_bathlightknob
      bg_color: 0xFFFFFF
      bg_opa: "100%"
      radius: 4
      pad_left: -13
      pad_right: -13
```

![Image](https://github.com/user-attachments/assets/36b0c3cd-4d55-4c32-afe4-0caed576b391)

### Which version of ESPHome has the issue?

2025.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.2

### What platform are you using?

ESP32-IDF

### Board

esp32-s3-devkitc-1 (Sensecap Indicator)

### Component causing the issue

lvgl

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by bennydiamond** [comment]
Came here for this.

Same deal with new version 2025.4.0

```
- slider:
      id: ${id_lv_slid_kelvin}
      bg_opa: COVER
      bg_color: color_orange
      bg_grad_color: color_white
      bg_grad_dir: HOR
      border_opa: 50%
      border_width: 1
      border_color: color_dark_gray
      shadow_opa: TRANSP
      pad_all: 0
      grid_cell_column_pos: 0
      grid_cell_row_pos: 2
      grid_cell_x_align: STRETCH
      grid_cell_y_align: STRETCH
      grid_cell_column_span: 1
      grid_cell_row_span: 1
      radius: 20
      min_value: ${value_min_kelvin}
      max_value: ${value_max_kelvin}
      indicator:
        opa: TRANSP
      knob:
        bg_opa: COVER
        radius: 3
        **pad_left: -30
        pad_right: -30**
        border_opa: TRANSP
        border_width: 0
        shadow_opa: COVER
        shadow_color: color_dark_gray
        shadow_width: 20
      on_release:
          - homeassistant.action:
              action: light.turn_on
              data:
                entity_id: ${light_ha_entity_id}
                # Cast return value to int because HA doesn't like float inputs on this field.
                color_temp_kelvin: !lambda return int(x);
```

will throw error

```
value must be at least 0.
pad_left: -30

value must be at least 0.
pad_right: -30
```

With version prior 2025.4.0, slider's knob style was just perfectly scaled for my needs.

![Image](https://github.com/user-attachments/assets/5ea4f089-fd66-4462-96d7-e5d723c57963)

Now I cannot get to thin it to the appropriate size and retain rounded corners and shadow.

with 2025.4.0 that prevents negative padding:

![Image](https://github.com/user-attachments/assets/efb559a0-5892-4c67-afcd-bf5237f1773f)
