### ISSUE TITLE
Config validation does not ensure all names are unique per platform/domain

### ISSUE THREAD

**Issue by bdraco** [esphome/issues#6953]
### The problem

Consider the following YAML
```
binary_sensor:
  - platform: template
    name: ""
    device_class: gas
    lambda: 'return true;'
  - platform: template
    name: ""
    device_class: lock
    lambda: 'return true;'
  - platform: template
    name: "xyz"
    device_class: garage_door
    lambda: 'return true;'
  - platform: template
    name: "xyz"
    device_class: lock
    lambda: 'return true;'    
```

The additional `binary_sensor` named `""` and `"xyz"` should be an error as its going to generate the same object_id, and this produce a unique id conflict
```
2025-04-20 09:19:05.870 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform esphome does not generate unique IDs. ID 24:4C:AB:06:49:9C-binary_sensor-xyz is already used by binary_sensor.poolhouse81proxy_xyz - ignoring binary_sensor.poolhouse81proxy_xyz
2025-04-20 09:19:05.871 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform esphome does not generate unique IDs. ID 24:4C:AB:06:49:9C-binary_sensor-81_pool_house_proxy is already used by binary_sensor.poolhouse81proxy - ignoring binary_sensor.poolhouse81proxy
```

### Which version of ESPHome has the issue?

dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```
