### ISSUE TITLE
Support of LYWSD03MMC Xiaomi sensor

### ISSUE THREAD

**Issue by Antonytm** [esphome/issues#6954]
### The problem

The documentation related to the LYWSD03MMC sensor is wrong for recent sensor revisions. https://esphome.io/components/sensor/xiaomi_ble.html

1. Xiaomi stock firmware bindkey doesn't work. 
2. Xiaomi added protection, you can't connect the device to flash with [PVVX MiThermometer](https://github.com/pvvx/ATC_MiThermometer) custom firmware
3. Only the third option works, but flashing is much harder.

It is not only for me, check reports on GitHub for suggested firmware repos, check this video:
https://www.youtube.com/watch?v=NfZHh6wmTp8

### Which version of ESPHome has the issue?

2025.4.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2025.3.0

### What platform are you using?

ESP32

### Board

ESP32 WROOM-32

### Component causing the issue

LYWSD03MMC

### YAML Config

```yaml
sensor:
  - platform: xiaomi_lywsd03mmc
    mac_address: XX:XX:XX:XX:XX:XX
    bindkey: "eef418daf699a0c188f3bfd17e4565d9"
    temperature:
      name: "LYWSD03MMC Temperature"
    humidity:
      name: "LYWSD03MMC Humidity"
    battery_level:
      name: "LYWSD03MMC Battery Level"
```

### Anything in the logs that might be useful for us?

```txt

```
