### ISSUE TITLE
Can't read 4 byte values using vbus component

### ISSUE THREAD

**Issue by H1b3rn4t3** [esphome/issues#6956]
### The problem

Just tried to read all possible sensor values of my Citrin (Resol) thermal solar controller using the ESPHome vBus component. As my device (Citrin CS1.3, also known as Resol Deltasol CS4) isn't supported, I have to use the custom sensor option and read the values using the lambda function.

The documentation (https://danielwippermann.github.io/resol-vbus/#/vsf/bytes/00_0010_1122_10_0100) shows "Status mask" and "Heat quantity" as 4 byte value.
It works just fine for all values stored in 1 byte or 2 bytes. But these are values stored in 4 bytes and I don't get it to work reading them.

It looks like the supported (and just smaller version of the CS4) Resol Deltasol CS2 just doesn't read these values, even they're present in the packet definition. So sadly I had no example to look at.

As you can see in my YAML config, I've tried a bit around with the bit shifting within the lambda section to read the 4 byte values. Shifting 8 bit within the 2 byte values is no problem, but shifting 32 bit within the 4 byte ones doesn't work. But these efforts result in the attached error message. I didn't fill in the full config, as I'm still building it up, but can share if really needed.
Important note: Without "solar_status_mask" and "solar_flow_rate", everything works fine. My config is up and running, but playing around with these 4 byte values breaks everything.

Maybe I'm doing something wrong with the lambda function. But maybe it's an issue with the component, as all examples and the supported CS2 device only show 2 byte readings, e. g. the temperature sensors.

It would be nice if someone could guide me or point out, if there's really an issue with the component.

Thank you so much :)

### Which version of ESPHome has the issue?

2025.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.3

### What platform are you using?

ESP32-IDF

### Component causing the issue

vbus

### YAML Config

```yaml
- id: solar_sw_version
        name: Citrin Controller Firmware Version
        lambda: return ((x[33] << 8) + x[32]) * 0.01f;
      - id: solar_unittype
        name: Citrin Controller UnitType
        lambda: return (x[16] << 8) * 1.0f;
      - id: solar_system
        name: Citrin Controller System
        lambda: return (x[17] << 8) * 1.0f;
      - id: solar_status_mask
        name: Solar Status Mask
        lambda: return ((x[27] << 32) + [24]) * 1677216f;
#      - id: solar_flow_rate
#        name: Solar Flow Rate
#        state_class: measurement
#        unit_of_measurement: "Wh"
#        lambda: return ((x[31] << 32) + [28]) * 1677216f;
```

### Anything in the logs that might be useful for us?

```txt
Reading CMake configuration...
No dependencies
Compiling .pioenvs/resol-vbus/src/main.cpp.o
/config/esphome/esphome-web-2f1df0.yaml: In lambda function:
/config/esphome/esphome-web-2f1df0.yaml:112:22: warning: left shift count >= width of type [-Wshift-count-overflow]
  112 | #      - id: solar_flow_rate
/config/esphome/esphome-web-2f1df0.yaml:112:32: error: expected identifier before numeric constant
  112 | #      - id: solar_flow_rate
      |                                ^ 
/config/esphome/esphome-web-2f1df0.yaml: In lambda function:
/config/esphome/esphome-web-2f1df0.yaml:112:35: error: expected '{' before ')' token
  112 | #      - id: solar_flow_rate
      |                                   ^
/config/esphome/esphome-web-2f1df0.yaml: In lambda function:
/config/esphome/esphome-web-2f1df0.yaml:112:29: error: no match for 'operator+' (operand types are 'int' and 'setup()::<lambda(std::vector<unsigned char>)>::<lambda()>')
  112 | #      - id: solar_flow_rate
      |               ~~~~~~~~~~~~~ ^     
      |                      |        |
      |                      int      setup()::<lambda(std::vector<unsigned char>)>::<lambda()>
In file included from src/esphome/core/entity_base.h:5,
                 from src/esphome/components/binary_sensor/binary_sensor.h:4,
                 from src/esphome/core/controller.h:5,
                 from src/esphome/components/api/api_server.h:11,
                 from src/esphome/components/api/api_connection.h:8,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/string_ref.h:118:20: note: candidate: 'std::string esphome::operator+(const char*, const StringRef&)'
  118 | inline std::string operator+(const char *lhs, const StringRef &rhs) {
      |                    ^~~~~~~~
src/esphome/core/string_ref.h:118:64: note:   no known conversion for argument 2 from 'setup()::<lambda(std::vector<unsigned char>)>::<lambda()>' to 'const esphome::StringRef&'
  118 | inline std::string operator+(const char *lhs, const StringRef &rhs) {
      |                                               ~~~~~~~~~~~~~~~~~^~~
src/esphome/core/string_ref.h:124:20: note: candidate: 'std::string esphome::operator+(const StringRef&, const char*)'
  124 | inline std::string operator+(const StringRef &lhs, const char *rhs) {
      |                    ^~~~~~~~
src/esphome/core/string_ref.h:124:47: note:   no known conversion for argument 1 from 'int' to 'const esphome::StringRef&'
  124 | inline std::string operator+(const StringRef &lhs, const char *rhs) {
      |                              ~~~~~~~~~~~~~~~~~^~~
/config/esphome/esphome-web-2f1df0.yaml:112:39: error: unable to find numeric literal operator 'operator""f'
  112 | #      - id: solar_flow_rate
      |                                       ^       
*** [.pioenvs/resol-vbus/src/main.cpp.o] Error 1
```
