### ISSUE TITLE
ESPHome 2025.4.0 - External_Components not loading/refreshing

### ISSUE THREAD

**Issue by Roving-Ronin** [esphome/issues#6960]
### The problem

Trying to update a couple of different sites, each with their own HA Addon 'ESPHome' and finding that they are all having issues when trying to call external_components (at least on Github). Repeatedly trying to validate/install and notice that they are showing old versions of the code/yaml from Github, as they are not updating / using cached version off local esphome instanace.

### Which version of ESPHome has the issue?

2025.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.3

### What platform are you using?

ESP32

### Board

Assorted ESP32 models

### Component causing the issue

external_components

### YAML Config

```yaml
#########################################################################
#
# Environmental monitoring using ESP32-S3 chipset and BME280 sensor(s)
# for temperature, humidity, pressure & dew point.
#

##########################################################################
# VERSION UPATES:
#
# v1.2.0 - Upate to Dentra v2 based water_statistics with publish yesterday = 0
# v1.3.0 - Updated Water and Gas (m3 and MJ) components, so that values remain between reflashing
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
  # Default name  
  name: "utilities-monitor"
  # Default friendly name 
  friendly_name: "Utilities Monitor"
  # Description as appears in ESPHome & top of webserver page
  device_description: "Gas, Water & Environmental Monitor (Temp./Humidity/Pressure)"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Front Gate, Decontamination, Shed XYZ etc  
  location: "Garage"
  # Location geographical height, in meters. Used for calculations in sensors such as BME280/BME680 and Water Tank sensors. Goulburn (673)
  location_height: "673"
  # Project Name
  project_name: "DIY.Utilities Monitor"
  # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "1.5.2"
  # The phase in the locations power supply, upon which this device is utilsed. 1p = A. 3p = A, B or C.  (GPO 1 = Phase A, GPO 2 = Phase B, GPO 3 = Phase C).
  # Used to populate a Text Sensor with this information, that may be used to loadshed in future, or trace outages to electrical faults.
  power_circuit: "TBA"
  # Define logging level: NONE, ERROR, WARN, INFO, DEBUG (Default), VERBOSE, VERY_VERBOSE.
  # Use 'INFO' as at DEBUG the energy/water/gas statistics "Internal" sensors appear in the logs
  log_level: "INFO"
  
  # BME 280 / BME680 Sensor
  # Location of BME280/680 Sensor #1. Used to prefix sensor if there are two. Leave empty if only 1. Add a " - " to the end of each entry if used.
  bme_sensor1_location: ""
  # Location of BME280/680 Sensor #2. Used to prefix sensor if there are two. Leave empty if only 1. Add a " - " to the end of each entry if used.
  bme_sensor2_location: ""
  # Calibrate the outpute of the temperature sensor(s).
  temperature_1_offset: "0.0"
  temperature_2_offset: "0.0"
  # Calibrate the outpute of the pressure sensor(s).
  pressure_1_offset: "0.0"
  pressure_2_offset: "0.0"
  # Calibrate the outpute of the humidity sensor(s).
  humidity_1_offset: "0.0"
  humidity_2_offset: "0.0"

  # PIN usage upon the JAComms S3-Core Board
  gpio_gas_pin: "10"
  gpio_water_pin: "11"

########################## End of Substitutions #########################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://roving-ronin/myhomeassistant/esphome/utilities-monitor.yaml@main
  import_full_config: false

packages:
  base-config:             !include common/base-configuration.yaml              # Base configuration applied to all ESPHome devices
  network-config:          !include common/network-ethernet-w5500.yaml          # Configure Ethernet port on this system board
  bme280a-sensors:         !include sensors/bme280-bus-a.yaml                   # Temperature, Humidity, Pressure sensor probe
  water-tank-sensors:      !include sensors/cylinder-liquid-pressure-tl136.yaml # Pressure sensor to monitor water tank  
#  ds18b20-sensors:       !include sensors/ds18b20-1wire.yaml
  consumption-gas:         !include sensors/utilities-gas.yaml                    # Sensors to monitor and calculate gas usage
  consumption-town-water:  !include sensors/utilities-town-water.yaml             # Sensors to monitor and calculate gas usage
#  consumption-tank-water:  !include sensors/utilities-tank-water.yaml             # Sensors to monitor and calculate gas usage
  esp32-system-board:      !include boards/jacomms-esp32-s3-core.yaml           # Model of ESP Board being used. This is Kincony S3 Core with JAComms HAT.

#########################################################################
#
# Custom Components to be utilised - For Gas and Water Statistics
#

external_components:
#  - source: github://roving-ronin/myhomeassistant/components@statistics-partial-times
#    refresh: 0s
  - source:
      type: git
      url: https://github.com/roving-ronin/myhomeassistant/
      ref: main
    refresh: 0s
    components: [ gas_statistics, gas_statistics_mj, water_statistics, usage_tracker ]

#########################################################################
#
# Web_server v3 Sort Groups - These substitutes are applied to overwrite the default ones supplied by the 
# sensor specific template file, in this case the /sensors/hc-sr04-ultrasonic.yaml file.
#

web_server:
  sorting_groups:
      # This sort group is used by both the Water and Gas Meter senors (flow rate / pulse counter), so must be in at this level, not in the water vs gas sensor yaml
    - id: group_utility_meter_sensors
      name: "Gas & Water Meter Sensors"
      sorting_weight: -44

#########################################################################
```

### Anything in the logs that might be useful for us?

```txt
Example of the external_components being called:

external_components:
  - source:
      type: git
      url: https://github.com/roving-ronin/myhomeassistant/
      ref: main
    refresh: 0s
```

### Additional information

Issue temporarily resolved by rolling back ESPHome to 2025.3.3
