### ISSUE TITLE
Home Assistant - M5STACK Timer Cam

### ISSUE THREAD

**Issue by benoitdevries** [esphome/issues#6962]
### The problem

My camera was working very fine, even if I was not able to update it since ... 2023.
I tried today to update it, but I was asked to remove the "Platform" from the code below. What I did.
It failed, asking to add the "Platform" back.
So I removed the device from Home Assistant, and used the wizard to install a new one.
It gave me a "new standard" code and I personalised it.
It fails asking me to remove the "Platform"

Guess who starts to drive crazy ??

ORIGINAL CODE : 
esphome:
  name: camera-m5
  platform: ESP32
  board: m5stack-timer-cam

logger:
  level: VERBOSE

api:

ota:
  platform: esphome
  password: "oupsie"

wifi:
  ssid: "oupsie"
  password: "oupsie"

  ap:
    ssid: "Camera-M5 Fallback Hotspot"
    password: "oupsie"

esp32_camera:
  name: "CameraSalon"
  board: m5stack-timer-cam
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO32, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  resolution: UXGA
  jpeg_quality: 10
  max_framerate: 8 fps
  idle_framerate: 0 fps
  vertical_flip: False
  horizontal_mirror: True

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

binary_sensor:
    platform: gpio
    pin: GPIO37
    name: "Camera Boutton"

light:
    platform: binary
    name: "Camera LED"
    output: camera_led

output:
    id: camera_led
    platform: gpio
    pin: GPIO2

switch:
    platform: gpio
    pin: GPIO33
    name: "Camera Batterie On"

sensor:
  platform: adc
  pin: GPIO38
  name: "Camera Voltage Batterie"
  filters:
    multiply: 3.3

### Which version of ESPHome has the issue?

ESPHOME 2025.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.3

### What platform are you using?

ESP32

### Board

M5STACK Timer Camera X

### YAML Config

```yaml
esphome:
  name: camera-m5
  friendly_name: camera-m5

esp32_camera:
  name: "CameraSalon"
  board: m5stack-timer-cam
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO32, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  resolution: UXGA
  jpeg_quality: 10
  max_framerate: 8 fps
  idle_framerate: 0 fps
  vertical_flip: False
  horizontal_mirror: True

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

binary_sensor:
    platform: gpio
    pin: GPIO37
    name: "Camera Boutton"

light:
    platform: binary
    name: "Camera LED"
    output: camera_led

output:
    id: camera_led
    platform: gpio
    pin: GPIO2

switch:
    platform: gpio
    pin: GPIO33
    name: "Camera Batterie On"

sensor:
  platform: adc
  pin: GPIO38
  name: "Camera Voltage Batterie"
  filters:
    multiply: 3.3
# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "oupsie"

ota:
  - platform: esphome
    password: "oupsie"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Camera-M5 Fallback Hotspot"
    password: "oupsie"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.4.0
INFO Reading configuration /config/esphome/camera-m5.yaml...
Failed config

esphome: [source /config/esphome/camera-m5.yaml:2]
  name: camera-m5
  
  Please remove the `platform` key from the [esphome] block and use the correct platform component. This style of configuration has now been removed.
  platform: ESP32
  board: m5stack-timer-cam
----------------------------------------------------------------
And when Platform is removed ... :

INFO ESPHome 2025.4.0
INFO Reading configuration /config/esphome/camera-m5.yaml...
Failed config

esphome: [source /config/esphome/camera-m5.yaml:2]
  
  Platform missing. You must include one of the available platform keys: bk72xx, host, libretiny, esp32, esp8266, rtl87xx, rp2040.
  name: camera-m5
  friendly_name: camera-m5
```

**Comment by randybb** [comment]
The old syntax was removed in [2025.2](https://esphome.io/changelog/2025.2.0#removal-of-old-style-platform-configuration) as it was replaced 3 years ago with the new one :D

So replace this in your original config:
```yaml
esphome:
  name: camera-m5
  platform: ESP32
  board: m5stack-timer-cam
```
with this (arduino framework is by default, but it is nice to have it specified so it is clear what it is using):
```yaml
esphome:
  name: camera-m5

esp32:
  board: m5stack-timer-cam
  framework:
    type: arduino
```
