### ISSUE TITLE
ESP8266 with MQTT and DeepSleep stopped working after the 2025.4.0 update

### ISSUE THREAD

**Issue by InspectorTrinket** [esphome/issues#6963]
### The problem

After updating to version 2025.4.0, my device, which is a battery powered ESP8266 +BME280 weather station stopped working properly. 

The communication is done with MQTT and the device is programmed to wake up every 15 minutes, do the measurements, post the MQTT messages and go back to sleep (as quick as possible). All sensor readings are interlocked and the sleep funcion only kicks in when all sensors are read.

After the update, the device goes to sleep regarless of the sensor states. So, it wakes up, reads nothing and goes back to sleep.

Reverting back to 2025.3.3, recompling the code and updating the firmware on the device solves the issue.

### Which version of ESPHome has the issue?

2025.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.3

### What platform are you using?

ESP8266

### Board

esp07s

### Component causing the issue

MQTT

### YAML Config

```yaml
substitutions:
  name: "estacao-meteorologica-externa"
  node_sleep_duration: "15min"
  node_run_duration_timeout: "15s" # The node enters sleep automatically after the tasks are done. The timeout is to prevent a never sleeping state when WiFi/MQTT is unavailable
  measurement_accuracy_decimals: "1"

esphome:
  name: ${name}
  friendly_name: Estação Meteorológica Externa
  on_boot:
    - priority: 300 # Just before WiFi initialization
      then:
      # Disable the WiFi persistence. The ESP8266 will not load and save WiFi settings in the flash memory to save time.
        lambda: |-
          WiFi.persistent(false);
          WiFi.setPhyMode(WIFI_PHY_MODE_11N);
    - priority: 500 # Force deep sleep if WIFI/MQTT is down
      then:
      - delay: ${node_run_duration_timeout}
      - if:
          condition:
            binary_sensor.is_off: node_status
          then:
            - deep_sleep.enter: deep_sleep_handler
esp8266:
  board: esp07s

logger:

# Allow Over-The-Air updates
ota:
- platform: esphome
  password: !secret ota_password

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true # If enabled, directly connects to WiFi network without doing a full scan first. This is required for hidden networks.
  # Manual IP to enable faster connection times than with DHCP. It also enables the use of 802.11n Wifi operation mode with ASUS AX Routers (see on_boot section)
  manual_ip:
    static_ip: 192.168.52.140
    gateway: 192.168.52.1
    subnet: 255.255.255.0
  # use_address: 192.168.5X.XXX # Set "use_address" to point to the old address when changing the device name or address.
  # Adding AP and Fallback hotspot makes no sense, because the node has a timeout to enter deep sleep.

# MQTT Configuration
mqtt:
  broker: !secret mqtt_server_IP
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery_unique_id_generator: mac
  birth_message: # Leave blank to turn off availability reporting
  will_message: # Leave blank to turn off availability reporting
  on_message:
    - topic: admin/disable_sleep
      payload: 'ON'
      then:
        - binary_sensor.template.publish:
            id: sleep_enable
            state: OFF
        - deep_sleep.prevent: deep_sleep_handler
    - topic: admin/disable_sleep
      payload: 'OFF'
      then:
        - binary_sensor.template.publish:
            id: sleep_enable
            state: ON
        - deep_sleep.allow: deep_sleep_handler

# Deep Sleep Parameters:
deep_sleep:
  id: deep_sleep_handler
  run_duration: ${node_run_duration_timeout}
  sleep_duration: ${node_sleep_duration}

# BME280 pin configuration
i2c:
  sda: 4
  scl: 5
  scan: false

sensor:
# BME280 sensor configuration
  - platform: bme280_i2c # CSB to Vcc and SDO to GND
    temperature:
      name: "Temperatura"
      id: bme280_temperature
      oversampling: 1x # For weather monitoring, the recommended oversampling is 1x according to BME280 Datasheet
      accuracy_decimals: ${measurement_accuracy_decimals} # Max = 2: Resolution of 0.01C according to BME280 Datasheet
      on_value:
        then:
          binary_sensor.template.publish:
            id: temperature_update
            state: ON
    pressure:
      name: "Pressão Atmosférica"
      id: bme280_pressure
      oversampling: 1x # For weather monitoring, the recommended oversampling is 1x according to BME280 Datasheet
      accuracy_decimals: ${measurement_accuracy_decimals} # Max = 2: Resolution of 0.18Pa according to BME280 Datasheet
      on_value:
        then:
          binary_sensor.template.publish:
            id: pressure_update
            state: ON    
    humidity:
      name: "Umidade Relativa"
      id: bme280_humidity
      oversampling: 1x # For weather monitoring, the recommended oversampling is 1x according to BME280 Datasheet
      accuracy_decimals: ${measurement_accuracy_decimals} # Max = 3: Resolution of 0.008% according to BME280 Datasheet
      on_value:
        then:
          binary_sensor.template.publish:
            id: humidity_update
            state: ON
    update_interval: ${node_sleep_duration} # Only usefull when the node is not allowed to sleep to keep the same interval between samples when sleep is enabled
    address: 0x76
# Vcc Voltage
  - platform: adc
    pin: A0
    name: "Vcc"
    id: vcc_voltage
    filters:
      - multiply: 4.2215 # Manually adjusted value (Measured = 4.32859)
    accuracy_decimals: 4 # Resolution of ESP8266 ADC (10 bit - 0 to 1023, measuring 1 V reference, 1/1024 = 0.00098)
    update_interval: ${node_sleep_duration} # Only usefull when the node is not allowed to sleep to keep the same interval between samples when sleep is enabled
    on_value:
      then:
        binary_sensor.template.publish:
          id: vcc_update
          state: ON
# Battery monitor
  - platform: copy
    source_id: vcc_voltage
    name: "Bateria"
    id: battery
    device_class: battery
    unit_of_measurement: "%"
    accuracy_decimals: 0
    filters:
      # Map Battery level from Vcc
      - calibrate_linear:
          - 3.3 -> 0 # Manually adjusted value
          - 4.2215 -> 100 # Manually adjusted value (Measured = 4.32859)
      #Handle/cap boundaries
      - lambda: |
          if (x < 0) return 0; 
          else if (x > 100) return 100;
          else return (x);
    on_value:
      then:
        binary_sensor.template.publish:
          id: battery_update
          state: ON
# Wifi Signal Sensor
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: ${node_sleep_duration} # Only usefull when the node is not allowed to sleep to keep the same interval between samples when sleep is enabled
    on_value:
      then:
        binary_sensor.template.publish:
          id: wifi_update
          state: ON

binary_sensor:
# Node Status
  - platform: status
    name: "Status"
    id: node_status
# Data update sensors and Sleep message publish interlock
# Internal components will not be exposed to the frontend (like Home Assistant) if only the "id" (and no "name") is specifyied, implicitly setting "internal" to "true".
  # BME 280 Template Sensor
  - platform: template
    id: temperature_update
  - platform: template
    id: pressure_update
  - platform: template
    id: humidity_update
  # Vcc Template Sensor
  - platform: template
    id: vcc_update
  # Battery Template Sensor
  - platform: template
    id: battery_update
  # Wifi Template Sensor
  - platform: template
    id: wifi_update
  # Sleep Enable Sensor
  - platform: template
    id: sleep_enable
  # All updates
  - platform: template
    id: full_update
    lambda: |-
      return
      id(temperature_update).state &&
      id(pressure_update).state &&
      id(humidity_update).state &&
      id(vcc_update).state &&
      id(battery_update).state &&
      id(wifi_update).state &&
      id(sleep_enable).state;
    on_press:
      then:
        deep_sleep.enter: deep_sleep_handler
```

### Anything in the logs that might be useful for us?

```txt

```
