### ISSUE TITLE
Home assitant doesnt recognize ESPHome relais/switch

### ISSUE THREAD

**Issue by Roshaan21** [esphome/issues#697]
![Screenshot (10)](https://user-images.githubusercontent.com/29692404/65772517-a9861400-e13a-11e9-9f70-aa2d456592cf.png)
![Screenshot (6)](https://user-images.githubusercontent.com/29692404/65772528-b0148b80-e13a-11e9-9073-7f08db946c18.png)

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io 0.99.3

**ESP (ESP32/ESP8266, Board/Sonoff):**
NodeMcuv3

**Affected component:**
https://esphome.io/components/switch/gpio.html

**Description of problem:**

So ive been trying to add switches to my home assistant via the ESPHome add on in Home assistant. 
Im using 2 NodeMcus with an ESP8266 chip WIFI chip on them. I managed them to work properly but after a while Home assitant didnt recoginze the relais anymore that I used to turn on and off the lights with, seen in the picture, while all the sensor data was still going through.

I tried to reboot everything a few times and even used some old snaoshots. But nothing works.
It keeps telling me that it vant find any relais/switches eventhough they are in the .yaml code.

I also added some exaple code but that didnt work either.

If you need anything else, pl let me know.

Also Im sorry for any grammar mistakes.
**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: poster_licht
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "My kids took karen"
  password: "Some Random numbers and signs"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "word"

ota:
  password: "Pass"

# Example configuration entry
switch:
  - platform: gpio
    pin: D5
    name: "Living Room Dehumidifier"
  - platform: gpio
    pin: D0
    inverted: yes
    restore_mode: RESTORE_DEFAULT_ON 
    name: "Weltenlicht"
  - platform: gpio
    pin: D1
    inverted: yes
    name: "ight of Takenking"
  - platform: gpio
    pin: D2
    name: "light of Destiny 2"

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```[15:29:41][C][wifi:372]: WiFi:
[15:29:41][C][wifi:254]:   SSID: [redacted]
[15:29:41][C][wifi:255]:   IP Address: __________________
[15:29:41][C][wifi:257]:   BSSID: [redacted]
[15:29:41][C][wifi:258]:   Hostname: 'poster_licht'
[15:29:41][C][wifi:262]:   Signal strength: -64 dB ▂▄▆█
[15:29:41][C][wifi:263]:   Channel: 6
[15:29:41][C][wifi:264]:   Subnet: _________________
[15:29:41][C][wifi:265]:   Gateway: __________________
[15:29:41][C][wifi:266]:   DNS1: _____________________
[15:29:41][C][wifi:267]:   DNS2: 0______________
[15:29:41][C][switch.gpio:042]: GPIO Switch 'Living Room Dehumidifier'
[15:29:41][C][switch.gpio:043]:   Pin: GPIO14 (Mode: OUTPUT)
[15:29:41][C][switch.gpio:059]:   Restore Mode: Restore (Defaults to OFF)
[15:29:41][C][switch.gpio:042]: GPIO Switch 'Weltenlicht'
[15:29:41][C][switch.gpio:042]:   Inverted: YES
[15:29:41][C][switch.gpio:043]:   Pin: GPIO16 (Mode: OUTPUT)
[15:29:41][C][switch.gpio:059]:   Restore Mode: Restore (Defaults to ON)
[15:29:41][C][switch.gpio:042]: GPIO Switch 'ight of Takenking'
[15:29:41][C][switch.gpio:042]:   Inverted: YES
[15:29:41][C][switch.gpio:043]:   Pin: GPIO5 (Mode: OUTPUT)
[15:29:41][C][switch.gpio:059]:   Restore Mode: Restore (Defaults to OFF)
[15:29:41][C][switch.gpio:042]: GPIO Switch 'light of Destiny 2'
[15:29:41][C][switch.gpio:043]:   Pin: GPIO4 (Mode: OUTPUT)
[15:29:41][C][switch.gpio:059]:   Restore Mode: Restore (Defaults to OFF)
[15:29:41][C][logger:137]: Logger:
[15:29:41][C][logger:138]:   Level: DEBUG
[15:29:41][C][logger:139]:   Log Baud Rate: 115200
[15:29:41][C][logger:140]:   Hardware UART: UART0
[15:29:41][C][ota:029]: Over-The-Air Updates:
[15:29:41][C][ota:030]:   Address: poster_licht.local:8266
[15:29:41][C][ota:032]:   Using Password.
[15:29:41][C][api:103]: API Server:
[15:29:41][C][api:104]:   Address: poster_licht.local:6053

**Additional information and things you've tried:**

As said, i rebooted everything a few times, changed the cable, 
deleted and readded the ESPHome integration and used some exsample code to
see if my code eas wrong.


<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
