### ISSUE TITLE
bool Rect::inside(int16_t test_x, int16_t test_y, bool absolute) const implementation incorrect result for points to the right/bottom  of the rect

### ISSUE THREAD

**Issue by clarencelocke** [esphome/issues#6972]
### The problem

The `bool Rect::inside(int16_t test_x, int16_t test_y, bool absolute) const` implementation returns an incorrect result for points to the right/bottom  of the rect.

Test Code:
```
display::Rect r(0, 0, 10, 5);
ESP_LOGD("bug", "(5,2) in rect = %d", (int)r.inside(5,2));
ESP_LOGD("bug", "(10,2) in rect = %d", (int)r.inside(10,2));
```

and the results:
```
[20:18:40][D][bug:061]: (5,2) in rect = 1
[20:18:40][D][bug:062]: (10,2) in rect = 1
```

The point (10,2) is just outside the rect bounds and `inside(x,y)` should report `false`.

### Which version of ESPHome has the issue?

2025.4.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

N/A

### YAML Config

```yaml
on_boot:
    - priority: 798
      then:
        - lambda: |-
                      display::Rect r(0, 0, 10, 5);
                      ESP_LOGD("bug", "(5,2) in rect = %d", (int)r.inside(5,2));
                      ESP_LOGD("bug", "(10,2) in rect = %d", (int)r.inside(10,2));
```

### Anything in the logs that might be useful for us?

```txt
[20:18:40][D][bug:061]: (5,2) in rect = 1
[20:18:40][D][bug:062]: (10,2) in rect = 1
```
