### ISSUE TITLE
http_request error with PR#8224

### ISSUE THREAD

**Issue by SeByDocKy** [esphome/issues#6976]
### The problem

Starting with the PR#8224, all my http_request returned errors.

### Which version of ESPHome has the issue?

2025.5.0 dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.4

### What platform are you using?

ESP32

### Component causing the issue

http_request

### YAML Config

```yaml
http_request:
  verify_ssl: false
  # buffer_size_rx: 4096
  # buffer_size_tx: 4096

external_components:
    - source: github://pr#6721
      components: [ network, modem ]  # also add 'watchdog' if not found
      refresh: 10min
      
    # - source: github://pr#7632
      # components: [ network, modem ]
      # refresh: 10s
    
   # # To create a Wifi AP that will use the modem connection
    # # - source: github://pr#7147
    # #   components: [ wifi ]
    # #   refresh: 10min

modem:
  id: atmodem
  rx_pin: GPIO27 
  tx_pin: GPIO26
  power_pin:
    number: GPIO04
    inverted: True
  model: SIM7670  # or SIM7670 BG96 SIM7000 SIM800 GENERIC
  apn: free
  pin_code: "1234"
  enable_cmux: True
  # we can send initial AT commands at setup
  init_at:
    - AT+GMM  # model
  on_not_responding:
    - logger.log: "modem not responding"
  on_connect:
    - logger.log: "modem got IP"
  on_disconnect:
    - logger.log: "modem lost IP"  

text_sensor:
  - platform: modem
    network_type:
      name: network type
      
sensor:
  - platform: modem
    rssi:
      # name: ${name}_rssi
      id: ${name}_rssi
      accuracy_decimals: 1
      filters:
        - round: 1
    # ber:
    #   name: ber
    # latitude:
    #   name: Latitude
    # longitude:
    #   name: Longitude
    # altitude:
    #   name: Altitude
    # accuracy:
    #   name: Accuracy
    
  - platform: internal_temperature
    name: ${name}_temperature
    id: ${name}_temperature
    accuracy_decimals: 1
    filters:
      - round: 1
    
time:
  - platform: sntp
    on_time:
    
      - seconds: /30 #0
        # minutes: /1
        # hours: /1
        then:
          - http_request.post:
              url: ${ha_url}/api/webhook/${webhook_id}     #${post_webhook_url}
              request_headers:
                Content-Type: application/json
              json: 
                temp: !lambda |-
                  return std::to_string(id(${name}_temperature).state);
                rssi: !lambda |-
                  return std::to_string(id(${name}_rssi).state);   
                switch: !lambda |-
                  return std::to_string(id(${name}_local_switch).state);                   
      # Every x minutes
      - seconds: /15
        #minutes: /1
        then:
          - http_request.get:
              url: ${ha_url}/api/states/${ha_switch} #${get_url_str}
              capture_response: true
              request_headers:
                Content-Type: application/json
                Authorization: Bearer ${token_id} #${get_authorization_str}
              on_response:
                then:
                  - if:
                      condition:
                         lambda: return response->status_code == 200;
                      then:
                         - lambda: |-
                            json::parse_json(body, [](JsonObject root) -> bool {
                              if (root["state"]) {
                                char* newchar;
                                newchar = strdup(root["state"]);
                                if (strcmp(newchar , "off")){
                                  id(${name}_local_switch).turn_on();
                                }
                                else{
                                  id(${name}_local_switch).turn_off();
                                }
                                ESP_LOGI("http_request","parsed string %s" , newchar);
                                return true;
                                free(newchar);
                              }
                              else {
                                ESP_LOGI("http_request","No 'state' key in this json!");
                                return false;
                              }
                            });    
                      else: 
                        - logger.log:
                            format: "message %s"
                            args: [ 'body.c_str()' ]
```

### Anything in the logs that might be useful for us?

```txt
[23:48:18][D][http_request.idf:041]: Received response header, name: content-type, value: text/plain; charset=utf-8
[23:48:18][D][http_request.idf:041]: Received response header, name: content-length, value: 17
[23:48:18][E][http_request.idf:206]: HTTP Request failed; URL: https://xxxxxxxxxx.duckdns.org/api/states/switch.a7670e; Code: 401
[23:48:18][E][component:164]: Component http_request set Error flag: unspecified
[23:48:18][D][main:169]: message 401: Unauthorized
[23:48:18][W][component:239]: Component time took a long time for an operation (3485 ms).
[23:48:18][W][component:240]: Components should block for at most 30 ms.
[23:48:18][D][sensor:094]: 'testa7670e_temperature': Sending state 45.60000 °C with 1 decimals of accuracy
[23:48:19][E][component:178]: Component http_request cleared Error flag
[23:48:19][D][modem.text_sensor:039]: Modem text_sensor update
[23:48:19][D][text_sensor:064]: 'network type': Sending state 'LTE'
(b
```
