### ISSUE TITLE
Bug component.update at esphome on_boot priority: 800

### ISSUE THREAD

**Issue by vespadj** [esphome/issues#6981]
### The problem

v.2025.4.1
sensor doesn't update after boot
using component.update at esphome on_boot priority: 800
sensor: NA

### Which version of ESPHome has the issue?

2025.4.1

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

esphome on_boot

### YAML Config

```yaml
esphome:
  name: test_component_update_on_boot
  friendly_name: test_component_update_on_boot
  on_boot:
    - priority: 800    # This is where all hardware initialization of vital components is executed
      then:
        - lambda: |-
            ESP_LOGD("on_boot", "------ on boot ------");
        - component.update: total_sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

web_server:
  port: 80
  ota: false
  log: true

wifi:
  networks:
  - ssid: !secret wifi_ssid0
    password: !secret wifi_password0
  - ssid: !secret wifi_ssid1
    password: !secret wifi_password1

logger:

button:
  - platform: restart
    name: Restart ESP32

  - platform: template
    name: "Increment"
    on_press:
      then:
        - lambda: |
            id(total_count) ++ ;
        - component.update: total_sensor

globals:
  - id: total_count
    type: int
    initial_value: '0'
    restore_value: true

sensor:
  - platform: template
    id: total_sensor
    name: "Total Dose Count"
    unit_of_measurement: ""
    accuracy_decimals: 0
    lambda: |-
      return id(total_count);
    update_interval: never # update on component.update: total_sensor
```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by vespadj** [comment]
Solution:
```yaml
  on_boot:
    - priority: -100 # very low and late. Pretty much everything should already be initialized
      then:
        - component.update: total_dose_sensor
        - lambda: |-
            ESP_LOGD("on_boot", "------ boot completed ------");
```
My misunderstanding about docs: 
800: very high / early
-100: very low / late
