### ISSUE TITLE
mics_4514 component is missing device_class for every gas entity

### ISSUE THREAD

**Issue by bharvey88** [esphome/issues#6982]
### The problem

The mics_4514 component does not have a device_class set for any of the gas entities.

https://github.com/esphome/esphome/blob/20062576a3f088a4f6ab1f9f7bb1a52c78a545fe/esphome/components/mics_4514/sensor.py#L25-L45 the device class is missing from here.

### Which version of ESPHome has the issue?

ESPHome 2025.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4

### What platform are you using?

ESP32

### Board

Apollo AIR-1

### Component causing the issue

mics_4514

### YAML Config

```yaml
this override adds the expected device_class to the carbon monoxide entity. The issue should be fixed for every gas entity though.
sensor:
  - platform: mics_4514
    id: !extend mics4514
    carbon_monoxide:
      device_class: carbon_monoxide
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

![Image](https://github.com/user-attachments/assets/4b0d3cbe-9106-4286-8ed3-599900133165)

missing device_class as shown above
