### ISSUE TITLE
Modbus: on_online action is not executed after the device starts up

### ISSUE THREAD

**Issue by dominikstupka** [esphome/issues#6986]
### The problem

The Modbus component does not trigger `on_online` after startup even when communication with the slave device is successfully established, so the sensor stays in the `unknown` state. Only after communication is lost does the sensor state switch to `OFF` , and when communication is restored it changes to `ON` .

I would expect that if communication is established immediately after the device starts, `the` on_online action would be triggered.

### Which version of ESPHome has the issue?

2025.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4

### What platform are you using?

ESP32

### Board

DIY

### Component causing the issue

Modbus

### YAML Config

```yaml
#Relé
  - id: modbus_relay_board_1
    address: 0x14   
    modbus_id: modbus1
    setup_priority: -10
    offline_skip_updates: 10
    max_cmd_retries: 1
    update_interval: 2s
    command_throttle: 5ms
    on_offline:
      then:
        - binary_sensor.template.publish:
            id: mb_relay_board_1_state
            state: OFF
    on_online:
      then:
        - binary_sensor.template.publish:
            id: mb_relay_board_1_state
            state: ON
```

### Anything in the logs that might be useful for us?

```txt

```
