### ISSUE TITLE
Konnected Alarm Panels / ESP Home in Home Assistant - Update Fails - April 2025

### ISSUE THREAD

**Issue by BlaqueJaxx** [esphome/issues#6987]
### The problem

The latest update to ESP Home will not install onto my Konnected Alarm Panels any longer.  Never had an issue prior to version 
Currently Installed Version: 2025.4.0
Will not install Version 2025.4.1
Error pasted below.

src/esphome/components/mdns/mdns_component.cpp: In member function 'void esphome::mdns::MDNSComponent::compile_records_()':
src/esphome/components/mdns/mdns_component.cpp:65:50: error: 'using element_type = class esphome::api::APINoiseContext' {aka 'class esphome::api::APINoiseContext'} has no member named 'has_psk'
   65 |     if (api::global_api_server->get_noise_ctx()->has_psk()) {
      |                                                  ^~~~~~~
Compiling .pioenvs/alarm-panel-826462/src/esphome/core/ring_buffer.cpp.o
*** [.pioenvs/alarm-panel-826462/src/esphome/components/mdns/mdns_component.cpp.o] Error 1
Compiling .pioenvs/alarm-panel-826462/src/esphome/core/scheduler.cpp.o
========================== [FAILED] Took 6.14 seconds ==========================
===== [ERROR] /config/esphome/alarm-panel-826462.yaml =====

### Which version of ESPHome has the issue?

2025.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.0b1

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

rror: 'using element_type = class esphome::api::APINoiseContext'

### YAML Config

```yaml
substitutions:
  name: alarm-panel-826462
  friendly_name: AP_826462
packages:
  konnected.alarm-panel-esp8266: github://konnected-io/konnected-esphome/alarm-panel-esp8266.yaml@master
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: qlsyJluAUNz17o3gM0dt+X3f8JaVnsqQErNGIN1ecGY=
  reboot_timeout: 0s


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: 192.168.86.33
  # ...
  manual_ip:
    static_ip: 192.168.86.33
    gateway: 192.168.86.1
    subnet: 255.255.255.0
    dns1: 192.168.86.1

mdns:
  disabled: false
```

### Anything in the logs that might be useful for us?

```txt

```
