### ISSUE TITLE
VL6180X Working, Kinda

### ISSUE THREAD

**Issue by tbillion** [esphome/issues#6992]
### The problem

didnt know where to put this so i just plugged it in here mods or someone will do something with it or delete it , im good either way .. 

`#pragma once

#include "esphome/components/i2c/i2c.h"
#include "esphome/components/sensor/sensor.h"
#include "esphome/core/component.h"
#include <Adafruit_VL6180X.h>

namespace esphome {
namespace vl6180x {

class VL6180XComponent : public PollingComponent, public i2c::I2CDevice {
 public:
  void set_distance_sensor(sensor::Sensor *sensor) { this->distance_sensor_ = sensor; }
  void set_luminance_sensor(sensor::Sensor *sensor) { this->luminance_sensor_ = sensor; }

  void setup() override {
    if (!vl_.begin(&Wire)) {
      ESP_LOGE("vl6180x", "Failed to initialize VL6180X");
      this->mark_failed();
    } else {
      ESP_LOGI("vl6180x", "VL6180X initialized");
    }
  }

  void update() override {
    if (this->distance_sensor_ != nullptr) {
      uint8_t dist = vl_.readRange();
      this->distance_sensor_->publish_state(dist);
    }
    if (this->luminance_sensor_ != nullptr) {
      uint16_t lux = vl_.readLux(VL6180X_ALS_GAIN_5);
      this->luminance_sensor_->publish_state(lux);
    }
  }

 protected:
  sensor::Sensor *distance_sensor_{nullptr};
  sensor::Sensor *luminance_sensor_{nullptr};
  Adafruit_VL6180X vl_;
};

}  // namespace vl6180x
}  // namespace esphome
`

that is vl6180x.h

this is the .cpp

`#include "vl6180x.h"

namespace esphome {
namespace vl6180x {

// nothing to do here

}  // namespace vl6180x
}  // namespace esphome
`
`import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components import i2c, sensor
from esphome.const import (
    CONF_ID,
    CONF_ADDRESS,
    CONF_UPDATE_INTERVAL,
    CONF_NAME,
)

DEPENDENCIES = ["i2c"]

CONF_DISTANCE = "distance"
CONF_LUMINANCE = "luminance"

vl6180x_ns = cg.esphome_ns.namespace("vl6180x")
VL6180XComponent = vl6180x_ns.class_("VL6180XComponent", cg.PollingComponent, i2c.I2CDevice)

CONFIG_SCHEMA = cv.Schema({
    cv.GenerateID(): cv.declare_id(VL6180XComponent),
    cv.Optional(CONF_ADDRESS, default=0x29): cv.i2c_address,
    cv.Optional(CONF_UPDATE_INTERVAL, default="1s"): cv.update_interval,
    cv.Required(CONF_DISTANCE): sensor.sensor_schema(
        unit_of_measurement="mm",
        icon="mdi:ruler",
        accuracy_decimals=0,
        device_class="distance",
    ),
    cv.Required(CONF_LUMINANCE): sensor.sensor_schema(
        unit_of_measurement="lx",
        icon="mdi:brightness-5",
        accuracy_decimals=0,
        device_class="illuminance",
    ),
}).extend(i2c.i2c_device_schema(0x29))

async def to_code(config):
    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)
    await i2c.register_i2c_device(var, config)

    distance = await sensor.new_sensor(config[CONF_DISTANCE])
    cg.add(var.set_distance_sensor(distance))

    luminance = await sensor.new_sensor(config[CONF_LUMINANCE])
    cg.add(var.set_luminance_sensor(luminance))
`
that is the init.py.

it works pretty good the only thing thusfar that i havent been able to get working is LUX, but the measurement works fine. 

`[20:49:45][W][component:237]: Component vl6180x.sensor took a long time for an operation (120 ms).
[20:49:45][W][component:238]: Components should block for at most 30 ms.
[20:49:46][D][sensor:094]: 'VL6180X Distance': Sending state 37.00000 mm with 0 decimals of accuracy
[20:49:46][D][sensor:094]: 'VL6180X Luminance': Sending state 0.00000 lx with 0 decimals of accuracy`

havent been able to shut this up though either. its painfully slow at reading in this situation. 

basic yaml cut out of much bigger yaml excuse the errors that ensue if any. 

again not really an issue other than HA doesnt support out the box, not really a feature request cuz i did most the work. 

Peace, and Happy Hacking!

### Which version of ESPHome has the issue?

2025.3.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.3

### What platform are you using?

ESP32-IDF

### Board

ESP32_Relay_X2

### Component causing the issue

VL6180X

### YAML Config

```yaml
`esphome:
  name: YOURNAME
  friendly_name: YOURFRIENDLYNAME
  min_version: 2024.11.0
  name_add_mac_suffix: false
  on_boot:
    priority: 800
    then:
      - switch.turn_on: vl6180x_power
  platformio_options:
  lib_deps:
    - https://github.com/adafruit/Adafruit_VL6180X
    - https://github.com/adafruit/Adafruit_BusIO
    - Wire
  lib_ldf_mode: deep+

external_components:
  - source:
      type: local
      path: custom_components
    components: [vl6180x]

# I2C Bus Configuration
i2c:
  sda: GPIO21
  scl: GPIO22
  frequency: 400kHz
  scan: true
  id: bus_a

switch:

  - platform: gpio
    pin: GPIO26
    id: vl6180x_power
    name: "VL6180X Power"
    restore_mode: ALWAYS_OFF
sensor:
  - platform: vl6180x
    id: vl6180x_sensor
    distance:
      name: "VL6180X Distance"
    luminance:
      name: "VL6180X Luminance"
    address: 0x29
    update_interval: 1s
`
```

### Anything in the logs that might be useful for us?

```txt
[20:55:29][D][sensor:094]: 'VL6180X Distance': Sending state 36.00000 mm with 0 decimals of accuracy
[20:55:29][D][sensor:094]: 'VL6180X Luminance': Sending state 0.00000 lx with 0 decimals of accuracy
[20:55:29][W][component:237]: Component vl6180x.sensor took a long time for an operation (119 ms).
[20:55:29][W][component:238]: Components should block for at most 30 ms.
[20:55:30][D][sensor:094]: 'VL6180X Distance': Sending state 38.00000 mm with 0 decimals of accuracy
[20:55:30][D][sensor:094]: 'VL6180X Luminance': Sending state 0.00000 lx with 0 decimals of accuracy
[20:55:30][W][component:237]: Component vl6180x.sensor took a long time for an operation (118 ms).
[20:55:30][W][component:238]: Components should block for at most 30 ms.
```

### Additional information

Thanks for all the hard work !
