### ISSUE TITLE
esp32_camera fails on boards with no psram - should be configurable

### ISSUE THREAD

**Issue by micw** [esphome/issues#6996]
### The problem

I have a esp32_cam module without psram. It used to work years ago with esphome but now fails with 

```
E (1353) cam_hal: cam_dma_config(300): frame buffer malloc failed
E (1353) cam_hal: cam_config(384): cam_dma_config failed
E (1354) camera: Camera config failed with error 0xffffffff
```

The reason is that esphome builds esp32_camera always with PSRAM although it's an option that can be toggled: https://github.com/espressif/esp32-camera/pull/302/files

After changing `this->config_.fb_location` to `CAMERA_FB_IN_DRAM` in `esp32_camera/esp32_camera.cpp`, it works again.

This should be an option that can be set in the component.

Related issues:
- https://github.com/espressif/esp32-camera/issues/571
- https://github.com/espressif/esp32-camera/issues/639
- https://github.com/espressif/esp32-camera/issues/339

### Which version of ESPHome has the issue?

2025.4.1-1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

not relevant

### What platform are you using?

ESP32

### Board

m5cam

### YAML Config

```yaml
esp32_camera:
  name: Cam1
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO17, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15
  idle_framerate: "0.5 fps"
  resolution: 640x480
```

### Anything in the logs that might be useful for us?

```txt
E (1353) cam_hal: cam_dma_config(300): frame buffer malloc failed
E (1353) cam_hal: cam_config(384): cam_dma_config failed
E (1354) camera: Camera config failed with error 0xffffffff
```
