### ISSUE TITLE
Error while compiling for a esp8266

### ISSUE THREAD

**Issue by mr-pepe69** [esphome/issues#7001]
### The problem

I tried installing a simple yaml with the necesary stuff to connect to my device. but i get an error while compiling

It should have compiled and connected but it always error out there.

### Which version of ESPHome has the issue?

2025.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.4

### What platform are you using?

ESP8266

### Board

nodeMCU v3

### Component causing the issue

the board itself.

### YAML Config

```yaml
esphome:
  name: esphome-web-3cbdbe
  friendly_name: Living Room sensors
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
    encryption:
      key: !secret esphome_encryption_key_livingroom
# Allow Over-The-Air updates

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.4.1
INFO Reading configuration /config/esphome/esphome-web-3cbdbe.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-web-3cbdbe (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESP8266WiFi
|-- ESP8266mDNS
|-- noise-c @ 0.1.6
Compiling .pioenvs/esphome-web-3cbdbe/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/esphome-web-3cbdbe/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/esphome-web-3cbdbe/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/esphome-web-3cbdbe/src/esphome/components/wifi/wifi_component_libretiny.cpp.o
src/esphome/components/mdns/mdns_esp8266.cpp: In member function 'virtual void esphome::mdns::MDNSComponent::setup()':
src/esphome/components/mdns/mdns_esp8266.cpp:17:3: error: 'MDNS' was not declared in this scope
   17 |   MDNS.begin(this->hostname_.c_str());
      |   ^~~~
src/esphome/components/mdns/mdns_esp8266.cpp: In member function 'virtual void esphome::mdns::MDNSComponent::loop()':
src/esphome/components/mdns/mdns_esp8266.cpp:39:30: error: 'MDNS' was not declared in this scope
   39 | void MDNSComponent::loop() { MDNS.update(); }
      |                              ^~~~
src/esphome/components/mdns/mdns_esp8266.cpp: In member function 'virtual void esphome::mdns::MDNSComponent::on_shutdown()':
src/esphome/components/mdns/mdns_esp8266.cpp:42:3: error: 'MDNS' was not declared in this scope
   42 |   MDNS.close();
      |   ^~~~
*** [.pioenvs/esphome-web-3cbdbe/src/esphome/components/mdns/mdns_esp8266.cpp.o] Error 1
```
