### ISSUE TITLE
LD2450 doesn't use the set presence timeout

### ISSUE THREAD

**Issue by pottkopp** [esphome/issues#7006]
### The problem

The LD2450 doesn't use the set presence timeout value. 
Instead it uses the following times to reset the presence states:
If Multi-Target is enabled: 36 seconds
If Multi-Target is disabled: 120 seconds

### Which version of ESPHome has the issue?

2025.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.0

### What platform are you using?

ESP32-IDF

### Board

esp32-c3-devkitm-1

### Component causing the issue

LD2450

### YAML Config

```yaml
substitutions:
  name: apollo-mtr-1-f8b110
  friendly_name: Apollo MTR-1 Küche f8b110
packages:
  ApolloAutomation.MTR-1: github://ApolloAutomation/MTR-1/Integrations/ESPHome/MTR-1_BLE.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret ek_mtr1_kuche


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

In the log it doesn't say something like "Timeout of XX seconds reached. Resetting presence states."
It just says when a new timeout value is set by the user.
In Home Assistant, the web interface and the log the set timeout value is shown correctly. So it seems to be saved on the device.

I have two Apollo MTR-1 and both show this behavior.
Software details of both sensors:
Firmware (reported by HLKRadarTool): 2.04.23101915
Firmware (reported by ESPHome): 25.4.11.1
I tried using the MTR-1.yaml as well as MTR-1_BLE.yaml without a difference regarding this issue.

I tried:
- setting low (3 seconds) and high (1000 seconds) values
- rebooting the esp after setting the value in Home Assistant
- setting the value via the web interface
- factory resetting the esp and leaving it at the default value (5 seconds)
- HLK-LD25 fw version 2.02.23090617
- enabling/disabling BT and/or the led doesn't change the actual timeout it uses

My suspicion:
It checks the wrong memory address to load the presence timeout value. 
Instead of the one it's actually saved in it seems like it checks the address where (part of) the state of the Multi Target option is saved.

Workaround:
Create helpers in Home Assistant for the needed presence states and set the timeout in automations for the helpers to be (re)set.

Let me know if you need more details or if I should test something.
