### ISSUE TITLE
debug sensors: lambda filter not triggering

### ISSUE THREAD

**Issue by Elix-g** [esphome/issues#7007]
### The problem

I've configured sensors for the debug platform to show device information in HA. Since the sensors return values in bytes, I want to recalculate the values to kB using a lambda filter. Works fine for free heap and max. block size but not for loop and free psram. HA still shows those values in byte/ms.

### Which version of ESPHome has the issue?

2025.4.x

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2025.5.x

### What platform are you using?

ESP32-IDF

### Board

Elecrow CrowPanel 7.0" HMI-Display (ESP32-S3-WROOM-1)

### Component causing the issue

debug

### YAML Config

```yaml
debug:
  update_interval: 60s
sensors:
  - platform: debug
    free:
      accuracy_decimals: 1
      device_class: data_size
      entity_category: diagnostic
      filters:
        - lambda: !lambda return x / 1024.0;
      unit_of_measurement: kB
      name: "Free Heap"
      id: device_free_heap
      icon: mdi:memory
    block:
      accuracy_decimals: 1
      device_class: data_size
      entity_category: diagnostic
      filters:
        - lambda: !lambda return x / 1024.0;
      unit_of_measurement: kB
      name: "Heap max. Block"
      id: device_heap_max_block
      icon: mdi:memory
    loop_time:
      accuracy_decimals: 0
      device_class: duration
      entity_category: diagnostic
      filters:
        - lambda: !lambda return x / 1000.0;
      unit_of_measurement: s
      name: "Loop Time"
      id: device_loop_time
      icon: mdi:sync
    psram:
      accuracy_decimals: 0
      device_class: data_size
      entity_category: diagnostic
      filters:
        - lambda: !lambda return x / 1024.0;
      unit_of_measurement: kB
      name: "Free PSRAM"
      id: device_psram_free
      icon: mdi:memory
```

### Anything in the logs that might be useful for us?

```txt
nothing useful in the logs
```
