### ISSUE TITLE
Plug will not connect back to WiFi

### ISSUE THREAD

**Issue by RafhaanShah** [esphome/issues#701]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io running in docker on Raspberry Pi 3B+

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 in [Slitinto NX-SM110](https://blakadder.github.io/templates/stilinto_NX-SM110.html) flashed via [Tuya Convert](https://github.com/ct-Open-Source/tuya-convert)

**Affected component:**

I'm assuming it's something to do with the WiFi component but not 100% sure
https://esphome.io/components/wifi.html

**Description of problem:**
Used Tuya Convert to flash ESPHome, worked perfectly fine throughout and during subsequent config changes and OTA updates. After my tweaking was done, left it unplugged for about 5 days and when I replug them in they do not connect to WiFi and I cannot view logs or change the config.

Is there any way to reset it?

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: plug1
  upper_devicename: Plug1

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: WARN

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      inverted: True
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${upper_devicename} Power"
    id: relay
    pin: GPIO15
    on_turn_on:
      # - switch.toggle: ledblue
      - switch.toggle: ledred
    on_turn_off:
      # - switch.toggle: ledblue
      - switch.toggle: ledred
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: ledred
    pin: GPIO0
    inverted: True
    restore_mode: ALWAYS_OFF
  # - platform: gpio
  #   id: ledblue
  #   pin: GPIO02
  #   inverted: True
  #   restore_mode: ALWAYS_OFF

sensor:
  - platform: wifi_signal
    name: "${upper_devicename} WiFi Signal"
    update_interval: 60s
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    power:
      name: "${upper_devicename} Wattage"
      unit_of_measurement: W
      id: wattage
      accuracy_decimals: 0
      filters:
        - calibrate_linear:
          - 38 -> 6
          - 6275 -> 810
    current:
      name: "${upper_devicename} Amperage"
      unit_of_measurement: A
      id: current
      accuracy_decimals: 1
      filters:
        - calibrate_linear:
          - 5.46 -> 3.376
          - 0.077 -> 0.048
    voltage:
      name: "${upper_devicename} Voltage"
      unit_of_measurement: V
      id: voltage
      accuracy_decimals: 0
      filters:
        - calibrate_linear:
          - 641 -> 244
          - 635 -> 243
    change_mode_every: 3
    update_interval: 12s
  - platform: total_daily_energy
    name: "${upper_devicename} Total Daily Energy"
    power_id: wattage
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Not sure if there's any way to reset it but tried pressing and holding the button, rapidly pressing 10 times etc.

Also created a new WiFi access point with the same credentials, and with the same SSID but no password to see if it would connect to that but no luck.

Monitoring WiFi broadcast requests in Wireshark show that the plug is not making probe requests to any specific SSID but instead the Wildcard SSID.
