### ISSUE TITLE
internal_filter_mode throws a validation error in pulse_meter

### ISSUE THREAD

**Issue by mhooghiemstra** [esphome/issues#7013]
### The problem

When trying to use the internal_filter_mode in pulse_meter I get the following validation error:

[internal_filter_mode] is an invalid option for [sensor.pulse_meter]. Did you mean [internal_filter]?

Running on the latest version.

### Which version of ESPHome has the issue?

2025.4.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4.1

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### YAML Config

```yaml
sensor:
  - platform: pulse_meter
    name: "Cold water - current water flow"
    pin:
      number: D6 # pin to which the D0 output of TCRT5000 is connected
      inverted: true 
      mode:
        input: true
        pullup: true
    unit_of_measurement: "l/min."
    accuracy_decimals: 0
    icon: "mdi:gauge"
    internal_filter_mode: PULSE
    internal_filter: 100ms
    timeout: 1min
    total:
      name: "Cold water - liters used"
      unit_of_measurement: "L"
      state_class: "total_increasing"
      device_class: WATER
      icon: "mdi:water-pump"
```

### Anything in the logs that might be useful for us?

```txt

```
