### ISSUE TITLE
`on_multi_click` Fails to Detect Rapid Successive Clicks Across Binary Sensors (e.g. MPR121)

### ISSUE THREAD

**Issue by sfields-forever** [esphome/issues#7014]
### The problem

**Description**:
The `mpr121` component with `on_multi_click` automation does not correctly detect rapid successive click patterns when the time between click patterns is short (e.g., within a few hundred milliseconds). Specifically, after triggering one click pattern (e.g., single short click or double short click), subsequent valid click patterns (e.g., single long click or another short click) are not detected, even though their conditions are met.

**Steps to Reproduce**:
1. Configure an MPR121 sensor with the provided YAML configuration (see below).
2. Trigger a "Single Short Click" (`ON for at most 1s, OFF for at least 0.4s`).
3. Within a few hundred milliseconds (e.g., <500ms) after the click is detected, perform one of the following (both do not work as expected):
   a. Press and hold the touch pad for >1s to trigger a "Single Long Click".
   b. Perform a "Double Short Click" sequence (`ON for at most 1s, OFF for at most 0.4s, ON for at most 1s, OFF for at least 0.05s`).

**Expected Behavior**:
- After a "Single Short Click" is detected, a subsequent "Single Long Click" or "Double Short Click" should be detected if their timing conditions are met.

**Actual Behavior**:
- After a "Single Short Click" is detected, a subsequent (within a few hundred milliseconds) "Single Long Click" or "Double Short Click" is not detected, even though the timing conditions are met.
- The same issue occurs when triggering a "Double Short Click" followed (within a few hundred milliseconds) by a subsequent "Single Short Click" or "Single Long Click".
- The `on_press` and `on_release` events are always detected and triggered correctly.
- Interestingly, a second "Single Short Click" is detected after a first "Single Short Click", even when the interval between the two patterns is only a few hundred milliseconds.

           
**Additional Context:**
- The issue does not occur if there is a sufficient delay (e.g., >500ms–1s) between click patterns.
- Setting `touch_debounce` and `release_debounce` to 0 does not resolve the issue.
- The MPR121 is correctly wired and communicates via I²C without errors.
- The issue is reproducible across multiple touch channels.

### Which version of ESPHome has the issue?

2025.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.1

### What platform are you using?

ESP32

### Board

 lilygo_t7_mini32,  wt32_eth01

### Component causing the issue

binary_sensor/on_multi_click

### YAML Config

```yaml
esphome:
  name: wt32-eth01-2
  friendly_name: wt32_eth01-2

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

i2c:
  sda: GPIO4
  scl: GPIO14
  scan: true

mpr121:
  id: mpr121_component
  address: 0x5A
  touch_debounce: 0 #1
  release_debounce: 0 #1
  touch_threshold: 12
  release_threshold: 7

sensor:
  - platform: template
    id: touch_click_type
    name: "Touch Click Type"
    accuracy_decimals: 0
    update_interval: never

binary_sensor:
  - platform: mpr121
    id: touch
    channel: 0
    name: "Touch Key"
    on_press:
      then:
        - logger.log: "Pressed"
        - lambda: |-
            id(touch_click_type).publish_state(6);
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at least 0.4s
      then:
        - logger.log: "Single Short Clicked"
        - lambda: |-
            id(touch_click_type).publish_state(1);
    - timing:
        - ON for at most 1s
        - OFF for at most 0.4s
        - ON for at most 1s
        - OFF for at least 0.05s
      then:
        - logger.log: "Double Short Clicked"
        - lambda: |-
            id(touch_click_type).publish_state(2);
    - timing:
        - ON for at least 1s
      then:
        - logger.log: "Single Long Clicked"
        - lambda: |-
            id(touch_click_type).publish_state(4);
    on_release: 
      then:
        - logger.log: "Released"
        - lambda: |-
            id(touch_click_type).publish_state(0);
```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by ssieb** [comment]
Why are you using a sensor for events?
Your press and release triggers are likely to mess things up.
Set the logger level to verbose to see what's happening with the multi-click.
You didn't show any logs, so it might not even need verbose to see what's happening.

**Comment by sfields-forever** [comment]
Thank you very much for your response.

> Why are you using a sensor for events?

I removed the sensor - to no avail - events have the same drawback.

> Your press and release triggers are likely to mess things up. 

I removed the on_press and on_release blocks. Same behaviour. Why should they mess things up? It is official code example from esphome.io/components/binary_sensor/

The code in question is now as follows

```
binary_sensor:
  - platform: mpr121
    id: touch
    channel: 0
    name: "Touch Key"
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at least 0.4s
      then:
        - logger.log: "Single Short Clicked"
    - timing:
        - ON for at most 1s
        - OFF for at most 0.4s
        - ON for at most 1s
        - OFF for at least 0.05s
      then:
        - logger.log: "Double Short Clicked"
    - timing:
        - ON for at least 1s
      then:
        - logger.log: "Single Long Clicked"
```

> Set the logger level to verbose to see what's happening with the multi-click. You didn't show any logs, so it might not even need verbose to see what's happening.

Here are the logs:

1. Trigger a "Single Short Click" (ON for at most 1s, OFF for at least 0.4s) + after the click is detected wait some hundred milliseconds (e.g., <500ms)  + trigger a "Single Long Click" (ON for at least 1s):
```
[17:50:03][D][binary_sensor:036]: 'Touch Key': Sending state ON
[17:50:03][D][binary_sensor:036]: 'Touch Key': Sending state OFF
[17:50:03][D][main:282]: Single Short Clicked
[17:50:04][D][binary_sensor:036]: 'Touch Key': Sending state ON
[17:50:13][D][binary_sensor:036]: 'Touch Key': Sending state OFF
```
"Single Long Click" is not detected, should be in the second-to-last line.

Whereas the "Single Long Click" IS detected, if one waits more than approx. 800 milliseconds after the "Single Short Click" was detected:
```
[17:52:25][D][binary_sensor:036]: 'Touch Key': Sending state ON
[17:52:25][D][binary_sensor:036]: 'Touch Key': Sending state OFF
[17:52:25][D][main:282]: Single Short Clicked
[17:52:26][D][binary_sensor:036]: 'Touch Key': Sending state ON
[17:52:27][D][main:320]: Single Long Clicked
[17:52:29][D][binary_sensor:036]: 'Touch Key': Sending state OFF
```

2. Trigger a "Single Short Click" (ON for at most 1s, OFF for at least 0.4s) + after the click is detected wait some hundred milliseconds (e.g., <500ms) + trigger a "Double Short Click" sequence (ON for at most 1s, OFF for at most 0.4s, ON for at most 1s, OFF for at least 0.05s):
```
[17:56:07][D][binary_sensor:036]: 'Touch Key': Sending state ON
[17:56:07][D][binary_sensor:036]: 'Touch Key': Sending state OFF
[17:56:07][D][main:282]: Single Short Clicked
[17:56:08][D][binary_sensor:036]: 'Touch Key': Sending state ON
[17:56:08][D][binary_sensor:036]: 'Touch Key': Sending state OFF
[17:56:09][D][binary_sensor:036]: 'Touch Key': Sending state ON
[17:56:09][D][binary_sensor:036]: 'Touch Key': Sending state OFF
```
"Double Short Click" is not detected, should be in last line.

Whereas the "Double Short Click" IS detected, if one waits more than approx. 800 milliseconds after the "Single Short Click" was detected:
```
[17:57:18][D][binary_sensor:036]: 'Touch Key': Sending state ON
[17:57:18][D][binary_sensor:036]: 'Touch Key': Sending state OFF
[17:57:18][D][main:282]: Single Short Clicked
[17:57:20][D][binary_sensor:036]: 'Touch Key': Sending state ON
[17:57:20][D][binary_sensor:036]: 'Touch Key': Sending state OFF
[17:57:21][D][binary_sensor:036]: 'Touch Key': Sending state ON
[17:57:21][D][binary_sensor:036]: 'Touch Key': Sending state OFF
[17:57:21][D][main:307]: Double Short Clicked

```

This is absolutely reproducible, and the code is very simple (I assume it’s error-free), but what is the cause of the problem? Does this issue only affect the mpr121 platform, or is it a general binary_sensor problem? Do you have any idea? Thankyou once again.
