### ISSUE TITLE
LD2420 does not work on GPIO43 and GPIO44 of the ESP32-S3

### ISSUE THREAD

**Issue by patrick3399** [esphome/issues#7015]
### The problem

Other UART sensors work when connected to GPIO43 and GPIO44.
The LD2420 works when connected to other GPIOs.

### Which version of ESPHome has the issue?

2025.4.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.1

### What platform are you using?

ESP32

### Board

ESP32-S3-DevKitC

### Component causing the issue

LD2420

### YAML Config

```yaml
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
logger:
  level: VERBOSE
  baud_rate: 0
uart:
  tx_pin: GPIO43
  rx_pin: GPIO44
  baud_rate: 115200
  id: uart_2420
ld2420:
text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware
binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence
```

### Anything in the logs that might be useful for us?

```txt
[E][component:082]:   Component ld2420 is marked FAILED: 
```

### Additional information
Already test:  CONFIG_ESP_CONSOLE_NONE, CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG, CONFIG_ESP_CONSOLE_USB_CDC, CONFIG_ESP_CONSOLE_UART_CUSTOM, CONFIG_ESP_CONSOLE_UART_CUSTOM_NUM_1

**Comment by swoboda1337** [comment]
```

**Comment by patrick3399** [comment]
@swoboda1337 Yes, I disable the HW UART logger.

**Comment by swoboda1337** [comment]
You could also try to add this option:
```
esp32:
  framework:
    sdkconfig_options:
      CONFIG_ESP_CONSOLE_NONE: "y"
```

**Comment by ssieb** [comment]
Is there a reason you need to use those pins?

**Comment by patrick3399** [comment]
Because the existing device uses GPIO43 and GPIO44 to connect external sensors, they must be used.

**Comment by swoboda1337** [comment]
Did you try with CONFIG_ESP_CONSOLE_NONE?

**Comment by patrick3399** [comment]
@swoboda1337 It still doesn't work, but I noticed that if I change the TX pin to a different one, it works properly.

**Comment by mKenfenheuer** [comment]
Can you post your full YAML? Having the same issue - LD2420 not working with ESP32S3 even if I change the GPIO pins, Lolin32 (ESP32) works fine. 
Version: 2025.7.3

```yaml
esphome:
  name: esp32-presence-01
  friendly_name: ESP32 Presence 01

esp32:
  board: lolin_s3_mini
  variant: esp32s3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    pin: GPIO21
    num_leds: 30
    chipset: ws2812
    name: "RGB Light"

uart:
  tx_pin: GPIO12
  rx_pin: GPIO11
  baud_rate: 115200

ld2420:

text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum
    # See "Number" section below for detail
    gate_select:
      name: Select Gate to Set
    still_threshold:
      name: Set Still Threshold Value
    move_threshold:
      name: Set Move Threshold Value

button:
  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits
    
```
