### ISSUE TITLE
Linking fails for RP2040 with ESPHome 2025.4.2

### ISSUE THREAD

**Issue by emefff** [esphome/issues#7020]
### The problem

Linking fails on my one and only device with RP2040 with the current ESPHome 2025.4.2.
The issue in #7008 is also visible on this device, but the error in the end is new. I also tried to clean build files, the error persists.

### Which version of ESPHome has the issue?

2025.4.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.1

### What platform are you using?

RP2040

### Board

rpipicow

### Component causing the issue

linker

### YAML Config

```yaml
esphome:
  name: esphome--14

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:
  
# Enable Home Assistant API
api:
  reboot_timeout: 1min 
  encryption:
    key: ***** REDACTED *****

ota:
  platform: esphome
  password: ***** REDACTED *****

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  output_power: 20dB #8.5-20db
  manual_ip:
    static_ip: ***** REDACTED *****
    gateway: ***** REDACTED *****
    subnet: 255.255.255.0
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Esphome--14 Fallback Hotspot"
    password: ***** REDACTED *****

status_led:
  pin:
    number: GPIO25 

one_wire:
  - platform: gpio
    pin: GPIO5

i2c: 
  sda: GPIO20 
  scl: GPIO21 
  scan: true
  id: bus_a    

sensor:
  - platform: dallas_temp
    address: 0x230922503ac7d228
    name: "Schlafzimmer oben Pico Onboard Dallas Temperatur"
    accuracy_decimals: 1  
    filters:
      - filter_out: nan
      - filter_out: 85.0   
  - platform: wifi_signal
    name: "Schlafzimmer oben Pico WiFi Signal"
    update_interval: 300s # defaults to 60s
    accuracy_decimals: 1
  - platform: uptime
    name: "Schlafzimmer oben Pico Uptime"
    update_interval: 300s # defaults to 60s
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1
  - platform: bmp280_i2c
    temperature:
      name: "Schlafzimmer oben Pico BMP280 Temperatur"
      oversampling: 16x
    pressure:
      name: "Schlafzimmer oben Pico BMP280 Druck"
    #humidity:
    #  name: "Schlafzimmer 2 Pico BME280 Feuchtigkeit"
    address: 0x76
    update_interval: 60s
  - platform: bh1750
    name: "Schlafzimmer oben Pico BH Lichtstärke"
    address: 0x23
    update_interval: 60s

button:
  - platform: restart
    name: "Schlafzimmer oben Restart"
    id: schlafzimmer2_restart_button
    disabled_by_default: true
    on_press:
      then:
        - logger.log: Button Pressed

```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/esphome--14/FrameworkArduino/wiring_digital.cpp.o
Compiling .pioenvs/esphome--14/FrameworkArduino/wiring_private.cpp.o
Compiling .pioenvs/esphome--14/FrameworkArduino/wiring_pulse.cpp.o
Compiling .pioenvs/esphome--14/FrameworkArduino/wiring_shift.cpp.o
Archiving .pioenvs/esphome--14/libFrameworkArduino.a
Linking .pioenvs/esphome--14/firmware.elf
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/lib/thumb/libc.a(libc_a-findfp.o): in function `std':
/workdir/repo/newlib/newlib/libc/stdio/findfp.c:93:(.text+0xda): undefined reference to `__retarget_lock_init_recursive'
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /workdir/repo/newlib/newlib/libc/stdio/findfp.c:93:(.text+0x124): undefined reference to `__retarget_lock_init_recursive'
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /workdir/repo/newlib/newlib/libc/stdio/findfp.c:93:(.text+0x17c): undefined reference to `__retarget_lock_init_recursive'
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/lib/thumb/libc.a(libc_a-findfp.o): in function `__sfp':
/workdir/repo/newlib/newlib/libc/stdio/findfp.c:201:(.text+0x1ea): undefined reference to `__retarget_lock_init_recursive'
collect2: error: ld returned 1 exit status
*** [.pioenvs/esphome--14/firmware.elf] Error 1
========================= [FAILED] Took 154.77 seconds =========================
```

EDIT: added .yaml
