### ISSUE TITLE
[modbus_controller] server_register RAW value_type broken

### ISSUE THREAD

**Issue by gotnone** [esphome/issues#7024]
### The problem

YAML checks allow user to select `RAW` value_type, but C++ backend does not properly support RAW.

* User supplied value in `read_lambda` is not passed to client / master
* The response from the modbus_controller component is out of spec and confuses the client / master

### Which version of ESPHome has the issue?

2025.5.0-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A bug is independent of HA version

### What platform are you using?

ESP32

### Board

Lolin32-Lite

### Component causing the issue

modbus_controller

### YAML Config

```yaml
uart:
  - id: uart_modbus_server
    tx_pin: GPIO25
    rx_pin: GPIO35
    baud_rate: 57600

modbus:
  - uart_id: uart_modbus_server
    id: modbus_server
    role: server

modbus_controller:
  - modbus_id: modbus_server
    address: 0x1
    server_registers:
      - address: 0x0000
        value_type: RAW
        read_lambda: |-
          return 0xAA55;
```

### Anything in the logs that might be useful for us?

```txt
[16:08:06][D][modbus_controller:113]: Received read holding/input registers for device 0x1. FC: 0x3. Start address: 0x0. Number of registers: 0x1.
[16:08:06][D][modbus_controller:124]: Matched register. Address: 0x00. Value type: 0. Register count: 1. Value: 43605.0.
[16:08:06][E][modbus_controller:616]: Invalid data type for modbus number to payload conversation: 0
[16:08:06][D][uart_debug:114]: <<< 01:03:00:00:00:01:84:0A
[16:08:06][D][uart_debug:114]: >>> 01:03:40:21
```

### Additional information

Potential fixes include:
1. Forbid RAW value_type in the YAML schema verification step
2. Permit RAW value_type and fix C++ backend
  * Single user provided register
    * Outstanding question: What benefit does this provides over the U_WORD value_type for single register?
  * Multi-register vector<uint8_t> with full user control
    * Are there performance reasons to avoid std::vector here?
    * Should we provide access to the underlying std::vector backing store by reference, or just copy the contents of  the user provided vector into the backing store
