### ISSUE TITLE
logger component is missing "config" as an option

### ISSUE THREAD

**Issue by VernGraner** [esphome/issues#7028]
### Summary:

`- logger.set_level` does not support the level "CONFIG"
`select:
   -platform: logger` does not offer "VERBOSE" and "VERY_VERBOSE"

### Description:

I was using the component:
```
select: 
  - platform: logger
    name: "Logger Level"
    id: logger_level
```
and noticed the drop down menu offers the following options:
```
NONE
ERROR
WARN
INFO
CONFIG
DEBUG
```
So as I was exploring what each level of logging did, I started to choose them one by one using this code at the top of my yaml:
```
esphome:
  name: "${host_name}"
  friendly_name: "${friendly_name}"
  on_boot: 
    then:
      - logger.set_level:
          level: CONFIG`
```
However, the syntax checker flags "config" and offers this advice:

`Unknown value 'CONFIG', valid options are 'NONE', 'ERROR', 'WARN', 'INFO', 'DEBUG', 'VERBOSE', 'VERY_VERBOSE'.`

So not only does `logger.set` not support the "CONFIG" option, it seems the `select: -platform: logger` does not offer "VERBOSE" and "VERY_VERBOSE" options either.

### Which version of ESPHome has the issue?

2025.4.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.1

### What platform are you using?

ESP32

### Board

ESP32 D1 

### Component causing the issue

logger

### YAML Config

```yaml
esphome:
  name: "${host_name}"
  friendly_name: "${friendly_name}"
  on_boot: 
    then:
      - logger.set_level:
          level: CONFIG`
```

### Anything in the logs that might be useful for us?

```txt

```
