### ISSUE TITLE
ESP32 with BLE Beacon enabled appears in classic Bluetooth device list on Android

### ISSUE THREAD

**Issue by RE-Kovalev** [esphome/issues#7029]
### The problem

Hi,
I'm using ESPHome on an ESP32-S3-WROOM-1, and I've configured it to broadcast only a BLE iBeacon (no Bluetooth proxy or BLE tracker enabled). Here's the relevant configuration:

```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

esp32_ble_beacon:
  type: iBeacon
  uuid: 'f63e5b06-59c4-4bcb-9e16-c5c7a7c6dfd8'
  major: 1
  minor: 2
```

However, even with only esp32_ble_beacon enabled, the ESP32 device still appears in the list of classic Bluetooth (BT) devices on Android — meaning it's visible under system Bluetooth settings (not just BLE scanner apps).

From my understanding, ESPHome does not enable BT Classic unless explicitly configured, so I wouldn't expect the device to be discoverable as a BT Classic device.

Could this be a bug in the way the BLE beacon is initialized under the Arduino framework?

Thanks in advance for your help.

### Which version of ESPHome has the issue?

2025.4.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.2

### What platform are you using?

ESP32

### Board

ESP32-S3-WROOM-1

### Component causing the issue

esp32_ble_beacon

### YAML Config

```yaml
esphome:
  name: esp32-bt-securitron
  friendly_name: Beacon

esp32:
  board: esp32-s3-devkitc-1 # esp32s3box
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_ENABLED: n
      CONFIG_BT_NIMBLE_ENABLED: n
      CONFIG_BT_BLUEDROID_ENABLED: n
      #CONFIG_BTDM_CTRL_MODE_BTDM: n
      #CONFIG_BTDM_CTRL_MODE_BLE_ONLY: y

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MyKey"

ota:
  - platform: esphome
    id: my_ota
    password: "MyOTA"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.204
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eps32-Bt-Securitron"
    password: "MyWIFIPass"

captive_portal:

esp32_ble_beacon:
  type: iBeacon
  uuid: 'MyUUID'
  major: 1
  minor: 2

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0  
      mode: INPUT_PULLUP
      inverted: true  
    name: "Unarm"
    id: unarm_button
```

### Anything in the logs that might be useful for us?

```txt

```
