### ISSUE TITLE
SSD1322 OLED Display does not display properly

### ISSUE THREAD

**Issue by Enrique-Cordoba-Saez** [esphome/issues#7033]
### The problem

![Image](https://github.com/user-attachments/assets/c26d8d84-9719-4d0a-8388-b314cca7856d)

### Which version of ESPHome has the issue?

Unknown

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Unknown

### What platform are you using?

ESP32

### Board

ESP32-WROOM-32

### Component causing the issue

SSD1322 OLED Display

### YAML Config

```yaml
esphome:
  name: mi-esp32
  friendly_name: Mi ESP32
  on_boot:
    priority: -100
    then:
      - lambda: |-
          pinMode(21, OUTPUT); // Fuerza SDA HIGH
          digitalWrite(21, HIGH);
          delay(10);
          for (int i = 0; i < 10; i++) {
            pinMode(22, OUTPUT);
            digitalWrite(22, HIGH);
            delay(2);
            digitalWrite(22, LOW);
            delay(2);
          }
          pinMode(22, INPUT);
          pinMode(21, INPUT); // Devuelve SDA a modo normal

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG
  
api:
  encryption:
    key: "sPNJb0u/fdvDRFGbsv8YlsZ5DTWl154hrsSALoLdce8="
  reboot_timeout: 0s
    
ota:
  platform: esphome
  password: "173f4d052c240e3716de7d5d29a8ffb9"

wifi:
  networks:
    - ssid: "Mi_redecilla"
      password: "okayokay"
    - ssid: "MOVISTAR-WIFI6-9170"
      password: "2MsWFA8c4qXUGb5D6mgj"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mi-Esp32 Fallback Hotspot"
    password: "tqR2WHrjPtTh"

captive_portal:

#------------------------------------------------------------------------------------

i2c:

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  

mqtt:
  broker: "192.168.1.33" # IP del ordenador con Mosquitto
  topic_prefix: "Debug_Una_ESP32"

  on_connect: 
    - delay: 2s
    - mqtt.publish: 
        topic: "hola"
        payload: "hola que tal!"
  birth_message:
    topic: "<-Una_ESP32->/hello"
    payload: "online que flipas"

  on_message:
    - topic: "saludar"
      qos: 0
      then:
        - logger.log: "Me ha llegado un saludito"
        - mqtt.publish:
              topic: "<-Una_ESP32->/respuesta_saludo"
              payload: !lambda 'return "Recibí tu mensaje --> " + x;'

    - topic: "mensaje-mosquitto"
      qos: 0
      then:
        - lambda: |-
            id(ultimo_mensaje) = x.c_str();
            id(pagina_actual) = 11;
            id(ciclado_automatico) = false;

  
#-------------------------------------------------------------------------------------

font:
  - file: "fuentes/Arial Unicode MS/arial unicode ms.otf"
    id: my_font
    size: 20
    bpp: 2

globals:
  - id: pagina_actual
    type: int
    restore_value: no
    initial_value: '1'

  - id: contador
    type: int
    restore_value: no
    initial_value: '0'


  - id: ultimo_mensaje
    type: std::string
    restore_value: no
    initial_value: '"hello world"'


  - id: ciclado_automatico
    type: bool
    restore_value: no
    initial_value: 'true'

#-------------------------------------------------------------------------------------

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32  
      mode: INPUT_PULLUP
      inverted: False
    id: "cambia_pag"
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        - lambda: |-
            id(contador) = 0;
            if (id(pagina_actual) == 10) {  
              id(pagina_actual) = 1;
            } else {
              id(pagina_actual) += 1;
            }
        - logger.log: "Button 'cambia_pag' PRESSED"
    on_release:
      then:
        - logger.log: "Button 'cambia_pag' RELEASED"

  - platform: gpio
    pin: 
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: False
    id: "cambia_ciclico"
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        - lambda: |-
              id(ciclado_automatico) = !id(ciclado_automatico);
        - logger.log: "Button 'cambia_ciclico' PRESSED"
    on_release:
      then:
        - logger.log: "Button 'cambia_ciclico' RELEASED"



button:
  - platform: template
    name: "Cambiar página"
    id: cambia_pag_ha
    on_press:
      then:
        - lambda: |-
            id(contador) = 0;
            if ((id(pagina_actual) == 10) || (id(pagina_actual) == 11)) {  
              id(pagina_actual) = 1;
            } else {
              id(pagina_actual) += 1;
            }


  - platform: template
    name: "Alternar ciclado automático pags"
    id: cambia_ciclico_ha
    on_press:
      then:
        - lambda: |-
              id(ciclado_automatico) = !id(ciclado_automatico);




  - platform: template
    name: "Publicar datos mqtt"
    id: publicar_datos_mqtt
    on_press:
      then:
        - mqtt.publish: 
            topic: "<-Una_ESP32->/Ozono (O3): "
            payload: !lambda |-
                return (String(id(sens_o3).state)).c_str();
        - mqtt.publish: 
            topic: "<-Una_ESP32->/Dioxido de Nitrogeno (NO2): "
            payload: !lambda |-
                return (String(id(sens_NO2).state)).c_str();
        - mqtt.publish: 
            topic: "<-Una_ESP32->/Monoxido de Carbono (CO): "
            payload: !lambda |-
                return (String(id(sens_CO).state)).c_str();
        - mqtt.publish: 
            topic: "<-Una_ESP32->/Hidrogeno del aire (H2): "
            payload: !lambda |-
                return (String(id(sens_h2).state)).c_str();
        - mqtt.publish: 
            topic: "<-Una_ESP32->/Etanol (C2H5-OH): "
            payload: !lambda |-
                return (String(id(sens_C2H5OH).state)).c_str();
        - mqtt.publish: 
            topic: "<-Una_ESP32->/Metano (CH4): "
            payload: !lambda |-
                return (String(id(sens_ch4).state)).c_str();
        - mqtt.publish: 
            topic: "<-Una_ESP32->/Amoniaco (NH3): "
            payload: !lambda |-
                return (String(id(sens_nh3).state)).c_str();
        - mqtt.publish: 
            topic: "<-Una_ESP32->/Dioxido de Carbono (CO2): "
            payload: !lambda |-
                return (String(id(sens_CO2).state)).c_str();
        - mqtt.publish: 
            topic: "<-Una_ESP32->/Temperatura: "
            payload: !lambda |-
                return (String(id(sens_Temp).state)).c_str();
        - mqtt.publish: 
            topic: "<-Una_ESP32->/Humedad: "
            payload: !lambda |-
                return (String(id(sens_Hum).state)).c_str();

#-------------------------------------------------------------------------------------
  
interval:
  - interval: 0.1s
    then:
      - lambda: |-

          if (id(contador) == 25){
              if ((id(pagina_actual) == 10) || (id(pagina_actual) == 11)){  
                id(pagina_actual) = 1;
              } else {
                id(pagina_actual) += 1;
              }
            }

  - interval: 0.1s
    then:
      - lambda: |-

          if (id(ciclado_automatico) == true){
            if (id(contador) == 25){
              id(contador) = 0;
            } else {
              id(contador) += 1;
            }
          }

  - interval: 10ms
    then:
      - lambda: |-
          if (id(pagina_actual) == 11) {
              id(pantalla)->show_page(pagina_mensaje);
          } 

          else if (id(pagina_actual) == 1) {
              id(pantalla)->show_page(pagina_O3);
          } 
          else if (id(pagina_actual) == 2) {
              id(pantalla)->show_page(pagina_CO2); 
          } 
          else if (id(pagina_actual) == 3) {
              id(pantalla)->show_page(pagina_NO2);
          } 
          else if (id(pagina_actual) == 4) {
              id(pantalla)->show_page(pagina_CO);
          } 
          else if (id(pagina_actual) == 5) {
              id(pantalla)->show_page(pagina_H2);
          } 
          else if (id(pagina_actual) == 6) {
              id(pantalla)->show_page(pagina_C2H5OH);
          } 
          else if (id(pagina_actual) == 7) {
              id(pantalla)->show_page(pagina_CH4);
          } 
          else if (id(pagina_actual) == 8) {
              id(pantalla)->show_page(pagina_NH3);
          } 
          else if (id(pagina_actual) == 9) {
              id(pantalla)->show_page(pagina_Temperatura);  
          } 
          else if (id(pagina_actual) == 10) {
              id(pantalla)->show_page(pagina_Humedad);
          }

  - interval: 60s
    then:
      - mqtt.publish: 
          topic: "<-Una_ESP32->/mediciones/Ozono (O3): "
          payload: !lambda |-
              return (String(id(sens_o3).state)).c_str();
      - mqtt.publish: 
          topic: "<-Una_ESP32->/mediciones/Dioxido de Nitrogeno (NO2): "
          payload: !lambda |-
              return (String(id(sens_NO2).state)).c_str();
      - mqtt.publish: 
          topic: "<-Una_ESP32->/mediciones/Monoxido de Carbono (CO): "
          payload: !lambda |-
              return (String(id(sens_CO).state)).c_str();
      - mqtt.publish: 
          topic: "<-Una_ESP32->/mediciones/Hidrogeno del aire (H2): "
          payload: !lambda |-
              return (String(id(sens_h2).state)).c_str();
      - mqtt.publish: 
          topic: "<-Una_ESP32->/mediciones/Etanol (C2H5-OH): "
          payload: !lambda |-
              return (String(id(sens_C2H5OH).state)).c_str();
      - mqtt.publish: 
          topic: "<-Una_ESP32->/mediciones/Metano (CH4): "
          payload: !lambda |-
              return (String(id(sens_ch4).state)).c_str();
      - mqtt.publish: 
          topic: "<-Una_ESP32->/mediciones/Amoniaco (NH3): "
          payload: !lambda |-
              return (String(id(sens_nh3).state)).c_str();
      - mqtt.publish: 
          topic: "<-Una_ESP32->/mediciones/Dioxido de Carbono (CO2): "
          payload: !lambda |-
              return (String(id(sens_CO2).state)).c_str();
      - mqtt.publish: 
          topic: "<-Una_ESP32->/mediciones/Temperatura: "
          payload: !lambda |-
              return (String(id(sens_Temp).state)).c_str();
      - mqtt.publish: 
          topic: "<-Una_ESP32->/mediciones/Humedad: "
          payload: !lambda |-
              return (String(id(sens_Hum).state)).c_str();

#-------------------------------------------------------------------------------------

display:
  - platform: ssd1322_spi
    model: "SSD1322 256x64"
    cs_pin: GPIO05
    reset_pin: GPIO26
    dc_pin: GPIO25
    update_interval: 0.1s
    id: pantalla
    rotation: 180  

    pages:  
      - id: pagina_mensaje
        lambda: |-
          if (id(ultimo_mensaje).empty()) {
              id(ultimo_mensaje) = "Mensaje no disponible";  // Inicializa si está vacío
            }
          it.printf(0, 0, id(my_font), "%s", id(ultimo_mensaje).c_str());

      - id: pagina_O3
        lambda: |-
          it.printf(0, 0, id(my_font), "Ozono: %d ppb", int(id(sens_o3).state));

      - id: pagina_CO2
        lambda: |-
          it.printf(0, 0, id(my_font), "CO2: %d ppm", int(id(sens_CO2).state));
            
      - id: pagina_NO2
        lambda: |-
          it.printf(0, 0, id(my_font), "NO2: %f ppm", id(sens_NO2).state);

            
      - id: pagina_CO
        lambda: |-
          it.printf(0, 0, id(my_font), "Monoxido car.: %f ppm", id(sens_CO).state);

            
      - id: pagina_H2
        lambda: |-
          it.printf(0, 0, id(my_font), "Hidrogeno: %f ppm", id(sens_h2).state);

            
      - id: pagina_C2H5OH
        lambda: |-
          it.printf(0, 0, id(my_font), "Etanol: %f ppm", id(sens_C2H5OH).state);

            
      - id: pagina_CH4
        lambda: |-
          it.printf(0, 0, id(my_font), "Metano: %f ppm", id(sens_ch4).state);

            
      - id: pagina_NH3
        lambda: |-
          it.printf(0, 0, id(my_font), "Amoniaco: %f ppm", id(sens_nh3).state);

      - id: pagina_Temperatura
        lambda: |-
          it.printf(0, 0, id(my_font), "Temperatura: %.2f °C", id(sens_Temp).state);

      - id: pagina_Humedad
        lambda: |-
          it.printf(0, 0, id(my_font), "Humedad: %.2f %%", id(sens_Hum).state);
    
#-------------------------------------------------------------------------------------------

sensor:
  - platform: sen0321
    name: "Ozono"
    id: "sens_o3"
    device_class: "ozone"
    state_class: "measurement"
    accuracy_decimals: 0
    address: 0x73
    update_interval: 10s #SEN0321 comprueba mediciones cada 2s


  - platform: scd4x
    co2:
      name: "Dioxido de Carbono"
      id: "sens_CO2"
    temperature:
      name: "Temperatura"
      id: "sens_Temp"
    humidity:
      name: "Humedad"
      id: "sens_Hum"
    update_interval: 10s


  - platform: mics_4514
    nitrogen_dioxide:
      name: "Dioxido de Nitrogeno"
      id: "sens_NO2"
    carbon_monoxide:
      name: "Monoxido de Carbono"
      id: "sens_CO"
    hydrogen:
      name: "Hidrogeno"
      id: "sens_h2"
    ethanol:
      name: "Etanol"
      id: "sens_C2H5OH"
    methane:
      name: "Metano"
      id: "sens_ch4"
    ammonia:
      name: "amoniaco"
      id: "sens_nh3"    
    update_interval: 10s
```

### Anything in the logs that might be useful for us?

```txt

```
