### ISSUE TITLE
No module named  'esphome.components.output.fan'

### ISSUE THREAD

**Issue by Gregovate** [esphome/issues#7038]
### The problem

INFO ESPHome 2025.5.0
INFO Reading configuration /config/esphome/fridgefanl.yaml...
INFO Unable to import component output.fan: No module named 'esphome.components.output.fan'
Failed config

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2025.5.2 Supervisor 2025.05.1 Operating System 15.2 Frontend 20250516.0

### What platform are you using?

ESP8266

### Board

D1mini

### Component causing the issue

fan:   - platform: output

### YAML Config

```yaml
esphome:
  name: fridgefanl
  friendly_name: FridgeFan L
  comment: Left Fridge Fan 192.168.9.41

esp8266:
  board: d1_mini
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fNOS2XiMCOr3wZyOGHq2RAG3bEzDXDhTehVECq+EMX4="

ota:
  - platform: esphome
    password: "e3895cccfa1f3b16caddfc7d348031a1"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "FridgeFanLeft Fallback Hotspot"
    password: !secret fallback_passwd

captive_portal:
    
one_wire:
  - platform: gpio
    pin: D2

web_server:
  port: 80

sensor:
  - platform: dallas_temp
    address: 0x7b3c01d075d50028
    update_interval: 30s
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"  
    name: "FridgeTempL"

output:
  - platform: esp8266_pwm
    pin: D4
    frequency: 20000 Hz
    id: fridgefanL_speed

fan:
  - platform: output
    output: fridgefanL_speed
    name: "Fridge Fan L Speed"
    id: fridge_fan
    speed_count: 100
    restore_mode: ALWAYS_OFF
```

### Anything in the logs that might be useful for us?

```txt

```
