### ISSUE TITLE
ESPHome 2025.5.0 requires more flash memory in an ESP32, existing programm will not compile anymore

### ISSUE THREAD

**Issue by Buggykiter** [esphome/issues#7041]
### The problem

With the changes to ESPHome 2025.5.0 my ESP32 yaml does not fit into the flash memory anymore. It was working for years up to ESPHome 2025.4.2. The yaml is unchanged, but it seems ESPHome 2025.5.0 needs more space.

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.4

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

I don´t know

### YAML Config

```yaml
esphome:
  name: "esp32-wz"
  friendly_name: 32-wz

esp32:
  board: esp32dev
  framework:
    type: arduino

# Setup MQTT
mqtt:
  broker: homeassistant.local
  username: mqttuser
  password: !secret mqtt_password
  discovery: true
  
# Enable logging
logger:
  #level: verbose

# Enable Home Assistant API
api:
  encryption:
    key: "f09IGnLOTnU5ApBWbkQyGGwBiwcNGJADTaoJdKQZkiU="

# New
ota:
  platform: esphome
  password: "5028bdb7e397b6104ac0c908b9be0bd5"

# Old
# ota:
  # password: "5028bdb7e397b6104ac0c908b9be0bd5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Optional manual IP
  manual_ip:
    static_ip: 192.168.0.54
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Fallback Hotspot"
    password: "38Y0eaYAFdLr"

captive_portal:

# Set a global I²C connection
i2c:
  sda: 21
  scl: 22
  scan: true


esp32_ble_tracker:
  scan_parameters:
    interval: 160ms #the default is 320ms and you want to shorten it, try half
    window: 60ms #the default is 30ms so try doubling it
  id: ESPWZ

sensor:
# Keller Dieter
  - platform: xiaomi_mhoc401
    mac_address: "A4:C1:38:63:DF:2A"
    bindkey: "2436afb8529d1c2b62b78832acefe2af"
    temperature:
      name: "DF2A Temperature"
      filters:
       offset: -0.01
      accuracy_decimals: 1
    humidity:
      name: "DF2A Humidity"
      filters:
       offset: 0.852
      accuracy_decimals: 1
    battery_level:
      name: "DF2A Battery Level"
    # RSSI based on MAC address
  - platform: ble_rssi
    mac_address: A4:C1:38:63:DF:2A
    name: "DF2A Signal Strength"
    accuracy_decimals: 0

# Gästezimmer  
  - platform: xiaomi_mhoc401
    mac_address: "A4:C1:38:CD:19:70"
    bindkey: "7d0ea4ac68d89fea836158e429b4b831"
        #"f3c11f9f2a3f8426f579a593789d163f"
      #"c5b1ea292c49d168b149672868b7f278" 
     #"44c0 09c8 ca04 285b 4cde bea9 d551 88d2"
    temperature:
      name: "1970 Temperature"
      filters:
       offset: 0.123
      accuracy_decimals: 1
    humidity:
      name: "1970 Humidity"
      filters:
       offset: 0.0
      accuracy_decimals: 1
    battery_level:
      name: "1970 Battery Level"
    # RSSI based on MAC address
  - platform: ble_rssi
    mac_address: A4:C1:38:CD:19:70
    name: "1970 Signal Strength"
    accuracy_decimals: 0

# Küche
  - platform: xiaomi_mhoc401
    mac_address: "A4:C1:38:35:4C:D6"
    bindkey: "490b231e060d232d042cc1b2e895feee"
    #"006a25d948f6cac31657f5e247acaf54"
    temperature:
      name: "4CD6 Temperature"
      filters:
       offset: -0.043
      accuracy_decimals: 1
    humidity:
      name: "4CD6 Humidity"
      filters:
       offset: -0.148
      accuracy_decimals: 1
    battery_level:
      name: "4CD6 Battery Level" 
  - platform: ble_rssi
    mac_address: A4:C1:38:35:4C:D6
    name: "4CD6 Signal Strength"
    accuracy_decimals: 0

# Keller
  - platform: xiaomi_mhoc401
    mac_address: "A4:C1:38:13:5B:EC"
    bindkey: "1e4306130599bff49266afc85036d98e"
    #"f069a0740857ec1173c1921b2490039c"
    #"20fd240bb001400221e9c2a2a7002a4a"
    temperature:
      name: "5BEC Temperature"
      filters:
       offset: 0.123
      accuracy_decimals: 1
    humidity:
      name: "5BEC Humidity"
      filters:
       offset: -1.2
      accuracy_decimals: 1
    battery_level:
      name: "5BEC Battery Level" 
  - platform: ble_rssi
    mac_address: A4:C1:38:13:5B:EC
    name: "5BEC Signal Strength"
    accuracy_decimals: 0

# Keller hinten
  - platform: xiaomi_mhoc401
    mac_address: "A4:C1:38:00:52:7E"
    bindkey: "d71ae0e81b584c397978bf112e917f07"
    #"cc137d5a33cf4e289f6344e169b7019c"
    temperature:
      name: "527E Temperature"
      filters:
       offset: 0.057
      accuracy_decimals: 1
    humidity:
      name: "527E Humidity"
      filters:
       offset: -3.981
      accuracy_decimals: 1
    battery_level:
      name: "527E Battery Level" 
  - platform: ble_rssi
    mac_address: A4:C1:38:00:52:7E
    name: "527E Signal Strength"
    accuracy_decimals: 0

# Aussen
  - platform: xiaomi_mhoc401
    mac_address: "A4:C1:38:20:C9:DB"
    bindkey: "641ca0c663c73e3baef79126f230cdf1" 
     #"404b8f9b676060f301c15c45813c8027"
     #"345efb8467e181ccc8f46048dc5dfda8"
    temperature:
      name: "C9DB Temperature"
      accuracy_decimals: 1
    humidity:
      name: "C9DB Humidity"
      accuracy_decimals: 1
    battery_level:
      name: "C9DB Battery Level"
  - platform: ble_rssi
    mac_address: A4:C1:38:20:C9:DB
    name: "C9DB Signal Strength"
    accuracy_decimals: 0 

# Auto
  - platform: xiaomi_mhoc401
    mac_address: "A4:C1:38:F3:7C:C1"
    bindkey: "aae4a65cc1ef1e4b20160e3358611ee2" 
    #"fae847c87cd8973e761698e441b7bffb"
    temperature:
      name: "7CC1 Temperature"
      filters:
       offset: 0.157
      accuracy_decimals: 1
    humidity:
      name: "7CC1 Humidity"
      filters:
       offset: -6.714
      accuracy_decimals: 1
    battery_level:
      name: "7CC1 Battery Level"
  - platform: ble_rssi
    mac_address: A4:C1:38:20:C9:DB
    name: "7CC1 Signal Strength"
    accuracy_decimals: 0 


  - platform: sht3xd
    temperature:
      name: "BLE2 Temperature6"
      filters:
       offset: -0.2
    humidity:
      name: "BLE2 Humidity6"
      filters:
       offset: 6.086
    address: 0x44
    update_interval: 60s

  - platform: wifi_signal
    name: "BLE2 WiFi Signal Sensor6"
    update_interval: 60s
    internal: false
```

### Anything in the logs that might be useful for us?

```txt
log of compilation:

Install esp32-wz.yaml
INFO ESPHome 2025.5.0
INFO Reading configuration /config/esphome/esp32-wz.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-wz (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
|-- Wire @ 2.0.0
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/esp32-wz/src/main.cpp.o
Linking .pioenvs/esp32-wz/firmware.elf
RAM:   [==        ]  16.6% (used 54248 bytes from 327680 bytes)
Error: The program size (1837657 bytes) is greater than maximum allowed (1835008 bytes)
Flash: [==========]  100.1% (used 1837657 bytes from 1835008 bytes)
*** [checkprogsize] Explicit exit, status 1
========================= [FAILED] Took 262.69 seconds =========================
```

### Additional information

Configuration:

Core 2025.4.0
Supervisor 2025.05.1
Operating System 15.2
Frontend 20250401.0
