### ISSUE TITLE
Shorten yaml not contains required project section

### ISSUE THREAD

**Issue by JampireX** [esphome/issues#7044]
### The problem

My configuration located here https://github.com/JampireX/esphome-test/blob/main/ir-remote.yaml
Option _import_full_config_ set to _false_ and _esphome.project_ section is present here, so config will be shorten with _packages_ variable on upload.

When I upload this config to the device, ESPHome dashboard loads shorten yaml with _packages_:
```
substitutions:
  name: ir-remote-######
  friendly_name: IR Remote ######
packages:
  JampireX.esphome-test: github://JampireX/esphome-test/ir-remote.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ################


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

And I get an error (esphome section red underlined, showing error), because _project_ section not present in the shorten yaml.
```
Dashboard import requires the `esphome` -> `project` information to be provided.
```

What am I missing to avoid this problem?

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266
