### ISSUE TITLE
Font size calculated differently since PR #8300

### ISSUE THREAD

**Issue by JonasB2497** [esphome/issues#7046]
### The problem

I am using a waveshare eink display and after an update to esphome I noticed a change in font height. I could narrow it down to PR esphome/esphome#8300 but can't find any obvious issues with the new freetype implementation.

I am using the Gotham Rounded Medium font  (but noticed it with other fonts as well) which is scalable. The MWE produces the following two results. The last character in the string is the one in the font with the lowest descender. The glyphs itself keep the same size but comparing the lines (baseline and height) with the glyph view from a fontviewer (fontdrop.info in my case) the baselines seem to be correct but the height/descender line is way off with the freetype implementation.

### Which version of ESPHome has the issue?

PR esphome/esphome#8300 and newer

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

font

### YAML Config

```yaml
esphome:
  name: eink-test
  friendly_name: eink-test
  on_boot:
    priority: 250
    then:
      - logger.log: "booted"
      - script.execute: eink_refresh

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

script:
  - id: eink_refresh
    mode: restart
    then:
      - delay: 1sec
      - output.turn_on: gpio_eink_pwr
      - component.update: eink
      - delay: 1min
      - output.turn_off: gpio_eink_pwr

output:
  - platform: gpio
    id: gpio_eink_pwr
    pin: GPIO12

font:
  - file: 'fonts/Gotham Rounded Medium.otf'
    id: font_main_144
    size: 144
    glyphs: [
      '!"%()+=,-_.:°/?0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ abcdefghijklmnopqrstuvwxyzäöü',
      "\u0218"
    ]



spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

external_components:
  # - source: github://pr#8261
  #   components: [font]
  - source: github://pr#8300
    components: [font]

display:
  - platform: waveshare_epaper
    id: eink
    cs_pin: GPIO33
    dc_pin: GPIO27
    busy_pin:
      number: GPIO25
      inverted: true
    reset_pin: GPIO26
    model: 7.50in-bV3
    update_interval: never
    rotation: 180
    lambda: |-
      it.print(0, 0, id(font_main_144), "ÄAäayg\u0218");
      int height = id(font_main_144).get_height();
      it.line(0, height, it.get_width(), height);
      height = id(font_main_144).get_baseline();
      it.line(0, height, it.get_width(), height);
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

using esphome/esphome#8261 ![Image](https://github.com/user-attachments/assets/e7367465-8be3-4637-a17e-b5a4f564dee9)

using esphome/esphome#8300 ![Image](https://github.com/user-attachments/assets/c4c2aecc-2ad8-41bc-b1cf-7ff7043c4a0d)

![Image](https://github.com/user-attachments/assets/da07c277-7488-45c9-ac31-2982e00da104)
