### ISSUE TITLE
Voice remote with adafruit_feather_esp32_v2 compile error with latest esphome update

### ISSUE THREAD

**Issue by tonyis49** [esphome/issues#7048]
### The problem

Hi,
I just updated to the latest esphome 2025.5.0 and my devices using an adafruit_feather_esp32_v2 board will not compile.

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.05.1

### What platform are you using?

ESP32

### Board

adafruit_feather_esp32_v2

### YAML Config

```yaml
esphome:
  name: voice-remote-2
  friendly_name: voice-remote-2
  on_boot:
#    priority: 100
    then:
      - script.execute: sleep_routine
      - switch.turn_on: neopwr
      - script.execute: wifi_check
      - output.turn_on: Mic_Power
      - output.turn_on: Amp_Power       

esp32:
  board: adafruit_feather_esp32_v2
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "+pfzjQSJQJXnnnDjyZbYYMoq84r55Z0o+Ymrj10e9oY="

ota:
  platform: esphome
  password: "e68c611a07dc1b02d85daa1104582547"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  power_save_mode: LIGHT  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Voice-Remote Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

button:
  - platform: restart
    id: restart_device
    name: " Restart"   

switch:
  - platform: gpio
    pin: GPIO2
    id: neopwr
    internal: true

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    chipset: WS2812
    rmt_channel: 0
    id: neopixel
    name: neopixel
    pin: GPIO0
    num_leds: 1
    default_transition_length: 0s #you can lengthen this to soften the LED transitions
    effects:
      - pulse:
          name: "extra_slow_pulse"
          transition_length: 800ms
          update_interval: 800ms
          min_brightness: 0%
          max_brightness: 30%
      - pulse:
          name: "slow_pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "fast_pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

i2s_audio:
  - id: i2s_mic
    i2s_lrclk_pin: GPIO15
    i2s_bclk_pin: GPIO33
  - id: i2s_amp
    i2s_lrclk_pin: GPIO21
    i2s_bclk_pin: GPIO5

microphone:
  - platform: i2s_audio
    id: feather_microphone
    adc_type: external 
    i2s_audio_id: i2s_mic 
    i2s_din_pin: GPIO27
    pdm: false

#speaker: #media player won't work currently with Piper, have to use speaker component. Media player works with cloud.
media_player:
  - platform: i2s_audio
    name: " Media Player"
    id: media_out
    dac_type: external
    i2s_audio_id: i2s_amp
    i2s_dout_pin: GPIO19
    mode: mono

sensor:
  - platform: adc
    pin: 35
    name: "Battery Voltage"
    update_interval: 20s
    attenuation: 11db #required
    filters:
     - multiply: 2.0
     - offset: 0.00 #trim reading by adjusting this value

output:
  - platform: gpio
    pin: GPIO4
    id: Amp_Power
  - platform: gpio
    pin: GPIO32
    id: Mic_Power

voice_assistant:
  microphone: feather_microphone
  media_player: media_out
  on_start:
    - script.stop: wifi_check #this script just updates the notification LED for wifi status. It's diabled during voice assist so it doesn't interfere with the indicator LED status during VA use
    - light.turn_on: 
        id: neopixel
        color_brightness: 25%
        red: 0%
        green: 0%
        blue: 50%
    - output.turn_on: Mic_Power #turn on mic power
    - output.turn_on: Amp_Power #enable MAX98357 power

  on_stt_vad_start:
    - light.turn_on: 
        id: neopixel
        color_brightness: 50%
        red: 20%
        green: 100%
        blue: 90%
        effect: slow_pulse 

  on_tts_start:
    - light.turn_on: 
        id: neopixel
        color_brightness: 50%
        red: 100%
        green: 90%
        blue: 20% 

  on_tts_end:
    - light.turn_on: 
        id: neopixel
        color_brightness: 50%
        red: 100%
        green: 90%
        blue: 20%
  
  on_end:
    - delay: 1s
    - wait_until:
        not:
          media_player.is_playing:
    - delay: 3s         
    - light.turn_off: neopixel
    - script.execute: wifi_check
    - output.turn_off: Mic_Power #power off Mic when not used
    - output.turn_off: Amp_Power #uses Amp SD pin to shut off amp when not being used.
  
  on_error: 
    - light.turn_on: 
        id: neopixel
        color_brightness: 100%
        red: 100%
        green: 0%
        blue: 0%
    - delay: 1s
    - light.turn_off: neopixel #set status LED to blank, to clear VA status and prep for Wifi check
    - script.execute: wifi_check

binary_sensor:

  - platform: gpio
    pin:
      number: GPIO14
      allow_other_uses: true
      inverted: False
    name: Button
    id: remote_button
    filters:
      - delayed_on: 10ms #debounce time

    on_multi_click:
      - timing:
          - ON FOR AT LEAST 350ms
        then:
          - voice_assistant.start:
      - timing:
          - ON FOR AT LEAST 350ms
          - OFF FOR AT LEAST 10ms
        then:
#          - voice_assistant.stop:
          - output.turn_off: Mic_Power          
          
    on_press: 
      then:
        - script.stop: sleep_routine #this resets the sleep timer every time the button is pressed
        - logger.log: "sleep reset"
        - script.execute: sleep_routine

deep_sleep:
  id: deep_sleep_1
  sleep_duration: 24h # how long to sleep before rewaking
  esp32_ext1_wakeup: #regular GPIO wakeup had some issues on some boards. Ext1 seems to work on everything.
    pins:
      number: GPIO14
      allow_other_uses: true
    mode: ANY_HIGH

script:
  - id: sleep_routine
    then:
    - logger.log: "sleep timer initiated"
    - delay: 180s  # sleep timeout length, adjust as necessary, longer time = device stays awake longer
    - switch.turn_off: neopwr
    - logger.log: "entering sleep"
    - deep_sleep.enter: deep_sleep_1

  - id: wifi_check
    then:
    - light.turn_on: 
        id: neopixel
        color_brightness: 25%
        red: 100%
        green: 100%
        blue: 100%
        effect: fast_pulse

    - wait_until:
       wifi.connected:

    - media_player.volume_set:
        volume: 50% 
    - output.turn_on: Amp_Power
    - media_player.play_media:
        id: media_out
        media_url: 'http://192.168.178.5:8123/local/click.mp3'    
    - delay: 1s
    - wait_until:
        not:
          media_player.is_playing: media_out    

    - media_player.volume_set:
        volume: 90% 

    - light.turn_on: 
        id: neopixel
        color_brightness: 25%
        red: 0%
        green: 50%
        blue: 0%
        effect: none
```

### Anything in the logs that might be useful for us?

```txt
compiling .pioenvs/voice-remote-2/src/esphome/components/api/subscribe_state.cpp.o
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:29,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:79,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:36,
                 from src/esphome/core/macros.h:7,
                 from src/esphome/core/defines.h:2,
                 from src/esphome/components/api/list_entities.h:3,
                 from src/esphome/components/api/list_entities.cpp:1:
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected identifier before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected '}' before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
In file included from src/esphome/components/api/list_entities.h:6,
                 from src/esphome/components/api/list_entities.cpp:1:
src/esphome/core/component_iterator.h:96:28: note: to match this '{'
   enum class IteratorState {
                            ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:29,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:79,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:36,
                 from src/esphome/core/macros.h:7,
                 from src/esphome/core/defines.h:2,
                 from src/esphome/components/api/list_entities.h:3,
                 from src/esphome/components/api/list_entities.cpp:1:
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected unqualified-id before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
In file included from src/esphome/components/api/list_entities.h:6,
                 from src/esphome/components/api/list_entities.cpp:1:
src/esphome/core/component_iterator.h:169:12: error: 'IteratorState' has not been declared
   } state_{IteratorState::NONE};
            ^~~~~~~~~~~~~
src/esphome/core/component_iterator.h:169:31: error: no matching function for call to 'esphome::ComponentIterator::ComponentIterator(<brace-enclosed initializer list>)'
   } state_{IteratorState::NONE};
                               ^
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator()'
 class ComponentIterator {
       ^~~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:19:7: note:   candidate expects 0 arguments, 1 provided
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator(const esphome::ComponentIterator&)'
src/esphome/core/component_iterator.h:19:7: note:   conversion of argument 1 would be ill-formed:
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator(esphome::ComponentIterator&&)'
src/esphome/core/component_iterator.h:19:7: note:   conversion of argument 1 would be ill-formed:
src/esphome/core/component_iterator.h:169:5: error: cannot declare variable 'esphome::state_' to be of abstract type 'esphome::ComponentIterator'
   } state_{IteratorState::NONE};
     ^~~~~~
src/esphome/core/component_iterator.h:19:7: note:   because the following virtual functions are pure within 'esphome::ComponentIterator':
 class ComponentIterator {
       ^~~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:25:16: note: 	'virtual bool esphome::ComponentIterator::on_binary_sensor(esphome::binary_sensor::BinarySensor*)'
   virtual bool on_binary_sensor(binary_sensor::BinarySensor *binary_sensor) = 0;
                ^~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:34:16: note: 	'virtual bool esphome::ComponentIterator::on_light(esphome::light::LightState*)'
   virtual bool on_light(light::LightState *light) = 0;
                ^~~~~~~~
src/esphome/core/component_iterator.h:37:16: note: 	'virtual bool esphome::ComponentIterator::on_sensor(esphome::sensor::Sensor*)'
   virtual bool on_sensor(sensor::Sensor *sensor) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:40:16: note: 	'virtual bool esphome::ComponentIterator::on_switch(esphome::switch_::Switch*)'
   virtual bool on_switch(switch_::Switch *a_switch) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:43:16: note: 	'virtual bool esphome::ComponentIterator::on_button(esphome::button::Button*)'
   virtual bool on_button(button::Button *button) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:174:1: error: expected declaration before '}' token
 }  // namespace esphome
 ^
*** [.pioenvs/voice-remote-2/src/esphome/components/api/list_entities.cpp.o] Error 1
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:29,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:79,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:36,
                 from src/esphome/core/macros.h:7,
                 from src/esphome/core/defines.h:2,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome/components/api/api_connection.cpp:1:
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected identifier before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected '}' before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
In file included from src/esphome/components/api/list_entities.h:6,
                 from src/esphome/components/api/api_server.h:13,
                 from src/esphome/components/api/api_connection.h:8,
                 from src/esphome/components/api/api_connection.cpp:1:
src/esphome/core/component_iterator.h:96:28: note: to match this '{'
   enum class IteratorState {
                            ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:29,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:79,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:36,
                 from src/esphome/core/macros.h:7,
                 from src/esphome/core/defines.h:2,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome/components/api/api_connection.cpp:1:
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected unqualified-id before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
In file included from src/esphome/components/api/list_entities.h:6,
                 from src/esphome/components/api/api_server.h:13,
                 from src/esphome/components/api/api_connection.h:8,
                 from src/esphome/components/api/api_connection.cpp:1:
src/esphome/core/component_iterator.h:169:12: error: 'IteratorState' has not been declared
   } state_{IteratorState::NONE};
            ^~~~~~~~~~~~~
src/esphome/core/component_iterator.h:169:31: error: no matching function for call to 'esphome::ComponentIterator::ComponentIterator(<brace-enclosed initializer list>)'
   } state_{IteratorState::NONE};
                               ^
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator()'
 class ComponentIterator {
       ^~~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:19:7: note:   candidate expects 0 arguments, 1 provided
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator(const esphome::ComponentIterator&)'
src/esphome/core/component_iterator.h:19:7: note:   conversion of argument 1 would be ill-formed:
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator(esphome::ComponentIterator&&)'
src/esphome/core/component_iterator.h:19:7: note:   conversion of argument 1 would be ill-formed:
src/esphome/core/component_iterator.h:169:5: error: cannot declare variable 'esphome::state_' to be of abstract type 'esphome::ComponentIterator'
   } state_{IteratorState::NONE};
     ^~~~~~
src/esphome/core/component_iterator.h:19:7: note:   because the following virtual functions are pure within 'esphome::ComponentIterator':
 class ComponentIterator {
       ^~~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:25:16: note: 	'virtual bool esphome::ComponentIterator::on_binary_sensor(esphome::binary_sensor::BinarySensor*)'
   virtual bool on_binary_sensor(binary_sensor::BinarySensor *binary_sensor) = 0;
                ^~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:34:16: note: 	'virtual bool esphome::ComponentIterator::on_light(esphome::light::LightState*)'
   virtual bool on_light(light::LightState *light) = 0;
                ^~~~~~~~
src/esphome/core/component_iterator.h:37:16: note: 	'virtual bool esphome::ComponentIterator::on_sensor(esphome::sensor::Sensor*)'
   virtual bool on_sensor(sensor::Sensor *sensor) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:40:16: note: 	'virtual bool esphome::ComponentIterator::on_switch(esphome::switch_::Switch*)'
   virtual bool on_switch(switch_::Switch *a_switch) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:43:16: note: 	'virtual bool esphome::ComponentIterator::on_button(esphome::button::Button*)'
   virtual bool on_button(button::Button *button) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:174:1: error: expected declaration before '}' token
 }  // namespace esphome
 ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:29,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:79,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:36,
                 from src/esphome/core/macros.h:7,
                 from src/esphome/core/defines.h:2,
                 from src/esphome/components/api/api_server.h:3,
                 from src/esphome/components/api/api_server.cpp:1:
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected identifier before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected '}' before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
In file included from src/esphome/components/api/list_entities.h:6,
                 from src/esphome/components/api/api_server.h:13,
                 from src/esphome/components/api/api_server.cpp:1:
src/esphome/core/component_iterator.h:96:28: note: to match this '{'
   enum class IteratorState {
                            ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:29,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:79,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:36,
                 from src/esphome/core/macros.h:7,
                 from src/esphome/core/defines.h:2,
                 from src/esphome/components/api/api_server.h:3,
                 from src/esphome/components/api/api_server.cpp:1:
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected unqualified-id before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
In file included from src/esphome/components/api/list_entities.h:6,
                 from src/esphome/components/api/api_server.h:13,
                 from src/esphome/components/api/api_server.cpp:1:
src/esphome/core/component_iterator.h:169:12: error: 'IteratorState' has not been declared
   } state_{IteratorState::NONE};
            ^~~~~~~~~~~~~
src/esphome/core/component_iterator.h:169:31: error: no matching function for call to 'esphome::ComponentIterator::ComponentIterator(<brace-enclosed initializer list>)'
   } state_{IteratorState::NONE};
                               ^
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator()'
 class ComponentIterator {
       ^~~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:19:7: note:   candidate expects 0 arguments, 1 provided
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator(const esphome::ComponentIterator&)'
src/esphome/core/component_iterator.h:19:7: note:   conversion of argument 1 would be ill-formed:
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator(esphome::ComponentIterator&&)'
src/esphome/core/component_iterator.h:19:7: note:   conversion of argument 1 would be ill-formed:
src/esphome/core/component_iterator.h:169:5: error: cannot declare variable 'esphome::state_' to be of abstract type 'esphome::ComponentIterator'
   } state_{IteratorState::NONE};
     ^~~~~~
src/esphome/core/component_iterator.h:19:7: note:   because the following virtual functions are pure within 'esphome::ComponentIterator':
 class ComponentIterator {
       ^~~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:25:16: note: 	'virtual bool esphome::ComponentIterator::on_binary_sensor(esphome::binary_sensor::BinarySensor*)'
   virtual bool on_binary_sensor(binary_sensor::BinarySensor *binary_sensor) = 0;
                ^~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:34:16: note: 	'virtual bool esphome::ComponentIterator::on_light(esphome::light::LightState*)'
   virtual bool on_light(light::LightState *light) = 0;
                ^~~~~~~~
src/esphome/core/component_iterator.h:37:16: note: 	'virtual bool esphome::ComponentIterator::on_sensor(esphome::sensor::Sensor*)'
   virtual bool on_sensor(sensor::Sensor *sensor) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:40:16: note: 	'virtual bool esphome::ComponentIterator::on_switch(esphome::switch_::Switch*)'
   virtual bool on_switch(switch_::Switch *a_switch) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:43:16: note: 	'virtual bool esphome::ComponentIterator::on_button(esphome::button::Button*)'
   virtual bool on_button(button::Button *button) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:174:1: error: expected declaration before '}' token
 }  // namespace esphome
 ^
*** [.pioenvs/voice-remote-2/src/esphome/components/api/api_connection.cpp.o] Error 1
*** [.pioenvs/voice-remote-2/src/esphome/components/api/api_server.cpp.o] Error 1
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:29,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:79,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:36,
                 from src/esphome/core/macros.h:7,
                 from src/esphome/core/defines.h:2,
                 from src/esphome/components/api/subscribe_state.h:3,
                 from src/esphome/components/api/subscribe_state.cpp:1:
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected identifier before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected '}' before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
In file included from src/esphome/components/api/subscribe_state.h:6,
                 from src/esphome/components/api/subscribe_state.cpp:1:
src/esphome/core/component_iterator.h:96:28: note: to match this '{'
   enum class IteratorState {
                            ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-gpio.h:29,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal.h:79,
                 from /data/cache/platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:36,
                 from src/esphome/core/macros.h:7,
                 from src/esphome/core/defines.h:2,
                 from src/esphome/components/api/subscribe_state.h:3,
                 from src/esphome/components/api/subscribe_state.cpp:1:
/data/cache/platformio/packages/framework-arduinoespressif32/variants/adafruit_feather_esp32_v2/pins_arduino.h:51:16: error: expected unqualified-id before numeric constant
 #define BUTTON 38
                ^~
src/esphome/core/component_iterator.h:118:5: note: in expansion of macro 'BUTTON'
     BUTTON,
     ^~~~~~
In file included from src/esphome/components/api/subscribe_state.h:6,
                 from src/esphome/components/api/subscribe_state.cpp:1:
src/esphome/core/component_iterator.h:169:12: error: 'IteratorState' has not been declared
   } state_{IteratorState::NONE};
            ^~~~~~~~~~~~~
src/esphome/core/component_iterator.h:169:31: error: no matching function for call to 'esphome::ComponentIterator::ComponentIterator(<brace-enclosed initializer list>)'
   } state_{IteratorState::NONE};
                               ^
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator()'
 class ComponentIterator {
       ^~~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:19:7: note:   candidate expects 0 arguments, 1 provided
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator(const esphome::ComponentIterator&)'
src/esphome/core/component_iterator.h:19:7: note:   conversion of argument 1 would be ill-formed:
src/esphome/core/component_iterator.h:19:7: note: candidate: 'constexpr esphome::ComponentIterator::ComponentIterator(esphome::ComponentIterator&&)'
src/esphome/core/component_iterator.h:19:7: note:   conversion of argument 1 would be ill-formed:
src/esphome/core/component_iterator.h:169:5: error: cannot declare variable 'esphome::state_' to be of abstract type 'esphome::ComponentIterator'
   } state_{IteratorState::NONE};
     ^~~~~~
src/esphome/core/component_iterator.h:19:7: note:   because the following virtual functions are pure within 'esphome::ComponentIterator':
 class ComponentIterator {
       ^~~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:25:16: note: 	'virtual bool esphome::ComponentIterator::on_binary_sensor(esphome::binary_sensor::BinarySensor*)'
   virtual bool on_binary_sensor(binary_sensor::BinarySensor *binary_sensor) = 0;
                ^~~~~~~~~~~~~~~~
src/esphome/core/component_iterator.h:34:16: note: 	'virtual bool esphome::ComponentIterator::on_light(esphome::light::LightState*)'
   virtual bool on_light(light::LightState *light) = 0;
                ^~~~~~~~
src/esphome/core/component_iterator.h:37:16: note: 	'virtual bool esphome::ComponentIterator::on_sensor(esphome::sensor::Sensor*)'
   virtual bool on_sensor(sensor::Sensor *sensor) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:40:16: note: 	'virtual bool esphome::ComponentIterator::on_switch(esphome::switch_::Switch*)'
   virtual bool on_switch(switch_::Switch *a_switch) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:43:16: note: 	'virtual bool esphome::ComponentIterator::on_button(esphome::button::Button*)'
   virtual bool on_button(button::Button *button) = 0;
                ^~~~~~~~~
src/esphome/core/component_iterator.h:174:1: error: expected declaration before '}' token
 }  // namespace esphome
 ^
*** [.pioenvs/voice-remote-2/src/esphome/components/api/subscribe_state.cpp.o] Error 1
========================== [FAILED] Took 4.00 seconds ==========================
```
