### ISSUE TITLE
DFplayer platform falsely deems playback to be finished when using "loop: true" with "dfplayer.play" action

### ISSUE THREAD

**Issue by blanknam3d** [esphome/issues#7051]
### The problem

When using the `dfplayer` platform, if `loop` is set to `true`, every time the playback restarts in the loop will trigger `on_finished_playback`.

As for how exactly this becomes a problem: I use a SPDT relay to physically switch my audio output between the DAC attached to the ESP32 & the DFplayer Mini. For a simple looping alarm sound button, I use the following:
```
  - platform: template
    id: sndalarm
    name: Sound Alarm
    icon: "mdi:alarm-light"
    on_press:
      - then:
          - switch.turn_on: ESP32_relay
      - then:
          - dfplayer.play:
              file: 1
              loop: true
```
I then use the following for the `dfplayer` platform:
```
dfplayer:
  uart_id: dfsfx
  on_finished_playback: 
    then:
      - switch.turn_off: ESP32_relay
      - if: 
          condition:
            media_player.is_playing
          then:
            - logger.log: "DFplayer is no longer active, restoring output to media_player"
```
What I expect to happen is if `dfplayer.play` is executed with `loop: true` set, the `on_finished_playback` trigger doesn't get fired until `dfplayer.stop` is executed. What actually happens is that every time the DFplayer reaches the end of the file it is playing, `on_finished_playback` is fired & shuts off the relay, even though the DFplayer has restarted playback & is therefore still playing audio.

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.2

### What platform are you using?

ESP32

### Board

ESP32 Relay x1

### Component causing the issue

dfplayer

### YAML Config

```yaml
esphome:
  name: littleguy
  friendly_name: littleguy
  on_boot:
    - priority: 200.0
      then:
          - switch.turn_on: ESP32_relay
          - dfplayer.set_volume: 24
          - delay: 0.1s
          - dfplayer.play:
              file: 11
              loop: False

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED"

ota:
  - platform: esphome
    password: "REDACTED"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Littleguy Fallback Hotspot"
    password: "REDACTED"

captive_portal:

light:
  - platform: status_led
    name: "Status LED"
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO23
      inverted: False
switch:
  - platform: gpio
    name: Audio Output Relay
    pin: GPIO16
    id: ESP32_relay
    entity_category: diagnostic

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    name: Button
    filters:
      - invert
      - delayed_on_off: 50ms
    on_click:
      min_length: 6s 
      max_length: 12s
      then:
        - button.press: restartHASSL
        

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO27
    i2s_bclk_pin: GPIO26

speaker:
  - platform: i2s_audio
    id: uda1334a
    dac_type: external
    i2s_dout_pin: 
      number: GPIO25
      allow_other_uses: true
    channel: mono

media_player:
  - platform: i2s_audio
    id: media_out
    name: Littleguy Media Player
    dac_type: external
    i2s_dout_pin: 
      number: GPIO25
      allow_other_uses: true
    mode: stereo
    on_play:
      - logger.log: "Playback started!"
      - if:
          condition:
            dfplayer.is_playing
          then:
            - logger.log: 'DFplayer is active, media player output is therefore disconnected'

uart:
  id: dfsfx
  tx_pin: GPIO13
  rx_pin: GPIO14
  baud_rate: 9600

number:
  - platform: template
    id: dfplayer_vol
    name: DFplayer Volume
    entity_category: config
    mode: slider
    max_value: 30
    min_value: 12
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      - dfplayer.set_volume: !lambda 'return x;'


dfplayer:
  uart_id: dfsfx
  on_finished_playback: 
    then:
      - switch.turn_off: ESP32_relay
      - if: 
          condition:
            media_player.is_playing
          then:
            - logger.log: "DFplayer is no longer active, restoring output to media_player"

button: 
  - platform: restart
    id: restartHASSL
    name: "Restart littleguy"
    icon: "mdi:restart"
    entity_category: diagnostic
  - platform: shutdown
    id: shutdownHASSL
    name: "Shutdown littleguy"
    icon: "mdi:power-off"
    entity_category: diagnostic
  - platform: safe_mode
    name: "Restart in Safe Mode"
    icon: "mdi:restart-alert"
    entity_category: diagnostic
  - platform: template
    id: sndalarm
    name: Sound Alarm
    icon: "mdi:alarm-light"
    on_press:
      - then:
          - switch.turn_on: ESP32_relay
      - then:
          - dfplayer.play:
              file: 1
              loop: true
  - platform: template
    id: sndalarm2
    name: Alarm Alt
    icon: "mdi:alarm-light"
    on_press:
      - then:
          - switch.turn_on: ESP32_relay
      - then:
          - dfplayer.play:
              file: 2
              loop: true
  - platform: template
    id: ffding
    name: Positive Ding
    icon: "mdi:bell-check"
    on_press:
      - then:
          - switch.turn_on: ESP32_relay
      - then:
          - dfplayer.play:
              file: 3
              loop: false
  - platform: template
    id: attnbell
    name: Attention Bell
    icon: "mdi:bell-ring"
    on_press:
      - then:
          - switch.turn_on: ESP32_relay
      - then:
          - dfplayer.play:
              file: 4
              loop: false
  - platform: template
    id: shutup
    name: Shut Up
    icon: "mdi:account-cancel"
    on_press:
      - then:
          - switch.turn_on: ESP32_relay
      - then:
          - dfplayer.play:
              file: 5
              loop: false
  - platform: template
    id: xpexclaim
    name: Exclamation
    icon: "mdi:exclamation"
    on_press:
      - then:
          - switch.turn_on: ESP32_relay
      - then:
          - dfplayer.play:
              file: 6
              loop: false
  - platform: template
    id: test1
    name: DFplayer Test 1
    entity_category: diagnostic
    icon: "mdi:test-tube"
    on_press:
      - then:
          - switch.turn_on: ESP32_relay
      - then:
          - dfplayer.play:
              file: 8
              loop: false
  - platform: template
    id: test2
    name: DFplayer Test 2
    entity_category: diagnostic
    icon: "mdi:test-tube"
    on_press:
      - then:
          - switch.turn_on: ESP32_relay
      - then:
          - dfplayer.play:
              file: 9
              loop: false
  - platform: template
    id: incorrect
    name: Incorrect
    icon: "mdi:cancel"
    on_press:
      - then:
          - switch.turn_on: ESP32_relay
      - then:
          - dfplayer.play:
              file: 10
              loop: false
  - platform: template
    id: dfplayer_reset
    name: Reset DFplayer Module
    entity_category: diagnostic
    icon: "mdi:reload"
    on_press:
      - then:
          - dfplayer.reset
  - platform: template
    id: dfplayer_stop
    name: Stop DFplayer
    icon: "mdi:octagon"
    on_press:
      - then:
          - dfplayer.stop
      - then:
          - switch.turn_off: ESP32_relay
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

This seems to be agnostic of the currently-running version of Home Assistant - tested with multiple different versions, still exhibits the same behavior across them.
