### ISSUE TITLE
Compile error with fastled component

### ISSUE THREAD

**Issue by 7h30n3** [esphome/issues#7052]
### The problem

After upgrading ESPHome from 2025.4.0 to 2025.5.0 the command `esphome compile` throws an error using the config below. 

After manually setting the fastLED library version to 3.7.2 via:
```yaml
esphome:
  libraries:
    - FastLED=https://github.com/FastLED/FastLED.git#3.7.2
```
... the config compiles again without error. The version 3.7.2. was the latest working version. Beginning with 3.7.3 I got the error. Maybe someone with more knowledge can drawn conclusions from this:
https://github.com/FastLED/FastLED/compare/3.7.2...3.7.3

I don't know if this is an issue with ESPHome or fastLED, but I think this PR is related: https://github.com/esphome/esphome/pull/8402

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2025.4.4

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

fastled

### YAML Config

```yaml
esphome:
  name: test_device

esp32:
  board: esp32dev

wifi:

api:

logger:
  level: none
  baud_rate: 0

ota:
  platform: esphome

light:
  - platform: fastled_spi
    internal: true
    chipset: WS2801
    data_pin: 32
    clock_pin: 33
    num_leds: 32
    rgb_order: RBG
```

### Anything in the logs that might be useful for us?

```txt
*** [.pioenvs\esp32_2\src\main.cpp.o] Error 1
```

### Additional information

One side note. Since ESPHome uses a much more up-to-date version of fastLED, is the warning about ESP-IDF still true?
See: https://esphome.io/components/light/fastled
