### ISSUE TITLE
ESP-IDF: sdkconfig_options for USB Host (e.g., CONFIG_USB_HOST_ENABLE) not applied for ESP32-S3 on version 2024.6.1 and later (macOS)

### ISSUE THREAD

**Issue by wifijt** [esphome/issues#7054]
### The problem

I am trying to enable USB Host and HID Host support for an ESP32-S3 project using the esp-idf framework to eventually include and use usb/hid_host.h in a custom component. I am attempting to set CONFIG_USB_HOST_ENABLE and CONFIG_HID_HOST_ENABLE via the sdkconfig_options: in my ESPHome YAML.

Despite trying various value formats (boolean true, string "y", string "true") and performing "Clean Build Files" each time, these options are consistently NOT appearing in the generated sdkconfig file located in the build directory (.esphome/build/DEVICE_NAME/esp-idf-build/sdkconfig).

This results in the ESP-IDF build not being configured for USB Host/HID support, leading to a C++ compilation error when trying to include the necessary header:
fatal error: usb/hid_host.h: No such file or directory

### Which version of ESPHome has the issue?

2024.6.1

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

adafruit_feather_esp32s3

### Component causing the issue

USB HID

### YAML Config

```yaml
esphome:
  name: usbhidincludetestminimal

esp32:
  board: adafruit_feather_esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      # --- Provide values as STRINGS, specifically "y" ---
      CONFIG_USB_HOST_ENABLE: "y"
      CONFIG_HID_HOST_ENABLE: "y"
```

### Anything in the logs that might be useful for us?

```txt
The CONFIG_USB_HOST_ENABLE and CONFIG_HID_HOST_ENABLE directives are consistently missing (or not set to y) in the generated sdkconfig file (I can provide the full generated sdkconfig if needed).

The C++ compiler fails with fatal error: usb/hid_host.h: No such file or directory because the usb component with HID host features is not being built by ESP-IDF.
```

### Additional information

I have done clean build with each test - I also tried this with ESPHome 2025.5.0 with the same error

**Comment by swoboda1337** [comment]
Maybe this helps: https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-reference/peripherals/usb_host.html

I dont think those configs exist.

**Comment by swoboda1337** [comment]
Also this: https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/hid
and: https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/usb_host_lib

**Comment by swoboda1337** [comment]
If you want to include `usb/hid_host.h` you need to include the idf component: https://github.com/espressif/esp-usb/blob/master/host/class/hid/usb_host_hid/include/usb/hid_host.h

Something like:
```
esp32:
  framework:
    type: esp-idf
    components:
      - name: "usb_host_hid"
        source: "github://espressif/esp-usb"
        path: "host/class/hid/usb_host_hid"
```
