### ISSUE TITLE
ESPHome fails to resolve esp_adc_cal in Git-less ESP-IDF environment (ADF pipeline + CONFIG_ADC_CALIBRATION_ENABLED=y)

### ISSUE THREAD

**Issue by wjohnson2250** [esphome/issues#7055]
### The problem

📋 Overview

When building an ESPHome firmware with the esp-idf framework and Audio Development Framework (ADF) components (e.g. adf_pipeline, i2s_audio, db_sound_meter), the build fails with a CMake error:
```
CMake Error: Failed to resolve component 'esp_adc_cal'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
This occurs even when CONFIG_ADC_CALIBRATION_ENABLED=y is explicitly set in sdkconfig_options.

🗒️ Configuration Context

ESPHome version: 2025.5.0 (ESPHome Add-On)

Framework: esp-idf

ADF Components used: adf_pipeline, i2s_audio, db_sound_meter (custom sink)

Platform: Home Assistant add-on, building inside /data/ (no Git repo present)

YAML fragment:
```yaml
esp32:
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ADC_CALIBRATION_ENABLED: y

external_components:
  - source:
      type: local
      path: /config/esphome_audio_sink/components
    components: [adf_pipeline, i2s_audio, db_sound_meter]
```
❗ Error Summary

The build environment is offline and Git-less (no .git directory under /data/)

ESP-IDF ≥ v5 removed esp_adc_cal as a standalone component — its functionality now lives inside esp_adc

However, ESPHome or its components still reference esp_adc_cal.h

With CONFIG_ADC_CALIBRATION_ENABLED enabled, the build tries to resolve the deprecated esp_adc_cal as a component — fails

The Git error is benign but reveals the fallback logic: IDF tries and fails to fetch missing components from registry

🔍 Root Cause

In ESP-IDF 5.x, the calibration APIs (esp_adc_cal_xxx) are deprecated and moved into esp_adc

If ESPHome or ADF components reference those APIs, the build must explicitly include the esp_adc component

In a Git-less container (like ESPHome Builder or HA add-on), the fallback resolver cannot find esp_adc_cal, and no Git metadata exists to bypass that

✅ Desired Outcome

Make ESPHome (or ADF platform logic) compatible with ESP-IDF 5.x by ensuring esp_adc is included when CONFIG_ADC_CALIBRATION_ENABLED=y is set

Provide a portable solution for users building in Git-less environments like the Home Assistant add-on

🔧 Workarounds Explored

Disable ADC calibration (temporary):Comment out CONFIG_ADC_CALIBRATION_ENABLED to bypass the dependency.

Build outside ESPHome Add-On:Use Docker or local build environment where Git context is available.

Use older ESPHome version:Building with ESP-IDF 4.x avoids the missing esp_adc_cal component.

Inject dummy esp_adc_cal component (works offline):Create a local shim that REQUIRES esp_adc to satisfy the build system.

Avoid microphone: and sound_level: blocks:These can trigger inclusion of the legacy calibration header even if unused.

📌 References

ESP-IDF Migration Docs – esp_adc_cal removal

Home Assistant Community – Git sandbox build failures

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

15.2

### What platform are you using?

ESP32

### Board

AZ-Delivery

### Component causing the issue

i2c

### YAML Config

```yaml
esphome:
  name: sm300d2
  friendly_name: SM300D2

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    # sdkconfig_options:
    #   CONFIG_ADC_CALIBRATION_ENABLED: y
    #   CONFIG_ESP_TLS_INSECURE: y

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "tgRo7gJ8voCZpjD7WQ4tgJ8ibcmjaNulP9dSx86TtDQ="

ota:
  platform: esphome
  password: "40862b0108ca63b51bdde71211d7e670"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.0.9
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sm400D2 Fallback Hotspot"
    password: "p8OgEbYdhWFH"

captive_portal:


# Add SM300D2 Sensors
uart:
  id: uart_sm300
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

external_components:
  - source:
      type: local
      path: /config/esphome_audio_sink/esphome/components
    components: [adf_pipeline, i2s_audio, db_sound_meter]

i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO26

adf_pipeline:
  - platform: i2s_audio
    type: audio_in
    id: adf_i2s_in
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO33
    sample_rate: 16000
    bits_per_sample: 16bit
    pdm: false

  - platform: db_sound_meter
    type: audio_out
    id: sound_meter_sink

# microphone:
#   - platform: adf_pipeline
#     id: adf_microphone
#     keep_pipeline_alive: true
#     pipeline:
#       - adf_i2s_in
#       - sound_meter_sink
#       - self
      
sensor:
  - platform: template
    name: "Sound Level (INMP441 ADF)"
    id: adf_db_sensor
    unit_of_measurement: "dB"
    accuracy_decimals: 1
    update_interval: 500ms

  - platform: sm300d2
    uart_id: uart_sm300
    pm_2_5:
      name: "SM300D2 PM2.5"
      icon: "mdi:air-filter"
    pm_10_0:
      name: "SM300D2 PM10"
      icon: "mdi:air-filter"
    temperature:
      name: "SM300D2 Temperature"
      icon: "mdi:thermometer"
    humidity:
      name: "SM300D2 Humidity"
      icon: "mdi:water-percent"
    co2:
      name: "SM300D2 CO2"
      icon: "mdi:molecule-co2"
    tvoc:
      name: "SM300D2 TVOC"
      icon: "mdi:chemical-weapon"
    formaldehyde:
      name: "SM300D2 Formaldehyde"
      icon: "mdi:biohazard"
```

### Anything in the logs that might be useful for us?

```txt

```
