### ISSUE TITLE
Api not connecting after update

### ISSUE THREAD

**Issue by zumbefin** [esphome/issues#7056]
### The problem

Im referring to "Api not connecting after update #6283" that get already closed.

I finaly get it working every time.

The problem seems to be the i2c device scanning, at least in my case. I removed parts from the configuration until I got the device to connect properly. NOTHING else worked except when I set the i2c definition to "scan: false" which made the api connect properly every time.

I also have that scan turned on other devices that have fewer i2c devices and the problem hasn't occurred so the problem may be a combination of multiple i2c devices and scan mode being on

# i2C pins and setup
i2c:
  sda: GPIO21 # D21
  scl: GPIO22 # D22
  scan: true    <----- The PROBLEM
  id: bus_a  

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.3

### What platform are you using?

ESP32

### Component causing the issue

i2c

### YAML Config

```yaml
esphome:
  name: "takapiha-keskus"
  friendly_name: Takapiha-keskus

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:  
  #encryption: 
    #key: "sensored"

#mqtt:
  #broker: 10.1.1.5
  #username: takapiha

ota:
  - platform: esphome
    password: salasana

safe_mode:
  boot_is_good_after: 90s
  num_attempts: 3

preferences:
  flash_write_interval: 10min  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Takapiha Fallback Hotspot"
    password: "sensored"
  fast_connect: off
 # manual_ip:
    # Set this to the IP of the ESP
    #static_ip: 10.1.1.40
    # Set this to the IP address of the router. Often ends with .1
    #gateway: 10.1.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    #subnet: 255.255.255.0
    #dns1: 10.1.1.1  

captive_portal:

#web_server:
  #port: 80
  #version: 3    

# i2C pins and setup
i2c:
  sda: GPIO21 # D21
  scl: GPIO22 # D22
  scan: false
  id: bus_a  

#co2 kommunikaatio
uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600  

#Valoisuus anturi BH1750
sensor:
  - platform: bh1750
    name: "takapiha valoisuus bh1750"
    address: 0x23
    update_interval: 60s

  - platform: sht4x
    temperature:
      name: "takapiha lämpötila sht40"
    humidity:
      name: "takapiha kosteus sht40"
    heater_max_duty: 0.05
    heater_power: High
    heater_time: Long  

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""   
#CO2
  - platform: senseair
    co2:
      name: "SenseAir CO2 arvo ulkona"
    update_interval: 60s


          

#sisäinen lämpötila
  - platform: internal_temperature
    name: "takapiha ESP lämpötila"    


  # BME280 Temperature, Pressure, Humidity sensor
  - platform: bme280_i2c
    temperature:
      name: "takapiha lämpötila bme280"
    pressure:
      name: "takapiha ilmanpaine bme280"
    humidity:
      name: "takapiha kosteus bme280"
    address: 0x76  

#restart nappi
switch:
  - platform: restart
    name: "Restart ESP32"
    id: restart_switch 
    
#CO2 lämmittimen rele
  - platform: gpio
    name: "CO2 lämmitys rele"
    pin: 
      number: GPIO4
      inverted: true
      mode: 
        output: True
        open_drain: True
    restore_mode: ALWAYS_OFF
```

### Anything in the logs that might be useful for us?

```txt

```
