### ISSUE TITLE
Home Assistant sensor update interval issue

### ISSUE THREAD

**Issue by plplaaa2** [esphome/issues#7059]
### The problem

While configuring LVGL, I tried to specify the update speed of the Home Assistant sensor as a way to reduce CPU load, but it doesn't work. 

I assume it's missing because it's a push-type sensor, but I want to use it as a poll-type sensor.

Of course, the Home Assistant sensor section states that all sensor options can be used.

### Which version of ESPHome has the issue?

2025.05

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.2

### What platform are you using?

ESP32-IDF

### Board

ESP32 S3

### Component causing the issue

homeassistant sensor

### YAML Config

```yaml
INFO ESPHome 2025.5.0
INFO Reading configuration /config/esphome/guition-esp32-7.yaml...
Failed config

sensor.homeassistant: [source /config/esphome/lvgl/dash_board/indoor-800.yaml:3]
  platform: homeassistant
  entity_id: sensor.smartmi_air_purifier_temperature
  id: temperature
  filters: 
    - median: {}
  
  [update_interval] is an invalid option for [sensor.homeassistant]. Did you mean [internal]?
  update_interval: 5s
  on_value: 
    - lvgl.indicator.update: 
        id: temp_needle
        value: !lambda |-
          return x * 10;
    - lvgl.label.update: 
        id: temp_in_text
        text: 
          format: %.1f°c
          args: 
            - x
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

At some point, the update_interval option disappeared from the ESPHome documentation under the sensor section
