### ISSUE TITLE
Dallas sensors not working with RP2040 after ESPHome 2025.5.0 update

### ISSUE THREAD

**Issue by Mavorad** [esphome/issues#7060]
### The problem

After the latest update my Dallas onwire sensors don't work stable anymore .
I use 2 systems one with 9 and one with 10 sensors of DS18B20,
With startup not all sensors are recognised, it worked before. 

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.3

### What platform are you using?

RP2040

### Board

Raspberry PicoW 2022

### Component causing the issue

Onewire

### YAML Config

```yaml
substitutions:
  name: "info-vloerverwarming"
  friendly_name: Info_Vloerverwarming

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WVoPfaC6JttjJwKGHbkPZSJNhe9GpQQ1yTGqR66Jxf4="

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: "015c4bdea34b56aabd61f607317f2b64"

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # ...
  manual_ip:
    static_ip: 172.20.2.206
    gateway: 172.20.2.1
    subnet: 255.255.255.0

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/pico-w.yaml@main
  import_full_config: true


# Example configuration entry
one_wire:
  - platform: gpio
    pin: GPIO28
    
     
# Individual sensors 1 til 10 for Floorheating
sensor:
  - platform: dallas_temp
    address: 0xf80318977923d728
    update_interval: 31s
    name: "Sensor_1"  # Groep 1
    filters:
    - offset: 0.7

  - platform: dallas_temp
    address: 0xab031997795a1e28
    update_interval: 33s
    name: "Sensor_2"  # Groep 2
    filters:
    - offset: 0.8

  - platform: dallas_temp
    address: 0x735704700a646128
    update_interval: 33s
    name: "Sensor_3"  # Groep 3
    filters:
    - offset: -1.5

  - platform: dallas_temp
    update_interval: 35s
    address: 0x917724700a646128
    name: "Sensor_4"  # Groep 4
    filters:
    - offset: -1.3

  - platform: dallas_temp
    update_interval: 31s
    address: 0x18031797797ddd28
    name: "Sensor_5"  # Groep 5
    filters:
    - offset: 0.1

  - platform: dallas_temp
    update_interval: 33s
    address: 0xa103189779350b28
    name: "Sensor_6"  # Groep 6
    filters:
    - offset: -0.0

  - platform: dallas_temp
    update_interval: 35s
    address: 0x7a0516a4c27bff28
    name: "Sensor_7"  # Groep 7
    filters:
    - offset: -0.7

  - platform: dallas_temp
    update_interval: 37s
    address: 0x140008023bafff10
    name: "Sensor_8"  # Aanvoer van ketel
    filters:
    - offset: -1.0

  - platform: dallas_temp
    update_interval: 33s
    address: 0xfb6adc7b12646128
    name: "Sensor_9"  # Retour naar ketel
    filters:
    - offset: -0.6
    
  - platform: dallas_temp
    update_interval: 3s
    address: 0x69000802571cc110 ##  0x913c01e07698dc28
    name: "Sensor_10" # Meng naar vloer
    filters:
    - offset: 0.1

output:
# For Raspberry Pi Pico W LED output
  - platform: gpio
    pin: 
      number: 32
      mode: output
    id: LED  

  - platform: gpio
    pin: 
      number: 22  
      mode: output
    id: PumpStart

# Blink LED
interval:
  - interval: 1000ms
    then:
      - output.turn_on: LED
      - delay: 100ms
      - output.turn_off: LED
   
# Set output fot PumpStart = Circulation pump Floorheating
# Start Pump if Aanvoertemp - Retoer temp > 5 C
# Stop pump if Aanvoertemp - Retour Temp < 2 C
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

[logs_info-vloerverwarming_logs.txt](https://github.com/user-attachments/files/20438575/logs_info-vloerverwarming_logs.txt)

![Image](https://github.com/user-attachments/assets/b7998ec8-6c91-4e7b-ba5b-055a798cc6b0)
