### ISSUE TITLE
Recompile all source files if value of esphome->project->version modified

### ISSUE THREAD

**Issue by alainvdu69** [esphome/issues#7062]
### The problem

Hi !

I've noticed that changing the value of the version in esphome->project->version causes all source files to be recompiled.
I think it's abusive ?

Thanks.

### Which version of ESPHome has the issue?

2025.5.0 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.3

### What platform are you using?

ESP32

### Board

ESP32

### Component causing the issue

 esphome->project->version 

### YAML Config

```yaml
esphome:
  name: "tdisplay01"
  friendly_name: "tdisplay01"
  project:
    name: "alain.tdisplay01"
    version: "1.3.4"
```

### Anything in the logs that might be useful for us?

```txt

```
