### ISSUE TITLE
Lanbon L9 uses MIPI-SPI, not Lanbon L8

### ISSUE THREAD

**Issue by janick** [esphome/issues#7064]
### The problem

I was happy to see the mipi_spi platform appear in 2025.5.0 however the LANBON-L8 model is wrong. The L8 uses a single-bit SPI. It is the Lanbon L9 that uses the 8-bit i80/MIPI interface.

Here's my configuration for the L9 using Clyde's i80-ili branch:

```
i80:
  dc_pin: GPIO17
  data_pins: 
    - GPIO6
    - GPIO7
    - GPIO15
    - GPIO16
    - GPIO10
    - GPIO9
    - ignore_strapping_warning: true
      number: GPIO46
    - ignore_strapping_warning: true
      number: GPIO3
  wr_pin: GPIO13
  rd_pin: GPIO18

i2c:
  sda: GPIO35
  scl:
    ignore_strapping_warning: true
    number: GPIO0

display:
  - id: langbon_L9
    platform: ili9xxx
    model: ST7789V
    bus_type: i80
    invert_colors: true
    dimensions:
      height: 320
      width: 170
      offset_width: 35
    cs_pin: GPIO21
    reset_pin: GPIO4
    auto_clear_enabled: false
    update_interval: never
    rotation: 0
```

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.1

### What platform are you using?

ESP32

### Board

Lanbon L9

### Component causing the issue

mipi_spi

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```
