### ISSUE TITLE
New Octal SPI is missing WR and RD pins for i80 bus

### ISSUE THREAD

**Issue by janick** [esphome/issues#7065]
### The problem

Trying to port my Lanbon L9 to the new mipi_spi platform and octal spi, but there are no options to specify the WR and RD pins that were present on the i80 component on CLyde's `i80-ili` branch. PR #8383 states it should support the i80 bus.

```
i80:
  dc_pin: GPIO17
  data_pins: 
    - GPIO6
    - GPIO7
    - GPIO15
    - GPIO16
    - GPIO10
    - GPIO9
    - ignore_strapping_warning: true
      number: GPIO46
    - ignore_strapping_warning: true
      number: GPIO3
  wr_pin: GPIO13
  rd_pin: GPIO18
```

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.3

### What platform are you using?

ESP32

### Board

Lanbon L9

### Component causing the issue

spi

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```
