### ISSUE TITLE
OTA size too large - TreatLife DS03 Fan and Light Switch BK7231N v2.1.6

### ISSUE THREAD

**Issue by jnrcorp** [esphome/issues#7068]
### The problem

Starting with version 2025.5.0, I got the error `OTA size too large` when attempting to update the version of ESPHome on my `TreatLife DS03 Fan and Light Switch BK7231N v2.1.6` devices.

These devices control both a fan and a light. The size of the OTA is slightly too large. It can be resolved by removing the web server add-on, but I like having access to that page to monitor the device.

### Which version of ESPHome has the issue?

2025.5.0, 2025.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

BK72XX

### Board

generic-bk7231n-qfn32-tuya

### YAML Config

```yaml
esphome:
  name: $device_name
  friendly_name: $friendly_name
  comment: "TreatLife DS03 Fan and Light Switch BK7231N v2.1.6"
  on_boot:
    priority: -100
    then:
      - delay: 5s
      - number.set:
          id: light_brightness
          value: $max_brightness_pct

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:

web_server:
  auth: 
    username: !secret web_server_auth_user
    password: !secret web_server_auth_password

captive_portal:

mdns:

# Uncomment to add local time and avoid the "LOCAL_TIME_QUERY is not handled because time is not configured" log error
time:
  - platform: homeassistant
    id: homeassistant_time
tuya:
  time_id: homeassistant_time

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$friendly_name Fallback"
    password: !secret fallback_hotspot_password

debug:
  update_interval: 30s

button:
  - platform: restart
    name: Restart

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
    filters:
      - delta: 0.01
      - throttle: 300s

  - platform: uptime
    name: Uptime
    filters:
      - throttle: 300s

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 115200

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

  # Expose ESPHome version as sensor.
  - platform: version
    name: ESPHome Version
    
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID
    bssid:
      name: BSSID

light:
  - platform: tuya
    name: Dimmer
    switch_datapoint: 101
    dimmer_datapoint: 6
    min_value_datapoint: 105
    min_value: $min_brightness
    max_value: $max_brightness

fan:
  - platform: tuya
    name: Fan
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4

select:
  - platform: tuya
    enum_datapoint: 3
    name: Fan Speed
    optimistic: true
    options:
      0: Speed 1
      1: Speed 2
      2: Speed 3
      3: Speed 4
  - platform: tuya
    enum_datapoint: 106
    entity_category: config
    name: Dimming Mode
    optimistic: true
    options:
      0: Mode 1
      1: Mode 2
      2: Mode 3

number:
  - platform: tuya
    number_datapoint: 6
    name: Brightness
    id: light_brightness
    unit_of_measurement: "%"
    min_value: $min_brightness_pct
    max_value: $max_brightness_pct
    step: 1
    multiply: 10
    mode: BOX
  - platform: tuya
    number_datapoint: 105
    name: Brightness Mininum
    unit_of_measurement: "%"
    min_value: 1
    max_value: 100
    step: 1
    multiply: 10
    entity_category: config
    mode: BOX
```

### Anything in the logs that might be useful for us?

```txt
|-- OTA size too large: 683504 > 679936 (0xA6000)
RAM:   [====      ]  36.7% (used 96088 bytes from 262144 bytes)
Flash: [==========]  96.4% (used 1044588 bytes from 1083136 bytes)
Building UF2 OTA image
|-- esphome_2025.5.1_generic-bk7231n-qfn32-tuya_bk7231n_lt1.7.0.uf2
|-- firmware.uf2
|-- firmware.bin
========================= [SUCCESS] Took 74.90 seconds =========================
Warning! Non-Git installations are NOT SUPPORTED.
INFO Successfully compiled program.
INFO Connecting to 10.33.10.23 port 8892...
INFO Connected to 10.33.10.23
INFO Uploading /data/build/family-room-tv/.pioenvs/family-room-tv/firmware.uf2 (3597824 bytes)
Uploading: [=========================================================== ] 99% ERROR Error chunk OK: Error: Wring OTA data to flash memory failed. See USB logs for more information.
```
