### ISSUE TITLE
dallas sensor no longer working after esp home update

### ISSUE THREAD

**Issue by wymes** [esphome/issues#7069]
### The problem

since the recent ESP home update the dallas temp sensors no longer update home assistant. I have an ESP32 with a bme280 sensor which is working fine after the update to the new version of esp home  

### Which version of ESPHome has the issue?

Firmware: 2025.5.1 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2025.5.3

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

dallas sensor

### YAML Config

```yaml
esphome:
  name: fox-ess-temp
  friendly_name: Fox-ESS-Temp

esp8266:
  board: d1_mini

one_wire:
  - platform: gpio
    pin: GPIO4
    #update_interval: 5s

sensor:
  - platform: dallas_temp
    address: 0x1d08225499e23628
    name: "Battery Temp"
    update_interval: 5s
  - platform: dallas_temp
    address: 0x3f0622606f774d28
    name: "Garage Temp"
    update_interval: 5s

# Enable logging
logger:
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

[logs_fox-ess-temp_logs.txt](https://github.com/user-attachments/files/20469308/logs_fox-ess-temp_logs.txt)
