### ISSUE TITLE
Custom Component setup() not called/logging with ESP-IDF framework on ESP32-S3 (ESPHome v2024.6.1 & v2025.5.

### ISSUE THREAD

**Issue by wifijt** [esphome/issues#7071]
### The problem

I am developing a custom component (cyberpower_ups_hid) that needs to use the ESP-IDF USB Host HID functionality. While the component's C++ dump_config() method is successfully called and produces log output, the C++ setup() method does not appear to be called, or it fails silently before its very first ESP_LOGE statement can execute. This prevents any of the component's initialization code (including USB host setup) from running.

This behavior has been observed with the component inheriting from esphome::Component (for diagnostic purposes) and also when it was inheriting from esphome::PollingComponent. The issue persists even with an ultra-minimal setup() method containing only a single ESP_LOGE statement.

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

esp32-s3-devkitc-1

### YAML Config

```yaml
esphome:
  name: cyberpower-ups
  friendly_name: CyberPower UPS
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  framework:
    type: esp-idf
    # sdkconfig_options are correctly nested under framework:
    components:
      - name: "usb_host_hid"
        source: "github://espressif/esp-usb"
        path: "host/class/hid/usb_host_hid"

external_components:
  - source:
      type: local
      path: custom_components # Points to folder containing 'cyberpower_ups_hid'

# WiFi, API, OTA as before...
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true # Added based on your last full YAML

api: 
ota:
  platform: esphome

logger:
  level: VERBOSE # Global verbose
  logs:
    cyberpower_ups_hid: VERBOSE # For your component's TAG
    CyberPowerUPS_DEBUG: VERBOSE # For the ESP_LOGE tag in the minimal setup()


# Configuration for custom component (defined by __init__.py using basic Component for this test)
cyberpower_ups_hid:
  id: my_ups_component_hub
  vendor_id: 0x0764
  product_id: 0x0000
  # NO update_interval here (because it's not a PollingComponent for this test)

# Sensor/binary_sensor definitions are fine, they link to the hub.
sensor:
  - platform: cyberpower_ups_hid
    hub_id: my_ups_component_hub
    input_voltage:
      name: "UPS Input Voltage Test"
    output_voltage:
      name: "UPS Output Voltage Test"
    load_power:
      name: "UPS Load Power Test"
    battery_level:
      name: "UPS Battery Level Test"
    runtime_remaining:
      name: "UPS Runtime Remaining Test"

binary_sensor:
  - platform: cyberpower_ups_hid
    hub_id: my_ups_component_hub
    ac_present:
      name: "UPS AC Present Test"
    battery_charging:
      name: "UPS Battery Charging Test"
    battery_discharging:
      name: "UPS Battery Discharging Test"
```

### Anything in the logs that might be useful for us?

```txt
The void dump_config() produces log messages as expected - however 

void CyberPowerUPSHIDComponent::setup() {
  ESP_LOGCONFIG(TAG, "!!!!!!!!!! FOO");
}

Produces no log - is setup being called?
```
