### ISSUE TITLE
2025.5.1 breaks Dallas one-wire sensor on Beken devices

### ISSUE THREAD

**Issue by VivitechMT** [esphome/issues#7080]
### The problem

I have several Esphome-flashed Beken based I-R blasters that I've added a DS18B20 to on spare input.  These have all been working perfectly for a year or more - but when I upgraded them to 2025.5 they all started to report the same error on the Dallas sensors:

"Scratch pad checksum invalid!"

I know this is often an issue with wire noise etc., but this must be a software-only issue because I've reverted them all back to 2025.4.2 and they are all working fine again.

### Which version of ESPHome has the issue?

2025.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.3

### What platform are you using?

BK72XX

### Component causing the issue

dallas/one-wire

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by dshokouhi** [comment]
same here all my devices fail to get recognized and show the same error, rolling back solves the issue

```
[18:08:56][W][dallas.temp.sensor:066]: 'Aquarium 10G Temperature' - reading scratch pad failed bus reset
[18:08:56][W][component:167]: Component dallas_temp.sensor set Warning flag: bus reset failed
```

**Comment by ssieb** [comment]
This is a duplicate of https://github.com/esphome/issues/issues/7039, but I'll keep it separate because I'm not sure how to fix it for libretiny devices.  As a workaround, you can use:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: 2025.4.2
    components: [ one_wire, gpio, dallas_temp ]
```

**Comment by jnxxx** [comment]
I have two ESP32s that have DS18B20s connected.
Upon updating to 2025.5.x both worked.

On one I tried to use the Captive Portal to change WiFi settings, but after this the WiFi became somewhat unstable and took a long time to connect upon wakeup. Reflashing it didn't solve it, so I ended up doing a factory reset. Then WiFi was back to normal, but then it didn't detect the DS18B20.
By using the workaround above I got it working. Afterwards I commented the 2025.4.2 reference out again and it still works...

Although it does not seem to match all cases, in my case it seems only to affect the initial discovery. Could it be some data in the flash memory that does not get initialized?

**Comment by VivitechMT** [comment]
Still an issue in 2025.6.0 I notice - is there likely to be a fix?   Do we know why this only broke the Beken devices?

**Comment by ssieb** [comment]
I have no idea when or if a fix is possible.  I moved all the other platforms to low-level pin access, but Beken doesn't provide the info for that.  I have a potential lead, but I need to find the time to experiment.

**Comment by ssieb** [comment]
@jnxxx this issue is only for Beken devices.  All other platforms should be fixed, so if you're still having problems, then come ask on Discord.

**Comment by ssieb** [comment]
@VivitechMT I don't know of any Beken devices that come with Dallas sensors on them.  You might be the only one affected by this.

**Comment by VivitechMT** [comment]
I just bolted a DS18B20 onto a spare pin in some Beken blaster devices.  They worked fine for ages, and now they don't - I'm just curious as to why - I've always been of the "if it ain't broke, don't fix it" philosophy!

**Comment by ssieb** [comment]
I don't know for sure about the Beken MCU, but I'm assuming it's the same.  I haven't had a chance to put a logic analyzer on one to verify yet.
All of these devices (ESP8266, ESP32, RP2040) have flash that is accessed over SPI, so it's much slower than the CPU.  So there's a small amount of RAM reserved as a cache for chunks of code.  The CPU automatically copies chunks from flash to this cache as needed.  This of course causes random brief pauses in the execution of code, which is really bad for microsecond timings.  Fortunately, there's a way to tell the linker to load certain functions directly into the cache and keep them there always.  The original 1-wire code disabled interrupts for the entire transaction, which is unnecessary and not great for future 1-wire components like the i2c one, but it did keep everything in the cache for the whole transaction.  When I reduced the area covered by disabled interrupts, I discovered that the underlying pin manipulation functions were not flagged for the cache, so I had to change all the platforms to use lower-level functions and macros that were cachable.  ESP was mostly easy.  For RP2040, I had to find the not really documented flag, but eventually found it.  However, Beken provides almost no info about anything, so I don't know if I'll be able to do the same there.
Still curious?  🤣

**Comment by VivitechMT** [comment]
Sorry if it sounded as though I was criticising - be assured it was not my intention at all. You all do a wonderful job of maintaining a brilliant platform.

Amazingly, yes I am still curious - but then I'm probably one of a dying breed that was coding 8-bit processors in assembly language in the early 80s - and debugging it with logic analyzers that had CRTs in them and weighed half a ton!  They were also the days when processors came with detailed manuals an inch thick, so it must be very frustrating for you nowadays if the chips come with little or no info.

Your explanation is very interesting and informative - and it all makes perfect sense now.  I knew my bolting on a 1-wire device to these Beken blasters was an oddball thing to do anyway - and it was fun to see find it actually worked!  As you say, there must be something about the Beken MCU that fails to get the bus timing right when running the newer optimised code.  

I'll go ahead and add the external_components: include above, rather than keeping these devices on 2025.4 entirely.

Thanks again for taking the time to explain in depth.

**Comment by Brokly** [comment]
> I don't know for sure about the Beken MCU, but I'm assuming it's the same. I haven't had a chance to put a logic analyzer on one to verify yet. All of these devices (ESP8266, ESP32, RP2040) have flash that is accessed over SPI, so it's much slower than the CPU. So there's a small amount of RAM reserved as a cache for chunks of code. The CPU automatically copies chunks from flash to this cache as needed. This of course causes random brief pauses in the execution of code, which is really bad for microsecond timings. Fortunately, there's a way to tell the linker to load certain functions directly into the cache and keep them there always. The original 1-wire code disabled interrupts for the entire transaction, which is unnecessary and not great for future 1-wire components like the i2c one, but it did keep everything in the cache for the whole transaction. When I reduced the area covered by disabled interrupts, I discovered that the underlying pin manipulation functions were not flagged for the cache, so I had to change all the platforms to use lower-level functions and macros that were cachable. ESP was mostly easy. For RP2040, I had to find the not really documented flag, but eventually found it. However, Beken provides almost no info about anything, so I don't know if I'll be able to do the same there. Still curious? 🤣

Take a look, you might find my edits useful. Everything works with these changes. https://github.com/Brokly/TestCoreGpioOneWire/tree/main/components/gpio/one_wre

**Comment by Brokly** [comment]
It's not just about macros, but also about their location in the code (reading). I also had to roll back the bus write timings.

This configuration allows  to compile the code (оf course, the corrected files are located locally in "old_components/2025.6.2") :

```yaml
external_components:
  - source:
      type: local
      path: old_components/2025.6.2  
    components: [ gpio ] 
    refresh: 1s

bk72xx:
  board: generic-bk7231n-qfn32-tuya

one_wire:
  - platform: gpio
    pin: TX1

sensor:
  - platform: dallas_temp
    update_interval: 10s
    id: temperature_id
    name: Temperature
    filters:
      - lambda: |-
          static uint32_t err=0;
          static uint32_t ok=0;
          if(isnan(x)){
             err++;
             id(dall_err_id).publish_state(err);
          } else {
             ok++;
             id(dall_ok_id).publish_state(ok);
          }
          return x;
  - platform: template
    id: dall_err_id
    name: Dallas Errors
  - platform: template
    id: dall_ok_id
    name: Dallas OK
```
However, it would be very helpful if you could help with the solution in future releases.
