### ISSUE TITLE
LD2410 and Light component after update to 2025.5.x

### ISSUE THREAD

**Issue by DerEmder** [esphome/issues#7082]
### The problem

After the update to 2025.5.0 and .1 the ESP8266 with an LD2410 and a LED stripe of 16 LEDS does not work anymore - it resets constantly. OTA flashing is possible but very slow until ~10% - then timeout. No connection to the API.

Log after USB flashing without LD2410 attached:

```
#### Try 1 - without LD2410 connected

INFO ESPHome 2025.5.1
INFO Reading configuration /config/esphome/gina.yaml...
INFO Starting log output from 10.42.0.73 using esphome API
INFO Successfully connected to gina @ 10.42.0.73 in 0.054s
INFO Successful handshake with gina @ 10.42.0.73 in 3.052s
[14:42:13][I][app:115]: ESPHome version 2025.5.1 compiled on May 30 2025, 13:21:47
[14:42:13][C][wifi:600]: WiFi:
[14:42:13][C][light:092]: Light 'Gina LED'
[14:42:13][C][template.switch:068]: Template Switch 'Gina LED0'
[14:42:13][C][template.switch:068]: Template Switch 'Gina LED2'
[14:42:13][C][ld2410:075]:   Throttle_ : 1000ms
[14:42:13][C][adc.esp8266:027]: ADC Sensor 'Gina Moisture'
[14:42:14][C][safe_mode:018]: Safe Mode:
[14:42:14][D][sensor:093]: 'Gina Moisture': Sending state 25.29297 % with 0 decimals of accuracy
WARNING gina @ 10.42.0.73: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for gina @ 10.42.0.73
WARNING Disconnected from API
INFO Successfully connected to gina @ 10.42.0.73 in 0.045s
INFO Successful handshake with gina @ 10.42.0.73 in 3.036s
WARNING gina @ 10.42.0.73: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for gina @ 10.42.0.73
WARNING Disconnected from API

#### Try 2 - with LD2410 connected

INFO Successfully connected to gina @ 10.42.0.73 in 0.040s
WARNING Can't connect to ESPHome API for gina @ 10.42.0.73: Handshake timed out after 30.0s (TimeoutAPIError)
INFO Trying to connect to gina @ 10.42.0.73 in the background
WARNING gina @ 10.42.0.73: Connection error occurred: gina @ 10.42.0.73: Connection lost
INFO Successfully connected to gina @ 10.42.0.73 in 0.042s
INFO Successful handshake with gina @ 10.42.0.73 in 3.000s
[14:44:08][D][binary_sensor:036]: 'Gina Moving Target': Sending state OFF
[14:44:08][D][sensor:093]: 'Gina Moving Energy': Sending state 0.00000 % with 0 decimals of accuracy
[14:44:10][D][sensor:093]: 'Gina Moving Distance': Sending state 86.00000 cm with 0 decimals of accuracy
[14:44:12][D][sensor:093]: 'Gina Moving Distance': Sending state 71.00000 cm with 0 decimals of accuracy
[14:44:12][D][sensor:093]: 'Gina Moisture': Sending state 25.78125 % with 0 decimals of accuracy
[14:44:14][D][binary_sensor:036]: 'Gina Moving Target': Sending state ON
[14:44:14][D][sensor:093]: 'Gina Moving Distance': Sending state 90.00000 cm with 0 decimals of accuracy
[14:44:15][D][binary_sensor:036]: 'Gina Moving Target': Sending state OFF
[14:44:15][D][sensor:093]: 'Gina Moving Distance': Sending state 80.00000 cm with 0 decimals of accuracy
[14:44:18][D][sensor:093]: 'Gina Moving Distance': Sending state 83.00000 cm with 0 decimals of accuracy
[14:44:18][D][sensor:093]: 'Gina Moving Energy': Sending state 72.00000 % with 0 decimals of accuracy
[14:44:19][D][sensor:093]: 'Gina Moving Distance': Sending state 80.00000 cm with 0 decimals of accuracy
[14:44:19][D][sensor:093]: 'Gina Moving Energy': Sending state 0.00000 % with 0 decimals of accuracy
[14:44:20][D][sensor:093]: 'Gina Moving Distance': Sending state 233.00000 cm with 0 decimals of accuracy
[14:44:20][D][sensor:093]: 'Gina Still Distance': Sending state 213.00000 cm with 0 decimals of accuracy
[14:44:21][D][sensor:093]: 'Gina Still Distance': Sending state 222.00000 cm with 0 decimals of accuracy
[14:44:21][D][sensor:093]: 'Gina Distance': Sending state 193.00000 cm with 0 decimals of accuracy
[14:44:22][D][sensor:093]: 'Gina Moisture': Sending state 25.58594 % with 0 decimals of accuracy
[14:44:22][D][sensor:093]: 'Gina Still Distance': Sending state 0.00000 cm with 0 decimals of accuracy
[14:44:22][D][sensor:093]: 'Gina Distance': Sending state 125.00000 cm with 0 decimals of accuracy
[14:44:23][D][sensor:093]: 'Gina Distance': Sending state 0.00000 cm with 0 decimals of accuracy
[14:44:27][D][sensor:093]: 'Gina Still Energy': Sending state 71.00000 % with 0 decimals of accuracy
[14:44:28][D][binary_sensor:036]: 'Gina Moving Target': Sending state OFF
[14:44:28][D][sensor:093]: 'Gina Moving Distance': Sending state 91.00000 cm with 0 decimals of accuracy
[14:44:29][D][binary_sensor:036]: 'Gina Moving Target': Sending state ON
[14:44:29][D][sensor:093]: 'Gina Moving Distance': Sending state 71.00000 cm with 0 decimals of accuracy
[14:44:30][D][sensor:093]: 'Gina Moving Distance': Sending state 86.00000 cm with 0 decimals of accuracy
[14:44:30][D][sensor:093]: 'Gina Distance': Sending state 57.00000 cm with 0 decimals of accuracy

at this point: no connection to API

```

yaml which worked before:

```
substitutions:
  firmware: '5.530'
  devicename: gina
  upper_devicename: 'Gina'

esphome:
  name: $devicename

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret gina_api

ota:
  - platform: esphome
    password: !secret gina_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true
  manual_ip:
    static_ip: 10.42.0.73
    gateway: 10.42.0.1
    subnet: 255.255.255.0
    dns1: 10.42.0.1

  ap:
    ssid: $upper_devicename
    password: !secret init_password

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:

text_sensor:
  - platform: version
    name: '$upper_devicename Firmware'
    filters:
    - lambda: return {"$firmware"};
  - platform: ld2410
    version:
      name: '$upper_devicename Sensor Firmware'
    mac_address:
      name: '$upper_devicename MAC'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: false
      mode:
        input: true
        pullup: true
    name: '$upper_devicename Motion'
    device_class: motion
  - platform: status
    name: '$upper_devicename Status'
    id: api_available
    on_state:
      then:
        - if:
            condition:
              lambda: 'return id(api_available).state;'
            then:
              light.turn_off:
                id: z_led
            else:
              light.turn_on:
                id: z_led
                brightness: 100%
                red: 0%
                green: 0%
                blue: 100%

### LD2410 Binary Sensors ###

  - platform: ld2410
    has_target:
      name: '$upper_devicename Target'
      id: target
    has_moving_target:
      name: '$upper_devicename Moving Target'
      id: moving_target
    has_still_target:
      name: '$upper_devicename Still Target'
      id: still_target

button:
  - platform: restart
    name: '$upper_devicename Reboot'
  - platform: safe_mode
    name: '$upper_devicename Safe Mode'
  - platform: ld2410
    factory_reset:
      name: '$upper_devicename Factory Reset'
    restart:
      name: '$upper_devicename Sensor Reboot'
    query_params:
      name: '$upper_devicename Get Params'

sensor:
  - platform: adc
    pin: A0
    name: '$upper_devicename Moisture'
    id: moisture
    device_class: moisture
    unit_of_measurement: "%"
    accuracy_decimals: 0
    internal: false
    samples: 8
    sampling_mode: max
    filters:
      - multiply: 3.3
      - lambda: |-
          if (x > 3.3) { x = 3.3; }
          return ((3.3 - x) * 100.0) / 3.3;
    on_value_range:
      - above: 36.0
        then:
          - switch.turn_on: alarm_kk
          - switch.template.publish:
              id: alarm_kk
              state: ON
      - below: 34.0
        then:
          - switch.turn_off: alarm_kk
          - switch.template.publish:
              id: alarm_kk
              state: OFF
    update_interval: 10s

### LD2410 Sensors ###

  - platform: ld2410
    moving_distance:
      name: '$upper_devicename Moving Distance'
      id: move_distance
      unit_of_measurement: "cm"
      accuracy_decimals: 0
    still_distance:
      name: '$upper_devicename Still Distance'
      id: still_distance
      unit_of_measurement: "cm"
      accuracy_decimals: 0
    moving_energy:
      name: '$upper_devicename Moving Energy'
      unit_of_measurement: "%"
      accuracy_decimals: 0
    still_energy:
      name: '$upper_devicename Still Energy'
      unit_of_measurement: "%"
      accuracy_decimals: 0
    detection_distance:
      name: '$upper_devicename Distance'
      id: distance
      unit_of_measurement: "cm"
      accuracy_decimals: 0
    g0:
      move_energy:
        name: '$upper_devicename G0 Move Energy'
      still_energy:
        name: '$upper_devicename G0 Still Energy'
    g1:
      move_energy:
        name: '$upper_devicename G1 Move Energy'
      still_energy:
        name: '$upper_devicename G1 Still Energy'
    g2:
      move_energy:
        name: '$upper_devicename G2 Move Energy'
      still_energy:
        name: '$upper_devicename G2 Still Energy'
    g3:
      move_energy:
        name: '$upper_devicename G3 Move Energy'
      still_energy:
        name: '$upper_devicename G3 Still Energy'
    g4:
      move_energy:
        name: '$upper_devicename G4 Move Energy'
      still_energy:
        name: '$upper_devicename G4 Still Energy'
    g5:
      move_energy:
        name: '$upper_devicename G5 Move Energy'
      still_energy:
        name: '$upper_devicename G5 Still Energy'
    g6:
      move_energy:
        name: '$upper_devicename G6 Move Energy'
      still_energy:
        name: '$upper_devicename G6 Still Energy'
    g7:
      move_energy:
        name: '$upper_devicename G7 Move Energy'
      still_energy:
        name: '$upper_devicename G7 Still Energy'
    g8:
      move_energy:
        name: '$upper_devicename G8 Move Energy'
      still_energy:
        name: '$upper_devicename G8 Still Energy'

select:
  - platform: ld2410
    distance_resolution:
      name: '$upper_devicename Resolution'
    baud_rate:
      name: '$upper_devicename Baudrate'
    light_function:
      name: '$upper_devicename Light Function'
    out_pin_level:
      name: '$upper_devicename Level'

number:
  - platform: ld2410
    timeout:
      name: '$upper_devicename Timeout'
      id: noneDuration
    max_move_distance_gate:
      name: '$upper_devicename Max Moving Distance'
      id: maxMovingDistanceRange
    max_still_distance_gate:
      name: '$upper_devicename Max Still Distance'
      id: maxStillDistanceRange
    g0:
      move_threshold:
        name: '$upper_devicename Set G0 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G0 Still'
        mode: box
    g1:
      move_threshold:
        name: '$upper_devicename Set G1 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G1 Still'
        mode: box
    g2:
      move_threshold:
        name: '$upper_devicename Set G2 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G2 Still'
        mode: box
    g3:
      move_threshold:
        name: '$upper_devicename Set G3 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G3 Still'
        mode: box
    g4:
      move_threshold:
        name: '$upper_devicename Set G4 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G4 Still'
        mode: box
    g5:
      move_threshold:
        name: '$upper_devicename Set G5 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G5 Still'
        mode: box
    g6:
      move_threshold:
        name: '$upper_devicename Set G6 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G6 Still'
        mode: box
    g7:
      move_threshold:
        name: '$upper_devicename Set G7 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G7 Still'
        mode: box
    g8:
      move_threshold:
        name: '$upper_devicename Set G8 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G8 Still'
        mode: box

light:
  - platform: neopixelbus
    name: '$upper_devicename LED'
    id: z_led
    type: GRB
    variant: WS2812
    num_leds: 16
    pin: D2
    method:
      type: bit_bang
    effects:
      - pulse:
          name: 'FastPulse'
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: 'SlowPulse'
          transition_length: 0.5s
          update_interval: 1s
          min_brightness: 0%
          max_brightness: 100%

switch:
  - platform: template
    name: '$upper_devicename Alarm Küchenkeller'
    id: alarm_kk
    device_class: switch
    turn_on_action:
      - light.turn_off:
          id: z_led
      - light.turn_on:
          id: z_led
          brightness: 100%
          color_brightness: 100%
          red: 100%
          green: 0%
          blue: 0%
          effect: FastPulse
    turn_off_action:
      - light.turn_off:
          id: z_led
  - platform: ld2410
    engineering_mode:
      name: '$upper_devicename Config Mode'
    bluetooth:
      name: '$upper_devicename Bluetooth'

```

yaml which does not work and produces the log above:

```

substitutions:
  firmware: '5.530'
  devicename: gina
  upper_devicename: 'Gina'

esphome:
  name: $devicename

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret gina_api

ota:
  - platform: esphome
    password: !secret gina_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true
  manual_ip:
    static_ip: 10.42.0.73
    gateway: 10.42.0.1
    subnet: 255.255.255.0
    dns1: 10.42.0.1

  ap:
    ssid: $upper_devicename
    password: !secret init_password

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:

text_sensor:
  - platform: version
    name: '$upper_devicename Firmware'
    filters:
    - lambda: return {"$firmware"};
  - platform: ld2410
    version:
      name: '$upper_devicename Sensor Firmware'
    mac_address:
      name: '$upper_devicename MAC'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: false
      mode:
        input: true
        pullup: true
    name: '$upper_devicename Motion'
    device_class: motion
  - platform: status
    name: '$upper_devicename Status'
    id: api_available
    on_state:
      then:
        - if:
            condition:
              lambda: 'return id(api_available).state;'
            then:
              light.turn_off:
                id: z_led
            else:
              light.turn_on:
                id: z_led
                brightness: 100%
                red: 0%
                green: 0%
                blue: 100%

### LD2410 Binary Sensors ###

  - platform: ld2410
    has_target:
      name: '$upper_devicename Target'
      id: target
    has_moving_target:
      name: '$upper_devicename Moving Target'
      id: moving_target
    has_still_target:
      name: '$upper_devicename Still Target'
      id: still_target

button:
  - platform: restart
    name: '$upper_devicename Reboot'
  - platform: safe_mode
    name: '$upper_devicename Safe Mode'
  - platform: ld2410
    factory_reset:
      name: '$upper_devicename Factory Reset'
    restart:
      name: '$upper_devicename Sensor Reboot'
    query_params:
      name: '$upper_devicename Get Params'

sensor:
  - platform: adc
    pin: A0
    name: '$upper_devicename Moisture'
    id: moisture
    device_class: moisture
    unit_of_measurement: "%"
    accuracy_decimals: 0
    internal: false
    samples: 8
    sampling_mode: max
    filters:
      - multiply: 3.3
      - lambda: |-
          if (x > 3.3) { x = 3.3; }
          return ((3.3 - x) * 100.0) / 3.3;
    on_value_range:
      - above: 36.0
        then:
          - switch.turn_on: alarm_kk
          - switch.template.publish:
              id: alarm_kk
              state: ON
      - below: 34.0
        then:
          - switch.turn_off: alarm_kk
          - switch.template.publish:
              id: alarm_kk
              state: OFF
    update_interval: 10s

### LD2410 Sensors ###

  - platform: ld2410
    moving_distance:
      name: '$upper_devicename Moving Distance'
      id: move_distance
      unit_of_measurement: "cm"
      accuracy_decimals: 0
    still_distance:
      name: '$upper_devicename Still Distance'
      id: still_distance
      unit_of_measurement: "cm"
      accuracy_decimals: 0
    moving_energy:
      name: '$upper_devicename Moving Energy'
      unit_of_measurement: "%"
      accuracy_decimals: 0
    still_energy:
      name: '$upper_devicename Still Energy'
      unit_of_measurement: "%"
      accuracy_decimals: 0
    detection_distance:
      name: '$upper_devicename Distance'
      id: distance
      unit_of_measurement: "cm"
      accuracy_decimals: 0
    g0:
      move_energy:
        name: '$upper_devicename G0 Move Energy'
      still_energy:
        name: '$upper_devicename G0 Still Energy'
    g1:
      move_energy:
        name: '$upper_devicename G1 Move Energy'
      still_energy:
        name: '$upper_devicename G1 Still Energy'
    g2:
      move_energy:
        name: '$upper_devicename G2 Move Energy'
      still_energy:
        name: '$upper_devicename G2 Still Energy'
    g3:
      move_energy:
        name: '$upper_devicename G3 Move Energy'
      still_energy:
        name: '$upper_devicename G3 Still Energy'
    g4:
      move_energy:
        name: '$upper_devicename G4 Move Energy'
      still_energy:
        name: '$upper_devicename G4 Still Energy'
    g5:
      move_energy:
        name: '$upper_devicename G5 Move Energy'
      still_energy:
        name: '$upper_devicename G5 Still Energy'
    g6:
      move_energy:
        name: '$upper_devicename G6 Move Energy'
      still_energy:
        name: '$upper_devicename G6 Still Energy'
    g7:
      move_energy:
        name: '$upper_devicename G7 Move Energy'
      still_energy:
        name: '$upper_devicename G7 Still Energy'
    g8:
      move_energy:
        name: '$upper_devicename G8 Move Energy'
      still_energy:
        name: '$upper_devicename G8 Still Energy'

select:
  - platform: ld2410
    distance_resolution:
      name: '$upper_devicename Resolution'
    baud_rate:
      name: '$upper_devicename Baudrate'
    light_function:
      name: '$upper_devicename Light Function'
    out_pin_level:
      name: '$upper_devicename Level'

number:
  - platform: ld2410
    timeout:
      name: '$upper_devicename Timeout'
      id: noneDuration
    max_move_distance_gate:
      name: '$upper_devicename Max Moving Distance'
      id: maxMovingDistanceRange
    max_still_distance_gate:
      name: '$upper_devicename Max Still Distance'
      id: maxStillDistanceRange
    g0:
      move_threshold:
        name: '$upper_devicename Set G0 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G0 Still'
        mode: box
    g1:
      move_threshold:
        name: '$upper_devicename Set G1 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G1 Still'
        mode: box
    g2:
      move_threshold:
        name: '$upper_devicename Set G2 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G2 Still'
        mode: box
    g3:
      move_threshold:
        name: '$upper_devicename Set G3 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G3 Still'
        mode: box
    g4:
      move_threshold:
        name: '$upper_devicename Set G4 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G4 Still'
        mode: box
    g5:
      move_threshold:
        name: '$upper_devicename Set G5 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G5 Still'
        mode: box
    g6:
      move_threshold:
        name: '$upper_devicename Set G6 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G6 Still'
        mode: box
    g7:
      move_threshold:
        name: '$upper_devicename Set G7 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G7 Still'
        mode: box
    g8:
      move_threshold:
        name: '$upper_devicename Set G8 Move'
        mode: box
      still_threshold:
        name: '$upper_devicename Set G8 Still'
        mode: box

light:
  - platform: neopixelbus
    name: '$upper_devicename LED'
    id: z_led
    type: GRB
    variant: WS2812
    num_leds: 16
    pin: D2
    method:
      type: bit_bang
    effects:
      - pulse:
          name: 'FastPulse'
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: 'SlowPulse'
          transition_length: 0.5s
          update_interval: 1s
          min_brightness: 0%
          max_brightness: 100%

switch:
  - platform: template
    name: '$upper_devicename Alarm Küchenkeller'
    id: alarm_kk
    device_class: switch
    turn_on_action:
      - light.turn_off:
          id: z_led
      - light.turn_on:
          id: z_led
          brightness: 100%
          color_brightness: 100%
          red: 100%
          green: 0%
          blue: 0%
          effect: FastPulse
    turn_off_action:
      - light.turn_off:
          id: z_led
  - platform: ld2410
    engineering_mode:
      name: '$upper_devicename Config Mode'
    bluetooth:
      name: '$upper_devicename Bluetooth'
  - platform: template
    name: '$upper_devicename LED0'
    turn_on_action:
      - light.addressable_set:
          id: z_led
          range_from: 0
          range_to: 3
          red: 0%
          green: 100%
          blue: 0%
          color_brightness: 50%
    turn_off_action:
      - light.addressable_set:
          id: z_led
          range_from: 0
          range_to: 3
          red: 0%
          green: 0%
          blue: 0%
          color_brightness: 0%
  - platform: template
    name: '$upper_devicename LED1'
    turn_on_action:
      - light.addressable_set:
          id: z_led
          range_from: 4
          range_to: 7
          red: 0%
          green: 40%
          blue: 0%
          color_brightness: 50%
    turn_off_action:
      - light.addressable_set:
          id: z_led
          range_from: 4
          range_to: 7
          red: 0%
          green: 0%
          blue: 0%
          color_brightness: 0%
  - platform: template
    name: '$upper_devicename LED2'
    turn_on_action:
      - light.addressable_set:
          id: z_led
          range_from: 8
          range_to: 11
          red: 0%
          green: 40%
          blue: 0%
          color_brightness: 50%
    turn_off_action:
      - light.addressable_set:
          id: z_led
          range_from: 8
          range_to: 11
          red: 0%
          green: 0%
          blue: 0%
          color_brightness: 0%
  - platform: template
    name: '$upper_devicename LED3'
    turn_on_action:
      - light.addressable_set:
          id: z_led
          range_from: 12
          range_to: 15
          red: 0%
          green: 40%
          blue: 0%
          color_brightness: 50%
    turn_off_action:
      - light.addressable_set:
          id: z_led
          range_from: 12
          range_to: 15
          red: 0%
          green: 0%
          blue: 0%
          color_brightness: 0%

```

The only change is the light.addressable_set function. I also tried the partition/segemnt function - that also put the device into a bootloop without any API connection.

Any ideas?

### Which version of ESPHome has the issue?

2025.5.x

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

latest

### What platform are you using?

ESP8266

### Board

Wemos D1

### Component causing the issue

LD2410 and Light

### YAML Config

```yaml
see below
```

### Anything in the logs that might be useful for us?

```txt
see below
```
