### ISSUE TITLE
ESPHome Device Builder Cannot Build Firmware / upload / update / install: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).' and more errors

### ISSUE THREAD

**Issue by MichaelWoodc** [esphome/issues#7087]
### The problem

Not sure why this is, I am running it in Home Assistant, the latest version of ESPHome, and I get this:

```
INFO ESPHome 2025.5.1
INFO Reading configuration /config/esphome/emporia.yaml...
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Detected timezone 'America/New_York'
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.8.2
INFO Compiling app...
Processing emporia-vue-v3 (board: esp32dev; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50106.0 (5.1.6) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.10.2 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 12.2.0+20230208
Reading CMake configuration...
-- Found Git: /usr/bin/git (found version "2.39.5") 
-- git rev-parse returned 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Found assembler: xtensa-esp32-elf-gcc
-- Warning: Did not find file Compiler/-ASM
-- Configuring incomplete, errors occurred!
See also "/data/build/emporia-vue-v3/.pioenvs/emporia-vue-v3/CMakeFiles/CMakeOutput.log".
See also "/data/build/emporia-vue-v3/.pioenvs/emporia-vue-v3/CMakeFiles/CMakeError.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Warning (dev) at /data/cache/platformio/packages/tool-cmake/share/cmake-3.21/Modules/CMakeFindBinUtils.cmake:208 (find_program):
  Policy CMP0109 is not set: find_program() requires permission to execute
  but not to read.  Run "cmake --help-policy CMP0109" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The file

    /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-ar

  is readable but not executable.  CMake is using it for compatibility.
Call Stack (most recent call first):
  /data/cache/platformio/packages/tool-cmake/share/cmake-3.21/Modules/CMakeDetermineCCompiler.cmake:201 (include)
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:505 (__project)
  CMakeLists.txt:3 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:505 (__project):
  The CMAKE_C_COMPILER:

    xtensa-esp32-elf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:505 (__project):
  The CMAKE_CXX_COMPILER:

    xtensa-esp32-elf-g++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)
```

CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:505 (__project):
  The CMAKE_ASM_COMPILER:

    xtensa-esp32-elf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

========================== [FAILED] Took 1.47 seconds ==========================

### Which version of ESPHome has the issue?

2025.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.3.4

### What platform are you using?

ESP32-IDF

### Board

Emporia Vue V3

### Component causing the issue

xtensa-esp32-elf-gcc, ESPHome Device Builder, Multiple

### YAML Config

```yaml
substitutions:
  name: emporia-vue-v3
  friendly_name: Emporia Vue V3
  area: "Garage"

  # Circuit Labels used for publishing to Home Assistant
  circuit_1:  "Circuit 1"                  #"Circuit 1"
  circuit_2:  "Circuit 2"         #"Circuit 2"
  circuit_3:  "Circuit 3"           #"Circuit 3"
  circuit_4:  "Circuit 4"           #"Circuit 4"
  circuit_5:  "Circuit 5"  #"Circuit 5"
  circuit_6:  "Circuit 6" #"Circuit 6"
  circuit_7:  "Circuit 7"      #"Circuit 7"
  circuit_8:  "Circuit 8"            #"Circuit 8"
  circuit_9:  "Circuit 9"
  circuit_10: "Circuit 10"
  circuit_11: "Circuit 11"
  circuit_12: "Circuit 12"
  circuit_13: "Circuit 13"
  circuit_14: "Circuit 14"
  circuit_15: "Circuit 15"
  circuit_16: "Circuit 16"

  # Icons for Home Assistant
  icon_circuit: "mdi:power-plug"
  icon_current: "mdi:current-ac"
  icon_meter:   "mdi:meter-electric"
  icon_phase:   "mdi:angle-acute"
  icon_power:   "mdi:transmission-tower-import"
  icon_voltage: "mdi:transmission-tower"

# Use Ethernet or WiFi on the Emporia Vue V3 (you can only include one)
wifi:
  ap: # Enable access point mode for the captive portal
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - light.turn_on: wifi_led
  on_disconnect:
    - light.turn_off: wifi_led

# ethernet:
#   type: RTL8201
#   mdc_pin: GPIO32
#   mdio_pin: GPIO33
#   clk_mode: GPIO0_IN
#   on_connect:
#     - light.turn_on: ethernet_led
#   on_disconnect:
#     - light.turn_off: ethernet_led

# Define filters to be used in circuit sensors.
.defaultfilters:
  - &throttle_avg # Average all raw readings together over a 5 second span before publishing
    throttle_average: 5s
  - &throttle_time # Only send the most recent measurement every 60 seconds
    throttle: 60s
  - &invert # Invert and filter out any values below 0.
    lambda: "return max(-x, 0.0f);"
  - &pos # Filter out any values below 0.
    lambda: "return max(x, 0.0f);"
  - &abs # Take the absolute value of the value
    lambda: "return abs(x);"
  - &zero # Use for disconnected circuits to return 0
    lambda: "return 0.0f;"
  - &double # Use to double the measurement for 240V breakers
    multiply: 2

# Define the sensors to be exposed to Home Assistant.
sensor:
  - platform: emporia_vue
    i2c_id: i2c_a

    # Configure the Emporia Vue wire harness phases.
    phases:
        # Verify that this specific phase/leg is connected to the matching input wire color on device listed below
      - id: phase_a
        # Vue device wire color (BLACK or RED for split phase)
        input: BLACK
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        # 0.0194 is used as the default as starting point for Vue 3 but may need adjusted to ensure accuracy
        calibration: 0.0194
        voltage: { id: phase_a_voltage, name: "Phase A Voltage", icon: $icon_voltage, accuracy_decimals: 0, filters: [ *throttle_avg, *pos ] }
        frequency: { id: phase_a_freqency, name: "Phase A Frequency", accuracy_decimals: 0, filters: [ *throttle_avg, *pos ] }

        # Verify that this specific phase/leg is connected to the matching input wire color on device listed below
      - id: phase_b
        # Vue device wire color (BLACK or RED for split phase)
        input: RED
        # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        # 0.0194 is used as the default as starting point for Vue 3 but may need adjusted to ensure accuracy
        calibration: 0.0194
        voltage: { id: phase_b_voltage, name: "Phase B Voltage", icon: $icon_voltage, accuracy_decimals: 0, filters: [ *throttle_avg, *pos ] }
        phase_angle: { id: phase_b_angle, name: "Phase B Phase Angle", icon: $icon_phase,  accuracy_decimals: 0, filters: [ *throttle_avg, *pos ] }

        # Verify that this specific phase/leg is connected to the matching input wire color on device listed below
        # - id: phase_c
        #   # Vue device wire color (BLUE for three phase)
        #   input: BLUE
        #   # To calculate new calibration value use the formula <in-use calibration value> * <accurate voltage> / <reporting voltage>
        #   # 0.0194 is used as the default as starting point for Vue 3 but may need adjusted to ensure accuracy
        #   calibration: 0.0194
        #   voltage: { id: phase_c_voltage, name: "Phase C Voltage", icon: $icon_voltage, accuracy_decimals: 0, filters: [ *throttle_avg, *pos ] }
        #   phase_angle: { id: phase_c_angle, name: "Phase C Phase Angle", icon: $icon_phase,  accuracy_decimals: 0, filters: [ *throttle_avg, *pos ] }

    # Configure the Emporia Vue CT clamps.
    ct_clamps:
      # Do not specify a name for any of the power sensors here, only an id. This leaves the power sensors internal to ESPHome.
      # These non-throttled power sensors are used for accurately calculating energy.
      # Copy sensors defined later will filter and then send power measurements to Home Assistant.

      # Main Service CT Clamps (up to 3)
      # Verify the correct input on the device is connected to the CT clamp phase defined (Vue 3 inputs are inverted)
      - { input: "A", phase_id: phase_a, power: { id: phase_a_power, filters: *invert } }
      - { input: "B", phase_id: phase_b, power: { id: phase_b_power, filters: *invert } }
      # - { input: "C", phase_id: phase_c, power: { id: phase_c_power, filters: *invert } }

      # Circuit CT Clamps (up to 16)
      # Pay close attention to set the phase_id for each breaker by matching it to the phase/leg it connects to in the panel
      # Use *invert filter for inverted positive values (Vue 3 inputs are inverted) or *zero for un-used inputs
      # Use *double filter for double (240v) breakers (this will assume power is evenly divided between the two legs)
      # Circuit CT Clamps 1–16 (basic, clean, invert only)
      - { input: "1",  phase_id: phase_a, power: { id: c1_pwr, filters: [ *invert ] }, current: { id: c1_cur } }
      - { input: "2",  phase_id: phase_a, power: { id: c2_pwr, filters: [ *invert ] }, current: { id: c2_cur } }
      - { input: "3",  phase_id: phase_a, power: { id: c3_pwr, filters: [ *invert ] }, current: { id: c3_cur } }
      - { input: "4",  phase_id: phase_a, power: { id: c4_pwr, filters: [ *invert ] }, current: { id: c4_cur } }
      - { input: "5",  phase_id: phase_b, power: { id: c5_pwr, filters: [ *invert ] }, current: { id: c5_cur } }
      - { input: "6",  phase_id: phase_a, power: { id: c6_pwr, filters: [ *invert ] }, current: { id: c6_cur } }
      - { input: "7",  phase_id: phase_b, power: { id: c7_pwr, filters: [ *invert ] }, current: { id: c7_cur } }
      - { input: "8",  phase_id: phase_b, power: { id: c8_pwr, filters: [ *invert ] }, current: { id: c8_cur } }
      - { input: "9",  phase_id: phase_a, power: { id: c9_pwr, filters: [ *invert ] }, current: { id: c9_cur } }
      - { input: "10", phase_id: phase_a, power: { id: c10_pwr, filters: [ *invert ] }, current: { id: c10_cur } }
      - { input: "11", phase_id: phase_a, power: { id: c11_pwr, filters: [ *invert ] }, current: { id: c11_cur } }
      - { input: "12", phase_id: phase_a, power: { id: c12_pwr, filters: [ *invert ] }, current: { id: c12_cur } }
      - { input: "13", phase_id: phase_a, power: { id: c13_pwr, filters: [ *invert ] }, current: { id: c13_cur } }
      - { input: "14", phase_id: phase_a, power: { id: c14_pwr, filters: [ *invert ] }, current: { id: c14_cur } }
      - { input: "15", phase_id: phase_a, power: { id: c15_pwr, filters: [ *invert ] }, current: { id: c15_cur } }
      - { input: "16", phase_id: phase_a, power: { id: c16_pwr, filters: [ *invert ] }, current: { id: c16_cur } }
      # - { input: "1",  phase_id: phase_a, power: { id: c1_pwr,  filters: [ *invert, *double ] }, current: { id: c1_cur, filters: [ *double ] } }
      # - { input: "2",  phase_id: phase_a, power: { id: c2_pwr,  filters: [ *invert, *double ] }, current: { id: c2_cur, filters: [ *double ] } }
      # - { input: "3",  phase_id: phase_a, power: { id: c3_pwr,  filters: [ *invert, *double ] }, current: { id: c3_cur, filters: [ *double ] } }
      # - { input: "4",  phase_id: phase_a, power: { id: c4_pwr,  filters: [ *invert, *double ] }, current: { id: c4_cur, filters: [ *double ] } }
      # - { input: "5",  phase_id: phase_b, power: { id: c5_pwr,  filters: [ *invert ]          }, current: { id: c5_cur } }
      # - { input: "6",  phase_id: phase_a, power: { id: c6_pwr,  filters: [ *invert ]          }, current: { id: c6_cur } }
      # - { input: "7",  phase_id: phase_b, power: { id: c7_pwr,  filters: [ *invert ]          }, current: { id: c7_cur } }
      # - { input: "8",  phase_id: phase_b, power: { id: c8_pwr,  filters: [ *invert ]          }, current: { id: c8_cur } }

      # # Unused CT clamp inputs are explicitly set to zero (*zero filter) to avoid phantom readings
      # - { input: "9",  phase_id: phase_a, power: { id: c9_pwr,  filters: [ *zero ]         }, current: { id: c9_cur, filters: [ *zero ] } }
      # - { input: "10", phase_id: phase_a, power: { id: c10_pwr, filters: [ *zero ]         }, current: { id: c10_cur, filters: [ *zero ] } }
      # - { input: "11", phase_id: phase_a, power: { id: c11_pwr, filters: [ *zero ]         }, current: { id: c11_cur, filters: [ *zero ] } }
      # - { input: "12", phase_id: phase_a, power: { id: c12_pwr, filters: [ *zero ]         }, current: { id: c12_cur, filters: [ *zero ] } }
      # - { input: "13", phase_id: phase_a, power: { id: c13_pwr, filters: [ *zero ]         }, current: { id: c13_cur, filters: [ *zero ] } }
      # - { input: "14", phase_id: phase_a, power: { id: c14_pwr, filters: [ *zero ]         }, current: { id: c14_cur, filters: [ *zero ] } }
      # - { input: "15", phase_id: phase_a, power: { id: c15_pwr, filters: [ *zero ]         }, current: { id: c15_cur, filters: [ *zero ] } }
      # - { input: "16", phase_id: phase_a, power: { id: c16_pwr, filters: [ *zero ]         }, current: { id: c16_cur, filters: [ *zero ] } }

    # Update total power and balance power readings at the same time.
    on_update:
      then:
        - component.update: total_power
        - component.update: balance_power

  # The total power sensor will be updated after all power sensors update via on_update trigger.
  - platform: template
    id: total_power
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    #lambda: return id(phase_a_power).state + id(phase_b_power).state + id(phase_c_power).state;

  # The balance power sensor will be updated after all power sensors update via on_update trigger.
  - platform: template
    id: balance_power
    update_interval: never
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    lambda: !lambda |-
      return max(0.0f, id(total_power).state
        - id( c1_pwr).state
        - id( c2_pwr).state
        - id( c3_pwr).state
        - id( c4_pwr).state
        - id( c5_pwr).state
        - id( c6_pwr).state
        - id( c7_pwr).state
        - id( c8_pwr).state
        - id( c9_pwr).state
        - id(c10_pwr).state
        - id(c11_pwr).state
        - id(c12_pwr).state
        - id(c13_pwr).state
        - id(c14_pwr).state
        - id(c15_pwr).state
        - id(c16_pwr).state
      );

  - platform: wifi_signal
    name: "RSSI"
    update_interval: 60s
    disabled_by_default: true

  # The copy sensors publish the each power state to Home Assistant.
  - { platform: copy, name: "Phase A Power", source_id: phase_a_power, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Phase B Power", source_id: phase_b_power, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Total Power",   source_id: total_power,   filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_power }
  - { platform: copy, name: "Balance Power", source_id: balance_power, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_power }

  - { platform: copy, name: "${circuit_1} Power", source_id: c1_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_2} Power", source_id: c2_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_3} Power", source_id: c3_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_4} Power", source_id: c4_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_5} Power", source_id: c5_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_6} Power", source_id: c6_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_7} Power", source_id: c7_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_8} Power", source_id: c8_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_9} Power", source_id: c9_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_10} Power", source_id: c10_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_11} Power", source_id: c11_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_12} Power", source_id: c12_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_13} Power", source_id: c13_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_14} Power", source_id: c14_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_15} Power", source_id: c15_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }
  - { platform: copy, name: "${circuit_16} Power", source_id: c16_pwr, filters: *throttle_avg, accuracy_decimals: 0, icon: $icon_circuit }

  - { platform: copy, name: "${circuit_1} Current", source_id: c1_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_2} Current", source_id: c2_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_3} Current", source_id: c3_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_4} Current", source_id: c4_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_5} Current", source_id: c5_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_6} Current", source_id: c6_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_7} Current", source_id: c7_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_8} Current", source_id: c8_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_9} Current", source_id: c9_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_10} Current", source_id: c10_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_11} Current", source_id: c11_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_12} Current", source_id: c12_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_13} Current", source_id: c13_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_14} Current", source_id: c14_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_15} Current", source_id: c15_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }
  - { platform: copy, name: "${circuit_16} Current", source_id: c16_cur, filters: *throttle_avg, accuracy_decimals: 1, icon: $icon_current }

  # The total daily energy sensors to be published to Home Assistant
  - { platform: total_daily_energy, name: "Total Daily Energy", power_id: total_power,      filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "Balance Daily Energy", power_id: balance_power,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_1} Daily Energy", power_id: c1_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_2} Daily Energy", power_id: c2_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_3} Daily Energy", power_id: c3_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_4} Daily Energy", power_id: c4_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_5} Daily Energy", power_id: c5_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_6} Daily Energy", power_id: c6_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_7} Daily Energy", power_id: c7_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_8} Daily Energy", power_id: c8_pwr,  filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_9} Daily Energy", power_id: c9_pwr,   filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_10} Daily Energy", power_id: c10_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_11} Daily Energy", power_id: c11_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_12} Daily Energy", power_id: c12_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_13} Daily Energy", power_id: c13_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_14} Daily Energy", power_id: c14_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_15} Daily Energy", power_id: c15_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }
  - { platform: total_daily_energy, name: "${circuit_16} Daily Energy", power_id: c16_pwr, filters: *throttle_time, accuracy_decimals: 0, restore: false, icon: $icon_meter }

# Core ESPHome Node Configuration.
esphome:
  name: ${name}
  area: ${area}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

# Import the emporia-vue-local v3 community component. 
external_components:
  - source: github://emporia-vue-local/esphome@vue3
    components:
      - emporia_vue

# Set ESPHome preferences.
preferences:
  flash_write_interval: "48h" # The default of 1min is too short (flash chip is rated for approx 100k writes)

# The logger component automatically logs all log messages
logger:
  baud_rate: 0 # Disable the hardware UART logging
  level: INFO  # Minimum log level
  logs:
    component: ERROR  # Silence warnings about execution/blocking time

# Sets up the I²C bus used to communicate with the Emporia Vue hardware.
i2c:
  sda: 5
  scl: 18
  scan: false
  frequency: 150kHz # Reportedly 150kHz works better to eliminate errors
  id: i2c_a

# The Emporia Vue V3 uses an ESP32 board.
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

# Configure the two status LEDs on the Emporia Vue v3 case.
light:
  - platform: status_led
    id: wifi_led
    pin:
      number: 2
      ignore_strapping_warning: true
    restore_mode: ALWAYS_OFF

  - platform: status_led
    id: ethernet_led
    pin: 4
    restore_mode: ALWAYS_OFF

# The restart button platform allows you to restart your node remotely through Home Assistant.
button:
  - platform: restart
    name: Restart
    id: restart_button
    icon: mdi:restart

  - platform: safe_mode
    name: Restart (Safe Mode)
    id: safe_mode_button
    icon: mdi:restart-alert

# The preferred way to get time in ESPHome is using Home Assistant. This is used for the daily energy use calculation.
time:
  - platform: homeassistant

# The ESPHome native API is used to communicate with Home Assistant directly.
api:

# The OTA (Over The Air) enables uploading firmware binaries to your node without having to use a USB cable for uploads.
ota:
  # Create a secure password for pushing OTA updates.
  platform: esphome
  password: "Mlw0112358!"

# The web_server component creates a simple web server on the node that can be accessed through any browser and a simple REST API.
# This is not required for Home Assistant and can be commented out to reduce memory and processor utilization.
web_server:

# The captive portal component in ESPHome is a fallback mechanism used when connecting to WiFi fails.
captive_portal:

# Provide diagnostic information about the platform.
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
      disabled_by_default: true
    mac_address:
      name: "MAC Address"
      disabled_by_default: true
```

### Anything in the logs that might be useful for us?

```txt
Running command 'esphome --dashboard run /config/esphome/emporia.yaml --device 192.168.1.133'
Process exited with return code 1
```
