### ISSUE TITLE
1wire issues compiling again

### ISSUE THREAD

**Issue by deanfourie1** [esphome/issues#7088]
### The problem

Latest update, and now 1wire will not compile.

Any ideas?

Thanks

### Which version of ESPHome has the issue?

2025.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.3

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

one_wire 

### YAML Config

```yaml
esphome:
  name: "fridge-freezer"
  friendly_name: "fridge-freezer"
  comment: 'Ethernet'
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

# Example configuration entry
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

  # Optional manual IP
  manual_ip:
    static_ip: 
    gateway:
    subnet: 255.255.255.224

web_server:
  port: 80
  log: true
  version: 3
  local: True
  include_internal: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

one_wire:
  - platform: gpio
    pin: GPIO14


sensor:
  - platform: dallas_temp
    address: 0x8501215ccdb32e28
    name: "Fridge Temperature"

  - platform: dallas_temp
    address: 0x7e01215ccaaf0728
    name: "Freezer Temperature"
```

### Anything in the logs that might be useful for us?

```txt
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/fridge-freezer/src/esphome/components/gpio/one_wire/gpio_one_wire.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/one_wire/one_wire.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/one_wire/one_wire_bus.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/ota/ota_backend.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/fridge-freezer/src/esphome/components/safe_mode/safe_mode.cpp.o
In file included from src/esphome/components/gpio/one_wire/gpio_one_wire.cpp:1:
src/esphome/components/gpio/one_wire/gpio_one_wire.h:33:7: error: 'int esphome::gpio::GPIOOneWireBus::reset_int()' marked 'override', but does not override
   int reset_int() override;
       ^~~~~~~~~
*** [.pioenvs/fridge-freezer/src/esphome/components/gpio/one_wire/gpio_one_wire.cpp.o] Error 1
========================== [FAILED] Took 2.62 seconds ==========================
```
