### ISSUE TITLE
LVGL Spinbox does not respect the step

### ISSUE THREAD

**Issue by numo68** [esphome/issues#7089]
### The problem

The spinbox as of the LVGL Cookbook https://esphome.io/cookbook/lvgl#climate-control does not respect the `step` configuration. The buttons always increment/decrement the selected digit.

This matches the upstream description in https://docs.lvgl.io/8.4/widgets/extra/spinbox.html ("increments/decrements the value of the Spinbox according to the currently selected digit") but does not match the ESPHome one in https://esphome.io/components/lvgl/widgets#spinbox ("increases the value by one step configured above").

The `esphome/components/lvgl/widgets/spinbox.py` specifies the `SPIN_ACTIONS` that seem to distinguish between incrementing and stepping, the constants defined here however don't seem to be used. It is well possible that the feature is not implemented yet and plans to add an increment/step parameter to the action, in that case fixing the docs to not confuse the users would be probably good.

Also, the `lvgl.spinbox.update` does not work as documented. The value needs to be scaled, i.e. one has to set 200 if `decimal_places` is 1 and intended value is 20.0.

Note that the `step` has another meaning in the upstream: "lv_spinbox_set_step(spinbox, 100) sets which digits to change on increment/decrement. Only multiples of ten can be set, and not for example 3".

### Which version of ESPHome has the issue?

2025.6.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.2

### What platform are you using?

ESP32-IDF

### Board

ESP32-WROVER-E

### Component causing the issue

lvgl

### YAML Config

```yaml
- obj:
      align: TOP_LEFT
      y: 44
      height: 48
      width: 100%
      layout:
        type: GRID
        grid_rows: [ FR(1) ]
        grid_columns: [ FR(1), FR(2), FR(1) ]
      widgets:
        - button:
            grid_cell_row_pos: 0
            grid_cell_column_pos: 0
            grid_cell_x_align: CENTER
            grid_cell_y_align: CENTER
            widgets:
              - label:
                  text_align: CENTER
                  text: "-"
            on_click:
              then:
                - lvgl.spinbox.decrement: spinbox_id
        - spinbox:
            id: spinbox_id
            grid_cell_row_pos: 0
            grid_cell_column_pos: 1
            grid_cell_x_align: CENTER
            grid_cell_y_align: CENTER
            digits: 3
            decimal_places: 1
            range_from: 5.0
            range_to: 30.0
            step: 0.5            
            text_align: CENTER
        - button:
            grid_cell_row_pos: 0
            grid_cell_column_pos: 2
            grid_cell_x_align: CENTER
            grid_cell_y_align: CENTER
            widgets:
              - label:
                  text_align: CENTER
                  text: "+"
            on_click:
              then:
                - lvgl.spinbox.increment: spinbox_id
```

### Anything in the logs that might be useful for us?

```txt

```
