### ISSUE TITLE
LVGL Tabview: Disable scrolling/sliding tabs

### ISSUE THREAD

**Issue by ckarrie** [esphome/issues#7090]
### The problem

Disable scrolling doesn't work for tabsviews.

According to https://forum.lvgl.io/t/v8-0-disable-tabview-sliding/6882/8 I tried to add `scrolling: false` to the `tabview` and the `tabs` item(s) but without success. But it's still horizontal scrollable.

```yaml
            ...
             - tabview:
                  id: tabview_id
                  grid_cell_row_pos: 2 
                  grid_cell_row_span: 2
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 5
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  position: BOTTOM # Position of the tab selector buttons.
                  size: 27%
                  border_width: 1
                  border_color: my_white
                  bg_color: my_black
                  scrollable: false
                  tab_style:
                    #border_color: my_green
                    #border_width: 1
                    text_font: icons_50
                    items:
                      text_color: my_blue
                      bg_color: my_black
                  tabs:
                    - name: "\U000F1AAF"
                      id: tabview_tab_1
                      scrollable: false
                      widgets:
                        - ...
```

### Which version of ESPHome has the issue?

2025.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.3

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

lvgl

### YAML Config

```yaml
esphome:
  name: esp-32d-display-01
  friendly_name: ESP-32D Display 01

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  #level: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"
  services:
    - service: wake_up_or_sleep
      then:
        - script.execute: wake_up_or_sleep
    - service: wake_up
      then:
        - script.execute: wake_up

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid           #iot_wifi_ssid
  password: !secret wifi_password   #iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-32D-Display-01"
    password: "xxx"

captive_portal:

# MQTT
#mqtt:
#  broker: 192.168.178.203
#  username: mqtt-addon
#  password: mqtt
#  discovery: False
#  on_message:
#    # update Timer Seconds
#    - topic: my/custom/topic
#      then:
#        - switch.turn_on: some_switch

# HA-Sensors
sensor:
  - platform: homeassistant
    id: ha_pv
    entity_id: sensor.summe_leistung_pv
    internal: True
    
  - platform: homeassistant
    id: ha_soc_percentage
    entity_id: sensor.albxxx_instantaneous_battery_soc
    internal: True    
    
  - platform: homeassistant
    id: ha_pool_temperature
    entity_id: sensor.shelly1_xxx_temperature
    internal: True    
    # on_value:
    #   - lvgl.indicator.update:
    #       id: temperature_needle
    #       value: !lambda return x * 10;
    #   - lvgl.label.update:
    #       id: temperature_text
    #       text:
    #         format: "%.1f°C"
    #         args: [ 'x' ]
            
  - platform: homeassistant
    id: ha_outdoor_temp
    entity_id: sensor.shellymotion2_xxx_temperature
    internal: True    
    # on_value:
    #   - lvgl.indicator.update:
    #       id: line_outdoor_temp
    #       value: !lambda return x * 10;
    #   - lvgl.label.update:
    #       id: lbl_temp
    #       text:
    #         format: "%.1f°C"
    #         args: [ 'x' ]
            
  # meter_water_flow_needle
  - platform: homeassistant
    id: ha_water_flow
    entity_id: sensor.d1_mini_hof_wasserzahler_flow_rate
    internal: True    
    #on_value:
    #  - lvgl.indicator.update:
    #      id: meter_water_flow_needle
    #      # da die Needle eine höhere Genauigkeit hat (Zwischenwerte), 
    #      # hier mal 10 und bei scale > range_to max. Wert mal 10
    #      value: !lambda return x * 10;  
    #  - lvgl.label.update:
    #      id: meter_water_flow_label
    #      text:
    #        format: "%.1f L/min"
    #        args: [ 'x' ]  

switch:
  - platform: homeassistant
    id: ha_pool_pump
    entity_id: switch.shelly1_xxx
    internal: True    
    #on_turn_on:
    #  - lvgl.widget.update:
    #      id: btn_pool_pump
    #      state:
    #        checked: true
    #on_turn_off:
    #  - lvgl.widget.update:
    #      id: btn_pool_pump
    #      state:
    #        checked: false

  - platform: homeassistant
    entity_id: automation.ausloser_timer_licht_hof
    id: ha_automation_ausloser_timer_licht_hof
    internal: True   
    #on_turn_on:
    #  - lvgl.widget.update:
    #      id: btn_automation_ausloser_timer_licht_hof
    #      state:
    #        checked: true
    #on_turn_off:
    #  - lvgl.widget.update:
    #      id: btn_automation_ausloser_timer_licht_hof
    #      state:
    #        checked: false

  - platform: homeassistant
    entity_id: automation.timer_aktion_buro_luftung_ein
    id: ha_automation_timer_aktion_buro_luftung_ein
    internal: True   
    #on_turn_on:
    #  - lvgl.widget.update:
    #      id: btn_automation_timer_aktion_buro_luftung_ein
    #      state:
    #        checked: true
    #on_turn_off:
    #  - lvgl.widget.update:
    #      id: btn_automation_timer_aktion_buro_luftung_ein
    #      state:
    #        checked: false 

  - platform: homeassistant
    id: ha_dnd
    entity_id: input_boolean.dnd
    internal: True  
    #on_turn_on:
    #  - lvgl.widget.update:
    #      id: sw_dnd
    #      state:
    #        checked: true
    #on_turn_off:
    #  - lvgl.widget.update:
    #      id: sw_dnd
    #      state:
    #        checked: false


time:
  - platform: homeassistant
    id: ha_time
    on_time:
      - seconds: "*"
        then:
          - lvgl.label.update:
              id: lbl_time
              text:
                time_format: "%H:%M:%S"
                time: !lambda return id(ha_time).now();
      - days_of_week: MON
        then: 
          - lvgl.label.update:
              id: lbl_date
              text: 
                time_format: "Montag, %d.%m.%Y"
                time: !lambda return id(ha_time).now();
      - days_of_week: TUE
        then: 
          - lvgl.label.update:
              id: lbl_date
              text: 
                time_format: "Dienstag, %d.%m.%Y"
                time: !lambda return id(ha_time).now();
      - days_of_week: WED
        then: 
          - lvgl.label.update:
              id: lbl_date
              text: 
                time_format: "Mittwoch, %d.%m.%Y"
                time: !lambda return id(ha_time).now();                                
      - days_of_week: THU
        then: 
          - lvgl.label.update:
              id: lbl_date
              text: 
                time_format: "Donnerstag, %d.%m.%Y"
                time: !lambda return id(ha_time).now();
      - days_of_week: FRI
        then: 
          - lvgl.label.update:
              id: lbl_date
              text: 
                time_format: "Freitag, %d.%m.%Y"
                time: !lambda return id(ha_time).now();
      - days_of_week: SAT
        then: 
          - lvgl.label.update:
              id: lbl_date
              text: 
                time_format: "Samstag, %d.%m.%Y"
                time: !lambda return id(ha_time).now();                                                
      - days_of_week: SUN
        then: 
          - lvgl.label.update:
              id: lbl_date
              text: 
                time_format: "Sonntag, %d.%m.%Y"
                time: !lambda return id(ha_time).now();  

# Control Sensors
number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 600
    step: 5
    mode: box
    
script:
  - id: wake_up_or_sleep
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:
            - light.turn_on: display_backlight
          else:
            - logger.log: "Sending LVGL to sleep"
            - light.turn_off: display_backlight
            - lvgl.pause:
  - id: wake_up
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:
            - light.turn_on: display_backlight

############################
# Fonts und Colors
############################

font:
  - file: "fonts/RobotoCondensed-Regular.ttf"
    id: roboto_56
    size: 56
    bpp: 4
    glyphsets:
      - GF_Latin_Core

  - file: "fonts/RobotoCondensed-Regular.ttf"
    id: roboto_25
    size: 25
    bpp: 4
    glyphsets:
      - GF_Latin_Core      

  - file: "fonts/RobotoCondensed-Regular.ttf"
    id: roboto_14
    size: 14
    bpp: 4
    glyphsets:
      - GF_Latin_Core        

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_50
    size: 50
    bpp: 4
    glyphs: [
      "\U000F1AAF", # heating-coil
      "\U000F0529", # tooth-outline
      "\U000F15C6", # bird
      "\U000F18B4", # dolphin
      "\U000F1589", # butterfly,
      "\U000F1A61", # rabbit
      ]        

color:
  - id: ha_blue
    hex: 51c0f2
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_gray
    red: 50%
    green: 50%
    blue: 50%
  - id: my_orange
    red: 100%
    green: 50%
    blue: 0%
  - id: my_teal
    red: 0%
    green: 100%
    blue: 100%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%
  - id: color_dark_blue
    hex: 002b36              

light:
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: display_backlight
    restore_mode: ALWAYS_ON
    
spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  #- id: touch
  #  clk_pin: GPIO25
  #  mosi_pin: GPIO32
  #  miso_pin: GPIO39

# Setup a pin to control the backlight
output:
  - platform: ledc
    pin: GPIO27
    id: backlight_pwm

display:
  - platform: ili9xxx
    id: main_display
    model: ILI9486
    spi_id: tft
    cs_pin: GPIO15
    dc_pin: GPIO2
    invert_colors: false
    auto_clear_enabled: false
    update_interval: never
    dimensions: 320x480
    #rotation: 180
    rotation: 90
    #color_palette: 8BIT

lvgl:
  buffer_size: 15%
  #disp_bg_color: my_black
  #disp_bg_opa: COVER
  displays:
    - main_display
  touchscreens:
    - main_touch
  pages:
    - id: main_page
      bg_color: color_dark_blue #ha_blue #my_black
      widgets:
        - obj:
            align: TOP_LEFT
            width: 480
            height: 320
            pad_all: 6
            radius: 0
            bg_color: my_black
            #bg_opa: 50%
            border_opa: TRANSP
            layout:
              type: GRID
              grid_columns: [FR(64), FR(64), FR(64), FR(64), FR(64)] # 5 cols = 320 / 5 = 
              grid_rows: [FR(64), FR(20), FR(332), FR(64)] # 4 rows, one bin middle row
            widgets:
              - label:
                  id: lbl_time
                  #pad_left: 12
                  text: "Connecting..."
                  grid_cell_row_pos: 0 
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 5
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: CENTER
                  pad_top: 1
                  text_color: my_white
              - label:
                  id: lbl_date
                  grid_cell_row_pos: 1 
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 5
                  text_font: roboto_14
                  text_color: my_white
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: CENTER
              - tabview:
                  id: tabview_id
                  grid_cell_row_pos: 2 
                  grid_cell_row_span: 2
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 5
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  position: BOTTOM # Position of the tab selector buttons.
                  size: 27%
                  border_width: 1
                  border_color: my_white
                  bg_color: my_black
                  scrollable: false
                  tab_style:
                    #border_color: my_green
                    #border_width: 1
                    text_font: icons_50
                    items:
                      text_color: my_blue
                      bg_color: my_black
                  tabs:
                    - name: "\U000F1AAF"
                      id: tabview_tab_1
                      scrollable: false
                      widgets:
                        - obj:
                            align: TOP_LEFT
                            width: 100%
                            height: 100%
                            pad_all: 0
                            radius: 0
                            border_width: 0
                            bg_color: my_black
                            ##bg_opa: 50%
                            #border_opa: TRANSP
                            layout:
                              type: GRID
                              grid_columns: [FR(25), FR(25), FR(25), FR(25)]
                              grid_rows: [FR(50), FR(50)]

                            widgets:
                              - label:
                                  grid_cell_row_pos: 0 
                                  grid_cell_column_pos: 0
                                  grid_cell_column_span: 2
                                  text_font: roboto_25
                                  text: "Fußboden-Heizung"
                                  text_color: my_white
                                  grid_cell_x_align: CENTER
                                  grid_cell_y_align: CENTER

                              - button:
                                  id: btn_fussbodenheizung
                                  grid_cell_row_pos: 0 
                                  grid_cell_column_pos: 2
                                  grid_cell_column_span: 2
                                  checkable: true
                                  grid_cell_x_align: STRETCH
                                  grid_cell_y_align: STRETCH
                                  widgets:
                                    - label:
                                        align: CENTER
                                        text: 'Aktivieren'
                                        text_font: roboto_25

                              - label:
                                  grid_cell_row_pos: 1 
                                  grid_cell_column_pos: 0
                                  grid_cell_column_span: 2
                                  text_font: roboto_25
                                  text: "noch 1:30 h"
                                  text_color: my_white
                                  grid_cell_x_align: CENTER
                                  grid_cell_y_align: CENTER

                              - button:
                                  id: btn_fussbodenheizung_minus
                                  grid_cell_row_pos: 1 
                                  grid_cell_column_pos: 2
                                  checkable: true
                                  grid_cell_x_align: STRETCH
                                  grid_cell_y_align: STRETCH
                                  widgets:
                                    - label:
                                        align: CENTER
                                        text: '-'
                                        text_font: roboto_25      
                              - button:
                                  id: btn_fussbodenheizung_plus
                                  grid_cell_row_pos: 1 
                                  grid_cell_column_pos: 3
                                  checkable: true
                                  grid_cell_x_align: STRETCH
                                  grid_cell_y_align: STRETCH
                                  widgets:
                                    - label:
                                        align: CENTER
                                        text: '+'
                                        text_font: roboto_25                                                                    



                    - name: "\U000F0529"
                      id: tabview_tab_2
                      widgets:
                        - label:
                            text: "Zahnputzen"
                            text_font: roboto_14
                    - name: "\U000F15C6"
                      id: tabview_tab_3
                      widgets:
                        - label:
                            text: "Licht"
                            text_font: roboto_14
                    - name: "\U000F18B4"
                      id: tabview_tab_4
                      widgets:
                        - label:
                            text: "TVs"
                            text_font: roboto_14
                    - name: "\U000F1589"
                      id: tabview_tab_5
                      widgets:
                        - label:
                            text: "Automationen"   
                            text_font: roboto_14
                    - name: "\U000F1A61"
                      id: tabview_tab_6
                      widgets:
                        - label:
                            text: "Wetter"                     
                            text_font: roboto_14                                                                                         

    - id: idle_page
      bg_color: my_black #ha_blue #my_black
      widgets:
        - obj:
            align: TOP_LEFT
            width: 480
            height: 320
            pad_all: 6
            radius: 0
            bg_color: my_black
            #bg_opa: 50%
            border_opa: TRANSP
            layout:
              type: GRID
              grid_columns: [FR(320)] # 1 col
              grid_rows: [FR(160), FR(160), FR(160)] # 3 rows, one bin middle row
            widgets:
              - label:
                  id: lbl_time_idle
                  pad_left: 12
                  text: "12:35:12"
                  grid_cell_row_pos: 1 
                  grid_cell_column_pos: 0
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: CENTER
                  text_color: my_gray              

  theme:
    arc:
      scroll_on_focus: true
    slider:
      scroll_on_focus: true
    button:
      bg_color: 0x4D93DD
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 2
      pressed: # set some button colors to be different in pressed state
        bg_color: 0xFFD512
      checked: # set some button colors to be different in checked state
        bg_color: 0xF53B3B
        text_color: 0xfff300
      scroll_on_focus: true
      text_font: roboto_56
      text_color: my_white
      focused:
        border_color: my_gray
    label:
      # outline_width: 1 ## for testing the grid, comment out when done
      text_font: roboto_56
      text_color: my_white
  on_idle:
    timeout: !lambda "return (id(display_timeout).state * 1000);"
    then:
      - logger.log: "LVGL is idle"
      - light.turn_off: display_backlight
      - lvgl.pause:

touchscreen:
  - platform: xpt2046
    id: main_touch
    #spi_id: touch
    cs_pin: GPIO33
    interrupt_pin: GPIO36
    #update_interval: 50ms
    threshold: 400
    calibration:
      x_min: 340   # Flip X by swapping min and max
      x_max: 3860  # Flip X by swapping min and max
      y_min: 280   # Flip Y by swapping min and max
      y_max: 3860  # Flip Y by swapping min and max
    transform:
      mirror_x: true  # falls display.rotation: 180
      mirror_y: true
      swap_xy: True
      
    on_touch:
      - lambda: |-
            ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                touch.x,
                touch.y,
                touch.x_raw,
                touch.y_raw
                );
    on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:
            - light.turn_on: display_backlight
```

### Anything in the logs that might be useful for us?

```txt
[21:53:05][I][cal:654]: x=90, y=220, x_raw=3194, y_raw=1398
[21:53:05][D][xpt2046:055]: Touchscreen Update [1364, 3563], z = 561
[21:53:05][I][cal:654]: x=40, y=223, x_raw=3563, y_raw=1364
[21:53:05][D][xpt2046:055]: Touchscreen Update [1354, 3651], z = 670
[21:53:05][D][xpt2046:055]: Touchscreen Update [1333, 3679], z = 753
[21:53:05][D][xpt2046:055]: Touchscreen Update [1328, 3678], z = 801
[21:53:08][D][xpt2046:055]: Touchscreen Update [2137, 2061], z = 438
[21:53:08][I][cal:654]: x=245, y=153, x_raw=2061, y_raw=2137
[21:53:09][D][xpt2046:055]: Touchscreen Update [2129, 1886], z = 1376
[21:53:09][I][cal:654]: x=269, y=154, x_raw=1886, y_raw=2129
[21:53:09][D][xpt2046:055]: Touchscreen Update [2140, 1976], z = 1504
[21:53:09][D][xpt2046:055]: Touchscreen Update [2026, 1966], z = 1663
[21:53:09][D][xpt2046:055]: Touchscreen Update [1991, 2626], z = 1287
[21:53:09][D][xpt2046:055]: Touchscreen Update [2072, 3149], z = 1350
[21:53:09][D][xpt2046:055]: Touchscreen Update [1997, 3786], z = 874
[21:53:10][D][xpt2046:055]: Touchscreen Update [2459, 1943], z = 926
[21:53:10][I][cal:654]: x=261, y=125, x_raw=1943, y_raw=2459
[21:53:12][D][xpt2046:055]: Touchscreen Update [2236, 3195], z = 742
[21:53:12][I][cal:654]: x=90, y=145, x_raw=3195, y_raw=2236
[21:53:12][D][xpt2046:055]: Touchscreen Update [2414, 3256], z = 1446
[21:53:12][D][xpt2046:055]: Touchscreen Update [2442, 3232], z = 1684
[21:53:12][D][xpt2046:055]: Touchscreen Update [2438, 3198], z = 1526
[21:53:12][D][xpt2046:055]: Touchscreen Update [2461, 3207], z = 1455
[21:53:12][D][xpt2046:055]: Touchscreen Update [2429, 3099], z = 1258
[21:53:12][D][xpt2046:055]: Touchscreen Update [2470, 3051], z = 1325
[21:53:12][D][xpt2046:055]: Touchscreen Update [2069, 2438], z = 1245
[21:53:12][D][xpt2046:055]: Touchscreen Update [2500, 2852], z = 1691
[21:53:12][D][xpt2046:055]: Touchscreen Update [2505, 2715], z = 1740
[21:53:12][D][xpt2046:055]: Touchscreen Update [2575, 1573], z = 1661
```

### Additional information

https://github.com/user-attachments/assets/64658d45-3df7-4d35-863e-52ae47411a63
