### ISSUE TITLE
Time-Based Cover Does Not Send Stop Command for Partial Positions When Using has_built_in_endstop: true

### ISSUE THREAD

**Issue by sendorm** [esphome/issues#7093]
### The problem

When using the time_based cover platform in ESPHome with has_built_in_endstop: true, the cover does not send a stop command when a partial position (e.g., 50%) is set from Home Assistant. Instead, the cover continues moving past the intended position and only stops at the physical endstop. This makes it impossible to reliably set the cover to intermediate positions.

Expected behavior:

When a partial position is set (any value between fully open and fully closed), ESPHome should calculate the required movement time and send a stop command when the target position is reached, even if has_built_in_endstop: true is set.

Stop commands should only be omitted when the target is exactly fully open or fully closed and endstops are enabled.

Actual behavior:

With has_built_in_endstop: true, ESPHome never sends a stop command for partial positions, causing the cover to ignore the requested position and move until a physical endstop is reached.

This issue prevents the use of percentage-based positioning with covers that have built-in endstops and rely on RF or similar stateless control. 

### Which version of ESPHome has the issue?

2025.5.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2025.5.1

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

Time-Based

### YAML Config

```yaml
`- platform: time_based
  name: 'study_cover'
  device_class: shutter
  assumed_state: true
  has_built_in_endstop: true

  close_action:
    - script.execute:
        id: send_dooya
        code_hex: '1235742833'
  close_duration: 28s

  stop_action:
    - script.execute:
        id: send_dooya
        code_hex: '1235742855'

  open_action:
    - script.execute:
        id: send_dooya
        code_hex: '123574281e'
  open_duration: 32s`
```

### Anything in the logs that might be useful for us?

```txt

```
