### ISSUE TITLE
Reboot frequently Reset: Exception|Fatal exception:28 flag:2 (Exception)

### ISSUE THREAD

**Issue by AbianTang** [esphome/issues#7096]
<img width="548" alt="Image" src="https://github.com/user-attachments/assets/96a2a723-456c-42c9-8734-ed55e927763d" />

### The problem

<img width="2204" alt="Image" src="https://github.com/user-attachments/assets/fdcb47d6-6df7-454d-a933-1895c043324c" />

变为 2025.5.1|Flash: 4096kB Speed:40MHz Mode:DOUT|Chip: 0x000f9dbb|SDK: 2.2.2-dev(38a443e)|Core: 3.1.2|Boot: 31|Mode: 1|CPU: 80|Flash: 0x00164020|Reset: Exception|Fatal exception:29 flag:2 (Exception) epc1:0x4000df64 epc2:0x00000000 epc3:0x00000000 excvaddr:0x
06:04:43 - 28秒钟前
不再可用
06:03:27 - 2分钟前
变为 2025.5.1|Flash: 4096kB Speed:40MHz Mode:DOUT|Chip: 0x000f9dbb|SDK: 2.2.2-dev(38a443e)|Core: 3.1.2|Boot: 31|Mode: 1|CPU: 80|Flash: 0x00164020|Reset: Exception|Fatal exception:28 flag:2 (Exception) epc1:0x40226578 epc2:0x00000000 epc3:0x00000000 excvaddr:0x
06:03:19 - 2分钟前
不再可用
06:03:15 - 2分钟前
变为 2025.5.1|Flash: 4096kB Speed:40MHz Mode:DOUT|Chip: 0x000f9dbb|SDK: 2.2.2-dev(38a443e)|Core: 3.1.2|Boot: 31|Mode: 1|CPU: 80|Flash: 0x00164020|Reset: Exception|Fatal exception:28 flag:2 (Exception) epc1:0x40226578 epc2:0x00000000 epc3:0x00000000 excvaddr:0x
05:59:51 - 5分钟前
不再可用
05:59:46 - 5分钟前
变为 2025.5.1|Flash: 4096kB Speed:40MHz Mode:DOUT|Chip: 0x000f9dbb|SDK: 2.2.2-dev(38a443e)|Core: 3.1.2|Boot: 31|Mode: 1|CPU: 80|Flash: 0x00164020|Reset: Exception|Fatal exception:28 flag:2 (Exception) epc1:0x40226578 epc2:0x00000000 epc3:0x00000000 excvaddr:0x
05:47:29 - 18分钟前
不再可用
05:47:24 - 18分钟前

### Which version of ESPHome has the issue?

2025.5.1 

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

captive_portal:

debug:
  update_interval: 1s

# Example configuration entry

```yaml

esphome:
  name: 8266dht11
  friendly_name: 8266dht11

esp8266:
  board: nodemcuv2
  restore_from_flash: True

# 串口1输出日志
logger:
  hardware_uart: UART1
  baud_rate: 0
  level: DEBUG
  

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxx="

ota:
  - platform: esphome
    password: "9babffc32exxxxxxxxxxxxa1231"

wifi:
  ssid: "xxxxxx"
  password: "xxxxxxxx"



sensor:

     

  - platform: debug
    free:
      name: "Heap Free"
    fragmentation:
      name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    device_class: "signal_strength"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: "signal_strength"


  # DHT11 sensors on bus_a
  - platform: dht
    pin: D3
    temperature:
      name: "Temperature"
      id: inside_temperature 
  
    humidity:
      name: "Humidity"
      id: humidityok
    update_interval: 3s
    model: "DHT11"

  - platform: adc
    pin: A0
    name: "VCC Voltage"
    id: vcc_voltage
    update_interval: 3s


  - platform: template
    name: "gas_meter"
    id: gas_meter
    lambda: |-
      return id(counter_int);
    unit_of_measurement: 'm³'
    state_class: 'total_increasing'
    accuracy_decimals: 2
    device_class: 'gas'
    update_interval: 60s


    

  - platform: template
    name: "Dew Point Magnus-Tetens"
    unit_of_measurement: "°C"
    id: dew_point
    update_interval: 3s
    lambda: |-
      if (!id(inside_temperature).has_state() || !id(humidityok).has_state()) {
        return NAN;
      }

      float temperature = id(inside_temperature).state;
      float humidity = id(humidityok).state;

      if (isnan(temperature) || isnan(humidity) || humidity < 0 || humidity > 100) {
        return NAN;
      }

      const float a = 17.271;
      const float b = 237.7;
      float alpha = (a * temperature) / (b + temperature) + log(humidity / 100.0);
      return (b * alpha) / (a - alpha);

      
      



  #Device UPTIME
  - platform: uptime
    name: Uptime
    type: seconds
    id: sys_uptime
    update_interval: 60s



switch:


  - platform: gpio
    name: "Kitchen switch"
    pin:
      number: D1
      inverted: True
    device_class: switch
    restore_mode: ALWAYS_OFF
    id: kitchen_switch  # 添加 ID，便于自动化引用



binary_sensor:

  - platform: gpio
    pin: D7
    name: gpio out pin presence
    device_class: presence  
    on_press:
      then:
        - switch.turn_on: kitchen_switch
    on_release:
      then:
        - switch.turn_off: kitchen_switch

    


  - platform: gpio
    pin:
      number: D0
      inverted: True
    name: "Gas Leak Detector"
    device_class: safety
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - homeassistant.service:
            service: notify.notify
            data:
              message: "天然气警告: 检测到气体泄漏!"


  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_off: 1000ms
    name: gas_counter_key_point
    id: gas_counter_key_point
    icon: mdi:gas-burner
    on_release:
      then:
       - lambda: |-
            id(counter_int) += 0.01;
            id(gas_meter).publish_state(id(counter_int));            


text_sensor:
  - platform: debug
    device:
      name: "Device Info"





globals:
  - id: counter_int
    type: float
    restore_value: yes
    initial_value: '1939.62'  #燃气表目前的数值


number:
  - platform: template
    id: initial_value
    name: “gas_meter值校正”
    mode: box
    optimistic: true
    min_value: -99999
    max_value: 99999
    step: 0.01
    restore_value: false
    initial_value: 0
    on_value:
      then:
        - lambda: |-
            id(counter_int) += id(initial_value).state;
            id(gas_meter).publish_state(id(counter_int));
```
