### ISSUE TITLE
ili9341 white screen problem

### ISSUE THREAD

**Issue by off112a** [esphome/issues#7100]
### The problem

Hi,

I just bought a ili9341 and got the problem with white screen. I tried with color_palette: 8BIT. The error in my log disappears but I have still the white screen. 

I'm using a esp-wrover with 8MB psram.

If I enable psram it will crash at boot and after a whole boot into safe mode. 

### Which version of ESPHome has the issue?

2025.5.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.3

### What platform are you using?

ESP32

### Board

esp32-wrover

### Component causing the issue

ili9341

### YAML Config

```yaml
esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    

#psram:

spi:
  clk_pin: GPIO16
  mosi_pin: GPIO17
  miso_pin: GPIO26
  id: tft_spi

display:
  - platform: ili9xxx
    model: ILI9341
    cs_pin: GPIO19
    dc_pin: GPIO32
    reset_pin: GPIO18
    data_rate: 20MHz
    rotation: 270
    invert_colors: false
    color_palette: 8BIT
    color_order: bgr
    show_test_card: true


output:
  - platform: ledc
    pin: GPIO04
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON
```

### Anything in the logs that might be useful for us?

```txt

```
