### ISSUE TITLE
No WiFi when using "it.filled_rectangle" with ssd1306 after update ESPHomeBuilder from V2025.2.1

### ISSUE THREAD

**Issue by schemart** [esphome/issues#7101]
### The problem

Hello,
I got exactly the same problem as already posted here:
https://github.com/esphome/issues/issues/2019:

WiFi connection can not be established, when "it.filled_rectangle" is used. There's no problem with "it.rectangle".

This problem came after an update with ESPHomeBuilder  > 2025.2.1 (don't know the breaking version exactly) 
Curent HA Version is 2025.5.3. But this version doesn't matter. 

### Which version of ESPHome has the issue?

> 2025.2.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

esp12e

### Component causing the issue

ssd1306 / sh1106

### YAML Config

```yaml
...

captive_portal:
    
font:
  - file: "fonts/Roboto-Black.ttf"
    id: font_01
    size: 10

globals:
  - id: total_pulses
    type: int
    restore_value: False
    initial_value: '728227'  # mit diesem Wert startet der Gaszählerstand
    
binary_sensor:
  - platform: gpio
    id: internal_pulse_counter
    pin:
      number: GPIO14
      mode: INPUT
    name: "Live-Impuls"
    filters:
      - delayed_on: 100ms
    on_press:
      then:
        - lambda: id(total_pulses) += 1;
        - output.turn_on: led  # für die LED, zur Anzeige des Schaltvorgangs
    on_release:
      then:
        - output.turn_off: led  # für die LED, zur Anzeige des Schaltvorgangs
    #LED blinkt, wenn ein Signal vom Reedkontakt erkannt wird
output:
  - platform: gpio # Die interne LED auf dem Board
    pin: GPIO16
    id: 'led'
    inverted: False

sensor: 
  - platform: template
    name: "hwr-gasverbrauch"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:fire"
    accuracy_decimals: 2
    ##(0.1qm/pulse)
    #lambda: |-
    #  return id(total_pulses) * 0.01; 
      
  - platform: adc
    pin: A0
    name: "water_level_pct"
    id: water_level_pct
    unit_of_measurement: "%"
    update_interval: 900s
    #update_interval: 10s
    filters:
      #- clamp:
      #    min_value: 0.14
      #    max_value: 0.7
      #    ignore_out_of_range: true
      - multiply: 5.0
      - calibrate_linear:
        # TankDia = 198cm ->308[L/dm] x height[dm]
        # Restpegel = 0,20m
        # Überlauf über Grund = 1,14m
        # Vout = 5V*(0.09 * P + 0.04) ± 5.0% VFSS
        # P = 11,11 * (Vout/5V) - 0.04
        #~5V/m * 0,94m = 4,7V /5 (R-Teiler da ADC 1V max.)= 0.94V = max
        - 0.0 -> 0 # Wert bei 0-Druck
        #- 4.7 -> 1 #0.95m (Überlaufhöhe) with multiply 5.0
        - 4.0 -> 1 #bei Voll auf 1 bzw. 100% angepasst

i2c:
  - id: bus_a
    sda: 4
    scl: 5
    scan: false
    setup_priority: -100

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    #reset_pin: D0
    i2c_id: bus_a
    address: 0x3C
    setup_priority: -100
    #rotation: 90
    flip_y: True
    update_interval: 10s
    contrast: 20%
    #DispTankwith: 40
    #DispTankheight: 60
    lambda: |-
      const int max_Vol = 2894;
      int rect_fill_height = (60 * id(water_level_pct).state);
      char buf_1[32];
      char buf_2[32];
      it.rectangle(1, 1, 40, 60);
      //it.filled_rectangle(1, (60 - rect_fill_height), 40, rect_fill_height);
      sprintf(buf_1, "Lvl: %.1f %%", (100 * id(water_level_pct).state));
      it.print(50, 15, id(font_01), buf_1);
      sprintf(buf_2, "Vol: %i Lit", int(max_Vol * id(water_level_pct).state));
      it.print(50, 30, id(font_01), buf_2);
```

### Anything in the logs that might be useful for us?

```txt

```
