### ISSUE TITLE
ESPHOME Voice Pipeline URL Error on 1st Request

### ISSUE THREAD

**Issue by GSVil** [esphome/issues#7103]
### The problem

Basically TTS does not create an audio file, so the ESPHOME device errors on trying to process the FLAC file.  This only occurs when using the my ESPHome assistants to initialize the voice pipeline. On face value it looks like its a HA Core issue, but it only started happening after upgrading my ESPHOME to 2025.5.0, and the problem appears to get worst with 2025.5.1 and 2025.5.2. It also only happens on the 1st request, after that it works perfectly fine. When left alone for a while, it would happen again. If I stop and start the voice assistant in ESPHOME on_wake_word_detected (workaround for problem, commented out in YAML below) the problem does not occur.

### Which version of ESPHome has the issue?

2025.5.0 and higher

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.3

### What platform are you using?

ESP32-IDF

### Board

ESP32-S3

### Component causing the issue

Media Player

### YAML Config

```yaml
################################################################################
# Substitution Variables
################################################################################
substitutions:
  device_internal_name: bar_voice_assistant
  friendly_name: Bar Voice Assistant
#  device_ip_address: 192.168.1.131
  device_wifi_name: bar_voice_assistant-wifi
  device_sampling_time: 30s

################################################################################
# Import Remote Package
################################################################################
#packages:
#  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main

################################################################################
# Board Configuration
################################################################################
esphome:
  name: ${device_internal_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

  platformio_options:
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
#    board_upload.maximum_ram_size: 524288

  on_boot:
    - light.turn_on:
        id: led_ww
        blue: 100%
        brightness: 60%
        effect: fast pulse
    - delay: 10s
    - light.turn_off:
        id: led_ww

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
#    type: arduino

    sdkconfig_options: # Only for esp-idf, not arduino framework
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"

psram:
  mode: octal  # quad for N8R2 and octal for N16R8
  speed: 80MHz
    
################################################################################
# Enable logging
################################################################################
logger:

################################################################################
# Enable Home Assistant API
################################################################################
api:
  encryption:    
    key: !secret api_encryption_key

################################################################################
# OTA
################################################################################
ota:
  platform: esphome
  password: !secret wifi_password

safe_mode:
  disabled: false
  reboot_timeout: 10min
  num_attempts: 5

################################################################################
# WiFi
################################################################################

wifi:
  networks:
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # 192.168.4.1
  ap:
    ssid: ${device_wifi_name}
    password: !secret wifi_password

captive_portal:



################################################################################
# Time
################################################################################
time:
  - platform: homeassistant

################################################################################
# Global Variables
################################################################################

globals:
  - id: voice_assistant_active
    type: int
    restore_value: no
    initial_value: '0'

################################################################################
# Binary Sensors
################################################################################
binary_sensor:
  # ESP Status
  - platform: status
    name: "Status"
    id: ${device_internal_name}_status
  - platform: gpio
    pin:
      number: GPIO1
      inverted: true
      mode:
        input: true  
        pullup: true
    name: "Momentary Button"
    id: momentary_button
    on_press:
      then:
        - light.toggle: button_led  # Toggle the LED light on button press

# Voice Assistant
  - platform: status
    name: API Connection
    id: api_connection
    filters:
      - delayed_on: 1s
    on_press:
      - if:
          condition:
            switch.is_on: use_wake_word
          then:
            - voice_assistant.start_continuous:
    on_release:
      - if:
          condition:
            switch.is_on: use_wake_word
          then:
            - voice_assistant.stop:
    
################################################################################
# Sensors
################################################################################
sensor:
  #-------------------------------------------------------------------------------
  # ESP Generic Sensors
  #-------------------------------------------------------------------------------

#   - platform: template
#     name: "Audio Stream Status"
#     id: ${device_internal_name}_audio_stream_sensor
#     lambda: |-
#      if (id(bar_voice_assistant_speaker).state == MediaPlayerState::MEDIA_PLAYER_STATE_PLAYING) {
#        return 1;
#      } else {
#        return 0;
#      }
#     update_interval: 1s

 # WiFi
 # - platform: wifi_signal
 #   name: "WiFi Signal Sensor"
 #   id: ${device_internal_name}_wifi_signal_sensor
 #   update_interval: ${device_sampling_time}


################################################################################
# Text Sensors
################################################################################
text_sensor:
  #-------------------------------------------------------------------------------
  # ESP32 internal sensors
  #-------------------------------------------------------------------------------
  - platform: wifi_info
    ip_address:
      name: IP Address
      id: ${device_internal_name}_ip_address
    mac_address:
      name: Mac Wifi Address
      id: ${device_internal_name}_mac_address

################################################################################
# Switch
################################################################################
switch:
  - platform: restart
    name: "Restart"
    id: device_restart
  
  - platform: safe_mode
    name: Use Safe Mode
    id: device_safe_mode

# Voice Assistant On or Off
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - lambda: id(va).set_use_wake_word(true);
      - if:
          condition:
            not:
              - voice_assistant.is_running
          then:
            - voice_assistant.start_continuous    
    on_turn_off:
      - voice_assistant.stop
      - lambda: id(va).set_use_wake_word(false);


################################################################################
# Light
################################################################################

################################################################################
# Lights and LEDs
################################################################################

output:
  - platform: ledc
    id: button_led_out
    pin: GPIO2
    max_power: 100%

light:
  - platform: monochromatic
    name: "Button LED"
    id: button_led
    output: button_led_out
    default_transition_length: 
      seconds: 0.1
  - platform: esp32_rmt_led_strip
    id: led_ww
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
#    rmt_channel: 0
    chipset: ws2812
    name: "on board light"
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - random:
      - random:
          name: Random Effect With Custom Values
          transition_length: 5s
          update_interval: 7s

################################################################################
# Audio and MediaPlayer
################################################################################

i2s_audio:
  - id: i2s_speaker
    i2s_lrclk_pin: GPIO6 #LRC Pin of the MAX98357A Audio Amplifier
    i2s_bclk_pin: GPIO7  #BCLK Pin of the MAX98357A Audio Amplifier
  - id: i2s_in
    i2s_lrclk_pin: GPIO17  #WS pin on the INMP441
    i2s_bclk_pin: GPIO18 #SCK pin on the INMP441

microphone:
  - platform: i2s_audio
    id: va_mic
    adc_type: external
    i2s_din_pin: GPIO16 #SD pin on the INMP441
    channel: left
    pdm: false
    i2s_audio_id: i2s_in
    bits_per_sample: 32 bit

speaker:
  - platform: i2s_audio
    id: speaker_id
    i2s_audio_id: i2s_speaker
    dac_type: external
    i2s_dout_pin: GPIO8   #  DIN Pin of the MAX98357A Audio Amplifier
    channel: mono
    sample_rate: 44100
    timeout: 5s
  - platform: mixer
    id: mixer_speaker_id
    output_speaker: speaker_id
#    task_stack_in_psram: true
    source_speakers:
      - id: announcement_spk_mixer_input
      - id: media_spk_mixer_input
        timeout: 5s

media_player:
  - platform: speaker
    name: "Media Player"
    id: media_player_id
    media_pipeline:
        speaker: media_spk_mixer_input
        num_channels: 1
    announcement_pipeline:
        speaker: announcement_spk_mixer_input
        num_channels: 1
#    task_stack_in_psram: true

    on_play:
      - logger.log: "Track On_Play!"
      - mixer_speaker.apply_ducking:
          id: media_spk_mixer_input
          decibel_reduction: 0

    on_announcement:
      - logger.log: "Track On_Anouncement"
      - mixer_speaker.apply_ducking:
          id: media_spk_mixer_input
          decibel_reduction: 50
#      - delay: 10sec 
#      - mixer_speaker.apply_ducking:
#          id: media_spk_mixer_input
#          decibel_reduction: 0

    on_idle:
      - logger.log: "Track On_Idle"

    on_pause:
      - logger.log: "Track On_Pause"


################################################################################
# Voice Assistant
################################################################################

voice_assistant:

# Assistant Definition 
  microphone:
    microphone: va_mic
    gain_factor: 4
  id: va
  noise_suppression_level: 4
  auto_gain: 31dBFS
  volume_multiplier: 3
  use_wake_word: false
  media_player: media_player_id


# Assistant Rules and Behaviours
  on_wake_word_detected:
    - logger.log: "Track - Voice - on_wake_word_detected"
    - light.turn_on:
        id: led_ww
        effect: "None"
        red: 0%
        green: 100%
        blue: 0%
#    - voice_assistant.stop
#    - lambda: id(va).set_use_wake_word(false);
    - mixer_speaker.apply_ducking:
        id: media_spk_mixer_input
        decibel_reduction: 50
#    - delay: 500ms
#    - voice_assistant.start
#    - wait_until:
#        not:
#          - voice_assistant.is_running
#    - voice_assistant.stop
#    - delay: 500ms
#    - lambda: id(va).set_use_wake_word(true);
#    - voice_assistant.start_continuous:
        
  on_listening: 
    - logger.log: "Track - Voice - on_listening"
    - light.turn_on:
        id: led_ww           
        red: 30%
        green: 30%
        blue: 70%
        brightness: 60%
        effect: fast pulse 
  
  on_stt_end:
    - logger.log: "Track - Voice - on_stt_end"
    - light.turn_on:
        id: led_ww
        effect: "None"
        red: 0%
        green: 100%
        blue: 0%

  on_error: 
    - logger.log: "Track - Voice - on_error"
    - light.turn_on:
        id: led_ww
        effect: "None"
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - switch.turn_off: use_wake_word
          - delay: 1sec 
          - switch.turn_on: use_wake_word      

#### Dont Enable
#  on_tts_start:
#    - homeassistant.service: 
#        service: tts.speak
#        data:
#          media_player_entity_id: media_player.bar_voice_assistant_speaker
#          message: !lambda 'return x;'
#          entity_id: tts.home_assistant_cloud  
#### Dont Enable
  
  on_idle:
    - logger.log: "Track - Voice - on_idle"
    - globals.set:
        id: voice_assistant_active
        value: '0'

  on_client_connected:
    - logger.log: "Track - Voice - on_client_connected"
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.start_continuous:

  on_client_disconnected:
    - logger.log: "Track - Voice - on_client_disconnected"
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.stop:

  on_end:
    - logger.log: "Track - Voice - on_end"
    - light.turn_off:
        id: led_ww
```

### Anything in the logs that might be useful for us?

```txt
Could not find anything after debugging with:
logger:
  default: error
  logs:
    homeassistant.components.tts: debug
    homeassistant.components.ffmpeg: debug
    homeassistant.components.cloud: debug
    homeassistant.components.shell_command: debug
    homeassistant.components.assist_pipeline: debug
    homeassistant.components.cloud.tts: debug
```

### Additional information

[logs_bar-voice-assistant_logs.txt](https://github.com/user-attachments/files/20643758/logs_bar-voice-assistant_logs.txt)

[11:33:16][E][speaker_media_player.pipeline:112]: Media reader encountered an error: ESP_FAIL
[11:33:16][E][speaker_media_player:328]: The announcement pipeline's file reader encountered an error.
[11:33:16][E][speaker_media_player.pipeline:112]: Media reader encountered an error: ESP_FAIL
[11:33:16][E][speaker_media_player:328]: The announcement pipeline's file reader encountered an error.
[11:33:16][E][speaker_media_player.pipeline:112]: Media reader encountered an error: ESP_FAIL
[11:33:16][E][speaker_media_player:328]: The announcement pipeline's file reader encountered an error.
[11:33:16][E][speaker_media_player.pipeline:112]: Media reader encountered an error: ESP_FAIL
[11:33:16][E][speaker_media_player:328]: The announcement pipeline's file reader encountered an error.
[11:33:16][E][speaker_media_player.pipeline:112]: Media reader encountered an error: ESP_FAIL
[11:33:16][E][speaker_media_player:328]: The announcement pipeline's file reader encountered an error.
[11:33:16][E][speaker_media_player.pipeline:112]: Media reader encountered an error: ESP_FAIL
[11:33:17][E][speaker_media_player:328]: The announcement pipeline's file reader encountered an error.
[11:33:17][E][speaker_media_player.pipeline:112]: Media reader encountered an error: ESP_FAIL
[11:33:17][E][speaker_media_player:328]: The announcement pipeline's file reader encountered an error.
[11:33:17][E][speaker_media_player.pipeline:112]: Media reader encountered an error: ESP_FAIL
[11:33:17][E][speaker_media_player:328]: The announcement pipeline's file reader encountered an error.

![Image](https://github.com/user-attachments/assets/e10387ec-c55b-43c9-8dc2-b299a6546371)
