### ISSUE TITLE
ESPHome 2025.5.2 Config Error

### ISSUE THREAD

**Issue by pnneil** [esphome/issues#7107]
### The problem

I have a Waveshare ESP32-S3-Touch-LCD-7 running a piece of code to provide Home theatre remote control functions. It was working fine on ESPHOME 2025.2.2, but after upgrading to 2025.5.2 I get a compile error when attempting to upgrade the device.

INFO ESPHome 2025.5.2
INFO Reading configuration /config/esphome/waveshare.yaml...
Failed config

psram: [source /config/esphome/waveshare.yaml:118]

PSRAM 120MHz is not supported in octal mode.
mode: octal
speed: 120MHz

### Which version of ESPHome has the issue?

2025.5.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.5.3

### What platform are you using?

ESP32

### Board

ESP32-S3-Touch-LCD-7  as esp32-s3-devkitc-1

### YAML Config

```yaml
################################################################################
# Board Configuration
################################################################################
esphome:
  name: ${device_internal_name}
  friendly_name: ${device_friendly_name}
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288
  on_boot:
    priority: 600  # Run early during boot
    then:
      - logger.log: "Device booted successfully"    

font:
  - file: "fonts/OpenSans-Bold.ttf"  # Adjust path if needed
    id: roboto
    size: 48
  - file: "fonts/OpenSans-Bold.ttf"
    id: roboto_50  # For time label
    size: 52
  - file: "fonts/OpenSans-Bold.ttf"
    id: roboto_20  # For date and button text
    size: 16
  - file: "fonts/OpenSans-Bold.ttf"
    id: roboto_36  # For Signal label, 20% smaller than roboto_50
    size: 26
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: mdi_42
    size: 42
    bpp: 4
    glyphs: [
      "$power", 
      "$music",
      "$apple_tv",
      "$volume_up",
      "$volume_down",
      "$up_arrow",
      "$down_arrow",
      "$left_arrow",
      "$right_arrow",
      "$enter",
      "$mute",
      "$rewind",
      "$fast_forward",
      "$play_pause",
      "$pause",
      "$movie_lights",
      "$theatre_light",
      "$menu",
      "$back"  
    ]  

psram:
  mode: octal
  speed: 120MHz  # try 80 if not working

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: "y"
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y

################################################################################
# Enable logging
################################################################################
logger:
  logs:
    component: ERROR

# Check original version if issues
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.5.2
INFO Reading configuration /config/esphome/waveshare.yaml...
Failed config

psram: [source /config/esphome/waveshare.yaml:118]

PSRAM 120MHz is not supported in octal mode.
mode: octal
speed: 120MHz
```

### Additional information

I saw a pull request where this check was added recently but my board works fine at 120MHz.  If I change the speed to 80MHz the code compiles but the board hangs on startup.

TIA
