### ISSUE TITLE
SML stopped decoding

### ISSUE THREAD

**Issue by Crumar** [esphome/issues#7110]
### The problem

Hi,

I am trying to migrate from my esp32cam to esp32-poe-iso. The config is essentially the same, besides wlan / ethernet config. The old system according to HA: Firmware: 2022.12.3 (Jan 11 2024, 16:32:02)
The new board was compiled yesterday/today, both with 2022.12.3 and 2025.5.2, both same result.
Reconnecting the old still works fine.
It just doesnt decode into strings

I have another energymeter with roughly the same config on nodemcu-32s, which suddenly had the same behaviour, I think after update but not sure. That one is on Firmware: 2024.10.3 (Nov 18 2024, 21:03:32)

### Which version of ESPHome has the issue?

2022.12.3/2025.5.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2025.5.1

### What platform are you using?

ESP32

### Board

esp32cam/olimex poe32-iso

### Component causing the issue

SML

### YAML Config

```yaml
esphome:
  name: energymeter

uart:
  id: uart_bus
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  debug:
   direction: BOTH
   after:
     timeout: 100ms
     delimiter: "\n"
   dummy_receiver: true
   sequence:
     - lambda: UARTDebug::log_string(direction, bytes);


sml:
  id: mysml
  uart_id: uart_bus

esp32:
  board: esp32-poe-iso

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0
  hardware_uart: UART0

# Enable Home Assistant API
api:
  encryption:
    key: ***

ota:
  password: ***

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  manual_ip:
    static_ip: 192.168.131.135
    gateway: 192.168.131.1
    subnet: 255.255.255.0

sensor:
  - platform: sml
    name: "Total energy"
    sml_id: mysml
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
  - platform: sml
    name: "Total energy feed"
    sml_id: mysml
    obis_code: "1-0:2.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
  - platform: sml
    name: "Total power"
    sml_id: mysml
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    filters:
      - multiply: 0.1
```

### Anything in the logs that might be useful for us?

```txt
[21:22:14][D][uart_debug:158]: <<< "P\xD6\x18s\xC0/\xFB\xA5\xD6\x90\x17kb\xE4n\xD9\xAE\xFC37\xB3<\xE2Z\x01\x01\x01c\x83\xCC\x00v\a\x00\v\x05o\e)b\x00b\x00rc\x02\x01q\x01c\x98j\x00\e\e\e\e\x1A\x00j\x15"
[21:22:15][D][uart_debug:158]: <<< "\e\e\e\e\x01\x01\x01\x01v\a\x00\v\x05o\e+b\x00b\x00rc\x01\x01v\x01\x01\a\x00\v\a\xC0\xB3\xB9\v\t\x01EMH\x00\x00\x9D\v\x94\x01\x01c\xF7$\x00v\a\x00\v\x05o\e,b\x00b\x00rc\a\x01w\x01\v\t\x01EMH\x00\x00\x9D\v\x94\a\x01\x00b\n"
[21:22:15][D][uart_debug:158]: <<< "\xFF\xFFrb\x01e\a\xC0zszw\a\x81\x81\xC7\x82\x03\xFF\x01\x01\x01\x01\x04EMH\x01w\a\x01\x00\x00\x00\t"
[21:22:15][D][uart_debug:158]: <<< "\xFF\x01\x01\x01\x01\v\t\x01EMH\x00\x00\x9D\v\x94\x01w\a\x01\x00\x01\b\x00\xFFd\x01\x01\x82\x01b\x1ER\xFFV\x00\v\xF6\x82\x9B\x01w\a\x01\x00\x02\b\x00\xFFd\x01\x01\x82\x01b\x1ER\xFFV\x00\x00h\r\xF8\x01w\a\x01\x00\x01\b\x01\xFF\x01\x01b\x1ER\xFFV\x00\v\xF6\x82\x9B\x01w\a\x01\x00\x02\b\x01\xFF\x01\x01b\x1ER\xFFV\x00\x00h\r\xF8\x01w\a\x01\x00\x01\b\x02\xFF\x01\x01b\x1ER\xFFV\x00\x00\x00\x00\x00\x01w\a\x01\x00\x02\b\x02\xFF\x01\x01b\x1ER\xFFV\x00\x00\x00\x00\x00\x01w"
[21:22:15][D][uart_debug:158]: <<< "\a\x01\x00\x10\a\x00\xFF\x01\x01b\eR\xFFU\x00\x00\x16\xC7\x01w\a\x81\x81\xC7\x82\x05\xFF\x01\x01\x01\x01\x83\x02a9|$\x8A52\xDB\xB7\xB9\xA6\xA9\fs\xE8\xA3\x8D3E\xF6\x8A\xB7,\n"
```

### Additional information

Hi,

I am trying to migrate from my esp32cam to esp32-poe-iso. The config is essentially the same, besides wlan / ethernet config. The old system according to HA: Firmware: 2022.12.3 (Jan 11 2024, 16:32:02)
The new board was compiled yesterday/today, both with 2022.12.3 and 2025.5.2, both same result.
Reconnecting the old still works fine.

I have another energymeter with roughly the same config on nodemcu-32s, which suddenly had the same behaviour, I think after update but not sure. That one is on Firmware: 2024.10.3 (Nov 18 2024, 21:03:32)

**Comment by Crumar** [comment]
So I am testing on the one that has been broken longer anyway and now tried to add the following:

```yaml
external_components:
  - source:
      type: local
      path: ../esphome/esphome/components
    components: [sml, uart, logger]
```
In the local path is the commit of tag 2022.12.3 (1691976587c964224e188fa7cfd2e2b06758b51c).

Behaviour does not change, sadly.

I see however partly valid strings in this data:
[21:25:17][D][uart_debug:158]: <<< "\t\x01EBZ\x01\x00\x14\xBB\xC2\x01w\a\x01\x00\x01\b\x00\xFFd\x01\x01\x80\x01b\x1ER\x03e\x00\x00 \xA3\x01w\a\x01\x00\x01\b\x01\xFF\x01\x01b\x1ER\x03e\x00\x00 \xA2\x01w\a\x01\x00\x01\b\x02\xFF\x01\x01b\x1ER\x03e\x00\x00\x00\x01\x01w\a\x01\x00\x02\b\x00\xFFd\x01\x01\x80\x01b\x1ER\x03e\x00\x00\x03\xE7\x01\x01\x01c$\xD0\x00v\x05\b\xD0\xC7\x8Bb\x00b\x00re\x00\x00\x02\x01q\x01c\x998\x00\x00\x00\x00\e\e\e\e\x1A\x03\'\xD0"

**Comment by Crumar** [comment]
I have absolutely no idea what happened - but on the nodemcu-32s I now get printed OBIS infos...

```yaml
esphome:
  name: powermeter

esp32:
  board: nodemcu-32s

external_components:
  - source:
      type: local
      path: ../esphome/esphome/components
    components: [sml, uart]

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption: 
    key: !secret enckey_rs_energy
ota:
  - platform: esphome
    password: !secret ota_rs_password

wifi:
  ssid: RS
  password: !secret wifi_rs_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.152.5
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.152.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Powermeter Fallback Hotspot"
#    password: "zcxGgCZT1Pjz"

#captive_portal:
    
uart:
  id: uart_bus
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 512
  # debug:
  #  direction: BOTH
  #  after:
  #    timeout: 1000ms
  #    delimiter: "\n"
  #  dummy_receiver: true
  #  sequence:
  #    - lambda: UARTDebug::log_hex(direction, bytes, ' ');


sml:
  id: mysml
  uart_id: uart_bus


sensor:
  - platform: sml
    name: "Total energy"
    sml_id: mysml
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    #filters:
    #  - multiply: 0.001
  - platform: sml
    name: "Total energy feed"
    sml_id: mysml
    obis_code: "1-0:2.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    #filters:
    #  - multiply: 0.001
  - platform: sml
    name: "Total power"
    sml_id: mysml
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    filters:
      - multiply: 0.01
  - platform: sml
    name: "Frequency"
    sml_id: mysml
    obis_code: "1-0:14.7.0"
    unit_of_measurement: Hz
    state_class: measurement
    device_class: frequency
  - platform: sml
    name: "Total power L1"
    sml_id: mysml
    obis_code: "1-0:36.7.0"
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    filters:
      - multiply: 0.01
  - platform: sml
    name: "Total power L2"
    sml_id: mysml
    obis_code: "1-0:56.7.0"
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    filters:
      - multiply: 0.01
  - platform: sml
    name: "Total power L3"
    sml_id: mysml
    obis_code: "1-0:76.7.0"
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    filters:
      - multiply: 0.01
```
I kept adding Debug statements in SML and nothing worked and now I just reverted my code to dev (f467c79a2) and it still works... 
Need to confirm on my other device and it seems like I need to reenter the pin on the other energy meter, though I can only visit that place later.
