### ISSUE TITLE
Substitutions are not working in filters

### ISSUE THREAD

**Issue by emrsmsrli** [esphome/issues#7115]
### The problem

Substitution variables are causing yaml config error when they are used in filters. 

### Which version of ESPHome has the issue?

2025.4.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

ESP32-DevkitC

### Component causing the issue

sensor

### YAML Config

```yaml
### sensor_kit.yaml

sensor:
  - platform: template
    name: "Moisture sensor ${num}"
    id: irrigator_moisture_sensor_${num}
    state_class: "measurement"
    accuracy_decimals: 1
    icon: mdi:flower
    unit_of_measurement: '%'
    filters:
      - clamp:
          min_value: ${moisture_max_v}
          max_value: ${moisture_min_v}
      - calibrate_linear:
          datapoints:
            - from: ${moisture_min_v}
              to: 0
            - from: ${moisture_max_v}
              to: 100
... 

### main.yaml

...
packages:
   moisture_kit_1: !include { file: sensor_kit.yaml, vars: { moisture_min_v: 2.8, moisture_max_v: 1.05 } }
...
```

### Anything in the logs that might be useful for us?

```txt
Failed config

sensor.template: [source .\moisture_sensor_kit.yaml:2]
  platform: template
  name: Moisture sensor 2
  id: irrigator_moisture_sensor_2
  state_class: measurement
  accuracy_decimals: 1
  icon: mdi:flower
  unit_of_measurement: %
  filters: 
    - clamp: 

        expected float.
        min_value: ${moisture_max_v}

        expected float.
        max_value: ${moisture_min_v}
    - calibrate_linear:
        datapoints:
```

### Additional information

There are other substitutions in sensor_kit.yaml and they work fine.

**Comment by jpeletier** [comment]
I ran your configuration and it works fine for me. I don't get your error and filter values are output correctly:

`esphome config main.yaml`

```yaml
# [...]
- platform: template
  name: Moisture sensor 1
  id: irrigator_moisture_sensor_1
  state_class: measurement
  accuracy_decimals: 1
  icon: mdi:flower
  unit_of_measurement: '%'
  filters:
  - clamp:
      min_value: 1.05
      max_value: 2.8
      ignore_out_of_range: false
  - calibrate_linear:
      datapoints:
      - from: 2.8
        to: 0.0
      - from: 1.05
        to: 100.0
      method: least_squares
  disabled_by_default: false
  force_update: false
  update_interval: 60s
```

```yaml
#main.yaml

esphome:
  name: hola

packages:
  moisture_kit_1: !include {file: sensor_kit.yaml, vars: {moisture_min_v: 2.8, moisture_max_v: 1.05, 'num': 1}}


esp32:
  board: esp32dev
```

```yaml
#sensor_kit.yaml
sensor:
  - platform: template
    name: "Moisture sensor ${num}"
    id: irrigator_moisture_sensor_${num}
    state_class: "measurement"
    accuracy_decimals: 1
    icon: mdi:flower
    unit_of_measurement: '%'
    filters:
      - clamp:
          min_value: ${moisture_max_v}
          max_value: ${moisture_min_v}
      - calibrate_linear:
          datapoints:
            - from: ${moisture_min_v}
              to: 0
            - from: ${moisture_max_v}
              to: 100
```
