### ISSUE TITLE
Select Component's dropdown doesn't update correctly after selecting previous.

### ISSUE THREAD

**Issue by EmberLightVFX** [esphome/issues#7119]
### The problem

I have a select component with the 4 objects "1", "2", "3" and "4".
I then have a number compontent (for this example) that changes the select component.
There is no problems selecing forward but after selecting backwards over all the objects, "3" and "4" now always show "1", even when selecing forward.

The state of the select component shows the correct value but the dropdown doesn't.

https://github.com/user-attachments/assets/fb90fb75-9b5a-4795-8974-2afd5bb55a57

### Which version of ESPHome has the issue?

2025.5.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Component causing the issue

select

### YAML Config

```yaml
globals:
  - id: previous_slot_value
    type: float
    restore_value: no
    initial_value: "5.0"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0 # https://github.com/platformio/platform-espressif32/releases/
    sdkconfig_options:
      CONFIG_MBEDTLS_HKDF_C: y # Needed for bambu KDF
      CONFIG_MBEDTLS_MD_C: y # Needed for bambu KDF
    # version: recommended
    # sdkconfig_options:
    # MBEDTLS_CERTIFICATE_BUNDLE: y
    # MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL: y

esphome:
  name: openspool
  project:
    name: spuder.openspool
    version: ${version}
  min_version: 2025.5.2
  platformio_options:
    build_unflags: -std=gnu++11
    build_flags:
      - -std=gnu++14
      - -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"

logger:
  level: debug

wifi:
  ssid: "wifi-ssid"
  password: "wifi-password"
  ap:
    ssid: "OpenSpool"

web_server:
  id: openspool_web_server
  port: 80
  local: true

number:
  - platform: template
    name: "Change me to change the others"
    id: slot_controller
    min_value: 1
    max_value: 20
    optimistic: true
    step: 1
    initial_value: 1
    on_value:
      then:
        - if:
            condition:
              lambda: "return x > id(previous_slot_value);"
            then:
              - select.next:
                  id: slot_number
                  cycle: true
              - number.increment:
                  id: number_number
                  cycle: true
            else:
              - if:
                  condition:
                    lambda: "return x < id(previous_slot_value);"
                  then:
                    - select.previous:
                        id: slot_number
                        cycle: true
                    - number.decrement:
                        id: number_number
                        cycle: true
        - lambda: "id(previous_slot_value) = x;"

  - platform: template
    name: "Number Number"
    id: number_number
    optimistic: true
    min_value: 1
    max_value: 4
    mode: box
    initial_value: 1
    step: 1

select:
  - platform: template
    name: "Slot Number"
    id: slot_number
    optimistic: true
    options:
      - "1"
      - "2"
      - "3"
      - "4"
    initial_option: "1"

```

### Anything in the logs that might be useful for us?

```txt

```
