### ISSUE TITLE
components/datetime: state_as_esptime() returns incomplete struct, breaks functionality

### ISSUE THREAD

**Issue by sur5r** [esphome/issues#7121]
### The problem

While debugging https://github.com/esphome/esphome/discussions/9093, I noticed that `DateEntity::state_as_esptime()` returns an incomplete `ESPTime`. This breaks comparison as `.timestamp` is not set. Also `ESPTime::recalc_timestamp_utc()` doesn't work either as the fields are filled with random values.

### Which version of ESPHome has the issue?

dev

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by sur5r** [comment]
Not stale FFS. People will get around to it when they get around to it, no need to add pressure.

Edit: Oh come on, now the discussion that found this issue got deleted? Please tell me that's not true.

Edit2: Internet Archive to the rescue: https://web.archive.org/web/2/https://github.com/esphome/esphome/discussions/9093#expand

To repeat the deleted discussion:

```YAML
time:
  - platform: sntp
    id: sntptime
    servers: 192.0.2.123

interval:
  - interval: 10s 
    then:
      - lambda: |-
          ESPTime now = id(sntptime).now();
          ESP_LOGI("main", "---");
          char buffer[100];
          snprintf(buffer, 100, "Current Time is: %04d-%02d-%02d %02d:%02d:%02d (@%d)", now.year, now.month, now.day_of_month, now.hour, now.minute, now.second, now.timestamp);
          ESP_LOGI("main", "%s", buffer);
          ESP_LOGI("main", "Current Time is: %04d-%02d-%02d (@%d)", now.year, now.month, now.day_of_month, now.timestamp);
          ESP_LOGI("main", "Current Time is: %04d-%02d-%02d %02d:%02d:%02d (@%d)", now.year, now.month, now.day_of_month, now.hour, now.minute, now.second, now.timestamp);
          ESP_LOGI("main", "Current Time is: %04d-%02d-%02d %02d:%02d (@%d)", now.year, now.month, now.day_of_month, now.hour, now.minute, now.timestamp);
```

results in

```
[20:10:54][I][main:028]: ---
[20:10:54][I][main:031]: Current Time is: 2025-06-15 20:10:54 (@249)
[20:10:54][I][main:032]: Current Time is: 2025-06-15 (@10)
[20:10:54][I][main:033]: Current Time is: 2025-06-15 20:10:54 (@1750011054)
[20:10:54][I][main:034]: Current Time is: 2025-06-15 20:10 (@54)
[20:11:04][I][main:028]: ---
[20:11:04][I][main:031]: Current Time is: 2025-06-15 20:11:04 (@249)
[20:11:04][I][main:032]: Current Time is: 2025-06-15 (@11)
[20:11:04][I][main:033]: Current Time is: 2025-06-15 20:11:04 (@1750011064)
[20:11:04][I][main:034]: Current Time is: 2025-06-15 20:11 (@4)
```

Symptom: If you don't access `now.second`, `now.timestamp` resolves to funny values.

Investigation back then found acc8d24a325b34cd4af035bb2e26b26f1d6e4f83 to be the breaking commit, with a workaround being:

```yaml
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    platform_version: "53.03.13-1"
    version: "5.3.1"
```

I suspected a compiler bug.

Today, I tested again, and it seems to be resolved with the defaults for both `2025.9.3` and `2025.10.0`.
