### ISSUE TITLE
ESP32-C6 fails to compile with esp-idf platform under esphome 2025.5.2

### ISSUE THREAD

**Issue by bln35** [esphome/issues#7122]
### The problem

I have ESPHOME 2025.5.2
Impossible to compile program for ESP32-C6-DevKitC-1 (see program and my log below)

### Which version of ESPHome has the issue?

esphome 2025.5.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32-IDF

### Board

ESP32-C6-DevKitC-1

### YAML Config

```yaml
esphome:
  name: esphome-web-014ff4
  friendly_name: ESPHome Web 014ff4
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32-c6-devkitm-1
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf
#    version: 5.3.1
#    platform_version: 6.9.0

logger:
  hardware_uart: UART0
  baud_rate: 115200
  level: DEBUG
  
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.5.2
INFO Reading configuration /root/config/esphome-web-014ff4.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.8.2
INFO Compiling app...
Processing esphome-web-014ff4 (board: esp32-c6-devkitm-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
HARDWARE: ESP32C6 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50106.0 (5.1.6) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 12.2.0+20230208
Reading CMake configuration...
-- git rev-parse returned 'fatal: not a git repository (or any of the parent directories): .git'
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is GNU
-- Found assembler: /root/.platformio/packages/toolchain-riscv32-esp@12.2.0+20230208/bin/riscv32-esp-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /root/.platformio/packages/toolchain-riscv32-esp@12.2.0+20230208/bin/riscv32-esp-elf-gcc
-- Check for working C compiler: /root/.platformio/packages/toolchain-riscv32-esp@12.2.0+20230208/bin/riscv32-esp-elf-gcc - broken
-- Configuring incomplete, errors occurred!
See also "/root/config/.esphome/build/esphome-web-014ff4/.pioenvs/esphome-web-014ff4/CMakeFiles/CMakeOutput.log".
See also "/root/config/.esphome/build/esphome-web-014ff4/.pioenvs/esphome-web-014ff4/CMakeFiles/CMakeError.log".

fatal: not a git repository (or any of the parent directories): .git
CMake Error at /root/.platformio/packages/tool-cmake/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/root/.platformio/packages/toolchain-riscv32-esp@12.2.0+20230208/bin/riscv32-esp-elf-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /root/config/.esphome/build/esphome-web-014ff4/.pioenvs/esphome-web-014ff4/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/root/.platformio/packages/tool-ninja/ninja cmTC_12321 && [1/2] Building C object CMakeFiles/cmTC_12321.dir/testCCompiler.c.obj
    FAILED: CMakeFiles/cmTC_12321.dir/testCCompiler.c.obj 
    /root/.platformio/packages/toolchain-riscv32-esp@12.2.0+20230208/bin/riscv32-esp-elf-gcc   -march=rv32imac_zicsr_zifencei -o CMakeFiles/cmTC_12321.dir/testCCompiler.c.obj -c /root/config/.esphome/build/esphome-web-014ff4/.pioenvs/esphome-web-014ff4/CMakeFiles/CMakeTmp/testCCompiler.c
    Assembler messages:
    Fatal error: invalid -march= option: `rv32imac_zicsr_zifencei'
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  /root/.platformio/packages/framework-espidf@src-f61644d6990eba6c2084961ff40be733/tools/cmake/project.cmake:505 (__project)
  CMakeLists.txt:3 (project)



========================== [FAILED] Took 2.06 seconds ==========================
```
