### ISSUE TITLE
Number component doesn't save value to flash when updated using publish_state()

### ISSUE THREAD

**Issue by EmberLightVFX** [esphome/issues#7124]
### The problem

This is my setup:
I have 2 number components.
The first component gets its number updated using number.increment.
The second component gets its number updated using lambda id(number_number).publish_state(x)

Both number components are exactly the same and have `restore_value: true`

For the first component its value always gets saved to flash. The second components value doesn't get saved to flash when it gets updated using publish_state but if I manually change the value using its slider the new value will get saved to flash.

### Which version of ESPHome has the issue?

2025.5.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Board

ESP32 S3 Super Mini

### YAML Config

```yaml
---
preferences:
  flash_write_interval: 3sec

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

esphome:
  name: openspool
  min_version: 2025.5.2

logger:
  level: debug

globals:
  - id: previous_slot_value
    type: int
    restore_value: false
    initial_value: "1"

wifi:
  ssid: "YOUR SSID"
  password: "YOUR PASSWORD"
  ap:
    ssid: "OpenSpool"

web_server:
  id: openspool_web_server
  port: 80
  local: true
  version: 3

number:
  - platform: template
    name: "Number Controller"
    id: number_controller
    min_value: 1
    max_value: 4
    optimistic: true
    step: 1
    initial_value: 10
    on_value:
      then:
        - if:
            condition:
              lambda: "return x > id(previous_slot_value);"
            then:
              - number.increment:
                  id: number_number
                  cycle: true
              - lambda: |-
                  id(publish_number).publish_state(x);
            else:
              - if:
                  condition:
                    lambda: "return x < id(previous_slot_value);"
                  then:
                    - number.decrement:
                        id: number_number
                        cycle: true
                    - lambda: |-

                        id(publish_number).publish_state(x);
              - lambda: "id(previous_slot_value) = x;"
    web_server:
      sorting_weight: 0

  - platform: template
    name: "Publish Number"
    id: publish_number
    min_value: 1
    max_value: 4
    step: 1
    initial_value: 1
    optimistic: true
    restore_value: true
    web_server:
      sorting_weight: 40

  - platform: template
    name: "Number Number"
    id: number_number
    min_value: 1
    max_value: 4
    step: 1
    initial_value: 1
    optimistic: true
    restore_value: true
    web_server:
      sorting_weight: 40
```

### Anything in the logs that might be useful for us?

```txt

```
