### ISSUE TITLE
position_action in cover.template does not accept arguments (x, position, value) and this->target_position, id().target_position, [this] also fail

### ISSUE THREAD

**Issue by Satlax** [esphome/issues#7125]
### The problem

Hello!

I'm encountering an extremely strange issue with the cover.template component and its position_action. I'm using ESPHome version 2025.5.2 on an ESP32 with the toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5 toolchain. My ESPHome installation type is Home Assistant Add-on.

### Which version of ESPHome has the issue?

2025.5.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.1

### What platform are you using?

ESP32

### YAML Config

```yaml
esphome:
  name: two_curtains_control
  on_boot:
    priority: -100.0
    then:
      - logger.log: "Device two_curtains_control loaded and ready."

substitutions:
  max_steps: "20000"

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  platform: esphome

logger:

stepper:
  - platform: uln2003
    id: motor_left_stepper
    pin_a: GPIO12
    pin_b: GPIO13
    pin_c: GPIO14
    pin_d: GPIO15
    max_speed: 250
    step_mode: FULL_STEP

  - platform: uln2003
    id: motor_right_stepper
    pin_a: GPIO16
    pin_b: GPIO17
    pin_c: GPIO18
    pin_d: GPIO19
    max_speed: 250
    step_mode: FULL_STEP

cover:
  - platform: template
    name: "Curtain Left"
    id: curtain_left_cover
    optimistic: true

    open_action:
      - stepper.set_target:
          id: motor_left_stepper
          target: !lambda "return ${max_steps};"

    close_action:
      - stepper.set_target:
          id: motor_left_stepper
          target: 0

    stop_action:
      - stepper.set_target:
          id: motor_left_stepper
          target: !lambda "return id(motor_left_stepper).current_position;"

    position_action:
      - lambda: |-
          [this] { # Or float position = x;
            int target_pos = static_cast<int>(this->target_position * ${max_steps}); # Or position * ${max_steps};
            id(motor_left_stepper).set_target(target_pos);
          }

  - platform: template
    name: "Curtain Right"
    id: curtain_right_cover
    optimistic: true

    open_action:
      - stepper.set_target:
          id: motor_right_stepper
          target: !lambda "return ${max_steps};"

    close_action:
      - stepper.set_target:
          id: motor_right_stepper
          target: 0

    stop_action:
      - stepper.set_target:
          id: motor_right_stepper
          target: !lambda "return id(motor_right_stepper).current_position;"

    position_action:
      - lambda: |-
          [this] { # Or float position = x;
            int target_pos = static_cast<int>(this->target_position * ${max_steps}); # Or position * ${max_steps};
            id(motor_right_stepper).set_target(target_pos);
          }
```

### Anything in the logs that might be useful for us?

```txt
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
Compiling .pioenvs/two_curtains_control/src/main.cpp.o
/config/esphome/two-curtains-control.yaml:68:16: error: stray '#' in program
           [this] { # Or float position = x;
                ^
/config/esphome/two-curtains-control.yaml:69:75: error: stray '#' in program
             int target_pos = static_cast<int>(this->target_position * ${max_steps}); # Or position * ${max_steps};
                                                                           ^
/config/esphome/two-curtains-control.yaml:95:16: error: stray '#' in program
           [this] { # Or float position = x;
                ^
/config/esphome/two-curtains-control.yaml:96:75: error: stray '#' in program
             int target_pos = static_cast<int>(this->target_position * ${max_steps}); # Or position * ${max_steps};
                                                                           ^
/config/esphome/two-curtains-control.yaml: In lambda function:
/config/esphome/two-curtains-control.yaml:68:8: error: 'this' was not captured for this lambda function
           [this] { # Or float position = x;
        ^  ~
/config/esphome/two-curtains-control.yaml: In lambda function:
/config/esphome/two-curtains-control.yaml:68:18: error: 'Or' was not declared in this scope
           [this] { # Or float position = x;
                  ^~
/config/esphome/two-curtains-control.yaml:68:18: note: suggested alternative: 'OK'
           [this] { # Or float position = x;
                  ^~
                  OK
/config/esphome/two-curtains-control.yaml:69:43: error: 'this' was not captured for this lambda function
             int target_pos = static_cast<int>(this->target_position * ${max_steps}); # Or position * ${max_steps};
                                           ^~~~
/config/esphome/two-curtains-control.yaml:69:79: error: expected ';' before 'position'
             int target_pos = static_cast<int>(this->target_position * ${max_steps}); # Or position * ${max_steps};
                                                                               ^~~~~~~~~
                                                                               ;
/config/esphome/two-curtains-control.yaml: In lambda function:
/config/esphome/two-curtains-control.yaml:71:8: error: expected ';' before '}' token
           }
        ^
        ;
 
         
/config/esphome/two-curtains-control.yaml: In lambda function:
/config/esphome/two-curtains-control.yaml:95:8: error: 'this' was not captured for this lambda function
           [this] { # Or float position = x;
        ^  ~
/config/esphome/two-curtains-control.yaml: In lambda function:
/config/esphome/two-curtains-control.yaml:95:18: error: 'Or' was not declared in this scope
           [this] { # Or float position = x;
                  ^~
/config/esphome/two-curtains-control.yaml:95:18: note: suggested alternative: 'OK'
           [this] { # Or float position = x;
                  ^~
                  OK
/config/esphome/two-curtains-control.yaml:96:43: error: 'this' was not captured for this lambda function
             int target_pos = static_cast<int>(this->target_position * ${max_steps}); # Or position * ${max_steps};
                                           ^~~~
/config/esphome/two-curtains-control.yaml:96:79: error: expected ';' before 'position'
             int target_pos = static_cast<int>(this->target_position * ${max_steps}); # Or position * ${max_steps};
                                                                               ^~~~~~~~~
                                                                               ;
/config/esphome/two-curtains-control.yaml: In lambda function:
/config/esphome/two-curtains-control.yaml:98:8: error: expected ';' before '}' token
           }
        ^
        ;
Compiling .pioenvs/two_curtains_control/FrameworkArduino/esp32-hal-gpio.c.o
Compiling .pioenvs/two_curtains_control/FrameworkArduino/esp32-hal-i2c-slave.c.o
Compiling .pioenvs/two_curtains_control/FrameworkArduino/esp32-hal-i2c.c.o
*** [.pioenvs/two_curtains_control/src/main.cpp.o] Error 1
```

### Additional information

I've systematically attempted to use all documented and logical ways to retrieve the position value within position_action, but each time I received a compilation error:

1. Direct access to x (as seen in older examples):

```
position_action:
  - lambda: |-
      int target_pos = static_cast<int>(x * ${max_steps});
      id(motor_left_stepper).set_target(target_pos);
```
Error: 'x' was not declared in this scope.

2. Explicit argument declaration (float position) / (float x) in a single-line lambda:

```
position_action:
  - lambda: '(float position) { int target_pos = static_cast<int>(position * ${max_steps}); id(motor_left_stepper).set_target(target_pos); }'
```
Error: error: expected primary-expression before 'float' or error: expected ')' before 'float'.

3. Using id(cover_id).target_position:

```
position_action:
  - lambda: |-
      int target_pos = static_cast<int>(id(curtain_left_cover).target_position * ${max_steps});
      id(motor_left_stepper).set_target(target_pos);
```

Error: 'class esphome::template_::TemplateCover' has no member named 'target_position'; did you mean 'has_position_'?.

4. Using this->target_position (with and without [this] capture):

```
position_action:
  - lambda: |-
      [this] {
        int target_pos = static_cast<int>(this->target_position * ${max_steps});
        id(motor_left_stepper).set_target(target_pos);
      }
```
Error: 'this' was not captured for this lambda function (even with explicit [this]), expected ';' before '}' token.

The only working solution:
The only configuration that successfully compiles is when I manually specify a fixed numerical value instead of a variable:

```
position_action:
  - lambda: |-
      float fixed_position = 0.5; # OR any other float
      int target_pos = static_cast<int>(fixed_position * ${max_steps});
      id(motor_left_stepper).set_target(target_pos);
```

I have consistently performed "Clean Build Files" between attempts and ensured there are no non-ASCII characters or obvious comments within the lambda blocks.
