### ISSUE TITLE
Persistent I2S Audio Data Acquisition Failure with `i2s_audio` Component on ESP32 (Arduino Framework)

### ISSUE THREAD

**Issue by vgisbert** [esphome/issues#7126]
### The problem

I am consistently encountering issues with the `i2s_audio` component in ESPHome, which fails to acquire meaningful audio data from I2S microphones (specifically INMP441 and SPH0645) on ESP32 development boards using the Arduino framework.

Previously, this manifested as `Raw RMS received: nan` errors. With ESPHome **2025.6.0**, these explicit `NaN` errors have disappeared, but the fundamental problem of **no audio data being processed persists**. The `on_data` lambda in my `microphone` configuration is never triggered with valid data (or is not triggered at all), indicating a silent failure in the `i2s_audio` component's ability to acquire data. This behavior has been confirmed with both INMP441 and SPH0645 microphones.

### Which version of ESPHome has the issue?

* **ESPHome Version:** 2025.6.0
* **ESP32 Board:** ESP32 Dev Module (tested with standard ESP32 development boards)
* **ESP-IDF Framework Version:** Arduino (tested with `esp32 by Espressif Systems` core versions 2.0.17 and development builds like 3.2.0)
* **Microphones Tested:** INMP441 and SPH0645

### **Problem Details:**

The core issue is that the `i2s_audio` component does not seem to be correctly acquiring valid digital audio data from connected I2S microphones. This is now evident by the complete absence of any `MIC_CALLBACK` or `MIC_RAW` debug messages from the `on_data` lambda, even after the device has been running for over 2 minutes with `logger: level: VERBOSE`. This indicates that the `on_data` callback (which receives the audio samples) is either never being invoked, or is always invoked with an empty data buffer (`x.size()` is 0). This identical behavior has been observed with both INMP441 and SPH0645 microphones, suggesting a general issue with the component rather than a specific microphone type.

### **Symptoms:**

1.  **Complete absence of `MIC_CALLBACK` and `MIC_RAW` logs:** Despite `logger: level: VERBOSE` and an `on_data` lambda designed to log incoming audio data, no such messages appear in the device's serial output for either microphone.
2.  **No `Raw RMS received` messages:** The previous `Raw RMS received: nan` messages no longer appear, suggesting the `DB_CALC` lambda is no longer being called (because no data is reaching it via `audio_level_raw_rms` or `microphone`).

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

HAOS 15.2 CORE 2025.6.1

### What platform are you using?

ESP32

### Board

ESP32_DEVKITC_V4

### Component causing the issue

i2s_audio

### **Steps to Reproduce:**

1.  Update ESPHome to version 2025.6.0.
2.  Compile and upload the minimal YAML configuration provided below for an ESP32 Dev Module (tested identically for both INMP441 and SPH0645).
    * **INMP441/SPH0645 Pinout (standard):**
        * SCK (BCLK): GPIO26
        * WS (LRCLK): GPIO27
        * SD (DIN): GPIO13
        * VCC: 3.3V
        * GND: GND
3.  Monitor the device's serial output for at least 2 minutes after boot.

### YAML Config

**Minimal YAML Configuration (tested with both INMP441 and SPH0645):**

```yaml
substitutions:
  name: "i2s_microphone_test"
  friendly_name: "I2S Microphone Test"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false

esp32:
  board: esp32dev # Ensure this matches your specific ESP32 Dev Module
  framework:
    type: arduino

logger:
  level: VERBOSE # VERY IMPORTANT: VERBOSE level to see ALL details!

# -----------------------------------------------------------
# I2S AUDIO COMPONENT DEFINITION - PROBLEM AREA
# -----------------------------------------------------------
i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO27  # WS (Word Select) - LRCLK on microphone
    i2s_bclk_pin: GPIO26   # SCK (Bit Clock) - BCLK on microphone

# -----------------------------------------------------------
# Microphone Configuration (uses i2s_audio as source)
# -----------------------------------------------------------
microphone:
  - platform: i2s_audio
    id: i2s_microphone_source
    adc_type: external
    pdm: false # <<< IMPORTANT! Set to FALSE for INMP441/SPH0645 (They are I2S digital microphones)
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO13
    channel: left
    sample_rate: 16000 # Common sample rate for INMP441/SPH0645 (can try 8000, 44100 as well)

    # Optional: Add on_data lambda for raw sample inspection
    on_data:
      lambda: |-
        // This lambda should be triggered with audio data.
        // If these logs are not seen, it indicates the i2s_audio component is not acquiring data.
        ESP_LOGD("MIC_CALLBACK", "on_data lambda del micrófono ejecutada!");

        static unsigned long last_publish_time = 0;
        const unsigned long publish_interval_ms = 50; // Log frequently to observe data flow

        if (millis() - last_publish_time >= publish_interval_ms) {
            last_publish_time = millis();

            const int16_t* samples_data = reinterpret_cast<const int16_t*>(x.data());
            size_t num_samples = x.size() / sizeof(int16_t);

            ESP_LOGD("MIC_RAW", "Audio buffer size (bytes): %u", x.size());
            ESP_LOGD("MIC_RAW", "Number of samples expected: %u", num_samples);

            if (num_samples > 0) {
                // Log first few samples for debugging.
                // If all are 0, it might indicate wiring or configuration issues.
                for (size_t i = 0; i < std::min((size_t)10, num_samples); ++i) {
                    ESP_LOGD("MIC_RAW", "Sample %u: %d", i, samples_data[i]);
                }
            } else {
                ESP_LOGW("MIC_RAW", "No audio samples received (num_samples es 0).");
            }
        }
```

### **Anything in the logs that might be useful for us?**

**Relevant Log Snippets (from current tests with ESPHome 2025.6.0, identical for INMP441 and SPH0645):**

```
[HH:MM:SS]ets Jul 29 2019 12:21:46
[HH:MM:SS]
[HH:MM:SS]rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[HH:MM:SS]configsip: 0, SPIWP:0xee
[HH:MM:SS]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[HH:MM:SS]mode:DIO, clock div:2
[HH:MM:SS]load:0x3fff0030,len:1184
[HH:MM:SS]load:0x40078000,len:13132
[HH:MM:SS]load:0x40080400,len:3036
[HH:MM:SS]entry 0x400805e4
[HH:MM:SS][     6][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[HH:MM:SS][I][logger:171]: Log initialized
```
*(This is the entire log output after running for >2 minutes. No further messages related to audio processing appear, nor any `Raw RMS received` from previous versions.)*

###  **Additional Context/Troubleshooting Attempts:**

* Tested with `esp32 by Espressif Systems` core versions 2.0.17 (stable) and development builds like 3.2.0 within ESPHome.
* The issue persisted across these core versions, suggesting a consistent problem with the `i2s_audio` component's operation with these microphones.

### **Expected Behavior:**

The `i2s_audio` component should actively acquire audio samples from the microphone, leading to the `on_data` lambda being frequently triggered and printing `MIC_CALLBACK` and `MIC_RAW` messages with actual sample data.

### **Request:**

Any guidance or debugging steps would be highly appreciated. The issue has shifted from explicit `NaN` errors to a silent failure to acquire any I2S audio data, making it harder to diagnose. This seems to be a core issue with the `i2s_audio` component's functionality on ESP32, as it consistently affects both INMP441 and SPH0645 microphones.
