### ISSUE TITLE
2025.6.0: Can not query BLE signal strength

### ISSUE THREAD

**Issue by top-gun** [esphome/issues#7127]
### The problem

My ESP32 uses the "esphome-tesla-ble" project. With 2025.6.0 (also -b2 and -b3) I don't get a reading for the BLE signal strength, the entity shows "unavailable". With 2025.5.2 and oder add-on versions it works just fine.

In the ESP log, I see an error instead of the usual RSSI reading:
[09:35:44][W][esp32_ble:417][BTC_TASK]: Ignoring unexpected GAP event type: 26

### Which version of ESPHome has the issue?

2025.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.1

### What platform are you using?

ESP32-IDF

### Board

ESP32-DevkitC (generic)

### Component causing the issue

ble_client

### YAML Config

```yaml
The YAML file has several includes. I will post one after another, I hope that's a good way. I can also post the "validate"-output if that is more helpful.

Project YAML:
'''
substitutions:
  # all substitutions for this project
  espidf_version: "5.3.1"
  platformio_version: 6.9.0
  friendly_name: Tesla BLE F549C4
  device_name: tesla-ble-f549c4
  device_description: Tesla BLE
  board: esp32dev
  variant: esp32
  flash_size: 4MB
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "16"

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  source: github://PedroKTFC/esphome-tesla-ble@dev


packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml@dev
  device_base: github://PedroKTFC/esphome-tesla-ble/boards/esp32-generic.yml@dev
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml@dev
  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git#dev 
      
tesla_ble_vehicle:
  odometer:
    name: "Odometer" # Rename if desired
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 180 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
  ble_disconnected_min_time: 120 # Minimum time BLE must be disconnected before sensors are Unknwon (s)

'''
base.yml:
substitutions:
  friendly_name: Tesla BLE
  device_name: tesla-ble
  device_description: Interact with Tesla vehicles over BLE using ESPHome and Home Assistant

packages:
  board: !include board.yml
  common: !include common.yml
  project: !include project.yml
  # listener: !include listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: PedroKTFC.esphome-tesla-ble
    version: "2025.0.4"
logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_hotspot_password

captive_portal:
---
esp32_generic.yaml:
substitutions:
  board: esp32dev
  variant: esp32
  flash_size: 4MB
---
client.yaml:
---
substitutions:
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "32"

ble_client:
  - mac_address: $ble_mac_address
    id: ble_tesla_id

tesla_ble_vehicle:
  ble_client_id: ble_tesla_id
  id: tesla_ble_vehicle_id
  vin: $tesla_vin
  update_interval: 1min # default
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  ble_disconnected_min_time: 10 # Minimum time BLE must be disconnected before sensors are Unknwon (s)

  is_asleep:
    name: "Asleep"
  is_user_present:
    name: "User presence"
  is_unlocked:
    name: "Doors"
  is_charge_flap_open:
    id: "is_charge_flap_open"
    name: "Charge flap"
  is_boot_open:
    id: "is_boot_open"
    name: "Boot"
  is_frunk_open:
    id: "is_frunk_open"
    name: "Frunk"
  shift_state:
    name: "Shift state"
  charge_state:
    id: "charge_state"
    name: "Charge level"
  odometer:
    name: "Odometer"
    filters:
      - multiply: 0.01 # Odometer is in hundredths of a mile (can use this to convert to km)
  charge_current:
    name: "Charge current"
  charge_power:
    name: "Charge power"
  max_soc:
    id: "max_soc"
    name: "Charge limit"
  max_amps:
    id: "max_amps"
    name: "Current limit"
  battery_range:
    name: "Range"
  charging_state:
    name: "Charging state"
  last_update:
    name: "Last update"
  is_climate_on:
    id: "is_climate_on"
    name: "Climate"
  internal_temp:
    name: "Interior"
  external_temp:
    name: "Exterior"
      
button:
  - platform: template
    id: ble_pair
    name: Pair BLE key
    icon: mdi:key-wireless
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->startPair();
    entity_category: diagnostic

  - platform: template
    name: Wake up
    icon: mdi:sleep-off
    on_press:
    - lambda: id(tesla_ble_vehicle_id)->wakeVehicle();

  - platform: template
    name: Flash light
    icon: mdi:car-light-high
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage (FLASH_LIGHT, 0);

  - platform: template
    name: Sound horn
    icon: mdi:bugle
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage (SOUND_HORN, 0);

  - platform: template
    name: Frunk
    icon: mdi:car
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_frontTrunk_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_OPEN);
  
  - platform: template
    name: Unlock charge port
    icon: mdi:ev-plug-ccs2
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_chargePort_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_OPEN);

  - platform: template
    name: Regenerate key
    icon: mdi:key-change
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->regenerateKey();
    entity_category: diagnostic
    disabled_by_default: true

  - platform: template
    name: Force data update
    icon: mdi:database-sync
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->enqueueVCSECInformationRequest(true);
    entity_category: diagnostic

sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ble_tesla_id
    name: "BLE Signal"
    icon: mdi:bluetooth
    update_interval: 60s
    entity_category: diagnostic

switch:
  - platform: template
    name: "Charger"
    optimistic: true
    icon: mdi:lightning-bolt
    assumed_state: true # we can't read the state of the charger over
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_SWITCH, 0);

  - platform: template
    name: "Sentry mode"
    optimistic: true
    icon: mdi:record-circle-outline
    assumed_state: true # we can't read the state 
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_SENTRY_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_SENTRY_SWITCH, 0);
  
  - platform: template
    name: "Climate"
    optimistic: true
    icon: mdi:fan
    lambda: |-
      if (id(is_climate_on).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_SWITCH, 0);

  - platform: template
    name: "Steering wheel heat"
    optimistic: true
    icon: mdi:steering
    assumed_state: true # we can't read the state 
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_STEERING_HEATER_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_STEERING_HEATER_SWITCH, 0);
  
  - platform: template
    name: "Charge port"
    optimistic: true
    icon: mdi:ev-plug-ccs2
    lambda: |-
      if (id(is_charge_flap_open).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_OPEN_CHARGE_PORT_DOOR,1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CLOSE_CHARGE_PORT_DOOR,1);

  - platform: template
    name: "Vent"
    optimistic: true
    icon: mdi:car-door
    assumed_state: true # we can't read the state 
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_WINDOWS_SWITCH,1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_WINDOWS_SWITCH,0);

  - platform: template
    name: "Boot"
    optimistic: true
    icon: mdi:car-back
    lambda: |-
      if (id(is_boot_open).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_rearTrunk_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_OPEN);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_rearTrunk_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_CLOSE);
      
  - platform: ble_client
    ble_client_id: ble_tesla_id
    name: "BLE Connection"
    entity_category: diagnostic

number:
  - platform: template
    name: "Charging amps"
    id: charging_amps
    icon: mdi:ev-station
    unit_of_measurement: "A"
    mode: slider
    update_interval: 2s
    min_value: 0
    max_value: $charging_amps_max
    step: 1
    set_action:
      - lambda: |-
          int var_x = static_cast<int>(x);
          id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_AMPS, var_x);
    lambda: |-
      if (id(max_amps).has_state())
      {
        return id(max_amps).state;
      }
      else return (0); 
  - platform: template
    name: "Charging limit"
    id: charging_limit
    icon: mdi:ev-station
    unit_of_measurement: "%"
    mode: slider
    update_interval: 2s
    min_value: 50
    max_value: 100
    step: 1
    set_action:
      - lambda: |-
          int var_x = static_cast<int>(x);
          id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_LIMIT, var_x);
    lambda: |-
      if (id(max_soc).has_state())
      {
        return id(max_soc).state;
      }
      else return (0); 
        
---
```

### Anything in the logs that might be useful for us?

```txt
[09:35:44][W][esp32_ble:417][BTC_TASK]: Ignoring unexpected GAP event type: 26
```

**Comment by slartibartfast11** [comment]
I have a similar issue after the update. I have a BLE receiver of electricity meter readings from a Powerpal device. Similar error, but it also appears to prevent the code from communicating after connecting to the device any further once the error is thrown.

**Comment by top-gun** [comment]
I switched to ESP-IDF 5.3.2 and removed the platform_version statement , no improvement. I do still see "unexpected GAP event type:26"

**Comment by asucrews** [comment]
Same issue, changing to mac address seems to work, but this less then ideal.

**Comment by bdraco** [comment]
Looks like we need

esphome/components/esp32_ble_beacon/esp32_ble_beacon.cpp:    case ESP_GAP_BLE_ADV_DATA_RAW_SET_COMPLETE_EVT: {
esphome/components/esp32_ble_beacon/esp32_ble_beacon.cpp:    case ESP_GAP_BLE_ADV_START_COMPLETE_EVT: {
esphome/components/esp32_ble_beacon/esp32_ble_beacon.cpp:    case ESP_GAP_BLE_ADV_STOP_COMPLETE_EVT: {

**Comment by asucrews** [comment]
imported [esphome PR 9138](https://github.com/esphome/esphome/pull/9138) changes via external_components and and seems to working for my usecase

```
external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: dev
    components: [ esp32_ble, esp32_ble_beacon, esp32_ble_tracker,bluetooth_proxy ]
    refresh: 1h
```
