### ISSUE TITLE
[2025.6.0] PSRAM 120MHz requires 240MHz CPU frequency (set in esp32 component).

### ISSUE THREAD

**Issue by derMicro** [esphome/issues#7131]
### The problem

When I try to update my Waveshare 7" Touch Panel to 2025.6.0, the error mentioned above appears.
Reducing to 80Mhz allowed me to run “Clean Build Files” but even after that an update with 120Mhz is not possible.

### Which version of ESPHome has the issue?

2025.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.1

### What platform are you using?

ESP32-IDF

### Board

esp32-s3-devkitc-1

### Component causing the issue

PSRAM

### YAML Config

```yaml
esphome:
  platformio_options:
    build_unflags: -Werror=all
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: qio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_ESPTOOLPY_FLASHFREQ_120M: y
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_IDF_EXPERIMENTAL_FEATURES: y
      CONFIG_SPIRAM_SPEED_120M: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      CONFIG_LV_MEM_CUSTOM: y
      CONFIG_LV_MEMCPY_MEMSET_STD: y
      CONFIG_LV_ATTRIBUTE_FAST_MEM: y
    advanced:
      enable_idf_experimental_features: true

psram:
  mode: octal
  speed: 120MHz
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

INFO ESPHome 2025.6.0
INFO Reading configuration /config/esphome/p-ku-lcd7touchpanel.yaml...
Failed config

psram: [source /config/_my/_esphome/packages/hardware/wavesharelcd7.yaml:36]
  
  PSRAM 120MHz requires 240MHz CPU frequency (set in esp32 component).
  mode: octal
  speed: 120MHZ
  enable_ecc: False

**Comment by clydebarrow** [comment]
As the message says, you need to set the CPU speed. Remove all the sdkconfig options, this is what you need.

```
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes

psram:
  mode: octal
  speed: 120MHz
```
