### ISSUE TITLE
Linking fails on adafruit_qtpy_esp32s3_nopsram with esp32-idf

### ISSUE THREAD

**Issue by agoode** [esphome/issues#7133]
### The problem

I updated to 2025.6.0 today and building for adafruit_qtpy_esp32s3_nopsram now fails. It worked previously.

### Which version of ESPHome has the issue?

2025.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.1

### What platform are you using?

ESP32-IDF

### Board

adafruit_qtpy_esp32s3_nopsram

### YAML Config

```yaml
esphome:
  name: orange-scd41
  friendly_name: "Orange SCD41"

esp32:
  board: adafruit_qtpy_esp32s3_nopsram
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  platform: esphome
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

bluetooth_proxy:
  active: true

esp32_ble_tracker:

output:
  - platform: gpio
    id: led_power
    pin: 38
    inverted: true

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 39
    num_leds: 1
    chipset: WS2812
    internal: true
    id: led
    effects:
      - pulse:
          transition_length: 5s
          update_interval: 5s
          min_brightness: 5%
          max_brightness: 35%
      - flicker:

i2c:
  sda: 41
  scl: 40
  scan: true
  frequency: 400kHz

sensor:
  - platform: homeassistant
    id: ambient_pressure
    entity_id: sensor.awn_weather_hub_abs_pressure

  - platform: scd4x
    id: scd41
    ambient_pressure_compensation_source: ambient_pressure
    co2:
      name: "Carbon dioxide"
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 5s
```

### Anything in the logs that might be useful for us?

```txt
Linking .pioenvs/orange-scd41/firmware.elf
RAM:   [==        ]  16.4% (used 53740 bytes from 327680 bytes)
Flash: [========  ]  76.5% (used 1403224 bytes from 1835008 bytes)
Building .pioenvs/orange-scd41/firmware.bin
Creating esp32s3 image...
Successfully created esp32s3 image.
esp32_create_combined_bin([".pioenvs/orange-scd41/firmware.bin"], [".pioenvs/orange-scd41/firmware.elf"])
usage: esptool merge_bin [-h] --output OUTPUT [--format {raw,uf2,hex}]
                         [--chunk-size CHUNK_SIZE] [--md5-disable]
                         [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                         [--flash_mode {keep,qio,qout,dio,dout}]
                         [--flash_size {keep,256KB,512KB,1MB,2MB,2MB-c1,4MB,4MB-c1,8MB,16MB,32MB,64MB,128MB}]
                         [--spi-connection SPI_CONNECTION]
                         [--target-offset TARGET_OFFSET]
                         [--fill-flash-size {256KB,512KB,1MB,2MB,4MB,8MB,16MB,32MB,64MB,128MB}]
                         <address> <filename> [<address> <filename> ...]
esptool merge_bin: error: argument <address> <filename>: [Errno 2] No such file or directory: '/data/build/orange-scd41/variants/tasmota/variants/adafruit_qtpy_esp32s3_nopsram/tinyuf2.bin'
*** [.pioenvs/orange-scd41/firmware.bin] Explicit exit, status 2
========================= [FAILED] Took 47.79 seconds =========================
```

**Comment by clydebarrow** [comment]
Use a more standard board choice:
```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
```
