### ISSUE TITLE
ESP32-C2 Compiling is failing to link bootloader since 2025.6.0

### ISSUE THREAD

**Issue by Maeur1** [esphome/issues#7137]
### The problem

Trying to upload a new firmware to an ESP32-C2 device and it appears to be failing to find a `bootloader.bin` file which seems to be failing the `merge_bin` command after compiling the firmware. Hence it cannot make a valid image to be uploaded to the ESP32-C2 switch I have.

### Which version of ESPHome has the issue?

2025.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.1

### What platform are you using?

ESP32-IDF

### Board

ESP8684-WROOM-04C (using the esp32-c2-devkitm-1 target)

### Component causing the issue

post_build.py script

### YAML Config

```yaml
esphome:
  name: switch-spare-bathroom
  friendly_name: Spare Bathroom Light Switch

packages:
  common: !include common/esp32.yaml

esp32:
  board: esp32-c2-devkitm-1
  framework:
    type: esp-idf
    version: latest
    sdkconfig_options:
      CONFIG_XTAL_FREQ_26: y

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "SpareBathSwitch Fallback Hotspot"
    password: !secret fallback_password

status_led:
  id: white_led
  pin:
    number: GPIO10
    inverted: true

switch:
  - platform: ld2410
    engineering_mode:
      name: "Engineering Mode"

output:
  - platform: gpio
    pin: GPIO6
    id: relay

light:
  - platform: binary
    name: "Spare Bathroom Lights"
    output: relay
    id: lights
    restore_mode: RESTORE_DEFAULT_ON
    
binary_sensor:
  - platform: ld2410
    has_target:
      name: Spare Bathroom Presence
    has_moving_target:
      name: Spare Bathroom Moving Target
    has_still_target:
      name: Spare Bathroom Still Target
  - platform: gpio
    internal: true
    pin:
      number: GPIO2
      mode: INPUT
      inverted: true
    name: "Switch Button"
    on_press:
      then:
        - light.toggle: lights

uart:
  id: uart_1
  tx_pin: GPIO20
  rx_pin: GPIO19
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

text_sensor:
  - platform: ld2410
    version:
      name: "LD2410 Firmware Version"
    mac_address:
      name: "LD2410 MAC Address"

ld2410:

sensor:
  - platform: ld2410
    light:
      name: Spare Bathroom Light Sensor
    moving_distance:
      name : Spare Bathroom Moving Distance
    still_distance:
      name: Spare Bathroom Still Distance
    moving_energy:
      name: Spare Bathroom Move Energy
    still_energy:
      name: Spare Bathroom Still Energy
    detection_distance:
      name: Spare Bathroom Detection Distance


number:
  - platform: ld2410
    timeout:
      name: LD2410 Timeout
    light_threshold:
      name: LD2410 Light Threshold
    max_move_distance_gate:
      name: LD2410 Max Move Distance Gate
    max_still_distance_gate:
      name: LD2410 Max Still Distance Gate
    g0:
      move_threshold:
        name: LD2410 g0 Move Threshold
      still_threshold:
        name: LD2410 g0 Still Threshold
    g1:
      move_threshold:
        name: LD2410 g1 Move Threshold
      still_threshold:
        name: LD2410 g1 Still Threshold
    g2:
      move_threshold:
        name: LD2410 g2 Move Threshold
      still_threshold:
        name: LD2410 g2 Still Threshold
    g3:
      move_threshold:
        name: LD2410 g3 Move Threshold
      still_threshold:
        name: LD2410 g3 Still Threshold
    g4:
      move_threshold:
        name: LD2410 g4 Move Threshold
      still_threshold:
        name: LD2410 g4 Still Threshold
    g5:
      move_threshold:
        name: LD2410 g5 Move Threshold
      still_threshold:
        name: LD2410 g5 Still Threshold
    g6:
      move_threshold:
        name: LD2410 g6 Move Threshold
      still_threshold:
        name: LD2410 g6 Still Threshold
    g7:
      move_threshold:
        name: LD2410 g7 Move Threshold
      still_threshold:
        name: LD2410 g7 Still Threshold
    g8:
      move_threshold:
        name: LD2410 g8 Move Threshold
      still_threshold:
        name: LD2410 g8 Still Threshold

button:
  - platform: ld2410
    factory_reset:
      name: LD2410 Factory Reset
    restart:
      name: LD2410 Restart
    query_params:
      name: LD2410 Query Params

select:
  - platform: ld2410
    distance_resolution:
      name: LD2410 Distance Resolution
    baud_rate:
      name: LD2410 Baud Rate
    light_function:
      name: LD2410 Light Function
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.6.0
INFO Reading configuration /config/esphome/switch-spare-bathroom.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.8.2
INFO Compiling app...
Processing switch-spare-bathroom (board: esp32-c2-devkitm-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32C2 120MHz, 272KB RAM, 4MB Flash
 - framework-arduino-c2-skeleton-lib @ 5.3.0+sha.083aad99cf 
 - framework-espidf @ 3.50302.0 (5.3.2) 
 - tool-cmake @ 3.30.2 
 - tool-esptoolpy @ 4.8.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 14.2.0+20240403 
 - tool-xtensa-esp-elf-gdb @ 14.2.0+20240403 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 13.2.0+20240530
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
RAM:   [=         ]  11.1% (used 30824 bytes from 278528 bytes)
Flash: [=====     ]  49.1% (used 900960 bytes from 1835008 bytes)
Building .pioenvs/switch-spare-bathroom/firmware.bin
Creating esp32c2 image...
Successfully created esp32c2 image.
esp32_create_combined_bin([".pioenvs/switch-spare-bathroom/firmware.bin"], [".pioenvs/switch-spare-bathroom/firmware.elf"])
usage: esptool merge_bin [-h] --output OUTPUT [--format {raw,uf2,hex}]
                         [--chunk-size CHUNK_SIZE] [--md5-disable]
                         [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                         [--flash_mode {keep,qio,qout,dio,dout}]
                         [--flash_size {keep,256KB,512KB,1MB,2MB,2MB-c1,4MB,4MB-c1,8MB,16MB,32MB,64MB,128MB}]
                         [--spi-connection SPI_CONNECTION]
                         [--target-offset TARGET_OFFSET]
                         [--fill-flash-size {256KB,512KB,1MB,2MB,4MB,8MB,16MB,32MB,64MB,128MB}]
                         <address> <filename> [<address> <filename> ...]
esptool merge_bin: error: argument <address> <filename>: [Errno 2] No such file or directory: '/data/build/switch-spare-bathroom/.pioenvs/switch-spare-bathroom/bootloader.bin'
*** [.pioenvs/switch-spare-bathroom/firmware.bin] Explicit exit, status 2
========================== [FAILED] Took 3.72 seconds ==========================
```

### Additional information

This was working perfectly fine and is still running fine on 2025.5.2 and I think it might be something to do with the esp-idf upgrade to 5.3.2? I do know this chip is currently unsupported but this was working fine in the previous version and some change to the FLASH_ARGs seems to have broken this?
