### ISSUE TITLE
receiver.rc_switch_raw does not receive what receiver.raw does

### ISSUE THREAD

**Issue by TheChatty** [esphome/issues#7139]
### The problem

I'm using esphome 2025.6.0 and got it working on a [esp32](https://www.az-delivery.de/en/products/esp-32-dev-kit-c-v4) with a CC1101 connected to it (for the moment using `source: github://pr#6300`).

Transmitting with raw & rc_switch_raw works fine.

**Receiving** works with raw but **does not with rc_switch_raw**.

### Which version of ESPHome has the issue?

2025.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.1

### What platform are you using?

ESP32

### Board

az-delivery-devkit-v4

### Component causing the issue

cc1101

### YAML Config

```yaml
binary_sensor:
    - platform: remote_receiver
      name: "Leinwand stop (proto)"
      rc_switch_raw:
        code: '1010001101000111100101101001011000000001000000000010001110010111'  # trailing '1' missing due to rc_switch limitation to 64 bits
        protocol:
          pulse_length: 200
          sync: [0,3]
      filters:
      - delayed_off: 400ms

    - platform: remote_receiver
      name: "Leinwand stop (raw)"
      raw:
        code: [-600,600,-200,200,-600,600,-200,200,-600,200,-600,200,-600,600,-200,600,-200,200,-600,600,-200,200,-600,200,-600,200,-600,600,-200,600,-200,600,-200,600,-200,200,-600,200,-600,600,-200,200,-600,600,-200,600,-200,200,-600,600,-200,200,-600,200,-600,600,-200,200,-600,600,-200,600,-200,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,600,-200,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,600,-200,200,-600,200,-600,200,-600,600,-200,600,-200,600,-200,200,-600,200,-600,600,-200,200,-600,600,-200,600,-200,600,-200,600,-200]
      filters:
      - delayed_off: 400ms
```

### Anything in the logs that might be useful for us?

```txt

```
