### ISSUE TITLE
Unable to send 24bit RC6 message with remote_transmitter.transmit_rc6

### ISSUE THREAD

**Issue by anishsane** [esphome/issues#7140]
### The problem

The RC6 message sent with remote_transmitter.transmit_rc6 is always 20 bits. We cannot send a 24bit message.
It would be useful to add nbits parameter.
Even the [IRremoteESP8266](https://github.com/crankyoldgit/IRremoteESP8266/blob/master/src/ir_RC5_RC6.cpp#L191) library has this parameter. But it is missing in the esphome.

### Which version of ESPHome has the issue?

2025.5.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2025.5.2

### What platform are you using?

ESP32-IDF

### Board

m5stack-atom-echo

### Component causing the issue

remote_transmitter (IR TX)

### YAML Config

```yaml
remote_transmitter:
  pin: GPIO12
  carrier_duty_percent: 50%


api:
  services:
    - service: send_ir
      variables:
        address: string
        protocol: string
        command: string
      then:
        - lambda: 'ESP_LOGD("main", "Protocol: %s - command: %s",  protocol.c_str(), command.c_str()); '
        - if:
            condition:
              lambda: 'return protocol == "RC6";'
            then:
              - logger.log: "Sending RC6 data...!"
              - remote_transmitter.transmit_rc6:
                  address: !lambda |-
                      long int j;
                      sscanf( command.c_str(), "%lx", &j );
                      return j;
                  command: !lambda |-
                      long int i;
                      sscanf( command.c_str(), "%lx", &i );
                      return i;
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

I verified with Tasmota based IR receiver:

Sent from esphome:
```
18:38:07.062 RSL: RESULT = {"IrReceived":{"Protocol":"RC6","Bits":20,"Data":"0x13434","DataLSB":"0x802C2C","Repeat":0}}
18:38:20.570 RSL: RESULT = {"IrReceived":{"Protocol":"RC6","Bits":20,"Data":"0x3434","DataLSB":"0x2C2C","Repeat":0}}
18:24:32.241 RSL: RESULT = {"IrReceived":{"Protocol":"RC6","Bits":20,"Data":"0x1FFFF","DataLSB":"0x80FFFF","Repeat":0}}
```
Sent from physical IR remote:
```
18:25:11.090 RSL: RESULT = {"IrReceived":{"Protocol":"RC6","Bits":24,"Data":"0xC0000C","DataLSB":"0x30030","Repeat":0}}
18:25:11.251 RSL: RESULT = {"IrReceived":{"Protocol":"RC6","Bits":24,"Data":"0xC0000C","DataLSB":"0x30030","Repeat":0}}
```

With address = 0x1234, data = 0x5678, I get this result:
```
19:05:15.874 RSL: RESULT = {"IrReceived":{"Protocol":"RC6","Bits":20,"Data":"0x7878","DataLSB":"0x1E1E","Repeat":0}}
```
