### ISSUE TITLE
SNTP time always UTC after upgrading to 2025.6

### ISSUE THREAD

**Issue by briis** [esphome/issues#7141]
### The problem

I have this time setup in my config:
```yaml
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Copenhagen
    servers:
      - 0.dk.pool.ntp.org
      - 1.dk.pool.ntp.org
      - 2.dk.pool.ntp.org
 ````
But after upgrading to ESPHome 2025.6 this always returns the time in UTC.

### Which version of ESPHome has the issue?

2025.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6

### What platform are you using?

ESP32-IDF

### Board

ESP32-S3

### Component causing the issue

sntp

### YAML Config

```yaml

```

### Anything in the logs that might be useful for us?

```txt
No errors are reported, it just sets the time wrong
```

### Additional information

When using the time platform: homeassistant, I do not get this error
