### ISSUE TITLE
ESP32-C6 onboard LED color channels for esp32_rmt_led_strip unresponsive to rgb_order

### ISSUE THREAD

**Issue by OBoudreaux** [esphome/issues#7143]
### The problem

Attempting to fiddle with a [C6](https://github.com/wuxx/nanoESP32-C6/blob/master/README_en.md) onboard led using esp32_rmt_led_strip. 

rgb_order: [RBG,GBR,BRG,etc] has no effect. The blue channel is always correct and the red and green are swapped. Logs show correct color values as set in HA (e.g. selecting red in HA and the logs show "Red: 100%, Green: 0%, Blue: 0%" but the LED is green.

### Which version of ESPHome has the issue?

2025.6.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2025.6.1

### What platform are you using?

ESP32-IDF

### Board

nanoESP32-C6

### Component causing the issue

esp32_rmt_led_strip

### YAML Config

```yaml
esphome:
  name: esp32-c6
  friendly_name: esp32_C6
  min_version: 2025.5.0
  name_add_mac_suffix: false
  on_boot:
    priority: 400
    then:
      - light.turn_on:
          id: status_led
          brightness: 25%
          red: 0%
          green: 0%
          blue: 100%

esp32:
  board: esp32-c6-devkitm-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ABC"

ota:
  - platform: esphome
    password: "123"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  on_connect:
    then:
      - light.turn_on:
          id: status_led
          brightness: 25%
          red: 0%
          green: 100%
          blue: 0%

  on_disconnect:
    then:
      - light.turn_on:
          id: status_led
          brightness: 25%
          red: 100%
          green: 0%
          blue: 0%

  ap:
    ssid: "Esp32-C6 Fallback Hotspot"
    password: "DoRayMe"

captive_portal:

web_server:
  local: True

switch:
  - platform: restart
    name: "Device Restart"
sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 30s
    entity_category: diagnostic
    filters:
      - throttle: 10min
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    entity_category: diagnostic
    update_interval: 60s
    filters:
      - throttle: 600s

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GBR
    pin: GPIO8
    num_leds: 1
    chipset: WS2812
    id: status_led
    name: "Light"
    icon: "mdi:led-outline"
    default_transition_length: 0.25s
    effects:
      - random:
      - flicker:
      - addressable_rainbow:
```

### Anything in the logs that might be useful for us?

```txt

```
