### ISSUE TITLE
Warning: esp_adc

### ISSUE THREAD

**Issue by maba64** [esphome/issues#7144]
### The problem

INFO ESPHome 2025.6.0
INFO Reading configuration /config/esphome/tanne.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.8.2
INFO Compiling app...
Processing tanne (board: esp32dev; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50302.0 (5.3.2) 
 - tool-cmake @ 3.30.2 
 - tool-esptoolpy @ 4.8.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 14.2.0+20240403 
 - tool-xtensa-esp-elf-gdb @ 14.2.0+20240403 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp-elf @ 13.2.0+20240530
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.6
Compiling .pioenvs/tanne/src/main.cpp.o
In file included from src/esphome/components/adc/adc_sensor.h:9,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-espidf/components/esp_adc/deprecated/include/esp_adc_cal.h:17:2: warning: #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h" [-Wcpp]
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:10:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
Linking .pioenvs/tanne/firmware.elf
RAM:   [=         ]  10.5% (used 34268 bytes from 327680 bytes)
Flash: [=====     ]  51.8% (used 950456 bytes from 1835008 bytes)
Building .pioenvs/tanne/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/tanne/firmware.bin"], [".pioenvs/tanne/firmware.elf"])
SHA digest in image updated
Wrote 0xf8220 bytes to file /data/build/tanne/.pioenvs/tanne/firmware.factory.bin, ready to flash to offset 0x0
esp32_copy_ota_bin([".pioenvs/tanne/firmware.bin"], [".pioenvs/tanne/firmware.elf"])
========================= [SUCCESS] Took 15.23 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 192.168.0.96 port 3232...
INFO Connected to 192.168.0.96
INFO Uploading /data/build/tanne/.pioenvs/tanne/firmware.bin (950816 bytes)
Uploading: [============================================================] 100% Done...

### Which version of ESPHome has the issue?

ESPHome 2025.6.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

nodemcu,

### Component causing the issue

esp adc

### YAML Config

```yaml
esphome:
  name: tanne
  friendly_name: tanne

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "L3LmNxkEuMETVbZOhkZI7IVEQDhZ86B1vsPWXDHEWc8="

ota:
  - platform: esphome
    password: "1cf60a15079e71f8009ee8fa2b9ea141"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tanne Fallback Hotspot"
    password: "dULUIv7rkESM"

one_wire:
  - platform: gpio
    pin: GPIO23 # Passe an deinen Anschluss für DS18B20 an
    id: bus1
captive_portal:
    

sensor:
      
    # Battery Sensor
  - platform: adc
    id: solar_plant_batt_voltage
    pin: GPIO33
    attenuation: 12db
    name: "Battery Voltage"
    update_interval: 10s
    accuracy_decimals: 2
    filters:
        - calibrate_linear:
            # Map from ESP32 voltage to Battery voltage
            - 0.0 -> 0
            - 1.96 -> 4.02 #measured 4.2V with multimeter while ESPHome reported 3.09V
        #use moving median to smooth spikes
        - median:
            window_size: 5
            send_every: 2
            send_first_at: 1

  # Bodenfeuchte Rohwert (ADC)
  - platform: adc
    pin: GPIO34
    attenuation: 12db
    name: "Bodenfeuchtigkeit Roh"
    id: soil_moisture_raw
    update_interval: 20s
    accuracy_decimals: 2

  # Bodenfeuchte als Prozent (angepasst auf DEINE Kalibrierung!)
  - platform: template
    name: "Bodenfeuchtigkeit (%)"
    id: soil_moisture_percent
    unit_of_measurement: "%"
    lambda: |-
      float trocken = 2.6; // ADC-Wert trocken (z.B. 2.6V)
      float nass = 1.1; // ADC-Wert nass (z.B. 1.1V)
      float val = id(soil_moisture_raw).state;
      float prozent = (trocken - val) * 100.0 / (trocken - nass);
      if (prozent < 0) prozent = 0;
      if (prozent > 100) prozent = 100;
      return prozent;
    #update_interval: never
    update_interval: 20s






  # DS18B20 Temperatur
  - platform: dallas_temp
    address: 0x1234567812345628
    name: temperature
    update_interval: 120s
    one_wire_id: bus1
```

### Anything in the logs that might be useful for us?

```txt

```
