### ISSUE TITLE
Sprinkler problem

### ISSUE THREAD

**Issue by CerboJoe** [esphome/issues#7155]
### The problem

When no spinkler is "Aktiv" and sprinkler system will be startet, all sprinklers get set to aktiv and run. As long, at least on srinkler is aktiv, it works fine. So, when all of my Plants are wet enough, it will start water them all.
I set the state of "Aktiv" or not by soil moisture sensor.

### Which version of ESPHome has the issue?

2025.6.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### YAML Config

```yaml
esphome:
  name: bewasserungssteuerung
  friendly_name: Bewasserungssteuerung

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: H220..
ota:
  - platform: esphome
    password: "b41af6a7836f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bewasserungssteuerung Hotspot"
    password: "oMnf1"

captive_portal:

switch:
  - platform: gpio
#    name: "Relay 1"
    pin:
      number: GPIO21
      inverted: true
    restore_mode: ALWAYS_OFF
    id: p1
    on_turn_on:
    - delay: 30s
    - switch.turn_off: p1
    internal: true
  - platform: gpio
#    name: "Relay 2"
    pin:
      number: GPIO22
      inverted: true
    restore_mode: ALWAYS_OFF
    id: p2
    on_turn_on:
    - delay: 30s
    - switch.turn_off: p2
  - platform: gpio
#    name: "Relay 3"
    pin:
      number: GPIO23
      inverted: true
    restore_mode: ALWAYS_OFF
    id: p3
    on_turn_on:
    - delay: 30s
    - switch.turn_off: p3
  - platform: gpio
#    name: "Relay 4"
    pin:
      number: GPIO25
      inverted: true
    restore_mode: ALWAYS_OFF
    id: p4
    on_turn_on:
    - delay: 30s
    - switch.turn_off: p4

  - platform: gpio
    name: "Wasserpumpe"
    pin:
      number: GPIO33
      inverted: true
    restore_mode: ALWAYS_OFF
    id: pumpe
    on_turn_on:
    - delay: 180s
    - switch.turn_off: pumpe


sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"


sprinkler:
  - id: sprinklersystem
    main_switch: "Sprinkler System"
    auto_advance_switch: "Advance"
    valve_overlap: 1s
    valves:
      - valve_switch: "P 1"
        enable_switch: "P1 Aktiv"
        run_duration: 10s
        valve_switch_id: p1
        pump_switch_id: pumpe
      - valve_switch: "P 2"
        enable_switch: "P2 Aktiv"
        run_duration: 10s
        valve_switch_id: p2
        pump_switch_id: pumpe        
      - valve_switch: "P 3"
        enable_switch: "P3 Aktiv"
        run_duration: 10s
        valve_switch_id: p3
        pump_switch_id: pumpe
      - valve_switch: "P 4"
        enable_switch: "P4 Aktiv"
        run_duration: 10s
        valve_switch_id: p4
        pump_switch_id: pumpe


button:
  - platform: restart
    name: "Reboot"
```

### Anything in the logs that might be useful for us?

```txt

```
