### ISSUE TITLE
[lvgl] lvgl.qrcode.update doesn't manage dynamic strings properly

### ISSUE THREAD

**Issue by agillis** [esphome/issues#7157]
### The problem

This does does not work a creates a QRcode that returns gibberish. I can use lvgl.qrcode.update to generate a QRCode of anything else and it works fine. Only WiFi text strings seems to be broken.

```
  - platform: template
    name: "Device Name"
    id: device_name
    internal: true
    lambda: |-
      return {App.get_name().c_str()};
    on_value:
      then:
        - lvgl.label.update:
            id: device_name_label
            text:
              format: "%s"
              args: [ 'id(device_name).state.c_str()' ]
        - lvgl.qrcode.update:
            id: cp_login
            text: 
              format: "WIFI:S:%s;T:WPA;P:password;I:192.168.4.1;;"
              args: [ 'id(device_name).state.c_str()' ]
```

This works fine too.

```
              - qrcode:
                  id: cp_login
                  size: 100
                  text: "WIFI:S:nonet;T:WPA;P:password;I:192.168.4.1;;"  
```

### Which version of ESPHome has the issue?

2025.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Latest

### What platform are you using?

ESP32-IDF

### Board

SDL

### Component causing the issue

lvgl.qrcode.update

### YAML Config

```yaml
- platform: template
    name: "Device Name"
    id: device_name
    internal: true
    lambda: |-
      return {App.get_name().c_str()};
    on_value:
      then:
        - lvgl.label.update:
            id: device_name_label
            text:
              format: "%s"
              args: [ 'id(device_name).state.c_str()' ]
        - lvgl.qrcode.update:
            id: cp_login
            text: 
              format: "WIFI:S:%s;T:WPA;P:password;I:192.168.4.1;;"
              args: [ 'id(device_name).state.c_str()' ]
```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

![Image](https://github.com/user-attachments/assets/81e85906-6af9-415a-ad7c-e5666a1b9a76)
This is the generated Qcode
