### ISSUE TITLE
Cannot compile for ESP8266 boards

### ISSUE THREAD

**Issue by jullit31** [esphome/issues#7158]
### The problem

Compiling even the basic auto-generated yaml for ESP8266 boards fails. Compiling for ESP32 works fine, as long as
``` 
framework:
    type: arduino
```
is set.

### Which version of ESPHome has the issue?

2025.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.2

### What platform are you using?

ESP8266

### Board

nodemcu, esp01_1m, d1_mini (doesn't seem to matter)

### YAML Config

```yaml
esphome:
  name: test2
  friendly_name: test2

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "oRXsNZi/1gDSEGEOozzclUyoB+tjeWM+pcXrj8x+Ac8="

ota:
  - platform: esphome
    password: "6712e030e9a4aeec3fb17675a857dfb8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test2 Fallback Hotspot"
    password: "g1VCYtmIrk1Q"

captive_portal:
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.6.1
INFO Reading configuration /config/esphome/test2.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing test2 (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.6
Compiling .pioenvs/test2/src/esphome/components/api/api_connection.cpp.o
In file included from src/esphome/core/macros.h:7,
                 from src/esphome/core/defines.h:2,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome/components/api/api_connection.cpp:1:
/data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:27:10: fatal error: stdlib.h: No such file or directory

****************************************************************
* Looking for stdlib.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:stdlib.h"
* Web  > https://registry.platformio.org/search?q=header:stdlib.h
*
****************************************************************

   27 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
Compiling .pioenvs/test2/src/esphome/components/api/api_frame_helper.cpp.o
*** [.pioenvs/test2/src/esphome/components/api/api_connection.cpp.o] Error 1
In file included from src/esphome/components/api/api_frame_helper.cpp:1:
src/esphome/components/api/api_frame_helper.h:2:10: fatal error: cstdint: No such file or directory
    2 | #include <cstdint>
      |          ^~~~~~~~~
compilation terminated.
*** [.pioenvs/test2/src/esphome/components/api/api_frame_helper.cpp.o] Error 1
========================== [FAILED] Took 2.78 seconds ==========================
```

### Additional information

Home Assistant on a Raspberry Pi 4.
