### ISSUE TITLE
Fresh installs don't work when the device name is only numbers

### ISSUE THREAD

**Issue by jtenniswood** [esphome/issues#7159]
### The problem

When I try to name a device with numbers the installer fails. When I do the same with a letter at the start, it works fine. 

### Which version of ESPHome has the issue?

2506

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2506

### What platform are you using?

ESP32

### Board

Xiao C3

### YAML Config

```yaml
# Xiao C3
substitutions:
  name: "6194"
  friendly_name: "6194"
  room: "Home"

# Presence Sensor
  rx_pin: "GPIO3"
  tx_pin: "GPIO4"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome/
    files: [base/xiao-c3.yaml,
            addon/bluetooth.yaml,
            addon/presence-xiao.yaml,
            addon/network.yaml,
            addon/webserver.yaml]
    refresh: 1sec
```

### Anything in the logs that might be useful for us?

```txt

```
