### ISSUE TITLE
2025.6.1: Project with BLE Tracker won't compile

### ISSUE THREAD

**Issue by top-gun** [esphome/issues#7161]
### The problem

This project has been working with 2025.6.0 . With 2025.6.1, compiling fails. From my understanding, this is an issue in the source of the Esphome components, but way above my level of competence.

### Which version of ESPHome has the issue?

2025.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.1

### What platform are you using?

ESP32-IDF

### Board

ESP32 devkit-c

### Component causing the issue

BLE-Tracker (not 100% sure)

### YAML Config

```yaml
substitutions:
  # all substitutions for this project
  espidf_version: "5.3.2"
  friendly_name: Tesla BLE F549C4
  device_name: tesla-ble-f549c4
  device_description: Tesla BLE
  board: esp32dev
  variant: esp32
  flash_size: 4MB
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "16"

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
#  source: github://top-gun/esphome-tesla-ble-test@dev
  source: github://PedroKTFC/esphome-tesla-ble@dev


packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml@dev
#  base:  github://top-gun/esphome-tesla-ble-test/packages/base.yml@dev
  device_base: github://PedroKTFC/esphome-tesla-ble/boards/esp32-generic.yml@dev
#  device_base: github://top-gun/esphome-tesla-ble-test/boards/esp32-generic.yml@dev
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml@dev
#  client: github://top-gun/esphome-tesla-ble-test/packages/client.yml@dev
  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git#dev 
      
tesla_ble_vehicle:
  odometer:
    name: "Odometer" # Rename if desired
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 180 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
  ble_disconnected_min_time: 120 # Minimum time BLE must be disconnected before sensors are Unknwon (s)

esp32_ble_tracker:
  max_connections: 1
  

########################
# personalized custom stuff starts here, this is for my 128x64 dot OLED display
########################


light:
  - platform: binary
    name: "ESP LED"
    output: light_output


output:
  - id: light_output
    platform: gpio
    pin: GPIO02
   
# i2c config
i2c:
    sda: 21
    scl: 22
    scan: True
    frequency: 800kHz


sensor:
  - platform: homeassistant
    name: "SOC from Tesla"
    entity_id: sensor.tesla_ble_f549c4_charge_level
    id: SOC_sensor
  - platform: homeassistant
    name: "KW from Tesla"
    entity_id: sensor.tesla_ble_f549c4_charge_power
    id: Amp_sensor
  - platform: homeassistant
    name: "BLE Signal"
    entity_id: sensor.tesla_ble_f549c4_ble_signal
    id: BLE_strength
  - platform: ble_rssi
    mac_address: ${ble_mac_address}
    name: "RSSI via ble_rssi"
#    update_interval: 60s

text_sensor:
  - platform: homeassistant
    name: "CHG State"
    entity_id: sensor.tesla_ble_f549c4_charging_state
    id: CHG_State
    filters:
      - substitute:
        - "charging -> Lade"
        - "unknown -> Unbekannt"
        - "Stopped -> Angehalten"
        - "Disconnected -> K. Kabel"
        - "completed -> Fertig"


display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    reset_pin: 16
    lambda: |-
      it.printf(0, 0, id(my_font), "SOC: %.0f %s", id(SOC_sensor).state, id(CHG_State).state.c_str() );
      it.printf(0, 20, id(my_font), "Ladeleistung: %.0f",id(Amp_sensor).state);
      it.printf(0, 40, id(my_font), "Signal: %.0f",id(BLE_strength).state);

font:
  - file: "gfonts://Roboto Condensed"
#  - file: "gfonts://Jost"
    id: my_font
    size: 15
```

### Anything in the logs that might be useful for us?

```txt
See screen shot. I understand there is some inconsistency between the order in which API objects are initialized and the compiler decides  this is not ok.
```

### Additional information

This is the error during the build:

![Image](https://github.com/user-attachments/assets/b3385b05-6328-47d0-80cf-bdd0f19ce6b4)
