### ISSUE TITLE
LD2410 sensor data 'Unknown' on ESP8266 & ESP32-C3 after recent update (UART issue)

### ISSUE THREAD

**Issue by MrCrin** [esphome/issues#7163]
### The problem

An LD2410 presence sensor that was working perfectly for weeks on an ESP8266 stopped providing data after a recent ESPHome update. The ESPHome device connects to Wi-Fi and Home Assistant, and all entities for the ld2410 component are created, but their state remains "Unknown".

To rule out hardware failure, I built a brand new ESPHome device from scratch using an ESP32-C3 board and a brand new LD2410 sensor module. The exact same failure occurs.

I can connect to the LD2410 sensor directly via Bluetooth, and I can see all the presence and distance data perfectly. 

### Which version of ESPHome has the issue?

2025.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.3

### What platform are you using?

ESP32

### Board

ESP32 C3 Zero (Also on ESP8266 originally - see above)

### Component causing the issue

ld2410

### YAML Config

```yaml
esphome:
  name: office-sensors
  friendly_name: Office Sensors

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

ld2410:

uart:
  tx_pin: 21
  rx_pin: 20
  baud_rate: 256000

i2c:
  sda: 8
  scl: 9
  scan: true
  id: bus_a

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  - platform: esphome
    password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Office-Sensors Fallback Hotspot"
    password: "***"

captive_portal:

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"


sensor:

  - platform: scd4x
    co2:
      name: "Office CO2"
    temperature:
      id: "office_temperature"
      name: "Office Temperature"
    humidity:
      id: "office_humidity"
      name: "Office Humidity"

  - platform: sgp30
    eco2:
      name: "Office eCO2"
      accuracy_decimals: 1
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 15
    tvoc:
      name: "Office TVOC"
      accuracy_decimals: 1
      filters:
        - exponential_moving_average:
            alpha: 0.1
            send_every: 15
    store_baseline: yes
    address: 0x58
    update_interval: 1s
    compensation:
      temperature_source: "office_temperature"
      humidity_source: "office_humidity"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  #mmWave Presence
  - platform: ld2410
    light:
      name: "Light"
    moving_distance:
      name : "Moving Distance"
    still_distance:
      name: "Still Distance"
    moving_energy:
      name: "Move Energy"
    still_energy:
      name: "Still Energy"
    detection_distance:
      name: "Detection Distance"
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold

button:
  - platform: ld2410
    factory_reset:
      name: "Factory Reset"
    restart:
      name: "Restart"
    query_params:
      name: query params

text_sensor:
  - platform: ld2410
    version:
      name: "Firmware Version"
    mac_address:
      name: "MAC Address"

select:
  - platform: ld2410
    distance_resolution:
      name: "Distance Resolution"
    baud_rate:
      name: "Baud Rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level
```

### Anything in the logs that might be useful for us?

```txt

```
