### ISSUE TITLE
Discovery messages aren't published retained although they should

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [esphome/issues#7165]
### The problem

My esphome device (gas/water meter), doesn't publish the MQTT discovery messages retained.
Currently this is the only one running 2025.6 (others aren't updated and all their discovery messages are retained.

Manual publishing retained messages works (I've checked with MQTT Explorer), however the discovery messages aren't.
I've explicitly set retain in the mqtt module:

```
mqtt:
  broker: "192.168.1.245"
  discovery: true
  discovery_retain: true
```
If I restart the esp device the discovery messages are published (I also deleted them from MQTT before), HA discovers them, but then forget about them again since they are not retained...

### Which version of ESPHome has the issue?

2025.6.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2025.6.3

### What platform are you using?

ESP8266

### Board

D1_mini

### Component causing the issue

mqtt

### YAML Config

```yaml
esphome:
  name: meters

esp8266:
  board: d1_mini

web_server:
  port: 80

logger:
  level: info

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "xxx"
  password: "xxxxxxxxx"
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.3.29
    gateway: 192.168.3.254
    subnet: 255.255.255.0

mqtt:
  broker: "192.168.1.245"
  discovery: true
  discovery_retain: true
  on_message:
    - topic: "gaszaehler/reading"
      then:
        - lambda: |-
            std::string payload = x.c_str();
            float val = std::stof(payload);
            float new_val = std::round(val * 100.0f) / 100.0f;
            if (new_val != id(gas_zaehlerstand)) {
              id(gas_zaehlerstand) = new_val;
              ESP_LOGI("mqtt", "Received Gas value: %.2f", id(gas_zaehlerstand));
              id(gas_reading).publish_state(id(gas_zaehlerstand));
            }
    - topic: "wasserzaehler/reading"
      then:
        - lambda: |-
            std::string payload = x.c_str();
            float val = std::stof(payload);
            float new_val = std::round(val * 100.0f) / 100.0f;
            if (new_val != id(wasser_zaehlerstand)) {
              id(wasser_zaehlerstand) = new_val;
              ESP_LOGI("mqtt", "Received Water value: %.2f", id(wasser_zaehlerstand));
              id(water_reading).publish_state(id(wasser_zaehlerstand));
            }

captive_portal:
    
globals:
  - id: total_pulses_gas
    type: int
    restore_value: false
    initial_value: '0'
  - id: gas_zaehlerstand
    type: float
    restore_value: false
  - id: total_pulses_water
    type: int
    restore_value: false
    initial_value: '0'
  - id: wasser_zaehlerstand
    type: float
    restore_value: false

binary_sensor:
  - platform: gpio
    id: internal_pulse_counter_gas
    pin:
      number: D2
      mode: INPUT
      inverted: true
    name: "Live-Impuls Gas"
    on_press:
      - lambda: |-
          id(total_pulses_gas) += 1;
          id(gas_zaehlerstand) += 0.01;
          ESP_LOGI("main", "Pulses gas since restart: %d", id(total_pulses_gas));
          ESP_LOGI("main", "Current reading gas: %.2f", id(gas_zaehlerstand));
          id(gas_reading).publish_state(id(gas_zaehlerstand));
      - mqtt.publish:
          topic: "gaszaehler/reading"
          payload: !lambda 'return String(id(gas_zaehlerstand)).c_str();'
          retain: true
  - platform: gpio
    id: internal_pulse_counter_water
    pin:
      number: D5
      mode: INPUT
      inverted: true
    name: "Live-Impuls Wasser"
    on_press:
      - lambda: |-
          id(total_pulses_water) += 1;
          id(wasser_zaehlerstand) += 0.01;
          ESP_LOGI("main", "Pulses water since restart: %d", id(total_pulses_water));
          ESP_LOGI("main", "Current reading water: %.2f", id(wasser_zaehlerstand));
          id(water_reading).publish_state(id(wasser_zaehlerstand));
      - mqtt.publish:
          topic: "wasserzaehler/reading"
          payload: !lambda 'return String(id(wasser_zaehlerstand)).c_str();'
          retain: true

sensor:
  - platform: template
    name: "Wasserverbrauch"
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:water"
    accuracy_decimals: 2
    lambda: |-
      return id(total_pulses_water) * 0.01;

  - platform: template
    name: "Zaehlerstand Wasser"
    id: water_reading
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:water"
    accuracy_decimals: 2

  - platform: template
    name: "Gasverbrauch"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:fire"
    accuracy_decimals: 2
    lambda: |-
      return id(total_pulses_gas) * 0.01;

  - platform: template
    name: "Zaehlerstand Gas"
    id: gas_reading
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:fire"
    accuracy_decimals: 2
  
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "Gas/Wasserzaehler WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "Gas/Wasserzeahler WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

switch:
  - platform: restart
    name: Restart
    id: restart_meter
```

### Anything in the logs that might be useful for us?

```txt

```
