### ISSUE TITLE
Main relay always stays ON after power loss on GoSund SP112 with ESPHome 2025.6.1 (ALWAYS_OFF not respected)

### ISSUE THREAD

**Issue by KaleiRo** [esphome/issues#7166]
### The problem

Hi,

I’m experiencing an issue with GoSund SP112 smart plugs flashed with ESPHome version 2025.6.1.

Problem description:
Whenever there is a power outage (i.e., the plug is physically unplugged from the mains and then plugged back in), the main relay always stays ON, regardless of the ALWAYS_OFF setting or any other configured restore mode.

I’ve tried the following:

Setting different restore_mode options for the main switch (including ALWAYS_OFF, ALWAYS_ON, RESTORE_DEFAULT_ON, etc.)

Flashing the device with various configurations

What I noticed:

If I reboot the device by flashing it, the relay behaves as expected and respects the configured restore mode or initial state.

But if there is a physical power cut (unplug/plug), the relay always comes up as ON, ignoring the configuration.

This issue only occurs after a complete loss of power (not on normal software reboots).

Is this a known issue, or is there a workaround for this behavior?
Is it possible that there is a hardware-specific initialization problem with the SP112 and ESPHome on cold boot (after full power loss)? Any help or suggestions would be much appreciated!

Let me know if you need more information or logs!

Thanks in advance!

### Which version of ESPHome has the issue?

2025.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.3

### What platform are you using?

ESP8266

### Board

esp01_1m

### YAML Config

```yaml

substitutions:
  devicename: "gosund_sp112"
  upper_devicename: "Gosund SP112"

esphome:
  name: esphome-web-0a6193
  friendly_name: esphome-web-0a6193

esp8266:
  board: esp01_1m
  restore_from_flash: true
  # This allows the device to restore the last saved relay state, either "ON" or "OFF" for the switch later in this config

preferences:
  flash_write_interval: 5min  # set to 5min to prevent wearing out the onboard flash module too quickly

# Reduce log level as otherwise logs would be flooded with analog sensor readings
logger:
  logs:
    sensor: INFO
    adc: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxx"

ota:
    platform: esphome
    password: "xxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  manual_ip:
    static_ip: 192.168.120.102
    gateway: 192.168.120.254
    subnet: 255.255.255.0
    dns1: 192.168.120.254

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-0A6193"
    password: "xxxxxxxxxxxxxxxx"

captive_portal:

# see: https://esphome.io/components/time.html, required for total_daily_energy
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server
web_server:
  port: 80

text_sensor:
  - platform: version
    name: "${devicename} - Version"
    icon: mdi:cube-outline

binary_sensor:
  - platform: template
    id: button1
    # read analog sensor and convert it's value to binary state
    lambda: return (id(button_adc).state < .5);
    on_click:
      # short button press toggles mains
      - min_length: 10ms
        max_length: 250ms
        then:
          - switch.toggle: switch1
      # long button press toggles USB
      - min_length: 250ms
        max_length: 1000ms
        then:
          - switch.toggle: switchusb

sensor:
  - platform: wifi_signal
    name: "${devicename} - Wifi Signal"
    update_interval: 60s
    icon: mdi:wifi

  - platform: uptime
    name: "${devicename} - Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

  - platform: total_daily_energy
    name: "${devicename} - Todays Usage"
    power_id: "wattage"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:calendar-clock

  - platform: adc
    id: button_adc
    pin: A0
    update_interval: .1s
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO04
    current_resistor: 0.00221
    voltage_divider: 775
    change_mode_every: 8
    update_interval: 10s
    current:
      id: amperage
      name: Amperage
      unit_of_measurement: A
      accuracy_decimals: 2
    voltage:
      id: voltage
      name: Voltage
      unit_of_measurement: V
      accuracy_decimals: 2
    power:
      id: wattage
      name: Wattage
      unit_of_measurement: W
      accuracy_decimals: 2

status_led:
  pin:
    number: GPIO02
    inverted: true

output:
  - platform: gpio
    id: led1
    pin:
      number: GPIO00
      inverted: true

switch:
  - platform: gpio
    name: "${devicename} - Main"
    icon: mdi:power
    restore_mode: RESTORE_DEFAULT_OFF
    id: switch1
    pin: GPIO14
    on_turn_on:
      - output.turn_on: led1
    on_turn_off:
      - output.turn_off: led1
  - platform: gpio
    name: "${devicename} - USB"
    icon: mdi:power
    restore_mode: RESTORE_DEFAULT_OFF
    id: switchusb
    pin:
      number: GPIO13
      inverted: true

```

### Anything in the logs that might be useful for us?

```txt

```
