### ISSUE TITLE
ESPHome 2025.6 breaks uart

### ISSUE THREAD

**Issue by oeiber** [esphome/issues#7167]
### The problem

After upgrading to 2025.6.0 or 2025.6.1 following Log message appears:
```
[23:38:14][W][uart.idf:149]: uart_param_config failed: ESP_ERR_NOT_SUPPORTED
[23:38:14][E][component:138]: Component uart was marked as failed.
[23:38:14][D][esp-idf:000]: E (6433) uart: uart_param_config(846): register back up is not supported
```

### Which version of ESPHome has the issue?

2025.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.3

### What platform are you using?

ESP32

### YAML Config

```yaml
esphome:
  name: "hcp01"
  friendly_name: "HCP01"
  platformio_options:
    monitor_filters: esp32_exception_decoder

external_components:
    - source: github://14yannick/hoermann_door
      refresh: 0s

esp32:
  board: adafruit_feather_esp32s3
  framework:
    type: esp-idf

logger:
  logs:
    uapbridge_esp: NONE

ota:
  - platform: esphome
    password: "xgUChqY38CLu5kpd6RhfZRMo2pjsYBVo"

uart:
  id: uart_bus
  baud_rate: 19200
  rx_pin: 18
  tx_pin: 17

one_wire:
  - platform: gpio
    pin: 4

uapbridge_esp:
  id: garage_door_comp
  uart_id: uart_bus
  auto_correction: true

cover:
  - platform: uapbridge
    id: cover01
    name: cover01
    device_class: garage

binary_sensor:
  - platform: uapbridge
    error_state:
      name: error_state
      entity_category: "diagnostic"
    got_valid_broadcast:
      name: connection_state
      entity_category: "diagnostic"

button:
  - platform: uapbridge
    impulse_button:
      id: button_impulse
      name: impulse
  - platform: restart
    name: restart

sensor:
  - platform: dallas_temp
    address: 0xb900000b55de6028
    name: temperature01
    update_interval: 120s
  - platform: dallas_temp
    address: 0xcc00000a4cdf3928
    name: temperature02
    update_interval: 120s
  - platform: wifi_signal
    name: signal
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    state_class: measurement
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: uptime
    name: uptime
    unit_of_measurement: "s"
    state_class: measurement
    device_class: duration
    update_interval: 60s
    entity_category: "diagnostic"

api:
  encryption:
    key: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

improv_serial:
```

### Anything in the logs that might be useful for us?

```txt

```
