### ISSUE TITLE
Remote package refresh does not seem to work when a non-existent file is referenced

### ISSUE THREAD

**Issue by DanielBaulig** [esphome/issues#7168]
### The problem

Steps to reproduce:

```
packages:
  package: 
    url: https://github.com/project/repository
    ref: main
    refresh: 0d
    file: missing_file.yaml
```

Context:
I was making changes to my remote package. I introduced a new yaml file and pushed the changes to the remote repository. I then changed the file attribute in my package configuration in ESPHome and tried to push the changes to my ESP32. But ESPHome complained that the file didn't exist. I looked at the local repository checkout and indeed, the file was missing. The remote repository hadn't been pulled. I changed the file back to an existing file and which then allowed the local package checkout to pull and update. At that point I was able to change the file back to the now existing file and build. 

It seems like the repository pull should probably occur before the validity of the file name is checked and/or not prevent the pull from happening.

### Which version of ESPHome has the issue?

2025.2.2

### What type of installation are you using?

Docker

### Component causing the issue

packages

### YAML Config

See above.
