### ISSUE TITLE
ESPHome 2025.6.1 breaks HA automations on Cree 5 Button Scene Controller (generic-bk7231n-qfn32-tuya based)

### ISSUE THREAD

**Issue by jeffd1845** [esphome/issues#7169]
### The problem

After updating my Cree 5-Button scene controller to ESPHome 2025.6.1 I can see ON, OFF, single, double, triple, and hold executions in the device log, but this is no longer triggering automations in HA.  A different Cree device with an identical YAML config, but still on ESPHome 2025.5.2 continues to trigger HA automations perfectly. 

### Which version of ESPHome has the issue?

2025.6.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### YAML Config

```yaml
esphome:
  name: "cree-5b"
  friendly_name: Office 5 Button Controller

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

web_server:

captive_portal:

mdns:

# Enable Home Assistant API
api:
  encryption:
    key: <removed>

ota:
  - platform: esphome
    password: <removed>

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret ap_password

button:
- platform: restart
  name: Restart

debug:
  update_interval: 30s

text_sensor:
- platform: debug
  reset_reason:
    name: Reset Reason
- platform: libretiny
  version:
    name: LibreTiny Version
- platform: template
  name: "State"
  id: template_text
- platform: template
  name: "Button 1"
  id: button1
  icon: "mdi:toggle-switch"
  on_value:
    then:
      - if:
          condition:
            text_sensor.state:
              id: button1
              state: "OFF"
          else:
            - delay: 20ms
            - text_sensor.template.publish:
                id: button1
                state: !lambda 'return "OFF";'
- platform: template
  name: "Button 2"
  id: button2
  icon: "mdi:toggle-switch"
  on_value:
    then:
      - if:
          condition:
            text_sensor.state:
              id: button2
              state: "OFF"
          else:
            - delay: 20ms
            - text_sensor.template.publish:
                id: button2
                state: !lambda 'return "OFF";'
- platform: template
  name: "Button 3"
  id: button3
  icon: "mdi:toggle-switch"
  on_value:
    then:
      - if:
          condition:
            text_sensor.state:
              id: button3
              state: "OFF"
          else:
            - delay: 20ms
            - text_sensor.template.publish:
                id: button3
                state: !lambda 'return "OFF";'
- platform: template
  name: "Button 4"
  id: button4
  icon: "mdi:toggle-switch"
  on_value:
    then:
      - if:
          condition:
            text_sensor.state:
              id: button4
              state: "OFF"
          else:
            - delay: 20ms
            - text_sensor.template.publish:
                id: button4
                state: !lambda 'return "OFF";'
- platform: template
  name: "Button 5"
  id: button5
  icon: "mdi:toggle-switch"
  on_value:
    then:
      - if:
          condition:
            text_sensor.state:
              id: button5
              state: "OFF"
          else:
            - delay: 20ms
            - text_sensor.template.publish:
                id: button5
                state: !lambda 'return "OFF";'

sensor:
- platform: uptime
  name: Uptime

status_led:
  pin: 
    number: P23
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: P20
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    name: "Button 1"
    id: rawbutton1
    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: button1
              state: !lambda 'return "single";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: button1
              state: !lambda 'return "double";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 50ms
        then:
          - text_sensor.template.publish:
              id: button1
              state: !lambda 'return "triple";'
      - timing:
          - ON for at least 2s
        then:
          - text_sensor.template.publish:
              id: button1
              state: !lambda 'return "hold";'
  - platform: gpio
    pin:
      number: P22
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    name: "Button 2"
    id: rawbutton2
    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: button2
              state: !lambda 'return "single";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: button2
              state: !lambda 'return "double";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 50ms
        then:
          - text_sensor.template.publish:
              id: button2
              state: !lambda 'return "triple";'
      - timing:
          - ON for at least 2s
        then:
          - text_sensor.template.publish:
              id: button2
              state: !lambda 'return "hold";'
  - platform: gpio
    pin:
      number: P28
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    name: "Button 3"
    id: rawbutton3
    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: button3
              state: !lambda 'return "single";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: button3
              state: !lambda 'return "double";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 50ms
        then:
          - text_sensor.template.publish:
              id: button3
              state: !lambda 'return "triple";'
      - timing:
          - ON for at least 2s
        then:
          - text_sensor.template.publish:
              id: button3
              state: !lambda 'return "hold";'
  - platform: gpio
    pin:
      number: P14
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    name: "Button 4"
    id: rawbutton4
    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: button4
              state: !lambda 'return "single";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: button4
              state: !lambda 'return "double";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 50ms
        then:
          - text_sensor.template.publish:
              id: button4
              state: !lambda 'return "triple";'
      - timing:
          - ON for at least 2s
        then:
          - text_sensor.template.publish:
              id: button4
              state: !lambda 'return "hold";'
  - platform: gpio
    pin:
      number: P15
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    name: "Button 5"
    id: rawbutton5
    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: button5
              state: !lambda 'return "single";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          - text_sensor.template.publish:
              id: button5
              state: !lambda 'return "double";'
      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 50ms
        then:
          - text_sensor.template.publish:
              id: button5
              state: !lambda 'return "triple";'
      - timing:
          - ON for at least 2s
        then:
          - text_sensor.template.publish:
              id: button5
              state: !lambda 'return "hold";'
```

### Anything in the logs that might be useful for us?

```txt

```
