### ISSUE TITLE
cover component appears in ESPHome Web Server UI but doesn't work correctly

### ISSUE THREAD

**Issue by behnam85** [esphome/issues#7172]
### The problem

I am using the cover component in ESPHome along with the built-in web_server:.
The cover entity does appear in the ESPHome Web UI (via browser), but it does not function properly:

The open, close, and stop buttons are visible, but pressing them has no effect.

The cover position and state are not updated.

Everything works fine in Home Assistant, so the configuration and hardware setup are correct.

### Which version of ESPHome has the issue?

2025.7.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.6.3

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

cover

### YAML Config

```yaml
cover:
  - platform: template
    name: "Right Cover"
    id: "top"
    
    open_action:
     
      - remote_transmitter.transmit_rc_switch_raw:

         code: '001011100000101010010100'
         protocol: 1
         repeat:
            times: 3
            wait_time: 25ms
    
      
    close_action:
   
      - remote_transmitter.transmit_rc_switch_raw:

         code: '001011100000101010010001'
         protocol: 1
         repeat:
            times: 3
            wait_time: 25ms
    
    stop_action:
   
      - remote_transmitter.transmit_rc_switch_raw:

         code: '001011100000101010010010'
         protocol: 1
         repeat:
            times: 3
            wait_time: 25ms
    
    assumed_state: True
    optimistic: False

  - platform: template
    name: "Left Cover"
    id:  my_cover_left
    internal: True
    open_action:
     
      - remote_transmitter.transmit_rc_switch_raw:

         code: '010011011101110000000011'
         protocol: 1
         repeat:
            times: 5
            wait_time: 25ms
    
      
    close_action:
   
      - remote_transmitter.transmit_rc_switch_raw:

         code: '010011011101110011000000'
         protocol: 1
         repeat:
            times: 5
            wait_time: 25ms
      - delay: 20s
      - remote_transmitter.transmit_rc_switch_raw:

         code: '010011011101110000110000'
         protocol: 1
         repeat:
            times: 5
            wait_time: 25ms
    
    stop_action:
   
      - remote_transmitter.transmit_rc_switch_raw:

         code: '010011011101110000110000'
         protocol: 1
         repeat:
            times: 5
            wait_time: 25ms
    
    assumed_state: True
    optimistic: False
```

### Anything in the logs that might be useful for us?

```txt

```
