### ISSUE TITLE
Problem with ESP8266

### ISSUE THREAD

**Issue by lakusz1github** [esphome/issues#7175]
### The problem

After last update (i gues) ESPHome during build firmware we see errors/worning :

Linking .pioenvs/esp-d1/firmware.elf
RAM:   [====      ]  42.1% (used 34448 bytes from 81920 bytes)
Flash: [=====     ]  48.7% (used 498357 bytes from 1023984 bytes)
Building .pioenvs/esp-d1/firmware.bin
/data/cache/platformio/packages/framework-arduinoespressif8266/tools/elf2bin.py:54: SyntaxWarning: invalid escape sequence '\s'
  words = re.split('\s+', line)
/data/cache/platformio/packages/framework-arduinoespressif8266/tools/elf2bin.py:73: SyntaxWarning: invalid escape sequence '\s'
  words = re.split('\s+', line)
esp8266_copy_factory_bin([".pioenvs/esp-d1/firmware.bin"], [".pioenvs/esp-d1/firmware.elf"])
esp8266_copy_ota_bin([".pioenvs/esp-d1/firmware.bin"], [".pioenvs/esp-d1/firmware.elf"])
======================== [SUCCESS] Took 503.17 seconds ========================

### Which version of ESPHome has the issue?

2025.5.2 and 2025.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2025.6.3

### What platform are you using?

ESP8266

### Board

D1 mini

### YAML Config

```yaml
esphome:
  name: esp-d1

esp8266:
  board: d1_mini_lite

# Enable logging
logger:
    level: INFO  #dodane

# Enable Home Assistant API
api:
  encryption:
    key: xxx

ota:
    platform: esphome
    password: xxx

wifi:
  ssid: xxx
  password: xxx

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Fallback"
    password: xxx

captive_portal:

sensor:
  - platform: adc
    pin: A0
    name: "czujnik"
    update_interval: 30s
```

### Anything in the logs that might be useful for us?

```txt

```
