### ISSUE TITLE
Sonoff Basic R1 does not connect to WiFi after upgrade from 2025.5.2 to 2024.6.2

### ISSUE THREAD

**Issue by erwinschoonhoven** [esphome/issues#7180]
### The problem

Sonoff Basic R1 does not come back on the WiFi after upgrade from 2025.5.2 to 2025.6.2. After (serial) flashing back to 2025.5.2 it's back on WiFi and operating as expected. When upgraded again it will no longer connect.

I had this issue before with the same type of devices (on all 3 i have) and the issue was resolved in a later version: https://github.com/esphome/issues/issues/5894

But now it's back again

### Which version of ESPHome has the issue?

> 2025.6.2

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

Sonoff BASIC R1

### Component causing the issue

wifi

### YAML Config

```yaml
esphome:
  name: testswitch
  friendly_name: Testswitch

esp8266:
  board: esp01_1m

logger:
  level: VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  output_power: 17db

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
```

### Anything in the logs that might be useful for us?

```txt
Cannot connect to device through wifi and i don't dare to connect to serial while the device is powered by the 220v. I just see a lot of connection attempts on the wifi where the device is registered and deregistered more than 50 times in a few minutes.
```
