### ISSUE TITLE
ESPHome not booting ESP32

### ISSUE THREAD

**Issue by SantiagoSotoC** [esphome/issues#719]
**Operating environment/Installation (Hass.io/Docker/pip/etc.): Docker ** 

**ESP (ESP32/ESP8266, Board/Sonoff): Esp32 **

**Affected component:**

-->

**Description of problem:**
ESPHome is not booting I get a restart after other

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
<!--
esphome:
  name: bridge
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "XXXXXX"
  password: "XXXXXX"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
```

**Logs (if applicable):**

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57
```

**Additional information and things you've tried:**

The board is working I flash it with a basic Arduino code and works !!
