### ISSUE TITLE
Adding expire_after variable to DHT22 sensor kills node

### ISSUE THREAD

**Issue by akasma74** [esphome/issues#72]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io v.0.88.0

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266, Wemos D1 mini

**Affected component:**
[DHT sensor](https://esphome.io/components/sensor/dht)

**Description of problem:**
If I uncomment `expire_after:` in the yaml and compile & upload it, it is no longer possible to get logs and the node becomes unavailable

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
- platform: dht
  pin: D4
  model: dht22
  temperature:
    name: "bathroom_shower_temperature"
#    expire_after: 65s

```

**Traceback (if applicable):**
```
INFO Connecting to 192.168.0.53:6053 (192.168.0.53)
WARNING Couldn't connect to API (Error connecting to 192.168.0.53: Connection refused). Trying to reconnect in 1 seconds
```

**Additional information and things you've tried:**
However, I'm still able to comment it back and compile & upload again, and it gets the node back online.
