### ISSUE TITLE
Automation Light Effect doesn't work

### ISSUE THREAD

**Issue by Fusseldieb** [esphome/issues#721]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Ubuntu Server 18 running Home Assistant and ESPHome in Docker

NodeMCU v3 4MB

**Affected component:**

https://esphome.io/components/light/index.html#automation-light-effect

**Description of problem:**
If I define a "automation light effect", it just doesn't work. The light stays still and doesn't do anything (Like it's set to Effect None). All other effects like Rainbow, Flicker, etc work just fine.

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: D5
    num_leds: 150
    rgb_order: BRG
    name: "Cozinha LED Teto"
    color_correct: [100%,100%,100%]
    id: cozinha_led_teto
    effects:
      - addressable_twinkle:
      - addressable_scan:
      - addressable_color_wipe:
      - addressable_rainbow:
      - flicker:
      - strobe:
      - random:
      - automation:
          name: Custom Automation Effect
          sequence:
            - light.addressable_set:
                id: cozinha_led_teto
                red: 100%
                green: 100%
                blue: 100%
            - delay: 100ms
            - light.addressable_set:
                id: cozinha_led_teto
                range_from: 0
                range_to: 20
                red: 100%
                green: 0%
                blue: 0%
```

**Logs (if applicable):**

```
[23:46:51][D][light:261]: 'Cozinha LED Teto' Setting:
[23:46:51][D][light:323]:   Effect: 'Custom Automation Effect'
[23:46:53][D][light:261]: 'Cozinha LED Teto' Setting:
[23:46:53][D][light:323]:   Effect: 'None'
```

**Additional information and things you've tried:**
The Lambda Effect apparently works.

EDIT: Yes, the Lambda Effect works.
