### ISSUE TITLE
cant connect.

### ISSUE THREAD

**Issue by FritsOV** [esphome/issues#7238]
For some days now 'm trying to connect to my esp12F. 
The case is:
an esp12F with esphome with an mpu6050 attached 
had a python part with kivy where first a connection is made to the ssid from the esp32  and after this succesful connection it tried to retrieve the available entities. it seems that kivy and aioesphome dont like eachother. Next step was just trying to get the example working as provided in github. i seem to do something wrong. is there a complete working sample with yaml to get a better understanding on how things work and get it working in my case? 

In my yaml file i have:
```
`api:
  id: my_api
  password: "0123456789"
  reboot_timeout: 24h  # Increase timeout to 24 hours
  services:  # Add heartbeat service
    - service: ping
      then:
        - lambda: |-
            // Empty lambda, just acknowledge the ping

 WiFi settings for better stability
wifi:
  ap: 
    ssid: "Leveler_Adria"
    password: "adria0548"
    ap_timeout: 0s
  power_save_mode: none  # Disable power saving for better stability
#  fast_connect: true  # Enable fast connect
  output_power: 20.0  # Maximum power for better signal

# Web server with increased timeout
web_server:
  port: 80
  local: true
  ota: false
  js_include: "./v2/www.js"
  js_url: ""  
  version: 2`

```

with the sample provided on github:
```
[ output: aioesphomeapi-logs rv-leveller.local  --port 6053 --password 0123456789 ] 
2025-05-03 11:28:37.446 INFO     Successfully connected to rv-leveller @ 192.168.4.1 in 0.004s
2025-05-03 11:28:37.465 WARNING  rv-leveller @ 192.168.4.1: Connection error occurred: [WinError 64] De opgegeven netwerknaam is niet langer beschikbaar (in English, networkname no longer available).
```
a snipet of the events are there:
```
id: 1237600
event: log
data: [0;38m[VV][scheduler:032]: set_timeout(name='', timeout=0)[0m

id: 1237613
event: log
data: [0;38m[VV][scheduler:225]: Running timeout '' with interval=0 last_execution=1237599 (now=1237612)[0m

id: 1237613
event: log
data: [0;37m[V][json:020]: Attempting to allocate 512 bytes for JSON serialization[0m

id: 1237614
event: log
data: [0;37m[V][json:040]: Size after shrink 100 bytes[0m

retry: 30000
id: 1237614
event: ping
data: {"title":"Gyroscope waterpas","comment":"","ota":false,"log":true,"lang":"en"}

id: 1237615
event: log
data: [0;37m[V][json:020]: Attempting to allocate 512 bytes for JSON serialization[0m

id: 1237616
event: log
data: [0;37m[V][json:040]: Size after shrink 72 bytes[0m

event: state
data: {"id":"sensor-y_angle","value":-2.376153,"state":"-2.4 Â°"}

id: 1237618
event: log
data: [0;38m[VV][scheduler:225]: Running interval 'update' with interval=200 last_execution=1237415 (now=1237617)[0m

id: 1237618
event: log
data: [0;37m[V][mpu6050:102]:     Updating MPU6050...[0m

id: 1237619
event: log
data: [0;38m[VV][i2c.arduino:176]: 0x68 TX 3B[0m

id: 1237624
event: log
data: [0;38m[VV][i2c.arduino:148]: 0x68 RX 0248F62CBC68EF90FFDFFFFDFFFE[0m

id: 1237625
event: log
data: [0;36m[D][mpu6050:120]: Got accel={x=0.349 m/sÂ², y=-1.505 m/sÂ², z=-10.351 m/sÂ²}, gyro={x=-2.012 Â°/s, y=-0.183 Â°/s, z=-0.122 Â°/s}, temp=24.154Â°C[0m

id: 1237626
event: log
data: [0;37m[V][sensor:043]: 'MPU6050 Accel X': Received new state 0.349352[0m
```
