### ISSUE TITLE
xtensa-lx106-elf-g++: internal compiler error: Segmentation fault (program cc1plus)

### ISSUE THREAD

**Issue by Wojcioo** [esphome/issues#724]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hassio installed in docker on RPI 3

**ESP (ESP32/ESP8266, Board/Sonoff):**
Sonoff Basic, Sonoff S-20, Sonoff 4CH

**Affected component:**
ESP have nothing attached 

**Description of problem:** 
Project fails to compile, appears to be downloading necessary library, it ends without uploading with error:
*** [/data/sonoff4ch/.pioenvs/sonoff4ch/src/esphome/components/api/util.cpp.o] Error 4
xtensa-lx106-elf-g++: internal compiler error: Segmentation fault (program cc1plus)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: sonoff4ch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "*****"
  password: "***********"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.85
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff 4CH Television"
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff 4CH Amplifier"
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff 4CH Xbox"
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff 4CH Subwoofer"
  - platform: status
    name: "Sonoff 4CH Status"

switch:
  - platform: gpio
    name: "Television"
    icon: "mdi:television-classic"
    pin: GPIO12
    restore_mode: always_on
  - platform: gpio
    name: "Amplifier"
    icon: "mdi:amplifier"
    pin: GPIO5
    restore_mode: always_on
  - platform: gpio
    name: "Xbox"
    icon: "mdi:xbox"
    pin: GPIO4
    restore_mode: always_on
  - platform: gpio
    name: "Subwoofer"
    icon: "mdi:speaker"
    pin: GPIO15
    restore_mode: always_on

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "Sonoff 4CH Blue LED"
    output: blue_led
```

**Logs (if applicable):**

```
INFO Reading configuration...
WARNING ESP8266: Pin 9 (6-11) might already be used by the flash interface. Be warned.
WARNING ESP8266: Pin 10 (6-11) might already be used by the flash interface. Be warned.
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/sonoff4ch
Processing sonoff4ch (framework: arduino; platform: espressif8266@1.8.0; board: esp01_1m)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz 80KB RAM (1MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 30 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP Async WebServer> 1.1.1
|   |-- <ESPAsyncTCP> 1.2.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.2.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.2.2
|   |-- <ESP8266WiFi> 1.0
Compiling /data/sonoff4ch/.pioenvs/sonoff4ch/src/esphome/components/api/user_services.cpp.o
Compiling /data/sonoff4ch/.pioenvs/sonoff4ch/src/esphome/components/api/util.cpp.o
Compiling /data/sonoff4ch/.pioenvs/sonoff4ch/src/esphome/components/binary_sensor/automation.cpp.o
Compiling /data/sonoff4ch/.pioenvs/sonoff4ch/src/esphome/components/binary_sensor/binary_sensor.cpp.o
xtensa-lx106-elf-g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
*** [/data/sonoff4ch/.pioenvs/sonoff4ch/src/esphome/components/api/util.cpp.o] Error 4
xtensa-lx106-elf-g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
*** [/data/sonoff4ch/.pioenvs/sonoff4ch/src/esphome/components/binary_sensor/automation.cpp.o] Error 4
========================== [ERROR] Took 8.94 seconds ==========================

```

**Additional information and things you've tried:**
