### ISSUE TITLE
TinyPICO listed on Espressif, not supported in ESPHome

### ISSUE THREAD

**Issue by djraidar** [esphome/issues#731]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
TinyPICO ESP32

**Affected component:**
ESP32 Integration

**Description of problem:**
http://docs.platformio.org/en/latest/boards/espressif32/tinypico.html#board-espressif32-tinypico

**Problem-relevant YAML-configuration entries:**

```
esphome:
  name: camera
  platform: ESP32
  board: tinypico
```

**Additional information and things you've tried:**
generic esp32 doe not work at all
