### ISSUE TITLE
Help needed: Set brightness of individual led in a light effect automation

### ISSUE THREAD

**Issue by marrobHD** [esphome/issues#732]
How can I set the brightness of LED 2 to 50% in this automation?
Thx for help
```
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D2
    num_leds: 3
    rgb_order: GRB
    name: "Skull Eys"
    id: "skulleys"
    effects:
      - automation:
          name: Eys flicker
          sequence:
          - light.addressable_set:
              id: skulleys
              range_from: 2
              range_to: 2
              red: 100%
              green: 100%
              blue: 100%
          - logger.log: "Eys flicker automation is running"
          - light.addressable_set:
              id: skulleys
              range_from: 0
              range_to: 1
              red: 100%
              green: 0%
              blue: 0%
          - delay: 0.05s
          - light.addressable_set:
              id: skulleys
              range_from: 0
              range_to: 1
              red: 0%
              green: 0%
              blue: 0%
```
