### ISSUE TITLE
Help needed: Set brightness of individual led in a light effect automation

### ISSUE THREAD

**Issue by marrobHD** [esphome/issues#733]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 D1 Mini V3
**Affected component:**

https://esphome.io/components/light/index.html

**Description of problem:**
How can I set the brightness of LED 2 to 50% in this automation?
Or add a brightness option to light.addressable_set. That would be the best option it think.
I have the Dev version installed on Hassio

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D2
    num_leds: 3
    rgb_order: GRB
    name: "Skull Eys"
    id: "skulleys"
    effects:
      - automation:
          name: Eys flicker
          sequence:
          - light.addressable_set:
              id: skulleys
              range_from: 2
              range_to: 2
              red: 100%
              green: 100%
              blue: 100%
          - logger.log: "Eys flicker automation is running"
          - light.addressable_set:
              id: skulleys
              range_from: 0
              range_to: 1
              red: 100%
              green: 0%
              blue: 0%
          - delay: 0.05s
          - light.addressable_set:
              id: skulleys
              range_from: 0
              range_to: 1
              red: 0%
              green: 0%
              blue: 0%

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
```yaml
- light.addressable_set:
    id: skulleys
    range_from: 2
    range_to: 2
    red: 50%
    green: 50%
    blue: 50%
```
