### ISSUE TITLE
effect: strobe overrides all other properties

### ISSUE THREAD

**Issue by Joshfindit** [esphome/issues#737]
When using the Strobe effect it only flashes white at full brightness, regardless of other properties.

```bash
curl -X POST -H "Authorization: Bearer eyJ0e" \
       -H "Content-Type: application/json" \
       -d '{"entity_id": "light.d1_mini_v3_with_apa102s_lamp_1", "effect": "strobe", "brightness": "128", "rgb_color": [255, 10, 10]}' \
       http://localhost:8123/api/services/light/turn_on
```

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io in a VM, ESPHome dev

**ESP (ESP32/ESP8266, Board/Sonoff):**

D1 mini

**Affected component:**

https://esphome.io/components/light/index.html#strobe-effect

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: fastled_spi
    chipset: APA102
    data_pin: $data_pin
    clock_pin: $clock_pin
    num_leds: 1
    rgb_order: BGR
    name: $upper_devicename
    id: fastled_light
    default_transition_length: 10ms
    effects:
      - strobe:
      - addressable_color_wipe:
      - addressable_rainbow:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_flicker:
      - addressable_flicker:
          name: Flicker Effect With Custom Values
          update_interval: 16ms
          intensity: 10%

```

**Logs (if applicable):**

```
[11:35:06][D][light:261]: 'D1 Mini v3 with APA102s Lamp 1' Setting:
[11:35:06][D][light:274]:   Brightness: 50%
[11:35:06][D][light:283]:   Red=100%, Green=4%, Blue=4%
[11:35:06][D][light:323]:   Effect: 'Strobe'
```

**Additional information and things you've tried:**
