### ISSUE TITLE
Platformio Options lib_deps override default lib_deps

### ISSUE THREAD

**Issue by alexyao2015** [esphome/issues#743]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP01
**Affected component:**

Platformio_options

**Description of problem:**
When lib_deps is added to a config that has a clean build, it overrides the default lib_deps, causing the code to not compile. 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
  platformio_options:
    lib_deps: ESPAsyncUDP@697c75a025
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Should add lib_deps from the yaml to the default lib_deps instead of overriding. It does work if you first compile without the lib_deps in the yaml and add it once the build has compiled.
