### ISSUE TITLE
Support for automations, switch and push button

### ISSUE THREAD

**Issue by xefil** [esphome/issues#747]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Installation via Docker on Synology NAS, usage with Home Assistant

**ESP (ESP8266, Board/Sonoff):**

ESP8266 Board V2 Nodemcu-CP2102
**Affected component:**

NOPE

Description of problem:

Hi to all!
I'm searching help for understanding where I'm doing something wrong.
I've setup my ESP8266 with some sensors (they work well) and one relay switch, one button and two leds. My prupose is to have a device to control the relay with the button, but the same way to control it via Home Assistant. As soon the button is pressed, the green led shout turned on, and the relay should turned on. When I press again the same button (so it's a push button), the led green should turn off, the red led should turn on and the relay off. The relay status should always sent to Home Assistant. The same way, I should be able to control the relay from Home Assistant. So, turning the switch on via HA, the leds should change as above.
Here is part of my conf. I'm pretty sure an issue is the button. I've a push button (pressing it, turns on, but it gets off as soon I release the button), but have no idea what else is wrong.
After that, I'll try to automate some actions based on temperatures, but it comes later on :-)
The relay gets on on the first push and if I try to turn it off via HA, nothing changes.
What I'm doing wrong?

**Problem-relevant YAML-configuration entries:**
```yaml
binary_sensor:
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
    name: "Button"
    on_press:
      then:
        - switch.toggle:
            id: bagno_relay

switch:
  - platform: gpio
    pin:
      number: D1
      inverted: yes
    id: bagno_relay_pin
    restore_mode: ALWAYS_OFF
  - platform: template
    name: "Relay Switch"
    icon: "mdi:fire"
    id: bagno_relay
    turn_on_action:
      - light.turn_on:
          id: led_green
      - light.turn_off:
          id: led_red
      - switch.turn_on:
          id: bagno_relay_pin
    turn_off_action:
      - light.turn_off:
          id: led_green
      - light.turn_on:
          id: led_red
      - switch.turn_off: 
          id: bagno_relay_pin

output:
  - platform: esp8266_pwm
    id: onboard_led_green
    pin:
      number: D3
  - platform: esp8266_pwm
    id: onboard_led_red
    pin:
      number: D4

light:
  - platform: monochromatic
    name: "Onboard LED Green"
    output: onboard_led_green
    id: led_green
  - platform: monochromatic
    name: "Onboard LED Red"
    output: onboard_led_red
    id: led_red

```

**Logs (if applicable):**

```
NOPE
```

**Additional information and things you've tried:**

Thanks for the support!!

Simon

**Comment by xefil** [comment]
Hi all, I would like to update the case with the solution found by myself. I'm sharing what was wrong hoping that could help someone other. I hope what follow is correct, btw it works :)
First of all, the template switch doesn't send the state to HA, so I need to force it and set it in optimistic mode. Then, I've changed the binary_sensor action from on_press to on_click. Seems it's better for those buttons. the result as follow:

```yaml
binary_sensor:
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
      inverted: yes
    name: "Button"
    on_click:
      then:
        - switch.toggle:
            id: bagno_relay

switch:
  - platform: gpio
    pin:
      number: D1
      inverted: yes
    id: bagno_relay_pin
    restore_mode: ALWAYS_OFF
  - platform: template
    name: "Bagno Relay"
    icon: "mdi:fire"
    id: bagno_relay
    optimistic: true
    lambda: 'return id(bagno_relay).state;'
    turn_on_action:
      - light.turn_on:
          id: led_green
      - light.turn_off:
          id: led_red
      - switch.turn_on:
          id: bagno_relay_pin
    turn_off_action:
      - light.turn_off:
          id: led_green
      - light.turn_on:
          id: led_red
      - switch.turn_off: 
          id: bagno_relay_pin

output:
  - platform: esp8266_pwm
    id: onboard_led_green
    pin:
      number: D3
  - platform: esp8266_pwm
    id: onboard_led_red
    pin:
      number: D4

light:
  - platform: monochromatic
    name: "Onboard LED Verde"
    output: onboard_led_green
    id: led_green
  - platform: monochromatic
    name: "Onboard LED Rosso"
    output: onboard_led_red
    id: led_red
```

Now it works from HA and from the button as expected.

I wish you all a nice week end.
Happy programming ;-)

Simon
