### ISSUE TITLE
fatal error: AsyncMqttClient.h: No such file or directory

### ISSUE THREAD

**Issue by dominicmcglinn** [esphome/issues#75]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
'.
-->
Hassio
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**Affected component:**

OTA upload 

**Description of problem:**
Compiling .pioenvs/loungeroom/lib7b3/AsyncTCP_ID1826/AsyncTCP.cpp.o
In file included from .piolibdeps/esphome-core/src/esphome/mqtt/mqtt_component.h:9:0,
from .piolibdeps/esphome-core/src/esphome/binary_sensor/mqtt_binary_sensor_component.h:9,
from .piolibdeps/esphome-core/src/esphome/binary_sensor/binary_sensor.h:262,
from .piolibdeps/esphome-core/src/esphome/controller.h:4,
from .piolibdeps/esphome-core/src/esphome/api/api_server.h:9,
from .piolibdeps/esphome-core/src/esphome/application.h:6,
from .piolibdeps/esphome-core/src/esphomelib/application.h:3,
from src/main.cpp:3:
.piolibdeps/esphome-core/src/esphome/mqtt/mqtt_client_component.h:12:29: fatal error: AsyncMqttClient.h: No such file or directory

*************************************************************************
* Looking for AsyncMqttClient.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:AsyncMqttClient.h"
* Web  > https://platformio.org/lib/search?query=header:AsyncMqttClient.h
*
*************************************************************************

compilation terminated.
Compiling .pioenvs/loungeroom/liba6f/WiFi/ETH.cpp.o
*** [.pioenvs/loungeroom/src/main.cpp.o] Error 1
========================== [ERROR] Took 27.47 seconds ==========================

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: loungeroom
  platform: ESP32
  board: esp32dev
  esphomelib_version: dev
  arduino_version: dev
  
wifi:
  ssid: ''
  password: ''
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 10.0.1.106
    # Set this to the IP address of the router. Often ends with .1
    gateway: 10.0.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  power_save_mode: light
  fast_connect: on
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ''

ota:
  password: ''

mqtt:
  broker: '10.0.1.44'
  username: 'Admin'
  password: ''

sensor:
  - platform: wifi_signal
    name: "loungeroom WiFi Signal Sensor"
    update_interval: 60s
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO27
    num_leds: 150
    rgb_order: GRB
    name: "KidsRoom Light"
    effects:
      - random:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:


```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
