### ISSUE TITLE
PCF8574 initilization toggles output at boot (if inversed logic)

### ISSUE THREAD

**Issue by swifty99** [esphome/issues#755]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

not relevant
**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemes D1, probably not relevant
**Affected component:**

PCF8574Component

**Description of problem:**
As the PCF8574 has limited capabilities relays may only be used which are low active. At least in other setups this successfully prevents unexpected activation in uncertain conditions.  If low active relays are used logic needs to be inverted. With esphome all inverse configured relays become active for 5ms after boot. Thy become active sequentially with a 23ms delay.

For me it looks like the PCF8574 setup function may write initialization values which are not yet inverted.

I will try some workarounds when I get the development environment running. 

**Problem-relevant YAML-configuration entries:**
```yaml

i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a
  
  
pcf8574:
  - id: 'pcf8574_hub'
    address: 0x38

# Individual outputs
switch:
  - platform: gpio
    name: "relais_standby"
    pin:
      pcf8574: pcf8574_hub
      number: 2
      mode: OUTPUT
      inverted: True
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

At least I know it can be avoided, I wrote a driver for this thing for other environments. Might help out.
