### ISSUE TITLE
Undefined reference to `app_entry_custom()'

### ISSUE THREAD

**Issue by TheZoker** [esphome/issues#756]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):** Sonoff S20

**Affected component:**

**Description of problem:**

When I try to compile, I get the issue below

**Problem-relevant YAML-configuration entries:** (output of validate)
```yaml
substitutions:
  id: ecklampe
  name: Ecklampe
  relay_pin: '12'
  button_pin: '0'
  status_led_pin: '13'
  led_pin: '13'
  icon: mdi:lightbulb
esphome:
  name: ecklampe
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  build_path: ecklampe
  includes: []
  esp8266_restore_from_flash: false
  arduino_version: espressif8266@2.2.3
  platformio_options: {}
  libraries: []
wifi:
  fast_connect: false
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  networks:
  - ssid: !secret 'wifi_ssid'
    password: !secret 'wifi_password'
    priority: 0.0
  use_address: ecklampe.local
logger:
  esp8266_store_log_strings_in_flash: true
  tx_buffer_size: 512
  level: DEBUG
  hardware_uart: UART0
  baud_rate: 115200
  logs: {}
api:
  password: !secret 'api_password'
  port: 6053
  reboot_timeout: 15min
ota:
  password: !secret 'api_password'
  safe_mode: true
  port: 8266
web_server:
  port: 80
  css_url: https://esphome.io/_static/webserver-v1.min.css
  js_url: https://esphome.io/_static/webserver-v1.min.js
switch:
- platform: gpio
  pin:
    number: 12
    mode: OUTPUT
    inverted: false
  id: relay
  interlock_wait_time: 0ms
  restore_mode: RESTORE_DEFAULT_OFF
  name: relay
  internal: true
- platform: template
  name: Ecklampe
  icon: mdi:lightbulb
  id: fakeswitch
  turn_on_action:
    then:
    - switch.turn_on:
        id: relay
    - light.turn_on:
        id: ecklampe_light
        state: true
  turn_off_action:
    then:
    - switch.turn_off:
        id: relay
    - light.turn_off:
        id: ecklampe_light
        state: false
  lambda: !lambda |-
    if(id(relay).state) {
      return true;
    }
    return false;
  assumed_state: false
  restore_state: false
  optimistic: false
binary_sensor:
- platform: gpio
  pin:
    number: 0
    mode: INPUT_PULLUP
    inverted: true
  name: Ecklampe Button
  on_press:
  - then:
    - switch.toggle:
        id: fakeswitch
- platform: status
  name: Ecklampe Status
  device_class: connectivity
output:
- platform: esp8266_pwm
  id: ecklampe_led
  pin:
    number: 13
    inverted: true
    mode: OUTPUT
  frequency: 1000.0
light:
- platform: monochromatic
  id: ecklampe_light
  output: ecklampe_led
  gamma_correct: 2.8
  restore_mode: RESTORE_DEFAULT_OFF
  default_transition_length: 1s
  name: ecklampe_light
  internal: true
status_led:
  pin:
    number: 13
    inverted: true
    mode: OUTPUT

```

**Logs (if applicable):**

```
Linking /data/ecklampe/.pioenvs/ecklampe/firmware.elf
/data/ecklampe/.pioenvs/ecklampe/libFrameworkArduino.a(core_esp8266_main.cpp.o):(.iram.text./root/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/core_esp8266_main.cpp.245.5+0x0): undefined reference to `app_entry_custom()'
/data/ecklampe/.pioenvs/ecklampe/libFrameworkArduino.a(core_esp8266_main.cpp.o): In function `app_entry':
core_esp8266_main.cpp:(.iram.text./root/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/core_esp8266_main.cpp.245.5+0xa): undefined reference to `app_entry_custom()'
collect2: error: ld returned 1 exit status
*** [/data/ecklampe/.pioenvs/ecklampe/firmware.elf] Error 1
```

**Additional information and things you've tried:**

![Screenshot_2019 10 21_00h08m14s_001_](https://user-images.githubusercontent.com/1368405/67168229-61a58600-f3a2-11e9-9a7d-e5b95f0a97e5.png)
