### ISSUE TITLE
ESP32 board does not boot with latest dev branch

### ISSUE THREAD

**Issue by Lumpusz** [esphome/issues#761]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

git clone of dev branch
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**Affected component:**

compiled binary

**Description of problem:**
After uploading the binary with ESPHome-Flasher-1.1.0-windows-x64.exe, board does not boot.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test_sensor
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "xx"
  password: "yy"


esp32_ble_tracker:
  scan_interval: 10s

sensor:
  - platform: ble_rssi
    mac_address: AC:37:43:77:5F:4C
    name: "Test MAC"

api:

ota:

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:952
load:0x40078000,len:6084
load:0x40080000,len:7944
entry 0x40080310

```

**Additional information and things you've tried:**

mkdir tmp
cd tmp
git clone https://github.com/esphome/esphome
cp ../test_sensor.yaml .
pip install ./esphome
python -m esphome test_sensor.yaml compile
upload using serial flasher

I tried removing the BT parts, and just have wifi, but I got the same error
