### ISSUE TITLE
Configuration error with duplicate sections

### ISSUE THREAD

**Issue by micronen** [esphome/issues#762]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESP8266 

**Affected component:**

Sensors, Switches, probably all of them

**Description of problem:**
When defining multiple sections for the same component type (eg. sensor)
in different files and using !include directive, only the last section is processed.

**Problem-relevant YAML-configuration entries:**
file1.yaml:
```yaml
esphome:
  name: test
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

# Example configuration entry
wifi:
  ssid: MyHomeNetwork
  password: VerySafePassword

  # Optional manual IP
  manual_ip:
    static_ip: 10.0.0.42
    gateway: 10.0.0.1
    subnet: 255.255.255.0
    
api:

ota:

# Example configuration entry
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
```
file2.yaml:
```yaml
sensor:  
  - platform: template
    name: Button1 Click
    id: button1_click
```
Main Configuration:
```yaml
<<: !include file1.yaml
<<: !include file2.yaml
```

**Logs (if applicable):**

Build Log1
```
INFO Reading configuration...
INFO Configuration is valid!
esphome:
  name: test
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true
  build_path: test
  platformio_options: {}
  arduino_version: espressif8266@1.8.0
  includes: []
  libraries: []
  board_flash_mode: dout
wifi:
  manual_ip:
    static_ip: 10.0.0.42
    gateway: 10.0.0.1
    subnet: 255.255.255.0
    dns2: 0.0.0.0
    dns1: 0.0.0.0
  fast_connect: false
  domain: .local
  power_save_mode: NONE
  reboot_timeout: 5min
  networks:
  - password: VerySafePassword
    ssid: MyHomeNetwork
  use_address: 10.0.0.42
api:
  reboot_timeout: 5min
  password: ''
  port: 6053
ota:
  password: ''
  safe_mode: true
  port: 8266
sensor:
- platform: adc
  pin: 17
  name: Living Room Brightness
  update_interval: 60s
  unit_of_measurement: V
  icon: mdi:flash
  accuracy_decimals: 2
  ```

**Additional information and things you've tried:**
Remove file2 from Main Configuration:
```yaml
<<: !include file1.yaml
# <<: !include file2.yaml
```

Build log2
```
INFO Reading configuration...
INFO Configuration is valid!
esphome:
  name: test
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true
  build_path: test
  platformio_options: {}
  arduino_version: espressif8266@1.8.0
  includes: []
  libraries: []
  board_flash_mode: dout
wifi:
  manual_ip:
    static_ip: 10.0.0.42
    gateway: 10.0.0.1
    subnet: 255.255.255.0
    dns2: 0.0.0.0
    dns1: 0.0.0.0
  fast_connect: false
  domain: .local
  power_save_mode: NONE
  reboot_timeout: 5min
  networks:
  - password: VerySafePassword
    ssid: MyHomeNetwork
  use_address: 10.0.0.42
api:
  reboot_timeout: 5min
  password: ''
  port: 6053
ota:
  password: ''
  safe_mode: true
  port: 8266
sensor:
- platform: wifi_signal
  name: WiFi Signal Sensor
  update_interval: 60s
  unit_of_measurement: dB
  icon: mdi:wifi
  accuracy_decimals: 0
```

Note the difference in **sensor** section
