### ISSUE TITLE
ESPHome with Sonoff Basic problem

### ISSUE THREAD

**Issue by onlize** [esphome/issues#764]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 Sonoff Basic

**Affected component:**
ESP8266 Sonoff Basic

https://esphome.io/devices/sonoff_basic.html

**Description of problem:**
I had Sonoff Basic running Tasmota, and I decided to update it to ESPHome.  I configured it like it is recommended here: https://esphome.io/devices/sonoff_basic.html

I configured ESPHome firmware and uploaded to the device. First, I tried to upload it using Tasmota Web Interface, but my device did not connect and did not pick up IP address.

I double checked and my WiFi information was correct, so I decided to use FlashESP8266.exe. I used it multiple times before and I uploaded ESPHome file successfully, but I still have the same problem.

If I flush Tasmota firmware back, everything works, so it is something with the bin file that was created by ESPHome web portal. The validation says that file is good. How can I troubleshoot and fix it? 

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: sonoff_basic_1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "my_ssid"
  password: "my_password"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "AlarmDecoder Sonoff Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "AlarmDecoder Sonoff Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
Reading other posts there was something about logger, but I do not see how I can read logs if I cannot connect to this device.
```

**Additional information and things you've tried:**
