### ISSUE TITLE
Displaying current time leads to disconnects

### ISSUE THREAD

**Issue by 7h30n3** [esphome/issues#768]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows 10
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (NodeMCUv2)

**Affected component:**

https://esphome.io/components/time.html
https://esphome.io/components/display/index.html

**Description of problem:**

The ESP8266 randomly disconnects from home assistant, the `wifi_strength` component shows a RSSI of 31dB and the `htu21d` sensor shows NaN or unavailable. All other ESPHome clients I have (without display) don't show this behavior.
First I thought it got something to do with `power_save_mode`, then the `time`-component, but it turns out it's the following part:

```
      - id: page3
        lambda: |-
          it.strftime(2, 5, id(logisoso_26), "%H:%M:%S", id(time_hass).now());
          it.line(0, 46, 127, 46);
          it.strftime(27, 48, id(arial_14), "%d.%m.%Y", id(time_hass).now());
```

![grafik](https://user-images.githubusercontent.com/18004390/67437759-ec2ff480-f5f1-11e9-908c-dc3e32b40c12.png)

As you can see in the image if I comment out this part everything is fine and I got the RSSI highlighted in yellow. With the part I got many disconnects and a RSSI auf 31dB.

I use Version: **1.14.0b2**, but it didn't work with 1.13.6 either.

**Problem-relevant YAML-configuration entries:**
```
esphome:
  name: sh1106_si7021
  platform: ESP8266
  board: nodemcuv2

api:

wifi:
  ssid: 'wirelessnetwork'
  password: 'secret'
  power_save_mode: high

# Enable logging
logger:
  level: verbose
  
i2c:

ota:

spi:
  clk_pin: 14
  mosi_pin: 13

sensor:
  - platform: wifi_signal
    name: "SH1106 Si7021 - RSSI"
    filters:
        - delta: 2.0
    
  - platform: htu21d
    temperature:
      filters:
        - delta: 0.4
        - offset: -5.2
      name: "SH1106 Si7021 - Temperature"
      unit_of_measurement: "°C"
      id: temperature
    humidity:
      filters:
        - delta: 1.2
        - offset: 4.0
      name: "SH1106 Si7021 - Humidity"
      accuracy_decimals: 1
      unit_of_measurement: "%"
      id: humidity
    update_interval: 60s
    
time:
  - platform: homeassistant
    id: time_hass

font:
  - file: "sh1106_si7021_dependencies/arial.ttf"
    id: arial_14
    size: 14
    glyphs:
    - "]"
    - "["
    - T
    - e
    - m
    - p 
    - r
    - a
    - t
    - u
    - L
    - f
    - c
    - h
    - "."
    - ":"
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 0
    - " "
    - "°"
    - C
    - "%"
    
    
     
  - file: "sh1106_si7021_dependencies/Logisoso.ttf"
    id: logisoso_42
    size: 62
    
  - file: "sh1106_si7021_dependencies/Logisoso.ttf"
    id: logisoso_26
    size: 39

display:
  - platform: ssd1306_spi
    model: "SH1106 128x64"
    brightness: 60%
    cs_pin: 15
    dc_pin: 0
    reset_pin: 2
    id: my_display
    pages:
      - id: page1
        lambda: |-
          it.printf(15, 23, id(logisoso_42), "%.1f", id(temperature).state);
          it.line(0, 46, 127, 46);
          it.print(13, 48, id(arial_14), "Temperatur [°C]");
      - id: page2
        lambda: |-
          it.printf(15, 23, id(logisoso_42), "%.1f", id(humidity).state);
          it.line(0, 46, 127, 46);
          it.print(16, 48, id(arial_14), "Luftfeuchte [%]");
      - id: page3
        lambda: |-
          it.strftime(2, 5, id(logisoso_26), "%H:%M:%S", id(time_hass).now());
          it.line(0, 46, 127, 46);
          it.strftime(27, 48, id(arial_14), "%d.%m.%Y", id(time_hass).now());

interval:
  - interval: 3s
    then:
      - display.page.show_next: my_display
      - component.update: my_display
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
