### ISSUE TITLE
witty cloud with LDR and RGB

### ISSUE THREAD

**Issue by lpt2007** [esphome/issues#769]
Hi,

I try to use witty cloud LDR and RGB.

![160422_witty_cloud_01-1-768x595](https://user-images.githubusercontent.com/38924279/67487386-1cb57400-f66e-11e9-91cf-e63f23d70760.jpg)

```
sensor:
  - platform: adc
    pin: A0
    name: Illuminance
    unit_of_measurement: lux
    filters:
      - lambda: (x * 3.3 / 10000.0) * 2000000.0
```
