### ISSUE TITLE
The addressable_light not work ok in the new esphome

### ISSUE THREAD

**Issue by zhujisheng** [esphome/issues#77]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**
The config works ok under esphomeyaml.
But when I use esphome1.11.0, the addressable_rainbow effect works, but strobe doesn't work, and the light can't be turn on&off.

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO3
    num_leds: 30
    name: "leds trip"
    effects:
      - strobe:
      - addressable_rainbow:

```
