### ISSUE TITLE
WARNING Disconnected from API: Timeout while waiting for message response!

### ISSUE THREAD

**Issue by KarlosHit** [esphome/issues#771]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant / Raspberry Pi 3 b+ / Raspbian + pip

**ESP (ESP32/ESP8266, Board/Sonoff):**

I am using an ESP32 with two relays and some sensors and an ESP01 with one relay

**Affected component:**

https://esphome.io/cookbook/relay.html?highlight=relay

**Description of problem:**
I have 2 relays controlled with an ESP32 and a relay controlled with an ESP01.
Constantly, the three relays are disconnected from the HA API, giving a message of: "changed to unavailable", and immediately afterwards they are reconnected. It happens randomly, but constantly.

I thought it would be a disconnection from the API of HA, or from MQTT, so I did a "show logs" in ESPHome, and found that it gives many flaws of: "WARNING Disconnected from API: Timeout while waiting for message response!".

However, I have been able to verify that when I have "show logs" open in ESPHome, the disconnection in HA stops, even though in "show logs" it still occasionally reports the error "WARNING Disconnected from API: Timeout while waiting for message response! " and in Home Assistant the message "changed to unavaiable" does not appear, but the relays go off without any order. The message is: "RelayX turned off".

**Problem-relevant YAML-configuration entries:**
```yaml
# Definición de variables:
substitutions:
  _ssid: '****'
  _passwifi: '****'
  _passota: '****'
  _usermosquitto: '*****'
  _passmosquitto: '****'

esphome:
  name: sensordht11
  platform: ESP32
#  board: esp-wrover-kit
#  board: nodemcu-32s
  board: esp32doit-devkit-v1

wifi:
  ssid: $_ssid
  password: $_passwifi
  manual_ip:
    static_ip: 192.168.xx.xx
    gateway: 192.168.xx.xx
    subnet: 255.255.255.0
  
i2c:
  sda: 21
  scl: 22
  scan: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: $_passota

ota:
  password: $_passota

web_server:
  port: 80

mqtt:
  broker: 192.168.31.xx
  username: $_usermosquitto
  password: $_passmosquitto

sensor:
  - platform: dht
    pin: 
      number: GPIO4
    model: DHT22
    temperature:
      name: "Temperatura DHT22"
    humidity:
      name: "Humedad Relativa DHT22"
    update_interval: 60s
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 60s
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
    name: "PIR Sensor"
    device_class: motion
    
switch:
  - platform: gpio
    pin: GPIO26
    name: "Relé 3"
    inverted: yes
  - platform: gpio
    pin: GPIO25
    name: "Relé 2"
    inverted: yes
```

**Logs (if applicable):**

```
```
![Registro HA](https://user-images.githubusercontent.com/48394829/67603834-4a87df00-f77a-11e9-911a-ebf86e6b8e04.jpg)

![Show logs](https://user-images.githubusercontent.com/48394829/67603836-4e1b6600-f77a-11e9-886b-f6988ee012a8.jpg)

**Additional information and things you've tried:**
