### ISSUE TITLE
LEDs flickering with ESP8266

### ISSUE THREAD

**Issue by pjmsullivan** [esphome/issues#776]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Linux 4.19.80-v7+ #1274 SMP Mon Oct 21 16:23:10 BST 2019 armv7l GNU/Linux
Raspberry pi 3
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 with 50 WS2812b LEDs on pin D1

**Affected component:**

https://esphome.io/components/light/fastled.html

**Description of problem:**
First @OttoWinter thank you so much for your work - this is fantastic.  I saw the previous issue you closed concerning ESP8266 hardware limitations results in flickering LEDs.  Previously, using an arduino sketch, effects were buttery smooth, but now they flicker with the same hardware with ESPHome.  Prior to switching to ESPHome, I resolved this issue with the inclusion of:
`#define FASTLED_ALLOW_INTERRUPTS 0`
located above `#include "FastLED.h"` (See https://github.com/FastLED/FastLED/wiki/Interrupt-problems).  
I did experiment with `max_refresh_rate` already.  Is there any way to add `FASTLED_ALLOW_INTERRUPTS 0` to eliminate the flickering?  
FYI - sorry if this is an obvious answer - I am not a pro.
Thanks again!

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO5
    num_leds: 50
    rgb_order: RGB
    max_refresh_rate: 25ms
    name: "Kitchen LED Lights"
    effects:
      - random:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:


```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
