### ISSUE TITLE
LEDs flickering with ESP32

### ISSUE THREAD

**Issue by MartinBrazdil** [esphome/issues#782]
Thank you for this wonderful software, really appreciate it. I am beginner in home automation with big plans ahead :)

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassbian on Raspberry Pi 4 model B
system info:
  Distro......: Raspbian GNU/Linux 10 (buster)
  Kernel......: Linux 4.19.50-v7l+

  Uptime......: up 1 week, 1 day, 21 hours, 16 minutes
  Load........: 0.02 (1m), 0.01 (5m), 0.00 (15m)
  Processes...: 108 (root), 10 (user) | 118 (total)

  CPU.........: ARMv7 Processor rev 3 (v7l)
  Memory......: 178Mi used, 2.1Gi free, 3.8Gi in total

services:
  home-assistant@homeassistant:  active

_ESPHome v1.15.0-dev_

Compiling with:
_espressif32@1.11.0_

**ESP (ESP32/ESP8266, Board/Sonoff):**

Espressif ESP32 devkit

**Affected component:**

I think problem is in somehow related to ledc output platform.

**Description of problem:**
PWM does not seem to work in 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
output:
  - platform: ledc
    pin: 16
    frequency: 1000 Hz
    id: LED_gpio_16
  - platform: ledc
    pin: 17
    frequency: 1000 Hz
    id: LED_gpio_17
  - platform: ledc
    pin: 5
    frequency: 1000 Hz
    id: LED_gpio_5
  - platform: ledc
    pin: 19
    frequency: 1000 Hz
    id: LED_gpio_19
light:
  - platform: cwww
    name: "Q1_CCT_1"
    cold_white: LED_gpio_16
    warm_white: LED_gpio_17
    cold_white_color_temperature: 4000 K
    warm_white_color_temperature: 1800 K
    default_transition_length: 2s
  - platform: cwww
    name: "Q1_CCT_2"
    cold_white: LED_gpio_5
    warm_white: LED_gpio_19
    cold_white_color_temperature: 4000 K
    warm_white_color_temperature: 1800 K
    default_transition_length: 2s
```

**Logs (if applicable):**
I dont have debug log because I have solved my issue by older ESPHome version, but there was a difference, namely, logs from 1.15.0dev show 1000.0Hz but it is not applied and also CHANNEL is missing. It was something like:

```
1.15.0dev
[21:10:47][C][output.ledc:032]: LEDC Output:
[21:10:47][C][output.ledc:033]:   Pin: 16
[21:10:47][C][output.ledc:035]:   Frequency: 1000.0 Hz

1.12.2
[21:10:47][C][output.ledc:032]: LEDC Output:
[21:10:47][C][output.ledc:033]:   Pin: 16
[21:10:47][C][output.ledc:034]:   LEDC Channel: 1
[21:10:47][C][output.ledc:035]:   Frequency: 1000.0 Hz
[21:10:47][C][output.ledc:036]:   Bit Depth: 12
```

**Additional information and things you've tried:**
I have found similar CLOSED issue:
https://github.com/esphome/issues/issues/258

So I have tried version 1.12.2 which works at 1000Hz as expected! :-)
