### ISSUE TITLE
Question regarding rgb_color

### ISSUE THREAD

**Issue by Fusseldieb** [esphome/issues#784]
It's more a question than a bug, but I still didn't find out how to do this.

Basically, I want to set a LED a specific color over the ESPHome API. I can turn the LED on, but I'm struggling to change the color of it.

```
  - platform: remote_receiver
    name: "Color 1"
    raw: 
      code: [ ... ]
    on_press:
      then:
        - homeassistant.service:
            service: light.turn_on
            data:
              entity_id": light.led_light
              #rgb_color: [0,255,0] - Doesn't accept it
```

with the code above, the light turns on, but if I try to put rgb_color, it gives me an error saying that ""string value cannot be dictionary or list", but I need three values. How do I pass them?

Thanks in advance
