### ISSUE TITLE
Set rgb_color via API

### ISSUE THREAD

**Issue by Fusseldieb** [esphome/issues#785]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant 0.100.3

**ESP (ESP32/ESP8266, Board/Sonoff):**
NodeMCU v3

**Affected component:**
rgb_color

**Description of problem:**

It's more a question than a bug, but I still didn't find out how to do this.

Basically, I want to set a LED a specific color over the ESPHome API. I can turn the LED on, but I'm struggling to change the color of it.

It gives me an error saying that "string value cannot be dictionary or list", but I need three values. How do I pass them?

Thanks in advance

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: remote_receiver
    name: "Color 1"
    raw: 
      code: [ ... ]
    on_press:
      then:
        - homeassistant.service:
            service: light.turn_on
            data:
              entity_id": light.led_light
              #rgb_color: [0,255,0] - Doesn't accept it

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
