### ISSUE TITLE
Stripped down config fails to compile - ESPmDNS.h: No such file

### ISSUE THREAD

**Issue by tomdee** [esphome/issues#79]
<!-- Thanks for reporting a bug for this project. READ THIS FIRST:

- Provide as many details as possible. Simply saying "X gives bug" or "X gives error" is not enough!
- Paste logs, configuration sample and code into the backticks (```).
- Read through the template carefully and fill out all missing details.
- Please also search for similar issues in this issue tracker first and read through the ESPHome FAQ.

DO NOT DELETE ANY TEXT from this template! Otherwise the issue may be closed without a comment.
-->

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip with esphome v1.11.0

**ESP (ESP32/ESP8266, Board/Sonoff):**
esp32
**Affected component:**
**Description of problem:**
Failure to compile. I get this error
```
.piolibdeps/esphome-core/src/esphome/util.cpp:9:23: fatal error: ESPmDNS.h: No such file or directory
```


If i add `ota:` then it does compile

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:                                                                                                                                                                                                                                                                                  
  name: hottub                                                                                                                                                                                                                                                                            
  platform: ESP32                                                                                                                                                                                                                                                                         
  board: nodemcu-32s                                                                                                                                                                                                                                                                      
logger:                                                                                                                                                                                                                                                                                   
sensor:                                                                                                                                                                                                                                                                                   
  - platform: dht                                                                                                                                                                                                                                                                         
    pin:                                                                                                                                                                                                                                                                                  
      number: GPIO22                                                                                                                                                                                                                                                                      
      mode: INPUT_PULLUP                                                                                                                                                                                                                                                                  
    model: DHT22                                                                                                                                                                                                                                                                          
    temperature:                                                                                                                                                                                                                                                                          
      name: "Outside Temperature"                                                                                                                                                                                                                                                         
    humidity:                                                                                                                                                                                                                                                                             
      name: "Outside Humidity"                                                                                                                                                                                                                                                            
    update_interval: 1s           

```
