### ISSUE TITLE
sun: on_sunrise and on_sunset at wrong time

### ISSUE THREAD

**Issue by dzikus** [esphome/issues#793]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
 pip
**ESP (ESP32/ESP8266, Board/Sonoff):**
 ESP8266
**Affected component:**

sun:

**Description of problem:**
on_sunrise is 1h before real sunrise and on_sunset is 1h after real sunset in my location

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: schody
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

logger:

api:

ota:

sun:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  on_sunrise:
  - then:
    - light.turn_off:
        id: light1
  on_sunset:
  - then:
    - light.turn_on:
        id: light1
time:
  - platform: homeassistant

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Schody button"
    on_press:
      - light.toggle: light1
  - platform: status
    name: "Sonoff Basic Schody Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  - platform: binary
    id: light1
    name: "Sonoff Basic Schody light"
    output: relay
  - platform: monochromatic
    name: "Sonoff Basic Schody Blue LED"
    output: blue_led
    internal: true
    id: blue_led_light

sensor:
  - platform: wifi_signal
    name: "Sonoff Basic Schody WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Sonoff Basic Schody Uptime"
    update_interval: 60s
  - platform: sun
    name: Sun Elevation
    type: elevation
    update_interval: 60s
  - platform: sun
    name: Sun Azimuth
    type: azimuth
    update_interval: 60s

text_sensor:
  - platform: sun
    name: Sun Next Sunrise
    type: sunrise
  - platform: sun
    name: Sun Next Sunset
    type: sunset
```

**Logs (if applicable):**

```
[14:00:15][D][text_sensor:015]: 'Sun Next Sunrise': Sending state '05:3X:XX'
[14:00:19][D][text_sensor:015]: 'Sun Next Sunset': Sending state '17:4X:XX'
```

**Additional information and things you've tried:**

Real sunrise on my location today is around 6:30, real sunset on my location today is around 16:30. I changed timezone to test it without success, I changed timesource to:
```yaml
  - platform: sntp
    id: sntp_time
    timezone: !secret timezone
    servers:
      - !secret home_ntp
```
also without success.

**Comment by OttoWinter** [comment]
I can't replicate the issue with my setup.

Unfortunately, to debug this you will need to provide some information like timezone and location. If you don't want to use your own location, you can also choose a similar one that exhibits the same behavior.

Especially timezone would be useful, because ±1 hour sounds a lot like a timezone issue.

Please also check the time is synchronized properly - after startup you will see a message like "Synchronized time: ..." that displays the synchronized time.

**Comment by dzikus** [comment]
```yaml
esphome:
  name: schody
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

logger:

api:

ota:

sun:
  latitude: 50.2648
  longitude: 19.0237
  on_sunrise:
  - then:
    - light.turn_off:
        id: light1
  on_sunset:
  - then:
    - light.turn_on:
        id: light1

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers:
      - !secret home_ntp
      - time.google.com
  - platform: homeassistant

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Schody button"
    on_press:
      - light.toggle: light1
  - platform: status
    name: "Sonoff Basic Schody Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  - platform: binary
    id: light1
    name: "Sonoff Basic Schody light"
    output: relay
  - platform: monochromatic
    name: "Sonoff Basic Schody Blue LED"
    output: blue_led
    internal: true
    id: blue_led_light

sensor:
  - platform: wifi_signal
    name: "Sonoff Basic Schody WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Sonoff Basic Schody Uptime"
    update_interval: 60s
  - platform: sun
    name: Sun Elevation
    type: elevation
    update_interval: 60s
  - platform: sun
    name: Sun Azimuth
    type: azimuth
    update_interval: 60s

text_sensor:
  - platform: sun
    name: Sun Next Sunrise
    type: sunrise
  - platform: sun
    name: Sun Next Sunset
    type: sunset
```

```
[10:56:30][C][sntp:043]: SNTP Time:
[10:56:30][C][sntp:044]:   Server 1: '172.x.x.254'
[10:56:30][C][sntp:045]:   Server 2: 'time.google.com'
[10:56:30][C][sntp:046]:   Server 3: ''
[10:56:30][C][sntp:047]:   Timezone: 'CET-1CEST-2,M3.5.0/2,M10.4.0/3'

[10:56:32][D][time:030]: Synchronized time: Sat Nov  2 10:56:32 2019
[10:56:54][D][text_sensor:015]: 'Sun Next Sunrise': Sending state '05:38:22'
[10:56:59][D][text_sensor:015]: 'Sun Next Sunset': Sending state '17:49:25'
```

https://www.google.com/search?q=katowice+poland+sunrise+sunset+time

**Comment by dzikus** [comment]
Esphome also display:
```
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 03/29/20 02:00:00 to 10/25/20 03:00:00
```
before compilation.

**Comment by jumblies** [comment]
I confirm.  Discrepant sunrise time with same lat/long between HomeAssistant and ESPhome.

**Comment by OttoWinter** [comment]
Ok, I figured it out. This happens when the sun declination is negative. There was an erroneous check that constrained sun declination in the range [0,1], but it should have been [-1,1]

**Comment by dzikus** [comment]
I tested your changes and still there is something wrong. It is much closer to the real sunrise and sunset times but still other then in Google or HomeAssistant:
On ESPHome (with patch from 003326f2eb0f52e974325347bcc2e1d76d3c2283):
```
[08:40:24][D][text_sensor:015]: 'Sun Next Sunset': Sending state '16:28:13'
[08:40:26][D][text_sensor:015]: 'Sun Next Sunrise': Sending state '06:58:56'
```
On HA:
Zachód Za 7 godzin(y) 16:12
Wschód Za 22 godzin(y) 6:44
On Google https://www.google.com/search?q=katowice+sunset+sunrise+time+7.11.2019 :
06:44
16:11

I tested it on this location:
```yaml
latitude: 50.2648
longitude: 19.0237
```

**Comment by OttoWinter** [comment]
Some discrepancy is to be expected - calculating the real position of the sun makes the calculations just way to complex.

However, that error was at most around ~2 minutes during my testing. So there may be another issue here.

**Comment by dzikus** [comment]
I also tested it on my light switch, and
```yaml
  on_sunrise:
  - then:
    - light.turn_off:
        id: light1
    elevation: 0
  on_sunset:
  - then:
    - light.turn_on:
        id: light1
    elevation: 0
```
turned off the light at other times than text_sensor gives, today light.turn_off was at 7:06, sunrise according to HA was at 6:46 and ESPHome text_sensor gives:
```
[09:35:19][D][text_sensor:015]: 'Sun Next Sunrise': Sending state '07:00:21'
```

I checked also light.turn_on yesterday and it was at 16:22, sunset according to HA was at 16:16 and text_sensor claims that next sunset is at 16:27.

All times are not much different but different, discrepancy is more than 2 minutes in every case that i tested.
