### ISSUE TITLE
Compilation and upload problem

### ISSUE THREAD

**Issue by kprzeb** [esphome/issues#805]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker aarch64 odroidc2
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 sonoff mini
**Affected component:**

**Description of problem:**
Compilation and upload problem

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: korytarz_gora
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "ssid"
  password: "pass"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO04
      mode: INPUT_PULLUP
      inverted: True
    name: "Światło korytarz góra przełącznik"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Światło korytarz góra"
    pin: GPIO12
    id: relay


```

**Logs (if applicable):**

INFO Reading configuration /config/esphome/korytarz_gora.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/korytarz_gora
Processing korytarz_gora (board: esp01_1m; framework: arduino; platform: espressif8266@2.2.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
Compiling /data/korytarz_gora/.pioenvs/korytarz_gora/src/esphome/components/api/api_connection.cpp.o
Illegal instruction (core dumped)
Compiling /data/korytarz_gora/.pioenvs/korytarz_gora/src/esphome/components/api/api_pb2.cpp.o
Illegal instruction (core dumped)
Compiling /data/korytarz_gora/.pioenvs/korytarz_gora/src/esphome/components/api/api_pb2_service.cpp.o
Illegal instruction (core dumped)
*** [/data/korytarz_gora/.pioenvs/korytarz_gora/src/esphome/components/api/api_connection.cpp.o] Error 132
Compiling /data/korytarz_gora/.pioenvs/korytarz_gora/src/esphome/components/api/api_server.cpp.o
*** [/data/korytarz_gora/.pioenvs/korytarz_gora/src/esphome/components/api/api_pb2.cpp.o] Error 132
*** [/data/korytarz_gora/.pioenvs/korytarz_gora/src/esphome/components/api/api_pb2_service.cpp.o] Error 132
Illegal instruction (core dumped)
*** [/data/korytarz_gora/.pioenvs/korytarz_gora/src/esphome/components/api/api_server.cpp.o] Error 132
========================== [FAILED] Took 7.66 seconds ==========================

**Additional information and things you've tried:**
