### ISSUE TITLE
Cannot build ESP32 based image - stops at linking - Crashes HA

### ISSUE THREAD

**Issue by borpin** [esphome/issues#821]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io, Docker, VM, HA 0.101.2

ESPHome add-in V1.14.2

**ESP (ESP32/ESP8266, Board/Sonoff):**

WEMOS D32

**Affected component:**

Any

**Description of problem:**
ESP32 based item never complies. Sits at linker and eventually crashes HA.

ESP8266 seems fine.

Worked fine with 1.14.0-dev

**Problem-relevant YAML-configuration entries:**
```yaml
<<: !include common/esphome.yaml
<<: !include common/wifi.yaml
<<: !include common/mqtt.yaml

esp32_ble_tracker:

sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: 4c:65:a8:d8:de:98
    temperature:
      name: "Xiaomi Temperature 98"
      state_topic: emon/xiaomi4c:65:a8:d8:de:98/temperature
      filters:
        - throttle: 90s
        - offset: -0.65
        - sliding_window_moving_average:
            window_size: 11
            send_every: 1
    humidity:
      name: "Xiaomi Humidity 98"
      state_topic: emon/xiaomi4c:65:a8:d8:de:98/humidity
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 1
        - throttle: 90s
    battery_level:
      name: "Xiaomi Battery 98"
      state_topic: emon/xiaomi4c:65:a8:d8:de:98/battery
```

**Logs (if applicable):**

```
INFO Reading configuration /config/esphome/esp32_ble.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/esp32_ble
Processing esp32_ble (board: lolin_d32; framework: arduino; platform: espressif32@1.11.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
Dependency Graph
|-- <AsyncTCP> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <AsyncMqttClient-esphome> 0.8.3
|   |-- <AsyncTCP> 1.1.1
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <Update> 1.0
|-- <WiFi> 1.0
Compiling /data/esp32_ble/.pioenvs/esp32_ble/src/main.cpp.o
Linking /data/esp32_ble/.pioenvs/esp32_ble/firmware.elf

```

**Additional information and things you've tried:**

Taken sensor out, rebooted server, clean build.

Tried rolling back to v1.14.0b1 - no success linking

[edit]
Tries to install v1.13.6 without success, so went back to mainstream and immediately, the compile was quicker and the linker finished!
```
Linking /data/esp32_ble/.pioenvs/esp32_ble/firmware.elf
Building /data/esp32_ble/.pioenvs/esp32_ble/firmware.bin
Retrieving maximum program size /data/esp32_ble/.pioenvs/esp32_ble/firmware.elf
Checking size /data/esp32_ble/.pioenvs/esp32_ble/firmware.elf
DATA:    [==        ]  18.5% (used 60692 bytes from 327680 bytes)
PROGRAM: [========= ]  89.3% (used 1462670 bytes from 1638400 bytes)
======================== [SUCCESS] Took 480.18 seconds ========================
INFO Successfully compiled program.
```
