### ISSUE TITLE
1.14.2 nodemcu doesn't connect with GPIO high 

### ISSUE THREAD

**Issue by andriej** [esphome/issues#822]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
docker (non-hassio)

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 / nodemcu v2

**Affected component:**
n/a

**Description of problem:**
I have nodemcu v2 with connected two digital sensors to two GPIOs. Since 1.14.2 it can't boot while one of it's sensors is HIGH state.

Binary sensor with GPIO14 - when it's HIGH esp won't connect to MQTT/boot, second after input changes it starts like nothing happened.
Im 99% sure it wasn't like that in 1.13.6 which was my previous release.

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  platform: ESP8266
  board: nodemcuv2
  devicename: klucznik
  upper_devicename: "Klucznik"
  static_ip: <redacted>
<<: !include common.yaml

logger:

switch:
  - platform: restart
    name: "Klucznik: restart"
    
sensor:   
  - platform: wifi_signal
    name: "Sygnał WiFi: Klucznik"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Zamek: górny"
    device_class: lock
    filters:
    - delayed_on: 3000ms
    - delayed_off: 3000ms
    
  - platform: gpio
    pin: 
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    name: "Zamek: dolny"
    device_class: lock
    filters:
    - delayed_on: 3000ms
    - delayed_off: 3000ms

```

**Logs (if applicable):**
n/a

**Additional information and things you've tried:**
I have just confirmed/checked - everything is working as expected after downgrade to 1.13.6.
Also: on 1.14.2 - the green indicator was showing node as online, while no other connection (i.e. MQTT or webserver). Also, it was receiving OTAs no problem.
