### ISSUE TITLE
Binary sensor randomly changes to unavailable

### ISSUE THREAD

**Issue by grzeg8102** [esphome/issues#825]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

esphome 1.14.2 in docker. HA 101.1 also docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP DEVKIT V1
**Affected component:**

binary sensor https://esphome.io/components/binary_sensor/gpio.html

**Description of problem:**
Status of binary sensor randomly changes to unavailable for a short period. I'm not sure if it started with 1.14, since the periods where it becomes unavailable are very short and last for a minute or so. But I spotted this after upgrading to 1.14 as I started to experience similar issue with a switch becoming unavailable for hours (issue #824).
![image](https://user-images.githubusercontent.com/27864579/68280521-ff24d900-0075-11ea-992a-9af20bfe9e58.png)

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: sensors_tracker
  platform: ESP32
  board: esp32doit-devkit-v1
          
wifi:
  ssid: 'REMOVED'
  password: 'removed'

ota:
  password: 'removed'

# Enable logging
logger:


esp32_ble_tracker:

sensor:
  - platform: xiaomi_hhccjcy01  #xiaomi_miflora
    mac_address: C4:7C:8D:65:FC:33
    temperature:
      name: "MiFlora Trawa Temperature"
    moisture:
      name: "MiFlora Trawa Moisture"
    illuminance:
      name: "MiFlora Trawa Illuminance"
    conductivity:
      name: "MiFlora Trawa Soil Conductivity"
    battery_level:
      name: "MiFlora Trawa Battery Level"

  - platform: xiaomi_hhccjcy01  #xiaomi_miflora
    mac_address: C4:7C:8D:65:FB:D5
    temperature:
      name: "MiFlora Tuje Temperature"
    moisture:
      name: "MiFlora Tuje Moisture"
    illuminance:
      name: "MiFlora Tuje Illuminance"
    conductivity:
      name: "MiFlora Tuje Soil Conductivity"
      
  - platform: xiaomi_lywsdcgq #xiaomi_mijia
    mac_address: 4C:65:A8:DB:DB:A6
    temperature:
      name: "Garaz Temperature"
      filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
    humidity:
      name: "Garaz Humidity"
    battery_level:
      name: "Garaz Battery Level"

  - platform: xiaomi_lywsd02
    mac_address: E7:2E:01:21:1C:33
    temperature:
      name: "Xiaomi LYWSD02 Temperature"
    humidity:
      name: "Xiaomi LYWSD02 Humidity"
  
  - platform: adc
    pin: GPIO34
    name: "esp32_swiatlo"
    update_interval: 60s
    attenuation: 11db

  - platform: adc
    pin: GPIO35
    name: "esp32_gleba"
    filters:
      - sliding_window_moving_average:
          window_size: 12
          send_every: 12
      - lambda: return abs(3.90 - x);
    update_interval: 5s
    attenuation: 11db
    
  - platform: adc
    pin: GPIO32
    name: "esp32_deszcz"
    update_interval: 60s
    attenuation: 11db

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO23
      mode: INPUT_PULLDOWN
      inverted: True
    name: "Brama garazowa"
    device_class: garage_door
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
        
api:  
  
time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: 0
        hours: 12
        days_of_week: MON-SUN
        then:
          - switch.toggle: restart_sw

switch:
  - platform: restart
    name: "ESP32 garaz restart"
    id: restart_sw
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
