### ISSUE TITLE
Unable to use Nextion display buttons

### ISSUE THREAD

**Issue by AalianKhan** [esphome/issues#83]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
'.
-->
running esphome version 1.11.1
**ESP (ESP32/ESP8266, Board/Sonoff):**

I am using a wemos D1 mini with a 2.4 inch Nextion Display
**Affected component:**

Nextion Touch Component/Nextion Display Component

**Description of problem:**
I am unable to use any buttons with the Nextion Display. esphome doesn't seem to see when I touch the button. Also when I use Lambda to populate some of the components for the display it gives errors but you can see it clearly did the task correctly because you can see it on the display. 

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: nextion
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'My SSID'
  password: 'MY PWD'
  manual_ip:
    static_ip: 192.168.0.51
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

uart: 
  rx_pin: D7
  tx_pin: D8
  baud_rate: 9600

display:
  - platform: nextion
    id: display
    lambda: |-
      it.set_component_text("t0", "hello");

binary_sensor:
  - platform: nextion
    page_id: 0
    component_id: 2
    nextion_id: display
    id: button
    on_release:
      then:
        lambda: |-
          id(display).set_component_text("t0", "pressed");

```

**Traceback (if applicable):**

```

```
**Logs**
```
[E][uart:228]: Reading from UART timed out at byte 1!
[W][display.nextion:039]: Nextion returned no ACK data!
[W][display.nextion:111]: Sending command 't0.txt="hello"' failed because no ACK was received
```
**Additional information and things you've tried:**
I have tried reflashing the D1 mini, reinstalling the Hass.io add on, making new files and many more. a friend in the esphome discord server named T-Bone, has got this working and he doesn't have the weird logs either. Maybe it is not flashing properly but it says successful when I flash it. One weird thing is that I can't see the logs when it is directly connected by a serial connection.
