### ISSUE TITLE
force_update not being respected in Home Assisant

### ISSUE THREAD

**Issue by haufes** [esphome/issues#842]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

- ESPHome 1.14.2 docker 
- Home Assistant 0.101.3 docker
- arch  x86_64

**ESP (ESP32/ESP8266, Board/Sonoff):**

- ESP32

**Affected component:**

[Sensor force_update](https://esphome.io/components/sensor/index.html?highlight=force_update)

**Description of problem:**

The pulse counter is not force updating in HA. 

**Problem-relevant YAML-configuration entries:**

```yaml
sensor:    
  - platform: pulse_counter
    pin: 35
    name: "House Power"
    unit_of_measurement: 'Wh'
    accuracy_decimals: 0    
    update_interval: 60s      
    force_update: true    

```

**Logs (if applicable):**

None, sensor was emitting

**Additional information and things you've tried:**

I was able to get the values forced from the esp using a the REST platform in HA.
