### ISSUE TITLE
Error after flashing,  "No route to host"

### ISSUE THREAD

**Issue by surfarn** [esphome/issues#844]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Ubuntu, Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**
 ESP8266

**Affected component:**

NAS WR01W

**Description of problem:**
![image](https://user-images.githubusercontent.com/53119062/68689825-4b3db500-0571-11ea-923e-3e15a8434995.png)

Something error must have happened while flashing.  The Hass.io ESpHome addon can see the device. But I can not connect to it or upload a new firmware. 

`INFO Reading configuration /config/esphome/neo_energy_plug2.yaml...
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 29 March 02:00:00 to 25 October 03:00:00
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/neo_energy_plug2
Processing neo_energy_plug2 (board: esp8285; framework: arduino; platform: espressif8266@2.2.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.5
|   |-- <ESPAsyncTCP-esphome> 1.2.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ArduinoJson-esphomelib> 5.13.3
Compiling /data/neo_energy_plug2/.pioenvs/neo_energy_plug2/src/main.cpp.o
Linking /data/neo_energy_plug2/.pioenvs/neo_energy_plug2/firmware.elf
Building /data/neo_energy_plug2/.pioenvs/neo_energy_plug2/firmware.bin
Retrieving maximum program size /data/neo_energy_plug2/.pioenvs/neo_energy_plug2/firmware.elf
Checking size /data/neo_energy_plug2/.pioenvs/neo_energy_plug2/firmware.elf
DATA:    [=====     ]  47.4% (used 38804 bytes from 81920 bytes)
PROGRAM: [====      ]  43.3% (used 443096 bytes from 1023984 bytes)
Creating BIN file "/data/neo_energy_plug2/.pioenvs/neo_energy_plug2/firmware.bin" using "/data/neo_energy_plug2/.pioenvs/neo_energy_plug2/firmware.elf"
========================= [SUCCESS] Took 3.86 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 10.0.0.130
ERROR Connecting to 10.0.0.130:8266 failed: [Errno 113] No route to host`

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
substitutions:
  plug_name: neo_energy_plug2
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "800"
esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285

wifi:
  networks:
  - ssid: "ssid"
    password: "passw"
    priority: 10
  - ssid: "ssid"
    password: "passw"
    priority: 5

# Optional manual IP
  manual_ip:
    static_ip: 10.0.0.130
    gateway: 10.0.0.1
    subnet: 255.255.255.0


# Enable Home Assistant API
api:
  password: "Passw"

ota:
  password: "Passw"  
# Enable logging
logger:
# Enable Web server
web_server:
  port: 80
# Enable Home Assistant API

time:
  - platform: homeassistant
    id: homeassistant_time
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    name: "${plug_name}_button"
    on_press:
      - switch.toggle: relay
    
switch:
- platform: gpio
  name: "${plug_name}_Relay"
  pin: GPIO14
  id: relay
  restore_mode: ALWAYS_ON
  
#- platform: gpio
#  name: "${plug_name}_LED_Blue"
#  pin: GPIO1
#  inverted: True
#  restore_mode: ALWAYS_OFF
- platform: gpio
  name: "${plug_name}_LED_Red"
  pin: GPIO13
  inverted: True
  restore_mode: ALWAYS_OFF
sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${plug_name}_Amperage"
      unit_of_measurement: A
    voltage:
      name: "${plug_name}_Voltage"
      unit_of_measurement: V
    power:
      name: "${plug_name}_Wattage"
      unit_of_measurement: W
      id: "${plug_name}_Wattage"
    change_mode_every: 8
    update_interval: 10s
  - platform: total_daily_energy
    name: "${plug_name}_Total Daily Energy"
    power_id: "${plug_name}_Wattage"
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
  - platform: wifi_signal
    name: "${plug_name}_Signal"
    update_interval: 120s      
# Extra sensor to keep track of plug uptime
  - platform: uptime
    name: ${plug_name}_Uptime SensorPreformatted text
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
INFO Reading configuration /config/esphome/neo_energy_plug2.yaml...
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 29 March 02:00:00 to 25 October 03:00:00
INFO Starting log output from 10.0.0.130 using esphome API
INFO Connecting to 10.0.0.130:6053 (10.0.0.130)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 10.0.0.130: [Errno 113] No route to host). Re-Trying in 1 seconds
```

**Additional information and things you've tried:**

I have another switch using almost the same yaml, so it should be valid. I can not connect to 10.0.0.130. I can not ping the device, and I can not upload a new firmware using the OTA. 

HomeAssistant have found the device but with no sensors. 

Any way to do a OTA flash since the device can be found by EspHome and HomeAssistent?
