### ISSUE TITLE
Unable to set color temperature with Kelvin

### ISSUE THREAD

**Issue by cryptelli** [esphome/issues#85]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Vanilla HA installed on Debian in a Python Virtualenv

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

[CW + WWL](https://esphome.io/components/light/cwww)

**Description of problem:**
When specifying Kelvin as a unit instead of mireds the following error occurs during compile.

`Expected Color Temperature with unit, got 6500 Kelvin. Got '6500 Kelvin'`

**Problem-relevant YAML-configuration entries:**
```yaml
light:
  - platform: cwww
    name: cwww_b22_01
    cold_white: output_daylight
    warm_white: output_warm_white
    cold_white_color_temperature: 6500 Kelvin
    warm_white_color_temperature: 2700 Kelvin

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
