### ISSUE TITLE
No Logs with esphome CLI

### ISSUE THREAD

**Issue by ellavas** [esphome/issues#861]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Mac OS 10.14.6
Python 3.7
Esphome 1.14.3

**ESP (ESP32/ESP8266, Board/Sonoff):**

SonOff Pow R2
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash

**Affected component:**

https://esphome.io/components/logger.html?highlight=logger

**Description of problem:**
When deploying and running a very simple project, there is no log ouput, even when the debug level is set to debug.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: pow
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: '*********'
  password: '*********'

debug:

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    pin: GPIO12
    name: "Living Room Torsher"
    id: relay
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
INFO Successfully compiled program.
Found multiple options, please choose one:
  [1] /dev/cu.SLAB_USBtoUART (CP2102 USB to UART Bridge Controller)
  [2] Over The Air (pow.local)
(number): 1
INFO Running:  esptool.py --before default_reset --after hard_reset --baud 460800 --chip esp8266 --port /dev/cu.SLAB_USBtoUART write_flash 0x0 pow/.pioenvs/pow/firmware.bin
esptool.py v2.7
Serial port /dev/cu.SLAB_USBtoUART
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 80:7d:3a:33:50:93
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0340
Compressed 373024 bytes to 258077...
Wrote 373024 bytes (258077 compressed) at 0x00000000 in 6.4 seconds (effective 465.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
INFO Successfully uploaded program.
INFO Starting log output from /dev/cu.SLAB_USBtoUART with baud rate 115200
```

**Additional information and things you've tried:**
