### ISSUE TITLE
PZEM 004T V1.0 wiring problem

### ISSUE THREAD

**Issue by MariusLaurinaitis** [esphome/issues#862]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266

**Affected component:**

**Description of problem:**
Do I need a PZEM soldering resistor (Pzem 004t V1.0)? And what do you use ESP8266 or ESP32? I try everything with the Wemos d1 mini, nothing can be seen.
Maybe you can show me the wiring diagram. Are you using the resistor soldered to PZEM?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
uart:
  tx_pin: D1
  rx_pin: D2
  baud_rate: 9600
  stop_bits: 2

sensor:
  - platform: pzem004t
    current:
      name: "PZEM-004T Current"
    voltage:
      name: "PZEM-004T Voltage"
    power:
      name: "PZEM-004T Power"
    update_interval: 60s
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
