### ISSUE TITLE
Trying to revert to 1.13.6 as 1.14.3 is not stable here

### ISSUE THREAD

**Issue by fribse** [esphome/issues#864]
Hi all

Im trying to revert to 1.13.6.
It works for most parts, but for my esp32-cam's it doesn't.

I get this message shown in the terminal:
`rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Guru Meditation Error: Core  0 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40160f74: 0300df21 d0091064 d04cd03b
`

My config looks like this:
```
substitutions:
  # Modify variables based on your settings
  hostname: 'camera_kitchen'

esphome:
  name: $hostname
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "SSID"
  password: "PW"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Camera Kitchen Fallback Hotspot"
    password: "b6Ihk0ROmC1Y"

#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "PW"

# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  name: kitchen
  # ... Frame Settings

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: $hostname light
```
I'm flashing the esp32 AI-Thinker board with ESPHome-Flasher-1.2.0-windows-x64.

I had it up and running on 1.14.3, but my other esp8266 devices went offline all the time, so I had to revert.
After revering I now get this problem with the ESP32 boards.
