### ISSUE TITLE
Problem with reverting to 1.13.6 from 1.14.3 on ESP32

### ISSUE THREAD

**Issue by fribse** [esphome/issues#865]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32 AI-Thinker Cam (2640)

**Affected component:**
It will not go online

**Description of problem:**
I have serious stability problems with 1.14.3 on my ESP8266's, they work for a day or so, and then they go offline. So I had to roll back to 1.13.6.
After doing that, my ESP32-cam (AI Thinker) from Geekcreit fails to boot properly.
They are flashed with ESPHome-Flasher-1.2.0-windows-x64
Looking in the console I see these messages:
```
rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Guru Meditation Error: Core  0 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40160f74: 0300df21 d0091064 d04cd03b
```

**Problem-relevant YAML-configuration entries:**
```
substitutions:
  # Modify variables based on your settings
  hostname: 'camera_kitchen'

esphome:
  name: $hostname
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "SSID"
  password: "PW"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Camera Kitchen Fallback Hotspot"
    password: "PW"

#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "PW"

# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  name: kitchen
  # ... Frame Settings

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: $hostname light


```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

```
