### ISSUE TITLE
DF-Player EQ issue

### ISSUE THREAD

**Issue by redskinhu** [esphome/issues#868]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Linux x86_64, Docker, Hass.io 0.101.3

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266 / ESP-12F

**Affected component:**
https://esphome.io/components/dfplayer.html

**Description of problem:**
The EQ is not working as suggested. It can't accept the ( NORMAL, POP, ROCK, JAZZ, CLASSIC and BASS) values if I call the service from the HASS with this service data `{ "preset": "ROCK" }` but it accept numbers `{ "preset": 1 }`. I dug out the number / value pairs from the source:
```
enum EqPreset {
  NORMAL = 0,
  POP = 1,
  ROCK = 2,
  JAZZ = 3,
  CLASSIC = 4,
  BASS = 5,
};
```
**Problem-relevant YAML-configuration entries:**
```yaml
  - service: dfplayer_set_eq
    variables:
      preset: int
    then:
      - dfplayer.set_eq: !lambda 'return static_cast<dfplayer::EqPreset>(preset);'
```

**Logs (if applicable):**
Home Assistant error if I use `{ "preset": "ROCK" }` service data.
```
Failed to call service esphome/dfplayer_esp12f_dfplayer_set_eq. expected int for dictionary value @ data['preset']
```

**Additional information and things you've tried:**
