### ISSUE TITLE
first time run hang at archiving libFrameworkArduino.a

### ISSUE THREAD

**Issue by austrisv** [esphome/issues#876]
[console_output.txt](https://github.com/esphome/issues/files/3882689/console_output.txt)

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip on windows commmandline

**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32 with ttgo-t display

**Affected component:**

first upload

**Description of problem:**
have just finished `esphome livingroom.yaml wizard`
Then, when running `esphome livingroom.yaml run` it hangs at `Archiving .pioenvs\livingroom2\libFrameworkArduino.a`

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: newnode
  platform: ESP32
  board: ttgo-t1

wifi:
  ssid: "aaaa"
  password: "12345678"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Newnode Fallback Hotspot"
    password: "UFGSsp0Swbyn"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
attached console output in .txt file
```

**Additional information and things you've tried:**
