### ISSUE TITLE
Can not compile or upload anymore

### ISSUE THREAD

**Issue by gnolnos** [esphome/issues#88]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff 4CH
**Affected component:**

Wifi

**Description of problem:**
I can not compile or upload the code anymore

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: lv3
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: 'LamThienR-3'
  password: 'mothaiba79'
  manual_ip:
    static_ip: 192.168.1.231
    gateway: 192.168.1.110
    subnet: 255.255.255.0
    dns1: 192.168.1.110
    dns2: 8.8.8.8
  fast_connect: True

api:

mqtt:
  discovery: clean
  broker: '192.168.1.200'
  username: 'sonoff'
  password: 'vungoimora!!!'
  port: 1883
  reboot_timeout: 0s
  keepalive: 5s

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: lv3_button_1
#    name: "LV3 Button 1"
    on_press:
      then:
        - light.toggle: lv3_light_1
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    id: lv3_button_2
#    name: "LV3 Button 2"
    on_press:
      then:
        - fan.toggle: lv3_fan_2
#  - platform: gpio
#    pin:
#      number: GPIO10
#      mode: INPUT_PULLUP
#      inverted: True
#    id: lv3_button_3
##   name: "LV3 Button 3"
#    on_press:
#      then:
#        - switch.toggle: lv3_relay_3
#  - platform: gpio
#    pin:
#      number: GPIO14
#      mode: INPUT_PULLUP
#      inverted: True
#    id: lv3_button_4
##   name: "LV3 Button 4"
#    on_press:
#      then:
#        - switch.toggle: lv3_relay_4
  - platform: status
    name: "LV3 Status"

#switch:
#  - platform: gpio
#    #name: "LV3 Relay 3"
#    id: lv3_relay_3
#    pin: GPIO4
#    retain: False
#  - platform: gpio
#    #name: "LV3 Relay 4"
#    id: lv3_relay_4
#    pin: GPIO15
#    retain: False

status_led:
    id: lv3_blue_led
    pin: 
      number: GPIO13
      inverted: True

output:
  - platform: gpio
    id: lv3_relay_1
    pin: GPIO12
  - platform: gpio
    id: lv3_relay_2
    pin: GPIO5

light:
#  - platform: monochromatic
#    name: "LV3 Blue LED"
#    output: lv3_blue_led
  - platform: binary
    name: "LV3 Relay 1"
    id: lv3_light_1
    output: lv3_relay_1
    retain: False

fan:
  - platform: binary
    name: "LV3 Relay 2"
    id: lv3_fan_2
    output: lv3_relay_2
    retain: False

sensor:
  - platform: wifi_signal
    name: "LV3 WiFi Signal Sensor"
    update_interval: 15s

```

**Traceback (if applicable):**

```
INFO Reading configuration...
WARNING ESP8266: Pin 9 (6-11) might already be used by the flash interface. Be warned.
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/lv3
Processing lv3 (platform: espressif8266@1.8.0; framework: arduino; board: esp01_1m)
--------------------------------------------------------------------------------
LibraryManager: Installing id=346 @ 0.8.2
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=305 @ ^1.1.0
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=1826 @ ^1.0.0
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=305 @ 1.1.3
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing esphome-core
git version 2.17.1
Cloning into '/config/esphome/lv3/.piolibdeps/_tmp_installing-itnqLI-package'...
LibraryManager: Installing id=3837 @ 5.13.3
Downloading...
Unpacking  [####################################]  100%
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz 80KB RAM (1MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 29 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <AsyncMqttClient> 0.8.2
|   |-- <ESPAsyncTCP> 1.2.0
|   |   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.1.3
|   |-- <ESP8266WiFi> 1.0
|-- <Hash> 1.0
|-- <esphome-core> 1.12.0-dev #1e91e7b
|   |-- <ArduinoJson-esphomelib> 5.13.3
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <AsyncMqttClient> 0.8.2
|   |   |-- <ESPAsyncTCP> 1.2.0
|   |   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESPAsyncTCP> 1.2.0
|   |   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/lv3/src/main.cpp.o
Generating LD script .pioenvs/lv3/ld/eagle.app.v6.common.ld
Compiling .pioenvs/lv3/lib4d9/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pioenvs/lv3/lib4d9/ESP8266WiFi/CertStoreBearSSL.cpp.o
Compiling .pioenvs/lv3/lib4d9/ESP8266WiFi/ESP8266WiFi.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:50:14: error: 'NoArg' was not declared in this scope
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:50:19: error: template argument 1 is invalid
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:50:33: error: invalid type in declaration before '=' token
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:50:55: error: the value of 'NoArg' is not usable in a constant expression
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:50:14: note: 'NoArg' was not declared 'constexpr'
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:50:88: error: no matching function for call to 'esphome::Application::make_automation(esphome::binary_sensor::PressTrigger*&)'
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:50:88: note: candidate is:
In file included from .piolibdeps/esphome-core/src/esphome.h:1:0,
from src/main.cpp:3:
.piolibdeps/esphome-core/src/esphome/application.h:359:22: note: template<class ... Ts> esphome::Automation<Ts ...>* esphome::Application::make_automation(esphome::Trigger<Ts ...>*)
Automation<Ts...> *make_automation(Trigger<Ts...> *trigger);
^
.piolibdeps/esphome-core/src/esphome/application.h:359:22: note:   template argument deduction/substitution failed:
src/main.cpp:51:14: error: the value of 'NoArg' is not usable in a constant expression
Automation<NoArg> *automation_2 = App.make_automation<NoArg>(binary_sensor_presstrigger_2);
^
src/main.cpp:50:14: note: 'NoArg' was not declared 'constexpr'
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:51:19: error: type/value mismatch at argument 1 in template parameter list for 'template<class ... Ts> class esphome::Automation'
Automation<NoArg> *automation_2 = App.make_automation<NoArg>(binary_sensor_presstrigger_2);
^
src/main.cpp:51:19: error:   expected a type, got 'NoArg'
src/main.cpp:51:35: error: invalid type in declaration before '=' token
Automation<NoArg> *automation_2 = App.make_automation<NoArg>(binary_sensor_presstrigger_2);
^
src/main.cpp:51:57: error: the value of 'NoArg' is not usable in a constant expression
Automation<NoArg> *automation_2 = App.make_automation<NoArg>(binary_sensor_presstrigger_2);
^
src/main.cpp:50:14: note: 'NoArg' was not declared 'constexpr'
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:51:92: error: no matching function for call to 'esphome::Application::make_automation(esphome::binary_sensor::PressTrigger*&)'
Automation<NoArg> *automation_2 = App.make_automation<NoArg>(binary_sensor_presstrigger_2);
^
src/main.cpp:51:92: note: candidate is:
In file included from .piolibdeps/esphome-core/src/esphome.h:1:0,
from src/main.cpp:3:
.piolibdeps/esphome-core/src/esphome/application.h:359:22: note: template<class ... Ts> esphome::Automation<Ts ...>* esphome::Application::make_automation(esphome::Trigger<Ts ...>*)
Automation<Ts...> *make_automation(Trigger<Ts...> *trigger);
^
.piolibdeps/esphome-core/src/esphome/application.h:359:22: note:   template argument deduction/substitution failed:
src/main.cpp:54:23: error: the value of 'NoArg' is not usable in a constant expression
light::ToggleAction<NoArg> *action = lv3_light_1->make_toggle_action<NoArg>();
^
src/main.cpp:50:14: note: 'NoArg' was not declared 'constexpr'
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:54:28: error: type/value mismatch at argument 1 in template parameter list for 'template<class ... Ts> class esphome::light::ToggleAction'
light::ToggleAction<NoArg> *action = lv3_light_1->make_toggle_action<NoArg>();
^
src/main.cpp:54:28: error:   expected a type, got 'NoArg'
src/main.cpp:54:38: error: invalid type in declaration before '=' token
light::ToggleAction<NoArg> *action = lv3_light_1->make_toggle_action<NoArg>();
^
src/main.cpp:54:72: error: the value of 'NoArg' is not usable in a constant expression
light::ToggleAction<NoArg> *action = lv3_light_1->make_toggle_action<NoArg>();
^
src/main.cpp:50:14: note: 'NoArg' was not declared 'constexpr'
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:54:79: error: no matching function for call to 'esphome::light::LightState::make_toggle_action()'
light::ToggleAction<NoArg> *action = lv3_light_1->make_toggle_action<NoArg>();
^
src/main.cpp:54:79: note: candidate is:
In file included from .piolibdeps/esphome-core/src/esphome/controller.h:6:0,
from .piolibdeps/esphome-core/src/esphome/api/api_server.h:9,
from .piolibdeps/esphome-core/src/esphome/application.h:6,
from .piolibdeps/esphome-core/src/esphome.h:1,
from src/main.cpp:3:
.piolibdeps/esphome-core/src/esphome/light/light_state.h:100:24: note: template<class ... Ts> esphome::light::ToggleAction<Ts ...>* esphome::light::LightState::make_toggle_action()
ToggleAction<Ts...> *make_toggle_action();
^
.piolibdeps/esphome-core/src/esphome/light/light_state.h:100:24: note:   template argument deduction/substitution failed:
src/main.cpp:55:21: error: the value of 'NoArg' is not usable in a constant expression
fan::ToggleAction<NoArg> *action_2 = lv3_fan_2->make_toggle_action<NoArg>();
^
src/main.cpp:50:14: note: 'NoArg' was not declared 'constexpr'
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:55:26: error: type/value mismatch at argument 1 in template parameter list for 'template<class ... Ts> class esphome::fan::ToggleAction'
fan::ToggleAction<NoArg> *action_2 = lv3_fan_2->make_toggle_action<NoArg>();
^
src/main.cpp:55:26: error:   expected a type, got 'NoArg'
src/main.cpp:55:38: error: invalid type in declaration before '=' token
fan::ToggleAction<NoArg> *action_2 = lv3_fan_2->make_toggle_action<NoArg>();
^
src/main.cpp:55:70: error: the value of 'NoArg' is not usable in a constant expression
fan::ToggleAction<NoArg> *action_2 = lv3_fan_2->make_toggle_action<NoArg>();
^
src/main.cpp:50:14: note: 'NoArg' was not declared 'constexpr'
Automation<NoArg> *automation = App.make_automation<NoArg>(binary_sensor_presstrigger);
^
src/main.cpp:55:77: error: no matching function for call to 'esphome::fan::FanState::make_toggle_action()'
fan::ToggleAction<NoArg> *action_2 = lv3_fan_2->make_toggle_action<NoArg>();
^
src/main.cpp:55:77: note: candidate is:
In file included from .piolibdeps/esphome-core/src/esphome/controller.h:5:0,
from .piolibdeps/esphome-core/src/esphome/api/api_server.h:9,
from .piolibdeps/esphome-core/src/esphome/application.h:6,
from .piolibdeps/esphome-core/src/esphome.h:1,
from src/main.cpp:3:
.piolibdeps/esphome-core/src/esphome/fan/fan_state.h:60:24: note: template<class ... Ts> esphome::fan::ToggleAction<Ts ...>* esphome::fan::FanState::make_toggle_action()
ToggleAction<Ts...> *make_toggle_action();
^
.piolibdeps/esphome-core/src/esphome/fan/fan_state.h:60:24: note:   template argument deduction/substitution failed:
src/main.cpp:56:15: error: request for member 'add_actions' in '* automation', which is of non-class type 'int'
automation->add_actions({action});
^
src/main.cpp:57:17: error: request for member 'add_actions' in '* automation_2', which is of non-class type 'int'
automation_2->add_actions({action_2});
^
*** [.pioenvs/lv3/src/main.cpp.o] Error 1
========================== [ERROR] Took 51.80 seconds ==========================
```

**Additional information and things you've tried:**
