### ISSUE TITLE
YAML anchor key merge

### ISSUE THREAD

**Issue by edge90** [esphome/issues#886]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip install esphome
arch linux

**ESP (ESP32/ESP8266, Board/Sonoff):**

shelly 2.5 
```yaml
esphome:
  platform: ESP8266
  board: esp01_1m
```

**Affected component:**

**Description of problem:**

YAML anchor tags doesn't work as expected.

`esphome shelly_25.yaml config`

Output:
> ERROR Error while reading config: Invalid YAML syntax. Please see YAML syntax reference or use an online YAML syntax validator:
> 
> duplicate key: "name"

Expected result: the latter should override the former.

**Problem-relevant YAML-configuration entries:**
```yaml

binary_sensor:
  - &button1
    platform: gpio
    name: "button 1"
    pin:
      number: GPIO2

switch:
  <<: *button1
  name: "override"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
