### ISSUE TITLE
ADS1115 needs locking?

### ISSUE THREAD

**Issue by balrog-kun** [esphome/issues#892]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip3

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32, lolin32

**Affected component:**

https://esphome.io/components/sensor/ads1115.html
https://esphome.io/components/sensor/ct_clamp.html

**Description of problem:**
I'm trying to measure current in 4 wires using 4 current transformers connected to ADS1115 inputs.  I configured the ct_clamp and ads1115 components.  I was getting either continuous ```[W][ads1115:116]: Reading ADS1115 timed out``` messages from boot-up, or if a conversion succeeded, the values would be wrong.  I read the code.  I think there may be two issues but this is the first time I'm using esphome or reading its code so I may be wrong.

Potential issue 1 is that there's no locking and with 4 sensors configured on top of the ads1115 component  the sensors may be interrupting each other's conversions, whether in continuous_mode or not.  This is based on the assumption that there's some multitasking in esphome which there seems to be.  There may be some locking implied by using PollingComponent in ct_clamp or somewhere else I don't know of, this and other facts would influence whether it's better if the locking is done at the ads1115 level or ct_clamp level, or both.
[EDIT] Ok, so based on comments in other issues reports, with people mostly successfully using ct_clamp, I don't think that is a real problem or that there's multitasking at this level...

Potential issue 2 is that in ADS1115Component::request_measurement() we're waiting for CONFIG register's bit 15 to become 1 after a conversion but in continuous_mode, by my reading of the spec, this may never happen.  That loop will also end if the read_byte_16() of that register returns an error by the way.

An issue/feature-request 3 would be that in continuous mode we could, at least partially, take advantage of the latest conversion result already being there to avoid the delay(2).  With multiple sensors+ct_clamp components this would obviously require that each ct_clamp instance is able to exclusively use the ads1115 components for its sampling period.

**Problem-relevant YAML-configuration entries:**
```yaml
i2c:
  sda: 21
  scl: 22
  scan: True
  frequency: 100kHz

ads1115:
  address: 0x48
  continuous_mode: on
  id: ads1115_48

sensor:
  - name: "ADS1115 Channel A0-GND"
    id: ads1115_a0
    ads1115_id: ads1115_48
    multiplexer: 'A0_GND'
    gain: 6.144
    platform: ads1115
  - name: "ADS1115 Channel A1-GND"
    id: ads1115_a1
    ads1115_id: ads1115_48
    multiplexer: 'A1_GND'
    gain: 6.144
    platform: ads1115
  - name: "ADS1115 Channel A2-GND"
    id: ads1115_a2
    ads1115_id: ads1115_48
    multiplexer: 'A2_GND'
    gain: 6.144
    platform: ads1115
  - name: "ADS1115 Channel A3-GND"
    id: ads1115_a3
    ads1115_id: ads1115_48
    multiplexer: 'A3_GND'
    gain: 6.144
    platform: ads1115
  - name: "Dormitory 2 current"
    platform: ct_clamp
    sensor: ads1115_a0
    sample_duration: 200ms
    filters:
      calibrate_linear:
        # The sensor should measure 2.5V + I / 2500 * 220 / 1.44 ?
        - 0 -> 0
        - 2.3328 -> 15
  - name: "Living room socket 1 current"
    platform: ct_clamp
    sensor: ads1115_a1
    sample_duration: 200ms
    filters:
      calibrate_linear:
        # The sensor should measure 2.5V + I / 2500 * 220 / 1.44 ?
        - 0 -> 0
        - 2.3328 -> 15
...
```

**Logs (if applicable):**

**Additional information and things you've tried:**
