### ISSUE TITLE
Can't import HA binary_sensor as sensor

### ISSUE THREAD

**Issue by ulph** [esphome/issues#898]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

hass.io on a rpi3b

**ESP (ESP32/ESP8266, Board/Sonoff):**

wemos lolin32

**Affected component:**

lambda, on homeassistant imported binary sensors

**Description of problem:**

Logic in lambdas based on homeassistant imported binary sensors is broken, as the values never change. 

See log for a hint. The underlying values seemingly are 'on'/'off' etc.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: homeassistant
    id: ytterdorr_nv_vibration
    entity_id: binary_sensor.ytterdorr_nv_vibration
    internal: true
    
font:
  - file: 'slkscr.ttf'
    id: font_slkscr
    size: 8
    
i2c:
  sda: 22
  scl: 21
  scan: False

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-
      auto row = 0;
      it.printf(127-64, (row++)*8, id(font_slkscr), TextAlign::TOP_RIGHT , "%s", id(ytterdorr_nv_vibration).has_state()?(id(ytterdorr_nv_vibration).state?"MTN":"-"):".");

```

**Logs (if applicable):**

```
[00:46:46][W][homeassistant.sensor:014]: Can't convert 'on' to number!
[00:46:46][D][sensor:092]: 'ytterdorr_nv_vibration': Sending state nan  with 1 decimals of accuracy

```

**Additional information and things you've tried:**

https://www.home-assistant.io/integrations/binary_sensor/

**Comment by brandond** [comment]
You're trying to import a binary_sensor as a sensor. One of these things has a boolean as the state, the other has a number. Did you maybe mean:

```yaml
binary_sensor:
  - platform: homeassistant
    id: ytterdorr_nv_vibration
    entity_id: binary_sensor.ytterdorr_nv_vibration
    internal: true
```
