### ISSUE TITLE
Can't compile ads with gain 4.096

### ISSUE THREAD

**Issue by rradar** [esphome/issues#90]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp8266/d1 mini
**Affected component:**

ads

**Description of problem:**

Can't compile

**Problem-relevant YAML-configuration entries:**
```yaml

  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 4.096
    name: "You name it!"
```

```
src/main.cpp: In function 'void setup()':
src/main.cpp:44:150: error: 'ADS1115_GAIN_6P096' is not a member of 'esphome::sensor'
sensor::ADS1115Sensor *sensor_ads1115sensor = sensor_ads1115component->get_sensor("younameit", sensor::ADS1115_MULTIPLEXER_P1_NG, sensor::ADS1115_GAIN_6P096);
^
*** [.pioenvs/younameit/src/main.cpp.o] Error 1

```

**Additional information and things you've tried:**

6.144 and 2.048 works like expected
