### ISSUE TITLE
core include yaml files within yaml files feature no longer working

### ISSUE THREAD

**Issue by poldim** [esphome/issues#902]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
- ESPHome in docker, running latest build via `esphome/esphome:dev`
- HA in docker, running latest build via `homeassistant/home-assistant:stable`

**ESP (ESP32/ESP8266, Board/Sonoff):**
Not relevant

**Affected component:**
core

**Description of problem:**
_I'm not sure if dev build issues are appropriate here._
I have a static part of my config for every device that I import via `<<: !include z_common.yaml`.  I uploaded code using this format last week, but today it is now giving me an error in the dev build.

**Problem-relevant YAML-configuration entries:**
```
substitutions:
  platform: ESP8266
  board: esp01_1m
  device_name: esphome_washer_dryer
  friendly_name: "Laundry"
  reboot_timeout_wifi: 900s
  reboot_timeout_api: 1800s
  output_power: 17dB

<<: !include z_common.yaml
```

**Logs (if applicable):**
```
Invalid YAML syntax. Please see YAML syntax reference or use an online YAML syntax validator:

while constructing a mapping
  in "/config/esphome_washer_dryer.yaml", line 1, column 1:
    substitutions:
    ^
expected a mapping or list of mappings for merging, but found scalar
  in "/config/esphome_washer_dryer.yaml", line 10, column 5:
    <<: !include z_common.yaml
        ^
```

**Additional information and things you've tried:**
Just pasting in the contents of my common file works without error.
This was working great until the most recent update to the dev build.  I'd like to maintain the current architecture that allows me to keep the bulk of this configuration standard.

Using https://davidchall.github.io/yaml-includes.html solution, it looks like the dev branch has it located here: https://github.com/esphome/esphome/blob/dev/esphome/yaml_util.py#L293

**common file contents**
```
esphome:
  platform: ${platform}
  board: ${board}
  name: ${device_name}

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_pwd
  fast_connect: on
  reboot_timeout: ${reboot_timeout_wifi}
  output_power: ${output_power}
  ap:
    ssid: "AP_${friendly_name}"
    password: !secret wifi_backup_pwd

api:
  reboot_timeout: ${reboot_timeout_api}

ota:

web_server:
  port: 80

logger:

```
