### ISSUE TITLE
script.wait waits forever

### ISSUE THREAD

**Issue by Iam-lcl** [esphome/issues#917]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

esphome 1.14.3

**ESP (ESP32/ESP8266, Board/Sonoff):**

Tuya power outlet (ESP8266).

**Affected component:**

[Automation ](https://esphome.io/guides/automations.html), [Script.wait](https://esphome.io/guides/automations.html?#script-wait-action)

**Description of problem:**
So tested the new feature script.wait that was introduced in 1.14.0.
What I expected is that the script will get blocked on script.wait until the script it validates ends.
The issue I found is that it appears the script.wait blocks the execution of all the lines after and when the script ends it never continues with the rest of the logic and script2 never executes.

My test was two scripts (script1 and script2).
script1 starts and has a delay of 10s
Script.wait gets called between script1 and scrip2, it will validate against script1.
Once script1 has ended it should call script2.

To me it appears that script.wait only validates once ?

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: deltaco3
  platform: ESP8266
  board: esp01_1m

<<: !include common/common.yaml

switch:
  - platform: gpio
    name: "deltaco3"
    pin: GPIO12
    
light:
  - platform: monochromatic
    name: "deltaco3 led"
    id: led
    default_transition_length: 0s
    output: output_1

output:
  - platform: esp8266_pwm
    id: output_1
    pin:
      number: GPIO5
      inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "deltaco3 switch"
    on_click:
      then:
      - logger.log: start scripts!
      - script.execute: script1
      - logger.log: wait!
#      - delay: 12s
      - script.wait: script1
      - logger.log: next move!
      - script.execute: script2
    
script:
  - id: script1
    then:
      - logger.log: Script delay!
      - delay: 10s
      - logger.log: Script delay end!
  - id: script2
    then:
      - logger.log: Script2 start!

```

**Logs (if applicable):**

```
[16:00:02][D][binary_sensor:036]: 'deltaco3 switch': Sending state ON
[16:00:02][D][binary_sensor:036]: 'deltaco3 switch': Sending state OFF
[16:00:02][D][main:235]: start scripts!
[16:00:02][D][main:231]: Script delay!
[16:00:02][D][main:250]: wait!
[16:00:12][D][main:247]: Script delay end!

```

**Additional information and things you've tried:**

If having a delay before script.wait that is longer then the delay in script1, then when script.wait is called it will validate that script1 is not running and continue to script2.

Started a thread at [homeassistant forum](https://community.home-assistant.io/t/script-wait/150957)

**Comment by napieraj** [comment]
This is still an issue in current dev and v1.14.5

easy-to-reproduce config:
```yaml
esphome:
  ...
  on_boot:
    priority: -100
    then:
      - delay: 5s
      - logger.log: "Executing Script"
      - script.execute: wait_example
      - logger.log: "Waiting for script"
      - script.wait: wait_example
      - logger.log: "Finished Waiting"

script:
- id: wait_example
  then:
  - logger.log: "Running script"
  - delay: 10s
  - logger.log: "Finished Script"

binary_sensor:
  - platform: template
    name: "Script Running"  
    lambda: |-
      return id(wait_example).script_is_running();
```

A template binary_sensor is attached to script_is_running() to better follow its execution, the script finishes but the logger call following `script.wait` is never called:
```
[D][main:090]: Executing Script
[D][main:164]: Running script
[D][main:175]: Waiting for script
[D][binary_sensor:036]: 'Script Running': Sending state ON
[D][main:179]: Finished Script
[D][binary_sensor:036]: 'Script Running': Sending state OFF
```
