### ISSUE TITLE
Range of days in time component results in whole week when week wraps

### ISSUE THREAD

**Issue by tribut** [esphome/issues#928]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**Affected component:**

https://esphome.io/components/time.html

**Description of problem:**

When giving a range for `days_of_week` that wraps around the numerical values, such as `SAT-SUN`, it is converted to `1,2,3,4,5,6,7`. This is unexpected.

**Problem-relevant YAML-configuration entries:**
```yaml
time:
  - platform: homeassistant
    on_time:
      - hours: 10
        minutes: 0
        seconds: 0
        days_of_week: SAT-SUN
        then:
          - switch.turn_off: relay
```

This results in (output from `validate`):

```yaml
time:
- platform: homeassistant
  on_time:
  - hours:
    - 10
    minutes:
    - 0
    seconds:
    - 0
    days_of_week:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    then:
    - switch.turn_off:
        id: relay
```
