### ISSUE TITLE
esp8266 crash with esphome 1.14.3

### ISSUE THREAD

**Issue by jhiller227** [esphome/issues#931]
I am having stability problems with my esp8266 devices all of my esp32 are fine. The devices that still have 1.13.6 are fine but every esp8266 that has 1.14.3 is unstable. I am running hasio 0.103.0 had have tried arduino 2.4.2 and 2.5.2 with the same result. the devices will run about 40 minutes then disconnect, serial login shows 'abort called'. I have tried to downgrade to 1.13.6 but the gui will not open. error 404. Any ideas?

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
 all esp8266 running 1.14.3 crash, all esp8266 running 1.13.6 work fine. all esp32  with either version are fine. 

**Affected component:**
  the device will abort and reboot after 40 minutes to and hour. 

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: test_plug
  platform: ESP8266
  board: esp01_1m
  arduino_version: 2.4.2

wifi:
  reboot_timeout: 0min
  networks:
  - ssid: "xxx"
    password: "xxx"
  - ssid: "xxx"
    password: "xxx"
  - ssid: "xxx"
    password: "xxx"

  manual_ip:
    static_ip: 192.168.0.19
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.92
    dns2: 192.168.0.90

    

# Enable logging
logger:
#  level: verbose 

# Enable Home Assistant API
api:
  reboot_timeout: 15min

ota:

web_server:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "test plug button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: " test plug"
    pin: GPIO12
    id: relay
    
 

status_led:
  pin:
    number: GPIO13
    inverted: no

**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->
