### ISSUE TITLE
Sonoff 4CH Pro external Buttons

### ISSUE THREAD

**Issue by alexmc1510** [esphome/issues#933]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 Board Sonoff 4CH Pro
**Affected component:**

**Description of problem:**
If I confugure GPIO0 and GPIO10 as PULLUP INPUT for external push buttons, behavior of the module is different from expected.
GPIO0 - Sonoff 4CH Pro does not start (it seems it remains in flash mode).
GPIO10 - Sonoff 4CH Pro resets.
The aim of the configuration is to open and close 1 cover so I need 2 external push buttons.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: dormitorio_principal
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: true
  id: pulsador_subir_persiana_dormitorio_principal
  on_press:
    then:
      # logic for cycling through movements: open->stop->close->stop->...
      - lambda: |
          if (id(persiana_dormitorio_principal).current_operation == COVER_OPERATION_IDLE) {
            // Cover is idle, check current state and either open or close cover.
            id(persiana_dormitorio_principal).open();
          } else {
            // Cover is opening/closing. Stop it.
            id(persiana_dormitorio_principal).stop();
          }

- platform: gpio
  pin:
    number: GPIO10
    mode: INPUT_PULLUP
    inverted: true
  id: pulsador_bajar_persiana_dormitorio_principal
  on_press:
    then:
      # logic for cycling through movements: open->stop->close->stop->...
      - lambda: |
          if (id(persiana_dormitorio_principal).current_operation == COVER_OPERATION_IDLE) {
            // Cover is idle, check current state and either open or close cover.
            id(persiana_dormitorio_principal).close();
          } else {
            // Cover is opening/closing. Stop it.
            id(persiana_dormitorio_principal).stop();
          }
- platform: status
  name: "Status Dormitorio Principal"

switch:
  - platform: gpio
    pin: 
      number: GPIO12
    id: subir_persiana_dormitorio_principal
    interlock: [bajar_persiana_dormitorio_principal]
  - platform: gpio
    pin: 
      number: GPIO5
    id: bajar_persiana_dormitorio_principal
    interlock: [subir_persiana_dormitorio_principal]
  - platform: gpio
    pin: 
      number: GPIO4
    id: radiador_dormitorio_principal
  - platform: gpio
    pin: 
      number: GPIO15
    id: luz_dormitorio_principal

cover:
  - platform: time_based
    name: "Persiana Dormitorio Principal"
    id: persiana_dormitorio_principal
    open_action:
      - switch.turn_on: subir_persiana_dormitorio_principal
    open_duration: 15s
    close_action:
      - switch.turn_on: bajar_persiana_dormitorio_principal
    close_duration: 15s
    stop_action:
      - switch.turn_off: subir_persiana_dormitorio_principal
      - switch.turn_off: bajar_persiana_dormitorio_principal
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I have tried GPIO9 and GPIO14 with success.
