### ISSUE TITLE
"Auth Expired" when compiled on windows

### ISSUE THREAD

**Issue by beikeland** [esphome/issues#936]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Does not work:
$ uname -a
MINGW64_NT-10.0 DESKTOP-OV51DUS 2.8.2(0.313/5/3) 2017-07-12 15:35 x86_64 Msys
$ esphome version
Version: 1.14.3

Does work:
$ uname -a
Linux rama 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
e$ esphome version
WARNING You're using ESPHome with python 2. Support for python 2 is deprecated and will be removed in 1.15.0. Please reinstall ESPHome with python 3.6 or higher.
Version: 1.14.3

**ESP (ESP32/ESP8266, Board/Sonoff):**

Blitzwolf BW-SHP6 (ESP8285)

**Affected component:**

wifi?

**Description of problem:**
After flashing new firmware from fresh windows install device lost wifi connection. Flashing with exactly the same config from linux, using same esphome version, for some reason works.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret iot_ssid
  password: !secret iot_password
  domain: !secret iot_domain 
  ap:
    ssid: "ESPhome"

logger:

api:
  reboot_timeout: 0s

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
   
binary_sensor:
  - platform: gpio
    id: button
    internal: true
    pin:
      number: GPIO13
    on_press:
      - switch.toggle: relay

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led

switch:
  - platform: gpio
    pin: GPIO15
    id: relay
    name: '${device_name} Relay'
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

status_led:
  pin:
    number: GPIO02
    inverted: true

sensor:
  - platform: uptime
    name: '${device_name} Uptime'
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574
    internal: true
  - platform: wifi_signal
    name: '${device_name} WiFi Signal'
    update_interval: 300s
    internal: true
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: '${device_name} Current'
      unit_of_measurement: 'A'
      accuracy_decimals: 3
      icon: mdi:flash-outline
      internal: true
    voltage:
      name: '${device_name} Voltage'
      unit_of_measurement: 'V'
      icon: mdi:flash-outline
      internal: true
    power:
      name: '${device_name} Power'
      unit_of_measurement: 'W'
      icon: mdi:flash-outline
      internal: true
    change_mode_every: 4
    update_interval: 10s
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
[I][logger:156]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:364]: There have been 0 suspected unsuccessful boot attempts.
[I][app:028]: Running through setup()...
[D][binary_sensor:034]: 'button': Sending initial state ON
[C][switch.gpio:011]: Setting up GPIO Switch 'blitzwolf04 Relay'...
[D][switch:025]: 'blitzwolf04 Relay' Turning OFF.
[D][switch:045]: 'blitzwolf04 Relay': Sending state OFF
[D][switch:025]: 'blitzwolf04 Relay' Turning OFF.
[C][hlw8012:013]: Setting up HLW8012...
[C][wifi:033]: Setting up WiFi...
[D][wifi:304]: Starting scan...
[D][sensor:092]: 'blitzwolf04 Uptime': Sending state 0.00000 days with 0 decimals of accuracy
[D][wifi:319]: Found networks:
[I][wifi:365]: - 'iotssid' (Dx:xx:xx:xx:xx:x4) ▂▄▆█
[D][wifi:366]:     Channel: 13
[D][wifi:367]:     RSSI: -62 dB
[D][wifi:369]: - 'EAGLE300EE7' (34:21:09:30:0E:E7) ▂▄▆█
[D][wifi:369]: - 'Telenor7533sei' (44:F0:34:ED:61:74) ▂▄▆█
[D][wifi:369]: - 'Mi-Fi' (44:F0:34:F1:09:D4) ▂▄▆█
[I][wifi:193]: WiFi Connecting to 'iotssid'...
[W][wifi_esp8266:337]: Event: Disconnected ssid='iotssid' bssid=Dx:xx:xx:xx:xx:x4 reason='Auth Expired'
[W][wifi:451]: Error while connecting to network.
[W][wifi:488]: Restarting WiFi adapter...
[W][wifi_esp8266:337]: Event: Disconnected ssid='iotssid' bssid=Dx:xx:xx:xx:xx:x4 reason='Authentication Failed'
[I][wifi:193]: WiFi Connecting to 'iotssid'...
[D][sensor:092]: 'blitzwolf04 Power': Sending state 0.00000 W with 1 decimals of accuracy
[W][wifi_esp8266:337]: Event: Disconnected ssid='iotssid' bssid=Dx:xx:xx:xx:xx:x4 reason='Auth Expired'
[W][wifi:451]: Error while connecting to network.
[W][wifi:488]: Restarting WiFi adapter...
[W][wifi_esp8266:337]: Event: Disconnected ssid='iotssid' bssid=Dx:xx:xx:xx:xx:x4 reason='Authentication Failed'
[D][wifi:304]: Starting scan...

```

**Additional information and things you've tried:**
have tried `esptool.py --port COM14 erase_flash` with no change.

similar is refrenced in #409 but downgrading to older esphome version failed, and in any case same version produce working binaries on linux.

removed logger and stripped config to basics with no change in outcome.

**Comment by tneish** [comment]
Same issue on windows.
I got it working on Linux only after updating the build environment (see below).

Run
`python -m platformio platform update`
to update.

The first 'platform' below worked, the second (older) didn't.

`python -m platformio platform update --dry-run`

> Platform Espressif 8266
> --------
> Checking espressif8266                   @ 2.3.2          [Up-to-date]
> Checking toolchain-xtensa                @ 2.40802.191122 [Up-to-date]
> Checking framework-arduinoespressif8266  @ 2.20603.191216 [Up-to-date]
> Checking tool-esptool                    @ 1.413.0        [Up-to-date]
> Checking tool-esptoolpy                  @ 1.20800.0      [Up-to-date]
> 
> Platform Espressif 8266
> --------
> Checking espressif8266                   @ 2.2.3          [Detached]
> Checking toolchain-xtensa                @ 2.40802.191122 [Up-to-date]
> Checking framework-arduinoespressif8266  @ 2.20502.0      [Up-to-date]
> Checking tool-esptool                    @ 1.413.0        [Up-to-date]
> Checking tool-esptoolpy                  @ 1.20600.0      [Up-to-date]`
>

**Comment by Electronlibre2012** [comment]
Hello,

same problem...

The only way to solved is to reboot the internet Box and my Wifi AP...

But other sensor dont start after that...

I dont understand anything...all my sensor have a static IP (x35 sensors).

Have you found a solution @beikeland  and @tneish please?

**Comment by tneish** [comment]
For reference I'm using Linux with:
Python 3.7.2
Created a virtual environment with "python3.7 -m venv"
Once inside the venv ("source bin/activate")..
Update pip ("python -m pip install --upgrade pip")
Install esphome ("pip install esphome")

Some special options in the esphome yaml that may or may not make a difference..

> esphome:
>   name: room1
>   platform: ESP8266
>   board: esp01_1m
>   platformio_options:
>     upload_speed: 57600
>     platform: espressif8266@2.3.2
> 
> wifi:
>   ssid: "..."
>   password: "..."
>   fast_connect: true
>   manual_ip:
>     static_ip: 10.0.4.203
>     gateway: 10.0.4.1
>     subnet: 255.255.255.0

Then compile and flash ("esphome room1.yaml run")

Flashed using serial, then flashed OTA while serial was still connected to make sure wifi OTA was working.

In my experience I suspect there can be bad combinations of esphome, platformio, esp libs.. but I have not looked further into it.

Also I am using Home Assistant and switched to adding the esphome devices by IP address instead of mDNS (e.g. "room1.local") as they appear faster after powering on. There is still a slight delay though. You can ping the IP address or run ("esphome room1.yaml logs") to see if it is up before it shows in Home assistant.

**Comment by Electronlibre2012** [comment]
@tneish 

Thanks for the time you bring to reply!

What a complete reply!

I am under HassOs on Rpi4 and i cant apply your solution, but i found another one, more simple way...i have a internet box and a AP, i am used to pair my sensor on the AP (Asus R8000) and i have plenty of gateway and sensor (50) so i pair the new sensor on the box this time and it work directly...

The AP is in "mix mode", there is only a SSID for one 2.4Ghz and two 5Ghz band...

The box is in "separate mode", there is one SSID for 2.4Ghz and one for 5Ghz.

Perhaps i have too much IOT on the AP...its strange because it happens just with 1 Weimos mini Pro and 2 Weimos D1 mini...i have a lot of deconnexions still 3 weeks, sometimes all works, sometimes one dont want to connect anymore, not always the same. So i decided to migrate the 3 "faulty" on the internet box SSID, and now, all works like a charm, together.

Thanks anyway for your help!

**Comment by martin3000** [comment]
platformio update

**Comment by h0jeZvgoxFepBQ2C** [comment]
I have this issue too on linux :(

**Comment by duchenpaul** [comment]
> esp01_1m

Thank you, your config works for me:
For the future people:
Add below as a walkarround, I swear to god I will never upgrade again.
```
  platformio_options:
    platform: espressif8266@2.3.2
```


```yaml
esphome:
  name: $device_name
  platform: ESP8266
  platformio_options:
    platform: espressif8266@2.3.2
  board: $board_model
  build_path: build/$device_name
  # esp8266_restore_from_flash: yes
  on_boot:
    priority: 800.0
    # ...
    then:
      - light.turn_off: rgbw_led
      - display.page.show: $main_page 

substitutions:
  board_model: d1_mini
  device_name: oled_display
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_fast_connect: 'true'
  wifi_reboot_timeout: 120s
  ota_password: !secret ota_password
  api_reboot_timeout: 120s
  main_page: time_page
```
