### ISSUE TITLE
Version text sensor showing as undefined

### ISSUE THREAD

**Issue by tomdee** [esphome/issues#94]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32
**Affected component:**

**Description of problem:**
In the web server, the version shows up as undefined

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
text_sensor:
  - platform: version
    name: "ESP32 Version"
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
