### ISSUE TITLE
RGBW(W) lights ignore brightness on white channel(s)

### ISSUE THREAD

**Issue by pauln** [esphome/issues#947]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

All affected (I'm using the esphome CLI)

**ESP (ESP32/ESP8266, Board/Sonoff):**

All affected (I'm using bulbs with ESP8266/ESP8285)

**Affected component:**

[rgbw](https://esphome.io/components/light/rgbw.html) and [rgbww](https://esphome.io/components/light/rgbww.html)

**Description of problem:**
White channels don't get dimmed by the `brightness` setting.  The calculations in `as_rgbw()` and `as_rgbww()` in `esphome/components/light/light_color_values.h` don't use `this->brightness_` at all (they factor in `this->white_` instead of it, rather than as well).

**Problem-relevant YAML-configuration entries:**
```yaml

output:
  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: pwm_red
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_green
  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_blue
  - platform: esp8266_pwm
    pin: GPIO5
    frequency: 1000 Hz
    id: pwm_cw
  - platform: esp8266_pwm
    pin: GPIO13
    frequency: 1000 Hz
    id: pwm_ww

light:
  - platform: rgbww
    name: "My Light"
    red: pwm_red
    green: pwm_green
    blue: pwm_blue
    cold_white: pwm_cw
    warm_white: pwm_ww
    cold_white_color_temperature: 5700 K
    warm_white_color_temperature: 3000 K
```

**Logs (if applicable):**

```
Not applicable

```

**Additional information and things you've tried:**
Modified the `as_rgbww()` function to include brightness in the cw/ww calculations, which fixed the issue.  I'll submit a pull request shortly.
