### ISSUE TITLE
SGP30 Baseline readings do not work

### ISSUE THREAD

**Issue by BertrumUK** [esphome/issues#950]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 Mini
**Affected component:**

SGP30

**Description of problem:**
Have just started using a [SGP30](https://esphome.io/components/sensor/sgp30.html) air quality sensor but after waiting 12 hours for the baseline reading to add to the config this causes either the eCO2 or the TVOC to stop reporting any values or to show their max readings of 60000 or 65000 respectively.

According to the [datasheet](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/0_Datasheets/Gas/Sensirion_Gas_Sensors_SGP30_Datasheet.pdf) there should be a baseline figure for both readings whereas this sensor reports and uses only 1 baseline setting.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: sgp30
    eco2:
      name: "Living Room eCO2"
      accuracy_decimals: 0
      filters:
        - median:
            window_size: 5
            send_every: 6
            send_first_at: 3
    tvoc:
      name: "Living Room  TVOC"
      accuracy_decimals: 0
    address: 0x58
    update_interval: 10s
    #baseline: 0x016D #0x747F #0xCA15 #0x1491 #0x5F4A #0x7AE8
    compensation:
      temperature_source: temperature
      humidity_source: humidity

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
