### ISSUE TITLE
gpio Binary Sensor triggers randomly in 1.14.3

### ISSUE THREAD

**Issue by aimartin** [esphome/issues#958]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

  platform: ESP32
  board: lolin_d32

**Affected component:**

GPIO Binary Sensor
https://esphome.io/components/binary_sensor/gpio.html?highlight=gpio
binary_sensor:
  - platform: gpio
    pin: 4
    name: "Movimiento Pasillo Superior"
    device_class: motion

**Description of problem:**
I've been using ESPHome in a LOLIN32 ESP32 chip since a while, with a HC-SR505 PIR movement sensor, and that worked perfect with 1.13.6. However, since I updated to 1.14.3, the sensor triggers randomly, showing movement when there is no movement. Moving back to 1.13.6 seems to have fixed the issue.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: planta_superior
  platform: ESP32
  board: lolin_d32

wifi:
  ssid: "WLAN_NOT"
  password: "SUPER_SECRET_PASSWORD"
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  safe_mode: True

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0,4,8,12,16,20
        days_of_week: MON-SUN
        then:
           - switch.toggle: reboot

esp32_ble_tracker:  

switch:
  - platform: restart
    id: reboot
    name: "ESP Restart"

binary_sensor:
  - platform: gpio
    pin: 4
    name: "Movimiento Pasillo Superior"
    device_class: motion
    
sensor:
  - platform: adc
    pin: 32
    name: "Iluminacion Pasillo Superior"
    update_interval: 30s
    unit_of_measurement: lx
    attenuation: 11db
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
          
  - platform: xiaomi_mijia
    mac_address: 4C:65:A8:D3:XX:XX
    temperature:
      name: "Xiaomi Despacho Aitor Temperatura"
    humidity:
      name: "Xiaomi Despacho Aitor Humedad"
    battery_level:
      name: "Xiaomi Despacho Aitor Bateria"


```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
