### ISSUE TITLE
Xiaomi CGG1 - same model, another firmware (again!)

### ISSUE THREAD

**Issue by mario-tux** [esphome/issues#959]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP32

**Affected component:**  https://esphome.io/components/sensor/xiaomi_cgg1.html

**Description of problem:**

As in https://github.com/esphome/issues/issues/799 I've just found that the just-bought fifth Xiaomi ClearGlass sensor (CGG1) doesn't report any sampling to esphome. I can't see it in the BLE scan but nothing is reported to HA. The other four items I got work well with the recent refactoring of the BLE xiaomi components.
Following the previous report, I've tried to investigate on the data packet. This is an example:

``50.20.47.03.1A.67.3A.10.34.2D.58.0D.10.04.C0.00.4F.02.0A.10.01.5A``

The MAC address of my item is ``58:2D:34:10:3A:67``. The only change looks related to the header: ``50.20.47.03`` instead of ``50.30.47.03``.

I will try to arrange and test a PR soon.

**Problem-relevant YAML-configuration entries:**
```yaml
  - platform: xiaomi_cgg1
    mac_address: 58:2D:34:10:3A:67
    temperature:
      name: "Xiaomi CG 3 Temperature"
    humidity:
      name: "Xiaomi CG 3 Humidity"
    battery_level:
      name: "Xiaomi CG 3 Battery"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
