### ISSUE TITLE
Binary sensor sometimes does not see state changes

### ISSUE THREAD

**Issue by deece** [esphome/issues#961]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

https://esphome.io/components/binary_sensor/gpio.html

**Description of problem:**
I have a Sonoff mini on every light circuit in my house. They all have local toggling via GPIO4.

Occasionally, the bathroom and ensuite modules get themselves into a state where local switch toggles do not turn off the relay. Home assistant does not see these state transistions either.

This can be fixed by restarting the module, or by changing the relay state of off via Home Assistant.

Both of these circuits have both a light and a small fan connected. I don't see this problem on other circuits that only have a light.

This problem persists on ESPHome 1.14.3 and earlier versions.

**Problem-relevant YAML-configuration entries:**
```
esphome:
  name: bathroom_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "redacted"
  password: "redacted"
  fast_connect: true
  domain: .theloft

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "redacted"

ota:
  password: "redacted"

status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay_1

  - platform: gpio
    name: "Bathroom Light Switch"
    pin: GPIO04
    id: switch_1
    on_press:
      then:
        - switch.toggle:
            id: relay_1
    on_release:
      then:
        - switch.toggle:
            id: relay_1

switch:
  - platform: gpio
    name: "Bathroom Light"
    icon: "mdi: lightbulb_outline"
    pin: GPIO12
    id: relay_1
    restore_mode: restore_default_off
```

**Logs (if applicable):**

**Additional information and things you've tried:**

Replaced Sonoff mini modules
