### ISSUE TITLE
Web Server Events feed only outputs first 7 states

### ISSUE THREAD

**Issue by rudshep** [esphome/issues#962]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip on Windows 10

**ESP (ESP32/ESP8266, Board/Sonoff):**

esp01_1m

**Affected component:**

https://esphome.io/components/web_server.html

**Description of problem:**
The Web Server dashboard shows all the sensors in the config but when there are more than 7,
some of the components don't show state in the UI anymore.

The names are there, but the State cell is blank.

It looks like the /events feed only outputs the first 7 states and Sensors take precedence.
In other words, if you add 7 Sensors, Switches and TextSensors and further Sensors get "pushed out".

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: demo_web_server_bug
  comment: Demo the web server bug
  platform: ESP8266
  board: esp01_1m

api:
logger:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time


switch:
  - platform: template
    id: switch1
    name: "Switch 1"

  - platform: template
    id: switch2
    name: "Switch 2"

  - platform: template
    id: switch3
    name: "Switch 3"

text_sensor:
  - platform: wifi_info
    ip_address:
      id: wifi_ip
      name: "IP Address"
    ssid:
      id: wifi_ssid
      name: "SSID"
    bssid:
      id: wifi_bssid
      name: "BSSID"
   
sensor:
  - platform: wifi_signal
    id: wifi_sig
    name: "RSSI"
    update_interval: 60s
  
  # Below are a few dummy sensors to fill up the component count.
  # Notice that when dummy1 is uncommented and included, BSSID no longer shows a value.
  # When dummy2 is included, SSID shows blank.
  # When dummy3 is included, IP Address shows blank.
  # When dummy4 is included, Switch3 no longer shows a state.
  #
  # So, it looks like the Events feed in the web server only outputs the states of the first 7 components and
  # Sensors take precendence over everything else.

  # Uncomment these out one by one to see the others being "pushed out" of the Events feed.
  #- platform: template
  #  id: dummy1
  #  name: "Dummy Sensor 1"

  #- platform: template
  #  id: dummy2
  #  name: "Dummy Sensor 2"

  #- platform: template
  #  id: dummy3
  #  name: "Dummy Sensor 3"

  #- platform: template
  #  id: dummy4
  #  name: "Dummy Sensor 4"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
This started with a UDP component I am building that casts the state of one sensor over UDP to another node (like a peer-to-peer scenario). I use the web server to monitor the state of the sensors on the various nodes. At first I thought the JSON payload in a TextSensor was breaking the web server (it actually breaks the API client but that's another bug report) but after eliminating all of it, even the most basic of Template sensors will cause the issue as you can see in the YAML example. 

My C++ knowledge is limited but I believe it could be something to do with how the WebServer::setup() function enumerates the components.
