### ISSUE TITLE
pulse_counter force_update not working

### ISSUE THREAD

**Issue by J-Pipe** [esphome/issues#965]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome 1.14.3 Hass.io addon

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

pulse_counter (https://esphome.io/components/sensor/pulse_counter.html)
which inherits from sensor (https://esphome.io/components/sensor/index.html#config-sensor)

**Description of problem:**
Issue #842 was initially created for this, which was apparently fixed in release 1.14.3, but it is still not working for me. Using Node Red, I am not getting a state_changed event for my pulse counter when the value stays the same.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: pulse_counter
    name: "Water usage"
    unit_of_measurement: "Gal/min"
    icon: "mdi:water"
    id: pin_1
    count_mode:
      rising_edge: INCREMENT
      falling_edge: INCREMENT
    pin:
      number: 5
      mode: INPUT_PULLUP
      inverted: true
      #inverted: false
    internal_filter: 10ms
    update_interval: 60s
    accuracy_decimals: 3
    force_update: true
    filters:
      - multiply: .5
      - multiply: .075

```
