### ISSUE TITLE
Compiler Segment Fault (The return of #677)

### ISSUE THREAD

**Issue by eboston** [esphome/issues#974]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

RPi4 buster
Hassio in docker
D1 Mini & Generic ESP8266

**Affected component:**

Compiling

**Description of problem:**

INFO Reading configuration /config/esphome/test.yaml...
INFO Generating C++ source...
INFO Core config or version changed, cleaning build files...
INFO Deleting /data/test/.pioenvs
INFO Deleting /data/test/.piolibdeps
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/test
Processing test (board: d1_mini; framework: arduino; platform: espressif8266@2.2.3)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Looking for ESPAsyncTCP-esphome library in registry
LibraryManager: Installing id=6757 @ 1.2.2
ESPAsyncTCP-esphome @ 1.2.2 has been successfully installed!
Looking for ESPAsyncWebServer-esphome library in registry
LibraryManager: Installing id=6758 @ 1.2.6
ESPAsyncWebServer-esphome @ 1.2.6 has been successfully installed!
LibraryManager: Installing id=6757
Looking for AsyncTCP-esphome library in registry
LibraryManager: Installing id=6798
AsyncTCP-esphome @ 1.1.1 has been successfully installed!
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.6
|   |-- <ESPAsyncTCP-esphome> 1.2.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling /data/test/.pioenvs/test/src/esphome/components/api/api_connection.cpp.o
Compiling /data/test/.pioenvs/test/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/test/.pioenvs/test/src/esphome/components/api/api_pb2_service.cpp.o
xtensa-lx106-elf-g++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
*** [/data/test/.pioenvs/test/src/esphome/components/api/api_pb2.cpp.o] Error 4
Compiling /data/test/.pioenvs/test/src/esphome/components/api/api_server.cpp.o
========================== [FAILED] Took 6.13 seconds ==========================

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

esphome:
  name: test
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "none"
  password: "nonenone"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "CJeEQQsY5wyf"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

This started happening when I switch over from Hassio on HassOS to Hassio on Docker in Raspbian Buster.

The solution from #677 does not fix the problem.
