### ISSUE TITLE
moving devices to different subnet

### ISSUE THREAD

**Issue by nicoolaro** [esphome/issues#979]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io on Proxmox (intel NUC)
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 Generic
**Affected component:**

https://esphome.io/components/esphome.html?highlight=use_address#changing-esphome-node-name

**Description of problem:**
All my devices have static manual IP and are working great.
Now , I am trying to move all my devices to different subnet.
I changed static IP's and gateway   i also use "use_address" to point to old one as instructed in the manual. Afterwords i remove old IP in "use_address" and although ESP8266 is working it regenerates new sensors in Home Assistant (usually by adding "_2 " to the name ), and light in ESPHOME dashboard stays RED although logs work.

I am not sure how to approach this issue so HA does not generate double entries. 
Is there a guide i can follow?
**Problem-relevant YAML-configuration entries:**
```yaml

wifi:
  ssid: "******"
  password: !secretwifi_password
  manual_ip:
    static_ip: 192.168.20.102
    gateway: 192.168.20.1
    subnet: 255.255.255.0
#  use_address: 192.168.1.48
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
