### ISSUE TITLE
OTA of esp32 fails.

### ISSUE THREAD

**Issue by michel72** [esphome/issues#98]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io 0.88.2, esphome 1.12.2 running on Ubuntu 18.04 in docker.
**ESP (ESP32/ESP8266, Board/Sonoff):**

Tried both the:
> New ESP 32 Lite V1.0.0 - wifi Module + bluetooth board based ESP-32 esp32 Rev1 4MB FLASH
and the:
> ESP-32S CP2102 Wireless WiFi Bluetooth Development Board Micro USB Dual Core Power Amplifier Filter Module

**Affected component:**

OTA flashing

**Description of problem:**

OTA flashing of the esp32 does not work (anymore).

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp32miflora01
  platform: ESP32
  board: esp32dev

wifi:
  ssid: 'xxxxxxx'
  password: 'xxxxxxxxxxxxxxxxxx'

api:

logger:

ota:

esp32_ble_tracker:

sensor:
### Plant1 MAC: C47C8D672CE6 ## Plant ras: Yucca
  - platform: xiaomi_miflora
    mac_address: C4:7C:8D:67:2C:E6
    temperature:
      name: "Plant1 temperatuur"
    moisture:
      name: "Plant1 vochtigheid"
    illuminance:
      name: "Plant1 licht"
    conductivity:
      name: "Plant1 geleiding"
    battery_level:
      name: "Plant1 batterij"

### Plant2 MAC: C47C8D672CA7 ## Plant ras: Ficus Bonzai
  - platform: xiaomi_miflora
    mac_address: C4:7C:8D:67:2C:A7
    temperature:
      name: "Plant2 temperatuur"
    moisture:
      name: "Plant2 vochtigheid"
    illuminance:
      name: "Plant2 licht"
    conductivity:
      name: "Plant2 geleiding"
    battery_level:
      name: "Plant2 batterij"
      
### Plant3 MAC: C47C8D672719 ## Plant ras: Dracaena
  - platform: xiaomi_miflora
    mac_address: C4:7C:8D:67:27:19
    temperature:
      name: "Plant3 temperatuur"
    moisture:
      name: "Plant3 vochtigheid"
    illuminance:
      name: "Plant3 licht"
    conductivity:
      name: "Plant3 geleiding"
    battery_level:
      name: "Plant3 batterij"
      
### Plant4 MAC: C47C8D672E68 ## Plant ras: Dracaena maginata
  - platform: xiaomi_miflora
    mac_address: C4:7C:8D:67:2E:68
    temperature:
      name: "Plant4 temperatuur"
    moisture:
      name: "Plant4 vochtigheid"
    illuminance:
      name: "Plant4 licht"
    conductivity:
      name: "Plant4 geleiding"
    battery_level:
      name: "Plant4 batterij"
```

**Traceback (if applicable):**

```
...
Retrieving maximum program size .pioenvs/esp32_miflora/firmware.elf
Checking size .pioenvs/esp32_miflora/firmware.elf
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [==        ]  23.6% (used 77292 bytes from 327680 bytes)
PROGRAM: [========  ]  84.6% (used 1386510 bytes from 1638400 bytes)
========================= [SUCCESS] Took 3.52 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of esp32_miflora.local
INFO  -> 192.168.2.99
INFO Uploading /config/esphome/esp32_miflora/.pioenvs/esp32_miflora/firmware.bin (1386752 bytes)
Uploading: [====                                                        ] 6% 
ERROR Error sending data: timed out
```

**Additional information and things you've tried:**

I have tried 2 different esp32's, tried different configurations and even een totally different setup of home assistant (also on ubuntu docker) but both fail.
