### ISSUE TITLE
Direction doesn't always work

### ISSUE THREAD

**Issue by EverythingSmartHome** [esphome/issues#980]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io and Pip
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32, ESP8266 and Wemos D1 Mini
**Affected component:**

https://esphome.io/components/stepper/index.html

**Description of problem:**
When toggling the stepper motor open or closed, it works as expected through multiple tries. Then if I physically leave the stepper connected for a while (not sure how long) and come back, when I toggle open or close, the stepper will only rotate in one direction. The console shows "open" and "closed" correctly, but the stepper will only move in the one direction. At first I thought I'd made a mistake with the wiring but I kept getting this intermittently over a few days.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: livingroom_curtain
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: XXX
  password: XXX
  domain: XXX

logger:

ota:
  password: XXX

web_server:
  port: 80

api:
  services:
    - service: control_blind
      variables:
        target: int
      then:
        - stepper.set_target:
            id: my_stepper
            target: !lambda 'return target;'
        - sensor.template.publish:
            id: position
            state: !lambda 'return target;'

cover:
  - platform: template
    name: "Livingroom Curtains"
    id: livingroom_curtains
    device_class: blind
    open_action:
      - stepper.set_target:
          id: my_stepper
          target: 0
      - sensor.template.publish:
          id: position
          state: !lambda return id(my_stepper).current_position;
    close_action:
      - stepper.set_target:
          id: my_stepper
          target: 1000
      - sensor.template.publish:
            id: position
            state: !lambda return id(my_stepper).current_position;
    stop_action:
      - stepper.set_target:
          id: my_stepper
          target: !lambda return id(my_stepper).current_position;
      - sensor.template.publish:
            id: position
            state: !lambda return id(my_stepper).current_position;
    optimistic: true
    assumed_state: true

sensor:
  - platform: template
    name: "Livingroom Curtain Position"
    id: position

stepper:
  - platform: a4988
    id: my_stepper
    step_pin: D6
    dir_pin:
      number: D5
      inverted: false 
    max_speed: 250 steps/s

    # Optional:
    sleep_pin: D7
    acceleration: inf
    deceleration: inf


```

**Logs (if applicable):**

```

```

**Additional information and things you've tried:**
I'm not sure if this is a bug or not, the issue is kind of intermittent and frustrating but not sure where the issue lies. Please let me know if you need any more information.
