### ISSUE TITLE
esp32_camera dump_config missing logic for FRAMESIZE_QXGA

### ISSUE THREAD

**Issue by tathamoddie** [esphome/issues#984]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**Affected component:**

https://esphome.io/components/esp32_camera.html

**Description of problem:**
When compiling firmware that uses the `esp32_camera` component, I'm getting these compilation warnings from ESPHome v1.14.3:

```
src/esphome/components/esp32_camera/esp32_camera.cpp: In member function 'virtual void esphome::esp32_camera::ESP32Camera::dump_config()':
src/esphome/components/esp32_camera/esp32_camera.cpp:54:10: warning: enumeration value 'FRAMESIZE_QXGA' not handled in switch [-Wswitch]
   switch (this->config_.frame_size) {
          ^
src/esphome/components/esp32_camera/esp32_camera.cpp:54:10: warning: enumeration value 'FRAMESIZE_INVALID' not handled in switch [-Wswitch]
```

This seems to refer to this `switch` statement, which is indeed missing an entry for `FRAMESIZE_QXGA`:

https://github.com/esphome/esphome/blob/064589934cd3df5d582563f6120f4fc9b8b9c717/esphome/components/esp32_camera/esp32_camera.cpp#L54-L90

**Problem-relevant YAML-configuration entries:**
```yaml
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: Camera 1

```
