### ISSUE TITLE
Uptime sensor counts on wifi connect

### ISSUE THREAD

**Issue by sti0** [esphome/issues#996]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 and WeMos D1 Mini Pro (with external antenna)

**Affected component:**

Uptime sensor
https://esphome.io/components/sensor/uptime.html

**Description of problem:**
I like to use an ESP at my car to auto open the garage door if I arrive at home. If the car is started and parked on the outside the garage door should not open. For this behavior I like to use the uptime sensor. If the uptime sensor is >= 240 seconds the garage door should open. If it's less nothing happens (= car started). On my test drives the uptime sensor seems to start (new) counting after wifi connect. I drive for 5 minutes (=300 sconds) and come back home. I receive a notification that the ESP is online (published by MQTT) but the uptime sensor is not ready yet. What I can see is that if the car arrives and den ESP connected to wifi the uptime sensor starts from 0. That's not what I'm expected.

**Problem-relevant YAML-configuration entries:**
```
esphome:
  name: car_opener
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: true
  reboot_timeout: 0s
  manual_ip:
    static_ip: 192.168.XXX.XXX
    gateway: 192.168.XXX.XXX
    subnet: 255.255.XXX.XXX
  ap:
    ssid: !secret wifi_fallback_ssid
    password: !secret wifi_fallback_pwd

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphomeota
  reboot_timeout: 0s
  
ota:
  password: !secret esphomeota

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  client_id: 'car'
  keepalive: 2s
  reboot_timeout: 0s
  discovery: false
  topic_prefix: 'home/garage_opener/car'

sensor:
  - platform: uptime
    name: "car_garage_opener_uptime"
    id: sensor_uptime
    update_interval: 1s
  - platform: wifi_signal
    name: "astra_garage_opener_wifi_strength"
    update_interval: 5s
    state_topic: 'home/garage_opener/car/sensor/wifi_signal/state'

binary_sensor:
  - platform: status
    name: "car_garage_opener"
  - platform: template
    name: uptime_grt240s
    id: uptime_grt240s
    state_topic: 'home/garage_opener/car/binary_sensor/uptime_grt240s/state'
    lambda: |-
      if (id(sensor_uptime).state >= 240) {
        return true;
      } else {
        return false;
      }

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```
=> Because I'm in the car I can't provide debug logs. If I connect the ESP at home it connects instantly to wifi and starts counting. But thats not the behavior as it is when I'm on the ride.

**Additional information and things you've tried:**
![image](https://user-images.githubusercontent.com/18382402/72652286-733d0080-3986-11ea-8d2f-a92edcdf8b89.png)
